### ISSUE TITLE
Test Variable Name Change: Pass Arguments to Avoid External Dependence in a Function

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39423]
**Describe your problem and how to reproduce it:**
The following code does not pass, because the test has a variable name which is the same:
```
// the global variable
var fixedValue = 4;

// Add your code below this line
function incrementer(value) {
  return value + 1;

  // Add your code above this line
}

var newValue = incrementer(fixedValue); // Should equal 5
console.log(fixedValue); // Should print 4
```
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/pass-arguments-to-avoid-external-dependence-in-a-function

Solution:
Change variable name of [this test](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/pass-arguments-to-avoid-external-dependence-in-a-function.english.md) from:
```
testString: const newValue = incrementer(fixedValue); assert(newValue === 5);
```
to
```
testString: const __newValue = incrementer(fixedValue); assert(__newValue === 5);
```

To make it less likely someone uses the same variable name.

**Comment by Shrman007658** [comment]
Hey! I am a beginner in open source programming. Can I take this issue up?
Thanks.

**Comment by Sky020** [comment]
@Shrman007658 , Yes you may have a go at this. To begin, you should go through the [contributing docs](https://contribute.freecodecamp.org/#/index), if you have not already.

Some things to highlight:
- We do not typically assign issues
- If an issue has _help wanted_ or _first timers only_ labels, then they are open for contribution
- The first PR which closes the issue will be accepted

If you have any questions about contributing in general, or setting up fCC locally, the [Contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3), and the [Gitter Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) are excellent places to start.
