### ISSUE TITLE
embed bilibili video for Chinese publication articles

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#39437]
**Is your feature request related to a problem? Please describe.**
I can only add a video URL now.

**Describe the solution you'd like**
Could you add "embed bilibili video" to the editor? Thanks!

**Comment by raisedadead** [comment]
Can you post a sample video URL and we can check what's needed?

**Comment by miyaliu666** [comment]
> Can you post a sample video URL and we can check what's needed?

This one: https://www.bilibili.com/video/BV1UC4y1a78j
Thanks!

**Comment by raisedadead** [comment]
Here is the iframe that should be genrated by the theme:

`<iframe src="//player.bilibili.com/player.html?aid=796086221&bvid=BV1UC4y1a78j&cid=205208423&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>`

**Comment by raisedadead** [comment]
This might be something that Ghost would need to support upstream first, I will let Ahmad do the research.

**Comment by scissorsneedfoodtoo** [comment]
Hi @miyaliu666, thanks for your patience.

I dug into this a little bit today and think I found a simple fix. I'll create a PR and leave instructions on how to get responsive Bilibili embeds there.
