### ISSUE TITLE
Waypoint: Generate Random Fractions with JavaScript

### ISSUE THREAD

**Issue by eagle122** [FreeCodeCamp/FreeCodeCamp#3943]
Challenge [Waypoint: Generate Random Fractions with JavaScript](http://www.freecodecamp.com/challenges/waypoint-generate-random-fractions-with-javascript#?solution=function%20myFunction()%20%7B%0A%20%20%2F%2F%20Change%20the%200%20to%20Math.random().%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%200%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A%0A%2F%2F%20We%20use%20this%20function%20to%20show%20you%20the%20value%20of%20your%20variable%20in%20your%20output%20box.%0A(function()%7Breturn%20myFunction()%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/7.1.7 Safari/537.85.16</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  // Change the 0 to Math.random().
  // Only change code below this line.

  return 0;

  // Only change code above this line.
}

// We use this function to show you the value of your variable in your output box.
(function(){return myFunction();})();

```
I couldn't find a place for the issue I'm having.  I can not click on "help" or any of the links att he top right of the page.  I click on them and nothing happens  The only 2 links I can get to work is the "Freecodecamp" link and "bug"  I tried shutting down. I tried reset.  This just started like 2 lessons ago  I worked find up til then.  Any ideas??

**Comment by eagle122** [comment]
This just started like 2 lessons ago I worked find up til then. Any ideas??  (should read)
It worked fine up til then

**Comment by ltegman** [comment]
Are you getting any errors in your developer console?

**Comment by eagle122** [comment]
nothing that a ; or capital letter doesn't take care of.  but i needed help on this lesson but i can get the help link to work

**Comment by eagle122** [comment]
here is a screenshot if it is helpful.  there is an error there but i think its cause i need help with the code
<img width="1440" alt="screen shot 2015-10-28 at 3 30 19 pm" src="https://cloud.githubusercontent.com/assets/13139039/10805152/ef8f8fb8-7d88-11e5-841d-9f29d0048522.png">

**Comment by ltegman** [comment]
Unfortunately I'm not able to repro and I don't have any hunches on what would be causing this. Leaving this open in case someone else has any ideas or can repro.

**Comment by eagle122** [comment]
thank you.  i really need help here for both the lesson and this problem

**Comment by BerkeleyTrue** [comment]
Your code has an infinite loop. You are calling `myFunction` within `myFunction`.

**Comment by ltegman** [comment]
If you need help, the help link simply opens the gitter chat at https://gitter.im/FreeCodeCamp/Help

**Comment by eagle122** [comment]
Please reread the issue from the beginning.  The issue is I can NOT click on the help link or any of the links in the upper right hand corner.  This just started.  I can not go to the help desk because when I click on help it doesn't respond...At all

**Comment by bugron** [comment]
@eagle122 try resetting the code one more time. If that won't help try [How to clear specific values from your browser's local storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser%27s-local-storage) or [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).
Closing as not an issue with the tests. Feel free to reopen if you still experience problems, thanks.

**Comment by ferhotguy** [comment]
function randomFraction() {
 
  // Only change code below this line.

  return Math.random();

  // Only change code above this line.
}

// We use this function to show you the value of your variable in your output box.
(function(){return randomFraction();})();

**Comment by niksolaz** [comment]
## I created a local variable and returned. 
`
function randomFraction() {

  // Only change code below this line.
  **var result = Math.random()*10;**
  return **result**;

  // Only change code above this line.
}
`

**Comment by hrithick** [comment]
function randomFraction() {

  // Only change code below this line.
value=Math.random();
  return value;

  // Only change code above this line.
}

**Comment by ohmiler** [comment]
`function randomFraction() {

  // Only change code below this line.
  Math.random();
  return 2.122323;

  // Only change code above this line.
}`

**Comment by cubancigaro** [comment]
try only changing the return line.

**Comment by flippss** [comment]
@ohmiler what 2.122323 means?

**Comment by ohmiler** [comment]
Just a custom float number you can use them :D

2017-01-07 22:57 GMT+07:00 Francesco Lippolis <notifications@github.com>:

**Comment by charlieprather** [comment]
You can make a variable within the function and set it to Math.random(); then proceed to follow the instructions.
