### ISSUE TITLE
[BUG] - Quality Assurance projects have user stories related to Information Security

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39435]
**Describe your problem and how to reproduce it:**

With the roll-out of the Python curriculum, the full stack curriculum was restructured and Information Security was split off from the Quality Assurance section and given its own section. However, three of the Quality Assurance projects still include user stories that expect features associated with the `helmet.js` learning - that is now covered under the Information Security section. 

This *may* be something that falls under expecting campers to do their own research, but it seems worth considering the removal of these user stories.

**Add a Link to the page with the problem:**
[Metric Imperial Converter](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter)
[Issue Tracker](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker)
[Personal Library](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/personal-library)

**Comment by ojeytonwilliams** [comment]
Thanks for bringing this up, Nicholas.  If the info sec certificate came before QA this would be less of a problem, but right now those user stories do seem out of place.

cc @scissorsneedfoodtoo @RandellDawson

**Comment by moT01** [comment]
Any thoughts on this @RandellDawson @Sky020 @scissorsneedfoodtoo?

**Comment by Sky020** [comment]
I agree with removing the test related to any Helmetjs content

>and/or the project you can fork on repl.it. Not sure on those last two.


From what I can tell, the link to a Repl of the boilerplate is just a direct method to clone the GitHub boilerplate. So, just the READMEs and `views/index.html` would need to be changed as well.

**Comment by scissorsneedfoodtoo** [comment]
@nhcarrigan, thanks for bringing this up and sorry for the late response.

I'm all for removing these user stories from the projects because Info Sec isn't covered in any of the practice projects. We discussed this internally before breaking the original QA and Infosec certificate up and decided to leave them in at the time, but I always felt a bit iffy about it.

**Comment by moT01** [comment]
There should be three parts to this:

- [ ] Remove tests/text from /learn pages
- [ ] Remove text from boilerplates
- [ ] Remove text from example projects

**Comment by moT01** [comment]
I think we might be able to close this. The user stories are removed on master (/learn), and as we implement the changes for https://github.com/freeCodeCamp/freeCodeCamp/issues/39721, they should all be removed.

**Comment by RandellDawson** [comment]
@nhcarrigan Are you fine with closing this issue and adding any relevant information as a comment to issue #39721?

**Comment by nhcarrigan** [comment]
Sure thing. 

@SaintPeter and I worked together on a few of these items and I believe everything has been caught, but I'll make a note on the other issue to ensure it doesn't get lost in the shuffle. 🙂
