### ISSUE TITLE
Array.prototype.every() explanation 

### ISSUE THREAD

**Issue by najmieh** [freeCodeCamp/freeCodeCamp#39441]
**in the 3rd solution on the hint section we have this explanation:  For every object in the collection array, check the truthiness of object’s property passed in pre parameter
Array#every method internally checks if the value returned from the callback is truthy.
Return true if it passes for every object. Otherwise, return false.  
**

**https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-everything-be-true/16011**

**Recommended fix, suggestions (how would you update it?): I think the second bullet has a misspelling.  It should go something like "Array.prototype.every() or in the case of this solution collection.every method internally checks if the value returned from the callback is truthy. **

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Thank you, for pointing this out.

I have updated the guide post with `Array.prototype.every` for clarity. As such, I am closing this issue.
