### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39453]
To better support contributors using Windows we should add CI tests running on that OS.

They should catch these kinds of issues: https://github.com/freeCodeCamp/freeCodeCamp/issues/39451

**Comment by ojeytonwilliams** [comment]
@raisedadead we're not going in this direction, right?  I assume so from the discussion on the PR, but if I'm being stupid, please re-open this.

**Comment by raisedadead** [comment]
Yes - We are not going to support native dev on Windows.
