### ISSUE TITLE
"Sudoku Solver" project has an error "setGrid is not defined" when user changes data inside textarea

### ISSUE THREAD

**Issue by randomSveta** [freeCodeCamp/freeCodeCamp#39468]
**Description:**
There is an issue “ReferenceError: setGrid is not defined” in “Sudoku Solver” https://sudoku-solver--freecodecamp.repl.co/ example project when a user enters/changes/removes data inside. Also, if data inside textarea was changed no changes apply to the sudoku grid. I suppose the second issue is because of the first.

* Browser Name:  Firefox
* Browser Version: 79.0 (64-bit)
* Operating System: macOS Catalina 10.15.6

**Steps:**

    Go to -> https://sudoku-solver--freecodecamp.repl.co/
    Open Dev Tools -> Console in browser
    Go to the page and find the textarea with the sample sudoku string and two buttons (Solve and Clear)
    Change data inside the textarea: remove/change/add any symbol.
    (I removed last 34 positions)
    Check the console for errors, check sudoku grid for changes

**Actual result:**
You can see an error in console.

Uncaught ReferenceError: setGrid is not defined
oninput https://sudoku-solver--freecodecamp.repl.co/:1
sudoku-solver–freecodecamp.repl.co:1:1
Uncaught ReferenceError: setGrid is not defined
oninput https://sudoku-solver--freecodecamp.repl.co/:1 

![sudoku-solver-error-setGrid-is-not-defined](https://user-images.githubusercontent.com/38963057/91212639-67799f80-e708-11ea-89c0-d83ff7f30a83.png)

The grid is not updated after changes:
![sudoku-solver-grid-not-updated](https://user-images.githubusercontent.com/38963057/91212643-69436300-e708-11ea-90c0-d2fd802e6b1b.png)

**Expected result:**
No error about setGrid is not defined.
If textarea was changed then changes should be applied to the grid.

**Comment by kelvinsanchez15** [comment]
I also realized this today when I was looking for a way to solve the project.

I was able to get it working by adding an event listener to textArea and a handler function.

```
const onInputHandler = (e) => {
  const str = e.target.value;
  setGrid(str);
};

textArea.addEventListener("input", onInputHandler);
```

This way, there's no need to use the `oninput` attribute that is within the textarea of the index.html file.

I have not contributed to open source projects yet, but I hope my comment can be of help to solve this issue.

**Comment by pankajboruah** [comment]
As the error message suggests, the function `setGrid` is not recognized. This might be because it's not getting imported.
While using type="module", the function needs to be imported like this: 
```
<script type="module">
  import {sayHi} from './say.js';

  document.body.innerHTML = sayHi('John');
</script>
```
Or better just remove type="module" from the script tag.

**Comment by nhcarrigan** [comment]
This issue appears to be fixed in the new [demo project](https://sudoku-solver.freecodecamp.rocks/). As such, we are going to close the issue. If you feel this has been done in error, feel free to request that it be reopened and provide all relevant information. 🙂
