### ISSUE TITLE
REPL.it Sample Projects Unavailable

### ISSUE THREAD

**Issue by shartrooper** [freeCodeCamp/freeCodeCamp#39467]
**Describe your problem and how to reproduce it:**
Hello.
Currently, the Url for the Personal Library challenge sample project cannot reach its Repl.it

**Add a Link to the page with the problem:**

Sample Project Repl.it URL: [QA Personal Library](https://personal-library--freecodecamp.repl.co/)
**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox
* Browser Version: Latest
* Operating System: Windows 7 Ultimate

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by nhcarrigan** [comment]
A couple of additional errors:

[Issue Tracker](https://issue-tracker--freecodecamp.repl.co/) - Returns a page that says "project started".
[Personal Library](https://personal-library--freecodecamp.repl.co/) - Returns a 404 error from repl.it
[American British Translator](https://americanbritish-english-translator--freecodecamp.repl.co/) - This one just won't connect for me.

**Comment by Sky020** [comment]
I am able to access the _Issue Tracker_ and _American British Translator_, without any problems.

**Comment by RandellDawson** [comment]
@nhcarrigan I can reach the Issue Tracker and American British Translator, but definitely can not reach the Personal Library.

@Sky020 Do you know if that is the correct url?  We QA'd that PR and all the links seem to work fine the other day.

**Comment by nhcarrigan** [comment]
Giving it another shot, I was finally able to access those two projects. Not sure what the cause of the error was. 🤔

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo Seems like we are getting some sporadic access issues to some of the projects?

**Comment by Sky020** [comment]
> Do you know if that is the correct url? We QA'd that PR and all the links seem to work fine the other day.

I do remember it working. So, it definitely took the browser somewhere.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/91227074-c6c0bb00-e6da-11ea-893d-108cc6a2a558.png)

This is where it takes me...

**Comment by Sky020** [comment]
I can get to it by going to https://repl.it/@freeCodeCamp then https://repl.it/@freeCodeCamp/Personal-Library

This leads me to a project link of: https://Personal-Library.freecodecamp.repl.co which needs to be run-up

**Comment by RandellDawson** [comment]
@Sky020 Even after going through the steps and clicking Run, the page that shows is still what @nhcarrigan shows above.

The page should show something like was on Glitch:

![Screenshot from 2020-08-25 14-28-24](https://user-images.githubusercontent.com/5313213/91229841-5b2d1c80-e6df-11ea-9c1c-1dc711e30726.png)


Also, there is a separate issue in that the `this link` link points to `https://repl.it/github/freeCodeCamp/boilerplate-project-metricimpconverter` instead of the the personal library boilerplate.

**Comment by Sky020** [comment]
I got it to run by adding a `.env` with a PORT and DB string. So, the code works.

How does fCC keep the servers alive for the example projects?

**Comment by scissorsneedfoodtoo** [comment]
Hi @shartrooper, thanks for reporting this.

Not sure what happened here. I'll reach out the Repl.it team to see why this project was unavailable. To fix it, I just opened the project under the official fCC account and clicked the "Run" button.

@Sky020, it's my understanding that Repl.it projects work similarly to ones on Glitch. The servers spin down after awhile, then restart when someone goes to the link to the application (https://issue-tracker--freecodecamp.repl.co/, https://personal-library--freecodecamp.repl.co/).

**Comment by shartrooper** [comment]
It's currently reaching the app now. Did running the app fixed the issue?.

**Comment by scissorsneedfoodtoo** [comment]
Hi @shartrooper, thank you for reporting this issue. Also, thanks everyone else for checking the other projects. Not sure if this is a problem on our end or not, but I've reached out to the Repl.it team in the meantime.

Please feel free to open a new issue if you find that another project is unreachable.

**Comment by Obaida-Albaroudi** [comment]
Hey Folks, I am Obaida from Repl.it. Appreciate you all reaching out to Kris with these issues. I will go ahead and look into this and keep you all posted with any updates I may have! Also always feel free to raise the issues here as well https://repl.it/bugs.

**Comment by RandellDawson** [comment]
@Obaida-Albaroudi We have another demo project that stopped working.

https://metric-imperial-converter--freecodecamp.repl.co/

**Comment by Obaida-Albaroudi** [comment]
@RandellDawson Thanks for flagging! I looked at the base code real quick and it seems like you are calling process.env.PORT with no env file. I believe that should fix the problem, please let me know if you are still having issues and I can dive into this a little more.

**Comment by scissorsneedfoodtoo** [comment]
Hi @Obaida-Albaroudi, thanks for taking a look at this project.

I went in and added the `.env` file, but I don't think it was necessary for the project, and was only used to set the port and whether or not tests run automatically. There's a fallback if `process.env.PORT` returned `undefined`, so the project was working until recently.

Still, that could be why the project stopped working here. Maybe there needs to be a `.env` file if `process.env...` is used anywhere? Are there any logs on your end that might give us more info about why the project was unreachable?

**Comment by Obaida-Albaroudi** [comment]
Hey, apologies you were definitely right and the env file had nothing to do with it. I dug into it a little more and was able to determine the issue with the help of the team. The app is running with no issues, matter of fact you should be able to open it up in a new tab. Unfortunately the issue is the web view won't open up in the repl page your on because you set X-Frame-Options: sameorigin (probably in the “helmet” package). 

<img width="550" alt="Screen Shot 2020-09-03 at 12 53 50 PM" src="https://user-images.githubusercontent.com/47952680/92161908-265b4c80-ede6-11ea-92ff-2d85b41a5ea9.png">

**Comment by scissorsneedfoodtoo** [comment]
@Obaida-Albaroudi, awesome, thank you for looking into that. Is there anything we can do on our end with this project and the others to prevent this issue in the future?

About the web view being unavailable, that should be okay for some projects that require Helmet with those settings. We can do a deeper audit to make sure only the projects with those specific user stories are affected, and that the web view works for everything else.

**Comment by Sky020** [comment]
@scissorsneedfoodtoo and @Obaida-Albaroudi ping

This is still (once again) an issue for: https://issue-tracker--freecodecamp.repl.co/

**Comment by RandellDawson** [comment]
This project is back up and running again.
