### ISSUE TITLE
Display issue with completion modal

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39476]
**Describe the bug**
The completion model buttons are not correctly aligned.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/learn/
2. Log out.
3. Go to https://www.freecodecamp.dev/learn/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements
4. Complete the challenge
5. Click run tests
6. See error

**Screenshots**
![SignIn](https://user-images.githubusercontent.com/15801806/91337800-3bc3eb80-e7d4-11ea-9396-003987fe1d87.png)

This is only on the development server, probably created by the css changes introduced by the landing page redesign.

**Comment by nhcarrigan** [comment]
I am able to confirm this bug. Looking at the elements:

The Go To Next Challenge button has a left margin of 5px.
![image](https://user-images.githubusercontent.com/63889819/91338048-2bd2ea00-e789-11ea-87e2-8d2428de88a4.png)

The Download My Solution button has a top margin of 5px.
![image](https://user-images.githubusercontent.com/63889819/91338140-50c75d00-e789-11ea-8442-d0161b48910f.png)
