### ISSUE TITLE
Code snippet highlights broken

### ISSUE THREAD

**Issue by Balagii** [freeCodeCamp/freeCodeCamp#39472]
**Describe your problem and how to reproduce it:**
I was reading https://www.freecodecamp.org/news/how-did-i-miss-javascript-symbols-c1f1c0e1874a/ on latest Chrome. Every code snippet in the article had a grey background for highlight EXCEPT for the last couple characters of each multiline snippets

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/how-did-i-miss-javascript-symbols-c1f1c0e1874a/

**Recommended fix, suggestions (how would you update it?):**
move the affected `</code>` tags a little farther to the right

**Comment by ahmadabdolsaheb** [comment]
Thanks for letting us know. I will share this with the editorial team.

**Comment by scissorsneedfoodtoo** [comment]
Hi @Balagii, thanks for reporting this. I went in and fixed all the code snippets, added syntax highlighting to many of them, and added some missing code snippets.

Here's the updated article: https://www.freecodecamp.org/news/how-did-i-miss-javascript-symbols-c1f1c0e1874a/
