### ISSUE TITLE
Having to stop/restart npm run develop when adding a new step in project-based curriculum

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39471]
Fixing this issue would speed up the process of viewing a new step after creating the necessary file when developing locally.  Currently, when a new step is added, you have to manually stop `npm run develop` and then run it again.  Depending on the user's machine, the total time wasted is between 60-120 seconds per new file created.  The wasted time is one thing, but it also stops the flow of continuous development of adding new steps.  When creating steps, it is much easier to stay focused when you do not have to interrupt the content creation process with extra steps that "should" work like when you make changes to other parts of the repo.

Need to figure out how to rebuild the pages each time a new file and/or the meta.json file is updated for a project.

**Comment by raisedadead** [comment]
I am moving this upto the current version with the linked PR as a partial solution given the limitations we discussed.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
