### ISSUE TITLE
A link to a "free" course is now premium.

### ISSUE THREAD

**Issue by MyNameIsAres** [freeCodeCamp/freeCodeCamp#39484]
**Describe your problem and how to reproduce it:**
An article suggests the first linked course is free. If you click on the link it brings you to a premium course. The course might have been free at the time of writing. However, it currently isn't. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/these-are-the-best-free-courses-to-learn-data-structures-and-algorithms-in-depth-4d52f0d6b35a/

The ''1. Easy to Advanced Data Structures'' course link brings you to the premium Udemy course.

**Recommended fix, suggestions (how would you update it?):**
Create a ''note'' or ''important'' header above the title; informing the reader this course is no longer free.

**Comment by QuincyLarson** [comment]
@MyNameIsAres Thanks for letting me know that this course is now paid. I moved it to the bottom of the article and noted that the course is no longer free.
