### ISSUE TITLE
Broken links in Record Collection solution.

### ISSUE THREAD

**Issue by MyNameIsAres** [freeCodeCamp/freeCodeCamp#39483]
**Problem description:**
Noticed the issue when helping someone with the Record Player challenge. Two links in the ''get a hint'' section are broken.
The ''add new properties to a JavaScript Object'' and ''Delete Properties from a JavaScript Object" links,  point to a 404 page with an incorrect url. 

https://www.freecodecamp.org/challenges/delete-properties-from-a-javascript-object 
-> should be: 
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/delete-properties-from-a-javascript-object

https://www.freecodecamp.org/challenges/add-new-properties-to-a-javascript-object
-> should be
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/add-new-properties-to-a-javascript-object

**Reproducing the error:**
Go to the "Record Collection" challenge. Click on "help" -> then ''get a hint'', and open the solution tab. The two broken links are there.

**Add a Link to the page with the problem:**
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-record-collection/18261

**Browser (version) and operating system:**
* Browser Name: Chrome
* Browser Version: 85.0.4183.83
* Operating System: Windows 10

Apologies if this isn't the best section to post this. Determined it was based the CoC and description. If this is incorrect then by all means, move it to the correct section.

**Comment by Sky020** [comment]
Thank you, for taking the time to help the freeCodeCamp community, by pointing this out.

I have updated the guide post's links.
