### ISSUE TITLE
InfoSec 5 multiplayer game project: broken tests

### ISSUE THREAD

**Issue by Gern-Yataro** [freeCodeCamp/freeCodeCamp#39481]
**Describe your problem and how to reproduce it:**
FCC Curriculum's Information Security 5: Secure Real Time Multiplayer Game Project test is completely broken, any link added to the testing screen passes all the tests.

Reproduce Steps:
1. Go to https://www.freecodecamp.org/learn/information-security/information-security-projects/secure-real-time-multiplayer-game.
2. Add any Repl.it project link to the "Solution" input.
3. Select "I've completed this challenge"

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security/information-security-projects/secure-real-time-multiplayer-game

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 84
* Operating System: Win10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screen1](https://user-images.githubusercontent.com/28675590/91530539-ddb31780-e93d-11ea-8fe8-824f4340db55.png)
![screen2](https://user-images.githubusercontent.com/28675590/91530550-e1469e80-e93d-11ea-96d3-16596a8940cd.png)
![screen3](https://user-images.githubusercontent.com/28675590/91530556-e4418f00-e93d-11ea-80cb-98e10fbb1c0b.png)

**Comment by Sky020** [comment]
I believe this should be added to: #37185

**Comment by moT01** [comment]
Thanks for reporting @Gern-Yataro. I am going to close this as a duplicate of the linked issue. Thanks and happy coding 🎉
