### ISSUE TITLE
Bonfire Proposal - Palindrome Number

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#3948]
### Find the number of palindromes between two given numbers i.e. between ***`N1`*** and ***`N2`***.

> It means to find the number of palindrome digits! between `1` to `1000`, etc.

e.g.
`727` is a palindrome
`818` is a palindrome
`11` is a palindrome
`94849` is a palindrome
`72937` is not a palindrome

Number of palindromes between `15` to `30` is `1` which is the number `22`.

**Comment by iTypeSlow** [comment]
I think that could be cool challenge!

**Comment by SaintPeter** [comment]
I really like this and I think it might make a good Bonfire.  Just not sure where it would fit or if its functionality is covered by other Bonfires.

**Comment by abhisekp** [comment]
@SaintPeter just the current palindrome solution will work with a wrapper!

**Comment by bugron** [comment]
Here is the solution of this hypothetical bonfire (a modification of Wiki solution):
```javascript
function palindrome(num) {
  var str = num.toString();
  var reverseStr = normalizedStr.split('').reverse().join('');
  return normalizedStr === reverseStr;
};

palindrome(555); // true
palindrome(456); // false
```
Actually this is the same palindrome challenge. I'm going to close this request but if someone is working on this let us know.

**Comment by abhisekp** [comment]
@bugron The bonfire is an enhancement to the palindrome bonfire. Please don't close it. Let it be open. Someone or I will build it.

**Comment by bugron** [comment]
OK, reopening then.

**Comment by ltegman** [comment]
Closing as stale. If someone wants to work on this they can let us know and we'll reopen, otherwise I'd rather not just have challenge suggestions languishing in our Github issues eternally. Thanks!
