### ISSUE TITLE
Update challenges with hint on how to get to the array

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#39486]
Challenges: 
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype

The assumption that the camper will know to use `this` inside the callback to get to the array is pretty unfounded in my opinion. The challenge text gives no hints or information about this what so ever.

I think this challenge should be updated to include some sort of hint, or just straight up tell the camper how to get to the array inside the callback.

**Comment by Sky020** [comment]
In a prior challenge, campers are taught about objects (the way I see it, everything in JavaScript boils down to an object), and how _methods_ of an object have access to the object via `this`:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/make-code-more-reusable-with-the-this-keyword

I do think the `Array.prototype.map` and `Array.prototype.filter` challenges are of the more difficult challenges, but I do not think it unreasonable for campers to accomplish them, or to discover the need for `this`.

**Comment by lasjorg** [comment]
I don't think the OOP part of the curriculum is of much help to people in figuring this out. The challenge seems completely oblivious to this missing piece of information, it's like it is not even part of the challenge, yet it's necessary to complete it.

I'm 99% sure if this challenge did not have a hints page we would be flooded with forum posts about it. Just do a search on the forum for it and read a few of the threads. The use of `this` is clearly a part of the challenge people do not fully understand.
https://forum.freecodecamp.org/search?q=Implement%20map%20on%20a%20Prototype

**Comment by nibble0101** [comment]
@lasjorg  Is this issue still open? I would love to work on it.
