### ISSUE TITLE
freecodecamp.com and www.freecodecamp.com sessions are different

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3949]
If I am logged in to freecodecamp.com or www.freecodecamp.com my session/login is not shared when I visit the other.

I don't know if this is a "bug", but I notice it occasionally, when I catch a link from another user in chat.

**Comment by abhisekp** [comment]
I guess, they should redirect the **www** to non-www.

**Comment by abhisekp** [comment]
Related to #3949

**Comment by BerkeleyTrue** [comment]
@SaintPeter thanks. Closing as duplicate of #3902 

Happy Coding!
