### ISSUE TITLE
challenge tribute page (codepen)

### ISSUE THREAD

**Issue by Laurent0311** [freeCodeCamp/freeCodeCamp#39496]
don't understand why i cannot see the picture on codepen 

![Capture d’écran 2020-08-31 à 05 22 44](https://user-images.githubusercontent.com/64399759/91712536-eaaa5380-eb55-11ea-80dd-9e7e775b9960.png)

NOTE: If you're reporting a security issue, don't create a GitHub issue. Instead, email security@freecodecamp.org. We will look into it immediately. 
-->
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Hello there,

Seeing as this is not an issue with the source code/test suite, I recommend you open a topic in the [forum](https://forum.freecodecamp.org). Please be sure to include a link to your project, and make use of the MarkDown syntax used.
It is difficult to work with screenshots of code.

As such, I am closing this issue. Thank you.
