### ISSUE TITLE
Add some space in completion modal when not signed in

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39498]
Go to any challenge when not signed in and complete it. The modal that pops up could use a little space where highlighted...
![Screen Shot 2020-08-31 at 12 01 40 PM](https://user-images.githubusercontent.com/20648924/91746501-4be81c00-eb82-11ea-94f3-7973476be66f.png)

Tested on chrome and firefox.

**Comment by nhcarrigan** [comment]
Heya @moT01 - is this related to #39476? 🙂
