### ISSUE TITLE
Account deletion redirects too quickly

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#39508]
**Describe the bug**
Deleting your account works as expected, but it also redirects users to /signin immediately after signing them out. This means the "Your account has successfully been deleted" message only appears for a split second before it disappears. I knew to look for it, but most users would not. Meaning they might misunderstand and think their account has not been deleted successfully.

**To Reproduce**
1. Go to the bottom of /settings
2. Click the "delete my account" button and confirm.
3. You will be redirected twice – once to the unauthenticated landing page, and then immediately afterward to /signin

**Comment by dev-script** [comment]
@QuincyLarson , @raisedadead  I would like to work on this issue.

**Comment by raisedadead** [comment]
Thanks for your interest. 

I recommend taking a look at our Contributing guide here: https://contribute.freecodecamp.org, it has details about issues open for contribution. We tag them with the "help wanted" label.
