### ISSUE TITLE
Missing nav from forum header

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39503]
**Describe the bug**
Missing nav from forum header.

**To Reproduce**
1. Go to <http://forum.freecodecamp.org/u/nonexistentuser>
2. See error

**Expected behavior**
Nav should be available at all times.

**Screenshots**
![image](https://user-images.githubusercontent.com/1884376/91862065-2135ba80-ec8b-11ea-9540-f30af2852286.png)

**Comment by Haroldthe24th** [comment]
Hey, is this still open for grabs?
@raisedadead

**Comment by raisedadead** [comment]
Thanks for reaching out, see: https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue

**Comment by Anoop01234** [comment]
Sir, I would like to resolve the issue but the problem that I am facing is that I can not navigate, where I could find the navigation bar code in the repo. So, it would be really helpful if you could help me out in that.

**Comment by raisedadead** [comment]
Thanks for your interest. 

This issue is non-trivial and is assigned to one of the staff members. I am locking this to avoid further "I want to work on this" comments.

We encourage you to sift through the help wanted labels and give our Contributing Docs a good read. They have all the information you need to start working on any issue that interests you.
