### ISSUE TITLE
Brownie points are missing my Nick

### ISSUE THREAD

**Issue by Masd925** [FreeCodeCamp/FreeCodeCamp#3951]
When someone thanks me (Masd925) on chat, camperbot tries to give a brownie point to masd925, which it cannot find due to wrong first letter.

![sieppaa](https://cloud.githubusercontent.com/assets/9335367/10782357/54ae5914-7d58-11e5-9c1a-dba749e0fd86.JPG)

**Comment by abhisekp** [comment]
@Masd925 it's not because of the first letter. You've to link your github account with FCC.
And for any camperbot issues, please post here https://github.com/gitterHQ/gitter/issues

**Comment by Masd925** [comment]
OK. I linked my github to FCC.

**Comment by abhisekp** [comment]
@Masd925 You can close this as it's resolved.

**Comment by Masd925** [comment]
Works now.
