### ISSUE TITLE
Mochachai testing unit failing: "before all" hook in "Unit Tests"

### ISSUE THREAD

**Issue by shartrooper** [freeCodeCamp/freeCodeCamp#39517]
**Describe your problem and how to reproduce it:**
Hello.
After finishing the main scripts for both Sudoku Solver and American/British translator. I was unable to write test units that actually work for my code, and I mostly left the suite async configuration in the boilerplate testing files mostly intact.

So I went to their respective FCC challenge sample projects, checked their **1_unit-test.js** code  and run **npm run test** .
Then Just happens the same issue: Unit tests fail due to timeout and displays **"_before all" hook in "Unit Tests_"**

**Add a Link to the page with the problem:**

[Sudoku Solver](https://repl.it/@freeCodeCamp/Sudoku-Solver)

[American British translator](https://repl.it/@freeCodeCamp/American-British-English-Translator)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![issue1](https://user-images.githubusercontent.com/21326996/92180787-e0b67800-ee15-11ea-935f-6bf440f83262.jpg)
![issue2](https://user-images.githubusercontent.com/21326996/92180790-e1e7a500-ee15-11ea-8343-9924dc9d8848.png)

**Comment by moT01** [comment]
Thanks for reporting this @shartrooper. I extended the timeout to 5000 and they pass on both projects...
![Screen Shot 2020-09-14 at 10 55 24 AM](https://user-images.githubusercontent.com/20648924/93108868-f8dd9100-f678-11ea-8fc6-f95399f97328.png)
So I think if we extend that timeout on both the example projects and the boilerplates, we would probably be good. 5000 worked on both of them for me.

**Comment by shartrooper** [comment]
Finally, Thanks a lot. Oddly enough, I've received zero feedback wherever I asked in regards of this issue. Now I have something to help sort out my testing unit coding issues too for my later projects.

**Comment by moT01** [comment]
If you want, you can let us know if you come across this issue on other projects as well so we can fix them up :smile:

**Comment by randomSveta** [comment]
Hi! @moT01, the thing is that if you do "npm run test" everything works fine, but when tests run automaticaly, when project is in a working state, then tests have the same issue issue. Could you check it too, please? Thank you!

![tests-run-on-command](https://user-images.githubusercontent.com/38963057/93115025-41b23b80-f6b3-11ea-8cb9-a624cda2ae74.png)

![test-run-before-all-hooks](https://user-images.githubusercontent.com/38963057/93114749-e54f1c00-f6b2-11ea-8509-078379c38d2e.png)

**Comment by moT01** [comment]
You can add the timeout option in `test-runner.js` and it will pass...

![Screen Shot 2020-09-14 at 9 18 48 PM](https://user-images.githubusercontent.com/20648924/93157543-0eca7080-f6d0-11ea-87bb-d925ae2d95c2.png)

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @shartrooper, and for catching the related issue with the automated test runner @randomSveta. @moT01's fixes were tested on these projects and merged into both boilerplates, so I'll close this for now. 

Could you let us know if you have any other issues with the tests timing out?

**Comment by randomSveta** [comment]
@shartrooper, @moT01 , @scissorsneedfoodtoo, Thank you for your help! :)

**Comment by scissorsneedfoodtoo** [comment]
@randomSveta, thanks again for your input! It was really helpful.

Please let us know if you run into any other issues with the projects.
