### ISSUE TITLE
Remove reference/link to Azure Notebooks in README.md in external repo

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39514]
While reviewing PR #39499, it was discovered that one of the external reps to which we link in four `Data Analysis with Python Course` challenges, has a note and link to Azure Notebooks.

The four challenges are:
- curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/data-cleaning-and-visualizations.english.md

- curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/data-cleaning-duplicates.english.md

- curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/data-cleaning-introduction.english.md

- curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/data-cleaning-with-dataframes.english.md

The external repo is:
https://github.com/ine-rmotr-curriculum/data-cleaning-rmotr-freecodecamp

A PR needs to be created to update the README.md file for that repo to be:

```md
# Data Science Course - Class 2

_This material is created for our [Data Science with Python Course](https://rmotr.com/data-science-python-course)
```

@raisedadead I assume they will only merge a PR from a representative of FCC, so who should do that?

**Comment by beaucarnes** [comment]
I just made the PR with this change and reached out to the creator via email to explain.

**Comment by RandellDawson** [comment]
I can confirm this issue has been resolved.
