### ISSUE TITLE
Faulty code passes all the tests for Bonfire: Everything Be True

### ISSUE THREAD

**Issue by xeoneux** [FreeCodeCamp/FreeCodeCamp#3952]
Challenge [Bonfire: Everything Be True](http://freecodecamp.com/challenges/bonfire-everything-be-true#?solution=function%20every(collection%2C%20pre)%20%7B%0A%20%20return%20collection.every(function(e)%20%7B%20return%20e%5Bpre%5D%3B%20%7D)%3B%0A%7D%0Aevery(%5B%7B'user'%3A%20'Tinky-Winky'%2C%20'sex'%3A%20'male'%7D%2C%20%7B'user'%3A%20'Dipsy'%2C%20'sex'%3A%20'male'%7D%2C%20%7B'user'%3A%20'Laa-Laa'%2C%20'sex'%3A%20'female'%7D%2C%20%7B'user'%3A%20'Po'%2C%20'sex'%3A%20'female'%7D%5D%2C%20'sex')%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function every(collection, pre) {
  return collection.every(function(e) { return e[pre]; });
}
every([{'user': 'Tinky-Winky', 'sex': 'male'}, {'user': 'Dipsy', 'sex': 'male'}, {'user': 'Laa-Laa', 'sex': 'female'}, {'user': 'Po', 'sex': 'female'}], 'sex');
```

**Comment by xeoneux** [comment]
And this one too
```
function every(collection, pre) {
  return return typeof pre === 'string' ? true : false;
}
every([{'user': 'Tinky-Winky', 'sex': 'male'}, {'user': 'Dipsy', 'sex': 'male'}, {'user': 'Laa-Laa', 'sex': 'female'}, {'user': 'Po', 'sex': 'female'}], 'sex');
```

**Comment by xeoneux** [comment]
Working on the PR

**Comment by abhisekp** [comment]
Might be resolved in #3620

**Comment by ltegman** [comment]
@abhisekp is correct that this challenge has already been fixed in the staging branch. Both in clarifying the goal and adding test cases. The solution you posted originally actually is a valid solution, since the goal of the challenge it to check if the predicate is truthy for every object in the collection and the second solution is not valid and does not pass in the corrected version.

Closing since this is fixed in staging.

Thanks and happy coding!

**Comment by abhisekp** [comment]
@ltegman the first solution will fail for this 

```js
every([{'user': 'Tinky-Winky', 'sex': false}], 'sex');
```

**Comment by xeoneux** [comment]
@abhisekp is correct and I checked it using 
```js
every([{'user': 'Tinky-Winky', 'sex': 'female'}, {'user': 'Dipsy', 'sex': 'female'}, {'user': 'Laa-Laa', 'sex': 'female'}, {'user': 'Po', 'sex': 'female'}], {'sex': 'female'});
```
It should return true but returns false.

**Comment by ltegman** [comment]
Both the problem and the tests were changed by that PR. It never should have been asking students to check if a property was defined and none of the test cases should have included a full object as a predicate. The wording of this problem after the PR is "Check if the predicate (second argument) is truthy on all elements of a collection (first argument).", it just hasn't been merged into the master branch yet.
