### ISSUE TITLE
News: Machine Learning Crash Course links to Private Video

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39524]
As the title says: Machine Learning Crash Course links to Private Video

Article: https://www.freecodecamp.org/news/machine-learning-crash-course/

I cannot find the same video on the channel.

@beaucarnes Ping

**Comment by beaucarnes** [comment]
Thanks for bringing that to my attention. We discovered that video course was plagiarized almost word-for-word from another course so we took it down. I forgot to delete the article. I just deleted it.
