### ISSUE TITLE
Advanced Node and Express - Package Versioning

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#39521]
_Advanced Node and Express_ section needs package versions added to the instructions, as discussed in: https://github.com/freeCodeCamp/freeCodeCamp/pull/39080#pullrequestreview-479988596

Example:
"
Add <code>passport.socketio</code> version <code>X.X.X</code>, <code>connect-mongo</code> version <code>X.X.X</code>, and <code>cookie-parser</code> version <code>X.X.X</code> as dependencies and require them as <code>passportSocketIo</code>, <code>MongoStore</code>, and <code>cookieParser</code> respectfully.
"

Before this is undertaken:
- [x] Wait for #39080 to be merged
- [ ] Discuss which versions to use and how to convey this (`express@^4.0.0` or `express@~4.2.0`)

**Comment by nhcarrigan** [comment]
I am leaning more toward the `@~4.2.0` requirement, myself. 

With the carat prefix, `npm` will install the latest *minor* version. In theory, updates to the minor version are backwards compatible and shouldn't create any issues with the tests or challenges. However, minor versions can include depreciation notices like `X is depreciated and will be unavailable in a future version. Use Y instead`. The feature will still work, but this could be confusing to a camper. 

Using the tilde prefix means `npm` will install the latest *patch* version, which includes bug fixes but shouldn't lead to any depreciation notices. I think this will offer the best long-term compatibility with our tests and challenge instructions.

**Comment by ShaunSHamilton** [comment]
Well, it has happened: https://forum.freecodecamp.org/t/authentication-with-socket-io-connect-mongo/448306

Last versions which definitely work:
```
"dependencies": {
    "bcrypt": "^5.0.0",
    "connect-mongo": "^3.2.0",
    "cookie-parser": "^1.4.5",
    "cross-env": "^7.0.2",
    "dotenv": "^8.2.0",
    "express": "^4.16.1",
    "express-session": "^1.17.1",
    "html": "^1.0.0",
    "mongodb": "^3.6.0",
    "node": "12.18.0",
    "passport": "^0.4.1",
    "passport-github": "^1.1.0",
    "passport-local": "^1.0.0",
    "passport.socketio": "^3.7.0",
    "pug": "^3.0.0",
    "socket.io": "^2.3.0"
  },
```

I have tested this. Now, discussion:
1) Just ask for `mongo-connect@3` to be installed
2) Also change the lesson/code to work with this latest version?

**Comment by raisedadead** [comment]
Hey @ShaunSHamilton how is this show stopper coming along?

**Comment by ShaunSHamilton** [comment]
@raisedadead Ah yes... I have updated the label, because it should have been removed by #41524 . _Can a PR automatically remove an issue's label?_

Otherwise, this issue is still open and _help wanted_ , as there are many packages which need their versioning fixed. If no one else, I can slot in some time for this tomorrow.

**Comment by raisedadead** [comment]
No rush. Thanks for confirming, I have removed the assignment since this is no longer a showstopper.

**Comment by saras17** [comment]
thank you so much for the

> Well, it has happened: https://forum.freecodecamp.org/t/authentication-with-socket-io-connect-mongo/448306
> 
> Last versions which definitely work:
> 
> ```
> "dependencies": {
>     "bcrypt": "^5.0.0",
>     "connect-mongo": "^3.2.0",
>     "cookie-parser": "^1.4.5",
>     "cross-env": "^7.0.2",
>     "dotenv": "^8.2.0",
>     "express": "^4.16.1",
>     "express-session": "^1.17.1",
>     "html": "^1.0.0",
>     "mongodb": "^3.6.0",
>     "node": "12.18.0",
>     "passport": "^0.4.1",
>     "passport-github": "^1.1.0",
>     "passport-local": "^1.0.0",
>     "passport.socketio": "^3.7.0",
>     "pug": "^3.0.0",
>     "socket.io": "^2.3.0"
>   },
> ```
> 
> I have tested this. Now, discussion:
> 
> 1. Just ask for `mongo-connect@3` to be installed
> 2. Also change the lesson/code to work with this latest version?

Thank you for the suggestion. It helped me alot
