### ISSUE TITLE
Basic JavaScript: Local Scope and Functions

### ISSUE THREAD

**Issue by devagarwal2503** [freeCodeCamp/freeCodeCamp#39523]
There is a problem with the challenge, even after solving it right it not accepting it.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version:  84.0.4147.135
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Problem](https://user-images.githubusercontent.com/70715867/92274260-84815000-ef0a-11ea-807b-5adf6431d02e.JPG)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
