### ISSUE TITLE
Run Cypress tests in more than one browser in parallel

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#39527]
**Is your feature request related to a problem? Please describe.**

We often get a lot of questions about which browser/s fCC's site supports. We normally answer saying, newer versions of Chrome... when in reality the site probably works fine on all browsers. But we couldn't guarantee it. It would be a good idea to run tests on different browsers. That way if a feature doesn't work in browser, we'll be able to know and fix them quickly rather waiting for user feedback and then fixing them (or even worse, telling the user to change their browser of choice). Other issues pop up time to time for cross browser support too, like #39519.

Btw... currently the Cypress tests run on Electron.

**Describe the solution you'd like**

Cypress e2e tests should run in popular browsers in parallel. Cypress already supports these features so this should be relatively easy implementing. I'd like to suggest running tests on the following browsers - 

1. Chrome (The most used browser)
2. Firefox (The most popular non-chromium browser)
3. Brave (The privacy focused Chromium based browser)

**Describe alternatives you've considered**

We could run the tests as a cron job on the master branch if you don't want to run it in every PR.

**Comment by ojeytonwilliams** [comment]
Sounds good to me. Do you know if we can group the status checks on GitHub?  Just to keep the noise down.  If that's the case I don't see a problem having them all run on each PR.

**Comment by Twaha-Rahman** [comment]
> Sounds good to me. Do you know if we can group the status checks on GitHub? Just to keep the noise down. If that's the case I don't see a problem having them all run on each PR.

@ojeytonwilliams I'll have to look into it. There should be a way to so....

**Comment by ojeytonwilliams** [comment]
Thanks.  I don't think it's a deal-breaker, but if we can keep the noise down, that's definitely a plus.

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams Looks like Brave doesn't play well with Cypress. Would you like to substitute Brave with any of the following -

1. Edge (stable/canary/nightly)
2. Chromium (stable/canary/nightly)

**Comment by Twaha-Rahman** [comment]
I'll keep an eye out on Cypress support for Brave on the meantime too :eyes:

**Comment by ojeytonwilliams** [comment]
We only officially support Chrome and Firefox, so we should definitely add tests for them.  Other browsers I'm less sure about: we don't want to end up in a situation were we have a bunch of tests that always fail and we have to ignore them.  Ideally we would support Safari and Edge, too, but each one we add increases the maintenance effort.   @raisedadead any thoughts?

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams So let's limits the tests to only run on Chrome and Firefox for now...
