### ISSUE TITLE
Correct answer not accepted

### ISSUE THREAD

**Issue by neilk13** [freeCodeCamp/freeCodeCamp#39536]
At the url https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed, the property is supposed to be added to several things.  However, the condition "Your .follow-btn should have a display property set to flex" is marked as not met.  It seems to be a website error, because I then copied and pasted the answer given at "get help," but the same thing happened again.

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
