### ISSUE TITLE
Chinese challenges (Responsive Web Design) needing another audit for English changes from Feb 29, 2020 - Sep 7, 2020

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39537]
The following Chinese curriculum challenges need to be compares to their English equivalents.

This issue only covers challenges in the Responsive Web Design certification.

All the challenges below have Description or Instructions sections with changes to the English version since Feb 29, 2020 (the day after the last such audit on this section of challenges). Also, any challenges with Tests where at least one test's text has changed in the English version since Feb 29, 2020 or where the number of tests in the current English version is different than the number of tests in the current Chinese version.

**NOTE:** This audit does not include any new English challenges created or deleted from the curriculum.  I believe @ojeytonwilliams has a script that can generate a list of those.

Followup to issue #38299

@raisedadead - Even though It only takes a minute to create the report, I suggest we lock down merging any English Responsive Web Design PRs or we will need to run the audit report again.  Just let me know if you want me to generate audit reports like this certification sections.  I assume you will want to wait until all the existing Chinese curriculum translation PRs are merged.

- [ ] [Standardize Times with the HTML5 datetime Attribute](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/standardize-times-with-the-html5-datetime-attribute.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your code should have a <code>p</code> element which includes the text "Thank you to everyone for responding to Master Camper Cat's survey." and include a <code>time</code> element.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your code should have a <code>p</code> element which includes the text <code>Thank you to everyone for responding to Master Camper Cat's survey.</code> and include a <code>time</code> element.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your added <code>time</code> tags should wrap around the text "Thursday, September 15&lt;sup&gt;th&lt;/sup&gt;".
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your added <code>time</code> tags should wrap around the text <code>Thursday, September 15&lt;sup&gt;th&lt;/sup&gt;</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 4**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your added <code>datetime</code> attribute should be set to a value of 2016-09-15.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your added <code>datetime</code> attribute should be set to a value of <code>2016-09-15</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Use tabindex to Add Keyboard Focus to an Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/use-tabindex-to-add-keyboard-focus-to-an-element.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] [Use tabindex to Specify the Order of Keyboard Focus for Several Elements](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] [Use the s Tag to Strikethrough Text](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-s-tag-to-strikethrough-text.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] [Use the strong Tag to Make Text Bold](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-strong-tag-to-make-text-bold.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 3**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>strong</code> tag should wrap around the words "Stanford University".
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>strong</code> tag should wrap around the words <code>Stanford University</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Use the u Tag to Underline Text](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-u-tag-to-underline-text.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>u</code> tag should wrap around the text "Ph.D. students".
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>u</code> tag should wrap around the text <code>Ph.D. students</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Adjust the Padding of an Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/adjust-the-padding-of-an-element.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Import a Google Font](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/import-a-google-font.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 3**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  You should use an <code>h2</code> CSS selector to change the font.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  You should only use an <code>h2</code> element selector to change the font.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Size Your Images](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/size-your-images.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your image should be 100 pixels wide. Browser zoom should be at 100%.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your image should be 100 pixels wide.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Add a Submit Button to a Form](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 3**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your submit button should only have the text "Submit".
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your submit button should only have the text <code>Submit</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Add Images to Your Website](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Add Placeholder Text to a Text Field](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-placeholder-text-to-a-text-field.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  You should set the value of your placeholder attribute to "cat photo URL".
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  You should set the value of your placeholder attribute to <code>cat photo URL</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Create a Form Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your text input element should be nested within a <code>form</code> element.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The existing <code>input</code> element should be nested within a <code>form</code> element.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>form</code> should have an <code>action</code> attribute which is set to <code>/submit-cat-photo</code>
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>form</code> should have an <code>action</code> attribute which is set to <code>https://freecatphotoapp.com/submit-cat-photo</code>
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Create an Ordered List](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-an-ordered-list.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  You should have an ordered list for "Top 3 things cats hate:"
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  You should have an ordered list for <code>Top 3 things cats hate:</code>
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  You should have an unordered list for "Things cats love:"
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  You should have an unordered list for <code>Things cats love:</code>
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Inform with the Paragraph Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/inform-with-the-paragraph-element.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>p</code> element should have the text "Hello Paragraph".
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>p</code> element should have the text <code>Hello Paragraph</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Link to External Pages with Anchor Elements](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  You need an <code>a</code> element that links to <code>http&#58;//freecatphotoapp<wbr>.com</code>
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  You need an <code>a</code> element that links to <code>https://freecatphotoapp.com</code>
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Make Dead Links Using the Hash Symbol](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/make-dead-links-using-the-hash-symbol.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] [Nest an Anchor Element within a Paragraph](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  You should have an <code>a</code> element that links to "http://freecatphotoapp.com".
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  You should have an <code>a</code> element that links to "https://freecatphotoapp.com".
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Use the value attribute with Radio Buttons and Checkboxes](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/use-the-value-attribute-with-radio-buttons-and-checkboxes.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Use the align-items Property in the Tweet Embed](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-align-items-property-in-the-tweet-embed.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] [Use the flex-direction Property to Make a Column](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-column.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Use the flex-direction Property to Make a Row](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-row.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Use grid-area Without Creating an Areas Template](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-grid/use-grid-area-without-creating-an-areas-template.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  <code>item5</code> class should have a <code>grid-area</code> property such that it is between the third and fourth horizontal lines and between the first and fourth vertical lines.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>item5</code> class should have a <code>grid-area</code> property to make it fill the whole area between the third and fourth horizontal lines, and first and fourth vertical lines.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [ ] [Create a Media Query](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] [Use a Retina Image for Higher Resolution Displays](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [ ] [Build a Personal Portfolio Webpage](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Build a Product Landing Page](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-product-landing-page.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Build a Survey Form](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Build a Technical Documentation Page](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [ ] [Build a Tribute Page](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-tribute-page.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

**Comment by raisedadead** [comment]
Let's merge all outstanding PRs (at least what we can) and the do the 

1. Audit 
2. Fix changes
3. Remove any freeze.

We would be needing to do this for all the certifications correct?

**Comment by RandellDawson** [comment]
> We would be needing to do this for all the certifications correct?

Yes. I will need to create separate issues for the different certifications and for some, maybe break them down into sub sections to avoid the audit information from being too much information (i.e. the JavaScript Algorithm and Data Structures certification).

Before you unfreeze, you will want to wait until @ojeytonwilliams has added the new test ids, once the Chinese team has confirmed all the test text/testStrings are in order after the audits.

**Comment by RandellDawson** [comment]
@raisedadead Once we are ready to freeze any English curriculum PRs into master, then I will update this issue by running my script again in case there were any recent changes since I created this issue that need to be reviewed in the audit.  Then, I will also create the other issues for the other sections.

**Comment by RandellDawson** [comment]
@raisedadead I think we can close this issue now that all the translations are performed on Crowdin and we have the various QA checks in place to warn about code block differences and other changes that occur in the English source for these files.  The original intent of the issue was to have PRs created to fix any discrepancies.  Some were created before we started really using Crowdin, but none are made now outside of Crowdin.
