### ISSUE TITLE
[BUG] - Formatting required in `Introducing Else If Statements`

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39538]
**Describe your problem and how to reproduce it:**

The tests appear to require specific (albeit conventionally correct) formatting in order for the code to pass. This code block, provided by a user, did not pass:
```js
function testElseIf(val) {
if (val > 10) {
  return "Greater than 10";
} else  if (val < 5) {
  return "Smaller than 5";
} else {
  return "Between 5 and 10";
}
}

testElseIf(7);
```

However, if I ran the formatter with `Ctrl`+`Alt`+`F`, the resulting formatted code *did* pass:
```js
function testElseIf(val) {
  if (val > 10) {
    return "Greater than 10";
  } else if (val < 5) {
    return "Smaller than 5";
  } else {
    return "Between 5 and 10";
  }
}

testElseIf(7);
```

**Add a Link to the page with the problem:**

[Basic JavaScript - Introducing Else If Statements](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/introducing-else-if-statements)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 85.0.4183.83
* Operating System: Windows 10 v1909

**Comment by Sky020** [comment]
Confirmed. This is due to the extra space between the word _else_ and _if_. Here is the culprit:

```
text: You should have closing and opening curly braces for each <code>if else</code> code block.
testString: assert(code.match(/if\s*\((.+)\)\s*\{[\s\S]+\}\s*else if\s*\((.+)\)\s*\{[\s\S]+\}\s*else\s*\{[\s\S]+\s*\}/));
```
Changing the above to this should work:
```
/if\s*\((.+)\)\s*\{[\s\S]+\}\s*else\s+if\s*\((.+)\)\s*\{[\s\S]+\}\s*else\s*\{[\s\S]+\s*\}/
```

@nhcarrigan Open up to _first-timers_?

**Comment by nhcarrigan** [comment]
Sounds good to me!

**Comment by AkshataJ96** [comment]
Hi, I would like to pick this! Thanks for the guide! :)

**Comment by nhcarrigan** [comment]
@AkshataJ96 Welcome! 

Issues labelled `first timers only` don't require permission for a pull request, as long as its your first pull request with us. 😁 

If you have not done so already, please give our [contributing docs](https://contribute.freecodecamp.org) a read - there are a lot of helpful tips in there to get you started.

**Comment by yashgupta18** [comment]
Hi, i am a first timer. Is the issue still open?

**Comment by ojeytonwilliams** [comment]
Hey @yashgupta18. We typically accept PRs in the order we receive them, so this will be open until we get a working PR.
