### ISSUE TITLE
Project Euler: Problem 2: Even Fibonacci Numbers

### ISSUE THREAD

**Issue by TheBeardBeatsAll** [freeCodeCamp/freeCodeCamp#39549]
**Describe your problem and how to reproduce it:**
The given solution for Problem 2: Even Fibonacci Numbers does not pass all the tests as it does not allow for when n itself is an even Fibonacci number to be added to the sum which is needed.
Failing tests: Your function should sum the even-valued Fibonacci numbers: fiboEvenSum(8) should return 10.
& fiboEvenSum(34) should return 44.
Line 6:  while(value < n) {   should be changed to  while(value <= n) {  

Additionally, the explanation to the problem on this page is incorrect because we are not trying to sum up the even Fibonacci numbers up to the nth term but the even Fibonacci numbers up to and including the value n:
"By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms."

**Add a Link to the page with the problem:**
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-problem-2-even-fibonacci-numbers/301838

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version:  80.0.1
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Firefox_Screenshot_2020-09-09T13-16-20 155Z](https://user-images.githubusercontent.com/23201815/92603292-6c655400-f2af-11ea-8d1a-896aadb52240.png)
![Firefox_Screenshot_2020-09-09T13-17-01 197Z](https://user-images.githubusercontent.com/23201815/92603385-87d05f00-f2af-11ea-9fef-31e17e019034.png)

**Comment by RandellDawson** [comment]
@TheBeardBeatsAll Thanks for pointing this out.  I have updated the Guide topic Problem Explanation and added a correct solution for the challenge.  I am closing this issue for now.  If you discover any other problems with it, you can request it to be reopened.
