### ISSUE TITLE
the jquery.js hosted by google is blocked by China Great FireWall

### ISSUE THREAD

**Issue by hhao99** [FreeCodeCamp/FreeCodeCamp#3954]
Challenge [Waypoint: Create a Text Field](http://freecodecamp.com/challenges/waypoint-create-a-text-field#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%3E%0A%20%20%3Cinput%20type%3D%22text%22%3E%20%3C%2Finput%3E%0A%3C%2Fform%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36 OPR/33.0.1990.43</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form>
  <input type="text"> </input>
</form>

```

**Comment by QuincyLarson** [comment]
Is jquery itself blocked? or are you talking about the Google font? We know that it's blocked. You can complete the challenge without it.

**Comment by hhao99** [comment]
the jquery library we used to check the code, it is blocked and cannot load the jquery, it report that the $ is not defined.
Now the cloudflare.com cdn is also blocked.

**Comment by BerkeleyTrue** [comment]
Cloudflare is blocked in china?

**Comment by BerkeleyTrue** [comment]
Can others confirm that jQuery and Cloudflare is blocked in china. Cloudflare reports it works in China.

**Comment by hhao99** [comment]
the jquery library we used to check the code, it is blocked and cannot load the jquery, it report that the $ is not defined.
Now the cloudflare.com cdn is also blocked.

**Comment by hhao99** [comment]
the jquery library we used to check the code, it is blocked and cannot load the jquery, it report that the $ is not defined.
Now the cloudflare.com cdn is not blocked, but it interfere by GFW and very slow.

**Comment by hhao99** [comment]
the jquery library we used to check the code, it is blocked and cannot load the jquery, it report that the $ is not defined.
Now the cloudflare.com cdn is not blocked, but it interfere by GFW and very slow.

**Comment by tomByrer** [comment]
May I humbly suggest [jsDelivr CDN](http://www.jsdelivr.com/projects/jquery)?  There are around [20 POPs inside China](http://www.jsdelivr.com/features/network-map) thanks to [QUANTIL CDN](https://www.quantil.com).  Even if the 0.0001% chance that QUANTIL goes down, traffic will automatically switch to Key & Max CDNs.

We have had several complaints about China users using Google & CloudFlare CDN.  Small chance of issues, but happens.  (Outside of China they're great.)  This is why jsDelivr sought a Chinese CDN to add to the network.

Disclaimer: I volunteer for jsDelivr. But you can ask me for consulting help, such as how to [concoct all OSS JS into as single flie](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request).

**Comment by BerkeleyTrue** [comment]
@tomByrer Well, bad first impression. I clicked on your first link and got a 503.

**Comment by BerkeleyTrue** [comment]
I'm also still waiting to hear others experiences. Since I have had none I'm assuming this is a one-off issue.

**Comment by tomByrer** [comment]
Looks like the deep linking is broken, sorry!  Home page works: http://www.jsdelivr.com/
We (& watching CDNJS's gitter) get reports of China issues every few months.  Not frequently, but happens.

**Comment by BerkeleyTrue** [comment]
We will be moving away from CDNJS as soon as we can verify Cloudflare works in the way we want it to. If what you say is true then that explains this issue. Closing. @tomByrer Thanks for letting me know of jsDelivr. I'll give it a look around.

Happy Coding!

**Comment by tomByrer** [comment]
Not sure if that will fix the issue at all; since [CDNJS uses CloudFlare as their exclusive CDN](https://cdnjs.com/about).  CloudFlare/CDNJS gets occasional IPs blocked or DoS because they [shield political sites](https://blog.cloudflare.com/protecting-free-expression-online/).  Good for protecting free speech, bad for China uptime.  (Aside from China, I'd 100% applaud CloudFlare; great service.  Depends how worried about China's users vs benefits)

**Comment by tomByrer** [comment]
OTOH, CF does have [new partners in China](https://blog.cloudflare.com/how-we-extended-cloudflares-performance-and-security-into-mainland-china/).

> Existing and new CloudFlare customers can request to be served in China by filling out an information request at:
https://www.cloudflare.com/china
Initially, the China network will be limited to Enterprise customers. Over time, as we are better able to operationalize the onboarding of customers, we hope to extend the benefits to all plan levels.

**Comment by BerkeleyTrue** [comment]
Well, that sucks.

**Comment by tomByrer** [comment]
You could ask for sponsorship for Enterprise; they seem like cool cats.  I don't think sponsorship for jsDelivr was hard (& we use much more bandwidth than you ever will ;) ).  Plus, would make financial wisdom to invite up & coming to use a CDN like CloudFlare.  You could make bonus tutorial how to use CF to make the sponsorship-swap more inciting... 

Or, you can host with one of their [Optimized Hosting Partners](https://www.cloudflare.com/hosting-partners/); just have to ensure China is turned on (perhaps double check via trial).  & could seek affiliate sales or sponsorship-swap as described above.
