### ISSUE TITLE
Some project url related issue

### ISSUE THREAD

**Issue by Bhavna777** [freeCodeCamp/freeCodeCamp#39547]
When I enter any random url on the freecodecamp solution of :-- 1) Scientific Computing with Python Certificate, 2) Data Analysis with Python Certificate, 3) Machine learning with Python certificate, then without checking my project it redirect me to next project(challenge).

**Comment by Sky020** [comment]
Hello there,

The tests have not been written yet, for them on the client side. This is a known issue, and you are welcome to open a PR adding tests.

Duplicate of #37185
