### ISSUE TITLE
Slice and Splice

### ISSUE THREAD

**Issue by CallumScaife** [freeCodeCamp/freeCodeCamp#39558]
Issue is either tests implemented incorrectly or the question should state that splice must be used.

Tell us what’s happening:
My code is satisfying all tests but returning false on the below which i believe is an error:
All elements from the first array should be added to the second array in their original order.

Your code so far
function frankenSplice(arr1, arr2, n) {
let rarr = [];
for(var i = 0; i < arr2.length; i++) {
  if(i == n) {
    rarr.push(...arr1)
  }
  rarr.push(arr2[i])
}
return rarr;
}

frankenSplice([1, 2], ["a", "b"], 1);

Your browser information:

User Agent is: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36.

Challenge: Slice and Splice

Link to the challenge:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/slice-and-splice

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by CallumScaife** [comment]
This was not me debugging my code. My code is proper and works. This is to raise an issue with the test.

**Comment by RandellDawson** [comment]
> This was not me debugging my code. My code is proper and works. This is to raise an issue with the test.

@CallumScaife The code you posted above does not pass the 4th test of the challenge (seen below) due to a logic error in your solution.  Your solution does not correctly handle the case where `arr2` is an empty array.
> All elements from the first array should be added to the second array in their original order.

See below for the function call being used for the 4th test.
```js
frankenSplice([1, 2, 3, 4], [], 0); // returns [] instead of [1, 2, 3, 4]
```
