### ISSUE TITLE
Lost everything last night version 3

### ISSUE THREAD

**Issue by anthonygallina1** [FreeCodeCamp/FreeCodeCamp#3955]
Most of my work in my portfolio is gone again. And there are multiple listings of the same projects in there place. I need help as soon as possible. I was interviewed today for a job,and it was a hour interview
by a panel of three people The CEO of the company and 2 others. They are going to be checking my portfolio here today. Not only that but when I try to look back to prior code I can not find it. And I cant back reference to help others in the help chat.  Please Please restore my work.

**Comment by abhisekp** [comment]
cc: @QuincyLarson @benmcmahon100 Urgent!! attention needed.

**Comment by abhisekp** [comment]
@anthonygallina1 but I see all your completed projects and challenges in your profile.

Are you talking about this or something else?

**Comment by awesomeaniruddh** [comment]
Closing this until @anthonygallina1 provides further info regarding the issue.
