### ISSUE TITLE
Exercise Tracker challenge hint possibly misleading

### ISSUE THREAD

**Issue by ffe4** [freeCodeCamp/freeCodeCamp#39563]
*Description updated. Original post quoted at the bottom.*

The [hint](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-exercise-tracker/301505) for the Exercise Tracker challenge contains the following line:
```js
  _id: 5f29cd9e782d5f13d127b456, // Must be of type 'ObjectId'
```
Which originally led me to believe that my solution using SQL did not pass because this field did not contain the correct type. 
If mentioning other database terms might be confusing to users of the site, I would suggest at least using _should_ instead of _must_, which would be in line with [RFC 2119](https://tools.ietf.org/html/rfc2119).

Original Issue Description

>**Describe your problem and how to reproduce it:**
>While investigating the test failures of my implementation of the [Exercise Tracker](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker), I looked at the [hints](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-exercise-tracker/301505) and noticed that the `_id` field has to be of type ObjectId. 
>Since there was no mention of which technologies to use, I used a PostgreSQL database, and a simple integer as the primary key. If I now want the tests to pass, I have to convert my primary key to something resembling an ObjectId before returning a response and then convert it back during requests.
>I see no reason why there should be any limitations on what database (or other technologies for that matter) you use for this exercise. The only thing about the `_id` field that should matter is that you can access to correct user across endpoints with whatever value it has.
>**Add a Link to the page with the problem:**
>https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-exercise-tracker/301505
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker

**Comment by skaparate** [comment]
AFAIK, it's not required to be an ObjectID nor a string, just that it matches the id of the recently created user. I mean, [the tests check that the object returned contains the `_id` parameter, but not the type](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.english.md). 

Maybe the hint could be updated so users could use other technologies, but the lessons are using MongoDB so I think that changing the hint may confuse students that are actually using MongoDB...

**Comment by ffe4** [comment]
> I mean, [the tests check that the object returned contains the `_id` parameter, but not the type](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.english.md).

Are those the test that are actually run? When I look at the [tests for shorturl](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice.english.md) they look pretty empty. 

Either way, it seems I jumped to conclusions. After reading the hint, it simply seemed like the most likely explanation for why the first test (adding a user) would fail. The actual issue was that I did not set the `Access-Control-Allow-Origin` (cors) header.

Still, due to the explicit mention of the response type, the hint was definitely not useful for troubleshooting in this case. This is especially true considering that I did not have to set the header during the url shortener exercise. I will rename the issue to reflect the actual problem, but I'm also fine with it being closed since this probably will not be an issue for the majority of the target audience.

**Comment by Sky020** [comment]
I have edited the guide post containing the hint. 
> Are those the test that are actually run? When I look at the tests for shorturl they look pretty empty.

Yes, Many of the tests for the backend projects have not been written: https://github.com/freeCodeCamp/freeCodeCamp/issues/37185

**Comment by ffe4** [comment]
Thank you @Sky020. LGTM, so I'll close the issue.
