### ISSUE TITLE
Drop it: 4th test case incorrect

### ISSUE THREAD

**Issue by AgathaLynn** [FreeCodeCamp/FreeCodeCamp#3956]
Bonfire: Drop it (http://www.freecodecamp.com/challenges/bonfire-drop-it)

There seems to be an issue with the last test case.  It says:

drop([1, 2, 3, 7, 4], function(n) {return n>= 3}) should return [7, 4]. 

The correct answer [3, 7, 4] passes, but it looks like maybe the additional test suggested here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2533 wasn't put in right.

**Comment by ltegman** [comment]
Looks like the test is looking for `> 3` but the test message says it's looking for `>= 3`, so someone needs to make them consistent.

**Comment by AgathaLynn** [comment]
It might be a good idea to change the 3's to 5's at the same time, to address issue #2533.

**Comment by ltegman** [comment]
Just noticed this issue has already been closed by PR #3944. I will reopen #2533 though since that is an issue again.

Thanks and happy coding!
