### ISSUE TITLE
Legacy submission bug

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39561]
**Describe the bug**

**To Reproduce**
1. Go to `https://www.freecodecamp.dev/settings`
2. Scroll down to just above 'Legacy Backend'
3. Enter in a valid url for any 'Legacy Front End' project 
4. Click 'Save Progress'
5. Alter that url (it should still be valid)
6. Click 'Save Progress' again
7. See 'It looks like you have not completed the necessary steps. Please complete the required projects to claim the Legacy Front End Certification'

**Expected behavior**
Step 7 should report: 'Your projects have been updated.'

@raisedadead am I right in thinking that once someone has claimed their cert, submissions should be closed?

Here's what it looks like:
![SubmissionBug](https://user-images.githubusercontent.com/15801806/92767277-40250280-f397-11ea-896e-597bf513d320.gif)

**Comment by RandellDawson** [comment]
@ojeytonwilliams I noticed this bug yesterday.  It only does it if there is at least one url for a section's solutions.  If there are none, it works as expected.

**Comment by RandellDawson** [comment]
> am I right in thinking that once someone has claimed their cert, submissions should be closed?

Since the url appears on their public profile, I could see someone improving upon their original design or now hosts it on their own domain, so they may have a new url to share.

**Comment by moT01** [comment]
> am I right in thinking that once someone has claimed their cert, submissions should be closed?

I would agree that users should be able to change it. Which is how it is now I believe. What if the hosting service changes something to where users have to move a project elsewhere.

**Comment by prolland006** [comment]
I confirm that it is unable to change the value.
