### ISSUE TITLE
Learn: Size your images challenge not working in Safari

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39569]
[This challenge](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images) is not working in Safari. 

See [this thread](https://github.com/freeCodeCamp/freeCodeCamp/pull/38770#issuecomment-691682076)

I suppose a fix would be to rewrite the regex.

**Comment by Ieahleen** [comment]
has the PR already been deployed? reports of the issue keep appearing

**Comment by Sky020** [comment]
@Ieahleen No, it does not look like this commit has made it to production yet.

@raisedadead Is there any need to cherry-pick this one? I remember there being a mention of this, but cannot remember why.
