### ISSUE TITLE
Suggestion: Exercise Tracker and Issue Tracker projects are conceptually identical

### ISSUE THREAD

**Issue by fuzzyray** [freeCodeCamp/freeCodeCamp#39571]
Feel free to close this as changing this isn't quick or easy and requires lots of time from someone. This is purely a suggestion from my working through the curriculum.

I recently finished the APIs and Microservices Projects and have moved on to the Quality Assurance Projects. I recently started working on the Issue Tracker and with the exception of adding in Helmet for security and writing the functional tests, the code is basically the same design as the code that was written for the Exercise Tracker. 

While this means I can fairly quickly complete this project, I don't feel like I'm really learning or reinforcing anything new with this project.

My suggestion (and this is where the time and work comes in) is that the Issue Tracker project be replaced with something else. I'm not sure what would make a good replacement, but since the the lessons touched on socket.io and authentication, maybe a full stack chat service project with some type of authentication would be nice as I don't see any projects in the Quality Assurance projects that seem to be touching on either topic.

Referenced Projects:
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker

Thanks for all the hard work that does go into making freeCodeCamp a great learning resource. I highly appreciate it.

**Comment by moT01** [comment]
I don't think this is an issue that needs fixing @fuzzyray - although a good suggestion, I don't think we want to change up the projects this much at the moment. I would disagree that this doesn't reinforce any learning - certainly it's more practice with known topics if nothing else.

Unless you're interested in creating a new project, I am going to vote to close this. We can leave it open for now if anyone else wants to weigh in.

**Comment by nhcarrigan** [comment]
> since the the lessons touched on socket.io and authentication, maybe a full stack chat service project with some type of authentication would be nice as I don't see any projects in the Quality Assurance projects that seem to be touching on either topic.

I do believe the lessons themselves involve a chat type application. 🤔 

> I don't think we want to change up the projects this much at the moment.

Agreed - with the planned shift to a project-based curriculum especially.

**Comment by fuzzyray** [comment]
While I would not mind working on a new project for this, I realistically know that it won't happen quickly, due to other obligations. My actual thought is to close this, especially since I'm seeing with other issues that things are being changed and moved around. It can always be revisited in the future.

**Comment by moT01** [comment]
Coincidentally, I have an example chat app https://my-chat.glitch.me/ that we could use - But I am still going to vote to leave this be. These projects are part of a certification and users who have earned that certification would no longer have all the required projects they completed to get it. I believe that if we ever change these certification projects it is with the roll out of a new certification and the existing ones would be moved to "legacy" certifications.

**Comment by moT01** [comment]
Thanks for all on the input on this everyone - I think we're safe to close this for now. I wouldn't mind adding a chat app project to the take home projects. If anyone thinks that would be a good idea, feel free to create an issue around that for further discussion. Thanks and happy coding 🎉
