### ISSUE TITLE
Advanced Node Social Authentication test fail due to broken test script

### ISSUE THREAD

**Issue by dvbsknd** [freeCodeCamp/freeCodeCamp#39572]
A [recent change](e3cfe80f88bb098f616c338b6b7a7b05ab676590) to the test scripts for the [social authentication](https://github.com/freeCodeCamp/freeCodeCamp/blob/production-current/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.english.md) step of the challenge will never pass: they expect the `fcctesting.js` script to expose a `/_api/routes.js` route, but that route doesn't exist in the test script provided in the starter repo, which clearly states "DO NOT EDIT", so it shouldn't be on the student to do this.

See the rendered/production page [here](https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/implementation-of-social-authentication).

![image](https://user-images.githubusercontent.com/1005395/93030632-c7a89500-f667-11ea-8e6c-7848ebc08ac9.png)

**Comment by Sky020** [comment]
Hello there,

This is due to the whole _Advanced Node and Express_ section having been updated recently. The entire section is new, and the boilerplate is new. So, unfortunately, if you had started the section, and half-way through it updated, you will have to restart, to ensure there are no issues along the way.

One of the main changes is there is no longer 3 separate boilerplates for the section. The same boilerplate is used throughout.

There were many issues in this section. So, unfortunately, a large change was needed.

**Comment by moT01** [comment]
Sorry, if you have to restart this @dvbsknd - that's a bummer. You can probably salvage much of the code, but you may need to copy/paste into the new boilerplate I think. If you do find out that this is not an issue when using the new boilerplate, let us know please so we can close this. If you don't think that's the issue, let us know that as well.

**Comment by dvbsknd** [comment]
Thanks guys, appreciate the responses. What I'll probably do is run with the two boilerplates side-by-side and bring in the items I need rather than starting from scratch, mainly because I'm trying to build this in its own repository and use good Git habits—so I'd like to keep my history. I'll update this issue once I've completed the module.

**Comment by dvbsknd** [comment]
I've managed to complete the challenge by cherry-picking changes from the updated one, so I'll close this issue.

**Comment by agracy2246** [comment]
Hi, I'm continuously getting 404 back on the passport-github section, when I am supposed ot be getting a profile. Any suggestionsd?

**Comment by scissorsneedfoodtoo** [comment]
Hi @agracy2246, for help with the coding challenges, please check out the forum at https://forum.freecodecamp.org. The contributors there are very active, and can help answer any questions you might have.
