### ISSUE TITLE
Logic Issue: "Override Class Declarations by Styling ID Attributes"

### ISSUE THREAD

**Issue by DaMaceMan** [FreeCodeCamp/FreeCodeCamp#3957]
The page doesn't seem to be checking that the ID definition is being inserted ABOVE the class definitions.

Since that is the part of the lesson (understanding that ID style overrides class style regardless of position in HTML, contrary to the logic that governs class style precedence) it seems like there should be a check that prevents this.

Maybe require that the position of the ID style is not after the class styles?

http://freecodecamp.com/challenges/waypoint-override-class-declarations-by-styling-id-attributes

**Comment by bugron** [comment]
Not sure what is this issue about so I'll close it. Thanks for posting, though, and feel free to comment or reopen if you still experience problems, thanks.

**Comment by DaMaceMan** [comment]
@bugron Once you complete the lesson the next one says something like "as you can see it doesn't matter where the ID style is located - it will always override a class definition."

But if there is no check for where the ID style is located, someone could put it above the class definitions which would not actually demonstrate anything.

Does that make sense?

An alternative solution would be to change the text in the next lesson to say "if you put the ID style above the class styles you probably noticed that it doesn't matter where the ID style is located - it will always override a class definition."

But honestly I think a check to ensure that the ID style is above the Class styles would be a good way to emphasize the lesson.

**Comment by bugron** [comment]
Still, I don't understand your point. This is from the next challenge: "id declarations override class declarations, **regardless** of **where** they **are declared** in your style element CSS.". Putting "ID style" above class definitions demonstrates this: http://prntscr.com/8x5t8f. Isn't this normal?

**Comment by DaMaceMan** [comment]
Right, but when I was doing the example I put it below and everything was
fine. So what I'm suggesting is to tell students to put the tag above
(might already say that) and then validate that it is above and not below.

Currently the exercise does not demonstrate your quote from the next lesson
unless the student happens to put the tag before.

If you do the exercise we're talking about and put the tag AFTER the class
style definitions I think you'll see the what I'm trying to describe.

The lesson is trying to demonstrate that 2+3=5, but the student could use
4+1=5 instead, so while they're getting the same answer it doesn't
demonstrate the same logic.


Christian M. Macy

**Comment by ltegman** [comment]
I'd worry that if we enforced certain CSS placement to prove a point we'd just end up creating confusion. The lesson text is about how the placement of a style declaration doesn't matter if one style is more specific than another, so forcing a certain page placement seems counterintuitive to the lesson being taught.

**Comment by DaMaceMan** [comment]
Hmm - well I do see your point. At the same time I think it's important to
remember the context of the lessons - the previous one is focused on the
importance of tag placement and how sequence matters.

I think if this lesson is about when to break that rule it should force the
user to do so so they can have the experience of having done it.

Or maybe there's another way to do it. Or maybe changing it wouldn't
actually improve the quality of education for anyone in the particular
lesson.

I tend to think that when it comes to changing things based on someone's
opinion, if it's not a Hell Yes then it's a No ;-)


Christian M. Macy
