### ISSUE TITLE
Are updates to "Install and Require Helmet" challenge needed?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#39582]
Challenge:
https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/install-and-require-helmet
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-with-helmetjs/install-and-require-helmet.english.md

1. Does this challenge need instructions on how to actually install the specified version? On repl.it if you search for a package it will just give you the latest version.

2. If you run `npm i helmet@3.21.3` it will add the package with the caret `^` in front of the version number but the test does not allow for that. Should the test allow for the caret?

**Comment by Sky020** [comment]
If changing the tests to allow `^` does not cause any of the versioning issues mentioned previously, then we should go with that. Otherwise, we could add a note that the camper should use `--save-exact`: `npm install --save-exact helmet@3.21.3`

**Comment by Sky020** [comment]
Just bringing this back up: Are we changing the tests, or changing the instructions to be explicit about the versioning?

**Comment by lasjorg** [comment]
Personally, I'd say both.

Show the npm command for how to install a specific package version and make the test ignore/accept the caret.

**Comment by Sky020** [comment]
@lasjorg I like that. This kind of lesson is **so** short, I also think it would be useful to add the information about `--save-exact`.

I am going to open this up for general help

**Comment by flemmingbond21** [comment]
Hi, I do exactly like npm install --save-exact helmet@3.21.3 and helmet = require('helmet'); but still not pass the challenge, anyone, please help me, thanks

**Comment by ShaunSHamilton** [comment]
Hey @flemmingbond21 ,

Without seeing your code, or being able to test your project, it will be difficult to assist.

Please make use of the [forum](https://forum.freecodecamp.org/) to open a topic, and provide as much detail as possible. It will be easier to assist that way.

**Comment by flemmingbond21** [comment]
my code:
myapp.js:
var express = require('express');
var app = express();
const helmet = require('helmet');
package.json:
{
	"name": "fcc-infosec-challenges",
	"version": "0.0.1",
	"description": "fcc backend boilerplate",
	"main": "server.js",
	"scripts": {
		"start": "node myApp.js"
	},
	"dependencies": {
		"express": "^4.14.0",
		"helmet": "3.21.3"
	},
	"keywords": [
		"node",
		"hyperdev",
		"express",
		"freecodecamp"
	],
	"license": "MIT"
}
and the test result:

// running tests
helmet version 3.21.3 should be in package.json
// tests completed
Please help me to solve this. thanks

**Comment by RandellDawson** [comment]
@flemmingbond21 As @ShaunSHamilton mentioned, please use [our forum](https://forum.freecodecamp.org) for questions that involve debugging challenge or project solutions.  Thank you.
