### ISSUE TITLE
Waypoint: Nest an Anchor Element within a Paragraph - Confusion about <p> placement

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3958]
Challenge "Waypoint: Nest an Anchor Element within a Paragraph"

I get a lot of questions about the test "Your a element should be nested within your new p element."  For some reason a lot of users want to move the new `<p>` element down to the bottom of the page.  The test code only checks to see if the first `<p>` element contains the anchor.

My code:
```html
<h2 class="red-text">CatPhotoApp</h2>

<!--- p tag should be here -->

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<!--- Users like to put it here -->
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>
```

One of two things should happen:

1. The test should be changed to find the `p` element anywhere on the page or
2. There should be a change to the challenge text to say to leave the image tag in place and wrap the `<p>` around it.

**Comment by ltegman** [comment]
Haha, I had noticed the same thing so I put in PR #3813 that should solve this whenever it gets merged into the master branch. Closing since this is already in staging :smile:

**Comment by SaintPeter** [comment]
Haha, there is something to be said for problems being solved before you even file them!
Thanks @ltegman!
