### ISSUE TITLE
Create pure Html,Css and Javascript web apps projects 

### ISSUE THREAD

**Issue by hamzaerrechydyhacker** [freeCodeCamp/freeCodeCamp#39589]
Hello, 

After finishing the JavaScript Section in freecodecamp i notice that there isn't projects in which students can create web apps using pure JavaScript plus the Html&Css skills they acquire from the earlier part. 

My suggestion is : to put instead of problems projects that the student can build with the knowledge he learned from this part, this is good for three reasons  : 

- The student will have more projects to put in his or her portfolio 
- I think crafting a web app is better and fun than solving a problem  
- There is already a LOT of problems to solve in the coding interview prep part

If you agree guys on this idea, i'm very happy to contribute with some web apps projects. 

Have a nice day.

[web app project example.zip](https://github.com/freeCodeCamp/freeCodeCamp/files/5232392/clock.zip)

**Comment by RandellDawson** [comment]
@hamzaerrechydyhacker You are in luck.  We have already been working on changes like the ones you are suggesting.   See [Quincy's article here for more information about the changes coming](https://www.freecodecamp.org/news/python-curriculum/).  You can also check the project prototypes over at our [curriculumExpansion repo](https://github.com/freecodecamp/curriculumExpansion).

I am closing this issue for now as we already working towards this goal and the changes are  being tracked in the other repo and outside of GitHub.  Please feel free to reach out to our [Contributors channel on Gitter](https://gitter.im/FreeCodeCamp/Contributors) to learn more about the project.

Thank you for your interest and suggestions.

**Comment by hamzaerrechydyhacker** [comment]
Thank you a lot for giving me this feedback

**Comment by Sky020** [comment]
@hamzaerrechydyhacker , This might not be exactly what you are looking for, but there are many projects under the `Coding Interview Prep` section within the `Take Home Projects` block.

Hope this helps
