### ISSUE TITLE
Setting the expectations for a certification before working on Challenges

### ISSUE THREAD

**Issue by danielh-official** [freeCodeCamp/freeCodeCamp#39593]
Some people get into this with pre-existing knowledge. Having to go back to the basics and go through 300 hours of coding problems just to earn a certificate can be quite tedious.

Each segment should have an all-encompassing assessment that allows people to get a certificate without having to go through every problem.

**Comment by nhcarrigan** [comment]
Hello~!

As an FYI, *only* the five projects in each section are required for certification. A user does not have to complete any of the challenges to be able to claim the certificate. 🙂

**Comment by ojeytonwilliams** [comment]
Yep, this is something we're looking to improve.  We're planning to make it clearer what's purely for practice and what's required to claim the certification.

**Comment by moT01** [comment]
I think we are safe to close this. We mention on the superblock pages to, `Complete the five <type> projects below to earn your <cert> certification.` It's also mentioned on [the message that pops up when you first visit /learn](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/translations.json#L243). If anyone thinks I am wrong in closing this or has a suggestion on what more could be done, feel free to leave a message and it can be reopened. Thanks and happy coding 🎉
