### ISSUE TITLE
Disable Monaco code actions highlighting

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39591]
**Describe the bug**
The highlighting for code actions appears in the editor, but the user cannot interact with them.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code
2. Enter 
```js
function anyname(){
  this.property = 'is set';
}
```
3. see the three dots below the 'a' in 'anyname'

**Expected behavior**
Since the user cannot act on this information these dots should not appear.

StackOverflow suggests they [can be disabled ](https://stackoverflow.com/questions/50257877/vscode-js-this-constructor-function-may-be-converted-to-a-class-declaration) in vscode, and hopefully the same is true of Monaco. 

**Screenshots**

![image](https://user-images.githubusercontent.com/15801806/93351766-62f16400-f83a-11ea-92d7-c4af15498929.png)

Thanks to @lasjorg for investigating this and olgamlop (who I'm not sure has a GitHub account, so I didn't want to ping the wrong person) for reporting it.

Originally discussed on the forum, [here](https://forum.freecodecamp.org/t/the-code-editor-doesnt-like-capitalized-functions/420935/3)

**Comment by lasjorg** [comment]
@ojeytonwilliams Not sure if there is an editor option for it, but here is the CSS for removing the three dots.

client\src\templates\Challenges\classic\classic.css
```
.monaco-editor .squiggly-hint {
  background: none !important;
}
```
I did look a bit for an option but the API docs for Monaco are pretty dense and hard to comb through.

Just let me know if I should make a PR with the CSS change.

**Comment by lasjorg** [comment]
I made a PR just in case. If we want to use it its there.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
