### ISSUE TITLE
Advanced Express - Inconsistent naming of user/username based on local/github Auth type

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#39599]
**Describe your problem and how to reproduce it:**
In doing the Advanced Express challenges I discovered there are some inconsistencies in the creation of a new user in the `local` vs. `github`.  For the former, the user name is stored in the DB as `username` for the latter it is stored as `name`.

Relevant sections of code from `routes.js`:
```js
 myDataBase.insertOne({
                username: req.body.username,
                password: hash
              },
```

And from `auth.js`:
```js
 $setOnInsert:{
            id: profile.id,
            name: profile.displayName || 'John Doe',  // <--  This should be username
            photo: profile.photos[0].value || '',
            email: Array.isArray(profile.emails) ? profile.emails[0].value : 'No public email',
            created_on: new Date(),
            provider: profile.provider || ''
          }
```

Assuming that they are supposed to be equivalent, the field names should be the same.

This was mainly a problem for me when I got to the "Announce New Users" section because I initially couldn't figure out why I was getting `undefined` from `console.log(`user ${socket.request.user.user} connected`);` with a local user.

My thought is to standardize on one or the other and then propagate the change through all of the exercises.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/announce-new-users

**Comment by Sky020** [comment]
Hello again,

>  initially couldn't figure out why I was getting undefined from console.log(user ${socket.request.user.user} connected);

Why did you think to search for `user` within `socket.request.user`? The code `socket.request.user.name` is given.

---

There should be no issue with local vs github, because only the github auth route is setup to direct to the `/chat` endpoint. Campers are welcome to refactor (and I did when I was testing), but all sections will need to be refactored.

As for standardising this:
- There was some discussion/mention of it: https://github.com/freeCodeCamp/freeCodeCamp/pull/39080#issuecomment-674151353
> Socket.io is only set-up to work with the GitHub auth routes. Should we refactor in any way to include the /login and /register routes. NOTE: This is not trivial, as Socket.io is setup to expect the user object from GitHub, which is structured differently to the user object from the app.

> ... it's probably fine to have Socket.io only work with the GitHub auth for now. That's how the original project was structured, and it would take a bit too long to refactor the project now. While it might be something to consider in the future,...

So, I suppose now could be a time to consider it.

Perhaps, I will leave the point for someone with more experience to weigh in on having separate tables for separate registration routes. @scissorsneedfoodtoo ?

**Comment by SaintPeter** [comment]
Here's the thing:
We're making a chat client, right?  In order to test this we need to connect multiple "users" to the client to see if the messages get sent out.  I only have one GitHub account and I'm not about to make a second one just to test this.  While I CAN log in multiple times from the same account then all I'm seeing is my name sending chats.  The UI we make doesn't differentiate between local-to-the-client messages and came-from-the-server messages.  I'm not even sure it could, without a unique message id?  It seemed logical to me that I should log in with some "local" users in order to test it.

But putting aside the chat aspect of this, it's just good design sense to have a standard set of fields for a user.  If we were to have a "Hello {{username}}!" field elsewhere on the site it would "break" depending on which auth was used.

Honestly, it would probably be better to have a Mongoose Schema for the user, but is maybe overkill for this type of app.

“Practice like you play, because you will play like you practice.”

**Comment by urbandesign09** [comment]
I agree with @SaintPeter , maybe having a Mongoose Schema for the user would clarify this point. As I was working through the Social Authentication exercises, I was also wondering why the exercise didn't involve a Schema (like the previous node section). It would help the learners keep things consistent.

My fix for the situation was just to add an additional property to $setOnInsert:
`username: profile.username || 'No username',`

This ensure that at least the Local and Social Auth have the same username reference point, either as the Github username (which will be familiar) or the registered local username.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
