### ISSUE TITLE
Remove video link where the video content no longer matches the current version of the challenges

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39594]
After some discussion on the forum, it was concluded the following challenges need the `videoUrl` removed from the the frontmatter of the challenge files.

* [Create a Form Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md)
* [Learn about Tertiary Colors](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/learn-about-tertiary-colors.english.md)

**Comment by AjeethT** [comment]
I am first timer to contribute it. please help with it.
We need to remove the `videoUrl` from `the create-a-form-element.english.md` right.

**Comment by RandellDawson** [comment]
@AjeethT Yes and the same goes for the other challenge too.

**Comment by AjeethT** [comment]
I removed the <videoUrl> and created a pull request for [Create a form Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md)

**Comment by RandellDawson** [comment]
@AjeethT Thank you for your contribution.

For future reference, you can make changes to multiple files on the same.  Also, you really should make your changes on a different branch than `master` to avoid soiling it.  I suggest taking a look at our documentation on [how to work on coding challenges](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=set-up-the-tooling-for-the-curriculum) when you want to work on more complex PRs.
