### ISSUE TITLE
Authentication with Socket.IO - Unclear instructions, incorrect/incomplete solution

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#39595]
**Describe your problem and how to reproduce it:**
Working on the Advanced Express problems with a server I control.

In the Authentication with Socket.IO section, you are instructed to:
> Be sure to add the key and store to the session middleware mounted on the app. This is necessary to tell SocketIO which session to relate to.

However, it is completely unexplained what this is supposed to mean or where you would do this.

I couldn't initially figure out what this even meant so I would get an error like this on the socket connection:
>`failed connection to socket.io: No session found`

 I googled around a bit and eventually figured it out.  My solution was to change the `key` definition in the `passportSocketIo.authorize` block to match the default `connect.sid` and add the `store` to my `session` definition.

When I went to check against the provided GIST/solution, it was incorrect and incomplete.

Here is the [relevant bit of code:](https://gist.github.com/camperbot/1414cc9433044e306dd7fd0caa1c6254#file-server-js-L27)
```js
app.use(session({
  secret: process.env.SESSION_SECRET,
  resave: true,
  saveUninitialized: true,
  cookie: { secure: false },
  // Missing entries for the key and store
}));
```
and also:
```js
io.use(
  passportSocketIo.authorize({
    cookieParser: cookieParser,
    key: 'express.sid',   // This is not the default cookie name, which is connect.sid
    secret: process.env.SESSION_SECRET,
    store: store,
    success: onAuthorizeSuccess,
    fail: onAuthorizeFail
  })
);
```

More clarity needs to be added to the instructions and the GIST needs to be corrected to match.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/authentication-with-socket-io

**Comment by SaintPeter** [comment]
Also, this provided code:
```js
console.log(`user ${socket.request.user.name} connected`);
```
is wrong.

It should be:
```js
console.log(`user ${socket.request.user.username} connected`);
```

**Comment by Sky020** [comment]
Thanks, for this, @SaintPeter . The missing `key` in the Gist is my fault, and I will fix it on my side just for parity. @scissorsneedfoodtoo could you update the _camperbot_ side?

> However, it is completely unexplained what this is supposed to mean or where you would do this.

I am not sure where the confusion is...there is only one _'session middleware mounted on the app'_. How would you want this explained? (I did not want any more code for a camper to copy-pasta)

Someone else with more experience will have to clarify here:
> key: 'express.sid',   // This is not the default cookie name, which is connect.sid

As far as I am aware, this does not matter, provided the two match. I assumed `'express.sid'` made sense, because it is an express app. Kris, do you have any insight?

**Comment by SaintPeter** [comment]
Maybe something along the lines of:
> Be sure to add the `key` with the cookie name to match the socket.io `key`  as well as the `store` reference to the options 
 for the session middleware, near where we set `saveUninitialized: true` . This is necessary to tell SocketIO which session to relate to.

I don't recall hearing the terminology "mounted on the app" previously and I found it confusing.  We're really talking about changing the options on the session.

I know what you mean about the cut and paste.  Not a whole lot of learning going on here, TBH.  Not sure if it is possible to get the average camper to be able to figure these things out - it's pretty complex.

**Comment by Sky020** [comment]
Fair enough. Thank you, for these suggestions. I would be happy with that wording change.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for bringing this to our attention @SaintPeter, and for all of your helpful suggestions.

I went ahead and updated that Gist and the ones after to the following:

```js
app.use(session({
  secret: process.env.SESSION_SECRET,
  resave: true,
  saveUninitialized: true,
  cookie: { secure: false },
  key: 'express.sid',
  store: store
}));
```

About the name of the key, I could go either way. Changing it to the default value seems fine, but leaving them as `'express.sid'` also works. 

We don't really explain what they are or why they work in the current lessons, so it might be best to leave them as is for now. Then if we go back and break this project down into more steps, we could start with the default value, then have a step where learners rename the keys and go into the fact that they should match.

**Comment by SaintPeter** [comment]
> We don't really explain what they are or why they work in the current lessons, so it might be best to leave them as is for now. Then if we go back and break this project down into more steps, we could start with the default value, then have a step where learners rename the keys and go into the fact that they should match.

I like this idea.  It could be the default key name initially, then by way of explanation we have them change it to match?  I'm not sure what a reason would be for changing the key name, though.  I do wonder how likely it is be that you would need to change it.  It's just as likely that express would randomly change it from `connect.sid` just to break things.

**Comment by scissorsneedfoodtoo** [comment]
@SaintPeter, that's a good point. I also don't know why you would change it from the default value unless you really had to for some reason. It could go either way, where we start at the default value and just point out that you could change it in certain situations. Or actually have them change it, though it would be rather arbitrary.

Hopefully Express doesn't go and change `connect.sid` in some later version and cause bugs if learners update Express before starting!

**Comment by NikIvan** [comment]
Hey, guys!
I just finished this project and was stuck with same problem for about an hour.
The instructions is still unclear.

Also, as @SaintPeter mentioned in this message https://github.com/freeCodeCamp/freeCodeCamp/issues/39595#issuecomment-693634106 there is inconsistency between logic of registering user using our app registration form with field `username` and registration via GitHub OAuth where user (by guide) should be stored in database with field `name`.

Do we have any agreement (proposals) on how this should be fixed?

**Comment by scissorsneedfoodtoo** [comment]
Hi @NikIvan, thanks for your feedback.

I think a good first step would be to update the wording for this challenge to the following, which is based on @SaintPeter's suggestion above:

> Be sure to add the `key` with the cookie name to match the Socket.IO `key` as well as the `store` reference to the options
for the session middleware, near where we set `saveUninitialized: true`. This is necessary to tell Socket.IO which session to relate to.

If you're interested in implementing this fix, please check out our documentation here: https://contribute.freecodecamp.org/

**Comment by NikIvan** [comment]
I have opened PR.
Also, in my humble opinion, **Advanced Node and Express** has at least one more thing to improve.

There's no explanation of why do we add `store` as `MongoStore` and why do we need it.  I think it would be cool to extract this part into separate lesson and explain difference (pros and cons) between in-memory (by default) storage of session versus storing sessions in database.

Possible location of this lesson: right after *Set up Passport*.

And probably different issue should be opened with proposition to fix this as well as an issue about 
```js
socket.request.user.name
``` 
vs 
```js
socket.request.user.username
```

**Comment by scissorsneedfoodtoo** [comment]
Hi @NikIvan, thanks for those suggestions and for your PR. We'll review it as soon as we can.

At the moment, we're trying not to add any lessons to the curriculum unless absolutely necessary. I could see there being a quick explanation of those points in "Set Up Passport", but it's probably not necessary to add another lesson to go into the pros and cons of storing the session in-memory vs in the DB.

About the other issue you mentioned about the inconsistency of user names, I can see what you mean. I believe it was done this way originally to prevent possible conflicts from storing the username from both registration methods as `user.username`, though I could be wrong.

@ShaunSHamilton, what do you think? Would it be easy to make that change? Or would it require reworking the boilerplate and a handful of the challenges?

**Comment by NikIvan** [comment]
Not sure if we should continue conversation about user names issue in this topic but just to clarify:
With current logic if we try to make conversation between GitHub registered users and signup form registered users - one group of users would have same name `undefined` in chat because on client side we relate to either `name` or `username`. 

From my understanding there are 3 ways to fix this:
- add mapping `username` -> `name`, `name` -> `name` client side
- add mapping server side before sending to client
- fix logic of storing users in DB

**Comment by ShaunSHamilton** [comment]
> it's probably not necessary to add another lesson to go into the pros and cons of storing the session in-memory vs in the DB.

I agree with this. It would be wonderful, if we could go into full detail about all the ins-and-outs of Node/Express + Socketio. However, there is little bandwidth for changing the current lessons to do such, and I would discourage large amounts of effort being put into re-working the current version of the curriculum.

The `name`/`username` issue is being tracked here: https://github.com/freeCodeCamp/freeCodeCamp/issues/39599

> @ShaunSHamilton, what do you think? Would it be easy to make that change? Or would it require reworking the boilerplate and a handful of the challenges?

As far as I can remember, there should be **no** need to change the boilerplate. It would require reworking a handful of challenges and Gists.

**Comment by jelugbadebo** [comment]
Hi all, I am having an issue with the code that @SaintPeter mentioned above: 

console.log('user ' + socket.request.user.name + ' connected');

When I include this code in **function onAuthorizeSuccess(data, accept)** in my server.js file, I get a throw error that says "socket is not defined at Object.onAuthorizeSuccess [as success] (/home/runner/boilerplate-advancednode/server.js:44:25)....."

When I delete that piece of code in **function onAuthorizeSuccess(data, accept)** in my server.js file, my app runs smoothly, with no throw errors.  Any idea what is going on?  

I can't quite seem to debug this.
