### ISSUE TITLE
Advanced Express Implementation of Social Authentication III - Deprecation for "findAndModify"

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#39592]
**Describe your problem and how to reproduce it:**
I am using the latest boilerplate for the "Implementation of Social Authentication III" challenge on a server I control.  When I copy and paste the code for the GitHub database record creation and run it, I get a deprecation warning:
```
(node:22140) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
```

According to the [MongoDB manual page](https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/), the replacement function, `findOneAndUpdate` has been in place since Mongo 3.2.  The boilerplate projects call out at least v3.6.

Deprecation notice:
https://mongoosejs.com/docs/deprecations.html#findandmodify

The sample code in the challenge should be updated to use `findOneAndUpdate`. The signature appears to be identical and worked for my code.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/implementation-of-social-authentication-iii

**Tell us about your browser and operating system:**
* Browser Name: node.js / Chrome
* Browser Version: N/A
* Operating System: Ubuntu 18.04 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Thank you, for bringing this up. You are correct in saying we should update the method used. However, there is some mismatch due to `findAndModify` having the format `(query, sort, doc, options, callback)`, and `findOneAndUpdate` having the format `(filter, update, options, callback)`. 

This mismatch is because the lessons are written to work with the MongoDB Nodejs Driver, and not necessarily the Mongoosejs API.

So, the fix would be (simply remove the `sort: {}`):
```
function (accessToken, refreshToken, profile, cb) {
            console.log(profile);
            myDataBase.findOneAndUpdate(
                { id: profile.id },
                {
                    $setOnInsert: {
                        id: profile.id,
                        name: profile.displayName || 'John Doe',
                        photo: profile.photos[0].value || '',
                        email: Array.isArray(profile.emails) ? profile.emails[0].value : 'No public email',
                        created_on: new Date(),
                        provider: profile.provider || ''
                    }, $set: {
                        last_login: new Date()
                    }, $inc: {
                        login_count: 1
                    }
                },
                { upsert: true, new: true },
                (err, doc) => {
                    return cb(null, doc.value);
                }
            );
        }
```

I do not see this as a difficult, nor pertinent,  change. So, I am opening this up to _first-timers only_

**Comment by SaintPeter** [comment]
Haha, ok, I just figured that the signature was different, since my code failed, and I was coming here to update.  Missed it by 4 minutes.

**Comment by todortotev** [comment]
I could give a shot on it. Please keep in mind I would complete it at least 2 days from now on.

**Comment by Sky020** [comment]
@todortotev , Sure. Go ahead. We normally QA the first comprehensive PR, and do not typically assign issues. So, any one is welcome to work on issues depending on the labels.

**Comment by tareq12345** [comment]
Was this issue solved or still there is a problem? in the code base sort:{} is empty.

**Comment by Sky020** [comment]
@tareq12345 It appears this issue is still open to _first-timers_. The issue still exists, because the `sort` query is still being used, despite it being an empty object literal.

**Comment by surajat17** [comment]
Is this issue solved or there's still some problem? i would like to work on it

**Comment by RandellDawson** [comment]
@surajat17 We already have a PR for this issue that is probably going to be merged very soon.
