### ISSUE TITLE
Redirects to Bonfires when you pass a waypoint. 

### ISSUE THREAD

**Issue by duttakapil** [FreeCodeCamp/freecodecamp#396]
I have some Waypoints left to do, after the curriculum was updated. And I have done most of the Bonfires. Now when I click on "I've completed this challenge" for a Waypoint, the site goes to the next Bonfire that I have not completed, instead of redirecting to the next waypoint that I have not completed.

**Comment by QuincyLarson** [comment]
Please send me a screenshot of your completed challenges and bonfires?

**Comment by duttakapil** [comment]
![FCC Map](http://i.imgur.com/5oic139.png)

**Comment by QuincyLarson** [comment]
@duttakapil Ah, that is as intended. Since you completed the last Waypoint (Pair Program on Bonfires) the system assumes you're in Bonfire "mode" and will by default send you to bonfires until you've completed them all.

**Comment by duttakapil** [comment]
But shouldn't it act like different sections? So suppose I have completed a Zipline, and then click on "next challenge", would it redirect to the next zipline that I haven't completed or the next Bonfire I haven't completed?

**Comment by QuincyLarson** [comment]
Assuming you do these in the correct order, it will. All challenges (except
for Bonfires) are of the same object type. We may merge Bonfires in to our
challenges at some point, but for now, this is the most graceful workaround
imho.


- Quincy Larson
"Anyone who has begun to think, places some portion of the world in
jeopardy." - John Dewey
