### ISSUE TITLE
Improve warnings about extensions?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#39608]
I know we added a warning about extensions to the intro page for the CSS challenges, but it is not really working. We still get many forum posts about the challenges affected by ad-block (flexbox [tweet embed](https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed) challenge) and the various color challenges affected by dark mode/dark reader extensions.

I think we have to be more explicit in the warning about which extensions can cause issues, and maybe don't use a blue background color because that is not a warning that is just information and people tend to ignore that (maybe orange/yellow instead?). Or we have to add warnings to the individual challenges. For the flexbox challenge, I think an explicit warning about ad-block might be needed because we still get forum threads about this challenge all the time.

**Comment by nhcarrigan** [comment]
I will say that the blue note stands out well on dark mode:
![image](https://user-images.githubusercontent.com/63889819/93633939-9e0fa680-f9a4-11ea-9024-40e5aaf59214.png)

But blends in a lot more on light mode:
![image](https://user-images.githubusercontent.com/63889819/93633991-b2ec3a00-f9a4-11ea-86eb-1ef8ccfa0c5e.png)

I am in favour of adding a note/warning to that challenge. There are a couple of other challenges that I frequently see posts for because dark-mode extensions interfere.

**Comment by lasjorg** [comment]
> I will say that the blue note stands out well on dark mode

It's not really the contrast that is the problem, it's the psychological response to colors. Errors are red, warnings are yellow/orange, and information is blue. This message would, in my opinion, be more a warning and not just information. An exclamation icon in front of the text might also do the trick or something to that effect.

> I am in favour of adding a note/warning to that challenge.

The only issue is we are trying to get away from having such messages on individual challenges. But in this case, it may be needed.

Another option we might want to consider is to just fix the challenge, as has already [been discussed](https://github.com/freeCodeCamp/freeCodeCamp/issues/38353), by changing the class name used on the button to something that will not get blocked. Then just remove the video. Apparently the videos are not getting updated and it was decided to just remove videos that are out of sync with challenges. That was the main issue with changing the class, as it would require the video to be updated.

**Comment by nhcarrigan** [comment]
> Another option we might want to consider is to just fix the challenge, as has already been discussed, by changing the class name used on the button to something that will not get blocked. Then just remove the video. Apparently the videos are not getting updated and it was decided to just remove videos that are out of sync with challenges. That was the main issue with changing the class, as it would require the video to be updated.

I think this is a good approach as well.

**Comment by RandellDawson** [comment]
@lasjorg If we need to remove the video due to a change to the challenge that improves the challenge, then go for it.

**Comment by ieahleen** [comment]
is this about changing the flex challenge to avoid having the button blocked, or about adding the warning, or both?

**Comment by nhcarrigan** [comment]
I believe the conclusion reached was to change the name of the button to avoid ad-blockers from blocking it.

**Comment by luqven** [comment]
I'd love to give this one a go if no one else is!

Seems like all that's needed is to change the name of the button(s) that break when ad-blockers are enabled? 

Otherwise, if there's a comprehensive list of challenges affected by ad-blockers that'd be helpful. If not I can try and snuff out as many ad-block related issues as I can myself and report back.

**Comment by nhcarrigan** [comment]
As far as I know, this is the only challenge with the tests failing due to the button being blocked. But we will want to make sure that any subsequent challenges that build on this code also reflect the change. 🙂

**Comment by ieahleen** [comment]
@luqven are you still working on this?

**Comment by luqven** [comment]
@ieahleen thanks for the heads-up, forgot to sub to that PR to know when it was merged. I'll pick this up again and make a new PR as suggested in #40272  👌🏼

**Comment by Sembauke** [comment]
Closing this one, tracking further in https://github.com/freeCodeCamp/freeCodeCamp/issues/41417#issuecomment-794892623
