### ISSUE TITLE
Fixed vs absolute Universal nav

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39604]
As discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/39580#discussion_r489477744 Cypress has a hard time with absolutely positioned elements.  Also, `fixed` seems more natural for a nav, since it always stays at the top of the viewport (and that seems to be the point of `fixed`).

Is there anything I'm missing or can we move to `position: fixed` and `click({ force: true }) -> click()`?

cc: @ahmadabdolsaheb @Twaha-Rahman

**Comment by raisedadead** [comment]
Yikes - looks like I missed that discussion. I went thru the other comments and it seemed the PR was just waiting to merged.

I assume it's something we can still fix (haven't read the whole context yet)?

**Comment by ojeytonwilliams** [comment]
> I assume it's something we can still fix 

Yeah, it's not urgent, though.  As far as I know it's fine to use `click({ force: true })` it's just a hint that something slightly odd is happening. In this case Cypress automatically scrolls the button into view before clicking and then warns because the button ends up covered by the nav.

It would be better if we didn't have to force things (it's fine right now, but I think it's a bad habit to get into).  `position: fixed` should resolve this, but I don't know if a straight replacement `absolute -> fixed` will have any side-effects.

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams  Have you tried using `fixed` and running Cypress without `force` locally?

**Comment by ojeytonwilliams** [comment]
I have, yes.  All the tests pass once you use `fixed` and stop forcing.  I'll create a draft PR so people can take a look.
