### ISSUE TITLE
Python for Everybody - isRequired set to true for all lessons

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39607]
**Describe your problem and how to reproduce it:**
It appears that all of the challenges/lessons in the Python for Everybody section of the curriculum have the `isRequired` property set to `true`.

Doing a top-level search, I did not see it in use anywhere...

This property is misleading, and should either be set to `false`, or removed as there are some lessons without it.

@beaucarnes I know you initially committed the files, was there a specific reason for the property?

**Comment by ojeytonwilliams** [comment]
Thanks Shaun, I've searched as well and it's no longer used.  It should be removed from everywhere (`challengeSchema` and mocks, too).

**Comment by Sky020** [comment]
@ojeytonwilliams Should this also be removed from all languages?
