### ISSUE TITLE
Instructions don't match test

### ISSUE THREAD

**Issue by ch4tml** [FreeCodeCamp/FreeCodeCamp#3960]
Challenge [Waypoint: Delete Properties from a JavaScript Object](http://freecodecamp.com/challenges/waypoint-delete-properties-from-a-javascript-object#?solution=var%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%2C%0A%20%20%22bark%22%3A%20%22bow-wow%22%0A%7D%3B%0A%0Adelete%20ourDog.bark%3B%0A%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Happy%20Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%2C%0A%20%20%22bark%22%3A%20%22woof%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Adelete%20myDog.bark%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(z)%7Breturn%20z%3B%7D)(myDog)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"],
  "bark": "bow-wow"
};

delete ourDog.bark;

var myDog = {
  "name": "Happy Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"],
  "bark": "woof"
};

// Only change code below this line.

delete myDog.bark;

// Only change code above this line.

(function(z){return z;})(myDog);

```
Issue:
Properties box says: 
"Let's delete the "tails" property from myDog."
Test success statement:
"Delete the property "bark" from myDog."

Test succeeds on deleting bark property, not tails.

**Comment by Petar-np** [comment]
I noticed that too

![delete properties from a javascript object issue](https://cloud.githubusercontent.com/assets/9700675/10801784/69628ebe-7db9-11e5-9904-060db095b7d0.png)
