### ISSUE TITLE
Minor issue with sample code

### ISSUE THREAD

**Issue by leftynaut** [FreeCodeCamp/FreeCodeCamp#3961]
Challenge [Waypoint: Convert JSON Data to HTML](http://www.freecodecamp.com/challenges/waypoint-convert-json-data-to-html#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON(%22%2Fjson%2Fcats.json%3Fcallback%3D%22%2C%20function(%20json%20)%20%7B%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0Ajson.map(function(val)%20%7B%0A%20%20html%20%2B%3D%20%22%3Cdiv%20class%20%3D%20'cat'%3E%22%0A%20%20for%20(var%20key%20in%20val)%20%7B%0A%20%20%20%20html%20%2B%3D%20%22%3Cdiv%20class%3D%20'%22%20%2B%20key%20%2B%20%22'%3E%22%20%2B%20val%5Bkey%5D%20%2B%20%22%3C%2Fdiv%3E%22%3B%0A%20%20%7D%0A%20%20%0A%20%20html%20%2B%3D%20%22%3C%2Fdiv%3E%3Cbr%20%2F%3E%22%0A%20%20%0A%7D)%3B%0A%20%20%0A%0A%0A%0A%0A%0A%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24(%22.message%22).html(html)%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

On the left side, the sample code switches between using double quotations at the start of a new element and using single quotations. I think this is a bit confusing for the user.

**Comment by BerkeleyTrue** [comment]
It's using both single and double quotes because it is writing string using strings and this is the best technique to use here.

**Comment by leftynaut** [comment]
so

```js
json.map(function(val) {

  html = html + "<div class = 'cat'>"

  for(var key in val) {

    html = html + '<div class = "' + key + '">' + val[key] + '</div>';

  }

  html = html + "</div><br/>"

});
```

is better than

```js
json.map(function(val) {

  html = html + "<div class = 'cat'>"

  for(var key in val) {

    html = html + "<div class= '" + key + "'>" + val[key] + "</div>";

  }

  html = html + "</div><br/>"

});
```

??

**Comment by carleyf1010** [comment]
I really just don't even want to receive anymore could you tell me how to unsubscribe from everything. 


Sent by Outlook for Android





On Wed, Oct 28, 2015 at 1:34 PM -0700, "Berkeley Martinez" <notifications@github.com> wrote:












It's using both single and double quotes because it is writing string using strings and this is the best technique to use here.

**Comment by bugron** [comment]
This is absolutely normal. Closing as not an issue with the code. Feel free to reopen if you still experience problems, thanks.
