### ISSUE TITLE
Issue Tracker Project - POST operation lacks error definition, default value for open

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#39620]
**Describe your problem and how to reproduce it:**
Here are the user stories for the POST operation for the Issue Tracker project:
>2.  I can POST /api/issues/{projectname} with form data containing required issue_title, issue_text, created_by, and optional assigned_to and status_text.
> 3. The object saved (and returned) will include all of those fields (blank for optional no input) and also include created_on(date/time), updated_on(date/time), open(boolean, true for open, false for closed), and _id.

Notably missing here are definitions for how to handle errors.  A "required" field implies that the lack of such a field will result in an error, but there is no direction given as to how to handle this.  

Additionally, the `open` field is defined as a boolean, but no default value is defined.  The logical choice is `true`.

I propose the following change to the user stories:
> If a required field is missing, return `"required fields missing: " + <comma separated list of field names>`

An example would be:
`required fields missing: issue_title,issue_text`

For the `open` value:
>  3. The object saved (and returned) will include all of those fields (blank for optional no input) and also include created_on(date/time), updated_on(date/time), open(boolean, true for open, false for closed, defaults to `true`), and _id.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker

If these changes (or alternates proposed in comments) are acceptable, I'll file a PR to update the boilerplate.

**Comment by SaintPeter** [comment]
It might also make sense to include a return status code like '400', which is "Bad Request"

>400 Bad Request
The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, **invalid request message framing**, or deceptive request routing).

(emphasis added)

Some discussion on the topic here:
https://stackoverflow.com/questions/3050518/what-http-status-response-code-should-i-use-if-the-request-is-missing-a-required

I don't know if this makes it harder to write a test for, since the XHR would "fail" in a particular way, but I think if we're expecting it we can extract the status code.

**Comment by divyavit** [comment]
Hi @SaintPeter I am up for this task. Pls let me know if I can proceed.

**Comment by nhcarrigan** [comment]
Hey there @divyavit~! Thank you for your interest in contributing!

When an issue is labelled with the `help wanted`, anyone is free to work on it - you do not need permission, and issues are not usually assigned to someone. 🙂 

We will generally accept the first pull request (PR) that provides a comprehensive fix for the issue. If you have not done so already, make sure to read our [contributing guidelines](https://contribute.freecodecamp.org).

**Comment by SaintPeter** [comment]
I was looking for some consensus.  I guess since there is no argument, this is what we'll go with?  I'm down with that.

@divyavit If you want to update the boilerplate, that would be awesome.

**Comment by SaintPeter** [comment]
There is also an oversight with the PUT verb:
> I can PUT /api/issues/{projectname} with a _id and any fields in the object with a value to object said object. Returned will be 'successfully updated' or 'could not update '+_id. This should always update updated_on. If no fields are sent return 'no updated field sent'.

There is no definition for what happens when the `_id` field is not sent. This is distinct from "no updated fields" being set, because it's possible to send an `_id` and still not have fields to update.

I propose we match the definition for the DELETE verb :
> I can PUT /api/issues/{projectname} with a _id and any fields in the object with a value to object said object. Returned will be 'successfully updated' or 'could not update '+_id, **If no _id is sent return '_id error'.** This should always update updated_on. If no fields are sent return 'no updated field sent'.

(emphasis to highlight addition only)

**Comment by SaintPeter** [comment]
This would necessitate one additional test to validate `_id not found`.

**Comment by SaintPeter** [comment]
On second thought:
> Returned will be 'successfully updated' or 'could not update '+_id.

seems to cover not being able to find the `_id`.

**Comment by SaintPeter** [comment]
@divyavit Please let me know when you'll get to this.  I have a pending PR which implements tests for these, see the link above.

Here is the complete final verbiage which needs to be updated on the boilerplate's [`views/index.html`](https://github.com/freeCodeCamp/boilerplate-project-issuetracker/blob/gomix/views/index.html):
> 2. I can POST /api/issues/{projectname} with form data containing required issue_title, issue_text, created_by, and optional assigned_to and status_text. If required fields are missing, return 'required fields missing: ' + <comma seperated list of missing fields>, IE: `<code>required fields missing: issue_title,issue_text</code>`. The object saved (and returned) will include all of those fields (blank for optional no input) and also include created_on(date/time), updated_on(date/time), open(boolean, true for open, false for closed, defaults to `<code>true</code>`), and _id.

> 3. I can PUT /api/issues/{projectname} with a _id and any fields in the object with a value to object said object. Returned will be 'successfully updated' or 'could not update '+_id. If no _id is sent return '_id error'.  This operation should always update updated_on. If no fields are sent return 'no updated field sent'.

Feel free to edit for legibility.

I can be found as `@SaintPeter#1584` on the fCC Discord if you have questions or need help.  I'm typically on during US Pacific times.

**Comment by gikf** [comment]
Hey @SaintPeter look like parts of this issue were incorporated in PRs related to other issues. Is there anything still needed to be done as a part of this issue or can it be safely closed?

**Comment by SaintPeter** [comment]
I believe that all of these issues were completed.  I'll close it out.
