### ISSUE TITLE
the Anonymous Message Board sample project has been substituted by something different

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#39623]
here: https://www.freecodecamp.org/learn/information-security/information-security-projects/anonymous-message-board

the example project: https://anonymous-message-board--freecodecamp.repl.co/

is not an anonymous message board:

![image](https://user-images.githubusercontent.com/26656284/93670062-9af5e280-fa98-11ea-9ebc-0b42a3bec0f9.png)

**Comment by nhcarrigan** [comment]
This appears to be back up and running again. @Ieahleen can you take a second look on your end?

**Comment by Ieahleen** [comment]
now it seems back to normal, yes

what was going on there?

**Comment by nhcarrigan** [comment]
I'm not sure. May have been some error on repl.it's side. Given that it's resolved, I think it's safe to close this issue for now.
