### ISSUE TITLE
Saved challenges stored for all users

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39638]
**Describe your problem and how to reproduce it:**

If you save your code `ctrl+s`, log out and then log back as a different user then the new user will see the saved code.  While this only affects users that share machines, it's clearly not intended behaviour.

Similarly, I think that failed submissions will be retried for the currently logged in user, not necessarily the user who attempted to submit them.

This might be behind some odd behaviour reported on the [forum](https://forum.freecodecamp.org/t/bug-in-the-curriculum-thiss-needs-to-be-reported/421795/).

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
