### ISSUE TITLE
Code completion problem in HTML tag img

### ISSUE THREAD

**Issue by Guru-coderZ** [freeCodeCamp/freeCodeCamp#39633]
When I use code completion for image tag, ie:-'img', it completes it as [object object], all other tags are working just fine.
Awesome tutorials btw

* Browser Name:  Google
* Browser Version: Latest
* Operating System: Windows 10 Home

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by Guru-coderZ** [comment]
👎.  The img auto completion feature is buggy.

**Comment by Ieahleen** [comment]
> 👎. The img auto completion feature is buggy.

there is no autocompletion in the editor, but if you think there is something going wrong with the editor features you can show a video or image or gif of the issue

**Comment by Guru-coderZ** [comment]
Is there an option to comment with videos

**Comment by Guru-coderZ** [comment]
> Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects. If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened. GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.
> 
I am not asking you to troubleshoot my code(I haven't shown it to you). There is an issue with the auto-completion
I am not able to add videos.
I want to show it to you.

**Comment by Ieahleen** [comment]
the freecodecamp editor doesn't have an autocomlpletion. But you can
provide a couple of screenshots, and a link to the page where you see this
happening.

Il giorno dom 27 set 2020 alle 18:25 Guru-coderZ <notifications@github.com>
ha scritto:
