### ISSUE TITLE
Personal Library Project - Improve Error Definitions, Test Coverage

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#39630]
**Describe your problem and how to reproduce it:**
The User Stories for the Personal Library project is missing an error handling definitions for the `title` field on creation.   

I propose the following changes to the user stories (changes in **bold text**).
> 1. I can post a title to /api/books to add a book and returned will be the object with the title and a unique _id. **If title is not included in the request return `missing required field title`**
...
> 8. If I try to request **, comment on, or delete** a book that doesn't exist I will get a 'no book exists' message.
> 9. All **9** functional tests required are complete and passing.

Note, as per #39435, the InfoSec user stories may be removed.

Additionally, the boilerplate should be updated to include tests for these new and existing conditions.  The following test suites should be added to the boilerplate:
* Section 'POST /api/books/[id] => add comment/expect book object with id'
   * Add 'Test POST /api/books/[id] with comment with with id not in db'

* Add Section 'DELETE /api/books/[id] => delete book object id'
  * Add 'Test DELETE /api/books/[id] with valid id in db'
  * Add 'Test DELETE /api/books/[id] with id not in db'

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/personal-library

I will file a PR if there are no objections.

**Comment by nhcarrigan** [comment]
@SaintPeter with the merge of #39642 this can be closed, now?

**Comment by SaintPeter** [comment]
@nhcarrigan I guess?  I honestly can't remember what this was for.

**Comment by nhcarrigan** [comment]
This was for the missing error handling expectations in the user stories - I believe they've been addressed in the PRs, so we can close this I think.
