### ISSUE TITLE
Add Flex Superpowers to the Tweet Embed | Your .follow-btn should have a display property set to flex.

### ISSUE THREAD

**Issue by schmelto** [freeCodeCamp/freeCodeCamp#39639]
**Describe your problem and how to reproduce it:**
Add Flex Superpowers to the Tweet Embed
Your .follow-btn should have a display property set to flex.

write source code but not accepted by test

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed

**Tell us about your browser and operating system:**
* Browser Name:  Microsoft Edge (Chromium)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/30869493/93761570-4e341800-fc0e-11ea-9bc2-fd7c7614031b.png)

**Comment by bgbraithwaite** [comment]
**Describe your problem and how to reproduce it:**
Add Flex Superpowers to the Tweet Embed
Your .follow-btn should have a display property set to flex.

Same as above, "write source code but not accepted by test"

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed

**Tell us about your browser and operating system:**
- Browser Name: Firefox 78.4.0esr (64-bit)
- Operating System: Debian 10 Buster (stable)

**Screenshot**:
![Screenshot_20201103_105038-edit](https://user-images.githubusercontent.com/478171/98009864-09320280-1dc4-11eb-8c89-01a385bf45d4.png)

**Comment by nhcarrigan** [comment]
Heya folks~!

Please be sure that you've disabled any extensions, such as ad blockers, as these interfere with the tests. Ad blockers especially, which commonly block a twitter follow button from rendering. 

Additionally, for help with code you have written it is best to use the [forum](https://forum.freecodecamp.org). Feel free to make a post there - if the community determines that there is a bug in the challenge, *then* make a GitHub issue. 🙂

**Comment by bgbraithwaite** [comment]
I didn't even think of that! Disabling uBlock Origin on freecodecamp.org fixed the issue, as did only disabling cosmetic filtering.

Thank you for a quick response!
