### ISSUE TITLE
Instructional Issue

### ISSUE THREAD

**Issue by awsaavedra** [FreeCodeCamp/FreeCodeCamp#3963]
The instructions are: "Let's delete the "tails" property from myDog."

and the test being run is "Delete the property "bark" from myDog." The test should test whether the key-value pair for tails prop is removed.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate of #3960 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
