### ISSUE TITLE
Workwindow variable in Functional Programming section

### ISSUE THREAD

**Issue by TineoC** [freeCodeCamp/freeCodeCamp#39634]
**Describe your problem and how to reproduce it:**

The problem is in the Functional Programming section from the Javascript Algorithms certificate in: Understand the Hazards of Using Imperative Code, the variable workwindow is initialized with this array:

var workWindow = new Window(['GMail', 'Inbox', 'Work mail', 'Docs', 'freeCodeCamp']); // Your mailbox, drive, and other work sites

And notice the GMail when it has to be Gmail as all the other examples are first-letter capitalized except for freeCodeCamp.

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/understand-the-hazards-of-using-imperative-code

* Browser Name: Firefox
* Browser Version: 80.0.1
* Operating System: Ubuntu

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2020-09-20 17-42-27](https://user-images.githubusercontent.com/40866642/93723016-0dce8e80-fb69-11ea-84ba-b3b18dd1ad12.png)

**Comment by nhcarrigan** [comment]
Hello~!

Are you able to provide more information? What is not working the way you expected it to?

**Comment by TineoC** [comment]
> Hello~!
> 
> Are you able to provide more information? What is not working the way you expected it to?

Sorry, now it's complete or think so

**Comment by nhcarrigan** [comment]
Ahhh I see. It should be `Gmail` not `GMail`, right?

**Comment by TineoC** [comment]
> Ahhh I see. It should be `Gmail` not `GMail`, right?

Yes :)

**Comment by nhcarrigan** [comment]
So it looks like this would need to be updated in a few places in the challenge file. The instructions, test, challenge seed, and solution all include references as `GMail`. 

Before opening this up, though, I wouldn't mind waiting for additional consensus. (I could have sworn the actual brand was `GMail` but apparently it's not...)

**Comment by TineoC** [comment]
I'm with you

**Comment by RandellDawson** [comment]
They are just representing email folder names.  The spelling of names are really not that important.  Changing "GMail" to "Gmail" feels like bike-shedding to me.
