### ISSUE TITLE
Official browser support

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39647]
Right now we recommend Chrome and Firefox on [/news/support](https://www.freecodecamp.org/news/support/), but we transpile for more than that: https://github.com/freeCodeCamp/freeCodeCamp/blob/dd7fba4558f5a0c4b2dc35ebd919c22921c0b0df/client/.babelrc#L12

Should we officially support, say, Chrome, Firefox, Edge, Safari and Opera?  If we do, we can tailor our browserlist to that and also our Cypress tests.

Whatever we decide to support, I think we should make our tooling reflect that.

**Comment by Twaha-Rahman** [comment]
Except Firefox almost all browsers are Chromium under the hood so supporting multiple browsers should be a big problem. The only browser I want to drop from the list is Safari.

That lefts us with -

1. Chrome
2. Firefox
3. Edge (The new Chromium one)
4. Opera

**Comment by ojeytonwilliams** [comment]
My rationale for including Safari was just that it's pretty popular. If we can support it, that would be good.  Could you expand a bit on why you'd prefer to drop it?

**Comment by nhcarrigan** [comment]
It would appear that, according to WikiPedia, Safari is still fairly popular:
![image](https://user-images.githubusercontent.com/63889819/93916507-84c96b80-fcbe-11ea-9f64-8daffe930b80.png)

I'm not sure if we can view browser statistics for our `/learn` platform specifically, but I'd be concerned about dropping support for an OS default browser.

**Comment by Twaha-Rahman** [comment]
My main complain/concerns with Safari was -

1. Many weird CSS issues (especially since we are going to be using CSS Flexbox and Grid moving forward)
2. Can't test e2e due to Cypress not supporting it (it's in the road map though :thinking: )

For the above mentioned reasons, I think supporting Safari would be a painful experience since we'll have to not only find weird fixes for weird Safari bugs but also we can't test them with Cypress meaning either manually testing it or shipping broken feature to prod.

(Sorry for the very late reply. This somehow slipped under my radar.)

**Comment by ojeytonwilliams** [comment]
Thanks Twaha, that makes sense.  

I've taken a look at our analytics and they're similar to the ones Nicholas posted, so ignoring Safari would be ignoring quite a lot of users.  That said, it seems sensible not to claim we support it when it's likely to be buggy (for the reasons you outlined).

How about this: transpile for Chrome, Safari, Firefox, Edge and Opera i.e. the top 5 (in that order)? Then we can update the support page as and when we're confident a browser works well enough.  At the very least we should wait until we Cypress test a particular browser.

I'll leave this open for a bit in case people want to weigh in.

cc @raisedadead

**Comment by RaspberryLime** [comment]
Please don’t drop support for Safari. It’s the default browser on macOS, iOS and iPadOS. And yes, people do want to learn to code using those devices!

**Comment by raisedadead** [comment]
@ojeytonwilliams - I am in agreement with your original proposal in the OP, if still interested please proceed or consider closing this stale.

**Comment by moT01** [comment]
We need to continue to support Safari the best we can, so nothing needs to change here.
