### ISSUE TITLE
YouTube embeds have issue loading.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39656]
https://forum.freecodecamp.org/t/tutorial-videos-on-fcc-dont-load/422178

**Comment by moT01** [comment]
I was having this issue on firefox - videos wouldn't load so I always switched to chrome if I had to see them. I disabled all my firefox security settings, reloaded the page and it works. I re-enabled all the same settings - and it still works - and when I go to any video now, it works.

Tried a few things to get them to break again, couldn't do it.
