### ISSUE TITLE
Port front end demo projects to .rocks

### ISSUE THREAD

**Issue by Goldac77** [freeCodeCamp/freeCodeCamp#39666]
The reference Tribute page used in the Tribute Page project opens in Codepen as well. Out of curiosity, I tried to copy and paste the code from the editor on the reference page to the Test Suite Template page made for the user. I wasn't really surprised but it works, there is nothing that prevents the user from copying and pasting code to pass tests.

My point is, this can lead to laziness in a way (if you just want to finish the course and have a certificate or something). Kindly do something about it, say using a different platform, or patterning with Codepen to design a custom environment for your projects. It can even deter people who require an environment where the user to forced to bring out fresh ideas, like myself.

The screenshot attached shows copied(highlighted)
 code from the reference page 
![Screenshot (1)](https://user-images.githubusercontent.com/65061618/93028012-71ecd200-f600-11ea-9860-a07b78994400.png)

Not going to lie, I was feeling lazy and just went with it for this one, maybe I won't for the other ones. Please do something about this

**Comment by kevinsmithwebdev** [comment]
Rather than having the examples in codepen, would it be good to just have them built as static pages, that they can just look at?

**Comment by nhcarrigan** [comment]
That's not a bad idea, I think. 
Campers can still use CodePen to build their own work if they choose, but the source code for the examples would be less readily available. Still accessible in the dev tools, I believe, but that is a better alternative IMO.

**Comment by kevinsmithwebdev** [comment]
Yeah, a clever coder could still find the code, but many of the beginners wouldn't know how, and at least it would be more work in that case.

**Comment by RandellDawson** [comment]
We are actually in the process of moving the front-end example projects off Codepen.

**Comment by Nickgld** [comment]
That would be awesome

**Comment by moT01** [comment]
Do we want to move these to .rocks or something else? I thought I remember a mention of github pages at one point.

**Comment by nhcarrigan** [comment]
We could move some of them to GitHub Pages, though the ones built on React will take a bit of extra help to get deployed.

**Comment by moT01** [comment]
This may have previously been answered, but I'm curious why we won't just put them on .rocks with the rest of the projects. They would all be in one place.

**Comment by nhcarrigan** [comment]
I don't remember seeing that discussion at all, tbh - and agree that .rocks would be the best solution.

**Comment by moT01** [comment]
If anyone is interested, the process would be to take the source code of each project from the [testable-projects repo](https://github.com/freeCodeCamp/testable-projects-fcc/tree/main/src/projects), maybe clean it up if needed at all, and move it to the [demo-projects repo](https://github.com/freeCodeCamp/demo-projects)

**Comment by Sembauke** [comment]
Do we still want to do this as this is now a legacy Certification?

**Comment by ShaunSHamilton** [comment]
@Sembauke This is already done, as far as I am aware.

---

Remember, this is not a legacy certification; the content has just changed - certification is exactly the same, and we use the same example projects for the certification projects.

**Comment by ShaunSHamilton** [comment]
Actually. My bad. We have ported over the RWD projects, but we have not done so for the Front End Development Libraries or Data Vis.

I will create a new issue for those.
