### ISSUE TITLE
Error in 'Waypoint: Iterate Odd Numbers With a For Loop'

### ISSUE THREAD

**Issue by ParkinT** [FreeCodeCamp/FreeCodeCamp#3966]
The code that appears when this waypoint loads **is** the answer to the challenge.

>Let's change our initialization and final-expression so we can count by odd numbers.
Push the odd numbers from 1 through 9 to myArray using a for loop.

```
var ourArray = [];
for(var i = 1; i < 10; i += 2){
  ourArray.push(i);
}
var myArray = [];
// Only change code below this line.

// Only change code above this line.
if(typeof(myArray) !== "undefined"){(function(){return myArray;})();}
```

**Comment by ltegman** [comment]
I would totally get if this lesson structure doesn't work for some people (parrot back what we already did but with a different variable name) but this is how all the waypoints in that area our structured.

**Comment by Em01** [comment]
Would a possible solution here be to remove the following:
```
var ourArray = [];
for(var i = 1; i < 10; i += 2){
  ourArray.push(i);
}
```
So just have the following in the code mirror? yet keep the bonfire instructions the same?
I am happy to implement this is you agree!

**Comment by ParkinT** [comment]
I think that makes since considering the previous lesson was __essentially__ the same exercise but with even numbers.

**Comment by Em01** [comment]
@ltegman Would you be happy with this?

**Comment by 4mifix** [comment]
Emo1 I would agree with what you are saying. Tried to work through this but nada, needs to be fixed on the server side.

**Comment by catapixel** [comment]
Agree with @4mifix that the waypoint requires implementing the example for loop for `ourArray` as the for loop for `myArray`. There is no reason to change the waypoint unless the suggestion is to remove the "example" code to make the waypoint harder for the camper...

**Comment by ltegman** [comment]
I think the point of this bug is that the rest of the waypoints don't generally have the example code using `ourArray` be the exact same code you need to do with `myArray`. There's usually some subtle difference between the two. In the one you could just copy and paste it and change `our` to `my`.

**Comment by ParkinT** [comment]
>There's usually some subtle difference between the two. In the one you could just copy and paste it

That is **precisely** the point.

**Comment by hallaathrad** [comment]
Maybe since the instructions state `for(var i = 0; i < 10; i += 2)` while running through the even numbers in `ourArray`, that's what it should be in the code. 

There's the subtle difference @ltegman refers to, methinks.

**Comment by SaintPeter** [comment]
I was following the example of other waypoints in this area, where there is sample code which is essentially the solution.

I am certainly open to removing the sample `ourArray` code.  It would definitely be somewhat more challenging.  I don't know if it would be TOO challenging.

**Comment by JesseJTF** [comment]
i dont't think it would be more or less challenging, since the way point before it has the same context, you could simply copy, paste, and add a line of code.

work smart not hard

**Comment by hallaathrad** [comment]
It should not be about ease of solving but about what makes sense from a learning standpoint... 
Why post the answer directly, when you can give a similar example code (for even numbers so people can read it along the clear and already existing instructions) and then ask the students to try it themselves, asking for enough variation (odd numbers instead).

Having the example code being the one explained in the instructions makes it much easier to digest. 
I believe the point of the exercise was to learn how to solve algorithms using a for loop, instead of an indeed very "smart not hard" copy-paste, rename the variable sort of exercise.

**Comment by ltegman** [comment]
Not sure when this got fixed, but the sample code now shows an iteration through even numbers instead of odd numbers, so the user cannot use the exact same code anymore. Closing this.

**Comment by munteanu1107** [comment]
Solution: 

// Example
var ourArray = [];

for (var i = 0; i < 10; i += 2) {
  ourArray.push(i);
}

// Setup
var myArray = [];

// Only change code below this line.

for (var x = 0; x < 10; x++){
  if(x % 2 !== 0){
    myArray.push(x);
  }
  
}

**Comment by henrihyacinthe** [comment]
for(var i =1; i<10; i +=2 ){
   myArray.push(i);
  
}
