### ISSUE TITLE
When you click run tests before you start the project it shows that 1/17 tests have been completed.

### ISSUE THREAD

**Issue by vishutdhar** [freeCodeCamp/freeCodeCamp#39669]
#### Browser Information

- Browser Name, Version:
- Operating System:
- Mobile, Desktop, or Tablet:

#### Your Code / Link to Your Pen

```



```

**Comment by RandellDawson** [comment]
@vishutdhar Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
