### ISSUE TITLE
Consolidate issues to main repo?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39664]
~~For visibility, please create issues related to this project on the [freeCodeCamp repository](https://github.com/freeCodeCamp/freeCodeCamp/issues). Thank you.~~

Edit: I have updated this issue for now so we can get some input on if we want to move the issues over to the main repo or not. If there were any issues I closed that someone was working on, feel free to reopen them - or let me know and I can do that.

**Comment by nhcarrigan** [comment]
I believe this one can be closed now, with @raisedadead migrating the issues and the merge of the bug report link change.

**Comment by raisedadead** [comment]
Move complete. Let's triage here instead.
