### ISSUE TITLE
Personal Portfolio navbar-link-test (7) not passing

### ISSUE THREAD

**Issue by Agathasta** [freeCodeCamp/freeCodeCamp#39668]
#### Issue Description

On the Personal Portfolio project, the test 
> 7. The navbar should contain at least one link that I can click on to navigate to different sections of the page

is not passing. I have 3 links on my navbar and they work (see code and CodePen link below)

#### Browser Information

- Browser Name, Version: Firefox 79.0 (64-bit)
- Operating System: MacOS HighSierra 10.13.6 (17G11023)
- Mobile, Desktop, or Tablet: Desktop

#### Your Code / Link to Your Pen
`<navbar id="navbar">`
  `<a class="menu-link" href="#welcome-section">HOME</a>`
  `<a class="menu-link" href="#projects">PROJECTS</a>`
  `<a class="menu-link" href="#profile-section">PROFILE</a>`
`</navbar>`
...
`<section id="welcome-section" class="anchor">`
...
`<section id="projects" class="anchor">`
...
`<section id="profile-section" class="anchor">`

[https://codepen.io/agathasta/pen/ExKZNOd](url)

#### Screenshot

<img width="933" alt="Screen Shot 2020-08-23 at 22 38 02" src="https://user-images.githubusercontent.com/69153207/90988215-6ffb9a00-e591-11ea-8631-01a308f748de.png">

**Comment by rip3rs** [comment]
add `<!DOCTYPE html>` at the top of the page, should fix the issue

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.

**Comment by Jdanom** [comment]
> Thank you for reporting this issue.
> 
> This is a standard message notifying you that the issue has become stale, so we are going to close it.
> 
> If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.


I've been trying to do this challenge for hours  I didn't know why links were not working read somewhere that inserting this 
snippet  at the top of the pen 

<style>
    section { height: 100vh; }
</style>

found out that it fixes the issue but it overflows the whole page ( I don't know why I'm just a newbie)
