### ISSUE TITLE
Script won't work locally

### ISSUE THREAD

**Issue by NetScr1be** [freeCodeCamp/freeCodeCamp#39671]
#### Issue Description

Inserting  the testing script either via URL or downloading a copy and calling it locally results in display:none in Chrome developer console

N.B. Placing script in <html>, <head> or <body> make no difference

The code is written in visual studio and run via live server which opens it in a browser page. There are no other issues doing this. Page refreshes every time the code is saved.

#### Browser Information

- Browser Name, Version:

Google Chrome | 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Linux
JavaScript | V8 8.4.371.19
Flash | 24.0.0.189 internal-not-yet-present
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
Executable Path | /opt/google/chrome/google-chrome
Profile Path | /home/patrick/.config/google-chrome/Default

- Operating System:

Linux kali 5.6.0-kali2-amd64 freeCodeCamp/testable-projects-fcc#1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64 GNU/Linux

- Mobile, Desktop, or Tablet:

Desktop

#### Your Code / Link to Your Pen

<script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>

<script>
    bundle.js
</script>

=================

**Comment by raisedadead** [comment]
Probably a CORS issue. Do you mind sharing a sample repo for me to reproduce this?

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
