### ISSUE TITLE
Tests for Implementation of Social Authentication Too Strict

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#39675]
The tests need to be updated to allow for the two main ways of defining routes:
```
app.get('/auth/github/callback')
  .post(passport.authenticate('local', { failureRedirect: '/' }), (req,res) => {
    res.redirect('/profile');
  });
```
**AND**
```
app.get('/auth/github/callback', passport.authenticate('local', { failureRedirect: '/' }), (req,res) => {
    res.redirect('/profile');
  });
```

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.english.md

**Comment by RandellDawson** [comment]
We need to figure how to test most things without using regex.

**Comment by Sky020** [comment]
@RandellDawson We could change the tests to ping the route, to determine if it was defined correctly?
