### ISSUE TITLE
Error in test script

### ISSUE THREAD

**Issue by Ajay121code** [freeCodeCamp/freeCodeCamp#39670]
#### Issue Description

First step of the test is showing that I have done something wrong. but i have checked my code for 10000 times and it is absolutely correct.  also i have matched my code with the help code, my code is working just fine on codepen but it is showing this issue on vscode.

#### Browser Information

- Browser Name, Version: chrome
- Operating System: windows 7
- Mobile, Desktop, or Tablet: Laptop

#### Your Code / Link to Your Pen

```



```

#### Screenshot
![image](https://user-images.githubusercontent.com/69109767/89122633-5e6d2800-d4e6-11ea-978c-733e05701f53.png)

**Comment by RandellDawson** [comment]
Hi @Ajay121code,

As there has been no response from your end for a while, we are closing this issue.

Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
