### ISSUE TITLE
Intermittent SSL certificate failures on cdn.freecodecamp.org

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#39685]
Is anybody else seeing this issue? It has happened to me multiple times over a period of time. It affects everything that uses the CDN, i.e. the test script and forum login page (script and SVG resource fail to load).

It seems very intermittent and random so I'm not really sure what is going on.

![cdn-cert](https://user-images.githubusercontent.com/28780271/94190014-cec37480-feab-11ea-94fd-79238c99d49b.png)
![cdn-cert-login](https://user-images.githubusercontent.com/28780271/94190018-cff4a180-feab-11ea-9f56-e535fbd9f962.png)
![cdn-cert-tests](https://user-images.githubusercontent.com/28780271/94190019-cff4a180-feab-11ea-8c9c-cd3749541766.png)
SSL Server Test:
![screencapture-ssllabs-ssltest-analyze-html-2020-09-25-00_20_18](https://user-images.githubusercontent.com/28780271/94206442-b95b4400-fec5-11ea-8f40-4126aa2e6494.png)

**Comment by raisedadead** [comment]
Hmm looks like the CDN is erroneously picking up the Cloudflare Certificate at times than the one from netlify.

I have been unable to reproduce this, and going to rule this out as a temporary DNS cache issue?

Please re-open if it persists.
