### ISSUE TITLE
can you please make a documentation to eazy understand

### ISSUE THREAD

**Issue by misbagas** [freeCodeCamp/freeCodeCamp#39684]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Recommended fix, suggestions (how would you update it?):**

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@misbagas Can you be more specific about what documentation you find difficult to understand?

**Comment by misbagas** [comment]
no its okay I understand about the documentation
