### ISSUE TITLE
25 + 5 Clock 'Not Reaching 00:00' Error

### ISSUE THREAD

**Issue by mplatt212** [freeCodeCamp/freeCodeCamp#39693]
Hi,

Here are two versions of the 25 + 5 clock challenge that I created.  One was made with Vanilla JS and the other in React.  Both of them fail about 6 or so tests that throw a 'Timer has not reached 00:00' error.  I'm just trying to figure out exactly what I'm missing because I can visually see the clock reach 00:00 on both of them.

https://codepen.io/mplatt212/pen/yLOGQwy?editors=0011

https://codepen.io/mplatt212/pen/OJNxJJr?editors=0010

Thank You,
Matt

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
