### ISSUE TITLE
Capitalized letters in username silently gets converted to lowercase

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#39697]
**Describe the bug**

While writing tests with Cypress, I found that in the `/settings` page when you try to change your username with a capital letter, it silently get's converted to lowercase. For example: if `Quincy` was input, it get's converted to `quincy`.

**To Reproduce**
1. Go to '/setting'
2. Click on the username change input and enter a username with capital letter
3. Click `Save`
4. See the issue

**Expected behavior**

It should show an error message or warn the user that capital letters in name will get converted to lowercase.

**Comment by nhcarrigan** [comment]
I'm seeing this in the actual input box itself. When I type "NHCARRIGAN", the input box shows "nhcarrigan" even before save.

**Comment by raisedadead** [comment]
This behavior is intentional. At the minute we have a bug with case sensitivity and it works best if usernames are in small case.

**Comment by nhcarrigan** [comment]
I figured the behaviour was intentional, but should it be silent? 
Maybe a note above/below the input that says "must be all lowercase letters"?

**Comment by raisedadead** [comment]
> Maybe a note above/below the input that says "must be all lowercase letters"?

Yes, it could be part of the validation message. A PR is welcome to clear up the confusion.

**Comment by raisedadead** [comment]
This line makes it lowercase:

https://github.com/freeCodeCamp/freeCodeCamp/blob/4e51e845bb1fd3d044ccc2b7a121584d172f5ebd/client/src/components/settings/Username.js#L99

This is something which we want to keep because of the current limitations. 

But I am not sure about yet another alert type info, because already have a couple which would clutter the UI

![image](https://user-images.githubusercontent.com/1884376/94676029-496f1280-0338-11eb-9c19-bc81f0f2596b.png)


Hey @ahmadabdolsaheb could you guide here?

**Comment by Twaha-Rahman** [comment]
I think that `Username (lowercase only)` should be enough. (We could also use `Username (lowercase alphanumeric only)` if we want to be more explicit.)

**Comment by raisedadead** [comment]
Since we haven't had any objections lets go with `Username (lowercase only)`.

**Comment by ojeytonwilliams** [comment]
We could go with:

![image](https://user-images.githubusercontent.com/15801806/95012140-2ee9b180-0636-11eb-851c-b907c1f0b3ed.png)

but have the text "Characters must be lowercase".  So, rather than transforming each character, we just validate in the usual way.

**Comment by Twaha-Rahman** [comment]
So... have a warning like that would suffice?

**Comment by ojeytonwilliams** [comment]
@Twaha-Rahman it seems odd to treat capitals differently from any other symbol we're not allowing.  With that in mind I think we should just have a warning like that and remove https://github.com/freeCodeCamp/freeCodeCamp/blob/4e51e845bb1fd3d044ccc2b7a121584d172f5ebd/client/src/components/settings/Username.js#L99

@raisedadead is that reasonable?

**Comment by raisedadead** [comment]
If we do want to remove the forced lowercasing in that input field we want to make sure its lowercased elsewhere before being sent to the API.

**Comment by ojeytonwilliams** [comment]
Sure. What I'm suggesting is that it's forced to be lowercase by validation, so you can't click submit until all the characters are lowercase.

To be on the safe side, I think we should validate in here

https://github.com/freeCodeCamp/freeCodeCamp/blob/a48ed627adaeed622a099b87d990d917b65a7561/api-server/common/models/user.js#L730

as well.

**Comment by Twaha-Rahman** [comment]
I'll be getting back to this after I get #39622 merged. That way I can add the tests for this feature in this PR.

**Comment by ojeytonwilliams** [comment]
Thanks, Twaha. Take whatever time you need.

**Comment by prolland006** [comment]
Personnality I think this is nice like that. Nothing to do!

**Comment by ieahleen** [comment]
@Twaha-Rahman still intend to continue with this?

**Comment by Twaha-Rahman** [comment]
> @Twaha-Rahman still intend to continue with this?

I'm currently quite busy. If you or anybody wants to fix it, go ahead! 😃

**Comment by ne0crank** [comment]
if it's cool with everyone, I'll take a stab. Just to confirm, we are wanting only to add the .toLowerCase() (via udpateMyUsername function) in the same area where the other pre-validation checks are performed on the username, correct?

**Comment by ShaunSHamilton** [comment]
Hey @ne0crank ,

From what I have understood in this discussion, two things need to be done:
**UI:** Camper needs to be shown a message warning them, if they try to input non-accepted characters (uppercase)
**API:** Input is validated to be only _accepted characters_, before being allowed to be sent to the DB.
