### ISSUE TITLE
Use GitHub actions for testable-projects deployments

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39704]
We would like to use GitHub actions instead of travis CI for testing and deployments.

**Comment by WebDevCaptain** [comment]
Github actions have a limit of 2000 minutes on build time. Actions also have a known bug of cron jobs schedule.

BTW, what problems you are facing with TravisCI ??

**Comment by nhcarrigan** [comment]
Heya @WebDevCaptain - I believe that actions limit only applies to private repositories.

**Comment by raisedadead** [comment]
Implemented.
