### ISSUE TITLE
embeds in forum sometimes have too big images

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#39700]
In this forum post: https://forum.freecodecamp.org/t/help-needed-html/422742 the embed for the challenge link has a freecodecamp image that is a tad too big

![image](https://user-images.githubusercontent.com/26656284/94349590-1f6ed500-0046-11eb-9f9f-ecae932aa204.png)

confront with usual embed:
![image](https://user-images.githubusercontent.com/26656284/94349593-2ac20080-0046-11eb-97fb-835ba553cd3a.png)

@nhcarrigan said there was at least an other case of this happening

**Comment by raisedadead** [comment]
Thanks for reporting. 

A quick fix to confirm if this is a bug is to check and rebuild the HTML for the post:

**more > post admin actions (wrench icon) > rebuild html**

Closing for now. Please re-open this issue if this persists and we will take a look.
