### ISSUE TITLE
Test issue for the YouTube video I am creating for FreeCodeCamp

### ISSUE THREAD

**Issue by eddiejaoude** [freeCodeCamp/freeCodeCamp#39706]
This is a test issue for a video I am creating. **Please ignore**

**Comment by ojeytonwilliams** [comment]
Hi. Please don't create spam issues as they create noise for the maintainers.  If you want to experiment, the best approach is to do so on your own fork.

**Comment by eddiejaoude** [comment]
My apologies to the maintainers. I was keen to have the freeCodeCamp repo name in the video as it is for the freeCodeCamp YouTube channel. But I will do this in a fork in the future if this is preferred by the maintainers and the video will just have to show my GitHub username instead

**Comment by ojeytonwilliams** [comment]
Well, this issue still exists if you want to reference it in your video.  However if you want to create multiple demo issues or PRs, it would be best if you did that in your own fork.  Doing it here means a lot of people will get unnecessary notifications.
