### ISSUE TITLE
Deprecated ComponentWillMount is present in React Section

### ISSUE THREAD

**Issue by aromalanil** [freeCodeCamp/freeCodeCamp#39710]
The React tutorial is containing ComponentWillMount lifecycle which is deprecated.

Page Link: https://www.freecodecamp.org/learn/front-end-libraries/react/use-the-lifecycle-method-componentwillmount

**Comment by raisedadead** [comment]
We should drop this challenge?

**Comment by aromalanil** [comment]
What is the point of including a deprecated lifecycle method ?

**Comment by moT01** [comment]
Deprecated methods are still used in codebases so I vote to leave this. There's a note explaining that it is being deprecated.

**Comment by lambao2k3** [comment]
Are you sure?

**Comment by majestic-owl448** [comment]
@lambao2k3 if you would like to contribute, please focus on more recent issues, this issue has been closed in 2020
