### ISSUE TITLE
Create single source of Machine Learning projects used with Google Colaboratory

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39717]
Create individual repos for the following Machine Learning certification projects under the freeCodeCamp organization on GitHub:

- Cat and Dog Image Classifier
- Book Recommendation Engine using KNN
- Linear Regression Health Costs Calculator
-Neural Networks SMS Text Classifier

Once created, the `learn` pages will need to be updated to include a link that will allow users to clone the GitHub repo into Google Colaboratory with a link similar to:
    https://colab.research.google.com/github/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/blob/master/Exercises_1.ipynb

For now, each projects' instructions/user stories will remain in the each repo’s `README.md` files.

@beaucarnes will be creating a PR to address this issue.

**Comment by raisedadead** [comment]
What would be the repo names? It would be quicker for me to create them and Beau or someone else can fill in the code.

**Comment by RandellDawson** [comment]
This has been completed, so I am closing.
