### ISSUE TITLE
Invalid PropTypes Sent to ShowSettings When Viewing Profile

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#39719]
If the camper (unsure if this occurs in production, but I assume so), sets any profile-related settings to private, and views their profile, an empty object is passed to many props expecting arrays:

![image](https://user-images.githubusercontent.com/51722130/94479294-80281a00-01cc-11eb-8a49-50ff4c5528b3.png)

I have been working on this side of the platform, so can get to it soon, unless someone else wants to give it a go?

**Comment by ojeytonwilliams** [comment]
Since you're already looking at this, please go ahead and create a PR.  If you do, tag me for review - I'd like to see what's going on here.

**Comment by Sky020** [comment]
Just to update: In development, at least one challenge (not project) has to be completed, in order for this bug to appear.

**Comment by max-voronov** [comment]
I've looked into this bug and have 2 observations:

1. When we do GET `user/get-session-user`, then inside the response, the type of `user.developmentuser.completedChallenges[index].files` will be array. It's actually an empty array for some reason.
2. When user completes a challenge and submits it, eventually we call a `submitComplete` redux action which updates the state with `completedChallenges` which have `files` as object and not an array.

So in one instance `files` is an array and in the other it's an object.

I also have a question about the first observation:
Why do we return an empty `files` array when we do GET `user/get-session-user`? Shouldn't it contain the solution files so we can display the user their solution if they go to a solved challenge? Right now if the user solves a challenge and submits it, and then goes back to it, they won't see their solution and will be presented with the initial incomplete challenge code.

**Comment by ShaunSHamilton** [comment]
I believe I have narrowed this down to having been broken by the introduction of the multifile editor:
- _ShowSettings.js and children expect `completedChallenges[].files` to be an array_
- This is what `completedChallenges` is, if an HTML challenge is completed:
```
[{
completedDate: 1613179279674
files: {
indexhtml: {
contents: "<h1>Hello World</h1>"
editableContents: ""
editableRegionBoundaries: null
error: null
ext: "html"
head: ""
history: ["index.html"]
key: "indexhtml"
name: "index"
path: "index.html"
seed: "<h1>Hello</h1>"
seedEditableRegionBoundaries: []
tail: ""
}
}
id: "bd7123c8c441eddfaeb5bdef"
points: undefined
username: "developmentuser"
__proto__: Object
length: 1
}]
```

This is from `gatsby-node.js`:
```
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
    type ChallengeNode implements Node {
      files: ChallengeFile
    }
    type ChallengeFile {
      indexcss: FileContents
      indexhtml: FileContents
      indexjs: FileContents
      indexjsx: FileContents
    }
```

@ojeytonwilliams This does not look like a quick fix, as I see two options:
1) Refactor the current setup to use `files` as an object
2) Rework the new (yet-to-be-used) multifile code to use `files` as an array.

Thoughts?

**Comment by ShaunSHamilton** [comment]
Last I checked, this is resolved. Closing
