### ISSUE TITLE
Project Submission Throws Uncaught Error

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#39729]
Submitting an invalid URL for the Front End projects does not behave as expected:
![image](https://user-images.githubusercontent.com/51722130/94611887-43c2ef80-029a-11eb-886e-bf505883573f.png)

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

**Expected**:
- No uncaught errors
- Camper is notified about misshapen URL

**Comment by max-voronov** [comment]
Maybe can use a pattern to enforce a correct URL. Please see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

In `FormFields` component if you add a pattern on the `FormControl` component it seems to solve the described problem but I think the pattern should be passed as part of the `options` prop and be applied conditionally.

**Comment by kostaslamo** [comment]
I could take a look on that. Is there any other similar place on the ui where errors are caught and printed to the user?

**Comment by Sky020** [comment]
@kostaslamo If you take a look at what happens with the [a clearly incorrect URL](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker)
![image](https://user-images.githubusercontent.com/51722130/94808858-a676d100-03e9-11eb-8068-7267c8647c45.png)

This is moreso an issue with just a slightly incorrect URL which still manages to match the validation, but should not.

**Comment by kostaslamo** [comment]
> @kostaslamo If you take a look at what happens with the [a clearly incorrect URL](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker)
> ![image](https://user-images.githubusercontent.com/51722130/94808858-a676d100-03e9-11eb-8068-7267c8647c45.png)
> 
> This is moreso an issue with just a slightly incorrect URL which still manages to match the validation, but should not.

Ok, so the fix in the bug should be this kind of validation under the lessons located here: https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/

**Comment by Sky020** [comment]
This bug has to do with the SolutionForm component, and the input validation for all projects. I have changed the title to reflect such.

**Comment by kostaslamo** [comment]
> This bug has to do with the SolutionForm component, and the input validation for all projects. I have changed the title to reflect such.

I will have a check for that and PR when ready.

**Comment by raisedadead** [comment]
We should probably do a validation message that shows a warning when users submit URLs which are of the commonly mistaken types for example: the editor links, run links etc,
