### ISSUE TITLE
Create single source of instructions and notes for back-end Node challenges

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39720]
Internally, we had several discussions about the pros and cons of moving all the instructions to a single place.  The final decision was to move all instructions and notes for the back-end Node challenges to `learn`.  

Main reasons for decision:

- Creates a single source for user instructions to reside.
- Makes it easier to create translations of these challenges’ instructions.

Tasks:

1. Compare instructions in all sources and conclude on which source or complication of sources will be used on `learn`.
2. Any instructions should be deleted form the boilerplate code files (i.e. `myApp.js` or `server.js`).
3. Each boilerplate README.md file should only contain a project title that links to the the applicable learn page project. Any other text should be deleted. Example:
```
# [URL Shortener Microservice](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice)
```
4. The practice challenges descriptions should indicate exactly where code should be placed in the files of the boilerplate’s project code files (i.e. myApp.js).  This is critical as we will no longer have reference points like step numbers or challenge titles to indicate where to put code.

**Notes:**
- Please limit PRs to one section or boilerplate at a time.
- PR's to boilerplates cannot be merged until changes on learn hit production.
- **If you would like to work on one of the sections, please reply so we can add your name to the table below, to avoid duplicate work by other contributors.**

| |Boilerplate|/learn|
| :-- | :--: | :--: |
|| Instructions have been removed | Instructions have been added |
|Managing Packages with npm [boilerplate](https://github.com/freeCodeCamp/boilerplate-npm/)| <ul><li>[x] Already done</li></ul> | <ul><li>[x] Already done</li><li>[x] In production</li></ul> |
|Basic Node and Express - [boilerplate](https://github.com/freeCodeCamp/boilerplate-express/)| <ul><li>[x] https://github.com/freeCodeCamp/boilerplate-express/pull/43</li></ul> | <ul><li>[x] PR - https://github.com/freeCodeCamp/freeCodeCamp/pull/39953</li><li>[x] In production</li></ul> |
|MongoDB and Mongoose - [boilerplate](https://github.com/freeCodeCamp/boilerplate-mongomongoose/)<br>Assigned to @Sky020 | <ul><li>[x] https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/31</li></ul> | <ul><li>[x] PR - #39970  </li><li>[x] In production</li></ul> |
|Quality Assurance with Chai - [boilerplate](https://github.com/freeCodeCamp/boilerplate-mochachai/)<br>Assigned to @Sky020 | <ul><li>[x] https://github.com/freeCodeCamp/boilerplate-mochachai/pull/27</li></ul> | <ul><li>[x] PR - https://github.com/freeCodeCamp/freeCodeCamp/pull/39976</li><li>[x] In production</li></ul> |
|Advanced Node and Express - [boilerplate](https://github.com/freeCodeCamp/boilerplate-advancednode/)<br>Assigned to @Sky020 | <ul><li>[x] https://github.com/freeCodeCamp/boilerplate-advancednode/pull/15/ </li></ul> | <ul><li>[x] PR - https://github.com/freeCodeCamp/freeCodeCamp/pull/39791</li><li>[x] In production</li></ul> |
|Information Security - [boilerplate](https://github.com/freeCodeCamp/boilerplate-infosec/)| <ul><li>[x] https://github.com/freeCodeCamp/boilerplate-bcrypt/pull/8 </li><li>[x] https://github.com/freeCodeCamp/boilerplate-infosec/pull/27</li></ul> | <ul><li>[x] PR - https://github.com/freeCodeCamp/freeCodeCamp/pull/39954</li><li>[x] In production</li></ul> |

**Comment by nhcarrigan** [comment]
I can jump in and start helping with some of these.

**Comment by moT01** [comment]
I looked over this plan, and I think it looks good. Just keeping it as a discussion for a very short time in case anyone can point out any issues with making these changes.

**Comment by Sky020** [comment]
@RandellDawson 
Randell, I have some time to work on the _Advanced Node_ section. I have a bit of experience with it, anyway.

**Comment by Sky020** [comment]
@RandellDawson and @moT01 I am going to need a bit of guidance with how to do the Chai instructions. I will add my PR now, but it will likely need more challenges added

**Comment by moT01** [comment]
I think we are good to close this since it looks like all of the instructions have been moved over to learn. I know there's a few PR's out there to clean up some things - those will get in when the code freeze is over. Thanks for all the work on this everyone 🎉 If there's still any concerns with this, let me know and we can reopen it.
