### ISSUE TITLE
Standardize links in curriculum

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39739]
The curriculum (project and challenge pages) contain links to various places; github, codepen, replit, etc. Sometimes they open in a new tab, sometimes not. Sometimes they contain `rel="noopener noreferrer"`, sometimes not.

We could go through and make them all consistent? Adding `target="_blank" rel="noopener noreferrer nofollow"` to all of them?

[Here's a good article explaining the `rel` values](https://pointjupiter.com/what-noopener-noreferrer-nofollow-explained/)

Not sure what we all want to use. I think we could make them all open in a new tab at the least.

----

Edit: 

For links with these format, `[hexadecimal numbers here](https://www.freecodecamp.org/news/hexadecimal-number-system/)` regex `/\[(.*?)\]\((.*?)\)/gm` should target them and `<a href="$2"target="_blank" rel="noopener noreferrer nofollow">$1</a>` will swap them into `<a href="https://www.freecodecamp.org/news/hexadecimal-number-system/"target="_blank" rel="noopener noreferrer nofollow">hexadecimal numbers here</a>`

**Comment by Sky020** [comment]
I agree, `target="_blank"` should be used.

It sounds like `noopener` and `noreferrer` are useless in this case. So, do not include them (waste of space)

`nofollow` sounds like it could be beneficial, but SEO is a wormhole. So, I will not advise either way.

**Comment by rajatgupta24** [comment]
Hi guys, I'm interested and want to work on this can you please guide me.

**Comment by Sky020** [comment]
@rajatgupta24 Hello there,

This issue is not quite open for contributions (indicated by help wanted or first-timers only labels). So, I suggest you take a look at another issue with either of those labels, and circle back to this, if it is made ready for contributions. Also, be sure to checkout our [Contributing Docs](https://contribute.freecodecamp.org/#/)

**Comment by rajatgupta24** [comment]
Ok Thanks @Sky020

**Comment by moT01** [comment]
Reopening, since the merged PR was reverted.

**Comment by LauraJaime8** [comment]
> @rajatgupta24 Hello there,
> 
> This issue is not quite open for contributions (indicated by help wanted or first-timers only labels). So, I suggest you take a look at another issue with either of those labels, and circle back to this, if it is made ready for contributions. Also, be sure to checkout our [Contributing Docs](https://contribute.freecodecamp.org/#/)

Hi!!! Is open for contributors now? Thanks!

**Comment by ojeytonwilliams** [comment]
> New Solution: change the markdown to use anchor tags and add the target=_blank

I'll look into that, but I'm not sure if/when that will be possible.

**Comment by sidemt** [comment]
Thank you all for working on this! I noticed an issue with regards to translation.

It looks like if you nest markdown syntax within HTML tags, Crowdin (translation tool) can't parse them properly.

For example, the string below in [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/7fc4367abd0fd7cb29549f5045007ce594e02041/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions.md):
```
Remember that <a href="https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables" target="_blank" rel="noopener noreferrer nofollow">`undefined` is a keyword</a>, not a string.
```
will appear like below on Crowdin, which does not trigger the [QA check](https://contribute.freecodecamp.org/#/how-to-translate-files?id=quality-assurance-checks) for `<code>` tags. ([Crowdin link](https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/22980/en-ja/132#1198559))
![image](https://user-images.githubusercontent.com/25644062/173895161-804643d0-ea23-4e17-bade-3b6dc35b3443.png)

It should work correctly if you change the backticks to `<code>` tags.

Note: Backticks work fine when they are not inside HTML tags.

**Comment by Sboonny** [comment]
Thank you for bringing this up, I will update it
