### ISSUE TITLE
News section - Level 5 heading (h5) style is inconsistent with other headings

### ISSUE THREAD

**Issue by robole** [freeCodeCamp/freeCodeCamp#39738]
Level 5 heading is navy and center-aligned. The other headings are left-aligned and are black.

![h5](https://user-images.githubusercontent.com/3703647/94695556-9ff44500-0368-11eb-821c-c44951e57772.png)

**Comment by codewithdev** [comment]
I can work with it.

**Comment by dhanush1909** [comment]
Hi @codewithdev, Have you started working on this? If not I can take it up

**Comment by dhanush1909** [comment]
started working on this

**Comment by Ismailtlem** [comment]
How to reproduce this issue ?

**Comment by raisedadead** [comment]
![image](https://user-images.githubusercontent.com/1884376/116516345-223aec80-a8eb-11eb-8d0f-1935f4b03be8.png)
