### ISSUE TITLE
Missing Repository for Data Reading Section - Data Analysis with Python Certificate Course

### ISSUE THREAD

**Issue by hectormikel** [freeCodeCamp/freeCodeCamp#39748]
Hi. I clicked on the ‘Notebooks on Github’ to get the files needed for the Data Reading section but the page was not found (error 404). Is there another link where I can access these files? Thanks!

Here’s a link to the course: https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/reading-data-introduction

![image](https://user-images.githubusercontent.com/64129425/94777267-c2806f80-03f5-11eb-808b-423552f4a127.png)

Error: https://github.com/ine-rmotr-curriculum/RDP-Reading-Data-with-Python-and-Pandas

![image](https://user-images.githubusercontent.com/64129425/94777372-f8bdef00-03f5-11eb-8c94-f4bf612147dc.png)

**Comment by codewithdev** [comment]
this repo can be created by the author itself to check auto workflow pass by any user.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/96353667-2ad08180-1083-11eb-8adc-7fc8cd12efab.png)

I click that same link in the lesson and am able to get to the repository with no errors.

**Comment by Ieahleen** [comment]
As it seems is resolved, I'm closing this.

**Comment by Tucker992** [comment]
Please reopen and investigate this issue. I attempted to access the link today and hit the 404 page as described by OP. When I searched INE's repository, there's no content related to Reading Data with Python and Pandas. Thank you.

**Comment by Anay21110** [comment]
I have updated the link.

Waiting for the approvals !

**Comment by Sembauke** [comment]
@ieahleen, I can see a lot of confusion with the opened PR's. Could you be a little more specific on what the link should link to?

**Comment by Nirajn2311** [comment]
Currently 4 files have broken links to a repo. The links have to be updated to https://github.com/krishnatray/RDP-Reading-Data-with-Python-and-Pandas

The 4 files with the broken links are:
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/reading-data-csv-and-txt.md
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/reading-data-from-databases.md
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/parsing-html-and-saving-data.md
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/reading-data-introduction.md

**Comment by bkelley361** [comment]
I have updated all 4 links and submitted the PR.
