### ISSUE TITLE
React: Render Conditionally from Props Incorrect Line Reference

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39741]
The challenge seed has since been updated, and this paragraph is _out of line_ 😉 
> First, you'll need a simple expression that randomly returns a different value every time it is run. You can use `Math.random()`. This method returns a value between 0 (inclusive) and 1 (exclusive) each time it is called. So for 50/50 odds, use `Math.random() >= .5` in your expression. Statistically speaking, this expression will return true 50% of the time, and false the other 50%. On line 30, replace the comment with this expression to complete the variable declaration.

This should be reworded to not make a line reference.

I suggest:
> ...Statistically speaking, this expression will return true 50% of the time, and false the other 50%. In the `render` method, replace `null` with the above expression to complete the variable declaration.

---
Challenge: https://www.freecodecamp.org/learn/front-end-libraries/react/render-conditionally-from-props

**Comment by RandellDawson** [comment]
I agree.

**Comment by HaramanJohal** [comment]
Can I have a bash at this?
