### ISSUE TITLE
Error in description of "Waypoint: Delete Properties from a JavaScript Object"

### ISSUE THREAD

**Issue by Takumar** [FreeCodeCamp/FreeCodeCamp#3974]
The instruction for [exercise](http://www.freecodecamp.com/challenges/waypoint-delete-properties-from-a-javascript-object) says:
`Let's delete the "tails" property from myDog.`
The test for this exercise tests if property bark() is deleted:
`Delete the property "bark" from myDog.`

Example in description is entire solution for this exercise:
`delete myDog.bark;`

**Comment by ltegman** [comment]
This was recently fixed by PR #3967 and is pending a deployment to the website.

Closing as fixed.

Thanks and happy coding!
