### ISSUE TITLE
Client Sentry integration

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39751]
**Is your feature request related to a problem? Please describe.**
Currently, errors in the client are silently ignored.

**Describe the solution you'd like**
Similarly to the api-server, it would be good if we could report errors to Sentry.

**Describe alternatives you've considered**
Nothing obvious leaps to mind - Sentry works well.

**Additional context**
We would need to be careful not to overwhelm the quota and only report things that are genuinely unexpected.  

There is already some code lying around from a previous attempt: https://github.com/freeCodeCamp/freeCodeCamp/issues/39574#issuecomment-701344881

**Comment by Kannndev** [comment]
@ojeytonwilliams  I could pick this up if you could share me the auth token, project, organization, and sentry DSN URL details.

**Comment by ojeytonwilliams** [comment]
Hi @Kannndev, sorry for the delay getting back to you.

Unless I'm missing something, you would not need any of that for local development.  When I was setting up the api monitoring, I just tested things using a free-tier Sentry account.  

Once we're confident it's not too noisy, we can set up a new DSN and put it into production.

**Comment by TristanToye** [comment]
@ojeytonwilliams is this still something that would be helpful?

**Comment by nhcarrigan** [comment]
Yep that was perfect thanks @ojeytonwilliams!
