### ISSUE TITLE
Test case bug in Delete Properties in JS Object waypoint

### ISSUE THREAD

**Issue by Salvero** [FreeCodeCamp/FreeCodeCamp#3975]
## Waypoint: Delete Properties from a JavaScript Object

```
We can also delete properties from objects like this:

delete myDog.bark;

Let's delete the "tails" property from myDog.


// --> Delete the property "bark" from myDog.
```
[Delete Properties Link](http://www.freecodecamp.com/challenges/waypoint-delete-properties-from-a-javascript-object#?solution=var%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%2C%0A%20%20%22bark%22%3A%20%22bow-wow%22%0A%7D%3B%0A%0Adelete%20ourDog.bark%3B%0A%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Happy%20Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%2C%0A%20%20%22bark%22%3A%20%22woof%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Adelete%20myDog.tails%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(z)%7Breturn%20z%3B%7D)(myDog)%3B%0A)

Instruction is not clear, we are asked to delete "tails" but the test required us to delete "bark" property. 

![properties_js](https://cloud.githubusercontent.com/assets/9256193/10807880/3ce77a00-7dbb-11e5-8f8c-172ac202a728.png)

**Comment by ltegman** [comment]
This was recently fixed by PR #3967 and is pending a deployment to the website.

Closing as fixed.

Thanks and happy coding!
