### ISSUE TITLE
Is the express .env exercise correct?

### ISSUE THREAD

**Issue by santimirandarp** [freeCodeCamp/freeCodeCamp#39765]
**Description**

Extract from the exercise:

> 
> The .env file is a hidden file that is used to pass environment variables to your application.
> ...

[Link to the exercise.](https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-the--env-file)

We write  a `.env` file holding a VAR=something. We can console log this variable, by running "Run" in a repl.it file. 

But this is not the standard Node.js behavior. `npm start` or `node server.js` won't load any variable unless we include the `dotenv` package. So If any user tries to emulate that project locally, it won't work the same.

I may be missing something simple, but just find it strange, and asking in repl.it didn't help much so far.

**Add a Link to the page with the problem:**

Because it's a hidden file the only way is to build it yourself. A way is to [create a new repl.it](https://repl.it/github/freeCodeCamp/boilerplate-express) and a `.env` file, then console logging the value.

**Directory Tree Image**

![fcc-dotenv](https://user-images.githubusercontent.com/29411936/94837735-8ad0f200-040c-11eb-9d82-ed2ea2d83f0d.jpg)

**Comment by TAbhay** [comment]
Can you assign this issue to me ?

**Comment by RandellDawson** [comment]
@TAbhay We have yet to determine if this is a bug.  We will attach a `help wanted` label once we make the determination of what needs to done.

**Comment by nhcarrigan** [comment]
To address the issue:

I believe repl.it (like Glitch) parses the environment variables behind the scenes. It is true that local development (and possibly some hosting providers) will require the use of the `dotenv` package (or something similar). It is worth adding a note to this challenge explaining this?

**Comment by RandellDawson** [comment]
@nhcarrigan This is the same issue that was present on the Advanced Node challenges (and probably many others).  Maybe we just need to update the boilerplate to already have the `dotenv` package in `package.json` and add the `require('dotenv').config()` line as the first line of the `myApp.js` file.

**Comment by santimirandarp** [comment]
> To address the issue:
> 
> I believe repl.it (like Glitch) parses the environment variables behind the scenes. It is true that local development (and possibly some hosting providers) will require the use of the `dotenv` package (or something similar). It is worth adding a note to this challenge explaining this?

I - as someone that is learning - believe it is. But I cant speak for everyone. Also, I asked on repl.it, and no one gave me a clear answer of what happens when you press "Run" (cause it should just run `node start` but something else it's going on there).

And if you open up the event run from "Run" it's just imposible to understand (for me at least).

**Comment by TAbhay** [comment]
Just do
1) **npm install dotenv**
2) Add **require('dotenv').config()** in myApp.js file
3) Add **.env** file with **PORT = 3000**
4) Now **npm start**
It will work

**Comment by TAbhay** [comment]
https://repl.it/join/knrubabi-tabhay1

**Comment by santimirandarp** [comment]
> Just do
> 
>     1. **npm install dotenv**
> 
>     2. Add **require('dotenv').config()** in myApp.js file
> 
>     3. Add **.env** file with **PORT = 3000**
> 
>     4. Now **npm start**
>        It will work

If you read the issue, you'll find out I've done that, but that should be clear from the exercise. Plus that's not the main problem, the problem is that because something is loaded in the background, understanding how it works is made more difficult. For example, do you know why console logging a .env variable runs fine without the .dotenv package? You might do, I doubt someone that is learning will.

**Comment by nhcarrigan** [comment]
@RandellDawson I think that's probably the best approach. 🙂

**Comment by ojeytonwilliams** [comment]
That makes sense to me, too.  We'd like to be as platform agnostic as possible and `dotenv` helps with that.

It might be worth re-wording the challenge slightly, too:

> This file is secret, no one but you can access it, and it can be used to store data that you want to keep private or hidden.

to

> This file should be kept out of version control, then it can be used to store data that you want to keep private or hidden.

and

> The environment variables are accessible from the app as

to 

> The `dotenv` package makes the contents of `.env` accessible in the app as

**Comment by Sky020** [comment]
Sounds like we are set on:
1) Add `dotenv` to the `package.json`
2) Require it in the appropriate location
3) Use Oliver's wording (above), for clarity

**Comment by VeraZab** [comment]
Hey guys, linked a pr for adjusting the boilerplate code above, if you'd like to review.

**Comment by csmiceli** [comment]
I just finished the APIs and microservices cert. Many of those projects used a "sample.env", which didn't work at all. I needed to rename on my local and drop into the repl.it project. The require('dotenv') is there.

**Comment by nhcarrigan** [comment]
> Many of those projects used a "sample.env", which didn't work at all. I needed to rename on my local and drop into the repl.it project.

This is standard behaviour - the `sample.env` file exists to show the required `env` values. You can copy or rename it to `.env` and fill in the secrets. 🙂

**Comment by nhcarrigan** [comment]
Do we want to go through and add the `dotenv` package to all of the boilerplate repositories that rely on environment variables?

**Comment by santimirandarp** [comment]
afaik in repl.it they put all effort in making dotenv not work as expected. imho the best way is to explain the user how it should be done locally, and that this is already set in the background by repl.it.

So `dotenv` should be removed as a package, and `.env` will work the same. 
I may be wrong.

**Comment by csmiceli** [comment]
dotenv feels like a hack. repl.it should have a built in way to add environment variables to containers -- or whatever they are using. Beyond control of this repo, I suppose.

**Comment by nhcarrigan** [comment]
Repl.it handles environment variables natively. However, `dotenv` *is* required for local development, which is where this discussion is going, I believe.

Testing this with a brand new repl.it instance, and I am able to log environment variables without `dotenv`.

**Comment by RandellDawson** [comment]
> Do we want to go through and add the dotenv package to all of the boilerplate repositories that rely on environment variables?

If we teach the user to user about using `dotenv` (I can not remember if we do), then the boilerplates for the projects should not come with it.  The projects should have the absolute minimum possible and the user adds the necessary libraries/code to implement the projects.

**Comment by nhcarrigan** [comment]
From a quick glance, we don't seem to mention the `dotenv` package currently. 

Would it be a better approach to modify the "Use the .env File" challenge to include instructions on using `dotenv` for local development?

**Comment by RandellDawson** [comment]
> Would it be a better approach to modify the "Use the .env File" challenge to include instructions on using dotenv for local development?

I like this idea.

**Comment by nhcarrigan** [comment]
Okay, so we could add the following text to the [challenge file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/basic-node-and-express/use-the-.env-file.md) at the end of the `Instructions` section:

```md
If you are working on this challenge locally, you will need to use the `dotenv` package for node to properly read the `.env` file. Install the package with `npm install dotenv` in your terminal. Then, at the top of your `myApp.js` file, import the package with `const dotenv = require('dotenv') and load the environment variables with `dotenv.config()`.
```

@RandellDawson if you're happy with this verbiage/approach I think we could open this one up to first-timers?

**Comment by santimirandarp** [comment]
you know better but saving a line here is justified requires('dotenv').config()

because dotenv is not needed for anything else afterwards

**Comment by nhcarrigan** [comment]
While you are correct, `require('dotenv').config()` works just fine, I'd argue that the two line approach will be more clear and understandable for campers at this point in the curriculum.

**Comment by RandellDawson** [comment]
@nhcarrigan I am leaning towards the one liner, since that is typically how I have seen it used.  I also think we can just state the user should install the `dotenv` package to properly read the `.env` file and take out the part about "if working on the challenge locally".  If the user installs the package on repl.it or Glitch, it will not hurt anything. How about changing the `Instructions` section to the following:

>Let's add an environment variable as a configuration option.
>
>Store the variable `MESSAGE_STYLE=uppercase` in the `.env` file. Then tell the GET `/json` route handler that you created in the last challenge to transform the response object’s message to uppercase if `process.env.MESSAGE_STYLE` equals `uppercase`. The response object should become `{"message": "HELLO JSON"}`.
>
>You will need to install the `dotenv` package  using `npm install dotenv` in your terminal (if not using repl.it). Then, at the top of your `myApp.js` file, import and load the environment variables with `require('dotenv').config()`.

**Comment by nhcarrigan** [comment]
That approach looks good to me. 🙂

**Comment by RandellDawson** [comment]
@santimirandarp Any thoughts on my last suggestion above?

**Comment by santimirandarp** [comment]
> @santimirandarp Any thoughts on my last suggestion above?

Looks good to me. But since repl.it is a bit unpredictable, I'd test there are no troubles if the user actually includes the package, I'll test it now.

**Comment by ShaunSHamilton** [comment]
Just to mention/remention it: On the forum, it comes up surprisingly often that campers get confused that a `.env` file needs to be created. So, could we change @RandellDawson suggestion to include this:

>Let's add an environment variable as a configuration option.

>Create a new `.env` file, and store the variable `MESSAGE_STYLE=uppercase` in it. Then tell the `GET` `/json` route handler that you created in the last challenge to transform the response object’s message to uppercase if `process.env.MESSAGE_STYLE` equals uppercase. The response object should become `{"message": "HELLO JSON"}`.

>You will need to install the `dotenv` package using `npm install dotenv` in your terminal (if not using repl.it). Then, at the top of your myApp.js file, import and load the environment variables with `require('dotenv').config()`.

**Comment by paulywill** [comment]
@RandellDawson Was this issue discussed before repl.it removed the ability to add `.env` files?

![image](https://user-images.githubusercontent.com/602422/121224914-01a17300-c857-11eb-9cb8-133fcbe49225.png)

**Comment by ShaunSHamilton** [comment]
@paulywill Sorry for butting in, but yes. We did try to clarify that with this line:
> Note: If you are using Replit, you cannot create a .env file. Instead, use the built-in SECRETS tab to add the variable.

We can probably close this issue as stale, because there have been changes to the lesson, and it comes up slightly less frequently.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
