### ISSUE TITLE
red text

### ISSUE THREAD

**Issue by Imnotgood1** [FreeCodeCamp/FreeCodeCamp#3977]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%0A%E2%80%89%E2%80%89.red-text%20%7B%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89color%3A%20red%3B%0A%0A%E2%80%89%E2%80%89%7D%0A%0A%3C%2Fstyle%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E.%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>

  .red-text {

    color: red;

  }

</style>
<h2>CatPhotoApp</h2>
<h2 class="red-text">CatPhotoApp</h2>.
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```
it just wont turn red!

**Comment by ltegman** [comment]
Looks like you copied and pasted the example code from the sidebar, which has "thin space" characters in it. Using this character as whitespace makes your css invalid. You're always better off typing the code yourself -- it's good for muscle memory and practice!

Also, the directions ask you to add the `red-text` class to your existing h2, not create a new one, so you'll need to delete the second one and move the `class="red-test"` into the first one.

Closing as not an issue with the tests, but feel free to reply if you need further clarification.

Thanks and happy coding!

**Comment by Imnotgood1** [comment]
hat stinks is. now I will never know what my actual problem was. Since I deleted and replaced the text. Sorry for bugging you!
