### ISSUE TITLE
Timestamp Microservice exercise test fails although manual investigation with the tests is work fine

### ISSUE THREAD

**Issue by avijit1258** [freeCodeCamp/freeCodeCamp#39776]
I have been trying to evaluate my code for the timestamp microservice challenge. But all the test cases fails. I tested manually with the testing set, it looks my code is working well for them. It looks like there is some bug causing the problem. Here is my public url for the timestamp microservice project. https://timestamp-microservice.avijitbhattacha.repl.co .

For further investigation, I put the solution code to my project and run the server. Still I am failing all the test cases. 

https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 14.0
* Operating System: Mac OS

![Screen Shot 2020-10-01 at 4 53 41 PM](https://user-images.githubusercontent.com/10563596/94871212-b6e97480-0406-11eb-8912-bb988ed1fe3e.png)

**Comment by avijit1258** [comment]
Actually, I was building the API from scratch without using the boilerplate code in Repl.it. So, in my server code this line was missing. 

`var cors = require('cors');`
`app.use(cors({optionsSuccessStatus: 200}));` 

After adding that my code worked like a charm.

**Comment by avijit1258** [comment]
Is it possible to show some error message if the problem is not failing the test cases? That might a save a lot of time for other situations also.

**Comment by nhcarrigan** [comment]
We are working on improving the tests - one of the things under consideration is returning more clear error messages when a test does not pass. 

However, our [forums](https://forum.freecodecamp.org) are the best place to get assistance with your code - if the community determines there is a bug in the curriculum itself, then an issue should be opened. 

It does look like you've solved this issue, so I am going to go ahead and close it. Happy coding! 😎
