### ISSUE TITLE
CORS blocking me from submitting package.json solution?

### ISSUE THREAD

**Issue by rogfut** [freeCodeCamp/freeCodeCamp#39779]
**Describe your problem and how to reproduce it:**
I am trying to complete the first managing [packages challenge](https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package) but after submitting what I believe to be the correct answer via my [repl.it URL](https://repl.it/@rogfut/ThoseIroncladMice#package.json) or my [github url](https://github.com/rogfut/boilerplate-npm/blob/rogfut/package.json), the page throws `package.json should have a valid "author" key`

my package.json passes my linter and my answer looks like other known solutions such as [this one](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/301528)

Upon inspecting the google chrome console, I see that I am getting CORS errors when I click on the submit button:

```
Access to XMLHttpRequest at 'https://repl.it/@rogfut/ThoseIroncladMice/_api/package.json' from origin 'https://www.freecodecamp.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package

**Tell us about your browser and operating system:**
* Browser Name:  Chrome
* Browser Version: Version 85.0.4183.121 (Official Build) (64-bit)
* Operating System:  Windows 10.0.18363
![fcc_error_10_1_2020](https://user-images.githubusercontent.com/17055161/94895740-d69d8e80-0440-11eb-85b0-2f78137ca038.png)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by nhcarrigan** [comment]
Hello~!

The link you are submitting is to the `package.json` file. You should be submitting a live link to your project (I believe it would be `http://thoseironcladmice.rogfut.repl.run/`). 

Go ahead and give that a shot. If that doesn't work, I recommend going to the [forums](https://forum.freecodecamp.org) for assistance with your code. For now, I am going to close this issue 🙂  If the community members determine that there is indeed a bug in the tests, then feel free to provide the relevant information and request we reopen this. 😁

**Comment by rogfut** [comment]
Neither using the [run url](http://thoseironcladmice.rogfut.repl.run/) nor the [repl project root url](http://thoseironcladmice.rogfut.repl.run/) work and both throw errors in google chrome and edge as well.  The first throws an insecure error (must be https), and the second a CORS error.

`Access to XMLHttpRequest at 'https://repl.it/@rogfut/ThoseIroncladMice/_api/package.json' from origin 'https://www.freecodecamp.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`VM35 frame-runner.841d1da76cdc88e006de.js:25 Mixed Content: The page at 'https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://thoseironcladmice.rogfut.repl.run/_api/package.json'. This request has been blocked; the content must be served over HTTPS.`

My understanding is that these CORS errors are server side issues as explained in [this SO post](https://stackoverflow.com/questions/36958999/cors-is-it-a-client-side-thing-a-server-side-thing-or-a-transport-level-thin)

I will make a forum post as suggested and will link it back here.

**Comment by nhcarrigan** [comment]
A quick glance at your code doesn't cause anything to pop out at me. 
I am headed out for the night, so I will go ahead and reopen this for visibility. I do recommend making the forum post still. 🙂

**Comment by rogfut** [comment]
This can be closed, this forum post from today resolved my issue and did not throw a CORS error.  The trick is to click run in the repl.it project and paste in the link provided.  This wasn't clear from the instructions at the beginning of the packages challenge [here](https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/)

![run](https://user-images.githubusercontent.com/17055161/94897815-3d24ab80-0445-11eb-9bb1-23daa77c8de0.png)

Hopefully this helps others who may run into this.

Thank you for the help!
