### ISSUE TITLE
docs: incorrect relative linking in translations

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39785]
To add to this issue:

- Navigate to the translations: https://contribute.freecodecamp.org/#/_translations
- Choose anything but English: https://contribute.freecodecamp.org/#/i18n/Afrikaans/index
- Click on a nav link such as _Reply Templates_: https://contribute.freecodecamp.org/#/i18n/Afrikaans/flight-manuals/using-reply-templates
- Try to navigate anywhere else: https://contribute.freecodecamp.org/#/i18n/Afrikaans/flight-manuals/how-to-setup-freecodecamp-locally

Malformed URL appears 🎉

_Originally posted by @Sky020 in https://github.com/freeCodeCamp/freeCodeCamp/issues/39784#issuecomment-702889697_

**Comment by raisedadead** [comment]
This should be a missed alias config or something. I will check this, thanks for letting me know.

**Comment by ZITANIMohamed98** [comment]
Arabic translation have alot of grammatical errors can i work on this ?

**Comment by Sky020** [comment]
@ZITANIMohamed98  Thank you, for your interest in contributing. This issue is not related to the word translations of any language, but the routing of the page.

So, I recommend you find an issue with either a _help wanted_ or _first-timers only_ label. Those are open to contribution. Also, if you have not already, take a read of the [contributing docs](https://contribute.freecodecamp.org/#/index)

**Comment by raisedadead** [comment]
This should now have been resolved with a simplified navigation.

**Comment by Sky020** [comment]
@raisedadead This seems to be working well now. Only things I have noticed:
![image](https://user-images.githubusercontent.com/51722130/96883266-212a8d80-1478-11eb-9c17-e00720260236.png)

⬆️ _Moderator Handbook_ children end up as _Reply Template_ children. Not a big deal; nothing breaks.

2) Translations do not have the Introduction page: https://contribute.freecodecamp.org/#/i18n/Chinese/README

**Comment by Sky020** [comment]
Also, if you traverse from a _right-to-left_ language (Arabic, Chinese), then go to English, the text remains _right-to-left:
![image](https://user-images.githubusercontent.com/51722130/96883995-ed039c80-1478-11eb-9dec-51bc486b391a.png)

**Comment by raisedadead** [comment]
Thanks Shaun. Have some fixes on the way, some need to be investigated.
