### ISSUE TITLE
docs: formatting issue on markdown templates

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39784]
Screenshots are quite self-explanatory:

From the [Afrikaans translation](https://contribute.freecodecamp.org/#/i18n/Afrikaans/flight-manuals/using-reply-templates):
![image](https://user-images.githubusercontent.com/51722130/94956235-bd015300-04e3-11eb-8806-f3ad9135c927.png)

From the [English Translation](https://contribute.freecodecamp.org/#/flight-manuals/using-reply-templates):
![image](https://user-images.githubusercontent.com/51722130/94956263-ca1e4200-04e3-11eb-83c3-5d516341a121.png)

Neither is correct, but it is odd that they are different as well.

@raisedadead _Separate issue: I was unsure whether to include the _crowdin-sync_ label in this. Could a description be added to that label?

**Comment by Sky020** [comment]
To add to this issue:

- Navigate to the translations: https://contribute.freecodecamp.org/#/_translations
- Choose anything but English: https://contribute.freecodecamp.org/#/i18n/Afrikaans/index
- Click on a nav link such as _Reply Templates_: https://contribute.freecodecamp.org/#/i18n/Afrikaans/flight-manuals/using-reply-templates
- Try to navigate anywhere else: https://contribute.freecodecamp.org/#/i18n/Afrikaans/flight-manuals/how-to-setup-freecodecamp-locally

Malformed URL appears 🎉

**Comment by raisedadead** [comment]
>  I was unsure whether to include the crowdin-sync label in this. Could a description be added to that label?

Thanks. I updated the description. Not required to be used here, we should use tools instead.

**Comment by raisedadead** [comment]
This is likely something to do with the files getting malformed somehow in flight from Crowdin? IDK I will have to investigate.

**Comment by raisedadead** [comment]
Addressed via https://github.com/freeCodeCamp/freeCodeCamp/pull/40059
