### ISSUE TITLE
D3 Visualization: Add Classes 'Content Security Policy' error shows.

### ISSUE THREAD

**Issue by bobbwhy** [freeCodeCamp/freeCodeCamp#39798]
First, thanks for setting up this really great site...

**Describe your problem and how to reproduce it:**
* The task is to use attr to create a class of 'bar' on a set of divs created by d3.
* I did that and confirmed that the dom inspector shows those divs as having a class of 'bar'.
* It keeps saying that the divs do not have the class.

* In the dev tools console, there is this error, which may or may not be the issues
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`
* There is also an UnspecifiedAssertionError in the console coming from frame_runner 84:16

**This error is in FF.  In Chrome, the same exact code passes.**

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-classes-with-d3

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version:  81.0.1
* Operating System: Mac OS 10.15.7

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
First image shows errors in the console.  Second image shows dom inspector validating that the divs have class of bar.

![image](https://user-images.githubusercontent.com/85128/95075978-213c3680-06df-11eb-80a8-13ae0e09cc6c.png)
![image](https://user-images.githubusercontent.com/85128/95076110-59437980-06df-11eb-830f-6aa99cc2b03e.png)

**Comment by ojeytonwilliams** [comment]
Hey @bobbwhy, it looks like you have some Firefox addons running.  Could you try again with them off?  Just opening a private mode window might be enough.

**Comment by bobbwhy** [comment]
Hey @ojeytonwilliams 
Thanks for the quick reply.  I had one addon running and turned it off and the page worked.  Also it worked when I turned the addon back on.

My computer did a spontaneous restart since i posted this, perhaps there was something else going on?
Anyway, it seems not to be a problem now.

thanks again.
Robert

**Comment by ojeytonwilliams** [comment]
Hi Robert, that's a bit strange, but I'm glad it's resolved itself.
