### ISSUE TITLE
Incorrect line number mentioned in the instructions of exercise "React: Render Conditionally from Props" 

### ISSUE THREAD

**Issue by g-rohit** [freeCodeCamp/freeCodeCamp#39795]
Incorrect line number mentioned in the instructions of exercise "React: Render Conditionally from Props" 

It says: `On line 30, replace the comment with this expression to complete the variable declaration.` However, there is a comment on line number 30 and the correct line number where the given hint is applicable is 24.

> I feel to avoid future confusions with line numbers - we could simply put it as 'replace the `null` value of expression variable with this expression to complete the variable declaration', or some more simple verbiage which will be easy to understand.

![image](https://user-images.githubusercontent.com/43009327/95005990-88dd7d80-061c-11eb-8f3b-eb4cb5af54a1.png)

**Comment by nhcarrigan** [comment]
You are correct that the line number mentioned is incorrect. 🙂 

However, I'm not sure if it is best to rewrite that entirely, or change the line number to match the challenge seed code. I would like to hear from a couple other folks as to the best approach here.

**Comment by RandellDawson** [comment]
This issue was recently fixed when PR #https://github.com/freeCodeCamp/freeCodeCamp/pull/39742 was merged.  At this point, we are just waiting for the latest `master` branch to be deployed to production.  I am closing this as resolved.
