### ISSUE TITLE
Issue Tracker project example link does not work!

### ISSUE THREAD

**Issue by ManasMahanand** [freeCodeCamp/freeCodeCamp#39796]
**Describe your problem and how to reproduce it:**
The following page has a link that leads to an example project, that the user has to replicate. That link seems to be broken.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker

Broken link: https://issue-tracker--freecodecamp.repl.co/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Chrome 85
* Operating System: Windows 10 64 bit

**Comment by Sky020** [comment]
Thank you, for taking the time to report this. A fix is on the board.

This should be resolved in this PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/39688

**Comment by RandellDawson** [comment]
I have restarted the demo.  I am closing this issue as the demo is now working again.
