### ISSUE TITLE
Issue submitting a correct answer

### ISSUE THREAD

**Issue by daniel-chung** [FreeCodeCamp/FreeCodeCamp#3979]
Challenge [Waypoint: Iterate with JavaScript For Loops](http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops#?solution=var%20myArray%20%3D%20%5B%5D%3B%0A%2F%2FPush%20the%20numbers%20zero%20through%20four%20to%20myArray%20using%20a%20%22for%20loop%22%20like%20above.%0Afor(var%20i%3D0%3B%20i%3C5%3B%20i%2B%2B)%20%7B%0A%20%20myArray.push(i)%3B%0A%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myArray = [];
//Push the numbers zero through four to myArray using a "for loop" like above.
for(var i=0; i<5; i++) {
  myArray.push(i);
}
```

**Comment by ltegman** [comment]
The seed code looks like this:

```javascript
var ourArray = [];

for(var i = 0; i < 5; i++){
  ourArray.push(i);
}

var myArray = [];

// Only change code below this line.



// Only change code above this line.

if(typeof(myArray) !== "undefined"){(function(){return myArray;})();}
```
Removing the content above and below the lines where comments tell you not to edit will cause the test to fail. Please reset the code and put your answer in the designated area.

Closing as not an issue with the test but feel free to reply if you need further clarification.

Thanks and happy coding!

**Comment by daniel-chung** [comment]
Great! Resetting the code solved the issue. Thanks for your response!
