### ISSUE TITLE
bug: Sign In button in nav shows on .dev even if already signed in

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39801]
While QAing `.dev`, I notice when visiting the main landing page, the `Sign In` button is present on the nav bar even if I am already logged in.  This is quite confusing to me.  If I click on `Sign In` or `Curriculum`, I am taken to the same place (`/lean`).  Why not show the `Profile` and avatar when a user is already logged into the site?

**Comment by RandellDawson** [comment]
No one addressed this issue before the changes on `.dev` were merged to production.  @ahmadabdolsaheb Can you provide some insight here on why we want a Sign In button to appear if a user is already signed in?  It makes it appear that the site has a bug in my opinion, which is why I raised the issue before the changes were deployed to production.

**Comment by ahmadabdolsaheb** [comment]
@RandellDawson this was by design; however, we came to your conclusion later on.  I will make pr to address this issue accodingly.
