### ISSUE TITLE
Issue with http://freecodecamp.com/challenges/waypoint-delete-properties-from-a-javascript-object

### ISSUE THREAD

**Issue by jjmax75** [FreeCodeCamp/FreeCodeCamp#3980]
Challenge [Waypoint: Delete Properties from a JavaScript Object](http://freecodecamp.com/challenges/waypoint-delete-properties-from-a-javascript-object)
Please describe how to reproduce this issue, and include links to screenshots if possible.

Challenge says to 
> Let's delete the "tails" property from myDog.

Deleting tails property doesn't work

Error returns
> Delete the property "bark" from myDog.

Deleting bark property passes

My code:
```javascript
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"],
  "bark": "bow-wow"
};

delete ourDog.bark;

var myDog = {
  "name": "Happy Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"],
  "bark": "woof"
};

// Only change code below this line.

delete myDog.tails;

// Only change code above this line.

(function(z){return z;})(myDog);

```

**Comment by ltegman** [comment]
This issue has been resolved by PR #3967 and is pending deployment to the website.

Closing as resolved.

Thanks and happy coding!
