### ISSUE TITLE
PDF file of coding challenges for future reference

### ISSUE THREAD

**Issue by ashfaq92** [freeCodeCamp/freeCodeCamp#39803]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have already solved a challenge and I need to revise it for further challenges. For example, there was a random number generator formula in javascript course and now I have to scan whole curriculum one-by-one to see where was that formula.

**Describe the solution you'd like**
It would be great if you provide a pdf file of all challenges and codes in a sorted way so that we may take that as a cookbook for future needs. (as given by tutorialspoint )
(Extra): If the pdf book contains our solutions and correct solutions, it would be great. So that we may not repeat same mistakes again.

**Describe alternatives you've considered**
I have tried to download the .md files of curriculum and used some online 'md to pdf' converters to make a pdf handbook. However, the whole code was messed up. (see attached file).
[access-array-data-with-indexes.pdf](https://github.com/freeCodeCamp/freeCodeCamp/files/5331904/access-array-data-with-indexes.pdf)

**Comment by raisedadead** [comment]
Thank you for this feature request. 

IMHO, this is something that we will not be implementing.

While we do understand the need for you to go back and refer challenges, we have no plans of storing user solutions for practice challenges. 

We also do not intend to make the curriculum available in any other format. The markdown files we have is solely intended to be used by our own parser to generate the curriculum on the learn platform. 

We do not intend to change that.

The best way forward (might not be trivial) is to fork the curriculum and format the files as you seem fit for whichever format you would need it.

Thanks for your understanding, happy coding.
