### ISSUE TITLE
My project 

### ISSUE THREAD

**Issue by Amani76828** [freeCodeCamp/freeCodeCamp#39815]
https://code.sololearn.com/Wmm6BZEX2Et1/?ref=app

**Comment by RandellDawson** [comment]
@Amani76828 
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects. GitHub issues are meant for reporting bugs with the freeCodeCamp site and not troubleshooting the code in your projects.

Thank you for understanding.
