### ISSUE TITLE
Has program execution error and logs 'chai is not defined' when there is no variable 'chai' in the code

### ISSUE THREAD

**Issue by dengjonathan** [FreeCodeCamp/FreeCodeCamp#3981]
Challenge [Bonfire: Diff Two Arrays](http://freecodecamp.com/challenges/bonfire-diff-two-arrays#?solution=function%20diff(arr1%2C%20arr2)%20%7B%0A%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20arr1.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(arr2.indexOf(arr1%5Bi%5D)%20%3D%3D%20-1)%7B%0A%20%20%20%20%20%20newArr.push(arr1%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20for(var%20n%20%3D%200%3B%20n%20%3C%20arr2.length%3B%20n%2B%2B)%7B%0A%20%20%20%20if(arr1.indexOf(arr2%5Bn%5D)%20%3D%3D%20-1)%7B%0A%20%20%20%20%20%20newArr.push(arr2%5Bn%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20newArr%3B%0A%7D%0A%0Adiff(%5B1%2C%202%2C%203%2C%205%5D%2C%20%5B1%2C%202%2C%203%2C%204%2C%205%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function diff(arr1, arr2) {
  var newArr = [];
  
  for(var i = 0; i < arr1.length; i++){
    if(arr2.indexOf(arr1[i]) == -1){
      newArr.push(arr1[i]);
    }
  }
  
  for(var n = 0; n < arr2.length; n++){
    if(arr1.indexOf(arr2[n]) == -1){
      newArr.push(arr2[n]);
    }
  }
  return newArr;
}

diff([1, 2, 3, 5], [1, 2, 3, 4, 5]);
```

Log Screen:
![screenshot 2015-10-29 09 47 30](https://cloud.githubusercontent.com/assets/13730320/10811932/285edb3e-7e22-11e5-94f2-25f2ce97f3af.png)

**Comment by bugron** [comment]
@dengjonathan thanks for posting this issue!
Are there any errors in your browsers console?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by dengjonathan** [comment]
Arsen,

I took another look at it today and realized it was happening with all
Bonfires, not just the one I was on.  The issue was apparently  my Privacy
Badger Chrome extension which I use to disable tracking websites.
Apparently that caused an issue with the chai function that FCC uses to the
check the answers. Disabling Privacy Badge solved the issue.

thanks for following up!
jon

On Fri, Oct 30, 2015 at 8:55 PM, Arsen Melikyan <notifications@github.com>
wrote:

> @dengjonathan <https://github.com/dengjonathan> thanks for posting this
> issue!
> Are there any errors in your browsers console?
>
> ------------------------------
>
> Please review the *Guidelines for Contributing*
> <https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md>,
> thank you!.
> ------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3981#issuecomment-152601586>
> .
>



-- 
Jonathan M. Deng

**Comment by bugron** [comment]
@dengjonathan awesome. Closing this issue as resolved. Thanks for posting.
