### ISSUE TITLE
RegEx need to fix in Basic Javascript / Finding a Remainder in Javascript

### ISSUE THREAD

**Issue by Arda13** [freeCodeCamp/freeCodeCamp#39810]
**Under Tests section text and textString do not match properly. If you only forget ' ; ' it still awaits for ' % ' **
**We need a separate test for ' ; ' check or fix the text like ' _Do not forget % or ;_ ' **

[Challenge Code](https://github.com/freeCodeCamp/freeCodeCamp/blob/2b9e38a17bd6039a1291f756157c94b3e57955db/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/finding-a-remainder-in-javascript.md)

`- text: You should use the <code>%</code> operator`
    `testString: assert(/\s+?remainder\s*?=\s*?.*%.*;/.test(code)):`

**Comment by RandellDawson** [comment]
The `;` can be made optional in the regex instead.  Leaving the `;` off the end of the line does not affect the code.  The test is trying to get the user to implement a "best practice", but all we really care about is the code written is valid and accomplishes the task.

@Arda13 Are you interested in creating a PR to make the `;` at he end of the line optional?

**Comment by Sky020** [comment]
While we are at it, can we strip the code of whitespace? I much prefer looking at regex without the `\s*` everywhere.

**Comment by RandellDawson** [comment]
> While we are at it, can we strip the code of whitespace? I much prefer looking at regex without the \s* everywhere.

@Sky020 I think that is fine.

FYI - There are a few helper functions available [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/utils/curriculum-helpers.js) that can be used in the testString by using `__helpers.methodName`.

For example, you could use it in the `testString` referenced in this issue like:

```yml
assert(/remainder=\d+%\d+/.test(__helpers.removeWhiteSpace(code)));
```
