### ISSUE TITLE
Problem on the topic of Applied Accessibility: Give Links Meaning by Using Descriptive Link Text

### ISSUE THREAD

**Issue by Mushfiq-alt** [freeCodeCamp/freeCodeCamp#39811]
**Describe your problem and how to reproduce it:**
Every tag is ok. But it showing error. 
**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/give-links-meaning-by-using-descriptive-link-text

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![freecodecamp](https://user-images.githubusercontent.com/52819923/95319712-1be71380-08ba-11eb-870a-8adb9c9557c7.PNG)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by Mushfiq-alt** [comment]
Everyone said no problem in the code after that I report this issue on
freecodecap github profile.

**Comment by RandellDawson** [comment]
> Everyone said no problem in the code

@Mushfiq-alt Can you please post a link here to the forum discussion topic?

Thank you.

**Comment by Sky020** [comment]
Just to add:

@Mushfiq-alt It appears you have included the _full-stop_ within the `a` tag, which, I believe, should not be included.

A link to the forum post would still be handy.

**Comment by Mushfiq-alt** [comment]
Look, full-stop now outside the a tag. Even though now its not working.

**Comment by RandellDawson** [comment]
@Mushfiq-alt Please create a forum post to work on challenge code issues.  GitHub is only for reporting bugs with the lesson instructions and/or tests.  Thank you.
