### ISSUE TITLE
Backend Projects Pre-Installed Packages

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#39825]
Regarding some of the backend projects:

On a few occasions, campers have had issues implementing their projects, because they use the versions of the pre-installed packages.

Specifically, this has been an issue with the MongoDB/Mongoose packages. Honestly, I realise this more-so falls on the camper, but I would rather have one of two things:
1) Remove all/most of the packages from the boilerplates (everything not used by the fcc-testing api)
2) Introduce a clear instruction for the camper that they will likely need to update the packages used.

I believe this was not as much an apparent issue when we were using Glitch, because it had an excellent UI advising packages to be updated. I realise the projects are already under much TLC, and I dislike adding to the mix, but this is coming up on the forum enough.

**Comment by ojeytonwilliams** [comment]
Is the problem that people use the package in the boilerplate, but try to use the current api?

If so, then why don't we take the packages out of the boilerplates, but put in advice about what packages they're likely to need?  That way the amount of guidance stays about the same, but the confusion should be reduced.

**Comment by Sky020** [comment]
> Is the problem that people use the package in the boilerplate, but try to use the current api?

@ojeytonwilliams The issue arises when campers just fork/clone the boilerplate, and start creating the API without updating the packages already in the boilerplate.  So, MongoDB is already included, as is Mongoose. However, the versions are not up-to-date.

Then, a camper will go to the Mongoose docs, and copy the latest information on how to use the Mongoose API, but some methods could be incompatible.

> ...put in advice about what packages they're likely to need?

This is one option, but I would not expect this to be needed. The user-stories should allude to the camper that some form of database is needed, etc.
It should be up to the camper to decide which packages they use. Majority (just not the ones involving Helmet) of the tests seem lenient for any package to achieve the desired output.

**Comment by ojeytonwilliams** [comment]
> copy the latest information on how to use the Mongoose API, but some methods could be incompatible.

Cool, that's what I assumed.

> It should be up to the camper to decide which packages they use.

Agreed, but the boilerplate was giving guidance by having some pre-installed.  I'm fine with taking that away if you think the user stories give enough of a hint.

**Comment by RandellDawson** [comment]
I am going to offer my two cents worth here.  For the certification projects, I would like to see as few as possible packages preinstalled by us.  These projects are to meant validate users understand how to build an app based on user stories provided.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
