### ISSUE TITLE
Typo - ES6 Const Array Mutatation

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#39820]
**Describe your problem and how to reproduce it:**
In this challenge, there is a minor grammar issue.
> Change the array to [2, 5, 7] using various element assignment.

should say

> Change the array to [2, 5, 7] using various element assignments.

as "various" means the noun is plural.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/mutate-an-array-declared-with-const

**Tell us about your browser and operating system:**
N/A

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
 
![image](https://user-images.githubusercontent.com/25011573/95500077-830cd280-0963-11eb-91f3-f16e228a7e62.png)

**Comment by mwlai288** [comment]
I can take this if you want this done.

**Comment by Sky020** [comment]
@mwlai288 Glad you are interested in this.

Any issue with _help wanted_ or _first-timers only_ labels are open to contribution. If you have not already, please read the [contributors docs](https://contribute.freecodecamp.org/#/index)

We will QA the first comprehensive PR for an issue.

**Comment by baranork** [comment]
Is this already fixed? If not, I could do it

**Comment by mwlai288** [comment]
I haven't done it yet. You can do it.

**Comment by dipayanDebTheCoder** [comment]
Hello,

This is my first time participating in any open source project. I see that the issue is open. So if no one is working on this, then should I start working on it. I would be happy to give it a try .

Thanks in advance

**Comment by Sky020** [comment]
@dipayanDebTheCoder This issue is now closed, as there was a linked PR which has now been merged. However, we welcome you to work on other issues.

Any issue with help wanted or first-timers only labels are open to contribution. If you have not already, please read the [contributors docs](https://contribute.freecodecamp.org/#/index)

We will QA the first comprehensive PR for an issue.
