### ISSUE TITLE
Chrome darkmode extensions incompatability

### ISSUE THREAD

**Issue by TheDesertKing** [freeCodeCamp/freeCodeCamp#39826]
CSS code not Checking Correclty if using DarkScreen Extension on Chrome.

https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: newest
* Operating System: windows 10

![Screenshot 2020-10-09 044328](https://user-images.githubusercontent.com/57393961/95532804-230d3f00-09ea-11eb-8d2e-dc476caab9eb.png)
Screenshot taken while in incognito mode, as in incognito mode the extension isn't activated.
This results in a success message.

![Screenshot 2020-10-09 044426](https://user-images.githubusercontent.com/57393961/95532900-6ebfe880-09ea-11eb-833e-02c0141b419b.png)
Screenshot taken while using the extension, having the same exact code.

**Comment by Sky020** [comment]
Hello there,

Thank you, for taking the time to open this issue.

Unfortunately, we cannot do much about external resources/tools affecting the experience. We have been aware of this, for quite some time, and there is a warning to campers here:
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/

As such, I am closing this issue.

Thank you.

**Comment by TheDesertKing** [comment]
Ah, my bad for not reading the note.
Thank you though, I really appreciate your site!


‫בתאריך יום ו׳, 9 באוק׳ 2020 ב-12:45 מאת ‪Shaun Hamilton‬‏ <‪
notifications@github.com‬‏>:‬
