### ISSUE TITLE
Applied Visual Design: Adjust the background-color Property of Text CSS test too strict

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39823]
This lesson: https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/adjust-the-background-color-property-of-text

Requires the semi-colon at the end of a last declaration in the block.
Passes
```
h4 {
  text-align: center;
  padding: 10px;
  background-color: rgba(45, 45, 45, 0.1);
}
```
Fails:
```
h4 {
  text-align: center;
  padding: 10px;
  background-color: rgba(45, 45, 45, 0.1)
}
```

---

The test should be changed to allow the missing semi-colon, provided the `background-color` declaration is last in the scope.

Similar implementation to this should be followed: https://github.com/freeCodeCamp/freeCodeCamp/pull/39570/files

**Comment by baranork** [comment]
I can do this! Do I need to be asigned?

**Comment by Sky020** [comment]
@baranork We typically do not assign issues to anyone other than long-time contributors to avoid ambiguous no-shows.

If you are wanting to contribute, I recommend you take a look at the [Contributors Docs](https://contribute.freecodecamp.org/#/index)
