### ISSUE TITLE
Scrimba's watch a video embed isn't working

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#39914]
**Describe the bug**
Clicking on watch a video under help brings up scrimba video embed which doesn't play the video. This issue applies to all challenges where `watch a video` option is available. 

![fcc-issue](https://user-images.githubusercontent.com/26724128/95639052-92e7fc00-0ab4-11eb-8719-7c0301d574e9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (64 bit)
 - Browser: Chrome
 - Version: 86.0.4240.75 (Official Build)

**Comment by bitsandbytes1708** [comment]
I'm also using the latest version of chrome and I'm not having any issues, however, the video does look like that before it loads. Have you waited more than 10 seconds for it to load, and if so, have you tried reloading your page?

**Comment by vkWeb** [comment]
@bitsandbytes1708 Yes - I waited for around a minute. I have tried hard reloading the page too. 

Update:
The issue was due to third party cookies being disabled by default by my browser.
