### ISSUE TITLE
Roman Numeral Converter Bonfire page crashes

### ISSUE THREAD

**Issue by juliageek** [FreeCodeCamp/FreeCodeCamp#3991]
When I attempt to Run the tests for the code I submitted for Roman Numerals Converter, the page freezes and I cannot solve the issue until I clear the cashe of my browser. Help!

**Comment by ChewieDonenea** [comment]
I have the same issue. 
My browser complains about a long running script and then bails out.

**Comment by juliageek** [comment]
Ok, I figured this one out... if you use the solution in the Gritter chat, that solution will cause a never ending loop, because of the while expression (while numCopy > 0 - which is always true btw). This never ending loop will freeze your browser. Moreover, as I lately discovered, the solution there only covers very few of the cases that we need to test to pass the Bonfire. So back to the drawing board, people!

**Comment by ltegman** [comment]
Leaving this open as a bug for someone to fix the solution in the wiki to one that works with the new test cases.
