### ISSUE TITLE
Description's text doesn't mach with test.

### ISSUE THREAD

**Issue by Megabyteceer** [FreeCodeCamp/FreeCodeCamp#3992]
Challenge [Waypoint: Use Bracket Notation to Find the Last Character in a String](http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-last-character-in-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.

in challenge's description the task is about lastLetterOfFirstName 
but in tests asked about lastLetterOfLastName

**Comment by ltegman** [comment]
The challenge description uses `lastLetterOfFirstName` as an example to show the user what to do and then asks them to do the same using the `lastName`. I'm not sure I see the issue.
