### ISSUE TITLE
Issue Tracker Project accepts incomplete solutions

### ISSUE THREAD

**Issue by Eyob-T** [freeCodeCamp/freeCodeCamp#39952]
**Describe your problem and how to reproduce it:**
Go to https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker
Click the Repl.it link and run the project. Then copy the URL and paste it in the solution text box on the above link
Without writing any solutions, all the tests pass

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Chrome 85.0.4183.121
* Operating System: Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Ieahleen** [comment]
Yes, it is still a work in progress, see https://github.com/freeCodeCamp/freeCodeCamp/issues/37185
