### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by TheEvilSkeleton** [freeCodeCamp/freeCodeCamp#39966]
**Is your feature request related to a problem? Please describe.**

Hi!

I'd like to ask if Google Analytics can be removed. Google has been heavily criticized[1][2] for abusing user's data, and there are posts about Google Analytics' problems[3][4]. I would love to see Google Analytics removed from freeCodeCamp!

**Describe the solution you'd like**

To switch to a more ethical alternative to Google Analytics.

**Describe alternatives you've considered**

Switch to one of the following ethical alternatives listed in the website: https://developers.reverseeagle.org/replace/google-analytics/

**Additional context**

[1] https://en.wikipedia.org/wiki/Criticism_of_Google#Privacy
[2] https://en.wikipedia.org/wiki/Privacy_concerns_regarding_Google
[3] https://plausible.io/blog/google-analytics-and-privacy
[4] https://plausible.io/blog/remove-google-analytics

ElementaryOS also has switched to Plausible: https://blog.elementary.io/leaving-google-analytics-is-finally-plausible/

**Comment by raisedadead** [comment]
Hi @TheEvilSkeleton 

Thanks a lot for this feedback and recommendation. 

While we will be discussing this with the team, the current work around that we recommend is to use an ad-blocker (although please be warned some of them might break freeCodeCamp's features like falsely flagging scripts on the learn platform).

We are investigating using server-side analytics more in favor of any of these client-side offerings. Doing that should help us better understand our audience and still be non-intrusive. 

It's obviously going to be a bit of work before we reach there and we will not be able to give an update on when we end up adopting this of course, that said we understand the sentiment and are in agreement with not using GA or any client-side analytics for that matter.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
