### ISSUE TITLE
Basic Algorithm Scripting: Find the Longest Word in a String (another easy way to solve this problem)

### ISSUE THREAD

**Issue by geeknabil** [freeCodeCamp/freeCodeCamp#39971]
Here is another easy way to solve this problem:

```javascript
function findLongestWordLength(str) {
  // split the whole string into an array and get each array element length 
   let arrLength = str.split(" ").map(item => item.length);
  // get the greatest length number
   return Math.max(...arrLength);
}

findLongestWordLength("The quick brown fox jumped over the lazy dog");
```

**Comment by geeknabil** [comment]
I am requesting a pull request for this solution!

**Comment by nhcarrigan** [comment]
Hello~!

Where are you wanting this solution to go? If you are looking at the markdown file for the challenge, the solution there is only used for testing changes to the challenge test or seed, and is not displayed to the end user. 

If you are talking about the guide post on the forum for a challenge, then that change is proposed through our forum, not through GitHub. 🙂

**Comment by Ieahleen** [comment]
if you want to contribute to the guide please open a topic in the [#contributors](https://forum.freecodecamp.org/c/contributors/3) subforum in the forum
