### ISSUE TITLE
Provided formula is for an inclusive range, but the instructions say the upper bound should be exclusive

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#3997]
Challenge [Waypoint: Generate Random Whole Numbers within a Range](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range#?solution=var%20ourMin%20%3D%201%3B%0A%0Avar%20ourMax%20%3D%209%3B%0A%0Afunction%20ourFunction()%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myMin%20%3D%205%3B%0A%0Avar%20myMax%20%3D%209%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(myMax%20-%20myMin))%20%2B%20myMin%3B%0A%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%0A(function()%7Breturn%20myFunction()%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourMin = 1;

var ourMax = 9;

function ourFunction() {

  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;

}

// Only change code below this line.

var myMin = 5;

var myMax = 9;

function myFunction() {

  return Math.floor(Math.random() * (myMax - myMin)) + myMin;

}

// Only change code above this line.


(function(){return myFunction();})();

```

The instructions for this way point say:
>create a function called myFunction that returns a random number that's **greater than or equal to** myMin, and is **less than** myMax.

(emphasis added)
However, the formula provided (`Math.floor(Math.random() * (max - min + 1)) + min`) is inclusive of the upper bound.  The correct formula for an exclusive max is `return Math.random() * (max - min) + min;`

It may be intended that campers should catch this and change the formula, but using the inclusive formula will still pass the tests.

I believe that either the description of the task should be changed, or the tests should be more stringent and there should be an indication that the formula needs to be modified.

**Comment by mohamed-avatarinweb** [comment]
![i did it](https://cloud.githubusercontent.com/assets/15839075/11169382/f2532650-8bc6-11e5-9d43-3fa753c4e5e0.png)

**Comment by SaintPeter** [comment]
@mohamed-avatarinweb Your code does not match the provided sample.  You removed the `+ 1` from after `myMin`.

**Comment by mohamed-avatarinweb** [comment]
Yes  I know that,because the random number by myFunction should be less than or equal to your maximum number
Remember: or equal

**Comment by ArielLeslie** [comment]
@mohamed-avatarinweb The `+1` is what makes it inclusive (less than **or equal too**).  To be strictly less-than, you would omit the `+1`.  Now that the instructions have been fixed, the `+1` is appropriate.   That was the premise of this Issue.

**Comment by sludge256** [comment]
Became aware of this while discussing the `+1` in chat.
It appears that while the wording was changed to be for an inclusive range the tests still pass for an exclusive range.
![image](https://cloud.githubusercontent.com/assets/10524623/11938924/0c59c090-a7d3-11e5-8fbd-814c0ca74042.png)
@mohamed-avatarinweb may have been referencing this but it appears his code was not passing back then but it would now.
![image](https://cloud.githubusercontent.com/assets/10524623/11939421/e5f4d3d2-a7d6-11e5-997f-077f5e1d4399.png)

**Comment by SaintPeter** [comment]
This is very difficult to test.  Previously we had a horrible massive Regex that tried to look for the explicit code, which caused no end of trouble.  Here are the current tests:
```
assert(myFunction() >= myMin, 'message: The random number generated by <code>myFunction</code> should be greater than or equal to your minimum number, <code>myMin</code>.');
assert(myFunction() <= myMax, 'message: The random number generated by <code>myFunction</code> should be less than or equal to your maximum number, <code>myMax</code>.');
assert(myFunction() % 1 === 0 , 'message: The random number generated by <code>myFunction</code> should be an integer, not a decimal.');
```

The only way I could see to improve this would be to write a loop in the "tail" section (which executes after the user code) that, for example, did 100 or 1000 calls to the random function and collected min and max values.  Now, there is no gaurentee that we'd always get a min and max . . . But that's pretty much the only way I can think of testing this "for real".

I'd like to hear what the other @FreeCodeCamp/issue-moderators have to say - is it worth the risk to do some sort of looping structure, or do we just want to leave it as is?

**Comment by erictleung** [comment]
As the function is random, it won't necessarily catch the min or max values. One thing you could do is accept this "feature" and just educate the camper as much as possible on what the function is really doing. 

So to do so, I suggest first adding a note as a reminder on the specifics on what the `Math.random()` function does.

> Note
> Remember that the `Math.random()` function generates a random decimal number from 0 (inclusive) up to but not including 1 (exclusive)

Secondly, you can then reference the [MDN documentation on `Math.random()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) if they get stuck, as it gives some really good examples on how it builds up the given equation. The downside to this approach is that you really could just copy-paste the example from MDN and not really learn. However, I believe in the honesty and curiosity of FCC coders trying to learn :)

And if these changes are made, we could change it back to making the upper end exclusive and noting you will have to change the original formula. Given all these additional hints and instructions, it'll hopefully make it more clear on what needs to be changed to the original given formula with the `+1`.

**Comment by SaintPeter** [comment]
http://www.freecodecamp.com/challenges/generate-random-fractions-with-javascript
> JavaScript has a Math.random() function that generates a random decimal number between 0 (inclusive) and not quite up to 1 (exclusive). Thus Math.random() can return a 0 but never quite return a 1

Doesn't that cover it?  

I'm pretty sure we've re-written all 3 random number challenges since this issue was opened.

**Comment by erictleung** [comment]
It does, but it would have been two challenges ago. I think it would just be a friendly reminder of that small detail.

**Comment by SaintPeter** [comment]
I could see a full explanation of this formula:
`Math.floor(Math.random() * (max - min + 1)) + min`

> `(max - min + 1)` is the "Range" of the random numbers.  For example a random number between 6 and 10 would have a range of `10 - 6 = 4`.  We add 1 because we are rounding down.
> `Math.floor(Math.random() * range)` gets us our random number between 0 and 4 (inclusive)
> `random number + min` adds back in the lower bound, so it would be 6 + (Random from 0 to 4), gives us our range of 6 to 10.

Probably needs some wordsmithing and may be too complex.

**Comment by erictleung** [comment]
@SaintPeter, it looks like your suggestion to loop through 100 iterations in the "tail" section [got added in](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4480-L4495).

On side note, it looks like the instructions are a little redundant with the "inclusive" and "or equal to" part:

> ...returns a random number that's greater than or equal to `myMin`, and is less than **or equal to** `myMax`, **inclusive**.

**Comment by SaintPeter** [comment]
I believe the instructions got updated as well.  I'm going to close this as resolved.

**Comment by oilhen** [comment]
just "return Math.random()" is ok!
