### ISSUE TITLE
"Rosetta Code: Date format" sample day is incorrect

### ISSUE THREAD

**Issue by ylevental** [freeCodeCamp/freeCodeCamp#39997]
**Describe your problem and how to reproduce it:**

The sample output in the sidebar has the date `Sunday, November 23, 2007`.  The date should read `Friday, November 23, 2007`.  Source: https://howlongagogo.com/date/2007/november/23 and many other websites.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/date-format

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 82
* Operating System: Linux Mint

**Comment by nhcarrigan** [comment]
```md
Return an array with the current date in the formats:
<ul>
  <li>2007-11-23</li>
  <li>Sunday, November 23, 2007</li>
</ul>
Example output: <code>['2007-11-23', 'Sunday, November 23, 2007']</code>
```

Looks like a fix would entail editing the challenge `description` - the tests themselves appear to be accurate. 

I will open this up to first timers. @ylevental thanks for the catch! 😁
