### ISSUE TITLE
Using a Generic font name gives error when answering

### ISSUE THREAD

**Issue by JohnnyGow** [freeCodeCamp/freeCodeCamp#39991]
**Describe your problem and how to reproduce it:**
This was discussed on the forum and it was suggested I submit it to GitHub. 

The instructions of this challenge introduce the use of a “generic name” (optional) so I used “monospace” in the generic name.

font-family: FAMILY_NAME, GENERIC_NAME; .

I would then get the error:

" You should only use an h2 selector to change your font", which I was doing.

It turns out any use of a generic name won't be accepted.

Please update question to say "don't use generic for now" or update possible answer to allow for a generic insert.

**Add a Link to the page with the problem:**

https://forum.freecodecamp.org/t/generic-name-gives-error/425828

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:.. 
* Operating System: Win 10 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
See link above for insight.

**Comment by nhcarrigan** [comment]
`testString: assert(/\s*[^\.]h2\s*\{\s*font-family\:\s*(['"]?)Lobster\1\s*(;\s*\}|\})/gi.test(code));`

[This is the test in question](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/import-a-google-font.md). I would support modifying the test to allow for a fallback value as shown in the challenge description.

Before opening this up for contribution, though, I'd like some additional feedback to see if there is support for this change.

**Comment by Sky020** [comment]
Thank you, for taking the time to bring this up.

Importantly, the instructions do not mention anything about the generic font. In fact, they are quite clear about what is expected.

In my opinion, there is no issue here. Also, I do not see this confusion popping up on the forum.

Perhaps the point of discussion should be: Is it _best-practice_ to use the generic/fall-back? If so, then we should consider rewriting the instructions, along with the tests.

_Something to keep in mind: The lesson is about importing a font...not setting the font-family (the next lesson covers this)_

**Comment by nhcarrigan** [comment]
I do agree that I haven't seen much confusion for this lesson popping up on the forum. The lesson does ask the camper to set the font-family of the `h2` element to `Lobster` - but the next lesson covers the "font degradation" fall-back value. 

Maybe it would be best to take this note (and the one below it) and move it to the next lesson?
![image](https://user-images.githubusercontent.com/63889819/96370836-15576800-1114-11eb-9b33-52146646d7b2.png)

**Comment by Sky020** [comment]
> Maybe it would be best to take this note (and the one below it) and move it to the next lesson?

@nhcarrigan Yes, I was thinking the same. It is just, this is the type of information I would expect when first encountering a new property.

**Comment by moT01** [comment]
I'm not sure I would move it to the next lesson - there's already an example there. I would be in favor of change the last three paragraphs of the instructions from this:
```
```
