### ISSUE TITLE
Rosetta Code: Day of the week test is worded incorrectly

### ISSUE THREAD

**Issue by ylevental** [freeCodeCamp/freeCodeCamp#39995]
**Describe your problem and how to reproduce it:**

The test statement `findXmasSunday(2008, 2121)` should return `[1977, 1983, 1988, 1994, 2005, 2011, 2016]` doesn’t make sense, since 2008 is after 1977.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/day-of-the-week

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 81.0.2
* Operating System: Linux Mint

**Comment by Ieahleen** [comment]
there seems to be just an issue in the test text:
```
  - text: <code>findXmasSunday(2008, 2121)</code> should return <code>[1977, 1983, 1988, 1994, 2005, 2011, 2016]</code>
    testString: assert.deepEqual(findXmasSunday(1970, 2017), firstSolution);
```

There is just to make so that the two functions, the one executed and the one written match. I will mark for first timers
