### ISSUE TITLE
Can't login with Github

### ISSUE THREAD

**Issue by brndnb** [FreeCodeCamp/freecodecamp#4]
I can't login with Github. When I try, it logs me into someone else's account. I didn't realize it was logging me into someone else's account, so I deleted the account once logged in, and then tried again. I was again logged into someone else's account (a different user this time).

Out of curiosity, I had to try deleting this user account as well (sorry!), and when I logged back in again with Github, I was signed in as a different user again. I assume these were all real accounts because they had different user profile pics and such.

It had been a few weeks since I had logged in. Pre-switching away from hipchat, if that helps.

**Comment by FreeCodeCamp** [comment]
We disabled Github for now and all other 4 authentication methods seem to work now. We will re-implement Github auth in the near future, but we have higher development priorities for now.

**Comment by figitalboy** [comment]
Each time I log in with Twitter, I still have to authorize the app to allow FCC access to my profile.

**Comment by terakilobyte** [comment]
Standard questions. Are you running any browser addons/extensions? What are
your cookie settings?

**Comment by FreeCodeCamp** [comment]
I believe this is just how Twitter auth works.

On Sat, Jan 17, 2015 at 10:04 AM, Nathan <notifications@github.com> wrote:

> Standard questions. Are you running any browser addons/extensions? What
> are
> your cookie settings?
>
> On Sat Jan 17 2015 at 12:24:24 PM Michael Johnson <
> notifications@github.com>
> wrote:
>
> > Each time I log in with Twitter, I still have to authorize the app to
> > allow FCC access to my profile.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/FreeCodeCamp/freecodecamp/issues/4#issuecomment-70375253>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/4#issuecomment-70377131>
> .
>



-- 
*Learn to Code*,
http://freecodecamp.com
Free Code Camp

**Comment by QuincyLarson** [comment]
Our login page has currently has a 91% conversion rate, and I don't think Github auth will significantly increase that, so I'm closing this issue. I'm opening another issue for the twitter auth issue, which @terakilobyte and @figitalboy are tackling today.
