### ISSUE TITLE
Bonfire Descriptions

### ISSUE THREAD

**Issue by Shadaez** [FreeCodeCamp/freecodecamp#400]
Smallest Common Multiple:
"Find the smallest number that evenly divides all numbers in the provided range."

It should read "Find the smallest number that is evenly divided by all numbers in the provided range." I believe. Otherwise, the answer would always be 1.

**Comment by Shadaez** [comment]
Search and Replace:
Should mention that the replacement needs to match the case of the previous word.

**Comment by Shadaez** [comment]
Drop it like it's hot:
The description makes no sense, you have to read the test cases just to understand what it wants you to do.

Current: "Drop the elements of an array (first argument), starting from the front, until the predicate (second argument) returns true."

What it's actually asking:  "Drop the elements of an array (first argument), starting from the front, until the truth test (second argument) passes for all elements."

**Comment by Shadaez** [comment]
Make a Person:
The tests should allow you to add methods via prototypes.

**Comment by Shadaez** [comment]
Inventory Update:

Says to update inventory quantity, not add to it. I assumed that 'updating' meant change to new value, rather than being added to.

Current: "Compare and update inventory stored in a 2d array against a second 2d array of a fresh delivery. Update current inventory item quantity, and if an item cannot be found, add the new item and quantity into the inventory array in alphabetical order."

Proposed: "Compare and update inventory stored in a 2d array against a second 2d array of a fresh delivery. Add to current inventory item quantity, and if an item cannot be found, add the new item and quantity into the inventory array in alphabetical order."

**Comment by terakilobyte** [comment]
Smallest common multiple: This is a standard mathematical term that a google search would return quickly. Bonfires aren't meant to be hand holding, they are meant to stimulate thought and make the programmer exercise tertiary programming skills (read, search, ask, post).

Search and Replace: Agreed

Drop it like it's hot: A predicate is a truth test. Again, these aren't meant to be hand holding.

Make a person: The point of the challenge to work with closure, not prototype functions.  

In the future please submit one issue per challenge.
