### ISSUE TITLE
It is red!

### ISSUE THREAD

**Issue by JonaYona** [FreeCodeCamp/FreeCodeCamp#4000]
here's my code:
```
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text>">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```
But I keep getting this result:

Your h2 element should be red.
Your h2 element should have the class red-text.
 Do not use inline style declarations like style="color: red" in your h2 element.

Edited by @ltegman to use markdown code formatting. Please use markdown formatting in the future.

**Comment by ltegman** [comment]
Could you provide us with a link to or name of the waypoint you are experiencing this problem on?

**Comment by JonaYona** [comment]
thanks for being in touch @ltegman !
http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%3E%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

**Comment by BerkeleyTrue** [comment]
Try changing
```html
<h2 class="red-text>">CatPhotoApp</h2>
```
to 
```html
<h2 class="red-text">CatPhotoApp</h2>
```

**Comment by JonaYona** [comment]
thanks @BerkeleyTrue !  I appreciate your input.
