### ISSUE TITLE
Scalar addition issue on Element-wise operations

### ISSUE THREAD

**Issue by ylevental** [freeCodeCamp/freeCodeCamp#40001]
**Describe your problem and how to reproduce it:**
For the challenge "Rosetta Code: Element-wise operations", it says that operation`("s_add",[[1,2],[3,4]],[[1,2],[3,4]])` should return `[[3,4],[5,6]]`.  However, to find this value, you simply add 2 to each element, which is scalar addition.  The second input should just be the number 2.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/element-wise-operations

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 82
* Operating System: Linux Mint

**Comment by nhcarrigan** [comment]
A quick peek in to the relevant test shows:
```
  - text: <code>operation("s_add",[[1,2],[3,4]],[[1,2],[3,4]])</code> should return <code>[[3,4],[5,6]]</code>.
    testString: assert.deepEqual(operation('s_add', [[1, 2], [3, 4]], 2), [[3, 4], [5, 6]]);
```

The test itself calls the function as you've describe, so the `text` should be updated to match. I think this one could be opened to first timers. 🙂 

Nice catch!

**Comment by ylevental** [comment]
Thank you!  I really like noticing these details

**Comment by msreekm** [comment]
I am a first time contributor, Can I take this issue?

**Comment by nhcarrigan** [comment]
Heya @msreekm~! Thank you for your interest in contributing!

As a heads up, issues labelled `first timers only` or `help wanted` are open for contribution and do not require permission. We typically accept the first comprehensive PR that fixes the issue. 

If you have not done so already, I encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

**Comment by msreekm** [comment]
ok will create a PR soon, thanks

**Comment by frankiefab100** [comment]
Hi, i would like to work on this too

**Comment by msreekm** [comment]
create a PR

**Comment by tanmayj2020** [comment]
I also would like to work
