### ISSUE TITLE
Bonfire: Arguments optional. Fails to validate

### ISSUE THREAD

**Issue by alidaca** [FreeCodeCamp/FreeCodeCamp#4001]
Challenge [Bonfire: Arguments Optional](http://freecodecamp.com/challenges/bonfire-arguments-optional#?solution=var%20vailidArgs%3B%0A%0Afunction%20add(a%2Cb)%20%7B%0A%20%20%0A%20%20var%20argsArray%20%3D%20Array.from(arguments)%3B%0A%20%20%0A%20%20argsArray.forEach(validate%2CargsArray)%3B%0A%20%20%0A%20%20if%20(validArgs)%7B%0A%20%20%0A%20%20%20%20if%20(arguments.length%20%3C%202)%7B%0A%20%20%20%20%20%20return%20function(x)%7B%0A%20%20%20%20%20%20%20%20return%20(a%20%2B%20x)%3B%0A%20%20%20%20%20%20%7D%3B%2F%2Freturne%20function%0A%0A%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20return%20a%2Bb%3B%0A%20%20%20%20%7D%20%2F%2F%20if-else%0A%20%20%7Delse%7B%0A%20%20%20%20return%20undefined%3B%0A%20%20%7D%2F%2F%20validArgs%0A%7D%2F%2F%20add%0A%0Afunction%20validate(a)%7B%0A%20%20if%20(typeof%20a%20%3D%3D%20'number')%7B%0A%20%20%20%20validArgs%20%3D%20true%3B%0A%20%20%20%20console.log(a%20%2B'is%3A%20'%2B%20validArgs)%3B%0A%20%20%7Delse%7B%0A%20%20%20%20validArgs%20%3D%20false%3B%0A%20%20%20%20console.log(a%20%2B'is%3A%20'%2B%20validArgs)%3B%0A%20%20%7D%0A%7D%0A%0Aadd(2%2C%5B3%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Last validation does not pass even if the console returns "undefined" when add(2,[3]) is tested in the sandbox.

My code:
```javascript
var vailidArgs;

function add(a,b) {
  
  var argsArray = Array.from(arguments);
  
  argsArray.forEach(validate,argsArray);
  
  if (validArgs){
  
    if (arguments.length < 2){
      return function(x){
        return (a + x);
      };//return function

    }else{
      return a+b;
    } // if-else
  }else{
    return undefined;
  }// validArgs
}// add

function validate(a){
  if (typeof a == 'number'){
    validArgs = true;
    console.log(a +'is: '+ validArgs);
  }else{
    validArgs = false;
    console.log(a +'is: '+ validArgs);
  }
}

add(2,[3]);

```

**Comment by ltegman** [comment]
The test case that you are failing is `add(2)([3])`, not `add(2, [3])`. When your function is called with `add(2)([3])` it returns `23`. It looks like your code is only running your argument validation code in the `add` function, but not in the function you're returning when only a single argument is passed. So whatever argument is passed into that function is not checked.

Closing as not an issue with the test but feel free to reply if you need further clarification.

Thanks and happy coding!

**Comment by alidaca** [comment]
Thanks!
