### ISSUE TITLE
There is errors in the Code, it should be changed to: 

### ISSUE THREAD

**Issue by samscripts** [FreeCodeCamp/FreeCodeCamp#4003]
the solution should be:
<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json?callback=", function( json ) {

        var html = "";
        
        json = json.filter(function(val) {

              return(val.id !== 1);

        });

        json.map(function(val) {

          html = html + "<div class = 'cat'>"

          for (var key in val) {

            // Only change code below this line.

            if(key === "imageLink") {

              html = html + '<img class = "' + key + '"src = "' + val[key] + '">';

            } else {

              html = html + '<div class = "' + key + '">' + val[key] + '</div>';

            }

            // Only change code above this line.

          }

          html = html + "</div>"

        });

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
 <div class = "row text-center">
   <h2>Cat Photo Finder</h2>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12 well message">
     The message will go here
   </div>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12">
     <button id = "getMessage" class = "btn btn-primary">
       Get Message
     </button>
   </div>
 </div>
</div>

Challenge [Waypoint: Prefilter JSON](http://www.freecodecamp.com/challenges/waypoint-prefilter-json#?solution=6fccss%0A%20%20%24(document).ready(function()%20%7B%0A%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON(%22%2Fjson%2Fcats.json%3Fcallback%3D%22%2C%20function(%20json%20)%20%7B%0A%0A%20%20%20%20%20%20%20%20var%20html%20%3D%20%22%22%3B%0A%0A%20%20%20%20%20%20%20%20json.map(function(val)%7B%0A%0A%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%20%20%20val%20%3D%20%22%3Cimg%20src%20%3D%20'%22%20%2B%20val.imageLink%20%2B%20%22'%2F%3E%22%E2%80%89%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%3D%20html%20%2B%20%22%3Cdiv%20class%20%3D%20'cat'%3E%22%0A%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20%20%20%20%20%20%20%20%20json%20%3D%20json.filter(function(val)%20%7B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%20%20%20%20%20%20%20%20return(val.id%20!%3D%3D%201)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%20%20%20%20%20%20%20%20%20%20for(var%20key%20in%20val)%7B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20html%20%3D%20html%20%2B%20'%3Cdiv%20class%20%3D%20%22'%20%2B%20key%20%2B%20'%22%3E'%20%2B%20val%5Bkey%5D%20%2B%20'%3C%2Fdiv%3E'%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%3D%20html%20%2B%20%22%3C%2Fdiv%3E%22%0A%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24(%22.message%22).html(html)%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
6<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json?callback=", function( json ) {

        var html = "";

        json.map(function(val){

          val = "<img src = '" + val.imageLink + "'/>" 

          html = html + "<div class = 'cat'>"

          // Only change code below this line.

          json = json.filter(function(val) {

              return(val.id !== 1);

          });

          // Only change code above this line.

          for(var key in val){

            html = html + '<div class = "' + key + '">' + val[key] + '</div>';

          }

          html = html + "</div>"

        });

        $(".message").html(html);

      });
    });
  });
</script>


<div class="container-fluid">
 <div class = "row text-center">
   <h2>Cat Photo Finder</h2>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12 well message">
     The message will go here
   </div>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12">
     <button id = "getMessage" class = "btn btn-primary">
       Get Message
     </button>
   </div>
 </div>
</div>


```

**Comment by ltegman** [comment]
Could you describe what the error you're seeing is?

**Comment by samscripts** [comment]
As it is the result of the code is: 
<
i
m
g
s
r
c
=
'
h
t
t
p
s
:
/
/
s
3
.
a
m
a
z
o
n
a
w
s
.
c
o
m
/
f
r
e
e
c
o
d
e
c
a
m
p
/
f
u
n
n
y
-
c
a
t
.
j
p
g
'
/
>
<
i
m
g
s
r
c
=
'
h
t
t
p
s
:
/
/
s
3
.
a
m
a
z
o
n
a
w
s
.
c
o
m
/
f
r
e
e
c
o
d
e
c
a
m
p
/
g
r
u
m
p
y
-
c
a
t
.
j
p
g
'
/
>
<
i
m
g
s
r
c
=
'
h
t
t
p
s
:
/
/
s
3
.
a
m
a
z
o
n
a
w
s
.
c
o
m
/
f
r
e
e
c
o
d
e
c
a
m
p
/
m
i
s
c
h
i
e
v
o
u
s
-
c
a
t
.
j
p
g
'
/
>

the code should be:

script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json?callback=", function( json ) {

        var html = "";
        
        json = json.filter(function(val) {

              return(val.id !== 1);

        });

        json.map(function(val) {

          html = html + "<div class = 'cat'>"

          for (var key in val) {

            // Only change code below this line.

            if(key === "imageLink") {

              html = html + '<img class = "' + key + '"src = "' + val[key] + '">';

            } else {

              html = html + '<div class = "' + key + '">' + val[key] + '</div>';

            }

            // Only change code above this line.

          }

          html = html + "</div>"

        });

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
 <div class = "row text-center">
   <h2>Cat Photo Finder</h2>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12 well message">
     The message will go here
   </div>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12">
     <button id = "getMessage" class = "btn btn-primary">
       Get Message
     </button>
   </div>
 </div>

so the result will be the 2 pictures after filter applied

**Comment by samscripts** [comment]
![error](https://cloud.githubusercontent.com/assets/13786661/10831381/91097908-7e42-11e5-9cc0-4dc4178cdecb.png)
![solution](https://cloud.githubusercontent.com/assets/13786661/10831382/910ad42e-7e42-11e5-8160-97b057d19350.png)

**Comment by ltegman** [comment]
@SaintPeter bought this up in one of the gitter chat channels. @benmcmahon100 is working on getting this waypoint fixed :smile:

**Comment by BerkeleyTrue** [comment]
Fix should be live now

**Comment by ltegman** [comment]
Tested and confirmed fixed. Closing.

Thanks and happy coding!
