### ISSUE TITLE
Problem with Applied Visual Design: Set the font-size for Multiple Heading Elements challenge

### ISSUE THREAD

**Issue by JustSomeone1223** [freeCodeCamp/freeCodeCamp#40031]
So, I tried submitting the following code:
```
<style>






</style>
<h1 style="font-size: 68px;">This is h1 text</h1>
<h2 style="font-size: 52px;">This is h2 text</h2>
<h3 style="font-size: 40px;">This is h3 text</h3>
<h4 style="font-size: 32px;">This is h4 text</h4>
<h5 style="font-size: 21px;">This is h5 text</h5>
<h6 style="font-size: 14px;">This is h6 text</h6>
```
When I ran it through the tests, all but the last one passed. Then I added in what I was supposed to do without removing the inline styles:
```
<style>
 h1 {
    font-size: 68px;
  }
  h2 {
    font-size: 52px;
  }
  h3 {
    font-size: 40px;
  }
  h4 {
    font-size: 32px;
  }
  h5 {
    font-size: 21px;
  }
  h6 {
    font-size: 14px;
  }
</style>
<h1 style="font-size: 68px;">This is h1 text</h1>
<h2 style="font-size: 52px;">This is h2 text</h2>
<h3 style="font-size: 40px;">This is h3 text</h3>
<h4 style="font-size: 32px;">This is h4 text</h4>
<h5 style="font-size: 21px;">This is h5 text</h5>
<h6 style="font-size: 14px;">This is h6 text</h6>
```
This one passed all the tests! I know we were supposed to put stuff in the style tag, but I discovered this issue because I didn't want to do so much typing. There doesn't seem to be some check in the last test that looks at inline styles, unlike the rest. Can you look into it?

**Comment by Sky020** [comment]
Hello there,
Thank you, for taking the time to open this issue.

This is expected behaviour. Recently, the test for the `h6` element was changed, because the usual method of testing did not work on some browsers (Safari, if I recall).

So, unless we find a better method to test all of the elements, I would not advise any of the tests being changed. However, perhaps we could change the instructions to be explicit about requiring campers to **not** use inline-styles.

I will leave this open for others to weigh in on.

**Comment by RandellDawson** [comment]
> However, perhaps we could change the instructions to be explicit about requiring campers to not use inline-styles.

I think this is about the only thing we can currently do.

**Comment by moT01** [comment]
I am good with adding a note there. Something like this:

```
In the `style` tags:
    Set the font-size of the h1 tag to 68px.
    Set the font-size of the h2 tag to 52px.
    Set the font-size of the h3 tag to 40px.
    Set the font-size of the h4 tag to 32px.
    Set the font-size of the h5 tag to 21px.
    Set the font-size of the h6 tag to 14px.
```

That whole thing could probably be shortened to something like this maybe:

```
In the `style` tags, set the `font-size` of the:
    h1 tag to 68px.
    h2 tag to 52px.
    h3 tag to 40px.
    h4 tag to 32px.
    h5 tag to 21px.
    h6 tag to 14px.
```

I'm fine with it either way.

**Comment by RandellDawson** [comment]
> That whole thing could probably be shortened to something like this maybe:

I like @moT01's second shortened suggestion.

**Comment by woftis** [comment]
> Hello there,
> Thank you, for taking the time to open this issue.
> 
> This is expected behaviour. Recently, the test for the `h6` element was changed, because the usual method of testing did not work on some browsers (Safari, if I recall).
> 
> So, unless we find a better method to test all of the elements, I would not advise any of the tests being changed. However, perhaps we could change the instructions to be explicit about requiring campers to **not** use inline-styles.
> 
> I will leave this open for others to weigh in on.

Any idea why it’s only the h6 that doesn’t work? I’ve made a PR with the above but wonder if removing the h6 altogether from this challenge might be slightly more elegant in lieu of not having a different way to test?
