### ISSUE TITLE
Basic JavaScript: Multiple Identical Options in Switch Statements

### ISSUE THREAD

**Issue by travisboss** [freeCodeCamp/freeCodeCamp#40032]
**Describe your problem and how to reproduce it:**
The example shows

```javascript
switch(val) {
  case 1:
  case 2:
  case 3:
    result = "1, 2, or 3";
    break;
  case 4:
    result = "4 alone";
}
```

Should not have `result` should show `return` with the example this is in basic javascript, this could be confusing for the user new to javascript to think they should use `result` and not `return` for output.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/multiple-identical-options-in-switch-statements

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version:  81.0.2
* Operating System:  OSX Catalina

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="819" alt="Screen Shot 2020-10-19 at 7 45 49 AM" src="https://user-images.githubusercontent.com/16948721/96452758-1e613b80-11df-11eb-9c8c-8627a9160b1b.png">

**Comment by Sky020** [comment]
Thank you, for taking the time to open this issue.

I see no issue with the example. However, perhaps some clarification could be beneficial.

The idea behind the code is a fuller example would be:
```javascript
function myFunc(val) {
  let result = '';
  switch(val) {
    case 1:
    case 2:
    case 3:
      result = "1, 2, or 3";
      break;
    case 4:
      result = "4 alone";
  }
  return result;
}
```

Although, I have not seen this section of this lesson cause confusion on the forums.

**Comment by nhcarrigan** [comment]
```js
function sequentialSizes(val) {
  var answer = "";
  // Only change code below this line



  // Only change code above this line
  return answer;
}
```
The boilerplate for the challenge includes the `return` statement, and the example effectively demonstrates the code campers should base their work on when they solve the challenge - I am not sure this requires additional clarity.

**Comment by RandellDawson** [comment]
I do not believe the suggested change is warranted here.  @moT01 Your thoughts?

**Comment by moT01** [comment]
My initial thought was that it's fine how it is, but a quick forum search shows some people struggling here....
https://forum.freecodecamp.org/t/multiple-identical-options-in-switch-statements-help/219876
https://forum.freecodecamp.org/t/multiple-identical-options-in-switch-statements-need-help/263907
https://forum.freecodecamp.org/t/multiple-identical-option-in-switch-statements/185017
https://forum.freecodecamp.org/t/problem-with-multiple-identical-options-in-switch-statements/363219

You can see variations of people using return and result where they shouldn't be. I wonder if using something along @Sky020's suggestion would help out - or perhaps something like this:

```
let answer = '';
switch(val) {
  case 1:
  case 2:
  case 3:
    answer = "1, 2, or 3";
    break;
  case 4:
    answer = "4 alone";
}
```

**Comment by travisboss** [comment]
What about:

```javascript
let answer = '';
switch(val) {
  case 1:
  case 2:
  case 3:
    // answer = "1, 2, or 3";
    break;
  case 4:
    // answer = "4 alone";
```

Since the importance of proper comments is illustrated right in the beginning of the lessons.

**Comment by nhcarrigan** [comment]
I took a quick peek at those forum posts - the first one seems to come from trying to condense the case statements (which the tests ask specifically for 9 distinct statements). The rest come from following the example too closely and missing the change in variable names. 

I do agree that these suggestions would alleviate that - but at the same time, we have a number of examples that do *not* directly match what the tests look for. And I fully support that, as it discourages blindly following the example and encourages the camper to think about *how the example works*.

**Comment by moT01** [comment]
Good point @nhcarrigan - perhaps the instructions aren't clear enough then. Although it does say what to do fairly clearly I think.

What about just putting a declaration of `result` at the top of the example so it's more clear that it's a variable - it does just set the value out of nowhere. I would be fine if someone wants to improve this lesson, but I don't think there's a real problem with it. There's probably room for improvement on most lessons.

**Comment by ieahleen** [comment]
> What about just putting a declaration of `result` at the top of the example so it's more clear that it's a variable - it does just set the value out of nowhere. I would be fine if someone wants to improve this lesson, but I don't think there's a real problem with it. There's probably room for improvement on most lessons.

this seems a good thing to do, and with that we could probably open this to first timers

**Comment by vrpcse** [comment]
I would like to take up this issue fix.

**Comment by Tracy-em** [comment]
Hiền SôKiu

Vào 15:55, Th 2, ngày 09 tháng 11 năm 2020 rajapandi_vijayakumar <
notifications@github.com> đã viết:
