### ISSUE TITLE
Bonfire: Drop it

### ISSUE THREAD

**Issue by TijmenvanderKemp** [FreeCodeCamp/FreeCodeCamp#4004]
Challenge [Bonfire: Drop it](http://freecodecamp.com/challenges/bonfire-drop-it#?solution=function%20drop(arr%2C%20func)%20%7B%0A%0A%20%20while%20(!func(arr%5B0%5D))%20%7B%0A%20%20%20%20%2F%2F%20console.log(%22%5Cn%22%2C%20arr%5B0%5D%2C%20func(arr%5B0%5D))%3B%0A%20%20%20%20%2F%2F%20console.log(arr)%3B%0A%20%20%20%20arr.shift()%3B%0A%20%20%20%20%2F%2F%20console.log(arr)%3B%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0Adrop(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(n)%20%7Breturn%20n%20%3E%3D%203%3B%20%7D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When I click submit with this specific solution, the tab crashes in Google Chrome. In Firefox, the whole window crashes. (To me it seems like an endless loop or not enough memory, but don't take my word for it.) In the screenshot I pulled up the console; as you can see the code did run correctly but afterwards it just gives up. I verified the correctness of the code in Atom (with nodejs running it). Please share your thoughts. 

http://puu.sh/l2lVJ/b212cb2fc5.png

My code:
```javascript
function drop(arr, func) {

  while (!func(arr[0])) {
    // console.log("\n", arr[0], func(arr[0]));
    // console.log(arr);
    arr.shift();
    // console.log(arr);
  }
  return arr;
}

drop([1, 2, 3, 4], function(n) {return n >= 3; });
```

**Comment by ltegman** [comment]
Your code goes into an infinite loop when the test case `drop([1, 2, 3, 4], function(n) {return n > 5;})` is run because the condition of your while loop will never be false.

Closing as not an issue with the tests, but feel free to reply if you need further clarification.

Thanks and happy coding!

**Comment by TijmenvanderKemp** [comment]
I saw this before, and I modified the condition to 
```javascript
while (arr && !func(arr[0])) {
```
However, the while loop still didn't terminate. It should be empty because of split(), right?

**Comment by TijmenvanderKemp** [comment]
Ok nevermind, I'm being stupid. The value
```javascript
[]
```
is not falsy but truthy. My bad. Sorry everyone.

**Comment by ltegman** [comment]
Don't worry about it -- happy to help! :smile:

**Comment by nugoose** [comment]
Hey folks, i have the exact same code as above however the tests were all run successfully and the bonfire was completed, not sure how that happened... I was expecting an infinite loop for the 4th case
Here's my code, but it's the exact same thing as above


`function drop(arr, func) {
  
  while(!func(arr[0]))
    {
      arr.shift();
    }
  
  return arr;
}

drop([1, 2, 3, 4], function(n) {return n >= 3;});`

**Comment by ltegman** [comment]
@nugoose Great catch! Looks like loopProtect (which we didn't have when this bug was filed) is causing the infinite loop to be broken out of which lets the function return the `arr` (the correct answer). I've filed #7105 to track this bug.
