### ISSUE TITLE
JavaScript Algorithms and Data Structures Projects: Cash Register  super confusing requirement

### ISSUE THREAD

**Issue by vikramvi** [freeCodeCamp/freeCodeCamp#40046]
**Describe your problem and how to reproduce it:**

```
[
  ["PENNY", 1.01],
  ["NICKEL", 2.05],
  ["DIME", 3.1],
  ["QUARTER", 4.25],
  ["ONE", 90],
  ["FIVE", 55],
  ["TEN", 20],
  ["TWENTY", 60],
  ["ONE HUNDRED", 100]
]
```

what does this array means ?

1.01 ?   does this mean 1 dollar and 1 penny ?

  ["NICKEL", 2.05],  does this mean 2 dollar and 5 penny ?

  ["TWENTY", 60], what is 60 here ? 

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register

**Comment by ieahleen** [comment]
when I did this challenge, I thought, or it's the number of pennies, or the value. Considering you can't have one hundreth of a coin, I was pretty sure it was the dollar amount.

Can you think of a way to make this clearer?

**Comment by ojeytonwilliams** [comment]
> cid is a 2D array listing available currency.

could be

> cid is a 2D array containing pairs of currency type (e.g. "PENNY") and the dollar value of that currency.  For example, 101 pennies and 41 nickels would be represented as `[["PENNY", 1.01], ["NICKEL", 2.05]]`

If we want to keep the size of the challenge down, we could replace 

> See below for an example of a cash-in-drawer array:

and the example array with 

> See the tests below for more examples of cash-in-draw arrays.

**Comment by ojeytonwilliams** [comment]
Having said all that, I agree with @ieahleen that it was fairly clear from the context, so I'm not 100% convinced this needs changing.

**Comment by nhcarrigan** [comment]
I also agree that this is fairly clear as is.
