### ISSUE TITLE
Running fcc locally, gets me 404 page couldnot be found error with a blank page

### ISSUE THREAD

**Issue by AliCemilcan** [freeCodeCamp/freeCodeCamp#40042]
**Describe your problem and how to reproduce it:**
I followed the documentation and download all the necessary softwares to run it locally but when "npm run develop"
It shows me a blank page with 404 page couldnot be found with the following errors 

- Note that the development build is not optimized.
1. To create a production build, use gatsby build
2. Success Building development bundle - 164.624s
4. Error loading a result for the page query in "/dev-404-page". Query was not run and no cached result was found.
5. Error loading a result for the page query in "/". Query was not run and no cached result was found.
6. Error loading a result for the page query in "/404.html". Query was not run and no cached result was found.

Am I missing something ? thank for you time..

**Comment by Sky020** [comment]
Hello there,

In general, we recommend you join the Gitter or Discord channel mentioned in the [docs](https://contribute.freecodecamp.org/#/FAQ?id=i-am-stuck-on-something-that-is-not-included-in-this-documentation), to ask for help on the respective _Contributors_ channel. If you are likely going to need to paste a wall of text/errors, it might be beneficial to make use of the [forum's](https://forum.freecodecamp.org) contributor sub-forum, or create a GitHub gist with the text, and share the public link.

I am closing this for now. It can be reopened, if it is determined that this is an issue with the development process (not your setup). Cheers.
