### ISSUE TITLE
Formatting error in Spinal Tap Case

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40044]
**Describe your problem and how to reproduce it:**

There is a formatting error in one of the test text strings for the Spinal Tap Case challenge. Because the sentence uses underscores, the parser is reading it as _italic_ syntax.

I believe this is a matter of escaping the `_` characters in the string - it might require a double-escape.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/spinal-tap-case

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 86.0.4240.75 (Official Build) (64-bit)
* Operating System: Windows 10 v1909

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/63889819/96635577-e1757180-12d0-11eb-81ed-d938c4dbcfaa.png)

**Comment by RandellDawson** [comment]
@ojeytonwilliams Is one of the edge cases you were thinking about in issue https://github.com/freeCodeCamp/freeCodeCamp/issues/39177

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams Is one of the edge cases you were thinking about in issue #39177

Yes.  There are a few things like this and I'm the process of dealing with them.

**Comment by nhcarrigan** [comment]
This one, too, can be closed I believe.
