### ISSUE TITLE
"Happy numbers" and "Iterated digits squaring" challenges are way too similar to each other

### ISSUE THREAD

**Issue by ylevental** [freeCodeCamp/freeCodeCamp#40051]
**Describe your problem and how to reproduce it:**
The only real difference between the two is that for happy numbers, one returns "true" when the sums reach 1 and "false" when the sums reach 89, and for iterated digits, either 1 or 89 is returned.

On the official Rosetta Code website, the challenges require different results: https://rosettacode.org/wiki/Iterated_digits_squaring and https://rosettacode.org/wiki/Happy_numbers

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/happy-numbers
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/iterated-digits-squaring

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 82
* Operating System: Linux

**Comment by afilipa** [comment]
Hey!

I was looking at this question and in fact your point @ylevental seems to be valid. The only difference I can see is that in **Rosetta Code: Happy numbers** there is nothing mentioning that the way to know that the number is not a happy number is to have a sum of 89.. If we use the link at the exercise, the info is:

> On the other hand, 4 is not a happy number because the sequence starting with 4^2=16 and 1^2+6^2=37 eventually reaches  2^2+0^2=4, the number that started the sequence, and so the process continues in an infinite cycle without ever reaching 1.

So following this information the way we have to return false in the exercise would be to do the function until we find 1 or the same number we started (instead 89)

But following the info on exercise **Rosetta Code: Iterated digits squaringPassed** we already know that the number will always be 1 OR 89 at the end, seems to be a help to **Rosetta Code: Happy numbers**

Hope it helps ;)

**Comment by gikf** [comment]
`Iterated digits squaring` challenge could be changed to reflect original challenge from Rosetta Code page - counting how many numbers below certain `n` end up with `89`. That however will make it more similar to [Project Euler Problem 92](https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-92-square-digit-chains). But maybe since those are in different sub-sections and Euler's version requires `n` to go higher, that could be okay?

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
