### ISSUE TITLE
English forum loading slowly in China

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#40058]
**Describe the bug**
https://forum.freecodecamp.org/ is loading very slowly (new incognito window, VPN off, failed after 3min today, succeed after 2min yesterday). But once it's open (VPN on, in 3s), I can fast visit the posts (VPN off).

**Expected behavior**
loading faster in China

**Screenshots**
![image](https://user-images.githubusercontent.com/19358186/96832809-ee7d9680-1471-11eb-924c-ac931adfac95.png)
![image](https://user-images.githubusercontent.com/19358186/96834409-8e3c2400-1474-11eb-936b-cda562ab04af.png)

Lots of URLs here are pending (or failed sometimes). They're aws1.discourse-cdn.com or sjc1.discourse-cdn.com. When I ping them, it shows timeout in different cities.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 86.0.4240.111

**Comment by raisedadead** [comment]
Can we get users from other regions / provinces / cities, etc. to confirm and add their reports as well? I would be able to forward this to discourse team.

**Comment by GarfieldLucy** [comment]
![image](https://user-images.githubusercontent.com/10388720/97246316-066d6580-1838-11eb-8dac-44a179c30892.png)

![image](https://user-images.githubusercontent.com/10388720/97246318-08cfbf80-1838-11eb-99ec-6ab8668d5469.png)

OS：Mac OS
Browser： Chrome
Browser Version：86.0.4240.80

**Comment by tEgRaT** [comment]
3s with vpn on
15s with vpn off
iPhone, 4G, China UniComm, Shandong Prov.

**Comment by MMMAY521** [comment]
10s No VPN
Android 4G

**Comment by raisedadead** [comment]
Related topic on Discourse meta: https://meta.discourse.org/t/its-slow-to-visit-hosted-discourse-in-china/109445

**Comment by raisedadead** [comment]
Hi everyone,

Thanks a lot for taking the time to share your reports here. Discourse has confirmed that they do not have a solution for avoiding the GFW issues.

We will continue to host the Chinese forum ourselves to provide a better experience.
