### ISSUE TITLE
Not able to skip Email Sign up.

### ISSUE THREAD

**Issue by schinj** [freeCodeCamp/freeCodeCamp#40053]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
Not able to skip Email Sign up.

**To Reproduce**
1. Login
2. Email Sign up page is shown
3. Scroll down to bottom
4. Click on `No thanks`

**Expected behavior**
Should be able to go back to the flow in which login was initiated.

**Screenshots**
Something is not quite right. A report has been generated and the freeCodeCamp.org team have been notified.
<img width="1270" alt="Screen Shot 2020-10-21 at 10 12 56 PM" src="https://user-images.githubusercontent.com/7895596/96777406-964f8180-13ea-11eb-83e6-219d64d11778.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari
 - Version: 13.1.2 (15609.3.5.1.3)

**Additional context**

**Comment by raisedadead** [comment]
Hi @schinj thanks for reporting. 

This looks like an issue with your freeCodeCamp account. Can you please check https://freecodecamp.org/support and follow the directions to resolve this?

Thanks.
