### ISSUE TITLE
Incorrect description of test suites that break the logic of the task

### ISSUE THREAD

**Issue by 5Mountains** [freeCodeCamp/freeCodeCamp#40067]
**Describe your problem and how to reproduce it:**
In order to find a bug, you should open the **[link](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/repeat-a-string-repeat-a-string)** and check the description of the test suites, namely multiplication by 8: `repeatStringNumTimes("*", 8) should return "****".`

The task "Repeat a String Repeat a String" in the "Basic Algorithm Scripting" Challenge has a bug in indicating the number of asterisks (I believe that expected to be 8) because the test does not pass when outputting 4 asterisks if multiplied by 8.

The test is passed when the number of asterisks equals multiplier.

I checked it several times on different browsers and devices. 
Browsers:
- Google Chrome - 86.0.4240.111 (64bit)
- Mozila FireFox - 82.0 (64bit)

Operating System:
- Windows 10 Pro (64bit), version - 2004, build - 19041.572

Mobile Browser:
- Safari v. 14.1 (iPhone 7 Plus)

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/repeat-a-string-repeat-a-string

**Recommended fix, suggestions (how would you update it?):**
Changed the task description to the correct one:  `repeatStringNumTimes("*", 8) should return "********".`

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<details>
<summary>Click to see a screenshot of the bug</summary>

![test](https://user-images.githubusercontent.com/29441499/96900881-4250a580-149b-11eb-8be2-daddaa4787eb.gif)

<details>

**Comment by nhcarrigan** [comment]
Nice catch! 

@ojeytonwilliams - is this one also a markdown parsing issue? I see the string in the file contains `********` but renders on the page as `****`.

**Comment by ojeytonwilliams** [comment]
Yes, that's right. If you look closely, you can see they're italicized.

This, and a bunch of related issues, will be fixed as part of moving to MDX.

**Comment by 5Mountains** [comment]
Great! Many thanks for your enthusiastic work!) 👍

**Comment by nhcarrigan** [comment]
I'll go ahead and close this as related to #36879. Thanks again @5Mountains for the catch~!
