### ISSUE TITLE
docs: Multiple H1 elements on a page show children from each other

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40063]
![image](https://user-images.githubusercontent.com/51722130/96883266-212a8d80-1478-11eb-9c17-e00720260236.png)

⬆️ _Moderator Handbook_ children end up as _Reply Template_ children. Not a big deal; nothing breaks.

_Originally posted by @Sky020 in https://github.com/freeCodeCamp/freeCodeCamp/issues/39785#issuecomment-714520138_

**Comment by ealvarez968** [comment]
Hello, this looks interesting, can I help?
