### ISSUE TITLE
docs: slow loading of assets

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40065]
Some of the assets (docsify code on unpkg and google fonts, at least) occasionally load painfully slowly (5 - 10 second waits).  Assuming the problem isn't anything at my end, it could be worth pulling those into our CDN.

**Comment by raisedadead** [comment]
> Assuming the problem isn't anything at my end, it could be worth pulling those into our CDN.

Can you confirm if these assets are being throttled by anything on your system/network? Testing this with VPN (On/Off) and extensions disabled etc.

**Comment by ojeytonwilliams** [comment]
It's intermittent.  Right now everything is fine, but I'll test it properly if it's slow in the future.

**Comment by raisedadead** [comment]
Thanks closing this for now.
