### ISSUE TITLE
Quote Machine Tweet button doesn't work on CodePen due to Twitter's API

### ISSUE THREAD

**Issue by IamSurrett** [freeCodeCamp/freeCodeCamp#40089]
**Describe your problem and how to reproduce it:**
The Tweet button on the Quote Machine project isn't working due to twitter.com refusing to connect and a ERR_BLOCKED_BY_RESPONSE error.
User story 10 in the instructions for this project states

> I can tweet the current quote by clicking on the `#tweet-quote` `a` element. This `a` element should include the `"twitter.com/intent/tweet"` path in its `href` attribute to tweet the current quote.

So I did some digging in Twitter’s web intents documentation and found that **web intents cannot be loaded inside an iframe** (about halfway through Working with Web Intents section).

I looked into how CodePen renders its projects, and in both the editor and full views, it renders as an iframe. Since the user has no control over Twitter’s rules, or how CodePen renders the project, I don’t know how a tweet button could be successfully implemented in this project. Maybe posting to another social media site could be implemented instead?

**Add a Link to the page with the problem:**
- [FreeCodeCamp quote machine instructions](https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-random-quote-machine)
- [FreeCodeCamp official example](https://codepen.io/freeCodeCamp/full/qRZeGZ)
- [Twitter documentation for web intents](https://developer.twitter.com/en/docs/twitter-for-websites/web-intents/overview)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 86.0.4240.111
* Operating System: MacOS Catalina (10.15.6)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

<img width="286" alt="Screen Shot 2020-10-25 at 4 24 41 PM" src="https://user-images.githubusercontent.com/16234670/97118108-98615b00-16de-11eb-87f1-07bd041a8f6e.png">

**Comment by RandellDawson** [comment]
@IamSurrett Did you open a topic on [our forum](https://forum.freecodecamp.org) concerning this yet?

**Comment by Sky020** [comment]
@RandellDawson Hey Randell, I directed _IamSurrett_ here: https://forum.freecodecamp.org/t/quote-machine-tweet-button-error-on-codepen-due-to-twitter-api/427126

**Comment by moT01** [comment]
Thanks for digging into this @IamSurrett.

I am not seeing a problem with the example project - I suppose since it's loading in a new tab. Can anyone confirm that? I assume that the test checks the `href` value and not that the twitter page will actually load so I'm not sure how much of a problem this is. We could possibly add a hint to tell users to use `target="_blank"` so that their tweet will load - or change the test and text to describe that they have to use it. I feel like a small hint here would be the easiest fix.

Do the tests still pass on your personal project @IamSurrett?

**Comment by IamSurrett** [comment]
Yes, all of the tests pass on my project.

The issue I was trying to raise was not that the tests were broken, but the idea that building something that passes a test but fails to work in a real-world scenario seems counter-productive. If the goal of a project is give users real-world experience, their final products should be something that work the way they are intended to work. 

Maybe we could consider changing the curriculum to have the users create a tumblr share button instead of a twitter button? The example project has a tumblr button already and it worked from codepen when I tested it a minute ago.

@moT01, have you been able to tweet a quote from the example project on [codepen](https://codepen.io/freeCodeCamp/full/qRZeGZ)? The issue I found is that the tweet button will not work from inside a codepen project.

**Comment by moT01** [comment]
The problem is, how do you know or test if a button actually opens up twitter with the correct tweet - a person could be looking at a project in an iframe or not. That's why I suggested adding a hint (adding `target="_blank"`) - which looks like it makes the links work. Switching to use tumblr isn't a bad idea - although I'm not sure it's worth the effort. Do they have the same problem? Will they in the future? It will probably break all of the existing projects. I vote not to go that route.

Yes, I can use the tweet button in the example codepen project and it works for me. When I remove the `target="_blank"` on the example project it doesn't work for me - when I add it back, it works. But you're saying it's not working for you, so I'm not sure.

**Comment by IamSurrett** [comment]
That makes sense. I agree that if switching to a Tumblr button would break all the current projects, then it is not a great idea. I hadn't considered that aspect of it.

I tested the example project a few more ways and figured out a few things (both browsers are updated to the latest version and on default settings):

#### What works for me (and passes all the tests):
- Firefox with `target="_blank"` works.
- Firefox without `target="_blank"` shows " "Firefox can't open this page" with a "Open Site in New Window" button that works.
- Chrome with or without `target="_blank"` works if you right click the button and choose "Open Link in New Tab"
- Chrome and Firefox with `target="_top"` (as long as you make sure your work is saved so you don't lose it)

#### What doesn't work for me: 
- Chrome with or without `target="_blank"` and regular button click (_this is what I was using when I found this bug_)

So it seems that this is only a problem for Chrome users, but there is still a workaround (right-click button or use `target="_top"`).  I think adding a hint that the tweet button might not work on Chrome as expected could be helpful, although a good forum post explaining the issue would be another solution.

**Comment by nhcarrigan** [comment]
I think @moT01's suggestion of adding a hint is a good approach here. Something like:

> Note: If you are developing this on CodePen, the restrictions prevent the Twitter link from loading in the window. Add the `target="_blank"` attribute as a workaround.

**Comment by IamSurrett** [comment]
I just created a preliminary PR for this issue. I changed the hint to the following to try to make it as clear as possible and match the wording of the current instructions: 

> **Note:** If you are developing this project on CodePen, restrictions prevent the Twitter link from loading in the same window. Use the `target="_blank"` attribute on the `#tweet-quote` element as a workaround.

If there is a better wording or location for the hint, I can change it.

**Comment by ieahleen** [comment]
> That's why I suggested adding a hint (adding `target="_blank"`) - which looks like it makes the links work

this doesn't seem to work, I have suggested it someone having the issue, and the issue persist

**Comment by IamSurrett** [comment]
I think we should create a hint that solves the problem for all users, instead of just certain users like the `target="_blank"` workaround is currently doing. I know `target="_top"` works for both Firefox and Chrome (and passes all the tests), but because it replaces the current tab, there is a risk of users losing their work if they do not get a "save changes before leaving page?" notification. At this point though, I think it is the best option. 
This is the best I can come up with:

> <strong>Note:</strong> Twitter does not allow links to be loaded in an iframe. Use the `target="_blank"` or `target="_top"` attribute on the `#tweet-quote` element as a workaround. `target="_top"` will replace the current tab so make sure your work is saved.

**Comment by anshullaikar** [comment]
Both of the solutions mentioned are not working. I am still getting the same error.

**Comment by Moustafa-Ahmed-2020** [comment]
Still doesn't work

**Comment by biometricPsychography** [comment]
Still having this issue.

**Comment by lcim** [comment]
When I run my code from visual studio code tweets successfully but not on codepen.

It quite a lot of my time trying to find a way but couldn't.

**Comment by acxdc** [comment]
Even doing what is mentioned in that note at the bottom, I am still having this issue. Twitter is blocked if I just click the button whether target="_blank" or target="_top". If I right click, and then click "Open in new tab", it opens in a new tab without a problem, regardless of the target attribute.

**Comment by eevontually** [comment]
Hi.. I am having the same problem here. The Twitter link will only open when I right click "Open in new tab". But now my problem is after reading this thread, I tried changing the target="_blank" to  target="_top" and now I have the word "_top" stuck on top of my quote. It just won't go away even after I've refreshed the page.
