### ISSUE TITLE
Spaces needed

### ISSUE THREAD

**Issue by MysteriousManfred** [FreeCodeCamp/FreeCodeCamp#4010]
There needs to be a space after Latitude, and one before and after Longitude, and maybe a comma as well - $("#data").html("Latitiude " + position.coords.latitude + ", Longitude " + position.coords.longitude);

Turns
latitude-1.2677468longitude-1.2677568
into
Latitude -1.2677468, Longitude -1.2677568

**Comment by ltegman** [comment]
Thanks for the report! We currently have PR #3986 open to fix this. It just needs a small update and then will be merged into the codebase :smile:

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3986 is merged.
