### ISSUE TITLE
Replace <Fragment> tags to <> around the projects

### ISSUE THREAD

**Issue by evertonrbraga** [freeCodeCamp/freeCodeCamp#40115]
**Describe the bug**
There are many <Fragment></Fragment> tags around the codebase. Please replace it to <></> in order to get a more concise and clear code.

<img width="516" alt="fragment" src="https://user-images.githubusercontent.com/25904662/97572379-e4561d80-19c6-11eb-82a4-b6510db66c97.png">

**Comment by DannyBoris** [comment]
Is this already complete or i can have a go here?

**Comment by evertonrbraga** [comment]
Hey Danny, what's up? It was completed in parts, there are some bugs to solve yet. I'm gonna create another issue explaining better what happens and let you know, okay?

**Comment by DannyBoris** [comment]
sure

**Comment by evertonrbraga** [comment]
Hey Danny, the new issue is here: https://github.com/freeCodeCamp/freeCodeCamp/issues/40143

**Comment by Phakeme** [comment]
Hy Danny and Evertonbraga, is this issue still open for contribution? I would love to contribute to it as well.

**Comment by evertonrbraga** [comment]
Hey Phakeme, I'd like to contribute but I'm so busy at the moment. Please go ahead!

**Comment by shootermv** [comment]
Hi Dear people!
 Im a new guy who want to make his first contribution here -  can somebody please guide me- 
 Is there already PR for this issue?
 Thanks
