### ISSUE TITLE
News tag error

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40111]
This appears intermittently in the news `ghost log`

```
BadRequestError: Error parsing filter

Error: Query Error: unrecognized text "c" in filter at char 7
(tags:c+id:-<somehash>
------^
```

Where `<somehash>` is the id (I assume it's not sensitive, but removed it on the off chance it was)

**Comment by raisedadead** [comment]
We removed this error with this patch: https://github.com/freeCodeCamp/news-theme/pull/18. Not sure what the path forward is with the theme but closing, as this error is no longer in play.
