### ISSUE TITLE
Running Python in the browser for python courses @ FreeCodeCamp

### ISSUE THREAD

**Issue by rahul1990gupta** [freeCodeCamp/freeCodeCamp#40113]
**Is your feature request related to a problem? Please describe.**

I have enjoyed learning front-end development through freecodecamp and it's smooth experience. Everything was in a single browser window: code, exercise instruction, web page and console.

Wouldn't it be nice, if we could have the same for python course as well by running python into the browser ?

**Describe the solution you'd like**
This [webpage](https://anvil.works/blog/python-in-the-browser-talk) talks about multiple solution that facilitates running python in the browser. 

Author makes a case for using skulpt for running  basic python and pyodide for data-science python workload. 

**Describe alternatives you've considered**

Another alternative would be to run python code on server using containers e.g. [mybinder.org](mybinder.org). I believe [datacamp.com](datacamp.com) uses that. but this will increase the server cost. 

**Additional context**

https://skulpt.org/
https://pyodide-cdn2.iodide.io/v0.15.0/full/console.html

**Comment by ojeytonwilliams** [comment]
Hi @rahul1990gupta thanks for taking the time to consider this carefully.  We are definitely interested in running Python in the browser, there's actually an open PR that shows how this could be done https://github.com/freeCodeCamp/freeCodeCamp/pull/39493.

At this stage we need to confirm that these in browser solutions can do everything we want (see https://github.com/freeCodeCamp/freeCodeCamp/pull/39493#issuecomment-696244466 in particular), before we start trying to add new lessons to the curriculum.

**Comment by rahul1990gupta** [comment]
@ojeytonwilliams 
Glad to hear that community and the dev team has been thinking about supporting python in the browser. 

Looking forward to use it in the future.

**Comment by Sembauke** [comment]
Hey @rahul1990gupta,

I am closing this issue/ feature request, there will be certain updates to the python certificates in [version 7 of the curriculum](https://www.freecodecamp.org/news/python-curriculum-is-live/).

Thanks for your interest though!
