### ISSUE TITLE
Front End Libraries Projects - Build a Random Quote Machine how to run in codepen is not at all clear

### ISSUE THREAD

**Issue by vikramvi** [freeCodeCamp/freeCodeCamp#40119]
**Describe your problem and how to reproduce it:**
1.  Challenge says 

`You can build your project by forking this CodePen pen. Or you can use this CDN link to run the tests in any environment you like: https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js
`
2.  But it's not clear how to run real world react app which is created with create-react-app inside codepen
3.  Neither tutorial has got any lesson teaching how to create react app from scratch and run inside codepen

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-random-quote-machine

**Comment by Sky020** [comment]
Hello there,

Could you provide a bit more information as to what you are struggling with?

CodePen has little to nothing to do with _create-react-app_; I doubt CodePen uses _create-react-app_ at all in the background. CodePen is just another online platform to view/host/edit basic pages.

Campers are encouraged to _Read-Search-Ask_:
1) Read given information and instructions
2) Search for what you need to understand/accomplish the problem
3) Ask (I recommend you use the forum for this), if you have any confusion about what you have _Read_ or _Searched_.

**Comment by moT01** [comment]
You can use react on codepen by adding it in the pen settings @vikramvi...
![Screen Shot 2020-11-06 at 11 54 09 AM 1](https://user-images.githubusercontent.com/20648924/98398631-e5bac200-2026-11eb-816f-549aa78057c3.png)

There's also a "projects" area of codepen that I haven't used much, but they have a react template there I believe.

Like @Sky020 mentioned, create-react-app specifically doesn't have anything to do with codepen and I don't think there's any way to use it there.

I suppose we could possibly make a codepen template to fork that has react included - or maybe describe how to add it (and possibly the other libraries as well - sass, bootstrap, jquery, etc). They are all taught on the curriculum - but it's not obvious how to use them on codepen.

**Comment by RandellDawson** [comment]
I do not think we need to start teaching how to set up projects on Codepen for React or jQuery.  Codepen can change things in their UI and/or what libraries they support.  These kinds of discussions are what Read, Search, and Ask is all about.  A user can easily go to the forum and discover many different topics that have already covered how to do this.

**Comment by moT01** [comment]
Sounds good to me @RandellDawson - I think we are probably safe to close this then. 

Thank you for reporting the issue @vikramvi. We don't think we will be making any changes around this for now, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
