### ISSUE TITLE
arrithmetic_arranger coding challenge test cases. assertEqual parameter list order. the "expected" result should be the first parameter so when a user is comparing their results with the expected results there is no confusion. 

### ISSUE THREAD

**Issue by aggreyah** [freeCodeCamp/freeCodeCamp#40112]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ojeytonwilliams** [comment]
Hi @aggreyah, could you add some context to help us understand the problem?  For example, which page has the problem and what should be happening?

**Comment by aggreyah** [comment]
https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter. The test_module.py file. In the test cases, assertEqual parameters are mixed up. Istead of starting with the expected, it starts with the result.  A consequence is if a user writes a failing test, the left column tagged "Expected" is the actual result from the users implementation.
![arrithmetic_arranger_test_cases](https://user-images.githubusercontent.com/10600077/97488775-bdb8c800-196f-11eb-90dc-343661708ed2.jpeg)

**Comment by scissorsneedfoodtoo** [comment]
Hi @aggreyah, thanks for reporting this.

Just to confirm, are you using PyCharm? If so, this seems to be a longstanding issue:

* https://youtrack.jetbrains.com/issue/PY-27267
* https://youtrack.jetbrains.com/issue/PY-26471

Unfortunately, Pycharm assumes that the first parameter is `expected`, and the second is `actual`, and there doesn't seem to be a way to change this behavior in the settings.

The Python docs don't seem to suggest an order for the parameters, just `first` and `second`. And it seems like testing libraries handle this slightly differently, with some assuming `assertEqual(actual, expected)` and others assuming `assertEqual(expected, actual)`.

I think the order works either way, though I slightly prefer the current order.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for confirming that @aggreyah.

No need to close this now. Let's leave it open for now to get some feedback from others in the community. It seems like there are different preferences for the order of the parameters, and some testing libraries even enforce `assertEqual(expected, actual)`.

**Comment by aggreyah** [comment]
Okay cool.

**Comment by moT01** [comment]
I am not too familiar with python. But, if I am understanding this correctly, would fixing the issue for PyCharm users possibly cause the same problem for someone using something else? I am doubting that this is a frequent problem, and I would be fine leaving this as is.

I think it's safe to close this for now. We encourage people to use the replit link in the challenge - which, I assume, doesn't have the issue. If I am mistaken, or anyone wants to weigh in further or has an idea - feel free to leave a comment and we can reopen it. Until then, thanks and happy coding 🎉
