### ISSUE TITLE
Link shows all the code

### ISSUE THREAD

**Issue by MysteriousManfred** [FreeCodeCamp/FreeCodeCamp#4011]
The link at the top needs to be /full/avqvgJ not /pen/avqvgJ or the link displays all the code.

**Comment by BerkeleyTrue** [comment]
Can you be more specific?

**Comment by AkiraLaine** [comment]
@BerkeleyTrue I think he's talking about CodePen. The Weather Zipline has the link: http://codepen.io/FreeCodeCamp/pen/avqvgJ - which goes to "editor" mode. The link should go to: http://codepen.io/FreeCodeCamp/pen/avqvgJ which is the "full page" mode.

**Comment by MysteriousManfred** [comment]
As AkiraLaine said, but it needs to be http://codepen.io/FreeCodeCamp/full/avqvgJ to hit full page mode. The specifications say not to look at the code, however if you click the link it takes you straight to the code, rather than the preview. Codepen keeps track of what format something appears in based on the word before the bunch of letters, so http://codepen.io/FreeCodeCamp/***pen***/avqvgJ takes you to the pen bit (sans ***), while http://codepen.io/FreeCodeCamp/***full***/avqvgJ will take you to an actual preview.

**Comment by BerkeleyTrue** [comment]
Alrighty, it's open for PR for those adventurous souls.

**Comment by pC15** [comment]
Hi, my PR with the fix (#4033) got merged, but because I didn't format it properly, this issue didn't get closed. Sorry for the inconvenience.

**Comment by bugron** [comment]
@pC15 you can close this issue but clicking on the "Close issue" button.
