### ISSUE TITLE
Applied Visual Design: Make Motion More Natural Using a Bezier Curve TYPO

### ISSUE THREAD

**Issue by DrFungi** [freeCodeCamp/freeCodeCamp#40128]
**Describe your problem and how to reproduce it:**
The text reads: "Prior challenges covered the linear and ease-out cubic Bezier curves, however...."
but it should read: Prior challenges covered the linear and ease-out curves, however..."

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/make-motion-more-natural-using-a-bezier-curve

**Recommended fix, suggestions (how would you update it?):**
by deleting cubi
![Error en Applied visual design: make motion more natural](https://user-images.githubusercontent.com/72053117/97767843-3e550100-1af5-11eb-87e3-581e541165a8.png)
c Bezier

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by nhcarrigan** [comment]
It might not seem apparent, but `animation-timing-function` uses a cubic Bezier calculation even for pre-defined values such as `linear` and `ease-out`, according to [MDN]

> The non-step keyword values (ease, linear, ease-in-out, etc.) each represent cubic Bézier curve with fixed four point values, with the cubic-bezier() function value allowing for a non-predefined value.

**Comment by DrFungi** [comment]
So it means that the text is indeed correct and it should not be changed. Thanks very much for your answer :+1:
