### ISSUE TITLE
argument vs parameter unclear usage of words

### ISSUE THREAD

**Issue by haplorhine** [freeCodeCamp/freeCodeCamp#40124]
**Describe your problem and how to reproduce it:**

The usage of the word "argument" ist unclear to me. The title of this challenge uses the word "parameter".

Then the instructions state:
"If an arrow function has a single argument, the parentheses enclosing the argument may be omitted."

But the following snippet cited from the instructions shows the **parameter** "item" without parentheses:
```
// the same function, without the argument [sic] parentheses
const doubler = item => item * 2;
```
The functions are never invoked with an **argument** in the examples.

As I understand it the sentence should say: "If an arrow function has a single **parameter**, the parentheses enclosing the **parameter** may be omitted."

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/write-arrow-functions-with-parameters

or,

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/write-arrow-functions-with-parameters.md

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by nhcarrigan** [comment]
Hello~!

I agree that the verbiage is wrong here. `Argument` should probably be replaced with `parameter` in the examples and text, with the exception of the top line (which, at a quick glance, is the only correct use of `argument`): 
> Just like a regular function, you can pass arguments into an arrow function.

**Comment by ojeytonwilliams** [comment]
> If an arrow function has a single argument, the parentheses enclosing the argument may be omitted.

> // the same function, without the argument parentheses
> const doubler = item => item * 2;

These are the ones that should be changed, I think.  In fact, we could use 

> // the same function, without the parentheses
> const doubler = item => item * 2;

instead.

**Comment by nhcarrigan** [comment]
I like that approach. Think this could be opened up to first timers?

**Comment by ojeytonwilliams** [comment]
Sure, that works.
