### ISSUE TITLE
Local Dev Tool to Change developmentuser's Settings

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#40125]
Spending too much time working on the client side, it is becoming tedious to test features which require the developmentuser to have certain certificates/settings. The main one being time taken to claim the certs.

Is there scope to include a dev tool to complete certain operations with ease? What would this look like?
- A new npm script to `npm run dev:claim-all-certs`
- A simple interface to allow devs to input specific URLs/Solutions

Main time-taking tasks:
- Trying to claim backend certs which have tests (I need to scavenge through my Repl and Glitch account to get a project which still hopefully passes.
- Trying to claim JS cert which requires solutions (I normally copy-pasta the `.md` solution, but still is tedious)

It is not as simple as just changing the devuser to be `isJsCertified`, because then it misses the solutions.

**Comment by ahmadabdolsaheb** [comment]
Seeding different users for cypress tests could work. see here:

https://github.com/freeCodeCamp/freeCodeCamp/pull/38348#discussion_r501767557

**Comment by ojeytonwilliams** [comment]
We'd need to add the ability to switch between the different dev users, but that sounds good.
