### ISSUE TITLE
Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#4013]
Challenge text reads: "For example, your jQuery Playground h3 element has the parent element of `<div class="container-fluid">`, which itself has the parent body."

However, the placeholder code doesn't have the <body> element. It should include this to allow the reader to follow along the chain of parent elements.

**Comment by ltegman** [comment]
Looks like the seed code for that waypoint has the following, which would seem to fit that description, unless I'm misunderstanding.
```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
```

**Comment by CodeNonprofit** [comment]
I'm sorry, doesn't have the <body> element.

**Comment by ltegman** [comment]
Apologies for my confusion. I've put in a PR to fix this.
