### ISSUE TITLE
Eslint breaks path modules when I try to refactor <Fragment> tags

### ISSUE THREAD

**Issue by evertonrbraga** [freeCodeCamp/freeCodeCamp#40143]
I've refactored many Fragment tags to the new pattern <>. But when I tried to refactor Fragment tags of specific files, the pre-commit structure has been blocked it, displaying errors about paths. The picture below illustrates the situation: The same path works in one place (Login.js) and doesn't work in another one (MobileLayout.js). 

* Browser Name: Google Chrome
* Browser Version: 86.0.4240.111 
* Operating System: MacOS

<img width="1440" alt="Screen Shot 2020-10-30 at 20 37 26" src="https://user-images.githubusercontent.com/25904662/97809500-01e7e900-1c4c-11eb-96d6-9c1b68a97e38.png">

**Comment by ojeytonwilliams** [comment]
Hi @evertonrbraga this should be resolved if you run `npm run develop`. That file gets generated as part of that.

**Comment by raisedadead** [comment]
Hi @evertonrbraga. I would recommend following our [contributing guide](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=set-up-freecodecamp-locally) closely. Closing but feel free to reach us in the help channels mentioned in the guide.
