### ISSUE TITLE
Bring @freecodecamp/eslint-config inside the monorepo

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40159]
We currently have some eslint configuration in the published package and some inside freeCodeCamp/freeCodeCamp - this is a bit confusing.  Is there a good reason to maintain the eslint-config repo separately?

If not, I think we should manage it with Lerna instead.

**Comment by raisedadead** [comment]
There is not, previously we had this because we were operating multiple repos. Please feel free to bring it in.

**Comment by ojeytonwilliams** [comment]
Okay, cool, thanks for confirming.  I think this would be a good issue for contributors, if anyone is interested.

**Comment by CipherGirl** [comment]
Hi, I'm new to this repo. I'd like to work on this. What exactly I need to do here?

**Comment by ojeytonwilliams** [comment]
Hey @CipherGirl.  Thanks for the offer of help.

Basically, that eslint config should be brought inside the main freeCodeCamp/freeCodeCamp repository.  We don't need to import that package any more, it should be fine to have a single `eslintrc.json` file in the root of this repository.

**Comment by CipherGirl** [comment]
Seems like @patlehmann1 resolved it.
