### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40158]
We use `gatsby-plugin-postcss`, but I think we could do more with it.  

For example, we already use `import 'style.css';` syntax, but we don't (as far as I can see) use CSS Modules to scope those files.  If we do start using this we will have to validate the style changes, but I think the increased modularity should make it easier to maintain.

cc: @ahmadabdolsaheb

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
