### ISSUE TITLE
Help, it is not rendering the cat pics :)

### ISSUE THREAD

**Issue by deaninous** [FreeCodeCamp/FreeCodeCamp#4016]
Challenge [Waypoint: Convert JSON Data to HTML](http://freecodecamp.com/challenges/waypoint-convert-json-data-to-html#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON(%22%2Fjson%2Fcats.json%3Fcallback%3D%22%2C%20function(%20json%20)%20%7B%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0Ajson.map(function(val)%20%7B%0A%0A%E2%80%89%E2%80%89html%20%3D%20html%20%2B%20%22%3Cdiv%20class%20%3D%20'cat'%3E%22%0A%0A%E2%80%89%E2%80%89html%20%3D%20html%20%2B%20'%3Cdiv%3E'%20%2B%20val%20%2B%20'%3C%2Fdiv%3E'%3B%0A%0A%E2%80%89%E2%80%89html%20%3D%20html%20%2B%20%22%3C%2Fdiv%3E%3Cbr%2F%3E%22%0A%0A%7D)%3B%0A%0A%0A%0A%0A%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24(%22.message%22).html(html)%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json?callback=", function( json ) {

        // Only change code below this line.


json.map(function(val) {

  html = html + "<div class = 'cat'>"

  html = html + '<div>' + val + '</div>';

  html = html + "</div><br/>"

});






        // Only change code above this line.

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
 <div class = "row text-center">
   <h2>Cat Photo Finder</h2>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12 well message">
     The message will go here
   </div>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12">
     <button id = "getMessage" class = "btn btn-primary">
       Get Message
     </button>
   </div>
 </div>
</div>

```

**Comment by deaninous** [comment]
I couldn't wait to get my hands dirty with ajax the moment  I realized that that are waypoints on it.
However, I switched between firefox and chrome and I am not getting any cute cat pics.
The geolocation waypoint didn't work either.
I am wondering if there are some tricks I am supposed to add in order to see the results.

**Comment by ltegman** [comment]
Thanks for the report! This waypoint needs some work. The example code doesn't initialize the `html` variable as an empty string and adding `val` to the html by itself just displays `[object Object]` for each element in the array since that's all the `Object.prototype.toString()` method does.

**Comment by ltegman** [comment]
Taking a whack at this and other cleanup in the JSON waypoints tonight. Expect a PR by tonight or tomorrow. :smile:
