### ISSUE TITLE
modify test parameters into an array

### ISSUE THREAD

**Issue by Karthik-Kashyap** [freeCodeCamp/freeCodeCamp#40166]
Under the coding-interview-prep -> algorithms -> find-the-symmetric-difference.
The test cases should have the parameters in an array when the call is made. Instead it is sent as different objects.For example:
```js
sym([1, 2, 3], [5, 2, 1, 4]);
```
should be replaced with 
```js
sym([[1, 2, 3], [5, 2, 1, 4]]);
```

https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/find-the-symmetric-difference

* Browser Name: Chrome
* Browser Version: 85
* Operating System: Mac OS Mojave

**Comment by ieahleen** [comment]
why do you think this is needed?

**Comment by Sky020** [comment]
Hello there,

The instructions say:
> Create a function that takes **two or more arrays** and returns an array of their symmetric difference. 

This: `sym([[1, 2, 3], [5, 2, 1, 4]]);` is a function taking only **1** array.

**Comment by Karthik-Kashyap** [comment]
@ieahleen okay so when I opened that page it only showed me:

```js
function sym(args) {
  return args;
}

sym([1, 2, 3], [5, 2, 1, 4]);
```
So either all the test calls should be made into an array or the first line should have sym(...args) instead of sym(args).

**Comment by ieahleen** [comment]
@Karthik-Kashyap there are multiple ways to get a variable number of arguments, and in the Interview Prep section, you should know at least one without needing a prompt.

I don't think this change is needed.

**Comment by Karthik-Kashyap** [comment]
@ieahleen Oh okay, if it was delibarate decision to make the user choose the way to get variable number of args, then I have no issues with it being an issue. 

Thank you.

**Comment by RandellDawson** [comment]
@Karthik-Kashyap We can close it for you.
