### ISSUE TITLE
Cypress test development mode

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40165]
By only testing the built site https://github.com/freeCodeCamp/freeCodeCamp/blob/b0e3d7369b669b7c91caf3dfc644fb2da5df0cbe/.github/workflows/cypress.yml#L58-L65

we miss errors, because Gatsby suppresses them in production.  For example bumping react-redux, https://github.com/freeCodeCamp/freeCodeCamp/pull/39941, passed all our tests, but introduced a bug with the hotkeys.

I think we should do at least one of

- Run the Cypress tests on the development site
- Add tests for the hotkeys that broke

**Comment by raisedadead** [comment]
Why not improve the unit test coverage? 

Clearly there was no logic change in the dep bump, we should scope e2e to functional scope of the app and unit tests to the component scope. That should definitively determine broken features.

Now, as for:

> because Gatsby suppresses them in production

If the e2e tests should have failed in the production mode, this clearly indicates the setup is not close to production. We should revisit that instead.

**Comment by ojeytonwilliams** [comment]
> we should scope e2e to functional scope of the app and unit tests to the component scope. 

If you mean behaviour of the app, then they definitely missed a behavioural change.  This broke how the hotkeys behave.  But, yes, we definitely want more of both types of tests.

> If the e2e tests should have failed in the production mode, this clearly indicates the setup is not close to production.

The e2e tests are pretty close to production - they just don't cover this particular behaviour.  If the current set of e2e tests were running against the live site this bug would still have been missed.

I just think it's worth having a fallback to answer the question "are there any unexpected errors being thrown?".

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.
