### ISSUE TITLE
Data Structures: Implement Heap Sort with a Min Heap (Passing)

### ISSUE THREAD

**Issue by farhankk360** [freeCodeCamp/freeCodeCamp#40163]
Hey there,

Here is what the challenge description says regarding the sort method.
"The sort method should return an array of all the elements in the min heap sorted from smallest to largest."

I am literally returning an empty array and the challenge keeps on passing.

[Data Structures: Implement Heap Sort with a Min Heap](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap)

* Browser Name: Chrome
* Browser Version: Version 86.0.4240.111 (Official Build) (64-bit)
* Operating System: Windows 10 Home

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26346408/97917921-0fe65880-1d77-11eb-9286-a9d5b6a91cf7.gif)

**Comment by JoshuaPelealu** [comment]
Has this worked everytime, even after you cleared your browser cache?

**Comment by RandellDawson** [comment]
@farhankk360 Can you please post your full code instead of a screen shot?

Thank you.

**Comment by farhankk360** [comment]
@RandellDawson Sure,
```
function isSorted(a){
  for(let i = 0; i < a.length - 1; i++)
    if(a[i] > a[i + 1])
      return false;
  return true;
}

// Generate a randomly filled array
var array = new Array();
(function createArray(size = 5) {
  array.push(+(Math.random() * 100).toFixed(0));
  return size > 1 ? createArray(size - 1) : undefined;
})(25);

var MinHeap = function() {
  // Only change code below this line
  this.insert = () => {}

  this.remove = () => {}

  this.sort = () => []
  // Only change code above this line
};
```

**Comment by farhankk360** [comment]
@JoshuaPelealu Yes couple of time but still the issues is there. I believe it's the `isSorted` method if you give it an empty array it returns true.
