### ISSUE TITLE
Source code is not visible in tutorial

### ISSUE THREAD

**Issue by anderledani** [freeCodeCamp/freeCodeCamp#40167]
in this tutorial: https://www.freecodecamp.org/news/ios-coreml-vision-image-recognition-3619cf319d0b/
source code is not visible, where it should be.[screenshot](https://i.gyazo.com/6d5fbd78d4ec60d45b948f1fae62d655.png)

**Comment by ojeytonwilliams** [comment]
Thanks for the report @anderledani, this definitely needs looking into.

@scissorsneedfoodtoo the gists are not showing up correctly.  Do you remember if there was a special trick to getting them working on Ghost?  They're visible in the Medium version, but not in the /news one.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @anderledani. I went in and fixed the article. All the code sections should be there now: https://www.freecodecamp.org/news/ios-coreml-vision-image-recognition-3619cf319d0b/

@ojeytonwilliams, unfortunately there's no easy way to move them over. I've just been fixing articles as they get reported.
