### ISSUE TITLE
 broken test 

### ISSUE THREAD

**Issue by shahidnsu** [freeCodeCamp/freeCodeCamp#40170]
**Iterate Odd Numbers With a For Loop
   This challenge test is broken. After writing the right code it doesn't pass the challenges.**

**https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-odd-numbers-with-a-for-loop**

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 86.0.4240.183
* Operating System: macOS Catalina version 10.15.7
![Screenshot 2020-11-04 at 6 45 26 PM](https://user-images.githubusercontent.com/19619396/98113507-f3106900-1ecd-11eb-92c5-e8b02558f702.png)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ieahleen** [comment]
your code doesn't satisfy the tests. Please open a topic on the forum for others to check your code before opening a bug report.
