### ISSUE TITLE
Mention to the user that they have to start a new glitch

### ISSUE THREAD

**Issue by diazabdulm** [freeCodeCamp/freeCodeCamp#40176]
I got stuck because I kept using the HelmetJS glitch and didn't realize I had to create a new glitch (it was not in the instructions). 
Other users seem to have faced this as well: https://forum.freecodecamp.org/t/help-understand-bcrypt-hashes-beta/184412

**Comment by raisedadead** [comment]
Closing after moving outstanding issues from boilerplate repos, please reopen if this persists. 

/cc @moT01
