### ISSUE TITLE
package.json node engine needs updating

### ISSUE THREAD

**Issue by nikrb** [freeCodeCamp/freeCodeCamp#40175]
raised an issue in [curriculum](https://github.com/freeCodeCamp/curriculum/issues/223), though I suspect it belongs here.
With regard to a pr: glitch imports from master I believe, so base pr branch on `gomix` and merge to master? 

#### Describe the bug
Working through the challenge [Information Security with HelmetJS - Hash and Compare Passwords Asynchronously](http://localhost:8000/information-security-and-quality-assurance/information-security-with-helmetjs/hash-and-compare-passwords-asynchronously) I noticed the console complaining about the node version. It is looking for v4 but v8 is currently used.

#### To Reproduce
1. Go to the challenge.
2. In glitch project add `bcrypt` as a dependency and require it in `server.js`
3. follow the instructions in the challenge, using bcrypt hash and compare
4. open the logs window to see `Could not find node 4.4.3, using 8`, just before the console.log outputs.

#### Expected behavior
the message should not appear

#### Screenshots
n/a

#### Desktop (please complete the following information):
 - OS: ubuntu xenial
 - Browser firefox
 - Version 61.0.1 (64-bit)

#### Additional context
Error shows up in learn repo running challenge (specified above) with curriculum import.

**Comment by raisedadead** [comment]
Closing after moving outstanding issues from boilerplate repos, please reopen if this persists. 

/cc @moT01
