### ISSUE TITLE
3 Questions To Watch Out For... article is missing embedded code examples

### ISSUE THREAD

**Issue by pjfoley23** [freeCodeCamp/freeCodeCamp#40178]
**Describe your problem and how to reproduce it:**
Code examples referenced in article do not appear. Tried three different browsers to verify.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/3-questions-to-watch-out-for-in-a-javascript-interview-725012834ccb/

**Recommended fix, suggestions (how would you update it?):**
Contact author and restore content.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="938" alt="3_JavaScript_questions_to_watch_out_for_during_coding_interviews" src="https://user-images.githubusercontent.com/5438191/98382565-38cd4e80-2000-11eb-9ec2-571d9666c31a.png">

**Comment by raisedadead** [comment]
Hi @scissorsneedfoodtoo can you please take a look?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @pjfoley23. Just went in and added the missing code sections: https://www.freecodecamp.org/news/3-questions-to-watch-out-for-in-a-javascript-interview-725012834ccb/

Please let us know if you find issues in any other articles.
