### ISSUE TITLE
Update Boilerplate Code

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40180]
Refer to: https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/15#discussion_r518700511

The following boilerplates use the `assertion-analyser.js` which needs to be updated per the above comment. The code in question should be on lines 66-69:
```javascript
  while(obj = objParser(str)) {
    data[cnt] = obj.obj;
    str = str.substring(0, obj.start) + '__#' + cnt++ + str.substring(obj.end+1)
  }
```

And should be replaced with @ojeytonwilliams' suggestion:
```javascript
let obj = objParser(str);
while(obj) {
  data[cnt] = obj.obj;
  str = str.substring(0, obj.start) + '__#' + cnt++ + str.substring(obj.end+1);
  obj = objParser(str);
}
```

The following boilerplates use this code:
- [ ] [Mocha - Chai](https://github.com/freeCodeCamp/boilerplate-mochachai) - could be fixed in the [current PR](https://github.com/freeCodeCamp/boilerplate-mochachai/pull/27)
- [ ] [Issue Tracker](https://github.com/freeCodeCamp/boilerplate-project-issuetracker) - could be fixed in the [current PR](https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/15)
- [ ] [Metric Converter](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter)
- [ ] [Stock Price Checker](https://github.com/freeCodeCamp/boilerplate-project-stockchecker)
- [ ] [Personal Library](https://github.com/freeCodeCamp/boilerplate-project-library)
- [ ] [Anonymous Message Board](https://github.com/freeCodeCamp/boilerplate-project-messageboard)
- [ ] [Sudoku Solver](https://github.com/freeCodeCamp/boilerplate-project-sudoku-solver)
- [ ] [American-British Translator](https://github.com/freeCodeCamp/boilerplate-project-american-british-english-translator)
- [ ] [Multiplayer Game](https://github.com/freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game)

The corresponding demo-projects will also need the update, it seems.

/cc @RandellDawson @raisedadead

**Comment by RandellDawson** [comment]
Before anyone creates a PR, we should discuss if a package would be better that could be imported to each of the boilerplates instead.

**Comment by nhcarrigan** [comment]
A package would be more maintainable, I think - serving as a single source of truth, and eliminating the need to keep all of the boilerplates in sync. 

That being said, we would then need to ensure the boilerplate `package.json` and `package-lock.json` include that package, and update the `test-runner.js` files to use it. 🙂

**Comment by raisedadead** [comment]
To be clear (excuse my lack of context on this), all of this only applies to all boilerplates in JS - Python ones are handled differently?

**Comment by nhcarrigan** [comment]
Correct - the python boilerplates do not seem to have a comparable file, either.

**Comment by murtaza63** [comment]
I think boilerplate should be update according to package.json if test-runner.js is also  updated with package.json.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
