### ISSUE TITLE
Create package for server-side project courseware

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#40183]
As per the discussion in #40180, and elsewhere, there are some ongoing issues with the server-side course wear used in the QA and some of the InfoSoc projects.

The proposal is to move this common course wear into a single package to reduce the overhead of maintaining it.

Here is a first pass analysis of what needs to be done:
  *  `assertion-analyser.js` 
This code needs a bit of a cleanup to ensure readability.  Otherwise it can be imported without difficulty into all projects.
  * `test-runner.js`
No concerns, can be imported directly as it is currently.
  * `fcctesting.js`
Currently this file is somewhat project specific.  In particular it has project specific routes for each of the user created files.  For example:
    ```js
     app.route('/_api/routes/api.js')
        .get(function(req, res, next) {
          console.log('requested');
          fs.readFile(__dirname + '/routes/api.js', function(err, data) {
            if(err) return next(err);
             res.type('txt').send(data.toString());
          });
        });
    ```
    The signature or each of these routes is almost identical:  It takes the path of the file and serves it up.  I believe we can instead pass in the list of files as a parameter to the module:
    ```js
    module.exports = function (app, filelist) {
       // Add project specific routes
       filelist.forEach(filepath => {
         app.route('/_api' + filepath')
            .get((req, res, next) {
              console.log('requested: ' + filepath);
              fs.readFile(__dirname + filepath, (err, data) => {
                if(err) return next(err);
                res.type('txt').send(data.toString());
          });
        });
    ```
    It would then be called like:
    ```js
    fcctesting(app, [ '/routes/app.js', '/server.js', `/controllers/convertHandler.js' ]); // and so on
    ```
I'm not sure what additional burdens bundling would impose on the files.  I suspect they can otherwise just be used as is.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
