### ISSUE TITLE
Waypoint: Iterate over Arrays with map

### ISSUE THREAD

**Issue by tbraden30** [FreeCodeCamp/FreeCodeCamp#4019]
okay so i added the semi colon and did everything right (my values increased by three) but its still saying that three wasnt added to each value. #frustrated 

![untitled](https://cloud.githubusercontent.com/assets/15311351/10837791/879e706e-7e8b-11e5-9933-d573ea4b4a0d.png)

**Comment by bugron** [comment]
@tbraden30 thanks for posting this issue!
Try changin `plusThree` to `newArray`.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by tbraden30** [comment]
that did it!!!!

**Comment by ltegman** [comment]
Thanks @bugron! Closing as resolved.

Thanks and happy coding!
