### ISSUE TITLE
In challenge : "Sass: Create Reusable CSS with Mixins" doesn't validate with space around ":" character

### ISSUE THREAD

**Issue by Nicolascrd** [freeCodeCamp/freeCodeCamp#40212]
**Describe your problem and how to reproduce it:**

If you write the mixin properly but you include space in your declarations. For example : 
-moz-border-radius : $radius

The validation system doesn't take it into account. Despite the fact that it works on the side where you can see the result.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/sass/create-reusable-css-with-mixins

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 82.0
* Operating System: Ubuntu 20.04.1 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fcc_mixin](https://user-images.githubusercontent.com/72993859/98664843-2e39ee80-234b-11eb-8e9f-e44fed05b7cf.png)

**Comment by ieahleen** [comment]
This is a thing you will notice in most css challenges, it is not an isolated thing.

When the code is validated with regex, it is required you write `rule: value`

**Comment by Nicolascrd** [comment]
@ieahleen Should I close the issue then ? I'm a beginner at contributing

**Comment by ieahleen** [comment]
It was to put context to the report, I don't know if it's a thing to change or not

**Comment by Sky020** [comment]
Thank you, for bringing this up.

As @ieahleen mentioned, common CSS syntax is without the spaces. However, we have, in the past, changed tests to allow for all _interpretable_ CSS to pass.

So, I will open this up for contribution. Specifically, to remove the unnecessary `\s*` declarations in the tests' regex. The tests should either be structured with:
```
assert.match(regex, code.replace('\s', ''));
```
OR
```
assert.match(regex, __removeWhiteSpace(code));
```

**Comment by zootechdrum** [comment]
Can I take this ? Is it up for grabs ? It will be my first time contributing with such a huge codebase.

**Comment by RandellDawson** [comment]
@Sky020 It would actually be `__helpers.removeWhiteSpace(code)`

**Comment by ieahleen** [comment]
@zootechdrum if you haven't done so, read our contributing docs contribute.freecodecamp.org

the first comprehensive PR submitted is the one evaluated, issues are not assigned
