### ISSUE TITLE
Hint 1 is incomplete 

### ISSUE THREAD

**Issue by DhairyaBahl** [freeCodeCamp/freeCodeCamp#40214]
**Describe your problem and how to reproduce it:**

Hint 1 of the formula here is incomplete. Maybe I am wrong and it is done desperately. Or maybe it is not being rendered in my browser . Kindly check it.

**Add a Link to the page with the problem:**
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-map-the-debris/16021

**Recommended fix, suggestions (how would you update it?):**

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![Screenshot](https://user-images.githubusercontent.com/71627983/98810755-ac7abb80-2445-11eb-92e4-5db2c647af78.png)

**Comment by Sky020** [comment]
Hello there,

Thank you for opening this. I have fixed the issue, and it should be visible now.

I am closing this, but feel free to reopen if the issue perists.

**Comment by DhairyaBahl** [comment]
@Sky020 It's visible now :) Thanks
