### ISSUE TITLE
Renaming Primary Branch

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40210]
I've created this issue in relation to the discussion in: https://github.com/freeCodeCamp/chapter/issues/434

GitHub made the decision (which many other tech companies have made) to identify language and terms that is not inclusive and replace those terminologies. As part of this, GitHub changed the default branch for *new* repositories from `master` to `main`. 

For existing repositories, GitHub is not enforcing any changes at this time - however, they are working on some [automation tooling](https://github.com/github/renaming#later-this-year) to facilitate the renaming process. 

With that being said, this does seem to be a change that is in line with our values as a community - I raise the issue here because it is a change that, if implemented, should be rolled out to all of our repositories for the sake of consistency. It would not make sense, in my opinion, to have some repositories with `main` and some with `master`. 

/cc @Ryuno-Ki @ojeytonwilliams

**Comment by Sky020** [comment]
If this goes ahead:
1) Let us remember to update the DOCS!
2) Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/38987

**Comment by Sky020** [comment]
Also, this is likely a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/39098

**Comment by nhcarrigan** [comment]
Oops - I even commented on that issue, and here I completely forgot about it 😅 

I'll go ahead and close this one.
