### ISSUE TITLE
Discussion (donations): give donors an option to voluntarily add the 2% charge that stripe / paypal demands 

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#40216]
**Is your feature request related to a problem? Please describe.**
Every year thounsands of dollars goes to payment gateways (stripe / paypal) as processing fees. Reducing this amount will provide freeCodeCamp with more funds to invest in free education. 

**Describe the solution you'd like**
Wikimedia foundation and Khanacademy allow their donors to add processing charges (usually 2% of donation amount) to their donation amount so that the organization can get 100% of it. 

We should also give our donors an option to add the processing charges. What do you people think on this?

Here's a screenshot of Khanacademty's donate page:

![Khanacademty's donate page](https://i.imgur.com/7ELCPI2.png)

**Comment by ahmadabdolsaheb** [comment]
This feature is on the roadmap :).

Since the development of this feature is a bit more involved, I would rather have a team member work on it in the background.

Let me know if you are interested in donation related issues/features. There are some that we could use your help with. 

I will close this issue for now accordingly.

**Comment by vkWeb** [comment]
@ahmadabdolsaheb Oh nice :) I hope donors will make use of the option & pump more donations to the fCC community.  

I would love to help and contribute. I do whenever it is possible. 

but to be honest, right now I am focusing on algorithms and systems. Also, I don't have the right skillset to contribute anything substantial. So I will return to the development side after getting some experience with the JS ecosystem. Till then I will keep on sharing observations (bugs, feature requests, nits :sweat_smile:).   

Happy coding Ahmad!

**Comment by ahmadabdolsaheb** [comment]
Thanks @vkWeb, best of luck with your algo and sys studies.
