### ISSUE TITLE
Form element instruction typo on Applied Accesibility courses

### ISSUE THREAD

**Issue by syauqy** [freeCodeCamp/freeCodeCamp#40215]
**Describe your problem and how to reproduce it:**
There is a typo on several pages of applied accessibility courses about adding **form** attribute.
Just go to the link that I provide below. I also share the screenshots of the issue.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/improve-form-field-accessibility-with-the-label-element
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/3627108/98814810-cd98d780-2458-11eb-934e-80aaa783e2e8.png)
![image](https://user-images.githubusercontent.com/3627108/98814734-ae9a4580-2458-11eb-9558-8c0a1c59c452.png)

**Comment by Sky020** [comment]
Hello there,

Thank you, for taking the time to report this. However, there is no typo here. There is **no** `form` attribute in `label` elements. but there **is** a `for` attribute.

As such, I am closing this issue. In general, we recommend a topic be opened on the [forum](https://forum.freecodecamp.org), and, if it is determined that there is an issue there, then an issue can be opened here on GitHub.

Cheers
