### ISSUE TITLE
translate the curriculum to Arabic.

### ISSUE THREAD

**Issue by M0hanad0** [freeCodeCamp/freeCodeCamp#40228]
**Is your feature request related to a problem? Please describe.**
I want to translate the curriculum to Arabic so students not fluent in English can get the benefit of this amazing platform.

**Describe the solution you'd like**
translating the curriculum to Arabic.

**Describe alternatives you've considered**
None

**Additional context**
it's a feature I wanted in the beginning of my journey to coding.

**Comment by ieahleen** [comment]
the FAQs in the contributing guideliens say:

> Can I translate freeCodeCamp's curriculum?
> Yes. We will roll out the tools for translating freeCodeCamp's curriculum soon.
> 
> Eventually, we intend to localize freeCodeCamp into several major world languages, starting with: Arabic, Chinese, Hindi, Portuguese, Russian, and Spanish.

([From Here](https://contribute.freecodecamp.org/#/FAQ))

it's in the road map and it will be possible in future.

**Comment by ieahleen** [comment]
You can start translating the contributing guidelines, you can find the link for that here: https://contribute.freecodecamp.org/#/

**Comment by M0hanad0** [comment]
Thanks for the reply.

**Comment by M0hanad0** [comment]
so is there any specific guidelines?

**Comment by ieahleen** [comment]
@M0hanad0 : it's pretty new, so there is not much yet consolidated. If you have issues with the software you can always ask in the contributor channel/subforum in the forum or in one of the chat systems
