### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by Thongsamouth** [freeCodeCamp/freeCodeCamp#40222]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ieahleen** [comment]
this issue seems to be opened accidentally, so I'm closing it

**Comment by Thongsamouth** [comment]
Hi honey I'm just checking on my pictures
