### ISSUE TITLE
news article says to ask any question in this repository

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40229]
> Feel free to ask any questions on FreeCodeCamp’s GitHub page or FreeCodeCamp’s Forum.

Maybe the part about any question in this repository should be removed?

the article is this one: https://www.freecodecamp.org/news/the-c-plus-plus-programming-language/

**Comment by RandellDawson** [comment]
I am not aware of any questions on GitHub coming from news articles.  The article does not link to freeCodeCamp's repo, so I think it is probably fine.  The only link in the sentence goes to the forum.

**Comment by ieahleen** [comment]
Oh, ok, I'm closing this then
