### ISSUE TITLE
Bug(learn) - List item's font size larger than surrounding text

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#40220]
While reviewing some new PRs that used unordered lists, I noticed the font size of the bulleted items was significantly larger than the surround text in a challenge's description or instruction section.  I asked a few other staff if they noticed it, and they agreed something was not right.  Today, I took the time to go back in as far as 12 months in the repo's commits and discovered it has been this way for at least a year (probably much longer).

See screenshot below for the large text for the [Use class Syntax to Define a Constructor FunctionPassed](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function) challenge.

![image](https://user-images.githubusercontent.com/5313213/98885209-7853ca80-2446-11eb-9929-dc15ffdcc84c.png)

**Comment by nhcarrigan** [comment]
Looking at the elements, the fonts are both rendered `18px` in size, but I see the discrepancy in appearance. 

The standard `p` element is set to `1rem`, whereas the `ul` and `li` items are hard-coded at `18px`.

**Comment by prolland006** [comment]
it is not the same font Roboto for the selected text (under <code>selected</code>) and Lato for the normal text. Maybe change the css for "<Code></Code> can have an impact on the others pages !

**Comment by prolland006** [comment]
the fonts are different : Roboto and Lato

**Comment by Sky020** [comment]
I noticed this with the MD/HTML here: https://github.com/freeCodeCamp/freeCodeCamp/issues/39614#issue-704573719

I suspected it had to do with the use of HTML vs MD, but I did  not end up getting conclusive evidence.

**Comment by prolland006** [comment]
i put the good font on <code>ul</code> and it looks better
