### ISSUE TITLE
Request Header Parser Microservice - check for language accepts any string. 

### ISSUE THREAD

**Issue by LazaroFilm** [freeCodeCamp/freeCodeCamp#40239]
**Describe your problem and how to reproduce it:**
In [APIs and Microservices Projects - Request Header Parser Microservice](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/request-header-parser-microservice), the test passes with any string in the language object. 
```
{
ipaddress: "XX.XXX.XXX.XXX", // IP changed to XXX for obvious reasons, not the issue here
language: "fart", // this will clear the test.
software: "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36"
}
```

**Add a Link to the page with the problem:**
[APIs and Microservices Projects - Request Header Parser Microservice](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/request-header-parser-microservice)

**Tell us about your browser and operating system:**
See above hehe. 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2020-11-15 at 4 08 30 PM](https://user-images.githubusercontent.com/18351100/99196861-e78a3100-275c-11eb-899b-b122f80369ad.png)

**Comment by nhcarrigan** [comment]
```
  - text: 'A request to `/api/whoami` should return a JSON object with your preferred language in the <code>language</code> key.'
    testString: 'getUserInput => $.get(getUserInput(''url'') + ''/api/whoami'').then(data => assert(data.language && data.language.length > 0), xhr => { throw new Error(xhr.responseText)})'
```

The issue is that the test only asserts that the property exists and has a length. The same is true for all three of the expected return properties. 

The challenge here would be writing a test that successfully accounts for any valid `language` value.

**Comment by Sky020** [comment]
I do not see a problem here. Unless we change the instructions (user story) to ask for a specific language, all we can/should do is test that it exists.

Am I missing something?

**Comment by nhcarrigan** [comment]
I believe the idea is that the endpoint should return the user's browser language, such as:
![image](https://user-images.githubusercontent.com/63889819/99199273-bb69b280-2752-11eb-8639-c9b8d0faebaa.png)

So it makes sense that allowing *any* value to be returned is a bit strange - though, testing for a valid language value would get overly complex IMO.

I'm fine either way I think - leave it, or determine a viable approach to tighten the test.

**Comment by lasjorg** [comment]
I'm sure there are some well-defined rules for the overall structure and allowed values. But validating for it seems pointless, especially seeing as we don't check the other properties.

You can pass all the tests by just hardcoding any string value for the properties.
