### ISSUE TITLE
I've  seen many tutorials on YouTube. But it seems I still can't  face this.i want the best way to learn coding 

### ISSUE THREAD

**Issue by d3334799** [freeCodeCamp/freeCodeCamp#40235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nhcarrigan** [comment]
Hello~!

For guidance with your development journey, I recommend checking out our [forums](https://forum.freecodecamp.org).

GitHub issues are for bugs or feature requests in the curriculum. As such, we are going to close this issue. 🙂
