### ISSUE TITLE
[SUGGESTION] Make FCC's Map more compact

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#4024]
Since FreeCodeCamp's Map will keep growing with new content, the page will get very long at some point. My suggestion is to keep the "table of contents" and remove everything below. Then when a user clicks on one of the topics, a drop-down shows with the respective challenges.

Just an idea, but could be useful in the future :smile:

**Comment by bugron** [comment]
@AkiraLaine thanks for posting. Let's keep this discussion in #4263.
