### ISSUE TITLE
Chat UI Inconsistencies Umbrella Issue.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#40259]
Hi everyone,

We will be ironing out some of the known theme inconsistencies in the chat UI (mostly color based) in the next couple of days.

Please list the UI related issues that you come across as comments on this issue so they are tackled accordingly.

**Comment by Twaha-Rahman** [comment]
Small styling issue: Can't see the fCC logo in light mode.

![image](https://user-images.githubusercontent.com/39026437/99685565-eafb2080-2aac-11eb-8e9a-9b191a3dc592.png)
![image](https://user-images.githubusercontent.com/39026437/99686648-00bd1580-2aae-11eb-997a-ca0243eb1e3b.png)

**Comment by ahmadabdolsaheb** [comment]
Thank you @Twaha-Rahman. Most of the inconsistency issues seem to have been resolved, so I am closing this issue accordingly.

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb I found a small issue with the Logout button color on the registering screen 😄 Not sure if I should create a separate issue for this 

<img width="580" alt="Screen Shot 2020-11-28 at 6 05 24 PM" src="https://user-images.githubusercontent.com/25715018/100514171-051bb980-31a5-11eb-9ca0-ffab70e1bd00.png">

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen, thanks for letting me know.

**Comment by Twaha-Rahman** [comment]
A few more inconsistencies/UI bugs ->

![image](https://user-images.githubusercontent.com/39026437/101594084-46209300-3a1b-11eb-8109-82f5eca7121a.png)

**Comment by ojeytonwilliams** [comment]
It's not an inconsistency, exactly, but it's hard to tell that a room has unread messages, since it's grey vs a slightly different grey.  Is it possible to make it a little more obvious?

**Comment by ahmadabdolsaheb** [comment]
Yes,

**Comment by ahmadabdolsaheb** [comment]
Yes, we should be able e to resolve this among other issues this week.

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.
