### ISSUE TITLE
Can't sign in chat room by using GitHub

### ISSUE THREAD

**Issue by stevending1st** [freeCodeCamp/freeCodeCamp#40258]
**Describe the bug**
I can not sigin in [chat room](https://chat.freecodecamp.org/home) by using GitHub
on my Smartphone.

**To Reproduce**
![IMG_20201119_002820](https://user-images.githubusercontent.com/23376142/99558549-d3655e80-29fe-11eb-8171-44298cc926b2.jpg)
![IMG_20201119_003042](https://user-images.githubusercontent.com/23376142/99558571-d82a1280-29fe-11eb-8188-13eafcb1ee2b.jpg)
![IMG_20201119_003224](https://user-images.githubusercontent.com/23376142/99558591-dbbd9980-29fe-11eb-99eb-081f6e55d90c.jpg)

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser: via

**Comment by Sky020** [comment]
Hello there,

I have been able to sign in through GitHub. What happens after you click _Continue with GitHub_?

**Comment by stevending1st** [comment]
> Hello there,
> 
> I have been able to sign in through GitHub. What happens after you click _Continue with GitHub_?

It will turn to the first page without siginning in.
(SORRY. I'm very tired. I have to sleep. See you.
