### ISSUE TITLE
bug with mobile autocomplete in challenge code section

### ISSUE THREAD

**Issue by cacious7** [freeCodeCamp/freeCodeCamp#40251]
**Describe the bug**
When trying to replace the text inside the closing tag of an html element, the autocomplete deletes part of the closing tag and sometimes, some text before it. 

**To Reproduce**
1. Click [here](https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-footer-landmark)  to go to the challenge where I experienced this issue. But use a mobile phone. I used a Samsung S8 with a Google Chrome browser.
2. Try editing the current div element. However, don't delete the whole element or its tags. Given a div element as follows:
`<div> some content here </div>`
edit it by replacing the characters `div` with `footer`.
3. Edit the opening tag first and with the keyboard still open, put the cursor inside the closing tag.
4. Start editing by deleting the `div` text in the closing tag. The platform will attempt to auto complete the tag for you. This will cause the removal of the `</` part of the closing tag. In my case, it also removed some text that was just before the `</` part of the closing tag.
4. To replicate the bug, it is important that you keep the keyboard open and don't attempt to hide or close it while editing the opening and closing tags.

**Expected behavior**
I expected the auto complete to simply replace the characters `div` with the characters `footer` when attempting to autocomplete instead of deleting other characters and part of the closing tag in the process.

**Screenshots**
Before editing
![Screenshot_20201117-090017_Chrome](https://user-images.githubusercontent.com/17464196/99357318-62199480-28b4-11eb-94be-2f56fccddf20.jpg)

After editing opening tag and keeping keyboard open
![Screenshot_20201117-090224_Chrome](https://user-images.githubusercontent.com/17464196/99357409-870e0780-28b4-11eb-855d-f01d982151b9.jpg)

While keeping keyboard open, I start deleting the `div` characters and the buggy autocomplete engages.
![Screenshot_20201117-090133_Chrome](https://user-images.githubusercontent.com/17464196/99357533-bcb2f080-28b4-11eb-9d94-3e26dc2a16d1.jpg)

**Desktop:**
Please don't use a Desktop 

**Smartphone :**
 - Device: Samsung S8
 - OS: Android 9
 - Browser: Google Chrome
 - Version: 85.0.4183.101

**Additional context**
I have only noticed this problem on mobile and it really is annoying considering that coding on mobile naturally isn't a piece of cake, so autocomplete is one feature that should always work correctly.

**Comment by nhcarrigan** [comment]
Hello~!

This is a known issue with the Monaco editor and the default mobile keyboard. We actually have a news [article on using a mobile device](https://www.freecodecamp.org/news/freecodecamp-mobile/), which touches on some mobile keyboards specifically built for coding that are known to work well with our platform. We recommend trying these keyboards.

For now, we are going to close this issue. If you still encounter the bug after switching to a supported keyboard, feel free to provide the relevant information and request that we re-open the issue. 🙂
