### ISSUE TITLE
Solidify campers understanding of the return keyword/return statement

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#40260]
Seeing how many campers seem to struggle with understanding what returning inside a function does, especially inside loops, it would be great if we somehow were able to solidify this knowledge. It seems like we somehow have not made this clear enough when the return happens inside a loop.

Not sure where it would go in the current curriculum, we do have challenges on function returns, but as it most often relates to returning values inside loops I'm not sure if that is the right place.

The challenge that most clearly shows this lacking knowledge is the profile lookup challenge. Just look at the forum to see how many campers make the same mistake.
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/profile-lookup

**Comment by RandellDawson** [comment]
The first challenge where we explain some of this is https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions.

I suppose we could add another example to this challenge that demonstrates how a `for` or `while` would behave with respect to using a return statement inside it.

**Comment by lasjorg** [comment]
@RandellDawson The problem is that challenge comes before loops have been introduced. So having a loop in the challenge wouldn't work unless we move it. Next, returning from a loop doesn't constitute an early return (guard clause).

It would almost need both an early return and a return from inside a loop which might get confusing and interfere with what is being taught (early return).

Right now I can't even come up with a simple example but I will think about it some more. But I'm not so sure if this challenge is the right place for it.

**Comment by moT01** [comment]
We will adress this with the new project based curriculum. The current curriculum is not getting new additions in favor of that. If you think this is still an issue - feel free to leave a comment, and it can be reopened. Thanks and happy coding 🎉
