### ISSUE TITLE
SyntaxError: invalid regular expression flag s

### ISSUE THREAD

**Issue by danielkix** [freeCodeCamp/freeCodeCamp#40261]
Hi! I can't complete this simple Javascript challenge. I even tried copypasting the solution from the forums, but it's still identical to my solution.

This is the solution code:

> let quoteSample = "Blueberry 3.141592653s are delicious.";
> let myRegex = /[h-s2-6]/gi; // Change this line
> let result = quoteSample.match(myRegex); // Change this line

and the console output:

> // running tests
> Your regex myRegex should match 17 items.
> Your regex myRegex should use the global flag.
> Your regex myRegex should use the case insensitive flag.
> // tests completed
> SyntaxError: invalid regular expression flag s

I don't have issues with any other challenges, so I assume the problem is not on my side.

**Comment by Sky020** [comment]
Hello there,

The solution code passes for me:
![image](https://user-images.githubusercontent.com/51722130/99670835-13f9c200-2a69-11eb-96a4-ad5d9483ef73.png)

What browser are you using? Also, if you _hard-refresh_ (`Ctrl+Shift+R`) the page, does it work?

**Comment by Ismailtlem** [comment]
It passes for me as well
![Screenshot (483)](https://user-images.githubusercontent.com/34961373/99877337-d0848c80-2bfd-11eb-9d89-4909ca2340f2.png)

**Comment by ieahleen** [comment]
I have changed the title to highlight the issue: this syntax error message can appear on all challenges, and the cause has not been pinpointed yet, nor a way to fix the issue has been found

**Comment by Sky020** [comment]
Currently, we assume it has to do with the browser version. So, if you come across this, and have experienced this issue, please share which browser (and version), it was on.

**Comment by danielkix** [comment]
> Currently, we assume it has to do with the browser version. So, if you come across this, and have experienced this issue, please share which browser (and version), it was on.

I can confirm that. I was using Firefox 77.0.1 at first, now I updated to 83.0 and the issue is gone, the challenge works fine now. (Windows 10)
