### ISSUE TITLE
Test a For loop doesn't work using short syntax.

### ISSUE THREAD

**Issue by JeremasPosta** [freeCodeCamp/freeCodeCamp#40277]
**Describe your problem and how to reproduce it:**
Test a For loop doesn't work using short syntax.
If we got this code:
for(let user in usersObj) usersObj[user].online ? ++count : null;
The tests fail, but it works if we use the brackets syntax for the loop:
for(let user in usersObj){usersObj[user].online ? ++count : null};

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for---in-statement

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  87
* Operating System: Windows 10

![forin](https://user-images.githubusercontent.com/60799999/99888481-f0cb4000-2c2b-11eb-8fe5-76b548696a72.png)

**Comment by nhcarrigan** [comment]
```yml
  - text: The function <code>countOnline</code> should use a `for in` statement to iterate through the object keys of the object passed to it.
    testString: assert(code.match(/for\s*\(\s*(var|let|const)\s+[a-zA-Z_$]\w*\s+in\s+[a-zA-Z_$]\w*\s*\)\s*{/));
```

The test for this challenge specifically looks for the opening curly brace. This could be adjusted, but then I'd worry about the test erroneously passing for code that does not work.

**Comment by JeremasPosta** [comment]
Yes, I also check the associated .md file.
I think the regex can be redefined to allow the non curly braces condition
if the loop hasn't a newline character. But I don't know the implications
of this on other tests.

**Comment by Ismailtlem** [comment]
How about looking for the curly brace and looking for the ; character at most 2 times ? (one for the instruction after the for loop and one for the return statement)

**Comment by JeremasPosta** [comment]
@nhcarrigan I will see it better later and try to test  alternatives, but I think if we remove the curly brace on the regex, we don't change the important stuff of the expression. In fact, the regex only tests if there is an opening curly brace, not the closing one, so isn't it for syntax review either. The point here is to test the good syntax of the For In expression, so maybe it's unnecessary. 
Please correct me if I'm wrong.
