### ISSUE TITLE
Bad link in https://contribute.freecodecamp.org/#/

### ISSUE THREAD

**Issue by gsigler** [freeCodeCamp/freeCodeCamp#40274]
**Describe your problem and how to reproduce it:**
There is a bad link on the https://contribute.freecodecamp.org/#/ page. The link to 'help by answering coding questions' takes you to https://forum.freecodecamp.org/c/help which says "Oops! That page doesn’t exist or is private."

**Add a Link to the page with the problem:**
[https://contribute.freecodecamp.org/#/](https://contribute.freecodecamp.org/#/)

**Recommended fix, suggestions (how would you update it?):**
I tried looking around the forum for the page that that used to link to but I am not sure. I would say it could just go to the home page. 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1679" alt="Screen Shot 2020-11-20 at 8 48 48 AM" src="https://user-images.githubusercontent.com/15613806/99820221-b10e3680-2b0d-11eb-8bfe-563d9bb3a9b8.png">

<img width="1679" alt="Screen Shot 2020-11-20 at 8 49 35 AM" src="https://user-images.githubusercontent.com/15613806/99820232-b4092700-2b0d-11eb-80bd-83aab91fdb03.png">

**Comment by nhcarrigan** [comment]
Nice catch! This link broke when we restructured our subforum categories, I believe.

The link is located in this file: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/_coverpage.md, and could be updated to redirect to the base forum URL I think.

**Comment by RandellDawson** [comment]
@gsigler @nhcarrigan When I click on the link from https://contribute.freecodecamp.org, it loads the forum in he Project Feedback category.  There is not error.

**Comment by nhcarrigan** [comment]
@RandellDawson I get the Project Feedback category off the second link ("Give feedback on coding projects"), but on the "Help by answering coding questions" I'm getting a 404.

**Comment by RandellDawson** [comment]
I agree with adding a link to `https://forum.freecodecamp.org` for `Help by answering coding questions`.
