### ISSUE TITLE
can't complete

### ISSUE THREAD

**Issue by Skullcruncher** [FreeCodeCamp/FreeCodeCamp#4027]
Challenge [Waypoint: Divide one Decimal by Another with JavaScript](http://www.freecodecamp.com/challenges/waypoint-divide-one-decimal-by-another-with-javascript#?solution=var%20quotient%20%3D%202.2%3B%0Aquotient%2F%3D2.0%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(y)%7Breturn%20'quotient%3D'%2By%3B%7D)(quotient)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var quotient = 2.2;
quotient/=2.0;


// Only change code above this line.

(function(y){return 'quotient='+y;})(quotient);

```

**Comment by ltegman** [comment]
This question is asking you to make 2.2 the result of diving by 2.0, which means that your first number needs to be 4.4

Closing as not an issue with the tests, but feel free to reply if you need further clarification. 

Thanks and happy coding!

**Comment by JPRox** [comment]
I know this is closed but thankful for answer as division was never my strong point
