### ISSUE TITLE
Typo in Instructions: "You should only be using revserse to modify array."

### ISSUE THREAD

**Issue by Volkenas** [FreeCodeCamp/FreeCodeCamp#4028]
Challenge [Waypoint: Reverse Arrays with reverse](http://freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse#?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7Breturn%20array%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.



// Only change code above this line.

(function() {return array;})();

```

**Comment by bugron** [comment]
@Volkenas thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by bencassidy** [comment]
Submitted a fix here https://waffle.io/freecodecamp/freecodecamp/cards/56339ba554be2f0300e86cbf

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4029 is merged.
