### ISSUE TITLE
Clarify and fix up metric-imperial user stories

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40307]
The user stories on the [metric imperial converter](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter) should use "you" instead of "me". There could also be some clarification to the expected output [as discussed here](https://github.com/freeCodeCamp/freeCodeCamp/pull/39615#pullrequestreview-530219175). Note that the linked PR is not in production as of this post. We should also update the description to what is [described here](https://github.com/freeCodeCamp/freeCodeCamp/issues/39721), along with anything else mentioned there.

**Comment by haragona** [comment]
> The user stories on the metric imperial converter should use "you" instead of "me".
I belive it's written that way, beacause that's the way users usually express their request. "I want to do this... and that... I want the app to use this color..."

**Comment by nhcarrigan** [comment]
Heya @haragona - we actually try to maintain the second-person perspective for user stories across our projects, and recently updated the back-end project pages to match this. 🙂 

@moT01 I've got #40358 open to move the tests from the boilerplate to the `/learn` page - I could hit the "me" => "you" verbiage in that PR?

**Comment by moT01** [comment]
Might as well @nhcarrigan?
