### ISSUE TITLE
After login: "We couldn't find path /auth/auth0/undefined/learn" error at top of page

### ISSUE THREAD

**Issue by spatter1** [freeCodeCamp/freeCodeCamp#40303]
**Describe the bug**
After login: "We couldn't find path /auth/auth0/undefined/learn" error at top of page

**To Reproduce**
1. This behavior is present after logging in to FCC.  Appears at the top of the screen immediately after login.

**Expected behavior**
Would not expect to see this error

**Screenshots**
![image](https://user-images.githubusercontent.com/35873883/99987517-92fb3d00-2d7e-11eb-911b-2555ec947baa.png)

**Desktop (please complete the following information):**
 - OS: Experienced on Win10 and MacOS BigSur
 - Browser: Experienced in Chrome, Firefox, and Safari
 - Version: would have to check on FF and Safari, Chrome is Version 86.0.4240.198

**Smartphone (please complete the following information):**
Have not tried on Safari

**Additional context**
Does not appear in impair functionality of site.

**Comment by ojeytonwilliams** [comment]
Thanks for the report @spatter1, I've been able to reproduce it - all I needed to do was log out and log back in.

**Comment by raisedadead** [comment]
Yikes, this has been there for a bit it seems.

**Comment by RandellDawson** [comment]
Is this related to https://github.com/freeCodeCamp/freeCodeCamp/pull/40161?

**Comment by raisedadead** [comment]
Yes it is and we are investigating it.

**Comment by ojeytonwilliams** [comment]
> Is this related to #40161?

Possibly, but that's live on .dev as well as .org, but .dev works as expected.

**Comment by raisedadead** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/6064e827e9755331354fee060f2d00ea4b462903/config/env.js#L4

**Comment by raisedadead** [comment]
The releases were failing, but the Pipelines were false negative: 

https://dev.azure.com/freeCodeCamp-org/freeCodeCamp/_releaseProgress?_a=release-environment-deployment-group-logs&releaseId=431&environmentId=1138&deploymentGroupPhaseId=1039

We should harden this? Somehow?
