### ISSUE TITLE
Move to Node.js 14 LTS

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40314]
We want to start using Node 14 LTS, and would love some help in testing out the current setup, workflows etc. Particularly we want to watch out for outdated deps, and warnings.

Here is a list of things that we want to check:

- [x] The local dev setup
- [x] Building production builds
- [x] Warnings, errors, etc.
- [x] Update deps if needed.

**Comment by nhcarrigan** [comment]
I've been running 14 LTS for a while, and haven't run in to any issues building the dev instance locally. 🙂

**Comment by reutKeyshawn** [comment]
Is the issue still relevant?

**Comment by nhcarrigan** [comment]
Heya @reutKeyshawn~!

I believe this issue is still relevant, yes. If you are working on contributions to freeCodeCamp and are finding errors related to using Node 14 LTS, please share them here. 🙂

**Comment by Twaha-Rahman** [comment]
> I've been running 14 LTS for a while, and haven't run in to any issues building the dev instance locally.

Same here. Using Node v14 for some time and found no prob whatsoever. (Currently rocking v14.15.1)

**Comment by ojeytonwilliams** [comment]
> \> cross-env DEBUG=fcc:* node ./tools/scripts/seed/seedAuthUser
> 
> (node:31702) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31702) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:31702) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:31702) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency

These are new warnings from node 14

**Comment by nhcarrigan** [comment]
Are those from the `develop` script?

**Comment by ojeytonwilliams** [comment]
Yep, `npm run seed`.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams I might be mistaken, but I remember always seeing those warnings on my side. For both v12 and v14

**Comment by ojeytonwilliams** [comment]
For me, at least, it's new in v14. For example:

```sh
nvm use lts/erbium
npm run seed
nvm use lts/fermium
nvm run seed
```
only generates warnings for the second run.

**Comment by Sembauke** [comment]
Is this issue still relevant @raisedadead?

**Comment by raisedadead** [comment]
Yes - I haven't gotten around to updating the pipelines.
