### ISSUE TITLE
Code fences should have languages

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40316]
This allows us to highlight them with Prism.  For contrast, https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/conditional-execution has a code language for the answers:
![image](https://user-images.githubusercontent.com/15801806/100262590-a3611280-2f4c-11eb-8af8-2aed225e0db7.png)
vs
https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/make-a-relational-database
![image](https://user-images.githubusercontent.com/15801806/100263547-ee2f5a00-2f4d-11eb-805b-7c9a661577e1.png)

Some challenges have console output wrapped in code fences.  Ideally these should not use code fences since they are just text - a pre element would be more semantic.

To avoid extra work, this should wait until https://github.com/freeCodeCamp/freeCodeCamp/pull/39800 is merged.

**Comment by Sky020** [comment]
Did we get around to adding SQL to the prism plugin: https://github.com/freeCodeCamp/freeCodeCamp/pull/39079#issuecomment-644904634 ?

**Comment by ojeytonwilliams** [comment]
Nope: https://github.com/freeCodeCamp/freeCodeCamp/blob/b5d5ec5a901db51e13411ba2769fd2aa36f06f08/client/.babelrc#L56-L66

are there any others that we'd like?

**Comment by Sky020** [comment]
> are there any others that we'd like?

I cannot think of any other that we use. Maybe TypeScript for future prep?

**Comment by ojeytonwilliams** [comment]
Is Typescript on the horizon? If so, sure.

**Comment by RandellDawson** [comment]
> Is Typescript on the horizon? If so, sure.

If it is, it will be quite a while before it is implemented.

**Comment by nhcarrigan** [comment]
I believe it is covered as part of the project-based V7.

**Comment by RandellDawson** [comment]
> I believe it is covered as part of the project-based V7.

It was on the original roadmap and a project exists, but it might have to be changed or may be dropped.  I think there is no harm in adding support for it, unless that adds a lot more overhead to the Prism plugin.

**Comment by moT01** [comment]
Add SQL to the list?

**Comment by ojeytonwilliams** [comment]
> Add SQL to the list?

Sure.  So, we'd add typescript and SQL to the plugin.

Since the challenge template change has been merged, I'm happy opening this up for contributions.

**Comment by ieahleen** [comment]
> Some challenges have console output wrapped in code fences. Ideally these should not use code fences since they are just text - a pre element would be more semantic.

do you mean like below?
```
## --answers--

<pre>['csev@umich.edu', 'cwen@iupui.edu']</pre>

---

<pre>['csev@umich.edu']</pre>

---

<pre>['umich.edu', 'iupui.edu']</pre>

---

<pre>['csev@', 'cwen@']</pre>
```
(in the file the pre elements are not included, it's the answers for curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/regular-expressions-matching-and-extracting-data.md)

**Comment by ieahleen** [comment]
or it was more about these?
(curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/pandas-conditional-selection-and-modifying-dataframes.md)

```
## --answers--

</pre>
Tom      13
Kris     11
Ahmad     9
Beau      7
Name: Longest streak, dtype: int64
</pre>

---

<pre>
      Certificates  Time (in months)  Longest streak
Tom               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7
</pre>

---

<pre>
      Certificates   Longest streak
Tom               8               13
Kris              2               11
Ahmad             5                9
Beau              6                7
</pre>
```
