### ISSUE TITLE
Error message in challenge console on initial page load: "SyntaxError: invalid regular expression flag s"

### ISSUE THREAD

**Issue by JonDevOps** [freeCodeCamp/freeCodeCamp#40311]
**Describe the bug**
I am using the latest version of firefox and microsoft edge (I gave not tried this issue in chrome yet) and I keep getting the following message "SyntaxError: invalid regular expression flag s". I noticed when I copied and pasted the message here it also pasted the error message freeCodeCamp provides when you get a test wrong and fCC provides hints in the console letting you know what is wrong on that test (even though it did not visibly populate in the console). This issue is effecting all tests I navigate to.

**To Reproduce**
1. Go to 'https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/headline-with-the-h2-element'
2. See error in challenge console

**Expected behavior**
I expect there to be no error message in the console and for the console to display proper error messages I need to pass the challenges.

**Screenshots**
![fccGhIssue](https://user-images.githubusercontent.com/30133774/100184119-bf15db80-2eae-11eb-9172-ca8f989bbf57.png)

**Desktop (please complete the following information):**
 - OS: Lubuntu and Windows 10
 - Browser: Firefox and Microsoft Edge
 - Version: Firefox 70.0.1 (32-bit) Mozilla for Ubuntu Canonical 1.0 and Firefox 83.0 (64-bit) for Windows and Microsoft Edge 87.0.664.41 for Window (64-bit)

**Comment by RandellDawson** [comment]
@ojeytonwilliams I believe this an another issue reported like it are due to use using the `s` flag in a regex that is not supported in some slightly older Firefox browsers.  I remember a PR that was recently merged that added the `s` flag in one of the helper functions.  After it was merged, we have seen a spike in these issues reported here and on the forum.  Maybe we should change the regex to remove the `s` flag and wait till the more people are using the latest versions of Firefox.

@JonDevOps You can upgrade your Firefox to the latest version and this should resolve the issue.

**Comment by JonDevOps** [comment]
Im going to give it a shot. Thanks for the info.

**Comment by JonDevOps** [comment]
Im going to give it a shot. Thanks for the info.

**Comment by ojeytonwilliams** [comment]
@RandellDawson that seems reasonable.  Do you know which other challenges are affected?

**Comment by ieahleen** [comment]
@ojeytonwilliams reports on the forum are for many challenges in the first two certs (I don't think I have seen it for others)

also already reported in #40261

**Comment by ieahleen** [comment]
this seems to have been the change that started the error:
https://github.com/freeCodeCamp/freeCodeCamp/commit/11dfe9274fb358008bd7eb7718b3901a87afcea4

**Comment by moT01** [comment]
Hey @ieahleen, are there still reports for this coming in?

**Comment by ieahleen** [comment]
@moT01 Yes, but it seems more rarely, people that have not yet updated their browser or stuck with a device where they are not authorized to do the updates.
