### ISSUE TITLE
[FORUM] - Nav bar is misaligned on dropdown event

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40318]
**Describe the bug**

When selecting one of the dropdown menu options on the forum, if the page is scrolled down at all the nav bar drops to the middle of the page.

**To Reproduce**
1. Go to https://forum.freecodecamp.org
2. Scroll the page down a bit.
3. Click on the `Menu` button in the top right of the nav.
4. Nav bar drops to centre of screen.

**Expected behavior**

The nav-bar should remain fixed in place.

**Screenshots**

![image](https://user-images.githubusercontent.com/63889819/100285828-6aae4280-2f26-11eb-8fa8-48f3dd803d99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1909
 - Browser: Chrome
 - Version: 86.0.4240.198

**Additional context**

/cc @ieahleen @bradtaniguchi

**Comment by bradtaniguchi** [comment]
I also see the issue in firefox,
version: 84.0b1 (firefox developer)

**Comment by yaezah** [comment]
<header class="d-header clearfix">

.d-header {
    position: absolute;
}

fixes it for me on chrome

**Comment by Sky020** [comment]
I am also experiencing this on Edge.

**Comment by lasjorg** [comment]
Adding `top: 0` to `.d-header` also seem to "fix" it.

---

But unless I just never noticed it, there seems to be something more going on. The "Menu" button is getting some borders added which is pushing everything around and the vertical alignment of the "Sign Up" and "Log In" buttons seems off.

![menu](https://user-images.githubusercontent.com/28780271/100294128-1a66cd00-2f86-11eb-8eb9-6ed800050fd2.gif)

There is also something wrong with the stacking order. The fCC logo in the middle is below the nav and I triggered some odd stacking bug on scroll as well.

![stacking-bug](https://user-images.githubusercontent.com/28780271/100294139-1e92ea80-2f86-11eb-8fd7-d1189cdea12e.gif)
![stacking-bug2](https://user-images.githubusercontent.com/28780271/100294284-a7118b00-2f86-11eb-990c-e55b17534c01.gif)

**Comment by nhcarrigan** [comment]
I think this is all new, but I'm not seeing any recent commits in the discourse repository that would have triggered this.

**Comment by lasjorg** [comment]
Looking at the dashboard it looks like there was an update 13 hours ago.

meta tag with the version we are running:
`<meta name="generator" content="Discourse 2.6.0.beta6 - https://github.com/discourse/discourse version 9ec0359022a0f6441972d9890313a8069552b904">`

Discourse 2.6.0.beta6 release notes
https://meta.discourse.org/t/discourse-2-6-0-beta6-release-notes/170642

Two things from the release notes that possibly seem relevant is "Disable local edits of remote themes" and "Add support for auto-updating themes on Discourse updates". Not sure if it's related to the bug or not.

**Comment by ieahleen** [comment]
now it seems back in order, does this still need to stay open?

**Comment by lasjorg** [comment]
The main issue does seem to be fixed.

The stacking bug on scroll is still there (I think it's a stacking issue anyway).

Navigate to some thread and scroll down. The "Sign Up" button will disappear and so will the menu if open. This doesn't happen on the main page or sub-pages on the forum, only when looking at an individual thread.

**Comment by nhcarrigan** [comment]
@ahmadabdolsaheb any thoughts on @lasjorg's comment?

The rest of the issues seem to be fixed by:
https://github.com/freeCodeCamp/forum-theme/pull/37
https://github.com/freeCodeCamp/forum-theme/pull/36

**Comment by ahmadabdolsaheb** [comment]
Thanks for bring this to my attention, @nhcarrigan.

@lasjorg, that is discourse's default behavior. That element gets removed from the dom.
I am aware of the margin. The is a pr is the works that would completely remove those nav items in favor of icons.

It seems the main issue has been resolved, so I am closing this issue accordingly. 

Feel free to re-open this issue if the issue persists.

**Comment by lasjorg** [comment]
@ahmadabdolsaheb Right, I had some time to actually look at it, as you said there is DOM manipulation on scroll that only happens when viewing a thread. I guess the button being removed is to make room for the thread title in the header and because we hide the title it just looks a little off to me (once you see it you can't unsee it kind of thing).

The menu being removed on scroll seems more like some technical limitation and is in my opinion not great UX (only happens on scroll when the header "switches" to have/not have the thread title). But that's not our fault.
