### ISSUE TITLE
Quality Assurance Projects - Sudoku Solver Example URL is down

### ISSUE THREAD

**Issue by fuzzyray** [freeCodeCamp/freeCodeCamp#40333]
**Describe the bug**
The example URL at https://sudoku-solver.freecodecamp.rocks/ is down and is returning an error 504 Gateway time-out response. All of the other Quality Assurance example URLs are functioning correctly.

**To Reproduce**
1. Go to https://sudoku-solver.freecodecamp.rocks
2. wait
3. See error

**Expected behavior**
Functioning example project

**Screenshots**
![gateway=timeout](https://user-images.githubusercontent.com/928480/100523407-ebaf4900-3175-11eb-875a-51b6d6958a3f.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 87.0.4280.67 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: IOS 14.2
 - Browser: Safari
 - Version: 14

**Additional context**
Screenshot is from iPhone using IPv6, it also is failing with IPv4 from the desktop

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this @fuzzyray. I went into the server and restarted that project. `pm2` reported it was at ~65% CPU usage for some reason, with some other projects/processes bringing the VM's CPU usage up to 100% for some reason.

I restarted the Sudoku Solver project and it loads fine now. Not sure what caused it to hang like this, but will leave this issue open while we investigate.

Cc @moT01 and @RandellDawson

**Comment by ojeytonwilliams** [comment]
Is it possible that it's simply an inefficient algorithm?  Brute force solutions have exponential time complexity and I believe the algorithm we use is brute force with backtracking.

**Comment by nhcarrigan** [comment]
The algorithm is a pretty heavy recursive function call, so that's entirely possible.

**Comment by ojeytonwilliams** [comment]
Rewriting it to bail out of long computations might not be trivial, though it's a possibility.  There are a bunch of fast algorithms, too.  

Anyway, it's still something of a hypothesis at the moment - we should dig around in the logs to see if a slow algorithm is a likely candidate first.

**Comment by moT01** [comment]
Update: The example was down again today. Not sure how long it was down. Same observations - pm2 shows CPU usage at 66.7% for the sudoku project. I just restarted it again to fix - may need to dig deeper at some point.

**Comment by moT01** [comment]
Does anyone know if a more permanent solution was implemented on the server to resolve this? I don't think this issue has popped back up in a while.

cc @freeCodeCamp/dev-team

**Comment by raisedadead** [comment]
Seeing this thread for the first time. We did not make any config changes. If it does reappear, we should be able to configure the resources allotted to the process with PM2.
