### ISSUE TITLE
A small mistake in the forth example of "const" in the given link

### ISSUE THREAD

**Issue by sthamit7** [freeCodeCamp/freeCodeCamp#40356]
**Problem description =>** 
In the link given below is an important concept of Var, Let and Const in JavaScript. 
I am absolutely happy with the post but I found a slight mistake in the snippet code for Const => 
After the line  **"While we cannot do this"**

It says the code should not work & should give an error but the code is working properly with no error. 
Even If the writers intention was to show object properties cannot be updated, the error given is incorrect.

**Link to a problem=>**
https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/

**Recommended Solution**
If the writers intention was to show object properties cannot be updated with the correct error => 

`const greeting = {
    words: "Hello",
    number: "five"
}
greeting = {
    words: "Hello",
    number: "five"
}
 // error:  Assignment to constant variable.`

** Screen shot of the error**
Note: After the line  **"While we cannot do this"**
![bug](https://user-images.githubusercontent.com/16065794/100577435-44ade700-3306-11eb-8d27-e1bba81d69d9.png)

**Comment by sthamit7** [comment]
My only concern was for those beginners who was stuck in this because of this slight mistake.

**Comment by nathanhannig** [comment]
I think some of your typed response is a little inaccurate probably on accident. I also do get an error when testing the code in the browsers console. 

But overall, I do agree with you that the article is incorrect in providing the redeclaration of the variable as a `const `and that should be removed.

```
greeting = {
    words: "Hello",
    number: "five"
} // error:  Assignment to constant variable.
```

**Comment by sthamit7** [comment]
> I do get an error when testing the code in the browsers console.
> 
> But overall, I do agree with you that the article is incorrect in providing the re-declaration of the variable as a `const `and that should be removed so that it is treated only as a re-assignment.
> 
> ```
> greeting = {
>     words: "Hello",
>     number: "five"
> } // error:  Assignment to constant variable.
> ```

Did you get this error specifically? => **Assignment to constant variable**

**Comment by sthamit7** [comment]
> I do get an error when testing the code in the browsers console.
> 
> But overall, I do agree with you that the article is incorrect in providing the re-declaration of the variable as a `const `and that should be removed so that it is treated only as a re-assignment.
> 
> ```
> greeting = {
>     words: "Hello",
>     number: "five"
> } // error:  Assignment to constant variable.
> ```

Exactly, this is also my recommended solution. The **const** must be removed from the snippet.

**Comment by ojeytonwilliams** [comment]
Hey @sthamit7, @nathanhannig, thanks for spotting this and providing the fix.  I've updated the original article with your suggestion.
