### ISSUE TITLE
Quality Assurance Projects - Sudoku Solver undefined use case

### ISSUE THREAD

**Issue by fuzzyray** [freeCodeCamp/freeCodeCamp#40359]
**Describe your problem and how to reproduce it:**
While working on the Sudoku solver project, one scenario came up that wasn't clear to me how to handle. 

The scenario is what do you do, if I ask to check a value of a cell with an existing value? 

For my project, I chose to return a conflict with the row, column, and region. However, I checked what the example app returns. The results it returns are logically inconsistent, which tells me this use case is undefined.

For the example app:
1. Goto https://sudoku-solver.freecodecamp.rocks
2. For coordinate enter C3, for value enter 2 (the existing value), click Check Placement
3. App returns ```{ "valid": false, "conflict": [ "row", "column", "region" ] }```
4. Change value to 9, App returns ```{ "valid": false, "conflict": [ "column", "region" ] }```
5. Change value to 1, App returns ```{ "valid": true }```

These response are not logically consistent. For the first one, it appears to be checking against all of the existing values in the puzzle. For the second and third cases, it appears to be checking after replacing the value.

I would expect this use case to be defined as either, it's a conflict, because there is an existing value at that cell or to replace the value in that cell and then check if it is valid or not and return the appropriate results.

**Add a Link to the page with the problem:**
1. https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/sudoku-solver
2. https://sudoku-solver.freecodecamp.rocks

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 87.0.4280.67 (Official Build) (x86_64)
* Operating System: macOS Mojave 10.14.6

**Comment by nathanhannig** [comment]
I feel there is a better example to describe the issue I see.

Let us take the first region only and try the following
C1, 9 result is `{ "valid": false, "conflict": [ "region" ] }`
A2, 8 result is `{ "valid": false, "conflict": [ "region" ] }`
B2, 5 result is `{ "valid": false, "conflict": [ "row", "column", "region" ] }`
A3, 4 result is `{ "valid": false, "conflict": [ "region" ] }`
B3, 3 result is `{ "valid": false, "conflict": [ "region" ] }`
C3, 2 result is `{ "valid": false, "conflict": [ "row", "column", "region" ] }`

Why do B2, 5 and C3, 2 return more conflicts?

**Comment by nathanhannig** [comment]
Yes, seems odd that you can place a value over an existing spot and it can return as valid

**Comment by nhcarrigan** [comment]
> App returns { "valid": false, "conflict": [ "row", "column", "region" ] }

I do agree that this should be handled as a valid placement (given that the number is already present in that cell). Unless there is objection/disagreement, I'd be willing to open this up for contribution. 🙂

**Comment by moT01** [comment]
I also vote to make it behave as if it replaces the cell before checking validity. Or something along those lines. I have opened this up for contributions.
