### ISSUE TITLE
Challenge "Regular Expressions: Reuse Patterns Using Capture Groups" not accepting a valid regex

### ISSUE THREAD

**Issue by rajatkantinandi** [freeCodeCamp/freeCodeCamp#40376]
**Describe your problem and how to reproduce it:**
This challenge is not aceepting the regex `/^(\d+)(\s\1)\2$/` which is valid and matches all the conditions except one condition `Your regex should have two spaces separating the three numbers.` because it is checking whether 2 `\s` is used in the regex or if `(\s)` is used along with `\1` or `\2`. So, it does not accept the above regex.

**Add a Link to the page with the problem:**
[Regular Expressions: Reuse Patterns Using Capture Groups](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups)

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 83.0 (64-bit)
* Operating System: macOS 11.0.1 Big Sur

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Thank you, for taking the time to raise this issue. I can confirm the issue.

I suggest the test in question be removed:
````text
Your regex should have two spaces separating the three numbers.
```javascript
assert(
  reRegex.source.match(/ |\\s/g).length === 2 ||
    reRegex.source.match(/\(\\s\)(?=.*\\(1|2))/g)
);
```
````

There should be no need for it, as the test conditions satisfy the requirements of the instructions. I am opening this to _first timers only_

**Comment by moT01** [comment]
I'm fine with removing that test.

**Comment by alsoto25** [comment]
I've went ahead and changed this one to start familiarizing myself with the code and hopefully keep contributing. Please tell me if there's any problem.
