### ISSUE TITLE
Syntax Error: invalid regular expression flag s

### ISSUE THREAD

**Issue by LilloLu** [freeCodeCamp/freeCodeCamp#40374]
Everytime I try to do a challenge, this shows up. What's going on?

**Comment by Sky020** [comment]
Hello there,

Thank you, for taking the time to open this. However, an issue for this has already been opened: https://github.com/freeCodeCamp/freeCodeCamp/issues/40311

As such, I am closing this as a duplicate.

For future issue reports, please include as much information as possible in the body of the issues.

Cheers
