### ISSUE TITLE
not able to update the avatar of a Chat room

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#40373]
**Describe the bug**
I tried to update the avatar of [this room](https://chat.freecodecamp.org/channel/bangzhu) as below. But it turned out to be a blank image.
![image](https://user-images.githubusercontent.com/19358186/101243123-09158180-3739-11eb-9ca4-3918add404ed.png)

**Expected behavior**
update the avatar successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/19358186/101243129-1894ca80-3739-11eb-86e2-62b9b1d502c5.png)
![image](https://user-images.githubusercontent.com/19358186/101243218-a40e5b80-3739-11eb-9a8e-7a1c38fcdd20.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 10.13.6

**Comment by ahmadabdolsaheb** [comment]
cc @nhcarrigan :)

**Comment by nhcarrigan** [comment]
I attempted an upload myself and got the same bug. This may be related to the switch to S3 for chat uploads. I'll try to poke around today and see if I can identify the issue. :)

**Comment by nhcarrigan** [comment]
Hey @miyaliu666 - I'm seeing the new chat room avatar successfully loading this morning. Can you confirm if it is present on your end as well?

It could have potentially been a caching issue. 🤔

**Comment by deka981** [comment]
> **Describe the bug**
> I tried to update the avatar of [this room](https://chat.freecodecamp.org/channel/bangzhu) as below. But it turned out to be a blank image.
> ![image](https://user-images.githubusercontent.com/19358186/101243123-09158180-3739-11eb-9ca4-3918add404ed.png)
> 
> **Expected behavior**
> update the avatar successfully
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/19358186/101243129-1894ca80-3739-11eb-86e2-62b9b1d502c5.png)
> ![image](https://user-images.githubusercontent.com/19358186/101243218-a40e5b80-3739-11eb-9a8e-7a1c38fcdd20.png)
> 
> **Desktop (please complete the following information):**
> 
> * Browser: Chrome
> * Version: 10.13.6

**Comment by ojeytonwilliams** [comment]
Hey @miyaliu666 I just tested this today and the uploaded image was instantly available.  Is it working for you now?

**Comment by miyaliu666** [comment]
Kris helped me figure out how to update it, and we already updated the room said above. Sorry I didn't close this issue.

**Comment by ojeytonwilliams** [comment]
Cool, thanks for confirming, I'm glad it's sorted out.
