### ISSUE TITLE
Missing 'News' button in Nav bar in the home page which is present previously

### ISSUE THREAD

**Issue by NagendraDevara** [freeCodeCamp/freeCodeCamp#40375]
Previously FreeCodeCamp users used to find the news section in the navbar of the home page but the new link is no more present in the navbar. Please include the 'News' hyperlink in the navbar so that new viewers will get to know about the blog of the 'FreeCodeCamp'.Here  I am including screenshots of how it looked previously and how the home page nav bar is looking now.

Previous webpage:
![image](https://user-images.githubusercontent.com/24850111/101245274-ac629880-3731-11eb-87f8-1c881a5fb8f8.png)
Present homepage:
![image](https://user-images.githubusercontent.com/24850111/101245294-d0be7500-3731-11eb-8962-56e47ee7d660.png)

**Comment by Sky020** [comment]
Hello there,

This was done intentionally, and here is some added background for the discussion: https://forum.freecodecamp.org/t/proposed-improvements-to-the-freecodecamp-forum-localization-approach/426565

And: https://github.com/freeCodeCamp/freeCodeCamp/issues/40033

I will leave this open as a feature request, but currently, there is no intention to re-introduce the `news` nav button.

Hope this clarifies
