### ISSUE TITLE
Example site not functioning correctly

### ISSUE THREAD

**Issue by alanbuchanan** [FreeCodeCamp/FreeCodeCamp#4038]
Challenge [Basejump: Chart the Stock Market](http://www.freecodecamp.com/challenges/basejump-chart-the-stock-market) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Example site http://stockstream.herokuapp.com/ is not functioning as expected. When submitting a stock code using form, console shows:

 `GET https://www.quandl.com/api/v1/datasets/WIKI/MMM.json?sort_order=asc&exclude…trim_start=2015-01-01&trim_end=2015-010-30&auth_token=PwyZscKorv3wCa-dEbtX 422 (Unprocessable Entity)`

**Comment by awesomeaniruddh** [comment]
Maybe you can use mine until that one gets fixed or an official FCC solution is created?

My 'stock charter': https://stockcharter.herokuapp.com/#/

Or if the other campers have a better solution, then there suggestions are welcome too.

**Comment by drorm** [comment]
Works for me. I added "goog" and "ibm" and the graph refreshed. Maybe someone fixed the heroku app? The URL that  you include above won't work since the end date "2015-010-30" is incorrect.  At this point, I'd vote to close this as worksforme or equivalent.

**Comment by ltegman** [comment]
Closing as no repro since it appears to work fine now. Please reopen with repro steps if you are still seeing this issue.
