### ISSUE TITLE
Live class

### ISSUE THREAD

**Issue by alan2006-star** [freeCodeCamp/freeCodeCamp#40381]
Do you have live classes for coding. If there Pls inform

**Comment by ahmadabdolsaheb** [comment]
@alan2006-star, we don't offer live classes, but we have live stream tutorials on our [youtube channel](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ), and video lessons where you could learn on your own pace.


I encourage you to continue this discussion on our community [forum](https://forum.freecodecamp.org/) to get the feedback of the community.
