### ISSUE TITLE
Console Incorrectly Setup in Escape Literal Quotes Challenge

### ISSUE THREAD

**Issue by paulsonjpaul** [freeCodeCamp/freeCodeCamp#40388]
**Describe your problem and how to reproduce it:**

I was completing the [Escaping Literal Quotes](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escaping-literal-quotes-in-strings) in Strings in Basic JavaScript. I did everything correctly, but the result shown in the console was not what was expected in the challenge.

Expected Output (stated in the challenge):

`I am a "double quoted" string inside "double quotes".`

Output Shown in Console:

`myStr = "I am a "double quoted" string inside "double quotes"."`

Please notice the last double quote in the console output, (which should not be the output). First, I thought this was an error with my code, but my code is correct and to make sure, I copied it from the video.

To find the problem, I added `console.log(myStr)` and surprisingly, it showed me the real result of my code.

I know this is a silly problem, but I have been taught that even a typo should we reported.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escaping-literal-quotes-in-strings

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox Developer Edition (upto date)
* Browser Version: Version 84.0b8
* Operating System: Windows 10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/73777251/101312206-2e110e00-3879-11eb-916b-bb12996bf52e.png)

**Comment by limvus** [comment]
Hi paulsonjpaul,
It looks like it is intended. It makes sense because the whole string need to be wrapped in double quote as well. That's why it's a double quote inside double quote.

**Comment by paulsonjpaul** [comment]
Oops! I did not think of that. Thanks for the clarification
