### ISSUE TITLE
Challenge:Regular Expressions: Find One or More Criminals in a Hunt

### ISSUE THREAD

**Issue by nikikalwar** [freeCodeCamp/freeCodeCamp#40397]
**Describe your problem and how to reproduce it:**
Regex expression should fail according to the problem specified but is passing due to missing test cases.

Write a greedy regex that finds one or more criminals within a group of other people. A criminal is represented by the capital letter C.
let reCriminals = /C+/; // Change this line//this passed and is according to question.

let reCriminals = /c+/ig; // Change this line//this regex should fail since capital letter is asked on question and will match lower-upper case//passed

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/find-one-or-more-criminals-in-a-hunt

**Tell us about your browser and operating system:**
* Browser Name: FireFox
* Browser Version: 83.0
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Thank you, for taking the time to open this issue.

I am not sure there is any need to do anything here. The aim of the lesson is to teach the `+` quantifier, but I do understand what you are getting at about campers being able to pass without following the instructions.

As you say, if anything is to be done, a test needs to be added/altered checking that the `reCriminals` variable does not match `c`.

I will leave this up for others to weigh in on.

**Comment by moT01** [comment]
To try and clarify the problem, you are supposed to match capital `C` letters. With the `let reCriminals = /c+/ig;` regex @nikikalwar mentioned, it will match lowercase and capital `c`'s, but there is no test to catch that.

Since the instructions specifically say capital `C`, I think we can make a change here. I vote to just change one of the existing tests to include a lowercase `c`.
