### ISSUE TITLE
[TYPO] Basic JavaScript: Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by samezuka** [freeCodeCamp/freeCodeCamp#40398]
This is a dumb problem and I am new to GitHub so please forgive me for any weirdness. Basically, on this page, we see this explanation:

----
_This signals to JavaScript that the following quote is not the end of the string, but should instead appear inside the string. So if you were to print this to the console, you would get:

Alan said, "Peter is learning JavaScript"._
----

and we are asked to make this string:  _I am a "double quoted" string inside "double quotes"._

However, I think that the period should be inside the quotations, grammatically. Like _"double quotes."_ 

Thank you.

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escaping-literal-quotes-in-strings

**Comment by ieahleen** [comment]
Thank you for your bug report, but I think this is in the realm of bike shedding

**Comment by Twaha-Rahman** [comment]
I do agree with @ieahleen that this is indeed a small typo but I also agree with @samezuka that it is indeed a grammatical prob.

Since this typo got noticed, I'd say let's fix it. 😃

**Comment by RandellDawson** [comment]
While I think it is fine to correct the typo, I think the tests should be loose enough to accommodate the period inside or outside the last double quote.  The point of the challenge is escaping double quotes, so we do not want to get caught up in a period inside or outside the quotes.  The reason I say this is the new curriculum is going in this direction.  We are going to be lenient in the tests when it makes sense to.  In my opinion, this is one of those cases.

**Comment by RandellDawson** [comment]
@Twaha-Rahman Is this still a first-timers issue now, since the contributor must also modify the test to accommodate both versions of the string?

**Comment by Twaha-Rahman** [comment]
> @Twaha-Rahman Is this still a first-timers issue now, since the contributor must also modify the test to accommodate both versions of the string?

Ooops. Forgot to update that.

**Comment by samezuka** [comment]
> While I think it is fine to correct the typo, I think the tests should be loose enough to accommodate the period inside or outside the last double quote. The point of the challenge is escaping double quotes, so we do not want to get caught up in forcing the user to keep the period inside or outside the quotes. The reason I say this is the new curriculum is going in this direction. We are going to be lenient in the tests when it makes sense to. In my opinion, this is one of those cases.

Thank you for your reply. I agree the grammar shouldn’t matter in the challenge.

The problem was that when I tried to submit the answer with the “proper grammar,” it told me my answer was wrong, and I had to change it to the “improper” way.

I’m an English teacher rather than a programmer, so completing the challenge with the improper grammar hurt my soul a little bit, haha.

**Comment by Twaha-Rahman** [comment]
Hey @RandellDawson , I just made a PR (#40426) that fixes the grammar issue and it looks quite simple as there's no need to change the tests. So, let's open this up for `First Timers`, what do you say?

**Comment by Sky020** [comment]
Just to add this: I do not see this as a bug/typo, because I mostly use British-styled English.

So, the only reason we might change this is if we are trying to have uniformity about using only American-styled English within the curriculum.

**Comment by ieahleen** [comment]
@Twaha-Rahman both versions should be allowed, dot inside snd dot outside. Your PR just changes with version is allowed

**Comment by Twaha-Rahman** [comment]
> Just to add this: I do not see this as a bug/typo, because I mostly use British-styled English.
> 
> So, the only reason we might change this is if we are trying to have uniformity about using only American-styled English within the curriculum.

I didn't knew that it differed in these two styles. If that is the case I'm in favour of closing this issue as it is proper English eitherway.

@ieahleen The tests and the sentence in the test question isn't changed in my PR as it is correct. I only changed the example sentence in the PR.

(Apologies for the trouble and misunderstanding 😅)

**Comment by ieahleen** [comment]
@raisedadead the change discussed here about making both solutions work is not wanted anymore?

**Comment by raisedadead** [comment]
Re-opening.
