### ISSUE TITLE
Challenge Waypoint: Filter Arrays with filter has an issue.

### ISSUE THREAD

**Issue by gangstafat** [FreeCodeCamp/FreeCodeCamp#4039]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%20%3C%205%20%3D%3D%3D%20true%3B%0A%7D)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7B%20return%20newArray%3B%20%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.

It asked me to use filter to remove all elements from array that are greater than 5. When I run test with my code, the result I got is true but it didn't let me pass.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val < 5 === true;
});

// Only change code above this line.

(function() { return newArray; })();

```

**Comment by ltegman** [comment]
Looks like your code isn't just removing values greater than 5, it is also removing 5.

Closing as not an issue with the tests but feel free to reply if you need further clarification.

Thanks and happy coding!

**Comment by gangstafat** [comment]
Oh I see, thank you!

**Comment by Mohab17** [comment]
Hi it must be:

  return val < 6 === true;
