### ISSUE TITLE
Some certifcate links open in a new tab, some in same tab

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40402]
If I click on a link to a certificate from my settings page, it opens in the same tab. If I click on one from the timeline on my portfolio, it opens in a new tab. We could probably make this consistent. I believe I made the timeline links open in a new tab because there's no nav on the cert pages, so the only way to get back to the site is with the browsers back button. I believe I have also heard an argument that they should open in the same tab so I'm not sure what the better way to go is.

**Comment by asperger99** [comment]
sir.. i would like to solve this issue...**can i contribute??**

**Comment by ahmadabdolsaheb** [comment]
#@asperger99,  please go ahead 👍. No assignment is necessary as described in our [contribution guidelines](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.

**Comment by NirajNair** [comment]
So should it open in a new tab or in the same tab? what should happen?

**Comment by asperger99** [comment]
same question as @NirajNair ....what shold happen?? @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
I will double check with the dev team and get back to you.

**Comment by moT01** [comment]
My vote was to open them in a new tab - like I said, there's no nav on the certs so you have to use the browsers back button to get back to the website.

**Comment by NirajNair** [comment]
@moT01 I agree

**Comment by moT01** [comment]
I was told, "If the user donates on the certificate, the redux store will not be updated on the other tab and would need a refresh". So, I think that for now, we should open them in the current tab - unless someone has a better solution to that.

**Comment by ShaunSHamilton** [comment]
> "If the user donates on the certificate, the redux store will not be updated on the other tab and would need a refresh"

Could you clarify this?
- If the user donates on the certificate opened on a new tab, the redux store will not be opened on the original (settings) tab?

This does not sound much like a problem. In fact, I would have said that is expected behaviour, from past experience.

**Comment by ahmadabdolsaheb** [comment]
So If a user donates on their certificate the store on that tab gets updated (isDonating: true). When the user goes back to the previous tab to work on the challenges, she will see the donation modal. (unless refresh). 

Solutions: 

1) keep a navigation on the certs and keep them in the same tab
2) open certs in new tab but sync state across tabs,

Might find this one helpful. https://medium.com/@daverivera90/sharing-state-between-browser-tabs-with-redux-68899eb88fb7

**Comment by alirezaghey** [comment]
What is the chosen path to solve this issue? Or am I missing something?

**Comment by ahmadabdolsaheb** [comment]
We have not come to an agreement regarding the way to move forward yet. 

The options are listed [above](https://github.com/freeCodeCamp/freeCodeCamp/issues/40402#issuecomment-750256121).

Once we reach an agreement, we should make the experience consistent across the app.
