### ISSUE TITLE
Incompatibiilty between tests?

### ISSUE THREAD

**Issue by bresson** [FreeCodeCamp/FreeCodeCamp#4040]
Challenge [Bonfire: Truncate a string](http://www.freecodecamp.com/challenges/bonfire-truncate-a-string#?

There seems to be an incompatibility in the test cases for this Bonfire. Under the Bonfire rules, the test 
    
    truncate("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length) should return "A-tisket a-tasket A green and yellow basket".
truncate("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length + 2) should return "A-tisket a-tasket A green and yellow basket".

should yield "A-tisket a-tasket A green and yellow bas..."

Similarly, 

    truncate("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length + 2) should return "A-tisket a-tasket A green and yellow basket".

should yield A-tisket a-tasket A green and yellow baske..."

solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20var%20strTrun%20%3D%20''%3B%0A%20if%20(%20str.length%20%3E%203%20)%20%7B%0A%20%20%20%20strTrun%20%3D%20str.substr(%200%2C%20num%20-%203%20)%20%2B%20'...'%3B%0A%20%20%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20strTrun%20%3D%20str.substr(%200%2C%20num%20%20)%20%2B%20'...'%3B%0A%20%20%7D%0A%20%20console.log(strTrun)%3B%0A%20%20return%20strTrun%3B%0A%7D%0A%0Atruncate(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncate(str, num) {
  var strTrun = '';
 if ( str.length > 3 ) {
    strTrun = str.substr( 0, num - 3 ) + '...';
  
    
    
  } else {
    strTrun = str.substr( 0, num  ) + '...';
  }
  console.log(strTrun);
  return strTrun;
}

truncate("A-tisket a-tasket A green and yellow basket", 11);

```

**Comment by jbmartinez** [comment]
It seems your code is truncating and adding the dots even if its not necessary, try running
```javascript
truncate("abcde", 20);  //returns "abcde..."
truncate("abcde", 5);  //returns ab...
```

I think it should return "abcde" in both cases

**Comment by bresson** [comment]
OK I see the conditional now (Truncate a string (first argument) if it is longer than the given maximum string length (second argument). ). Please close this ticket per my mistake but I do recommend a redraft of the instructions for this bonfire. There are three caveats in the conditionals and it would make better sense to place them all in place.
