### ISSUE TITLE
Flesh-Out Exercise Tracker User Stories and Typo

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#40405]
In order to avoid common confusion with this project, I suggest we add something along the lines of:

```typescript
interface Exercise {
  description: string,
  duration: number,
  date: Date, // Specifically: toDateString (date portion of Date object
}

interface NewUser {
  _id: string,
  username: string,
}

interface Log {
  count: number,
  log: Exercise[],
}

```

I expect this to be added to the description of the challenge. Something to that extent.

---

Also, there is a small typo, which can be easily fixed: [from this forum post](https://forum.freecodecamp.org/t/tiny-typo-in-exercise-tracker-challenge/443740)
You can POST to /api/exercise/new-user with form data username to create a new user. The returned response will be an object with username and _id properties.

You can make a GET request to :point_right: api/exercise/users to get an array of all users. Each element in the array is an object containing a user’s username and _id .

You can make a GET request to /api/exercise/log with […]

**Comment by nhcarrigan** [comment]
This challenge doesn't have an instructions field currently, so maybe we could leverage that. Something like:
````md
Your responses should have the following structures.
Exercise:
```js
{
  username: "fcc_test"
  description: "test",
  duration: 60,
  date: "Mon Jan 01 1990",
  _id: "5fb5853f734231456ccb3b05"
}
```
User:
```js
{
  username: "fcc_test",
  _id: "5fb5853f734231456ccb3b05"
}
```
Log:
```js
{
  username: "fcc_test",
  count: 1,
  _id: "5fd01a41c5b5cf05d080502f",
  log: [{
    description: "test",
    duration: 60,
    date: "Mon Jan 01 1990",
  }]
}
```
````
test

**Comment by csmiceli** [comment]
I recently finished this cert. The Exercise Tracker was one I needed to reverse engineer to understand. Maybe that's a good thing? I found the data types and date formatting were particularly touchy yet never mentioned.

**Comment by moT01** [comment]
I am fine adding this if that is the consensus. But I wonder if it would be easier to just put something like, "Use the demo project to see example responses."

**Comment by nhcarrigan** [comment]
That would certainly be more maintainable - though reading the response from the example project isn't always clear without an extension to make the JSON "pretty".

**Comment by risaddex** [comment]
I would like to point on this, the user's stories say "similar with this" but in practice it actually needs to be DEEPLY equal (i needed to look into assertions from the project to check what I was missing - in this case, the date Format since my date constructor was getting my local date, which with the tests, makes the date 1990-01-01 become 1989-12-31 )

just specify that the date format is mandatory, please

sorry for my bad English, but I've ended up seeing more people passing for the same situation - specially with the possibly lack of information about assertions for people new to node :)

Keep doing the good job!

**Comment by raisedadead** [comment]
Hey @ShaunSHamilton how do we proceed with this?

**Comment by ShaunSHamilton** [comment]
@raisedadead I like Nicholas' suggestion, but would definitely want to add something like:
```
**Hint:** For the `date` property, the `toDateString` method of the `Date` API can be used to achieve the expected output.
```

In all fairness, the tests could be changed to accept any JS-approved date (we have done this with the Anonymous Message Board, IIRC). The above would definitely be the easiest, though.
