### ISSUE TITLE
Improve news performance to improve SEO

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#40408]
Google will include page experience signals  in Google Search ranking by May 2021.

As a result performance will be considered when ranking  pages.

We need to have the client optimized to ensure better ranking before the above-mentioned date. 

ref https://developers.google.com/search/blog/2020/11/timing-for-page-experience?hl=en

**Comment by ojeytonwilliams** [comment]
How is it doing at the moment?  We've got Lighthouse running on this repo, but we could do the same for /news.  Might be useful.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/101651765-45273b80-39f2-11eb-9e38-bdde986e92bd.png)

If I run lighthouse manually against our `/news` platform I receive these metrics.

**Comment by ojeytonwilliams** [comment]
Thanks Nick, looks like it's mostly images that're causing problems.  

Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/39043

**Comment by Twaha-Rahman** [comment]
> We've got Lighthouse running on this repo...

Currently, it's only configured to run on the landing page. Should we run it on all the pages?

**Comment by ojeytonwilliams** [comment]
All pages?  I think that would be a bit much, but extending it to cover key pages like /learn, /donate and one of each type of challenge (html, video, js and project) seems reasonable.

**Comment by Twaha-Rahman** [comment]
> EDIT: the 'collect' [config](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#collect) seems to control this

Well... the `collect` config won't work in this case because IIRC if you aren't signed in (by clicking the yellow button on the landing page), it just redirects you back to the landing page.

I think the best way to achieve running Lighthouse would be to use Cypress to visit the pages in question and run the Lighthouse plugin.

Lemme know what you think.

**Comment by ojeytonwilliams** [comment]
> Well... the `collect` config won't work in this case because IIRC if you aren't signed in (by clicking the yellow button on the landing page), it just redirects you back to the landing page.

The UX is slightly different if you're not signed in, but to my knowledge only /settings redirects you, so I think this is doable using `collect`.

> I think the best way to achieve running Lighthouse would be to use Cypress to visit the pages in question and run the Lighthouse plugin.

Would we be able to schedule it like we do currently?  It's quite nice to have the reports every couple of weeks.

**Comment by Twaha-Rahman** [comment]
> The UX is slightly different if you're not signed in, but to my knowledge only /settings redirects you, so I think this is doable using `collect`.

Oh... I didn't know that.

> Would we be able to schedule it like we do currently? It's quite nice to have the reports every couple of weeks.

Sure. That's easily possible. (Btw... you could even manually trigger it by going to the `Actions` page ;) )

**Comment by ojeytonwilliams** [comment]
Awesome, that's good to know.  I suggest we stick to the current setup for now, but keep in mind that we can use Cypress if needed.

It sounds to me like we have two items

- [ ] extend the existing site coverage to a better sample of pages
- [ ] set up a similar action for /news

Does that about cover it?

**Comment by Twaha-Rahman** [comment]
> Awesome, that's good to know. I suggest we stick to the current setup for now, but keep in mind that we can use Cypress if needed.
> 
> It sounds to me like we have two items
> 
> * [ ]  extend the existing site coverage to a better sample of pages
> * [ ]  set up a similar action for /news
> 
> Does that about cover it?

Yup.

**Comment by moT01** [comment]
This process is in place - probably good to close.
