### ISSUE TITLE
Revisiting CDN caching

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40418]
In https://github.com/freeCodeCamp/cdn/pull/57 we disabled caching for the CDN.  Since [Cloudflare respects Etags](https://support.cloudflare.com/hc/en-us/articles/218505467-Using-ETag-Headers-with-Cloudflare) and [Netlify uses them to bust caches](https://www.netlify.com/blog/2017/02/23/better-living-through-caching/) it should be possible to cache the assets in Cloudflare.

@raisedadead is this worth experimenting with?

**Comment by raisedadead** [comment]
> it should be possible to cache the assets in Cloudflare.

CloudFlare automatically does that - if Netlify sends such a header, which I believe it should at the minute. In short, I do not think there is a change necessary.

**Comment by ojeytonwilliams** [comment]
Doesn't look like it. Try this:

https://cdn.freecodecamp.org/project-data/readme.md

I see the headers

```
cache-control: no-store
cf-cache-status: DYNAMIC
```

and if it was cached I'd expect to see `cf-cache-status: HIT`.

**Comment by raisedadead** [comment]
Hmm, that is expected then. While we could use CF to cache, do we need to is the real question? Has there been a perf penalty that we have been having?

As I understand a CDN in front of a CDN (netlify) is a bad idea and given me a lot of headaches in the past.

**Comment by ojeytonwilliams** [comment]
> Has there been a perf penalty that we have been having?

It's probably not a huge deal, no. It's small enough that I can't see an obvious difference between cache hits and misses.

> As I understand a CDN in front of a CDN (netlify) is a bad idea and given me a lot of headaches in the past.

We do still cache everything in /news-assets/ though, so the headache potential is there.
