### ISSUE TITLE
Consider optimizing for Core Web Vitals

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#40419]
As stated in #40408 and #39354, **Core Web Vitals** or CWV, in short, will affect SEO soon and Google will keep adding and updating them in the future. So it's of utmost importance to optimize for these performance metrics. I've been investigating a little bit and it looks like that **First Contentful Paint (FCP)** and **Largest Contentful Paint (LCP)** are the main pain point. 

### Field Data

<details>
<summary>fCC's field CWV score (of last 28 days via "Chrome UX Report" or CrUX in short)</summary>

### Mobile Score

![image](https://user-images.githubusercontent.com/39026437/101890084-6fcbec80-3bca-11eb-8317-497b0a4f0555.png)

### Desktop Score

![image](https://user-images.githubusercontent.com/39026437/101890180-8ffbab80-3bca-11eb-91bb-9a2893752bc3.png)

</details>

### Lab Data

<details>

## LightHouse shows that the site has a poor performance score.

<summary>fCC's lab CWV score (of last LightHouse CI run on `master` branch)</summary>

![image](https://user-images.githubusercontent.com/39026437/101892920-3301f480-3bce-11eb-859e-ec0c5bf0fc6d.png)

</details>

### Monitoring and measuring performance metrics -

- [ ] Collect performance metrics from the field using the `web-vitals` npm package by Google
- [ ] Use CrUX and Search Console's `Web Vital` tab to see Google's view on site perf metrics

### Code fixes -

- [ ] Use modern image formats with proper size (using `srcset`) (This supports older browsers too) ([Useful link](https://www.youtube.com/watch?v=reztLS3vomE))
- [ ] Introduce Code splitting on a per-page basis ([Useful link](https://web.dev/code-splitting-suspense/))
- [ ] Cut down usage on third-party libraries or lazy load them
- [ ] Avoid serving legacy JavaScript to modern browsers (There's a babel preset for it... forgot the name)
- [ ] Pre-render routes ([Useful link](https://web.dev/prerender-with-react-snap/)) 
- [ ] Cache long-living immutable assets (fCC logo, fonts, Landing Page logos etc) etc...

Hope you guys find this report useful and lemme know if you guys would like to optimize for these things. I'd love to help as much as I can. 😃

**Comment by ahmadabdolsaheb** [comment]
Hey @Twaha-Rahman, we are working on improving the core web vitals and I am focused on code splitting at the moment.
There is a large 2MB chunk that is served on initial load that is causing some of the performance related issues. 

More information is posted here: https://github.com/freeCodeCamp/freeCodeCamp/issues/37742

Let me know if you are still interested in helping out with improving the metrics.

**Comment by Sembauke** [comment]
Hey @Twaha-Rahman,

Thanks for the thorough inspection of what we can do better.
At this time we are tracking most of the web optimizations in #37742.

This is the reason why I am closing this issue. You can always give tips for optimization in the issue I mentioned.

Thanks for your understanding,
Happy coding,
