### ISSUE TITLE
Quality Assurance Projects - Sudoku Solver clearer instructions on logic

### ISSUE THREAD

**Issue by darren-stoll** [freeCodeCamp/freeCodeCamp#40413]
**Describe your problem and how to reproduce it:**
There are two major questions I had while I was doing this project, and it seems like other people also had similar issues.

1.) (There's a similar issue to this already [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/40359), but this question deals with conflicting row/column/region.)

Q: Do we need to indicate if the value at a coordinate is conflicting with the final solution or with what is currently on the board? 

If something could indicate that you only need to figure out checkRow/Column/RegionPlacement in `sudoku-solver.js` with what is currently on the board rather than checking with the final solution, that would help immensely.

2.) Q: For the `solve()` method in `sudoku-solver.js`, does it need to check against solution logic provided elsewhere in the backend only on the test inputs, or do we need to provide the solve logic ourselves for ANY given puzzleString input? 

I received several conflicting answers when I asked on Discord, but I believe the right answer is that I need to provide the logic myself? Making this clearer on the /learn page by saying that we need to return the solved string with our own logic in `solve()` would be helpful.

These are probably not the clearest answers, but these were sufficient in helping me answer my questions that I had about this.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/sudoku-solver

**Comment by nhcarrigan** [comment]
> Do we need to indicate if the value at a coordinate is conflicting with the final solution or with what is currently on the board?

The `check` function should be validating against the *current* state of the board, not necessarily the final solution. Essentially, it is confirming that your number placement is valid when compared against the numbers currently present on the board.

Imagine implementing this as a sudoku helper - checking against the current state of the board would allow for things like highlighting numbers that conflict by row/column/region.

> For the solve() method in sudoku-solver.js, does it need to check against solution logic provided elsewhere in the backend only on the test inputs, or do we need to provide the solve logic ourselves for ANY given puzzleString input?

You *are* expected to write the logic (and related tests) to handle solving the sudoku puzzle based on the given input. I do agree that this is not explicitly spelled out on the `/learn` page and would be more than open to suggestions for clarifying this piece.

**Comment by darren-stoll** [comment]
Underneath "All puzzle logic can into `/controllers/sudoku-solver.js`", maybe add an indented bullet with this information:

- The `validate` function should take a given puzzle string and check it to see if it has 81 valid characters for the input.
- The `check` functions should be validating against the _current_ state of the board.
- The `solve` function should handle solving any given valid puzzle string, not just the test inputs and solutions. You are expected to write out the logic to solve this.

I still feel a bit iffy about my descriptions to add above (even though English is my native language, I'm not the best at clearly explaining things), and I have not submitted a pull request yet with the proposed changes. I'd like to discuss further to help make this clearer.

**Comment by nhcarrigan** [comment]
I think I am okay with this approach - I'll give others a chance to weigh in before opening this up. 🙂

**Comment by moT01** [comment]
I am fine with adding this as well.

**Comment by vicky11z** [comment]
Hi, I've opened my first PR in this repo for this issue. Please take a look when you have a chance!
