### ISSUE TITLE
Text in Basic Data Structures lesson can be better clarified.

### ISSUE THREAD

**Issue by MyNameIsAres** [freeCodeCamp/freeCodeCamp#40412]
**Describe your problem and how to reproduce it:**
The lesson Basic Data Structures: Add Items Using splice() has an introductory text which has an implication that allows for misinterpretation of the `splice()` function. We discussed this in the FCC Discord under the software development channel.

The text: "We then pass the following to splice(). The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the elements (13, 14) to be inserted at that same index" implies we insert two elements in the same index. This is (to my understanding) incorrect within the context of the given example. 

The text can be improved to clarify that we _**start**_ to insert the elements from that index. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/add-items-using-splice

My apologies if I glossed over something or misinterpreted what was written in the introduction text.

**Comment by RandellDawson** [comment]
@MyNameIsAres Just to clarify what you are wanting changed, can you post the full text you think better explains `splice`?

**Comment by GrumpyGusDev** [comment]
@MyNameIsAres I think I understand what you mean. 
We're inserting 2 new elements into the array, but not into a single index location. 
It's more a deletion of the element in index location 3 and replacing it with 2 new elements, the second element requiring an index location of it's own.
Did I get that correct? 
Good catch, btw! I can see that tripping up a lot of newbies. 
@RandellDawson is there a better way of stating that we aren't splicing (13, 14) into index location 3?

**Comment by moT01** [comment]
I think it's fairly clear when you look at the example. That being said, I don't mind a little improvement here. What about:

`We then pass the following to splice(). The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the remaining arguments (13, 14) will be inserted starting that same index`

**Comment by MyNameIsAres** [comment]
> I think it's fairly clear when you look at the example. That being said, I don't mind a little improvement here. What about:
> 
> `We then pass the following to splice(). The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the remaining arguments (13, 14) will be inserted starting at that same index.`

The example definitely is definitely correct. The text adds unnecessary confusion to the problem. Your improvement sounds great.

**Comment by MyNameIsAres** [comment]
> @MyNameIsAres Just to clarify what you are wanting changed, can you post the full text you think better explains `splice`?

I believe moT01's suggestion is a more accurate explanation of the method.

> @MyNameIsAres I think I understand what you mean.
> We're inserting 2 new elements into the array, but not into a single index location.
> It's more a deletion of the element in index location 3 and replacing it with 2 new elements, the second element requiring an index location of it's own.
> Did I get that correct?
> Good catch, btw! I can see that tripping up a lot of newbies.
> @RandellDawson is there a better way of stating that we aren't splicing (13, 14) into index location 3?

Correct!

**Comment by ieahleen** [comment]
> `We then pass the following to splice(). The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the remaining arguments (13, 14) will be inserted starting at that same index.`

as it seems this is the wanted text I'm opening this for first timers

**Comment by GJ-16** [comment]
Can I work on this?

**Comment by ieahleen** [comment]
@GJ-16 this is open for people doing their first contribution to the repo. Note that we don't assign issues, all issues with the "first timers only" or "help wanted" label are up for grubs, the first comprehensive PR submittef is reviewed.
If you haven't already, you can start reading contribute.freecodecamp.org, where also this is explained.
