### ISSUE TITLE
"Wrong answer" error in Jupyter cells lesson of Data Analysis with Python course

### ISSUE THREAD

**Issue by yaseen221** [freeCodeCamp/freeCodeCamp#40410]
The correct answer for the question: Which cells are responsible for rich display? is Markdown Cells.
But it erroneously accepts "Code Cells" as the correct answer.

To reproduce the bug, go to below link and select the correct answer to the question.

[link](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/jupyter-notebooks-cells)

![Screenshot 2020-12-09 164523](https://user-images.githubusercontent.com/25766559/101623113-f901e880-3a3d-11eb-8753-c9e0d17ff2f1.png)

**Comment by moT01** [comment]
From [https://readthedocs.org/projects/jupyter-notebook/downloads/pdf/latest/](https://readthedocs.org/projects/jupyter-notebook/downloads/pdf/latest/):

**Code cells:**
... The output is not limited to text, with many other possible forms of output are also possible, including matplotlib figures and HTML tables(as used, for example, in the pandas data analysis package). This is known as IPython’s **rich display** capability

**Markdown cells:**
You can document the computational process in a literate way, alternating descriptive text with code, using **rich text** ...

I watched the video at 2x and I didn't hear a mention of 'rich display' or 'rich text' - although, I may have just missed it.

By the definitions above, code cells sort of seems correct? but I am guessing that markdown has more capabilities for display - I'm not sure - and I'm not sure of the question creators intention here. The video does mention that markdown is used to make it look "pretty". Perhaps we could change the question to "What type of cells are used to make your reports look pretty?" and then use markdown as the answer.

**Comment by Sky020** [comment]
I am not a fan of this question at all. What about changing it to be:

> What are the three main types of Jupyter Notebook Cell?
```text
A - Code, MarkDown, and Python
B - Code, MarkDown, and Raw
C - MarkDown, Python, and Raw
```

**Comment by moT01** [comment]
I'm fine with that @Sky020. What do you think @yaseen221?

**Comment by nhcarrigan** [comment]
> But I think the correct answer to that question(rich text) should be Markdown Cells.

To clarify, the question asks about `rich display`, not `rich text`. Which, according to what Tom quoted, would be code cells. 

That being said, I completely agree that there's too much room for confusion here. For now, I suggest moving forward with @ShaunSHamilton's approach. Because this is a text change, I'll go ahead and open it up to first timers.

**Comment by therandomuserr** [comment]
Can I work on this? 
Since this is first time I'm contributing. Can you please help me?

Do I need to change the question and options like this?
> What are the three main types of Jupyter Notebook Cell?
```
A - Code, MarkDown, and Python
B - Code, MarkDown, and Raw
C - MarkDown, Python, and Raw
```

**Comment by ShaunSHamilton** [comment]
> Do I need to change the question and options like this?

@GJ-16 Yes, the questions here: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/jupyter-notebooks-cells.md

Need to be changed to the above. Be sure to read the [Contributors Docs](https://contribute.freecodecamp.org/#/), if you have not already 👍

**Comment by yaseen221** [comment]
I'm a first time contributor as well. Can I modify it please? @GJ-16

**Comment by GJ-16** [comment]
Actually i started. But if you want to, then go ahead ill look for something else. @yaseen221

**Comment by yaseen221** [comment]
Thanks a bunch mate @GJ-16
