### ISSUE TITLE
Just trying to understand how you check answers

### ISSUE THREAD

**Issue by misterybodon** [freeCodeCamp/freeCodeCamp#40416]
I'm reading mongoose guide, it would be nice to find where is the code checking the REPLs. 

All I find is `.md` files?

Say for mongoose & mongodb exercise 1, where is the checker code? 

Can I find it in the node modules too correct?

**Comment by ieahleen** [comment]
as this is not a bug report or a feature request, can you please ask about it on one of the chats in the #contributors channel or in the forum in the subforum of the same name?

the code snippets you see in the hints part of the .md files are those used for the various tests
