### ISSUE TITLE
Improve Lighthouse coverage

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40420]
As discussed in https://github.com/freeCodeCamp/freeCodeCamp/issues/40408 it would be helpful to have Lighthouse monitor more pages.  This breaks down into two broad cases

- [ ] extend the existing action to collect a better sample of pages: /, /learn, /donate and a sample of challenges (e.g. one from each of html, video, js, jsx and backend)
- [ ] set up a similar action for /news

**Comment by Sembauke** [comment]
As we decided to remove Lighthouse from action workflow #42027 there would be no need to keep this open.
