### ISSUE TITLE
Would like to see a progress gauge/bar for challenges.

### ISSUE THREAD

**Issue by Diacron** [freeCodeCamp/freeCodeCamp#40424]
I'm currently going though the Basic CSS challenges (as a guest, not logged in). It would be nice to see how many I've completed or how close I am to completing all of them.

**Describe the solution you'd like**
Perhaps a challenges completion status bar or gauge on the congratulatory screen.

**Comment by RandellDawson** [comment]
This feature is only available for registered users.  There are no current plans to add such a feature for guest users.

**Comment by raisedadead** [comment]
Hi @Diacron what Randell here means is that to implement such a feature we would need to store the data locally on the browsers, which can become stale over time. We recommend a login to consistently store the progress. 

We understand users may have reservations with this, and hence we do support using throw-away email addresses from mailinator, getnada, etc on our learning platform, if you do not want to use your own emails for some reason.
