### ISSUE TITLE
Break challenge instructions into paragraphs

### ISSUE THREAD

**Issue by nibble0101** [freeCodeCamp/freeCodeCamp#40425]
**Describe your problem and how to reproduce it:**

Currently the instruction for  "Data Structures: Create a Circular Queue" challenge is cramped up in one paragraph.

> In this challenge we will implement a circular queue. The circular queue should provide enqueue and dequeue methods which allow you to read from and write to the queue. The class itself should also accept an integer argument which you can use to specify the size of the queue when created. We've written the starting version of this class for you in the code editor. When you enqueue items to the queue, the write pointer should advance forward and loop back to the beginning once it reaches the end of the queue. Likewise, the read pointer should advance forward as you dequeue items. The write pointer should not be allowed to move past the read pointer (our class won't let you overwrite data you haven't read yet) and the read pointer should not be able to advance past data you have written. In addition, the enqueue method should return the item you enqueued if it is successful; otherwise it will return null. Similarly, when you dequeue an item, that item should be returned and if you cannot dequeue an item you should return null.

This makes it difficult to understand and keep track of the challenge requirements. It would be better to break the instructions down into paragraphs. Something like:

>  In this challenge we will implement a circular queue. The circular queue should provide enqueue and dequeue methods which allow you to read from and write to the queue. The class itself should also accept an integer argument which you can use to specify the size of the queue when created. We've written the starting version of this class for you in the code editor

 > When you enqueue items to the queue, the write pointer should advance forward and loop back to the beginning once it reaches the end of the queue. The enqueue method should return the item you enqueued if it is successful; otherwise it will return null.

> Likewise, the read pointer should advance forward as you dequeue items. When you dequeue an item, that item should be returned and if you cannot dequeue an item you should return null.

> The write pointer should not be allowed to move past the read pointer (our class won't let you overwrite data you haven't read yet) and the read pointer should not be able to advance past data you have written

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-circular-queue

**Tell us about your browser and operating system:**
* Browser Name: N/A
* Browser Version: N/A
* Operating System: N/A

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
This would be better 👍 Thanks, for taking the time to create this issue.

Seems like a nice _first timers only_ issue.

**Comment by get-thepacket** [comment]
I can't seem to find the code regarding this issue. It would be good to receive some hints.

**Comment by Sky020** [comment]
Hello @get-thepacket ,

Here are the [Contributors Docs](https://contribute.freecodecamp.org/#/index). I recommend you read those to see how to contribute, and get an idea of setup and formatting.

Here is the relevant file: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/10-coding-interview-prep/data-structures/create-a-circular-queue.md

If you have any further questions, feel free to create a topic on the [forum contributors channel](https://forum.freecodecamp.org/c/contributors/3). Or, reach out on the Contributors chat on [Discord](https://discord.com/invite/pFspAhS)

**Comment by get-thepacket** [comment]
@ShaunSHamilton Got it.

**Comment by get-thepacket** [comment]
I have done it with some bullets, looks fine.
![scrnli_12_13_2020_12-17-28 AM](https://user-images.githubusercontent.com/38386292/101992427-28805180-3cd9-11eb-8917-b977b954b801.png)

**Comment by get-thepacket** [comment]
So just paragraph change, ok.
