### ISSUE TITLE
Seeded users share an email

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40421]
In [the scripts to seed the database](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/tools/scripts/seed), the auth user and certified user share an email address. I had them both seeded and could not change any of the settings for the development user - you get an "email uniqueness" error.

One of the email addresses could probably be changed in there.

Edit: On second thought, I bet this is by design so you can log in with either user in development. I'll leave this open for a bit though. Perhaps those scripts could delete the maybe existing user with the same email before seeding.

**Comment by Sky020** [comment]
The email addresses were purposefully set to be the same, because the dev sign-in relies on the email address. So, if `fullyCertifiedUser` was given a different email address, then it would not be possible to sign in as them.

**Comment by moT01** [comment]
I think we should delete the other users before seeding the certified user and vice versa - something like this maybe...

```
if (seeding cert user)
  delete(certuser, devuser, blankuser)
  insert(certuser, blankuser)
else 
  delete(certuser, devuser, blankuser)
  insert(devuser, blankuser)
```

**Comment by ojeytonwilliams** [comment]
> To add: I hardly delved in the mock auth user process. So, if someone can find a better way to sign in, that would be better.

Your approach was fine, I don't think we need to come up with anything fancy.  I do like Tom's suggestion, too.  What do you think, Shaun?

**Comment by Sky020** [comment]
> What do you think, Shaun?

Tom's suggestion makes sense 👍 .
