### ISSUE TITLE
Low contrast on Code Selection: Can't See Anything

### ISSUE THREAD

**Issue by paulsonjpaul** [freeCodeCamp/freeCodeCamp#40442]
**Describe your problem and how to reproduce it:**

I had started noticing this a few days ago onward. The issue is that I can't see the code example when I highlight it. It has low contrast. The issue is similar to #39967. The surprising thing is that the highlight color is different in Chrome and FireFox Developer Edition.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

The problem is in every challenges.

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome & FireFox Developer Edition
* Browser Version: Version 87.0.4280.88 (Official Build) (64-bit) (Chrome) & Version 84.0b8 (64-bit) (FireFox)
* Operating System: Windows 10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/73777251/102005706-f73b6c00-3d40-11eb-93c7-a1970022a05c.png)

The left is in Chrome & right is in FireFox.

**Comment by ojeytonwilliams** [comment]
Thanks for the report @paulsonjpaul, this definitely isn't what we want.  However, the colour can be controlled via the `::selection` selector, so this is definitely fixable.  

@ahmadabdolsaheb do you want to take a look or can we open this up to contributors?

**Comment by paulsonjpaul** [comment]
If you don't mind, can I open a PR for this? All I want would be contributing docs and the location of the file to edit.

**Comment by paulsonjpaul** [comment]
I noticed that there is a Code Freeze currently. So, is this not the correct time to create a PR? Thanks.

**Comment by RandellDawson** [comment]
@paulsonjpaul You can always create a PR.  The code freeze only impacts the merging of the PR right now.  Go ahead and create one if you want and we will review and merge when the freeze is over.

**Comment by paulsonjpaul** [comment]
Thank you @RandellDawson for your clarification. But, I don't know the location of the file to edit. Also, I noticed that this is a problem with dark mode only. For light mode, the selection color works perfectly and has correct contrast. So, I think we should change the selection color for the dark mode only.

Please give me the location of the file to edit. Thanks.

**Comment by ojeytonwilliams** [comment]
@paulsonjpaul the contribution guide is [here](https://contribute.freecodecamp.org/).  I would recommend putting it in `client/src/components/layouts/global.css` unless you're only changing the selection colour on specific pages.  Finally, we apply night mode styles via the `.night` class.

**Comment by paulsonjpaul** [comment]
I am really sorry to irritate you again. I checked the file you suggested, but I couldn't find any `::selection` and any `.night` selectors.

But, I found the `.night` selector in `prism-night.css` file. But, no `::selection` there 😢.

So, which is the exact file to edit and which line should I edit. Sorry again, I am a complete noob at this. It's really hard to find something in a big project's files like this.

**Comment by ojeytonwilliams** [comment]
It's no trouble at all.  

Those selectors don't exist, yet, you'd need to add them.  Once you do the site should automatically reload when you save the css file.  Then it's just a case of making sure they look okay and have high enough contrast.

**Comment by paulsonjpaul** [comment]
I setup freecodecamp in gitpod and I can see the preview. But, to enable dark mode, I have to login into freecodecamp from gitpod's preview. But I am afraid whether it is safe to do so. Please guide me.

**Comment by paulsonjpaul** [comment]
To get a correct color that has enough contrast, I experimented with different colors using the browser's built-in inspect tool. Here is something that I found works best with both light and night mode:

![image](https://user-images.githubusercontent.com/73777251/102174599-e23b1600-3ec3-11eb-9cac-a5430e7af33e.png)

![image](https://user-images.githubusercontent.com/73777251/102174746-24fcee00-3ec4-11eb-9f71-14922b6f45c1.png)

Please check if this color is good enough.

**Comment by paulsonjpaul** [comment]
I also noticed that this problem persists in HTML & CSS challenges as well, which should have been fixed in #39967 (but not). But, I will fix it in this PR (I have found a solution for it).

**Comment by RandellDawson** [comment]
@paulsonjpaul I think you meant it should have been fixed by PR https://github.com/freeCodeCamp/freeCodeCamp/pull/39987?

**Comment by paulsonjpaul** [comment]
> 
> 
> @paulsonjpaul I think you meant it should have been fixed by PR #39987?

Yes @RandellDawson. That PR was meant to fix this issue, but it is now back again. But, I will fix it.

> I setup freecodecamp in gitpod and I can see the preview. But, to enable dark mode (for testing if the color works in both modes), I have to login into freecodecamp from gitpod's preview. But I am afraid whether it is safe to do so. Please guide me.

Can you please provide an answer to this? Also, please see my reply above (the one with screenshots) and check if the color is fine.

**Comment by ShaunSHamilton** [comment]
@paulsonjpaul It might be easier for you to get this kind of assistance on either the forum  (in the Contributors sub-forum), or on the Discord server (contributors channel). Links in docs

To sum up, it is mostly explained in the [docs](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=sign-in-with-a-local-user)
But, you are not supposed to sign in with your account. In fact, you cannot. If your setup has gone well, you should _technically_ already be signed in. Although, you will still see the _SIGN IN_ buttons in development.

Hope this clarifies

**Comment by ojeytonwilliams** [comment]
Thanks Shaun, that's exactly what I was going to say.

As far as contrast goes, I recommend making use of a tool to check it complies with the [WCAG guidelines](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).  For example https://wave.webaim.org/

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams, I think a contributor can open a pr and we could adjust it before merge.
In addition to the resources that @ojeytonwilliams has listed, I encourage you anyone who is interested to do a research on the accepted contrast level for selected text, and see the contrast levels adopted by websites with best accessibility practices. 

Here is the contrast checker that I usually use:https://webaim.org/resources/contrastchecker/

**Comment by paulsonjpaul** [comment]
I have made a PR for this issue. Please check it #40461

**Comment by paulsonjpaul** [comment]
Please check my comment in #40461. The issue still persists.
