### ISSUE TITLE
Waypoint: Trigger Click Events With jQuery -- fuzzy wording

### ISSUE THREAD

**Issue by StevePaytosh** [FreeCodeCamp/FreeCodeCamp#4045]
I noticed some of the wording for this waypoint is a bit confusing.
The Issue lies with the following paragraph:

   Let's make our "Get Message" button change the text of the element with the class message.

The request is to modify a button with the id "getMessage" as opposed to a class "message". The wording might also cause somebody to think there is some css involved with the code (i.e. they are expected to change the button text with a css class). There are also elements in the code with the class "message" in it.

**Comment by bugron** [comment]
@StevePaytosh thanks for posting this issue!
Bind the click event to the button with the ID of getMessage and make our "Get Message" button (which is the button with the ID of getMessage) change the text of the element with the class message.
Which means clicking the button with ID getMessage should change the text of the `div` with class message.
Closing this issue. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
