### ISSUE TITLE
Add a two-pane view with a keyboard shortcut to switch back and forth

### ISSUE THREAD

**Issue by adql** [freeCodeCamp/freeCodeCamp#40454]
**Is your feature request related to a problem? Please describe.**
When working on a three-paned challenge (e.g. lessons of the Responsive Web Design certificate and probably many others), especially on smaller screens the code pane in the middle is just too narrow. Line wrapping is happening way too often, which reduces usability. Manually resizing the panes each lesson is cumbersome. Using `Ctrl--` to reduce font size results in a font too small for some people, especially in the text pane.

**Describe the solution you'd like**
Add a keyboard shortcut to quickly switch between 3- and 2-pane view, where the latter will display two even sized panes of code and preview

**Describe alternatives you've considered**
Remembering pane ratio across lessons is partially helpful but the text pane should anyway be wide when reading it (especially because of code blocks).

**Additional context**
As a bonus, the preview pane becomes much wider with one shortcut.

**Comment by moT01** [comment]
There's a few things you can possibly do to help with this for the time being @adql. If you make your window a little smaller, the view does change to where each pane takes up the whole screen, and you can switch between them with tabs. Although, you can't do that on a phone. I'm curious what device you are using? You can stop the text from wrapping with `ctrl/cmd + f1` - not sure if you can do that on a phone either. But `f1` brings up a menu, and then there's a `Toggle Accessibility Mode` option to accomplish the same thing.

I like the idea of remember the pane size across challenges.

I believe our future editor will have all the instructions embedded within the code, so there will be one less pane to deal with.

As a quick fix, we could possible change the width at which the view changes from panes to tabs so it's a little sooner (bigger).

**Comment by adql** [comment]
I'm using a laptop with a 14" HD monitor. Do people actually use the phone to study coding? It would be interesting to see statistics...

These tips are really useful! It's especially helpful knowing about the `f1` menu that includes not only accessibility and usability options but also keyboard shortcuts. I think it would be a good idea to inform the user about this menu at least at the first time of visiting the study interface (I don't remember such guidance, excuse me if I'm wrong).

**Comment by ojeytonwilliams** [comment]
Since https://github.com/freeCodeCamp/freeCodeCamp/pull/42519 means that any resizing you do will be persisted between challenges and reloads, I think this problem is mitigated somewhat.
