### ISSUE TITLE
Lesson will not allow to progress after it is completed

### ISSUE THREAD

**Issue by aligolji** [freeCodeCamp/freeCodeCamp#40459]
I've completed the lesson correctly and it will not allow me to move on.
I read a couple of older threads regarding the same issue and I tried all of the suggested work-arounds. As this issue happened on the lesson just before this one, it worked. However, on this lesson none of the suggested solutions are working.

tried double clicking, ctrl+enter twice, changing the color to blue, to blue then back red, refreshing the page and trying all of the above, tried on firefox and chrome (currently using chrome). Reset the code and attempted all again.

Nothing worked.

Please help so I can move on. Thanks!!

This is the lesson I'm stuck on: -------------

Basic CSS: Use a CSS Class to Style an Element
Classes are reusable styles that can be added to HTML elements.

Here's an example CSS class declaration:

<style>
  .blue-text {
    color: blue;
  }
</style>
You can see that we've created a CSS class called blue-text within the <style> tag. You can apply a class to an HTML element like this: <h2 class="blue-text">CatPhotoApp</h2> Note that in your CSS style element, class names start with a period. In your HTML elements' class attribute, the class name does not include the period.

Inside your style element, change the h2 selector to .red-text and update the color's value from blue to red.

Give your h2 element the class attribute with a value of 'red-text'.
-------------------------------------

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
