### ISSUE TITLE
Your example code is wrong

### ISSUE THREAD

**Issue by joeneuman** [FreeCodeCamp/FreeCodeCamp#4046]
var ourArray = [];
for(var i = 1; i < 10; i += 2){  // this line needs to read:  for(var i = 0;
ourArray.push(i);                  // if you want ourArray to contain [0,2,4,6,8]     
}
var myArray = [];

**Comment by terakilobyte** [comment]
Could you specify what this is linked to?

**Comment by joeneuman** [comment]
http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops
The description was changed to support the code. The original description stated the results for the example code would produce [0,2,4,6,8].  It makes more sense that way as otherwise the student is just retyping the exact same code.

**Comment by awesomeaniruddh** [comment]
The example code you mentioned is not there in the challenge, so I'm not sure what that is about. The second issue you raised, that the user is simply retyping existing code is valid.

Thanks for reporting this @joeneuman!

**Comment by joeneuman** [comment]
Yes the example code is there. Just as stated. 
var ourArray = [];

for(var i = 0; i < 5; i++){
  ourArray.push(i);
}

var myArray = [];

// Only change code below this line.

**Comment by awesomeaniruddh** [comment]
```js
var ourArray = [];
for(var i = 1; i < 10; i += 2){ // this line needs to read: for(var i = 0;
ourArray.push(i); // if you want ourArray to contain [0,2,4,6,8]

}
var myArray = [];
```
is not there though?

**Comment by joeneuman** [comment]
The only thing added were my comments?

**Comment by joeneuman** [comment]
OH I see, I fixed the code then said the change it. 
The code needs to read:

for(var i = 1;

 if you want ourArray to contain [0,2,4,6,8]

**Comment by ltegman** [comment]
@joeneuman It looks like you may have linked to the wrong waypoint, because you're saying there's a problem with a waypoint that contains a loop like `for(var i = 1; i < 10; i += 2)` but the waypoint you linked to has a loop like `for(var i = 0; i < 5; i++)`
