### ISSUE TITLE
there is a spelling error in this lesson "Count Backwards With a For Loop"

### ISSUE THREAD

**Issue by najmieh** [freeCodeCamp/freeCodeCamp#40470]
**Describe your problem and how to reproduce it:**
here in this lesson we this explanation: In order to count backwards by twos, we'll need to change our initialization, condition, and final-expression.
 backwards should change into backward and twos should change into two. 

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/count-backwards-with-a-for-loop

**Tell us about your browser and operating system:**
* Browser Name: chrome 
* Browser Version: 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by najmieh** [comment]
also, this lesson needs an edit https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/replace-loops-using-recursion


Note: Recursive functions must have a base case when they return without calling the function again (in this example, when n <= 0), otherwise they can never finish executing.


when n <= 0 has one parentheses

**Comment by nhcarrigan** [comment]
> Note: Recursive functions must have a base case when they return without calling the function again (in this example, when n <= 0), otherwise they can never finish executing.

I'm not seeing an issue here? The parentheses wrap the subclause "in this example, when n <= 0".

**Comment by nhcarrigan** [comment]
> backwards should change into backward and twos should change into two. 

This would be a good change, though, I agree.

**Comment by ieahleen** [comment]
> backwards should change into backward and twos should change into two.

agree with this change - I'm opening this as first timers only

**Comment by matias-miller** [comment]
I am interested in contributing. I have never made a contribution to an open source project. If I could get a little help, this would be a great learning experience.

**Comment by ieahleen** [comment]
@matias-miller if you haven't, start with contribte.freecodecamp.org, then you can ask for help on discord, in the contributors channel. Here to join: https://www.freecodecamp.org/news/freecodecamp-discord-chat-room-server/ , or on the forum in the contributors subforum

**Comment by CreaTorAleXander** [comment]
@matias-miller are you doing this issue or is it free?

**Comment by ieahleen** [comment]
@CreaTorAleXander @matias-miller  all issues with the "first timers only" or "help wanted" are up for grabs, the first comprehensive PR is reviewed

**Comment by matias-miller** [comment]
I believe I fixed it. Let me know if there is anything I missed.
![image](https://user-images.githubusercontent.com/45863274/102565250-b1fd9e00-40a2-11eb-9752-f4636aa51753.png)
