### ISSUE TITLE
Title Case: My function works but still not passing me. 

### ISSUE THREAD

**Issue by tbraden30** [FreeCodeCamp/FreeCodeCamp#4047]
I hate doing a bug report but i'm at my wits end. My code works but its saying that it doesn't.
Thank you kindly, 

![titlecase](https://cloud.githubusercontent.com/assets/15311351/10861739/85696956-7f59-11e5-891e-0fba29a5a5de.jpg)

Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0Astr%20%3D%20str.toLowerCase().split(%2F%5CW%2Fg)%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20str%5Bi%5D%20%3D%20str%5Bi%5D.charAt(0).toUpperCase()%20%2B%20str%5Bi%5D.slice(1)%20%2B%22%20%22%3B%0A%20%20%7D%0A%20%20return%20str.join('%20')%3B%0A%7D%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
str = str.toLowerCase().split(/\W/g);
  for (i = 0; i < str.length; i++) {
    str[i] = str[i].charAt(0).toUpperCase() + str[i].slice(1) +" ";
  }
  return str.join(' ');
}
titleCase("sHoRt AnD sToUt");

```

**Comment by ltegman** [comment]
Your code is adding in extra spaces after each word. `titleCase("sHoRt AnD sToUt");` should return `"Short And Stout"` but your code returns `"Short  And  Stout "`.

Closing as not an issue with the test. Please use https://gitter.im/FreeCodeCamp/HelpBonfires for help with bonfire solutions.

Thanks and happy coding!

**Comment by tbraden30** [comment]
how do i fix it

**Comment by ltegman** [comment]
Github issues are not for answer help. Please visit our gitter channels https://gitter.im/FreeCodeCamp/Help and https://gitter.im/FreeCodeCamp/HelpBonfires for assistance.
