### ISSUE TITLE
Remove the change code below/above line instructions for Redux challenge:Use const for Action Types

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#40489]
**Describe your problem and how to reproduce it:**
Hi there! 
This challenge asks users to declare two variables with const and then edit the `authReducer()` function and action creators. 
The `//change code below/above line` instructions imply that your code should only be between those two lines. 
However, in order to pass the challenge, you have to edit the code below the `// Change code above this line`.
I think it would be best to remove those comments. 

Thanks! 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/redux/use-const-for-action-types

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="530" alt="Screen Shot 2020-12-18 at 4 34 39 PM" src="https://user-images.githubusercontent.com/67210629/102675627-fc3c5900-414e-11eb-9b44-15473306658b.png">

**Comment by GJ-16** [comment]
Actually the Problem states

>Declare LOGIN and LOGOUT as const values and assign them to the strings 'LOGIN' and 'LOGOUT', respectively.

Which is why these two comments are given at the first place
```
// Change code below this line

// Change code above this line
```
I don't think it is good idea to remove these comments.
And yes the changes has to be made below the  __*```Change code above this line```*__ as well. 
>Then, edit the authReducer() and the action creators to reference these constants instead of string values.
So, for this, may be i think some extra comments can be given. My suggestion would be this, please wait for the confirmation.

**Comment by jdwilkin4** [comment]
Hi @GJ-16 ! 

Whenever we see these lines, it has always been in the context of only place your code in here. 
```
// Change code below this line

// Change code above this line
```

Examples: 
https://www.freecodecamp.org/learn/responsive-web-design/css-grid/create-flexible-layouts-using-auto-fill
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/combine-two-arrays-using-the-concat-method

I get that they want users to declare their variables at the top of the page.  
IMO users probably don't need to be told that because they would probably already do that anyway by this point in the curriculum. 

But, I could be totally wrong and the moderators might think it is a dumb idea to change it, which is fine.

**Comment by GJ-16** [comment]
Rather we could do something like this:
>  // Change code in this line

Near the particular line inside ```authReducer()``` and ```action creators``` which needs to be changed.

**Comment by RandellDawson** [comment]
@GJ-16 We are not planning on adding any more comments to the current curriculum.  We have a specific set of comments located in [/curriculum/dictionaries/english/comments.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/dictionaries/english/comments.js) that we want to stick to at the current time.

We have three specific sets comments we use related to where to put code:

```
// Only change code below this line

// Only change code above this line
```
and
```
// Change code below this line

// Change code above this line
```
and
```
// Change this line
```
My recommendation is to leave the existing comments at the top and add `Change this line` on the `case `'LOGIN':` and `case 'LOGOUT':` lines.

**Comment by nhcarrigan** [comment]
>My recommendation is to leave the existing comments at the top and add Change this line on the case 'LOGIN': and case 'LOGOUT': lines.

I think that's a good approach.

**Comment by GJ-16** [comment]
@RandellDawson I was suggesting the same and Sorry I didn't check this ```/curriculum/dictionaries/english/comments.js``` 

> My recommendation is to leave the existing comments at the top and add `Change this line` on the `case 'LOGIN':` and `case 'LOGOUT':` lines.

Yes, this would be fine.

**Comment by RandellDawson** [comment]
Since this is a fairly simple fix, I have open this PR up to first timers only.

**Comment by jdwilkin4** [comment]
Thank you for taking the time to listen to my suggestions!

**Comment by NirajNair** [comment]
Is it okay if I go ahead with this issue?

**Comment by ShaunSHamilton** [comment]
@NirajNair 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by AlcidesGome** [comment]
I don't think its a good idea to remove the comments. It is just asking to add the code in between the above and below comment. And declare login & logout. Also the authReducer()

**Comment by jdwilkin4** [comment]
Hi @AlcidesGome! 

Yes, I realize that now. There is already a pull request with the new changes.

**Comment by martinmilani** [comment]
> 
> 
> @GJ-16 We are not planning on adding any more comments to the current curriculum. We have a specific set of comments located in [/curriculum/dictionaries/english/comments.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/dictionaries/english/comments.js) that we want to stick to at the current time.
> 
> We have three specific sets comments we use related to where to put code:
> 
> ```
> // Only change code below this line
> 
> // Only change code above this line
> ```
> 
> and
> 
> ```
> // Change code below this line
> 
> // Change code above this line
> ```
> 
> and
> 
> ```
> // Change this line
> ```
> 
> My recommendation is to leave the existing comments at the top and add `Change this line` on the `case 'LOGIN':` and `case 'LOGOUT':` lines.

I agree.
This same scenario happens in other challenges also
