### ISSUE TITLE
Chinese challenges (APIs and Microservices) needing an audit for English changes from Dec, 1, 2019

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#40483]
@freeCodeCamp/chinese 

In preparation of the upcoming launch of the Chinese curriculum, the following Chinese curriculum challenges need to be compared to their English equivalents.

This issue only covers challenges in the **`APIs and Microservices`** certification.

All the challenges below have Description or Instructions sections with changes to the English version since Dec 1, 2019. Also includes any challenges with Tests where at least one test's text has changed in the English version since Dec 1, 2019 or where the number of tests in the current English version is different than the number of tests in the current Chinese version.

Please create any necessary PRs to bring the Chinese challenge listed below in sync with the English version.  

**NOTES:**
- Some changes are not translation related (like addition of code examples or addition/removal of code tags (single back ticks).  These changes are still needed to bring make the challenge more like the English version.
- There are two links to the right of the challenge title (one allows you directly link to the editable Chinese version of the file on GitHub and the other links to the raw English version.  You can right-click and open the links in new tabs to keep this issue in the background.
---
- [ ] **Use model.find() to Search Your Database** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/use-model.find-to-search-your-database.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/use-model.find-to-search-your-database.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Use model.findOne() to Return a Single Matching Document from Your Database** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/use-model.findone-to-return-a-single-matching-document-from-your-database.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/use-model.findone-to-return-a-single-matching-document-from-your-database.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Create Many Records with model.create()** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model.create.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model.create.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Create a Model** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/create-a-model.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/create-a-model.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Chain Search Query Helpers to Narrow Search Results** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/chain-search-query-helpers-to-narrow-search-results.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/chain-search-query-helpers-to-narrow-search-results.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Install and Set Up Mongoose** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Perform Classic Updates by Running Find, Edit, then Save** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/perform-classic-updates-by-running-find-edit-then-save.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/perform-classic-updates-by-running-find-edit-then-save.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Perform New Updates on a Document Using model.findOneAndUpdate()** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/perform-new-updates-on-a-document-using-model.findoneandupdate.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/perform-new-updates-on-a-document-using-model.findoneandupdate.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Create and Save a Record of a Model** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/create-and-save-a-record-of-a-model.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/create-and-save-a-record-of-a-model.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Delete Many Documents with model.remove()** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/delete-many-documents-with-model.remove.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/delete-many-documents-with-model.remove.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **Number of tests do not match - English: 1 | Chinese: 2**
**Instructions:** Add or delete the applicable tests.  It is possible some tests have been rearranged, so make sure each English test has a corresponding Chinese test in the same order

</details>

---
- [ ] **Delete One Document Using model.findByIdAndRemove** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/delete-one-document-using-model.findbyidandremove.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/delete-one-document-using-model.findbyidandremove.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Use model.findById() to Search Your Database By _id** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/mongodb-and-mongoose/use-model.findbyid-to-search-your-database-by-id.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/use-model.findbyid-to-search-your-database-by-id.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Timestamp Microservice** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **Number of tests do not match - English: 8 | Chinese: 6**
**Instructions:** Add or delete the applicable tests.  It is possible some tests have been rearranged, so make sure each English test has a corresponding Chinese test in the same order

</details>

---
- [ ] **Request Header Parser Microservice** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/apis-and-microservices-projects/request-header-parser-microservice.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/request-header-parser-microservice.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **Number of tests do not match - English: 4 | Chinese: 3**
**Instructions:** Add or delete the applicable tests.  It is possible some tests have been rearranged, so make sure each English test has a corresponding Chinese test in the same order

</details>

---
- [ ] **File Metadata Microservice** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **Number of tests do not match - English: 4 | Chinese: 2**
**Instructions:** Add or delete the applicable tests.  It is possible some tests have been rearranged, so make sure each English test has a corresponding Chinese test in the same order

</details>

---
- [ ] **Exercise Tracker** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **Number of tests do not match - English: 7 | Chinese: 6**
**Instructions:** Add or delete the applicable tests.  It is possible some tests have been rearranged, so make sure each English test has a corresponding Chinese test in the same order

</details>

---
- [ ] **URL Shortener Microservice** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **Number of tests do not match - English: 4 | Chinese: 3**
**Instructions:** Add or delete the applicable tests.  It is possible some tests have been rearranged, so make sure each English test has a corresponding Chinese test in the same order

</details>

---
- [ ] **Meet the Node console** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/basic-node-and-express/meet-the-node-console.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/basic-node-and-express/meet-the-node-console.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Get Query Parameter Input from the Client** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/basic-node-and-express/get-query-parameter-input-from-the-client.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/basic-node-and-express/get-query-parameter-input-from-the-client.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test(s) `text` do not match:**
**Instructions:** Make sure to also check that the English tests have not been reorderd.
**Test 2**
    <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

```
  Test 2 : Your APi endpoint should respond with the correct name
```
  </td>
  </tr>
  <td>New</td>
  <td>

```
  Test 2 : Your API endpoint should respond with the correct name

```
  </td>
  </tr>
  </table>

</details>

---
- [ ] **Start a Working Express Server** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/basic-node-and-express/start-a-working-express-server.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/basic-node-and-express/start-a-working-express-server.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**

</details>

---
- [ ] **Use body-parser to Parse POST Requests** [Edit Chinese](https://github.com/freeCodeCamp/freeCodeCamp/edit/master/curriculum/challenges/chinese/05-apis-and-microservices/basic-node-and-express/use-body-parser-to-parse-post-requests.md) | [View English](https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/05-apis-and-microservices/basic-node-and-express/use-body-parser-to-parse-post-requests.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

**Comment by sidram05** [comment]
Hi @RandellDawson  can I work on this one ?

**Comment by stevending1st** [comment]
I am working for this part.

**Comment by RandellDawson** [comment]
@raisedadead I think we can close this issue now that all the translations are performed on Crowdin and we have the various QA checks in place to warn about code block differences and other changes that occur in the English source for these files.  The original intent of the issue was to have PRs created to fix any discrepancies.  Some were created before we started really using Crowdin, but none are made now outside of Crowdin.
