### ISSUE TITLE
Recursive factorialize gets correct answer but test does not indicate passing

### ISSUE THREAD

**Issue by dcc1079** [FreeCodeCamp/FreeCodeCamp#4051]
Challenge [Bonfire: Factorialize a Number](http://freecodecamp.com/challenges/bonfire-factorialize-a-number#?solution=function%20factorialize(num)%20%7B%0A%20%20if%20(num%20%3C%202)%20%7B%0A%20%20%20%20return%20num%3B%0A%20%20%7D%0A%20%20return%20num%20*%20factorialize(num%20-%201)%3B%0A%7D%0A%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function factorialize(num) {
  if (num < 2) {
    return num;
  }
  return num * factorialize(num - 1);
}

factorialize(5);

```
This shows the right answer in the output bar (below Reset Help Bug), but no congratulatory popup appears.  I ran this outside of the FCC automation and it gets the right answer there also, even with repeated invocations.

Is the automation rejecting recursion on principle?

I redid this as an iterative solution and that was accepted.

**Comment by ltegman** [comment]
Take a look at the test case you're failing, `factorialize(0)`. It wants you to be returning 1, but what does your code return in this case?

Closing as not an issue with the tests, but feel free to reply if you need further clarification. 

Thanks and happy coding!

**Comment by dcc1079** [comment]
Hey, thanks for the quick reply! I guess I  need to review the edge cases for the factorial function.
