### ISSUE TITLE
Your code should not have any div tags.

### ISSUE THREAD

**Issue by tyantrinh** [freeCodeCamp/freeCodeCamp#40515]
**Describe your problem and how to reproduce it:**
I am on the applied accessibility section for responsive web design, and the instructions for this problem and the problem after ask me to change the div tags. I change it to article for the problem I have linked and I'm still getting the "Your code should not have any dig tags" even though the other requirement is having 3 article tags which I do. I am also sure I deleted all div tags.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/wrap-content-in-the-article-element

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 87.0.4280.88
* Operating System: Windows 10 Pro 2004 OS Build 19041.685

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@tyantrinh Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in the challenges and projects.

Thank you for understanding.
