### ISSUE TITLE
Corrections to the article "10 JavaScript Hacks Every Web Developer Should Know"

### ISSUE THREAD

**Issue by dym-sh** [freeCodeCamp/freeCodeCamp#40527]
several corrections to the article at https://www.freecodecamp.org/news/javascript-hacks/

x-post from [FCC forum](https://forum.freecodecamp.org/t/corrections-to-the-article-10-javascript-hacks-every-web-developer-should-know/436875), as per [support-reply](https://forum.freecodecamp.org/t/corrections-to-the-article-10-javascript-hacks-every-web-developer-should-know/436875/3)

### 1.
> `math.round(math.random*50)`
```
Uncaught ReferenceError: math is not defined
```
the keyword is `Math`, first letter is upper-cased
and its method is `.random()`, with brackets at the end

### 2.

equating `Math.round` to `~~`
```
// instead of
math.round(math.random*50)
// use
~~(math.random*50)
```

`~~` acts the same as `Math.floor`, since its "~" twice – bitwise inversion two times, decimal part just falls off, as it can only be apllied to integer numbers, and floats are converted on first inversion

### 3. 
> You can also use `filter()` together with `Boolean` to return all null or undefined values from your array.

no, its literally the opposite. only truthy elements will be returned.

![37e0b8d1818dc81862515c9ae0ea6d7dd62bc058](https://user-images.githubusercontent.com/59403389/103020088-28d5e380-4548-11eb-90dd-80f009eb5ada.png)

**Comment by nhcarrigan** [comment]
Thank you for bringing this to our attention! We have notified the editorial team to look in to this issue. 🙂

**Comment by ishansinghal9810** [comment]
Any Help from my side ?

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo I just updated the `Math.random()` part of this article, but the entire `filter` section is just poorly written from the start.  There is no mention that the `filter` method's callback needs to return `true` for the elements that are to be kept.  Also, as @dym-sh first reported, the following sentence is just wrong.
> You can also use `filter()` together with `Boolean` to return all null or undefined values from your array.

What do we do in situations like this?  Do you have the author resubmit a corrected article or do you try to rewrite the article for them?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for taking a look and fixing part of the article, @RandellDawson.

I think in cases like this it's better to reach out to the original author to fix all these issues. If they can't update the article for some reason, then we can look at rewriting it or redirecting traffic to a different article.

**Comment by AbbeyRenn** [comment]
Thank you @dym-sh @RandellDawson @scissorsneedfoodtoo I've emailed the author so he can make the remaining corrections 👍

**Comment by scissorsneedfoodtoo** [comment]
The author made some updates and I worked on some additional formatting and wording issues.

Thanks for reporting this @dym-sh. Please let us know if you notice anything else in this or other articles.
