### ISSUE TITLE
Change example for Basic HTML and HTML5: Create a Form Element

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#40523]
Hi there! I would like to discuss a change to the example given in the create a form element challenge. This trips up a lot of people and is always brought up in the forum. 

https://forum.freecodecamp.org/search?q=create%20a%20form%20element%20after%3A2020-12-01

I think a small change to the example would help a lot of people. 

**Describe your problem and how to reproduce it:**
Existing example: `<form action="/url-where-you-want-to-submit-form-data"></form>`
Possible change: `<form action="https://submit-form-data.com"><input></form>`

Using https:// at the beginning of the action will hopefully get people to correctly use the url provided. Placing the input inside the form will hopefully fix the confusion around nesting. 

I think a lot of beginners look to the examples to help them with the challenges. So I think making these changes should help. While it might look like we are giving them the answer with this proposed change, there have been previous html challenges where the example was basically the answer. 

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements
 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by manuelczs** [comment]
your proposal is valid, I support it!

**Comment by nhcarrigan** [comment]
`<form action="/url-where-you-want-to-submit-form-data">`

My only concern about changing this is that *this is a common syntax* when you are building a full-stack application.

Often times, you'll have your `form` element send a `post` request to a specific endpoint on your server, which means instead of writing the full link you use `/login` (as an example).

**Comment by jdwilkin4** [comment]
Can we do a combination of keeping the opening tag the way it is and adding the input tag to the example? 
`<form action="/url-where-you-want-to-submit-form-data"><input></form>`

**Comment by nhcarrigan** [comment]
Yes, I think showing the nested example is a good approach. I see a lot of confusion regarding that particular instruction.

**Comment by ieahleen** [comment]
yeah, it could be a good change

could be right for first timers

**Comment by Aditya9111** [comment]
hey i would like to work on this .

**Comment by RohiniMallem** [comment]
These mails,
Are linked with my mail and it has been sunc with different accounts
rohinimallem@gmail.com, mallemrohini@gmail.com, yugandhar brother laptop
system I'm using. So it's not my problem because I have done my PG MCA
Mount Carmel College 2015-18, batch 2020 Data files structure second sem of
main has been cleared.

**Comment by thdU** [comment]
Hi. I opened my first PR. Was able to confirm my changes running locally. Please let me know if I've got anything wrong. Thanks!

**Comment by devifeoma** [comment]
Hi everyone, 

I’m new to open source and would love to contribute here. Freecode camp has really helped me in terms of my coding journey. I need a guide on how to contribute. Thanks

**Comment by jdwilkin4** [comment]
Hi @devifeoma! 

Here is the guide on how to contribute to FCC.
https://contribute.freecodecamp.org/#/index

Here is a more general guide on how to contribute to open source.
https://github.com/freeCodeCamp/how-to-contribute-to-open-source

**Comment by nhcarrigan** [comment]
Hey @devifeoma!

Thank you for your interest in contributing! I highly recommend checking out the resources @jdwilkin4 shared - additionally, this issue currently has a PR that resolves it which is approved and awaiting merge (we are in a code freeze at the moment). 

I recommend looking for issues labelled `help wanted` or `first timers only` for more opportunities to contribute.

**Comment by devifeoma** [comment]
Noted with thanks.
