### ISSUE TITLE
Typo Error in the options and wrong option is set as correct answer in Data Analysis with Python Course - Numpy Operations

### ISSUE THREAD

**Issue by NirajNair** [freeCodeCamp/freeCodeCamp#40520]
**Describe your problem and how to reproduce it:**
The question asked in this page is as follows: 

_What is the value of a after you run the following code?

a = np.arange(5)
a + 20

[20, 21, 22, 24, 24]

[0, 1, 2, 3, 4]

[25, 26, 27, 28, 29]_

There is a typo error in the first option, I believe it should be **_[20, 21, 22, 23, 24]_**  which is the correct answer to the question asked.
Whereas the second option is set as the correct answer.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-operations

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ieahleen** [comment]
try it yourself in an editor, the value of `a` is between the options

**Comment by NirajNair** [comment]
![Screenshot (36)](https://user-images.githubusercontent.com/46632741/102918012-33db3600-44ac-11eb-8aca-2c348e134eed.png)
