### ISSUE TITLE
BUG: Incorrect code-block formatting on news article

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40536]
**Describe your problem and how to reproduce it:**

This article has code blocks formatted as multi-line, but all of the content is rendering on a single line. This results in a horizontal scroll bar within the code block, diminishing readability.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/news/array-destructuring-in-es6-30e398f21d10/

**Recommended fix, suggestions (how would you update it?):**

Add line breaks within the code block text to provide a more legible format.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/63889819/103138338-4315db80-4686-11eb-992b-c69748972f88.png)

**Comment by scissorsneedfoodtoo** [comment]
Hi @nhcarrigan, thank you for catching this. Just fixed the article in Ghost.

Please let me know if you notice anything else :+1: :+1:
