### ISSUE TITLE
Assertion error in lesson ::: Applied Accessibility: Make Screen Reader Navigation Easier with the header Landmark

### ISSUE THREAD

**Issue by fmartins-andre** [freeCodeCamp/freeCodeCamp#40540]
**Describe your problem and how to reproduce it:**
In the "Applied Accessibility: Make Screen Reader Navigation Easier with the header Landmark" lesson, when replaced the "div" tags with "header" tags, every assertion runs fine except the assertion about the existence of a "div" tag in the code. This error has been thrown in other lessons too.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-header-landmark

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 84.0.1 (64bits)
* Operating System: Manjaro Linux (64bits)

![erro_fcc](https://user-images.githubusercontent.com/56693576/103153992-78e4be00-4773-11eb-9192-5574ec5544c5.gif)

**Comment by ShaunSHamilton** [comment]
Hello there,

I am unable to re-produce this. Do you have any browser extensions with access to the lesson page? If so, I recommend you disable them, and try again.

**Comment by fmartins-andre** [comment]
You're right! There was a browser plugin messing up with the code! Thank you, Shaun.
