### ISSUE TITLE
Solution does not submit due to cors error on freecodecamp

### ISSUE THREAD

**Issue by lucas-langa** [freeCodeCamp/freeCodeCamp#40541]
**Describe your problem and how to reproduce it:**
Basically whenever I submit my solution for any apis and microservices exercise that needs a solution hosted elsewhere, my solution is never submitted and the console throws a cors error(see screenshot below).
1. start first challenge on "Managing Packages with Npm - How to Use package.json, the Core of Any Node.js Project or npm Package" from APIs and microservices certification path.
2. fork repl or glone github repo as per instructions
3. complete the exercise, paste link to repo or repl and submit

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: firefox
* Browser Version: 84
* Operating System: ubuntu 18.045 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2020-12-26 19-49-37](https://user-images.githubusercontent.com/43442438/103156658-90dc3200-47b3-11eb-92fd-a303f2882a15.png)

**Comment by ieahleen** [comment]
are submitting the repl.it link shown in the error? that's the wrong link, you need to submit the live app link.

Please use the forum to ask for debugging your code, not github. If on the forum it is established there is nothing wrong with your code you can then open an issue.
