### ISSUE TITLE
Code Portfolio views on should show links to a camper's solutions

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4056]
Here's what @abhisekp's profile looks like on mobile: 
![](https://www.evernote.com/l/Aly3QW5uZHJFA4gAEC9JA9MMTsp_Mcb-JCYB/image.png)

It doesn't show any of his challenge solutions.

Ideally, we would have a single column with just the name of the completed solution that would be a hyperlink to the solution.

For example:

[Bonfire: Repeat a String](http://freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string?solution=function%20repeat(str%2C%20num)%20%7B%0A%20%20%2F%2F%20repeat%20after%20me%0A%20%20%2F%2F%20am%20i%20in%20class%202%20or%20something%3F%0A%20%20%0A%20%20return%20str.repeat(num%20%3C%200%20%3F%200%20%3A%20num)%3B%0A%7D%0A%0Arepeat(%27abc%27%2C%203)%3B%0A)

The view that would need to be updated here is showAccount.jade

There shouldn't be any need to update the controller - this is purely a Bootstrap / Jade task.

**Comment by bugron** [comment]
@QuincyLarson do you mean something like [this](http://prnt.sc/8xqqel)?
