### ISSUE TITLE
Sea level Predictor unit test "test_plot_data_points" broken

### ISSUE THREAD

**Issue by Seventreesofwisdom** [freeCodeCamp/freeCodeCamp#40576]
**Describe your problem and how to reproduce it:**
The test contains expected values that do not match the values in the given csv file, the problem seems to be caused by floating point precision errors.

The problem and a suggested solution have already been discussed here on the freeCodeCamp forum:
https://forum.freecodecamp.org/t/sea-level-predictor-errors/437517

**Add a Link to the page with the problem:**
https://repl.it/github/freeCodeCamp/boilerplate-sea-level-predictor

**Comment by gikf** [comment]
Seems like `1.2.0` version of pandas makes a difference here
With pandas `1.2.0`, exactly the same two errors.
https://repl.it/@sanityto/sea-level-predictor-pandas-1-2-0

With pandas `1.1.5`, no errors, everything passes.
https://repl.it/@sanityto/sea-level-predictor-final

Then one way to solve this is modifying `project.toml` file to force pandas 1.1.5 version with line:
```
pandas = "1.1.5"
```

**Comment by kurotom** [comment]
I had the same problem, do what @gikf said and it worked fine.
Thank you.

**Comment by gianplod** [comment]
Had the same problem, and changing pandas version to 1.1.5 worked perfectly. My question is, will this affect the certification obtention in any way? I mean, if eventually the project is revised, would changing the version of a library be considered as a violation of the Academic Honesty Pledge? Thanks in advance!

**Comment by Seventreesofwisdom** [comment]
Does anyone have any idea WHY the pandas version makes a difference? I think it would be good to understand exactly what causes the error to find the right solution.

**Comment by gikf** [comment]
That's a really good point. I've found `read_csv` method uses now by default higher precision for float point numbers. [Change in default floating precision for read_csv and read_table](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html#change-in-default-floating-precision-for-read-csv-and-read-table). This checks out, as setting `float_precision='legacy'` keyword argument when calling `read_csv`, makes errors go away in pandas `1.2.0`. And in other way as well, setting `float_precision='high'` in pandas `1.1.5` makes errors occur.

This suggests updating values in tests to the ones using higher precision, while using other ways to override issue at best only as a temporary measure.

**Comment by Seventreesofwisdom** [comment]
Ok, so the change in floating precision for `read_csv` is the cause. Still I don't understand exactly how the errors happen, because the tests already have higher precision values (more decimal places) than the original data in the csv. So this would mean the parser in the old pandas version somehow added more decimal places to the data and the new one doesn't.
Anyway, in my opinion it doesn't make much sense to use more decimals in the test than the original data, so this should be changed, right?
I also think that changing the test to use `assertAlmostEqual` instead of `assertEqual` would make sense, as suggested in the forum thread linked above. Any opinions on that?

**Comment by gikf** [comment]
Rather than necessarily using more decimal places, it's higher precision in accurately representing float numbers. Taking as example one value from the project, after reading from csv, float number `0.220472441` was internally represented by pandas as `0.22047244100000002`. That's also why test have such value - it simply was expected value after reading data.

**Comment by beaucarnes** [comment]
I agree with @Seventreesofwisdom and the people in the forum about changing the test to use assertAlmostEqual. I made the change and it seems to be working now so I will close this issue.

**Comment by Seventreesofwisdom** [comment]
@gikf Thank you for the explanation... I had some catching up to do regarding floating point precision but it's clear now.
@beaucarnes, where did you make the change? I can't see no change and no PR in the boilerplate repository?

**Comment by diogo-guimaraes-repo** [comment]
changing the panda version worked for me as well.
