### ISSUE TITLE
JS Data Structures and Algorithms Telephone Number Validator Project, passes weak answers.

### ISSUE THREAD

**Issue by Christopher-Stevers** [freeCodeCamp/freeCodeCamp#40571]
There is a problem with the test for the telephone validator. They pass validators which do not check for proper spacing or dashing. (i. e. my validator will return true for 55 55-55-555-5).
This is the my code which passed the test, but really shouldn't have:
```function telephoneCheck(str) { 
 let firstReg=new RegExp("^\-");
  if(firstReg.test(str)){return false;}
  let regEx= new RegExp("-","g");
  console.log(firstReg);
  let newStr=str.replace(regEx,"");
  let newRegEx= new RegExp(" ","g")
  newStr=newStr.replace( newRegEx,"");
  console.log(newStr);
  let regExArr=[/^\d\d\d\d\d\d\d\d\d\d$/, /^[(]\d\d\d[)]\d\d\d\d\d\d\d$/, /^1[(]\d\d\d[)]\d\d\d\d\d\d\d$/, /^1\d\d\d\d\d\d\d\d\d\d$/];
  for(let i=0; i<regExArr.length; i++){
    if(regExArr[i].test(newStr)){
      console.log(i);
      return regExArr[i].test(newStr);
    }
  }
  return false;
}
```
I'd recommend adding some extra tests to the exercise.

Here is a link to the [exercise:](telephone-number-validator)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 87.0.4280.88
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Durbatuluk1701** [comment]
Link to [code](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator.md)

Link to [project @ freeCodeCamp](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator)

**Comment by jdwilkin4** [comment]
I guess a simple fix would be to add this test. 

`telephoneCheck("55 55-55-555-5")` should be false
```
assert(telephoneCheck("55 55-55-555-5") === false);
```
