### ISSUE TITLE
one-off pages on news should be translated

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40588]
```js
    <Trans i18nKey='donate.other-ways'>
      <a href='https://www.freecodecamp.org/news/how-to-donate-to-free-code-camp'>
```

Should this link be translatable too? With the active effort to translate `/news` articles, being able to replace this ref with the correct translated article would be important IMHO.

_Originally posted by @nhcarrigan in https://github.com/freeCodeCamp/freeCodeCamp/pull/40584#r549769307_

**Comment by nhcarrigan** [comment]
I definitely support this feature - I built out https://github.com/freeCodeCamp/freeCodeCamp/pull/40577 which allows us to translate the trending article links in the footer (or potentially select different trending articles based on each language's analytics). So being able to hot-swap this link would be in line with our overall roadmap, I believe.

**Comment by raisedadead** [comment]
I think this also going to be the case for our other one-off pages like about, terms, etc.

**Comment by nhcarrigan** [comment]
I can start building the groundwork for this tomorrow. 🙂

**Comment by nhcarrigan** [comment]
I've got the translation schema set up for this - I did not mark the PR as closing this issue, though, because we still want to track that the articles themselves are translated right?

**Comment by raisedadead** [comment]
> because we still want to track that the articles themselves are translated right?

let discuss in core chat?

**Comment by raisedadead** [comment]
I believe the infra is already in place, as for translating the articles in-house did we decide on the strategy, if none is available we could always use the internal Trello?

**Comment by nhcarrigan** [comment]
I believe Miya is using a GitHub repo for the news translations, while Rafa is using a Trello board.

**Comment by raisedadead** [comment]
Cool, we do not need to unify this for now.
