### ISSUE TITLE
update task description

### ISSUE THREAD

**Issue by jasontwuk** [freeCodeCamp/freeCodeCamp#40582]
**Describe your problem and how to reproduce it:**
In the description, it said "Nest three `button` elements within each of your `well` `div` elements."
I think it would be clearer to change it to the following:
Nest three `button` elements within each of your `div` elements with class `well`.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/bootstrap/add-elements-within-your-bootstrap-wells

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 87.0.4280.88
* Operating System: Mac OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screenshot](https://user-images.githubusercontent.com/13745974/103274189-fcdbb780-49b8-11eb-9d40-5fa859e9e759.png)

**Comment by RandellDawson** [comment]
What about the following?
> Nest three `button` elements within each of your `div` elements that have the class name `well`.

**Comment by jasontwuk** [comment]
That's even better, thank you.

**Comment by RandellDawson** [comment]
@jasontwuk Would you like to create a PR with this change?

**Comment by jasontwuk** [comment]
@RandellDawson Yes, I would like to do this.
