### ISSUE TITLE
Challenge Waypoint: Iterate over Arrays with map description/code confusion

### ISSUE THREAD

**Issue by Blauelf** [FreeCodeCamp/FreeCodeCamp#4059]
[Challenge  Waypoint: Iterate over Arrays with map](http://freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map)
There seems to be an issue with the task description and the sample code. The task description says

> Use the map function to add 3 to every value in the variable `array`.

while the sample code is
```javascript
var oldArray = [1,2,3,4,5];

// Only change code below this line.


var newArray = oldArray;



// Only change code above this line.

(function() {return newArray;})();
```
Given the context, one could understand the usage of `array` here, and guess from the code what you are supposed to do.
However, in the help chat I frequently encounter people who are confused by this, mix everything, and ask why their code won't pass. I would suggest changing the description to mention the variable `oldArray` instead of the variable `array`.

**Comment by bugron** [comment]
@Blauelf thanks for pointing this out, confirmed!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
