### ISSUE TITLE
Global meta and Stylesheet side-effects due to cross dependencies

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40596]
Some global deps can lead to side-effects when parts of the stack are down

![image](https://user-images.githubusercontent.com/1884376/103382559-886a5b00-4b15-11eb-9d9c-015292f79739.png)

We introduce some components into the head here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/gatsby-ssr.js#L47

but then we break flow and add components directly in the `gatsby-ssr`.

I think we should simplify this whole area here: https://github.com/freeCodeCamp/freeCodeCamp/tree/master/client/src/head, and move it all into the `gatsby-ssr`. The modularization in there is an overkill and is easy source of bugs.

Finally, we should make sure that the global deps like `/css/bootstrap.min.css`, etc. which are relative and can lead to side-effects are being introduces with the path prefix helper (`withPrefix`)

**Comment by ahmadabdolsaheb** [comment]
closed by #40630
