### ISSUE TITLE
Quality Assurance Projects - American British Translator- Automated tester doesn't check for unit and functional tests

### ISSUE THREAD

**Issue by ofk8vb** [freeCodeCamp/freeCodeCamp#40605]
**Describe your problem and how to reproduce it:**
My project passes all the automated tests except the last two which says

‘All 24 unit tests are complete and passing. See /tests/1_unit-tests.js for the expected behavior you should write tests for.’

‘All 6 functional tests are complete and passing. See /tests/2_functional-tests.js for the functionality you should write tests for.’

Chrome developer console shows these errors:

Error: At least 24 tests passed: expected 0 to be at least 24
Error: At least 6 tests passed: expected 0 to be at least 6

I have 30 tests in total for sure, and I see all 30 pass succesfully in repl’s console.

Here is my repl: 

https://boilerplate-project-american-british-english-translator-1.ofk8vb.repl.co

here is a github for working project:

https://github.com/ofk8vb/freeCodeCamp-American-to-British-Translator

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/american-british-translator

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version:  latest
* Operating System:  windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![freecodecamp tester issue](https://user-images.githubusercontent.com/10839171/103458231-182b2780-4d17-11eb-9b59-e47bece155f9.JPG)

**Comment by nhcarrigan** [comment]
Taking a look at your code, I believe this issue is specifically related to https://github.com/freeCodeCamp/freeCodeCamp/pull/40467.

**Comment by ofk8vb** [comment]
> Taking a look at your code, I believe this issue is specifically related to #40467.

Removed all the arrow functions from the tests yet I am still getting the same error.

**Comment by ofk8vb** [comment]
> Taking a look at your code, I believe this issue is specifically related to #40467.

So is there nothing I can do to pass these tests?

**Comment by nhcarrigan** [comment]
Try changing this line:

https://github.com/ofk8vb/freeCodeCamp-American-to-British-Translator/blob/35274b03a0c5fe19c9faa39db7ee684a0b5faf2d/tests/1_unit-tests.js#L7

To `suite('Unit Tests ->', function() {`

**Comment by ofk8vb** [comment]
Your solution worked, I have passed the tests, and got the certificate. 

Since you  already have an open issue about the subject I will be closing this issue.
 
 Thanks a lot!
