### ISSUE TITLE
Seems pretty easy to game this bonfire without a working solution

### ISSUE THREAD

**Issue by dmfarcas** [FreeCodeCamp/FreeCodeCamp#4062]
Challenge [Bonfire: Repeat a string repeat a string](http://www.freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string#?solution=function%20repeat(str%2C%20num)%20%7B%0A%20%20%0A%20%20if%20(num%20%3C%200)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20str%20%3D%20%22%22%3B%0A%20%20%20%20%7D%0A%20%20var%20str2%20%3D%20str.concat(str%2C%20str)%3B%0A%20%20%0A%20%20return%20str2%3B%0A%7D%0A%0Arepeat(%22abc%22%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function repeat(str, num) {
  
  if (num < 0)
    {
      str = "";
    }
  var str2 = str.concat(str, str);
  
  return str2;
}

repeat("abc", 5);

```

**Comment by ltegman** [comment]
This bonfire could definitely use a couple more test cases with more variety, since currently 3 and -2 are the only values for `num` used.

**Comment by ankitaggarwal011** [comment]
This code should fail for tests where num = 0, 1, 2, and >= 4. Thus, these tests should be included in the test suite as well. @ltegman
Tests can be added here, https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/basic-bonfires.json#L368.
@dmfarcas, do you want take it?

**Comment by natac13** [comment]
I would like to take this if no one else is

**Comment by dmfarcas** [comment]
@ankitaggarwal011  if it's just a matter of adding those tests, I could be assigned for this. 

Assign @natac13  though, since he asked first :smile:

**Comment by ankitaggarwal011** [comment]
@natac13, please go ahead, add the required tests and close this issue.

**Comment by natac13** [comment]
No problem will be done when I get home from work

**Comment by natac13** [comment]
Probably have to wait till the weekend.... apologies. Anyone else is free to take it before then
