### ISSUE TITLE
Chinese comments needing different translations

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#40629]
I noticed two comments in [curriculum/dictionaries/chinese/comments.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/dictionaries/chinese/comments.js) that translated words that were actually code variable names.

### Comment 1
```js
  {	
    id: 'tegkqa',	
    text: 'Define the Container component here:'	
  },
```
`Container` is a variable name that should not be translated.

### Comment 2
```js
  {	
    id: 'ead98i',	
    text: 'Global count variable:'	
  },
```
`count` is a variable name that should not be translated.

**Comment by miyaliu666** [comment]
Just fixed them. Thanks!

**Comment by RandellDawson** [comment]
Where is the PR?

**Comment by RandellDawson** [comment]
[This commit](https://github.com/freeCodeCamp/freeCodeCamp/commit/c6cbe7750fb5f3f9b38e1a72caf037a3957664df) closed this issue.
