### ISSUE TITLE
Two new translation keys that haven't been translated to Chinese

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40623]
A recent PR added a few new sentences to the donate page. The new keys are here: https://github.com/freeCodeCamp/freeCodeCamp/blob/next-i18n-client/client/i18n/locales/chinese/translations.json#L346.

Want to translate these when you get a chance @miyaliu666?

**Comment by miyaliu666** [comment]
Just translated line 209, 210, 346 and 367. LGTM. @moT01
