### ISSUE TITLE
Bug : Python for Everybody Challenge - Conditional Execution 

### ISSUE THREAD

**Issue by Gimhan-minion** [freeCodeCamp/freeCodeCamp#40625]
**Describe your problem and how to reproduce it:**
**Problem**
- All 4 answers in the below-mentioned python challenge is incorrect.

**Reproduce**
-At least one of the answers should be replaced with `if 0==x:`to `if x==0:`

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/conditional-execution

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 86.0.4240.198 (Official Build) (64-bit)
* Operating System: Ubuntu 20.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/60275681/103582659-5174ba80-4f04-11eb-8dd5-ce8bd8e486c8.png)

**Comment by RandellDawson** [comment]
Not sure why you think the last answer is not correct.  It is definitely correct.  Put the following into your favorite Python interpreter and run it.  You will see "Yes" gets printed.

```
x = 0
y = 10

if 0 == x:
  if y == 10:
    print("Yes")
```

**Comment by moT01** [comment]
I'm not convinced. The accepted correct answer you have selected in the screen shot seems to print `Yes`...
![Screen Shot 2021-01-04 at 4 14 48 PM](https://user-images.githubusercontent.com/20648924/103585074-147ada80-4ea8-11eb-916e-b7784078f17d.png)

**Comment by Gimhan-minion** [comment]
@RandellDawson @moT01 My initial thought was even though this works fine, this is for the beginners isn't it? I thought it will give a better idea for beginners if we replace it with `x=0`. Anyway if you guys think it's better this way I'm totally fine with it. Thank you for responding quickly. :hugs:

**Comment by moT01** [comment]
I suppose that `x == 0` is probably more conventional. But I don't think this is an issue that needs fixing. We can see if anyone else wants to weigh in.

**Comment by Gimhan-minion** [comment]
Okay guys understood. Thank you all for responding. I'll close this issue. :)
