### ISSUE TITLE
Setup Issues on Windows 10 WSL2 Ubuntu 20.04

### ISSUE THREAD

**Issue by Novalis15** [freeCodeCamp/freeCodeCamp#40632]
## Description
Based on the suggestion of @raisedadead in #37865, i setup a local dev environment of this repository on an Ubuntu 20.04 WSL2 Instance. However, similar to #39278, the mongodb connector is unable to establish a connection to my MongoDB 3.6.21 instance, running on Docker Desktop 3.0.0. The MongoDB Container is not even printing any logs during the connection phase. I'm running on the latest master branch without any custom changes.

```
Connection fails: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkTimeoutError: connection timed out
```

Also, Even though the frontend compiles successfully, build time increases drastically on the WSL2 instance versus on native Windows 10. I did some Screenshots of the different build times:

#### WSL2 - Ubuntu 20.04
![WSL2_Buildtime](https://user-images.githubusercontent.com/18482238/103668075-021ba200-4f77-11eb-970e-dd3cae720978.png)

#### Windows 10
![Windows_Buildtime](https://user-images.githubusercontent.com/18482238/103668091-06e05600-4f77-11eb-86ef-46a9e7eacec2.png)

### Browser and Operating System:
OS: Windows 10 (Build 19042.685) with WSL2 Ubuntu 20.04
Browser: Firefox 84.0.1 (64-Bit)
Docker Desktop 3.0.0 with WSL2 Integration and a MongoDB 3.6.21 Container

**Comment by ShaunSHamilton** [comment]
Hello there,

I _almost always_ get the `MongoNetworkError: failed to connect to server [localhost:27017] on first connect` error (Windows 10, and WSL2 Ubuntu 20.04). I am not using the Docker setup, but it should eventually connect.

Something that helped my PC is to not run `npm run develop`, but first run:
- `npm run develop:server`
- `npm run develop:client`
Running both at the same time, often caused parity issues between the connections. _I assume this is not specific to using MongoDB in Docker, but there is no harm in installing `mongodb` within Ubuntu, and side-stepping the Docker stage.

PS: Unless otherwise confirmed, I cannot see this as an issue for this repository, and this is more likely to suit the [forums](https://forum.freecodecamp.org/), or the [contributors chat](https://chat.freecodecamp.org/channel/contributors)

**Comment by raisedadead** [comment]
Is the container already available before you are starting the dev server? 

I think we would need to isolate the issue (which to me seems flaky) - how about connecting to the mongodb container via something like Robo 3T or Compass to test if you can connect to it at `localhost:27017` in the first place.

WSL2 has had some "networking" and discovery issues in the past, but I haven't faced any recently.

**Comment by Novalis15** [comment]
Hi! I'm sorry if this topic is more suitable for the forums or the contributors chat. I thought because of the linked issues, this one would be a fit aswell :).

Running only `npm run develop:server` will also just give me the `MongoNetworkError`. The container starts up on Windows boot. I even tried to delete the container and create a new MongoDB Container inside of WSL2. I also tried to use a local ubuntu MongoDB installation in WSL2, as @ShaunSHamilton suggested. Although, the output is the same. However, I can successfully connect to any MongoDB Instance via MongoDB Compass via `localhost:27017`.

**Comment by Novalis15** [comment]
I was able to resolve this issue!

Most of my problems were based on the filesharing System between WSL2 and Windows. Therefore i had to move the cloned Repo to a place which is not shared with Windows (e.g. `~/user/PROJECTS/freeCodeCamp`). Build times are now blazingly fast and the Browser finally loads all pages without trouble. `ConnectionTimeout` errors with MongoDB are now gone as well, even though i had some `ConnectionRefused` Errors, using a Docker MongoDB Container, which is somehow now resolved by restarting the Container.

However, i didn't have any problems with a local Ubuntu MongoDB Installation so far, so if someone wants to swap from a MongoDB Container to a local instance, i would recommend [this Post](https://dev.to/seanwelshbrown/installing-mongodb-on-windows-subsystem-for-linux-wsl-2-19m9) for doing so.

I think it would be great to have some Hints to the [How To Setup WSL Guidelines](https://contribute.freecodecamp.org/#/how-to-setup-wsl). At least regarding those intensive performance issues in conjunction with the WSL2 - Windows 10 file sharing System.

Thanks for the great Help @raisedadead and @ShaunSHamilton 😃 👍

**Comment by raisedadead** [comment]
You can actually access WSL2 side files on Windows 10 Explorer like so:


```
\\wsl$
```

For me on `Ubuntu 20.04` with the username `raisedadead`

```
\\wsl$\Ubuntu-20.04\home\raisedadead
```

![image](https://user-images.githubusercontent.com/1884376/103908555-9a0cbd80-5128-11eb-92db-1e8450f06b3f.png)


You are right we should add tips on that guide. A PR is welcome if you are interested.
