### ISSUE TITLE
Parallel Execution of Multiple Functions in a Lambda using Node.js

### ISSUE THREAD

**Issue by ThirumalaV** [freeCodeCamp/freeCodeCamp#40633]
Can we execute multiple functions parallelly/asynchronously in a lambda with synchronous flow using node.js. We tried using run-parallel, async/await, and promise.all. But, the functions are executing synchronously one after another rather than the required asynchronous process. Can anyone suggest best approach?

**Comment by ojeytonwilliams** [comment]
Hi @ThirumalaV you might want to ask over at the [forum](https://forum.freecodecamp.org/) about this.  It doesn't sound like an issue with our codebase, though.
