### ISSUE TITLE
Implement Bubble Sort description does not match code in the editor

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40645]
**Describe your problem and how to reproduce it:**
The challenge description says
> We are calling this function from behind the scenes; the test array we are using is commented out in the editor. Try logging array to see your sorting algorithm in action!

there is not a commented out array there
I wouldn't know how to change that other than deleting the paragraph entirely

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-bubble-sort

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 87.0.4280.77
* Operating System: iOS 14.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by rufanov** [comment]
Description is wrong. Code placeholder was changed in f203273 - test array moved from comment to function call argument, but description stayed same without any edits.

**Comment by ShaunSHamilton** [comment]
> I wouldn't know how to change that other than deleting the paragraph entirely

This seems quite reasonable. I will open this up to first timers

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Lazt009** [comment]
I would Like to contribute to your cause i am a first timer and have not yet worked in big project but i want to start by freecodecamp

**Comment by ieahleen** [comment]
@Lazt009 thank you for wanting to contribute, this issue has already a linked PR. Take a look at other issues with label "first timers only" and "help wanted" that do not have already a linked PR
