### ISSUE TITLE
Time calculator test error (Scientific computing with Python)

### ISSUE THREAD

**Issue by gianplod** [freeCodeCamp/freeCodeCamp#40655]
**Describe your problem and how to reproduce it:**
There's an error in one of the tests provided for the Time calculator project, which is part of the Scientific computing with Python Certification: 
```
def test_two_days_later_with_day(self):
        actual = add_time("11:59 PM", "24:05", "Wednesday")
        expected = "12:04 AM, Friday (2 days later)"
        self.assertEqual(actual, expected, 'Expected calling "add_time()" with "2:59 AM", "24:00", "Friday" to return "12:04 AM, Friday (2 days later)"')
```
The self.assertEqual method text should say 'Expected calling "add_time()" with **"11:59 PM", "24:05", "Wednesday"** to return "12:04 AM, Friday (2 days later)".

**Add a Link to the page with the problem:**
https://repl.it/@gPlod/boilerplate-time-calculator#test_module.py

**Tell us about your browser and operating system:**
* Browser Name: - 
* Browser Version: -
* Operating System: - 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Ismailtlem** [comment]
Are the test files of the python projects hosted on some repo somewhere ?

**Comment by gianplod** [comment]
They are. And there's already a Pull request to fix this error. 

Thank you for making me notice that.

Guess I can close this.
