### ISSUE TITLE
Bonfire: Truncate a string - Passes all tests, but creates wrong output

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4066]
A user @adnan333bd alerted me to this issue:

Challenge [Bonfire: Truncate a string](http://www.freecodecamp.com/challenges/bonfire-truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20var%20strlen%20%3D%20str.length%3B%0A%20%20var%20dotSpace%20%3D%203%3B%0A%20%20%0A%20%20if(strlen%3C%3D3)%0A%20%20%20%20dotSpace%20%3D%200%3B%0A%20%20%0A%20%20if(num%3Cstrlen)%0A%20%20%20%20str%20%3D%20str.slice(0%2Cnum-dotSpace)%20%2B%20'...'%3B%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0Atruncate(%22abcd%22%2C%203)%3B%0A) has an issue.

User code:
```javascript
function truncate(str, num) {
// Clear out that junk in your trunk
  var strlen = str.length;
  var dotSpace = 3;
  
  if(strlen<=3)
    dotSpace = 0;
  
  if(num<strlen)
    str = str.slice(0,num-dotSpace) + '...';
  
  return str;
}

truncate("abcd", 3);
```

Output for `truncate("abcd", 3);` is `...`

I'm not entirely certain what is going wrong here, but it seems like an additional test might be in order.

**Comment by mike9182** [comment]
What is the correct output for truncate("abcd", 3)?

I think part of the question needs to be clarified. If "less than or equal to 3 characters" is referring to the input string (first parameter), then the result "..." seems to satisfy the rules given in the question. In order to return a string of length 3 that ends in "...", and include the three dots in the string length, the result must always be "...". However, if the "less than or equal to 3 characters is referring to the length of the result (second parameter), then the result should be "abc". Although, this interpretation of the 3 character rule would not satisfy the test below (copied from the question).

> truncate("A-", 1) should return "A...".

**Rules from question:**
> Note that the three dots at the end add to the string length.
>
 > If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length.

Let me know if I am missing something here.

**Comment by adnan333bd** [comment]
@mike9182 is right. According to the spec, the solution was correct.

But a more practical spec could have the following last line.

"<b>The truncated string must contain at least one character of the original string.</b>"

**Comment by awesomeaniruddh** [comment]
`abcd` should return `a...`. This solution should be added as a test to prevent ambiguity.

@adnan333bd's suggested spec is better than the one currently in place.

This should be an easy PR for a camper.

**Comment by zmbc** [comment]
@awesomeaniruddh That doesn't seem right. No matter what, the truncated string should be the length passed to the function. So truncate("abcd", 3) wouldn't return "a...", it would return "abc" (if we are following @adnan333bd's suggested spec).

**Comment by awesomeaniruddh** [comment]
On second thought, I see no reason why `...` is an invalid solution for the bonfire. The rules don't say that the output string must contain a character from the initial string.

> If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length.

^That seems to be for cases where the output string without the `...`s has a length of less than or equal to 1. If we take that into account, the correct solution for the bonfire would be `abc...` and not `a...` as I had suggested previously.

**Comment by SaintPeter** [comment]
While the specific example of `...` is potentially correct, both this code and the code from #4204 produce other obviously incorrect results while still passing the test.

Here is some of the output:
Test: `truncate("Absolutely Longer", 2);`
```
 Good: "Ab..."
#4066: "Absolutely Longe..."
#4204: "Absolutely Longe..."
```
So it is clear to me that we need to add an additional test.  I'll write a PR shortly.

**Comment by luisescobar89** [comment]
try this
function truncate(str, num) {
  // Clear out that junk in your trunk
  if(num <= 3){
    str = str.slice(0, num);
    str += "...";
    
    
  }
  
  else if(str.length > num){
    str = str.slice(0,num-3);
    str += "...";
  }


  return str;
  

}

truncate("Absolutely Longer", 2);

**Comment by iskya** [comment]
Really confusing instructions... I still dont get it when I read it, I have to see the solution just to figure out what is wanted here...
