### ISSUE TITLE
Client side tests for installing helmet in Info Security curriculum fail with 404 on Github repository

### ISSUE THREAD

**Issue by JustinKnueppel** [freeCodeCamp/freeCodeCamp#40674]
**Describe your problem and how to reproduce it:**

I forked the given Github repository [here](https://github.com/freeCodeCamp/boilerplate-infosec/), created a main branch and set it as default, ran `npm install --save-exact helmet@3.21.3`, added `const helmet = require('helmet');` to the top of `myApp.js`, saved the commit, pushed to main, and submitted the URL [https://github.com/JustinKnueppel/boilerplate-infosec](https://github.com/JustinKnueppel/boilerplate-infosec). When running the tests, it said that it failed to find Helmet version 3.21.3 in the `package.json`. Looking at the network tab as well as the documentation found [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-with-helmetjs/install-and-require-helmet.md) it shows that the test is validated by making a request to `${url}/_api/package.json` but that appears to be returning a 404 status.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/install-and-require-helmet

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 84.0.1
* Operating System: OpenSuse Linux

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![fccissue](https://user-images.githubusercontent.com/32350916/104243348-6d112100-542e-11eb-977b-fde340338666.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

It appears you are submitting a URL to a GitHub repository. The tests require a **Live App** url. That means the app must be running (with a server), and publicly available.

As this is not an issue with the code base or boilerplate, I am going to close this issue. Thank you.

In general, I recommend you seek help on the [forum](https://forum.freecodecamp.org/), as this is the fastest way to get help, and a friendlier format to work with.

Happy coding

**Comment by jeremyfiel** [comment]
hi @ShaunSHamilton 

This remains as a blocker for anyone using github clone to work on this section. 

I have an Azure static web app of the site up and running but there is no `_api/` route for the test to read the `package.json` file. 

The only way this challenge is passed is by using repl.it because they are exposing that endpoint.   Can these tests be updated to allow for any hosting of this challenge?  

I'm not clear if it's even possible to read a `package.json` file from a node build if it's not explicitly exposed in an api the same way repl.it does it.

**Comment by ShaunSHamilton** [comment]
@jeremyfiel I am not sure I understand the issue.

We (from the boilerplate) add those routes. There is nothing Replit specific in that boilerplate:
https://github.com/freeCodeCamp/boilerplate-infosec/blob/8fbd158cb85be2351ebfae0a5852e39865b9f1fe/server.js#L49-L54
