### ISSUE TITLE
Typographical error in the test suite, "tile" instead of "title"

### ISSUE THREAD

**Issue by Mafevito** [freeCodeCamp/freeCodeCamp#40679]
**Describe your problem and how to reproduce it:**
There is a typographical error in the test suite of the last project: Personal Portfolio Webpage of Receptive Web Design Certification.

In point 4 of the test suite it says that: 
The projects section should contain at least one element with a class of "project-tile" to hold a project.

It should be "project-title" and not "project-tile".

**Add a Link to the page with the problem:**
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 87
* Operating System: Linux, Ubuntu

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![error](https://user-images.githubusercontent.com/19434332/104321895-7eb50000-54e4-11eb-80d7-fa0a77ed9050.png)

**Comment by nhcarrigan** [comment]
Hello there!

The [project page](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage) also references the `project-tile` class:

> User Story #4: The projects section should contain at least one element with a class of project-tile to hold a project.

The `project-tile` isn't a *title*, but rather the "tile" that holds a project image + information. This is shown in the example project:

![image](https://user-images.githubusercontent.com/63889819/104326011-15aa9980-549e-11eb-9f5a-0fde164464c7.png)

**Comment by lasjorg** [comment]
You are not the first to mistake this for a typo (or add title instead of tile for the class name in their project).

I would have preferred "card", "item", or "container", instead of "tile". But it is what it is and changing it now is more hassle than it's worth.

**Comment by ojeytonwilliams** [comment]
Yep, I agree with you on this @lasjorg. We might look into producing more bundle versions in the future and, if we change this, we should definitely use one of those of those other names.

Thanks for opening this discussion, @Mafevito, but, as @nhcarrigan pointed out, this is behaving correctly, albeit in an odd way.
