### ISSUE TITLE
OOP: Iterate Over All Properties - Test both presence and absence of properties

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#40682]
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/iterate-over-all-properties
Forum: https://forum.freecodecamp.org/t/bug-in-iterate-over-all-properties/440230

Right now you can pass the challenge using a for loop with no conditionals.

```
for (let property in beagle) {
  ownProps.push(property);
  prototypeProps.push(property);
}
```

1. Test for both the presence and absence of properties (includes && !includes).

```
assert(ownProps.includes('name') && !ownProps.includes('numLegs'));

assert(prototypeProps.includes('numLegs') && !prototypeProps.includes('name'));
```

2. Possibly change assert messages from "should include" to "should only contain".

**Comment by moT01** [comment]
Sounds good to me @lasjorg. We could possible use a deepEqual to make sure there aren't any other properties added.
