### ISSUE TITLE
Rosetta Code - Stern-Brocot sequence - tests don't match task in challenge description

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#40684]
**Describe your problem and how to reproduce it:**
Challenge description gives slightly different task, to what needs to be done to pass tests.

Challenge is about [Stern-Brocot sequence](https://oeis.org/A002487), which looks at the beginning like (skipping zero at start):
```
1, 1, 2, 1, 3, 2, 3, 1, 4, 3, 5, 2, 5, 3, 4, 1, 5, 4, 7, 3
```
Challenge description asks to create function returning **n-th member** of the sequence. 

However expected values in tests, and sample solution don't match that.
>sternBrocot(2) should return 3.
sternBrocot(3) should return 5.
sternBrocot(5) should return 11.
sternBrocot(7) should return 19.
sternBrocot(10) should return 39.

Function matching tests would be one returning at **which position** in sequence number is encountered for first time.

Original challenge on Rosetta Code - [Stern-Brocot sequence](https://rosettacode.org/wiki/Stern-Brocot_sequence) have both these variations as a part of task, so that's most likely how it sneaked in.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/stern-brocot-sequence
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/stern-brocot-sequence.md

**Comment by moT01** [comment]
I vote to have the function return the position in the sequence of the argument. We wouldn't need to change the tests, just the description.

**Comment by nhcarrigan** [comment]
I'm in favour of that approach as well.
