### ISSUE TITLE
One "defined" word in description of basic-css/inherit-css-variables missing in Chrome.

### ISSUE THREAD

**Issue by RWitak** [freeCodeCamp/freeCodeCamp#40695]
**Problem**  
The "Inherit CSS Variables" lesson has the following passage:  
> To make use of inheritance, CSS variables are often defined in the
> 
> element.

When inspecting the passage in Chrome, I get:  
```
<p>To make use of inheritance, CSS variables are often defined in the <dfn></dfn></p><div></div> element.<p></p>
<p><code>:root</code> is a <dfn>pseudo-class</dfn> selector that matches the root element of the document, usually the <code>html</code> element.

```
but looking at the original file in the repo, I found the correct  
```
To make use of inheritance, CSS variables are often defined in the <dfn>:root</dfn> element.

`:root` is a <dfn>pseudo-class</dfn> selector that matches the root element of the document, usually the `html` element.
```

So apparently, there is some bug when translating the Markdown's <dfn> tag into HTML.  

**Link to the page with the problem:**  
https://freecodecamp.org/learn/responsive-web-design/basic-css/inherit-css-variables

**Browser and operating system:**  
* Browser Name: Google Chrome  
* Browser Version:  87.0.4280.141 (64-Bit)  
* Operating System: Windows 10 (64-Bit)  

**Screenshots**
![image](https://user-images.githubusercontent.com/53919023/104502986-d59fff80-55e0-11eb-8085-351b9a634c42.png)

![image](https://user-images.githubusercontent.com/53919023/104503132-f5cfbe80-55e0-11eb-8639-f663ea90a766.png)

**Comment by nhcarrigan** [comment]
Thanks for bringing this to our attention - this appears to be related to #40491

**Comment by ShaunSHamilton** [comment]
As this looks like a simple fix, I have opened this up to first timers.

It appears the word _:root_ is just missing  backticks (`): https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-css/inherit-css-variables.md

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by nhcarrigan** [comment]
Closing as resolved via https://github.com/freeCodeCamp/freeCodeCamp/pull/41186
