### ISSUE TITLE
Health checks for third party services

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40702]
@ojeytonwilliams that is the path moving forward. Since we cannot consistently test the outcome of our scripts on a third party service (paypal modal), the best way to test such cases would be to test the information that we are giving to these services. 

For this instance, a test to check if we are supplying the proper url parameters should work; however, if they change their api without our knowledge, I am not sure how we could properly test against that unless a user creates an issue.

_Originally posted by @ahmadabdolsaheb in https://github.com/freeCodeCamp/freeCodeCamp/issues/40641#issuecomment-760754360_

> Since we cannot consistently test the outcome of our scripts on a third party service (paypal modal)

I agree that this shouldn't be part of the CI, because service disruptions should not break our tests.  However, it would be nice if we didn't have to rely on user reports.  One thing we could consider is a separate check (like we do with Lighthouse) that periodically confirms that our site can successfully interact with the sandboxes.  What do you think?

**Comment by ahmadabdolsaheb** [comment]
There is a broad spectrum of tests when it comes to payment providers (Stripe, Paypal) ranging from mock apis to e2e cypress tests.



It seem like they don't mind us talking to their sandbox api for regular testing ([Paypal testing docs](https://developer.paypal.com/docs/business/test-and-go-live/))
And even if we do it more frequently than we should there are rate limiting in place([Stripe testing docs](https://stripe.com/docs/testing))
Although cypress frowns upon testing what we cannot control, there is documentation and instances for talking to 3rd party apis. ( not recommended )

As you mentioned:
- We should always test the data we provide to the 3rd party services (parameters, arguments, etc)
- We should periodically hit the sandbox apis with our data and test the outcome. 

Note to self: keep in mind that integration testing 3rd party apis is always flaking, so our tests should wait for the response and retry upon failure if possible.

**Comment by ojeytonwilliams** [comment]
Thanks Ahmad, that covers it nicely.  The specifics of how we want to test the services we have to work out, but the broad plan sounds perfect.

**Comment by ahmadabdolsaheb** [comment]
So basically we would need sandbox and mock tests:
1) sandbox testing should occur preferably daily for a subset of cypress tests on a cron schedule.
2) mocks should run on each source modification, and should preferably be provided by an up to date npm module or the payment processor.

**Comment by ojeytonwilliams** [comment]
Closing since it's covering the same issues as https://github.com/freeCodeCamp/freeCodeCamp/issues/39980
