### ISSUE TITLE
Use Rest Parameter with Function Parameter Final Test is Unclear

### ISSUE THREAD

**Issue by Abidkarim1010** [freeCodeCamp/freeCodeCamp#40707]
While solving a problem on the free code camp of JavaScript ES6, I stuck to an error. Which was about the rest parameter.
The problem says to make a sum function which should take a rest parameter and return the sum of the parameters. I did the job but got an error about to use the args as the rest parameter, instead of using the args as the rest parameter. I called for help and reported the bug. You must change the last test, as it does not tells about the real issue or it must say to use the arrow function in order to create the sum funciton.

**Comment by ShaunSHamilton** [comment]
For those reading, here is the related forum post: https://forum.freecodecamp.org/t/rest-paramenters-and-es6/440776

This is the code, the author tried:
```javascript
function sum(...args) {
  return args.reduce((a,b) => a+b,0);
}
```

My recommendation is, seeing as this is the ES6 section, the last test of this file: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-the-rest-parameter-with-function-parameters.md

To this:
> `sum` should be an arrow function, and use the `...` rest parameter on the `args` parameter.

I would be happy, if someone could shorten that...

**Comment by nhcarrigan** [comment]
I'd be okay with that description, or with adding our "Don't touch this" comments to the seed:

```js
const sum = (x, y, z) => {
  // Only change code below this line
  const args = [x, y, z];
  return args.reduce((a, b) => a + b, 0);
  // Only change code above this line
}
```

That was the source of the camper's bug, correct? Changing the outer function from an arrow to `function` syntax?

**Comment by ShaunSHamilton** [comment]
> That was the source of the camper's bug, correct? Changing the outer function from an arrow to function syntax?

@nhcarrigan Yes. Unfortunately, the camper is required to change the `(x,y,z)` of the function. So, the _change code below this line_ will not work in this case.

**Comment by nhcarrigan** [comment]
Ah, right - okay. I'm content with your proposal then. 🙂

**Comment by ShaunSHamilton** [comment]
I have opened this issue up for _first timers only_. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
