### ISSUE TITLE
project description could be reworded to convey its value more efficiently 

### ISSUE THREAD

**Issue by atopp25** [freeCodeCamp/freeCodeCamp#40700]
**Describe your problem and how to reproduce it:**
On the project's home page, under JavaScript Algorithms and Data Structures, where it describes why freeCodeCamp is a valuable source for people wanting to learn how to code, the description could use some improvements. For example in section of the page it reads:

<p>Practice is the key. Practice, practice, practice.</p>
      <p>
        And this curriculum will give you thousands of hours of hands-on
        programming practice.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn

**Recommended fix, suggestions (how would you update it?):**
It sounds a bit redundant so a better description could be something like:

<p>Practice is key, and this curriculum will provide you with thousands of hours of hands-on programming practice.</p>

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
Just for clarity, this message only appears when you go to /learn while logged out.

I think the redundancy is intentional, to try and get the message across. I don't mind how it is now. Your suggestion is good too @atopp25, but I think I'm going to vote to leave this as-is. We can see what others think, though.

**Comment by ahmadabdolsaheb** [comment]
Thanks @atopp25 for submitting this issue. Although the message is redundant, as @moT01 pointed out, the redundancy is intentional and most users will see this message a few times. 

I am closing this issue accordingly. Please let us know if this issue has been closed by mistake.
