### ISSUE TITLE
Remove Function Calls from Challenge Seed

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#40710]
The following challenges have an example function call in the seed code. These function calls should be removed and the related tests should be clarified to reflect the call instead.

- https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-bubble-sort
- https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-merge-sort
- https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-selection-sort
- https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-insertion-sort

This sorting challenge is correct and could be used for reference.
- https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-quick-sort

**Comment by MuriloMarquesSantos** [comment]
Hi, nhcarrigan. I'd like to try to help and solve it. I'm still learning about the project so I would like to ask a question so I can understand the issue better.

There is a function call in the file (example: **implement-bubble-sort.md**)
![image](https://user-images.githubusercontent.com/18178861/104789249-395a3200-5773-11eb-82d4-e50264e659bc.png)

And it should be removed from the seed section and transferred to here, similarly to implement-quick-sort:
![image](https://user-images.githubusercontent.com/18178861/104789313-77efec80-5773-11eb-9cb0-104364621574.png)

Is it correct or are there other files that I should be concerned about?

**Comment by nhcarrigan** [comment]
That is correct, yes - this same change should be completed on the four files I've linked.

I would, however, recommend holding off on working on this until we receive additional consensus that this is the best way to proceed. 🙂 

If you run in to any questions, feel free to review our [contributing documentation](https://contribute.freecodecamp.org) or ask in our [contributors chat](https://chat.freecodecamp.org) or the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3).

**Comment by MuriloMarquesSantos** [comment]
Sounds great!! Thanks for the fast response. I will wait until further notice.

**Comment by tristansoriaga** [comment]
Hi MuriloMarquesSantos, are you still interested in fixing this issue?
