### ISSUE TITLE
Remove spaces from beginning and end passed with result as array instead of string

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40715]
**Describe your problem and how to reproduce it:**
the challenge accepts 
```
let hello = "   Hello, World!  ";
let wsRegex = /(?!=\s+)(?:\w+\D\s\w+\D)(?!=\s+)/; // Change this line
let result = hello.match(wsRegex); // Change this line
```

in this case though `result` has value of:
```
[ 'Hello, World!',
  index: 3,
  input: '   Hello, World!  ',
  groups: undefined ]
```

looking at the test, it is asserted as `assert(result == 'Hello, World!');`, with non strict equality
I suggest a change here

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end.md

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by gikf** [comment]
There's one more issue with this challenge, this also passes:
```
let result = 'Hello, World';
```
