### ISSUE TITLE
More in-depth functional programming course

### ISSUE THREAD

**Issue by dark-magic** [freeCodeCamp/freeCodeCamp#40759]
**Is your feature request related to a problem? Please describe.**
The functional programming course of the curriculum seems to focus mostly on using functions as first order citizens. While this and array functions like, `forEach`, `map`, and `reduce` are a great place to start for functional programming, this is not all there is to functional programming. Using recursion to reduce state, using immutable variables whenever possible, and explaining what pure functions are where the real functional programming **starts**. Furthermore, currying is a concept every functional programmer should have at least heard of and tried, and should not just be shown at the end of the course as filler content.

**Describe the solution you'd like**
A complete overhaul of the functional programming course is needed. There are challenges about string methods which have nothing to do with functional programming apart from being functions, and there is a lack of explanation on the goal of functional programming. The challenges should focus more on coding the functional way and how to reduce state instead of using functions. [This talk](https://youtu.be/vK1DazRK_a0) could be a great point of reference for functional programming. He even uses javascript in his talk :)

**Comment by ieahleen** [comment]
considering tbe developing of curriculum 7.0 I don't think the current one is going do be overhauled like that. Consider take a look at the progress for 7.0 and contribute/give feedback there

https://github.com/freeCodeCamp/CurriculumExpansion

**Comment by dark-magic** [comment]
Good to know, will have a look at it!

**Comment by dark-magic** [comment]
[The code for curriculum 7](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/functional-programming-spreadsheet) looks more like actual functional programming. Great to see improvements being made explaining the fundamentals of functional programming instead of just using functions.

**Comment by moT01** [comment]
I think it's safe to close this. As mentioned, we won't be overhauling the current functional programming section. The project based curriculum in the works will give it a fresh update. Input on it is certainly welcome. Thanks and happy coding 🎉
