### ISSUE TITLE
Private names show up on certificates

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40765]
If I set my name to private on my settings page, it still shows up on certificates.

We could perhaps do like we do for some of the other settings and disable certificates when a name is private.

Or perhaps just use a generic or blank name on the certificate - this doesn't sound very good though - I vote for the first option. It's not that big of a problem, but it seems like we shouldn't show a users name anywhere if it's set to private.

**Comment by ojeytonwilliams** [comment]
I'd say either disable them or use the username, since that's still public.  I think it would be fine to have 

> This certifies that
moT01
has successfully completed...

/cc @QuincyLarson

**Comment by raisedadead** [comment]
The certificates should fallback to username when a name is not available. In practice we should disable them because of lack of transparency on the user's part, but I think using the username is just as fine.
