### ISSUE TITLE
Rosetta Code - Zeckendorf number representation - test doesn't match task in challenge description

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#40763]
**Describe your problem and how to reproduce it:**
Challenge description asks for an **array of the first n** Zeckendorf number representations in order. On the other hand second test expects function to return just a single representation of **number n**:
```
assert.deepEqual(answer, solution20);
```
And those variables from `--after-user-code--`:
```
const range = (m, n) => (
  Array.from({
    length: Math.floor(n - m) + 1
  }, (_, i) => m + i)
);

const solution20 = [
  '1', '10', '100', '101', '1000', '1001', '1010', '10000', '10001',
  '10010', '10100', '10101', '100000', '100001', '100010', '100100', '100101',
  '101000', '101001', '101010'
];

const answer = range(1, 20).map(zeckendorf);
```
Description of the relevant test is very general and it wouldn't be affected when clearing above inconsistency, However it could say something more than just that answer needs to be correct.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/zeckendorf-number-representation
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/zeckendorf-number-representation.md

**Comment by Durbatuluk1701** [comment]
Is this asking for the 2nd test description to be more specific?

If so would something along the lines of 'Your `zeckendorf` function should return the an array of the first `n` zeckendorf numbers' be sufficient?

**Comment by gikf** [comment]
It can be partially about 2nd test description - yes, but the main issue is to clarify challenge goal. Is it - as challenge description say - returning array of the first n or is it - as what test actually checks - returning just the single n number.
