### ISSUE TITLE
Add a display: block;

### ISSUE THREAD

**Issue by Porphyrogennitos** [freeCodeCamp/freeCodeCamp#40805]
So [here](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/make-an-image-responsive) we learn how to make an image, responsive.

[Here](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page) and specifically in User Story 8, it says that I must make my image responsive. OK, we had a tutorial so I know how to do that **BUT**:

![Screenshot_2021-01-26_171502](https://user-images.githubusercontent.com/27696433/105870236-bc477c00-6000-11eb-9ae5-f7edc3075a81.png)

How would I know that, if the tutorial doesn't have the `display: block;`?

My image was responsive but the problem was that I didn't put `display: block` because how would I know? 

Thank you for your time. I hope you add it to the tutorial.

**Comment by abmincodecreations** [comment]
can u describe with relevant links

**Comment by ieahleen** [comment]
the errors tell you what you need to change

also it is highly suggested that you use the Read-Search-Ask method

you will find other requirements to meet that where not present in the previous challenges and you will need to use Read-Search-Ask method and read carefully the errors

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by ShaunSHamilton** [comment]
A bit of context for this issue:

I followed the discussion on the Discord server, and believe that is where this came from.

The main points are:
- The Tribute Page project expects an image to be responsive
  - The tests expect the image to have `display: block`
- The Camper is not specifically taught to use `display: block` _as the way to make an image responsive_
- Therefore, the Camper relies on the test to tell them what it expects

IMO, there is little to no confusion around needing the Camper to add such a property; the tests are very explicit.

Something which could be changed is the user story, to specifically ask for something like:
> **User Story #8:** The `img` element should responsively resize, relative to the width of its parent element, and start on a new line, taking up the whole width of the parent.

This _implicitly_ signals the camper to use `display: block`.
