### ISSUE TITLE
Regular Expression: Match anything with Wildcard Period Task

### ISSUE THREAD

**Issue by abdurrahimkhan** [freeCodeCamp/freeCodeCamp#40812]
**Describe your problem and how to reproduce it:**
The task is:
Complete the regex unRegex so that it matches the strings "run", "sun", "fun", "pun", "nun", and "bun". Your regex should use the wildcard character.
// Code Section:
Now the correct code is: 
***
let exampleStr = "Let's have fun with regualr expressions!";
let unRegex = /un./;
let result = unRegex.test(exampleStr);
***
Now I tried the following code:
***
let exampleStr = "Let's have fun with regualr expressions!";
let unRegex = /un./;
let result = unRegex.test(unRegex);
***
Surprisingly, the compiler passed the task. The third line doesn't make sense as it checks on itself. Compiler should've thrown an error.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/match-anything-with-wildcard-period

**Tell us about your browser and operating system:**
* Browser Name: FireFox
* Browser Version: 18.0.2
* Operating System: Ubuntu 20.04.1 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![Screenshot from 2021-01-26 21-07-25](https://user-images.githubusercontent.com/44447280/106044033-031c9b00-6101-11eb-8e39-34c6cd49de22.png)
![Screenshot from 2021-01-26 21-07-38](https://user-images.githubusercontent.com/44447280/106044036-04e65e80-6101-11eb-9a33-73ab402a0e11.png)
![Screenshot from 2021-01-26 21-07-15](https://user-images.githubusercontent.com/44447280/106044017-ff891400-6100-11eb-94f5-dd900f3f0c37.png)

**Comment by RandellDawson** [comment]
It should not show an error nor should the tests fail because of how the tests are written.   You have stumbled upon an edge case in the tests.  The tests assume you follow the instruction of the comment `// Change this line`.  I supposed we should have put the comment `Only change this line`.

**Comment by nhcarrigan** [comment]
`Only change this line` isn't in our comment dictionary, though we could add it I believe

**Comment by RandellDawson** [comment]
That is strange.  I thought that was one of the comments.  I am really not wanting to add any more though.  Also, this is an extreme edge case.

**Comment by gikf** [comment]
This can apply to more Regular Expressions challenges, not only one with Wildcard Period

Some other options:
- Use `Change code below this line` and `Change code above this line`. In challenges, where only single line is expected to change, it might make more explicit where changes should be made.
- Remove line with `result`, for challenges not needing change in it. Method call and assigning result to, well, `result` can make impression it's being used directly for testing. Especially that in some previous and later challenges that line is indeed for changing. I guess it may be partially for convenience to show how pattern will be used, but that could be put explicitly into description or be replaced with a `console.log` call.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
