### ISSUE TITLE
Example if wrong.

### ISSUE THREAD

**Issue by joeneuman** [FreeCodeCamp/FreeCodeCamp#4081]
The description is correct for(var i = 0 yet in the example code reads for(var i = 1.

Challenge [Waypoint: Iterate Odd Numbers With a For Loop](http://freecodecamp.com/challenges/waypoint-iterate-odd-numbers-with-a-for-loop#?solution=var%20ourArray%20%3D%20%5B%5D%3B%0A%0Afor(var%20i%20%3D%201%3B%20i%20%3C%2010%3B%20i%20%2B%3D%202)%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0A%0Avar%20myArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0Aif(typeof(myArray)%20!%3D%3D%20%22undefined%22)%7B(function()%7Breturn%20myArray%3B%7D)()%3B%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = [];

for(var i = 1; i < 10; i += 2){
  ourArray.push(i);
}

var myArray = [];

// Only change code below this line.



// Only change code above this line.

if(typeof(myArray) !== "undefined"){(function(){return myArray;})();}


```

**Comment by joeneuman** [comment]
http://freecodecamp.com/challenges/waypoint-iterate-odd-numbers-with-a-for-loop

**Comment by ltegman** [comment]
Confirmed. The seed code for `ourArray` should mirror the code in the sidebar example.

**Comment by joeneuman** [comment]
Glad I could help. :+1:
