### ISSUE TITLE
Add Crowdin setup for the UI strings

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40816]
Need to add/updated the Crowdin setup for the UI strings

**Comment by raisedadead** [comment]
@RandellDawson would you be fine with taking this up?

**Comment by RandellDawson** [comment]
Sure.  I can do this.  They are all JSON files, so that will make it easier.  Do you want me to create a separate project for them?  I am thinking that is best for now.

**Comment by raisedadead** [comment]
Yes, that would be ideal, I think.
