### ISSUE TITLE
Navbar pre-loading animation

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40815]
The navbar has a pre-loading animation on our production, the upcoming new navigation needs to implement this as well.

/cc @nhcarrigan and @moT01

**Comment by ahmadabdolsaheb** [comment]
@moT01, It seems like pathName and pending is not provided to the authOrProfile as props,  so the skeletonSprite if statement does not execute.

![image](https://user-images.githubusercontent.com/4591597/106472325-9c5a0180-64b3-11eb-9e42-5e91be3f6175.png)

**Comment by raisedadead** [comment]
Mind dropping a fix?

**Comment by ahmadabdolsaheb** [comment]
working on it .

**Comment by ahmadabdolsaheb** [comment]
Just discussed this with @moT01. Since we will be showing the menu on the landing page, we would only need to pass pending to the menu component.

**Comment by ahmadabdolsaheb** [comment]
Fyi, the current setup does show the loader, but there was a loader nested inside the menu that is removed by #40864
