### ISSUE TITLE
Menu button covers logo on small screens when user is not signed in

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#40820]
<img width="245" alt="Screen Shot 2021-01-28 at 1 36 32 PM" src="https://user-images.githubusercontent.com/4591597/106133920-efac1700-6176-11eb-8d19-03f0357b0eee.png">

/cc @nhcarrigan and @moT01

**Comment by neeraj-here** [comment]
Hello, Ahmad! I want to mention that interface looks like this on my phone's screen:
![WhatsApp Image 2021-01-28 at 19 09 01](https://user-images.githubusercontent.com/64999816/106146203-67d90380-619c-11eb-97b9-03959040b9a7.jpeg)

**Comment by moT01** [comment]
How small is that screen @ahmadabdolsaheb? It should work down to 350px wide or so before that happens - which is smaller than most phones. Gets tough to fit it all in there. Curious if you have any suggestions? We could shrink the buttons, which might make them smaller than lighthouse recommends for being able to touch on phones - or just use the fcc logo without the text - or move the sign in button into the menu with the rest of the links.

Even with any of these fixes, there is a certain point at which it just doesn't fit - but one, or a combination, of these would make it work a little longer. I think I would like to just use the fcc logo without the text - that would give us quite a bit more room, and be an easy fix - although, I'm not sure Quincy would approve. Moving the sign in button down would be my next choice - that would give us a little more room - although we would probably run into the same problem, maybe at 300px or something. We could change `Sign in` to `Login` - which is two less characters to squeeze out a few more pixels.

**Comment by ahmadabdolsaheb** [comment]
We have traditionally supported down to iphone 5 320px, and as you mentioned we definitely, we need to make some compromises when we go that small.

I think these are our options:

1) hide the sign up in the menu
2) go with small version of the logo
3) have the main navigation in two rows: row one) freecodecamp logo centered, row two) menu, sign in button. ( I don't think this would be optimal, since we should not take vertical real-estate in a screen that small.)

Even if we go hamburger menu for menu button, there would still be some overlap for 320px. 

At some point we had three rows of navigation for the forum on super small screens :)
Here is a screenshot of the forum nav grid from one of our previous iterations.


![image](https://user-images.githubusercontent.com/4591597/106189218-07a48a80-61b9-11eb-930e-78e0c49cd356.png)

**Comment by ahmadabdolsaheb** [comment]
> Hello, Ahmad! I want to mention that interface looks like this on my phone's screen:
Hi @neeraj-here, should have mentioned, but the issue is regarding the next branch that will be merged with master in near future.
