### ISSUE TITLE
Superblock projects cards improvements

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#40829]
On the next-i18n-client branch we are showing the status of each certification page. It might be more useful to have a claim/show certification button instead so users don't have to go to the settings page to claim/show their certifications.

<img width="823" alt="Screen Shot 2021-01-29 at 11 51 31 AM" src="https://user-images.githubusercontent.com/4591597/106253313-5dfce200-6228-11eb-804f-bd101bf4effe.png">

**Comment by raisedadead** [comment]
Is this a duplicate or extension of https://github.com/freeCodeCamp/freeCodeCamp/issues/38569? Should we consolidate the discussion there instead?
