### ISSUE TITLE
Python for Everybody - Conditional Execution: Syntax Error

### ISSUE THREAD

**Issue by mtrivera** [freeCodeCamp/freeCodeCamp#40827]
**Describe your problem and how to reproduce it:**
All possible solutions have `0 == x`, but that is incorrect. Python variable names can contain digits, but not the first one.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/conditional-execution

**Recommended fix, suggestions (how would you update it?):**
Change each possible solution from `0 == x`to `x == 0`

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fcc-python](https://user-images.githubusercontent.com/10368105/106196180-f5e5c780-6165-11eb-88dc-9176a0c06081.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

I do not understand the issue. When i run the code, I get a response:
![image](https://user-images.githubusercontent.com/51722130/106198932-97900780-61ac-11eb-9fa0-0bd985319f28.png)

**Comment by ieahleen** [comment]
> Python variable names can contain digits, but not the first one.

there is not a rule that the left hand side of a comparison must be a variable
that is valid code

**Comment by mtrivera** [comment]
This is targeted at beginners, so I thought it should be more readable. My two cents.
