### ISSUE TITLE
Simplify dependencies between services

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#40834]
Following on from https://github.com/freeCodeCamp/freeCodeCamp/pull/40703 the different 'services' i.e. the curriculum, client and api need to be loosely coupled.  For instance, it's fine to build the curriculum into a JSON file and make that available to the api.  It's not good to call curriculum functions from the api, since that means the curriculum packages have to be served with the api.

A (somewhat) reasonable dependency structure is as follows

| directory | depends on |
| - | - |
| /client | in principle anything, since it all gets bundled into /public, but ideally only /utils and /config |
| /api-server | utils, config | 
| /curriculum | in principle anything, since it is only used during the initial build step | 
| /utils | only root prod dependencies |
| /config | only root prod dependencies | 

For simplicity's sake, I think the structure should be:

| directory | depends on |
| - | - |
| all of them | utils, config, root prod dependencies |

and their own packages, of course.  This far, far easier to understand, build and maintain, but we would have to do a bit of work to make sure the client still reloads quickly whenever a challenge changes.

@freeCodeCamp/staff any thoughts?

**Comment by raisedadead** [comment]
Is this a duplicate or extention of https://github.com/freeCodeCamp/freeCodeCamp/issues/38626? Should we consolidate the discussion there instead?

**Comment by ojeytonwilliams** [comment]
It's worse than that, I'd completely forgotten about that issue 🤦‍♂️ I'll just copy over a summary of this into the older one.
