### ISSUE TITLE
imprecisions in "How Hex Code Colors Work" article

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40845]
**Describe your problem and how to reproduce it:**
This sentence:
> Hexidecimal, as the name suggests, is a way of encoding a base 16 number system. Decimal is base 2, and our regular system is base 10.

Hex***a***decimal, not Hex***i***decimal.
Binary is base 2, not decimal - decimal is out regular system

> Hexadecimal uses the same numerals as the regular system for the first 10 numbers (so 1 – 10) and then swaps to letters, so the numbers 11 – 15 are encoded using the letters A – F

hexadecimal uses numbers from 0-9, 10 is written as `A`

> Binary numbers are commonly expressed as a power of 2, and 16 is 2^3.

2^3 is 8, 2^4 is 16

> (Incidentally, the reason that 255 is the maximum value is also related to the ease of using this value [or, actually, 256] in binary. 256 is 2^7

255 is the maximum value, there are 256 values because 0 is the first number used
2^7 is 128, 2^8 is 256

> The two first characters of this hex color code (and, in fact, all hex color codes) refer to the red component, and here the value is 256

FF is 255, not 256

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/how-hex-code-colors-work-how-to-choose-colors-without-a-color-picker/

**Recommended fix, suggestions (how would you update it?):**
Just the corrections above, it really needs so to avoid confusion for people that have just met this side of maths

**Comment by nhcarrigan** [comment]
@scissorsneedfoodtoo could you take a look at this when you have a chance?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting these issues, @ieahleen, and for your helpful suggestions. We've had a few emails about this article, but you caught a few other issues like that first misspelling.

Thanks again, and please let us know if you notice anything else.
