### ISSUE TITLE
Chat layout issue increasing font-size

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40846]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
I have increased default font-size for my browser, and now the icons in the top left corners overlap with the main part of the page.

**To Reproduce**
Google Chrome, go to Settings -> Appearance
Change font size to "really big" (? - the highest font-size)

Also if setting the side bar appearence  to extended it gets really crowded

**Screenshots**
Icons overlapping with content:
![image](https://user-images.githubusercontent.com/26656284/106383191-cf719780-63c4-11eb-97f7-3a5acade93ab.png)

![image](https://user-images.githubusercontent.com/26656284/106383199-d7313c00-63c4-11eb-8e49-f57e05010333.png)

Crowded side-bar with extended appearence:
![image](https://user-images.githubusercontent.com/26656284/106383327-8a019a00-63c5-11eb-9772-51e7173092a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 88.0.4324.104 (Build ufficiale) (a 64 bit)

**Comment by Nicke7117** [comment]
Could I work on this issue?

**Comment by moT01** [comment]
Fixed 👍
