### ISSUE TITLE
thumbnails on news are cut on mobile

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40858]
**Describe the bug**
On mobile there are some layout issues on \news
 - the thumbnails are cut, this is moticeable where there is text in the image, there are words being stolen letters
 -  with long author names, the publication date gets moved out of screen

**To Reproduce**
Go to freecodecamp.org/news with a small enough screen

**Expected behavior**
Seeing the whole thing

**Screenshots**
![D73C48A2-E005-42EA-8DF9-BA6AD9B2DEE5](https://user-images.githubusercontent.com/26656284/106470669-10d77500-64a1-11eb-9cfd-359587693adf.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2016
 - OS: iOS 14.3
 - Browser: Google Chrome
 - Version: 87.0.4280.77

**Comment by lucievr** [comment]
Happy to work on this issue

**Comment by ahmadabdolsaheb** [comment]
I could not reproduce it, but most likely this is causing it:   [object-fit: cover;](https://github.com/freeCodeCamp/news-theme/blob/d1c510d871784b733f30c325682e2638177d33c0/assets/css/screen.css#L457)

This one is in place to make sure taller/wider images adhere to the size of their containers and follow the grid.

**Comment by lucievr** [comment]
Thanks, @ahmadabdolsaheb! 

I had a quick look earlier and was able to reproduce this bug on mobile. Will dig into this later today.
