### ISSUE TITLE
green flame icon still in use

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40854]
if I link to contribute.freecodecamp.org in the forum, the embed that appears has still the old green icon that was substituted with the one with the new color scheme:
![image](https://user-images.githubusercontent.com/26656284/106453553-ca2a5080-6489-11eb-8658-511d073c0c0f.png)

**Comment by ahmadabdolsaheb** [comment]
Thanks for letting us know.
We have a dedicated issue for the older icons. It would be great if you could update https://github.com/freeCodeCamp/freeCodeCamp/issues/38540 with instances of the green logo.

I am closing this issue in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/38540
let me know if this issue has been closed by mistake.
