### ISSUE TITLE
In article "10 to the power of 0" some snippets and text overflow on mobile

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40859]
**Describe the bug**
In this article there are some maths and text snippets that can't be seen whole

**To Reproduce**
go to https://www.freecodecamp.org/news/10-to-the-power-of-0-the-zero-exponent-rule-and-the-power-of-zero-explained/ with a small enough screen

**Expected behavior**
See all the text

**Screenshots**
![231C5120-991E-4A52-B539-76FE37B3C57D](https://user-images.githubusercontent.com/26656284/106471584-12556d00-64a2-11eb-85f6-b7bab34e460a.png)
![58F3C232-C349-4DB7-A8AF-7A19254C8A75](https://user-images.githubusercontent.com/26656284/106471585-12ee0380-64a2-11eb-9c3d-104bbb0885d3.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2016
 - OS: iOS 14.3
 - Browser: Google Chrome
 - Version: 87.0.4280.77

**Additional context**

**Comment by neeraj-here** [comment]
I confirm this issue. I face it on my smartphone as well. Few long sentences and calculations do get hidden. Also, there isn't any option to scroll the screen sideways, not allowing the user to read the content.

**Comment by neeraj-here** [comment]
I offer my help in resolving this issue. Please guide me thru the way.

**Comment by nhcarrigan** [comment]
Hey there @neeraj-here,

This is an issue with a published news article, so our editorial team will need to take a look at this. If you are interested in contributing to the freeCodeCamp code base, we recommend reviewing our [contributing guidelines](https://contribute.freecodecamp.org), then looking for issues labelled `help wanted` or `first timers only`.

**Comment by nhcarrigan** [comment]
@scissorsneedfoodtoo @ahmadabdolsaheb is this something we would need to edit in the article text? Or do we need to reduce the font size through the news theme?

**Comment by lucievr** [comment]
Sorry to jump in, @nhcarrigan... Just wanted to say this should all be fixable by changing a few CSS properties in the news theme (there was an issue with no word breaks, whitespace wrap, content min-width set to 100% etc.)

Just played with it in browser dev tools and it looks like this:

![screen1](https://user-images.githubusercontent.com/46979603/106683279-838d4100-65c4-11eb-8c9e-72501b2c0d89.jpg)

![screen2](https://user-images.githubusercontent.com/46979603/106683360-a4559680-65c4-11eb-855f-3f1316844c5e.jpg)

**Comment by ahmadabdolsaheb** [comment]
It must be the theme. @lucievr, could you create a pull request with your solution?

**Comment by lucievr** [comment]
Sure – will do, @ahmadabdolsaheb
