### ISSUE TITLE
using the forum on mobile many dropdown menu items are inaccessible

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#40861]
**Describe the bug**
Using the forum I can't log out in portrait mode, and in landscape mode only the first button of the User Menu, "Summary", is accessible, I have tried swiping to see if it moves and show the others, but it doesn't, only what is visible is usable.

**To Reproduce**
Steps to reproduce the behaviour:
use the forum with a small enough screen and open the User menu

**Expected behavior**
Being able to access all the menu items

**Screenshots**
![69ACC276-BDDF-4421-B8B8-173C906DB094](https://user-images.githubusercontent.com/26656284/106473073-a6740400-64a3-11eb-9863-7ee3eb0b74c8.png)
![B82B9B1D-BDAF-429C-8D0A-397A8C0EBAD5](https://user-images.githubusercontent.com/26656284/106473081-a7a53100-64a3-11eb-851d-129955346b90.png)

**Device**:
**Smartphone**:

Device: iPhone SE 2016
OS: iOS 14.3
Browser: Google Chrome
Version: 87.0.4280.77

**Comment by ahmadabdolsaheb** [comment]
I double checked that and you are right, I cannot scroll down. Could you please try it with another discourse instance such as [this one](https://forum.ghost.org/) and see if you get similar results.

**Comment by ieahleen** [comment]
I've tried on meta.discourse.org and community.postcrossing.com, where I already had an account - it seems it's a general discourse issue

on desktop if you reduce the window a scrollbar appear in the dropdown menu

I don't see it mentioned in https://meta.discourse.org/c/bug/1 - should I open there a topic?

**Comment by raisedadead** [comment]
> should I open there a topic?

Yes please.

**Comment by ieahleen** [comment]
I have opened a topi on discourse meta forum: https://meta.discourse.org/t/dropdown-user-menu-is-not-accessible-on-small-screens/178244

**Comment by ieahleen** [comment]
There was an update from discourse, they are working on fixing the issue, so I'm closing this.
