### ISSUE TITLE
QA Functional coding challenges test bug

### ISSUE THREAD

**Issue by rookiebehaviour** [freeCodeCamp/freeCodeCamp#40868]
There's a bug in FCC testing on QA Functional testing with Chai. I have the right code that passes 4/5 tests. The first test just simply verifying that the other tests passed (hince the 4/5 passing). So I passed all the tests except the all tests pass... Please see code below:
```
// #2 (PASSES FCC TEST)
test("Test GET /hello with your name", function (done) {
      chai
        .request(server)
        .get("/hello?name=Jacqueline")
        .end(function (err, res) {
          assert.equal(res.status, 200);
          assert.equal(res.text, "hello Jacqueline");
          done();
        });
    });
    // #3 (SINGLE QUOTES, DOESN'T PASS FIRST FCC TEST, PASSES ALL OTHERS)
    test('send {surname: "Colombo"}', function (done) {
      chai
        .request(server)
        .put("/travellers")
        .end(function (err, res) {
          assert.equal(res.status, 200);
          assert.equal(res.type, 'application/json');
          assert.equal(res.body.name, 'Cristoforo');
          assert.equal(res.body.surname, 'Colombo');
          done();
        });
    });
    // #4 (DOUBLE QUOTES, DOESN'T PASS FIRST FCC TEST, PASSES ALL OTHERS)
    test('send {surname: "da Verrazzano"}', function (done) {
      assert.equal(res.status, 200);
      assert.equal(res.type, "application/json");
      assert.equal(res.body.name, "Giovanni");
      assert.equal(res.body.surname, "da Verrazzano")

      done();
    });
  });
});
```

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 88.0.4324.104 (Official Build) (64-bit)
* Operating System: Windows10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![FCC Testing bug](https://user-images.githubusercontent.com/75797321/106532297-eea02000-64bd-11eb-96e6-a7528057a045.PNG)

**Comment by rookiebehaviour** [comment]
FYI: this was using your project built in repl.it

**Comment by ShaunSHamilton** [comment]
Hello there,

In general, I recommend you open a topic on the forum, for something like this, as it is likely an issue with your code, and not the main codebase. Once it has been determined that the issue is in fact on freeCodeCamp's side, an issue may be opened.

**Note**: the _"All tests should pass"_ test is referring to your app's tests, not the tests on freeCodeCamp's side.

When you open a topic on the forum, please include a link to your project **code**. Thanks
