### ISSUE TITLE
Chinese Certificate verification URL incorrect

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#40867]
**Describe the bug**

The English and Espanol certifications have the correct "verify this certification at" URL, but the Chinese certification links to the `www.freecodecamp.dev` domain.

**To Reproduce**
1. Go to https://www.freecodecamp.org/certification/nhcarrigan/responsive-web-design and see the correct verify URL
2. Go to https://www.freecodecamp.org/espanol/certification/nhcarrigan/responsive-web-design and see the correct verify URL
3. Go to https://chinese.freecodecamp.org/certification/nhcarrigan/responsive-web-design and see the **incorrect** verify URL.

**Expected behavior**

The Chinese certification should correctly use `chinese.freecodecamp.org` for the verification url.

**Comment by ojeytonwilliams** [comment]
Nice catch, Nick.  That bit's hard-coded.

**Comment by nhcarrigan** [comment]
Related #41000

**Comment by Sboonny** [comment]
I am wondering if [PR 46220](https://github.com/freeCodeCamp/freeCodeCamp/pull/46220), closes this.

**Comment by ojeytonwilliams** [comment]
This will get fixed by the move from `chinese.freecodecamp.org` to `www.freecodecamp.org/chinese`, primarily by the PR I've set to close this (technically the NGINX config needs changing, too)
