### ISSUE TITLE
the system won't let me advance to the next challenge

### ISSUE THREAD

**Issue by stellarnode** [FreeCodeCamp/FreeCodeCamp#4087]
Hi All!

My code seems to give the right answers. And all the checks are green but in the Map the challenge is still not marked as completed.

What could be the reason?

The code I wrote was the following:
```
function palindrome(str) {
    var splitStr;
    var backward = Array();
    var len = str.length;
        
    str = str.toLowerCase();
    str = str.replace(/[^a-z]+/g, "");
    splitStr = str.split("");
        
    for (i = len - 1; i >= 0; i--) {
        backward.push(splitStr.pop());
    }
            
    if (str === backward.join("")) { 
      return true;
  } else {
      return false;
  }
}

palindrome("race car");
```

Thanks in advance for your help!

**Comment by ltegman** [comment]
There's a lot of test for this challenge! Scroll the sidebar to the bottom and you'll see that your code does not pass the second to last test :smile:

Closing as not an issue with the tests.

Thanks and happy coding!
