### ISSUE TITLE
[.dev] Selected text has same background as the rest of the page

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40876]
If I try to select text with my mouse so I can copy/paste it or something - the selected text has the same background as the rest of the page. Making it difficult to see what is selected, and frustrating to try and select, well anything.

![Feb-02-2021 11-03-51](https://user-images.githubusercontent.com/20648924/106635393-644fce80-6546-11eb-9e7d-9b831e1e5929.gif)

This seems to occur across the entire site. Perhaps it was intentional or something, but I don't think it's a good ux. Note: the text does actually get selected, so you can still copy/paste it.

Tested on Chrome and Firefox

**Comment by ojeytonwilliams** [comment]
Good catch.  It'll be this PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/40461 which didn't scope the change to challenge descriptions.  I'll put together a quick fix.
