### ISSUE TITLE
Landing page icons are different heights

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#40874]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
The heights of the SVG files on the landing page vary, which causes the certification chart to look inconsistent.

**To Reproduce**

<img width="946" alt="zoom_floating_video_window_and_Learn_to_Code_—_For_Free_—_Coding_Courses_for_Busy_People" src="https://user-images.githubusercontent.com/985197/106614760-52affc00-6531-11eb-8e9f-d2d39e632c58.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 88.0.4324.96 (Official Build) (x86_64)

**Comment by RandellDawson** [comment]
Hi Quincy, I let @ahmadabdolsaheb know about this already.

**Comment by ahmadabdolsaheb** [comment]
added in min height, so #40883 should take care of it.
