### ISSUE TITLE
Scientific Computing with Python: Probability Calculator: improving problem statement

### ISSUE THREAD

**Issue by uptonnm** [freeCodeCamp/freeCodeCamp#40886]
**Describe your problem and how to reproduce it:**
The unit tests for the probability calculator are broken and cannot be passed with an actual solution for the project.

The test for test_prob_experiment performs two tests. One requires the drawn balls to be {"blue":2,"green":1} - three balls - but draws four balls. The other similarly requires six balls (2 yellow, 3 blue, 1 test) but draws 20. 

The unit test in question:
```py

def test_prob_experiment(self):
    hat = prob_calculator.Hat(blue=3,red=2,green=6)
    probability = prob_calculator.experiment(hat=hat, expected_balls={"blue":2,"green":1}, num_balls_drawn=4, num_experiments=1000)
    actual = probability
    expected = 0.272
    self.assertAlmostEqual(actual, expected, delta = 0.01, msg = 'Expected experiment method to return a different probability.')
    hat = prob_calculator.Hat(yellow=5,red=1,green=3,blue=9,test=1)
    probability = prob_calculator.experiment(hat=hat, expected_balls={"yellow":2,"blue":3,"test":1}, num_balls_drawn=20, num_experiments=100)
    actual = probability
    expected = 1.0
    self.assertAlmostEqual(actual, expected, delta = 0.01, msg = 'Expected experiment method to return a different probability.')`

```
**Add a Link to the page with the problem:**
 [https://repl.it/github/freeCodeCamp/boilerplate-probability-calculator](https://repl.it/github/freeCodeCamp/boilerplate-probability-calculator)

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 84.0.1(64 bit)
* Operating System: Win10 home 64 bit v2004 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by gikf** [comment]
Could you be more specific why this makes tests broken? Experiment is supposed to determine probability of drawing specific balls - `expected_balls` - from the `hat`  when drawing `num_balls_drawn` balls from it. This doesn't seem to be incorrect.

**Comment by uptonnm** [comment]
In combination with the problem statement section describing `expected_balls`:

```
* `expected_balls`: An object indicating the exact group of balls to attempt to draw from the hat for the experiment. For example, to determine the probability of drawing 2 blue balls and 1 red ball from the hat, set `expected_balls` to `{"blue":2, "red":1}`
```

'Exact group' indicates `expected_balls` is not a subset - that `expected_balls` and the result are identical. A set of four balls cannot be identical to any set of three balls, and a set of twenty balls cannot be identical to a set of six balls.

So either the tests are broken, or the problem statement doesn't align with the intent.

**Comment by gikf** [comment]
Would you have suggestions how wording can be improved here to avoid such confusion?

**Comment by uptonnm** [comment]
Sure - how about:

> * `expected_balls`: An object indicating a set or subset of balls to attempt to draw from the hat for the experiment. For example, to determine the probability of drawing at least 2 blue balls and at least 1 red ball from the hat, set `expected_balls` to `{"blue":2, "red":1}`

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. However, I am closing this issue as stale. That is, I have not seen this confusion come up on the forum, nor elsewhere on the platform.

Personally, see no issue in the wording of the user story. This is one clause: _"exact group of balls to attempt to draw"_ - the group is referring to the _group_ you draw, and therefore should be _exact_. It is not referring to the hat set.

If you are still unsure, I recommend opening a topic on the [forum](https://forum.freecodecamp.org/).
