### ISSUE TITLE
Custom company logos for the Chinese landing page.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#40890]
The Chinese landing page should have the following logos in order:

Apple, Google, Microsoft, Alibaba and Tencent

**Comment by naveen8801** [comment]
Hi @ahmadabdolsaheb , i wanna work on it , can you help me in getting started with this issue !

**Comment by ahmadabdolsaheb** [comment]
Sure, we would like to replace Amazon and Spotify logos with Alibaba and Tencent when the clientLocale === 'chinese'.
Here is where the logos are displayed. Please follow the path to see where they are located. We would like similar svg react components for Alibaba and Tencent.

Then we would pull clientLocale similar to the following and display the above mentioned logos when the client is chinese.
https://github.com/freeCodeCamp/freeCodeCamp/blob/c0e24d735caa04e8a1874aef82fdc67b076fdee8/client/src/components/profile/components/Camper.js#L19

**Comment by naveen8801** [comment]
Thanks @ahmadabdolsaheb  :-)

**Comment by naveen8801** [comment]
Dear @ahmadabdolsaheb , i have followed all the steps for setting up locally but getting this error while running ' npm run develop ' . 

Error in "F:\open source\freeCodeCamp\client\node_modules\gatsby-plugin-manifest\gatsby-node.js":
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- F:\open source\freeCodeCamp\client\node_modules\sharp\lib\constructor.js
- F:\open source\freeCodeCamp\client\node_modules\sharp\lib\index.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby-plugin-manifest\safe-sharp.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby-plugin-manifest\gatsby-node.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\services\initialize.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\services\index.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\state-machines\develop\services.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\state-machines\develop\index.js
- F:\open source\freeCodeCamp\client\node_modules\gatsby\dist\commands\develop-process.js
- F:\open source\freeCodeCamp\client\.cache\tmp-5024-mcD7XsGWBxgh

**Comment by ahmadabdolsaheb** [comment]
Are you getting that before implementing the changes? I suggest following https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally carefully to get he repo running locally, and letting us know about related issues here: https://chat.freecodecamp.org/channel/contributors.

I suspect there is a mismatch your machine's and the required node/npm versions.

**Comment by naveen8801** [comment]
@ahmadabdolsaheb  yaa  , i am running it for first time :-(

**Comment by moT01** [comment]
How do you create or find the svg's for those @ahmadabdolsaheb?

**Comment by ahmadabdolsaheb** [comment]
We followed the following steps for the other svgs:
1) We found the images for logos and turned them into svgs if necessary.
2) Optimize the size of svgs using an online tool ( there are a lot of them, [here](https://www.svgminify.com/) is one).
3) Rectified the optimized svg.
