### ISSUE TITLE
Rename all default branches to main across the fCC organization

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40895]
This issue is to keep track of switching all our repo's to use `main` as the default branch - unless there's maybe a special case or something. The list below is all our non archived repos - perhaps a few of them could be archived. This issue replaces/should take care of https://github.com/freeCodeCamp/freeCodeCamp/issues/39098 and https://github.com/freeCodeCamp/freeCodeCamp/issues/38987

Many of the boilerplates use `gomix` as the default branch, we can rename those to `main` as well. There shouldn't be any problems with links on challenges that use them - replit clones the default branch, so the links should still work without modification.

References fixed means that any references to `master` or `slave` in documentation, readme's, or other files are removed or changed to `main` or `primary` and `replica` if possible - or changed to whatever is appropriate for the context. Some other terms we could change while looking over the repos include `whitelist` and `blacklist` - These can be replaced with `allowlist` and `blocklist`. I think that if a quick search of these terms in a repo yields nothing, the code is probably fine - but feel free to leave a message if find something you think you be brought up.

Feel free to add a checkmark next to any repo if you've looked it over and the issue is fixed - or leave some notes or make a PR if there's problems.

<details>
<summary>Details</summary>

| Repo | Branch Renamed | References Fixed | Notes |
| - | - | - | - |
| freeCodeCamp | ✔️ | | |
| boilerplate-project-timestamp | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-sudoku-solver | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-secure-real-time-multiplayer-game | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-metricimpconverter | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-messageboard | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-library | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-issuetracker | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-headerparser | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-filemetadata | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-exercisetracker | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-american-british-english-translator | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-mongomongoose | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-mochachai | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-mean-variance-standard-deviation-calculator | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-infosec | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-express | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-bcrypt | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-advancednode | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-stockchecker | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-project-urlshortener | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-npm | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-budget-app | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-sea-level-predictor | ✔️ | ✔️ | Reviewed by @moT01 |
| boilerplate-probability-calculator | ✔️ | | |
| boilerplate-medical-data-visualizer | ✔️ | | |
| boilerplate-polygon-area-calculator | ✔️ | | |
| boilerplate-arithmetic-formatter | ✔️ | | |
| boilerplate-neural-network-sms-text-classifier | ✔️ | | |
| boilerplate-linear-regression-health-costs-calculator | ✔️ | | |
| boilerplate-cat-and-dog-image-classifier | ✔️ | | |
| boilerplate-time-calculator | ✔️ | | |
| boilerplate-demographic-data-analyzer | ✔️ | | |
| boilerplate-page-view-time-series-visualizer | ✔️ | | |
| boilerplate-book-recommendation-engine | ✔️ | | |
| boilerplate-SHA-1-password-cracker | ✔️ | | |
| boilerplate-port-scanner | ✔️ | | |
| boilerplate-rock-paper-scissors | ✔️ | | |
| demo-projects-nginx-config | | | |
| demo-projects | | | |
| ghost-config | | | |
| news-translation | | | |
| news-theme | | | |
| infra | ✔️ | | |
| devdocs | ✔️ | | |
| crowdin-config | | | |
| coderadio-client | ✔️ | | |
| nginx-config | | | |
| how-to-contribute-to-open-source | | | |
| error-pages | | | |
| cdn | ✔️ | | |
| scripts | ✔️| | |
| forum-theme | | | |
| chat-config | | | |
| design-style-guide | | | |
| CurriculumExpansion | | | |
| chapter | | | |
| testable-projects-fcc | | | |
| 100DaysOfCode-twitter-bot | | | |
| template | | | |
| auth0-templates | | | |
| freeCatPhotoApp | | | |
| forum-users-nav | | | |
| fcc-express-bground-pkg | | | |
| forum-banner | | | |
| react-calendar-heatmap | | | |
| videos-translation | | | |
| netlify-redirects | | | |
| client-config | | | |
| FreeCodeCampTriviaQuiz | | | |
| youtube-tutorials | | | |
| loopback-component-passport | | | |
| ProjectReferenceData | | | |
| eslint-config-freecodecamp | | | |
| open-data | | | |
| react-bootstrap | | | |
| react-notification | | | |
| sendgrid-email-blast | ✔️ | | |
| store.js | | | |
| cz-freecodecamp | | | |

</details>

**Comment by moT01** [comment]
I left the archived repos off the initial list because, I believe, you have to unarchive them to rename the branch. Not too difficult, but I didn't think it was worth it. Your call.

**Comment by ShaunSHamilton** [comment]
- The `CurriculumExpansion` repo should just need the currently open PRs to retarget.
- The `design-style-guide` repo should be easy, because it is deployed with GitHub Pages (just change  the default in the settings)
- Should the `videos-translation` repo be archived?
- `fcc-express-bground-pkg` might be easy, because we "recently" published it as an [NPM package](https://www.npmjs.com/package/fcc-express-bground). However, I believe old projects still point to the `master` branch - only an issue, if the project is ever re-built (`npm i`)
- The `forum-banner` repo might be unused. @raisedadead disabled it on the forum. We can archive?

**Comment by ojeytonwilliams** [comment]
@raisedadead for https://github.com/freecodecamp/client-config I believe this can be changed unless you're doing something fancy in the new devops approach.  Right now we just clone the repo when needed.

**Comment by raisedadead** [comment]
> The forum-banner repo might be unused. @raisedadead disabled it on the forum. We can archive?

I have renamed this and re-installed the component on the forum. Yes - this can be archived. We probably never need to change anything in the code. Thanks for looking this up.

> I believe this can be changed unless you're doing something fancy in the new devops approach.

I have a job or two on the housekeeping instance and pipelines that I need to check but you are right. Thanks for looking this up. I will take care of it.

**Comment by raisedadead** [comment]
Just a few more to go...

**Comment by moT01** [comment]
demo-projects ✅

**Comment by raisedadead** [comment]
This has been taken care off except the two repos which are client-config and the error-pages repo, which will be handled when we move to containers cause those repos will be archived.
