### ISSUE TITLE
It lets me pass when it shouldn't 

### ISSUE THREAD

**Issue by jebalert** [FreeCodeCamp/FreeCodeCamp#4089]
Challenge [Waypoint: Inherit Styles from the Body Element](http://www.freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%20%0A%20%20%7D%0A%20%20%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch1%3EHello%20World%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: green;
    font-family: Monospace;
    color: green;
   
  }
  

</style>

<h1>Hello World</h1>
```

**Comment by bugron** [comment]
@jebalert thanks for posting this issue!
Your code is correct and passes all the tests. Not sure what is this issue about so I'll close it. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
