### ISSUE TITLE
contribute.freecodecamp.org meta still uses old logo / color scheme

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#40891]
I noticed when tweeting https://contribute.freecodecamp.org/ that Twitter was completing the card with our old logo and color scheme. We should update this when we have time.

<img width="761" alt="_42__Soneca_on_Twitter____ossia__EstefaniaCassN_Where_do_I_go_if_I_want_to_help_translate_freeCodeCamp_to_Portuguese_____Twitter" src="https://user-images.githubusercontent.com/985197/106771847-0a620e00-6605-11eb-95e8-c085faeecfa9.png">

**Comment by nhcarrigan** [comment]
Hmm this should have been resolved in #40863 - I'll dig in to it today.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/106772365-c830d080-65f4-11eb-99c6-50e0ff0787c7.png)

I validated with Twitter's developer tools and it is fetching the indigo version correctly - it may have been a cached version of the embed that they were using.

![image](https://user-images.githubusercontent.com/63889819/106772467-e4cd0880-65f4-11eb-8ad6-afb264478ff1.png)

Should be updated now, though - would you mind trying again?

**Comment by moT01** [comment]
I see the indigo version as well when I tweet.
