### ISSUE TITLE
Client Console Errors

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#40892]
To begin: I am seeing these on a GitPod instance. So, your kilometerage may vary.

<details>
  <summary>layouts/Default.js</summary>

```
Warning: Failed prop type: Invalid prop `children` supplied to `DefaultLayout`, expected a ReactNode.
    in DefaultLayout
    in withI18nextTranslation(DefaultLayout)
    in Connect(withI18nextTranslation(DefaultLayout))
    in RouteHandler
    in Context.Provider
    in div
    in FocusHandlerImpl
    in Context.Consumer
    in FocusHandler
    in Context.Provider
    in RouterImpl
    in Context.Consumer
    in Location
    in Context.Consumer
    in Router
    in Context.Provider
    in ServerLocation
    in Context.Provider
    in I18nextProvider
    in Provider
```
</details>

<details>
<summary>Mysterious ShadowPortal</summary>

```
Warning: Expected server HTML to contain a matching <span> in <div>.
    in span (created by ShadowPortal)
    in ShadowPortal (created by Indicator)
    in Indicator (created by LoadingIndicatorEventHandler)
    in LoadingIndicatorEventHandler (created by _default)
    in ConditionalFastRefreshOverlay (created by _default)
    in _default
```
</details>

<details>
  <summary>Found in Settings page</summary>

```
Warning: Expected server HTML to contain a matching <div> in <div>.
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by Settings)
    in Settings (created by HotExportedSettings)
    in AppContainer (created by HotExportedSettings)
    in HotExportedSettings (created by PageRenderer)
    in div (created by DefaultLayout)
    in InstantSearch (created by InstantSearchRoot)
    in InstantSearchRoot (created by withI18nextTranslation(InstantSearchRoot))
    in withI18nextTranslation(InstantSearchRoot) (created by Connect(withI18nextTranslation(InstantSearchRoot)))
    in Connect(withI18nextTranslation(InstantSearchRoot)) (created by Context.Consumer)
    in Location (created by WithInstantSearch)
```
</details>

<details>
  <summary>Refreshed page on '/learn'</summary>

```
Warning: Prop `aria-current` did not match. Server: "null" Client: "page"
    in a (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Link (created by GatsbyLink)
    in GatsbyLink (created by Context.Consumer)
    in Location (created by GatsbyLinkLocationWrapper)
    in GatsbyLinkLocationWrapper (created by ForwardRef)
    in ForwardRef (created by Link)
    in Link (created by UniversalNav)
    in div (created by UniversalNav)
    in nav (created by UniversalNav)
    in UniversalNav (created by Header)
    in header (created by Header)
    in Header (created by DefaultLayout)
    in div (created by DefaultLayout)
    in InstantSearch (created by InstantSearchRoot)
    in InstantSearchRoot (created by withI18nextTranslation(InstantSearchRoot))
```
</details>
<details>
<summary>Opening a Python Challenge</summary>

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').
www-widgetapi.js:629 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://8000-cc38e06f-dfac-408b-b1b3-a12dc0c5e62c.ws-eu03.gitpod.io').
```
</details>

Quick mention: I do have my cache disabled.

Hope this is quick to resolve

**Comment by nhcarrigan** [comment]
> So, your kilometerage may vary.

This made me lol. 🙂

**Comment by nhcarrigan** [comment]
So I spun up a GitPod instance using the link on our README:

Encountered no errors:
![image](https://user-images.githubusercontent.com/63889819/107106166-23beb200-67df-11eb-9326-586a3a24d758.png)


Visited `/learn`, refreshed the page. Visited a couple of Python challenges. Visited settings, toggled a few. Could not get any errors to generate.

**Comment by ShaunSHamilton** [comment]
@nhcarrigan The errors are from the browser console?

**Comment by nhcarrigan** [comment]
In the browser console, I get lots of:
<details>
<summary>WillRecieveProps is deprecated</summary>

![image](https://user-images.githubusercontent.com/63889819/107122534-17713e00-684d-11eb-8faa-b427bb156708.png)

</details>

<details>
<summary>AdBlocker at work?</summary>

![image](https://user-images.githubusercontent.com/63889819/107122592-68813200-684d-11eb-9a68-654b03281684.png)

</details>

**Comment by ShaunSHamilton** [comment]
> AdBlocker at work?

The google stuff, yes. The `socket.io` errors are specific to GitPod's setup, and I have brought it up with them, because it affects debugging through things like the Redux DevTools

---

From main, when I open it in GitPod (only navigated to `/`):
![image](https://user-images.githubusercontent.com/51722130/107122807-d8b1a700-6891-11eb-8af9-503b2386a917.png)

Any ideas why it might just be my side?

**Comment by nhcarrigan** [comment]
> Any ideas why it might just be my side?

Kilometrage may vary? 😅 

I'm not sure - I'll poke around at it this weekend and see if I can repro.

**Comment by raisedadead** [comment]
Quick sanity check: have you seen any of this on the staging site?

**Comment by ShaunSHamilton** [comment]
@raisedadead No, I have not seen these on staging.

The only errors I get on staging are:
- Algolia complaining
- `www-widgetapi.js:629 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://www.freecodecamp.dev').` - on a Python challenge

I am happy closing this, and just keeping an eye out, if anything comes to fruition.
