### ISSUE TITLE
Redux: Use const for Action Types - More Comments Needed

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#40903]
**Describe your problem and how to reproduce it:**
Lines 32 and 38 of this challenge need the comments ` // Change this line`.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/redux/use-const-for-action-types
See also
https://forum.freecodecamp.org/t/redux-use-const-for-action-types-error/444251

**Tell us about your browser and operating system:**
N/A

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/25011573/106816656-eddcca80-6632-11eb-9e85-c058d4cadc14.png)

**Comment by RandellDawson** [comment]
At this point in the curriculum, I would prefer not to use `// Change this lane` as it feels like it makes the challenge too easy.  How about the following:
```js
// Change code below this line
const loginUser = () => {
  return {
    type: 'LOGIN'
  }
};

const logoutUser = () => {
  return {
    type: 'LOGOUT'
  }
};
// Change code above this line
```

**Comment by jeremylt** [comment]
Good point. That seems reasonable to me. So perhaps
```
// Change code below this line

// Change code above this line

const defaultState = {
  authenticated: false
};

const authReducer = (state = defaultState, action) => {
// Change code below this line
  switch (action.type) {
    case 'LOGIN':
      return {
        authenticated: true
      }
    case 'LOGOUT':
      return {
        authenticated: false
      }
    default:
      return state;
  }
// Change code above this line
};

const store = Redux.createStore(authReducer);
// Change code below this line
const loginUser = () => {
  return {
    type: 'LOGIN'
  }
};

const logoutUser = () => {
  return {
    type: 'LOGOUT'
  }
};
// Change code above this line
```

**Comment by RandellDawson** [comment]
@jeremylt I like it.  Let's see what others think and then we can open it up for first timers.

**Comment by nhcarrigan** [comment]
If we are adding additional comments, I'm in favour of the example Jeremy provided.

I'd argue, though, that at this point we've effectively eliminated the usefulness of the comments (there are a total of 5 lines of code not within "change this" comments) and would vote for removing them entirely.

**Comment by kuntau** [comment]
I thought the comments were used by fcc as scope to check the solutions. If not needed, I'd like more subtle comments like “fix the following function”

**Comment by jeremylt** [comment]
That's not one of the `three comments` as I understand them
* `// Change code below this line`
* `// Change code above this line`
* `// Change this line`

**Comment by nhcarrigan** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/dictionaries/english/comments.json

This is our list of approved comments.

**Comment by jeremylt** [comment]
Huh, that's a bigger list than I thought. I think stripping them all together should be fine though. The instructions are essentially 'create two constants and use them', which shouldn't require too much of a safety net.

**Comment by nhcarrigan** [comment]
@RandellDawson are you okay with removing the comments entirely? If so, this could be opened up to first timers.

**Comment by RandellDawson** [comment]
@nhcarrigan From just this challenge?

**Comment by nhcarrigan** [comment]
Yes.,

**Comment by nhcarrigan** [comment]
We are opening this issue up to first timers.

Please review our [contributing documentation](https://contribute.freecodecamp.org) if you are interested in working on this issue.

For clarity's sake: The consensus is to remove the helper comments from this challenge's seed entirely.

**Comment by supzi-del** [comment]
Hey, can I take this up? I'm a newbie, so can someone walk me through it?

**Comment by RandellDawson** [comment]
> Hey, can I take this up? I'm a newbie, so can someone walk me through it?

@supzi-del Make sure to look at the link provided by @nhcarrigan above to get started.

**Comment by CreaTorAlexander** [comment]
This issue is closed right?

**Comment by supzi-del** [comment]
Not yet.
