### ISSUE TITLE
"Update my portfolio from GitHub" button does not disappear despite github being already linked

### ISSUE THREAD

**Issue by ArgonCode** [FreeCodeCamp/FreeCodeCamp#4090]
![screenshot](https://cloud.githubusercontent.com/assets/5458077/10867264/593f65bc-8015-11e5-89a2-798246cbf131.png)

**Comment by bugron** [comment]
@ArgonCode thanks for posting this issue!
It shouldn't. For example, if you change your name in your GitHub account you can update it here with this button.
Closing. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
