### ISSUE TITLE
Use the .env File Challenge Issue

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#40915]
For more coverage, I am opening this here:

Challenge: https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-the--env-file

As of <04/02/2021, a change has caused the above mentioned lesson to be uncompletable.

Error: `SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/runner/boilerplate-express-2/node_modules/fcc-express-bground/index.js:91:26`

The error in full:
<details>
<summary>Error</summary>

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/runner/boilerplate-express-2/node_modules/fcc-express-bground/index.js:91:26
    at IncomingMessage.<anonymous> (/home/runner/boilerplate-express-2/node_modules/fcc-express-bground/index.js:33:7)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:1005:34)
    at resume_ (_stream_readable.js:986:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/runner/boilerplate-express-2/node_modules/fcc-express-bground/index.js:99:28
    at IncomingMessage.<anonymous> (/home/runner/boilerplate-express-2/node_modules/fcc-express-bground/index.js:33:7)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:1005:34)
    at resume_ (_stream_readable.js:986:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
_http_outgoing.js:518
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (/home/runner/boilerplate-express-2/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/home/runner/boilerplate-express-2/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/runner/boilerplate-express-2/node_modules/express/lib/response.js:267:15)
    at /home/runner/boilerplate-express-2/node_modules/fcc-express-bground/index.js:108:15
    at IncomingMessage.<anonymous> (/home/runner/boilerplate-express-2/node_modules/fcc-express-bground/index.js:33:7)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:1005:34)
    at resume_ (_stream_readable.js:986:3) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

</details>

If you encounter this, the best course of action is to skip the lesson, and continue with the curriculum.

As nothing obvious has changed on freeCodeCamp's side, this is likely an issue on Repl.it's side.

<details>
<summary>Current Debugged Steps</summary>

1) Tested code which previously used to pass - no longer passes
2) Downgraded `express` package - no effect
3) One user was able to pass, and the noticeable difference was their `origin` was not `freecodecamp.org`, when they submitted.
4) All manor of sending data via stringifying etc.

</details>

From forum post: https://forum.freecodecamp.org/t/headers-error-in-env-challenge/444357

__P.S. Even though I have said there has been no change to the challenge, in the last few seconds (19:00 UTC) there has been a change pushed to `main`. Otherwise, our side has not changed in a way I can see which would affect this_

**Comment by nhcarrigan** [comment]
Doing some triaging here, it looks like the error originates from the `/_api/use-env-vars` route, which is defined in our [custom express package](https://github.com/freeCodeCamp/fcc-express-bground-pkg/blob/master/index.js).

**Comment by lasjorg** [comment]
Not really sure what is going on, as far as I can tell it's trying to JSON.parse a redirect link (for both `/_api/json` and `/_api/use-env-vars` routes).


Line 33: `cb(d.toString(), req, res, r.headers);`

For me `d.toString()` === `<a href="https://basic-node-and-express-lib-test.lasjorg.repl.co/json">Temporary Redirect</a>`

```
// the callback in /_api/json, "lowerCase" is the "d.toString()" argument
function (lowerCase, req, res) {
  process.env.MESSAGE_STYLE = msgStyle;
  try {
    // lowerCase === <a href="https://basic-node-and-express-lib-test.lasjorg.repl.co/json">Temporary Redirect</a>.
    lowerCase = JSON.parse(lowerCase);
  }

...rest of code
}
```

It's the same for the callback in `/_api/use-env-vars`.

**Comment by nhcarrigan** [comment]
That is likely a change in repl.it's functionality, then.

I'll test this on another host and see what I get.

**Comment by nhcarrigan** [comment]
I'm able to replicate these issues on Glitch as well.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/107064520-7329c180-6790-11eb-9a7c-caaed935d983.png)

Interestingly enough, if I throw the code up on my VPS, I'm able to get a successful query from the `/_api/use-env-vars` route that the test hits (this route crashes repl.it and glitch both).

**Comment by ShaunSHamilton** [comment]
@nhcarrigan Which browser/s did you see this kind of behaviour on? I am now wondering if some change in internet protocol (probably the completely wrong term , but 🤷‍♂️ ) has caused this. That is, a Chromium change?

**Comment by nhcarrigan** [comment]
This was on Chrome. I can also test on Firefox Dev edition.

**Comment by gikf** [comment]
I believe I've found what's happening, although not fully sure *why*. 

Long story short - request send from ie. `/_api/use-env-vars` to the relevant `/json` route uses http, what results in (repl.it?) trying to redirect to https. I don't know how up to date this information is, but I've found posts that `http.request` doesn't follow redirects on it own.

https://github.com/freeCodeCamp/fcc-express-bground-pkg/blob/master/index.js#L16
```
var selfCaller = function (path, req, res, cb, url) {
  var url = req.get('host').split(':');
  var port = url[1];
  url = url[0];
  var prot = req.protocol === 'https' ? https : http;
  var opts = {
    hostname: url,
    method: 'GET',
    path: path,
    port: port || 80,
    headers: {
      'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36',
    },
  };
  var rq = prot.request(opts, function (r) {
(...)
```
Taking repl.it as example: `req.host` doesn't contain port, so `port` is undefined and in the request will be always used `80`. Second thing is that `protocol` in passed `req` is `http`.
Changing `prot` to `https` and `port` to `443` makes everything work.

FWIW this is affecting also `Basic Node and Express - Implement a Root-Level Request Logger Middleware` and `Basic Node and Express - Chain Middleware to Create a Time Server`.

**Comment by ShaunSHamilton** [comment]
This popped up on the forum and reminded me that this is not the first time we are seeing this error on Glitch: https://forum.freecodecamp.org/t/basic-node-and-express-use-the-env-file-get-error-cannot-set-headers-after-they-are-sent-to-the-client/405090

@gikf Thank you, for the thorough debugging. I am not disagreeing with what you found, but I do not understand why the protocol would be unsecured.

**Comment by gikf** [comment]
After some more digging, there seem to be relation between what `req.protocol` is showing, using proxy and having `trust proxy` setting set or not in express - http://expressjs.com/en/api.html#req.protocol. With the option set `req.protocol` is `https` as expected.

**Comment by ShaunSHamilton** [comment]
Thanks @gikf I followed most of your advice, just to get something out which might work for most.

I am still not sure what introduced this bug, and I doubt it is the last time we will see it.

**Comment by JoshuaPelealu** [comment]
I have tried doing every way possible to get an HTTP request but it all responded with the same exact string
`<a href="https://boilerplate-express-1.joshuapelealu.repl.co/json">Permanent Redirect</a>`

I took FCC's boilerplate express package and put it into my reply to test around with it.

I tried using the `http.get()` request:
```js
http.get('http://' + req.get('host') + '/json', (res) => {
    console.log(`STATUS: ${res.statusCode}`)
    console.log(`HEADERS: ${JSON.stringify(res.headers)}`)
    res.setEncoding('utf8');

    res.on('data', chunk => {
      console.log(`BODY: ${chunk}`)
    })

    res.on('end', () => console.log('no more data'))
  })
```
Still the same result.

At some point I tried messing around with the request protocols, adding Agents and adding some request headers and came across the SSL error that @lasjorg came across: 
`EPROTO 140464383563584:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:`
After digging a little deeper, it seems like this error is happening because the proxy or the port is different or something

I was getting a bit curious because it's pointing on the response, so I wanted to try every way possible to do an HTTP request, and one thing that I tried is using node-fetch. When I used it, it worked, here's what it looked like:
```js
var selfCaller = async function (path, req, res, cb, url) {
  let Url = req.protocol + '://' + req.get('host') + path;

  let rq = fetch(Url, {
    method: 'GET',
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'
    }
  }).then(res => res.json())

  rq.then(d => cb(JSON.stringify(d), req, res))

  rq.catch(() => res.status(500).type('txt').send('SERVER ERROR'))
}
```
And it returned:
![image](https://user-images.githubusercontent.com/45566099/108383973-476afa80-71d8-11eb-81ec-e420d97dc2b2.png)

Here's the REPL:
https://repl.it/@JoshuaPelealu/boilerplate-express-1

Here's a join link if you want to mess around with it:
https://repl.it/join/elzmjplm-joshuapelealu

This narrows down the problem to become the express package, or the response handler. The method I use above (using node-fetch) somehow works.

**Comment by JoshuaPelealu** [comment]
Should a temporary solution be used for this issue, until we find exactly why it's failing? This will mean that users can use the curriculum back while we try to fix the issue.

**Comment by ShaunSHamilton** [comment]
@JoshuaPelealu There is a temporary solution, just waiting to be QAed.

**Comment by ShaunSHamilton** [comment]
I am going to close this, for now. The "_temporary_" solution appears to have worked well enough to prevent further issues.
