### ISSUE TITLE
Waypoint: Condense arrays with reduce

### ISSUE THREAD

**Issue by Irfan-M** [FreeCodeCamp/FreeCodeCamp#4091]
In this waypoint there is the code: 
```js
var singleVal = array.reduce(function(previousVal, currentVal) {

  return previousVal - currentVal;

}, 0);
```

There is a misplaced comma in the code above near the end.

**Comment by awesomeaniruddh** [comment]
@Irfan-M Do you mean the comma in this line:

```js
}, 0);
```

**Comment by Irfan-M** [comment]
yea

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue, but the comma is not misplaced :)
`0` is the second argument for `reduce`. From the waypoint:
>`reduce` has an optional second argument which can be used to set the initial value of the accumulator. If no initial value is specified it will be the first array element and `currentVal` will start with the second array element.

Closing the issue. Happy coding!
