### ISSUE TITLE
News article "Logistic Regression: The good parts" is a stub/wip/unfinished.

### ISSUE THREAD

**Issue by danielcaballero88** [freeCodeCamp/freeCodeCamp#40912]
Searching for some Machine Learning content I got a result from google to this FCC article: Logistic Regression: The good parts 4

However, it seems to be a stub, work-in-progress or unfinished article.
Of course I might be wrong too, but I thought to share.

Link to the said article:
https://www.freecodecamp.org/news/logistic-regression-the-good-parts-55efa68e11df/

And a picture:
![image](https://user-images.githubusercontent.com/38633241/106908540-acfeb780-66ff-11eb-9389-268a333f9568.png)

**Comment by ojeytonwilliams** [comment]
Thanks for letting us know about this @danielcaballero88 we'll take a look into this and replace it with the full article, if possible.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for bringing this to our attention @danielcaballero88. I was able to find the original content and updated the stub we had. 

You should be able to go to https://www.freecodecamp.org/news/logistic-regression-the-good-parts-55efa68e11df/ and read the full article now.
