### ISSUE TITLE
Manipulating DOM element using JavaScript

### ISSUE THREAD

**Issue by LearnerSamuelX** [freeCodeCamp/freeCodeCamp#40913]
Based on my personal experience with FCC, I would suggest we should come up a learning section for DOM Manipulation using JavaScript in the JavaScript Algorithm chapter. Things like these:
```
const user_id = document.getElementById('user_ud');
user_id.style.backgroundColor = 'blue'

const button = document.getElementById('button');
button.addEventListener(()=>{
      console.log('button clicked!')
})
```
Current curriculum puts strong focus on CSS Manipulation (very very important for static styling). But when it comes to reflecting UI through style changes, beginners might find it is hard to leap over the gap if they don't have strong knowledge base in JS DOM Manipulation.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to mention this. It has been discussed quite a bit, and is being worked on. However, no more lessons are being added to this version of  the curriculum. The next version is receiving the brunt of the educational development: https://www.freecodecamp.org/news/python-curriculum-is-live/

The above article mostly outlines the first step into the curriculum expansion, but it does mention the ideas behind v7 of the curriculum. If you are interested, here is some of the work done so far on the expansion: https://github.com/freeCodeCamp/CurriculumExpansion

As such, I am going to close this issue. If you have any questions/concerns, feel free to reach out on the [forum](https://forum.freecodecamp.org/), or the [contributors channel](https://chat.freecodecamp.org/channel/contributors).

Hope this clarifies.
