### ISSUE TITLE
Gitter Tool Pallet

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#4092]
> Gitter Tool Pallet
1) Copy Solution as Gitter Link
Precisely as @abhisekp suggested above:  :point_up: November 1, 2015 4:05 AM (Sans URL Shortening) - It is definitely Gitter specific, but Gitter is our help platform of choice.
2) Copy Solution as Gitter Formatted code.
Would prepend the ```js and backtick suffix to simplify cuting and pasting a solution for review. I've also been thinking about adding a waypoint on this, because we burn a lot of time trying to get people to understand this. It's a waste of helper time and it's a waste of camper time.

-@saintpeter

**Comment by SaintPeter** [comment]
@abhisekp's proposed solution:
> A Share URL w/ Solution button which will copy the long url w/ solution in markdown format.
`[Waypoint - XYZ](http://freecodecamp.com/waypoint?solution=blablabla)`

**Comment by SaintPeter** [comment]
Possible amendment:
`[Waypoint - XYZ (SaintPeter's Solution)](http://freecodecamp.com/waypoint?solution=blablabla)`

**Comment by awesomeaniruddh** [comment]
I'd like to work on this

**Comment by bugron** [comment]
@awesomeaniruddh what's your progress?

**Comment by SaintPeter** [comment]
This is needed now more than ever.
