### ISSUE TITLE
[contribute.freecodecamp] Typo in translating docs

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#40932]
Looks like a typo or something in the [Translating a Curriculum File](https://contribute.freecodecamp.org/#/how-to-translate-files?id=translation-best-practices) docs:
![Screen Shot 2021-02-05 at 2 04 33 PM](https://user-images.githubusercontent.com/20648924/107083506-5b1b6780-67bb-11eb-93ca-46a29d387484.png)

Maybe a missing closing tag or something, I didn't look at the file. 

Also, if you click either of the `translators chat room` links on the left, they open in a new tab.

**Comment by nhcarrigan** [comment]
The link itself is incorrect, and is fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/40806

The rendering thing is strange, though - the current file on `main` doesn't have any spacing issues on that line:

```
If you have any questions, feel free to reach out to us in our [translators chat room](https://chat.freecodecamp.org/translators) and we will be happy to assist you.
```

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/107087050-b8a9b700-67af-11eb-884b-ae831f1703b7.png)

This also doesn't repro locally for me - I'm wondering if this is some funky stuff with GH Pages?

**Comment by raisedadead** [comment]
Fixed in https://github.com/freeCodeCamp/freeCodeCamp/commit/8a42bbdf62405aa68431fd4d25ae7ec545f5ad16.
