### ISSUE TITLE
Fixing redirect link

### ISSUE THREAD

**Issue by TawfikYasser** [freeCodeCamp/freeCodeCamp#40930]
**Describe your problem and how to reproduce it:**

The problem is when click on this [link](https://chat.freecodecamp.org/contributors) in `/tools/contributor/` directory to open 
[contributor's chat room](https://chat.freecodecamp.org/contributors) link is not valid and go to `404` page.

**Add a Link to the page with the problem:**

[Link](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/tools/contributor#contribute)

**Recommended fix, suggestions (how would you update it?):**

I recommend to replace this link by [this](https://chat.freecodecamp.org/channel/contributors) because the basic going to contributors channel.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![i404](https://user-images.githubusercontent.com/54971231/107079188-2a0d5800-67f8-11eb-920f-669acd1864cb.png)

If i can fix it, It will be great for me. 

Thanks

**Comment by nhcarrigan** [comment]
Thank you for catching this - I'm opening this up to first timers to replace the link in the README.md file.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/contributor/README.md

**Comment by TawfikYasser** [comment]
Thanks, Can i fix it?

**Comment by nhcarrigan** [comment]
Go for it!

If you have not done so already, we recommend reviewing our [contributing guidelines](https://contribute.freecodecamp.org).

**Comment by TawfikYasser** [comment]
Okay, @nhcarrigan Thanks a lot, I will do that.
