### ISSUE TITLE
Typo in FCC News article called API Cheatsheet

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#40940]
**Describe your problem and how to reproduce it:**
Hi There! 

There is a typo in the API Testing Tools section of the [ API Cheatsheet article](https://www.freecodecamp.org/news/what-is-an-api-and-how-to-test-it/)

It says POSTWOMAN / HOOPSCOTCH
But it should be Postwoman/Hoppscotch

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/news/what-is-an-api-and-how-to-test-it/

**Recommended fix, suggestions (how would you update it?):**
Change to Hoppscotch 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot of typo in article](https://www.dropbox.com/s/nqrtueqkzgb1qc9/Screen%20Shot%202021-02-05%20at%2010.37.24%20PM.png?raw=1)

**Comment by nhcarrigan** [comment]
It looks like the author capitalised all of those image headings.

@scissorsneedfoodtoo would you mind taking a look at this when you have time?

**Comment by jdwilkin4** [comment]
Yeah they capitalized all of them except for Rest-assured. 

I liked the article though. :)

**Comment by scissorsneedfoodtoo** [comment]
Thanks for bringing this to our attention, @jdwilkin4. I just went through and fixed that typo and capitalized the headings based on each product/project's landing page.

Please let us know if you notice anything else :)
