### ISSUE TITLE
Fixing redirect link to contributors chat room

### ISSUE THREAD

**Issue by TawfikYasser** [freeCodeCamp/freeCodeCamp#40947]
**Describe your problem and how to reproduce it:**

The problem is when click on this link in `/docs/how-to-setup-freecodecamp-locally.md` directory to open
contributor's chat room link is not valid and go to `404` page.

**Add a Link to the page with the problem:**

Problem link [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/how-to-setup-freecodecamp-locally.md#getting-help)

**Recommended fix, suggestions (how would you update it?):**

I recommend to replace that link by [this](https://chat.freecodecamp.org/channel/contributors) because the basic going to contributors channel.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

### Image-1

![Image-1](https://user-images.githubusercontent.com/54971231/107126058-4079e900-68b6-11eb-9c9c-7045772223fe.png)

### Image-2

![Image-2](https://user-images.githubusercontent.com/54971231/107126062-47086080-68b6-11eb-8833-161d447dc65b.png)

Thanks

**Comment by nhcarrigan** [comment]
Should be resolved in #40806

**Comment by TawfikYasser** [comment]
So should i close my pr ?
