### ISSUE TITLE
DevOps - Umbrella thread for our IaC

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40969]
### This thread serves as an umbrella discussion for our Infrastructure as Code.

**Note:** _We will be limiting comments here to encourage detailed discussions in the spin-off threads. This thread will remain a location to kick off additional tasks for our ongoing work on our IaC_

Broadly we manage the below pillars of our platforms. Our goal is to create the IaC for all of these eventually.

1. Learn
2. Forum (self-managed Discourse instances - currently only Chinese)
3. News  (self-managed Ghost instances)
4. Coderadio
5. Static applications and sites

**Comment by raisedadead** [comment]
Discussion on the tools for our IaC: **Terraform: Using `cdktf` or `HCL` for our IaC: https://github.com/freeCodeCamp/freeCodeCamp/issues/40970**

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
