### ISSUE TITLE
(fCC/news): Clicking on a link that directs to a heading should take us to the expected position on the article  

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#40975]
**Describe the bug**
Markdown (or HTML) allows us to link to a particular heading in a article. When that link is clicked, the browser takes us to the expected position.

For example, when we open [this link](https://github.com/freeCodeCamp/freeCodeCamp#contributing), we go to the "Contributing" heading position. 

This is **not** the case with fCC/news. We should fix this. 

This came in light when I clicked on "Donate here" on: https://www.freecodecamp.org/news/building-a-data-science-curriculum-with-advanced-math-and-machine-learning

![current](https://user-images.githubusercontent.com/26724128/107157550-a34cac80-69aa-11eb-8a51-25713a7d4f40.png) 

**To Reproduce**
1. Go to https://www.freecodecamp.org/news/building-a-data-science-curriculum-with-advanced-math-and-machine-learning
2. Click on "Donate here" under the FAQ "How Can I Get Involved in This New Data Science Curriculum?".
3. We are not being directed to the correct position.

**Expected behavior**
When links like those are clicked, the browser should take us to the expected position.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04.
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] 88.0.4324.96 (Official Build) (64-bit)

**Comment by imrishabh18** [comment]
Hey @vkWeb! I would like to take up this issue.

**Comment by ShaunSHamilton** [comment]
@vkWeb Thank you, for opening this.

Looks like it is a misplaced few misplaced words, and this link:
`https://www.freecodecamp.org/news/building-a-data-science-curriculum-with-advanced-math-and-machine-learning/#donate-to-the-2021-data-science-curriculum-pledge-drive`

Should be changed to:
`https://www.freecodecamp.org/news/building-a-data-science-curriculum-with-advanced-math-and-machine-learning/#2021-data-science-curriculum-pledge-drive`

---

@imrishabh18 It is excellent you have an interest in contributing, however the author of the article (or a member of staff) are the only ones able to make changes to articles on `/news`.

If you want to contribute, an issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by nhcarrigan** [comment]
I have updated the link in the article. Thank you @vkWeb for reporting, and @ShaunSHamilton for the fix. 🙂

**Comment by vkWeb** [comment]
@ShaunSHamilton Ohh yes you are right. Nice catch there.

@nhcarrigan Thanks for the quick fix :smile:. There's one more link at the bottom that points to the wrong place, let us update that as well:

![issue](https://i.imgur.com/eURcVhW.png)

**Comment by nhcarrigan** [comment]
Thank you - I've fixed that one as well.
