### ISSUE TITLE
Certification has nav and does not render correctly when night mode is active

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#40999]
Reference URL: <https://www.freecodecamp.dev/espanol/certification/nhcarrigan/responsive-web-design>

Navbar on espanol

![image](https://user-images.githubusercontent.com/1884376/107251413-50cac900-6a5a-11eb-936d-1794d7bd5bd3.png)

Night mode active:

![image](https://user-images.githubusercontent.com/1884376/107251611-8a033900-6a5a-11eb-856d-c29d858be589.png)

**Comment by nhcarrigan** [comment]
To expand:

Donation component also breaks on night mode:
![image](https://user-images.githubusercontent.com/63889819/107252903-a4053300-69ea-11eb-9eb3-8234a81e7081.png)

**Comment by Sembauke** [comment]
I would like to work on this

**Comment by ahmadabdolsaheb** [comment]
<img width="1440" alt="Screen Shot 2021-02-08 at 11 02 37 PM" src="https://user-images.githubusercontent.com/4591597/107274652-bff7eb80-6a61-11eb-8d7e-7de4a5fc3185.png">
