### ISSUE TITLE
Staging/i18n: Navbar menu is not wide enough in the spanish version

### ISSUE THREAD

**Issue by kelvinsanchez15** [freeCodeCamp/freeCodeCamp#40997]
**Describe the bug**
The navigation menu is not wide enough to display the text "Inicia sesión para cambiar el tema." in the spanish version of the site.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/espanol/
2. Click on 'Menú'
3. See display bug

**Expected behavior**
The text shouldn't be trimmed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4708484/107228940-9e601b00-69f3-11eb-93f9-0347ec2d23fc.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [chrome]
 - Version: [88]

**Comment by raisedadead** [comment]
We would need to adjust the text to be short enough to be within the width. It's inevitable that we could be handling the width for the differences in each language that we support.

To make this easy we are looking into a visual translation widget that should help you translate with context on the website, as an overlay. We will let you everyone know when that is available.

Until then we would need to adjust these one-off as we notice them.

**Comment by kelvinsanchez15** [comment]
I get it, I will suggest a shorter translation in Crowdin that fits within the available space of the menu.

**Comment by ChrisMOliva** [comment]
What if you added a font size?

.nav-link-dull {
    color: var(--gray-45);
    **font-size: 75%;**
}

**Comment by ahmadabdolsaheb** [comment]
We could avoid this particular issue altogether if we persist the user's choice on the browser as discussed in #36819 which we will be focusing on in the upcoming weeks.

**Comment by raisedadead** [comment]
I think you and us are talking about different things? 

The query here is the text on a label (could be a button, link, menu item etc.) does not fit the width, when translated. 

This is more of a generic issue. 

Anyways, here is an integration with Crowdin that we are currently exploring
https://support.crowdin.com/enterprise/in-context-setup

**Comment by moT01** [comment]
The menu appears to be fixed for espanol:
![Screen Shot 2021-04-22 at 1 39 59 PM](https://user-images.githubusercontent.com/20648924/115768705-46894d00-a370-11eb-84b8-260f6d9df784.png)

Not sure if we want to keep this open.
