### ISSUE TITLE
Staging/i18n: Project and certificates titles are untranslatable on settings page

### ISSUE THREAD

**Issue by kelvinsanchez15** [freeCodeCamp/freeCodeCamp#40998]
**Describe the bug**

freeCodeCamp aims for all of its content to be translated, but the project titles that appear in the sections "certifications" and "legacy certifications" of the user settings page are not translated.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/espanol/settings
2. Sign in
3. Scroll down to 'Certifications'
4. See untranslated strings

To reproduce this Locally, change the below values in `.env` to your desired language.

```
# Languages to build
CLIENT_LOCALE=english
CURRICULUM_LOCALE=english
```

**Expected behavior**

The title should be properly translated, linking the used values to a respectable JSON file should make it so.

Here is the file for the projects [intro.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json), you can use it.
here are the used components:

- [certification.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/settings/certification.js)
- [time-line.tsx](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/profile/components/time-line.tsx)

**Screenshots**
- Spanish:
![image](https://user-images.githubusercontent.com/4708484/107245041-16830c80-6a05-11eb-8d7d-57c7adc20507.png)
- Chinese:
![image](https://user-images.githubusercontent.com/4708484/107245175-3adee900-6a05-11eb-847e-f98b77f56214.png)

**Desktop (please complete the following information):**
- OS: [Windows 10]
- Browser: [chrome]
- Version: [88]

**Additional Context**

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by nhcarrigan** [comment]
These titles are currently grabbed from a config-generated file. It's on the roadmap for how to translate but still being discussed. 🙂

**Comment by JoshuaPelealu** [comment]
I want to pitch in on this, because I really liked the i18n idea. It's probably best to leave the Title in English, but include the translated version in parentheses beside it. So it would look like this.
![image](https://user-images.githubusercontent.com/45566099/107777391-c3fd6500-6d10-11eb-8a7b-1afc12aef581.png).

I'm just trying to suggest an idea here....

**Comment by nhcarrigan** [comment]
Hey @JoshuaPelealu,

I believe our goal is to have 100% translation parity - a camper visiting the Spanish site should see everything in Spanish.

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

For this specific issue, you will come across hard-coding in the [Certification.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/settings/Certification.js#L374) file. For now, these values can be converted to individual keys in one of the translation `.json` files to be translated on Crowdin.

**Comment by moT01** [comment]
Looks like the profile page has some similar issues:
![Screen Shot 2021-08-17 at 3 50 52 PM](https://user-images.githubusercontent.com/20648924/129798816-daa74bb9-c53b-47ba-a90e-e5636759785a.png)

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/129800277-ed6ab922-61fe-488f-975c-17ef79172174.png)

That might be due to no translations (due to rename)

**Comment by moT01** [comment]
Possibly, but it doesn't seem like it - it's on production too. Production still has the folder as `12-certificates`. In the `espanol` version, it has everything translated...
![Screen Shot 2021-08-17 at 4 13 55 PM](https://user-images.githubusercontent.com/20648924/129801572-5b1f3e2a-9bc1-4d23-a213-7cbc6e3f0418.png)
Going to https://www.freecodecamp.org/espanol/mot01, shows all the certs in English. And if you open a cert, it's in English there too.

**Comment by nhcarrigan** [comment]
This might be coming from the meta...

**Comment by LauraJaime8** [comment]
Hi! I would like to contribute to this PR. Could it be possible?

It is my first time and I have seen that this PR has the help wanted tag.

**Comment by nhcarrigan** [comment]
Hey there @LauraJaime8,

I had started taking a look at this, but have been pre-occupied with other tasks. You're welcome to try a solution! You can refer to #43237 to see where I had gone.

**Comment by sidemt** [comment]
I think this issue might be in a higher priority now, since after the change in #44574 every user will come to settings page to claim certifications. I just noticed this issue too.

**Comment by moT01** [comment]
One last spot I see that I don't think was mentioned yet, the certifications themselves don't have the cert title translated.

**Comment by Sboonny** [comment]
A camper talked to me about this issue, and it was difficult for them to understand, so I will update the original post to reflect on the requirement better
