### ISSUE TITLE
Tests in Friendly Date Ranges Bonfire 

### ISSUE THREAD

**Issue by duttakapil** [FreeCodeCamp/freecodecamp#410]
One of the tests for that bonfire is : `friendly(['2016-03-01', '2016-05-05'])`, which is supposed to give  : `['March 1st','May 5th, 2016']`. 
And another test is the same bonfire is : `friendly(['2015-12-01', '2016-02-03'])`, which is supposed to give :
`['December 1st','February 3rd']`. 
This doesn't make sense. If it can be inferred, based on the difference being one month apart, that it's the next year, for the second case, then it should also be possible for the first case too. March and May are one month apart, so the output should be `['March 1st','May 5th']` just like the second case.

**Comment by terakilobyte** [comment]
We're a little backlogged right now so if you can submit a PR to clean this up it would be much appreciated.
