### ISSUE TITLE
Cypress tests broken or flaky?

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#41009]
https://github.com/freeCodeCamp/freeCodeCamp/runs/1861028611#step:10:419

/cc @freeCodeCamp/dev-team

**Comment by ojeytonwilliams** [comment]
This works perfectly locally.  I ran `cypress-repeat run -n 50 --spec "cypress/integration/learn/challenges/output.js"` without any problems.

All of the tests are a bit on the long side (~3000ms), so possibly we just need to wait longer.

**Comment by raisedadead** [comment]
Cool. Do we also want to enable flaky runs on Cypress? It's a new feature they have added recently.

**Comment by ojeytonwilliams** [comment]
Yep, I think so.  We'll probably need to rewrite a few tests, but I've created https://github.com/freeCodeCamp/freeCodeCamp/pull/41013 so we can see.

**Comment by Sembauke** [comment]
This seems to be outdated so I am closing this.
