### ISSUE TITLE
MongoDB driver errors on console

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#41011]
We have been getting new errors since updating the mongodb drivers to `3.6.4`

```console
Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
```

Related reports: https://developer.mongodb.com/community/forums/t/top-level-use-of-w-wtimeout-j-and-fsync-is-deprecated-use-writeconcern-instead/15501

**Comment by raisedadead** [comment]
Context for anyone investigating this:

We use the mongodb driver configs in two indirect places:

**1. In the loopback configs**

https://github.com/freeCodeCamp/freeCodeCamp/blob/827bcfaaa2c71f12bc52a4c660e7213c2c426caf/api-server/server/datasources.production.js#L4-L11

The above config while primarily in the `production` context for Loopback is also derived into the local context:

https://github.com/freeCodeCamp/freeCodeCamp/blob/827bcfaaa2c71f12bc52a4c660e7213c2c426caf/api-server/server/datasources.development.js#L2

Need to update our configs to remove these warnings.

**Comment by njtnestor** [comment]
Im getting the same error/warning conecting loopback 4 with mongo atlas

**Comment by raisedadead** [comment]
> Im getting the same error/warning conecting loopback 4 with mongo atlas

While this may be a genric that you are facing, please note we are reserving this thread for discussions related to this repo's issue and upgrade path only.

**Comment by akat1978** [comment]
I am getting the same error using latest docker image of mongodb

Loopback 4

package.json dependencies
`"dependencies": {
    "@loopback/authentication": "^7.0.5",
    "@loopback/authentication-jwt": "^0.7.5",
    "@loopback/authorization": "^0.7.5",
    "@loopback/boot": "^3.1.2",
    "@loopback/core": "^2.14.0",
    "@loopback/repository": "^3.4.0",
    "@loopback/rest": "^9.1.2",
    "@loopback/rest-explorer": "^3.0.6",
    "@loopback/service-proxy": "^3.0.6",
    "axios": "^0.21.1",
    "dotenv": "^8.2.0",
    "dotenv-extended": "^2.9.0",
    "jsonwebtoken": "^8.5.1",
    "loopback-connector-mongodb": "^5.5.0",
    "tslib": "^2.0.0"
  },
`

Datasource Config

`const config = {
  name: 'mongodb',
  connector: 'mongodb',
  host: '0.0.0.0',
  port: 27017,
  user: 'user',
  password: 'password',
  database: 'db_name',
  useNewUrlParser: true
};`
