### ISSUE TITLE
i18n as related to the Ask for Help on Forum link

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#41015]
As we are now rolling out the curriculum in Chinese and Spanish, we need to think about how to get the `Ask for Help` button to work for the two languages.  Currently, when the button is clicked, the user is taken to the English forum (https://forum.freecodecamp.org) where a pre-populated topic message (in English) is displayed for the user to fill in with relevant information.

These topics are dynamically generated before the post is created on the forum, so we will just need to make use of the `translations.json` file for the content of the topics.  Also, we will need to route to the correct forum url for Chinese and target the correct subforum for Spanish.

**Comment by nhcarrigan** [comment]
So the Chinese links work correctly, because the Chinese forum is hosted at a different domain (which is passed in to the `forumLocation` environment variable).

For Espanol, as it currently stands the category comes from the `helpCategory` value returned by the `challengeMetaSelector`.

**Comment by ramsemune123** [comment]
#45948
