### ISSUE TITLE
Redirecting in new tab in readme.md 

### ISSUE THREAD

**Issue by Aanandgupta** [freeCodeCamp/freeCodeCamp#41019]
**Is your feature request related to a problem? Please describe.**
There are many links in readme would it be a better option to redirect user in new tab
**Describe the solution you'd like**
The links such as that in certification section it would be better to redirect users in new tab because they might want to view multiple pages at a time and with current situation they might not able to find root directory on been redirected no of times.

**Comment by RandellDawson** [comment]
This issue does not appear to be related to freeCodeCamp's repo, so we are closing it at this time.  If you can explain how this related to freeCodeCamp, we could consider reopening this issue.

Thank you
