### ISSUE TITLE
Implementing Backdrop when  menu is been displayed for mobile devices

### ISSUE THREAD

**Issue by Aanandgupta** [freeCodeCamp/freeCodeCamp#41020]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be nice user experience if we add backdrop while displaying menu for mobile devices.

**Additional context**
Like in the image below 
![Screenshot (131)](https://user-images.githubusercontent.com/71023799/107420082-86e17900-6b3e-11eb-955f-605cd1172a8e.png)

**Comment by RandellDawson** [comment]
This issue does not appear to be related to freeCodeCamp's repo, so we are closing it at this time.  If you can explain how this related to freeCodeCamp, we could consider reopening this issue.

Thank you

**Comment by Aanandgupta** [comment]
> 
> 
> This issue does not appear to be related to freeCodeCamp's repo, so we are closing it at this time. If you can explain how this related to freeCodeCamp, we could consider reopening this issue.
> 
> Thank you

I was trying to say that  while we display our nav-bar we can add a backdrop behind  it.Same as in the image i have attached
