### ISSUE TITLE
Bug: Clicking on credit card button on Chinese donate page results in an Invalid API Key error

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#41028]
When on the [Donate page of the Chinese site](https://chinese.freecodecamp.org/donate/), the button does not appear to do anything when clicked and results in a 401 error (see below).

![image](https://user-images.githubusercontent.com/5313213/107452763-08b5b000-6b07-11eb-8343-581a9dc18061.png)

**Comment by nhcarrigan** [comment]
I believe that's a deployment thing - @raisedadead could you confirm?

**Comment by raisedadead** [comment]
Thanks pushing a fresh build.
