### ISSUE TITLE
Algolia 404 error showing in console when Spanish home page loads.

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#41029]
When the [Spanish home page](https://www.freecodecamp.org/espanol) loads, I see an Algolia 404 error.

The English and Chinese home page do not appear to have this error.  I also test incognito on Chrome and the error still persists.

![image](https://user-images.githubusercontent.com/5313213/107453509-5a126f00-6b08-11eb-9656-3403ef37288b.png)

**Comment by nhcarrigan** [comment]
When I trace the network request, I get:

```
{message: "Index noticias does not exist", status: 404}
message: "Index noticias does not exist"
status: 404
```

**Comment by raisedadead** [comment]
I think this is something that @scissorsneedfoodtoo can confim.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching this @RandellDawson. It seems like the search index name got changed somewhere along the line from news-es to noticias.

I'll work on getting those index names out of there to prevent this in the future.
