### ISSUE TITLE
i18n-Launch: Links to Block Pages

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41024]
Currently, links to block pages do not exist. This issue is multi-part:

## Repository Readme

The `README.md` file currently contains the links to the old block pages. These links should be updated (ideally to new block links, but for now a link to the superblock is fine).

These old links will also need to be redirected, possibly.

** Resolved in #41045 **

## Block Views

The old block view pages need to be removed from the client. These would be files such as: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/pages/learn/coding-interview-prep/data-structures/index.md

@ojeytonwilliams can you confirm if removing these files will cause any issues with the parser?

## Block Links

As a nice to have, we could implement block-links as anchors: so `https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures#basic-javascript` would auto-scroll to the correct block on the superBlock view.

** Resolved in #41042 **

**Comment by raisedadead** [comment]
The introduction on the README, for freecodecamp is a bit outdated IMHO as well.

**Comment by ojeytonwilliams** [comment]
The parser only touches .md files in the curriculum/challenges folder, so it will not be affected.

**Comment by nhcarrigan** [comment]
I'll push a couple of PRs to resolve this today.

**Comment by ShaunSHamilton** [comment]
@nhcarrigan Is this related: #41044 ?

**Comment by nhcarrigan** [comment]
Indirectly. I'll comment there too.
