### ISSUE TITLE
i18n-launch: Certificate Path

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41025]
The English and Chinese certificate paths point to the correct location.

The Espanol certificate paths point to the English URL. I believe this is caused by the `external` attribute here: https://github.com/freeCodeCamp/freeCodeCamp/blob/0a7278774eee83a8b8056f2a89a0d353104a574b/client/src/components/profile/components/Certifications.js#L40-L57 but have not triaged yet.

**Comment by moT01** [comment]
I tried looking into this. Here's what I see on the espanol site:
![img](https://user-images.githubusercontent.com/20648924/107523443-561f3500-6b7a-11eb-9b46-bc25f15dd78c.png)

The code and the rendered element look nearly identical, but the hover URL that shows up at the bottom of the browser window isn't correct for the top link.

This doesn't seem easy to reproduce locally so it makes it tough to test anything. The only thing I noticed that I think might be causing it, is [this `curry` function](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/profile/components/Certifications.js#L67).
