### ISSUE TITLE
Forum option missing for mobile devices.

### ISSUE THREAD

**Issue by Aanandgupta** [freeCodeCamp/freeCodeCamp#41035]
Forum option missing for mobile devices. on news page https://www.freecodecamp.org/news/
Normally we have two options on the header but for mobile devices we have only one
You will better understand the issue going through the images attached 

![Screenshot (133)](https://user-images.githubusercontent.com/71023799/107492906-f85b0f00-6bb2-11eb-8506-3184baecc004.png)

![Screenshot (135)](https://user-images.githubusercontent.com/71023799/107493177-57208880-6bb3-11eb-9826-c3a0e2214852.png)

I think to align with all the other pages we should have a menu which on clicking displays both or some more options
![Screenshot (136)](https://user-images.githubusercontent.com/71023799/107493203-5ee02d00-6bb3-11eb-81da-a69bc7d97505.png)

**Comment by raisedadead** [comment]
I believe this was intentional to save real-estate on news. @ahmadabdolsaheb could you weigh in.

**Comment by ahmadabdolsaheb** [comment]
Thanks for bringing this to our attention. We are discussing a few improvements for the news navigation and having a more functional mobile navigation is one of them. 

I will discuss our options with the team and reply with updates.

**Comment by Aanandgupta** [comment]
> Thanks for bringing this to our attention. We are discussing a few improvements for the news navigation and having a more functional mobile navigation is one of them.
> 
> I will discuss our options with the team and reply with updates.

I was not knowing that improvement is going on that news navigation and taught that bringing it to you would be helpful.

**Comment by ahmadabdolsaheb** [comment]
Closing with https://github.com/freeCodeCamp/freeCodeCamp/issues/40808#issuecomment-779262032
