### ISSUE TITLE
i18n-launch: SolutionForm disallowing Python projects

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41033]
![image](https://user-images.githubusercontent.com/63889819/107466407-cb5a1e00-6b18-11eb-9b5c-c159bd441e24.png)

Included in the i18n launch was PR #40225 which added validation that campers are submitting the link to the live URL for their backend projects. This is great for the Node.js projects, but has broken the ability to submit Python projects. 

This should be adjusted to pull the Python projects out of the scope of this validation.

Related forum post: https://forum.freecodecamp.org/t/problem-submitting-solution/445429?u=nhcarrigan

**Comment by ShaunSHamilton** [comment]
Sorry about that, I am getting right on it.

This completely slipped my mind.

**Comment by ojeytonwilliams** [comment]
Thanks Shaun, let me know if I can help.  While you're doing that, I'll put together some tests to make sure we don't recreate this bug.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams A test or 2 would be ideal 👍
