### ISSUE TITLE
i18n-launch: Feedback on New UI Design

### ISSUE THREAD

**Issue by LearntoCodeQuickly** [freeCodeCamp/freeCodeCamp#41032]
Saw the forum post about the UI updates and thought I would share some feedback.

From a design perspective I think the recent changes to the menu and curriculum  have increased the UI a bit but decreased the UX a bit.  Couple of notes on my personal user experience which may or may not be useful insights to the designers:

1. I liked having the "Curriculum", "Forum", and "Profile" at top.  Now that they're nested in a menu I have to go through an extra layer of clicks to get where I want to go.  I mostly jump back and forth between the forums and curriculum in particular.  This is not a big deal, and make the top bar look cleaner, but it does add an extra step.  Given that I'm on the site several hours a day right now, I'm guessing this is going to add up to hundreds, if not thousands, of extra clicks for me.  Not a huge deal, but given the choice, I'd prefer to have those menu items immediately accessible.  [This article](https://www.nngroup.com/articles/menu-design/) lists it as their #1 rule (Don't use tiny menus or menu icons on large screens).

2. One thing I really liked about the previous design was the ability to get an overview of the entire certification syllabus in a single visual gulp.  Again, where the UI looks nice with the containers with logos, I do feel it is less functionally clean and impairs the ability to drink the entire course in all in one "gulp".  There's probably a technical name for absorbing the respective syllabi in  a single shot, but "gulp" is all I've got at the moment.  I'm doing a different program simultaneously, and one of the things I REALLY appreciate about the way they've laid things out is that they keep the curriculum in a left sidebar at all times.  It's one nuisance I've had with freeCodeCamp compared with the other program, I find that I often want to jump back a lesson or two to refresh on a concept that's being built upon.  With the other program I can find what I'm looking for in literally about a second, whereas with FCC I need to keep hitting back and evaluate if the page I'm looking at is the right page, or else open up the curriculum and scroll to the area I'm looking for (I ended up doing the latter more often unless I knew what I was looking for was in a previous lesson).

By breaking each section down into collapsible containers and spacing between the containers, it makes it much more difficult to quickly digest how everything flows together.   

Also, not sure if I'm already forgetting how it was laid out previously, but were there descriptions of each section the same?  I feel like I'm having trouble quickly scanning because I'm alternative between titles, paragraph chunks of descriptions, and expandable course tutorials.  I think what I don't like are the paragraph descriptions because they are the weightiest parts of the page, but the part I least care about and which I'll have the least reason to revisit.  Can the description be hidden in a dropdown?

Couple of thoughts on my personal experience, hopefully these are taken as constructive feedback from someone who's spending quite a bit of time each day on the site.   Overall, it's a fantastic program that's laid out in a very intuitive manner, I'm only going into this level of details with the aim of giving useful feedback.

Thanks to everyone who's put so much work into creating this absolutely fantastic free resource for the world, including the mods, who do an incredible job of staying positive and supportive while providing useful feedback and keeping the forums free of spam / distractions!

**Comment by ojeytonwilliams** [comment]
Hey @LearntoCodeQuickly thanks for this incredible feedback.  This kind of detailed, thoughtful critique is exactly what we need to keep improving the site.

I won't weigh in with my opinions just yet (UX isn't my strongest suit), I just wanted to thank you for taking the time to write this.

**Comment by ahmadabdolsaheb** [comment]
@LearntoCodeQuickly, thank you for the detailed feedback.

We have added a few more items to the navigation to help users get around easier. More items require more vertical real-estate. That is the main reason behind the collapsable vertical navigation. For the next iteration we could  identify a group of navigational items that are most used and only collapse them in smaller screens. Also, it might be feasible to adapt a vertical always on navigation.

In additional to performance considerations, chunking the map into multiple sections would help users focus on a section at a time. As we are expanding our curriculum to different programing languages and disciplines, displaying all educational content at once might introduce more noise into the user journey. That being said, I see the benefit of offering some users the ability to see everything all at once.

Although the new breadcrumb would help with transitioning between challenges, and a collapsable in challenge navigation could be considered, a new project based curriculum is in works in which concepts are reused and switching between challenges is less necessary. 

Please keep us notified if you come across other aspects of our platforms that could be improved.

**Comment by ahmadabdolsaheb** [comment]
After a slit drop on the forum signups, I believe we should go ahead and add links to our other platfroms in the nav for larger screens.

**Comment by moT01** [comment]
Thanks for the feedback @LearntoCodeQuickly 🎉 Tip: if you are in a challenge, you can press escape then `n` or `p` to go to the next or previous challenge.

**Comment by raisedadead** [comment]
> Thanks for the feedback @LearntoCodeQuickly 🎉 Tip: if you are in a challenge, you can press escape then `n` or `p` to go to the next or previous challenge.

I remember Oliver working on something for displaying the shortcuts to power users?

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
