### ISSUE TITLE
edge case in which it should fall-back on username from name in showing cert

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#41040]
If there is no name set in the settings, doesn't matter if name is public or private, instead of falling back to username, it gives an error and certificate is not shown

**Comment by ShaunSHamilton** [comment]
I assume the best UX is for a note to appear, if the Camper tries to set `name` to public, without having first set `name` to something.

**Comment by ieahleen** [comment]
the error appears also if name is not set and set to private - certificate does not appear saying that one has to put a name (I'm adding this on top message too)

**Comment by Sembauke** [comment]
Picture
![Screenshot_5](https://user-images.githubusercontent.com/46919888/107516147-44568580-6bac-11eb-98e8-119e81c01249.jpg)

**Comment by Ismailtlem** [comment]
The objective here then is to show the username on the certification if the name is not set ? 

Maybe some message then must warn the camper that his username will be shown on the certification instead of his real name (I am not sure though that a certification given to a weird username would be ok)

**Comment by ieahleen** [comment]
@Ismailtlem already if the name is private the username is shown, this issue appears if the name is not set

**Comment by ShaunSHamilton** [comment]
@moT01 Apologies if this has nothing to do with you, but I vaguely remember you being involved in the discussion I cannot find:

Was there any conclusion as to disabling the certification until a Camper has set their name, and made it public?

**Comment by moT01** [comment]
Sorry for the late response here - The only thing that comes to mind is [the discussion here](https://github.com/freeCodeCamp/freeCodeCamp/issues/38569) @ShaunSHamilton

**Comment by ahmadabdolsaheb** [comment]
Either we would need to remove having usernames as a fallback , or having a public  name requirements when displaying certs.

I now it might be inconvenient, but I vote for removing the fallback for simplicity and keeping the public name as a requirement.

**Comment by nhcarrigan** [comment]
Discussing in issue triage meeting.

### Current Behaviour
1. When a camper sets the `name` to a non-empty string and `private`, the certificate renders with the `username`.
2. .When a camper sets the `name` to an empty string and either `public` or `private`, the certificate does not render and redirects to `/` with a flash message.

We should update the behaviour of #1 to mirror the behaviour of #2, and avoid using the username field as a fallback entirely.

**Comment by BalanaguYashwanth** [comment]
Hello @ieahleen 

Is this issue solved ?
