### ISSUE TITLE
boilerplate links for backend challenges has gone missing 

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#41044]
the introduction page that was removed had the link to the boilerplate, now those links are not in the curriculum

already a few people that reached that point today have shown confusion

**Comment by ShaunSHamilton** [comment]
To add:
Here is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/pages/learn/apis-and-microservices/managing-packages-with-npm/index.md

It seems only some of the paragraphs is taken: https://www.freecodecamp.org/learn/apis-and-microservices
![image](https://user-images.githubusercontent.com/51722130/107543283-fbf59280-6bc0-11eb-8a8a-cf66821ee3f2.png)

I agree - very confusing.

**Comment by nhcarrigan** [comment]
I'm not sure that the links should go in those intro paragraphs. I'm thinking instead that we add them to the first challenge within the superblock.
