### ISSUE TITLE
Further explanation needed for Hack No.4 from 10 CSS Hacks Every Web Developer Should Know

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41053]
**Describe your problem and how to reproduce it:**
I think it is unclear how Hack No.4 actually works. The author should provide more details. 
When I tried to google .single-post css, I only received results related to WordPress. 
If this is something that only works for WordPress, than the author should clarify that. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/10-css-hacks-every-web-developer-should-know/

**Recommended fix, suggestions (how would you update it?):**
More clarification is needed on how .single-post works.

**Comment by giaduc777** [comment]
Yeah I have already check too, didn’t find anything “.single-post” related to CSS. It looks like “.single-post” is just a custom CSS class that you would add to the single page that you want to modify.

**Comment by jdwilkin4** [comment]
I also posted this question in the forum and a user said that it was used in WordPress. So I think the author needs to clarify that because it would only be considered a css hack within the context of WordPress. But if you are not working with Wordpress than this hack doesn't really apply.

**Comment by raisedadead** [comment]
Hey @scissorsneedfoodtoo mind taking a look?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @jdwilkin4, and for your input @giaduc777. I also think that this section could have used some clarification.

It seems like the whole `.single-post .entry-title` method refers to WordPress, but the way it was used in the article wasn't exactly right. Seems like if you did that, then it would modify all styling for all single post pages.

I went ahead and rewrote this section for WordPress, and also tried to make it more general by mentioning methods for another CMS and showing how you could do the same thing with plain HTML and CSS.

Will close this for now. Please let me know if you notice anything else :+1: :+1:
