### ISSUE TITLE
Fixing css to enhance the redability for user

### ISSUE THREAD

**Issue by Aanandgupta** [freeCodeCamp/freeCodeCamp#41062]
In email signup page text is not structured refer to that attached images
If we add
"div class="intro-description" style="
    padding:0 15px;
""
it would look much good 
Before & after images 

![Screenshot (142)](https://user-images.githubusercontent.com/71023799/107695523-bc20cf00-6cd6-11eb-90ad-b96153701e78.png)

![Screenshot (138)](https://user-images.githubusercontent.com/71023799/107695704-f8ecc600-6cd6-11eb-957a-703381cca65f.png)

**Comment by manziEric** [comment]
can i work on this ? i'm a first time contributor

**Comment by Aanandgupta** [comment]
> can i work on this ? i'm a first time contributor

I didn't see the comment and pr you generated .

**Comment by ShaunSHamilton** [comment]
It is great that you are eager to contribute to the code base, but this issue/feature has not been triaged yet. So, no decision has been made as to the appropriate course of action - whether anything needs to be changed and how. This means PRs might not be needed, or changes are likely needing to be made to them.

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. 

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Aanandgupta** [comment]
> It is great that you are eager to contribute to the code base, but this issue/feature has not been triaged yet. So, no decision has been made as to the appropriate course of action - whether anything needs to be changed and how. This means PRs might not be needed, or changes are likely needing to be made to them.
> 
> An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.
> 
> If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/
> 
> If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

Thanks a lot for your guidance

**Comment by moT01** [comment]
I am fine with fixing this up in some way. I left a review on the PR with some thoughts.

**Comment by Sembauke** [comment]
People that want to work on this can follow this PR- / comment https://github.com/freeCodeCamp/freeCodeCamp/pull/41088#issuecomment-785039397
