### ISSUE TITLE
Player plays the wrong song after a long pause

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#41069]
If the player is paused for a while (30min) and unpaused, it will play song a; however if the page is refreshed the player is updated and it will play song b.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
