### ISSUE TITLE
Current song's album not being displayed and being cut off of at the bottom. 

### ISSUE THREAD

**Issue by bvi1994** [freeCodeCamp/freeCodeCamp#41075]
Hi everyone, 

I noticed for the current song, the artwork for the album is not being displayed. Also, I noticed that the image is cut off at the bottom. 

I think this would be a good first issue for newcomers to fix up! :) 

Here's the problem for Desktop: 

![image](https://user-images.githubusercontent.com/9060271/72388361-8deb4d00-36da-11ea-839f-4a44628b42fe.png)

**Comment by moT01** [comment]
I am unable to reproduce this on a few different OS's and browsers. Can anyone confirm that this is still an issue? I think it may be resolved.

**Comment by binyamin** [comment]
@moT01 I can't reproduce anymore.

**Comment by ahmadabdolsaheb** [comment]
https://github.com/freeCodeCamp/coderadio-client/pull/135 seems to have resolved the issue.
