### ISSUE TITLE
Make background image responsive

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#41072]
The background and the Saron animation are fixed and do not change size based on viewport, so smaller screens see only a portion of the image and large fullhd + screen will see the image stock to a corner.

User stories (edited):
- Users should see as much of the image as possible.
- If the view has a wider ratio in comparison to the image, the image's full width should be displayed allowing the upper and lower part of the image to stay outside of the screen.
- If the view has a taller ratio in comparison to the image, the image's full height should be displayed allowing the the sides of the image to be out of the view.

Note: It would be great if we could achieve this without using js.

**Comment by Ismailtlem** [comment]
Hi,
Should PRs for Coderadio be pushed to freecodecamp/freecodecamp repo or to coderadio-client repo ?

**Comment by nhcarrigan** [comment]
The codebase is still located on the coderadio-client repository. All PRs to modify the code radio client should go there.

The issues were moved to this repository to allow all of our codebase issues to be in one place.

**Comment by raisedadead** [comment]
Hi @Ismailtlem how is this coming along? Is this still an issue?

**Comment by Ismailtlem** [comment]
It is still  not completely solved, the issue mainly is about the animation in the background which is independant from the background image. We need to agree on what to do regarding the animation for screens with a width larger than 750 px I think

**Comment by raisedadead** [comment]
Hi @ahmadabdolsaheb 

Can you list down the user-stories or action items to keep this feature request moving.

**Comment by ahmadabdolsaheb** [comment]
I will edit the description accordingly.

**Comment by Stev24** [comment]
Is this issue already fixed ? Or do you still need help ?

**Comment by ahmadabdolsaheb** [comment]
@Stev24, the issue has not been resolved completely. You could see the issue if you visit Coderadio with a screen taller or wider than FHD.

**Comment by SwarajBaral** [comment]
hey @ahmadabdolsaheb, I have an idea. We can overlay the gif and bg-image and export it as a gif altogether. We can use the exported gif as the background image and a single gif is much easier to make responsive. Can I give it a try ?

**Comment by ahmadabdolsaheb** [comment]
@SwarajBaral, that makes sense. please go ahead with a pr.

**Comment by SwarajBaral** [comment]
@ahmadabdolsaheb okay then, I am on it.

**Comment by SwarajBaral** [comment]
@ahmadabdolsaheb I have created the required pr. Please go through it and let me know if it needs any changes. Thank you.

**Comment by JaySharma11** [comment]
Is this issue still open?

**Comment by JaySharma11** [comment]
I was thinking what if we divide current background in 2 parts one from the left most end to the center including Saron and then the rest of the background from center to right end. After this we can use min width to scale only the part with Saron for small screen sizes and for screen size larger than that of the whole image we can scale both parts together.

P S. I'm still learning Web Development and just wanted to contribute to the platform for all the great work you guys are doing.

**Comment by ahmadabdolsaheb** [comment]
Note: lighthouse suggest using video formats instead of gif for animations.
If there is a performance benefit, we might altogether do a video format if we end up having the Saron gif and the background in one file.

<img width="896" alt="136167257-62e44d6d-2a75-4ca9-a362-f9f38802bd5d" src="https://user-images.githubusercontent.com/4591597/148643070-b176943f-0f89-4fbc-9ba5-b495c6c618aa.png">

**Comment by nawed2611** [comment]
Hi, is this issue still open?

**Comment by ahmadabdolsaheb** [comment]
Yes. Also feel free to experiment with mpeg4/webm for the animations and see if we could reduce the size of the assets.
