### ISSUE TITLE
Better accessibility

### ISSUE THREAD

**Issue by AskMP** [freeCodeCamp/freeCodeCamp#41079]
While yes, the site is "technically" keyboard controllable, it would be a good idea to implement proper accessibility for users when the hit the page. I'm not an expert at this but I may know some people who can assist in making recommendations as it's a fairly unique use case.

**Comment by ahmadabdolsaheb** [comment]
Other than turning the play/pause into a button element and the small issue mentioned in the lighthouse report, I think we should be good. 
<img width="1148" alt="Screen Shot 2021-02-16 at 3 41 40 PM" src="https://user-images.githubusercontent.com/4591597/108064292-83ce1780-706d-11eb-8485-212c50594e19.png">

**Comment by ahmadabdolsaheb** [comment]
I am closing this replacing div with button has been addressed.
