### ISSUE TITLE
Localstorage for personal preferences

### ISSUE THREAD

**Issue by AskMP** [freeCodeCamp/freeCodeCamp#41080]
Adding the page configuration and removal of the CTA after first viewing would be good to have. If you've selected the lower (or higher) bitrates manually or when we add localization, it should keep those preferences upon revisiting the page.

**Comment by ahmadabdolsaheb** [comment]
The bitrate is being adjusted based on the user's internet connection, and the volume is being saved in localstorage.

We could set a value in the localstorage on initial load so we could hide the cta based on that.  I cannot think of any other use case for now.

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.
