### ISSUE TITLE
feature: FCC Credentials for added functionality

### ISSUE THREAD

**Issue by AskMP** [freeCodeCamp/freeCodeCamp#41081]
Similar to how nightbot was able to be used for public curation and song preference of the audience (VERY interesting to see how impact full that actually was) it would be good to add this. The issue comes in with how we implement it for non-spamming. I think an "if you're logged into fCC, you have additional functionality" would likely be the best case.

Previously, nightbot sent me the UID of the YouTube user where that was tracked to whether they had voted before and I was able to update if so or add if it was new. This could be the same, UID per song. Also, chat. Chat was a VERY large aspect of the YouTube live that could be implemented with credentials however it should be noted that ANYBODY can create an account... so it would likely still need to be moderated to an extent.

**Comment by ahmadabdolsaheb** [comment]
We currently have a rocket chat server that we could integrate into our coderadio using an iframe. That way we could use user inputs from chat to alter the playlist if necessary.

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.
