### ISSUE TITLE
Standardize icon sizes on map

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41083]
This is pretty minor, and may be fine to just leave. The icons are causing the buttons on the map to be different sizes:

![Screen Shot 2021-02-12 at 9 18 04 AM](https://user-images.githubusercontent.com/20648924/107786352-6880a680-6d13-11eb-867c-b3de8ffa2ef4.png)

The first highlighted button is larger than the second highlighted button, even though there's more text on the second one. Seems like we could give the icons a set size or something. Pretty sure it's the icons anyway. Probably would go with a universal height across them and an auto width?

**Comment by nhcarrigan** [comment]
Yeah I'm pretty sure it's the icons too.

**Comment by ahmadabdolsaheb** [comment]
It is the icons. We could increase the min height of the container as a quick fix;however, the optimal solution would be to have icons that occupy similar real estate: height and width. 

There is a related umbrella issue for standardizing icons.

**Comment by moT01** [comment]
Closed with the linked PR
