### ISSUE TITLE
Heroku Setup Info Missing

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/FreeCodeCamp#4108]
The new "Get Set for Basejumps" waypoint does not contain information about setting up a Heroku account for the Basejump deployment, but the text of the Voting App basejump states. "Note that for each Basejump, you should create a new GitHub repository and a new Heroku project. If you can't remember how to do this, revisit http://freecodecamp.com/challenges/get-set-for-basejumps".

I assume Heroku deployment is still a desired goal of the basejumps, so rather than removing this text we probably want to modify the waypoint to show this.

**Comment by ltegman** [comment]
There's some other lingering issues from the transition from Angular-Fullstack to Clementine.

+ Step 4 says that after committing new changes to Heroku you should run `grunt --force && grunt buildcontrol:heroku` but that does not work with Clementine.
+ Step 14 says "If you need further guidance on using Yeoman Angular-Fullstack Generator, check out: https://github.com/clnhll/guidetobasejumps" still.

**Comment by BerkeleyTrue** [comment]
fixed with #4158

**Comment by colindevs** [comment]
@BerkeleyTrue @QuincyLarson Is there an estimated date of when Heroku setup steps will be available?
