### ISSUE TITLE
All terms should be defined when first introduced

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4109]
Examples:
CSS = Cascading Style Sheets
HTML = Hypertext Markup Language
Tag
Element

Also, a brief description of what it is or what it does.

Assume someone coming in with zero knowledge.

Possible internal hyperlinks to Wiki on these topics.

FCC Glossary maybe?

In-line pop-up definitions?  Link to more info?

**Comment by AkiraLaine** [comment]
@QuincyLarson opened an issue #4117 for this :D

**Comment by atjonathan** [comment]
Closing in favor of #4117
