### ISSUE TITLE
Dead Link in Curriculum (Install and Set Up Mongoose)

### ISSUE THREAD

**Issue by Ne0nWinds** [freeCodeCamp/freeCodeCamp#41097]
**Describe your problem and how to reproduce it:**
1. Go to [this coding challenge](https://www.freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose)
2. Click on **Follow this tutorial**, which leads you to [this link](https://www.freecodecamp.org/news/get-started-with-mongodb-atlas/)
3. The link gives a 404 message

This link is important, because it's supposed to tell you how to set up a mongodb database. I would make a pull request, but I'm not sure what link should replace it. Perhaps, [this one](https://docs.atlas.mongodb.com/getting-started/)?

* Browser Name: Firefox
* Browser Version: 85.0.2
* Operating System: Windows 10

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this.

It is related to this PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/40803 (I am not sure why the link leads to a 404)

@scissorsneedfoodtoo Ping

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching this @Ne0nWinds, and for the ping @ShaunSHamilton.

There was an issue with the article's slug on News/Ghost. I just fixed it, so the link should work now.

Will close this issue, but please let us know if you notice any other issues in the curriculum.
