### ISSUE TITLE
Missing hex code value in Spanish language version of challenge

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#41096]
challenge: https://www.freecodecamp.org/espanol/learn/responsive-web-design/applied-visual-design/learn-about-tertiary-colors
challenge: https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/learn-about-tertiary-colors

`orange #FF7F00`
`anaranjado #F7F00`

**Comment by ShaunSHamilton** [comment]
I have submitted a suggestion for this change on [Crowdin](https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/20456/en-esem/8?filter=basic&value=0)

_unsure if the link to what I want_

**Comment by kelvinsanchez15** [comment]
Yes, that is the right place to suggest translations. It is already approved. So in the next merge it will be effective. Thank you.

**Comment by lasjorg** [comment]
As this was fixed, I will close the issue.
