### ISSUE TITLE
Restrict possible usernames: a wrong solution passes challenge

### ISSUE THREAD

**Issue by petzi53** [freeCodeCamp/freeCodeCamp#41095]
**Describe your problem and how to reproduce it:**
`let userCheck = /^[a-z][a-z]+\d*$|^[a-z].\d+$/i;` 
passes the test and therefore allowing a username like "J%4" which is contradicting the first rule

> Usernames can only use alpha-numeric characters.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

**Comment by JoshuaPelealu** [comment]
It seems like the culprit is because the test does not check if the username is using legal characters like alphabet and a non alphanumeric in the middle of the username string.

**Comment by JoshuaPelealu** [comment]
I can take care of this...
