### ISSUE TITLE
Sign up / Sign in Page Localization

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/freeCodeCamp#41112]
The sign-in page is not translated into world languages.

**Comment by raisedadead** [comment]
I have mulled over this quite a bit, and it seems that localizing the sign-in page will be non-trivial and will come with added delays in loading the page. 

We are currently, and for the foreseeable future are using Auth0's hosted login page, which is a centralized page hosted at `https://auth.freecodecamp.org`. This means all our applications chat, forum, etc., all redirect from this page with user authentication.

This page is extremely lightweight HTML with very little JS code for handling the interactions. While we could add localized markup and even render that based on the referrer URL, it would add a lot of weight to the page once we have dozens of languages.

Users do not spend too much time on this, and the redirection flow is not ideal; adding more markup will only slow the UX more.

Considering the % of the audience using the localized page would be a small fraction of the global audience, I am not sure if the implementation is worth the tradeoff in UX. We might want to keep the page fast instead.

I think we should consider closing this as a `wontfix`.

**Comment by ahmadabdolsaheb** [comment]
We could add icons to the buttons to reduce confusion for users who do not speak english.

**Comment by nhcarrigan** [comment]
Closing as wontfix for now, due to our current auth implementation.
