### ISSUE TITLE
Add solutions to rest of challenges.

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#4111]
These challenges still need solutions (some of these might not need solutions but got mixed in anyways)

- [x] Exact Change
- [x] Use the Javascript Console
- [x] Using typeof
- [x] Comment your JavaScript Code
- [x] Understanding Boolean Values
- [x] Check for Palindromes
- [x] Declare JavaScript Variables
- [x] Declare String Variables
- [x] Find the Length of a String
- [x] Use Bracket Notation to Find the First Character in a String
- [x] Use Bracket Notation to Find the Nth Character in a String
- [x] Use Bracket Notation to Find the Last Character in a String
- [x] Truncate a string
- [x] Use Bracket Notation to Find the Nth-to-Last Character in a String
- [x] Add Two Numbers with JavaScript
- [x] Subtract One Number from Another with JavaScript
- [x] Multiply Two Numbers with JavaScript
- [x] Divide One Number by Another with JavaScript
- [x] Create Decimal Numbers with JavaScript
- [x] Where do I belong
- [x] Multiply Two Decimals with JavaScript
- [x] Divide one Decimal by Another with JavaScript
- [x] Store Multiple Values in one Variable using JavaScript Arrays
- [x] Nest one Array within Another Array
- [x] Access Array Data with Indexes
- [x] Modify Array Data With Indexes
- [x] Manipulate Arrays With pop()
- [x] Manipulate Arrays With push()
- [x] Manipulate Arrays With shift()
- [x] Manipulate Arrays With unshift()
- [x] Write Reusable JavaScript with Functions
- [x] Build JavaScript Objects
- [x] Update the Properties of a JavaScript Object
- [x] Add New Properties to a JavaScript Object
- [x] Delete Properties from a JavaScript Object
- [x] Iterate with JavaScript For Loops
- [x] Iterate Odd Numbers With a For Loop
- [x] Count Backwards With a For Loop
- [x] Iterate with JavaScript While Loops
- [x] Generate Random Fractions with JavaScript
- [x] Generate Random Whole Numbers with JavaScript
- [x] Generate Random Whole Numbers within a Range
- [x] Use Conditional Logic with If and Else Statements
- [x] Sift through Text with Regular Expressions
- [x] Find Numbers with Regular Expressions
- [x] Find Whitespace with Regular Expressions
- [x] Invert Regular Expression Matches with JavaScript
- [ ] Create a JavaScript Slot Machine
- [ ] Add your JavaScript Slot Machine Slots
- [ ] Bring your JavaScript Slot Machine to Life
- [ ] Give your JavaScript Slot Machine some Stylish Images

## Object Oriented and Functional Programming

- [x] Declare JavaScript Objects as Variables
- [x] Construct JavaScript Objects with Functions
- [x] Make Instances of Objects with a Constructor Function
- [x] Make Unique Objects by Passing Parameters to our Constructor
- [x] Make Object Properties Private
- [x] Iterate over Arrays with .map
- [x] Condense arrays with .reduce
- [x] Filter Arrays with .filter
- [x] Sort Arrays with .sort
- [x] Reverse Arrays with .reverse
- [x] Concatenate Strings with .concat
- [x] Split Strings with .split
- [x] Join Strings with .join

## HTML5 and CSS

- [ ] Say Hello to HTML Elements
- [ ] Headline with the h2 Element
- [ ] Inform with the Paragraph Element
- [ ] Uncomment HTML
- [ ] Comment out HTML
- [ ] Fill in the Blank with Placeholder Text
- [ ] Delete HTML Elements
- [ ] Change the Color of Text
- [ ] Use CSS Selectors to Style Elements
- [ ] Use a CSS Class to Style an Element
- [ ] Style Multiple Elements with a CSS Class
- [ ] Change the Font Size of an Element
- [ ] Set the Font Family of an Element
- [ ] Import a Google Font
- [ ] Specify How Fonts Should Degrade
- [ ] Add Images to your Website
- [ ] Size your Images
- [ ] Add Borders Around your Elements
- [ ] Add Rounded Corners with a Border Radius
- [ ] Make Circular Images with a Border Radius
- [ ] Link to External Pages with Anchor Elements
- [ ] Nest an Anchor Element within a Paragraph
- [ ] Make Dead Links using the Hash Symbol
- [ ] Turn an Image into a Link
- [ ] Add Alt Text to an Image for Accessibility
- [ ] Create a Bulleted Unordered List
- [ ] Create an Ordered List
- [ ] Create a Text Field
- [ ] Add Placeholder Text to a Text Field
- [ ] Create a Form Element
- [ ] Add a Submit Button to a Form
- [ ] Use HTML5 to Require a Field
- [ ] Create a Set of Radio Buttons
- [ ] Create a Set of Checkboxes
- [ ] Check Radio Buttons and Checkboxes by Default
- [ ] Nest Many Elements within a Single Div Element
- [ ] Give a Background Color to a Div Element
- [ ] Set the ID of an Element
- [ ] Use an ID Attribute to Style an Element
- [ ] Adjusting the Padding of an Element
- [ ] Adjust the Margin of an Element
- [ ] Add a Negative Margin to an Element
- [ ] Add Different Padding to Each Side of an Element
- [ ] Add Different Margins to Each Side of an Element
- [ ] Use Clockwise Notation to Specify the Padding of an Element
- [ ] Use Clockwise Notation to Specify the Margin of an Element
- [ ] Style the HTML Body Element
- [ ] Inherit Styles from the Body Element
- [ ] Prioritize One Style Over Another
- [ ] Override Styles in Subsequent CSS
- [ ] Override Class Declarations by Styling ID Attributes
- [ ] Override Class Declarations with Inline Styles
- [ ] Override All Other Styles by using Important
- [ ] Use Hex Code for Specific Colors
- [ ] Use Hex Code to Color Elements White
- [ ] Use Hex Code to Color Elements Red
- [ ] Use Hex Code to Color Elements Green
- [ ] Use Hex Code to Color Elements Blue
- [ ] Use Hex Code to Mix Colors
- [ ] Use Hex Code to Color Elements Gray
- [ ] Use Hex Code for Specific Shades of Gray
- [ ] Use Abbreviated Hex Code
- [ ] Use RGB values to Color Elements
- [ ] Use RGB to Color Elements White
- [ ] Use RGB to Color Elements Red
- [ ] Use RGB to Color Elements Green
- [ ] Use RGB to Color Elements Blue
- [ ] Use RGB to Mix Colors

## Responsive Design with Bootstrap

- [ ] Use Responsive Design with Bootstrap Fluid Containers
- [ ] Make Images Mobile Responsive
- [ ] Center Text with Bootstrap
- [ ] Create a Bootstrap Button
- [ ] Create a Block Element Bootstrap Button
- [ ] Taste the Bootstrap Button Color Rainbow
- [ ] Call out Optional Actions with Button Info
- [ ] Warn your Users of a Dangerous Action
- [ ] Use the Bootstrap Grid to Put Elements Side By Side
- [ ] Ditch Custom CSS for Bootstrap
- [ ] Use Spans for Inline Elements
- [ ] Create a Custom Heading
- [ ] Add Font Awesome Icons to our Buttons
- [ ] Add Font Awesome Icons to all of our Buttons
- [ ] Responsively Style Radio Buttons
- [ ] Responsively Style Checkboxes
- [ ] Style Text Inputs as Form Controls
- [ ] Line up Form Elements Responsively with Bootstrap
- [ ] Create a Bootstrap Headline
- [ ] House our page within a Bootstrap Container Fluid Div
- [ ] Create a Bootstrap Row
- [ ] Split your Bootstrap Row
- [ ] Create Bootstrap Wells
- [ ] Add Elements within your Bootstrap Wells
- [ ] Apply the Default Bootstrap Button Style
- [ ] Create a Class to Target with jQuery Selectors
- [ ] Add ID Attributes to Bootstrap Elements
- [ ] Label Bootstrap Wells
- [ ] Give Each Element a Unique ID
- [ ] Label Bootstrap Buttons
- [ ] Use Comments to Clarify Code

## jQuery

- [ ] Target HTML Elements with Selectors Using jQuery
- [ ] Target Elements by Class Using jQuery
- [ ] Target Elements by ID Using jQuery
- [ ] Delete your jQuery Functions
- [ ] Target the same element with multiple jQuery Selectors
- [ ] Remove Classes from an element with jQuery
- [ ] Change the CSS of an Element Using jQuery
- [ ] Disable an Element Using jQuery
- [ ] Change Text Inside an Element Using jQuery
- [ ] Remove an Element Using jQuery
- [ ] Use appendTo to Move Elements with jQuery
- [ ] Clone an Element Using jQuery
- [ ] Target the Parent of an Element Using jQuery
- [ ] Target the Children of an Element Using jQuery
- [ ] Target a Specific Child of an Element Using jQuery
- [ ] Target Even Numbered Elements Using jQuery
- [ ] Use jQuery to Modify the Entire Page

## JSON APIs and Ajax

- [ ] Trigger Click Events with jQuery
- [ ] Change Text with Click Events
- [ ] Get JSON with the jQuery getJSON Method
- [ ] Convert JSON Data to HTML
- [ ] Render Images from Data Sources
- [ ] Prefilter JSON
- [ ] Get Geo-location Data

## Video Challenges: Computer Basics

- [ ] Computer Basics 1: The 4 Basic Parts of a Computer
- [ ] Computer Basics 2: More Computer Hardware
- [ ] Computer Basics 3: Hardware: Chips and Moore's Law
- [ ] Computer Basics 4: Intro to Binary Code
- [ ] Computer Basics 5: Decoding a Binary Number
- [ ] Computer Basics 6: How To Measure Data Size
- [ ] Computer Basics 7: Measuring Data Speed
- [ ] Computer Basics 8: Binary Bytes
- [ ] Computer Basics 9: Types of Computers
- [ ] Computer Basics 10: More on the Motherboard
- [ ] Computer Basics 11: Data Networks
- [ ] Computer Basics 12: IP Addresses
- [ ] Computer Basics 13: How the Internet Works
- [ ] Computer Basics 14: Software Delivery Networks
- [ ] Computer Basics: 
- [ ] Analog vs Digital and File Compression
- [ ] Routers and Packets
- [ ] Source Code
- [ ] Variables In Code
- [ ] What Do Programmers Do?
- [ ] Console and Logging
- [ ] Computer Security

**Comment by BerkeleyTrue** [comment]
Rule #1: Don't just copy and paste! Make sure a solution actually works.

**Comment by BerkeleyTrue** [comment]
Rule #2: Include only the solution. Do NOT include the last function call.

**Comment by pedrro** [comment]
Where I should put the solutions?

**Comment by BerkeleyTrue** [comment]
Each challenge should have it's own solution field which is an array of strings.
see:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/advanced-bonfires.json#L60

**Comment by SaintPeter** [comment]
Should solutions include comments to make them more readable?

**Comment by BerkeleyTrue** [comment]
No. Solutions are for testing only.

**Comment by BerkeleyTrue** [comment]
There is also a hold on adding solutions for challenges other than javascript or bonfires.

**Comment by SaintPeter** [comment]
How should I capture that I have submitted a PR which included a solution on this list?

**Comment by SaintPeter** [comment]
Truncate a String Solution added: #4214

**Comment by vignesh-m** [comment]
added solution for Exact Change [#4241](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4241)

**Comment by ribeirojpn** [comment]
added solution for Bonfire:Check for Palindromes: #4419

**Comment by nuku89** [comment]
Where are the challenge numbers?

**Comment by josectello** [comment]
Noticed there hasn't been a comment since November of this past year. May I still contribute to solutions for the basic-bonfires.json?

**Comment by SaintPeter** [comment]
I am pretty sure that the list is no longer accurate.  I would say that if you can find a challenge with no solution listed, more power to ya!

Note:  HTML, CSS, and jQuery Challenges (anything that requires the DOM) cannot be tested, so please don't add solutions to them.  Be sure to test your solutions with `npm run test-challenges`

**Comment by josectello** [comment]
I looked through a few times but it looks like the solutions are all taken care of. Thanks!

**Comment by Jago-Kosolosky** [comment]
I would suggest closing this issue as it is now still open and confirmed as easy so it might attract future first time contributors only to be disappointed.

**Comment by BerkeleyTrue** [comment]
I'm closing this for now until I get around to implement a test framework that runs the solutions using the same framework as the site.

Happy Coding
