### ISSUE TITLE
Certification page display issues - background and bottom padding

### ISSUE THREAD

**Issue by rtpHarry** [freeCodeCamp/freeCodeCamp#41125]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
There is some display issues with the certification page, for example:

 - The background is set to height 100% which means it cuts off at strange places depending on the browser size.
 - There is no spacing at the end of the page so the last line of text just bumps into the bottom of the browser window

**To Reproduce**

1. [View a certificate page](https://www.freecodecamp.org/certification/rtpharry/responsive-web-design) (tested on Mac/Chrome)
2. Scale the browser window so it has a scrollbar
3. Scroll down and see that the white background cuts off (see screenshot 1 below)
4. Scroll to the end of the page to see that the page doesn't have any padding (see screenshot 2 below)

**Expected behavior**

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/1038062/107943883-3aa29880-6f85-11eb-9e82-8791a3a7b74d.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/1038062/107943921-4726f100-6f85-11eb-9223-8339197e2fe2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**

**Comment by manakwadhwa2002** [comment]
@rtpHarry Sir,
Can you please share the link of the css file for [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/5539dbf086a69390170824cf79be0b6e4a326c12/client/src/client-only-routes/ShowProjectLinks.js) file.

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb Should this be something resolved using a `Spacer` component, or via CSS?

Also, are there any other aspects of this which could do with re-arranging/styling?

**Comment by ahmadabdolsaheb** [comment]
@ShaunSHamilton, yes some spacers at the bottom should do the trick. Other than the issue @rtpHarry mentioned regarding the sections running together, i cannot think of anything else.

P.S the donation element on the top of the certification should be reviewed after the fix.

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by rtpHarry** [comment]
@manakwadhwa2002 I'm not sure exactly what you mean, but looking on the page, there isn't an external file for the css, its embedded into the page.

It seems that unticking this will fix the design:

![image](https://user-images.githubusercontent.com/1038062/108213572-17afea00-7127-11eb-8444-94d0935eeaea.png)

Or alternatively setting it to min-height:

![image](https://user-images.githubusercontent.com/1038062/108213765-4c23a600-7127-11eb-87b0-b7cea084009b.png)

**Comment by ahmadabdolsaheb** [comment]
A solution that would target the `certificate-outer-wrapper` and its children is recommended to avoid unwanted changes to the other parts of the platform.

**Comment by ieahleen** [comment]
there is also this, can be addressed here or better a new issue?
https://forum.freecodecamp.org/t/the-responsive-webdesign-certificate-is-not-responsive/447635
