### ISSUE TITLE
z-index clash on notification bar vs menu

### ISSUE THREAD

**Issue by rtpHarry** [freeCodeCamp/freeCodeCamp#41126]
**Describe the bug**
The notification bar has a higher z-index than the menu, making portions of it inaccessible without dismissing a notification.

**To Reproduce**
1. Set your profile to private
2. Attempt to view your certificates
3. After the notification appears, open the menu

**Expected behavior**
I reported this on the forums where [it was suggested](https://forum.freecodecamp.org/t/site-bug-z-index-for-menu-vs-notification/446388) this was not a bug, but it's not how I would expect the z-index to work. 

It's a notification bar not a modal, so it shouldn't block you from doing other activities on the site.

**Screenshots**
![image](https://user-images.githubusercontent.com/1038062/107944323-d8966300-6f85-11eb-9d2b-262b979c3862.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**

**Comment by manakwadhwa2002** [comment]
We can change the z index of the menu so that it appears over the notification or we can resize the notification when the menu is opened using js and css

**Comment by ahmadabdolsaheb** [comment]
Although this is not a bug, it could definitely be optimized.

It seems like the only way  we could have the UI react this way would be by opening the menu after the flash message has been displayed.

So the user sees the the flash message and chooses to ignore it and open the navigation.

I think the user should be able to see the full nav in that situation. What do you think @ShaunSHamilton?

**Comment by ShaunSHamilton** [comment]
> What do you think @ShaunSHamilton?

@ahmadabdolsaheb I could go either way. At the end of the day, the notification is not going anywhere, until the Camper closes it.

I do not think changing this is as simple as increasing the `nav` `z-index`, as it is already set to 1000. So, I am happy for this to be opened up for _help wanted_.

**Comment by JoshuaPelealu** [comment]
I think where the notification is already where it is at, it's a notification, and it should attract the user. It also have an element to dismiss it, when needed. 
But to improve this, I would suggest making the notification bar have a timeout function where it would dismiss itself after a certain amount of time. This could be easily implemented and would help the user be able to access the higher part of the menu bar after a certain amount of time.

**Comment by rtpHarry** [comment]
I think it should just go over the top of it because in this case I was actually taking the suggested action of the notice bar - it said to go to my profile to make it public to view the certificate.

It's not a modal operation, it doesn't require me to take some action to continue using the site. I am free to ignore it, so it shouldn't impact any other aspects of my site usage. If I'm not free to ignore it then it should be designed as a full screen blocking ui.

**Comment by rtpHarry** [comment]
Besides everything else, the thing that it blocks in the menu is the "donate" link, which considering the number of times I've been asked to become a member, seems like it is a high priority for visibility.

**Comment by raisedadead** [comment]
The nav menu should be the top most element and should show on top of that notification, which the user should dismiss later, when convenient to them.

**Comment by JoshuaPelealu** [comment]
One fix I can see working is changing the z-index of the Flash itself into 900, and it will still be in front of everything else except for the header and menu.

**Comment by manakwadhwa2002** [comment]
Instead of this we can automate the notification to go automatically once the nav bar button is clicked.

**Comment by JoshuaPelealu** [comment]
We do not want to remove the notification unless the user removes it by themselves...
