### ISSUE TITLE
Convert JSON Data to HTML regex typo

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41133]
Challenge link: https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/convert-json-data-to-html

Code that fails:
```
        // Add your code below this line
        json.forEach(function(val) {
          // Adding each object keys
          var keys = Object.keys(val);
          // Generating new html
          html+= "<div class = 'cat'>";
          // Adding the custom html to each key
          keys.map(function(key) {
            html+= "<strong>" + key + "</strong>: " + val[key] + "<br>";
          });
          html+= "</div><br>";
        });
        // Add your code above this line
```
Code that passes:
```
        // Add your code below this line
        json.forEach(function(val) {
          // Adding each object keys
          var keys = Object.keys(val);
          // Generating new html
          html+= "<div class = 'cat'>";
          // Adding the custom html to each key
          keys.map(function(key) {
            html += "<strong>" + key + "</strong>: " + val[key] + "<br>";
          });
          html+= "</div><br>";
        });
        // Add your code above this line
```

Issue: `assert(code.match(/html\s+?(\+=|=\shtml\s\+)/g));`

Correction: `assert(__helpers.removeWhiteSpace(code).match(html(\+=|=html\+))`

Challenge file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/convert-json-data-to-html.md

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by RandellDawson** [comment]
It would need to be `__helpers.removeWhiteSpace`
