### ISSUE TITLE
Certificate Project Modal Bug

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41138]
When trying to view a solution to the JS Algorithms section on the certificate: https://www.freecodecamp.org/certification/sky020/javascript-algorithms-and-data-structures
```
react-dom.production.min.js:209 TypeError: c is not a function
    at ProjectModal (ProjectModal.js:41)
    at Ki (react-dom.production.min.js:153)
    at vo (react-dom.production.min.js:261)
    at cu (react-dom.production.min.js:246)
    at ou (react-dom.production.min.js:246)
    at Zo (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ql (react-dom.production.min.js:122)
    at Hl (react-dom.production.min.js:123)
```
Appears to be related to the introduction of the `t` library/function.

I am looking into resolving this.

**Comment by ojeytonwilliams** [comment]
Nice catch, Shaun.  We should create some tests to prevent regressions.

**Comment by nhcarrigan** [comment]
Commenting here for contributors:

The bug was resolved in #41139 - however we would still need to add tests to ensure this flow is validated in our CI.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams I keep meaning to create tests for a lot of my previous PRs. However, every time I get time to do it, I encounter issues with Cypress in GitPod - still a work-in-progress for certain workflows.

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton that's totally fine.  Having tests is always great, but I know that you have to work within the limits of your machine.

We just need to keep tracking spots (like this) where the testing is lacking. If we do, then contributors who'd like to help, but are not sure where, can always pick them up.
