### ISSUE TITLE
Regex should accept https and http

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41132]
**Describe your problem and how to reproduce it:**
I was assisting a camper on the forum for this lesson and they said they couldn't pass the test. They said they copied the solution exactly from the video but the video is wrong. It uses a different url than the challenge. I think it would be best to remove it so campers are not confused. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

Correct instructions:
<img width="459" alt="Screen Shot 2021-02-15 at 11 27 24 AM" src="https://user-images.githubusercontent.com/67210629/107986407-d5e53f00-6f80-11eb-9294-21d57f00fffe.png">

Video Instructions:
<img width="890" alt="Screen Shot 2021-02-15 at 11 31 00 AM" src="https://user-images.githubusercontent.com/67210629/107986645-5a37c200-6f81-11eb-8b8f-601652766d6e.png">

**Comment by RandellDawson** [comment]
The second test's assert is:
```js
assert(/https:\/\/(www\.)?freecatphotoapp\.com/gi.test($('a').attr('href')));
```

I would not mind changing the regex to allow `http` or `https` in order to not remove the video link.

**Comment by jdwilkin4** [comment]
Hi @RandellDawson ! 

I think that could work. 
But now that I think about it, would it be easier to just remove the s completely from the http. 
That way the video matches up exactly with the challenge and if the user makes a mistake elsewhere in the code we don't also yell at them for the incorrect url. 

Just a thought :) 

Thanks!

**Comment by RandellDawson** [comment]
Honestly, we should have never used `http` as you should never link to `http` anymore because of SEO and security for your site's users.  I think leave it `https` but accept `http` or `https`.

**Comment by jdwilkin4** [comment]
Sounds good

**Comment by lasjorg** [comment]
Just an FYI, I mentioned this long ago https://github.com/freeCodeCamp/freeCodeCamp/issues/35642

But at the time some people were against letting the test accept both protocols.

**Comment by RandellDawson** [comment]
@lasjorg Good point.  My opinions since I wrote that comment have changed since working on the project-based curriculum.

**Comment by alirezaghey** [comment]
Apparently, this is already resolved but not closed.

**Comment by lasjorg** [comment]
Closed by https://github.com/freeCodeCamp/freeCodeCamp/pull/41191
