### ISSUE TITLE
"Combine Arrays with the Spread Operator" bug

### ISSUE THREAD

**Issue by M0hanad0** [freeCodeCamp/freeCodeCamp#41135]
**Describe your problem and how to reproduce it:**
I was solving the **"Combine Arrays with the Spread Operator"** challenge in the _Basic Data structures_ course in the **JavaScript Algorithms and Data Structures Certificate**.

```js
function spreadOut() {
    let fragment = ['to', 'code'];
    let sentence = ["learning", ...fragment, "is", "fun"]; // Change this line
    return sentence;
}

console.log(spreadOut());
```

Here is the code I've submited

**Add a Link to the page with the problem:**
[Challenge link](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/combine-arrays-with-the-spread-operator)

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 85.0.1 (64-bit)
* Operating System: Manjaro Linux

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![FreeCodeCamp bug](https://user-images.githubusercontent.com/41490275/108002292-3bc4db80-7000-11eb-9152-d2e57195627d.png)

**Comment by moT01** [comment]
I could not reproduce this on Firefox, Safari or Chrome on High Sierra - or Firefox on Ubuntu. Want to give it another try @M0hanad0? To see if it's still a problem. Maybe with another browser.

**Comment by JoshuaPelealu** [comment]
As @moT01 said, I have tried this in Firefox, Firefox Dev Edition, Chrome and I cannot reproduce the problem. Try refreshing your cache, or maybe disable some extensions.

**Comment by M0hanad0** [comment]
Okay Thank you. @moT01 , @JoshuaPelealu I will try.
