### ISSUE TITLE
i18n: Donate button on Spanish news links to English donate page

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/freeCodeCamp#41142]
from Español news page clicking the 'donar' button will redirects to an English version donation page.

This issue happens for mobile and desktop.

**Comment by RafaelDavisH** [comment]
https://user-images.githubusercontent.com/6822714/108131147-b70ca880-7065-11eb-82ee-ca33aca1e6c8.mp4

**Comment by ahmadabdolsaheb** [comment]
We would need to add a separate donation link for each language: 
https://github.com/freeCodeCamp/news-theme/blob/be5fd6f1364342261e69e7ff118018ae68b50b77/locales/es.json#L20

**Comment by raisedadead** [comment]
I think we should be creating a **non-public** Crowdin project to configure it to be able to track these changes. @nhcarrigan or @RandellDawson if one of would you be interested (when you get time of course).

**Comment by RandellDawson** [comment]
This seems like more of something that should be handled by a config file instead of via Crowdin.  Why not put stuff like this in a config file?

**Comment by raisedadead** [comment]
Correct - I missed stating the what I thought is the standard approach now on. 

We need to put stuff that is non-translatable separate from the translatable bits, in most of our codebases that need i18n. Anything that is translatable should ideally be done on Crowdin. 

We can begin by making a non-public project for such translation work before considering if it should go public at some point.

I will let @ahmadabdolsaheb confirm, on how these theme files and i18n should be split such that translatable stuff can be configured to be uploaded to Crowdin and the rest like the URLs, etc. can remain in a config file.

**Comment by ahmadabdolsaheb** [comment]
Sure. @scissorsneedfoodtoo since you have more experience with setting i18n for handlebars, what do you think is the best course of actions here. The translation files seem to be pre defined. Would saving all text phrases in the UI in one object work for the ghost theme?

**Comment by scissorsneedfoodtoo** [comment]
@ahmadabdolsaheb, the translation helper and file structure for Handlebars/Ghost is a bit more restrictive than what we're doing in the main repo. But I'm pretty sure we could separate things like the footer and donor links, along with some of the Algolia config strings into a separate config file or files.

We'll need to test it out to confirm, though.

**Comment by scissorsneedfoodtoo** [comment]
Just deployed https://github.com/freeCodeCamp/news-theme/pull/50 to all News sites. Will mark this as closed.
