### ISSUE TITLE
Unexpected behaviour  while updating settings

### ISSUE THREAD

**Issue by Aanandgupta** [freeCodeCamp/freeCodeCamp#41156]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
While I was updating settings i noticed that when we select multiple buttons(that provides options of public or private) at a time
the switching of their styling was not appropriate 
**To Reproduce**
1. Go to 'https://www.freecodecamp.org/settings'
2. Click on 'buttons that ask to select public or private do it a bit faster' 
3. You will notice that styling is not switched between the selected and unselected buttons
**Expected behavior**
It should be showing only the one selected as selected not both of them
**Screenshots**

**Additional context**
It might be be fixed if we use synchronous code
![Screenshot (146)](https://user-images.githubusercontent.com/71023799/108249370-00025100-717b-11eb-828a-18249e77d745.png)

**Comment by JoshuaPelealu** [comment]
I can confirm that this is happening, while I wouldn't be to troubled about the styles, the problem goes deeper than that. After the styles does not appropriately change, it wouldn't let me change it, even if I try pressing it multiple times.
![image](https://user-images.githubusercontent.com/45566099/108251657-acb1e380-7125-11eb-8604-c314e529d9d5.png)

**Comment by nhcarrigan** [comment]
Hello there,

Thank you for reporting this. We are going to close this as a duplicate of #40764
