### ISSUE TITLE
Add i18n keys to ShowProjectLinks component

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41155]
This [ShowProjectLinks component](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/client-only-routes/ShowProjectLinks.js#L162) is mostly untranslated. Keys should be added to [the JSON files](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/translations.json) and used in the component so it can be translated. There's some [docs that may be helpful here](https://contribute.freecodecamp.org/#/how-to-translate-the-website).

![Screen Shot 2021-02-17 at 11 46 47 AM](https://user-images.githubusercontent.com/20648924/108245388-d7943b80-7115-11eb-8b7b-e913b483e6cc.png)

**Comment by errmayank** [comment]
@moT01 Do the translation first needs to be done on [Crowdin](https://freecodecamp.crowdin.com/learn-ui) and after that make necessary changes to `ShowProjectLinks`?

**Comment by moT01** [comment]
I don't believe so - you can add the keys to the JSON files for all the languages and use English values for now. Then, changes the component so it uses those keys. After that, the next time the files are uploaded to crowdin, they will contain the new strings so they can be translated.

**Comment by RandellDawson** [comment]
Yes.
