### ISSUE TITLE
Certificate for Resposive web design cannot be claimed

### ISSUE THREAD

**Issue by LexDemonica** [freeCodeCamp/freeCodeCamp#41150]
Hi there.
I just completed my responsive web design along with all of the projects and there doesn't seem to be a way for me to claim a certificate. All units and projects are marked as 100% complete. Alas no way to claim a certificate.

It may be just me overlooking something while being buried in the learning process. But i was really excited about that first certificate. Even without them the curriculum is rewarding but the cert is a nice touch and it would be lovely to have one.

**Comment by nhcarrigan** [comment]
You need to go to your account settings to claim your certificate. Before you can do so, you also need to agree to the Academy Honesty Pledge.

To make your certificate appear in your profile, you need to have your profile set to public.

**Comment by LexDemonica** [comment]
Signed the pledge and the profile is set to public. I still can't see anywhere to claim the cert

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/108236763-1d440a80-70fc-11eb-91c7-dc113b581c84.png)

Underneath the Academic Honesty Pledge you should see the certification sections.

**Comment by LexDemonica** [comment]
I knew i missed a spot thanks for sorting the noob out. much appreciated
