### ISSUE TITLE
Private timeline doesn't hide certs

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41171]
The note on the settings page next to the `timeline` option says `"Your certifications will be disabled, if set to private."` But if you set your timeline to private, you can still view your certifications.

More discussion on the linked issue

**Comment by moT01** [comment]
Continued from discussion on linked issue...

I think we would be fine to just remove the message next to the setting.

**Comment by nhcarrigan** [comment]
@ShaunSHamilton brought up a valid point [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/40403#issuecomment-779957353): If I make my timeline private, my project links also disappear from the bottom of my certificate. 

Being someone who isn't terribly concerned with privacy settings (if I don't want it seen, I don't put it online) I'm not really understanding the use case for hiding my timeline, so I'm not sure which is the best approach:

1. Remove the message from the setting, and make the project links persistent on the certification itself

2. Keep the message, and disable the certificate entirely when the timeline is set to private.

**Comment by dsachin** [comment]
I think removing the message should be opted, as we do have the option to make the certificate public/private

**Comment by moT01** [comment]
I'm quite certain that anytime a certification is public, the projects submitted to complete it should be visible at the bottom.

I vote for `#1`, remove the message and make the projects persistent.

**Comment by ShaunSHamilton** [comment]
As an aside: Should it be possible to un-publicise certificates? That is, should it be possible to set profile/certifications private after claiming a cert?

**Comment by moT01** [comment]
I think that's fine @ShaunSHamilton, but others can certainly weigh in. What would happen then if you set your whole profile to private - the certs stay public? I think it's nice for users to be able to make public or private what they choose to.

**Comment by ShaunSHamilton** [comment]
![image](https://user-images.githubusercontent.com/51722130/108771184-35c88080-7553-11eb-8138-701a8ff071c1.png)

This is what happens, when I set Certifications to private, and try to view a cert.

**Comment by moT01** [comment]
The merged PR to fix this issue hides the message. If I make my timeline private, either locally or on .dev, the projects are shown on the cert - so I'm not sure if that second part of @nhcarrigan's `#1` solution is still a problem. If it turns out to be, we should make another issue for it.
