### ISSUE TITLE
Refactor Project Links to Single Source

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41174]
Original Discussion: https://github.com/freeCodeCamp/freeCodeCamp/issues/41159

Some thoughts discussed on previous PRs and chat:

Validate example links are not submitted
- This would mean less maintenance for the project links (we could remove the tests that look for the example)
- Prevent Campers from submitting the CodePen boilerplate, and not saving their project code

Store project links within one config file
- Could be linked to DRYing out the .md files (related: #40860)

<details>
  <summary>Example config</summary>

```
const frontendLinks = {
  link: 'https://codepen.io/freecodecamp/example',
  name: 'Tribute Page', // Doubles as placeholder if necessary
  id: 1234,
}
```

This is more just me thinking out-loud.

</details>

**Comment by JoshuaPelealu** [comment]
Here's another example using these challenge 
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-product-landing-page.md

```json
{
    'responsive-web-design':  [
        {
            'link': 'https://codepen.io/freeCodeCamp/full/zNBOYG',
            'name': 'build-a-personal-portfolio-webpage',
            'id': 'some-id (Could be challenge-id)'
        },
        {
            'link': 'https://codepen.io/freeCodeCamp/full/RKRbwL',
            'name': 'build-a-product-landing-page',
            'id': 'some-id (Could be challenge-id)'
        }
    ]
}
```

Then on the `.md` files we can do something like
```md
Objective: Build a CodePen.io app that is functionally similar to this: {{ example-project }}
```

This is just an example, anything can be changed around.
