### ISSUE TITLE
Link to External Pages with Anchor Elements test is too permissive

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#41173]
**Describe your problem and how to reproduce it:**
the challenge can be passed with an url like `href="https://freecatphotoapp.com."`, or `href="https://freecatphotoapp.com/stuuyuuufushtfgh"`

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements

**Suggestion:**
```diff
-assert(/https:\/\/(www\.)?freecatphotoapp\.com/gi.test($('a').attr('href')));
+assert(/^https:\/\/(www\.)?freecatphotoapp\.com$/i.test($('a').attr('href')));
```

 - add anchors to make sure that the link is exactly that with no extra stuff around
 - remove the `g` tag which in this case is just useless
 - ~[possibly] add the possibility to have an `http` link pass, seeing that the video hint show that link (it shows an example `https`, and then it deletes the `s`)~

**Comment by nhcarrigan** [comment]
> [possibly] add the possibility to have an http link pass, seeing that the video hint show that link (it shows an example https, and then it deletes the s)

I'd vote against this one, personally. The `http` vs `https` often trips up campers, but I think that's an important bit that calls attention to the fact that the protocol matters.

> add anchors to make sure that the link is exactly that with no extra stuff around
> remove the g tag which in this case is just useless

These I very much agree with and, provided no one disagrees, would gladly open this up to contributions.

**Comment by ieahleen** [comment]
> I'd vote against this one, personally. The `http` vs `https` often trips up campers, but I think that's an important bit that calls attention to the fact that the protocol matters.

True, so maybe it warrants removing the video or changing it. In the video it clearly show the deleting of the `s` from `https` and folsk that follow the videos floods the forum asking why the video solution doesn't work

**Comment by nhcarrigan** [comment]
Huh the guide post is outdated too.

I'd be okay with one or the other:
- Remove video, update guide post, leave challenge as expecting `https`
- Keep video and guide post, modify challenge to expect `http`

But I do think we should allow only one protocol, and the other should fail.

**Comment by ieahleen** [comment]
it may be less disruptive to people that use video hints to leave the video

I'm fine with either way

**Comment by RandellDawson** [comment]
I like allowing either `http` or `https`.

**Comment by JoshuaPelealu** [comment]
Leaving to allow either `http` or `https` is IMO better to avoid confusion in errors because even if you used `http` in your links, it will usually redirects into https if the target location have an SSL certificate.

**Comment by nhcarrigan** [comment]
Alright looks like I'm in the minority here 😅 

So, this issue can be resolved with:

- add anchors to make sure that the link is exactly that with no extra stuff around
- remove the g tag which in this case is just useless
- add the possibility to have an http link pass, seeing that the video hint show that link (it shows an example https, and then it deletes the s)

**Comment by nhcarrigan** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
