### ISSUE TITLE
Add definition popover feature to challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4117]
For specific terms, we can create bootstrap popovers to allow you view their definitions (rather than having to look them up).

Here's an example:

![](https://www.evernote.com/l/AlymDvksc1pJxbBtjvkiwTTbustwTN8u6bkB/image.png)

Here's the working code: http://jsfiddle.net/v5L7m/263/

The catch is we need to create JavaScript in main.js that will allow for an infinite number of links with popovers within the same challenge description.

**Comment by SaintPeter** [comment]
Please flag "Help Wanted".

**Comment by olingern** [comment]
Hey @QuincyLarson, I've been getting acquainted with fcc's code today and thought this might be a place where I could start to contribute. I have a couple of questions.

I see that Main.js is some jQuery and some AngularJS. I also see that the project is aiming to convert to React. Do you guys have a preferred framework for this feature? 

Second - Would there be an rest call to grab a list of words + modal information available? My only thought would be that it get expensive with many words.

**Comment by jbmartinez** [comment]
I've not messed with the Main.js file, but it's possible to have any number of links with popovers using a class:
```html
<a class="definition" data-toggle="popover" data-trigger="focus" title="Dismissible popover" data-content="Some content">Dismissible popover</a>
```
and then:
```javascript
$('.definition').popover();
```
Or even without using a class at all:
```javascript
$('[data-toggle="popover"]').popover();
```

Challenge descriptions already contains HTML code, for example:
```json
{
      "id": "bad87fee1348bd9aedf08833",
      "title": "Fill in the Blank with Placeholder Text",
      "description": [
        "Web developers traditionally use <code>lorem ipsum text</code> as placeholder text."
      ]
```
Since each challenge builds on top of previous ones, I think it is not necessary to give the same definition in more than one challenge. So, the definitions could be inserted in each description in the `seed/challenges` directory, like this:
```json
"description": [
    "<a class='definition' tabindex='0' data-toggle='popover' data-trigger='focus' title='Dismissible popover' data-content='And here's some amazing content. It's very engaging. Right?'>Dismissible popover</a> description continues..."
]
```

This is somewhat verbose though, but can be done manually. Ideally, it can be done at build or deploy time before seeding the database.

Another option is to add an array of definitions and populate them at run time with jQuery/angular/react/whatever:
```json
"description": [
    "<a data-definition='some_definition'>Dismissible popover</a> description continues..."
],
"definitions" : [
    "some_definition: {
        "title": "A title",
        "content": "A nice definition"
    }
]
```

**Comment by djfordz** [comment]
I'm going to work on this.  What exactly needs the popovers? all html definitions? Bootstrap definitions?Javascript as well?

**Comment by olingern** [comment]
Sorry for going mia here. 

@jbmartinez Thanks for the information! Still a little in the dark on the source of the terms / descriptions. Ideally, they'd be maintainable and easy to add, edit, delete, yes?

Per @QuincyLarson : "...for an infinite number of links with popovers within the same challenge description."

Does there (or should there) exist a form where someone can select an existing or create a new term with a description?

**Comment by SaintPeter** [comment]
I think what I'd like to see is leveraging the `<def>` html element and some javascript wrapper to either pull definitions from the challenge, or from a central database.  The raw markup is too messy to clutter up our description text with.

I like @jbmartinez's markup:
```js
"definitions" : [
    {"some_definition": {
        "title": "A title",
        "content": "A nice definition"
        "wiki": "wiki/full-definition-path"
    } }
]
```
Where the `some_definition` is the keyword that the JS looks up.  Or maybe as the challenges are read in there is some pre-processing?

The advantage of a central database (probably a `defintions.json` file) is that it's easy to maintain.  It also vastly simplifies authoring challenges.  Just drop a `<def>` tag around something and you don't even have to have defined it yet.  Just let the pre-processing skip over anything it can't find (or leave it highlighted in some way).  We could use it like we use code tags now to highlight keywords and, as we fill in the glossary, they get pretty popups.

**Comment by atjonathan** [comment]
@QuincyLarson why was this closed?

**Comment by QuincyLarson** [comment]
@atjonathan let's keep this closed. Our goal is to have challenge instructions that minimize jargon and clearly explain newly introduced terms: [Challenge Style Guide](https://github.com/FreeCodeCamp/CurriculumExpansion/blob/master/challenge-style-guide.md)
