### ISSUE TITLE
Create a class for embedding code mirror text areas into challenge description

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4118]
Instead of showing multiple lines with <code> at their beginning and </code> at their end, we want to be able to embed multi-line code examples into a single code mirror text area.

For example: 

```
"title": "Use a CSS Class to Style an Element",
      "description": [
        "Classes are reusable styles that can be added to HTML elements.",
        "Here's an example CSS class declaration:",
        "<code>&#60;style&#62;</code>",
        "<code>&thinsp;&thinsp;.blue-text {</code>",
        "<code>&thinsp;&thinsp;&thinsp;&thinsp;color: blue;</code>",
        "<code>&thinsp;&thinsp;}</code>",
        "<code>&#60;/style&#62;</code>",
        "You can see that we've created a CSS class called <code>blue-text</code> within the <code>&#60;style&#62;</code> tag.",
```

We should be able to wrap these lines of code inside a div element with a class that applies a single code mirror text area to its contents. Currently they render like this: 

![](https://www.evernote.com/l/AlxnBU4SNg5Ixr3x6kXi_vYszcTzBe_r57wB/image.png)

**Comment by bugron** [comment]
Closing this issue. We're using `blockquote`'s for code examples.
