### ISSUE TITLE
Hint in "tore Multiple Values in one Variable using JavaScript Arrays" is outdated

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#41192]
**Describe your problem and how to reproduce it:**
the challenge contains 
>Refer to the example code in the text editor if you get stuck.

There is no example code in the editor

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/store-multiple-values-in-one-variable-using-javascript-arrays

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/26656284/108597363-f64e3880-7388-11eb-9d45-2b21c0e90333.png)
![image](https://user-images.githubusercontent.com/26656284/108597368-fd754680-7388-11eb-87b6-503d102d0a8d.png)

**Comment by RandellDawson** [comment]
Let's just remove the `Hint`.

**Comment by RandellDawson** [comment]
I have opened this issue up for first timers to contribute.

**Comment by CreaTorAlexander** [comment]
First timers contributing to this repository or first timers in general?

**Comment by Sembauke** [comment]
![Knipsel](https://user-images.githubusercontent.com/46919888/108600706-f5bd9e00-7398-11eb-99d3-6c46f70e5583.PNG)

This is weird the sample code does exist on my view. Which broswer are you using?

**Comment by nhcarrigan** [comment]
@CreaTorAlexander First timers to this repository. 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by RandellDawson** [comment]
> First timers contributing to this repository or first timers in general?

To this repo.

**Comment by nhcarrigan** [comment]
@Sembauke That is an example in the challenge description - but the `hint` refers to a non-existent sample in the *editor* and should thus be removed.

**Comment by CreaTorAlexander** [comment]
Well, then I would like to work on it 👍

**Comment by ieahleen** [comment]
@CreaTorAlexander 
issues are not assigned, the first comprehensive PR is reviewed
