### ISSUE TITLE
(i18n): Potential Site Performance Improvements

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41213]
As _your average dev_, I spend a lot of my time with my devtools open. As _your un-average dev_, I read way too much minified JS, which is why I stumbled upon the freeCodeCamp sourcemap.

I notice it ships with all languages included. Perhaps this does not create as large a performance impact as I think, but once we add more languages, surely it might?

I assume linking to the file like this does not work: https://www.freecodecamp.org/app-67cba5e849cb47817635.js
So, it is just the largest `.js` file downloaded when on `freecodecamp.org/` that is not `preset-env`. It is about `552kB` (over network).

**Comment by ojeytonwilliams** [comment]
I could be wrong, but I don't believe sourcemaps get loaded until you open the console.  If someone could confirm that's the case, I think they're worth keeping.

**Comment by RandellDawson** [comment]
@ojeytonwilliams I believe you are correct.

**Comment by ShaunSHamilton** [comment]
Ah. Yes, I see... well, then ignore me 😄 
Thank you, both, for pointing that out.
