### ISSUE TITLE
i18n docs do not render images

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41228]
![image](https://user-images.githubusercontent.com/63889819/108770834-abaaf880-750f-11eb-9e8c-0cf8cc1504a9.png)

Our local images currently do not render in the translated documentation views. This is due to the use of a relative link, which breaks with the new path generated for i18n pages.

A couple of potential fixes:
- Use an absolute link (https://contribute.freecodecamp.org/images/<filename>). This, IMHO, is the most effective.
- Have translators fix the link in the translation flow.
- Host the images through our CDN and fetch them.

**Comment by raisedadead** [comment]
We should use the `https://contribute.freecodecamp.org/images` absolute path.

**Comment by nhcarrigan** [comment]
Sounds good. I'll get a PR up shortly.
