### ISSUE TITLE
Continued from discussion on linked issue...

### ISSUE THREAD

**Issue by pap0135** [freeCodeCamp/freeCodeCamp#41229]
Continued from discussion on linked issue...

I think we would be fine to just remove the message next to the setting.

_Originally posted by @moT01 in https://github.com/freeCodeCamp/freeCodeCamp/issues/41171#issuecomment-781425956_

**Comment by nhcarrigan** [comment]
Hey there,

We are going to close this issue in favour of the linked discussion. Please keep all discussion on the relevant issue for visibility and ease of communication.

If you feel there is a separate topic that needs to be discussed in this issue, feel free to provide the relevant information and request we reopen this issue.
