### ISSUE TITLE
JavaScript QA projects cannot retrieve source files

### ISSUE THREAD

**Issue by studio1202** [freeCodeCamp/freeCodeCamp#41236]
The [JavaScript QA projects ](https://www.freecodecamp.org/learn/quality-assurance/#quality-assurance-projects) contain some (apparently unused) routes to fetch source code files in file [fcctesting.js](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/blob/gomix/routes/fcctesting.js) .

Those routes do not appear to work, because they search files as if the source file was located in the project root. I created a [sample patch](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/compare/gomix...studio1202:gomix-bugfix) to illustrate the problem and propose a fix.

(The patch also addresses another small issue in file server.js for which I will open another bug report.)

**Comment by gikf** [comment]
As that's not used for anything anyway it might be better to just remove it all together.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
