### ISSUE TITLE
JavaScript QA projects do not print the listening port if it is not specified

### ISSUE THREAD

**Issue by studio1202** [freeCodeCamp/freeCodeCamp#41237]
The [JavaScript QA projects ](https://www.freecodecamp.org/learn/quality-assurance/#quality-assurance-projects) print the server port number in file [server.js](https://github.com/freeCodeCamp/boilerplate-project-library/blob/gomix/server.js).

The port number is only printed when the user specifies it as environment variable. In the other cases the server prints `undefined`. As a consequence the user does not know on which port to open the application in the browser. I created a [sample patch](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/compare/gomix...studio1202:gomix-bugfix#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406f) to illustrate the problem and propose a fix. Another solution would be to use `listener.address().port` .

(The patch also addresses other issues in file fcctestingjs for which I opened a separate bug report.)

**Comment by JustinSingleton303** [comment]
is this still an open ticket or has a pull request been submitted to close this issue?

**Comment by studio1202** [comment]
The reported bug seems still [there](https://github.com/freeCodeCamp/boilerplate-project-library/blob/gomix/server.js). I leave it to you guys.

**Comment by moT01** [comment]
The four above PR's should close this issue after merged.
