### ISSUE TITLE
An easy way for freeCodeCamp contributors to quickly deploy & preview backend+frontend changes for each PR

### ISSUE THREAD

**Issue by emiquelito** [freeCodeCamp/freeCodeCamp#41240]
**Is your feature request related to a problem? Please describe.**

freeCodeCamp contributors, students and developers are currently not able to quickly deploy & preview backend+frontend changes for each PR.

**Describe the solution you'd like**

Hello freeCodeCamp Community!

I'm with [Squash.io](https://www.squash.io/) and we wanted to support freeCodeCamp by providing on-demand test environments for each Pull Request (i.e: a complete staging environment for each PR, running your full stack). Our service is free for open source projects and we would be able to increase our standard limits as needed to provide great user experience for your developers, students and contributors.

Here is how it works: you push a branch of code, create a Pull Request and Squash automatically posts a comment with a unique URL where you can test the branch changes in isolation (it usually takes just a few minutes for an environment to spin up):

![squash-url](https://user-images.githubusercontent.com/98694/108773052-0c8bfe00-751b-11eb-8fad-7334b11b80bf.png)

You may customize this comment to include links to different apps:

![custom-pr-comments-full](https://user-images.githubusercontent.com/98694/108907157-fcd5ed80-75de-11eb-8118-397b212c68c4.png)

Squash can also spin up a new environment for each commit within a PR, and give you a pass or fail if it can receive a success HTTP response. You can also run any existing front-end tests (Selenium, TestCafe, etc.) on top of this Squash environment.

![squash-check2](https://user-images.githubusercontent.com/98694/108773348-6ee4fe80-751b-11eb-92e3-d9262192264e.png)

**We can set it up for you**

Let me know if you like the idea of using Squash on this project. If so, we would be happy to create a Pull Request with a Squash YAML file so you don't have to invest any time on this.

**Describe alternatives you've considered**
Squash is different than traditional CI/CD tools in the sense that:

* we give you a unique testing URL for each branch of code
* we spin up a new VM for each branch of code and deploy your full stack: database (and any other services you might have), microservices and the front-end - and the environment immediately starts responding to HTTP requests.
* The environment [remains active for several hours ](https://www.squash.io/auto-shutdown-policies/) giving you enough time to test it, or you can just restart it at any time by just clicking on the unique deployment URL.

Please let me know if you think this could be useful to the freeCodeCamp community and we would be happy to support you.

**Comment by ieahleen** [comment]
we already have GitPod, what does your software has that GitPod doesn't?

**Comment by raisedadead** [comment]
Hi @emiquelito 

Thanks for taking the time to open this PR. I went ahead and looked at bunch of other PRs on the other open-source repositories for this product.

Ref: https://github.com/joomla/joomla-cms/issues/32495, https://github.com/odoo/odoo/issues/66644, https://github.com/guardian/grid/issues/3181, https://github.com/gohugoio/hugo/issues/8275

We encourage meaningful contributions to our repositories, especially well researched and high-quality changes & contributions. 

As an extension to that philosophy and quick feedback to this PR, I would like to confirm that this is NOT accurate:

> freeCodeCamp contributors, students and developers are currently not able to quickly deploy & preview backend+frontend changes for each PR.

Closing, let us know if we can be of help.

**Comment by emiquelito** [comment]
@raisedadead and @ieahleen thanks for raising your concerns. Squash is different than "Development Environments" in the sense that we are not focused on the collaboration of the actual code per see, our focus is to allow users to test the end product from unique end points, including end points for microservices (seeding data into test environments, dependencies, etc). I could go in greater detail on our feature set and how we are different but I'm under the impression that you already made a decision about this, so I will refrain from expanding this further.

I just wanted to make it clear that we are offering our service for free as a way to support the community. I'm not selling anything here (even though I thought this was already clear in my first post).


@raalejandre 

> Thanks for taking the time to open this PR. I went ahead and looked at bunch of other PRs on the other open-source repositories for this product.

You are absolutely right, I've been offering the product to select projects/repos where we think we can bring value. Since I'm not charging anything and offering value where it makes sense I don't see where is the problem.

Many other companies in the same space also have free offerings for Open Source. 

Anyway, thanks for your time, and sorry if this caused any disruption to your day, this was definitely never my intention.

**Comment by raisedadead** [comment]
> You are absolutely right, I've been offering the product to select projects/repos where we think we can bring value. 

Yup, we understand. 

However, my research so far gives me the impression that these are templated threads (akin to cold emails), thereby lacking the efforts put in to what a project like ours needs.

That is the sole reason for closure of this issue. Some research about the pain-points of our contributors and maintainers would have helped us evaluate the product better.
 
And we have been able to partner with great platforms in the past based off of that. :)

> Since I'm not charging anything and offering value where it makes sense I don't see where is the problem.

Thank you for your kind offer. 

Trust me when I say this, we understand the value of every help a tiny non-profit gets. We are mostly driven by the hard work of thousands volunteer contributors and help millions of users have access to learning resources.

We hope you take this as constructive feedback with your approach to other open-source communities that you trying to help.

IMHO, we do not have the need for integrating Squash at the moment. However, we will reach out to you in future if such a need does arise.

Cheers :)
