### ISSUE TITLE
Coderadio does not play on mobile chrome and mobile safari on IOS

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#41255]
Some users are experiencing issues playing coderadio on mobile safari and mobile chrome on IOS.

This issue aims to document its reproducibility and provide a solution.

**Comment by ahmadabdolsaheb** [comment]
I have not been able to reproduce this on: 
IOS: 14.4, chrome: 870.0.4280, firefox 31.0

**Comment by Ismailtlem** [comment]
I also was not able to reproduce this bug on chrome v 88.0.4324.181 on an android device

**Comment by ahmadabdolsaheb** [comment]
I am closing this issue since it is not reproducible and other fixes might have resolved it.

**Comment by nhcarrigan** [comment]
@ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
I tried coderadio on multiple iPhone devices with different installations of Safari and was not able to reproduce it; therefore, I am closing this pr due to inactivity for the time being.

If a you are still experiencing the issue, we would appreciate you providing as much context as possible to reproduce it.
