### ISSUE TITLE
Crowdin Glossary Feature

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41264]
Crowdin offers a glossary feature for defining source-language (english) terms and mapping the desired translation for those terms. Our translation contributors have begun utilising this feature, but it seems that our translation mapping does not impact the suggested Machine Translations that Crowdin offers in the UI.

As such, a couple of things to consider:

- Can we implement a custom QA check that matches terms in the glossary with their relevant translations and checks that our proposed translation strings use the correct terms?

- Can we integrate the glossaries into the automatically generated Machine Translations?

**Comment by comradekingu** [comment]
Here is some _free code_ to do it:
https://docs.weblate.org/en/latest/user/glossary.html?highlight=glossary   https://docs.weblate.org/en/latest/user/translating.html#auto-translation

**Comment by nhcarrigan** [comment]
Thank you for sharing, but that appears to be documentation for a different translation service.

**Comment by comradekingu** [comment]
Thought it would be interesting to point out in the interest of avoiding only-as-a-service products.

**Comment by RandellDawson** [comment]
> Thought it would be interesting to point out in the interest of avoiding only-as-a-service products.

We would prefer to stick with solutions that are related to Crowdin, since that is the service we are going to be using. Thank you.
