### ISSUE TITLE
Bug on Challenge: Create Visual Direction by Fading an Element from Left to Right. From the first module.

### ISSUE THREAD

**Issue by boringow** [freeCodeCamp/freeCodeCamp#41269]
**Describe your problem and how to reproduce it:**
This problem is a small but specific problem on the challenge Create Visual Direction by Fading an Element from Left to Right.
Where the "left: 50%;" property of the @keyframes class has to be changed to 60%.

The solution is just to put 60%, but it should accept the default 50% as well, as you are only changing the opacity.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/create-visual-direction-by-fading-an-element-from-left-to-right#

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox
* Browser Version: 84.0.2
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="943" alt="github_isue" src="https://user-images.githubusercontent.com/62092582/109272411-1fe7e380-7811-11eb-8b39-7e4f9db086c8.PNG">

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. For future reference, we recommend you open a topic on the forum first, and, once something is determined to be an issue there, then open the relevant issue here on the repo.

Reason being, there is no issue here. I suggest you reset your code, and see that the starter code is:
![image](https://user-images.githubusercontent.com/51722130/109292617-8de8d680-7822-11eb-80bd-92cc2ea927d7.png)

As such, I am closing this. Thank you
