### ISSUE TITLE
Project-Based Curriculum Prototypes

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41265]
As discussed in today's contributor meeting, we are looking to build prototype projects for our new curriculum. Each project will introduce a pre-defined list of concepts (i.e. CSS `text-align` or HTML `<div>`) and will be limited in scope to those concepts and any previously-covered concepts.

We are looking for contributors who would be willing to build a prototype - if you are interested in contributing, please let us know here or reply back here and we will get with you to assign a project.

**UPDATE (March 2nd, 2021)**
We currently have a [Google Sheet](https://docs.google.com/spreadsheets/d/1KXEJvgnAziiePMp2Ovf_ssDqCFFWYuycXWBNp91k3qM/edit#gid=536323154) with tabs for each certification section.  Each tab contains a list of concepts/syntax we want to cover (the rows) and the corresponding practice project (the yellow columns) in which they will be introduced and/or seen again.  There are currently two or three practice projects showing before each certification project, but we plan to have many more.  These were just a few of the projects that came over from the [CurriculumExpansion repo](https://github.com/freecodecamp/curriculumExpansion).  My goal is to finalize the first half of the projects (including all the syntax/concepts to be covered for each) added by early next week. Then, I would like to schedule a meeting (or two) in the next two week where anyone who is interested can join to learn more details about the exact process of developing these projects will entail.  We are putting some final touches on the new UI for the project-based curriculum this week and plan to demo a few of the completed projects for you during the scheduled meeting.

To answer a few of the question asked so far, the following is the general steps we plan to use to create the project:

1. A prototype of the final project (including all HTML and CSS) based on the project tile.  The key is the final prototype can only include concepts/syntax covered in a previous project or designated as `p` or `wc`, or `cnp` in a project column.

**NOTE:** Some concepts/syntax may not appear in the final prototype but are covered in a step of a project.  For example, there may be steps where we introduce `margin-top`, `margin-bottom`, `margin-left`, and `margin-right`, but then some refactoring occurs and the final prototype ends up with the short-hand version of using just `margin`.
  
2. Once the prototype is accepted as meeting the project specifications, someone (at first it will probably be me) will break the prototype into very granular steps with each step building the HTML and CSS until the final prototype has been created.

3. The project-based curriculum will differ from the current curriculum in many ways.  One of the main differences is the editor will have an editable and non-editable region.  The user will add/modify code in the editable region and a series of specially designed tests will examine the user's code and suggest a "hint" if the code does not fulfill the instruction of the step. These tests will need to be written in a similar style as the currently completed projects to provide a similar feedback loop throughout all the projects.  The tests can be written by anyone once all the projects steps are completed in (see step 2. above).

I will be able to cover all of the above in greater detail when I show you a demo of some of the completed projects.  In the mean time if anyone has questions about the project-based curriculum, you can reach me via direct message on [Contributors chat room](https://chat.freecodecamp.org/channel/contributors) or [on the forum](https://forum.freecodecamp.org/u/RandellDawson).

**Comment by Sembauke** [comment]
I woud like to help. But first I want to know what I am getting into.

**Comment by JoshuaPelealu** [comment]
I would be interested to help :)

**Comment by ClockworkOrange605** [comment]
Want to participate.

And by the way, it feels strange that JavaScript path, and event part about Object Oriented Programming doesn't explain how to use `class` keyword. Maybe you need to cover this concept in your new curriculum.

**Comment by Ismailtlem** [comment]
Are the contributors the ones who will bring up the project ideas ? Or are there some project ideas and the contributors will be building prototypes of them ?

**Comment by JoshuaPelealu** [comment]
@Ismailtlem 

I think the contributors are going to build prototypes of what has been decided.

**Comment by Ne0nWinds** [comment]
I'm willing to help, as well!

**Comment by RandellDawson** [comment]
Sorry for not replying sooner.  See the update I have made in the issue body.

**Comment by RafaelDavisH** [comment]
@nhcarrigan I would love to work on the 'Learn Responsive Web Design by Building a Piano" prototype. Hopefully, it has not been assigned yet.
