### ISSUE TITLE
Applied Accessibility

### ISSUE THREAD

**Issue by RobertoCastaneda3500** [freeCodeCamp/freeCodeCamp#41267]
I have an issue with div tags. I am not able to fully complete the following challenges: Make Screen Reader Navigation Easier with the header Landmark and Camper Cat included navigation links at the top of his training page, but wrapped them in a div. Change the div to a nav tag to improve the accessibility on his page. I get that "Your code should not have any div tags" is still wrong when div tags are off my code. 

Thank you.

**Comment by ShaunSHamilton** [comment]
Hello there,

In general, I recommend you open an issue like this on the [forum](https://forum.freecodecamp.org/), as this is not an issue with the code base.

The easiest way to open an issue on the forum is to use the _Ask for Help_ button located on the specific challenge you are struggling with. This will create a pre-populated post with your current code, and give you the opportunity to fill in the necessary extra information, before posting.

If something is determined to be an issue on the forum, then an issue can be opened here with the necessary information.

I am closing this, for now. Thank you
