### ISSUE TITLE
Add tests for breadcrumbs

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41277]
Ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/41276#pullrequestreview-599942709

We should build out some tests to assert that the breadcrumbs are rendering correctly and have the expected text content.

**Comment by Sembauke** [comment]
Some Test cases that might be useful: 

1.Ensure that clicking the links redirects the users to the corresponding page.
2.Ensure that tooltip/corresponding page URL is displayed on mouse hovering the links. (might be useful to add tooltips?)
3.Ensure that there is proper spacing in between the navigation links in breadcrumbs.
4.Ensure the browser compatibility of this feature (breadcrumbs).

**Comment by Sembauke** [comment]
Doesn't the ChallengeTitle test already check if the bread crumbs get rendered correctly?

```
describe('<ChallengeTitle/>', () => {
  it('renders correctly', () => {
    const tree = renderer.create(<ChallengeTitle {...baseProps} />).toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

**Comment by ahmadabdolsaheb** [comment]
in addition to uni tests, it would be great to have some cypress tests to make sure it the component get rendered properly on the page.

**Comment by gikf** [comment]
@Sembauke It does, but in a limited scope. Using `baseProps` defined specifically for test, (which has correct-fake data), and checking against [snapshot](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/components/__snapshots__/ChallengeTitle.test.js.snap). That doesn't check if breadcrumb looks as it should when `ChallengeTitle` component receives props from another component and these props may or may not be correct.

**Comment by JackMaunders** [comment]
Hey, having had a look into the context around this I am happy to pick it up as my first contribution to freeCodeCamp, unless someone else has already started on it?

As well as some unit tests, I can take a look at some cypress tests too as mentioned by @ahmadabdolsaheb

**Comment by gikf** [comment]
Hey @JackMaunders I haven't followed it, but there's some work regarding cypress testing being done in #41602, feel free to check it and add your insights.

**Comment by alirezaghey** [comment]
Hi,
I was looking into adding these tests, but I'm a little bit confused about the following:
1. Where do we add the tests? I have read the [guidelines](https://contribute.freecodecamp.org/#/how-to-add-cypress-tests?id=how-to-add-cypress-tests), and looked at how the already written tests are organized in the code base but could not come to a conclusion.
2. Is this a separate suite/file for the breadcrumbs tests or do we add a test to each challenge's tests/suit?
3. Should there be tests for all the pages under `/learn/` or only a representative subset?

I also looked at some related PRs and issues including #42138, but it seems that most, at least those that I checked, of the changes have been reverted.

Hope I haven't complicated things.
I guess with some directions and lead I'll be able to solve this and also add more tests to other parts of the application if desired.

**Comment by Sembauke** [comment]
While these changes in the PR are reverted @ojeytonwilliams and I are planning on optimizing the PR. But that should still take some time.

In the meantime, we could use some tests for the breadcrumbs. If you are familiar with Cypress you can use that to make the new test. I suggest you add these tests under `cypress\integration\learn\redirects`.  

>Hope I haven't complicated things.
I guess with some directions and lead I'll be able to solve this and also add more tests to other parts of the application if desired.

You haven't made anything more complicated :smile:  We are always happy to add new tests to our codebase you can look into [this issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38611) (Which is a bit outdated but could lead you in the right direction).

Happy coding.
