### ISSUE TITLE
Solidity and Smart Contract curriculum

### ISSUE THREAD

**Issue by PatrickAlphaC** [freeCodeCamp/freeCodeCamp#41272]
**Is your feature request related to a problem? Please describe.**
As more and more engineers enter the solidity/smart contract/blockchain space, having a go-to place would be a welcome need for the community. I'd love to add a smart contract section to freecodecamp. 
 
**Describe the solution you'd like**
A solidity curriculum which incorporates:

1. Introduction to blockchain
2. Solidity core concepts
3. Deployment frameworks (brownie, hardhat, truffle)
4. Full stack w/ react

**Describe alternatives you've considered**
Not sure if this section is applicable. 

**Additional context**
N/A

I'd be happy to help build this out, but I'm nervous to spend a **loooooottt** of time creating this and then not having it accepted. What are the thoughts here?

**Comment by ieahleen** [comment]
I don't know if it's something for the interactive curriculum, but it can be for the YouTube channel or news publication

The intended path for the curriculum is this one:
https://www.freecodecamp.org/news/building-a-data-science-curriculum-with-advanced-math-and-machine-learning/

for news publication you can read here:
https://www.freecodecamp.org/news/developer-news-style-guide/

for youtube read here:
https://www.freecodecamp.org/news/how-to-contribute-to-the-freecodecamp-community-youtube-channel-b86bce4c865/

**Comment by PatrickAlphaC** [comment]
Thanks for responding!

Why not the interactive curriculum? And how do we contribute to the publication? I don't see a way to contribute.
 
I'll reach out for youtube :D

**Comment by ieahleen** [comment]
> Why not the interactive curriculum? 

at the time the plan is the one I linked above

> And how do we contribute to the publication? I don't see a way to contribute.

the link is in the article, it also explain what is expected from an article to be accepted. Note you need three articles to show in your application.

**Comment by PatrickAlphaC** [comment]
Ah found it! Will close this.

Didn't realize that curriculum building was synchronous instead of async. Thank you!
