### ISSUE TITLE
Forum Theme Changes

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41273]
Discourse rolled out an update which included a small breaking change for our forum theme. The "This topic will close in 6 months" message box is visible at the bottom of each topic again.

This was originally fixed in our theme here:

https://github.com/freeCodeCamp/forum-theme/blob/afa902f64dc79db95304b21beb8b9a92f5b5fcbb/common/common.scss#L727-L729

The CSS selector for this rule needs to be changed from `.topic-status-info` to `.topic-timer-info` to resolve the issue, I believe.

Changes to the theme are handled in this repository: https://github.com/freeCodeCamp/forum-theme/

**Comment by JoshuaPelealu** [comment]
I can do a longer term fix where the CSS will target an element that has text of `This topic will close 6 months after the last reply.`

**Comment by ahmadabdolsaheb** [comment]
@nhcarrigan, hide that element all together would also hide the related settings for the admins.
I was wondering if that is what we want. if so we could merge the pr and update themes accordingly.
<img width="793" alt="Screen Shot 2021-03-04 at 3 17 04 PM" src="https://user-images.githubusercontent.com/4591597/109963090-0e18ab80-7cfd-11eb-8d4b-b6df63163463.png">
<img width="471" alt="Screen Shot 2021-03-04 at 3 16 28 PM" src="https://user-images.githubusercontent.com/4591597/109963101-107b0580-7cfd-11eb-8369-ed5f97406aa5.png">

**Comment by nhcarrigan** [comment]
So the "global" setting is configured at the category level - those two buttons are for disabling the timer on a specific post. I, personally, can't think of a use-case where we would want to do this, so I'm fine with hiding those too. But I'll let others chime in if needed.

**Comment by ahmadabdolsaheb** [comment]
@RandellDawson, if you also agree with @nhcarrigan, we could get the class name change in and completely hide that section?

**Comment by RandellDawson** [comment]
Just to be clear, those buttons are for disabling the timer at the topic level and not the post level.  We might want to disable the timer for a topic that has information that is important to keep enabled but not quite important enough to be a "sticky" topic.  I think the main goal would be to just hide the message and leave the admin buttons in place (since they are not seen by the public).  Is that possible?

**Comment by nhcarrigan** [comment]
The actual text itself doesn't have a handy class to select but it would be possible, potentially with something like:

```css
.topic-timer-heading > span
```
