### ISSUE TITLE
Translate contribute docs alerts

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#41324]
`docsify-plugin-flexible-alerts` lets us customise the alert labels, depending on the path.  This allows us to display hints in the appropriate language.

To use this, we'd need translations for each note (note, tip, warning and attention) and then we can configure the plugin.  Since we're translating into many languages, it might be best to handle this translation through Crowdin, even though it's only 4 words.

**Comment by nhcarrigan** [comment]
So looking at the docs, if we add this we would need to upload the `index.html` file to Crowdin to be able to translate there.

Would it be better to use the "global" setting they offer:

```html
<script>
  window.$docsify = {
    'flexible-alerts': {
      note: {
        label: {
          '/de-DE/': 'Hinweis',
          '/': 'Note'
        }
      },
      tip: {
        label: {
          '/de-DE/': 'Tipp',
          '/': 'Tip'
        }
      },
      warning: {
        label: {
          '/de-DE/': 'Warnung',
          '/': 'Warning'
        }
      },
      attention: {
        label: {
          '/de-DE/': 'Achtung',
          '/': 'Attention'
        }
      }
    }
  };
</script>
```

**Comment by nhcarrigan** [comment]
I'll play with this today. Maybe I can create a JSON file and hot-load it in to the HTML so we don't have to mess with the HTML on Crowdin. 🤔

**Comment by ojeytonwilliams** [comment]
I was vaguely thinking we could have `/locales/en.json` etc and then use those to build the `index.html` from a template.  That way it's as static as possible.

**Comment by ojeytonwilliams** [comment]
For visibility: Nick and I talked about it a bit and he convinced me that Crowdin's probably overkill for this, even if there are many different languages.  The simplest approach is just to edit the config by hand.
