### ISSUE TITLE
Suggestion for a project: Record and replay user typing text

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/freeCodeCamp#41328]
**Is your feature request related to a problem? Please describe.**
This is a suggestion for a front end project. The idea is to have a web app which has an input box / text editor where a user can type and the app records what the user types, similar to recording a video. The app then allows you to download the recording and then play it later and see the user typing text similar to playing a video.

Example: https://www.youtube.com/watch?v=t17uJKb-rho

Project source code - https://github.com/karuppiah7890/text-editor-recorder/
Live here -
Recorder - https://karuppiah7890.github.io/text-editor-recorder/recorder.html
Player - https://karuppiah7890.github.io/text-editor-recorder/recorder.html

Long ago I remember contributing by suggesting another front end project (peer to peer video chat app) and hence suggesting another since I felt this was a cool project to try out! :)

**Describe the solution you'd like**
If you think that this is a good suggestion, I would like to see a challenge for such a project in the freecodecamp curriculum somewhere, like the list of Take Home Projects https://www.freecodecamp.org/learn/coding-interview-prep/#take-home-projects

**Describe alternatives you've considered**
Not Applicable

**Comment by Sembauke** [comment]
Hey @karuppiah7890,

Thank you for this great idea, unfortunately, we have all our projects planned out at the moment for version 7 of the curriculum. 
Thank you for thanking the time to share this.

Enjoy your day, and happy coding!
