### ISSUE TITLE
On the certifications pages change the text that says expand/collapse courses to expand/collapse lessons

### ISSUE THREAD

**Issue by tomjbradley** [freeCodeCamp/freeCodeCamp#41330]
Currently when you go to a page for a certification such as [the responsive web design page.
](https://www.freecodecamp.org/learn/responsive-web-design/) for each course there is an accordion dropdown which says **"expand/collapse courses"**.

I'm suggesting that it should say expand/collapse lessons instead as I consider the content in the accordion to be more like lessons than courses.

It could alternatively be changed to *'expand/collapse modules'* or *'expand/collapse challenges'* perhaps.

Here's a screenshot of what I mean:
![certification-page](https://user-images.githubusercontent.com/42977828/109568497-4a72be80-7ae7-11eb-8b67-1155cb864f11.jpg)

**Comment by HBDanks** [comment]
This sounds like a great clarification. Would you mind if I worked on it?

**Comment by tomjbradley** [comment]
Hey @raisedadead I saw you closed this PR #41331 and said this issue might be closed too, could you explain why?

**Comment by raisedadead** [comment]
I have reached out to @QuincyLarson to get this clarified, thanks for your patience.

**Comment by QuincyLarson** [comment]
@tomjbradley @HBDanks This is a good observation. We changed the word from "lessons" to "courses" for 2 reasons:
1. Courses sounds more substantial
2. The word "courses" is much, much more frequently searched on Google than "lessons". And one of the reasons we updated the design of these pages was to make them more useful to people arriving from Google.

<img width="1629" alt="_programming_courses____programming_lessons__-_Explore_-_Google_Trends" src="https://user-images.githubusercontent.com/985197/109687816-3e1f4d80-7b49-11eb-952f-52e468fde495.png">

**Comment by tomjbradley** [comment]
Though I'm not an expert I do understand the SEO concerns, but it still seems a tiny bit misleading, after all they're shorter form lessons so they're not that substantial and although it seems unlikely, I could see this confusing people. 

Wouldn't it maybe be better to mention courses on [the curriculum page](https://www.freecodecamp.org/learn) like so:
![curriculum-page-with-changes](https://user-images.githubusercontent.com/42977828/109708247-6e8fd780-7b9b-11eb-8899-00d411d56e89.png)

and edit each [certification/course page](https://www.freecodecamp.org/learn/responsive-web-design/) to say **'units'** at the top instead and **'expand/collapse lessons'**
![certification-page-with-changes](https://user-images.githubusercontent.com/42977828/109708307-849d9800-7b9b-11eb-9f42-56796fde4470.png)

Wouldn't having the word courses featured prominently on the curriculum page be more informative and have similarly good SEO?

**Comment by Sembauke** [comment]
Hey @tomjbradley,

Thank you for your suggestion, but as Quincy stated we would like to keep it the same.

Enjoy your day and happy contributing
