### ISSUE TITLE
Bonfire: Confirm the Ending - A test case requests true for what should be false.

### ISSUE THREAD

**Issue by av-7** [FreeCodeCamp/FreeCodeCamp#4134]
Challenge [Bonfire: Confirm the Ending](http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending#?solution=function%20end(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20var%20n%20%3D%20str.split(%22%20%22)%3B%0A%20%20%0A%20%20if%20(str.slice(-1)%20%3D%3D%3D%20target%20%7C%7C%20n%5Bn.length%20-%201%5D%20%3D%3D%3D%20target)%20%7B%0A%20%20%20%20return%20true%3B%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0Aend(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code
![capture](https://cloud.githubusercontent.com/assets/9023987/10889052/7d1e87f8-8144-11e5-9b11-476a5b30df08.JPG)
>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The test case shown in the screenshot asserts true, where it should be false. If we are matching the last character or word in a string with the target, then you can clearly see it in the case 

    end("He has to give me a new name", "me") should return true.

that the **last word "name" is not same as the target "me"**.

My code:
```javascript
function end(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var n = str.split(" ");
  
  if (str.slice(-1) === target || n[n.length - 1] === target) {
    return true;  
  } else {
    return false;
  }
  
}

end("Bastian", "n");

```

**Comment by ltegman** [comment]
I don't see anywhere in the instructions that states that it has to be a word or single character. They simply state `Check if a string (first argument) ends with the given target string (second argument).`

Closing as not a problem with the tests but feel free to reply if you need further clarification or see conflicting instructions that I missed.

Thanks and happy coding!

**Comment by av-7** [comment]
Yes, your comment has made the fact a lot clearer that the questions asks to check if a string (first argument) ends with a given target string (second argument).

But in the test case which I pointed out, the given string "He has to give me a new **name**" does not end with target string "**me**", and so it should return false. But the test case asks to return true.

Please correct me if I am wrong. Thank you for your prompt reply.

**Comment by ltegman** [comment]
@av-7 A string can be any length, it does not have to be a word. So that test should return true because `me` are the last two characters in the string `He has to give me a new name`

**Comment by av-7** [comment]
@ltegman Yes, I get it now. Thank you for the clarification.

**Comment by utkarshyadav5** [comment]
function end(str, target) {
// "Never give up and good luck will find you."
// -- Falcor
var len=target.length;
if(target==str.substr(-len,len)){
return true;
}else{
return false;
}

}
end("Bastian", "n");

The right answer for the question using the hint given.
