### ISSUE TITLE
[show upcoming changes/new editor] Bottom of editor gets cut off

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41342]
When working on a challenge locally, pretty sure with the `SHOW_UPCOMING_CHANGES` set to true so it shows the "file tabs" at the top of the editor - it seems to be cutting off a few lines at the bottom of the editor...
![Screen Shot 2021-03-03 at 7 35 17 AM 1](https://user-images.githubusercontent.com/20648924/109813815-72e7df00-7bf3-11eb-89dc-8d129728c563.png)
 In the image, there's a console.log on line 45 or so, but I can't scroll down any further to see it. I did not see this on production - the only difference seems to be the file tabs at the top which I think is causing this. A little digging shows the editor being pushed down slightly from those tabs, hiding the last couple lines behind the console or something.

**Comment by RandellDawson** [comment]
@moT01 We have an existing [issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/39348) where we have been tracking all the current new editor bugs.  This is a known bug, but it does not appear to be listed on the other issue.

**Comment by moT01** [comment]
I will add this to the list.
