### ISSUE TITLE
assert.throws Doesn't Count Towards Assertions

### ISSUE THREAD

**Issue by SethFalco** [freeCodeCamp/freeCodeCamp#41354]
**Describe your problem and how to reproduce it:**
I was working on the Sudoku Solver project and ran into an issue with my tests failing despite my unit tests passing locally.

Test case:
```js
test('Invalid puzzle strings fail the solver', (done) => {
  const puzzleString = '115..2.84..63.12.7.2..5.....9..1....8.2.3674.3.7.2..9.47...8..1..16....926914.37.';
  assert.throws(() => solver.solve(puzzleString), 'Puzzle cannot be solved');
  done();
});  
```
Unit tests:
![image](https://user-images.githubusercontent.com/22801583/109906373-ac2a5880-7ca0-11eb-97dd-f35fde0a3d06.png)

Network tab:
![image](https://user-images.githubusercontent.com/22801583/109906389-b4829380-7ca0-11eb-8eee-5526d771c455.png)

I can see in the tests for the project, it dictates all tests must have at least one assertion. I do have an assertion though, but it's not being returned.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/sudoku-solver

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 86.0 (64-bit)
* Operating System: Ubuntu 20.04.2 LTS x86_64

**Comment by sachinh19** [comment]
Have you tried doing something like this?

`expect(() => solver.solve(puzzleString)).toThrow('Puzzle cannot be solved');`

**Comment by SethFalco** [comment]
> Have you tried doing something like this?
> 
> `expect(() => solver.solve(puzzleString)).toThrow('Puzzle cannot be solved');`

I've already passed the task so I don't need to work around it anymore.
However, I did try `expect(() => solver.solve(puzzleString)).throw('Puzzle cannot be solved');` anyway.

This did _not_ fix the issue. I'm betting it's probably something to do with the pattern not catching the `() =>` syntax as a valid assertion, but haven't looked into it much yet.

**Comment by sachinh19** [comment]
We could probably close this issue since you have already finished the task.

**Comment by SethFalco** [comment]
I think the problem lies with how the functions look post compilation.

```js
// assert.isFalse -> assert.isFalse.
function (done) { var puzzleString = '1.5..2.84..63.12.7.2..5.....9..1....8.2.3674.3.7.2..9.47...8..1..16....926914.37.'; var actual = solver.checkRegionPlacement(puzzleString, 0, 1, 2); assert.isFalse(actual); done(); }

// assert.throws -> assert["throws"]
function (done) { var puzzleString = '115..2.84..63.12.7.2..5.....9..1....8.2.3674.3.7.2..9.47...8..1..16....926914.37.'; assert["throws"](function () { return solver.solve(puzzleString); }, 'Puzzle cannot be solved'); done(); }
```

The regex can be updated to:
```js
const cleanedBody = body.match(/(?:browser\s*\.\s*)?assert\s*(?:\.\s*\w*|\s*\[(["'])\w*\1\])\([\s\S]*\)/);
```

This will allow it to also work with the `["property"]` syntax as well, for example:  
![image](https://user-images.githubusercontent.com/22801583/110008932-9bb7c380-7d1c-11eb-978b-9eeb8ca4e0af.png)

Other parts will also still have to be updated, but unfortunately those methods are more complex, so I will review them later.
Just wanted to share some progress on it so far.

**Comment by SethFalco** [comment]
> We could probably close this issue since you have already finished the task.

No, because this is still a valid issue. I could work around it for now, however others will still encounter it when they shouldn't, and it still needs to be fixed.

**Comment by NikIvan** [comment]
I've encountered same issue while was trying to use `assert.throws()` and `assert.doesNotThrow()` in some tests. 

If adding this methods would be difficult, text of error in console should be fixed at least because now it's misleading. It says something like `each test should contain at least one assert` and obviously my tests contain asserts.

So maybe easy fix would be change description of this project (and maybe others which have same issue) and say something like `Use at least one assert.equal in your tests to pass them`

**Comment by Sboonny** [comment]
here is the file [curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/sudoku-solver.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/sudoku-solver.md)

I am planning to solve the project, first. then I will attempt to solve this, because of fCC honest policy

**Comment by SethFalco** [comment]
Hey hey!

Just wondering, would you mind sharing why this was closed as wontfix, since other users have shared they've encountered the same issue?

Was this resolved in another way? I can open a PR myself later if not, but just wondering if there was a reason that addressing this would be undesirable.

**Comment by ShaunSHamilton** [comment]
@SethFalco 👋 

We mostly closed this as stale - the help wanted has been there for years. Also, I have not seen anyone mention encountering this on the forum in a long time.

This is an older section of the curriculum we plan to replace. As such, we did not want to put the effort into fixing something which is not a showstopper.

If you would not mind fixing this, then we would be happy to review 🙂
