### ISSUE TITLE
Stock Price Checker: Content Security Policy requirement breaks the front end of the application.

### ISSUE THREAD

**Issue by fuzzyray** [freeCodeCamp/freeCodeCamp#41355]
**Describe your problem and how to reproduce it:**
The requirement "You should set the content security policies to only allow loading of scripts and CSS from your server." breaks the front end index.html page, if it is implemented properly. 

The helmet security middleware should be at the top of the `app.use()` chain in order to provide maximum benefit to the application. However, if you do this, then the front end index.html page is broken because it relies on jquery to be downloaded from `https://code.jquery.com/jquery-2.2.1.min.js`

This can be worked around and pass the requirement with a couple of methods, the first is to use the helmet middleware after the route for '/' and before any other routes are defined. The second method is to download a copy of jquery, place it in the project and change index.html to reference the copy.

Of the two methods, the second one is more secure as all of your routes have the content security policy and you are controlling the script that is being loaded. This does come at the cost of more disk space and if this was a real world application building a process to watch for updates and/or security fixes to jquery and getting those fixes pushed to the application.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security/information-security-projects/stock-price-checker

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox
* Browser Version: 86.0
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
This screenshot shows the network activity without a CSP. Both the favicon from freeCodeCamp and jquery are loaded. The get request is initiated by jquery.

![no-csp-policy](https://user-images.githubusercontent.com/928480/109907111-4c638b80-7c67-11eb-908e-cde4feb43c04.png)

This screen shot shows the activity when the CSP policy for scripts is set to self. Neither the favicon or jquery are loaded and submitting the form just causes the page to refresh without a call to /api/stock-prices.

![self-csp-policy](https://user-images.githubusercontent.com/928480/109907242-8a60af80-7c67-11eb-9738-8404f29c1e88.png)

**Comment by gikf** [comment]
If that's not a part of the task (I'm not sure if it is), then the most convenient might be changing it to not require jquery at all.

**Comment by fuzzyray** [comment]
Now that I've completed the project and submitted it, I went and looked at the code in demo-projects. The example app, removed the dependency on jquery and hosted its own script.js file with the jquery functionality required rewritten in plain Javascript. Since the front end piece is not part of the project requirements, I would just update the boilerplate project to use `views/index.html` and `public/script.js` from the demo-project app.

**Comment by santi224m** [comment]
I made a [pull request](https://github.com/freeCodeCamp/boilerplate-project-stockchecker/pull/16) to the ```freeCodeCamp/boilerplate-project-stockchecker``` repository to fix this issue. I removed the dependency on jquery and added the script.js file from the demo-projects.
