### ISSUE TITLE
Waypoint: Use HTML5 to Require a Field

### ISSUE THREAD

**Issue by codenow2015** [FreeCodeCamp/FreeCodeCamp#4135]
After making my input element a required field, the form submitted without any input and the form didn't notify me that the field is required.

**Comment by ltegman** [comment]
Please copy and paste the code you are experiencing this issue with.

**Comment by codenow2015** [comment]
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

**Comment by codenow2015** [comment]
My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <input type="text" placeholder="cat photo U<RL" required>
  <button type="submit">Submit</button>
</form>
```

**Comment by pedrro** [comment]
@codenow2015 Which browse are u testing it? I tested on chrome and firefox and it's working to me.

**Comment by codenow2015** [comment]
@pedrro Safari

**Comment by pedrro** [comment]
@codenow2015 I made a quick search on stackoverflow and I found this link, that says that Safari is not supporting HTML5 tags, so, if you want to run your program, plz, run in google chrome or firefox.

http://stackoverflow.com/questions/23261301/required-attribute-not-work-in-safari-browser

**Comment by ltegman** [comment]
Thanks for looking into this @pedrro. Closing this as an issue with Safari rather than FCC. Please note that the FCC app only officially supports Chrome, so I would highly recommend installing that if you haven't already and using that to continue the FCC curriculum.

Thanks and happy coding!

**Comment by Lapkritinis** [comment]
Had same issue with safari browser. Thanks for posting solution.

**Comment by codenow2015** [comment]
Hi,

I have been working trough the exercises but my browser always freezes on Bonfire: Truncate a string and Bonfire: Chunky Monkey.

my userid is codenow2015

Regards,
Emmanuel.
