### ISSUE TITLE
Video in Use grid-column to Control Spacing does not work

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41356]
**Describe your problem and how to reproduce it:**
The video in the Use grid-column to Control Spacing challenge does not work and has an error message. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/css-grid/use-grid-column-to-control-spacing

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1273" alt="Screen Shot 2021-03-04 at 12 04 49 AM" src="https://user-images.githubusercontent.com/67210629/109931277-80e24200-7c7d-11eb-9b6b-4c6e7d28b6a7.png">

**Comment by raisedadead** [comment]
This is interesting because the [video link on the challenge source](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/css-grid/use-grid-row-to-control-spacing.md) seems to be fine. 

Did we break something?

**Comment by jdwilkin4** [comment]
I tested some of the other videos in that same section and they seem to be working fine. 

So it looks like it is just this video.

**Comment by ojeytonwilliams** [comment]
@raisedadead that's the grid row challenge.  This is the [source file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/css-grid/use-grid-column-to-control-spacing.md) and it's just that that video has somehow stopped working.

**Comment by beaucarnes** [comment]
I don't know how this could have happened. It seems that maybe the Scrimba video was deleted but I'm pretty sure nobody deleted it on our team. I'm really the only one that uses the freeCodeCamp Scrimba account and I haven't logged into that for a long time.

I'll reach out to the Scrimba team to see if they can help. For now, it's probably best to remove the video link from the curriculum.

**Comment by raisedadead** [comment]
Thanks for the clarification Beau. 

We should wait a few more days for the Scrimba team to get back to us. If the video is indeed lost, we can make a PR removing it.

**Comment by raisedadead** [comment]
The video was inaccessible due to an accidental flagging as private. Scrimba has since restored it.
