### ISSUE TITLE
Create PM2 ecosystem config for demo projects

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#41376]
The [demo-projects](https://github.com/freeCodeCamp/demo-projects) currently does not have an [ecosystem config](https://pm2.keymetrics.io/docs/usage/application-declaration/#ecosystem-file) for PM2. 

We would want to create one to help us do server maintenance. 

Bonus points for:

1. Creating a GitHub actions to CI test that all the demo-projects are "deployable", i.e. when a PR is landed, we should spin up the app and take it down to see if will boot.
2. Creating health-check endpoints for each app (not needed for one-off scripts) so that we can add some monitoring to these.

**Comment by nhcarrigan** [comment]
> The [demo-projects](https://github.com/freeCodeCamp/demo-projects) currently does not have an [ecosystem config](https://pm2.keymetrics.io/docs/usage/application-declaration/#ecosystem-file) for PM2.

Solved in https://github.com/freeCodeCamp/demo-projects/pull/127

> Creating a GitHub actions to CI test that all the demo-projects are "deployable", i.e. when a PR is landed, we should spin up the app and take it down to see if will boot.

Resolved as part of https://github.com/freeCodeCamp/demo-projects/pull/94

> Creating health-check endpoints for each app (not needed for one-off scripts) so that we can add some monitoring to these.

@raisedadead I can take a look at this if it's still desired - otherwise, I think this issue is good to close?

**Comment by raisedadead** [comment]
Yes - we can close this. The setup can be more elegant honestly but it's more of a nice one to have at this point.
