### ISSUE TITLE
Word boundary and backspace confusion in JavaScript string escape sequences

### ISSUE THREAD

**Issue by tysonliddell** [freeCodeCamp/freeCodeCamp#41388]
**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings

**Describe your problem and how to reproduce it:**
Changes introduced by #35176 change the name of the `\b` escape character from "backspace" to "word boundary". As far as I can tell, this is incorrect in the context of JavaScript **string** escape sequences. In particular, this could cause confusion when someone tries to do the following and expects a regex match:

```
let regEx = new RegExp('.\b.');      //  \b in the string not interpreted as word boundary
let match = regEx.exec('a b');       // no match
```

The correct expression in this case would be:

```
let regEx = new RegExp('.\\b.');
let match = regEx.exec('a b');
```

or 

```
let regEx =/.\b./;
let match = regEx.exec('a b');
```

The literal `\b` can not be used in a **string** to refer to a word boundary, this only works in the context of regular expression literals like `let re = /.\b./;`, which are not strings. I understand from #35176 that @QuincyLarson has a different view on this and is trying to prevent confusion for beginners, however, since the lesson is about **string** escape sequences (not regular expression special characters), calling `\b` a word boundary in this context is incorrect. The [Mozilla string docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) refer to the character as a backspace, as does string documentation for any programming language that I have come across.

It appears that the distinction between strings and regular expressions was missed when #35176 was raised. Or perhaps I'm, just missing something. Any clarification/input appreciated.

**Comment by yassir206** [comment]
good

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.

**Comment by eliandoran** [comment]
This issue is still relevant, "word boundary" is not the right name for the `\b` escape sequence in the context of strings. Created a PR to treat this: #50001.
