### ISSUE TITLE
Last test at end shouldn't return true?

### ISSUE THREAD

**Issue by amusedalpaca** [FreeCodeCamp/FreeCodeCamp#4139]
The last test says: palindrome("0_0 (: /-\ :) 0-0") should return true.

But "_" is not the same as "-", so shouldn't this test return false?

Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20if%20(str.toLowerCase().replace(%2F%5CW%2Fg%2C%20'')%20%3D%3D%20str.toLowerCase().replace(%2F%5CW%2Fg%2C%20'').split('').reverse().join(''))%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%20%20%0A%20%20%0A%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  if (str.toLowerCase().replace(/\W/g, '') == str.toLowerCase().replace(/\W/g, '').split('').reverse().join('')) {
    return true;
  }
  else {
    return false;
  }
}
  
  




palindrome("eye");

```

**Comment by ltegman** [comment]
This challenge asks that you remove all punctuation and whitespace, so the only characters left in that string after you do so should be `0000`, which would be a palindrome.

Closing this as not an issue with the test, but please feel free to reply if you need further clarification.

Thanks and happy coding!
