### ISSUE TITLE
Show indication for completed courses on main courses page

### ISSUE THREAD

**Issue by eliasm307** [freeCodeCamp/freeCodeCamp#41403]
Currently, on the main page which shows the list of courses, there is no indication to show which courses have already been completed, you need to click each one individually to get that information.

It would be good if there was a tick, icon, or different colour etc to differentiate completed courses. It helps to see how much a user has achieved and what is left at a glance.

Here is an example of what I mean, guess which courses I have completed...
![image](https://user-images.githubusercontent.com/13420359/110271791-9d091a80-7fc0-11eb-8508-e9953f5852b9.png)

**Comment by CreaTorAlexander** [comment]
I would suggest to switch the color of the completed courses to a light green to signal that it is already finished.

**Comment by Narcos101** [comment]
Hello! Could you assign it to me and tell me how should i approach it?

**Comment by ShaunSHamilton** [comment]
@Narcos101 This is a feature request, and nothing has been decided about whether or not to implement it.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by raisedadead** [comment]
Check marks could be one way of adding a completion status, I will wait on @ahmadabdolsaheb's recommendation.

**Comment by moT01** [comment]
I like the idea of being able to see the overall progress from somewhere. Perhaps the map on the homepage isn't the best place, but the map on /learn has some room. I can't think of a good way to convey this info. One idea might be to have two columns on the right of each cert - a `Challenge Progress` and `Project Progress` or something. The challenge progress might say 50/1000 for how many challenges are completed, and the project progress might say 1/5 for how many projects are completed. Maybe a checkmark could be added if either of them are entirely completed.

**Comment by ahmadabdolsaheb** [comment]
How about showing the progress in the superblocks and only displaying a checkmark on the superblock icon?
<img width="544" alt="Screen Shot 2021-04-13 at 12 09 05 PM" src="https://user-images.githubusercontent.com/4591597/114528051-4d69de80-9c51-11eb-90f7-0d6231259cd0.png">

**Comment by ahmadabdolsaheb** [comment]
I think we optimized the query that shows the cert map to only pull the superblocks info. For displaying percentages we would probably need to pull all of the challenges like we used to.

**Comment by DhruvLamba** [comment]
Can you please assign me this issue

**Comment by ieahleen** [comment]
@DhruvLamba 

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by DhruvLamba** [comment]
okay Thanks:)
