### ISSUE TITLE
Missing warning about extensions

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#41417]
We used to have a warning about extensions at the start of the CSS challenges but with the new curriculum layout, there is no intro page which is where the warning was located.

Not sure if this is intentionally missing now or if the warning should be added back to the block description?

**Comment by raisedadead** [comment]
@freeCodeCamp/moderators what do you think about this? Should we display a one-liner warning on the first "block" card for the CSS Challenges?

**Comment by nhcarrigan** [comment]
I'm not sure the block card alone would be sufficient.

If I am a camper new to the curriculum, I start with the Basic HTML and HTML5 challenges. Upon completing the last challenge, I am immediately taken to the first challenge of the Basic CSS section.

I would suggest we add it to both the Basic CSS block, and a note on the "Change the Color of Text" challenge that says something like "Note that browser extensions such as dark mode can interfere with the tests for this and upcoming challenges. Please disable extensions that modify the layout of the page."

**Comment by ShaunSHamilton** [comment]
We have been dealing with this issue for so long. Is there not a way we can test for if a Camper has a browser extension with access to the webpage? Then, show them a warning.

**Comment by ojeytonwilliams** [comment]
In principle, I think so: http://blog.kotowicz.net/2012/02/intro-to-chrome-addons-hacking.html, but it's a bit unreliable.  If we did show a one-time warning, we might as well show everyone.  That said, I prefer localising warnings to the sections it matters, just to so there's a chance people remember when they run into the problem.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams Right.
>That said, I prefer localising warnings to the sections it matters, just to so there's a chance people remember when they run into the problem.

My thinking was, as it stands, this affects multiple lessons/sections, and with the new curriculum content, I can only imagine it must affect some of them. So, if we could have a reliable way of detecting extensions, then I would imagine it be beneficial for maintenance. Otherwise, I would agree, if it is unreliable.

What if the warning only came up, and offered a _"Never show this warning again"_ button, along with a _"Close warning"_ button?

**Comment by ojeytonwilliams** [comment]
I don't think it would be reliable enough, since that method checks from a list of known extensions. If it was any extension it might be worth it, but I don't believe that's possible.

Recreating the old warnings in new places seems fine, though.

**Comment by raisedadead** [comment]
Thanks for the feedback everyone, I think we should add the warning along the lines of https://github.com/freeCodeCamp/freeCodeCamp/issues/41417#issuecomment-794892623

**Comment by miku86** [comment]
> We have been dealing with this issue for so long. Is there not a way we can test for if a Camper has a browser extension with access to the webpage? Then, show them a one-time warning.

I think this is overengineering. Especially because we would have to build this for different browsers/browser engines.

> What about the pop-up after a few failed attempts at running the tests.

Can we currently see if the tests fail to run?

Because if we just show a hint after n failed attempts to master the lesson, this could lead to false positives. (The user just has a wrong solution, but they think it's caused by an extension.)

**Comment by lasjorg** [comment]
@miku86 I assume it would be failing to pass the tests, not failing to run the tests. I'm personally not sure if that is such a good idea. Might just become a "red herring" for people making actual mistakes in the code.

Would adding the warning at the beginning of the responsive web design section not be an option?

https://www.freecodecamp.org/learn/responsive-web-design/

**Comment by moT01** [comment]
> Would adding the warning at the beginning of the responsive web design section not be an option?

I'm not opposed to it, but I really don't think it's important enough to add there. 

What about a single news article or forum post that has answers to semi frequent problems like this. There must some others that are similar. I think there was one about browser zoom levels at one point. Then maybe link to it in the ask for help modal:
![Screen Shot 2021-03-10 at 10 09 43 AM](https://user-images.githubusercontent.com/20648924/110660026-c07ec180-8188-11eb-95d1-97f532ca4c31.png)

Any time there's a common issue that we can't really solve on our end, add it to the article.

**Comment by lasjorg** [comment]
> What about a single news article or forum post that has answers to semi frequent problems like this.

I think having an FAQ-style forum thread is a good idea. We just need to make sure people actually read it.

> Any time there's a common issue that we can't really solve on our end, add it to the article.

Technically, for the color-related challenges, I do believe we can fix them on our end. We are testing the styles applied to the DOM, not the code that was entered. We do this to avoid having to use regex checks for the actual code written. Which is most definitely preferable but does leave us vulnerable to this specific issue. I'm not suggesting we should "fix it" on our end as testing the written code isn't a great option either.

> I'm not opposed to it, but I really don't think it's important enough to add there.

I guess that depends on what is considered important. We get forum posts all the time where the code is passing but we (the mods) have to inform the user about issues with extensions. Not saying it makes our work harder, just a little annoying.

**Comment by RandellDawson** [comment]
> Technically, for the color-related challenges, I do believe we can fix them on our end. We are testing the styles applied to the DOM, not the code that was entered. We do this to avoid having to use regex checks for the actual code written. Which is most definitely preferable but does leave us vulnerable to this specific issue. I'm not suggesting we should "fix it" on our end as testing the written code isn't a great option either.

This entire issue will vanish once we can use the CSS helper function that will use a CSS parser.  I had started work on this a while back but got side-tracked on other curriculum and localization stuff.  If this is super important, then I think we could discuss this in the next Office Hours meeting and come up with a plan to get these created once and for all. It will benefit the project-based curriculum and the existing one.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/131520438-550b9d89-6ebe-4789-b9d7-96eb80d4a0e2.png)

**Comment by nhcarrigan** [comment]
Closing this as fixed - banner is present on the superblock page. Feel free to request reopening if further review is required. :)
