### ISSUE TITLE
Responsive Web Design Certification

### ISSUE THREAD

**Issue by DSok-DSok** [freeCodeCamp/freeCodeCamp#41419]
**Describe your problem and how to reproduce it:**
Hello,

When I click on the View Responsive Web Design Certification link, it redirects me to the home page of freecodcamp.
Tried looking for answers online with no result.

Please help me.

Thank you!

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/fcc656f1642-26cf-4d80-819d-ac21d5d51963
**Recommended fix, suggestions (how would you update it?):**
![Capture](https://user-images.githubusercontent.com/78227472/110373628-8f758400-8004-11eb-97e6-86ba0c938833.PNG)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by miku86** [comment]
Hey there,

when you opened the issue, there should have been a template to fill out some data.

Please add it, thanks.

**Comment by ShaunSHamilton** [comment]
Hello there,

It appears you have not completed the required steps to view your certificates:
![image](https://user-images.githubusercontent.com/51722130/110381576-91b1ff80-8051-11eb-89cb-ca0bbeb1ed06.png)

Please go to your settings page, and read the notices about the required settings to make use of the certificates. Thank you

**Comment by raisedadead** [comment]
If you need further assistance, please reach out to our community forum: https://forum.freecodecamp.org
