### ISSUE TITLE
Should contextual navigation be removed?

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#41423]
In the past we have added contextual navigation buttons in the UI to be able to reduce the nav items.

Since we have grouped all nav items in the menu button, I was wondering if having them in different pages is redundant.

Specially buttons that redirect to settings, portfolio, and sign out.

![image](https://user-images.githubusercontent.com/4591597/110450876-aaafc480-80d4-11eb-891e-437f1c421200.png)
![image](https://user-images.githubusercontent.com/4591597/110462295-89a1a080-80e1-11eb-81e4-c6206d449ad8.png)
![image](https://user-images.githubusercontent.com/4591597/110462305-8dcdbe00-80e1-11eb-8486-da01ff23185a.png)

etc...

**Comment by raisedadead** [comment]
I think other than the go to my current challenge, everything else can go.

**Comment by Sembauke** [comment]
Is it possible to test which widget is used more before deleting anything?  Personally, I would use the buttons that are directly displayed on the page.

**Comment by ahmadabdolsaheb** [comment]
We could add analytics events and see which ones are getting the most usage; However, since we have moved all those buttons to the menu, and the user can have access to them at any point, it makes sense to remove the duplicates and save the users some scrolling.

**Comment by Nirajn2311** [comment]
Yup, I think its better to remove them as they(Sign out and update account settings) are in the Menu itself. They might also end up confusing the user.
