### ISSUE TITLE
Instructions needed for how to fork codepen projects

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41429]
**Describe your problem and how to reproduce it:**
Hi there! 

I think there needs to be instructions on how to properly fork a codepen pen. 
Right now, it is just this line here
"You can build your project by forking this CodePen pen."

But that doesn't explain how to fork the project. So the user will just click the link and start coding. Then they try to submit the link but it is rejected because they are submitting a FCC boilerplate. 
It is a common issue brought up all of the time on the forum
https://forum.freecodecamp.org/search?q=Remember%20to%20submit%20your%20own%20work

Possible addition to the tribute page instructions:

How to fork a pen

1. Login to codepen
2. Visit this FCC codepen pen
2. Click on the fork option located at the bottom right hand corner of the page.
3. Click save
4. Start coding

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
@freeCodeCamp/moderators - I think we could add something succinct along the lines of what Jessica recommends above to each project description? Thoughts?

**Comment by nhcarrigan** [comment]
I agree - I think this would be helpful information.

**Comment by supzi-del** [comment]
Is this what you're looking for?

**Comment by ShaunSHamilton** [comment]
We have used CodePen long enough, and I do not see it changing much. So, what if we included another news article going through _The ins-and-outs of CodePen_? The main topics I would expect:
- How to fork a boilerplate pen
- How to use the HTML/CSS/JS editors (what code goes where)
- How to analyse/format your code
- How to add React and other packages to your project
These are common pitfalls I have seen on the forum.

---

@supzi-del This issue has not been opened up for contribution, yet. This is indicated by the labels _help wanted_ or _first timers only_.

**Comment by jdwilkin4** [comment]
I didn't even think about an article. I found one article on FCC news from 2016 but a lot has changed since then. I found a few articles on google  but they don't really have many screenshots which would be really helpful. I would be interested in writing that. Unless, you wanted to @ShaunSHamilton since it was your idea. 

I think whatever is decided for this issue, writing a FCC news article about codepen is a good idea.

**Comment by ShaunSHamilton** [comment]
@RandellDawson That does look simpler. What happens, when a user does not have a CodePen account, though?

**Comment by RandellDawson** [comment]
@ShaunSHamilton If not logged in or no account, then clicking `Save` prompts the user to login and/or create an account.  Similar as to what happens if someone clicks the `Fork` link.

**Comment by ieahleen** [comment]
there is still the chance that people may not save and submit the template link... not much as there is a Save button, but it could happen - just to be sure, make sure that template links cannot be submitted?

**Comment by jdwilkin4** [comment]
I like this template idea. 
And I agree with @ieahleen 's suggestion of making sure the template links cannot be submitted.

**Comment by RandellDawson** [comment]
@ieahleen  @jdwilkin4 That would be nice, but seems to be beyond the scope of the current issue needing to be addressed.  @ShaunSHamilton Not sure the best way to approach that feature, but there was talk at one point about once a project is submitted, then instead of it showing up as completed, the test runner would run behind-the-scenes using something like puppeteer and then depending if the tests pass or not, would make it eligible to claim certification.

**Comment by jdwilkin4** [comment]
> That would be nice, but seems to be beyond the scope of the current issue needing to be addressed.

Ok no problem. 

Just curious though, 
Would it be difficult to replicate the same rejection process you are using now? 

If a user tries to submit this link `https://codepen.io/freeCodeCamp/pen/MJjpwO` then they get this error message
<img width="973" alt="Screen Shot 2021-03-10 at 1 50 36 PM" src="https://user-images.githubusercontent.com/67210629/110702994-12830f80-81a8-11eb-8873-906ebbda6950.png">

Couldn't the same be done for this link? `https://codepen.io/pen?template=MJjpwO`

It wouldn't check to make sure everything is passing but it would deter those from just submitting the template. 

Thanks!

**Comment by RandellDawson** [comment]
> Couldn't the same be done for this link? https://codepen.io/pen?template=MJjpwO

Not quite.  The current code uses the following regex to test for a freeCodeCamp Codepen without specifying the slug name (the `MJjpwO`).  That was done on purpose so we did not have to try and track the various slug names in our code base somewhere.  If we want to use this template feature I suggest and want to prevent users from submitting it, then we might not have a choice about tracking the slugs for each project.

**Comment by nhcarrigan** [comment]
> If we want to use this template feature I suggest

I tested out the template feature in the draft PR (and commented there) - 100% support from me. It's a much more streamlined UX.
