### ISSUE TITLE
My code clearly works, as tested elsewhere (see image attached).

### ISSUE THREAD

**Issue by akulaggarwal** [FreeCodeCamp/FreeCodeCamp#4142]
![works](https://cloud.githubusercontent.com/assets/13689319/10899485/f3e967f0-8189-11e5-953f-29fa44a0fa55.JPG)
Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence#?solution=function%20titleCase(str)%7B%0A%20%20var%20allLower%20%3D%20str.toLowerCase()%3B%0A%20%20var%20brkArry%20%3D%20allLower.split('%20')%3B%0A%20%20%2F%2Fconsole.log(brkArry)%3B%0A%20%20var%20storageArray%20%3D%20('')%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20brkArry.length%3B%20i%2B%2B)%7B%0A%20%20%20%20var%20currentWord%20%3D%20brkArry%5Bi%5D%3B%0A%20%20%20%20%2F%2Fconsole.log('This%20is%20my%20current%20word%3A%20'%20%2B%20currentWord)%3B%0A%20%20%20%20var%20first%20%3D%20currentWord.charAt(0)%3B%0A%20%20%20%20var%20firstCap%20%3D%20first.toUpperCase()%3B%0A%20%20%20%20var%20final%20%3D%20currentWord.replace(currentWord%5B0%5D%2C%20firstCap)%3B%0A%20%20%20%20%2F%2Fconsole.log(%22This%20should%20be%20my%20current%20word%20correct%20Caps%3A%20%22%20%2B%20final)%3B%0A%20%20%20%20storageArray%20%3D%20storageArray%20%2B%20%22%20%22%20%2B%20final%3B%0A%20%20%20%20%2F%2F%20console.log(%22this%20is%20my%20current%20statement%3A%20%22%2B%20storageArray)%3B%0A%20%20%20%20%2F%2Freturn%20storageArray%3B%0A%20%20%7D%0A%20%20%2F%2Fconsole.log(storageArray)%0A%20%20return%20(storageArray)%3B%0A%7D%0A%0AtitleCase(%22I'm%20A%20Little%20Tea%20Pot%22)%3B%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str){
  var allLower = str.toLowerCase();
  var brkArry = allLower.split(' ');
  //console.log(brkArry);
  var storageArray = ('');
  for (i = 0; i < brkArry.length; i++){
    var currentWord = brkArry[i];
    //console.log('This is my current word: ' + currentWord);
    var first = currentWord.charAt(0);
    var firstCap = first.toUpperCase();
    var final = currentWord.replace(currentWord[0], firstCap);
    //console.log("This should be my current word correct Caps: " + final);
    storageArray = storageArray + " " + final;
    // console.log("this is my current statement: "+ storageArray);
    //return storageArray;
  }
  //console.log(storageArray)
  return (storageArray);
}

titleCase("I'm A Little Tea Pot");
titleCase("sHoRt AnD sToUt");
titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");
```

**Comment by ltegman** [comment]
Take a close look at your output. You're adding a space at the beginning of the string, which makes it not match the expected output.

In the future please ask for help in the [Gitter Help Channel](https://gitter.im/FreeCodeCamp/Help) before filing a bug.

Thanks and happy coding!
