### ISSUE TITLE
i18n - Fix challenge format for Crowdin

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41449]
Within the [Nest an Anchor Element challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.md) the text which reads: 

> The text, `link to freecodecamp.org`, within the `a` element is called `anchor text`, and will display the link to click:  

is incorrectly formatted - "anchor text" is within backticks and is thus untranslatable on Crowdin.

The text in the English file should be updated to use `<dfn>` tags instead: 

> The text, `link to freecodecamp.org`, within the `a` element is called <dfn>anchor text</dfn>, and will display the link to click:  

This issue is open to first time contributors for this repository. If you are interested in contributing, we recommend you start by reading our [contributing documentation](https://contribute.freecodecamp.org). And if you run in to any issues or have any questions, you can reach us in our [contributors chat room](https://chat.freecodecamp.org/channel/contributors).

**Comment by pandacoder7** [comment]
Hi @nhcarrigan . I would like to work on this.

**Comment by nhcarrigan** [comment]
Hey there @pandacoder7,

Thank you for your interest in contributing. Note that we do not typically assign issues except to long-term contributors. Instead, we generally review and merge the first pull request which comprehensively resolves the issue.

Feel free to let us know if you have any questions. 🙂
