### ISSUE TITLE
Validating Frontend Project Submissions Through Testing

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41442]
Not sure the best way to approach that feature, but there was talk at one point about once a project is submitted, then instead of it showing up as completed, the test runner would run behind-the-scenes using something like puppeteer and then depending if the tests pass or not, would make it eligible to claim certification.

_Originally posted by @RandellDawson in https://github.com/freeCodeCamp/freeCodeCamp/issues/41429#issuecomment-796157963_

---

I am wondering how feasible this is, in terms of who is running Puppeteer. This does sound like something Mrugesh would need to be involved with, as my understanding is we would need, ideally, a separate sever somewhere to host/run the tests?

Otherwise, how worth it is this? That is, are we anywhere near being able to host a CodePen like experience on freeCodeCamp for the projects? Also, would the idea behind this be to test already submitted projects?

**Comment by ahmadabdolsaheb** [comment]
@raisedadead, what would be the ideal testing scenario for front end projects?

**Comment by raisedadead** [comment]
This is a broad topic, something that we would discuss on the office hours if it's all the same with you both?

**Comment by nhcarrigan** [comment]
Closing as the shift to the on-platform testing for the project based curriculum will make this less relevant. Feel free to re-open if further discussion is desired.
