### ISSUE TITLE
Repl Migration

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41444]
Just putting this here to keep on radar:

Replit are moving from `repl.it` to `replit.com`.
- https://blog.repl.it/dotcom

They say:
> Nothing is required on your end -- all urls will automatically redirect.

---

The whole platform needs to be audited for the change from `repl.it` to `Replit`, as per:
- https://github.com/freeCodeCamp/freeCodeCamp/pull/41933/files#r621498674

**Comment by ieahleen** [comment]
I think maybe it is to keep in mind for solution link validations

**Comment by nhcarrigan** [comment]
Probably wouldn't hurt to update our URLs to avoid confusion, when the time comes.

**Comment by moT01** [comment]
Most of the backend challenges and projects show `repl.it`...
![Screen Shot 2021-04-09 at 8 45 49 AM](https://user-images.githubusercontent.com/20648924/114192909-a238ec80-9913-11eb-8799-271f4055ab1b.png)

And in the challenge files...
![Screen Shot 2021-04-09 at 8 47 01 AM](https://user-images.githubusercontent.com/20648924/114192905-a107bf80-9913-11eb-8932-b4b02b7e5448.png)

We could probably update these if we get to it.

**Comment by ieahleen** [comment]
@moT01 it could be a good issue to open to first timers, change from `repl.it` to `replit.com`

**Comment by moT01** [comment]
Sounds good @ieahleen 👍 - Although, I'm not sure if adjusting those should close this issue or not. Other things may arise that could use updating.

**Comment by arunkumaralagesan** [comment]
mind if i pick this up

**Comment by ShaunSHamilton** [comment]
After #41933 is merged, we should audit the whole platform for the change from `repl.it` to `Replit`, as per:
- https://github.com/freeCodeCamp/freeCodeCamp/pull/41933/files#r621498674

After that, this issue should be closable. I will adjust the OP to reflect.

**Comment by ShaunSHamilton** [comment]
What still needs to be done:
- [ ] Mention of `Replit` should just be that - `Replit`, **not** `Replit.com`
- [x] A link to the Replit platform should link to `replit.com` - not `repl.it`
- [ ] The example link (placeholder) in `SolutionForm.js` should also be updated - remember, use the file search in your favourite editor to find the file.
- [x] No changes should happen to the other language folders for this issue.

**Comment by gmfuster** [comment]
I'll continue with this.

**Comment by gmfuster** [comment]
@ShaunSHamilton  Question: In file \freeCodeCamp\cypress\integration\learn\challenges\projects.js, I am changing the link to https://replit.com/@camperbot/python-project#main.py but the original https://repl.it/@camperbot/python-project#main.py is giving a 404 error.  Do you know what it should be?  Or maybe it doesn't matter? I'm not sure what the code that has it is doing anyway so not sure about the link.  Thanks!!

**Comment by ShaunSHamilton** [comment]
@gmfuster Cypress is our testing framework. The link does not actually exist - never has. It is merely used as some input to test the sites behaviour.

Hope this clarifies.
