### ISSUE TITLE
Data Structure challenge (Everything but true) doesn't pass on a correct solution

### ISSUE THREAD

**Issue by Ismailtlem** [freeCodeCamp/freeCodeCamp#41451]
**Describe your problem and how to reproduce it:**
The challenge doesn't pass what appears to be a correct solution.
![image](https://user-images.githubusercontent.com/34961373/110859287-8104c200-82bb-11eb-9115-3651fe04345a.png)
3 tests fails with this solution : 
![image](https://user-images.githubusercontent.com/34961373/110859591-ee185780-82bb-11eb-95da-7111e7a766cb.png)

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/everything-be-true

**Tell us about your browser and operating system:**
* Browser: Chrome 
* Browser Version: Version 88.0.4324.182  
* Operating System: Ubuntu 20

**Comment by RandellDawson** [comment]
Hi @Ismailtlem 

Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by Ismailtlem** [comment]
Sure (y)
