### ISSUE TITLE
Bug - Certification Page Uses Night Theme When Set For Code Formatting

### ISSUE THREAD

**Issue by rtpHarry** [freeCodeCamp/freeCodeCamp#41463]
**Describe the bug**
I'm back again, with another bug that I've observed in the certification page.

It uses the night theme setting when styling code in the solution modal, but the page doesn't use night theme elsewhere.

**To Reproduce**
1. Visit your settings and ensure that the Night Mode is set to `on` - https://www.freecodecamp.org/settings
1. Visit a certification with script in it eg - https://www.freecodecamp.org/certification/rtpharry/javascript-algorithms-and-data-structures
1. Scroll down to the projects, click on any solution
1. Observe that the code is barely readable because its using the night theme code colours, but the certification page itself doesn't use the night theme for anything else.

![image](https://user-images.githubusercontent.com/1038062/111030876-861d5a80-83fc-11eb-9c8f-8304cf98f33c.png)

For bonus points, go back and switch night mode off and observe that it then shows readable code:

![image](https://user-images.githubusercontent.com/1038062/111030902-afd68180-83fc-11eb-9e5b-ac3b746aa83d.png)

**Expected behavior**
Should ignore the night theme setting and display in consistent colours.

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this. It was briefly mentioned, but appears to have been lost in the bussle.

Something to keep track of with this: https://github.com/freeCodeCamp/freeCodeCamp/issues/37166

**Comment by moT01** [comment]
What would be the desired experience?

I see two potential solutions
- Use the selected theme and make the background of the code viewer dark when night theme is set
- Force the code viewer to use the light theme when viewing one of the solutions on the certification

**Comment by moT01** [comment]
We want to go with the second option there - just use the light theme.

**Comment by TomerPacific** [comment]
@moT01 , is this still relevant? Wanting to help out.

**Comment by ieahleen** [comment]
Yes, it was never fixed @TomerPacific 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by TomerPacific** [comment]
@ieahleen, I'll start working on it.

**Comment by TomerPacific** [comment]
I've gone over the project structure and am trying to pinpoint where the changes must occur.
I saw the following:

- themes.js is responsible for the light/dark theme
- certifications.tsx is responsible for rendering the different certifications
- cert-and-project-map.ts has all the projects for each certification
- Inside the templates/challenges/projects folder there is the Show.tsx which I am assuming is responsible for showing the code for each project's solution
- I noticed that at the redux folder, inside index.js there is a method called createNightModeSaga (and the relevant file), but I don't know how relevant it is
- There is also the certification layout inside the layouts folder

As you are probably aware, the project's structure can be quite astounding and I would appreciate some pointers as to if I am looking in the right direction or if I should be looking elsewhere.

**Comment by ieahleen** [comment]
@TomerPacific for certification completion, you can take the solutions from the md file of the projects and submit those, so then you have a completed is cert to test stuff with

**Comment by TomerPacific** [comment]
@ieahleen, I have opened a PR for this issue. Would you mind adding the hacktoberfest-accepted label to this issue?
