### ISSUE TITLE
Bonfire: Seek and Destroy - code does not work

### ISSUE THREAD

**Issue by ShjneeUlrjch** [FreeCodeCamp/FreeCodeCamp#4146]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20var%20arg%20%3D%20arguments%3B%0A%20%20return%20arr.filter(function(val)%20%7B%0A%20%20%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%20arg.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(val%20%3D%3D%3D%20arg%5Bi%5D)%20%7B%0A%20%20%20%20%20%20%20%20return%20false%3B%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%0A%20%20%7D)%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  var arg = arguments;
  return arr.filter(function(val) {
    for (var i = 1; i < arg.length; i++) {
      if (val === arg[i]) {
        return false;        
      } else {
        return true;
      }
    }  
  });
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

The code returns [1, 3, 1, 3]. Only arg[1] is destroyed. =(

Thanks

**Comment by awesomeaniruddh** [comment]
No issues asking for help with code please.
