### ISSUE TITLE
the "Give your image a border width of 10px." doesnt work properly 

### ISSUE THREAD

**Issue by kaomry** [FreeCodeCamp/FreeCodeCamp#4147]
Challenge [Waypoint: Add Borders Around your Elements](http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%20%20%0A%0A%20%20%7D%0A%20%20%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%20%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
    

  }
  
  .thick-green-border {
    border-style: solid;
    border-color: green;
    border-width: 10px;
  }
  
</style>

<h2 class="red-text ">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by awesomeaniruddh** [comment]
@kaomry Please describe the issue.

**Comment by kaomry** [comment]
i finished everything in the level and it still show me that i need to
change the border width to 10px.
i dont know what changed, but after couple of hours i did refresh and it
accepted my 10px change..

2015-11-03 15:57 GMT+02:00 Aniruddh Agarwal <notifications@github.com>:

**Comment by ltegman** [comment]
Glad to know you were able to get it working eventually! :smile: Closing this issue as resolved. Let us know if you have any further issues.

Thanks and happy coding!

**Comment by J-Harris** [comment]
I encountered this bug.  The code test panel requires the border-width to be (at least) 11px as opposed to the specified 10px

**Comment by annhnova** [comment]
I just ran into the same bug. Screenshot below.
![waypoint bug](https://cloud.githubusercontent.com/assets/5374431/10998933/73639a60-845e-11e5-9b3f-4d93a4fc0992.png)

**Comment by ZeeMax** [comment]
Me too I encountered the same bug. Thank you @J-Harris  for sharing the solution. Yes it is 11px

**Comment by NeenuAVarghese** [comment]
I too encountered the same 10px issue. Changing the font value to 11px solved the issue. Thanks.

**Comment by TaraT1** [comment]
Me2. Thanks to @J-Harris for providing solution.

**Comment by monsterHunter** [comment]
I got this problem as well, I think it has things to do with browsers zoom. If I use 100% zoom instead of 125% it passes without a problem

**Comment by TaraT1** [comment]
Thanks @monsterHunter  for pointing to a possible cause for the conflict (10px not counted as correct).
