### ISSUE TITLE
Zipline 2 Twitter Button Link

### ISSUE THREAD

**Issue by crosscris** [FreeCodeCamp/freecodecamp#415]
I was working on zipline 2, but I noticed that the proper Twitter api for posting was not in the Zipline's bullets. This link might help campers get to the right place.

https://dev.twitter.com/web/overview

**Comment by QuincyLarson** [comment]
Hi @crosscris I'm not sure what you mean. Our second zipline involves Twitch.tv, not Twitter. Please clarify.

**Comment by crosscris** [comment]
Ahh..Sorry, I was referring to the random quote machine, zip line 3. I was not sure if the first zip line counted because it is a tutorial.
