### ISSUE TITLE
This code seems to be right but it's not working

### ISSUE THREAD

**Issue by thatsharone** [FreeCodeCamp/FreeCodeCamp#4150]
Challenge [Waypoint: Size your Images](http://www.freecodecamp.com/challenges/waypoint-size-your-images#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%7D%20%0A%20%0A%20%20.smaller-image%20%7B%0A%20%20%20%20%0A%20%20%20%20width%3A%20100px%3B%20%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%20%0A%0A%20%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%20%0A%0A%20%20%20%20%20%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
 } 
 
  .smaller-image {
    
    width: 100px; 
  }
  
</style>
 

 
<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat"> 

     

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by thatsharone** [comment]
.smaller-image {

width: 100px;

}

this isn't having any effect

**Comment by ltegman** [comment]
You need to add the class `smaller-image` to your img tag for it to take effect.

Closing as not an issue with the tests. In the future please seek help and code review in the [Gitter Help Channel](https://gitter.im/FreeCodeCamp/Help) before filing an issue with the challenge.

Thanks and happy coding!

**Comment by thatsharone** [comment]
There’s nothing in the instructions that indicate how to do this. 

It leads us to believe it needs to be done in the style section, which doesn’t work

**Comment by ltegman** [comment]
Earlier lessons like [this one](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element) cover how css classes are used to style an element.

**Comment by thatsharone** [comment]
Thanks, but that’s what I’m doing and it’s still not working

**Comment by ltegman** [comment]
You've added `class="smaller-image"` to the img tag so that it looks like `<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">`?

**Comment by thatsharone** [comment]
I really appreciate your help! But I’m still confused - here’s the instructions

CSS has a property called width that controls an element's width. Just like with fonts, we'll use px (pixels) to specify the image's width.

For example, if we wanted to create a CSS class called larger-image that gave HTML elements a width of 500 pixels, we'd use:

<style>

  .larger-image {

    width: 500px;

  }

</style>

Create a class called smaller-image and use it to resize the image so that it's only 100 pixels wide.


This seems like the code should go in the style section, but I understand now from you it should go in the image tag?

**Comment by ltegman** [comment]
It needs to go in both. When styling using CSS class selectors you need to declare the rule (this is what you're doing in the) `<style>` area with
```css
.smaller-image {
  width: 100px;
}
```
but that css rule will only be applied to any HTML elements that have been tagged with that class using the `class="smaller-image"` syntax.

When the instructions state "Create a class called smaller-image and use it to resize the image so that it's only 100 pixels wide" it is expecting you will apply the lesson from "Use a CSS Class to Style an Element" where it more explicitly instructs you to style something using a CSS class selector by telling you each step involved in the process.

**Comment by thatsharone** [comment]
Thanks so much, that makes sense and worked!

**Comment by ltegman** [comment]
Awesome! :smile:

**Comment by doransignal** [comment]
yes this isn't real clear in the directions but reading this i got it to work. thanks all

**Comment by RandyDerrell** [comment]
I'm going to go so far as saying the example is almost misleading. Even if you were on the right track and read over that example it would just about throw you off. There may be a reason why folks are stumbling on this. But, great work-thru.
Thanks to Itegman.

**Comment by jrjuneja** [comment]
Thanks for your help!

**Comment by dobs1211** [comment]
Struggling on this same thing for days, thanks for the walk thru Itegman!

**Comment by anainrd** [comment]
```<img src="https://bit.ly/fcc-relaxing-cat" class="smaller-image"> ''' you forgot to add the class to the html

**Comment by Merozibi** [comment]
Woah....struggled with this for so long- thanks for the help!

**Comment by thatsharone** [comment]
Why am I still on this distribution list and how can I get off it?

**Comment by ltegman** [comment]
@thatsharone. If you open up the thread on Github there will be a button on the right hand side that says "Unsubscribe".

**Comment by iameunme** [comment]
very helpful! Thank you so much!

**Comment by calmchaos17** [comment]
Thanks!!! This helped me too!

**Comment by ahishakiyeobed** [comment]
thanks men its its reall helped.

**Comment by tumi-lean** [comment]
I was confused still so I read the question again and made a few changes and this might someone also I did this:

`<img src="#" class="smaller-image" />`

and within the css style I did this:

`<head>
<style>
img { width: 100px; }
</style>
<title>your title</title>
</style>`

I hope this helps also :100:

**Comment by XavierHappyTime** [comment]
i solve this problem but i'm confuse about something in the css classes, so is your style inputs what happening, and your class is saying what is happening..

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  img {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img cLass="smaller-image"
     src="https://bit.ly/fcc-relaxing-cat" 
     alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by XavierHappyTime** [comment]
i know you have to have the "img" in the style because that tells the section where you suppose to be hitting but why in the images section of the picture you have to put the class="smaller-image" because i'm not understanding what it is doing ....? can any one explain....

**Comment by XavierHappyTime** [comment]
```
now when i go to the next section i'm more lost because i see when in the code they have ..

- <style>
.smaller-images;{
width: 100px;
}
   </style>

-----<h2>------ section 
<img Class="smaller-image" >
this is making the picture smaller but when i did this 
----<h2>----(what i did to pass)
<style>
img ;{
width: 100px; 
}
</style>
-------<h2>-----section
<img Class"=smaller-image">

("side note" i'm more lost then ever ???????????????????)
```

**Comment by dwd2010** [comment]
@XavierHappyTime, you could go to the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by ronit31** [comment]
Thanks for the help.

**Comment by swordv** [comment]
Agreed, i struggled with them one as well. Wasn't clear till I read the above.

Thanks

**Comment by menachemgold** [comment]
hi I created a class <img class="smaller-image">https://bit.ly/fcc-relaxing-cat</img> it didn't work when I typed smaller image in style section

**Comment by texas2010** [comment]
@menachemgold, Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Brian123456789** [comment]
This is not very good, it expects you to do something from several lessons back, but that example was with an H2 element. You have to basically guess at how to apply the tag.   class="smaller-image" Has to be inserted BETWEEN <img  (INSERT HERE)  src ="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "> .....plain as mud and was not covered earlier. So the only way to get the answer is take up people's time in the chat. In books and tutorials I have used you are never left at having to guess at things, this should be fixed, wasting time due to lack of information is not good.

**Comment by UmidBig** [comment]
Thank you soooo much Brian123456789. You resolved my problem.

**Comment by bsbatusesli** [comment]
Thanks for help @Itegman

**Comment by yankease** [comment]
thank you baby jesus and all contributors for this thread, helped me out immensely

**Comment by Riverino** [comment]
I'm having troubles with the same challenge. The smaller-image class works if I insert it into the tag before the other classes, but then the other classes do not work. Am I doing something wrong?

here it is:

.smaller-image {
    width: 100px;
  }
  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img  class="thick-green-border" class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. " >

**Comment by texas2010** [comment]
@Riverino 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
