### ISSUE TITLE
curriculum: Bug in the Create a Variable for a Specific Area challenge

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#41500]
**Describe your problem and how to reproduce it:**

The challenge expects the camper to add the following CSS property to the `.penguin` class:

```css
--penguin-belly: white;
```

However, the following code (which does not accomplish the challenge) passes due to a lack of specificity in the regex assertion:

```css
background-color: --penguin-belly:white;
```

Note that this code will not change the colour of the penguin's belly and should not pass.

This could potentially be fixed with a change in the test regex to:

```js
/.penguin\s*?{[\s\S]*\n\s*--penguin-belly\s*?:\s*?white\s*?;[\s\S]*}/gi
```

which would assert the `--penguin-belly` is preceded by a new line and some spaces, but no non-space characters.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/responsive-web-design/basic-css/change-a-variable-for-a-specific-area

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/63889819/111259735-c9ceba80-85dc-11eb-88fd-248de82fc98a.png)

Screenshot provided by `Zeal#6159` on Discord.

**Comment by texas2010** [comment]
oh yeah. in that code line, suppose to not accept any code with it. and focus only that answer.

**Comment by Sembauke** [comment]
**Note:** when adding an extra line at the beginning it will cause the RegEx not to pass.
```
  .penguin {
    /* Only change code below this line */
	 
	 --penguin-belly:white;
    /* Only change code above this line */
  }
```
