### ISSUE TITLE
Typo on waypoint: learn what to do

### ISSUE THREAD

**Issue by iheartkode** [FreeCodeCamp/FreeCodeCamp#4151]
http://www.freecodecamp.com/challenges/waypoint-learn-what-to-do-if-you-get-stuck
Should be "become" I would fix it but I'm not sure where this file is located.

![ty](https://cloud.githubusercontent.com/assets/7018580/10919925/3f4a75a2-8222-11e5-8581-332770045394.png)

**Comment by BerkeleyTrue** [comment]
closed. Fixed with #4154
