### ISSUE TITLE
[i18n] Chinese motivational and congratulatory quotes are in English

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41510]
Congratulatory quote at the top of the image:
![Screen Shot 2021-03-16 at 1 25 53 PM](https://user-images.githubusercontent.com/20648924/111374768-79eb0480-866b-11eb-9fc3-706b6eced7dd.png)

Motivational quote when on Chinese `/learn`:
![Screen Shot 2021-03-16 at 3 21 24 PM](https://user-images.githubusercontent.com/20648924/111374774-7bb4c800-866b-11eb-9a37-e6618d51b0cb.png)

The [file that holds these quotes is here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/chinese/motivation.json). It'd be nice to get a few translations in there. Unless something has changed, this doesn't have to be a translation of the English version and the arrays don't need to be the same length. So maybe if we could get 10 or so of each type in there - more would be better, but 10 is probably enough to start.

**Comment by RandellDawson** [comment]
Yeah those were just placeholders.  The idea was to have some actual quotes from each language instead of translations of the quotes as they may be lost in translation.

**Comment by leonfeng** [comment]
Translation of these quotes is currently underway and is being discussed here: https://github.com/freeCodeCamp/news-translation/issues/402

**Comment by ojeytonwilliams** [comment]
Awesome, thanks for the update @leonfeng 

I can't see an obvious way to make use of Crowdin for this.  So, as a general approach, could we ask proofreaders to take a look and come up with some appropriate replacements?  i.e. what @leonfeng is doing, but for other languages. @miyaliu666  @RafaelDavisH what do you think?

**Comment by leonfeng** [comment]
@ojeytonwilliams Sure thing :)

**Comment by miyaliu666** [comment]
Thank @leonfeng for translating the quotes. I'll do proofreading soon. As you mentioned on the Chinese forum there were some mistakes in the English version, could you create an issue, so we can modify them before translating? Thanks again!

@ojeytonwilliams We discussed about proofreader onboarding for other languages. I think @raisedadead will share a plan later. Each language should have more than one proofreader, then they can translate and review the PRs just like we do for the Chinese version. Does it make sense?

**Comment by ojeytonwilliams** [comment]
> We discussed about proofreader onboarding for other languages. I think @raisedadead will share a plan later. Each language should have more than one proofreader, then they can translate and review the PRs just like we do for the Chinese version. Does it make sense?

It does, that makes perfect sense. Thanks, Miya.

**Comment by leonfeng** [comment]
@miyaliu666 Here it is: https://github.com/freeCodeCamp/freeCodeCamp/issues/41769

The fact-checking is rather slow going though, as I'm literally Googling the quotes one by one... Any idea how we can open this up to contributions (assuming anyone else is interested)?

**Comment by nhcarrigan** [comment]
Hey @miyaliu666 where are we at with this?

**Comment by miyaliu666** [comment]
Let me review this later this week. Thanks! @nhcarrigan

**Comment by lijiang2014** [comment]
```
{
      "quote": "Whatever you are, be a good one.",
      "author": "Abraham Lincoln"
    }
```
    可以是 
{
      "quote": "但行好事,莫问前程",
      "author": "增广贤文"
    }
```
     {
      "quote": "It does not matter how slowly you go as long as you do not stop.",
      "author": "Confucius"
    },
    {
      "quote": "Real knowledge is to know the extent of one's ignorance.",
      "author": "Confucius"
    },
    {
      "quote": "The past cannot be changed. The future is yet in your power.",
      "author": "Confucius"
    },
```
应该是
```
     {
      "quote": "譬如为山,未成一篑,止,吾止也。譬如平地,虽覆一篑,进,吾往也.",
      "author": "孔子"
    },
    {
      "quote": "知之为知之，不知为不知，是知也",
      "author": "孔子"
    },
    {
      "quote": "往者不可谏，来者犹可追",
      "author": "孔子"
    },
```

```
{
      "quote": "A good traveler has no fixed plans and is not intent on arriving.",
      "author": "Lao Tzu"
    },
    {
      "quote": "An ant on the move does more than a dozing ox.",
      "author": "Lao Tzu"
    },
    {
      "quote": "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step.",
      "author": "Lao Tzu"
    },
```

应该是（第二个找不到合适的）

```
{
      "quote": "善行无辙迹,善言无瑕谪",
      "author": "老子"
    },
    {
      "quote": "上士闻道,勤而行之",
      "author": "老子"
    },
    {
      "quote": "天下难事，必作于易，天下大事，必作于细；千里之行，始于足下",
      "author": "Lao Tzu"
    },
```

**Comment by miyaliu666** [comment]
Sorry, I communicated in Chinese here and just realized it. I'll review the translations above asap. Thanks for your patience!

**Comment by moT01** [comment]
bump

**Comment by moT01** [comment]
I wonder if we should promote this somehow. I'm wondering if people don't realize these need to be translated/created. Looks like a few of the languages have added localized quotes - but many haven't, it's not just Chinese. Maybe we should just add them to crowdin.

**Comment by nhcarrigan** [comment]
The concern with adding them to Crowdin was that not all quotes/phrases are going to make sense culturally.

That is, these shouldn't be one-to-one translations - each language should select their own relevant quotes and phrases to use.

**Comment by nhcarrigan** [comment]
@miyaliu666 if these quotes are good can we get them added?

**Comment by miyaliu666** [comment]
Can you wait for another week, so I can review them and translate the rest after finishing the translation of the first curriculum? Thanks for your huge patience! @nhcarrigan
