### ISSUE TITLE
Typo in challenge for ES6 JS, "Use * to Import Everything"

### ISSUE THREAD

**Issue by Leeoku** [freeCodeCamp/freeCodeCamp#41528]
**Describe your problem and how to reproduce it:**
There is a typo in the sample text provided. The comment says "Only change code above this line" for line 1. It should be "Only change code below this line", or move line 1 to line 2

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file

**Tell us about your browser and operating system:**
* Browser Name:  Firefox
* Browser Version: Latest
* Operating System: W10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/13722143/111730453-d99e0700-8847-11eb-99e8-af3706a0b60f.png)

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this issue.

It appears our Prettier config has removed the blank space in: https://github.com/freeCodeCamp/freeCodeCamp/commit/0bd52f8bd1272ad7c7b8f8c8fc6bda4b8403bd06#diff-076eefafe36ab78a9962f4ab3b72053588bac6c4f947041bf28d396d4e4d153f

I am going to open this up to first timer only, as it should be a case of forcing the blank space to return.

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Omolajacodec** [comment]
I would like to work on this issue, I'm a first timer

**Comment by ShaunSHamilton** [comment]
@Omolajacodec Thanks, for your interest in contributing. A PR is already linked to likely close this issue. So, you are welcome to find other issues with either _first timers only_ or _help wanted_ labels. 👍
