### ISSUE TITLE
Bonfire: Diff Two Arrays, Test or Clarification?

### ISSUE THREAD

**Issue by ArgonCode** [FreeCodeCamp/FreeCodeCamp#4152]
The problem description does not make it clear what to do with elements that exist in one array more than once. The tests also do not cover such situation. 

In this simple example:
```
[1, 2, 3, 3, 5], [1, 2, 3, 4, 5]
```
the repeating element interpreted in two ways:

1. Repeating threes are unconnected elements. Thus are eliminated in pairs from both arrays. Result:
```
[3, 4]
```
2. Repeating elements are treated as the same element and all copies are removed. Result:
```
[4]
```

**Comment by ltegman** [comment]
The lack of a test case for this is intentional as per discussion in #3758. After a test case that covered this was added it was decided that it caused too much additional confusion without a worthwhile enhancement to learning.

Thanks and happy coding!
