### ISSUE TITLE
Error message is showing for FCC News homepage in certain situations(this issue is also for the author login)

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41522]
**Describe the bug**
When you try to access the FCC news author account or click on the logo at the top of the FCC news page you get this error message
We are upgrading this part of freeCodeCamp.org for the next few minutes.

I first noticed this issue when I tried to login into my author account. 
And then a few people mentioned this issue on the twitter account under one of the recent posts.
https://twitter.com/freeCodeCamp/status/1372533749724889088

You can still access the individual articles and even the homepage. 
But not the ghost account login or trying to click on the logo for the homepage. 

**To Reproduce**
1. Go to https://www.freecodecamp.org/
2. Click on the News option

or 

1. Go to https://www.freecodecamp.org/news/
2. Click on the logo

or 

1. Go to https://www.freecodecamp.org/news/ghost/#/signin

**Expected behavior**
When you click on the logo or go to the ghost sign in you should be able to see the content. 

**Screenshots**
<img width="1059" alt="Screen Shot 2021-03-18 at 7 12 17 AM" src="https://user-images.githubusercontent.com/67210629/111641672-9ba6d180-87ba-11eb-9693-d27888571652.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macbook pro]
 - Browser: tested on [ chrome, and safari]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneSE]

**Comment by raisedadead** [comment]
Thanks for reporting. On it.

**Comment by raisedadead** [comment]
Hi @jdwilkin4 

We have fixed the issue with the news (Ghost) instance. Thanks for reporting.
