### ISSUE TITLE
Possible changes to backend project endpoints

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#41529]
As mentioned in last night's Office Hour meeting, here are the current endpoints for the backend challenges, and some possible changes.

Please feel free to make any corrections or suggestions below.

### APIs and Microservices Projects

- Timestamp Microservice
  - `GET /api/timestamp/{utc_date}` - Returns a JSON object with `unix` and `utc` versions of the input date
  - `GET /api/timestamp/{ms_date}` - Returns a JSON object with `unix` and `utc` versions of the input date
  - `GET /api/timestamp/` - Returns a JSON object with `unix` and `utc` versions of the current date

- Request Header Parser Microservice
  - `GET /api/whoami` - Returns a JSON object with `ipaddress`, `language`, and `software`
- URL Shortener Microservice
  - `POST /api/shorturl/new` - Returns a JSON object with `original_url` and `short_url`
  - `GET /api/shorturl/{short_url}` - Redirects to the original URL

- Exercise Tracker
  - `POST /api/exercise/new-user` - Creates a new user and returns a JSON object with `_id` and `username`
  - `GET /api/exercise/users` - Returns all users
  - `POST /api/exercise/add` - Adds a new exercise to the specified user and return a JSON object with ...
  - `GET /api/exercise/log?userId={user_id}` - Returns a JSON object with all exercises for the specified user
- File Metadata Microservice
  - `POST /api/fileanalyse` - Returns a JSON object with the `name`, `type`, and `size` of the file

### Quality Assurance Projects

- Metric-Imperial Converter
  - `GET /api/convert?input={num_and_or_unit}` - Returns a JSON object with `initNum`, `initUnit`, `returnNum`, `returnUnit`, and `string`

- Issue Tracker
  - `POST /api/issues/{projectName}` - Creates a new issue for the specified project and returns a JSON object with `_id`, `issue_title`, `issue_text`, `created_by`, `assigned_to`, `status_text`, `created_on`, and `updated_on`
  - `GET /api/issues/{projectName}?{filter}={filterVal}` - Returns an array of JSON objects for that project. Each JSON object is an issue with these keys: `_id`, `issue_title`, `issue_text`, `created_by`, `assigned_to`, `status_text`, `created_on`, and `updated_on`
  - `PUT /api/issues/{projectName}` - Updates the passed issue's `updated_on` field and returns a JSON object with `result: 'successfully updated'` and `_id`
  - `DELETE /api/issues/{projectName}` - Returns a JSON object with `result: 'successfully deleted'` on success, and an error if the `id` was missing or couldn't be found

- Personal Library
  - `POST /api/books` - Adds a new book and returns a JSON object with `_id` and the passed `title`
  - `GET /api/books` - Returns a JSON object with an array of all book objects
  - `GET /api/books/{book_id}` - Returns a JSON object with the properties `_id`, `title`, and a `comments` array
  - `POST /api/books/{book_id}` - Adds a comment to the `comments` array for that book and updates the `commentcount`
  - `DELETE /api/books/{book_id}` - Deletes a book from the collection and returns a JSON response with a success or failure message
  - `DELETE /api/books/` - Deletes all books from the collection and returns a JSON response with a success or failure message
- Sudoku Solver
  - `POST /api/solve` - Returns a JSON object with `solution` and the solved puzzle string if successful, or different error messages
  - `POST /api/check` - Returns a JSON object with `valid` set to `true` or `false`. If `valid` is `false`, the returned JSON object will contain a `conflict` array with the strings `"row"`, `"column"`, and/or `"region"`
- American British Translator
  - `POST /api/translate` - Returns a JSON object with `text` and the original text, and `translation` with the translated word/term

### Information Security Projects

- Stock Price Checker
  - `GET /api/stock/prices?{stock_ticker}={ticker}?{like}={true/false}` - Returns a JSON object with `stock`, `price`, and `likes`. Can optionally like a stock by passing `like` as a URL param

- Anonymous Message Board
  - `POST /api/threads/{board}` - Creates a new message thread and returns a JSON object with `_id`, `text`, `created_on`, `bumped_on`, `reported`, `delete_password`, and `replies`. If POSTing to an existing thread, `bumped_on` is updated
  - `POST /api/replies/{board}` - Adds a comment to the thread and updates the thread's `bumped_on` date
  - `GET /api/threads/{board}` - Returns an array of the 10 most recently bumped threads on the board, with up to 3 replies from each. `reported` and `delete_password` are not sent back to the client
  - `GET /api/replies/{board}?thread_id={thread_id}` - Returns the entire thread as an array, but doesn't include `reported` and `delete_password`
  - `DELETE /api/threads/{board}` - Deletes a thread and returns a success or failure message
  - `DELETE /api/replies/{board}` - Deletes a comment and changes it to `[deleted]` in the thread's comments array, and returns a success or failure message
  - `PUT /api/replies/{board}` - Reports a comment, updates `reply_id` to true, and returns a success or failure message

### APIs and Microservices Projects

- ~~**Timestamp Microservice**~~
  - `GET /api/timestamp/{utc_date}` --> `GET /api/{utc_date}` - Returns a JSON object with `unix` and `utc` versions of the input date
  - `GET /api/timestamp/{ms_date}` --> `GET /api/{ms_date}` - Returns a JSON object with `unix` and `utc` versions of the input date
  - `GET /api/timestamp/` --> `GET /api` - Returns a JSON object with `unix` and `utc` versions of the current date
  - Related PRs: https://github.com/freeCodeCamp/freeCodeCamp/pull/41783, https://github.com/freeCodeCamp/demo-projects/pull/52, and https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/55

- Request Header Parser Microservice
  - `GET /api/whoami` --> `GET /api` - Returns a JSON object with `ipaddress`, `language`, and `software`
  - *Maybe?* `/api/whoami` is not a bad path/resource name

- ~~**URL Shortener Microservice**~~
  - `POST /api/shorturl/new` --> `POST /api/shorturl` - Returns a JSON object with `original_url` and `short_url`
  - `GET /api/shorturl/{short_url}` --> `GET /api/shorturl/{short_url}` - Redirects to the original URL (Same)
  - Related PRs: https://github.com/freeCodeCamp/freeCodeCamp/pull/41784, https://github.com/freeCodeCamp/demo-projects/pull/53, and https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/33

- ~~**Exercise Tracker**~~
  - `GET /api/exercise/users` --> `GET /api/users` - Returns all users
  - `POST /api/exercise/new-user` --> `POST /api/users` - Creates a new user
  - `GET /api/exercise/log?userId={user_id}` --> `GET /api/users/{user_id}/logs?[from][to][limit]` - Returns all exercises entered for the specified user. Might be better as `GET /api/users/{user_id}/exercises?[from][to][limit]`
  - `POST /api/exercise/add` --> `POST /api/users/{user_id}/exercises` - Adds a new exercise to the specified user
  - Related PRs: https://github.com/freeCodeCamp/freeCodeCamp/pull/41786, https://github.com/freeCodeCamp/demo-projects/pull/51, and https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/51

- File Metadata Microservice
  - `POST /api` - Returns a JSON object with the `name`, `type`, and `size` of the file
  - *Maybe?* `/api/fileanalyse` is not a bad path/resource name. `/api/analyzer`?

### Quality Assurance Projects

- Metric-Imperial Converter
  - `GET /api/conversion?input={num_and_or_unit}` --> `GET /api/?input={num_and_or_unit}` - Returns a JSON object with `initNum`, `initUnit`, `returnNum`, `returnUnit`, and `string`
  - *Maybe?* Is there a noun we can use to replace `convert`? **Edit:** updated possible endpoint based on suggestion below.

- Sudoku Solver
  - `POST /api/solve` --> `POST /api/solver` - Returns a JSON object with `solution` and the solved puzzle string if successful, or different error messages
  - `POST /api/check` --> `POST /api/checker` - Returns a JSON object with `valid` set to `true` or `false`. If `valid` is `false`, the returned JSON object will contain a `conflict` array with the strings `"row"`, `"column"`, and/or `"region"`
  - *Maybe?* Solve and check are verbs, but are descriptive. Are there other nouns we can use instead of `solver` and `checker`?

- American British Translator
  - `POST /api/translation` --> `POST /api` - Returns a JSON object with `text` and the original text, and `translation` with the translated word/term
  - *Maybe?* Is there a noun besides `translator` we can use instead of the verb `translate`? **Edit:** updated possible endpoint based on suggestion below.

### Notes

- This is related to https://github.com/freeCodeCamp/freeCodeCamp/issues/34933
- If on Replit, the URL might look like this: `https://boilerplate-project-{project_name}.{username}.repl.co`
- If using a subdomain: `https://{project_name}.domain.com/`
- And if using a subpath: `https://domain.com/{project_name}`
- At the very least the Exercise Tracker (major changes) and URL Shortener Microservice (minor changes) should probably be updated. Others are up for debate
- If we decide to make changes to a project's endpoints, the example project should still handle the older endpoints if possible. For example, other sites apparently use our URL Shortener example project, and removing the old endpoints would cause issues on their end. This is probably not necessary for projects like the Exercise Tracker
- Also, if we do decide to update a project, the tests on /learn can just handle the new endpoints. We can assume that someone who finished a project with the older endpoints already submitted and got credit for it. If someone with an older version of the project with the older endpoints would like to submit their project again, they would have to update it to meet the new project requirements

**Comment by RandellDawson** [comment]
> Maybe? Is there a noun we can use to replace convert?

`conversion`?

> Maybe? Is there a noun besides translator we can use instead of the verb translate?

`translation`?

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks @RandellDawson. Those are both great alternatives :+1: :+1:
