### ISSUE TITLE
 Redux: Register a Store Listener challenge passes with incorrect answer

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41535]
**Describe your problem and how to reproduce it:**
Hi there! 

A forum user in this [discussion](https://forum.freecodecamp.org/t/got-a-build-error-but-it-pased-the-test-redux-register-a-store-listener/451922) wanted to know why they received an error message for their code when it passed the test. 

Here are the FCC instructions:
Write a callback function that increments the global variable count every time the store receives an action, and pass this function in to the store.subscribe() method. 

But the user's answer did not include a callback function as you can see in the screenshot.

I think the test should only pass if a callback function was used. 

Thanks! 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/redux/register-a-store-listener

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="963" alt="Screen Shot 2021-03-19 at 7 51 59 AM" src="https://user-images.githubusercontent.com/67210629/111799201-08d46880-8888-11eb-9911-7bf563aa48c9.png">

**Comment by LaurentLabine** [comment]
Nobody looking into this yet?  I'll take it a shot!
