### ISSUE TITLE
Intellisense suggestion box appears out of place

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#41533]
**Describe the bug**
Intellisense usually shows a list and box to the side of the menu with details of the current function/object etc. Since Intellisense has been disabled, the suggestion box shouldnt be visible but that isn't so.

In the below picture, there are two boxes, the one on the right ie. detailed box is the one that appears which shouldn't happen.

![Screenshot_7](https://user-images.githubusercontent.com/36357875/111782382-64c3df00-88d2-11eb-9c9d-84bd4e04edad.png)

**To Reproduce**
1. Open any problem
2. Type something
3. Click `Ctrl + Space` (Sometimes it appears in first try but for sure it will appear when you click the buttons the second time)
4. Look at the top right corner to see a black out of place box, this is the suggestions box

**Expected behavior**
That box shouldnt be visible.

**Screenshots**
![Screenshot (760)_LI](https://user-images.githubusercontent.com/36357875/111782022-f848e000-88d1-11eb-898d-fab53eeb54de.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge, Firefox

I can create a PR once the bug is reproduced by others.

**Comment by gikf** [comment]
If there isn't cleaner way, then `Ctrl + Space`, shortcut for suggestions, could be re-bind to something else or some dummy function.

**Comment by Nirajn2311** [comment]
That can be done but currently CSS has been used to hide Intellisense so even without clicking `Ctrl + Space` Intellisense works and all user has to do is click `Enter` and it autocompletes. Or both options can be done together ie.  re-bind the button combination and hide using CSS. 
Yea there isn't a cleaner way, Monaco Editor doesn't give an option of completely disabling it.

**Comment by Nirajn2311** [comment]
Reopening the issue, as when I tried it in Edge in Macbook the issue was still there.

**Comment by Sembauke** [comment]
Hey @Nirajn2311,

I can't seem to reproduce this on Edge. Can you tell me what you did?

**Comment by Nirajn2311** [comment]
After checking with Sem, this issue now happens only for people who use MacOS. I think I've got a way to fix it and will update here tonight.

**Comment by Sembauke** [comment]
Great! Looking forward to your solution.

**Comment by raisedadead** [comment]
@Sembauke I see the PR has not been merged yet. But the issue was closed, is this resolved?

**Comment by Sembauke** [comment]
@raisedadead My bad, did not see the pending reviewer on the PR.

**Comment by raisedadead** [comment]
It's all cool; I was just confused about the issue being closed manually. We usually leave issues to get autoclosed when a PR lands to avoid missing things.
