### ISSUE TITLE
Alternative Methods

### ISSUE THREAD

**Issue by rohitbhat1603** [freeCodeCamp/freeCodeCamp#41545]
In the past we have added contextual navigation buttons in the UI to be able to reduce the nav items.

Since we have grouped all nav items in the menu button, I was wondering if having them in different pages is redundant.

Specially buttons that redirect to settings, portfolio, and sign out.
![110450876-aaafc480-80d4-11eb-891e-437f1c421200](https://user-images.githubusercontent.com/80664968/111881019-9de47800-89d4-11eb-94cb-c1d66d49f783.png)

**Comment by Sembauke** [comment]
We are discussing if contextual navigation should be removed in #41423

**Comment by ShaunSHamilton** [comment]
It appears this issue has been accidentally copied from the above mentioned link. As such, I am closing this as a duplicate.

Thank you
