### ISSUE TITLE
Obsolete / potentially offensive cultural reference

### ISSUE THREAD

**Issue by EvanHarper** [freeCodeCamp/freeCodeCamp#41540]
JavaScript Algorithms and Data Structures > Functional Programming > Use the filter Method to Extract Data from an Array

The variable watchList[0]["Actors"] contains the name of a former actress who is now an actor, having transitioned gender and changed his name to _Elliot_ Page. Many people describe it as mortally offensive or even endangering to use the former names of trans people in this way, so this should probably be changed. (It appears to be standard entertainment industry practice now to retroactively change credits in this circumstance, so that is what I would suggest.)

**Comment by RandellDawson** [comment]
The current imdb.com site has updated the actors' names section.  Since this is the source of the data for 3 challenges, I think it is reasonable to make the same change on our site.

The name appears twice in each of the following challenge files:
- `curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array.md`
- `curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array.md`
- `curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data.md`

I am opening this issue up to "first timers only" as this is an easy change.  To resolve this issue, you will need to replace the name `Ellen Page` with `Elliot Page` in all relevant places in the above challenges.

**Comment by ShaunSHamilton** [comment]
I know it is more work, but would we not be better off changing all names/(personal info) to random/unrelated names/words?

**Comment by Nirajn2311** [comment]
> I know it is more work, but would we not be better off changing all names/(personal info) to random/unrelated names/words?

Yes, I agree with this as then we wouldn't have to worry about backlash or criticism if a mistake/error is made.

**Comment by gracewest333** [comment]
Just changed the name where necessary. I wasn't too sure what you meant by changing all the names/(personal info) to random/unrelated names/words in the context of movie information. Hope I helped :)

**Comment by RandellDawson** [comment]
> I know it is more work, but would we not be better off changing all names/(personal info) to random/unrelated names/words?

The list of real movies gives the 3 challenges a more "real-life" purpose.  Changing the actor names to be random names would make the data not as interesting, not to mention inaccurate.  My proposal for changing the name will not happen often, so I do not think it is going to become a high maintenance issue.  If it were to ever become a high maintenance issue, we could adjust the challenges accordingly to be more generic in nature.

@gracewest333 Your PR only contains changes to one challenges.  To close this issue, you need to make the change across all 3 challenges referenced in the issue body.  Also, you should read through our [contributing documentation](https://contribute.freecodecamp.org) as related to creating PR titles.

**Comment by miku86** [comment]
> The list of real movies gives the 3 challenges a more "real-life" purpose. Changing the actor names to be random names would make the data not as interesting, not to mention inaccurate.

But we would also remove the need to check if facts change (like in this issue) or some moral stuff like if these folks become criminals or do other shady stuff. (Weinstein, Polanksi, Depp etc.).

I thought about using just animated movies, e.g. Toy Story, Finding Nemo, but then the whole lesson would need some changes.

**Comment by RandellDawson** [comment]
> I thought about using just animated movies, e.g. Toy Story, Finding Nemo, but then the whole lesson would need some changes.

What if the name of the voice actor changes?  It is the same situation.

**Comment by ShaunSHamilton** [comment]
>What if the name of the voice actor changes?

I think @miku86 meant use the character names, instead.

**Comment by RandellDawson** [comment]
We can do whatever, I still think the easiest solution for now is to just change the name in the 3 challenges.

**Comment by akibmaredia** [comment]
Is this still open? I am a newbie would like to start with something simple

**Comment by ShaunSHamilton** [comment]
@akibmaredia Yes, this is still open. Feel free to create a PR.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by akibmaredia** [comment]
Just to confirm, we are to replace all the instances of Ellen Page to Elliot Page?
