### ISSUE TITLE
Inconsistent styling on forum buttons and dropdowns

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#41559]
![image](https://user-images.githubusercontent.com/1884376/112137843-c77ce980-8bf6-11eb-82ae-212d7faf8e91.png)

And some of the dropdowns are not styled correctly:

![image](https://user-images.githubusercontent.com/1884376/112137992-fb580f00-8bf6-11eb-96f1-66946f8485d2.png)

Link to repository: https://github.com/freeCodeCamp/forum-theme

**Comment by H1rkul2** [comment]
which page  can you put more information regarding this issue?

**Comment by ahmadabdolsaheb** [comment]
@H1rkul2, https://freecodecamp.org/forum.

**Comment by LaurentLabine** [comment]
if it needs to solved quickly I might not be the right person but otherwise, I can look into this.

**Comment by raisedadead** [comment]
@LaurentLabine there is no deadline on a fix for this, although we would want this to fixed soon. If you are interested you should probably start by visiting the linked repository in the first comment on this issue thread.

There are some pointers on working on discourse themes. 

Once you make some progress, let us know here or in our [chat room](https://chat.freecodecamp.org/channel/contributors).

**Comment by LaurentLabine** [comment]
Alright, Sounds good!

I managed to run a local version of the discourse forum on my laptop and apply it the Theme in order to reproduce the issue so I'd say so far so good and I'm getting into it now!

**Comment by ShaunSHamilton** [comment]
Just to repeat from chat:
From just poking in the devtools, this is what I would look into:
1) Give the `ol` a `margin: 0 0 var(--nav-space)`
2) Get rid of the `.category-breadcrumb.select-kit-header` `margin-bottom: var(--nav-space)`
3) Get rid of the `.list-controls .combo-box .combo-box-header` `height: 38px`
4) The font-size is up for discussion, but I would leave it as is.

**Comment by LaurentLabine** [comment]
Thanks for your input!

I managed to find the combination of overwriting the margin to 0 and setting height to 42px seems to work.  Submitted a pull request with the changes : https://github.com/freeCodeCamp/forum-theme/pull/45.

Thanks again!

**Comment by ahmadabdolsaheb** [comment]
For the dropdown, it seems like the parent element is not respecting the size of the child element and causes the padding to overlap the child element.
element size:
<img width="264" alt="Screen Shot 2021-04-02 at 3 12 15 PM" src="https://user-images.githubusercontent.com/4591597/113414628-14ff1080-93c6-11eb-85be-ebf4945753e9.png">
containing element
<img width="274" alt="Screen Shot 2021-04-02 at 3 12 22 PM" src="https://user-images.githubusercontent.com/4591597/113414643-221bff80-93c6-11eb-8fb2-b3bd93b6b093.png">

I think just changing the display property of the child or containing element properly should do it; However, I want not able to land on a solution.

**Comment by AhmedIbrahim336** [comment]
But what about the Dropdown we can make it distinctive from the background for example give it a shadow or a border to support hierarchy

**Comment by ahmadabdolsaheb** [comment]
@AhmedIbrahim336, so our strategy with the forum theme is to stay as close to the defaults as possible. The dropdown has a carrot icon that makes its functionality obvious.

**Comment by raisedadead** [comment]
We have enabled the `/styleguide` path on the forum for you all to debug things better. It's available here: https://forum.freecodecamp.org/styleguide
