### ISSUE TITLE
numbering the lessons and not going back to the topic name after pressing 'back'

### ISSUE THREAD

**Issue by oreo-gif** [freeCodeCamp/freeCodeCamp#41555]
**Problem**
I was reviewing my lessons from ES6 which I have already done, but its very annoying to find the particular lesson I was on. example:- We have multiple lessons on destructive assignment. I did some 2 days back and again wanted to go further today but now I have to find from 4-5 lessons to see on which I was on. Suppose I clicked one and saw that I already reviewed that. After I push the back button it takes me to the title 'ES6'. Now I have to again scroll down and find the lesson. It's really frustrating. I hope you get what I'm trying to say 

**Possible solution**
The lesson from which I clicked 'back button' just a moment before could be highlighted and the page should not shift to the main topic name. 

**alternatives**
Lessons in a topic could be numbered ( recalling the serial number I accessed just now is easier )

**Additional context**
I can provide further explanation if needed. Hope you review the issue

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking time to open this feature request. I think most of what you are wanting is being resolved in version 7 of the curriculum (the project-based curriculum):
![image](https://user-images.githubusercontent.com/51722130/112129813-b369c580-8bbf-11eb-9505-1ae9267db1d7.png)

You can search for "_v7 Project Curriculum_" on the [news](https://freecodecamp.org/news/) for more information.

**Comment by ahmadabdolsaheb** [comment]
Could you more information? I am not sure I understood the issue.

**Comment by oreo-gif** [comment]
hey @ShaunSHamilton ! I'm sorry I couldn't get what you have specified here. :(
I think I need to explain more about what the problem I'm facing

**Comment by oreo-gif** [comment]
Suppose I have to revise ES6 which I have already completed before
I'll go to this heading:
![Screenshot 2021-03-24 at 11 41 27 AM](https://user-images.githubusercontent.com/71915346/112263847-f6966800-8c95-11eb-8187-fa7d5a0e18e3.png)

Then I have to find a particular topic for revising eg something from destructive assignment. The destructive assignment topic is in multiple lessons and I have to find a particular one and I don't remember the lesson name so I have to open the lessons and see from the list
![Screenshot 2021-03-24 at 11 46 06 AM](https://user-images.githubusercontent.com/71915346/112264213-89cf9d80-8c96-11eb-8c27-ae719b5acc23.png)

Suppose I opened a lesson and realised that I wasn't finding that one but a lesson after that. I'm sure that the lesson is after that one. So I pressed the BACK button from the lesson page 
![Screenshot 2021-03-24 at 11 49 43 AM](https://user-images.githubusercontent.com/71915346/112264547-0ebab700-8c97-11eb-8c5f-fa8dcf48f424.png)

After I pressed back I'M SENT BACK TO THE TOPIC NAME 'ES6' and now I have to again scroll down and find which lesson I was on like the screenshot I have uploaded below
![Screenshot 2021-03-24 at 11 52 00 AM](https://user-images.githubusercontent.com/71915346/112264799-6a854000-8c97-11eb-8550-8192a13b08b0.png)

That would be great if Rather than being sent back to the topic name :
- I'm just sent back to the area of page where the lesson was present i.e 
![Screenshot 2021-03-24 at 11 46 06 AM](https://user-images.githubusercontent.com/71915346/112264963-afa97200-8c97-11eb-88ba-f1361f67c91d.png)

- The lesson which I visited just now is highlighted like this:
![Screenshot 2021-03-24 at 11 57 27 AM](https://user-images.githubusercontent.com/71915346/112265427-7a515400-8c98-11eb-86e9-3186bbac8a62.png)

- The lesson is numbered:
![Screenshot 2021-03-24 at 12 00 37 PM](https://user-images.githubusercontent.com/71915346/112265599-be445900-8c98-11eb-8358-eac0a1ed4d59.png)

@ahmadabdolsaheb  @ShaunSHamilton I hope this explanation helps :)

**Comment by RandellDawson** [comment]
To quickly move back and forth between lessons in a section, you can click the `Esc` on your keyboard and click `n` for next lesson and `p` for previous lesson.  These are shortcut keys.

**Comment by oreo-gif** [comment]
Got it @RandellDawson . thank you for the help 💯

**Comment by ahmadabdolsaheb** [comment]
Great, the shortcuts will be included in the editor in the upcoming iteration.
I am closing this issue as it seems Randel has provided the related information.
Please let us know if this issue has been closed by mistake. happy coding.

**Comment by oreo-gif** [comment]
thank you for the help @ahmadabdolsaheb  @RandellDawson @ShaunSHamilton @nhcarrigan
