### ISSUE TITLE
This lesson won't let me go on

### ISSUE THREAD

**Issue by LisaRamos** [FreeCodeCamp/FreeCodeCamp#4155]
Challenge [Waypoint: Comment out HTML](http://www.freecodecamp.com/challenges/waypoint-comment-out-html#?solution=%3C!--%3Ch1%3EHello%20World%3C%2Fh1%3E--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--<h1>Hello World</h1>-->

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
```

**Comment by jbmartinez** [comment]
You also have to comment out the paragraph (`<p>` element)

**Comment by ltegman** [comment]
@jbmartinez is correct. Closing as not an issue with the tests.

In the future make sure you look at what tests are failing on the left hand side of the screen and ask for help on our [Gitter Help Channel](https://gitter.im/FreeCodeCamp/Help) before filing a bug with the challenge.

Thanks and happy coding!
