### ISSUE TITLE
Learners being directed to create env variables in replit.

### ISSUE THREAD

**Issue by Christopher-Stevers** [freeCodeCamp/freeCodeCamp#41558]
I was directed to create and use .env files when using replit.com(which was recommended by freeCodeCamp. Replit does not allow you to use env files. [https://replit.com/bugs/p/replrun-not-loading-environment-variables](url). I would suggest the user be notified about replit's policy.

[https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-the--env-file](url).

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 86.0.1
* Operating System: Windows 10 (64 bit)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this issue. Please note: ReplRun is slightly different, and not used for any of the Nodejs projects on freeCodeCamp.

`.env` files work as expected on Replit:
![image](https://user-images.githubusercontent.com/51722130/112146667-bff81900-8bd3-11eb-81b9-dee649c865e4.png)

![image](https://user-images.githubusercontent.com/51722130/112146599-aeaf0c80-8bd3-11eb-81a4-7a998d8c56d8.png)


As such, I am closing this issue. Thank you
