### ISSUE TITLE
Typo - Extra paragraph on final React and Redux lesson

### ISSUE THREAD

**Issue by rtpHarry** [freeCodeCamp/freeCodeCamp#41569]
**Describe your problem and how to reproduce it:**

There is a paragraph tag breaking up the sentence at the start of the create react app link.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/moving-forward-from-here

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  Latest
* Operating System: MacOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/1038062/112314250-b688b280-8ca0-11eb-9270-831c947041dc.png)

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this issue.

It appears it was potentially introduced here: https://github.com/freeCodeCamp/freeCodeCamp/pull/39800/files#diff-5c92d03acb07d19db25f4377f4f9447173f1c4b3250af0bbed06dc568cadf494

@ojeytonwilliams Is there any reason the parser needs this formatting?
