### ISSUE TITLE
Viewing v7 Certs from SuperBlock Fails

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41564]
To reproduce:
1) Complete any v7 projects
2) Go to settings to claim certificate
3) Navigate to related SuperBlock
4) Click on widget to view
5) Experience error:
![image](https://user-images.githubusercontent.com/51722130/112209172-159ee680-8c11-11eb-8feb-3ae09e86ac28.png)

I am busy fixing this now, before #41147

**Comment by ojeytonwilliams** [comment]
Just a quick note: the problem occurs when you try to follow the link to the certification.
