### ISSUE TITLE
I can't delete symbols when editing code on a SMARTPHONE while solving a task

### ISSUE THREAD

**Issue by Gramazeka-Reachyourgoals** [freeCodeCamp/freeCodeCamp#41578]
**Describe the bug**
Smartphone bug only
Situation: I open some lesson, like(https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/using-the-test-method), turn on tab 'Code' and try with smartphone keyboard to solve task. I can type smth, but when I delete it site don't show any changes. So I can't delete wrong code, if I need. Because of this, I cannot solve tasks from the phone, only from the PC.

**To Reproduce**
Steps to reproduce the behavior on smartphone:
1. Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/using-the-test-method (actually any lesson)
2. Click on tab 'Code' at the top of the page
3. Write some text
4. Try to delete it 
5. See error -> It's not deleted

**Expected behavior**
I expected this code to be removed; instead, it remained unchanged.

**Screenshots**
https://youtu.be/bSR_HRmxzuM

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 4, Xiaomi Redmi 8
 - OS: Android 7.0NRD90M, Android 10 QKQ1.191014.001(respectively)
 - Browser: Chrome 89.0.4389.105, Firefox 87.0.0-rc.1(I think it don't depend of browser)
 - Version: ?

**Additional context**
I wish freecodecamp.org to develop and get better, that's why I created this problem on github. I would really like to see this problem solved. because it was this platform that helped me learn and understand many things in web development. If you need more information, you can write to this email -> gramazekavip@gmail.com

**Comment by nhcarrigan** [comment]
Hey there, 

This is a known issue with the way the default keyboard in phones interact with the editor (likely due to the text prediction and autocorrect). We have an article which will point you toward some alternative keyboards that mesh well with freeCodeCamp: https://www.freecodecamp.org/news/freecodecamp-mobile/

For now, we are going to close this issue. 🙂

**Comment by Gramazeka-Reachyourgoals** [comment]
I'll try this keyboard, and it's work. Thank you, for gives the solving.
Best wishes!)

**Comment by nhcarrigan** [comment]
Glad to help. Happy coding!

**Comment by azatecas** [comment]
I was about to report this issue glad it's already known. While changing to an alternative keyboard works, i feel the users should be notified of this issue and potential solutions in a modal or popup when on a mobile view. People starting out wont know to visit github issues

**Comment by QuincyLarson** [comment]
@azatecas This is a good point. @nhcarrigan perhaps we could notify them "Hey it looks like your using Android. We recommend installing the freeCodeCamp Android app for a better coding experience. Or at least reading this: https://www.freecodecamp.org/news/freecodecamp-mobile/"
