### ISSUE TITLE
CI pipeline for coderadio

### ISSUE THREAD

**Issue by Ismailtlem** [freeCodeCamp/freeCodeCamp#41582]
Since tests are being written for the coderadio repo, I think that some CI pipeline testing every new PR would be great for that to make sure that it doesn't break anything.

@ahmadabdolsaheb what do you think ?

**Comment by raisedadead** [comment]
Yes please.

**Comment by Ismailtlem** [comment]
yes

**Comment by huyenltnguyen** [comment]
You have my vote too 😄 This is something I have in mind as well when working with code radio, but have not been able to look into it due to time limit.

**Comment by ahmadabdolsaheb** [comment]
Here is something to get the party started. https://github.com/freeCodeCamp/coderadio-client/pull/138

**Comment by Ismailtlem** [comment]
Is this issue completely done ?

**Comment by ahmadabdolsaheb** [comment]
Almost. We would just need to linting related actions, and we should be good to go.

**Comment by Ismailtlem** [comment]
Is there recommanded way to divide this line https://github.com/freeCodeCamp/coderadio-client/blob/main/.github/workflows/cypress.yml#L17 into 2 lines ?
That's the only linting error in this file from what I see

**Comment by ojeytonwilliams** [comment]
```yaml
        run: |
          echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" \
          >> $GITHUB_ENV
```
should work.  How're you running into this error, though?  Lint should only be looking at .js files.

**Comment by Ismailtlem** [comment]
It's an error that I got from yamllint (https://yamllint.readthedocs.io/en/stable/)

It's a tool that checks the validity of a yaml file

**Comment by moT01** [comment]
Are you still working on this @Ismailtlem?

**Comment by Ismailtlem** [comment]
I think it's done

**Comment by moT01** [comment]
Awesome, I haven't interacted with that repo really - so it's in place then and this can be closed?

**Comment by Ismailtlem** [comment]
@ahmadabdolsaheb  ?

**Comment by ahmadabdolsaheb** [comment]
We would just need to add the linters and an action and this could be closed after that.

**Comment by Ismailtlem** [comment]
Hi @ahmadabdolsaheb 

- Do you mean adding a linter job ? In a different file or in the same one ? (maybe just renaming the file will be enough)
- What's the purpose of the action that needs to be added ?

**Comment by ahmadabdolsaheb** [comment]
=
> * Do you mean adding a linter job ? In a different file or in the same one ? (maybe just renaming the file and adding a linter job will be enough)
Yes a seperate linter github action
> * What's the purpose of the action that needs to be added ?
linting :)
We have one for the learn repo.

**Comment by ahmadabdolsaheb** [comment]
@Ismailtlem thanks for working on this 🙌
