### ISSUE TITLE
Typo - All code on one line in D3 lesson

### ISSUE THREAD

**Issue by rtpHarry** [freeCodeCamp/freeCodeCamp#41587]
**Describe your problem and how to reproduce it:**
All of the code is on one long line, rather than being formatted.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/work-with-data-in-d3

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Latest
* Operating System:  MacOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/1038062/112551529-0a86ba80-8db9-11eb-9e49-2aa28e2ca661.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. I believe this was fixed with: https://github.com/freeCodeCamp/freeCodeCamp/pull/41572

As such, I am closing this as shipping.
