### ISSUE TITLE
Redundant scrollbars in curriculum answers

### ISSUE THREAD

**Issue by pkarczma** [freeCodeCamp/freeCodeCamp#41598]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
Under many (or probably all) answers in courses questions there is a vertical scrollbar that does nothing - there is nothing to scroll through. It is not breaking anything but it is a little bit annoying and misleading in a way that I am confused if maybe a part of the answer is hidden and I need to scroll through to see it fully. I haven't checked all questions but this probably applies to every single question in all courses.

**To Reproduce**
1. Go to freeCodeCamp's curriculum webpage
2. Click on any of the videos to the courses, e.g. https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/natural-language-processing-with-rnns-recurring-neural-networks
3. Scroll down to question & answers
4. Look at the bottom of every question

**Expected behavior**
I guess there shouldn't be any scrollbars if they are not needed.

**Screenshots**
![Screenshot from 2021-03-26 13-47-27](https://user-images.githubusercontent.com/26768923/112633711-fcc54980-8e39-11eb-9c55-1ff42737f9c0.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser: chrome
 - Version: 89.0.4389.82 (Official Build) (64-bit)

**Additional context**

**Comment by raisedadead** [comment]
We have a fix incoming with https://github.com/freeCodeCamp/freeCodeCamp/pull/41556, thanks for your patience while this gets deployed on the platform.
