### ISSUE TITLE
Tutorial forcing redirect to GitHub

### ISSUE THREAD

**Issue by Dumbaz** [FreeCodeCamp/FreeCodeCamp#4159]
During the first steps of FreeCodeCamp, I am getting asked to go to GitHub [on this step](http://www.freecodecamp.com/challenges/waypoint-create-a-github-account-and-join-our-chat-rooms). I can not skip this step, even though I logged into FreeCodeCamp via my GitHub Account from the get-go. Neither can I skip the next steps, the buttons are grayed out until I click the link.

All steps regarding GitHub account creation should be skipable when logging in via GitHub.

**Comment by awesomeaniruddh** [comment]
That's a good point. Many users do not do these steps (which are important), which is why it was forced. 

Thanks for the suggestion @Dumbaz

**Comment by QuincyLarson** [comment]
Yes, we want to create a "skip" button. I'll create the issue and close this one.

**Comment by Dumbaz** [comment]
I have searched for this issue, but nothing turned up, as the title is not very informative. Thanks either way.
