### ISSUE TITLE
missing semicolon after background-color: gray

### ISSUE THREAD

**Issue by Lapkritinis** [FreeCodeCamp/FreeCodeCamp#4160]
just to have clean style :)

**Comment by awesomeaniruddh** [comment]
@Lapkritinis Which waypoint are you referring to?

**Comment by Lapkritinis** [comment]
Cant find it... As there is no easy way to navigate between waypoints and
see original code. Somewhere in "html5 css" and 30-54 waypoints

On 2015-11-04, at 11:21, Aniruddh Agarwal <notifications@github.com> wrote:

@Lapkritinis <https://github.com/Lapkritinis> Which waypoint are you
referring to?

—
Reply to this email directly or view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4160#issuecomment-153649478>
.

**Comment by awesomeaniruddh** [comment]
Are you referring to this waypoint: [Waypoint: Give a Background Color to a Div Element](http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%20%0A%20%20.gray-background%20%7B%0A%20%20%20%20background-color%3A%20gray%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cdiv%20class%3D%22gray-background%22%3E%0A%20%20%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%3C%2Fdiv%3E%0A%0A%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%20checked%3E%20Indoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%20checked%3E%20Loving%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Energetic%3C%2Flabel%3E%0A%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%3C%2Fform%3E%0A)

Are you referring to the fact that you can pass the waypoint without putting a semicolon?

**Comment by Lapkritinis** [comment]
This one. In "source" missing semicolon - thats it :)

On 2015-11-04, at 12:18, Aniruddh Agarwal <notifications@github.com> wrote:

Are you referring to this waypoint: Waypoint: Give a Background Color to a
Div Element

Are you referring to the fact that you can pass the waypoint without
putting a semicolon?

—
Reply to this email directly or view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4160#issuecomment-153671800>
.

**Comment by awesomeaniruddh** [comment]
I am unable to locate the missing semi-colon. Can you please post a screenshot?

**Comment by Lapkritinis** [comment]
different waypoint:
http://www.freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element#

**Comment by awesomeaniruddh** [comment]
Oh, right I see it. Thanks for reporting this @Lapkritinis
