### ISSUE TITLE
Not able to get the CSS Class right in below code. Need to have the below font in Red. Please do the need full.

### ISSUE THREAD

**Issue by naveenmarigowda** [FreeCodeCamp/FreeCodeCamp#4161]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%0A%20%3Cstyle%3E%0A%20%20%20h2%20%20%7Bcolor%3A%20red%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

 <style>
   h2  {color: red;}
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by ltegman** [comment]
Please use the [Gitter Help Channel](https://gitter.im/FreeCodeCamp/Help) to ask for help with your code.

Thanks and happy coding!
