### ISSUE TITLE
The datasets link leads to a 404 page

### ISSUE THREAD

**Issue by qiqicodes** [freeCodeCamp/freeCodeCamp#41646]
**Describe your problem and how to reproduce it:**
I'm currently translating this article to Chinese, and the "several datasets" link under "A note on objectivity" leads to a 404 page.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/coding-bootcamp-handbook/

**Recommended fix, suggestions (how would you update it?):**
If there is an updated url, I would love to include it in the original and translated article.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2021-03-28 at 5 01 17 PM](https://user-images.githubusercontent.com/68657634/112772959-a0ecf300-8fe8-11eb-9be9-ced551082cd2.png)
![Screen Shot 2021-03-28 at 5 01 34 PM](https://user-images.githubusercontent.com/68657634/112772961-a5191080-8fe8-11eb-8c20-90be23823a1c.png)

**Comment by QuincyLarson** [comment]
@qiqicodes Awesome. Thank you for catching this broken link. I've updated the link to point to the right place
