### ISSUE TITLE
Profile Picture Upload

### ISSUE THREAD

**Issue by oussamanidhal** [freeCodeCamp/freeCodeCamp#41642]
**Describe the bug**
when i am using Freecodecamp platforms this days, my profil picture does not appear in the menu bar and in the profil setting page. Freecodecamp don't allow users to upload their profil picture to the website, instead of that, they ask for the link of the picture. and this can make a problem.

**Steps to reproduce the behavior:**
1. Go to 'freecodecamp.org'
2. Click on 'sign in '
3. **See the  error in the top right of navbar** 
4. click on menu 
5. Scroll down to 'settings'
6. **you can see also the full picture does not appear**

**Screenshots**
![contribution1](https://user-images.githubusercontent.com/48177890/112765317-93ddfd00-9004-11eb-8139-bbdc63b9d688.PNG)

**Desktop information:**
 - OS: Windows
 - Browser: Chrome
 - Version: 89.0.4389.90

**Comment by ShaunSHamilton** [comment]
Hello there,

This is not a bug, but the expected behaviour. As such, I have turned this into a feature request to add upload functionality.

**Comment by raisedadead** [comment]
Hello,

Thanks for reporting. We have intentionally not implemented the feature for various needs. Some of them being able store and process files and also implementing a whole backbone of making sure we avoid nefarious uploads.

Most users have a social profile. You can use some of these instead, for example if you have an account on freeCodeCamp forum or GitHub

At the same time explaining the above workaround on the settings page is quite an overkill.
