### ISSUE TITLE
Scaped character myDog\'s

### ISSUE THREAD

**Issue by Damian143** [FreeCodeCamp/FreeCodeCamp#4165]
Update myDog\'s "name" should read Update myDog's "name"
![sin_ti_tulo_](https://cloud.githubusercontent.com/assets/6015034/10942362/f5ab3776-82f6-11e5-9082-350418469b10.jpg)

**Comment by bugron** [comment]
@Damian143 thanks for posting this issue!
Please, provide the link to the challenge.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Damian143** [comment]
The error is in:
Basic Javascript, Waypoint: Update the properties of a javascript object
http://www.freecodecamp.com/challenges/waypoint-update-the-properties-of-a-javascript-object
