### ISSUE TITLE
UX improvement to the forum’s Ask For Help template

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#41654]
**Describe the bug**
Last week, I saw multiple posts where people asking for help didn’t write down what they needed help with.

I think the help post template may be confusing some folks.

**Screenshots**
![Screenshot 2021-03-29 082908](https://user-images.githubusercontent.com/53984269/112882923-a298e280-90de-11eb-89f2-2c18ea360cb6.png)

**Additional context**
“Tell us what’s happening” looks a bit like an overall heading. I suggest the following changes to make it more obvious that people are supposed to write something down:

**Mockup**
![Mockup 2021-03-29 082908](https://user-images.githubusercontent.com/53984269/112883087-db38bc00-90de-11eb-9c0d-5440a36b59f0.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. I believe it would help _some_ Campers understand the need to add more information.

However, I suspect the large majority just post without reading any further. The Discourse software does have a lot of cool features aiding the topic creating (e.g. Information about informative titles, showing similar topics).

---

If others are in agreement, this would be an easy implementation, and could be put up for first timers? That being said, I find dedent to be pesky.

**Comment by jeremylt** [comment]
I'm not big on the idea of adding an extra heading. Perhaps just the extra describe prompt:

---


**Tell us what's happening:**
 Describe your issue in detail here

**Your code so far:**
```
code
```
**Your browser information:**
blah blah blah

---

Mildly related - I think we should add a colon after "**Your code so far**" to match the other headings.

**Comment by LaurentLabine** [comment]
If it's a first-timer I'll let somebody do it but if not I can take care of making the changes.  Your call!

**Comment by jeremylt** [comment]
Any decision on if we're opening this for first timers?

**Comment by harshgoel05** [comment]
@LaurentLabine Can I work on this issue, being my first contribution to freeCodeCamp?

**Comment by ahmadabdolsaheb** [comment]
@harshgoel05, please go ahead.

**Comment by gracewest333** [comment]
Hi, I saw that this issue wanted to be done by someone a few days ago, but its still not been closed, I am also an newbie and am really eager to contribute so would be happy to help, and close it today. Was trying to find the template to change it, but couldn't find the file. Would it be possible for someone to point me to the right file? Thanks :)

**Comment by gikf** [comment]
Hey @gracewest333, it's this one -  
https://github.com/freeCodeCamp/freeCodeCamp/blob/ad9b1f89d8ef21c8ecd81c95717ed7e5582ff380/client/src/templates/Challenges/redux/create-question-epic.js

**Comment by gracewest333** [comment]
Thanks
