### ISSUE TITLE
UX Consistency 

### ISSUE THREAD

**Issue by oussamanidhal** [freeCodeCamp/freeCodeCamp#41653]
**Is your feature request related to a problem? Please describe.**
Consistency is one of the UX Design principal that every website should take care of that.
Sign out button above the title of the page "Account Settings for User Name" is not a good choice. 

1.Go to 'Freecodecamp.org'
2.Click on 'Menu'
3.Scroll down to 'Settings'
4.See an error.

Screenshots

![contribution2](https://user-images.githubusercontent.com/48177890/112863295-9e54d100-90ae-11eb-8a3e-301209b2d40f.PNG)

**Describe the solution you'd like**
I think that we should Remove this button or change the position at the bottom of the page. Because we have this button in the Menu

*

**Comment by Sembauke** [comment]
Hey @oussamanidhal ,

You have posted this 3 times already the reason why your post is getting closed is that it is a duplicate.
Please forward your suggestion to #41423

Hope to see you there :)

**Comment by ShaunSHamilton** [comment]
As mentioned above, it has been explained in the previous issues, this is a duplicate. Please read through issue #41423 .
