### ISSUE TITLE
Two Spanish challenges with the same title

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#41673]
curriculum/challenges/espanol/01-responsive-web-design/css-flexbox/apply-the-flex-direction-property-to-create-a-column-in-the-tweet-embed.md

and 

curriculum/challenges/espanol/01-responsive-web-design/css-flexbox/apply-the-flex-direction-property-to-create-rows-in-the-tweet-embed.md

Have the same title, "Aplica la propiedad flex-direction para crear filas en el tweet Insertado"

@RafaelDavisH could you take a look? Unfortunately it'll cause the tests to fail: https://github.com/freeCodeCamp/freeCodeCamp/pull/41512

**Comment by RafaelDavisH** [comment]
Thanks, @ojeytonwilliams for catching this. This falls on me, I approved the translation. It's now corrected on CrowdIn to 'columnas'.

**Comment by ojeytonwilliams** [comment]
No worries, that's exactly what the tests are designed to catch.  Thanks for the quick fix!
