### ISSUE TITLE
Manipulating Complex Objects Javascript passes with trivial code

### ISSUE THREAD

**Issue by cyneptic** [freeCodeCamp/freeCodeCamp#41675]
**Describe your problem and how to reproduce it:**

<details>
<summary>Previous comments</summary>

I know going for something like this defeats the whole purpose of learning, I just couldn’t help but try this and it passed. since I had some hard challenges so far that really engaged me by putting so many limits on. I thought maybe I should report this so that a new limit to prevent such action makes it more engaging.
i’m sorry if this is not the place to post or its not important at all.

Thank you for this great site, its helping me learn quite fast, and its pretty fun and engaging.

</details>

The challenge passes with incorrect code.

**Description:**

Used this code which simply adds `{}` to the array before the sample code and passes all the tests.

```js
var myMusic = [
{}, // this is what i tried xD
{
  "artist": "Billy Joel",
  "title": "Piano Man",
  "release_year": 1973,
  "formats": [
    "CD",
    "8T",
    "LP"
  ],
  "gold": true
}
// Add a record here
];
```

<details>
<summary>Previous comments</summary>

What I did was that I saw the challenge requires the [1](second) object of the array to have certain criteria and no other limitations
putting a {}, at the start instead of typing an entire 2nd object made the challenge pass.

</details>

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

NA

**Comment by raisedadead** [comment]
Hi @cyneptic 

Can you please report this on [our forum first](http://forum.freecodecamp.org/) and see if this is a bug with the challenge or your code so far, the awesome folk there will help you with the challenge.

If there is a reason to believe this is a bug, we can reopen this for investigation.

Thanks, and happy coding.

**Comment by cyneptic** [comment]
I had opened a ticket on the forum, they told me to report it here.

**Comment by raisedadead** [comment]
Thanks for getting back to us. Can you point me to the forum post (it's the URL of the post in your browser)?

**Comment by cyneptic** [comment]
https://forum.freecodecamp.org/t/found-a-solution-that-might-not-be-ideal-for-learning/453661

**Comment by raisedadead** [comment]
Thanks for sharing a link to the post, when we first read thru the issue report it did not make much sense and now that I have given the forum post a read it makes more sense now. I have edited your original report here for better readability.

Thanks for reporting this.

**Comment by LaurentLabine** [comment]
Hey,

Send it my way i'll take a look!

**Comment by Sembauke** [comment]
Oh, @LaurentLabine  I am also taking a look already

**Comment by LaurentLabine** [comment]
No problem i'll find something else! Cheers!
