### ISSUE TITLE
Spanish CSS Strong Tag Bug

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41672]
Challenge File: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/espanol/01-responsive-web-design/applied-visual-design/use-the-css-transform-scale-property-to-scale-an-element-on-hover.md

As reported by _raulsanctes_, this challenge has a malformed `strong` tag around the note: https://forum.freecodecamp.org/t/simple-css-error-in-task-pane-only-in-spanish-version/453649

I am not sure why the opening tag got like this: 
![image](https://user-images.githubusercontent.com/51722130/113011539-cce7b000-9171-11eb-95c3-1ce48eb46933.png)

**Comment by RafaelDavisH** [comment]
"Note" should be wrapped with `<strong x-id="1">Note:</strong>` not with a code tag. I'll make the PR to correct this in min.

![note](https://user-images.githubusercontent.com/6822714/113052459-031a3500-915c-11eb-880d-b4d5e6fcc62e.PNG)

**Comment by RafaelDavisH** [comment]
Corrected on CrowndIn 👍
