### ISSUE TITLE
Fibonacci numbers page is blocking

### ISSUE THREAD

**Issue by nchabini** [FreeCodeCamp/FreeCodeCamp#4169]
Challenge [Bonfire: Spinal Tap Case](http://www.freecodecamp.com/challenges/http://www.freecodecamp.com/challenges/bonfire-sum-all-odd-fibonacci-numbers) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Hello guys,

I wrote some code and I think there is something wrong with it cause the page loads but I there is nothing I can do in it- not pressing buttons, not deleting code, it is completely unresponsive. No other page is blocking. What can I do to fix this?

**Comment by SaintPeter** [comment]
You may have written an infinite loop.  You can clear your solution from you local storage:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage

**Comment by nchabini** [comment]
I think that is exactly what happened! Thank you for the solution!

**Comment by ltegman** [comment]
Thanks @SaintPeter! Closing as resolved.

Thanks and happy coding!
