### ISSUE TITLE
Links to news from search open in same tab

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41729]
If you search news articles using the search bar on /learn and click one - it opens in the current tab. All the links to news in the footer open in a new tab. Seems like they should all open in a new tab.

**Comment by michaelparkadze** [comment]
I can modify it to open in a different tab but my question is, is it really a bug? I think maybe it was intentional but I could still make a pull request and maybe have it 'fixed'.

**Comment by Nirajn2311** [comment]
Well it would be better if anything other than 'learn' stuff appeared in a new tab, that way the user knows its different.

**Comment by michaelparkadze** [comment]
Here you go, made the change for the results to open in a new tab :)

**Comment by ahmadabdolsaheb** [comment]
In addition to the search suggestions, searching the news by clicking the magnifying glass or "See all results for" should also open in a new tab since these are external pages to the learn platform.
