### ISSUE TITLE
API and Microservices: Timestamp challenge 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#41730]
**Describe your problem and how to reproduce it:**
I was wanting to know if my advanced solution 
was something that FreeCodeCamp was interested in. I use a 
function to determine whether or not the value is a Timestamp. 
I based this on how the JavaScript date object 
can't parse a string objects that only has numeric
characters in it. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice

**Tell us about your browser and operating system:**
* Browser Name: FireFox
* Browser Version: 87.0
* Operating System: Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![My timestamp function](https://user-images.githubusercontent.com/9373245/113435539-01957a80-93b1-11eb-8141-e248f479185d.PNG)

**Comment by gikf** [comment]
Hey @a2937 I'm not sure I understand. If you just want feedback on your project, then ['Project Feedback' category on forum](https://forum.freecodecamp.org/c/project-feedback/) is a more appropriate place for that. Or do you have a problem with project?

**Comment by Sembauke** [comment]
Hey @a2937  If I understand correctly you are asking if freeCodeCamp is interested in improving their test to pass the challenges?

Here are the current test for the project:
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.md

**Comment by a2937** [comment]
> That’s it. There is no intermediate or advanced solution yet. If you have a better, more elegant solution, help us all out and contribute them! 

On the [Get a hint](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-timestamp-microservice/301508) page it asked to contribute them. I believe [my solution](https://github.com/a2937/boilerplate-project-timestamp) is more elegant.

**Comment by gikf** [comment]
There's actually discussion regarding removing solutions for projects from hints entirely - see #40472 - so it might not be desired to add more solutions at this time.

I'm marking this as needing hints update to at least remove mentioned note, which may be misleading right now.

**Comment by moT01** [comment]
Thanks for the solution @a2937. The consensus on the issue @gikf linked seems to be to remove solutions for certification projects, as to make it less tempting for people to copy and paste answers. So I think it's safe to say that we won't be adding this. If anyone thinks I am wrong in closing this issue, feel free to leave a comment and we can reopen it. Thanks and happy coding 🎉
