### ISSUE TITLE
Typo in Introduction for Quality Assurance certification

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#41743]
**Describe your problem and how to reproduce it:**
In the introduction, there is a typo in the second paragraph.
"In the Quality Assurance Certification, you'll learn how to write to write tests with Chai to ensure your applications work the way you expect them to."

There is an extra "to write" in that sentence that needs to be removed. 

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/quality-assurance/

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="975" alt="Screen Shot 2021-04-04 at 9 56 30 AM" src="https://user-images.githubusercontent.com/67210629/113515889-0fbbd600-952c-11eb-9c39-9c9633ebc210.png">

**Comment by ShaunSHamilton** [comment]
Thank you, for reporting this. However, this has been recently fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/41733

As such, I am going to close this as resolved/shipping
