### ISSUE TITLE
Incorrect use of display property in article text

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#41749]
The article text incorrectly uses the `display` property with `position` values.

Example:

> First, set the `display` property of the parent element to `relative`.
Then for the child element, set the `display` property to `absolute` and `top` to `50%:`

The actual code example that follows is correctly using the `position` property.

News article: https://www.freecodecamp.org/news/how-to-center-anything-with-css-align-a-div-text-and-more/

**Comment by PeroHub** [comment]
Please, is there any fix that should be done to this issue @lasjorg ? as I can't seem to understand what is required to be done to the display and position properties

**Comment by supzi-del** [comment]
I want to work on this but I'm unable to find the file this article is located in.

**Comment by ShaunSHamilton** [comment]
@PeroHub and @supzi-del Thank you, for your interest in contributing.

Issues labelled with the _help wanted_ or _first timers only_ labels are open for contribution. This issue is with regards to the news platform, which is not publicly editable. As such, a member of staff with write access to the platform will make necessary changes.

**Comment by PeroHub** [comment]
Alright thank you @ShaunSHamilton for the prompt feedback.

I will definitely check out the first timers labels and contribute

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/42240#issuecomment-848897634

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching those typos, @lasjorg. I went in and changed the text `display` to `position` wherever applicable.

Please let us know if you notice issues in any other articles.
