### ISSUE TITLE
"Get JSON with the JavaScript fetch method" Test Too Specific

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#41750]
Challenge Page: https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-fetch-method
File: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/get-json-with-the-javascript-fetch-method.md

Code which passes:
```
      // Add your code below this line
      fetch('/json/cats.json')
        .then(response => response.json())
        .then(data => {
          document.getElementById('message').innerHTML = JSON.stringify(data);
        })
      // Add your code above this line
```
Code which fails:
```
      // Add your code below this line
      fetch('/json/cats.json')
        .then(response => response.json())
        .then(x => {
          document.getElementById('message').innerHTML = JSON.stringify(x);
        })
      // Add your code above this line
```

The test should not rely on the variable name.

Suggestion for 3rd test:
```
assert(__helpers.removeWhiteSpace(code).match(/\.then\(\(?\w+\)?=>{[^}]*}\)/g));
```

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by kitarp29** [comment]
I would love to work on this @ShaunSHamilton 
Please assign this to me

**Comment by JoshuaPelealu** [comment]
Hey @kitarp29, Usually if there is a 'Help Wanted' label, anyone can start working on it. I think @ShaunSHamilton meant to do this, but You can definitely start working on this! 

Thank you for helping us improve freeCodeCamp!

**Comment by kitarp29** [comment]
No problem @JoshuaPelealu I will wait for some time for Shaun to do it.
ELse I will start working on it

**Comment by ShaunSHamilton** [comment]
@kitarp29 Hey there,

This is open for contribution. Please read the last paragraph of the original post.

**Comment by ojeytonwilliams** [comment]
Since there's a 'first timers only' label, you're very welcome to contribute @kitarp29.
