### ISSUE TITLE
`e` keymap not working in challenges with JS

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#41751]
**Describe the bug**
In challenges which make use of JS in the editor, the `e` keymap doesn't work as in it doesn't focus on the editor.

**To Reproduce**
1. Go to any challenge with a JS editor like [Comment-your-javascript-code](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code) or [Add-comments-in-jsx](https://www.freecodecamp.org/learn/front-end-libraries/react/add-comments-in-jsx)
2. Don't focus on the editor
3. Click `e` in your keyboard
4. The editor doesn't get focused

**Comment by hassaanp** [comment]
I have pushed a fix for this.
The issue was due to the `editorRef` not being assigned to the appropriate child component.

I have verified the fix locally.
