### ISSUE TITLE
Misattributed motivational quotes

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#41769]
**Describe your problem and how to reproduce it:**
While translating the motivational quotes into Chinese, I discovered that many of them are attributed to the wrong person, or are not actual quotes at all.

**Why I believe this is important enough to open an issue**
Although not bugs in the code, these misattributions are akin to typos. And since freeCodeCamp is an educational organization, the curriculum material's accuracy matters, whether directly related to coding or not.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Instead of listing all the misattributions here, I'll propose a PR and link to my sources in the comments there.

Thank you for reading this.

**Comment by raisedadead** [comment]
Hi @leonfeng yes, we haven't gotten around to a good set of motivational quotes for Chinese (I believe we have some for Spanish). If you are interested in curating some of these and making a PR while fixing the current ones, we would love to have them in the repository. 

I am sure both @QuincyLarson and @Miya would appreciate this as well.

Let us know?

**Comment by moT01** [comment]
Any progress on this @leonfeng?

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
