### ISSUE TITLE
Waypoint: Make Object Properties Private - Instruction Clarity

### ISSUE THREAD

**Issue by MattYamamoto** [FreeCodeCamp/FreeCodeCamp#4178]
I have addressed a number of questions regarding this Waypoint over that past week. While I don't believe the wording of the instructions is to blame for all the confusion, perhaps some clarity could be added at the end to help users understand what needs to be done while also reinforcing the terminology.  Additions in bold, deleted text struck through.

> ## Properties Private
>Objects have their own attributes, called properties, and their own functions, called methods.
>
>In the previous challenge, we used the this keyword to reference public properties and public methods of the current object.
>
>We can also create private properties and private methods, which aren't accessible from outside the object.
>
>To do this, just declare properties or functions within the constructor **without the `this` keyword**.
>
>~~Let's create an object with two functions. One attached as a property and one not.~~
>
>~~See if you can keep myBike.speed and myBike.addUnit private, while making myBike.getSpeed publicly accessible.~~
>**See if you can modify the Bike constructor so that both the speed property and the addUnit method are private, while also making the getSpeed method publicly accessible for all objects created from the Bike constructor.  We'll check your work by testing the myBike object we've created from the Bike constructor at the bottom of the code.**

**Comment by awesomeaniruddh** [comment]
Hi @MattYamamoto, we already have an issue for this at https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4177.

Can you please post your suggestions on the other issue? This will ensure that they will get consideration when someone is working on fixing the issue.

Thanks!

**Comment by ysroels** [comment]
after countless attemps i got this to pass:
```javascript
 var gear = 0;

  this.setGear = function() {
    gear += 4;
  };

  this.getGear = function() {
    return gear;
  };
```
can someone please explain why / what happened??

**Comment by Sirius2016gy** [comment]
hmmmm... yeah I don't think I would be able to come up with that... at least now with the "+= 4;" *sigh*

**Comment by saifalizafar** [comment]
The isntructions are a bit vague. Here is my solution, knock yourself out :)
`var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Private var
  var gear;
// accessible from outside
  this.getGear = function(){
    return gear;
  };
  this.setGear = function(set){
    gear = set;
  };
};

var myCar = new Car();

var myBike = new Bike();`

**Comment by interglobalmedia** [comment]
The instructions for this exercise were very confusing. I got everything that you got, @saifalizafar except for the gear = set. I was trying to do something similar to get getGear to be equal to setGear, but no go. Will try this now.

**Comment by bklynate** [comment]
I come from a language where if you are initializing a variable it has to be to something, the entire notion of being able to accomplish "var gear;" and it automatically be set to undefined was foreign to me. Initially I did:

`var Bike = function() {

  // Only change code below this line.
  var gear = undefined;
  
  this.getGear = function() {
    return gear;
  };
  
  this.setGear = function(newGear) {
    gear = newGear;
  };
};`

Despite the FCC editor alerting me to the fact that I didnt have to set gear to undefined.

I later refactored my code to get "var gear" to clear the alert raised by the editor. Again, to me it hasnt really been mentioned that you can successfully initialize a var without setting to anything....coming from Ruby such a concept doesnt even exist I dont think. This is what lead to my confusions at least.

**Comment by friendofdog** [comment]
Anyone who has ever ridden a bike knows that you don't "set" a gear; you can only change gears relative to the gear that you're in. The below isn't accepted by FCC as a "correct" answer, but it makes more sense in the context of shifting gears on a bike.

`var Bike = function(gearInitial) {
	var gear = gearInitial;

	this.setGear = function(shiftGear) {
		gear += shiftGear;
	};

	this.getGear = function() {
		return gear;
	};
};`

So let's say I start in 3rd gear, shift up one gear, then shift down two gears. I'd then be in 2nd gear...

`var myBike = new Bike(3);

myBike.setGear(1);
myBike.setGear(-2);`

**Comment by interglobalmedia** [comment]
Thanks @friendofdog for the clarification. I will revisit.

**Comment by Galiante** [comment]
Hi...this is my solution...

var Bike = function() {
  // Only change code below this line.
  var gear;
  
   this.setGear = function(y) {
    gear = y;
  };
  
  this.getGear = function() {
    return gear;
  };
  
};

**Comment by theflametrooper** [comment]
@Galiante Please don't post solutions in here!

**Comment by Galiante** [comment]
Sorry @theflametrooper , I'll delete my post :smile:

**Comment by jrogodel** [comment]
#### Hi friends,
###### I stumbled upon some videos that helped me tremendously when I was stuck on this challenge. He breaks down the concepts revolving around this exercise: Constructor functions, closures, getters, setters, etc. Have fun!  and....
### Keep on hacking!
##### [Javascript Closures Part 1](http://youtu.be/6ltWzDKweUQ)
##### [Javascript Closures Part 2](https://www.youtube.com/watch?v=6ltWzDKweUQ)
---
___
![bitmoji](https://render.bitstrips.com/v2/cpanel/9940891-132598998_1-s1-v1.png?palette=1&width=246)

**Comment by theflametrooper** [comment]
@jrogodel Feel free to post these videos on our [Subreddit](https://www.reddit.com/r/FreeCodeCamp/)!

**Comment by profoundhub** [comment]
@jrogodel ... thanks for the links, but they are the SAME... here are the correct URLs: 

Video 1 =  https://www.youtube.com/watch?v=DZEblYanz3c
Video 2 = https://www.youtube.com/watch?v=6ltWzDKweUQ

**Comment by jamuhuri** [comment]
setGear() is just supposed to set the gear. You don't need to add new gear to the new values from set gear. all you need is x = y and not x+=y.

**Comment by Warstainer** [comment]
The code given above the challenge is rather confusing. I've never ridden a bike but I thought its just like (setting gear += set), as friendofdog mentioned. and if you var gear = 0 and then setGear(4) it will return four. "I made it! What the heck..."

**Comment by kumhr** [comment]
Finally :)

var Bike = function() {

  // Only change code below this line.
  var gear;
  
  this.setGear = function(change) {
    gear = change;
  };
  this.getGear = function() {
    return gear;
  };
};

**Comment by Anarchrist** [comment]
Hey.
Maybe this can clarify (I found this ultra confusing at first).

The hint is in the test credentials:
myBike.**get**Gear() should return 3 after calling myBike.**set**Gear(3)

1. So you create your object:

var Bike = function() { 

};

2. add your private variable:
var Bike = function() { 
 var gear;  
};

3. Now you need a function that will get the number passed to it from myBike.**set**Gear(3)

var Bike = function() { 
 var gear;

this.**setGear**= function(passedVar){
    gear = passedVar;
  };  

};

4. Finally you need to return the current gear (which is our private variable)

var Bike = function() { 
 var gear;

this.setGear= function(passedVar){
    gear = passedVar;
  };  

this.**get**Gear= function(){
    return gear;
  };

};

**Comment by juancbaires** [comment]
i did this and it works
 var gear = 0;
  this.setGear = function(shift) {
    gear = shift;
};
  this.getGear = function() {
    return gear;
};
  
};

**Comment by x19kutz** [comment]
// --- Spoiler --- //
::Solution ahead::

var Bike = function() {
    var gear = 0;
  this.setGear = function(change) {
    gear = change;
  };
  this.getGear = function() {
    return gear;
  };
};
So basically, setGear needs to set the value of the gear which is PRIVATE.
Hence we use setGear to set the value and getGear to simply return gear.

**Comment by texas2010** [comment]
@x19kutz 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by x19kutz** [comment]
@texas2010 Thank you for the update, wasn't aware of it! That was my first comment.

**Comment by texas2010** [comment]
@x19kutz, no problem.  all good.

**Comment by ricopella** [comment]
Thank you @jrogodel those videos did help

**Comment by Taylorbostick32** [comment]
I just finished this. Here is what i got. I hope it helps.

var Bike = function() {

  // Only change code below this line.
  var gear = 0;
  this.setGear = function(i) {
    gear = i;
  };
  this.getGear = function () {
    return gear;
  };
};

Whatever we put inside the parameters of setGear() becomes the value of gear, which getGear returns and holds that value as well.

**Comment by jaydev1997** [comment]
@Taylorbostick32  Please Don't post solution Here !
