### ISSUE TITLE
Remove Intro Markdown

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#41785]
As discussed here https://github.com/freeCodeCamp/freeCodeCamp/pull/41746#issuecomment-814856761 the .md files in `client/src/pages/learn` are in need of cleanup.  They're currently quite misleading, because all the intro text is now sourced from JSON files in `client/i18n/locales`, but we still source the .md files in `client/gatsby-node.js`.

Ideally the data they provide should be sourced from somewhere else so that we can remove the .md files entirely.  At first glance, the `client/i18n/locales/english/intro.json` should contain all the info we need.

**Comment by LaurentLabine** [comment]
I can look into this!

**Comment by jovicon** [comment]
Can I take this issue?

**Comment by LaurentLabine** [comment]
Yes go for it!

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by jovicon** [comment]
Thanks for the contributors docs @ShaunSHamilton. So, I'll work on this today and create a PR for review.

Thanks again for your help.

**Comment by moT01** [comment]
We have decided to keep these pages. Thanks and happy coding 🎉
