### ISSUE TITLE
Wrong text on "Standardize Times with the HTML5 datetime Attribute"

### ISSUE THREAD

**Issue by markosankovic** [freeCodeCamp/freeCodeCamp#41804]
The sidebar text on "Standardize Times with the HTML5 datetime Attribute" says "The datetime attribute is an inline element that can wrap a date or time on a page."

https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/standardize-times-with-the-html5-datetime-attribute

The attribute cannot be an inline element. Change it to: "The `time` element is an inline element that can wrap a date or time on a page. " or "The `time` is an inline element that can wrap a date or time on a page.".

![Screenshot from 2021-04-13 22-16-46](https://user-images.githubusercontent.com/102078/114615435-fd693700-9ca5-11eb-9c40-4a368826d0e8.png)

**Comment by jonathankerr** [comment]
Hey @markosankovic good spot there I'll sort this 👍
