### ISSUE TITLE
Remove comments in challenges?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#41803]
There has been some PR's to remove comments from a number of challenges recently. The general consensus seems to be to remove them when we can. This issue is for figuring out which ones we want to remove and which to leave it. Perhaps it's going to be a case by case basis and there won't be a blanket solution. One thing to maybe consider is to have some comments for the first few lessons in a new section and gradually have less as users start to get the hang of things.

More discussion:
https://github.com/freeCodeCamp/freeCodeCamp/pull/41778
https://github.com/freeCodeCamp/freeCodeCamp/pull/41612

**Comment by moT01** [comment]
In one of the links above, @emerconghaile mentioned that he intended to "go through all lessons in the Basic Javascript module in small chunks" (to remove comments) and that he "recently finished this module and noticed there was a varied consistency of what did or did not have comments". I would be fine if he made PR for that section as he sees fit. From there, we can see if there's too many removed or not enough.

**Comment by nhcarrigan** [comment]
I'm certainly a fan of removing more rather than less, since being able to read and understand existing code is an important skill.

**Comment by ShaunSHamilton** [comment]
Our main issue with the current layout is relying on existing seed code objects for tests. I am aware we have resolved some of these (I assume not all), by have a `--after-seed` object to test on, and/or by entirely removing the example object from the seed.

I am happy with whatever you decide on, but I do wonder how much more effort will go into these _cross-block_ changes, considering the challenges do work (99.9%), and we (not me) have already put in most of the necessary groundwork for i18n to work with the comments.

Out of interest, for v7, does the JS section also make use of the editable region?

**Comment by nhcarrigan** [comment]
> by have a --after-seed object to test on, and/or by entirely removing the example object from the seed.

This is probably a good approach for these challenges in question as well. 

> Out of interest, for v7, does the JS section also make use of the editable region?

Yes, though currently the editable region doesn't preclude changing other code.
