### ISSUE TITLE
Waypoint: Condense arrays with reduce - currentVal should be wrapped in code tags

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#4182]
In [Waypoint: Condense arrays with reduce](http://www.freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce), the variable `currentVal` in the third paragraph should be wrapped in code tags, just like in the second paragraph where it was initially mentioned.

![fcc-image](https://cloud.githubusercontent.com/assets/2754821/10960619/ee545eb0-8339-11e5-8a8c-66237adf03a5.png)

The line of code needed to be fixed is [here on line 228](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/3b04646dff1b973b5360f82728fa6a92184dbb60/seed/challenges/object-oriented-and-functional-programming.json#L228).

**Comment by SaintPeter** [comment]
I think 21 minutes is a decent turn-around for a fix.

**Comment by ltegman** [comment]
Sub 20 or bust! :stuck_out_tongue_winking_eye:

**Comment by SaintPeter** [comment]
@ltegman Well, I had it up in 16, took you long enough to merge it. ;)
