### ISSUE TITLE
Inconsistent styling of forum icon buttons 

### ISSUE THREAD

**Issue by sitek94** [freeCodeCamp/freeCodeCamp#41830]
**Describe the bug**
The following icon buttons of the of the `new topic` / `reply` dialog don't have their colors inverted on hover:
* `enter full screen composer`
* `minimize the composer panel`
* `toggle preview`

**To Reproduce**
1. Go to the forum: https://forum.freecodecamp.org/
2. Click on `+ New Topic` 
3. Hover over the icon buttons on the right

**Expected behavior**
I expect colors of the buttons to be inverted - so that I can see what button I'm hovering over.

**Screenshots**
Incorrect behaviour:
![enter-fullscreen-composer](https://user-images.githubusercontent.com/58401630/114824856-bd00da80-9dc5-11eb-89cd-48fe9fabfc19.png)
![minimize-the-composer-panel](https://user-images.githubusercontent.com/58401630/114824858-bd997100-9dc5-11eb-9e48-9ded59e97f0a.png)
![show-preview](https://user-images.githubusercontent.com/58401630/114824861-bd997100-9dc5-11eb-9d41-3fb44818004e.png)

Expected:
![create-topic](https://user-images.githubusercontent.com/58401630/114824849-bb371700-9dc5-11eb-8cff-ccaca0678e1e.png)

**Comment by sitek94** [comment]
If someone will confirm that it is actually a bug, I'd be happy to fix that as my first contribution :)

**Comment by ahmadabdolsaheb** [comment]
I see, this is a bug. the icon color should be inverted. 
Please make selector as specific as possible to avoid unwanted changes in other areas of the UI.
Our theme repo is here: https://github.com/freeCodeCamp/forum-theme/
And you could test your changes using theme creator: https://meta.discourse.org/t/beginners-guide-to-using-theme-creator-and-theme-cli-to-start-building-a-discourse-theme/108444


Best of luck and let me know if you need further assistance.

**Comment by sitek94** [comment]
Okay, thanks for the tips, I'll get on with it then :)

**Comment by sitek94** [comment]
I've found a way to invert the colors: 

<p float="left">
  <img src="https://user-images.githubusercontent.com/58401630/115113132-fa619580-9f88-11eb-8e82-354f440678c2.gif" />
  <img src="https://user-images.githubusercontent.com/58401630/115113129-f6ce0e80-9f88-11eb-910b-db967bff183b.gif" />
  <img src="https://user-images.githubusercontent.com/58401630/115113130-f897d200-9f88-11eb-8c2c-90eb3d2adac1.gif" />
  <img src="https://user-images.githubusercontent.com/58401630/115113131-f9c8ff00-9f88-11eb-808a-c20bcbd2fa09.gif" />
</p>

Do you think the following selector will be specific enough? 

```scss
#reply-control .btn-mini-toggle:hover {
  .d-icon {
    color: $secondary;
  }
}
```

If so, I should send a PR to the theme repo, right? :)

**Comment by Sembauke** [comment]
Hey @sitek94, 

Please do open a PR so we can look at your solution. 
If changes are needed we can discuss them there.

**Comment by ahmadabdolsaheb** [comment]
@sitek94, Yes and yes :)
Also feel free to audit the rest of the theme for similar inconsistencies.

**Comment by raisedadead** [comment]
We have enabled the `/styleguide` path on the forum for you all to debug things better. It's available here: https://forum.freecodecamp.org/styleguide
