### ISSUE TITLE
Minor typo on CSS inline style lesson

### ISSUE THREAD

**Issue by geochronology** [freeCodeCamp/freeCodeCamp#41846]
**Describe your problem and how to reproduce it:**
There is a minor typo on the lesson for CSS inline styles as part of the Responsive Web Design curriculum.  

The challenge part of the lesson reads as follows:
`"Use an inline style to try to make our h1 element white. Remember, in line styles look like this:"`

The second instance of inline is here written as “in line” which is incorrect.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/override-class-declarations-with-inline-styles

**Tell us about your browser and operating system:**
Not relevant (though FWIW, Firefox Developer Edition on MacOS Big Sur)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="920" alt="Screen Shot 2021-04-17 at 12 24 03 PM" src="https://user-images.githubusercontent.com/54387644/115124578-cf227a80-9f77-11eb-9da3-e973817ba83a.png">

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this.

This is a simple issue. So, I have opened it up to first timers.

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Dzheky** [comment]
Can I work on this as my first code contribution to FCC?
