### ISSUE TITLE
Missing Letters - Test Shortfall 

### ISSUE THREAD

**Issue by jschref** [freeCodeCamp/freeCodeCamp#41843]
**Describe your problem and how to reproduce it:**
There is a missing test case in the "JavaScript Intermediate Algorithm Scripting - Missing Letters" challenge. The only test case which does not contain a missing letter, is one which contains the entire alphabet. This makes it possible to pass the challenge while having a string which is not missing any letters, but contains less than the entire alphabet. 

When researching how to report this, I discovered I'm also not the first to catch this. (see below) However I couldn't find a ticket on the subject, open or closed. I attached a few images showing code which will pass and shouldn't as well as a "correct" solution. I hope this helps. :) 
![Missing Letters - correct solution](https://user-images.githubusercontent.com/80697816/115061052-a38b8b80-9eb6-11eb-9b40-8f3b2d0c40dd.png)
![Missing Letters - incorrect solution which passes](https://user-images.githubusercontent.com/80697816/115061053-a4242200-9eb6-11eb-9363-f0fb6542215a.png)

https://forum.freecodecamp.org/t/missing-letters-missing-test-case-spoiler/254140

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/missing-letters

**Tell us about your browser and operating system:**
* Browser Name: NA
* Browser Version: NA
* Operating System: NA

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by jonathankerr** [comment]
Hey @jschref this has already been reported and was deemed to be a non-issue. Reference here: https://github.com/freeCodeCamp/freeCodeCamp/issues/34958

In the future please check if the same issue has already been opened, especially in this case as the the OP of the forum you've linked mentioned he had created an issue for this.

**Comment by Sembauke** [comment]
I think @jonathankerr is correct here.

As quoted by Randell Dawson:

> In JavaScript, if a function does not explicitly return a value, it returns undefined by default, so your function would still return undefined if the test case of fearNotLetter("bcdef") were to be added (which is not necessary).

(Or Any other value that is alphabetically correct)

I am closing this issue for this reason.
