### ISSUE TITLE
Typo in Data Analysis - Medical Data Visualizer

### ISSUE THREAD

**Issue by SparksCode** [freeCodeCamp/freeCodeCamp#41841]
**Describe your problem and how to reproduce it:**
In the below comment, 'cholestorol' should be spelt 'cholesterol'

Normalize data by making 0 always good and 1 always bad. If the value of 'cholestorol' or 'gluc' is 1, make the value 0. If the value is more than 1, make the value 1.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/blob/master/medical_data_visualizer.py

**Comment by Sembauke** [comment]
Hey @SparksCode,

Thank you for making an issue on this. This should be pretty easy to fix so I am adding the first timers only label.

**Comment by EKaxada** [comment]
Can I take this up @Sembauke

**Comment by Sembauke** [comment]
> Can I take this up @Sembauke

Happy to see you want to contribute to the repository. But this issue is only available for people that haven't contributed before (because it has the first timers only label). You can contribute to any issue with the "[help wanted](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)" label.

**Comment by EKaxada** [comment]
Ohh. Thank you. I didn't know "first timers only" really meant that literally

**Comment by Hypermona** [comment]
> Hey @SparksCode,
> 
> Thank you for making an issue on this. This should be pretty easy to fix so I am adding the first timers only label.

I would like to contribute can you guide me

**Comment by Sembauke** [comment]
> I would like to contribute can you guide me

Hey, @Hypermona we have a pretty good [documentation](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges) that can guide you through this.
If you need any additional help. Let me know.

**Comment by Hypermona** [comment]
> > I would like to contribute can you guide me
> 
> Hey, @Hypermona we have a pretty good [documentation](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges) that can guide you through this.
> If you need any additional help. Let me know.

I have committed the 2 changes

**Comment by Sembauke** [comment]
> I have committed the 2 changes

Great now you can open a pull request so we can review your contribution.

**Comment by Hypermona** [comment]
> > I have committed the 2 changes
> 
> Great now you can open a pull request so we can review your contribution.

https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/pull/10#issue-617098650
