### ISSUE TITLE
the Run Test button does not led to the next step its inactive. I have tried refreshing and also used a different browser. Please help

### ISSUE THREAD

**Issue by Amanuel1D** [FreeCodeCamp/FreeCodeCamp#4186]
Challenge [Waypoint: Learn how Script Tags and Document Ready Work](http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work#?solution=fccss%0A%20%20%24(document).ready(function()%7B%0A%20%20%7D)%3Bfcces%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22b

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps and a description on how to reproduce the issue.

Happy Coding!

**Comment by Tirjasdyn** [comment]
I am having this same  problem. I add the following code to line one:

<script>
  $(document).ready(function() {
    
  });
</script>

Then I click Run tests. 
The steps disappear and the next challenge does not come up.

**Comment by SaintPeter** [comment]
@Tirjasdyn I don't see any code in your message.  

I encourage you to take your code to the [Help Room](https://gitter.im/FreeCodeCamp/Help) to seek out an answer there before you post an issue.  There is a good chance there is a simple syntax or logic error causing your code not to run.

**Comment by Tirjasdyn** [comment]
Okay let my try again:

<script>$(document).ready(function() {});</script>

Then when I click Run Test, the steps disappear and nothing else happens. This also happens after I reset the window and if I put no new code in.

**Comment by Tirjasdyn** [comment]
```<script>$(document).ready(function() {});</script>
```

**Comment by Tirjasdyn** [comment]
So the code won't show. It does't matter the same error occurs with no new code entered. Just hit Run test and the same thing happens.

**Comment by SaintPeter** [comment]
@Tirjasdyn Have you checked your code with the folks in the help room first?

Also, use the "Bug" button to submit a new issue and it will copy your code for you.
