### ISSUE TITLE
Back-button targets preview-page in coding challenge

### ISSUE THREAD

**Issue by Glitchy-Tozier** [freeCodeCamp/freeCodeCamp#41865]
**Describe your problem and how to reproduce it:**
1. Go [here](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element).
2. Create the requested form.
3. Enter something in that text field and press enter.
4. A `Thank you!`-page appears in the preview section. **(see first screenshot)**

Everything is great up until now. Here comes the problem.

5. The user can now press BACK in the browser (or on the Mouse or via a keyboard shortcut). This, however doesn't go to the previous full page. Instead, it messes up the preview panel. **(see second screenshot)**
6. The user can then repeat steps 1-6 as often as he wants. It's kind of janky and doesn't seem like it should exist. **(see third screenshot)**

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 88.0 (64bit)
* Operating System: Linux (Mint)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![freeWeirdCodeBehaviour0](https://user-images.githubusercontent.com/59611881/115370190-1bb0c480-a1c9-11eb-9d87-510704c751ac.png)

![freeWeirdCodeBehaviour1](https://user-images.githubusercontent.com/59611881/115371026-ed7fb480-a1c9-11eb-9d5a-916517d06e0b.png)

![freeWeirdCodeBehaviour2](https://user-images.githubusercontent.com/59611881/115371055-f1abd200-a1c9-11eb-8cf6-bebee98e8fad.png)

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this. To be honest, I am not sure why/how you managed to stumble upon this bug. It is quite funny.

I believe there is an `iframe` attribute we can attach which would resolve this behaviour, but I forget which one. _will edit this, once I find it_

**Comment by Glitchy-Tozier** [comment]
1. Yeah, it's pretty funny!
2. Not sure how i discovered this, maybe I just wanted to go back to the previous challenge...
3. Thank you for the video, I'll watch it as soon as possible.

By the way, I haven't advanced very far in the curriculum, but i suspect that this is reproducible in other challenges with input fields.

**Comment by Sembauke** [comment]
Hey @ShaunSHamilton ,

After struggling to solve this issue with attributes the iframe provides, I made an example project that seems to work as it should. 
https://intrepidgiddyinfo.semboot699.repl.co/

So my conclusion here is that it may not be the iframes fault but somewhere else in the code.

**Comment by Nirajn2311** [comment]
Shouldn't this PR #35180 have blocked the submission of forms in iframes itself.

**Comment by Glitchy-Tozier** [comment]
@Nirajn2311 I don't know the answer to your question but that sounds like a horrible thing to do.

As a student, seeing my form actually do something made me very happy.

**Comment by Sembauke** [comment]
Looks like someone already did something to prevent this on anchor tags

```
// base tag here will force relative links
// within iframe to point to '' instead of
// append to the current challenge url
// this also allows in-page anchors to work properly
// rather than load another instance of the learn
```

**Comment by Sembauke** [comment]
We can always open a new tab instead of in the iframe.

**Comment by Glitchy-Tozier** [comment]
@Sembauke Either this, or prevent the bug and add a back-button to the "Form Submitted"-page.

**Comment by Nirajn2311** [comment]
Opening a new tab can be an alternative but imagine if a user is playing and suddenly a new tab opens, it feels jarry and may confuse them. I feel it's better if we loaded it in the iframe itself.

**Comment by ojeytonwilliams** [comment]
> As a student, seeing my form actually do something made me very happy.

I think this is crucial.  Whatever we go with, we shouldn't lose this part of the current behaviour.

> Opening a new tab can be an alternative but imagine if a user is playing around with what they coded and suddenly a new tab opens, it feels jarry and may confuse them. I feel it's better if we loaded it in the iframe itself.

Agreed.  I think opening in the preview frame is a nice UX.  It should feel like that's the page they're creating and suddenly having that page spawn a new tab breaks that feeling.

**Comment by moT01** [comment]
If anyone thinks this needs to fixed, feel free to leave a comment and we can reopen it. Thanks and happy coding 🎉
