### ISSUE TITLE
Link in challenge doesn't respect `target="_blank"`

### ISSUE THREAD

**Issue by Glitchy-Tozier** [freeCodeCamp/freeCodeCamp#41861]
**Describe your problem and how to reproduce it:**
In the **Nest an Anchor Element within a Paragraph**-challenge, in the description there's an example text+link. It is explicitly said that there's a `target="_blank"` attribute being used.
However, at the bottom of the example, the link after `"The final output of the example will look like this:"` doesn't take you to a new tab. This seems wrong to me.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 88.0 (64-bit)
* Operating System: Linux

**Comment by Glitchy-Tozier** [comment]
Should I just do another pull request?

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this.

Yes, this was _semi_-recently changed: https://github.com/freeCodeCamp/freeCodeCamp/pull/39800/files?file-filters%5B%5D=.markdown&file-filters%5B%5D=.md#diff-fac8c38218acdea5469da1593050f2586b7cbdaee567fba221a2e1637420f5da

There does not appear to be any necessary reason to stick with Markdown, in this case. As this is such a simple fix, I am inclined to open it to first-timers.

TODO: Change link in description to HTML with `target='_blank'`

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by sa-ritesh** [comment]
Hello sir, 
I am a first-time contributor, can you please help me by telling me how can I set this up in my local machine.
I had already cloned and installed the necessary packages but still could not run it.
