### ISSUE TITLE
HTML-challenges: links are inconsistent.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [freeCodeCamp/freeCodeCamp#41886]
**Describe your problem and how to reproduce it:**
About **19** of the HTML lessons contain links, either in the html-code or in the description&instructions.

**16** of them use short links. (for example `freecodecamp.org`)
**2** of them use long links. (for example `www.freecodecamp.org`)
**1** uses a mixture of both.

I suggest using one style for all challenges.
Personally, I'm in favor of the shorter variant, as it's easier to read for new students.

**Add a Link to the page with the problem:**
This originated here: https://github.com/freeCodeCamp/freeCodeCamp/pull/41876#issuecomment-824105202

**Links to challenges:**
`thisisalink.com`
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/make-dead-links-using-the-hash-symbol
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/turn-an-image-into-a-link
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-an-ordered-list
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-text-field
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-placeholder-text-to-a-text-field
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-a-submit-button-to-a-form
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/use-html5-to-require-a-field
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-set-of-checkboxes
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/use-the-value-attribute-with-radio-buttons-and-checkboxes
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/check-radio-buttons-and-checkboxes-by-default
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-many-elements-within-a-single-div-element

`www.thisisalink.com`
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements
1. https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

Mixture of both:
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 88.0 (64-bit)
* Operating System: Linux

**Comment by raisedadead** [comment]
Thanks for reporting, I think we should swap them all for the `www` version. Will you be interested in taking credit by making a PR?

**Comment by Glitchy-Tozier** [comment]
Unfortunately, my time and energy are very limited during the next weeks, so i won't be able to make a PR.  :/

**Comment by raisedadead** [comment]
No worries. Your help compiling the list is much appreciated.

--

Hi Contributors.

This looks something that can be fixed by "first time" code contributors to this repository. 

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides.

Here is how you should approach this issue:

1. Look up the challenges in the list in the OP in your editor.
2. Replace the links like so: `freecodecamp.org` to `www.freecodecamp.org`
3. Please be careful that you are changing only the list in the OP. 
4. Please be careful that you are changing files in [`curriculum/challenges/english`](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english) - and not the translations.

Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull-requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by EboranBokaj** [comment]
Hi, I hope everything is as it should be. This is my first PR so if there is anything I need to change please let me know, I appreciate the feedback. Thanks!

**Comment by Jaspreet099** [comment]
can I work on this issue ?

**Comment by ojeytonwilliams** [comment]
Hi @Jaspreet099, please do.  This issue is open to people who haven't previously contributed to this repository.

**Comment by Glitchy-Tozier** [comment]
@Jaspreet099 @ojeytonwilliams Uhhh, isn't there already someone working on this? (#41900)

**Comment by WalidMoua** [comment]
Hi @raisedadead  can i work on this issue?

**Comment by gmfuster** [comment]
Sorry for the question.  I saw somebody asked if they could take it.  I guess, if when we fetch the code it has been changed, we know it's already done, and if not, then we can send a PR and you may end up getting multiple ones but you will take one and disregard the other ones?

**Comment by raisedadead** [comment]
Hi @Jaspreet099 @WalidMoua and @gmfuster we thank you for your interest in contributing to the codebase. We understand we may not have enough first-timer only issues for you to work on, however we always have a lot of things that you can help us with. 

I encourage you to look at some the issues that are labeled help-wanted. These may not be trivial but we trust that with some help from the folks in our contributing chat you should be able to kickstart your contributing journey.

Also do not forget to read our [contributing guidelines](https://contribute.freecodecamp.org), they have all the information you need to get started.

Cheers & happy contributing
