### ISSUE TITLE
Safari(v14.0.3) Menu & Sign In Missing from Navbar

### ISSUE THREAD

**Issue by dsuttler** [freeCodeCamp/freeCodeCamp#41884]
**Describe the bug**
When navigating to the home page, the Menu and Sign In buttons in the top right corner are missing. Can not sign in to profile.

**To Reproduce**
1. Go to 'freecodecamp.org'
2. Try to locate Menu & Sign In
3. See error: Missing Menu and Sign In buttons on top navbar.

**Expected behavior**
- Expected to be able to sign in and continue coursework or see profile.

**Screenshots**
![Screen Shot 2021-04-21 at 9 31 22 PM](https://user-images.githubusercontent.com/35442488/115642503-134fab00-a2e9-11eb-9f73-f4d597b37741.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur v =11.2.3
 - Browser:Safari v14.0.3

**Additional context**
I haven't actually helped on any open source project yet. I'm pretty new, but in my senior year of CS degree. I would love to work on this issue.

**Comment by ojeytonwilliams** [comment]
@moT01 could you check this out on Safari?

> I haven't actually helped on any open source project yet. I'm pretty new, but in my senior year of CS degree. I would love to work on this issue.

First off, thanks for letting us know about the problem!  And, yes, you're very welcome to work on this issue.  If you haven't already taken a look, it's worth reading our [guide](https://contribute.freecodecamp.org/#/index?id=our-open-source-codebase) to contributing to freeCodeCamp.

**Comment by ahmadabdolsaheb** [comment]
I get a loader on /learn's navigation and the page itself. it seems like near 8% of users are affected. 
How long have you been experiencing this issue?

@ojeytonwilliams, should we have a script that detect the browser and shows a flash accordingly? "For a better experience ...

<img width="1438" alt="Screen Shot 2021-04-22 at 11 03 40 AM" src="https://user-images.githubusercontent.com/4591597/115679026-d0c6b680-a35a-11eb-9f34-b81034d2dfba.png">

**Comment by ojeytonwilliams** [comment]
> and shows a flash accordingly?

Sure, what did you have in mind?

**Comment by Nirajn2311** [comment]
Adding in a small detail, the same issue is on iOS devices also and in any browser on the phone.

**Comment by ShaunSHamilton** [comment]
Hey all, this is likely my fault with: https://github.com/freeCodeCamp/freeCodeCamp/pull/41858

I used a lookbehind in the regex, which I believe Safari does not support:
![image](https://user-images.githubusercontent.com/51722130/115705783-d923ef00-a364-11eb-9a86-72ab251ed53a.png)

**Comment by Sembauke** [comment]
You can open a PR and see if it fixes it. @ShaunSHamilton
