### ISSUE TITLE
Broken Test Case [Responsive Web Design - Basic CSS - Import a Google Font]

### ISSUE THREAD

**Issue by KL13NT** [freeCodeCamp/freeCodeCamp#41905]
**Affected page**
[Responsive Web Design - Basic CSS - Import a Google Font](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/import-a-google-font)

**Your code**

```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: monospace;
  }

  h2 {
    font-family : Lobster; // REPORTED BUG
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>

  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>

  <form action="https://freecatphotoapp.com/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Expected behavior**
Should pass all test cases 100%, but instead fails on the third test case "You should only use an h2 element selector to change the font". 

**System (please complete the following information):**
 - Device: Laptop
 - OS: Windows 8.1 Pro Latest Update
 - Browser: Firefox, Chrome, Opera
 - Version: Latest All

**Additional context**
The bug exists at the rule declaration colon where adding a space breaks the test fixtures. The following piece of CSS doesn't pass the tests, despite being valid and correct:

```css
h2 {
    font-family : Lobster; // Extra space before colon
  }
```

While the following passes: 

```css
h2 {
    font-family: Lobster; // Removed space before colon
  }
```

Per the W3C Syntax and basic data types documentation, the `declaration : property S* ':' S* value;` regex is used to verify CSS rule declarations. I'd like to work on a fix for this if this will be fixed.

**Comment by moT01** [comment]
The [test is here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-css/import-a-google-font.md#--hints--). The regex doesn't allow spaces there. 
`/\s*[^\.]h2\s*\{\s*font-family\s*:\s*(['"]?)Lobster\1\s*(;\s*\}|\})` should work

**Comment by KL13NT** [comment]
@moT01 Okay so, there's more than just that. I mentor a student based on the freeCodeCamp curriculum and a few of this bug have turned up so far. What is the Regex flavor? I tried running the Regex you provided in the fix using JavaScript and it fails.

**Comment by KL13NT** [comment]
Should I open another issue that's more general and mention this or continue in this one?

**Comment by moT01** [comment]
Is there still an issue of concern here @KL13NT?

**Comment by KL13NT** [comment]
There's a number of other lessons that suffer the same Regex bug, yes. @moT01

**Comment by Sembauke** [comment]
> There's a number of other lessons that suffer the same Regex bug, yes. @moT01

Hey @KL13NT , I suggest you open a new issue with a list of the affected challenges if you are up to the task.

**Comment by KL13NT** [comment]
Sure thing.
