### ISSUE TITLE
Unify assets to cdn.freecodecamp.org

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#41913]
We should unify static assets to use the `cdn.freecodecamp.org` CDN. The CDN repo is here: https://github.com/freeCodeCamp/cdn

#### List of assets not using cdn.freecodecamp.org

Edit: all the below projects have been updated.

<s>
### Build a Tribute Page:

https://codepen.io/freeCodeCamp/pen/zNqgVx

The image is on flickr. Needs to be moved to CDN and have the Codepen updated.

`https://c2.staticflickr.com/4/3689/10613180113_fdf7bcd316_b.jpg`

### Build a Product Landing Page:

https://codepen.io/freeCodeCamp/pen/RKRbwL

The logo image is on AWS. Needs to be moved to CDN and have the Codepen updated.

`https://s3.amazonaws.com/freecodecamp/original_trombones.png`

### Build a Personal Portfolio Webpage:

https://codepen.io/freeCodeCamp/pen/zNBOYG

Is using `raw.githubusercontent.com`. The images are already in the CDN repo but the Codepen needs to be updated to use `cdn.freecodecamp.org` instead.
</s>

---

If anyone knows of other assets that should be added to the list please post them here.

**Comment by raisedadead** [comment]
The images can be added to the `build` folder by creating a new subdirectory with the name `codepen`. 

```
build
|-- ...
|-- codepen 
     | -- image-name.jpg
    
```


This will make it automatically available at the path `https://cdn.freecodecamp.org/codepen/image-name.jpg`

Will you be interested in making a PR?

**Comment by lasjorg** [comment]
@raisedadead Right now we are using `testable-projects-fcc/images` for the example projects. That folder has the images used in the Personal Portfolio and Survey Form projects.

Do you want me to move them to a new `codepen` folder in the `build` folder along with the other images?

Or do we just keep using the `testable-projects-fcc/images` folder? It might be nice to keep all the "testable projects" assets inside a common folder. So maybe we should just keep them where they are now?

**Comment by lasjorg** [comment]
@raisedadead I think I should just upload the images to the folder we are using now. That way we do not have to update all the projects to use a different file path.

1. I will make a PR on the CDN repo (see *note).

2. Make a PR on the testable-projects-fcc repo to update the projects.

3. Have someone with access to the fCC Codepen update the relevant projects.

*There is an issue with the CDN repo and Windows. I commented on the relevant PR https://github.com/freeCodeCamp/cdn/pull/53 in hopes that it can get fixed. Otherwise I will have to just use the GitHub interface for the file uploads.

**Comment by raisedadead** [comment]
Sorry for the delay in getting back to you. 

Yes - there is no requirement with the CDN for duplication. It's perfectly OK to have duplicated content if we want. The goal is to keep the images categorized hopefully for identifying the use.

However, I can see its best to use the current images folder for now. That will have least impact or changes elsewhere.

As for the issue with repo and Windows, sorry about the inconvenience. Could you try using GitPod to clone and rename the files? IMHO, all the files that have spaces should be kabab cased as well.

You can add all changes into the same PR if you wish.

**Comment by lasjorg** [comment]
> Could you try using GitPod or WSL Setup to clone and rename the files? IMHO, all the files that have spaces should be kabab cased as well.

I can, but I would assume the files are used somewhere (I don't know where). If they are, it might be better to wait until we are sure the usage will be corrected so we do not break anything.

I will try using Gitpod for the image uploads.

**Comment by raisedadead** [comment]
> I can, but I would assume the files are used somewhere (I don't know where). If they are, it might be better to wait until we are sure the usage will be corrected so we do not break anything.

I will get that verified with the team. Meanwhile thanks for your understanding and using the workaround for this particular issue.

**Comment by lasjorg** [comment]
I created the PR: https://github.com/freeCodeCamp/cdn/pull/65

It took a little longer than expected as I had to add some environment variables to GitPod for it to work with GitHub private emails. I will post a link to the GitPod issue https://github.com/gitpod-io/gitpod/issues/387 with the info just in case anyone else needs it.

**Comment by raisedadead** [comment]
@lasjorg I have given Beau an heads up that we are going to be renaming the files under the `youtube` directory. You can proceed with a PR for the same. We would want all files to have kebab case.

**Comment by lasjorg** [comment]
I have updated the initial post to reflect the updates done.

I will keep this issue open for now just in case anyone finds other assets that need to be updated. Just so we can keep a list of them here.

**Comment by moT01** [comment]
I think it's safe to close this at this point. Feel free to leave a comment if any more are found 🌮
