### ISSUE TITLE
Requirements or description are wrong.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [freeCodeCamp/freeCodeCamp#41916]
**Affected page**
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images

**Your code**
```html
<style>
  .red-text {
    color: red;
  }

  img {
    height:100px;
  }

  h2 {
    font-family: Lobster, monospace;
  }

  p {
    font-size: 16px;
    font-family: monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>

  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
```

**Expected behavior**
I set the height instead of the width to 100px. As the image is a perfect square, this also changes the width. 
Therefore, this code should either pass the challenge or the passing-requirements should be adjusted.

**Screenshots**
![image](https://user-images.githubusercontent.com/59611881/115950699-1dd29600-a4dd-11eb-8953-5b830436909f.png)

![image](https://user-images.githubusercontent.com/59611881/115950720-3e025500-a4dd-11eb-8dcb-89ec42dccf88.png)

![image](https://user-images.githubusercontent.com/59611881/115950668-faa7e680-a4dc-11eb-8701-a7889abc0af2.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 88.0

**Additional Thoughts:**
In the next challenge, there's this comment:
`Note: This challenge allows for multiple possible solutions. For example, you may add border-radius to either the .thick-green-border class or the .smaller-image class.`

We could add the same thing in this challenge.

**Comment by Sembauke** [comment]
Hey @Glitchy-Tozier,

I see what you mean, but the challenge asks specifically to change the width to 100px. 
People won't set the height to 100px. 

therefore I am closing this issue.

**Comment by Glitchy-Tozier** [comment]
@Sembauke  Those requirements don't tell you the correct instructions though.
![Screenshot_20210424-112605_GitHub.jpg](https://user-images.githubusercontent.com/59611881/115954212-fb964380-a4ef-11eb-9600-5f39a135593e.jpg)

(I mean it IS 100px wide)

**Comment by ShaunSHamilton** [comment]
Hello there,

@Glitchy-Tozier As Sem mentioned, the whole point of the lesson is to introduce the `width` property, and it is made clear through the description, example code, and instructions:
> CSS has a property called width that controls an element's width.
> `width: 500px;`
> 100 pixels wide.

As this is not an issue coming up on the forums, and the lessons are meant to be kept plain, and this version of the curriculum is changing, I do not see a need for anything to be done here.

**Comment by Sembauke** [comment]
Sorry, @Glitchy-Tozier  I might not have been clear enough!
