### ISSUE TITLE
Broken Test Case Regex

### ISSUE THREAD

**Issue by KL13NT** [freeCodeCamp/freeCodeCamp#41921]
This issue is an extension of #41905. Multiple challenges suffer the same regex incorrectness in CSS challenges. This is a list of affected challenges: 
- [ ] [Specify How Fonts Should Degrade](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/specify-how-fonts-should-degrade)
- [ ] [Size Your Images](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images)
- [ ] [Use Abbreviated Hex Code](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-abbreviated-hex-code)
- [ ] [Use RGB to Mix Colors](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-rgb-to-mix-colors)
- [ ] [ES6 Template Literals](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals)

**Expected behavior**
Test cases should pass, but the regex incorrectness in handling spaces prevents it from passing. 

**System (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: Chrome, Firefox
 - Version: Latest

**Additional context**
Refer to #41905 for more info. I can work on this.

**Comment by gkhedekar5758** [comment]
are this still open? or these are resolved?

**Comment by Sembauke** [comment]
> are this still open? or these are resolved?

Hey @gkhedekar5758 ,

You can still solve this issue!

**Comment by Ismailtlem** [comment]
What's the issue in this challenge as an example https://www.freecodecamp.org/learn/responsive-web-design/basic-css/size-your-images ?

**Comment by KL13NT** [comment]
@Ismailtlem The following solution works:

```html
<img src="https://bit.ly/fcc-relaxing-cat" class="smaller-image"></a>
```

while this doesn't:

```html
<img src="https://bit.ly/fcc-relaxing-cat" class=" smaller-image ">
```

Note the difference in spacing between `class="smaller-image"` and `class=" smaller-image "`.

**Comment by SethFalco** [comment]
I can see the CSS issue was already described in #41905.
Is it worth fixing this everywhere now, or might it be better to wait for the CSS parser? (#41942)

With the HTML issues, the flaw is that we're not trimming the attribute. Whitespaces should be allowed before and after the list of classes.

> A set of space-separated tokens is a string containing zero or more words (known as tokens) separated by one or more ASCII whitespace, where words consist of any string of one or more characters, none of which are ASCII whitespace.
> 
> A string containing a set of space-separated tokens may have leading or trailing ASCII whitespace.
> \- https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#set-of-space-separated-tokens

Alternatively, it could be worth changing the logic to `split` by `/\s*/` and check if the array `includes` the target class. Technically, we only care if they added `smaller-image`. Does it matter if users decided to add other classes too?

I'm not sure what's wrong with "ES6 Template Literals", though. I don't see any obvious problems, has this been elaborated anywhere?

**Comment by KL13NT** [comment]
@SethFalco 

> Is it worth fixing this everywhere now, or might it be better to wait for the CSS parser? (#41942)

I think a parser would most definitely fix all of the related CSS bugs, but until the parser lands in production some users will still face issues with these challenges. If freeCodeCamp use some analytics for tasks passes/fails a more elaborate solution would be available. Right now, I have no idea about the the number of users who face this bug. 

> Alternatively, it could be worth changing the logic to split by /\s*/ and check if the array includes the target class. Technically, we only care if they added smaller-image. Does it matter if users decided to add other classes too?

Would it even be possible? All I know is each challenge has a regex for each test and only that?

> I'm not sure what's wrong with "ES6 Template Literals", though. I don't see any obvious problems, has this been elaborated anywhere?

I'll double-check it and update the issue.

**Comment by KL13NT** [comment]
Also, freeCodeCamp could use an HTML parser like [hast](https://github.com/syntax-tree/hast) to parse HTML into an AST, a parser for CSS, and parser for JS if needed. Then all you'd need is traverse the AST to search for a test expected value. I don't know what the security/performance implications of this idea, but it'd completely remove the need for regex.

**Comment by SethFalco** [comment]
> Would it even be possible?

Yup, the tests are JavaScript, not just a regex. It's just a lot of them use regular expressions is all.
The tests are the `--hint--` sections of each document. ([Example](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-css/size-your-images.md#--hints--))

> \# --hints--
> 
> Tests to run against user code, in pairs of markdown text and code block test code.
> \- https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=challenge-template

I've already addressed the CSS/HTML issues, we'll see what others think.

Regarding "ES6 Template Literals", I'd like to wait for other opinions.
I'm not sure if the output should be treated and tested like a string literal or HTML for this challenge.

**Comment by moT01** [comment]
I don't think we need to worry about the template literals lesson. In other cases, I would like to allow spaces in those places, but this particular one specifies the exact output expected - So I think we would be fine to leave it.

**Comment by alirezaghey** [comment]
Hi,
I've created some amendments for all the pages except [ES6 Template Literals](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals).
In the ES6 template literals' case, considering that the exact output is specified, I also don't think that allowing optional spaces would make much sense.
