### ISSUE TITLE
editor help?

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4193]
I have a habit of using [CTRL D] when I want to duplicate a line.  Deletes a line in your app.  Your editor uses CodeMirror, so am I assuming correct you left it at the [key defautls](https://codemirror.net/doc/manual.html#commands)?

If so, where should the info/link go for students to find?

**Comment by SaintPeter** [comment]
What action do you propose here?

New users are unlikely to use these keybindings.  While we could potentially add a `?` in the corner or something, the return seems low.

**Comment by tomByrer** [comment]
Well, all the commands are on the CodeMirror site, no need to do anything more than linking.
The first places I looked were the WiKi (which is locked, so I had to request) & the Gitter bot.  A link at one or both should suffice for those who look.  I guess a corner (?) button or [F1] help would be nice, but yes extra work might not be worth it for now.

**Comment by tomByrer** [comment]
Please keep in mind, though most of your focus have been on newbies to HTML/CSS/JS, I think you'll attract ether non-beginners like me who want the certificate & internship experience, or advanced users who will want to learn new tech.  Eg: I see your D3 & React lessons in progress; which will definitely attract experienced coders.  They'll all hope for short cuts & other conveniences, since they use them constantly.

**Comment by SaintPeter** [comment]
Fair enough.  I think it's reasonable to have a link to editor info.  I'll capture this as a feature request.

**Comment by tomByrer** [comment]
Thinking about this more, best to add to Wiki &/or bot.  I agree too much work for editor GUI; unless there is more people looking for it.
