### ISSUE TITLE
Streak broke

### ISSUE THREAD

**Issue by MKhasib** [freeCodeCamp/freeCodeCamp#41937]
The following two problems occured for the javascript course
I was going for a full month streak on freecodecamp and I was surprised that my submitted solution)one solution) yesterday was removed for some reason and when I came back today I saw that the question is not marked as solved even though I submitted it yesterday and passed!
The second issue that I solve ordered questions(same order as freecodecamp curriculum) but one of the questions that I solved two days ago was marked as not solved as well!

**Affected page**
Add a Link to the page with the problem.
https://www.freecodecamp.org/mkhasib

**Expected behavior**
I was expected for the results to be saved not to be lost and the streak to break

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

![image](https://user-images.githubusercontent.com/57562096/116399025-2276b180-a831-11eb-8cbc-c46257e3e130.png)

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by raisedadead** [comment]
Thanks for reporting.

Do you mind emailing us at `support@freecodecamp.org` from your registered email as well while we look into this? You do not need to add too many details other than a link to this issue for now.

**Comment by raisedadead** [comment]
Hey @scissorsneedfoodtoo could you let us know how this went, is this a bug on ourside?

**Comment by MKhasib** [comment]
> Hey @scissorsneedfoodtoo could you let us know how this went, is this a bug on ourside?
I don't know why the problem happened but I broke the streak yesterday(didn't submit any challenges)
Thanks for your time guys, I really appreciate it !

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I wasn't able to determine if it's a bug on our side or not. Looking at @MKhasib's record everything seems fine -- there were no obvious gaps in `progressTimestamps` or `completedChallenges`, at least as far as I could tell.

It may have been a temporary connection issue when the challenge in question was submitted.

**Comment by raisedadead** [comment]
Awesome. Thanks for confirming.
