### ISSUE TITLE
Use a smaller amount of Lodash

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#41935]
I made an attempt, https://github.com/freeCodeCamp/freeCodeCamp/pull/41931, to reduce the contribution of Lodash to our bundle size.  This worked, with moderate success, but I couldn't find a way use Mocha to test the curriculum.  

The problem was that our Mocha tests rely on @babel/register which can't handle a ES module that imports another ES module.  It tries to require the second module, which fails.

Things I have tried:

- updating the @babel/register config to use `ignore: []` - no use, it still throws the same error
- using lodash/core - seems fine, but we use quite a lot of non-core functions so there's a fair bit of re-writing required
- use lodash-webpack-plugin to save space - tricky to integrate with Gatsby, I managed to use it, but it failed on SSR

What we could do:

- put the time in to replace any non-core functions
- use Cypress tests for the curriculum and remove the existing ones https://github.com/freeCodeCamp/freeCodeCamp/pull/41602

As @raisedadead said, this is all for a relatively minor gain in performance, so it's not a high priority.  I'll leave this issue up for a while, though, in case anyone can see a simple solution.

**Comment by raisedadead** [comment]
It will be a combination of both reducing cruft and moving closer to real world tests. Going to close this unless you think more work is necessary. If true, reopen.

**Comment by ojeytonwilliams** [comment]
@raisedadead not urgently, no.  @ahmadabdolsaheb and I have been steadily reducing the bundle sizes, so once we've picked the low-hanging fruit I'll open another issue if there's minor tweaks we might do.
