### ISSUE TITLE
This code passes when it never actually produces a whole number as per directions.

### ISSUE THREAD

**Issue by jebalert** [FreeCodeCamp/FreeCodeCamp#4194]
Challenge [Waypoint: Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript#?solution=var%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20myFunction()%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20Math.floor(Math.random()%20*%2010%20)%3B%0A%20%20return%20Math.random()%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A%0A(function()%7Breturn%20myFunction()%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function myFunction(){

  // Only change code below this line.
  Math.floor(Math.random() * 10 );
  return Math.random();
  
  // Only change code above this line.
}

(function(){return myFunction();})();

```

**Comment by abhisekp** [comment]
Test case needs to be added to check for a whole number output between 0 and 9.

**Comment by jebalert** [comment]
Also include instruction / or an example of how to add a min, max number.

**Comment by SaintPeter** [comment]
@jebalert The next waypoint talks about min/max numbers.

It's going to be hard to check the output range with our current infrastructure because we can't store the result in a variable to check the range.

I don't know if we can ensure that it is an integer for the same reason.

**Comment by asauce99** [comment]
Why don't you just have it return Math.floor(Math.random() * 10 );   ?  You don't need it to return Math.random()     Am I missing something?

**Comment by jamuhuri** [comment]
Initialize a variable to the random generator between 0 - 9 and then return the variable. See below,

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  var randomNumberBetween0and10 = Math.floor(Math.random() * 10);


  return randomNumberBetween0and10 ;
}
