### ISSUE TITLE
Tests need to accept both www and not www links

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#41950]
PR #41900 has made all links consistent as `www` links

Now a lot of people that are using old solutions and the videos as guide are failing using not-www links

Tests need to be made to accept both kind of links in the 18 challenges affected by the PR

(discussion [here](https://chat.freecodecamp.org/channel/contributors?msg=283Aec3kzzaPuLcWe))

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by gracewest333** [comment]
I would like to help with this issue, if you could point me to the right place in the repository where you where thinking it is an issue. Thanks :)

**Comment by ieahleen** [comment]
@gracewest333 for this issue you would to need to check all the files that were changed by #41900 and see in which challenges the url is tested, and adjust the tests to allow for both versions of the url

**Comment by gracewest333** [comment]
ok thanks

**Comment by gracewest333** [comment]
Do you want me to change the files to also say stuff like "Now set the `src` attribute so that it points to the url `https://www.bit.ly/fcc-relaxing-cat` or `https://bit.ly/fcc-relaxing-cat` ". Rather than just "Now set the `src` attribute so that it points to the url `https://www.bit.ly/fcc-relaxing-cat` " to, each time it mentions the specific URL? Or is that overkill?

**Comment by ieahleen** [comment]
@gracewest333 no, that would invalidate the work to make the links consistent, make the tests more permissible, do not change the challenge text

please also change the tests in the other challenges in which an url is tested, of the 18 challenges less than 5 actually have a test involgin an url
