### ISSUE TITLE
Missing carriage returns in main example in lesson

### ISSUE THREAD

**Issue by Elliria** [freeCodeCamp/freeCodeCamp#41954]
**Description:**
I ran into a slight hiccup in the [Networking: Write a Web Browser](https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/networking-write-a-web-browser) lesson, which is part of the **"Scientific Computing with Python"** course and figured I'd share in case something ought to be done to ease the way for the next person.

The carriage returns are missing from the GET request in the main example in which the GET request is stored in the **cmd** variable at the **1:09-minute mark** in the video, like so:
```
cmd = 'GET http://data.pr4e.org/romeo.txt HTTP/1.0\n\n'.encode()
```
When I copied the code on that page and tried to connect with the server, the server kept telling me I'd sent a bad command and that it didn't understand what I wanted. After a bit of experimenting, I noticed that the example in the **"Test"** section at the bottom of the lesson page had some carriage returns (`\r`)in front of the line feeds (`\n`), like this:
```
cmd = 'GET http://data.pr4e.org/romeo.txt HTTP/1.0\r\n\r\n'.encode()
```
When I substituted that line for the one in the main example, I was able to successfully connect to the server without issue.

The carriage returns weren't mentioned in the lesson's video and were just in the **Test** section of the page. They may have been optional at the time when that video was made and just happened to be added to the test code.

It seems that the double CRLF (`\r\n\r\n`) is currently how the [HTTP protocol is defined by the IETF](https://tools.ietf.org/html/rfc1945), which explains why the server was confused by my omission of them yesterday.

Perhaps a note could be added beneath the video on the lesson page letting future campers know that the carriage returns are now required.

**System:**
 - Device: desktop
 - OS: Ubuntu MATE 16.04 LTS
 - Browser: Firefox
 - Version: 88.0

**Comment by Elliria** [comment]
Note that the [Networking: Text Processing](https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/networking-text-processing) lesson that immediately follows the one above uses the same example without the necessary carriage returns at the **8:14-minute mark** and again at the **9:02-minute mark**, so that lesson, too, may need a note beneath the video in the lesson page letting future campers know that the carriage returns are now required.

**Comment by Elliria** [comment]
Last, but not least, I plan on continuing to work my way through this breathtakingly awesome course, so I'd be happy to let you'all know if any of the lessons after this also have the same, or a similar, example in them without the carriage returns so those lessons can also get a note (or be handled however you'd like to handle them).

**Comment by raisedadead** [comment]
Hi @Elliria 

Thanks a lot for the feedback and reporting this. 

We are working towards building a fully interactive course for python and we will be retiring these video courses when they are ready late this year or early next year.

However, I understand we can update the current challenges by adding notes like you mentioned and updating the seed code in the UI which people may be copying like you caught. 

Will you be interested in making a pull-request (or more) as you are going thru the course. It would help us increase the quality a bit and in turn help everyone taking these courses.

Let us know?

**Comment by Elliria** [comment]
Thanks for taking it on.

That's a shame that these have to be retired. I'm really enjoying them. Hopefully I'll finish before you do that (I'm currently at 70% of the way through the course).

One solution that I noticed was in a later video that also contains the outdated code. It's the [chapter 12 socket1 exercise](https://www.youtube.com/watch?v=dWLdI143W-g) that's hosted on YouTube and linked to by the "[Networking: Web Scraping with Python](https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/networking-web-scraping-with-python)" lesson. Someone had apparently noticed that the code is now outdated and put a text overlay onto the video at the [26-second mark](https://youtu.be/dWLdI143W-g?t=26) with a suggesting use of the current code instead. If you have the ability to edit the videos and add the overlay, that might be the quickest or easiest solution.

My "Git-fu" is very weak, but if you had one or more specific tasks with (hopefully air-tight) steps for me to take, I wouldn't mind doing a pull request or whatever would be needed.

Meanwhile, I've still got 17 lessons to do in this course. I've made it all the way through to the end of the JSON lesson without finding any other lessons that need attention besides the two mentioned in the bug report above, but I'll post here if I find any more.

**Comment by raisedadead** [comment]
> That's a shame that these have to be retired. I'm really enjoying them. Hopefully I'll finish before you do that (I'm currently at 70% of the way through the course).

Sorry, I should have clarified. 

You will be able to work through them even when we retire courses. They will always be available under a legacy section. I am pretty sure if you are enjoying the current video-based challenges you are going to like the interactive curriculum too. That said it's going to be a while before they get released. Meaning I am confident you would have already completed your current progress. :)

> My "Git-fu" is very weak, but if you had one or more specific tasks with (hopefully air-tight) steps for me to take, I wouldn't mind doing a pull request or whatever would be needed.

Absolutely, we will be glad to help you help us. I remember myself getting scared about Git too when I was starting off. 

If you are willing and interested, please go thru the lessons (we don't want to distract you) and once you have got time on your hand let us know if you find additional areas of improvement other than the two you mentioned previously.

We will lay down some steps that you can follow and make a PR.

Thanks again for reporting & happy coding.

**Comment by Elliria** [comment]
Oh, it's a relief that the courses will still be available and that I can definitely finish all the lessons. He really is a wonderful teacher. I'm not just sort of getting it like I would with many other teachers. What Charles Severance has done is make it so I actually **know** things. He tops off your tanks and makes it so you walk away from each of those lessons with really solid ground beneath your feet.

The interactive curriculum sounds interesting, too, and I'll definitely be checking that out as well when it's released. You can never learn too much.

I'll be learning Git properly by and by, probably once I'm done with these lessons (and/or the projects afterwards that get you the certificate). I know that GitHub offers a free tutorial you can go through.

Meanwhile, I'll let you know if I find anything else that needs attention and would be happy to try my hand at the Git without having fully learned it with whatever instructions you provide and as long as you don't mind if I mess it up a bit.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
