### ISSUE TITLE
WP: css class

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4195]
http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element
It is very bad practice to name a class after a color.  Class names should either declare function &/or location.  eg `main-header`, or `intro-paragraph`.
https://css-tricks.com/semantic-class-names/

**Comment by ltegman** [comment]
Even the article you linked states that classes being used to describe styling is not uncommon in this era of CSS frameworks (like bootstrap) so I don't see this as an issue. Especially in a simple first introduction like that lesson. I'm leaving this open for discussion though to get other people's opinions.

**Comment by SaintPeter** [comment]
I don't know that @tomByrer is wrong, but any change would need to be made to several waypoints which share the same naming scheme.

I'm not seeing this as being critical.  It may not be a best practice, but it's still valid CSS and helpful for simplifying the teaching.

**Comment by tomByrer** [comment]
Good point about bootstrap, though I avoid using it (& classitis is one of the reasons).  I'd prefer to find 'best practices' as I learn, so I don't have to un-learn anything later.

Would be a good lesson to teach best practices (eg "Let's pretend the client changed their mind about the color scheme.  Change the unsemtatic `blue-text`to a more semantic `top-header` and change the color to blue.".
Unless project owners *never* change their mind in the wild... ;)

**Comment by ltegman** [comment]
@tomByrer definitely like this idea of using the really simple example `blue-text` first and then using that to illustrate the value of semantic classes in a follow up lesson.

**Comment by BerkeleyTrue** [comment]
You don't teach best practices first. You teach the concept first and the concept we are trying to get across is naming a css class and using a css class. 

Often `best practice` is subjective, especially when it comes to css. For instance, I prefer my own style of BEM when writing CSS. Others will want to use an approach like Atomic. 

I don't think this is an issue especially considering how much would need to be changed for what is a matter of preference.

**Comment by ltegman** [comment]
Closing as a matter of preference and not worth fixing. Someone else can reopen if they feel this is worth changing.
