### ISSUE TITLE
WP: font size

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4198]
http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element
Confusing directions:
`Then, inside your <style> element, set the font-size of all p elements to 16 pixels.`
then at end:
`Give elements with the red-text class a font-size of 16px.`  Should be "paragraphs" not "red-text class".

**Comment by ltegman** [comment]
There's a couple confusing parts in the text for this waypoint. It also states that you should be giving "both" `p` elements a different font size but the seed code only has one, so this could use some definite cleanup.

Thanks for the report!

**Comment by tomByrer** [comment]
cheers
