### ISSUE TITLE
http://www.freecodecamp.com/challenges/waypoint-import-a-google-font

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4199]
Considered best practice to have generic family (`monospace`) names in lower case; easier to find.
Most examples I've seen & official specs use lower case also.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

**Comment by SaintPeter** [comment]
Generic fonts, being css keywords, are case insensitive - there is no requirement that any particular case be used.

As to what is or is not "best practice", reasonable men may differ.  

If you feel strongly about this, I encourage you to file a PR.

Thank you and happy coding!
