### ISSUE TITLE
Tests for curriculum helpers

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#41994]
The curriculum helper scripts could use some tests.  A recent breaking change to https://github.com/williamkapke/bson-objectid stops the helpers working, but https://github.com/freeCodeCamp/freeCodeCamp/pull/41677 is green.

**Comment by raisedadead** [comment]
Did that breaking change land? If so why & how?

**Comment by ojeytonwilliams** [comment]
Nope, because I saw that it was major bump and went and investigated.  I had to find this PR: https://github.com/williamkapke/bson-objectid/pull/37 before I realised that it was going to affect us, though, so I could easily have missed it.

**Comment by Nirajn2311** [comment]
I'm interested in taking this up and wanted to know what kind of tests can be made.

**Comment by ojeytonwilliams** [comment]
Awesome :+1: 

Since we're not actively developing right now (@RandellDawson did a great job and we don't currently plan to extend it), the main thing we want is to make sure it doesn't break if we update dependencies.

It's worth considering tests like 

- do the scripts create-empty-steps, create-next-step and so on behave as expected (i.e. acceptance tests)
- do the individual functions do what we think they do (i.e. unit tests)

I'd probably go the unit test route and test `createStepFile` and `reorderSteps`, since they do the majority of the work.

Does that give you enough to go on @Nirajn2311 ?

**Comment by Nirajn2311** [comment]
Gotcha 👍
