### ISSUE TITLE
row outside of div detected as valid

### ISSUE THREAD

**Issue by tchan811** [FreeCodeCamp/FreeCodeCamp#4203]
Challenge [Waypoint: Create a Bootstrap Row](http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-row#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%0A%3C%2Fdiv%3E%0A%0A%3Cdiv%20class%3D%22row%22%3E%0A%3C%2Fdiv%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>

</div>

<div class="row">
</div>
```

This is detected as valid even though the div is supposed to be nested inside the container-fluid div.
<img width="470" alt="screen shot 2015-11-05 at 9 04 13 pm" src="https://cloud.githubusercontent.com/assets/12490711/10989811/da7e244e-8400-11e5-8540-1e554cc49bd6.png">

**Comment by ltegman** [comment]
While someone is at it with changing the tests for this we might also want to alter the sidebar instructions to explicitly state that the new div with class row should be inside the containter-fluid. It can be inferred from the previous challenge, but it's not actually stated.

**Comment by SaintPeter** [comment]
Assign me, I'll take this.
