### ISSUE TITLE
Solution code to Exercise 8 is broken

### ISSUE THREAD

**Issue by jaybot7** [FreeCodeCamp/FreeCodeCamp#4210]
Challenge [Waypoint: Build Web Apps with Expressjs](http://www.freecodecamp.com/challenges/waypoint-build-web-apps-with-expressjs) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

// buggy solution code doesnt work!
// app.get('/search', function(req, res){
//       var query = req.query
//       res.send(query)
//     })

Which is what everyone will try to do. The verify expects the output to be a JSON.stringify object, which the above code won't do.

Making a map and doing res.end(JSON.stringify(map) will pass the test, however.

**Comment by SaintPeter** [comment]
You can file a bug against expressworks here:
https://github.com/azat-co/expressworks

**Comment by BerkeleyTrue** [comment]
@SaintPeter is correct, please file against express works.
