### ISSUE TITLE
iPadOS Curriculum Incompatibility

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#42102]
Opening any challenge page on an iPad (2 tested so far) yields a blank page.

Related forum post: https://forum.freecodecamp.org/t/lessons-not-loading-on-ipad-pro/459782

First device user-agent:
- `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

My device user-agent:
- `Mozilla/5.0 (iPad; CPU OS 10_3_4 like Mac OS X) AppleWebkit/603.3.8 (KHYML, like Gecko) Version/10.0 Mobile/14G61 Safari/602.1`

Behaviour:
1) Navigating `/learn` platform is as expected, until a `challenge` (with editor) page is opened
2) Page loads, initially with editor preview
3) Before seed is loaded and iframe preview is mounted, whole page goes blank - no errors

I am unable to test any further other than having experienced the same in the Edge browser as well.

I would have said #42101 is related, but behaviour is worse - no errors.

**Comment by lasjorg** [comment]
OK, so it's the old version before the engine switch. That is what I expected, thanks.

**Comment by moT01** [comment]
I am experiencing this with: 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
(Safari 13.1.2)
```
It was confirmed by @texas2010 on chat that the latest version of Safari is working.
It was working for me on this version of Safari when I made this issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/41893 - Quite sure that issue is unrelated.
Also, I noticed this issue when I was debugging the strip comments issue linked at the top yesterday. Reverted commits back to `a23d96f0d8 chore(deps): include postcss` and it was still broken at that point. So I believe it broke some time between when I made the issue I linked, and that commit. I feel like it's one of the dependency updates, but I'm not sure.

**Comment by raisedadead** [comment]
Hey @moT01 or anyone else interested. We just pushed a batch up to staging in case anyone wants to test it out.

**Comment by moT01** [comment]
Looks like it works:
(iPad + (safari || firefox)) || (OSX + Safari) = Broken on production, Works on staging

**Comment by raisedadead** [comment]
Thanks for confirming.

**Comment by ShaunSHamilton** [comment]
Just to mention it, I get the status `500` error on `.dev` on my iPad in Safari - the one that says this part of the site is under maintenance.

**Comment by raisedadead** [comment]
It could be a temporary outage when the site was rolling over, try clearing cache? The site is up as far as I can tell.

**Comment by ShaunSHamilton** [comment]
I am still unable to access it, but it does seem unrelated to this, as I see the _details_ message with:
```console
Connection timed out

The initial connection between Cloudflare's network and the origin
web server timed out. As a result, the web page can not be displayed.

- Ray ID: xxxx
- Your IP address: xxxx
- Error reference number: 522
- Cloudflare Location: London
```

**Comment by ojeytonwilliams** [comment]
Well that's unexpected.  If you're still seeing this and could share the headers, that'd be awesome.

**Comment by Nirajn2311** [comment]
Curious question, how are you accessing the local dev in ipad?

**Comment by ShaunSHamilton** [comment]
@Nirajn2311 I think you might be confusing local development with what we are talking about - the staging platform of freeCodeCamp: https://freecodecamp.dev

Although, I can access a local development of freeCodeCamp by exposing the URL from GitPod.

**Comment by Nirajn2311** [comment]
Ahh I dint realise you were talking of the staging platform. Also thanks for that Gitpod suggestion, I needed just that for some of my testing.
