### ISSUE TITLE
WP hex gray easier to read

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4211]
http://www.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-gray
May I suggest `#707070` instead?  `#808080` is very hard to read in monospaced slashed-0 small font on a monitor that is 1m away in the sun.  ;)

**Comment by SaintPeter** [comment]
We have not gotten any complaints in the /Help chat.
