### ISSUE TITLE
freeCodeCamp Twitch Project broken

### ISSUE THREAD

**Issue by texas2010** [freeCodeCamp/freeCodeCamp#42117]
the freeCodeCamp Twitch API project is broken.

nothing shows up on it.

https://codepen.io/freeCodeCamp/full/Myvqmo/

![Screen Shot 2021-05-12 at 11 06 14 AM](https://user-images.githubusercontent.com/9701609/118007820-1d762f80-b312-11eb-824e-44141598f267.png)

**Comment by moT01** [comment]
Should be good to go. 👍
