### ISSUE TITLE
inconstant editor linting

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4212]
-  [ ] http://www.freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-red

Usually the editor will seem to beautiy code to include trailing semicolons for the last item in CSS.  This is a good practice.  But for some reason, beautification doesn't happen in the above links.

(I'll add to the above links as needed.  Feel free to fill in my checkboxes.)

**Comment by SaintPeter** [comment]
Am I correct that there are two issues here:
1) There is a missing semicolon in the solution
2) The linter doesn't highlight this as an error?

**Comment by tomByrer** [comment]
1) missing in the pre-filled code, before you start to add the answer.  The other exercises include the `;` already
2) not an error; leaving out a `;` at the last item in a CSS rule is perfectly fine.  Kinda like `;` in JS; not needed often, but good practice to prevent errors in later editing.

**Comment by SaintPeter** [comment]
Since it's technically acceptable as is and doesn't represent a defect, I propose taking no action.  It's not worth a PR to "fix".
