### ISSUE TITLE
Expand/Collapse courses arrows point to wrong directions

### ISSUE THREAD

**Issue by alirezaghey** [freeCodeCamp/freeCodeCamp#42139]
**Describe the bug**
The arrow to the left of **Expand courses**/**Collapse courses** buttons points down when the list is in collapsed state and points up when the list is in expanded state.
This is opposed to standard behavior of similar features in other apps.

**To Reproduce**
1. Go to [https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)
2. Look at the arrow to the left of *Collapse courses*. It points up while the list is in expanded state.
3. Click on the above mentioned button to collapse the list.
4. Now the list is collapsed state but the arrow points down.

**Expected behavior**
By convention, the arrow should point to the right or up when the list is in collapsed state and point down when the list is in expanded state.

**Screenshots**
![image](https://user-images.githubusercontent.com/26653424/118332613-e06c9180-b4f9-11eb-9cb0-ede17a86890b.png)
![image](https://user-images.githubusercontent.com/26653424/118332630-e9f5f980-b4f9-11eb-90d9-6216c56b49b0.png)

**Desktop:**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Opera
 - Version: 76

**Additional context**
Also tested this on the same OS with Firefox 88.0.1 with the same result.

**Comment by ahmadabdolsaheb** [comment]
I agree, we should have the arrow pointing to the left when the courses are collapsed and down when they are expanded.

**Comment by alirezaghey** [comment]
Hi Ahmad,
I think you mean we should have the arrow pointing to the right when the courses are collapsed, right?

**Comment by ArnoldGee** [comment]
Hi. I'm new to contributing to FreecodeCamp, and just read the guidelines. With your permission, I will fork the project and try to solve the issue with a pull request.
