### ISSUE TITLE
Accept Donations in Bitcoin   

### ISSUE THREAD

**Issue by bliotti** [freeCodeCamp/freeCodeCamp#42142]
Why not accept donations in Bitcoin? It can only help. Give users alternative ways to contribute!  

Easy Setup. BitPay has been around for a while. (I am not affiliated to BitPay in any way)
https://bitpay.com/docs/donations

**Comment by ahmadabdolsaheb** [comment]
Thanks you for your suggestion @bliotti.

Although we have been focusing on accepting single value recurring donations, we do accept [crypto donations](https://www.freecodecamp.org/news/how-to-donate-to-free-code-camp/#does-freecodecamp-accept-donations-in-bitcoin-or-other-cryptocurrencies) among other options.

We have been evaluating different crypto payment processors including open-source self-hosted solutions, and we will share the news as soon as we arrive at a conclusion.

I am going to close this issue for now. Please let me know if this issue has been closed by mistake or if it needs further discussion.
