### ISSUE TITLE
[Challenge: Use a CSS Class to Style an Element] The code looks good, but can't pass the first test

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#42174]
**Affected page**
[Use a CSS Class to Style an Element](https://chinese.freecodecamp.org/learn/responsive-web-design/basic-css/use-a-css-class-to-style-an-element)

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
<style>
.red-text {color: red;}
</style>

<main>
<h2 class="red-text">CatPhotoApp</h2>
<p>Click here to view more <a href="#">cat photos</a>.
</p>

<a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

<div>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="https://freecatphotoapp.com/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label><br>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
</main>



```

**Expected behavior**
I create this issue on behalf of a learner who [reported on the Chinese forum](https://chinese.freecodecamp.org/forum/t/topic/2368). The code works for me on Mac (both Chinese and English versions). The learner's system details are listed below.

**Screenshots**
![image](https://user-images.githubusercontent.com/19358186/118637106-05b61400-b808-11eb-8de3-77d082bc1621.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.114

**Comment by Sembauke** [comment]
Hey, this might be caused by enabled extensions in the browser.  Try disabling them they might interfere with the current challenge.

**Comment by paulywill** [comment]
Can they also try another browser such as Firefox?

**Comment by alirezaghey** [comment]
I tested this on Ubuntu 20 with both Opera 76 and Firefox 88 for both English and Chinese versions of the page. All four combinations work correctly for me.

**Comment by raisedadead** [comment]
Replied on the forum thread.
