### ISSUE TITLE
freecodecamp waypoint 7: filtering an array with .filter()

### ISSUE THREAD

**Issue by bg87** [FreeCodeCamp/FreeCodeCamp#4218]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val > 5;
  
});

// Only change code above this line.

(function() { return newArray; })();

```

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps and a description on how to reproduce the issue.

Happy Coding!
