### ISSUE TITLE
Error of right option in data analysis with python course

### ISSUE THREAD

**Issue by nitishjoshi86** [freeCodeCamp/freeCodeCamp#42184]
**Affected page**
Add a link to the coding challenge with the problem.
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-operations

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
a = np.arange(5)
a + 20


above problem showing right answer as [0, 1, 2, 3, 4] 

**BUT**



```

**Expected behavior**
Add a clear and concise description of what you expected to happen.

**The right answer should be == [20, 21, 22, 24, 24]** 

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.
![image](https://user-images.githubusercontent.com/84433778/118760312-36da2700-b890-11eb-8fdf-e51172d0c602.png)

**System (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 90.0.4430.212
 - 
**Additional context**

**Comment by Nirajn2311** [comment]
Hi, the right option is correct. Remember we are asking for the **value** of `a`.

**Comment by nitishjoshi86** [comment]
> Hi, the right option is correct. Remember we are asking for the **value** of `a`.

You can go through the below screenshots. 

**below ss shows issue in your course** 

![image](https://user-images.githubusercontent.com/84433778/118808255-f3e77600-b8c6-11eb-90ba-1b64babb2406.png)


**below is the practical example of the correct answer I have raised the issue for** 

![image](https://user-images.githubusercontent.com/84433778/118808399-1b3e4300-b8c7-11eb-9768-4fbd09002734.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

> below is the practical example of the correct answer I have raised the issue for

Now, print the "value of `a`"...

**Comment by Nirajn2311** [comment]
I understand. Ok, think what the last line ie. `a+20` is doing. Again, I'm saying we're asking the **VALUE** of `a`.

**Comment by nitishjoshi86** [comment]
ok understood, was confused. Thanks.
