### ISSUE TITLE
filtering an array using .filter()

### ISSUE THREAD

**Issue by bg87** [FreeCodeCamp/FreeCodeCamp#4219]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val > 5;
  
});

// Only change code above this line.

(function() { return newArray; })();

```
I'm trying to filter oldArray[1,2,3,4,5,6,7,8,9,10] to take out any numbers greater than five so I'm using the filter method with the function return val > 5 and storing it in newArray. My code seems to be creating newArray with the numbers 6 -10 but I still can't pass the waypoint.

**Comment by venkatraj** [comment]
The waypoint is about filtering out numbers greater than 5. So your function should return true for numbers that are less than 5.
```
return val <= 5;
```
