### ISSUE TITLE
Edit feature on Camper News 

### ISSUE THREAD

**Issue by duttakapil** [FreeCodeCamp/FreeCodeCamp#422]
It would be nice if you could edit the posts you submit on Camper News. I made this post by mistake : http://www.freecodecamp.com/news/let. I was typing the title for the submission and hit the enter key by mistake and now I can neither delete it nor edit it.

**Comment by BerkeleyTrue** [comment]
Great idea!

**Comment by QuincyLarson** [comment]
Yes - the ability to delete it entirely would suffice. Then people could resubmit if necessary, but like with Twitter, there probably isn't a need for an edit functionality, especially since we removed comments.
