### ISSUE TITLE
Challenge implies using anti-pattern which may have unexpected results in real situations

### ISSUE THREAD

**Issue by alirezaghey** [freeCodeCamp/freeCodeCamp#42208]
**Affected page**
https://www.freecodecamp.org/learn/front-end-libraries/react/render-conditionally-from-props

The lines 242-246 of the [file](https://github.com/freeCodeCamp/freeCodeCamp/blob/4d024f3e4bcbb0a0016e6a6bce01619c25e54dbc/curriculum/challenges/english/03-front-end-libraries/react/render-conditionally-from-props.md#L242-L246) read:
```js
handleClick() {
  this.setState({
    counter: 0 // Change this line
  });
}
```
This implies that you can increment `counter` as follows: `counter: this.state.counter + 1`.
As already taught at this point of the curriculum, this method can result in unexpected behavior, since React may batch state updates for performance reasons.
AFAIK, the following is the correct way to handle this situation:
```js
handleClick() {
  this.setState(prevState => ({counter: prevState.counter + 1}))
}
```
**Expected behavior**
Right now, both methods of incrementing `counter` are accepted. I suggest we change the provided code and the tests so that only the second method is implied and accepted.

**System:**
 - Device: Laptop
 - OS: Ubuntu 20.4
 - Browser: Opera
 - Version: 76

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. It appears this lesson was missed in the PR that closed the related issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/39267

As such, I am going to open this to first-timers with the expected change being outlined as in the original post.

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by suburban-daredevil** [comment]
@ShaunSHamilton . I would like to work on this issue. Just for your kind information. Thanks!

**Comment by suburban-daredevil** [comment]
Hello @ShaunSHamilton,

I have opened a pull request for this issue. Can you please check?

Thanks

**Comment by lasjorg** [comment]
@suburban-daredevil There is already a PR for this which is awaiting requested changes. Let's give them a chance to change what is needed first. If it does not happen within a reasonable timeframe we can use your PR instead.

**Comment by suburban-daredevil** [comment]
Thanks @ShaunSHamilton and @lasjorg for taking your time out and responding. I understand it completely. Thanks once again!

**Comment by raisedadead** [comment]
Hi @soham283 thanks for reaching out and we appreciate your help. We would like you to start here: https://contribute.freecodecamp.org/#/FAQ

Happy contribuitng.
