### ISSUE TITLE
Challenge asks to call preventDefault but it has no effect on the results

### ISSUE THREAD

**Issue by alirezaghey** [freeCodeCamp/freeCodeCamp#42204]
**Affected page**
https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-controlled-form

**Your code**

```
class MyForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: '',
      submit: ''
    };
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }
  handleChange(event) {
    this.setState({
      input: event.target.value
    });
  }
  handleSubmit(event) {
    // Change code below this line
    event.preventDefault();
    this.setState((prevState, props) => (
      {submit: prevState.input}
    ))
    // Change code above this line
  }
  render() {
    return (
      <div>
        <form onSubmit={this.handleSubmit}>
          {/* Change code below this line */}
          <input onChange={this.handleChange}
            value={this.state.input}
          />
          {/* Change code above this line */}
          <button type='submit'>Submit!</button>
        </form>
        {/* Change code below this line */}
        <h1>{this.state.submit}</h1>
        {/* Change code above this line */}
      </div>
    );
  }
}
```

**Expected behavior**
The challenge states:
_Note: You also must call event.preventDefault() in the submit handler, to prevent the default form submit behavior which will refresh the web page._

But calling `preventDefault()` doesn't have any effect. The tests pass without calling it and there is no visual difference between the state where `preventDefault()` is called and where it is omitted, as far as I can tell.

If that's the case, my suggestion is to add some additional context for Campers to learn and be aware of or remove that part altogether.

**System:**
 - Device: Laptop
 - OS: Ubuntu 20.4
 - Browser: Opera
 - Version: 76

**Comment by Nirajn2311** [comment]
> The tests pass without calling it and there is no visual difference between the state where preventDefault() is called and where it is omitted, as far as I can tell.

This is caused by the below code which is inserted into the iframes `head` tag. Since the page doesn't refresh for us, I guess it would be better for us to make a test for it so the user knows that line is required for the page to not refresh when a form is submitted.

https://github.com/freeCodeCamp/freeCodeCamp/blob/21dd80c47a0a5f4d50cad18ed06d9daf540fbab5/client/src/templates/Challenges/utils/frame.js#L43-L48

**Comment by alirezaghey** [comment]
I have a question and this may well be out of the scope of this issue/challenge:

Why are we testing every challenge on the frontend? If we tested on the backend we could employ standard testing libraries instead of custom methods involving regex or...
Setting up the infrastructure and rewriting tests would take much time and effort at the beginning but in the long-run, I imagine, it would be easier to add, debut, and update tests and challenges.
The additional load on the backend, just a guess, wouldn't be relatively very huge considering the small footprint of containers and the already huge dimensions of FCC.
