### ISSUE TITLE
Create a separate warning if the server is unreachable

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#42203]
**Is your feature request related to a problem? Please describe.**
Currently the client displays the "You appear to be offline, your progress may not be saved" message if the browser reports that it's offline or if challenge submission fails. However challenge submission can fail for several reasons and not necessarily because a user is unable to get online.

**Describe the solution you'd like**
As second message to be shown if the servers cannot be reached. "The server could not be reached, please contact support if this you see this message again"  Something along those lines.

**Comment by Sembauke** [comment]
This seems like a needed feature, after what happened a couple of days ago.

**Comment by ojeytonwilliams** [comment]
Yeah, it should help us work out where the problem lies. Right now it doesn't tell us much

**Comment by Anay21110** [comment]
Hello @ojeytonwilliams  ,
I am new to open source trying to make my first contribution,
I am interested in contributing in this issue, if the problem is not solved,
can you assign me this issue

**Comment by ojeytonwilliams** [comment]
Hi @Anay21110 thanks for the offer of help.  Please take a look at our [contribution docs](https://contribute.freecodecamp.org/#/index?id=introduction) if you would like to know about how to take part.

**Comment by JimmyK1995** [comment]
This would definitely make sense to add. A pretty small feature that may avoid lots of frustration for the users. 
I will look into it.

**Comment by Sembauke** [comment]
If you have any questions you can always at the at freecodecamp/dev-team.

**Comment by budbreaker** [comment]
Hello I am eyeing this issue, trying my hand at contributing. 
I just wonder whether server unavailability is reproducible on local environment and/or Gitpod.

**Comment by ojeytonwilliams** [comment]
Hey @budbreaker.  It certainly is and the following steps should replicate it:

1. in one terminal: `npm run develop:client`
2. in a separate terminal: `npm run develop:server`
3. sign in, if you are not already
4. shut down the server
5. navigate to a challenge
6. wait a few seconds to see the warning

**Comment by budbreaker** [comment]
hi @ojeytonwilliams 
I am looking at the problem and it seems that the isOnline property is not being set correctly... which baffles me, because it's being set as such 

https://github.com/budbreaker/freeCodeCamp/blob/cf3dc4d3b5656a9aa95bd7b76f6098d0f560a3a5/client/src/components/layouts/Default.js#L121-L122

but inside the offline-warning function with disabled server the values are following:

isOnline=false
window.navigator.onLine=true
navigator.onLine=true
isSignedIn=true

The message could be based on current status of navigator.onLine instead of isOnline property. Thoughts ?

**Comment by ojeytonwilliams** [comment]
Hey @budbreaker.  So, what's going on is that that function is only called when the `online` and `offline` events fire.  So, if you turn off your internet, that will trigger and correctly show the offline warning.  In addition there's a redux epic that dispatches an `onlineStatusChange` action when it's unable to reach the server: https://github.com/freeCodeCamp/freeCodeCamp/blob/e44610f1d02e53404b99b2a23a3feb0fcaeb1eba/client/src/redux/failed-updates-epic.js#L40

It's that epic that's responsible for the value of `isOnline` that you saw in `offline-warning`. To resolve this issue, those two things (lack of internet and inability to reach the server) should be handled separately and provide different warnings.

Does that clear things up?

**Comment by budbreaker** [comment]
Yes, this will help greatly, because I was unsure whether there will be a need to implement some sort of heartbeat to check for server availability.

**Comment by budbreaker** [comment]
Hi @ojeytonwilliams 
I am almost done with this, but I have stumbled upon one problem. I have added a new string into english `translations.json` file, but when I try to invoke it as the previous one was (`t('misc.server-offline')`), it will only say "misc.server-offline". Do I need to update something in order for the string to be usable as the others in translation files ?

**Comment by Sembauke** [comment]
You can run  `npm run clean:client` and run develop again.

**Comment by budbreaker** [comment]
Yes thank you, I got my response in the chat meanwhile, so I deleted my comment here.

**Comment by ShaunSHamilton** [comment]
After looking over the #43576 implementation, it looks as though we would be best removing the _Camper offline_ logic, and, instead, simplify everything to:
- If Camper cannot reach server, Camper is disconnected

That is, the only thing we care about is whether or not the client can access the server. So, there is only one `online` state to keep track of.

@ojeytonwilliams and @Sembauke Thoughts?
