### ISSUE TITLE
Broken test or unclear instructions in Headless Browser II of the quality assurance curriculum

### ISSUE THREAD

**Issue by Halu89** [freeCodeCamp/freeCodeCamp#42212]
**Affected page**
Add a link to the coding challenge with the problem.
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser-ii

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
    test('submit "surname" : "Vespucci" - write your e2e test...', function (done) {
      browser.fill("surname", "Vespucci").pressButton("submit", function() {
        browser.assert.success();
        browser.assert.text("span#name", "Amerigo");
        browser.assert.text("span#surname", "Vespucci");
        browser.assert.elements('span#dates', 1);
      
        done()
      })
    });
```

**Expected behavior**
Add a clear and concise description of what you expected to happen.

The code should pass the fcc tests

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.
![Capture d’écran 2021-05-21 200652](https://user-images.githubusercontent.com/63454314/119180094-1f599480-ba70-11eb-9b95-477c5202a49c.png)

**System (please complete the following information):**
Irrelevant

**Additional context**
The solution at https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-run-functional-tests-using-a-headless-browser-ii/301594 uses browser.assert.element ( **s missing** ) and the tests are using that.
It is inconsistent with the previous lesson, and according to the Zombie docs, we could either use browser.assert.element('span#name') or browser.assert.elements('span#name', 1)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. It appears this was missed with the previous PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/42090 , and issue.

As such, it is a simple fix to correct the test at: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser-ii.md

So, I am going to open this up to first timers

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
