### ISSUE TITLE
Update image link in React Markdown Previewer example project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#42226]
The [Markdown React example project](https://codepen.io/freeCodeCamp/full/GrZVVO) has an image link (React logo) that no longer works. The link is using Google URL Shortener and redirects to some WP site.

`https://goo.gl/Umyytc`
`https://techchronos.com/wp-content/uploads/SszarkLabs/stack-icon/cywBkaGwkMeDAuJbSt1k.png`

Not sure if we should add the logo to our CDN, or just use something like commons.wikimedia.org for the link?

The logo is licensed under Creative Commons Attribution 4.0 ([GitHub issue](https://github.com/facebook/react/issues/12570#issuecomment-411130246))
https://github.com/reactjs/reactjs.org/blob/master/LICENSE-DOCS.md

https://commons.wikimedia.org/wiki/File:React-icon.svg

**Comment by suburban-daredevil** [comment]
Hello @lasjorg. I would like to work on this issue. Can you please assign this issue to me? Thank you!

**Comment by ShaunSHamilton** [comment]
@suburban-daredevil 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

As this issue requires access to the freeCodeCamp CodePen account, a member of staff will have to get to it. Hope this clarifies

**Comment by suburban-daredevil** [comment]
Hello @ShaunSHamilton. Thanks for clarifying!

**Comment by lasjorg** [comment]
I'm still not sure if we should use the CDN or not? As far as I can tell, the logo license should allow us to have a copy on the CDN repo.

I might just open a PR and see if anyone has any concerns or not.

**Comment by ShaunSHamilton** [comment]
> I'm still not sure if we should use the CDN or not?

Me neither. I will defer to others on this.

> I might just open a PR and see if anyone has any concerns or not.

If you mean to add to the CDN, then by all means.

**Comment by lasjorg** [comment]
PR https://github.com/freeCodeCamp/cdn/pull/72

**Comment by lasjorg** [comment]
Come to think of it. It doesn't have to be the React logo. Maybe we should just use the fCC logo instead?

**Comment by moT01** [comment]
Closed via the linked merged PR
