### ISSUE TITLE
Localize ask-for-help template

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#42232]
We want to localize the Ask-To-Help template that pre-fills the post on the forum.

![image](https://user-images.githubusercontent.com/1884376/119367773-ec154080-bccf-11eb-93a3-0df15bdc9ae2.png)

The above button which takes you to the forum should render this template:

![image](https://user-images.githubusercontent.com/1884376/119367918-12d37700-bcd0-11eb-97ce-9c9475d5d8f8.png)

In the localized version instead.

**Comment by nhcarrigan** [comment]
Should be able to tackle this today, I think.

**Comment by raisedadead** [comment]
Sure. Not a high priority, so take your time.
