### ISSUE TITLE
The code properly reverses the array but doesn't allow me to proceed. (claims I'm not using the reverse method)

### ISSUE THREAD

**Issue by jebalert** [FreeCodeCamp/FreeCodeCamp#4224]
Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse#?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%0Aarray.reverse(function(a%2Cb)%7B%0A%20%20%20%20%20%20%20%20return%20b%20-%20a%3B%0A%7D)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7Breturn%20array%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.
 
array.reverse(function(a,b){
        return b - a;
});

// Only change code above this line.

(function() {return array;})();

```

**Comment by jebalert** [comment]
it appears that, while my solution indeed reverses the array - the proper way to do so is simply 

```
array.reverse();
```

**Comment by asauce99** [comment]
The code  array.reverse();   does not work for this waypoint.

**Comment by faizaanceg** [comment]
@asauce99  It does work.

**Comment by asauce99** [comment]
Yeah, it does. I must have been a character off. Maybe semicolon
