### ISSUE TITLE
Codepen template for projects - move test script to pen settings?

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#42269]
It happens that a lot of people, even using the codepen template, when they start working on the projects delete everything that is in the html box and then start write their code, then when they want to test find that the test suite has disappeared
If the link is moved to the pen settings instead it will make it less likeley for users to delete it accidentally.

It may be worth considering

**Comment by ShaunSHamilton** [comment]
Yes, I like the idea of this.

If no one is opposed, I will go ahead and change the templates.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for creating an issue about this, @ieahleen. This is a great suggestion, and should hopefully make it easier for campers and everyone on the forum who helps debug projects.

@ShaunSHamilton, here's the link to the CodePen project we're using as a template: https://codepen.io/freeCodeCamp/pen/MJjpwO

I think we'll just want to check that, once the test suite is moved to the settings for the project, it's still there once someone clicks the [template link](https://codepen.io/pen?template=MJjpwO) to create their own fork.

But I'm pretty sure this won't be a problem. I tried creating a fork of a couple of completed projects, which all have the test suite link in their settings, and the test suite carried over to my forks.

**Comment by ShaunSHamilton** [comment]
@scissorsneedfoodtoo Is this message still true?
> For now, the test suite only works in Chrome!

**Comment by ShaunSHamilton** [comment]
Well, that appears to be working. I have moved the script into the JS settings, and tested with my own account - works.

**Comment by scissorsneedfoodtoo** [comment]
@ShaunSHamilton, sorry, just seeing this now. I believe that used to be the case, but the suite should work in both Firefox and Chrome. We're running Selenium tests for both at the moment.

We can probably go through and remove all of those notes. Are they in the pens themselves?
