### ISSUE TITLE
Sign in buttons do not have visible focus states for keyboard navigation

### ISSUE THREAD

**Issue by tannerdolby** [freeCodeCamp/freeCodeCamp#42261]
**Affected page**
The affected page is [Sign in](https://auth.freecodecamp.org/login?state=hKFo2SAxMjVKYU5peWJONmY3VnBNQWoxZ2dBRU54WWNtQU1XZaFupWxvZ2luo3RpZNkgdzBUZm1oRmZfTWhDNE1GXzFVeXZDZHJkaDYzZWdDa06jY2lk2SBhVUR2OWpWcVRmeEJSRTFsNjBOQTVBZjd5VENHRTRjeQ&client=aUDv9jVqTfxBRE1l60NA5Af7yTCGE4cy&protocol=oauth2&response_type=code&redirect_uri=https%3A%2F%2Fapi.freecodecamp.org%2Fauth%2Fauth0%2Fcallback&scope=openid%20profile%20email)

**To Reproduce**

1. Go to [freeCodeCamp](https://www.freecodecamp.org/)
2. Click on 'Sign in button' (Top right corner for larger viewports)
3. Arrive at the [freeCodeCamp Sign in](https://auth.freecodecamp.org/login?state=hKFo2SAxMjVKYU5peWJONmY3VnBNQWoxZ2dBRU54WWNtQU1XZaFupWxvZ2luo3RpZNkgdzBUZm1oRmZfTWhDNE1GXzFVeXZDZHJkaDYzZWdDa06jY2lk2SBhVUR2OWpWcVRmeEJSRTFsNjBOQTVBZjd5VENHRTRjeQ&client=aUDv9jVqTfxBRE1l60NA5Af7yTCGE4cy&protocol=oauth2&response_type=code&redirect_uri=https%3A%2F%2Fapi.freecodecamp.org%2Fauth%2Fauth0%2Fcallback&scope=openid%20profile%20email) page
4. Tab through the sign in buttons
5. See error that each of the buttons do not have visible focus states for someone navigating the site with a keyboard or screen reader.
6. Click 'Sign in with email' button
7. See the same non-existent focus state for "Email me a short code to continue" button"

**Expected behavior**
For all of the buttons on sign in page and subsequent pages to have focus states (visible outline) that highlight interactive components like buttons.

**Screenshots**
Demo of tabbing through buttons on sign in page

https://user-images.githubusercontent.com/48612525/119704120-23890780-be0c-11eb-8465-0b48275f91f8.mov

**System (please complete the following information):**
 - Device: Macbook Pro Laptop
 - OS: Mac OS High Sierra v10.13.6
 - Browser: Chrome
 - Version: [Version 90.0.4430.212 (Official Build) (x86_64)]

**Additional context**
Focus states on these buttons are crucial for someone attempting to sign in to freeCodeCamp using only a keyboard for navigation (ie tab), or for those using a screen reader. 

The buttons do indeed have a hover state, just missing a visible focus state. Buttons on the Home page at freeCodeCamp.org are tabbable with visible focus states. It seems the Sign in page is the only affected page to my knowledge.

**Comment by tannerdolby** [comment]
There is `outline: none` in the CSS here which is the root cause. 

<img width="384" alt="Screen Shot 2021-05-26 at 10 31 30 AM" src="https://user-images.githubusercontent.com/48612525/119705465-9e9eed80-be0d-11eb-8208-1aaeb924f80d.png">

**Comment by tannerdolby** [comment]
If we were to add `outline` and `outline-offset` to the `focus` state on those buttons like other buttons on the site have, that would do the trick to fix this issue.

```
.btn:focus, .btn-primary:focus, .btn-primary.focus {
    background-color: var(--gray-15);
    color: var(--gray-85);
    border-color: var(--gray-85);
    outline: 5px auto -webkit-focus-ring-color;
    outline-offset: -2px;
}
```

**Comment by raisedadead** [comment]
Thanks for reporting and creating the PR. However, the code for this can be found here: https://github.com/freeCodeCamp/auth0-templates/blob/org-tenant/pages/login.html.

If you are still interested in making a PR, can you please make the same on the repo above, specifically to the `org-tenant` branch?

Thanks.

**Comment by tannerdolby** [comment]
@raisedadead Your welcome. Yeah sure thing, I will make the same PR on the repo above, specifically to the org-tenant branch. Thanks for the heads up!

**Comment by raisedadead** [comment]
Looking forward to it. Cheers.

**Comment by tannerdolby** [comment]
Just submitted PR over in `freeCodeCamp/auth0-templates`. Ping for review @raisedadead
