### ISSUE TITLE
Minor Naming inconsistency and Clarification

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#42262]
Challenges
---

1) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-character-in-a-string
2) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-last-character-in-a-string
3) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-to-last-character-in-a-string
4) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/find-the-length-of-a-string

Issue
---
In the first challenge listed (1), we use `Ada Lovelace` as our sample person.
In the second (2) and third (3), we use a non-existent 'Charles Lovelace'. 

**Question 1**:
What do we think about updating (2) and (3) to reference Ada Lovelace instead of this random name?

**Question 2**:
Also, there is at least one camper that got confused and thought we were talking about Linda Lovelace (never heard of her before today).
https://forum.freecodecamp.org/t/varible-name-choice-in-javascript-intro-lesson/462078/2

What do we think about modifying the starter code in all 4 linked challenges to make it painfully obvious that we are *not* talking about a pornographic actress?
```javascript
// Setup
var firstName = "Ada";
var lastName = "Lovelace";

// Only change code below this line
var thirdLetterOfLastName = lastName; // Change this line
```

**Comment by jeremylt** [comment]
It also might be worthwhile to hyperlink Ada Lovelace's name to her wikipedia page to encourage people to go learn about her.

**Comment by lasjorg** [comment]
I guess I'm fine with replacing the name Charles with Ada. Other than that, I really do not see an issue here. Not sure I care much either way.

I will note that any Wikipedia link would have to go on the hint page and not the challenge. We intentionally do not want external links on challenges as it breaks the flow and is just distracting.

**Comment by jeremylt** [comment]
Yeah, I feel most strongly about changing Charles to Ada. It feels like an incomplete old change to the example?

Personally, I do not know how many people will think of a porn star before the world's first programmer, but I wanted to bring it up because we saw it come up on the forum. Consistently using Ada in the example text should help mitigate the (small, in my eyes) potential concern.

**Comment by alirezaghey** [comment]
I would like to do this but thought this may be a good first issue. In the spirit of being welcoming to newcomers, I thought it may be appropriate to first raise this before jumping on it. Let me know ;)

**Comment by RebekahKoon** [comment]
Hi, this is my first time contributing to freeCodeCamp! Let me know if there are any problems with the changes.

Thanks!
