### ISSUE TITLE
Scientific Computing with Python: Probability Calculator: improving test_hat_draw

### ISSUE THREAD

**Issue by mleonelli** [freeCodeCamp/freeCodeCamp#42275]
**Affected page**
https://github.com/freeCodeCamp/boilerplate-probability-calculator

**Your code**
test_hat_draw first test is meant to validate that the submitted code returns a list of strings with the correct draw from the hat. To do so, it expects a list with blue and red in this order, but the draw can actually take any other kind of combination (BB, RB, BR, RR)
```
hat = prob_calculator.Hat(red=5,blue=2)
actual = hat.draw(2)
expected = ['blue', 'red']
self.assertEqual(actual, expected, 'Expected hat draw to return two random items from hat contents.')
```

**Expected behavior**
My proposal is to change the Hat creation and test to invalidate one of the 4 combinations as a "proof" that the code is working properly. I.e. if the hat is create with red=5,blue=**1**, the BB (blue - blue) combination would prove the code wrong. On the other hand any other one should make the test pass

**Screenshots**
![image](https://user-images.githubusercontent.com/4825294/119845848-e9059480-bf09-11eb-9ebc-00feab7b3c34.png)

**System (please complete the following information):**
Browser Name: Firefox
Browser Version: 84.0.1(64 bit)
Operating System: Win10 home 64 bit v2004

**Comment by gikf** [comment]
I've updated link to the boilerplate repository.

Generally I think it's a good idea to add some additional checks here. I recall from some threads on forums, that problems with `draw` method behavior are often revealed further along the road, only because of wrong final result of experiments.

**Comment by mleonelli** [comment]
Hi @gikf, I understood where the challenge is coming from. While in the main.py there is no initialization of random seed, in the unit tests the seed is set.
For this reason, within the `draw` function, the student must not set him/herself the seed but rather rely on the the main program.

I propose then to
1. Add a seed initialization in main.py
2. Add a small paragraph in the assignment to highlight that

**Comment by mleonelli** [comment]
Unless there is a PR coming before, I'll commit one in the next couple of days.
