### ISSUE TITLE
Typing "function" underneath existing Bonfire code crashes browser

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4228]
This issue probably exists somewhere, but adding a function below a bonfire's default code will crash the browser.

Adding a function above a Bonfire's default code doesn't cause any problems.

**Comment by BerkeleyTrue** [comment]
adding a function or adding the keyword `function`?

**Comment by ltegman** [comment]
Can confirm this happens the second `function` is typed as the last code in the editor. Was refactoring the functional challenges to take advantage of the new head/tail spec, but without the final function at the end the page freezes the as soon as a user finishes typing `function` to make the callback.

**Comment by BerkeleyTrue** [comment]
Frak, that is strange. It must be  CodeMirror error (just a guess) since we no longer autorun code.

**Comment by ltegman** [comment]
Okay, so I've been starting to dig into this a little and the problem appears to be coming from CodeMirror's linting. Turning linting off prevents the error.

**Comment by BerkeleyTrue** [comment]
@ltegman Thanks for the insight. Might need to update Codemirror and JSHINT (although I would like to move to eslint but that can wait for another day).

**Comment by bugron** [comment]
This is not an issue anymore, closing.
