### ISSUE TITLE
Moment.js is considered a legacy package and should be replaced with a recommended substitute

### ISSUE THREAD

**Issue by alirezaghey** [freeCodeCamp/freeCodeCamp#42294]
**Affected page**
[https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm](https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm)

The challenge states:
*"Add version "2.14.0" of the "moment" package to the dependencies field of your package.json file."* and adds, "*Note: Moment is a handy library for working with time and dates.*"

Since moment is [officially a legacy project](https://momentjs.com/docs/#/-project-status/) and students are students are just getting familiar with npm and its package system, we are teaching them something that they need to unlearn later on.

**Expected behavior**
I suggest we base the challenge on a recommended substitute for moment. There are a few recommendations by moment itself on the previously linked page.

**Comment by alirezaghey** [comment]
https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/manage-npm-dependencies-by-understanding-semantic-versioning
https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/use-the-tilde-character-to-always-use-the-latest-patch-version-of-a-dependency
https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/use-the-caret-character-to-use-the-latest-minor-version-of-a-dependency
https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/remove-a-package-from-your-dependencies

The above links are all part of the same challenge that follow the introduction of moment js and reference it.
If it is decided that this package should be replace by something else, all of these files need minor edits.

**Comment by gikf** [comment]
Instead of replacing Moment.js in challenges with another package, maybe just remove or change that note? Main point of these challenges is to learn how to use `npm`, this isn't really affected by the fact Moment.js will not be getting any new features.

**Comment by HarshitPatel25** [comment]
Learn how to use npm.

**Comment by raisedadead** [comment]
I am in favour of making these challenges more agnostic. 

Also if we absolutely need examples for using a real-world package, we should create dummy packages and publish them npm for consumption. That we control the lifecycle of the package affecting these challenges getting out dated.

**Comment by moT01** [comment]
I don't think there's an issue that needs to be fixed here. None of it's methods are used in these challenges so nothing will need to be unlearned. As @gikf mentioned, the main point is to learn how to use npm and how versioning and the package.json file work. I think the package used is irrelevant and we could probably leave this be.

Side note - moment is still getting 16.5 million weekly downloads so plenty of projects are still using it.

**Comment by raisedadead** [comment]
We all agree that the challenge is about learning to use npm, so we should probably swap out the packages we use as examples for our own and avoid a discussion around an unrelated need again in the future. 

Closing this as-is may be fine, but IMHO someone will open a fresh issue in future raising the same concerns, which I think we can avoid pretty efficiently by using our packages.

**Comment by nhcarrigan** [comment]
I'd be happy to slap together an example package we can use for this. If we want to go that route, I can set up the repository and package - I assume we'd need to get together to publish under freecodecamp @raisedadead?

**Comment by raisedadead** [comment]
Yes - something like `@freecodecamp/sample-package`

**Comment by nhcarrigan** [comment]
This fell under the radar, but here's a quick fix.

We should update the challenge to ask campers to add version 1.0.0 of `freecodecamp`: https://www.npmjs.com/package/freecodecamp

**Comment by ieahleen** [comment]
> This fell under the radar, but here's a quick fix.
> 
> We should update the challenge to ask campers to add version 1.0.0 of `freecodecamp`: https://www.npmjs.com/package/freecodecamp

What version could be requested for the next few steps
> In the dependencies section of your package.json file, change the version of moment to match MAJOR version 2, MINOR version 10 and PATCH version 2

> In the package.json file, your current rule for how npm may upgrade moment is to use a specific version (2.10.2). But now, you want to allow the latest 2.10.x version.
> 
> Use the tilde (~) character to prefix the version of moment in your dependencies, and allow npm to update it to any new PATCH release.
> 
> Note: The version numbers themselves should not be changed.

> Use the caret (^) to prefix the version of moment in your dependencies and allow npm to update it to any new MINOR release.

Should we maybe publish a new version of the package so to have available for teaching 1.0.0 and like 1.4.23?

**Comment by scissorsneedfoodtoo** [comment]
The current plan is to create and publish a new package under the freeCodeCamp org on NPM (a simple example like Hello World?) and use that in the challenge, rather than the [freecodecamp](https://www.npmjs.com/package/freecodecamp) package, or Moment.js.
