### ISSUE TITLE
Basic Javascript task #45 - not displaying the images

### ISSUE THREAD

**Issue by n01ded** [FreeCodeCamp/FreeCodeCamp#4230]
There seems to be an issue with the last task of the basic Javascript part of the course where the image is not displayed in the .slot div.

![jsissue](https://cloud.githubusercontent.com/assets/15439283/11015968/ea8cb1e8-8572-11e5-8bbd-dd07293bef7e.png)

**Comment by SaintPeter** [comment]
In order to see the images you must click the "Go" button.

Happy coding!
