### ISSUE TITLE
Add section for configuring IntelliJ for running project locally in docs

### ISSUE THREAD

**Issue by Dripcoding** [freeCodeCamp/freeCodeCamp#42319]
**Description:**
I use IntelliJ Idea on Windows 10 with WSL2 to run the project locally.

The specific problem I ran in to was running tests via the IDE instead of the command line. I had to configure IntelliJ to use the version of Node I have installed in WSL2.

This is the error I encountered when trying to run the tests via the IDE:

`CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'jest' is not recognized as an internal or external command,
operable program or batch file.`

**Recommended fix, suggestions:**

I think it would be worth while to add a small section to the WSL set up doc (https://contribute.freecodecamp.org/#/how-to-setup-wsl) for anyone using IntelliJ products.

**Comment by Dripcoding** [comment]
I really liked how the Windows and WSL set up guides were easy to read and follow! I think adding this would lower barrier of entry for people who are using or evaluating IntelliJ IDEs.  

If this change is approved I'd be happy to update this docs :)

**Comment by raisedadead** [comment]
Sure, go ahead and add a line to this area: https://contribute.freecodecamp.org/#/how-to-setup-wsl?id=installing-a-code-editor
