### ISSUE TITLE
 'removedFromMyArray' Typo in [Waypoint: Manipulate Arrays With pop]

### ISSUE THREAD

**Issue by GrahamCressey** [FreeCodeCamp/FreeCodeCamp#4231]
I think there's an error in the output code for this challenge; to correct this the function in the pre-set code should be:

{return 'MyArray = '

not 

{return 'removedFromMyArray = '

So that your answer displayed in the black output box on the left when the correct code is run is aligned to the solution underneath i.e. it wouldn't read "removedFromMyArray" but it would say "myArray = [John, 23]..." and this is aligned to the solution underneath of "myArray should only contain ["John", 23]"

![image](https://cloud.githubusercontent.com/assets/13405230/11016345/8e172110-8576-11e5-987c-f43d93762109.png)

Thank you

Graham

p.s. very much enjoying the challenges. 

Challenge [Waypoint: Manipulate Arrays With pop](http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop#?solution=var%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0Avar%20removedFromOurArray%20%3D%20ourArray.pop()%3B%20%2F%2F%20removedFromOurArray%20now%20equals%203%2C%20and%20ourArray%20now%20equals%20%5B1%2C2%5D%0A%0Avar%20myArray%20%3D%20%5B%22John%22%2C%2023%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20removedFromMyArray%20%3D%20myArray.pop()%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(y%2C%20z)%7Breturn%20'removedFromMyArray%20%3D%20'%20%2B%20JSON.stringify(y)%20%2B%20'%20%26%20removed%20%3D%20'%20%2B%20JSON.stringify(z)%3B%7D)(myArray%2C%20removedFromMyArray)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = [1,2,3];

var removedFromOurArray = ourArray.pop(); // removedFromOurArray now equals 3, and ourArray now equals [1,2]

var myArray = ["John", 23, ["cat", 2]];

// Only change code below this line.

var removedFromMyArray = myArray.pop();

// Only change code above this line.

(function(y, z){return 'removedFromMyArray = ' + JSON.stringify(y) + ' & removed = ' + JSON.stringify(z);})(myArray, removedFromMyArray);

```

**Comment by SaintPeter** [comment]
Confirmed - looks like the output was updated and doesn't match.

**Comment by MartinaCarrington** [comment]
ok i am having a problem with myArray should only contain [["John", 23]]

**Comment by jokerrapeu** [comment]
i get error same with u , pls help

**Comment by texas2010** [comment]
@jokerrapeu 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by OgunniyiOwamamwen** [comment]
THE CODE ANSWER
Manipulate Arrays With pop


// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray = myArray.pop();
