### ISSUE TITLE
Passing the challenge while running a wrong code.

### ISSUE THREAD

**Issue by RawandDev** [freeCodeCamp/freeCodeCamp#42324]
**Affected page**

https://www.freecodecamp.org/learn/responsive-web-design/basic-css/import-a-google-font

**Your code**

```

<style>

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

.red-text {
  color: red;
  
}
h2 {font-family: Lobster;}
p {
  font-size: 16px;
  font-family: monospace;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
<p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>

<a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

<div>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="https://freecatphotoapp.com/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label><br>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
</main>


```

**Expected behavior**

Importing `<link>` must be outside the `<style>` tag not inside it. This code above will pass the test cases even tho the font isn't 
applied and imported inside the `<style>` tag.

**Screenshots**

As you can see the lobster font is not applied to the `h2` tag but it still passes all the tests.
![bad](https://user-images.githubusercontent.com/82733587/120326025-ef708380-c2f0-11eb-921c-decd9b3dbcf2.png)

This is the right implementation of importing a `link` tag
![good](https://user-images.githubusercontent.com/82733587/120326137-10d16f80-c2f1-11eb-9655-ef4506f7b61e.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212 (Official Build) (64-bit)

**Additional context**

**Comment by ojeytonwilliams** [comment]
Thanks for the report @RawandDev, the regex for this one is a bit too permissive.  It should check that the link is not inside the style tags (without using lookbehinds, because we've broken safari often enough recently)
