### ISSUE TITLE
Grammatical / Typo Error in News Section.

### ISSUE THREAD

**Issue by ShekharDhangar** [freeCodeCamp/freeCodeCamp#42346]
Issue :
Grammatical / Typo Error.  In the first line of "How to Find a Project to Contribute to" of "How to Contribute to Open Source Projects – A Beginner's Guide" news. There should be a English word "you" present in the line "Now that know how an open-source project works"

Link to Issue : 
https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/#howtofindaprojecttocontributeto

Suggestion to fix the issue : 
Add a English word "you" in the 1st Line of the said part of the news page.

**If possible, add a screenshot here (you can dr
![Grammatical_Typo_Error](https://user-images.githubusercontent.com/68814457/120638194-73f80900-c48d-11eb-80ba-fadedfc46d87.jpeg)
ag and drop, png, jpg, gif, etc. in this box):**

**Comment by ShekharDhangar** [comment]
Hey, I am new here. Would really appreciate if someone can guide me on how to raise a new issue or any important part of contributing to FreeCodeCamp.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this issue. I have emailed the editorial team at `editorial<at>freecodecamp.org`.

---

If you are interested in how to contribute to freeCodeCamp, then I recommend going through the [Contributors Guide](https://contribute.freecodecamp.org/#/)

Happy coding :)

**Comment by ShekharDhangar** [comment]
Thankyou

**Comment by ShekharDhangar** [comment]
Should I fix this issue?

**Comment by ShaunSHamilton** [comment]
@ShekharDhangar Thank you, for your interest. However, this is not something that can be fixed by contributors, as it requires access to the news platform - it is not a part of this code base.

Feel free to look for open issues with _help wanted_ labels, though.

**Comment by ShekharDhangar** [comment]
Okay Thanks.
