### ISSUE TITLE
I think we broke something with Safari...again.

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#42354]
Challenge: https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/create-a-media-query

Forum Post: https://forum.freecodecamp.org/t/no-idea-why-is-not-giving-me-the-pass/463327

I have only tested this using LambdaTest.

macOS Mojave Safari
![macOS-Mojave-Safari](https://user-images.githubusercontent.com/28780271/120720410-5007e800-c4cc-11eb-99e5-18e74c4a3c31.png)

macOS Mojave Chrome
![macOS-Mojave-Chrome](https://user-images.githubusercontent.com/28780271/120720836-12578f00-c4cd-11eb-99b9-02762bd97033.png)

I assume it's related to https://github.com/freeCodeCamp/freeCodeCamp/pull/42148 but I can't really do much testing with Safari or MacOS (just have a few free minutes on lambda test).

@moT01 can you help take a look at this when you have time?

---

Speaking of which, I really wish we had a deal with one of the cross-browser testing places (BrowserStack, LambdaTest, whatever). It would really help us do better cross-browser testing.

**Comment by moT01** [comment]
Yea, passes in firefox and edge (osx) for me - not passing in Safari. I can try and dig a little deeper at some point here.

**Comment by ojeytonwilliams** [comment]
cc: @ShaunSHamilton

**Comment by ShaunSHamilton** [comment]
Some quick testing on LambdaTest (thanks for the mention @lasjorg ) lead to me seeing this:
![image](https://user-images.githubusercontent.com/51722130/120777179-ee239e80-c51c-11eb-8d01-3032e6799e6d.png)

There is no `conditionText` property on the `CSSMediaRule`. However, the same info appears to be within the `media.mediaText` property.
