### ISSUE TITLE
Use Yarn instead of NPM.

### ISSUE THREAD

**Issue by samarmohan** [freeCodeCamp/freeCodeCamp#42366]
**Is your feature request related to a problem? Please describe.**
NPM is slow and unreliable, Yarn is faster. With Yarn v2, we may not even need node_modules which will save space in local environments.

**Describe the solution you'd like**
Use Yarn v2 instead. We can use Yarn v1 but v2 (berry) is even better and faster.

**Additional context**
#11208 and #11501 were closed in 2016 and the reason was `yarn is unstable`, 5 years have passed and Yarn has (mostly) become the standard.

**Comment by giridhar7632** [comment]
Freecodecamp courses have challenges using npm. So I think npm is more suitable for beginners.

**Comment by samarmohan** [comment]
Yes but this is the website, what we do internally doesn't affect externally. NPM is better for beginners but it is not better for professional sites.

**Comment by raisedadead** [comment]
Thanks for your feedback. We appreciate it.

The issues in the OP have been made in context at that time, there is no point discussing those here. We are going to be using `npm` - it has endured the test of time and our workflows.

We don't care much for the opinionated push for a tool. Our [architecture design decisions](https://www.google.com/search?q=architecture+design+decisions) follow a philosophy for using the right tool for the job, even competing ones if it helps.

Thanks for taking the time.
