### ISSUE TITLE
Personal Library Test#3 GET request passes with no code

### ISSUE THREAD

**Issue by shekine** [freeCodeCamp/freeCodeCamp#42363]
**Affected page**
Add a link to the coding challenge with the problem.

[Personal Library](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/personal-library)

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```js
/*
*
*
*       Complete the API routing below
*       
*       
*/

'use strict';

module.exports = function (app) {

  app.route('/api/books')
    .get(function (req, res){
      //response will be array of book objects
      //json res format: [{"_id": bookid, "title": book_title, "commentcount": num_of_comments },...]
    })
    
    .post(function (req, res){
      let title = req.body.title;
      //response will contain new book object including atleast _id and title
    })
    
    .delete(function(req, res){
      //if successful response will be 'complete delete successful'
    });



  app.route('/api/books/:id')
    .get(function (req, res){
      let bookid = req.params.id;
      //json res format: {"_id": bookid, "title": book_title, "comments": [comment,comment,...]}
    })
    
    .post(function(req, res){
      let bookid = req.params.id;
      let comment = req.body.comment;
      //json res format same as .get
    })
    
    .delete(function(req, res){
      let bookid = req.params.id;
      //if successful response will be 'delete successful'
    });
  
};

```

**Expected behavior**

Given that this is the Replit starter project and the GET route has no code, I expected test no. 3 to fail.

**Screenshots**

If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

**System (please complete the following information):**
 - Device: [PC]
 - OS: [Windows 10]
 - Browser: [chrome]
 - Version: Version 91.0.4472.77 (Official Build) (64-bit)

**Additional context**

I am working through this project and found test 3 passes even before I had written any code. I made a new copy of the Replit starter project and ran the tests to see if I could replicate the issue. Test 3 still passes. The github personal-library.md file shows that it supposedly makes several post requests and a get request, but somehow it passes without GET or POST routes.

```js
async (getUserInput) => {
  try {
    let url = getUserInput('url') + '/api/books';
    let a = $.post(url, { title: 'Faux Book A' });
    let b = $.post(url, { title: 'Faux Book B' });
    let c = $.post(url, { title: 'Faux Book C' });
    Promise.all([a, b, c]).then(async () => {
      let data = await $.get(url);
      assert.isArray(data);
      assert.isAtLeast(data.length, 3);
      data.forEach((book) => {
        assert.isObject(book);
        assert.property(book, 'title');
        assert.isString(book.title);
        assert.property(book, '_id');
        assert.property(book, 'commentcount');
        assert.isNumber(book.commentcount);
      });
    });
  } catch (err) {
    throw new Error(err.responseText || err.message);
  }
};

```

**Comment by gikf** [comment]
It seems asserts are not even run, because promises are not fulfilled. Not sure if this is to be expected, but I'm surprised there isn't timeout like in other tests. I guess internally that doesn't make test not finished, so there's nothing to timeout...?

Adding `await` before `Promise.all(...` or each post request in `a`, `b`, `c`, would make it timeout as expected.
