### ISSUE TITLE
Javascript Slot Machine Reports "Not A Winner" When you Win

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4236]
Challenge [Waypoint: Give your JavaScript Slot Machine some Stylish Images](http://www.freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images#?solution=fccss%0A%20%20function%20runSlots()%7B%0A%20%20%20%20var%20slotOne%3B%0A%20%20%20%20var%20slotTwo%3B%0A%20%20%20%20var%20slotThree%3B%0A%20%20%20%20%0A%20%20%20%20var%20images%20%3D%20%5B%22http%3A%2F%2Fi.imgur.com%2F9H17QFk.png%22%2C%20%22http%3A%2F%2Fi.imgur.com%2F9RmpXTy.png%22%2C%20%22http%3A%2F%2Fi.imgur.com%2FVJnmtt5.png%22%5D%3B%0A%20%20%20%20%0A%20%20%20%20slotOne%20%3D%20Math.floor(Math.random()%20*%20(3%20-%201%20%2B%201))%20%2B%201%3B%0A%20%20%20%20slotTwo%20%3D%20Math.floor(Math.random()%20*%20(3%20-%201%20%2B%201))%20%2B%201%3B%0A%20%20%20%20slotThree%20%3D%20Math.floor(Math.random()%20*%20(3%20-%201%20%2B%201))%20%2B%201%3B%0A%20%20%20%20%0A%20%20%20%20%24('.logger').html('')%3B%0A%20%20%20%20%24('.logger').html('Not%20A%20Win')%3B%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%24(%24('.slot')%5B0%5D).html('%3Cimg%20src%20%3D%20%22'%20%2B%20images%5BslotOne-1%5D%20%2B%20'%22%3E')%3B%0A%20%20%20%20%24(%24('.slot')%5B1%5D).html('%3Cimg%20src%20%3D%20%22'%20%2B%20images%5BslotTwo-1%5D%20%2B%20'%22%3E')%3B%0A%20%20%20%20%24(%24('.slot')%5B2%5D).html('%3Cimg%20src%20%3D%20%22'%20%2B%20images%5BslotThree-1%5D%20%2B%20'%22%3E')%3B%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%20%20%20%20%0A%20%20%20%20if%20(slotOne%20%3D%3D%3D%20slotTwo%20%26%26%20slotTwo%20%3D%3D%3D%20slotThree)%20%7B%0A%20%20%20%20%20%20return%20slotOne%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20if(slotOne%20!%3D%3D%20undefined%20%26%26%20slotTwo%20!%3D%3D%20undefined%20%26%26%20slotThree%20!%3D%3D%20undefined)%7B%0A%20%20%20%20%20%20%24('.logger').html(slotOne)%3B%0A%20%20%20%20%20%20%24('.logger').append('%20'%20%2B%20slotTwo)%3B%0A%20%20%20%20%20%20%24('.logger').append('%20'%20%2B%20slotThree)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20return%20%5BslotOne%2C%20slotTwo%2C%20slotThree%5D%3B%0A%20%20%7D%0A%0A%20%20%24(document).ready(function()%7B%0A%20%20%20%20%20%24('.go').click(function()%7B%0A%20%20%20%20%20%20%20runSlots()%3B%0A%20%20%20%20%20%7D)%3B%0A%20%20%20%7D)%3B%0Afcces%0A%20%0A%0A) has an issue.

User @bflatt72 noted that when you actually win it prints out "Not a Winner", rather than "Your are a Winner" or similar.  Challenge seed needs to be refactored.

My code:
```html
<script>
  function runSlots(){
    var slotOne;
    var slotTwo;
    var slotThree;
    
    var images = ["http://i.imgur.com/9H17QFk.png", "http://i.imgur.com/9RmpXTy.png", "http://i.imgur.com/VJnmtt5.png"];
    
    slotOne = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    slotTwo = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    slotThree = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    
    $('.logger').html('');
    $('.logger').html('Not A Win');
    
    // Only change code below this line.
    $($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');
    $($('.slot')[1]).html('<img src = "' + images[slotTwo-1] + '">');
    $($('.slot')[2]).html('<img src = "' + images[slotThree-1] + '">');
    
    
    // Only change code above this line.
    
    if (slotOne === slotTwo && slotTwo === slotThree) {
      return slotOne; // Problem is probably here.
    }
    
    if(slotOne !== undefined && slotTwo !== undefined && slotThree !== undefined){
      $('.logger').html(slotOne);
      $('.logger').append(' ' + slotTwo);
      $('.logger').append(' ' + slotThree);
    }
    
    return [slotOne, slotTwo, slotThree];
  }

  $(document).ready(function(){
     $('.go').click(function(){
       runSlots();
     });
   });
</script>
 ```

**Comment by faizaanceg** [comment]
Can I take this @SaintPeter   ?

I think we should move these lines below before the last return statement

```
$('.logger').html('');
$('.logger').html('Not A Win');
```

**Comment by SaintPeter** [comment]
@faizaanceg It's all yours!  Just test it on a local instance before you submit a PR, or specifically mention that you have not when you do.
