### ISSUE TITLE
CSSHelp Features and Bugs

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#42373]
**Reason for this issue**:
- Documenting quirks and issues with the CSSHelp class

**Quirks** _(will not fix)_
- Testing in JSDOM results in whitespace formatting being taken through to computed values. [Example](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/utils/css-help.test.ts#L74)
- Colour values are computed into `rgb`. Example: `#000` -> `rgb(0, 0, 0)`
  - **Note**: Named colours are not computed. Example: `red` -> `red`
- Custom CSS variable property values are not computed. Example: `#000` -> `#000`
- Custom CSS variable property values come with untrimmed whitespace. Example:
```js
CSSHelp(document).getStyleDeclaration('selector')?.getPropertyValue('--custom-variable') === " #000"
```

**Bugs** _(will fix)_
- [x] Safari does not have `<CSSMediaRule>.conditionText`. Ref: https://github.com/freeCodeCamp/freeCodeCamp/issues/42354#issuecomment-854505895
  - Will likely only rely on `media.mediaText` property, as `conditionText` is computed from this.

**Feature Requests** 🤷‍♂️ 
- [x] Calculated values can contain whitespace (not `\t\r\n`). Example:
```css
selector {
  background: linear-gradient(  var(--building-color1 ) ,
      var(--window-color1)
    );
```
```js
getStyleDeclaration('selector')?.background === "linear-gradient( var(--building-color1 ) , var(--window-color1) )"
```
- [x] This helper should be able to select out only the CSS defined in the editor, but testing needs to be done to confirm external stylesheets will not end up being selected. (related: #42356 )

**Comment by ShaunSHamilton** [comment]
@nhcarrigan Your thoughts on a fix for `Calculated values can contain whitespace (not \t\r\n).` would be appreciated?

My thinking is to just `.replace(/\s+/g, "")`. Reasoning: The value is already computed. So, we can rely on the fact that if a Camper were to write something incorrect (e.g. `var(-- building-color 1)`), the CSS parser would not take it as valid, and not allow the property to contain a value.

Example code:
```css
selector {
  background: linear-gradient(  var(--building-color1 ) ,
      var(--window-color1)
    );
}
```
Test with suggested fix:
```js
assert.equal(getStyleDeclaration('selector')?.background, 'linear-gradient(var(--building-color1),var(--window-color1))');
```
Test without suggested fix:
```js
assert.match(getStyleDeclaration('selector')?.background, /linear-gradient(\s*var(\s*--building-color1\s*),\s*var(\s*--window-color1\s*)\s*)/);
```

**Comment by ojeytonwilliams** [comment]
> Custom CSS variable property values come with untrimmed whitespace. Example:

I thought CSS ignored surrounding whitespace and "background: red", "background: red " and "background:red" all being equivalent.  Don't we want the helper to treat values the same way?

**Comment by ShaunSHamilton** [comment]
> Don't we want the helper to treat values the same way?

Yes. But this has to do with **custom CSS variable** property values. `background` is not a custom CSS property. We cannot control this parser fact _unless we alter the prototype_ 😉 . Also, these values are accessible through the prototype function `getPropertyValue` -> not our own helper.

**Comment by ojeytonwilliams** [comment]
Yeah, sure.  We don't need to alter the prototype, though, we could just wrap the function.  Anyways, I see your point - custom properties really are just text until they are used by `var(--custom-property)`.  So, if we're writing tests to see what the user put in their custom properties, that's what we have to use.

Not to get too deep into the weeds, but if I wanted to see how a property is used, can I make use of the helpers?

```css
body {
  --custom-stuff:   blue
}

div {
  color: var(--custom-stuff)
}
```

How would I check that `--custom-stuff` is in the div selector and `color` is `blue` ?

**Comment by ShaunSHamilton** [comment]
>How would I check that --custom-stuff is in the div selector and color is blue ?

```js
const h = new __helpers.CSSHelp(document);
assert.equal(h.getStyleDeclaration('div')?.color, "var(--custom-stuff)");
assert.equal(h.getStyleDeclaration("body")?.getPropertyValue("--custom-stuff").trim(), "blue");
```

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by ShaunSHamilton** [comment]
@prsmahajan Thank you, for our interest in contributing. However, this is not an open issue for contribution (as indicated by the _help wanted_ label). It is for discussing the use of the CSSHelp class.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by prsmahajan** [comment]
Thank you but I will try my best to be a part of FCC.

**Comment by prasad1004** [comment]
🙌

**Comment by moT01** [comment]
Are we still wanting to make some updates to this @ShaunSHamilton?

**Comment by ShaunSHamilton** [comment]
@moT01 The only thing I would want done is this helper should be able to ignore _external_ stylesheets (e.g. Darkmode Browser Extensions), but will require some tinkering, and potentially adding something unique to the `styles` appended to the iframe.

**Short:** I would like this to stay open, for now. What needs to change is:
https://github.com/freeCodeCamp/freeCodeCamp/blob/5de0aae5da35927042a8ad5565b6b7eca0a95338/client/src/utils/css-help.ts#L95-L103

**Comment by ShaunSHamilton** [comment]
Closed by https://github.com/freeCodeCamp/freeCodeCamp/pull/46000
