### ISSUE TITLE
"Your solution should not use the ... method" test can be deceived with eval

### ISSUE THREAD

**Issue by theogom** [freeCodeCamp/freeCodeCamp#42381]
**Bug**

In the "JavaScript Algorithms and Data Structures" section, challenges with the "Your solution should not use the ... method" test can be done with the undesired method using eval.

Indeed, the regex can be deceived using eval and string concatenation.

**Example**

For instance, the method ``Array.prototype.flat`` should not be used to solve the challenge [Steamroller](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller). The regex checking this is :

```
code.match(/\.\s*flat\s*\(/)
```

And it can be deceived with the following :

```
eval('arr.fl' + 'at(Infinity)')
```

**Expected behavior**

The undesired methods should be impossible to use in any way.

**Comment by ShaunSHamilton** [comment]
Hello there,

There will always be ways to get around the tests. However, if someone has gone to the lengths described in this issue to get around them, then they show little-to-no intent to use the freeCodeCamp lesson to learn the intended topic. As such, the learner is either more adept in JavaScript than expected at this point in the curriculum, or _shooting themselves in the foot_ by not following instructions.

Whilst we do often improve the tests, as time goes on, we cannot write tests for every use case.

As such, thank you, for taking the time to open this, but I am going to close it as a non-issue, and a _won't fix_. I hope this makes sense.

Happy coding.
