### ISSUE TITLE
Regex test for hardcoding matches other numbers in function body

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#42386]
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array

Forum: https://forum.freecodecamp.org/t/should-not-be-hard-coded-test-failure/463741

Closed issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/39396

The regex should at least do an exact match for `23569` and not just any part of the numbers.

```
var globalArray = [5, 6, 3, 2, 9];

function nonMutatingSort(arr) {
// Only change code below this line
  return arr.slice(0).sort((val1, val2) => (val1 - val2));
// Only change code above this line
}

nonMutatingSort(globalArray);
```

The test:
`assert(!nonMutatingSort.toString().match(/[23569]/g));`

**Comment by awu43** [comment]
> The regex should at least do an exact match for `23569` and not just any part of the numbers.

This could be extended to match any number between square brackets as hardcoding (`\[.*?\d.*?\]`), though this will match a false positive on a more convoluted solution like
```js
return [...arr.slice().sort(val1, val2 => val1 - val2)];
```
