### ISSUE TITLE
Logging in by email redirects to main.css

### ISSUE THREAD

**Issue by Cylocation** [FreeCodeCamp/freecodecamp#424]
I was logging in at http://www.freecodecamp.com/email-signin and when I clicked login it sent me to  http://www.freecodecamp.com/css/main.css
The login was successful, and when I went to the homepage by url it worked fine.

I was using chrome browser in case that helps.

**Comment by terakilobyte** [comment]
I was able to replicate this bug and addressed the issue as part of pr #426.
