### ISSUE TITLE
Cannot get this work !

### ISSUE THREAD

**Issue by Shehab-Eltawel** [FreeCodeCamp/FreeCodeCamp#4240]
Challenge [Waypoint: Target the same element with multiple jQuery Selectors](http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors#?solution=fccss%0A%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22button%22).addClass(%22animated%22)%3B%0A%20%20%20%20%24(%22.btn%22).addClass(%22shake%22)%3B%0A%20%20%20%20%24(%22%23target1%22).addClass(%22btn-primary%20animated%20shake%22)%3B%0A%0A%0A%20%20%7D)%3B%0Afcces) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
$(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary animated shake");


  });
</script>
```
When I submit the code, it gives me error saying: Your #target1 element should have the classes animated‚ shake and btn-primary. 

am confused !

**Comment by ltegman** [comment]
All the HTML code that constructs the page is missing from your editor, so there is no `#target1` anywhere on the page. If you press the restart button you can get the HTML back.

Closing as not an issue with the tests.

Thanks and happy coding!

**Comment by idebtor** [comment]
It seems that the 5th check point as shown below has a conflict with the instruction above.
"Your #target1 element should have the classes animated‚ shake and btn-primary." 

Also "the restart button" mentioned above by Itegman Collaborator is not well understood. I don't figure out where that button is. 
Blessings,
(a debtor)<><

**Comment by ltegman** [comment]
Sorry, I meant the reset button. It's right below the run tests button on the left. The point of this lesson is to illustrate how multiple different kinds of jquery selectors can all effect the same element. Since `#target1` is also a `button` and has a class of `.btn` adding one class per selector will result in `#target1` having all three classes that you added.

**Comment by idebtor** [comment]
Wow! I am impressed how fast you responded! You are running a super web site! 
I understand that #target1 has three classes in result even though you specified only btn-primary literally. Then the following code pass the 5th check point, right? But it does not pass the test.  That is the problem that many people are experiencing. 
    $("button").addClass(animated);
    $(".btn").addClass(shake);
    $("#target1").addClass(btn-primary);
Once again, I really appreciate your prompt response, great WORK and Services. I am going to recommend this freecodecamp to my students.
Blessings, 
(a debtor)<><

**Comment by ltegman** [comment]
Glad you're enjoying using FreeCodeCamp! The code you have is correct and will work if you add quotes around the argument you're passing into addClass. You need to be passing in a string value :smile:

**Comment by idebtor** [comment]
Oops! 

Thank you again. There must be many people like me who are really appreciating your work here. ^^
Blessings,
(a debtor)<><

**Comment by Shehab-Eltawel** [comment]
I just added button#target1 element to the body and worked perfectly.  Thanks folks for the amazing work.
