### ISSUE TITLE
Discussion Regarding Backticks and Translations

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#42421]
Continuing [this discussion](https://github.com/freeCodeCamp/freeCodeCamp/pull/42403#discussion_r647322903):

We are re-assessing our approach for keywords such as `string`, and whether to wrap them in code tags and leave them as "do not translate" or take another approach. Based on that discussion, some ideas have been pitched:

- Leave keywords in code tags, allow translators to "save anyway" when they need to be translated.
- Remove code tags from keywords.

Would love to hear some thoughts from our current translators and proofreaders on which approaches make the most sense for you.

**Comment by ieahleen** [comment]
I would agree with @RafaelDavisH that having translators decide case by case may have confusing consequences, and better leave code tags as to not translate, but changing the original text if the code tags are not useful.

Also I would agree that if it's not written code then it doesn't need backticks, better having some less text in backticks and making translation less difficult

**Comment by ojeytonwilliams** [comment]
My high level take is that allowing the translators more freedom will make it possible for them to produce the highest quality translations.  However, Nick and Rafa raised good, practical points about consistency.  I think we do want to make it easier to make decent translations, even if that makes it harder to make great ones.

If we're in the happy situation where a language has lots of contributors and proofreaders, they could be encouraged to have 'in house' rules about what works best for them.  In other cases, it's probably safer to just recommend they follow the existing guidelines.

Regarding the existing English text, honestly they should not have code tags around anything that's not actually code. If the translation process (e.g. @ieahleen going through things!) uncovers situations where the code tags shouldn't be there, then we can and should change them.

**Comment by RafaelDavisH** [comment]
This is an example where the title of the Challenge doesn't have the keyword 'main' wrapped in code tags, but later it is. Here we decide to translate the word but also include it in parentheses in English.

https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/20254/en-esem/130#601686

<img width="488" alt="Screen Shot 2021-06-09 at 12 09 07 PM" src="https://user-images.githubusercontent.com/6822714/121414504-8e156980-c91b-11eb-9d65-0e6e324b0e85.png">
 
 This specific string makes sense to translate the word 'main' but not down the challenge since is a semantic element.
 
 Now, so this is the opposite approach argument: Should 'main' be wrapped in this string? NO it shouldn't. 
 
 Removing code tags or allowing translators' to decide, when some translators might not be familiar with programming syntax, it will be more a problem than a solution. IMHO

**Comment by ieahleen** [comment]
The case that started this discussion was a "should return a number" (or other data type), which jumped to attention as I had just come accross various almost identical sentences where `number` was not in backticks, and in that challenge it was, so I made the PR for consistency reasons.

I don't think I would have made the PR if it wasn't for both versions of the sentence existing.

**Comment by RafaelDavisH** [comment]
> I think we do want to make it easier to make decent translations, even if that makes it harder to make great ones.

I don't agree with this statement. We CAN have great translations regardless of having certain word wrapped. It will be challenging, but it is 100 percent doable. Programming languages' syntax are in English, and we will not find some words in our native world languages, and IMO that's okay. It doesn't make these decent translations.

**Comment by ieahleen** [comment]
There is a bit of everything, and the inconsistency usage is huge
Example
> `For example, computers distinguish between numbers, such as the number <code>12</code>, and <code>strings</code>, such as <code>"12"</code>, <code>"dog"</code>, or <code>"123 cats"</code>, which are collections of characters.`

Here `numbers` is not in code tags, while `strings` is

**Comment by moT01** [comment]
There doesn't seem to be a blanket solution for this. We are going to have to handle these on a case-by-case basis I think. If there are still concerns, feel free to bring them up and this can be reopened.
