### ISSUE TITLE
stuck in understanding

### ISSUE THREAD

**Issue by kranthi123** [FreeCodeCamp/FreeCodeCamp#4243]
Challenge [Waypoint: Understand Boolean Values](http://www.freecodecamp.com/challenges/waypoint-understand-boolean-values#?solution=function%20welcomeToBooleans()%20%7B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20false%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A%0AwelcomeToBooleans()%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function welcomeToBooleans() {

// Only change code below this line.

  return false;

// Only change code above this line.
}

welcomeToBooleans();


```

**Comment by awesomeaniruddh** [comment]
@kranthi123 please describe your issue in more detail.

**Comment by SaintPeter** [comment]
@kranthi123 - I encourage you to stop by the help chat room and ask for assistance there.
You can find the chat room at https://gitter.im/FreeCodeCamp/Help

**Comment by ltegman** [comment]
Closing this since there is no issue described. Please feel free to reopen with further details!

Thanks and happy coding!

**Comment by frogshelp** [comment]
i can help u got it right  but u forgt to change the return false; and rewrite it at the bottom of all of it with the {} brackets  and it should pass  so basically take and write it like this 
function welcomeToBooleans() {
  return false;;  <-- change that from false 
}
