### ISSUE TITLE
Rename APIs and Microservices to include "Backend"

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#42444]
Quincy requested that we rename the APIs and Microservices cert to include "Backend" - I don't recall if there was a specific title recommended, but "Backend API's and Microservices" should work I think.

**Comment by ShaunSHamilton** [comment]
If I am not mistaken, the idea was to completely remove the mention of _Microservices_.

**Comment by moT01** [comment]
That might be right - I'm not sure. I'll see if I can get something more concrete from him.

**Comment by heysujal** [comment]
Please assign me this issue

**Comment by ShaunSHamilton** [comment]
@heysujal 
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by heysujal** [comment]
@ShaunSHamilton Got it. Thanks for the info.

**Comment by moT01** [comment]
Hey @heysujal, or whoever ends up working on this - we should be sure to rename this on the settings page as well. In the same area as these: https://github.com/freeCodeCamp/freeCodeCamp/issues/42502

**Comment by heysujal** [comment]
@moT01  I am not allowed to work on it because

> An issue with the help wanted or first timers only label is open for contribution.

**Comment by moT01** [comment]
Sorry, sometimes we forget to change the labels. Feel free to give it a go if you want.

**Comment by heysujal** [comment]
Assign me this , I will be working on it.

**Comment by Sembauke** [comment]
> Assign me this , I will be working on it.

Hey @heysujal,
We do not assign issues, feel free to work on this though.
The first PR or the PR with the highest quality will be merged.

Happy contributing

**Comment by heysujal** [comment]
Hey I am facing a problem , there are many files where "APIs and Microservices" is used . Should I replace it with "Back End Development and APIs Certification" everywhere ?
![something like this](https://user-images.githubusercontent.com/55016909/122101352-d1973880-ce31-11eb-873b-395db4443f0b.JPG)

**Comment by moT01** [comment]
I'm not sure exactly what all needs to be changed - you should only need to change what is displayed, the rest can probably be left alone for now. Also, only change English files - don't worry about the other languages. Looking at your list, I would say to change the `README.md` file, the English `intro.json` file, and the `Certification.js` file - not sure on the `ShowProjectLinks.js` file, I would have to dig into it more. There may be others not in the image.

**Comment by moT01** [comment]
Also, it may be worth following the conversation/progress on [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/42511) - looks like a few of the changes might be a little tricky.

**Comment by heysujal** [comment]
> I'm not sure exactly what all needs to be changed - you should only need to change what is displayed, the rest can probably be left alone for now. Also, only change English files - don't worry about the other languages. Looking at your list, I would say to change the `README.md` file, the English `intro.json` file, and the `Certification.js` file - not sure on the `ShowProjectLinks.js` file, I would have to dig into it more. There may be others not in the image.

yes there are more of them , and yes I am following that progress of PR as well. Meanwhile I will make changes only in the files you are sure about.
