### ISSUE TITLE
'npm run first-time' not working

### ISSUE THREAD

**Issue by vtamara** [FreeCodeCamp/FreeCodeCamp#4244]
I can install (and even run without seed), but README.md says:
```
# Initialize Free Code Camp
# This will seed the database for the first time.
# This command should only be run once.
npm run first-time
```

However when I run it, it says:

```
kadosh$ npm run first-time   
npm ERR! OpenBSD 5.7
npm ERR! argv "node" "/usr/local/bin/npm" "run" "first-time"
npm ERR! node v0.10.35
npm ERR! npm  v3.3.10

npm ERR! missing script: first-time
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vJtamara/comp/freecodecamp/FreeCodeCamp/npm-debug.log
```

**Comment by faizaanceg** [comment]
Hmm. where are you running the script from? It should run in the folder which contains the package.json file

You can also run this instead: 
```
npm run create-rev && echo '\n\nseeding database\n\n' && node seed && node seed/nonprofits
```

**Comment by vtamara** [comment]
Thank you. It didn't work either.   I upgraded node from 0.10.38 to 0.10.40 (default version of node.js in OpenBSD 5.8). Cloned again and followed installation instructions (anyway I had to do ```sudo npm install bower -g``` and ```sudo npm install gulp -g").  

Running from directory with package.json:

```
npm run create-rev

> freecodecamp@0.1.0 create-rev /home/vJtamara/comp/freecodecamp/FreeCodeCamp
> test ! -e server/rev-manifest.json && echo '

creating manifest

' && touch server/rev-manifest.json && echo '{}' >> server/rev-manifest.json


npm ERR! OpenBSD 5.7
npm ERR! argv "node" "/usr/local/bin/npm" "run" "create-rev"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 create-rev: `test ! -e server/rev-manifest.json && echo '
npm ERR! 
npm ERR! creating manifest
npm ERR! 
npm ERR! ' && touch server/rev-manifest.json && echo '{}' >> server/rev-manifest.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 create-rev script 'test ! -e server/rev-manifest.json && echo '
npm ERR! 
npm ERR! creating manifest
npm ERR! 
npm ERR! ' && touch server/rev-manifest.json && echo '{}' >> server/rev-manifest.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     test ! -e server/rev-manifest.json && echo '
npm ERR! 
npm ERR! creating manifest
npm ERR! 
npm ERR! ' && touch server/rev-manifest.json && echo '{}' >> server/rev-manifest.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vJtamara/comp/freecodecamp/FreeCodeCamp/npm-debug.log
```


I guess it has to do with the port of node.js to OpenBSD.

Anyway I did from command line:
```
$ touch server/rev-manifest.json
$ echo '{}' >> server/rev-manifest.json 
```
And then  it worked (even with problems with bufferutils)
```
sudo npm install node-gyp -g
npm install react-dom
node seed
node seed/nonprofits
gulp
```

Thank you.

**Comment by ltegman** [comment]
FreeCodeCamp currently runs on and recommends node 4.2.X. I don't know if that would have solved your problem, but I highly recommend updating (or using nvm to install multiple versions) because 4.2.X is the current LTS version of node.

**Comment by anthonygore** [comment]
I've got the same problem. The fix above didn't work:

12 error Darwin 15.0.0
13 error argv "/usr/local/Cellar/nvm/0.29.0/versions/node/v4.2.2/bin/node" "/usr/local/opt/nvm/versions/node/v4.2.2/bin/npm" "run" "first-time"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error freecodecamp@0.1.0 first-time: `npm run create-rev && echo '
17 error
17 error seeding database
17 error
17 error ' && node seed && node seed/nonprofits`
17 error Exit status 1
18 error Failed at the freecodecamp@0.1.0 first-time script 'npm run create-rev && echo '
18 error
18 error seeding database
18 error
18 error ' && node seed && node seed/nonprofits'.
18 error This is most likely a problem with the freecodecamp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run create-rev && echo '
18 error
18 error seeding database
18 error
18 error ' && node seed && node seed/nonprofits
18 error You can get their info via:
18 error     npm owner ls freecodecamp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
