### ISSUE TITLE
Translation: backticked strings loose spaces at the end

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#42455]
I think we have a small issue with translations and spaces at the end of strings in backticks
In at least one challenge there is a space at the end of a string, (the string `This is the start. `)
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator.md
in the english challenge it is kept
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator

It doesn't appear in the string to translate on crowdin tho

![image](https://user-images.githubusercontent.com/26656284/121772514-12fbbf80-cb76-11eb-9bb5-f0679e30548a.png)

in consequence the spanish and chinese translation don't have that space

https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator
https://chinese.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator

The next challenge has the same issue.
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-the-plus-equals-operator

**Comment by ojeytonwilliams** [comment]
Good catch @ieahleen.  I think this is a bug with Crowdin, unfortunately - it should definitely be preserving all the spaces.

As a workaround we could try using `<pre><code>This is the start. </code></pre>` and see how it handles that.

**Comment by patlehmann1** [comment]
I can open a PR for these changes, if needed.

**Comment by ieahleen** [comment]
@patlehmann1 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
