### ISSUE TITLE
Null Error 

### ISSUE THREAD

**Issue by Sammi-93** [FreeCodeCamp/FreeCodeCamp#4245]
Challenge [Bonfire: Falsy Bouncer](http://www.freecodecamp.com/challenges/bonfire-falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don%27t%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20%0A%20%20%20%20var%20myArray%3D%5B%5D%3B%0A%20%20%20%20%20%20for(var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20if(arr%5Bi%5D%20%3D%3D%3D%20false%20%7C%7C%20arr%5Bi%5D%20%3D%3D%3D%20null%20%7C%7C%20arr%5Bi%5D%20%3D%3D%3D%20%22%22%20%7C%7C%20arr%5Bi%5D%20%3D%3D%3D%200%20%7C%7C%20arr%5Bi%5D%20%3D%3D%3D%20undefined%20%7C%7C%20arr%5Bi%5D.NaN%20)%0A%20%20%20%20%20%20%20%20%20%20continue%3B%0A%20%20%20%20%20%20%20else%20myArray.push(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20return%20myArray%3B%0A%7D%0A%0Abouncer(%5Bfalse%2C%20null%2C%2078%2C%20NaN%2C%20undefined%2C%20%22%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  
    var myArray=[];
      for(var i=0;i<arr.length;i++){
      if(arr[i] === false || arr[i] === null || arr[i] === "" || arr[i] === 0 || arr[i] === undefined || arr[i].NaN )
          continue;
       else myArray.push(arr[i]);
        
    }
    
  
  
  
  
  
  
  return myArray;
}

bouncer([false, null, 78, NaN, undefined, ""]);

```

**Comment by SaintPeter** [comment]
The problem, in part, is that `arr[i].NaN` is not a valid function.  It would evaluate to `NaN.NaN` which is not a thing.

You will want to use the `Boolean` function, as suggested, to solve this problem.  There is no need to compare any of the elements to anything with the `===` operator when `Boolean` will automatically convert truthy and falsy values to true and false respectively.

Closing as this is not a bug in the Bonfire.  If you need code help, please try the /HelpBonfire chat room: https://gitter.im/FreeCodeCamp/HelpBonfires

**Comment by Sammi-93** [comment]
Thanks man
