### ISSUE TITLE
Comma-separated const declarations not accepted (Redux)

### ISSUE THREAD

**Issue by lincore81** [freeCodeCamp/freeCodeCamp#42460]
**Affected page**
https://www.freecodecamp.org/learn/front-end-libraries/redux/use-const-for-action-types

**Expected behavior**
The following two code snippets are both correct and semantically equivalent js, but one passes all tests and the other does not. Either both should pass or both should fail.

Passes:
```
const LOGIN = `LOGIN`;
const LOGOUT = `LOGOUT`;
```
Fails:
```
const LOGIN = `LOGIN`
    , LOGOUT = `LOGOUT`;
```

Declaring multiple comma separated const's fails this test:
```LOGIN and LOGOUT should be declared as const values and should be assigned strings of LOGIN and LOGOUT.```

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
const LOGIN = 'LOGIN'
    , LOGOUT = 'LOGOUT';

const defaultState = {
  authenticated: false
};

const authReducer = (state = defaultState, action) => {

  switch (action.type) {
    case LOGIN: 
      return {
        authenticated: true
      }
    case LOGOUT: 
      return {
        authenticated: false
      }

    default:
      return state;

  }

};

const store = Redux.createStore(authReducer);

const loginUser = () => {
  return {
    type: LOGIN
  }
};

const logoutUser = () => {
  return {
    type: LOGOUT
  }
};
```

**System (please complete the following information):**
 - Browser: Firefox 90.0b6

**Comment by Nirajn2311** [comment]
The test currently checks for two separate `const` declarations. You can view it here - [Use const for action types](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/03-front-end-libraries/redux/use-const-for-action-types.md)

I think the regex can be updated to fix this.

**Comment by patlehmann1** [comment]
I can grab this, if no one else is working on it.

**Comment by Nirajn2311** [comment]
Hi @patlehmann1, any issue with the help wanted or first timers only label is open for contribution. So yeah you can start working on it.
