### ISSUE TITLE
Missing period at the end of the third sentence.

### ISSUE THREAD

**Issue by stephanduesterhoeft** [freeCodeCamp/freeCodeCamp#42479]
**Affected page**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```




```

**Expected behavior**
There should be a period at the end of the third sentence (Finally ...).

**Screenshots**
![Screen](https://user-images.githubusercontent.com/57948566/121898144-5fd0c900-cd23-11eb-8cee-fd87caae3c32.jpg)

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this issue. We can add a period (`.`) at the end.

Here is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list.md

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
