### ISSUE TITLE
bug: Curriculum test regex does not cover some code formats

### ISSUE THREAD

**Issue by alirezaghey** [freeCodeCamp/freeCodeCamp#42473]
**Affected page**
[Affected page](https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/implementation-of-social-authentication-ii)

**Your code**
```js
  passport.use(
    new GithubStrategy(
      {
        clientID: process.env.GITHUB_CLIENT_ID,
        clientSecret: process.env.GITHUB_CLIENT_SECRET,
        callbackURL:
          "https://myapplication.myId.repl.co/auth/github/callback",
      },
      (accessToken, refreshToken, profile, cb) => {
        console.log(profile);
      }
    )
  );
```
*The callback url is redacted.*

**Expected behavior**
I expected this code to pass the tests. But it did not.

**System (please complete the following information):**
 - Device: [Laptop]
 - OS: [Ubuntu 20.4]
 - Browser: [Opera]
 - Version: [77]

**Additional context**
The third test `GitHub strategy should be setup correctly thus far.` didn't pass. So, I ran FCC on my local computer and checked the tests on the page. The first regex test is as follows:
```js
      assert.match(
        data,
        /passport\.use.*new GitHubStrategy/gi,
        'Passport should use a new GitHubStrategy'
      );
```
The regex won't pass if `new GitHubStrategy` is on a new line because `.` matches all characters except for the new line.
When I replaced `.` with `[\s\S]` the tests passed.
So I think we should change this test to the following:
```js
      assert.match(
        data,
        /passport\.use[\s\S]*new GitHubStrategy/gi,
        'Passport should use a new GitHubStrategy'
      );
```
My reasoning is that the correctness of a solution should not depend on formatting. Especially when the formatting is not something very abnormal.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. In general, we need to find a better way of testing these challenges without using RegEx, as mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/39675

As for this issue, a quick-fix could be as you mentioned, but, I might even just make the test to use the `s` flag:
```
/passport\.use.*new GitHubStrategy/gis,
```

---


An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by aileenpalafox** [comment]
Hello, @ShaunSHamilton. Can I do this? I understand that I just need to change `/passport\.use.*new GitHubStrategy/gi,` to this `/passport\.use[\s\S]*new GitHubStrategy/gi,`, right?
I just didn't get this part: "make the test to use the s flag".

**Comment by ShaunSHamilton** [comment]
Hey @aileenpalafox . Thank you, for your interest in contributing.
> I just didn't get this part: "make the test to use the s flag".

The issue with the current test RegEx is the `.*` does not match new lines. In JavaScript RegEx, there is an [s flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags) which allows `.` to match new lines.

Hope this clarifies

**Comment by aileenpalafox** [comment]
Yes, thank you @ShaunSHamilton! 
I've another question, the only way to try these regex tests is by passing the url with the code as if you were someone trying to do the challenge, or does freeCodeCamp makes specific tests for this? 
Like tests to try the challenge test or something like that.

**Comment by ShaunSHamilton** [comment]
> passing the url with the code as if you were someone trying to do the challenge, or does freeCodeCamp makes specific tests for this?

@aileenpalafox Unfortunately, we currently have nothing to help test the backend content - you will need to have the project and code, and build freeCodeCamp locally with the changes to test.
Do remember, this section of the curriculum links all the code needed to pass the current tests.

**Comment by aileenpalafox** [comment]
OK, I'll see if a can give it a try, then! Thank you :)

**Comment by aileenpalafox** [comment]
Hey @alirezaghey, @ShaunSHamilton so I tried it out and the test actually passed without needing to modify anything! 
I made a deploy in Heroku: https://aileen-freecodecamp.herokuapp.com/
Based on this [forked repo](https://github.com/aileenpalafox/boilerplate-advancednode ) for the challenge.
I just modified some files in the repo to see that the first tests of the challenge pass (i.e. try the previous heroku url [here](https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/set-up-passport))
Then skipped some steps and go ahead to modify the part of code that alirezaghey said that wasn't passing the tests.
I tried with both codes: the one provided by the [solution](https://gist.github.com/camperbot/ff3a1166684c1b184709ac0bee30dee6) and the one provided by alirezaghey and it worked just fine.
The file with the code that is being tested is right [here](https://github.com/aileenpalafox/boilerplate-advancednode/blob/master/auth.js), as you would see is the same code provided in this issue.

Here's a screenshot of the results.
<img width="858" alt="Screen Shot 2021-06-24 at 7 24 31 PM" src="https://user-images.githubusercontent.com/22950294/123360739-aba12080-d522-11eb-81cb-8682ee08ad01.png">

**Comment by alirezaghey** [comment]
Hi @aileenpalafox 
Are you sure you haven't a false positive produced by the [commented out](https://github.com/aileenpalafox/boilerplate-advancednode/blob/master/auth.js#L29-L38) `GithubStrategy`?
Neither of the regexes can differentiate between commented and uncommented code.

**Comment by aileenpalafox** [comment]
You're totally right, @alirezaghey! I completely forgot about that, sorry. I delete the comment and now the test is not passing. Tomorrow will be trying the fix both of you suggested. Thank you for your response!
