### ISSUE TITLE
HTML/CSS WP-12 requires clarification

### ISSUE THREAD

**Issue by h0nd0** [FreeCodeCamp/FreeCodeCamp#4249]
The end of this way point reads:
>Create a second p element with the following kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

>Then, **_inside your ```<style>``` element, set the font-size of all p elements to 16 pixels._**

The last way point task reads:
>**_Give elements with the red-text class a font-size of 16px._**

I believe this requires clarification.  Is it the **_```<p>```_** element **or** the **_.red-text_** **or** both which require the font-size to be set to 16px?  If the **_.red-text_** font-size is set to 16, it will also impact the **_```<h2>```_** tag.

**Comment by ltegman** [comment]
Thanks for the report. This was recently resolved by PR #4225 and should hopefully be deployed to the production website soon.

Thanks and happy coding!
