### ISSUE TITLE
There should be consistent styling for Field Guide pages

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#425]
This page in particular uses much smaller font than other pages seem to

http://www.freecodecamp.com/field-guide/how-do-free-code-camp's-nonprofit-projects-work

**Comment by JesseNoBata** [comment]
Hi, 
The Headings seem to alternate between H2 and H3, should these be reversed mayhap?

**Comment by phoenixstormcrow** [comment]
This issue is related to a question I had about authoring field guides: why are parts of the text which semantically should probably be paragraphs marked up using `<h3>` tags? How is this markup generated?

**Comment by QuincyLarson** [comment]
I thought the h3 looked better than p, but we can use p and style it later if we need to. Google will like p better. I've made the changes and will push the release tomorrow.
