### ISSUE TITLE
Bonfire allows use of str.prototype.repeat.

### ISSUE THREAD

**Issue by shadowfool** [freeCodeCamp/freeCodeCamp#4250]
Challenge [Bonfire: Repeat a string repeat a string](http://www.freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string#?solution=function%20repeat%28str%2C%20num%29%20%7B%0A%20%20ans%20%3D%20%22%22%3B%0A%20%20if%28num%20%3C%3D%200%29%7B%0A%20%20%20%20return%20%22%22%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20str%20%2B%20repeat%28str%2C%20num%20-%201%29%3B%0A%20%20%7D%0A%7D%0A%0Arepeat%28%22*%22%2C%203%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I think this could end up being misleading to beginner programmers who don't realize that repeat is a preexisting function in JS that takes a number as its argument.  Is there a way to restrict the use of repeat for this exercise? I think this would be very valuable to have someone create their own repeat function either through loops or recursion. 

My code:

``` javascript

function repeat(str, num) {
  if(num < 0){
    return "";
  }
  return str.repeat(num);
}

```

**Comment by dmfarcas** [comment]
I think it's up to the user's intuition on how to solve this bonfire, I don't think it's a good idea to remove functionality from JS, it's just how it works.

When I tried the bonfire for the first time, coming from C, my first move was to iterate through it. Functions are awesome.

**Comment by BerkeleyTrue** [comment]
@dmfarcas The point of bonfires is to devise algorithms to solve the challenge. If you use a built in method that completely solves the bonfire on its own then you aren't solving the bonfire.

**Comment by SaintPeter** [comment]
We don't currently have the infrastructure in place to disallow the use of `String.repeat()`.  Once we have mocks and spies in place we can easily implement this.

**Comment by shadowfool** [comment]
Thanks Berkley, this was my understanding of the point of the bonfire challenges. I'll be sure to point out any more "cheats" like this.

**Comment by iMearner** [comment]
unction repeatStringNumTimes(str, num) {
  var st="";
  // repeat after me
  for(i=0; i<num; i++)
    {
   st=st+str;
      
    }
  return st;
}

repeatStringNumTimes("abc", 3);
