### ISSUE TITLE
Change cert name to "Front End Development Libraries" on settings page

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#42502]
We renamed the "Front End Libraries" cert to "Front End Development Libraries" a while back. It never got updated in a few spots on the settings page...
![Screen Shot 2021-06-15 at 6 58 30 AM](https://user-images.githubusercontent.com/20648924/122049055-994b1800-cda7-11eb-82a7-7a7ed9d833eb.png)
![Screen Shot 2021-06-15 at 6 58 13 AM](https://user-images.githubusercontent.com/20648924/122049061-9b14db80-cda7-11eb-956a-c3bf56aafc36.png)

We should update the name in these two spots

**Comment by ShaunSHamilton** [comment]
As #42511 does not close this issue. These files still need to be changed to match the new name:

- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/front-end-libraries-certificate/meta.json
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/12-certificates/front-end-libraries-certificate/front-end-libraries-certificate.yml
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/front-end-libraries-projects/meta.json

**Comment by NoorFakhry** [comment]
@shabnamNajafian Do you mean that anybody else would work on those changes?, or we wait for the creator of the PR to do them?

**Comment by lazy-geek** [comment]
> As #42511 does not close this issue. These files still need to be changed to match the new name:
> 
> * https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/front-end-libraries-certificate/meta.json
> * https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/12-certificates/front-end-libraries-certificate/front-end-libraries-certificate.yml
> * https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/front-end-libraries-projects/meta.json

@ShaunSHamilton Hi I Am New To Open Source Contribution And I Would Like To Contribute To This Issue By changing above files, can i do that?

**Comment by raisedadead** [comment]
This PR already has a PR aiming to fix this. However, we have several open issues that need help. We encourage you to look through the "help-wanted" label

**Comment by NoorFakhry** [comment]
Hey, I apologize but I realized It would take me time to understand the project as a whole and understand the code and its flow, So feel free to close this PR and let somebody else work on the issue, I will start contributing again once I feel comfortable with the code and have a better understanding of the project.

**Comment by ojeytonwilliams** [comment]
As discussed https://github.com/freeCodeCamp/freeCodeCamp/pull/42512#issuecomment-863449654 @NoorFakhry is not planning to work on this any more, but that PR might help someone else who wants to tackle this.
