### ISSUE TITLE
Mismatch translatable text

### ISSUE THREAD

**Issue by ocioran** [freeCodeCamp/freeCodeCamp#42517]
**Affected page**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```




```

**Expected behavior**
Text with the example code is not translatable - which is fine.
However, the text lower is translatable and this will create confusion for end users on other languages.

**Screenshots**
Untrabslatable example:
![image](https://user-images.githubusercontent.com/39167526/122111047-f25a9080-ce27-11eb-8b61-6e83ce7becdf.png)
vs.
Translatable output of the exmple:
![image](https://user-images.githubusercontent.com/39167526/122111111-030b0680-ce28-11eb-8a84-938c19d4c912.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: chrome
 - Version: 91.0.4472.77

**Additional context**

**Comment by raisedadead** [comment]
I think this is expected behaviour. That is because its and example we would not translate it.

**Comment by ocioran** [comment]
Sure... then the description of the output should not be translated either and right now it is.

**Comment by raisedadead** [comment]
I think

- The description should be translated. Which I understand it currently is. This gives the context of the example that follows.
- The example text line should NOT be translated because it's a literal output of the code. Which I understand it currently is not.

It looks like we would want the current behaviour though I would wait for someone else to confirm.

**Comment by ocioran** [comment]
I was just thinking under translation context: people looking at this page in other languages will see on the page: 
- if you write a text like this (in English): ..... 
- that code produces the output (for example in Romania ):
Acesta este ul link către freecodecamp.org la care poți ajunge.

I personally would be confused how English is rendered into Romanian by itself

**Comment by raisedadead** [comment]
I believe all the other languages are translating the example and instructions, so you are correct both should be translated.

https://www.freecodecamp.org/espanol/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

https://chinese.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

**Comment by ieahleen** [comment]
the example in code can't be translated
the example
```
<p>
  Here's a <a target="_blank" href="https://www.freecodecamp.org"> link to www.freecodecamp.org</a> for you to follow.
</p>
```

can't be translated, so if the result is translated it will never match
in English it says
> The final output of the example will look like this:
Here's a link to www.freecodecamp.org for you to follow.

where in Spanish it says
> El resultado final del ejemplo se verá así:
Aquí hay un enlace a www.freecodecamp.org para que lo sigas.

where the second line would be how the code above should appear

it is translated in Chinese too, and I think we translated it also in Italian 
But it stands more correct to be kept in English as actual rapresentation of what the result of the code is

**Comment by raisedadead** [comment]
> But it stands more correct to be kept in English as actual rapresentation of what the result of the code is

Thanks, that is what my intuitive thought was like I mentioned. I think we should get this change in all languages and have a check to catch changes as a warning.

@nhcarrigan can you guide here?

**Comment by nhcarrigan** [comment]
Unfortunately our current workflow doesn't have a quick way to mark a specific string as non-translatable. I could probably put something together, but IMHO it might be worth re-wording the challenge instead.

**Comment by raisedadead** [comment]
Hmm, did Crowdin not have a way to manually mark it non-translatable? I might be mistaken though.

**Comment by nhcarrigan** [comment]
We can do that, yes - we would need to revert the translations for the languages which have translated it.

However, I believe that hidden state is lost every time the file is re-uploaded.

**Comment by raisedadead** [comment]
Hmm, I see. Thanks for clarifying all this. I am glad that I double-checked with you. Do you mind sending a quick support request to Crowdin, seeking advice?

**Comment by nhcarrigan** [comment]
Sure thing - will add that to the list today and CC you :)

**Comment by nhcarrigan** [comment]
Okay I slept on this, and decided to see if there was a way to automate this process.

PR coming shortly.

**Comment by raisedadead** [comment]
@nhcarrigan now that this has been merged do we need to do anything over on Crowdin or in our codebase to reset the strings?

**Comment by nhcarrigan** [comment]
Thanks for the reminder 🙂 

I have gone through and cleared the existing translations for this string - it should come down in English for all languages going forward.

**Comment by raisedadead** [comment]
Awesome, thanks for taking care of it.
