### ISSUE TITLE
Adding cypress tests for hotkeys

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#42528]
Issue for tracking adding cypress tests of hotkeys, as per #42503.

Challenges / Projects / Video challenges:
- Navigation mode - 'escape'
- Previous challenge - 'p'
- Next challenge - 'n'
- Focus on editor - 'e'
- Focus on instructions panel - 'r'
- Running the tests - 'ctrl + enter' / 'command + enter'

**Comment by Sembauke** [comment]
Hey @gikfk, Are you still planning on working on this?

**Comment by gikf** [comment]
Hey @Sembauke, sorry, I haven't managed to start on this yet. If you'd want feel free to have a go at it.

**Comment by lastrafda** [comment]
I would like to work on this @Sembauke

**Comment by Sembauke** [comment]
Hey @lastrafda,
This is a pretty though one, let me know if you need some help.

**Comment by lastrafda** [comment]
Thanks @Sembauke I'll let you know! I have a question
I was looking at a video challenge and I realized that you have to click inside the main tag o focus the "Check your answer" button in order to be able to use the previous challenge and next challenge hotkey, is this the expected behavior?

**Comment by ShaunSHamilton** [comment]
@lastrafda 
> you have to click inside the main tag or focus the "Check your answer" button in order to be able to use the previous challenge and next challenge hotkeys

Expected behaviour is using the `esc` key to allow the hotkeys to be targeted. That is, to enter navigation mode:
> Navigation mode - 'escape'

**Comment by Sembauke** [comment]
I've tested some of the hotkeys and the previous and next challenge hotkey does not seem to work for me. Can anyone test this out?

**Comment by gikf** [comment]
Any specific challenge type?
- classic challenges: `esc` ->`p` and `n` works for current and challenges that are changed to
- backend/project challenges: `esc` -> `p` and `n` works for current and challenges that are changed to
- video challenges: click on page -> `esc` -> `p` and `n` works for current challenge, after changing challenge with hotkey, it's needed to click again on page to be able to use `p` or `n`

**Comment by lastrafda** [comment]
> I've tested some of the hotkeys and the previous and next challenge hotkey does not seem to work for me. Can anyone test this out? 

For the video challenges I had to click on the page before entering navigation mode as @gikf said I thought it was a bug the other challenges worked just fine (this was some weeks ago)

**Comment by ojeytonwilliams** [comment]
> video challenges: click on page -> esc -> p and n works for current challenge, after changing challenge with hotkey, it's needed to click again on page to be able to use p or n

Good catch @gikf I'll add a fix to Sem's PR.
