### ISSUE TITLE
[challenges] Add Dev Mode

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#4252]
A dev mode that does not cache challenges and refreshes page on challenge change.

**Comment by BerkeleyTrue** [comment]
cc @SaintPeter

**Comment by SaintPeter** [comment]
Can this be added as a Gulp task?

`gulp dev-mode` or whatever.  This task would set the appropriate environment variables and have the watchers for the challenge files.  This would be the simplest possible solution for devs.
