### ISSUE TITLE
Wrong answer i test - python for everybody

### ISSUE THREAD

**Issue by bautzon** [freeCodeCamp/freeCodeCamp#42523]
**Affected page**
https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/intermediate-strings

**Your code**
Well he bascially just spelled banana wrong, as he spelled it "bananana"
the student is then asked to use word.find('na') and the answer comes out 2, as if the word was spelled correctly.
Answer should be 3 or banana should be spelled correct

Got to the page and it will make sense

```




```

**Expected behavior**
Add a clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by thecodingaviator** [comment]
Hi @bautzon ,

@VivekThazhathattil above is correct. I'm not sure, but it is possible that the word was intentionally "misspelt" for a better understanding of `.find()`. As such, I'm closing the issue. Please add additional clarification below if you think this issue should be reopened.

Happy coding! :confetti_ball:

**Comment by bautzon** [comment]
I know feel very embarrassed, thank you guys so much for the explanation

**Comment by VivekThazhathattil** [comment]
@bautzon  Don't be embarrassed; making mistakes is natural in any learning process..
