### ISSUE TITLE
Cross Platform testing

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#42541]
Recently a lot of Safari users have faced issues in using our platforms. The reason being some browsers do not support every available feature. Also we face restrictions ourselves in having access to every browser available, like Safari is only available in MacOS and not everyone will have a MacOS device. This in turn makes it harder for us to QA any feature or bug fix. Hence, it results in the occasional bugs being missed out and creating issues among our users.

A proposed solution(by @raisedadead) was to integrate a tool like Browserstack(https://www.browserstack.com) to make it easier for our contributors to do cross platform testing.

This issue is open to discussion for any suggestion or feedback.

Browserstack developer docs - https://www.browserstack.com/docs/
They also have support to do cross browser testing with Cypress.

**Comment by Nirajn2311** [comment]
I've used Browserstack for cross platform testing and it hasn't disappointed me at all. Mostly I've used it for mobile testing because Devtools has its own restrictions.

**Comment by raisedadead** [comment]
Thanks for confirming all these details, we have access to their open-source tier thru Sept. this year. Will you be interested in helping us integrate our codebase/testing workflows with BrowserStack? 

If yes, let us know I will check with @ojeytonwilliams to get you a set of credentials.

**Comment by Nirajn2311** [comment]
Yes, I'm interested in working on this.

**Comment by raisedadead** [comment]
I have sent you an invite in the chat DM.

**Comment by Sembauke** [comment]
Any updates on this @Nirajn2311 ?

**Comment by Nirajn2311** [comment]
I've just gone through their docs at the moment. Will begin working on it soon and update the progress here.

**Comment by Art-auto** [comment]
I'm open to collaboration here. Let me know if you need any help

**Comment by Sembauke** [comment]
@Art-auto You are welcome to work on this yourself 😄

**Comment by Nirajn2311** [comment]
Now that we've upgraded Cypress to v10 in the repo, we can prepare for WebKit testing using Cypress itself(until Cypress makes it stable). Last I checked there were some errors when I ran the tests locally.

**Comment by a2937** [comment]
I wanna see how the codebase performs but unfortunately Safari is no longer supported on Windows. 

https://support.apple.com/en-us/HT204416

**Comment by Sembauke** [comment]
Closing this in favour of Playwright testing. 

> Playwright Test was created specifically to accommodate the needs of end-to-end testing. Playwright supports all modern rendering engines including Chromium, WebKit, and Firefox. Test on Windows, Linux, and macOS, locally or on CI, headless or headed with native mobile emulation of Google Chrome for Android and Mobile Safari.
