### ISSUE TITLE
Low Priority Issue: Typo on Basic CSS

### ISSUE THREAD

**Issue by Fhaalkras** [freeCodeCamp/freeCodeCamp#42554]
**Describe your problem and how to reproduce it:**
Typo, it's a typo. (The word "penguin" is "pengiun" on the code area.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable

**Recommended fix, suggestions (how would you update it?):**
It's a typo, just reporting it, but like.... its just a typo.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/62732548/122502364-1b138f00-cfbc-11eb-8619-a46c74822018.png)

**Comment by gikf** [comment]
Hey @Fhaalkras 

Thank you for opening this issue.

This typo is intentional, it is to demonstrate the usage of fallback value of property.

Thank you and happy coding.
