### ISSUE TITLE
Easy readability of documentation in mobile view

### ISSUE THREAD

**Issue by PrashantSakre** [freeCodeCamp/freeCodeCamp#42571]
**Describe your problem and how to reproduce it:**
Viewing Documentation in mobile view as shown in bellow image the content is narrower. Need to make the content little more wider for easy readability. This is also true in landscape view lot of empty space left both sides.

**Add a Link to the page with the problem:**
https://contribute.freecodecamp.org/#/how-to-work-on-the-docs-theme

**Recommended fix, suggestions (how would you update it?):**

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot 2021-06-19 at 10 26 00 PM](https://user-images.githubusercontent.com/42613882/122649806-57c2c000-d14d-11eb-8182-15d8a5552d5b.png)

![Screenshot 2021-06-19 at 10 49 20 PM](https://user-images.githubusercontent.com/42613882/122650441-a6258e00-d150-11eb-96be-90c8ec30d300.png)

**Comment by ojeytonwilliams** [comment]
Thanks for the report @PrashantSakre. I agree that margins are too wide. 

Would you be interested in creating a PR to fix this?

**Comment by PrashantSakre** [comment]
@ojeytonwilliams sure will work on this issue
