### ISSUE TITLE
Inconsistency in Docsify flexible alerts

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#42599]
We are currently using the [flexible-alerts plugin](https://www.npmjs.com/package/docsify-plugin-flexible-alerts) for our Docsify-powered contributing documentation.

One of the alert types, `attention`, also accepts the `danger` keyword to render.

We currently render one of these boxes with `attention` and four of them with `danger`. For consistency sake, we should use the same keyword to render these.

IMHO, with the displayed text being "Attention" we should use the `attention` keyword, but I wanted to get some feedback before opening this up to first timers.

As an alternative, if we prefer the `danger` text, we can modify the plugin config to render `Danger` on the end-user view instead of `Attention`.

**Comment by ieahleen** [comment]
At this time, there are 4 instances of usage of `DANGER` and 1 instance for `ATTENTION`, I think it would make sense to make it consistent. And seeing that with the displayed being "Attention" I agree on that being the one used.

**Comment by thecodingaviator** [comment]
+1 on making it `attention`

**Comment by ShaunSHamilton** [comment]
I am happy either way. The only reason I came into this is because I am used to the Bootstrap way of naming, and naturally put DANGER.

**Comment by nhcarrigan** [comment]
Alright, I am going to open this up to first timers.

A pull request that closes this issue will:
- Replace all instances of `[!DANGER]` with `[!ATTENTION]` in the `/docs` directory
- Will *not* modify any of the files in the `/docs/i18n` directory (these will be updated through our translation worfklow)

If you are interested in resolving this issue, we recommend starting with our [contributing guidelines](https://contribute.freecodecamp.org). If you have further questions feel free to join us in our [contributor chatroom](https://chat.freecodecamp.org/channel/contributors).

**Comment by aileenpalafox** [comment]
Hi, @nhcarrigan can I try this out?

**Comment by nhcarrigan** [comment]
Sure thing! Let us know if you have any questions :)

**Comment by kaiwalyakoparkar** [comment]
Hey Nick, I would like to work on this!

**Comment by krishdevdb** [comment]
> Hey Nick, I would like to work on this!

@kaiwalyakoparkar I also thought of that, but as this issue has been already received by someone, let's give them some time! If it is more than a week without no response, you can grab this!

**Comment by kaiwalyakoparkar** [comment]
> > Hey Nick, I would like to work on this!
> 
> @kaiwalyakoparkar I also thought of that, but as this issue has been already received by someone, let's give them some time! If it is more than a week without no response, you can grab this!

Yup I got that. That's why I commented so if they are unable then I can pick that up
