### ISSUE TITLE
The tests in challenge "Record Collection" is not accurately determining the result of the code entered.

### ISSUE THREAD

**Issue by GregSaintJean** [freeCodeCamp/freeCodeCamp#42627]
**Affected page**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection

**Your code**

```
if(value.length === 0){
    delete records[id][prop];
    return records;
  }

  if(prop !== "tracks" && value.length > 0){
    records[id][prop] = value;
  } else if(prop === "tracks"){

    album = records[id];

    if(album.hasOwnProperty(prop)){

      if(value.length > 0){
        album[prop].push(value);
      }

    } else {
      album[prop] = [value];
    }
  }

  return records;

```

**Expected behavior**
I ran the code in the challenge webpage and it was stating that my solution was wrong. However, when I created a folder, an HTML page and ran the javascript by itself on the HTML page with the developer tools opened in chrome, the code executed just as it was explained under the hints the test is suppose to give you when you are wrong.

**Screenshots**
[Image of chrome developer tools console results after calling "updateRecords(recordCollection, 5439, 'artist', 'ABBA');" followed by "console.log(updateRecords(recordCollection, 5439, "tracks", "Take a Chance on Me"));"](https://i.ibb.co/p3wJTq0/screenshot-code.png)

**System (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: chrome
 - Version: version of chrome? 91.0.4472.114 (Official Build) (64-bit)

**Additional context**
The files and file structure used to test the behavior against the challenge page goes as follows.

One folder called "wtf" was created. It stored a file named "wtf.html" and a folder called "js". The folder contained a file named "wtf.js".

wtf.html has the following code:
[Image of HTML code because markdown isn't behaving](https://i.ibb.co/zGR5FCR/html-code.png)

wtf.js has the following code:

`
var recordCollection = {
    2548: {
      albumTitle: 'Slippery When Wet',
      artist: 'Bon Jovi',
      tracks: ['Let It Rock', 'You Give Love a Bad Name']
    },
    2468: {
      albumTitle: '1999',
      artist: 'Prince',
      tracks: ['1999', 'Little Red Corvette']
    },
    1245: {
      artist: 'Robert Palmer',
      tracks: []
    },
    5439: {
      albumTitle: 'ABBA Gold'
    }
  };

  function updateRecords(records, id, prop, value) {

    if(value.length === 0){
      delete records[id][prop];
      return records;
    }
  
    if(prop !== "tracks" && value.length > 0){
      records[id][prop] = value;
    } else if(prop === "tracks"){
  
      album = records[id];
  
      if(album.hasOwnProperty(prop)){
  
        if(value.length > 0){
          album[prop].push(value);
        }
  
      } else {
        album[prop] = [value];
      }
    }
  
    return records;
  }

  //console.log(updateRecords(recordCollection, 5439, 'artist', 'ABBA'));
  updateRecords(recordCollection, 5439, 'artist', 'ABBA');

  console.log(updateRecords(recordCollection, 5439, "tracks", "Take a Chance on Me"));
  //updateRecords(recordCollection, 5439, "tracks", "Take a Chance on Me")
`

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
