### ISSUE TITLE
"Go to my Next Challenge" Button broken when not signed in

### ISSUE THREAD

**Issue by Yashraj-Gore** [FreeCodeCamp/FreeCodeCamp#4262]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%20%3D%20%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class = "red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

Nothing happens on clicking 'go to my next challenge'. Have attached the screenshot for details.

**Comment by faizaanceg** [comment]
Is this a misclick? What is the problem here?

**Comment by Yashraj-Gore** [comment]
Attaching screenshot,hang on...

**Comment by Yashraj-Gore** [comment]
![1](https://cloud.githubusercontent.com/assets/15717581/11029577/f0303dd2-86ed-11e5-92a3-1e2942ebec42.png)

**Comment by Yashraj-Gore** [comment]
But there is a work around with ctrl+enter key press.

**Comment by faizaanceg** [comment]
Hmm. Both the click and shortcut work for me. Can you try this other Waypoints?

**Comment by Yashraj-Gore** [comment]
Sure,i shall and try and get back in a while.

**Comment by Yashraj-Gore** [comment]
Nope,the issue persists.

**Comment by faizaanceg** [comment]
Weird. Both are working for me.

**Comment by marhyorh** [comment]
You're Logged Out, See the SignIn button above

**Comment by Yashraj-Gore** [comment]
In that scenario,ctrl+enter should also be not working i suppose.

**Comment by faizaanceg** [comment]
Oh..didn't notice that. but the Ctrl+Enter shouldnt work then.

**Comment by Yashraj-Gore** [comment]
Well, as pointed out by marhyorh,It did solve the problem, am able to click now,but then ctrl+enter should also not work.

**Comment by marhyorh** [comment]
Yeah, it will

**Comment by SaintPeter** [comment]
Confirmed Issue.

Issue Reproduction:

1. Log out of the site
2. complete a waypoint and click "run tests"
3. Clicking the "Go to my next challenge" button does not work. 
4. Doing ctrl+enter does work.

**Comment by SaintPeter** [comment]
@BerkeleyTrue can you take a look at this one?

**Comment by BerkeleyTrue** [comment]
@SaintPeter There is already a PR. Waiting for @ltegman to make updates.
