### ISSUE TITLE
Private timeline hides cert solutions

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#42621]
If you set the timeline to private and open one of your certifications, all the solutions will be hidden:
![Screen Shot 2021-06-24 at 8 03 29 AM](https://user-images.githubusercontent.com/20648924/123267562-c5ab1680-d4c2-11eb-9911-474ff462e667.png)

**Comment by ShaunSHamilton** [comment]
Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/40403#issuecomment-779957353

**Comment by raisedadead** [comment]
I am closing this in favour of the other issue because the fix is most likely to be in the same area. Tom, please feel to carry over your report if the other issue does not cover this.

**Comment by ShaunSHamilton** [comment]
@raisedadead We decided to go a different route: https://github.com/freeCodeCamp/freeCodeCamp/pull/45562

But we have not actually discussed what that route is: https://github.com/freeCodeCamp/freeCodeCamp/issues/45563

**Comment by raisedadead** [comment]
Ok - lets' discuss this over a call sometime early next week.

**Comment by moT01** [comment]
In addition to the discussed "404" page or whatever we come up with, we should add this next to the timeline setting:
<img width="289" alt="Screen Shot 2022-07-06 at 9 42 13 AM" src="https://user-images.githubusercontent.com/20648924/177577406-593953f8-1a29-4a11-b253-7fcc851db5f6.png">
