### ISSUE TITLE
Filter map page to show only challenges not completed

### ISSUE THREAD

**Issue by pdewouters** [FreeCodeCamp/FreeCodeCamp#4263]
I think it would be helpful to have a filter at the top of the page to show only challenges that haven't been done yet.
How can I get started contributing this?

**Comment by SaintPeter** [comment]
This is a good idea - to be able to filter what you see on the map, as it gets bigger.   I'll capture this as a feature request.

We are planning to completely rewrite the challenge map when we move to React, but you're welcome to spin something up for use on the current site.

**Comment by pdewouters** [comment]
cool, I'm interested in getting involved with React.

**Comment by bugron** [comment]
Another suggestion is in #4024.
