### ISSUE TITLE
Translations: Incomplete text string in crowdin (missing last word and closing </code> tag)

### ISSUE THREAD

**Issue by ocioran** [freeCodeCamp/freeCodeCamp#42647]
**Affected page**
https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/use-the-u-tag-to-underline-text

**Expected behavior**
On the challenge page, in English the text says:
"Wrap the u tag only around the text Ph.D. students."

However, the source string in crowdin is:
```html
"Wrap the <code>u</code> tag only around the text <code>Ph.D."
```

It is missing the last word "students" and the closing tag \</code\>. 
And this part ("students \</code\>) is split into a separate string.

Same issue for the error message: "The u tag should wrap around the text Ph.D. students."

**Screenshots**
![image](https://user-images.githubusercontent.com/39167526/123525480-aa662400-d6d9-11eb-8d6c-d528258ff13e.png)
![image](https://user-images.githubusercontent.com/39167526/123525487-bb169a00-d6d9-11eb-8cef-853d7ba38519.png)
![image](https://user-images.githubusercontent.com/39167526/123525552-3d06c300-d6da-11eb-9899-8e2d90a8044f.png)

**System (please complete the following information):**
 - Device: iPhone6, Laptop
 - OS: Windows 10
 - Browser: chrome
 - Version:  91.0.4472.114 

**Additional context**
I am helping with Romanian translations while doing the challenges and this is how I stumbled upon this difference.

**Comment by nhcarrigan** [comment]
Crowdin splits these into two different strings. We are working with their dev team to resolve this.

**Comment by nhcarrigan** [comment]
A fix has been applied for this and the file is updated in Crowdin. Feel free to let us know if you continue to see issues. :)
