### ISSUE TITLE
Possibly a typo 

### ISSUE THREAD

**Issue by CodeWingX** [FreeCodeCamp/FreeCodeCamp#4264]
Challenge [Bonfire: Pairwise](http://www.freecodecamp.com/challenges/bonfire-pairwise?solution=function%20pairwise(arr%2C%20arg)%20%7B%0A%20%20var%20sum%20%3D%200%3B%0A%20%20for(%20var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B%20)%20%7B%0A%20%20%20%20for(var%20j%20%3D%20i%20%2B%201%3B%20j%20%3C%20arr.length%3B%20j%2B%2B%20)%20%7B%0A%20%20%20%20%20%20if(%20arr%5Bi%5D%20%2B%20arr%5Bj%5D%20%3D%3D%3D%20arg%20%26%26%20i%20!%3D%3D%20j)%20%7B%20%0A%20%20%20%20%20%20%20%20sum%20%2B%3D%20i%20%2B%20j%3B%0A%20%20%20%20%20%20%20%20console.log(%22%20i%3A%20%22%2B%20i%20%2B%20%22%20j%3A%20%22%20%2B%20j%20%2B%20%22%20sum%3A%20%22%20%2B%20sum)%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20sum%3B%0A%7D%0A%0Apairwise(%5B1%2C1%2C1%5D%2C%202)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I don't understand the second test case, is this a typo? 

2) pairwise([1, 3, 2, 4], 4), 1 should return 1.

My code:
```javascript
function pairwise(arr, arg) {
  var sum = 0;
  for( var i = 0; i < arr.length; i++ ) {
    for(var j = i + 1; j < arr.length; j++ ) {
      if( arr[i] + arr[j] === arg && i !== j) { 
        sum += i + j;
        console.log(" i: "+ i + " j: " + j + " sum: " + sum);
          
      }
    }
  }
  
  return sum;
}

pairwise([1,1,1], 2);
```

**Comment by faizaanceg** [comment]
I would like to fix this.
