### ISSUE TITLE
Confirm the Ending: Add test case

### ISSUE THREAD

**Issue by geoff-wasilwa** [FreeCodeCamp/FreeCodeCamp#4267]
I wrote a function that checks if `target` exists in the last string of `str`, and all test were passing. I called the same function with `end("He has to give me a new name", "na")` expecting `false`, but it was true. I think a new test case should be added for this scenario.

**Comment by marhyorh** [comment]
Can you post the code here?

**Comment by geoff-wasilwa** [comment]
```
function end(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (str.indexOf(' ') > -1) {
    str = str.split(' ');
  }
  var lastVal = str[str.length - 1];
  return lastVal.indexOf(target)> -1;
}
```
