### ISSUE TITLE
Clarification for express body-parser exercise

### ISSUE THREAD

**Issue by santimirandarp** [freeCodeCamp/freeCodeCamp#42682]
**Affected page**
Add a link to the coding challenge with the problem.
Page for exercise: https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-body-parser-to-parse-post-requests

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
// external packages
const express = require('express');
const app = express();
const bodyParser = require('body-parser')

const userPostData = (req,res) => console.log(req.body) 
const bp = bodyParser.urlencoded({extended: false})
app.route("/name").get(userGetData).post(bp,userPostData)
// error at printing object
```

**Expected behavior**
Add a clear and concise description of what you expected to happen.

If we add `extended:false` not only we enable standard query string parsing, but also disable the ability to print the object, this is because the querystring object does not inherit from Object, for security reasons, but can confuse any beginner (I guess).

Can be solved by using `extended:true`, this way, the expected behavior will happen (object is logged out).

**Additional context**
IMHO the exercise should clarify this (although users will found answers on SO if they look it up).

**Comment by raisedadead** [comment]
I agree we could add some explanation in the challenge description.

**Comment by anirudh-modi** [comment]
Hi @raisedadead can you assign this issue to me? I would like pick and solve this..
