### ISSUE TITLE
New user gets automatically redirected to /learn after briefly shown the intro page

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#42708]
**Affected page**
Add a Link to the page with the problem.

**To Reproduce**

1. Go to freecodecamp.org as an unauthenticated user and click Sign in
2. Enter a new email address that will sign you up as a new user
3. After the user enters the sign in code, they get redirected to a page where the intro ([IntroDescription](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/Intro/components/IntroDescription.js)) is displayed, then almost immediately get redirected to /learn where they would see the curriculum. 

**Expected behavior**
I think the user should not be redirected to /learn automatically, as we would want them to read through the introduction page first.

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

N/A

**System (please complete the following information):**
 - Device: Laptop
 - OS: MacOS
 - Browser: Firefox

**Additional context**
N/A

**Comment by alirezaghey** [comment]
Hello,
I'm wondering how one can simulate the signup process on a local setup. This would be needed to test any solution or even dig further into the problem.

**Comment by ahmadabdolsaheb** [comment]
I can reproduce the issue on .org and .dev, it seems like it would affect the email sign ups for new users.
@alirezaghey, we are using a mock auth for local setup, so the behavior is different.

**Comment by ahmadabdolsaheb** [comment]
I assume, at some point the user's privacy policy flag gets updated and and the user is redirected accordingly.

**Comment by huyenltnguyen** [comment]
Okay, I think my report was wrong. It happened very quickly and I actually didn't pay attention to the URL, so there might not be a redirect, but some conditional rendering rather.

I didn't look closely into this, but by reading the rendering of this part (code [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/Intro/index.js#L22)), I think the `isSignedIn` state is initially `false`, which allows the rendering of the intro page, but then it swiftly switches to `true` and causes the page to render the curriculum instead.

`isSignedIn` is returned from the `isSignedInSelector`, which looks for the username to determine the signed in state:

https://github.com/freeCodeCamp/freeCodeCamp/blob/d475b850bc8a0a8910b4a5389382ad4d9401616c/client/src/redux/index.js#L181

**Comment by victor-duarte** [comment]
For reference, evidence:

https://user-images.githubusercontent.com/1746030/125321116-faf89680-e301-11eb-8ed4-5e5b079d113c.mov

**Comment by ShaunSHamilton** [comment]
Closed in: https://github.com/freeCodeCamp/freeCodeCamp/pull/42944
