### ISSUE TITLE
Unable to View JS Algorithms Solutions

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#42716]
When trying to view a JS solution, the following error appears in dev, explaining the issue in production.

```console
Warning: Failed prop type: Invalid prop `files` of type `object` supplied to `ProjectModal`, expected an array.
    in ProjectModal (created by CertificationSettings)
    in CertificationSettings (created by withI18nextTranslation(CertificationSettings))
```

It seems we followed the expected prop-types too early (ref: #42695 ). The `challengeFiles` object is still an object literal.

Reported on forum: https://forum.freecodecamp.org/t/i-cant-see-my-code-in-the-javascript-algorithms-and-data-structures-certification/467465

**Comment by MickenCZ** [comment]
I have the same problem as I said in the forum, the bottom error says it responded with 404 to the request for the certification on JS algorithms and data structures. Seems like there's an issue with the backend reaching that certification.
![image](https://user-images.githubusercontent.com/73470371/124392857-e3188580-dcf7-11eb-9532-f4c253809fc9.png)
