### ISSUE TITLE
Open a new browser tab instead of leaving the curriculum

### ISSUE THREAD

**Issue by quistthejack10** [freeCodeCamp/freeCodeCamp#42744]
**Is your feature request related to a problem? Please describe.**
In the API's and Microservices curriculum. Clicking on the links to either clone the repo or to open replit the user is taken off the freecodecamp site. Should the link open a new tab so that the user can still see the instructions and problem from the curriculum?
https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/meet-the-node-console

**Describe the solution you'd like**
When clicking on those links I would find it more convenient for the software to open a new tab instead of navigating away from the curriculum.

**Describe alternatives you've considered**

**Additional context**
This is my first time raising an issue and id like to help implement this feature if possible.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this issue. We are currently keeping track of this here: https://github.com/freeCodeCamp/freeCodeCamp/issues/39739

As such, I am going to close this as a duplicate.
