### ISSUE TITLE
Wrong translation in Spanish for "Learn about Tertiary Colors"

### ISSUE THREAD

**Issue by kevinsmithwebdev** [freeCodeCamp/freeCodeCamp#42746]
**Affected page**
Add a link to the coding challenge with the problem.

https://www.freecodecamp.org/espanol/learn/responsive-web-design/applied-visual-design/learn-about-tertiary-colors

In the second to last test, the text is:

    El elemento `div` con clase `raspberry` debe tener un `background-color` naranja.

The word "naranja" means "orange" - it should be "frambuesa".

In the file:

freeCodeCamp/main/curriculum/challenges/espanol/01-responsive-web-design/applied-visual-design/learn-about-tertiary-colors.md

**Your code**
Copy and paste the code from the editor that you used in between the back-ticks below:

```
El elemento `div` con clase `raspberry` debe tener un `background-color` frambuesa.
```

**Expected behavior**
Add a clear and concise description of what you expected to happen.

I expect the color raspberry to be translated into Spanish as "frambuesa", not "naranja".

**Screenshots**

N/A

**System (please complete the following information):**

N/A

**Additional context**

I'm just relaying a report from the forum. If someone wants to grab this, they're welcome.

**Comment by ieahleen** [comment]
Translations are now managed through Crowdin, and translation errors are best communicated to the translators through the official chat

I'm forwarding the issue there

**Comment by raisedadead** [comment]
We already have our translators and proofreaders on forum, we should be able to tag them directly on the forum?

**Comment by ieahleen** [comment]
We may need an easily consultable list with at least one proofreader per language that can be tagged for this maybe

**Comment by Sembauke** [comment]
There is a build-in Crowdin discussion widget where you can tag others. Maybe @RafaelDavisH can make a list of all the proofreaders so we can make a separate team to tag them if needed here. But I am not a fan of using GitHub for translations as we do not accept translations through Github.

**Comment by juancarrillofl** [comment]
Hello, Spanish proofreader here. Thanks for pointing this out, Kevin! I already fixed it on Crowdin, hope that it updates on production soon.

**Comment by raisedadead** [comment]
We have had teams and groups on Crowdin from day one, they seem to be utilized I think. It's perfectly okay to report issues in any of the channels Chat, Forum or GitHub and someone will get to it. 

However, the idea should be not to duplicate the report in other channels. So, if we get a report on the forum we can simply tag someone (even someone in the staff) to draw their attention.

@juancarrillofl thanks for fixing the issue. 

Usually, it takes 1-2 days for us to pull changes and deploy them live, but it could take longer depending on workload & other factors.
