### ISSUE TITLE
waypoint-join-our-linkedin-alumni-network

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/FreeCodeCamp#4275]
Hi,

The Finish Challenge button doesn't work when opening the OPEN LINK IN NEW TAB with the mouse cursor button (which normally opens links directly in new tabs) in stead of just clicking on the button.

Cheers!
~SteinGee

**Comment by SaintPeter** [comment]
Clicking the button should open the link in a new tab for you.  We can only register a click that has been clicked - this is a limitation of your browser.

Thank you and happy coding!
