### ISSUE TITLE
Fix minor spelling error

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#42756]
This word should be spelled "programming".

Instead of just fixing this myself, I figured it would be a good first-time issue for a contributor who wants to get familiar with the codebase and pull request process. 😄 

The error can be seen in production here: https://www.freecodecamp.org/learn/data-visualization/

**Screenshots**
<img width="1382" alt="Data_Visualization_Certification___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/124538001-8d6bd800-dde0-11eb-8e07-6855defdd05e.png">

**Comment by mohamed-elalem** [comment]
@QuincyLarson I can pick this one

**Comment by gikf** [comment]
Hey @mohamed-elalem 

Just go ahead :rocket: 

Issues are typically not assigned to anyone other than long-time contributors. You can read more about this at https://contribute.freecodecamp.org/#/FAQ?id=how-can-i-get-an-issue-assigned-to-me. 

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
