### ISSUE TITLE
Bonfire: Drop it; Expecting wrong quoted answer in 5th test case

### ISSUE THREAD

**Issue by carefulAxe** [FreeCodeCamp/FreeCodeCamp#4278]
Link: http://www.freecodecamp.com/challenges/bonfire-drop-it

Here is the 5th test case:
drop([1, 2, 3, 9, 2], function(n) {return n > 2}) should return [3, 9, 2].

From the description alone you can see what is wrong. It should return [3, 9], it cannot include "2" in the result array if the function is n > 2.

If code you write is correct and actually returns [3, 9], you will still not pass the test.
If code you write has hardcoded the wrong answer returned quoted in the test case, then the test will pass. So it is expecting the wrong answer.

![image](https://cloud.githubusercontent.com/assets/9951362/11050934/6684f32c-86ff-11e5-9735-60e98da02f56.png)

**Comment by faizaanceg** [comment]
Well the Bonfire *is* technically right. If you read the description correctly, the function should **stop** once the predicate returns true. So the last 2 in `[1,2,3,92]` would actually be preserved.

Maybe the description could be made more clearer

**Comment by carefulAxe** [comment]
Ah ok, let me re-read the description more carefully, then I'll update/cancel the issue.

**Comment by carefulAxe** [comment]
Ok, I've misread. Cancelling ticket.

**Comment by carefulAxe** [comment]
Is this issue closed? I can no longer interact with this Bonfire (cannot enter any code on screen, buttons do not work), is there something more I should do to release the screen so I can finish it?

**Comment by carefulAxe** [comment]
Sorry, but I can no longer interact with this Bonfire since I submitted this erroneous issue (cannot enter any text, cannot run tests or reset code, nothing happens on click help or click bug). Is there something I need to do to be able to use it again? I realize this is a different issue but re-opening this issue as I cannot submit a new one from that page.

**Comment by SaintPeter** [comment]
It's possible that you wrote some code that loops infinitely or otherwise fails catastrophically.  You can delete your local storage's instance of your code here:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage

**Comment by carefulAxe** [comment]
Thanks so much, that fixed it. Closing this issue.
