### ISSUE TITLE
wrong external link in Create Decimal Numbers with JavaScript

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#42795]
The `href` of the external link in the challenge is `https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems` but it points to a page of a music album, the `href` should be `https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems`

Issue #40749 was asking what to do of external links to avoid such issues, if we have an article talking of this topic I would suggest we use that instead of a wikipedia link

Challenge link: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript
Challenge file: curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript.md

**Comment by raisedadead** [comment]
cc: @scissorsneedfoodtoo

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @ieahleen. We don't seem to have a good article on accuracy problems when using floating point numbers, so the Wikipedia article you suggested is a good alternative for now.
