### ISSUE TITLE
Bonfire: Symmetric Difference - Needs more test cases

### ISSUE THREAD

**Issue by CodeWingX** [FreeCodeCamp/FreeCodeCamp#4281]
Challenge [Bonfire: Symmetric Difference](http://www.freecodecamp.com/challenges/bonfire-symmetric-difference?solution=function%20sym(args)%20%7B%0A%20%20var%20filler%20%3D%20Array.prototype.slice.call(arguments)%2C%0A%20%20%20%20%20%20arr%20%3D%20%5B%5D%3B%0A%20%0A%20%20for(%20var%20i%20%3D%200%3B%20i%20%3C%20filler.length%3B%20i%2B%2B%20)%20%7B%0A%20%20%20%20for(%20var%20j%20%3D%200%3B%20j%20%3C%20filler.length%3B%20j%2B%2B%20)%20%7B%0A%20%20%20%20%20%20if(%20filler%5Bi%5D%5Bj%5D%20%3D%3D%3D%20filler%5Bi%5D%5Bj%2B1%5D%20)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20filler%5Bi%5D.splice(%20j%2C%201)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%0A%20%20%7D%0A%20%20%0A%20%20for(%20i%20%3D%200%3B%20i%20%3C%20filler.length%3B%20i%2B%2B%20)%20%7B%0A%20%20%20%20arr%20%3D%20arr.concat(filler%5Bi%5D)%3B%0A%20%20%7D%0A%20%20%0A%20%20arr%20%3D%20arr.sort()%3B%0A%0A%20%20i%20%3D%200%3B%0A%20while(%20i%20%3C%20arr.length%20)%20%7B%0A%20%20%20%20if(%20arr%5Bi%5D%20%3D%3D%3D%20arr%5Bi%2B1%5D%20)%7B%0A%20%20%20%20%20%20%20console.log(arr%5Bi%5D%20%2B%20%22%20%22%20%2B%20arr%5Bi%2B1%5D%20%2B%20%22%20%22%20%2B%20i)%3B%0A%20%20%20%20%20%20arr.splice(%20i%2C%202)%3B%0A%20%20%20%20%20%20i%20%3D%200%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20i%2B%2B%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20console.log(arr)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0Asym(%5B1%2C%201%2C%202%2C%205%5D%2C%20%5B2%2C%202%2C%203%2C%205%5D%2C%20%5B3%2C%204%2C%205%2C%205%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sym(args) {
  var filler = Array.prototype.slice.call(arguments),
      arr = [];
 
  for( var i = 0; i < filler.length; i++ ) {
    for( var j = 0; j < filler.length; j++ ) {
      if( filler[i][j] === filler[i][j+1] ){
             filler[i].splice( j, 1);
      }
    }  
  }
  
  for( i = 0; i < filler.length; i++ ) {
    arr = arr.concat(filler[i]);
  }
  
  arr = arr.sort();

  i = 0;
 while( i < arr.length ) {
    if( arr[i] === arr[i+1] ){
       console.log(arr[i] + " " + arr[i+1] + " " + i); // this would fail if there are three identical elements.
      arr.splice( i, 2); // for I'm only removing two
      i = 0;
    } else {
      i++;
    }
  }
  console.log(arr);
  return arr;
}

sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]);

```

**Comment by SaintPeter** [comment]
Confirmed.  I will build a couple more test cases for this one.
