### ISSUE TITLE
Filter Campsites per country, then alphabetically

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/FreeCodeCamp#4282]
Hi all,

Filtering the campsites per country would be way more visible as I spend quite some time trying to find a campsite near my city yesterday. This makes it immediately visible when there isn't already a campsite in my country.

https://github.com/FreeCodeCamp/freecodecamp/wiki/List-of-Free-Code-Camp-city-based-Campsites

Thanks in advance!

Kind regards,

Stein

**Comment by SaintPeter** [comment]
This seems like it might be a helpful thing.  For the short term we could re-organize the Wiki list by country and sub-division.  For the longer term, having a searchable database would be helpful.

**Comment by Stiino0** [comment]
Hi guys,

I've cloned the repo to my Desktop and am now looking up the correct countries / Continents, but there are already 500 lines haha.

I like the idea to have the geo-location "Find my closest Campsite", that'd be the easiest way for people to find a campsite!

Can I put it somewhere on Github that I'm currently "busy" with looking up information so that other people know that I'm already doing something on it? I don't want people to do the same work, that'd be counterproductive.

Cheers,

Stein
