### ISSUE TITLE
Why do tests not ignore text case?

### ISSUE THREAD

**Issue by KL13NT** [freeCodeCamp/freeCodeCamp#42825]
Looking at the linked code challenge, writing the following code passed:

```html
<input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor</label>
```

while the following doesn't pass:

```html
<input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> indoor</label>
```

Note the change from "Indoor" to "indoor".

**Update 11 July, 2021**
As per the discussion in the replies, the best thing to do now is to wait for the next version of the curriculum. See https://github.com/freeCodeCamp/freeCodeCamp/issues/42825#issuecomment-877843443 for more context.

**Affected page**
Multiple, including:
- [Use the value attribute with Radio Buttons and Checkboxes](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/use-the-value-attribute-with-radio-buttons-and-checkboxes)

**Your code**
```html
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>

  <a href="#"><img src="https://www.bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="https://www.freecatphotoapp.com/submit-cat-photo">
    <label for="indoor"><input id="indoor" type="radio" name="indoor-outdoor" value="indoor"> Indoor</label>
    <label for="outdoor"><input id="outdoor" type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label for="loving"><input id="loving" type="checkbox" name="personality"> Loving</label>
    <label for="lazy"><input id="lazy" type="checkbox" name="personality"> Lazy</label>
    <label for="energetic"><input id="energetic" type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Expected behavior**
Should pass regardless of the text case.

**System (please complete the following information):**
 - Device: Desktop
 - OS: Windows 8.1 Pro Latest
 - Browser: Chrome, Firefox, Edge
 - Version: Latest

**Comment by KL13NT** [comment]
I noticed the following:
The tests for this challenge uses

```js
$('label:contains("Indoor") > input[type="radio"]').filter("[value='indoor']")
```

I'm not sure what the `$` is, but would like to understand further. Is there no `label.toLowerCase:contains`?

**Comment by ShaunSHamilton** [comment]
@KL13NT Thank you, for taking the time to open this. However, this is probably not the best platform for general inquiries about the freeCodeCamp platform - the [forum](https://forum.freecodecamp.org/) would be better suit.

In most programming languages, and in most software use-cases, character _case_ (upper and lower) is important, and a change of case produces a different program/value. As such, it is important to be specific when learning/teaching programming. 

Currently, there are two things you should keep in mind for this lesson:
1) The lesson does not ask you to change the text value for the `label` element - in this case, and in most of the upcoming tests, changing content you are not asked to in the instructions will likely break the tests and/or output.
2) My original point - programming is case-sensitive. It would be unproductive to allow other values which change the output.

---


> I'm not sure what the `$`

The `$` symbol is commonly used to represent library classes. In this case, it is representing the jQuery wrapper. You can learn more about this in the _Front End Libraries_ certification on the platform.

---

**Comment by KL13NT** [comment]
@ShaunSHamilton This is more of a UX problem than a challenge solution, so GH is probably the best channel for it. The value of the label in this case doesn't change the output of the challenge nor the actual solution of it (it actually passes if the label isn't changed), and could rather be made entirely in mistake. A couple of my mentees have reported that it's frustrating because they like to dabble around the code to add stuff on their own, etc. This is not a requirement of FCC per se, but there's surely a better alternative. 

What I understand here is that Label Value points to having the set of characters [i, n, d, o, o, r] in the same order to represent the word "indoor", regardless of character case. This is how many people recognise it, and one of the reasons my mentees got confused. It's visual change based on a grammatical rule that FCC should ignore entirely.

As per your points:
1. The lesson doesn't ask for it, and so should impose minimal to 0 restrictions IMO. If a student solves the challenge by creating the same label in a different character case that shouldn't report back as "invalid", especially given that the student successfully solves the task "Use value attribute".
2. I beg to differ. This is not a change of value in itself, but rather a change of visual value. The label says "indoor" either way. The goal of the label is to provide information about the button, which it successfully achieves either way, either "indoor" or "Indoor". 

The confusion lies in the a question that pops up to students once they encounter this. "Does label text affect the value?".

If your POV is the one to keep then simplest solution to give this a UX fix of sorts that I can think of is to include a disclaimer that says something like "Changing the value of the label will affect the result". This won't require any change in the `--hint--` code.

**Comment by ieahleen** [comment]
> ```css
> label:contains("Indoor") > input[type="radio"]
> ```

this is a css selector, which is case sensitive
it is not easy to give freedom to users to change all they want and still allow the tests to pass, also because it becomes an issue on what we would allow and what we wouldn't. We can't allow everything, it becomes impossible to test reliably

**Comment by KL13NT** [comment]
> 
> 
> > ```css
> > label:contains("Indoor") > input[type="radio"]
> > ```
> 
> this is a css selector, which is case sensitive
> it is not easy to give freedom to users to change all they want and still allow the tests to pass, also because it becomes an issue on what we would allow and what we wouldn't. We can't allow everything, it becomes impossible to test reliably

That makes sense, yes, and I'm aware of it. The other "disclaimer" option seems like the most logical solution to this, AFAICT. It'd keep test cases as is while providing more context as to what affects test passing and what doesn't.

**Comment by ShaunSHamilton** [comment]
> The value of the label in this case doesn't change the output of the challenge

Changing text value of the label does change the output.

> > 2. My original point - programming is case-sensitive. It would be unproductive to allow other values which change the output.

> I beg to differ. This is not a change of value in itself, but rather a change of visual value. The label says "indoor" either way. The goal of the label is to provide information about the button, which it successfully achieves either way, either "indoor" or "Indoor".

My point here is to say that the instructions are specific - as they have to be in programming. The label does not say `indoor` either way, because it either says `indoor` or `Indoor`. If a client asked for it to say `Indoor`, and a programmer set it to `indoor`, this would be incorrect.

In the case of this lesson, it can be thought of a client saying: _"Take this code of mine, and add `value` attributes to all of the inputs using their text value in lowercase"_ - changing the text value is not a part of the instructions.

I am not saying the lesson/s should not be made more/less specific along with their tests. In fact, one of the main new features of the next version of the curriculum is being more specific about which code the Camper is supposed to edit. I am arguing for not making tests lenient beyond the instructions - the tests pass when the instructions are followed.

Campers are welcome to play around with the code in all sorts of lessons, but when it comes to passing the tests, the Camper should reset the lesson to its initial state, and follow the instructions. The lessons and their boilerplate are there to teach specific topics; the certification projects are there to allow freedom (outside of the user-stories) to customise projects.

This is just my opinion on the curriculum, and is all I will add to the subject 🙂

**Comment by KL13NT** [comment]
> In the case of this lesson, it can be thought of a client saying: "Take this code of mine, and add value attributes to all of the inputs using their text value in lowercase" - changing the text value is not a part of the instructions.

> I am not saying the lesson/s should not be made more/less specific along with their tests. In fact, one of the main new features of the next version of the curriculum is being more specific about which code the Camper is supposed to edit. I am arguing for not making tests lenient beyond the instructions - the tests pass when the instructions are followed.

Thanks for the clarification, @ShaunSHamilton. It makes more sense now. Do you know when can one expect the next version? All I could find searching for it is topics on the forum pre-2021. Is it in beta?

I'll update the name of the issue to reflect where this discussion is going.

**Comment by ShaunSHamilton** [comment]
> Do you know when can one expect the next version? All I could find searching for it is topics on the forum pre-2021. Is it in beta?

The next version (v7), is still under development - some of the code exists in this repository, but is not _enabled_ _per-se_. We specifically do not set/give release dates. So, I cannot say for sure when to expect it.

There are bits and pieces of information about it scattered here and on the forum, but I tend to stick to what is written in the announcement: https://www.freecodecamp.org/news/python-curriculum-is-live/

If you are really interested, you can check out the progress in the [CurriculumExpansion Repo](https://github.com/freeCodeCamp/CurriculumExpansion), as well as the outline of what is to come in the [Curriculum Google Sheet](https://docs.google.com/spreadsheets/d/1KXEJvgnAziiePMp2Ovf_ssDqCFFWYuycXWBNp91k3qM/edit?usp=sharing).

Hope this helps some

**Comment by Sembauke** [comment]
Hey @KL13NT,
After this extravagant debate between u and Shaun, I will be closing this, as we want the user to learn how to read instructions that are given by the challenges. This may help the user in further endeavors.

Happy coding 😄
