### ISSUE TITLE
Update Back-end curriculum tests to be more transparent/descriptive

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#42836]
Personally, I find it much harder to get the projects right without knowing what exactly is being tested for. Seeing the test code makes the requirements much more clear. We very often link to the tests on the forum because it really helps people better understand the requirements.

Fundamentally I guess it shows an issue with the test output and requirements not being clear enough. But letting people see the actual code their projects are being tested against isn't that unreasonable either.

**Comment by moT01** [comment]
I don't mind linking to the tests when someone asks in chat or on the forum, but I'm not sure linking them on the project pages by default is the right way to go - although, I'm open to arguments. It seems like it's probably our fault for not making things clear enough - I think it would better to try and make it clear on the project pages or whatever test suite is being used. I don't have a whole lot of other good arguments not to do it, but I am going to vote against it. Do you have an example or two of this @lasjorg? - not that I doubt you, I have done this myself - just for some examples.

**Comment by ShaunSHamilton** [comment]
The two best things I can think for the backend-style tests are:
- Being persistant to encourage Campers to use the browser devtools (console for assertion errors, and network tab for... _well_ ...)
- Displaying the test output to the Camper: https://github.com/freeCodeCamp/freeCodeCamp/pull/40860 

The issue with the latter is many of the tests will need to be re-written to correctly throw the assertion output errors, and the PR never took off, because of i18n concerns (trouble easily integrating). Also, with the new curriculum/VSCode-in-browser, I am unsure how worthwhile putting tonnes of time into implementing the latter would be 🤷‍♂️ .

@moT01 You are in the best position to comment on the VSCode/i18n integration. Have we discussed how this would work?

**Comment by moT01** [comment]
There's a [start to a discussion here](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/21) on how to translate the instructions and hints. The test text/assertion errors will probably not be able to get translated. I suppose we could look into it, but it wouldn't be a priority for at least a little while.

**Comment by lasjorg** [comment]
Ideally the requirements and assert messages might be enough.

Most TDD style code kata challenge sites have sample tests you can test against. Not seeing the tests is a bit like doing TDD in the blind, with only requirements and assert messages. It would be nice if the challenges had some sample tests, not only to better understand the requirements but also to give something to manually test against.

The most obvious example I can think of is the URL validation in the URL Shortener Microservice challenge.

> If you pass an invalid URL that doesn't follow the valid `http://www.example.com` format, the JSON response will contain `{ error: 'invalid url' }`

An example of an invalid URL would be nice. If I go to [the tests](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice.md) I can see the URL tested against.

Linking to the tests is more of a lazy (temporary?) solution to this issue. But I understand the hesitancy to do so. It would be nice if the platform better supported showing the running tests but I realize that is a big ask. Not sure what the plans are for the updated curriculum with the code editor setup. It would be super nice to have a setup like Codewars.

---

I think it's safe to say people struggle with our backend project and I don't think it is unfair to point out that we are in part to blame for this. I know we have made updates to the backend project but I still think they are problematic.

**Comment by nhcarrigan** [comment]
We could potentially update the tests to be more like the front end tests:

`Passing the url daas;dlkfjadslkj shouldreturn { error: 'invalid url' }`

**Comment by moT01** [comment]
I am in favor of changing the test text to be more specific, the URL shortener example could be changed to something like: 
```
If you pass an invalid URL that doesn't follow the valid http://www.example.com format, such as `url=ftp:/john-doe.org`, the JSON response will contain { error: 'invalid url' }
```
Certainly, the other tests could probably be better, as well - they will have to be fixed on a case-by-case basis as they come up I think. For now, maybe just fix this one.

**Comment by ahmaxed** [comment]
This feature has been introduced in the upcoming curriculum.
