### ISSUE TITLE
Error emissing ) after argument list when clicking run test button

### ISSUE THREAD

**Issue by Chrixos** [FreeCodeCamp/FreeCodeCamp#4285]
Guys I tried following the instructions on clearing storage, opening a private window prior to creating a new issue but no luck, no good, the error still is there. I dont know if this is a browser error but I suspect a bug.

![image](https://cloud.githubusercontent.com/assets/12056435/11069925/920c5d2e-87b7-11e5-90a1-6170a03f1352.png)

Challenge [Waypoint: Target the same element with multiple jQuery Selectors](http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%24(%22button%22).addClass(animated)%3B%0A%20%20%24(%22.btn%22).addClass(animated%20shake)%3B%0A%20%20%24(%22%23target1%22).addClass(btn-primary)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
  $("button").addClass(animated);
  $(".btn").addClass(animated shake);
  $("#target1").addClass(btn-primary);
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

Bottomline is: I am kind of stuck and cannot move forward, let alone that the last piece of jQuery code might be incorrect but that should not be an issue.

**Comment by Chrixos** [comment]
Irrespective of browser and or incorrect typed jQuery code, the display on the right vanished completely and the list of tasks red/green they are gone too.

**Comment by BerkeleyTrue** [comment]
Try wrapping strings in quotes:
```js 
 $(document).ready(function() {
  $("button").addClass('animated');
  $(".btn").addClass('animated shake');
  $("#target1").addClass('btn-primary');
  });
```

Happy Coding!

**Comment by Chrixos** [comment]
Thanks

2015-11-10 15:47 GMT-03:00 Berkeley Martinez <notifications@github.com>:

**Comment by Chrixos** [comment]
It worked beautifully, thanks B!

**Comment by BerkeleyTrue** [comment]
Yay :blush:

**Comment by hushhoney** [comment]
Hi im getting the same kind of problem but a couple of exercises before yours! 

![untitled3](https://cloud.githubusercontent.com/assets/15873524/11212718/6aa7fa2c-8d2f-11e5-93ed-a5045677d15f.jpg)

**Comment by Chrixos** [comment]
Hey hushhoney can you tell me which waypoint challenge number is the one you are having a problem with? That way I can try to help you :)

Thanks and happy coding

**Comment by bugron** [comment]
@hushhoney, please, note that [we officially support only Chrome browser](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2942#issuecomment-136591448), latest Firefox is good to go too. In IE/Edge challenges won't work at all!

**Comment by Chrixos** [comment]
@bugron, looks like she was able to pass many challenges with IE.

**Comment by bugron** [comment]
@Chrixos I mean bonfires won't work and not all the challenges, my bad. @hushhoney are there any errors/warnings in your browser's console?

**Comment by hushhoney** [comment]
yeah i'm working on IE and unfortunately I'm on a works computer and cant download other browsers, quite disappointing is this going to be something that will be fixed in the future? maybe there should be some warning sign on the site that it only works properly on google chrome, so people like me don't spend half there day wondering what there doing wrong ha!

**Comment by hushhoney** [comment]
but as @Chrixos said ive managed to pass 109 challenges on IE

**Comment by bugron** [comment]
As I said I was talking about bonfires. IE/Edge doesn't support some features used in FCC. If MS add those in future that would be great. And about the warning we have a [feature request](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3976). Hopefully, this will be implemented soon.

**Comment by hushhoney** [comment]
Fingers crossed!!

**Comment by Chrixos** [comment]
@hushhoney If you need help, let alone that IE might work or not with some challenges, let us know.
