### ISSUE TITLE
This FCC test shouldn't pass, but passes anyway.

### ISSUE THREAD

**Issue by danzel-py** [freeCodeCamp/freeCodeCamp#42852]
**Affected page**
https://www.freecodecamp.org/learn/information-security/information-security-projects/anonymous-message-board

**Your code**
My .env is still commented, functional testing aren't even commenced.
```
# NODE_ENV=test
```

**Expected behavior**
Shouldn't pass the FCC tester's last test but it did:
>All 10 functional tests are complete and passing.

**Screenshots**
![Screenshot 2021-07-14 at 16 15 59](https://user-images.githubusercontent.com/67574872/125579585-03314f07-df81-4b2b-9fcc-fa00f3eba371.png)

**System (please complete the following information):**
 - Device: Macbook
 - OS: macOS 10.15.5 (19F101)
 - Browser: Google Chrome
 - Version: 91.0.4472.114 (Official Build) (x86_64)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this. This is expected behaviour, as not all the tests for this project have been written yet.

As such, I am going to close this issue. Thank you.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/41323
