### ISSUE TITLE
Waypoint: Set the ID of an Element

### ISSUE THREAD

**Issue by viviannealves** [FreeCodeCamp/FreeCodeCamp#4286]
Give your form element the id cat-photo-form.

Give your form element the id of cat-photo-form.

How to do it???

**Comment by SaintPeter** [comment]
If you are stuck on a Waypoint, please use the "Help" button to ask for help on the Gitter Chat Rooms.  

For waypoints you can access the help room directly at:
https://gitter.im/FreeCodeCamp/Help

**Comment by jundc1006** [comment]
<form id="cat-photo-form">I think there's a bug because when I try to submit the answer , it doesn't respond.
