### ISSUE TITLE
User profile icon blocks other elements in the navbar

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#42861]
https://forum.freecodecamp.org/t/469271

![image](https://user-images.githubusercontent.com/1884376/125672375-8f9b2063-173a-4bcf-8c34-d9b9a182a308.png)

This is presumably because of a CSS API that is not available in a lot of legacy browsers. I have seen this being reported one too many times on the forum.

**API in question:**

https://github.com/freeCodeCamp/freeCodeCamp/blob/de2f4e2843ef7ae6609f098f482d0aaa86057829/client/src/components/Header/components/universal-nav.css#L190-L192

caniuse: https://caniuse.com/css-display-contents

We need to resolve this with a more compatible solution.

**Comment by lasjorg** [comment]
Maybe there is some special case for this I'm not seeing, but `display: flex` seems to work just as well. I didn't look too much at this, like check if the CSS is used elsewhere, so I might be missing something.
