### ISSUE TITLE
"Help improve or add subtitles" is hidden on the video challenges

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#42870]
**Affected page**
Add a Link to the page with the problem.

https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/intermediate-strings

**To Reproduce**

1. Go to https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/intermediate-strings
2. See the video
3. The text "Help improve or add subtitles" is obscured by the video 

**Expected behavior**
Either this text should be visible or the code should be removed.

**Screenshots**

The text is underneath this corner of the video.
![image](https://user-images.githubusercontent.com/15801806/125794798-4d14bfb4-d297-4330-8d31-2a87310659f7.png)

**Comment by ieahleen** [comment]
YouTube doesn't allow anymore for crowd sourcing subtitles
If we don't have a different alternative it should be to remove
