### ISSUE TITLE
Typo in first assert's error message

### ISSUE THREAD

**Issue by jonslucas** [FreeCodeCamp/FreeCodeCamp#4288]
Challenge [Waypoint: Make Unique Objects by Passing Parameters to our Constructor](http://www.freecodecamp.com/challenges/waypoint-make-unique-objects-by-passing-parameters-to-our-constructor) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

First assert message currently has:
"'message: Calling <code>new Car(3,1,2)</code> should produce and object with a ..."

Should be this instead:
"'message: Calling <code>new Car(3,1,2)</code> should produce an object with a ..."

**Comment by bencassidy** [comment]
Wrote a fix here https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4290

**Comment by jonslucas** [comment]
My mistake, I should have included that I had a pr with the fix -> #4289

**Comment by bencassidy** [comment]
oh ok cool, I'll close mine
