### ISSUE TITLE
Typo/Incorrect and misleading explanation on AVL Insertion process

### ISSUE THREAD

**Issue by trooms** [freeCodeCamp/freeCodeCamp#42884]
**Describe your problem and how to reproduce it:**

"If there is an imbalance in left child of right subtree, then you perform a left-right rotation.
...
If there is an imbalance in right child of left subtree, then you perform a right-left rotation"

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/avl-tree-insertion-rotation-and-balance-factor/

**Recommended fix, suggestions (how would you update it?):**

"If there is an imbalance in left subtree's of right child, then you perform a left-right rotation.
...
If there is an imbalance in right subtree's of left child, then you perform a right-left rotation"

I would use this wording as it is how the lecturer does so in the embedded video. It  currently gives incorrect instructions.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this.

I have emailed the editorial team at `editorial<at>freecodecamp.org`, and one of the team will close this issue, once this is investigated further/resolved.

**Comment by raisedadead** [comment]
Closing, now that we email the editorial team for these. See templates: https://github.com/freeCodeCamp/freeCodeCamp/issues/new/choose
