### ISSUE TITLE
Viewing URL Cert solutions brings up JS solution modal

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#42900]
I'm not sure if this was deliberately added at some point, I'm guessing not - but viewing a cert solution for any cert brings up the JS code viewer with the URL in it when a URL is used to submit the project...
![Screen Shot 2021-07-16 at 8 53 03 AM](https://user-images.githubusercontent.com/20648924/125959026-199e5e42-4afa-400b-a428-65f6bb343762.png)

Go [here](https://www.freecodecamp.org/certification/mot01/responsive-web-design) 
View a solution
See modal

Possibly from this recent PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/42717 - I swear I tested it

**Comment by ShaunSHamilton** [comment]
My bad. This line probably needs to change:

```diff
- if (files) {
+ if (files.length) {
```

**Comment by awu43** [comment]
@ShaunSHamilton I just tried implementing your solution, but then realized I didn't know how to test if it worked without sign in/user data. How should that be done?

**Comment by moT01** [comment]
You should be able to log in - assuming the [LOCAL_MOCK_AUTH](https://replit.com/@moT01/boilerplate-arithmetic-formatter) is set to true in your .env file. Then you can submit some projects, many of them can just be a URL and don't have any requirements. I believe the responsive web design, front end libraries, and data visualization don't require passing tests. So you should be able to get a cert like that and then go view it.

**Comment by awu43** [comment]
Turns out that somewhere along the line I broke the dev user on my machine. GitPod still works fine though, so it's been tested there.
