### ISSUE TITLE
Adjust superBlock folder naming schema

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#42902]
There's a few related comments and inspiration for the issue [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/42885#issuecomment-881205743)
Basically, we want to improve the [folder names of the superblocks](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english)

Some possible approaches:
- Remove the numbers entirely

- Rename Certificates to 00
Rename Coding Interview to 99
Space out the rest of them for easy additions of new certs?

Things to consider:
- Renaming these might break some crowdin scripts or something

**Comment by nhcarrigan** [comment]
I have some concerns about the use of the numbering system to maintain the order of the superblocks in the file tree. Primarily, my concern is that it is entirely possible we want to add a superblock *between* two existing superblocks, which would mean we either:
- assign the next number in the list and create a disparity between the file tree and the rendered order
- assign the correct ordinal number and then rename all subsequent superblocks to increment the order.

Either approach has issues and leads to potential overhead or confusion. IMHO, doing away with the numbering system would be the best approach.

**Comment by moT01** [comment]
We will definitely need to put the relational database cert right after the front end libraries or data viz. That's right in the middle of the others. The future plan is to combine data viz and front end libraries, but I don't think that will happen before the relational databases is ready. So, it's going to be a problem soon. If we use the correct number for it, we would have to renumber all subsequent superblock's like @nhcarrigan mentioned. This seems like the wrong way to go - having to rename them all each time. I am fine with removing the numbers - another solution might be to space them out, like I mentioned in the issue description. i.e. 10, 20, 30... instead of 1, 2, 3... the numbers wouldn't match the order they appear, but they would be in the correct order they appear. And we could nest new certificates in between existing ones. I think I prefer removing the numbers - but there's another solution if it turns out removing them would be problematic or something.

**Comment by nhcarrigan** [comment]
I think that approach still leaves some room for issues in the future, though less likely.

Aside from the convenience of things being in order, I don't see an issue with removing the numbers - finding the superblock shouldn't be too difficult with them being in alphabetical order. The one nice-to-have with the number approach is it provides a clear outline on Crowdin for the order to translate things in.

We could also name the certificates folder to something like `_certificates` so it is always hoisted.

**Comment by nhcarrigan** [comment]
Closing in favour of above linked issue.
