### ISSUE TITLE
Firefox ESR breaks rendering on news pages

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#42915]
**Affected page**
Add a Link to the page with the problem.

All pages on news.

**To Reproduce**

1. Go to any page on news.
2. See the text is superimposed.

**Expected behavior**

The text and article should render correctly.

**Screenshots**
If applicable, add screenshots to help explain your problem. you can drag and drop, png, jpg, gif, etc. in this box.

![image](https://user-images.githubusercontent.com/1884376/126029671-7b1e3027-b8d8-4f56-adab-f6b47862847e.png)

**System (please complete the following information):**
 - Device: [e.g. iPhone6, Laptop]
 - OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
 - Browser: Firefox ESR desktop version 78.12.0esr (64-bit)
 - Version: 78.12.0esr (64-bit)

**Additional context**

I have not reproduced this myself, we got a report over email.

**Comment by moT01** [comment]
I downloaded this version of firefox and cannot reproduce it either.

**Comment by raisedadead** [comment]
Thanks for confirming.
