### ISSUE TITLE
Split screen snaps back/forward when adjusted forward/backward

### ISSUE THREAD

**Issue by Mush-A** [freeCodeCamp/freeCodeCamp#42924]
**Affected page**
All pages with code editors

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api.'
2. Slide the adjustable split screens
3. Split screen snaps back or forward if the split-screen was pulled forward or back respectively

Related behaviour:

1. Go to 'https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api.'
2. Slide the adjustable split screens
3. Now click the Code Editor
4. Type a character
5. Split screen snaps back or forward again

**Expected behaviour**
Split-screen should not snap backwards or forwards 

**Screenshots**
(https://imgur.com/a/IURLxOX)

**System (please complete the following information):**
 - Device: [HP laptop]
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version: [Version 91.0.4472.124 (Official Build) (64-bit)]

**Additional context**
Was able to reproduce Error on MS EDGE on the Same device
Was able to reproduce Error on Chrome on an Ubuntu device

**Comment by Sembauke** [comment]
This does seem to appear on the freecodecamp.org website but I am unable to reproduce this locally.

**Comment by ShaunSHamilton** [comment]
> This does seem to appear on the freecodecamp.org website but I am unable to reproduce this locally.

I was able to reproduce this locally, when I tested 3 days ago. However, I did not get anywhere in terms of finding a fix.

**Comment by Sembauke** [comment]
I am able to reproduce it when I throttle my network connection in the dev tools somehow.
