### ISSUE TITLE
Im getting syntax error when i use spread operator

### ISSUE THREAD

**Issue by umerrauf6** [freeCodeCamp/freeCodeCamp#42925]
console.log(h1.parentElement.children)

[....h1.parentElement.children].forEach(el => {
  console.log(el)
});

**Comment by Sembauke** [comment]
Hey @umerrauf6,

You can ask these types of questions at https://forum.freecodecamp.org/ .

Tip: when opening a new topic on the forum please give us some more info on what you are trying to do.

Thank you and have a nice day :smile:
