### ISSUE TITLE
Potential i18n bug when renaming curriculum files

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#42938]
A [recent PR of mine](https://github.com/freeCodeCamp/freeCodeCamp/pull/42885) renamed only the English version of a curriculum file. I was trying to `npm run develop` the site locally in Italian and got this:

<img width="569" alt="Screen Shot 2021-07-19 at 9 35 11 PM" src="https://user-images.githubusercontent.com/20648924/126255366-32ae2ebf-47e6-446e-819c-22af3c98b54f.png">

So my PR was in with the new filename in English and all the other locales had the old filename. So an error was thrown. I guess I'm wondering if PR's like that should rename all the languages. If so, we could perhaps add something to the action that says "Looks like you renamed an English file, you should rename all the others"

The other languages will be updated on the next pull from crowdin I suppose, fixing everything. But this would block us from deploying until that is fixed, no? So it seems like we could try and catch that. Not sure, maybe I'm missing something.

**Comment by raisedadead** [comment]
@nhcarrigan mind taking a look and coming up with some sort of playbook guidelines when we rename things. This is going to be a use case in a lot of the PRs.

**Comment by nhcarrigan** [comment]
Yep - I'll get something put together and PR for the docs.
