### ISSUE TITLE
E2E Tests for Email-Sign-Up

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#42946]
Largely, to prevent another #42708 we should add tests for the email sign up page.

This would involve either: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/scripts/seed/seedAuthUser.js
a) Editing a user to have the `acceptedPrivacyTerms` be `false`
b) Creating a new test user with the same

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by christianztamayo** [comment]
@ShaunSHamilton I'd like to take a stab at this. Would editing `authUser` or `blankUser`'s `acceptedPrivacyTerms` to `false` break other tests?

**Comment by ShaunSHamilton** [comment]
@christianztamayo Thank you, for your interest in contributing.

> Would editing authUser or blankUser's acceptedPrivacyTerms to false break other tests?

Off the top of my head, yes. (_maybe not `blankUser`_) The easiest way to find out would be to change it and locally run the tests.
