### ISSUE TITLE
Code graph(contributions) on Portfolio page is not accurate

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#4295]
I just noticed that the code timeline/graph on the user's portfolio page is not accurate. As with GitHub, I think the map color changes, or should change, according to the contributions of that day relative to all the contributions over time.

A short description of the problem:
14 items on November 8 has the same color as 97 items as November 10 as 4 items on August 27th. The only items that, I think, are colored differently are 1 item each on September 22 and September 26.

Here's my FreeCodeCamp portfolio link: http://www.freecodecamp.com/Manish-Giri

I tried logging out of my profile and visiting my profile, while logged out, from different browsers. Same result.

**Comment by SaintPeter** [comment]
The colors are not meant to represent any relative value.  The lightest color represents one item, increasing in shade by one for each up to 4, which is the darkest.

The issue with making relative coloring is that it is very common for users to go through 60-80 initial waypoints, but slow down significantly with later sets.  Using 80 as high would guarantee that all future numbers would be the lightest color possible.

Please let us know if you have further questions.  Thanks and happy coding!
