### ISSUE TITLE
Create a Media Query - a Chinese user wrote right code but couldn't pass the test

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#42966]
**Affected page**
https://chinese.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/create-a-media-query

**Your code**

```
<style>
p {
  font-size: 20px;
}

/* 只修改这一行下面的代码 */
@media (max-height:800px) {
  p {font-size: 10px;}
  }
/* 只修改这一行上面的代码 */
</style>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tempus massa. Aenean erat nisl, gravida vel vestibulum cursus, interdum sit amet lectus. Sed sit amet quam nibh. Suspendisse quis tincidunt nulla. In hac habitasse platea dictumst. Ut sit amet pretium nisl. Vivamus vel mi sem. Aenean sit amet consectetur sem. Suspendisse pretium, purus et gravida consequat, nunc ligula ultricies diam, at aliquet velit libero a dui.</p>



```

**Expected behavior**
The code looked good and worked for me (MacOS, Chrome). As the user said, the first word (@media?) was not identified on his end, so he couldn't pass the test.

**System (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser: QQ
 - Version: 10.5.2

**Comment by ieahleen** [comment]
this is one of the challenges that would benefit from #42373 most

the code is correct and it passes, but there are often browser settings or extensions, or maybe an older browser version that interferes and then it doesn't pass

**Comment by ShaunSHamilton** [comment]
@ieahleen This challenge already makes use of the new CSSHelp function.

@miyaliu666 Are you able to try this on Safari? If it is going to fail anywhere, it would be there. Otherwise, as Ilenia mentioned, it sounds like an old browser version.

**Comment by moT01** [comment]
I could not reproduce this on firefox or safari.

**Comment by miyaliu666** [comment]
It works for me on Safari. I'll let the user check his browser or change another one. Thanks!

**Comment by nhcarrigan** [comment]
@miyaliu666 is this good to close?

**Comment by miyaliu666** [comment]
> @miyaliu666 is this good to close?

Yes, he changed browser and passed the test. Thanks!
