### ISSUE TITLE
Portuguese Translation Breaks Challenge

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#42974]
File: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/portuguese/02-javascript-algorithms-and-data-structures/basic-javascript/understanding-undefined-value-returned-from-a-function.md

Forum post: https://forum.freecodecamp.org/t/what-is-wrong-could-someone-help-me-please/470438

**Issue**
Test has been converted (presumably by Crowdin) to `pre` tags:
````markdown
Dentro da função `addFive`, você deve adicionar `5` à variável `sum<code>.</p>

<pre><code class="js">assert(
  __helpers.removeWhiteSpace(addFive.toString()).match(/sum=sum\+5|sum\+=5/)
);
`</pre>
````

@nhcarrigan Pinging to help investigate how this happened.

**Comment by nhcarrigan** [comment]
This is odd. The only broken language for this file appears to be Portuguese, and I'm not entirely sure why.
It might have been a hiccup in their markdown parser.
