### ISSUE TITLE
/news author pages are not validating correctly on Twitter

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#42977]
**Describe the bug**
freeCodeCamp author pages are not showing up correctly with large Twitter cards when people share them.

**To Reproduce**
You can take an author card URL like this one: https://www.freecodecamp.org/news/author/kolade/

And plug it into Twitter's validator and see that it does not create a large Twitter card. @ahmadabdolsaheb @scissorsneedfoodtoo I think this is just a meta property we can update in our template. Even if we don't fix this in Ghost we want to be sure it's fixed in 11ty. 

![Card_Validator___Twitter_Developers_🔊](https://user-images.githubusercontent.com/985197/126700066-dfbf7c15-6a03-4a87-8062-79a5823434a2.png)

**Comment by ahmadabdolsaheb** [comment]
Kris's pr takes care of this.
