### ISSUE TITLE
What's wrong with this code?

### ISSUE THREAD

**Issue by jatinderKaur** [FreeCodeCamp/FreeCodeCamp#4298]
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

oldArray = oldArray.filter(function(val){
 return val > 5;
});

// Only change code above this line.

(function() { return oldArray; })();

**Comment by jatinderKaur** [comment]
trying to do this exercise:
Use filter to remove all elements from array that are greater than 5.

Hitting issue with:
You should have removed all the values from the array that are greater than 5.

**Comment by SaintPeter** [comment]
We have help rooms to assist you with code.  Please hit the "help" button to bring up the appropriate help room.

Filter keeps items for which the callback function returns true.  With `val > 5` you will keep items for which the function evaluates as true.  7 is greater than 5, thus returns true and is kept.  Your logic is backwards.

Happy Coding!
