### ISSUE TITLE
Add editor wrapper object for solutions testing

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4299]
Enable automated testing with a faux editor object.

**Comment by BerkeleyTrue** [comment]
@SaintPeter Any ideas?

I'm thing something like `var code = editor.get('js')`

This will allow us to specify files as well. `editor.get('foo.js');`, `editor.get('bar/biz.js');`

**Comment by SaintPeter** [comment]
`var code = editor.get('js');`
This works for me.

How about if the element that is being searched for 'js', 'html', or 'css' is not present specifically, it returns everything it has? And/Or make the string a wildcard?  

So if I do:
`editor.get('js')` it will return a generic 'js' editor, or all of the files that have `js` in them, but if it can't find anything that matches, it returns everything?

Later, when we move to a multi-file view, it will still work and be more tightly coupled.

This will still return a string, right?

So we can do:
`assert(editor.get('js').match(/regExHere/).length > 0, 'You must have a regExHere present')` 

Random thought:
Why do we have to do `editor.get(X)`, why not:
`editor('js').match(//)`?

What other functions might `editor` have?  If the only thing it's ever doing is pulling a string (the `get` function), why not just make it a function?

**Comment by BerkeleyTrue** [comment]
@SaintPeter Yeah it can just be a function (my preference). Another thing that bothers me is calling it `editor`. Something more appropriate would be `getCode('js')` (naming things is hard).

**Comment by SaintPeter** [comment]
So:
New way of doing things would be `getCode('js')`.
`editor` should be pre-populated to `editor  = getCode('*')` during the test-challenges?

Or we just do a global search and replace on the keyword `editor`?

I think we want drop in backwards compatibility for now.

**Comment by BerkeleyTrue** [comment]
yeah I think `getCode('js')` is the way of the future!

We can have backward compatibility.

**Comment by SaintPeter** [comment]
I'm wondering if we should have aliases for `getCode('html')` and 'getCode('js')` so they all point to the same thing for now?  That way we can fully specify what we want to test against but still have it work today.

**Comment by BerkeleyTrue** [comment]
sounds like a plan

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale. If someone gets the bandwidth for this we can reopen it.
