### ISSUE TITLE
Link to Forum on italian Menu

### ISSUE THREAD

**Issue by dottorgross** [freeCodeCamp/freeCodeCamp#42991]
**Affected page**
https://www.freecodecamp.org/italian/

**To Reproduce**

1. Click on 'Menu'
2. Click on 'Forum'
3. See error

**Expected behavior**
It should open
https://forum.freecodecamp.org/c/italiano/535

**System (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Comment by gikf** [comment]
The same issue is for Portuguese.
