### ISSUE TITLE
Babel transpiles out syntax errors?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#43006]
Just a question based on this [forum post](https://forum.freecodecamp.org/t/object-property-with-bracket-and-dot-notation-test-failure/470688). Is that just an edge case or what?

**Comment by ShaunSHamilton** [comment]
Seems `@babel/eslint-parser` allows it: https://astexplorer.net/#/gist/4155e2fa3e78133802cecb4ace3ceadb/6e051ec87a3c59b4e1428a60009b19e9ad5e971d

**Comment by lasjorg** [comment]
The issue is, it is allowing for invalid syntax and making tests pass that should fail.

**Comment by ShaunSHamilton** [comment]
> The issue is, it is allowing for invalid syntax and making tests pass that should fail.

Right. Short of adding onto the plugin, I cannot think of a way to resolve this.

**Comment by ojeytonwilliams** [comment]
Sounds like we'd have to check the source and use regex, which isn't great.

**Comment by nhcarrigan** [comment]
Hey folks,

Are we considering this as an edge case and wontfix? Or are we going to move forward with the regex approach?
