### ISSUE TITLE
My function returns [5, 27, 39, 1000], but its wants it to return [27, 5, 39, 1000], it solves the issue at hand but is being checked against the wrong driver it seems. 

### ISSUE THREAD

**Issue by ericksong9** [FreeCodeCamp/FreeCodeCamp#4300]
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays?solution=function%20largestOfFour(arr)%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20%20%20var%20arr2%20%3D%20%5B%5D%3B%0A%20%20var%20holder%3B%0A%20%20var%20max%20%3D%200%3B%0A%20%20arr.forEach(function(val)%7B%0A%20%20%20%20val.forEach(function(val2)%7B%0A%20%20%20%20%20%20if%20(val2%20%3E%20max)%7B%0A%20%20%20%20%20%20%20%20max%20%3D%20val2%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D)%3B%0A%20%20%20%20arr2.push(max)%3B%0A%20%20%7D)%3B%0A%20%20arr%20%3D%20arr2%3B%0A%20%20return%20arr%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function largestOfFour(arr) {
  // You can do this!
    var arr2 = [];
  var holder;
  var max = 0;
  arr.forEach(function(val){
    val.forEach(function(val2){
      if (val2 > max){
        max = val2;
      }
      
    });
    arr2.push(max);
  });
  arr = arr2;
  return arr;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by HermanFassett** [comment]
There's actually nothing wrong with the test, you're just missing something important in the code. Make sure you reset max after you push it, otherwise, for following arrays, val2 might never be greater than max and will return the old max value.

**Comment by BerkeleyTrue** [comment]
@HermanFassett Thanks!

Happy Coding!
