### ISSUE TITLE
Update README to link to specific blocks

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#43010]
The links to curriculum blocks in the [main README file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/README.md#1-responsive-web-design-certification) all just link to the top of the superblock page. We could link to the specific blocks with something like https://www.freecodecamp.org/learn/responsive-web-design/#basic-html-and-html5. Unless there's a reason we wouldn't want to do that, seems like a good first timer issue.

**Comment by ShaunSHamilton** [comment]
> Unless there's a reason we wouldn't want to do that

Probably no reason, bar it is _slightly_ more maintenance if any block link changes - hardly a reason not to.
