### ISSUE TITLE
Documentation to work over https

### ISSUE THREAD

**Issue by vtamara** [FreeCodeCamp/FreeCodeCamp#4302]
I cannot find how to make it work for example with a nginx proxy or to run it directly over  https.
 

My initial attempts over nginx didn't work.

**Comment by SaintPeter** [comment]
Missing context or not apparent connection to Free Code Camp.

Feel free to add additional details and re-open this issue.

**Comment by vtamara** [comment]
Short term, I would like that spanish speakers that need, could see what has been translated of the challenges up to now (but telling them to send their answers to freecodecamp.com in english for certification).    The primary group of users that need this is non-english speaker with who I work voluntarely every saturday in San Nicolás, Soacha, Colombia, see: https://www.facebook.com/danzadoresdeJesucristo/?ref=hl   I have promoted this space in Free Code Camp Bogota.

I guess this will increase motivation to translate to spanish (at least for me, but could be also with other translators or future translators).

Longer term ideas I guess I will share with Quincy when I can contribute more to the sources and when I finish full stack certification (I already have front-end certification), see my simple contributions at: https://github.com/FreeCodeCamp/FreeCodeCamp/commits?author=vtamara

By the way I work everything open source as you can see in my github profile.

**Comment by vtamara** [comment]
I don't see way to reopen.

**Comment by SaintPeter** [comment]
To be clear:  You're talking about needing https access to the Free Code Camp site?

**Comment by SaintPeter** [comment]
After further reading -
You appear to be asking for support on running an instance of the FCC site on nginx.  We cannot support other installations of FCC.  The site/wiki documentation should be sufficient to install a local copy.  That is the limit to the support we can give.

Happy coding!
