### ISSUE TITLE
Missing word in APIs and Microservices Intro

### ISSUE THREAD

**Issue by Lochoa11** [freeCodeCamp/freeCodeCamp#43027]
https://github.com/freeCodeCamp/freeCodeCamp/blob/6fac38ef7d724efc469f7918a9e5013210e1f39c/client/i18n/locales/english/intro.json#L293

In this paragraph it seems like the word "apps" in line **293** it could want to say `...write back end-ready apps with Node.js...`

**Comment by Sembauke** [comment]
Issues labelled with help wanted or first timers only are open for contributions.

Please make sure you read our guidelines for contributing. Join us in our chat room or the forum if you need help contributing, our moderators will guide you through this.
