### ISSUE TITLE
Unclear explanation- should be "return the non common element(s) in the set of two arrays"

### ISSUE THREAD

**Issue by tesla809** [FreeCodeCamp/FreeCodeCamp#4304]
The description for the challenge is vague. The wording could be clearer. I'd use "return the non common element(s) between two given arrays" or something like that.

Challenge [Bonfire: Diff Two Arrays](http://www.freecodecamp.com/challenges/bonfire-diff-two-arrays?solution=function%20diff(arr1%2C%20arr2)%20%7B%0A%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20Same%2C%20same%3B%20but%20different.%0A%20%20return%20newArr%3B%0A%7D%0A%0Adiff(%5B1%2C%202%2C%203%2C%205%5D%2C%20%5B1%2C%202%2C%203%2C%204%2C%205%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function diff(arr1, arr2) {
  var newArr = [];
  // Same, same; but different.
  return newArr;
}

diff([1, 2, 3, 5], [1, 2, 3, 4, 5]);

```

**Comment by ltegman** [comment]
Thanks for the report! The current wording for this challenge actually came after the last wording was considered too confusing. I personally think the suggested wording would actually make it more confusing for me. I'm leaving this open for discussion to get some more opinions.

**Comment by SaintPeter** [comment]
How about:
```
Compare two arrays and return a new array with items found in only one of the input arrays.
```

**Comment by tesla809** [comment]
That could mean I return everything in one array, regardless of similarity between both. 

I could return 
array1 = [1,2,3,4];
array2 = [4,5,6,7];

And just return 

array3 = array1.

Return array3.

The definition doesn't mention anything about returning the Intersection of two sets. 

Better to state: return the intersection of the two arrays, be link the mathematical definition for exactitude.

See:
https://en.m.wikipedia.org/wiki/Intersection_(set_theory)

**Comment by faizaanceg** [comment]
Why don't we just say Intersection of two arrays? I know it goes into Math territory but programming does require Math knowledge. Union, Intersection are very basic concepts and plus this is a Bonfire and not a Waypoint, so the student would already have some expertise in programming.

**Comment by SaintPeter** [comment]
> Why don't we just say Intersection of two arrays?

@faizaanceg Unfortunately, the poor American educational system will render all but a few math majors able to answer the question.  Set theory is not part of the standard educational curriculum.

**Comment by faizaanceg** [comment]
Oh ok, wow. Is it that bad? :/ 

What about

> Return those elements which are in only one array?

**Comment by tesla809** [comment]
Not really. But at least to me its non intuitive. If I am the only one with problems, then its probably just me then.
