### ISSUE TITLE
Fix lighthouse accessibility issues for publication

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#43054]
We only have 2 outstanding accessibility issues with freeCodeCamp's publication. If we can finish these, we will get the coveted 100% accessibility score 😄 

![Cursor_and_How_to_Use_Webmentions_with_Gatsby_js_–_A_Beginner_s_Guide](https://user-images.githubusercontent.com/985197/127372096-9ae71c2e-b934-484e-b320-48bee3e76a12.png)

**Comment by scissorsneedfoodtoo** [comment]
I was able to fix some of the issues in the [affected article](https://www.freecodecamp.org/news/how-to-use-webmentions-with-gatsby-beginners-guide/), and fixed what I could:

![image](https://user-images.githubusercontent.com/2051070/127600743-2cb1ea61-75d4-45ca-a8b6-749b4df6b164.png)

The last issue is referring to the contrast of some of the Prism.js code highlights. This is also an issue on /learn, and we'll need to tackle these in separate PRs.

I also did an audit of the most recent articles and everything in the footer.
