### ISSUE TITLE
Use Caution When Reinitializing Variables Inside a Loop needs stronger tests

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#43050]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/use-caution-when-reinitializing-variables-inside-a-loop

## Your code

```
function zeroArray(m, n) {
// Creates a 2-D array with m rows and n columns of zeroes
let newArray = [];
let row = [];
for (let i = 0; i < m; i++) {
  // Adds the m-th row into newArray

  for (let j = 1; j < i; j++) {
    // Pushes n zeroes into the current row to create the columns
    row.push(0,0);
  }
  // Pushes the current row, which now has n zeroes in it, to the array
  newArray.push(row);
}
return newArray;
}

let matrix = zeroArray(3, 2);
console.log(matrix);
```

[code from this forum topic https://forum.freecodecamp.org/t/reinitializing-variables-inside-a-loop-solution/471296 ]
## Expected behavior

It shouldn't pass.

## Additional context

Maybe we need to add one other test with different arguments to avoid this hardcoding way to pass the challenge.

**Comment by Nirajn2311** [comment]
Yes, I agree that adding another test with different arguments will prevent the hardcoding issue. I'll go ahead and mark this as a first timers issue.

**Comment by ManasviGoyal** [comment]
i would like to work on this. can you pls help me get started?

**Comment by ieahleen** [comment]
Hello @ManasviGoyal,
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
