### ISSUE TITLE
Translate the hints of challenges

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#43067]
## Is your feature request related to a problem? Please describe.

Now it points to a Chinese forum post and shows nothing when people click "Get a Hint" button in the challenge of Chinese curriculum, for example, [this post](https://chinese.freecodecamp.org/forum/t/18276) ([the corresponding English post](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-say-hello-to-html-elements/18276)).

## Describe the solution you'd like

We may translate the hints into Chinese and other languages on Crowdin.

@raisedadead @ojeytonwilliams @nhcarrigan

**Comment by ojeytonwilliams** [comment]
It should be possible to create something analogous to our current workflow, as long as the Discourse API allows it.  i.e. GET the current articles for upload and then POST the translations once they're approved.

Nick probably has a better idea about this than I do, though.

**Comment by nhcarrigan** [comment]
The biggest challenge is going to be figuring out how to update the front matter in the curriculum files to link the appropriate forum post.

**Comment by raisedadead** [comment]
I think a really long time ago in one of our conversations with Randy, it was deliberated that the complexity & time involved in working on a way to translate the hint comments, vs working on the new editor & new curriculum was not worth it.

But I could be wrong.

**Comment by ojeytonwilliams** [comment]
That's probably true, but what do we want to do with the "Get a Hint" button?  Some options:

- Link to the English page 
- Remove that button for the Chinese challenges

**Comment by iLtc** [comment]
I think linking to the English page is better~

**Comment by miyaliu666** [comment]
Can we just link them to English pages?

**Comment by nhcarrigan** [comment]
That should be fine, yeah
