### ISSUE TITLE
Making test function call visible in test text

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#43064]
Continuing from https://github.com/freeCodeCamp/freeCodeCamp/pull/43052#issuecomment-888585380

This is a challenges with the function call used in the test not being visible in the test text. There may be others.
The test text should include the function call used.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting/slice-and-splice.md

**Comment by moT01** [comment]
I'm not sure I understand here @ieahleen. Are you referring to this test:
```
The first array should remain the same after the function runs.

frankenSplice(testArr1, testArr2, 1);
assert.deepEqual(testArr1, [1, 2]);
```

How it doesn't say what exactly is being tested? The text should be more specific?

**Comment by ieahleen** [comment]
Sorry, it's this one:
All elements from the first array should be added to the second array in their original order.
assert.deepEqual(frankenSplice([1, 2, 3, 4], [], 0), [1, 2, 3, 4]);

it happens that users use ways that don't agree with an empty array, but fail to understand why it is failing, and the only way for them to see that it was an empty array was to use `console.log(arr1, arr2)` inside the function and rely on the test logs

**Comment by ieahleen** [comment]
So to add, I think the test text should be something like
> `frankenSplice([1, 2, 3, 4], [], 0), [1, 2, 3, 4])` should return `[1,2,3,4]`

The original text could be changed to be this, or the two could be combined in some way

**Comment by DanielRosa74** [comment]
A suggestion to try to make the description a little clearer:
