### ISSUE TITLE
Bad RSS Spanish

### ISSUE THREAD

**Issue by tanrax** [freeCodeCamp/freeCodeCamp#43079]
In my RSS reader I couldn't see the latest Spanish-language articles, and as far as I can see it's a problem with the date. Currently it looks like this.

`<pubDate>mié., 14 jul. 2021 13:00:00 +0000</pubDate>`

But it should be the day of the week and mouth in English, capitalize and without the dot.

`<pubDate>Wed, 14 Jul 2021 13:00:00 +0000</pubDate>`

RSS Specification: https://www.rssboard.org/rss-specification#ltpubdategtSubelementOfLtitemgt

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @tanrax.

I took a look and there doesn't seem to be a good way to fix this at the moment.

To get and format the dates, we use Ghost's [`date`](https://ghost.org/docs/themes/helpers/date/) helper, which uses Moment.js for localized dates under the hood. The `date` helper picks up the site language from the Ghost settings, and sets the locale Moment.js uses based on that.

Unfortunately it isn't possible to override this behavior specify a locale for the `date` helper to use. Probably the only fix for the current News theme would be to create a custom Handlebars helper to handle dates for the RSS feeds, which involves modifying Ghost itself, which we probably don't want to do.

We're working on a new version of News that uses Ghost as a headless CMS, and we can easily fix this issue in that implementation. There's no timeline for the new version of News, but we'll make sure that we fix this date formatting issue for the RSS feeds.

**Comment by scissorsneedfoodtoo** [comment]
Thanks again for bringing this to our attention, @tanrax.

This has been fixed in the new version of News. While we don't have a timeline for release yet, your RSS feeds for https://www.freecodecamp.org/espanol/news/ should work normally once it's rolled out.

Will close this for now. Please let us know if you notice any other issues.
