### ISSUE TITLE
Incorrect Auto-Translation

### ISSUE THREAD

**Issue by knrodriguez** [freeCodeCamp/freeCodeCamp#43081]
## Issue
It seems the auto-translation for the Learn How to Deploy 12 Apps to AWS, Azure, & Google Cloud article by Beau Carnes is incorrect, and discusses a flexbox tutorial.

## Affected page

https://www.freecodecamp.org/news/learn-how-to-deploy-12-apps-to-aws-azure-google-cloud/

## Screenshots

![screenshot_docker_video_transcript](https://user-images.githubusercontent.com/18505368/127692800-ea906016-4d23-4a77-905b-fba4a9464649.png)

**Comment by ieahleen** [comment]
Thank you, I have notified the editorial team about this

**Comment by beaucarnes** [comment]
Fixed now!
