### ISSUE TITLE
Remove react-hotkeys from Code Radio to reduce its bundle size

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#43098]
## Affected page

https://coderadio.freecodecamp.org/

## To reproduce

I made a spot check on the bundle size as I was looking for some way to optimize the Code Radio app. And I found that `react-hotkeys` is taking a significant amount of the bundle size.

<img width="1680" alt="Screen Shot 2021-08-02 at 16 22 31" src="https://user-images.githubusercontent.com/25715018/127841808-a2a0cf3a-99ba-4854-a0ad-0228528f5bef.png">

## Expected behavior

The library is for keyboard shortcuts handling, but there are just 4 of them, so I don't believe it justifies the cost. This also hurts mobile users, who don't need to use the shortcuts but have it loaded anyway.

I think we can replace it with native event handlers.

Here is the bundle size after I tried removing the package:

<img width="1680" alt="Screen Shot 2021-08-02 at 17 00 52" src="https://user-images.githubusercontent.com/25715018/127843744-132f92a8-267d-4658-93b8-8203d91ed26d.png">

## Other notes

It seems to me that we can shave some code off of the /learn bundle as well, since it also uses `react-hotkeys`, but I'm not sure to what extent. Ref https://github.com/freeCodeCamp/freeCodeCamp/issues/37742#issuecomment-821819174

**Comment by victor-duarte** [comment]
@huyenltnguyen, currently there are a couple of items that are affected by hot keys listening to `space bar` for playing the music. 

If the library is removed or not, the following items should be looked into:

- When pressing `space bar` on an focusable item, the action of the element is triggered and also the music is toggle. E.g history button; the menu opens or closes and the music also. I would expect only one of the action to be triggered.
- If user tabs to the play button and press `space bar`, the native action of the button and the hot keys action are triggered causing the button to play and stop.

**Comment by huyenltnguyen** [comment]
Thanks @victor-duarte! The collision between the history button and the music player is actually new to me. You have found a bug there.

I'll be sure to address it and keep the app working as expected after the package removal :)

**Comment by iepsen** [comment]
Hi @huyenltnguyen! I have open a PR for this fix as your last activity was in August so I assumed you are not working on this ticket. Hope you like it! 😄

**Comment by huyenltnguyen** [comment]
@iepsen Ah, your assumption is correct. I unfortunately didn't get a chance to wrap this one up.

Thanks for working on this. I'll review the PR as soon as I can 🙂
