### ISSUE TITLE
What do we want to log in our console

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#43105]
I made [a PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/43052) to update how the console behaved, but I think it could use some more discussion first.

**Comment by ojeytonwilliams** [comment]
One option:

```
Test text
console logs from running that test

Second test text
second set of logs
```

**Comment by Sembauke** [comment]
What about this?

```
Function a should return x
✅  expected output to be x got x  

Function b should return y
❌ expected output to be x got y 
```

**Comment by Sembauke** [comment]
What do you think @ojeytonwilliams?

**Comment by ojeytonwilliams** [comment]
I do like that idea.  It's similar to something Randy suggested a while back.  I think this is something we could do independently of the option I suggested.

**Comment by Sembauke** [comment]
So the questions to ask here is:

1. How do we log a gotten result written by the Camper.
2. How do we log the expected result?

Is it even possible, if so how would we achieve this.

**Comment by moT01** [comment]
I'm having second thoughts on this - it sounds good, but I'm not sure it makes sense for most of the challenges. Here's a test from a random CSS challenge: `The --penguin-belly variable should be declared in the :root and assigned the value pink.` Looking through a few others in RWD, I don't think it would work for anything in that section. Javascript is the place where you think it would be best, and maybe possible - but looking at some of those, I don't think it would work there either. Here's a few examples of test text from the JS section:
`You should use the .match() method.`
`You should create a // style comment that contains at least five letters.`
`You should use the % operator`

Seemingly, going to any random challenge has at least one test that wouldn't work without getting rid of it or re-writing it. What would the assert messages for those look like? They would probably just confuse people. There's quite a few that would work: 
`The value of remainder should be 2`
`lastLetterOfLastName should be the letter e.`

But, for the most part, it doesn't make sense to me with our tests and I don't think it would work. My initial thought on this was that we should just log exactly what the users code logs.

**Comment by Sembauke** [comment]
I agree

**Comment by ojeytonwilliams** [comment]
It's definitely true that not all tests can (or should) be written in this style.  However, since some tests clearly could be, do we want to have a mixed output:

```
✅ Function a should return x:
expected output to be x got: x  

❌ Function b should return y:
expected output to be y got: z

❌ You should use the .match() method.
```

Something like that?

**Comment by Sembauke** [comment]
How would we know which written style needs to be used?

**Comment by ojeytonwilliams** [comment]
As test authors? I assume you'd try to write tests such that they could give the detailed feedback and fallback to the empty message if it's not possible.

That's assuming we want this in the first place :man_shrugging:

**Comment by ShaunSHamilton** [comment]
I have specifically been writing tests using their method assertions (e.g. Instead of `assert(truthy)`, `assert.isTrue(truthy)`) for this reason - in the case we want to have more granular output.

Largely, I am still in favour of this approach: https://github.com/freeCodeCamp/freeCodeCamp/pull/40518

But again, will it work for the new editor tests - they should be written as hints anyway (not just `Such and such should return X`)

**Comment by ojeytonwilliams** [comment]
> But again, will it work for the new editor tests - they should be written as hints anyway (not just Such and such should return X)

I think that's a very good point.  We should focus on what we want for the project-based curriculum.  The soon-to-be-legacy console isn't really worth worrying about, imo.  It's not terrible as is.

So, since you and @nhcarrigan have been writing almost all the tests, what would you like to be able to do that you can't currently?

**Comment by ShaunSHamilton** [comment]
> what would you like to be able to do that you can't currently?

We have a few _features_, but there is nothing that has to be done, in terms of running the tests and their output.

**Comment by moT01** [comment]
So should we just close this then? I agree that it's not worth the effort to slightly improve the existing console that already works quite well.

**Comment by ShaunSHamilton** [comment]
_When in doubt, close it_ 😉 

I think we are happy with the current behaviour of the current editor/console.

If it comes up, we can open a new issue specifically for the new editor/output.

**Comment by moT01** [comment]
<generic close issue message here>
