### ISSUE TITLE
Typos in function name

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#43102]
There are some typos in function name in the Code Radio app: `stopCurrenttInterval` and `toggleIntterval`.

We should change `stopCurrenttInterval` to `stopCurrentInterval`, and `toggleIntterval` to `toggleInterval` instead.

Links to the code: 
- https://github.com/freeCodeCamp/coderadio-client/blob/main/src/components/Footer.js#L51
- https://github.com/freeCodeCamp/coderadio-client/blob/main/src/components/Footer.js#L57

**Comment by huyenltnguyen** [comment]
This issue is open for first-time code contributors only.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing!

**Comment by suryakantpandey** [comment]
I would love to work on this issue

**Comment by suryakantpandey** [comment]
I have created a pull request with the required changes  https://github.com/freeCodeCamp/coderadio-client/pull/173
please have a look
