### ISSUE TITLE
Make our landing page's page speed faster

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4311]
We have really low page speed according to https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.freecodecamp.com%2F&tab=desktop

We should be in the low 90s. I managed to get our landing page to that point previously, but it seems we've regressed. I think part of it is because we're using imgur as a CDN for images, and they're uncompressed. I can tackle this part, but could someone help with the other speed issues?

**Comment by lunjwaba1** [comment]
I can minify the CSS  and set an expiration date for the headers. I am guessing, since you are still modifying/updating the site, the files get bloated again so we need to re-compress the images,  and minify JavaScript constantly.

**Comment by anushprabhu** [comment]
Am new to this project but I can try helping to optimize with some  guidance.

**Comment by iheartkode** [comment]
@QuincyLarson  I can do some tests and see what is causing the slow down.

**Comment by iheartkode** [comment]
main-5ec7cf9022.css   is 299kb is the largest file that is being processed.
angular.js is next at 234kb

Minifying any of the css, js files will help significantly

**Comment by iheartkode** [comment]
@lunjwaba1 were you able to minify any files yet? If not I will get started on it.

**Comment by BionicCa** [comment]
gzip compressing the js and css files by the server would help much more! Instead of miniyfing I would rather start to clean up the css. The main css is so overblown with unnecessary style definitions. By optimizing I bet you could save over 50% of lines of code.

**Comment by iheartkode** [comment]
@BionicCa if you are familiar with gzip mayne you can look into implementing it.

**Comment by BerkeleyTrue** [comment]
We have minification set up on a separate branch.

**Comment by BerkeleyTrue** [comment]
see: #4034

**Comment by organicdude** [comment]
@bioniCa that is 100% true - gzip is the key to this. Who can change server settings to make that change?

**Comment by organicdude** [comment]
Another thing you can do is move js files that aren't for rendering to the end of the body tag. An example of the type of file you can move to the end of the body tag would be a js file that only is active when a form is submitted (eg error checking). 

Another aspect of page speed is to remove files that aren't needed. Are 100% of the below files needed to create functionality for the page? Or are they only being used on other pages?

http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js
http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.11/angular.js
http://cdnjs.cloudflare.com/…-ui-bootstrap/0.13.0/ui-bootstrap.min.js
http://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js
http://cdnjs.cloudflare.com/…tter-bootstrap/3.3.4/js/bootstrap.min.js
http://cdnjs.cloudflare.com/…ajax/libs/moment.js/2.10.2/moment.min.js
http://www.freecodecamp.com/js/main-b8db47b344.js
http://www.freecodecamp.com/…gular-bootstrap/ui-bootstrap-tpls.min.js
http://www.freecodecamp.com/…onents/lightbox2/dist/js/lightbox.min.js

**Comment by SaintPeter** [comment]
RE: lightbox2
I did a quick review of the .jade files and we use lightbox in only 3 places:
1. The "Commit" page.  The Girl DevelopIT image has a lighbox, which is useless
2. The Challenge Map - the Medium ad image has a lightbox on it, which is useless
3. The Step Challenges - all of the images have a lighbox . . . near as I can tell this is useless

Bottom line:  Pretty sure we can jettison Lightbox2 without difficulty.  Just remove the JS, don't even need to remove the references, since they degrade cleanly.

**Comment by organicdude** [comment]
@iheartkode can confirm - readme has info

**Comment by organicdude** [comment]
@QuincyLarson IMHO, here are the lowest hanging fruit.

1. Enable gzip type compression on server - is there a technical reason why this is not possible?
2. Inlining the CSS/JS scripts - this means fewer requests to the server upon loading, which means you don't have to wait to request the files before you begin to render the page...you can just request the base "html" file and skip all other server requests...you can just comment out the file name just before you dump it's contents so you know what file was dumped out. BUT - this may actually slow down load times if the gzip type compression is not enabled.
3. It looks like the dimensions of this file is much larger than it needs to be: http://i.imgur.com/nsvNixW.jpg --- if you open just that link in browser, then you will find that the dimensions are larger than 
4. Google generally likes longer file caching lengths than 24 hours (around 1 month in my experience). You can ignore 3rd party files if you have no control over them. But, with how quickly you guys iterate on these files, this may not be a 100% appropriate recommendation for FCC...but it would make your score go up, and improve the speed for some repeat visitors.

https://s3.amazonaws.com/freecodecamp/as-seen-on.png (expiration not specified)
https://s3.amazonaws.com/freecodecamp/freecodecamp_logo.svg (expiration not specified)
http://www.google-analytics.com/analytics.js (2 hours)
http://www.freecodecamp.com/…gular-bootstrap/ui-bootstrap-tpls.min.js (24 hours)
http://www.freecodecamp.com/…r_components/cal-heatmap/cal-heatmap.css (24 hours)
http://www.freecodecamp.com/…ts/font-awesome/css/font-awesome.min.css (24 hours)
http://www.freecodecamp.com/…e/fonts/fontawesome-webfont.woff?v=4.3.0 (24 hours)
http://www.freecodecamp.com/…mponents/lightbox2/dist/css/lightbox.css (24 hours)
http://www.freecodecamp.com/…mponents/lightbox2/dist/images/close.png (24 hours)
http://www.freecodecamp.com/…onents/lightbox2/dist/images/loading.gif (24 hours)
http://www.freecodecamp.com/…omponents/lightbox2/dist/images/next.png (24 hours)
http://www.freecodecamp.com/…omponents/lightbox2/dist/images/prev.png (24 hours)
http://www.freecodecamp.com/…onents/lightbox2/dist/js/lightbox.min.js (24 hours)
http://www.freecodecamp.com/css/lato.css (24 hours)
http://www.freecodecamp.com/css/main-c5353721e0.css (24 hours)
http://www.freecodecamp.com/fonts/Lato-Regular.ttf (24 hours)
http://www.freecodecamp.com/fonts/ionicons.ttf?v=2.0.0 (24 hours)
http://www.freecodecamp.com/js/main-b8db47b344.js (24 hours)

**Comment by BerkeleyTrue** [comment]
Gzip has been enabled

**Comment by organicdude** [comment]
Can confirm that the Gzip has been enabled according to Google page speed tool: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.freecodecamp.com%2F&tab=desktop

**Comment by LenaBarinova** [comment]
For a map page In Chrome developer tool, I see that top most time consuming download is for a main banner. I've tried compressing it with Compressor.io (https://compressor.io) - and it can be reduced in size from 227KB to 73KB (68%!) without any visible loss in quality. Attaching compressed version. Could someone update it in S3?
![wide-social-banner](https://cloud.githubusercontent.com/assets/2317409/11672693/960c0e12-9dc7-11e5-913e-865f13021775.png)

**Comment by organicdude** [comment]
Nice!

**Comment by BerkeleyTrue** [comment]
Going to close this as not actionable through the repo or by a contributor. @QuincyLarson we need to compress all the images stored on s3 and set a cache header.

Moving to react should solve everything else.

Happy Coding!
