### ISSUE TITLE
Cash Register Challenge - Remove ambiguities

### ISSUE THREAD

**Issue by Laserbase** [freeCodeCamp/freeCodeCamp#43110]
## Affected page

[javascript-algorithms-and-data-structures-projects/cash-registe](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register)

# Problem

This issue has been raised in response to the following thread.
[unhandled-condition-in-cash-register-problem](https://forum.freecodecamp.org/t/unhandled-condition-in-cash-register-problem/469708)

Looking at the other issues raised for this page it seems like there is a problem in the comprehension of the specification.
This can expressed like 
>New learners certainly find this project plenty difficult on its own without additional complexity.

For example
```
Return {status: "CLOSED", change: [...]} 
with cash-in-drawer as the value for the key change if it is equal to the change due.
```
What is the `it` being referred to? to find out requires testing.
What are the allowed values for `price` and `cash`?
Why are we returning the cash drawer (`cid`) under the key `change`, (has it/should it) be have zero amounts because we have taken out the customers change out of the cash register?
Why is it closed so we cannot refill the empty cash drawer?
Why if we have sufficient cash on hand do we leave the till open afterward so it can be robbed?
These questions and more are not resolved in the text and the only way to resolve this is by trial and error.

# Proposed solution - Additional text to increase understanding

You can safely assume that the arguments will always be correct, 
For example -
- the `price` is always greater than zero;
- the `cash` payment will never be less than the `price`;
- the cash-in-drawer (`cid`) is a fixed array of correct values.

# End Proposed solution

## Aside - A quick rewrite to show my thinking

Design a cash register drawer function `checkCashRegister(price,cash, cid)` that accepts 
-    purchase price as the first argument (`price`),
-    payment as the second argument (`cash`),
-    and cash-in-drawer as the third argument (`cid`).

`cid` is a 2D array listing available currency.

---
The `checkCashRegister()` function should always return an object with 
- a `status` key with a string value and 
- a `change` key with an array value.

---
**Return** `{status: "INSUFFICIENT_FUNDS", change: []}`
- when the cash-in-drawer total is less than the change due,
- or if you cannot return the exact change (i.e. the change due is $1.00 and the register has only a single $100 dollar bill).
  

**Return** `{ status: 'CLOSED', change: [] }`
- when the cash paid is equal to the price asked.
  

**Return** `{status: "CLOSED", change: [...]}`
- when the sum of cash-in-drawer (`cid`) is equal to the change due
- with the passed in cash-in-drawer (`cid`) as the value for the key change.
  

**Otherwise, return** `{status: "OPEN", change: [...]}`,
- with the change due in coins and bills,
- sorted in highest to lowest order, as the value of the `change` key.
  

---
You can safely assume that the arguments will always be correct, 
- the `price` is always greater than zero;
- the `cash` payment will never be less than the `price`;
- the cash-in-drawer (`cid`) is a fixed array of correct values.

**Comment by nhcarrigan** [comment]
> Return { status: 'CLOSED', change: [] }
>when the cash paid is equal to the price asked.

The register would not be out of change in this circumstance, so should still be `OPEN`.

> Why is it closed so we cannot refill the empty cash drawer?
> Why if we have sufficient cash on hand do we leave the till open afterward so it can be robbed?

For what it's worth, the register is still `OPEN` while there is cash present because it is "open to receive more transactions", not because the drawer itself is physically open.

**Comment by moT01** [comment]
I don't think anything needs to be changed here. If you think I am wrong in closing this, feel free to leave a comment and it can be reopened.
