### ISSUE TITLE
Freezing Issue

### ISSUE THREAD

**Issue by MrMPerial** [FreeCodeCamp/FreeCodeCamp#4313]
Challenge [Waypoint: Make Instances of Objects with a Constructor Function](http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var myCar; "once I begin typing on this line, the whole site freezes on me."

```

**Comment by SaintPeter** [comment]
Have you tried on different browsers?  Have you tried with plugins disabled?

**Comment by MrMPerial** [comment]
Different devices but all in Chrome.

**Comment by MrMPerial** [comment]
No plugins running.

**Comment by ltegman** [comment]
Closing as an unexpected manifestation of #4228

I can put in a PR to put the tail back on this challenge to temporarily mitigate the issue on this challenge and then I'll see if I can make any further progress on solving this tonight.

**Comment by MrMPerial** [comment]
Thanks

**Comment by drakata** [comment]
I have been having the same problem, used different browsers and different computers, still happening.

**Comment by Lgofk** [comment]
I have the same problem too, on Windows and mac, in chrome, mozilla and safari.

**Comment by francisngo** [comment]
i have the same problem on multiple browsers.

**Comment by MrMPerial** [comment]
So I found this somewhere, I don't remember where or I would give credit. But I added this to the bottom and It worked for me. Hope it works for everyone else.
----------------------------------------------------------------------------------------------------------------------------------
// Only change code above this line

(function() {return JSON.stringify(myCar);})();
