### ISSUE TITLE
Modify instructions for Nest an Anchor Element within a Paragraph challenge

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#43141]
The [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph) comes up a lot in the forum. 

It has come up over 50 times in the past couple of months. 
https://forum.freecodecamp.org/search?q=Challenge%3A%20Nest%20an%20Anchor%20Element%20within%20a%20Paragraph%20after%3A2021-05-01

Most people misunderstand the instructions and create a new anchor tag even though the instructions say to use the existing one. 

Since this is a frequent problem, I think the instructions should be modified to include "Do not create a new anchor tag"
Love to hear your thoughts. 

## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

## Screenshots

Proposed solution

<img width="467" alt="Screen Shot 2021-08-07 at 1 02 40 PM" src="https://user-images.githubusercontent.com/67210629/128612577-43d8c951-1f91-459c-8ed3-86cae88614ef.png">

**Comment by ShaunSHamilton** [comment]
I would be happy to try this, but I suspect there will be little noticeable affect:
> Users do not read.

\- _Many people_

**Comment by gikf** [comment]
I came here to propose adding explicit test checking for number of `a` elements, but then noticed there's one already. Then perhaps rewording description of that test could help?

>You should not add new `a` element.
There should be only one `a` element.

**Comment by ieahleen** [comment]
We have the same issue on this other challenge: https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/use-the-value-attribute-with-radio-buttons-and-checkboxes

People keep creating new elements instead of adding the `value` attribute to the existing elements

**Comment by jdwilkin4** [comment]
@ieahleen That challenge comes up a lot too. 

@ShaunSHamilton I see your point about people not wanting to read directions. Hopefully we get a few people to notice it though .

**Comment by Sembauke** [comment]
I think we can try this out and see if it helps @jdwilkin4

**Comment by Nirajn2311** [comment]
There's no harm in adding a small note at the end of the instructions. It might even clarify any doubt a user has.
