### ISSUE TITLE
infinite loop on http://www.freecodecamp.com/challenges/bonfire-roman-numeral-converter

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#4314]
Hey, I messed up my code.  It saved and now it's immediately invoking and auto infinite looping on load.

Could you possibly reset the code solution for: http://www.freecodecamp.com/challenges/bonfire-roman-numeral-converter

thanks.

**Comment by SaintPeter** [comment]
You can clear a specific solution by following these instructions:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage

Happy Coding!
