### ISSUE TITLE
Translation mistake - cadena con valor 9000

### ISSUE THREAD

**Issue by doineedthis** [freeCodeCamp/freeCodeCamp#43151]
## Affected page

https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-case-sensitivity-in-variables

## Your code

```
// Declaración de variables
var studlyCapVar;
var properCamelCase;
var titleCaseOver;

// Asignación de variables
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = "9000";

```

## Expected behavior

There is a translation mistake in the third test case, where it says: "titleCaseOver debe definirse y tener una cadena con valor 9000". There it is implied that a string value must be assigned, when in fact a numeric value must be entered.

## Screenshots

![2021-08-08-232334_1024x768_scrot](https://user-images.githubusercontent.com/88637919/128654843-f13bf555-c6d5-4449-9f44-e35fcdfa6960.png)

## System

- Device: Desktop
- OS: Ubuntu 18.04.5 LTS i686
- Browser: Firefox
- Version: 90.0.2 (32-bit)

## Additional context

best regards

**Comment by ieahleen** [comment]
Thank you for your report, I will the translation team know.
If you want to join in the translation efforts you can join the Spanish chat room at https://chat.freecodecamp.org/channel/espanol

**Comment by RafaelDavisH** [comment]
@doineedthis Thank you for pointing this mistake. This and others similar to these strings have been corrected. Please, do continue to point out any mistake that you find.
