### ISSUE TITLE
403 error when trying to do a PR on wiki

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#4317]
I was trying to update your bonfire-roman-numeral-converter.md because you don't need to have numCopy variable in the solution but I got a 403 when I tried to upstream it. :( 

<img width="565" alt="screen shot 2015-11-11 at 10 50 46 pm" src="https://cloud.githubusercontent.com/assets/2502947/11110213/1fb8f870-88c7-11e5-8206-aa368d3e36e4.png">

**Comment by ltegman** [comment]
The wiki is currently locked down due to issues with spammers. Please make any wiki PRs on https://github.com/FreeCodeCamp/wiki

Thanks and happy coding!
