### ISSUE TITLE
Translation mistake - "This is the start."

### ISSUE THREAD

**Issue by doineedthis** [freeCodeCamp/freeCodeCamp#43174]
## Affected page

[https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator](url)

## Your code

```

var myStr = "This is the start." + "This is the end."; // Cambia esta línea


```

## Expected behavior

I think there is a translation mistake in the instruction where it says "This is the start." instead of "This is the start. ".
I think it could lead to errors when copying and pasting phrases from the instructions.

## Screenshots

Spanish version
![2021-08-10-203207_1024x768_scrot](https://user-images.githubusercontent.com/88637919/128949246-0309c64a-69ec-4e9b-b4fa-8796ab04a4e9.png)

English version
![2021-08-10-201708_1024x768_scrot](https://user-images.githubusercontent.com/88637919/128949276-e3d75e1b-496d-4d86-8628-f02cee851f4e.png)

## System

- Device: Desktop
- OS: Ubuntu 18.04.5 LTS i686
- Browser: Firefox
- Version: 90.0.2 (32-bit)

## Additional context

Have a nice day

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #42455, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
