### ISSUE TITLE
Incorrect solution provided for Divide the Grid Into an Area Template challenge 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#43185]
A user on the forum had trouble passing a challenge using a solution provided in the video. 
I led them to the correct solution but the video seems to be referencing a different challenge. 
Even the hint page is incorrect and provides these instructions. 

"Since the challenge requires you to make the cell labeled advert into an empty cell, change advert to a . (period) so that the code reflects the following:"
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-divide-the-grid-into-an-area-template/301130

But those are the incorrect instructions.
Here are the correct instructions
Change the template so the footer area spans the entire bottom row. 

The solution in the hint needs to be updated and the video should be removed. 

Thanks! 

## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/css-grid/divide-the-grid-into-an-area-template

## Your code

Correct solution
```
    grid-template-areas:
    /* Only change code below this line */
      "header header header"
      "advert content content"
      "footer footer footer";
    /* Only change code above this line */
  }

```

**Comment by ShaunSHamilton** [comment]
Hey Jessica,

This appears to have gone out of sync with: https://github.com/freeCodeCamp/freeCodeCamp/pull/43059

I have updated the Guide Post, but this is open for contribution to _first timers_ to remove the video:

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by StephNathai** [comment]
Hi! Is this available to be picked up?

**Comment by ShaunSHamilton** [comment]
> Hi! Is this available to be picked up?

@StephNathai Yes, it is open for first time contributors to freeCodeCamp.

**Comment by StephNathai** [comment]
Great, I'm a first time contributor and would love to grab it.

**Comment by w286432531** [comment]
I tried to create a pull request for the first time ever. Please let me know if I made any mistake. Thanks.

**Comment by shikhar13012001** [comment]
I made a pull, some checks are failing can someone help me? I am very new to this. Thankyou

**Comment by StephNathai** [comment]
@ShaunSHamilton can you let us know who this is assigned to? I thought we had to ask and wait to be assigned the ticket but I see two others are already trying to work on this.

**Comment by ShaunSHamilton** [comment]
> @ShaunSHamilton can you let us know who this is assigned to?

@StephNathai Sure. As mentioned in my earlier reply:
> An issue with the help wanted or first timers only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

As such, linked open PRs will be QAed with these ordered priorities in mind:
1) The highest quality PR - contributor has followed Contribution Guidelines, and contribution is an improvement
2) The first opened PR

We try to do this to best respect everyone's time. If a linked PR for this issue is _likely_, then please feel free to work on another issue open to contribution.

Hope this clarifies 🙂
