### ISSUE TITLE
Site logo and Menu overlapping for smaller screen sizes

### ISSUE THREAD

**Issue by heysujal** [freeCodeCamp/freeCodeCamp#43182]
## Affected page

[Homepage](https://www.freecodecamp.org/)

## To reproduce

1. Go to https://www.freecodecamp.org/ on mobile device.
2. Or open chrome dev tools to view site for smaller screen size.
3. On decreasing the screen size the menu button overlaps with the logo which starts at screen size <418px. On decreasing size further for screen size <=300 it behaves normally.

## Expected behavior
Maybe freeCodeCamp title should get hidden and only the logo(bonfire like) should remain like it does for screen size <= 300px.

## Video

https://user-images.githubusercontent.com/55016909/129068027-931aceb5-7470-451c-a1a7-7f0c9740e3f7.mp4

 

## System

- Device:Laptop
- OS: Windows 10
- Browser: Chrome

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to help the freeCodeCamp community. This issue has been resolved with: https://github.com/freeCodeCamp/freeCodeCamp/pull/43176

The fix is in staging, but has yet to be pushed to production.

As such, I am closing this as shipping. Thank you 🙂
