### ISSUE TITLE
Camper News with blank URL

### ISSUE THREAD

**Issue by storbeck** [FreeCodeCamp/FreeCodeCamp#4319]
http://www.freecodecamp.com/news/podcasts-i-like-web-designer-notebook-web-designer-notebook

I tried submitting a URL to camper news and somehow it got added as a blank URL. The link I tried to add was http://webdesignernotebook.com/reviews/podcasts-i-like/ but it just links to http://

I also can't edit or delete it, so I can't try fixing it.

**Comment by SaintPeter** [comment]
Yup, I confirmed this with that URL.

@BerkeleyTrue Did you make a change to disallow blank URLs that might affect this?

**Comment by BerkeleyTrue** [comment]
Nope. Didn't realize this was possible.

**Comment by storbeck** [comment]
I see the mistake I made, I clicked "Submit" then typed in the url and hit "Submit" again. Then on the next page the title is auto-filled out but the URL is not copied over so I hit submit again, which let it be a blank URL. URL should copy from previous page into the new textbox.

**Comment by SaintPeter** [comment]
I think I may have done the same thing.

**Comment by roelver** [comment]
For some reason the url value is not copied from the page URL. This requires some adjustments in the jade template. I will fix that.
