### ISSUE TITLE
Landing/Home Page UI Modifications

### ISSUE THREAD

**Issue by rituraj8503** [freeCodeCamp/freeCodeCamp#43194]
## Is your feature request related to a problem? Please describe.

When I went to the landing/home page of [freeCodeCamp](https://www.freecodecamp.org/) I found the UI to be a little basic. Although I've heard the the curriculum is amazing I was wondering if we could slightly tweak the UI on the home page. 

## Describe the solution you'd like

In particular, I was thinking about the logos of the different companies on the home page. Could we perhaps replace them with colored images instead of black and white? Right now, the logos seem slightly bland, especially since the Get Started button is colored. Unless that is the concept of the UI, I feel like that can be changed. 

Furthermore, could we add a slight border radius to the "Get Started (it's free)" button because the squared off edges do not come off too nicely to the eye. The same goes for the Navbar buttons. The footer looks quite nice, it's just these buttons that bothered me a little bit. 

I feel like this should mainly be a CSS thing...Could you guys please let me know your thoughts? 
Thank you so much. 

## Additional context

This is the part of the home page I am referring to.

<img width="955" alt="Screen Shot 2021-08-13 at 15 54 26" src="https://user-images.githubusercontent.com/75031370/129316897-c34c1397-88a8-4ba9-a556-28305fe8295a.png">

This is the part of the Navbar I am talking about:

<img width="221" alt="Screen Shot 2021-08-13 at 15 56 08" src="https://user-images.githubusercontent.com/75031370/129317090-b1a76305-dee6-4ebb-b225-08a7b0bb41fc.png">

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to share your thoughts. For context, freeCodeCamp is largely designed to look command line -like. For more information, check out our [Design Style Guide](https://design-style-guide.freecodecamp.org/#vision).

That is the reason for the simple, and comparatively _plain_ style.

**Comment by rituraj8503** [comment]
Ohh that makes so much more sense now. Thank you so much for the clarification. I will go ahead and close this issue.
