### ISSUE TITLE
Adding basic Typescript inside JavaScript Algorithms section

### ISSUE THREAD

**Issue by iamarpitpatidar** [freeCodeCamp/freeCodeCamp#43208]
## Describe the Issue
this is a proposal of adding basic typescript inside the javascript algo section. we all know the importance of types and I think we should give the users a basic taste of exactly it is and why one should use typescript while writing javascript.

Rest I leave it to you guys for more discussion.

**Comment by ieahleen** [comment]
Thank you for your request, but at this time the work is being focused on the new curriculum 7.0 and the Data Science curriculum.
This could be a proposal for next version of the curriculum, at this time no new challenges are being added to the current curriculum.

https://www.freecodecamp.org/news/python-curriculum-is-live/
https://www.freecodecamp.org/news/building-a-data-science-curriculum-with-advanced-math-and-machine-learning/
