### ISSUE TITLE
Failure to load/timing out due to "memory" [2 separate computers]

### ISSUE THREAD

**Issue by meaberna** [freeCodeCamp/freeCodeCamp#43207]
## Affected page
https://www.freecodecamp.org/learn/front-end-libraries/react/pass-props-to-a-stateless-functional-component

## To reproduce

1. Go to above linked page
2. Click on attempt to change any code

## Expected behavior
After changing any of the code, the website will freeze causing an alert to pop up stating there is a problem with the page. The alert will ask if you will like to wait or close the site. 

This issue has been reproduced on 2 different computers [laptop and hardwired PC] on 2 different networks. 

Cache was cleared on both machines. Nothing was logged in the developer console. 

## System

 The first device was a HP PC; The second is a Toshiba Laptop. Both running Windows 10. 
Both utilizing Chrome. Laptop Chrome was updated same day.

**Comment by gikf** [comment]
Just to confirm, you wouldn't have some browser extension, which might be causing this?

**Comment by meaberna** [comment]
No browser extensions on either one.

**Comment by nhcarrigan** [comment]
Hello! Thank you for reporting this issue. 

I am unable to reproduce this - can you share the specific changes you made to the code?

**Comment by meaberna** [comment]
This issue seems to be related to my account and I am unsure as to why.

I have now worked on 3 different machines... All having the same issue.

I don't know why/how to reproduce the issue. It happens at different points
during the code changing and in different lessons.

[Honestly after the 8th time changing the code on the 3rd lesson it
froze/cancelled on me, I just gave up.]

I end up skipping the lessons but 2-3 lessons down the road, it happens
again.

It's only within the Front End Developer so far.

I have updated all browsers and have no extensions

I have even tried only running Chrome with a single tab after clearing
cookies/cache and in incognito but it will still freeze/lock on me.

Any direction would be greatly appreciated... Seriously. I have worked over
900 hours in this system plus whatever I have in Front End.

I don't want to lose that

Thanks,

Meagan

**Comment by Nirajn2311** [comment]
You said you tried it in incognito mode also, did you login to attempt the challenge or not?

Also if possible could try doing the challenges while logged in to your account in another PC.

**Comment by ShaunSHamilton** [comment]
@meaberna Hey there,

The reason we ask this:
> can you share the specific changes you made to the code?

Is browsers are likely to crash, if their memory/cpu is used up. For the freeCodeCamp curriculum, the most common cause of this is a Camper's code containing an infinite loop.

Example:
```jsx
const CurrentDate = (props) => {
  return (
    <div>
      { /* Notice how the CurrentDate component returns itself */ }
      <p>The current date is: <CurrentDate /></p>
      { /* This will cause a browser to freeze */ }
    </div>
  );
};
```

If you are looking for more examples of this, it is a common mistake: https://github.com/freeCodeCamp/freeCodeCamp/issues/36118

---

I realise you mention it being caused by _any_ change to code, but I have never heard of any other Camper encountering this issue. So, I cannot see a link.

As a last-ditch effort, would you mind sharing a link to your freeCodeCamp account?

**Comment by meaberna** [comment]
Yeah I often use a code editor and checker before entering the code into
the FreeCodeCamp browser window. So it shouldn't be an infinite loop issue

Depending on the machine I am working on I use VS Editor, Sublime, or
Notepad ++ to edit and then follow that up but checking the information in
Regex101 if necessary and JSFiddle
I use Fiddle to tidy up the code as well.

https://www.freecodecamp.org/fcc0a5ab177-3eb5-4621-8dec-7a98f2dc4692

**Comment by ann-lang** [comment]
Hello, we are a group of researchers developing machine learning techniques to locate issues suitable for newcomers, and our model consider this issue as likely a "good first issue". May we recommend you to label it as "good first issue" so newcomers know where to choose?

Thank you!

**Comment by nhcarrigan** [comment]
Hey there @meaberna are you still experiencing this issue?

**Comment by raisedadead** [comment]
If you are still experiencing this issue, can you please reach out to `support@freecodecamp.org` as well to have someone from the team look at your account to help understand this better.
