### ISSUE TITLE
chai functional tests not passing on FCC but passed on Replit

### ISSUE THREAD

**Issue by RZMiRaN** [freeCodeCamp/freeCodeCamp#43228]
## Affected page

1. https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser
2. https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser-ii

## Your code

https://replit.com/@miran1337/boilerplate-mochachai

```
const chai = require('chai');
const assert = chai.assert;

const server = require('../server');

const chaiHttp = require('chai-http');
chai.use(chaiHttp);

suite('Functional Tests', function () {
  this.timeout(5000);
  suite('Integration tests with chai-http', function () {
    // #1
    test('Test GET /hello with no name', function (done) {
      chai
        .request(server)
        .get('/hello')
        .end(function (err, res) {
          assert.equal(res.status, 200);
          assert.equal(res.text, 'hello Guest');
          done();
        });
    });
    // #2
    test('Test GET /hello with your name', function (done) {
      chai
        .request(server)
        .get('/hello?name=xy_z')
        .end(function (err, res) {
          assert.equal(res.status, 200);
          assert.equal(res.text, 'hello xy_z');
          done();
        });
    });
    // #3
    test('Send {surname: "Colombo"}', function (done) {
      chai
        .request(server)
        .put('/travellers')
        .send({ surname: 'Colombo' })
        .end(function (err, res) {
          assert.equal(res.status, 200);
          assert.equal(res.type, 'application/json');
          assert.equal(res.body.name, 'Cristoforo');
          assert.equal(res.body.surname, 'Colombo');
          done();
        });
    });
    // #4
    test('Send {surname: "da Verrazzano"}', function (done) {
      chai
        .request(server)
        .put('/travellers')
        .send({ surname: 'da Verrazzano' })
        .end((err, res) => {
          assert.equal(res.status, 200);
          assert.equal(res.type, 'application/json');
          assert.equal(res.body.name, 'Giovanni');
          assert.equal(res.body.surname, 'da Verrazzano');
          done();
        });
    });
  });
});

const Browser = require('zombie');

Browser.site = 'https://boilerplate-mochachai.miran1337.repl.co/';

suite('Functional Tests with Zombie.js', function () {
  this.timeout(5000);

  const browser = new Browser();
  suiteSetup(function(done) {
    return browser.visit('/', done);
  });

  suite('Headless browser', function () {
    test('should have a working "site" property', function() {
      assert.isNotNull(browser.site);
    });
  });

  suite('"Famous Italian Explorers" form', function () {
    // #5
    test('Submit the surname "Colombo" in the HTML form', function (done) {
      browser.fill('surname', 'Colombo');
      browser.pressButton('submit', () => {
        browser.assert.success();
        browser.assert.text('span#name', 'Cristoforo');
        browser.assert.text('span#surname', 'Colombo');
        browser.assert.elements('span#dates', 1);
        done();
      });
    });
    // #6
    test('Submit the surname "Vespucci" in the HTML form', function (done) {
      browser.fill('surname', 'Vespucci');
      browser.pressButton('submit', () => {
        browser.assert.success();
        browser.assert.text('span#name', 'Amerigo');
        browser.assert.text('span#surname', 'Vespucci');
        browser.assert.elements('span#dates', 1);
        done();
      });
    });
  });
});

```

## Expected behavior

I expected to pass the challenge because everything is correct and replit shows that all 25 challenges are passed

## Screenshots

This is the result of the first challenge (Run Functional Tests Using a Headless Browser)
![nCDevNI](https://user-images.githubusercontent.com/11421315/129843310-19eb8398-6f0c-43d0-a914-9f62bf0f6d63.png)

This is the result of the second challenge (Run Functional Tests Using a Headless Browser II)
![nCDevNI4](https://user-images.githubusercontent.com/11421315/129843793-cd4122b1-85ac-4338-a6ed-3ce5147b3e1a.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 92.0.4515.159

## Additional context

Replit shows 25 passed in the end of the console, so I'm guessing the problem is not with my code, it is with how FCC is trying to detect whether it's correct or not
![nCDevNI3](https://user-images.githubusercontent.com/11421315/129844457-8da7bc7a-14d9-4706-aa22-0eecbe87573b.png)

**Comment by gikf** [comment]
Hey @RZMiRaN 
this project was recently updated together with the boilerplate code. However due to unrelated bug, code on the production page was reverted to date before these changes. This makes project page tests not align with the bolilerplate.

The issue shouldn't occur on the staging website. Could you confirm tests are passing there? https://www.freecodecamp.dev/learn/quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser. Once code from staging is pushed to the production tests should pass for you also on the main page.

**Comment by RZMiRaN** [comment]
Hello sir @gikf , confirmed, the test is passing on the link you provided
![fccdev](https://user-images.githubusercontent.com/11421315/129854181-4bdd3bc6-741e-456b-8db2-db3003e975e6.png)

**Comment by gikf** [comment]
Great, thanks for confirmation! I don't have an exact timeline, but I'd say production code should be updated within couple of days.

**Comment by RZMiRaN** [comment]
Great, thank you for your time, much appreciated

**Comment by rosaforrestiana** [comment]
Hi!

How pass the level for Run Functional Tests Using a Headless Browser which is in the second last level.
My replit shows my codes have passed all the test but not in the curriculum page
![image_2023-03-23_182212474](https://user-images.githubusercontent.com/30365715/227174156-4e8222c7-63ef-4fd5-bc9b-7cacbd454c26.png)
The rest of my codes are in this replit link https://replit.com/@vlchung/boilerplate-mochachai-1

**Comment by gikf** [comment]
Hey @rosaforrestiana,

Instead of asking for help here, please click the **"Ask Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum.

Thank you and happy coding.
