### ISSUE TITLE
Change "help translate" links to link to translated documentation for Italian and Portuguese

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#43249]
The links that suggest users to help translate should point to the documentation in the language, not to the English one

For example, the Italian links file:

https://github.com/freeCodeCamp/freeCodeCamp/blob/1fec73cdf746f85cfe13ac48afff43e9eb44f068/client/i18n/locales/italian/links.json#L2

should link to the documentation in italian:

`https://contribute.freecodecamp.org/#/i18n/italian/how-to-translate-files`

For Portuguese
https://github.com/freeCodeCamp/freeCodeCamp/blob/1fec73cdf746f85cfe13ac48afff43e9eb44f068/client/i18n/locales/portuguese/links.json#L2
it should link to Portuguese documentation
https://contribute.freecodecamp.org/#/i18n/portuguese/how-to-translate-files

---

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by madhhuurrii** [comment]
Hii @ieahleen, I would like to work in this issue

**Comment by gikf** [comment]
Hey @madhhuurrii

no need to ask. Issues labelled with `help wanted` or `first timers only` are open for contributions. Issues are typically not assigned to a specific person. You can read more about this at https://contribute.freecodecamp.org/#/FAQ?id=how-can-i-get-an-issue-assigned-to-me. 

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by sahilcode17** [comment]
I went through the site and after inspecting the link I found out that the link for the languages mentioned has errors in them, I would like to make a pr to this issue, can I?

**Comment by ieahleen** [comment]
@sahilcode17 do you mean helping with the translation? translations are not dons through github, you can read the page https://contribute.freecodecamp.org/#/how-to-translate-files to know how to help with translations

If it's about swapping the links as described in the first message in this issue, as already said, we don't assign issues, so you can do it
