### ISSUE TITLE
Waypoint: Make Instances of Objects with a Constructor Function

### ISSUE THREAD

**Issue by Pujann** [FreeCodeCamp/FreeCodeCamp#4324]
Hi,
I think the sample given in the explanation is wrong.
--------------------------------------------------------------------------------------------------------------
Now, once the myCar instance is created it can be used like any other object and can have its properties accessed and modified the same way you would usually. For example:

var myCar.turboType = "twin";  **we don't need var**
**it should be**
**myCar.turboType = "twin";**

Our myCar variable now has a property turboType with a value of "twin".
-----------------------------------------------------------------------------------------------------------------------

**Comment by ltegman** [comment]
Wow, I can't believe I missed this in the proofreading pass! Thanks for pointing this out!
