### ISSUE TITLE
GET request from /api/users/ endpoint times out for the "Exercise tracker" demo project

### ISSUE THREAD

**Issue by NoorFakhry** [freeCodeCamp/freeCodeCamp#43257]
## Affected page

https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker 

## Expected behavior

 When you submit the demo Exercise Tracker link, tests for GET requests from /api/users/ endpoint should pass without a timeout 

## Acual behavior

 When you submit the demo Exercise Tracker link, tests for GET requests from /api/users/ endpoint time out and fail.

## Screenshots

This one is from the production site
 
![Screenshot (194)](https://user-images.githubusercontent.com/65724923/130287655-79b214a0-0d0c-4bb7-9234-caf9881b45d2.png)

And this one is from the local branch I've been working on

![Screenshot (193)](https://user-images.githubusercontent.com/65724923/130287752-c743852c-0272-478c-8ccf-54f1af1c2ac0.png)

**Comment by gikf** [comment]
For some reason relevant route - https://exercise-tracker.freecodecamp.rocks/api/users - takes almost 15 seconds to load. Not sure if this is caused by being sad because of loading 200 thousands users...

**Comment by nhcarrigan** [comment]
I've dropped the collections for the example project so it's started fresh, and confirmed this resolved the timeout issue.

@NoorFakhry you should be good to test your changes against the example again.
