### ISSUE TITLE
Spanish translation of Counting Cards

### ISSUE THREAD

**Issue by doineedthis** [freeCodeCamp/freeCodeCamp#43260]
## Affected page

https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/basic-javascript/counting-cards

## Your code

```

var count = 0;

function cc(card) {
  // Cambia solo el código debajo de esta línea

  // No code yet
  return "Change Me";
  // Cambia solo el código encima de esta línea
}

cc(2); cc(3); cc(7); cc('K'); cc('A');


```

## Expected behavior

There is a minimal grammar mistake in the description section, where it says "una valor " instead of "un valor ".

## Screenshots

![2021-08-21-003205_1024x768_scrot](https://user-images.githubusercontent.com/88637919/130309156-38fa045e-4c1e-4a72-b0a2-f816af3fcc33.png)

## System

- Device: Desktop
- OS: Ubuntu 16.04.7 LTS
- Browser: Firefox
- Version: 91.0.1 (32-bit)

## Additional context

This not affect the comprehension of the lesson or cause any trouble at all.
I just point it in case you want to change it.

Regards

**Comment by ieahleen** [comment]
Thank you for your report.
If you want to contribute to the translation you can join the chat at chat.freecodecamp.org and you can read the guide here: https://contribute.freecodecamp.org/#/how-to-translate-files

I will let the translators know

**Comment by RafaelDavisH** [comment]
Thank you for pointing this error @doineedthis 

It's corrected now.
