### ISSUE TITLE
There'

### ISSUE THREAD

**Issue by MuhammadAsifMA** [FreeCodeCamp/FreeCodeCamp#4328]
Challenge [Waypoint: Make Instances of Objects with a Constructor Function](http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0AmyCar.nickname%20%3D%20%22whatever%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var myCar = new Car();
myCar.nickname = "whatever";
```

**Comment by ltegman** [comment]
This issue does not describe the problem. Please make a new issue that details the problem you're running into if you're still have difficulties.

Thanks and happy coding!
