### ISSUE TITLE
update mongoDB constructor to useUnifiedTopology

### ISSUE THREAD

**Issue by patlehmann1** [freeCodeCamp/freeCodeCamp#43291]
## Affected page

No pages are affected. This is just a warning coming from MongoDB when running the server. Low priority but could cause issues later on when the MongoDB Server Discovery and Monitoring engine is removed.

## To reproduce

1. Spin up FCC locally using `npm run develop`
2. See warning when MongoDB is initialized:
```
(node:9916) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```

## Expected behavior

That warning should not show during server initialization.

## Screenshots

![image](https://user-images.githubusercontent.com/35785843/130668808-bac985b2-2401-4465-a1c9-755b64c56e4e.png)

## System

- Device: [MacBook Pro]
- OS: [macOS 11.5.1]

## Additional context

I believe this can be resolved by adding `useUnifiedTopology: true` [in between these two lines here.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/datasources.production.js#L9-L10)

I'm willing to work on this, if needed.

**Comment by patlehmann1** [comment]
Sorry for labeling this a bug, I don't know how to remove it. It's really not, but it could be in the future.

**Comment by patlehmann1** [comment]
I just tried to resolve this locally and I'm still getting the warning after throwing `useUnifiedTopology: true` [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/scripts/seed/seedAuthUser.js#L146) and [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/datasources.production.js#L9-L10), so I'm a little stumped as to where the warning is coming from.

**Comment by raisedadead** [comment]
We have been aware of this for a while now, and have had the same conclusion as you. There is an API rewrite planned that should help remove some of these warnings. 

I am going to go ahead and close this as a wontfix for now though.
