### ISSUE TITLE
Renamed file not getting translated with new translations from crowdin

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#43340]
I renamed the English version of [a file](https://github.com/freeCodeCamp/freeCodeCamp/pull/42885/files#diff-3dd97fc546d08b3b628f712eb253cf8ceed7e0a5ea1d3196f71c9663833db683) in the Relational Databases section a little while ago - it's still one of the hidden upcoming changes sections

On Crowdin, the file has the correct name in the rest of the languages:
![Screen Shot 2021-08-30 at 1 03 12 PM](https://user-images.githubusercontent.com/20648924/131384608-f193c99f-f64b-49b7-a95e-4871ed193de4.png)

But the file still has the old name for [other languages](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/espanol/13-relational-databases/learn-relational-databases/learn-advanced-bash-by-building.md) on main.

This breaks i18n builds if you have the upcoming changes visible. Was I supposed to rename the file across the rest of the languages with that PR? Or why is that not getting updated?

**Comment by ieahleen** [comment]
yes, see renaming a challenge section here: https://contribute.freecodecamp.org/#/curriculum-file-structure

**Comment by moT01** [comment]
Thanks @ieahleen - sadly, I did a lot of work on those docs.
