### ISSUE TITLE
Certification card checks the "Set your name and make it public" requirement incorrectly.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#43358]
It seems that "Set your name and make it public" check mark check for the name being public but not if the name is set or not.
Adding another checkmark for setting the username and linking it to the related setting section is a plausible solution.

After setting the name to public and clicking on the `claim certification` button displays the following flash message:

<img width="1440" alt="Screen Shot 2021-08-31 at 1 32 23 PM" src="https://user-images.githubusercontent.com/4591597/131635455-f9a832d3-59f3-4201-8e20-615756bd4fd0.png">

**Comment by Sembauke** [comment]
Hey Ahmad, if you would like I can fix this in #43335. Instead of adding a new step, we can check it in the current step, as it is a requirement "Set your name, and ake it public" in this step.

**Comment by ahmadabdolsaheb** [comment]
My only concern is that when users have made their name public and click on the "Set your name, and make it public" it will take them to the privacy settings not the name input area. This might cause confusion, but it is your call.

**Comment by ieahleen** [comment]
I would agree that have two separate checks that bring to two different sections of the settings would be a better user experience

**Comment by Sembauke** [comment]
Why not fall back to the username if the name is not set as discussed in #41040

**Comment by ieahleen** [comment]
@Sembauke we decided not to in the issue triage metting, see https://github.com/freeCodeCamp/freeCodeCamp/issues/41040#issuecomment-904698765

**Comment by Sembauke** [comment]
> I would agree that have two separate checks that bring to two different sections of the settings would be a better user experience
let's go with this then.

**Comment by Ismailtlem** [comment]
where in the app can i find this page please ? 
<img width="1440" alt="131635455-f9a832d3-59f3-4201-8e20-615756bd4fd0" src="https://user-images.githubusercontent.com/34961373/132594874-905e9fdc-f890-4f57-8418-96d7dc851228.png">

**Comment by ieahleen** [comment]
@Ismailtlem that can be found in any curriculum certification page just scrolling down below the projects

**Comment by theshakeabhi** [comment]
Hi Can I take it up? I have started to locally set up freeCodeCamp on my machine.

**Comment by ieahleen** [comment]
@theshakeabhi 
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
