### ISSUE TITLE
Modal buttons should match in size and font

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#43357]
The button width and the button font of the completion modal when the user is not signed in should match the buttons of the completion modal when the user is signed in.

Modal when user is signed in:
<img width="678" alt="Screen Shot 2021-08-29 at 1 50 29 PM" src="https://user-images.githubusercontent.com/4591597/131624883-d27dbc48-a8ae-49f9-863a-ccc3d5e7fdc6.png">

Modal when user is not signed in:
<img width="897" alt="Screen Shot 2021-08-31 at 4 02 53 PM" src="https://user-images.githubusercontent.com/4591597/131624894-a363061b-1343-47a6-b2ae-581f56347004.png">

**Comment by moT01** [comment]
I'm not seeing this on production + firefox...

Not signed in:
<img width="832" alt="Screen Shot 2021-09-01 at 12 13 54 PM" src="https://user-images.githubusercontent.com/20648924/131714972-0dcef664-0d51-4234-afbc-fca8e18cace5.png">

Signed in:
![Screen Shot 2021-09-01 at 12 15 06 PM](https://user-images.githubusercontent.com/20648924/131715005-56bb070b-00a8-457e-83ed-961f06b3968d.png)

Do you have any more details @ahmadabdolsaheb?

**Comment by ahmadabdolsaheb** [comment]
the sign in button should be the same size as the rest in here.

**Comment by moT01** [comment]
I see - I was looking at the two buttons below it in your image. The font size is off there.
