### ISSUE TITLE
(client): Remove sentence from donor success message that doesn't apply

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#43401]
After making a donation, you get this success message whether you are signed in or not:
![Screen Shot 2021-09-07 at 9 14 31 PM](https://user-images.githubusercontent.com/20648924/132444771-9ba7e668-098f-42c4-9302-fb2acbc5c0e6.png)

I don't think that last sentence should show up if you aren't signed in. Doesn't really make sense.

**Comment by EhEhRon91** [comment]
Working on a fix for this. What is a good way to test donations?

**Comment by moT01** [comment]
I would recommend just manipulating the component to show the success message without actually making the donation requests.

**Comment by EhEhRon91** [comment]
I will give that a go. Thanks!
