### ISSUE TITLE
Add tests for curriculum order

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#43407]
[This PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/42182#discussion_r704011339) added a new block in responsive web design with the same order number as another and all the tests passed. The result was that the lessons jumped between the two blocks after finishing each lesson.

We could possibly add some tests to ensure that the superBlock order numbers are unique, the block order numbers are unique within their superBlock, and the challenge order numbers are unique within their block.

If anything else comes to mind, feel free to share or add it - perhaps a warning if an order number is skipped or doesn't start at 1? I believe the [block numbers for responsive web design](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/basic-html-and-html5/meta.json#L5) start at zero, they start at two in [front end development libraries](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/_meta/bootstrap/meta.json#L5), and the rest start at one. Maybe a warning/log for something like that.

**Comment by nhcarrigan** [comment]
We will want to audit the order pre-launch too.

**Comment by ankitkumarsamota121** [comment]
Hi @moT01! I would like to work on this issue. So far this is what I have understood, the tests need to ensure  - 
- `superBlockOrder` is unique for each `superBlock`
- `order` is unique for each block within a `superBlock`
- Challenge IDs inside `challengeOrder` of each block are unique
- Throw a warning if `order` numbers do not start at 1 or are not contiguous 

I can find all the `order` numbers, `superBlocks`, `superOrder` etc. in the `./curriculum/challenges/_meta` directory.
Please confirm if I have understood the issue correctly? Is there anything else that I missed or should look into?

**Comment by moT01** [comment]
That all sounds right @ankitkumarsamota121. I made a mistake - the challenges don't have an order number, they are just in an array for their order - looks like you noticed that. You could potentially see if those challenges ID's in the meta files match the ID's in their challenge files - I don't think there's a test for that. That's not entirely necessary, but it would provide some extra stability.

**Comment by ankitkumarsamota121** [comment]
While working on the test for `superBlock` and `superOrder`, I noticed that for the superBlock `certifications` there are two superOrders - 
- `0` for current challenges
- `12` for legacy challenges 

Also, the legacy challenges have an extra field `isPrivate: true`. 
So, should I avoid writing checks for challenges that are private? 
Or should the `superOrder` for `certifications` be same for all challenges?

**Comment by moT01** [comment]
You should be safe to change the superOrder to 0 for all the certs if you need to - I changed all the others in [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/43108/files). I must have just missed the legacy ones.

It looks like isPrivate is on all the certs, not just legacy. One thing I noticed is that some of the certs share an order. I'm not sure if that's is a problem - likely not since it's been that way for a while. So, you could probably not make checks for those - or, if you want to, you would probably need to change the order for some of them.
