### ISSUE TITLE
typo in parsing html and saving data challenge

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#43414]
![image](https://user-images.githubusercontent.com/26656284/132581667-abc062bc-d4b9-4248-bbbd-62ce8cbefa24.png)

the sentence needs to be fixed removing the second "we"

---

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/parsing-html-and-saving-data.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by dharniel45** [comment]
Wow

**Comment by jameshhe** [comment]
Just submitted a pull request after fixing this typo! This is my first time contributing to open source, so please let me know if there're things that I should've done. Thank you for providing this opportunity for first-time contributors.
