### ISSUE TITLE
comparing and sorting tuples challenge visual issue

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#43447]
In this challenge the first possible answer appear differently from the others

![image](https://user-images.githubusercontent.com/26656284/133079984-16332f55-b57c-4b4b-88d2-1d448fd6b051.png)

https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/comparing-and-sorting-tuples

**Comment by rhollings** [comment]
Is this because the answer is longer than the others? And they've added a scroll bar
Are you suggesting that they add code like such.. `overflow-x: hidden;`

**Comment by ShaunSHamilton** [comment]
Personally, I would not do anything about this, because it is just one of those things where someone complains if the code wraps, and someone else complains if there is a scrollbar.

**Comment by ieahleen** [comment]
I didn't notice at all it is a scrollbar 😓 it seemed a border or an empty thing or something like that
