### ISSUE TITLE
404 pages on news do not have trending links (all langs)

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#43449]
Here is a 404 example: https://chinese.freecodecamp.org/news/1235r1t23/

<img width="1199" alt="Screen Shot 2021-09-13 at 9 08 23 PM" src="https://user-images.githubusercontent.com/4591597/133135204-ad51a077-1666-4e08-876a-8b9f855e9c7f.png">

**Comment by moT01** [comment]
The search also seems broken on these pages
