### ISSUE TITLE
Spelling errors in the "where do I belong" lesson

### ISSUE THREAD

**Issue by najmieh** [freeCodeCamp/freeCodeCamp#43464]
## Affected page

https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-where-do-i-belong/16094

## Your code

```
```

## Expected behavior

_Here there is an explanation for the third solution of this lesson. There are some errors in the spelling._

Once the array **it** is sorted, we directly apply the .findIndex() where we are going to compare every element in the array until we find where num <= currNum meaning where the number we want to insert is less or equal to the current **number number** in the iteration.
Then we use ternary operations to check whether we got an index returned or -1. We only get -1 when the index was not found meaning when we get a false for all elements **int he array**, and for such case, it would mean that num should be inserted at the end of the list hence why we use arr.length.

**The correct version  of the explanation in the third solution should look like this one**

Once the array is sorted, we directly apply the .findIndex() where we are going to compare every element in the array until we find where num <= currNum meaning where the number we want to insert is less or equal to the current number in the iteration.
Then we use ternary operations to check whether we got an index returned or -1. We only get -1 when the index was not found meaning when we get a false for all elements **in the array**, and for such case, it would mean that num should be inserted at the end of the list hence why we use arr.length.

## System

- Device: [e.g. iPhone6, Laptop] Laptop
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4] Windows 10
- Browser: [e.g. chrome, safari] Chrome
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this. 🙂 

I have edited the guide post to fix those typos.

For future cases where you find issues with the typos, it might be quicker/easier to open a topic in the _Contributors_ sub-forum on the [forum](https://forum.freecodecamp.org/).

**Comment by najmieh** [comment]
Thank you.
Ok sure. I thought I should mention it here. :)
