### ISSUE TITLE
Shows offline and not saving my progress

### ISSUE THREAD

**Issue by khushi200701** [freeCodeCamp/freeCodeCamp#43462]
## System

- Device: Dell Laptop
- OS: Windows 10
- Browser: Brave browser (tried on chrome as well, same error)
- Version:

## Additional context

All pages are showing I am offline while I am clearly not, everything else works fine. Also, my progress isn't getting saved. Today's heatmap also is blank whereas I've been practiced all day.

## Screenshots
![Screenshot (146)](https://user-images.githubusercontent.com/58480229/133420799-cfe8e5cc-2e44-4e70-bc0a-537c5b41c3ec.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

If you are unable to log in or keep getting “we cannot reach the server…” it may be that you have a duplicated account. To solve this issue you will need to write to `support@freecodecamp.org`.

Find more support FAQ’s here:

https://www.freecodecamp.org/news/support/

----

I am going to close this for now. If you have any more issues, be sure to reach out on the [forum](https://forum.freecodecamp.org/).
