### ISSUE TITLE
Regarding the "Go to current challenge" button on the homepage

### ISSUE THREAD

**Issue by codingmickey** [freeCodeCamp/freeCodeCamp#43469]
## Affected page

[The Freecodecamp homepage](https://www.freecodecamp.org/learn)

## Description

I had started the JavaScript Algorithms and Data Structures course on the website and completed the module of Basic Javascript in it but even when I press the **Go to current challenge button**
![image](https://user-images.githubusercontent.com/42518907/133632324-309de436-e159-4e30-a618-df56f654da87.png)
It redirects me to the already [finished challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/compound-assignment-with-augmented-division) and not the current one which is the start of es6

This is not a major issue but just wanted to inform you!

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #43453, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
