### ISSUE TITLE
Basic JavaScript: course lesson could accept "let" or "const" in addition to "var"

### ISSUE THREAD

**Issue by aaronmccollum** [freeCodeCamp/freeCodeCamp#43484]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/finding-a-remainder-in-javascript

## Your code

```
let remainder;
remainder = 11 % 3;
```

## Expected behavior

Expected behavior would be for the test to pass, since the `remainder` variable has been initialized correctly. This follows the example of other early Basic JavaScript lessons that accept the `let` keyword when initializing variables.

Actual behavior: 2/3 tests pass, however test 1 fails with the message "The variable `remainder` should be initialized"

## System

- Device: MacBook Air (2017)
- OS: macOS Big Sur
- Browser: Chrome
- Version: 93.0.4577.82

## Additional context

This is a suggestion to update this particular lesson and any other early Basic JavaScript lessons that only accept `var` to initialize a variable. 

This is my first open source issue suggestion ever, so I am open to correction if I submitted this erroneously. Thank you for reading.

**Comment by ShaunSHamilton** [comment]
Hello there,

This will be closed by the above mentioned PR.

**Comment by aaronmccollum** [comment]
Hey @ShaunSHamilton thanks! I appreciate you taking a look at this and linking it with a pre-existing PR that I missed. Hope all is well.
