### ISSUE TITLE
A few typos in the first two tutorials of the Relational Databases course

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#43491]
I love the new Relational Databases Course and I think the other fCC learners will too. 

I just wanted to report some typos I found in the first two tutorials.
I marked all of the typos with their corresponding json id's.
I also put the typos in bold and suggested changes. 

Thanks! 

**Learn Bash by Building a Boilerplate**
https://raw.githubusercontent.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/main/tutorial.json

~~id:1260.1~~
~~**Turns out you want some different font for the website**. From here, create `roboto-bold.woff` in your new `fonts` folder. You can put the path in front of the filename of where you want it to go.~~

~~**Change**: Turns out you want a different font for the website~~
~~or~~
~~Turns out you want some different fonts for the website~~

^^ fixed via https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/pull/2

**Learn Relational Databases by Building a Mario Database**
https://raw.githubusercontent.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/main/tutorial.json

id: 400
There's two columns. **You won't either of them** for the Mario database. **Alter** the **table** `second_table` and **drop** the **column** `username`.

**Change**: You won’t need either of them

id:430
Still two. **You won't either of those** for the new database either. Drop `second_table` from your database. Here's an example:\n\n```sql\nDROP TABLE table_name;\n```

**Change**: You won’t need either of those

id: 710
Her favorite color was updated. **Toadstool's name wrong as well,** it's actually `Toad`. Use `UPDATE` to `SET` his `name` to `Toad`. Use the condition `favorite_color='Red'`.

**Change**: Toadstool’s name is wrong as well 

id: 1580
**Next it Toad. Add three more rows his actions.** 

**Change**: Next is Toad. Add three more rows for his actions.

**Comment by Jy411** [comment]
Where is the course? I can't find it

**Comment by ShaunSHamilton** [comment]
@Jy411 Thank you, for your interest in contributing. However, issues with the _help wanted_ or _first timers only_ label are open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Rahul4343** [comment]
use command properly

**Comment by Veercodeprog** [comment]
hi,is it still open ?

**Comment by riadh26** [comment]
I've created two PRs: 

[freeCodeCamp/learn-bash-by-building-a-boilerplate#2](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/pull/2)
[freeCodeCamp/learn-relational-databases-by-building-a-mario-database#3](https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/pull/3)
