### ISSUE TITLE
Build an Image Search Abstraction Layer challenge example API to recent queries not working

### ISSUE THREAD

**Issue by jjnilton** [freeCodeCamp/freeCodeCamp#43518]
## Affected page

https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-an-image-search-abstraction-layer

## Your code

> curl https://image-search-abstraction-layer.freecodecamp.rocks/recent/

returns:

> {"name":"MongoError","message":"connection destroyed, not possible to instantiate cursor"}

## Expected behavior

I think it should show the recent queries.
## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]>

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @jjnilton. Turns out we had to update one of the environment variables for this project and give it a restart.

Will close this for now. But please try that endpoint again and let us know if you're still having issues.
