### ISSUE TITLE
Example code in hover + css animation doesn't work very good

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#43517]
The example code in the description of [this challenge](https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/use-css-animation-to-change-the-hover-state-of-a-button) doesn't really work. I'm guessing there's supposed to be a smooth animation, but it doesn't do that - and I can't really keep the image hovered because it changes sizes on hover, which causes me to not have it hovered.

**Comment by Shofiya2003** [comment]
Can I take up this issue?

**Comment by jamesgeer** [comment]
Hi moT01,

I've created this [pull request](https://github.com/freeCodeCamp/freeCodeCamp/pull/43524) for the issue you raised. 

This is my first open source contribution so I hope it all goes well!

**Comment by tabhay563** [comment]
i will work on this issue
