### ISSUE TITLE
Global State Reset Bug

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#43516]
## Affected page

All JavaScript Challenges

## Your code

Something introduced a bug in the runner for JavaScript challenge tests. Now the global variable space for each challenge is separate. This means that invalid solutions that [ab]use the global space are suddenly passing challenges.

For example, see the recursion challenges

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown
```javascript
// Only change code below this line
let global = [];
function countdown(n){
  console.log(n, global);
  if (n < 1)
    return [];
  global.push(n);
  countdown(n - 1);
  return global;
}
// Only change code above this line
```

This solution is fragile and misses some key learner misunderstandings about scope, variables, return values, function calls, and the global space. This solution should not pass.

## Expected behavior

The test suite should *not* use a clean/new/reset global variable space for each challenge test executing.

## Additional context

We have a canned reply on the forum explaining why global variable [ab]use is bad:

> Your code contains global variables that are changed each time the function is run. This means that after each test completes, subsequent tests start with the previous value. To fix this, make sure your function doesn't change any global variables, and declare/assign variables  within the function if they need to be changed.

> Example:
```javascript
var myGlobal = [1];
function returnGlobal(arg) {
  myGlobal.push(arg);
  return myGlobal;
} // unreliable - array gets longer each time the function is run

function returnLocal(arg) {
  var myLocal = [1];
  myLocal.push(arg);
  return myLocal;
} // reliable - always returns an array of length 2
```

**Comment by ShaunSHamilton** [comment]
Hey Jeremy,

> Something introduced a bug in the runner for JavaScript challenge tests. Now the global variable space for each challenge is separate.

I have not noticed a change in behaviour, but I do not see this as a bug.

Whilst the use of global variables is not recommended, according to the linked challenge instructions, their use is not prohibited. As such, the given example is a valid solution - recursion is used to solve the task, and the script outputs are correct.

Essentially, I see no issue with the current test runner behaviour. So, if something must change, a requirement in instruction and test should be added to say:
> You must not use any global variables

However, with the specific linked example, I would not be in a rush to change anything, because it is not in the _Functional Programming_ section, and the objective behind the lesson is accomplished.

**Comment by jeremylt** [comment]
I would assume it is a change somewhere here:
https://github.com/freeCodeCamp/freeCodeCamp/commits/main/curriculum/test/test-challenges.js

But this stuff is hieroglyphs to me and I don't see anything that would obviously cause the change.

**Comment by ieahleen** [comment]
if I remember correctly it was somewhere around the issue that is there if the global state stay the same with people using `test` regex method with the `g` flag, with tests failing because lastIndex advance and people not getting it

**Comment by jeremylt** [comment]
That seems like a reasonable thing to do for the regex tests, but it lets a ton of bad code through for the rest of the JavaScript challenges.

**Comment by jeremylt** [comment]
This also makes the Project Euler solutions run slower by wiping any cached values, which makes it harder to show the benefits of memoization for people doing the interview prep challenges.

**Comment by ieahleen** [comment]
checking the regex challenges to add a test for the `g` flag may be a bit of work, but it can make so to revert the change. or it could be hidden by adding a `regex.lastIndex = 0` before each test run

**Comment by jeremylt** [comment]
Hmm, if it isn't possible to selectively reset the global space only for some challenges, that might be the way to go.

**Comment by ieahleen** [comment]
let's open this for help and let's see if someone is willing to go through the regex challenges

**Comment by Sboonny** [comment]
I wonder if this issue still open, and what should i do to help, if so?

**Comment by DEBADRIBASAK** [comment]
Is this issue still open? I would like to work on it.
