### ISSUE TITLE
$$ 1 800 439 2949 $$ Canon Printer Technical  Support Phone Number, Canon Printer Support Phone Number

### ISSUE THREAD

**Issue by marrykanty** [FreeCodeCamp/FreeCodeCamp#4352]
$$ 1 800 439 2949 $$ Canon Printer Technical  Support Phone Number, Canon Printer Support Phone Number

**Comment by Chris2Brooks** [comment]
@bugron any way that FreeCodeCamp moderators could block this account from the repo?

**Comment by Chris2Brooks** [comment]
@bugron oh and thanks for flagging and closing all of them

**Comment by bugron** [comment]
@Chris2Brooks I'm trying to find that out.
