### ISSUE TITLE
Issue: Authentication with Socket.IO

### ISSUE THREAD

**Issue by nayabatir1** [freeCodeCamp/freeCodeCamp#43574]
## Affected page

[challenge link](https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/authentication-with-socket-io)

## Your code

```js
'use strict';
require('dotenv').config();
const express = require('express');
let myDB = require('./connection');
const session = require('express-session')
const fccTesting = require('./freeCodeCamp/fcctesting.js');
const passport = require('passport')
const auth = require('./auth.js')
const routes = require('./routes.js')
const MongoStore = require('connect-mongo')(session);
const URI = process.env.MONGO_URI;
const store = new MongoStore({ url: URI });
const passportSocketIo = require("passport.socketio");



const app = express();

const http = require('http').createServer(app);
const io = require('socket.io')(http);

app.set('view engine', 'pug')

fccTesting(app); //For FCC testing purposes
app.use('/public', express.static(process.cwd() + '/public'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.use(session({
  secret: process.env['SESSION_SECRET'],
  resave: true,
  saveUninitialized: true,
  cookie: { secure: false }
}));

app.use(passport.initialize())
app.use(passport.session())



myDB(async (client) => {
  const myDataBase = await client.db('repl').collection('users');
  let currentUsers = 0;
  io.on('connection', socket => {
    console.log('A user has connected');
    ++currentUsers;
    io.emit('user count', currentUsers);
  });
  socket.on('disconnect', () => {
    /*anything you want to do on disconnect*/
    --currentUsers;
  });
  routes(app, myDataBase);
  auth(app, myDataBase);

}).catch((e) => {
  app.route('/').get((req, res) => {
    res.render('pug/index', { title: e, message: 'Unable to login' });
  });
});
// app.listen out here...


const PORT = process.env.PORT || 3000;
http.listen(PORT, () => {
  console.log('Listening on port ' + PORT);
});

```

## Expected behavior

![image](https://user-images.githubusercontent.com/91016903/134804556-817a7fcf-3716-41b6-9912-8ea4de87e20c.png)
I've written above as mentioned in challenge description.

## Screenshots

![image](https://user-images.githubusercontent.com/91016903/134804602-18dd08b7-2705-4653-94f6-82bfbaa068f9.png)
But the code shared in description is not working as it should.

## System

- Device: laptop
- OS: ubuntu 20.04
- Browser: firefox
- Version: 92.0 (64-bit)

## Additional context
I'm doing above challenge in [repl](https://replit.com/@jack1947/boilerplate-advancednode#server.js)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
