### ISSUE TITLE
Adding a comment causes a valid answer to be wrong

### ISSUE THREAD

**Issue by jsgm** [freeCodeCamp/freeCodeCamp#43578]
## Affected page
Adding a comment causes the result that should be correct to be returned as invalid in the following page:

[JavaScript Algorithms and Data Structures > ES6 > Compare Scopes of the var and let Keywords](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/compare-scopes-of-the-var-and-let-keywords)

## Your code

**Code used:**
```
function checkScope() {
  let i = 'function scope';
  if (true) {
    /* Block scope */
    let i = 'block scope';
    console.log('Block scope i is: ', i);
  }
  console.log('Function scope i is: ', i);
  return i;
}
```

**Console result after running tests:**
```
// running tests
The variable i declared in the if statement should equal the string block scope.
// tests completed
// console output
Block scope i is:  block scope
Function scope i is:  function scope
```

## Expected behavior
The answer above should be taken as correct ✅

## Screenshots
![image](https://user-images.githubusercontent.com/34169065/134819040-94cd263b-8af8-4b88-9414-eeec92d50613.png)
![image](https://user-images.githubusercontent.com/34169065/134819089-0412c772-be1c-4ed6-9d88-a1b7ee575fb5.png)
![image](https://user-images.githubusercontent.com/34169065/134819099-62d88dfa-2c3e-4260-85d4-b6637e783cb5.png)

## System

- Device: Desktop
- OS: Windows 10
- Browser: Brave
- Version: 1.29.81 Chromium: 93.0.4577.82 (Build oficial) (64 bits)

**Comment by ojeytonwilliams** [comment]
Thanks for the report @jsgm.  The problem is that comments are not removed from `(getUserInput('index'))`, only from the `code` variable.

A simple fix would be to re-write the test to use `code`.  For example:

```js
  assert(code.match(/(i\s*=\s*).*\s*.*\s*.*\1('|")block\s*scope\2/g));
```

**Comment by elfransat** [comment]
Hi,

Would I be able to have a go at this? 

Thanks

**Comment by elfransat** [comment]
hi @gikf 

This issue does appear to have the label first timers only as far as I can tell.

**Comment by gikf** [comment]
@elfransat, to use a different words - you are free to contribute, if you are first-time contributor, and you don't need to ask :slightly_smiling_face:

**Comment by prashantaghoshal** [comment]
Hi @gikf 

Am an absolute newbie and this is my first first-step in Open Source World. Have submitted a PR to fix this issue. many thanks for providing this for a beginner to take up. While submitting the PR, i just realized that i have not taken care of the localization versions - Chinese, Spanish etc.  Will the update be pushed to these versions automatically? Else should i update those files too and put in another PR. I did not want to break anything with the localization. 
Thanks

**Comment by gikf** [comment]
Hey @prashantaghoshal

files in other languages don't need (nor should they) to be changed manually. They will be updated using the translation workflow.

**Comment by prashantaghoshal** [comment]
Hi @gikf 

Many Thanks for your review and guidance. have updated accordingly.
