### ISSUE TITLE
Claim cartification card shows completed step without signing in.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#43585]
## Affected page

Certification pages

## Expected behavior

Users should be singed in before their requirements are checked.

## Screenshots

<img width="905" alt="Screen Shot 2021-09-27 at 4 12 39 PM" src="https://user-images.githubusercontent.com/4591597/134916697-5e1b8a35-7212-4b77-869a-de225fc8268f.png">

**Comment by Sembauke** [comment]
@ahmadabdolsaheb  This will be fixed in the pr I made #43335.
