### ISSUE TITLE
When selecting a language in the nav menu it opens in a new tab

### ISSUE THREAD

**Issue by kelvinsanchez15** [freeCodeCamp/freeCodeCamp#43639]
## Affected page

[https://www.freecodecamp.org/](https://www.freecodecamp.org/)

## To reproduce

1. Go to [https://www.freecodecamp.org/](https://www.freecodecamp.org/)
2. Click on 'Menu'
3. Select a language (ex. Español)
4. See how it opens in a new tab

## Expected behavior

It should open in the same tab.

## System

- Device: Laptop
- OS: Windows 104]
- Browser: chrome
- Version: 94

**Comment by Dhananjaymahajan2001** [comment]
hello i would like to work on this issue but i am quite new to open source so can you help me with which files to check for the code

**Comment by ieahleen** [comment]
@Dhananjaymahajan2001 thank you for wanting to contribute, this issue has not been triaged yet. Check our contributing guidelines at contribute.freecodecamp.org . Check issued with labels “first timers only” and “help wanted” to know where you can contribute.

**Comment by starkkumarkk1611** [comment]
Hi, I can fix this issue assign me this issue. I have inspected the affected page there is a target blank attribute

**Comment by uttammanani** [comment]
I want to work on this issue, please assign me this task. I can fix this for sure.

**Comment by ieahleen** [comment]
@starkkumarkk1611 @uttammanani thank you for wanting to contribute, this issue has not been triaged yet, check the “help wanted” or “first timers only” labels.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by moT01** [comment]
I feel like there was a reason that we had those open in a new tab, but I don't recall exactly why. I think we should leave it as-is for now, until we can figure out if that was intentional or not.

**Comment by Tamanna-S** [comment]
may i resolve this issue..?

**Comment by ieahleen** [comment]
@Tamanna-S this issue is blocked, look at issues with "help wanted" or "first timers only" to know what needs contribution

**Comment by viroopaksh-utrayak** [comment]
i know how to resolve this  issue

**Comment by viroopaksh-utrayak** [comment]
> may i resolve this issue..?

but how

**Comment by Tamanna-S** [comment]
okay.. thank you 
@ieahleen i am beginner may you help me how to get started in it?

**Comment by ieahleen** [comment]
@viroopaksh-utrayak @Tamanna-S thank you for your interest but this issue is blocked, it is not open for contribution.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by manishreddy6305** [comment]
I can resolve this issue. Can you assign this issue to me?  Probably it may take 1-4 hour.

**Comment by ieahleen** [comment]
@manishreddy6305 before commenting on an issue please read already existing posts, I already answered to really similar posts already

**Comment by manishreddy6305** [comment]
> @manishreddy6305 before commenting on an issue please read already existing posts, I already answered to really similar posts already

Sorry My bad .

**Comment by Le-Roi777** [comment]
> I feel like there was a reason that we had those open in a new tab, but I don't recall exactly why. I think we should leave it as-is for now, until we can figure out if that was intentional or not.

Hi @moT01,

The HTML `<a>` tag links in the menu language options has the HTML `<a>` tag target attribute.

The target attribute value `target="_blank"` wil open the page in a new  window.
`<a target="_blank">Español</a>`

If you decide not to open the page in a new window, you can simply set the target attribute value to `target="_self"`, this is by default.
`<a target="_self">Español</a>`

**Comment by ashan333** [comment]
Yess it will

**Comment by satvik07-ynk** [comment]
I can fix this issue, please assign me.

**Comment by gikf** [comment]
@satvik07-ynk Please read all comments in this issue.
