### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by neeraj-2** [freeCodeCamp/freeCodeCamp#43688]
## Affected page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/README.md

## To reproduce

Just go through the readme and check line number 13, which says: 

> Our full-stack web development and machine learning curriculum **is** completely free and self-paced. We have thousands of interactive coding challenges to help you expand your skills.

## Recommended fix, suggestions

It appears that the singular verb 'is' does not agree with the plural compound subject Our full-stack web development and machine learning curriculum. Consider changing the verb to the plural form. So the line should be modified as:

> Our full-stack web development and machine learning curriculum **are** completely free and self-paced. We have thousands of interactive coding challenges to help you expand your skills.

**Comment by neeraj-2** [comment]
Realized it has already been fixed. Thanks

**Comment by ieahleen** [comment]
Curriculum is singular
