### ISSUE TITLE
Maintaining Streak

### ISSUE THREAD

**Issue by pasportit** [FreeCodeCamp/freecodecamp#437]
Everybody has a different pace at which we are comfortable at studying. Some challenges on the Map take longer then others, sometimes you stop and read a different source. Learning is a curve, and sometimes it can be difficult to motivate yourself. I use streaks as a motivation tool. If I am not able to complete a challenge today because I spent a day reading a book to understand a concept better, then I believe I should still get a streak. Perhaps you get one point if you logged in to the website, or perhaps you write a summary not on what you've been up to today.  

Thank you for consideration.

**Comment by terakilobyte** [comment]
I do like the idea of either notes, perhaps a personal learning diary or whatnot with a link to it from the profile page.

I'm very much against getting a point for just visiting the site.

**Comment by QuincyLarson** [comment]
Note that one easy way to maintain your streak is to post something to Camper News. This will give you one point immediately, and another point for each time that post is upvoted.

**Comment by pasportit** [comment]
I understand that, but at some level it feels like cheating. Here comes the spam!
