### ISSUE TITLE
Remove whitespace challenge can be passed by editing variable directly

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#43788]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end

## Your code

```
let hello = "Hello, World!";
let wsRegex = /change/; // Change this line
let result = hello; // Change this line
```

## Expected behavior

The challenge shouldn't pass as the user is directly editing the `hello` variable. Another test should be added to this [file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end.md) to check if the user has changed the value of `hello` or not.

## Bug report source
https://forum.freecodecamp.org/t/remove-whitespace-from-start-and-end-challenge-bug/480586

**Comment by Prathamesh010** [comment]
I would like to work on this issue!

**Comment by ManishOffi** [comment]
Hey @Nirajn2311 ,
If you allow me then i contribute this issue?

**Comment by ManishOffi** [comment]
@ieahleen 
Thanks!
