### ISSUE TITLE
Bug: List of unique winning teams doesn't match the expected_output.txt

### ISSUE THREAD

**Issue by jeremyfiel** [freeCodeCamp/freeCodeCamp#43856]
repo: https://www.github.com/freecodecamp/learn-world-cup-database

In queries.sh, one of the challenges is to write a SQL statement to return a list of unique winning teams in the dataset. The expected_output.txt file has an incorrect list.

To Reproduce

seed the database with the instructions in the lesson
write a SQL statement to return the list of unique winning teams
Expected behavior
The result set should only have 11 rows of unique winning teams.

cc @moT01

**Comment by moT01** [comment]
This should be fixed 👍 Let me know if there's still a problem
