### ISSUE TITLE
Bug with this lesson 

### ISSUE THREAD

**Issue by Evaughan1014** [FreeCodeCamp/FreeCodeCamp#4388]
Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20array.reverse(function()%7B%0A%20%20%0A%20%20return%20myArray%3B%0A%20%20%0A%7D)%3B%20%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7Breturn%20newArray%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.

var newArray = array.reverse(function(){
  
  return myArray;
  
}); 


// Only change code above this line.

(function() {return newArray;})();

```

i successfully reversed the code but its not letting me pass the course

**Comment by ltegman** [comment]
The lesson is not letting you pass because you did not use `reverse` correctly. `reverse` should not be passed any arguments when you use it.

Closing as not an issue with the tests.

Thanks and happy coding!

**Comment by nevergolden** [comment]
Challenge: Uncomment HTML
Deleted all trailing comments but cannot pass this course:
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
