### ISSUE TITLE
Challenge:Uncomment HTML

### ISSUE THREAD

**Issue by nevergolden** [FreeCodeCamp/FreeCodeCamp#4389]
Can't seem to pass the lesson after deleting all trailing comments.  Is there something specific I'm missing?
```html
<!---->
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
```

**Comment by ltegman** [comment]
You still have a comment (which includes the closing tag) at the top of the page. Remove that and the tests will pass.

Closing as not an issue with the tests. In the future please ask for help in the [Gitter Help Channel](https://gitter.im/FreeCodeCamp/Help) before filing a bug.

Thanks and happy coding!
