### ISSUE TITLE
End of Waypoints leads to start of Ziplines

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/freecodecamp#439]
When you click "I've completed this challenge" on 'Pair Program on Bonfires' (the last Waypoint), it directs you to 'Get Set for Ziplines' instead of 'Meet Bonfire'.

**Comment by terakilobyte** [comment]
I'm unable to reproduce this behavior. Please provide a screenshot of your challenge map.

**Comment by AkiraLaine** [comment]
![map](https://cloud.githubusercontent.com/assets/11958359/7553140/d47108c2-f72f-11e4-9661-546c23103337.JPG)

**Comment by AkiraLaine** [comment]
UPDATE: Now that I have done a few Bonfires, I cannot reproduce the bug.

**Comment by terakilobyte** [comment]
I suspect this has something to do with the age of your account. I tested this multiple times last night on fresh accounts and every time it took me to bonfires after completing challenge 44.
