### ISSUE TITLE
Array.prototype.filter() is not a function

### ISSUE THREAD

**Issue by t73biz** [FreeCodeCamp/FreeCodeCamp#4390]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I have tested this elsewhere, locally as well as on codepen. http://codepen.io/t73biz/pen/BovpKP

Both places are working as expected.

My code:
```javascript
function destroyer(arr) {
    var args = Array.prototype.slice.call(arr, 1);
    var ctrl = arr[0];
    results = ctrl.filter(function(value){
        return args.indexOf(value) === -1;
    });

    return results;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
![screen shot 2015-11-12 at 13 39 14](https://cloud.githubusercontent.com/assets/169922/11129017/d033508a-8942-11e5-9c7b-6f2e92f2b4e7.png)

**Comment by ltegman** [comment]
I get the exact same error FCC is giving you when I run your code in a repl. `arr[0]` is the first element of the array argument that is passed in, which is a number, so this error makes sense.

Closing this as not an issue with the website. In the future please use the [Gitter Help Chat](https://gitter.im/FreeCodeCamp/Help) to ask for assistance when you are encountering problems with a challenge.

Thanks and happy coding!
