### ISSUE TITLE
Link-to-external-pages-with-anchor-elements not working.

### ISSUE THREAD

**Issue by ericrasmusson420** [freeCodeCamp/freeCodeCamp#43906]
## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements

## Your code

```
<h2>CatPhotoApp</h2>
<main>
<a href="https://www.freecodecamp.org">this links to freecodecamp.org</a>
<a ="https://www.freecatphotoapp.com">cat photos"</a>
<img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>



```

## Expected behavior

The test should have advance me to the next lesson. Instead it indicated a mistake -You need an a element that links to https://www.freecatphotoapp.com

## System

- Device: [e.g. iPhone6, Laptop]IBM PC
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]Windows 7
- Browser: [e.g. chrome, safari]Chrome
- Version: [e.g. 22]94.0

**Comment by sunflowermarmalade** [comment]
You have put in a wrong line of code for the solution. It should be

`<h2>CatPhotoApp</h2>
<main>
<a href="https://www.freecodecamp.org">this links to freecodecamp.org</a>
<a href="https://www.freecatphotoapp.com">cat photos"</a>
<img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>`

You missed the href attribute in the anchor tag
