### ISSUE TITLE
Freezing Issue

### ISSUE THREAD

**Issue by abckatxyz** [FreeCodeCamp/FreeCodeCamp#4392]
Currently at "Bonfire: Reverse a String" and I can only type a few characters before the browser freezes. I've tried it on Firefox, Safari, and Google Chrome.

**Comment by ltegman** [comment]
I am not able to reproduce this problem. Is anyone else able to?

@abckatxyz Out of curiosity, where and what are you trying to type?

**Comment by abckatxyz** [comment]
Hm it seems to be working fine now. Thanks!

**Comment by michaelkp** [comment]
Having the same issue. I type "function" and the browser freezes. I have to close the tab and reopen to continue.
