### ISSUE TITLE
Bug: Most goals scored in a single game doesn't match the expected_output.txt

### ISSUE THREAD

**Issue by jeremyfiel** [freeCodeCamp/freeCodeCamp#43936]
repo: https://www.github.com/freecodecamp/learn-world-cup-database

In queries.sh, one of the challenges is to write a SQL statement to return a list of `Most goals scored in a single game` in the dataset. The expected_output.txt file has an incorrect value of `7`.

To Reproduce

seed the database with the instructions in the lesson
write a SQL statement to return the calculation of `Most goals scored in a single game`
Expected behavior
The result should be `8`.

related to #43856 

cc @moT01

**Comment by iccowan** [comment]
I believe this is referencing the total number of goals scored by one team, which would be seven. I will add clarification in the tutorial.

**Comment by moT01** [comment]
This should be fixed 👍 We went with clarifying the instructions to "Most goals scored in a single game by one team".
