### ISSUE TITLE
Two small typos in Waypoint: Make Instances of Objects with a Constructor Function

### ISSUE THREAD

**Issue by matty22** [FreeCodeCamp/FreeCodeCamp#4394]
Two small typos in this waypoint:

To use a constructor function we call it with the new keyword in front *if* it like:

*javascript*

I have a pull request ready, but wanted to open an issue prior to submitting a PR.

**Comment by iheartkode** [comment]
Did you submit a PR yet?

**Comment by SaintPeter** [comment]
Submitted and accepted.

Closed via #4395
