### ISSUE TITLE
Minor grammatical error in "Waypoint: Count Backwards With a For Loop"

### ISSUE THREAD

**Issue by rjmccallumbigl** [FreeCodeCamp/FreeCodeCamp#4397]
It says "Let's change our initialization and final-expression so we can count backward by twos for numbers."

Shouldn't it be "Let's change our initialization and final-expression so we can count backward by twos for **odd** numbers."

![image](https://cloud.githubusercontent.com/assets/15747450/11133903/eab748de-8966-11e5-99dd-ce97dcf7bd0b.png)

**Comment by SaintPeter** [comment]
Got it, thanks!
