### ISSUE TITLE
Typo in Waypoint: Reverse Arrays with reverse

### ISSUE THREAD

**Issue by gasperno** [FreeCodeCamp/FreeCodeCamp#4399]
There is a typo I found in one of the waypoint challenges.
In the link below, the description says reverse an array and set it to myArray.
But the waypoint is achieved by setting the reversed array to newArray.

http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse

**Comment by SaintPeter** [comment]
Confirmed.  Will fix.

**Comment by faizaanceg** [comment]
Can I do this/? @SaintPeter

**Comment by SaintPeter** [comment]
@faizaanceg Sure.

**Comment by SaintPeter** [comment]
@faizaanceg While you're at it, see if you can move the display function to `tail`.  Check the earlier waypoints for an example.

**Comment by faizaanceg** [comment]
Hmm ok :+1:
