### ISSUE TITLE
Bonfire code font not good

### ISSUE THREAD

**Issue by thirumal** [FreeCodeCamp/freecodecamp#44]
Existing font may look good for the code typed in the editor, but it's a pain to indent and maintain indentation as each letter is of not the same size, could you guys please move to courier new, monospace or something similar?

**Comment by terakilobyte** [comment]
Thanks for your feedback. Bonfire will be using monospaced font upon next release.

**Comment by terakilobyte** [comment]
Going to close this issue as the bonfire-improvement branch has much better styling and represents the way forward for this feature.
