### ISSUE TITLE
Code vanished on this exercise!

### ISSUE THREAD

**Issue by jimvillanueva** [FreeCodeCamp/FreeCodeCamp#4404]
Challenge [Waypoint: Line up Form Elements Responsively with Bootstrap](http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap?solution=) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

After completing the previous exercise, this page loaded with no code or output displayed at all!

**Comment by ltegman** [comment]
Unfortunately I am not able to reproduce this error when finishing the previous challenge and moving onto this one.

You can reset the seed code by using the Reset button on the left hand side of the page, underneath the Run Tests button.

Thanks and happy coding!
