### ISSUE TITLE
Add campfire mode to nav menu

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#44040]
We added Campfire mode(https://github.com/freeCodeCamp/freeCodeCamp/pull/42663). Wondering if we should put a button in the main menu next to the night mode button for it.

**Comment by ahmadabdolsaheb** [comment]
It would depend on our plans for this feature and how useful it would be to keep it accessible in the dropdown menu.
@nhcarrigan what do you think?

**Comment by nhcarrigan** [comment]
Let's leave this issue open for a bit - I'm not sure this is something people will toggle on and off enough to warrant taking up the space.

**Comment by kamatheuska** [comment]
Hi there! first contributor here :) What about a submenu?
![submenu-1](https://user-images.githubusercontent.com/26850124/142725434-c1f63cf6-9437-4500-ad27-7372176822d3.png)
![submenu](https://user-images.githubusercontent.com/26850124/142725424-c9619c69-265b-4c9a-8435-aecd48561459.png)

**Comment by ahmadabdolsaheb** [comment]
I am leaning towards keeping the campfire mode as a hidden gem.

**Comment by kamatheuska** [comment]
@ahmadabdolsaheb Do you mind expanding on why to hide a feature? Maybe it's not working as it should yet?

**Comment by cenkberry** [comment]
campfire mode is so good , I liked...

**Comment by ahmadabdolsaheb** [comment]
@kamatheuska, thanks for the question. It would help with reducing cognitive load. I think we should only display what we have to to keep the UI as simple as possible. That being said, this is only an opinion. I don't have hard data on the matter.

**Comment by nhcarrigan** [comment]
Going to go ahead and close this in agreement with Ahmad's point about cognitive load.
