### ISSUE TITLE
Can not pass first testing condition with correct result

### ISSUE THREAD

**Issue by oyang** [FreeCodeCamp/FreeCodeCamp#4406]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%20%7B%0A%20%20return%20val%20%3C%205%3B%0A%7D)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7B%20return%20newArray%3B%20%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
  return val < 5;
});

// Only change code above this line.

(function() { return newArray; })();

```

**Comment by faizaanceg** [comment]
> Use `filter` to remove all elements from array that are **greater than** 5.

Your code not only removes the numbers that are greater than 5 but it also removes 5 itself! 

Please use the [Gitter Chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp) for these questions.

**Comment by oyang** [comment]
Good catch.
