### ISSUE TITLE
Adding link to workflow in CodeRoad tutorial repos

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#44096]
All CodeRoad tutorials should have a link to the contributing workflow.

This issue can be used as masterlist.
I have started with https://github.com/freeCodeCamp/learn-world-cup-database/pull/8 , then once this is finalized and approved the same change should be done to all other projects.

I will list them here, then once it's time this can be open to contributions, and used as masterlist to keep tracks of things. (I will not be able to update it myself, mods feel free to make edits as needed)

- [x] [World Cup Database](https://github.com/freeCodeCamp/learn-world-cup-database) https://github.com/freeCodeCamp/learn-world-cup-database/pull/8
- [x] [Learn Bash by Building a Boilerplate](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate)
- [x] [Learn Bash and SQL by Building a Bike Rental Shop](https://github.com/freeCodeCamp/learn-bash-and-sql-by-building-a-bike-rental-shop)
- [x] [Learn Bash Scripting by Building Five Programs](https://github.com/freeCodeCamp/learn-bash-scripting-by-building-five-programs)
- [x] [Learn Git by Building an SQL Reference Object](https://github.com/freeCodeCamp/learn-git-by-building-an-sql-reference-object)
- [x] [Salon Appointment Scheduler](https://github.com/freeCodeCamp/learn-salon-appointment-scheduler)
- [x] [Learn SQL by Building a Student Database](https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database)
- [x] [Celestial Bodies Database](https://github.com/freeCodeCamp/learn-celestial-bodies-database)
- [x] [Learn Relational Databases by Building a Mario Database](https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database)
- [x] [Periodic Table Database](https://github.com/freeCodeCamp/learn-periodic-table-database)
- [x] [Number Guessing Game](https://github.com/freeCodeCamp/learn-number-guessing-game)
- [x] [Learn Nano by Building a Castle](https://github.com/freeCodeCamp/learn-nano-by-building-a-castle)
- [x] [Learn Advanced Bash by Building a Kitty Ipsum Translator](https://github.com/freeCodeCamp/learn-advanced-bash-by-building-a-kitty-ipsum-translator)

**Comment by shayannosrat** [comment]
@ieahleen i would love to work on this as my first contribution ❤️

**Comment by moT01** [comment]
Thanks for adding all these @shayannosrat 🎉 and congratulations on your first contributions to freeCodeCamp 🎉

**Comment by moT01** [comment]
Thanks for making the issue to track this @ieahleen 🎉 All done 👍
