### ISSUE TITLE
 Make Instances of Objects with a Constructor Function

### ISSUE THREAD

**Issue by LeighHarrisUK** [FreeCodeCamp/FreeCodeCamp#4411]
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var Car = function() {
   this.wheels = 4;
};

// New instance of Car object.
var myCar = new Car();

//Add the property "engines" to myCar, and make it a number.
myCar.engines = 1;

Have tried all solutions and feel I am staring too hard at this to get the final instruction 

Then give myCar a nickname property with a string value. I know this should be simple but however I try to call it it will not accept.
Have tried (function() {return JSON.stringify(myCar);})(); at end as others have given in solutions - console.log is not even accepted here, Preventing me moving on.

**Comment by ltegman** [comment]
Adding a property to an object can be done through dot-notation. Something like the following will satisfy the final instruction:
```javascript
myCar.nickname = "Bob Ryan";
```

Thanks and happy coding!

**Comment by jel111** [comment]
no it doesn't. I thought this should do it and is exactly what I have .

**Comment by KamIsHere** [comment]
The answer is above you @jel111 . Good Luck!!!!!

**Comment by singleparin** [comment]
how is it that changing nickName from camelCase to nickname satisfied the problem?

**Comment by singleparin** [comment]
i'm kinda confused?

**Comment by Snowcat8** [comment]
You need to use "nickname" (literally. it is written in red). So don't use any property (which is what I did. for e.g. I used .cover or .mirror but that gave me the same string error). They want you to use the word nickname.

**Comment by vishalsharmas** [comment]
they have asked to  assign variable as myCar and constructor as Car.this is how it works below
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 5;
};

// Only change code below this line.
var myCar = new Car();
myCar.nickname = "hourglass23";

**Comment by Koder90** [comment]
Doesn't work for me...doesnt accept solution and console shows nothing.

**Comment by scottcinatl** [comment]
A common error with this problem is forgetting to put a semicolon after you create a new instance. This can seem a little picky since javascript's automatic semicolon insertion should be taken place here. 

// TypeError: "Beast" is not a function - (notice the missing semicolon)
myCar.nickname = "Beast"

// Correct solution with no errors
myCar.nickname = "Beast";
