### ISSUE TITLE
Instructions on Create a More Complex Shape Using Css and HTML

### ISSUE THREAD

**Issue by skaparate** [freeCodeCamp/freeCodeCamp#44141]
Hey everyone!

On the lesson [Responsive Web Design / Applied Visual Design / Create a More Complex Shape Using CSS and HTML](https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/create-a-more-complex-shape-using-css-and-html), with regards to `::before` and `::after`, it says:

> These pseudo-elements are used to add something before or after a selected element

I think this is not actually correct. A more appropriate definition could be: 

> These pseudo-elements are used to add content before or after a selected element's content

Otherwise it may lead people to believe it's getting added before/after the actual element.

Another definition could be (taken from the MDN):

> ::before creates a pseudo-element that is the first child of the selected element; ::after creates a pseudo-element that is the last child of the selected element.

**Comment by Emiliano-Russo** [comment]
i'll do it (i like MDN definition)
