### ISSUE TITLE
Fails validation / Tried removing spaces / changing case adding text all fails

### ISSUE THREAD

**Issue by davidva123** [FreeCodeCamp/FreeCodeCamp#4414]
Challenge [Waypoint: Fill in the Blank with Placeholder Text](http://www.freecodecamp.com/challenges/waypoint-fill-in-the-blank-with-placeholder-text?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3Ekitty%20ipsum%20text%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>kitty ipsum text</p>

```

**Comment by davidva123** [comment]
hard refresh failed / reset app restarted browser worked.

**Comment by SnakeByte2** [comment]
I have the same problem, but the resets have not worked for me.
