### ISSUE TITLE
Iterate over Arrays with map

### ISSUE THREAD

**Issue by LeighHarrisUK** [FreeCodeCamp/FreeCodeCamp#4415]
//Use map to add three to each value in the array
var array = [1,2,3,4,5];
console.log(array);
// Only change code below this line.
var array = array.map(function(num){
return num + 3;
});
console.log(array);
// Only change code above this line.
(function() {return(array);})();

Ran this in re.plit and it adds three to all in array.Sometimes find this frustrating when you dont give the exact answer that FCC requires, because I still get you should add three to each value in the array

**Comment by SaintPeter** [comment]
The problem is that you have tried to re-define `array` with:
```js
var array = array.map(function(num){  // Only one definition of arr is needed
```

In the future, please ask for assistance in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) or [Bonfire Help Chat](https://gitter.im/FreeCodeCamp/HelpBonfires) before filing an issue.

Thanks and happy coding!
