### ISSUE TITLE
Clicking Next Field Guide Entry Button or Pressing Ctrl-Enter Increments completion count

### ISSUE THREAD

**Issue by StevenKW** [FreeCodeCamp/freecodecamp#442]
When reading the field guides:
Clicking Next Field Guide Entry Button or Pressing Ctrl-Enter Increments completion count at the top right of the header and profile page. It only does this if the the field guide is unread.
![image](https://cloud.githubusercontent.com/assets/4203807/7576588/4740bf72-f7f4-11e4-982f-a72bc597cfbf.png)
![image](https://cloud.githubusercontent.com/assets/4203807/7576597/5af254d6-f7f4-11e4-8438-4007197027b7.png)
![image](https://cloud.githubusercontent.com/assets/4203807/7576605/6fcbb640-f7f4-11e4-872a-556a5ca4384e.png)

**Comment by terakilobyte** [comment]
This isn't a bug. You get a point for reading every field guide the first time.

**Comment by StevenKW** [comment]
Sorry about that. I thought the point count was for Waypoints, Bonfires, Ziplines, and Basejumps.
