### ISSUE TITLE
Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by drafina** [FreeCodeCamp/FreeCodeCamp#4422]
I added the ".parent()" method to my "#target1" and added $("#left-well").parent().css("background-color", "red"); which actually did change the color of the background to red. However, the "Your left-well element should have a red background." instructions are still showing unchecked.

**Comment by SaintPeter** [comment]
Please take your code questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).  Only file issues for a confirmed bug in the website.

Thanks and happy coding!

**Comment by drafina** [comment]
Hi, I took it to the Help Room, and they said there is nothing else that I could have done.

**Comment by SaintPeter** [comment]
Without seeing your code I cannot comment.  It is impossible for us to debug your issue without code.

Are you unable to pass the waypoint?  If you PM me on Gitter I can take a look at your code.
