### ISSUE TITLE
Back End Development and APIs and Information Security projects description typo

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#44231]
There's small typo in description of some _Back End Development and APIs_ and _Information Security_ projects. Sentence with:
> Optionally, also submit a link to your **projects** source code in the `GitHub Link` field.

Should have apostrophe in word _projects_ as written below:
Optionally, also submit a link to your **project's** source code in the `GitHub Link` field.

## Affected page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/file-metadata-microservice
https://www.freecodecamp.org/learn/information-security/information-security-projects/stock-price-checker
https://www.freecodecamp.org/learn/information-security/information-security-projects/anonymous-message-board

## Additional context

Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice.md
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice.md
3. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/file-metadata-microservice.md
4. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/information-security-projects/stock-price-checker.md
5. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by pariksh1th** [comment]
I would like to work on this issue

**Comment by gikf** [comment]
Hey @pariksh1th,

thank you for being eager to contribute. This issue has already corresponding PR, which most likely will close the issue. Feel free to look at other issues labelled with `help wanted` or `first timers only`.
