### ISSUE TITLE
Waypoint 168 challenge explanation does not correspond to solution

### ISSUE THREAD

**Issue by Mamacom** [FreeCodeCamp/FreeCodeCamp#4423]
I have been banging my head against the wall with this challenge. It says to create an if statement with multiple conditions, so that 3 same numbers return null. But then the text underneath run test says that it's only when 3 numbers are different that they should return null. I tried pasting the code in the explanation into the editor and it did not pass. Then entered a completely different code from the wiki into the editor and I passed the challenge.

Totally, totally confusing.

**Comment by Mamacom** [comment]
Just to add to this, I copied the code in Waypoint 160:

  if (slotOne === slotTwo && slotTwo === slotThree) {
      $(".logger").html(" It's A Win")
      return null;
    }

and went back to Waypoint 168 to paste it in, and it did not pass the challenge.

Seems there's definitely a big there.

**Comment by jbmartinez** [comment]
Could you provide a link to the waypoint?

**Comment by Mamacom** [comment]
http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots?solution=fccss%0A%20%20function%20runSlots()%20%7B%0A%20%20%20%20var%20slotOne%3B%0A%20%20%20%20var%20slotTwo%3B%0A%20%20%20%20var%20slotThree%3B%0A%20%20%20%20%0A%20%20%20%20var%20images%20%3D%20%5B%22http%3A%2F%2Fi.imgur.com%2F9H17QFk.png%22%2C%20%22http%3A%2F%2Fi.imgur.com%2F9RmpXTy.png%22%2C%20%22http%3A%2F%2Fi.imgur.com%2FVJnmtt5.png%22%5D%3B%0A%20%20%20%20%0A%20%20%20%20slotOne%20%3D%20Math.floor(Math.random()%20*%20(3%20-%201%20%2B%201))%20%2B%201%3B%0A%20%20%20%20slotTwo%20%3D%20Math.floor(Math.random()%20*%20(3%20-%201%20%2B%201))%20%2B%201%3B%0A%20%20%20%20slotThree%20%3D%20Math.floor(Math.random()%20*%20(3%20-%201%20%2B%201))%20%2B%201%3B%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%0A%20%20if%20(slotOne%20%3D%3D%3D%20slotTwo%20%26%26%20slotTwo%20%3D%3D%3D%20slotThree)%20%7B%0A%20%20%20%20%20%20%24(%22.logger%22).html(%22%20It%27s%20A%20Win%22)%0A%20%20%20%20%20%20return%20null%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%20%20%20%20%0A%20%20%20%20if(slotOne%20!%3D%3D%20undefined%20%26%26%20slotTwo%20!%3D%3D%20undefined%20%26%26%20slotThree%20!%3D%3D%20undefined)%7B%0A%20%20%20%20%20%20%24(%22.logger%22).html(slotOne%20%2B%20%22%20%22%20%2B%20slotTwo%20%2B%20%22%20%22%20%2B%20slotThree)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%24(%22.logger%22).append(%22%20Not%20A%20Win%22)%3B%0A%20%20%20%20%0A%20%20%20%20return%20%5BslotOne%2C%20slotTwo%2C%20slotThree%5D%3B%0A%20%20%7D%0A%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%20%24(%22.go%22).click(function()%20%7B%0A%20%20%20%20%20%20%20runSlots()%3B%0A%20%20%20%20%20%7D)%3B%0A%20%20%20%7D)%3B%0Afcces%0A%20%0A%3Cdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22container%20inset%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22header%20inset%22%3E%0A%20%20%20%20%20%3Cimg%20src%3D%22https%3A%2F%2Fs3.amazonaws.com%2Ffreecodecamp%2Ffreecodecamp_logo.svg.gz%22%20alt%3D%22learn%20to%20code%20javascript%20at%20Free%20Code%20Camp%20logo%22%20class%3D%22img-responsive%20nav-logo%22%3E%0A%20%20%20%20%20%3Ch2%3EFCC%20Slot%20Machine%3C%2Fh2%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22slots%20inset%22%3E%0A%20%20%20%20%20%3Cdiv%20class%20%3D%20%22slot%20inset%22%3E%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%3Cdiv%20class%20%3D%20%22slot%20inset%22%3E%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%3Cdiv%20class%20%3D%20%22slot%20inset%22%3E%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%20%3Cbr%2F%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22outset%22%3E%0A%20%20%20%20%20%3Cbutton%20class%20%3D%20%22go%20inset%22%3E%0A%20%20%20%20%20%20%20Go%0A%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%20%3Cbr%2F%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22foot%20inset%22%3E%0A%20%20%20%20%20%3Cspan%20class%20%3D%20%22logger%22%3E%3C%2Fspan%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%0A%3Cstyle%3E%0A%20.container%20%7B%0A%20%20%20background-color%3A%20%234a2b0f%3B%0A%20%20%20height%3A%20400px%3B%0A%20%20%20width%3A%20260px%3B%0A%20%20%20margin%3A%2050px%20auto%3B%0A%20%20%20border-radius%3A%204px%3B%0A%20%7D%0A%20.header%20%7B%0A%20%20%20border%3A%202px%20solid%20%23fff%3B%0A%20%20%20border-radius%3A%204px%3B%0A%20%20%20height%3A%2055px%3B%0A%20%20%20margin%3A%2014px%20auto%3B%0A%20%20%20background-color%3A%20%23457f86%0A%20%7D%0A%20.header%20h2%20%7B%0A%20%20%20height%3A%2030px%3B%0A%20%20%20margin%3A%20auto%3B%0A%20%7D%0A%20.header%20h2%20%7B%0A%20%20%20font-size%3A%2014px%3B%0A%20%20%20margin%3A%200%200%3B%0A%20%20%20padding%3A%200%3B%0A%20%20%20color%3A%20%23fff%3B%0A%20%20%20text-align%3A%20center%3B%0A%20%7D%0A%20.slots%7B%0A%20%20%20display%3A%20flex%3B%0A%20%20%20background-color%3A%20%23457f86%3B%0A%20%20%20border-radius%3A%206px%3B%0A%20%20%20border%3A%202px%20solid%20%23fff%3B%0A%20%7D%0A%20.slot%7B%0A%20%20%20flex%3A%201%200%20auto%3B%0A%20%20%20background%3A%20white%3B%0A%20%20%20height%3A%2075px%3B%0A%20%20%20margin%3A%208px%3B%0A%20%20%20border%3A%202px%20solid%20%23215f1e%3B%0A%20%20%20border-radius%3A%204px%3B%0A%20%7D%0A%20.go%20%7B%0A%20%20%20width%3A%20100%25%3B%0A%20%20%20color%3A%20%23fff%3B%0A%20%20%20background-color%3A%20%23457f86%3B%0A%20%20%20border%3A%202px%20solid%20%23fff%3B%0A%20%20%20border-radius%3A%202px%3B%0A%20%20%20box-sizing%3A%20none%3B%0A%20%20%20outline%3A%20none!important%3B%0A%20%7D%0A%20.foot%20%7B%0A%20%20%20height%3A%20150px%3B%0A%20%20%20background-color%3A%20457f86%3B%0A%20%20%20border%3A%202px%20solid%20%23fff%3B%0A%20%7D%0A%20%0A%20.logger%20%7B%0A%20%20%20color%3A%20white%3B%0A%20%20%20margin%3A%2010px%3B%0A%20%7D%0A%20%0A%20.outset%20%7B%0A%20%20%20-webkit-box-shadow%3A%200px%200px%2015px%20-2px%20rgba(0%2C0%2C0%2C0.75)%3B%0A%20%20%20-moz-box-shadow%3A%200px%200px%2015px%20-2px%20rgba(0%2C0%2C0%2C0.75)%3B%0A%20%20%20%20%20box-shadow%3A%200px%200px%2015px%20-2px%20rgba(0%2C0%2C0%2C0.75)%3B%0A%20%7D%0A%20%0A%20.inset%20%7B%0A%20%20%20-webkit-box-shadow%3A%20inset%200px%200px%2015px%20-2px%20rgba(0%2C0%2C0%2C0.75)%3B%0A%20%20%20-moz-box-shadow%3A%20inset%200px%200px%2015px%20-2px%20rgba(0%2C0%2C0%2C0.75)%3B%0A%20%20%20box-shadow%3A%20inset%200px%200px%2015px%20-2px%20rgba(0%2C0%2C0%2C0.75)%3B%0A%20%7D%0A%3C%2Fstyle%3E%0A

**Comment by ltegman** [comment]
You're totally right. What the challenge text asks you to do and what the test asks you to do are not the same.

**Comment by SaintPeter** [comment]
We have a recently merged PR, #4260, which actually fixes this issue. 

Closing as fixed.

**Comment by SaintPeter** [comment]
The PR should be pushed live in the next few days.
