### ISSUE TITLE
Exercise Tracker - Back End Development and APIs Projects | problem with toDateString test

### ISSUE THREAD

**Issue by Gers2017** [freeCodeCamp/freeCodeCamp#44249]
## Affected page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker
## Your code

[complete code on replit](https://replit.com/@Gers2017/boilerplate-project-exercisetracker#server.js)
```js
app.get("/api/users/:_id/logs", async (req, res) => {
	const { _id } = req.params;
	let { from, to, limit } = req.query;

	try {
		// get all the exercises
		const exercises = await execiseModel.find({ _user_id: _id },
			"description duration date");

		// get username
		const user = await userModel.findById(_id, "_id username").exec();

		// generate the log
		let log = exercises.map(e => ({
			description: e.description,
			duration: parseInt(e.duration),
			date: e.date,
		}));

		// filter process
		let should_filter_by_date = from !== undefined || to !== undefined;

		if (should_filter_by_date) {
			const fromDate = from ? new Date(from) : new Date(0);
			const toDate = to ? new Date(to) : new Date(MAX_UNIX_TIME);

			if (!isValidDate(fromDate) || !isValidDate(toDate)) {
				return res.json({
					error: "Invalid format on optional dates [from, to]"
				});
			}

			log = log.filter(l => isBetweenDates(new Date(l.date), fromDate, toDate));
		}

		// limit the log (slice it)
		let limit_number = parseInt(limit);
		log = log.slice(0, limit_number > 0 ? limit_number : log.length);

		res.json({
			username: user.username,
			count: log.length,
			_id,
			log
		});
	} catch (e) {
		console.error(e);
		res.json({
			error: `Error at searching user with _id: ${_id}`
		})
	}
});
```

## Expected behavior
I was expecting to pass the dateToString() test
but instead I keep getting this message
```
The date property of any object in the log array that is returned from GET /api/users/:id/logs should be a string.. 
Use the dateString format of the Date API.
```

## Screenshots
![image](https://user-images.githubusercontent.com/49139988/142973410-2e1bceea-fe53-469c-bdb1-ba155b21af8c.png)

### Freecodecamp example
![image](https://user-images.githubusercontent.com/49139988/142973632-b9f2eb83-6001-4a5e-b2f1-b6c3caaf35cc.png)

### My api
![image](https://user-images.githubusercontent.com/49139988/142973653-a06fd559-fc34-4477-a8fc-df716512c471.png)

### As you may already notice both responses are strings and are formatted using dateToString() method from the Date class
![image](https://user-images.githubusercontent.com/49139988/142973850-32249829-ded0-458c-ab40-b6e108d5cf57.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: brave and firefox
- Version: brave: 1.32.106 Chromium: 96.0.4664.45, firefox: 94.0.1 (64-bit)

## Additional context
I have been trying this challenge for 6-8 hours and I couldn't pass the dateString() test case by any means

**Comment by nhcarrigan** [comment]
Hi there,

I just tested submitting your project, and all the tests passed on my end.

**Comment by Gers2017** [comment]
Yeah I tested the project and it passed all the tests. I suppose it was fixed after I created the issue
@nhcarrigan thank you for letting me know
