### ISSUE TITLE
Misleading h2 description

### ISSUE THREAD

**Issue by dalejcruse** [FreeCodeCamp/FreeCodeCamp#4424]
Challenge [Waypoint: Headline with the h2 Element](http://www.freecodecamp.com/challenges/waypoint-headline-with-the-h2-element?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
```

The description says, "h2 elements are slightly smaller than h1 elements." That suggests headings are only related to size. In fact, h1, h2, etc, are structural and form a hierarchy, regardless of their size. Please consider updating this misleading information. Thanks!

**Comment by SaintPeter** [comment]
The description is accurate.  We are not attempting to be, nor could we be a comprehensive source of information on all of the aspects of HTML.  For beginners - true novices - adding a bunch of extraneous information will only serve to confuse or distract them from the fundamentals.  In these early waypoints our focus is on establishing how HTML elements generically are used, not exploring all of the nitty gritty details.

Thank you and happy coding.

**Comment by peterallenio** [comment]
This isn't nitty gritty. Even if you don't give all information and want to give the basics then you should be giving the actual, correct basics. HTML markup is structural, not presentational. Giving someone misleading information so they have to go and correct that knowledge later is counter productive. 

Simply establishing the fact that Heading elements are structural, semantic identifiers and not presentational would suffice. 

>"```h1``` elements are often used for a main headings, ```h2``` elements are generally used for a subheadings."
 
This would be a better, but still incomplete, summary of their use. Mixing up structure and presentation at such an early stage is a recipe for disaster in my opinion.
