### ISSUE TITLE
Faulty code successfully passes tests in Insert an Element Into a Max Heap challenge

### ISSUE THREAD

**Issue by EdenSweden** [freeCodeCamp/freeCodeCamp#44269]
**Describe the bug**

 **Insert an Element Into a Max Heap challenge (Coding Interview Prep Section--Data Structures):**
 I erroneously thought my code was working properly because I passed the challenge. But the array resulting from my code does not satisfy the max heap property.
**To Reproduce:**

1. Go to ['Insert an Element Into a Max Heap'](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/insert-an-element-into-a-max-heap)
2. Paste the following code into the space between the //only change code below this line and //only change code above this line comments:
```
      this.heap = [null];
      this.insert = value => {
        if(this.heap.length === 1) {
          this.heap.push(value);
        } else {
          //this.heap.length = the not-yet-existent index after the last item.
        let parentIndex = Math.floor(this.heap.length/2);
        let parentValue = this.heap[parentIndex];
        if(parentValue < value) {
          this.heap[parentIndex] = value;
          this.heap.push(parentValue);
        } else if (parentValue >= value){
          this.heap.push(value);
        }
        
        }
      }
      this.print = () => {
        console.log(this.heap);
        return this.heap;
      }
```
3. Click "Run the Tests" and watch it pass.
4. Test, either on FCC or in some other environment like JSFiddle/CodeSandbox or your own code editor, by copying and pasting the following code after the MaxHeap() function:

```
let mh = new MaxHeap();
  mh.insert(45);
  console.log(mh.heap);
  mh.insert(30);
  console.log(mh.heap);
  mh.insert(35);
  console.log(mh.heap);
  mh.insert(50);
  console.log(mh.heap);
  mh.insert(20);
  console.log(mh.heap);
  mh.insert(15);
  console.log(mh.heap);
```

5. View console. See how the last three printed arrays do not meet the max heap property. For example, [ null, 45, 50, 35, 30, 20, 15 ]. 50 > 45, but 45 is its parent.

**Expected behavior:**
My code should not pass the last test on FCC. The last test states, "The insert method should add elements according to the max heap property."

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 95.0

**Comment by Prathamesh010** [comment]
The MaxHeap in the 3rd test case has one level of swaps and misses the case when there are multiple levels of swaps and that's why the above code passes it.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/data-structures/insert-an-element-into-a-max-heap.md
