### ISSUE TITLE
Separate 2 variables currently in 1 tag (Problem 124: Ordered radicals)

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#44264]
On Crowdin (translation platform), we are seeing the following string:
`The radical of $n, rad(n)$, is the product of the distinct prime factors of $n$.`

Here `n, rad(n)` are wrapped in 1 pair of `$` tag. (MathJax tag?)

We would like them to be in separate tags so that we can treat them properly in translations. As follows:
`The radical of $n$, $rad(n)$, is the product of the distinct prime factors of $n$.`

## Affected page

Coding Interview Prep > Project Euler > Problem 124: Ordered radicals
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-124-ordered-radicals

I guess the file needs fix is this:
https://github.com/freeCodeCamp/freeCodeCamp/blob/7907f623378b934cdfa47c80b77c5e88678e45a7/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-124-ordered-radicals.md

For your reference, it is written separately in a similar string in "Problem 127: abc-hits"
https://github.com/freeCodeCamp/freeCodeCamp/blob/7907f623378b934cdfa47c80b77c5e88678e45a7/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-127-abc-hits.md

## Expected behavior

`n` and `rad(n)` are in separate tags.

## Screenshots

Screenshot from Crowdin
![project_euler_124_crowdin](https://user-images.githubusercontent.com/25644062/143101489-c46dcb92-c71a-4e2f-bff4-bc7333936a69.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 96.0.4664.45

## Additional context

Originally reported in a comment on Crowdin during translation effort.
https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/22112/en-ja?filter=basic&value=7#q=756633

**Comment by ShaunSHamilton** [comment]
This makes sense to do. As such, I have opened this up to first timers.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Dhananjaymahajan2001** [comment]
hello I think I understand the problem and can solve it so if possible can you assign this to me. 
I think I  only have to make change here: https://github.com/freeCodeCamp/freeCodeCamp/blob/7907f623378b934cdfa47c80b77c5e88678e45a7/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-124-ordered-radicals.md
pls correct me if i am wrong.

**Comment by nhcarrigan** [comment]
Yes that looks like it would be a fix 🙂

**Comment by Sembauke** [comment]
@Dhananjaymahajan2001 It seems like you have opened a pull-request on your origin not on the upstream. Did you mean to do this?

**Comment by Dhananjaymahajan2001** [comment]
yes sorry i think i did it by mistake but i have made the changes now properly i think.
If there is anything wrong please point it out as i am quite new to open source would be helpful.
