### ISSUE TITLE
Some (All?) users have no green squares on their Profile Pages

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4427]
Some users (myself included) are reporting no filled in squares on their profile activity calendar.  All of the squares are gray.
![image](https://cloud.githubusercontent.com/assets/553494/11161644/5458f258-8a37-11e5-9f5d-6710848444a2.png)

**Comment by SaintPeter** [comment]
In the console:
`Uncaught TypeError: Cannot read property 'getTime' of undefined cal-heatmap.min.js:9`

**Comment by faizaanceg** [comment]
Well, FCC is using [cal-heatmap](https://github.com/wa0x6e/cal-heatmap), and there aren't any issues listed regarding this. Is FCC using the latest version?

**Comment by BerkeleyTrue** [comment]
cc @terakilobyte

**Comment by wildlifehexagon** [comment]
Thanks for opening this. I'm having the same issue.

**Comment by terakilobyte** [comment]
I'm looking into it. Could everyone do me a big favor?

Open up your console, and tell me if you see this error:

`Uncaught TypeError: Cannot read property 'getTime' of undefined` ?

**Comment by alistermada** [comment]
@terakilobyte Yep, I've got that error.

**Comment by wildlifehexagon** [comment]
@terakilobyte Yep, same error here.

**Comment by terakilobyte** [comment]
Thanks for the info. Rest assured I'm looking into the issue. Fear not, the data is being saved properly, this is an issue with display.

**Comment by BerkeleyTrue** [comment]
Reverted heat map to previous version. We will re-introduce when this bug has been fixed.
