### ISSUE TITLE
In the HTML/CSS lessons the intructions indicate to use the color rule when it should say background-color

### ISSUE THREAD

**Issue by andrit** [FreeCodeCamp/FreeCodeCamp#4429]
In a few of the lessons in the HTML/CSS lessons/Waypoints, the instruction ask you color the body using different RGB and HEX, but the instructions state: 
"Use rgb to give your body element the background-color of black. For example body { color: rgb(0, 0, 0); }"

The color rule would make the text black, it should say background or background-color

**Comment by SaintPeter** [comment]
If you have give the specific name of the waypoint(s) that would be helpful.  We can track 'em down and fix/clarify.

**Comment by faizaanceg** [comment]
I believe it is [Waypoint: Use RGB values to Color Elements](http://www.freecodecamp.com/challenges/waypoint-use-rgb-values-to-color-elements)

In the tests,

> Use rgb to give your body element the background-color of black. For example body { color: rgb(0, 0, 0); }

**Comment by SaintPeter** [comment]
@faizaanceg You want to fix this one?

**Comment by faizaanceg** [comment]
Sure =)
