### ISSUE TITLE
Build a Nightlife Coordination App: Demo app is not working

### ISSUE THREAD

**Issue by iLtc** [freeCodeCamp/freeCodeCamp#44310]
## Affected page

https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app

## Your code

```
N/A
```

## Expected behavior

When I click the demo app link (https://yoyo44.herokuapp.com/), the demo app should pop up.

## Screenshots

<img width="1621" alt="Screen Shot 2021-11-27 at 9 41 24 PM" src="https://user-images.githubusercontent.com/4352234/143731115-b436a6f7-d1c6-4545-b384-c19f80655ddf.png">

## System

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

## Additional context

On this page, it asks the user to create an app that is similar to https://yoyo44.herokuapp.com/. However, https://yoyo44.herokuapp.com/ is not working.

**Comment by raisedadead** [comment]
@moT01 let's transfer over the source code to the demo projects and get it hosted like the others.

**Comment by moT01** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/48950 to hopefully give it some attention.
