### ISSUE TITLE
Basic algorithm scripting "where do I belong"

### ISSUE THREAD

**Issue by sikafe** [FreeCodeCamp/FreeCodeCamp#4433]
Challenge [Bonfire: Where do I belong](http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20var%20newArray%3Darr.sort()%3B%0A%20%20for(var%20i%3D0%3B%20i%3CnewArray.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(num%3C%3DnewArray%5Bi%5D)%7B%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20newArray.length%3B%0A%7D%0A%0Awhere(%5B5%2C%203%2C%2010%2C%203%5D%2C%205)%20%3B%20%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(arr, num) {
  var newArray=arr.sort();
  for(var i=0; i<newArray.length; i++){
    if(num<=newArray[i]){
      return i;
    }
  }
  return newArray.length;
}

where([5, 3, 10, 3], 5) ; 

```
The code works when you change the 10 to a 9 or any single digit. It should work for both single and double digit numbers.

**Comment by joeyq** [comment]
From the linked docs for [Array.sort()](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort):

>If compareFunction is not supplied, elements are sorted by converting them to strings and comparing strings in Unicode code point order. For example, "Cherry" comes before "banana". In a numeric sort, 9 comes before 80, but because numbers are converted to strings, "80" comes before "9" in Unicode order.

You need to supply a compareFunction when you call arr.sort();
For example, ` var newArray=arr.sort(function(a, b) {
    return a > b;
  });`

That way, your array will be sorted properly and your code will work.

**Comment by SaintPeter** [comment]
This is a code issue, not a site issue.

In the future, please check in the [Help Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) prior to submitting an issue.

Thanks and happy coding!
