### ISSUE TITLE
Individual Basejumps refence Heroku but the Basejumps Waypoint describes setting up c9.io not Heroku

### ISSUE THREAD

**Issue by ariadna-m** [FreeCodeCamp/FreeCodeCamp#4435]
Challenge [Basejump: Build a Voting App](http://www.freecodecamp.com/challenges/basejump-build-a-voting-app) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
All the steps in the challenge reference Heroku but the Basejumps Waypoint referenced here http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps only describes setting up a c9.io account, not a Heroku one.

**Comment by SaintPeter** [comment]
From the last step:
>We will soon add instructions for getting Clementine running on Heroku. For now, develop your Basejumps right on c9.io.

This is on the roadmap, just not completed yet.

**Comment by bheavner** [comment]
Is this still on the roadmap, given the January changes? I'm stopped by the lack of Heroku info prior to this BaseJump as well.
