### ISSUE TITLE
Still have issues with Override All Other Styles by using Important 

### ISSUE THREAD

**Issue by longjay6** [freeCodeCamp/freeCodeCamp#44354]
I followed the video of how to override with !important. However, it still shows that I my H1 element should have pink-text and blue-text. 

My work:

```
<style>
  body {
    background-color: black;
    font-family: monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink !important ;
  }
  .blue-text {
    color:blue;
  }
</style>
<h1 id="orange-text" class:"pink-text blue-text" style="color: white">Hello World!</h1>
```
Update: I had a probelm with google and switched to firefox. I was able to get passed it. Hope this helps other people.

**Comment by raisedadead** [comment]
Hi. 

Thanks for reaching out.

We require you to fill in [the template presented to you](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/ISSUE_TEMPLATE/01--issues-with-coding-challenges.md?plain=1) when you opened this issue. That helps us help you, and take an issue report seriously.

Please add details like a link to the affected page, your system details etc. That will help us reproduce the error and help resolve it.

Thanks & happy coding.

**Comment by danfarrow** [comment]
There’s a typo in the HTML which may or may not be part of the issue:

```
class:"pink-text blue-text"
```

should be:

```
class="pink-text blue-text"
```

**Comment by raisedadead** [comment]
Thanks for clarifying, @danfarrow  

The original issue is better suited for our community in the ask for the help section. I am going to go ahead and close this issue. 

Happy coding!
