### ISSUE TITLE
Missing instruction and test case in "Problem 461: Almost Pi"

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#44367]
According to Project Euler's official site, the following string is missing at the end of freeCodeCamp's challenge.

```
Find g(10000).
```

Project Euler Official
https://projecteuler.net/problem=461

Since the function is renamed to `almostPi` in the freeCodeCamp's challenge, the missing string should be:
```
Find almostPi(10000).
```

If we were to provide the same content as the Project Euler's site, it seems the test for `almostPi(10000)` is missing too.

## Affected page
Coding Interview Prep > Project Euler > Problem 461: Almost Pi
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-461-almost-pi

## Expected behavior

Add the missing string and the test case.

## Screenshots
![problem461](https://user-images.githubusercontent.com/25644062/144552943-153b88ff-01c0-444a-8d1a-235af1276926.png)

## System
- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 96.0.4664.45(Official Build)(64 bit)

## Additional context
Originally reported in a comment on Crowdin
https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/22866/en-ja?filter=basic&value=17#q=731694

**Comment by gikf** [comment]
That wasn't added on purpose when challenge was reworked, with current added solution internal tests would always time out. The same would be very likely for any solution user might try to submit (this is also applying to a number of other _Project Euler_ problems that weren't yet reworked). See #41333.

I guess there could be added some note that original problem was considering way higher input number.

**Comment by sidemt** [comment]
@gikf Sorry I didn't notice there have been reworks for these challenges.
But I still think the instruction is missing at the end. I guess we should add "Write a function almostPi to fulfill the above conditions" or something like that?

**Comment by nhcarrigan** [comment]
Just taking a glance at some random Euler challenges, it looks like none of them have instructions like "write a function `name`" - presumably to keep the verbiage as close to the original problem as possible.

**Comment by sidemt** [comment]
Thanks @nhcarrigan for checking it. I think we can close this issue in that case.
