### ISSUE TITLE
Remove normalize from /learn preview

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#44364]
We discussed that the desired goal of the preview on /learn challenges would be to have it behave exactly (ideally) as a browser would natively. Things like how browsers have a margin by default. Right now, we use normalize to get rid of those things. So if a user writes code in our editor and sees it one way, then moves it to locally or hosted somewhere, it may look different. Wondering if we should get rid of normalize and add steps in the projects to have users remove the margin, and whatever else, manually. If we decide to do that - I would leave projects where that default margin or other things aren't an issue. It may require a decent rework on some of the other projects. One alternative to having users manually remove the margin, could be to have them add normalize as a step.

**Comment by ShaunSHamilton** [comment]
@moT01 A few of the projects already do have those kinds of steps:

- [Learn Accessibility by Building a Quiz](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/learn-accessibility-by-building-a-quiz/step-001.md) - already has normalisation in boilerplate
- [Learn CSS Flexbox by Building a Photo Gallery](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-007.md) - has both one lesson on it, and includes it in boilerplate for 010
- [Learn CSS Grid by Building a Magazin](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/learn-css-grid-by-building-a-magazine/step-026.md) - actually teaches normalisation
- [Learn CSS Variables by Building a Beautiful CSS Skyline](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-007.md) - normalise by removing default margin
- [Learn HTML by Building an Ugly Cat Photo App](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-007.md) - Has no CSS
- [Learn HTML Forms by Building a Registration Form](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/learn-html-forms-by-building-a-registration-form/step-008.md) - normalise by removing default margin
- Learn Intermediate CSS by Building a Picasso Painting - Cannot be normalised
- [Learn Responsive Web Design by Building a Piano](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-009.md) - Explains box-sizing/border-box, and default margins
- Learn the CSS Box Model by Building a Rothko Thing - Nothing
- Learn Typography by Building a Nutrition Label - touches on border-box, but that is it
