### ISSUE TITLE
Create "Setup and Deploy to Heroku" Waypoint

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4436]
We need a waypoint that describes how to setup your ClementineJS App on Heroku and deploy.

From the current "Getting Set for Basejumps" Waypoint:
>We will soon add instructions for getting Clementine running on Heroku. For now, develop your Basejumps right on c9.io.

**Comment by danilobarion1986** [comment]
Sorry, I can't locate the Waypoint that you've mentioned. Is it necessary yet? What is the current Waypoint that have this statement about deploying ClementineJS on Heroku?

**Comment by atjonathan** [comment]
@danilobarion1986 https://www.freecodecamp.com/challenges/get-set-for-our-dynamic-web-application-projects and https://www.freecodecamp.com/challenges/get-set-for-our-api-development-projects on the last slides :smile:

**Comment by danilobarion1986** [comment]
Thank you @atjonathan! I want to help create this instructions. But I don't know how to create a page like that, with the gifs and instructions, and so on. Do you know how can I create it?

**Comment by atjonathan** [comment]
@cc/ @FreeCodeCamp/issue-moderators, do we want to implement this waypoint yet?
@danilobarion1986, hold a second while I check if we wanna go ahead with this :smiley:

**Comment by atjonathan** [comment]
Closing as we are moving to using HyperDev.

**Comment by danilobarion1986** [comment]
Thank you for reply! Great choice switch to HyperDev :+1:
