### ISSUE TITLE
Add additional navigation to Step Challenges

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4437]
The GIF Style challenges are great for short introductions, but more challenging for longer content, like "Get Set for Basejumps" there are several improvements that would make them easier to use:

- [x] **Enable "Previous" button on final screen**  
Right now there is no "Previous" button on the "Finish Challenge" screen.  If I accidentally double-clicked or wanted to go back, I should be able to go back from the final slide.

- [x] **Add (Step X of Y) somewhere on the screen**  
It would be helpful to be able to see how many steps there are and how many are to go.  As I am clicking through the "Get Set for BaseJumps" set, it seems interminable and there is no clear end in sight.

- [ ] **Add sidebar navigation**  
This would require giving each slide a title, but would make it significantly easier to go back and forth between slides if you missed something or just want to review. On first view, unvisited slides could be grayed out until visited.  This would also reinforce (or possibly replace) 1 above.

- [ ] **Add navigable anchors and `windows.history` entries for each slide**  
This would make it possible to link to a specific slide, ties into the navigation above.
Examples `#slide1`,  `#slide-title-slug-here`, or `#slideX-title-here`

- [x]   **Disable force "Click To Open" if Waypoint has been previously completed**  
I shouldn't be forced to click to open another window if I've completed the challenge.  If I'm just looking for a specific piece of information (especially in longer step challenges), it's a drag to have to open all those windows.

**Comment by ltegman** [comment]
Checking off two of these via @SaintPeter's PR #4467

**Comment by BerkeleyTrue** [comment]
> Disable force "Click To Open" if Waypoint has been previously completed

Is this a valid concern? How often does someone need to repeat a step challenge?

**Comment by SaintPeter** [comment]
A key use of the step challenges are as "how to" type instructions.  If you need to go back to review these instructions at all - for example the c9 setup instructions - you have to click every single "click to open" in order to get back to a specific step.

These instructions and links are not available elsewhere.  Having recently tried to step through several of these, the requirement that you click again is a huge pain.

What I have not yet investigated is how visible the completion status of a given challenge is to the client.  That was my next investigation.

**Comment by BerkeleyTrue** [comment]
@SaintPeter fair enough. I think there is another issue open to add a "skip" step button which would do the same thing.

Some challenges should not be skippable as well (earn front end/full stack cert step challenges).

**Comment by SaintPeter** [comment]
Click to open closed by #5121

**Comment by bugron** [comment]
@SaintPeter do we still need those two or they are just nice to have (meaning we can close this issue)?

**Comment by BerkeleyTrue** [comment]
While those last two are nice features, they don't really bring a lot of value to users and would clutter a clean and simple UI.

Happy Coding!

**Comment by SaintPeter** [comment]
Yeah, I agree with Berkeley - I think the X of Y is probably enough, especially now that we can skip "required" steps once we've already completed them.
