### ISSUE TITLE
Create a Linked List Class - Problem with test

### ISSUE THREAD

**Issue by MattDClarke** [freeCodeCamp/freeCodeCamp#44389]
## Affected page
[Create a Linked List Class](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-linked-list-class)

## Your code

Code from the [freeCodeCamp Challenge guide solution](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-create-a-linked-list-class/301628):
```js
 this.add = element => {
    const node = new Node(element);
    if (head) {
      let current = head;
      while (current.next !== null) {
        current = current.next;
      }
      current.next = node;
    }
    else {
      head = node;
    }
    length++;
  };

```

## Expected behavior

If the while loop is removed from the [solution code](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-create-a-linked-list-class/301628), the following [test](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/data-structures/create-a-linked-list-class.md) should fail (if 3 or more items added), but it does not:

> The previous `node` in your `LinkedList` class should have reference to the newest node created
```js
assert(
  (function () {
    var test = new LinkedList();
    test.add('cat');
    test.add('dog');
    return test.head().next.element === 'dog';
  })()
);
```

## System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 96

## Additional context

The [test](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/data-structures/create-a-linked-list-class.md) is only testing with 2 items added to a linked list. 

The test should fail if a third item is added and the while loop is removed from the [solution code](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-create-a-linked-list-class/301628) because the third item would would be added to the linked list, but it would orphan the second item. 

My suggestion for an improved test:
``` diff
assert(
  (function () {
    var test = new LinkedList();
    test.add('cat');
    test.add('dog');
+ test.add('fish');
    return test.head().next.element === 'dog';
  })()

```

**Comment by ColinSidberry** [comment]
Can I take this one?
