### ISSUE TITLE
Typo in sample code in Waypoint Update the Properties of JS Object

### ISSUE THREAD

**Issue by sylvalynn** [FreeCodeCamp/FreeCodeCamp#4438]
Challenge [Waypoint: Update the Properties of a JavaScript Object](http://www.freecodecamp.com/challenges/waypoint-update-the-properties-of-a-javascript-object) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the instructions, tails has two commas! Oh dear! 

See below:
  "tails": 1,,

**Comment by alvynmcq** [comment]
I have created a pull request for this
