### ISSUE TITLE
Broken Link on-  A fast new way to find people in your city to code with page

### ISSUE THREAD

**Issue by sumitdadwal** [freeCodeCamp/freeCodeCamp#44395]
I have recently found a broken link in this article on freecodecamp:
A fast new way to find people in your city to code with

the line where link is located is:

> Introducing our **new study group directory**.

The link should lead to this URL:
https://study-group-directory.freecodecamp.org/

But instead it is leading to: 
https://www.freecodecamp.org/study-group-directory 

Which is showing 404 error.

screenshot
![freecodecamp](https://user-images.githubusercontent.com/84678969/144854925-d70bc938-c4fa-478f-b423-28adb46754d0.PNG)
:

**Comment by gikf** [comment]
Could you confirm that's this article? https://www.freecodecamp.org/news/the-fastest-way-to-find-people-in-your-city-to-code-with-c71c956456c8/

Link I'm seeing there is the one first one - https://study-group-directory.freecodecamp.org/

**Comment by sumitdadwal** [comment]
I already informed it to the editorial team and they fixed it. Sorry I did not close the issue.

**Comment by sumitdadwal** [comment]
fcv
