### ISSUE TITLE
Add step to basejump setups for SSH key

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#444]
for step 38 here: 
http://www.freecodecamp.com/challenges/get-set-for-basejumps

the new user needs to set up an SSH key to push to github.  the key is given by C9, but it's not clear to me how to add it to github, a simple copy /paste to my SSH keys in my account isn't working. 

This should be clarified for new users of c9.  Not sure if it's needed for every c9 workspace or just once, but I guess github is seeing c9 as a new computer?

**Comment by AdventureBear** [comment]
Here is a set of instructions that worked for me: 

http://lepidllama.net/blog/how-to-push-an-existing-cloud9-project-to-github/
In the bottom left of your C9 dashboard is a section called “Add-on Services”. Click “activate” next to the “GitHub” icon (if you haven’t already).
When the pop up appears, tell it to allow access to your account. This should complete the link between GitHub account and your C9 account.
While still on the dashboard, look to the right under “Account Settings” for the link “Show your SSH key”. Click on it, and copy the value which appears.
Go to the GitHub SSH settings page, and click “Add SSH Key”
Enter the title “C9″, paste the SSH Key into the “Key” box, and click “Add Key”.

**Comment by QuincyLarson** [comment]
Excellent. Thank you for pointing this out. I'll add this.
