### ISSUE TITLE
Set up Passport challenge: Allow for space after "secret" key in object

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#44400]
The current regex will fail with this code.

`secret : process.env.SESSION_SECRET`

Forum: https://forum.freecodecamp.org/t/set-up-passport-session-and-session-secret-should-be-correctly-set-up/487881

Challenge: https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/set-up-passport

Tests: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/set-up-passport.md

**Comment by justinrobinson1020** [comment]
I would like to work on this issue
