### ISSUE TITLE
FAQ about community leadership

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#44408]
We want to encourage offering help as a leader within the community and document something in the FAQ of our contributing docs. 

The idea is to point interested people in the right direction, whereby they can offer meaningful help and establish their credibility over a period of time. This should essentially help them in becoming a member of our awesome @freeCodeCamp/moderators team.

Please see more context in https://github.com/freeCodeCamp/freeCodeCamp/pull/44399#discussion_r764152816

**Comment by nhcarrigan** [comment]
Ideally, I'd like to have an outline for each of our platforms, i.e. Forum, Chat/Discord, GitHub.

**Comment by raisedadead** [comment]
Thanks, @nhcarrigan - I agree on an outline for each of the platforms is useful.

Side note: Here is some recommendation from Ariel in the earlier discussion:

> So maybe more of some suggestions on how best to offer help and leadership? Things like tips on how to answer questions effectively, when to flag posts for moderation, using encouraging/supportive language, cross-cultural communication, avoiding online drama...
> Maybe an external News article that could be linked in a 'so you wanna moderate' section?

For anyone interested in working on this we are welcoming proposals on the verbiage for the FAQ. We would love to hear and add the outline based on first-hand feedback from community leaders & contributors such as you.

**Comment by raisedadead** [comment]
And just to kick off the thought process, the idea is to have a FAQ that reads like so (or along the lines of):

--

### I am interested in being a moderator at freeCodeCamp. Where do I start?

Our community moderators are our heroes. Their voluntary contributions make freeCodeCamp a safe and welcoming community.

First and foremost we would need you to be an active participant in the community, and live by our code of conduct (not just help enforce it). 

Here are some recommended paths for some of our platforms:

- ... _do this_ on Discord, and so on.
- ... _do this_ on GitHub, and so on.


If you practice the above **consistently for a while** and our fellow moderator members recommend you, a staff member will reach out and onboard you to the moderators' team.
