### ISSUE TITLE
Waypoint Override Class (Wrong code, right answer)

### ISSUE THREAD

**Issue by NobisPete** [FreeCodeCamp/FreeCodeCamp#4444]
Some of the instructions were "Your h1 element should be orange."....As you can see, my h1 was green.
I ran the tests and it said I passed the waypoint.
If you click the link you may see the code submitted, and the green h1, and my passing score.

[link:](http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-by-styling-id-attributes?solution=%3Cstyle%3E%0A%20%20body%20{%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20}%0A%20%20%23orange-text%20{%0A%0A%20%20color%3A%20orange%3B%0A%20%20.pink-text%20{%0A%20%20%20%20color%3A%20pink%3B%0A%20%20}%0A%20%20.blue-text%20{%0A%20%20%20%20color%3A%20blue%3B%0A%20%20}%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%3E%0A%3Ch1%20class%3D%22pink-text%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A)
![firefox_screenshot_2015-11-15t04-40-59 136z](https://cloud.githubusercontent.com/assets/11945928/11167271/3dfa9302-8b10-11e5-9aff-79ca515e6a7c.png)

**Comment by SaintPeter** [comment]
There are nearly an infinite number of ways to be wrong in an exercise, but only a finite number of ways to test for correctness.  It is definitely possible to subvert many of our test cases or, in the case of Bonfires, to "code to the test", that are almost impossible to catch.

In this specific case, there are a number of significant errors and changes that have been made to the code, some of which are highlighted by the editor itself:
![image](https://cloud.githubusercontent.com/assets/553494/11167959/53a2985c-8b2f-11e5-81f9-9584b357432b.png)

1. `pink-text` is "defined" inside the prior class and is invalid and highlighted as such by the editor
2. Ditto for `.blue-text`
3. A second, empty `h1` tag has been added.  This is actually correctly orange, if it had text in it.

I'm at a loss as to how we could reasonably detect these sorts of errors.

I guess my question to you is:
Seeing all of these things, and knowing that your text was not, in fact, orange, did you attempt to correct the errors or just continue on?  We can't force you to fix them, and if you don't have the desire to do them correctly there is no force on earth that can compel you.

What do you propose we do?

**Comment by bugron** [comment]
Closing this issue. @NobisPete try following the instructions when going through the curriculum. Feel free to reopen if you still experience problems.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.
