### ISSUE TITLE
Unusual comma characters

### ISSUE THREAD

**Issue by joshuaadamhenderson** [freeCodeCamp/freeCodeCamp#44449]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
Some commas that haven't been there before have appeared under the output for certain tutorials recently. On the Bootstrap tutorial, one comma appears at the top of the output window, and during React tutorials, two commas appear at the top of the output window. This is not necessarily a bug, just something I noticed. On the page source, they are appearing shortly after the <body> tag and before the first <script> tags.

**To Reproduce**
1. Go to "Front-End Development Libraries"
2. Click on "Bootstrap" or "React"
3. See error at the top of output window.

**Expected behavior**
No commas to appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Browser: Firefox, Chrome
 - Version: Most Recent

**Smartphone (please complete the following information):**
 - Device: Samsung s10e
 - OS: Android
 - Browser: Chrome
 - Version: Most Recent

**Additional context**

**Comment by joshuaadamhenderson** [comment]
![ss2](https://user-images.githubusercontent.com/47343175/145503576-ae6c44fd-4594-4896-ae14-cf7ad692c5c9.jpg)
![ss1](https://user-images.githubusercontent.com/47343175/145503580-e1f5f39d-0684-445f-836b-5d810c9ea89c.jpg)
![ss3](https://user-images.githubusercontent.com/47343175/145503582-90a0e9e6-db40-40e7-8424-63c4500a3242.jpg)

**Comment by gikf** [comment]
Issue seems to appear first in https://github.com/freeCodeCamp/freeCodeCamp/commit/86cc7579452e5975567529a4c254445d51ace167

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to report this.

As correctly pointed out above, the `heads` variable is an array, but it is being input directly into the template literal on line `110`.

This should be a simple fix.

An issue with the _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by JakobBanes** [comment]
Hi, I'm fairly new to github. I'm reading over contribution guidelines and will try to make a PR tonight.
