### ISSUE TITLE
unclear code instructions 

### ISSUE THREAD

**Issue by shayaneshwar** [freeCodeCamp/freeCodeCamp#44469]
## Your code

```
https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/give-links-meaning-by-using-descriptive-link-text
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-give-links-meaning-by-using-descriptive-link-text/301013



```

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by raisedadead** [comment]
Hi,

Thanks for this report. 

I recommend you first create a post on the forum with succinct details of the issue that you are facing. If others facing the same someone will surely guide you to report it as a bug here on GitHub.

As is we are going to have to close this.

Happy Coding.
