### ISSUE TITLE
create-new-middleware   challenges， about pug   set code，can   more simple

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#44468]
## Affected page
https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/create-new-middleware

## Your code
```
app.set('view engine', 'pug');
app.set('views', './views/pug')
```
it set pug as view engine, and   set  Express look for your templates in  './views/pug' 

so   the code 
```
app
 .route('/profile')
 .get(ensureAuthenticated, (req,res) => {
    res.render(process.cwd() + '/views/pug/profile');
 });
``` 
can write into
```
app
 .route('/profile')
 .get(ensureAuthenticated, (req,res) => {
    res.render('profile');
 });
```

**Comment by raisedadead** [comment]
Hey there, 

We understand you are having trouble with this challenge, could elaborate a bit more on this? It's unclear to us the exact issue you are facing. 

Apologies in advance, if you did mean to post the issue report in the English version of the challenge, but we also have a Chinese language forum and this same challenge translated in Chinese here if that might help:

- https://chinese.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/create-new-middleware
- https://chinese.freecodecamp.org/forum/

Thanks.

cc @miyaliu666

**Comment by luojiyin1987** [comment]
I  pass the challenge,   but I want write  more  clear code    @raisedadead

**Comment by raisedadead** [comment]
Thanks for confirming. 

I would recommend you to post this on the forum for help with your solution to the challenge. This issue tracker is not for coding help, we are using it to only track bugs on the learning platform.

Happy coding!

**Comment by luojiyin1987** [comment]
ok

**Comment by miyaliu666** [comment]
I just met with @luojiyin1987 during the Chinese contributors meeting. He meant the code in the challenge could be improved. Could you check the challenge and confirm if it's necessary? Thanks! @raisedadead

**Comment by raisedadead** [comment]
While in practice the code that the OP shared is better, this challenge's scope (and for that matter any challenge on freeCodeCamp) is not to teach best practice while teaching a concept. 

The idea is to limit the scope of the lesson to get the concept across without too many abstractions. 

IMHO, the code in the current lesson eliminates the need for teaching setting options which are covered elsewhere. I don't think we need to update the challenge.
