### ISSUE TITLE
"Expand courses" and "Collapse courses" cannot be displayed correctly in Japanese

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#44476]
In the screenshot below, "Expand courses" and "Collapse courses" are displayed by combining 3 strings `Expand` `Collapse` and `Courses` taken from `/client/i18n/locales/english/intro.json`

Can we change the translatable strings to `Expand courses` and `Collapse courses` ?
Not `Expand` + `Courses` and `Collapse` + `Courses` .

It is difficult to translate them correctly into a language with different grammar rules, such as Japanese. Refer to "Additional context" below for detailed explanation.

![image](https://user-images.githubusercontent.com/25644062/145681327-9e95d250-5879-451a-afa6-8d28b29717ec.png)

## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/ (and all other certifications)

## To reproduce

1. Visit the above URL

## Expected behavior

"Expand courses" and "Collapse courses" can be displayed correctly in languages with different grammar rules.

## Screenshots

See above

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 96.0.4664.93

## Additional context

The problem is caused by grammatical differences between English and Japanese (and possibly other languages).

In Japanese, the words correspond as follows:
"Expand" -> "展開"
"Collapse" -> "閉じる"
"Courses" -> "コース"

But when saying "Expand courses" or "Collapse courses", they should be like:
"Expand courses" -> "コースを展開"
"Collapse courses" -> "コースを閉じる"

Notice that:
- The order of words is different. The word for "Courses" comes first.
- We need a connecting word "を"

They are displayed incorrectly like this with current implementation. (tested in my local)
![image](https://user-images.githubusercontent.com/25644062/145681385-42237c7c-837c-4f35-ae63-e7c94592705f.png)

**Comment by ieahleen** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by PrashantSakre** [comment]
Hi team, Do I have to change all intro.json files with there respective languages ? Or is handled through Crowdin translation ?
