### ISSUE TITLE
the "Get a Hint"  info is no use, in   "registration-of-new-users" challenges

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#44470]
## Affected page

https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/registration-of-new-users

click "Get a Hint" button   will to url 
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-registration-of-new-users/301561

but hint info is no use,   I change it ,but I can not pass challenges

at the end  I write  is to pass challenges
```
  app.route('/register')
    .post((req, res, next) => {
    myDataBase.findOne({ username: req.body.username }, function(err, user) {
        const  hash =  bcrypt.hashSync(req.body.password, 12);
        if (err) {
          next(err);
        } else if (user) {
          res.redirect('/');
        } else {
          myDataBase.insertOne({
            username: req.body.username,
            password: hash
          },
            (err, doc) => {
              if (err) {
                res.redirect('/');
              } else {
                // The inserted document is held within
                // the ops property of the doc
                next(null, doc.ops[0]);
              }
            }
          )
        }
      })
    },
      passport.authenticate('local', { failureRedirect: '/' }),
      (req, res, next) => {
        res.redirect('/profile');
      }
    );
```

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by luojiyin1987** [comment]
ok

**Comment by miyaliu666** [comment]
@luojiyin1987 passed this challenge, and he meant the hint was not helpful. Anyone wants to check the hint? Thanks!

**Comment by ieahleen** [comment]
@miyaliu666 the hints are a forum post, to suggest changes to the guild you can open a thread in the forum

**Comment by raisedadead** [comment]
To elaborate what @ieahleen mentioned:

- Challenge hints are a helping tool. They are normally posted on the forum and updated when needed with help of the community moderators and contributors. These are not a bug per se, in the curriculum or the codebase.
- We are keeping this tracker to keep the discussions & threads for issues/bugs in codebase only. I think it's best to post on the forum first when stuck, or if you find something unuseful. Someone from the mod team can confirm the course of action whether it's a bug and needs reporting here or can be addressed in the discussions on the forum.

Thanks again for your reports and feedback.

**Comment by miyaliu666** [comment]
@raisedadead @ieahleen Thanks for the details. I've told @luojiyin1987 to report on the English forum.
