### ISSUE TITLE
Request for star when new tests are added

### ISSUE THREAD

**Issue by ArgonCode** [FreeCodeCamp/FreeCodeCamp#4447]
Sometimes tests are added to bonefires and my solution did not take them into account. Sometimes it is still OK, but not always. When I go back (for diff reasons) I see it no longer works. It would be cool to have some indication when new coverage was added to bonefires. So I can go back and see if my solution is working or if I missed sth.

**Comment by SaintPeter** [comment]
All of the curriculum on the site is undergoing constant improvement.  If you just take a look at the closed pull requests for the last week, you'll be amazed.  The fact of the matter is that there are simply too many changes of varying levels of triviality to reasonably track.  So long as you have passed it once, at some given time, that's good enough for us.

Now, we are considering adding some sort of "Updated" flag when there is a significant rewrite of the content, but that has not been confirmed yet.

I'm going to close this as "won't fix". 

Happy Coding!
