### ISSUE TITLE
Add a test bypass mode in development

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#44488]
Testing challenges in development can be tough. I propose a `TEST_BYPASS_MODE` we can use in development to make the challenges always pass the tests.

**Comment by ShaunSHamilton** [comment]
Are you proposing just a flag to ignore all tests? Or, the ability to submit without passing?

Or, something more like `AUTOMATICALLY_ADD_EXPECTED_SOLUTION_MODE`?

**Comment by moT01** [comment]
Either way would work. Ignore the tests was what I had in mind and would probably quite easy to implement.
