### ISSUE TITLE
DX: hot-reloading challenges is broken.

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#44514]
## Affected page

All challenges in development.

## To reproduce

1. `npm run develop` in terminal
1. Go to localhost:8000/learn/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements
2. Open curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/say-hello-to-html-elements.md in your editor
3. Change some text below --description--
4. See error in terminal
5. Do not see expected changes to the page

## Expected behavior

It should be possible to see changes in the development client without stopping and restarting `npm run develop`

## Additional context

This was caused by https://github.com/freeCodeCamp/freeCodeCamp/pull/44499

specifically the change to
(https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/plugins/fcc-source-challenges/create-challenge-nodes.js#L57)

The solution is *probably* to create a map between filename paths and the UUID that's generated for each path, but there might be a better approach.

**Comment by moT01** [comment]
I was having issues with the hot reloading when trying to review the last practice project. Dug into it a little - I used a combo of the block and dashed name of the challenge for the gatsby id: ``{ id: `${challenge.block}-${challenge.dashedName}` }`` - no issues that I noticed. Might be one way to go that would probably work.

**Comment by ojeytonwilliams** [comment]
Good thinking! It would need to be something that's definitely unique, though. A sub-path like `responsive-web-design/basic-html-and-html5/say-hello-to-html-elements` would be guaranteed to be unique.
