### ISSUE TITLE
Server crashes frequently

### ISSUE THREAD

**Issue by Waqasahmad145** [freeCodeCamp/freeCodeCamp#44526]
The server is crashing frequently while accessing the javascript course, by refreshing the page it stucks in a loop of loading bars not enabling me to enter my profile. It would be really helpful for me if resolved. Thank you.

**Comment by ShaunSHamilton** [comment]
Hello there,

Would you be able to provide more information? We are unaware of any issue with the platform, and I am unable to produce such issue.

1) What browser and version are you using? (we suggest the latest version of Chrome)
2) Do you have any browser extensions with access to `freecodecamp.org`? (we suggest disabling all extensions)
3) What OS are you using?

**Comment by Waqasahmad145** [comment]
1. Chrome (lasted version)
2. None
3. Windows

Thank you for considering.

**Comment by Waqasahmad145** [comment]
It seems to be with javascript course only I assume. Firstly, once I run the tests for my challenge, it prompts me to submit and move to the next challenge but it crashes and becomes unresponsive. After that, when I refresh the page, it logs me out and loading bars are on a loop. After 2 to 3 mins it lets me in, one challenge later, all happens again.

**Comment by IbrahimSaffi** [comment]
It is happening to me too for last two days. Now I have enabled VPN and it is working fine. So it could be location based issue. If issue repeats under VPN I will comment here.

**Comment by Waqasahmad145** [comment]
Thank you for considering. Working fine with VPN.
