### ISSUE TITLE
Index Pages for Blocks

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#44546]
Currently, we have pages such as [/basic-html-and-html5/](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/) coming from: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/pages/learn/responsive-web-design/basic-html-and-html5/index.md

Re: https://github.com/freeCodeCamp/freeCodeCamp/pull/44545

Do we want to keep all the old pages around, as well as add new pages?

I think we discussed removing them before (because there are no links to these pages), but there were SEO concerns - the pages are useful for SEO.

**Comment by MadhaviMandalia** [comment]
Hello @ShaunSHamilton 
So should we keep this pages or remove them? let me know how can I be helpful with this.

Thanks.

**Comment by ShaunSHamilton** [comment]
@MadhaviMandalia Thank you, for your interest in contributing. This issue is not open for contribution, because we still need to discuss:

> Do we want to keep all the old pages around, as well as add new pages?

Once a decision has been made for an issue, the `help wanted` or `first timers only` labels are added, and then it is open for contribution.

**Comment by MadhaviMandalia** [comment]
Ok. @ShaunSHamilton Thanks

**Comment by moT01** [comment]
I think for now, we want to keep these - I'm quite sure I've heard us say we are going keep them. So I think it's safe to close this. If anyone thinks I'm wrong, feel free to leave a comment and it can be reopened. Thanks and happy coding 🎉
