### ISSUE TITLE
hi, as per the result, all the values that are greater than 5 have been removed, still I am getting an error saying that all the values should have been removed.

### ISSUE THREAD

**Issue by JatinSethi** [FreeCodeCamp/FreeCodeCamp#4454]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AoldArray%20%3D%20oldArray.filter(function(val)%7Breturn%20val%3E5%3B%7D)%3B%0Avar%20newArray%20%3D%20oldArray%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7B%20return%20newArray%3B%20%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.
oldArray = oldArray.filter(function(val){return val>5;});
var newArray = oldArray;

// Only change code above this line.

(function() { return newArray; })();

```

**Comment by faizaanceg** [comment]
Hmm

> The filter method is used to iterate through an array and **filter out** elements where a given condition is **not** true.

So when you call`.filter` on an array and pass a function which returns `true` or `false`, the `filter` retains only those elements for which the function returned `true`.

The question is,
> Use filter to **remove all elements** from array that are **greater than 5**.

To remove the elements that are greater than 5, you need to pass a function that returns **true** if an element is less than or equal to 5. In other words, it returns `false` if number is greater than 5.

So the correct code in this case would be,

```
oldArray = oldArray.filter(function(val){ 
                      return val <= 5; 
                  });
```

Hope the doubt is clarified.


Please use the [Gitter chatroom](https://gitter.im/FreeCodeCamp/FreeCodeCamp) for coding related queries!

**Comment by JatinSethi** [comment]
yes thank you, Mis-read the question itself!
