### ISSUE TITLE
New jQuery Waypoint: Modifying Html

### ISSUE THREAD

**Issue by fraziern** [FreeCodeCamp/FreeCodeCamp#4457]
I think it would be useful preparation for the pomodoro and calculator projects to introduce .html() and .text() in the jQuery waypoint section

**Comment by fraziern** [comment]
Working on this.

**Comment by SaintPeter** [comment]
Good idea.  You're working on new waypoints?

**Comment by fraziern** [comment]
That's the goal, anyways :)

**Comment by SaintPeter** [comment]
Awesome, can't wait to see your PR.  Don't hesitate to contact me if you have questions about the process of building a waypoint.  One important note:  You must use MongoDB to generate a new ObjectID for the ID of your new waypoint.
