### ISSUE TITLE
Missing possible edge cases in Sorted Union challenge

### ISSUE THREAD

**Issue by MarkPinto** [freeCodeCamp/freeCodeCamp#44588]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sorted-union

## Your code

```

function uniteUnique(arr) 
{ 
  //new array, made to make a copy of arguments to follow functional programming practices
  let narr = [];

  //make a copy of all argments and push into narr
  for(let i = 0;i<arguments.length;i++)
  {
    narr.push(arguments[i]);
  }

  //filters out duplicates contained in
  for(let i=1;i<narr.length;i++)
  {
    narr[i] = narr[i].filter(a => !narr[0].includes(a));
  }

  //combines all arrays together
  for(let i = 1;i<narr.length;i++)
  {
    narr[0] = narr[0].concat(narr[i]);
  }

  return narr[0];
}

console.log(uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]));


```

## Expected behavior

The code above should not pass the challenge however it does. For example uniteUnique([1, 3, 2, 3], [5, 2, 1, 4], [2, 1]) returns [ 1, 3, 2, 3, 5, 4 ]. [ 1, 3, 2, 3, 5, 4 ] has two 3s in it but it still pass the checks for the challenges despite not meeting the requirement of only having unique values in the final array. This edge case has duplicate elements in the first array of arguments.

Another example where my code should fail the challenge is when other arrays have duplicates with each other in arguments but not the first array. uniteUnique([1, 3, 2], [5, 4], [5, 6]) returns [ 1, 3, 2, 5, 4, 5, 6 ], which again has duplicate elements yet it still passes the challenge.

To conclude their should 2 edge cases added to make sure the challenge is passed
1. An edge case that has the first array in arguments have duplicate elements such as uniteUnique([1, 3, 2, 3], [5, 2, 1, 4], [2, 1])
2. An edge case where duplicates are found between arrays but not with the first array in arguments such as uniteUnique([1, 3, 2], [5, 4], [5, 6])

## Screenshots

![Screenshot 2021-12-24 091331](https://user-images.githubusercontent.com/17538608/147358399-27b86e11-0c55-4c22-a4b5-2fd4950711a2.png)

![Screenshot 2021-12-24 091412](https://user-images.githubusercontent.com/17538608/147358407-a7a3d873-235a-4875-902b-dbfbefa1021c.png)

## System

- Device: Desktop
- OS: Windows 11
- Browser: Firefox
- Version: 95.0.2

## Additional context

I see this an issue because I missed it myself originally and almost went to the next problem thinking I learned how to actually solve the issue. It wasn't until I took a look at my code to clean it up that I noticed the two edge cases that would make my code not meet the requirements of the challenge yet still pass the challenge.

**Comment by marsonya** [comment]
I would like to help with this issue.

**Comment by ieahleen** [comment]
Note: for anyone willing to take on this issue, you may need to adjust the solution function

---

@marsonya 
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
