### ISSUE TITLE
Bonfire: Where do I belong? Second example in instructions is incorrect.

### ISSUE THREAD

**Issue by UsernameWasTaken** [FreeCodeCamp/FreeCodeCamp#4458]
Challenge [Bonfire: Where do I belong](http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20return%20num%3B%0A%7D%0A%0Awhere(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the instructions for this exercise the second example reads, "Likewise, where([20,3,5], 19) should return 2 because it is less than 20 (index 2) and greater than 5 (index 1)." Based on the example result given, the example array should be [3,5,20].

**Comment by UsernameWasTaken** [comment]
After completing this exercise, I realized that the second example may not be a typo as the exercise requires the use of the sort() method to sort the given arrays in a numerically ascending order. So, rather than a typo, this example may just be confusing to those who have not completed the exercise.

**Comment by SaintPeter** [comment]
It might make sense to add a clarifying statement like:
>Likewise, where([20,3,5], 19) should return 2 because (once the array has been sorted) it is less than 20 (index 2) and greater than 5 (index 1).
