### ISSUE TITLE
Broken CSS property tests in new RWD certification when using Firefox

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#44593]
## Affected page

There are multiple pages affected. I will use [step 25](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-25) in the Learn Accessibility by Building a Quiz course as an example.

When using Firefox, the code check is erroneously failing for `border: 0`. The current assert for this test is

```
assert.equal(new __helpers.CSSHelp(document).getStyle('.sr-only')?.border, '0px');
```

Chrome-based browsers do return `0px` when `border` is set to `0` but Firefox is returning `0px none` and thus the assert is failing.

## Your code

The following assert fixes this issue and allows the border test to pass for both Chrome and Firefox.

```
assert.include(['0px', '0px none'], new __helpers.CSSHelp(document).getStyle('.sr-only')?.border);
```

## System

- Device: Desktop
- OS: Linux/Fedora 34
- Browser: Firefox
- Version: 95.0

## Additional context

I am going through the entire accessibility course and finding/fixing all of these Firefox-specific issues and will open a PR. Should I do a separate PR for each step that needs fixing or one PR that includes all of the fixed steps in the accessibility course?

**Comment by gikf** [comment]
Thanks for opening this issue.

As this sounds like a single issue type affecting multiple steps, one PR with multiple steps fixed seems right.

**Comment by bbsmooth** [comment]
I found/fixed three firefox-specific issues in the learn-accessibility-by-building-a-quiz course and have submitted a PR for them. This issue wasn't necessarily specific to just that course. I'm assuming there are other courses in the new beta that will also have this problem. I'm happy to start going through them as well. Do we want to keep this issue open as an umbrella issue for all of the courses in the beta or should I create a separate issue for each course I find problems in?

**Comment by najmieh** [comment]
> I found/fixed three firefox-specific issues in the learn-accessibility-by-building-a-quiz course and have submitted a PR for them. This issue wasn't necessarily specific to just that course. I'm assuming there are other courses in the new beta that will also have this problem. I'm happy to start going through them as well. Do we want to keep this issue open as an umbrella issue for all of the courses in the beta or should I create a separate issue for each course I find problems in?

Kinda a PR Collision! I can update mine for all the issues. Please let me know if I can do an update for this https://github.com/freeCodeCamp/freeCodeCamp/pull/44597 ?

**Comment by bbsmooth** [comment]
Since I have all three fixes in my PR, would it not be more convenient to just leave mine and remove yours?

**Comment by najmieh** [comment]
> Since I have all three fixes in my PR, would it not be more convenient to just leave mine and remove yours?

Sure. 100% agreed :)

**Comment by gikf** [comment]
> I found/fixed three firefox-specific issues in the learn-accessibility-by-building-a-quiz course and have submitted a PR for them. This issue wasn't necessarily specific to just that course. I'm assuming there are other courses in the new beta that will also have this problem. I'm happy to start going through them as well. Do we want to keep this issue open as an umbrella issue for all of the courses in the beta or should I create a separate issue for each course I find problems in?

I think this issue can be used for that for now.

**Comment by lasjorg** [comment]
Seems related

https://forum.freecodecamp.org/t/can-someone-help-me-on-this-please/490861
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-28


---

@bbsmooth does switching `equal` to `include` not work without the array? As far as I can tell it is looking for substrings.

> Docs [include](https://www.chaijs.com/api/assert/#method_include)
> 
> `assert.include('foobar', 'foo', 'string contains substring');`

So it seems like the needle `0px` should match the haystack `0px none` (didn't test it).

`assert.include('0px none', '0px', 'might work I'm thinking');`

If so, it would at least make doing a find and replace a bit easier.

---

Do we know if this affects other properties besides `border`?

**Comment by gikf** [comment]
Another affected property is `background`.

I mentioned this in related PR, tests could target more precisely the desired property. For example, when set should be `border: 0;`, check in test value of `borderWidth`, rather than the general `border`.

**Comment by xoxoKaralee** [comment]
> Another affected property is `background`.
> 
> I mentioned this in related PR, tests could target more precisely the desired property. For example, when set should be `border: 0;`, check in test value of `borderWidth`, rather than the general `border`.

Safari also has issues with background. [Here ](https://forum.freecodecamp.org/t/rwd-beta-colored-markers-need-help-or-to-verify-bug/490422/10) is my forum post about it. Not sure if this is related or not. It passed in chrome, but not on Safari.

**Comment by ShaunSHamilton** [comment]
Thank you, for bringing this up. We have multiple tests following the `assert.include` pattern specifically because Firefox appears to be "the odd one out".

However, as you did in one PR, Bruce, perhaps we are just better testing - wherever we can - for the specific "sub-property" - like @gikf suggested.

This would not be feasible for some tests/lessons where we ask/expect Campers to use the long-hand vs short-hand property, but anywhere else, we could probably just go with the shorthand.

**Comment by gikf** [comment]
I've looked for cases where shorthand `border` or `background` are checked (`.*(\.border[^\w\-]|\.background[^\w\-])`) and tried them on Firefox. Found just one step left, not passing because of it.
