### ISSUE TITLE
Set the font-size for Multiple Heading Elements challenge not working

### ISSUE THREAD

**Issue by hacksanuj** [freeCodeCamp/freeCodeCamp#44591]
## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements

## Your code

```
<style>
  h1 {
    font-size: 68px;
  }
  h2 {
    font-size: 52px;
  }
  h3 {
    font-size: 40px;
  }
  h4 {
    font-size: 32px;
  }
  h5 {
    font-size: 21px;
  }
  h6 {
    font-size: 14px;
  }
</style>
<h1>This is h1 text</h1>
<h2>This is h2 text</h2>
<h3>This is h3 text</h3>
<h4>This is h4 text</h4>
<h5>This is h5 text</h5>
<h6>This is h6 text</h6>



```

## Expected behavior

I have tried all the possible solution for this challenge, but it's not working. I have even tried the official solution, but it's not working. Only the h1 tag is working correctly and getting correct. The other tags from h2-h6 are not working. Even the browser on the challenge is showing that the code is working. But it's not accepting the answer.

## Screenshots

![screencapture-freecodecamp-org-learn-responsive-web-design-applied-visual-design-set-the-font-size-for-multiple-heading-elements-2021-12-27-06_18_58](https://user-images.githubusercontent.com/60060877/147424076-47d61c69-a72f-443c-92fb-e466221ee8ee.png)

## System

- Device: Laptop
- OS: Windows 11
- Browser: Brave
- Version: 1.33.106

**Comment by jdwilkin4** [comment]
HI @hacksanuj ! 

The code you have shared works on my end. Please ensure that you have disabled any extensions that interface with the freeCodeCamp website (such as Dark Mode and Ad Blocker), and set your browser zoom level to 100%. Both of these factors can cause tests to fail erroneously.

You can also try another browser without extensions.
I ran the tests on google chrome without extensions and your code is passing for me.

If you have further issues, we can continue the discussion in your open [forum post](https://forum.freecodecamp.org/t/please-someone-help-i-am-not-able-to-clear-this-challenge-wvwn-though-my-solution-is-correct/490076)

Thanks!

**Comment by hacksanuj** [comment]
Thanks, It's working now.
Although it was not working in brave browser, so I installed Firefox, and it worked there.
