### ISSUE TITLE
RWD Beta, Create Cafe Menu, Cinnamon is spelled wrong.

### ISSUE THREAD

**Issue by xoxoKaralee** [freeCodeCamp/freeCodeCamp#44596]
## Affected page

Problem begins at Step 53 and continues throughout the rest of the tutorial (Step 92)
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-53

## To reproduce

Am able to see in private browsing mode too. 

## Recommended fix, suggestions

Wherever the code is located that has the word "Cinammon", fixing the spelling error so it's "Cinnamon". 

## Screenshots
First page it's incorrect.
<img width="708" alt="Screen Shot 2021-12-27 at 10 34 39 AM" src="https://user-images.githubusercontent.com/49349280/147490578-c88d511e-0cd2-461c-a579-ffccab950f9f.png">

Last page, showing it's still incorrect.
<img width="495" alt="Screen Shot 2021-12-27 at 10 35 17 AM" src="https://user-images.githubusercontent.com/49349280/147490613-685cca3d-82da-4838-8daa-c136b9e2630f.png">

**Comment by najmieh** [comment]
I added a PR for this https://github.com/freeCodeCamp/freeCodeCamp/pull/44597
and appreciate any feedbacks :)
