### ISSUE TITLE
Bug in Tic-Tac-Toe Zipline

### ISSUE THREAD

**Issue by ltongues** [FreeCodeCamp/freecodecamp#446]
Problem: At the start of the game you are asked to choose between X and O. If you click outside the popup, it goes away and then the game does nothing.

Suggested improvement: If you click outside, it goes away and assigns you X or O randomly.

**Comment by abdulhannanali** [comment]
The Ziplines are made by FreeCodeCamp students and are hosted on CodePen. This one is made by Alex Dixon. I can suggest him the following solution to this problem.

**Comment by terakilobyte** [comment]
We'll take this up with the author of the  Tic-Tac-Toe example we use. Thanks
