### ISSUE TITLE
Unclear instructions for RWD (Beta) / Learn Accessibility by Building a Quiz / Step 38

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#44603]
## Affected page

[RWD (Beta) / Learn Accessibility by Building a Quiz / Step 38](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-38)

## Explanation

The final instructions for this step say:

"Then, give the `textarea` placeholder text describing an example answer."

Since the instructions mention "placeholder" I think it is safe to assume that some people will think they should use the `placeholder` attribute on the `textarea` to fulfill this requirement. But the code check test checks the `textContent` of the `textarea`:

```
assert.notEmpty(document.querySelectorAll('div.answer')?.[1]?.querySelector('textarea')?.textContent);
```

So using the `placeholder` attribute will result in the following hint:

"You should give the `textarea` placeholder text describing an example answer."

Which does not make it clear that the example answer should be embedded in the `textarea` instead of using the `placeholder` attribute.

Based on the current instructions I think most users will assume that the `placeholder` attribute should be used to complete this step and the test should be updated accordingly.

## System

- Device: Desktop
- OS: Linux/Fedora 34
- Browser: Firefox
- Version: 95.0.2

**Comment by Zeiccc** [comment]
On

**Comment by bbsmooth** [comment]
I was going to fix this issue by updating the test in step 38 to check the placeholder attribute on the textarea but then I realized that if we make this change then the HTML in each step after 38 would also need to be updated to use the placeholder attribute as well. So the question is, do we want to use the placeholder attribute and update all of the remaining steps or do we want to reword the instructions in step 38 to make it clear that you should embed the question text in the textarea and not use the placeholder attribute?

**Comment by gikf** [comment]
@bbsmooth That's a good question. The _placeholder text_ matches wording from [step 22](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-22) referring to the added attribute. That would make me think, the intention is to use the attribute.

**Comment by bbsmooth** [comment]
@gikf Agreed, this should probably be updated to use the placeholder attribute. Looks like I've got a lot of updates to include in the PR.

**Comment by ShaunSHamilton** [comment]
Thank you, for opening this.

When I wrote this, I vaguely remember reading a resource mentioning using the `placeholder` attribute on `textarea` was not the recommended approach. However, as I cannot find that, I agree using the `placeholder` attribute in this case seems like the better option.

Yes, this will require a rewrite for all subsequent lessons. However, this usually is a simple _Find and Replace_.

**Comment by bbsmooth** [comment]
Perfect. I'll submit a PR for this in just a bit.
