### ISSUE TITLE
"/" incorrectly required before ">", RWD Beta

### ISSUE THREAD

**Issue by philsawa** [freeCodeCamp/freeCodeCamp#44616]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-17

## Your code

```
<meta charset="utf-8" /> 
*note the extra space and the slash shouldn't be there*

solution also requires an extra slash near the end:
<link rel="stylesheet" type="text/css" href="styles.css"/>
*note that the forward slash is required to pass the challenge*




```

## Expected behavior

A) Expected not to see a space and forward slash before the closing less than sign of the meta element.

B)Expected to clear the stage without having to insert a forward slash.

## System

- Device: LG G6 and Samsung Tablet
- OS: Android 9
- Browser: Firefox Nightly
- Version: 97

## Additional context

See the forum for a screenshot and Roma's solution:

https://forum.freecodecamp.org/t/rwd-beta-colored-markers-need-help-or-to-verify-bug/490422/11

**Comment by gikf** [comment]
`meta` is self-closing element, `/` is not required in it, but that don't seem to be an error per se. As far as I can tell both versions with `/` and without are accepted by tests.

Similarly `link` is self-closing, so it appears that both with `/` and without it should be fine. Some tests don't allow version without `/`. Pages that seem to be affected, with specific lines:
[curriculum\challenges\english\14-responsive-web-design-22\learn-basic-css-by-building-a-cafe-menu\step-017.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/1a9a48911f2a5316bd4e1180edcfb73a9fcb49de/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-017.md?plain=1#L30-L38):
````
  30  ```js
  31: assert(code.match(/<link[\w\W\s]+\/>/i));
  32: ```
  33: 
  34: Your `link` element should be within your `head` element.
  35: 
  36: ```js
  37: assert(code.match(/<head>[\w\W\s]*<link[\w\W\s]*\/>[\w\W\s]*<\/head>/i))
  38  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-animation-by-building-a-ferris-wheel\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/1a9a48911f2a5316bd4e1180edcfb73a9fcb49de/curriculum/challenges/english/14-responsive-web-design-22/learn-css-animation-by-building-a-ferris-wheel/step-001.md?plain=1#L144-L152):
````
  144  ```js
  145: assert(code.match(/<link[\w\W\s]+\/>/i));
  146: ```
  147: 
  148: Your `link` element should be within your `head` element.
  149: 
  150: ```js
  151: assert(code.match(/<head>[\w\W\s]*<link[\w\W\s]*\/>[\w\W\s]*<\/head>/i))
  152  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-transforms-by-building-a-penguin\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/1a9a48911f2a5316bd4e1180edcfb73a9fcb49de/curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/step-001.md?plain=1#L91-L93):
````
  91  ```js
  92: assert(code.match(/<head>[\w\W\s]*<link[\w\W\s]*\/>[\w\W\s]*<\/head>/i))
  93  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-variables-by-building-a-city-skyline\step-004.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/1a9a48911f2a5316bd4e1180edcfb73a9fcb49de/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/step-004.md?plain=1#L57-L65):
````
  57  ```js
  58: assert(code.match(/<link[\w\W\s]+\/>/i));
  59: ```
  60: 
  61: Your `link` element should be within your `head` element.
  62: 
  63: ```js
  64: assert(code.match(/<head>[\w\W\s]*<link[\w\W\s]*\/>[\w\W\s]*<\/head>/i))
  65  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-html-forms-by-building-a-registration-form\step-004.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/1a9a48911f2a5316bd4e1180edcfb73a9fcb49de/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/step-004.md?plain=1#L58-L66):
````
  58  ```js
  59: assert(code.match(/<link[\w\W\s]+\/>/i));
  60: ```
  61: 
  62: Your `link` element should be within your `head` element.
  63: 
  64: ```js
  65: assert(code.match(/<head>[\w\W\s]*<link[\w\W\s]*\/>[\w\W\s]*<\/head>/i))
  66  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-intermediate-css-by-building-a-picasso-painting\step-003.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/1a9a48911f2a5316bd4e1180edcfb73a9fcb49de/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-picasso-painting/step-003.md?plain=1#L25-L33):
````
  25  ```js
  26: assert(code.match(/<link[\w\W\s]+\/>/i));
  27: ```
  28: 
  29: Your `link` element should be within your `head` element.
  30: 
  31: ```js
  32: assert(code.match(/<head>[\w\W\s]*<link[\w\W\s]*\/>[\w\W\s]*<\/head>/i))
  33  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-responsive-web-design-by-building-a-piano\step-008.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/1a9a48911f2a5316bd4e1180edcfb73a9fcb49de/curriculum/challenges/english/14-responsive-web-design-22/learn-responsive-web-design-by-building-a-piano/step-008.md?plain=1#L29-L37):
````
  29  ```js
  30: assert(code.match(/<link[\w\W\s]+\/>/i));
  31: ```
  32: 
  33: Your `link` element should be within your `head` element.
  34: 
  35: ```js
  36: assert(code.match(/<head>[\w\W\s]*<link[\w\W\s]*\/>[\w\W\s]*<\/head>/i))
  37  ```
````

**Comment by abgutmann1** [comment]
I also had the same problem. Apparently, you use a /> closing tag with link if you're using HTML5. The thing is up until this point, all self-closing elements we've worked with (like img and meta) have not required it. Perhaps what is needed here is further explanation on the instruction portion of the exercise.

**Comment by nhcarrigan** [comment]
Weird that prettier auto-closes `meta` tags with `/>`.

I'd be fine with making the `/` optional in these tests.

**Comment by moT01** [comment]
If they're both valid, ideally, they would both pass. 

[This PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/42195) should be getting in soon, which can help us with these tests. The reason they're all in regex is cause some of these elements weren't being rendered as hoped. `link` elements, for example, were rendering in the `body` of the preview, not the `head`. When that PR gets in, it should render those as they appear in the code. Then, we can use JavaScript to check the DOM on where these element live and don't have to worry about the syntax. I wouldn't oppose a PR to fix the regex tests, but it might be easier to wait for that PR and fix these after that using JS.

**Comment by nhcarrigan** [comment]
The above referenced PR has been merged. We should be good to move forward with updating the tests to move away from Regex and use DOM queries.

**Comment by Ne0nWinds** [comment]
I was trying to implement this today and ran into an issue. It looks like the link tag is removed from the DOM in this piece of code. This makes it impossible to do DOM test cases when it requires including `styles.css`. As a test, I removed line `222`, and the new DOM test cases I wrote passed without a problem
https://github.com/freeCodeCamp/freeCodeCamp/blob/06071cfbcf7c3a3a25f84fdf17777d8d87b59f76/client/src/templates/Challenges/rechallenge/transformers.js#L210-L222

A few questions:
- What was the purpose of removing link tags from the DOM? (Original PR: #42205)
- Can we modify / remove the code in the `addImportedFiles` to work with the DOM-style test cases?

FYI @moT01 @nhcarrigan

**Comment by moT01** [comment]
There's [some context in that PR you linked](https://github.com/freeCodeCamp/freeCodeCamp/pull/42205/files#r643285915) @Ne0nWinds. "They were causing 404 errors to appear in the console, so I figured it was simpler just to remove them entirely"

I guess a few console errors might not be the worst thing, but I think we probably want to leave it how it is (remove them) if we can. It looks like we've been using regex on [those few tests elsewhere.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3477cb2e27333b1ab2b955.md)

**Comment by Ne0nWinds** [comment]
Okay, I can start working on making these regex tests better. Though, I think, if there's a way we can do it through DOM queries, we should definitely do that, because they're going to be more reliable and easier to maintain

**Comment by Ne0nWinds** [comment]
I had an idea that would potentially solve this. What if instead of removing the link tag, we change the `href` to a `data:href` property (more on this [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*)). Without an `href` property, the link tag won't make an actual http request, so this would solve the problem of 404 errors. However, we still have access to the link tag for DOM query test cases

The only weird part would be this one test case:
```js
// Your `link` element should have an `href` attribute with the value `styles.css`.
const element = document.querySelector('link');
assert.equal(element.dataset.href, 'styles.css');
```

The rest of the test cases can use the standard `getAttribute` function

**Comment by ojeytonwilliams** [comment]
While that does neatly solve the 404 issue, it is no longer realistic - it's not how to add css to a page.

As much as possible, we want to keep the experience of working in the editor equivalent to working with raw html, css and JavaScript.

**Comment by Ne0nWinds** [comment]
> While that does neatly solve the 404 issue, it is no longer realistic - it's not how to add css to a page.
> 
> As much as possible, we want to keep the experience of working in the editor equivalent to working with raw html, css and JavaScript.

So the user would still put in this in the code editor:
```html
<link rel="stylesheet" type="text/css" href="styles.css" />
```

but the code transformer could do something like this:
```js
link.removeAttribute("href");
link.dataset.href = "styles.css";
```

So the code the user puts in is still exactly the same as in real code, but behind the scenes, it's transformed to something we can use for the test cases

**Comment by Ne0nWinds** [comment]
> Thanks for explaining, it's an interesting idea. Would be interested in creating a PR so we can test this out?

Yeah! I'll get a PR out this weekend

**Comment by Ne0nWinds** [comment]
Hey @ojeytonwilliams, if you can look at the PR I just referenced, that would be great!
