### ISSUE TITLE
The challenge description contains an unnecessary word in "Learn HTML by Building a Cat Photo App" - Step 36

### ISSUE THREAD

**Issue by senthusiva** [freeCodeCamp/freeCodeCamp#44618]
## Affected page
(https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-36)

## System

- Device: [Laptop]
- OS: [Kubuntu 21.10 x86]
- Browser: [chrome]

## Additional context

The challenge description contains an unnecessary word:
The input element **~~is allows~~** you several ways to collect data from a web form. 

### The correct way can be:
**Proposal 1**: The input element gives you several ways to collect data from a web form. 
**Proposal 2**: The input element offers you several ways to collect data from a web form. > #44619

I am not a native english speaker. Please let me know if that is an error and if there are other ways to formulate it. Thank you for your patience and your work. 

This is my solution pull request: #44619

**Comment by gikf** [comment]
Thank you for reporting this issue.

This was fixed in #44592.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
