### ISSUE TITLE
Your h2 element should be red.

### ISSUE THREAD

**Issue by dsinjm** [FreeCodeCamp/FreeCodeCamp#4462]
Waypoint: Change the Color of Text. Before I even type my code in I have a red X and it says that your h2 element should be red. When I do type in me code. I get the same result. My code is 
<h2 style="color: red">CatPhotoApp</h2>. What am I doing wrong?

**Comment by SaintPeter** [comment]
For questions about code that are not specifically a bug with the site, please ask for help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) - There are plenty of helpful campers waiting to answer your questions.
