### ISSUE TITLE
RWD Ferris Wheel Step 1

### ISSUE THREAD

**Issue by whitwulf** [freeCodeCamp/freeCodeCamp#44623]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-animation-by-building-a-ferris-wheel/step-1

## Your code

```
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./styles.css" />
    <title>CSS Ferris Wheel</title>
  </head>
  <body></body>
</html>

```

## Expected behavior

Tests return error: 
Your html element should be below the DOCTYPE declaration

## System

- Device: [Desktop]
- OS: [EndeavorOS (Arch Linux)]
- Browser: [chrome]
- Version: [96.0.4664.110 (Official Build) (64-bit)]

**Comment by bbsmooth** [comment]
I was able to fix this by adding the 'm' flag to the test so it takes multiple lines into account:

`assert(code.match(/^\s*<!DOCTYPE\s+html\s*>[\s\S]*<\s*html\s*>/gim));`

I'll go through the other steps in this course real quick to make sure there are no other issues and then submit a PR>

**Comment by bbsmooth** [comment]
I didn't find any problems with the other steps.
