### ISSUE TITLE
RWD Beta: Test that requires DOCTYPE to be on its own line is failing

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#44626]
## Affected page

Several. One example is [Learn HTML Forms by Building a Registration Form / Step 2](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-2)

## Your code

```
<!DOCTYPE html><html></html>
```

## Expected behavior

The hint for this step seems to indicate that the user must add the `html` element below the `DOCTYPE` (there must be at least one new line separating them).

Hint: "Your `html` element should be below the `DOCTYPE` declaration.:"

So the expected behavior would be that the user will not pass this step until they add the `html` element below the `DOCTYPE`.

## System

- Device: Desktop
- OS: Linux/Fedora 34
- Browser: Firefox
- Version: [e.g. 22]

## Additional context

This is happening for several courses. The regex used for this test is not enforcing the newline between the elements. If this requirement is important enough to be enforced then we should probably come up with one regex that enforces this requirement and use it for all courses.

**Comment by bbsmooth** [comment]
One possible regex I am using as a solution for this [issue](https://github.com/freeCodeCamp/freeCodeCamp/pull/44625) is:

`assert(code.match(/\s*<!DOCTYPE\s+html\s*>(\r?\n)+<\s*html\s*>/gi));`

**Comment by gikf** [comment]
Affected pages:

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-animation-by-building-a-ferris-wheel\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-css-animation-by-building-a-ferris-wheel/step-001.md?plain=1#L54-L58):
````
  54: Your `html` element should be below the `DOCTYPE` declaration.
  55  
  56  ```js
  57  assert(code.match(/^\s*<!DOCTYPE\s+html\s*>[\s\S]*<\s*html\s*>/gi));
  58  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-colors-by-building-a-set-of-colored-markers\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/step-001.md?plain=1#L52-L56):
````
  52: Your `html` element should be below the `DOCTYPE` declaration.
  53  
  54  ```js
  55  assert(code.match(/(?<!<html\s*>)<!DOCTYPE\s+html\s*>/gi));
  56  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-flexbox-by-building-a-photo-gallery\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/step-001.md?plain=1#L50-L54):
````
  50: Your `html` element should be below the `DOCTYPE` declaration.
  51  
  52  ```js
  53  assert(code.match(/(?<!<html\s*>)<!DOCTYPE\s+html\s*>/gi));
  54  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-grid-by-building-a-magazine\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-css-grid-by-building-a-magazine/step-001.md?plain=1#L52-L56):
````
  52: Your `html` element should be below the `DOCTYPE` declaration.
  53  
  54  ```js
  55  assert(code.match(/(?<!<html\s*>)<!DOCTYPE\s+html\s*>/gi));
  56  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-css-variables-by-building-a-city-skyline\step-002.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/step-002.md?plain=1#L14-L18):
````
  14: Your `html` element should be below the `DOCTYPE` declaration.
  15  
  16  ```js
  17  assert(code.match(/(?<!<html\s*>)<!DOCTYPE\s+html\s*>/gi));
  18  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-html-forms-by-building-a-registration-form\step-002.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/step-002.md?plain=1#L14-L18):
````
  14: Your `html` element should be below the `DOCTYPE` declaration.
  15  
  16  ```js
  17  assert(code.match(/(?<!<html\s*>)<!DOCTYPE\s+html\s*>/gi));
  18  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-intermediate-css-by-building-a-picasso-painting\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-picasso-painting/step-001.md?plain=1#L38-L42):
````
  38: Your `html` element should be below the `DOCTYPE` declaration.
  39  
  40  ```js
  41  assert(code.match(/(?<!<html\s*>)<!DOCTYPE\s+html\s*>/gi));
  42  ```
````

[curriculum\challenges\english\14-responsive-web-design-22\learn-responsive-web-design-by-building-a-piano\step-001.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/426b2f57c7a8ec7e1a9f2b6323392762ee843899/curriculum/challenges/english/14-responsive-web-design-22/learn-responsive-web-design-by-building-a-piano/step-001.md?plain=1#L50-L54):
````
  50: Your `html` element should be below the `DOCTYPE` declaration.
  51  
  52  ```js
  53  assert(code.match(/(?<!<html\s*>)<!DOCTYPE\s+html\s*>/gi));
  54  ```
````

**Comment by xoxoKaralee** [comment]
If the regex from @bbsmooth is the way we want to go, I'd be happy to start working on it in the pages linked by @gikf .

**Comment by bbsmooth** [comment]
@xoxoKaralee I was eventually going to get around to updating these but please, feel free to step in. My solution above was officially merged into main so I'm assuming that's acceptable to use for these as well.

**Comment by bbsmooth** [comment]
I'm beginning to wonder if we should even have a requirement that the DOCTYPE be on its own separate line? I can't seem to find any documentation that says this is required and the W3C HTML validator accepts it without being on a new line. Also, we don't seem to be enforcing separate lines for other types of tags. But the DOCTYPE does need to be the first element on the page, which I don't think we are currently testing for, so I propose we test for that instead and get rid of the separate line requirement.

**Comment by ShaunSHamilton** [comment]
As far as the tests go, I suggest we stick with this:
- If the HTML spec can parse it, it is valid, and should be accepted, unless the instructions specifically say, for example, _"add a semi-colon at the end of the value"_

So, as I can see in the spec, there is no requirement for the DOCTYPE and the `html` element to be on separate lines:
- https://html.spec.whatwg.org/#the-doctype
- https://html.spec.whatwg.org/#the-html-element

**Comment by bbsmooth** [comment]
Would you agree with me then that instead of testing for DOCTYPE being on a separate line we should be testing that the DOCTYPE is the first element on the page? This brings us back to another [issue](https://github.com/freeCodeCamp/freeCodeCamp/pull/44625) I found in which there are JS comments in the code string before the HTML begins:

```
/*fcc*/

/*fcc*/
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./styles.css" />
    <title>CSS Ferris Wheel</title>
  </head>
  <body></body>
</html>
```
Not impossible to work around, just wanted to make whoever ultimately works on this aware of it.

**Comment by xoxoKaralee** [comment]
It wouldnt surprise me if that's the why the test was written that way, because if doctype isnt the first element, how else would you check it's current placement? It would be in relation to the html tag, right?

**Comment by ShaunSHamilton** [comment]
> Would you agree with me then that instead of testing for DOCTYPE being on a separate line we should be testing that the DOCTYPE is the first element on the page?

Ideally, yes. As I mentioned below, we do have a solution to the comment thing, but it is a work-in-progress.

https://github.com/freeCodeCamp/freeCodeCamp/pull/44625#issuecomment-1003978797

**Comment by bbsmooth** [comment]
I have submitted a [pull request](https://github.com/freeCodeCamp/freeCodeCamp/pull/44720) that fixes the source of this issue (css comments before the html in the code string) which if approved will allow us to easily test that the DOCTYPE declaration is the first element in the HTML.

**Comment by xoxoKaralee** [comment]
@bbsmooth should i close my initial pull request since you said in your pull request that you were going to fix the others once yours gets approved and merged? I dont mind helping update the other docs with the new test once it's approved if you want me to. either way, just let me know !

**Comment by scissorsneedfoodtoo** [comment]
We've had a couple of reports in the support inbox that the negative lookbehind used in some of these tests is failing in Safari, so it's great that either #44651 or #44829 (pending update) will take care of that as well.

At the moment #44829 seems more flexible, and allows valid code to pass without forcing a particular style. It'll also be good to move away from regex for this type of test.

**Comment by ahmadabdolsaheb** [comment]
If __helpers.removeHtmlComments(code) is preferred, we could modify #44651 in that direction or accept #44996 alternatively.

**Comment by bbsmooth** [comment]
Yes, [#44996](https://github.com/freeCodeCamp/freeCodeCamp/pull/44996) is the final PR to put this issue to rest. I did an initial PR [#44829](https://github.com/freeCodeCamp/freeCodeCamp/pull/44829) for just one course and it has already been merged. [#44996](https://github.com/freeCodeCamp/freeCodeCamp/pull/44996) is using the same solution, just updating the remaining courses that need it.
