### ISSUE TITLE
Correct answer not being accepted in Resp. Web Design (Beta)

### ISSUE THREAD

**Issue by Kernix13** [freeCodeCamp/freeCodeCamp#44621]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-17

## Your code

```

  <head>
    <meta charset="utf-8" />
    <title>Camper Cafe Menu</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>


```

## Expected behavior

I expected to get a correct answer after clicking the Check Your Code button but I got an error message instead.

## Screenshots

![link-tag-bug](https://user-images.githubusercontent.com/66497948/147713631-2bafcb81-ea9b-4490-ba76-9b0c86d15f41.PNG)

## System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [brave]
- Version: [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)]

**Comment by buntured** [comment]
Hey @Kernix13, try using the plural `styles.css` instead of singular `style.css`.   

![Screenshot](https://user-images.githubusercontent.com/640624/147726274-0db2e05b-add0-4438-a8df-7200403cc211.jpg)

Thank you,
Buntu

**Comment by Kernix13** [comment]
I was really hoping I didn't miss something, and I did. I just changed style.css to styles.css and it worked. Sorry to waste your time.
