### ISSUE TITLE
JAWS 2022 overly verbose with aria-roledescription attribute in monaco editor

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#44639]
## Affected page

Any page with the monaco editor while using the JAWS 2022 screen reader with either Firefox or Chrome (and I'm assuming any other Chrome-based browsers).

## Explanation

The monaco editor has the aria-roledescription attribute set to "editor" on its textarea. This is causing JAWS 2022 to add the word "editor" to the beginning of each line and the phrase "end editor" to the end of each line while traversing the lines with the up and down arrow keys. This issue is not present in previous versions of JAWS (such as 2021) so it seems that the 2022 version has changed the way it handles the aria-roledescription attribute. Removing this attribute eliminates the extra verbiage in JAWS 2022.

The use of the aria-roledescription attribute is not necessarily required for accessibility. A textarea already has a default role which will be announced by the screen reader. The aria-roledescription attribute allows the default role to be overridden, which in this case the monaco editor is setting it to "editor". Regardless of whether the use of aria-roledescription is warranted here, JAWS 2022 is now handling it differently and being too verbose, to the point that we have already received a [bug report](https://forum.freecodecamp.org/t/i-am-having-issues-with-jaws-screen-reader-in-code-editor-in-css-course-part-of-responsive-web-design-certification/490279/6) from a user in the forums.

## Recommendation

The immediate solution is to remove the aria-roledescription attribute from the textarea. The monaco API does not appear to give us a convenient way to do this, so this will have to be done by brute force. I have implemented a code fix for this and will open a PR to get the ball rolling.

Before pushing this to production I would recommend we have a few screen reader users test this fix just to make sure the removal of this attribute does not cause more harm than it fixes. They do not need to be using JAWS 2022 for testing. In fact, it would be a good idea to get testing with several different screen readers.

Another thought is that perhaps we could make this fix an option that the user could enable if needed? In other words, leave the aria-roledescription by default and give users who are affected by this issue the ability to enable the fix and remove the attribute.

Granted, this issue is not ultimately for FCC to solve as either JAWS and/or monaco will need to address this. I suppose if we didn't feel comfortable manually fixing this ourselves then we could provide a disclaimer that JAWS 2022 is not recommended to be used with FCC, or at least warn JAWS 2022 users of this issue.

## System

- Device: Desktop
- OS: Windows 10
- Browsers: Firefox 95.0.2 (64-bit) and Chrome 96.0.4664.110 (Official Build) (64-bit)

## Additional context

I have opened a [bug report issue with FreedomScientific](https://github.com/FreedomScientific/VFO-standards-support/issues/598) (the developers of JAWS). This is proprietary software and there is no guarantee of when, or even if it will be fixed. I think I will also open a bug report in the monaco repo to make them aware that this is going to become a prominent issue as more people transition to JAWS 2022.

**Comment by bbsmooth** [comment]
This issue has now officially been confirmed as a bug in JAWS 2020. I have a fix for this on my local copy (it just removes the `aria-roledescription` attribute from the monaco editor). I've tried to start a discussion in the Contributors section of the forum about how we could roll this fix out but haven't had any bites yet. I do believe that we could apply the fix for everyone and it would not cause any significant accessibility issues. But this attribute could potentially be providing some benefit that certain users might not want to lose. So I think a selective solution that provides an opt-in to the fix (or at least an opt-out if we apply the fix globally) might be best.

**Comment by bbsmooth** [comment]
I now have a working solution in place that will allow the user to toggle the `aria-roledescription` attribute off and on. I've added an option to the monaco editor's F1 menu that adds a key-combination command to toggle the attribute (I'm using Ctrl+Alt+J at the moment). The toggled state is saved to local storage so it persists across sessions. This is modeled on how the "Accessibility Mode" feature is implemented.

There are some minor details that still need to be worked out but we do have one known user who is affected by this and is currently having to use a workaround (coding in Notepad and then copy/pasting into monarch). I think it would be beneficial to get this fix to production even before every single detail is worked out so we can have him test and make sure it is working properly for him. I don't think this should cause any confusion for other users as this is a fix for a very specific bug that can only be accessed through the monaco menu and will only affect screen reader users.

**Comment by ShaunSHamilton** [comment]
@bbsmooth Is this safe to close now? Or, are we leaving this open until the shortcut is changed?
