### ISSUE TITLE
Waypoint: Add Images to your Website

### ISSUE THREAD

**Issue by senoff** [FreeCodeCamp/FreeCodeCamp#4463]
In this waypoint it doesn't mention that you should add the image to the button of the page.  That seems like it would make it a clearer instruction.

**Comment by SaintPeter** [comment]
I presume that you mean "bottom" of the page, as there are no buttons.  There is no requirement that you add it in any particular location on the page. 

Thanks and happy coding!

**Comment by senoff** [comment]
Yep.  Exactly.

**Comment by senoff** [comment]
Ah.  Thanks.
