### ISSUE TITLE
Remove invalid example of a PR title

### ISSUE THREAD

**Issue by Browun** [freeCodeCamp/freeCodeCamp#44638]
## Affected page

As stated in a [PR review](https://github.com/freeCodeCamp/.github/pull/6#discussion_r777112965) by @ieahleen, the example of a PR title (`docs(i18n): Chinese translation of local setup`) is misleading as this is not to be done manually; instead being perormed by automated pipelines.

[Prepare a good PR title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title)

[Page on Github](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/how-to-open-a-pull-request.md#prepare-a-good-pr-title)

## To reproduce

Visit the above page `Prepare a good PR title` and scroll down to find the text: `docs(i18n): Chinese translation of local setup`

## Recommended fix, suggestions

Remove this example from the documentation.

## Screenshots

<img width="653" alt="Image of the invalid example of a pr title" src="https://user-images.githubusercontent.com/37123234/147853546-68f7d667-2f01-477e-b51c-ac8e7fc0535c.png">

**Comment by ShaunSHamilton** [comment]
Hello there 👋 

If anything is done here, I would not remove it from the examples - I would change it to include something else that is relevant. Reason being, it is nice to have an example showing `docs(i18n)`.

**Comment by ieahleen** [comment]
like we could make the last example something like `docs(i18n): fix links to be relative instead of absolute`, that is something we keep doing to avoid redirect to the EN docs from the other ones

**Comment by nhcarrigan** [comment]
I'd be in favour of implementing Ilenia's proposed change.

Though I'm not sure anything needs to be fixed here. Yes, our translation PRs are automatic, but it's still a good example of a PR title.
