### ISSUE TITLE
RWD Beta: Markdown text not displaying on lesson page

### ISSUE THREAD

**Issue by Kernix13** [freeCodeCamp/freeCodeCamp#44640]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-31

## Your code

```
<option>freeCodeCamp YouTube</option>
```

## Expected behavior

The text for the options was provided and for the third one the text is `freeCodeCamp YouTube`.

However, that option is wrong and you are prompted to use `freeCodeCamp YouTube Channel`. 

The word "Channel" is not on the page so I was going to add it but it is in the markdown file `step-031.md` on **line 15**.

## Screenshots

![missing-channel](https://user-images.githubusercontent.com/66497948/147858326-cba082d5-945d-4aee-ad51-8653c91fc76b.PNG)

## System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [brave]
- Version: [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)]

## Additional context

It is the third option and all the JavaScript snippets belw the page text have `fieldset:nth-child(3)`. Here is the one for the option for the YT Channel:

```js
assert.equal(document.querySelectorAll('fieldset:nth-child(3) > label:nth-child(3) option')?.[2]?.textContent, 'freeCodeCamp YouTube Channel');
```

**Comment by xoxoKaralee** [comment]
Hey! This has already been brought up:
Closed original issue #44602
PR in #44607

Again someone yesterday brought it up in a new issue #44634
if you check in here, the last comment explains what seems to be going on.

**Comment by Kernix13** [comment]
Good, so it looks like it will be fixed soon. What would be a good way to see if an issue has already been created? Should I have searched for "step 31" or something unique with this problem? I'll try to remember to do a search first - sorry for the duplicate issue.

**Comment by gikf** [comment]
Relevant fix is in production, as such I'm closing this issue.

Trying to search open and closed issues for something related to the problem, or taking a look at some titles of recently opened and closed issues usually should be enough to find, if there's already the issue on the same topic.
