### ISSUE TITLE
Make tests stricter for challenge "Decrement a number with javascript"

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#44648]
You can pass the test by assigning 10 to the variable after decrementing it past that value.

It also doesn't seem like the...

> `myVar = myVar - 1;` should be changed.

...test is not working.

Incorrect code that is passing:

```
let myVar = 11;

// Only change code below this line
myVar = myVar - 1;
myVar--;
myVar = 10;
```

Forum: https://forum.freecodecamp.org/t/decrement-a-number-with-javascript-solution/490852

Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/decrement-a-number-with-javascript

Tests: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/decrement-a-number-with-javascript.md

**Comment by ShaunSHamilton** [comment]
I am happy with this being changed, but, personally, I see no issue here:
- The lesson teaches the  `--` operator, and that has been used.

If the lesson were to give an `h1` element the text `Hello, World!`, and you did this, I would not expect you to fail the tests:
```js
const h1 = document.querySelector('h1')
h1.textContent = "Hi there!";
h1.textContent = "Hello, World!";
```

**Aside**
_I might be becoming pessimistic in my teaching pedagogy, but we cannot truly expect to keep changing all these lessons forever, as more and more cases are found_ - there is a "good enough" point, IMO.

**Comment by import-brain** [comment]
> I am happy with this being changed, but, personally, I see no issue here:
> 
> * The lesson teaches the  `--` operator, and that has been used.
> 
> If the lesson were to give an `h1` element the text `Hello, World!`, and you did this, I would not expect you to fail the tests:
> 
> ```js
> const h1 = document.querySelector('h1')
> h1.textContent = "Hi there!";
> h1.textContent = "Hello, World!";
> ```
> 
> **Aside** _I might be becoming pessimistic in my teaching pedagogy, but we cannot truly expect to keep changing all these lessons forever, as more and more cases are found_ - there is a "good enough" point, IMO.

Yes, I believe that if a user uses the solution that @lasjorg stated, they know how `--` works already, which fulfills the objective of the lesson.

**Comment by lasjorg** [comment]
@ShaunSHamilton I don't think your example is equivalent at all. The end value is supposed to be the result of decrementing, not just assigning a final value.

> Yes, I believe that if a user uses the solution that @lasjorg stated, they know how `--` works already, which fulfills the objective of the lesson.

Clearly, they do not if they can not decrement the starting value to the final value that is asked for. I see no reason why anyone that understands what the challenge is asking for would do that assignment.

---

I would think a test with a regex that looks for an assignment to be good enough here.

> Do not directly assign the value `10` to the `myVar` variable.

**Comment by import-brain** [comment]
> @ShaunSHamilton I don't think your example is equivalent at all. The end value is supposed to be the result of decrementing, not just assigning a final value.
> 
> > Yes, I believe that if a user uses the solution that @lasjorg stated, they know how `--` works already, which fulfills the objective of the lesson.
> 
> Clearly, they do not if they can not decrement the starting value to the final value that is asked for. I see no reason why anyone that understands what the challenge is asking for would do that assignment.
> 
> We are not just blindly looking for the `--` operator to be used. We are looking for the value `11` to be decremented to `10` using the operator.
> 
> An example would be a lesson where you ask someone to use a word in a sentence and they use the word incorrectly. They may have used the word but if it is used incorrectly they do not understand the word. Using it in a sentence means correctly using it, not just blindly shoving it into a sentence.
> 
> I would think a test with a regex that looks for an assignment to be good enough here.
> 
> > Do not directly assign the value `10` to the `myVar` variable.

You're right, my bad. As I understand it, you want to use regex to check if an assignment is present, and if it is, fail the tests?

I think that would work well.

**Comment by lasjorg** [comment]
1. The second test should be updated. Right now you can leave the initial code even though the test says it should be replaced. It should test that `myVar = myVar - 1;` is not present in the code.

2. Check that no assignment is used.

**Comment by import-brain** [comment]
> 1. The second test should be updated. Right now you can leave the initial code even though the test says it should be replaced. It should test that `myVar = myVar - 1;` is not present in the code.
> 
>     2. Check that no assignment is used.

I see, thank you for the clarification!
