### ISSUE TITLE
Unclear instructions in Learn SQL by Building a Student Database: Part 2

### ISSUE THREAD

**Issue by aburto22** [freeCodeCamp/freeCodeCamp#44659]
## Affected page

Learn SQL by Building a Student Database: Part 2 (Completing locally)

## Issue

There are some excercises where the instruction are a bit missleading. For example, take this excercise:

You’re doing great. Next, use the most efficient join to get the rows needed if you were asked to get the first name, last name, major, and GPA of students who are taking Data Science or have a gpa of 3.8 or greater.

Reading this, I would think that I need to SELECT only the fours requested rows (first name, last name, major and GPA), join both tables and then include conditions to complete the excercise. However, this doesn’t resolve the exercise at all. After reading the hints, you realize that you need to query all columns (*) and don’t include any conditions (avoid using WHERE and HAVING) for now.

This happens with a couple more excercises.

## Proposed solution

I believe the wording should be amended slightly to indicate the expected result. For example:

You’re doing great. Next, use the most efficient join to get the rows needed if you were asked to get the first name, last name, major, and GPA of students who are taking Data Science or have a gpa of 3.8 or greater. Start by selecting all columns from both tables. Don’t include any conditions for now.

## System

- Device: Laptop
- OS: Windows 10 WSL2
- Browser: N.A.
- Software: VS Code

**Comment by moT01** [comment]
Thanks for reporting @aburto22. I agree that these could be a little more clear.

**Comment by raditotev** [comment]
Hi @aburto22. You've mentioned `This happens with a couple more exercises .`. If you can make a list with proposed changes and those get approved by the freeCodeCamp members, I can make the necessary changes.

**Comment by akalezic** [comment]
I made a PR that should hopefully solve this issue https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-2/pull/18

I'd love to hear which other sections are unclear to take a crack at those as well.

**Comment by cossieB** [comment]
I'm doing this now and I came here to say this. Instructions are misleading. I had to look at the hint.
