### ISSUE TITLE
problem when hitting Space bar

### ISSUE THREAD

**Issue by franciscomelov** [freeCodeCamp/freeCodeCamp#44656]
**Describe the bug**
when I hit the Space bar instead of giving an space it inputs more text.
When I want to write "hello world"
I write "hello" normally but when it the Space bar "hellohellohello " is the output

**To Reproduce**
1. Go to  Responsive web design certification, "
2. Go to the first challenge "say hello to html elements"
3. Go to the "code" section
4. In the code editor you have "Hello"
5. If I try to put an space after "hello"
6. this is the output "HelloHelloHello "

**Expected behavior**
hitting the space bar should just give an space " "

**Screenshots**
![1](https://user-images.githubusercontent.com/17803231/147834589-8c3a2d66-bb8d-4a49-8ada-092db261a4e5.jpeg)
![2](https://user-images.githubusercontent.com/17803231/147834606-0bc5501c-4ccf-4736-8473-3f1fb2369f3a.jpeg)

**Smartphone (please complete the following information):**
 - Device: [HUAWEI P10 Selfie]
 - OS: [android 8.0.0]
 - Browser [frecodecamp app]
 - Version [frecodecamp app version 2.0.4]

**Comment by ShaunSHamilton** [comment]
Hello there.

If you are using a mobile device, the default keyboard does not always play well with the freeCodeCamp editor. I recommend you read the [article on using a mobile device](https://www.freecodecamp.org/news/freecodecamp-mobile/) to view some tips - most importantly, check out the coding keyboards listed as they interface with the editor well.

**Comment by franciscomelov** [comment]
I installed CodeBoard Keyboard for Coding and works fine.
Thanks
