### ISSUE TITLE
Learn SQL by Building a Student Database: Part 2 - Wrong solution for last challange

### ISSUE THREAD

**Issue by aburto22** [freeCodeCamp/freeCodeCamp#44660]
## Affected page

Learn SQL by Building a Student Database: Part 2 (Completing locally).

## Issue

In the last excercise, we are asked to:

List of courses, in alphabetical order, with only one student enrolled:

The correct answer given in hints is the following:

SELECT course FROM students RIGHT JOIN majors USING(major_id) INNER JOIN majors_courses USING(major_id) INNER JOIN courses USING(course_id) GROUP BY course HAVING COUNT(course) = 1 ORDER BY course;

Which gives the following result:

Network Security
Server Administration
UNIX

However, I don’t believe this is correct. Server Administration and UNIX are correct, but Network Security is not. Network Security is only in one major, Network Engineering, and no students are taking this major.

In addition to this, Computer Systems and Computer Network courses are both in 3 majors: Computer Programming, Network Engineering and System Administration. Computer Programming and Network Engineering have no students, and System Administration has 1 student. Therefore, there should be part of the correct answer.

## Proposed solution

My proposed correct answer is:

Computer Systems
Computer Network
Server Administration
UNIX

To obtain this answer, my proposed solution is:

SELECT course FROM students INNER JOIN majors_courses USING(major_id) INNER JOIN courses USING(course_id) GROUP BY course HAVING COUNT(student_id) = 1 ORDER BY course;

## System

- Device: Laptop
- OS: Windows 10 WSL
- Browser: NA
- Software: VS Code

**Comment by moT01** [comment]
You're right @aburto22. Thanks for spotting this. I will put a help wanted label on it in case anyone want to try and fix it. Otherwise, I can give it a fix when I get to it.

**Comment by Rohitrout416** [comment]
hey I tried to fix the issue at https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-2/pull/11.
Please check it.
