### ISSUE TITLE
RWD Beta: Step 90 - Incomplete Instructions (Learn CSS Colors by Building a Set of Colored Markers)

### ISSUE THREAD

**Issue by abgutmann1** [freeCodeCamp/freeCodeCamp#44676]
Hi!

In Step 90 of the "Learn CSS Colors by Building a Set of Colored Markers" course, there is a piece of information missing from the instructions, which regards adding the color red to the box-shadow property. As a newbie learner, I could deduce the correct answer and complete the exercise, but perhaps updating the instructions would avoid any future confusion by other people.

**Link:** https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-90

## Screenshots

![Step 90 - Missing Info](https://user-images.githubusercontent.com/82047619/148116824-7423cad6-7899-4e68-a3b5-664f0eda86f3.png)
How it looks by following the instructions given.

## System

- Device: Laptop
- OS: Windows 10
- Browser: Google Chrome

**Comment by kamarel** [comment]
![image](https://user-images.githubusercontent.com/84261846/148311912-a05961c2-2488-42d0-98ad-f6a02a426be3.png)

box-shadow: 0 0 20px 0 red
