### ISSUE TITLE
[beta] RWD misleading error messages

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#44696]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-2

## Your code

```
<head>
 <title>
    Camper Cafe Menu 
 </title>
</head>
```

## Expected behavior

Tests should fail because the text is incorrect (it should not be surrounded by spaces or newlines).

## Actual behavior

You see the hint:
```
Your <title> element should be nested in your <head> element
```

Also, it's quite easy to fail this challenge by having spaces or newlines around the "Camper Cafe Menu" string. It might be nice to have an additional test specifically to catch that.

**Comment by nhcarrigan** [comment]
The title element isn't stripped away, so I think we could query the DOM and look at the `textContent`.
