### ISSUE TITLE
Challenge editing UI

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#44690]
MVP

- A user can create, delete and update challenges without needing to open another editor (this can make use of the cli in tools/challenge-helper-scripts)
- A user can easily navigate between steps
- A user can run it locally alongside the client, so they can see their changes taking shape.

Nice to have

- A user can see an overview (scrollable?) of the entire project
- A user can click a button to open the current challenge in their browser if the /learn client is running.
- A user can click a button to open the file in their editor

**Comment by ShaunSHamilton** [comment]
Are we set on having this tooling within the main repo?

**Comment by ojeytonwilliams** [comment]
I think we should. It's intended to be run locally when you're working on the main repo.  Putting it in another repo just creates extra friction.

**Comment by ShaunSHamilton** [comment]
What do we think about this being an editor extension?

**Comment by ojeytonwilliams** [comment]
Sounds good, but presumably we'd want to have that additionally rather than instead.  For one thing, we can't assume people are using VSCode (unless they're in Gitpod).

**Comment by Sembauke** [comment]
This does sound like a good idea, an easier way of editing challenges on the local version of the site itself (That is what I understand without any further knowledge). 

But I do have some doubts.

It sounds like we are slowly trying to put together our own CMS. There probably already exists one that fits our needs and would save us a lot of time building our own.

**Comment by ojeytonwilliams** [comment]
Hey @Sembauke it's possible something exists that meets our needs.  If so, that's awesome.  However, we should bear in mind that we have very specific requirements for the format of the data. It needs to match the [schema](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/schema/challengeSchema.js), basically.

If that's something an existing CMS can do (maybe with a custom plugin?), that's great.

**Comment by moT01** [comment]
✅ ?
