### ISSUE TITLE
Curriculum structure update

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#44691]
Fundamental:
- [x] Merge any outstanding PRs to the new project based lessons
- [x] Rename each step from `step-123.md` to the id of that step

DX:
- [x] Update our cli tooling tools/challenge-helper-scripts @ojeytonwilliams 
- [x] Implement a challenge editing UI https://github.com/freeCodeCamp/freeCodeCamp/issues/44690

**Comment by nhcarrigan** [comment]
> Rename each step from step-123.md to the id of that step

I'll spend today putting together a tool to do this for us so we aren't renaming anything manually.

**Comment by ShaunSHamilton** [comment]
**Two Notes**

1) What will this look like with the IDs:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/51722130/152253101-c69374ba-0174-43d8-a4d0-34f753360eb1.png">

2) Even with `Step`s, I do not like the lack of info in the timeline.

_Yes, I did complete the 2nd step for every project to make this point_

**Comment by nhcarrigan** [comment]
Our curriculum is designed to be done from the top down. Skipping around may lead to an incomplete experience and gaps in your learning.

**Comment by nhcarrigan** [comment]
To actually answer the question, AFAIK we'll still include step numbers in the front matter as the challenge title, so that won't change.

We could update the timeline to display the block + challenge name maybe?

**Comment by ieahleen** [comment]
This seems that everything has been completed, isn't it? @ojeytonwilliams @ShaunSHamilton @naomi-lgbt

**Comment by ShaunSHamilton** [comment]
Thanks for the ping. Yes, this all looks resolved.
