### ISSUE TITLE
Page does not goes down while scrolling with arrow 

### ISSUE THREAD

**Issue by khushbuparakh** [FreeCodeCamp/FreeCodeCamp#4470]
While writing code in editor if I use arrow keys my sidebar did not scroll down hence my arrow moves forward though.

**Comment by SaintPeter** [comment]
Your description is very vague, but this sounds like normal browser behavior.  The arrow keys only control scrolling if you don't have a text editing element selected.

Try clicking on the left column and using the arrow keys.

**Comment by ltegman** [comment]
As @SaintPeter points out this sounds like normal browser behavior when your cursor is in a text input area. If you click out of the text area into the sidebar your arrow keys can be used to scroll again.

Closing as not an issue with the website.

Thanks and happy coding!
