### ISSUE TITLE
The new RWD beta took up a lot of my laptops memory

### ISSUE THREAD

**Issue by DevOps-DoDo** [freeCodeCamp/freeCodeCamp#44706]
## Affected page

[RWD](https://www.freecodecamp.org/learn/2022/responsive-web-design)
## Your code

```
# n/a



```

## Expected behavior

I started using the new RWD beta yesterday. I did the HTML section, then moved on to the CSS cafe menu. The further I got in the CSS challenge, the slower the website got till it became next to useless. I checked it wasn't my internet so checked the processes. Chrome was showing that that tab alone was taking up 6,518,976K memory and was using 94.3% CPU. I used the end process which gave me the "Oops, something went wrong" page from chrome. I reloaded the page and it was ok, but not for long. I found I kept having to do this process throughout the CSS challenge.
Today, I moved on to the CSS marker pens and the system worked ok. Once I'd finished it, however, I checked again and the tab was using 1,154,648K memory (but was not (yet) showing any signs of being slow or causing chrome to say the page was unresponsive)

## Screenshots

![Screenshot 2022-01-05 22 49 24](https://user-images.githubusercontent.com/5068651/148468772-1918df3a-f463-4c24-b726-40e9ab9adaea.png)
![Screenshot 2022-01-06 23 54 06](https://user-images.githubusercontent.com/5068651/148468842-3b0b6a83-6d40-4df6-8213-8affcbcab0bd.png)

## System

- Device: [e.g. iPhone6, Laptop] Chromebook Laptop
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4] Chrome Version 98.0.4758.14 (Official Build) dev (64-bit)
- Browser: [e.g. chrome, safari] Chrome
- Version: [e.g. 22] Version 98.0.4758.14 (Official Build) dev (64-bit)

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to share this.

---

For others' benefit: https://forum.freecodecamp.org/t/fcc-responsive-web-design-beta-bugs-i-found-today/491301

**Comment by moT01** [comment]
I found a few posts related to chromebooks using a lot of memory:
https://www.reddit.com/r/chromeos/comments/eispxh/high_memory_usage_in_chromeos_for_seemingly_no/
https://support.google.com/chromebook/thread/13108902/high-memory-leakage-and-cpu-usage-from-browser-in-os-76?hl=en

Didn't look over them, but it seems like it might be a problem with chromebooks and/or chrome OS. Do other sites use an unusual amount of memory for you @DevOps-DoDo?

**Comment by DevOps-DoDo** [comment]
No, not had any other website doing it. And since reporting it, I've gone on and none of the other lessons do it.

**Comment by moT01** [comment]
So, to be clear - all the new RWD lessons you tried (linked in description) cause this - but none of the current/old lessons have issues? If you haven't already, want to try a few of them again to see if it happens every time?

**Comment by DevOps-DoDo** [comment]
> So, to be clear - all the new RWD lessons you tried (linked in description) cause this - but none of the current/old lessons have issues? If you haven't already, want to try a few of them again to see if it happens every time?

Correct. I will try again and get back to you.

**Comment by bradtaniguchi** [comment]
To add another data point I did parts of the first few challenges earlier as "smoke test" on my Chromebook and didn't see any increased CPU usage, or RAM usage besides a small spike when the page loads between challenges. I only spent a few minutes trying it out, as I didn't want to rebuild the entire photo-app.

I'm on a different channel than @DevOps-DoDo, here's my system specs:

```
Google Chrome: Version 98.0.4758.67 (Official Build) beta (64-bit)
Platform: 14388.37.0 (Official Build) beta-channel eve
Channel: beta-channel
Firmware Version: Google_Eve.9584.230.0
ARC Enabled: true
ARC: 8070028
Enterprise Enrolled: false
Developer Mode: false
```

I can do another focused test if need be if I know where to look/focus.

**Comment by moT01** [comment]
This is still the only known instance of this occurring as far as I know - we haven't been able to reproduce it or seen others with the issue. I could certainly be wrong, but I feel like the problem isn't on our end since it only seems to have occurred on this one device. Since this issue hasn't seen any more activity, I think it's safe to close. If anyone thinks I'm wrong in doing so, feel free to leave a comment and we can reopen it. Thanks and happy coding 🎉

**Comment by DevOps-DoDo** [comment]
No, I'm happy. If you've had no other issues, then must have been me. Sorry
for wild goose chase.

Dominic Ross
07738382996
***@***.***
DevOps_DoDo

**Comment by DevOps-DoDo** [comment]
I've changed laptop since I first reported this, so I can't test it
anymore.

Dominic Ross
07738382996
***@***.***
DevOps_DoDo
