### ISSUE TITLE
Feature request: Functionality to make it easier to find a specific step of project-based curriculum

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#44718]
## Is your feature request related to a problem? Please describe.

The new [Responsive Web Design (Beta)](https://www.freecodecamp.org/learn/2022/responsive-web-design/) certification does not have names for each step. This is making it difficult to look for a specific step.

Adding some sort of functionality to allow users to search through the curriculum (especially the project-based curriculum) will help:
- Forum contributors to answer forum questions when the questioner does not provide the link
- Learners to review/recall what they have learned

## Describe the solution you'd like

**Some ideas**

- Some kind of search functionality for the curriculum
	- Add it to contributors tools or the new challenge editing UI
- Add "tags" to identify key concepts in the challenge
- "Walkthrough mode" (list all the steps and their instructions, code, tests on a single page so that users can search with ctrl+F)
- Adding a "next step" and "previous step" next to the reset button to make it easier to navigate back and forth

## Additional context

The above ideas are from the contributors' chat https://chat.freecodecamp.org/channel/off-topic?msg=enhwnP9zj9QjGPmkf

**Comment by sidemt** [comment]
I personally want the search for the curriculum (not only for the project-based curriculum but for all of them) but it seems it has been removed for some reason in the past, so I don't want to underrate that decision. But I used it a lot as a learner.

**Comment by ShaunSHamilton** [comment]
> Adding a "next step" and "previous step" next to the reset button to make it easier to navigate back and forth

To mention: This functionality already exists as a shortcut.
- On a challenge, press `ESC` to unfocus the editor
- Press `n` to go to next challenge
- Press `p` to go to previous challenge

**Comment by sidemt** [comment]
Thanks @ShaunSHamilton I didn't know that. Is there any place users can know those shortcuts?

And @xoxoKaralee the above information may help you 🙂

**Comment by ShaunSHamilton** [comment]
> Is there any place users can know those shortcuts?

We were close to making this explicit: https://github.com/freeCodeCamp/freeCodeCamp/issues/39635

It was not a high priority for the curriculum. We could probably create a dedicated issue for this to implement something like: https://github.com/freeCodeCamp/freeCodeCamp/pull/38203

**Comment by sidemt** [comment]
I did some search too and found an open issue #36841 for shortcuts modal.

**Comment by naomi-lgbt** [comment]
Going to assign this to myself and play with the following plan:

- Attach a `topics` key to challenge frontmatter
- Use the currently orphaned [block pages](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/) to list the topics alongside the challenge list.

Long-term???:

- Add a `topics` component that lists *all* topics and the steps that teach them??

**Comment by devtahmid** [comment]
> To mention: This functionality already exists as a shortcut.
I'm trying the shortcuts on the new RWD steps but the shortcuts dont work. For example on this page - https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6 

Can you please confirm if it works? They're really helpful for ones who one to quickly see which step contains what (if the person has prior knowledge of the steps)

**Comment by ShaunSHamilton** [comment]
@devtahmid We recently disabled the shortcuts by default, and you need to enable them in the settings:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/51722130/185869041-fa9d148e-9681-4168-9388-90ff93e2cd25.png">

**Comment by moT01** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/48800
