### ISSUE TITLE
Waypoint: Reverse Arrays with reverse

### ISSUE THREAD

**Issue by Jereti** [FreeCodeCamp/FreeCodeCamp#4471]
Is there anything wrong with my code? I'm not getting a pass.
![reverse array](https://cloud.githubusercontent.com/assets/13770117/11178833/4402548c-8c47-11e5-8ee8-22dd18282108.png)

**Comment by Mansuro** [comment]
It's as simple as 
    var newArray = array.reverse();

**Comment by faizaanceg** [comment]
Please use the [Gitter chatroom](https://gitter.im/FreeCodeCamp/FreeCodeCamp) for programming queries

**Comment by ltegman** [comment]
both @Mansuro and @faizaanceg are correct.

Thanks and happy coding!

**Comment by Jereti** [comment]
Thanks, i've got it.
