### ISSUE TITLE
RWD Beta Rothko Painting lesson improvements

### ISSUE THREAD

**Issue by xoxoKaralee** [freeCodeCamp/freeCodeCamp#44716]
## Is your feature request related to a problem? Please describe.

It's my opinion that the RWD Beta Rothko painting lesson could be improved by changing the wording of many of the steps. Currently, many steps tell you exactly what to put. 

Example: 
```
Give the .frame a border with the shorthand border: 50px solid black; declaration.
```

## Describe the solution you'd like

Solutions that I would like include less handholding and more information that lets you practice what you've learned. And if it's the first time showing you code like this, an example of how the code is used.  

## Describe alternatives you've considered

The example above could be re-written `Using border shorthand, give the .frame a solid black border of 50px.`
Here is another good example of what steps could be written like:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-14

## Additional context

Pages that should be discussed:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-12
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-14
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-20
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-21
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-22
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-34
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-40
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-41

Pages that could use improvement or not.
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-15
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-28
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-38

**Comment by nhcarrigan** [comment]
I'd definitely be open to improving the descriptions on these. We can make them less explicit, to encourage campers to think about what they've learned a bit more.

We want to ensure the hint text remains clear, though, so campers are not stuck and lose the flow-state.

Assuming there are no objections, I'd be willing to open this up for `help wanted`. PRs could solve all of the files at once, or take them in chunks. @ShaunSHamilton since you did a 🚀, would love to hear your thoughts.

**Comment by ShaunSHamilton** [comment]
Yes, I agree - open this up for contribution. Provided the sentences can be short and clear enough, they should encourage Campers to think more. This should only be the case if they have previously encountered the syntax.

If a Camper gets stuck, then the hints should contain the explicit answer. _I doubt any of these will need to be changed_

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
