### ISSUE TITLE
Refactor Global Variables Out of Functions Strangeness

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#44721]
## Affected page

[Refactor Global Variables Out of Functions](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/refactor-global-variables-out-of-functions)

## Your code

This is the starter code:

```javascript
// The global variable
var bookList = ["The Hound of the Baskervilles", "On The Electrodynamics of Moving Bodies", "Philosophiæ Naturalis Principia Mathematica", "Disquisitiones Arithmeticae"];

// Change code below this line
function add (bookName) {

  bookList.push(bookName);
  return bookList;
  
  // Change code above this line
}

// Change code below this line
function remove (bookName) {
  var book_index = bookList.indexOf(bookName);
  if (book_index >= 0) {

    bookList.splice(book_index, 1);
    return bookList;

    // Change code above this line
    }
}

var newBookList = add(bookList, 'A Brief History of Time');
var newerBookList = remove(bookList, 'On The Electrodynamics of Moving Bodies');
var newestBookList = remove(add(bookList, 'A Brief History of Time'), 'On The Electrodynamics of Moving Bodies');

console.log(bookList);
```

## Expected behavior

The starter code for this challenge is strange.

1) Why the space between the function name and the ()s for the arguments?

2) I get that the idea is to have the learners change the function signature, but it is a bit strange having a mismatch between the function signatures and the function calls in the starter code.

**Comment by nhcarrigan** [comment]
The linked PR resolves #1 in this issue.

For #2, we could probably move away from having variables in the seed code and instead assert the function returns the expected value 🤔
