### ISSUE TITLE
Exercise Tracker microservices test broken

### ISSUE THREAD

**Issue by ankitkandari** [freeCodeCamp/freeCodeCamp#44730]
## Affected page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

## Solution link

https://replit.com/@ankitkandari/freecodecamp-exercisetracker

## Forum link

https://forum.freecodecamp.org/t/exercise-tracker-test-broken-for-date-to-be-string/491710

## Expected behavior

Test should be passed as no issue in data

## Failing test

The date property of any object in the log array that is returned from GET /api/users/:id/logs should be a string… Use the dateString format of the Date API.

Unable to pass this test.

Please help

**Comment by ankitkandari** [comment]
Exercise tracker test broken

**Comment by nhcarrigan** [comment]
Hi there, it looks like you successfully received guidance on your forum post.

We'll go ahead and close this issue. Making a forum post for questions about your code is the way to go 🙂
