### ISSUE TITLE
Typo in Lesson 10 in Learn Bash Scripting by Building Five Programs

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#44731]
## Affected page

In lesson 10 of Learn Bash Scripting by Building Five Programs, the directions tell you to use this command: `chmod +x questionnnaire.sh`.
But the command has added an extra `n` in  questionnaire.
The correct command should be `chmod +x questionnaire.sh`

## Screenshots

![Screen Shot 2022-01-09 at 1 42 10 AM](https://user-images.githubusercontent.com/67210629/148677117-c81a7ddb-d67f-46ad-b777-4d4a92868755.png)

**Comment by huyenltnguyen** [comment]
I'm going to mark this issue for first-time contributors.

Here is the file you should be looking at to work on a fix: https://github.com/freeCodeCamp/learn-bash-scripting-by-building-five-programs/blob/main/TUTORIAL.md#901

Please make sure you have read [our contribution guidelines](https://contribute.freecodecamp.org/#/). Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing!

**Comment by akshat-o5** [comment]
Can I work on this issue?

**Comment by akshat-o5** [comment]
Hello, I have worked on that issue and solved it. Also made the PR , please refer it.

**Comment by ieahleen** [comment]
@akshat-o5 please link this issue in the PR, otherwise they are not linked

**Comment by srkds** [comment]
Hello,

I am following guidelines 
- created a new branch
- installed coderoad v0.9.3
- committed changes on file TUTORIAL.md
- now running command ```coderoad build```
  and getting error 
```
Building CodeRoad tutorial.json...
Error loading commits:
Code branch "v1.0.1" not found
```

Please can anyone give any suggestions

**Comment by gikf** [comment]
The latest _version_ branch from the repository needs to exist locally:
```bash
git fetch upstream
git branch v1.0.1 upstream/v1.0.1
```

**Comment by srkds** [comment]
Mentioned PR.

**Comment by GoonerBrian** [comment]
I see this has been solved multiple times but I'm going to add to that as I complete my first contribution. Great documentation by the way! Super easy to setup my local environment!
