### ISSUE TITLE
RWD Beta: Tooltip in the editor should not be displayed

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#44735]
When you mouse over on a HTML tag in the editor, a tooltip will be displayed.
~~But when the tag is near the top of the editor area, the tooltip gets hidden by the header area.~~

## Affected page

Any of the new Responsive Web Design Beta page such as:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2

## To reproduce

1. Go to the link above
2. Mouse over on `<html>` or `<body>` tag in the editor
3. See the tooltip

## Expected behavior

~~The tooltip is not hidden~~ -> Don't show tooltips

## Screenshots

![new challenge](https://user-images.githubusercontent.com/25644062/148717245-e13f383d-5a3c-4c0c-bb05-2d78adee10dc.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 97.0.4692.71

## Additional context

This does not happen in the editor for the existing challenges
![existing challenge](https://user-images.githubusercontent.com/25644062/148717062-3a4ef0c5-16bc-4d49-819c-9eaafe1cac45.png)

**Comment by ShaunSHamilton** [comment]
Thank you, for opening this, Yoko.

@freeCodeCamp/dev-team Can we remember if the tooltip is supposed to show at all?

Personally, I am for the _further information_ tooltip (as shown above), but I cannot remember if we had discussed outright removing all extraneous UI features.

**Comment by ojeytonwilliams** [comment]
I don't remember discussing it, either, but I like having them.  If we leave them in for now, then we can see if users find them irritating or not.

**Comment by sidemt** [comment]
Actually, I didn't notice this tooltip until today, so I don't know when it was added. I thought it's just me didn't know that, but maybe not...

**Comment by ojeytonwilliams** [comment]
> the auto complete though

Yep, we discussed that and decided against it.

I was in favour of them, but you make a good point about them being distracting.  We want the learners to focus on the things we're trying to teach rather than some random element they happen to have moused over.

So, I guess I'm changing my vote to "stop showing the tooltips".

**Comment by nhcarrigan** [comment]
I'm also in favour of removing it.

**Comment by ojeytonwilliams** [comment]
Okay, no-one is in favour of keeping them, so I'm happy to open this up to contributions.

**Comment by sidemt** [comment]
I updated the title & description accordingly.
