### ISSUE TITLE
correction off var 

### ISSUE THREAD

**Issue by smadakcir** [FreeCodeCamp/FreeCodeCamp#4473]
# reagerding var starting form 0 
would var 0 be "L"
var 1 be "o"
and var 3 will be "v" instead of var 2 what is current var #3

 
challenge [Waypoint: Use Bracket Notation to Find the Nth Character in a String](http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nth-character-in-a-string?solution=var%20firstName%20%3D%20%22Ada%22%3B%0A%0Avar%20secondLetterOfFirstName%20%3D%20firstName%5B1%5D%3B%0A%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0Avar%20thirdLetterOfLastName%20%3D%20lastName%5B2%5D%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(v)%7Breturn%20v%3B%7D)(thirdLetterOfLastName)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var firstName = "futhere";

var secondLetterOfFirstName = firstName[1];

var lastName = "Lovelace";

var thirdLetterOfLastName = lastName[2];


// Only change code above this line.

(function(v){return v;})(thirdLetterOfLastName);

```

**Comment by ltegman** [comment]
I'm not seeing any issues with this waypoint.

Thanks and happy coding!
