### ISSUE TITLE
RWD Beta, Cat, Step 55: Possible bug at the hints

### ISSUE THREAD

**Issue by Etkesmeci** [freeCodeCamp/freeCodeCamp#44740]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-55

## Your code

```
<input id="loving" type="checkbox"><label for="loving"> Loving</label>
```

## Expected behavior

I believe the hint was supposed to be "The new label element should be located directly to the right of your checkbox. Make sure there is a space between the two elements." this.

## Screenshots

<img width="1440" alt="Ekran Resmi 2022-01-10 15 37 06" src="https://user-images.githubusercontent.com/96954609/148773554-24ec95a9-3aae-43f0-9ef8-7f892ef80282.png">
<img width="1440" alt="Ekran Resmi 2022-01-10 15 44 58" src="https://user-images.githubusercontent.com/96954609/148773567-1de562fa-3274-48c5-b2d0-53f929e71d09.png">

## System

- Device: MacBook Pro (13-inch, M1, 2020)
- OS: MacOS Monterey 12.1
- Browser: Chrome
- Version: 97.0.4692.71

**Comment by nhcarrigan** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/63889819/148834663-82012f89-4531-4ab9-875c-9151512f0fb4.png">

Looking at the initial seed code, the space is already there - it looks like the test assumes that wrapping the text means leaving the space alone.

**Comment by Etkesmeci** [comment]
So should “Make sure there is a space between the two elements.” be added to the hint I was given or was the hint given the wrong one?

**Comment by nhcarrigan** [comment]
I think that would be a good clarification, yeah. We want that space to be there as it affects the layout of the page.
