### ISSUE TITLE
Recursion impossible in freeCodeCamp console 

### ISSUE THREAD

**Issue by koouty** [FreeCodeCamp/FreeCodeCamp#4475]
Bonfire: Sum All Odd Fibonacci Numbers
I make a litle recursion to get the Fibonacci numbers and the console is blocked
In repl.it it''s run perfectly. What is the problem?
Here is the code.
```
function sumFibs(num) {
  if (num === 1 || num === 0) {return 1;}
  else {return sumFibs(num - 2) + sumFibs(num - 1);}
}
sumFibs(4);
```

**Comment by ltegman** [comment]
I'll copy my response from the other thread:

>@koouty I know recursion is a popular way to solve the fibonacci problem, but it's an incredible inefficient solution in Javascript. Function calls in javascript are VERY slow, so once you start doing test cases like FCC has (1000+) your recursive solution is orders of magnitude slower than using a while loop. Check out what happens when you toss your solution into a repl with some of the large number test cases and you'll see what I'm talking about.

>You might be able to make the resursive solution work by implementing memoization, but you'd just be putting a bandage over the issue and it still probably won't be fast enough for the larger test cases.

Recursion is possible in the challenges, but if the solution is too slow it will look like an infinite loop.

Closing as not an issue.

**Comment by koouty** [comment]
@ltegman Thank's
