### ISSUE TITLE
Typos in RDB student database part 1 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#44759]
## Affected page
Here is the lesson with the typo.
https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-1/blob/main/TUTORIAL.md#840-add-course_id

It currently says "Next is the courses. "
But I think it would be better to say "Next are the courses. " or "Now we are going to work on the courses".
Or something along those lines.

Also found this typo here
https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-1/blob/main/TUTORIAL.md#910-add-insert_majors_courses_result

It currently says "Also, you won't need and quotes " but it should be "Also, you won't need any quotes"

**Comment by nhcarrigan** [comment]
Hey @moT01 is this something we could open up for contribution?

**Comment by mhblatch** [comment]
Hi, I would love to handle these typos!

**Comment by jdwilkin4** [comment]
Hi @mhblatch ! 

This issue has the help wanted label so you are free to work on it.
Make sure to read through the [contributing docs](https://contribute.freecodecamp.org/#/index) and the section on how to contribute to [lessons using coderoad](https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad). 
Let us know if you have any questions.
