### ISSUE TITLE
Safari bug - RWD Beta - step 43 - Learn Typography by building a Nutrition Label 

### ISSUE THREAD

**Issue by marks1974** [freeCodeCamp/freeCodeCamp#44754]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-43

## Your code

```

<p>Saturated Fat 1g <span class="bold right">5%</span></p>


```

## Expected behavior

I cannot get past this step using Safari 15.2 on Mac OS 12.1. I have checked the same lesson in Firefox and the same code gets marked as correct. However, in Safari it just keeps saying my code is wrong. I have not had any other issues in Safari.

## Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/13849426/149038022-e8092f37-8434-4154-89e9-250721d9d032.png)
![screenshot_142](https://user-images.githubusercontent.com/13849426/149038246-f19b0fe6-a771-4b41-8c7f-cfa94423536d.png)

## System

Safari 15.2 on Mac OS 12.1.
- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by moT01** [comment]
I can confirm this issue

**Comment by marks1974** [comment]
I have found another bug like this one in step 65 which asks for the following code to be entered:

```
* {
  scroll-behavior: smooth;
}
```

It won't pass in Safari but passes without any issues in Firefox.

![screenshot_145](https://user-images.githubusercontent.com/13849426/149673970-0d664d47-f2cd-476c-aad4-479ad098debd.png)


![screenshot_146](https://user-images.githubusercontent.com/13849426/149674013-84c70ec7-93f1-4429-90c9-6636c4b32045.png)

**Comment by moT01** [comment]
The problem with step 43 - the test:
`assert(document.querySelector('.daily-value.sm-text')?.lastElementChild?.previousElementSibling?.innerText.match(/Total Fat 8g[\s|\n]+10%/));`

Checks the `innerText` of the `previousSibling`. Safari renders it as:
![Screen Shot 2022-01-20 at 1 50 51 PM](https://user-images.githubusercontent.com/20648924/150412338-a96feec3-dc4c-4cf6-89b6-ac718b16c556.png)

Firefox puts a new line:
<img width="98" alt="Screen Shot 2022-01-20 at 1 57 08 PM" src="https://user-images.githubusercontent.com/20648924/150412662-e836c1dd-f189-4c89-9165-6b3ca2895672.png">

Chrome must have a space or new line or something. We can change the test to this for a fix:
`assert(document.querySelector('.daily-value.sm-text')?.lastElementChild?.previousElementSibling?.innerText.match(/Total Fat 8g[\s|\n]*10%/));`

^ Changed `+` to `*` at the end of the regex

**Comment by moT01** [comment]
For step 65 - Safari doesn't support [scoll-behavior](https://caniuse.com/?search=scroll-behavior). I think we have [a helper function](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/utils/css-help.ts#L95) that can the values in the stylesheet or something that might work here. Otherwise, maybe resort to regex.

**Comment by sstonaker** [comment]
Is it ok to piecemeal this?

I can do a fix for the typography lesson, but the scroll behaviour (step 65) is in another lesson - learn accessibility by building a quiz.

**Comment by moT01** [comment]
I made a dedicated issue for the remaining problem described here so we can close this. Thanks and happy coding 🎉
