### ISSUE TITLE
Cert Projects: Changing wording for ease of translation

### ISSUE THREAD

**Issue by Etkesmeci** [freeCodeCamp/freeCodeCamp#44760]
## Is your feature request related to a problem? Please describe.
While I was trying to translate <a href="https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-personal-portfolio-webpage-project/build-a-personal-portfolio-webpage"> build a personal portfolio webpage</a> to Turkish this came to my mind. 

Just to mention, we try to avoid the combination of code-block and non-code-block words as much as possible, because it is difficult for translators to translate:
> ...`section`'s ...

Instead, we should be going for:
> ... `section` element's ...

_Originally posted by @ShaunSHamilton in https://github.com/freeCodeCamp/freeCodeCamp/pull/44704#discussion_r780235798_ 

## Describe the solution you'd like
For example should "User Story #1: My portfolio should have a welcome section with an id of `welcome-section`." be changed to "User Story #1: My portfolio should have a welcome section with an id attribute of `welcome-section`." I haven't added element after "section" as in this context it was probably plain English. 

## Describe alternatives you've considered
I could also translate it to Turkish as if it was like that in English.

## Additional context
I am sorry if this is the wrong place to discuss this.

**Comment by Etkesmeci** [comment]
I was also going to ask whether changing this "Or you can use this CDN link to run the tests in any environment you like: https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js" to "Or you can use <a href="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js">this CDN link</a> to run the tests in any environment you like." this would be more consistent as the previous sentence was "You can build your project by <a href='https://codepen.io/pen?template=MJjpwO' target='_blank' rel='nofollow' mark="crwd-mark">using this CodePen template</a> and clicking <code>Save</code> to create your own pen."

**Comment by ShaunSHamilton** [comment]
For the most part, I recommend we not change anything with the user stories or wording on the current certification, because most of this will be changing with: https://github.com/freeCodeCamp/freeCodeCamp/pull/44564

**Comment by Etkesmeci** [comment]
I see, sorry for bothering you guys with minor details.
