### ISSUE TITLE
Improve project blocks on new curriculum superblock pages?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#44767]
I was looking at the new curriculum, the certification projects blend in with the rest of the projects pretty good. I played around with it in the dev tools real quick and came up with this:
![Screen Shot 2022-01-10 at 8 32 22 AM](https://user-images.githubusercontent.com/20648924/149182906-0344239e-ec11-4dcb-b764-fbe48b41f1b3.png)

Wondering if we should do something to distinguish the cert projects from the rest of the blocks. It doesn't have to look like the image.

**Comment by ShaunSHamilton** [comment]
YES! I vote for that, **and** adding the word "Certification" before the word `Project`.

**Comment by nhcarrigan** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/63889819/149418650-a2b979b9-4f26-469d-b88c-0c11aea145c4.png">

**Comment by ahmadabdolsaheb** [comment]
We could replace the first sentence "This project is a requirement ..." with a tag to make it stand out.
Also experimenting with different icons and backgrounds is an option.

<img width="789" alt="Screen Shot 2022-01-14 at 9 56 11 AM" src="https://user-images.githubusercontent.com/4591597/149464614-49038f19-814d-4162-823c-72619e8559b3.png">
