### ISSUE TITLE
Typo in Learn SQL Student Database course part 2

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#44772]
There is a missing word in the directions here.
In your student info script, add echo statement at the bottom like the other to print the results of the suggested query.

The word "an" should be added before echo statement.
Fix: add an echo statement...

This is an easy fix, so I have added the first timers only label.
Here is the file you need to fix:
https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-2/blob/main/TUTORIAL.md#16901

Please make sure you have read our [contribution guidelines](https://contribute.freecodecamp.org/#/). 
You will also need to read through the guidelines on [how to contribute to tutorials with CodeRoad](https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad). 
Join us in our [chat room](https://chat.freecodecamp.org/channel/contributors) or the [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by spandanghosh** [comment]
Bug fixed according to requirement
