### ISSUE TITLE
The server could not be reached and your progress may not be saved. Please contact support if this message persists

### ISSUE THREAD

**Issue by youngwitty** [freeCodeCamp/freeCodeCamp#44787]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ieahleen** [comment]
as it is about your personal account you will neep to contact support@freecodecamp.org

You have not given enough infos here to be able to help. I am closing this issue.
