### ISSUE TITLE
Suggested edit for step 18 in Learn basic CSS by Building a Cafe Menu project in Responsive Web Design(Beta)

### ISSUE THREAD

**Issue by deniselemonaki** [freeCodeCamp/freeCodeCamp#44782]
## Affected page

The prompt currently says:

"So the styling of the page looks similar on mobile as it does on a desktop or laptop, you need to add a meta element with a special content attribute."

I think it it makes more sense to say:

"For the styling of the page to look similar on mobile as it does on a desktop or laptop, you need to add a meta element with a special content attribute."

Here is the link to the lesson:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-018.md

## Screenshots
<img width="688" alt="Screenshot 2022-01-14 at 6 07 51 PM" src="https://user-images.githubusercontent.com/51991217/149547340-c1ea9f3a-4882-48b9-abf1-70f851c68ab3.png">

**Comment by SaarthakMaini** [comment]
@deniselemonaki #44799 This is my pull request is it correct?
