### ISSUE TITLE
RWD Beta:  Grid Magazine section Step 24

### ISSUE THREAD

**Issue by Kernix13** [freeCodeCamp/freeCodeCamp#44796]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-grid-by-building-a-magazine/step-24

## Your code

```
src="https://cdn.freecodecamp.org/testable-projects-fcc/images/survey-form-background.jpeg"
            alt="four people working on code"
            loading="lazy"
            class="image-3"
            width="600"
            height="400"
```

## Expected behavior

I expected it to pass. I also tried:
```
<img src="https://cdn.freecodecamp.org/testable-projects-fcc/images/survey-form-background.jpeg"
            alt="four people working on code"
            loading="lazy"
            class="image-3"
            width="600"
            height="400" />
```
I even went to step 25 and copied/pasted the complete tag from that lesson and it failed. It wasn't clear if I should add `<img` and ` />` or not. You can see the empty `img` tag above the instructions. But the error message was always:

> Your third img element should have a src set to https://cdn.freecodecamp.org/testable-projects-fcc/images/survey-form-background.jpeg.

## Screenshots

![grid-magazine-24](https://user-images.githubusercontent.com/66497948/149640555-7fcc8ec3-1cea-4e54-9407-8d5a2994f278.PNG)

## System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [brave]
- Version: [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)]

**Comment by jdwilkin4** [comment]
Hi @Kernix13 ! 

I was able to pass with the following code
<img width="720" alt="Screen Shot 2022-01-15 at 9 09 32 PM" src="https://user-images.githubusercontent.com/67210629/149648121-e9cab86b-cd5c-4410-83a6-2aee97a63468.png">
I think the issue is that people don't realize that with this new editor, you can edit other lines of the html file like on line 154.
I guess a possible solution would be to edit line 154 to be the following: ` <img `and then users would just have to finish out the rest of that image tag. 
```
src="https://cdn.freecodecamp.org/testable-projects-fcc/images/survey-form-background.jpeg"
alt="four people working on code"
loading="lazy"
class="image-3"
width="600"
height="400"/>
```

**Comment by gikf** [comment]
Easier might be just including the whole `<img />` in the editable region at the start.

**Comment by Kernix13** [comment]
Ok, I tried it exactly as you have it with nothing on lines 155 and 162 AFTER removing ` />`, also with the code starting on 155 and having the code end on line 160 which also worked. I think it would be best to either:

- have the user enter the entire `img` tag (with `<img />` removed from line 154), or 
- have `<img ` on line 154 and the closing ` />` on the first line following the editor

Is that something that I should do? I can go into Step 24 and edit the HTML for either scenario. I tested both ways of my bullet points and passed both times.

**Comment by jdwilkin4** [comment]
If we add the entire `img` tag in the editable part, then we might consider altering the text to say create a third `img` element instead of give your third `img` element. 

>Is that something that I should do? 

Any issue that is marked with a help wanted label is up for grabs. 
You are free to make a PR.
But also, more people will probably comment on the issue with their two cents after the weekend.

**Comment by Kernix13** [comment]
Ok, so should I just go ahead and do that? Since all three `img` tags were created a few steps prior, I think it would make sense to remove the closing part of the tag from above the editor and add it below the editor. However, what is actually doing the tests, checking what was entered? Wouldn't that have to be updated as well? Is it JavaScript? Does the code for that check need to be changed to recognize the change in the HTML above and below the editor?

**Comment by gikf** [comment]
I'd consider just moving editable region, to contain `<img />`. This requires adjusting just single step and keeps consistent with previous steps. Adding `img` in this step would need removing it from previous steps. Similarly if editable region would be added inside of `<img` `/>`, some previous steps might need changing to keep it consistent.

Tests are using code below each hint in the `--hints--`, in this case none would require changing.

**Comment by Kernix13** [comment]
Done - moved it to be between the `--fcc-editable-region` lines and pushed the change.
