### ISSUE TITLE
Exercise Tracker Challenge - Code with incorrect functionality passes tests

### ISSUE THREAD

**Issue by c-ehrlich** [freeCodeCamp/freeCodeCamp#44806]
## Affected page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

### The backend route that passes FCC tests despite not working correctly (see comments)
```js
app.get("/api/users/:_id/logs", (req, res) => {
  // get user id from params and check that it won't break the DB query
  const { _id } = req.params;
  if (_id.length !== 24) {
    return res.json({ error: "User ID needs to be 24 hex characters" });
  }

  // find the user
  getUserByIdAnd(_id, (userObject) => {
    if (userObject === null) res.json({ error: "User not found" });
    else {
      const limit = req.query.limit ? req.query.limit : 0;

      // /!\ NOTE `limit` is being applied here BEFORE `from` and `to`
      let promise = ExerciseActivity.find({ user_id: _id }).limit(limit).exec();
      assert.ok(promise instanceof Promise);
      promise.then((exerciseObjects) => {
        // /!\ NOTE `limit` has already been applied at this point, so only
        // the truncated array of exercises will be filtered by `from` and `to`
        if (req.query.from) {
          const from = new Date(req.query.from);
          exerciseObjects = exerciseObjects.filter(
            (e) => new Date(e.date).getTime() >= from.getTime()
          );
        }
        if (req.query.to) {
          const to = new Date(req.query.to);
          exerciseObjects = exerciseObjects.filter(
            (e) => new Date(e.date).getTime() <= to.getTime()
          );
        }
        exerciseObjects = exerciseObjects.map((e) => ({
          ...e,
          date: new Date(e.date).toDateString(),
        }));

        res.json({
          _id: userObject._id,
          username: userObject.username,
          count: exerciseObjects.length,
          log: exerciseObjects,
        });
      });
    }
  });
});
```

#### All exercises for this user
`GET /api/users/61e5689b039759356d4f6a51/logs`
```json
{
  "_id": "61e5689b039759356d4f6a51",
  "username": "cehrlich",
  "count": 6,
  "log": [
    {
      "description": "Jogging",
      "duration": 30,
      "date": "Wed Jan 12 2022"
    },
    {
      "description": "Weights",
      "duration": 60,
      "date": "Mon Jan 11 2021"
    },
    {
      "description": "Climbing",
      "duration": 25,
      "date": "Tue Jan 11 2022"
    },
    {
      "description": "Tennis",
      "duration": 45,
      "date": "Wed Dec 15 2021"
    },
    {
      "description": "Basketball",
      "duration": 25,
      "date": "Sat Feb 12 2022"
    },
    {
      "description": "Swimming",
      "duration": 15,
      "date": "Thu Jan 13 2022"
    }
  ]
}
```

#### Exercises for this user from January 2022 - Note there are three of them
`GET /api/users/61e5689b039759356d4f6a51/logs?from=2022-01-01&to=2022-01-31`
```json
{
  "_id": "61e5689b039759356d4f6a51",
  "username": "cehrlich",
  "count": 3,
  "log": [
    {
      "description": "Jogging",
      "duration": 30,
      "date": "Wed Jan 12 2022"
    },
    {
      "description": "Climbing",
      "duration": 25,
      "date": "Tue Jan 11 2022"
    },
    {
      "description": "Swimming",
      "duration": 15,
      "date": "Thu Jan 13 2022"
    }
  ]
}
```

#### Limiting the results to 2 only returns 1 - This is because the query was limited to the first two objects ("Jogging" and "Weights") _before_ the `from` and `to` filters are applied
`GET /api/users/61e5689b039759356d4f6a51/logs?from=2022-01-01&to=2022-01-31&limit=2`
```json
{
  "_id": "61e5689b039759356d4f6a51",
  "username": "cehrlich",
  "count": 1,
  "log": [
    {
      "description": "Jogging",
      "duration": 30,
      "date": "Wed Jan 12 2022"
    }
  ]
}
```

## Expected behavior

The Challenge requirements state:
> You can add from, to and limit parameters to a GET /api/users/:_id/logs request to retrieve part of the log of any user. from and to are dates in yyyy-mm-dd format. limit is an integer of how many logs to send back.

The above code / functionality should not pass the test.

## System

(this is an issue with the tests so it will be the same for any client device, but I'm using:)
- Device: MacBook Air (Late 2020)
- OS: MacOS 12.1
- Browser: Chrome
- Version: 97

## Additional context

If you believe the tests should catch this, I would be happy to rewrite the relevant test and create a Pull Request for it.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this.

I follow what you are saying until here:
> Limiting the results to 2 only returns 1 - This is because the query was limited to the first two objects ("Jogging" and "Weights") before the from and to filters are applied

Would you mind clarifying how the query limits based on "Jogging" and "Weights"?

---

I see the response does not match the query, but I cannot see any other filter for:

```
GET /api/users/61e5689b039759356d4f6a51/logs?from=2022-01-01&to=2022-01-31&limit=2
```

**Comment by c-ehrlich** [comment]
Thanks for the response :) Maybe my example was unnecessarily complicated. 

Imagine a user with these exercises:
```json
"log": [
    {
        "description": "Exercise 1"
        "date": "Tue Jan 18 2022"
    },
    {
        "description": "Exercise 2"
        "date": "Thu Jan 20 2022"
    }
]
```
Now imagine a project/solution that applies `limit` before `from` and `to`. For a query for `GET /api/users/foo/logs?from=2022-02-19&to=2022-02-21&limit=1`, this server would return 0 objects.

This is because it would first apply `limit=1`, so now all that's left is Exercise 1. Then it checks whether any of the remaining exercises (only Exercise 1) matches `from=2022-02-19&to=2022-02-21`, which it does not.

I believe that this behaviour should fail the tests, but it does not. 

The current tests do the following:
- add an exercise with a date of 1990-01-01
- add an exercise with a date of 1990-01-02
- assert 1: get user data between 1989-12-31 and 1990-01-03, no limit, should return 2 exercises
- assert 2: get user data from any time span, limit 1, should return 1 exercise

So they don't test whether `from/to` and `limit` work correctly when applied at the same time.

**Comment by nhcarrigan** [comment]
Probably wouldn't hurt to add a test that checks both at once. 👍🏻

**Comment by moT01** [comment]
I would be fine with fixing this test. @c-ehrlich seems willing to make a PR - so why not. I think we would accept one if you want to do that @c-ehrlich 👍 Thanks
