### ISSUE TITLE
Incorrect links on Contribute page 

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#44808]
## Affected page

https://contribute.freecodecamp.org/#/index?id=translations

## To reproduce

The Italian and Portuguese curriculum links in the "Translations" section are both pointing to the Spanish page.

## Recommended fix, suggestions

- Change the Italian link to https://www.freecodecamp.org/italian/learn 
- Change the Portuguese link to https://www.freecodecamp.org/portuguese/learn/
- The file that needs to be updated: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/index.md#translations

**Comment by huyenltnguyen** [comment]
This issue is open for first-time contributors only.

Please make sure you read [our contribution guidelines](https://contribute.freecodecamp.org/#/). Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing!

**Comment by UrviSinghal28** [comment]
Hi fixed this issue #44809
