### ISSUE TITLE
Wrong object properties on JS Curriculum

### ISSUE THREAD

**Issue by juanalbglz** [freeCodeCamp/freeCodeCamp#44813]
## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-bracket-notation

## Expected behavior
Show actual object structure

## Screenshots
![image](https://user-images.githubusercontent.com/2136913/149846506-810cb772-bde1-4818-9375-c70b1cd6d923.png)

## System

- Device: Desktop
- OS: W10
- Browser: Brave
- Version: 1.34.80

## Additional context
The object information shown represents the previous lesson:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-dot-notation

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this.

This is an interesting bug. @ojeytonwilliams Any immediate ideas?

**To Reproduce**
1) Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-dot-notation
2) Complete and submit challenge
3) Hover over the call to the `testObj` variable on line `9` or `10`

**Comment by gikf** [comment]
It's not needed to submit or complete challenge. `Esc` + `n` or `p` will reproduce it too, also over multiple challenges, ie:
1. https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-dot-notation.
2. `Esc` + `n` + `n`.
3. Hovering over `testObj` on line `10` will show properties from dot notation challenge.

**Comment by moT01** [comment]
I vote to hide that helper box.

**Comment by ojeytonwilliams** [comment]
True, we did discuss that.  I'll hold off trying to fix this until we decide.

**Comment by nhcarrigan** [comment]
Is this still an issue? I can't get the hover box to show up at all.

**Comment by gikf** [comment]
Kind of, as #44949 disabled hover by default, but it still can be shown from palette:
- Move keyboard cursor on variable name.
- Open palette - `F1`
- Pick `Show hover` or `Show Definition Preview Hover`.

**Comment by nhcarrigan** [comment]
Do we need the command palette?

**Comment by ojeytonwilliams** [comment]
I think so, yeah.  Otherwise it's hard for users that rely on the keyboard to find out the shortcuts.

Regardless, I think this particular issue is resolved - it's sufficiently hidden to not be annoying.
