### ISSUE TITLE
Minor typo in javascript-algorithms-and-data-structures > object-oriented-programming > understand-own-properties

### ISSUE THREAD

**Issue by Roburlion** [freeCodeCamp/freeCodeCamp#44828]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/understand-own-properties
## To reproduce

There is a typo in one of the code blocks.  There is an extra space in the following line between "name" and "=":

this.name  = name;
## Recommended fix, suggestions

Remove the extra space.

## Screenshots
![Screenshot 2022-01-18 180915](https://user-images.githubusercontent.com/94622793/150039011-22185b67-5e72-4367-81fd-5fbccbfde02b.png)

**Comment by Palakash27** [comment]
Hey, can I take this one??

**Comment by Roburlion** [comment]
Yes, go for it!

Sorry I didn't get back to you sooner. It's been a hectic day.

**Comment by Palakash27** [comment]
No worries. I have fixed this issue ☺️☺️
