### ISSUE TITLE
Suggestion: Wider context for code in RWD Beta

### ISSUE THREAD

**Issue by WaterBloom** [freeCodeCamp/freeCodeCamp#44827]
In RWB, the placement of the instructions interrupts the code and makes indentation unclear, especially for a beginner that may not know what to look for yet.

I noticed several instances where putting longer, uninterrupted part of the code in the highlighted editor might help with clarity.

<h2>Examples</h2>

<a href="https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-21">Step 21</a>: change the error message or expand the highlighted code. (Error message when h3 is in the wrong location: _"There should be an h3 element right above the second section element's closing tag."_)

<a href="https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-23">Step 23</a>: include `figure` in highlighted editor to match the instructions _("A figure caption (figcaption) element is used to add a caption to describe the image contained withing the figure element.")_ and to show the placement of `figcaption` within `figure`.

<a href="https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-50">Step 50</a>: include `fieldset` in highlighted editor to match the instructions _("The legend element acts as a caption for the content in the fieldset element.")_ and to show the placement of `legend` within `fieldset`.

<h2>Proposed solutions</h2>

- Expand the code on case-per-case basis.
- Permanently move the instructions box on top of the code editor. (I think that would make everything clearer and more accessible with well defined sections on the page, but I imagine it would be harder to implement now.)

**Comment by nhcarrigan** [comment]
> Permanently move the instructions box on top of the code editor. (I think that would make everything clearer and more accessible with well defined sections on the page, but I imagine it would be harder to implement now.)

I don't believe we would go this route, as the instructions UI was specifically designed to allow us to highlight the section of code a camper should be editing. I do agree some of these regions could be tweaked a bit 🙂

**Comment by WaterBloom** [comment]
> I don't believe we would go this route, as the instructions UI was specifically designed to allow us to highlight the section of code a camper should be editing. I do agree some of these regions could be tweaked a bit 🙂

Thank you for reading through it! I will admit I added that secondary suggestion because of a personal issue as well, as I find the page a bit overwhelming and every time I click on the next step, it takes me a while to find and re-focus on the editor. I think there's just a lot going on visually, but I'm not a UI/UX designer so I don't have specific suggestions except for the fixed placement.

**Comment by moT01** [comment]
I'm fine with changing the three lessons mentioned here, but we could maybe use a discussion on how those regions should be. There's probably going to be many steps where the editable region could be bigger or smaller or different. Maybe we need some hard rules on how to apply them. Something like - for HTML steps, include the parent element in the region. For CSS steps, include the whole selector.

There may be instances where rules like that don't work out so well. Like for the first steps of the Cat Photo project, we may want to be more specific about where to add code - and on later steps or projects, more vague. So I don't know.

**Comment by ShaunSHamilton** [comment]
> Maybe we need some hard rules on how to apply them. Something like - for HTML steps, include the parent element in the region. For CSS steps, include the whole selector.

I did bring this up, but we were on the fence with:

> I don't think you can have a hard and fast rule here. It really depends on what is being asked of the user. There are times when even though you may be having the user do something new, that you still have to expand the editable region based on the existing project structure. This was especially true with the basic cat photo app and will probably be the case with the JavaScript projects.

**Comment by nhcarrigan** [comment]
Yeah it seems like something that's more of a case-by-case basis than to have hard and fast rules for.

My proposed "general" approach would be to encapsulate anything the instructions mention. So if the instructions say "write a h2 below your h1", the h1 should be within the editable region.

**Comment by ahmadabdolsaheb** [comment]
Thank you @WaterBloom for reporting this issue.

> Thank you for reading through it! I will admit I added that secondary suggestion because of a personal issue as well, as I find the page a bit overwhelming and every time I click on the next step, it takes me a while to find and re-focus on the editor. I think there's just a lot going on visually, but I'm not a UI/UX designer so I don't have specific suggestions except for the fixed placement.

An easy fix would be to scroll the editor so the instructions are always almost at the top of the "page". That way the eyes know where to go on each challenge. (right now it scrolls to the center)

I am interested in knowing more about this: " it takes me a while to find and re-focus on the editor." Are you having difficulty locating the instructions? do also look around for the tests and the submit button? More context is appreciated.

We ultimately need to usability test this with people who have not seen the curriculum.

**Comment by WaterBloom** [comment]
@ahmadabdolsaheb Hello, sorry for the late reply.

> I am interested in knowing more about this: " it takes me a while to find and re-focus on the editor." Are you having difficulty locating the instructions? do also look around for the tests and the submit button? More context is appreciated.

After seeing this notification, I opened the curriculum on a random step to see if I could provide you with more information. I mostly forgot how the page was structured and my eyes just ran across the page in no specific order. "Check your code" was the first text I read, as it draws the most attention, and then "index.html".

> An easy fix would be to scroll the editor so the instructions are always almost at the top of the "page". That way the eyes know where to go on each challenge. (right now it scrolls to the center)

I believe that would be very helpful!

(I think it would also be nice if the navigation breadcrumbs were more subtle, and if the buttons like "index.html", "style.csss" and "preview" looked more like toggle buttons – now they remind me of tabs but disconnected from their sections, and they also draw more attention than is perhaps needed?)

Thank you for checking in on this!

**Comment by ahmadabdolsaheb** [comment]
Thank you for your feedback.
