### ISSUE TITLE
Error with step 36 of the Learn HTML by Building A Cat Photo App in the Beta RWD

### ISSUE THREAD

**Issue by realandrew** [freeCodeCamp/freeCodeCamp#44831]
## Affected page

[https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-36](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-36)

## Expected behavior

Step 36 says

> Like anchor ( a ) elements, input elements are self-closing and do not need closing tags.

However this is false, anchor tags are not self-closing. I believe it meant to say `img` which is the self-closing tag introduced in the previous steps.

## Screenshots

![](https://aws1.discourse-cdn.com/freecodecamp/original/3X/0/c/0cb063c5714172bf52a2ba7335c198f8dfc93bb4.png)

## Additional context

Wasn't sure where to report this so I also posted about it on the forums at [https://forum.freecodecamp.org/t/responsive-web-design-beta-error-on-step-36-of-learn-html-by-building-a-cat-photo-app/493214](https://forum.freecodecamp.org/t/responsive-web-design-beta-error-on-step-36-of-learn-html-by-building-a-cat-photo-app/493214).

**Comment by JayNewbie** [comment]
Good eye!

**Comment by jdwilkin4** [comment]
Hi @realandrew ! 

Thank you for bringing up this issue.
This is an easy fix to change anchor elements to img elements.
I have added the first timers only label for those who are interested in making their first PR.

**Comment by jbarryfl** [comment]
Could I take this issue? I'm looking for a good first contribution.

**Comment by jdwilkin4** [comment]
Hi @jbarryfl ! 

Any issue with the first timers only label is up for grabs.
The first PR that has the correct changes will be reviewed and merged into the main codebase. 
Here is the file that needs changing.
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/step-036.md

Happy contributing !
