### ISSUE TITLE
Geo-location deprecation notice on insecure origins

### ISSUE THREAD

**Issue by adibradfield** [FreeCodeCamp/FreeCodeCamp#4484]
Challenge [Zipline: Show the Local Weather](http://www.freecodecamp.com/challenges/zipline-show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Google Chrome has started showing a deprecation notice when using geo-location on an insecure origin, meaning that this Zipline will soon not be able to be completed using Codepen. I am sure that other browsers will follow suit, as this deprecation has come due to future W3C specs.

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

![image](https://cloud.githubusercontent.com/assets/12462105/11195462/fba5a8a2-8ca9-11e5-85cb-c99da59417fe.png)

**Comment by ltegman** [comment]
This warning notice goes away if you use the https version of codepen, so this won't be a blocking issue.

Thanks and happy coding!

**Comment by wsabol** [comment]
In Chrome, even if you try to use the https version of codepen, it still doesn't work. The geolocation is still blocked, and I'm getting this message: 

"Mixed Content: The page at 'https://s.codepen.io/wsabol/fullpage/gPrmpG?' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.wunderground.com/api/conditions/q/29.9688,-96.8637.json'. This request has been blocked; the content must be served over HTTPS."
