### ISSUE TITLE
boilerplate-advancednode: `npm i` fails on Apple Silicon because of incompatible Node version

### ISSUE THREAD

**Issue by c-ehrlich** [freeCodeCamp/freeCodeCamp#44867]
Note: I'm opening this issue here as it doesn't seem to be possible to open issues on the `boilerplate-advancednode` repository.

## Affected page

https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/set-up-a-template-engine
https://github.com/freeCodeCamp/boilerplate-advancednode/

## Your code

Running `npm i` on an Apple Silicon Mac results in the following error:

```
npm ERR! code 1
npm ERR! path /Users/ce-dev/Documents/dev/courses/freecodecamp-projects/06 Quality Assurance/boilerplate-advancednode/node_modules/node
npm ERR! command failed
npm ERR! command sh -c node installArchSpecificPackage
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for node-darwin-arm64@12.18.0.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/ce-dev/.npm/_logs/2022-01-21T14_43_20_296Z-debug.log
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'node-darwin-arm64/package.json'
npm ERR! Require stack:
npm ERR! - /Users/ce-dev/Documents/dev/courses/freecodecamp-projects/06 Quality Assurance/boilerplate-advancednode/node_modules/node/installArchSpecificPackage.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
npm ERR!     at ChildProcess.<anonymous> (/Users/ce-dev/Documents/dev/courses/freecodecamp-projects/06 Quality Assurance/boilerplate-advancednode/node_modules/node-bin-setup/index.js:18:27)
npm ERR!     at ChildProcess.emit (node:events:390:28)
npm ERR!     at maybeClose (node:internal/child_process:1064:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/ce-dev/Documents/dev/courses/freecodecamp-projects/06 Quality Assurance/boilerplate-advancednode/node_modules/node/installArchSpecificPackage.js'
npm ERR!   ]
npm ERR! }
```

This is because `node@12.18.0`, which is listed as a dependency, does not run on Apple Silicon.

## Expected behavior

Users should be able to install dependencies.

## System

- Device: MacBook Air M1
- OS: MacOS 12.1
- Browser: n/a

## Additional context

Changing the dependencies to the following fixes the problem. 

```json
"dependencies": {
  "dotenv": "^8.2.0",
  "express": "^4.16.1",
  "mongodb": "^3.6.1",
  "node": "^17.3.1"
},
```

Everything still seems to work as I was able to pass the first challenge ("Set up a Template Engine") with these packages, but I have not done any testing beyond "seems to works on my system and on Heroku".

**Comment by nhcarrigan** [comment]
We should not be pinning node to version 17, IMHO.

odd-numbered releases are like "staging" releases, used for 6 months to allow developers to work with new features. Even numbered releases are stable releases and have LTS.

Node.js 16, however, does have Apple Silicon support AFAIK.

**Comment by nhcarrigan** [comment]
@ojeytonwilliams We migrated the example projects to node 16, should we do the same for the boilerplates?

**Comment by c-ehrlich** [comment]
With the dependencies:
```json
"dependencies": {
    "dotenv": "^8.2.0",
    "express": "^4.16.1",
    "mongodb": "^3.6.1",
    "node": "^16.13.2"
},
```
`npm i` fails on node v16.14.0 (npm v8.3.1), but succeeds on node v14.18.3 (npm v6.14.15). Both are running through nvm on Apple Silicon. I already tried a clean install of node v16.14.0, but that didn't change anything. Full log of the failed install on node v16.14.0 is attached.

Completely removing `node` from the dependencies also works (dependencies install and server can be started), and this is what boilerplate-mongomongoose and the projects for the cert do, but I also understand the benefit of requiring a specific node version.

I'm not very knowledgeable about node and package management so I don't know how to give any more useful feedback than this, but happy to try anything someone suggests if it might help getting the project to install easily for other campers.

[2022-02-15T20_50_26_538Z-debug-0.log](https://github.com/freeCodeCamp/freeCodeCamp/files/8074542/2022-02-15T20_50_26_538Z-debug-0.log)

**Comment by ojeytonwilliams** [comment]
It seems there can be issues installing node on certain [macs](https://stackoverflow.com/questions/68896696/having-trouble-installing-npm-on-mac-m1).  There are workarounds in that link.

What should we do?  Well, ideally we should *recommend* a specific node version, but not *require*  it, since we can't test in all environments.  In cases like this, where there's an incompatibility, strictness seems unhelpful.

So, `engines` seems useful, but `engine-strict` does not.

**Comment by c-ehrlich** [comment]
As far as I can tell boilerplate-advancednode is the only boilerplate that has node in the `requirements` at all.

Since this is the second boilerplate of the QA cert, and most people will already have done the API cert before that, it seems reasonable to assume that people who want to do the course on their own computer will have installed node either through binary or nvm by this point. I also didn't run into any issues running the boilerplate-advancednode with node 14, 16, or 17. Is there any major downside to just removing node from the `requirements` in package.json to bring it in line with other boilerplates?

Maybe there could be a suggestion on either [the lesson page](https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/set-up-a-template-engine) or in the readme to install the current LTS (or possibly be more specific and say 16.x, as unless there is another new CPU architecture 16.x should be ok for all popular architectures / operating systems for the foreseeable future)?

**Comment by ojeytonwilliams** [comment]
> Is there any major downside to just removing node from the requirements in package.json to bring it in line with other boilerplates?

To be honest, I'm not sure why we have node as a dependency.  That's not how I ever set a node version in practice.  I vote we remove that.

It's useful to recommend compatible node versions (i.e. use `engines`), but only if we test them to make sure that's true.  We can defer that until we set up testing for the boilerplates - otherwise it's just annoying and misleading.  So, to qualify my previous statement: `engines` seems useful *if* we're running tests. 

For now, I'd be fine with just deleting `node` from the dependencies.

**Comment by nhcarrigan** [comment]
Wanted to confirm the dependency wasn't present in other boilerplates before closing. Think we're good to go now.
