### ISSUE TITLE
Text in <a href> for dead link challenge unclear

### ISSUE THREAD

**Issue by Cull-Methi** [FreeCodeCamp/FreeCodeCamp#4487]
http://www.freecodecamp.com/challenges/waypoint-make-dead-links-using-the-hash-symbol

Says: Replace your a element's href attribute with a #, also known as a hash symbol, to turn it into a dead link.

I think it is kind of unclear - would potentially be better as "Replace **the value** of your a element's...."
Tripped me up at first.

Submitting a pull request for the change

**Comment by ltegman** [comment]
Closed by #4488

**Comment by PeterBurkhard** [comment]
Yeah, messed me up too.
