### ISSUE TITLE
Error in translating the page Make Motion More Natural Using a Bezier Curve

### ISSUE THREAD

**Issue by FelipeSandes** [freeCodeCamp/freeCodeCamp#44884]
## Affected page

https://www.freecodecamp.org/portuguese/learn/responsive-web-design/applied-visual-design/make-motion-more-natural-using-a-bezier-curve

## Your code

```


The values in the Portuguese translation are wrong 0,311, 0,441, 0,444, 1,649. "," instead of "."

```

## Expected behavior

Correct values 0.311, 0.441, 0.444, 1.649.

## Screenshots

![erro](https://user-images.githubusercontent.com/57547388/150713558-1129e9df-fd5b-4b48-bbc9-c8d554d1cc03.jpg)

## System

- Device: Laptop MacBook Pro 
- OS: macOS Big Sur
- Browser: Safari
- Version: 15.1

**Comment by DanielRosa74** [comment]
Changes done and will show on the next build. Thanks for pointing it out, @FelipeSandes! :)
