### ISSUE TITLE
Learn Relational Databases by Building a Mario Database instructions wording

### ISSUE THREAD

**Issue by kmbenjel** [freeCodeCamp/freeCodeCamp#44883]
Here it says `You can see the key for your name column at the bottom`, well, I think it was meaningless, we could rather say: 

` You can see that the primary key is your name column at the bottom.`

![Screenshot from 2022-01-23 21-43-53](https://user-images.githubusercontent.com/14932601/150700253-0e1b0d3c-b8a5-4656-a910-529a303a929d.png)

**Comment by moT01** [comment]
Thanks for the suggestion. I think it's fine to leave it how it is. Thanks and happy coding 🎉

**Comment by kmbenjel** [comment]
Thank you.

Did you get sure it's meaningful?
`name` does not have a key to be shown below, `name` is the key, the
primary key.
