### ISSUE TITLE
Suggestion to avoid confusion for self-closing HTML elements, in Learn Basic CSS by Build a Cafe Menu  in Responsive Web Design Certification

### ISSUE THREAD

**Issue by deniselemonaki** [freeCodeCamp/freeCodeCamp#44894]
[Step 3](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-003.md) mentions that  the `<meta charset="utf-8" >`  is self-closing element,  without making it  very clear how to write it.

Tests pass when the forward slash is not written.

<img width="744" alt="Screenshot 2022-01-24 at 7 31 25 PM" src="https://user-images.githubusercontent.com/51991217/150834826-31052370-b440-49db-8427-2d4ecc8a6d6a.png">

Then, in [step 17](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-017.md)  the `<meta charset="utf-8" />` has a forward slash  added to it, and when I try to write `<link rel="stylesheet" type="text/css" href="styles.css">` without a forward slash, tests fail.

<img width="729" alt="Screenshot 2022-01-24 at 7 51 44 PM" src="https://user-images.githubusercontent.com/51991217/150837532-477fab49-db50-4502-a6dd-74a5964d7d16.png">

In [step 18](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/step-018.md) there is a code block showing how to write the `<meta name="viewport" content="width=device-width, initial-scale=1.0" />` element.

Maybe such a code block could be added in step 3 instead, in order to avoid confusion  for complete beginners in step 17.

As there is no mention of whether  a forward slash is needed or not in the first project(Learn HTML by Building a Cat Photo App).

The  `img` element is written without one in the lessons, so maybe making this step more clear would help avoid some people getting stuck on step 17

**Comment by moT01** [comment]
The first test on step 3 requires a space in the tag:
![Screenshot from 2022-01-25 17-59-29](https://user-images.githubusercontent.com/20648924/151080037-aef4d97c-413f-43ae-a048-7ba89df4101a.png)
`<meta >` passes. The test shouldn't require a space. And if we change the hint to `You should have a <meta /> tag` or something - I think that would clarify it enough in case users forgot. I'm not opposed to an example or something, but those instructions are already kind of long.

Most self-closing elements will allow the slash or not. We should try to make our tests pass with any valid method. Step 17 requires the slash, as mentioned. It should allow both methods.

I would make those two fixes. What do you think @deniselemonaki

**Comment by deniselemonaki** [comment]
@moT01  I think tests passing with any valid method would be helpful 👍

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

**To Resolve**

- Valid HTML syntax should pass the tests.
- Unless explicitly requested in the instructions, a self-closing element without the `/` in the tag should still pass the tests.

**Comment by sstonaker** [comment]
Submitted PR#[44982](https://github.com/freeCodeCamp/freeCodeCamp/pull/44982) to resolve issue with Step #3.
I left step 17 unchanged since the instructions require a self-closing tag.
Step 18 seems to work for valid html.
