### ISSUE TITLE
RDB Student Database Part1 required spaces after "#"s to pass

### ISSUE THREAD

**Issue by philsawa** [freeCodeCamp/freeCodeCamp#44897]
## Affected page
Where you add the first if statement

## Your code
Code _required_ to pass:
```
#!/bin/bash
# Script to insert data from courses.csv and students.csv into students database
PSQL="psql -X --username=freecodecamp --dbname=students --no-align --tuples-only -c"

cat courses.csv | while IFS="," read MAJOR COURSE
do
  # get major_id
  MAJOR_ID=$($PSQL "SELECT major_id FROM majors WHERE major='$MAJOR';")
  echo $MAJOR_ID
  # if not found
  if [[ -z $MAJOR_ID ]]
  then
    # insert major

    # get new major_id

  fi

  # get course_id

  # if not found

  # insert course

  # get new course_id

  # insert into majors_courses
done
```

## Expected behavior
The code that _should_ pass:
```
#!/bin/bash
#Script to insert data from courses.csv and students.csv into students database
PSQL="psql -X --username=freecodecamp --dbname=students --no-align --tuples-only -c"
cat courses.csv | while IFS="," read MAJOR COURSE
do
  #get major_id
  MAJOR_ID=$($PSQL "SELECT major_id FROM majors WHERE major='$MAJOR';")
  echo $MAJOR_ID
  #if not found
  if [[ -z $MAJOR_ID ]]
  then
    # insert major

    # get new major_id

  fi
  
  #get course_id
  #if not found
  #insert course
  #get new course_id
  #insert into majors_courses
done
```

## Screenshots
![spaces required before comments](https://user-images.githubusercontent.com/9974973/150869466-2090a99c-d4aa-47b1-a2d2-c888e9163252.PNG)

## System
- Device: Laptop
- OS: Windows 10
- Browser: VS Code
- Version: Version: 1.63.2

**Comment by moT01** [comment]
This looks correct @philsawa - thanks for reporting 👍

**Comment by Jagrutiti** [comment]
@moT01 shall I  take this up? If my understanding is correct, I have to change this:
` # get course_id `

  `# if not found`

 ` # insert course`

  `# get new course_id`

  `# insert into majors_courses`

to this:

`  #get course_id`
 ` #if not found`
 ` #insert course`
 ` #get new course_id`
`  #insert into majors_courses`

Remove the spaces between lines?

**Comment by moT01** [comment]
Fixed via: https://github.com/freeCodeCamp/learn-sql-by-building-a-student-database-part-1/pull/16
