### ISSUE TITLE
Typing error in the name of website

### ISSUE THREAD

**Issue by DivyanshuBist** [freeCodeCamp/freeCodeCamp#44892]
## Affected page
https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/

## To reproduce
Typing error in the name of the website.

## Recommended fix, suggestions
Change 24 pull reuests->24 pull requests

## Screenshots

![image](https://user-images.githubusercontent.com/77827249/150815312-b8900ba1-bda0-4c2e-b09c-c2f7687fd136.png)

**Comment by DivyanshuBist** [comment]
Sure but how to do that.this is the first time I have raised an issue.

**Comment by Sampathkumar-PN** [comment]
We are provided with [Contributing guidelines](https://contribute.freecodecamp.org/#/index?id=our-open-source-codebase ).

**Comment by moT01** [comment]
Thanks for reporting @DivyanshuBist - I don't think this can be fixed with a PR. The author, or someone with access, will need to go and edit the article.

**Comment by filipkujawa** [comment]
I believe this issue was fixed.

![image](https://user-images.githubusercontent.com/44206832/151106320-76e16926-455d-45fb-b87f-c8a7fa580bbd.png)

**Comment by Sembauke** [comment]
The issue appears to be fixed by the author, thanks for reporting though.

Have a nice day, and happy coding :) !
