### ISSUE TITLE
[Feature request] Add video links in README.md and website

### ISSUE THREAD

**Issue by thamognya** [freeCodeCamp/freeCodeCamp#44901]
## Is your feature request related to a problem? Please describe.

I really like this readme.md and the website in general but the thing that frustrates me is that I have to go searching for the video link (i.e the tutorials on youtube) which makes it a bit unmotivating. 

## Describe the solution you'd like

I would like to request a addition of the video links (i.e the tutorials on youtube) to the `README.md` and the website

**Comment by moT01** [comment]
Thanks for sharing your ideas @ThamognyaKodi. I, personally, don't think the readme is an appropriate place for video links. There's a link to our youtube channel in it, which has hundreds of videos on the channel. Is there some specific ones you were thinking of?

**Comment by yudenojepri9** [comment]
> ## Is your feature request related to a problem? Please describe.
> I really like this readme.md and the website in general but the thing that frustrates me is that I have to go searching for the video link (i.e the tutorials on youtube) which makes it a bit unmotivating.
> 
> ## Describe the solution you'd like
> I would like to request a addition of the video links (i.e the tutorials on youtube) to the `README.md` and the website
