### ISSUE TITLE
Keyboard Shortcut for Next Challenge without submitting the current one

### ISSUE THREAD

**Issue by kmbenjel** [freeCodeCamp/freeCodeCamp#44930]
## Your code

```
I needed to have a glance again at all my previous challenges in RWD to just revise and see I there will be something that needs attention and I found this a little difficult, having a Next button + a shortcut making it easy to just move forward without the need to submit again = will be a really useful thing.

Thank you, Contributors!


```

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by nhcarrigan** [comment]
This actually exists, if you press `Esc` to get out of editor mode, you can press `n` to move to the next challenge and `p` to move to the previous.

**Comment by kmbenjel** [comment]
Aha thank you.
