### ISSUE TITLE
We need to go through issues and comments on crowdin for suggested changes to challenges

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#44933]
This is also a reminder to myself to do it.

**Comment by nhcarrigan** [comment]
I resolved all of the issues I could - linked PR includes source string fixes.

**Comment by moT01** [comment]
Do we want to keep this open as a reminder to go through them from time to time @ieahleen? I'm fine with that.

**Comment by ieahleen** [comment]
Yeah, I opened it as a reminder when looking through issues

If it's taking space we can close it
