### ISSUE TITLE
Possible issue with "Waypoint: Add Font Awesome Icons to all of our Buttons"

### ISSUE THREAD

**Issue by freeradik** [FreeCodeCamp/FreeCodeCamp#4494]
I might have found a potential issue with the above mentioned exercise.
I had the code below pass the 'test' 
This code results in **Info** and **Delete** button of a smaller width compared to **Like** button. Reason being that i closed the *i* element after the text ("Info" and "Delete") while i closed the *i* element before the text "Like". Both passed the test. Is this supposed to happen? or should one scenario (my code which closes the *i* element after) fail?

<div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle">Info </i></button> 
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash">Delete</i></button>
    </div>
  </div>

**Comment by bugron** [comment]
@freeradik thanks for posting this issue!
I see what you mean and I don't think this is an issue> It's an "incorrect" use on Font Awesome icons. There are own styles defined for Font Awesome's specific classes so this is normal that `<i class="fa fa-trash">Delete</i>` won't look the same as `<i class="fa fa-trash"></i> Delete`. I'll left this open to discuss if this case needs to be prevented by test cases.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by SaintPeter** [comment]
I think we need two changes:
1) Add sample code to the description with an alternate icon so users can see what it looks like.
2) Possibly add a test case to cover this, and in the second FA waypoint as well.  Maybe use jquery to ensure all `i` elements have a blank `html`.  Not sure if this is required if we have the example in the instructions.

**Comment by freeradik** [comment]
Thanks folks. I am brand new here and appreciate your responses very much.

**Comment by iallfree** [comment]
the original post has incorrect code- I just recognized my issue... it is fa fa-thumbs-up

**Comment by WaqasEhmed** [comment]
<i class="fa fa-thumbs-up"><button class="btn btn-block btn-primary">Like</i></button>

**Comment by WaqasEhmed** [comment]
This is the correct way
<i class="fa fa-thumbs-up"><button class="btn btn-block btn-primary">Like</i></button>

**Comment by WaqasEhmed** [comment]
`<i class="fa fa-thumbs-up"><button class="btn btn-block btn-primary">Like</i></button>`
