### ISSUE TITLE
Adding Custom Fonts for Different Langauges

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#44955]
Currently Lato does not support italic for Japanese and we optimally would like to support different fonts for different languages. 

Here is the plan:
1) download the related woff files and place them in the [static directory](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/client/static/fonts).
2) group all font assignments in css into one file for english, and dynamically load alternative files.
3) create [typeface definition css files](https://github.com/freecodecamp/freeCodeCamp/blob/984f311061fd504b5a71310b40d0947fee525a52/client%2Fsrc%2Fcomponents%2Flayouts%2Ffonts.css) for different fonts and load them dynamically.
5) inject [link tags](https://github.com/freecodecamp/freeCodeCamp/blob/4bdfb6794f65b49e6141cef29c8095cd1126c307/client%2Fsrc%2Fcomponents%2Flayouts%2Fdefault.tsx#L159-L200) conditionally based on language. 

Alternatively we could introduce new names to our our fonts, and rename all fonts across css files, and skip number 3.

Feedback is appreciated.

**Comment by sidemt** [comment]
I think Lato font doesn't have Japanese characters at all (not only italic) and some fallback font is used now. And that fallback font does not have italic.

When I had the same issue on /news, I chose 'Noto Sans JP' for Japanese news.
Noto Sans JP: https://fonts.google.com/noto/specimen/Noto+Sans+JP

The issue I created for news: https://github.com/freeCodeCamp/news-theme/pull/232

**Comment by sidemt** [comment]
@ahmadabdolsaheb Can I start working on this in the way you suggested? The current Japanese font doesn't look good. Changing it to a better font should improve the impression of freeCodeCamp on Japanese users.

**Comment by ahmadabdolsaheb** [comment]
@sidemt, I think we could move forward with the implementation described above. Please let us know if we could be of any help.

**Comment by naomi-lgbt** [comment]
@sidemt is this still needed?

If so, can we open it for contributions?

**Comment by moT01** [comment]
Adding the help wanted label here if that's okay @sidemt. Let us know if you need any help with anything.

**Comment by ganesh-159th** [comment]
To move forward, could you provide the following details?

1)Font List: Which fonts and styles do we need for each language?
2)Font Source: Where should we download the fonts from?
3)CSS Examples: Any examples of the typeface definition CSS files?
4)Language Detection: How are we detecting and handling language changes?
4)Existing CSS Files: How many and which CSS files will need updating if we rename fonts?
