### ISSUE TITLE
Selecting Ukrainian redirects to Japanese, and sometimes just some of the content is displayed in Japanese

### ISSUE THREAD

**Issue by sasha066** [freeCodeCamp/freeCodeCamp#44956]
## Affected page
https://www.freecodecamp.org/ukrainian/learn/ and all lessons.

## To reproduce

1. Go to https://www.freecodecamp.org/ukrainian/learn/
2. Click on menu button
3. Select "Українська" language

## Expected behavior

Displaying the site in Ukrainian.

## Screenshots

![s1](https://user-images.githubusercontent.com/71141771/151577127-0e4810c0-99aa-46bb-b48a-4ac76b9ea886.png)

## System

- Device: PC
- OS: Manjaro 21.2.1
- Browser: Brave
- Version: 1.34.81

(also tested with other browsers and android devices, I cleared the cache and cookies, the problem is everywhere, it seems to be platform independent)

## Additional context

When choosing the Ukrainian language, the URL redirects me to Japanese  https://www.freecodecamp.org/japanese/learn/ for some reason. In some cases, there is no redirect, but the content is still in Japanese. In some cases, some of the elements may be in Japanese, some in Ukrainian. This only started happening today. Everything was fine yesterday. This happens only when choosing the Ukrainian language. This does not happen with other languages.

**Comment by raisedadead** [comment]
Thanks for your report. We are looking into this.

**Comment by raisedadead** [comment]
OK - We have reset the deployments can you please check again? You may need to do a hard refresh / reload the page.

**Comment by sasha066** [comment]
> OK - We have reset the deployments can you please check again? You may need to do a hard refresh / reload the page.

yep, that's works fine now, thanks you very much

**Comment by raisedadead** [comment]
Great - Thanks for confirming, sincerest apologies about that. We misconfigured a few things in the last deployment. Will be more careful in the future.

Happy coding!
