### ISSUE TITLE
Palindrome waypoint

### ISSUE THREAD

**Issue by fatemamelg** [FreeCodeCamp/FreeCodeCamp#4495]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20str%20%3D%20str.replace(%2F%5Cs%2B%2Fg%2C%20%27%27)%3B%0A%20%20str%20%3D%20str.replace(%2F%5B%2C.%5D%2Fg%2C%20%27%27)%3B%0A%0A%20%20if%20(str.length%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20if%20(str%5B0%5D%20!%3D%3D%20str%5Bstr.length%20-%201%5D)%7B%20return%20false%3B%20%7D%0A%20%20return%20palindrome(str.slice(1%2C%20str.length-1))%3B%0A%7D%0A%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0Apalindrome(%22race%20car%22)%3B%0Apalindrome(%22not%20a%20palindrome%22)%3B%0Apalindrome(%22A%20man%2C%20a%20plan%2C%20a%20canal.%20Panama%22)%3B%0Apalindrome(%22never%20odd%20or%20even%22)%3B%0Apalindrome(%22nope%22)%3B%0Apalindrome(%22almostomla%22)%3B%0Apalindrome(%22My%20age%20is%200%2C%200%20si%20ega%20ym.%22)%3B%0Apalindrome(%220_0%20(%3A%20%2F-%5C%20%3A)%200-0%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  str = str.toLowerCase();
  str = str.replace(/\s+/g, '');
  str = str.replace(/[,.]/g, '');

  if (str.length === 0) {
    return true;
  }
  if (str[0] !== str[str.length - 1]){ return false; }
  return palindrome(str.slice(1, str.length-1));
}




palindrome("eye");
palindrome("race car");
palindrome("not a palindrome");
palindrome("A man, a plan, a canal. Panama");
palindrome("never odd or even");
palindrome("nope");
palindrome("almostomla");
palindrome("My age is 0, 0 si ega ym.");
palindrome("0_0 (: /-\ :) 0-0");
```

why the last palindrome doesn't return true?

**Comment by faizaanceg** [comment]
> You'll need to remove punctuation and turn everything lower case in order to check for palindromes.

Only `,` and `.` aren't part of the punctuation. You also need to remove `(, ), :, \, /, _, -`

**Comment by abhisekp** [comment]
@fatemamelg You need to remove all punctuation. https://en.wikipedia.org/wiki/Punctuation

You can use Regular Expression.
If you need any help, please feel free to ask in https://gitter.im/FreeCodeCamp/HelpBonfires room.

> This issue can be closed.

**Comment by bugron** [comment]
@fatemamelg thanks for posting this issue!
Closing. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
