### ISSUE TITLE
Typo in Responsive Web Design (Beta) 

### ISSUE THREAD

**Issue by Dainelli** [freeCodeCamp/freeCodeCamp#44969]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-36

## Your Issue

```
The instructions do not state that the <select> element shoud  be required. Only the hints say so.



```

## Expected behavior

The instructions should specify that the <select> element should be required.

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by DarshanVaishya** [comment]
In the instructions it is stated that nest a required select element. You can see it below

Within the first `div.answer` element, nest one **required** `select` element with three `option` elements.

**Comment by gikf** [comment]
Hey @Dainelli

Thank you for opening this issue.

This seems to be already the case, as such I'm going to close this issue. If you think this is a mistake feel free to add more information and request to re-open issue.

Thank you and happy coding.
