### ISSUE TITLE
Random Quote Machine template passing 12/12 test with barely any code

### ISSUE THREAD

**Issue by cesaugo** [freeCodeCamp/freeCodeCamp#44972]
## Affected page
https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-random-quote-machine
Build a Random Quote Machine
 You can build your project by using this CodePen template and clicking Save to create your own pen 
https://codepen.io/pen?template=MJjpwO 

## Your code

```
<div id="quote-box">
  <div id="text"></div>
  <div id="author"></div>
  <div id="new-quote"></div>
  <a id="tweet-quote" href="twitter.com/intent/tweet"></a>
</div>



```

## Expected behavior

I'm using the template provided and I’m getting 12/12 test passed so it’s difficult to keep track of my progress if it doesn’t display the passed tests properly.
![random quote machine](https://user-images.githubusercontent.com/52609760/151717203-af439a48-b17f-47f4-9953-23a1722cad32.png)

## Screenshots

![image](https://user-images.githubusercontent.com/52609760/151716019-dbb6c8cd-12c2-487e-8c08-aa10065f0942.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: Firefox
- Version: 96.0.3 (64-bit)

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you, for taking the time to open this.
This issues should be closed by: https://github.com/freeCodeCamp/testable-projects-fcc/pull/1344
