### ISSUE TITLE
Issue: Waypoint "Count Backwards With a For Loop" tail isn't showing up.

### ISSUE THREAD

**Issue by RobRoseKnows** [FreeCodeCamp/FreeCodeCamp#4499]
The final tail of this (http://www.freecodecamp.com/challenges/waypoint-count-backwards-with-a-for-loop) problem isn't showing up for me. I'm in the process of doing a fix right now.

**Comment by RobRoseKnows** [comment]
Fixed in PR #4500

**Comment by RobRoseKnows** [comment]
Note: this error could've been because of a larger issue. I'm not expert enough to look into that so I created a hot-fix.

**Comment by bugron** [comment]
@RobRoseKnows thanks for posting this issue!
This is not an error. See your PR for details.
Closing.

**Comment by RobRoseKnows** [comment]
When I tried running my program though, it didn't verify. I had to copy and paste the code from the previous exercise.

**Comment by ltegman** [comment]
That tail function isn't actually used in any of the tests, it is purely used to make sure your array is displayed in the console, so it can't have impacted whether you passed the tests or not. I also just confirmed that I can complete that challenge without the tail code being in the editor. There must have been something else that changed when you copied and pasted that other code that made it pass.

**Comment by RobRoseKnows** [comment]
Alright. Not sure what it was then. Thanks!
