### ISSUE TITLE
SASS/SCSS challenges are broken in Firefox

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45006]
When I revert PR https://github.com/freeCodeCamp/freeCodeCamp/pull/42195 it works again.

I didn't really figure out what is causing it but if I log out the innerHTML of the frame before and after the Promise.all inside the transform function I first see the content and then empty `<head></head><body></body>`

```
const transformHtml = async function (file) {
  const transform = async frame => {
    console.log('before');
    // correct content
    console.log(frame.contentDocument.documentElement.innerHTML);
    await Promise.all([
      transformSASS(frame.contentDocument),
      transformScript(frame.contentDocument)
    ]);
    console.log('after');
    // empty content
    // <head></head><body></body>
    console.log(frame.contentDocument.documentElement.innerHTML);
    return { contents: frame.contentDocument.documentElement.innerHTML };
  };

  const { contents } = await transformWithFrame(transform, file.contents);
  return transformContents(() => contents, file);
};
```

---

Forum post: https://forum.freecodecamp.org/t/scss-not-showing-in-iframe/495117

**Comment by gikf** [comment]
These changes appear to make it work, I'm not able to explain why this makes it work. Maybe it will give somebody idea what is going out here.

https://github.com/freeCodeCamp/freeCodeCamp/blob/a2a1c62953bdc78373b582193b6fe24d74ec311f/client/src/templates/Challenges/rechallenge/transformers.js#L214
```js
    const documentElement = frame;
```

https://github.com/freeCodeCamp/freeCodeCamp/blob/a2a1c62953bdc78373b582193b6fe24d74ec311f/client/src/templates/Challenges/rechallenge/transformers.js#L261
```js
    out = await transform(frame.contentDocument.documentElement);
```

https://github.com/freeCodeCamp/freeCodeCamp/blob/a2a1c62953bdc78373b582193b6fe24d74ec311f/client/src/templates/Challenges/rechallenge/transformers.js#L271-L274
```js
      transformSASS(frame),
      transformScript(frame)
    ]);
    return { contents: frame.innerHTML };
```

How does it look?

---

There might be related, but slightly different issue with jQuery on Firefox - fresh load (after `F5`) of jQuery challenge won't render preview, but in the next/previous challenge, or visiting challenge again from challenges list - preview will load now. After the above changes that issue also goes away.

**Comment by techanthere** [comment]
I am having trouble in running tests and submitting solutions to the challenge number 5 and onwards challenges in Sass. The tests keep failing despite correct solution. Please resolve this issue. Thanks

**Comment by gikf** [comment]
> I am having trouble in running tests and submitting solutions to the challenge number 5 and onwards challenges in Sass. The tests keep failing despite correct solution. Please resolve this issue. Thanks

@techanthere That doesn't sound related to this issue, as problem here affects previous challenges as well. Please first click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can create separate issue.

Thank you and happy coding.

**Comment by lasjorg** [comment]
@gikf I did see it randomly work a few times with code changes and hot-reload/refresh but when reloading the page manually it broke again. So I guess it might be related to the jQuery challenges issue as well. Does reverting https://github.com/freeCodeCamp/freeCodeCamp/pull/42195 make the jQuery challenges work again?

---

I didn't test your code. But I don't really understand how you can change the first line and not have to change the rest of the function (the event listeners and return) but maybe I'm just missing something having only skimmed it.

**Comment by gikf** [comment]
@lasjorg Hm, you know what? Reverting it, doesn't make jQuery challenges work reliably, but rolling back before it does :thinking:.

**Comment by lasjorg** [comment]
@ojeytonwilliams @ShaunSHamilton

It would be nice if someone from the PR that seemingly broke the SASS/SCSS challenges in Firefox would post a response to this issue.

**Comment by ShaunSHamilton** [comment]
@lasjorg Thank you, for the ping. @gikf 's solution is better than anything I tried. So, hopefully we can move forward with that.

**Comment by ojeytonwilliams** [comment]
Thanks for the detailed debugging and fix @lasjorg @gikf. While I still don't understand what the problem is, the suggestions you made did fix it!  Sorry for the delay getting to the issue and thanks for the nudge.
