### ISSUE TITLE
RWD Beta: Inconsistent naming for courses/steps

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#45037]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design

## Explanation

On the main Beta RWD page there is a list of "Courses", and each course can be expanded using the "Expand courses" button. This implies that each course is composed of individual "courses". When you open one of the individual courses, the main heading is "Step N" however, which implies that each course is really composed of "steps", not "courses".

For accessibility, I think it would be best if we removed the ambiguity here and kept the naming consistent. If a course is really composed of "steps" then course toggle button should reference "steps" instead of "courses". 

Is there an official naming convention here for how these should be referenced?

**Comment by ShaunSHamilton** [comment]
Thank you, for opening this.

> Is there an official naming convention here for how these should be referenced?

Yes, we do generally have a convention.

---

In this case, we should just change `Expand Courses` to `Expand Course`.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
