### ISSUE TITLE
Challenge: Iterate through an array with a for loop (Make test and requirements stricter)

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45041]
This challenge can be passed with incorrect code. It does not check that the array elements are added to `total`.

```
var total = 0;
for (total; total < 20; total += myArr[0]) { }
```

```
var total = 0;
for (var i = 0; i <= 20; i++) {
  myArr[0];
  total = i;
}
```

```
var total = 0;
for (var i = 0; i <= myArr[3] * 4; i++) {
 total = i;
}
```

The requirements should probably be stricter and expect either `total += myArr[i]` or `total = total + myArr[i]` to be inside the body of the for loop (without forcing the iterator variable name to be `i`).

---

Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop

Test: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop.md

Forum post: https://forum.freecodecamp.org/t/iterate-through-an-array-with-a-for-loop-challenge-help/495925

**Comment by kartikth40** [comment]
On each for loop instance, we can check if the `total == current  total + myArr[i]`  or not

- current total can be hard coded in the tests

**Comment by hrushi2003** [comment]
On each iteration we can check the condition and return according statement

var total = 0;
function iterate(arr){
for(let i = 0 ; i < arr.length; i++){
    if (total !== arr[i]){
total += arr[i];}
}

**Comment by LuciusLiciniusLucullus** [comment]
var total = 0;
let number = 20
for (var i = 0; i <= 20; i++) {
  myArr[0];
  total = number;
}

The condition: 'You should not attempt to directly assign the value 20 to total.' is still passed with this incorrect code

**Comment by utsav0** [comment]
Hey, sorry to interrupt you guys, but I want to contribute here. So, where can I contribute and how ? Please guide me

**Comment by lasjorg** [comment]
An issue with the help wanted or first timers only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Nirajn2311** [comment]
Challenge is being rewritten for the new curriculum so closing it.
