### ISSUE TITLE
Solution for "Everything Be True" in Wiki is no longer correct

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4505]
Ref:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Bonfire-Everything-be-True

This now fails several of the test cases.

If you fix the code, update the explanation as well.

![image](https://cloud.githubusercontent.com/assets/553494/11229518/f3166d1a-8d4a-11e5-8df4-0e9756a7d2b0.png)

**Comment by ltegman** [comment]
This was closed by https://github.com/FreeCodeCamp/wiki/pull/88 and just needs to be pushed from the wiki repo to the FCC wiki.
