### ISSUE TITLE
JS Curriculum: missing test case in Telephone Number Validator challenge

### ISSUE THREAD

**Issue by rdelia** [freeCodeCamp/freeCodeCamp#45080]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator
## Your code

```
// example of buggy function that passes the challenge
function telephoneCheck(str) {
  return /^(1)*(\s)*(?:\d\d\d|\(\d\d\d\))([-|\s])*\d\d\d([-|\s])*\d\d\d\d$/.test(str);
}

```

## Expected behavior

The code above shouldn't pass the challenge.

## Additional context

In the challenge, it is required to confirm that the country code is 1, where it is provided.

Please add a test case where the country code is made of multiple 1s, for example:

```
//test 
console.log(telephoneCheck("11 555-555-5555")); // should return false


```

**Comment by gikf** [comment]
I guess it might be fine as well to change one of the existing test including country code.

**Comment by gikf** [comment]
Relevant user story stays the same:
> If the country code is provided, you must confirm that the country code is `1`.
