### ISSUE TITLE
Local Scope and Functions: example needs to be a little less confusing

### ISSUE THREAD

**Issue by kmbenjel** [freeCodeCamp/freeCodeCamp#45081]
## Affected page
[Local Scope and Functions
](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions)

## Your code

```




```

## Expected behavior

Once `console.log(loc)` has been used twice inside the caption, in the paragraph below it, `. The console.log(loc) line will throw an error` might be a little confusing, I think we have somehow to mention that we're talking about the second occurrence of it, not the first which is inside the function, just for better quality and clarification.

## Screenshots

![Screenshot from 2022-02-11 03-35-29](https://user-images.githubusercontent.com/14932601/153529288-04167427-aaa0-49ab-8c3a-bd13152711fc.png)

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by ls-madhu** [comment]
Hi @gikf, I'd like to work on this.

**Comment by ls-madhu** [comment]
@gikf Thank you for the info❤️.
