### ISSUE TITLE
[beta] Issue with order of content

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45096]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-90

## To reproduce

The use of the CSS transform-origin property was never explained in the course but is required the use of it. The course is assuming we have used this property in the past.

But it's explained in the next section, assuming we have never seen this property, the ferris wheel one.
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-animation-by-building-a-ferris-wheel/step-8

## Recommended fix, suggestions

I don't know, I think you should either change the order of the section, doing first the ferris one and later the penguin or, add the explanation to the penguin section and exclude the explanation from the ferris wheel.

## Screenshots

screenshot of the ferris wheel
![image](https://user-images.githubusercontent.com/92828033/153719595-8d131141-9d75-43b7-83c8-dd168ae07076.png)

screenshot of the penguin
![image](https://user-images.githubusercontent.com/92828033/153719624-f17fc4ce-4c91-4231-b23d-137426b8bc9a.png)

**Comment by moT01** [comment]
I'm not sure if there's other issues around switching the order of those two projects - perhaps other things will have the same problem. We could just add the `transform-origin` description to that step in the penguin project...

```
The transform-origin property is used to set the point around which a CSS transformation
is applied.

Within the .arm.left selector, alter the origin of the transform function to be the top left
corner of its parent.
```

Something like that maybe. We may want to double check that this is the first place this property is used.

**Comment by ieahleen** [comment]
The ferris wheel and penguin projects have been switched, so I am closing this as fixed.

If you think this is still an issue please let us know and this can be reopened.
