### ISSUE TITLE
Correct answer marked as a bad one

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45099]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-animation-by-building-a-ferris-wheel/step-14

## Your code

```
.cabin:first-of-type {
  right: -8.5%;
  top: 50%;
}

```

## Screenshots

![image](https://user-images.githubusercontent.com/92828033/153720427-45c2e2e0-48f6-4eea-935b-af3e64825220.png)

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional context

I could be able to solve the minichallenge with my code using the .first-of-type selector, but the minichllenge required the use of :nth-of-type(1), I think that this is ok because of the future use of the other elements, but there should be some kind of explanation saying something like "You should have a .cabin:nth-of-type(1) selector. because we will use others elements in the future using this selector: or something like this.

**Comment by nhcarrigan** [comment]
@ShaunSHamilton curious to hear your thoughts on this one.

It's valid code that produces the desired result, but it's not in line with the instructions.

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this.

---

In my opinion, the test should be changed to allow for a solution such as `:first-of-type`.

Potentially, there should also be space made for `:last-of-type` with the `6th` element.

---

@nhcarrigan If you agree, please open this up for `help-wanted`.

**Comment by nhcarrigan** [comment]
Works for me!

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by wbenarto** [comment]
Hi @ShaunSHamilton, I would like to work on this. 

My proposed changes are :

- Step-014.md:

1. Add a test that passes .cabin:first-of-type selector
2. Add ".cabin:first-of-type" selector to the hints 
3. Have the tests passes for both first-of-type and nth-of-type(1) 

- Step-015md:

1.  Add a test that passes .cabin:last-of-type selector for the 6th element
2. Add ".cabin:last-of-type" selector to the hints
3. Have the tests passes for both last-of-type and nth-of-type(6)

Let me know if you think of anything else. I will create a PR for this issue.
