### ISSUE TITLE
Some issues with order of content

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45102]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/#build-a-product-landing-page-project
## Your code

```




```

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional context

as far as I know, the "[Learn CSS Transforms by Building a Penguin](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-css-transforms-by-building-a-penguin)" section uses animation that never was explained, but "[Learn CSS Animation by Building a Ferris Wheel](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-css-animation-by-building-a-ferris-wheel)" explains all the animation.

I think you should change several minichallenge of both sections, specifically the minichallenge associated with animations because in the penguin one assume you know already this content but in the ferris wheel doesn't.

**Comment by huyenltnguyen** [comment]
Hey @LuckyLolo123, thank you for the feedback!

I'm going to close this issue out to keep the discussion in one place, as it is similar to #45096. Please help update the description there with the problems you found as well as your suggestions.
