### ISSUE TITLE
another issues with order of content 

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45101]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-95

## Your code

```
None



```

## Expected behavior

The curriculum requires that I use the @keyframes rule, and it was never explained, but, it's explained in this future section:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-animation-by-building-a-ferris-wheel/step-16
Assuming the curriculum this is the first time I am going to work whit it.

So, there is a light misorder in the content in the curriculum.

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by huyenltnguyen** [comment]
Hey @LuckyLolo123, thank you for the feedback!

I'm going to close this issue out to keep the discussion in one place, as it is similar to #45096. Please help update the description there with the problems you found as well as your suggestions.
