### ISSUE TITLE
js base and js debugging tutorial conflict

### ISSUE THREAD

**Issue by yuanhepeng** [freeCodeCamp/freeCodeCamp#45117]
![图片](https://user-images.githubusercontent.com/39111057/154004595-d83a9dd7-49be-45cf-bac5-05e73c35cb29.png)
[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/use-typeof-to-check-the-type-of-a-variable](url) 
in there, a type should be added : bigint
![图片](https://user-images.githubusercontent.com/39111057/154004647-09bb4747-e435-4298-a52b-4600e272292a.png)
[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-javascript-variables](url)

**Comment by nhcarrigan** [comment]
Nice catch! It looks like we've got an open PR that will resolve this.
