### ISSUE TITLE
Give option to bookmark a challenge

### ISSUE THREAD

**Issue by unniksk** [FreeCodeCamp/FreeCodeCamp#4511]
Give options to bookmark a challenge

**Comment by SaintPeter** [comment]
In what way can you not bookmark a challenge now?  All challenges have a unique url that you can bookmark with your browser.

What is it that you would like to do with a bookmark?

**Comment by BerkeleyTrue** [comment]
@SaintPeter is correct. You can just use you're browsers bookmarks.

Happy Coding!
