### ISSUE TITLE
Waypoint passes with incorrect code

### ISSUE THREAD

**Issue by asauce99** [FreeCodeCamp/FreeCodeCamp#4512]
http://www.freecodecamp.com/challenges/waypoint-update-the-properties-of-a-javascript-object

Code passes with:

```
var myDog = {
  "name": "Happy Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"]
};
```

But, it shouldn't.
It basically doesn't require you to modify the property in the way they are instructing using `myDog.name` in order to pass. It allows you to directly modify the property of the variable by simply adding the word "Happy" to the `"Name"` property in order to pass.

**Comment by ltegman** [comment]
The waypoint seed does clearly state that the upper code should not be modified, so there's no reason a student should by modifying that code. Waypoints are optional learning and there's only so much we can reasonably test for. If a user is interested in "gaming" them by completing them in a manner outside the instructions they're only potentially harming their own learning.

Thanks and happy coding!
