### ISSUE TITLE
"Saved!" message on code editor is not translated

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#45129]
The banner message "Saved! Your code was saved to your browser's local storage." is displayed in English even if other language is selected.

It is not in translation strings and the message is hard coded here: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/7fe46957943028a8d950d8f00f8e737b9d1f34d1/client/src/templates/Challenges/redux/code-storage-epic.js#L116

## Affected page

Any challenge on /learn

## To reproduce

1. Go to any challenge
2. Press Ctrl+S
3. See the message banner

## Expected behavior

The message ""

## Screenshots

![not_translated](https://user-images.githubusercontent.com/25644062/154118472-4b1b1034-4adc-4c2f-8eff-44a58ae4b581.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: chrome
- Version: 98.0.4758.82

**Comment by nhcarrigan** [comment]
Thanks for catching this! I've got a PR in place to fix it. 😁

**Comment by sidemt** [comment]
@nhcarrigan Awesome! Thanks as always Naomi 👍
