### ISSUE TITLE
Inconsistancy on const Naming Cases

### ISSUE THREAD

**Issue by juanalbglz** [freeCodeCamp/freeCodeCamp#45128]
## Affected pages

- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/add-two-numbers-with-javascript

- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/subtract-one-number-from-another-with-javascript

- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/multiply-two-numbers-with-javascript

- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/divide-one-number-by-another-with-javascript
- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript

Previous Lesson:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword

## Your code

```
/*
  Change the 0 so that sum will equal 20.
*/

const SUM = 10 + 10;


```

## Expected behavior

Correctionr:
Extract: On lesson 10 from the JavaScript curriculum all caps constants are referred as the "common practice" and there after several times this "common practice" is not followed. Does it deserves to change lesson 10 text to limit this convention to a certain kind of constants or should other lessons be updated to follow this "common practice".

<del datetime="Tue Feb 15 2022 21:23:56 GMT+0000" title="deleted Tue Feb 15 2022 21:23:56 GMT+0000 (Western European Standard Time)">As explained on previous lesson all const should be named ALLCAPS
"...variables declared with const to conform to common practices, meaning constants should be in all caps."
"const sum" according to previous lesson should be rewritten to "const SUM"</del>

## System

- Device: Desktop
- OS: Manjaro Linux 21.2.3 "Qonos"
- Browser: Firefox
- Version: 97.0 (64 bits)

**Comment by ls-madhu** [comment]
@nhcarrigan Yeah that's correct. But in the lesson [Declare a Read-Only Variable with the const Keyword
](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword)
It was mentioned:
> A common practice when naming constants is to use all uppercase letters, with words separated by an underscore.

So we need to correct that statement.

**Comment by ls-madhu** [comment]
@nhcarrigan I read that, capital-named constants are only used for “hard-coded” values and constants that are calculated at run-time are named normally.
Source: [javascript.info](https://javascript.info/variables#uppercase-constants)
Which is the correct way😕?

**Comment by ShaunSHamilton** [comment]
> Is this accurate? I use camelCase for almost everything, personally.

In general, many programming languages (C-like) follow this:

```js
const I_AM_GLOBAL_AND_PRIMITIVE = 10;

let iAmGlobalButChange = 10;

// This is often also SCREAMING_SNAKE
const iAmGlobalButIndefinite = I_AM_GLOBAL_AND_PRIMITIVE + iAmGlobalButChange;

const iAmJustAConstantPointer = ["i", "could", "change", "but", "my", "pointer", "never", "does"];

enum IAmAnEnum {
  VALUE
};

function iAmAFunction() {
  for (const iAmLocalAndIndefinite in [1, 2, 3]) {
    iAmGlobalButChange++;
  } 
}

class IAmAClass {}
```

---

At the end of the day, it does not matter, because none of this is a feature of the language, and I know some who actively have the opposite _convention_.

My suggestion: Nothing to be done here.

**Comment by nhcarrigan** [comment]
> My suggestion: Nothing to be done here.

How would you feel about removing the note? Seems unnecessary.

**Comment by juanalbglz** [comment]
If you mean that is it not inconsistent to have an exercise in lesson [Declare a Read-Only Variable with the const Keyword](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword) "Change the code so that all variables are declared using let or const. Use let when you want the variable to change, and const when you want the variable to remain constant. Also, rename variables declared with const to conform to common practices, meaning constants should be in all caps." with the fact that in the next lessons this "common practice" seems to be "less common".
Then maybe change the text on that lesson to explain somehow where to use capitalized constants, and where to follow the most "common practise" of camel case practise. I question, where is the pedagogics of learning the way something should be, when thereafter you learn how not to do it?

**Comment by ShaunSHamilton** [comment]
If we do anything, I would change this line:

> Also, rename variables declared with `const` to conform to common practices, meaning constants should be in all caps.

To
> Also, rename variables declared with `const` to conform to common practices.

And maybe remove this:
> A common practice when naming constants is to use all uppercase letters, with words separated by an underscore.

---

> How would you feel about removing the note? 

The note is spot-on, in my opinion.

> Note: It is common for developers to use uppercase variable identifiers for immutable values and lowercase or camelCase for mutable values (objects and arrays). You will learn more about objects, arrays, and immutable and mutable values in later challenges. Also in later challenges, you will see examples of uppercase, lowercase, or camelCase variable identifiers.

Especially our declaration of:
> Also in later challenges, you will see examples of uppercase, lowercase, or camelCase variable identifiers.

**Comment by juanalbglz** [comment]
Marvelous!

**Comment by nhcarrigan** [comment]
Alright, let's give that a shot. I think it's a clear enough explanation that we can open this up for first timers.

---

This looks like something that can be fixed by "first time" code contributors to this repository.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Jagruti1610** [comment]
Is this issue open to work? Shall I take this up?

**Comment by ls-madhu** [comment]
@Jagruti1610 Yes, you can make a Pull Request.

**Comment by Rhut-virani** [comment]
can I work on this ?
