### ISSUE TITLE
Basic JavaScript Curriculum - code comments are evaluated as part of the solution - multiple exercises affected

### ISSUE THREAD

**Issue by juanalbglz** [freeCodeCamp/freeCodeCamp#45127]
## Affected pages
- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/explore-differences-between-the-var-and-let-keywords
- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword
- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript

## Your code

```
// 009 Explore Differences Between the var and let Keywords.js

/*
  unlike var, when you use let, a variable with the 
  same name can only be declared once.

  Update the code so it only uses the let keyword.
*/

let catName = "Oliver";
let catSound = "Meow!";
```
```
// 015 Increment a Number with JavaScript.js

/*
  Change the code to use the ++ operator on myVar.
*/

let myVar = 87;

// Only change code below this line
//myVar = myVar + 1;

myVar++

console.log(myVar);

```

## Expected behavior
Validate as correct

## Screenshots
![image](https://user-images.githubusercontent.com/2136913/154111642-37b834b3-3db1-48c9-8e95-75f1c08f73e7.png)

## System

- Device: [e.g. iPhone6, Laptop] Desktop
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4] Manjaro Gnome
- Browser: [e.g. chrome, safari] Firefox
- Version: [e.g. 22] 97.0

**Comment by nhcarrigan** [comment]
Thanks for catching this! I've got a PR in place to potentially fix it.
