### ISSUE TITLE
Waypoint: Add your JavaScript Slot Machine Slots - test passes with totally wrong code

### ISSUE THREAD

**Issue by Dishant15** [FreeCodeCamp/FreeCodeCamp#4513]
![capture](https://cloud.githubusercontent.com/assets/3438538/11235690/83c756c2-8df9-11e5-8326-0e434cc02d32.JPG)

As shown in SS above i passed the test with totally inverted logic than stated in the challenge. This bug only appears when all three slot numbers are equal.. i.e. you win, in which case you should actually return the number rather than null that this code will return.
Also to mention that instruction also says: "If all three numbers match, we should also set the text "It's A Win" to the element with class logger." which is not done or checked and you still pass the test.

**Comment by faizaanceg** [comment]
Ah..I did this one :/ Forgot to change the text in tests. @SaintPeter  can I take this?

**Comment by SaintPeter** [comment]
I believe we are planning on removing or substantially revamping the slot machine challenges in the near future.  You're welcome to make the change @faizaanceg, but at this point I'm not sure that they'll even be around long enough to get it accepted.

@QuincyLarson Do we have a timeline?

**Comment by BerkeleyTrue** [comment]
@SaintPeter do you want to submit a PR adding the beta flag to those challenges?

**Comment by stongaf** [comment]
This issue is now back. There seems have been no update but the challenge has reappeared.
