### ISSUE TITLE
Make locales work in development

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45144]
It may be a little tricky or not realistic, but it would be nice if we could see the different locales when working locally without having to rebuild. Just throwing it out there in case anyone wants to look into it.

**Comment by ShaunSHamilton** [comment]
If we do not already build i18n, then I would suggest we still avoid this, and instead have yet another flag in the `.env`: `BUILD_ALL_LOCALES=true` which would build everything for development.
