### ISSUE TITLE
Fix 'Duplicate Code' issue in curriculum\utils.js

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#45159]
[CodeFactor](https://www.codefactor.io/repository/github/freecodecamp/freecodecamp) found an issue: Duplicate Code

It's currently on:

[curriculum\utils.js:24-34](https://www.codefactor.io/repository/github/freecodecamp/freecodecamp/source/main/curriculum/utils.js#L24)

[curriculum\utils.js:39-49](https://www.codefactor.io/repository/github/freecodecamp/freecodecamp/source/main/curriculum/utils.js#L39)

Commit 62e75bc14f063e8b2834271ff7f67a7760e42ec3

**Comment by nhcarrigan** [comment]
To clarify this one, the intention here is to allow us to configure a different order if `showNewCurriculum` is on, allowing us to display the RWD beta at the bottom (for example) and move it up to the top when we release.

That being said, at the moment we aren't injecting any superblocks in the middle of the map, so we could update lines `39-49` to something like this:

```js
const superBlockToNewOrder = {
  ...superBlockToOrder,
  '2022/responsive-web-design': 12
}
```
