### ISSUE TITLE
Waypoint: Convert JSON Data to HTML -- "Run Tests" resetting content and test is not passing

### ISSUE THREAD

**Issue by MrPold** [FreeCodeCamp/FreeCodeCamp#4515]
I encountered this problem in trying to submit for a simple waypoint. It seems that clicking "Run Tests" resets the content on the "phone" and that makes it fail the automated test. This is a simple waypoint where it seems that you just are supposed to try out the code from the instructions.

Challenge [Waypoint: Convert JSON Data to HTML](http://www.freecodecamp.com/challenges/waypoint-convert-json-data-to-html?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON(%22%2Fjson%2Fcats.json%22%2C%20function(json)%20%7B%0A%0A%20%20%20%20%20%20%20%20var%20html%20%3D%20%22%22%3B%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20json.forEach(function(val)%20%7B%0A%0A%20%20%20%20%20%20%20%20%20%20var%20keys%20%3D%20Object.keys(val)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3Cdiv%20class%20%3D%20%27cat%27%3E%22%3B%0A%0A%20%20%20%20%20%20%20%20%20%20keys.forEach(function(key)%20%7B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3Cb%3E%22%20%2B%20key%20%2B%20%22%3C%2Fb%3E%3A%20%22%20%2B%20val%5Bkey%5D%20%2B%20%22%3Cbr%3E%22%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3C%2Fdiv%3E%3Cbr%3E%22%3B%0A%0A%20%20%20%20%20%20%20%20%7D)%3B%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24(%22.message%22).html(html)%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json", function(json) {

        var html = "";
        // Only change code below this line.
        
        json.forEach(function(val) {

          var keys = Object.keys(val);

          html += "<div class = 'cat'>";

          keys.forEach(function(key) {

            html += "<b>" + key + "</b>: " + val[key] + "<br>";

          });

          html += "</div><br>";

        });        
        
        // Only change code above this line.

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
   </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```
1st screen: good code in there
<img width="1280" alt="screen shot 2015-11-18 at 11 25 49 am" src="https://cloud.githubusercontent.com/assets/10596075/11238797/62fe754e-8de8-11e5-9e9a-fc833c7ad7d5.png">

2nd screen: good result on button click
<img width="1280" alt="screen shot 2015-11-18 at 11 25 57 am" src="https://cloud.githubusercontent.com/assets/10596075/11238800/66026854-8de8-11e5-9a3e-2cf8d6074f12.png">

3rd screen: clicked on "run tests", content resets back to normal and tests fail.
<img width="1280" alt="screen shot 2015-11-18 at 11 26 09 am" src="https://cloud.githubusercontent.com/assets/10596075/11238802/68a5ee6e-8de8-11e5-97c7-57f4b5232c68.png">

**Comment by tombarton** [comment]
Tests pass if you use map instead of forEach instead. I've talked about this in more detail in issue [#4516](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4516).

**Comment by shadowfool** [comment]
Can you close this issue, as it's the same as #4516
