### ISSUE TITLE
A Tiny Typo in "Comparison with the Equality Operator"

### ISSUE THREAD

**Issue by Rafeqm** [freeCodeCamp/freeCodeCamp#45160]
## Affected page

[Comparison with the Equality Operator](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator)

## Your code

[Type Coercion in Line 25](https://github.com/freeCodeCamp/freeCodeCamp/blob/1bdb03807add001b825bcebd83b4b8bc0e85bbe1/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator.md?plain=1#L25)

## Expected behavior

Fixed to Type Conversion

## Screenshots

![image](https://user-images.githubusercontent.com/87463084/154638105-8b1c8444-e7dd-403d-9442-d9550cd5364b.png)

## System

- Device: Laptop
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: Edge

**Comment by ls-madhu** [comment]
It is not a typo. **Type Coercion** is the conversion of one data type into another.

**Comment by Rafeqm** [comment]
Oh thanks for referencing the MDN Docs! Definitely never know that coercion actually exist because _coercion_ and _conversion_ do looks alike.
