### ISSUE TITLE
never was said that you can use ctrl + enter to run the tests

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45175]
## Affected page

[javascript curriculum](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)

## Your code

none

```




```

## Expected behavior

The users should be able to read somewhere at the beginning of the curriculum that they can use ctrl + enter to run the tests.

## Screenshots

no screenshots
## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by nhcarrigan** [comment]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/63889819/155391869-e4d5885c-ea8a-4c30-8265-a4796a6a26c6.png">

We could probably add a note to the button like we do for the multifule layout:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/63889819/155391936-69a276f0-ccf5-41ae-83a0-26fd3fd5fafb.png">

**Comment by ojeytonwilliams** [comment]
Seems reasonable.  That makes it consistent with the completion modal.

**Comment by nhcarrigan** [comment]
Will go ahead and open up for contribution. 😁

**Comment by wuteek** [comment]
Hello, I'm interested in taking on this task! Is there any more info I would need to help get me started?

**Comment by nhcarrigan** [comment]
Heya @wuteek!

You're certainly welcome to take this on. We recommend taking a look through our [contributing guide](https://contribute.freecodecamp.org), and hopping in to our [chat room](https://chat.freecodecamp.org/channels/contributing) if you have any questions or issues.

**Comment by wuteek** [comment]
Awesome, thank you! Would I need to have it assigned to me so I can get started?

**Comment by nhcarrigan** [comment]
Nope! We typically don't assign issues except to long-time contributors. Instead, we accept the first comprehensive PR that resolves the issue and follows our contributing guidelines.
