### ISSUE TITLE
Clicking on a informative link open another website in the same tab.

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45171]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/create-decimal-numbers-with-javascript

## To reproduce

when you click on "[Details Here](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems)." the Wikipedia webpage is opened in the same webpage.

## Recommended fix, suggestions

this is where the potential problem is located
<a href="https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems">Details Here</a>

add the attribute target="_blank" to the <a> tag.
final solution
<a target="_blank" href="https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems">Details Here</a>

## Screenshots

No need of screenshot

**Comment by LuckyLolo123** [comment]
I added the potential solution but, github changed the HTML code and the browser is rendering that code, but I think the person who is reading this got the idea.
I haven't worked with github in the past, so I don't know if this is a normal behavior of this platform.

**Comment by LuckyLolo123** [comment]
This is something I noticed too. If a person uses a mobile, I don't know what attribute the a tag could use regarding the problem of opening a completely new tab, I use chrome on my android in my phone, and I have noticed that some website have something implemented that when you open a link the browser creates a tab group, and you can easily switch between tabs of that tab group, I think this should be implemented for the mobile version
![group-tabs](https://user-images.githubusercontent.com/92828033/154766497-594db018-6eb5-4888-b8fd-ac616f8a45fd.png)
.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #39739, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
