### ISSUE TITLE
Understanding Undefined Value returned from a Function - console.log calls in seed code

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45177]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-undefined-value-returned-from-a-function
## Your code

This code, being the correct answer, is not good enough because the student will not be able to watch any output, It is proposed a potential change (read below).
```

// Setup
let sum = 0;

function addThree() {
  sum = sum + 3;
}

// Only change code below this line

function addFive() {
  sum = sum + 5;
}

// Only change code above this line

addThree();
addFive();

```
//////////////////
//NO OUTPUT//
/////////////////
## Expected behavior

I think this code should be better

// Setup
let sum = 0;

function addThree() {
  sum = sum + 3;
}
//added by me
function addFour() {
  sum = sum + 4;
  return sum;
}

// Only change code below this line

function addFive() {
  sum = sum + 5;
}

// Only change code above this line

//added by me
console.log(addThree());
console.log(addFour());
console.log(addFive());

//////////////
//OUTPUT//
/////////////
undefined
7
undefined

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional context
People learn through trial and error and from their observations. Using the original code the student won't be able to reproduce what the instruction is describing, they have to use their imagination, if you use the proposed change they will see in the output that a function with no return value will return undefined but using a return will return something, and they will notice how the use of the global variable sum was affected.

**Comment by jeremylt** [comment]
This is another case where I don't think we need to fill up the seed code for the learners. They n add their own logging statements.
