### ISSUE TITLE
Basic JavaScript - Global Scope and Functions - unclear fun2 function

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45176]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/global-scope-and-functions
## Your code

```

no code


```

## Expected behavior

There should be some kind of comment in the code because students of the curriculum with any coding knowledge couldn't know what the fun2 is trying to prove.

## Screenshots

![image](https://user-images.githubusercontent.com/92828033/154773612-21273db4-8c66-49f2-aa0b-fab57e424063.png)

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
I think whole `fun2` function could be moved to the background code, with a note in the description about what will be displaying in the console.

**Comment by Jobrien0394** [comment]
Also using back ticks for concatenation is generally the better way to teach beginners about concatenation.
For example: output += `myGlobal: ${myGlobal}` on line 16.

**Comment by abhijain2003** [comment]
I want to do this but I didn't know how can I fork it and update the affected page, can anyone guide me please

**Comment by abhijain2003** [comment]
I make an attempt of fixing this issue, but I am unable to find out the way to fork it and to update the code in the affected page. If someone knows then please tell me? 
![Screenshot 2022-03-03 214155](https://user-images.githubusercontent.com/91718608/156605031-0735a13c-777a-410e-8c83-c65d4c236f76.png)

**Comment by ShaunSHamilton** [comment]
> I think whole fun2 function could be moved to the background code, with a note in the description about what will be displaying in the console.

I would not go this route, because we have received many complaints about "hidden" code.

---

In general, I do not think there is anything to fix here. However, I would be fine just removing `func2` in its entirety. 

---

@abhijain2003 This issue is not open for contributions, yet. This issue is still being discussed.

Issues labelled with either `help wanted` or `first timers only` are open for contribution.

**Comment by NnajiChimuanya** [comment]
But instruction was given to only edit code above that line

**Comment by moT01** [comment]
Closing this so we can focus our efforts on the project based curriculum. Thanks and happy coding 🎉
