### ISSUE TITLE
Use Conditional Logic with If Statements - console.log calls in seed code

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45182]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-conditional-logic-with-if-statements
## Your code

```
function trueOrFalse(wasThatTrue) {
  // Only change code below this line
  if(wasThatTrue) {
    return "Yes, that was true";
  }
  return "No, that was false";

  // Only change code above this line

}
/////////////////////
//NO OUTPUT ////
////////////////////
```

## Expected behavior
Some examples should be added at the end of the script so that the student has some feedback on the output of his code, like this:
console.log(trueOrFalse(False));
console.log(trueOrFalse(False);

////////////
//output//
///////////

// running tests
// tests completed
No, that was false
Yes, that was true

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by c-ehrlich** [comment]
I have mixed feelings about this.

I do agree that on this lesson, and the JS Algorithms cert in general, the first thing I did most of the time was place some fairly obvious `console.log`s at the bottom of the file. So having those there by default would have made things easier.

On the other hand having to do it myself made me think about the possible inputs I wanted to test, so maybe there's also an upside to them not being there by default?

I'm not sure and would be interested in hearing other opinions.

**Comment by LuckyLolo123** [comment]
What you are saying is true, I didn't think about it, I suggest doing something like a multistep minichallenge, like, when you click on run test, FCC will ask you to uncomment the possible console.log at the bottom of the file in order to see the result on the output in case you haven't done that by yourself. Saying this, I think this should be a kind of implicit instruction, or at least, the instruction should say something like "and show the output of calling the functions two times using as argument True and false"

**Comment by jeremylt** [comment]
I disagree with this suggestion. I'm not big on adding extra noise into the seed text. Also, somewhere along the way learners should decide for themselves if they want to run some test cases  of their own and what those test cases are.

**Comment by raisedadead** [comment]
I am in agreement with @jeremylt here. We do not want to hold hands more than it's necessary. Going to go ahead and close this. Thanks for your contribution & feedback everyone.
