### ISSUE TITLE
[EDITED] another (sorry, again) light visual/order improvement to the explanation of content

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45185]
## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-strict-inequality-operator
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-greater-than-operator
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-greater-than-or-equal-to-operator
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-less-than-operator
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-less-than-or-equal-to-operator

sorry for the several and similar new issues I have opened so far, I didn't know there were some of them that are very similar, I will keep adding them here.
!!!!!!!!!!!
!!!!EDIT: I think there are no more links left
!!!!!!!!!!

## Your code

```




```

## Expected behavior
same as:
https://github.com/freeCodeCamp/freeCodeCamp/issues/45183

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
I've added links from here to the first issue.
