### ISSUE TITLE
another light visual/order improvement to the explanation of content

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45184]
## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-inequality-operator

## Your code

```




```

## Expected behavior
Same as:
https://github.com/freeCodeCamp/freeCodeCamp/issues/45183

but another other link

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
I've added link from here to the first issue.
