### ISSUE TITLE
Weird Instructions -> Add Elements to the End of an Array Using concat Instead of push

### ISSUE THREAD

**Issue by haplorhine** [freeCodeCamp/freeCodeCamp#45194]
## Affected page

[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/add-elements-to-the-end-of-an-array-using-concat-instead-of-push](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/add-elements-to-the-end-of-an-array-using-concat-instead-of-push
)
## Your code

```
function nonMutatingPush(original, newItem) {
  // Only change code below this line
  return original.concat([newItem]); //[ 1, 2, 3, [ 4, 5 ] ]

  // Only change code above this line
}

const first = [1, 2, 3];
const second = [4, 5];
nonMutatingPush(first, second);

```

## Expected behavior

Since newItem, which references an array should be added to the original array (per the instructions), I expected to pass the test. Instead it says "nonMutatingPush([1, 2, 3], [4, 5]) should return [1, 2, 3, 4, 5].", which would be concatenating the two arrays, but it isn't a non mutating alternative to `.push()` as the instructions suggest.

## Screenshots

<img width="1437" alt="fcc-challenge" src="https://user-images.githubusercontent.com/36515150/154822464-1803be5f-91cb-4036-b299-12961306411c.png">

## System

- Device: [laptop]
- OS: [macOS]
- Browser: [chrome]

**Comment by ls-madhu** [comment]
@haplorhine the function should return original.concat(newItem).
You put the newItem in an array literal, due to which the test is failing.

**Comment by jeremylt** [comment]
I see what you are saying. Really, the challenge is asking you to replicate the effect of using push with the spread operator. I'm not sure what change to the wording would make this clearer. Do you have any suggestions?

**Comment by haplorhine** [comment]
@ls-madhu it also fails without literal syntax, e.g.:

```
function nonMutatingPush(original, newItem) {
  // Only change code below this line
  return original.concat(new Array(newItem));
  // Only change code above this line
}

const first = [1, 2, 3];
const second = [4, 5];
nonMutatingPush(first, second);
```

I know that it will pass when I write `return original.concat(newItem);` but this is the problem, because the instructions say:
```
const arr = [1, 2, 3];
arr.push([4, 5, 6]);
```
would result in arr having the value `[1, 2, 3, [4, 5, 6]]`. So i suppose a function named "nonMutatingPush" should have a similar effect as push namely creating a "two dimensional"-Array in this case, like in the example in the instructions, and not do something entirely different (ie. merging the content of the two arrays into a new array)

**Comment by haplorhine** [comment]
@jeremylt The challenge doesn't say anything about using a spread operator, instead it asks users to "Change the nonMutatingPush function so it uses concat to add newItem to the end of original instead of push".
Pushing an array to an array would produce an array in an array. Since "The concat() method is used to merge two or more arrays" ([https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)) to replicate the effect of push one needs to put the array about to be "pushed" into a new array, so the outer array gets merged and the inner array stays intact.
My suggest if replicating the push behaviour isn't the case (but merging the two given arrays), the instructions should ask users to "Change the nonMutatingPush function so it uses concat to merge newItem with original."

**Comment by ls-madhu** [comment]
@jeremylt Yeah makes sense to me. And since merging two arrays is taught in the previous lesson, I think the goal of this lesson is to replicate the behaviour of push using concat. In that case, my suggestion would be: "Change the nonMutatingPush function so it uses concat to replicate the behaviour of push without altering the first and second arrays".

**Comment by jeremylt** [comment]
I think we need to be car. The intended behavior is better. We don't want the users to concat a reference to the second array.

**Comment by pranav1597** [comment]
![concatArray](https://user-images.githubusercontent.com/78584781/154940129-528539f5-1e2c-4c75-9289-dc33299b34eb.jpg)
you need to assign original.concat(newItem) to a new variable and return it

**Comment by ojeytonwilliams** [comment]
As far as I can see the idea here is the user should create a function that behaves like `push()`, but it returns a new array instead of modifying the array it's called on.

That function can be implemented as follows

```
function nonMutatingPush(original, newItem) {
  return original.concat([newItem]);
}
```

This replicates `push` as closely as possible, so that if I
```js
let first = [1, 2, 3];
let second = [4, 5];
let third = nonMutatingPush(first, second);

console.log(third); // [ 1, 2, 3, [ 4, 5 ] ]
second.push(6)
console.log(third); // [ 1, 2, 3, [ 4, 5, 6 ] ]
```

in the same way as if I used push

```js
let first = [1, 2, 3];
let second = [4, 5];

first.push(second)
console.log(first) // [ 1, 2, 3, [ 4, 5 ] ]
second.push(6)
console.log(first) // [ 1, 2, 3, [ 4, 5, 6 ] ]
```

So, the main issue is that both the solution and the final test need updating.

Also @ls-madhu's wording, 
> "Change the nonMutatingPush function so it uses concat to replicate the behaviour of push without altering the first and second arrays"

should help guide users down the right path.

**Comment by jeremylt** [comment]
If we want users to learn a "non mutating push", I think its better that the solution not provide an avenue to mutate the original arrays.
```javascript
const first = [1, 2, 3];
const second = [4, 5];
const third = first.concat([second]);

third[3].push(6);
console.log(third); // [ 1, 2, 3, [ 4, 5, 6 ] ]
console.log(second); // [ 4, 5, 6 ] I hate this....
```

I think the current intended solution is fine but the wording describing it isn't quite accurate.

**Comment by ls-madhu** [comment]
@jeremylt I think it would be better to compare:

```js
first.push(4,5,6);
// and
first.concat([4,5,6]);
```

**Comment by GHSid** [comment]
IMHO, it is necessary either to change the expected solution
`return original.concat([newItem])`
or the wording of the task.
For example:

> "Change the nonMutatingPush function so it uses concat to add **_the contents of_** newItem to the end of original instead of push. The function should return an array."

P.S.: It seems to me that it is better to change the expected solution (based on the previously described behavior of the push method)

**Comment by jeremylt** [comment]
I wouldn't change the expected behavior.. If we change the expected behavior, then this is no longer a non-mutating function. We should modify the description.

**Comment by GHSid** [comment]
I agree with any of your solutions, but I did not understand - why would another solution cease to be a non-mutating function?

**Comment by jeremylt** [comment]
If you change the expected behavior, then if `newItem` is an array, the output of this function can be used to mutate `newItem`, as I explained above.

**Comment by GHSid** [comment]
Thank you. I understand what you mean... - but then it looks like we are deliberately simplifying the task to meet the requirements. Maybe it's better to just replace the expected behavior with `return original.concat([[...newItem]])`?

**Comment by jeremylt** [comment]
I don't see how this would be a simplification. The current solution works fine. Not changing the solution wouldn't make the task simpler - it would make it identical to what it is right now. We just need to describe the task more accurately.

**Comment by GHSid** [comment]
We show that we can get this result with push: [1, 2, 3, [4, 5]], and then we ask to get [1, 2, 3, 4, 5] with concat?.. Well... - Ok. Thank you for your time.

**Comment by jeremylt** [comment]
Right.... You highlighted exactly the [wrong] description that I want replaced. Using push like that mutates one array and allows for the mutation of the other. The current solution to the challenge prevents mutation of both. The description should reflect that fact. Changing the solution to permit mutation of one of the arguments misses the idea of making a more functional solution to using push.

**Comment by adi-uchiha** [comment]
Can I work on this ?

**Comment by jeremylt** [comment]
Sure. We don't assign issues - we accept the first complete PR that addresses the issue.

In ttis case, we are looking for someone to update the description of the challenge so that is clear that we want a non-mutating push.

**Comment by DerrykBoyd** [comment]
I've read through the full thread and submitted a PR that I think should satisfy most, if not all, concerns with the description.
