### ISSUE TITLE
CamperBot's code format help link broken

### ISSUE THREAD

**Issue by chautob0t** [FreeCodeCamp/FreeCodeCamp#4519]
In the Gitter application, when I tried to paste a code, CamperBot's help link is this - 
![camper](https://cloud.githubusercontent.com/assets/8208082/11243254/04cb2978-8e2d-11e5-9759-708bc0eac34e.PNG)
https://github.com/freecodecamp/freecodecamp/wiki/code-formatting

This should be changed to this - https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-format

**Comment by bugron** [comment]
@chautob0t thanks for posting this issue!
Please, post Camperbot related issues in [FreeCodeCamp/camperbot](https://github.com/FreeCodeCamp/camperbot) repository, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by chautob0t** [comment]
My bad, thank you. Posting in the correct repo.
