### ISSUE TITLE
Challenge (Create a Form Element): Remove root relative path from action URL in example

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45200]
Challenge: https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element

This is a very minor "issue". But I have seen a few people on the forum adding the `/` in front of the absolute URL and I think it is because of the example code given. I would suggest we just remove the slash.

Example code:

```
<form action="/url-where-you-want-to-submit-form-data">
  <input>
</form>
```

So just this instead:

```
<form action="url-where-you-want-to-submit-form-data">
  <input>
</form>
```

Not sure if, or where, we teach about paths. But I think most paths used in the curriculum are absolute or relative.

**Comment by Jagrutiti** [comment]
@lasjorg shall I take this up?

**Comment by omegapaulo** [comment]
Is anyone dealing with this issue? I could take upon it and make the PR if it's okay for everyone.

**Comment by Jagrutiti** [comment]
> Is anyone dealing with this issue? I could take upon it and make the PR if it's okay for everyone.

I am. I'll let you know if it doesn't work for me,
