### ISSUE TITLE
Convert flaky e2e tests to unit tests

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#45205]
## Issue

At the moment, pull requests coming to the [Code Radio repo](https://github.com/freeCodeCamp/coderadio-client) are not mergeable due to a failed test. I believe this is a Cypress issue, as reported in https://github.com/cypress-io/cypress/issues/4383. 

## Suggested solution

Since purpose of the failed test is just to check if some certain links are shown on the page, and no complex interactions involved, we can simply convert the test to unit test to unblock the open PRs. This will also help reduce CI time a bit, since end-to-end tests are slower than unit tests.

What we need to do are:
- Set up [React Testing Library](https://testing-library.com/docs/react-testing-library/setup) and [jest-dom](@testing-library/jest-dom) with its recommended ESLint plugins ([eslint-plugin-testing-library](https://testing-library.com/docs/ecosystem-eslint-plugin-testing-library) and [eslint-plugin-jest-dom](https://testing-library.com/docs/ecosystem-eslint-plugin-jest-dom))
- Write unit tests that are equivalent to [these end-to-end tests](https://github.com/freeCodeCamp/coderadio-client/blob/main/cypress/integration/nav-bar-links.js)
- Remove the end-to-test test file
- Update the CI workflow to include running unit tests

**Comment by huyenltnguyen** [comment]
I'm familiar with the process and happy to work on this myself, but my schedule is quite packed right now. So before I'm able to pick this up, if anyone is interested in this issue feel free to beat me to it.

**Comment by huyenltnguyen** [comment]
Hey @Jagrutiti, it is correct that you need to clone the Code Radio repo, create a new branch from there, make changes to it and submit a PR against the FCC's Code Radio repo.

The output above looks okay, the `npm test` command runs on the existing `App.test.js` file and things are working as expected.

I'm sorry about this, but one thing I forgot to mention is that we should pin the libraries version in the `package.json` file, meaning there shouldn't be a caret character (`^`) before the version number. So if you see the character in the file, please remove it and run `npm install` again.

Now with RTL and jest-dom having been set up, we can proceed to write new unit tests. I don't know how familiar you are with unit tests in general, so I apologize if I'm over-explaining. We will need to write unit tests that are equivalent to [this one](https://github.com/freeCodeCamp/coderadio-client/blob/main/cypress/integration/nav-bar-links.js) in order to replace it. What we need to do is to render the [Nav component](https://github.com/freeCodeCamp/coderadio-client/blob/main/src/components/Nav.js), then check if there are links on the page. That means we will need to create a `Nav.test.js` file.

I'm not on the computer that has the repo pulled down so I can't validate what I write here is 100% correct, but just to give you an idea of how the tests should be written:

```jsx
// in Nav.test.js
import React from 'react'
import { render, screen } from '@testing-library/react'

import Nav from './Nav'

describe('<Nav />', () => {
  it('should render a link to the News page', () => {
    // Render the Nav component
    render(<Nav />)
    
    // Find a link with the text 'News' in the component - I'll explain more
    const newsLink = screen.getByRole('link', { name: 'News' })
    
    // Assert that the link exists
    expect(newsLink).toBeInTheDocument()
    // Assert that the link points to the correct page
    expect(newsLink).toHaveAttribute('href', 'https://www.freecodecamp.org/news/')
  })

  it('should render a link to the Forum page', () => {})
  it('should render a link to the Learn page', () => {})
})
```

I hope the snippet above helps communicate the idea, but since you're not familiar with RTL, I think the most confusing part would be the line with `getByRole`. I can go a bit more in the details if you are interested, but to avoid overwhelming you, when it comes to querying an item in the DOM, `getByRole` is the recommended method. The method helps ensure that we are using an appropriate HTML element for the links, and not, say, an `input`, or a `p`, or a mere `div`. 

And if you compare this with the Cypress file, we are missing the [status check for the target pages](https://github.com/freeCodeCamp/coderadio-client/blob/main/cypress/integration/nav-bar-links.js#L11-L13). I think it is totally fine and we just need to ensure that Code Radio displays the correct links. It is the responsibility of the other platforms to make sure their pages are working properly.

---

Once we have the unit test file ready, we can proceed to:
- Delete the end-to-end test file
- Update the [CI workflow](https://github.com/freeCodeCamp/coderadio-client/blob/main/.github/workflows/ci.yml) to include the `npm test` step

**Comment by Jagrutiti** [comment]
Hi, @huyenltnguyen I am excited to share my progress with you. 

Starting with essentials. I ran the `npm install` after removing the carat character from `package.json` as you had suggested. All went fine.

`getByRole` sure was tricky. But nothing a good R&D can't beat. 

This line `const newsLink = screen.getByRole('link', { name: 'News' })` in the code threw the following error:

```
      10 |     
      11 |     // Find a link with the text 'News' in the component - I'll explain more
    > 12 |     const newsLink = screen.getByRole('link', { name: 'News' })
         |                             ^
      13 |     
      14 |     // Assert that the link exists
      15 |     expect(newsLink).toBeInTheDocument()

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:38:19)
      at getElementError (node_modules/@testing-library/dom/dist/query-helpers.js:25:35)
      at getMultipleElementsFoundError (node_modules/@testing-library/dom/dist/query-helpers.js:29:10)
      at node_modules/@testing-library/dom/dist/query-helpers.js:66:13
      at getByRole (node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
      at Object.<anonymous> (src/components/Nav.test.js:12:29) 
```

Dived a little deeper into `getByRole`. With the help of `react-testing-library`  documentation and [Testing Playground](https://testing-playground.com/) I came up with this solution:`    const newsLink = screen.getByRole('link', { name: /news opens in new window/i })
`

Rest is history. All three test cases passed. This is the output of `npm test`:

```
 PASS  src/components/Nav.test.js
  <Nav />
    ✓ should render a link to the News page (116 ms)
    ✓ should render a link to the Forum page (41 ms)
    ✓ should render a link to the Learn page (32 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.408 s, estimated 2 s
Ran all test suites related to changed files.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.

```
Here is the complete code in `Nav.test.js` file:

```
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';

import Nav from './Nav';

describe('<Nav />', () => {
  it('should render a link to the News page', () => {
    // Render the Nav component
    render(<Nav />);

    // Find a link with the text 'News' in the component - I'll explain more
    // const newsLink = screen.getByRole('link', { name: 'News' })

    const newsLink = screen.getByRole('link', {
      name: /news opens in new window/i
    });
    // Assert that the link exists
    expect(newsLink).toBeInTheDocument();
    // Assert that the link points to the correct page
    expect(newsLink).toHaveAttribute(
      'href',
      'https://www.freecodecamp.org/news/'
    );
  });

  it('should render a link to the Forum page', () => {
    // Render the Nav component
    render(<Nav />);

    // Find a link with the text 'Forum' in the component
    const forumLink = screen.getByRole('link', {
      name: /forum opens in new window/i
    });

    // Assert that the link exists
    expect(forumLink).toBeInTheDocument();

    // Assert that the link points to the correct page
    expect(forumLink).toHaveAttribute(
      'href',
      'https://www.freecodecamp.org/forum/'
    );
  });

  it('should render a link to the Learn page', () => {
    // Render the Nav component
    render(<Nav />);

    // Find a link with the text 'Forum' in the component
    const learnLink = screen.getByRole('link', {
      name: /learn opens in new window/i
    });

    // Assert that the link exists
    expect(learnLink).toBeInTheDocument();

    // Assert that the link points to the correct page
    expect(learnLink).toHaveAttribute(
      'href',
      'https://www.freecodecamp.org/learn/'
    );
  });
});
```
If the code looks good to you, I will move to the next steps you mentioned. I am a little clueless about updating `CI workflow` though. Also which file is the end-to-end test file?

Thanks for your invaluable guidance. I learned something new today.

**Comment by huyenltnguyen** [comment]
> Dived a little deeper into `getByRole`. With the help of `react-testing-library` documentation and [Testing Playground](https://testing-playground.com/) I came up with this solution: `const newsLink = screen.getByRole('link', { name: /news opens in new window/i })`

Ah ha! I'm pretty sure this is from a recent change that I missed. Thanks for catching this! 👍 Also, great to hear you have made progress with the tests.

I think at this point we can create a pull request, so that it's easier to review the work as well as to test the CI workflow.

For CI workflow update, we should add a new `test` step to the `ci.yml` file. The change should be similar to this block: https://github.com/freeCodeCamp/coderadio-client/blob/main/.github/workflows/ci.yml#L6-L22. There is a list of checks in every PR, and we can verify if our change is correct by finding the new step in the list. Now that it's weekend and I have some free time, I can help you with this step though. 

<img width="929" alt="Screen Shot 2022-02-26 at 21 35 35" src="https://user-images.githubusercontent.com/25715018/155847053-ec3dcc24-e9ef-4365-855e-1a98f696c1c9.png">

As for the end-to-end test file we need to delete, it's this one: https://github.com/freeCodeCamp/coderadio-client/blob/main/cypress/integration/nav-bar-links.js

**Comment by Jagrutiti** [comment]
Hi @huyenltnguyen I have made this pull request https://github.com/freeCodeCamp/coderadio-client/pull/233

I am not sure about adding the `test` step to `ci.yml`. What new things do I need to add to the `test` step?  

Did not delete the end-to-end test file because it will be safe to delete the file once you have reviewed the code.

**Comment by huyenltnguyen** [comment]
Thanks for the PR! 

I have added some comments to it and I will take over the CI workflow change. To prevent code conflicts, I will be pushing commits to your branch after those comments have been addressed. No rush though 🙂

**Comment by Jagrutiti** [comment]
@huyenltnguyen Working with you was a pleasant learning experience. Hope to collab in the future as well :)
