### ISSUE TITLE
Add Flash component to the component library

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#45206]
Previously in the refactoring of the `Alert` component, we said that we would need to build a `Flash` component also, because with the current implementation of `Alert`, it is a combination of both (see https://github.com/freeCodeCamp/freeCodeCamp/pull/45015#discussion_r802387268).

I'm moving the discussion here so that we can continue to discuss.

@ahmadabdolsaheb If you're okay with my approach I can update the main issue to include `Flash` as well as making changes to the Alert component to correct its implementation 🙂

**Comment by ahmadabdolsaheb** [comment]
Thanks for discussing our implementation options in details and creating an issue for adding the flash component.

Both approaches have their advantages, so either way should work. 

That being said, adding the flash component could wait until we replace the components that are imported directly from react-bootstrap so we could remove that dependency completely. Then, we could shift our focus and create custom components such as flash accordingly.
