### ISSUE TITLE
Bug "chai is not defined"

### ISSUE THREAD

**Issue by SarunasP** [FreeCodeCamp/FreeCodeCamp#4522]
Despite doing the excersize correctly (I believe) the console output gives me an error. I assume this is a bug.

Challenge [Waypoint: Generate Random Whole Numbers within a Range](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range?solution=var%20ourMin%20%3D%201%3B%0A%0Avar%20ourMax%20%3D%209%3B%0A%0Afunction%20ourFunction()%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myMin%20%3D%200%3B%0Avar%20myMax%20%3D%2010%3B%0A%0Afunction%20myFunction()%20%7B%0Areturn%20Math.floor(Math.random()%20*%20(myMax%20-%20myMin%20%2B1))%20%2B%20myMin%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%0A(function()%7Breturn%20myFunction()%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourMin = 1;

var ourMax = 9;

function ourFunction() {

  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;

}

// Only change code below this line.

var myMin = 0;
var myMax = 10;

function myFunction() {
return Math.floor(Math.random() * (myMax - myMin +1)) + myMin;
}

// Only change code above this line.


(function(){return myFunction();})();

```

**Comment by SarunasP** [comment]
Nevermind, the issue fixed itself when I stopped using my VPN.

**Comment by shadowfool** [comment]
Code seems to work fine

**Comment by bugron** [comment]
@SarunasP thanks for posting this issue!
Closing. Also note that FCC normally won't work if you're behind any proxy servers or you're using any anonymizing software/browser extension. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
