### ISSUE TITLE
Challenge (Use the .env File): Clarify accessing process.env inside route hander

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45231]
We get so many forum posts all with the same issue with this challenge.

People are accessing the environment variables outside the route handler, which doesn't work with the test. If we can somehow make it more clear where the variable should be accessed it would really help.

Challenge: https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file

**Comment by ShaunSHamilton** [comment]
I agree that this continues to be a problematic challenge, but how much clearer do you get than:
> Then, in the `/json GET` route handler you created in the last challenge,

**Comment by lasjorg** [comment]
I don't actually think the sentence makes it that clear that the environment variable has to be evaluated inside the route handler. I would consider it unexpected behavior and it should be explained better.

> *Note:* Because of how testing is performed you must access `process.env.MESSAGE_STYLE` _inside_ the route handler.

Or restructure the sentence somehow.

> Then, in the `/json` GET route handler you created in the last challenge access `process.env.MESSAGE_STYLE` and transform the response object's message to uppercase if it equals `uppercase`.

**Comment by nhcarrigan** [comment]
> Then, in the /json GET route handler you created in the last challenge, transform the response object's message to uppercase if process.env.MESSAGE_STYLE equals uppercase

It's a bit of a clunky structure and I agree it could be worded better.
