### ISSUE TITLE
It should be done some emphasis in a keyword

### ISSUE THREAD

**Issue by LuckyLolo123** [freeCodeCamp/freeCodeCamp#45233]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for---in-statement
## Your code

```




```

## Expected behavior
I think <i><strong>"all the keys"</strong></i> should be remarked someway, I spent a relatively good amount of time asking myself why my function was not returning the object. Maybe other people have experienced the same.

## Screenshots

![image](https://user-images.githubusercontent.com/92828033/155446410-d3a8f4ce-f2e1-49ec-8211-a36ba8aeb2c2.png)

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by raisedadead** [comment]
The idea is to force users to read? Spending time, getting stumped, and discovering the pitfall is part of the learning process. 

I do see your intention. I would encourage you to post such issues (which are of opinion) on the forum before opening them up here to get more support for such a change. The forum gets substantially more traffic from peers like others students/users than this GitHub tracker.

Cheers.

**Comment by LuckyLolo123** [comment]
the Responsive Web Design (Beta) is full of this kind of pattern, every keyword is emphasized, and the objective of the curriculum is achieved, to finish every minichallenge in less than 2 min and so stay in the freecodecamp website all the time, this is one of the reasons that I was able to learn it in a relatively short amount of time and didn't feel burnt out of stuck most of the time. But, I am just a person trying to contribute.

> Spending time, getting stumped, and discovering the pitfall is part of the learning process.
For beginners, I don't think so, because you don't want them to lose motivation.

**Comment by ojeytonwilliams** [comment]
@LuckyLolo123 we understand that you're trying to contribute and that's definitely appreciated.  It's just that the forum is the ideal place for highly subjective discussions like this.
