### ISSUE TITLE
Challenge (Use the .env File) delete the property instead of setting it to undefined

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45247]
Technically, if we are testing for a non-existing property we can't set `process.env.MESSAGE_STYLE` to `undefined` as that is implicitly converted to a string.

> [process.env](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_process_env)
> 
> Assigning a property on process.env will implicitly convert the value to a string.

This means you can't use this logic

```
// process.env.MESSAGE_STYLE = 'uppercase'

let message = process.env.MESSAGE_STYLE ? {"message": "HELLO JSON"} : {"message": "Hello json"}

console.log(message) // { message: 'HELLO JSON' }

process.env.MESSAGE_STYLE = undefined;
console.log(typeof process.env.MESSAGE_STYLE) // string

message = process.env.MESSAGE_STYLE ? {"message": "HELLO JSON"} : {"message": "Hello json"}
console.log(message) // { message: 'HELLO JSON' }
```

But if you delete it, it works.

```
delete process.env.MESSAGE_STYLE
message = process.env.MESSAGE_STYLE ? {"message": "HELLO JSON"} : {"message": "Hello json"}
console.log(message) // { message: 'Hello json' }
```

The forum thread that made me open this issue:

https://forum.freecodecamp.org/t/use-the-end-file/498485

---

Challenge: https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file

Test: https://github.com/freeCodeCamp/fcc-express-bground-pkg/blob/master/index.js

**Comment by nhcarrigan** [comment]
Hmm, I think this warrants some further discussion.

I do agree that `process.env.MESSAGE_STYLE = undefined;` is an issue and should be fixed. However, I'm not sure that `let message = process.env.MESSAGE_STYLE ? {"message": "HELLO JSON"} : {"message": "Hello json"}` should be considered valid logic.

It seems like an anti-pattern to allow a truthiness check to pass a challenge that expects a specific value.

**Comment by lasjorg** [comment]
I'm not suggesting that using this type of logic is the correct way of checking (in the client code) for the presence of a value on an environment variable. You would normally look for the string value (e.g. 'development').

However, if you just consider the presence of the string value as a "Boolean" (i.e. it exists or not) you should be able to check for it as such. The only reason you can't is that we set it to a value that isn't actually a falsy value but a string value. Setting the environment variable to the string `"undefined"` is equivalent to setting it to any arbitrary string that isn't the string `"uppercase"`.

I don't think setting the environment variable to the string `"undefined"` is in any way the correct thing to do. It's misleading and makes the test code look like it is doing something it isn't. Secondly, we are looking for the absence of the string value, and setting it to another string value just isn't the same.

I don't see an issue with the fix I propose, but if there is one I'd like to hear it.

**Comment by nhcarrigan** [comment]
> Setting the environment variable to the string "undefined" is equivalent to setting it to any arbitrary string that isn't the string "uppercase".

Which is, IMHO, what we should do.

> I don't think setting the environment variable to the string "undefined" is in any way the correct thing to do. It's misleading and makes the test code look like it is doing something it isn't.

I agree.

> Secondly, we are looking for the absence of the string value, and setting it to another string value just isn't the same.

This is the bit I'm confused on. The challenge asks "transform the response object's message to uppercase if process.env.MESSAGE_STYLE equals uppercase", which to me means a specific equality check rather than a truthiness test.

**Comment by lasjorg** [comment]
> Which is, IMHO, what we should do.

Why? I'm not sure I understand the logic here?

1. We check that the value is set to the expected string and that we get the expected response.

2. We remove the value and check that we get the expected response.

Why would setting the environment variable to some random string value be better than removing it?

**Comment by nhcarrigan** [comment]
Because it would prevent code like the one above from passing, without the ambiguity of setting it to `undefined`.

**Comment by lasjorg** [comment]
I still don't get it.

If you have an environment variable in your code that isn't being set then sure it wouldn't match the string you are looking for, but it also wouldn't be some random string value. It simply wouldn't be there. If the property was missing it would be `undefined`, if the value was missing it would be `undefined`. At no point in a real project would the absence of the property or value result in some random string being placed on it.

Removing the property seems to me to be what closest emulates a real-world senario.

**Comment by lasjorg** [comment]
I don't think we should change expected behavior to force code to conform with some idea of what is, or isn't an anti-pattern. That just doesn't seem like a good idea to me. If something would work in real-world code it should ideally work in an "emulated" setup. If we change the expected behavior that may result in misleading conclusions on the part of the student.

Again just to clarify, I do agree that the code in question isn't how you would want to write it. However, that still doesn't change the fact that it in fact should work.

**Comment by nhcarrigan** [comment]
What if, instead of a random string, we set it to a typo like `UPERCASE`? That would assert that their logic is in line with the challenge and emulate a real world scenario.

**Comment by lasjorg** [comment]
I just don't understand the point? Why is removing the property wrong when it clearly is what the intention of the original code is? The point of setting it to undefined is to emulate it not having a value. Why would that be a problem and how is setting the variable to some magic string behind the user's back not completely unexpected?

This environment variable _is_ acting as a Boolean, it never is set to any other string value (by anyone other than us). It does not contain two possible values used for switching between responses. If it was we would have the client code set it to the two values `uppercase` and `lowercase`. Which would be fine with me, but it isn't how the challenge was implemented.

---

Anyway, if people think we should set it to some string value then I can update the code. I just don't agree with it that's all.
Sorry if it seems like I'm being argumentative. I'm just trying to understand the logic here.

**Comment by ShaunSHamilton** [comment]
In my experience, it has bitten me in the back many times, in recent months, assuming `ENV_VAR=false` did anything for a check of `if (process.env.ENV_VAR)`.

That is, I need to constantly be reminded that environment variables are treated like that.

---

So, if the lesson instructions are:
> transform the response object's message to uppercase if `process.env.MESSAGE_STYLE` equals `uppercase`

Then, regardless of what `process.env.MESSAGE_STYLE` is, it should result in the _"object's message [being] uppercase"_

That is, if `process.env.MESSAGE_STYLE=foo` or `process.env.MESSAGE_STYLE=undefined`, the object's message should **not** be uppercase.

**Comment by lasjorg** [comment]
Setting `process.env.MESSAGE_STYLE` to `undefined` is simply checking what happens when the value is anything other than `uppercase`. So far so good.

Setting it to _any_ truthy value for this test is in my opinion wrong. We should give them expected values. The expected value when not set is `undefined`. What the user decides to do with the value is 100% up to the user.

**Comment by lasjorg** [comment]
if `object.value === "uppercase"` is `true`, `value` is `"uppercase"`

if `object.value !== "uppercase"` is `true`, `value` is ???

I'm not suggesting inferring the type is a good idea, but what if you had to guess?

A safe guess would be an "Any type" but that is just a cop-out.

You might say if the value was initialized to a string value, it should be a string. OK, but what if the value can be missing? That would make it an optional string, or `string | undefined`. This is an object property, if it or its value is missing it is `undefined`.

The user doesn't know what the value is when `value !== "uppercase"` but inferring a falsy value, while not a good idea, isn't that unreasonable either. Always receiving a truthy value seems unexpected to me based on the challenge setup.

The user is setting the value, we are emulating what happens if it is not the correct value, as such we can set it to anything to test. However, in doing so we are changing _a user set value_ **without** the user knowing about it. Based on the challenge setup, having it always be a truthy string value is, in my opinion, unexpected.

---

I still do not see the problem with removing the property to test for `object.value !== "uppercase"`

**Comment by jeremylt** [comment]
> if `object.value === "uppercase"` is `true`, `value` is `"uppercase"`
> 
> if `object.value !== "uppercase"` is `true`, `value` is ???

> Then, in the /json GET route handler you created in the last challenge, transform the response object's message to uppercase if process.env.MESSAGE_STYLE equals uppercase. **The response object should either be {"message": "Hello json"} or {"message": "HELLO JSON"}, depending on the MESSAGE_STYLE value.**

Again, letting the user decide to ignore the value of the environment variable and instead use its truthiness is a fundamentally different exercise. I'm fine with that exercise existing, but that would require changing the instructions of this exercise. 

I think having a challenge where the user has to check not only the existence but also the value of the environment variable is important. That is currently what the instructions require for this challenge.

**Comment by jeremylt** [comment]
Case `MESSAGE_STYLE === "uppercase"`:

> transform the response object's message to uppercase if process.env.MESSAGE_STYLE equals uppercase. 

Case `MESSAGE_STYLE !== "uppercase"`:

> The response object should either be `{"message": "Hello json"}` or `{"message": "HELLO JSON"}`, depending on the MESSAGE_STYLE value.

Specifically, I'm focused on the words **depending on the `MESSAGE_STYLE` value.**

Absolutely nowhere have I mentioned the user code from the forum. I don't like their code, but I'm talking about the instructions as written.

If we instead changed the tests to ignore the value of the `MESSAGE_STYLE`, then the instructions should correspondingly change to **depending upon if the `MESSAGE_STYLE` variable has been set** and we should probably change the name of the environment variable to be consistent with its change into a boolean flag.

**Comment by jeremylt** [comment]
I don't care what we set it to when `MESSAGE_STYLE !== "uppercase"`. I agree that alternative values are not currently in the speciation.

I do care that the exercise checks that the user understands they can the the *value* out of the environment variable and use it like any other value stored in a variable. Getting the exact value out is useful. 

If we change then tests to remove the environment variable all together, then we don't know if the user understands that they have access to the value of the environment variable. But that's a very useful thing for them to know.

**Comment by lasjorg** [comment]
> I don't care what we set it to when `MESSAGE_STYLE !== "uppercase"`. I agree that alternative values are not currently in the speciation.

I mean that is the whole point of this issue though. So you are OK with it being `undefined`?

No one has posted a good reason why we shouldn't remove the property when testing the response for `MESSAGE_STYLE !== "uppercase"`.

@nhcarrigan said because it allows for an anti-pattern.

I don't agree with us preventing users from creating code that uses anti-patterns. That is not our responsibility. The only responsibility we have here is to make sure we provide a trustworthy environment with expected behavior. Having the environment variable contain a value that the user didn't set is unexpected behavior.

**Comment by jeremylt** [comment]
I keep repeating a very good reason.

If we go with your proposed change, then the user can pass the challenge by only checking if the environment variable exists.

That means that we don't verify that the user understands how to get *values* out of environment variables. 

Knowing how to get *values* out of environment variables is important.

Thus, removing the check that the user knows how to access the *value* (not just the fact that the variable was set) would be reducing the volume of knowledge required to pass the challenge.

**Comment by lasjorg** [comment]
> If we go with your proposed change, then the user can pass the challenge by only checking if the environment variable exists.

But that _is_ the expected behavior.

> That means that we don't verify that the user understands how to get values out of environment variables.

We also do not know if they have a full understanding of JS and are leveraging it to write code the way they want to write code (good or bad).

If all we need to confirm is that they know how to set the environment variable and use it we can just have it in the response.

`res.json({ message: "The message is " + environment_variable})`

But we are not doing that. We are asking them to use the environment variable to make a logical branching decision. As such it does matter that the value contain expected values. And when a property value isn't set, it is `undefined`.

**Comment by jeremylt** [comment]
>  If we go with your proposed change, then the user can pass the challenge by only checking if the environment variable exists.

> But that is the expected behavior.

Ok. Then we need to

1) remove all references to the value of the environment variable from the instructions 

2) change ` MESSAGE_STYLE` to a name consistent with a  boolean flag

3) Remove the `=== "uppercase"` information as irrelevant

**Comment by lasjorg** [comment]
Well, we definitely need to decide what this challenge is doing and what it is teaching because as it stands now that isn't even clear to me.

Again if we just want to check the env is set and used then why not just have the response with the env value?

On the other hand, if we want to teach how to use an env that can have more than one value, like what you have with "development" and "production", we should set it up as such with two different known values and have the user make a logical branching decision based on the known values.

**Comment by jeremylt** [comment]
I thought it was trying to teach accessing environment variable *values*. That seemed obvious to me from the instructions, but maybe not. 

What I don't think is clear is the fact that the test suite has the ability to modify the environment at runtime, which has caused most of the confusion that I've seen on the forum.

I think both use cases (boolean flag or actual value) are important. I don't want to lose the second in an effort to reduce the confusion in the current instructions.

**Comment by lasjorg** [comment]
I think this should ideally have been two challenges. One that simply tests for setting and using an env value and then one that uses the env for making logical branching.

Or if combined as it is now, the two possible values should be fixed and the user should know the values.

```
if (env.value === 'uppercase') {
  res.json({ message: env.value.toUpperCase() })
} else if (env.value === 'LOWERCASE') {
  res.json({ message: env.value.toLowerCase() })
}
```

**Comment by jeremylt** [comment]
Two challenges would definately be better, but I thought we weren't adding challenges? 

I agree that it would make more sense if there was more cases, though I like having a default behavior if particular values are not found. Currently we specify a) "uppercase"  and b) default. I'd be happy with a) "uppercase" b) "lowercase" and c) default.

I know we won't ever keep users from writing bad code. The only way to write good code is to write lots of bad code first. But I don't see that as a reason to make it easier to write bad code. In this case, the requirements currently specify that the user checks the value, so letting user code pass that doesn't do that would go beyond 'bad code' to me.

**Comment by jeremylt** [comment]
I still did not say that fixing this will let the user write bad code.

I agree that setting the string value "undefined" was probably not the intent.

But your proposed change to the tests would require a change to text of the challenge as well. Checking only if the value has been set is different from the text of the challenge.

> process.env.MESSAGE_STYLE ? 'do something' : 'do something else'

This checks if the environment is set and ignores the value of the environment variable.

> process.env.MESSAGE_STYLE === "uppercase" ? 'do something' : 'do something else'

This is fundamentally different behavior. It checks if the environment variable is set and what value it is set to.

**Comment by jeremylt** [comment]
I'm not trying to twist your words. I'm try to acknowledge that mistakes are important in learning, especially to you, without agreeing that we should write tests that knowingly let solutions pass that have semanticly different results from the requirements.

> In the real world, there isn't some gremlin that changes values on you behind your back. 

I see this as a bad assumption. I always assume bad input is a possibility. Letting the user ignore realty that more than just their code matters feels hand holdy to me.

> The env from a user's perspective can not contain a string value they did not set, if it can, it should be made clear.

I agree that the user should be told that the environment variable can change. 

---

Any test change needs a corresponding change in the challenge text.

I like the approach of adding another possible value. Suppose we wanted user code to behave like this (ignoring any bad code/good code discussion, which.... again... isn't my point with my objection to just changing the test)

```
app.get("/json", (req, res) => {
  let messageStyle = process.env.MESSAGE_STYLE;
  let message = "Hello json";
  if (messageStyle === "uppercase") {
    message = message.toUpperCase();
 } else if (messageStyle === "lowercase") {
    message = message.toLowerCase();
 }
res.json({ "message": message});
});
```

This makes the value meaningful and requires more interaction with the value.

We then would have 3 tests for the *outcomes* of the user code

1) `MESSAGE_STYLE === "uppercase"` -> return `"HELLO JSON"`

2) `MESSAGE_STYLE === "lowercase"` -> return `"hello json"`

3) All other cases -> return `"Hello json"`

**Comment by ShaunSHamilton** [comment]
Thank you, for all the discussion on this.

I think if anything more needs to be said on the matter, I suggest we take it to the contributor's channel on Chat.

---

I will be giving this a proper review, next week, and discussing as needed to come to a conclusion for resolution.

**Comment by ShaunSHamilton** [comment]
My suggestion is as on the comment I made on: https://github.com/freeCodeCamp/fcc-express-bground-pkg/pull/11

---

Nothing in the instructions here need to change. They are as clear as they need to be whereby:
> If `MESSAGE_STYLE` is equal to the string `uppercase`, the response should be uppercased. For all other values (falsey or otherwise), the response should be unchanged.
