### ISSUE TITLE
Basic JavasSript: fail unless return is in else block

### ISSUE THREAD

**Issue by Kernix13** [freeCodeCamp/freeCodeCamp#45246]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties

## Your code

```js

if (obj.hasOwnProperty(checkProp)) {
    return obj[checkProp];
  }
  return "Not found";


```

## Expected behavior

To pass. I only passed the lesson when I put the line `return "Not found";` in an else block. 

## System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [brave]
- Version:  [1.35.103]

## Additional context

I'm not sure why I did not pass with this:

```js
function checkObj(obj, checkProp) {
  if (obj.hasOwnProperty(checkProp)) {
    return obj[checkProp];
  }
  return "Not found";
}
```

But this did pass:

```js
function checkObj(obj, checkProp) {
  if (obj.hasOwnProperty(checkProp)) {
    return obj[checkProp];
  } else {
    return "Not Found";
  }
}
```
Are the lessons coded so that only 1 solution will pass?

**Comment by gikf** [comment]
Hey @Kernix13

Thank you for reporting this issue.

Both approaches work, but the first example has different than expected capitalization in the returned string. Because this isn't a bug I'm closing the issue.

Thank you and happy coding.

**Comment by Kernix13** [comment]
Okay.
