### ISSUE TITLE
Incorrect code passes tests in "Implement Binary Search" challenge 

### ISSUE THREAD

**Issue by marcocosta1618** [freeCodeCamp/freeCodeCamp#45254]
## Affected page

[Implement Binary Search](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-binary-search)

## Your code

The following code passes all the challenge's tests, but it is incorrect (it fails to find `value` if `value` is the last element of `testArray`

```
function binarySearch(searchList, value, arrayPath = []) {
   const midIdx = Math.floor(searchList.length / 2);
   const midElem = searchList[midIdx-1];
   if (midElem == value) {
      arrayPath.push(midElem)
      return arrayPath;
   }
   if (searchList.length == 1) return 'Value Not Found'
   arrayPath.push(midElem)
   if (midElem < value) return binarySearch(searchList.slice(midIdx), value, arrayPath)
   return binarySearch(searchList.slice(0, midIdx), value, arrayPath)
}

const testArray = [
   0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 
   22, 23, 49, 70
];
```

## Expected behavior

The code above should not pass the challenge.

## Screenshots
![wrongBinarySearch](https://user-images.githubusercontent.com/78434326/155701971-b4441846-c0fd-4808-a6a6-fa8f7be8fa0e.png)

## System

- Device: Macbook Pro
- OS: 10.13.6
- Browser: Firefox 
- Version: 97.0.1

**Comment by nhcarrigan** [comment]
Checking against the solution on the forum, it appears that `binarySearch(testArray, 70)` should return `[ 13, 19, 22, 49, 70 ]`. 

We could add a test to the challenge that checks this, which would resolve this issue.

**Comment by marcocosta1618** [comment]
Yes, that should be all it takes to resolve this issue.

**Comment by nhcarrigan** [comment]
I'm going to go ahead and open this up for first time contributors.

A PR to resolve this issue will:

- Add a test to https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/algorithms/implement-binary-search.md that asserts `binarySearch(testArray, 70)` returns `[ 13, 19, 22, 49, 70 ]`.

If you are interested in working on this issue, we recommend starting with our [contributing guidelines](https://contribute.freecodecamp.org), and you are welcome to join our [chat channel](https://chat.freecodecamp.org/channel/contributors) if you have any questions.

**Comment by jeremylt** [comment]
> can I do the code in python ?

No. Our challenges run on Javascript. 

In this case, you don't need to write a new impl of the algorithm or anything. You just need to add an additional test case that matches the one given above.

**Comment by marcocosta1618** [comment]
> If you are interested in working on this issue, we recommend starting with our [contributing guidelines](https://contribute.freecodecamp.org), and you are welcome to join our [chat channel](https://chat.freecodecamp.org/channel/contributors) if you have any questions.

Sure, unless @NeelPatel31 wants to take this, I will
