### ISSUE TITLE
Issue with test suite description

### ISSUE THREAD

**Issue by michaelwnelson** [FreeCodeCamp/FreeCodeCamp#4525]
Challenge [Waypoint: Construct JavaScript Objects with Functions](http://www.freecodecamp.com/challenges/waypoint-construct-javascript-objects-with-functions#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20MotorBike%20%3D%20function()%20%7B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.wheels%20%3D%202%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

var myCar = new Car();

// Only change code below this line.

var MotorBike = function() {
  this.engines = 1;
  this.wheels = 2;
  this.seats = 1;
};

```

The user isn't required to instantiate an object of `MotorBike` as `myMotorBike` (like the `Car` example above) to proceed. I would have expected the code below in order to pass:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

var myCar = new Car();

// Only change code below this line.

var MotorBike = function() {
  this.engines = 1;
  this.wheels = 2;
  this.seats = 1;
};

var myMotorBike = new MotorBike();

```

**Comment by shadowfool** [comment]
Confirmed, top code passes but should not, looking into issue.
