### ISSUE TITLE
typo in test of a challenge

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#45269]
In challenge Euler problem 184 both the hint and the text have the function call with a typo.

To fix this issue you would need to edit the linked file and remove the extra `t` in the function call in the test description and in the assertion of the test itself.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-184-triangles-containing-the-origin.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by DinahWorld** [comment]
Hello, can you assign me please ? this will be my first contribution to an open source project.
I will read the guidelines.

**Comment by Nirajn2311** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
