### ISSUE TITLE
Periodic Table Database project - typo

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#45293]
[Periodic Table Database project](https://github.com/freeCodeCamp/learn-periodic-table-database/) has small typo in one of the subtasks:

> It the argument input to your `element.sh` script doesn't exist as an `atomic_number`, `symbol`, or `name` in the database, the output should be `I could not find that element in the database.`

should be
> I**f** the argument input to your `element.sh` script doesn't exist as an `atomic_number`, `symbol`, or `name` in the database, the output should be `I could not find that element in the database.`

## Additional context

This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by OrdoFlammae** [comment]
This was fixed by https://github.com/freeCodeCamp/learn-periodic-table-database/commit/31dba322c015c65079875923d767d1478615ced9.

**Comment by erictleung** [comment]
Closing as fixed by https://github.com/freeCodeCamp/learn-periodic-table-database/commit/31dba322c015c65079875923d767d1478615ced9. Happy coding!
