### ISSUE TITLE
The page checklist breaks

### ISSUE THREAD

**Issue by Bycrozz** [FreeCodeCamp/FreeCodeCamp#4529]
Hello! I was doing the challenge "Chunky Monkey" and when i used the code below my checklist disappeared and the console stopped (was not showing results even when i press Ctrl + Enter)

function chunk(arr, size) {
  var newArr = [];
  for(i = 0; i <= arr.length; i++){
  for(i = 0; i <= size; i++){
    if(i%size === 0){
   newArr.push(arr.slice(i,i+size));
        }
      }
    }
  return newArr; 
}
chunk([0, 1, 2, 3, 4, 5], 3);

Sorry for my poor language skills, i'm learning english :D

**Comment by shadowfool** [comment]
I believe this is because your code defines "i" twice and keeps setting "i" to 0, you need to use a different variable for your second for loop.

**Comment by BerkeleyTrue** [comment]
@shadowfool is correct. 

In the future please use the Help chat room first before opening an issue.

Happy Coding!
