### ISSUE TITLE
Symmetric Difference Bonfire(42) description is unclear

### ISSUE THREAD

**Issue by prashcr** [FreeCodeCamp/freecodecamp#453]
`Create a function that takes two or more arrays and returns an array of the symmetric difference of the provided arrays.`

I initially assumed that it wanted us to sym-diff all the provided arrays at once. However, what it actually wants is for us to sym the first two, sym that with the next one and so on..  
  
Many others have had the same confusion and I think it's worth a rewrite of the description.

`Create a function that takes two or more arrays and reduces them into the symmetric difference of the provided arrays.`
`Like Array.prototype.reduce(), your function should sym-diff the first two arrays, then sym-diff the result with the next one, and so on.`

**Comment by terakilobyte** [comment]
The definition of symmetric difference is for two sets. For n-ary sets, you
can see it is equivalent here
http://en.wikipedia.org/wiki/Symmetric_difference#n-ary_symmetric_difference

This is a more advanced bonfire, thus it demands an exacting definition
without any additional explanation or hints at how to implement the
algorithm in my opinion.

**Comment by prashcr** [comment]
Fair enough, was just a suggestion.
Feel free to close.
