### ISSUE TITLE
Trying to `checkout main` or `push origin main` results in errors (there is no `main` branch)

### ISSUE THREAD

**Issue by TaraBryn** [freeCodeCamp/freeCodeCamp#45303]
## Affected page

[Set up freeCodeCamp locally](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally)

## To reproduce

follow page instructions that include references to the `main` branch

## Recommended fix, suggestions

Change references to the `main` branch to reference the `master` branch in the `checkout` and `push` lines

**Comment by OrdoFlammae** [comment]
There is no `master` branch, there is a `main` branch. Are you sure you are cloning the right repository?

**Comment by TaraBryn** [comment]
> There is no `master` branch, there is a `main` branch. Are you sure you are cloning the right repository?

For some reason, when I forked it, it forked with `master` intead of `main`

<img width="692" alt="image" src="https://user-images.githubusercontent.com/28311501/156252004-df0e84c3-939d-40c9-8677-c4c57c7217a4.png">

**Comment by OrdoFlammae** [comment]
It's a GitHub setting that's at fault. Go to `Settings->Repositories->Repository Default Branch` and change the name. Or not. Just be aware that the main branch will be forked as whatever you put there.

**Comment by TaraBryn** [comment]
> It's a GitHub setting that's at fault. Go to `Settings->Repositories->Repository Default Branch` and change the name. Or not. Just be aware that the main branch will be forked as whatever you put there.

it was already set to that, I tried reimporting, and it reimported with `main`
