### ISSUE TITLE
Challenge (URL Shortener Microservice) invalid URL will pass dns check

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45319]
The "invalid" URL used by the test will pass the DNS check suggested by the challenge text.

```
const dns = require('dns');
const hostName = new URL('ftp:/john-doe.org').hostname;

dns.lookup(hostName, (err, address, family) => {
  if (err) {
    return res.json({ error: 'invalid url' });
  } else {
    console.log('valid'); // valid
  }
});
```

I realize in a real app it might still be useful, but it isn't for the test. Not sure if the test used to fail, the `john-doe.org` domain is redirecting which it might not always have?

Anyway, I would suggest we update the test with an actual invalid URL that will fail the `dns.lookup` or change the challenge text. Edit: maybe we can just use an invalid top-level domain?

Challenge: https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice

Tests: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice.md

---

I didn't look through all the issues so if this is a dub, sorry.

**Comment by raisedadead** [comment]
> maybe we can just use an invalid top-level domain?

That's not a bad idea.

**Comment by WoWWork** [comment]
Great let's do it.

2022年3月7日 下午10:39，"Mrugesh Mohapatra" ***@***.***>寫道：
