### ISSUE TITLE
Page freezes whenever you try to write in a solution. Tried two different browsers, issue remains.

### ISSUE THREAD

**Issue by michelangelo17** [FreeCodeCamp/FreeCodeCamp#4532]
Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36 OPR/33.0.1990.87</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.

var newArray = array;

// Only change code above this line.


```

**Comment by gasperno** [comment]
I am using the following user agent and I could not produce the issue.
`Mozilla/5.0 (X11; CrOS x86_64 7390.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.82 Safari/537.36`

**Comment by michelangelo17** [comment]
Yeah, I did a little more testing myself, and I don't know what the issue
is, but quite a few way points are freezing on me now. Perhaps it's my
computer, but I'm not having problems on any other sites, including similar
code learning sites. But it's not just specific to the page like I
originally thought, and I can't find a way to fix it. Guess I'll just have
to use something else.

**Comment by SaintPeter** [comment]
Closing as this appears to be user specific.

Thanks and happy coding!
