### ISSUE TITLE
Sections not saving in code portfolio after completion

### ISSUE THREAD

**Issue by ZacharyKearns** [FreeCodeCamp/FreeCodeCamp#4533]
The get started with Free Code Camp and HTML5 and CSS sections disappeared from my code portfolio and the map after I logged out and then logged back in even though I completed them

**Comment by BerkeleyTrue** [comment]
@ZacharyKearns I can see you're completed bonfires on you're account page. Can you give some more detail on what is missing?

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
