### ISSUE TITLE
Users can continue using CodeAlley while they are singed off 

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#45345]
@Tom_M After users sign out of their account, CodeAlly related data remains in the local Storage and CodeAlly challenges could be accessed and continued. Not sure if this is the intended behavior or not.

**Comment by raisedadead** [comment]
The action items are:

1. We can remove the "Create Token" (for CodeRoad) step. This can instead become implicit.
2. The token that is needed back by CodeRoad, can instead be regenerated each time the container is generated and passed along through CodeAlly.
