### ISSUE TITLE
Suggestion for beta Responsive web course: format instructions

### ISSUE THREAD

**Issue by placoderm** [freeCodeCamp/freeCodeCamp#45352]
I’m not sure where the right place is to give this feedback. I was going to recommend the beta course to a friend so I decided to try it out.

In general it looks great! Congratulations.

One thing I didn’t like is the lack of visual distinction between code and instructions. For example:

![image](https://user-images.githubusercontent.com/31570884/156877374-7dc81554-cc29-413a-9043-c150bb91a184.png)

I would suggest making the instruction area have a different background colour. Otherwise it’s just a whole lot of gray. I know that the instructions are in a serif font and the code is in a mono font, but to me that isn’t enough to separate. Having the instructions embedded in the code is probably a good thing, but I’d make it more distinct.

Perhaps like this:

![image](https://user-images.githubusercontent.com/31570884/156877384-f75d9f20-82d9-4580-9bb8-6df3110db119.png)

I'd also recommend that the instructions be indicated with perhaps a heading of ***To Do***. 

Any way, it looks really great and I'm excited to recommend it to friends. Thanks for all the hard work!

**Comment by kai-wei-mo** [comment]
I'd like to take on this issue!

**Comment by kai-wei-mo** [comment]
Personally, I didn't find an outstanding color in `client/src/components/layouts/variables.css` that would satisfy your request without taking away from the semantic values of said color (e.g. `--green-light` should mean success/completion, `--danger-background` is not appropriate for simple instructions, etc.), and I don't know if this use case justifies the addition of a new hue to the website theme.

Instead, I made the `background-color` a little brighter and added a `border-left` to your components.

Let me know what you think!

![image](https://user-images.githubusercontent.com/66972679/156905500-602960c0-a2fc-422e-b1bd-366f71f1c3fb.png)

**Comment by placoderm** [comment]
For sure that's an improvement. I'd say, though, that if this issue is a real problem, then it would be worth it to add another colour to the palette. The instructions are central to the whole app, after all.

Thanks for taking an interest in this!

**Comment by ahmadabdolsaheb** [comment]
I see your point. We have discussed the visibility of the description area and added a flashing background on the first challenge of each project. Changing the background color of description area would introduce visibility issues for the styled code blocks and the selected text.

Maybe we could simply break the flow of the editor similar to github:
<img width="1716" alt="Screen Shot 2022-03-07 at 2 07 14 PM" src="https://user-images.githubusercontent.com/4591597/157020527-76b3d68e-5c4a-458e-80f6-de24158b3598.png">


here is our layout with `margin-left: -40px` on upper and lower jaws:
<img width="1267" alt="Screen Shot 2022-03-07 at 2 13 05 PM" src="https://user-images.githubusercontent.com/4591597/157020690-c7639aee-1431-4687-afa0-de4d3063a6e6.png">

**Comment by placoderm** [comment]
To me it still looks like a jumble. 

Perhaps a colour border around the instructions?

**Comment by raisedadead** [comment]
I am in favor of the changes @kai-wei-mo is proposing. That's a fair improvement.

**Comment by ahmadabdolsaheb** [comment]
Thank you all for the feedback.

To make the jaws stand out, we could give them a wider left boarder and align it with the line decoration. That should visually group the active elements in the editor.

<img width="644" alt="Screen Shot 2022-03-08 at 1 23 51 PM" src="https://user-images.githubusercontent.com/4591597/157230656-1e42e397-f19c-44b8-a039-364bbb829b78.png">

Down the line, we could experiment with changing the border color to reflect the state of the tests similar to the line
decoration.

**Comment by placoderm** [comment]
> we could give them a wider left border and align it with the line decoration.

I think this has the opposite effect. You are making the instruction box *more* similar to the code and not less.

I think we really need to think about things from the _user perspective_. The people taking this course may be using an ide environment for the very first time. Honestly the whole concept of merging the instructions right into the editor is a little odd to me, but that's just my opinion (and one that doesn't matter since that's how it works now😁) 

Imagine replacing everything there with lorum ipsum text. Would what is going on still be clear? Because for a new person, that's exactly what they will experience.

**Comment by ahmadabdolsaheb** [comment]
Interesting observation. Let me run some usability tests to see if new users find this version of the challenges harder to navigate than the older version.

**Comment by ahmadabdolsaheb** [comment]
I discussed this issue with @ojeytonwilliams, changed the design slightly and ran a usability test with 5 people with different technical proficiencies.

The implemented changes: 
- Step number were replaced with "Instructions".
- Step number was added to the breadcrumbs.
- The border contrast of the upper and lower jaws have been increased.

The tested design:
<img width="1728" alt="testible " src="https://user-images.githubusercontent.com/4591597/157672544-3a74d7a8-1fd1-4274-972f-d67b93ff0b37.png">

The participants were asked "Where would you click to edit text?" and here is the heat-map:
<img width="934" alt="Screen Shot 2022-03-10 at 4 20 54 PM" src="https://user-images.githubusercontent.com/4591597/157672795-17a3c38f-13b1-4d30-9c05-125b084aa6f5.png">

Participants were on average confident that they clicked on the right element and most found the element easy to find.

Conclusion:
We could change the border color of the selected editor line to create a sufficient distinction between the rest of the page and where the code needs to be edited.

That change along with flashing the background color of the instructions box from blue to the secondary background color on the first challenge should give new users enough visual guidance to complete the task.

@placoderm thank you for creating this issue and pointing out the need for creating visual distinction in the UI. I will keep changing  and testing the layout to make sure we are heading in the right direction

@kai-wei-mo, if you are still interested in creating a pull request, I would appreciate it if you could change the border color of the upper and lower jaws to `var(--quaternary-background)` and set the border of the selected editor line to `var(--highlight-background). You may need to dig into the Monaco documentations.

**Comment by placoderm** [comment]
I'm glad I could contribute in some small way! Big thank you to everyone who is working on this.

**Comment by ojeytonwilliams** [comment]
Thanks @placoderm it's hard to escape the curse of knowledge, so it's always helpful to get more perspectives.  The point about highlighting that the instructions should be labelled as such was particularly useful.  Cheers!

**Comment by moT01** [comment]
Not sure if this helps at all or is the way to go, but I played with this in the dev tools a little bit and came up with some different ideas:
![Screen Shot 2022-03-10 at 8 55 36 AM](https://user-images.githubusercontent.com/20648924/157689497-52f43c1a-2880-4b73-926d-36bf293d5233.png)

- Made the background of the jaws full width - this may be not great. It's an idea anyway
- Made the editable region have the same background as the rest of the document - I like this one a little more. Making the background white blends it with the instructions and is maybe a little confusing. I suppose we're trying to differentiate it from the rest of the document - but there's already a big gray bar on the left and it makes it feel a little unnatural.

**Comment by ahmadabdolsaheb** [comment]
I like this iteration as well and we would probably need to test to see if users can find the editable region easily.

**Comment by kai-wei-mo** [comment]
> @kai-wei-mo, if you are still interested in creating a pull request, I would appreciate it if you could change the border color of the upper and lower jaws to `var(--quaternary-background)` and set the border of the selected editor line to `var(--highlight-background). You may need to dig into the Monaco documentations.

@ahmadabdolsaheb I updated my PR with the items that you requested.
