### ISSUE TITLE
Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by whitevamp** [FreeCodeCamp/FreeCodeCamp#4535]
when doing Nest an Anchor Element within a Paragraph.
The HTML page is blank, so you have to figure out what the previous HTML section contained, and the description doesn't say any thing about using
http://www.freecatphotoapp.com inside of the anchor tag.
this is what it tells you to do taken from 
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/html5-and-css.json#L1177

Now nest your existing <code>a</code> element within a new <code>p</code> element (just after the existing <code>h2</code> element) so that the surrounding paragraph says \"View more cat photos\", but where only \"cat photos\" is a link, and the rest of the text is plain text. 

i figured out what to do by looking at the code and seeing what is was parsing for.

**Comment by ltegman** [comment]
The seed code for this challenge includes all the HTML from the previous lesson and the anchor tag (which already has a link to the appropriate URL). If you did not see this code something went wrong on page load and pressing the reset button would have solved this problem.

As such a fix for this challenge is not required.

Thanks and happy coding!

**Comment by whitevamp** [comment]
tried the reset button a couple times.

**Comment by m4sterbunny** [comment]
I have reset- this works in the preview window- but I am not passing the challenge:

under my h2 tag is the following: 

<p> View more  <a href="http://freecatphotoapp.com">cat photos</a>
</p>

**Comment by m4sterbunny** [comment]
Using this code

**Comment by m4sterbunny** [comment]
reboot fixed it- go figure
