### ISSUE TITLE
Suggestion for Information Security course: update helmet to v5

### ISSUE THREAD

**Issue by harmonify** [freeCodeCamp/freeCodeCamp#45368]
When following throughout [this course](https://www.freecodecamp.org/learn/information-security) on freeCodeCamp, I noticed that the boilerplate challenges use helmet v3. I suggest to update the curriculum to use helmet v5 as I found out the older version has some security issues.
And one of them is about setting the `X-XSS-Protection` HTTP header. In helmet v3, using `helmet.xssFilter()` will set the header to `X-XSS-Protection: 1; mode=block`. This enables browsers' buggy cross-site scripting filter. Meanwhile in v5, it will set `X-XSS-Protection: 0` by default.

## Affected page

1. [freeCodeCamp's X-XSS-Protection challenge](https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/mitigate-the-risk-of-cross-site-scripting-xss-attacks-with-helmet-xssfilter)

## Expected behavior

1. Using `helmet.xssfilter()` middleware set the `X-XSS-Protection` header to `0`.

## Additional context

1. [MDN Documentation on X-XSS-Protection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)
2. [HelmetJS' discussion on X-XSS-Protection](https://github.com/helmetjs/helmet/issues/230)
3. [Community discussion on X-XSS-Protection](https://stackoverflow.com/questions/9090577/what-is-the-http-header-x-xss-protection/57802070#57802070)

**Comment by nhcarrigan** [comment]
We have had a lot of discussion re: whether to continually update the curriculum to keep up with package updates.

The challenges here are:
- The entire block would need to be updated to reflect any breaking changes
- The certification projects would need to be updated to expect + test the latest version.

**Comment by nhcarrigan** [comment]
I'm in agreement with Tom here. I'd be in favour of closing this and continuing to focus our efforts on the redesigned curriculum.
