### ISSUE TITLE
Grammar issue in Learn CSS introduction

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#45373]
https://github.com/freeCodeCamp/freeCodeCamp/blob/984a2f2bc2e234466c3800c87038f28fdc9bc1d0/client/i18n/locales/english/intro.json#L153

I am not sure this is correct English here

**Comment by ieahleen** [comment]
I am not confident to know which is the best wording to use, but...

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

 - https://github.com/freeCodeCamp/freeCodeCamp/blob/984a2f2bc2e234466c3800c87038f28fdc9bc1d0/client/i18n/locales/english/intro.json line 153

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by crystal-kishore** [comment]
I will resolve it and make a PR
