### ISSUE TITLE
Timestamp project | "An empty date parameter should return the current time in a JSON object with a utc/unix key" test doesn't work correctly

### ISSUE THREAD

**Issue by ebdurrehm** [freeCodeCamp/freeCodeCamp#45377]
Hello. In the timestamp project, the results of all tests are successful, except for the data value tests:
"An empty date parameter should return the current time in a JSON object with a unix key
An empty date parameter should return the current time in a JSON object with a utc key"

I did some research and the logic in your test is as follows:
```
(getUserInput) =>
  $.get(getUserInput('url') + '/api').then(
    (data) => {
      var now = Date.now();
      assert.approximately(data.unix, now, 20000);
    },
    (xhr) => {
      throw new Error(xhr.responseText);
    }
  );

```

When the difference between the current time specified in the test and the time in the response is large, the test fails, ie if the difference is greater than 20,000, the result fails (as it usually does). To check, I added +20000 to the current time I set in the code and the test was successful.

## Affected page

[Challenge page](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice)

[Test page](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice.md)

## Your code

```

//  empty date parameter
app.get("/api", (req, res)=>{
  let date = new Date();
  let UTC = date.toUTCString();
  let UNIX = date.getTime();
  res.json({ unix: UNIX, utc: UTC });
})


```

## Expected behavior
the test must be successful

## Screenshots
my result:
![image](https://user-images.githubusercontent.com/42205442/157093886-fb168745-53d4-493a-a812-bceb87abd5fc.png)

## System

- Device: Laptop
- OS:  Windows 10
- Browser: edge
- Version:  99.0.1150.30

**Comment by ojeytonwilliams** [comment]
Hi @ebdurrehm could you elaborate a bit more on what the problem is here?  I tried your project https://boilerplate-project-timestamp.ebdurrehm.repl.co/ and it passes all the tests.  Also, the test logic, checking if timestamp returned is near to the current time, seems fine to me.

**Comment by ebdurrehm** [comment]
> Hi @ebdurrehm could you elaborate a bit more on what the problem is here? I tried your project https://boilerplate-project-timestamp.ebdurrehm.repl.co/ and it passes all the tests. Also, the test logic, checking if timestamp returned is near to the current time, seems fine to me.

Hi, I have added 20,000 to utc and unix in my code to make the test successful. If I don't add it, the test fails. I think the reason for this is that there is a big difference between the current time I set in response and the time in the test.

Normally the test should have been successful when the logic was set up as follows, but it is not:

```
app.get("/api", (req, res)=>{
  let date = new Date();
  let UTC = date.toUTCString();
  let UNIX = date.getTime();
  res.json({ unix: UNIX, utc: UTC });
})
```
I had to artificially eliminate the difference to pass the test, and the test was successful:
```
app.get("/api", (req, res)=>{
  let date = new Date();
  let UTC = date.getTime()+20000;
  UTC = new Date(UTC);
  UTS = UTC.toUTCString();
  let UNIX = date.getTime()+20000;
  res.json({ unix: UNIX, utc: UTS });
})
```

I think the reason is that the test is not set up correctly. So normally the difference between data.unix and "now" is more than 20,000.

**Comment by ebdurrehm** [comment]
@ojeytonwilliams Thank you, if you have it, it means that there is no problem with the test. The same situation I checked was not taken. I close this issue.

**Comment by ojeytonwilliams** [comment]
You're welcome @ebdurrehm. Thanks for taking the time to raise the issue :)

**Comment by viktorm471** [comment]
if someone have issues with the last two tests maybe his clock isn't in the right time, you need to automatic update the windows clock. 
https://www.softzone.es/windows/como-se-hace/solucionar-problemas-fecha-hora-windows/

**Comment by xylvnking** [comment]
In case anybody else ends up here, I couldn't get this to pass either, ended up here too, and used @ojeytonwilliams answer but removed the +20000 and it passed after submitting it a few times. I've had trouble with lots of the freeCodeCamp + replit tests not passing unless submitted multiple times, so always try a few times (in my experience). Thanks for the help, and the free education.

```js
app.get("/api", (req, res)=>{
  let date = new Date();
  let UTC = date.getTime();
  UTC = new Date(UTC);
  UTS = UTC.toUTCString();
  let UNIX = date.getTime();
  res.json({ unix: UNIX, utc: UTS });
})
```

(code for reference)
