### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by RickGrimes808** [FreeCodeCamp/FreeCodeCamp#4537]
Challenge [Waypoint: Uncomment HTML](http://www.freecodecamp.com/challenges/waypoint-uncomment-html?solution=%3C!--uncomment--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--uncomment-->
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>


```

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps and a description on how to reproduce the issue.

Happy Coding!
