### ISSUE TITLE
Spanish Translation of Basejumps

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4538]
Translate all Basejump challenges to Spanish
- [x] Get Set for Basejumps

**Comment by BerkeleyTrue** [comment]
Has this been completed?

**Comment by vtamara** [comment]
No yet.

- [ ] Get Set for Basejumps
- [ ] Build a Voting App
- [ ] Build a Nightlife Coordination App
- [ ] Chart the Stock Market
- [ ] Manage a Book Trading Club
- [ ] Build a Pinterest Clone

**Comment by JS-Taiyou** [comment]
Is anybody working on this?

**Comment by justinian336** [comment]
@JS-Taiyou thanks for the help! There's no one working on this issue. If you plan to take it, please leave a comment here saying so. If you have any question about how to start, you can ask us in the chat room.

**Comment by justinian336** [comment]
@JS-Taiyou I will work on this one as we talked on the chat room. Will appreciate your comments on the translation.
