### ISSUE TITLE
Incorrect commenting for "Write Concise Object Literal Declarations Using Object Property Shorthand" challenge.

### ISSUE THREAD

**Issue by jordmondson** [freeCodeCamp/freeCodeCamp#45391]
## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/write-concise-object-literal-declarations-using-object-property-shorthand

## Your code

```
const createPerson = (name, age, gender) => ({
  // Only change code below this line
    name,
    age,
    gender
  });
  // Only change code above this line
```

## Expected behavior
```
const createPerson = (name, age, gender) => {
  return {
    name: name,
    age: age,
    gender: gender
  };
};
```
This solution requires the first and second lines to be edited, however, the comments ask not to do this.

The comments should accurately reflect the solution, or not exist at all.

## System

- Device: Laptop
- OS: macOS Big Sur
- Browser: Edge
- Version:  98.0.1108.56

**Comment by jordmondson** [comment]
Just went through to see if I could remove the comments and submit a pull request, but noticed that a valid solution does exist without editing the first or last line. This solution doesn't follow the syntax in the example though.

**Comment by nhcarrigan** [comment]
Yeah, the challenge is specifically looking for the object literal shorthand, and passes with this code:

```js
const createPerson = (name, age, gender) => {
  // Only change code below this line
  return {
    name, age, gender
  };
  // Only change code above this line
};
```

But I do agree that doesn't quite match the example. And given that it skips over the fact that a function implicitly returning an object needs to wrap the object in `()`, which is a common question on the forum, I'd be in favour of adding some more information to this challenge.

My proposal would be to remove the comments, and add a note to the description about implicitly returned objects.

@ShaunSHamilton thoughts?

**Comment by nhcarrigan** [comment]
Given that, and the fact that there's nothing actually stopping a camper from using an implicit return, I'd be in favour of closing this.

**Comment by jeremylt** [comment]
I'd be fine with that, personally
