### ISSUE TITLE
Spanish translation of Get Started with FreeCodeCamp

### ISSUE THREAD

**Issue by vtamara** [FreeCodeCamp/FreeCodeCamp#4539]
- [x] Learn how Free Code Camp Works
- [x] Create a GitHub Account and Join our Chat Rooms
- [x] Configure your Code Portfolio
- [x] Join a Campsite in Your City
- [x] Learn What to Do If You Get Stuck

**Comment by Oxyrus** [comment]
Have you started yet? If not I could help you out with this.

**Comment by vtamara** [comment]
Por favor, adelante.

**Comment by Oxyrus** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4649
