### ISSUE TITLE
We should use correctly tag and element

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#45408]
related to https://github.com/freeCodeCamp/freeCodeCamp/issues/43427#issuecomment-917026049

In the new Responsive Design curriculum the words tag and element are used interchangebly

The correct use should be `h1` element and `<h1>` tag (or at least, element is the whole thing, tag is the one that start with `<` and end with `>` and can be an opening tag, a closing tag or a self-closing tag).

Should this be changed in the new curriculum?

**Comment by ShaunSHamilton** [comment]
Do we have many/any incorrect uses?

**Comment by ieahleen** [comment]
actually mostly not - there is some ambiguity with `meta` in the second step of the accessibility quiz

I have been hasty

**Comment by ShaunSHamilton** [comment]
@ieahleen That does look like something that should be standardised. Thank you, for listing them.

---

I am opening this issue up for **first timers only**. The files that need changed are listed in the above reply.

**What needs changed**
- There are a few uses of the word `tag` which should be changed to `element`.

**Example**

Original:
> You may be familiar with the meta tag already;

New:
> You may be familiar with the meta element already;

**Note**

Not all uses of the word `tag` should be changed. Example:
> You should give the meta tag a charset of UTF-8.

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Anifahb** [comment]
Hi @ShaunSHamilton @ieahleen - is it ok if i pick this up? First timer here 👋
