### ISSUE TITLE
Spanish translation of  Responsive Design with Bootstrap

### ISSUE THREAD

**Issue by vtamara** [FreeCodeCamp/FreeCodeCamp#4540]
- [x] Use Responsive Design with Bootstrap Fluid Containers
- [x] Make Images Mobile Responsive
- [x] Center Text with Bootstrap
- [x] Create a Bootstrap Button
- [x] Create a Block Element Bootstrap Button
- [x] Taste the Bootstrap Button Color Rainbow
- [x] Call out Optional Actions with Button Info
- [x] Warn your Users of a Dangerous Action
- [x] Use the Bootstrap Grid to Put Elements Side By Side
- [x] Ditch Custom CSS for Bootstrap
- [x] Use Spans for Inline Elements
- [x] Create a Custom Heading
- [x] Add Font Awesome Icons to our Buttons
- [x] Add Font Awesome Icons to all of our Buttons
- [x] Responsively Style Radio Buttons
- [x] Responsively Style Checkboxes
- [x] Style Text Inputs as Form Controls
- [x] Line up Form Elements Responsively with Bootstrap
- [x] Create a Bootstrap Headline
- [x] House our page within a Bootstrap Container Fluid Div
- [x] Create a Bootstrap Row
- [x] Split your Bootstrap Row
- [x] Create Bootstrap Wells
- [x] Add Elements within your Bootstrap Wells
- [x] Apply the Default Bootstrap Button Style
- [x] Create a Class to Target with jQuery Selectors
- [x] Add ID Attributes to Bootstrap Elements
- [x] Label Bootstrap Wells
- [x] Give Each Element a Unique ID
- [x] Label Bootstrap Buttons
- [x] Use Comments to Clarify Code

**Comment by justinian336** [comment]
I will start with this one if nobody else is working on it. By the way, @vtamara I can't put checks on this checklist. Maybe if you add me as an assignee I will be able to do it?

**Comment by vtamara** [comment]
I cannot add you.  But i can put checks (since I created).

**Comment by deniz946** [comment]
How I can help to translate into spanish the challanges?

**Comment by justinian336** [comment]
@deniz946 First fork the FreeCodeCamp repository and clone it into your PC. Then choose among the open issues related to the translation into Spanish. If no one is working on it, you can take it. Join our chat room to check out the status of the translation: https://gitter.im/AlexTrapp/FreeCodeCampEspa%C3%B1ol

We're very active on that chat room, so you can get some help there if you have any doubt.

After you choose an issue, create a branch and name it something like "Add/ES-translation-of-XXXX", where XXXX is the name of the part you are gonna work in. Be sure to leave a comment on the issue on GitHub saying that you are working on it, so others will know. If you think you can't continue with it, please also leave a comment, so others can continue where you left.

When you finish, you can push your commit to your fork and share the url with the translators at the chat room. You could also make the pull request and wait for the other translators to make comments.

We'd really appreciate your help!

**Comment by justinian336** [comment]
I'm done, please check the PR.
