### ISSUE TITLE
Spanish translation of Gear up for Success

### ISSUE THREAD

**Issue by vtamara** [FreeCodeCamp/FreeCodeCamp#4541]
- [ ] Browse Camper News
- [ ] Reference our Wiki
- [ ] Join our LinkedIn Alumni Network
- [ ] Commit to a Goal and a Nonprofit

**Comment by MEXshredder** [comment]
I will work on this one.

**Comment by vtamara** [comment]
Great.

**Comment by vtamara** [comment]
By the way David  (@MEXshredder ) if you can join us in this chat about the spanish translation https://gitter.im/AlexTrapp/FreeCodeCampEspa%C3%B1ol  please vote about the terms of the glossary where we need other people to vote: (1) Waypoint (a) Punto de ruta, (b) Coordenadas.  (2) Array (a) vector (o matriz) (b) arreglo

**Comment by JS-Taiyou** [comment]
@vtamara Yo voto por "arreglo" para "array".

**Comment by bugron** [comment]
Only this one is left, good job.
