### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by Lindakay82** [freeCodeCamp/freeCodeCamp#45427]
## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional context

__Originally posted by @Lindakay82 in https://github.com/freeCodeCamp/freeCodeCamp/issues/44521__

**Comment by ojeytonwilliams** [comment]
Hi, I'm closing this because it looks like it has been opened by accident.
