### ISSUE TITLE
Spanish translation of Basic JavaScript 

### ISSUE THREAD

**Issue by vtamara** [FreeCodeCamp/FreeCodeCamp#4542]
- [x] Comment your JavaScript Code
- [x] Understand Boolean Values
- [x] Declare JavaScript Variables
- [x] Declare String Variables
- [x] Check the Length Property of a String Variable
- [x] Use Bracket Notation to Find the First Character in a String
- [x] Use Bracket Notation to Find the Nth Character in a String
- [x] Use Bracket Notation to Find the Last Character in a String
- [x] Use Bracket Notation to Find the Nth-to-Last Character in a String
- [x] Add Two Numbers with JavaScript
- [x] Subtract One Number from Another with JavaScript
- [x] Multiply Two Numbers with JavaScript
- [x] Divide One Number by Another with JavaScript
- [x] Create Decimal Numbers with JavaScript
- [x] Multiply Two Decimals with JavaScript
- [x] Divide one Decimal by Another with JavaScript
- [x] Store Multiple Values in one Variable using JavaScript Arrays
- [x] Nest one Array within Another Array
- [x] Access Array Data with Indexes
- [x] Modify Array Data With Indexes
- [x] Manipulate Arrays With pop()
- [x] Manipulate Arrays With push()
- [x] Manipulate Arrays With shift()
- [x] Manipulate Arrays With unshift()
- [x] Write Reusable JavaScript with Functions
- [x] Build JavaScript Objects
- [x] Update the Properties of a JavaScript Object
- [x] Add New Properties to a JavaScript Object
- [x] Delete Properties from a JavaScript Object
- [x] Iterate with JavaScript For Loops
- [x] Iterate Odd Numbers With a For Loop
- [x] Count Backwards With a For Loop
- [x] Iterate with JavaScript While Loops
- [x] Generate Random Fractions with JavaScript
- [x] Generate Random Whole Numbers with JavaScript
- [x] Generate Random Whole Numbers within a Range
- [x] Use Conditional Logic with If and Else Statements
- [x] Sift through Text with Regular Expressions
- [x] Find Numbers with Regular Expressions
- [x] Find Whitespace with Regular Expressions
- [x] Invert Regular Expression Matches with JavaScript
- [x] Create a JavaScript Slot Machine
- [x] Add your JavaScript Slot Machine Slots
- [x] Bring your JavaScript Slot Machine to Life
- [x] Give your JavaScript Slot Machine some Stylish Images

**Comment by vtamara** [comment]
Working on it

**Comment by Oxyrus** [comment]
https://github.com/vtamara/FreeCodeCamp/commit/411b90d4ee62bb0170b0a30e961cbe99d76c3a14#commitcomment-14668833

"Numero" a "Number"
