### ISSUE TITLE
"Create a Component With Composition" Question frozen

### ISSUE THREAD

**Issue by d2vin** [freeCodeCamp/freeCodeCamp#45434]
## Affected page
https://www.freecodecamp.org/learn/front-end-development-libraries/react/create-a-component-with-composition

## Your code

```




```

## Expected behavior
For the page to load 

## Screenshots

After I click on run test, I'm getting alerts that say "page unresponsive", "Something went wrong displaying this webpage.", and "Error Code: 5".
## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
Laptop, MacOS, Chrome

**Comment by ojeytonwilliams** [comment]
Hi @d2vin could you share the code that generates these errors?

**Comment by d2vin** [comment]
```
const ChildComponent = () => {
  return (
    <div>
      <p>I am the child</p>
    </div>
  );
};

class ParentComponent extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h1>I am the parent</h1>
        { /* Change code below this line */ }
        <ParentComponent>
          <ChildComponent />
        </ParentComponent>

        { /* Change code above this line */ }
      </div>
    );
  }
};
```

**Comment by ojeytonwilliams** [comment]
Thanks for sharing your code, @d2vin.  This is a known issue https://github.com/freeCodeCamp/freeCodeCamp/issues/36118 which, unfortunately, we have not managed to resolve, so I'm closing this as a duplicate.  

In short, if a React component tries to render itself, the browser enters an infinite loop and crashes. In your case the `<ParentComponent>` tries to render itself and runs into this problem.
