### ISSUE TITLE
Track user progress separately by certifications paths (with API endpoint)

### ISSUE THREAD

**Issue by rafaelpac** [freeCodeCamp/freeCodeCamp#45463]
## Is your feature request related to a problem? Please describe.
The only public progress indicator of a given user is the total points count.
But those points are a sum of the number of solved challenges on all certifications paths.
I think it would be cool if we had the points separated by certification path and also indicated as a percentage.

## Describe the solution you'd like
On a user page, instead of having the total points progress, display the points separately by certification path.

## Describe alternatives you've considered
It would be great if this is also queryable as an API endpoint.

**Comment by moT01** [comment]
That heatmap is kind of complex and has always been somewhat problematic. I'm not against improvements, but this sounds like added complexity. I'm not sure exactly how you envision this @rafaelpac, perhaps a mock or something might help.

I potentially like the idea of having some user info being available via an api. Not sure if we want to open that up for extra external traffic though.

**Comment by rafaelpac** [comment]
Hi, thanks for your interest!
Today, if I go to my page, this is what I see:

> ![image](https://user-images.githubusercontent.com/6444444/160031160-8c42ae35-d6c6-4695-b9f4-4731db739fae.png)

I have got 96 points from the Responsive Web Design path and 77 from the JS Algorithms and Data Structures path.
That sums up to 173 points. I am not sure where the other 2 points came from.
I would like to see something like this:

> 
![image](https://user-images.githubusercontent.com/6444444/160033193-0a0760c6-c6ea-4b36-887a-cd41a8c8f502.png)

I would like to use this to track my kids progress (with a little python script that I wrote).
To do that today I would need to use something like Selenium, login with their usernames, find the points elements in the DOM and sum them.
It would be much easier and less prone to errors if I could check their public page at once or even better if I can get it from an API.

**Comment by ojeytonwilliams** [comment]
Hi there @rafaelpac I think you might be interested in https://github.com/freeCodeCamp/classroom From the README:

> For a while now teachers have been asking for a way to get a birds eye view of multiple students who are progressing through the course. This is why we set out to make freeCodeCamp classroom mode, an interactive dashboard for teachers to view multiple freeCodeCamp users’ progress on their courses.

Is that more or less what you're looking for?

**Comment by rafaelpac** [comment]
Thanks @ojeytonwilliams! This looks great indeed!
But I am not sure if I know enough to use this, is there a demo version of it running publicly somewhere?

**Comment by moT01** [comment]
cc @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
Thanks for bringing this to my attention. Our profile is due for a redesign and we should make the number more meaningful. It will most likely be a tooltip or a dropdown that reveals more info about the user's points. 

I will work on a mock/wireframe next week, share it here, and we can continue the discussion.

**Comment by Sembauke** [comment]
check #48234
