### ISSUE TITLE
Too unforgiving tests in JS: Use Bracket Notation*

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#45487]
The test regexes don't allow for spaces before the brackets, which is unnecessarily strict.

## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-first-character-in-a-string
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-character-in-a-string

The other two bracket notation exercises are fine, since the assertions don't test the whole line.

## Your code

```
const thirdLetterOfLastName = lastName [2]; 

```

## Expected behavior
Should work just as well as the expected solution of:
```
const thirdLetterOfLastName = lastName[2]; 

```

**Comment by ojeytonwilliams** [comment]
Nice catch @lynxlynxlynx, those should definitely pass.
