### ISSUE TITLE
code folding in the editor breaks the ui (beta responsive web design course)

### ISSUE THREAD

**Issue by lem0n4id** [freeCodeCamp/freeCodeCamp#45481]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-49

## To reproduce

1. Click on toggle button(code folding) on line 36 of the code editor (check screenshots)
2. See error

## Expected behavior

no idea

## Screenshots

![image](https://user-images.githubusercontent.com/61219881/159153538-2de0d0a1-af75-4cbb-868f-2e57c4356c0e.png)
![image](https://user-images.githubusercontent.com/61219881/159153556-9c00d983-9628-4f69-989a-96f441a654c2.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: firefox
- Version: 98.0.1 (64-bit)

**Comment by nhcarrigan** [comment]
I'd be in favour of that solution. Should just be a matter of adding `folding: false` to this editor options object right? https://github.com/freeCodeCamp/freeCodeCamp/blob/94650964c49f7b0f90986dfaf25a034b13315bca/client/src/templates/Challenges/classic/editor.tsx#L231

**Comment by ojeytonwilliams** [comment]
I think so, yeah. We could make it conditional: false if there's an editable region and true otherwise.

That might be nice if you're working on a project using the multifile editor, since they can be quite large and don't have editable regions.

**Comment by nhcarrigan** [comment]
I'll go ahead and open this one up for contribution then 😁

**Comment by MrShadowDev** [comment]
I hope they fix this soon

**Comment by ilenia-magoni** [comment]
@MrShadowDev this issue has been closed 2 years ago as completed. Do you experience this issue? Can you share a screenshot reproducing it?

**Comment by MrShadowDev** [comment]
> [@MrShadowDev](https://github.com/MrShadowDev) this issue has been closed 2 years ago as completed. Do you experience this issue? Can you share a screenshot reproducing it?

I have opened a new issue just hours ago.

**Comment by ilenia-magoni** [comment]
@MrShadowDev I see you opened #57039 but that seems to be feedback that you don't like the new editor, not that there is something not working. And since this issue #45481 code folding was removed to avoid the issue described here.
