### ISSUE TITLE
Suboptimal wording for JS: Find the Length of a String

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#45486]
One of my students got stuck on this exercise, but it turned out to be a spoken language issue, not one of programming.

> Use the `.length` property to count the number of characters in the `lastName` variable and assign it to `lastNameLength`.

They understood the task as being to find the length of `lastName`, but then to still assign `lastName` itself to `lastNameLength`. So exactly the pedantry we want to teach, uncovering undefined behaviour. :)

I suggest changing the text to be more explicit:
> Use the `.length` property to count the number of characters in the `lastName` variable, then assign that length to `lastNameLength`.

## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/find-the-length-of-a-string

**Comment by ojeytonwilliams** [comment]
I'm not convinced anything needs changing here.  The seed of the challenge already has `lastNameLength = lastName` and the student is asked to change the code, which leads them away from that assignment.  The variable name itself tells them what to do.  Finally, the tests are there to guide them.

As for the suggested change, I think it's fine, but unnecessary.

**Comment by lynxlynxlynx** [comment]
Keep in mind, it might be obvious to us who have experience and great or native English proficiency, which was not true in this case (let's say B2 for language and almost zero programming experience). After spending over 15 minutes on something like this, frustrated why the test is failing, I doubt anyone would remember how the original seed looked like. The instructions can be legitimately read so that `lastNameLength = lastName` is the expected solution. Hence the suggestion for change (though I'm not married to particular wording).

**Comment by ojeytonwilliams** [comment]
Thanks.  I'm still not 100% convinced, but I see where you're coming from.  I'll leave this up to other mods, though, since I'm on the fence!

**Comment by ShaunSHamilton** [comment]
I am not sure that is any clearer as to the exact intentions behind the challenge.

My suggestion would be something along the lines of:
> Use the `.length` method to change the `lastNameLength` assignment to equal the number of characters in the `lastName` variable.

**Comment by lynxlynxlynx** [comment]
It's not a method, but more importantly, I think that version is less readable (unbroken length, wording). 

How about a reordering?
> Assign the number of characters in the `lastName` variable to `lastNameLength`. Use the `.length` property to do so.

or
> Set `lastNameLength` to the number of characters in the `lastName` variable by using the `.length` property.

**Comment by ojeytonwilliams** [comment]
> Set lastNameLength to the number of characters in the lastName variable by using the .length property.

That's nice, I think it's at least as clear as the original.  @ShaunSHamilton if you're happy with that, could you open this up to first timers?

**Comment by ShaunSHamilton** [comment]
> It's not a method

Right. Thank you. I have been spending too much time around other languages.

---



The main thing we are trying to clear up, from what I understand is we want Campers to change the given assignment, and not just use the `.length` property. So, unless we mention to change the current assignment, we might as well not be changing anything?

**Comment by lynxlynxlynx** [comment]
We're doing that and I guess it doesn't matter if they decide to do it on an extra line. But we can for example change "Set" above to "Assign" if you think it's clearer.

**Comment by ShaunSHamilton** [comment]
To be clear, I would use:
> Change the given assignment...

**Comment by lynxlynxlynx** [comment]
IMHO that just adds unnecessary complexity. 🤷🏾‍♂️

**Comment by moT01** [comment]
I really don't think there's much of a problem here either. There's tips all over this page...
`You should not change the variable declarations in the // Setup section.`
`You should be getting the length of lastName by using .length like this: lastName.length.`
`// Only change code below this line`

But, I'm guessing some of those tips were added because of others having similar issues. Perhaps part of the problem is that there's too much info. So maybe it could be cleared up a little - I would be fine with the suggestion:
> Set lastNameLength to the number of characters in the lastName variable by using the .length property.

Or here's a similar wording:
> Use the `.length` property to set `lastNameLength` to the number of characters in `lastName`

**Comment by jeremylt** [comment]
> Or here's a similar wording:

> Use the .length property to set lastNameLength to the number of characters in last Name

I like this one if we're going to change it.
