### ISSUE TITLE
inconsistent shadows behind color texts

### ISSUE THREAD

**Issue by wongruiyang** [freeCodeCamp/freeCodeCamp#45484]
Some of the color texts have no shadow while some have.

## Affected page
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/change-the-color-of-text
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-a-css-class-to-style-an-element

## Expected behavior

All the color texts should have a shadow.

## Screenshots

![image](https://user-images.githubusercontent.com/97069075/159167819-e7a8ad80-49be-48af-8e5b-67d7694e4d88.png)
![image](https://user-images.githubusercontent.com/97069075/159167852-27894c80-24e8-40c1-886e-c070e06b9d7c.png)
![image](https://user-images.githubusercontent.com/97069075/159167888-67e0e26a-04ab-41d6-af5b-8cd0c36bdbd4.png)

## System

- Device: [PC]
- OS: [Windows 10]
- Browser: [Chrome]
- Version:

**Comment by wongruiyang** [comment]
I have done a pull request. This is my first time contributing to an open source project.

#45485

**Comment by ieahleen** [comment]
In this case I think it is correct like this, as it is just saying what color to turn the element to. This is also for translations. When it say "property set to" then it needs to be the exact keyword. But colors in generals are not code keywords

**Comment by wongruiyang** [comment]
I think we can assign colors to html elements by using 'color : red' or 'color : blue'. Also, some colors in the guide are shaded while some are not, I hope it can be consistent throughout as it will be more beginner friendly.

**Comment by ieahleen** [comment]
it's formatted as code when it is a keyword to use, like when you say "set this property to `red`", but it's not when it's just a color, like "the `h1` should be red"
Considering that text formatted as code is not to be translated, I would disagree with this change.
"set this property to `red`" -> "questa proprietà dovrebbe avere valore `red`"
"the `h1` should be red" -> "il `h1` dovrebbe essere rosso"
