### ISSUE TITLE
Copy and paste does not work on mobile devices 

### ISSUE THREAD

**Issue by wongruiyang** [freeCodeCamp/freeCodeCamp#45495]
## Affected page
Challenges

## To reproduce

1. Copy any text from the guide in the challenge on any mobile device
2. Paste them onto the editor

## Expected behavior
Text should be pasted to editor

## System

- OS: [Android]
- Browser: [Chrome]

**Comment by wongruiyang** [comment]
> What 
> 
> > 2\. Paste them onto the editor
> 
> What method are you using for pasting?

I tapped and hold then there will be a menu with the Paste selection. For the copying part, i tapped and dragged the part i wanted and then selected copy.

**Comment by nhcarrigan** [comment]
I am unable to reproduce this on:
- Android version 12
- Chrome version 98.0.4758.101

I did, however, get a prompt asking to grant freecodecamp.org access to the clipboard. I would double-check your chrome settings to confirm you did not deny that permission.

**Comment by raisedadead** [comment]
I could not reproduce as well.

However, there is a high chance that this will not be fixed (regardless of the browser/version you are on) because of how Monaco behaves on mobile. I am going to leave it open for now though, in case someone comes up with better.

**Comment by wongruiyang** [comment]
```
I have tried updating my browser and it seems that this error happens only in older versions.

```

**Comment by nhcarrigan** [comment]
Thanks for confirming - given that, I think this issue is good to be closed.
