### ISSUE TITLE
Broken Link in Hint

### ISSUE THREAD

**Issue by jfines** [freeCodeCamp/freeCodeCamp#45505]
## [Affected page](http://forum.freecodecamp.com/t/javascript-arguments/14283.md)
http://forum.freecodecamp.com/t/javascript-arguments/14283.md

The above page is linked to in the Hint page for the **Everything Be True Challenge** 

Challenge Page: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/everything-be-true

Hint Page: https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-everything-be-true/16011

**See Screenshot for detail..**

## Expected behavior

Either the link should resolve to a page containing useful information - pertinent to the challenge being addressed - or the link should be removed from the hint page (preferably the former).

## Screenshots

![Everything Be True Hint Page](https://user-images.githubusercontent.com/86216502/159537525-305ae4f5-0d0e-4061-b4a2-13ae412b49e7.png)

## System

- Device: Laptop
- OS: Ubuntu 20.04
- Browser: Firefox 98.0.1 (64-bit)

**Comment by nhcarrigan** [comment]
Thanks for catching this! I've updated the link in the post.
