### ISSUE TITLE
Show a message after completing a project - RWD beta

### ISSUE THREAD

**Issue by lem0n4id** [freeCodeCamp/freeCodeCamp#45501]
## Is your feature request related to a problem? Please describe.

The platform shows **no indication** saying that you have finished a practice project in the beta RWD. It straight goes to the next challenge and a preview of the next project pops up.

This is kinda an issue because in the end, I want to see what I've made and go through the code again. 

After all, our vision is to focus on more repetition, [especially the new RWD](https://www.freecodecamp.org/news/responsive-web-design-certification-redesigned/)
> Note that for Version 7.0 of the freeCodeCamp curriculum, we are moving toward [an entirely project-focused model with a lot more repetition](https://www.freecodecamp.org/news/python-curriculum-is-live/). - [Contributing guidelines](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges)

## Describe the solution you'd like

After completing the final step of a practice project, there could be a **popup modal** which says "`🎉 You have completed the practice project`" and gives the options "`Continue to the next challenge`" and "`Explore your code before moving on`".

This is inspired from the new [`project preview`](https://github.com/freeCodeCamp/freeCodeCamp/pull/43967) which is shown at the start of every new practice project. 

## Describe alternatives you've considered

We could add a message below `✅ Step completed.` in the output box like `🚀 Project finished. Feel free to go through the code before continuing to the next challenge` 

#### This is a screenshot of the last step of a practice project ([cafe-menu/step-92](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-92))
![image](https://user-images.githubusercontent.com/61219881/159450449-471f6523-45ed-4a5d-92e7-f2aa096658a0.png)

#### This is what you see after clicking `Submit your code and go to next challenge (Ctrl + Enter)`
![image](https://user-images.githubusercontent.com/61219881/159451524-57dcc310-4ab8-41ae-878f-30a2cf6ccfc0.png)

**Comment by lem0n4id** [comment]
> My initial suggestion is to, at least, add a similar sentence to the `cafe-menu`.

This sounds good _for now_. 

However, I feel like showing a modal popup would be a great addition to UX. It will help with better retention of what you've learned if you do decide to take a look at the code again before moving forward. 

So let this be open for discussion, and add a final sentence as **a fix** to the missing sentence in the instructions.

**Comment by ojeytonwilliams** [comment]
Having some form of celebration seems neat. It comes after quite a lot of effort, after all.

@ahmadabdolsaheb this is more your department than mine. Any thoughts?

**Comment by wongruiyang** [comment]
I think like other courses, there should be a modal popout that shows your progress after submitting your codes, or we can perhaps make it even better by having an animation. I feel the preview is abit too small

**Comment by ahmadabdolsaheb** [comment]
Quick note: a progress bar will be added to the button jaw of the editor where the submit button is. That should help a little bit but not ideal.

A few things happen when a user finishes a block (project):
- user is moved to a new block
- the user is shown the block completion donation modal (it should have popped if you are not donating. If not, that is an issue by itself)
- user is shown the preview modal

Here are a few options to consider:

- Telling the users about the completion of the project in the test status div.
- Adding a confetti to the last challenge after passing tests ( I am looking for a home for the confetti :)
- Telling the users about project completion in the description of the last step.
- Adding a final "step" to each project telling people it is all done, enjoy your creation, we are gonna move on..
- Showing a modal.
- etc

I think moving the user to a new project without the user's confirmation ( a button click ) is confusing. Ideally we need to take them somewhere so they could see their progress and evaluate their options. 

Here i would like to propose a learning status component that lives on the top of learn. It would be the first thing people see when they sign in, complete a project, get lost, etc. 

It would show them their progress on their current block, cert and it would include a button to the next suggested action: resume progress on the current block or staring a new project, certification.

This would ideally cut down on a lot of confusion and unnecessary navigation.

**Comment by ShaunSHamilton** [comment]
> It would show them their progress on their current block, cert and it would include a button to the next suggested action: resume progress on the current block or staring a new project, certification.

I like this feature, but with the current state of the client/db state, this has been unreliable: https://github.com/freeCodeCamp/freeCodeCamp/pull/44405

---

> ( I am looking for a home for the confetti :)

😆

**Comment by moT01** [comment]
I like the idea of having a way to just play with the finished code. Maybe a final step on each project with no tests, "You have finished the project... feel free to review and modify your code... run the tests when you are ready to move on"

**Comment by bbsmooth** [comment]
This issue has accessibility concerns as well. We definitely need to make sure that people who are listening to the page are informed that they have completed the project. I would lean toward a modal congratulating them on completing the project and then giving them a few options, such as return to the main curriculum landing page or continue on to the next project.

**Comment by ilenia-magoni** [comment]
Now once a project has finished you get confetti and go back to the list of projects, so I am closing this issue as outdated
