### ISSUE TITLE
Responsive Web Design (Beta) : Learn Responsive Web Design by Building a Piano > Step 10 Issues

### ISSUE THREAD

**Issue by vikramvi** [freeCodeCamp/freeCodeCamp#45516]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-10

## Your code

```
html {
  box-sizing: border-box;
}

*::before, *::after{
  box-sizing: inherit;
}

```

## Expected behavior

1.  Even though I've used `::before` and `::after` as per [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/::before) ,  test fails with error message `You should have a *, ::before, ::after selector.`

2. As per [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/::before) one needs to put selector along with `::before` and `::after` but error message is confusing.

3. Test passes with code as below
  
```
html {
  box-sizing: border-box;
}

*, ::before, ::after{
  box-sizing: inherit;
}
```

This is not correct as special keyword must follow a selector

## Screenshots

<img width="1440" alt="Screen Shot 2022-03-24 at 11 32 29 AM" src="https://user-images.githubusercontent.com/308490/159852950-77823796-2648-41a5-a105-2ba9cef6c457.png">

<img width="1439" alt="Screen Shot 2022-03-24 at 11 37 19 AM" src="https://user-images.githubusercontent.com/308490/159853134-04224fd0-2c56-4123-8e9b-d57f2ce6ec3e.png">

## System

- Device: Laptop
- OS: MAC OS 11.5.2
- Browser: Chrome
- Version: 99

**Comment by ShaunSHamilton** [comment]
Thank you, for taking the time to open this.

For context, the reason it is written like that is because that is how browsers interpret the CSS:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/51722130/159874177-3154c139-0ad3-4fa6-ae71-9862c4e8dca9.png">

---

Also, whilst Mozilla has excellent docs, the examples they use do not represent the CSS Standard:
> If this compound selector is omitted, it is assumed to be the [universal selector](https://drafts.csswg.org/selectors-4/#universal-selector) [*](https://drafts.csswg.org/selectors-3/#x).

https://drafts.csswg.org/selectors-4/#pseudo-element-attachment

---

As such, I am going to close this issue

**Comment by vikramvi** [comment]
@ShaunSHamilton Please check **Expected Behaviour** code again 

```
*, ::before, ::after{
  box-sizing: inherit;
}
```

Isn't this a wrong syntax ? 

Students will get confused with wrong syntax. The bug is about fixing to correct syntax to make test passs.

Please revisit this bug and re-open

**Comment by ShaunSHamilton** [comment]
> Isn't this a wrong syntax ?

No, this **is correct**. As per CSS spec:
> If this compound selector is omitted, it is assumed to be the [universal selector](https://drafts.csswg.org/selectors-4/#universal-selector) [*](https://drafts.csswg.org/selectors-3/#x).

---

> The bug is about fixing to correct syntax to make test pass.

I can see no bug. The syntax is correct as per CSS specification, and the tests pass as expected.
