### ISSUE TITLE
Automatic submit challenge after passing all the tests

### ISSUE THREAD

**Issue by wongruiyang** [freeCodeCamp/freeCodeCamp#45511]
## Is your feature request related to a problem? Please describe.

Currently, when you do not press the submit challenge on the pop out after passing all the tests, the system considers that you have not completed the challenge. 

## Describe the solution you'd like
I would like to propose an automatic submission of the challenge after passing all the tests, and the 'Submit and go to next challenge' button can be changed to 'Go to next challenge'.

**Comment by moT01** [comment]
I think the technical complexities in implement this aren't worth the benefit. Not sure, maybe it wouldn't be as difficult as I think. I don't really have any other arguments against this, other than it's just not the way it was designed to work. Here's one scenario I guess, we will soon have the certification projects using this platform that the other main challenges are using. Perhaps a user wants to just run the tests to see if they pass, but not submit the project yet. I suppose the same could be said for the challenges.

I'm open to discussion, but I would vote to leave it how it is at the moment.

**Comment by nhcarrigan** [comment]
I think I'm in agreement with Tom that this isn't worth the technical overhead to implement.
