### ISSUE TITLE
Add block intro pages for RDB

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45523]
I never got around to adding these intro pages for the relational databases. e.g. [block intro for basic html](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/) The files are located [here](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/client/src/pages/learn)

**Comment by Sembauke** [comment]
We thought about removing them altogether:
https://github.com/freeCodeCamp/freeCodeCamp/issues/43289

**Comment by moT01** [comment]
Closing in favor of the linked related issue.
