### ISSUE TITLE
(RDBMS: Bash Boilerplate) - Confusing instructions on step 160

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45521]
Several users have had an issue with [step 160](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md#160-long-list-format). They are confusing the `-l` with a `-1`. Clarify that it's an `-l`.

**Comment by wongruiyang** [comment]
It is ``-l``

**Comment by moT01** [comment]
Fixed via https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/pull/16
