### ISSUE TITLE
Safari doesn't support scroll behavior

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45524]
As described in [this issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/44754#issuecomment-1013932793), Safari doesn't support scroll-behavior. The step in question is [step 65 of the quiz](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-65). Here's what the test currently looks like: `assert.equal(new __helpers.CSSHelp(document).getStyle('*')?.scrollBehavior, 'smooth');`. We should change the test, there's a few suggestions in that thread. We could also probably look around to see if any other steps are checking for that property like this.

**Comment by Sembauke** [comment]
https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes 

they do now

**Comment by bbsmooth** [comment]
Ya, but I believe that you can only run the newest version of Safari on the newest OS, right? It's going to be a while before the vast majority of Safari users have upgraded to a version of Safari that supports `scroll-behavior` so we should probably implement a workaround for this.

**Comment by ShaunSHamilton** [comment]
@bbsmooth Safari 15.4 should be downloadable (is supported) for MacOS v10.14.6+

That is, the latest 4 versions (spanning 2018+). Sounds reasonable that many/most Campers using MacOS would meet those requirements.

I assume Safari automatically updates to the latest version compatible with the device.

**Comment by raisedadead** [comment]
Yeah, while ideally, we cover all the browsers (or at least a few versions back), balancing that with maintaining curricular content is almost impossible. The latter is our priority and the best use of the time of both contributors and staff.

Technically we do not have any SLAs (for a free-to-use service), but at least, more empathically speaking, we make every effort to support the latest "LTS" or stable versions of OS and browsers.

IMHO, it's fair to assume that users will need to update the browser to a stable/latest version. Not saying we are happy suggesting it, but it's a better use of everyone's time. Almost every device can use an alternative browser than Safari (as inconvenient as it might be for an end-user).

Going ahead and closing this as a wontfix.
