### ISSUE TITLE
(RDB: Learn RDB's) hint on 1260 gives wrong answer

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45532]
The instructions on [this step](https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/main/TUTORIAL.md#12601) ask you to display the tables, the shortcut command for that is `\d` - the hint says to use `\l`, the display databases shortcut. It can just be changed to that.

**Comment by wongruiyang** [comment]
the hint also says to use list command to display the table. It should be changed to 'Use the display shortcut command' instead.

**Comment by moT01** [comment]
Fixed in [v1.0.4](https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/main/CHANGELOG.md#v104)
