### ISSUE TITLE
Create seperate Beta DB, Beta Branch

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4554]
Please create a separate Beta from the live DB and put it on its own branch.

Create a "staging-beta" branch to commit beta-only changes to . . . or whatever makes the most sense.

**Comment by BerkeleyTrue** [comment]
I don't think we need a separate beta branch. If a feature gets to the point where it needs to be tested behind a live url it can be merged into staging and tested on beta url. 

Anything that shouldn't be merged into staging doesn't need to be tested behind a url.

**Comment by SaintPeter** [comment]
You misunderstand - it's not a matter of features.  It's a matter of doing a lot of high touch editing on a bunch of existing waypoints as I add new content and harmonize what has been written with what I'm writing. 

I want to be able to point reviewers/testers to Beta to review the new content before it goes live, so I can get the painful editing out of the way on Beta branch.  I don't want to do that testing/editing on live like what happened with the new OO and jQuery stuff.  I also don't want to have to push it to staging and then be blocked from releasing hot-fixes during that time frame, like the site was blocked for a month+ back in May/June with the switch to loopback.io.

By maintaining a separate beta branch I can push out whatever edits I want, get feedback, make corrections, etc, without interfering with live.  And once I'm confident that the new material is up to snuff, then we can re-sync with staging and push it all over in one swell foomp.  I'll take responsibility for keeping `staging-beta` current with `staging`, so we don't have to worry about merge conflicts once I'm good to go.

If you have an alternate proposal to be able to do what I'm proposing in a non-blocking way, I'm all ears.

**Comment by bugron** [comment]
@SaintPeter @BerkeleyTrue are you still discussing this?

**Comment by SaintPeter** [comment]
I thought I had convinced @BerkeleyTrue, but I don't know for sure.

**Comment by BerkeleyTrue** [comment]
@SaintPeter Yes, we will have a separate DB when it is needed.

**Comment by BerkeleyTrue** [comment]
done
