### ISSUE TITLE
Screen reader only text on icons

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#45551]
## Affected page

[Curriculum landing page](https://www.freecodecamp.org/learn/) and each certification landing page.

## Discussion

The icons on the curriculum landing page and each of the associated certification landing pages have screen reader only text associated with them that describes the icon (basically acting as alt text for an image). For example, on the curriculum landing page, the Responsive Web Design Certification link has an icon of a laptop and mobile phone with hidden screen reader only text immediately preceding the icon that reads "Laptop and mobile phone icon":

```
<a class="btn link-btn btn-lg" href="/learn/responsive-web-design/">
  <div style="display: flex; justify-content: space-between; align-items: center;">
    <span class="sr-only">Laptop and mobile phone icon</span>
    <svg viewBox="0 0 640 512" xmlns="http://www.w3.org/2000/svg" class="map-icon">...</svg>
    Responsive Web Design Certification (300&nbsp;hours)
  </div>
</a>
```

It does not seem apparent to me that these icons add any additional value to the content and are thus purely decorative in nature and should not have any "alt" text associated with them. I am recommending that the screen reader only text be removed and the svg be hidden using `aria-hidden="true"`.  This aligns with [current best practices for decorative images](https://www.w3.org/WAI/tutorials/images/decorative/).

I just want to make sure no one has any objection or considers these icons more than decorative before I spend the time removing the screen reader only text.

**Comment by Adin9** [comment]
bruh

**Comment by raisedadead** [comment]
@bbsmooth, please proceed with your recommendation.

**Comment by Sboonny** [comment]
I am wondering how the progress in this issue going? And if I can help with it. 🤔

**Comment by bbsmooth** [comment]
@Sboonny I had to take a break for the past few weeks as I was preparing for a rather intense certification exam. I just took it today and so now I'm back and will have some time to do this this in the next few days.

**Comment by Sboonny** [comment]
I see. Sorry if I sounded like I am rushing you 😓, I hope your exam has gone well. Take it easy and I can't wait for your commit🍻
