### ISSUE TITLE
are these colors keywords?

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#45556]
In the Responsive Web Design challenge [adjust-the-hue-of-a-color.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/adjust-the-hue-of-a-color.md)

there are these sentences 
> Your code should use the <code>hsl()</code> function to declare the color <code>green</code>.

> Your code should use the <code>hsl()</code> function to declare the color <code>cyan</code>.

> Your code should use the <code>hsl()</code> function to declare the color <code>blue</code>.

As I don't think these colors are keywords, I propose to remove the backticks for translation purposes

**Comment by ojeytonwilliams** [comment]
Bit of a weird one, tbh.  Those all *are* html color codes, but they're really just being used as names for colors.  Anyways, it seems reasonable to stop using them as keywords, honestly.

**Comment by ojeytonwilliams** [comment]
Sure, I agree that they shouldn't be keywords.  I was just speculating as to why they're currently keywords.

**Comment by JordanMooree** [comment]
I was playing around with the markdown syntax and feel like bolding the colors like this looks neat.

For example:

> Your code should use the `hsl()` function to declare the color **blue**.

I also tried italicizing:

> Your code should use the `hsl()` function to declare the color *blue*.

Or I can also bold and italicize it:

> Your code should use the `hsl()` function to declare the color **_blue_**.

Let me know what you think looks best
