### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SeanB99** [FreeCodeCamp/FreeCodeCamp#4556]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=%0A%0Avar%20palindrome%20%3D%20function(str)%20%7B%20str%20%3D%20str.replace(%2F%5B%5C.%2C-%5C%2F%23!%24%25%5C%5E%26%5C*%3B%3A%7B%7D%3D%5C-_%60~()%40%5C%2B%5C%3F%3E%3C%5C%5B%5C%5D%5C%2B%5D%2Fg%2C%20%27%27).toLowerCase()%3B%20return%20str%20%3D%3D%3D%20str.split(%22%22).reverse().join(%22%22)%3B%20%7D%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; LG-D321 Build/KOT49I.D32110d) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


var palindrome = function(str) { str = str.replace(/[\.,-\/#!$%\^&\*;:{}=\-_`~()@\+\?><\[\]\+]/g, '').toLowerCase(); return str === str.split("").reverse().join(""); }
palindrome("eye");

```
Everything checks out beside (race car) and 2 others. At first i thought it was an issue with spaces and used /\s/g in replace(), but after pulling my hair out I literally used the answer (the one not using recursion) from Github and its not working

**Comment by SeanB99** [comment]
Aswer i input from https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Bonfire-Check-for-Palindromes

function palindrome(str) {
  var normalizedStr = str.replace(/[\W_]/g, '').toLowerCase();
  var reverseStr = normalizedStr.split('').reverse().join('');
  return normalizedStr === reverseStr;
}

**Comment by SeanB99** [comment]
Well answer from Github works. Copying error on my part. Don't understand the error in mine though. Guess I'll have to trudge through it more.

**Comment by SaintPeter** [comment]
The problem is, indeed, that you are not removing spaces.  Simply adding a space to your character class causes it to pass all tests.
