### ISSUE TITLE
The last 2 conditions passed even though I am yet to replace integers 0,1 with \d

### ISSUE THREAD

**Issue by rejreign** [FreeCodeCamp/FreeCodeCamp#4557]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20newStr1%20%3D%20str.replace(%2F%5B%5Cs%5C.%2C%5D%2Fg%2C%22%22).toLowerCase()%3B%0A%20var%20newStr2%20%3D%20str.replace(%2F%5B%5Cs%5C.%2C%5D%2Fg%2C%22%22).toLowerCase().split(%22%22).reverse().join(%22%22)%3B%0A%0Aif(newStr1%20%3D%3D%3D%20newStr2)%0A%7B%0A%20%20return%20true%3B%0A%7D%0A%0Aelse%0A%7B%0A%20%20return%20false%3B%0A%7D%0A%0A%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var newStr1 = str.replace(/[\s\.,]/g,"").toLowerCase();
 var newStr2 = str.replace(/[\s\.,]/g,"").toLowerCase().split("").reverse().join("");

if(newStr1 === newStr2)
{
  return true;
}

else
{
  return false;
}


}



palindrome("My age is 0, 0 si ega ym.");

```

**Comment by faizaanceg** [comment]
There is no need to remove the integers. Just the punctuation is enough.

**Comment by rejreign** [comment]
@jlslew @faizaanceg How so? Also, when I complete the code, it still doesn't compile correctly.  
![screenshot_2015-11-19-13-25-58](https://cloud.githubusercontent.com/assets/13300617/11271096/2425df24-8ec4-11e5-91ee-4a885be19eff.png)

**Comment by faizaanceg** [comment]
Well for the last case, you have to remove *all* punctuation. This means `_, -, (, ), :, / ,\ ` should be removed from the string.

**Comment by bugron** [comment]
@rejreign thanks for posting this issue!
See #4495. Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by rejreign** [comment]
@jlslew @faizaanceg @bugron     I have completed the code, still it doesn't compile correctly
![screenshot_2015-11-19-14-03-51](https://cloud.githubusercontent.com/assets/13300617/11271536/c00894b6-8ec6-11e5-98d8-425f736c43b8.png)

**Comment by bugron** [comment]
@rejreign you should escape minus sign in your regex, try `\-` instead of `-`.

**Comment by rejreign** [comment]
@bugron The only condition with - passes.

**Comment by rejreign** [comment]
All the 3 conditions that didn't pass(see pix above) should return true. Write them down and you'll see.
@faizaanceg @bugron @jlslew

**Comment by rejreign** [comment]
<
```
1

function palindrome(str) {

2

// Good luck!

3

var newStr1 = str.replace(/[\s\.,]/g,"").toLowerCase();

4

    newStr1 = newStr1.replace(/[\(\)\-_:\\\/]/g,"");

5

var newStr2 = str.replace(/[\s\.,]/g,"").toLowerCase().split("").reverse().join("");

6

    newStr2 = newStr2.replace(/[\(\)\-_:\\\/]/g,"");

7

​

8

if(newStr1 === newStr2)

9

{

10

return true;

11

}

12

​

13

else

14

{

15

return false;

16

}

17

​

18

}

19

palindrome("eye");

20

```
>

**Comment by faizaanceg** [comment]
`Palindrome(1eyeforof1eye)` -> `eye1forofeye1` 

The palindrome is not the same. So it's false.

`Palindrome(myageis00siegaym)` -> `myageis00siegaym`

They are the same. So it's true.
