### ISSUE TITLE
Too unforgiving tests in JS: Use typeof to Check the Type of a Variable

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#45570]
The test regexes don't allow for spaces before the parentheses, which is unnecessarily strict.

## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/use-typeof-to-check-the-type-of-a-variable

## Your code

```
console.log (typeof seven);
console.log (typeof three);
```

## Expected behavior

Same as:
```
console.log(typeof seven);
console.log(typeof three);
```

**Comment by sonAndrew** [comment]
What do you mean by "unnecessarily strict"?

**Comment by jeremylt** [comment]
I'm not wild about relaxing the tests to suppor irregular/unusual formatting. It's uncommon to stick spaces between the function/method nane and the ()s for the argument list in JS.

**Comment by lynxlynxlynx** [comment]
People do it, otherwise we wouldn't be careful about it in most tests. I guess my student keeps doing it because it's the norm in natural languages. FCC doesn't teach or enforce style and I'm sure you know code formatting is a major source of bikeshedding anyway. Silly details like this shouldn't get in the way of learning.

**Comment by sonAndrew** [comment]
If you call a method with a space between the name and parentheses then that method would not work. Why promote bad syntax when learning?

**Comment by jeremylt** [comment]
Some people do it but it is really uncommon. Making the code readable to other people is part of getting hired. This just isn't a thing that you see in production code. JS has a bunch of these little things that are technically possible but never used. There is a huge difference between bikeshedding on indentation or semicolons and going out of our way to support baffling, non-standard syntax that nobody uses in professional code.

We're made notes about this sort of thing in the past so learners don't get in the habit of writing technically correct but bizzaro code:

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/access-array-data-with-indexes

> Note: There shouldn't be any spaces between the array name and the square brackets, like array [0]. Although JavaScript is able to process this correctly, this may confuse other programmers reading your code.

And all of our examples of using functions follow the basic convention in JS of not jamming extra spaces in there, from the beginning:

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/write-reusable-javascript-with-functions

> You can call or invoke this function by using its name followed by parentheses, like this: functionName(); 

I don't see why we'd be obligated to support every single non-standard thing that a learner can imagine.

**Comment by jeremylt** [comment]
We have 400-500 asserts designed to allow spacing in between the function name are ()s? Odd.

**Comment by lynxlynxlynx** [comment]
The spacing leniency is not limited to that one case, of course ...

**Comment by Sboonny** [comment]
I agree with
> It's uncommon to stick spaces between the function/method nane and the ()s for the argument list in JS.

but the people who type
```
console.log (typeof seven);
console.log (typeof three);
```
should get more descriptive fallback error instead 
>Your code should use typeof in two console.log() statements to check the type of the variables.

because in console it logs 'number' and 'string' when the code above is used.
maybe changing this
>Your code should use typeof in two console.log() statements to check the type of the variables.

to 
>Your code should be in the correct format while using typeof in two console.log() statements to check the type of the variables.

**Comment by lynxlynxlynx** [comment]
Neither syntax is incorrect, one is just less common. 
There is already wide support for being lax in tests like these. Most recently the discussion was in the previously linked #45575, where the core team weighed in as well. So the main thing that should be done in this bug is just to fix the tests. Other bugs should have their own issues.
