### ISSUE TITLE
Remove Style Note

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#45575]
https://github.com/freeCodeCamp/freeCodeCamp/issues/45487

I see here that we are intentionally supporting confusing but technically correct syntax. In light of this, we should remove the note here

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/access-array-data-with-indexes

> Note: There shouldn't be any spaces between the array name and the square brackets, like array [0]. Although JavaScript is able to process this correctly, this may confuse other programmers reading your code.

---

```
myFunction (args);
myArray [0];
myString [0];
```

All of these are non-standard things that technically work but nobody actually does in practice. We should either go out of our way to support this sort of thing or not. If we are going out of our way to support this sort of thing, then there really isn't much point of letting the users know that it's unconventional syntax.

See also:
https://github.com/freeCodeCamp/freeCodeCamp/issues/45570

---

Personally, I think it's valuable to teach the learners how to write code that others expect to see so that it's easier for them to get hired, but we really need to be consistent. We should either help them with conventions or not bother. If we aren't doing anything after making the note, then it's just visual noise and should be removed.

**Comment by nhcarrigan** [comment]
For what it's worth:

```js
const myArray = [50, 60, 70];
const myData = myArray [0];
```

This code fails the "bracket notation" test, presumably because of the space. And I'm of the opinion that it should stay that way (I'd be okay with updating the test to allow spacing and adding a third test that clarifies "you should not have spacing").

That being said, there are areas where we are more lenient on the spacing/conventional style, which IMHO is okay if that's not the concept being taught/tested.

**Comment by ojeytonwilliams** [comment]
For what it's worth here's what I think about formatting.  In practice the likes of prettier have rendered manual formatting unnecessary and unhelpful - I don't need to see diff noise obscuring actual code changes.

If we're overly picky about formatting then I can see that creating a frustrating experience.  However, we should provide nicely formatted code in the examples.  That way learners can pick up good habits simply by copying.

**Comment by jeremylt** [comment]
I'm generally pretty flexible with formatting. I don't think we have any business requiring a  specific bracket and indentation style. I'll format utterly unformatted code when someone asks for help and explain how it helps me and the learner discuss the code more easily, but that's a very useful context to discuss readability.

But the extra spaces in the above three examples are so unusual and uncommon of syntax that it feels strange to make our tests permit them in the recent couple of issues while also calling it out here as something to not do.

**Comment by lynxlynxlynx** [comment]
I disagree with both propositions — the note is fine, we should encourage standard style. But also let's not be a PITA.

I'll copy my other comment here, so we can have a discussion in a single place:

> Well, we've already been doing this spacing leniency for ages, so it's not like I'm proposing some novelty. Or anything absurd (your strawman of "every single non-standard thing"). I count uses in between 400-500 of our test asserts, so they're pretty much everywhere.
> 
> If we wanted to enforce style, we would have tests for that, not letting unrelated tests fail and be opaque at it. It just breaks the learning flow, so I can completely understand why we do it as we do. Forceful automatic code reformatting would also be silly.

**Comment by jeremylt** [comment]
If we aren't going to enforce it, it's just pointless noise that needs to be removed.

**Comment by jeremylt** [comment]
I find the accessibility concern more compelling than just allowing highly uncommon syntax variations because it can run in other JS environments.

But I still say that it we aren't going to test it, then the spacing note should not be there. If its not part of the challenge outcomes, then it's noise. We already struggle to get learners to actually read the parts of the text that relate to their ability to pass the challenge.

**Comment by bbsmooth** [comment]
Allow me to revise my previous answer just a little. I think I was assuming that this extraneous space issue was being tested in all challenges, but now I'm realizing that it may apply to only this one particular challenge. If so, then as long as the challenge makes it clear that this is a requirement to pass the challenge, and there is a clear error message that indicates the reason the test failed is due to the extraneous space, then I think it is OK to leave this test in there if it's deemed important enough to keep.

But in general, I do not think such formatting issues should cause a test to fail (as explained above).

**Comment by raisedadead** [comment]
Thanks for the thoughts @jeremylt & @bbsmooth 

Here is what we should do:

1. Remove the note. IMHO you all are correct in assuming it does nothing other than draw attention to a confusing notion.
2. We should support the technically correct syntax. Autoformatting may be a good idea, but I am afraid of accidentally introducing something else.
