### ISSUE TITLE
Out of box feature request 🤔

### ISSUE THREAD

**Issue by neerajcodes** [freeCodeCamp/freeCodeCamp#45584]
Hey i think that's the very big community of developers, 
Hii i am neeraj and learning programming, i loved making applications and websites. 

My question about taking screenshots

1. In Android development it's so easy to take screenshot of a view.
2. In ios is also simple to take screenshot of a UIview.

But in javascript why doesn't possible to take screenshot of a dom element correctly. 

I know some third party libraries like
 `dom-to-image `
`html-to-image`
`capture-dom`
`html2canvas`

And many more but they have lots of bugs like they doesn't support filters, new technology like backdrop filters and other.

### So everyone who loved and experts in web programming 

Can you develop a library for taking screenshot of a dom element with no bug.

If it is possible so reply my msg or not,

Happy Coding to everyone 👌👌👌

**Comment by ieahleen** [comment]
this repo is for bugs and feature requests for the freeCodeCamp website and curriculum, not the place to request coding tasks
