### ISSUE TITLE
`npm run first-time` failing

### ISSUE THREAD

**Issue by anthonygore** [FreeCodeCamp/FreeCodeCamp#4558]
This is the output of my npm-debug.log:

12 error Darwin 15.0.0
13 error argv "/usr/local/Cellar/nvm/0.29.0/versions/node/v4.2.2/bin/node" "/usr/local/opt/nvm/versions/node/v4.2.2/bin/npm" "run" "first-time"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error freecodecamp@0.1.0 first-time: `npm run create-rev && echo '
17 error
17 error seeding database
17 error
17 error ' && node seed && node seed/nonprofits`
17 error Exit status 1
18 error Failed at the freecodecamp@0.1.0 first-time script 'npm run create-rev && echo '
18 error
18 error seeding database
18 error
18 error ' && node seed && node seed/nonprofits'.
18 error This is most likely a problem with the freecodecamp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run create-rev && echo '
18 error
18 error seeding database
18 error
18 error ' && node seed && node seed/nonprofits
18 error You can get their info via:
18 error     npm owner ls freecodecamp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by faizaanceg** [comment]
Which version of node are you using?

**Comment by xDae** [comment]
I have the same problem
node v5.10

**Comment by bugron** [comment]
@anthonygore @xDae try Node v4.2.

**Comment by ltegman** [comment]
I can reproduce this error with node 4.2.1

**Comment by ltegman** [comment]
Looks like v0.28.0 or react-bootstrap removed this module: https://github.com/react-bootstrap/react-bootstrap/releases/tag/v0.28.0

**Comment by ltegman** [comment]
Working on getting us compliant with the new version of react-bootstrap right now.

**Comment by anthonygore** [comment]
@faizaanceg I've tried node versions 4.2.2 and 5.0.0, both fail. I'll experiment more later but I think @ltegman is on the right track

**Comment by BerkeleyTrue** [comment]
@ltegman We are still on 0.27

**Comment by anthonygore** [comment]
There was a similar issue reported here, I tried the solution but couldn't get it working https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4244

**Comment by ltegman** [comment]
@BerkeleyTrue Not as of this PR: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4479

**Comment by BerkeleyTrue** [comment]
@anthonygore Does running `gulp` not work?

**Comment by ltegman** [comment]
@BerkeleyTrue The update to react-bootstrap 0.28.1 broke `node seed`

**Comment by BerkeleyTrue** [comment]
@ltegman we are still on React-boostrap 0.27.

**Comment by BerkeleyTrue** [comment]
NVM was looking at the wrong file

**Comment by anthonygore** [comment]
@BerkeleyTrue when I run gulp I get:

Failed loading boot script: /Users/anthonygore/Projects/freecodecamp/server/boot/a-react.js
Error: Cannot find module 'react-bootstrap/lib/BootstrapMixin'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function._load (/Users/anthonygore/Projects/freecodecamp/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/anthonygore/Projects/freecodecamp/common/app/components/Nav/NavItem.jsx:2:36)
    at Module._compile (module.js:435:26)
    at normalLoader (/Users/anthonygore/Projects/freecodecamp/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/anthonygore/Projects/freecodecamp/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function._load (/Users/anthonygore/Projects/freecodecamp/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/anthonygore/Projects/freecodecamp/common/app/components/Nav/Nav.jsx:12:36)
    at Module._compile (module.js:435:26)

**Comment by BerkeleyTrue** [comment]
@ltegman Are you working on a PR?

**Comment by ltegman** [comment]
I am, but I got caught up in work and probably won't be able to finish it out for a couple hours. You can go ahead and do it if you've got the time.

**Comment by BerkeleyTrue** [comment]
@anthonygore I've reverted back to bootstrap 0.27.3. 

please do the following:
```bash
rm -rf node_modules
npm install
node seed
gulp
```

**Comment by anthonygore** [comment]
@BerkeleyTrue that works (after a git pull)

**Comment by BerkeleyTrue** [comment]
awesome. 

Happy Coding!

**Comment by 0x0936** [comment]
I was getting the same error as OP, yesterday and today. @BerkeleyTrue your directions work, but perhaps the README.md should be updated to reflect this, because npm run first-time still doesn't work.
