### ISSUE TITLE
typos and flow issues in wiki page

### ISSUE THREAD

**Issue by ArbitraryHubris** [FreeCodeCamp/FreeCodeCamp#4559]
I would love to be able to submit edits on the wiki when I find issues.  The Javascript styleguide, for example, has some misplaced code block endings leading to markdown showing up in the finished product.  https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Free-Code-Camp-JavaScript-Style-Guide#indent.  Can I help?

For example, space after function name section is actually part of the Curly Braces Everywhere section because of misplaced triple backticks.

## space after `function` keyword expect in anonymous functions.

**Comment by bugron** [comment]
@ArbitraryHubris thanks for posting this issue!
If you want to contribute to our wiki you should fork https://github.com/FreeCodeCamp/wiki repository, make changes in your fork and then create a pull request. Before contributing, please read these articles:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Style-Guide
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/wiki-js-template
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ArbitraryHubris** [comment]
Thanks!  Closing.
