### ISSUE TITLE
Sample Image

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#45592]
## Affected page

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website

## Your code

```
<h2>CatPhotoApp</h2>
<main>

<img src="https://www.freecatphotoapp.com/your-image.jpg" alt="fcc-relaxing-cat">
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>
```

## Screenshots

![image](https://user-images.githubusercontent.com/25011573/161177547-1196058e-0f6c-4f5b-b46e-f7a2040841b0.png)

## Additional context

Could we change this sample image to something that is obviously not a cat so that users have a more obvious clue that they are using the wrong url for their `src` attribute? Maybe a nice picture of our logo or a camperbot?

**Comment by nhcarrigan** [comment]
I'd be in favour of that.

**Comment by joshkh87** [comment]
this isn't a bug. this is more of a preference change. while I understand and agree with the change suggested and I do think that having an unrelated image as a sort of boiler plate that gives an instant "hey!! jerk!! this is not a cat". that being said, this is a misclassification of what the issue is.. the code is not incorrect nor does it pose any security or syntax issues to the user . there for not a bug.

**Comment by joshkh87** [comment]
```
<h2>CatPhotoApp</h2>
<main>

<img src="https://bit.ly/fcc-running-cats" alt="fcc-relaxing-cat">
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>
```

**Comment by jeremylt** [comment]
I wouldn't worry too much about the tag - it's automatically generated. Not worth obsessing over.

**Comment by nhcarrigan** [comment]
Going to go ahead and open this one up for contribution.

The referenced example image is found in this repo: https://github.com/freeCodeCamp/freeCatPhotoApp

And can be replaced with this image: https://github.com/freeCodeCamp/cdn/blob/main/build/platform/universal/logo-512X512.png (make sure to keep the `your-image.jpg` filename so the links in the curriculum still work.
