### ISSUE TITLE
Typo in the spelling of HTML

### ISSUE THREAD

**Issue by meenal2000** [freeCodeCamp/freeCodeCamp#45596]
Link to the page with the problem - https://www.freecodecamp.org/news/css-positioning-position-absolute-and-relative/

Problem - In the heading "What is the default position of HTML elements in CSS?" , the first line includes HTLM instead of HTML .
There's another typo too in the heading "What is position relative in CSS?" . The third para has a wrong spelling for earliar . 
![image](https://user-images.githubusercontent.com/53430411/161235698-9bda206e-2c3f-4a44-a6dc-10a9c692d765.png)

![image](https://user-images.githubusercontent.com/53430411/161221905-c066f2c1-93e3-40d8-a2c2-eea95abc8a5b.png)

**Comment by moT01** [comment]
Thanks for pointing this out @meenal2000. I updated the article, it will be live on the next publish.

**Comment by meenal2000** [comment]
You're welcome 👍 . In between , there are more similar typos in the page and maybe someone can re-read it again and correct them ;

**Comment by scissorsneedfoodtoo** [comment]
Hi @meenal2000, thanks again for pointing out the original typo, and for mentioning that there were a couple more.

I went through the article and fixed those typos, and also tweaked the formatting for the code snippets.

Please let us know if you notice any other issues in this or other articles.
