### ISSUE TITLE
[RDB] Clarify Salon Appointment Scheduler "Subtask 1.1:16" user story

### ISSUE THREAD

**Issue by Ken-Leung-5** [freeCodeCamp/freeCodeCamp#45595]
## Affected page

Relational Database Alpha
[Salon Appointment Scheduler](https://raw.githubusercontent.com/freeCodeCamp/learn-salon-appointment-scheduler/main/tutorial.json)

## Your code

```
#! /bin/bash
PSQL="psql -X --username=freecodecamp --dbname=salon --tuples-only -c"
# display title
  echo -e "\n~~~~~ MY SALON ~~~~~\n"
  echo -e "Welcome to My Salon, how can I help you?\n"

# get services
SERVICES=$($PSQL "SELECT service_id, name FROM services ORDER BY service_id;")

MAIN_MENU(){

  # display argument if exist
  if [[ $1 ]]
  then
    echo -e "\n$1"
  fi

  # show service menu
  echo "$SERVICES" | while read SERVICE_ID BAR SERVICE_NAME
  do
    echo "$SERVICE_ID) $SERVICE_NAME"
  done

  read SERVICE_ID_SELECTED
  #if input is not INT
  if [[ ! $SERVICE_ID_SELECTED =~ ^[0-9]+$ ]]
  then
    # return to main menu
    MAIN_MENU "I could not find that service. What would you like today?"
  fi

  SERVICE_ID=$($PSQL "SELECT service_id FROM services WHERE service_id =$SERVICE_ID_SELECTED;")
  #if the number input not found
  if [[ -z $SERVICE_ID ]]
  then
    # return to main menu
    MAIN_MENU "I could not find that service. What would you like today?"
  fi
  SERVICE_NAME=$($PSQL "SELECT name FROM services WHERE service_id=$SERVICE_ID")

  # if a valid option
  # ask for phone number
  echo -e "\nWhat's your phone number?"
  read CUSTOMER_PHONE
  CUSTOMER_NAME=$($PSQL "SELECT name FROM customers WHERE phone='$CUSTOMER_PHONE';")
  

  # if customer not found
  if [[ -z $CUSTOMER_NAME ]]
  then
    # ask for customer name
    echo -e "\nI don't have a record for that phone number, what's your name?"
    read CUSTOMER_NAME
    # insert customer data
    UPDATE_CUSTOMER_RESULT=$($PSQL "INSERT INTO customers(phone, name) VALUES('$CUSTOMER_PHONE','$CUSTOMER_NAME');")
  fi
  CUSTOMER_ID=$($PSQL "SELECT customer_id FROM customers WHERE phone='$CUSTOMER_PHONE';")

  # add appointment time
  echo -e "\nWhat time would you like your $(echo $SERVICE_NAME | sed -r 's/^ *| *$//g'), $(echo $CUSTOMER_NAME | sed -r 's/^ *| *$//g')?"
  read SERVICE_TIME

  # if no time input
  if [[ -z $SERVICE_TIME ]]
  then
    MAIN_MENU "You have to input the time, please try again"
  fi

  #insert appointment
  APPOINTMENT_RESULT=$($PSQL "INSERT INTO appointments(customer_id, service_id, time) VALUES($CUSTOMER_ID, $SERVICE_ID, '$SERVICE_TIME')")
  if [[ $APPOINTMENT_RESULT=='INSERT 0 1' ]]
  then
    echo -e "\nI have put you down for a $(echo $SERVICE_NAME | sed -r 's/^ *| *$//g') at $(echo $SERVICE_TIME | sed -r 's/^ *| *$//g'), $(echo $CUSTOMER_NAME | sed -r 's/^ *| *$//g')."
  else
    MAIN_MENU "Unexpected error occur, please try again."
  fi
}


MAIN_MENU
```

## Expected behavior

I expect it should pass subtask 1.1:16 "If you pick a service that doesn't exist, you should be shown the same list of services again"

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional context

I tried many times, and the code seems fulfill all requirements (especially subtask 1.1:16) (passed all other subtask already)
It's great if anyone can point out the problem

After the user input SERVICE_ID_SELECTED, the code check whether input is a number. If it is a number, the code will check whether the service_id exist in services table. User will be sent back to MAIN_MENU if either condition do not pass

**Comment by moT01** [comment]
Can you share a dump of your database using the command in the instructions @Ken-Leung-5? `pg_dump -cC --inserts -U freecodecamp salon > salon.sql`

**Comment by Ken-Leung-5** [comment]
I am sorry, seems I accidentally close this issue since I am a new user

**Comment by Ken-Leung-5** [comment]
Reopen

**Comment by moT01** [comment]
The test runs your script and enters these values at each prompt: `'BadInput', '1', '555-5555', 'Test', 'FakeTime'`. I just ran your script with those values and at the end, the script doesn't finish. I get prompted again for my phone number. The script needs to finish so the test can see the output. I think if you change the script so it does that, you will pass. Let me know if that works. I can look into rewording that user story so it's more clear on what happens.

**Comment by moT01** [comment]
Reopening, because I think that user story could use some clarification.

**Comment by hxko** [comment]
Had the same issue. 
Solved by not echoing the first argument of MAIN_MENU.

ex.
I Changed:
`MAIN_MENU "I could not find that service. What would you like today?"`

to:

```
echo -e "I could not find that service. What would you like today?"
MAIN_MENU
```

After that the tests passed. 
Happy coding 👾
