### ISSUE TITLE
Expressworks WHAT'S IN QUERY - Official solution does not work.

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [FreeCodeCamp/freecodecamp#456]
The official solution for Expressworks WHAT'S IN QUERY:

var express = require('express')
    var app = express()
    
    app.get('/search', function(req, res){
      var query = req.query
      res.send(query)
    })
    
    app.listen(process.argv[2])

Gives:

                 ACTUAL                                 EXPECTED                
───────────────────────────────────────────────────

   "{"                                 !=    "{\"results\":\"recent\",\"type\":\"quote\",\"page\":\"8\"}"
   "  \"type\": \"quote\","            !=                                       
   "  \"page\": \"8\","                !=                                       
   "  \"__proto__\": {}"               !=                                       
   "}"                                 !=         

It is obviously not expecting:    "  \"__proto__\": {}"

Manually building the object like so does work:

app.get('/search', function(req, res){
    var send = {};
    send.results = req.query.results;
    send.type = req.query.type;
    send.page = req.query.page;
    
    send = JSON.stringify(send);
    res.status(200).send(send);
});

**Comment by terakilobyte** [comment]
Please submit this as an issue against ExpressWorks.

**Comment by prashcr** [comment]
Yes, the expressworks solution is wrong.
However, there's a really simple fix.
`__proto__` is a *non-enumerable* property
There's your big hint

**Comment by MichaelLeeHobbs** [comment]
@prashcr Yes, I am aware and have solved the issue, but this needs to be addressed. I have submitted it here: https://github.com/reddock/fcc_express/issues/1
