### ISSUE TITLE
document object is not recognized in FCC in-browser editor

### ISSUE THREAD

**Issue by sabahang** [FreeCodeCamp/FreeCodeCamp#4560]
If you try to access any of the properties of  document object in FCC in-browser editor you will get a 'document not defined' error message. As a result you can't access any of the child functions listed here: https://developer.mozilla.org/en-US/docs/Web/API/Document
In my case I was trying to run 'document.createElement("div");' code when I ran into the issue

![fccbug](https://cloud.githubusercontent.com/assets/2657540/11276280/1c5fc826-8ea7-11e5-977a-2a3fe4211a85.JPG)

**Comment by SaintPeter** [comment]
While this is a very clever solution, it is not the solution we're looking for. You will need to manually replace the HTML entities with a `replace` command or similar.

I don't actually know why `document` is not available in our test environment, except to say that it is not used/required by any of our challenges. 

Thanks and happy coding!

**Comment by sabahang** [comment]
@SaintPeter don't you think aside from whether or not this is the wanted solution for this task `document` object should be accessible? If so the point of this bug report is simply to bring attention to that rather than reporting a bug with the coding task per se. I have checked whether 'document' is accessible in other in-browser environments like jsfiddle, Codepen or jsbin and you can pretty much access it in all of them. Nevertheless if you think this shouldn't be implemented I understand. Thanks for commenting

**Comment by ltegman** [comment]
@sabahang `document` is only available when there's a DOM. These challenges that don't have the iphone on the side don't have a DOM available to them, they are just javascript code. This is a common experience now that javascript can run in a lot more places than the browser. All of the services you mentioned don't run JS alone, they have a DOM component that the JS is running in and can modify.

**Comment by sabahang** [comment]
@ltegman makes sense! thanks for clarifying!
