### ISSUE TITLE
Waypoint: Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by mminev** [FreeCodeCamp/FreeCodeCamp#4561]
Challenge [Waypoint: Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript?solution=var%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2010)%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20Math.floor(Math.random()%20*%201000)%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var randomNumberBetween0and19 = Math.floor(Math.random() * 10);

function myFunction() {

  // Only change code below this line.

  return Math.floor(Math.random() * 1000);

  // Only change code above this line.
}

```

A requirement for this exercise is that I change the multiplication of Math.random() of 20 to 10 in order to get a number between 0 and 10. But that makes me change code above the comment "Only change code below this line".
On the other hand, in my actual solution, I multiplied the Math.random() function by a thousand. I guess the exercise was meant to actully make the user change that value there to 10, instead of inserting any random number. Or none at all... it also works, but the result is always 0 ;-)

Thanks for checking!

**Comment by SaintPeter** [comment]
Humm, looks like we're just matching `10` literally, not making sure there are no characters following.

I'm not sure why you persisted in changing code above the line.  There is not much we can do if you don't follow directions.  I suppose we could add a test to ensure that the 20 is still there.

**Comment by lbray** [comment]
The code they are looking for is pretty simple...should look something like this...

function myFunction(){
  return Math.floor(Math.random()*10);
}

**Comment by mminev** [comment]
Alright, then I guess I changed it because initially it would not take my solution. I did not multiply by 10 where I had to. Thus I thought I had to change the code above the comment.

**Comment by erictleung** [comment]
I looked back at my solution and ran it again and found it doesn't work any more! My answer is exactly the same as @lbray. 

I then checked the test code and found the second-listed test "You should be using <code>Math.random</code> to generate a random number." having the assert statement `editor.getValue().match(/Math.random/g).length > 1`. This checks that there is greater than one instance of `Math.random`. However, the solution to this challenge only requires one instance of `Math.random` (e.g. `Math.floor(Math.random()*10)`). 

So I think to fix this, the greater than signs should be changed to greater than or equal to signs.

**Comment by AdiDD** [comment]
Insert this inside the specified lines and it will work

 **var x = Math.floor(Math.random() * 10);
  return x;**


I also tried  returning **Math.floor(Math.random() * 10)** and for some reason it dosen't work.
So initialize a variable **x** with the function and return **x**.
It will work.

**Comment by ohmiler** [comment]
```

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  // Only change code below this line.
  
  return Math.floor(Math.random() * 10);
}

```

**Comment by sachdevadeepen** [comment]
var randomNumberBetween0and10 = Math.floor(Math.random() * 10);

function randomWholeNum() {
 randomNumberBetween0and10 = Math.floor(Math.random() * 10);

 
    
  
  return Math.floor(Math.random());
}

**Comment by sachdevadeepen** [comment]
`var randomNumberBetween0and10 = Math.floor(Math.random() * 10);

function randomWholeNum() {
 

  // Only change code below this line.
    randomNumberBetween0and10 = Math.floor(Math.random() * 10);
  
  return Math.floor(Math.random());
}
`

**Comment by ansenevans** [comment]
function myFunction() {

  // Only change code below this line.
  return Math.random();
  

  // Only change code above this line.
}
