### ISSUE TITLE
in here should exist <code></code> element

### ISSUE THREAD

**Issue by yuanhepeng** [freeCodeCamp/freeCodeCamp#45629]
## Affected page

[https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-17](url)
## Your code

```
`<code>sans-serif</code>
`
```

## Expected behavior

in here should exist <code></code> element:
`<code>sans-serif</code>
`
## Screenshots
![image](https://user-images.githubusercontent.com/39111057/161958758-2a0b4283-812f-4f41-8282-c9728c55da07.png)

## System

win11  Firefox
- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
 
## Additional context

I want to modify it myself，but I don't know how to deal with it. I don't know how to find him

**Comment by ojeytonwilliams** [comment]
Hi @yuanhepeng thanks for raising this issue, but there's nothing to fix here. The reason is that sans-serif is not being used as a programming term here, it is referring to the class of fonts.  Multiple different fonts, such as Arial and Helvetica, fall into this class.

**Comment by yuanhepeng** [comment]
Hi@[ojeytonwilliams](https://github.com/ojeytonwilliams)
Verdana similarly referring to the class of fonts, but please note picture, Verdana is surrounded <code>Verdana </code>
![image](https://user-images.githubusercontent.com/39111057/162108615-768787e8-6750-4876-b940-0b17dfb4d48e.png)
in here should keep consistent

**Comment by ojeytonwilliams** [comment]
Thanks, @yuanhepeng, that's a good point. I think Verdana should simply be plain text for consistency.

**Comment by ShaunSHamilton** [comment]
@ojeytonwilliams and @yuanhepeng The instruction to set the preferential font to `Verdana` is not a suggestion for a family of fonts. It is an instruction to use the code-word `Verdana` as the preferential font.

It should remain within a `code` element.

Specifically, we are talking about _family-names_ and _generic-names_ : https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#values

`Verdana` is not a _generic-name_ font.

**Comment by ojeytonwilliams** [comment]
It's a bit of grey area, to be honest, but I feel like this is not really code.  Reason being, it's just the name of specific font family called Verdana. It's not a keyword or part of any specific language, it just a string id that lets you get a `font-family` via a `@font-face` rule.

**Comment by ShaunSHamilton** [comment]
> It's a bit of grey area, to be honest, but I feel like this is not really code.

Am I missing something? The challenge expects Campers to use the code `Verdana`, if they put anything else, it will fail.

````markdown
You should set the first value of the `font-family` property to `Verdana`.

```js
const gs = (s) => new __helpers.CSSHelp(document).getStyle(s);
const style = gs('h1, h2') || gs('h2, h1');
assert.include(style?.fontFamily, 'Verdana');
```
````

**Comment by yuanhepeng** [comment]
Verdana and sans-serif both part of the actual  css code
![image](https://user-images.githubusercontent.com/39111057/162349111-faad1906-05fd-4797-9750-3491f06ef4d5.png)

**Comment by bbsmooth** [comment]
My two cents, for what it's worth. I think Verdana should remain marked up as code since the instructions are specifically telling the user to use Verdana for the initial font. I've found other courses that have the font name marked up as code in the instructions as well. And it just seems that in general, whenever the instructions tell the user exactly what value to add, the value is marked up as code. 

And I also think that sans-serif should not be marked up as code since it is referring to a family of fonts and the tests will accept five different fonts for the fallback, so we aren't telling the user specifically what to use here. I'm guessing any confusion stems from the fact that one of the acceptable fall back fonts is sans-serif itself. Perhaps we could reword this a little?

"..., and use another web-safe font in the sans-serif family as a fallback."

**Comment by yuanhepeng** [comment]
@[bbsmooth](https://github.com/bbsmooth)@[ShaunSHamilton](https://github.com/ShaunSHamilton)@[ojeytonwilliams](https://github.com/ojeytonwilliams)
Thank you all very much，I understand it，sans-serif is a  family, Verdana is a sans-serif family menber.

> "..., and use another web-safe font in the sans-serif family as a fallback."

I think [bbsmooth](https://github.com/bbsmooth) the suggestion is very good.
<br>
[https://www.freecodecamp.org/news/html-font-css-font-family-example-serif-and-sans-serif-characters/](url)
![image](https://user-images.githubusercontent.com/39111057/162354501-12e7cc43-7316-47e2-ba9a-0c6603677eed.png)

**Comment by ojeytonwilliams** [comment]
Let's go with @bbsmooth's wording, I think that should be clearer than what we have.

**Comment by yuanhepeng** [comment]
How should I further locate where the file is
![image](https://user-images.githubusercontent.com/39111057/162423004-a9110a5f-eebf-4c90-a1fc-113b9475cffb.png)

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/614206033d366c090ca7dd42.md is the file you need.

We're in the process of making it easier to search for individual steps, but for now you can search for the title (Step 17 in this case) within that folder. For instance

```
grep -r 'Step 17'
```

**Comment by yuanhepeng** [comment]
&nbsp;thank you



---Original---
From: "Oliver ***@***.***&gt;
Date: Fri, Apr 8, 2022 19:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [freeCodeCamp/freeCodeCamp] in here should exist <code&gt;</code&gt;element (Issue #45629)




 
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/614206033d366c090ca7dd42.md is the file you need.
 
We're in the process of making it easier to search for individual steps, but for now you can search for the title (Step 17 in this case) within that folder. For instance
 grep -r 'Step 17'
