### ISSUE TITLE
☔ Chinese - :s/subdomain/subpath/

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#45623]
This issue tracks the ongoing Chinese-specific platform migration from the subdomain to the subpath.

We request help auditing our codebases on the organization like `nginx-config`, `news`, etc., including this repo for reference to `chinese.freecodecamp.org`, `/chinese` or code snippets that are making/doing Chinese language-specific things.

Please comment or edit this issue description to add such locations. Once the auditing is complete, we will need further help swapping the code/text, which we will explain in a follow-up.

### Code Changes and Preparatory action items

- [x] Learn
	- [x] freeCodeCamp/freeCodeCamp#46202
	- [x] freeCodeCamp/freeCodeCamp#46203
	- [x] freeCodeCamp/freeCodeCamp#46204
	- [x] freeCodeCamp/freeCodeCamp#48448
	- [x] freeCodeCamp/freeCodeCamp#46222
- [x] News
	- [x] Frontend
		- [x] freeCodeCamp/freeCodeCamp#46197
		- [x] freeCodeCamp/news#299
	- [x] Ghost
		- [x] freeCodeCamp/freeCodeCamp#46201
		- [x] freeCodeCamp/infra#603
	- [ ] Serverless indexer
		- [ ] freeCodeCamp/serverless-indexer#97
- [x] Forum
	- [x] Refer google sheet shared by Miya and Mrugesh in the Staff shared drive.
	- [x] Create subforums for certification (area-specific) like other languages.
	- [x] Update the "welcome post" on the Chinese subforum.
	- [x] Update learn link to the forum to Chinese subforum on the main forum
	- [x] freeCodeCamp/freeCodeCamp#46200
- [x] NGINX
	- [x] freeCodeCamp/freeCodeCamp#46199

### Battleplan for cutover:

Mrugesh will create the detailed battle plan for the cutover once the actions items in the previous sections are ready. That is, PRs are reviewed and ready to be merged.

-- 
Based on: https://cs.github.com/?scope=org%3AfreeCodeCamp&scopeName=freeCodeCamp&q=chinese

**Comment by ieahleen** [comment]
nginx-config I found 4 files
 - https://github.com/freeCodeCamp/nginx-config/blob/main/sites-enabled/10-www.freecodecamp.org.conf
 - https://github.dev/freeCodeCamp/nginx-config/blob/main/sites-enabled/15-chinese.freecodecamp.org.conf
 - https://github.dev/freeCodeCamp/nginx-config/blob/main/sites-enabled/20-www.freecodecamp.dev.conf
 - https://github.dev/freeCodeCamp/nginx-config/blob/main/sites-enabled/30-chinese.freecodecamp.dev.conf

**Comment by nhcarrigan** [comment]
Within the client:

- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/create-language-redirect.ts (handles the logic for `chinese.freecodecamp.org` instead of `freecodecamp.org/chinese`.
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/utils/algolia-locale-setup.ts (points to chinese news)
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/utils/tags.tsx (injects specific tags for chinese)
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/gatsby-config.js (gatsby config has logic for english and chinese to not use language subpaths)

Some of the `i18n` files in the client have links which point to `chinese.freecodecamp.org`.

**Comment by ojeytonwilliams** [comment]
Tests and mocks for the files Naomi found:
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/__mocks__/gatsby.js 
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/create-language-redirect.test.ts
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/utils/tags.test.tsx

One challenge file:
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/chinese/02-javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions.md

Cors config:
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/config/cors-settings.js

Docs:

* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/devops.md
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/how-to-test-translations-locally.md
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/index.md

**Comment by Nirajn2311** [comment]
What about `chinese-traditional`? Are they getting a separate subpath or a different language code?

**Comment by raisedadead** [comment]
> What about `chinese-traditional`? Are they getting a separate subpath or a different language code?

They are already at the location where should be and are completely unrelated to this migration.
