### ISSUE TITLE
Minor discrepancy in the description and actual excercise

### ISSUE THREAD

**Issue by chautob0t** [FreeCodeCamp/FreeCodeCamp#4563]
Challenge [Waypoint: Add your JavaScript Slot Machine Slots](http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots?solution=) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.

Waypoint description says ->
Now that our slots will each generate random numbers, we need to check whether they've all returned the same number.

**If they have, we should notify our user that they've won and we should return null.**

null is a JavaScript data structure that means nothing.

The user wins when all the three numbers match. Let's create an if statement with multiple conditions in order to check whether all numbers are equal.

if(slotOne === slotTwo && slotTwo === slotThree){

  return null;

}

Also, we need to show the user that he has won the game when he gets the same number in all the slots.

If all three numbers match, we should also set the text "It's A Win" to the element with class logger.

*whereas* the actual requirement of the waypoint is the reverse- 

**"If all three of our random numbers are the same we should return that number. Otherwise we should return null."**

**Comment by ltegman** [comment]
Closing this because these challenges are being removed from the curriculum soon.

Thanks and happy coding!
