### ISSUE TITLE
Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by despinam** [FreeCodeCamp/FreeCodeCamp#4566]
Challenge [Waypoint: Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function myFunction() {

  // Only change code below this line.
 var randomNumberBetween0and9 = Math.floor(Math.random() * 10); 
  return Math.random();
  // Only change code above this line.
}

```

**Comment by SaintPeter** [comment]
No problem has been described.  Closing.  Feel free to re-open with a description of the issue, or go to the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for coding help.

Thanks and Happy Coding!

**Comment by mohannadsawalhi** [comment]
return randomNumberBetween0and9;

**Comment by JAndrewT** [comment]
@despinam  look at the question it should be randomWholeNumBetween
then the return should be for the randomWholeNumBetween

**Comment by Project360VRCam** [comment]
Should be like this :)
![screen shot 2017-03-21 at 14 39 59](https://cloud.githubusercontent.com/assets/23374748/24147744/58848756-0e44-11e7-9e21-b336cb59906a.png)

**Comment by texas2010** [comment]
@Project360VRCam 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by wangari** [comment]
return randomNumberBetween0and9

Or check Out this

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  // Only change code below this line.

  return ( Math.floor(Math.random()*10));
}
