### ISSUE TITLE
Profile page doesn't show certifications

### ISSUE THREAD

**Issue by Yash-Singh1** [freeCodeCamp/freeCodeCamp#45667]
## Affected page

`/[user]`

## To reproduce

1. Go to https://www.freecodecamp.org/Yash-Singh1
3. Scroll down to `freeCodeCamp Certifications`
4. Notice that even though I have the `JavaScript Algorithms and Data Structures Certification`, it says:

```
No certifications have been earned under the current curriculum
```

## Expected behavior

Certification appearing.

## Screenshots

![Screenshot from 2022-04-10 17-27-38](https://user-images.githubusercontent.com/53054099/162646752-de4e687f-9814-41eb-8b16-0c23790e7504.png)

## System

- Device: PC
- OS: Ubuntu
- Browser: chrome

**Comment by scissorsneedfoodtoo** [comment]
Hi @Yash-Singh1, thanks for your patience and for reporting this.

However, I don't think this is an issue. I can see your certification when I open your public profile:

![image](https://user-images.githubusercontent.com/2051070/162666716-e3a29125-6e9f-44f3-8ca6-b267062b6fb0.png)

If you still don't see your certification, then it may be an issue with your browser's cache. Could you clear your cache and cookies, and do a hard refresh of the page, then check your public profile?

**Comment by Yash-Singh1** [comment]
> Hi @Yash-Singh1, thanks for your patience and for reporting this.
> 
> 
> 
> However, I don't think this is an issue. I can see your certification when I open your public profile:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2051070/162666716-e3a29125-6e9f-44f3-8ca6-b267062b6fb0.png)
> 
> 
> 
> If you still don't see your certification, then it may be an issue with your browser's cache. Could you clear your cache and cookies, and do a hard refresh of the page, then check your public profile?

Oh yeah, sorry about the false alarm.
