### ISSUE TITLE
Ukrainian - translation error           

### ISSUE THREAD

**Issue by SergeyOcheretenko** [freeCodeCamp/freeCodeCamp#45661]
## Affected page

https://www.freecodecamp.org/ukrainian/learn/javascript-algorithms-and-data-structures/regular-expressions/positive-and-negative-lookahead

## To reproduce

In the Ukrainian translation (?=...) is repeated twice. In the Ukrainian translation in the paragraph about the negative lookahead should be (?!...), not (?=...).

## Recommended fix, suggestions

In the Ukrainian translation in the paragraph about the negative lookahead should be (?!...), not (?=...).

## Screenshots

Ebglish (all right):
![image](https://user-images.githubusercontent.com/71709401/162609228-9e291291-eff9-4f5a-a3e5-fa6e58d4b1e4.png)

Ukrainian (there is a problem):
![image](https://user-images.githubusercontent.com/71709401/162609264-98090d72-4c6b-4ef2-a451-d74fbc4398ed.png)

In English translation everything is correct, in Ukrainian it is repeated twice (?=...).

**Comment by ieahleen** [comment]
Thank you, if you can make the change to the string on crowdin, I can approve it and it will be changed in the repo tomorrow - this is the file crowdin: https://translate.freecodecamp.org/translate/690087755819f2f67b26dbee3be0eb53/22472/en-uk/132?filter=basic&value=0

Please help getting the Ukrainian curriculum to 100% translated :)

**Comment by SergeyOcheretenko** [comment]
Thank you for agreeing to look into this problem!
On Crowdin, I offered my changes to the line where I fixed the needed
problem. Username: SergeyOcheretenko.

[image: image.png]

вс, 10 апр. 2022 г. в 15:30, Ilenia ***@***.***>:

**Comment by ieahleen** [comment]
@SergeyOcheretenko Thank you! the file will be downloaded to github tomorrow with the authomatic pipeline.

We would welcome your help in bringing Ukrainian to 100% translated! If you haven't done so you can read our contributing guidelines at contribute.freecodecamp.org and join the chat server at https://chat.freecodecamp.org/home
