### ISSUE TITLE
Random Whole Number with JavaScript

### ISSUE THREAD

**Issue by despinam** [FreeCodeCamp/FreeCodeCamp#4567]
What have I done wrong? Can someone help me in order to continue?
Thank you in advance
My code:

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function myFunction() {

  // Only change code below this line.
 var randomNumberBetween0and9 = Math.floor(Math.random() * 10); 
  return Math.random();
  // Only change code above this line.
}

![math_random](https://cloud.githubusercontent.com/assets/15333740/11287465/6cf3bdf6-8f24-11e5-98d5-2c04126d3100.jpg)

**Comment by SaintPeter** [comment]
For coding help go to the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).  Please *do not* open another issue for this waypoint unless and until you have posted your problem there and been specifically told that there is a bug with this waypoint.

Closing as this is not a site problem.

Thanks and Happy Coding!
