### ISSUE TITLE
Remove instructions from boilerplates

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45676]
We recently finished moving the last of the instructions for cert projects from the boilerplates to /learn so they can be translated. See https://github.com/freeCodeCamp/freeCodeCamp/issues/43836. I think the boilerplates not listed in that issue already had their instructions removed. I'm thinking we should remove the instructions from the rest of those boilerplates. 

There's one line in the colab boilerplates that didn't get added to /learn...
```
Note: You are currently reading this using Google Colaboratory which is a cloud-hosted version
of Jupyter Notebook. This is a document containng both text cells for documentation and runnable
code cells. If you are unfamiliar with Jupyter Notebook, watch this 3-minute introduction before
starting this challenge: https://www.youtube.com/watch?v=inN8seMm7UI
```
It's at the top of some of the notebooks, we may want to keep that in those notebooks and possibly add it to the notebooks that don't have it - or possibly add it to /learn for all of the colab projects - or maybe just remove it from all of them, not sure.

Only the Jupyter/Colab boilerplates haven't been updated

**Comment by nhcarrigan** [comment]
I've made PRs to clean up the README files for the non-Jupyter projects.

**Comment by naomi-lgbt** [comment]
Will clean up the notebooks today - looks like the instructions have all been moved to learn
