### ISSUE TITLE
Suggestion: Suggested reading lists for curriculum topics

### ISSUE THREAD

**Issue by danmolloy** [freeCodeCamp/freeCodeCamp#45680]
## The Problem

I completed several of the FreeCodeCamp certifications last year, with little background in coding. Like all students, much of my learning was through reading external docs such as [javascript.info](https://javascript.info/) or the [React docs](https://reactjs.org/docs/getting-started.html). 

There were a few topics, such as Node.js, which I struggled with. I blame this almost entirely on struggling to find helpful external docs such as [nodejs.dev/learn](https://nodejs.dev/learn). Although I tried to find learning resources on Google and the forums on several occasions, it was several months before I found this page. Once I did find it, the topic was significantly more straightforward.

Finding concise, beginner-friendly docs was an ongoing issue while starting to learn web development and I believe this is an issue many students face.

## A Solution

In the curriculum pages, I propose there be a short list of _Suggested Reading_. For example, the list for Javascript Algorithms could include [javascript.info](https://javascript.info/) and [MDN Web Docs: Javascript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript). 

## Alternatives

Currently, as far as I can see, students find further resources via search engines and the forum. Both of these methods can be slightly troublesome as there is often concise official docs, which aren't immediately found for all topics.

**Comment by nhcarrigan** [comment]
I don't think this is the direction we want to go. Historically, we've avoided linking to external resources within the curriculum (with only a few exceptions), and recently made an effort to clean up the links and include relevant information directly within the course instructions.

**Comment by jeremylt** [comment]
Yeah, this sort of thing would be like an endorsement by fCC for those other resources, and I don't know that we want to open the can of worms of external resource vetting. Much simpler to keep recommending personal favorites on the forum and chat platforms.

**Comment by nhcarrigan** [comment]
Thanks for opening this issue!

Based on the comments above, we are going to go ahead and close this. If you feel there is more to discuss, you're welcome to request we reopen it and explore further.

Happy coding!
