### ISSUE TITLE
JavaScript Algorithms and Data Structures: Introducing Else Statements

### ISSUE THREAD

**Issue by lampenny** [freeCodeCamp/freeCodeCamp#45686]
## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/introducing-else-statements

## Your code

```
function testElse(val) {
  var result = "";
  // Only change code below this line

  if (val > 5) {
    result = "Bigger than 5";
  }

  if (val <= 5) {
    result = "5 or Smaller";
  }

  // Only change code above this line
  return result;
}

testElse(4);
```

## Expected behavior

No error message of ""You should not change the code above or below the specified comments." in console as the code above and below the line has not been changed.

## System

- Device: Laptop
- OS: iOs 11
- Browser: Chrome
- Version: 100.0.4896.88

## Additional context

The error is shown when the code above and below the lines has not been changed and will also throw the same error when code is changed within the above/below boundary. This happens even when Reset All Code is hit.

**Comment by ojeytonwilliams** [comment]
Hi @lampenny thanks for submitting this report.  The reason the tests are complaining is that they expect to see `let result = "";` above the first comment, not `var result = "";`

We changed this challenge about 6 months ago, so it's possible the old version (which used var) was saved in your browser.

> This happens even when Reset All Code is hit.

I couldn't reproduce this, when I reset the code I get:

```js
function testElse(val) {
  let result = "";
  // Only change code below this line

  if (val > 5) {
    result = "Bigger than 5";
  }

  if (val <= 5) {
    result = "5 or Smaller";
  }

  // Only change code above this line
  return result;
}

testElse(4);
```

Would you mind sharing the code you get after resetting?  If the reset isn't working, that's unexpected.

**Comment by nhcarrigan** [comment]
I am also unable to reproduce the Reset All Code bug.

**Comment by lampenny** [comment]
Hi all, thanks for your help!! @ojeytonwilliams was right in that it should be let and this was merely a bug saved in my browser. As of today, when I tried the lesson again, the Reset All Code now works as it should.

Thanks again all.
