### ISSUE TITLE
[RDB] Don't use strict equal on numbers

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45687]
[This test](https://github.com/freeCodeCamp/learn-periodic-table-database/blob/v1.0.2/.freeCodeCamp/test/1.1.test.js#L211) and surrounding tests are checking for strings. It should allow a string or number where applicable.

**Comment by archibongn1** [comment]
Hi @moT01 ! Are you open to contributions?

**Comment by moT01** [comment]
Go for it @archibongn1. There's [instructions how to work on them here](https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad). These are kind of tricky to work on - this one will be a little more difficult since it's changing the tests. Some of the other issues related to the Relational Database section are just grammar changes and typo fixes - those would be a little easier.

**Comment by archibongn1** [comment]
Thank you! If I can't figure it out I will go for the easier ones.

**Comment by moT01** [comment]
fixed via https://github.com/freeCodeCamp/learn-periodic-table-database/pull/9
