### ISSUE TITLE
Not a issue, a suggest :)

### ISSUE THREAD

**Issue by SherlockStoneed** [FreeCodeCamp/FreeCodeCamp#4569]
Hello FreeCodeCamp !

First, let's me say you that yout platform is the best !! I'm in love with it :heart_eyes: :heart: 
Secondly, I think it can be a good thinks that the hour of solution's submit is in the time zone of the user, and not under time zone of the server, which is the case today ^^

I hope my suggestion will help you, I will have to like to make the commit myself the same but unfortunately I am still a beginner and therefore did not yet have the skills to :sob: 

Have a nice night (in France is 01a.m. :sleepy: :smile: )
SherlockStoneed
http://www.freecodecamp.com/sherlockstoneed

**Comment by SaintPeter** [comment]
Time issues are . . . really sticky.  There is really no way to tell what time it is for any given user.  The good news is that all of the submission dates are consistent relative to one another, so if it took two days to do thing X, there will be two days between it.  

We are looking at displaying times in the user's time zone, as reported by their browser, for some displayed times.  Unsure when this will be live.
