### ISSUE TITLE
Fibonaci Word - fuzz for roundoff

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#45715]
## Affected page

https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/fibonacci-word

## Your code

```javascript
// Entrophy calculation for string with only 0 and 1
function entrophy(word) {
  const numZeros = word.split('').filter(e => e === '0').length;
  const numOnes  = word.length - numZeros;
  return - numZeros / word.length * Math.log2(numZeros / word.length)
         - numOnes  / word.length * Math.log2(numOnes  / word.length);
}

// Compute array of Fibonacci words
function fibWord(n) {
  const words = [
    { N: 1, Length: 1, Entropy: 0, Word: '1' },
    { N: 2, Length: 0, Entropy: 0, Word: '0' }
  ];

  for (let i = 3; i <= n; i++) {
    const word = words[i - 2].Word + words[i - 3].Word;
    words.push(
      { N: i, Length: word.length, Entrophy: entrophy(word), Word: word }
    );
  }

  return words;
}

// Testing
console.log(fibWord(5));
```

## Expected behavior

This solution is valid but fails due to floating point rounding. Our solution checking for this problem (and possibly others) should fuzz for floating point rounding. Anything within some sensible error tolerance like `50 * Number.EPSILON` should pass.

We might also consider replacing that solution in the markdown file with something far simpler and modern.

We probably also need to explain what 'entrophy' is in the challenge description.

**Comment by jeremylt** [comment]
We could also request entropy to N digits to make our life easier. Perhaps 8 digits would be enough?

While we're at it, we should add a second test case.

**Comment by ojeytonwilliams** [comment]
> We could also request entropy to N digits to make our life easier. Perhaps 8 digits would be enough?

Sounds good. It provides clarity for the users, too.
