### ISSUE TITLE
[UI Components] Disabled button should not have active styles

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#45712]
## To reproduce

The Button component in the UI component library is having active styles even when it is disabled.

Refer to: https://github.com/freeCodeCamp/freeCodeCamp/pull/45665#issuecomment-1101213249

## Expected behavior

Disabled Button should not have active styles.

## Screenshots

![clickable](https://user-images.githubusercontent.com/4591597/163780202-ea7f9c52-f33e-415a-aeb8-197385a2137b.gif)

## Useful resources

- Component library contributing guide: https://contribute.freecodecamp.org/#/how-to-work-on-the-component-library
- Button component code: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/ui-components/src/button/button.tsx

**Comment by aparna2071** [comment]
Can I please work on this issue?

**Comment by ShaunSHamilton** [comment]
@aparna2071 

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
