### ISSUE TITLE
test allows invalid syntax (<label/>) - beta RWD

### ISSUE THREAD

**Issue by lem0n4id** [freeCodeCamp/freeCodeCamp#45720]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-12

## Your code

```html
        <label/>
        <label/>
        <label/>
        <label/>
```

## Expected behavior

A **failing test** should be shown in the output box.

## Screenshots

![image](https://user-images.githubusercontent.com/61219881/163882369-404fa36a-15a5-4c9c-9878-39787aef8396.png)

## System

- Device: Laptop
- OS: Windows 10
- Browser: firefox
- Version: 99.0.1 (64-bit)

## Additional context

`<label>` tag is not self closing. 

The existing test needs to be modified or a new test needs to be added.

**Comment by lem0n4id** [comment]
Also, one more suggestion, update the **instructions** of the above step by adding the following text-

"Recall that `label` element is not self closing, unlike `<input />` tag."

**Comment by ShaunSHamilton** [comment]
@lem0n4id Thank you, for taking the time to open this.

However, the tests are not allowing that syntax - the browser is allowing that syntax. That is, if you look at the resultant HTML from `<label />`, you will see `<label></label>`.

As such, I am going to close this. We cannot reasonably test **against** every "incorrect" solution, when that solution produces the expected output.
