### ISSUE TITLE
[Python] Incorrect User Stories

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#45731]
A mismatch happened when we migrated the Python project user stories over to `/learn`

**Affected Page**

https://www.freecodecamp.org/learn/machine-learning-with-python/machine-learning-with-python-projects/rock-paper-scissors

_Pointed out in this forum post:_ https://forum.freecodecamp.org/t/mismatch-of-tasks-for-rock-paper-scissors-of-machine-learning-with-python/505463

---

The correct user stories need to be ported over from the relevant README.

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Sboonny** [comment]
hey, does changing [rock-paper-scissors.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/rock-paper-scissors.md) fix this issue. if so I can work in this

**Comment by ShaunSHamilton** [comment]
@Sboonny Yes, that should be the only file that needs to be changed.
