### ISSUE TITLE
Challenge [Waypoint: Sort Arrays with sort]

### ISSUE THREAD

**Issue by curioussavage** [FreeCodeCamp/FreeCodeCamp#4575]
I think the text for this exercise could improve. Its ok that it mentions that you can sort numerically or alphabetically but that it seems to imply that you can only sort by that. Its not that hard to tell what the function does, so after mentioning that it will default to sorting the array as unicode strings the bulk of the explanation could be about the callback. Maybe a simplified version of the explanation in bullet points [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

Something like:

>The callback takes 2 elements as parameters and compares the first in relation to the second. If the callback returns a number below 0 the first element is sorted to the left of the second. If a number greater than zero is returned the first element is sorted to the right of the second. 0 means their positions are left the same.

Not much of a writer so that is about the best I can do. Opinions? I can make a pr and edit according to feedback if thats cool.

**Comment by SaintPeter** [comment]
This PR is pending https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4531 with pretty much exactly what you suggest.  We are waiting on some minor edits before we accept it.  Please review that content and make your comments there.

**Comment by curioussavage** [comment]
oops, didn't find that when i searched. thanks
