### ISSUE TITLE
Feature request to add option to auto complete.

### ISSUE THREAD

**Issue by AdityaVarmaUddaraju** [freeCodeCamp/freeCodeCamp#45757]
## Is your feature request related to a problem? Please describe.

It is very difficult to type entire variable or function names when I try to complete small exercises
## Describe the solution you'd like

It would be lot helpful if there is an option to enable auto completion of variable or function names to complete the programming task

**Comment by jeremylt** [comment]
I agree that auto complete is useful for professional development environments, but auto complete has been intentionally disabled since FreeCodeCamp is a learning environment.

**Comment by nhcarrigan** [comment]
As Jeremy mentioned, this is a feature which is intentionally turned off. Writing the code from scratch can help solidify the concepts.

Thank you for opening this issue! At this time, we're going to go ahead and close it. If you feel additional discussion is needed, you are welcome to request we re-open it with your reasoning.
