### ISSUE TITLE
Update example HTML to be valid HTML

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45765]
The example code in the challenge [Define the Head and Body of an HTML Document](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/define-the-head-and-body-of-an-html-document) is not valid. The `<meta>` element is empty and the `<head>` is missing the `<title>` element. I would suggest updating the HTML so it validates.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Example title</title>
  </head>
  <body>
  </body>
</html>
```

This follows the basic example given on MDN for the [Anatomy of an HTML document](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics#anatomy_of_an_html_document).

I know this is a very minor thing and won't stay around after the beta version becomes the standard one but it's easy to update and I don't see why we wouldn't. I have tagged it for first-timers as this seems like a good first PR.

**Comment by Kas1680** [comment]
Working on it
