### ISSUE TITLE
Concatenating Strings with Plus Operator issue

### ISSUE THREAD

**Issue by tenadopt** [freeCodeCamp/freeCodeCamp#45771]
## Affected page

[]
(https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator)

## Your code

const myStr = "This is the start. " + "This is the end"; // Change this line
```




```

## Expected behavior

I expected that myStr has a value of the string
## Screenshots
<img width="1265" alt="Screenshot 2022-04-25 at 15 24 14" src="https://user-images.githubusercontent.com/46803834/165088376-fe5c4344-4aa4-4043-8ef5-3a6369248652.png">

## System

- Device: [e.g. iPhone6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.4]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Hello there,

This appears to be a request for help - not an issue. You have a typo in your code.

Please use the `Ask for Help` button on the challenge page to open a post on the [forum](https://forum.freecodecamp.org/) if you need further help.
