### ISSUE TITLE
https://www.freecodecamp.org/news/exploratory-data-analysis-in-go-with-gota,   `go get`  is no longer supported outside a module  it shout use `go install`

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#45797]
## Affected page
https://www.freecodecamp.org/news/exploratory-data-analysis-in-go-with-gota/

## To reproduce
```shell
go get github.com/oschwald/geoip2-golang
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

```
it should fix to `go install github.com/go-gota/gota@latest`

## Screenshots
![image](https://user-images.githubusercontent.com/6524977/165787768-aa503740-4d11-44b2-9fc4-1781427756ea.png)
![image](https://user-images.githubusercontent.com/6524977/165787817-309bc36b-0917-467e-a934-4d5e5e151192.png)
![image](https://user-images.githubusercontent.com/6524977/165787850-05d8f034-2dca-4681-b2d9-ee87088a20d6.png)

**Comment by scissorsneedfoodtoo** [comment]
Hi @luojiyin1987, thank you for opening this issue.

I did some testing locally and was able to reproduce the error with the `go get` command you pointed out above. Unfortunately it doesn't seem like `go install github.com/go-gota/gota@latest` works with that library.

I reached out to the author about this, and will work with them to update this article. We'll close this issue once a new version of the article with updated instructions is live.

**Comment by luojiyin1987** [comment]
@scissorsneedfoodtoo     
in code write
```go
import (
	"fmt"
	"github.com/go-gota/gota/dataframe"
	"strings"
)
```
soon,   int   Terminal run \
```shell
go mod tidy
```

```shell
[luo@T430s learnGolang]$ go mod tidy              
go: finding module for package github.com/go-gota/gota/dataframe
go: found github.com/go-gota/gota/dataframe in github.com/go-gota/gota v0.12.0
go: downloading golang.org/x/net v0.0.0-20210423184538-5f58ad60dda6
go: downloading gonum.org/v1/gonum v0.9.1
go: downloading golang.org/x/exp v0.0.0-20191002040644-a1355ae1e2c3
go: downloading gonum.org/v1/netlib v0.0.0-20190313105609-8cb42192e0e0
```
it will auto deal with golang package.

The golang code  in the  article can not run  directly， it  need change code, it is not firend for beginner。
golang is not javascript.

**Comment by scissorsneedfoodtoo** [comment]
@luojiyin1987, awesome, thank you for those steps. I'll give them a shot and see if I can get them working on my end.

Also, I'm still waiting to hear back from the author. When I get a response, I'll send your steps over and see what they think.

**Comment by ieahleen** [comment]
@scissorsneedfoodtoo any updates on this?

**Comment by scissorsneedfoodtoo** [comment]
@ieahleen, no, I haven't heard back from the author about this article yet, and haven't had time to dig into Go and the packages myself yet.

It's on the list of things to do, but if you'd like to take a crack at it, please feel free.

**Comment by scissorsneedfoodtoo** [comment]
Thanks again for your patience and for reporting this @luojiyin1987. Also, thanks for your helpful suggestions on installing the Gota package.

I spent some time over the last couple of days updating this article and the code used throughout. Now it should be much easier for readers to install Gota and follow along locally.

Will close this for now. Please feel free to reopen this issue and @ mention me if there are any other issues with this article.
