### ISSUE TITLE
No preview for Javascript course

### ISSUE THREAD

**Issue by chibuikes** [freeCodeCamp/freeCodeCamp#45800]
## Affected page  
The  javascript course doesn't have a preview/console for me to run my code on. For example when l type console.log(56) on code editor , there is no page( preview/console) embedded on the website for  me to see the 56 as the result.

## To reproduce

1. Go to '.freecodecamp website'
2. Click on ' Javascript and data structures..'
3. Type  any javascript code snippet eg console.log(56)....'
4. See error= no preview page

## Expected behavior
There is usually a page beside 'test' where l will see 56

## System

- Device: Redimi 9A phone
- Android
- Browser: chrome
- Version: [e.g. 22]

**Comment by nhcarrigan** [comment]
To confirm, you are not able to see the test tab or contents?

![SmartSelect_20220428-125225_Chrome](https://user-images.githubusercontent.com/63889819/165834687-f8c867a7-c678-4f75-ad7e-8af587edee22.jpg)

**Comment by chibuikes** [comment]
Ooh, there was never a problem . I didn't know that the results show in the
test tab. Thank you. Problem solved: more like there was never problem.
Sorry for the disturbance.

**Comment by ojeytonwilliams** [comment]
No problem, @chibuikes. Thanks for confirming.
