### ISSUE TITLE
No preview/ console to run my JS code snippet

### ISSUE THREAD

**Issue by chibuikes** [freeCodeCamp/freeCodeCamp#45801]
The  javascript course doesn't have a preview/console for me to run my code on. For example when l type console.log(56) on code editor , there is no page( preview/console) embedded on the website for  me to see the 56 as the result.

**Comment by nhcarrigan** [comment]
Could you share a screenshot of your page?

**Comment by ShaunSHamilton** [comment]
Hello there,

I am closing this issue in favour of the more detailed issue you first opened: https://github.com/freeCodeCamp/freeCodeCamp/issues/45800

**Comment by chibuikes** [comment]
Ooh, there was never a problem . I didn't know that the results show in the
test tab. Thank you. Problem solved: more like there was never problem.
Sorry for the disturbance.
