### ISSUE TITLE
Failure in CatPlotTestCase for Medical Data Visualizer in Data Analysis with Python

### ISSUE THREAD

**Issue by iliyabu** [freeCodeCamp/freeCodeCamp#45821]
## Affected page

[Medical Data Visualizer](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer)

## My code

```
def draw_cat_plot():
    # Create DataFrame for cat plot using `pd.melt`
    # using just the values from 'cholesterol', 'gluc', 'smoke', 'alco', 'active', and 'overweight'.
    df_cat = pd.melt(df, value_vars=['active', 'alco', 'cholesterol', 'gluc', 'overweight', 'smoke'],
                     id_vars=['cardio'])

    # Group and reformat the data to split it by 'cardio'.
    # Show the counts of each feature. You will have to rename one of the columns for the catplot to work correctly.

    # ...

    # Draw the catplot with 'sns.catplot()'
    fig = sns.catplot(data=df_cat, kind='count', x='variable', hue='value', col='cardio')
    fig.set_ylabels('total')

    # Do not modify the next two lines
    fig.savefig('catplot.png')
    return fig
```

## Expected behavior

Pass ```CatPlotTestCase``` without any issues.

## Actual behavior

```test_line_plot_labels``` fails with error:
```
    def test_line_plot_labels(self):
>       actual = self.ax.get_xlabel()
E       AttributeError: 'numpy.ndarray' object has no attribute 'get_xlabel'
```

```test_bar_plot_number_of_bars``` fails with error:
```
    def test_bar_plot_number_of_bars(self):
>       actual = len([rect for rect in self.ax.get_children() if isinstance(rect, mpl.patches.Rectangle)])
E       AttributeError: 'numpy.ndarray' object has no attribute 'get_children'
```

## System

- Device: Laptop
- OS: Ubuntu 18.04.6 LTS
- Python: 3.10.4
- matplotlib: 3.5.1
- numpy: 1.22.2
- pandas: 1.4.1
- scipy: 1.8.0
- seaborn: 0.11.2

## Additional context

```catplot``` is a figure-level interface, not an axes-level interface. When ```fig.axes``` is printed, it outputs:
```
[[<AxesSubplot:title={'center':'cardio = 0'}, xlabel='variable', ylabel='total'>
  <AxesSubplot:title={'center':'cardio = 1'}, xlabel='variable'>]]
```
Changing in ```test_module.py```:
```
class CatPlotTestCase(unittest.TestCase):
    def setUp(self):
        self.fig = medical_data_visualizer.draw_cat_plot()
        self.ax = self.fig.axes[0]
```
to
```
class CatPlotTestCase(unittest.TestCase):
    def setUp(self):
        self.fig = medical_data_visualizer.draw_cat_plot()
        self.ax = self.fig.axes[0][0]
```
allows for the test to pass successfully.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
