### ISSUE TITLE
Waypoint: Override Class Declarations by Styling ID Attributes (Not passing test)

### ISSUE THREAD

**Issue by floydhiebert** [FreeCodeCamp/FreeCodeCamp#4583]
Code works and turns color to orange, but the test doesn't pass: see code below.
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }

  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
  .orange-text {
    color: orange;
 }  
</style>
<h1 class="pink-text blue-text orange-text">Hello World!</h1>

**Comment by bugron** [comment]
@floydhiebert thanks for posting this issue!
Actually your code is incorrect. Challenge wants you to add an **ID** of `orange-text` but you've added it as a c **class**. See the example in the description.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
