### ISSUE TITLE
Bug - The code returns the correct values but the #FreeCodeCamp website wouldn't approve it!

### ISSUE THREAD

**Issue by shayanahmed1993** [FreeCodeCamp/FreeCodeCamp#4584]
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays?solution=function%20largestOfFour(arr)%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20%0A%20%20var%20aec%2Ci%3B%0A%20%20var%20largest%20%3D%20Array()%3B%0A%20%20largest%5Baec%5D%20%3D%200%3B%0A%20%20%0A%20%20%0A%20%20for(aec%20%3D%200%3B%20aec%20%3C%20arr.length%3B%20aec%2B%2B)%20%7B%20%20%0A%20%20%20%20%20%20largest%5Baec%5D%20%3D%200%3B%0A%20%20%20%20%20%20for(i%20%3D%200%3B%20i%3C4%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if%20(arr%5Baec%5D%5Bi%5D%20%3E%20largest%5Baec%5D)%20%7B%0A%20%20%20%20%20%20%20%20%20%20largest%5Baec%5D%20%3D%20arr%5Baec%5D%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20largest%5Baec%5D%20%3D%20largest%5Baec%5D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%7D%0A%20%20%20%20return%20largest%3B%0A%20%20%0A%20%20%2F*%0A%20%20for%20(aec%20%3D%200%3B%20i%3Carr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%0A%20%20%20%20for%20(i%20%3D%200%3B%20i%20%3C%204%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if%20(arr%5Baec%5D%5Bi%5D%20%3E%20largest%5Baec%5D)%20%7B%0A%20%20%20%20%20%20largest%5Baec%5D%20%3D%20arr%5Baec%5D%5Bi%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20largest%5Baec%5D%20%3D%20largest%5Baec%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20*%2F%0A%20%20%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function largestOfFour(arr) {
  // You can do this!
  
  var aec,i;
  var largest = Array();
  largest[aec] = 0;
  
  
  for(aec = 0; aec < arr.length; aec++) {  
      largest[aec] = 0;
      for(i = 0; i<4; i++) {
        if (arr[aec][i] > largest[aec]) {
          largest[aec] = arr[aec][i];
        }
    
        else {
          largest[aec] = largest[aec];
        }
      }
    
   }
    return largest;
  
  /*
  for (aec = 0; i<arr.length; i++) {
    
    for (i = 0; i < 4; i++) {
      
      if (arr[aec][i] > largest[aec]) {
      largest[aec] = arr[aec][i];
      }
      
      else {
        largest[aec] = largest[aec];
      }
      
    }
    
    
  }
  
  */
  
}

largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]);

```

**Comment by ltegman** [comment]
If you console.log the result of your code you'll see that you are returning an array that actually looks like: `[27, 5, 39, 1001, undefined: 0]`. This undefined property is causing it to not match the required answer. Remove `largest[aec] = 0;` at the top of your solution and you won't have this problem anymore.

In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) and [Bonfire Help Chat](https://gitter.im/FreeCodeCamp/HelpBonfires) before filing a bug.

Thanks and happy coding!
