### ISSUE TITLE
Challenge (Adjust the Tone of a Color): Use computed styles for test or fix regex

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45859]
Instead of using a regex maybe we should just check the computed styles?

```
background-color: hsl(180, 80%, 25%);

// $0 is the nav element
getComputedStyle($0).backgroundColor

'rgb(13, 115, 115)'
```

I realize doing so will technically allow users to pass the test without using the `hsl()` function, but I doubt people will convert the HSL value to hex or RGB and submit that.

Or, we can trim the code of whitespace and/or allow for spaces in the regex.

---

Forum thread: https://forum.freecodecamp.org/t/about-your-answer-checking-algorithm/507093

Challenge: https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color

Test: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color.md

**Comment by ShaunSHamilton** [comment]
Well, we already have a helper specifically for this case: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/utils/css-help.ts#L47

https://github.com/freeCodeCamp/freeCodeCamp/blob/d19a943c289e4550df74677ace6c3e738deb477c/client/src/utils/css-help.test.ts#L27-L29

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
