### ISSUE TITLE
Navbar jobs issue

### ISSUE THREAD

**Issue by HermanFassett** [FreeCodeCamp/FreeCodeCamp#4585]
When on jobs, there is an extra square item linking to jobs again (showing mouse hover):
![](http://i.imgur.com/LnKGcJC.png)
This leads to unforgivable sizing issues:
![](http://i.imgur.com/pUSymtF.png)

**Comment by ltegman** [comment]
Thanks for the report! We have a PR open (#4579) that will close this whenever it is merged.
