### ISSUE TITLE
tips is wrong at  page   https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables    

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#45853]
## Affected page
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables

## Screenshots
![image](https://user-images.githubusercontent.com/6524977/166492657-e21f4ee7-c53e-415b-804a-0c55bf0ce907.png)
but 
![image](https://user-images.githubusercontent.com/6524977/166492750-307043ff-b3ef-4ef2-be21-2f9e243848be.png)

first  it say  `Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.`
but,   following tips  is Conflicts.  Beginners don't know  which is right.

**Comment by nhcarrigan** [comment]
I don't see anything incorrect here.

The instructions ask you to initialise the three variables with specific values. Initialising `a` with `5` would be `var a = 5;`.

The tests state that `a` should be defined and *evaluated* to have the value of `6`. In the section of code the camper should not change, `a` is reassigned with `a = a + 1`. If the camper has initialised `a` to be `5`, then the final evaluated value will indeed be `6`.

**Comment by moT01** [comment]
I don't really see anything wrong here either - perhaps it's a little confusing. Do you have any suggestions of what you would like to see @luojiyin1987?

Maybe `a should be defined so that its end value is 6`

**Comment by nhcarrigan** [comment]
`a should be defined and have a final value of 6`?

**Comment by moT01** [comment]
I think that's probably a slight improvement, so I would be fine with that @nhcarrigan. Not sure it's needed, but I wouldn't object.

**Comment by nhcarrigan** [comment]
I'm pretty sure I've seen confusion with this challenge on the forum before, so it probably wouldn't hurt. I'll open this up for first timers.

**Comment by luojiyin1987** [comment]
`a should be defined and evaluated to have the value of 6`     I will wirte `var a = 6`

`b should be defined and evaluated to have the value of 15.`    I will wirte `var b=15`

It will get me a misinformation.

After I see  [test case](https://github.com/cmccormack/freeCodeCamp-1/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables.english.md),   I know how to write.

@nhcarrigan   @moT01

**Comment by MdSujan99** [comment]
I think the tip about variable c that says 

> ## Affected page
> https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables
> 
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/6524977/166492657-e21f4ee7-c53e-415b-804a-0c55bf0ce907.png) but ![image](https://user-images.githubusercontent.com/6524977/166492750-307043ff-b3ef-4ef2-be21-2f9e243848be.png)
> 
> first it say `Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.` but, following tips is Conflicts. Beginners don't know which is right.
> 
> ## Additional context

**Comment by MdSujan99** [comment]
> ## Affected page
> https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables
> 
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/6524977/166492657-e21f4ee7-c53e-415b-804a-0c55bf0ce907.png) but ![image](https://user-images.githubusercontent.com/6524977/166492750-307043ff-b3ef-4ef2-be21-2f9e243848be.png)
> 
> first it say `Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.` but, following tips is Conflicts. Beginners don't know which is right.
> 
> ## Additional context

I think the tip about variable c that says
"c should not contain undefined and should have a value of the string I am a String!"
it should also contain the term "should be evaluated to have the" replacing "should have a value of the"
that way the beginner coder would find the evaluated keyword striking and they might start thinking about the difference between "evaluated" and "initialised"
