### ISSUE TITLE
Add illustration to explain Margin vs. Padding

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4586]
Challenge [Waypoint: Adjusting the Padding of an Element](http://www.freecodecamp.com/challenges/waypoint-adjusting-the-padding-of-an-element

This waypoint has a lot of talky talky about padding and margin, but what it really needs is an image of the CSS box model, like this:
![image](https://cloud.githubusercontent.com/assets/553494/11308172/81455588-8f71-11e5-86a0-bbec3973d9cf.png)

Good explanation here
http://www.w3schools.com/css/css_boxmodel.asp

It would probably make sense to make a smaller image and refer to/update it over the next few waypoints as they talk about each aspect of margin/padding, etc.  Maybe highlight each element as we talk about it?

Possibly add a new waypoint that talks about the box model in general first?  Like a step challenge?

Thanks @rahulshinde235 for the question.

**Comment by Darksmurf** [comment]
We could add that image in a waypoint and then link to good resources. Possibly, insert the one shown in the chrome debugger(I think that one is clearer).

**Comment by theflametrooper** [comment]
What's the status on this @SaintPeter? If we can decide on an image I can submit a pr with the image and relevant code.

**Comment by SaintPeter** [comment]
I believe we have implemented this with actual CSS.  We had some debate about the value of that implementation, but I think this can actually be closed . . . which I will do now.
