### ISSUE TITLE
crowdin segmentation issue

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#45897]
- [ ] The file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc17d3bf86c76b9248c6eb4.md

The sentence 
> Your p element's text should be `Click here to view more cat photos.` You have either omitted the text or have a typo.

is not separated in two sentences in Crowdin, as the dot is inside the backticks. I know the dot inside quotes is best practice in American English, but in this case the quotes are not visible, and just for formatting. Plus the test
> `assert(extraSpacesRemoved.match(/click here to view more cat photos\.?$/i));`

marks the period as optional.
Maybe the period can be put outside the quotes so that it can be segmented correctly on crowdin?

Other cases:

- [ ] file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc23991f86c76b9248c6eb8.md

sentence:
> The text of the p element should be `Click here to view more cat photos.` Do not change the text, spacing, or punctuation of the p element.

- [ ] file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md

sentence:
> After nesting the anchor (a) element, the only p element content visible in the browser should be `Click here to view more cat photos.` Double check the text, spacing, or punctuation of both the p and nested anchor element.

- [ ] file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfb6250eacea3f48c6300b2.md

sentence:
> The new image should have an alt value of `A slice of lasagna on a plate.` Make sure the alt attribute's value is surrounded with quotation marks.

- [ ] file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5efae16e3cbd2bbdab94e334.md

sentence:
> The <code>figcaption</code> element should have the text <code>Cats hate other cats.</code> You have omitted a word or have a typo.

**Comment by Dario-DC** [comment]
file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfb6a35eacea3f48c6300b4.md
sentence:
> Your <code>figcaption</code> element's text should be <code>Cats love lasagna.</code> You have either omitted the text or have a typo.

**Comment by moT01** [comment]
That's not bad. It may look a little goofy:
> Your `p` element's text should be `Click here to view more cat photos.`. You have either omitted the text or have a typo.

It looks good enough I guess. An alternative could be to restructure the sentence so that text is in the middle. Maybe something like this:
> `Click here to view more cat photos.` should be the text of your `p` element. You have either omitted the text or have a typo.

I'm fine with either of those approaches.

**Comment by ieahleen** [comment]
Other possibility altogether, I find a regex that makes the correct segnmentation on these directly from crowdin
