### ISSUE TITLE
Campfire Mode Volume Slider

### ISSUE THREAD

**Issue by DemonSlayer112** [freeCodeCamp/freeCodeCamp#45894]
### Is your feature request related to a problem? Please describe.

I like the campfire mode's idea, however it would be nice to control the volume of it instead of turning my main speaker down.

### Describe the solution you'd like

For volume under the campfire settings, or even in the top right menu(so we can control anywhere on site)

### Describe alternatives you've considered

A volume slider in the menu would allow for easier, quicker control of the volume.

### Additional context

I'm sorry about the duplication in the solution and alternative, its a simple feature but they were required to fill.

**Comment by raisedadead** [comment]
Sounds like a good idea. Would you be interested in helping us build it out? We will be happy to guide you through it. If not, that's OK - let us know, and we will open this up for contribution.

Happy coding.

**Comment by benjamrio** [comment]
Hi! I am a new FreeCodeCamp contributor and I would be happy to help design/implement this. 

Hit me up if I can help.

**Comment by raisedadead** [comment]
Thanks, @benjamrio. I would give @DemonSlayer112 some time to respond; stay tuned.

**Comment by DemonSlayer112** [comment]
Im afraid im more ideas then functionality right now, though im sure you guys would be able to find a nice fit that would match the site's layout :)
Sorry for the waited response

**Comment by raisedadead** [comment]
No worries @DemonSlayer112 thanks for getting back to us! Please feel free to share ideas and feedback, those are really valuable to us.

@benjamrio if you are around and interested we are opening this for contributions.

**Comment by benjamrio** [comment]
Hi @raisedadead ! Yes I am still interested in helping building this. I am super excited to work on a component, yet it might take me sometimes getting everything right. Fortunately the contributing guide helps a lot.

**Comment by raisedadead** [comment]
Awesome - there is no rush, take all the time you need to build it. Also you can reach out to us on the forum or the contributor's chat if you find yourself stuck.

**Comment by benjamrio** [comment]
Hi @raditotev . Thank you very much for offering your help. I will look a bit on my side to see what I can figure out alone and will reach out to you.
