### ISSUE TITLE
Ethical Issues of having people write an html entities encoder

### ISSUE THREAD

**Issue by PeregrinePDX** [FreeCodeCamp/FreeCodeCamp#4590]
I think that there are some ethical issues with this Bonfire. HTML entity encoding is a well solved problem with tried and tested code. The consequences of getting your HTML entity encoding wrong can be very dangerous for your applications. I think at the very least there should be a note saying that in production you really should use a tested library instead of your own hand written entity encoder.

Challenge [Bonfire: Convert HTML Entities](http://www.freecodecamp.com/challenges/bonfire-convert-html-entities) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(str) {
  // &colon;&rpar;
  var escChars = /[&<>\"\']/;
  var splitStr = str.split('');
  for(i=0, len = splitStr.length;i < len; i++) {
    if (splitStr[i].match(escChars)) {
      switch (splitStr[i]) {
        case '&':
          splitStr[i] = '&amp;';
          break;
        case '<':
          splitStr[i] = '&lt;';
          break;
        case '>':
          splitStr[i] = '&gt;';
          break;
        case '"':
          splitStr[i] = '&quot;';
          break;
        case "'":
          splitStr[i] = '&apos;';
          break;
      }
    }
  }
  str = splitStr.join('');
  return str;
}

convert("Dolce & Gabbana");

```

**Comment by ltegman** [comment]
Having people solve already solved problems in a way that isn't bullet-proof is pretty much standard fair for a programming curriculum. I think it goes without saying that code you write as part of a learning process shouldn't be put into prod without seriously refactoring and testing beyond what you did originally.

If we were going to warn people about not using bonfire code in prod and to not reinvent the wheel we'd need to be doing that on every challenge. However, for the purposes of learning these challenges work perfectly well.

Thanks and happy coding!
