### ISSUE TITLE
Problem in the code box

### ISSUE THREAD

**Issue by djackcu** [FreeCodeCamp/FreeCodeCamp#4591]
Challenge [http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery](http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/13282715/11315796/5e27e6b8-8ff0-11e5-94ca-3153906b9f37.png)

**Comment by ltegman** [comment]
I am not able to reproduce this error. Please try refreshing your browser, pressing the reset button, and if neither of those work you can try disabling browser extensions.

Thanks and happy coding!
