### ISSUE TITLE
Grammar Error in "How Recursion Works" Lesson

### ISSUE THREAD

**Issue by clearfeather** [freeCodeCamp/freeCodeCamp#45917]
### Describe the Issue

Grammar issue from this lesson page.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/replace-loops-using-recursion# (Watch a Video link)

### Your code

```
N/A
```

### Expected behavior

"This similar to a stack of books."

should be

"This is similar to a stack of books."

### Screenshots

<img width="796" alt="Screen Shot 2022-05-11 at 8 58 25 AM" src="https://user-images.githubusercontent.com/22827897/167868063-1406e278-8168-4fa4-acd1-dc727d6194e3.png">

### System

- Device: Mac Studio
- OS: Mac Monterey 12.3.1
- Browser: Chrome
- Version: Version 101.0.4951.54

**Comment by gourcool** [comment]
The above mention issue doesn't exist.

**Comment by Sembauke** [comment]
@gourcool It actually does exist. When you click the `Get Help` button and click the video option it redirects to an article of one of our authors.

**Comment by nhcarrigan** [comment]
Thank you for reporting this! We've updated the text in the article, and the fix will be live in the next build.
