### ISSUE TITLE
Specify How Fonts Should Degrade - Expects "Monospace", doesn't call for it

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4592]
Challenge [Waypoint: Specify How Fonts Should Degrade](http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade) has an issue.

The purpose of this waypoint is to demonstrate what happens when a specified font is not available.  It talks about degrading to `Monospace`.  

The problem is, the only thing the instructions tell you to do is comment out the link to Lobster.

The code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster; /* Should Monospace be added here? */
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>
```

One of two things needs to happen:
1) Add `Monospace` to h2's font-family
2) Explicitly tell the user to add it themselves.

**Comment by rahulshinde235** [comment]
Yup add Monospace to h2 font family so that when user comments out the link to lobster then he can see that Monospace becomes active
