### ISSUE TITLE
New RWD editor should support a mix of style element and stylesheet

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45937]
### Describe the Issue

I assume this is a known issue?

### Affected Page

All Certification Projects

### Your code

This example shows a red background in the preview when it should be black.

index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="styles.css" />
    <title>Document</title>
    <style>
      body {
        background-color: black;
      }
    </style>
  </head>
  <body>
    <h1>test</h1>
  </body>
</html>
```

styles,css

```
body {
  background: red;
}
```

### Expected behavior

The preview should be black with the example code and the tests should not fail when using a combination of a style element and a stylesheet.

### System

- OS: [Windows 10]
- Browser: [Chrome]

### Additional context

---

Unrelated note, I'm really not digging this new form for issues.

**Comment by nhcarrigan** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/63889819/168185297-3151a739-2f2c-4bfe-8c73-b22a6f70ff5f.png">

It looks like the build process for the preview is appending the CSS as a style element at the end of the body.

**Comment by lasjorg** [comment]
I assume the style element styles and stylesheet styles can be concatenated in the correct order before applying them.

The main issue is the tests break if you combine the two. I saw one camper failing some tests because they had set some styles on the body in the style element.

forum: https://forum.freecodecamp.org/t/my-code-is-not-working-on-the-new-editor-please-help-me/508379

challenge: https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

index.html

```
<link href="styles.css" />
<style>
  body {
    background-color: black;
    color: cyan;
    font-family: calibri;
  }
</style>
<main id="main">
  <h1 id="title"> Vegeta- the true underdog</h1>
  <figure id="img-div">
    <a id="tribute-link" target="_blank" href="https://youtu.be/rep3tz3XpyQ">
      <img id="image" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSg63I6oiwQTTr2_kHyOjkfxrbMMTBCjU2jQ&usqp=CAU" alt="picture of vegeta" width="100%" height="auto">
    </a>
    <figcaption id="img-caption"> vegeta is a picture which makes you stronger when you feel week. </figcaption>
  </figure>
  <p id="tribute-info">
    <b>Vegeta Tributes</b>
  <ul>
    <li> reselience </li>
    <li> feerlesness</li>
    <li> persistence</li>
  </ul>
</main>
```

styles.css

```
#img-caption {
  width: 400px;
}

#image {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 0 auto;  
}
```

This code will fail the image tests. If you remove the style element it passes the tests for the image.

**Comment by ojeytonwilliams** [comment]
Thanks for the detailed write up @lasjorg.  

I'm looking into this now and it looks like we can fix this by replacing the link and script elements with the user's code. This is guaranteed to break something, though. It might be a little while before we can be confident that we've fixed this without creating too many other issues.
