### ISSUE TITLE
[Product Landing Page] Added User Story

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#45931]
### Describe the Issue

The following test (user story) prevents my previously passing project from passing:

```
Your #video should have a src attribute.
```

**Important**: Notice I use `<video><source></source></video>` instead of just `<video src=""></video>`

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-product-landing-page-project/build-a-product-landing-page

### Your code

- https://codepen.io/anon/pen/bXRGNa

_I never claimed to be a UI expert_

### Expected behavior

Do we want to keep such a test?

### System

_Unrelated_

**Comment by nhcarrigan** [comment]
Maybe you should update your project 🙃 

Honestly I think small tweaks are going to be okay - my tribute page fails because the image needs a height now.

**Comment by moT01** [comment]
https://github.com/freeCodeCamp/testable-projects-fcc/blob/main/src/project-tests/product-landing-page-tests.js#L127

**Comment by Sboonny** [comment]
although, I think it's good that, we moved on from the old test.

 `<source>` tag is extremely useful in html, it has `media` attribute that help developers use less need css, which lead to better experience, [Source Docs](https://www.w3schools.com/TAGS/tag_picture.asp). it should be accepted to use `<video><source></source></video>`
