### ISSUE TITLE
CodeRoad Tutorial not working | VM will run but the tutorial is not there | Build a Mario Database

### ISSUE THREAD

**Issue by hvaandres** [freeCodeCamp/freeCodeCamp#45938]
### Describe the Issue

I'm currently trying to complete the assignments from Learn Relational Databases by Building a Mario Database and the VM will start and Visual Studio Code will appear inside of the VM, but the tutorial by CodeAlly will not appear.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

No code at the moment

### Expected behavior

The Page should start working as soon as you logged in

### Screenshots

<img width="702" alt="Screen Shot 2022-05-12 at 10 41 29 PM" src="https://user-images.githubusercontent.com/26829975/168212489-86f47e74-2048-4874-830d-2101f908e283.png">

### System

- Device: Laptop
- OS: MacOS Monterey 12.3.1
- Browser: Chrome
- Version: 101.0.4951.64

### Additional context

When I logged in for the first time, I was able to run to some of the examples. Then, I decided to stop and close chrome. At the time that I get back to this tutorial for the second time, I noticed that the tutorial was not there anymore.

**Comment by gikf** [comment]
Hey @hvaandres,

are you able to start CodeRoad extension manually? From the command palette `CodeRoad: Start` should bring back tutorial window.

**Comment by raisedadead** [comment]
@moT01 wasn't there a help article about this? Could we make that more obvious to avoid issues like this being logged on the tracker?

**Comment by moT01** [comment]
Yes, you can learn [how to start the course manually here](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231/1#your-container-loaded-but-coderoad-didnt-start-automatically-6) @hvaandres. There's a number of other troubleshooting steps there, as well. If you're stuck, make a reply to that post or create a new post and we can help you work through the issue.


> make that more obvious

@raisedadead, there's a banner with a link to the post on the superblock page. Were you thinking of something more? Most people seem to be using the forum - this may be the first GH issue we've seen.

**Comment by raisedadead** [comment]
> Were you thinking of something more? Most people seem to be using the forum - this may be the first GH issue we've seen.

I sure hope it's the last here or elsewhere. 

Remember the "absence of error" fallacy? As a user (presumably lazy or in a rush like most humans), that black VS Code is confusing. If there is the slightest chance, we can put something there. Even if it's a default README, for all I care, it would help.

**Comment by hvaandres** [comment]
Thank you guys for your help. I forgot about this but I was able to make it work
