### ISSUE TITLE
Filter Arrays with filter has a bad example with %

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4593]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) has an issue.

Had a user share code for this one today like this:
```js
var newArray = oldArray.filter(function(val)
{
  return val < 5  === 0;
});
```

Couldn't figure out what they thought was going on, until I looked at the example code:
```js
array = array.filter(function(val) {
  return val % 2 === 0;  // % is not a comparison operator
});
```

This example should probably be changed to some sort of comparison operator other than `===` combined with `%`.

**Comment by ltegman** [comment]
This sounds like a good plan. I can see the potential for that example code to create confusion for new coders so changing it to a simple comparison would be great.
