### ISSUE TITLE
RWD Projects' test should accept HTML tags with `media` attribute

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#45939]
### Describe the Issue

> Your portfolio should use at least one media query.

Projects with that requirement should accept HTML tags with `media` attribute.

As described in this [doc's](https://www.w3schools.com/TAGs/tag_source.asp) page, `media` have the value of `media_query`. which technically should pass the top requirement

### Affected Page

[build portfolio](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage) 

[build technical page](https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page)

### Your code

```html
<picture>
        <source media="(min-width: 35em)" srcset="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.7qeEY9Xlu7r1UEmFuT9w9AHaFj%26pid%3DApi&f=1" alt="cat in a pot" />
        <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.hOf-jG62n2syzAIYHr4KdwHaE6%26pid%3DApi&f=1" alt="cat in a barn" />
</picture>
```

### Expected behavior

Your portfolio should use at least one media query's test to pass 

### Screenshots

![image](https://user-images.githubusercontent.com/88248797/168225300-d57eef90-052e-4754-aebd-c0540993431a.png)

### System

Device: laptop
system: Windows 11 with WSL installed
browser: Edge, same happens in FireFox

### Additional context

#45931 made me wanna test `source` tag kudo to Shaun

**Comment by Sboonny** [comment]
Oh for more info the test is 
```js
assert.isAtLeast(new __helpers.CSSHelp(document).getCSSRules('media')?.length, 1);
```
And it's in this file [personal-portfolio.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/831b062f2329dcad596a43868cf6f21859a953f7/curriculum/challenges/english/14-responsive-web-design-22/build-a-personal-portfolio-webpage-project/build-a-personal-portfolio-webpage.md)

**Comment by ShaunSHamilton** [comment]
@Sboonny [`CSSHelp`](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/utils/css-help.ts) is an in-house class. Completely unrelated to Bootstrap.

**Comment by Sboonny** [comment]
thanks shaun. I was lost trying to figure it out. and thanks for the links as well. 🤍
