### ISSUE TITLE
View button for viewing new multifile solutions is not full width

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45947]
### Describe the Issue

When looking at your settings page or timeline, the view button to see a code solution and preview for the new multifile solutions is not full width. All the other buttons on those pages are full width.

### Steps to Reproduce

1. Go to https://www.freecodecamp.dev/fccb1
2. See button, not full width - other buttons are

### Expected behavior

To be full width

### Screenshots

![Screen Shot 2022-05-13 at 9 01 39 AM](https://user-images.githubusercontent.com/20648924/168300443-c2da5352-6978-4bb1-b153-69b50cc3522c.png)

^ Timeline - same on settings page

**Comment by Sboonny** [comment]
this issue happens because `<div class="dropdown btn-group btn-group-primary">...</div>``` isn't `inheriting` it's parent element `<td>`. 

adding `width: 100%`  will fix it. 
![image](https://user-images.githubusercontent.com/88248797/168304030-f9cfeb53-c6d6-4472-bf57-11b90b4ea471.png)

I will make pr tomorrow, if no pr is present😓

**Comment by Sboonny** [comment]
hey Tom, because of bbsmooth's accessibility Pull request, I got this idea that we should swap `Show Code` and `Show Solution` with `View` while adding `.sr-only` to `span` in the `button` with `innerText` equal to **Code** or **Solution**.

Examples:

``` html
- <button>Show Code</button>
- <button>Show Solution</button>

+ <button>View <span class="sr-only>Code</span></button>
+ <button>View <span class="sr-only>Solution</span></button>
```

What do you think?
