### ISSUE TITLE
Code solution modal on timeline is more narrow than others

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45948]
### Describe the Issue

The modal for viewing code solutions on the timeline page is more narrow than all the other modals.

### Steps to Reproduce

1. Go to https://www.freecodecamp.dev/fccb1
2. Click view -> code for one of the new RWD cert projects
3. See narrow modal
4. Close modal -> click view -> project
5. See wider modal
6. Go to https://www.freecodecamp.dev/certification/fccb1/responsive-web-design
7. View the same two modals, they're both the wide version

### Expected behavior

All of them to be the wide version

**Comment by CAPTAINCOBRA** [comment]
It's simple. Because the "modal-lg" class is not present in the code along with "modal-dialog" class. Can I add this here and take the issue please?

**Comment by moT01** [comment]
Go for it @CAPTAINCOBRA

**Comment by CAPTAINCOBRA** [comment]
Hi Tom,
Its my first open source contribution. I have made the change in my local copy and it is working. 
I have added it in my forked repo here - https://github.com/CAPTAINCOBRA/freeCodeCamp/commit/d39e6e062fe4df2f234f3d984ddbb95bbf9b47c9
Can you please help me out and guide me on who approves the change?

**Comment by gikf** [comment]
Hey @CAPTAINCOBRA,

Here's page from contributing guidelines covering basics of opening pull request - https://contribute.freecodecamp.org/#/how-to-open-a-pull-request.

Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Happy contributing.

**Comment by CAPTAINCOBRA** [comment]
hey @gikf ,
I have sent a pull request regarding the issue
Thanks for the help
