### ISSUE TITLE
Code solution modal title is left aligned

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45946]
### Describe the Issue

The title for code preview modals is left aligned. The rest of our modals have a centered title.

### Steps to Reproduce

1. Go to https://www.freecodecamp.dev/fccb1
2. Click on view -> show code
3. See left aligned title
4. Close it -> click view -> show project
5. Title is centered

### Expected behavior

Center the title

### Screenshots

Code modal:
![Screen Shot 2022-05-13 at 8 45 50 AM](https://user-images.githubusercontent.com/20648924/168297969-878669f8-2228-49e0-aec8-0d52c9319982.png)

Preview modal:
![Screen Shot 2022-05-13 at 8 46 14 AM](https://user-images.githubusercontent.com/20648924/168297965-f1539de8-4534-432d-9f27-447ab8d6bc27.png)

### Additional context

I think I would just center the title, not the HTML/CSS/JS title

**Comment by Sboonny** [comment]
I see there is `.text-center` with value `text-align: center;`, I will start working on it
