### ISSUE TITLE
Wrong hint in step 53 of the Cafe menu project

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#45940]
In step 53 of the Building a Cafe Menu project:
Adding by mistake three p elements inside a single article element (instead of three different article elements), I received an unhelpful hint message.

Code:
```
<article class="item">
            <p class="dessert">Donut</p><p class="price">1.50</p>
            <p class="dessert">Cherry Pie</p><p class="price">2.75</p>
            <p class="dessert">Cheesecake</p><p class="price">3.00</p>
            <p class="dessert">Cinnamon Roll</p><p class="price">2.50</p>
          </article>
```
Hint:

> You should not have any spaces between your p elements.

I think that the hint should say something like: You should add three new article elements.

**Comment by Sboonny** [comment]
[Step 53 file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f716bee5838c354c728a7c5.md)

**Comment by moT01** [comment]
[Step page](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-53)

**Comment by Arerib** [comment]
<section>
          <h2>Desserts</h2>
<article class="item">
      <p class="dessert">Donut</p><p class="price">1.50</p>
      <p class="dessert">Cherry Pie</p><p class="price">2.75</p>
      <p class="dessert">Cheesecake</p><p class="price">3.00</p>
      <p class="dessert">Cinnamon Roll</p><p class="price">2.50</p>
 </article>
</section>
