### ISSUE TITLE
View button on new RWD certs looks out of place

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45949]
### Describe the Issue

The links to projects on the new RWD certs have a 'view' button (see screenshots). All other certs have text links.

### Steps to Reproduce

1. Go to https://www.freecodecamp.dev/certification/fccb1/responsive-web-design
2. See 'view' button
3. Go https://www.freecodecamp.org/mot01
4. Click on any cert
5. See text links, not view button

### Expected behavior

Change the 'view' button to two text links similar to the URL + github URL solution in the image below. I would go with `code` and `preview` or `code` and `project`.

### Screenshots

New RWD certs:
![Screen Shot 2022-02-23 at 12 14 16 PM](https://user-images.githubusercontent.com/20648924/155387422-e510bbd7-de85-4fc7-ba27-9ce823575c81.png)
^ landing page has a URL (codepen) solution - others have the multifile editor solution

Here's what the URL + github URL solutions look like:
![Screen Shot 2022-02-23 at 12 22 35 PM](https://user-images.githubusercontent.com/20648924/155387514-ddbc7957-ce69-420f-bb57-da88149a835f.png)

**Comment by nhcarrigan** [comment]
The problem is the `solution` and `source` are links to external projects.

I'm not sure I'm a fan of changing the button to look like a link, since it opens a modal instead of being a link.

**Comment by moT01** [comment]
I hear what you're saying @nhcarrigan - although, the [JS projects](https://www.freecodecamp.dev/certification/fccb1/javascript-algorithms-and-data-structures) look like links and open up the modal:
![Screen Shot 2022-05-16 at 3 57 19 PM](https://user-images.githubusercontent.com/20648924/168681392-b63b4320-e818-46c8-9e22-5a78fc845045.png)

With the current UI, I feel like I would prefer them all be text, even if they open the modal - for consistency and they fit better.

Perhaps we could just make the buttons a bit shorter and they would look better. I think something could be done anyway - those buttons are too close. Maybe a grid like the timeline.

**Comment by moT01** [comment]
I think we should change this to a table so it looks like what's on the timeline page. Then they can all be buttons.

**Comment by ieahleen** [comment]
the settings has changed since then. is this still an issue?

**Comment by moT01** [comment]
The settings did change, but I still think it looks a little rough:
![Screen Shot 2022-07-24 at 8 30 09 AM](https://user-images.githubusercontent.com/20648924/180650292-0f866ffa-4347-4f42-af1b-f336ae732d54.png)

I suggested turning this area into a table, like the timeline - what do you think about that @ieahleen?

**Comment by ieahleen** [comment]
I don't have a preference, personally, I was just looking to see if the issue could be closed or it still needs to be solved

**Comment by moT01** [comment]
I cut a couple screen shots together for an example of what I think it should maybe look like:
![Untitled](https://user-images.githubusercontent.com/20648924/181508021-ea95d985-daac-45a2-a259-790c861d5bdf.png)

**Comment by naomi-lgbt** [comment]
The timeline is a distinct component so we might be able to do that?

**Comment by chrysillala** [comment]
Hi, can I contribute to this issue? Would appreciate if you could share some guidance, thanks!

**Comment by moT01** [comment]
There's [a comment on another issue (linked above)...](https://github.com/freeCodeCamp/freeCodeCamp/issues/46497#issuecomment-1158992698)
>It seems like we have three places where we show lists of projects and their solutions.
>  1. Portfolio timeline
>  2. Certification page
>  3. Settings
>
>Ideally, they should be the same component and the same buttons for displaying the code.

So I think we want to make a single component that displays a list of projects, probably so it looks like the timeline. Then we can use that component in those three places. Those three places all look a little different, so I'm not sure if we just want to unify the look or maybe make some things optional - like maybe an option to show the completed date. Perhaps @ahmadabdolsaheb can elaborate on some of the specifics of the looks. I think I would just vote to unify the look so they all look like the timeline. 

I think you would be safe to get started on a PR that does that if you want @chrysillala - and if we want them to look a little different on the various pages, it shouldn't be difficult to make those adjustments. Let us know if you need any more clarity or help.

**Comment by adi-uchiha** [comment]
Hey , Can I work on making that component?

**Comment by ahmadabdolsaheb** [comment]
So we have three tables, one in the certification, on in the settings, and one in the timeline.

They should all essentially be the same bootstrap table element with different  styling props (condensed: boolean;
  striped: boolean) and different columns.

We have traditionally used striped and condensed when we have a large list of data (timeline), but I am open to unifying our tables.

We could add a completed column if you think that info is essential. The only consideration is that it would make things wrap early on tablet viewports.

If anyone is interested, I suggest starting by gathering requirements from different table implementations ( shape of data, column titles, props, etc) and unifying them into one component that shows different columns based on the data that is passed.

**Comment by moT01** [comment]
> We could add a completed column...

I can see that being potentially helpful on the settings page. In the other two places, everything is completed, so it would just be a list of check marks or something. We do have the solution column - we could potentially use that to display "Not Completed" or something on the settings page if we want to convey that info somehow while not taking up more space.

**Comment by ahmadabdolsaheb** [comment]
Would having a  view button signify a project's completion?

**Comment by moT01** [comment]
It does - I'm not sure how obvious it is to campers though. Actually, the timeline already does have a completed column to show the date completed. So we will want to keep that I think.

**Comment by ahmadabdolsaheb** [comment]
Yes, we should keep the number of columns as they are for now imho.

**Comment by nayabatir1** [comment]
Hey I would like to work on this issue.
To summarise, make table component which looks like [this](https://github.com/freeCodeCamp/freeCodeCamp/issues/45949#issuecomment-1198093516) with some configurations.
Also I have to use this components in 3 different places mentioned [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/46497#issuecomment-1158992698)

**Comment by nayabatir1** [comment]
When ever I try to navigate to settings page, it redirects me to `localhost:3000/signin` page.
Any suggestions?

![image](https://user-images.githubusercontent.com/91016903/197023810-0459703c-5548-48af-be63-e63b40c646ac.png)

**Comment by nayabatir1** [comment]
when I tried to run `npm run develop:server`
I might be missing something, but I don't know what

![image](https://user-images.githubusercontent.com/91016903/197070835-8dc37189-8b54-4685-a058-3496134cdfd7.png)

**Comment by naomi-lgbt** [comment]
Have you set a `MONGOHQ_URL` in the `.env` file? By default, if you copied the `sample.env`, this is set to a local instance.

**Comment by nayabatir1** [comment]
I'm not local mognodb

**Comment by nayabatir1** [comment]
What is the link for Portfolio timeline

**Comment by varunmulay22** [comment]
@nayabatir1 I suspect you havent started your mongo server using mongod cmd which is why the error. If you have, then the next suspect would be the .env file containing MONGOHQ_URL with localhost string instead of 127.0.0.1. Try replacing it and run `npm run develop:server` again
