### ISSUE TITLE
Chinese translation of Get Started with Free Code Camp

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4594]
- [x] Learn how Free Code Camp Works
- [x] Create a GitHub Account and Join our Chat Rooms
- [x] Configure your Code Portfolio
- [x] Join a Campsite in Your City
- [x] Learn What to Do If You Get Stuck

**Comment by leonfeng** [comment]
Proofreaders, please review https://github.com/leonfeng/FreeCodeCamp/commit/b51999e69070c48d2d45a63c5620d36e3c4718e2. Thanks! You can comment on the translation like this: 

![Comment on line of code](https://help.github.com/assets/images/help/commits/hover-comment-icon.gif)

**Comment by erictleung** [comment]
Closing this issue in favor of moving the conversation over to FreeCodeCamp/TranslationExpansion#2
