### ISSUE TITLE
[multifile editor: cert projects] Add a button to hide instructions

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#45950]
### Describe the Issue

When working on the RWD cert projects using the multifile editor, space is somewhat limited. A button to toggle the instructions might be nice.

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-tribute-page-project/build-a-tribute-page
2. See instructions
3. No way to hide them (edit: I guess you can change the width, but I don't think that's as good of a UX)

### Expected behavior

A way to toggle instructions to give more space

**Comment by ahmadabdolsaheb** [comment]
Adding another button to the button group should do it.
[Instructions][index.html][styles.css]
That being said, we might need to add a way to distinguish which pane is for which button. There is not easy way to tell html and css panes apart.

**Comment by moT01** [comment]
I'm going to open this up for contribution. I would stick with just adding a button to toggle the instruction pane for now.
