### ISSUE TITLE
Css part of registration form project does not accept right answers

### ISSUE THREAD

**Issue by KavrinDEV** [freeCodeCamp/freeCodeCamp#45963]
### Describe the Issue

for example in [step 7](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f1922fcbd2410527b3bd89.md) description says:

> To spruce the project up, let us add some CSS. Begin by giving the body a width of 100%, and a height of 100vh.

but when you type `body {
  width: 100%;
  height: 100vh;
}` it does not accept the solution 

>  Sorry, your code does not pass. Don't give up. Hint: You should give the body a width of 100%. 

[step 8](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f1a5e2d2c23707a4f9a660.md):

> Now, get rid of the horizontal scroll-bar, by setting the body default margin added by some browsers to 0.

code: `body {
  width: 100%;
  height: 100vh;
  margin: 0;
} `

> Sorry, your code does not pass. Hang in there. Hint: You should add margin within the body element selector.

[step 14](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f803d5241e6a0433a523a1.md): 

> As label elements are inline by default, they appear on the same line as the text they are labelling. To make them appear on separate lines, add display: block to the label element, and add a margin of 0.5rem 0, to separate them from each other.

code:`
label {
  display: block;
  margin: 0.5rem 0;
}`

> Sorry, your code does not pass. Try again. Hint: You should use the label selector.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-forms-by-building-a-registration-form

### Your code

```
label {
  display: block;
  margin: 0.5rem 0;
}
```

### Expected behavior

expected behavior is that the tests should pass the solution as it's answer that has been used in the steps afterwards

### Screenshots

![Untitled](https://user-images.githubusercontent.com/93947258/168416826-8d6f6eed-2d8c-4729-84aa-d3a360cd480b.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Hey @KavrinDEV,

I'm not able to reproduce the issue. Please include more information - what browser are you using? What OS? Do you have any browser extensions that might be affecting page style?

**Comment by KavrinDEV** [comment]
@gikf 
i use firefox on windows. apparently [this extension](https://addons.mozilla.org/en-US/firefox/addon/selectext/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) was affecting the page. thank you
