### ISSUE TITLE
I'm able to pass this Waypoint even with a typo.

### ISSUE THREAD

**Issue by xfilipe** [FreeCodeCamp/FreeCodeCamp#4596]
Challenge [Waypoint: Get Geolocation Data](http://www.freecodecamp.com/challenges/waypoint-get-geolocation-data?solution=fccss%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%0A%20%20if(navigator.geolocation)%7B%0A%20%20%20%20navigator.geolocation.getCurrentPosition(function(position)%7B%0A%20%20%20%20%20%20%24(%22%23data%22).html(%22latitude%3A%20%22%2Bposition.coords.latitude%2B%22%3Cbr%3Elongitude%3A%20%22%2Bpsition.coords.longitude)%3B%0A%20%20%20%20%7D)%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0Afcces%0A%3Cdiv%20id%20%3D%20%22data%22%3E%0A%20%20%3Ch4%3EYou%20are%20here%3A%3C%2Fh4%3E%0A%20%20%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I'm able to pass even with a typo on *psition.coords.longitude*.

My code:
```html
<script>
  // Only change code below this line.
  
  if(navigator.geolocation){
    navigator.geolocation.getCurrentPosition(function(position){
      $("#data").html("latitude: "+position.coords.latitude+"<br>longitude: "+psition.coords.longitude);
    })
  }
  
  
  
  // Only change code above this line.
</script>
<div id = "data">
  <h4>You are here:</h4>
  
</div>

```

**Comment by SaintPeter** [comment]
I have confirmed this issue.  Unfortunately we do not currently have the infrastructure in place to be able to detect this issue.  We have plans in place to make it, though, so I'll keep this open.
