### ISSUE TITLE
Clarify New VS Old Responsive Web Design cert right in /learn UI

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#45968]
### Describe the Issue

The biggest issue we've had with promoting the updated Responsive Web Design certification to production (and retiring the old one to legacy) is confusion from past visitors. They seem to think their progress was erased.

I have a simple way we can update this:

Put the word `(New)` in front of Responsive Web Design on /learn, then move the Legacy Responsive Web Design cert to be immediately below it, like this:
![Learn_to_Code_—_For_Free_—_Coding_Courses_for_Busy_People_and_Idea_](https://user-images.githubusercontent.com/985197/168430748-1eeeefa1-e84a-47df-87f2-d649dfa77149.png)

I believe this will immediately reduce confusion.

We can just show this for returning campers – not new ones. (Though I think we can add this functionality later. The most immediate concern is reducing confusion.)

Then, a few weeks from now, we can revert to just putting the legacy cert at the bottom again.

### Affected Page

https://www.freecodecamp.org/learn

### Your code

N/A

### Expected behavior

Clarity

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Personally, I would find a way to visually distinguish new content:

https://user-images.githubusercontent.com/51722130/168440254-60623cae-4fe6-4b1e-a1cd-17b5d2505e4b.mp4

Something Campers could get used to, and come to recognise.

**Comment by nhcarrigan** [comment]
I am very much a sucker for shiny things and now feel like we *have* to do this. 😁

**Comment by ojeytonwilliams** [comment]
That is pretty slick.

**Comment by ahmadabdolsaheb** [comment]
IMHO, we could simply add a tag to differentiate an item in a "list". 

An good example is the "certification project" tag on the certification project cards in the new cert. 

Additionally we could have a Dropdown in the corner of the super block for navigating between versions. 

Lastly, we might be able to detect the last completed challenge and see if it is from the legacy cert. If so we could have an onboarding alert message on the new cert explaining their progress and navigation.
