### ISSUE TITLE
Chinese translation of Responsive Design with Bootstrap

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4597]
- [ ] Use Responsive Design with Bootstrap Fluid Containers
- [ ] Make Images Mobile Responsive
- [ ] Center Text with Bootstrap
- [ ] Create a Bootstrap Button
- [ ] Create a Block Element Bootstrap Button
- [ ] Taste the Bootstrap Button Color Rainbow
- [ ] Call out Optional Actions with Button Info
- [ ] Warn your Users of a Dangerous Action
- [ ] Use the Bootstrap Grid to Put Elements Side By Side
- [ ] Ditch Custom CSS for Bootstrap
- [ ] Use Spans for Inline Elements
- [ ] Create a Custom Heading
- [ ] Add Font Awesome Icons to our Buttons
- [ ] Add Font Awesome Icons to all of our Buttons
- [ ] Responsively Style Radio Buttons
- [ ] Responsively Style Checkboxes
- [ ] Style Text Inputs as Form Controls
- [ ] Line up Form Elements Responsively with Bootstrap
- [ ] Create a Bootstrap Headline
- [ ] House our page within a Bootstrap Container Fluid Div
- [ ] Create a Bootstrap Row
- [ ] Split your Bootstrap Row
- [ ] Create Bootstrap Wells
- [ ] Add Elements within your Bootstrap Wells
- [ ] Apply the Default Bootstrap Button Style
- [ ] Create a Class to Target with jQuery Selectors
- [ ] Add ID Attributes to Bootstrap Elements
- [ ] Label Bootstrap Wells
- [ ] Give Each Element a Unique ID
- [ ] Label Bootstrap Buttons
- [ ] Use Comments to Clarify Code

**Comment by erictleung** [comment]
Closing in favor of moving the conversation over to https://github.com/FreeCodeCamp/TranslationExpansion/issues/4
