### ISSUE TITLE
Misleading hint message after failing the test

### ISSUE THREAD

**Issue by tbgracy** [freeCodeCamp/freeCodeCamp#45973]
### Describe the Issue

I nested an `img` element withing the `figure` element, then set the wrong link to the `src` attribute and checked the code but it hints that I should have a third `img` element nested in the `figure` element.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-28

### Your code

```
<figure>
  <img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/lasagna.jpg">
</figure>
```

### Expected behavior

I excpected the hint to tell me that I typed a wrong `src` value.

### Screenshots

![issue](https://user-images.githubusercontent.com/65624131/168442873-297c6e3d-4177-43a8-a8c1-ed3acf50e63e.png)

### System

- Device:Laptop
- OS: Ubuntu 20.04
- Browser: Chrome
- Version: 101.0.4951.64

**Comment by benjaminJohnson2204** [comment]
> we can do the same for checking `src`. something like
const figureSrc = document.querySelectorAll('figure > img')[1];
assert(
  figureSrc.length === 1
);

I'm not sure how that would check if a `src` is in `figure`. Wouldn't that just check if an `img` is in `figure`? 


> `The third image should have an src attribute.`
const catsImg = document.querySelectorAll('figure > img')[1];
assert(
  catsImg &&
    catsImg.getAttribute('src')
);

Doesn't this code already check if there is a `src` in the `img` ?

**Comment by Sboonny** [comment]
True I forgot to add `attribute` checker 😓

**Comment by Sboonny** [comment]
> Doesn't this code already check if there is a src in the img ?

it checks if `figure`'s `img` has `src`, but because the next code do almost the same thing, when error happens the first one runs and send the wrong hints.

so I wonder instead of checking if `img` has `src` in them, we check if the code exist. if it does it goes to next checker and check if the `src` has the right link in it.

```js
const figureSrc = document.querySelectorAll('figure > img')[1].getAttribute('src');
assert(
figureSrc.length >= 1
);
```

what do you think?

**Comment by benjaminJohnson2204** [comment]
Oh, I understand now. I think that's a good idea. So you're saying we could use that test instead of the test below?

`The third image should have an src attribute.`
```js
const catsImg = document.querySelectorAll('figure > img')[1];
assert(
catsImg &&
catsImg.getAttribute('src')
);
```

**Comment by Sboonny** [comment]
> I think that's a good idea. 

thank you 🤍.

yes I do think changing that test would be better. I will be honest, although that sounds logical in my head, I haven't tested it out. so there is a chance that my code won't work. 😅
