### ISSUE TITLE
class="classname" challenges identifying spaces as mistakes

### ISSUE THREAD

**Issue by TRBF** [freeCodeCamp/freeCodeCamp#45978]
### Describe the Issue

When given the task of assigning a class to a certain object and placing spaces around the = sign (class = "class-name"), although the code is working properly, a warning is thrown out saying you still need to assign the class. This warning can be easily avoided by removing the spaces around the = sign (class="class-name"), but the fact that the warning is not stating it is best practice to remove the spaces and just deems the code incorrect might confuse new people.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-33

### Your code

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cafe Menu</title>
    <link href="styles.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div class="menu">
      <header>
        <h1>CAMPER CAFE</h1>
        <p>Est. 2020</p>
      </header>
      <main>
        <section>
          <h2>Coffee</h2>
          <article class="item">
            <p class = "flavor">French Vanilla</p>
            <p class="price">3.00</p>
          </article>
          <article>
            <p>Caramel Macchiato</p>
            <p>3.75</p>
          </article>
          <article>
            <p>Pumpkin Spice</p>
            <p>3.50</p>
          </article>
          <article>
            <p>Hazelnut</p>
            <p>4.00</p>
          </article>
          <article>
            <p>Mocha</p>
            <p>4.50</p>
          </article>
        </section>
      </main>
    </div>
  </body>
<html>

```

### Expected behavior

It should have evaluated the code as correct, ignoring the spaces around the = sign.

### Screenshots

![Capture2](https://user-images.githubusercontent.com/104624564/168466977-d0397ecc-a9ce-42c8-b9a0-9970762be667.PNG)
![Capture](https://user-images.githubusercontent.com/104624564/168466978-282816d6-2ce2-43c5-9a42-2fa550170f86.PNG)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Firefox & Chrome

**Comment by Sboonny** [comment]
The markdown file is [here: cafe menu step 23](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3c866d28d7ad0de6470505.md)

**Comment by Sboonny** [comment]
@TRBF the topic is mentioned in freeCodeCamp chat. It will receive attention when dB issues are less severe.

Unless the issue is fixed, of course 💚
