### ISSUE TITLE
New RWD editor: scripts loaded is making media query test fail

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#45977]
### Describe the Issue

Not sure what is happening. But one thing I did notice is that the scripts have had `"use strict";` added inside them.

![odd script content](https://user-images.githubusercontent.com/28780271/168456097-d22b8a78-ae32-4d64-a8a1-662697515412.png)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-personal-portfolio-webpage-project/build-a-personal-portfolio-webpage

### Your code

Scripts breaking the test
```
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
```

### Expected behavior

For it not to break.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum thread: https://forum.freecodecamp.org/t/personnal-portfolio-media-query-issue/508731

**Comment by coxde** [comment]
Same here, but use this script:

> 	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/default.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
	<script>hljs.highlightAll();</script>

**Comment by moT01** [comment]
Just to clarify - the one media query test on that project is failing for you as well @coxde?

**Comment by coxde** [comment]
> Just to clarify - the one media query test on that project is failing for you as well @coxde?

Yes, after I delete this script, I passed the one media query test.
