### ISSUE TITLE
the code is wrong!  in    https://www.freecodecamp.org/news/lets-talk-about-semicolons-in-javascript-f1fe08ab4e53/

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#45981]
### Describe the Issue

I read    [orgin article](https://flaviocopes.com/javascript-automatic-semicolon-insertion/), I find  all the code  show is wrong 

for example
![image](https://user-images.githubusercontent.com/6524977/168479875-b5bdf1b9-4950-4751-8c5d-05be6783e402.png)
but  in  freecodecamp 
![image](https://user-images.githubusercontent.com/6524977/168479929-0936c662-8f53-4563-9c9e-c0b2833c577b.png)

### Affected Page

https://www.freecodecamp.org/news/lets-talk-about-semicolons-in-javascript-f1fe08ab4e53/

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

The code show  not  all in a line.
It should has Indent  ， the code can run 

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching this @luojiyin1987, and for these helpful details.

I went through and fixed these code blocks, and added JS highlighting.

I'll keep an eye on the article, and will close this issue after confirming the fixes go live after the next build.

**Comment by scissorsneedfoodtoo** [comment]
Hey @luojiyin1987, thanks again for your patience and reporting this issue.

The build completed a little while ago, and the old cache expired. You should now be able to see the fixed code snippets and highlighting: https://www.freecodecamp.org/news/lets-talk-about-semicolons-in-javascript-f1fe08ab4e53/

Please let us know if you notice issues in any other articles. Also, feel free to @ mention me directly :slightly_smiling_face:

**Comment by luojiyin1987** [comment]
I check it ， it is OK！    @scissorsneedfoodtoo   🙂
