### ISSUE TITLE
Add Hint on Learn Relational Databases by Building a Mario Database

### ISSUE THREAD

**Issue by clarkngo** [freeCodeCamp/freeCodeCamp#45986]
### Is your feature request related to a problem? Please describe.

User unable to proceed if table has duplicate data.

### Describe the solution you'd like

Let’s add a hint on how to delete duplicate data if user accidentally inserted twice of the same.
![image](https://user-images.githubusercontent.com/30854108/168546963-b150ed72-3958-46f7-8f07-0f5367f92e49.png)

### Describe alternatives you've considered

Alternative can be, to add a step or a reminder lesson on deleting duplicate data.

**Comment by moT01** [comment]
Thanks for the suggestion @clarkngo. I don't think it's a good hint to add here, it's not really part of what's needed to pass the step. I don't think we can add a hint for each edge case that might go wrong. If you get stuck, be sure to check the [troubleshooting steps on the forum](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231#troubleshooting-2)
