### ISSUE TITLE
Unable to complete challenge on Learn Relational Databases by Building a Mario Database

### ISSUE THREAD

**Issue by clarkngo** [freeCodeCamp/freeCodeCamp#45987]
### Describe the Issue

Doesn't give any feedback on what is wrong. It should be able to proceed.
![image](https://user-images.githubusercontent.com/30854108/168547523-ab4a6c80-cd58-4386-a154-2d62dce871f5.png)

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

```
ALTER TABLE characters ALTER COLUMN character_id SET NOT NULL;
```

### Expected behavior

Sucess/Pass

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 101.0.4951.54 (Official Build) (64-bit)

**Comment by moT01** [comment]
Thanks for reporting @clarkngo. You should try the [troubleshooting steps in this forum post.](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231#troubleshooting-2) If none of them work, make a post there and I, or someone, can try to help debug the issue. Thanks and happy coding.
