### ISSUE TITLE
Ferris wheel and Penguin project should be switched in the curriculum order

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#45985]
### Describe the Issue

There was a discussion on the [forum here ](https://forum.freecodecamp.org/t/responsive-web-design-updates/508345/71?u=jwilkins.oboe) regarding the penguin project. The user brought up that the animation elements were taught in the ferris wheel project which is currently after the penguin project in the curriculum. This user had some trouble completing the project because of this order. 

Also the [last step of the penguin project](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-104) congratulates the user on completing the course, even though there is a whole other practice project left in the curriculum. 
<img width="679" alt="Screen Shot 2022-05-15 at 11 45 09 PM" src="https://user-images.githubusercontent.com/67210629/168534423-2c8edfa0-e345-4586-9eda-b5f55e440c83.png">

Were these two projects originally swapped in the beta version? 
Should they be swapped back so the Ferris Wheel comes before the penguin project?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-104

**Comment by ShaunSHamilton** [comment]
I somewhat remember discussing this with @nhcarrigan ... 🤔 

If I recall, we did actually make some changes to prevent this sort of issue, but I have no idea where that conversation/change is/went. Any chance you remember, Naomi?

On the Randy Sheet, the order is as on production. So, the "congrats" could just have been me being confused. If it makes more sense, then I would definitely agree with swapping the order.

**Comment by moT01** [comment]
found this related: https://github.com/freeCodeCamp/freeCodeCamp/issues/45096

**Comment by Sboonny** [comment]
I am in support of swapping them, penguin's project will serve as good reminder for the wheel's one

**Comment by ahmadabdolsaheb** [comment]
@nhcarrigan, I think we discussed swapping them when they were under development. Are you able to provide more context?

**Comment by ieahleen** [comment]
I also think we should swap them, it would make more sense, considering that many things in the Ferris Wheel project are used in the Penguin project, and in the Penguin project they are not explained.
So you do the Penguin Project meeting for the first time many confusing concepts, and then find them expained in the next project, the Ferris Wheel.
