### ISSUE TITLE
Chinese translation of Gear up for Success

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4598]
- [ ] Browse Camper News
- [ ] Reference our Wiki
- [ ] Join our LinkedIn Alumni Network
- [ ] Commit to a Goal and a Nonprofit

**Comment by erictleung** [comment]
Closing in favor of moving the conversation over to https://github.com/FreeCodeCamp/TranslationExpansion/issues/5
