### ISSUE TITLE
Old Curriculum Style Option

### ISSUE THREAD

**Issue by DemonSlayer112** [freeCodeCamp/freeCodeCamp#45997]
### Is your feature request related to a problem? Please describe.

Before going on, i love the idea of the new curriculum, loving things getting updated.
I like the old curriculum's way of having a random message when a lesson is completed, it feels rewarding for difficult ones:
![image](https://user-images.githubusercontent.com/70122500/168664792-b5bac76e-2e99-4993-89fc-103a76f98548.png)

How ever, the new one is...repetitive, the same message for each it seems:
![image](https://user-images.githubusercontent.com/70122500/168665314-b6b203ce-d5c9-4256-a96f-b9b1677f4919.png)

And whats worse? If you do end up ctrl+enter submitting(as I do) and your scrolled up you wont see if you completed it or not on longer lessons.

### Describe the solution you'd like

It would be nice for the popup to find a way into the new layout, either as a option in settings or not, but there's a way I believe it would blend in rather beautifully.

At the top you have files, "index.html" for instance.
What if, sense its fixed at the top, it would turn green or red if the submitted answer were wrong?
This not only tells the user the answer was wrong without having to see if they were right or not in the first place, it could also highlight the given file where the issue is, or multiple.

And for that little rewarding feeling of the random message maybe it can popup near the files:
![image](https://user-images.githubusercontent.com/70122500/168666400-a29ddecc-d80a-49aa-82df-e60b36532950.png)

Again this is mainly for helping with not being in scroll with the current new "result box" if there's an error or if it feels like at times somethings wrong.

### Describe alternatives you've considered

Since this is required im going to reference to the "Describe the solution you'd like" section.
Sorry for the bother.

### Additional context

This is reply to https://forum.freecodecamp.org/t/new-course-layout/508942 but i couldnt send more than one img for being new so i assumed here would be best.

**Comment by ahmadabdolsaheb** [comment]
Thank you @DemonSlayer112 for the feedback.

We are baking some of the previous interaction patterns into the new editor and releasing them on a weekly basis. 

> However, the new one is...repetitive, the same message for each it seems:

I agree, there are a few texts that are only valuable to new users. We could remove/replace them if a user has completed a number of challenges.

> And whats worse? If you do end up ctrl+enter submitting(as I do) and your scrolled up you wont see if you completed it or not on longer lessons.

I agree, an indicator of step completion should be visible regarding of where the user is in the editor. There is a highlighter next to the left of the suggested editable region that turns green when tests pass.  Let me know if you have noticed that or you were in a part of the editor where the highlighter was not visible. The more context you provide the better.

> It would be nice for the popup to find a way into the new layout, either as an option in settings or not, but there's a way I believe it would blend in rather beautifully.

Most of the pop up elements such as the progress bar will find their way into the editor and be displayed in the proper state.

> And for that little rewarding feeling of the random message maybe it can popup near the files:

The random messages can be shown next to the test state when tests pass.

**Comment by ahmadabdolsaheb** [comment]
Thank you for your feedback. I have turned some of the points discussed here into actionable items in #46178 and closing this issue as a result. Please refer to #46178 for further discussion.
