### ISSUE TITLE
Chinese translation of jQuery waypoints

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4599]
- [ ] Learn how Script Tags and Document Ready Work
- [ ] Target HTML Elements with Selectors Using jQuery
- [ ] Target Elements by Class Using jQuery
- [ ] Target Elements by ID Using jQuery
- [ ] Delete your jQuery Functions
- [ ] Target the same element with multiple jQuery Selectors
- [ ] Remove Classes from an element with jQuery
- [ ] Change the CSS of an Element Using jQuery
- [ ] Disable an Element Using jQuery
- [ ] Change Text Inside an Element Using jQuery
- [ ] Remove an Element Using jQuery
- [ ] Use appendTo to Move Elements with jQuery
- [ ] Clone an Element Using jQuery
- [ ] Target the Parent of an Element Using jQuery
- [ ] Target the Children of an Element Using jQuery
- [ ] Target a Specific Child of an Element Using jQuery
- [ ] Target Even Numbered Elements Using jQuery
- [ ] Use jQuery to Modify the Entire Page

**Comment by erictleung** [comment]
Closing in favor of moving the conversation over to https://github.com/FreeCodeCamp/TranslationExpansion/issues/6
