### ISSUE TITLE
No jQuery Exercise Descriptions in Firefox

### ISSUE THREAD

**Issue by brndnb** [FreeCodeCamp/freecodecamp#46]
No descriptions and therefore no way to complete these exercises in Firefox.

![screen shot 2015-01-22 at 10 44 52 am](https://cloud.githubusercontent.com/assets/7098232/5860188/5637d12a-a225-11e4-927d-30aac4bcf0fa.png)

**Comment by QuincyLarson** [comment]
@terakilobyte and I managed to isolate the jQuery compatibility issue that was causing this. We pushed a fix with commit 1f6cb10a32928e7484eb132d8e7c661aefe20b7a. Thanks again for pointing out this huge issue!
