### ISSUE TITLE
Chinese translation of Basic JavaScript

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4600]
- [ ] Comment your JavaScript Code
- [ ] Understand Boolean Values
- [ ] Declare JavaScript Variables
- [ ] Declare String Variables
- [ ] Check the Length Property of a String Variable
- [ ] Use Bracket Notation to Find the First Character in a String
- [ ] Use Bracket Notation to Find the Nth Character in a String
- [ ] Use Bracket Notation to Find the Last Character in a String
- [ ] Use Bracket Notation to Find the Nth-to-Last Character in a String
- [ ] Add Two Numbers with JavaScript
- [ ] Subtract One Number from Another with JavaScript
- [ ] Multiply Two Numbers with JavaScript
- [ ] Divide One Number by Another with JavaScript
- [ ] Create Decimal Numbers with JavaScript
- [ ] Multiply Two Decimals with JavaScript
- [ ] Divide one Decimal by Another with JavaScript
- [ ] Store Multiple Values in one Variable using JavaScript Arrays
- [ ] Nest one Array within Another Array
- [ ] Access Array Data with Indexes
- [ ] Modify Array Data With Indexes
- [ ] Manipulate Arrays With pop()
- [ ] Manipulate Arrays With push()
- [ ] Manipulate Arrays With shift()
- [ ] Manipulate Arrays With unshift()
- [ ] Write Reusable JavaScript with Functions
- [ ] Build JavaScript Objects
- [ ] Update the Properties of a JavaScript Object
- [ ] Add New Properties to a JavaScript Object
- [ ] Delete Properties from a JavaScript Object
- [ ] Iterate with JavaScript For Loops
- [ ] Iterate Odd Numbers With a For Loop
- [ ] Count Backwards With a For Loop
- [ ] Iterate with JavaScript While Loops
- [ ] Generate Random Fractions with JavaScript
- [ ] Generate Random Whole Numbers with JavaScript
- [ ] Generate Random Whole Numbers within a Range
- [ ] Use Conditional Logic with If and Else Statements
- [ ] Sift through Text with Regular Expressions
- [ ] Find Numbers with Regular Expressions
- [ ] Find Whitespace with Regular Expressions
- [ ] Invert Regular Expression Matches with JavaScript

**Comment by erictleung** [comment]
Closing in favor of moving the conversation over to https://github.com/FreeCodeCamp/TranslationExpansion/issues/7
