### ISSUE TITLE
Missing course collapse/expand button for Rosetta Code

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#46006]
### Describe the Issue

Rosetta Code is missing expand/collapse button. 

Issue is caused as a combination of https://github.com/freeCodeCamp/freeCodeCamp/blob/64cb47e1348d63e38a60d78646c1234f1257ecfd/client/src/templates/Introduction/components/block.tsx#L124-L126 with rosetta code having order `3` and challengeType `5`. As such it is treated as projects block.

One possible way of dealing is changing the check above, to include superBlock check. Another might be using different order in meta for Rosetta.

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/coding-interview-prep/
2. Scroll to Rosetta Code

### Expected behavior

Have expand/collapse button for Rosetta Code

### Screenshots

![image](https://user-images.githubusercontent.com/60067306/168751114-f0518529-c381-4e32-86eb-837a4d7c4847.png)

### System

N/A

**Comment by hvinnieg** [comment]
I'll see if I can fix this

**Comment by atmanandsah** [comment]
@raisedadead  Can you please help me out in configuration the freecodecamp web project.
Thanks In Advance

**Comment by raisedadead** [comment]
> Can you please help me out in configuration the freecodecamp web project.

Sure, please follow our [contributing guidelines](https://contribute.freecodecamp.org)
