### ISSUE TITLE
Error Logging in to /learn

### ISSUE THREAD

**Issue by natureflora** [freeCodeCamp/freeCodeCamp#46015]
### Describe the Issue

![https___www freecodecamp org_learn_2022_responsive-web-design#learn-basic-css-by-building-a-cafe-menu - Brave 5_17_2022 9_57_27 PM](https://user-images.githubusercontent.com/45417004/168828623-38f1aac1-ca06-4ded-a07a-6467e1ddd075.png)

### Affected Page

https://www.freecodecamp.org/learn/*

### Your code

On learning page, its says
```
The server could not be reached and your progress may not be saved. Please contact [support](mailto:support@freecodecamp.org) if this message persists
```

### Expected behavior

I am learning coding today as usual, but I am facing up with this problem.

### Screenshots

![https___www freecodecamp org_learn_2022_responsive-web-design#learn-basic-css-by-building-a-cafe-menu - Brave 5_17_2022 9_57_27 PM](https://user-images.githubusercontent.com/45417004/168829141-c9af7e70-b078-4e76-a875-22bb4f4dfb03.png)
![Learn Basic CSS by Building a Cafe Menu_ Step 11 _ freeCodeCamp org - Brave 5_17_2022 10_00_52 PM](https://user-images.githubusercontent.com/45417004/168829207-8b9dd6cc-25aa-475d-a0ed-c216d51eee9a.png)

### System

- Device: Dell Latitude E7240
- OS: Windows 10
- Browser: Brave Browser
- Version: 1.38.117

**Comment by texas2010** [comment]
thank you for the report. freeCodeCamp staff is aware of it.

**Comment by natureflora** [comment]
Meanwhile, freeCodeCamp Beta website [dev.freecodecamp.org](dev.freecodecamp.org) is still accessible.

**Comment by raisedadead** [comment]
See: https://forum.freecodecamp.org/t/announcement-learn-outage/509202; the team is working incredibly hard to get things back to normal. We request your patience.
