### ISSUE TITLE
Chinese translation of Object Oriented and Functional Programming

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4601]
- [ ] Declare JavaScript Objects as Variables
- [ ] Construct JavaScript Objects with Functions
- [ ] Make Instances of Objects with a Constructor Function
- [ ] Make Unique Objects by Passing Parameters to our Constructor
- [ ] Make Object Properties Private
- [ ] Iterate over Arrays with .map
- [ ] Condense arrays with .reduce
- [ ] Filter Arrays with .filter
- [ ] Sort Arrays with .sort
- [ ] Reverse Arrays with .reverse
- [ ] Concatenate Arrays with .concat
- [ ] Split Strings with .split
- [ ] Join Strings with .join

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/8
