### ISSUE TITLE
[DB Optimize] Batch update privacy settings

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#46025]
### Describe the Issue

On a users settings page, there's a bunch of privacy settings you can toggle. Each time you click one, it writes to the user object.

### Expected behavior

We could batch update these like the other areas on the settings page. Toggle the settings to how you want them, and click save - which sends one request to write all the settings at once.

### Additional context

The route it uses is [update-my-profileui](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/boot/settings.js#L117) - I didn't notice anything other than those privacy settings using that route.

**Comment by gikf** [comment]
Related issue: #40764
