### ISSUE TITLE
[DB Optimize] New usernames can make many reads

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#46027]
### Describe the Issue

On the settings page, you can change your username. Any time you stop typing, it reads from the database to see if the username is available - we could change it so that it only makes a query when the user is ready. So instead of when they stop typing, we just let them choose the name they want, then when they click save we check if it's available.

### Additional context

Not sure how big of a deal this is, I'm guessing users don't change their username often. Every little bit helps?

**Comment by nhcarrigan** [comment]
I've always wondered about this one. Definitely agree that we shouldn't hit the DB until the camper tries to submit.

**Comment by ahmadabdolsaheb** [comment]
I think we can go with the current implementation but wait for a meaningful pause to make sure the user is intending to submit the new username for validity check.
