### ISSUE TITLE
[DB Optimize] Claim Cert button makes a query

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#46026]
### Describe the Issue

The 'claim cert' button on the settings page makes a request to [`/certificate/verify`](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/boot/certificate.js#L237). We could check if they have the correct challenges completed on the client using redux and stop the request there if they don't so we don't have to query the db.

**Comment by nhcarrigan** [comment]
> We could check if they have the correct challenges completed on the client using redux

We could use this as an initial check, but we would still need the server side query (to be hit if the client side query passes).
