### ISSUE TITLE
New RWD (Build a Product Landing Page): Test for fixed nav element is failing with fCC example project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46021]
### Describe the Issue

The test was changed so the example project will fail and the two tests (script and site) are not in sync.

![example-project-nav-bar](https://user-images.githubusercontent.com/28780271/168884649-e3ca5a67-3702-4347-ae31-f2aba72a1262.png)

Also, I think you should be able to pass it using a fixed header.

There are already a few forum posts about this. My guess is people are maybe using or referring to the example code (maybe on Codepen), or they are passing the test using the test script but then failing with the site test.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-product-landing-page-project/build-a-product-landing-page

### Your code

I'm also not sure I understand what is going on with the test. If I set the header to be fixed and set the nav to be relative and move the nav up so its offsetTop is within the valid range it still fails the test.

There is also something odder going on. Use the example code below and make sure your preview pane is above 600px screen width.

1. Comment out the `margin-top: 40px;` inside the `.logo` selector. Test will now pass but the `offsetTop` value on `nav-bar` remains the same with or without it.

2. Keep the `margin-top: 40px;` on `.logo` so the test fails. Make sure you are above 600px screen width. Now uncomment the header media query. It now passes the test and again the `offsetTop` value on `nav-bar` remains the same with or without it.

<details><summary>Code example</summary>

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="styles.css" />
    <title>Document</title>
  </head>
  <body>
    <header id="header">
      <div class="logo">
        <img
          id="header-img"
          src="https://cdn.freecodecamp.org/testable-projects-fcc/images/product-landing-page-logo.png"
          alt="original trombones logo"
        />
      </div>

      <nav id="nav-bar">
        <ul>
          <li><a class="nav-link" href="#features">Features</a></li>
          <li><a class="nav-link" href="#how-it-works">How It Works</a></li>
          <li><a class="nav-link" href="#pricing">Pricing</a></li>
        </ul>
      </nav>
    </header>
    <h2 id="offsetTop"></h2>
    <script>
      window.addEventListener('DOMContentLoaded', (event) => {
        document.getElementById('offsetTop').textContent = `nav-bar offsetTop value: ${
          document.getElementById('nav-bar').offsetTop
        }`;
      });
    </script>
  </body>
</html>

```

```

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  background-color: #eee;
  height: 2000px;
}

li {
  list-style: none;
}

a {
  color: #000;
  text-decoration: none;
}

header {
  position: fixed;
  top: 0;
  min-height: 75px;
  padding: 0px 20px;
  display: flex;
  justify-content: space-around;
  align-items: center;
  background-color: #eee;
}
/* 2. 
 * At > 600px commenting this out makes the test pass again even with margin-top applied to .logo.
 * The offsetTop value on nav-bar remains the same
*/
@media (max-width: 600px) {
  header {
    flex-wrap: wrap;
  }
}

/* 1. 
 * add/remove margin-top to see the test pass/fail. The offsetTop value on nav-bar remains the same
*/
.logo {
  width: 60vw;
  margin-top: 40px;
}
/* 1. */

.logo > img {
  width: 100%;
  height: 100%;
  max-width: 300px;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
  margin-left: 20px;
}

nav {
  /* move the nav position up */
  position: relative;
  top: -20px;
  font-weight: 400;
}

nav > ul {
  width: 35vw;
  display: flex;
  flex-direction: row;
  justify-content: space-around;
}

#offsetTop {
  position: fixed;
  top: 50%;
}

```

</details>

### Expected behavior

The test should pass with a fixed header.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Maybe I'm just being dense, but what is the difference between `top1` and `top2` in the test code? Is there like a scroll between the two that is supposed to take place?

```
const el = document.getElementById('nav-bar')
const top1 = el?.offsetTop
const top2 = el?.offsetTop
assert(!!el && top1 >= -15 && top1 <= 15 && top2 >= -15 && top2 <= 15)
```

Test: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-product-landing-page.md

For reference here is the test script code.

https://github.com/freeCodeCamp/testable-projects-fcc/blob/fcbce226f9c6d589e05493686563e1669c1ca31e/src/project-tests/product-landing-page-tests.js#L240

```
it('The navbar should always be at the top of the viewport.', function () {
  const header = document.getElementById('header');
  const headerChildren = header.children;
  // array of all potential elements serving as a navbar
  const navbarCandidates = [header, ...headerChildren];

  // get the 'top' position value from the element whose value is closest
  // to 0
  function getNavbarPosition(candidates) {
    // by default, set to first candidate's top value
    var candidatePosition = Math.abs(
      candidates[0].getBoundingClientRect().top
    );
    for (var i = 1; i < candidates.length; i++) {
      // if another candidate has a top value closer to 0, replace the
      // old value
      var currentCandidatePosition = Math.abs(
        candidates[i].getBoundingClientRect().top
      );
      if (currentCandidatePosition < candidatePosition) {
        candidatePosition = currentCandidatePosition;
      }
    }
    return candidatePosition;
  }

  assert.approximately(
    getNavbarPosition(navbarCandidates),
    0,
    15,
    '#header or one of its children should be at the top of the viewport '
  );
  window.scroll(0, 500);
  assert.approximately(
    getNavbarPosition(navbarCandidates),
    0,
    15,
    '#header or one of its children should be at the top of the ' +
      'viewport even after scrolling '
  );
  window.scroll(0, 0);
});
```

**Comment by Sboonny** [comment]
Related issue in the forum: [the-navbar-should-always-be-at-the-top-of-the-viewport-is-failing-and-i-don-t-know-why](https://forum.freecodecamp.org/t/number-11-the-navbar-should-always-be-at-the-top-of-the-viewport-is-failing-and-i-don-t-know-why/509068/2). 

I am with changing the test, to make it lenient and I do think `header` with `position: fixed` should pass
