### ISSUE TITLE
Chinese translation of Basic Algorithm Scripting

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4602]
- [ ] Meet Bonfire
- [ ] Reverse a String
- [ ] Factorialize a Number
- [ ] Check for Palindromes
- [ ] Find the Longest Word in a String
- [ ] Title Case a Sentence
- [ ] Return Largest Numbers in Arrays
- [ ] Confirm the Ending
- [ ] Repeat a string repeat a string
- [ ] Truncate a string
- [ ] Chunky Monkey
- [ ] Slasher Flick
- [ ] Mutations
- [ ] Falsy Bouncer
- [ ] Seek and Destroy
- [ ] Where do I belong

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/9
