### ISSUE TITLE
feature to disable auto save when clicking run the code

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46036]
### Is your feature request related to a problem? Please describe.

I wonder if we can add option to disable auto-save when run the code or not provide it as default. It can be a `checkbox` above **Run The Code** `button` that disable saving.

### Describe the solution you'd like

would it be good to add **save** button that run function, instead of automating save when **Run the code** is clicked.

for people who don't need or use it, because for example we use Text-editor, and testing people code from the forum we can disable it.

but the people who need it should know about, so they don't lose their code because they didn't click **Run the Code** before closing the tab, we can disable auto save when clicking **Run the Code** and add a shiny `button` that saves instead.

![image](https://user-images.githubusercontent.com/88248797/168981181-34d4dd78-5586-4ab1-8ce2-75af180f8192.png)
 

### Describe alternatives you've considered

 and I hope to make it will be something resembles codepen **save**  button later, but with different options like a toggle Save on click `Run the code`, or disable save for a day, preview your code in a modal, open console in modal,  
![image](https://user-images.githubusercontent.com/88248797/168982008-4c2eecf7-5cde-49fd-b8db-ec1fc1c1aaf5.png)

### Additional context

I am not saying disable auto save entirely, I just think people who don't need or use it can disable it. and people who need it but leave the editor before clicking **Run The Code** have an option to save their code.

**Comment by ShaunSHamilton** [comment]
@moT01 Do we even have auto save? It is my understanding that we specifically did not add that feature.

**Comment by Sboonny** [comment]
When you click submit code, it's saved🤔

 but I am maybe wrong as I may misremembering. I will recheck when I get back

**Comment by ShaunSHamilton** [comment]
Well, to submit code (for the certification projects), we do need to save the code.

I might be misunderstanding your feature suggestion?

**Comment by Sboonny** [comment]
nope bad wording on my part, english is hard. let me edit it

**Comment by moT01** [comment]
No, we do not have auto-save

Quite sure it works like this:
-save button -> saves to savedChallenges
-run tests -> saves to local storage - there may be some improvements around that we can make - specifically, when we should clear it
-submit challenge -> saves to savedChallenges and completedChallenges + clears local storage

-loading code -> looks in savedChallenges for code first, then local storage

> for people who don't need or use it, because for example we use Text-editor, and testing people code from the forum we can disable it.

So what's happening for you @Sboonny, is you test someones code -> click run -> it saves to local storage. You must not have anything saved for that challenge in the database, so it loads the local storage. I believe this (local storage behavior) is the same as any of the other challenges, you maybe just don't really notice cause you're tending to an influx of issues around the new cert projects - and most other challenges are a few lines of code. The JS cert project would be the other place you would notice it pretty good.

**Comment by Sboonny** [comment]
> I believe this (local storage behavior) is the same as any of the other challenges. 

I do believe so as well, I guess me mentioning terminal modal was unnecessary. 

 I am talking about projects that required for certification.

 If I try to debug someone issue with navbar `position: fixed`, or `media` in portfolio. I don't have to use codepen or lose my original project. To help someone with his.

**Comment by Sboonny** [comment]
-save button -> saves to savedChallenges
-run tests -> saves to local storage - there may be some improvements around that we can make - specifically, when we should clear it
-submit challenge -> saves to savedChallenges and completedChallenges + clears local storage

-loading code -> looks in savedChallenges for code first, then local storage
 
Oh I see more clearly, I wonder if there something. I do in my end to stop it while testing someone code

**Comment by moT01** [comment]
Just test in an incognito window or browser where you are signed out.

**Comment by Sboonny** [comment]
This would work👍💚
