### ISSUE TITLE
Chinese translation of Basic Front End Development Projects

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4603]
- [ ] Get Set for Ziplines
- [ ] Build a Personal Portfolio Webpage
- [ ] Build a Random Quote Machine
- [ ] Build a Pomodoro Clock
- [ ] Build a JavaScript Calculator

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/10
