### ISSUE TITLE
Chinese translation of Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4604]
- [ ] Sum All Numbers in a Range
- [ ] Diff Two Arrays
- [ ] Roman Numeral Converter
- [ ] Where art thou
- [ ] Search and Replace
- [ ] Pig Latin
- [ ] DNA Pairing
- [ ] Missing letters
- [ ] Boo who
- [ ] Sorted Union
- [ ] Convert HTML Entities
- [ ] Spinal Tap Case
- [ ] Sum All Odd Fibonacci Numbers
- [ ] Sum All Primes
- [ ] Smallest Common Multiple
- [ ] Finders Keepers
- [ ] Drop it
- [ ] Steamroller
- [ ] Binary Agents
- [ ] Everything Be True
- [ ] Arguments Optional

**Comment by kkyo22222** [comment]
加總所有範圍內的數字
比較兩陣列
轉換成羅馬數字
人名配對
尋找與取代
兒童黑話
基因字串組合
遺失的字母
布林判斷
找出不重複並保持順序
轉換成html格式
螺旋連接字串

**Comment by erictleung** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/15
