### ISSUE TITLE
More Flexible Configuration of Panels in HTML/CSS Projects

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46058]
### Describe the Issue

Adding the ability for users to more flexibly configure the panels in the may be beneficial. Possible options include:

* Adding a toggle for the instructions/test output (users can do this manually by sliding the width of this panel, but not all users find this adequate) 

* Adding the ability to control how the source and possibly preview panels are laid out. The ability to vertically stack the source tabs would be nice for the projects. I'm not sure if it would work as well for the challenges/steps but it would be nice for the projects.

I'm ambivalent about the first part, but the second would be a nice option.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### System

All

**Comment by nhcarrigan** [comment]
Linking this as partially related: #45950
