### ISSUE TITLE
Stacking code panels and accessible display options

### ISSUE THREAD

**Issue by jinlikegold** [freeCodeCamp/freeCodeCamp#46059]
### Describe the Issue

As a relatively new coder, I’d like to share some feedback for the new editor. After submitting 3 projects for Responsive Web Design the old way, I just finished my 4th after the update.

I do appreciate the way the new editor is more similar to an actual coding environment. However, from an accessibility standpoint, as someone who is neurodivergent and gets overwhelmed by visual processing overload, the new editor is far too crowded visually. The current display options to either hide the html or css or preview, or end up with four columns side by side, don't work well.

### Affected Page

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page

### Your code

```
n/a

```

### Expected behavior

Here are my suggestions:

1) Put the instructions and user stories on a separate page, or have the option to pop them out to a separate tab. I realize this can be done manually, but it's awkward to manually minimize the instruction column, then have to toggle it back out when running tests. Which brings me to...

2) Allow the tests to be minimized when not being run, similarly to how they use to work in Codepen.

3) Consider having multiple stacking options for the code panels, as well as a full page preview. The latter is helpful especially for testing responsiveness.

Lastly, for feedback purposes, there isn't a simple way I can link to the code in the new editor when I post my projects on the forum. If there was an option for others to also see the results and code, that would be best.

Thanks for considering!

### System

- Device: Chromebook
- OS: n/a
- Browser: Chrome
- Version: latest version

**Comment by moT01** [comment]
Thanks for the feedback @jinlikegold 🎉

> ...it's awkward to manually minimize the instruction...

We have [an issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/45950) that will add a button for toggling the instructions. That should help quite a bit

> Allow the tests to be minimized when not being run...

I'm not opposed to that. It would clean up the UI quite a bit

> ...having multiple stacking options...as well as a full page preview...
> ...there isn't a simple way I can link to the code in the new editor...

I like these ideas, they would greatly improve things. They would probably be quite tricky to implement. This editor is new and we will continue to improve things as much as we can. Thanks again for the feedback.

**Comment by lasjorg** [comment]
I wouldn't mind if the default was having the code panels stacked. I also think having a propper tabbed layout would be super nice. Like https://jsfiddle.net > Settings > "Tabs (columns)" and "Right result" for the stacking.

I realize it's easier said than done, just thinking out loud.

**Comment by ahmadabdolsaheb** [comment]
Thank you for your feedback. I have turned some of the points discussed here into actionable items in #46178 and closing this issue as a result. Please refer to #46178 for further discussion.
