### ISSUE TITLE
Sentences ending with code blocks

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46052]
### Describe the Issue

Sentences ending with code blocks are confusing a noticeable portion of users.

For instance,

> Add a comment above the p element with the text `TODO: Add link to cat photos`.

some users are expecting the . to be part of the required text while the tests will not pass with the . as part of the comment text.

### Affected Page

Just looking at the first 15 challenges:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-4
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-8
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-9

Here the period is part of the text:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-3

This is going to touch a lot of challenges...

### Your code

N/A

### Expected behavior

Sentences should not end with code blocks. This will take some time, but someone should tweak the grammar in these new challenges to avoid ending sentences with code blocks where able.

### System

All

**Comment by bbsmooth** [comment]
I'll second this motion. Part of accessibility is attempting to make the content as clear as possible and it becoming obvious in the forum that this is causing unnecessary confusion. One method would be to reword the the sentence:

Add the comment `TODO: Add link to cat photos` above the p element.

Another approach would be to separate the comment completely from the sentence:

Add the following comment above the p element:

`TODO: Add link to cat photos`

The second approach would make it much easier for people using touch devices to copy/paste.

**Comment by jeremylt** [comment]
I like the second approach to fix as well.

**Comment by ojeytonwilliams** [comment]
To ease the burden on translators, it would be good to separate the code block into its own paragraph.  If we just tweak the grammar, that may only fix the English.

**Comment by hvinnieg** [comment]
Yea it would still be a problem I. Other languages should I make a pull request with the fixes?

**Comment by hvinnieg** [comment]
i made a pull request is that what you guys meant by this?

**Comment by jeremylt** [comment]
That's what we were talking about yes, but I'm not sure that we have reached a consensus yet. The issue has not been marked as ready for contribution yet.

**Comment by hvinnieg** [comment]
ok its there if u need it tho if u approve i will do it for the rest of them thought it might help to have an example!

**Comment by moT01** [comment]
I'm not against putting code blocks on their own paragraph, but I think it could potentially look a little rough. Here's what one of the hints on step-2 would look like if we did that:

```
Your
`h2`
element's text should be 'Cat Photos'. Only place the text
`Cat Photos`
between the opening and closing
`h2`
tags.
```

Maybe it needs to be a judgement on a case-by-case basis of what ones to put on their own paragraph. Only the specific text that is problematic?

An alternative might be to change the tests so the period is optional. Specifically, only for the first part of this practice project. Since it's the first project users do, they might not understand that codeblocks are the exact thing they need to add/change/etc - and they will probably pick up on that after half a project or so? I'm just guessing. It's an idea.

**Comment by ojeytonwilliams** [comment]
> Maybe it needs to be a judgement on a case-by-case basis of what ones to put on their own paragraph. Only the specific text that is problematic?

I think that's better than simply moving every bit of code to its own paragraph.

For the example you showed, how about this:

```
Your `h2` element's text should be 'Cat Photos'. Only place the following text:
`Cat Photos`
between the opening and closing `h2` tags.
```

**Comment by bbsmooth** [comment]
I'm not sure the original suggestion was meant to be applied to all of the hints as well? I assumed it was only for the instructions.

**Comment by moT01** [comment]
The open PR changes one of the hints - so I guess I wasn't sure. If we only do it to the instructions, then I would be fine putting that one codeblock on it's own line across these steps - and I think I would lean towards doing that.

**Comment by jeremylt** [comment]
Woops, dropping my phone accidentally pushed a button. 

I personally wasn't thinking of every code tag but rather lengthy verbametem blocks like urls,  required strings, that sort of thing. Sort of how you see it in math textbooks where short things go inline and long things go on a separate line.

**Comment by jeremylt** [comment]
Yeah, starting with the first project is good. I'd do it by putting these long chunks on separate lines so that it's the same across all translation efforts.

**Comment by hvinnieg** [comment]
so what did we decide on?

**Comment by moT01** [comment]
I went through the first chunk of steps. Here are the step numbers and what we should put on its own line:

1 CatPhotoApp
2 Cat Photo
3 Click here to view more cat photos.
 4 TODO: Add link to cat photos
8 https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg 
9 A cute orange cat lying on its back

Stop Here?
17 Cat Lists

These are all/mostly the last thing in the instructions. I think if we change the first few through step 9, we would be alright. There's quite a few more after that, but I'm thinking users will pick up on things by then.

**Comment by hvinnieg** [comment]
i can change them all if u want

**Comment by moT01** [comment]
Go for it @hvinnieg 👍 I would change those up to step 9

**Comment by RandellDawson** [comment]
Maybe things have changed since I worked on the new curriculum, but I thought being more concise was important to keep the instructions box as small as possible.  Creating separate paragraphs for the code definitely makes the overall box taller.

**Comment by RandellDawson** [comment]
> Also, I can't be sure, but I think users may be copy/pasting with the period included which leads them to this problem. I have done that myself - this would stop that.

When I created most of the hint tests, I sometimes would allow the text to contain or not contain a period if text ended in a period.  The more flexible the tests are regarding text (not code), the better.

**Comment by jeremylt** [comment]
That's true, but we have a bunch of users on the forum asking questions because they are including the period at the end of sentences because they mistake them for part of the required text. Lots of people making the mistake means an opportunity to improve the UX.

**Comment by RandellDawson** [comment]
> but there are places where the period changes the symantic meaning of the sentence, like with the url.

In that case, then a change would definitely be needed.

**Comment by moT01** [comment]
hey @RandellDawson 👋

I think the aim of making things concise was more so users didn't have to read so much. This change is the same amount of reading. It does make the box taller - which isn't preferential - but, it's not a whole lot taller.

**Comment by ieahleen** [comment]
Partly related #45897 , where I collected a bunch of strings that have the period in the code block, causing crowding to not divide the sentences.

Maybe we need to decide on a standard?
