### ISSUE TITLE
Chinese translation of JSON APIs and Ajax

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4605]
- [ ] Trigger Click Events with jQuery
- [ ] Change Text with Click Events
- [ ] Get JSON with the jQuery getJSON Method
- [ ] Convert JSON Data to HTML
- [ ] Render Images from Data Sources
- [ ] Prefilter JSON
- [ ] Get Geo-location Data

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/11
