### ISSUE TITLE
Iframe bounces back to top when running tests

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#46061]
### Describe the Issue

There seems to be an issue with the Iframe (this happens when having an Iframe with a scrollbar)

So to reproduce:
1.  scroll down in the Iframe
2. run the tests
3. Iframe pops back to the top

This might be annoying when trying to see the changes you made.

### Affected Page

https://freecodecamp.org/learn/2022/responsive-web-design/

### Your code

```

```

### Expected behavior

When running the test the Iframe should stay in place.

### System

- Device:  Desktop
- OS: Windows 11
- Browser:  Brave
- Version: V1.38.119

**Comment by ahmadabdolsaheb** [comment]
This seems to be a general preview issue and could be reproduced in challenges that have previews(including the legacy certificate) 

In addition to the tests, altering the code in the editor seem to also re render the preview and cause it to scroll to the top.

To reproduce:
1. Visit any responsive web design challenge: https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements
2. past large section of text in the editor
3. scroll the preview
4. alter the code in the editor
5. preview scrolls to the top

**Comment by raisedadead** [comment]
Ah, so this is not even related to the new editor. Thanks for looking into it.

**Comment by moT01** [comment]
We could possibly get the window.offset or something to see how far the preview is scrolled - save it somewhere and then auto scroll to that when re-rendering. That sounds tricky and maybe not worth the effort, but if someone wants to give it a try, go for it.

**Comment by DerrykBoyd** [comment]
> We could possibly get the window.offset or something to see how far the preview is scrolled - save it somewhere and then auto scroll to that when re-rendering. That sounds tricky and maybe not worth the effort, but if someone wants to give it a try, go for it.

I gave this a try. It didn't work out. I needed to jump through some hoops to even get the scroll position from the iframe into the Preview component via a postMessage. But even with that data, I wasn't able to programatically set the scroll position of the iframe on render.

**Comment by saw-jan** [comment]
@Sembauke @moT01 I have created a PR for this with my idea (#47870). What do you guys think? Please, have a look.
