### ISSUE TITLE
Chinese translation of Intermediate Front End Development Projects

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#4606]
- [ ] Show the Local Weather
- [ ] Use the Twitch.tv JSON API
- [ ] Stylize Stories on Camper News
- [ ] Build a Wikipedia Viewer
- [ ] Build a Tic Tac Toe Game
- [ ] Build a Simon Game

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/12
