### ISSUE TITLE
Entering new code after checking a valid solution breaks the lower jaw

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#46062]
### Describe the Issue

The new challenges in https://www.freecodecamp.org/learn/2022/responsive-web-design/ display the wrong UI in certain situations

### Affected Page

All project steps e.g. https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2  

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
2. Complete the step by adding `<h2>Cat Photos</h2>`
3. Click Check your code
4. Go to the editor and type anything
5. See ![image](https://user-images.githubusercontent.com/15801806/169241755-2ed2f605-035f-4d31-a348-feb55173f428.png)
6. Type another character
7. See ![image](https://user-images.githubusercontent.com/15801806/169242010-85581a56-1194-4428-8e15-27396ac12827.png)

### Expected behavior

The editor should say "Submit and go to the next challenge" until the user resets the step.

**Comment by Sembauke** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/45636 might have caused this. 

@nhcarrigan  do you mind looking at this?

**Comment by ahmadabdolsaheb** [comment]
yep, that one did it. The lower jaw need to persist the challengeIsCompleted.
