### ISSUE TITLE
Challenge (Install and Set Up Mongoose): MongoDB Atlas no longer provides the database name with the connection string

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46079]
### Describe the Issue

It seems Atlas changed something. You used to get the database name with the connection string but you don't anymore. The connection string without the database name seems to break with the version of mongoose we require.

`MongoError: database name must be a string`

I think we may need to add a note about this and maybe also update the article that is linked to in the challenge.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/mongodb-and-mongoose/install-and-set-up-mongoose

### Your code

```
NOP
```

### Expected behavior

Clarification on the connection string.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum thread: https://forum.freecodecamp.org/t/mongoerror-database-name-must-be-a-string/509789

**Comment by ShaunSHamilton** [comment]
More might need to be done, but I would alter the final paragraph in the article to:
> Notice that the `<username>` and `<cluster-name>` fields of the URI you copied are already filled out for you. All you need to do is replace the `<password>` field with the one you created in the previous step, and be sure to add the name of your database before the query string.
>
> Example:
> `mongodb+srv://freecodecamp:1234@fcc-cluster.mongodb.net/testdb?retryWrites=true&w=majority`

**Comment by lasjorg** [comment]
How to find the Database name should be included as well as it isn't super intuitive.

> Atlas dashboard under "Deployment" click "Database" now click the "Browse Collections" button.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for pointing this out, @lasjorg, and for the helpful suggestions that you and @ShaunSHamilton made.

I just updated the article based on your suggestions, and made other updates while creating a new Atlas account and cluster. The changes should be live within the next few hours.
