### ISSUE TITLE
Not allowing type attribute in Step 7

### ISSUE THREAD

**Issue by DemonSlayer112** [freeCodeCamp/freeCodeCamp#46078]
### Describe the Issue

In the painting lesson at step 7 we add our stylesheet link, all the other times we did so we added `type="text/css"`
However this time that attribute would claim the test as incorrect.

Correct:
`<link rel="stylesheet" href="./styles.css">`
Incorrect:
`<link rel="stylesheet" type="text/css" href="./styles.css">`

Link: [Rothko Painting - Step 7](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-7)

I assume this isn't intended.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-7

### Your code

```
<link rel="stylesheet" type="text/css" href="./styles.css">
```

### Expected behavior

To have to test complete with or apparently without `type` attribute.

### System

- Device: Desktop, Omen
- OS: Windows 10
- Browser: Chrome
- Version: Not sure

**Comment by Sboonny** [comment]
> I assume this isn't intended.
 
You are right. 👍
Issue file [Rothko file 7](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-the-css-box-model-by-building-a-rothko-painting/60a3e3396c7b40068ad69970.md)

Same issue can be found here

**Comment by moT01** [comment]
I don't think step 1 of the Ferris Wheel project is the same issue. That will pass if you add the `type` attribute. Step 7 of the Rothko project will not. The step 7 should be changed to allow that. What I would do is change the last three tests on that step to match the last two tests of the Ferris Wheel project.

e.g. Replace the last three tests of step 7 with:
````
Your `link` element should have a `rel` attribute with the value `stylesheet`.

```js
assert.match(code, /<link[\s\S]*?rel=('|"|`)stylesheet\1/)
```

Your `link` element should have an `href` attribute with the value `styles.css`.

```js
assert.match(code, /<link[\s\S]*?href=('|"|`)(\.\/)?styles\.css\1/)
```
````

**Comment by Sboonny** [comment]
Tom is right, I had typo mistake. 

I should have double checked my code
