### ISSUE TITLE
Learn HTML Forms by Building a Registration Form - Step 15

### ISSUE THREAD

**Issue by LeandroM07** [freeCodeCamp/freeCodeCamp#46091]
### Describe the Issue

This challenge presents the **prompt of incorrect code, even when the code is actually right**. I figured this out because after pressing ctrl+enter several times when having the right solution and recieving an incorrect code prompt, eventually it gave me the pass to summit and continue.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-16

### Steps to Reproduce

1. Write an acceptable solution for the challenge.
2. Check the code by clicking on the 'Check Your Code' button or by pressing ctrl+enter.
3. Even if the correct is well written and it is an acceptable solution, there would appear that the code is still not right and it will ask to check the code.
4. Without changing the code, keep checking the answer and it will eventually accept it.

### Expected behavior

I expected to recieve the prompt which tells congrats the user and allows him to move forward on the next challenge when the a correct code is provided to the challenge.

### System

- Laptop
- Windows 10
- Mozilla Firefox
- 100.0.1

**Comment by lasjorg** [comment]
I had no issues completing this step. Tested in both Firefox and Chrome.

It might have been a glitch with the backend. The tests at least seem just fine.

**Comment by LeandroM07** [comment]
After sharing my problem I found out that my firefox was one update behind the lastest as I saw the updating prompt when I tried to restart it. Now even if the correct code is written, it doestn't even approve it

**Comment by lasjorg** [comment]
I tested it in Firefox with the latest version `100.0.2` and I have no issues.

![FF-passing](https://user-images.githubusercontent.com/28780271/169625085-61b5b1f1-9664-4b96-adf9-6aae3e65ec63.png)

---

Make sure you do not have any extensions installed that are interfering with the tests.

**Comment by meaghangallant** [comment]
Just want to note for others also stumbling across this: the title says step 15 but the description and given solution are for step 16

**Comment by Senpaiada** [comment]
I've been stuck on step 15 for a couple hours now i keep entering the code but it keeps saying incorrect

**Comment by lasjorg** [comment]
@Senpaiada If you need help with this please use [the forum](https://forum.freecodecamp.org/).

After it has been confirmed to be the correct code and if then the tests are still not passing you can post the code and your system information here in this issue so we can test it.

---

@LeandroM07 Is this issue for step 15 or 16? Your title and link do not match.

I have tested both steps in Firefox and the correct code is passing the tests.

**Comment by ieahleen** [comment]
As no one has been able to reproduce this issue, I am closing this.

If this issue presents again, this can be reopened.
