### ISSUE TITLE
Add Project name on timeline for new RWD

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#46109]
### Is your feature request related to a problem? Please describe.

At the moment when visiting my timeline I have no clue what project I completed as it only shows steps and not the project name:
![image](https://user-images.githubusercontent.com/46919888/169702293-c5a22a3c-de9f-4b66-8ada-1c8f4979d22a.png)

### Describe the solution you'd like

For the new RWD certification the project name should also be shown on the timeline.

### Describe alternatives you've considered

None

**Comment by moT01** [comment]
I'm in favor of this. Wonder if we should use the full title or a short version.

`Learn HTML by Building a Cat Photo App - Step 1`
or
`Cat Photo App - Step 1`

I kind of like the second version - the long titles would probably mostly push the text onto a second line. I'm fine with it either way.
