### ISSUE TITLE
Missing semicolons

### ISSUE THREAD

**Issue by Rubenkl** [FreeCodeCamp/FreeCodeCamp#4610]
Challenge [Bonfire: Drop it](http://www.freecodecamp.com/challenges/bonfire-drop-it?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20%0A%20%20%20%2F%2Fcan%27t%20use%20arr.length%20anymore%20in%20the%20for-loop%2C%20because%20it%20changes%0A%20%20var%20leng%20%3D%20arr.length%3B%0A%20%20var%20temparr%20%3D%20%5B%5D%3B%0A%20%20for%20(i%3D0%3B%20i%3C%20leng%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(func(arr%5Bi%5D))%20%7B%20%0A%20%20%20%20%20%20temparr.push(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%20else%7B%20%2F%2Fif%20func%20evaluates%20to%20FALSE%0A%20%20%20%20%20%20arr.shift()%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20temparr%3B%0A%20%20%0A%0A%7D%0A%0Adrop(%5B1%2C%202%2C%203%2C%207%2C%204%5D%2C%20function(n)%20%7Breturn%20n%20%3E%203%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The assignment checks 5 different examples if the anwers match. However, there are semicolons missing in the last 2 examples:
```javascript
drop([1, 2, 3, 7, 4], function(n) {return n > 3})
```
Should be:
```javascript
drop([1, 2, 3, 7, 4], function(n) {return n > 3;})
```

(same for the last example)

**Comment by SaintPeter** [comment]
Confirmed.  The semicolons are missing from both the display and the test code.  This doesn't actually stop the code from working.  Technically semi-colons are optional in Javascript.  However, we strongly encourage their use.  

Someone can file a quick PR to fix this.

**Comment by nuku89** [comment]
I can help. I'll make a PR from staging if that sounds a o.k.

**Comment by SaintPeter** [comment]
@nuku89 Be sure to read the [Contributor Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)
Looking forward to the fix.
