### ISSUE TITLE
Challenge (Learn HTML by Building a Cat Photo App - step-3): parentheses around element type is confusing some people

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46111]
### Describe the Issue

I have seen a few people misinterpreting the (`p`) in the challenge text as actual syntax. It might be better to remove the parentheses?

> Paragraph (`p`) elements are used to create paragraph text on websites.
> 
> Create a paragraph (`p`) element below your `h2` element, and give it the text Click here to view more cat photos.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-3

### Your code

```
nop
```

### Expected behavior

The syntax for the `p` and `h2` elements should be presented the same way.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum:
https://forum.freecodecamp.org/t/cant-seem-to-get-step-3-right/510187
https://forum.freecodecamp.org/t/need-a-step-or-guide-on-step-3-of-cat-photo-app/510648

**Comment by bbsmooth** [comment]
Possible alternative instructions:

The `p` element is used to create a paragraph of text on websites. Create a `p` element below your `h2` element and give it the following text:

`Click here to view more cat photos`

**Comment by UCYLMZ** [comment]
Is it ok if i just remove pharentheses? As i remember, i saw that presenting before in other courses. I think it is not confusing at all.

**Comment by jeremylt** [comment]
I like avoiding the issue by rewording per @bbsmooth's suggestion above.

**Comment by lasjorg** [comment]
Here is another one.

https://forum.freecodecamp.org/t/emphasazing-the-word-love/511942
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-24

**Comment by ieahleen** [comment]
as the step in question doesn't have anymore an element name in parenthesis, I am closing this issue as fixed. If this is not correct, please ask to reopen the issue again.
