### ISSUE TITLE
Revise instructions for step 6 of Cat Photo App

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#46110]
### Describe the Issue

Step 6 of the Cat Photo App has been coming up a lot in the past few days on the forum. 
https://forum.freecodecamp.org/search?expanded=true&q=step%206%20cat%20photo%20app%20indent

The instructions make sense to me when I read it, but there is still a disconnect with beginners on how to go through this challenge. 

Would it help to add a sentence like this? 🤷‍♀️ 
In front of each element, press spacebar twice or hit tab once. 

Thoughts?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6

### Your code

N/A

### Expected behavior

N/A

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bbsmooth** [comment]
The hint says:

"Your `h2` element should be below the `main` element's opening tag and its opening tag should start 6 spaces over from the start of the line."

If we are telling them in the hint that it should be indented 6 spaces then maybe we should just say that in the instructions too.

**Comment by jeremylt** [comment]
Checking for 4+ spaces would mean the starter code would pass - that doesn't seem like a great idea. I'd be fine with 6+ spaces passing, but I think the wording is the real issue. Perhaps an example is needed?

**Comment by Sboonny** [comment]
> Perhaps an example is needed

Nope it's typo from me😅, nice catch

**Comment by jeremylt** [comment]
No, I mean perhaps the learner needs an example?

**Comment by jdwilkin4** [comment]
Providing an example for the learner might be the way to go.
That way if they don't understand the text 100%, then they can just look to the example.

Maybe showing something like this:
```
<ul>
  <li>example 1</li>
  <li>example 2</li>
  <li>example 3</li>
</ul>
```
I have provided that example on the forum a few times and the learner usually is able to pass the test afterwards.

**Comment by Sboonny** [comment]
I am in favour of the example idea as well

**Comment by jdwilkin4** [comment]
@RandellDawson 
In my experience, the confusion comes in with the actual word indenting.
Most of the posters will ask what is indenting? How to do it?
Even with the hint of indented 6 spaces, users are still confused.

As a native english speaker, I hear the word indenting and immediately understand what it means.
But I think for those where english is not their first language, there is confusion on what indenting means.

If we were to just change the wording, then we can say something more explicit like 
"move each element over two spaces to the right"

or something like that
