### ISSUE TITLE
Invalid parameters on Wiki solutions

### ISSUE THREAD

**Issue by grawlinson** [FreeCodeCamp/FreeCodeCamp#4612]
[Reference](https://www.reddit.com/r/FreeCodeCamp/comments/3tp3yx/please_explain_this_rule_passing_a_defaultfalse/) & [fix](https://gist.github.com/grawlinson/a27c1f4db7ff0d87f892) for the two files.

Summary:

```
function repeat(str, num) {
  var newstr = [];
  for (var i = 0; i < num; i++) {
    newstr.push(str);
  };
  return newstr.join('');
}

repeat("abc", 3, "");

```

The first usage of the repeat/chunk function has 3 parameters passed to it, as well as having a semicolon at the end of the for loop.

**Comment by grawlinson** [comment]
Note: I originally wanted to fork the FCC Wiki, make changes, then make a PR. However, the process is quite convoluted so I ended up just filing a ticket instead. Hopefully GitHub gets around to fixing that particular problem.

Here is a fork of the Wiki repo with my changes. Whoever gets around to merging my changes will have to do it [manually](https://gist.github.com/larrybotha/10650410).

**Comment by BerkeleyTrue** [comment]
What is the issue?

**Comment by grawlinson** [comment]
The third parameter doesn't actually do anything, so why is it there?

**Comment by bugron** [comment]
Closing this issue as it is fixed in https://github.com/FreeCodeCamp/wiki/pull/111.

**Comment by grawlinson** [comment]
Not closed properly, I just submitted a PR that hopefully fixes the issue.

Apologies for posting on the wrong repo, I didn't realise that wikis had their own repo. My mistake.
