### ISSUE TITLE
Cafe Menu 53 - Bad Code Passing

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46125]
### Describe the Issue

This code should fail but actually passes.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-53

### Your code

```
<article class="item">
  <p class="dessert">Donut</p><p class="price">1.50</p><p class="dessert">Cherry Pie</p><p class="price">2.75</p><p class="dessert">Cheesecake</p><p class="price">3.00</p><p class="dessert">Cinnamon Roll</p><p class="price">2.50</p>
</article>
```

![image](https://user-images.githubusercontent.com/25011573/169868524-d52b658f-4e33-43e2-9e3a-31cfae6c90c9.png)

### Expected behavior

This code should fail.

**Comment by jeremylt** [comment]
Woops, dupe of
https://github.com/freeCodeCamp/freeCodeCamp/issues/45940

**Comment by Arerib** [comment]
<article class="item">
            <p class="dessert">Donut</p><p class="price">1.50</p>
          </article>
          <article class="item">
        <p class="dessert">Cherry pie></p><p class="price">2.75</p>
        </article>
        <article class="item">
        <p class="dessert">cheesecake></p><p class="price">3.00</p>
        </article>
      <article class="item">
    <p class="dessert">Cinnamon Roll></p><p class="price">2.50</p>
        </article>
