### ISSUE TITLE
Improve multifile cert project preview

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#46126]
### Is your feature request related to a problem? Please describe.

There's been a few comments on issues and other areas about how we could improve things with the multifile editor, and specifically, the cert projects using it. One of the issues is that the preview is stuck in the preview pane. You can't resize it very well to see responsiveness, and it takes up a lot of space.

### Describe the solution you'd like

I dug around a little and found this: https://codepen.io/davidgilbertson/pen/xPVMqp. It opens a component in a new window. I propose making the preview behave this way for the new cert projects. Then users can see the responsiveness of their project and have more space for the instructions and code.

**Comment by ojeytonwilliams** [comment]
This sounds like a great addition.  How about implementing it as a toggle, a bit like devtools?  So, just have a button to detach/attach the preview.
