### ISSUE TITLE
New RWD: lack of consistency with stylesheet type attribute

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46137]
### Describe the Issue

One challenge asked for the `type` attribute and one doesn't. Given the current best practice is to _not_ include it for CSS I'd suggest removing it from "building a cafe menu - step-17".

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-17

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-7

> [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-type)
> This attribute is used to define the type of the content linked to. The value of the attribute should be a MIME type such as text/html, text/css, and so on. The common use of this attribute is to define the type of stylesheet being referenced (such as text/css), **but given that CSS is the only stylesheet language used on the web, not only is it possible to omit the type attribute, but is actually now recommended practice. It is also used on rel="preload" link types, to make sure the browser only downloads file types that it supports.**

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-7

### Your code

```
<link rel="stylesheet" href="styles.css" />
```

### Expected behavior

Consistency between the two challenges and the likely removal of the `type` attribute.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/step-7-rothko-painting/511284

**Comment by nhcarrigan** [comment]
I honestly had no idea it wasn't best practise anymore.

I agree, we should remove this from the instructions and the following steps' seed code.

However, we should still allow it in the tests (not require it) as it is technically valid HTML.
