### ISSUE TITLE
Unable to interact with editor (Waypoint: Filter Arrays with filter)

### ISSUE THREAD

**Issue by Nate-Sanchez** [FreeCodeCamp/FreeCodeCamp#4613]
The editor frozen on this particular exercise. I can highlight, but cannot erase or add anything.

Browser specs:
Safari version 9.0.1 (10601.2.7.2)

**Comment by Nate-Sanchez** [comment]
Problem has been resolved. No idea how.

**Comment by BerkeleyTrue** [comment]
Happy Coding!
