### ISSUE TITLE
Improve Step 43 & 46 because of confusion?

### ISSUE THREAD

**Issue by JonathanL03** [freeCodeCamp/freeCodeCamp#46146]
**Describe the bug**
I dont know if this is supposed to be like this but in the new Responsive Web Design Course in step 43 and also in step 46 when the radio buttons are introduced, you need to have a space between the input element and the text 'Indoor' and 'Outdoor'.

Wrong: 
![grafik](https://user-images.githubusercontent.com/94629778/170233649-8a6727fb-21b4-4631-a586-3d09e31aa69e.png)

Right: 
![grafik](https://user-images.githubusercontent.com/94629778/170233785-a657d7a5-0467-485f-a9c0-fbfd6677c7ef.png)

Maybe this should be changed, since it did confuse me quiet a bit.

**Comment by JonathanL03** [comment]
Adding to the post, it does work in the preview but seems to be a case of your own opinion what looks better :)

**Comment by RandellDawson** [comment]
Since the step instructions do not explicitly state to add a space between the radio button and the text, I am actually inclined to change the instruction to just:

> The text ` Indoor` should be located to the right of your `radio` button.

Then, the test could be modified to accept a no space, one space, or multiple spaces between the radio button and the text `Indoor`.   If we really want the space, then the step instructions would be something like:
> Before the text input, add a radio button with the option `Indoor`. Put a space between the button and the option text.

**Comment by jeremylt** [comment]
I think we want the space but should be flexible on how many spaces the user adds.

**Comment by RandellDawson** [comment]
> I think we want the space but should be flexible on how many spaces the user adds.

I believe the current test already does that.  So if that is what you think, then I think the instructions for the step should specify the space requirement instead of relying on a hint.

**Comment by amde-et** [comment]
<Indoor input type="radio"> type="text" name="catphotourl" placeholder="cat photo URL" required>

**Comment by bhanu2209** [comment]
The text  Indoor should be located directly to the right of your radio button. Make sure there is a space between the element and the text. You have either omitted the text or have a typo.

**Comment by jeremylt** [comment]
Please don't necro old issues
