### ISSUE TITLE
Need to add additional instructions to step 12 of Learn HTML by Building a Cat Photo App

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#46140]
### Describe the Issue

In step 12 of the **Learn HTML by Building a Cat Photo App**, the following two line numbers 7 & 8 exist at the start of the step:
```
      <p>Click here to view more cat photos.</p>
      <a href="https://freecatphotoapp.com">cat photos</a>
```
The instructions tell the user to make the text `cat photos` that appears inside the sentence of the `p` element a link.  The instructions do not explicitly state to remove the existing anchor element that is below the `p` element.  Instead, it just has a last sentence that says `There should only be one link showing in the app.`.  Step 13 starts off only showing the following for line 7:

```
<p>Click here to view more <a href="https://freecatphotoapp.com">cat photos</a>.</p>
```
The original link that appeared in step 12 is gone.

In my opinion, an easy solution is to just change the last sentence in step 12 to:
```
Make sure to remove the link `cat photos` that originally appeared below the `p` element.
```
OR
```
Make sure to remove the link `cat photos` that appears below the `p` element.
```

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

n/a

### Expected behavior

n/a

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by codad5** [comment]
> There should only be one link showing in the app.

I think this instruction above is enough to tell what the end result should be

**Comment by bbsmooth** [comment]
> I think this instruction above is enough to tell what the end result should be

But it doesn't appear to be as this particular step comes up a lot in the forums. I agree with @RandellDawson, we need to make this a little clearer. If the intent is for the user to remove the existing link below the `<p>` then I think we should tell them exactly that. Here's my attempt at making the instructions clearer:

1. Turn the words `cat photos` in the `p` element into a link using the same value for the `href` attribute as the link below the `p` element.
2. Delete the link below the `p` element.

I'm not sure what the purpose of this step is, so my instructions may be unwittingly stepping on the goal here.

**Comment by Sboonny** [comment]
I think a better word is `replace` than `remove` in `Make sure to remove the link `cat photos` that appears below the `p` element`, but that's nitpicking.

I do fully agree changing the hint.

**Comment by jeremylt** [comment]
We're also teaching vocabulary here. I would use slightly more consistent language with the previous steps:

> Make sure to remove the `a` element with the text `cat photos` on the line below the `p` element.
