### ISSUE TITLE
Unclear directions in New HTML/CSS Building A Quiz Step 9

### ISSUE THREAD

**Issue by bellhuffstutler** [freeCodeCamp/freeCodeCamp#46151]
### Describe the Issue

I saw this on the forum, and checked for myself because I was already where they were, so I figured I would just send in an issue about it. 

On step 9 of the Building A Quiz section (https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-9) it goes over ratio, however it shows the standard formatting for ratios (35:4) and wraps it in the same formatting that is typically used when the thing should be typed in or pasted exactly the same. 

This is an issue because if you type it in as you would having gone through the rest of the course to this point, you get an error that you have no solution to (and are forced to go off-site to figure out why it's not working)

![image](https://user-images.githubusercontent.com/106115808/170320599-785c7f40-1ccf-475d-9b4d-7e47ca60d20b.png)

The hint simply says "You should use this aspect-ratio property" which i clearly am, leading to confusion and frustration because there's no indication of what's wrong because of how the original aspect ratio was labelled. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-9

### Your code

```
#logo {
  width: max(100px, 18vw);
  background-color: #0a0a23;
	aspect-ratio: 35:4;
	padding: 0.4rem;
}
```

### Expected behavior

I either expected 35:4 to work, or for either the error or the step to let me know the correct formatting is "35/4"

### System

- Device: Desktop
- OS: EndevourOS
- Browser: Firefox
- Version: 100.0.2

**Comment by bellhuffstutler** [comment]
Honestly that sounds perfect to me! 

Main issues are just using the code fomatting in a way they have never been used before, and the hint being absolutely no help in figuring out why the issue is happening

**Comment by lasjorg** [comment]
Side note: How come we have an external link in this challenge? I thought we didn't want those.

**Comment by bellhuffstutler** [comment]
Wait where? I don't remember there being one at all

**Comment by lasjorg** [comment]
I'm talking about the link to the style guide. I just mean external as in it takes you away from the challenge, not external as in off-site.

**Comment by bellhuffstutler** [comment]
Oh!

Good point I'm not sure haha

**Comment by lasjorg** [comment]
I just thought links were seen as distractions, no matter where they take you. But I guess if the point of the challenge is to follow a style guide it kind of has to be posted.

Probably just out of the loop on this one.

**Comment by Crissyukbr** [comment]
Hello all... forgive me if I make any mistake here as it's my first time  using Git ... 
I need help with the topic above, please. I have noticed that the question has been adjusted by FreeCodeCamp but I am getting the same error message with my CSS code below. I don't understand where the error is, what am I doing wrong?

#logo {
  width: max(100px, 18vw);
	background-color: #0a0a23;
	aspect-ratio: 35 / 4;
	padding: 0.4rem;
}

Thanks
Crissy

**Comment by ieahleen** [comment]
@Crissyukbr please use the forum for asking for help, the Ask for help buttn is there just for this
