### ISSUE TITLE
I think there's a problem with the sample code on that page, since it returns a decimal, rather than a whole number. I managed to complete the challenge after changing line 7 to read "return randomNumberBetween0and9;". 

### ISSUE THREAD

**Issue by kdough03** [FreeCodeCamp/FreeCodeCamp#4616]
Challenge [Waypoint: Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript?solution=var%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0Avar%20randomNumberBetween0and9%20%3D%20Math.floor(Math.random()%20*%2010)%3B%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20randomNumberBetween0and9%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var randomNumberBetween0and19 = Math.floor(Math.random() * 20);
var randomNumberBetween0and9 = Math.floor(Math.random() * 10);
function myFunction() {

  // Only change code below this line.

  return randomNumberBetween0and9;

  // Only change code above this line.
}

```

**Comment by SaintPeter** [comment]
You need to make the changes where it asks you to make the changes:
```js
  // Only change code below this line.

  return Math.random();   // Modify THIS line to change how the random number is generated

  // Only change code above this line.
```

You can ask for help in our [Help Chat Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link). 

I am closing this issue since it is not a problem with the site.

Thanks and happy coding!
