### ISSUE TITLE
New RWD (cafe menu step-14/15), correct selector type in text, reorder tests

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46163]
### Describe the Issue

Forum thread for context: https://forum.freecodecamp.org/t/need-help-understanding-this-styles-css-file/511315

Here the camper does not combine the selectors into a list and is given this hint.

> Your `styles.css` file should have the `h1, h2, p` type selector.

---

## Step 14 ✅ done

> You now have three type selectors with the exact same styling. You can add the same group of styles to many elements by separating the selectors with commas like this:
> ```
> selector1, selector2 {
>   property: value;
> }
> ```
> Use a single type selector to center the `h1`, `h2` and p elements at the same time.

We are not using the correct term for the selector `h1, h2, p`. It is a [selector list](https://developer.mozilla.org/en-US/docs/Web/CSS/Selector_list), not a type selector. Each selector in the list happens to be a type selector. A single type selector is `h1` or `h2` or `p`, not `h1, h2, p` that is a selector list.

### Proposed change:

> You now have three type selectors with the exact same styling. You can add the same group of styles to many elements by creating a list of selectors. Each selector is separated with commas like this:
> ```
> selector1, selector2 {
>   property: value;
> }
> ```
> Use a selector list to center the `h1`, `h2` and `p` elements at the same time.

## Step 15:

Your `styles.css` file should have the `h1, h2, p` type selector.

```js
(getUserInput) => {
  assert(getUserInput('editableContents').replace(/[\s\n]*/g, "").match(/(h1|h2|p),(h1|h2|p),(h1|h2|p){/));
}
```

You should only have one selector.

```js
(getUserInput) => {
  assert(getUserInput('editableContents').match(/text-align:\s*center;?/)?.length === 1);
}
```

### Proposed change:

1. Move the single selector test up in the test order.
2. Correct the selector terminology to "selector list".
3. Add a new test that checks the `style` element was removed.

You should only have one selector.

```js
(getUserInput) => {
  assert(getUserInput('editableContents').match(/text-align:\s*center;?/)?.length === 1);
}
```

Your `styles.css` file should have the `h1, h2, p` selector list.

```js
(getUserInput) => {
  assert(getUserInput('editableContents').replace(/[\s\n]*/g, "").match(/(h1|h2|p),(h1|h2|p),(h1|h2|p){/));
}
```

Exclude the opening and closing `style` tags.

```
assert(test for style tags)
```

### Affected Page

two (or more?)

### Your code

```
nop
```

### Expected behavior

Correct selector type. Reordering tests in step 15 may also help so the single selector hint comes before the selector check.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-14
curriculum\challenges\english\14-responsive-web-design-22\learn-basic-css-by-building-a-cafe-menu\5f3477ae34c1239cafe128be.md

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-15
curriculum\challenges\english\14-responsive-web-design-22\learn-basic-css-by-building-a-cafe-menu\5f3477aefa51bfc29327200b.md

**Comment by UCYLMZ** [comment]
I have two beatiful commits for this issue because of there are two steps. Should i merge them or open PR seperately. Or not both :)

**Comment by lasjorg** [comment]
@UCYLMZ I'd like to hear what people have to say about switching the test order for step 15. But we definitely need to correct the selector terminology.

If you want to do the change for step 14 first and then wait until we hear back with some opinion on the test order of step 15 that would maybe be the way to go. Or you can wait for the feedback and do them both in one PR if/when a consensus is reached.

**Comment by UCYLMZ** [comment]
I missed the link at the top. Sorry about it. I'm opening a PR for step 14 for now and pending for step 15. Thank you for your time. @lasjorg

**Comment by Sboonny** [comment]
About step 15:

I agree hints and description should be changed, and they should account for added HTML tags as well. 

![image](https://user-images.githubusercontent.com/88248797/171029619-b3d71c07-c97e-4a31-9347-825f7ce43d2c.png)

```css
<style>
h1, h2, p {
        text-align: center;
      }
</style>
```

the code above shouldn't pass,

**Comment by lasjorg** [comment]
I agree, we should test that the style element has been removed as well.

**Comment by ShaunSHamilton** [comment]
The suggestions in the first post sound like a plan.

---

An issue with the _help wanted_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
