### ISSUE TITLE
Confusing step-by-step directions on this challenge.

### ISSUE THREAD

**Issue by ejm2172** [FreeCodeCamp/FreeCodeCamp#4618]
Challenge [Waypoint: Create a Block Element Bootstrap Button]

Hey- text instructions on this page do not make it clear that you would like two separate lines of code.

Currently they make users think they need to apply class="btn" class "btn-block" in the step by step direction.  I

<img width="327" alt="screen shot 2015-11-21 at 6 07 29 pm" src="https://cloud.githubusercontent.com/assets/15882084/11320960/bf8f20e4-907a-11e5-99f1-0c08486c9002.png">
 figured it out by looking at the visual provided in the instructions.

**Comment by SaintPeter** [comment]
You mean you think it makes users think they need to do:
`<button class="btn" class="btn-block">` 
as opposed to 
`<button class="btn btn-block">`?

**Comment by ejm2172** [comment]
Yep!

**Comment by ltegman** [comment]
All the instructions ask is that your button have two classes. It is mentioned earlier in the curriculum that multiple classes are added to elements by using one class attribute and putting spaces between the different classes so I don't see this as a problem.

Thanks and happy coding!
