### ISSUE TITLE
Translation words Spanish

### ISSUE THREAD

**Issue by Oxyrus** [FreeCodeCamp/FreeCodeCamp#4619]
Which convention should we use for the word "camper" when translating to the Spanish?

**Comment by bugron** [comment]
@Oxyrus thanks for posting this issue!
I think this question should go to https://gitter.im/AlexTrapp/FreeCodeCampEspa%C3%B1ol. Closing.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
