### ISSUE TITLE
New RWD: Missing full stops/periods in Registration Form project instructions.

### ISSUE THREAD

**Issue by deagloria** [freeCodeCamp/freeCodeCamp#46195]
### Describe the Issue

Please add full stops/periods to the sentences in the Registration Form project! This is like the written word equivalent of not closing tags! :rofl:

This affects Step 6 and Step 24.

“Please fill out this form with the required information.”
“I accept the terms and conditions.”

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-6, https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-24

### Steps to Reproduce

None. Visit affected pages at https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-6
and
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-24

### Recommended fix or suggestions

Step 6: “Please fill out this form with the required information.” instead of “Please fill out this form with the required information”
Step 24: “I accept the terms and conditions.” instead of "I accept the terms and conditions"

**Comment by deagloria** [comment]
Sorry this should probably be under curriculum instead of bug, but I don't know how to change the label.

**Comment by Aarushi5g** [comment]
Hello, can I take up this issue?

**Comment by Sboonny** [comment]
the tests check if the code has `I accept the terms and conditions`, and `Please fill out this form with the required information`. 

If we plan to add periods we need to change the test to account for that periods as well

**Comment by moT01** [comment]
I commented on the PR. I don't think this change is necessary - but I guess if someone wants to do the work, I don't mind it either.

**Comment by raisedadead** [comment]
I am going ahead and closing this. Thanks for taking the time to report this.
