### ISSUE TITLE
Relational Database (Beta) - Bug with the Terminal in 'mkdir' test

### ISSUE THREAD

**Issue by bellhuffstutler** [freeCodeCamp/freeCodeCamp#46215]
### Describe the Issue

So I already know how to use BASH pretty well, because I use Linux as my daily driver, and I made a typo when it wanted me to make a directory for "website" 

so just did `mv websitre website` to change the name, and the ls shows the correct name, but the test isn't working (I'm assuming it's looking for me to *specifically* put in `mkdir website`) 

![image](https://user-images.githubusercontent.com/106115808/170842501-9878c716-6602-4df7-896c-2c02fd768d8b.png)

this is a screenshot with the last commands and the fail from the test, even after hitting Ctrl+Enter to try and get it read again. 

It's probably not an immediate issue, but it is definitely a bit jarring for someone at least already slightly familiar with terminal and BASH because mv is one of the first things you tend to pick up

EDIT: So i went to reset the lesson, and it also doesn't clear out the already moved directory, so as far as I can tell the only solution to this issue at the moment is to `rm -rf website` and then `mkdir website` again

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate

### Your code

```
mkdir websitre
mv websitre website
```

### Expected behavior

Expected for the program to see the new "website" directory in the project folder and continue the lesson

### System

- Device: Desktop
- OS: EndevourOS
- Browser: Opera
- Version: 87.0.4390.25

### Additional context

I have attempted a few different similar typo issues now in other parts of the lesson, this is definitely just a case of the test is checking for the input, not the actual filenames. 

Which is confusing if you have typos and try to fix them. If there was a way to make it so the test would look for the existence of the files when the student presses Ctrl+Enter to redo the test check, that would likely fix the problem

**Comment by bellhuffstutler** [comment]
makes sense, but shutting off commands that should cause a pass to make it less likely for people to use GUI to cheese it seems weird to me? But i'm not familiar with how any of this particular thing is set up, so I'm not going to push I just wanted to bring it to people's attention in case it was actually a bug and not an intended feature. If it's an intended feature we could probably just close it then, and deal with it when it's out of beta if it does end up confusing people?

**Comment by Sboonny** [comment]
> But i'm not familiar with how any of this particular thing is set up

Here is the [markdown file](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md#850-make-directory), you can find it in its repo [main branch](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate). If you open the [1.0.2v branch](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/tree/v1.0.2), you will find the [850.test.js](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/v1.0.2/freeCodeCamp/test/850.test.js) in it.

If you want to contribute in the other hand, you can check this [use coderoad](https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad)

**Comment by bellhuffstutler** [comment]
Thanks! I'll check it out!

**Comment by bellhuffstutler** [comment]
```
describe('tests', () => {
  it('should pass', async () => {
    const websiteDirectory = await getDirectoryContents('../website');
```

It already has it, but it's looking for the wrong folder.

When you make the website folder, you're in Projects already, so the `../` at the beginning will check outside of that folder, the one with `Project` and `swift-5.6.6-RELEASE-ubuntu20.04` in it. I'll work on a fix and see if the checks for the other tests do that. 

Also, I went back into the course, and i have no lesson it's just the VSCode, so I'm not sure what to do, but i'll chalk that up to being weird atm.

**Comment by Sboonny** [comment]
> It already has it, but it's looking for the wrong folder.
> 
> When you make the website folder, you're in Projects already, so the `../` at the beginning will check outside of that folder, the one with `Project` and `swift-5.6.6-RELEASE-ubuntu20.04` in it. I'll work on a fix and see if the checks for the other tests do that.

You are totally right

> Also, I went back into the course, and i have no lesson it's just the VSCode, so I'm not sure what to do, but i'll chalk that up to being weird atm.

There was no need for that. This is embarrassing, but I linked the wrong file here is [280 markdown](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md#280-make-directory), and here is its [280.test.js](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/v1.0.2/freeCodeCamp/test/280.test.js).

**Comment by bellhuffstutler** [comment]
I was actually about to edit my comment to say the one i was looking for was actually 280 now that I'm going through everything haha 

So, with 280.js it seems like it's literally as simple as changing this `&&` to a `||` unless i'm real dumb:

```
    assert(projectDirectory.indexOf('website') >= 0 && lastCommand[0] === 'mkdir' && /website/g.test(lastCommand[1]));
```

That way it'll check if there is either a folder called "website" in the Projects folder, or if you did the command

I mean, we could even do something like: 

```
const assert = require('assert');
const { getLastCommand, getDirectoryContents } = require('./utils');

describe('tests', () => {
  it('should pass', async () => {
    const projectDirectory = await getDirectoryContents('../project/website');
    const lastCommand = await getLastCommand();

    assert(projectDirectory.indexOf('website') >= 0 || lastCommand[0] === 'mkdir' && /website/g.test(lastCommand[1]));
  });
});
```
If I'm reading everything correctly

**Comment by Sboonny** [comment]
```js
     assert(projectDirectory.indexOf('website') >= 0 && lastCommand[0] === 'mkdir' && /website/g.test(lastCommand[1]));
```

Doing this will make your attempt pass, but it will undermine Tom concerns. If I am not misunderstanding the code above.

> that is intentional so that users can't click around the GUI to create/move/delete things.

We can merge your idea with the original intent, to make your attempt pass.

for example

```js
const checkMV = projectDirectory.indexOf('website') >= 0 && lastCommand[0] === 'mv' && /website/g.test(lastCommand[1])
const checkMkdir =projectDirectory.indexOf('website') >= 0 && lastCommand[0] === 'mkdir' && /website/g.test(lastCommand[1])
assert(checkMkdir || checkMV);
```

**Comment by Sboonny** [comment]
> My only real issue is I have no idea how to test these, because they're in a completely seperate repo than the actual freeCodeCamp local instance and I'm not sure how to set it up. I'll go through the other ones and see if there's anything I notice in those and just leave myself notes though

Unfortunality, I didn't need to test script in RDB yet, but you can check [freecodecamp chat](https://chat.freecodecamp.org/channel/contributors)

**Comment by bellhuffstutler** [comment]
oh that's a really smart way to do it and it locks out GUI modifying! 

I need to finish the javascript course so I know I can do that lmao 

but yeah no that looks like a correct way to do it and I can just see if there are any other lessons that particular code would work in 

also thanks for the link! I'll do that

**Comment by bellhuffstutler** [comment]
Yeah it can work for all of them like: 

```const assert = require('assert');
const { getLastCommand, getDirectoryContents } = require('./utils');

describe('tests', () => {
  it('should pass', async () => {
    const websiteDirectory = await getDirectoryContents('../website');
    const lastCommand = await getLastCommand();
    const checkTouch = websiteDirectory.indexOf('styles.css') >= 0 && lastCommand[0] === 'touch' && /styles\.css$/.test(lastCommand[1]);
    const checkMV = websiteDirectory.indexOf('website') >=0 && lastCommand[0] === 'mv' && /styles\.css$/.test(lastCommand[1]);
    
    assert(checkTouch || checkMV);
  });
});
```

Should I just go through and make those changes or ask about it in chat?

**Comment by moT01** [comment]
I don't think any of these tests need changing in this way - the instructions tell you what command you're supposed to use. What about using the copy command, that would pretty much be the same - do we add a third check? What other commands can be used to get that folder or file to exist? We can't add a check for all of them. The tests aren't like that only so users can't use the GUI, they're supposed to use the specific command being taught or asked of them. Many people have gone through these, and I don't think I've seen this come up before. I appreciate the interest here, but I don't think we would add those changes.

**Comment by bellhuffstutler** [comment]
Why would we ever need the cp command in this instance though? 

mv for rename is super common and a thing that people do quite often using BASH it just seems super weird to cause it to fail when the fix is so easy, and someone else is offering to put in the work to make it feasable? 

But, it's your project, I was just mentioning an issue that I had, and we came to a solution, I can't make you implement it or let me implement it so i guess that's where we end this

**Comment by moT01** [comment]
> Why would we ever need the cp command in this instance though?

Maybe they don't know the mv command. You're right, mv is common for renaming. I just don't think these changes are necessary - and this seems quite rare. The instructions are to use `mkdir website`, not with a typo and then use mv to rename it.

This is my opinion anyway - I hope I'm not discouraging you. I'll leave this open, if someone else from the curriculum team says to do it, then we can. Really, the change is pretty harmless. Thanks again for your interest in contributing.

**Comment by bellhuffstutler** [comment]
The thing is:

I have had this problem.
There is no downside to implementing the fix that we have suggested (and I have offered to implement)
And people make typos

Yes, it's an edge case 

But it's an edge case that we have a proposed fix that solves both the issue and stays within the want to not allow GUI renaming, and it is harmless to implement.

It's not for everyone? But it definitely helps the curriculum teach BASH and feel like BASH if at the very least we can rename with BASH. It's extremely awkward to have to run `rm [file]` and then `touch/mkdir/whatever [file]`

**Comment by moT01** [comment]
I ran this by one of the team members. You seemed pretty excited to work on this, and like we said, there isn't really a downside to add this - so if you want to give it a try, go for it.

One thing you mentioned:
>     const websiteDirectory = await getDirectoryContents('../website');
> It already has it, but it's looking for the wrong folder.
> When you make the website folder, you're in Projects already, so the ../ at the beginning will check outside of that folder

I don't think that's true. The tests run from `projects/freeCodeCamp` so you need to go back a level to get to `projects`

Also, this part of the test you suggested: 
`lastCommand[0] === 'mv' && /styles\.css$/.test(lastCommand[1]);`
should be:
`lastCommand[0] === 'mv' && /styles\.css$/.test(lastCommand[2]);`
I changed the last 1 to 2 - pretty sure it should be like that. The mv command would be `mv stiles.css styles.css` - which is split by spaces (for the most part), and turned into the `lastCommand` array.

I know you got this in chat, but [the instructions for working on these are here.](https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad) I recently moved all the tests to the `INIT` commit, so you should only need to change that one. Let me know if you have any questions.

**Comment by bellhuffstutler** [comment]
Thank you! 

Also yeah, I know the ../website part is wrong now, I was just saying that based off the info I was given, and i was told 850 was the test when it was a different test, and I just didn't edit it, because it was clarified in later messages. 

Also thank you for the tip, and I'll look at the INIT commit after I finish eating and then get to work making the changes.

**Comment by moT01** [comment]
Also, I wrote those instructions some time ago - they may be a little outdated or not as refined as they could be.

**Comment by bellhuffstutler** [comment]
No worries, they look pretty solid, but I'm sure if I have any questions I can find somewhere to ask about them

**Comment by bellhuffstutler** [comment]
@moT01 So I do have a question. 

The tests don't show up in the main repo. I have my fork checked out on `v1.0.2`, is that the way you would like me to do it? Then I can make the changes, push the changes to a new branch on my repo and then set the PR. 

Or is there another way I should be doing it that you would prefer?

**Comment by moT01** [comment]
Just for maybe some help - here's how I would do it.

-fork the repo and clone it locally, make sure all the changes are pulled in, etc
-create and checkout the latest version branch - v1.0.2
-create and checkout a v1.0.3 branch off of that
-rebase that branch to the root and edit the `INIT` commit
-make all your test fixes
-continue and finish the rebase
-push the new branch to your fork
-checkout `main`
-create and checkout a new branch off of that - `feat/v1.0.3`
-update the stuff in there + commit
-run coderoad build
-commit new json file
-push that branch + make a PR

These are tricky to work on, which is another reason I try to limit changes to ones that are really necessary. But those are pretty close to the steps I would take. 

If you want to test your changes, here's what I do - after you push the v1.0.3 branch to your fork...
-checkout main
-update coderoad.yaml to use your fork and the new version branch + commit
-coderoad build + commit the new JSON file
-push to your main branch
-use this URL to test the changes: `https://codeally.io/embed/?repoUrl=https://github.com/bellhuffstutler/learn-bash-by-building-a-boilerplate` - you may need to delete any existing VM's for that project on codeally first - after opening the project to test it, you can look in the repo files to make sure you are using the repo you just created. e.g. look in coderoad.yaml to see if it's using your fork

**Comment by bellhuffstutler** [comment]
Sounds good! 

I'll work on that now then thank you

**Comment by bellhuffstutler** [comment]
ah cool cool i'll try that
