### ISSUE TITLE
RWD: possible unclear instructions on challenge step (prefers-reduced-motion media query)

### ISSUE THREAD

**Issue by MoiraX** [freeCodeCamp/freeCodeCamp#46210]
### Describe the Issue

I think that the instructions for the  `prefers-reduced-motion` media query are a little difficult for (relative) beginners to understand.

Up until now, as far as I can see, they've only been asked to create media queries for CSS rules that they're already somewhat familiar with (`max-width`, `min-width` etc.).
So, to me, it just feels a little too ambitious at this stage to expect them to have fully  grasped the terminology involved (media-rule, values etc.) and to be able to construct the appropriate media query.

It doesn't help that the MDN docs page has no examples using either `reduce` or `no-preference` which also makes it a little more difficult for students to search for help via Google. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-66

### Your code

```

```

### Expected behavior

I feel as though some kind of example would be very useful here, although I do appreciate that it's difficult to provide an example without effectively giving the solution away.
Perhaps something like "reminder - the format of a media-query is (_media-rule_: _value_)" could be added? (at least to the hint if not to the instructions).

Alternatively, perhaps add a link to this [CSS-tricks article](https://css-tricks.com/introduction-reduced-motion-media-query/) which does have an appropriate example.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Recent forum posts:
https://forum.freecodecamp.org/t/step-66-learn-accessibility-by-building-a-quiz/512424/2
https://forum.freecodecamp.org/t/wrapping-elements-within-media-queries/512233
https://forum.freecodecamp.org/t/helphelp-of-css-examination-of-forms-of-the-second-module/510741

**Comment by Sboonny** [comment]
> I feel as though some kind of example would be very useful here, although I do appreciate that it's difficult to provide an example without effectively giving the solution away.

I do agree an example would work, but it isn't the optimal way.

> Alternatively, perhaps add a link to this [CSS-tricks article](https://css-tricks.com/introduction-reduced-motion-media-query/) which does have an appropriate example

It's against freeCodeCamp policy to add an external link, there is an issue with the content of the external link changing.

We can change previous media challenge to include this [article](https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/), until media reduce article made

**Comment by ojeytonwilliams** [comment]
> It's against freeCodeCamp policy to add an external link, there is an issue with the content of the external link changing.

Agreed, users are always free to search if they want to, but we should try to make our lessons self-contained if possible.

I just tried doing the lesson myself and found it frustrating to keep getting the hint 

> You should wrap the existing `*` rule within the `@media` rule.

when I had wrapped the rule correctly, but the `@media` rule was wrong. 

```
@media(prefers-reduced-motion) {
  * {
  scroll-behavior: smooth;
  }
}
```

should trigger a different hint.

> Perhaps something like "reminder - the format of a media-query is (media-rule: value)" could be added? (at least to the hint if not to the instructions).

That sounds good to me, though I'd word it slightly differently to be more consistent with the rest of the hints:

> You should use the syntax `@media(<media-feature>: <value>)`

cc: @ShaunSHamilton
