### ISSUE TITLE
Scrolling on touch devices does not work consistently in editor in Steps

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46236]
### Describe the Issue

There are regions of the editor in the new Steps challenges that do not scroll properly when using a touch device:

- The left gutter (line numbers)
- The "Check Your code" button and its expanded results/hint box

This issue is also affecting our ability to implement fixes for PR #46217.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-18

### Your code

N/A

### Expected behavior

Editor should scroll when swiping over any area of the editor.

### System

- Device: moto g6
- OS: android 9
- Browser: Chrome
- Version: 101

**Comment by Sboonny** [comment]
https://forum.freecodecamp.org/t/cant-view-entire-elements/514572/5

Is this forum related to this issue?

**Comment by bbsmooth** [comment]
@Sboonny Yes, this is the issue that is causing the problems in that forum post. I have a fix for it in my PR #46217. Hopefully we can get it to production this coming week.

**Comment by bbsmooth** [comment]
PR #46217 has been merged and is on production and we are now able to scroll the editor at any position using the line number gutter. It's not a perfect solution but probably good enough since getting vertical scroll to work on monaco's content and overlay widgets is probably not possible without fixing the monaco code itself.
