### ISSUE TITLE
Get set for Bonfires, Ziplines, Basejumps need warning about ambiguity

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#4625]
From Reddit (https://www.reddit.com/r/FreeCodeCamp/comments/3tll4s/noob_question_is_there_a_glossary_of_fcc_terms/cx7brpt): 
In my case I initially wondered whether something had gone wrong and I'd landed on page prematurely.

For our front end Zipline challenges, we'll use a popular browser-based code editor called CodePen.

vs

"Ziplines" are front end challenges. These are where you will practice the skills you've learned so far. For these we'll use a popular browser-based code editor called CodePen."

We should also take this opportunity to remind campers that - unlike Waypoints - these challenges are difficult, ambiguous, and will require a much larger investment of time and effort. 

So we need to come up with consistent copy for the "Get Set for ____" challenges. 

Currently they look like this:

(we're missing a Get Set for Bonfires challenge)
http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines
http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps

Any copy suggestions?

**Comment by SaintPeter** [comment]
Off the cuff:
"Bonfires are where the rubber meets the road.  You will take the tools you have learned from Javascript and apply them to solve algorithmic problems"

"Beware:  Bonfires can be very challenging and will require you to apply your problem solving skills to break down the challenges into their atomic parts, then build them back up with Javascript."

"Don't worry about finding the 'perfect' or 'most efficient' solutions.  There is plenty of time for that later.  Instead, focus on solving the challenge and satisfying the tests."

"While we do have hints and solutions available on our [Wiki](#), you are better off solving them on your own.  Use Google and other online resources to help you find solutions to sub-problems, but don't search for the answer."

"Don't forget that we have many dedicated helpers in our [HelpBonfires Chat Room](#).  If you get stuck or don't know where to start, you can ask for tips there."

**Comment by ltegman** [comment]
Looks like the get set waypoints have been updated to make it clear how difficult these challenges are.
