### ISSUE TITLE
Arabic translation of Gear up for Success

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4627]
* [ ] Browse Camper News Complete
* [ ] Reference our Wiki Complete
* [ ] Join our LinkedIn Alumni Network Complete
* [ ] Commit to a Goal and a Nonprofit Complete

**Comment by erictleung** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/20
