### ISSUE TITLE
Arabic translation of jQuery waypoints

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4628]
* [ ] Learn how Script Tags and Document Ready Work
* [ ] Target HTML Elements with Selectors Using jQuery
* [ ] Target Elements by Class Using jQuery
* [ ] Target Elements by ID Using jQuery
* [ ] Delete your jQuery Functions
* [ ] Target the same element with multiple jQuery Selectors
* [ ] Remove Classes from an element with jQuery
* [ ] Change the CSS of an Element Using jQuery
* [ ] Disable an Element Using jQuery
* [ ] Change Text Inside an Element Using jQuery
* [ ] Remove an Element Using jQuery
* [ ] Use appendTo to Move Elements with jQuery
* [ ] Clone an Element Using jQuery
* [ ] Target the Parent of an Element Using jQuery
* [ ] Target the Children of an Element Using jQuery
* [ ] Target a Specific Child of an Element Using jQuery
* [ ] Target Even Numbered Elements Using jQuery
* [ ] Use jQuery to Modify the Entire Page

**Comment by erictleung** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/21
