### ISSUE TITLE
Unneeded Check for Semicolon 

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46296]
### Describe the Issue

Why are we checking for a semicolon in this challenge again? The check leads to somewhat confusing test output, and I thought we were pushing towards 'any valid syntax must be allowed to pass'?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript

### Your code

```
myVar++
```

### Expected behavior

Test output should mention required semicolon or test should be relaxed.

### System

All

**Comment by ShaunSHamilton** [comment]
Thanks, Jeremy.

I agree. We should change the tests in this file to not check for the `;`
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript.md

---

An issue with the _first timers only_ label is open for contribution to first-timers. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
