### ISSUE TITLE
Confusion In Test Output

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46295]
### Describe the Issue

Occasionally users are confused by the test output, as changing the contents of `FCC` can result in a message about capitalizing the variable name. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword

### Your code

```
const FCC = "FreeCodeCamp"; // Change this line
let fact = "is cool!"; // Change this line
fact = "is awesome!";
console.log(FCC, fact); // Change this line
```

### Expected behavior

Two possibilities here.

1) add a sentence stating that the user should not change the variable contents 

2) split the relevant test into two parts, one for changing the capitalization of the variable name and the other for not changing the contents 

### System

All

**Comment by Sboonny** [comment]
I think a more lenient approach is to not care about the content of the variable, unless I am missing something.

```js
assert.equal(FCC, 'freeCodeCamp');
assert.match(code, /const\s+FCC/);
```

Here is the file [declare a read only variable](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword.md)

**Comment by jeremylt** [comment]
I think we should care about the content of the variable - I have seen learners blindly capitalize everything on the line instead of understanding that they should only make the variable name ALL_CAPS.

**Comment by Sboonny** [comment]
If I am understanding this correctly, people tried to capitalize `const`.

I am in favour of the second one, to make it clearer that they should focus only on variables.

> split the relevant test into two parts, one for changing the capitalization of the variable name and the other for not changing the contents

**Comment by jeremylt** [comment]
They capitalize parts of the string itself, which can be an indication that they don't understand what all should and should not be changed.

**Comment by Sboonny** [comment]
> they don't understand what all should and should not be changed.

Wait, I thought that's normal, I almost finished front-end frameworks projects without understanding React, jQuery, and bootstrap.😅

I like your intent. It isn't possible for everyone to understand the steps, and stopping them on something that isn't required in the test feels harsh to me.

So I am in support of the second possibility, which splits the test. Although I would prefer not stopping them at all, this can be too lenient from me.👍

**Comment by jeremylt** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword.md

Suggested test change:

`FCC` should be a constant variable declared with `const`.

```js
assert.match(code, /const\s+FCC/);
```

The string assigned to `FCC` should not be changed.

```js
assert.equal(FCC, 'freeCodeCamp');
```

Suggested lesson content change:
# --instructions--

Change the code so that all variables are declared using `let` or `const`. Use `let` when you want the variable to change, and `const` when you want the variable to remain constant. Also, rename variables declared with `const` to conform to common practices. Do not change the strings assigned to the variables.

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. For details look at Jeremy's comment above, https://github.com/freeCodeCamp/freeCodeCamp/issues/46295#issuecomment-1145129600.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
