### ISSUE TITLE
CatApp Step 63 - Malformed Code Passing

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46299]
### Describe the Issue

Can we prevent this malformed code from passing?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-63

### Your code

```html
    No Copyright - <a href="https://www.freecodecamp.org"</a> freeCodeCamp.org  
```

### Expected behavior

Bad code is bad. Bad code should not be marked as good.

### System

All

**Comment by jeremylt** [comment]
I haven't see this come up on the forum too much, so I doubt this is a likely error. Just thought I'd ask though. I'm fine closing this issue, but thought we should at least discuss.

**Comment by ojeytonwilliams** [comment]
Thing is, this code is pretty bad and it does rather weird things when the browser tries to parse it.  I see this:

```html
<footer>
      <p>
       No Copyright - <a href="https://www.freecodecamp.org" < a> freeCodeCamp.org  
      </a></p><a href="https://www.freecodecamp.org" < a>
    </a></footer>
    <a href="https://www.freecodecamp.org" < a> </a>
```

when I put in the bad code.

Regexes are a pain, though.
