### ISSUE TITLE
Quiz 33 - Quotes Around Value

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46298]
### Describe the Issue

It would be clearer if we put quotes around the value we want the user to use.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-33

### Your code

I have seen this mistaken answer a few times:
```css
p::before {
  content: Question #;
}
```

### Expected behavior

Suggested text:
To prevent unnecessary repetition, target the `before` pseudo-element of the `p` element, and give it a `content` property of `"Question #"`.

### System

All

**Comment by ShaunSHamilton** [comment]
Thanks, Jeremy.

I agree, the description should read:

> ...and give it a `content` property of `'Question #'`.

Here is the file needing changed:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6145ed1f22caab087630aaad.md

---

An issue with the _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
