### ISSUE TITLE
"Take Home Projects - Build a Nightlife Coordination App" - Dead demo project

### ISSUE THREAD

**Issue by c-ehrlich** [freeCodeCamp/freeCodeCamp#46316]
**Describe the bug**
The [demo project](https://yoyo44.herokuapp.com/) for [Take Home Projects - Build a Nightlife Coordination App](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app) links to a dead page.

**Comment by JordanMooree** [comment]
Thank you @c-ehrlich for reporting this issue!

This issue appears to be very similar to issue #44310, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding!
