### ISSUE TITLE
"Build a freeCodeCamp Forum Homepage" demo project uses outdated API endpoint

### ISSUE THREAD

**Issue by c-ehrlich** [freeCodeCamp/freeCodeCamp#46315]
**Describe the bug**
The [sample project](https://codepen.io/freeCodeCamp/full/JqdoMV) for the [Take Home Projects - Build a freeCodeCamp Forum Homepage](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-freecodecamp-forum-homepage) fails to load data because it makes a request to an endpoint that returns a 500 (due to an expired cert, according to the response). 

On the challenge page, there is a link to an API endpoint that works. Fixing this is just a matter of changing the following in the codepen:

**Incorrect Code**
```js
componentDidMount() {
  fetch('https://buttercup-island.glitch.me/latest')
    .then(response => response.json())
    .then((data) => {
      this.setState({
        users: data.users,
        topics: data.topic_list.topics,
      });
    });
}
```

**Correct Code**
```js
componentDidMount() {
  fetch('https://forum-proxy.freecodecamp.rocks/latest')
    .then(response => response.json())
    .then((data) => {
      this.setState({
        users: data.users,
        topics: data.topic_list.topics,
      });
    });
}
```

**Comment by JordanMooree** [comment]
Thanks, @c-ehrlich for catching this. @freeCodeCamp/dev-team we need a change on the link for freeCodeCamp's Codepen `line 15` for the [sample project](https://codepen.io/freeCodeCamp/pen/JqdoMV?editors=1010) from 
```
https://buttercup-island.glitch.me/latest
```
to
```
https://forum-proxy.freecodecamp.rocks/latest
```

**Comment by ShaunSHamilton** [comment]
Along with the change to the endpoint, and similarly to https://github.com/freeCodeCamp/freeCodeCamp/issues/46173 , we should port the example project over to `.rocks`.

**Comment by ShaunSHamilton** [comment]
For now, I have updated the example project to use the latest link.

**Comment by naomi-lgbt** [comment]
Going to close this - the migration to .rocks can be tracked in the issue Shaun linked above.
