### ISSUE TITLE
Arabic translation of Basic Front End Development Projects

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4632]
* [ ] Get Set for Ziplines
* [ ] Build a Personal Portfolio Webpage
* [ ] Build a Random Quote Machine
* [ ] Build a Pomodoro Clock
* [ ] Build a JavaScript Calculator

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/25
