### ISSUE TITLE
New RWD (cafe menu, step 65) tests accept incorrect answer

### ISSUE THREAD

**Issue by MoiraX** [freeCodeCamp/freeCodeCamp#46332]
### Describe the Issue

While I was replying to a forum question, I realised that step 65 of the Cafe Menu section accepts an incorrect answer.

The challenge is to nest an anchor element inside a `p` element, like this:

`<p><a href="https://www.freecodecamp.org">Visit our website</a></p>`

But the student had nested the p element inside the anchor element, like this:

`<a href="https://www.freecodecamp.org"><p>Visit our website<p></a>`

The tests accept that (incorrect) answer - but only if the closing `p` tag is malformed (`<p>` instead of `</p>`).

It's a weirdly specific case, I know, but is there any way to have the tests pick this up?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-65

### Your code

```
<a href="https://www.freecodecamp.org"><p>Visit our website<p></a>
```

### Expected behavior

Ideally, the tests would recognise that the elements are incorrectly nested and not allow the incorrect code to pass the tests.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Link to the relevant forum post:

https://forum.freecodecamp.org/t/step-65-cafe-menu/514376

**Comment by Sboonny** [comment]
Here is the file

 https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0a81099d9a697b550.md#L18
 
 I think, it's best to not do anything. 

The next challenge isn't about css, and they can see the correct format in it

**Comment by lasjorg** [comment]
This is how the browser renders the HTML.

```
<footer>
 <a href="https://www.freecodecamp.org"><p>Visit our website</p></a>
 <p><a href="https://www.freecodecamp.org"></a></p>
</footer>
```


If we scope the selectors it should fail. We really do not need `find` or `children`, or the case-insensitive not exactly matching regex.

```
assert($('footer').length === 1)
assert($('footer > p').length === 1);
assert($('footer > p > a').length === 1);
assert($('footer > p > a').text() === 'Visit our website')
assert($('footer > p > a').attr('href') === 'https://www.freecodecamp.org');
```

We can also extend the third test so that its assert message would trigger, with the incorrect code in question.

```
assert($('footer > p > a').length === 1 && $('footer > p > a').text() === 'Visit our website');
```

**Comment by MoiraX** [comment]
Hi Muhammed

I'm not sure whether I'm allowed/supposed to reply to these mails - if not,
please let me know!

Anyway, I did wonder whether I should even raise this as an issue.
But given that the test lets the incorrect code through, I felt I should at
least flag it as a problem.

I don't think it will happen too often, though - they'd need to both
misunderstand the instructions and get the closing tag wrong.
So, I totally understand the decision to leave this one alone.

Thanks for getting back to me.

Cheers
Moira
