### ISSUE TITLE
Arabic translation of Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4633]
* [ ] Sum All Numbers in a Range
* [ ] Diff Two Arrays
* [ ] Roman Numeral Converter
* [ ] Where art thou
* [ ] Search and Replace
* [ ] Pig Latin
* [ ] DNA Pairing
* [ ] Missing letters
* [ ] Boo who
* [ ] Sorted Union
* [ ] Convert HTML Entities
* [ ] Spinal Tap Case
* [ ] Sum All Odd Fibonacci Numbers
* [ ] Sum All Primes
* [ ] Smallest Common Multiple
* [ ] Finders Keepers
* [ ] Drop it
* [ ] Steamroller
* [ ] Binary Agents
* [ ] Everything Be True
* [ ] Arguments Optional

**Comment by muteb1** [comment]
working on it

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/46 @3laa-Khalil-Alarabi @muteb1 please continue discussion on that thread.
