### ISSUE TITLE
Arabic translation of JSON APIs and Ajax

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4634]
* [ ] Trigger Click Events with jQuery
* [ ] Change Text with Click Events
* [ ] Get JSON with the jQuery getJSON Method
* [ ] Convert JSON Data to HTML
* [ ] Render Images from Data Sources
* [ ] Prefilter JSON
* [ ] Get Geo-location Data

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/26
