### ISSUE TITLE
Learn Typography by Building a Nutrition Label - gets repetitive and a bit boring

### ISSUE THREAD

**Issue by PersianBlue** [freeCodeCamp/freeCodeCamp#46358]
This isn't really a bug issue, more of a content/feature issue. I feel like it would be more intuitive if the class names (lg, md, sm-text, etc.) were spelled out to make them more intuitive, and then having understood what we were doing, we were just tasked to build each section of the nutrition label. As opposed to adding every new paragraph and divider one by one by one in this instance. Then if a person was unsure about a certain aspect of it, hints could guide them along the way.

On another note, if there's a better place to give feedback/suggestions do let me know.

![image](https://user-images.githubusercontent.com/71480723/172065074-73acdd98-15a4-4663-86ee-4f9d34273ffd.png)
Likewise, the code that we're adding to over time turns into a mass of pargaraph and div soup... not very easy on the eyes

**Comment by bellhuffstutler** [comment]
I will agree this one got a bit long, a lot like the balance sheet one. 

Im not entirely sure a great solution though. The repetition is *really* useful for getting a bit more of an understanding tbh 

I do like the idea of making the divs and classes a bit more clear/descriptive. Maybe use more sections and make the classes less condensed?

**Comment by naomi-lgbt** [comment]
The repetition *does* help to reinforce concepts and get campers familiar with the concepts we are teaching.

PRs are certainly welcome to change the class names from `lg` to `large` - we'd also welcome a PR to adjust the flow of the project, if you're feeling ambitious.

**Comment by chrysillala** [comment]
Hi, can I contribute to this issue? Would appreciate if you could give some guidance, thanks!

**Comment by ieahleen** [comment]
I am going to tackle part of the issue in #47675 47675

**Comment by Omkar0803** [comment]
I would like to contribute, can assign me issues?

**Comment by naomi-lgbt** [comment]
Going to go ahead and close this one as stale.
