### ISSUE TITLE
Colored Markers step 49

### ISSUE THREAD

**Issue by ThirstB1ood** [freeCodeCamp/freeCodeCamp#46351]
### Describe the Issue

After right changing code I face with one problem: "Your .red CSS rule should have a background property with the value rgb(255, 0, 0)."

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design#learn-html-by-building-a-cat-photo-app

### Your code

```
.red {
  background: rgb(255, 0, 0);
}
```

### Expected behavior

Submit and go to next challenge

### Screenshots

<img width="517" alt="Screenshot" src="https://user-images.githubusercontent.com/82532230/172048397-1cb740b1-65e5-4d3f-912a-8836e4d7da8a.png">

### System

- Device: MacBook Air
- OS: MacOS Monterey 12.4
- Browser: Safari
- Version: 15.5

**Comment by ieahleen** [comment]
related to #46233, but not exactly a duplicate as it is about a different step

**Comment by ThirstB1ood** [comment]
Thanks, I solve my problem by Google Chrome
