### ISSUE TITLE
freeCodeCamp readme does not list the new responsive web design course

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#46356]
### Describe the Issue

The [freeCodeCamp readme](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/README.md) only shows the legacy Responsive web design courses. 
<img width="358" alt="Screen Shot 2022-06-05 at 9 40 55 AM" src="https://user-images.githubusercontent.com/67210629/172061025-c99d52b2-11a3-414b-87b2-687a1a1fac58.png">

That needs to be changed to list the new Responsive Design course.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/README.md

### Steps to Reproduce

N/A

### Recommended fix or suggestions

List only the new Responsive Design course

**Comment by JordanMooree** [comment]
Yes, I agree with this. I think we should also update the projects to link to the new RWD projects as well.

![image](https://user-images.githubusercontent.com/27147016/172064595-9161d1f2-4a0d-4d7f-8e2c-d6e76913d2fb.png)

**Comment by Sboonny** [comment]
We may take the same approach as we did in `/learn`
![Screenshot_2022-06-06-17-37-45-64_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/88248797/172194733-82daa145-21a2-4032-acc7-069cfc823302.jpg)
