### ISSUE TITLE
The Ctrl / Cmd + Enter shortcut doesn't trigger the completion modal in the RWD projects

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#46361]
### Describe the Issue

A learner on Twitter pointed out that using the Ctrl / Cmd + Enter shortcut to run the tests for the RWD projects doesn't trigger the completion modal.

Clicking the "Run the Tests (Ctrl + Enter)" button triggers the modal as expected if all the tests pass. But using the keyboard shortcut just runs the tests, and the shortcut has to be used again to actually submit the code in the editor as a solution and move on to the next challenge.

### Affected Page

All RWD project pages

### Steps to Reproduce

1. Go to one of the RWD projects like [Build a Survey Form](https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form)
2. Enter a valid solution (can use code from the demo repo here for testing: https://github.com/freeCodeCamp/demo-projects/tree/master/apps/survey-form)
3. Use the Ctrl / Cmd + Enter shortcut to run the tests
4. Check the tests pane to see that all the tests have passed, but the completion modal is absent
5. Submit the project code
    - Use the Ctrl / Cmd + Enter shortcut again
    - Or click the "Run the Tests (Ctrl + Enter)" button to trigger the completion modal, then click the "Submit and go to next challenge (Ctrl + Enter)" button, or use the Ctrl / Cmd + Enter shortcut

### Expected behavior

The Ctrl / Cmd + Enter shortcut should trigger the completion modal like clicking the "Run the Tests (Ctrl + Enter)" button does.

### System

- Device: Laptop
- OS: Linux Mint 20.3
- Browser: Chrome (102.0.5005.61), Firefox (101.0)

**Comment by ShaunSHamilton** [comment]
Related: https://github.com/freeCodeCamp/freeCodeCamp/pull/43728
