### ISSUE TITLE
Campfire Mode doesn't trigger on multiple browsers unless you turn it on and off

### ISSUE THREAD

**Issue by carly-kins** [freeCodeCamp/freeCodeCamp#46372]
### Describe the Issue

Campfire Mode was not playing on my account. I did find a fix, but still wanted to report! Please note it could be affecting more than one page, but I only tested on the new responsive web design! 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/

### Steps to Reproduce

1. I'm logged in on my computer 
2. Under settings, Campfire Mode is enabled. 
3. My volume is turned up!
4. I go to the (New) Responsive Web Design course
5. The serenade of the Guitar does not play as I type or click on items :(

### Expected behavior

1. I'm logged in on my computer 
2. Under settings, Campfire Mode is enabled. 
3. My volume is turned up!
4. I go to the (New) Responsive Web Design course
5. The serenade of the Guitar plays!

### System

- Mac OS Big Sur 11.6.5 running Safari
- Windows 10 running Google Chrome 

### Additional context

I found a fix while poking around! 

1. I go to my settings and turn off and on Campfire mode.
2. The serenade of the Guitar DOES play as I type and click on items :)

**Comment by raisedadead** [comment]
@freeCodeCamp/dev-team We are somehow not tracking the setting into the local storage I believe?

**Comment by ojeytonwilliams** [comment]
We're using a hybrid of local storage and the session user, right now.  It would be best to remove all reliance on local storage, so that it's consistent across devices.

**Comment by nhcarrigan** [comment]
The usage of local storage was restored as a temporary fix for another issue - I agree with Oliver that we want to move to relying on the session user, but this will require some component updates to pass the user into the props.

**Comment by ojeytonwilliams** [comment]
@nhcarrigan this sounds like something we might want to open for contributions, since it's definitely something we want, but isn't urgent. What do you reckon?

**Comment by nhcarrigan** [comment]
I agree. It's already got the help wanted tag, so I propose we leave it as such.

**Comment by nayabatir1** [comment]
Hey I want to work on this issue, could you let me know what needs to be done here.

**Comment by KravMaguy** [comment]
Im unable to reproduce the steps as outlined in the issue. 

>Expected behavior
>I'm logged in on my computer
>Under settings, Campfire Mode is enabled.
>My volume is turned up!
>I go to the (New) Responsive Web Design course
>The serenade of the Guitar plays!

Im getting exactly this expected behavior. Should this issue still be open? If so please describe steps to reproduce and desired behavior.

**Comment by naomi-lgbt** [comment]
Log in on Computer A
Under settings, Campfire Mode is enabled.
My volume is turned up!
I go to the (New) Responsive Web Design course
The serenade of the Guitar plays!
Log in on Computer B
I go to the (New) Responsive Web Design course
The serenade of the Guitar does not play as I type or click on items :(

**Comment by nayabatir1** [comment]
Is setting sound volume manually part of requirement ?
Can't we just leave it to system sound volume?

**Comment by ieahleen** [comment]
@nayabatir1 volume is already implemented, that's not what this issue is about

**Comment by nayabatir1** [comment]
> @nayabatir1 volume is already implemented, that's not what this issue is about

Let me re-phrase
I looking at the code, I found that audio volume is being set manually. Any specific reason for setting volume level.

My bad there is option to set volume level. Didn't saw that.

**Comment by ieahleen** [comment]
because so users have freedom to set the volume to what they want
