### ISSUE TITLE
Arabic translation of Advanced Algorithm Scripting 

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4639]
* [ ] Validate US Telephone Numbers Incomplete
* [ ] Symmetric Difference Incomplete
* [ ] Exact Change Incomplete
* [ ] Inventory Update Incomplete
* [ ] No repeats please Incomplete
* [ ] Friendly Date Ranges

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/30
