### ISSUE TITLE
Bug alert! Sum of All Prime is doubling submitted answers

### ISSUE THREAD

**Issue by WalterPhillips** [FreeCodeCamp/freecodecamp#464]
Hi!

It seems that Sum Of All Prime validator is messed up. It is taking the answer generated by submissions and doubling it.

I am getting the error below:
expect(sumPrimes(10)).to.equal(17);expected 34 to equal 17

17 should be the correct answer.

Here is my code:
```javascript
var primes = [];
var primeSum = 0;

function sumPrimes(num) {
  for (var i=0; i<=num; i++) {

    if (i>11) {
      var j=0;
      for ( j=0; j<primes.length; j++) {
        if ((i % primes[j]) === 0) {
          break;
        }
      }

      if (j==primes.length) {
        addToPrime(i);
      }

    } else {
      if (i===2 || i===3 || i===5 || i===7 || i==11) {
        addToPrime(i);
      }
    }
  }

  return primeSum;
}

function addToPrime(n) {
  primes.push(n);
  primeSum += n;
}
```

**Comment by terakilobyte** [comment]
I'm unable to reproduce this bug with your code on either Chrome or Firefox.

**Comment by PKMNinja** [comment]
I also couldn't reproduce the bug in either Chrome or Firefox.

**Comment by WalterPhillips** [comment]
Ok, I'm not sure why it not reproducible now. I have at least one other person, @geekfish who experience the same thing.  Thanks for looking into this.

**Comment by terakilobyte** [comment]
Alright, sometimes things can happen and it's hard to track down. Bonfires execute entirely within the browser, there's absolutely no server side interaction except to fetch new bonfires. If this happens again please take screenshots with your developer console open to catch any javascript errors and feel free to reopen and update this issue. Happy coding!
