### ISSUE TITLE
Arabic translation of AngularJS Waypoints

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4640]
* [ ] Get Started with Angular.js Incomplete
* [ ] Apply Angular.js Directives Incomplete
* [ ] Power Forms with Angular.js Incomplete
* [ ] Customize Angular.js Directives Incomplete
* [ ] Create Angular.js Services

**Comment by atjonathan** [comment]
@dwd2010 why was this closed?

**Comment by dwd2010** [comment]
@atjonathan, It is AngularJS waypoint. we dont have that on fcc anymore. So it dont need to translation.

**Comment by atjonathan** [comment]
@dwd2010 :+1:
