### ISSUE TITLE
On macOS keyboard shortcut is shown as Ctrl+Enter instead of Cmd+Enter

### ISSUE THREAD

**Issue by tugkankibar** [freeCodeCamp/freeCodeCamp#46423]
### Describe the Issue

Even though on macOS it would seem that Ctrl+Enter does not work & Cmd+Enter does; website still tells you to use Ctrl+Enter.

I think this might end up being confusing for some - and should be fairly straightforward of a change.

### Affected Page

All coding pages

### Steps to Reproduce

You must use macOS for this issue.

1. Go to any coding challenge
2. Type your changes
3. You will see button underneath says "Check your code (Ctrl + Enter)"
4. Press Ctrl + Enter
5. Nothing will happen.
6. Press Cmd + Enter
7. Expected behaviour will occur.

### Expected behavior

It should tell the user correct shortcut (Cmd + Enter) instead of (Ctrl + Enter) depending on the platform.

### Screenshots

<img width="647" alt="Screenshot 2022-06-09 at 16 52 28" src="https://user-images.githubusercontent.com/5172699/172877184-8251af54-65eb-46dd-949f-9ad04f7e20fa.png">

### System

- Device: M1 MacBook Pro
- OS: macOS 12.0.1
- Browser: Safari
- Version: 15.1

**Comment by tugkankibar** [comment]
I've created the PR however;

>I've updated non English translations as well in here to use dynamic values; however not really sure how to align it with the crowdin. Since updated translations should coincide with this change; any opinions on this?

https://github.com/freeCodeCamp/freeCodeCamp/pull/46428#issuecomment-1151568332

**Comment by raisedadead** [comment]
> Since updated translations should coincide with this change; any opinions on this?

Do not worry, I think you are putting too much effort into it. Simply drop the changes to those files and as the bot mentioned, they will get updated eventually via our translation workflow.

As for the bug itself:

I am 100% sure at some point we introduced a regression, because `Ctrl + Enter` (in addition to the implicit Cmd + Enter) was working since the inception of the code editor.

@freeCodeCamp/dev-team do you happen to know if this was just an accident with the new editor?

**Comment by ojeytonwilliams** [comment]
I can't check this myself, since I don't have a mac, but it *should* work. This is the code:

https://github.com/freeCodeCamp/freeCodeCamp/blob/1083f1d5c5a58a4b399f1af4842abd96443aff0b/client/src/templates/Challenges/classic/editor.tsx#L427-L431

and 

https://github.com/freeCodeCamp/freeCodeCamp/blob/1083f1d5c5a58a4b399f1af4842abd96443aff0b/client/src/templates/Challenges/components/Hotkeys.tsx#L45

@moT01 could you try and reproduce the issue?

**Comment by tugkankibar** [comment]
@ojeytonwilliams 

I've shot a short video of the behaviour I am seeing; if that helps.

https://www.loom.com/share/9d590c0470c449b69e8fa83cbce5de45

**Comment by ojeytonwilliams** [comment]
That does help, yeah. It seems to be ignoring the command button entirely, which is odd.

I can't investigate myself, but this will help anyone that has access to a Mac.

**Comment by moT01** [comment]
Thanks for the video @tugkankibar 👍

> I am 100% sure at some point we introduced a regression ... do you happen to know if this was just an accident with the new editor?

I don't recall if ctrl+enter ever worked on mac - I may or may not have ever used it. I just hit buttons without looking 😬 

I'm not sure if you are trying to show something specific with those code snippets @ojeytonwilliams - that's the code on main. Which results in the current behavior. 

Here's the current behavior I see (all on mac) - there's some nuance...

New RWD:
Execute: only command+enter works on mac
Submit: Enter alone works, so any key+enter works

Legacy RWD, JS, etc:
Execute: Only cmd+enter works
Submit: Enter alone does not work - both ctrl+enter or command+enter do work

Multiple choice Python video questions:
Execute: Enter alone does not work - ctrl+enter and cmd+enter work
Submit: Enter alone does not work - both ctrl+enter or command+enter do work

Projects with URL inputs - e.g. front end libs cert project, or backend api challenges, etc:
Execute: Enter alone works cause it's a form I suppose, which also means any key+enter works
Submit: Enter alone does not work - both ctrl+enter or command+enter do work

The last three groups there have the same submit modal, so the behavior is the same on all of them. What I see is that the submit modal, and the video question both allow [ctrl or cmd] +enter - we should see what those are doing.

**Comment by moT01** [comment]
K, I think I found a fix.

ctrl+enter works when the hotkeys package/component is used. So crtl+enter actually does work on the legacy challenges when the instructions are focused. When the editor is focused, those hotkeys don't get used, the actions/hotkeys we add to the editor take over.

I made ctrl+enter work when the editor is focused by changing that line 431 @ojeytonwilliams mentioned to this:
`keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, monaco.KeyMod.WinCtrl | monaco.KeyCode.Enter],`

That should work. There's a number of actions in that file that use the same hotkeys - lines 457 and 469 for example. There may be others. I think we should be safe to change all those.

**Comment by ojeytonwilliams** [comment]
Nice work, Tom.  I thought CtrlCmd was "Ctrl or Command", but it must be Ctrl on Windows and Command on Mac :man_facepalming: 

I guess this has never worked properly.

**Comment by tugkankibar** [comment]
@moT01 happy to give it a look and update the PR. Thank you 🙏

**Comment by Nirajn2311** [comment]
> Nice work, Tom. I thought CtrlCmd was "Ctrl or Command", but it must be Ctrl on Windows and Command on Mac 🤦‍♂️

Here's an [issue](https://github.com/microsoft/monaco-editor/issues/102) I had created sometime back when working on the `editor`. Apparently the logic goes like this - the first word is Windows and the second one is Mac button.
