### ISSUE TITLE
Arabic translation of Full Stack JavaScript Projects  

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4642]
* [ ] Get Set for Basejumps Incomplete
* [ ] Build a Voting App Incomplete
* [ ] Build a Nightlife Coordination App Incomplete
* [ ] Chart the Stock Market Incomplete
* [ ] Manage a Book Trading Club Incomplete
* [ ] Build a Pinterest Clone

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/32
