### ISSUE TITLE
All React Challenges Fail To Load Dependencies

### ISSUE THREAD

**Issue by L4rryFisherman** [freeCodeCamp/freeCodeCamp#46426]
### Describe the Issue

Experiencing [this previously resolved issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38060) currently: `ReferenceError: React is not defined`

(OS x 12.4 Firefox 101.01 (64-bit) & Brave 1.39.111 (arm64)) 

<img width="1146" alt="Screenshot 2022-06-09 at 19 31 06" src="https://user-images.githubusercontent.com/99208478/172908728-5ebe8c5f-fc13-4343-9988-e54bf5912d92.png">

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/create-a-simple-jsx-element

### System

(OS x 12.4 Firefox 101.01 (64-bit) & Brave 1.39.111 (arm64))

**Comment by L4rryFisherman** [comment]
@raisedadead 

Just tried on mobile hotspot, presumably AdGuard is blocking the domain from which the React is being loaded. Which I assume is out-of scope.

**Comment by raisedadead** [comment]
Ah - yeah. Thanks for for confirming.
