### ISSUE TITLE
Arabic translation of Node.js and Express.js  

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4643]
* [ ] Manage Packages with NPM Incomplete
* [ ] Start a Node.js Server Incomplete
* [ ] Continue working with Node.js Servers Incomplete
* [ ] Finish working with Node.js Servers Incomplete
* [ ] Build Web Apps with Express.js

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/33
