### ISSUE TITLE
Typo in challenge text

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46444]
### Describe the Issue

The 100 should be a superscript in the last line of this challenge.

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-168-number-rotations

### Your code

N/A

### Expected behavior

> Find the last 5 digits of the sum of all integers `n`, 10 < `n` < 10100, that have this property.

Should say

> Find the last 5 digits of the sum of all integers `n`, 10 < `n` < 10<sup>100</sup>, that have this property.

We may also consider better mathematical formatting?

### System

All

**Comment by ShaunSHamilton** [comment]
Seems like it has been like this for a while: https://github.com/freeCodeCamp/freeCodeCamp/pull/42782/files#diff-07874ce76ee81c81cbbf0aeef396a6bc5de9a00628ae20572e0fee082849c78c

I will open this up to first timers. The expected fix is to use MathJax (KaTeX-like) to render the following:

$$
n: 10 < n < 10^{100}
$$

---

An issue with the  _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by jeremylt** [comment]
I actually saw a way to roll this into a fix that expands the challenge so that `const myCrapSolution = () => theAnswer` won't work.
