### ISSUE TITLE
Arabic translation of Git Waypoint

### ISSUE THREAD

**Issue by 3laa-Khalil-Alarabi** [FreeCodeCamp/FreeCodeCamp#4644]
* [ ] Save your Code Revisions Forever with Git

**Comment by mohessaid** [comment]
احفظ مراجعات شفرتك للأبد مع Git

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/35
Please continue discussion there.
