### ISSUE TITLE
console preview

### ISSUE THREAD

**Issue by jinlikegold** [freeCodeCamp/freeCodeCamp#46448]
### Describe the Issue

In the new Responsive Web Design course, which I'm going through after completing the Legacy course, the preview window will reset to the top of the screen while adding new code in the console. This means that if I'm adjusting code that affects an element on the lower half of the screen, I can't see the result until I manually scroll down on the preview.

Frequently, especially when it comes to CSS, the adjustments are so minute that the only way to see the difference is to have the preview side by side. As part of learning, especially with the new course design, which minimizes instruction and teaches everything in-line, it would be helpful to see real-time adjustments that the code makes to the preview, by having the scroll stay put while updating or perhaps having a full preview view option.

The link provided is just an example of where this problem occurs, where the task is to modify a button that is at the bottom of the screen.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-61

### Your code

```
n/a
```

### Expected behavior

I expect to be able to see the preview clearly while coding in the console. 

### System

Chrome, latest version

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue https://github.com/freeCodeCamp/freeCodeCamp/issues/46061, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

**Comment by jinlikegold** [comment]
Great, glad it’s been brought up already and thanks for letting me know.
