### ISSUE TITLE
New RWD: Test cases don't pass when you include a space between attribute and its value

### ISSUE THREAD

**Issue by Bharath314** [freeCodeCamp/freeCodeCamp#46453]
### Describe the Issue

In step 17 of Learn Basic CSS by Building a Cafe Menu, using a space between attribute and equals sign results in the code failing.

 I believe this is an issue because it goes against the principle "any valid syntax must be allowed to pass", which means that the tests not passing due to the presence of space is unexpected/ undesired behavior.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-17

### Your code

```html
  <head>
    <link rel = "stylesheet" type = "text/css" href = "styles.css">
    <meta charset="utf-8" />
    <title>Cafe Menu</title>
  </head>
```

### Expected behavior

The test should pass irrespective of whether there is a space present or not.

### Screenshots

![image](https://user-images.githubusercontent.com/69413757/173175062-618a2077-6a47-4a4e-9fe5-ab38697ee1c6.png)

Now if I remove the space between `rel` and `"stylesheet"`
![image](https://user-images.githubusercontent.com/69413757/173175229-4a1b4da3-b396-48a6-998e-033e45387e9c.png)

And after removing the space after `type`
![image](https://user-images.githubusercontent.com/69413757/173175273-44617069-9fb2-4957-ad33-41ebed090c61.png)

The code only passes after removing the space after `href`

### System

All

**Comment by Sboonny** [comment]
Jeremy had similar issue pop up in discord, I am wondering how often does this come up?

Anyway a valid answer should pass.

**Comment by ieahleen** [comment]
The head elements have to be checked with regex, so probably every step that there is such an element tested
