### ISSUE TITLE
Flash message stays displayed even after navigating to another page

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#46468]
### Describe the Issue

I noticed that a flash message stays displayed even after navigating to another page. Was it always like this?

### Affected Page

any

### Steps to Reproduce

1. Perform any action to show a flash message (For example, change some settings)
2. Go to a different page
3. See the flash message

### Expected behavior

Flash message should disappear after navigating to a different page

### Screenshots

![Animation](https://user-images.githubusercontent.com/25644062/173233141-fb8e7139-9f19-4bc5-8dab-3d29f0da49ca.gif)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 102.0.5005.115

**Comment by ShaunSHamilton** [comment]
I think it has always been like this, and this, in my opinion, is expected behaviour.

The flash messages are supposed to be relatively important. So, the only reason they should _disappear_ is when a Camper closes them.

**Comment by Owais28** [comment]
I think some flash messages should disappear after sometime. For example, after signing up successfully a flash notification should disappear itself.

**Comment by sidemt** [comment]
Thank you @ShaunSHamilton . It's OK with me if it was by design. But I also agree with @Owais28 , I thought most of the flash messages are mainly used for letting users know the result of their action and don't need to stay there if user moved on to a different page.

I will close this issue for now as it was not a bug.
