### ISSUE TITLE
Hofstadter Figure-Figure sequences Rosetta challenge needs a better description

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46475]
In the challenge you are given sequences, and instructions. But we lack description of what the issue is. I am wondering if you have suggestions for it, because I can't seem to figure it out, even when researching it and the links didn't help me.

![image](https://user-images.githubusercontent.com/88248797/173300942-f8bd73b9-a70b-4f6f-9737-646c15f05c73.png)

----

Link for the step in freeCodeCamp.org, [coding-interview-prep/rosetta-code/hofstadter-figure-figure-sequences](https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/hofstadter-figure-figure-sequences)

Link for the file in freeCodeCamp repo, [curriculum/challenges/english/10-coding-interview-prep/rosetta-code/hofstadter-figure-figure-sequences.md#L1](https://github.com/freeCodeCamp/freeCodeCamp/blob/ee1e8abd8752df017f57ba8eefd9384f24e4ce61/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/hofstadter-figure-figure-sequences.md#L1)

**Comment by gikf** [comment]
There isn't an issue per se. Goal is to have two functions, `ffr` and `ffs`.

`ffr` returns the value of `R` for the `n`, `ffs` value of `S` for the `n`.

`R` and `S` are sequences that depend on each other.
