### ISSUE TITLE
need to add sudo

### ISSUE THREAD

**Issue by earthshakira** [FreeCodeCamp/FreeCodeCamp#4648]
Challenge [Waypoint: Build Web Apps with Expressjs](http://www.freecodecamp.com/challenges/waypoint-build-web-apps-with-expressjs) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
i encountered the problem in cloud 9. chmod needs a sudo on expressworks wont install it worked fine when i added a sudo before all 3 commands

**Comment by jbmartinez** [comment]
That's weird. I already finished several projects on c9 and I've not needed `sudo`

**Comment by SaintPeter** [comment]
Can you give a more detailed explanation of what commands you tried and how they failed?  Copy and paste your command line and responses?

We periodically get requests like this, but the vast majority of people go through it without trouble.

**Comment by earthshakira** [comment]
The cloud9 works really well but this command :
git clone https://github.com/FreeCodeCamp/fcc-expressworks.git && chmod 744
fcc-expressworks/setup.sh && fcc-expressworks/setup.sh && source ~/.profile

Gave me an error so I had to run it as follows

Sudo git clone https://github.com/FreeCodeCamp/fcc-expressworks.git && sudo
chmod 744 fcc-expressworks/setup.sh && sudo fcc-expressworks/setup.sh &&
source ~/.profile

I over did the sudo

Only the chmod required sudo actually

But it gave like a not enough permissions type of error

Can you give a more detailed explanation of what commands you tried and how
they failed? Copy and paste your command line and responses?

We periodically get requests like this, but the vast majority of people go
through it without trouble.

—
Reply to this email directly or view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4648#issuecomment-158779261>
.

**Comment by SaintPeter** [comment]
I just ran the commands on a fresh instance:
```
saintpeter:~/workspace $ git clone https://github.com/FreeCodeCamp/fcc-expressworks.git
Cloning into 'fcc-expressworks'...
remote: Counting objects: 24, done.
remote: Total 24 (delta 0), reused 0 (delta 0), pack-reused 23
Unpacking objects: 100% (24/24), done.
Checking connectivity... done.
saintpeter:~/workspace $ chmod 744 fcc-expressworks/setup.sh
saintpeter:~/workspace $ ls fcc-expressworks/
README.md  setup.sh*
saintpeter:~/workspace $ 
```
Setup showed as executable.  Did you get an error message or anything?  Did you choose a `node.js` baseline for the workspace?

**Comment by earthshakira** [comment]
Yup I had but I installed npm and updated git may be some bug on my system
cool thanks for the support :)

**Comment by earthshakira** [comment]
Yaa sorry dude ...I checked sorry for the trouble I must have done
something to the workspace sorry

**Comment by SaintPeter** [comment]
Thanks and happy coding!
