### ISSUE TITLE
Making `/settings`' buttons consistent 

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46497]
### Is your feature request related to a problem? Please describe.

There are 3 buttons with different innerText `View`, `Show Code`, `Show Solution`

~~Edit: did I just put same buttons twice🤦🤣, because I am currently away from laptop~~ check [setting](https://www.freecodecamp.org/settings)

![image](https://user-images.githubusercontent.com/88248797/173580640-e3ff6c6a-a3fb-4121-8156-cd681e39e8b8.png)
![image](https://user-images.githubusercontent.com/88248797/173662178-297e0d71-b98a-414e-bbf8-d3c7aab7f6b9.png)

### Describe the solution you'd like

Swapping `Show Code` and `Show Solution` with `View` for consistent look,  while adding `.sr-only` to `span` in the `button` with `innerText` equal to **Code** or **Solution**.

Examples:

``` diff
- <button>Show Code</button>
- <button>Show Solution</button>

+ <button>View <span class="sr-only>Code</span></button>
+ <button>View <span class="sr-only>Solution</span></button>
```

### Describe alternatives you've considered

Nothing, this isn't a true issue. Quality of life change

### Additional context

This idea is originated from full button width

for more info check comment in https://github.com/freeCodeCamp/freeCodeCamp/issues/45947#issuecomment-1130030952

**Comment by ahmadabdolsaheb** [comment]
Speaking of consistency, 

It seems like we have three places where we show lists of projects and their solutions.
1) Portfolio timeline
2) Certification page
3) Settings

Ideally, they should be the same component and the same buttons for displaying the code. 
ref https://github.com/freeCodeCamp/freeCodeCamp/issues/45949

**Comment by Sboonny** [comment]
@Hdanzo yeab that would be lovely 👍.

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by tom-raley** [comment]
Is @Hdanzo working on this? If not, I'd love to take a crack at it. Doesn't seem it's been assigned to anyone 😄

**Comment by Hdanzo** [comment]
@tom-raley Hello! I am working on this at the moment 😄
