### ISSUE TITLE
Cat Photo App - Step 6: Extra spaces after opening main tag causing test to fail

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46492]
### Describe the Issue

The camper's HTML was indented correctly but they accidentally added some extra spaces after the opening `<main>` tag which caused the test to fail.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6

### Your code

```
<html>
  <body>
    <h1>CatPhotoApp</h1>
    <main>        
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos -->
      <p>Click here to view more cat photos.</p>
    </main>
  </body>
</html>
```

### Expected behavior

Test should probably pass even with those extra spaces.

### System

I don't know what system they were on but I'm on:
- Device: [Desktop]
- OS: [Linux - Fedora 34]
- Browser: [Firefox]
- Version: [101]

**Comment by Sboonny** [comment]
You mentioned [in different issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/46443#issuecomment-1153263874)

> P.S. I won't even get started on the accessibility issues caused by forcing people to use a certain number of spaces instead of tabs which allow people to configure the spacing to their own needs :-)

This test has similar issue `assert(code.toLowerCase().match(/<main\>\n\s{6}<h2>/))` , I wonder what you mean by tabs

At first I thought you meant something like this `assert(code.toLowerCase().match(/<main\>\n\s{6,}<h2>/))` but reading it again, I noticed my misunderstanding.

**Comment by bbsmooth** [comment]
That P.S. comment was just me having a little fun with the fact that I can come off as sort of a kill joy because I'm always bringing up accessibility issues that can potentially create extra work. I didn't expect it to be taken seriously and I'm not expecting any of the curriculum to switch from spaces to tabs. But tabs are more accessible, so in the ongoing war between tabs and spaces, tabs win!

**Comment by Sboonny** [comment]
>  I can come off as sort of a kill joy because I'm always bringing up accessibility issues that can potentially create extra work. 

Oh this is embarrassing 😅. Well I don't think anyone thought of your opened issue as a killer joy, unless you have had advocated for Vim or Emacs 🤔

**Comment by jeremylt** [comment]
I wish tabs over spaces was more common....

Anywho, +1 to the idea of adding a test to check that users don't just dump the sample indentation code in

**Comment by Shyamjizoyo** [comment]
i get error in this ?? how to solve ??

**Comment by Sboonny** [comment]
@Shyamjizoyo, Join [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/) if you need help in the challenge, our volunteers will help you there.

**Comment by Shyamjizoyo** [comment]
Please help me !!

**Comment by jeremylt** [comment]
@Shyamjizoyo this is not as appropriate place to ask for help finishing the curriculum. As stated above, you can ask for help on the forum or chat.
