### ISSUE TITLE
Denying permission isn't respected 

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46493]
**Looking forward for reporting a security issue:**

I don't think there is one

**Describe the bug**

In mobile. Try to share img in chat but deny access, this will lead to your file manager to open

**To Reproduce**

1. Go to chat with you mobile device 
2. Click on screen icon
3. Deny
4. Click appropriate IMG
5. See the IMG in chat

**Expected behavior**

 Not to open.

**Video**

https://user-images.githubusercontent.com/88248797/169374029-190bfe35-b135-4bd2-b81b-91c68c5a1de2.mp4

**Desktop (please complete the following information):**

 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**

 - Device: [oppo a55]
 - OS: [android version 11]
 - Browser: [brave]
 - Version: [1.38.113]
 - update Date: [10/may]
 - Chromium version:  [Chromium 101]

**Additional context**

We all agree, that the true solution is allow access everytime option🤣

**Comment by raisedadead** [comment]
Moved the issue to this repo for better visibility and @Sboonny mentioned to me in the chat this is being discussed in the Chrominum tracker here: https://bugs.chromium.org/p/chromium/issues/detail?id=1329080#c7

**Comment by raisedadead** [comment]
And finally, the Chromium team has also closed this as a wontfix, because the behavior is intentional.
