### ISSUE TITLE
Navbar on show html doesn't scale properly

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#465]
Resizing the window has the navbar pop down before the frame moves.

**Comment by piecedigital** [comment]
Which branch is this on? I could take a look at this.

**Comment by terakilobyte** [comment]
challenge-restructure, same issue we were looking at last night. Have a go at it please!

**Comment by QuincyLarson** [comment]
This is now a non-issue with our new text buttons (they take up less horizontal real estate).
