### ISSUE TITLE
New RWD : Concepts like `vh` and `rem` are never explained

### ISSUE THREAD

**Issue by Bharath314** [freeCodeCamp/freeCodeCamp#46502]
### Describe the Issue

In [step 7](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-7) of `Learn HTML Forms by Building a Registration Form`  , we are asked to set the height of the body element to 100vh. However, the unit vh was never introduced in earlier lessons and there is no explanation given at this step too as to what it is.

As I continued through the course, I stumbled upon another unexplained unit `rem` in [step 14](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-14)

`em` isn't explained either in [step 38](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-38) 

Relative units were never explained in the course. The problem seems to be that this practice projects assumes familiarity with these concepts.
 

### Affected Pages

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-7
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-14
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-38

### Your code

n/a

### Expected behavior

 A brief explanation on relative units in CSS would help new learners.

**Comment by Bharath314** [comment]
I'm still going through the course so I'll let you know if they are explained later. But I still feel a brief one line explanation as to what they are is needed at least even if they are explored in detail in later projects. Just dumping them onto learners would only confuse them and send them down a rabbit hole of resources. I know I was.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @Bharath314.

We'll need to take a close look at this project and the ones before and figure out where `vh` and `em` are first introduced. Once we find the first step where each concept is introduced, we'll need to make sure it's properly explained.

**Comment by aharna** [comment]
hey, I would like to work on this issue

**Comment by Ayush-singla27** [comment]
Hey, is it fine to add one line explanations for em and vh wherever it is mentioned first in the project.
Also, can we provide a link like [this](https://www.freecodecamp.org/news/css-unit-guide/) so that the user can look into it if he /she wants to.

**Comment by Al3nMicL** [comment]
> hey, I would like to work on this issue

To contribute, I think you should follow the requirements in this [guide](https://contribute.freecodecamp.org/#/index?id=learning-platform)?... Not a %100 sure, since I've never contributed to the learning platform myself, but this is what I found after some digging around

Please correct me anyone if I am wrong, thanks
