### ISSUE TITLE
Ask for Help/Restart Step buttons take too long to show for some steps

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46513]
### Describe the Issue

I think it is taking too many tries before the Ask for Help/Restart Step buttons appear in the lower jaw for certain steps. The notorious step 6 in the Cat Photo App takes eight attempts! I understand the reasoning for not wanting to show those buttons immediately but I think we may want to put a reasonable max limit on the number of attempts before they show (3 perhaps). Most of these steps only ask the user to make one or two changes. I think after a certain number of attempts if they aren't getting it then they are just going to get frustrated and start trying desperate things (like copy/pasting the code example in step 6 into the HTML).

### Affected Page

Many

### Your code

N/A

### Expected behavior

Display the Ask for Help/Restart Step button consistently after a certain number of tries (such as 3).

### System

N/A

**Comment by jeremylt** [comment]
Yeah, I agree with this. I think maybe 3 would be a good max?

**Comment by ahmadabdolsaheb** [comment]
I don't have any hard data if the current strategy is working or not. We could potentially display both buttons side by side as button icons with hover based tooltips from the first attempt.
