### ISSUE TITLE
Unlimited forms created by spamming add items button in user setting

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46510]
### Is your feature request related to a problem? Please describe.

When you navigate to [/settings](https://www.freecodecamp.org/settings) scroll to portfolio setting and press `Add a new portfolio Item`
![thumb-Clipboard - June 14, 2022 8_34 PM](https://user-images.githubusercontent.com/88248797/173835500-6c4bb81a-8727-4dc7-981a-54b178cfef04.png)
 
 If you keep pressing them a number of times, you will create the same number of forms.

### Describe the solution you'd like

Adding `active` class that stops creating new ones or indicate the button is pressed, so people don't keep spamming it.

### Describe alternatives you've considered

In issue #44668 we are planning to create toggle button, I can try to create it following the guide then swapping it later with the current components

### Additional context

This isn't a true issue, but a quality of life request

**Comment by moT01** [comment]
To clarify a little, each time you click that "Add a new portfolio Item" button, a new form shows up to add an item. You can spam it and have a bunch of forms show up...

![Screen Shot 2022-06-16 at 8 32 11 AM](https://user-images.githubusercontent.com/20648924/174081509-91100a34-ca9f-4073-bde8-d180b6a0c625.png)

The bigger issue I see is that each time you click a save or remove button, it makes a request to the api and saves to the database. I don't think this is overloading our server or database, it's probably minimal - but I think we should find a way to batch update these, similar to what we did with the privacy settings. So, maybe there's one save button at the bottom.

We could also maybe set a maximum number of items? Maybe 10.

**Comment by moT01** [comment]
yea, like I mentioned, I don't think the batch updates are going to save us a ton here - but a little anyway.

> not something we want them to fill in, and forget to find the Save button for

I agree, but I don't think that's really an issue here. The onus is already on the user to click the save button, so that behavior already exists. With the batch updates, users could still click the save button after each form they add, or wait until they add as many as they want before saving. Currently, the remove button makes an api call on each click - batch updates -> you could remove 4 items, then click save, making one api call. I guess the difference would be that you have to click remove then save - whereas now, you just click remove and it saves automatically.

I think I still lean towards the batch updates, but I'm fine with it either way. The difference in api calls would be quite small.

**Comment by scissorsneedfoodtoo** [comment]
We discussed this in an issue triage meeting and decided that adding one form at a time is probably the way to go.

When a camper presses the "Add a new portfolio item" button, a form should be added to the page and the "Add a new portfolio item" button should be disabled or hidden.

Then after the camper fills out the form and presses the "Save this portfolio item" button, the "Add a new portfolio item" button should be re-enabled / unhidden.

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by KravMaguy** [comment]
> We discussed this in an issue triage meeting and decided that adding one form at a time is probably the way to go.
> 
> When a camper presses the "Add a new portfolio item" button, a form should be added to the page and the "Add a new portfolio item" button should be disabled or hidden.
> 
> Then after the camper fills out the form and presses the "Save this portfolio item" button, the "Add a new portfolio item" button should be re-enabled / unhidden.

and after he deletes a form? you will also want the button to be re-enabled, but not in a case where the form he deletes is not the last form added.

**Comment by KravMaguy** [comment]
> The only thing I might change here is to disable `Add a new portfolio item` until a changed item is saved.

If he adds an item and doesnt save it then goes to edit another item and saves it, you will still want the add button to be disabled, else you would be allowing him to create two blank forms
