### ISSUE TITLE
Unordered list will not accept closing tag

### ISSUE THREAD

**Issue by Jarevalo92** [FreeCodeCamp/FreeCodeCamp#4652]
Challenge [Waypoint: Create a Bulleted Unordered List](http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3CUL%3E%0A%20%20%3Cli%3E%20scratching%3C%2Fli%3E%0A%20%20%3Cli%3E%20sleeping%3C%2Fli%3E%0A%20%20%3Cli%3Efish%3C%2Fli%3E%0A%3C%2Ful%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<UL>
  <li> scratching</li>
  <li> sleeping</li>
  <li>fish</li>
</ul>

```

**Comment by ltegman** [comment]
The editor is highlighting your code to let you know something doesn't look right, which in this case is that you open your `ul` with uppercase and close it with lowercase.
![waypoint__create_a_bulleted_unordered_list___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/11326110/1fb7623e-9115-11e5-9a1f-96fd201a22ad.png)
However, despite this being bad practice it is valid markup and should pass. I am putting in a PR to make the regular expressions case insensitive now.

**Comment by Jarevalo92** [comment]
Okay, thank you for the response. Will make sure to get into the habit of being deliberate with casing. Thank you.
