### ISSUE TITLE
Move Legacy RWD to bottom of map

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#46523]
### Is your feature request related to a problem? Please describe.

I'm not sure if we want to implement this yet, but we could discuss it and get a PR ready. We will want to move the legacy RWD to the bottom of the map.

### Describe the solution you'd like

Here's how I might like to see it:
![Screen Shot 2022-06-16 at 8 20 49 AM](https://user-images.githubusercontent.com/20648924/174079126-31d02d68-72b9-4dd2-9d7a-1c45dd9e1826.png)

With better styling, of course. We would also want to remove the cert projects from the legacy RWD. Perhaps that could be done on another PR so there's more of a transition - not sure.

**Comment by Sboonny** [comment]
Because the new JS is coming, too. I was thinking of adding buttons below the quotes, that toggle legacy and updated challenges. 

Something like this, of course with different styling as well.

![image](https://user-images.githubusercontent.com/88248797/174083034-b5b3a08b-c212-41a6-826d-77f7872beaf5.png)

**Comment by JordanMooree** [comment]
> Front End
> 
> * Responsive Web Design
> * Javascript Algorithms and Data Structures
> * Front End Development Libraries
> * Data Visualization

I think this would be a _really good_ approach. Showing the user what type of content they will learn will help them map out a learning roadmap for themselves.

**Comment by Sembauke** [comment]
I really like the idea @jeremylt suggested.

**Comment by ieahleen** [comment]
doesn't information security have Python in it? can we really put it above Python considering the curriculum is a linear path?

**Comment by ahmadabdolsaheb** [comment]
ideally we would only need to have one RWD in the map.
We could have the versions in a dropdown at the top of the intro similar to react bootstrap docs. 
<img width="231" alt="Screen Shot 2022-06-17 at 4 43 01 PM" src="https://user-images.githubusercontent.com/4591597/174310493-165a2789-4d52-4263-84e0-868781b2fe4c.png">

**Comment by jeremylt** [comment]
I think ideally we should kill the legacy versions after a reasonable mourning period - that's maintenance debt that nobody wants to pay. Adding a drop down would make the interface more complex, imho.

Front End
- Responsive Web Design
- Javascript Algorithms and Data Structures
- Front End Development Libraries
- Data Visualization

Back End
- Back End Development and APIs
- Quality Assurance
- Relational Database

Python
- Scientific Computing with Python (not really scientific computing by definition tho)
- Data Analysis with Python
- Machine Learning with Python
- Information Security

Practice Challenges
- Coding Interview Prep

Legacy Curriculum (Retiring Soon)
- Responsive Web Design
- Javascript Algorithms and Data Structures

**Comment by moT01** [comment]
I would vote to keep the legacy curriculum around. Those challenges are significantly different than the step based approach. It's a lot of good content that I hate to just get rid of. I don't think there's much for maintenance debt, we could just say that they are no longer being maintained.

**Comment by ahmadabdolsaheb** [comment]
We would need to keep it around until the localized versions has made the transition.

**Comment by ojeytonwilliams** [comment]
We will need a systematic way to retire old content, eventually, but until it becomes a maintenance problem there's no need to get rid of it.

The reorganisation of the map looks really nice, though.  Simply grouping things make it much clearer and less intimidating.

**Comment by raisedadead** [comment]
> It's a lot of good content that I hate to just get rid of. I don't think there's much for maintenance debt, we could just say that they are no longer being maintained.

I hate to say this, but it can have a counter-effect. People don't read, skim over things, miss, or even outright ignore warnings. It isn't easy to convey the point across. We have seen this. We have known about this.

We could be hurting users by keeping things (APIs, features) that are deprecated and can and do create confusion. Some of the curriculum, like jQuery and React, are embarrassingly behind. They are almost sure to miss the warnings when they land on a challenge outside the learning map, for instance, from the forum.

Understandably, there is good content in there. 

However, it should be made available away from freeCodeCamp proper as archives, where researchers and enthusiasts can still check it out for whatever sentimental value such content may have.

**Comment by ojeytonwilliams** [comment]
Right, and stuff will eventually need to be removed, but remember the vote between the Tom and Naomi doctrines? https://chat.freecodecamp.org/group/dev-team?msg=szHvX99fZLtpR5dCr Ultimately the consensus was that we wanted to keep things "playable" as long as possible, even if that isn't forever. That is to say, we agreed to do it Tom's way.

> However, it should be made available away from freeCodeCamp proper as archives, where researchers and enthusiasts can still check it out for whatever sentimental value such content may have.

That's likely to be the long-term fate, but we decided to keep it around for the time being.

**Comment by moT01** [comment]
I think the long-term fate is a discussion we can revisit later if needed - unless we are sure we want to get rid of them soon, I don't think it's going to change what we need to do next. I would vote to go with something similar to [@jeremylt's initial suggestion.](https://github.com/freeCodeCamp/freeCodeCamp/issues/46523#issuecomment-1157903147) If/when we get to a point where there's many versions of a block, we can maybe move to something like @ahmadabdolsaheb's suggestion - my thoughts anyway.

**Comment by raisedadead** [comment]
> Users could visit older versions from each certification using a dropdown, etc if they choose to do so.

That will not fly when we outright change a certification (superblock) name OR we split a superblock into two or combine two into one.

**Comment by raisedadead** [comment]
> We could have a link or button that takes users to a list of legacy certs.

That & we do not want eyes on it (other than for nostalgic enthusiasts). The point is to "teach" things that are most relevant to land you a job—our end goal.

**Comment by moT01** [comment]
Bumping this since seeing two RWD buttons at the top of the map annoys me.

**Comment by scissorsneedfoodtoo** [comment]
For now let's move the Legacy RWD certification to the bottom of the map, and we can tackle reorganizing the map in separate PRs.

**Comment by moT01** [comment]
Should we remove the cert projects from that superblock at the same time? or just move the button for now?

**Comment by ieahleen** [comment]
Maybe both at the same time, for now the challenges are still there, but that is finally not the current curriculum for the Responsive Web Design. Maybe at the same time Responsive Web Design can loose the New part? If it's the only one it's not new anymore

**Comment by moT01** [comment]
K, so the tasks here:

1. Make the map look like this:
`Responsive Web Design` at the top
`Legacy Responsive Web Design` at the bottom
Just move the buttons for now. We can come up with different labels or headings another time.

2. Remove the certification projects from the Legacy RWD

These should be fairly easy - and we can keep this discussion in mind when we need to come up with something more like some of the suggestions here.

**Comment by JP-GECT** [comment]
Hi, I am a freeCodeCamp user, in my opinion its not a good option to remove or take the legacy courses to the bottom,
wouldn't it  be like depreciating its value?. I would suggest to give it a separate block with equal importance..

**Comment by raisedadead** [comment]
Thanks for your feedback. 

We are retiring these courses because the content has become outdated. We have the newer certifications for you. This way, you can be skilled with the latest concepts and topics.

Also, retiring older certifications doesn't affect you as a user because you still get to keep the certifications you claimed in the past.
