### ISSUE TITLE
HTML validation errors and warnings for Cafe menu practice project 

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#46539]
Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46463#issuecomment-1155180861
The final code of the project has been validated with three different html validators (https://www.freeformatter.com/html-validator.html, https://appdevtools.com/html-validator, https://validator.w3.org/), resulting in these errors and warnings:

~~- [ ] Warning: Article lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all articles. For all 3 validators~~
- [ ] Error: Stray start tag “html”. For all 3 validators
```
From line 62, column 1 to line 62, column 6.
</body> <html>
```
- [ ] Warning: Consider adding a “lang” attribute to the “html” start tag to declare the language of this document. For all 3 validators

**Comment by bbsmooth** [comment]
Yes, generally articles will have a heading near the top describing what the article is about, but it is not a requirement. I think the bigger issue here is whether each of the product/prices in the menu should be an article in the first place, but that's outside the scope of this issue.

**Comment by ajeetk1** [comment]
Headings are not must but essential to grab reader's attention. I believe well crafted heading give glimpse of "big idea" of article and it improves search engine optimization of page. Heading with semantic keywords adds call to attention to the most important idea of article.

**Comment by bbsmooth** [comment]
Oh, and definitely the `html` tag needs a `lang` attribute. This is a level A [WCAG requirement](https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html).

**Comment by ieahleen** [comment]
And the closing html tag needs to be fixed, I will open this for help for the two things

**Comment by Sboonny** [comment]
what is stray start tag `html`? I am creating pr and can't understand it from looking at the code

**Comment by ieahleen** [comment]
> what is stray start tag `html`?

The tag at the end is an opening tag instead of a closing one
