### ISSUE TITLE
Html validation errors and warnings for Magazine practice project

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#46537]
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/46463#issuecomment-1155180861

The final code of the project has been validated with three different html validators (https://www.freeformatter.com/html-validator.html, https://appdevtools.com/html-validator, https://validator.w3.org/), resutling in these errors and warnings:

- [ ] `Warning: This document appears to be written in English. Consider adding lang="en" (or variant) to the html start tag.` reported by all 3
- [ ] `Error: Bad value https://fonts.googleapis.com/css?family=Anton|Baskervville|Raleway&display=swap for attribute href on element link: Illegal character in query: | is not allowed.`, from all 3 validators
This could be solved by swapping `|` with `%7C`
~~- [ ] Warning: Section lacks heading. Consider using h2-h6 elements to [add identifying headings to all sections](https://www.w3.org/wiki/HTML/Usage/Headings/Missing), or else use a div element instead for any cases where no heading is needed.
from all 3 validators~~
~~- [ ] Attribute “loading” not allowed on element “img” at this point.
reported by freeformatter~~

**Comment by bbsmooth** [comment]
I think you can ignore the warning about sections without headings as there is no requirement that they have one. To be honest, as far as accessibility is concerned, sections without an accessible name (assigned through either `aria-label` or `aria-labelledby`) are basically just `div`s as they really have no special meaning to assistive technology. But I understand that they do help authors organize content and may be of use to other consumers of the HTML, so there is use for them outside of accessibility.

**Comment by bbsmooth** [comment]
Oh, and definitely the `lang` attribute needs to be added to `<html>`. [WCAG SC 3.1.1](https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html).
