### ISSUE TITLE
Consider changing monospaced font for code examples

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46530]
### Describe the Issue

I've had two different forum posts today in which the user thought the lowercase L was the number 1 in the HTML code examples, and I have seen this before today as well. I can definitely understand the confusion. In the example below, the user mistook the "ul" element for "u1".

![image](https://user-images.githubusercontent.com/5926192/174152579-ed5feca7-5d16-43ab-8465-6aee914a9118.png)

If I remove Roboto Mono from the font family and just rely on the default monospace font on my computer it looks much more like a lowercase L.

![image](https://user-images.githubusercontent.com/5926192/174153468-7ca5cac6-d809-4e8d-aa06-52d09bc9a412.png)

### Affected Page

Several

### Your code

N/A

### Expected behavior

Find a monospaced font with a better distinction between lowercase L and the number 1.

### System

- Device: desktop
- OS: Fedora
- Browser: Firefox
- Version: 102

**Comment by ahmadabdolsaheb** [comment]
If the issue is wide spread, I am open to finding a better monospaced font across platforms.

**Comment by seths10** [comment]
I agree with @Sboonny. roboto is available on a lot of platforms

**Comment by ahmadabdolsaheb** [comment]
Since we rarely change our fonts, we would need some digging into monospaced fonts to see what we need to consider before choosing one. Then preview code blocks from our challenges in the top choices and pick one.

**Comment by austinjbrock** [comment]
Roboto Flex could easily replace the current font family... Just a thought.

**Comment by ahmadabdolsaheb** [comment]
It seems like we need to be looking for a "namely being sans-serif, fixed-width, slashed zero, and sufficient differentiation between the characters 1, l, |, and I." Here is a helpful [thread](https://ux.stackexchange.com/questions/46142/need-a-font-with-unambiguous-letters-for-commonly-confused-characters).

At the same time, we could see if the vscode or monaco editors' default fonts meet our criteria. If so, they might be a good choice as the users are already familiar with those fonts.

**Comment by bbsmooth** [comment]
I'm using the following string for testing:

`0 O 1 l | I`

The font we are using for monaco does not pass. No slashed zero and the lowercase letter `l` looks too much like the number 1. 

I will start testing fonts and report back with my findings.

**Comment by ieahleen** [comment]
@bbsmooth hey, did you ever went through in your search?

I am for Fira Code
![image](https://user-images.githubusercontent.com/26656284/188907985-4793b241-3be3-42bb-8532-4721a0bc75df.png)

**Comment by scissorsneedfoodtoo** [comment]
There are some great suggestions here already. @ahmadabdolsaheb suggested we could also look at what GitHub, Monaco, and VS Code are using by default.

**Comment by bbsmooth** [comment]
@ieahleen I was actually putting together a quick web app to allow us to compare possible fonts. But then I had a death in the family and had to basically drop everything for the past few weeks. But I'm back now and I'll try to finish up my app in the next few days. Fira Code is definitely on the list.

**Comment by bbsmooth** [comment]
> Roboto Flex could easily replace the current font family

In my opinion, Roboto Flex (as found in Google fonts) does not make enough of a distinction between lowercase letter `l` and uppercase letter `I`.

**Comment by bbsmooth** [comment]
Here's a link to my font comparison web app:

[Font Selector](http://font-selector.surge.sh/)

I'll probably be adding a few more. Let me know if you have any suggestions for other contenders. 

@ieahleen I also think Fira Code is nice but if you look at the JS function example you'll see that it combines certain characters together (such as the arrow operator, >= and <=). While I personally think that looks cool I'm not sure it's a good idea for this site. But Fira Mono appears to be the same thing except it doesn't combine characters, so that might be the better Fira option.

**Comment by ahmadabdolsaheb** [comment]
Thanks for putting the list together. ligatures are great but I am sure new users are going face issues if they cannot find in the keyboard what they see in the example code blocks.

**Comment by ieahleen** [comment]
> I am for Fira Code
> ![image](https://user-images.githubusercontent.com/26656284/188907985-4793b241-3be3-42bb-8532-4721a0bc75df.png)

Fira Mono seems pretty similar
![image](https://user-images.githubusercontent.com/26656284/189138742-bd91f787-921a-4605-ab3f-f1fb81c15b7a.png)
The 0 changes, but the other characters that may be confused have the same level of distinction, so yeah, why not on Fira Mono!
(It seems that removing the ligatures from Fira Code is not that easy)

**Comment by bbsmooth** [comment]
I do like Fire Mono, but I find the ampersand to be a little "weird". I think my real first choice might be Hack (which according to their documentation offers a way to customize glyph styles, so we could have a slashed zero with it). But really, any of these is going to be an improvement over what we have now so I'll be happy with whatever the consensus is.

**Comment by ahmadabdolsaheb** [comment]
We initially almost went with Hack. I like the '&' in Hack better than Fira. If we could have a slashed zero, Hack would be my first choice too. I would like to hear about @ieahleen's feedback before we finalize our choice.

**Comment by ieahleen** [comment]
If the ampersand is weird, maybe Red Hat Mono? It should have everything - no ligatures, a sensible ampersand and a slashed zero. I don't have a particular preference honestly

**Comment by ahmadabdolsaheb** [comment]
Red Hat Mono is a great alternative, but Hack seems to have a larger community behind it.
If you all don't have any objections, I would like to move forward with the slashed Zero Hack.

**Comment by ieahleen** [comment]
Sure, if there is a slashed zero Hack, that would be pretty good

**Comment by bbsmooth** [comment]
I have updated my font web app with a version of Hack with a zero slash. The only difference should be the zero. You can compare the original Hack and the new zero slash version to verify.

**Comment by ieahleen** [comment]
![image](https://user-images.githubusercontent.com/26656284/191704117-d45e41ee-d827-4e95-8082-026a5f490341.png)
 Looking at the various options. the `%` is weird, but it doesn't seem to be so unusual to cause confusion

**Comment by bbsmooth** [comment]
Agreed, the percentage sign could be a little better. I put back all of the other fonts so you can compare with the rest. I do think the percentage sign in something like Fira Mono is slightly better. But I also think that the one in Hack is adequate and will probably not cause confusion. Hopefully this isn't enough of a showstopper to prevent us from moving on with the slashed zero Hack?

If you click on the "Hack-ZeroSlash" heading link in my font web app you can download a zip with the WOFF and WOFF2 files for the font.

**Comment by ieahleen** [comment]
If it was for me, it would have the green light - @ahmadabdolsaheb ?

**Comment by ahmadabdolsaheb** [comment]
It is a green light for me as well. Thank you @ieahleen for your feedback and thank you @bbsmooth for the font web app.

**Comment by ieahleen** [comment]
decided that, are you going to work on it yourself @ahmadabdolsaheb ?

**Comment by ahmadabdolsaheb** [comment]
Some pointers for the interested contributors:
The new fonts should be downloaded and added to the repo.
Every instance of roboto mono should be replaced with hack.

Note: The above-mentioned customized hack repo has a different font format that roboto mono in our repository. Please  evaluate both format and choose the more compatible/faster version.

**Comment by bbsmooth** [comment]
The font formats I used are woff and woff2, which I believe are the recommended formats for the web nowadays and the most popular (except for variable fonts, which I believe still use ttf). They are super compressed formats and thus also faster to load. Just in case anyone missed it above, a link to a zip file with the woff/woff2 files for Hack font with the added slashed zero:

[woff/woff2 font files for Hack with slashed zero](http://font-selector.surge.sh/Hack-ZeroSlash-fonts.zip)

Also, a link to the CSS I used to include them.

[CSS for Hack with slashed zero](http://font-selector.surge.sh/style.css)

**Comment by dannygr664** [comment]
I am happy to take this on!

**Comment by Sboonny** [comment]
Bruce, I am wondering is there an open repo for the site mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1240296183, I want to use something similar for RTL font issue https://github.com/freeCodeCamp/freeCodeCamp/issues/48101#issuecomment-1292098248

**Comment by bbsmooth** [comment]
@Sboonny I didn't put this in a github repo because really it is not worthy as I basically threw it together quickly with no regard for best practices. Fortunately, it only consists of three small files ([index.html](http://font-selector.surge.sh/), [index.js](http://font-selector.surge.sh/index.js), and [style.css](http://font-selector.surge.sh/style.css)). Please feel free to pull them down and modify them for your own purposes.

**Comment by Sboonny** [comment]
Thank you 💚
