### ISSUE TITLE
Html validation errors and warnings for Photo Gallery practice project

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#46538]
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/46463#issuecomment-1155180861

The final code of the project has been validated with three different html validators (https://www.freeformatter.com/html-validator.html, https://appdevtools.com/html-validator, https://validator.w3.org/), resutling in these errors and warnings:

~~- [ ] An “img” element must have an “alt” attribute
None of the image elements have an alt attribute. If they are decorative they could have `alt=""`, otherwise it's good practice to have an alt attribute that describe them. From all validators.~~ discussed in #46579
- [ ] Consider adding a “lang” attribute to the “html” start tag to declare the language of this document.
reported by w3 e appdevtools

**Comment by bbsmooth** [comment]
The validators are right on with this one. These images aren't decorative, they are the main focus of the page, so they should all have descriptive alt text if you want to be accessible. I know the purpose of this course is teaching flexbox, not accessibility. But as an accessibility enthusiast I don't think there is ever a bad time to incorporate accessibility :-) Of course writing good alt text for images isn't as easy as it seems and some of these images are a little more esoteric than others. You might want to consider replacing some of these images with something a little easier to describe. Or if you feel that making the user add alt text is just too out of scope for this course then I would add a note on step 6 explaining that you would normally need to add alt text for each of the images but in the interest of saving time you are intentionally leaving that out.
