### ISSUE TITLE
Legacy Full Stack Certification Issues

### ISSUE THREAD

**Issue by muhammedctgr** [freeCodeCamp/freeCodeCamp#46544]
**Describe the bug**
I have completed the necessary requirements to get the Legacy Full Stack Certification, whenever I click on the claim certification button, it displays nothing, leaving the page as it is, I emailed the support team about this, they agreed i've fulfilled the requirements to get Legacy Full Stack certified and they said its a bug, and I should open a github case about it, so here I am.
please help.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [chrome]
 - Version: [102.0.5005.115 (Official Build) (64-bit)]

**Additional context**
My username is muhammedctgr and my name is Popoola Muhammed

**Comment by raisedadead** [comment]
@freeCodeCamp/dev-team to investigate

**Comment by muhammedctgr** [comment]
hi pls whats the status on this?

**Comment by ieahleen** [comment]
@muhammedctgr it needs to be investigated

**Comment by muhammedctgr** [comment]
> @freeCodeCamp/dev-team to investigate

says page not found....

**Comment by muhammedctgr** [comment]
> @muhammedctgr it needs to be investigated

noted, thank you. i'll wait.

**Comment by muhammedctgr** [comment]
Many thanks to the dev team, I really appreciate the efforts...does this mean its been fixed? Still unable to claim the cert tho.

**Comment by ShaunSHamilton** [comment]
@muhammedctgr Once the next production build is deployed, this fix should be in. We typically do 1 - 2 deployments each week.

**Comment by nhcarrigan** [comment]
This should be live now!

**Comment by muhammedctgr** [comment]
👏🏼👏🏼🕺🏽....really appreciate this, I've been able to claim the full stack cert. Promise to make FCC proud.
