### ISSUE TITLE
Html validation errors and warnings for Accessibility quiz practice project

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#46541]
Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46463#issuecomment-1155180861
The final code of the project has been validated with three different html validators (https://www.freeformatter.com/html-validator.html, https://appdevtools.com/html-validator, https://validator.w3.org/), resulting in these errors and warnings:

- [ ] Warning : The “region” role is unnecessary for element “section”. From all 3 validators
- [ ] The “date” input type is not supported in all browsers. Please be sure to test, and consider using a polyfill. Just from freeformatter validator
```
From line 39, column 6 to line 39, column 60
Code Extract:
bel>↩ <input type="date" id="birth-date" name="birth-date" />
```

**Comment by ieahleen** [comment]
COnsidering that, I am closing this as wontfix
