### ISSUE TITLE
Additional Check needed

### ISSUE THREAD

**Issue by bighitbiker3** [FreeCodeCamp/FreeCodeCamp#4655]
Challenge [Bonfire: Roman Numeral Converter](http://www.freecodecamp.com/challenges/bonfire-roman-numeral-converter?solution=function%20convert(num)%20%7B%0Anum%20%3D%20%5Bnum%20-%20(num%20%25%20100)%2C%20(num%20%25%20100)%20-%20(num%20%25%2010)%2C%20(num%20%25%2010)%5D%3B%20%20%20%20%0A%20%0A%20%20var%20romans%20%3D%20%5B%27M%27%2C%20%27CM%27%2C%20%27DCCC%27%2C%20%27DCC%27%2C%20%27DC%27%2C%27D%27%2C%20%27CD%27%2C%20%27CCC%27%2C%20%27CC%27%2C%20%27C%27%2C%20%27XC%27%2C%20%27LXXX%27%2C%20%27LXX%27%2C%20%27LX%27%2C%20%27L%27%2C%20%27XL%27%2C%20%27XXX%27%2C%20%27XX%27%2C%20%27X%27%2C%20%27IX%27%2C%20%27VIII%27%2C%20%27VII%27%2C%20%27VI%27%2C%20%27V%27%2C%20%27IV%27%2C%20%27III%27%2C%20%27II%27%2C%20%27I%27%5D%3B%0A%20%20var%20numbers%20%3D%20%5B1000%2C%20900%2C%20800%2C%20700%2C%20600%2C%20500%2C%20400%2C%20300%2C%20200%2C%20100%2C%2090%2C%2080%2C%2070%2C%2060%2C%2050%2C%2040%2C%2030%2C%2020%2C%2010%2C%209%2C%208%2C%207%2C%206%2C%205%2C%204%2C%203%2C%202%2C%201%5D%3B%0A%20var%20romanNumeral%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20num.length%3B%20i%2B%2B)%0A%20%20%20%20for(var%20x%20%3D%200%3B%20x%20%3C%20romans.length%3B%20x%2B%2B)%0A%20%20%20%20%20if%20(num%5Bi%5D%20%3D%3D%20numbers%5Bx%5D)%7B%0A%20%20%20%20%20%20console.log(numbers%5Bx%5D)%3B%0A%20%20%20%20%20%20romanNumeral.push(romans%5Bx%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20var%20romansDone%20%3D%20romanNumeral.join(%27%27)%3B%0A%20return%20romansDone%3B%0A%0A%7D%0A%0Aconvert(1123)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(num) {
num = [num - (num % 100), (num % 100) - (num % 10), (num % 10)];    
 
  var romans = ['M', 'CM', 'DCCC', 'DCC', 'DC','D', 'CD', 'CCC', 'CC', 'C', 'XC', 'LXXX', 'LXX', 'LX', 'L', 'XL', 'XXX', 'XX', 'X', 'IX', 'VIII', 'VII', 'VI', 'V', 'IV', 'III', 'II', 'I'];
  var numbers = [1000, 900, 800, 700, 600, 500, 400, 300, 200, 100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1];
 var romanNumeral = [];
  for (var i = 0; i < num.length; i++)
    for(var x = 0; x < romans.length; x++)
     if (num[i] == numbers[x]){
      console.log(numbers[x]);
      romanNumeral.push(romans[x]);
          
    }
  var romansDone = romanNumeral.join('');
 return romansDone;

}

convert(1023);

```
Here is my code for this one.  Notice that it passes all tests, but if the number is say convert(1123), it doesn't work.

**Comment by SaintPeter** [comment]
Confirmed.

It looks like we need some tests for greater than 1000.

I'm thinking 1023, 2014, and 3999.
