### ISSUE TITLE
feature: support for baseUrl in the tsconfig.json in project

### ISSUE THREAD

**Issue by palashgdev** [freeCodeCamp/freeCodeCamp#46555]
### Is your feature request related to a problem? Please describe.

In source code there are many place in which we can find `../../../utils` 

### Describe the solution you'd like

By using baseUrl in tsconfig.json or path to specific repo

```
baseUrl: './src'
paths: {
"@/client":"./client"
}
```

### Describe alternatives you've considered

https://www.typescriptlang.org/tsconfig#baseUrl
https://www.typescriptlang.org/tsconfig#paths

### Additional context

https://www.typescriptlang.org/tsconfig#baseUrl
https://www.typescriptlang.org/tsconfig#paths

**Comment by ojeytonwilliams** [comment]
I'd rather not, honestly. My experience with this is that it makes the integration with tooling and other frameworks consuming the TS that bit more difficult. Considering that the gain (nicer import paths) is minor, I don't think it's worth it.

Finally, I'm not 100% convinced that the nicer paths are actually better. Since they look like package imports, the reader has to spend a moment checking if they're importing a local module or an npm package.

I may be missing something obvious, but I don't think we should go this direction.

**Comment by palashgdev** [comment]
>Finally, I'm not 100% convinced that the nicer paths are actually better. Since they look like package imports, the reader has to spend a moment checking if they're importing a local module or an npm package.

 - probably there are annotation that  comes into a picture like `@/utils` => from this we know that we are importing from local utils

- also let's say we are migrating or using the same utils in two different levels/components, as their path would be different but with this, we know which file it is pointing to

one good example is https://github.com/freeCodeCamp/freeCodeCamp/issues/44668 we would know we are importing from components 

also, there are many open-source [packages](https://github.com/mui/material-ui/blob/master/tsconfig.json#L16) which use baseUrl and path

> I'd rather not, honestly. My experience with this is that it makes the integration with tooling and other frameworks consuming the TS that bit more difficult. Considering that the gain (nicer import paths) is minor, I don't think it's worth it.

yeah totally agree but it comes with great developer experience

**Comment by ShaunSHamilton** [comment]
Hello there,

I agree with Oliver on this one; more native configs makes reading and maintaining the code easier. Also, with how powerful text editors have become, changing an exported components path is relatively hassle free.
