### ISSUE TITLE
Storybook setup is broken

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/freeCodeCamp#46584]
**Describe the bug**
A storybook tool fails to run.

**To Reproduce**
1. clone project 
2. run 'npm run storybook'
3. you will see following error at terminal

![image](https://user-images.githubusercontent.com/1336862/174602319-7dfea22a-6811-4c13-a266-a346455831a0.png)

**Desktop (please complete the following information):**
 - OS: windows, Ubuntu
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Possible solution:
comment out line 99 of `tools/ui-components/tailwind.config.js` file:
![image](https://user-images.githubusercontent.com/1336862/174609142-fe5655e2-4a45-49a2-8e01-fc6da5e5bada.png)

**Comment by ojeytonwilliams** [comment]
@shootermv thanks for the report.  I'm not 100% sure when this broke, but since that particular variant was added two months ago, it's likely not just that.

cc: @huyenltnguyen @ahmadabdolsaheb 

To catch this sooner, is it possible to use `--smoke-test` to write a basic "Does this start?" test?

**Comment by shootermv** [comment]
as far as i can see, tailwind want their variant to be prefixed with '@' or '&' -
![image](https://user-images.githubusercontent.com/1336862/174840407-6aa97110-ce8d-4407-955f-cf3a6c014cb5.png)
so, i can see that using :
`   plugin(({ addVariant }) => {
      addVariant('aria-disabled', '&[aria-disabled="true"]');
    })`
makes storybook not fail
