### ISSUE TITLE
Can't figure out how to call this constructor. I keep getting an error. Is it a bug?

### ISSUE THREAD

**Issue by dperygin** [FreeCodeCamp/FreeCodeCamp#4658]
Challenge [Waypoint: Make Unique Objects by Passing Parameters to our Constructor](http://www.freecodecamp.com/challenges/waypoint-make-unique-objects-by-passing-parameters-to-our-constructor?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2FChange%20this%20constructor%0A%20%20this.wheels%20%3D%202%3B%0A%20%20this.seats%20%3D%203%3B%0A%20%20this.engines%20%3D%202%3B%0A%7D%3B%0A%0A%2F%2FTry%20it%20out%20here%0Avar%20myCar%20%3D%20new%20Car(3%2C%202%2C%201)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A(function()%20%7Breturn%20JSON.stringify(myCar)%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  //Change this constructor
  this.wheels = 2;
  this.seats = 3;
  this.engines = 2;
};

//The next line is the one that I edited. It looks correct to me. 
var myCar = new Car(3, 2, 1);

// Only change code above this line

(function() {return JSON.stringify(myCar);})();

I get this error: Calling new Car(3,1,2) should produce an object with a wheels property of 3, a seats property of 1, and an engines property of 2. Am I missing something?

```

**Comment by ltegman** [comment]
The instructions are also asking you to modify the constructor itself to use those parameters.

In the future please ask for help with challenges in the [Help Chat](https://gitter.im/FreeCodeCamp/Help)

Thanks and happy coding!

**Comment by dperygin** [comment]
Sorry. I got it.

**Comment by HasanatJahan** [comment]
`var Car = function(wheels, seats, engines) {
  //Change this constructor
  this.wheels = 4;
  this.seats = 5;
  this.engines = 1;
};

//Try it out here
var myCar=new Car (0,1, 2);`

This isn't passing, what's wrong with this?
