### ISSUE TITLE
Not explicit test in step 12 of Penguin project of new RWD

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#46598]
### Describe the Issue

The description says: Use the `margin `property to horizontally center the `.penguin` element, and set the `margin-top` to `75px`.

Maybe we should explicitly say in the description that the test requires that `margin-bottom: auto` or change the test.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/619699c10a0f6e11591d73c4.md

### Your code

 The code
`margin: 75px auto 0;`
or
```
margin-top: 75px;
margin-left: auto;
margin-right: auto;
```
does not pass because the test requires that also `margin-bottom` is set to `auto`. So the accepted code is `margin: 75px auto auto;`.

### Expected behavior

From reading the description I understand that the requirements involve `margin-left` and `margin-right` (value of `auto`) and `margin-top` (value of `75px`). I didn't expect to need also` margin-bottom: auto`.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bakerfield** [comment]
had a hard time figuring this out. thanks young king
