### ISSUE TITLE
remove quote from negative source in Magazine project

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#46606]
A user on the forum (https://forum.freecodecamp.org/t/any-chance-a-lesson-example-featuring-a-woody-allen-quote-could-be-replaced/520343) ask if we can replace the Woody Allen's quote

**Comment by nhcarrigan** [comment]
This is just a matter of replacing the image found at https://github.com/freeCodeCamp/cdn/blob/main/build/testable-projects-fcc/images/random-quote-machine.png to display a different quote.

**Comment by rooben-me** [comment]
@nhcarrigan can I take this issue , This is my first time contributing to open source :)

**Comment by ieahleen** [comment]
Hey @rooben-me, we typically do not assign issues to anyone other than long-time contributors.
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ieahleen** [comment]
@rabtennamgyal as long as it's appropriate I would say yes

**Comment by rabtennamgyal** [comment]
@ieahleen Can someone please check my pull request ??

**Comment by ieahleen** [comment]
@rabtennamgyal remember to link the original issue, so that people are aware that you have made a pull request that closes it. Only Liam-boston PR is linked here.
To link an issue in a different repository, paste the whole link in the `Closes` line of the PR template
