### ISSUE TITLE
Add forward and backward buttons to tools/challenge-editor

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#46611]
Currently, the challenge editor needs you to go back to the listing of all challenges to move between challenges.
We want to make this be possible without leaving the code editor page.

cc: @ojeytonwilliams

**Comment by nhcarrigan** [comment]
We do have keyboard shortcuts for this, specifically intended for power users. I'm not sure if we need buttons for this, since the curriculum is designed to be linear.

**Comment by ojeytonwilliams** [comment]
@nhcarrigan this would be for the challenge-editor dev tool, not the monaco editor.  

@thecodingaviator and I were discussing possible improvements and I suggested that it might be nice to be able to navigate between steps directly rather than having to go back to, say, http://localhost:3300/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz each time.

**Comment by thecodingaviator** [comment]
![image](https://user-images.githubusercontent.com/34807532/174982963-50ebd94a-6bb2-4dd3-885e-358639499287.png)
@ojeytonwilliams from what I see, the code that needs to change is being done here  in "tools\challenge-editor\api\utils\getStepContent.ts"
Which is the API code that sends the data here "tools\challenge-editor\client\src\components\editor\Editor.tsx"
![image](https://user-images.githubusercontent.com/34807532/174983435-62f9c6dc-ee46-4ef9-8755-6499ab0e6f77.png)

I am having difficulty figuring out how to get the path name of the next challenge in the API code. Any ideas?

**Comment by ojeytonwilliams** [comment]
I'd start by looking at

https://github.com/freeCodeCamp/freeCodeCamp/blob/a0c081348840bac9a6e28dc5b613248dd9d2eb89/tools/challenge-editor/api/utils/getSteps.ts#L9-L11

specifically the challenge order.  If you know the current step id and have access to the challenge order it should be reasonably straightforward to find the previous and next steps.

**Comment by jeremylt** [comment]
I'm not really sure that I see why this is needed either.

Anywho, a side effect of this will be users clicking ahead one step, copying the answer, and untimately ending up deep in the course with no skills but copy and paste. Are we ok with this outcome?

**Comment by thecodingaviator** [comment]
Hi @jeremylt , I believe this is for the `challenge-editor` which is a tool. I am attaching a screenshot below

![image](https://user-images.githubusercontent.com/34807532/175052913-cf5c6324-6697-49d9-9cc4-1a7d5e38250f.png)

@ojeytonwilliams can provide more context

**Comment by jeremylt** [comment]
Ah. This is a new whatchamacallit to me.

**Comment by Sembauke** [comment]
I am closing this as stale and can be revisited in the future if there is still any interest.
