### ISSUE TITLE
username shouldn't include "freecodecamp" (forum & learn)

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#46637]
we have a bunch of forum users (that are not official accounts) that have "freecodecamp" in their username

![image](https://user-images.githubusercontent.com/26656284/175370001-1257b4d9-a215-4548-9312-72a0f861ab14.png)

I don't think such usernames should be allowed

**Comment by ShaunSHamilton** [comment]
We can easily restrict them, but none of them appear to be impersonating.
<img width="584" alt="image" src="https://user-images.githubusercontent.com/51722130/175400435-d985ab62-a5ce-41d2-ad81-6ec1ca10caae.png">

**Comment by ieahleen** [comment]
It would be a precaution, plus it could cause confusion to other users if someone with such username would be active in the forum

**Comment by ahmadabdolsaheb** [comment]
The block list needs to be updated (freecodecamp) for learn [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/config/constants.js#L73)

The reserved usernames for the forum has been updated accordingly.
