### ISSUE TITLE
The code compiles, gives me all the right outputs for the given inputs, but the website doesn't register any of them as valid,

### ISSUE THREAD

**Issue by thehumanmeshnet** [FreeCodeCamp/FreeCodeCamp#4664]
Challenge  Bonfire: Steamroller  http://www.freecodecamp.com/challenges/bonfire-steamroller?solution=var%20B%20%20%20%20%20%3B%20FUNCTION%20steamroller%20arr%20%20%7B%20FUNCTION%20steamrolle%20array%20%20%7B%20%2F%2F%20I%20m%20a%20steamroller%2C%20baby%20%2F%2Fvar%20A%20%20%20%20%20%3B%20%2F%2F%20return%20%3B%20if%20Array.isArray%20array%20%20%20%7B%20for%20var%20i%20%20%200%3B%20i%20%20%20array.length%3Bi%2B%20%20%7B%20steamrolle%20array%20i%20%20%3B%20%7D%20%7D%20else%20B.push%20array%20%3B%20%7D%20steamrolle%20arr%20%3B%20return%20B%3B%20%7D%20steamroller%20%201%2C%20%7B%7D%2C%20%203%2C%20%20%204%20%20%20%20%20%3B%20%20%20has%20an%20issue.%20User%20Agent%20is%3A%20code%3EMozilla%2F5.0%20%20Windows%20NT%2010.0%3B%20WOW64%3B%20rv%3A41.0%20%20Gecko%2F20100101%20Firefox%2F41.0%20%2Fcode%3E.%20Please%20describe%20how%20to%20reproduce%20this%20issue%2C%20and%20include%20links%20to%20screenshots%20if%20possible.%20My%20code%3A%20%20%20%20javascript%20var%20B%20=%20%20%20%3B%20FUNCTION%20steamroller%20arr%20%20%7B%20FUNCTION%20steamrolle%20array%20%20%7B%20%2F%2F%20I%20m%20a%20steamroller%2C%20baby%20%2F%2Fvar%20A%20=%20%20%20%3B%20%2F%2F%20return%20%3B%20if%20Array.isArray%20array%20%20%20%7B%20for%20var%20i%20=%200%3B%20i%20%20%20array.length%3Bi+%20%20%7B%20steamrolle%20array%20i%20%20%3B%20%7D%20%7D%20else%20B.push%20array%20%3B%20%7D%20steamrolle%20arr%20%3B%20return%20B%3B%20%7D%20steamroller%20%201%2C%20%7B%7D%2C%20%203%2C%20%20%204%20%20%20%20%20%3B%20%20%20%20%20

**Comment by ltegman** [comment]
The link included with your bug has very broken code. Please copy and paste the code you are trying to run that you think should work.

**Comment by ltegman** [comment]
Closing as not an issue with FCC.

Thanks and happy coding!
