### ISSUE TITLE
Replace images used for flexbox gallery challenge

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46640]
### Describe the Issue

I think we need to replace some of the images used for this project as they look to be an advertisement for a third-party website `devalert.me`.

https://twitter.com/devalertme

@QuincyLarson Sorry to bother you, but I was wondering if we have any freeCodeCamp images that are available for public usage. Maybe we can use some images from a meetup or something like that for this project instead?

### Affected Page

To see the images: https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-21

### Your code

```

```

### Expected behavior

Use neutral, or freeCodeCamp related images.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by lasjorg** [comment]
Fork the CDN repo, and clone it down locally.

https://github.com/freeCodeCamp/cdn

Replace the images in the folder `build/curriculum/css-photo-gallery` and push the changes.

---

But we do not have any new images yet so there is nothing to replace them with.

**Comment by staranbeer** [comment]
[link to pull request](https://github.com/freeCodeCamp/cdn/pull/146

**Comment by lasjorg** [comment]
@ShaunSHamilton @nhcarrigan What are we going to do here? Do we just use the puppy images from the PR or what?

I really do not see how we can keep the current images and I'm not sure why they were approved. Do they not violate the fCC rules of no third-party promotion?

**Comment by ShaunSHamilton** [comment]
@lasjorg Thank you for the ping. I have forwarded this to Quincy.

IMO, provided any images we use do not require attribution - we would like to attribute, but it gets difficult to do in the curriculum content.

**Comment by QuincyLarson** [comment]
Thanks for pointing this out. We are not sure how the use of these images passed QA, but it looks like the PR was merged 3 years ago. We can replace them with Creative Commons 0 images – preferably smaller file sizes, and hosted on freeCodeCamp's CDN. We might want to use cats to go with our theme.
