### ISSUE TITLE
Language specific subpaths should have translated meta.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#46646]
### Describe the Issue

Localized subpaths display english meta. 

### Affected Page

https://www.freecodecamp.org/portuguese/

### Steps to Reproduce

If you search "freeCodeCamp Portuguese" you see English meta instead of Portuguese.

### Expected behavior

We want to make sure all /learn subpaths that are indexed and use the correct language's title, description, and other meta information, and that it shows up on Google.

### Screenshots

<img width="1027" alt="Screen Shot 2022-06-24 at 4 09 08 PM" src="https://user-images.githubusercontent.com/4591597/175542576-c9d10026-a708-4dcb-8edb-14da4c76fbc3.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ahmadabdolsaheb** [comment]
@nhcarrigan, the meta for some of the languages such as Spanish has been ported. I was wondering what would be the best way to get the rest translated and ported as well.

**Comment by nhcarrigan** [comment]
We chose not to upload them because they aren't necessarily one-to-one translations. Things like keywords will be changed entirely to fit the more common search terms for the language and such.

**Comment by nhcarrigan** [comment]
@ahmadabdolsaheb the `meta-tags.json` files need to be updated directly on GitHub. Here is the Portuguese one: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/portuguese/meta-tags.json

**Comment by ahmadabdolsaheb** [comment]
Cool, I will just ask our i18n team to update them directly.

**Comment by ojeytonwilliams** [comment]
Could we just make the keywords a special case then?  The rest look to be translatable.

**Comment by ahmadabdolsaheb** [comment]
@naomi-lgbt,  was wondering what you think about Oliver's last comment.

**Comment by naomi-lgbt** [comment]
The challenge then would be to run it through crowdin without overwriting the keywords

**Comment by ahmadabdolsaheb** [comment]
The meta files has been updated. @ieahleen could you update the docs accordingly so we have some guidance for the next update.

**Comment by naomi-lgbt** [comment]
https://contribute.freecodecamp.org/#/language-lead-handbook?id=how-to-update-the-site-meta-data We do have this in our docs already.

**Comment by ahmadabdolsaheb** [comment]
@naomi-lgbt, Thanks for letting me know. In that case, I will proceed with closing this issue. 
@ieahleen, let me know if this issue has been closed by mistake.
