### ISSUE TITLE
Step 12 requirements are not clear in cat photo app project

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#46679]
### Describe the Issue

`Step 12
Turn the words cat photos located inside p element into a link using the same value for the href attribute as the link below the p element. The p element should show the same text in the browser, but the words cat photos should now be a link. Make sure to remove the a element with the text cat photos on the line below the p element.
`

I can't understand the requirements. 
I know  `a`  is in `p` ,  but I  I don't know is add link to `cat photos `，not add link to `Click here to view more cat photos`

at finish ,I understand from file  `14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md`.

The  test code 
```js
const nestedAnchor = $('p > a')[0];
assert(
  nestedAnchor.getAttribute('href') === 'https://freecatphotoapp.com' &&
    nestedAnchor.innerText.toLowerCase().replace(/\s+/g, ' ') === 'cat photos'
);
```

It is no clear for newbie

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

```
 <p>Click here to view more <a href="https://freecatphotoapp.com">cat photos</a></p>
```

### Expected behavior

No descript

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Chrome
- Version: [102.0.5005.115]

**Comment by Sboonny** [comment]
I see three post in the forum related to this step, whenever I open it.

> Step 12 Turn the words cat photos located inside p element into a link

I think this line is confusing people the most. What I mostly see is `<a href="cat photo"></a>`


> Make sure to remove the a element with the text cat photos on the line below the p element.

I think this line is confusing people too. What I see is people deleting the line, not the link 

```html
<p>Click here to view more <a href="cat photos">cat photos</a></p><a href="https://freecatphotoapp.com">cat photos</a>
```

I suggest

> Create Anchor tag that wraps around <em>cat photos</em> text in the `p` tag, the new `a` element will have `href` attribute that navigate to the same link of the previous challenge. Make sure to remove the obsolete old `a` element below the `p` element.

**Comment by Sboonny** [comment]
@luojiyin1987 the file hasn't changed https://github.com/freeCodeCamp/freeCodeCamp/blob/430f45655e50fd58b7162ad1082075a15ae076b3/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md#L3

@salehmalik121 Pull request was to his own fork, it didn't change freeCodeCamp original repo

**Comment by luojiyin1987** [comment]
@Sboonny   thank you!

**Comment by jeremylt** [comment]
This back and forth in the PR probably is an indication that this was not ready for contribution yet....

Original text:
```
Turn the words `cat photos` located inside `p` element into a link using the same value for the `href` attribute as the link below the `p` element. The `p` element should show the same text in the browser, but the words `cat photos` should now be a link. Make sure to remove the `a` element with the text `cat photos` on the line below the `p` element.
```

I've had good success on the forum by saying that the anchor element is being moved to replace the text `cat photos` in the `p`.

Possible fix:
```
The phrase `cat photos` shows up twice in our webpage. Replace the words `cat photos` located inside `p` element with the entire 'a' element. The `p` element should show the same text in the browser, but the words `cat photos` should now be a link. Remove the `a` element with the text `cat photos` on the line below the `p` element.
```

**Comment by Liam-boston** [comment]
^ very helpful, thank you.

**Comment by Wunmi93** [comment]
``p``

**Comment by Wunmi93** [comment]
Possible fix:

Try putting the link in the anchor tag. inside the ``p`` tag text.
