### ISSUE TITLE
Sitelink snippets on Google search results should include relevant information

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#46674]
### Describe the Issue

Most freeCodeCamp related search results display snippets from a footer <p> tag instead of related information.

### Affected Page

freecodecamp.org

### Steps to Reproduce

When freeCodeCamp related topics are searched on Google, the results' snippets include the same <p> tag from the footer.

<img width="750" alt="Screen Shot 2022-06-26 at 6 03 58 PM" src="https://user-images.githubusercontent.com/4591597/175822740-fc1f7ad2-5ffb-4c27-a1a1-47ad664d917c.png">

### Expected behavior

Snippets should include relevant information to the indexed page.

Here are a few ways we could tackle this:

1. Adding relevant meta description tags: This could be archived through manually or automatically adding description to the indexed page. 

2. Providing structured data for rich results: Google offers a variety or custom search results depending on the searched topic. We could include the relevant script tag to display our search results a course carousel.

Related links:
[Control google search snippets](https://developers.google.com/search/docs/advanced/appearance/snippet)
[SiteLinks](https://developers.google.com/search/docs/advanced/appearance/sitelinks)
[Structured data for courses carousel](https://developers.google.com/search/docs/advanced/structured-data/course)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by raisedadead** [comment]
Can we move this out of triage if this is a known bug and tag accordingly?

**Comment by ahmadabdolsaheb** [comment]
@Hdanzo, yes please. Assignment is not needed.

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ahmadabdolsaheb** [comment]
@Hdanzo, this issue seems to be more involved than I expected, so it would be better if a team member with access work on it.

@raisedadead could you please provide some guidance on the next steps?

**Comment by raisedadead** [comment]
This issue needs more elaborate description before anyone can work on it. I will try and summarize this before opening up for contributions.

**Comment by Hdanzo** [comment]
Well, I am kind of confused now. Would this be open for contributing at some point then or is it only for team members? 
Since I already worked on it and have something that I think might work, should I just stand by for any requirement changes?

**Comment by raisedadead** [comment]
@Hdanzo 

Sorry about the confusion. 

This issue came up in a meeting earlier today, and we figured that the issue goes deeper than the OP. So while you can still work on this, it will probably need more implementation (not just changing code in the repository, but more stuff elsewhere) to completely address what Google is indexing.

I am still in the process of analyzing the whole setup. 

That said, please feel free to open a PR with whatever you have and we will take it in after a review.

Cheeers.

**Comment by moT01** [comment]
Closing since the linked issue seems to have fixed this. Thanks and happy coding 🎉
