### ISSUE TITLE
Challenges request is not clear in  https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-15

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#46686]
### Describe the Issue

```plain
Step 15
Before adding any new content, you should make use of a section element to separate the cat photos content from the future content.

Take all the elements currently located within the main element and nest them in a section element.
```
what the meaning of  ` Take all the elements currently located within the main element and nest them in a section element` ?
```html
<section>
   <main> ....</main>
</section>
```
or 
```html 
<main>
   <section>....</section>
</main>
```  
 ????
  I know how to do from  the hint `
The existing h2, comment, p element, and anchor (a) element should be between the opening and closing tags of the section element.`

if add  the hint to   challenges request,   people will understand easylly.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-15

### Your code

```html
   <main>
      <section>
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos -->
      <p>Click here to view more <a target="_blank" href="https://freecatphotoapp.com">cat photos</a>.</p>
      <a href="https://freecatphotoapp.com"><img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back."></a>
     </section>
    </main>
```

### Expected behavior

no descript

### System

- Device: [Laptop]
- OS: [ Windows 10]
- Browser: [Chrome, ]
- Version: [102.0.5005.115]

**Comment by jeremylt** [comment]
I don't think this change is needed. `Nested` is a term of the art that should be used.

**Comment by luojiyin1987** [comment]
Are  you sure ?

**Comment by jeremylt** [comment]
Am I sure that nested is a term of the art? Yes

**Comment by jeremylt** [comment]
'Nested' is a technical term. We need to consistently use technical language correctly. 

We don't want to make the challenge text too long because people don't all of the text even when it's short. Verbose additional explanations belong in the hints.

I thought that we had the term 'nested' in Step 5, but I don't see it, so we should put it back there.

**Comment by luojiyin1987** [comment]
```plan
Take all child  the elements currently located within the main element and nest them in a section element
```
Is more clear?

**Comment by jeremylt** [comment]
I still say we should not add more text to this lesson.

We should use the word 'nested' on Step 5.

**Comment by luojiyin1987** [comment]
my meaning is   not add `The existing h2, comment, p element, and anchor (a) element should be between the opening and closing tags of the section element.` to   this lesson. 
But  change  `Take all the elements currently located within the main element and nest them in a section element`  to  `Take all child  the elements currently located within the main element and nest them in a section element`

**Comment by gikf** [comment]
For me adding _child_ to the sentence doesn't change anything, it's implied that all elements within other element are children elements of it.

Is the need to see hint to get deeper understanding about the task something bad?
