### ISSUE TITLE
Strict step 1 with spacing, at building a cafe menu project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46695]
### Describe the Issue

In step 1 of building a cafe menu, the `lang` attribute test is strict with space

Here is the markdown file 

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f33071498eb2472b87ddee4.md#L22-L27

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-1

### Your code

```html
<!DOCTYPE html>
  <html lang = "en">
  </html>
```

### Expected behavior

The code above should pass, for this to happen you should change

```js
assert(code.match(/<html\s+lang=('|")en\1\s*>/i));
```

to 

```js
assert(code.match(/<html\s+lang\s*=\s*('|")en\1\s*>/gi));
```

### Screenshots

![image](https://user-images.githubusercontent.com/88248797/176218233-5008e017-ad4f-49f1-a260-74779e118a89.png)

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by SwapnilThatte** [comment]
Can I work on this issue ?
