### ISSUE TITLE
Link in stern-brocot-sequence.md doesn't work

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#46691]
I think it needs to be fixed. It makes the string on Crowdin incredibly confusing.

File is https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/stern-brocot-sequence.md

/cc @Sboonny

**Comment by Sboonny** [comment]
btw, how do you translate anchor with link, as it's text

example 

```html
<a href="https://image-search-abstraction-layer.freecodecamp.rocks/query/lolcats%20funny?page=10" target="_blank" rel="noopener noreferrer nofollow">https://image-search-abstraction-layer.freecodecamp.rocks/query/lolcats%20funny?page=10</a>
```

**Comment by ieahleen** [comment]
come to the chat somewhere for this, this issue doesn't seam the best place
