### ISSUE TITLE
Bonfire: Sum All Numbers in a Range - Description not clear

### ISSUE THREAD

**Issue by Rahul1992** [FreeCodeCamp/FreeCodeCamp#4669]
The description mentioned for this problem clearly says the returned value should be 
1. sum of the numbers in the array and
2. sum of all the integers between them.

But the evaluation is based only on the point 2.

**Comment by ltegman** [comment]
I'm not seeing any issue with the description of this challenge. It is asking for the sum of both those things, not just the second. For example, `[1,4]` expects an output of 10, which is the sum of the numbers in the array (`1 + 4 = 5`) plus the sum of all the integers in between ('2 + 3 = 5`). It seems to me that this fits what the description is asking for.

Closing this as not an issue with the lesson. Please let me know if you have further concerns.

Thanks and happy coding!

**Comment by Rahul1992** [comment]
now i get it. Thanks for the explanation.

**Comment by Rahul1992** [comment]
the question is a little confusing "Return the sum of those two numbers and all numbers between them."
So i thought the result should be two outputs one for the "sum of those two" and another "all the numbers between them". I would still emphasis on slight change in the description.
