### ISSUE TITLE
Issue in HTML challenge

### ISSUE THREAD

**Issue by vanya31** [freeCodeCamp/freeCodeCamp#46717]
### Describe the Issue

In the fourth challenge of 'Learn HTML Forms by Building a Registration Form', the challenge gives an error of 'Link tag should be self closing'. 
**The solution according to the challenge:**
<link rel="stylesheet href="styles.css"/>
**Whereas the solution should be:**
<link rel="stylesheet href="styles.css">

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-4

### Your code

```
<head>
   <title>Registration Form</title>
    <link rel="stylesheet" href="styles.css>
  </head>
  <body>
  </body>

```

### Expected behavior

The code should have passed since Link tag is a self closing tag and doesn't need a '/'.

### Screenshots

![Screenshot (12)](https://user-images.githubusercontent.com/72427243/176608947-0126b189-f964-49f6-ae94-3ad5d25748a6.png)

### System

- Device: Laptop MI Notebook
- OS: Windows 11
- Browser: Brave
- Version: 1.40.107

**Comment by Sboonny** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #44616, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
