### ISSUE TITLE
Tests are not passing when using new JS syntax (const [LOGIN, LOGOUT] = ['LOGIN', 'LOGOUT'])

### ISSUE THREAD

**Issue by GrzywN** [freeCodeCamp/freeCodeCamp#46728]
### Describe the Issue

Test doesn't pass even, if variables are declared using `const`. It's totally correct and it's working, but tests doesn't pass. Variables are `const`, but are made using the new syntax which I think tests doesn't support.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/use-const-for-action-types

### Your code

```
const [LOGIN, LOGOUT] = ['LOGIN', 'LOGOUT']

const defaultState = {
  authenticated: false
};

const authReducer = (state = defaultState, action) => {


  switch (action.type) {
    case LOGIN:
      return {
        authenticated: true
      }
    case LOGOUT:
      return {
        authenticated: false
      }

    default:
      return state;

  }

};

const store = Redux.createStore(authReducer);

const loginUser = () => {
  return {
    type: LOGIN
  }
};

const logoutUser = () => {
  return {
    type: LOGOUT
  }
};
```

### Expected behavior

Tests should pass.

### Screenshots

![Screenshot 2022-06-30 at 17-22-58 freeCodeCamp org](https://user-images.githubusercontent.com/59345997/176715557-70b3c40f-bb67-46a2-88fb-9a6333df6b5c.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ieahleen** [comment]
The test is this one
```
const noWhiteSpace = __helpers.removeWhiteSpace(code);
assert(
  (/constLOGIN=(['"`])LOGIN\1/.test(noWhiteSpace) &&
    /constLOGOUT=(['"`])LOGOUT\1/.test(noWhiteSpace)) ||
      /const(LOGIN|LOGOUT)=(['"`])\1\2,(?!\1)(LOGIN|LOGOUT)=(['"`])\3\4/.test(noWhiteSpace)
);
```
it would need to be changed to support a destructuring assignment

this is the file
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/03-front-end-development-libraries/redux/use-const-for-action-types.md

https://github.com/freeCodeCamp/freeCodeCamp/blob/e2d6b5eb5f5e2b78cf018a374375d6919425cf52/curriculum/challenges/english/03-front-end-development-libraries/redux/use-const-for-action-types.md?plain=1#L86-L95

---

An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by MSK1582** [comment]
If no one's working on this, I can fix this quickly.
