### ISSUE TITLE
Menu button for all categories  available on footer of website like about, alumni network, sponsership.

### ISSUE THREAD

**Issue by spiderxp3** [freeCodeCamp/freeCodeCamp#46727]
### Describe the Issue

On clicking any link, pages redirected not have a go-back option or Menu button. 
Bug is there on clicking support option.

### Affected Page

https://www.freecodecamp.org/news/about/

### Steps to Reproduce

1. Search for footer section in client mode. 
2. Get articles section and create menu button with link to main website.

### Expected behavior

Improvement and more reliability between client and platform.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ieahleen** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #46697, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
