### ISSUE TITLE
refactor challenge types for reliable client logic

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#46729]
There are two issues here.  Firstly [...] that the client is performing ad-hoc logic. Secondly, that there isn't a good way to determine which challenges are JS projects.

With those two issues in mind, I think the way to go is as follows.  We have a challenge type `bonfire` that is functionally equivalent to the challenge type `js`.  I'd rename that `jsProject`, convert all the *other* challenges that have challenge type 5 (currently `bonfire`) to challenge type 1 (`js`) and then we can expand the following logic (from https://github.com/freeCodeCamp/freeCodeCamp/pull/46087)

https://github.com/freeCodeCamp/freeCodeCamp/blob/469bac51a6683c22195aae10b93b17c2ec086aa3/utils/challenge-types.js#L44-L54

to include `jsProject`.  Then `isProject` can be used in the client and should be reliable.  With this in place we'd no-longer need to add `isStepBased`.

[...]

_Originally posted by @ojeytonwilliams in https://github.com/freeCodeCamp/freeCodeCamp/issues/46339#issuecomment-1152206940_

**Comment by ojeytonwilliams** [comment]
Sure, I think this can be broken down into a few PRs

JS:
- convert `bonfire` to `jsProject`
- convert all JS challenges to challengeType `js`
- simplify the client logic

Multifile
- convert from challengeType 0 to a new type
- simplify the client logic

Does that about sum it up?

**Comment by ieahleen** [comment]
> * convert from challengeType 0 to a new type

the projects use 
https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/client/utils/challenge-types.js#L16

And I went to investigate what the other types are used for, maybe there is one already for the step based projects.
Challenges in es6 are type 6
curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/
https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/client/utils/challenge-types.js#L8

These could actually be type 1 too. It doesn't seem all of them tho.

Then challenges in front end libraries (react, jquery, redux), and data visualization are type 6 - this could make sense.

---

https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/client/utils/challenge-types.js#L9

challenge type 7 appears only in the folder `00-certifications` to identify the project blocks

and is used in the logic for the blocks and superblocks

also, there is a todo for it:
https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/client/utils/gatsby/challenge-page-creator.js#L71-L72

https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/client/plugins/fcc-source-challenges/create-challenge-nodes.js#L12
https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/client/plugins/fcc-source-challenges/create-challenge-nodes.js#L20-L25
https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/client/plugins/fcc-source-challenges/create-challenge-nodes.js#L36-L39
https://github.com/freeCodeCamp/freeCodeCamp/blob/1a8899bfb8ef543ebd6be7895f2e8ff1189409f3/api-server/src/common/models/user.js#L769-L779

**Comment by moT01** [comment]
Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/45522

**Comment by ojeytonwilliams** [comment]
Still needing updates:

Multifile

- convert from challengeType 0 to a new type
- simplify the client logic

**Comment by nayabatir1** [comment]
Hey, I want to work on this issue but I'm not understanding the gist of this issue.

**Comment by a2937** [comment]
I hope the equivalent of an enum is going to be used for the challenge types in place of the actual numbers.

**Comment by Sembauke** [comment]
<img width="464" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/46919888/470c77de-8b2c-44f3-a679-5926fe629bfb">

**Comment by moT01** [comment]
Closing as stale. This is something we will continue to improve. Thanks and happy coding 🎉
