### ISSUE TITLE
test failing on "URL Shortener Microservice" challage when using NextJs

### ISSUE THREAD

**Issue by robdll** [freeCodeCamp/freeCodeCamp#46730]
### Describe the Issue

When trying to complete thee challenge it fails 3 of the 4 tests although the developed project works properly

Failed:You can POST a URL to /api/shorturl and get a JSON response with original_url and short_url properties. Here’s an example: { original_url : 'https://freeCodeCamp.org', short_url : 1}  
Failed:When you visit /api/shorturl/<short_url>, you will be redirected to the original URL.
  
Failed:If you pass an invalid URL that doesn’t follow the valid http://www.example.com format, the JSON response will contain { error: 'invalid url' }

project link(s)

[solution](https://short-url-six-sigma.vercel.app/)
[githubLink](https://github.com/robdll/short-url)

browser information:

User Agent is: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

Challenge: [URL Shortener Microservice](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice)

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice

### Your code

[solution](https://short-url-six-sigma.vercel.app/)
[githubLink](https://github.com/robdll/short-url)

### Expected behavior

test should pass

### Screenshots

![image](https://user-images.githubusercontent.com/4103610/176870391-e8dc0152-8dc8-4b87-b62d-9e2d19ea9add.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

project deployed using NextJs

**Comment by moT01** [comment]
The link to your repo doesn't work @robdll - not sure if it's private or you deleted it or what, but it doesn't seem to be there.

I tried to submit your project, I see a lot of CORS errors from the tests requests:
<img width="591" alt="Screen Shot 2022-07-01 at 9 09 14 AM" src="https://user-images.githubusercontent.com/20648924/176911186-aae0761f-f64b-4965-8071-0af5ff653905.png">
<img width="756" alt="Screen Shot 2022-07-01 at 9 10 12 AM" src="https://user-images.githubusercontent.com/20648924/176911197-c10640ea-3024-4365-aef4-ea1fcf2ab8d5.png">

I did a quick search and found [this post.](https://stackoverflow.com/questions/65058598/nextjs-cors-issue) Your solution may be in there. I don't think there's anything we can do on our end to resolve this.

**Comment by nhcarrigan** [comment]
I agree we should clarify the test descriptions to indicate the shape of the requests we are making.

**Comment by robdll** [comment]
@moT01 thanks for checking my issue.

I checked both the [repo link](https://github.com/robdll/short-url) and the [website link](https://short-url-six-sigma.vercel.app/) provided and are working, maybe there was a vercel/github issue when you tried to access them?

I've also tried to make the request

- via curl:
`curl -d "original_url=https://roberto.dilillo.dev" -X POST https://short-url-six-sigma.vercel.app/api/shorturl `

response was 
`{"original_url":"https://roberto.dilillo.dev","short_url":29}%  `

- via postman (201), here's a screenshot:
![postman](https://user-images.githubusercontent.com/4103610/177049491-fc9de48c-5776-444b-8271-a52bb8d3235a.png)

**Comment by robdll** [comment]
can confirm this is a cors issue, closing

**Comment by moT01** [comment]
Did you see the addition I added to my comment @robdll?

> One thing I noticed when looking at this is that your app sends a post request with a body like this: `original_url=${url}`, the tests use `url=${url}` - your app gave me a bad response when I tried to use what the tests are using

I would try to change your app to handle a body that looks like what the tests are using - I think that's likely the problem.

**Comment by robdll** [comment]
@moT01 yes sorry,
I can confirm that was one of the issue, and i also solved the NExt js issue thanksto [this post](https://stackoverflow.com/a/72663223/2324133)

The preflight request was failing due to an agressive HTTP method filter.

If anyone has the same issue, make sure that you specify
```
  // Preflight Check:
  if (req.method == "OPTIONS") {
    res.setHeader("Allow", "POST");
    return res.status(202).json({});
  }

  // Allow only POST Methods 
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: `Method ${req.method} Not Allowed` });
  }
```
