### ISSUE TITLE
Registration Form 30 - Too Strict of Test

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46735]
### Describe the Issue

The test for this challenge is a bit too strict with whitespace.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-30

### Your code

```html/css
        <label>
          How did you hear about us?
          <select>
            <option></option>
            <option></option>
            <option></option>
            <option></option>
            <option></option>
          </select>
        </label>
```

### Expected behavior

This code should pass

### System

All

**Comment by nhcarrigan** [comment]
```js
assert.match(document.querySelector('fieldset:nth-child(3) > label:nth-child(3)')?.innerHTML?.replace(/[\t\n]+/g, ''), /^How did you hear about us\?/);
```

Should be able to tighten up the replace regex. Or use `trim`.
