### ISSUE TITLE
Step 49 onwards City Skyline Project

### ISSUE THREAD

**Issue by s-hackman** [freeCodeCamp/freeCodeCamp#46752]
### Describe the Issue

Step 49 suggests adding height of 100% to .bb2b

![image](https://user-images.githubusercontent.com/106757825/177041019-afe7a1d5-0f94-46fa-8c18-1b5a641a877e.png)

When I completed the project on VS code, the .bb2b building was still overhanging but this problem did not happen on the preview of the freeCodeCamp website. 

![image](https://user-images.githubusercontent.com/106757825/177041267-871c0cd9-d564-4d95-8aa2-2ec755c3e146.png)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-49

### Your code

Before
```
.bb2b {
  width: 100%;
  height: 100%;
  background: repeating-linear-gradient(
      var(--building-color2),
      var(--building-color2) 6%,
      var(--window-color2) 6%,
      var(--window-color2) 9%
    );
}
```
After editing .bb2b height the overhang of building is gone
```
.bb2b {
  width: 100%;
  height: 90%;
  background: repeating-linear-gradient(
      var(--building-color2),
      var(--building-color2) 6%,
      var(--window-color2) 6%,
      var(--window-color2) 9%
    );
}
```

### Expected behavior

I expected the preview from freeCodeCamp website to match my VS Code preview.
Giving .bb2b a height of 90% fixed this issue. 
![image](https://user-images.githubusercontent.com/106757825/177041688-83cf3741-1dcb-4c40-b681-e8856a5bbf43.png)

### System

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: Version 102.0.5005.115

**Comment by gikf** [comment]
Could you include more detailed steps how to reproduce the issue? I wasn't able to get it look like that.
