### ISSUE TITLE
Clarify instructions for Cafe Menu Step 14

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46769]
### Describe the Issue

Campers are creating the new rule set properly but are adding it below the existing rule sets instead of deleting them, which is necessary to pass this step. Even though the hint says "You should only have one selector in your style element." it doesn't seem that they understand what this means.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-14

### Your code

```
      h1 {
        text-align: center;
      }
      h2 {
        text-align: center;
      }
      p {
        text-align: center;
      }
      /* The three rule sets above must be deleted to pass the step */
      h1, h2, p {
        text-align: center;
      }
```

### Expected behavior

I don't think the instructions make it clear that the three existing rule sets should be deleted and replaced with one new rule set. Perhaps change the instructions to something like:

"Replace the three existing type selectors with one selector list that centers the text for the `h1`, `h2`, and `p` elements."

Or even:

"Delete the three existing type selectors and replace them with one selector list that centers the text for the `h1`, `h2`, and `p` elements."

### System

N/A

**Comment by jdwilkin4** [comment]
> "Delete the three existing type selectors and replace them with one selector list that centers the text for the h1, h2, and p elements."

I like this second option. I think adding this to the instructions will make it more clear.
