### ISSUE TITLE
(FEL): redux use const for action types doesn't accept a valid answer

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46776]
### Describe the Issue

As pointed out by @raditotev in the affected page, there is a valid solution, that isn't accepted by the tests. But if we keep adding to the regex, it will be too complicated, and it will get out of hand for new contributor to be able to help.

Radi comment: https://github.com/freeCodeCamp/freeCodeCamp/pull/46753#issuecomment-1174857836

@lulululu12345 has mentioned a regex solution in his comment, but I am hoping there is an alternative to regex

Luke comment: https://github.com/freeCodeCamp/freeCodeCamp/pull/46753#issuecomment-1175136663

Here is the markdown page
https://github.com/freeCodeCamp/freeCodeCamp/blob/04eaee51fc08b27576081519306819d467e62793/curriculum/challenges/english/03-front-end-development-libraries/redux/use-const-for-action-types.md

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/use-const-for-action-types

### Your code

```js
const {LOGIN, LOGOUT} = {LOGIN: 'LOGIN', LOGOUT: 'LOGOUT'}
```

### Expected behavior

This code is valid, so we should allow it to pass. But as mentioned before the regex is too complex, I wonder if we can do something that make the need for using regex unnecessary.

### Screenshots

![image](https://user-images.githubusercontent.com/88248797/177604459-8dcafd07-0db9-4cd4-98df-da455667b1f1.png)

**Comment by ieahleen** [comment]
uhm... try to reassign LOGIN and LOGOUT, if it gives error `TypeError: Assignment to constant variable.` you pass?
that would remove all those regex checks

**Comment by raditotev** [comment]
@ieahleen this doesn't work, [see here](https://github.com/freeCodeCamp/freeCodeCamp/pull/46753#pullrequestreview-1028861387):

>I have tried to cover for this test case with reassigning the variables and expecting an error but this didn't work as well:

>assert.throws(() => {LOGIN = 'some value'}, TypeError, 'Assignment to constant variable.')
For some reason the JS test runner allows constants to change.

**Comment by raditotev** [comment]
Thanks for opening this issue @Sboonny .

**Comment by ieahleen** [comment]
No, right, all the user code is converted to `var` under the hood, @nhcarrigan was having the same issue

**Comment by ieahleen** [comment]
I propose
> For testing limitations, you can use only plain assignment

**Comment by Sboonny** [comment]
Because I don't want to make the regex text more complex, and the opportunity of changing it from regex isn't possible currently. I vote with Ieahleen suggestion

**Comment by raditotev** [comment]
There are two conditions to be fulfilled for this test:
1. User should use variable instead of string
2. Variable should be constant
I think the more declarative approach would be the following:
```js
assert(LOGIN === 'LOGIN' && LOGOUT === 'LOGOUT') // fulfils No. 1
assert(noWhiteSpace.includes('const')) // fulfils No.2
assert.isNotOk(noWhiteSpace.includes('let')) // No.2
assert.isNotOk(noWhiteSpace.includes('var')) // No.2
```
I think the above will work without being too implicit regarding the solution.
I would say the last  two `assert.isNotOk` could even be omitted because there is always a slim chance someone might write 
 unconsciously  some comment that might contain `let` or `var` as substrings.

**Comment by ieahleen** [comment]
there is a function to strip comments that can be used, so that the last two can be included

**Comment by raditotev** [comment]
@ieahleen I was waiting to hear any comments regarding the proposed changes but I assume whoever saw this is ok. We can open this for contributors. The change should be pretty straight forward.
