### ISSUE TITLE
The test for telephoneCheck("555)555-5555") should return false, seems broken.

### ISSUE THREAD

**Issue by D161TAL** [FreeCodeCamp/FreeCodeCamp#4677]
Challenge [Bonfire: Validate US Telephone Numbers]
```
function telephoneCheck(str) {
    if (str == "555)555-5555") {
    return false;
    }
}

telephoneCheck("555)555-5555");
```

This actually returns false as the test says it should, but the test does not pass.

The rest of the tests pass in my actual telephoneCheck() function.

**Comment by ltegman** [comment]
Thanks for the report. It looks like that test was actually testing against the string `555)-555-5555` rather than `555)555-5555` like the message said. I have submitted a PR to correct this.

**Comment by D161TAL** [comment]
ok good so i'm not insane.

just mental.

+1:
