### ISSUE TITLE
In cat app photo project, meta element is mislabeled

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46772]
### Describe the Issue

as ieahleen mentioned in Crowdin, if `meta` written this way, then it is an element. While if it's written this way `<meta>`, it's a tag.

The description and the hint should be changed accordingly

```markdown
One more thing. You should allow people to use their native language. Tell the browser to encode multiple languages by adding a `meta` tag as a child of the `head` element. Set its `charset` attribute to `UTF-8`.

...

You should give the `meta` tag a `charset` of `UTF-8`.
```

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/f27c2e80898a59cae85fcd8d81d0a0d1251a8982/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/62bb4009e3458a128ff57d5d.md

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by Mosesjespar** [comment]
> i m new to open source contribution, it seems to be nice for me. i think i can tackle this..

Me too man, but I have no idea how on how to actually contribute.Any help or guide?

**Comment by Sboonny** [comment]
@Mosesjespar [our guidelines for contributing](https://contribute.freecodecamp.org/#/)

**Comment by Sboonny** [comment]
This issue is simple, I would fork the repo and use Gitpod `.gitpod.yml` should automatically set everything up, you will still need to create your own branch. But you can try locally if you want some experience with node, although I would not do that
