### ISSUE TITLE
CSS Flexbox Photo Gallery Step 1: language attribute causes error

### ISSUE THREAD

**Issue by LauraLangdon** [freeCodeCamp/freeCodeCamp#46771]
**Describe the bug**
The `html` opening tag is rejected if it contains a language attribute.

**To Reproduce**
1. Go to New Responsive Web Design -> Learn CSS Flexbox by Building a Photo Gallery
2. Click on Step 1
3. Fulfill the listed requirements and include a language attribute in the `html` opening tag
4. Code is rejected with the hint "Your `html` element should have an opening tag"

**Expected behavior**
Providing a language attribute should not cause code to be rejected.

**Screenshots**

Code is rejected if a language attribute is provided:

![image](https://user-images.githubusercontent.com/48335772/177460813-1b092fd3-6465-49de-8595-ad9adac13fb2.png)

Code is accepted if the language attribute is removed:

![image](https://user-images.githubusercontent.com/48335772/177460936-bd9f32dd-8b05-4fa3-a3f7-96e29ab17505.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser: Chrome
 - Version: 103.0.5060.53

**Comment by bbsmooth** [comment]
It looks like this will be fixed in [PR #46639](https://github.com/freeCodeCamp/freeCodeCamp/pull/46639/files).
