### ISSUE TITLE
Strict whitespace test

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#46783]
### Describe the Issue

Overly strict whitespace tests 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-15

### Your code

```
      <fieldset>
        <label>Enter Your First Name: <input> </label>
        <label>Enter Your Last Name: <input> </label>
        <label>Enter Your Email: <input> </label>
        <label>Create a New Password: <input> </label>
      </fieldset>
```

### Expected behavior

The space between the input element and closing label tag shouldn't matter, right?

### System

All

**Comment by Sboonny** [comment]
Here is the markdown file: https://github.com/freeCodeCamp/freeCodeCamp/blob/eca650dc699aaaa8846b64e9d1d5d642562e97eb/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f805f813eaf2049bc2ceea.md


we can use regex in these tests

> You should add the first `input` after the `label` text `Enter Your First Name:`, and include a space after the colon.
>
> ```js
> assert.equal(document.querySelectorAll('label')?.[0]?.innerHTML, 'Enter Your First Name: <input>');
> ```
>
> You should add the second `input` after the `label` text `Enter Your Last Name:`, and include a space after the colon.
> 
> ```js
> assert.equal(document.querySelectorAll('label')?.[1]?.innerHTML, 'Enter Your Last Name: <input>');
> ```
>
> You should add the third `input` after the `label` text `Enter Your Email:`, and include a space after the colon.
>
> ```js
> assert.equal(document.querySelectorAll('label')?.[2]?.innerHTML, 'Enter Your Email: <input>');
> ```
>
> You should add the fourth `input` after the `label` text `Create a New Password:`, and include a space after the colon.
> 
> ```js
> assert.equal(document.querySelectorAll('label')?.[3]?.innerHTML, 'Create a New Password: <input>');
> ```

Something like `/Enter Your First Name: <input\s*>\s*/`, but we have to use regex which is headache.

**Comment by Sboonny** [comment]
Sure, I don't mind, because they aren't required to type text in this step, but the description will be altered

**Comment by jeremylt** [comment]
I'm not sure I see why the description would be changed. I was thinking of this:
```
document.querySelectorAll('label')?.[0]?.innerHTML.trim()
```
