### ISSUE TITLE
Typo in cramers rule challenge from rosetta code section

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46809]
### Describe the Issue

there is a typo in cramers-rule challenge, `determinates` is used instead of `determinants` which is wrong

these sentences 

> <a href="https://rosettacode.org/wiki/Cramer%27s_rule" target="_blank" rel="noopener noreferrer nofollow">Cramer's rule</a> is a formula for solving a system of linear equations by using the determinates of matrixes formed from subsets of the coefficients and right hand side values.
>
>The determinate of a matrix with 2 rows and two columns is given by:

should be changed to 

> <a href="https://rosettacode.org/wiki/Cramer%27s_rule" target="_blank" rel="noopener noreferrer nofollow">Cramer's rule</a> is a formula for solving a system of linear equations by using the determinants of matrixes formed from subsets of the coefficients and right hand side values.
>
>The determinant of a matrix with 2 rows and two columns is given by:

Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/cramers-rule.md

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/cramers-rule

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by ayaanraj** [comment]
@Sboonny I wanted to work on this issue

**Comment by Sboonny** [comment]
@ayaanraj feel free to open pull request after you have read [our guidelines for contributing](https://contribute.freecodecamp.org/#/)
