### ISSUE TITLE
Possibly wrong test case

### ISSUE THREAD

**Issue by ricardobortoti** [FreeCodeCamp/FreeCodeCamp#4681]
Challenge [Bonfire: No repeats please](http://www.freecodecamp.com/challenges/bonfire-no-repeats-please) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

in this exercise, there is one test case that i think is not right : 

"permAlone(aabb) should return 8." How is possible this permutation result in 8? since the total permutations, including char repetition results in 6?

**Comment by SaintPeter** [comment]
For the purposes of this challenge we treat identical letters as being "different" for the purposes of permuting, but identical for the purposes of determining sameness.

Basically, if you use a naive permutation algorithm you'll get "repeated" patters which are counted.

A reasonably good explanation can be found here:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2854

This challenge is only a problem for people who have been properly educated in the actual mathematical definition of permutation.  For the ignorant, it's not a big deal.  Despite discussing it for . . . months . . . we have yet to come up with better challenge text.

**Comment by ricardobortoti** [comment]
Understood, i was thinking more on the mathematical approach of non repeating permutation.

thanks.
