### ISSUE TITLE
Bugs in Colored Markers Step 2

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46814]
### Describe the Issue

I am able to pass this step by completely removing all HTML from the editor. I am also able to pass this step if I add the correct `head` and `body` elements but delete everything else. Finally, I am able to pass this test if I add the `body` element before the `head` element.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-2

### Your code

Described above.

### Expected behavior

I'm not sure how many of these bugs absolutely need fixing but I would think the empty editor bug should be fixed for sure. And since the instructions ask that the `body` element be added after the `head` element we should probably fix that one as well.

### System

Confirmed with newest versions of both Chrome and Firefox.

**Comment by ieahleen** [comment]
The querySelector tests can be tricked by the fact that some things are automatically added by the browser.

But all these, how can these pass if the code is empty?

https://github.com/freeCodeCamp/freeCodeCamp/blob/428de4154dbb41576bacc34ed31d7639a9a0d9d7/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/61695ab9f6ffe951c16d03dd.md?plain=1#L17

https://github.com/freeCodeCamp/freeCodeCamp/blob/428de4154dbb41576bacc34ed31d7639a9a0d9d7/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/61695ab9f6ffe951c16d03dd.md?plain=1#L23

https://github.com/freeCodeCamp/freeCodeCamp/blob/428de4154dbb41576bacc34ed31d7639a9a0d9d7/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/61695ab9f6ffe951c16d03dd.md?plain=1#L29

https://github.com/freeCodeCamp/freeCodeCamp/blob/428de4154dbb41576bacc34ed31d7639a9a0d9d7/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/61695ab9f6ffe951c16d03dd.md?plain=1#L35

this the file
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/61695ab9f6ffe951c16d03dd.md

**Comment by bbsmooth** [comment]
I stuck a `console.log(code)` in the first test and when there is no content in the editor `code` equals `<head></head><body></body>`. I don't know enough about how this works to know why that's the case, but that explains why it is passing when there is no content in the editor.

**Comment by RandellDawson** [comment]
@ojeytonwilliams ???

**Comment by bbsmooth** [comment]
Opening again. Someone in the forums just discovered that the following will pass this step:

```
<head>
  <body></body>
</head>
```

**Comment by bbsmooth** [comment]
It also passes 

```
<body></body>
<head></head>
```

```
<head><body></head></body>
```

```
<head></body><body></head>
```

And probably other variations as well. This is with FF 100 on linux. I think browsers are just too good at fixing bad HTML :smile:
