### ISSUE TITLE
Survey Form Certification Project: Clarify tests for non-empty labels

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46834]
### Describe the Issue

There are three tests that test for non-empty labels:

"Your #name-label should not be empty."
"Your #email-label should not be empty."
"Your #number-label should not be empty."

I think the word "empty" is slightly ambiguous here. These tests appear to be looking for actual text inside the label. But if the user nests an `input` inside the label without text then the `label` isn't exactly empty:

```
<label id="name-label"><input placeholder="Name" id="name" type="text" required /></label>
```

The above will fail because there is no actual text in the `label` but I can see how the user would not think the `label` is empty.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### Your code

N/A

### Expected behavior

Adjust the test descriptions so they clarify that text needs to be inside the `label`. Perhaps something like:

"Your #name-label should contain text that describes the input".

### System

N/A

**Comment by Sboonny** [comment]
Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.
