### ISSUE TITLE
Specify the number of project from full Projects is Complete

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46843]
### Is your feature request related to a problem? Please describe.

"When I submit the project it stops at 60%" is common to see in the forum or discord chat, those percentages seem to confuse many people 

### Describe the solution you'd like

Saying 'X of Y Projects Complete'

### Describe alternatives you've considered

I have no idea

### Additional context

here is the completion model https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/components/completion-modal.tsx

**Comment by ieahleen** [comment]
That would be a great UX improvement, considering that we don't have the progress modal in the projects anymore.

See here for many confused people:
https://forum.freecodecamp.org/t/survey-form-stuck-on-20-completion-5-parts/523950

**Comment by ieahleen** [comment]
@ahmadabdolsaheb as you are the designer, maybe you want to say yours?

**Comment by ahmadabdolsaheb** [comment]
Thanks for notifying me. "Saying 'X of Y Projects Complete" would make sense.

**Comment by Jagrutiti** [comment]
Hey everyone,

I looked up this issue and went through the code.

From `getCompletedPercent()` I learn that the message could be a combination of two variables used in the same function. Something like this:

` Completed ${completedChallengesInBlock.length} of ${currentBlockIds.length} challenges`

`getCompletedPercent()` returns a number so I do not want to change that.

My approach would be to write a new function that returns the exact string required and replace the `completedPercent ` value on line number 251 with new the variable that would return a  string.

Should I go ahead with this approach or do you have something else in mind?

**Comment by ieahleen** [comment]
It could work, just keep in mind that the string needs to be translatable, so you can't hardcode it there

**Comment by Jagrutiti** [comment]
Where do  I put the text that needs to be hard coded?

**Comment by ieahleen** [comment]
You can't hardcode it, you need to add it to `translations.json` and use the translation function to retrieve it, like it's done for any text, for example
https://github.com/freeCodeCamp/freeCodeCamp/blob/530737f9cc4a7827366f1d43db563a6c93cb4a92/client/src/templates/Challenges/components/completion-modal.tsx#L265

which are here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/530737f9cc4a7827366f1d43db563a6c93cb4a92/client/i18n/locales/english/translations.json#L68-L69

For an example of how to interpolate a value in a translatable string, here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/530737f9cc4a7827366f1d43db563a6c93cb4a92/client/i18n/locales/english/translations.json#L114
https://github.com/freeCodeCamp/freeCodeCamp/blob/530737f9cc4a7827366f1d43db563a6c93cb4a92/client/src/client-only-routes/show-settings.tsx#L165

**Comment by akhilpamwani** [comment]
Hi ! I am interested to help but before please tell me the issue
in detail

**Comment by ahmadabdolsaheb** [comment]
@akhilpamwani, there is an open pr for this issue. Feel free to look into other issues that might interest you.

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb Do we want to remove the existing loading bar in favour of `X out of Y`? Or, do we want to replace the text? Or, do we want both?

a)
<img width="328" alt="image" src="https://user-images.githubusercontent.com/51722130/194046732-1416277a-b249-48fc-a0fc-b556cad15769.png">

b) 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/51722130/194047179-5dc71e6f-53e6-4dff-8f47-c3725b0b3291.png">

c) 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/51722130/194047262-8f699152-0d99-469c-9439-c019006dac6b.png">
