### ISSUE TITLE
Inncorrect test case: http://www.freecodecamp.com/challenges/bonfire-drop-it

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#4685]
Your last test case will never pass
<img width="1255" alt="screen shot 2015-11-24 at 12 00 38 am" src="https://cloud.githubusercontent.com/assets/2502947/11358307/aee48368-923e-11e5-9d51-85cc0e11c0ad.png">
.  You should change it :)

**Comment by ltegman** [comment]
Passes no problem with my solution. Filter is not a valid way to solve this problem.

Thanks and happy coding!

**Comment by benschac** [comment]
That makes no sense.  Why wouldn't the second 2 be in the array too? 2 will never be > the number 2?

**Comment by ltegman** [comment]
Read the question carefully. It asks you to remove elements from the array until the predicate returns true and then stop. So you will end the loop before you get to that element.

**Comment by benschac** [comment]
I was just thinking about shifting the array after I posted that last
comment.  You're totally right.  Thanks.

On Tue, Nov 24, 2015 at 12:12 AM, Logan Tegman <notifications@github.com>
wrote:

> Read the question carefully. It asks you to remove elements from the array
> until the predicate returns true and then stop. So you will end the loop
> before you get to that element.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4685#issuecomment-159151289>
> .
>



-- 
*Benjamin Schachter *• Project Manager
* <http://www.dramafever.com/>*    |   bschachter@dramafever.com

**Comment by benschac** [comment]
Thanks again for the help.  I took some time to think about the problem and got the correct solution.  That was tricky! 
![screen shot 2015-11-28 at 8 08 52 pm](https://cloud.githubusercontent.com/assets/2502947/11454827/00a9153a-960c-11e5-986f-bddb0a75c1f3.png)
