### ISSUE TITLE
Lack of practice questions in courses

### ISSUE THREAD

**Issue by 11HyperlinkBlocked11** [freeCodeCamp/freeCodeCamp#46867]
### Describe the Issue

Curriculum lack practice questions after each course (little courses before cert projects).
It is easy to forget info after going through the course, so it would be great if there will be tests which test you on _everything_ you can learn from each course.
E.g. questions like

- What element is used for creating links?
- What semantic element is used for grouping related content?
- How to make some input fields to be must-have to be able to submit the form?
- What is the purpose of elements for content areas in HTML5?
- How is paragraph element displayed by the browser by default?
- How inline elements are displayed, if they are placed on different lines in the code?
- How to add an unordered list?
- How to emphasize the text?
- What is the difference between article and section elements? What is the `button` element default behaviour?
- How to create buttons to choose only one from multiple options?
- How to associate input element with it’s text input?
- How to target all the elements nested in elements with specific class in styling?
- What should we do if selected custom font is not available, how to prevent it?
- And so on

Even better if there would be variations of the one question e.g..:
- How to associate input element with it’s text input?

Variations:
- How to make so if you click on text related to the `checkbox`, it also checks this `checkbox`?
- How to make an `input`'s element text clickable?

Majority of questions should ask about little concepts, things etc , without naming them (so you won’t be able to guess the answer from the question words). And some questions should test you on group of concepts (like “what are all the attributes of img element?”) after answering the “little questions”

Examples of "little question": how to align a text to one side?; what is the attribute for setting the type of an `input` element?
Examples of "big question": how to make several elements to be inline and how to prevent them from separating too far away from each other etc.?; what are all attributes of an `input` element?

It is easier and much more effective than just simply going through curriculum again to repeat.
Tests on _**everything**_ like this are extremely helpful at revealing gaps in the knowledge and repetition-memorization.

### Affected Page

https://www.freecodecamp.org/learn/

### Your code

N/A

### Expected behavior

N/A

### System

N/A

**Comment by ieahleen** [comment]
You don't have to memorize everything, the quiz would give that impression, I am not keen on the idea
