### ISSUE TITLE
Issue in Learn CSS Animation by Building a Ferris Wheel Step 1

### ISSUE THREAD

**Issue by junilm** [freeCodeCamp/freeCodeCamp#46868]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Correct answer is shown as incorrect.

**To Reproduce**
1. Go to (https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-animation-by-building-a-ferris-wheel/step-1)
2. Answer is 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Ferris Wheel</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
    <body></body>
</html>
```
3. Click 'Check Your Code' Button
Test
Sorry, your code does not pass. You're getting there.

Hint
You should have one self-closing link element.

**Expected behavior**
The code should have passed.

**Screenshots**
![image](https://user-images.githubusercontent.com/13235990/178447672-8b8059c2-d74d-409d-8b57-a42d5349ca34.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 103.0.1264.44

**Comment by ieahleen** [comment]
I can't reproduce the issue, the code you posted is passing

**Comment by Sembauke** [comment]
@junilm Please make sure that you disable any extensions that might interfere with completing the challenge.

**Comment by AlvaroH1276** [comment]
@Sboonny It also worked for me and I did the same stuff.

**Comment by Njong392** [comment]
Works for me in Chromium. I have noticed a few people post about failing tests, only to have the tests pass for me. What could be the reason?

**Comment by Sboonny** [comment]
@Njong392 Some extension inject `meta` elements with `color-theme` as dark mode extensions.

This is example of how extension manipulated Dom, we don't know what extensions people run, and building sandbox where they can run every extensions and pass the test is almost impossible work. So we recommend disabling them.

**Comment by jdwilkin4** [comment]
Hi @junilm ! 
I am going to go ahead and close this issue since multiple people have tested it and it works on their end. 
As mentioned, try disabling browser extensions since they have been know to interfere with the tests. 
Or you can try this challenge in another browser. 

Hope that helps! 👍

**Comment by junilm** [comment]
Did from another browser and it worked, thank you all for your help and support.
