### ISSUE TITLE
CatPhotoApp Step 6 is still not clear

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46863]
### Describe the Issue

For such a seemingly easy step this one is still a very popular topic in the forums. I think the fact that so many people are still struggling with it is telling us that the instructions are not clear enough. I also think the addition of the example code is confusing too many people into thinking they need to use it in the solution. I know that we now have a test that checks for this and the hint tells them not to use the list elements, but I think it's better to try to prevent this in the first place instead of trying to correct them after the fact.

If we want to continue using the list as an example then I think we should spell it out very clearly that it is just an example and should not be used in the solution for the step. The previous steps have all had HTML/text in the instructions that the user was expected to use in their solution, so I can definitely see why they would think the same for the example list. 

My suggested changes for the sentence before the list example:

"Indenting nested elements two more spaces than their parent element improves readability. Below is an example of what this indenting looks like using HTML list elements."

And then I think the final sentence should be much more detailed about what the user needs to do.

"Without making any other changes to the current HTML, use the space bar on your keyboard to add two more spaces in front of the `h2`, comment, and `p` elements so that these elements are indented and more readable."

Please feel free to make any adjustments to the above, I'm just getting the ball rolling here. But I think this step has the potential to make people feel silly, or even dumb once they finally get it right and we should avoid that by making it as clear as possible up front.

P.S. I just noticed that the instructions actually have the first element in the last sentence as `h1` instead of `h2`. I'll open a PR.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6

### Your code

N/A

### Expected behavior

Suggested changes described above.

### System

N/A

**Comment by jeremylt** [comment]
I like these changes. I agree we should

1) Add before the example:
> Indenting nested elements two more spaces than their parent element improves readability. Below is an example of what this indenting looks like using HTML list elements.

2) Replace last sentence:
> Without making any other changes to the current HTML, use the space bar on your keyboard to add two more spaces in front of the h2, comment, and p elements so that these elements are indented and more readable.

I would perhaps suggest that we break up the last sentence into smaller pieces. I've been trying to push our sentences to be a bit more straightforward, especially for our ESL learners:
> Use the space bar on your keyboard to add two more spaces in front of the h2, comment, and p elements so that these elements are indented and more readable. Do not make any other changes to the current HTML.

**Comment by texas2010** [comment]
i would say one more thing.  somehow this lesson did not remind to add space to comment too.  since it said h2 and p element need to have space. 🤔    do we need to remind user to add space to comment too?   i know hint message will tell them too.

**Comment by bbsmooth** [comment]
"Use the space bar on your keyboard to add two more spaces in front of the h2, comment, and p elements..."

Are you saying we need to make the comment stand out a little more? Perhaps something like:

"Use the space bar on your keyboard to add two more spaces in front of the `h2` element, the comment, and the `p` element..."

**Comment by jeremylt** [comment]
I think explicitly saying 'use the space bar' could make a huge difference. That seems to help on the forum.

**Comment by bbsmooth** [comment]
I understand the need for conciseness, but I don't think we should sacrifice brevity for clarity. And I think it's better to try and prevent mistakes than fix them after the fact. The mistakes here are that they start adding the list tags from the example and then it blows up and they give up in confusion and frustration. If we tell them explicitly in the instructions not to make any changes to the HTML then hopefully that will prevent them from adding the tags in the first place. That warning at the end is only 10 more words.

**Comment by jeremylt** [comment]
So the current suggestion is

1) Add before the example:

> Below is an example of what this indenting looks like using HTML list elements.

2) Replace the last sentence:

> Use the space bar on your keyboard to add two more spaces in front of the h2, comment, and p elements so that these elements are indented and more readable.

and we're split on adding at the very end:

> Do not make any other changes to the current HTML.

**Comment by ojeytonwilliams** [comment]
With instructions, I think brevity is very important. The more words we use the greater the likelihood people will skim/skip. It's always a tricky balance.

However, one thought just occurred to me. Wouldn't it be better to teach about indentation by only asking them to indent a single element? It should be clearer what we're asking if that's the case.

**Comment by jeremylt** [comment]
I'd vote that we try smaller changes, like explicitly saying 'use the spacebar' before making bigger changes like only indenting one child.

**Comment by jdwilkin4** [comment]
Maybe we could mention why the starter code is different from the last step.
It could be part of the lesson.

Something like

In the previous step, you nested the h2 element, comment, and p element within the main element. Indenting nested elements two more spaces than their parent element improves readability.

We have already indented the comment and p elements for you. Use the space bar on your keyboard to add two more spaces in front of the h2 element so it lines up with the comment and p elements. 

Thoughts? 🤷‍♀️

**Comment by jeremylt** [comment]
I still think we should try something small (make the last sentence more explicit) before we do something big (change the starter code and task). We can always make more changes in the future. Steps 6 and 12 seem to be the catching the most questions right now, so we'll get lots of forum posts to see what errors are being made.

**Comment by jdwilkin4** [comment]
For this small change, then I like the idea of changing the last sentence.

**Comment by bbsmooth** [comment]
I like @ojeytonwilliams and @jdwilkin4 idea of only having them indent only one element and having the comment and `p` already indented correctly and just having them indent the `h2` to match. If we did this we could do away with the HTML list example because we would already have an example in the starter code to refer to. This solves the problem of people inserting the list elements in the HTML and allows us to shorten up the instructions even more, which should make everyone happy!

**Comment by bbsmooth** [comment]
@lasjorg I think I've noticed on the forums as well that the word "indentation" is causing some problems. Defining it as you have here would probably be a good idea. I still think we ought to get rid of the code example completely in the instructions though. Even if we use pseudo-code I still think people will copy/paste it into the HTML.

**Comment by lasjorg** [comment]
> Even if we use pseudo-code I still think people will copy/paste it into the HTML.

They might, it is really an attempt to tie the words used in the text (parent/child) to the code example given.

**Comment by bbsmooth** [comment]
If we do end up keeping the example list HTML (I still want to get rid of it) then I would suggest we close up the spacing on the list items because someone in the forums thought that the space between the `<li>` and the text was the spaces the instructions were referring to. Also, it seems like a lot of the steps actually fail if users add extra unnecessary spaces like that so it seems strange that we would do it in our examples.

**Comment by lasjorg** [comment]
The formatting for the example does look off and the code fencing (backticks) around the word li inside the `li`s seems weird.

I still feel like we need a visual example of the formatting. Not sure what the best option for it is.

**Comment by bbsmooth** [comment]
What about @jdwilkin4's suggestion that we have the comment and `p` element already indented properly in the starter code and then they just have to indent the `h2` to make it match? Or it could be the `h2` and comment that are indented and they have to indent the `p`. That gives us an example without having to introduce any new code/pseudo-code. It also simplifies the lesson because they only need to indent on element. And they can see right away when the get it right because the three elements will line up.

**Comment by lasjorg** [comment]
I'm open to that as well.

- Explain what indentation is (literally) and why it is needed.
- Have two of the elements already indented in the seed code and explain that the elements are already indented.
- Ask them to indent the first (or last) element.

**Comment by ieahleen** [comment]
Let's consider even maybe dividing the step into two different one...
step 6: indent one single element
step 7: indent everything else

**Comment by wschuz** [comment]
Spacebar twice.
Make sure you press the spacebar twice on every line inside the main element

**Comment by jeremylt** [comment]
The flood of step 6 requests for help is still coming. It would be good to try *something* - we can always iterate more in the future. How about this:

> In the previous step, you nested the `h2` element, comment, and `p` elements within the main element. Indenting nested elements two more spaces than their parent element improves readability.

> The `h2` has been indented two spaces from the `main` element in the code below.

> Use the space bar on your keyboard to add two more spaces in front of the comment, and `p` elements so that these elements are indented and more readable. Do not make any other changes to the current HTML.

With the seed code:

```html
<html>
  <body>
    <h1>CatPhotoApp</h1>
    <main>
      <h2>Cat Photos</h2>
    <!-- TODO: Add link to cat photos -->
    <p>Click here to view more cat photos.</p>
    </main>
  </body>
</html>
```

**Comment by bbsmooth** [comment]
@jeremylt , I'm basically on board with you. I do think that the word "indentation" is causing trouble for ESL campers and we should define it a little better as @lasjorg recommended above. Perhaps this for the first paragraph:

>In the previous step, you nested the `h2` element, the comment, and the `p` element within the main element. Nested elements should be placed two spaces more to the right of their outer element to improve the readability of the HTML. Such a spacing is called an indentation.

Would anyone object if I opened a PR on this with @jeremylt's latest suggestion and my change here?

**Comment by jdwilkin4** [comment]
> Would anyone object if I opened a PR on this

No objections here 👍

**Comment by NavinduRanjuka** [comment]
In the previous step, you put the h1, h2, comment, and p elements inside the main element. This is called nesting. Nested elements should be placed two spaces further to the right of the element they are nested in. This spacing is called indentation and it is used to make HTML easier to read.

The h1 element, h2 element and the comment are indented two spaces more than the main element in the code below. Use the space bar on your keyboard to add two more spaces in front of the p element so that it is indented properly as well.

code: 
<html>
  <body>
    <main>
      <h1>CatPhotoApp</h1>
      <h2>Cat Photos</h2>




      
      
      <p>Click here to view more cat photos.</p>
    </main>
  </body>
</html>

**Comment by Sboonny** [comment]
@NavinduRanjuka, join [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help in step, this isn't the right place to seek help, our volunteers will help you out.
