### ISSUE TITLE
Bonfire: Return Largest Numbers in Arrays

### ISSUE THREAD

**Issue by renss78** [FreeCodeCamp/FreeCodeCamp#4686]
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays?solution=var%20array%20%3D%20%5B%5D%3B%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20temp%20%3D%20arr%5Bi%5D%3B%0A%20%20%20%20%20%20for(var%20y%20%3D%200%3B%20y%20%3C%20temp.length%20%2B1%3B%20y%2B%2B)%7B%0A%20%20%20%20%20%20%20%20if(temp%5B0%5D%20%3E%20temp%5B1%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20temp.splice(1%2C%201)%3B%0A%20%20%20%20%20%20%20%20%7D%20else%0A%20%20%20%20%20%20%20%20%20%20temp.splice(0%2C%201)%3B%20%0A%20%20%20%20%20%20%7D%20%0A%20%20%20%20array.push(temp%5B0%5D)%3B%0A%20%20%7D%20%0A%20%20return%20array%3B%0A%7D%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [];
function largestOfFour(arr) {
  for(var i = 0; i < arr.length; i++){
    temp = arr[i];
      for(var y = 0; y < temp.length +1; y++){
        if(temp[0] > temp[1]){
          temp.splice(1, 1);
        } else
          temp.splice(0, 1); 
      } 
    array.push(temp[0]);
  } 
  return array;
}
largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]);
```

Gets the correct output:  [9,35,97,1000000], But freeCodeCamp says it is not correct....

**Comment by renss78** [comment]
Ahh, when i put the var array = []; in the function, it is corrected!

**Comment by ltegman** [comment]
Glad to know you fixed it! This is due to the dangers of global variables. Make your variables are correctly scoped to the functions that use them :smile:

Thanks and happy coding!
