### ISSUE TITLE
Missing periods at the end of sentences in counting cards.

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46877]
### Describe the Issue

In the challenge, there are multiple hints that end without period, example:

> Cards Sequence 2, 3, 4, 5, 6 should return the string `5 Bet`

These should have period in the end of them

Here is the markdown file [curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/counting-cards.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/counting-cards.md)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/counting-cards

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by nhcarrigan** [comment]
I don't believe we've enforced full stops at the end of hint texts.

**Comment by Sboonny** [comment]
True but almost every new hint has period at the end of it. 

Anyway, this is the old JavaScript which will be deprecated, so I don't mind.
