### ISSUE TITLE
When/when are RWD media queries first taught?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46886]
### Describe the Issue

Edit: I'm talking about a standard media query used in responsive design.

Is [step 27](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-27) in "Learn Responsive Web Design by Building a Piano" really the first mention? And if so how does that step qualify as teaching media queries? Nothing is explained at all. If this challenge step is meant to be the first introduction to RWD media queries then it should be updated with an explanation and syntax example.

[Step 114](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-114) in "Learn CSS Variables by Building a City Skyline" at least explains it briefly and has a syntax example. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-27

### Your code

```
@media (max-width: 960px) {
  .card {
    flex-direction: column;
  }
}
```

### Expected behavior

Explain what a media query is, what it looks like, and how it works.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by sparkO7** [comment]
[Step 20](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-20) is the first mention. (with no syntax example)

[Step 66](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-66) is the 2nd mention. (with syntax example)

**Comment by lasjorg** [comment]
The first one is actually in the process of being removed completely ([PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/46639)). Because we can't ask people to do something that hasn't been taught.

The second isn't really the type of media query I'm talking about here. Sure it is an `@media` at-rule, but I'm talking about a standard media query used in responsive design.

```
@media (max-width: 960px) {
  .card {
    flex-direction: column;
  }
}
```

Anyway, thank you for looking at it, I appreciate it.

I will update the issue to clarify what type of media query I'm talking about.

**Comment by Tracerract** [comment]
As someone that ran into this issue firsthand, I wanted to share some context. 

The "Step 20" PR was merged, so Step 66 is now the first example of a media at-rule. I might be mistaken, but I think it might be the first of any at-rule used as well. 

Step 66 does not use the word query once, nor does it provide context about at-rules. It mentions `@media` as an at-rule, provides the minimum syntax for the rule to operate, and provides only necessary wording to use the syntax in this one way. media features aren't explained either, only that `prefers-reduced-motion` is one, and what it's possible values are.

This gets users through that step, and does show them that these exist, but Step 27 in 'Building a Piano' assumes a prior knowledge of media _queries_ and how to implement them. The directions for that step being:

> Now you need to make it responsive. Add a `@media` query with a max-width of 768px.

With the hint:
> Hint: You should add a new `@media` query.

This can be resolved by updating the description with a quick reference of media query syntax, but doesn't relate it to the context of the media rule they already completed, or progress the necessary understanding of at-rules.

This is further compounded in [Step 32](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-32) which necessitates the use a logical operator to make a more complex media query that checks multiple conditions.

I think the explanation in [Step 114](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-114) of 'Building a City Skyline' would be a fair example of how to improve the earlier projects.
