### ISSUE TITLE
Product Landing Page: allow flexbox to be set only inside a media query

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46887]
### Describe the Issue

The test should allow that flexbox is only set inside a media query.

As the test is written right now it doesn't seem possible.

I didn't actually try logging out what the test is accessing. But I would assume from looking at the code that if the selector is inside a media query `rule.style` won't be what is expected.

https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/14-responsive-web-design-22/build-a-product-landing-page-project/build-a-product-landing-page.md

```js
const stylesheet = new __helpers.CSSHelp(document).getStyleSheet()
const cssRules = new __helpers.CSSHelp(document).styleSheetToCssRulesArray(stylesheet)
const usesFlex = cssRules.find(rule => {
  return rule.style?.display === 'flex' || rule.style?.display === 'inline-flex'
})
assert(usesFlex)
```

Forum: https://forum.freecodecamp.org/t/product-landing-page-build-a-product-landing-page-8w6hc8gqzk1w-bqdykvdf/528722

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-product-landing-page-project/build-a-product-landing-page

### Your code

```

```

### Expected behavior

Allow flexbox to be set inside a media query.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by sagivab** [comment]
Hi @lasjorg,

I've been looking to this issue and been able to solve it by iterating the rules if it's instanceof CSSMediaRule like the following:
```
if(rule instanceof CSSMediaRule) {
    for(let i=0; i<mediaRules.length; i++) {
      if(mediaRules.item(i).style?.display == 'flex') {
```
I know it's not efficient because media rules can be nested in others and I don't catch this cases, any suggestions how to parse the data in more efficient way? 

Thanks!

**Comment by Preet-Sojitra** [comment]
Is this issue still open?

**Comment by ieahleen** [comment]
@Preet-Sojitra feel free to open a PR if you think you can fix the issue
