### ISSUE TITLE
Typo: 'switches' instead of 'squishes' in question of 'Neural Networks: Activation Functions'

### ISSUE THREAD

**Issue by delivey** [freeCodeCamp/freeCodeCamp#46909]
### Describe the Issue

https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/neural-networks-activation-functions

In the page above, a question (Which activation function switches values between -1 and 1?) uses 'switches' when the actual word should be 'squishes' (like Tim says in the video)

### Affected Page

https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/neural-networks-activation-functions

### Your code

```
Not applicable.
```

### Expected behavior

The question should be: Which activation function squishes values between -1 and 1?

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 103.0.5060.114

**Comment by raisedadead** [comment]
@delivey please go ahead.
