### ISSUE TITLE
Blank Space / Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by Tataboj** [FreeCodeCamp/FreeCodeCamp#4690]
Challenge [http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery](http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello, while trying to proceed in my learning I have found a blank space in this task and do not know how to continue, can you help, pls. Thank you https://space.zeo.net/g/32kgz

**Comment by ltegman** [comment]
Hmmm, I am not able to reproduce this error. Have to tried refreshing your browser or pressing the reset button on the left hand side of the page? If neither of those work, do you have any browser extensions enabled? Do you see any errors in the console?

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
