### ISSUE TITLE
Replit config update status for Node.js challenges and projects

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46910]
### Describe the Issue

I thought it might be nice to have a separate issue for tracking Replit config updates to the Node.js challenges/projects. We may want to do the same for Python. This is a work in progress so excuse the mess.

### Challenges

[Managing Packages with npm](https://www.freecodecamp.org/learn/back-end-development-and-apis/managing-packages-with-npm/) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-npm/pull/419
- Learn PR: Not necessary. Learners just need to add `"moment": "2.14.0"` to the `dependencies` array in `package.json`, but it does not need to be pre-installed, or installed through the Replit command line. While installing packages with the command line does work with the recent fixes, `"moment": "2.14.0"` just needs to be in the `dependencies` array to pass the test, and the package doesn't actually have to be installed.

**Note:** There is [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/46924) to swap out the older version of Moment.js for an empty [@freecodecamp/example](https://www.npmjs.com/package/@freecodecamp/example) package. But that shouldn't affect our efforts here, and updates to this project and its boilerplate can still be considered complete

[Basic Node and Express](https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/) ✅
- Boilerplate PRs:
  - https://github.com/freeCodeCamp/boilerplate-express/pull/96
  - https://github.com/freeCodeCamp/boilerplate-express/pull/98
- Learn PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/47048

[MongoDB and Mongoose](https://www.freecodecamp.org/learn/back-end-development-and-apis/mongodb-and-mongoose/) ✅
- Boilerplate PRs:
  - https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/46
  - https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/48
- Learn PRs:
  - https://github.com/freeCodeCamp/freeCodeCamp/pull/46911
  - https://github.com/freeCodeCamp/freeCodeCamp/pull/47129
  - https://github.com/freeCodeCamp/freeCodeCamp/pull/47133

### Projects

[Timestamp microservice](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/79

[Request Header Parser Microservice](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/request-header-parser-microservice) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-headerparser/pull/28

[URL Shortener Microservice](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/49

[Exercise Tracker](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/63

[File Metadata Microservice](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/file-metadata-microservice) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-filemetadata/pull/21

---

### Challenges

[Quality Assurance and Testing with Chai](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/learn-how-javascript-assertions-work) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-mochachai/pull/79
- Learn PR: Not necessary

[Advanced Node and Express](https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-advancednode/pull/24
- Learn PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/47050

### Projects

[Metric-Imperial Converter](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/pull/24

[Issue Tracker](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/25

[Personal Library](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/personal-library) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-library/pull/16

[Sudoku Solver](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/sudoku-solver) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-sudoku-solver/pull/25

[American British Translator](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/american-british-translator) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-american-british-english-translator/pull/21

---

### Challenges

[Information Security with HelmetJS](https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-infosec/pull/47
- Learn PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/47052

[bCrypt](https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/understand-bcrypt-hashes) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-bcrypt/pull/13
- Learn PR:https://github.com/freeCodeCamp/freeCodeCamp/pull/47052

### Projects

[Stock Price Checker](https://www.freecodecamp.org/learn/information-security/information-security-projects/stock-price-checker) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-stockchecker/pull/23

[Anonymous Message Board](https://www.freecodecamp.org/learn/information-security/information-security-projects/anonymous-message-board) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-messageboard/pull/22

[Secure Real Time Multiplayer Game](https://www.freecodecamp.org/learn/information-security/information-security-projects/secure-real-time-multiplayer-game) ✅
- Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game/pull/19

---

### Expected behavior

Some green check marks.

### Additional context

https://github.com/freeCodeCamp/freeCodeCamp/issues/46824

**Comment by moT01** [comment]
Note: The exercise tracker PR had *.html in the .gitattributes file, but it was still using html/css/js instead of node. I added .css in there and it started using node.

**Comment by moT01** [comment]
At least a few of the remaining boilerplates need the dependencies added to the package - and the instructions that tell users to install them need to be removed on /learn - similar to the mongo boilerplate we did.

**Comment by lasjorg** [comment]
When I import the Node projects we fixed, Replit now wants to update the run command and add "run" to it. Even though that absolutely shouldn't be needed with an npm start command.

![config-run-command](https://user-images.githubusercontent.com/28780271/182047313-965dca10-15e9-4d82-b636-100f9f1b2876.png)


The suggestion it makes, and can auto-correct, works just fine. So strictly speaking, we might not need to update anything again. Although it isn't the best UX for the camper to see that message.

**Comment by scissorsneedfoodtoo** [comment]
Hey @lasjorg, thanks again for catching this.

I just started a new Replit project with the latest changes in the [boilerplate-infosec](https://github.com/freeCodeCamp/boilerplate-infosec) repo, and unfortunately, it doesn't seem like changing the `run` command to `"npm run start"` has made a difference — I still see the same "Configure the Run Command" message when starting a new project.

We may need to reach out the Replit team to take a look at this. Like you mentioned, it shouldn't matter whether we use `npm start` or `npm run start`. And while I don't mind the second command, it's strange that the same message still pops up.

[This section of the docs](https://docs.replit.com/programming-ide/configuring-repl#replit-reference) mentions that a list of strings is preferred whenever possible. But when I tried changing the command to `["npm", "run", "start"]` in my fork, I get the same message.

**Comment by ShaunSHamilton** [comment]
Regarding the above: I have seen that message in a lot of my REPLs, for ~ a month now, and, just like Kris, the message appears regardless of the existence of a `run` config.

**Comment by lasjorg** [comment]
@scissorsneedfoodtoo I honestly just assumed it would, I never tested it with a new import. I don't see why it would prompt for something that already exists. It does seem more like an issue Replit needs to handle.

**Comment by scissorsneedfoodtoo** [comment]
@lasjorg, no worries, I assumed that would work as well. If there's something we can do on our end in the future to get rid of that message, we can set up another issue like this to create a battle plan and check progress. But I'm guessing it's something on their end that can possibly be fixed.
