### ISSUE TITLE
#320.1 build-a-kitty-ipsum-translator

### ISSUE THREAD

**Issue by vetrisuriya** [freeCodeCamp/freeCodeCamp#46912]
### Describe the Issue

https://www.freecodecamp.org/learn/relational-database/learn-advanced-bash-by-building-a-kitty-ipsum-translator/build-a-kitty-ipsum-translator

I typed the code correctly but I have no idea how to complete this level.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-advanced-bash-by-building-a-kitty-ipsum-translator/build-a-kitty-ipsum-translator

### Your code

```
./script.sh < name.txt 2> stderr.txt > stdout.txt

```

### Expected behavior

I typed the code correctly but I have no idea how to complete this level.

### Screenshots

![freecodecamp_issue](https://user-images.githubusercontent.com/34440110/179282221-ce9add80-a383-4fb6-bb83-ea20d064df5d.png)
![freecodecamp_issue_1](https://user-images.githubusercontent.com/34440110/179282229-fa9d82d1-2059-4816-985a-a3785b179e93.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Hey, what text do you have in the `name.txt` file?

**Comment by vetrisuriya** [comment]
> Hey, what text do you have in the `name.txt` file?

freeCodeCamp

**Comment by mackotron** [comment]
Have you tried closing this terminal and opening new one ? I found that, if CodeRoad doesn't open automatically and you open it manually, the terminal which had been open before CodeRoad, doesn't work with it.

**Comment by vetrisuriya** [comment]
> Welcome, have you tried closing this terminal and opening new one ? I found that, if CodeRoad doesn't open automatically and you open it manually, the terminal which had been open before CodeRoad, doesn't work with it.

Thanks buddy it works, thanks for taking your time to reply my issue. Have a nice day.
