### ISSUE TITLE
Typo in step 73 buliding skyline hint from new RWD

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46921]
### Describe the Issue

there is a typo in cramers-rule challenge, `determinates` is used instead of `determinants` which is wrong

this sentence

> You should give the second new `div` a class of `fbab`.

should be changed to 

> You should give the second new `div` a class of `fb1b`.

Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e9911.md

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-73

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [discord](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by DeepaPrasanna** [comment]
Hi, May I work on this issue ?

**Comment by Sboonny** [comment]
@DeepaPrasanna of course, feel free to open pull request, after you have read the guide line
