### ISSUE TITLE
developmentuser should have keyboard shortcuts already enabled

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#46923]
### Is your feature request related to a problem? Please describe.

During testing of the local version, it's easier to use keyboard shortcuts to navigate between challenges.

### Describe the solution you'd like

Please let's have the development user having them already enabled.

### Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/26656284/179346758-a28efc39-8eb0-4921-94b0-a88a56d4ffb7.png)

**Comment by raisedadead** [comment]
This should be it: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/8f19b1926bc51c0149254fdd7a86ecb0708c6dd2/tools/scripts/seed/seedAuthUser.js#L88
