### ISSUE TITLE
Learn Basic CSS by building a cafe menu - step 17

### ISSUE THREAD

**Issue by Njong392** [freeCodeCamp/freeCodeCamp#46930]
### Describe the Issue

Instruction requires you to add a self closing link tag, add a rel with value of stylesheet and a href = "styles.css". But test is not passing for some reason.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-17

### Your code

```
/* file: index.html */
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Cafe Menu</title>
  <link href="styles.css" rel="stylesheet"/>
</head>
<body>
  <header>
    <h1>CAMPER CAFE</h1>
    <p>Est. 2020</p>
  </header>
  <main>
    <section>
      <h2>Coffee</h2>
    </section>
  </main>
</body>
</html>
```

### Expected behavior

Test was suppposed to pass with self closing link tag, and also with an extra closing link tag.

### System

- Device: No info
- OS: Windows 10
- Browser: No info
- Version: No info

**Comment by Njong392** [comment]
And I just wanted to ask this. For the System part of the issue template, if the issue was created based on problems faced by a camper, do I ask them about their device info?

**Comment by gikf** [comment]
I'm not able to reproduce the issue.

> And I just wanted to ask this. For the System part of the issue template, if the issue was created based on problems faced by a camper, do I ask them about their device info?

Generally yes, it might not always be needed, but if the issue is not happening for everybody, specific device, os or browser can play some role in the problem.

**Comment by jdwilkin4** [comment]
HI @Njong392 ! 

I am also unable to replicate the issue.

Maybe you have a browser extension messing with the tests.
Have you disabled all browser extensions and run the test again?
Or maybe you can run this test in another browser.

I am testing in chrome and it passes for me.

**Comment by Njong392** [comment]
This problem was faced by a camper. I'll just go ahead and close this issue if no one else can reproduce the problem.
