### ISSUE TITLE
Can't go to next challenge in New Responsive Web Design 

### ISSUE THREAD

**Issue by kriscdesign** [freeCodeCamp/freeCodeCamp#46933]
### Describe the Issue

Successfully checking your code, changing something, then trying to submit and go to the next challenge will do nothing. If someone checks their code for correctness, goes back and removes extra spaces/new lines, they will be stuck!

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design

### Steps to Reproduce

1. Go to any step in the responsive web design curriculum ([step 1](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1), for example)
2. Successfully check your code so that it passes
3. Go back and remove/add any characters, including spaces or new lines
4. Get stuck forever 💀 (or at least until refreshing the page)

### Expected behavior

Any of the following would be fine:
1) keep the check button there
2) just re-check automatically when trying to submit new code
3) update the button so that it goes back to "check your code" after any changes to the editor

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome v103.0.5

**Comment by Sboonny** [comment]
Couldn't replicate in edge, did you make sure that you undo step 3?

**Comment by kriscdesign** [comment]
@Sboonny Oooh, sorry about that. Changed the affected page link to the new RWD
