### ISSUE TITLE
Misleading hint in step 23 at building a quiz project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46934]
### Describe the Issue

there is a misleading hint in [step 23](https://github.com/freeCodeCamp/freeCodeCamp/blob/85b009b308b1beccad0b4f5e7ee302cc396a54a1/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6143931a113bb80c45546287.md) at building a quiz project, it reads as follows:

> You should place the `span` after the text content `D.O.B.`.

it is testing for span closing tag, so the hint should be changed to 

> You should place `span` closing tag after the text content `D.O.B.`.

Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/85b009b308b1beccad0b4f5e7ee302cc396a54a1/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6143931a113bb80c45546287.md

### Code

The hint may lead to people typing this code as in https://forum.freecodecamp.org/t/learn-accessibility-by-building-a-quiz-step-23/530303/7

```html
         <div class="info">
            <label for="birth-date">D.O.B. <span class="sr-only"></span></label>
            <input type="date" name="birth-date" id="birth-date" />
          </div>
```

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-23

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [discord](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by mackotron** [comment]
Hey, If you mean something like this: `<span class="sr-only">D.O.B.</span>` then it doesn't work, but `D.O.B. <span class="sr-only"></span>` passes. The linked case has been solved and that wasn't the issue.

**Comment by Sboonny** [comment]
@mackotron The issue is in the hint, when you type the code, the hint isn't describing correctly what the test is doing.

**Comment by ieahleen** [comment]
> ```
>   <label for="birth-date">D.O.B. <span class="sr-only"></span></label>
> ```



that's the correct code, look at next challenge

**Comment by Sboonny** [comment]
Oh I see now, thank you @ieahleen, and @mackotron. 😅😳 let me apologize to the guy in the forum real quick
