### ISSUE TITLE
`task.once` is invalid in worker-executor.js

### ISSUE THREAD

**Issue by masterX89** [freeCodeCamp/freeCodeCamp#46949]
## Describe the bug

`task.once` is invalid in `client/src/templates/Challenges/utils/worker-executor.js`.

## To Reproduce

1. add a test in `client/src/templates/Challenges/utils/worker-executor.test.js`

   ```js
   it('Task should emit handler once', () => {
     mockWorker();
     const testWorker = createWorker('test');
     const task = testWorker.execute('test');
     const handler = jest.fn();
     task.once('testOnce', handler);
   
     task.emit('testOnce', handler);
     task.emit('testOnce', handler);
     expect(handler).toBeCalledTimes(1);
   });
   ```

2. run this test

3. If `task.once` works well, then `handler` will be called just once.

4. However, `handler` is called twice time.

## Expected behavior

`handler` should only be called once.

## Analyze

There is only one parameter `handler` in the function `self.removeListener` on Line 141

https://github.com/freeCodeCamp/freeCodeCamp/blob/8f19b1926bc51c0149254fdd7a86ecb0708c6dd2/client/src/templates/Challenges/utils/worker-executor.js#L141

```js
self.once = (event, listener) => {
  self.on(event, function handler(...args) {
    self.removeListener(handler);
    listener.apply(self, args);
  });
  return self;
};
```

But function`removeListener` needs two parameters (`event` and `listener`), since `handler` is type of function instead of type of string, so the program never enters the if judgment.

```js
  self.removeListener = (event, listener) => {
    if (typeof self._events[event] !== 'undefined') {
      const index = self._events[event].indexOf(listener);
      if (index !== -1) {
        self._events[event].splice(index, 1);
      }
    }
    return self;
  };
```

## Solution

Perhaps Line 141

https://github.com/freeCodeCamp/freeCodeCamp/blob/8f19b1926bc51c0149254fdd7a86ecb0708c6dd2/client/src/templates/Challenges/utils/worker-executor.js#L141

should be changed to

```js
self.removeListener(event, handler);
```

and change Line 96

https://github.com/freeCodeCamp/freeCodeCamp/blob/8f19b1926bc51c0149254fdd7a86ecb0708c6dd2/client/src/templates/Challenges/utils/worker-executor.js#L96 to

```js
task.done = new Promise((resolve, reject) => {
  task
    .on('done', data => resolve(data))
    .on('error', err => reject(err.message));
});
```

**Comment by ojeytonwilliams** [comment]
Thanks for the report @masterX89. I'm not aware of any serious side effects of this bug, but I agree that `once` is not behaving as expected.

That said, I think `task.done` is fine as is: I don't believe we will want to respond more than once to 'done' or 'error'.

Would you be interested in creating a PR fixing the `removeListener` call? Then we can investigate and make sure there are no bad side-effects.

**Comment by ojeytonwilliams** [comment]
It's a tricky one to migrate - I tried myself and it was a bit of a mess.  However, with your changes the number of arguments should match up, so that should help the migration.

**Comment by masterX89** [comment]
sorry, I just misunderstood your meaning.

> That said, I think task.done is fine as is: I don't believe we will want to respond more than once to 'done' or 'error'.

If I just fix `removeListener` to `self.removeListener(event, handler)` then it works and will really remove handler.

Then the following tests will throw errors (expected: 1, received: 0) in this line `expect(handler).toBeCalledTimes(1)` because handler has been removed when `task.done`:
- Worker executor should successfully execute one task
- Worker executor should successfully execute two tasks in parallel
- Worker executor should reject task
- Worker executor should emit LOG events
- Worker executor should reject task on timeout

**Comment by ojeytonwilliams** [comment]
Thanks for explaining. The tests failing aren't surprising, but the concern is: do these broken tests represent new bugs or were the tests broken in the first place?

**Comment by masterX89** [comment]
Thanks for sharing idea , I figure it out.
I should reduce `index` and `length` in the `emit` because it may call `Array.prototype.splice` in `removeListener`

**Comment by ojeytonwilliams** [comment]
Awesome, I'm glad you were able to figure it out - that file is pretty confusing.
