### ISSUE TITLE
Wrong test number referenced in Run Functional Tests Using a Headless Browser II challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#46944]
### Describe the Issue

Two of the typos are minor but one could be confusing
In the first paragraph of the instructions (see below), there is a reference to 
> Within tests/2_functional-tests.js, in the 'Submit the surname "Vespucci" in the HTML form' test (// #5), automate the following:

The actual test number to change is `#6` and not `#5`, so it should be changed to reflect this.

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser-ii

### Your code

```
n/a
```

### Expected behavior

n/a

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by mackotron** [comment]
Hey, I created pull request for this issue.
