### ISSUE TITLE
FreeCodeCamp social media links can be included on both the header and the footer 

### ISSUE THREAD

**Issue by michaelteye** [freeCodeCamp/freeCodeCamp#46946]
### Is your feature request related to a problem? Please describe.

Including a social link in the header(navbar)will enable sponsors and students to know more about the community with the help of social media.

### Describe the solution you'd like

Including a social link in the header(navbar)will enable sponsors and students to know more about the community with the help of social media.

### Describe alternatives you've considered

Including a social link in the header(navbar)will enable sponsors and students to know more about the community with the help of social media.

**Comment by ahmadabdolsaheb** [comment]
Thank you for the feature request. Since there is a link to our moderated community (forum) in the main menu, having links to other social media is not a priority for now.  As a result I will be closing this issue.
