### ISSUE TITLE
Building a Rothko Painting - move syntax example from step 35 to step 34

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#46955]
### Describe the Issue

It would make more sense for step 34 to have the filter syntax example, instead of it showing up in the next step.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-34

### Your code

```
selector {
  filter: blur(3px);
}
```

### Expected behavior

Explain and show the syntax.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/rule-explanation-not-where-its-supposed-to-be-responsive-web-design-course/531328

**Comment by ieahleen** [comment]
Yes, that totally needs to be done

what about step 35? there I think the example is to remind people how to give same rules to multiple selectors. Should that be removed? double blur example?

**Comment by lasjorg** [comment]
Not sure if we need a selector list example as long as the hint text shows the selector. But I would like for the hint text to actually specify it as a selector list.

> Hint You should have a `.one, .two` selector list.
