### ISSUE TITLE
Indroductory course on how to use FCC?

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#46972]
### Is your feature request related to a problem? Please describe.

Has the topic of creating a quick introductory course on how to use FCC ever come up? It feels like a lot of the issues that keep coming up over and over again in the forums could potentially be avoided if FCC offered a quick intro course that taught people how to use the system and also made them aware of the common pitfalls that tend to catch people.

I won't list all of my ideas for such a course now. Just wanted to know if the topic has ever come up and if it would even be considered as something that was needed.

 

### Describe the solution you'd like

A short introductory course that would walk new users through the basics of how to use the system and also make them aware of common issues new users have so that they can avoid them.

### Describe alternatives you've considered

If an actual course doesn't work then perhaps a static document.

**Comment by jdwilkin4** [comment]
If it were to be a video course, it would get a lot of views on the youtube channel. Maybe Ania or Beau could do it and it would be really popular. 

> If an actual course doesn't work then perhaps a static document.
An article on the fcc news publication would work. 
Plus it could be translated into the other non english news publications too.

**Comment by naomi-lgbt** [comment]
The challenge with a video course is that they are remarkably difficult to update.

**Comment by jdwilkin4** [comment]
> If someone needs to watch a video to figure out how to use our website, the problem is our site is too confusing.

From my experience from helping people on the forum, I think a lot of people are very intimidated to start learning programming.  I don't think it is always that the site is hard to navigate but rather people feel more comfortable getting started with a video. 
Videos like this already exist through non freecodecamp accounts. 
https://www.youtube.com/watch?v=9DCpQG1KVGk

After reading through those video comments, it seems like people feel more comfortable going through the course. 

But I also understand Naomi's point about videos going out of date quickly.

**Comment by Njong392** [comment]
> 
> But I also understand Naomi's point about videos going out of date quickly.

Then perhaps a static site or article would be preferable in this case? It'll be easier to update, and this is better in my opinion because it could get translations so that many people can access it (as mentioned above)

**Comment by moT01** [comment]
It should be like the "getting to know the buttons" part of a video game. When you first turn on a video game, you often have a short period at the start where they teach you the buttons and mechanics of the game. I think we could potentially try to create something like this - it should be interactive and on the website, with popups that explain the buttons and then have users click everything. Maybe a short, few step project in a block before the cat photo app.

**Comment by ahmadabdolsaheb** [comment]
Thinking out-load here.
- If we end up with an article, we could add a link of it to the help section if the user has less than a number of completed challenges.
- we could cook the "getting to know the buttons" in the entry points of the curriculum. For instance, users are told what some of site functionalities are and we let them pass the tests.

**Comment by bbsmooth** [comment]
I like this discussion, but to be honest, my main intent was not to teach people how to use the interface, because I think it is for the most part pretty clear, but rather more about making them aware of common problems and giving them the tools to figure them out. For example, a lot of people don't realize that case matters in these steps. So they've basically done the step correctly except they haven't properly capitalized a word. If we included a step in an introductory course that made them aware about the need capitalize exactly as the text is presented in the description then hopefully that would make them more vigilant about such things as they proceed through the courses.

Another common problem is people changing parts of the HTML that they weren't asked to and the tests being very sensitive about that and thus they fail. A step in an introductory course explaining that they should only make the changes specifically asked for in the description and should not change anything else would hopefully prevent a lot of these types of issues that come up on the forum.

And how many forum issues are a simple typo? A step that instructed them that they should always check for typos if things are working correctly might help reduce these types of forum posts. The exercise could be to have them fix the intentional typos in a sentence or simple piece of code.

These are the types of issues I was thinking could be covered in the course.

**Comment by moT01** [comment]
I know what you mean about these problems @bbsmooth...

> If we included a step in an introductory course that made them aware about the need capitalize...

I don't really think an extra step for something like this is needed. This indicates to me that the steps themselves aren't clear enough. I would lean towards not creating something like this - but, if it's done right, might not be too bad.

> Another common problem is people changing parts of the HTML that they weren't asked to...

I can see more of a need for something to help with this - something to explain the editable region, and that it's the only area where they will need to add or change code. Although - again, this feels like an issue with the tests on the steps themselves not working good enough. Maybe not in all cases, not sure.

I guess I'm not sure what exactly you had in mind for an introductory course @bbsmooth - a few things were mentioned here and we're still discussing it. If it's on the site, I'm not a big fan of the things I responded to here. If it's something external - like a video or article, I'm fine with any type of explanation there.

I've noticed the many forum posts, here's an idea that might help. We added the functionality for "notes" to be added on steps - mentioned [near the top of this issue.](https://github.com/freeCodeCamp/freeCodeCamp/issues/43668) It's just a chunk of markdown that would show in the steps. None of the steps have these notes, so they don't show up anywhere - but the functionality still exists (pretty sure). One of the plans was to put the solution for each step in these notes. We could implement that so campers have access to the solution of every step - it may cut down the forum posts, hopefully not too much though.

**Comment by bbsmooth** [comment]
I'm perfectly fine with not having a separate introductory course to deal with this stuff. It was just one idea that came to mind. We can integrate it into the existing cat photo app course, add a "notes" feature, create articles/videos, whatever. I do think that more people will be likely to complete a short intro course than watch a video or read an article, but I could be wrong about that.

> I guess I'm not sure what exactly you had in mind for an introductory course

Primarily, to make people aware of the common issues/problems that many beginners have with these courses and to give them some skills to both avoid those issues and help them fix their problems when they fail a test. I've listed some of those above (not a comprehensive list for sure). Perhaps it might be helpful to create a list of the most common issues and then we could figure out how to address each one.

**Comment by Bharath314** [comment]
I have an idea that could potentially hit multiple birds with a single stone.
We could have a course named "Learn how the web works by making a forum post".
We could teach them the basics of the web by having a mock conversation with a fictional user similar to the discobot tutorial. This way we can teach them the basics of the web, forum etiquette and markdown syntax all at the same time. 
We could even have a certification project where the user has to write an essay in markdown containing the answers to some fill-in-the-blanks type questions that the camper has to google to figure out.

**Comment by ahmadabdolsaheb** [comment]
So it would be helpful to accumulate these topics to so we could design our course accordingly.
One thing that comes to mind is that if there is an error in the input, the tests/hints should deal with that.
We can have tests to notify the users of case sensitivity (if the input is correct, but casing is not) and if the user has edited outside the editable region (for new RWD perhaps)

**Comment by bbsmooth** [comment]
Here's another "lesson" I would teach in this course. Don't add unnecessary spaces. Getting a lot of forum posts lately because the user has put spaces around the equals sign when adding an attribute to an element. Or they add space between the opening/closing tags and the text. A lot of tests are very strict about these unnecessary spaces.

**Comment by moT01** [comment]
If this is something that goes on the website, I'm not a huge fan of some of the suggestions here. This may be some people's first introduction to coding, I think we want them to get excited about it as fast as possible. Maybe just my opinion, but I think that's one of the goals of the cat photo app - get them writing code and seeing results ASAP. They start adding photos on step 8 - and cats are... popular.

Many of the problems mentioned here seem more like problems with the tests or instructions - and not something campers should need to learn.

**Comment by bbsmooth** [comment]
I'm getting the sense that some sort of introductory course is not in the future, and that's fine, I was just curious if it had ever been considered and what people's opinions of it were. I do think that this discussion has given us some ideas as to how we can improve the current courses to help beginners be more successful and minimizing the common errors that keep showing up in the forum. I'm under no illusions that we can reduce these errors to `0`. But I've also seen plenty of competent learners post to the forum with errors that I am very surprised they are making, which tells me that we could probably do a better job of preventing some of them.

I think the general consensus here is to focus on improving the instructions, tests, and hints where needed. So that's where I'll put most of my energy. Thanks everyone for the feedback.

**Comment by ahmadabdolsaheb** [comment]
I am closing this issue since " the general consensus here is to focus on improving the instructions, tests, and hints where needed." :)
