### ISSUE TITLE
Typo in language lead handbook

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46977]
there are two typos in the file 

- [ ] a typo in this line, `there two places` should be `there are two places`, here is the line

https://github.com/freeCodeCamp/freeCodeCamp/blob/d0e42982f070e9ec8ba95be308af1ea090384421/docs/language-lead-handbook.md#L34

- [ ] a typo in this line, `settngs` should be `settings`, here is the line 

https://github.com/freeCodeCamp/freeCodeCamp/blob/d0e42982f070e9ec8ba95be308af1ea090384421/docs/language-lead-handbook.md#L269

---

Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/d0e42982f070e9ec8ba95be308af1ea090384421/docs/language-lead-handbook.md

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by Nishant-96** [comment]
Can i take this issue?

**Comment by Sboonny** [comment]
@Nishant-96 feel free to open pull request, after you have read our guidelines

**Comment by hrittik2002** [comment]
I have fixed both the typo errors. Can you accept my PR

**Comment by ashwathhalemane** [comment]
I was about to take up this task, but later I understood this is closed, can this PR be closed if merged?

**Comment by Sboonny** [comment]
Yes the is will close with @Nishant-96 pull request
