### ISSUE TITLE
Missing period at the end of setup mobile app locally document

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46970]
### Describe the Issue

in the docs, there is a line that is missing period at the end of it.

> We also recommend installing the official <a href="https://docs.flutter.dev/get-started/editor?tab=vscode">extensions</a>

These should have period in the end of it

Here is the markdown file [/docs/how-to-setup-freecodecamp-mobile-app-locally.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/b0faf882e1a603144d19d17248b0f7424f010f44/docs/how-to-setup-freecodecamp-mobile-app-locally.md)

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by adity2911** [comment]
I will work on that
