### ISSUE TITLE
Code snippets do not fit into code editor on phone

### ISSUE THREAD

**Issue by chibuikes** [freeCodeCamp/freeCodeCamp#46975]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
For some reason my code in the editor does not fit into the screen anymore. It is out of the screen. 

**To Reproduce**
1. Go to '. Go To  any code editor on freecodecamp'
2. Type  '. Console.log("any sentence longer than the size of a phone screen's width")...'
4. See error 'the code does not go to the next line it all remains on one line'

**Expected behavior**
The code should go to the next line after the sentence gets longer than the phone screen's width

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: redimi 9a
 - OS: octa processor
 - Browser: chrome
 - Version: 2021 version

**Additional context**

**Comment by bbsmooth** [comment]
> 1. Go to '. Go To  any code editor on freecodecamp'

@chibuikes Could you be very specific here and tell us exactly where you go to trigger this issue? Giving us a link to the specific challenge would be best, but if not possible then tell us exactly which course and which challenge/step it is.

**Comment by chibuikes** [comment]
Javascript  algorithm and data structures certification exam ,cash register(),this is where it started from. You don't actually need a picture but I will still send one. The problem is that my codes in the code editor doesn't fit into my screen, that is, I have to scroll horizontally when I want to read my code,instead of vertically.
This problem is now on all of the code editors in my freecodecamp account.

PS : I code on my phone

**Comment by bbsmooth** [comment]
@chibuikes Try this. In a blank space in the editor, hold your finger down on the screen for a good second and then let up. You should see a pop-up menu. Select the Command Palette at the bottom. In the search box that show up, type start typing "Toggle Accessibility". At some point it should narrow down to one option. Select that option and see if that doesn't fix your problem.

**Comment by chibuikes** [comment]
Ok,I will try this now. also please how do I send pictures?

**Comment by chibuikes** [comment]
Ok,I will try this now. also please how do I send pictures?

**Comment by chibuikes** [comment]
Problem solved . Thank you!

**Comment by bbsmooth** [comment]
You had accidentally turned on accessibility mode for the editor. This mode is primarily for people who use screen readers and it is much easier to use a screen reader with the editor if the lines don't wrap.
