### ISSUE TITLE
Incorrectly indented code in steps 12 through 89 of the Learn Intermediate CSS by Building a Picasso Painting project

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#46982]
### Describe the Issue

I came across [this forum topic](https://forum.freecodecamp.org/t/why-div-does-not-have-closing-tags/532489) where the user was confused about opening/closing tags for `div` elements.  After looking at step 12 of the project, I noticed the starting code for step 12 (the solution for step 11) added an indentation of 4 spaces not needed for the `<div class="characters">`.  Also, the `</body>` has too much indentation.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-picasso-painting/step-12

### Incorrect code

Instead of the starting code looking like:
```html
  <body>
    <div id="back-wall"></div>
        <div class="characters">

          </div>
      </body>
```

### Expected behavior

It instead should look like:
```html
  <body>
    <div id="back-wall"></div>
    <div class="characters">

    </div>
  </body>
```
This affects all the remaining steps through step 89 (the final step).  This will be an easy but tedious task to fix all the steps.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by emcode93** [comment]
I discovered this issue and would love to help fix it!

**Comment by Sboonny** [comment]
Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/93b3151cca51becd237c3a58083f99a02b5059fb/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-picasso-painting/60b69a66b6ddb80858c51582.md

this issue requires changing the seed contents, especially these lines

https://github.com/freeCodeCamp/freeCodeCamp/blob/93b3151cca51becd237c3a58083f99a02b5059fb/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-picasso-painting/60b69a66b6ddb80858c51582.md#L45-L52

**be careful** and don't delete `--fcc-editable-region--`

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by ieahleen** [comment]
@emcode93 issues are not assigned, feel free to open a PR

@hrittik2002 don't trust PR titles, there isn't such a folder, the steps are in curriculum/challenges/english/14-responsive-web-design-22/learn-the-css-box-model-by-building-a-rothko-painting
Please read the contributing guidelines at contribute.freecodecamp.org

**Comment by ieahleen** [comment]
@Sboonny you have linked only one step, but this issue is for all the steps between 12 and 89

**Comment by Sboonny** [comment]
thank you @ieahleen, I have edited my original comment

**Comment by RandellDawson** [comment]
This would be much easier to fix using the Challenge Editor.  @ieahleen created [an issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/46987) to have instructions for using it added to the [How to Work on Practice Projects](https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects?id=how-to-work-on-practice-projects) guide.
