### ISSUE TITLE
Lesson Instructions unclear

### ISSUE THREAD

**Issue by niaskywalk** [FreeCodeCamp/FreeCodeCamp#4698]
After using the various other Waypoint formats, running into this created confusion. It made me believe I somehow had to use .text() in the solution. Perhaps some rearrangement of the paragraphs or a clarification of what the solution asks for will help.

**Comment by erictleung** [comment]
Can you be most specific on which Waypoint instructions are unclear or at what point did the confusion start?

**Comment by ltegman** [comment]
Closing since no details have been provided. Please provide more details if you are still experiencing issues.
