### ISSUE TITLE
Typo in building a picasso painting step 50

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#46994]
### Describe the Issue

There is a typo in learn-intermediate-css-by-building-a-picasso-painting, `elemnts` is used instead of `elements`.

Here is the typo

https://github.com/freeCodeCamp/freeCodeCamp/blob/84a41308c02ce4fac2b0db6a23ac21e9ba1590a0/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-picasso-painting/60b69a66b6ddb80858c515a7.md#L14

Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-picasso-painting/60b69a66b6ddb80858c515a7.md

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-picasso-painting/step-50

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [discord](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by anoopano** [comment]
can i take this up

**Comment by Sboonny** [comment]
@anoopano feel free to open pull request after you have read the guidelines
