### ISSUE TITLE
Include CodeReview Room as possible  Feedback area

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4699]
Right now the only "official" way to get feedback on a project is to tweet it out.  This won't scale.  We should encourage campers too use the CodeReview Room. 

Should be included in the Zipline into and getting set sections.  Elsewhere?

**Comment by chandowd** [comment]
I agree there should totally be something like that even if it just a 'Hey we're here to help too' kind of thing.
