### ISSUE TITLE
Update the forum link for "Ask for Help" button in Chinese curriculum

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#46992]
The Chinese forum has been moved to https://forum.freecodecamp.org/c/chinese/533, and the links in the curriculum should be updated.

**Comment by raisedadead** [comment]
I have updated the keys, and the builds should be out in a while on production. @naomi-lgbt can you help check if that worked or we need more changes?

**Comment by naomi-lgbt** [comment]
I'll follow up once the deployment completes!

**Comment by naomi-lgbt** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/63889819/180517837-a15a5845-2401-4af3-ab16-9a152bb81e52.png">

I can confirm that the Ask for Help button points to the right location now.
