### ISSUE TITLE
The instructions are confusing

### ISSUE THREAD

**Issue by sweann** [FreeCodeCamp/FreeCodeCamp#4700]
You want us to use filter()  to remove all values equal to or greater than 5, not just greater than 5.

**Comment by erictleung** [comment]
Are you referring to the [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) challenge?

"Use `filter` to remove all elements from `array` that are greater than 5."

So I don't think there's anything wrong with the wording of the problem. The challenge asks to remove all values "greater than 5" (i.e. numbers > 5) but another way to look at it is to keep all values less than or equal to 5 (i.e. numbers <= 5). I hope that helps.

**Comment by BerkeleyTrue** [comment]
@erictleung That is correct.

Happy Coding!
