### ISSUE TITLE
Typo in step 22 of registration form practice project

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47009]
In the file curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f85a62fb30c80bcea0cedb.md

https://github.com/freeCodeCamp/freeCodeCamp/blob/b22f28d7738099ba2b1a8fd0e058ecc8f0dd05c5/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f85a62fb30c80bcea0cedb.md?plain=1#L10

There is a typo, "chose" should be "choose".

If you would like to fix this issue please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by ShivamMadlani** [comment]
I would like to work on this

**Comment by RandellDawson** [comment]
@ShivamMadlani Go for it.

**Comment by JohnathanTWebster** [comment]
Added updated wording and is linked to issue.

**Comment by RandellDawson** [comment]
We have two pull requests with the same change.
