### ISSUE TITLE
CatPhotoApp Step 12 is not clear

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47010]
There are many users every day having issues with this step.

I have no idea what could be changed, but something would need to be changed

**Comment by Sboonny** [comment]
We can make it two steps one adding a link and the other deleting it

**Comment by bbsmooth** [comment]
I think one of the causes for confusion with this step is that this is the first time we are really asking them to embed one element within another and they don't realize they can do that. Granted, they have been embedding elements within elements all along, but each element they have added up to this point has taken up the entire line. So I could see that they may think you can only have one element per line. Now we are asking them to put two elements on the same line, one within another. We might want to make it clear in the description that this is allowed and that tags can be inserted in the middle of text.

**Comment by bbsmooth** [comment]
Here's some more common mistakes:
- They add the link with the "cat photos" text at the very end of the sentence, thus duplicating "cat photos" in the sentence.
- They add the link with the "cat photos" text but delete the rest of the sentence so that the only text in the `p` is "cat photos".
- The add the link correctly but include the period inside the anchor tags.

**Comment by jeremylt** [comment]
One thing that I noticed is that our description of Step 6 less obviously calls out the nesting as a concept, which might be contributing to the confusion

**Comment by bbsmooth** [comment]
Here's my first attempt at a new description for step 12.

>You can see the words `cat photos` underlined next to the image in the preview now. That's your link; feel free to give it a click. So far, every element you have added has been on its own line. But you can also nest elements on the same line. For example, you can nest an anchor (`a`) element inside of a `p` element to turn part of the text into a link.

> In the text of your `p` element, turn the words `cat photos` into a link to `https://freecatphotoapp.com`. The words in the text should stay exactly the same. You should only add the opening and closing `a` tags to create the link. After you have created the link in the `p` element, remove the old link below the paragraph.

**Comment by jeremylt** [comment]
What about this variant? Anecdotally, I have had good success by saying something like what I added to paragraph 3.

> You can see the words cat photos underlined next to the image in the preview now. That's your link; feel free to give it a click.

> You can put an anchor (`a`) element inside of your `p` element to turn part of the text into a link. Placing one element between the opening and closing tags of another element is called nesting.

> In your `p` element, replace the words 'cat photos' with the entire anchor element on the following line. The text of your `p` element will look the same, but the words 'cat photos' will become a link.

> After you have nested the link in the `p` element, remove the old anchor element below the `p` element.

**Comment by bbsmooth** [comment]
> You can put an anchor (a) element inside of your p element to turn part of the text into a link. Placing one element between the opening and closing tags of another element is called nesting.

We do define nesting now in step 6, but I guess there is nothing wrong with defining it again. Actually, I like this one sentence definition better than what we have in step 6 right now. I would vote that we replace the four word sentence definition currently in step 6 with this sentence.

> In your p element, replace the words 'cat photos' with the entire anchor element on the following line. The text of your p element will look the same, but the words 'cat photos' will become a link.

This is exactly what is happening in this step of course, but I can't help but feel that it is basically just telling them to copy/paste without understanding what they are actually doing. I like the idea of telling them to "turn the words `cat photos` into a link" so that they have to make the connection between the previous "cat photos" link they have already created and the new one they need to create. In other words, they should (hopefully) realize that they can turn any word(s) into a link by wrapping them in `a` tags.

**Comment by bbsmooth** [comment]
I'm beginning to realize that even though the previous two steps walked them through how to turn a group of words into a link, they don't realize that that is what they have just done and so they don't understand what it means to turn the words "cat photos" into a link. Perhaps we need to reiterate this a little more clearly.

> In the previous steps you turned the words `cat photos` into a link by surrounding them with an opening `<a>` tag and closing `</a>` tag. You can now see the words `cat photos` underlined next to the image in the preview now. That's your link; feel free to give it a click.

**Comment by jeremylt** [comment]
I like that idea.

I also agree that we should split this step it half

12 -> turn `cat photos` in the `p` into a link
13 -> delete the duplicate `a` element

---

So, summary so far

1) Update Step 12

> In the previous steps you turned the words cat photos into a link by surrounding them with an opening `<a>` tag and closing `</a>` tag. You can see the words `cat photos` underlined next to the image in the preview now. That's your link; feel free to give it a click.

> In the text of your `p` element, turn the words cat photos into a link to https://freecatphotoapp.com. 

2) Create new Step 13 (and shift all later Steps by 1)

> Now there are two links with the text `cat photos`. Remove the second anchor tag and text on the line below the paragraph.

---

Thoughts?

**Comment by bbsmooth** [comment]
I think what you have is almost perfect. I would make one addition.

> In the previous steps you turned the words `cat photos` into a link by surrounding them with an opening `<a>` tag and closing `</a>` tag. You can see the words cat photos underlined next to the image in the preview now. That's your link; feel free to give it a click.

> You can also turn words inside of a `p` element into a link by surrounding them with an opening `<a>` tag and closing `</a>` tag. In the text of your `p` element, turn the words `cat photos` into a link to `https://freecatphotoapp.com`.

I think we still need to emphasize that it is OK to nest an anchor element inside of a `p` element. I'm trying to use the same terminology in both paragraphs, so the wording is slightly awkward and not the way I would normally say it, but I think consistency is very important here.

And yes, definitely split this into two steps.

**Comment by bbsmooth** [comment]
I'm also predicting, based on what I see in the forums, that people will still add a second "cat photos" to the end of the `p` element and make that the link. I'm fine leaving this unaddressed for now. I'm just making a prediction that I think there is a good possibility we will be revisiting this issue again and making it clear that they shouldn't add any new text to the `p` element :smile:

**Comment by jeremylt** [comment]
:+1: to waiting to see what happens, but I suspect you are correct. I like the cycle we have going of incremental updates based upon what we see on the forums.

**Comment by Arun-Mclaren** [comment]
They add the link with the "cat photos" text at the very end of the sentence, thus duplicating "cat photos" in the sentence.
They add the link with the "cat photos" text but delete the rest of the sentence so that the only text in the p is "cat photos".
The add the link correctly but include the period inside the anchor tags.

**Comment by Jagrutiti** [comment]
Hey everyone,

To resolve this issue I will replace instructions from [this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/47010#issuecomment-1206688744) instead of step 12. 

I hope I have got it right.

**Comment by ieahleen** [comment]
There is also https://github.com/freeCodeCamp/freeCodeCamp/pull/47320 about trying to improve step 12

**Comment by Jagrutiti** [comment]
> There is also #47320 about trying to improve step 12

I did not see a PR linked to the issue. Shall I delete this PR?

**Comment by ieahleen** [comment]
It's not linked, that was @jeremylt forgetfulness
