### ISSUE TITLE
Missing code block around the hint in step 21 of building a piano project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47015]
### Describe the Issue

in step 21 of building a piano project, the hint in line 30 is missing code blocks

> Your `img` element should have a `class` set to logo. 

This should be changed to

> Your `img` element should have a `class` set to `logo`. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/343b7f70eede56860097df1ea7a9f9d60146ee7e/curriculum/challenges/english/14-responsive-web-design-22/learn-responsive-web-design-by-building-a-piano/612eaf56b7ba3257fdbfb0db.md#L29-L31

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by DylanDevelops** [comment]
I believe I did all this right. This is my first time contributing to open source. Very exciting :))
