### ISSUE TITLE
Link redirects to porn website 

### ISSUE THREAD

**Issue by Dark2412** [freeCodeCamp/freeCodeCamp#47023]
### Describe the Issue

![Screenshot 2022-07-24 193428](https://user-images.githubusercontent.com/97246023/180659206-d01d80aa-f228-4c19-a986-e3e6f8460f4d.png)

In step eight of the Responsive Web Design course ( " Create a cat photo app" is a link. If you paste it in your browser with a german ip, you get redirected to a p*rn website. This should be fixed soon  xD

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-8

### Steps to Reproduce

Please change the link so nobody gets redirected to this website

### Recommended fix or suggestions

Change the link

### Screenshots

![Screenshot 2022-07-24 193850](https://user-images.githubusercontent.com/97246023/180659302-d310304b-5af9-4cdf-bf90-678a5405c6ae.png)

**Comment by DylanDevelops** [comment]
I can try to fix this but I'll let you guys know if I can't figure it out.

**Comment by DylanDevelops** [comment]
This is not recreating for me. I used a VPN and connected to Germany but it just goes to this site so I'm not sure if this is just something affecting you.

<img width="1512" alt="Screen Shot 2022-07-24 at 4 17 24 PM" src="https://user-images.githubusercontent.com/48571264/180667982-529ccfe7-fb05-4ee3-9908-ec0992976100.png">

**Comment by DylanDevelops** [comment]
I ended up recreating it and it didn't direct me to a p*rn website but it did direct me to scam websites so I changed the link and hopefully it should be fixed. Thanks for noticing this!

**Comment by AlexMNet** [comment]
It also didn't redirect me to a p*rn site.

**Comment by SaintPeter** [comment]
I got redirected through several sites and landed on a faux Google.

Bottom line: we should use something like example.com which is specifically designed for usage like this. Alternately, we should use a domain owned and controlled by fCC.

**Comment by AlexMNet** [comment]
That's a great idea @SaintPeter

**Comment by DylanDevelops** [comment]
I'll implement this now. Thanks fo the suggestion!
