### ISSUE TITLE
Missing code block on step 4 of building a balance sheet

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47024]
### Describe the Issue

in step 4 of building a balance sheet, the hint in line 16 is missing code blocks

>  Your existing span element should have the `class` attribute set to `flex`. 

This should be changed to

>  Your existing `span` element should have the `class` attribute set to `flex`. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/85a110e2642eee73f94b450ddf5ddff9c13854db/curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/61fd67a656743144844941cb.md#L16

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by AlexMNet** [comment]
I can take care of this!
