### ISSUE TITLE
Code in HTML window is not loaded completely.

### ISSUE THREAD

**Issue by pravinmache** [FreeCodeCamp/FreeCodeCamp#4702]
Challenge [Waypoint: Set the Font Family of an Element](http://www.freecodecamp.com/challenges/waypoint-set-the-font-family-of-an-element?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3AMonospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family:Monospace;
  }
</style>

<h2 class="red-text">
```

**Comment by SaintPeter** [comment]
If you click "Reset" and clear your code it will pull the rest of the code down.  It's unclear why it didn't work the first time . . but sometimes things happen.

Closing as this appears to be a single user experience.

Thanks and happy coding!
