### ISSUE TITLE
24 Game is missing answers.

### ISSUE THREAD

**Issue by DanielFacchiano** [freeCodeCamp/freeCodeCamp#47028]
### Describe the Issue

There are tons of different ways to write this algorithim, that will come up with tons of different variations of the acceptable equation that reaches 24. 
My algorithim came up with the following solutions:
for set 4878 my algorithm returns 7 * 8 - 4 * 8 which is 24, but that will fail the test
for set (1234) my algorithm returns ( 3 + ( 1 + 2 ) ) * 4 which is 24, but will fail the test. (for set (1234)
and for set 6897 we get  6 * 8 / ( 9 - 7 ) which is 24, but will fail the test
and  3 * 4 / 1 * 2 and i'm sure plenty more...

The question does not specify a specific equation it wants, only that it should be 24 and fit the format. So for this reason, I think its broken, and either needs its answer bank revised, or needs to have numbers with only 1 or 2 solutions chosen for the tests.

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/24-game

### Your code

```
function solve24 (numStr) {
  let nums = numStr.split("").map((elem)=>{
    return [elem, ""+elem];
  })
  let answer = false;
  let ops = ['+','-','*','/']

  const recursive24 = (nums) => {
    if(nums.length == 1){
      if (nums[0][0] == 24){
        answer = nums[0][1];
      }
      return
    }
    if(answer){
      return
    }
    // select first number
    for(let x = 0; x < nums.length; x++){
      //select a operator
      for(let j = 0; j < ops.length; j++){
          //select second number
        for(let k = 0; k < nums.length; k++){
          if (k == x){
            continue
          }
          // copy new array, remove nums from it.
          let newArr= nums.slice().filter((val, index)=>{
            if (index ==k || index == x){
              return false
            }
            return true
          });
          let exp = nums[x][1]+ops[j]+nums[k][1];
          if (j<=1 && newArr.length > 0){
            exp="("+exp+")";
          }
          let val = eval(exp)
          newArr.push([val,exp])
          recursive24(newArr)

        }
      }
    }
  }
  recursive24(nums);
  console.log(answer)
  if(answer===false){
    return "no solution exists"
  }
  return answer;
}
```

### Expected behavior

Should pass the tests, but it fails because the answer bank does not have enough equation results.

### System

Desktop
free code camp terminal

**Comment by ieahleen** [comment]
This is the file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/24-game.md

At this point I don't know...
1. check it contains the required numbers
2. use `eval` or something? to check that it actually results to 24?

**Comment by ieahleen** [comment]
cc/ @jeremylt

**Comment by jeremylt** [comment]
This challenge again.

Mathematically there should be a wide range of possible solutions - I'm not wild about using eval but we could make a small parsing function to check strings.

**Comment by abhi3315** [comment]
@jeremylt Why don't we create a script to find out all the possible solutions and then add those permutations to the test-cases array? A valid solution can have 4 digits, mathematical operators (`+`,`-`,`/`,`*`,`%`), brackets, and at the max length of 11. For example `(6*8)/(9-7)` has 4 numbers, operators, brackets, and a max length of 11.

I can write out the script and update the possible cases. What do you suggest?

**Comment by jeremylt** [comment]
There is a very large possible number of solutions. I do not think it is a good idea trying to write every single possible solution out.

**Comment by abhi3315** [comment]
What about evaluating with regex?

A possible solution can have the following case-
`( n $ n ) $ (n $ n)`
`( n $ n ) $ n $ n`
`n $ ( n $ n ) $ n`
`n $ n $ ( n $ n )`
`n $ n $ n $ n`
`n $ ( n $ n $ n )`
`( n $ n $ n ) $ n`
`$` => Mathematical operator, `n` => Number

We can extract the operator and number and calculate them. Need to take care of the precedence of the operator and brackets.

**Comment by jeremylt** [comment]
Or we could skip all that and make a simple, lightweight expression parser.

**Comment by abhi3315** [comment]
Parsing is fine but evaluation of the expression to the target answer is tricky!

**Comment by jeremylt** [comment]
Not really though, since we only have four operations. I'm making up a smaller parser right now

**Comment by abhi3315** [comment]
Great! Please share it in the thread once done.

**Comment by jeremylt** [comment]
This isn't fully bulletproof, but this is the basic idea:
```javascript
const OPERATORS = {
  "+": (a, b) => a + b,
  "-": (a, b) => a - b,
  "*": (a, b) => a * b,
  "/": (a, b) => a / b,
}

const PRECIDENCE = {
  "+": 1,
  "-": 1,
  "*": 2,
  "/": 2,
}

function evaluate(expression) {
  expression = expression.replace('/\s+/g', '');
  const stack = [];
  let postfix = "";

  // Convert from infix to postfix
  let head = 0;
  while (head < expression.length) {
    let c = expression[head];
    switch (c) {
      case "(":
        stack.push(c);
        break;
      case ")":
        let last = stack.pop();
        while (last !== "(") {
          postfix += last;
          last = stack.pop();
        }
        break;
      case "+":
      case "-":
      case "*":
      case "/":
        while (stack.length &&
               PRECIDENCE[c] < PRECIDENCE[stack[stack.length-1]]) {
          postfix += stack.pop();
        }
        stack.push(c);
        break;
      default:
        postfix += c;
    }
    head++;
  }

  // Clear out stack
  while (stack.length) {
    postfix += stack.pop();
  }

  // Evaluate postfix
  for (let c of postfix) {
    switch (c) {
      case "+":
      case "-":
      case "*":
      case "/":
        const b = +stack.pop();
        const a = +stack.pop();
        stack.push(OPERATORS[c](a, b));
        break;
      default:
        stack.push(c);
    }
  }
  return stack.pop();
}

console.log(evaluate("(3+(1+2))*4"))
```
