### ISSUE TITLE
Reduce require submit times needed to show reset the code button

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47037]
### Is your feature request related to a problem? Please describe.

In forum, people come frustrated, I think when they have the ability to reset their steps early, it will reduce that frustration.

### Describe the solution you'd like

Show reset button after one click. 

Seeing `reset` button showing after one click, will make it look like we are offering tools if they need them, instead of blocking them.

Pressing `reset` button will reset the counter, which should need to be changed, as well. 

### Describe alternatives you've considered

Show `reset` button right away, although easier, it will make people feel, we are blocking need for help button, because you can't access it unless you have submitted three times.

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [Discord server](https://discord.gg/Z7Fm39aNtZ)) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

You can try to take inspiration from this pull request 😉 if you want to tackle it https://github.com/freeCodeCamp/freeCodeCamp/pull/46641

Happy contributing.

**Comment by bbsmooth** [comment]
Agreed. I've had to tell several people in the forum that they need to keep clicking the Check Your Code button in order to get the Restart button.

**Comment by naomi-lgbt** [comment]
IMHO, we should always show the reset button.

**Comment by Sboonny** [comment]
@naomi-lgbt in chance, that someone misclicks the button, sees a shiny red button, doesn't read the message and click it, then reset the code without meaning to, I vote for the first one.

I felt like I am typing a Final Destination movie, while thinking of this possibility 🤣

**Comment by ahmadabdolsaheb** [comment]
That makes sense. We could eventually show both of them as icon buttons side by side and display tooltips on hover to save space.

**Comment by Sboonny** [comment]
I do like the icons, it opens the possibilities to add multiple options.

**Comment by bbsmooth** [comment]
I'll just add that the words "tooltip" and "accessibility" almost never go together. So if we are going to use icon buttons for restart and help then we need to pick icons that are very obvious.

**Comment by moT01** [comment]
Side note - it appears like a mobile size or narrow window can show these buttons twice:
![Screen Shot 2022-07-28 at 8 24 16 AM](https://user-images.githubusercontent.com/20648924/181516291-266ec815-10c2-4470-9e7e-4b711d12c9b5.png)

Maybe this is a separate issue, or potentially something we can fix here if we're going to be working on it.

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth, since we can add related arias to the icon, we keep the tooltips completely hidden from screen readers. It is just there to reduce confusion for visual users

@moT01, mobile needs redesign :.)

**Comment by bbsmooth** [comment]
@ahmadabdolsaheb Correct, tooltips aren't a problem for screen reader users because icon buttons are required to have a programmatically accessible name to begin with. But by default they are not accessible to visual users who use only a keyboard. You can fix them to make them keyboard accessible, but it's a lot of work and potentially annoying for keyboard users. I'm not saying we can't have the tooltips there, just that the icons need to be clearly understandable. Also, it would probably be a good idea to have a help page that explains what these icons do.

**Comment by bbsmooth** [comment]
Perhaps we can just concentrate on a quick fix right now of showing the Reset button after the first attempt if they don't get it right? Moving them to icon buttons and rearranging the format could come later? Do we need to do both at once?

**Comment by Sboonny** [comment]
I have opened this for contribution, and tomorrow I will open a second issue about the icons.

**Comment by Jagrutiti** [comment]
I find this issue interesting and would like to take this up. The thing is I am a noob in React.  

I read the React documentation but will need help from time to time.

**Comment by Sboonny** [comment]
@Jagrutiti thank you for taking interest in this, if you need help with error you are facing you can ask in our [discord server](https://discord.gg/Z7Fm39aNtZ)
