### ISSUE TITLE
Arguments Optional missing a valid test case that would cause existing Guide solutions to fail

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#47044]
### Describe the Issue

I was looking at the existing solutions in the Guide for the [Arguments Optional](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/arguments-optional) challenge and noticed if we added the following valid test case, both Guide solutions would fail.  For this test case, they should return `undefined` but instead return a function.

**Extra Test Case:**
> `addTogether(5, undefined)` should return `undefined`.

I am proposing we add the new test case, add the solution I propose as one of the solutions in the Guide, and refactor/remove the existing solutions.

**Existing Guide Solutions:**

Solution Number 1
```
function addTogether(...args) {
  const [first, second] = args;
  if (typeof first === 'number') {
    if (args.length === 1) {
      return num => {
        if (typeof num === 'number') {
         return first + num;
       }
      };
    }
    if (typeof second === 'number') {
      return first + second;
    }
  }
}
function addTogether() {
  const [first, second] = arguments;
  if (typeof(first) !== "number")
    return undefined;
  if (second === undefined)
    return (second) => addTogether(first, second);
  if (typeof(second) !== "number")
    return undefined;
  return first + second;
}
```
Solution Number 2
```
function addTogether() {
  const [first, second] = arguments;
  // First argument is not a number
  if (typeof(first) !== "number") {
    return undefined;
  }
  // First argument is a number
  //  and second argument is not defined
  else if (second === undefined) {
    function addSecond(second) {
      // New argument is not a number
      if (typeof(second) !== "number") {
        return undefined;
      }
      // New argument is a number
      else {
        return first + second;
      }
    }
    // Note: returning a *function*
    return addSecond;
  }
  // First argument is a number
  //  and second argument is not a number
  else if (typeof(second) !== "number") {
    return undefined;
  }
  // First argument is a number
  //  and second argument is a number
  else {
    return first + second;
  }
}
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/arguments-optional

### Your code

n/a

### Expected behavior

Using the following solution, it would pass not only the existing test cases but also the new one I described in the above section.
```
function addTogether(...args) {
  const [first, second] = args;
  if (args.length === 1 && typeof first === 'number') {
    return num => {
      if (typeof num === 'number') {
        return first + num;
      }
    }
  }
  if (typeof first === 'number' && typeof second === 'number') {
    return first + second;
  }
}
```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jeremylt** [comment]
I tweaked the guide solutions for correctness. I don't have any objection to this extra test case

**Comment by RandellDawson** [comment]
I have opened this issue up for contributors.

The requirements for before submitting a PR for this issue are:
1. Adding the new test case as described in the issue body.
2. Replacing the existing solution in the challenge with the proposed solution above.
3. Validate your changes work by running the following command without receiving any errors:
  `npm run test:curriculum --superblock=javascript-algorithms-and-data-structures`
4. Read through the [How to Work on Coding Challenges](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges) and [How to open a Pull Request (PR)](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=how-to-open-a-pull-request-pr) and use recommended guidelines for creating the PR title and body content.

**Comment by RandellDawson** [comment]
@jeremylt Are you fine with us adding the solution I proposed above to the Guide also?

**Comment by jeremylt** [comment]
Sure, I went ahead and added it

**Comment by Mir-SA** [comment]
can I take this issue to add the extra test case?

**Comment by yashdev9274** [comment]
hello @RandellDawson  I'm Yash and I'm new to github contribution can you please guide me , from where should I start.

**Comment by RandellDawson** [comment]
@yashdev9274 Looks like a PR was already created, approved, and merged.  You can look for other issues to work on.  We appreciate any help you can provide.
