### ISSUE TITLE
user text and user user is too close to the user's avatar.

### ISSUE THREAD

**Issue by staranbeer** [freeCodeCamp/freeCodeCamp#47054]
### Describe the Issue

The profile summary page on the freecodecamp's forums have the user's avatar right next to the user's information which is a little too close in my opinion. 

### Affected Page

https://forum.freecodecamp.org/u/staranbeer/summary

### Steps to Reproduce

https://forum.freecodecamp.org/u/staranbeer/summary

### Expected behavior

Some spacing between the elements would be better.

### Screenshots

![Screenshot from 2022-07-28 00-14-52](https://user-images.githubusercontent.com/62498540/181349449-a1eee99c-0244-4d56-ac9f-c4d528e16c42.png)

### System

- Device:  Laptop
- OS: Ubuntu 20.04
- Browser: Firefox

**Comment by jeremylt** [comment]
Note - we don't write the forum software, so I don't think we can change this

It looks like when the green border for online users is added, the distance between the text and the user photo actually *decreases*. That feels like a Discourse bug.

**Comment by staranbeer** [comment]
so we have no control over how the site the user profile looks? is there nothing we can do?

**Comment by ieahleen** [comment]
there is a forum theme https://github.com/freeCodeCamp/forum-theme
I don't know if the customization allowed by the Discourse software would allow to make this change tho

**Comment by raisedadead** [comment]
Yup - while the platform is hosted by Discourse, we do have the ability to use our theme on top of it for visual things. 

Interested contributors should look at the theme shared in the previous comment. There is documentation on how you can test changes as well.

**Comment by staranbeer** [comment]
Hey! @raisedadead  i actually tried looking for the particular CSS rules that are being used to style the user summary, but i couldn't find anything from the repo that @ieahleen  mentioned.

**Comment by raisedadead** [comment]
You should reach out to the [contributor's chat](https://discord.gg/PRyKn3Vbay) for more help. Goodluck.

**Comment by ahmadabdolsaheb** [comment]
@staranbeer, here is the file that needs changing: https://github.com/freeCodeCamp/forum-theme/blob/main/common/common.scss

Mind, you would need to change the styles for the signed in users.

**Comment by ahmadabdolsaheb** [comment]
@staranbeer Thanks for working on this issue. Your proposed solution resolves the issue with minor changes. Therefore, I am closing this issue accordingly. 
https://github.com/freeCodeCamp/forum-theme/pull/74
Thank you for your contribution.
