### ISSUE TITLE
it's not possible to run the tests for a single challenge in RWD-22

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47057]
In 2022/responsive-web-design there is no way to test for a single challenge.

As there is a step 1 for each practice project, running 
```bash
cd curriculum
npm run test -- -g 'Step 1'
```

as instructed runs a lot of tests

```bash
> @freecodecamp/curriculum@0.0.0-next.4 test
> ts-node ../node_modules/mocha/bin/mocha --delay --exit --reporter progress --bail "-g" "Step 1"

⠦ Populate tests.


  2814 passing (34s)
  3 pending
```

**Comment by naomi-lgbt** [comment]
I wonder if we can updated it to take the file name instead. 🤔

**Comment by moT01** [comment]
Here's [the area of code where the challenges get filtered.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/test/test-challenges.js#L176) If someone wants to add more options to test a single challenge, I'm fine with it.

**Comment by ieahleen** [comment]
it could make sense
 - file name
 - project-dashed-name/step-#

**Comment by moT01** [comment]
Throwing a help wanted label in case someone wants to give it a try - seems like an addition with no downside.

**Comment by a2937** [comment]
I'm having trouble replicating OP's beginning result. It just reports no test files found. My belief is that the run method needs overridden as well.


![Screenshot of running the command](https://i.imgur.com/JBwxT0S.png)

**Comment by raisedadead** [comment]
See: https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges

Does this help answer your query?

**Comment by a2937** [comment]
Yes it does.
