### ISSUE TITLE
Wrong description in truncate a string bonfire question.

### ISSUE THREAD

**Issue by iammangod96** [FreeCodeCamp/FreeCodeCamp#4706]
In the question description the following section -
" If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length.".
This should be stated as follwoing to get the code accepted -
" If the num is less than 3, then the length of the three dots is not added to the string length."
I had solved all the problems in algorithm scripting but this one because according to previous description my code was not getting accepted.
As soon as I wrote the code for the new description I got my code accepted.

**Comment by ltegman** [comment]
Agreed. It still should say "less than or equal to", but you are correct that `num` is the real number we're concerned with, not the input string length.

**Comment by AryanJ-NYC** [comment]
@ltegman Are you doing this? I was just getting started. I'll stop if you started already.

**Comment by ltegman** [comment]
@AryanJ-NYC It looks like @iammangod96 already put in a PR for this (#4708), they just didn't link it to this issue.

**Comment by s3ned** [comment]
But that still goes for the A- part. Either string or num is smaller then 3

**Comment by ltegman** [comment]
@s3ned If `num` is smaller than 3 you still honor the truncation it's asking for, you just don't count the dots towards the character count. If you did count them you'd end up with an output of `...` for the test case `truncate("A-", 1)`. Instead, you trim the string to a length of 1 like the function call indicates, giving you `A` and then add on the dots to produce an output of `A...`

**Comment by s3ned** [comment]
Oke, I will do that, but the description suggests otherwise. And it will break others like when the string is equal to the num. It just sounds wrong to me. The description that is.

**Comment by EgoPlacebo** [comment]
Lol I was so confused by the instructions for this task, seeing this solved my problem almost instantly; specifying that it is the length of num helps a lot!

**Comment by gitasong** [comment]
I agree. Instead of "If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length," the instructions need to say "If the length of the original string..." or "If the length of the truncated string..." or both.
