### ISSUE TITLE
Missing code block on step 31 of building a registration form

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47074]
### Describe the Issue

in step 31 of building a registration form, the description in line 10 is missing code blocks

>  Nest the select element (with its option elements)

This should be changed to

>  Nest the select element (with its `option` elements)

https://github.com/freeCodeCamp/freeCodeCamp/blob/972dbd5c27579ffc77c10acc6fec8170943cf1dd/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fac56271087806def55b33.md?plain=1#L10

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by Vedanshi555** [comment]
hey , i would like to solve this issue, but i can't find the step 31...can you help me with it?

**Comment by ieahleen** [comment]
Maybe also `Balance Sheet` and `AcmeWidgetCorp` need to be in code blocks

OH! That is a different file! LOL @Sboonny 

---

@Vedanshi555 this file here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/972dbd5c27579ffc77c10acc6fec8170943cf1dd/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fac56271087806def55b33.md?plain=1#L10

**Comment by Vedanshi555** [comment]
@ieahleen thankss

can i get assigned to this issue?

**Comment by ieahleen** [comment]
@Vedanshi555 issues are not assigned, feel free to open a PR. Check the contributing guidelines!

**Comment by Sboonny** [comment]
@Vedanshi555 feel free to open pull request after reading the guidelines 👍

Even after 100 PRs juggling between files still doing this silly mistake. Thanks for the backup, I have updated the link
