### ISSUE TITLE
Remove "6 spaces" from hints for cat photo app step 6

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47084]
### Describe the Issue

The new description seems to be working well as the amount of step 6 issues in the forums has gone way down. But I think the hints are still causing confusion for some people, primarily the mention of 6 spaces. If they don't get it right on the first try then they start adding six spaces to everything.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6

### Your code

N/A

### Expected behavior

Remove the mention of six spaces completely in the hints. Personally, I think there should be just one hint that says something like:

"Hint: Restart this step to get the original indentation back. Then, only add two more spaces in front of the `p` element. Do not change anything else."

My experience is that once they get it wrong then they start changing other things they shouldn't and they ultimately need to restart to get the original formatting back anyway. So let's just tell them to do that immediately. I guess this would also mean that we would need the restart button to show on the first fail.

### System

N/A

**Comment by DylanDevelops** [comment]
I'll try to get this.

**Comment by DylanDevelops** [comment]
I added the line:

> Your `p` element should be below the comment so that the formatting is consistent. Remember, that's 3 indents from the start of the line.

instead of:

> Your `p` element should be below the comment and its opening tag should start 6 spaces over from the start of the line.

Not sure if this is exactly what you are looking for but I belive it works better than making it so they have to restart. If they are still stuck, clicking check  more times will allow them to restart.

**Comment by bbsmooth** [comment]
> I believe it works better than making it so they have to restart.

I think we will have to disagree there :-) My experience in the forums is that they almost always have to restart the step to get the original formatting back because they have changed things they shouldn't have and they just can't get them back to what they should be without restarting.

**Comment by DylanDevelops** [comment]
I get that for most coding problems. There's a point of no return lol. But I feel like this specific step is way harder to get to that point than others.

**Comment by Sboonny** [comment]
Is it possible for the step to count the number of space the camper currently have, and reduce it from `6`. 

the camper will get something like you 

> add `n` of spaces before `p` element

and if they add too much it will turn to 

> remove `n` of spaces before `p` element

**Comment by DylanDevelops** [comment]
That sounds like it could be possible but I don't know how to do that, unfortunately. It wouldn't be able to update constantly though most likely, only when you click the hint button.

**Comment by lasjorg** [comment]
Just as an aside. Something I also noticed is the format of the HTML when creating a help thread.

```HTML
<html>
<body>
  <h1>CatPhotoApp</h1>
  <main>
    <h2>Cat Photos</h2>
    <!-- TODO: Add link to cat photos -->
  <p>Click here to view more cat photos.</p>
  </main>
</body>
</html>
```

At first when I saw it, I was thinking the campers made that change but it's just how the code is formatted when posting.

Not sure why the body is missing the indentation and everything subsequently is missing an indentation level. It just makes it harder to talk about the indentation level when everything is posted with the wrong formatting.

**Comment by bbsmooth** [comment]
@lasjorg I was actually going to create an issue about this very thing yesterday. The auto-formatter is not indenting either the `body` or `head` tags, but all of the FCC steps indent those tags. So when the Ask for Help button is used and the HTML is automatically filled in for the user then we lose the FCC formatting style. Also, if you use the formatter built into monaco you have the same issue.

I'm not sure if CatPhotoApp step 6 is the only step that actually checks for indentation? If so, the maybe it's not worth fixing. Otherwise, we might want to look into whether it is possible to make the auto-formatter indent the `body` and `head` elements so that they follow the FCC indentation style.

**Comment by lasjorg** [comment]
@bbsmooth Maybe open the issue anyway, just to get some more eyes on it?
