### ISSUE TITLE
Learn Typography by building a Nutrition Label:Step 22

### ISSUE THREAD

**Issue by MahijithMenon** [freeCodeCamp/freeCodeCamp#47109]
### Describe the Issue

In this ,we have to add span tag in between p tags and if we give spacing between text present in p tags only then the test cases is accepted.
This case will work:-
```html
    //<div class="label">
      //<h1 class="bold">Nutrition Facts</h1>
      //<div class="divider"></div>
      //<p>8 servings per container</p>
      //<p class="bold">Serving size <span class="right">2/3 cup (55g)</span></p>
    //</div>
```
But This will not work:-
```html
    // <div class="label">
       //<h1 class="bold">Nutrition Facts</h1>
       //<div class="divider"></div>
       //<p>8 servings per container</p>
       //<p class="bold">Serving size<span class="right"> 2/3 cup (55g)</span></p>
     //</div>
```
we can add a new test case which could allow the second one too or can add a description regarding it.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-22

### Your code

```html
 //<div class="label">
      // <h1 class="bold">Nutrition Facts</h1>
       //<div class="divider"></div>
       //<p>8 servings per container</p>
       //<p class="bold">Serving size<span class="right"> 2/3 cup (55g)</span></p>
     //</div>
```

### Expected behavior

This should have been worked or we could actually tell the user to rectify the spacing 

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
Laptop
Windows 11
Brave

**Comment by MahijithMenon** [comment]
how to add html code it is showing the executed code

**Comment by Sboonny** [comment]
@MahijithMenon I have update your post, to show html

**Comment by Sboonny** [comment]
In step https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-24 has similar instructions, because campers do face this earlier, I don't think we should change the description.

**Comment by hanswang123456** [comment]
@MahijithMenon, it would be good to close the issue if no PRs are needed.

**Comment by Sboonny** [comment]
@hanswang123456 I disagree

**Comment by moT01** [comment]
I don't know how much of a problem there is here. Using the code that will not pass above (`<p class="bold">Serving size<span class="right"> 2/3 cup (55g)</span></p>`), you get the hint:

> Your `span` element should have the text `2/3 cup (55g)`.

So that should let users know to remove the space. If you then remove the space to use this code: `<p class="bold">Serving size<span class="right">2/3 cup (55g)</span></p>` - the hint is:

> Your `p` element should still have the text `Serving size 2/3 cup (55g)`.

Which should let them know that they need a space.

A quick forum search shows a few people adding that space, but many others that do it wrong - like including `size` in the span or something. I would be fine with making the tests a little more lenient on that space if we want.

**Comment by hanswang123456** [comment]
@moT01, removing the leading/trailing white space from the span assertion could be an option. That way, the test only has to confirm the correct text(leading/trailing space) and let the general `p` tag test handle any spacing issues.

**Comment by moT01** [comment]
Alright, I'm going to open this up for help. We want to change the test so it allows a space at the start of that span, but keep the test for the paragraph so the sentence is correct. It's the third test in [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/095cf332fe776e89deb2caf950fe1cc0522eec5d/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f42a021625f656101ef93.md)

**Comment by Xavier-Pierre-dev** [comment]
> I don't know how much of a problem there is here. Using the code that will not pass above (`<p class="bold">Serving size<span class="right"> 2/3 cup (55g)</span></p>`), you get the hint:
> 
> > Your `span` element should have the text `2/3 cup (55g)`.
> 
> So that should let users know to remove the space. If you then remove the space to use this code: `<p class="bold">Serving size<span class="right">2/3 cup (55g)</span></p>` - the hint is:
> 
> > Your `p` element should still have the text `Serving size 2/3 cup (55g)`.
> 
> Which should let them know that they need a space.
> 
> A quick forum search shows a few people adding that space, but many others that do it wrong - like including `size` in the span or something. I would be fine with making the tests a little more lenient on that space if we want.

When you are describing like this it's make sens but inside the hint for the test say : 
Your `span` element should have the text `2/3 cup (55g)`. 


But people can misinterpret, thinking that the span element must contain the text and not the exact text without space. After all ` 2/3 cup (55g)` contains `2/3 cup (55g)`. 

<br>

I think the test could be change from : 
```js
assert(document.querySelector('span')?.textContent === '2/3 cup (55g)');
```
to 
```js
assert(document.querySelector('span')?.textContent.includes('2/3 cup (55g)'));
```

I add an image to illustrate :
![illustrate](https://user-images.githubusercontent.com/81990309/186248813-0e75fd31-61fb-452f-be88-5a94cc95507c.PNG)

<details>
<summary>code snippet</summary>

```html
    <div class="label">
      <h1 class="bold">Nutrition Facts</h1>
      <div class="divider"></div>
      <p>8 servings per container</p>
      <p class="bold">Serving size <span> 2/3 cup (55g)  <span></p>
    </div>
    <script>
      
      if(document.querySelector('span')?.textContent.includes('2/3 cup (55g)'))
      {
          document.querySelector("p").style.backgroundColor = "red";
      }
    </script>
```

</details>

**Comment by hanswang123456** [comment]
@Xavier-Pierre-dev, it might be better to remove spaces then check for exact occurrence of '2/3 cup (55g)' . This way if campers insert unwanted text, it won't pass.

Maybe something like:
 `assert(document.querySelector('span')?.textContent.trimStart() === '2/3 cup (55g)');` to remove whitespaces at the start.


And then do `assert(document.querySelectorAll('p')?.[1]?.textContent === 'Serving size 2/3 cup (55g)');` so you have the correct textContent inside the `p` tag.

**Comment by Xavier-Pierre-dev** [comment]
I'm not sur to understand your point if you remove all the space then `2/3cup(55g)` will also pass. 
![illustrategif](https://user-images.githubusercontent.com/81990309/186256242-160ce719-c5f6-4f1a-ad05-b30bcc3f6cb4.gif)

In fact with `includes` i already check if the text contains exactly `2/3 cup (55g)`. I put a gif to illustrate

**Comment by hanswang123456** [comment]
Includes doesn't check for letters added to the start or end which can make error messages less specific.

**Comment by moT01** [comment]
One issue I saw when I looked on the forum was people doing something like this: `<p class="bold">Serving <span class="right">size 2/3 cup (55g)</span></p>` (they put `size` in the span, not supposed to)

So using `.includes` would allow that to pass. I don't think we should be that lenient. Extra spaces, sure - extra text, I don't like it. I am fine with removing the whitespace before (and after?) the text content. Either way works for me.

**Comment by hanswang123456** [comment]
@moT01 for the assertion on the `p` tag: `assert(document.querySelectorAll('p')?.[1]?.textContent === 'Serving size 2/3 cup (55g)')`, it seems like `textContent` is more specific than `innerText`:

**Comment by Xavier-Pierre-dev** [comment]
yes exactly but I think this is exactly what the hint ask here
Your `span` element should have the text ``2/3 cup (55g)``.

and ``2/3 cup (55g) something`` contain ``2/3 cup (55g)``

otherwise the hint should be changed to : 
Your `span` element should only contain ``2/3 cup (55g)``.

in this case i think I think regex will be better : 
![illustrategif2](https://user-images.githubusercontent.com/81990309/186259587-f87ab897-02c0-48b6-830a-4056b50428aa.gif)


<details>
<summary>code snippet</summary>

```html
    <div class="label">
      <h1 class="bold">Nutrition Facts</h1>
      <div class="divider"></div>
      <p>8 servings per container</p>
      <p class="bold">Serving size <span>2/3 cup (55g)<span></p>
    </div>
    <script>
      if(document.querySelector('span')?.textContent.match(/^2\/3 cup \(55g\)$/))
      {
          document.querySelector("p").style.backgroundColor = "red";
      }
    </script>
```
</details>

**Comment by hanswang123456** [comment]
@Xavier-Pierre-dev, regexes do work. Include 1 optional whitespace at the start of the string so there is more flexibility for users. I think that would work well in conjunction with the `p` tag assertion.

**Comment by Xavier-Pierre-dev** [comment]
so here difference beetween the regex is that we can easily allow white space before and after the string so it's more near to 
Your `span` element should **only** contain `2/3 cup (55g)`.

but at the same time the hint say : 
Your `span` element should have the text `2/3 cup (55g)`.
and in this case I think the example I provide with include should work because `2/3 cup (55g) something` contains `2/3 cup (55g)` so that's already follow the hint provided and link to this test. 

I'm not sur if one solution is better than the other I think both will work

**Comment by hanswang123456** [comment]
I think only allowing whitespaces before the element works best. So something like your second version. `document.querySelector('span')?.textContent.match(/^(\s|)2\/3 cup \(55g\)$/)`

**Comment by Xavier-Pierre-dev** [comment]
> I think only allowing whitespaces before the element works best. So something like your second version. `document.querySelector('span')?.textContent.match(/^(\s|)2\/3 cup \(55g\)$/)`

yes I think also I was editing my comment at the same time to add this.

**Comment by hanswang123456** [comment]
Feel free to open a PR and reviewers can review the code.
