### ISSUE TITLE
Cat Photo App 48 - Tests are not checking for radio buttons type attribute 

### ISSUE THREAD

**Issue by sparkO7** [freeCodeCamp/freeCodeCamp#47106]
### Describe the Issue

The tests aren't checking for the `type` attribute for both `radio` buttons, on [step 48](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-48) of the Cat Photo App. 
I can successfully pass this step with no `type` attributes set.

![image](https://user-images.githubusercontent.com/108756150/181942659-ac814c1e-4e70-45c8-aa25-92b635cc6168.png)
Code to replicate the issue :
```
      <label><input id="indoor" value="indoor" name="indoor-outdoor"> Indoor</label>
      <label><input id="outdoor" value="outdoor" name="indoor-outdoor"> Outdoor</label>
```

**Other affected pages :**
- [Step 45](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-45)
- [Step 47](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-47)

## [Step 45](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-45) :

![image](https://user-images.githubusercontent.com/108756150/181946952-20150600-decc-4b55-9c8d-5042c77e062b.png)

Code to replicate the issue :
```
       <label><input id="indoor"> Indoor</label>
```

## [Step 47](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-47) :

![image](https://user-images.githubusercontent.com/108756150/181952315-24aafaed-0179-4316-acea-18ff3e41910d.png)

Code to replicate the issue :
```
          <label><input id="indoor" name="indoor-outdoor"> Indoor</label>
          <label><input id="outdoor" name="indoor-outdoor"> Outdoor</label>
```

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-48

### Your code

```
 <label><input id="indoor" value="indoor" name="indoor-outdoor"> Indoor</label>
 <label><input id="outdoor" value="outdoor" name="indoor-outdoor"> Outdoor</label>
```

### Expected behavior

It would be better if the tests check for the `type` attribute, just like in the following steps :
- [Step 43](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-43)
- [Step 44](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-44)

## [Step 43 ](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-43):
![image](https://user-images.githubusercontent.com/108756150/181981766-fb643cb7-51b4-4688-ad89-787db17bf032.png)

## [Step 44](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-44)

![image](https://user-images.githubusercontent.com/108756150/181979017-81624255-a6b3-456c-86c8-c8176d7ac387.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 103.0.5060.134

**Comment by DylanDevelops** [comment]
I'm gonna try to tackle this issue.

**Comment by DylanDevelops** [comment]
Sorry i'm not really sure how the checking system functions. Here is the code I believe is checking the users answer. Could someone explain it to me. I was confused by the docs on how the checking system works.:

```js
const labelChildNodes = [...document.querySelectorAll('form > label')].map(
  (node) => node.childNodes
);
assert(
  labelChildNodes.filter((childNode) => childNode[0].nodeName === 'INPUT')
    .length === 2
);
```

Both radio buttons should have a `value` attribute. Check that there is a space after the opening tag's name and/or there are spaces before all attribute names.

```js
const radioButtons = [...document.querySelectorAll('input[type="radio"]')];
assert(radioButtons.every((btn) => btn.hasAttribute('value')));
```

The `Indoor` radio button's `value` attribute should be set to `indoor`. You have either omitted the value or have a typo. Remember that attribute values should be surrounded with quotation marks.

```js
const indoorRadioButton = document.querySelector('#indoor');
assert(indoorRadioButton.getAttribute('value').match(/^indoor$/));
```

The `Outdoor` radio button's `value` attribute should be set to `outdoor`. You have either omitted the value or have a typo. Remember that attribute values should be surrounded with quotation marks.

```js
const outdoorRadioButton = document.querySelector('#outdoor');
assert(outdoorRadioButton.getAttribute('value').match(/^outdoor$/));
```
