### ISSUE TITLE
Picasso Painting preview does not look like what the final project ends up looking like if screen width is greater than the preview width

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#47111]
### Describe the Issue

See [this comment on the forum](https://forum.freecodecamp.org/t/not-sure-about-the-final-result-in-picasso-painting-project/5368920) regarding the final version compared to the preview that is shown at the beginning of the project.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-picasso-painting/step-89

### Your code

```

```

### Expected behavior

I expect the final version of the painting to look the same regardless of the width of the preview pane.  I think this project needs to be refactored so that the painting looks the same regardless of the user's screen size.  The elements should not shift around or if they do shift around, they should do so proportionately.  You really notice the differences when you look at the eyes of the characters.  They are hidden in the preview but show up in the final version. Maybe a fixed width for the project should be used.

### Screenshots

**Preview of project:**
![ea5fa87f3302102190ae2dbe4a200dc0101dac11](https://user-images.githubusercontent.com/5313213/182034217-7f5c68b3-3fed-4d4a-8c78-5b23ac398b0b.png)

**Actual final project in preview pane on my screen:**
![image](https://user-images.githubusercontent.com/5313213/182034367-bce3adcd-0269-4023-8933-8704af7c41f1.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by lasjorg** [comment]
Pretty sure it would take a major redesign to make that responsive. It is using a lot of fixed px units for the dimensions and positions. It also looks like some of the elements are not inside the proper containers to have the correct relative/absolute relationship.

I will say the image it is supposed to be is also not the easiest to recreate in CSS.

https://github.com/freeCodeCamp/CurriculumExpansion/issues/132#issuecomment-492755813

**Comment by RandellDawson** [comment]
> Pretty sure it would take a major redesign to make that responsive.

Maybe, but something needs to be done here.  It does not have to be responsive.  It either needs to use percentages to keep things aligned correctly or use fixed widths. When I first saw this project over in the curriculumExplansion repo as a prototype, I assumed it would be a fixed width design when it was transposed over to the curriculum.

**Comment by lasjorg** [comment]
Sure, it can be made fixed width and just have it overflow as well. Without having looked much at the code I would imagine that would still be quite a few code changes and I'd assume as a result test changes.

**Comment by moT01** [comment]
I don't know if this necessarily **needs** to be fixed - but yea, that behavior is a little rough. If someone wants to fix it, I wouldn't oppose.

**Comment by ojeytonwilliams** [comment]
It sounds like quite an extensive rework would be required. Given that it's still recognisably art, regardless of screen size, I think it's fine as is.
