### ISSUE TITLE
Stuck in challenge when I had a typo

### ISSUE THREAD

**Issue by JustLolo** [freeCodeCamp/freeCodeCamp#47117]
### Describe the Issue

I don't know how to address this bc this is the relational database course, and I don't have a link.
But check the picture I uploaded, you should be able to go to the affected code from there.
The issues was I had a typo and when I fixed it I was stuck in the same mini challenge, I have to redo the steps to be able to continue to the next screen, for more references about this issue I had check the steps for reproduce section.

### Affected Page

database 

### Steps to Reproduce

  101  mv menlo.font menlo.otg
  102  mv menlo.otg menlo.otf
  103  ls
  104  mv menlo.otf menlo.otg
  105  mv menlo.otf menlo.otf
  106  mv menlo.otf menlo.otg
  107  ls -l\
  108  mv menlo.otg menlo.otf
  109  clear
  110  ls
  111  mv menlo.otf menlo.font
  112  mv menlo.font menlo.otf
  113  ls
  114  history 20

after 112 I was good to continue

### Expected behavior

after 102 I should be able to finish the minichallenge

### Screenshots

**
![image](https://user-images.githubusercontent.com/103621114/182257401-ea725c66-19db-4929-9771-83b9277dccd6.png)
**

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ojeytonwilliams** [comment]
cc: @moT01

**Comment by moT01** [comment]
Thanks for sharing @JustLolo. The tests are checking that you enter the command you used on 112, as shown in the last hint there. That's why you didn't pass on 102, you made a typo, then tried to continue by fixing the typo - but never entered the expected command.

Someone actually tried to account for this in the [latest changes to that course.](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/CHANGELOG.md#v103) Perhaps they missed that step. I will take a look and see if that's the case and add a fix for it.

**Comment by JustLolo** [comment]
no problem, thanks for the response and for the valuable work you all are doing

**Comment by JustLolo** [comment]
check this too
![image](https://user-images.githubusercontent.com/103621114/182412617-c6d5f44c-3611-4881-8090-29abc8ffd278.png)

I created second_table some steps before because I didn't read correctly, I had to delete the table and create it again, I am not sure if this could be categorized as a bug bc it was a previous mistake

**Comment by moT01** [comment]
That one should have passed if you already created the table. That test just checks if the table exists - the tests likely don't run automatically until you enter an SQL command I think. So I don't think we need to change anything there.

**Comment by JustLolo** [comment]
> the tests likely don't run automatically until you enter an SQL command I think

maybe this was what happened, bc I didn't run any command, I just deleted the table and created it again.

**Comment by 20RitikSingh** [comment]
can i contribute?
