### ISSUE TITLE
Learn Bash Scripting By Building Five Programs

### ISSUE THREAD

**Issue by lawfets** [freeCodeCamp/freeCodeCamp#47115]
### Describe the Issue

When working on the fortune.sh file we are asked to write a function.

> It looks like you can create a function like this:
> 
> FUNCTION_NAME() {
>   STATEMENTS
> }
> Add an empty function named GET_FORTUNE to your script. Make sure the repsonse you are printing is the last thing in the script.

There is a typo in the last sentence of the info you give. "Make sure the "**repsonse**" you...

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-scripting-by-building-five-programs/build-five-programs

### Your code

```

```
no code needed

### Expected behavior

just fix the typo, lol

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for opening this issue.

Tutorial is located at: https://github.com/freeCodeCamp/learn-bash-scripting-by-building-five-programs

This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the `main` branch.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by DylanDevelops** [comment]
I can fix this typo :)

**Comment by DylanDevelops** [comment]
I believe I fixed this typo correctly, but I was a little confused with the guide. You can read the description of the pull request for a more detailed explanation.
