### ISSUE TITLE
Does not accept response incase extra space is added

### ISSUE THREAD

**Issue by footedroom575** [freeCodeCamp/freeCodeCamp#47120]
### Describe the Issue

If the following code snippet response is submitted as a response, the response succeeds. 
```
const makeServerRequest = new Promise((resolve, reject) => {

});
```

But, if we add a space after "new Promise" like: 
```
const makeServerRequest = new Promise ((resolve, reject) => {

});
```
the, response should be accepted technically, but it throws error `Your promise should receive a function with resolve and reject as parameters.
`

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/create-a-javascript-promise

### Your code

```
const makeServerRequest = new Promise ((resolve, reject) => {

});
```

### Expected behavior

should be accepted and the current lessons must be marked as done

### Screenshots

**Code that Works:**

![1](https://user-images.githubusercontent.com/63443749/182313104-dfe76fde-b098-44a2-a36d-99ad0b332567.png)

**Output of above:**

![2](https://user-images.githubusercontent.com/63443749/182313123-9400aa30-4063-432c-81b2-19cd85bf07f2.png)

**Code that does not work:**

![3](https://user-images.githubusercontent.com/63443749/182313132-3b3b5b3c-80eb-4503-a048-496ba2ab1d54.png)

**Output of above:**

![4](https://user-images.githubusercontent.com/63443749/182313147-1d3dac1c-051c-4383-b52b-db3514c2eaa8.png)

### System

- Device: HP 255 g7
- OS: Manjaro Linux
- Browser: Mozilla Firefox
- Version: 101.0.1

**Comment by hanswang123456** [comment]
Proper syntax for a JS promise does not allow for spaces after the word "promise."

**Comment by lasjorg** [comment]
What do you mean by allow?

As far as I know, you can call any constructor with as many spaces before the parentheses as you like. Not sure why you would, but the constructor works just fine.
```js
new Date            ();
```
Proper _formatting_ rules shouldn't allow it, but that has nothing to do with allowed syntax.
