### ISSUE TITLE
Does not accept logically equivalent answer

### ISSUE THREAD

**Issue by footedroom575** [freeCodeCamp/freeCodeCamp#47123]
### Describe the Issue

When I write the loop as:
```
  for (let i = 0; i < len; i++) {
    console.log(firstFive[i]);
  }
```
the response is evaluated to be correct. But similar approach and logically equivalent approach like:
```
  for (let i = 0; i <= len-1; i++) {
  // Only change code above this line
    console.log(firstFive[i]);
  }
  ```
  is rejected.
  
  In first loop, I converted` <= `to` < `to solve OBOE problem. In second loop, I changed the value i is being compared with like  `i <= len-1`

both are acceptable approaches but the response is not accepted in case of 2nd approach.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/catch-off-by-one-errors-when-using-indexing

### Your code

```
function countToFive() {
  let firstFive = "12345";
  let len = firstFive.length;
  // Only change code below this line
  for (let i = 0; i <= len-1; i++) {
  // Only change code above this line
    console.log(firstFive[i]);
  }
}

countToFive();
```

### Expected behavior

Code should be considered as valid and must be accepted.

### System

    Device: HP 255 g7
    OS: Manjaro Linux
    Browser: Mozilla Firefox
    Version: 101.0.1

**Comment by Sboonny** [comment]
the third is the one failing, it's expecting a certain formula. 

We can check if `i` value isn't above `5`, and remove the regex. or we can update the regex to have both possibilities

https://github.com/freeCodeCamp/freeCodeCamp/blob/af288935b973a3b36278bbd9ea8871e1fb3c3230/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/catch-off-by-one-errors-when-using-indexing.md#L49-L53

**Comment by jeremylt** [comment]
Yeah, it looks like a reasonable fix to me.

Side note for @footedroom575 - `i < len` is much more common than `i <= len - 1`, so you should use the first in general over the second

**Comment by moT01** [comment]
[File with the code.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/catch-off-by-one-errors-when-using-indexing.md)

I was going to suggest we reword the instructions, but I think it would be fine to account for both of these possible variations. Here's a regex I made quick: `i\s*<\s*len\s*;|i\s*<=\s*len\s*-\s*1\s*;`

![Screen Shot 2022-08-02 at 10 52 33 AM](https://user-images.githubusercontent.com/20648924/182418090-c9ca7895-30fc-425b-a841-37b43608aaeb.png)

**Comment by jeremylt** [comment]
In general, our rule of thumb is that valid code should pass the challenges.

**Comment by TomJPrice** [comment]
That makes sense to me, thanks for the info.

**Comment by footedroom575** [comment]
> > Yeah, it looks like a reasonable fix to me.
> > Side note for @footedroom575 - `i < len` is much more common than `i <= len - 1`, so you should use the first in general over the second
> 
> Do you think that, despite the answer being _correct_, there is an argument for some form of warning or discouragement against the `<= len-1` pattern so as to promote best practices/common patterns?

Yes you're right. I acknowledge that the former approach should be followed and `<= len -1` should be avoided because of the reason that the CPU is evaluating an extra expression, every iteration i.e. `len-1`.

But my whole point was, it should be at least accepted as an answer since its correct too :)

**Comment by jeremylt** [comment]
It doesn't really have anything to do with `the CPU is evaluating an extra expression'. Micro-optimizations like that aren't often a noticeable performance impact. My point is just that when you defy typical conventions, you make it a little bit harder for others to read your code, which is a "bad thing" (technical term there).

**Comment by Sboonny** [comment]
If you want to contribute, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [discord](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by Sboonny** [comment]
I have marked the discussion about "= Len - 1" as off-topic to not confuse new contributors

**Comment by abhi3315** [comment]
> [File with the code.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/catch-off-by-one-errors-when-using-indexing.md?rgh-link-date=2022-08-02T15%3A53%3A55Z)
> 
> I was going to suggest we reword the instructions, but I think it would be fine to account for both of these possible variations. Here's a regex I made quick: `i\s*<\s*len\s*;|i\s*<=\s*len\s*-\s*1\s*;`
> 
> ![Screen Shot 2022-08-02 at 10 52 33 AM](https://user-images.githubusercontent.com/20648924/182418090-c9ca7895-30fc-425b-a841-37b43608aaeb.png)

Instead of just solving the `len - 1` we should also focus on some other cases too like if some using the index from 1 to 5:
```js
for (let i = 1; i <= len; i++) {
  // Only change code above this line
    console.log(firstFive[i-1]);
  }
```

I am willing to contribute to this issue!

**Comment by jeremylt** [comment]
Personally, I don't think we need to add every single possible way to accomplish this task. The current regex handles the majority of learner solutions. This extra case should handle the overwhelming majority of learner solutions. We can add more if they become necessary.

**Comment by abhi3315** [comment]
I have a question. Do I need to change the files of the other translations like Chinese etc along with English?

**Comment by gikf** [comment]
@abhi3315 no, just English version should be changed. Other languages will be handled using the translation workflow.

**Comment by abhi3315** [comment]
I have raised the PR https://github.com/freeCodeCamp/freeCodeCamp/pull/47139. Please get it reviewed.
