### ISSUE TITLE
please add CodePen link to 

### ISSUE THREAD

**Issue by nikitakoselev** [freeCodeCamp/freeCodeCamp#47131]
### Describe the Issue

In the amazing doc of README.md, the CodePen website doesn't have a link.
When a great website, like a CodePen, doesn't have a link in a README.md of a quality OpenSource project,
a small kitten starts crying somewhere. A small, shaking, frozen kitten.

Please think of kittens and add a hyperlink to the CodePen.
Edited by moderator

Special thanks to [@eazyangel](https://twitter.com/eazyangel)  who made this ticket happen, as we have realized there are no open "first timers only" tickets available.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/README.md

### Steps to Reproduce

Open the README.md and try clicking on CodePen. Nothing happens, but ideally, it should transfer to the CodePen's webpage.

### Recommended fix or suggestions

Make CodePen a hyperlink, pointing at the correct web page.

### Screenshots

![image](https://user-images.githubusercontent.com/6383738/182472340-1684e23e-dd45-44de-b335-f70390216dc7.png)

**Comment by ChocoUnicorn** [comment]
Thank you for raising this issue. Hopefully it gets fixed soon

**Comment by nikitakoselev** [comment]
> 

Congrats on the contribution, you are amazing. Really.

**Comment by jeremylt** [comment]
Please don't use our issue tracker to advertise your project. That's not very friendly.

**Comment by DylanDevelops** [comment]
> Please don't use our issue tracker to advertise your project. That's not very friendly.
Are you saying we shouldn't add this or should we? I can add this if you'd like.

**Comment by jeremylt** [comment]
I have not weighed in on if this is needed or not - I'm not familiar with the current preferences on the README, but we generally limit external links.

My comment was more pointing out that this issue is largely an advertisement for OP's YouTube channel, and trying to use an issue tracker to get advertising is rude, in my opinion.

**Comment by DylanDevelops** [comment]
> I have not weighed in on if this is needed or not - I'm not familiar with the current preferences on the README, but we generally limit external links.
> 
> My comment was more pointing out that this issue is largely an advertisement for OP's YouTube channel, and trying to use an issue tracker to get advertising is rude, in my opinion.

I totally agree with this. I can add the link and then if they approve it then we know it's okay. I might also add a link to replit since it occurs in the same sentence just to keep it consistent.

**Comment by jeremylt** [comment]
I'd wait until someone else weighs in. Like I said, we generally limit external links in our content and I'm not sure if that policy applies here or not.

**Comment by DylanDevelops** [comment]
> I'd wait until someone else weighs in. Like I said, we generally limit external links in our content and I'm not sure if that policy applies here or not.
> 
> It is better to wait for an issue to be ready for a PR rather than making a premature PR and having the content get changed a bunch as everyone gets a chance to weigh in.

Oh, I see this message now. Sorry. I will do that the next time.

**Comment by jeremylt** [comment]
No worries - I was just trying to save on extra work/confusion. You'll know for next time.

**Comment by DylanDevelops** [comment]
> No worries - I was just trying to save on extra work/confusion. You'll know for next time.

I really appreciate all the help. I'm super new to this so learning how these kinds of things are implemented are really helpful.

**Comment by Sboonny** [comment]
@nikitakoselev Thank you for bringing this to our attention, I have edited your original post, to remove self advertisement. 

If you talked to someone about you being able to post your YouTube channel, please let them know, so they can help you post it back.

**Comment by raisedadead** [comment]
Thanks for taking the time to create this issue. I think people interested in this project can quickly figure out popular services and apps. 

We do not think there is any need to add links to everything. Adding a link to every technology / app / service that we mention in our content will just make things more cumbersome.

Thanks.

**Comment by nikitakoselev** [comment]
Hi, I wanted to say I'm sorry for the advertising. I'm autistic, sometimes I make mistakes like that one :( 
My goal is to help people from underrepresented and underprivileged groups to start contributing to OpenSource.
I believe this way they can find an impactful project close to their hearts and find a good job, eventually.

Once again, I am sorry for advertising and I want to thank you for your feedback.
