### ISSUE TITLE
Auto-formatter does not follow FCC indentation standards for `body` and `head` elements

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47146]
### Describe the Issue

This is most noticeable in CatPhotoApp Step 6, since the indentation for that step must be precise in order to pass. 

FCC indentation standards appear to indent the `body` and `head` elements two spaces. This is the way it appears in all default HTML for the steps.

```
<html>
  <head></head>
  <body></body>
</html>
```

But when you use the Ask for Help button, the auto-formatter does not indent the `body` and `head` tags. Thus, for Step 6, the entire indentation is off by two spaces, which has the potential to cause a little confusion when trying to help someone with Step 6. 

Also, the formatting feature in monaco has the same issue. I'm assuming these are tied together.

I have not had time to look into how much work would be involved in trying to fix this issue. If step 6 is the only step the requires precise indentation then perhaps it isn't even worth the effort? 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6

### Your code

N/A

### Expected behavior

Auto-formatter in both Ask for Help process and monoco editor should follow FCC's indentation standards for `body` and `head` element OR FCC could change indentation standards OR we could just ignore this because it might not be worth the hassle to fix.

### System

N/A

**Comment by jeremylt** [comment]
I don't know if it is related, but some user have had 2 spaces of indentation lost when making Javascript help posts as well.

**Comment by ShaunSHamilton** [comment]
To clarify, are we talking about the fomatter (linter)? Or, are we talking about the [create-question-epic](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/redux/create-question-epic.js)?

**Comment by moT01** [comment]
Is it time to just remove this step yet?

**Comment by bbsmooth** [comment]
Since we updated the description to step 6 a few weeks ago, the number of posts about it in the forums has dwindled to almost nothing. So it seems like we can keep it if introducing them to formatting is considered important.

**Comment by moT01** [comment]
I don't think we need to try and make monaco format things the way we want. I'm not against it, but I feel like it might be difficult. If someone want to give it a try, I'm fine with that.

The ask for help button, however, really should have the exact code from the editor so we can be sure of a campers code when they post to the forum. I think we should at least fix that.

**Comment by bbsmooth** [comment]
I have looked at several posts in the forum today and it appears that the formatting is now being left exactly the same as it appears in the editor in the step. So I think we can close this issue.
