### ISSUE TITLE
Replace button with icons in the lower jar of the challenges

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47157]
### Is your feature request related to a problem? Please describe.

As discussed in #47037, swapping buttons with icons then adding tool tips for the icons, will open the possibility for more features that can be helpful for campers

### Describe the solution you'd like

Adding icons and their tooltips to lower jaw with a helping page, that replace the buttons

### Describe alternatives you've considered

Not skilled enough to think of one

### Additional context

We have to make sure that these icons and its tool tips are accessible as mentioned by @bbsmooth, and @ahmadabdolsaheb. For additional info please read their discussion on https://github.com/freeCodeCamp/freeCodeCamp/issues/47037

And I would really love to have the reset icon show after one attempt, but we can give it time in the forum first see if learners complain

**Comment by ahmadabdolsaheb** [comment]
We would need to replace those buttons with icons and then have tooltips for those. I believe we could adjust this issue to prioritize that or update the #46178 to reflect the new action item.

**Comment by Sboonny** [comment]
@ahmadabdolsaheb I have updated the issue, hopefully it will reflect better the requirement.

About moving it, I am worried the reset icon won't change of its moved.

but if you think it would be better to move it, go for it

**Comment by SleemBee444** [comment]
I think i would want to work on this issue, but to be clear, what we are looking to achieve can be implemented same way the YouTube navigation bar icons were right
![tooltip, youtube](https://user-images.githubusercontent.com/83936667/183927933-f9d37dbc-e419-49d6-a45a-0bcd26912928.png)
?

**Comment by ahmadabdolsaheb** [comment]
@SleemBee444 yes, the tooltips should look like bootstrap top tooltip, but should not use bootstrap if possible since we are migrating to our own component library.
https://getbootstrap.com/docs/4.0/components/tooltips/

First, we would need to replace the help and restart buttons to icon button and then add the tooltips.

**Comment by Sboonny** [comment]
We don't assign issue, unless to active contributors. 

Because of Ahmad comment I am opening the issue for contribution. What is needed:

- replace the help and reset buttons to icons
- add tooltips to them


If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by bbsmooth** [comment]
Implementing accessible tooltips is not easy. The WCAG requirements are very hard to meet. And of course there may be issues with hover on touch devices. @SleemBee444, you'll notice that if you use the keyboard to focus those icons at the top of a youtube page that the tooltips don't show (except for the search magnifying glass). Yes, even the big sites don't implement them accessibly.  

I would focus on making the icons obvious enough that tooltips are not needed in the first place. If we don't think that we can find icons good enough for that then we should consider another way to inform the user of what they do that is accessible to everyone. Maybe we could come up with simple text we could make small enough to fit underneath each button (such as "restart" for the restart step button, "test" for the check your code button). Or some type of help functionality that would explain the icons. Or we could try to implement accessible tooltips (perhaps there is a react library out there that gets close, or roll our own).

But I don't think we should rely on the default behavior of the `title` attribute to provide any extra information we feel is necessary to make sense of the icon buttons. If we feel the information is necessary for visual mouse users then it should be available for all users.

**Comment by Sboonny** [comment]
I want this to move forward, so we can use the icons used in our mobile app. If they are confusing, then we can change both for better ones, which is a plus.

Here is the mobile app design: [The Figma design](https://www.figma.com/file/4XPlUi8QGWsmyV7hA8r86m/learn-mobile?node-id=79%3A3123), the figma design is missing the reset button, so here it's: [Reset Button](https://fontawesome.com/icons/arrow-rotate-right?s=regular&f=classic)

About the component itself, I don't really mind how it styled. But for now we need the component to have `inert` attribute, and role of `tooltip`.

```ts
<fCC-Tooltips inert role="tooltip">
```

(optional) It would be lovely to have pseudo-element `::after`, with content like `; Has tooltip ;` so screen readers read something like this

> Button has tooltip reset your current code.

Maybe after a couple of months we remove the tooltips for better components, but we can start small and move to a better component

@bbsmooth, Is this a good starting point to open this for contribution?

**Comment by bbsmooth** [comment]
@Sboonny Tooltips on these buttons aren't for screen reader users. Screen reader users will hear the accessible name of the button when they focus it (e.g. if we use `aria-label="reset code" then they will hear "reset code button" when they focus the button). So we do not need to do anything special for screen reader users like adding extra text about being a tooltip. Basically, screen reader users do not need to know that a tooltip exists for these buttons.

These tooltips are for sighted users who may not understand what the icon means. They should be displayed on both mouse hover and keyboard focus. And there are other requirements on functionality which can mainly be found in [WCAG 1.4.13](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html). A good article about how to implement them accessibly is [Tooltips in the time of WCAG 2.1](https://sarahmhigley.com/writing/tooltips-in-wcag-21/).

The text shown in the tooltip for these buttons should be the same as the accessible name for the button (e.g. if we use `aria-label="reset code" then the text in the tooltip should be "reset code"). This is primarily so people using voice control will know the exact name of the button so they can trigger it with their voice.

It sort of pains me to say this, but if you are only worried about being technically accessible to meet minimum WCAG standards, then giving these icon buttons an accessible name is enough to make it accessible and you can use the `title` attribute to trigger the tooltip without having to do anything special (knowing that you will prevent at least keyboard users from seeing the tooltip). So you can proceed converting these to icon buttons and just use the `title` attribute for now and we can tackle truly accessiblle tooltips at a later time.

**Comment by Sboonny** [comment]
With these comments, I am comfortable opening this for contribution, we can add temporary tooltips as bbsmooth described and prefect it, later. 

What is required: 

- [ ] two Icons button for (submit, and reset)
- [ ] `title`, `aria-label`, and `aria-describedby` to the buttons
- [ ] add temporary tooltip for the two button
- [ ] innerText for tooltips should be the same as `aria-label` in the buttons, 
- [ ] add `aria-hidden="false"` to the tooltips

**Comment by bbsmooth** [comment]
Hey @Sboonny most of the above sounds good but I'm not quite sure I understand everything. Are we going to rely on the `title` attribute and the browser's default tooltip behavior to display them? If so, then we don't need to do anything special other than add `aria-label` for the accessible name and set `title` to the same value. So we wouldn't need `aria-describedby` or `aria-hidden` on anything, unless I am not understanding correctly and there is some other element we are going to use?

**Comment by Sboonny** [comment]
I haven't added them to allow for contribution to choose what they are comfortable with. That being said, I always prefer the default behaviors, because it is easier to spot its issue 🤔, and easier to alter slightly to our needs. I will update my previous comment 👍

**Comment by bbsmooth** [comment]
@Sboonny For the default browser behavior, you only need the first two items and you can just add a note on the second item that the values of `aria-label` and `title` should be the same. That is all you need to do to use the browser's built in tooltip functionality.

If we aren't going to use the default behavior then that second list you have is going to need a lot more checkboxes :-) Also, if we are storing the tooltip text in a separate element, then since these are buttons you would use `aria-labelledby` on the button to give it an accessible name using the tooltip text and you would set the element with the tooltip text to `aria-hidden="true"` so that screen readers don't read it twice. 

Custom tooltips are very complicated. If someone wants to try and implement them then they can let me know here and I will take the time to create a list of all the requirements and links to supported documentation and examples.

**Comment by bbsmooth** [comment]
Just want to add that I spent most of today searching for accessible react tooltip components, just to see what was out there, and was greatly disappointed except for one, the [MUI React Tooltip component](https://mui.com/material-ui/react-tooltip/#basic-tooltip). This implementation is extremely accessible and appears to be highly configurable and customizable. Not sure if we would consider using this but based on accessibility I would highly recommend it.

**Comment by Omkar0803** [comment]
I would like to contribute, can assign me issues?

**Comment by Sboonny** [comment]
there is no assignment @Omkar0803, feel free to open a pull request after reading our [guideline](https://contribute.freecodecamp.org/#/)

**Comment by ahmadabdolsaheb** [comment]
I agree, we should go with having a representative icon that has the same text for `aria-label` and `title`.

**Comment by nayabatir1** [comment]
Can anybody help with the file where actual change needs to be done.

**Comment by mehdibouaziz** [comment]
hi,
I just saw that there is another PR for the same issue but I had mine ready:
- replaced the text inside help and reset buttons with simple svg icons similar to the figma design
- added title and aria-label for default browser tooltip - the tooltip uses the translate function to have a localised text
- removed the btn-block class to allow a more compact UI which will allow more icons in the future - I might add some padding to make the buttons wider so they are easier to click, opinions ?

Result:
![image](https://user-images.githubusercontent.com/31729703/195439462-769bea88-6cd6-4a46-8bfd-4039d5a348d4.png)
