### ISSUE TITLE
Splitting flex-direction concept into two steps for better detailed explaination

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47163]
### Describe the Issue

In https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/6153908a366afb4d57185c8d.md

Instead of only telling the camper to try something, we can give them an explanation of what is happening while they are trying it.

Like for example:

A step explaining the reverse values and ask them to use reverse direction, and 2nd step explains why they shouldn't use reverse direction after seeing its effect, and how it's damaging accessibility, then why they should use explicit values and explain why explicit values are useful.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-12

### Additional context

there is discussion in the pull request about this for more info https://github.com/freeCodeCamp/freeCodeCamp/pull/46639#discussion_r928272135

**Comment by DylanDevelops** [comment]
Was this implemented or is this still awaiting help.

**Comment by Sboonny** [comment]
It isn't decided, if it's even needed @DylanDevelops

**Comment by DylanDevelops** [comment]
Perfect. Thanks @Sboonny

**Comment by hanswang123456** [comment]
I think having a step that describes the flex-box's features would help. Maybe break it into 2 steps where the camper test out some of the properties(with code snippet help) and then get them to setup the gallery without help.

**Comment by Sboonny** [comment]
> where the camper test out some of the properties(with code snippet help) and then get them to setup the gallery without help.

I think, you are talking about something similar to Mozilla docs. Although that would be nice, it would turn steps from challenges to documents.

**Comment by hanswang123456** [comment]
> 
> I think, you are talking about something similar to Mozilla docs. Although that would be nice, it would turn steps from challenges to documents.

That's true. I think your suggestion of putting a step and then reversing the values would be good. Maybe add a step that tests out flex columns?

**Comment by gfr2003** [comment]
I believe that more challenges and support material would help
