### ISSUE TITLE
Move from Standalone MongoDB to replica set

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#4716]
At the moment we are using a standalone mongoDB instance. We are starting to grow fast and will need to upgrade our server for more capacity (we currently use 35 gigs of data on our 80 gig server). 

To move to a replica set we will need to shutdown the server to restart it in replica mode. This cause a temporary outage.

Once this is done we can then add replica databases.

What this gives us is the ability to expand the database later on without needing to shutdown. This should also increase the read speed of MongoDB.

**Comment by bugron** [comment]
Sounds good. Is there any progress on this?

**Comment by BerkeleyTrue** [comment]
Since this is DevOps and not actionable on this repo I'm going to close this issue.
