### ISSUE TITLE
Adding explanation for why campers are doing the instructions

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47165]
### Describe the Issue

In some steps there are description that carry instructions only, this will make campers think of why they are implementing instruction, instead of how to add these instruction and concepts into their future projects.

### Example

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-5

### Additional context

We don't have to explain the concept, but giving something small that they can research, is better than giving nothing

**Comment by bbsmooth** [comment]
Are you thinking of something like this?

> Below your .header element, create a new div element with the id set to gallery, which will act as a container for the images.

> The photo gallery will have ten images. Start by adding ten `img` elements in the `#gallery` element.

**Comment by ojeytonwilliams** [comment]
> Below your .header element, create a new div element with the id set to gallery, which will act as a container for the images.

That seems enough to me. It gives them some motivation and the number of images is implied.

Also, I know this is super nitpicky, but I'd go with this: 

> Below your .header element, create a new div element with the id set to gallery. This will act as a container for the images.

Longer sentences put slightly more burden on the reader, so, since the objective is to be almost painfully clear, I'd favour short ones.
