### ISSUE TITLE
Registration Form Step 55: Clarify instructions

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47175]
### Describe the Issue

Seeing a lot of forum posts for this step in which they add the `1em` top/bottom margins correctly but they change the left/right margins to `0`. Not sure why this is happening, but perhaps we can make it a little clearer that they should keep the left/right margins at `auto`.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-55

### Your code

Most of the time I see this:

```
margin: 1em 0 1em 0;
```

And sometimes I see this:

```
margin-top: 1em;
margin-bottom: 1em;
margin-left: 0;
margin-right: 0;
```

### Expected behavior

I think by this step the user has been exposed to the `margin` shortcut property and should know that the first value is for top/bottom and the second value is for right/left. Hopefully this is a valid assumption. Based on this, perhaps change the instructions to:

> Change the `margin` property to include `1em` on the top and bottom. Be sure to leave the right and left margins at `auto`. And then set the width as described above.

### System

N/A

**Comment by DylanDevelops** [comment]
I can implement this!

**Comment by bbsmooth** [comment]
Go for it. It's a minor change and if someone wants it reworded a little they can make a suggestion in the PR.

Yes, I am only referring to the second sentence. The first sentence should remain as is.

**Comment by DylanDevelops** [comment]
Perfect i'll add the change.
