### ISSUE TITLE
Can't advance to next challenge due to error message "Can't find variable: chai"

### ISSUE THREAD

**Issue by itsvango** [FreeCodeCamp/FreeCodeCamp#4718]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/537.86.2</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
<img width="1256" alt="screen shot 2015-11-25 at 3 06 05 pm" src="https://cloud.githubusercontent.com/assets/15681928/11408931/76cc36e0-938a-11e5-840f-a58cbc72535f.png">
I went through past waypoints that I have already cleared and encountered the same error. The code below is correct solution but I'm not sure why I can't get past. Also, there wasn't any chai variable anywhere in the code if you can see.
My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
  return val<=5;
});

// Only change code above this line.

(function() { return newArray; })();

```

**Comment by ltegman** [comment]
I am not able to repro this problem. We have had people report this issue when they're behind certain firewalls or on VPN connections, so if that applies to you I would advise changing that. Other possible troubleshooting options: switch to Chrome (at this time Chrome is the only officially supported browser) or disable any Safari extensions you might have installed.

Thanks and happy coding!
