### ISSUE TITLE
'Unexpected End Of Input' error on Waypoint: Delete Your jQuery Functions

### ISSUE THREAD

**Issue by vanillakernel** [FreeCodeCamp/FreeCodeCamp#4719]
When deleting the three jquery functions in the script section, an error appears if the document ready function is mangled.

This may indicate insufficient sanitizing of code in the text box or tests.
<img width="1475" alt="screen shot 2015-11-25 at 12 49 56 pm" src="https://cloud.githubusercontent.com/assets/13111622/11410200/6901ebb4-937a-11e5-9e8c-58ccd2fe064e.png">

[Challenge [Waypoint: Delete your jQuery Functions]](http://www.freecodecamp.com/challenges/waypoint-delete-your-jquery-functions)

*Note: code not included, as it had changed by the time I filed the bug. See attached screenshot for code.*

**Comment by ltegman** [comment]
Unless I'm missing something I don't see the issue with this. Incorrect code causes and error to show up in the sidebar output. That doesn't seem like a problem.

**Comment by BerkeleyTrue** [comment]
This is expected behavior. The JavaScript interpreter is returning an error and it's being displayed to the user.

Happy Coding!
