### ISSUE TITLE
Clarify instructions for Cat Photo App Step 1

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47197]
### Describe the Issue

Been seeing this more lately where people are changing the tag names to `CatPhotoApp` instead of the text. I'm tempted to believe it is because the explanation of where the text for the element is located is at the very bottom of the description, after the actual instructions, and perhaps people just aren't reading that far.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1

### Your code

Seeing more of this lately in the forums:

```
<html>
<body>
  <catphotoapp>HelloWorld</catphotoapp>
</body>
</html>
```

### Expected behavior

Move explanation about where text is located in element before instructions. My suggestion:

> HTML elements have opening tags like `<h1>` and closing tags like `</h1>`. The text for an element goes between its opening and closing tags.

> Find the `h1` element and change its text to:

> `CatPhotoApp`

Also, I think the intro for this course on the RWD main page should be updated to use the terminology "HTML elements" instead of "HTML tags" so that it is consistent with step 1.

> HTML elements give a webpage its structure. You can use HTML elements to add photos, buttons,  and other elements to your webpage.

> In this course, you'll learn the most common HTML elements by building your own cat photo app.

This makes a much better transition into the first step when we immediately introduce the first HTML element.

### System

N/A

**Comment by DylanDevelops** [comment]
Would you mind posting the link to the page that has this? 
> Also, I think the intro for this course on the RWD main page should be updated to use the terminology "HTML elements" instead of "HTML tags" so that it is consistent with step 1.

I've never had to edit the RWD main page so I'm not sure where to find that. Is it just in the same place where all the steps are for this project?

**Comment by bbsmooth** [comment]
@DylanDevelops I think that we should perhaps give some time for others to chime in here before opening a PR. I am not the ultimate authority on these things and this is a change to the main RWD page, so I think it needs a little more consideration.

**Comment by DylanDevelops** [comment]
> @DylanDevelops I think that we should perhaps give some time for others to chime in here before opening a PR. I am not the ultimate authority on these things and this is a change to the main RWD page, so I think it needs a little more consideration.

I see. Is the main RWD page just in the the Build a cat photo app folder that has all the steps. I'm not gonna make a PR, I'm just curious for future reference.

**Comment by hanswang123456** [comment]
I don't see much of a problem to be honest.  The instruction explicitly states "make sure that the text is between its opening and closing tags."

**Comment by hanswang123456** [comment]
A fix might be changing the last lines to "Give the document a heading by putting `CatPhotoApp` between the opening and closing h1 tags."

**Comment by hanswang123456** [comment]
I guess the issue would people not know what "text" is being referenced in this part---> "Find the h1 element and change its text to: CatPhotoApp Make sure that the text is between its opening and closing tags."

**Comment by bbsmooth** [comment]
Just to reiterate, my problem isn't that the instructions aren't telling the user what to do. My issue is with where they are placed, which is potentially causing them to miss it.

If we want to spell it out more by explicitly by telling the user to change the text between the `<h1>` and `</h1>` tags I'm fine with that as well. Either way, we have moved the last line of the instructions, which was my intent.

**Comment by hanswang123456** [comment]
Here's a draft of a pull request, with a bit of rephrasing to make the location of where to put `CatPhotoApp` a bit more clear.

**Comment by moT01** [comment]
I'm fine with the suggested instructional change. I would leave the intro (main) page, the phrasing on those pages is somewhat deliberate for SEO purposes.

**Comment by hanswang123456** [comment]
That sounds good, I'll reopen a pull request that updates the last few lines.
