### ISSUE TITLE
Dead link in demographic data analyzer

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47200]
### Describe the Issue

There is dead link in [https://www.freecodecamp.org/news/learn-python-video-course/](https://www.freecodecamp.org/news/learn-python-video-course/) the file below
 
https://github.com/freeCodeCamp/freeCodeCamp/blob/1cd621fa673199b2fedf381fff2e9bd3a2797aa3/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/demographic-data-analyzer.md?plain=1#L16

Do we swap the link or delete it all together? or is it possible to get the link back?

Someone in Crowdin recommended https://www.freecodecamp.org/news/learn-python-basics-in-depth-video-course/ but that beginner video for project, I don't think it's fitting

### Affected Page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/demographic-data-analyzer

**Comment by mmatsumoto1026** [comment]
Hello, @Sboonny.

I found that all five projects in "Data Analysis with Python Projects" contain the link (https://www.freecodecamp.org/news/learn-python-video-course/) and as you mentioned, they are all dead link now.

But I also noted that only in "Demographic Data Analyzer" project, there is "(10 hours)" text with the link. It may be a hint for correct video course.

In freeCodeCamp YouTube channel, I searched Python video course that length is about 10 hours. And [Data Analysis with Python Course - Numpy, Pandas, Data Visualization](https://www.youtube.com/watch?v=GPVsHOlRBBI&t=26417s) was found.

The video course covers basics of Python, Numpy, Pandas, Matplotlib, and Seaborn.

I confirmed the contents of all five projects in the curriculum and I thought These Python libraries will fit them.

How about consider changing the link to this video's URL?

Thanks.
