### ISSUE TITLE
Usability on Waypoint: Use Conditional Logic with If and Else Statements

### ISSUE THREAD

**Issue by mirped** [FreeCodeCamp/FreeCodeCamp#4722]
I would suggest changing the example on the left side since it can be confusing for people not familiar with conditional logic.
The example listed on the site shows (I added my suggestion as a comment on the code)

if (1 === 2) {  

  return true;
// 1 is NOT equal to 2 so the condition evaluates to FALSE. So to return TRUE can be confusing in my opinion
} else {

  return false;

}

**Comment by ltegman** [comment]
I do think `1 === 2` is perhaps not the best example code we could be using since it could lead to the confusion mentioned and is just longhand for `false`. Perhaps having the example code say something like `if (x === 1)` or `if (x === y)` makes more sense.
