### ISSUE TITLE
Implement Tabs component

### ISSUE THREAD

**Issue by masterX89** [freeCodeCamp/freeCodeCamp#47247]
## where to use

- ~~`client/src/components/Donation/duration-amount-options.tsx`~~(for a/b test)

- `client/src/templates/Challenges/classic/mobile-layout.tsx`

![image](https://user-images.githubusercontent.com/8510146/183844109-5b8c80d3-e731-4cee-93fc-21cb3f77ff20.png)

  ```tsx
  <Tabs
      activeKey={currentTab}
      defaultActiveKey={currentTab}
      id='mobile-layout'
      onSelect={this.switchTab}
      >
  	{/* omit something */}
      <TabPane
          eventKey={Tab.Editor}
          title={i18next.t('learn.editor-tabs.code')}
          {...editorTabPaneProps}
          >
          {/* omit something */}
          {editor}
      </TabPane>
      <TabPane
          eventKey={Tab.Console}
          title={i18next.t('learn.editor-tabs.tests')}
          {...editorTabPaneProps}
          >
          {testOutput}
      </TabPane>
      {/* omit something */}
  </Tabs>
  ```

### Tabs

| **Name**    | **Type**            | **Default** | **Description**                                    |
| ----------- | ------------------- | ----------- | -------------------------------------------------- |
| `activeKey` | `string` | `number` |             | Mark the Tab with a matching `eventKey` as active. |
| `animation` | `boolean`           | true        | Sets if `Fade` animation strategy                  |
| id          | `string`            |             |                                                    |
| onSelect    | `function`          |             | Callback fired when a Tab is selected              |

### Tab

| **Name**   | **Type**  | **Default** | **Description**        |
| ---------- | --------- | ----------- | ---------------------- |
| `disabled` | `boolean` |             | Use `false` to disable |
| `title`    | `node`    |             |                        |

### TabPane

| **Name**        | **Type**            | **Default** | **Description**                                              |
| --------------- | ------------------- | ----------- | ------------------------------------------------------------ |
| `eventKey`      | `string` | `number` |             | Uniquely identify the `<TabPane>` among its siblings.        |
| `title`         |                     |             |                                                              |
| `mountOnEnter`  |                     |             | Wait until the first "enter" transition to mount the tab (add it to the DOM) |
| `unmountOnExit` |                     |             | Unmount the tab (remove it from the DOM) when it is no longer visible |

## Screenshots

| Status     | Light theme                                                  | Dark theme                                                   |
| ---------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| selected   | ![image](https://user-images.githubusercontent.com/8510146/183844194-3565a817-7916-484e-95d9-757e5587229d.png) | ![image](https://user-images.githubusercontent.com/8510146/183844243-b40f225f-eff2-466b-bc63-3638bab7f3d0.png) |
| unselected | ![image](https://user-images.githubusercontent.com/8510146/183844314-25a62022-5d34-4987-b0cc-baaa529f3be6.png) | ![image](https://user-images.githubusercontent.com/8510146/183844340-8c52776f-6847-4512-aa96-e362a0a06a94.png) |

### Tabs

- Themes:
  - Light
  - Dark

### Tab

- Font-family: `Roboto Mono, monospace`
- States:
  - disabled
  - selected

### TabPane

- display:
  - block
  - hidden

### Tab

- border: `1px`
- border-color: `transparent`
- border-bottom-color: `#ddd`
- margin-right: `2px`
- padding: `5px 10px`
- font-size: `0.8em`
- font-color: `--foreground-secondary: var(--gray05)`

| Status     | Spacing and typography                                       |
| ---------- | ------------------------------------------------------------ |
| selected   | `border-top-color: #ddd`<br>`border-right-color: #ddd`<br>`border-left-color: #ddd`<br>`background-color: --background-quaternary` |
| unselected | `border-bottom-color: #ddd`                                  |

### TabPane

| Status     | Spacing and typography |
| ---------- | ---------------------- |
| selected   | `display: block`       |
| unselected | `display: none`        |

## rough delivery plan

- [ ] basic fCC Tailwind style Uncontrolled Tabs - #47313
- [ ] add `disable` prop
- [ ] add Fade `animation`, and could set `false`
- [ ] basic controlled Tabs, add `onSelect`
- [ ] `mountOnEnter` and `unmountOnExit`
- [ ] implement TabPane (this part of the details still need to continue to discuss)

**Comment by ahmadabdolsaheb** [comment]
@masterX89, thanks for researching the `Tabs` component and opening this detailed issue. Solid work here.

Here are a few nitpicks:
- Client/src/components/Donation/duration-amount-options.tsx belongs to a feature that we might a/b test in a couple of months so it does not need checking. You could re-adjust the specifications based on the `mobile-layout.tsx` only. 
- `bsStyle` could be removed since it is not used in `mobile-layout.tsx`
-  If a props is not used in codebase such as `mountOnEnter` in the `Tabs` component, it should be removed. 
-  The `Tab` component could be removed.
-  **Spacing and typography** and **Current specs** could be made more specific to each component `Tabs` and `Tab

**Comment by masterX89** [comment]
@ahmadabdolsaheb Thanks for the suggestions, I modified the content of the issue according to the suggestions and tried to implement basic `Tabs` component. If there is anything that can be improved please let me know.
Thanks in advance :)

**Comment by Rahul-Palamarthi** [comment]
I would like to work on this issue

**Comment by ahmaxed** [comment]
Thanks for your interest, @Rahul-Palamarthi. There is a pull request associated with this issue. If you enjoy creating components, I recommend finding an available component from this issue and working on it.
https://github.com/freeCodeCamp/freeCodeCamp/issues/44668
