### ISSUE TITLE
 Learn Typography by Building a Nutrition Label - Step 28 

### ISSUE THREAD

**Issue by Kingkiosk** [freeCodeCamp/freeCodeCamp#47255]
### Describe the Issue

The task is:

**You may notice there is still a small border at the bottom of your .lg element. To reset this, give your .lg, .md selector a border property set to 0.**

Issue: There isn't anywhere a class="md" in whole code. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-28

### Your code

/* file: index.html */
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Nutrition Label</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
  <link href="./styles.css" rel="stylesheet">
</head>
<body>
  <div class="label">
    <header>
      <h1 class="bold">Nutrition Facts</h1>
      <div class="divider"></div>
      <p>8 servings per container</p>
      <p class="bold">Serving size <span class="right">2/3 cup (55g)</span></p>
    </header>
    <div class="divider lg"></div>
  </div>
</body>
</html>

/* file: styles.css */
* {
box-sizing: border-box;
}

html {
font-size: 16px;
}

body {
font-family: 'Open Sans', sans-serif;
}

.label {
border: 2px solid black;
width: 270px;
margin: 20px auto;
padding: 0 7px;
}

header h1 {
text-align: center;
margin: -4px 0;
letter-spacing: 0.15px
}

p {
margin: 0;
}

.divider {
border-bottom: 1px solid #888989;
margin: 2px 0;
}

.bold {
font-weight: 800;
}

.right {
float: right;
}

.lg {
height: 10px;
}

.lg, .md {
background-color: black;
border: 0;

}

### Expected behavior

Please remove .md from the task because it is not necessary. 

### System

- Device: PC
- OS: Windows 10
- Browser: Firefox
- Version: 103.0.2 (64-Bit)

**Comment by naomi-lgbt** [comment]
The class is later used in [step 37](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-37). We could probably add a note explaining this.

**Comment by hanswang123456** [comment]
I will open a PR to resolve
