### ISSUE TITLE
Learn CSS Colors by Building a Set of Colored Markers - Step 49

### ISSUE THREAD

**Issue by Tito-Osemobor** [freeCodeCamp/freeCodeCamp#47256]
### Describe the Issue

I believe the code I entered for this particular step is correct but is being parsed as wrong. Maybe I didn't understand what the step entails but I have gone over it several times and input different variations of what I think the correct syntax should be with no success. I have come to the conclusion that it is a bug :)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-49

### Your code

```
.red {
  background: rgb(255, 0, 0);
}
```

### Expected behavior

In the .red CSS rule, change the background-color property to background.

### Screenshots

![Screen Shot 2022-08-10 at 18 24 06](https://user-images.githubusercontent.com/91590992/184030989-4edbfa49-eb91-4617-bf4f-e492336f80ed.png)

### System

- Device: [MacBook Air]
- OS: [macOS Monterey]
- Browser: [Safari]
- Version: [15.5]

### Additional context

The same problem occurs in step 60 and step 66
![Screen Shot 2022-08-10 at 18 28 19](https://user-images.githubusercontent.com/91590992/184031593-c3835728-5f24-4019-9d41-4833deb23c33.png)
![Screen Shot 2022-08-10 at 18 27 29](https://user-images.githubusercontent.com/91590992/184031594-e7d9605d-d14e-44a2-8156-505f66891675.png)

**Comment by DylanDevelops** [comment]
I'll take a look at the code that checks your code.

**Comment by DylanDevelops** [comment]
This is the code that checks if your code is right:

```js
assert.include(new __helpers.CSSHelp(document).getStyle('.red').cssText, 'background: rgb(255, 0, 0)');
```

I'm not seeing anything wrong with it though. The `background: rgb(255, 0, 0)` looks exactly the same as yours to me so I'm not sure what the issue is. In step 50 the code looks like this:

`.red {
  background: rgb(255, 0, 0);
}`

Hopefully, someone can come along and help you out with this issue!

**Comment by DylanDevelops** [comment]
Thanks @bbsmooth
