### ISSUE TITLE
[Forum] Links to headings a hidden behind nav

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#47257]
### Describe the Issue

When sharing a link to a heading within a forum post, it takes you to that heading but scrolls up too far. The heading and some text is hidden behind the nav.

### Steps to Reproduce

Open this link:
https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231#your-container-loaded-but-the-terminal-is-not-visible-8

The `Your container loaded, but the terminal is not visible` heading is hidden behind the nav

### Expected behavior

It not to be hidden.

**Comment by saadbitcoin** [comment]
May your days be happy and flowers == I would like someone or a group to
help me to finish a special site for bitcoin mining on Quekza and the
Central Therapy Unit = who has feelings of help My mail is available to
call = Wishing you happy days

**Comment by DylanDevelops** [comment]
I'm seeing this. What exactly is the issue? If the error isn't showing up in this picture it might be an issue on your side rather than a global problem.
<img width="1480" alt="Screen Shot 2022-08-11 at 12 46 55 AM" src="https://user-images.githubusercontent.com/48571264/184078372-6c5a8ea6-696d-423b-bae8-c2034545f1e9.png">

**Comment by naomi-lgbt** [comment]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/63889819/184422915-32f357b4-746e-47e3-a0aa-9bc763638dc2.png">

I'm able to reproduce this, yeah.

**Comment by ahmadabdolsaheb** [comment]
If there are any takers, I would check to see if --header-offset variable can be reset. If not, I would add the following style and check to see if it looks good on mobile ( reload after toggling device toolbar from the elements pane on developer tools )
```
.topic-post.sticky-avatar .topic-avatar {
    top: calc($--global-nav-height - 0.25em);
}
```

**Comment by usmanabdurrehman** [comment]
I was looking to contribute to something. I will take this @ahmadabdolsaheb

**Comment by ieahleen** [comment]
@MahendraBishnoi29 issues are not assigned, please make sure to read our contributing docs if you want to contribute!

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb I do not think you are talking about the same issue (with your suggested fix).

**Comment by MahendraBishnoi29** [comment]
@ShaunSHamilton can u suggest me the solution?

**Comment by ahmadabdolsaheb** [comment]
Thanks for letting me know, Shaun. I thing there are a few issues being discussed here:

1) Title not being visible Dylan's screenshot
2) Profile image not being visible  Naomi 's screenshot

First issue is could be resolved by changing the theme from `Staff - Debug` to any other theme. We hid the title and tags from the nav on our custom theme to free space for our lego and curriculum nav item.

The proposed solution would resolve the second. 

Just to clarify, @moT01, the issue you are referring to is one of the above right?

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb No, both Naomi and Dylan mention the same issue: When clicking on an anchor, the anchor element is hidden underneath the navbar.

**Comment by ahmadabdolsaheb** [comment]
Thanks for the explanation. I see it now, this should do the trick.

**Comment by moT01** [comment]
I don't think we're talking about quite the same issue @ahmadabdolsaheb.

I cannot (or do not know how to) reproduce the issue in @DylanDevelops's screen shot. The navbar is always at the top for me with the fCC logo and the rest of the universal nav. I never see a post title or anything like that in the navbar.

The issue I was referring to can be seen in @naomi-lgbt's screen shot. When you open the link I shared, the heading for it is hidden. It's supposed to take you to the `#your-container-loaded-but-the-terminal-is-not-visible-8` heading, and it does - but it's hidden behind the nav, as if it's just scrolled up a little too much. Now that I double check, there is the second issue that you mentioned - the profile icon is hidden as well.

**Comment by trenz999** [comment]
I try the link heading but its backend? can you be more explainary

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by IvanoskiHarmonia** [comment]
The issue with the anchor jumps I think is that they might be pointing to multiple directions so it has no idea where to jump and it jumps to the last pointed section, I tried to fix it but nothing works really...

**Comment by ahmadabdolsaheb** [comment]
@IvanoskiHarmonia, thank you for digging into this issue. The latest merged pr addresses issue by styling the elements with .anchor class. As a result I am closing this issue.
