### ISSUE TITLE
Learn-css-colors-by-building-a-set-of-colored-markers - Step 5 

### ISSUE THREAD

**Issue by Srisuma13** [freeCodeCamp/freeCodeCamp#47266]
### Describe the Issue

For more clarity, can we specify to the user to add a **_NEW_** `meta` element in Step 5 as one already exists (added in step 4)?

Also, explain the reason why we are adding a new `meta` when some might think of adding attributes to the existing one.

- **Exactly one of the `name`, `http-equiv`, and `charset` attributes must be specified for a single meta element.**

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-5

### Your code

Nest a self-closing meta element within the head. Give it a name attribute set to viewport and a content attribute set to width=device-width, initial-scale=1.0.

```
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0"/>
```

### Expected behavior

Nest another self-closing meta element within the head. Give it a name attribute set to viewport and a content attribute set to width=device-width, initial-scale=1.0.

```
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by moT01** [comment]
I would change the description to this: 
> Add another self-closing `meta` element within the `head`. Give it a `name` attribute set to `viewport` and a `content` attribute set to `width=device-width, initial-scale=1.0`.

I wouldn't add the extra info about the meta tag.

**Comment by jeremylt** [comment]
+1 to the suggested wording change from @moT01
