### ISSUE TITLE
Stuck in a step in Learn Bash Scripting by Building Five Programs, database curriculum

### ISSUE THREAD

**Issue by JustLolo** [freeCodeCamp/freeCodeCamp#47273]
### Describe the Issue

I think that it's enough info with the pictures.
I even restart the whole thing.
Tested on both codeally and FCC.

![image](https://user-images.githubusercontent.com/103621114/184452008-5e4cbb85-321a-477d-9fab-afd2dce54a24.png)
![image](https://user-images.githubusercontent.com/103621114/184452030-efc53c51-dfab-4c27-b130-654291219fe9.png)
![image](https://user-images.githubusercontent.com/103621114/184452062-66c04148-0946-4af4-b49d-eb6447180d70.png)

### Affected Page

Learn Bash Scripting by Building Five Programs

### Your code

```

# Program that counts down to zero from a given argument

echo -e "\n~~ Countdown Timer ~~\n"

if [[ $1 -gt 0 ]]
then
  : '
  for (( i = $1; i >= 0; i-- ))
  do
    echo $i
    sleep 1
  done
  '

  I=$1

  while [[ $I -ge 0 ]]
  do
    echo $I
    (( I-- ))
    sleep 1
  done
else
  echo Include a positive integer as the first argument.
fi

```

### Expected behavior

should be able to go to the next step

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jeremylt** [comment]
This looks a request for help. Have you tried asking on the forum?

**Comment by moT01** [comment]
There is an issue loading containers right now @JustLolo, so you probably won't be able to try this. We are looking into it.

[Resetting the step](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231#issues-within-a-course-9) should resolve this for you after we fix that issue. Please post issues on the forum first, where we can decide if it's an issue that needs fixing or if it's just something we can help you with. Thanks.
