### ISSUE TITLE
font size task for p element fails

### ISSUE THREAD

**Issue by srinivastin** [FreeCodeCamp/FreeCodeCamp#4727]
Challenge [Waypoint: Change the Font Size of an Element](http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20%20color%3Ared%3B%0A%20%20%20%20p%20%7B%0A%20%20%20%20%20%0A%20%20%20%20%20%20font-size%3A16px%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
     color:red;
    p {
     
      font-size:16px;
    }
  }
</style>
<h2 class="red-text">CatPhotoApp</h2>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment]
The code editor is alerting you to the fact that your CSS is incorrect.
![waypoint__change_the_font_size_of_an_element___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/11417584/1fccedce-93cd-11e5-820c-4a014c150493.png)
You didn't close your `.red-text` rule.

In the future please consult our [Help Chat](https://gitter.im/FreeCodeCamp/Help) for challenge help, rather than filing a bug.

Thanks and happy coding!

**Comment by srinivastin** [comment]
Thanks i got it
