### ISSUE TITLE
Project *TILE*?

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#47271]
### Describe the Issue

Do we mean this step to check for `project-tile`? `project-title` makes more sense to me.

https://github.com/freeCodeCamp/freeCodeCamp/blob/92270f7ef63183c25fd34d58fe1a3d50893095ea/curriculum/challenges/english/14-responsive-web-design-22/build-a-personal-portfolio-webpage-project/build-a-personal-portfolio-webpage.md?plain=1#L72

Also, the text of the hint doesn't make it clear that this must be inside of the element with the `projects` id, at least to me.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-personal-portfolio-webpage-project/build-a-personal-portfolio-webpage

**Comment by ShaunSHamilton** [comment]
`tile` is a very common term in HTML/CSS naming: https://www.digitalocean.com/community/tutorials/how-to-build-a-tiled-layout-with-css-section-3

It is a `tile`. It is not a `title`. Also, it is a certification project. So, we are very unlikely to change that test/user-story

**Comment by jeremylt** [comment]
Ah, the tile vs title makes more sense now.
