### ISSUE TITLE
Build a boilerplate page does not load

### ISSUE THREAD

**Issue by oriooctopus** [freeCodeCamp/freeCodeCamp#47285]
### Describe the Issue

Both my wife and I were testing out the "Build a boilerplate" tutorial of the new Relational database model. We did about 5-10 lessons. The next day we went back to do more of it and both of us experienced the same error, on different computers, and on different accounts. This was about a week ago and the issue still exist

I have tried disabling all chrome extensions and still get the same issue. 

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate

### Your code

can't even load the page		

### Expected behavior

that the page loads

### Screenshots

<img width="1792" alt="Screen Shot 2022-08-13 at 12 19 17 PM" src="https://user-images.githubusercontent.com/20331238/184500437-5cfb6e99-0422-48ef-ab6d-f052bf029d51.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by hanswang123456** [comment]
I was able to load the page.
![image](https://user-images.githubusercontent.com/50556568/184539876-5b527710-9554-4286-b952-585440ed4f8b.png)

**Comment by hanswang123456** [comment]
Once you hit "Start the Course" it give you a prompt: 
![image](https://user-images.githubusercontent.com/50556568/184539902-d7ddfdfe-8799-49cc-bca1-effd85d99018.png)

**Comment by rudy0628** [comment]
I have the same issue with beta page, it stuck on build virtual server, i have seen the trouble shooting on freecodecamp official docuemnt, i still got stuck when i refresh the page.
Document: `https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231`
![image](https://user-images.githubusercontent.com/53780265/184567330-a99d50c6-25d0-4e99-9ea2-c78cf05844f5.png)

**Comment by moT01** [comment]
Thanks for reporting. There is an issue loading containers right now, and you will not be able to load a project. We are looking into it - thanks for your patience.

**Comment by moT01** [comment]
This should be resolved @oriooctopus @hanswang123456 @rudy0628 - let us know if you are still having issues.
