### ISSUE TITLE
Take home Project - Show National Contiguity with a Force Directed Graph

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#47289]
### Describe the Issue

I am having trouble understanding the take-home project and nothing loads on the sample page. All I see is a big black box with a blue background. I wanted to see how much I still need to learn by picking a random project and starting to build it to see my weaknesses. 

 https://codepen.io/freeCodeCamp/full/xVopBo 

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/show-national-contiguity-with-a-force-directed-graph

### Your code

```

```

### Expected behavior

I expected the page to have something in the box as a sample instead of an black box. 

### Screenshots

![Screenshot of the challenge website](https://user-images.githubusercontent.com/9373245/184552102-28717344-fcb9-403d-b40c-4760df3e595f.PNG)

### System

- Device: Desktop Computer
- OS: Windows 10 
- Browser: FireFox
- Version: latest

### Additional context

More informational in general would be lovely for this page.

**Comment by moT01** [comment]
I didn't look into why this one isn't working, it may be a simple fix - which would probably be preferable. But, I completed this project and we can use that for now if we want: https://codepen.io/moT01/full/EWmYPq - it could probably use a little update, but it's better than a broken project.

**Comment by naomi-lgbt** [comment]
Looks like the dataset this example relies on is no longer available.

The request triggers a CORS error:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/63889819/184651430-3dc1b5f8-89ec-44db-b57c-61c915203b9e.png">

And visiting the resource in my browser throws a 403:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/63889819/184651695-85be0e19-41de-4413-ad37-fa3d4c6b8a8e.png">

---

Fixing the example project might be a bit trickier - throwing the data link that @moT01 uses into the example's request call fixes the graph, but the flags are loaded through a CSS file from the same domain.

It would probably be easier to use Tom's example instead.

**Comment by moT01** [comment]
Lets do that then. We just need to replace the link in [that challenge file.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/take-home-projects/show-national-contiguity-with-a-force-directed-graph.md)

**Comment by mohitchakraverty** [comment]
I would like to work on it.

**Comment by mohitchakraverty** [comment]
I would like to work on it.
