### ISSUE TITLE
Wrong test in Page Series Visualiser Final Project

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47294]
### Describe the Issue

It says that plot 1 should have an x label of Month, but it's the second plot that is monthly. It should say that plot 2 should have that xlabel.

### Affected Page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/page-view-time-series-visualizer

### Your code

```
def draw_box_plot():
    # Prepare data for box plots (this part is done!)
    df_box = df.copy()
    df_box.reset_index(inplace=True)
    df_box['year'] = [d.year for d in df_box.date]
    df_box['month'] = [d.strftime('%b') for d in df_box.date]

    # Draw box plots (using Seaborn)

    fig, axes = plt.subplots(1, 2)
    sns.boxplot(ax=axes[0], x='year', y='value', data=df_box)
    sns.boxplot(ax=axes[1], x='month', y='value', data=df_box)
   

    
    axes[0].set_title('Year-wise Box Plot (Trend)')
    
    axes[0].set_xlabel('Year')
    axes[0].set_ylabel('Page Views')

    axes[1].
    
    axes[1].set_title('Month-wise Box Plot (Seasonality)')
   
    




    # Save image and return fig (don't change this part)
    fig.savefig('box_plot.png')
    return fig
```

### Expected behavior

It should say that plot 2 should have an xlabel of Years

> Expected box plot 2 xlabel to be 'Month'

It's testing correctly, so it should be an issue only with the assert message

### Screenshots

![image](https://user-images.githubusercontent.com/26656284/184625223-ca1b2b01-b849-494f-92f8-2bd03f746673.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by mmatsumoto1026** [comment]
Hello,

It seems that same thing is for the "test_box_plot_titles".

**Comment by ieahleen** [comment]
I am opening this for contribution.
The PR has to be done on the boilerplate: https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer
