### ISSUE TITLE
zipline 5 calculator example project % button doesn't work?

### ISSUE THREAD

**Issue by hughforsyth** [FreeCodeCamp/FreeCodeCamp#4729]
As far as I can tell the % button in http://codepen.io/GeoffStorbeck/full/zxgaqw does not do anything which I'm guessing is not intentional (although it does make it easier to reverse engineer!).

It seems like the real world is not in agreement as to what a percentage button should do but I'm guessing it's should do something on the example. http://www.percentagecalculator.co/Percent-Button.html

I'll pick one and I'm sure most people will too but it's probably worth fixing, if not high priority.
Thanks.

**Comment by dutchsteven** [comment]
I also noticed this.
personally I simply removed it and created a 'backspace' button.
http://codepen.io/dutchsteven/pen/LpaQLM

**Comment by SaintPeter** [comment]
@storbeck Can you please fix this?

**Comment by bugron** [comment]
This is still an issue. Closing this issue as I'm not sure that @storbeck will have much time to fix it. @hughforsyth thanks for posting, though.
