### ISSUE TITLE
Please activate the german language for the freecodecamp

### ISSUE THREAD

**Issue by stephanduesterhoeft** [freeCodeCamp/freeCodeCamp#47307]
The German-speaking community is making great progress.

82 percent of the German-language curriculum has already been translated. 4 certificates (including the first 3) are now fully translated and approved.

I request to activate german language.

**Comment by mseibert** [comment]
+1 

This would help us teaching kids a lot!

**Comment by Sembauke** [comment]
@naomi-lgbt

**Comment by ieahleen** [comment]
![image](https://user-images.githubusercontent.com/26656284/185147299-a29fb953-5549-4887-becf-7600257481c2.png)

The proofred certifications are:
Legacy Responsive Web Design
JavaScript Data Structures and Algorithms
Front End Development

And also Learn UI is translated and approved, so this is ready to go!
