### ISSUE TITLE
Button not clicking to check code and progress to the next challenge when you restart the challenge after initially solving the challenge.

### ISSUE THREAD

**Issue by favour-olumese** [freeCodeCamp/freeCodeCamp#47302]
### Describe the Issue

In "Learning HTML by Building a Cat Photo App," once a challenge has been completed and the "Restart Step" button is clicked, the "Submit and go to the challenge" button is not reverted to "Check Your Code" and users are unable submit their challenge again or progress to the next challenge.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-16

### Steps to Reproduce

1. Solve the problem
2. Click on "Check Your Code"
3. Click on "Restart Step"
4. Solve problem again and try resubmitting

### Expected behavior

You would be unable to submit a solved challenge after clicking the "Restart Step" button.

### Screenshots

https://user-images.githubusercontent.com/70489864/184887903-bc32ea95-e23d-4fac-b542-113f242c70cf.mp4

### System

- Device: Laptop
- OS: Windows 10, Ubuntu 20.04
- Browser: Microsoft Edge

**Comment by moT01** [comment]
I can reproduce this.

**Comment by ieahleen** [comment]
Possible solutions:
- hide reset button after the tests succed
- Or bring back the Check your code button when step is reset

**Comment by moT01** [comment]
I would be fine with either of those solutions. I'm really not sure which one I like better - what do you like @ieahleen @favour-olumese?

Side note: for me, clicking the button after resetting doesn't work, but the hotkeys do.

**Comment by favour-olumese** [comment]
> I would be fine with either of those solutions. I'm really not sure which one I like better - what do you like @ieahleen @favour-olumese?
> 
> Side note: for me, clicking the button after resetting doesn't work, but the hotkeys do.

@moT01 I believe bringing back the "Check Your Code" button after the challenge has been reset would be great. I noticed this error while explaining this challenge to a beginner and after solving it, I wanted him to give it a try also.

**Comment by hanswang123456** [comment]
> @moT01 I believe bringing back the "Check Your Code" button after the challenge has been reset would be great. I noticed this error while explaining this challenge to a beginner and after solving it, I wanted him to give it a try also.

This does make more sense, having the ability to reset challenges is good for first time learners.

**Comment by moT01** [comment]
Lets try that then.

**Comment by hanswang123456** [comment]
It seems like we need to change
![image](https://user-images.githubusercontent.com/50556568/185444084-9f6ffc5b-1a7b-4606-abef-ce1ed1b3c499.png)

**Comment by hanswang123456** [comment]
![image](https://user-images.githubusercontent.com/50556568/185449276-297931c0-0d7b-4f76-bd7c-8c2a248b5bd2.png)

**Comment by mmatsumoto1026** [comment]
I agree with @favour-olumese's idea, so I would like to participate in solving this issue.

The behavior of test button and submit button in challenge editor seems to be controled by `challengeHasBeenCompleted` state and `challengeIsCompleted` prop of `LowerJaw` component in `client/src/templates/Challenges/classic/lower-jaw.tsx`, so the issue may be solved by adding some processes after `challengeIsCompleted` is set to false.

**Comment by ieahleen** [comment]
Feel free to open a PR if you can solve this! The challenge has the help wanted tag, so it's up for grabs for anyone that wants to contribute.
