### ISSUE TITLE
[ Building FreeCodeCamp ] : Build issues while Installing and running FCC locally.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#4730]
Hi,

I have forked the repo, and I am trying to follow the getting started guide, to install and run FCC locally.

The `npm install` is failing with below log:
```
npm ERR! not a package /tmp/npm-1254-mMQP9bL4/github.com/FreeCodeCamp/react-router-bootstrap.git                                   
npm ERR! not a package /tmp/npm-1254-mMQP9bL4/github.com/berkeleytrue/store.js.git                                                 
npm WARN deprecated gulp-webpack@1.5.0: Renamed to https://www.npmjs.com/package/webpack-stream                                    
npm ERR! Error: ENOENT, open '/tmp/npm-1254-mMQP9bL4/github.com/FreeCodeCamp/react-router-bootstrap.git-unpack/package.json'  
```
That I could fix by referring [#2976](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2976), just had to change :

```
"react-router-bootstrap": "https://github.com/FreeCodeCamp/react-router-bootstrap.git#freecodecamp",
to
"react-router-bootstrap": "FreeCodeCamp/react-router-bootstrap.git#freecodecamp",
```
and similarly
```
"store": "https://github.com/berkeleytrue/store.js.git#feature/noop-server",
```
to
```
"store": "berkeleytrue/store.js.git#feature/noop-server",
```

but that still leaves my with the below error:
```
npm ERR! notarget No compatible version found: store@'berkeleytrue/store.js.git#feature/noop-server'                               
npm ERR! notarget Valid install targets:                                                                                           
npm ERR! notarget ["1.1.0","1.1.1","1.3.1","1.3.2","1.3.3","1.3.6","1.3.8","1.3.10","1.3.11","1.3.12","1.3.14","1.3.16","1.3.17"]  
npm ERR! notarget                                                                                                                  
```

So I changed the target to latest:
```
"store": "berkeleytrue/store.js.git#v1.3.17",
```

This leads to successful build, with just one error:
```
npm ERR! fetch failed https://registry.npmjs.org/lodash._baseindexof/-/lodash._baseindexof-3.1.0.tgz 
```
I am not sure what that is sadly. 

If what I tinkered is correct? I think we should fix the packaging. Also it would be great if we have a wiki page on building and contributing? Maybe just a set of F.A.Qs?

Thanks,
Mrugesh

----
P.S : Will update on the running FCC later as I progress on the installation, (working on a dead slow network).

**Comment by raisedadead** [comment]
Sorry I forgot to mention my build machine config : 

Ubuntu : 12.04 LTS ( codio.com vm box)
Node      : 4.2.2
MongoDb : 3.0.0

**Comment by ltegman** [comment]
Hmmm. I think this may be down to your network connection, because I've installed FCC onto a bunch of different dev environments over the past week or two (Mac/Windows/Ubuntu) with both npm 2 and npm 3 and haven't run into any of these issues.

**Comment by raisedadead** [comment]
Yup, it could be. Will try on a couple physical machines instead of the Codio VM and get back on this. 
Thanks!

**Comment by raisedadead** [comment]
Hi, 

Sadly I haven't yet got access to physical machines, so Codio.com VM Boxes (Cloud IDE) are my option atleast for now. But the GOOD News is that the build, and install goes good now.

I am no longer getting those npm errors.

But, I have run into another config trouble, the thing is localhost or 127.0.0.1 is not allowed by Codio VMs, so they recommend to change all those IP references in code to 0.0.0.0.

What this does is : It resolves to the domain name for the VM, something like ``username.codio.io``

Which means if the Node.js app was supposed to be accessible at ``http://localhost:3000`` can now be accessed at  ``http://username.codio.io:3000 `` and so on.

I tried a find and replace, in the below files:
    gulpfile.js                                                                                              
    server/config.development.js                                                                             
    modified:   server/config.json               

for the necessary change, but nothing works!

Now, I agree that this is not an issue with the FCC repo itself, hence I am closing this issue. But it would be great if anyone could point me to any other config that I might have missed to get this running.

Hahaha, I was so close.

Cheers & thanks,
raisedadead.
