### ISSUE TITLE
Template for forum posts in non english languages don't have correct subforum (maybe?)

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47309]
Lots of the Spanish and Portuguese topics end in General.
Maybe they don't have the correct subforums set.
We would want to double check there, and in case fix it.

**Comment by moT01** [comment]
I don't see any of these posts, I presume you moved them to their correct category. Do you know of any specific ones that ended up in the wrong place?

I clicked the create forum post button on a few steps and it gave me a forum template in the correct category. I wonder if these campers are manually going to the forum and creating posts. If that's the case, I'm not sure what we could do. Potentially show the ask for help button sooner.

**Comment by ieahleen** [comment]
@moT01 for example: https://forum.freecodecamp.org/t/expressoes-regulares-encontrar-padroes-ao-inicio-da-string/543976

It should have gone to `portugues/javascript-pt`
So I guess this could be the source of the issue, the subforum doesn't match in the file:
https://github.com/freeCodeCamp/freeCodeCamp/blob/3a0f3a7253aad8d7682bde864d31b05df47bc4ad/client/i18n/locales/portuguese/links.json#L27

**Comment by moT01** [comment]
Yes, I can reproduce this by going to https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/regular-expressions/match-beginning-string-patterns and clicking the create forum post button. It also happens in a new RWD challenge I tried. So presumably, it happens with all the challenges in this language.

I copied the URL that opens when you click that button - everything looks right:
https://forum.freecodecamp.org/new-topic?category=Portugues%2FHTML-CSS
https://forum.freecodecamp.org/new-topic?category=Espanol%2FHTML-CSS

^ Espanol works, Portugues doesn't. 

I didn't try many in Espanol, but I didn't see any that didn't work. Seems like it might only be Portugues.

That file looks correct, as well @ieahleen - so I'm not quite sure why it's not working.

**Comment by ieahleen** [comment]
Portuguese doesn't work because of how the subforums are named
it should be https://forum.freecodecamp.org/new-topic?category=Portugues%2FHTML-CSS-pt
Because the subforum link is https://forum.freecodecamp.org/c/portugues/html-css-pt/546

**Comment by moT01** [comment]
I see. Do we want to just change the file you shared then or change the names on the forum? None of the other languages follow that convention.

**Comment by ieahleen** [comment]
I honestly have no idea what's best. Changing the subforums would mean we don't need to wait for deployment for it to take effect

**Comment by naomi-lgbt** [comment]
I'm in favour of changing the subforum slug - Discourse uses numeric IDs to track everything, so this shouldn't break any links. This will make things consistent with the other languages, though.

**Comment by naomi-lgbt** [comment]
The Portuguese slugs have been updated on the forum.
