### ISSUE TITLE
challenge-editor step tools off by one error

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47328]
The tool "Insert step" says to write the nth step after which the new step will be added.
![image](https://user-images.githubusercontent.com/26656284/185616830-c473f498-f54b-42e2-aef0-8d0683b68e77.png)

But if I write 16, it creates a new step 16, not 17.
If I want a new step after 16, I have to write 17.

**Comment by hanswang123456** [comment]
![image](https://user-images.githubusercontent.com/50556568/185630090-247bb1bb-069e-43a7-b83c-a459cd1310b4.png)
It seems like line 45 is incorrect where the indexing should be `[stepNum-1][0]`?

**Comment by ojeytonwilliams** [comment]
I think we just need to check the wording. The tool is supposed to insert the nth step, not the n+1th.

**Comment by hanswang123456** [comment]
that's another option too. I can edit up the files and draft a PR

**Comment by ieahleen** [comment]
@hanswang123456 could you maybe also change the documentation? it says the same thing
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/how-to-work-on-practice-projects.md

**Comment by hanswang123456** [comment]
@ieahleen I've updated the documentation in the PR. I've removed the redundant example in the doc as well. Let me know if any edits should be made.
