### ISSUE TITLE
Bonfire: Check for Palindromes - Description doesn't explain the last test case

### ISSUE THREAD

**Issue by dawnguard** [FreeCodeCamp/FreeCodeCamp#4734]
``palindrome("0_0 (: /-\ :) 0-0") should return true.``

It should be 0_0 (: /-\ :) **0_0** instead of 0_0 (: /-\ :) **0-0**

In its present state, the bonfire is impossible to do without cheating (Unlike ``-``, ``_``is not a non-word character. I had to add ``|(_)`` to my RegExp to make it work.

**Comment by ltegman** [comment]
Your solution wasn't cheating, it's the correct answer! :smile: `_` might be a word character in regex, but for the purposes of the challenge we consider it "punctuation".

Thanks and happy coding!

**Comment by rybka02** [comment]
I ran into the same problem. Dawn is right. The last challenge shouldn't read True, unless the hyphen is changed to an underscore or vise-versa.

**Comment by SaintPeter** [comment]
@rybka02 I assure you that the last test is correct and complete.  If you are using `\W` to filter non-word characters, note that the definition of `\W` is `/[^a-zA-Z0-9_]/`.  If you want to capture the underscores as well, you will need to add additional logic to your regex.

**Comment by rybka02** [comment]
It's not.

0_0 (: /-\ :) 0-0 does not equal 0-0 (: /-\ :) 0_0 

The point of the exercise is to be able to input any string and get a TRUE value if it's read backwards (Palindrome). Of course you can filter non-word characters, but then it's not a true palindrome.

https://en.wikipedia.org/wiki/Palindrome

**Comment by SaintPeter** [comment]
On the same Wikipedia page, next sentence:
> Allowances may be made for adjustments to capital letters, punctuation, and word dividers.

Otherwise, the classic Palindrome is "A man, a plan, a canal, Panama!" would not be a "true" palindrome.

If you remove "All punctuation" from `0_0 (: /-\ :) 0-0` you get `0000`, which is a palindrome.

Ultimately, though, it comes down to the constraints that we've set for this problem.  You could just as easily say we're testing for a "Palindrome style sequence" which meets the description and test cases we've set forth, for the purposes of teaching Javascript.

**Comment by jbmartinez** [comment]
The last test is fine, the problem is in the description:

>You'll need to remove punctuation and turn everything lower case in order to check for palindromes.

Underscore is not punctuation, it's a symbol. That's why `\W` doesn't capture it.

**Comment by SaintPeter** [comment]
I'd be amenable to a PR that clarifies or expands that.  Maybe:
> You'll need to remove punctuation, spaces, and symbols and turn everything lower case in order to check for palindromes.
I do want to take care that we don't make it too easy.  Part of the challenge is trying to figure out the corner cases.
I have also said to "remove all non-alphanumeric characters", but that is a bit more opaque.

**Comment by rybka02** [comment]
If you simply changed 0-0 to 0_0 or vice-versa it's still challenging and you could keep everything else the same. This is merely feedback from the community.

**Comment by SaintPeter** [comment]
> If you simply changed 0-0 to 0_0 or vice-versa it's still challenging

The entire existence of this test case is to cause users to understand what `\W` MEANS.  We very deliberately created this test to keep campers from blindly using `\W` in their regex without understanding what it actually represents.

**Comment by rybka02** [comment]
I didn't even use \w and I got it completed.

Used split, replace, join and reverse. So I'm not quite sure why a user would necessarily use \w if it doesn't outline the use of it in the description.

**Comment by jbmartinez** [comment]
I think "remove all non-alphanumeric characters" it's the best way to express the idea. [This wikipedia page](https://en.wikipedia.org/wiki/Alphanumeric) is the first result for "alphanumeric characters" on google, which explains it quite clearly, in my opinion

**Comment by rybka02** [comment]
Understanding the directions shouldn't be the challenge-- it should be what the directions ask for. Anyhow, I'm just a new user giving feedback. I'm not trying to really cause a ruckus. Good luck people.

**Comment by jbmartinez** [comment]
Your feedback is appreciated, @rybka02 . We are trying to make the directions as clear as possible without revealing the solution

**Comment by SaintPeter** [comment]
I've reopened this.  I'll accept a PR with an amended description.

@rybka02 I do appreciate you pressing the point.  We definitely get questions on this one, so some clarification in the directions is clearly needed.

**Comment by jbmartinez** [comment]
I'm about to send a PR for this. The wording I used is

>"You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols)" 

I think it's pretty clear
