### ISSUE TITLE
Implement DropDownButton component

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/freeCodeCamp#47356]
### Describe the Issue

`/client/src/components/solution-display-widget/index.tsx`
`/client/src/templates/Challenges/components/tool-panel.tsx`
<img width="745" alt="image" src="https://user-images.githubusercontent.com/1336862/185940629-e6ed9bfa-553c-40d1-8005-6a493bcc804b.png">

### Affected Page

client/src/components/solution-display-widget/index.tsx

### Steps to Reproduce

1. Go to 'cirriculum->responsive-web-design' (resolution should be less than 600 px)
2. Click on first challenge
4. See topdown button at age footer

### Expected behavior

when clicking main button it will display menu with options

### Screenshots

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1336862/185943289-f8841b91-61d0-4a4c-8821-6383f6d7e5b6.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ahmadabdolsaheb** [comment]
Thank you for opening this issue.
I see another usage for this component in `/client/src/templates/Challenges/components/tool-panel.tsx`. Could you please include the component spec and implementation plan as well. 

Here is the documentation's [Researching and Planning](https://contribute.freecodecamp.org/#/how-to-work-on-the-component-library?id=how-to-work-on-the-component-library) and the [button issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/45357) for your reference

**Comment by PrakritiShetty** [comment]
Hi, can this issue be assigned to me? 
Also, can the hacktoberfest label also be added to this issue

**Comment by ahmadabdolsaheb** [comment]
@PrakritiShetty, there is an open pr for this issue. Feel free to work on any of the remaining components https://github.com/freeCodeCamp/freeCodeCamp/issues/44668
