### ISSUE TITLE
Division elements and closing tags

### ISSUE THREAD

**Issue by jmoakey** [FreeCodeCamp/FreeCodeCamp#4735]
I got all checkmarks on this section except for one part; the goals say I need a closing tag for all my division elements. But I posted the code in GitHub and everyone sees what I see, that there are enough closing tags for each division element:
```
<div class="row">
  <div class="col-xs-8"><h2 class="text-primary text-center">CatPhotoApp</h2></div>

  <div class="col-xs-4"><a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a></div>
</div>
```
Any suggestions?

**Comment by ltegman** [comment]
Please provide a link to the waypoint your are working on.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
