### ISSUE TITLE
translated challenges can fail because of translated comments in seed code

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47351]
### Describe the Issue

Running the tests in step 6 of Cat Photo App practice project in Portuguese the test

> O texto do comentário deve ser `TODO: Add link to cat photos`. Não altere o texto nem o espaçamento do comentário.

fail.

### Affected Page

https://www.freecodecamp.org/portuguese/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6

### Your code

```
<html>
  <body>
    <h1>CatPhotoApp</h1>
    <main>
      <h2>Cat Photos</h2>
      <!-- TODO: Adicionar link para as fotos de gatos -->
    <p>Click here to view more cat photos.</p>
    </main>
  </body>
</html>
```

it's the starting code of the step

### Expected behavior

The comment in the seed code is translated. It shouldn't be or the test should be different.

### Screenshots

![image](https://user-images.githubusercontent.com/26656284/185881765-90628b01-2a90-4355-ab79-ae9c81a8ac70.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

cc/ @DanielRosa74 @naomi-lgbt @RafaelDavisH

**Comment by ojeytonwilliams** [comment]
We *could* include translations in the tests, but I recommend removing any reliance on the translated text instead.

**Comment by ieahleen** [comment]
considering that the user add the english version in a previous step, maybe the comment is to not be translated

**Comment by DanielRosa74** [comment]
Reverted the text back to English on Crowdin (comments.json) for the time being. It does not seem to influence any other part of the code. However, there may be other comments and producing the same results on the Portuguese version.

**Comment by ojeytonwilliams** [comment]
I think @ieahleen is right - since it's 'code' the user enters, it should not be translated. In other words, it should be added to the list of comments not to be translated.

**Comment by ieahleen** [comment]
so that would be move the string from
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/dictionaries/english/comments.json
to
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/dictionaries/english/comments-to-not-translate.json

do you know if there is something to change somewhere else, @ojeytonwilliams?

**Comment by ojeytonwilliams** [comment]
I think that covers it, @ieahleen, thanks!

**Comment by ieahleen** [comment]
considering this is breaking for the various translated curriculums, I am going to make a PR after the meeting
