### ISSUE TITLE
Language selection menu - not intuitive about available languages

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#47360]
### Describe the Issue

The language selection menu is not intuitive about the no. of available options. It's a bit paradoxical at the moment:

- You will not notice additional options until you start scrolling while being on top of the options. 
- You will not start scrolling until you know there are additional options.

### Affected Page

https://www.freecodecamp.org/learn

### Steps to Reproduce

1. Go to '/learn'
2. Click on 'Menu'
3. Scroll down to 'Change Language'
4. Hover the cursor on the options
5. Start Scrolling while being in the area of the listed options.

### Expected behavior

1. The menu should be very clean and intuitive.
2. The "Cancel Change" option should have some form of visual separation.

### Screenshots

https://user-images.githubusercontent.com/1884376/185990344-9c32de09-ec12-4397-82c3-4c2b50bf2f87.mp4

### System

- Device: All Devices
- OS: All OS
- Browser: All Browsers
- Version: All Versions

**Comment by raisedadead** [comment]
@ahmadabdolsaheb, this will start becoming evident with more languages on the list.

**Comment by kulraj710** [comment]
is this issue still being worked on? If not, I would like to take it.

**Comment by ahmadabdolsaheb** [comment]
That makes sense, I thought we fixed that.

`height: 19.9rem;` should be removed for `.nav-lang-menu` and 
```
#nav-lang-menu li:first-child {
    border-bottom: 0.1rem solid var(--gray-45);
}
```

**Comment by raisedadead** [comment]
@kulraj710 or anyone else interested, this is up for grabs.

**Comment by boontham33345** [comment]
Good 
[readme.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/9522454/readme.txt)

**Comment by bbsmooth** [comment]
> height: 19.9rem; should be removed

This is what makes the language menu full length so no vertical scroll bar appears. Originally, I had the language menu set so that a vertical scroll bar would appear if it was taller than the main menu. But it was decided that there shouldn't be a vertical scroll bar, the language menu should be as tall as necessary so no scroll bar was needed. Is this what we still want? Even as we continue to add even more languages?

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth thanks for bringing this up. Ideally we would need to show as many languages as possible in a viewport and display a minified scroll bar if the list exceeds the height viewport minus of the navigation.

We could show a scrollbar initially as you recommended, but the dropdown needs expand further than the main menu if needed.
