### ISSUE TITLE
Suggest searching the forum before making a help thread

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#47375]
### Describe the Issue

We should find a way to cut down on the number of support threads. Not just by improving the challenges but by improving the help the camper can find for themselves before even having to ask a question.

I think if we ask the camper to search the forum when making an "ask for help" thread it might do the trick. Or now that the forum can handle the same title for multiple threads maybe we can automatically link to a search using the challenge title?

Either one I think can help cut down the number of support threads.

### Affected Page

https://forum.freecodecamp.org/

### Your code

```

```

### Expected behavior

Less of the same threads.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
I like the idea of linking to a search for the same title.

**Comment by ieahleen** [comment]
Well, there is already this...
![image](https://user-images.githubusercontent.com/26656284/186707877-0f6f16a0-1cf6-45a3-8853-783116422763.png)

**Comment by jeremylt** [comment]
Right, but posters already mash the 'Create Topic' button without reading, so it would be nice to catch them before that point.

**Comment by lasjorg** [comment]
Would there be some way of using this idea to also prevent campers from posting duplicate threads for the same step? I guess it would require that the freeCodeCamp login was tied to the forum login which I don't think they are.

Anyway, just a thought I had.

**Comment by ieahleen** [comment]
@lasjorg at this time the forum is hosted by Discourse, I imagine it would need to be self-hosted for more integration with the curriculum

**Comment by KinzaaSheikh** [comment]
Maybe it can be done by suggesting the related topics before the post goes live in the forums.
