### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jakefair97** [freeCodeCamp/freeCodeCamp#47376]
### Describe the Issue

There is a typo on the JavaScript Algorithms and Data Structures -> Functional Programming -> Understand Functional Programming Terminology page in the 6th paragraph.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/understand-functional-programming-terminology

### Steps to Reproduce

Load the page

### Recommended fix or suggestions

Adding a comma after the seventeenth word (the word "value")

### Screenshots

<img width="694" alt="Typo on FCC page" src="https://user-images.githubusercontent.com/100549835/186541378-b886fa6f-a4fa-4ea9-9e65-2c2d20637030.png">

**Comment by vedanshi555** [comment]
can you assign this issue to me?
@jakefair97

**Comment by ShaunSHamilton** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by vedanshi555** [comment]
> An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.
> 
> If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/
> 
> If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

okay👍🏻
