### ISSUE TITLE
a typo in DB curriculum

### ISSUE THREAD

**Issue by JustLolo** [freeCodeCamp/freeCodeCamp#47388]
### Describe the Issue

it should be --> important <-- instead of import

### Affected Page

 Learn Bash Scripting by Building Five Programs

### Your code

```

```

### Expected behavior

False. An **_important_** operator in that menu is =~. It allows for pattern matching. Using the same syntax but with this operator, check if hello contains the pattern el.

### Screenshots

![image](https://user-images.githubusercontent.com/103621114/186911012-575528d9-74bf-4be8-9b8c-0ebfe1e4f999.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by DylanDevelops** [comment]
I'll fix this!

**Comment by DylanDevelops** [comment]
Just for reference, I will be fixing [this](https://github.com/freeCodeCamp/learn-bash-scripting-by-building-five-programs) issue in this repository.

**Comment by DylanDevelops** [comment]
Hey guys! I'm getting this error when typing `coderoad build` in the terminal. Anyone know how to fix? I created a seperate branch that is up to date.

```Building CodeRoad tutorial.json...
(node:36797) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Error loading commits:
Code branch "v1.0.3" not found
```

**Comment by gikf** [comment]
@DylanDevelops For generating `tutorial.json` file, the coderoad cli requires for the _version_ branch to exist locally. 

Detailed guidelines how to contribute to these tutorials can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Please refer to the parts about making changes on the `main` branch.

Thank you and happy coding! 😊

**Comment by DylanDevelops** [comment]
Perfect. I have the typo fixed and ill make that branch work with coderoad. Thank you for your patience
