### ISSUE TITLE
email notifications about news comments should hyperlink to actual comment thread

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#474]
I recieved this email: 

Just a quick heads-up: testify
 replied to you on Camper News.
You can keep this conversation going.
Just head back to the discussion here: http://freecodecamp.com/news/
learning-d3--essential-skills-for-the-javascript-programmer--mr-hassles-long-underp
- the Free Code Camp Volunteer Team

the link takes me to the main news page.  Searching for "d3" took me to my original submission, but there was no additional comment from "testify". 

Perhaps as a separate issue, commenting should bump the news item up in some way.

**Comment by QuincyLarson** [comment]
@adventurebear can you verify that the link you received in the email had a space between  http://freecodecamp.com/news/ and learning-d3--essential-skills-for-the-javascript-programmer--mr-hassles-long-underp? That is why the link wasn't working. Links shouldn't have spaces in them obviously, so if that was the case, we need to trim leading whitespace from titles.

**Comment by AdventureBear** [comment]
I copied and pasted exactly as the Emil was so that's probably the cause. I
deleted it already though.

On Saturday, May 23, 2015, Quincy Larson <notifications@github.com> wrote:

> @adventurebear <https://github.com/adventurebear> can you verify that the
> link you received in the email had a space between
> http://freecodecamp.com/news/ and
> learning-d3--essential-skills-for-the-javascript-programmer--mr-hassles-long-underp?
> That is why the link wasn't working. Links shouldn't have spaces in them
> obviously, so if that was the case, we need to trim leading whitespace from
> titles.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/474#issuecomment-104953969>
> .
>


-- 
Schedule a Swim lesson, Podcast or Coaching consult here:
http://www.booknow.so/SteelCity

**Comment by AdventureBear** [comment]
to clarify, it was a line break, but that may be due to a space followed by a long unbroken "word" falling to the next line.    Maybe a short link stays on one line and the hypertext works?

**Comment by QuincyLarson** [comment]
@adventurebear this is now fixed! Thanks for reporting it!
