### ISSUE TITLE
Tests for `remove-an-element-from-a-max-heap` challenge passable with incorrect solution

### ISSUE THREAD

**Issue by Adelinked** [freeCodeCamp/freeCodeCamp#47401]
### Describe the Issue

The issue is with the tests of the [Coding interview prep/Data structures/Remove an Element from a Max Heap] challenge.
In fact, I was able to pass the challenge by implementing a wrong remove method which only verifies the max heap property 
for the root element. Passing this challenge without a 100% correct solution will create issues for campers for the next one (the heap sort) as we usually adapt the max heap to become min heap. As a suggestion for resolving the issue is to test the max heap property at each insert/remove operation.
You can verify the issue with the code provided below. 

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/remove-an-element-from-a-max-heap

### Your code

```
const isDefined = (value) => value !== undefined && value !== null;

var MaxHeap = function () {
  // Only change code below this line
  this.heap = [null];

  this.insert = (value) => {
    this.heap.push(value);

    const place = (index) => {
      const parentIndex = Math.floor(index / 2);
      if (parentIndex <= 0) return;
      if (this.heap[index] > this.heap[parentIndex]) {
        [this.heap[parentIndex], this.heap[index]] = [
          this.heap[index],
          this.heap[parentIndex],
        ];
        place(parentIndex);
      }
    };
    place(this.heap.length - 1);
  };
  //
  this.print = () => {
    return this.heap;
  };
  //
  this.remove = () => {
    const removed = this.heap[1];
    this.heap[1] = this.heap[this.heap.length - 1];
    this.heap.splice(this.heap.length - 1, 1);

    const place = (index) => {
      if (index === this.heap.length - 1) return;
      const child1Index = 2 * index;
      const child2Index = child1Index + 1;
      const child1 = this.heap[child1Index];
      const child2 = this.heap[child2Index];

      if (
        (!isDefined(child1) || this.heap[index] >= child1) &&
        (!isDefined(child2) || this.heap[index] >= child2)
      ) {
        return;
      }
      if (isDefined(child1) && this.heap[index] < child1) {
        [this.heap[index], this.heap[child1Index]] = [
          this.heap[child1Index],
          this.heap[index],
        ];
      } else if (isDefined(child2) && this.heap[index] < child2) {
        [this.heap[index], this.heap[child2Index]] = [
          this.heap[child2Index],
          this.heap[index],
        ];
      }
      place(index);
    };
    place(1);
    return removed;
  };
  // Only change code above this line
};
```

### Expected behavior

The test should fail because of the incorrect remove method.

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Mozilla Firefox]
- Version: [Version 104.0 (64-bit) ]

**Comment by nayabatir1** [comment]
Will this be considered for hacktoberfest ?

**Comment by KravMaguy** [comment]
@Adelinked yes, you do not increase the index each time you run your place function. Also I think perhaps it should be `if (isDefined(child2) && etc..` and not `else if`. I hope the pull request solves the issue.

**Comment by Adelinked** [comment]
yes, but the issue is my wrong solution passes the tests
