### ISSUE TITLE
Learn Responsive Web Design By Building A Piano - Step 32 - Media Query

### ISSUE THREAD

**Issue by Tracerract** [freeCodeCamp/freeCodeCamp#47417]
### Describe the Issue

For context, I mentioned in #46886: 

> This is further compounded in [Step 32](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-32) which necessitates the use a logical operator to make a more complex media query that checks multiple conditions.

The fix  #47389 resolves Step 27 (Thank you!), and introduces media queries (which was the title of that issue), so I'm bringing up Step 32 as it's own issue. If there was a better way to go about this please let me know.

This step requires the use of multiple conditions via 'and', but that syntax isn't shown or explained yet. The solution for this step being something like:

```
@media (max-width: 1199px) and (min-width: 769px) {

}
```

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-responsive-web-design-by-building-a-piano/step-32

### Your code

```
Not applicable
```

### Expected behavior

Expected explanation of syntax required to use multiple conditions on one media query.

### System

- Device: Desktop
- OS: Win 10
- Browser: Firefox

**Comment by hanswang123456** [comment]
That would be a useful addition. Maybe add an example snippet.

**Comment by Sboonny** [comment]
While we are improving the description, should we include [4th level media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax_improvements_in_level_4) in curriculum as extra steps. Or as it's known in curriculum as [range syntax](https://developer.chrome.com/blog/media-query-range-syntax/)

example

```css
@media (30em <= width <= 50em ) { /* … */ }
```

**Comment by Tracerract** [comment]
> While we are improving the description, should we include [4th level media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax_improvements_in_level_4) in curriculum as extra steps. Or as it's known in curriculum as [range syntax](https://developer.chrome.com/blog/media-query-range-syntax/)

I do see your point, and I do agree that this would definitely be the place to explain that one in particular. I feel like that should fall under the scope of a mild rework/update for the 4th level media query though (as this wouldn't be the only new thing needing changed.) 

### **I'm unsure what the standard is for CSS to be adopted by browsers before being taught in the curriculum.** 

Specific to your example though, [this page](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#browser_compatibility) tells me that the 'range syntax' (which I do admit is very useful) is mostly supported by mozilla and chrome currently. Double checking with [this page](https://caniuse.com/?search=range%20syntax) shows that edge started supporting it only in the last couple months, and that this particular feature is still unsupported on Safari and Opera. 

I feel like range syntax is probably on the side of still too new to teach. I really wish it wasn't though, as that does look like a pretty useful tool. At least it's closer than `attr()` support is though.

**Comment by 1LISA2** [comment]
![下载 (6)](https://user-images.githubusercontent.com/103248540/188255886-71ce3c98-3b7b-4f49-8c32-4797f49455ee.jpeg)
![下载 (2)](https://user-images.githubusercontent.com/103248540/188255889-37cba8ed-d65b-49d9-972e-bd796a9ecc08.jpeg)
