### ISSUE TITLE
Bonfire: Drop It - Add additional Test Cases

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4741]
Ever since we added the last test case to [Drop It](http://www.freecodecamp.com/challenges/bonfire-drop-it), there have been questions about it.

We either need to add several additional test cases which have a later number which does not meet the test criteria retained, or alter earlier test cases to have that same condition.

Relevant Text (Emphasis added):
< Drop the elements of an array (first argument), starting from the front, **until** the predicate (second argument) returns true.

Existing Test Case:
`drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, 2].`

We do believe that this "early exit" solution is important and should be supported by test cases.

**Comment by SaintPeter** [comment]
Ref: #4737 for an example of the sort of issue we see.

**Comment by alan1001110** [comment]
I'll do this.  Note I've never actually made a PR before, anywhere.

**Comment by 1LISA2** [comment]
![下载 (2)](https://user-images.githubusercontent.com/103248540/188255899-ee677287-bc38-4256-9871-f34eb7c82aa0.jpeg)
![images (2)](https://user-images.githubusercontent.com/103248540/188255901-8c954ffb-6fb7-4e1c-b17d-9609b1b1891d.jpeg)
