### ISSUE TITLE
Wrong word in step 17, 28, 37 of Building a registration form of RWD

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#47423]
### Describe the Issue

The text refers to `id`s as properties instead of attributes. 

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff919a7b5612c0670923a5.md, https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff8b9dab5ac88e4d3d43a3.md, https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff8e998d3e7eae14d6ae3b.md

### Your code

https://github.com/freeCodeCamp/freeCodeCamp/blob/aa4404e05af522af8abb5c83f3e145bb6febee4b/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff8b9dab5ac88e4d3d43a3.md?plain=1#L12

https://github.com/freeCodeCamp/freeCodeCamp/blob/aa4404e05af522af8abb5c83f3e145bb6febee4b/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff8e998d3e7eae14d6ae3b.md?plain=1#L12

https://github.com/freeCodeCamp/freeCodeCamp/blob/aa4404e05af522af8abb5c83f3e145bb6febee4b/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff919a7b5612c0670923a5.md?plain=1#L12

### Expected behavior

The text should use the term "attribute"

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
My bad. I am happy for the mentioned references be changed to:

```markdown
... `id` attributes: ...
```

---

An issue with the _first timers only_ label is open for contribution by **first timers**. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Sboonny** [comment]
While we are trying to change it, can we switch the code blocks arrangements? This will help with Arabic translation. 

Example 

> Use these values `first-name`, `last-name`, `email`, `new-password` for the respective `id` attribute.

**Comment by ShaunSHamilton** [comment]
Let us go with:

> Use `first-name`, `last-name`, `email`,  and `new-password` as values for the respective `id` attributes.
