### ISSUE TITLE
wrong order of table contents in an English article

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#47430]
### Describe the Issue

In [this article](https://www.freecodecamp.org/news/how-to-optimize-nodejs-apis/), two tables

| Method | Document Scanned |
| --- | --- |
| Without indexing | With indexing |
| 1039 | 1 |

| Method | Response Time |
| --- | --- |
| Without using Redis | With Redis |
| 900ms | 0.621 |

### Affected Page

https://www.freecodecamp.org/news/how-to-optimize-nodejs-apis/

### Steps to Reproduce

finding this when reviewing translation

### Recommended fix or suggestions

should be

| Method | Document Scanned |
| --- | --- |
| Without indexing | 1039 |
| With indexing | 1 |

| Method | Response Time |
| --- | --- |
| Without using Redis | 900ms |
|  With Redis | 0.621ms |

**Comment by kartikjoshi267** [comment]
Hey @miyaliu666 
I would like to work on this issue, but I am not able to reproduce this issue on my local machine despite cloning it successfully.

**Comment by ieahleen** [comment]
thank you for your interst in contributing, @kartikjoshi267 , the articles are in a CMS that only the editorial team can access.

Please check out the issues with "help wanted" label to find issues to which you can contribute to!

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this issue @miyaliu666. I just updated the article based on your suggestions, and it should go live after the next build.

Please take a look when you can and let me know if there are still issues with the table, or if you notice any other issues throughout the article.

And thanks for your interest in contributing @kartikjoshi267. Like @ieahleen mentioned, someone on the editorial team needs to go in and fix the issue.

But you can still contribute by reporting any issues you find in a published article. If you're reading something on freeCodeCamp News and notice something like a broken image, a bug in the code, and so on, please feel free to open an issue here in the main repo. Then someone on the editorial team can go in and make the fix.

**Comment by miyaliu666** [comment]
Just checked it again and it looks good now:) @scissorsneedfoodtoo
