### ISSUE TITLE
Got full disk and needs to resize but don't want to upgrade on cloud9

### ISSUE THREAD

**Issue by CheTene** [FreeCodeCamp/FreeCodeCamp#4743]
Challenge [Waypoint: Manage Packages with NPM](http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hey,
I'm learning node js via freecodecamp and i've got stuck in this level and found out that the reason is that my disk is full (1GB and 512MB memory). So i get "Killed" message.

How do i solve this issue without upgrading the cloud9 package (more disk space and memory)  which is not free? 
Are all the ppl who learned it, did actually upgrade and pay for this?

**Comment by SaintPeter** [comment]
Did you do anything special with your instance?  Starting with a fresh instance and following the install instructions you shouldn't need anywhere near the 1GB of space.   We might have issues with memory, though.

**Comment by ltegman** [comment]
@SaintPeter is correct that this challenge should not take anywhere near the full memory or disk space of a free c9 instance. I just went through the lesson myself to confirm. Make sure you're doing the challenge with a fresh instance and that you're not installing an excessive amount of npm packages.

Thanks and happy coding!
