### ISSUE TITLE
Github - open a new issue - news editorial team email address should be displayed on github

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#47453]
When opening a new issue on Github for the /new sarticles, the user is forced to click on a link to open their local mail software.
Some users do not use a local mail app and do not have it setup.

If we can simply add the email address to the description (see below for mockup) then someone can grab it and use it on their online mail server just as easily if they wish. I realise that this will bypass the email template, but maybe one can be provided with the template as a link as well in the same area...

Mockup of Solution:
==============================

Report issues with content on /news articles
Please fill out an email to our editorial team [`editorial[at]freecodecamp.org`] to report issues on specific articles on our technical publication (link opens an email template). Copy then fill out this <template@somewhere> to describe the issue to the team.

**Comment by ShaunSHamilton** [comment]
Hello there,

My understanding is we do not want to include too many (if any) obvious links to such email address, because it will cause an increase in spam (from bots scraping public sites like GitHub).

So, in the past, we have done as so: https://contribute.freecodecamp.org/#/FAQ?id=additional-assistance

**Comment by hbar1st** [comment]
I see the link you mentioned does have one email address posted in it. So should people email that instead (if they don't want to setup their mail app?)

**Comment by naomi-lgbt** [comment]
I'm not sure how often that email is monitored, tbh.

However, campers who do not wish to use the mailto link are totally able to proceed with the issue creation flow instead - we make sure those issues are seen by the correct people.

I'm not sure there's anything to fix here, tbh.

**Comment by hbar1st** [comment]
Thanks for your comment. I will close this issue.
