### ISSUE TITLE
[learn: New RWD] Hotkeys don't work when instructions are focused 

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#47457]
### Describe the Issue

When doing the new RWD challenges, the hotkeys don't seem to work when the instructions or the tests text/hints are focused.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
2. Click the instructions area or the area around the 'check your code' button
3. Attempt to use the hotkeys (ctrl+enter | cmd+enter) to run the tests
4. The tests don't run

### Expected behavior

The tests should run

### System

I only tried the on mac - I would guess this happens on all OS's, but I'm not sure.

### Additional context

The same happens if you click the preview - although, I'm not sure if we need a fix for that.

# Edit

So the main issue of the hotkeys not working was fixed. I think we just want to add some tests that check those hotkeys and we can close this.

**Comment by ojeytonwilliams** [comment]
The PR should fix the problem, but I think tests would be good to prevent regression, so I'll leave this issue up.

**Comment by trngapp** [comment]
What is the update of this issue?

**Comment by ieahleen** [comment]
the PR was merged, and the feature is waiting on tests

**Comment by nayabatir1** [comment]
Hey, I would like to work on it. Can anyone tell what should test cases cover.

**Comment by moT01** [comment]
It should test that the hotkeys (ctrl+enter) run the tests when the instructions or test area is focused

**Comment by nayabatir1** [comment]
What is the best place to write test cases ?
Any reference file ?

**Comment by ojeytonwilliams** [comment]
@nayabatir1 cypress/integration/default/learn/challenges/multifile.js is probably the best place for these tests.  There are a few similar tests that you can look at, the obvious difference being we'd want to shift the focus to the instructions before trying to trigger the hotkey.

**Comment by nayabatir1** [comment]
@raisedadead Could you pls share an update on this pr?

**Comment by raisedadead** [comment]
We appreciate you taking the time to help us.

However, keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.

Happy Contributing.
