### ISSUE TITLE
Learn CSS Grid by Building a Magazine - Step 65

### ISSUE THREAD

**Issue by blackpug9** [freeCodeCamp/freeCodeCamp#47459]
### Describe the Issue

There's a slight error in the instructions to Step 65 of the “Learn CSS Grid by Building a Magazine” project.

It says:

> Now it’s time to style your **second** section. Note that it has the text and text-with-images values for the class attribute, which means it is already inheriting the styles from your .text rule.
> 
> Create a .text-with-images selector and set the display property to grid.

It should instead say "Now it’s time to style your **third** section." (as confirmed by freeCodeCamp staff, I first raised the issue in the [fCC forum](https://forum.freecodecamp.org/t/mistake-learn-css-grid-by-building-a-magazine-step-65/551699) -- link to forum post provided).

To provide some background, in this project there are three sections, i.e.

    <section class=“heading”>
    <section class=“text”>
    <section class=“text text-with-images”>

The “second” section in the HTML only has the class “text” and doesn’t have the class “text-with-images”. The instruction should be telling the user to style the “third” section.

Thanks in advance.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-grid-by-building-a-magazine/step-65

### Your code

```

```
No coding error here, just an error with the wording of the instruction on Step 65.

### Expected behavior

It should say:

> Now it’s time to style your **third** section. Note that it has the text and text-with-images values for the class attribute, which means it is already inheriting the styles from your .text rule.
> 
> Create a .text-with-images selector and set the display property to grid.

### System

- Device: Laptop
- OS: Windows 10
- Browser: Firefox

**Comment by DylanDevelops** [comment]
I can fix this typo!
