### ISSUE TITLE
Multifile editor refactor

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#47467]
While working on https://github.com/freeCodeCamp/freeCodeCamp/pull/47463 I ran into an issue where the props get 'stuck' on old values.  What happens is that not every function is recreated on each render. If that function closes over props, then whatever values props had on creation are used whenever the function is invoked (i.e. they're bound). Since the props may have changed by this point, the bound props can easily be incorrect.

Since this is quite tricky to debug, I think we should avoid using props directly inside functions (since we don't know how future devs will use those functions).  Instead, it would make sense to have a single `propsRef` and use that everywhere.

**Comment by MikeKochendorfer** [comment]
Hi @ojeytonwilliams, I would love to give this issue a shot - I reviewed #47463 that you mentioned and I believe I have a good understanding of the problem you bring up here. I just have a clarifying question before jumping into it - you have titled this issue "Multifile editor refactor" but the changes you are proposing here are for the editor.tsx file not the multifile-editor.tsx file under client/src/templates/Challenges/classic/editor.tsx, correct? Or have I misunderstood? Thanks!

**Comment by ojeytonwilliams** [comment]
Hey @MikeKochendorfer thanks for looking into this.  You've understood this correctly - it is `editor.tsx` that contains the majority of the editor code.  `multifile-editor.tsx` is basically just a wrapper around all the editors.

**Comment by ojeytonwilliams** [comment]
I'm not entirely sure this is the way to go.  When I have more time, I'll circle back to refactoring the editor, but I think this can be closed.
