### ISSUE TITLE
html element lesson: url image(the cat) not working.

### ISSUE THREAD

**Issue by aseds** [FreeCodeCamp/FreeCodeCamp#4746]
http://bit.ly/fcc-relaxing-cat

this link does not open

**Comment by SaintPeter** [comment]
Works fine for me. It is hosted on Amazon's services.  It sounds like it's a local networking issue.  Could be related to proxies or VPN, or possibly a plugin you are running in your browerser.

Closing as unable to reproduce.

Thanks and Happy Coding!

**Comment by aseds** [comment]
it worked after maybe three lessons. and thank you.
