### ISSUE TITLE
Explanation Needed - Build a Cat Photo App

### ISSUE THREAD

**Issue by DylanDevelops** [freeCodeCamp/freeCodeCamp#47472]
### Describe the Issue

In the cat photo app depending on the step, people use either `""` or `''` for their code. Example:
`<a href="https://freecatphotoapp.com"></a>` can also be written as `<a href='https://freecatphotoapp.com'></a>`.

### Affected Page

Every step that has an example using either " or '

### Your code

```

```

### Expected behavior

I think that we should have some sort of explanation for this. If I wasn't already a programmer, I would not necessarily understand that these are interchangeable. It would be good to either go through every step and make them consistent or add a little message at the beginning that lets the user know that they can be used interchangeably.

### Screenshots

<img width="616" alt="Screen Shot 2022-09-08 at 12 05 31 PM" src="https://user-images.githubusercontent.com/48571264/189194296-ac210a94-f11f-4408-beb9-3bfbda4b4924.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by mojo-KB** [comment]
I would say we should add a recommended note suggesting using double quotes for a link in this case or any strings to keep the consistency.

**Comment by naomi-lgbt** [comment]
I'd argue that this doesn't need to be clarified.

The tests are specifically written to allow single or double quotes, and the syntax highlighting will indicate that either is valid.

**Comment by bbsmooth** [comment]
> add a little message at the beginning that lets the user know that they can be used interchangeably.

I kind of agree that it might be nice to let people know you can use either double quotes or single quotes for attribute values. I think Cat Photo App Step 8 is the first use of an attribute value. The example in that step uses double quotes. Would it be such a bad thing if we added a note letting them know they can use single quotes as well?

**Comment by naomi-lgbt** [comment]
My only concern with that is the more text we add, the greater the chance people don't read any of it.

**Comment by DylanDevelops** [comment]
That's understandable, but I think leaving it up to them to decide is not necessarily a good idea. If you are learning, it's easier to be told that they are interchangeable so that you know for the future. If for the whole lesson you use quotation marks and then you try to read someone else's code and they have apostrophes, it might be confusing. We save the user confusion later on by just having a quick message that says something about it. We can work on the wording to make it as short as possible.

**Comment by bbsmooth** [comment]
@naomi-lgbt Ya, I get that, I don't want to turn these into chapters worth of text either :smile: But at the same time, people have to be expected to do a little bit of reading if they want to learn. Seems to me one additional sentence is worth the trade-off in this case.

**Comment by DylanDevelops** [comment]
Yeah even if some don't read, the people that do read will benefit from the information later on.

**Comment by ojeytonwilliams** [comment]
Ideally we want each step to teach one thing at a time, so I'd be inclined towards creating a step just for that.  Students should have a better chance of recalling it if they actually have to use the information (even if it's just briefly).

**Comment by Sembauke** [comment]
I agree with Naomi.

Being a developer is all about trial and error and see what things work and things that don't. An entire new step for this seems excessive.

I think we should close this.

**Comment by ojeytonwilliams** [comment]
> An entire new step for this seems excessive.

I would prefer that to bulking up an existing step, though.  That said, I'm fine with leaving this for users to discover on their own.

**Comment by Sembauke** [comment]
Hey @DylanDevelops,
Thank you for opening this issue, we think is should be fine for users to discover this on their own. 
We allow any of the quotation marks, as they are valid. (the tests will pass)
