### ISSUE TITLE
Update title and text from rest parameter to rest property (or element)

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#47473]
### Describe the Issue

A rest parameter would involve parameters.

The MDN article on [rest parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) only has function parameter examples and it links to the function definition part of the specs. The only instance I can find of the words "rest parameter" in the specs is under the [Parameter Lists](https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-parameter-lists) section.

MDN calls it [a rest property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#rest_property) when `...rest` is used with a destructuring assignment.

The specs do seem to have two versions of it if I read it correctly, the `AssignmentRestElement` used with arrays and the `AssignmentRestProperty` used with objects.

[13.15.5.2 Runtime Semantics: DestructuringAssignmentEvaluation](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-runtime-semantics-destructuringassignmentevaluation)

```
ObjectAssignmentPattern : { AssignmentPropertyList , AssignmentRestProperty }

ArrayAssignmentPattern : [ AssignmentElementList , Elision AssignmentRestElement ]
```

While "rest element" might be more correct with an array I don't think using "rest property" for both arrays and objects as MDN does is the end of the world.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements

### Your code

```
const [one, two, ...restElement] = [1, 2, 3, 4, 5];

const { name, age, ...restProperty } = {
  name: 'John',
  age: 30,
  email: 'example@john.com',
  address: 'Sesame Street',
};
```

### Expected behavior

The correct technical definition should be used.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

This PR https://github.com/freeCodeCamp/freeCodeCamp/pull/35496 changed it from rest operator to rest parameter.

**Comment by lasjorg** [comment]
Just so I don't forget if it is changed the hint guide needs to be updated as well.
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements/301218

**Comment by naomi-lgbt** [comment]
I'm honestly tempted to just change this to `spread operator`.

**Comment by lasjorg** [comment]
I assume you mean rest and not spread? Because in the context of the challenge it is rest.

The least specific verbiage would be "rest syntax", which would cover "rest parameter", "rest property", and "rest element".

I'm also not convinced `...` is an operator even though it is often called it.

---

Even though I came to the conclusion independently by reading the specs that it is a "rest element" I now have more confidence that it is in fact the correct term ([rest element](https://exploringjs.com/impatient-js/ch_destructuring.html#rest-elements)).


> https://2ality.com/2022/05/rest-vs-spread.html
> 
> Rest syntax:
> 
> [Rest parameters](https://exploringjs.com/impatient-js/ch_callables.html#rest-parameters)
> [Destructuring via rest elements](https://exploringjs.com/impatient-js/ch_destructuring.html#rest-elements)
> [Destructuring via rest properties](https://exploringjs.com/impatient-js/ch_destructuring.html#rest-properties)
>
> Spreading:
> 
> [Spreading into function calls](https://exploringjs.com/impatient-js/ch_callables.html#spread-arguments)
> [Spreading into Array literals](https://exploringjs.com/impatient-js/ch_arrays.html#spreading-into-array-literals)
> [Spreading into object literals](https://exploringjs.com/impatient-js/ch_objects.html#spreading-into-object-literals)

**Comment by santimirandarp** [comment]
I agree that the wording isn't correct. 

> Spread syntax looks exactly like rest syntax. In a way, spread syntax is the opposite of rest syntax. Spread syntax "expands" an array into its elements, while rest syntax collects multiple elements and "condenses" them into a single element. 

And so in that case, where it is collecting the rest of the array, it is certainly rest. And it is not an operator because it does not operate on array, as spread does.

Rest property sounds good to me.

**Comment by lasjorg** [comment]
I just noticed that the challenge already calls it a "rest element"

> The rest element only works correctly as the last variable in the list.

---

Here is one suggested change:

# Destructuring via rest elements

In some situations involving array destructuring, we might want to collect the rest of the elements into a separate array.

The result is similar to `Array.prototype.slice()`, as shown below:
```
const [a, b, ...arr] = [1, 2, 3, 4, 5, 7];
console.log(a, b);
console.log(arr);
The console would display the values 1, 2 and [3, 4, 5, 7].
```

Variables `a` and `b` take the first and second values from the array. After that, because of the rest syntax presence, `arr` gets the rest of the values in the form of an array. The rest element only works correctly as the last variable in the list. As in, you cannot use the rest syntax to catch a subarray that leaves out the last element of the original array.

Use destructuring assignment with the rest syntax to perform an effective `Array.prototype.slice()` so that `arr` is a sub-array of the original array source with the first two elements omitted.

**Comment by moT01** [comment]
I added the first timers label. Lets go with @lasjorg's suggestion.

**Comment by rahulchopra-dev** [comment]
Hi there, I am completely new to the open source culture and i would want to make this contribution.
Am i allowed to do this contribution?
If yes, then if you guys could guide me through the process. That would be very helpful.

**Comment by Nirajn2311** [comment]
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.

If have not read the [contributors docs](https://contribute.freecodecamp.org/#/) then I would suggest starting from there

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by rahulchopra-dev** [comment]
Since @roygav has already committed changes, i can't commit these changes right?
