### ISSUE TITLE
Confusing wording which should be changed

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#47476]
### Describe the Issue

The difference between ES5 and ES6 construction is the removal of keyword function. The constructor in ES6 or function constructor in ES5 is invoked by a new keyword.

The wording of the question says
> In ES5, we usually define a `constructor` function and use the new keyword to instantiate an object.

and then after code 
> The `class` syntax simply replaces the `constructor` function creation:

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function

### Your code

NA

### Expected behavior

In my experience, it should be
> The class syntax simply replaces the keyword `function` with `construction`.

### Screenshots

<img width="717" alt="Screenshot 2022-09-09 at 10 20 04" src="https://user-images.githubusercontent.com/8664996/189318176-06b56260-838c-4142-8963-6a3391e08572.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jeremylt** [comment]
I think saying that the keyword `function` is replaced with the keyword `constructor` is literally true but also not very useful of an observation.

**Comment by DylanDevelops** [comment]
Should we make this change? Since it's not too complicated of an update to the wording and if it only helps better someone's understanding of the material, we should make the change. But let me know what you think.

**Comment by jeremylt** [comment]
I think that this change removes the usefulness of that sentence. It should be about not what literal characters are changing on the screen but rather what those changes are accomplishing.

**Comment by DylanDevelops** [comment]
> I think that this change removes the usefulness of that sentence. It should be about not what literal characters are changing on the screen but rather what those changes are accomplishing.

I definitely agree with this take.

**Comment by naomi-lgbt** [comment]
I second Jeremy's stance - I don't see any need to change the verbiage here.

Thanks for opening this issue. We are closing this as "wont fix". If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

**Comment by jeremylt** [comment]
Crap, never clicked the button

---

That said, the explanation is a bit awkward, at least in my eyes.

Perhaps something like this:

In ES5, an object can be created by defining a constructor function and using the `new` keyword to instantiate the object.

```javascript
var SpaceShuttle = function(targetPlanet){
  this.targetPlanet = targetPlanet;
}
var zeus = new SpaceShuttle('Jupiter');
```

The `class` syntax replaces the constructor function:

```javascript
class SpaceShuttle {
  constructor(targetPlanet) {
    this.targetPlanet = targetPlanet;
  }
}
const zeus = new SpaceShuttle('Jupiter');
```

**Comment by bbsmooth** [comment]
> The class syntax replaces the constructor function

I think this is the potentially confusing part. The `class` example has a `constructor` method, but I'm guessing a lot of people will think of that as a "constructor function" and thus it doesn't look like the ES5 constructor function has been replaced. I think we just need to be a little more descriptive in the explanation. Perhaps something like:

> The `class` syntax replaces the ES5 constructor function with a `constructor` method:

**Comment by DylanDevelops** [comment]
I can make this change if we think it's worth it? Just lmk

**Comment by lasjorg** [comment]
I'm not sure why constructor is in a code block in the sentences.

> In ES5, we usually define a `constructor` function and use the `new` keyword to instantiate an object.
> The `class` syntax simply replaces the `constructor` function creation:

We just call it a constructor function. The `constructor` method used with a class and a "constructor function" are two different things. It isn't even a constructor function until it is invoked using `new`. It becomes a constructor function by way of invocation, not definition.

I would suggest we remove the code block and only use that with the `constructor` method.

---

As an aside, technically a class is a function.

```
class test {}
console.log(typeof test)// 'function'
```

You can even use an IIFE (not sure why you would do that).

```
const person = new (class {
  name = 'John';
  getName() {
    return this.name;
  }
})();

console.log(person.getName()); // John
```

**Comment by mahassan** [comment]
>We just call it a constructor function. The constructor method used with a class and a "constructor function" are two different things. It isn't even a constructor function until it is invoked using new. It becomes a constructor function by way of invocation, not definition.

>I would suggest we remove the code block and only use that with the constructor method.

@lasjorg Thanks for the correction about the constructor function as I am new to this. 

what @jeremylt reworded it is the way I think should be as it is not confusing and straight forward.

**Comment by lasjorg** [comment]
I wouldn't say the `constructor` method is a replacement for a constructor function, if anything, I would say the `class` is.

> In ES5, an object can be created by defining a constructor function and using the `new` keyword to instantiate the object.
> 
> The ES6 `class` syntax replaces the ES5 constructor function.

---

Not sure if we need to rephrase anything here but we should at the very least remove the code blocks from the two sentences as they are used incorrectly.

In the context of a constructor function, `constructor` isn't a language construct, it's just what we call such a function.

Inside a `class`, the identifier `constructor` is a language construct and you can only have one `constructor` identifier inside the class, that is you can't overload the `constructor` method and you can't have a field named `constructor` (you can have a property though).

```js
// SyntaxError: Duplicate constructor in the same class
class User {
  constructor(name) {
    this.name = name;
  }
  constructor(age) {
    this.age = age;
  }
}

// SyntaxError: Classes can't have a field named 'constructor'
class User {
  constructor = 'test';
  constructor(name) {
    this.name = name;
  }
}

class User {
  constructor(name) {
    this.constructor = name;
  }
}

const user1 = new User('John');
console.log(user1.constructor); // John
```

**Comment by jeremylt** [comment]
In ES5, an object can be created by defining a constructor function and using the new keyword to instantiate the object.

In ES6, a `class` declaration can have constructor method that is invoked with the `new`  keyword:

```javascript
class SpaceShuttle {
  constructor(targetPlanet) {
    this.targetPlanet = targetPlanet;
  }
}
const zeus = new SpaceShuttle('Jupiter');
```

**Comment by jeremylt** [comment]
Do we want to open this for contributions with my last suggested wording?

**Comment by lasjorg** [comment]
@jeremylt I think so, just make sure both of the `new` keywords are inside a code block and `constructor` for the class constructor. As they are both actual code and should be shown as such.

> In ES5, an object can be created by defining a constructor function and using the `new` keyword to instantiate the object.
> 
> In ES6, a `class` declaration can have a `constructor` method that is invoked with the `new` keyword:

I think the second sentence might need to be changed slightly, but I'm not sure how best to word it.

> In ES6, a `class` declaration has a `constructor` method, it is created implicitly or explicitly, and is invoked when instantiating the object with the `new` keyword:

---

At the very least the use of code blocks around the word `constructor` in the original text is wrong and as such is a bug. I don't see how this is a feature request or even something that needs discussion.

**Comment by lasjorg** [comment]
My only small concern is with this part of the sentence.

> has a `constructor` method that is invoked with the `new` keyword

It makes it sound like you call the `constructor` directly using `new`.

There is some level of indirection between the class and the `constructor` I'd like to verbalize. I know the word "invoked" does carry some level of indirection but I'm not sure if that will be clear enough to a beginner.

The class _is_ the constructor.

```
console.log(SpaceShuttle.prototype.constructor === SpaceShuttle); // true
console.log(Rocket.prototype.constructor === Rocket); // true
```

But I do like what you have. 👍

---

Side note, there is a missing `+` in the console.log() for the `SpaceShuttle` class. Just in case anyone uses the code for the update.
