### ISSUE TITLE
Building a Cat Photo App - Step 2

### ISSUE THREAD

**Issue by DylanDevelops** [freeCodeCamp/freeCodeCamp#47471]
### Describe the Issue

In the Cat Photo App Challenge, I think that the wording should be different. Right now it looks like this:

> The `h1` to `h6` heading elements are used to signify the importance of content below them. The lower the number, the higher the importance, so `h2` elements have less importance than `h1` elements. Only use one `h1` element per page and place lower importance headings below higher importance headings.

I believe that we should change the word `to` to say `through`. I think this makes it a little easier to understand that there are a bunch of `h` elements. After this change it would look like this:

> The `h1` through `h6` heading elements are used to signify the importance of content below them. The lower the number, the higher the importance, so `h2` elements have less importance than `h1` elements. Only use one `h1` element per page and place lower importance headings below higher importance headings.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2

### Your code

```

```

### Expected behavior

In my opinion, it should look like what I said above.

### Screenshots

<img width="622" alt="Screen Shot 2022-09-08 at 9 40 00 AM" src="https://user-images.githubusercontent.com/48571264/189165486-298f6e0d-24a5-46ad-a702-b63162c88c00.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by DylanDevelops** [comment]
This is totally my opinion but let me know if you think this is a change worth making.

**Comment by DylanDevelops** [comment]
should I work on this change since no one has picked it up or not?

**Comment by ShaunSHamilton** [comment]
An issue with the  _first timers only_ label is open for contribution by **first time contributors only**. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by DylanDevelops** [comment]
Oh, I'm not a first-timer I've don't this a bunch. just curious since its been open for a few days now and no one has picked it up.

> An issue with the _first timers only_ label is open for contribution by **first time contributors only**. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.
> 
> If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/
> 
> If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ShaunSHamilton** [comment]
> since its been open for a few days now and no one has picked it up.

That is not what I see.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/51722130/189500361-9d2896ff-5f67-4ac4-9685-edbc565b3f64.png">

**Comment by DylanDevelops** [comment]
<img width="670" alt="Screen Shot 2022-09-10 at 2 16 59 PM" src="https://user-images.githubusercontent.com/48571264/189500441-42188e56-8801-4733-afbc-bec9bd969752.png">

**Comment by DylanDevelops** [comment]
i meant this ^

**Comment by sejalmishra** [comment]
Hey, I am a first-timer can I work on this if no one else is?

**Comment by DylanDevelops** [comment]
Yes, go for it @sejalmishra. Read the contributing guidelines and work on a different branch when making the change. Ask me if you need any help.

**Comment by sejalmishra** [comment]
Okay, sure thank you
