### ISSUE TITLE
Step 15 Building a City Skyline curriculum is missing important information

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#47474]
### Describe the Issue

In step 15 of the curriculum called Learn CSS Variables By Building a City Skyline, the instructions fail to provide the name of the variable that is being referenced.
The instructions say:
`To use a variable, put the variable name in parentheses with var in front of them like this: var(--variable-name). Add your variable as the value of the background-color property of the .bb1a class. Whatever value you gave the variable will be applied to whatever property you use it on. In this case, your variable has the value of #999. So #999 will be used as the value for the background-color property. `

Notice that at no point does this paragraph give the exact name of the variable that is to be used to pass this step. 
("Add *your* variable...the variable...your variable" all of these are not variable names)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-15

### Your code

```

```

### Expected behavior

Instead the instructions should mention the variable name once:

To use a variable, put the variable name in parentheses with var in front of them like this: var(--variable-name). Add your variable as the value of the background-color property of the .bb1a class. Whatever value you gave the variable will be applied to whatever property you use it on. In this case, the variable `--building-color1` has the value of #999. So #999 will be used as the value for the background-color property.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: n/a

**Comment by jeremylt** [comment]
The user is expected to use the variable they created on the last step: https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-14

That is the only CSS variable that exists at this point in the project.

That said, people take breaks between steps, so it can be mildly unreasonable to expect users to remember details from previous steps.

Perhaps:

> To use a variable, put the variable name in parentheses with `var` in front of them like this: `var(--variable-name)`. Whatever value you gave the variable will be applied to whatever property you use it on.

>  Add the variable `--building-color-1` as the value of the `background-color` property of the `.bb1a` class.

**Comment by hbar1st** [comment]
yes please. Also I spent a long time trying to help someone because I didn't realize right away that the variable was being referenced from a previous step. (I could see the hints, but I couldn't understand why the hints were hinting at something I had never seen)

**Comment by bbsmooth** [comment]
Why not the best of both worlds?

> Add the variable `--building-color-1` you created in the previous step as the value of the `background-color` property of the `.bb1a` class.

**Comment by jeremylt** [comment]
> To use a variable, put the variable name in parentheses with var in front of them like this: var(--variable-name). Whatever value you gave the variable will be applied to whatever property you use it on.

> Add the variable --building-color-1 you created in the previous step as the value of the background-color property of the .bb1a class.

Seems straightforward of a PR. I'll open it for first timers.

**Comment by hbar1st** [comment]
Thanks for the update. I had a question about updates and how they make it back to the what we see as users in the curriculum. Is there a schedule at all for a release or whenever someone's PR is accepted, it immediately is available to everyone who uses fCC?

**Comment by naomi-lgbt** [comment]
Releases aren't done on a specific schedule.

We merge `main` into `prod-staging` to trigger a staging release (on `freecodecamp.dev`), and merge `prod-staging` into `prod-current` to trigger a production release.

**Comment by shannonharrison118** [comment]
if no one is working on this issue yet, could i work on this?

**Comment by sejalmishra** [comment]
Can I work on it if no one works on it?

**Comment by yashkoli836** [comment]
Hey @hbar1st, I understood the problem that the instructions are not providing the name for the variable used.
And this can be solved by simply providing the name which is --building-color1 having a value #999.
And I would also like to ask If anybody is not working on this issue I would like to work on it.

**Comment by jeremylt** [comment]
Anyone can work on an issue - they are not assigned. We merge the first complete PR to address the issue.

The desired new text is listed above.

**Comment by KILARI380** [comment]
.bb1a {
  width: 70%;
  height: 10%;
  background-color:  var(--building-color1);
}

here i am getting :- The background-color of the .bb1a element should be set.
i dont know what to do?????

**Comment by ilenia-magoni** [comment]
@KILARI380 open a topic on the forum, the repo is not the place to ask for help in solving the steps
