### ISSUE TITLE
Search index.

### ISSUE THREAD

**Issue by BryceAF** [freeCodeCamp/freeCodeCamp#47478]
### Is your feature request related to a problem? Please describe.

Yes, I recently completed "Learn Accessibility by Building a Quiz" in the "Responsive Web Design" lessons. Quite a few of the steps are very vague and ask us to use coding and info that wasn't covered in prior lessons that I can find. 

### Describe the solution you'd like

It seems that a Search Index of some kind would be very helpful in situations like this. Whether it's a search bar that allows you to look up how the coding was done in prior lessons. Ex: If it requires the use of unordered lists and someone is unsure how, they can type "unordered lists" in the search bar and it will bring up the prior lessons that used it. Making it easier to look up and remember.

### Describe alternatives you've considered

Even providing a link that will send the user to a page with information that is relevant to the current step in their lesson would be helpful.

**Comment by naomi-lgbt** [comment]
This has been on my list for a while. Ideally, we should attach a `topic` property to the challenge frontmatter, so we can define the topics a challenge teaches. We could then consume that data wherever we felt it would be helpful.

**Comment by alfonsusac** [comment]
Isn't that what were being done in the Legacy Curriculum? I kinda missed that where every step has a "Title" that I can skim through and go back to that particular step.

**Comment by ahmadabdolsaheb** [comment]
@naomi-lgbt that is a great idea. We also need to find a way to display the topic tags on the step grid/ challenge list.

**Comment by moT01** [comment]
Not sure how we would display the tags on the grid, but I like this idea. We added a "notes" tab to the challenges a while back, none of the steps use it so it never shows up. It's a panel with a button next to the preview button to display it. 

Just throwing this out there - we could maybe make a dictionary with tag definitions - add the tags to the steps, and put the definitions in the notes. So if a step needs you to know how to use unordered lists, you would tag the step with `ul` or whatever, and the `ul` definition, probably with syntax, would show up in the notes.

**Comment by Salabh255** [comment]
Hello Sir please assign me this task

**Comment by naomi-lgbt** [comment]
> We also need to find a way to display the topic tags on the step grid/ challenge list.

> Not sure how we would display the tags on the grid, but I like this idea. 

I don't think we need to display them on the map itself, they just need to be available for the client to consume in a search feature. That is, if I want to find lessons that cover `ul`, I could search and get a list of lessons with that tag.

**Comment by naomi-lgbt** [comment]
Heya @Salabh255, thanks for your interest in contributing. This issue has not been fully discussed yet and is not open for contribution. Issues with https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only are open for contribution.

**Comment by oriooctopus** [comment]
@naomi-lgbt is there anyway we can contribute to the discussion?

**Comment by moT01** [comment]
The issue linked above this comment discusses the tags that would be required for a search like this, so I think I am going to close this in favor of that for now. If anyone disagrees, feel free to leave a comment. Thanks and happy coding 🎉
