### ISSUE TITLE
Include some more testcases.

### ISSUE THREAD

**Issue by punitkrjain** [FreeCodeCamp/FreeCodeCamp#4750]
Challenge [Bonfire: Convert HTML Entities](http://www.freecodecamp.com/challenges/bonfire-convert-html-entities?solution=function%20convert(str)%20%7B%0A%20%20%2F%2F%20%26colon%3B%26rpar%3B%0A%20%20%0A%20%20%2F%2F%20first%20handle%20%26%0A%20%20str%3D%20str.replace(%2F(%26.%7B3%2C5%7D%3B%3F)%2Fg%2Cfunction(match)%20%7B%0A%20%20%20%20console.log(%22Found%20match%20-%22%20%2B%20match%2B%22-%22)%3B%0A%20%20%20%20var%20subMatch%20%3D%20match.substring(0%2C2)%3B%0A%20%20%20%20if%20(match%20%3D%3D%3D%20%22%26amp%3B%22%20%7C%7C%0A%20%20%20%20%20%20%20subMatch%20%3D%3D%3D%20%22%26lt%3B%22%20%7C%7C%0A%20%20%20%20%20%20%20subMatch%20%3D%3D%3D%20%22%26gt%3B%22%20%7C%7C%0A%20%20%20%20%20%20%20subMatch%20%3D%3D%3D%20%22%26quot%3B%22%20%7C%7C%0A%20%20%20%20%20%20%20subMatch%20%3D%3D%3D%20%22%26apos%3B%22)%20return%20match%3B%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%20return%20match.replace(%2F%26%2Fg%2C%22%26amp%3B%22)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D)%3B%0A%20%20%0A%20%20str%3D%20str.replace(%2F%3C%2Fg%2C%22%26lt%3B%22)%3B%0A%20%20str%3D%20str.replace(%2F%5C%3E%2Fg%2C%22%26gt%3B%22)%3B%0A%20%20str%3D%20str.replace(%2F%22%2Fg%2C%22%26quot%3B%22)%3B%0A%20%20str%3D%20str.replace(%2F%27%2Fg%2C%22%26apos%3B%22)%3B%0A%20%20return%20str%3B%20%20%20%20%0A%20%20%0A%7D%0A%0Aconvert(%22Dolce%20%26%26lt%3B%20Gabbana%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(str) {
  // &colon;&rpar;
  
  // first handle &
  str= str.replace(/(&.{3,5};?)/g,function(match) {
    console.log("Found match -" + match+"-");
    var subMatch = match.substring(0,2);
    if (match === "&amp;" ||
       subMatch === "&lt;" ||
       subMatch === "&gt;" ||
       subMatch === "&quot;" ||
       subMatch === "&apos;") return match;
    else {
      return match.replace(/&/g,"&amp;");
    }
    
  });
  
  str= str.replace(/</g,"&lt;");
  str= str.replace(/\>/g,"&gt;");
  str= str.replace(/"/g,"&quot;");
  str= str.replace(/'/g,"&apos;");
  return str;    
  
}

convert("Dolce &&lt; Gabbana");

```
the tests are insufficient. It should include testcases like "dolce &&gabanna", "dolce &&lt; gabanna" etc. I have written the above function which passes the existing tests but is incorrect.

**Comment by SaintPeter** [comment]
I'm sorry, but I fail to see in what way your function in insufficient.  The assumption of the problem is that the strings incoming at not encoded and need to be encoded.  You're proposing that we also encode encodings?  Double encode?  To what end?

If you can give a sample of your propose input, what you would expect to see come out of it, and what actually comes out of it, that would be helpful in understanding what the issue is.

**Comment by punitkrjain** [comment]
OK. I see your point. I think i was even looking at cases where the input string can be poorly formatted. example "{ampersand}{ampersand}amp;". But my understanding of input was incorrect. The input is supposed to be unformatted.  Sorry for confusion.
