### ISSUE TITLE
Step 35 - Build A Cat Photo App

### ISSUE THREAD

**Issue by DylanDevelops** [freeCodeCamp/freeCodeCamp#47509]
### Describe the Issue

The instruction asks you to add an action attribute to your form tag. The URL is `https://freecatphotoapp.com/submit-cat-photo` but I believe we should change it to `https://www.freecatphotoapp.com/submit-cat-photo` as it is how most people would type in a website and the link auto changes to that. When trying to do www in the URL in your code, it fails the check and I believe it should either accept both or we should change it to www.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-35

### Your code

```

```

### Expected behavior

See above.

### Screenshots

![image](https://user-images.githubusercontent.com/48571264/189817846-01a70edf-f864-4fa6-833d-ad6ef601b538.png)

### System

- Device: Windows PC
- OS: Windows 10
- Browser: Opera

**Comment by ArshErgon** [comment]
its working for me, `https://freecatphotoapp.com/submit-cat-photo` can you change the browser of yours? or maybe clean cookies?

**Comment by DHCJS** [comment]
I've come across people using Mozilla and Opera sometimes have an issue.
Several things you can do:
1. Try to do it on your mobile phone
2. Restart and redo  your lesson
3. Change your browser

**Comment by DylanDevelops** [comment]
This works: https://freecatphotoapp.com/submit-cat-photo. I'm saying I think we should change the URL to https://www.freecatphotoapp.com/submit-cat-photo because that's more normal to URLs.

**Comment by naomi-lgbt** [comment]
`www` isn't "more normal" to URLs.

In fact, this very page isn't on a www subdomain:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/63889819/189990576-d4d07a4c-8281-41bb-b69c-d30319cc8e4b.png">

(if you visit the www subdomain it just redirects).

`www` is primarily an artefact from back in the early Internet days, and many sites don't really standardise how this is handled now. I'd argue for no change needed here.

**Comment by DylanDevelops** [comment]
That's true. I just feel people who are newer to coding might not familiar with subdomains and such so I think we should keep it to what kids learn in tech class in school these days and such.

or just let the test pass if they type www

**Comment by jeremylt** [comment]
+1 to the idea that we don't need to stick `www` everywhere it might conceivably go. Sometimes you don't need it, and that's ok.

**Comment by ojeytonwilliams** [comment]
I think there's enough agreement that no change is necessary, so I'm closing this.

Thanks for the discussion, everyone.
