### ISSUE TITLE
Missing code block in practice comparing different values challenge in old JavaScript certification

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47505]
In this line, there is a missing code block around word false

> `3 == '3'` returns `true` because JavaScript performs type conversion from string to number. `3 === '3'` returns false because the types are different and type conversion is not performed.

It should be like this 

> `3 == '3'` returns `true` because JavaScript performs type conversion from string to number. `3 === '3'` returns `false` because the types are different and type conversion is not performed.

here is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/c15fd16ffe5d4a6ad6454ee975f0be339e324455/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/practice-comparing-different-values.md#L18

---

## Additional Content

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Happy contribution.

**Comment by maciek5000** [comment]
I opened pull request
