### ISSUE TITLE
Step 55 - Build a Cat Photo App

### ISSUE THREAD

**Issue by DylanDevelops** [freeCodeCamp/freeCodeCamp#47514]
### Describe the Issue

The instructions tell you to put a `for="Loving"` attribute in the label. However, the instructions ask with a capital `L` but the answer is only accepted if there is a lowercase `L`.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-55

### Your code

```html
Correct Answer:
<input id="loving" type="checkbox"> <label for="loving">Loving</label>

Wrong Answer:
<input id="loving" type="checkbox"> <label for="Loving">Loving</label>
```

### Expected behavior

Since the instructions mention adding `Loving` using a capital L, we should change the code block to a lowercase L as that is what passes the test.

We should change the instructions to something like this where the word, "loving," starts with a lowercase `L`:

> Associate the text `Loving` with the checkbox by only nesting the text `loving` in a `label` element and place it to the right side of the checkbox `input` element.

### Screenshots

![image](https://user-images.githubusercontent.com/48571264/190033125-c40eb9fd-97ad-4fdd-9a09-768b5d837f15.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jeremylt** [comment]
Common mistake by learners.

> Associate the text Loving with the checkbox by only nesting the text Loving in a label element and place it to the right side of the checkbox input element.

The label text and the value of the for attribute are two different things. One should be capitalized and the other should not. The instructions are correct.

**Comment by DylanDevelops** [comment]
> Common mistake by learners.
> 
> > Associate the text Loving with the checkbox by only nesting the text Loving in a label element and place it to the right side of the checkbox input element.
> 
> The label text and the value of the for attribute are two different things. One should be capitalized and the other should not. The instructions are correct.

But the instructions are capital? I think you are misinterpreting my suggestion for what the instructions should be as the instructions that are in place currently.

**Comment by jeremylt** [comment]
No. Your suggested instructions are incorrect.

```

```

**Comment by DylanDevelops** [comment]
I'm talking about the `for="loving"`. the instructions never mention this as being lowercase so I struggled to figure out what was wrong because I typed it as `for="Loving"` and the check failed. I'm saying that it needing to be lowercase is not specified in the instructions. If they are could you point it out because then I am just blind?

**Comment by jeremylt** [comment]
> You can nest the text within a label element and add a for attribute with the same value as the input element's id attribute.

What is the value of the id attribute for the input element?

**Comment by DylanDevelops** [comment]
Oh, I see now. That's my mistake. I was looking in the wrong place. Should we make this instruction clearer? It could have been just me but when reading that I was thinking that it was just giving an example since the usual format is an explanation and examples are the first part and then the second part is the instructions on what you need to do.

**Comment by jeremylt** [comment]
The explanation is the first part and the instructions are the second part though?

> You can also associate text with an input element by doing X.

> Associate this text with this input element.

**Comment by DylanDevelops** [comment]
Yeah but this part:

>You can nest the text within a label element and add a for attribute with the same value as the input element's id attribute.

is in the first part as well and it is technically giving you the instructions of what to do so you can press the check.

**Comment by jeremylt** [comment]
I still don't agree. 

We don't want to turn this into yet another 'type along without thinking' tutorial.

**Comment by DylanDevelops** [comment]
That's true. I'm fine leaving it as is because it was just an honest miss when I was reading those instructions. Thanks for pointing that out!
