### ISSUE TITLE
Broken test: Step 5 of Learn CSS transforms by building a penguin

### ISSUE THREAD

**Issue by yamamoto34** [freeCodeCamp/freeCodeCamp#47513]
### Describe the Issue

Instruction: Remove both the horizontal and vertical scrollbars, and prevent programmatic scrolling, using only one property.
Hint: You should give body and overflow of clip.
I typed in overflow: clip; to the list of properties: values; within the body selector. Even the hint is giving me the same answer, but the code will not pass. I tried different browsers, checked for extensions and updates, but so far nothing has fixed this.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-5

### Your code

```
body { background-color: linear-gradient(45deg, rgb(118, 201, 255), rgb(247, 255, 222)); margin: 0; padding: 0; width: 100%; height: 100vh; overflow: clip; }

```

### Expected behavior

Since I typed overflow: clip; I expected the overflow to be clipped with the rest of the content hidden, and scrolling should be forbidden. According to the hint that comes up and the forum post about this exact issue, I’ve entered the correct code. However, the test keeps failing.

### System

- Device: iPad Pro
- OS: iOS 15.6.1
- Browser: Safari, Chrome, Firefox
- Version: iPadOS 15.6.1

**Comment by jeremylt** [comment]
This exact code is passing for me. It may be [another] Apple following web standards issue?

**Comment by yamamoto34** [comment]
Quite possibly. It’s just so strange that all other tests have been fine, and this very simple one is the only one bugging out.

**Comment by ojeytonwilliams** [comment]
It could be that it only has `overflowX` and `overflowY`.

@yamamoto34 if it's possible to open DevTools on your iPad, could you inspect the preview and click on the `<style class="fcc-injected-styles"></style>` element? Then please go to the console and type

`$0.sheet.cssRules[0].style.overflowX` and then `$0.sheet.cssRules[0].style.overflow`

The console *should* show `'clip'` for both, but if not that might be the issue.

**Comment by yamamoto34** [comment]
I couldn’t exactly do what you said, but I was able to go to Settings>Safari>Advanced>Experimental Features and there was an option to turn on “CSS overflow: clip support” and the test passed! Thank you for helping me figure this out!

**Comment by ojeytonwilliams** [comment]
Interesting, thanks @yamamoto34!

I'll try creating a quick PR to test the hypothesis.  If you're up for a bit of testing, that would be awesome. No worries if not, though!

**Comment by bbsmooth** [comment]
According to [Can I Use](https://caniuse.com/css-overflow), support for `overflow: clip` has only been enabled by default for the latest version of Safari (16.0). So I think a lot of Safari users are going to have trouble with this step for a while. It might be a good idea to accomplish the goal in this step some other way. Or put in a disclaimer for Safari users.

**Comment by yamamoto34** [comment]
Sure! Let me know how I can help.

**Comment by ojeytonwilliams** [comment]
@bbsmooth yeah, chances are we'll need to use regex :(

@yamamoto34 if you can, it would help if you can try going to the PR https://github.com/freeCodeCamp/freeCodeCamp/pull/47515 and clicking on the GitPod button. That should let you try that fix.

I'm not optimistic, to be honest, but it would be good to know.

**Comment by moT01** [comment]
I added the help wanted label here. The linked PR above, that is set to close this, isn't quite ready and has some more discussion on what we want to do.

**Comment by Gerschuk** [comment]
Hi everyone.
The clip property in css is deprecated. [https://developer.mozilla.org/en-US/docs/Web/CSS/clip](url)
I think this step needing change to use `clip-path` property.
Sorry for my english i'm work in it.
Regards.

**Comment by moT01** [comment]
Thanks @Gerschuk

Yea, I think we should definitely change this lesson then - the `overflow: hidden` suggestion I made on the PR might be the better way to go for this particular step. I believe we use that `clip` property somewhere else in the curriculum, as I mentioned on the PR - we should maybe find where it is and see if we want to change that one (those ones?), as well.

**Comment by livinglifemeaning** [comment]
Doesn't 'overflow: hidden' not work on the body and html elements in mobile? I was facing an issue maknig the mobile version of a website and I had to apply the overflow property to the main element that wrapped my content for it to work properly on mobile. 

https://stackoverflow.com/questions/14270084/overflow-xhidden-doesnt-prevent-content-from-overflowing-in-mobile-browsers

**Comment by RJ025** [comment]
is someone working on this issue

**Comment by Omkar0803** [comment]
I would like to contribute, can assign me issues?

**Comment by Gerschuk** [comment]
> I would like to contribute, can assign me issues?

I think you can fork the repo, solve the issues and made a pull request with the solutions.

**Comment by jsmayo** [comment]
I tested adding 'overflow:clip;' in both Chrome and Safari, both passed. I tried the latest version of Safari as well as changing the user agent to match that of the original described above, which passed as well.

**Comment by anand454** [comment]
i would like to contribute,can you assign me some issues.?
