### ISSUE TITLE
Inconsistent display of tests for Bonfire: Roman Numeral Converter

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#4752]
Challenge [Bonfire: Roman Numeral Converter](http://www.freecodecamp.com/challenges/bonfire-roman-numeral-converter) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(num) {
 return num;
}

convert(36);

```

There's inconsistency in how the tests are displaying in the left-hand side. Some show you the actual assert statements plus instructions, others show just the instructions. Only the first six tests show just the instructions, the other sixteen tests show additionally show the assert statement associated with the test. 

![screen shot 2015-11-27 at 21 07 29](https://cloud.githubusercontent.com/assets/2754821/11450217/2f31fa3c-954b-11e5-9aac-3a7c023cb41e.png)

Which should it be? Just instructions? Or showing the assert statements as well?

**Comment by SaintPeter** [comment]
You're right, this is incorrect.
The problem is that the assert statements are missing a `message:`
```js
assert.deepEqual(convert(44), "XLIV", 'message: <code>convert(44)</code> should return "XLIV".');
assert.deepEqual(convert(45), "XLV", '<code>convert(45)</code> should return "XLV"');
```
You can see that the line for 44 has the `message:` and the line for 45 does not.  All of the asserts for numbers greater than 44 need that message prefix.

**Comment by SaintPeter** [comment]
14 minutes from post to closed PR.  Niiiiice.
