### ISSUE TITLE
in    [How to Sign and Validate JSON Web Tokens – JWT Tutorial](https://www.freecodecamp.org/news/how-to-sign-and-validate-json-web-tokens)  about "SHA-256 is an Asymmetric Key Cryptography algorithm,"  is wrong

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#47535]
### Describe the Issue

SHA 256 is a cryptographic hash algorithm which does not use any key. So there is no question of symmetric/asymmetric. A hash function is any function which maps an arbitrary length input into a fixed length output. A cryptographic hash is a hash algorithm which has the property of pre-image resistance and collision resistance.

but the author say "SHA-256 is an Asymmetric Key Cryptography algorithm"

it is wrong 

SHA-256  use to  Verify data integrity。
RSA use to  Encryption and Decryption

RS256 (RSA Signature with SHA-256) is an asymmetric algorithm, and it uses a public/private key pair: the identity provider has a private (secret) key used to generate the signature, and the consumer of the JWT gets a public key to validate the signature. Since the public key, as opposed to the private key, doesn’t need to be kept secured, most identity providers make it easily available for consumers to obtain and use (usually through a metadata URL).

[more info](https://community.auth0.com/t/jwt-signing-algorithms-rs256-vs-hs256/7720)

### Affected Page

https://www.freecodecamp.org/news/how-to-sign-and-validate-json-web-tokens

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

![image](https://user-images.githubusercontent.com/6524977/190837805-7af81112-0c62-4a32-a9ee-53050b947cd7.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by rushikeshadhav** [comment]
Can I take this up?
Just tell me what to add.

**Comment by jdwilkin4** [comment]
HI @rushikeshadhav ! 

It looks like this issue has already been assigned.
But there are plenty of open issues marked with a `help wanted` label if you are interested in contributing. 👍

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this, @luojiyin1987, and for those helpful details.

I went in and fixed that typo. I also reworked a few paragraphs to make it clear that RSA256 is a combination of the RSA algorithm and the SHA-256 hashing algorithm, which are used together to sign and verify JWTs.

The changes should go live within the next few hours.

Please let us know if you notice other issues in this or any other article.
