### ISSUE TITLE
Expecting wrong answer

### ISSUE THREAD

**Issue by kashodiya** [FreeCodeCamp/FreeCodeCamp#4754]
In the following challenge the second last expectation is wrong.
Here is the expectation:

drawer(19.50, 20.00, [["PENNY", 0.01], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 1.00], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return "Insufficient Funds".

Clearly the change is 50 cent and drawer is has ONE dollar bill!

Challenge [Bonfire: Exact Change](http://www.freecodecamp.com/challenges/bonfire-exact-change?solution=function%20drawer(price%2C%20cash%2C%20cid)%20%7B%0A%20%20var%20change%20%3D%20cash%20-%20price%3B%0A%20%20var%20total%20%3D%20cid.reduce(function(p%2C%20c)%7B%0A%20%20%20%20console.log(p%20%2C%20c)%3B%0A%20%20%20%20return%20%5B0%2C%20p%5B1%5D%20%2B%20c%5B1%5D%5D%3B%0A%20%20%7D)%5B1%5D%3B%0A%20%20%0A%20%20console.log(total%2C%20change)%3B%0A%20%20%0A%20%20if(total%20%3C%20change)%7B%0A%20%20%20%20return%20%22Insufficient%20Funds%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Here%20is%20your%20change%2C%20ma%27am.%0A%20%20return%20%22Closed%22%3B%0A%7D%0A%0A%2F%2F%20Example%20cash-in-drawer%20array%3A%0A%2F%2F%20%5B%5B%22PENNY%22%2C%201.01%5D%2C%0A%2F%2F%20%5B%22NICKEL%22%2C%202.05%5D%2C%0A%2F%2F%20%5B%22DIME%22%2C%203.10%5D%2C%0A%2F%2F%20%5B%22QUARTER%22%2C%204.25%5D%2C%0A%2F%2F%20%5B%22ONE%22%2C%2090.00%5D%2C%0A%2F%2F%20%5B%22FIVE%22%2C%2055.00%5D%2C%0A%2F%2F%20%5B%22TEN%22%2C%2020.00%5D%2C%0A%2F%2F%20%5B%22TWENTY%22%2C%2060.00%5D%2C%0A%2F%2F%20%5B%22ONE%20HUNDRED%22%2C%20100.00%5D%5D%0A%0A%2F%2Fdrawer(19.50%2C%2020.00%2C%20%5B%5B%22PENNY%22%2C%201.01%5D%2C%20%5B%22NICKEL%22%2C%202.05%5D%2C%20%5B%22DIME%22%2C%203.10%5D%2C%20%5B%22QUARTER%22%2C%204.25%5D%2C%20%5B%22ONE%22%2C%2090.00%5D%2C%20%5B%22FIVE%22%2C%2055.00%5D%2C%20%5B%22TEN%22%2C%2020.00%5D%2C%20%5B%22TWENTY%22%2C%2060.00%5D%2C%20%5B%22ONE%20HUNDRED%22%2C%20100.00%5D%5D)%3B%0A%0Adrawer(19.50%2C%2020.00%2C%20%5B%5B%22PENNY%22%2C%200.01%5D%2C%20%5B%22NICKEL%22%2C%200%5D%2C%20%5B%22DIME%22%2C%200%5D%2C%20%5B%22QUARTER%22%2C%200%5D%2C%20%5B%22ONE%22%2C%201.00%5D%2C%20%5B%22FIVE%22%2C%200%5D%2C%20%5B%22TEN%22%2C%200%5D%2C%20%5B%22TWENTY%22%2C%200%5D%2C%20%5B%22ONE%20HUNDRED%22%2C%200%5D%5D)%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drawer(price, cash, cid) {
  var change = cash - price;
  var total = cid.reduce(function(p, c){
    console.log(p , c);
    return [0, p[1] + c[1]];
  })[1];
  
  console.log(total, change);
  
  if(total < change){
    return "Insufficient Funds";
  }
  
  // Here is your change, ma'am.
  return "Closed";
}

// Example cash-in-drawer array:
// [["PENNY", 1.01],
// ["NICKEL", 2.05],
// ["DIME", 3.10],
// ["QUARTER", 4.25],
// ["ONE", 90.00],
// ["FIVE", 55.00],
// ["TEN", 20.00],
// ["TWENTY", 60.00],
// ["ONE HUNDRED", 100.00]]

//drawer(19.50, 20.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);

drawer(19.50, 20.00, [["PENNY", 0.01], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 1.00], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]])

```

**Comment by SaintPeter** [comment]
Right, in that case you are instructed to reply "Insufficient Funds".  There are two cases you need to consider:
1) You've already checked to see if the monetary value of the change is enough to cover what is left over.
2) You need to consider what happens if you don't have all of the bills/coins needed to give exact change.

If you need further assistance, please stop by the [HelpBonfires Chat Room](https://gitter.im/FreeCodeCamp/HelpBonfires?utm_source=share-link&utm_medium=link&utm_campaign=share-link).  There are plenty of folks there who can help you work through your code issues.

I am closing this as it is not an issue with the site.
