### ISSUE TITLE
Request to add DOM Manipulation Coding Challenges for JavaScript

### ISSUE THREAD

**Issue by vishalscodes** [freeCodeCamp/freeCodeCamp#47540]
### Is your feature request related to a problem? Please describe.

No, my feature request isn't related to a problem.

### Describe the solution you'd like

I want a dedicated section for DOM Manipulation to learn it. I feel it's an important topic to learn but there's no section to learn it here. Kindly add that Learning Section as it would be beneficial for us.

### Describe alternatives you've considered

I haven't considered any alternatives for this feature.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you for taking the time to open this.

We do have this on the roadmap for the new curriculum. For now, we have the following sections on DOM manipulation:
- https://www.freecodecamp.org/learn/front-end-development-libraries/#jquery
- https://www.freecodecamp.org/learn/front-end-development-libraries/#react
- https://www.freecodecamp.org/learn/data-visualization/#json-apis-and-ajax

As such, I am closing this as on the roadmap.

**Comment by vishalscodes** [comment]
I had meant DOM Manipulation in JavaScript.

**Comment by ShaunSHamilton** [comment]
> I had meant DOM Manipulation in JavaScript.

https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property

Also, jQuery is a JavaScript library, and React is a JavaScript framework.
