### ISSUE TITLE
Learn CSS Variables by Building a City Skyline Step 40 broken

### ISSUE THREAD

**Issue by Nathanael-Whitrow** [freeCodeCamp/freeCodeCamp#47568]
### Describe the Issue

The test hints suggest applying a background, even though I am applying a background correctly.
After checking the MDN page here: https://developer.mozilla.org/en-US/docs/Web/CSS/background
I see that the 'background' property is shorthand for 'background-color'. As there is already a background-color property the new 'background' property must go after, however this isn't mentioned anywhere or given as a hint anywhere.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-40

### Your code

This is invalid and gives the hint: "You should apply a background to .bb1a.":
```
.bb1a {
  width: 70%;
  height: 10%;
  background: linear-gradient(var(--building-color1), var(--window-color1));
  background-color: var(--building-color1);
}
```
This is valid and passes the tests:
```
.bb1a {
  width: 70%;
  height: 10%;
  background-color: var(--building-color1);
  background: linear-gradient(var(--building-color1), var(--window-color1));
}
```

### Expected behavior

I expect a hint about what I've done wrong.
If my code isn't passing because I'm writing the code in the wrong place then it would be helpful to know that.

### System

- Device: Mac book pro
- OS: MacOS Monterey 12.5.1
- Browser: Chrome Dev 
- Version: 107.0.5300.0 (Official Build) dev (arm64)

**Comment by moT01** [comment]
Here's [the file for that step.](https://github.com/freeCodeCamp/freeCodeCamp/blob/5bfd14a4a2d5d2f6f4cf3bee70a883362eb1eaba/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98f0.md)

This seems quite strange. Here's a table with the output I see:

| Failing code in OP | Passing code in OP |
| - | - |
| <img width="327" alt="Screen Shot 2022-09-20 at 6 38 45 PM" src="https://user-images.githubusercontent.com/20648924/191383796-fa8991e1-512e-4649-954c-19663f943278.png"> | <img width="304" alt="Screen Shot 2022-09-20 at 6 39 47 PM" src="https://user-images.githubusercontent.com/20648924/191383747-a6874c68-d048-4302-add4-92b0304439f5.png"> |
| <img width="319" alt="Screen Shot 2022-09-20 at 6 41 06 PM" src="https://user-images.githubusercontent.com/20648924/191383670-d9fdecfa-8627-49ba-a55c-10131d45aa57.png"> | <img width="613" alt="Screen Shot 2022-09-20 at 6 40 15 PM" src="https://user-images.githubusercontent.com/20648924/191383730-f851bd75-69cd-4a22-bdd0-638a9248d3fa.png"> |

In the failing example, the computed values don't seem to be showing the gradient - but in both cases the page is rendering the gradient. Not quite sure what's going on. One solution could be to add another test that says "Your `background` property should be below your `background-color` property."

OSX 10.13.6
Firefox 104.0.2

**Comment by IvanoskiHarmonia** [comment]
In my opinion the invalid case makes sense to me, because having two similar/same styles one after another is not only not desirable but also can lead to a bug that is hard to trace.

Here's what I mean: 

```
.cont {
     margin: 10px 0;
     margin: 5px 0; // this will always be applied because css is read top to bottom, unless the margin above it has !important which tells the compiler to apply the margin on the top in any case.
}
```


So the hint make absolute sense in this case, the highlighted ```background``` shows you that you need to be using only background because gradient only works with the ```background``` property.

I think this on its own is not an issue in the software.

**Comment by Nathanael-Whitrow** [comment]
@moT01 Yeah I think an extra test similar to what you suggest would be a good clarification, and is probably the quickest solution. However...
In the next couple of lessons the code gets moved to its own class and the background-color property is removed.
Perhaps there's a learning opportunity here? @IvanoskiHarmonia makes a good point.
Is it teaching bad code style? Should the background-color be removed in the same lesson? Is it worth inserting another step here about the order of CSS rules, and how not doubling up is good practice?

**Comment by Nathanael-Whitrow** [comment]
The relevant parts of how these CSS rules are defined to work:

- [linear-gradient()](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient) returns an image
- [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color) takes a single color value and is rendered behind any background-image. Its default value is transparent.
- [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background) is a [shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties) for setting all the more specific background properties. If any specific properties are omitted (in this case we give it an image and omit everything else) they are set to default values.

This explains why even if background is set before background-color the gradient still shows up. (linear-gradient is an image and background-image is rendered over the top of background-color).

I'm not sure why the tests don't pick up that the background property is set, I would look into it but I don't know anything about the test suite!

**Comment by IvanoskiHarmonia** [comment]
@Nathanael-Whitrow I think teaching good practice should be included in the lessons, because having both is actually really hard not only to read but it also creates unexpected results that sometimes might lead you to 20-40 min of fix for really bad practices. 

In my opinion and this is just speculations, I think that background-color overwrites something in the browser rules and the assert function thinks that instead of having a linear-gradient it has a single value color.

**Comment by chrischma** [comment]
The easy solution that worked for me: 
Try again with Google Chrome instead of Safari.
