### ISSUE TITLE
Content disappears after clicking "Go to my previous step" button in one step step-challenges

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/FreeCodeCamp#4756]
How to reproduce:

1. Go to any **one step** step-challenge:
[Waypoint: Browse Camper News](http://www.freecodecamp.com/challenges/waypoint-browse-camper-news), [Waypoint: Reference our Wiki](http://www.freecodecamp.com/challenges/waypoint-reference-our-wiki), [Waypoint: Join our LinkedIn Alumni Network](http://www.freecodecamp.com/challenges/waypoint-join-our-linkedin-alumni-network), [Waypoint: Commit to a Goal and a Nonprofit](http://www.freecodecamp.com/challenges/waypoint-commit-to-a-goal-and-a-nonprofit), [Waypoint: Configure your Code Portfolio](http://www.freecodecamp.com/challenges/waypoint-configure-your-code-portfolio).

2. Click "Go to my previous step" button:
![](http://i.imgur.com/TO5uLCi.png)

3. You will see something like this:
![](http://i.imgur.com/7sxqZUV.png)

There is no need for "Go to my previous step" button in these (one step) challenges because actually there is no any previous step.

**Comment by bogadodiegoh** [comment]
Hi, I like to contribute to fix this issue. Thanks!

**Comment by SaintPeter** [comment]
@bogadodiegoh No need to ask permission.  Go for it!

**Comment by gasperno** [comment]
Is it assigned to anyone or can I submit a PR after I fix it?

**Comment by bugron** [comment]
@gasperno It's yours.

**Comment by ltegman** [comment]
Closed by #4830
