### ISSUE TITLE
Wrong Italian translation on Step 44 of (New) Responsive Web Design module

### ISSUE THREAD

**Issue by antoninojob** [freeCodeCamp/freeCodeCamp#47563]
### Describe the Issue

It should say "Sopra l'input di testo..." instead of "Sotto l'input di testo..."

**To Reproduce**
1. Go to Step 44 of (New) Responsive Web Design module in Italian
2. See error on last sentence of the instructions

### Affected Page

https://www.freecodecamp.org/italian/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-44

### Your code

```
none
```

### Expected behavior

It should say "Sopra l'input di testo..." instead of "Sotto l'input di testo..."

### System

- Device: Laptop
- OS: Ubuntu 22.04.1
- Browser: Brave
- Version: 1.43.93

**Comment by Dario-DC** [comment]
Translation fixed @ieahleen

**Comment by ieahleen** [comment]
Thank you for reporting this! It has been fixed on crowdin, and will be brought to GitHub tomorrow by the automatic translation pipelines
