### ISSUE TITLE
Cat Photo App 5 - Confusing Hint

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#47573]
### Describe the Issue

This code will produce the hint

> Hint: Your `main` element's closing tag should be below the `p` element. You have them in the wrong order.

but the actual issue is that the opening `main` tag is in the wrong place.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-5

### Your code

```html
  <h1><main>CatPhotoApp</h1>
  <h2>Cat Photos</h2>
  <!-- TODO: Add link to cat photos -->
  <p>Click here to view more cat photos.</p>
  </main>
```

### Expected behavior

Hint for this code should indicate the problem with the opening `main`tag.

### System

All

**Comment by moT01** [comment]
Here's [the file for that step.](https://github.com/freeCodeCamp/freeCodeCamp/blob/339c6713d2c4e89e7ebd0375199a8ee3be7b9bd6/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc2385ff86c76b9248c6eb7.md)

The third test says "Your `main` element's opening tag should be below the `h1` element. You have them in the wrong order." Seems like it's not checking that quite right. What renders for me with that code:
<img width="314" alt="Screen Shot 2022-09-20 at 6 09 29 PM" src="https://user-images.githubusercontent.com/20648924/191380504-fdeef0f1-7516-437e-b13d-45d47eb387d3.png">
It should make sure the opening `main` is after the closing `h1` - I think that might fix this.

**Comment by naomi-lgbt** [comment]
I don't think we necessarily need to look at the tag order (I do love to avoid regex).

I just think we need to write some more effective DOM queries. What we have isn't very robust.

```js
const collection = [...document.querySelectorAll('main,h1')].map(
  (node) => node.nodeName
);
assert(collection.indexOf('H1') < collection.indexOf('MAIN'));
```

We should be able to:

```js
const main = document.querySelector('main');
assert.equal(main?.previousElementSibling?.tagName, "H1");
```

**Comment by DylanDevelops** [comment]
I can implement these changes. Let me just get this right. Would I replace the previous check with this?

```javascript
const main = document.querySelector('main');
assert.equal(main?.previousElementSibling?.tagName, "H1");
```

**Comment by harshPoonia196** [comment]
This test says that the <main> tag should be started after the <h1> tag . But I didn't get that where to close the <main> tag .
But i did this and the test has been cleared. 

  
    <h1>CatPhotoApp</h1>
      <main>
    <h2>Cat Photos</h2>
    
    <p>Click here to view more cat photos.</p>
    </main>
