### ISSUE TITLE
accessibility quiz step 56 is confusing

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47588]
This step is confusing to many people

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-56

Specifically the
> Also, align the text to the right.

You write the code required
```css
.info > label, .info > input {
  display: inline-block;
  text-align: right;
}
```

and then it says
> You should set the text-align: right property before the .info input rule.

It uses precedence rules without talking about them.
The end result needs to be that the labels have `text-align: right;` and the inputs `text-align: left` so why are we asking yo add the `text-align: right` to a selector list that includes both and then rely on precedence rules to have them assigned property?

**Comment by ShaunSHamilton** [comment]
I cannot answer why it was done like this.

I suppose we could change the tests and instruction to say:
> Also, align the text to the right for `label` elements within `.info` elements.

**Comment by ieahleen** [comment]
and change the tests, right now they specifically test for the new selector to be before the old one, so it would need to be reworked a bit. But I guess we can keep this all as one step, it seems doable.

Create new selector with rulws + add new rule to an already existing selector

Or is it too much?

**Comment by ShaunSHamilton** [comment]
I would say it is no more than we currently have. If there is still too much confusion after this change, we can always split it up.

**Comment by ieahleen** [comment]
So seed code of next step would need to be
```
.info input {
  width: 50%;
  text-align: left;
}

.info label {
  width: 10%;
  min-width: 55px;
  text-align: right;
}

.info > label, .info > input {
  display: inline-block;
}
```

or should the selector be the same as above?, `.info label, .info input {}`

**Comment by tom-raley** [comment]
I'd be happy to take this on!

**Comment by ieahleen** [comment]
@tom-raley go for it
Issues with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted label are up fpr grabs, the first comprehensive PR received is reviewed. Issues are not assigned.

**Comment by SaarthakMaini** [comment]
I am not able to find the files to make the necessary changes.

If possible, could anyone redirect me

Thank you!

**Comment by ieahleen** [comment]
@SaarthakMaini the best way to work on the practice projects is with the challenge editor, as explained in [How to work on practice projects](https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects)

**Comment by Insidiae** [comment]
I'd also be happy to take this on!

**Comment by Akash7649** [comment]
I can doo it please assign it to me

**Comment by Akash7649** [comment]
I can do it please assign it to me
