### ISSUE TITLE
'close' button of success alert, better to be aligned at the right

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/freeCodeCamp#47598]
### Describe the Issue

![image](https://user-images.githubusercontent.com/1336862/191909431-5212abdf-422f-44a8-bdd8-373a8c68017d.png)
https://www.freecodecamp.org/learn
the `close` button on the alert located at some distance from the right side

### Affected Page

https://www.freecodecamp.org/learn

### Steps to Reproduce

1. Go to '[learn](https://www.freecodecamp.org/learn)'
2. After loggin in you will see alert notification at the top
3. the `close` button on the alert located at some distance from the right side

### Expected behavior

i think it is better for close button to be located at the right

### Screenshots

current
![image](https://user-images.githubusercontent.com/1336862/191911649-7ea5c942-d7d4-4b09-bca5-a1b6bc32000e.png)

better design
![image](https://user-images.githubusercontent.com/1336862/191911530-ac0df466-1dd3-426c-840c-478ca95944af.png)

### System

- Device: [Laptop]
- OS: [ Windows 10]
- Browser: [Chrome]
- Version: [e.g. 22]

**Comment by divyanshraj0408** [comment]
It would also be better if the success message be on the extreme left of the page. Like this: 
![Screenshot from 2022-09-23 14-17-21](https://user-images.githubusercontent.com/73312468/191949054-74d75642-102f-4705-9aab-1b9901d0d29f.png)

**Comment by ahmadabdolsaheb** [comment]
I see your point here. We are intentionally trying to keep the close button close its related content so the users eyes does not have to travel across the viewport to close the flash message. 

Ideally we could make the message and the close button stay within a similar container that footer stays on, but for now I think it is a non-issue.

**Comment by prathameshMoharkar** [comment]
can you assign this issue to me as I have taken part in HacktoberFest and I am best in Web Development.

**Comment by ieahleen** [comment]
@prathameshMoharkar welcome, please check the issues labeled with https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22

**Comment by Sanga-byte29** [comment]
please assign this issue i will resolve this

**Comment by ieahleen** [comment]
Hey @Sanga-byte29, thank you for your interested in contributing, but this issue is not open for contributions, please look at issues with labels https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only or https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted

**Comment by ahmadabdolsaheb** [comment]
I would close this issue for now to reduce confusion. We can discuss this further in the upcoming component library.
