### ISSUE TITLE
Help me with the map function in JS

### ISSUE THREAD

**Issue by phanlinhkhuong** [FreeCodeCamp/FreeCodeCamp#4759]
Challenge [Waypoint: Iterate over Arrays with map](http://www.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.map(function(value)%7B%0A%20%20return%20value%20%2B%203%3B%0A%7D)%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7Breturn%20newArray%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray.map(function(value){
  return value + 3;
})

// Only change code above this line.

(function() {return newArray;})();

```

**Comment by 3laa-Khalil-Alarabi** [comment]
```javascript
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray.map(function(value){
  return value + 3;
}); 

// Only change code above this line.

(function() {return newArray;})();
```
You were missing semicolon.

**Comment by ltegman** [comment]
@3laa-Khalil-Alarabi is correct. In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for help with challenges. Bugs should only be used for problems with the website.

Thanks and happy coding!
