### ISSUE TITLE
Remove bottom buttons in mobile layout for steps in RWD

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47597]
### Describe the Issue

Hey, what do you all say to removing the bottom buttons for the steps in the RWD course when in the mobile layout? There are three of them (Help, Reset, and Run) and these functions are already offered in the Step itself. So it's unnecessary duplication and will also free up just a little more screen space at the bottom.

### Affected Page

All steps in RWD course when in the mobile layout

### Steps to Reproduce

1. Open any step in any course in the new RWD course
2. Narrow your browser enough to trigger the mobile layout
3. Notice the three buttons anchored at the very bottom of the screen.

### Expected behavior

Don't display the three bottom buttons in the steps for RWD when in the mobile layout.

### System

- Device: Desktop
- OS: Linux (Fedora 36)
- Browser: Firefox
- Version: 106

**Comment by ahmadabdolsaheb** [comment]
I agree. That is a move in the right direction for now. The mobile experience need a redesign. 
We are moving in the following direction for the mobile app. I am wondering if we could reimplement some of that design's features in learn directly.

https://user-images.githubusercontent.com/4591597/184894491-5a2c5ec9-4cf3-405e-98d7-8d998f27aad3.png

**Comment by bbsmooth** [comment]
One caveat to this is that while the Steps in the RWD do not need the buttons in the tool panel at the bottom, the certification projects do need them.

**Comment by 6gaurav13** [comment]
Please asign this issue to me for correction
