### ISSUE TITLE
catphotoapp step 56 allows incorrect solution to be submitted

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#47602]
### Describe the Issue

The challenge on step 56 of the cat photo app project allows incorrect code to be submitted as correct.
The code that passes is:
```
            <input id="loving" type="checkbox">Loving
            <label for="loving" type="checkbox">Loving</label>
```
However the correct solution is:
```
            <input id="loving" type="checkbox"><label for="loving">Loving</label>
```
Link to the challenge: https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-56

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-56

### Your code

```
            <input id="loving" type="checkbox">Loving
            <label for="loving" type="checkbox">Loving</label>
```

### Expected behavior

This step is confusing enough without allowing multiple solutions to pass.
Suggest tightening up the checks for this one.

### Screenshots

![fcc-issue-step56](https://user-images.githubusercontent.com/35541470/192001074-91acd847-c092-4a56-a838-2ffba24e1de2.png)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: n/a

### Additional context

came to my attention on the forum that someone was sharing the incorrect solution.
(turns out that it was passing so I decided to open this issue)

**Comment by hbar1st** [comment]
Yes I started noticing other tests allowing additional code to pass as well. For eg step 2 cat photo to app allows me to define 6 lines of headers from h1 to h6 and it passes.

My thought though is that this person's solution doesn't show that they understood what to do here. Oh well. Also it can be frustrating to tell someone how to fix their code and then they say something like : oh you were wrong cause my code passed. 

That's just me though.

**Comment by Sagarw09** [comment]
Hello,I'm also getting error in this step 56 after writing the correct code it states that your code does not pass.

**Comment by Whisker-Warlock** [comment]
![Screenshot (32)](https://github.com/freeCodeCamp/freeCodeCamp/assets/169016444/f437487a-1233-4cc2-89db-65f6215a9b37)

This one
