### ISSUE TITLE
whats wrong with this

### ISSUE THREAD

**Issue by zunaidq07** [FreeCodeCamp/FreeCodeCamp#4761]
Challenge [Waypoint: Style Text Inputs as Form Controls](http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls?solution=%3Cform%20%3E%0A%20%20%3Cinput%20type%3D%22text%22%20name%3D%22name%22%20class%3D%22form-control%22%3E%0A%20%20%3Cbutton%20type%3D%22submit%22class%3D%22btn%20btn-primary%22%20%3E%20%3Ci%20class%3D%22fa%20fa-paper-plane%22%3Ebutton%3C%2Fi%3E%0A%20%20%3C%2Fbutton%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<form >
  <input type="text" name="name" class="form-control">
  <button type="submit"class="btn btn-primary" > <i class="fa fa-paper-plane">button</i>
  </button>

```

**Comment by CharleneBLN** [comment]
your closing tag</i> should be placed before the world "button" not after. Like below
<button type="submit" class="btn btn-primary" > <i class="fa fa-paper-plane"></i> button
  </button>

**Comment by ltegman** [comment]
You've deleted almost all the starting code for one. Please using the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for challenge questions. Bugs are only for problems with the website.

Thanks and happy coding!
