### ISSUE TITLE
Lack of a descriptive enough hint in step 40 of building skyline project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47616]
In the hint below it ask to add variable, but it's similar to how we ask colors to be added, which cased confusion to a camper

https://github.com/freeCodeCamp/freeCodeCamp/blob/2e4f1e31be28cd9d8287dd0fdf110aab4af11dde/curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98f0.md#L35

I propose, applying the same approach in ieahleen pull request to skyline variables name, #47609. Although it feels like giving answers outright, variables are case-sensitive and require specific syntax, which I think we should give their steps some lay way in the hints. 

original issue: https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/32714/en-esem?filter=basic&value=0#q=1153282

**Comment by ieahleen** [comment]
For that you need to use `assert.equal`.
First argument of `assert.equal` is the found value, and can be referenced with `--fcc-actual--`.
Second argument of `assert.equal` is the expected value, and can be referenced with `--fcc-expected--` in the hint text.

**Comment by Sboonny** [comment]
I thought `assert.equal` will trim the spaces, but as showing in the image below it doesn't. That looks like a nightmare, so let's ignore my original suggestion

![image](https://user-images.githubusercontent.com/88248797/192136451-96dce0ea-9b93-4e8d-91bc-0beab501de18.png)

the camper mentioned the lack of `var` keyword, what about adding in the hints something like

> You should give the `background` a `linear-gradient` starting from `--building-color1` variable.
