### ISSUE TITLE
Cat Photo App Step 44 allows multiple type attributes

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47627]
### Describe the Issue

Step 44 will pass if the new radio `input` is given multiple `type` attributes. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-44

### Your code

This will pass:

```
<input type="radio" type="text"> Indoor
```

### Expected behavior

Step should fail if there is more than one `type` attribute, even if they all have the value `radio`.

### System

- Device: Desktop
- OS: Linux (Fedora 36)
- Browser: Firefox
- Version: 104.0.2

**Comment by ppeters0502** [comment]
I was playing around with this issue, and was able to replicate it locally. Looks like the .getAttribute() JS function only returns the first attribute in an HTML element, so as long as the first "type" attribute is radio it passes the tests.
I was able to fix this with a regex check that looks explicitly for a type="radio" and checks for any additional "type" text in the input. I feel like this could be bypassed if someone had a type attribute at the beginning of the element, some additional attributes, and then a second type attribute.

Maybe just simplify the whole thing by checking for the number of attributes on the input, and if it's more than one, throw an error? It wouldn't be specific to more than one type attribute, but could be like "Your new `input` element should only have one attribute, the `type` attribute" or something like that.

**Comment by ShaunSHamilton** [comment]
At the end of the day, the output is correct - parsed HTML is valid.

**Comment by bbsmooth** [comment]
According to the [13.1.2.3 Attributes](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2):

"There must never be two or more attributes on the same start tag whose names are an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for each other."

**Comment by ieahleen** [comment]
We kind of go back to #46463

In this specific case we can patch it up with a test that check there is only one attribute of that type.

**Comment by nayabatir1** [comment]
Is this issue resolved ?

**Comment by ieahleen** [comment]
@nayabatir1 no, but there is a PR open that targets this issue

**Comment by nayabatir1** [comment]
> @nayabatir1 no, but there is a PR open that targets this issue

From my past experience it's better to not create pr if an issue already has  a pr.
Do let me know if that pr is not up to the mark and new pr are welcome.

**Comment by nayabatir1** [comment]
Hey I did some research and found that 
* even if add duplicate attribute is added, DOM node only consider the first one and just ignore the rest. [reference](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-duplicate-attribute)
* 'getAttribute()` will return only first attribute

I'm not sure how to validate this.

![image](https://user-images.githubusercontent.com/91016903/194399560-be2b0baa-4444-4978-ac0d-6f7418a3522f.png)

**Comment by ShaunSHamilton** [comment]
> only consider the first one and just ignore the rest.

This is why I disagree with trying to test for this - there are an infinite number of incorrect ways Campers can get the correct output.

> I'm not sure how to validate this.

We would need to use RegEx.

**Comment by nayabatir1** [comment]
One cannot test by accessing DOM node, inorder o test it we need to check actual text that user has entered in the input box.

**Comment by bbsmooth** [comment]
> This is why I disagree with trying to test for this

I completely understand this sentiment. If you want to close this issue and forget about it, it won't hurt my feelings :smiling_face_with_tear: But the specs definitely do not allow it and the W3 validator will throw an error. But I suppose you could have this problem with every step. I think @ieahleen was onto something and this is really more an issue of whether we should validate the HTML. So ya, I vote to drop this issue.

**Comment by ShaunSHamilton** [comment]
As such, I am closing this in favour of the previously linked PR tracking possible HTML validation. _no hurt feelings_
