### ISSUE TITLE
Tweet function for particular quotes

### ISSUE THREAD

**Issue by yuyao17** [FreeCodeCamp/FreeCodeCamp#4762]
I want a tweet function to tweet out the speicific quote thats randomly generated.

http://codepen.io/yuyao17/pen/YymPrW

**Comment by ltegman** [comment]
Github issue are for reporting problems with the website. You can ask for help with this in the [Zipline Help Chat](https://gitter.im/FreeCodeCamp/HelpZiplines)

Thanks and happy coding!
