### ISSUE TITLE
Cafe Menu Steps 13: Instructions are not clear

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47629]
### Describe the Issue

In step 13 the tests will fail if the two new selectors aren't added to the existing `style` element but this is not made clear in the instructions. If the user adds the selectors in a new `style` element then the hint they receive is not accurate.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-13

### Your code

This is valid code but is not what the tests are expecting and thus fails.

```
<style>
      h1 {
        text-align: center;
      }
    </style>
    <style>
      h2 {
        text-align: center;
      }
    </style>
    <style>
      p{
        text-align: center;
      }
    </style>
```

The hint for this is "You should add a new `h2` selector" which is not accurately stating the real problem (that the tests want the new selectors to be in the same `style` element as the `h1`).

### Expected behavior

If we do want to enforce that all of these selectors should be in the same `style` element then update the instructions to make that clear. Also, add additional test to check for this and give an appropriate hint.

### System

- Device: Desktop
- OS: Linux (Fedora 36)
- Browser: Firefox
- Version: 104.0.2

**Comment by bbsmooth** [comment]
I guess I should offer a suggestion for the new wording on the instructions.

> In the previous step, you used a type selector to style the h1 element. Using this same `style` element, center the h2 and p elements with a new type selector for each one.

**Comment by rakzool** [comment]
> ### Describe the Issue
> In step 13 the tests will fail if the two new selectors aren't added to the existing `style` element but this is not made clear in the instructions. If the user adds the selectors in a new `style` element then the hint they receive is not accurate.
> 
> ### Affected Page
> https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-13
> 
> ### Your code
> This is valid code but is not what the tests are expecting and thus fails.
> 
> ```
> <style>
>       h1 {
>         text-align: center;
>       }
>     </style>
>     <style>
>       h2 {
>         text-align: center;
>       }
>     </style>
>     <style>
>       p{
>         text-align: center;
>       }
>     </style>
> ```
> 
> The hint for this is "You should add a new `h2` selector" which is not accurately stating the real problem (that the tests want the new selectors to be in the same `style` element as the `h1`).
> 
> ### Expected behavior
> If we do want to enforce that all of these selectors should be in the same `style` element then update the instructions to make that clear. Also, add additional test to check for this and give an appropriate hint.
> 
> ### Screenshots
> _No response_
> 
> ### System
> * Device: Desktop
> * OS: Linux (Fedora 36)
> * Browser: Firefox
> * Version: 104.0.2
> 
> ### Additional context
> _No response_

i have and idea we can change the hint to say something like "use two seperate selectors for type : h2 and the paragraph tag" if no one is working on the issue i wold like to give it a try .
