### ISSUE TITLE
Falsy Bouncer

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#47622]
### Describe the Issue

The instructions imply that the original array must be modified, while we are fine with a non-mutating approach.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/falsy-bouncer

### Expected behavior

Clearer instructions.

### System

All

**Comment by ShaunSHamilton** [comment]
Would it be ok to just:

> Return all falsy values from an array.

**Comment by jeremylt** [comment]
That would mean reversing output the test suite, but I think it would result in covering the same ideas.

**Comment by nayabatir1** [comment]
Hi,
I would like to work on this issue.

**Comment by jeremylt** [comment]
We don't assign issues. We accept the first complete PR that addresses the issue adequately.

I'm ready to open this up to contributions, but let's let other maintainers chime in here.

**Comment by nayabatir1** [comment]
Can tell me what exactly needs to done here. As per task description `remove falsy values`, but above comments says return falsy values

**Comment by jeremylt** [comment]
We still have not decided on a final path forward and opened this up for contribution yet. Please be patient.

**Comment by naomi-lgbt** [comment]
> The instructions imply that the original array must be modified, while we are fine with a non-mutating approach

I feel like we should also change this to expect a non-mutating solution only.

**Comment by jeremylt** [comment]
I would be good with that.

**Comment by naomi-lgbt** [comment]
Going to open this up for first timers. The fix involves two changes:

> Remove all falsy values from an array.

Update this line to something like `Remove all falsy values from an array. Return the new array, do not mutate the original array.`

Add a test to check that the function is non-mutating.

**Comment by SaarthakMaini** [comment]
I can make the necessary changes.

Where do I have to add the test exactly?
