### ISSUE TITLE
Touching settings other than Campfire Mode triggers the sound

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#47626]
### Describe the Issue

When Campfire Mode is on, actions like opening the Settings page, touching any fields under "Account Settings for [username]", or closing the flash message banner triggers the Campfire Mode sound. 

I'm note sure which ones are expected sounds, but making sounds on unfocusing the fields or closing the banner feels too much to me.

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

You will hear the sound at the steps 1, 2, 4 but I'm not sure if we want the sound here

1. Go to "Settings"
2. Change the value of any field under "Account Settings for [username]" section and unfocus
3. Save any settings (You will hear the sound here too but I think this is expected)
4. Close the "We have updated you preferences" banner

### Expected behavior

Remove unwanted sounds

### Screenshots

https://user-images.githubusercontent.com/25644062/192288573-8cb6b279-d83b-4509-9142-33953499590b.mp4

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 105.0.5195.127

**Comment by ShaunSHamilton** [comment]
All of these sounds are expected and configured here: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/utils/tone/index.ts#L8

**Comment by wojtekxtx** [comment]
@ShaunSHamilton
Fuck FCC

**Comment by wojtekxtx** [comment]
Map PIS !!!!!!!!!!!!!!!!!!!!!!!!

Fuck THIS FUCKED UP SHIT
