### ISSUE TITLE
Kjnjikn

### ISSUE THREAD

**Issue by hackathon19** [freeCodeCamp/freeCodeCamp#47637]
### Describe the Issue

Jjjnunnbhhh

### Affected Page

Jjhhnn

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Ijjjnnbjnnn

### Screenshots

Kkmnnjmnn

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Jjnnjn n

**Comment by ShaunSHamilton** [comment]
Please do not open invalid issues/PRs. This is creating noise, and potentially disturbing ~8500 developers who watch this repo.

**Comment by hackathon19** [comment]
Can you tell me how to contribute then i am beginner. I wants to contribute ?

**Comment by ShaunSHamilton** [comment]
@hackathon19 

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by hackathon19** [comment]
Can i create my own label with issue like beginner ?

**Comment by ShaunSHamilton** [comment]
> Can i create my own label with issue like beginner ?

No. Members of the freeCodeCamp organisation triage issues, and add the labels. Please read the above linked contributors docs.

> If you have any issues with contributing, be sure to join us on the [contributors channel](https://discordapp.com/channels/692816967895220344/718214639669870683), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by hackathon19** [comment]
How to become member of freecodecamp organisation?

**Comment by hackathon19** [comment]
Can i get job if i contribue?

**Comment by ShaunSHamilton** [comment]
@hackathon19 Please make use of our dedicated channels to have this sort of discussion: [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
