### ISSUE TITLE
Cat Photo App - Revenge of Step 12

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#47631]
### Describe the Issue

Step 12 continues to plague users. I would be really good if we can get them to understand "copy-paste the previous anchor element into this new spot" without saying that explicitly.

(Follow-up from discussion on Discord with @bbsmooth @ieahleen @hbar1st)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Expected behavior

Possible extended wording

> You have now created a link with the text `cat photos`. The words `cat photos` are underlined next to the image in the preview now. You can click on the link now.

> Now, turn the words `cat photos` inside of your `p` element into a new link to `https://freecatphotoapp.com` by placing these words inside of a new anchor element.

### System

All

**Comment by jeremylt** [comment]
It also might help to change Step 11 to put different text inside of the first anchor element so they are easier to tell apart?

**Comment by hbar1st** [comment]
My suggestion for the second paragraph:

Now, turn the words `cat photos` inside of your `p` element into a new link by placing these words inside of a new anchor element.

Use `https://freecatphotoapp.com` as the href value.

**Comment by jeremylt** [comment]
Typically we put the instructions all on one paragraph.

**Comment by hbar1st** [comment]
Like this?

Now, turn the words cat photos inside of your p element into a new link by placing these words inside of a new anchor element. Use https://freecatphotoapp.com as the value of the href.

**Comment by jeremylt** [comment]
Perhaps

Now, turn the words cat photos inside of your p element into a new link by placing these words inside of a new anchor element. Add a href attribute with the value of https://freecatphotoapp.com to this anchor element.

If we go the route of being super blatant.

**Comment by hbar1st** [comment]
I haven't had trouble with people saying they don't know what to put in the href.
Just trouble with people missing the whole point of this exercise (last two words only become links) And people deleting the rest of the text plus people adding extra text links of cat photos. 
(I don't care about the small mistakes they do just the big misunderstandings that take a long time to fix, and/or that make me instruct them to restart the step which feels like a cop out because the mess is too big to be fixed).

**Comment by jeremylt** [comment]
So we don't need to be explicit about the href?

Back to

> Now, turn the words cat photos inside of your p element into a new link to https://freecatphotoapp.com by placing these words inside of a new anchor element.

**Comment by hbar1st** [comment]
I feel the placement of the href piece in the middle is hiding the intent (which is to put an anchor around the words in question) . That's why I wanted to move it down.

**Comment by jeremylt** [comment]
Ah. So assuming they don't know what 'link' means?

> Now, place the words cat photos inside of your p element inside of a new anchor element linking to https://freecatphotoapp.com

I don't love that wording. I think that version is worse but I'm not sure how to eliminate the idea of 'link'.

**Comment by bbsmooth** [comment]
My first try:

> In the previous step you turned the words `cat photos` into a link by wrapping them with opening and closing anchor (`a`) tags. You can also do the same to words inside of an element, such as a `p` element.

> In the text of your `p` element, turn the words `cat photos` into a link to `https://freecatphotoapp.com` by wrapping these words with the appropriate opening and closing anchor (`a`) tags.

I do agree that we should use different words for step 11, so replace `cat photos` in the first paragraph with whatever words we ultimately decide on for that step.

I think that people are not making the connection from the previous steps that they have just turned a group of words into a link, so I think we should reiterate this at the beginning of the first paragraph. I think this is more important than pointing out that the link is now underlined in the preview, so to keep the instructions brief I removed that part completely. But if the feeling is that that is an important point to make then I'm sure we can work it back in.

I also felt like we should use the same verbiage between the first and second paragraphs, so I went with "wrapping opening and closing anchor tags" in both. But I'm fine with using "nesting inside a new anchor element" for the second paragraph. It might be slightly more confusing, but we have already covered nesting in a previous step, so it shouldn't be a surprise.

>  I'm not sure how to eliminate the idea of 'link'.

A link is one of the most basic features of the web. Everyone should know what a link is. I don't think think we need to avoid that terminology at all. Or maybe I am not understanding that sentiment correctly?

**Comment by jeremylt** [comment]
We have had trouble with (a) leading to (a href=...)

Perhaps

> wrapping them with opening and closing anchor (a) tags

Could be

> placing them between opening and closing anchor tags

I agree that re-iterating anchor=a is good but I'm not sure the best way to do it

**Comment by bbsmooth** [comment]
> placing them between opening and closing anchor (`a`) tags

That works for me. Probably the better choice since we use this verbiage in step 11.

**Comment by bbsmooth** [comment]
> I agree that re-iterating anchor=a is good but I'm not sure the best way to do it

Ya, it's unfortunate that everyone calls these links but yet we use the `anchor` element to create them and to compound that confusion, there is an actual `link` element :smile: In steps 10 and 11 we use "anchor (`a`) element" so I think for consistency's sake we should do the same in this step. Perhaps we only need to do it in the first paragraph and we can refer to them as "anchor tags" or "anchor element" in the second paragraph?

**Comment by hbar1st** [comment]
> Ah. So assuming they don't know what 'link' means?

Not at all. I am only saying the URL is interrupting the sentence or lessening the directness/succinctness of the sentence when it is in the middle. 

Compare these two first sentences:
> Now, turn the words cat photos inside of your p element into a new link by placing these words inside of a new anchor element. 

vs.

>Now, turn the words cat photos inside of your p element into a new link to https://freecatphotoapp.com by placing these words inside of a new anchor element.

(In the first sentence we say "new link by" while in the second "new link to")

The "to" bit is better left to the end (as per my last suggestion) so as to keep the emphasis on the "how" of it. (How should the link get created? By placing these words inside of a new anchor element)


So if I combine the thoughts expressed by Bruce then we could rewrite to:(using the quotes just to show the areas that would be highlighted normally)

---

In the previous step you turned the words "cat photos" into a link by wrapping them with opening and closing anchor (a) tags. You can also do the same to words inside of an element, such as a "p" element.

Now, turn "cat photos" inside of your "p" element into a new link by placing them between opening and closing anchor tags. Use "https://freecatphotoapp.com" as the value for the "href" attribute.

**Comment by jeremylt** [comment]
I am still not sure that is needed.

We don't have to get this perfect and make this completly simple all in one shot. I think we the should give the learners a chance to synthesize the concepts 'anchor element with the href attribute = value' into 'link to value'.

I think this provides a better explanation of what happened than we currently have and gives the idea that we want them to do it again.

> In the previous step you turned the words `link to cat pictures` into a link by placing them between opening and closing anchor (`a`) tags. You can do the same to words inside of an element, such as a `p` element.

> In the text of your p element, turn the words `cat photos` into a link to `https://freecatphotoapp.com` by placing these words inside of opening and closing anchor (`a`) tags.

We would then also change Step 11 to use different text. Perhaps `link to cat pictures`.

**Comment by Dorfieeee** [comment]
> It also might help to change Step 11 to put different text inside of the first anchor element so they are easier to tell apart?

I can relate to this. The words `cat photos` and link `https://freecatphotoapp.com` being there already might make them question the given task. They will see those two *key words* there already and completely ignore the fact they should change something inside the `<p>` element. 
They may be also thinking: "They don't expect me just to copy-paste it, right?" and get stuck there.
