### ISSUE TITLE
Step 44 NRWD Building Registration Form accepts CSS with a missing semi-colon

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#47642]
### Describe the Issue

the NRWD Building Registration Form curriculum step 44 accepts a solution that is missing a semi-colon.
The solution given to it is:
```
fieldset{border:0;padding-left:0; padding-right:0; padding-top:2rem; padding-bottom:2rem}
```
When I put this code in to try it, i was expecting it to fail as it had a missing semi-colon at the end of the last style however, it passed the test and I was allowed to proceed to the next step.

Link to forum question for ref: https://forum.freecodecamp.org/t/new-responsive-web-design-building-registration-form-step-44/557880

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-44

### Your code

```
fieldset{
  border:0;
  padding-left:0; 
  padding-right:0; 
  padding-top:2rem; 
  padding-bottom:2rem
}
```

### Expected behavior

I think the step should prevent submission if the answer is missing a semi-colon. (And give an appropriate hint of course)

### Screenshots

![delete-this](https://user-images.githubusercontent.com/35541470/192536286-f103308b-a85d-406c-be3b-e6831fa433f6.png)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: N/A

**Comment by ShaunSHamilton** [comment]
This is valid CSS. The final CSS declaration in a rule does not need the semi-colon: https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#css_declaration_blocks
