### ISSUE TITLE
Bonfire: Confirm the Ending - Solvable with ES6 endsWith function

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4764]
[ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) shortens the answer to `return str.endsWith(target);`.  Fine by me, but judging from the other bonfires I'd guess you were looking for more challenging questions?

Challenge [Bonfire: Confirm the Ending](http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending?solution=function%20end(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20return%20str.endsWith(target)%3B%0A%7D%0A%0Aend(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function end(str, target) {
  return str.endsWith(target);
}
end("Bastian", "n");
```

**Comment by SaintPeter** [comment]
This is a good observation.  We do not yet have the infrastructure support (mocks and spies) to disallow the usage of a specific function, but it is something we have on our roadmap.  I'll keep this one open for the future.

**Comment by tomByrer** [comment]
Thanks for the fast reply.
I was thinking a different bonfire be replaced here.  Perhaps that exercise to be moved to an "Advanced JS / ESNext" lesson section if/when you flesh that out.

**Comment by ltegman** [comment]
I think for this particular bonfire a good stopgap is to just setup a regex test looking for the use of `endsWith` in the challenge. There's not reason a user should use this string in a solution unless they are using the ES2015 function and we can warn them in the sidebar just in case they do.

**Comment by tomByrer** [comment]
> There's not reason a user should use this [RegEx] string in a solution 

It seems that `str.endsWith(target)` is *much* easier to read than `/#$/.test(str)` or `str.indexOf(suffix, str.length - suffix.length) !== -1;`.  You might be used to RegEx like I'm used to ASM, but doesn't mean we should write that code when more expressive language is available.  Good comments help, but I'd have a feeling a code reviewer would prefer `endsWith`.

**Comment by ltegman** [comment]
Sure, but this bonfire isn't about teaching users ES2015, it's about having them think through the algorithm to solve this problem themselves. Looking up ES2015 features is a trivial thing to do on your own once you have a good foundation for thinking through code. These lessons should be about nurturing that foundation by having users think through solving problems.

**Comment by battaile** [comment]
Using the problem solving approach prescribed by the site itself is going to lead the user to endsWith() though. If the goal is just to get them to use substr() et al, it seems like a better approach might be coming up with a problem that can't be easily solved with an ES6 function...  "see if the test text occurs anywhere past the midpoint of the string" etc.

**Comment by utkarshyadav5** [comment]
Challenge Bonfire: Confirm the Ending has no issues.
It can easily be solved using the function given in hint.
The solution is:

function end(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var len=target.length;
  if(target==str.substr(-len,len)){
    return true;
  }else{
    return false;
  }
  
}

end("Bastian", "n");

**Comment by adius** [comment]
@battaile I'm on your side! Prohibiting the use of a clearly better solution would be utterly nonsense.

**Comment by kamilejones** [comment]
hi, wanna leave my code,

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  return str.substr((-1)*target.length) == target;
}

confirmEnding("Bastian", "n");
