### ISSUE TITLE
Incorrect description on Waypoint: Understand Boolean Values

### ISSUE THREAD

**Issue by Sayanc93** [FreeCodeCamp/FreeCodeCamp#4765]
"In computer science, data structures are things that hold data. JavaScript has seven of these. For example, the Number data structure holds numbers. Let's learn about the most basic data structure of all: the Boolean."

Well I think Number, Boolean and the other seven that are not mentioned are essentially "Data types" rather than being "Data structures". Data structure are containers that hold data whereas data types describe data.

The details on the description might baffle newbies as they move along. Correct me if I'm wrong. :)

**Comment by SaintPeter** [comment]
@Sayanc93 You are technically correct, which we all know is the best kind of correct.  :wink:
Generically, though Data Types are a subset of Data Structures.

I am currently working on a complete rewrite/revamp of the Basic Javascript curriculum.  I was going to rewrite this one anyway, I'll take your suggestion under advisement.

**Comment by Sayanc93** [comment]
Awesome :smile:

**Comment by bugron** [comment]
Done. Closing this issue. See https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L38.
