### ISSUE TITLE
Remove user data when set to private

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#47655]
### Is your feature request related to a problem? Please describe.

Someone made a suggestion recently that kind of got lost, it was something like this... We want to remove potentially sensitive information from the database when campers set that information to private. For example, someone's name I suppose. When they set it to private, there's an expectation that nobody can see it - we still store that information in the database even though it's private. If our database were compromised, someone could have access to it.

Here's are all the fields in the privacy settings:
My profile
My name
My location
My about
My points
My heatmap
My certifications
My portfolio
My timeline
My donations

-Many of these we cannot delete from the database: `points`, `heatmap` (created from the points array), `certifications` (created from completed challenges array), `timeline` (created from completed challenges array), `donations`
-Ones we maybe can: `name`, `location`, `about`, `portfolio`
-The `profile` setting is unique in that it just hides everything
Side note: campers email addresses are also stored in the database - which we cannot delete or you couldn't log in

### Describe the solution you'd like

The solution that comes to mind for this is to remove the private/public toggle buttons for all of these fields. They will always be public - if a camper wants to make any of them private, they can just delete their name, location, about, or portfolio items. We could maybe add a delete button next to those fields or something.

The profile toggle would need a popup maybe? that says your name, about, etc. will be deleted if you set your profile to private

### Additional context

Couple side thoughts that we can probably make separate issues for...

- We have campers emails, which we need to save so they can log in - but we don't really give them an option to display it on their profiles. We could add an option for them to do that.

There's a few things on a profile:
![Screen Shot 2022-09-28 at 6 27 55 PM](https://user-images.githubusercontent.com/20648924/192905923-5b5f9f7e-1d4a-46cf-a925-b80ec3fb49c3.png)
- The joined date is tied to the "About" privacy setting. Hide your about, and that gets hidden. This is not intuitive. I believe that is the date of your first point, which you get when you create your account.
- The top contributor status doesn't have a setting to hide it.

**Comment by Aman123lug** [comment]
@moT01 i can work on it

**Comment by ojeytonwilliams** [comment]
@moT01 this makes a lot of sense. There was one issue, though.

What do we do with currently private stuff?  We can't (to my knowledge) delete people's data without their consent, so we'd need a way to handle the fact that this may be part of their user object. Both on the api and the client.

**Comment by moT01** [comment]
We currently just keep the info in the database. e.g. Fill in your info on settings - name, location, etc - set your profile to private - the info still shows up in all those forms from the database. Note that campers do have the option to delete the data themselves if they don't want it in the database.

I don't like randomly deleting campers info either - I wouldn't like it.

Trying to think through it... we remove those toggle switches, keep campers info and privacy settings in the database for now so we can still have the info, display it in those forms, and keep it private. They wouldn't have a switch to make it public anymore, so we would need a way to communicate to them what we are doing. We could have some logic that checks if they have that info and if it's private, then maybe a popup that says something like "Your X is private and not shown on your profile [make it public] [delete my info]" - so we can then either set it to public or delete it. It would show up the next time they visit their settings page and they would not be able to change any of those form fields until they resolved that popup. If they click delete it, we delete the info and set the private to public in the database. If they click make public, we just set it to public. The flags for all that info would essentially become one directional I guess. You can set it to public, but never again back to private - you can only delete the info after that.

Campers with that info set to public wouldn't have the option to set it to private anymore, just delete it.

**Comment by ashutoshshisodia** [comment]
Can we encrypt the entities and update them in database that the user wants to be made private? That way, we would not end up deleting them and it would not be an issue even if the database gets compromised.
Also, we can decrypt them to plain text anytime we want, or when the user wants.

**Comment by sanyamgandhak** [comment]
Hi there , Please assign to me

**Comment by ShaunSHamilton** [comment]
@sanyamgandhak 
Only issues with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by souravsasmal01** [comment]
Hello sir , can you assign this issue to me?

**Comment by moT01** [comment]
See [the comment above](https://github.com/freeCodeCamp/freeCodeCamp/issues/47655#issuecomment-1264387328) @sanyamgandhak.

We are still figuring out how we want to fix this, I would look for another issue. Thanks for your interest in contributing 🎉

**Comment by scissorsneedfoodtoo** [comment]
Closing as stale.
