### ISSUE TITLE
Turn a quote into code block in Create RPG game project 

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47661]
The quote block is harming translation, because it shows as a translatable string while it shouldn't be.

Here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/f80e34a9509f3208c01524ea25dd573fcacbe760/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a2401b9842721796b72850.md#L12

this quotes should turn into code block

> Welcome to Dragon Repeller. You must defeat the dragon that is preventing people from leaving the town. You are in the town square. Where do you want to go? Use the buttons above.

into 

```md
Welcome to Dragon Repeller. You must defeat the dragon that is preventing people from leaving the town. You are in the town square. Where do you want to go? Use the buttons above.
```

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by Anuran12** [comment]
Hi @Sboonny  can you assign me. 

But you have to guide me because i am newbie in open source. : )

**Comment by Sboonny** [comment]
we don't give assignment, feel free to open PR, after you have read our contribution guidelines

**Comment by ieahleen** [comment]
@Anuran12 the contributing docs says a lot — for more help reach out in forum or discord as said above

**Comment by DylanDevelops** [comment]
> Hi @Sboonny can you please assign it to me.
> 
> But you have to guide me because i am a newbie in open source. : )

Read through this and if you have any questions ask away! https://contribute.freecodecamp.org/#/

**Comment by ShrishPande** [comment]
Is this issue open 
can you guide me a little it's my first time?

**Comment by Sboonny** [comment]
There is a pull request addressing the change, so there is no need to open a new pull request.

You can check out [article about markdown](https://www.freecodecamp.org/news/markdown-cheat-sheet/), that issues was about switching to different markdown format
