### ISSUE TITLE
dev  environment: docs and challenge editor open on same port

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47663]
The documentation opens on port 3200

The challenge editor uses ports 3200/3300

There is a clash there. It may need to move one of the two

**Comment by DylanDevelops** [comment]
What do we have to change to fix this issue?

**Comment by naomi-lgbt** [comment]
Heya @DylanDevelops,

The quickest fix would probably be to change this line:

https://github.com/freeCodeCamp/freeCodeCamp/blob/2c4b0adf4163bd01ce7ae2aeb6bd5649dc557d37/package.json#L68

Replacing 3200 with 3400.

**Comment by ieahleen** [comment]
And here! So the documentation is updated together
https://github.com/freeCodeCamp/freeCodeCamp/blob/2c4b0adf4163bd01ce7ae2aeb6bd5649dc557d37/docs/how-to-work-on-the-docs-theme.md?plain=1#L79

**Comment by DylanDevelops** [comment]
I can make this change if you wouldn't mind!

**Comment by naomi-lgbt** [comment]
Thanks for your interest in contributing! You've already contributed to our codebase, however - we prefer to leave https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only issues for folks who are new to our codebase so they have a chance to familiarise themselves.

**Comment by DylanDevelops** [comment]
> Thanks for your interest in contributing! You've already contributed to our codebase, however - we prefer to leave [ first timers only](https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only) Open for anyone doing contributions for first time. You do not need permission to work on these. issues for folks who are new to our codebase so they have a chance to familiarise themselves.

that's fair! I guess now I know how to do it so it wouldn't make sense for me to contribute.

**Comment by Sboonny** [comment]
Reopened because the docs section still need to be updated

If you're going to update the docs, update the English file only

**Comment by ShrishPande** [comment]
is this issue still open

**Comment by Sboonny** [comment]
yes @ShrishPande, the docs [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/2c4b0adf4163bd01ce7ae2aeb6bd5649dc557d37/docs/how-to-work-on-the-docs-theme.md?plain=1#L79) tells people to expect port:3200, while we are using port:3400, which may cause confusion. opening a pull request to change the docs will solve this issue for good

**Comment by ShrishPande** [comment]
@Sboonny do you mind checking it again ,because I think it has already been edited
its showing 3400 now

**Comment by Sboonny** [comment]
@ShrishPande no worries, can you link the change because the documents is talking about port:3200

Here is the docs, that I am talking about

https://github.com/freeCodeCamp/freeCodeCamp/blob/2c4b0adf4163bd01ce7ae2aeb6bd5649dc557d37/docs/how-to-work-on-the-docs-theme.md?plain=1#L79

**Comment by ShrishPande** [comment]
@Sboonny I was talking about the main branch ,the link you sent just now ,it is not main branch

**Comment by ShrishPande** [comment]
@Sboonny so do I have to make changes in this branch
??

**Comment by Sboonny** [comment]
Nope, I was simply confused

https://github.com/freeCodeCamp/freeCodeCamp/blob/85b5254c48cb228b7604ec89804188b79e5fd390/docs/how-to-work-on-the-docs-theme.md#L79

> The documentation site should be available at <http://localhost:3400>
