### ISSUE TITLE
Bonfire Smallest Common Multiple: First test case handled but doesn't pass

### ISSUE THREAD

**Issue by MrSkinny** [FreeCodeCamp/FreeCodeCamp#4766]
It says that if a the function is run without an argument it should return a number.  My code ensures if the argument passed in is undefined, it returns 0.  I've verified that 0 is being returned.  Have also tried other numbers, but the test is not passing.

Challenge [Bonfire: Smallest Common Multiple](http://www.freecodecamp.com/challenges/bonfire-smallest-common-multiple?solution=function%20smallestCommons(arr)%20%7B%0A%20%20if%20(arr%20%3D%3D%3D%20undefined)%20return%200%3B%0A%20%20return%20arr%3B%0A%7D%0A%0AsmallestCommons()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function smallestCommons(arr) {
  if (arr === undefined) return 0;
  return arr;
}

smallestCommons();

```

**Comment by ltegman** [comment]
The code that this test actually runs is `smallestCommons([1,5])`, which in your code returns an array.

I'm not a fan of these test cases that we have on some of these challenges where the first test case that checks for a type doesn't actually list the exact code it's running.

I'm leaving this issue open. If no one else does it before then I will go look for all these generic test messages later tonight or tomorrow and replace them with messages that actually state the test being run.
