### ISSUE TITLE
on the Waypoint Activities, it does not allow me to access and change certain parts of my code

### ISSUE THREAD

**Issue by wisekrish** [FreeCodeCamp/FreeCodeCamp#4767]
I am currently in the lesson:  style text inputs as form controls. It requires me to add another class to an already existing piece of code. However, when I click to go to that specific part of the code, it does not go there, and the screen freezes.

**Comment by ltegman** [comment]
I am not able to reproduce this bug. If you are not already try using the Chrome browser with no extensions installed, as that is the only browser officially supported by Free Code Camp.

Thanks and happy coding!
