### ISSUE TITLE
Small fixes notified on crowdin

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47686]
Just transcribing issues from crowdin.

In this line:
https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/06-quality-assurance/quality-assurance-and-testing-with-chai/assert-deep-equality-with-.deepequal-and-.notdeepequal.md?plain=1#L11
There is an extra comma before the anchor element that has to be removed.

In this line:
https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/discordian-date.md?plain=1#L29
There is an incorrect use of parenthesis.

It should become
> Note that the day Chaos 1, 3188 YOLD the Discordian calendar is the day January 1, 2022 in the Gregorian calendar.

---

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/06-quality-assurance/quality-assurance-and-testing-with-chai/assert-deep-equality-with-.deepequal-and-.notdeepequal.md
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/discordian-date.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by prajwal-144** [comment]
Hey, I would like to work on this.
