### ISSUE TITLE
Missing backticks around variables

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47687]
This markdown table is missing backticks around the variables (third column).
https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer.md?plain=1#L29-L42

---

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:
1. https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by KanishkKhurana** [comment]
Hi @ieahleen , this seems like an issue that i can handle. I am new to freecodecamp repository and would love to contribute

**Comment by ieahleen** [comment]
@KanishkKhurana Thank you for your interest! I suggest looking at issues that do not have linked PRs already
