### ISSUE TITLE
Typo fixes

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47689]
In both the sentences on this line the word `href` should be surrounded with backticks:
https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md?plain=1#L23

In this line there is a period (full-stop) where there should be a comma.
https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/24-game.md?plain=1#L54

---

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/d490c828197d68749e63ddaa5509fa1e0df20476/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/24-game.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by slayeh17** [comment]
Hello, I want to work on this.

**Comment by amitturare** [comment]
Heyy, is this assigned to anyone?

**Comment by patil-prathamesh** [comment]
I will work on this.

**Comment by Aaroh1** [comment]
Hey! I would like to work on this issue.

**Comment by maddy1381** [comment]
Hi I have fixed the issue and you can find the PR here #47722

**Comment by dhruvjain896** [comment]
Is this issue available or has it been resolved?
