### ISSUE TITLE
Update data viz demo project URL's

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#47691]
### Describe the Issue

All the data viz projects were created on our .rocks domain. We just need to replace the codepen URL's with the new addresses in the curriculum files of those five projects.

Here's the URL's:
https://bar-chart.freecodecamp.rocks/
https://scatterplot-graph.freecodecamp.rocks/
https://heat-map.freecodecamp.rocks/
https://choropleth-map.freecodecamp.rocks/
https://treemap-diagram.freecodecamp.rocks/

And the [project files are here](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/04-data-visualization/data-visualization-projects)

**Comment by IvanoskiHarmonia** [comment]
Hey @moT01,

Just to make sure you want this https://codepen.io/freeCodeCamp/full/GrZVaM replaced with  https://bar-chart.freecodecamp.rocks/ ?

**Comment by Shreyas250503** [comment]
@moT01 
I want to contribute to this project.
Please assign me this task.

**Comment by ieahleen** [comment]
@Shreyas250503 thank you for your interested in contributing, but this issue is not open for contributions, please look at issues with labels https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only or https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted
