### ISSUE TITLE
Basic JavaScript - Understanding Uninitialized Variables- issue with this lesson

### ISSUE THREAD

**Issue by sfbaygrl** [freeCodeCamp/freeCodeCamp#47736]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
"was having an issue with this lesson asked for help on forum and was told to open an issue here, screen shot provided below"
**To Reproduce**

**Expected behavior**

**Screenshots**
![free code issue](https://user-images.githubusercontent.com/108196927/193404692-64b314af-945e-4b70-8bd7-4a8fd3d7204b.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ieahleen** [comment]
The challenge passes with this code, please return to the forum and follow the debugging steps offered there.
