### ISSUE TITLE
Typos in challenges description

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47738]
1. This sentence is missing a word
https://github.com/freeCodeCamp/freeCodeCamp/blob/762945baf260afde16f4fd5191ce50a1dc20e3cc/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa2999ec27ec516655eba6.md?plain=1#L20

---

2. Here the word `gallery` should not have quotes inside the code block
https://github.com/freeCodeCamp/freeCodeCamp/blob/762945baf260afde16f4fd5191ce50a1dc20e3cc/curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/61537c9eecea6a335db6da79.md?plain=1#L10

---

3. In this sentence
> The `"from"` array should contain the original names and the `"to"` array

`from` and `to` should not have quotations in the code block
https://github.com/freeCodeCamp/freeCodeCamp/blob/762945baf260afde16f4fd5191ce50a1dc20e3cc/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/state-name-puzzle.md?plain=1#L18

**Comment by Shubham-Rasal** [comment]
Working on it!

**Comment by Shubham-Rasal** [comment]
Hey @ieahleen ,
Please can you go through the changes and see if they can be merged ?

**Comment by ieahleen** [comment]
@Shubham-Rasal a bit of patience please, someone will review it

**Comment by SandhyaR1007** [comment]
Starting on it.

**Comment by AkashsRepositories** [comment]
Working on it. Will update soon.

**Comment by AkashsRepositories** [comment]
Raised a MR regarding this. Please check.

**Comment by bpires** [comment]
Hey @AkashsRepositories and @SandhyaR1007, this issue already has a PR open that addresses the situation:

![image](https://user-images.githubusercontent.com/86871991/194774034-e69c9aab-7163-40c9-a100-6bd5971ed808.png)

You should always check if there are any PRs open before starting to work on an issue. All subsequent PRs are likely to be closed by the maintainers without notice. 

Also, when you sent a PR, always [link the pull request to the underlying issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Kudos on your interest in contributing! 👏🏻

**Comment by AkashsRepositories** [comment]
Got it. Thanks for pointing it out.

**Comment by getcoder-top** [comment]
please accept the pull request

**Comment by ieahleen** [comment]
@getcoder-top please follow the contributing guidelines first :)

**Comment by AkashsRepositories** [comment]
@ieahleen What is @getcoder-top missing out from the guidlines? Itvwould be great if you can point out.

**Comment by ieahleen** [comment]
@AkashsRepositories 

As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by getcoder-top** [comment]
> @AkashsRepositories
> 
> As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).
> 
> We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.
> 
> Some examples of this are:
> 
> 1. Do not edit files directly through GitHub – while you can, it's not a good idea.
> 2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
> 3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
> 4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
> 5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.
> 
> We appreciate you taking the time to help us, and we hope to see more contributions from you.
> 
> Happy Contributing.

hiii, @AkashsRepositories for the first point i am not directly editing from git i am forking and then cloning then making the changes then then creating trhe pull request which following guidlines

**Comment by getcoder-top** [comment]
other than that what is the issue here only the typo, then the pull request had the changes and the issue it passed through all the checks , then also it was closed

**Comment by getcoder-top** [comment]
This sentence is missing a word
[freeCodeCamp/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa2999ec27ec516655eba6.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/762945baf260afde16f4fd5191ce50a1dc20e3cc/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa2999ec27ec516655eba6.md?plain=1#L20)

Line 20 in [762945b](https://github.com/freeCodeCamp/freeCodeCamp/commit/762945baf260afde16f4fd5191ce50a1dc20e3cc)
what is the missing word


 You should use compound assignment add `20` to the value of `gold`.

**Comment by getcoder-top** [comment]
@ieahleen  @AkashsRepositories

**Comment by ieahleen** [comment]
@getcoder-top the missing word is "to", "you should use compound assignment to add". If you need help please reach out to the contributors chat room, your PR is still not following guidelines AND including unrelated changes.

**Comment by nayabatir1** [comment]
Is this not resolved yet?
I can re-open my pr.

**Comment by ieahleen** [comment]
@nayabatir1 if you can quickly fix this it may be ideal
