### ISSUE TITLE
issue with function parameter passing

### ISSUE THREAD

**Issue by tariqph** [FreeCodeCamp/FreeCodeCamp#4775]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  // Remove all the values
  
 var a=arr[7];
return a;
  for(var i=1;i<arr.length;i++){
   // b=a.filter(function(n){
   //return ( n!==arr[i]);
   // });
  }
  return arr;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
I think there is some issue with function parameter passing.

**Comment by ltegman** [comment]
Please provide details for exactly what the issue you're experiencing is.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
