### ISSUE TITLE
Add "Does Not Work in Safari" to "Use HTML5 to Require a Field" Description

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4776]
We've gotten a ton of bugs on [Use HTML5 to Require a Field](http://www.freecodecamp.com/challenges/waypoint-use-html5-to-require-a-field) from Safari users lately.  Safari does not support the `required` field (or it doesn't work the way you'd expect).

We need a `Note: This field does not work in Safari` added to the end of the description so we can stop getting bugs.

**Comment by chriscampbell32** [comment]
i'd like to get my feet wet with this one.

**Comment by bugron** [comment]
@chriscampbell32 It's all yours.

**Comment by erictleung** [comment]
This should be closed as PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4785 fixes this.

**Comment by ltegman** [comment]
Thanks for pointing this out @erictleung!
