### ISSUE TITLE
Code sentence in make RPG game confuses Crowdin

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47775]
The period at the end of this sentence is confusing Crowdin. It breaks the code sentence into two 

Here is the sentence

`You are in the town square. You see a sign that says Store.`.

Here is how it looks in Crowdin: [step 48 in Crowdin](https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/34639/en-ptbr?filter=basic&value=17#q=1217913)

here is the file:

https://github.com/freeCodeCamp/freeCodeCamp/blob/f80e34a9509f3208c01524ea25dd573fcacbe760/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a7c071219da921758a35bb.md#L10

We have two options, change the structure of the sentence or use code blocks like these 

\`\`\`md
\`\`\`

Note: whatever we decide to do, need to be applied to the hint at the bottom ,as well

**Comment by ethandpark** [comment]
I gave it a go, used a code block for the instruction itself and then switched up the wording for the hint section

**Comment by ieahleen** [comment]
Things like this don't need to have the file changed, we can change the segmentation on crowdin.

I will fix it from there

**Comment by ieahleen** [comment]
![image](https://user-images.githubusercontent.com/26656284/193462088-b9468c42-b571-40fc-a332-700b57ed32e8.png)
Here, it's a single string now.
