### ISSUE TITLE
Typos in new JavaScript make an RPG game

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47774]
### Describe the Issue

There is a typo in Step 45, the word `propertry` is misspelled.

Here is the typo

https://github.com/freeCodeCamp/freeCodeCamp/blob/f80e34a9509f3208c01524ea25dd573fcacbe760/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a7bfabe119461eb13ccbd6.md#L14

it should be 

> You should use dot notation to access the `innerText` property of `text`.

----

in step 26, `you will be use` is incorrect grammar, it should be `you will be using` or `you will use`

https://github.com/freeCodeCamp/freeCodeCamp/blob/f80e34a9509f3208c01524ea25dd573fcacbe760/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3b49686792938718b90d3.md#L10

---

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by guptadeepak8** [comment]
Is anybody working on this issue? if not I would like too

**Comment by aneeshgupta25** [comment]
Hello.. I would like to contribute to this issue.. Kindly assign me the same
