### ISSUE TITLE
Add link icon and button to headings in blog.

### ISSUE THREAD

**Issue by gefgu** [freeCodeCamp/freeCodeCamp#47778]
### Is your feature request related to a problem? Please describe.

![example](https://user-images.githubusercontent.com/53129852/193455339-8cb0f6a9-5062-452b-8f0f-f81e469a3995.png)
If you hover the `Insertion Sort` algorithm, you can't easily get a link like `https://www.freecodecamp.org/news/sorting-algorithms-explained-with-examples-in-python-java-and-c#insertion-sort` to reference this section.

### Describe the solution you'd like

Something like what happens in GitHub: 
![Screenshot from 2022-10-02 09-53-19](https://user-images.githubusercontent.com/53129852/193455388-d9e0cf01-44f3-4512-b43b-aa36ab5aa7e9.png)

### Describe alternatives you've considered

The implementation could be close to the one of GitHub, but I think that the icon being in the right side would be better for following the design of the site.

**Comment by code08-ind** [comment]
I can do that if you assign me that

**Comment by neha-gunta** [comment]
Hello, I would like to take up this issue.
Apart from a 'chain-link' icon, we can even use icons like a reference book or paper like the images in this:

https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/OOjs_UI_icon_reference.svg/1024px-OOjs_UI_icon_reference.svg.png
or
https://t4.ftcdn.net/jpg/02/48/02/41/360_F_248024184_FtFWfUKe4qBDMgYP9jZNMAsdgLFwCtDI.jpg

Do let me know your views on this! I'll work on the similar lines

**Comment by code08-ind** [comment]
If you can share the link of the blogs.

**Comment by gefgu** [comment]
@neha-gunta I think the 'chain-link' icon works best for this case.

**Comment by gefgu** [comment]
@code08-ind and @neha-gunta I'm not maintainer of this project and, thus, I can't assign any of you. In my experience, the best you can do is to provide a high-quality PR in a short-time and wait for it to be approved.

**Comment by gefgu** [comment]
The best I can do for help you both is when one of you provide a high-quality PR, I can ping one of the maintainers for them to merge.

**Comment by jeremylt** [comment]
This issue has not been marked ready for contributions. Please be patient and let the team decide if and what changes may be needed.

**Comment by ieahleen** [comment]
@yashdev9274 
thank you for your interested in contributing, but this issue is not open for contributions, please look at issues with labels https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only or https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted

**Comment by Arka90** [comment]
please assign it to me i would really like to contribute

**Comment by bbsmooth** [comment]
> The implementation could be close to the one of GitHub

I would not use the github implementation as a model as it is not accessible because you can't get to it with the keyboard. Also, the link is completely hidden from assistive technology because it has `aria-hidden="true"` set on it.

A much more accessible implementation can be found on the following page:

[Overlays Underwhelm at ID24
](https://adrianroselli.com/2022/09/overlays-underwhelm-at-id24.html)

He has the anchor links always showing, which is probably for touch user's sake. By the way, he is considered one of the premier accessibility experts, so if he is using this approach on his own web site it is a good bet that this will be accessible.

**Comment by amitaryansingh** [comment]
Hello Sir

i can fix this issue.can you assign it to me?

**Comment by gefgu** [comment]
@amitaryansingh this issue is still being discused. Have a look at this [suggestion](https://github.com/freeCodeCamp/freeCodeCamp/issues/47778#issuecomment-1264699026)

**Comment by scissorsneedfoodtoo** [comment]
Closing in favor of https://github.com/freeCodeCamp/news/issues/518
