### ISSUE TITLE
Clean up and normalize Contributing and other PR Related Documenation

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4778]
I made a first pass on cleaning up the CONTRIBUTING.md document (#4777), but I quickly realized that there already existed a body of documentation on Pull Requests.

Ref: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

These instructions need to be cleaned up and normalized and integated into the two new (larger and more detailed) Wiki articles I just wrote:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Create-A-Pull-Request-for-Free-Code-Camp

@ltegman also mentioned a new rebasing doc?
We have this guide:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

The README.md also needs references to these things.

We need to decide what information should live where before we proceed.

**Comment by bugron** [comment]
I think this issue can be closed.
