### ISSUE TITLE
Problem with challenge "Target the same element with multiple jQuery Selectors"

### ISSUE THREAD

**Issue by efrGas** [FreeCodeCamp/FreeCodeCamp#4779]
Challenge [Waypoint: Target the same element with multiple jQuery Selectors] has an issue. Can somebody help with this.
![problem](https://cloud.githubusercontent.com/assets/16018016/11456261/d6bcfbcc-9694-11e5-9c24-817ad7cc0057.jpg)

**Comment by bugron** [comment]
@efrGas thanks for posting this issue!
Please, provide your code, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by efrGas** [comment]
<script>
  $(document).ready(function() {
    $("button").addClass("animated ")
    $(".btn").addClass("shake ")
    $("#target1").addClass("animated shake btn-primary")
  });
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by efrGas** [comment]
Here are my code 
http://codepen.io/efrGas/pen/zvgNPW

**Comment by ltegman** [comment]
You have spaces after your first two class names in your `addClass` calls. Once you've resolved that you'll find that you will get an error because you should only be adding one class with each of your `addClass` statements.

Thanks and happy coding!

**Comment by efrGas** [comment]
It's woking!!!! thanks.
