### ISSUE TITLE
Bonfires Don't Save Until "Go to Next Bonfire" is Pressed

### ISSUE THREAD

**Issue by mdmoore** [FreeCodeCamp/freecodecamp#478]
When a Bonfire has been successfully completed, many times I've pressed the 'x' to close the modal to go over my solution again.  If you leave the Bonfire at this point, say to go read some news, the Bonfire isn't saved as completed and you've lost your solution.  

Maybe it's a good idea to save as completed as soon as soon as the modal is triggered.

**Comment by QuincyLarson** [comment]
@mdmoore thanks for pointing this out. Yes, this violates the principle of least astonishment. You expect it to save, and if you navigate away, progress is lost.
@terakilobyte - would it be possible to save a bonfire solution upon running it with no failing tests? I'm not exactly sure how we'd go about doing this.
