### ISSUE TITLE
the push() method don't give a space after the commas.

### ISSUE THREAD

**Issue by koouty** [FreeCodeCamp/FreeCodeCamp#4780]
Challenge [Bonfire: Steamroller](http://www.freecodecamp.com/challenges/bonfire-steamroller?solution=var%20newArr%20%3D%20%5B%5D%3B%0Afunction%20steamroller(arr)%20%7B%0A%20%20%20%20%0A%20%20%20%20while%20(arr.length%20%3E%200)%20%7B%0A%20%20%20%20%20%20if%20(Array.isArray(arr%5B0%5D))%20%7B%0A%20%20%20%20%20%20%20steamroller(arr%5B0%5D)%3B%20%20%20%0A%20%20%20%20%20%20%7D%20%20%0A%20%20%20%20%20%20else%20%7BnewArr.push(arr%5B0%5D)%3B%0A%20%20%20%20%20%20console.log(%22newArr%20%22%2C%20newArr)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20arr.shift()%3B%0A%20%20%20%20%7D%0A%20%20%2F%2F%20I%27m%20a%20steamroller%2C%20baby%0A%20%20return%20newArr%3B%0A%7D%0Asteamroller(%5B1%2C%20%7B%7D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var newArr = [];
function steamroller(arr) {
    
    while (arr.length > 0) {
      if (Array.isArray(arr[0])) {
       steamroller(arr[0]);   
      }  
      else {newArr.push(arr[0]);
      console.log("newArr ", newArr);
      }
      arr.shift();
    }
  // I'm a steamroller, baby
  return newArr;
}
steamroller([1, {}, [3, [[4]]]]);

```

**Comment by ltegman** [comment]
That's just a difference in how the console displays arrays. The reason your code isn't passing is that you're initializing the `newArr` variable globally, so after the first time you call your function you're not starting with an empty array and will return the wrong result.

Thanks and happy coding!

**Comment by koouty** [comment]
Thank you Itegman.
It is a great surprise for me, the existence of two kinds of empty arrays.
A second surprise is that there is noway to include the initialization inside the function d/t the recursion that create a new empty array anytime that it recurse.

**Comment by koouty** [comment]
Thank again, thank's to the error I discover somewhat of the secet types of empty arrays.

**Comment by koouty** [comment]
finally I make it with a nested function into the main function
