### ISSUE TITLE
Technical Documentation Page - a header element with elements inside it should not count as empty

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#47803]
### Describe the Issue

The test is looking for `innerText` content and doesn't count other elements as content. A `header` element with other elements inside it is not an empty element and should not be flagged as such.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-technical-documentation-page-project/build-a-technical-documentation-page

### Your code

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page.md

None of your header elements should be empty.

```
const els = document.querySelectorAll('header')
els.forEach(el => {
  if (el.innerText?.length <= 0) assert(false)
})
assert(els.length > 0)
```

### Expected behavior

A `header` element with elements inside it should not be seen as being empty. Or the requirements should clearly state that all header elements must have direct text content EDIT or a direct child element must have text.

The requirement should be reworded or changed.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/failed-none-of-your-header-elements-should-be-empty-error/559858

**Comment by nayabatir1** [comment]
Hey @lasjorg I've used same html and css provided in codepen. All tests are passing for me.

![image](https://user-images.githubusercontent.com/91016903/193658002-644da33f-0080-4885-9740-35fad97b76a3.png)

Also I tried to console `innerText`, all the text are displaying fine. I don't any reason test should fail.

![image](https://user-images.githubusercontent.com/91016903/193658652-0684c365-fa72-4ffc-8109-da17e0ce02b1.png)

**Comment by lasjorg** [comment]
That isn't the original HTML. The new HTML now has a `p` element with a pipe `|` symbol which counts as text.

But I was wrong in saying the text had to be a direct text node of the header element as it can be text inside a direct child element. But the main point still stands.

Original
```
<header class="top-header">
    <div class="nav-links">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/MDN_Web_Docs_logo.svg/1200px-MDN_Web_Docs_logo.svg.png"
            id="logo">
        <ul>
            <li> <a href="#Cascading_Style_Sheets" class="nav-link">Cascading Style Sheets</a></li>
            <li><a href="#Key_Resources" class="nav-link">Key Resources</a></li>
            <li><a href="#Tutorials" class="nav-link">Tutorials</a></li>
        </ul>
    </div>
    <div class="nav-links links-right">
        <div class="theme-btn">
            <a href="#">
                <li><i class="fa fa-sun"></i>Theme</li>
            </a>
        </div>
			 
        <div class="search-btn">
            <a href="#">
                <li><i class="fa fa-search"></i>Search</li>
            </a>
        </div>

        <a href="#Reference" class="nav-link">
            <li>Reference</li>
        </a>
        <a href="#Cookbook" id="btn-cookbook" class="nav-link">Cookbook</a>
        <i class="fa fa-bars"></i>
    </div>
</header>
```


New (notice the `<p> | </p>` element)

```
<header class="top-header">
    <div class="nav-links">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/MDN_Web_Docs_logo.svg/1200px-MDN_Web_Docs_logo.svg.png"
            id="logo" alt="MDN Logo">
        <ul>
            <li> <a href="#Cascading_Style_Sheets" class="nav-link">Cascading Style Sheets</a></li>
            <li><a href="#Key_Resources" class="nav-link">Key Resources</a></li>
            <li><a href="#Tutorials" class="nav-link">Tutorials</a></li>
        </ul>
    </div>
    <div class="nav-links links-right">
        <div class="theme-btn">
						
            <a href="#"><i class="fa fa-sun"></i>Theme </a>
				
        </div>
       <p> | </p>
        <div class="search-btn">
						
            <a href="#"><i class="fa fa-search"></i>Search </a>
				
        </div>

        <a href="#Reference" class="nav-link">Reference</a>

			
        <a href="#Cookbook" id="btn-cookbook" class="nav-link">Cookbook</a>
        <i class="fa fa-bars"></i>
    </div>
</header>
```

**Comment by nayabatir1** [comment]
This strange behavior 1st code block has innerText still it fails

On FCC (with 1st code block)
![image](https://user-images.githubusercontent.com/91016903/193684692-b6322df9-c7de-4b77-a353-0d012d8ce8fc.png)

On local system / codepen (with 1st code block)
![image](https://user-images.githubusercontent.com/91016903/193685201-cc057bd0-ffb9-4456-afb2-603991d0e9f4.png)

**Comment by raisedadead** [comment]
This seems to be working as expected now. Please open a fresh issue if you think this is still an issue.

**Comment by girmsh** [comment]
This pass the challange .



    <body>
      <main id="main-doc">
        <nav id="navbar">
             <header>Nav Bar</header>
         
        </nav>
        
        <section class="main-section" id="apple">
          <header>Apple</header>
             <nav id="navbar">
            
          <a class="nav-link" href="#apple">Apple</a>
        </nav>
         
         
          <p></p>
            <p></p>
            <code></code>
             <ul>
              <li>
                </li>
              </ul>
        </section>
        <section class="main-section" id="banana">
          <header>Banana</header>
             <nav id="navbar">
            
          <a class="nav-link" href="#banana">Banana</a>
        </nav>
          
        
           <p></p>
            <p></p>
            <code></code>
            <ul>
              <li>
                </li>
              </ul>
        </section>
        <section class="main-section" id="peach">
             <header>peach</header>
             <nav id="navbar">
        
          <a class="nav-link" href="#peach">Peach</a>
        </nav>
        
         
           <p></p>
            <p></p>
            <code></code>
             <ul>
              <li>
                </li>
              </ul>
        </section>
        <section class="main-section" id="orange">
            <header>orange</header>
             <nav id="navbar">
           
          <a class="nav-link" href="#orange">Orange</a>
        </nav>
         
           <p></p>
            <p></p>
            <code></code>
             <ul>
              <li>
                </li>
              </ul>
        </section>
        <section class="main-section" id="avocado">
          <header>Avocado</header>
             <nav id="navbar">
             
          <a class="nav-link" href="#avocado">Avocado</a>
        </nav>
           
         
           <p></p>
            <p></p>
            <code></code>
             <ul>
              <li>
                </li>
              </ul>
        </section>

        </main>
      </body>

  </html>
