### ISSUE TITLE
Building a Set of Colored Markers - Step 5: Remove whitespace requirement for content attribute in meta element

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#47805]
### Describe the Issue

The test is looking for a string with a space in it that isn't required.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-5

### Your code

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/616965351e74d4689eb6de30.md

> Your new meta element should have a name attribute set to viewport, and a content attribute set to width=device-width, initial-scale=1.0.

```
const meta = [...document.querySelectorAll('meta')];
const target = meta?.find(m => m?.getAttribute('name') === 'viewport' && m?.getAttribute('content') === 'width=device-width, initial-scale=1.0');
assert.exists(target);
```

### Expected behavior

Valid HTML should pass the test.

https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-content
https://infra.spec.whatwg.org/#split-on-commas

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/learn-css-colors-by-building-a-set-of-colored-markers-step-5/559840

**Comment by Saul-BT** [comment]
Can I work on this?

**Comment by Avijit-1352** [comment]
hi can I work on this?

**Comment by lasjorg** [comment]
@Avijit-1352 It looks like there already is a PR open for this. But have a look for other issues with the `help wanted` label.
