### ISSUE TITLE
 Invalid Name and location in user profile

### ISSUE THREAD

**Issue by Ankitchaudharyy** [freeCodeCamp/freeCodeCamp#47809]
### Describe the Issue

Numeric digits and invalid (random) text is allowed in Name field in Profile page.
Invalid or non-existent locations can be entered.

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/settings'
2. Click on Name / location field input box.
3. You can enter all characters.

### Expected behavior

For Names, it should not accept numerics, special characters except dot. Name should not start and with spaces, and should not contain more than one space in between first and last name.

For locations, a drop down with all existing locations would be there.

### Screenshots

<img width="1728" alt="Screenshot 2022-10-04 at 1 27 43 AM" src="https://user-images.githubusercontent.com/46367738/193667734-d4320244-2bb7-4ec0-bf7a-6824d81a87ea.png">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Ankitchaudharyy** [comment]
I can work on this issue, if approved.

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

We are specifically lenient on the characters allowed in these fields; you never know when someone's name will contain a number: https://www.wikidata.org/wiki/Q93418989

Also, a location with a dropdown of the hundreds of thousands of locations does not sound useable or maintainable. Also, seeing as we do not use the location value for anything official (we do not send anyone anything, or use it in any way for verification), it does not need to be necessarily valid. _in my opinion, it can be removed as unnecessary_

**Comment by Sboonny** [comment]
I vote to remove the location field 👍

**Comment by vinayak-0017** [comment]
hey @Sboonny can you assign me this issue , I would love to help out by removing that location input field.

**Comment by ShaunSHamilton** [comment]
@Sboonny We cannot delete the field just so quickly. I was making a passing comment about my thoughts on the field.

This sort of decision would result in the removal of data in the DB, which cannot just _happen_.

**Comment by ojeytonwilliams** [comment]
Also, it's not redundant, it's displayed on the user's profile. The only issue is that it's not identified as such.

Being able to display your location is a nice feature, so I don't see that it needs to be removed.  Why not simply add "Location: " in front of it?

**Comment by ShaunSHamilton** [comment]
> Why not simply add "Location: " in front of it?

This is very off-topic for the current issue thread. I do not think that is necessary - I cannot think of another platform that does that

**Comment by ojeytonwilliams** [comment]
This platform does.  Admittedly it uses an icon, not text, but the point stands.

**Comment by ieahleen** [comment]
I don't think we need to remove either field, nor limit them. People can choose to dispaly what they want on their profile.

I mean, freeCodeCamp uses "on Earth... for now" as location, who we are to limit people!

**Comment by ieahleen** [comment]
I'm closing this in favor of #47847
