### ISSUE TITLE
Math.Fl

### ISSUE THREAD

**Issue by kapaionut** [FreeCodeCamp/FreeCodeCamp#4782]
Challenge [Waypoint: Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript?solution=Math.floor(Math.random()%20*%2010)%3Bvar%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20Math.floor(Math.random()%20*%2010)%3B%0A%0A%20%20return%20Math.floor()%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Why does the code "Math.floor(Math.random() * 10);" does not work on codecamp but on w3schools.com works fine?
I tried to return both math.floor and math.random

My code:
```javascript
Math.floor(Math.random() * 10);var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function myFunction() {

  // Only change code below this line.
  Math.floor(Math.random() * 10);

  return Math.floor();

  // Only change code above this line.
}

```

![codecamp1](https://cloud.githubusercontent.com/assets/15847539/11458379/6b03ec6e-96c7-11e5-8bd1-9f6f9d001651.jpg)
![codecamp2](https://cloud.githubusercontent.com/assets/15847539/11458380/6b067eac-96c7-11e5-886b-bd32bfcc0892.jpg)

**Comment by ltegman** [comment]
You should be returning `Math.floor(Math.random() * 10);` but instead you are returning `Math.floor();` which is `NaN`. In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance with challenges.

Thanks and happy coding!

**Comment by kapaionut** [comment]
Thank you, i will use chat in future :)
