### ISSUE TITLE
cannot submit codepen link with pair's username

### ISSUE THREAD

**Issue by ashliecrooks** [FreeCodeCamp/FreeCodeCamp#4784]
It will not recognize a valid username (johnwsteill) as the pair programmer. Now it will not accept a URL even without the pair's username, as in the "Go to next challenge" remains disabled.

**Comment by SaintPeter** [comment]
Humm, works for me:
![image](https://cloud.githubusercontent.com/assets/553494/11458910/f5714c0a-967e-11e5-91c5-673ce9ac1705.png)

I do see that it seems to sort of flash "username not found" a bit, but it looked like I would be able to submit.

Do you get an error when you attempt to submit?

**Comment by ashliecrooks** [comment]
I do get an error.

<img width="853" alt="screenshot" src="https://cloud.githubusercontent.com/assets/14913352/11459065/a6bc563a-9693-11e5-81cc-137091bb230c.png">

HOWEVER, since taking that screenshot & pasting it here it started working and I was able to submit. Weird.
