### ISSUE TITLE
Doc: ES6 flag in editor

### ISSUE THREAD

**Issue by tomByrer** [FreeCodeCamp/FreeCodeCamp#4786]
Seems like you need the top-line comment of [`/*jshint esnext: true */`](http://stackoverflow.com/a/27442276/1324588) to use `let` & perhaps more ES2015/ES6 commands, though (in FxDev) others like `endsWith` don't need the flag.

Fine by me, though this flag is not mentioned [in the WiKi](https://github.com/freecodecamp/freecodecamp/wiki/write-and-run-es6-code-in-browser) for the JS editor.

**Comment by ltegman** [comment]
We are planning to switch to ESLint with babel-eslint in the future.

**Comment by BerkeleyTrue** [comment]
Adding that flag does not automatically add ES2015, it just tells jshint to add the lint features. ES2015 features depend on the browser at the moment.
