### ISSUE TITLE
Typos in new JavaScript make an RPG game

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47860]
### Describe the Issue

There is a typo in Step 108, the word `property` is single while it should be `properties`.

Here is the typo

https://github.com/freeCodeCamp/freeCodeCamp/blob/6dd8c6241be330bd3b32b7af6756f60473fc88c7/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8d81f539f004776dd9b1e.md#L12

----

in step 102, there is a missing code block in this line 

https://github.com/freeCodeCamp/freeCodeCamp/blob/6dd8c6241be330bd3b32b7af6756f60473fc88c7/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8d35660db4040ba292193.md#L20

it should be this 

> You should set `goldText.innerText` to `gold`.

---

in step 81, there are three missing code blocks in these line 

https://github.com/freeCodeCamp/freeCodeCamp/blob/6dd8c6241be330bd3b32b7af6756f60473fc88c7/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8c7322e42962ad53ad204.md#L35-L50

they should be

> Your second `weapons` object should have the `name` set to `dagger` and the `power` set to `30`.

> Your third `weapons` object should have the `name` set to `claw hammer` and the `power` set to `50`. 

> Your fourth `weapons` object should have the `name` set to `sword` and the `power` set to `100`.

---

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by void-hr** [comment]
I would like to work on this.

**Comment by Sboonny** [comment]
@void-hr feel free to open a pull request, after you have read [our guidelines for contributing](https://contribute.freecodecamp.org/#/).

**Comment by void-hr** [comment]
@Sboonny I have opened a PR please let me know if there are any changes or improvements that needs to be done.
