### ISSUE TITLE
Showing both options as view in selection menu while claiming certificate

### ISSUE THREAD

**Issue by IIvexII** [freeCodeCamp/freeCodeCamp#47871]
### Describe the Issue

It looks like there is a typo on this page.

### Affected Page

https://www.freecodecamp.org/settings#certification-settings

### Expected behavior

It should show the view code and view as website.

### Screenshots
![Screenshot from 2022-10-06 18-42-40](https://user-images.githubusercontent.com/41378765/194328860-7fa3f3a2-bb15-4dbf-9b4f-f37dd5a7e518.png)

### System

- Device: [Laptop]
- OS: [Zorin OS]
- Browser: [edge]
- Version: [106]

**Comment by ieahleen** [comment]
It's doing the same in a certification page
![image](https://user-images.githubusercontent.com/26656284/194345914-b6f598e9-6388-4b36-821c-4b1316ef7640.png)
(https://www.freecodecamp.org/certification/ieahleen/responsive-web-design)

**Comment by raisedadead** [comment]
@Sboonny Is this related to something you were working on recently?

**Comment by UditNS** [comment]
Where I can find the code for making the changes ?

**Comment by raisedadead** [comment]
You should follow these [contributing guidelines](https://contribute.freecodecamp.org)

**Comment by surajrane42** [comment]
Hello, I am interested in working on it

**Comment by Sboonny** [comment]
@raisedadead yes, this passed my radar in reviewing #47525, we can revert it, and I should be adding a fix shortly

**Comment by Prince-Mendiratta** [comment]
Hi, @Sboonny! Could you assign this issue to me instead? I've already started implementing a fix and adding the respective texts for each locale.

**Comment by Prince-Mendiratta** [comment]
> @Prince-Mendiratta, although I am almost done I just wanted to add preview icon that Tom added, but this doesn't mean I am done.
> 
> sure you can submit PR. I will review it instead +1

Sounds awesome, thanks!
Also, which preview icon are we talking about? I'll make sure to add that as well.

**Comment by Sboonny** [comment]
@Prince-Mendiratta, in this PR #46251 tom added `<FontAwesomeIcon icon={faExternalLinkAlt} />`, tom add icon to previewing iframe icon.

because the button do similar thing, I wanted to add the icon as well.

**Comment by Prince-Mendiratta** [comment]
@Sboonny To which buttons should I add the preview icon? Should I add this as a separate PR to keep things atomic or should I add it as a commit to the current PR?

**Comment by Sboonny** [comment]
You are right, the current issue is about typo.  👍 

We can merge your work in, and I will create a new issue about the icons, maybe we can think of an icon for `View` button that isn't a dropdown there, as well. 🤔

**Comment by Prince-Mendiratta** [comment]
The `faExternalLinkAlt` icon renders something like this. It implies an external redirection, rather than an iframe popup but I guess that's just me nitpicking.

![image](https://user-images.githubusercontent.com/54077356/194527365-08ce88f6-6907-467a-b4f5-f757e554a4b4.png)

**Comment by Sboonny** [comment]
Opening a new issue for this, and adding icon to view button. 👍 

> icon renders something like this. It implies an external redirection, rather than an iframe popup but I guess that's just me nitpicking.

**Comment by ieahleen** [comment]
If the project is an external link I agree with the use of that icon, if it's a modal I am not sure
