### ISSUE TITLE
Update front end demo project URL's

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#47891]
Describe the Issue
All the data viz projects were created on our .rocks domain. We just need to replace the codepen URL's with the new addresses in the curriculum files of those five projects.

Here's the URL's:
https://25--5-clock.freecodecamp.rocks
https://drum-machine.freecodecamp.rocks
https://javascript-calculator.freecodecamp.rocks
https://markdown-previewe.freecodecamp.rocks
https://random-quote-machine.freecodecamp.rocks

And the [project files are here](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/03-front-end-development-libraries/front-end-development-libraries-projects)

---

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/03-front-end-development-libraries/front-end-development-libraries-projects

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Anuran12** [comment]
@ieahleen  i would like to do this. I started open source contribution a few days ago .

**Comment by Anuran12** [comment]
@ieahleen  will it count for Hacktoberfest?

**Comment by kclalit64** [comment]
@ieahleen the project URLs you have provided are not accessible. [Error: DNS address could not be found.]

**Comment by RJ025** [comment]
@ieahleen  i have changed all mentioned projects URL please check

**Comment by kclalit64** [comment]
@Anuran12 I know, but Isn't it a good habit to look into that before opening an issue?

**Comment by RohitShah1706** [comment]
I have a good experience with JS & node JS, can I updated the content.

**Comment by raisedadead** [comment]
There is an PR in the works that is going to fix this. We are locking this thread to avoid too many "Can I help" comments. 

Please read [contributing guidelines](https://contribute.freecodecamp.org) to help us help you.
