### ISSUE TITLE
the output is in chinese language

### ISSUE THREAD

**Issue by koouty** [FreeCodeCamp/FreeCodeCamp#4789]
Challenge [Bonfire: Binary Agents](http://www.freecodecamp.com/challenges/bonfire-binary-agents?solution=function%20binaryAgent(str)%20%7B%0A%20newArr%20%3D%20%5B%5D%3B%20%20%20%0A%20%20var%20arr%20%3D%20str.split(%22%20%22)%3B%0A%20%20%2F%2Fconsole.log(arr)%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20console.log(String.fromCharCode(arr%5Bi%5D))%3B%0A%20%20%20%20%20%20newArr.push(String.fromCharCode(arr%5Bi%5D))%3B%0A%20%20%20%20%20%2F%2F%20console.log(newArr)%3B%0A%20%20%7D%0A%20%20str2%20%3D%20newArr.join(%22%20%22)%3B%0A%0A%20%20return%20str2%3B%0A%7D%0AbinaryAgent(%2201000001%2001110010%2001100101%2001101110%2000100111%2001110100%2000100000%2001100010%2001101111%2001101110%2001100110%2001101001%2001110010%2001100101%2001110011%2000100000%2001100110%2001110101%2001101110%2000100001%2000111111%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function binaryAgent(str) {
 newArr = [];   
  var arr = str.split(" ");
  //console.log(arr);
  for (i = 0; i < arr.length; i++) {
      console.log(String.fromCharCode(arr[i]));
      newArr.push(String.fromCharCode(arr[i]));
     // console.log(newArr);
  }
  str2 = newArr.join(" ");

  return str2;
}
binaryAgent("01000001 01110010 01100101 01101110 00100111 01110100 00100000 01100010 01101111 01101110 01100110 01101001 01110010 01100101 01110011 00100000 01100110 01110101 01101110 00100001 00111111");
```

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) and [Bonfire Help Chat](https://gitter.im/FreeCodeCamp/HelpBonfires) for assistance.

Thanks and happy coding!
