### ISSUE TITLE
Exercise Tracker first test false positive

### ISSUE THREAD

**Issue by NNRepos** [freeCodeCamp/freeCodeCamp#47893]
### Describe the Issue

on the [exercise tracker website](https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker), the first test says "You should provide your own project, not the example URL.".
obviously i provided the example URL, but then the test has passed.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

### Steps to Reproduce

1. Go to the website
2. Scroll down to 'Solution Link'
3. enter `https://project-name.camperbot.repl.co/` (the example URL)
4. click on 'I've completed this challenge'
5. test passes

### Expected behavior

the first test should fail.

### Screenshots

![image](https://user-images.githubusercontent.com/45516943/194541676-871b6091-05b6-44b3-b338-71ab536ad58b.png)

### System

- Device: [laptop]
- OS: [Windows 11]
- Browser: [Chrome]
- Version: [106.0.5249.103]

**Comment by kclalit64** [comment]
Please confirm if the issue is resolved

**Comment by ieahleen** [comment]
This one fails if you use the sample project provided at the top of the page
> Build a full stack JavaScript app that is functionally similar to this: https://exercise-tracker.freecodecamp.rocks/.

The palceholder url doesn't point anywhere and all the other tests fail

**Comment by NNRepos** [comment]
@ieahleen oh, i guess there are 2 example URLs, i misunderstood. should i close this?
or do you want me to create a PR to clarify the description (or even better, use the same URL in both cases)?
