### ISSUE TITLE
Streak and calendar aren't synced.

### ISSUE THREAD

**Issue by ahstro** [FreeCodeCamp/freecodecamp#479]
As you can see here, I have worked on FCC for 9 days straight, but the streak counter is off. I'm pretty sure this has something to do with how you handle timezones since I remember working at about 1am here but not getting the streak updated until way later.
![streakfcc](https://cloud.githubusercontent.com/assets/3090888/7788161/1d389f88-0230-11e5-8eb7-d3596e58012e.png)

**Comment by terakilobyte** [comment]
Unfortunately by server time you missed a day, Saturday specifically. Here's what your streak looks like when specifically rendered server time.

Based on repeated confusion over the streak display I'll look at not localizing the time.

![Your streak](https://www.dropbox.com/s/ztgcwsse9uxx0xv/Screenshot%202015-05-24%2010.24.35.png)

**Comment by LumenTeun** [comment]
Figured that was what happened. Oh well, I know I'm still on that streak.

**Comment by QuincyLarson** [comment]
@terakilobyte - if there isn't some better solution, I propose we use GMT and just post a notification on there. But it would definitely be better if we could detect the time zone and write that into the user's profile for reference. I'm not sure how complicated that will be.

**Comment by BerkeleyTrue** [comment]
Closing this in favor of #1075.
