### ISSUE TITLE
Misleading statements

### ISSUE THREAD

**Issue by Serial-Coder** [FreeCodeCamp/FreeCodeCamp#4790]
First it says: Add the btn-primary class to the button with id #target1.

Then: Your #target1 element should have the classes animated‚ shake and btn-primary.

Only by having one single class the exercise is considered correct
![screen shot 2015-11-29 at 10 05 05 pm]
(https://cloud.githubusercontent.com/assets/15092795/11460061/5e8d16f4-96e5-11e5-87e9-ca62c4577d14.png)

**Comment by ltegman** [comment]
You add one class with each of the three selectors, but since `#target` is a `button` and has the class `.btn` it will have all three classes added to it.

Thanks and happy coding!

**Comment by Serial-Coder** [comment]
Wow that was fast! Thanks for the explanation :)
