### ISSUE TITLE
Add Icons to the settings page buttons

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47924]
### Is your feature request related to a problem? Please describe.

In the settings page, we have changed `show-code` and `show-solution` to `view`  for consistency. With the extra spaces freed, we can add icons for the setting page. Mainly to differentiate between normal `View` button and `View` Dropdown.

![View button](https://user-images.githubusercontent.com/88248797/194698509-2a12fce1-24e6-4fb4-8d2e-54a0d95a790a.png)

### Describe the solution you'd like

We can add the old Preview Icon that indicated to the camper, it's an external link. 

For context: https://github.com/freeCodeCamp/freeCodeCamp/issues/47923

### Describe alternatives you've considered

We can pick New icon if we decided to keep the old preview icon from font-awesome.

### Additional context

We have the opportunity to test mobile app icons in the setting, with the freed spaces. I think it's a good idea to use mobile icons if they are picked and decided in the setting to test them out.

**Comment by AhmedIbrahim336** [comment]
If this feature will be accepted I can implement it!

**Comment by ShuvamBag** [comment]
hello sir, I want to work on this issue.

**Comment by Sboonny** [comment]
thank you for the interest, @ShuvamBag, but issues label with https://github.com/freeCodeCamp/freeCodeCamp/labels/status%3A%20discussing aren't open for contribution, because it is in discussion state, and we don't know if it's needed or wanted yes.

you can look up https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22, if you are interesting on open issue

**Comment by Sboonny** [comment]
thank you for the interest, @Wolverine-08 and, @prreff123 , but issues label with https://github.com/freeCodeCamp/freeCodeCamp/labels/status%3A%20discussing aren't open for contribution, because it is in discussion state, and we don't know if it's needed or wanted yes.

you can look up https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22, if you are interesting on open issue

**Comment by ahmadabdolsaheb** [comment]
We currently have the dropdown icon such as the following:

<img width="807" alt="Screen Shot 2022-10-19 at 4 05 52 PM" src="https://user-images.githubusercontent.com/4591597/196700053-a0869ea6-cd8f-4357-86c6-5acddbae5c35.png">

For external links we could add the one we use in the dropdown navigation.
What other states do we need to cover?

**Comment by Sboonny** [comment]
In the dropdown there is `veiw code`, and `view project` links. Should we add icons in them as well?

the consistency mentioned in [this issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/46497#issuecomment-1158992698), should be account for, as if the icons functional in these section, as well. 🤔

I think that's all I can think of currently

**Comment by Jaya-sys** [comment]
Hello! I have some development experience and it will be an opportunity for me if you can assign this issue to me! Thankyou

**Comment by Sboonny** [comment]
thank you for the interest, @Jaya-sys, but issues label with https://github.com/freeCodeCamp/freeCodeCamp/labels/status%3A%20discussing aren't open for contribution, because it is in discussion state, and we don't know if it's needed or wanted yes.

you can look up https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22, if you are interesting on open issue

**Comment by ahmadabdolsaheb** [comment]
@Sboonny, we probably could add the external link icon for elements navigating out of the website, but it is not necessary.

**Comment by Sboonny** [comment]
I am opening this for contribution then, we can add icon to `View` to make it look different from the dropdown. as mentioned in this comment, https://github.com/freeCodeCamp/freeCodeCamp/issues/47924#issuecomment-1285067542

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Jaya-sys** [comment]
As you have opened this for contribution can I contribute to it? Can you assign this to me?

**Comment by Sboonny** [comment]
feel free to open a PR :+1: , after you have read our contribution guide

**Comment by nayabatir1** [comment]
IMO we should wait for #48211, working on both issues simultaneously will lead to overwriting one change over another.

**Comment by Sboonny** [comment]
@nayabatir1, how so? 🤔 I thought the conclusion is to add something like our old icon from the preview `<FontAwesomeIcon icon={faExternalLinkAlt} />`

It should be one line 🤔, did I misread Ahmad comments?

**Comment by nayabatir1** [comment]
@Sboonny yeah, you are right, 
Instead of overwriting I should have written merge conflict.
