### ISSUE TITLE
Replacing the preview icon, with clearer one

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47923]
A camper mentioned in his comment, that this icon below indicate to them that it's an external link not a popup.

![image](https://user-images.githubusercontent.com/88248797/194698227-7d9735a0-b547-4653-815b-a615c3cf19a3.png)

We can change it to clearer icon that show, that it's a popup.

The original comment for context: https://github.com/freeCodeCamp/freeCodeCamp/issues/47871#issuecomment-1271385419

**Comment by Prince-Mendiratta** [comment]
I found it interesting, that [Windows UX guidelines](https://docs.microsoft.com/en-us/windows/desktop/uxguide/ctrl-command-buttons) say you should use ellipsis (…) when there is some additional action required after the action (popup, dialog, confirmation) and it isn't clear by the action itself. 

> While command buttons are used for immediate actions, more information might be needed to perform the action. Indicate a command that needs additional information (including confirmation) by adding an ellipsis at the end of the button label.
> ...
>This doesn't mean you should use an ellipsis whenever an action displays another window only when additional information is required to perform the action. Consequently, any command button whose implicit verb is to "show another window" doesn't take an ellipsis, such as with the commands About, Advanced, Help (or any other command linking to a Help topic), Options, Properties, or Settings.

So maybe an ellipsis of some kind: in button's label or in the icon?

More so, it's a part of [Apple's human interface guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/buttons/push-buttons/) too.

> Append a trailing ellipsis to the title when a push button opens another window, view, or app. Throughout the system, an ellipsis in a control title signals that people can provide additional input. For example, the Edit buttons in the AutoFill pane of Safari Settings include ellipses because they open other views that let people modify autofill values.

If we were to stick with keeping an icon regardless, this regular [fa-square-up-right](https://fontawesome.com/icons/square-arrow-up-right?s=light&f=classic) feels like a better choice, with the arrow denoting there would be some kind of external interface but the enclosed square representing that it is not an external redirection, thus denoting some kind of popup or modal.

**Comment by bbsmooth** [comment]
I think these guides are saying that the ellipses should be added when the button opens a window that requires the user to enter more information or perform another action. This isn't the case here, so I don't think they are warranted in this instance.

If we want to use a new icon then I would suggest we use one that has [two windows, one overlapping the other](https://www.onlinewebfonts.com/icon/273031). I'm not suggesting that we use this exact icon. This is just an example of what I'm suggesting.

**Comment by Prince-Mendiratta** [comment]
> If we want to use a new icon then I would suggest we use one that has [two windows, one overlapping the other](https://www.onlinewebfonts.com/icon/273031).

I agree with the use of some kind of variation of that icon. There's a small issue though, there's no such icon in the font awesome library for this so we'll have to find a different way to implement this.

**Comment by mehdibouaziz** [comment]
Font awesome has an icon that could have the same meaning: [window-restore](https://fontawesome.com/icons/window-restore?s=solid&f=classic)

Alternatively Material Icons has a specific preview icon if these can be used? [preview icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apreview%3A)

**Comment by being-nitin** [comment]
can you assign me this task?

**Comment by being-nitin** [comment]
allright sir

**Comment by ahmadabdolsaheb** [comment]
Both [two windows, one overlapping the other](https://www.onlinewebfonts.com/icon/273031) and [window-restore](https://fontawesome.com/icons/window-restore?s=solid&f=classic) both are plausible.

**Comment by Prince-Mendiratta** [comment]
I'd suggest we should move forward to replace the `faExternalLinkAlt` icon with the `faWindowRestore` icon. Should I move ahead and send over a PR?

This is the output -
![image](https://user-images.githubusercontent.com/54077356/196970942-4cc1c809-f59f-4e8f-8b01-46738ecca50f.png)

**Comment by ahmadabdolsaheb** [comment]
@Prince-Mendiratta, Sure.
