### ISSUE TITLE
Feature: diff

### ISSUE THREAD

**Issue by KravMaguy** [freeCodeCamp/freeCodeCamp#47937]
@moT01 I suppose that is a fair point. My reason for sticking with requiring specificity is we have the ability to say: "We expected `some text`, but you put `some text.`".

We could even go as far as pointing out the diff.

_Originally posted by @ShaunSHamilton in https://github.com/freeCodeCamp/freeCodeCamp/issues/47854#issuecomment-1271447172_

This would possibly prevent users from making extra forum posts if they could visualize the difference between --fcc-actual-- and --fcc-expected--

**Comment by KravMaguy** [comment]
![image](https://user-images.githubusercontent.com/37171082/194727516-4f0560f2-b16c-4a20-94bb-259feea682be.png)

**Comment by raisedadead** [comment]
Please use the issue template correctly, and give the issue a [succinct](https://www.google.com/search?q=succinct+meaning) title. 

Also, check our contributing guidelines.

**Comment by kartikey-katara-sn11** [comment]
Hello KravMaguy Sir!!
Please assign me to this issue. I'd like to contribute.

**Comment by raisedadead** [comment]
Re-open a fresh issue when you are ready.
