### ISSUE TITLE
Search page enhancements

### ISSUE THREAD

**Issue by SiddheshKukade** [freeCodeCamp/freeCodeCamp#47933]
### Describe the Issue

Currently, the Search page of `FreeCodeCamp`shows a list of results but doesn't show what are the results for and the text in the search bar is also cleared in the new tab of the search query. This is not good for enhancing User Experience. I have suggested some changes below . I would like to work on them please assign issue to me 

### Affected Page

https://www.freecodecamp.org/news/search?query=SQL%20Queries

### Steps to Reproduce

1. Go to [https://www.freecodecamp.org/](https://www.freecodecamp.org/)
2. Click on SEARCH button
3. Type your query and hit enter 
4. See the error

### Expected behavior

It should have a heading something like "Search Results for "<SEARCH_TEXT>""
just like we have on google.com
![image](https://user-images.githubusercontent.com/65951872/194712873-f1ea27cf-d88e-460f-b4d4-f8e687338de9.png)

### Screenshots

Problem  : 
![image](https://user-images.githubusercontent.com/65951872/194712713-1d72afc6-28a8-4952-9f89-9f437bd410ad.png)

Solution : 
![image](https://user-images.githubusercontent.com/65951872/194712706-b3a76e46-1fe9-4f87-96bf-f8a6034a72b4.png)

### System

- Browser: Firefox 

![image](https://user-images.githubusercontent.com/65951872/194712800-7a6d368a-4483-4fa0-b805-8ba173954a3a.png)

### Additional context

I would like to take this issue I'd do the changes in very less time and the code will also be documented and maintainable

**Comment by SiddheshKukade** [comment]
Dear Maintainers ,  I would like to work on this issue.

**Comment by bbsmooth** [comment]
As far as accessibility is concerned, the new results page should have a `<title>` that describes the purpose of the page. So in this case the title should probably at least include the phrase "search results" and even better if it could include the string searched for (e.g. "Search results for [query string]"). All of this should come before "freeCodeCamp.org". This is a [WCAG 2.4.2](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html) requirement, although there is some potential wiggle room in defining what adequately describes the topic or purpose of the page. But currently the title is just "Search - freeCodeCamp.org" and I would argue that that is too ambiguous and needs to be defined a little better as described above.

As for an `h1` heading, it's not technically a WCAG requirement but I agree, it is a best practice. It should mimic the `<title>` for the most part but it would probably be cool to add the number of results found as well. And even if you don't include the query string in the `<title>` I would definitely include it in the `h1`.

**Comment by raisedadead** [comment]
BTW, it's freeCodeCamp or freeCodeCamp.org - never FreeCodeCamp - the "f" is small as in camelCase like iPhone and eBay

**Comment by SiddheshKukade** [comment]
> BTW, it's freeCodeCamp or freeCodeCamp.org - never FreeCodeCamp - the "f" is small as in camelCase like iPhone and eBay

Ok sir 👍 can I work on this  ?

**Comment by SiddheshKukade** [comment]
> As far as accessibility is concerned, the new results page should have a `<title>` that describes the purpose of the page. So in this case the title should probably at least include the phrase "search results" and even better if it could include the string searched for (e.g. "Search results for [query string]"). All of this should come before "freeCodeCamp.org". This is a [WCAG 2.4.2](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html) requirement, although there is some potential wiggle room in defining what adequately describes the topic or purpose of the page. But currently the title is just "Search - freeCodeCamp.org" and I would argue that that is too ambiguous and needs to be defined a little better as described above.
> 
> As for an `h1` heading, it's not technically a WCAG requirement but I agree, it is a best practice. It should mimic the `<title>` for the most part but it would probably be cool to add the number of results found as well. And even if you don't include the query string in the `<title>` I would definitely include it in the `h1`.

@bbsmooth  I agree 👍

**Comment by nayabatir1** [comment]
I'm getting lot of warnings. Any suggestion ?
![image](https://user-images.githubusercontent.com/91016903/194773001-1282ad41-972e-485d-8488-98336f4ca02c.png)

**Comment by raisedadead** [comment]
The news repository is a particular case. 

To work with it locally, you must set up [Ghost](ghost.org) on your local machine. Once you do, you can create keys for, say, English and add them to your `.env` file. Look at the sample file for reference. You don't need all, any one language should be fine - I would go with English.

Now - even with that, we would have to make an exception when you are ready to submit a PR - because we block PRs from forks for security reasons.

**Comment by nayabatir1** [comment]
@raisedadead Ghost link is not working. 
On clicking it taking me to https://github.com/freeCodeCamp/freeCodeCamp/issues/ghost.org

**Comment by raisedadead** [comment]
https://www.google.com/search?q=ghost.org

**Comment by raisedadead** [comment]
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by raisedadead** [comment]
After deliberation, we gave this some more thought and think that this is a non-trivial issue at the moment.

i.e, the OP is suggesting implementing a form of:

"Showing results for X, search instead for Y."

The search results are rendered from an Algolia-based index. While, in theory, it is possible to show this in the style the OP suggests, the implementation is involving and is a low priority for the staff members.

We will reconsider this sometime in the future when we can open up the repository for contributions from the community.
