### ISSUE TITLE
typo descedant should be descendant in build-a-survey-form.md

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#47949]
### Describe the Issue

the word descendant is misspelled multiple times as "descedant" int the file build-a-survey-form.md

https://forum.freecodecamp.org/t/small-typo-in-freecodecamp/561536/3

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### Your code

N/A

### Expected behavior

correct the spelling

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

list of what appears to be 2 files that need to be fixed:

hbar1st@LAPTOP-KKSHJUG1:~/fcc/freeCodeCamp/curriculum/challenges/english$ grep -r descedant
01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md:Your `#name` should be a descedant of `#survey-form`.
01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md:Your `#email` should be a descedant of `#survey-form`
01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md:Your `#number` should be a descedant of `#survey-form`.
01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md:Your `#name-label` should be a descedant of `#survey-form`.
01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md:Your `#email-label` should be a descedan
 of `#survey-form`.
01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md:Your `#number-label` should be a descedant of `#survey-form`.
14-responsive-web-design-22/build-a-survey-form-project/build-a-survey-form.md:Your `#name` should be a descedant of `#survey-form`.
14-responsive-web-design-22/build-a-survey-form-project/build-a-survey-form.md:Your `#email` should be a descedant of `#survey-form`
14-responsive-web-design-22/build-a-survey-form-project/build-a-survey-form.md:Your `#number` should be a descedant of `#survey-form`.
14-responsive-web-design-22/build-a-survey-form-project/build-a-survey-form.md:Your `#name-label` should be a descedant of `#survey-form`.
14-responsive-web-design-22/build-a-survey-form-project/build-a-survey-form.md:Your `#email-label` should be a descedan
 of `#survey-form`.
14-responsive-web-design-22/build-a-survey-form-project/build-a-survey-form.md:Your `#number-label` should be a descedant of `#survey-form`.

**Comment by ieahleen** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files: see the first comment of the issue.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by ArsalanAli915** [comment]
Hi @hbar1st, I am first time contributing to Hacktoberfest. could assign this issue to me.

**Comment by hbar1st** [comment]
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
