### ISSUE TITLE
Add contributor label in readme file 

### ISSUE THREAD

**Issue by Hariom8799** [freeCodeCamp/freeCodeCamp#47941]
![194721540-e2c06f16-cdcf-4d0d-8f58-964f96d5fd95](https://user-images.githubusercontent.com/76242202/194737505-3ca7a84b-146a-4dce-a018-d1babaf530e0.png)
Like that

**Comment by belphegor-s** [comment]
I want to contribute, please assign this to me.

**Comment by Hariom8799** [comment]
@belphegor-s bro pls find another one

**Comment by Hariom8799** [comment]
pls assign me

**Comment by Sboonny** [comment]
Because freeCodeCamp isn't only the repo, it will be unfair to add contributors section because it will leave a lot more people who do contribute to freeCodeCamp but not in code.
