### ISSUE TITLE
Editor's code completition bug

### ISSUE THREAD

**Issue by nhquiroz** [FreeCodeCamp/FreeCodeCamp#4795]
Hi!

The code completition feature of the embedded editor is bugged, at least it has issues with the HTML tags. For example, if you type

`<p` and then press **TAB** to use the auto complete, the editor's output will be `<<p></p>`, with an extra `<` at the beginning.

**Comment by ltegman** [comment]
This is not a bug. The editor does not have code completion, it has [Emmet](http://emmet.io/) which autocreates html and CSS from shorthand when you press tab. If you hadn't included the opening `<` it still would have created the `p`, but without the extra opening bracket :smile:

Thanks and happy coding!
