### ISSUE TITLE
Make Cafe Menu Step 36 instructions a little clearer

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#47958]
### Describe the Issue

Most of the description for step 37 is about styling `p` elements. It even states that "you need to apply some styling to the `p` elements". But then suddenly the last line instructs the user to add a `class` to an `article`, which seems a little confusing and out of place. This caused a least one camper to add a new `p` element in this step and apply the class attribute to that element. 

### Affected Page

~~https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-37~~

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-36

### Your code

Campers code:

```
<article>
            <p class="item"></p>
            <p class="flavor">French Vanilla</p>
            <p class="price">3.00</p>
</article>
```

### Expected behavior

Even though the last line is clear that the class should be added to the article, I think it could be made less confusing if we explained that this is in preparation for styling the `p` elements. Perhaps change the last sentence to something like:

> To help with styling the `p` elements, you will first add a `class` attribute with the value `item` to the first `article` element under the `Coffee` heading.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by AbhishekKC16** [comment]
Hello Sir, can you assign this issue to me?

**Comment by kartikey-katara-sn11** [comment]
Hello bbsmooth Sir!!
Please assign me to this issue. I'd like to contribute.

**Comment by Sboonny** [comment]
> To get them on the same line, you need to apply some styling to the `p` elements, so they behave more like inline elements.

I think it's better to slightly change this line, it's talking about changing `p` styling. We can keep the limelight on `article` by mention it as `p` element's parent.

> To get them on the same line, you need to apply some styling to the `p` elements, so they behave more like inline elements.

Or

> To get them on the same line, you need to apply some styling to the `p` elements' parent, so you can control their layout.


The reason I am suggesting this, because the issue seems rare, and I don't want too much change to description, if it's a rare issue.

**Comment by mehdibouaziz** [comment]
I think that what's missing is explaining shortly why we add the class to the parent element and not directly to the `p` elements. Like you said, the confusion comes from why we are suddently targeting the `article` element, when the focus of the lesson was styling the `p` elements.

i.e we don't `need` to target the parent element, it's just cleaner.

> To get them on the same line, you need to apply some styling to the `p` elements, so they behave more like inline elements.
> To avoid repetition by adding a class to each individual `p` element we will use their parent element instead.
> Add a `class` attribute with the value `item` to the first `article` element under the `Coffee` heading.

@Sboonny what do you think ?

**Comment by raisedadead** [comment]
I think we should go with the proposal from @sidemt, Is anyone up for taking this up?

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by andriy-koz** [comment]
![screenshot](https://user-images.githubusercontent.com/86450120/212693336-d0853be2-75ba-478c-a775-bc42e7c4147c.png)

This looks good to me, any suggestions on what to do to close the issue?

**Comment by a2937** [comment]
Pardon me but I believe the issue needs updated as the issue now refers to lesson 36 , not 37.

**Comment by bbsmooth** [comment]
Yes, it appears that this used to be step 37 but now it is step 36. It also appears that the wording has been updated in step 36 to pretty much match what @sidemt suggested above.

**Comment by a2937** [comment]
> Yes, it appears that this used to be step 37 but now it is step 36. It also appears that the wording has been updated in step 36 to pretty much match what @sidemt suggested above.

Actually I think it matches what @mehdibouaziz said more tbh.
