### ISSUE TITLE
Clean up unused files and exports

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#47971]
As discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/47836 there are several unused files and exports.  We should remove all of these from the codebase.

The full set of tasks is:

- [ ] Remove unused files
- [ ] Add missing dependencies
- [ ] Remove unused exports
- [ ] Remove unused types
- [ ] Remove duplicate exports

The files with issues are:

--- UNUSED FILES (8)
src/assets/icons/donate-with-PayPal.tsx
src/assets/icons/intro-information.tsx
src/components/Donation/duration-amount-options.tsx
src/components/Header/components/user-state.tsx
src/components/helpers/form/block-save-wrapper.tsx
src/components/search/searchPage/empty-search.tsx
src/components/search/searchPage/no-results.tsx
src/components/search/searchPage/search-page-hits.tsx

--- UNLISTED DEPENDENCIES (4)
react-instantsearch-core  src/components/search/searchBar/search-bar.tsx
react-instantsearch-core  src/components/search/searchBar/search-hits.tsx
react-instantsearch-core  src/components/search/searchBar/search-suggestion.tsx
gatsby-link               src/templates/Introduction/components/cert-challenge.tsx

--- UNUSED EXPORTS (46)
DonationOptionsText              src/components/Donation/donation-text-components.tsx
DonationSupportText              src/components/Donation/donation-text-components.tsx
PaypalButton                     src/components/Donation/paypal-button.tsx
sagas                            src/components/Flash/redux/index.ts
NavLinks                         src/components/Header/components/nav-links.tsx
searchIndexNameSelector          src/components/search/redux/index.js
updateSearchIndexName            src/components/search/redux/index.js
SearchBarOptimized               src/components/search/searchBar/search-bar-optimized.tsx
SearchBar                        src/components/search/searchBar/search-bar.tsx
CertificationSettings            src/components/settings/certification.js
updateCurrentChallengeId         src/redux/actions.js
initialState                     src/redux/index.js
defaultFetchState                src/redux/index.js
CurrentCertsPropType             src/redux/prop-types.ts
UserPropType                     src/redux/prop-types.ts
saveChallengeSaga                src/redux/save-challenge-saga.js
sessionMetaSelector              src/redux/selectors.js
defaultDonationFormState         src/redux/types.ts
defaultFetchState                src/redux/types.ts
CompletionModalInner             src/templates/Challenges/components/completion-modal.tsx
getCompletedPercent              src/templates/Challenges/components/completion-modal.tsx
HelpModal                        src/templates/Challenges/components/help-modal.tsx
ShortcutsModal                   src/templates/Challenges/components/shortcuts-modal.tsx
VideoModal                       src/templates/Challenges/components/video-modal.tsx
ToolPanel                        src/templates/Challenges/projects/tool-panel.tsx
replaceNBSP                      src/templates/Challenges/rechallenge/transformers.js
testJS$JSX                       src/templates/Challenges/rechallenge/transformers.js
checkChallenge                   src/templates/Challenges/redux/actions.js
lockCode                         src/templates/Challenges/redux/actions.js
updateJSEnabled                  src/templates/Challenges/redux/actions.js
updateSuccessMessageSaga         src/templates/Challenges/redux/current-challenge-saga.js
currentChallengeSaga             src/templates/Challenges/redux/current-challenge-saga.js
executeChallengeSaga             src/templates/Challenges/redux/execute-challenge-saga.js
executeCancellablePreviewSaga    src/templates/Challenges/redux/execute-challenge-saga.js
executeCancellableChallengeSaga  src/templates/Challenges/redux/execute-challenge-saga.js
currentTabSelector               src/templates/Challenges/redux/selectors.js
buildBackendChallenge            src/templates/Challenges/utils/build.ts
buildJSChallenge                 src/templates/Challenges/utils/build.ts
buildDOMChallenge                src/templates/Challenges/utils/build.ts
Block                            src/templates/Introduction/components/block.tsx
CertChallenge                    src/templates/Introduction/components/cert-challenge.tsx
handledErrorSymbol               src/utils/handled-error.ts
wrapHandledError                 src/utils/handled-error.ts
pathParsers                      src/utils/path-parsers.ts
pathsMap                         utils/challenge-types.js
injectConditionalTags            utils/tags.tsx

--- UNUSED TYPES (17)
LoginProps                interface  src/components/Header/components/Login.tsx
AuthOrProfileProps        interface  src/components/Header/components/auth-or-profile.tsx
MenuButtonProps           interface  src/components/Header/components/menu-button.tsx
NavLinksProps             interface  src/components/Header/components/nav-links.tsx
UniversalNavProps         interface  src/components/Header/components/universal-nav.tsx
HeaderProps               interface  src/components/Header/index.tsx
Validator                 type       src/components/formHelpers/form-validators.tsx
FormProps                 type       src/components/formHelpers/form.tsx
FileKeyChallenge          type       src/redux/prop-types.ts
SavedChallenges           type       src/redux/prop-types.ts
ClaimedCertifications     type       src/redux/prop-types.ts
CertTest                  type       src/redux/prop-types.ts
AllMarkdownRemark         type       src/redux/prop-types.ts
Required                  type       src/redux/prop-types.ts
DefaultDonationFormState  interface  src/redux/types.ts
DefaultFetchState         interface  src/redux/types.ts
HandledError              type       src/utils/handled-error.ts

--- DUPLICATE EXPORTS (4)
PayPalButtonScriptLoader, default src/components/Donation/paypal-button-script-loader.tsx
UniversalNav, default             src/components/Header/components/universal-nav.tsx
Header, default                   src/components/Header/index.tsx
Map, default                      src/components/Map/index.tsx

**Comment by ojeytonwilliams** [comment]
Please remember to read the [contribution guidelines](https://contribute.freecodecamp.org/#/index) and that we do not assign issues. The first PR that solves the issue will be merged.

**Comment by Devanshu011** [comment]
I want to work on these.

**Comment by vedo18** [comment]
Hello, can you assign this issue to me. I am a good participant to solve this issue.

**Comment by PiyushAryan** [comment]
Assign me this issue I want to work on this

**Comment by anupp-11** [comment]
Hello! Please assign me on this issue, i want to work on this.

**Comment by getcoder-top** [comment]
hiii, i want to contribute to this please accept my pull request.
i use freecodecamp and want to contribute to it

**Comment by sucheta90** [comment]
## Are the Issues still open?
I am a Frontend Developer looking to contribute to Open Sources. Here's my Github profile [https://github.com/sucheta90](url) and my LinkedIn profile [https://github.com/sucheta90](url), if you wish to take a look.

**Comment by raisedadead** [comment]
Issues tagged help-wanted are open for contributions, this particular one included. Please follow our [contributing guidelines](https://contribute.freecodecamp.org) to learn more about contributing.

**Comment by sravanthbaratam** [comment]
I see a merged pull request for the issue. Are there any other unused files that need to be removed for the issue?

**Comment by ojeytonwilliams** [comment]
@sravanthbaratam if you run `npm run knip:all` you can see a list of files and exports that may not be necessary.  Unfortunately, either due to an problem with knip or with our configuration, there are things on the list that shouldn't be.

To close the issue we would need two things

- `knip.jsonc` to be updated so that it has no false positives. It is missing some missing "entry" files like cypress-install.js, so those will need to be added (ideally via globs)
- `knip:all` to find no issues

**Comment by naomi-lgbt** [comment]
@ojeytonwilliams to circle back on the discussion in #50498...

Could we piece-meal dependency removals in smaller PRs? I think the approach here is to remove dependencies that we *can* remove (that is, without causing build errors or test failures), which will give us a smaller list to work with the false positives and tighten up the config.

**Comment by ojeytonwilliams** [comment]
Yeah, that makes sense.  I suspect that there are testing gaps, so doing it a bit at a time should help us plug those.

**Comment by ieahleen** [comment]
It seems knip hasn't been updated in a while, so the scripts give errors.
The error:
<details>
```
ilenia@Ilenia:~/freeCodeCamp/freeCodeCamp$ pnpm knip

> @freecodecamp/freecodecamp@0.0.1 knip /home/ilenia/freeCodeCamp/freeCodeCamp
> npx -y knip@1 --include files

Resolving plugin configuration files...
/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/modes/posix/rules/syntaxerror-oncontinue.js:7
                        throw new SyntaxError('Unclosed ' + tk.value);
                              ^

SyntaxError: Unclosed '
    at /home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/modes/posix/rules/syntaxerror-oncontinue.js:7:10
    at Object.next (/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/map-iterable/index.js:35:18)
    at Object.next (/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/map-iterable/index.js:33:30)
    at Object.lex (/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/shell-lexer.js:6:31)
    at lex (/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/modes/posix/built-grammar.js:321:27)
    at Parser.parse (/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/modes/posix/built-grammar.js:334:26)
    at parse (/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/index.js:34:22)
    at setCommandExpansion (/home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/modes/posix/rules/command-expansion.js:17:21)
    at /home/ilenia/.npm/_npx/8edc7500d4586efd/node_modules/bash-parser/src/modes/posix/rules/command-expansion.js:37:12
    at Array.map (<anonymous>)

Node.js v20.8.0
 ELIFECYCLE  Command failed with exit code 1.
```
</details>

I have followed @raisedadead suggestion and used `npx -y knip --include files`

It gives this output:
<details>
```
api-server/ecosystem.config.js
api-server/src/common/config.global.js
api-server/src/common/models/User-Credential.js
api-server/src/common/models/block.js
api-server/src/common/models/user.js
api-server/src/common/utils/empty-protector.js
api-server/src/production-start.js
api-server/src/server/boot/a-extend-built-ins.js
api-server/src/server/boot/a-increase-listeners.js
api-server/src/server/boot/authentication.js
api-server/src/server/boot/donate.js
api-server/src/server/boot/explorer.js
api-server/src/server/boot/news.js
api-server/src/server/boot/randomAPIs.js
api-server/src/server/boot/restApi.js
api-server/src/server/boot/status.js
api-server/src/server/boot/t-wiki.js
api-server/src/server/boot/user.js
api-server/src/server/boot/z-not-found.js
api-server/src/server/config.development.js
api-server/src/server/config.local.js
api-server/src/server/config.production.js
api-server/src/server/datasources.development.js
api-server/src/server/datasources.production.js
api-server/src/server/middlewares/constant-headers.js
api-server/src/server/middlewares/cookie-parser.js
api-server/src/server/middlewares/csp.js
api-server/src/server/middlewares/csurf-error-handler.js
api-server/src/server/middlewares/csurf-set-cookie.js
api-server/src/server/middlewares/csurf.js
api-server/src/server/middlewares/error-handlers.js
api-server/src/server/middlewares/express-extensions.js
api-server/src/server/middlewares/flash-cheaters.js
api-server/src/server/middlewares/ms-username.js
api-server/src/server/middlewares/passport-login.js
api-server/src/server/middlewares/rate-limit.js
api-server/src/server/middlewares/sentry-request-handler.js
api-server/src/server/middlewares/sentry-tracing-handler.js
api-server/src/server/middlewares/sessions.js
api-server/src/server/middlewares/survey.js
api-server/src/server/middlewares/user-token.js
api-server/src/server/models/auth-token.js
api-server/src/server/models/donation.js
api-server/src/server/rss/index.js
api-server/src/server/rss/lybsyn.js
api-server/src/server/utils/auth.js
api-server/src/server/utils/cast-to-observable.js
api-server/src/server/utils/cookieConfig.js
api-server/src/server/utils/lang-passthrough-urls.js
api-server/src/server/utils/publicUserProps.js
api-server/src/server/utils/react.js
api-server/src/server/utils/stripeHelpers.js
api-server/src/server/utils/url-utils.js
api-server/src/server/utils/validators.js
client/gatsby-browser.js
client/gatsby-ssr.js
client/i18n/config.js
client/src/assets/icons/dot-net-logo.tsx
client/src/assets/icons/fail.tsx
client/src/assets/icons/help.tsx
client/src/assets/icons/initial.tsx
client/src/assets/icons/lightbulb.tsx
client/src/assets/icons/quote.tsx
client/src/assets/icons/reset.tsx
client/src/client-only-routes/show-unsubscribed.tsx
client/src/client-only-routes/show-user.tsx
client/src/components/Donation/donation-text-components.tsx
client/src/components/growth-book/codeally-down.tsx
client/src/components/growth-book/growth-book-redux-connector.tsx
client/src/components/growth-book/growth-book-wrapper.tsx
client/src/components/share/index.tsx
client/src/html.tsx
client/src/pages/blocked.tsx
client/src/pages/donate.tsx
client/src/pages/settings.tsx
client/src/pages/unsubscribed.tsx
client/src/pages/update-email.tsx
client/src/pages/user.tsx
client/src/templates/Challenges/classic/action-row.tsx
client/src/templates/Challenges/classic/desktop-layout.tsx
client/src/templates/Challenges/classic/editor-tabs.tsx
client/src/templates/Challenges/classic/editor.tsx
client/src/templates/Challenges/classic/lower-jaw.tsx
client/src/templates/Challenges/classic/mobile-layout.tsx
client/src/templates/Challenges/classic/multifile-editor.tsx
client/src/templates/Challenges/classic/show.tsx
client/src/templates/Challenges/codeally/show.tsx
client/src/templates/Challenges/components/challenge-description.tsx
client/src/templates/Challenges/components/help-modal.tsx
client/src/templates/Challenges/components/hotkeys.tsx
client/src/templates/Challenges/components/notes.tsx
client/src/templates/Challenges/components/output.tsx
client/src/templates/Challenges/components/preview-portal.tsx
client/src/templates/Challenges/components/prism-formatted.tsx
client/src/templates/Challenges/components/reset-modal.tsx
client/src/templates/Challenges/components/shortcuts-modal.tsx
client/src/templates/Challenges/components/side-panel.tsx
client/src/templates/Challenges/components/test-suite.tsx
client/src/templates/Challenges/components/tool-panel.tsx
client/src/templates/Challenges/components/video-modal.tsx
client/src/templates/Challenges/components/video-player.tsx
client/src/templates/Challenges/exam/components/exam-results.tsx
client/src/templates/Challenges/exam/components/exit-exam-modal.tsx
client/src/templates/Challenges/exam/components/finish-exam-modal.tsx
client/src/templates/Challenges/exam/components/foundational-c-sharp-survey-alert.tsx
client/src/templates/Challenges/exam/components/foundational-c-sharp-survey.tsx
client/src/templates/Challenges/exam/components/missing-prerequisites.tsx
client/src/templates/Challenges/exam/components/survey-modal.tsx
client/src/templates/Challenges/exam/show.tsx
client/src/templates/Challenges/ms-trophy/link-ms-user.tsx
client/src/templates/Challenges/ms-trophy/show.tsx
client/src/templates/Challenges/odin/show.tsx
client/src/templates/Challenges/projects/backend/show.tsx
client/src/templates/Challenges/projects/frontend/show.tsx
client/src/templates/Challenges/projects/solution-form.tsx
client/src/templates/Challenges/projects/tool-panel.tsx
client/src/templates/Challenges/video/show.tsx
client/src/templates/Introduction/components/cert-challenge.tsx
client/src/templates/Introduction/components/legacy-links.tsx
client/src/templates/Introduction/components/super-block-intro.tsx
client/src/templates/Introduction/intro.tsx
client/src/templates/Introduction/super-block-intro.tsx
client/src/utils/tone/editor-config.ts
client/src/utils/tone/editor-notes.ts
client/tailwind.config.js
client/utils/tags.tsx
curriculum-server/source-curriculum.ts
tools/challenge-editor/client/src/setup-tests.ts
tools/challenge-helper-scripts/rename-challenge-files.js
tools/challenge-parser/parser/plugins/add-ids.js
tools/challenge-parser/parser/tools/full-parse.js
tools/challenge-parser/parser/tools/generate-ast.js
tools/challenge-parser/parser/tools/inspect-ast.js
tools/challenge-parser/parser/tools/parse-md.js
tools/scripts/redirect-gen.ts
tools/scripts/seed-exams/add-nano-ids.js
web/src/data-fetching/get-curriculum.ts
web/src/page-templates/challenge.tsx
web/src/page-templates/superblock.tsx
web/src/pages/learn/[...id].tsx
web/src/pages/learn/[superblock]/[blockOrId].tsx
web/src/pages/learn/[superblock]/[blockOrId]/[dashedName]/[id].tsx
```
</details>

So I will try to see what can be removed without causing issues.

**Comment by moT01** [comment]
Closing this as the list is outdated. If anyone objects, feel free to leave a comment. Thanks and happy coding 🎉
