### ISSUE TITLE
Bonfire Where do I belong crashes Chrome

### ISSUE THREAD

**Issue by sweann** [FreeCodeCamp/FreeCodeCamp#4797]
I put some code in and Chrome crashes so that I can't even reset my code! I can't copy the code either to show you! It looks to be reset in both IE and Firefox. Rebooting did not help.

**Comment by ltegman** [comment]
Please follow [this wiki article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage) on how to remove broken saved code from your browser's local storage.

Thanks and happy coding!
