### ISSUE TITLE
Reword docs, news articles, and other from remote containers to dev containers

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#47981]
### Describe the Issue

The VS Code "remote containers" extension is now called "dev containers". This affects documentation, news articles, readme's, and probably other stuff where we reference the remote containers extension. The biggest issue is probably that the VS Code command to run the extension changed - so where we tell people to run the `Remote Containers: Rebuild Container`, it's now `Dev Containers: Rebuild Container`.

If you see somewhere "remote containers" is still being used, you can let us know here.

### Affected Page

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

### Recommended fix or suggestions

We should change the wording where necessary. This will be a lot of stuff @ShaunSHamilton and I have worked on, so we will probably need to take care of most of it.

**Comment by ieahleen** [comment]
A few hits:

 - [ ] https://www.freecodecamp.org/news/near-curriculum/
 - [ ] https://www.freecodecamp.org/news/what-is-docker-learn-how-to-use-containers-with-examples/
 - [ ] https://web3.freecodecamp.org/near
 - [ ] https://www.freecodecamp.org/news/put-your-dev-env-in-github/
 - [ ] https://web3.freecodecamp.org/web3
 - [ ] freecodecamp.org/news/solana-curriculum/
 - [ ] https://www.freecodecamp.org/news/web3-curriculum-open-beta/
 - [ ] https://www.freecodecamp.org/news/how-to-run-freecodecamps-relational-databases-curriculum-using-docker-vscode-and-coderoad/

All the articles are for admin/editor access on Ghost, but the web3 website could be opened for contributions, or you could want to do that yourself too.

**Comment by ieahleen** [comment]
These are on i18n news
 - [ ] https://www.freecodecamp.org/portuguese/news/curso-de-bancos-de-dados-relacionais-como-aprender-sql-no-vscode-usando-o-docker-e-o-freecodecamp/
 - [ ] https://chinese.freecodecamp.org/news/how-to-run-freecodecamps-relational-databases-curriculum-using-docker-vscode-and-coderoad/
 - [ ] https://www.freecodecamp.org/espanol/news/por-favor-todos-pongan-su-entorno-de-desarrollo-en-github/
 - [ ] https://chinese.freecodecamp.org/news/web3-curriculum-open-beta/
 - [ ] https://www.freecodecamp.org/espanol/news/curso-de-base-de-datos-relacional-como-aprender-sql-en-vs-code-usando-docker-y-freecodecamp/

And I have added a couple more links above

**Comment by ieahleen** [comment]
> * [ ]  https://web3.freecodecamp.org/near
> * [ ]  https://web3.freecodecamp.org/web3
> * [ ]  https://web3.freecodecamp.org/solana


For these, it's this file here
https://github.com/freeCodeCamp/web3-site/blob/main/src/pages/superblock.tsx

**Comment by naomi-lgbt** [comment]
I fixed up the English articles, except for https://www.freecodecamp.org/news/put-your-dev-env-in-github/ which requires new screenshots - we may want to see if the author is interested in updating that one.

**Comment by getcoder-top** [comment]
is the issue still open

**Comment by ShaunSHamilton** [comment]
@getcoder-top 

> Only issues with the [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted) or [ first timers only](https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only) label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.
> 
> If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/
> 
> If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)


---

The changes to resolve this PR require admin/write access to the `/news` platform.

**Comment by ShaunSHamilton** [comment]
@naomi-lgbt Did you ping/email/contact the author yet?

> I fixed up the English articles, except for https://www.freecodecamp.org/news/put-your-dev-env-in-github/ which requires new screenshots - we may want to see if the author is interested in updating that one.

**Comment by naomi-lgbt** [comment]
Not yet. On the todo list.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for putting this detailed list together @moT01 and @ieahleen, and for everyone's help updating these articles.

I went in and updated the text for the last English article, "Please, everyone, put your entire development environment in Github", and added a note near the beginning about the new extension name. And I emailed the author in case their interested in taking new screenshots.

I also updated most of the remaining translated articles. All the updates should go live within the next 2-6 hours, or so.

The only article I need some extra help with is adding the note to "Por favor, todos, pongan su entorno de desarrollo en GitHub". I'll reach out to Rafa in the chat for help with that.
