### ISSUE TITLE
Waypoint:Make Dead Link, no base text provided to make edits on

### ISSUE THREAD

**Issue by acarey3** [FreeCodeCamp/FreeCodeCamp#4798]
Many of the other steps include the previous text code to enter the new steps, however, in this instance, the text edit box is empty. The a element I should be editing with a # is not there. And the instructions refer to this previous element/code.

Perhaps this is a cache problem?

**Comment by SaintPeter** [comment]
Try clicking the "Reset" Button.  Sometimes, for unknown reasons, the challenge seed does not load.  If this problem persists, let us know.  We just released a new version of the backend, so there may be bugs.

**Comment by SaintPeter** [comment]
@acarey3 Has this issue been resolved or are you still having trouble?

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
