### ISSUE TITLE
Hide breadcrumbs when in CodeAlly container (relational database challenge)

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#47980]
### Describe the Issue

A [recent PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/47577) changed the way the breadcrumbs behave a little or something. They are now showing up when you are inside an embedded CodeAlly container and it doesn't look quite right (see screenshot).

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate
2. Click on Start the course
3. Click run with CodeAlly - and do whatever else you need to do to get the container loaded
4. See breadcrumbs at the top

### Expected behavior

The breadcrumbs to be hidden - only once you leave the screen with the challenge info - e.g. the main page you land on when visiting the link above.

### Screenshots

![Screen Shot 2022-10-11 at 8 53 13 AM](https://user-images.githubusercontent.com/20648924/195110171-7657be77-aa9b-4dd1-bd0a-5eca28dbbb4b.png)

**Comment by ieahleen** [comment]
The files to change will be somewhere in what #47577 changed, I am opening this for contributions.

If you would like to contribute, please read the [Contribution Guidelines](https://contribute.freecodecamp.org/#/) and reach out in the contributors subforum or chatroom for any questions.

**Comment by moT01** [comment]
I think I added something in redux for showing the iframe - we could probably use that to determine if we want to display the breadcrumbs or not. e.g. `if (showIframe) -> hide breadcrumbs`.

**Comment by A-5ingh** [comment]
@ieahleen I'd like to contribute to this.

**Comment by Prince-Mendiratta** [comment]
@moT01 We do want to show the breadcrumbs on this page, right?
![image](https://user-images.githubusercontent.com/54077356/195153681-c8a6d56c-88e3-4e5a-948e-f77641efd2b7.png)

This page also uses breadcrumbs but also uses the iframe.

**Comment by moT01** [comment]
correct, only on the main page you first land on [here](https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate) - after you click start the course, hide them.

**Comment by ieahleen** [comment]
I think Tom meant to say that also the page with the "Run with CodeAlly" button should not have breadcrumbs

**Comment by moT01** [comment]
Yes, I misread that other message. We only want the breadcrumbs on the page you first land on when you click that link I shared. After you click 'start the course', hide the bread crumbs.
