### ISSUE TITLE
Add public/js to .gitignore

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#4799]
I'm seeing new files that look generated by gulp, etc, in my public/js folder?

I'm not sure which are source files (if any) and which are generated and should be ignored?

**Comment by BerkeleyTrue** [comment]
Yes. Source files are in client/ generated in public/js

**Comment by SaintPeter** [comment]
I'll write a PR.

**Comment by BerkeleyTrue** [comment]
Sorry, misspoke. Not all files in public/js are generated.
