### ISSUE TITLE
Forum Post Withdrawal

### ISSUE THREAD

**Issue by crosscris** [FreeCodeCamp/freecodecamp#48]
Discourse may not be deleting posts withdrawn by author; withdrawn posts are supposedly programmed to be withdrawn 24 hours after withdrawal. I have attached a picture of an issue and anonymized the original poster.

The issue was found on google chrome on windows 7.

Please note, the post was posted 4 days ago. It is possible author may have withdrawn post recently. If post in question still exists by Sunday, 1/25, posts may not be self-withdrawing.  
![Uploading Discourse Post Withdrawal Bug.JPG . . .]()

.....if picture is not visible,
feel free to find bug at http://forum.freecodecamp.com/t/seattle-area-free-code-campers/141/18

**Comment by crosscris** [comment]
Checked the post withdrawal issue 5 days after initial find. The posts to be withdrawn are still in the forum thread. Attached is a picture of post that is not withdrawn - blacked for anonymity.
![1 28 2015 discourse post withdraw fail](https://cloud.githubusercontent.com/assets/9522511/5944940/cd6691a0-a6df-11e4-8b10-2e67cb8ada3b.JPG)

**Comment by terakilobyte** [comment]
I'm going to close this issue as there is momentum to go with a different forum solution that appears to be far more performant on small instances.
