### ISSUE TITLE
When use image is broken camper news image breaks.

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#480]
Steps to repeat.

* Use twitter for signing
* update twitter image

> twitter breaks last image url
>FCC shows default camper image for user image

* post link to camper news

>Camper news uses user image url, which at this point is broken

* Update image url to new twitter image url

> User image is updated
> Camper news image is not updated, still broken.

![hot_stories_currently_trending_on_camper_news___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/7790364/d8fea9d4-0239-11e5-8007-d44719873e52.png)

possible solutions:

* When posting link, ping user image and look for 200 code, if positive use image, else use default image. (only checks once, only slows down link posting)
* When rendering camper news pull image url from user. (this would be costly and would slow down rendering)

**Comment by QuincyLarson** [comment]
@berkeleytrue This is costly indeed, which is why we're storing the image url in the camper news story object itself instead of performing a lookup. Broken images SHOULD be automatically replaced with the default camper news icon. I'm not sure why my code is failing here. I'll look into it.

**Comment by BerkeleyTrue** [comment]
Looks like logic works when clicking on discuss
![object_playground__the_definitive_guide_to_object-oriented_javascript___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/7805529/d3de077a-0328-11e5-9dd8-f1f4f628d4a1.png)

**Comment by BerkeleyTrue** [comment]
fixed
