### ISSUE TITLE
Project to build a quiz doesn’t teach method attribute

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48002]
### Describe the Issue

Step 14 of the “Learn Accessibility by Building a Quiz” project asks people to “ make the form submit to https://freecodecamp.org/practice-project/accessibility-quiz, using the correct method”

And when they try what they learned so far (adding the action attribute) they are unable to pass and instructed via hints that they needed a method attribute set to post value.

this method attribute and post value were never introduced in earlier projects (as far as I can tell) and no information is given as to why they are needed here.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-14

### Your code

```

```

### Expected behavior

We need a separate step to explain the method attribute. It seems like an important topic. I am not sure why it was not introduced in the earlier quiz form project.

### System

N/A

### Additional context

https://forum.freecodecamp.org/t/form-submission-needs-method-attribute/561994?u=hbar1st

**Comment by ShaunSHamilton** [comment]
Again, we need to be careful with the way we are constantly updating these projects. We need to keep in mind the actual learning outcomes for the projects; this one aims to teach accessibility. So, this is not the project to teach about the `method` attribute.

If we change anything here, it might make more sense to add a lesson to the `Registration Form` project

**Comment by moT01** [comment]
The registration form is where it makes sense to me to add an explanation about this. That form doesn't have a method attribute so it uses `get` by default. The form includes sensitive information, so it fits nicely to add a step adding a post method there. I would be fine adding a help wanted label to do that - or we can work out more details if we want here first.

**Comment by ShaunSHamilton** [comment]
It should be quite simple to add one/two lesson/s in the registration-form project. So, I am happy opening this up for help.

**Goal**

- Add one (two if needed) lessons to the `learn-html-forms-by-building-a-registration-form` project
- This lesson should teach about the `method` attribute
- The goal should be to add `method="post"`

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Arghya46** [comment]
Hello sir, Can u assign this issuet to me?

**Comment by RohitPatel1122** [comment]
@ShaunSHamilton I have raised the PR for the fix. Kindly review.
