### ISSUE TITLE
Claim Front End Certificate with dead links and error message

### ISSUE THREAD

**Issue by pwdd** [FreeCodeCamp/FreeCodeCamp#4800]
The steps to reproduce the problem: 
1. All the Bonfires and Ziplines (basic and intermediate) are done (not all waypoints);
2. Click link 'Waypoint: Claim Your Front End Development Certificate' from 'Map' page;
3. Click 'go to next step';
4. On second screen (plagiarism), click on 'Open link in a new tab' and no tab gets opened. Although no tab opens, the link 'go to my next step' gets clickable;
5. On screen 3, 'front end dev certificate requirements', where it suppose to check if basic and intermediate Bonfires and Ziplines are completed, click 'open link in a new tab';
6. No tab opens and return error message;

**Comment by piecedigital** [comment]
Just came here to submit the same issue.

**Comment by robeerob** [comment]
What browser are you using and what is the error message?

**Comment by ramirozap** [comment]
Challenge Map renders on the samer page and a message is displayed : "Oops! Something went wrong. Please try again later"

**Comment by BerkeleyTrue** [comment]
I'm looking into it.

**Comment by BerkeleyTrue** [comment]
Looks like there was corrupted db seed attempt. Should be fixed now.

**Comment by pwdd** [comment]
Hi. It now renders the certificate, but the links are still dead (the 'open in a new tab' links) and the certificate has no name/username on it. 
![screen shot 2015-11-30 at 8 51 51 am](https://cloud.githubusercontent.com/assets/7341279/11478078/cdf2987a-973f-11e5-9906-a00400253ccd.png)

**Comment by BerkeleyTrue** [comment]
@pwdd There are no links. They hit api endpoints.

Your name is pulled from Github. Please update you're Github (we recommend adding an actual picture of yourself as well). Then sign out and sign in again on FCC.

Happy Coding!

**Comment by pwdd** [comment]
@BerkeleyTrue Thanks, but I changed my name on my Github profile, tried the 'claim' process again, and the 'name' field on the certificate is still blank. And the 'open link in a new tab' as text of the button is a little misleading if nothing will open ;-)

**Comment by alexkond** [comment]
I have the same problem! Tried in Chrome, Firefox and also in Explorer!

**Comment by GaneshmKumar** [comment]
When I tried to claim my front end development certificate I got a message showing 'Oops! something went wrong. Please try again later' .The error in chrome console is **Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience**.
![screenshot from 2016-04-08 06-41-04](https://cloud.githubusercontent.com/assets/16433336/14370571/0b37b5d0-fd4d-11e5-999b-d543947ea2af.png)
