### ISSUE TITLE
Line goes against our challenge document in building a registration form project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48011]
### Describe the Issue

In step 8 of building a registration form project, there is a text that go against [challenge document](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=challenge-descriptionsinstructions)

> To spruce the project up, let us add some CSS.

This should be changed to 

> To spruce the project up, add some CSS.

Here is the markdown file https://github.com/freeCodeCamp/freeCodeCamp/blob/1459bc6879ce700830e710f30764b4562f2f52d3/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f1922fcbd2410527b3bd89.md#L11

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-8

### Additional context

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by PiyushKeshari24** [comment]
Can you please review and merge my PR? #48012

**Comment by raisedadead** [comment]
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org) specifically the "How to open a PR" section.

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

**Comment by DavidRod1865** [comment]
If this PR is still available, I'll like to work on it.

**Comment by soumya0S** [comment]
I would want to make a Pull request if this issue still exists.

**Comment by sonicx180** [comment]
> As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org) specifically the "How to open a PR" section.
> 
> We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.
> 
> Some examples of this are:
> 
> 1. Do not edit files directly through GitHub – while you can, it's not a good idea.

@raisedadead I think you can use github.dev for that.

**Comment by PiyushKeshari24** [comment]
@raisedadead Please accept my apologies. I am new and still learning.

Things which I implemented after learning from your comments are.
- I have updated the PR title to comply with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- I won't add mentions/review requests unnecessarily
- From now on I will create a separate branch for any changes and not commit directly to the main branch.

Point 3 is not clear to me. How would I link the PR to the issue?
I am trying to follow [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) article.

> As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org) specifically the "How to open a PR" section.
> 
> We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.
> 
> Some examples of this are:
> 
> 1. Do not edit files directly through GitHub – while you can, it's not a good idea.
> 2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
> 3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
> 4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
> 5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.
> 
> We appreciate you taking the time to help us, and we hope to see more contributions from you.
> 
> Happy Contributing.

**Comment by Sboonny** [comment]
@PiyushKeshari24 thank you for taking care of this.

@DavidRod1865, @soumya0S. The contribution guideline, that  raisedadead linked should answer most of your questions.

@sonicx180 there is no mentioning of GitHub Dev environment in the guideline, if you are uncomfortable setting it up locally, our section about Gitpod should do the trick.
