### ISSUE TITLE
My error is approved !? Responsive Web Des./Label design /step 58

### ISSUE THREAD

**Issue by Dumitrash-C** [freeCodeCamp/freeCodeCamp#48020]
### Describe the Issue

I’ve made a mistake in the code and it got accepted (screenshot below).
Instead of “_margin-left: 2em_” it accepts my wrong answer  of “_margin: 2em_”.
Seems to be a bug. I’m using the latest Firefox browser with no AdBlocker.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-58

### Your code

```
.dbl-indent {
  margin: 2em;
}
```

### Expected behavior

Test

Sorry, your code does not pass. Keep trying.
Hint

Your **.dbl-indent** selector should have a **margin-left** _only_ property set to 2em.

### Screenshots

This is my wrong outcome accepted as correct:
![step_58_label_design_new_resp_web_des](https://user-images.githubusercontent.com/87341676/195511053-9f185220-6c86-46dd-bb38-59da8d7674ee.png)

But in the next step you can see it automticaly corrected:
![step_59_label_design_new_resp_web_des](https://user-images.githubusercontent.com/87341676/195512667-b304bb9a-07d5-4598-8bc8-95545e9350a4.png)

### System

- Device: [Laptop, i5-7300HQ @2.5 GHz, 24gb ram]
- OS: [Windows 10, 64 bit]
- Browser: [Firefox]
- Version: [105.0.3 (64-bit)]

**Comment by Mani-07** [comment]
@Dumitrash-C  - Can you assign this defect to me. I will take care of this.

**Comment by Dumitrash-C** [comment]
@Mani-07 - It seems like I'm not able to. 
Could this [status: waiting triage](https://github.com/freeCodeCamp/freeCodeCamp/labels/status%3A%20waiting%20triage) be the issue? Needs approval from a moderator as a valid issue.

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

I do not think there is any issue here. You have accomplished the goal of adding the correct amount of left margin.

At the end of the day, we cannot test for all cases of: You should add left margin, without changing the colour, font size, padding, etc...

I will leave this up for discussion

**Comment by Dumitrash-C** [comment]
@ShaunSHamilton 
Thnaks for the reply. I did use different types od approaches before and am grateful for not being narrowed down with my approach.

**Comment by Sembauke** [comment]
I think we should close this, the answer is correct. You have added a  `margin` of `2em` . But I see what you mean as it specifically asks you to add a margin on the left. Not on all sides.

**Comment by ojeytonwilliams** [comment]
This isn't something we need to fix.  As Shaun said, we err on the side of leniency. Since the text does not specifically prohibit you from adding other margins, the tests should not enforce that.
