### ISSUE TITLE
hint for Learn Typography by Building a Nutrition Label - Step 50 needs a space between class names

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48043]
### Describe the Issue

The first hint shown in step 50 of Learn Typography by Building a Nutrition Label places two class names together without any space in between so it is hard to read.
The hint is shown if we do not enter any code and simply click on the Check Your Code button.

>Hint
> You should create a new p element at the end of your .daily-value.sm-text element.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-50

### Your code

N/A

### Expected behavior

Need to have a single space in between the two class names for better readability.

### System

N/A

**Comment by ieahleen** [comment]
`.daily-value.sm-text` this is a selector for an element that has both classes, a space in between would change the meaning

**Comment by nayabatir1** [comment]
It's a selector but for display purpose (hint text) we can separate them.

**Comment by ieahleen** [comment]
Or
> You should create a new `p` element at the end of your element having the classes `daily-value` and `sm-text`.

I don't want to see a wrong selector, `.daily-value .sm-text` means the element with classe `sm-text` descendant of the element with class `daily-value`

**Comment by nayabatir1** [comment]
`div.daily-value` it references only one dom node. If you feel like we can use this

**Comment by ieahleen** [comment]
I am going to change all the project soon, so this may even be a moot point...

**Comment by naomi-lgbt** [comment]
Could just change it to `.daily-value` not sure why we need to mention both classes.

**Comment by rajesh604** [comment]
Can you tell me how to improve my programming skills to start working for opensource organisations in gsoc i know programming languages but I am not able to solve issues

**Comment by hbar1st** [comment]
Actually it would be helpful to repeat the instruction "after your last .divider" in the hint as when reading the current hint, the referenced element is not even in the current view (you have to scroll up past the editing region to find it)

**Comment by nayabatir1** [comment]
> Could just change it to `.daily-value` not sure why we need to mention both classes.

I agree `.daily-value` is sufficient.

**Comment by SanskarJain007** [comment]
We could just change it to `.daily-value` .

**Comment by Kannan0017** [comment]
We could just change that to .daily-value .

**Comment by getcoder-top** [comment]
can i work on it

**Comment by getcoder-top** [comment]
please assign this issue to me

**Comment by ieahleen** [comment]
@getcoder-top We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by SHAKIRULLA** [comment]
if you want all the solutions of freecodecamp.org, you are free to message me
