### ISSUE TITLE
Cannot understand instructions

### ISSUE THREAD

**Issue by Serial-Coder** [FreeCodeCamp/FreeCodeCamp#4804]
Waypoint: Change Text Inside an Element Using jQuery Incomplete 

Asks to italicize the text, but also that is "otherwise unchanged". Attached is a screenshot of my code, seems to be italicized, a no other changes; but I cannot pass the waypoint. 

Thanks in advanced
![screen shot 2015-11-30 at 12 56 39 pm](https://cloud.githubusercontent.com/assets/15092795/11470941/07163cf2-9762-11e5-8f0f-2bbf42cd4a5b.png)

**Comment by AlyxMoon** [comment]
Don't want to give the answer away completely, but you do have a typo.
The text should remain the same. Originally, the text is "#target4" but in the script once you change it, it's "target4"

**Comment by Serial-Coder** [comment]
Whaat? i've been looking for like 10 min... Thanks, I'll find it :)


*Luis F. Vidal *
*Partnership & Marketing Manager*
Email. lfv@betternow.org
Tlf.: +34 91 186 8840




<https://www.facebook.com/BetterNow.org?ref=hl>

**Comment by ltegman** [comment]
@AlyxMoon is correct.

Thanks and happy coding!

**Comment by Serial-Coder** [comment]
I found the typo!! :) I must train my eyes...
