### ISSUE TITLE
Bonfire: Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by gsgwebdev** [FreeCodeCamp/FreeCodeCamp#4806]
Link: http://www.freecodecamp.com/challenges/bonfire-sum-all-odd-fibonacci-numbers

My algorithm returns the correct values, but the tests failed.

```
function fibonacci(x)
{
  // fibonacci starts from 1,1
  var arr = [1,1];
  
  // starts from 2 bc the array already have two items
  for (var i = 2; i < x; i++)
  {
    // the fibonacci number will be pushed only if is
    // smaller than the argument 'x'
    if (arr[arr.length-1] + arr[arr.length-2] <= x)
    {
      arr.push(arr[arr.length-1] + arr[arr.length-2]);
    }
  }  
  
  // a new array to store just the odd numbers
  var oddArr = [];
  
  // iterates over the all fibonacci number and push
  // just odd numbers
  for (var y = 0, len = arr.length; y < len; y++)
  {
    if (arr[y] % 2 !== 0 && arr[y] <= x)
    {
      oddArr.push(arr[y]);
    }
  }
  
  // use reduce method to find the sum of the numbers within 'oddArr' array
  oddArr = oddArr.reduce(function(previousValue, currentValue, currentIndex, array) {
    return previousValue + currentValue;
  });
  
  return oddArr;
}
```

**Comment by ltegman** [comment]
You initializing `oddArr` globally, so after the first time you run the function you will not be starting wth an empty array and therefore will return an incorrect result.

Thanks and happy coding!

**Comment by gsgwebdev** [comment]
// a new array to store just the odd numbers
    var oddArr = [];

It is not globally, and the results returned by the function are correct. :)

**Comment by ltegman** [comment]
Apologies. I am not thinking clearly today. The real problem is that you changed the name of the function. The tests are looking for a function named `sumFibs` but your function is named `fibonacci`. Once you rename your function it will work perfectly :smile: 

Sorry for the confusion!

**Comment by gsgwebdev** [comment]
Not a problem. Yeah, the name was the problem.

Thanks for your help!
