### ISSUE TITLE
Bonfire: Drop it - Wrong test input

### ISSUE THREAD

**Issue by RohanImmanuel** [FreeCodeCamp/FreeCodeCamp#4807]
Challenge [Bonfire: Drop it](http://www.freecodecamp.com/challenges/bonfire-drop-it?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20return%20arr.filter(function(val)%20%7B%0A%20%20%20%20return%20func(val)%3B%0A%20%20%7D)%3B%0A%7D%0A%0Adrop(%5B1%2C%202%2C%203%2C%209%2C%202%5D%2C%20function(n)%20%7Breturn%20n%20%3E%202%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drop(arr, func) {
  return arr.filter(function(val) {
    return func(val);
  });
}

drop([1, 2, 3, 9, 2], function(n) {return n > 2;});

```

The last test is wrong:
It states:
*__drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, 2]__*
it should be
**drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9].**
or
**drop([1, 2, 3, 9, 2], function(n) {return n >= 2;}) should return [3, 9, 2].**

**Comment by ltegman** [comment]
This test is correct. The challenge asks you to remove elements from the front of the array until the predicate returns true. So once you reach `3` and the predicate returns true you should stop removing elements from the array, which would leave the second `2` in the array.

Thanks and happy coding!

**Comment by RohanImmanuel** [comment]
Got it
Thanks
