### ISSUE TITLE
Learn Git Lesson gives incorrect definition of soft and medium resets

### ISSUE THREAD

**Issue by stabbystabstab** [freeCodeCamp/freeCodeCamp#48079]
### Describe the Issue

There's a definition in a Relational Database Learn Git lesson that is not strictly correct. This instruction is given:

> I'm going to show you a few ways to remove or undo a commit. The first is to simply "travel back in time". You can use the `git reset` command to travel to any point in your commit history. Your current `HEAD` is a reference to the last commit you just made. Use `git reset HEAD~1` to go back one before `HEAD` .

The problem is the next instruction which says:

> This is a "soft" reset and will put the changes from the commit you undid in your working tree. You can see that it says there's unstaged changes after the reset to your file...

This was not a "soft" reset. This was a "medium" reset. `--medium` is the default. `--soft` would leave changes in the staging area.

The original author probably indended "soft" meaning "not hard" but "soft" has a very specific meaning here.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-git-by-building-an-sql-reference-object/build-an-sql-reference-object

### Your code

```
git reset HEAD~1

```

### Expected behavior

I expect to be taught that `git reset HEAD~1` is equivalent to `git reset --medium HEAD~1`, NOT `git reset --soft HEAD~1` as the lesson suggests

### System

- Device: HP laptop
- OS: 5.18.0-kali7-amd64
- Browser: Chrome
- Version: Latest

**Comment by stabbystabstab** [comment]
PR: https://github.com/freeCodeCamp/learn-git-by-building-an-sql-reference-object/pull/15

**Comment by Ayush-singla27** [comment]
hey, i am was looking into this issue. Just wanted to confirm should i also change medium to mixed as suggested by @moT01 in the above PR?

**Comment by nayabatir1** [comment]
Is this still open for contribution ?

**Comment by Ayush-singla27** [comment]
@nayabatir1  My [PR](https://github.com/freeCodeCamp/learn-git-by-building-an-sql-reference-object/pull/16)  have been merged. I think this issue will soon be closed.

**Comment by rffontenelle** [comment]
@Ayush-singla27 If your PR should close this issue, consider next time use a keyword to [link your PR to the issue](https://docs.github.com/pt/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Using keywords like close, resolves, fixes, etc. will automatically close the linked issue as soon as your PR gets merged.

**Comment by Ayush-singla27** [comment]
Ohk. Will keep that in mind next time.

**Comment by rffontenelle** [comment]
@Ayush-singla27 That linking works only in the original post, but we're past that point.

@stabbystabstab can still close, or just wait an admin spot this conversation and close it.

**Comment by Ayush-singla27** [comment]
Ohk. Will keep that in mind next time.
