### ISSUE TITLE
Missing code block in step 154 of new JS rpg project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48087]
## the issue 

In the step, the hint says the following:

> You should add the string " Your " to `text.innerText`. Remember that spacing matters.

## the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/6df93646db629a535c3ae193aee1c8e16d33feed/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa226207f33d3ad4c6f546.md#L27

<s>
### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.
</s>

**Comment by TechGeek3** [comment]
Can I contribute to this?

**Comment by Sboonny** [comment]
yes, feel free to open PR, after reading our guideline 👍

**Comment by ieahleen** [comment]
Remember that spaces do not appear in a code block at the beginning or end. Are spaces important in that step?

**Comment by rffontenelle** [comment]
@ieahleen It seems so, yes. Reading the source file, the intention is to create a "`text.innerText` + Your [weapon] breaks." string. This step adds "Your", making sure there is a space before the previous sentence and a space after "Your" before what will be the result of running `inventory.pop()` .

**Comment by Sboonny** [comment]
Welp.

We have different issue, using quotes doesn't stop people from adding/removing space https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/34723/en-ptbr?filter=basic&value=0#q=1220701 

what about using `" Your "`

**Comment by ieahleen** [comment]
Maybe `" Your "` or
> You should add the string ` Your ` to `text.innerText`, adding a space before and a space after.

Something that makes clear to add the spaces and also that describe how to add them (updating the `remember that spacing matter`)

**Comment by Sboonny** [comment]
I am leaning towards your suggestion, because I can see mine spawning multiple threads in the forum about "using quotes but not passing the test"

**Comment by ieahleen** [comment]
I think it's even more important to make sure learners notice that here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/6df93646db629a535c3ae193aee1c8e16d33feed/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa226207f33d3ad4c6f546.md?plain=1#L10
there is a space at the start of the code block.

**Comment by moT01** [comment]
Here's what I might do...

Description:
"Use the `+=` operator to add ` Your [weapon] breaks.`, with a space in front of `Your`, to the end of `text.innerText`.  Replace `[weapon]` with the last item in the `inventory` array using `inventory.pop()`, which will remove the last item in the array AND return it so it appears in your string."

Test 3:
"You should add `Your` with a space before and after it to `text.innerText`"

Test 4:
I don't think we need to do anything with line 33.

Test 5:
"You should add `breaks.`, with a space in front of it, to the end of your string.

**Comment by dojutsu-user** [comment]
Hi @Sboonny,
I would like to contribute in this issue.

**Comment by Sboonny** [comment]
Feel free to open pull request after reading our guideline.

Here is canned details I forgot to mention, sorry about that.


If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Arunima007** [comment]
> ## the issue
> In the step, the hint says the following:
> 
> > You should add the string " Your " to `text.innerText`. Remember that spacing matters.
> 
> ## the file
> https://github.com/freeCodeCamp/freeCodeCamp/blob/6df93646db629a535c3ae193aee1c8e16d33feed/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa226207f33d3ad4c6f546.md#L27
> 
> ### Additional context
> If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
> 
> Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.
> 
> Happy contributing.

Hi, Can I contribute?

**Comment by Arunima007** [comment]
Can you assign this to me?

**Comment by ieahleen** [comment]
@DeeppriyaGupta @Arunima007 
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
