### ISSUE TITLE
learn-the-css-box-model-by-building-a-rothko-painting/step-41 typo

### ISSUE THREAD

**Issue by Guillon88** [freeCodeCamp/freeCodeCamp#48080]
### Describe the Issue

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-41

Step 41
Use the border-radius property on the .two selector, to set its top-left and bottom-right radii to 8px, and top-right and bottom-left radii to 10px.

should be

Step 41
Use the border-radius property on the .two selector, to set its top-left and bottom-right radio to 8px, and top-right and bottom-left radii to 10px.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-41

### Your code

```

```

### Expected behavior

Coding challenge description typo, should be like this

Step 41
Use the border-radius property on the .two selector, to set its top-left and bottom-right **radio** to 8px, and top-right and bottom-left radii to 10px.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: 106

**Comment by jeremylt** [comment]
Radii is correct. Radii is the plural of radius.
