### ISSUE TITLE
Typo on how to open pull request document

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48085]
in the document, the instruction header says this:

> Resolve any conflicts, and cleanup, install run tests

because how the following instruction looks

 ```console
   npm run clean

   npm ci
   npm run test:curriculum --superblock=<superblock-name>

   # example:

   # npm run test:curriculum --superblock=python-for-everybody

 ```
 
I agree with the camper suggestion, in the original issue
 
 > Resolve any conflicts, cleanup, install dependencies and run tests
 
Can we clear the empty line in the code block, it's annoying me 🤣 
 
 here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/6df93646db629a535c3ae193aee1c8e16d33feed/docs/how-to-open-a-pull-request.md#L191

here is the original issue

https://freecodecamp.crowdin.com/translate/457d487b1586f10d2fba3c4ccb9c5453/5358/en-ptbr?filter=basic&value=0#q=1222499

**Comment by getcoder-top** [comment]
hiii, Please accept the pull request

**Comment by OyinOlamide** [comment]
Hello @Sboonny Please is this still open? And how can I work on it?
