### ISSUE TITLE
Vim/Emacs/Sublime Text keybindings in Bonfires

### ISSUE THREAD

**Issue by LumenTeun** [FreeCodeCamp/freecodecamp#481]
I was digging around the code base when I found out that you use CodeMirror as the editor for Bonfires. CodeMirror supports [Vim](http://codemirror.net/demo/vim.html), [Emacs](http://codemirror.net/demo/emacs.html) and [Sublime Text](http://codemirror.net/demo/sublime.html) [keymaps](http://codemirror.net/doc/manual.html#keymaps), and since quite a big part of the user base (at least the one active in the Slack room) uses one or more of these editors, implementing them would most likely be very appreciated. I'd do it myself, but turns out the building blocks of FCC confuses the living hell out of me, so I'll come back when I'm done with all the challenges.

**Comment by QuincyLarson** [comment]
Thanks for the suggestion, @lumenteun. We probably won't implement these any time soon. We're trying to encourage people to use common tools and default settings (it makes it a lot easier to pair). I think learning Vim and Emacs are a huge distraction from actually coding, and aren't nearly as powerful as IDEs like WebStorm. My rationals are best explained here: http://blog.freecodecamp.com/2014/11/a-cautionary-tale-of-learning-to-code.html

**Comment by LumenTeun** [comment]
I completely understand your point of view. However, seeing as how many of the campers already use one of these tools, making them available in some way, no matter how obscure, would benefit many without necessarily making the camping experience harder for newcomers. For exampe, I saw something about the Konami Code on the Waffle Board. I know that won't be implemented in a while either, but if it is, it could maybe activate the choice of editor or some "super secret advanced expert"-settings on your profile or something similar.
It seems like a waste to completely ignore a feature that is not only available, but wanted.
Fully understand that this is not your main concern right now though :) Keep up the great work!
