### ISSUE TITLE
RTL layout for freeCodeCamp curriculum

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48101]
### Is your feature request related to a problem? Please describe.

With 100% of the three Arabic front end libraries proofread in Crowdin, we need to change the pages Layout to account for this.

The layout that need to be changed are as follows:

<details><summary>The Header and Footer layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196185925-7fc2de6a-86fc-4e12-b3f4-08a59530edba.png)

</details> 

<details><summary>The home layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196185797-e1af967f-9699-4b1e-8947-90d0ec738e71.png)

</details> 

<details><summary>the timeline layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196187158-b41c95b0-b690-469e-9114-528bcd67cab5.png)

</details> 

<details><summary>the setting layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196187505-ca2bd068-5256-4d93-9e9e-d8b3601a01a1.png)

</details> 

<details><summary>The donate layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196188352-9fb7ea88-e279-46b2-84c8-45d43bcffe9a.png)

</details> 

<details><summary>The new test project layout? I think this is similar to the new RWD layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196188634-31638903-b846-492e-bb06-151cc27b2eb7.png)

</details> 

<details><summary>The learn layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196186444-d5536c22-fae7-4550-a655-d1f68116ce3f.png)

</details> 

<details><summary>the certification introduction layout</summary>

![image](https://user-images.githubusercontent.com/88248797/196185649-26a09c14-1160-4eee-b386-fd442ce57390.png)

</details> 

<details><summary>the new RWD layout</summary>

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-1

![image](https://user-images.githubusercontent.com/88248797/196186856-6990ff10-273d-4908-b4bc-1e7ba062c873.png)

</details> 

<details><summary>The old JavaScript certification</summary>

![image](https://user-images.githubusercontent.com/88248797/196185339-37c707fb-7a80-43e9-be61-c2df3c0fae93.png)

</details> 

<details><summary>The front end library project certification</summary>

![image](https://user-images.githubusercontent.com/88248797/196189519-93209840-e6dd-47a4-9715-63c1894a07e4.png)

</details> 

### Describe the solution you'd like

Change the component and layout to account for RTL Language

### Describe alternatives you've considered

I thought this was possible :rofl:

```css
flex-direction: row-reverse;
direction: rtl;
```

### Additional context

Is there a way to change SubForm layout in the forum?

### Issues

- [x] #48174
- [x] #48347
- [ ] #48348

**Comment by Sboonny** [comment]
I have created a branch with files in it, to act as sandbox for the changes here it's https://github.com/Sboonny/freeCodeCamp/tree/Arabic-curriculum-subtree

**Comment by ahmadabdolsaheb** [comment]
Thanks @Sboonny for creating this issue, importing the translations and  submitting fixes.
I came across this guide for RTL styling that thought might be helpful: (https://rtlstyling.com/posts/rtl-styling/)

Initially we would need to have a branch that only has the added translation files. The UI and lesson translations should be working so we would know if we need to change the size of some elements to accommodate the Arabic language. 

Next, a direction attribute should be added to the HTML element (or body) based on the clinetLocale.
Client/src/html.tsx might be a good place.

Then, we can dedicate a CSS file for all RTL styling.

Could you update me about the timeline? I would rather get the component library in if we have a week and then add the RTL styles to avoid conflicts.

**Comment by Sboonny** [comment]
thanks to Naomi, we can link Arabic string consistently. we need to run `npm run clean-and-develop`, and it will throw the old english string and use the arabic string, I think 🤔 


![image](https://user-images.githubusercontent.com/88248797/197262734-8bc1605b-3242-4f01-b03e-fc2a50c502e2.png)

**Comment by Sboonny** [comment]
Javascript final projects editors aren't interactive in RTL layout

![image](https://user-images.githubusercontent.com/88248797/197350794-7319d480-d174-47f9-980b-8dc3549956f6.png)

**Comment by ahmadabdolsaheb** [comment]
> I am confused, do I create a branch in freeCodeCamp, with Arabic strings only? What should I account for while creating it, as how is different from the current imported strings from Crowdin?

Any branch anywhere would do.

> Do I update `HTML` attribute, then delete `.rtl-layout` class? Using the class with the attribute around feels redundant to me.
> 

Adding the direction attribute seems to be best practice. 

> anyway, I am adding it. Random question, should I change the logic for `lang=en` to account for different language, as well? like if it's Arabic, then the `lang` will be `ar`.

Yes

> Testing the `dtr=rtl` breaks the UI in weirds ways, as in the picture below

That is expected. The direction of the spacing should be changed for some of the element for RTL, or we could rewrite the old styles using CSS Logical Properties.


Here are the actionable items for our recent meeting:
- Some Ui translations need adjustment
- The navigation needs to be mirrored
- The best practices for building rtf compatible components
  - Storybook documentation 
  - Samples in current storybook design systems
- Adjust word-break to account for sentences with two languages
- Research popular Arabic fonts that are readable in bold and regular

**Comment by Sboonny** [comment]
I was confused, we have `lang='en'` in the `html` element, here it's https://github.com/freeCodeCamp/freeCodeCamp/blob/bdc2f43c0059657bb49832b66b8abff02689c836/client/src/html.tsx#L21-L41?plain=1

but the test the check for `lang` value doesn't fail in this, https://github.com/freeCodeCamp/freeCodeCamp/blob/bdc2f43c0059657bb49832b66b8abff02689c836/client/src/components/app-mount-notifier.test.tsx#L37-L50?plain=1

Where is the `HTML` imported (my guess is the middle), which allows this sorcery.

---

So this is not needed 

> > anyway, I am adding it. Random question, should I change the logic for lang=en to account for different language, as well? like if it's Arabic, then the lang will be ar.

> Yes

**Comment by Sboonny** [comment]
This is complicated.
- [IBM Plex Sans Arabic](https://fonts.google.com/specimen/IBM+Plex+Sans+Arabic?subset=arabic) does look nice, but the way it's typing `في` is making me worried about other RTL language. (it can be used for LearnUI)
- [Noto Naskh Arabic](https://fonts.google.com/noto/specimen/Noto+Naskh+Arabic?subset=arabic) is accessible, and look fine. Which is nice if we are going to use it for editor text. (it can be used for both)
- [Lateef](https://fonts.google.com/specimen/Lateef?subset=arabic) this one reminded me of my old books about general education stuff, I guess something similar is used for books. Although I like it the most, I find it hard to read. But to be fair, I find reading hard in general :rofl: (It can be used for both)
- [Noto Sans Arabic](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?subset=arabic) this is one seem fine on most angles, so it's good master of all trades? 🤔 to be honest I don't know, I am not designer.

**Comment by bbsmooth** [comment]
FYI, I came across this great guide on supporting rtl styling.

[RTL Styling 101](https://rtlstyling.com/posts/rtl-styling)

**Comment by Sboonny** [comment]
I have tried to create quick demo, but the font isn't different 😞 https://codepen.io/Sboony/pen/ZERYwqd

![image](https://user-images.githubusercontent.com/88248797/198335241-d53bd32f-14c2-41dc-85db-bf0ad1e65edc.png)

**Comment by ojeytonwilliams** [comment]
@Sboonny currently we're serving pages with `lang=en` and then dynamically updating that to `lang=whatever-it-actually-is`.  As I understand it I18nextProvider does this for us, but I haven't dug into it.

This isn't ideal (we should generate html with the correct code), but I suspect it's fine for now.

**Comment by Sboonny** [comment]
@ojeytonwilliams, true. I had a small discussion with raisedadead in here about this https://github.com/freeCodeCamp/freeCodeCamp/pull/48245#discussion_r1006968532

**Comment by ahmadabdolsaheb** [comment]
@Sboonny, the [Noto Sans Arabic](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?subset=arabic) does not seem to be working properly on the codepen.

If [IBM Plex Sans Arabic](https://fonts.google.com/specimen/IBM+Plex+Sans+Arabic?subset=arabic) is over extending letters, and [Lateef](https://fonts.google.com/specimen/Lateef?subset=arabic) is hard to read in Urdu, we choose the Noto ones. 

Both of those look good, but I prefer the Noto Sans over Noto Naskh.
