### ISSUE TITLE
Sentence that needs improvement in the new JS rpg project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48118]
@Dario-DC, reported sentence that looks weird, and I agree. it is used in 4 files

here is the sentence

> property with the value an array

https://github.com/freeCodeCamp/freeCodeCamp/blob/2f841a56dbe06a8f374d6eff6669664f000993c5/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8eff21c0b0f6ebe5b8e38.md#L32-L38

https://github.com/freeCodeCamp/freeCodeCamp/blob/2f841a56dbe06a8f374d6eff6669664f000993c5/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a94114ce0b8918b487390f.md#L32-L38

https://github.com/freeCodeCamp/freeCodeCamp/blob/2f841a56dbe06a8f374d6eff6669664f000993c5/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62ba17beef16c563069a65d8.md#L32-L38

---

I noticed in the last file, we are using deepEquel, should we mention that array's variables' respective position matter?

https://github.com/freeCodeCamp/freeCodeCamp/blob/2f841a56dbe06a8f374d6eff6669664f000993c5/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa25fcb5837d43b4d9873d.md#L32-L38

**Comment by rohanprichard** [comment]
Can I be assigned to this?

**Comment by Sboonny** [comment]
contribution isn't open for issues with label https://github.com/freeCodeCamp/freeCodeCamp/labels/status%3A%20discussing, you are more than welcome to discuss how to improve it

**Comment by moT01** [comment]
I would shorten them to just use `array`...

e.g. "Your fifth `locations` value should have a `button text` array with three `Go to town square` strings."

**Comment by Sboonny** [comment]
there is no one has provided a better option yet, so I am opening this for contribution, and when the JS is published, we can come back to this when campers are taking the course.

You should follow Tom comment here https://github.com/freeCodeCamp/freeCodeCamp/issues/48118#issuecomment-1285793087

----


If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by 1901124414ask** [comment]
Hello Sir, can you assign me this issue? hacktoberfest#1

**Comment by Sboonny** [comment]
> I for one think we don't need to over explain this, as the values are described in order most people will put them in that exact order.

Although, we are trying to include everyone, you are right this is me trying to overengineer something simple.

> "Your fifth locations value should have a button text with the value being an array consisting of three Go to town square strings."

It's good, but we should keep Tom suggestion. In HTML/CSS projects steps, we are using the same that Tom mentioned, so there will be comfort, and subtle hints that `array` is an object that carry variables.

**Comment by Sboonny** [comment]
@1901124414ask you can open a PR, after reading our guideline. more info in this comment https://github.com/freeCodeCamp/freeCodeCamp/issues/48118#issuecomment-1291550666

**Comment by haweecodes** [comment]
> > I for one think we don't need to over explain this, as the values are described in order most people will put them in that exact order.
> 
> Although, we are trying to include everyone, you are right this is me trying to overtune something simple.
> 
> > "Your fifth locations value should have a button text with the value being an array consisting of three Go to town square strings."
> 
> It's good, but we should keep Tom suggestion. In HTML/CSS projects steps, we are using the same sentence structure that Tom mentioned, so there will be comfort, and subtle hints that `array` is an object that carry variables.


Your fifth locations value should have a `button text` property and an array value with three `Go to town square` strings.

@Sboonny kept most of the original wordings.

**Comment by michpara** [comment]
Opened a PR for this issue!
