### ISSUE TITLE
Typo in new JavaScript make an RPG game

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48119]
### Describe the Issue

There is a typo in Step 156, the word `or` is used to refer to the `AND` operator.

Here is the typo

https://github.com/freeCodeCamp/freeCodeCamp/blob/2f841a56dbe06a8f374d6eff6669664f000993c5/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa234322d4ad3e8bce42cc.md#L10

it should be `AND`

Can you change the lowercase `and` that refers to the operator in the file, to uppercase **`AND`**, as well? to follow the docs of Mozilla https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND

### Additional context

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution, followed by the one that is made first.

Happy contributing.

**Comment by LeGrandMAG** [comment]
Hello, I would like to work on this issue.

**Comment by aadityarajkashyap** [comment]
hello,can i resolve the issue?
