### ISSUE TITLE
Waypoint: Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by jcloutz** [FreeCodeCamp/FreeCodeCamp#4811]
Challenge [Waypoint: Nest an Anchor Element within a Paragraph](http://www.freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%0A%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%3Cp%3EView%20more%20%3Ca%20href%3D%22http%3A%2F%2Fwww.freecatphotoapp%22%3Ecat%20photos%3C%2Fa%3E%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This came up in gitter today. There is a problem with the first error check if the url is entered incorrectly.

Using this code
```
<p>View more <a href="http.freecatphotoapp">cat photos</a></p>
```

The error displays as 
```
You need an a element that links to "http
```

 instead of 
```
You need an a element that links to "http://www.freecatphotoapp.com".
```

**Comment by bugron** [comment]
@jcloutz thanks for pointing this out, confirmed!
Interesting, I am able to reproduce this in FF 42 but not in Chrome 43.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ltegman** [comment]
I can repro this in both Chrome 46 and Firefox 42 using the prod website or the master branch, but I can't repro in staging or beta, so this is fixed and will be deployed as soon as the beta period for the latest code is over.

Thanks and happy coding!
