### ISSUE TITLE
Test case bug in 'Using typeof' waypoint

### ISSUE THREAD

**Issue by diegoingaramo** [FreeCodeCamp/FreeCodeCamp#4813]
Section: Automated Testing and Debugging
Waypoint: Using typeof

If I type the following code:

```
console.log(typeof "");
console.log(typeof 0);
console.log(typeof []);
console.log(typeof {});
```

The test won't pass. What it seems odd to me is that If I type the values between brackets the tests are fulfilled:

```
console.log(typeof(""));
console.log(typeof(0));
console.log(typeof([]));
console.log(typeof({}));
```
I think both cases are correct.

link: http://www.freecodecamp.com/challenges/waypoint-using-typeof

Best regards

**Comment by ltegman** [comment]
Good catch. Despite showing our preferred syntax (no parens) in the sidebar the regex is expecting parens. These tests should be made to allow either.
