### ISSUE TITLE
Typo on how to open pull request document

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48133]
in the document, there is a sentence saying this:

> Search for the user that will become contributor.

But this section is talking about assigning proofreading, it should be changed to this:

> Search for the user that will become proofreader.
 
 here is the file

[Search for the user that will become contributor.](https://github.com/freeCodeCamp/freeCodeCamp/blob/3653ff4e18e1ab4a967a89bf3c0a1eff2bdba813/docs/language-lead-handbook.md#L311)

here is the original issue

https://freecodecamp.crowdin.com/translate/457d487b1586f10d2fba3c4ccb9c5453/34389/en-it?filter=basic&value=0#q=1222173

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Aman-zishan** [comment]
I can take this up
