### ISSUE TITLE
Bookmarked Certifications were no longer usable

### ISSUE THREAD

**Issue by Tracerract** [freeCodeCamp/freeCodeCamp#48145]
### Describe the Issue

I'm working on my Front End Cert. I had a bookmark for my first two certs, and had also added them to my LinkedIn, like the button suggests doing. I was trying to check something and clicked my bookmark only to find out that it wasn't working anymore. I got lucky.

I've somewhat looked through #42621 and #45562 so I realize that this is a solution to a problem I didn't even know existed. I like my privacy, so at the time I only unchecked the few that said they were required for certifications.

The main thing is that people could be sharing their certs like that, without knowing that the link is broken because of this change. Or maybe I was the only one.

Additionally, while the timeline is private, you can still look at a profile and see links to their certifications, but when clicked they redirect to fcc home. I believe the redirect is intended, but I'm not sure that still seeing the certifications is.

I don't know if this is even something that would get fixed, but I wanted to make sure it was at least brought up in case there are others that ended up similar to me and haven't noticed the change.

### Affected Page

https://www.freecodecamp.org/certification/Tracerract/responsive-web-design

### Steps to Reproduce

1. Follow profile instructions before #45562 was merged
2. Get certification before #45562 was merged
3. Bookmark cert and post on any social media
4. Look silly when anyone tries to look at your cert after #45562 was merged

### Expected behavior

na

### System

na

Edit: typo

**Comment by ieahleen** [comment]
> Additionally, while the timeline is private, you can still look at a profile and see links to their certifications, but when clicked they redirect to fcc home. I believe the redirect is intended, but I'm not sure that still seeing the certifications is.

For other privacy options, like certifications private, the certs are hidden in the profile. Maybe it can be extended 🤔

**Comment by moT01** [comment]
Yea, this is a little goofy. We say that your certs will be private if timeline is private - but we still show the earned certs on the profile. That's not the cert itself, but it kind of makes you think those might be hidden if timeline is private.

For some context, the certs get hidden when timeline is private because we want to show the projects completed to earn a cert, on the cert. Hiding a timeline, hides those projects.

Do you have any suggestions that might help here @Tracerract?

I can think of a couple.

Timeline means timeline, not necessarily the projects. We could stop hiding certs when timeline is private, and include the completed projects on the cert. I kind of like this idea, if someone sets their certs to public, they shouldn't mind showing their projects there.

We could rearrange the settings page so that timeline and certifications are right next to each other, making this harder to occur.

**Comment by Tracerract** [comment]
> Timeline means timeline, not necessarily the projects. We could stop hiding certs when timeline is private, and include the completed projects on the cert.

This is what I thought to be happening before, and I didn't realize that wasn't the case. I do think that removing the certification's dependancy on the timeline would allow this to resolve in a way that works for users that had their settings like I did and haven't noticed their broken cert links yet.

Also, I think that this solution is one method of solving that additional unintended behavior I mentioned about the cert links on the profile regardless of the timeline setting.

> if someone sets their certs to public, they shouldn't mind showing their projects there.

I agree with this completely, part of the reason I liked these certs was because people could check my work if they wanted.

I do see benefit in having projects not shown for printing out a cert though, so that might be something to keep in mind there.

**Comment by naomi-lgbt** [comment]
I think this is related to https://github.com/freeCodeCamp/freeCodeCamp/issues/45563, in that we want to stop redirecting "hidden" carts to the homepage and instead redirect to a FAQ page which will help clarify why a certification might be unavailable.

**Comment by Tracerract** [comment]
I agree that it is related in that it's about certs not being shown, but I think that the solutions will likely be different. 

As in: removing the timeline dependency for certs wouldn't resolve other things causing it to redirect to the home page, and changing the redirect page won't resolve previously shared functional links to certs being broken from the fix a few weeks ago.

**Comment by ieahleen** [comment]
The redirect to homepage is the desired behaviour if the certification is not available for whatever issue, it has a message on top saying that the certification is not available
![image](https://user-images.githubusercontent.com/26656284/197333904-3cea3293-602f-4da9-8023-e55676bcc28e.png)

**Comment by Tracerract** [comment]
That wasn't the issue I was bringing up here though. I was bringing up that my publicly shared cert links were broken and I wasn't informed in any manner, and had no way to find out other than getting lucky and clicking on my bookmark to view my cert.

The issue I'm trying to bring attention to is that there was a breaking change made, and there are likely other people out there who had their settings the way that I did and don't know that they have broken links that they are sharing.

Yes a better explanation on a redirect will help them once they find the issue, but it won't actually solve the issue about their links being broken and them not knowing and still sharing it publicly.

The solutions for this as I see it, are either to update users via email or etc that there was a possible breaking change in their settings for viewing certs and that all users sharing their certs publicly will need to re-examine their settings to make sure their timeline is now also set to public, or like we had been discussing before in this topic, the certifications dependency on the timeline could be removed which would allow the same settings as before to work without issue.

**Comment by ieahleen** [comment]
And removing the dependency from the timeline would fix that, as it means that even if the timeline is private, if you set the certificates to public then they are visible and not disabled.

The fact that a disabled certificate redirects to the homepage is intended

**Comment by Tracerract** [comment]
> And removing the dependency from the timeline would fix that, as it means that even if the timeline is private, if you set the certificates to public then they are visible and not disabled.

Yes, this is where I'm not sure how to help more though, cause I'm not sure of any specifics about the implementation that causes that dependency. Do you have any ideas on that front?




> The fact that a disabled certificate redirects to the homepage is intended, at least for now

Woops, I'm sorry, I'd forgotten about the secondary effect that I'd found (where I wasn't 100% about intended behavior) and thought we had ended up off-topic. My bad.

**Comment by raisedadead** [comment]
I think what we should do is once a user has claimed a certification and then for some reason change their privacy settings, we should redirect the certification link to something like `https://www.freecodecamp.org/certification/private` and then render a helpful message along the lines of what we have in the flash message.

The logic should account for any certifications that have not been claimed.

Here is an example:

Say the user claimed these below certs:

https://www.freecodecamp.org/certification/USERNAME/responsive-web-design
https://www.freecodecamp.org/certification/USERNAME/javascript-algorithms-and-data-structures

and then they make their certification settings private,

all the below certs should redirect to `https://www.freecodecamp.org/certification/private`

https://www.freecodecamp.org/certification/USERNAME/responsive-web-design
https://www.freecodecamp.org/certification/USERNAME/javascript-algorithms-and-data-structures
https://www.freecodecamp.org/certification/USERNAME/relational-database
https://www.freecodecamp.org/certification/USERNAME/...
...

and so on.

**Comment by naomi-lgbt** [comment]
We had previously discussed this in #45563

**Comment by raisedadead** [comment]
Ah, right, we should just go ahead and implement the discussion in that thread.

**Comment by ojeytonwilliams** [comment]
I don't think we need two issues tracking this. Let's just keep https://github.com/freeCodeCamp/freeCodeCamp/issues/45563 open.
