### ISSUE TITLE
Relational Databases: Number guessing game:

### ISSUE THREAD

**Issue by vkats90** [freeCodeCamp/freeCodeCamp#48164]
### Describe the Issue

In the tests for the number guessing game, the tests count printed empty spaces as guesses, and so If you code the game to print empty spaces for readability purposes, you will not subtests 8 and 13.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/build-a-number-guessing-game-project/build-a-number-guessing-game

### Your code

```
#!/bin/bash

PSQL="psql -X --username=freecodecamp --dbname=users --no-align --tuples-only -c"

NUMBER=$(( $RANDOM % 1000 + 1 ))

echo -e "\nEnter your username:"
read USERNAME

USERID=$($PSQL "SELECT user_id FROM users WHERE username='$USERNAME'")

if [[ ! -z $USERID ]] 
then
  GAMES_PLAYED=$($PSQL "SELECT games_played FROM users WHERE username='$USERNAME'")
  BEST_GAME=$($PSQL "SELECT best_game FROM users WHERE username='$USERNAME'")
  echo "Welcome back, $USERNAME! You have played $GAMES_PLAYED games, and your best game took $BEST_GAME guesses."
else
  echo "Welcome, $USERNAME! It looks like this is your first time here."
  $PSQL "INSERT INTO users(username) VALUES('$USERNAME')" | echo 
  GAMES_PLAYED=0
  BEST_GAME=0
fi
echo -e "\nGuess the secret number between 1 and 1000:"

GUESSES() {
  read GUESS
  COUNTER=$(( $1 + 1 ))

  if ! [[ $GUESS =~ ^[0-9]+$ ]]
  then
    echo -e "That is not an integer, guess again:\n"
    GUESSES $COUNTER
  fi

  if [[ $GUESS = $NUMBER ]]
  then 
    echo -e "\nYou guessed it in $COUNTER tries. The secret number was $GUESS. Nice job!"
    $PSQL "UPDATE users SET games_played='$(( $GAMES_PLAYED + 1 ))' WHERE username='$USERNAME'" | echo
    if [[ $COUNTER < $BEST_GAME || $BEST_GAME = 0 ]]
    then
      $PSQL "UPDATE users SET best_game='$COUNTER' WHERE username='$USERNAME'" | echo
    fi
  elif [[ $GUESS > $NUMBER ]]
  then
    echo -e "It's lower than that, guess again:\n"
    GUESSES $COUNTER
  elif [[ $GUESS < $NUMBER ]]
  then
    echo -e "It's higher than that, guess again:\n"
    GUESSES $COUNTER
  fi
}

GUESSES
```

### Expected behavior

1 of 2 solutions proposed for this: 
1. Add a note in the challenge description saying that you cannot print extra spaces
2. Make it so the tests only count the actual prints an not empty spaces printed by the code

### System

- Device: Macbook Mini
- OS: MacOS Monterey
- Browser: Chrome
- Version: 106.0.5249.119

**Comment by gikf** [comment]
More context:
https://forum.freecodecamp.org/t/number-guessing-game-tests-8-and-13-wont-pass/564738
https://github.com/freeCodeCamp/learn-number-guessing-game/blob/3ab32fa2baf1e5abbe0df24693f8e3b3a709d4f3/.freeCodeCamp/test/1.1.test.js#L7-L32

As mentioned, the test is making another guess after each line printed out by script. Because of the way the number of guesses and the secret number is counted, this can create discrepancy with the actual numbers.

I think second proposed option would be more desired and wouldn't add much complexity.

cc @moT01

**Comment by moT01** [comment]
Hey, what do you think of [my solution](https://github.com/freeCodeCamp/learn-number-guessing-game/blob/v1.0.4/.freeCodeCamp/test/1.1.test.js#L12) @gikf @vkats90?

I added a check for empty lines, tested on my script and yours - both passed. Wondering if I'm missing anything though.
