### ISSUE TITLE
Lack of a descriptive enough hint in step 22 of building skyline project 

### ISSUE THREAD

**Issue by Vishal101022** [freeCodeCamp/freeCodeCamp#48165]
### Describe the Issue

In the hint below it ask to create a new variable, but it doesn't say where we have to add. A camper like me add variable in **.bb2** which is normal we did same in **.bb1**, which cased confusion to a camper.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-variables-by-building-a-city-skyline/step-22

### Your code

```
.bb2 {
  width: 10%;
  height: 50%;
  --building-color2: #66cc99;
}
```

### Expected behavior

Hint should clearly say where we have to add variable instead of **Hint
You should give --building-color2 a value of #66cc99.**

### Screenshots

![Screenshot 2022-10-21 093345](https://user-images.githubusercontent.com/13450751/197109111-25f57eaa-7cb1-4a83-afd6-1c7c9276f159.jpg)

### System

- Device: [Desktop]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: [106.0.5249.119 ]

**Comment by footedroom575** [comment]
The step instructs where to add the other variable imo. 

> Create a new variable below the other one 
There is only 1 variable in the code `--building-color1` and it should be inferred that the other one goes right below it.

However, I still agree that the hint should be more meaningful in case someone misunderstood it. 

Will add a new pr soon

**Comment by naomi-lgbt** [comment]
We should change:

> Create a new variable below the other one called --building-color2 and give it a value of #66cc99

To:

> Create a new variable below your `--building-color1` variable. Name your new variable `--building-color2` and give it a value of `#66cc99`.
