### ISSUE TITLE
Arabic LearnUI strings aren't used by the Arabic curriculum in testing

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48174]
When testing Arabic LearnUI, after the Arabic strings have been imported in the curriculum.

The Arabic strings are ignored, and English strings are used instead, as shown in the issue below.

![image](https://user-images.githubusercontent.com/88248797/197236584-72b82e16-f9f8-423e-8e66-ccaba5fee5ca.png)

----

The unique Arabic string is me testing how they look from the devtools, sorry for the confusion. here is a live PR with strings attached https://github.com/freeCodeCamp/freeCodeCamp/pull/48148

**Comment by Sboonny** [comment]
somewhere in this file, there is a logic that make it failback to english ui, I have no idea what it's


https://github.com/freeCodeCamp/freeCodeCamp/blob/33a95e4e102b1b080de60d55036914bd11b7450c/client/i18n/config.js#L1-L82

**Comment by naomi-lgbt** [comment]
Any time the `.env` values are changed, especially with the locale values, `npm run clean` should be run to remove any cached files that are now stale.

As a shortcut, `npm run clean-and-develop` will run `clean` and then start the dev server again.

Going to close this for now, but if you run in to additional issues feel free to ping in chat or on this thread.
