### ISSUE TITLE
Editor contents resets whenever tests are run

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#48173]
Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46061

Any time the tests are run the preview iframe is recreated from scratch.  This is unnecessary, since the tests run in a separate frame.

https://github.com/freeCodeCamp/freeCodeCamp/pull/47870 fixes the most visible consequence of this - the preview scrolling back to the top.  However, this is still an unnecessary operation.

### Where the problem lies

https://github.com/freeCodeCamp/freeCodeCamp/blob/eb489c2d3c2afeb1fc0f806a554aca0198a7e656/client/src/templates/Challenges/redux/execute-challenge-saga.js#L81-L83 is the offending function call, so this should be removed and the saga simplified.

**Comment by dojutsu-user** [comment]
Hi @ojeytonwilliams @Sboonny,

Taking this up. Possible to assign the issue to me?

**Comment by Sboonny** [comment]
We don't give assignments, after you have read our guideline, feel free to open PR. 


If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by BodhisattaKumar** [comment]
hi i would like to work in this issue please assign

**Comment by jdwilkin4** [comment]
Hi @BodhisattaKumar ! 

Please read through @Sboonny 's earlier reply 👍
