### ISSUE TITLE
Broken test in boilerplate-budget-app replit

### ISSUE THREAD

**Issue by victoremeka** [freeCodeCamp/freeCodeCamp#48195]
### Describe the Issue

When calculating percentage **spent**, the results are calculated based on deposits and not withdrawals as stated in the challenge description.

### Affected Page

https://replit.com/github/freeCodeCamp/boilerplate-budget-app

### Your code
```
def create_spend_chart(data:list):
  chart = []
  creds = []
  y_side = [f'{i}|' for i in range(100, -10, -10)] # Create the vertical labels
  fnl = 'Percentage spent by category\n' # Final chart result

  # Add horizontal lines
  lines = ['---' for i in range(len(data))] 
  lines.append('-') # Add final line


  for i in range(11): 
    # Format vertical labels
    for a in range(4 -len(y_side[i])):  y_side[i] = ' ' + y_side[i]

  chart.append(y_side)


  elm = 'o' # Lil add to fix formatting
  elm_x = ' ' # Same here
  for cat in data:
    total_spends = sum(cat.spends)
    total_saves = sum(cat.savings)
    percentage_spent = int(round((total_spends/total_saves)*100, -1)) # Round to the nearest 10
    bars = [elm for i in range(percentage_spent//10 + 1)] # Create a cannonical representation of a bar 

    for i in range(11 - len(bars)): bars.insert(0, elm_x) # Format bars

    # Add trailing end credits
    cat_name = [i for i in cat.name]
    creds.append(cat_name)


    chart.append(bars) # Append bar to main chart

    elm = ' o' # Here's the fix
    elm_x = '  ' # This too
  
  # Find the max credit's index
  largest = [len(i) for i in creds]
  largest = largest.index(max(largest)) 

  # Format end credits's length
  for x in creds:
    for i in range(len(creds[largest]) - len(x)):
      x.append(' ')
  # Format end credit's width
  cn = 0
  for y in creds[0]:
    y = '   ' + y
    creds[0][cn] = y
    cn += 1
  
  for i in range(11): # Make main chart
    for verts in chart:
      fnl += verts[i] + ' '
    fnl += '\n'

  fnl += '    ' + ''.join(lines) + '\n' # Make horizontal lines
  

  for i in range(len(creds[largest])):
    for dat in creds:
      fnl += '  ' + dat[i]
    fnl += '\n'

  # print(fnl)
  # print(repr(fnl))
  return fnl.rstrip() + '  '


```

### Expected behavior

Expects **test_create_spend_chart** to assert proper results

### Screenshots

![test_module py - boilerplate-budget-app - Replit - Google Chrome 10_22_2022 8_17_54 AM](https://user-images.githubusercontent.com/98593069/197327295-4696efd0-8a4e-4c6c-9832-9fee58a2d4aa.png)
![test_module py - boilerplate-budget-app - Replit - Google Chrome 10_22_2022 8_18_14 AM](https://user-images.githubusercontent.com/98593069/197327315-65fcda72-63b5-4c67-8d86-2e60f11da3a2.png)
![test_module py - boilerplate-budget-app - Replit - Google Chrome 10_22_2022 8_18_51 AM](https://user-images.githubusercontent.com/98593069/197327318-b21f0201-db71-4a2f-82b1-2cbd8aa39168.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 106.0.5249.119 (Official Build) (64-bit) (cohort: Stable)

**Comment by gikf** [comment]
Thank you for reporting this issue.

The each bar should show amount spend in single category to the total amount spend in all categories.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
