### ISSUE TITLE
My code returns the correct answer but does not give credit

### ISSUE THREAD

**Issue by anthonyjrizzo** [FreeCodeCamp/FreeCodeCamp#4819]
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays?solution=var%20finalArray%20%3D%20%5B%5D%3B%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20for%20(var%20i%3D0%3Bi%20%3C%204%3B%20i%2B%2B)%20%7B%0A%20%20%20%20finalArray.push(Math.max.apply(Math%2C%20arr%5Bi%5D))%3B%0A%20%20%7D%0A%20%20return%20finalArray%3B%0A%7D%0A%0AlargestOfFour(%5B%5B13%2C%2027%2C%2018%2C%2026%5D%2C%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var finalArray = [];
function largestOfFour(arr) {
  for (var i=0;i < 4; i++) {
    finalArray.push(Math.max.apply(Math, arr[i]));
  }
  return finalArray;
}

largestOfFour([[13, 27, 18, 26],[4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by ltegman** [comment]
You are initializing `finalArray` globally, so after the first time your function runs the array is not empty and the result returned will be incorrect. Variables should be initialized within the context of the scope they are used (in this case the `largestOfFour` function).

In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) before filing a bug.

Thanks and happy coding!
