### ISSUE TITLE
Bonfires code editor should auto-save a user's work

### ISSUE THREAD

**Issue by nickbarry** [FreeCodeCamp/FreeCodeCamp#482]
It would be great if the code editor for the Bonfires auto-saved a user's work. This would prevent losing code if you accidentally close your tab, or your browser crashes. It would also make it easy to go back and review what code you used, after having completed a bonfire.

**Comment by Lemony-Andrew** [comment]
Looks like I was right there with you! I just added the feature and hopefully it passes.

**Comment by QuincyLarson** [comment]
@nickbarry this works now!

**Comment by nickbarry** [comment]
Cool!
