### ISSUE TITLE
Hello from PyScript

### ISSUE THREAD

**Issue by marimeireles** [freeCodeCamp/freeCodeCamp#48217]
### Describe the Issue

Hi!
I didn't know how to reach out to you folks, I saw you released a new track using PyScript.
I'm a core dev and I used freecodecamp to start getting into code so I have a deep love for the project and respect and appreciation for you work!
If you ever encounter some weird behavior or just would like some nice specific feature that would fit you well, please bring it up! I'll be more than happy to help.

### Affected Page

Just wanted to build this bridge!

### Your code

```
```

### Expected behavior

Thanks and sorry for opening the issue in the obviously wrong location.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by marimeireles** [comment]
You can reach me: mariana@psychonautgirl.space
or my twitter :)
or through opening an issue on github
or through pyscript's discord community
cheers!

**Comment by Vishal101022** [comment]
@marimeireles this is not an issue please don't do this , its against contributing guidelines so i request to @raisedadead to close this issue.
