### ISSUE TITLE
"target:nth-child()" Selector only working with space after "target"

### ISSUE THREAD

**Issue by danieloliveira56** [FreeCodeCamp/FreeCodeCamp#4822]
Code
$("#right-well:nth-child(2)").addClass("animated bounce");
$("#left-well:nth-child(2)").addClass("animated bounce");
made the two wells bounce, while code
$("#right-well :nth-child(2)").addClass("animated bounce");
$("#left-well :nth-child(2)").addClass("animated bounce");
by inserting a space after well solved the challenge correctly.

**Comment by ltegman** [comment]
Please provide a link to the challenge you are working on.

**Comment by danieloliveira56** [comment]
http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery

**Comment by bugron** [comment]
@danieloliveira56 thanks for posting this issue!
I think this [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927#issuecomment-132369084) is the answer.
Closing this issue. Feel free to reopen if you still experience problems, thanks.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

**Comment by msjohncox** [comment]
Thank you for solving this! Why does putting a space after the target element solve it? Also, I was able to solve it with a single statement:  $(".well :nth-child(2)").addClass("animated bounce");
