### ISSUE TITLE
Typo in the "Regular Expressions: Matching and Extracting Data" Challenge

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#48229]
### Describe the Issue

This typo was recently sent into the support inbox.

In the Python for Everybody challenge, "Regular Expressions: Matching and Extracting Data", the example code includes a regex string with a typo: `lst = re.findall('\\S+@\\S+', s)`

However, the regex string should be `lst = re.findall('\S+@\S+', s)`, with single backslashes (`\`) before `S+`.

Here's a screenshot from the video clip showing the `\S` character class in Python:

![image](https://user-images.githubusercontent.com/2051070/197454291-82617b37-a5a8-4fed-b7a3-4fded2dbbfa6.png)

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/regular-expressions-matching-and-extracting-data

**Comment by ificiana** [comment]
I believe it's not a typo.
Using a single backslash outside an r-string, in this case, violates PEP 8 conventions
In some IDEs, this shows up as a warning like: `PEP 8: W605 invalid escape sequence '\S'`

Valid options:
`lst = re.findall(r'\S+@\S+', s)`
`lst = re.findall('\\S+@\\S+', s)`

**Comment by scissorsneedfoodtoo** [comment]
Thank you for pointing that out, @ificiana. I wasn't aware of the PEP 8 conventions regarding escape sequences.

In that case, this may need more investigation and discussion.

**Comment by scissorsneedfoodtoo** [comment]
After thinking more about this, I think it's safe to close this issue. I'll respond to the person who wrote into support individually, and send this older issue with an explanation and some examples: https://github.com/freeCodeCamp/freeCodeCamp/issues/41996

If other people raise this issue on the forum or in the support inbox, it might be worth taking another look at this, or adding a note about PEP 8 conventions to the challenge description.
