### ISSUE TITLE
Help with the Portfolio redesign

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#48234]
### Is your feature request related to a problem? Please describe.

The redesign of the Profile is way overdue. Here is the proposal for organizing the personal info section of the Profile and improving its aesthetics.

Design file:

https://www.figma.com/file/4M7uEe9kH8hgZdB07lBvj9/Untitled-(Copy)?type=design&node-id=0-1&mode=design&t=xDY6TLQqE5Ez0LF3-0

### Describe the solution you'd like

We could use icons for location and joined date as Tom suggested.
Let us know if you have other considerations before we move to the implementation.

### Describe alternatives you've considered

.

**Comment by SWELLZ** [comment]
I think an option to share your profile as a "card" would be cool. Maybe a share button with the option to share to Twitter, Instagram, as an image, etc. The card would have your name, username, streak, points, longest streak, and maybe recent badges? Sort of like how Snapchat allows you to export your profile info!

**Comment by ahmadabdolsaheb** [comment]
A share button would be a good option. OG Image Generation for news articles is on the road map. We could consider it for the profile once that  solution is deployed https://github.com/freeCodeCamp/freeCodeCamp/issues/47085

**Comment by chirag-cyber** [comment]
Under the profile section, we can add projects icon link to link our achievements and also our social media handles..

**Comment by ParthMadhvani2** [comment]
Hello, I think there must be a share button to share a portfolio. a section of achievements and projects made, and our social media handles must be included in the portfolio.

**Comment by Feanor96** [comment]
yes, section of achievements and projects is a must!

**Comment by Sboonny** [comment]
Should we add switch account, and log out buttons to the Portfolio?

I have got feedback from Estefania, that some users seek these feature in Profile like pages, so we can add them in freeCodeCamp, as well. 🤔

**Comment by Feanor96** [comment]
> Should we add switch account, and log out buttons to the Portfolio?
> 
> I have got feedback from Estefania, that some users seek these feature in Profile like pages, so we can add them in freeCodeCamp, as well. 🤔

Yeah that would also be nice..

**Comment by ahmadabdolsaheb** [comment]
Thanks for the feedback everyone.
1 ) The socials will be included next to the location (those three boxes in the mocks)
2 ) Projects, certifications, and timeline will be added at the bottom of the the general info section
3 ) Could provide me links to similar websites  which have implemented switch account, and log out buttons on the portfolio page. That would help me understand the convention better.

**Comment by Sboonny** [comment]
I have asked for similar websites, and I was getting different functionality from what I understood.

So there is a miscommunication from my part, sorry about that

**Comment by Sembauke** [comment]
Hey @ahmadabdolsaheb,

Can we put a help wanted label on this?

**Comment by BernardoDeveloper** [comment]
Have a concise design and that the user has a shareable profile, showing courses and their progress on the platform.

**Comment by oriooctopus** [comment]
I never knew that FreeCodeCamp kept track of your streak! I remember when I used Duolingo the streak always helped to keep me motivated. Similarly, I know a few video games that use streaks as a way to encourage daily use. I wonder if we could make this more prominent to gamify the learning experience a little bit and make consistent learning a bit more emotionally rewarding. Perhaps every time the street gets bigger there's a little notification/annoucement bar that pops out from the top that says something like: "Your streak is now 14, that's an all time high!" 

I know this is not the relevant issue to talk about this so I'd be happy to open up a new issue to discuss it further.

**Comment by Sboonny** [comment]
We should open new issue for this 👍.

I disagree with including streak in general, as it may incentives campers into taking a certification they don't want or need, to keep the streak going, which is against one of the principles of freeCodeCamp.

**Comment by gmgrigsby** [comment]
I am curious as to which social media handles will be available to display in the new profile? I made a suggestion in the FCC Forums to add an option for Mastadon, and was directed to the GitHub issues for the project, which is how I came to find this post.

**Comment by oriooctopus** [comment]
So a few thoughts:
- Something CodeAcademy includes in their profile is when they use it was last active. I think that's useful information if we can do it easily ![Screen Shot 2022-12-17 at 9 59 28 PM](https://user-images.githubusercontent.com/20331238/208282216-9a28501f-d1ae-44aa-8194-9616f51661bf.png)
- Although I initially strongly agreed with the idea to add share buttons to the profile I found that no other similar site seems to have these in their profile. I checked Coursera, Duolingo, and CodeAcademy. I imagine those other sites considered it and didn't find it useful enough. Just thinking out loud because I'm not necessarily opposed to it, but I just view this observation as a bit of a red flag.
- in the designs I don't see an edit button
- I think it makes sense to put longest streak and current streak next to each other since they're related
-  ![Screen Shot 2022-12-17 at 10 03 21 PM](https://user-images.githubusercontent.com/20331238/208282356-559f63af-7dc3-4d0f-a533-49d903f34168.png) What are these three dots for?
- ![Screen Shot 2022-12-17 at 10 04 01 PM](https://user-images.githubusercontent.com/20331238/208282376-77b19874-da16-4222-ad4f-9967bf441507.png) in the current profile there is a grid of the days where you completed the challenge. I thought this was cool, what's the reason for not including it in the new design?
- in the current design there is a timeline and certifications section. Is that also going to be included? If so, is the reason for it not being included in the above design that it's not being altered?

**Comment by ShaunSHamilton** [comment]
> Something CodeAcademy includes in their profile is when the user was last active. I think that's useful information if we can do it easily

I would discourage this. It is another field we would have to add to the user record, and largely goes against freeCodeCamp's "collecting as little as possible" stance.

**Comment by oriooctopus** [comment]
That makes sense, I think what it adds is pretty minor so considering what you've just said I agree that it shouldn't be added

**Comment by ahmadabdolsaheb** [comment]
@gmgrigsby  thank you for your suggestion. Ideally we would have a selector to allow users choose a number of social networks. Due to limited resources, we are sticking with the current functionality so contributors and maintainers can focus on the mission critical issues/features.

**Comment by oriooctopus** [comment]
> The edit will happen from the settings page for now.
My concern is that it's harder for users to find, I wouldn't necessarily assume that to edit the profile information I have to go to the settings page. Most of the time on a profile page (also consistent with the other sites I checked), there is an edit button on the profile page itself. Can we at least add an edit button that when clicked takes them to the settings page?

**Comment by ahmadabdolsaheb** [comment]
> > The edit will happen from the settings page for now.
> 
> My concern is that it's harder for users to find, I wouldn't necessarily assume that to edit the profile information I have to go to the settings page. Most of the time on a profile page (also consistent with the other sites I checked), there is an edit button on the profile page itself. Can we at least add an edit button that when clicked takes them to the settings page?

that makes sense.

**Comment by JordanMooree** [comment]
Curious, is there a Figma file to this design that was proposed?

**Comment by ahmadabdolsaheb** [comment]
There is, but think of it as a wireframe rather than a mockup. @Sembauke is looking into the implementation, so we should be able to see the changes in his pr soon.

**Comment by bbsmooth** [comment]
One thing the Profile page should probably have is an `h1` heading near the top. I suppose we could convert the username that is currently an `h2`.

**Comment by spiritanand** [comment]
Has anyone got started in converting the design to code?

**Comment by ojeytonwilliams** [comment]
I believe @Sembauke was intending to look into it. Is that still the plan, Sem?

**Comment by ahmadabdolsaheb** [comment]
@Sembauke are you still interested in this?

**Comment by BirushaNdegeya** [comment]
__Helo there__  👋 !

Your design looks okay; however, I would like to mention that in modern-day design, it's important to include a switch button between light and dark modes for accessibility, particularly for people experiencing eye-related issues. Additionally, providing social media links facilitates communication with users.

__Happy coding__ 🚀🚀🚀

**Comment by Abdulsaboor2004** [comment]
I think it should also display your email address or a contact form to get user's information.
Also add a call-to-action button (like., “Hire Me” or “Work With Me”).

**Comment by ahmaxed** [comment]
Thanks for the suggestions. The issue is for redesigning the current features that exist on portfolio page. The design has been finalized. Please proceed if you are interested in helping with implementing the changes.

**Comment by pasan2002** [comment]
I believe it would be beneficial to include a section detailing professional experiences and skills.

**Comment by shootermv** [comment]
i can see the new design figma, but may be it can be better to have also the design for mobile as well...

**Comment by jenna5376** [comment]
@shootermv  I'll work on the mobile design!

**Comment by ahmaxed** [comment]
Updated the mobile version and the desktop version.

**Comment by jenna5376** [comment]
I also created a mobile version. Feel free to suggest any changes
https://www.figma.com/file/dfMxnhDgZmQOt3ZoVajaEB/freeCodeCamp-Profile?type=design&node-id=0%3A1&mode=design&t=JTaWEYcAAdabN4oG-1

**Comment by ahmaxed** [comment]
Thanks for the mock up. I have updated the mobile version and took inspirations from your version. The title of the stats might run in one another based on the length of the translations. Here is the mock for your reference:
[figma.com/file/4M7uEe9kH8hgZdB07lBvj9/Untitled-(Copy)?type=design&node-id=0%3A1&mode=design&t=i1k1rk04gyBhUAwd-1](https://www.figma.com/file/4M7uEe9kH8hgZdB07lBvj9/Untitled-(Copy)?type=design&node-id=0%3A1&mode=design&t=i1k1rk04gyBhUAwd-1)

It is also helpful to breakdown the prs based on their secsion:

- [ ] bio
- [ ] stat
- [ ] badges
- [ ] projects

**Comment by jenna5376** [comment]
@ahmaxed Good point! However, I am worried that the bio, stats, and badges sections take up too much screen real estate in your version--especially if the user has multiple badges. This could result in profile viewers clicking off the website before ever reaching the project section, which is arguably more important.

I will try to come up with alternative designs for the stats representation!

**Comment by ahmaxed** [comment]
I agree, let's go with you version of the badges. I will update the mocks accordingly

**Comment by jenna5376** [comment]
@ahmaxed For the stats section, what if we have the titles span two lines instead of one? This eliminates the problem of titles running too long and takes up less real estate than if we display stats vertically. I updated the [mockup](https://www.figma.com/file/dfMxnhDgZmQOt3ZoVajaEB/freeCodeCamp-Profile?type=design&node-id=1%3A2&mode=design&t=YmihiH3UvM340Y1f-1) and atttached a photo for reference.

<img width="729" alt="Screen Shot 2024-03-26 at 2 21 32 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/62906996/734cf1a3-6c97-4763-8d32-648ba466f61e">

**Comment by shootermv** [comment]
wanted to ask  steps:
will it be right to merge if only bio section will be modified according to new design (and other section will still has old look)?

**Comment by jenna5376** [comment]
@ahmaxed @shootermv If we're set with the design for now, I would also love to help implement it

**Comment by ahmaxed** [comment]
We are set with the design. Yes, one section at a time works. It would be easier to review as well.

**Comment by shootermv** [comment]
@ahmaxed ,  question:
 Can it make sense to add one more step(or PR) before  the steps you listed already - 
to wrap the `camper` component with the userContext,
in order not to pass user details as a props to `bio`, 'stats' and `badges` child components?

**Comment by shootermv** [comment]
good point @huyenltnguyen! of course we can, it is only matter of add user selector

**Comment by shootermv** [comment]
one more thing about figma design -
i think we better to have also design for a desktop (currently what we have - is a tablet and mobile)

**Comment by Rabberpoli** [comment]
I was following this issue lately and I was wondering that I might be available offering some help with implementing the new design. Is there already something to work with?

**Comment by jenna5376** [comment]
@shootermv I checked the Figma file and we already have designs for desktop and mobile! I think the only change we need to make to turn the desktop design into tablet design is decreasing the margins and maybe resizing badges/putting them in a carousel

**Comment by shootermv** [comment]
i tried to see how the current design could look on wide (1277px) screen, here is what i got:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/1336862/176b5228-2796-47b7-b331-511169e573ce)
my question here: is it good that `bio` section has only ne row?

**Comment by jenna5376** [comment]
@ahmaxed  I'm trying to implement the stats section. Are we adding a toggle to let users display stats on their profiles in settings, or is this section going to be visible by default? I'm thinking we could simply rename the "My points" setting to "My stats."

<img width="1440" alt="Screen Shot 2024-03-31 at 8 33 47 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/62906996/a4ee4d4e-ef91-4c8f-a8ce-421de6d3909f">

**Comment by ahmaxed** [comment]
@shootermv, you could use a similar grid (col, row, container) as the current profile. That should help. 
@jenna5376, that makes sense. currently the streaks are grouped with the timeline. Once those are extracted and added to the stats section, we can change "my points" to "my stats"

**Comment by shaman-004** [comment]
How about a QR code that describes the whole profile,@NehemiahDias already mentioned one card that can be sharable and has a QR code in it.

**Comment by shootermv** [comment]
should we mark `bio` and `stats` components  at this issue`s checklist as finished?

**Comment by ahmaxed** [comment]
We need to have an edit button for the bio, 
The edit button should open a modal with all of the related forms and states imported from the settings page.

**Comment by shootermv** [comment]
this `edit button` at bio area - should it be shown for someone else who looking at profile (not profile author) ?

**Comment by ahmaxed** [comment]
No, only the profile owner.

**Comment by moT01** [comment]
Is this still a work in progress @ahmaxed or is it safe to close?

**Comment by ahmaxed** [comment]
Only the edit buttons are left. I can close this and create a more focused issue.
