### ISSUE TITLE
[accessibility-quiz]: grammar 

### ISSUE THREAD

**Issue by disabledandfab** [freeCodeCamp/freeCodeCamp#48238]
### Describe the Issue

There's a consistent grammatical issue. The author uses "it's" to indicate possession, when the correct word is "its". Due to this, I am also willing to look for other grammatical errors. They could cause confusion, or, at the very least, annoyance.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-10

### Your code

```

```
/*Note: this issue is present throughout the entire challenge*/

### Expected behavior

n/a

### Screenshots

n/a

### System

- Device: Macbook Air
- OS: Mac OS Ventura
- Browser: Chrome

### Additional context

This is more of a writing issue than a tech one. I hope that's ok.

**Comment by ShaunSHamilton** [comment]
@disabledandfab Thank you for taking the time to open this.

 > /Note: this issue is present throughout the entire challenge/

I am only able to see the use of `it's` in 2 challenges:
- step-8
- step-10

Would you mind sharing any more?

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
