### ISSUE TITLE
style issue

### ISSUE THREAD

**Issue by catfish68** [FreeCodeCamp/FreeCodeCamp#4824]
Hello i have a style issue,  I have it as 
<style>
 h2 {color: blue;}
</style> 

The system recognizes everything but the closing style tag

**Comment by ltegman** [comment]
Please give us more details, like what challenge you are on.

**Comment by ltegman** [comment]
Closing as a duplicate of #4833. Please continue further discussion in that thread.

Thanks and happy coding!
