### ISSUE TITLE
Generate Random Whole Numbers within a Range

### ISSUE THREAD

**Issue by riccardopit** [freeCodeCamp/freeCodeCamp#48248]
### Describe the Issue

I'm following the "JavaScript Algorithms and Data Structures" course. In the section "Basic JavaScript", lesson "Generate Random Whole Numbers within a Range" i think there is an error. The correct code is "Math.floor(Math.random() * (max - min + 1) + min)" but the lesson shows the following code "Math.floor(Math.random() * (max - min + 1)) + min". The code ckecker works corretly in both cases but in my opinion the right code is mine.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-within-a-range

### Your code

return Math.floor(Math.random() * (myMax - myMin + 1) + myMin)

### Expected behavior

code checker gives an error if you write:
return Math.floor(Math.random() * (myMax - myMin + 1)) + myMin

### Screenshots

![Generate Random Whole Numbers within a Range](https://user-images.githubusercontent.com/102901401/197767148-fe7b9235-3641-4ad4-bf49-c69db54d4531.PNG)

### System

Browser: Chrome Version 106.0.5249.119 (Build ufficiale) (a 64 bit)

### Additional context

Link to a topic on stackoverflow where it is used my formula instead of the one provided by freeCodeCamp.
https://stackoverflow.com/questions/62981108/how-does-math-floormath-random-max-min-1-min-work-in-javascript

**Comment by jeremylt** [comment]
Both answers are correct and produce identical results

**Comment by riccardopit** [comment]
After a check, I agree with you. Thanks for the answer
