### ISSUE TITLE
Waypoint: Use Hex Code for Specific Colors

### ISSUE THREAD

**Issue by DanteSparda39** [FreeCodeCamp/FreeCodeCamp#4825]
I've done what was expected but still can't move on. The code is correct since it was simply changing the color black to its hex code. Please help.

**Comment by Phumphie** [comment]
I am having the same problem!

**Comment by ltegman** [comment]
Hmm. I can confirm this is an issue but I can't figure out why yet. The test it's running is `$("body").css("background-color") === "rgb(0, 0, 0)"`, which when I console.log from the editor returns true. Hopefully someone else will have an idea where to go with this one.

**Comment by ltegman** [comment]
We will be tracking this issue in #4833. Please continue further discussion in there.

Thanks and happy coding!
