### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ritikbanger** [freeCodeCamp/freeCodeCamp#48257]
Hello, My name is Ritik Banger, I am a Full Stack Javascript Engineer with robust problem-solving skills and proven experience in creating and designing web apps in a test driven environment and deploy them to cloud servers. 

I am an open-source contributor, I have created react18-input-otp npm package. I have also contributed to webpack, core-js, react-hook-form, and node-emoji.

I would like to contribute to freeCodeCamp, please add me to the organization.

**Comment by ojeytonwilliams** [comment]
Hi @ritikbanger you're more than welcome to contribute to freeCodeCamp.  If you're unsure how best to help out, I would start is by reading our [contribution guidelines](https://contribute.freecodecamp.org/).
