### ISSUE TITLE
Sentence that needs improvement in the new JS rpg project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48273]
**Looking forward for reporting a security issue:**
@Dario-DC, reported sentence that needs more context, and I agree.

Here is the sentence

https://github.com/freeCodeCamp/freeCodeCamp/blob/a00844eac58a77f0a192a8443070a9699dbdb16e/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8f14fe6d1fc72454648c7.md#L26

I suggest

> Your function should start with `monsterStats.style.display = none`, don't add empty line after the function.

**Comment by Sembauke** [comment]
I suggest to keep it simple:
> It should be the first line of the `update` function.

**Comment by Sboonny** [comment]
I think there is a leeway for spoiling, because this is the 3rd test. But I do agree short answers are better, what about:

> Your newly added code should be below `update` function, without extra lines.

**Comment by Dario-DC** [comment]
What about this:

> You should add your code in the first line of the `update` function.

**Comment by Sboonny** [comment]
I am opening the issue, you should apply Dario comment here https://github.com/freeCodeCamp/freeCodeCamp/issues/48273#issuecomment-1294023664

---

**Comment by Rancho2002** [comment]
> I am opening the issue, you should apply Dario comment here [#48273 (comment)](https://github.com/freeCodeCamp/freeCodeCamp/issues/48273#issuecomment-1294023664)
> 
> If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

hey I wish to do this changes? Can I ?

**Comment by Sboonny** [comment]
Sure, you can open a pull request with the changes, after you have read our contribution guide 👍

**Comment by Rancho2002** [comment]
![image](https://user-images.githubusercontent.com/92109154/198531679-4e811883-0fb0-4c72-b46e-a49ca8603428.png)
I have to change this line to 
'You should add your code in the first line of the ```update``` function' 
this line, right? @Sboonny

**Comment by Sboonny** [comment]
Yeab

**Comment by Rancho2002** [comment]
hi @Sboonny I made a PR as you said

> Sure, you can open a pull request with the changes, after you have read our contribution guide 👍
