### ISSUE TITLE
Link to an external site in advanced node and express section

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48278]
We have an external link in the below paragraph, which link to [this page](https://github.com/settings/developers)

> Obtaining your *Client ID and Secret* from GitHub is done in your account profile settings under 'developer settings', then <a href="https://github.com/settings/developers" target="_blank" rel="noopener noreferrer nofollow">'OAuth applications'</a>. Click 'Register a new application', name your app, paste in the url to your Replit homepage (**Not the project code's url**), and lastly, for the callback url, paste in the same url as the homepage but with `/auth/github/callback` added on. This is where users will be redirected for us to handle after authenticating on GitHub. Save the returned information as `'GITHUB_CLIENT_ID'` and `'GITHUB_CLIENT_SECRET'` in your `.env` file.

here is the file:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.md

Ideally, the camper doesn't need to use external docs to pass the current step, but this may not be possible with a little info, we are giving.

To sort this issue, we need to create an Article about `How to set up OAuth application`, like this one https://www.freecodecamp.org/news/a-quick-introduction-to-oauth-using-passport-js-65ea5b621a/, but with way to sort it using GitHub ClientID and secret

Or we can change the context from using GitHub to using Google.

**Comment by naomi-lgbt** [comment]
I can prep an article real quick.

**Comment by ShaunSHamilton** [comment]
Let us not change this until #47349 is landed.

**Comment by naomi-lgbt** [comment]
Article is live: https://www.freecodecamp.org/news/how-to-set-up-a-github-oauth-application/

**Comment by ppeters0502** [comment]
I'd love to contribute on this issue! 
So just to make sure I'm understanding, now that the article is live and #47349 is merged, all that needs to happen is just the link on this [page](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.md) just needs to be updated to reference the new article?

**Comment by Sboonny** [comment]
Yes 👍

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by ppeters0502** [comment]
PR Submitted! I contemplated removing the additional Github Client/Secret instructions in the curriculum, since they're kind of redundant. Some of the instructions were specific to this assignment though, so in the end I kept them in. If anyone disagrees, let me know and I can take the redundant parts out.
