### ISSUE TITLE
Remove `.replit` and `replit.nix` Files From Boilerplate Repos

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#48274]
One of the Replit devs mentioned that they're making a lot of changes on their end, and recommends that we remove the `.replit` and `replit.nix` files from our boilerplate repos whenever possible. We should be able to do this in most of the boilerplate repos without issue.

There may be a couple of exceptions, though, like with the [Rust in Replit](https://github.com/freeCodeCamp/Rust-In-Replit) project boilerplate. For that project, there are some commands that need to run when the project is imported.

The recommendation for repos that need special commands is to leave the `.replit` and `replit.nix` files in the repo, but to make sure the only difference between them and the autogenerated `.replit` and `replit.nix` files are the commands that need to run.

Here's a list of the project boilerplates that should be updated. Please let me know if I missed any:

#### Practice Projects

- [x] Managing Packages with NPM
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-npm/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-npm/pull/491
    - Learn description: 

- [x] Basic Node and Express
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-express/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-express/pull/110
    - Learn description: 

- [x] MongoDB and Mongoose
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-mongomongoose/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/51
    - Learn description: 

#### Required Projects

- [x] Timestamp Microservice
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-timestamp/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/85
    - Learn description: 

- [x] Request Header Parser Microservice
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-headerparser/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-headerparser/pull/31
    - Learn description: 

- [x] URL Shortener Microservice
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-urlshortener/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/53
    - Learn description: 

- [x] Exercise Tracker
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/67
    - Learn description: 

- [x] File Metadata Microservice
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-filemetadata/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-filemetadata/pull/23
    - Learn description: 

#### Practice Projects

- [x] Quality Assurance and Testing with Chai
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-mochachai/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-mochachai/pull/84
    - Learn description: 

- [x] Advanced Node and Express
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-advancednode/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-advancednode/pull/26
    - Learn description: 

#### Required Projects

- [x] Metric-Imperial Converter
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/pull/25
    - Learn description: 

- [x] Issue Tracker
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-issuetracker/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/26
    - Learn description: 

- [x] Personal Library
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-library
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-library/pull/18
    - Learn description: 

- [x] Sudoku Solver
  - Boilerplate repo: https://github.com/freecodecamp/boilerplate-project-sudoku-solver
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-sudoku-solver/pull/26
    - Learn description: 

- [x] American British Translator
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-american-british-english-translator/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-american-british-english-translator/pull/22
    - Learn description: 

#### Required Projects

- [x] Arithmetic Formatter
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter/pull/13
    - Learn description: 

- [x] Time Calculator
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-time-calculator
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-time-calculator/pull/7
    - Learn description: 

- [x] Budget App
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-budget-app
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-budget-app/pull/14
    - Learn description: 

- [x] Polygon Area Calculator
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-polygon-area-calculator
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-polygon-area-calculator/pull/7
    - Learn description: 

- [x] Probability Calculator
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-probability-calculator
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-probability-calculator/pull/10
    - Learn description: 

#### Required Projects

- [x] Mean-Variance-Standard Deviation Calculator
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator/pull/8
    - Learn description: 

- [x] Demographic Data Analyzer
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer/pull/12
    - Learn description: 

- [x] Medical Data Visualizer
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/pull/22
    - Learn description: 

- [x] Page View Time Series Visualizer
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer/pull/11
    - Learn description: 

- [x] Sea Level Predictor
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-sea-level-predictor
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-sea-level-predictor/pull/9
    - Learn description: 

#### Practice Projects

- [x] Information Security with HelmetJS
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-infosec/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-infosec/pull/54
    - Learn description: 

#### Required Projects

- [x] Stock Price Checker
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-stockchecker/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-stockchecker/pull/30
    - Learn description: 

- [x] Anonymous Message Board
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-messageboard/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-messageboard/pull/23
    - Learn description: 

- [x] Port Scanner
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-port-scanner
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-port-scanner/pull/5
    - Learn description: 

- [x] SHA-1 Password Cracker
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-SHA-1-password-cracker
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-SHA-1-password-cracker/pull/4
    - Learn description: 

- [x] Secure Real Time Multiplayer Game
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game/pull/20
    - Learn description: 

#### Required Projects

- [x] Rock Paper Scissors
  - Boilerplate repo: https://github.com/freeCodeCamp/boilerplate-rock-paper-scissors
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/boilerplate-rock-paper-scissors/pull/5
    - Learn description: 

## Special Cases

- [x] Rust in Replit
  - Tasks:
    - Import the project into Replit
    - Copy the autogenerated `.replit` and `replit.nix` files back into the boilerplate
    - Add the special commands back to the boilerplate's `.replit` file — the only diff between Replit's autogenerated `.replit` file and the one in the boilerplate are those special commands
  - Boilerplate repo: https://github.com/freeCodeCamp/Rust-In-Replit/
  - PRs:
    - Boilerplate: https://github.com/freeCodeCamp/Rust-In-Replit/pull/27
    - Learn description: N/A

**Comment by ShaunSHamilton** [comment]
Excellent issue write-up, as always, Kris 🚀 
I will tackle the Rust in Replit project.

**Comment by naomi-lgbt** [comment]
Hey @scissorsneedfoodtoo we should be fine to open this for contribution yes?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for opening up that PR @ShaunSHamilton. I'll take a look at it now.

@naomi-lgbt, yes, it should be fine to open this up for contribution now. I did a bit of testing with the different project types and didn't run into any issues after removing the `.replit` and `replit.nix` files.

The only real difference I noticed is that, while Replit seems to pick up a run command for Node projects from the `package.json` file, it's slightly different for Python projects.

When importing a Python project, learners have to click "Use run command" and the "Done" button. The command `python3 main.py` is already there:

![image](https://user-images.githubusercontent.com/2051070/198533503-79404da8-46c0-4cca-b5f7-eedab6b80080.png)

That config menu defaults to "Use default interpreter" with a dropdown. Learners could select the `main.py` file from the dropdown, then click the "Done" button, but the other method seems a bit easier to communicate.

We'll probably need to update the Learn descriptions for Python projects with instructions on how to set that run command. Once those updated descriptions are live on Learn, we can merge PRs to the Python project boilerplate repos.

**Comment by Prince-Mendiratta** [comment]
Hi team! To solve this monotonous(?) task in a fun and efficient way, I created a script for automating this full process!

Here's the link to that project - https://github.com/Prince-Mendiratta/mass-repo-editor

---
I am not sure what/where I should change the Learn description to so any pointers on that and I'll get that done as well. 😄

**Comment by RandellDawson** [comment]
How far off is FCC from being able to have the users create these project on FCC controlled servers instead of constantly changing the repos because replit does not have a clue of the mess they create every time they make a config change?

**Comment by Prince-Mendiratta** [comment]
@scissorsneedfoodtoo When can we work on merging these PRs as well and closing this issue for good?

**Comment by scissorsneedfoodtoo** [comment]
Hey @Prince-Mendiratta, thanks for your patience and again for all of your help with these updates.

We plan to do a new release of Learn soon. Once the updated text you added in https://github.com/freeCodeCamp/freeCodeCamp/pull/48374 goes live, we can go in and merge all of the PRs you opened in the boilerplate repos listed above.

This is something we need to coordinate internally, but I will definitely tag you and close this issue once that's all done 🙂

**Comment by scissorsneedfoodtoo** [comment]
Thank you again for all of your help updating these boilerplate repos and descriptions @Prince-Mendiratta.

Just went through and merged all of the PRs listed here. Also cloned and tested a few projects and everything seems to work as expected.

It should be safe to close this now, and I'll do more thorough testing after the weekend.
