### ISSUE TITLE
Word mistake that doesn't make sense.

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#48270]
### Describe the Issue

In [this](https://www.freecodecamp.org/learn/front-end-development-libraries/redux/use-a-switch-statement-to-handle-multiple-actions) page, the following line is incorrect English, it says
> they are all run any time an action dispatch is made,

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/use-a-switch-statement-to-handle-multiple-actions

### Your code

NA

### Expected behavior

The correct English IMO is
>  they can all run any time an action dispatch is made,

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jeremylt** [comment]
The original wording is correct - your proposal changes the meaning of the sentence.
