### ISSUE TITLE
Learn Relational Databases by Building a Mario Database - Typo in hint

### ISSUE THREAD

**Issue by nreiter29** [freeCodeCamp/freeCodeCamp#48285]
### Describe the Issue

Writing issue in the hints

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

look at the screeenshot

### Expected behavior

Rename CREAT TABLE table_name(); into CREATE TABLE table_name();

### Screenshots

![image](https://user-images.githubusercontent.com/90345883/198528585-29579483-3d32-4a0c-a754-522486b6513c.png)

### System

- Device: [Windows PC]
- OS: [Windows 11]
- Browser: [Chrome]
- Version: [22]

**Comment by moT01** [comment]
This is the [file with the typo](https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/main/TUTORIAL.md#540-create-characters-table) - and here's some [info on how to work on those repos.](https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad)
