### ISSUE TITLE
Run Test fail on : Waypoint: Style the HTML Body Element

### ISSUE THREAD

**Issue by weiquanpoo** [FreeCodeCamp/FreeCodeCamp#4828]
It is an easy task and had provided the answer in the description.
However it doesn't give me a tick.

>Waypoint: Style the HTML Body Element
>Now let's start fresh and talk about CSS inheritance.
>Every HTML page has a body element.
>We can prove that the body element exists here by giving it a background-color of black.
>We can do this by adding the following to our style element:
>
>body {
>background-color: black;
>}

My Code:

><style>
>body {
>background-color: black;
>}
></style>

![untitled](https://cloud.githubusercontent.com/assets/7202228/11492318/61e34fde-9826-11e5-9a8a-93eae17e731f.png)

**Comment by catfish68** [comment]
I am having the same issue

**Comment by ltegman** [comment]
Closing as a duplicate of #4825. Not quite the same waypoint, but it stems from the same issue.

Thanks and happy coding!

**Comment by catfish68** [comment]
Was the issue resolved?

**Comment by ltegman** [comment]
@catfish68 No. We are tracking the issue in #4833

**Comment by VladimirRazi** [comment]
i have the same issue.i used the same code and i can't run the test :(
