### ISSUE TITLE
Sudoku Solver example program accepts invalid Sudoku puzzles

### ISSUE THREAD

**Issue by b-van-b** [freeCodeCamp/freeCodeCamp#48307]
### Describe the Issue

The example Sudoku Solver accepts erroneous input and produces an incorrect "solution," rather than rejecting it.

### Affected Page

https://sudoku-solver.freecodecamp.rocks/

### Your code

Input the following and click "solve:"
```
.99..5.1.85.4....2432......1...69.83.9.....6.62.71...9......1945....4.37.4.3..6..
```

### Expected behavior

It should produce the following JSON response: `{ "error": "Puzzle cannot be solved" }`

### Screenshots

This is what the erroneous result looks like:

![sudoku](https://user-images.githubusercontent.com/115096508/198814195-0bafcbd9-5946-4823-8f49-af2b8b50605d.png)

The solution includes an invalid row, column, and region.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: 106.0.5249.119

**Comment by SavainB** [comment]
can i work on this ?
