### ISSUE TITLE
impossible to share my solution in github as gist. the browser return "about blank"

### ISSUE THREAD

**Issue by koouty** [FreeCodeCamp/FreeCodeCamp#4831]
Challenge [Bonfire: Everything Be True](http://www.freecodecamp.com/challenges/bonfire-everything-be-true#?solution=function%20every(collection%2C%20pre)%20%7B%0A%20%20var%20paquet%20%3D%20%5B%5D%3B%0A%20%20console.log(paquet)%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20collection.length%3B%20i%20%2B%2B)%20%7B%0A%20%20%20%20var%20Gc%20%3D%20collection%5Bi%5D%3B%0A%20%20%20%20for(var%20key%20in%20Gc)%20%7B%0A%20%20%20%20%20%20%20%20console.log(Gc%5Bkey%5D%2C%20%22%20%22%2C%20key)%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20if%20((Gc.key%20%3D%3D%3D%20pre%20%7C%7C%20key%20%3D%3D%3D%20pre)%20%26%26%20Gc%5Bpre%5D%20)%20%7B%0A%20%20%20%20%20%20%20%20paquet.push(true)%3B%0A%20%20%20%20%20%20%20%20console.log(paquet)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20console.log(collection.length%2C%20%27%26%27%2C%20paquet.length)%3B%0A%20%20if%20(collection.length%20%3D%3D%3D%20paquet.length)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%20%7Breturn%20false%3B%7D%0A%20%20%2F%2F%20Is%20everyone%20being%20true%3F%0A%20%0A%7D%0A%0Aevery(%5B%7B%22user%22%3A%20%22Tinky-Winky%22%2C%20%22sex%22%3A%20%22male%22%2C%20%22age%22%3A%200%7D%2C%20%0A%7B%22user%22%3A%20%22Dipsy%22%2C%20%22sex%22%3A%20%22male%22%2C%20%22age%22%3A%203%7D%2C%20%0A%7B%22user%22%3A%20%22Laa-Laa%22%2C%20%22sex%22%3A%20%22female%22%2C%20%22age%22%3A%205%7D%2C%20%0A%7B%22user%22%3A%20%22Po%22%2C%20%22sex%22%3A%20%22female%22%2C%20%22age%22%3A%204%7D%5D%2C%20%22age%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function every(collection, pre) {
  var paquet = [];
  console.log(paquet);
  for(var i = 0; i < collection.length; i ++) {
    var Gc = collection[i];
    for(var key in Gc) {
        console.log(Gc[key], " ", key);
        
      if ((Gc.key === pre || key === pre) && Gc[pre] ) {
        paquet.push(true);
        console.log(paquet);
      }
    }
  }
  console.log(collection.length, '&', paquet.length);
  if (collection.length === paquet.length) {
    return true;
  }
  else {return false;}
  // Is everyone being true?
 
}

every([{"user": "Tinky-Winky", "sex": "male", "age": 0}, 
{"user": "Dipsy", "sex": "male", "age": 3}, 
{"user": "Laa-Laa", "sex": "female", "age": 5}, 
{"user": "Po", "sex": "female", "age": 4}], "age");
```

**Comment by koouty** [comment]
the url of the exercise: http://www.freecodecamp.com/challenges/bonfire-everything-be-true#?solution=function%20every%28collection%2C%20pre%29%20{%0A%20%20var%20paquet%20%3D%20[]%3B%0A%20%20console.log%28paquet%29%3B%0A%20%20for%28var%20i%20%3D%200%3B%20i%20%3C%20collection.length%3B%20i%20%2B%2B%29%20{%0A%20%20%20%20var%20Gc%20%3D%20collection[i]%3B%0A%20%20%20%20for%28var%20key%20in%20Gc%29%20{%0A%20%20%20%20%20%20%20%20console.log%28Gc[key]%2C%20%22%20%22%2C%20key%29%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20if%20%28%28Gc.key%20%3D%3D%3D%20pre%20||%20key%20%3D%3D%3D%20pre%29%20%26%26%20Gc[pre]%20%29%20{%0A%20%20%20%20%20%20%20%20paquet.push%28true%29%3B%0A%20%20%20%20%20%20%20%20console.log%28paquet%29%3B%0A%20%20%20%20%20%20}%0A%20%20%20%20}%0A%20%20}%0A%20%20console.log%28collection.length%2C%20%27%26%27%2C%20paquet.length%29%3B%0A%20%20if%20%28collection.length%20%3D%3D%3D%20paquet.length%29%20{%0A%20%20%20%20return%20true%3B%0A%20%20}%0A%20%20else%20{return%20false%3B}%0A%20%20%2F%2F%20Is%20everyone%20being%20true%3F%0A%20%0A}%0A%0Aevery%28[{%22user%22%3A%20%22Tinky-Winky%22%2C%20%22sex%22%3A%20%22male%22%2C%20%22age%22%3A%200}%2C%20%0A{%22user%22%3A%20%22Dipsy%22%2C%20%22sex%22%3A%20%22male%22%2C%20%22age%22%3A%203}%2C%20%0A{%22user%22%3A%20%22Laa-Laa%22%2C%20%22sex%22%3A%20%22female%22%2C%20%22age%22%3A%205}%2C%20%0A{%22user%22%3A%20%22Po%22%2C%20%22sex%22%3A%20%22female%22%2C%20%22age%22%3A%204}]%2C%20%22age%22%29%3B
the url after the click about:blank

**Comment by bugron** [comment]
Currently sharing solutions as gists isn't working anywhere, looking into it, seems another refactor related issue.

**Comment by koouty** [comment]
for me the problem remain the same, exactly th same

**Comment by bugron** [comment]
@koouty this issue is fixed and, hopefully, will be in production soon.
