### ISSUE TITLE
Typo on how to moderator handbook document

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48310]
In the document, there is a sentence saying this:

> show if off

But this section is talking about dealing with solutions [in this section](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/moderator-handbook.md#dealing-with-posted-solutions), it should be changed to this:

> show it off.
 
 here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/moderator-handbook.md#:~:text=If%20a%20user%20creates%20a%20thread%20asking%20for%20feedback%20on%20a%20solution%2C%20move%20the%20thread%20to%20the%20feedback%20subforum%20and%20blur%20the%20solution%2C%20as%20necessary.%20If%20the%20user%20is%20only%20posting%20the%20solution%20to%20show%20if%20off

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by synoraeusebio** [comment]
Hi there! I'm definitely a first-timer and would like to fix this. You can assign this issue to me.

**Comment by Sboonny** [comment]
Hi @synoraeusebio, feel free to open a pull request after you have read our contribution guide

**Comment by saursagar** [comment]
Hey there! I would like to fix this issue,you can assign this to me.

**Comment by Sboonny** [comment]
Hey @saursagar, feel free to open a pull request after you have read our contribution guide
