### ISSUE TITLE
Preview external window disappears when moving to the next challenge

### ISSUE THREAD

**Issue by nicolo-ribaudo** [freeCodeCamp/freeCodeCamp#48326]
### Describe the Issue

I have two screens: I use one to keep the editor open and one to keep the preview window.

When I click on the "Submit and go to the next challenge" button, the preview window disappears: I have to re-open it in a separate window, and re-move it to the second screen.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-29

### Steps to Reproduce

1. Open a step of the "(New) Responsive Web Design" curriculum
2. Click on the button to open the preview in a second window (top-right, next to the "Preview" button)
3. Complete the step, click on "Check Your code" and then on "Submit and go to the next challenge"
4. The preview window closes

### Expected behavior

The preview window should stay open, containing the preview of the next step

### System

- Device: Laptop
- OS: Ubuntu 22.04
- Browser: Chrome
- Version: 106

### Additional context

This may be related to https://github.com/freeCodeCamp/freeCodeCamp/issues/47608

**Comment by CallmeHongmaybe** [comment]
Don't mean to spam here...but does anyone know where to find the code for popping up the window ?

**Comment by ojeytonwilliams** [comment]
@CallmeHongmaybe it's a little complicated, but if you start from
https://github.com/freeCodeCamp/freeCodeCamp/blob/52953a5b95b8abef7189de7a42391b8e600b2fb9/client/src/templates/Challenges/components/preview-portal.tsx you can see how it's used.

Precisely how the user's code makes it into the preview is a good deal more convoluted, but I wouldn't worry about that for this issue.  As long as the `Preview` component is shown, the user's code should get injected into it.

**Comment by CallmeHongmaybe** [comment]
Thanks for the walk through. 
As I'm still new here, am I going to be assigned to this issue ( in order to prevent multiple linked PRs ? )

**Comment by ojeytonwilliams** [comment]
We do not typically assign issues, but you are very welcome to work on this. If you haven't already, please take a look at our [contribution guidelines](https://contribute.freecodecamp.org) which should cover everything you need to know.

**Comment by nicolo-ribaudo** [comment]
@CallmeHongmaybe When I opened this issue I investigated a bit, but I ended up opening an issue instead of a PR because I couldn't finish. If you need some pointers:
- When going from one step to the one after, the whole UI gets unmounted and remounted.
- This means that the state in [`DesktopLayout`](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/classic/desktop-layout.tsx) to track where to show the preview gets reset: https://github.com/freeCodeCamp/freeCodeCamp/blob/de02417bd562811dd3eb0bd17d40f33f790125a3/client/src/templates/Challenges/classic/desktop-layout.tsx#L45-L46
  - We should probably move that state to the global redux store, in https://github.com/freeCodeCamp/freeCodeCamp/tree/main/client/src/templates/Challenges/redux
- [`PreviewPortal`](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/components/preview-portal.tsx) gets unmounted and remounted too, since it's a child of `DesktopLayout`
  - Instead of doing `window.open()` on mount and `externalWindow.close()` on unmount, we should store the window in the global state and:
    - not close it on unmount
    - when mounting, if the window already exist we should just "reset" it (by doing `html.innerHTML = ""`, where `html` is the root `<html>` element accessible using `externalWindow.document.firstElementChild`).
  - `externalWindow.document` is already stored in the global redux store (you can see `storePortalDocument` and `removePortalDocument` in that file): we can probably change it to just store the window, and rename that state to `portalWindow` instead of `portalDocument`.

**Comment by ojeytonwilliams** [comment]
Thanks for taking the time to share your insights, @nicolo-ribaudo, they're very helpful.

One thing to watch out for, though: we do need to close the external window when we leave challenge pages, since it doesn't make sense to leave it dangling there as the user navigates to unrelated parts of the site (settings, say).

**Comment by CallmeHongmaybe** [comment]
So far I've managed to prevent the window from closing, and once we click submit and go to next challenge, the window went blank while the preview pane shows the html result. 
I'd like to know if I've made lapses in logic, and whether I can send in the screencast directly on this thread.
Many thanks everyone :)

**Comment by CallmeHongmaybe** [comment]
Thanks for the very detailed suggestion.
@nicolo-ribaudo by storing the window in global state you mean we're not going to create a new window but to rewrite the existing window is that right ?

**Comment by nicolo-ribaudo** [comment]
Yes exactly!

**Comment by KravMaguy** [comment]
> Yes exactly!

Ok ive done it, it is working as expected. I hope you like the added feature. I agree that your suggested improvement provides a better user experience now.
