### ISSUE TITLE
 Add one more form of authentication by facebook.

### ISSUE THREAD

**Issue by DeiseCristiane** [freeCodeCamp/freeCodeCamp#48325]
### Is your feature request related to a problem? Please describe.

Many people have the habit of using facebook as authentication, and the platform does not offer this option, which can cause disinterest on the part of the user.

### Describe the solution you'd like

Add one more form of authentication through facebook.

### Describe alternatives you've considered

I did no.t have

**Comment by ieahleen** [comment]
Thank you for your feature request. The Facebook login method has been removed a few months ago, I don't think it will be reintroduced
