### ISSUE TITLE
CSS and Style element tests failing with correct code.

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/FreeCodeCamp#4833]
This will be the central issue for tracking this problem. So far it appears to be effecting tests that look for the `style` element or that test for specific style elements on `body`. Please let us know if you see cases that break from this pattern.

**Comment by ltegman** [comment]
Examples of this problem can be found on [Waypoint: Use JQuery to Modify the Entire Page](http://www.freecodecamp.com/challenges/waypoint-use-jquery-to-modify-the-entire-page?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target1%22).prop(%22disabled%22%2C%20true)%3B%0A%20%20%20%20%24(%22%23target4%22).remove()%3B%0A%20%20%20%20%24(%22%23target2%22).appendTo(%22%23right-well%22)%3B%0A%20%20%20%20%24(%22%23target5%22).clone().appendTo(%22%23left-well%22)%3B%0A%20%20%20%20%24(%22%23target1%22).parent().css(%22background-color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23right-well%22).children().css(%22color%22%2C%20%22green%22)%3B%0A%20%20%20%20%24(%22%23left-well%22).children().css(%22color%22%2C%20%22green%22)%3B%0A%20%20%20%20%24(%22.target%3Anth-child(2)%22).addClass(%22animated%20bounce%22)%3B%0A%20%20%20%20%24(%22.target%3Aeven%22).addClass(%22animated%20shake%22)%3B%0A%20%20%20%20%24(%22body%22).addClass(%22animated%20hinge%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) and [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements?solution=%3Cstyle%3E%0A%20%20%0A%20%20h2%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A)

**Comment by ltegman** [comment]
An example test would be something like `$("body").css("background-color") === "rgb(0, 0, 0)"`. The test will work correctly when logged from a script in the editor, but it will not work when run in the test suite.

**Comment by catfish68** [comment]
Has this been resolved?

**Comment by bugron** [comment]
@catfish68 do you have the same issue described in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4865?

**Comment by catfish68** [comment]
I have the same issue, I have refreshed, cleared my cache and evened used 3 different devices all with the same end results that I can not get passed this waypoint

**Comment by rajsoyantar** [comment]
same issue here in waypoint: inherit style from the body element
coded like:
<style>
  body {
    background-color: green;
    font-family: Monospace;
  }

</style>
<body >
<h1>Hello World</h1>
</body>
but run test fails, hard refreshed many time, but not working

**Comment by catfish68** [comment]
Try a different browser

**Comment by luyi1678** [comment]
I have same issue too

**Comment by jdjrwoot13** [comment]
Put it all on the same line of code just passed it :)

**Comment by HulkBear** [comment]
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green
      }

</style>

Had the same issue but I just completed as i placed the font before the color as that was the issue
