### ISSUE TITLE
The ability to change the splitter between editor and instruction is reverted in RTL

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48348]
While trying to move the `.reflex-splitter` to open more spacing for instruction, it reduces it instead.

Here is the splitter

![image](https://user-images.githubusercontent.com/88248797/198890653-84032eee-1066-49a7-8db8-01d6c66d1397.png)

Currently, I am checking https://github.com/leefsmp/Re-Flex, and https://leefsmp.github.io/Re-Flex/index.html#demo6 for a way around this

---

Edit:

Short answer: it currently isn't possible with it https://github.com/leefsmp/Re-Flex/issues/112, there is sandbox in the linked issue for people interested in what is going on https://codesandbox.io/s/pedantic-mahavira-jzdhw?file=/src/App.js

--- 

[Split.js](https://github.com/nathancahill/split) has the same issue

**Comment by Sboonny** [comment]
Okay, if I am creating from scratch, what is needed is

- Create a `div` between the pages, give it class `fCC-splitter`
- Add a value that control the layout width and height, `inset` property should do.
- Listen to the camper input on `fCC-splitter`
- Stop re-rendering of the component, this library should do the trick
- Find when to allow the re-rendering
- Style the `div` element, it should have different class because there will be vertical and horizontal splitter

**Comment by Sboonny** [comment]
this may take too long for functional refactor and may introduce bugs, is it okay to remove the splitters in the RTL layout? maybe adding buttons to collapse the editor, instruction, or console to provide needed spacing

**Comment by ojeytonwilliams** [comment]
It's an ugly hack, but could you make *only* the ReflexContainers LTR while having their containers and children be RLT?  While playing with the codesandbox, that seemed to do the trick.

**Comment by Sboonny** [comment]
one comment solved two issues 👍 🤣

**Comment by Sboonny** [comment]
reopenned, although this solve the issue. I have tried to finish the course with the text on the left, and it was hard because my attention isn't aligning with how the language meant to be preserved

**Comment by ojeytonwilliams** [comment]
@Sboonny this can probably be closed by a dedicated PR.  If you go with my suggestion, it is kind of a hack. So, it'll be easier to QA and eventually revert (if we come up with a non-hack) if it's confined to one PR.

**Comment by Sboonny** [comment]
I couldn't find a replacement after looking for a while, @ahmadabdolsaheb found https://www.npmjs.com/package/react-collapse-pane?activeTab=readme, but installing it isn't possible because we are using React 16. 

I will try to migrate to React 17, then try to install the package again

**Comment by Sboonny** [comment]
When RTL language is added to the /learn, we can re discuss this, for now I am closing it
