### ISSUE TITLE
Accessing camper profile page in development environment is hidden

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48359]
**Describe the issue**
While changing the RTL layout, I tried to access profile but was getting 404 page, luckily Naomi guided me and told me that it's a custom error page. This is abstract and hard to know for developers new to codebase, which may block people who may have the intention to help out.

**To Reproduce**
1. Run Gitpod environment
2. Open the menu in nav bar
3. Click Profile
4. See 404 error
5. Click Preview custom error

**Expected behavior**
To skip the 404 error and open the profile without issues

**Additional context**
If it isn't possible to make navigation to profile direct, should we add a new section in how to contribute?

**Comment by ShaunSHamilton** [comment]
Is this not clear enough?

https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=sign-in-with-a-local-user

**Comment by Sboonny** [comment]
Nope 😃, because the signing in is automatic, so when I sign in this section that talks about signing in becomes redundant, and I skipped it.

We can change it to something like `Accessing camper profile`.

**Comment by ojeytonwilliams** [comment]
'Viewing user profile' seems the most descriptive.

> Your local setup automatically populates a local user in the database. Clicking the Sign In button will automatically authenticate you into the local application.

-> 

> Click the Sign In button to sign in as the user you created in step 3.

and 

> However, accessing the user portfolio page is a little tricky. In development, Gatsby takes over serving the client-side pages and hence you will get a 404 page for the user portfolio when working locally.

-> 

> Navigate to http://localhost:8000/developmentuser to view the profile page. In development, you also have to click on "Preview custom 404 page" to see the profile.

The existing docs are a bit vague and explain a bit too much, imo.

**Comment by raisedadead** [comment]
> the section that talks about signing in becomes redundant, so I skipped it.

Skipping docs is a way to err like a human, which is the issue here. Feel free to update the docs.

Coming to updating the 404 page to show a relevant button — is easier said than done.

This is expected behavior - has been discussed before and is because Gatsby's dev-mode server hijacks the page, and you can't bypass it (while working locally). Period.

**Comment by ojeytonwilliams** [comment]
Yep. I don't think the docs need to go into that, though.  They're long enough already.

**Comment by raisedadead** [comment]
Maybe add - DO NOT SKIP DOCS. They are important !! With three exclamation marks will do? Jokes apart - I do not see how to update the verbiage in the section. In my personal opinion, it is good enough.

**Comment by Sboonny** [comment]
this is my 4th time reading docs, it can't be expected for someone who searching for "how to change the sub-forum" and "how to access the profile page", to look for them in section that talks about setting freecodecamp locally while working in Gitpod

**Comment by raisedadead** [comment]
> Skimming should be expected.

I disagree as a maintainer. The docs are there for a reason. We can't handhold every use case. 

That said, I have tagged this help wanted for a reason. If you have a recommended approach to how it could have saved you a pitfall. You are welcome to update the docs.

**Comment by Sboonny** [comment]
And to be honest, I think a better option is to break this into two sections. one that talks of what expected of a language lead who may not have knowledge of our code base, and other for developers who know the code base and may stumble into weird scenarios like the profile page, and gastby cashing

**Comment by ojeytonwilliams** [comment]
> In my personal opinion, it is good enough.

I think it can be improved with the above changes.  Also the gif is ancient so probably should just be removed.

**Comment by raisedadead** [comment]
> I think it can be improved with the above changes.

Did you mean this verbiage can be improved? I do not see a simpler explanation.

```
However, accessing the user portfolio page is a little tricky. In development, Gatsby takes over serving the client-side pages and hence you will get a 404 page for the user portfolio when working locally.

Simply clicking the "Preview Custom 404 Page" button will forward you to the correct page.
```

In case you wandered into the conversation, Muhammed and I are talking about different areas of the docs. 

The doc that was skipped was what I have pointed to. Of course, it is in a different location than a translator would expect, which can be improved.
