### ISSUE TITLE
Possibe error in code example

### ISSUE THREAD

**Issue by SethBashamDev** [freeCodeCamp/freeCodeCamp#48387]
### Describe the Issue

The example shows "const thirdLetter = alpha[2]". Below that, the snippet of text says that alpha[2] should be "Y".
"thirdLetter is the string Y, lastLetter is the string C, and valueLookup is the string Y."

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/using-objects-for-lookups

```js

const alpha = {
  1:"Z",
  2:"Y",				//<--------------- thirdLetter ??
  3:"X",
  4:"W",
  ...
  24:"C",				//<--------------- lastLetter ??
  25:"B",
  26:"A"
};

const thirdLetter = alpha[2];
const lastLetter = alpha[24];

const value = 2;
const valueLookup = alpha[value];

```

The snippet has the below explanation in the instructions:

```markdown

`thirdLetter` is the string `Y`, lastLetter is the string `C`, and `valueLookup` is the string `Y`.
```

### Expected behavior

I believe correcting the const "thirdLetter" to "secondLetter" could be less confusing.

**Comment by zhangleihong** [comment]
hello

**Comment by jeremylt** [comment]
I think part of what is weird is the indexing starting at 1. How about this:

```javascript
const alpha = {
  0:"Z",
  1:"Y",
  2:"X",
  3:"W",
  ...
  23:"C",
  24:"B",
  25:"A"
};

const thirdLetter = alpha[2];
const lastLetter = alpha[25];

const value = 2;
const valueLookup = alpha[value];
```

> `thirdLetter` is the string `X`, lastLetter is the string `A`, and `valueLookup` is the string `X`.

**Comment by nayabatir1** [comment]
I don't think it matters what property name we choose for object `alphabet` and from where it begins.

What confusing for me is as `2` is 2nd object property.
`const thirdLetter = alpha[2];` should be `const secondLetter = alpha[2];`
same for 
`const lastLetter = alpha[24];` should be `const lastLetter = alpha[26];`

Below text should be re-written
~`thirdLetter` is the string `Y`, `lastLetter` is the string `C`~  `secondLetter` is the string `Y`, `lastLetter`is the string `A`

If you think this is the right approach I'll start working on it.

**Comment by jeremylt** [comment]
Don't forget about zero based inhexing. I see no reason to switch indexing here.

**Comment by nayabatir1** [comment]
> Don't forget about zero based indexing. I see no reason to switch indexing here to one based.

`1`, `2` ... are object properties. So, it doesn't matter from where it begins or what name we choose. For Arrays indexing matters and it always begins from `0`

**Comment by jeremylt** [comment]
Yes, I understand how objects work. I don't see a reason to start counting at 1 here when in general JS starts counting at 0.

**Comment by nayabatir1** [comment]
Do we need to wait for other members suggestion ?

**Comment by jeremylt** [comment]
Yes, we need to wait. The issue isn't ready for contributions when discussion is ongoing.

**Comment by Sboonny** [comment]
I hate the idea of `number` as key because I had issue with octal numbers. Jeremy's example is good, but can we use something like.


```ts
const capitalAlphabet = {
  "z": "Z",
  "y": "Y",
  "x": "X",
  "w": "W",
  ...
  "c": "C",
  "b": "B",
  "a": "A"
};

const capitalA = capitalAlphabet[a];
const capitalB = capitalAlphabet[b];

const value = "z";
const valueLookup = capitalAlphabet[value];
```

But this maybe giving the answer away 🤔

**Comment by jeremylt** [comment]
Yeah, the numerical index is odd. 

Does it have to be an alphabet? Is there a better, simpler example?

**Comment by SethBashamDev** [comment]
Hello. I just read through everyone's comment. 

I understand numbering in main languages starts at 0. However, for this example, the numbering starts at 1, but the const names don't match. 

If the general consensus, is to keep the formatting how is currently is. We can close. 

I was looking at it from someone learning, thirdLetter but showing the second letter was a little off.

**Comment by jeremylt** [comment]
The variable name in current example is plain wrong. Nobody said that was not the case. 

We are talking about how best to fix this example. Personally, I'm thinking it should be replaced with a simpler object.

**Comment by Sboonny** [comment]
> Yeah, the numerical index is odd.
> 
> Does it have to be an alphabet? Is there a better, simpler example?

I can't think of a better example to be honest, but we can use a practical one. Like how the freeCodeCamp codebase Json files structured.

```ts
const article = {
  "title": "How to create objects in JavaScript",
  "link": "https://www.freecodecamp.org/news/a-complete-guide-to-creating-objects-in-javascript-b0e2450655e8/",
  "author": "Kaashan Hussain",
  "language": "JavaScripts",
  "tags": "TECHNOLOGY",
  "createdAt": "NOVEMBER 28, 2018"
};

const articleAuthor = article[author];
const articleLink = article[link];

const value = "title";
const valueLookup = article[value];
```

**Comment by jeremylt** [comment]
I like that example better. I think we should use it + the corresponding text fixes that would be needed.

**Comment by Sboonny** [comment]
I am opening this for contribution 👍. What is required is the following:

- Change the example to what's mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/48387#issuecomment-1304761517
- Change the text after the example

> `thirdLetter` is the string `Y`, `lastLetter` is the string `C`, and `valueLookup` is the string `Y`.

To 

> `articleAuthor` is the string `Kaashan Hussain`, `articleLink` is the string `https://www.freecodecamp.org/news/a-complete-guide-to-creating-objects-in-javascript-b0e2450655e8/`, and `valueLookup` is the string `How to create objects in JavaScript`.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
