### ISSUE TITLE
What to do with spam PR workflow

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48383]
I think raisedadead added this workflow, because of hacktobefest, which ended.

Here is the workflow

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/github-spam.yml

Should we disable it? or we have another plan for it, like updating the text to push invalid PR canned reply, we do have invalid label

**Comment by naomi-lgbt** [comment]
The workflow is disabled and can honestly just sit there until next year.
