### ISSUE TITLE
Expand superblock title logic when we make certificates legacy

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#48392]
It's not used, but I left it in. What I had planned was to remove the cert projects from the legacy RWD and rename the button to say "Legacy RWD Challenges" instead of "Legacy RWD Certification". But I couldn't remove the cert projects since many of the i18n's are using the legacy RWD as their first superblock. So I think this will get used at some point. With that, do you still think we should remove this? I don't mind.

_Originally posted by @moT01 in https://github.com/freeCodeCamp/freeCodeCamp/pull/47596#discussion_r1014062637_

**Comment by ojeytonwilliams** [comment]
I'm not 100% sure an issue is the best place to track this, but Tom and I were talking about this and I didn't want it to get lost.

**Comment by moT01** [comment]
This looks completed. All i18n's use RWD as the first superblock, and the cert projects were removed from legacy RWD 👍
