### ISSUE TITLE
Early challenges are not tested

### ISSUE THREAD

**Issue by Feanor96** [freeCodeCamp/freeCodeCamp#48408]
### The Issue-
**When we do the challenges in the** _Backend Development and APIs_ **course, our early challenges are not being tested, for example when I did the fourth challenge, even if I remove the code from challenge 1 that I wrote, we can still proceed to the next challenge**

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/managing-packages-with-npm/add-a-license-to-your-package-json

### Steps to Reproduce

1. Go to the replit code
2. Remove the code from challenge 1, 2 and 3
3. Click on Run
4. Paste the link on the solution input box
5. See that you can still proceed

### Expected behavior

**We should not be able to proceed unless all the code from the past challenges is present**

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context
**I do not know how to fix this issue, someone else should fix this**
_No response_

**Comment by jeremylt** [comment]
Do we care if people delete or modify code unrelated to the step?

**Comment by naomi-lgbt** [comment]
> Do we care if people delete or modify code unrelated to the step? If so, why?

IMHO, no. In fact we even have some steps that ask campers to delete previous code.

**Comment by ShaunSHamilton** [comment]
I do not see anything to fix here.

Whilst many courses/projects rely on most lessons following a golden path, the lesson tests are atomic with the expectation:
> Campers should not expect to pass tests in further lessons, if they do things outside of what has been asked

Without completely limiting the environment Campers can edit/work in, it is unreasonable to test every aspect of what they do outside of the scope of a single lesson.

**Comment by Feanor96** [comment]
> Do we care if people delete or modify code unrelated to the step? If so, why?

Actually yeah I guess this does not need fixing...anyways thanks!
