### ISSUE TITLE
JavaScipt

### ISSUE THREAD

**Issue by ronnie0492** [FreeCodeCamp/FreeCodeCamp#4844]
I m not able to execute the first task of javascript it has just mentioned to insert the comments but it is showing undefined so pls look into the matter asap.
THANK you.
http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code

**Comment by AlyxMoon** [comment]
This was happening for me as well, and I was checking from the Intermediate bonfires going back. They all appear to be giving an error of:
<code>TypeError: Object.assign is not a function</code>

**Comment by ComputerRepairLasVegas-DJ** [comment]
ok.  there is an error in the page where it checks for the multi line comment.  I have just completed the challenge using

// commet 1
/*/ comment 3 /*/

**Comment by bugron** [comment]
@ronnie0492 thanks for posting!
Closing this issue. I believe this will be fixed in #4853.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
