### ISSUE TITLE
Seems like there's a bug

### ISSUE THREAD

**Issue by gijscor** [FreeCodeCamp/FreeCodeCamp#4845]
Challenge [Waypoint: Find Numbers with Regular Expressions](http://www.freecodecamp.com/challenges/waypoint-find-numbers-with-regular-expressions?solution=var%20test%20%3D%20(function()%20%7B%0A%0A%20%20var%20testString%20%3D%20%22There%20are%203%20cats%20but%204%20dogs.%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20var%20expression%20%3D%20%2F%5Cd%2B%2Fg%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%20%20return%20testString.match(expression).length%3B%0A%0A%7D)()%3B(function()%7Breturn%20test%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var test = (function() {

  var testString = "There are 3 cats but 4 dogs.";

  // Only change code below this line.

  var expression = /\d+/g;

  // Only change code above this line.

  return testString.match(expression).length;

})();(function(){return test;})();

```

So my Error is:

<img width="288" alt="screen shot 2015-12-01 at 08 04 05" src="https://cloud.githubusercontent.com/assets/15912395/11494367/1e87732e-9802-11e5-9840-28822c2965f9.png">

I've seen people give exactly the same answer, and proceeding to next level, so all i can think of that there is a bug..

**Comment by bugron** [comment]
@gijscor thanks for posting!
Closing this issue. Let's keep the discussion in #4853, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
