### ISSUE TITLE
Your test might be wrong...

### ISSUE THREAD

**Issue by pnoiboi77** [FreeCodeCamp/FreeCodeCamp#4847]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20cleaned%20%3D%20str.match(%2F%5Ba-zA-Z%5D%2B%2Fg).join(%27%27).toLowerCase()%3B%0A%20%20%0A%20%20return%20cleaned%20%3D%3D%20cleaned.split(%27%27).reverse().join(%27%27)%3B%0A%7D%0A%0A%0A%0Apalindrome(%222%20eye%20for%20of%201%20eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var cleaned = str.match(/[a-zA-Z]+/g).join('').toLowerCase();
  
  return cleaned == cleaned.split('').reverse().join('');
}



palindrome("1 eye for of 1 eye.");

```

Your test states this should return false. I could be wrong but removing all non alpha characters and passing this within my palindrome function returns true.

**Comment by ltegman** [comment]
The reverse of that string is `eye1forofeye1` which is not the same as `1eyeforof1eye`, so this is not a palindrome. You should be keeping numeric characters in addition to alphabetic ones.

Thanks and happy coding!

**Comment by pnoiboi77** [comment]
Ahhh alphanumeric :). My bad.
