### ISSUE TITLE
Users can create a Random Quote Machine that passes all tests but the New Quote button does not get a new Quote

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#48476]
### Describe the Issue

Users can create a Random Quote Machine that passes all tests but the New Quote button does not get a new quote.  See the discussion that contains the project in question and the issue.

https://forum.freecodecamp.org/t/need-help-with-random-quote-machine/569884

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-random-quote-machine

### Your code

The following is a fork of a user's project that passes all the tests but the New Quote button does not do anything.
https://codepen.io/rmdawson/pen/ZERLWrY

### Expected behavior

The New Quote button should change to a new quote at some point.  The test was changed a while back to allow no new quotes to be displayed.  What is the point of a random quote machine project if the tests can not validate it is a random quote generator?

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by KravMaguy** [comment]
the campers example is not setting the state on click. 

In the code of the test they are using this.timeout incorrectly. also the function in the assert does not execute. as well pass done as parameter to the function in the it block and call it on resolve of the promise. Ive taken the current code and modified it to provide a starting example of how one could write such a test :

`
  describe('New Quote gets a new Quote', function () {
      const requestTimeout = 5000;
      // however much time you think it might take the network if making a call over the 
      //wire to get the quote
      this.timeout(requestTimeout);
      it(`When the #new-quote button is clicked, my quote machine
      should fetch a new quote and display it in the #text element.`, function (done) {
        let prevText;
        const newQuoteBtn = document.getElementById('new-quote');

        const text = document.getElementById('text');
        assert.isNotNull(text, '#text is not defined ');

        prevText = document.getElementById('text').innerText;
        newQuoteBtn.click();

        assert.isAbove(
          prevText.length,
          0,
          'element with id="text" should contain a random quote'
        );

        if (prevText) {
          assert(
            (() => {
              console.log('i got here');
              return new Promise((resolve) => {
                const intervalId = setInterval(() => {
                  const newText = document.getElementById('text').innerText;
                  if (newText !== prevText) {
                    clearInterval(intervalId);
                    resolve(done());
                  } else {
                    console.log('asdfasdfsadf here');
                    newQuoteBtn.click();
                  }
                }, 500);
              });
            })()
          );
        }
      });
    });

`

**Comment by Sboonny** [comment]
I may be misremembering, but that timeout is added for React 18 bug. If the function is altered, we have to account for campers trying to pass the project using React 18.

**Comment by RandellDawson** [comment]
It should not matter if a user writes vanilla JS, uses React 15, 16, 17, 18, Vue, AngularJs, etc., the tests should correctly validate the New Quote button does result in a new random quote (at some point).  If a user only has 2 quotes in an array of quotes, it may take several attempts before realizing there are more than one.  In my opinion, the project user stories should reflect the need to make sure the app never produces the same quote twice in a row.  Then, the test is much simpler and only has to click the button one time.

**Comment by KravMaguy** [comment]
> One fix for this mess is changing the project user stories to reflect the need to make sure the app never produces the same quote twice in a row. Then, the test is much simpler and only has to click the button one time.

For the sake of argument legacy code might fail. Additionally there is nothing in this file which guarantees that a new quote will be generated. 

![image](https://user-images.githubusercontent.com/37171082/201491588-0115ed3d-3d30-4199-bba0-f505733024e8.png)

We will have to modify this randomQuote function to guarantee such a test passes every time. Not difficult to do but..

> New Quote button does result in a new random quote (**_at some point_**).

That is what the current tests are (attempting) to do, clicking the button multiple times in the hope that it will change, small probablility that it wont _at some point_ given a big enough timeout and a large enough quotesArray. 

> make sure the app never produces the same quote twice in a row

Unless we can see the users code, how can we guarantee that it will **always** result in a _new_ quote? Unless I misunderstood, you will still have to click it mulitple times, and you change the approach from:

a) Click multiple times and just verify that it changes at least once (tests can finish earlier)
b) Click multiple times and make sure it passes every time (test will take longer)

End even still theres no guarantee.

**Comment by KravMaguy** [comment]
please correct me if what I said is wrong, basically, we dont have a way to write a test that guarantees the app will produce a new quote every time.

I believe we can do one of two approaches:
1) keep instructions as they are, if it changes finish early with pass, if it never changes than its fails on timeout (what the current test is trying to do)
2) rewrite the requirements, if it times out it passes, if it doesnt change fail early

>I may be misremembering, but that timeout is added for React 18 bug. If the function is altered, we have to account for campers trying to pass the project using React 18.

Ill write a new test. Ill make sure it works whether the user is using the new version of react or an older version. The way the code currently is, I dont think this is accomplishing anything, for the reasons I mentioned In my earlier reply...

`      if (prevText) {
          assert(() => {
            return new Promise((resolve) => {
              const intervalId = setInterval(() => {
                const newText = document.getElementById('text').innerText;
                if (newText !== prevText) {
                  clearInterval(intervalId);
                  resolve();
                } else {
                  console.log('got here');
                  newQuoteBtn.click();
                }
              }, 1000);
            });
          });
        }
`

**Comment by RandellDawson** [comment]
[Here is another example](https://forum.freecodecamp.org/t/random-quote-machine-tests-bug/578578) of a project that does not even have any JavaScript and passes all the tests.  Are there any staff that can work on this?

**Comment by ShaunSHamilton** [comment]
**Double-checking**: How ok are we with potentially invalidating Camper's submitted projects? In this case, it seems like fixing this issue would just enforce the user story.

---

To resolve this, there are 4 tests using the `assert(() => ...)` pattern, which seems like the issue (also is not nice to read). So, let us alter these asserts - **NO IIFEs**. [testable-projects-fcc]() uses `mocha>=9.0.0`, so we are free to [declare tests as `async`](https://mochajs.org/#using-async-await). In which case:

```js
try {
  const textIsGreaterThanZero = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(), 1000);
    const intervalId = setInterval(() => {
      if (text.innerText.length > 0) {
        console.log('Clearing interval ' + intervalId);
        clearInterval(intervalId);
        clearTimeout(timeout);
        resolve();
      }
    }, 500);
  });
} catch (e) {
  assert.fail("unable to find text in time");
}
```

**Comment by RandellDawson** [comment]
Will this resolve the validating there is a different quote after clicking the button?

**Comment by ShaunSHamilton** [comment]
> Will this resolve the validating there is a different quote than the one which displays when the app loads after clicking the button?

No, the above is just an example based of of the first test that needs to be changed. 4 should be changed.

**Comment by Sboonny** [comment]
There have been three weeks and there seems to be no issue with Shaun suggestion, as far as I can tell. I am opening this for contribution.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by RandellDawson** [comment]
> There have been three weeks and there seems to be no issue with Shaun suggestion, as far as I can tell. I am opening this for contribution.

There has been no suggestion agreed upon that will fix the issue I described, so what is the point?

**Comment by Sboonny** [comment]
Reading the last 3 comments, the context that I understood is:

- Shaun provided an example and where the issue lies
- You asked him if it solves it.
- He mentioned, nope, there are more with similar issue that can be solved.

---

I can bring the issue up in Wednesday meeting, if the previous comments don't solve the issue.

**Comment by ojeytonwilliams** [comment]
While we don't know how to fix it, I think we agree that the problems need fixing.  With that in mind, I'll set this as help wanted for now.

If it proves to be a difficult fix, we can rework the project when we update the Front End Development Libraries Certification. For anyone interested, https://github.com/freeCodeCamp/testable-projects-fcc/blob/main/src/projects/random-quote-machine/index.js the place to look.
