### ISSUE TITLE
Merge some lessons.

### ISSUE THREAD

**Issue by adsingh14** [freeCodeCamp/freeCodeCamp#48485]
### Describe the Issue

I was testing these lessons where some steps are time-consuming. I'm sharing one example below.

- Open this link: [CSS Cafe lessons](https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-basic-css-by-building-a-cafe-menu)
- Open Step 42, Step 43 and a few of the following 3 or 4 lessons.
- Step 43,44,45 is time-consuming step, should've merge in step 42

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-basic-css-by-building-a-cafe-menu

### Your code

```
-- Same as 'Describe the Issue' --
```

### Expected behavior

-- Same as 'Describe the Issue' --

### System

- Device: Laptop [e.g. iPhone 6, Laptop]
- OS: Windows 10 [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: Chrome[e.g. Chrome, Safari]
- Version: 106 (or latest)[e.g. 22]

**Comment by jeremylt** [comment]
I'm not sure we want to collapse that into a really big step. That  would run counter to the course design.

**Comment by naomi-lgbt** [comment]
I'm in agreement with Jeremy here. Steps are intentionally granular, to keep campers in a flow state.
