### ISSUE TITLE
Typo on personal library project in quality assuarance

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48498]
There is an extra quote in the string below

> You can send a <b>DELETE</b> request to `/api/books` to delete all books in the database. The returned response will be the string `'complete delete successful` if successful.

it can be removed as it isn't required 

> You can send a <b>DELETE</b> request to `/api/books` to delete all books in the database. The returned response will be the string `complete delete successful` if successful.

Here is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/15c19a44a7763755ccaaad228c1a325cac9914b6/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/personal-library.md#L174?plain=1

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by theritikchoure** [comment]
Can I work on this issue?

**Comment by Sboonny** [comment]
Yea, feel free to open PR, after you have read our contribution guideline

**Comment by RUCHI21CODES** [comment]
@Sboonny I have created the pull request, please review it.

**Comment by SumitP549** [comment]
Can i also contribute to this issue?

**Comment by Sboonny** [comment]
Yes, there is no pull request that follows the contribution guideline. If you open PR that follows it, that pr will be merged and closes the issue with it

**Comment by SumitP549** [comment]
Thank you @Sboonny
