### ISSUE TITLE
When using HEX value for color, it accepts it but can't recognise that the brace is correctly closed

### ISSUE THREAD

**Issue by Puukallistaja** [FreeCodeCamp/FreeCodeCamp#4850]
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements?solution=%3Cstyle%3E%0A%20%20h2%20%7B%0A%20%20%20%20color%3A%20%230000FF%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {
    color: #0000FF;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by bugron** [comment]
@Puukallistaja thanks for pointing this out, confirmed!
Looks like test search for the word `blue` ([see this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/html5-and-css.json#L395)) but actually one can specify `#0000FF` or even `rgb(0, 0, 255)`. The result will be as expected but this test won't pass. We can replace `blue` with `.*` (which means any character). 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
