### ISSUE TITLE
Wrong filter description 

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#48523]
### Describe the Issue

This page incorrectly says that filter keeps elements when the callback returns the Boolean value true. This is incorrect, any element that results in a truthy return value is retained.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array

### Expected behavior

The line:

> `filter` calls a function on each element of an array and returns a new array containing only the elements for which that function returns `true`.

Should be replaced with the line:

> `filter` calls a function on each element of an array and returns a new array containing only the elements for which that function returns a truthy value - that is, a value which returns `true` if passed to the `Boolean()` constructor.

### System

All

### Additional context

The file to edit: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array.md

**Comment by lasjorg** [comment]
Not really sure I understand. This is what the challenge says.

> filter calls a function on each element of an array and returns a new array containing only the elements for which that function returns `true`.

Here are the specs
> [23.1.3.8 Array.prototype.filter](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.filter)
> 
> callbackfn should be a function that accepts three arguments and **_returns a value that is coercible to a Boolean value_**. filter calls callbackfn once for each element in the array, in ascending order, and **_constructs a new array of all the values for which callbackfn returns true_**. callbackfn is called only for elements of the array which actually exist; it is not called for missing elements of the array.

...

> ii. Let selected be [ToBoolean](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-toboolean)(? [Call](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-call)(callbackfn, thisArg, « kValue, [𝔽](https://tc39.es/ecma262/multipage/notational-conventions.html#%F0%9D%94%BD)(k), O »)).

A truthy value is any value that when coerced or converted becomes the Boolean value `true`.

> Truthy
> In [JavaScript](https://developer.mozilla.org/en-US/docs/Glossary/JavaScript), a truthy value is a value that is considered true when encountered in a [Boolean](https://developer.mozilla.org/en-US/docs/Glossary/Boolean) context. All values are truthy unless they are defined as [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy). That is, all values are truthy except false, 0, -0, 0n, "", null, undefined, and NaN.

**Comment by lasjorg** [comment]
I mean I guess we can mention coercion and truthy values but we do not do so implicitly either in other places.

> [If Statements](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-conditional-logic-with-if-statements)
> 
> `if` statements are used to make decisions in code. The keyword if tells JavaScript to execute the code in the curly braces under certain conditions, defined in the parentheses. These conditions are known as `Boolean` conditions and they may only be `true` or `false`.

The closest we get is the use of the word "evaluates" which implies coercion can happen. But it certainly does not tell a beginner as much.

> When the condition evaluates to `true`

**Comment by jeremylt** [comment]
"`true`" is not the same thing as `coercible to the Boolean value `true`'.

This part of the spec is poorly worded:

> constructs a new array of all the values for which callbackfn returns 'true'

The return value is coerced, so a boolean literal `true` does not need to be returned.

It should say

> constructs a new array of all the values for which callbackfn returns a value that is coerced to 'true'

That would be consistent with the previous sentence of the spec:

> returns a value that is coercible to a Boolean value

MDN's description is more accurate:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#parameters

> `callbackFn`: A function to execute for each element in the array. It should return a [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) to keep the element in the resulting array, and a falsy value otherwise.

---

I think that we should say something like

> filter calls a function on each element of an array and returns a new array containing only the elements for which that function returns a truthy value.

---

Right now we are saying the return value must **be** `true`, not that it must be **equivalent to** `true`

**Comment by jeremylt** [comment]
Fasly/Truthy discussed here:

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/falsy-bouncer

The Basic Algorithms section is before the Functional Programming section, so I think it is fair to use the concept.

**Comment by lasjorg** [comment]
I don't think the specs are poorly worded.

There is no difference between the literal primitive value `true` or `!!'true'` or `Boolean('true')`

**Comment by jeremylt** [comment]
So your read of the spec is that a `filter` function will only retain a value in the array if the callaback returns the Boolean literal `true`?

**Comment by lasjorg** [comment]
I mean that is the implementation. It doesn't matter if `true` is directly passed or a value that when passed into `ToBoolean` comes back as `true`

1. Let O be ? [ToObject](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-toobject)(this value).
2. Let len be ? [LengthOfArrayLike](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-lengthofarraylike)(O).
3. If [IsCallable](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-iscallable)(callbackfn) is false, throw a TypeError exception.
4. Let A be ? [ArraySpeciesCreate](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-arrayspeciescreate)(O, 0).
5. Let k be 0.
6. Let to be 0.
7. Repeat, while k < len,
a. Let Pk be ! [ToString](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tostring)([𝔽](https://tc39.es/ecma262/multipage/notational-conventions.html#%F0%9D%94%BD)(k)).
b. Let kPresent be ? [HasProperty](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-hasproperty)(O, Pk).
c. If kPresent is true, then
i. Let kValue be ? [Get](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-get-o-p)(O, Pk).
ii. Let selected be [ToBoolean](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-toboolean)(? [Call](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-call)(callbackfn, thisArg, « kValue, [𝔽](https://tc39.es/ecma262/multipage/notational-conventions.html#%F0%9D%94%BD)(k), O »)).
iii. If selected is true, then
1. Perform ? [CreateDataPropertyOrThrow](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-createdatapropertyorthrow)(A, ! [ToString](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tostring)([𝔽](https://tc39.es/ecma262/multipage/notational-conventions.html#%F0%9D%94%BD)(to)), kValue).
2. Set to to to + 1.
d. Set k to k + 1.
8. Return A.

---

7.1.2 ToBoolean ( argument )
The abstract operation ToBoolean takes argument argument (an [ECMAScript language value](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-language-types)) and returns a Boolean. It converts argument to a value of type Boolean. It performs the following steps when called:

1. If argument [is a Boolean](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-language-types-boolean-type), return argument.
2. If argument is any of undefined, null, +0𝔽, -0𝔽, NaN, 0ℤ, or the empty String, return false.
3. NOTE: This step is replaced in section [B.3.6.1](https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#sec-IsHTMLDDA-internal-slot-to-boolean).
4. Return true.

**Comment by jeremylt** [comment]
> It doesn't matter if true is directly passed or a value that when passed into ToBoolean comes back as true

That's my understanding too... so why are we saying that `true` must be returned?

**Comment by lasjorg** [comment]
> That's my understanding too... so why are we saying that `true` must be returned?

It doesn't matter if it is done explicit or implicitly through coercion/convertion. It will be `true` or `false` and only if it is `true` will the element be added to the new array that is returned.

**Comment by jeremylt** [comment]
Right, that has consistently been my understanding of how `.filter` works. How about our challenge text says that clearly?

One concise way that we can say that is by saying

> `filter` calls a function on each element of an array and returns a new array containing only the elements for which that function returns a truthy value.

**Comment by lasjorg** [comment]
I don't think we would be wrong in making sure the camper understands that the value is converted to a Boolean value. But I don't think simpely throwing the word truthy at them is going to explain that.

**Comment by jeremylt** [comment]
Sure, maybe they forgot the falsy/truthy lesson. I don't care about the exact wording used to fix this.

I would be happy with anything in the challenge that points out that "the return value of the callback function is coerced into a Boolean literal and only the elements that generate return values that coerce to the Boolean literal `true` are inserted into the new array". Currently we don't say that. 

We say

> `filter` calls a function on each element of an array and returns a new array containing only the elements for which that function returns `true`.

We could say

 >   `filter` calls a function on each element of an array and returns a new array containing only the elements for which that function returns a value equivalent to `true`.

We could say something else too. It's not a big deal to me so long as it is clear to learners that their callback doesn't need to actually return `true`. That's not the case with the current wording.

**Comment by naomi-lgbt** [comment]
> `filter` calls a function on each element of an array and returns a new array containing only the elements for which the callback function evaluates to `true`.

How's this?

Also, looking at our curriculum, Falsy Bouncer has campers remove falsy values, but doesn't *really* teach what a truthy/falsy value is (or how coercion works). Maybe we should go in to that a bit more?

**Comment by jeremylt** [comment]
Is "evaluates to `true`" a JavaScript term of the art? I don't use it, but I also don't have weak and strong comparisons in most languages I use.

> `filter` calls a function on each element of an array and returns a new array containing only the elements for which the callback function is equivalent to `true`.

---

> Also, looking at our curriculum, Falsy Bouncer has campers remove falsy values, but doesn't really teach what a truthy/falsy value is (or how coercion works). Maybe we should go in to that a bit more?

Yeah, I agree that this lesson could be clearer. I've seen so many strange hacks to get around the point - using implicit coercision/truthiness.

**Comment by lasjorg** [comment]
> It's not a big deal to me so long as it is clear to learners that their callback doesn't need to actually return `true`.

But it _does_ have to return `true`. It doesn't matter that it happens through a Boolean conversion, or through an expression `item > 10`, or whatever else might result in a boolean value. The end result is that the callback either returns `true` or `false` and that is literally the value that is used by filter to keep or not keep an element.

**Comment by jeremylt** [comment]
But what about this example

```javascript
console.log([1, 2, 4, 8, 16, 17].filter(e => e % 2)
```

The return value is never `true`.

**Comment by lasjorg** [comment]
Except this is what actually happens:

```
console.log([1, 2, 4, 8, 16, 17].filter(e => Boolean(e % 2)))
```

> evaluates to `true`.

Is pretty "inside baseball" in my opinion.

**Comment by naomi-lgbt** [comment]
I think we may be splitting hairs on this.

> filter calls a function on each element of an array and returns a new array containing only the elements for which that function returns a truthy value - that is, a value which returns `true` when passed to the `Boolean()` constructor.

**Comment by jeremylt** [comment]
The coercion happens *internal* to the filter, after the callback function returns.

---

> `filter` calls a function on each element of an array and returns a new array containing only the elements for which that function returns `true`.

```javascript
Array.prototype.myFilter = function(callback) {
  const newArray = [];
  for (let i = 0; i < this.length; i++) {
    if (callback(this[i]) === true) newArray.push(this[i]);
  }
  return newArray;
};
```

---

> `filter` calls a function on each element of an array and returns a new array containing only the elements for which that function returns a value equivalent to `true`.

```javascript
Array.prototype.myFilter = function(callback) {
  const newArray = [];
  for (let i = 0; i < this.length; i++) {
    if (callback(this[i])) newArray.push(this[i]);
  }
  return newArray;
};
```

---

The `myFilter` exercise is exactly why I care about this.

**Comment by lasjorg** [comment]
@naomi-lgbt I think that might work.

Not sure if it should be worded more as a hypothetical so the context is more general?

> that is, any value that returns `true` if passed to the `Boolean()` constructor.

Not sure if it makes much of a difference, really.

**Comment by naomi-lgbt** [comment]
Yep that should be fine.

I'll go ahead and open this up to contribution, then.

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
