### ISSUE TITLE
Relational Database: able to pass step 895.1 of Build a Mario Database without setting primary key

### ISSUE THREAD

**Issue by KravMaguy** [freeCodeCamp/freeCodeCamp#48521]
### Describe the Issue

I passed step with "content": "Set your new column as the primary key for this table.", without setting any primary key. I had wanted to see the table, I simply displayed it and the challenge passed. 

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

```
mario_database=> \d more_info
```

### Expected behavior

challenge should not pass on display of tables but only pass on setting the primary key per instructions. as you can see primary key was never set on this table:

![image](https://user-images.githubusercontent.com/37171082/202029956-93378412-cdc5-4702-869c-f27b13d7b6b8.png)

### Screenshots

![challenge_pass](https://user-images.githubusercontent.com/37171082/202029548-72b436c6-e189-493e-b20c-78dfb272250a.jpg)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
[Learn Relational Databases by Building a Mario Database](https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database) tutorial.

## Affected page

https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/v1.0.4/.freeCodeCamp/test/895.test.js

Test is checking table and column from one of the previous steps. It should check `more_info` and `more_info_id` respectively.

## Additional context

This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Making PR for this issue will require following parts referring to making changes on the version branch.


Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
