### ISSUE TITLE
CSS property clip is deprecated, but used in (New) Responsive Web Design accessibility lesson

### ISSUE THREAD

**Issue by NicksPatties** [freeCodeCamp/freeCodeCamp#48535]
### Describe the Issue

The CSS property `clip` is used to visually hide an element while leaving it visible for screen readers in the accessibility lessons. However, the property is [deprecated according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/clip). An alternative to this is available using the new `clip-path` CSS property like so: `clip-path: circle(0)`.

The lesson and the tests verifying its correctness use the deprecated `clip` property, and should be replaced.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-25

### Your code

```css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
  white-space: nowrap;
  border: 0;
}
```

### Expected behavior

The test should fail and a hint provided to use something other than the `clip` property.

### Screenshots

![Screen Shot 2022-11-17 at 1 22 39 PM](https://user-images.githubusercontent.com/3261001/202554795-f8eca7e0-e68f-45b4-a410-1f0ab3c4ff18.png)

### System

- Device: Laptop
- OS: macOS 10.15.7
- Browser: Brave
- Version: 1.45.127

### Additional context

While researching this problem, I noticed this error persists throughout all subsequent steps for all languages in the lesson. I found 450 results in 440 files where this error occurred.
![Screen Shot 2022-11-17 at 1 29 21 PM](https://user-images.githubusercontent.com/3261001/202555088-b3a8450b-d1eb-40b8-b120-c48cb08cf355.png)

To that end, I can approach this in big or small pieces and I'm open to other suggestions. Either I can:
* Fix the problem on Step 25 of the lesson, which includes the check that the `clip-path` property is used, for English
* Fix the problem on Step 25 of the lesson, for all languages
* Replace all instances of `clip: rect(0, 0, 0, 0)` with `clip-path: circle(0)`, and the assertion fix in Step 25, for all languages and all following steps

**Comment by bbsmooth** [comment]
While we are at it, we might as well get rid of some of the other properties in the `sr-only` class that don't need to be there (such as `padding`, `margin`, and `border`). Based on the article I linked to above, the class should be:

```
.sr-only {
    clip-path: inset(50%);
    height: 1px;
    overflow: hidden;
    position: absolute;
    white-space: nowrap;
    width: 1px;
}
```

**Comment by NicksPatties** [comment]
Thanks for the article! I'll make a new branch and start tackling this today. First, I'll fix the styles and assertions in the mentioned step, then if appropriate in the same PR, I'll update the styles for the subsequent pages.

**Comment by ojeytonwilliams** [comment]
While we will want to update this in the future, at this time the browser support isn't [there](https://caniuse.com/?search=clip-path)
