### ISSUE TITLE
 Check the Length Property of a String Variable

### ISSUE THREAD

**Issue by ushankhan** [FreeCodeCamp/FreeCodeCamp#4854]
Challenge [Waypoint: Check the Length Property of a String Variable](http://www.freecodecamp.com/challenges/waypoint-check-the-length-property-of-a-string-variable?solution=var%20firstNameLength%20%3D%200%3B%0Avar%20lastNameLength%20%3D%208%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AlastName%3DlastName.lenght%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0Aif(typeof%20lastNameLength%20%3D%3D%3D%208)%7B(function()%7Breturn%20lastNameLength%3B%7D)()%3B%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var firstNameLength = 0;
var lastNameLength = 8;
var firstName = "Ada";

firstNameLength = firstName.length;

var lastName = "Lovelace";

// Only change code below this line.

lastName=lastName.lenght;


// Only change code above this line.

if(typeof lastNameLength === 8){(function(){return lastNameLength;})();}

```

**Comment by Dajust** [comment]
@ushankhan you have not written any solution to the problem. Meanwhile, are you having any issues? Please specify.

**Comment by bugron** [comment]
@ushankhan thanks for posting this issue!.
First of all you have a typo here: `lastName=lastName.lenght;`, `length` and not `lenght`. Also you've modified the line below the comment `// Only change code above this line.` (`if(typeof lastNameLength === 8)` should be `if(typeof lastNameLength !== "undefined")` but in this case this won't fail the test) and above  `// Only change code below this line.`  (`var lastNameLength = 8;` should be `var lastNameLength = 0;`). Reset your code, please.
The only thing we can discuss here is that neither in description nor in tests isn't any mention that `lastNameLength` should contain the length of the string variable `lastName`.
>Use the .length property to count the number of characters in the lastName variable.

Campers have to guess that `lastNameLength` needs to be equal to `lastName.length`, after this:
>lastNameLength should be equal to eight.

So I propose this change:
>Use the .length property to count the number of characters in the lastName variable and then place it in lastNameLength variable.

or something like that.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by SaintPeter** [comment]
I will cover this in #3881

I've already done a basic rewrite of this, I can easily add the requested verbiage.

**Comment by SaintPeter** [comment]
This what it would look like:
![image](https://cloud.githubusercontent.com/assets/553494/11508834/9dd1ddd8-980f-11e5-86a4-2772e5d33db4.png)

**Comment by bugron** [comment]
@SaintPeter awesome :+1:. Closing this issue then.

**Comment by ushankhan** [comment]
thank u
