### ISSUE TITLE
References to comment dictionary gives invalid link

### ISSUE THREAD

**Issue by bryanleemoore** [freeCodeCamp/freeCodeCamp#48557]
### Describe the Issue

1. Any reference to the comment dictionary on the [How to work on coding challenges](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges) section of the documentation gives an invalid link which sends users to https://contribute.freecodecamp.org/#/curriculum/dictionaries/english/comments.js
 ![image](https://user-images.githubusercontent.com/31421559/202961114-f42ecb02-7bc1-48f1-be6d-1f5e7537626d.png) 

      ![image](https://user-images.githubusercontent.com/31421559/202961332-097feb5d-5ea6-4144-93b8-88d706463daf.png)

3. Example which references the location of the non-English version of the Chinese comment dictionary has the wrong path. 
![image](https://user-images.githubusercontent.com/31421559/202961240-46db8855-756a-4192-b169-12a862035518.png)

### Affected Page

https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=formatting-seed-code

### Steps to Reproduce

1. Go to the [How to work on coding challenges](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges) portion of the documentation.
2. Scroll to [Formatting seed code](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=formatting-seed-code)
3. Click on either the **[comment dictionary](https://contribute.freecodecamp.org/#/curriculum/dictionaries/english/comments.js)** reference or the **[English version of the comment dictionary](https://contribute.freecodecamp.org/#/curriculum/dictionaries/english/comments.js)** reference in the documentation, which leads to an error page.

### Recommended fix or suggestions

According to pull request [#40844](https://github.com/freeCodeCamp/freeCodeCamp/pull/40844), comments.js is no longer being used, and instead comments.json replaces comments.js.

1. Replace links of /curriculum/dictionaries/english/comments.json in the file **how-to-work-on-coding-challenges.md** to https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/dictionaries/english/comments.json? 
2. Change all references of comments.js to comments.json?

**Comment by Sboonny** [comment]
The seed comments are translated in crowdin, do we even want to keep that section? or are these comment different from the ones in crowdin?

**Comment by naomi-lgbt** [comment]
The seed comments are translated in Crowdin *through* these dictionaries.

**Comment by Sboonny** [comment]
So I was misunderstanding the workflow 👍, opening this for review 👍
