### ISSUE TITLE
Solutions are deleted upon successful submission of challenges

### ISSUE THREAD

**Issue by b-van-b** [freeCodeCamp/freeCodeCamp#48555]
### Describe the Issue

Work-in-progress code for a challenge persists indefinitely, through signouts, closing and re-opening the browser, and rebooting the computer; however, as soon as the challenge is completed and "Submit and go to the next challenge" is clicked, the user's solution is deleted and replaced with the original boilerplate code presented at the beginning of the challenge.

This means that users cannot go back and review past code in order to see how they once solved a challenge, or to refactor it and create an improved solution.

The effect appears to be the same on any challenge.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown

### Steps to Reproduce

1. Go to the challenge page.
2. Enter an acceptable solution.
3. Leave and return to verify that the solution has been cached.
4. Click on "Run the tests" followed by "Submit and go to the next challenge"
5. Return to the challenge page and see that the solution has been erased, the same as if you had clicked on "Reset all code"

### Expected behavior

It is expected that the user's solution should persist after submission.

### System

- Device: Laptop PC
- OS: Windows 11
- Browser: Chrome
- Version: 107.0.5304.107 (Official Build) (64-bit)

**Comment by b-van-b** [comment]
I believe that this is the affected code, from [/client/src/templates/Challenges/redux/code-storage-epic.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/6e9cb35e3ea3e999f94ee328deaf6cee40be2092/client/src/templates/Challenges/redux/code-storage-epic.js#L74):
```javascript
function clearCodeEpic(action$, state$) {
  return action$.pipe(
    ofType(appTypes.submitComplete, actionTypes.resetChallenge),
    tap(() => {
      const { id } = challengeMetaSelector(state$.value);
      store.remove(id);
    }),
    ignoreElements()
  );
}
```

Am I correct?

**Comment by moT01** [comment]
This has come up quite a few times. Here's several issues with related discussions - some have links to other related issues:
-https://github.com/freeCodeCamp/freeCodeCamp/issues/17485
-https://github.com/freeCodeCamp/freeCodeCamp/issues/34479
-https://github.com/freeCodeCamp/freeCodeCamp/issues/36599
-https://github.com/freeCodeCamp/freeCodeCamp/issues/36626

I don't think this is something we are going to change.
