### ISSUE TITLE
Var in Challenge 

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#48554]
### Describe the Issue

Is there a reason we have var in this challenge code? 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/global-scope-and-functions

### Expected behavior

Var isn't used in most of your challenges. 

### System

All

**Comment by sivalaxman7** [comment]
we need to use let here instead of var right?

**Comment by jeremylt** [comment]
> Does this really need fixing?

Yes. We intentionally moved away from using `var` in our challenges.

**Comment by ShaunSHamilton** [comment]
Looking at the blame, it appears this is just one of the challenges we hardly ever change - it is old.

There appears to be no reason to not change it from `var` to `let`.

---


An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
