### ISSUE TITLE
Plugin Error, Constant Loading, Not excepting code

### ISSUE THREAD

**Issue by GhostParticle** [FreeCodeCamp/FreeCodeCamp#4856]
![waypoint1](https://cloud.githubusercontent.com/assets/10119077/11501980/c03523ba-97fd-11e5-8f9e-0d3bb05bdfc6.PNG)
![waypoint1a](https://cloud.githubusercontent.com/assets/10119077/11501982/c514ba26-97fd-11e5-9abd-e53a28be9e2e.PNG)

Challenge [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Page takes a long time to complete the load, when its loading it gives the plugin error. Once i type in the code and click run test the plugin error goes away but the waypoint wont except the code as being good code. 

My code:
```javascript
// This is a comment.
/* This is also a comment */
```

![waypoint1](https://cloud.githubusercontent.com/assets/10119077/11501988/d560e3dc-97fd-11e5-88a7-9c7d7fce4083.PNG)
![waypoint1a](https://cloud.githubusercontent.com/assets/10119077/11501987/d55babc4-97fd-11e5-8b55-f4cd5a62ccbf.PNG)

**Comment by PeanutPerri** [comment]
I'm getting that same issue right now.

**Comment by matty22** [comment]
From comments in the help chat early this morning, lots of people are having this issue. I've seen a dozen or so people in about 20 minutes ask about this error.

**Comment by bugron** [comment]
@GhostParticle thanks for posting. We're aware of this issue. Let's keep the discussion in #4853. Closing.
