### ISSUE TITLE
The tests are not being completed

### ISSUE THREAD

**Issue by Feanor96** [freeCodeCamp/freeCodeCamp#48562]
### Describe the Issue

**Issue Location-** _Backend and Api Course_, _Install and Set up mongoose_

**Issue-** The issue is that whenever I complete the instructions, the tests are still not completing. For example when the test was that Mongoose version _^5.11.15_ should be installed, it was already installed and now its saying that the test is not completed. I am using StackBlitz website builder.

Below is the screenshot of the affected page-

**Is there a problem with the URL I have provided in the input box?**

![MongoDB and Mongoose - Install and Set Up Mongoose _ Learn _ freeCodeCamp org - Google Chrome 21-11-2022 22_18_33](https://user-images.githubusercontent.com/78372105/203112785-f0e8f5c4-e861-451e-aaa9-2343408b25c7.png)

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/mongodb-and-mongoose/install-and-set-up-mongoose

### Your code

```js
  "dependencies": {
    "body-parser": "^1.15.2",
    "dotenv": "^8.2.0",
    "express": "^4.12.4",
    "mongoose": "^5.11.15"
  },
```
My .env code which is sample.env..

`<redacted>`

My code in myApp.js
```js
const mongoose = require('mongoose');
mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser=true,
  useUnifiedTopology=true
})
```

### Expected behavior

It should pass the tests when I have written the code

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ojeytonwilliams** [comment]
Hi @Feanor96, I recommend not sharing full connection strings with your username and password.  Just to be safe, it's best to update your password since this one is public now.

If this was just a random string, ignore me.

**Comment by moT01** [comment]
I removed your URI string from the post @Feanor96.

I'm curious, is that a codespaces URL or what? It might have something to do with that, not sure. You could look at the network tab when you run the tests and see what the requests are doing. Is your server running?

This feels like a question that would be better for the forum. There's something not quite working in the project - I don't think it's an issue with the tests. So I would recommend making a post on the forum to try and get help. I'm going to close this because I don't think it's an issue we can solve in our codebase. If you think I'm wrong, let me know and we can maybe reopen this. Thanks and happy coding 🎉

**Comment by Feanor96** [comment]
> I removed your URI string from the post @Feanor96.
> 
> I'm curious, is that a codespaces URL or what? It might have something to do with that, not sure. You could look at the network tab when you run the tests and see what the requests are doing. Is your server running?
> 
> This feels like a question that would be better for the forum. There's something not quite working in the project - I don't think it's an issue with the tests. So I would recommend making a post on the forum to try and get help. I'm going to close this because I don't think it's an issue we can solve in our codebase. If you think I'm wrong, let me know and we can maybe reopen this. Thanks and happy coding 🎉

Thanks @moT01 for removing the URI! I will check it and if it is not working, I will post it in the forum 🙌
