### ISSUE TITLE
Typo in: "Hash Table Explained: What it Is and How to Implement It"

### ISSUE THREAD

**Issue by IvanoskiHarmonia** [freeCodeCamp/freeCodeCamp#48566]
### Describe the Issue

if you go to this link: [Hash Table link](https://www.freecodecamp.org/news/hash-tables/), and go to "Some important notes about hash tables:" which is right below the first picture, in the second list point, the mistake is: "You **mush** account for potential collisions"

The only problem is that I cannot find this article anywhere. if someone knows where to find it let me know.

### Affected Page

https://www.freecodecamp.org/news/hash-tables/

### Steps to Reproduce

This is not a bug, so if you want to see it, just go to this [link](https://www.freecodecamp.org/news/hash-tables/).

### Recommended fix or suggestions

The only thing needs changing is: **mush** -> **must**.

### Screenshots

<img width="738" alt="Screenshot 2022-11-21 at 6 59 34 PM" src="https://user-images.githubusercontent.com/70523051/203188784-4a2d4eab-0179-4d2d-b6a8-3a6ed8ee554f.png">

**Comment by moT01** [comment]
Thanks for reporting @IvanoskiHarmonia, I found the article and fixed the typo - it will be updated with the next release of articles. Thanks

**Comment by IvanoskiHarmonia** [comment]
Hey @moT01, I appreciate your help, I was not able to find the article so that is why I created this issue.

Thanks again for fixing it for me.

**Comment by moT01** [comment]
I couldn't find it for a while either.
