### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ab80four** [freeCodeCamp/freeCodeCamp#48571]
### Describe the Issue

In the last paragraph in the "Abstraction" section there is a small typo of the word "Abstraction".  Right now its spelled "Abstarction".

### Affected Page

https://www.freecodecamp.org/news/what-is-object-oriented-programming/

### Steps to Reproduce

Would just have to follow the link and scroll down to the "Abstraction" section and read the last paragraph.

### Recommended fix or suggestions

Locate the file and correct the spelling

### Screenshots

<img width="709" alt="Screenshot 2022-11-22 at 8 20 30 AM" src="https://user-images.githubusercontent.com/83462295/203324980-9aaf273e-09ed-4eec-ace6-50a7c66c0538.png">

**Comment by DylanDevelops** [comment]
Is the typo somewhere in this repository: https://github.com/freeCodeCamp/news

**Comment by ab80four** [comment]
Honestly I couldn't find where the file was located, so I created the issue :/ sorry.

**Comment by DylanDevelops** [comment]
You're totally good. I just looked through the whole repository and I'm confused about where the file is located too. Hopefully, someone knows. I'm going to keep looking.

**Comment by ab80four** [comment]
Yeah its interesting, I did a search for the address and found nothing in the freecodecamp public repository.  I wonder if its in a private one?

**Comment by DylanDevelops** [comment]
Could be. I'll let you know if I find anything and maybe a member of freeCodeCamp will see this issue soon.

**Comment by pJanks** [comment]
Possibly in the db? where ever `[...]/news/[oop_article]` gets its data.

**Comment by ShaunSHamilton** [comment]
@ab80four Thank you for opening this issue.

@DylanDevelops and @pJanks Sorry for the confusion, news articles can only be edited by a member of staff.

**Comment by ShaunSHamilton** [comment]
I have fixed the typo, and the change should be live the next time `/news` builds.
