### ISSUE TITLE
i variable not declared and all the code assignments are missing going through "Map" link

### ISSUE THREAD

**Issue by rafster** [FreeCodeCamp/FreeCodeCamp#4857]
All my assignments code is missing if I try to find it through "Map" link, if I follow it through the "porfolio" link it is there but I am getting "i is not defined" error in all of my scripts for all assignments.

**Comment by bugron** [comment]
@rafster thanks for posting this issue!
Can you post a screenshot, provide more details?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Manna-Iyengar** [comment]
same here no code on any assignments i have previously completed.
![image](https://cloud.githubusercontent.com/assets/15222759/11504305/a1e6ea82-9812-11e5-9306-0f98dd61e588.png)
![image](https://cloud.githubusercontent.com/assets/15222759/11504327/bec35582-9812-11e5-9929-20c3d8294165.png)

Thanks
Manna

**Comment by rafster** [comment]
If I go to "Map" link at the top of the page and click on assignment no code which I wrote and worked:
![image](https://cloud.githubusercontent.com/assets/15970039/11504282/5e4560b0-97f9-11e5-9748-4f0099c3c2f3.png)

this is going through portfolio link, code is there but "i not defined" error in all my codes

![image](https://cloud.githubusercontent.com/assets/15970039/11504310/89c67724-97f9-11e5-8808-111b68199a02.png)

**Comment by Manna-Iyengar** [comment]
i have completed 6 other assignments on basic algorithm scripting after this and it is not even updated in the map...

Thanks
Manna

**Comment by rafster** [comment]
I tried closing and opening browser, tried different browser, tried logging in and out of the account , still the same problem

**Comment by bugron** [comment]
Can you check if there are any errors in your browser's console?

**Comment by rafster** [comment]
this is the error message in Chrome
![image](https://cloud.githubusercontent.com/assets/15970039/11506519/b59488c2-9804-11e5-8960-33c81f30f247.png)
this is firebug in Firefox
![image](https://cloud.githubusercontent.com/assets/15970039/11506650/593b89da-9805-11e5-927d-13a5f1afa5da.png)

**Comment by BerkeleyTrue** [comment]
@rafster Can you post the code where you are getting `i is not defined`?

**Comment by legionista66** [comment]
How it was resolver? I have the same issue with my. I have one mouth break and now when I try to see my previously made solution the e are gone... how to fix it ?

**Comment by cdandro** [comment]
I think I'm having the same problem. If I load an item via the map my solution doesn't show. If I go to profile, find the same item I get my previous solution. Chrome on Windows 10. Console shows nothing.

Loading via the map:
![image](https://cloud.githubusercontent.com/assets/6656333/13547880/288d3676-e2b0-11e5-86e3-8781da08721b.png)

Loading via the profile:
![image](https://cloud.githubusercontent.com/assets/6656333/13547889/3a90a2ea-e2b0-11e5-8458-19b5847db88b.png)

**Comment by ltegman** [comment]
@cdandro This expected. Navigating from the map pulls from localStorage, which is stored in the browser and is only temporary. If you want to resave your profile solution to localStorage you can navigate to the challenge from your profile and then type something into the editor - that will trigger a localStorage write.

**Comment by cdandro** [comment]
Ohhh didn't expect that, I started using multiple  computers and didn't
know it would do that. Is there a way to mass update local storage? I'm
doing a review by going back through challenges.
