### ISSUE TITLE
extra space in a hint causes confusion in translation efforts

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48579]
There is empty space after `should` that confuses translation

Here is the string
https://github.com/freeCodeCamp/freeCodeCamp/blob/6ba84c091a72463e87111fb1e8b2e66d8ba16f1b/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object.md#L112?plain=1

here is the original issue
https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/20696/en-id?filter=basic&value=3#q=724770

What is required is to type the string like this

> A `setter` should be defined.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by thinklikeadesigner** [comment]
Nice catch, whitespaces are weird in markdown. I'll make a PR.
