### ISSUE TITLE
Typos in OOP Meaning – What is Object-Oriented Programming? Article

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#48585]
### Describe the Issue

One of the paragraphs within the article happens to be as follows:

> In this article we will go over Object Oriented Programming (OOP) as a whole, without relying on a particular language. You'll learn what it is, why it's so popular as a programming paradigm, it's structure, how it works, its principles, and more.

Instead, it should be as follows:

In this article, we will go over Object Oriented Programming (OOP) as a whole, without relying on a particular language. You'll learn what it is, why it's so popular as a programming paradigm, its structure, how it works, its principles, and more.

**NOTE:** In the second sentence, instead of saying `it's structure`, it should be saying `its structure`.

------

One of the paragraphs within the article ( second paragraph within the following instance to be specific ) happens to be as follows:

> For example, you'll define an employee object that defines all the overall characteristics of employees in your company.
> 
> You'll be able to then define a manager object that inherits the characteristics of the worker object but also adds characteristics unique to managers in your company. The manager object will automatically reflect any changes within the implementation of the worker object.

Instead, it should be as follows:

You'll be able to then define a manager object that inherits the characteristics of the employee object but also adds characteristics unique to managers in your company. The manager object will automatically reflect any changes within the implementation of the employee object.

**NOTE:** Within this paragraph, since we are trying to refer to the `employee` object ( defined within the paragraph right before the above paragraph ), keeping that in mind it should be saying `employee` object instead of saying `worker` object.

### Affected Page

https://www.freecodecamp.org/news/what-is-object-oriented-programming/

### Steps to Reproduce

Just viewing the article itself within the browser, should be sufficient to reproduce the problem.

### Recommended fix or suggestions

For the first issue, updating the paragraph as follows should fix the typo:

In this article, we will go over Object Oriented Programming (OOP) as a whole, without relying on a particular language. You'll learn what it is, why it's so popular as a programming paradigm, its structure, how it works, its principles, and more.

**NOTE:** In the second sentence, instead of saying `it's structure`, it should be saying `its structure`.

-----

For the second issue, updating the paragraph as follows should fix the typo:

You'll be able to then define a manager object that inherits the characteristics of the employee object but also adds characteristics unique to managers in your company. The manager object will automatically reflect any changes within the implementation of the employee object.

**NOTE:** Within this paragraph, since we are trying to refer to the `employee` object ( defined within the paragraph right before the above paragraph ), keeping that in mind it should be saying `employee` object instead of saying `worker` object.

### Screenshots

<img width="787" alt="image" src="https://user-images.githubusercontent.com/36872756/203670532-1c96af40-06c3-40d5-bb60-e88b32693ae1.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/36872756/203670603-2166f47f-1ed3-4ac4-b1ea-5cb7539a97fa.png">

**Comment by AbbeyRenn** [comment]
Thank you @AnonSar and @sidemt - fixed! It'll render after the next site build.
