### ISSUE TITLE
Binary Agents: results checklist - num2

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#4858]
This is probably an aesthetical issue, not a bug.
You may want to correct it, if it was not made on purpose.

*binaryAgent("01001001 00100000 01101100 01101111 01110110 01100101 00100000 01000110 01110010 01100101 01100101 01000011 01101111 01100100 01100101 01000011 01100001 01101101 01110000 00100001" should return "I love FreeCodeCamp!"*
should probably be 
*binaryAgent("01001001 00100000 01101100 01101111 01110110 01100101 00100000 01000110 01110010 01100101 01100101 01000011 01101111 01100100 01100101 01000011 01100001 01101101 01110000 00100001"__)__ should return "I love FreeCodeCamp!"*

**Comment by bugron** [comment]
@rfprod thanks for pointing this out, confirmed!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
