### ISSUE TITLE
CatPhotoApp Step 4 Editor should have a blank line where new comment should go

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48589]
### Describe the Issue

Been puzzling over why so many people see the instructions in step 4 of the cat photo app and ignore the requested location of "above the p element" when adding their new comment line of code.
Discussed with @jeremylt and he noticed that the editor doesn't show an empty line where it expects the code to go (usually it does on other steps).
This issue then is to request a blank line be added to the editor for step 4 above the p element line to show where the expected new line of code should be written.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-4

### Your code

```

```

### Expected behavior

Editor should display a single blank line above the p element.

### System

not applicable

### Additional context
Example of forum post where learner just doesn't understand how the code can be added -above-
<https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-4/573788>

full discussion in the contributors area of the discord channel
(start point here <https://discordapp.com/channels/692816967895220344/715074489422970962/1045440339948875857>)

**Comment by DylanDevelops** [comment]
I don't have an option for this.

However, I do think that we should take away the empty space that is created below the `p` tag as there is no reason why it needs to be there, and might lead to confusion.

**Comment by amansinghal14** [comment]
Hi @hbar1st and @DylanDevelops, I want to work on this issue. Could you assign it to me?

**Comment by DylanDevelops** [comment]
> Hi @hbar1st and @DylanDevelops, I want to work on this issue. Could you assign it to me?

Issues don't get assigned so just create a new branch and get to work! Make sure you have read the rules for contributing: https://contribute.freecodecamp.org/#/

**Comment by Sboonny** [comment]
Whoops, I have missed a step 🤣 👍 
---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
