### ISSUE TITLE
Two variables which are same

### ISSUE THREAD

**Issue by Feanor96** [freeCodeCamp/freeCodeCamp#48582]
### The issue is in _Backend Development and APIs Course, MongoDB and Mongoose section_ challenge "Create a Model" 

In the instructions, we are asked to create a model called `Person` from `personSchema` by the code:
```js
const Person = mongoose.model("Person", personSchema);
```
However in the folder `boilerplate-mongomongoose`, there is already an empty variable:
```js
let Person;
```
Following the instructions gives a bug as the Person variable is already declared.
We have to delete the empty variable in order to continue with the instructions. Maybe the hints should be corrected for the challenge or the variable name in the instruction should be changed.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/mongodb-and-mongoose/create-a-model

### Your code

```

```

### Expected behavior

We should not get an error after running the code.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
That line has to stay in order for the code to "compile":

https://github.com/freeCodeCamp/boilerplate-mongomongoose/blob/a820f2b3b01349a429f8589718868f8b68e107c5/myApp.js#L58-L60

**Comment by Feanor96** [comment]
> I believe the idea is that you assign the new schema to the existing variable - but I would not be opposed to removing it.

ok thanks! 😄

**Comment by ojeytonwilliams** [comment]
So, it sounds like we can't remove `let Person;` but we could clarify the wording slightly.

How about the following?

> Now, create a model from the `personSchema` and assign it to the variable `Person`.

**Comment by naomi-lgbt** [comment]
Maybe `the existing variable Person` just for clarity?

**Comment by spiritanand** [comment]
Why is there a need to change? They are not conflicting with each other in any way, are they?
