### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by hansinla** [FreeCodeCamp/FreeCodeCamp#4859]
Challenge [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code?solution=%2F%2F%20This%20is%20a%20comment.%0A%0A%2F*%20This%20is%20also%20a%20comment.%20*%2F%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// This is a comment.

/* This is also a comment. */

```

**Comment by bugron** [comment]
@hansinla thanks for posting. We're aware of this issue. Let's keep the discussion in #4853. Closing.
