### ISSUE TITLE
Typo in Wi-Fi Hacking 101 – How to Hack WPA2 and Defend Against These Attacks Article

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#48609]
### Describe the Issue

An item within the `What We'll Cover` list within the article has been misspelled as `Preriquisites` ( it should be spelled as `Prerequisites` ).

### Affected Page

https://www.freecodecamp.org/news/wi-fi-hacking-101/?fbclid=IwAR3OeQ7Y-vO8TNkm2Zbr971ToV27S5cuTnHfTWVSaI5NuEvWVBy1UdnjtoY

### Steps to Reproduce

Just viewing the article itself within the browser, should be sufficient to reproduce the problem.

### Recommended fix or suggestions

An item within the `What We'll Cover` list within the article has been misspelled as `Preriquisites` ( it should be spelled as `Prerequisites` ).

### Screenshots

![image](https://user-images.githubusercontent.com/36872756/204115319-7af3a7b3-a473-4ece-ac4b-3d28033e33ec.png)

**Comment by AbbeyRenn** [comment]
Thank you - fixed!
