### ISSUE TITLE
Cannot complete challenge 

### ISSUE THREAD

**Issue by mahom21** [FreeCodeCamp/FreeCodeCamp#4860]
Challenge [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code?solution=%2F%2F%20comment%20overlord%0A%2F*%20comment%20underling%20*%2F) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// comment overlord
/* comment underling */
```

**Comment by bugron** [comment]
@mahom21 thanks for posting. We're aware of this issue. Let's keep the discussion in #4853. Closing.
