### ISSUE TITLE
Missing German link in live certifications section

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48607]
In https://contribute.freecodecamp.org/#/index?id=translations, live certification missing German.

Here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/2357ad69b7da2f24a8895dd736395775eda69c24/docs/index.md#L28-L33?plain=1

You should add 

> - [German (Deutsch)](https://www.freecodecamp.org/german/learn)

Here is the code link

```md
- [German (Deutsch)](https://www.freecodecamp.org/german/learn)
```

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by harshilnakum** [comment]
@Sboonny assign this to me.
