### ISSUE TITLE
Trending Guides section in Footer is not translated in German 

### ISSUE THREAD

**Issue by harshilnakum** [freeCodeCamp/freeCodeCamp#48614]
### Describe the Issue

Upon changing the language to German on home page, the trending guides section in footer displays content in English instead of German. 

### Affected Page

https://www.freecodecamp.org/german/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/german/
2. Scroll down to footer
3. See the content under "Beliebte Guides" (Trending Guides)

It is not translated to German!

### Expected behavior

The content should be displayed in German language.

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/85291725/204141565-ccab831b-17bc-43d3-8909-7d6c17063cc9.png)

### System

- Device: Laptop
- OS: Win10
- Browser: Chrome
- Version: 107.0.5304.108 (Official Build) (64-bit)

**Comment by Sboonny** [comment]
Although what you are saying is true, it's complicated, there need to have enough translated article to be displayed in the footer. If you are interested in helping out, you can head to [German discord channel](https://discord.gg/PRyKn3Vbay) and discuss it with language lead there
