### ISSUE TITLE
Progress bar (with percentage point) and navigation menu needed 

### ISSUE THREAD

**Issue by greptux** [freeCodeCamp/freeCodeCamp#48648]
### Is your feature request related to a problem? Please describe.

I find it's easy to be lost in the interface of challenges. Maybe we could add a **progress bar** and a **navigation menu** inside the workspace. The graph and numbers shown can reward us going forward more consistently. I think in future versions of freeCodeCamp we can do something more on UI/UX to gamify the learning process.

### Describe the solution you'd like

<img width="1406" alt="Screenshot 2022-12-02 at 00 15 57" src="https://user-images.githubusercontent.com/46900286/205107968-4a34b7a2-050c-4e1d-81a9-0c6d0f683e80.png">
Above is a simple demonstration. I'm a novice here. I don't know how to implement it. It definitely has better solution. Anyone can do this?

### Describe alternatives you've considered

A side bar may also work. But the layout should be completely changed. That's a huge amount of work.

**Comment by ahmadabdolsaheb** [comment]
Thanks for creating this issue.
We try to make the users focus on the challenge itself in the challenge layout. 
As a result, the challenge navigation is reduced to a breadcrumb and the footer is completely removed.
The progress bar and detailed content navigation do exist, but we only try to show them when the user needs them.

In the new Responsive Web Design challenges, the progress bar will be added to the challenge itself and we are discussing in a few issues if adding tags and/or creating more descriptive titles are feasible.

**Comment by greptux** [comment]
Thank you for your efforts! I really appreciate the work you've done. I hope one day I could contribute to this project too.

**Comment by ahmadabdolsaheb** [comment]
@greptux, thank you for you feedback. I highly recommend checking out our [Contribution Guidelines](https://contribute.freecodecamp.org/#/) and finding an issue that you are interested on working on.

I am closing this issue as the requested features are already in the roadmap.
