### ISSUE TITLE
Help me progress

### ISSUE THREAD

**Issue by fire69water** [FreeCodeCamp/FreeCodeCamp#4865]
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%23000000%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My answer is correct but wrongly flagged as erroneous.
My code:
```html
<style>
  body {
    background-color: #000000;
  }
</style>

```

**Comment by ltegman** [comment]
There looks to be an issue with how this test runs on initial page load. Try refreshing the page and then pressing Run Tests. It should let you pass at that point. However, I am going to keep this issue open so we can look into why it doesn't pass on page load.

**Comment by catfish68** [comment]
I have the same problem, I have refreshed, cleared my cache and even used 3 different devices and it still doesn't work or let me bypass this specific waypoint

**Comment by ltegman** [comment]
@catfish68 What browser are you using?

**Comment by catfish68** [comment]
IE, Firefox and chrome on my pc and tablet
Safari and opera on my iPhone

**Comment by catfish68** [comment]
It finally cleared. I was able to get pass that waypoint

**Comment by ltegman** [comment]
Looks like this issue does not resolve upon manual submission through "Run Tests" in Firefox, only in Chrome.

**Comment by bickhaus** [comment]
I am also having this issue in Firefox 42.  I am having a similar issue with waypoints 45, 46, and 47.

**Comment by catfish68** [comment]
Try a different browser. I would go with Firefox or chrome

**Comment by fire69water** [comment]
I encountered this problem when I used Microsoft Edge and Firefox. No problem when I used Chrome.

Thanks all.
