### ISSUE TITLE
Step 31 of project "Building a Registration Form" should specify input element must be nested in the label

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48655]
### Describe the Issue

In step 31 of the Learn HTML Forms by Building a Registration Form project, the step doesn't explicitly say that it wants the input element to be nested inside the label element. Instead it says:
"Add a label with the text Upload a profile picture: , and add an input accepting a file upload."
This could be interpreted to mean that the input element should be on the right side of the label element.
Only when we attempt this are we told by the Hint  "You should nest an input element inside the label element."

To clarify the requirement, the step should use the word *nest* in the exercise as below for eg.:
"Add a label with the text Upload a profile picture: , and nest an input accepting a file upload within it.",

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-31

### Your code

```

```

### Expected behavior

The step should explicitly state that the input element should be nested within the new label element.

### System

Not Applicable

**Comment by arantebw** [comment]
@hbar1st I think if all of the challenges will have specifications defined explicitly, it will serve no purpose of "challenging" the learners to really think and solve it. In the first place, the solution is already implied from the given code and then, if the learners will still have the hard time solving it, then the `hint` feature will definitely do its job.

**Comment by bbsmooth** [comment]
> "Add a label with the text Upload a profile picture: , and nest an input accepting a file upload within it."

Agreed. The instructions should be clear to begin with. Making the users guess what the test requires isn't a "challenge", it's just rude.

**Comment by naomi-lgbt** [comment]
> Only when we attempt this are we told by the Hint "You should nest an input element inside the label element."

For what it is worth, the camper has nested an input in a label element a few times in this challenge prior to this step.

I am not against adding this reminder to the instructions, but I don't want to lose sight of our goal to keep the instructions more lean and have the hints serve as the reminders.

**Comment by bbsmooth** [comment]
> For what it is worth, the camper has nested an input in a label element a few times in this challenge prior to this step.

Definitely. But I looked back at the instructions on the steps where they add the previous inputs and we do explicitly tell them to put the input within the label:

- step 17: Nest an input element within each label. 
- step 25: within each of the first two label elements, add one input element with type="radio".

If we can add that information to those instructions then I think we can add it to this one.

**Comment by hbar1st** [comment]
I understand that if someone is working on a series of steps they may not need to be told to nest the input again. However, if they stop and return to the project a few weeks later on, they may not remember that. The hint will remind them sure. I guess this is a minor issue given the hint is quite clear. Personally I like a more explicit instruction.
