### ISSUE TITLE
Typo found as in badge for 'Certification Porject' in mobile app beta

### ISSUE THREAD

**Issue by rubanero14** [freeCodeCamp/freeCodeCamp#48667]
### Describe the Issue

As a beta tester for the mobile app for fCC, I noticed in the latest RWD curriculum, there are multiple sections for certification project with badge contains typo 'Certification Porject', should not it be Certification Project?. Maybe I'm wrong, thought of highlighting 

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp

### Your code

```
# Nothing here 
```

### Expected behavior

A badge with Certification Project 

### Screenshots

![Screenshot_20221204_132237](https://user-images.githubusercontent.com/85555894/205476076-7d4db43a-aea7-4bee-807a-7c2cbc9a9fd3.jpg)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by arantebw** [comment]
@rubanero14 I think you should move this issue to this repository instead: https://github.com/freeCodeCamp/mobile/issues
