### ISSUE TITLE
Keep the keyboard in mobile devices open when camper press Run

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48666]
### Is your feature request related to a problem? Please describe.

While reviewing #48586, please check it if you want more context, I suggested keeping the keyboard open while clicking on "Run" button.

The idea is as follows, because `input` element opens the keyboard, we can add a hidden `input` element inside the `button` with text "Run". This should keep the button open and with the hidden nature of the input, screen readers should ignore it and it won't be focusable.

But this is inviting a second issue if we do this, because now we will have input that can handle campers input, but doesn't do anything with. We need to add a functionality that use the handled input to change the code back, so the experience stay smooth and doesn't require campers to navigate to where the code, to interact with the code again.

### Describe the solution you'd like

- We create a function that saves the place where the camper was typing in. (edit: changed "remembers" to "saves")
- Add `input` element that is hidden, inside the `Run` button (or the clear icon in search bar for future PR)
- This `input` will keep the keyboard on, and campers can still type in that input
- the campers inputs, which they typed in the hidden `input` element, transferred to the last place that the camper typed in, which is saved by the function. (Edit: thinking about this, do we need to transfer the input? Maybe we can select the saved place back and remove a headache.)

### Describe alternatives you've considered

We can ignore a hacky way, and go with my first suggestion by moving the focus into the keyboard again, but we have to account for accessibility, like how Bruce mentioned here https://github.com/freeCodeCamp/freeCodeCamp/pull/48586#issuecomment-1335724747

### Additional context

The more that I think about it, my solution seems too hard and terrible, perhaps I am complicating things so here is the idea to iterate on it and hopefully improve it.

**Comment by bbsmooth** [comment]
> we can add a hidden input element inside the button with text "Run".

I'm not sure if I am understanding this correctly, but if you mean that we should embed an `input` element within a `button` element then this would be a WCAG violation and thus not accessible. Interactive elements cannot contain other interactive elements.

**Comment by Sboonny** [comment]
oh, time to update Chapter 🤣, thank you. Didn't know that

**Comment by mmatsumoto1026** [comment]
According to [this question](https://stackoverflow.com/questions/71513013/how-to-prevent-mobile-keyboard-from-closing-when-i-click-button-in-website), using `touchend` event listener and `event.preventDefault();` with "Run" button, It seems that we can keep the virtual keyboard in mobile devices open when camper press the button.

So how about using this idea in `tool-panel.tsx` with the code shown below?

```typescript
const handleRunTests = (event: React.TouchEvent<HTMLButtonElement> | React.MouseEvent<HTMLButtonElement>) => {
  event.preventDefault();
  executeChallenge({ showCompletionModal: true });
};
```

```typescript
<div
　className={`tool-panel-group button-group ${
  　isMobile ? 'tool-panel-group-mobile' : ''
  }`}
>
　<Button
    　aria-label='Run the tests use shortcut Ctrl+enter'
    　block={true}
    　bsStyle='primary'
    　{...(navigator.userAgent.match(/iPhone|Android.+Mobile/) ? { onTouchEnd : handleRunTests } : { onClick : handleRunTests })}
　>
　　{isMobile ? t('buttons.run') : t('buttons.run-test')}
　</Button>
```

**Comment by bbsmooth** [comment]
Personally, I am leery of overriding the default behavior of the virtual keyboard and I'm still not convinced this is going to work properly or be accessible. But if you can get this working in a PR I'll be happy to review it for accessibility.

**Comment by ojeytonwilliams** [comment]
Based on those a11y issues, we should not change the default behaviour.
