### ISSUE TITLE
Page Not Found-Broken Link

### ISSUE THREAD

**Issue by DivyanshuBist** [freeCodeCamp/freeCodeCamp#48683]
### Describe the Issue

In the provided [link](https://www.freecodecamp.org/news/finding-your-first-open-source-project-or-bug-to-work-on-1712f651e5ba/), 

 `contributing regularly` url doesn't exists( page not found).

### Affected Page

https://www.freecodecamp.org/news/finding-your-first-open-source-project-or-bug-to-work-on-1712f651e5ba/

### Steps to Reproduce

Go To this [url](https://www.freecodecamp.org/news/finding-your-first-open-source-project-or-bug-to-work-on-1712f651e5ba/)

### Recommended fix or suggestions

Fix the url or may be remove if url is not present

### Screenshots

![image](https://user-images.githubusercontent.com/77827249/206093828-b3f2562b-9a55-4426-ac85-a0fa33f13b9c.png)

**Comment by Nirajn2311** [comment]
The correct url is - https://www.freecodecamp.org/news/a-beginners-very-bumpy-journey-through-the-world-of-open-source-4d108d540b39

**Comment by scissorsneedfoodtoo** [comment]
Hi @DivyanshuBist, thank you for reporting this. And thank you @Nirajn2311 for posting the correct link.

I went in and fixed that broken link. I also fixed a few other broken links that I found.

These fixes should go live within a few hours.

Please let us know if you find issues in any other articles.
