### ISSUE TITLE
define i in a for loop?

### ISSUE THREAD

**Issue by versatal** [FreeCodeCamp/FreeCodeCamp#4869]
Challenge [Bonfire: Chunky Monkey](http://www.freecodecamp.com/challenges/bonfire-chunky-monkey?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20var%20myArr%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%204%3B%20i%2B%2B)%20%7B%0A%20%20%20%20myArr%20%3D%20arr.slice(i%2C2)%3B%0A%20%20%7D%0A%20%20return%20myArr%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Pretty clear .... I get "i is not defined" as an error message.  The code should run even though it is not the correct output.

My code:
```javascript
function chunk(arr, size) {
  // Break it up.
  var myArr;
  for (i = 0; i < 4; i++) {
    myArr = arr.slice(i,2);
  }
  return myArr;
}

chunk(["a", "b", "c", "d"], 2);

```

**Comment by bugron** [comment]
@versatal thanks for posting this issue!
You're missing `var` keyword before `i = 0` but even with that you code won't pass tests. Please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
