### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue 

### ISSUE THREAD

**Issue by ekojsalim** [FreeCodeCamp/freecodecamp#487]
Test passes even though the img src attribute is empty

**Comment by katiequin335** [comment]
I also have this issue.

**Comment by terakilobyte** [comment]
This is because of the way html is actually structured. We'll look into verifying the src attribute itself.  Thanks for the heads up on this!

**Comment by QuincyLarson** [comment]
OK - I fixed this issue for two different challenges. It may come up other places, in which case I'll follow the pattern I used and fix it those places, too.

Thank you @katiequin335 @ekojsalim for reporting this suboptimal test! :)
