### ISSUE TITLE
Typo on the Moderator Handbook Document

### ISSUE THREAD

**Issue by Sriparno08** [freeCodeCamp/freeCodeCamp#48709]
### Describe the Issue

In the Moderator Handbook document, you will see a note section just above the Moderating GitHub section. In that note, there is a sentence that says:

> If you are missing access on a platform

The preposition you see after the word "access" is incorrect.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/moderator-handbook.md

### Steps to Reproduce

1. Go to [Moderator Handbook](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/moderator-handbook.md)
2. Navigate to the note section located just before the Moderating GitHub section
3. Spot the typo

### Recommended fix or suggestions

The sentence should be changed to:

> If you are missing access to a platform

The preposition after "access" needs to be changed from "on" to "to".

### Screenshots

![Untitled design](https://user-images.githubusercontent.com/89148144/206835223-79609c18-248e-4342-a2eb-b99d65f7aa17.png)

**Comment by naomi-lgbt** [comment]
I don't think this is correct tbh.

We don't grant access to a platform - moderators typically have an account already. We grant access to the moderation tooling on the platform.

**Comment by Sriparno08** [comment]
Hey @naomi-lgbt, I have got your point! So, shall I close the issue?

**Comment by naomi-lgbt** [comment]
Yes, I'll go ahead and close this.
