### ISSUE TITLE
Extra new lines in being a moderator of FAQ docs

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48718]
**Describe the bug**
In FAQ docs, being a moderator section has extra new lines that make it challenging to translate to Arabic, as there is no flow to words and making it abstract.

Here is the file 
https://github.com/freeCodeCamp/freeCodeCamp/blob/12fd5c4d328ca279debad8ca8b5da68d34bbf29b/docs/FAQ.md#L72-L107?plain=1

We can remove the extra new lines in that section and make it look similar to the other sections

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by suyashmadhesia** [comment]
Hi, I want to contribute to the docs. I have never contributed before. Can you help me with this? @Sboonny

**Comment by Harixomxsingh** [comment]
Hey, I found the issue and I would love to help with that

**Comment by Sboonny** [comment]
Feel free to open a pr, after you have read our guidelines

**Comment by tiwarishankar** [comment]
Hey @Sboonny is this already assign to someone if not i am ready to take this up

**Comment by Libra2003** [comment]
Hey Sboonny, This is my first time contributing and i would love to start with this issue

**Comment by hbar1st** [comment]
Hi M., 
What do you mean by "extra new lines"? I can detect any extra newline characters.

Maybe you should give at least one example of something that has an extra newline character and how you would fix it?

**Comment by Sboonny** [comment]
It's extra line breaks, not new lines. sorry for the confusion

```md
something like
this is used 
in the moderator section
of the docs
```
