### ISSUE TITLE
A word ending with special character in the docs

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48722]
**Describe the bug**
there are situations in which you need to add special character (like `!@#$%^&().`) which is fine, but for RTL the direction is reverted so the placement of the special character is reverted, as well.

> Locate and click on the link for your Windows version (32 or 64 bit) and a .exe file will be downloaded to your computer.

Here is the file 

https://github.com/freeCodeCamp/freeCodeCamp/blob/519e0d2a51221e54907b8ee0c21e09dce7457ee2/docs/how-to-catch-outgoing-emails-locally.md#L53-L54?plain=1

Likely we have the CSS property to fix this, we simply need the element to wrap that word so we can apply them.

To fix this issue wrap the `.exe`, between markdown code, like this \`.exe\`, so the sentence will be something like this

> Locate and click on the link for your Windows version (32 or 64 bit) and a `.exe` file will be downloaded to your computer.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Sboonny** [comment]
There is a second mentioning of .exe in this sentence

> To start MailHog again, click on the MailHog executable (.exe) file that was downloaded initially - it is not necessary to download a new MailHog installation file.

if it changed to `.exe` too, that would be awesome

**Comment by yoyoekta** [comment]
Hi,
Has this issue been assigned to someone? If not, could you please assign this to me?

**Comment by Sboonny** [comment]
We don't assign issues, feel free to open PR after reading our docs 👍
