### ISSUE TITLE
Waypoint: Manipulate Arrays With shift

### ISSUE THREAD

**Issue by minsooshin** [FreeCodeCamp/FreeCodeCamp#4872]
It complains "removedFromOurArray is not defined" in the console.
The exercise code has issue on line #3; it doesn't declared with `var` keyword, and exercise instructs change only certain line, but the error is not related to that section.

**Comment by ltegman** [comment]
This has been fixed by PR #4870 and is awaiting deployment to the prod website.

Thanks and happy coding!

**Comment by minsooshin** [comment]
Got it. Thanks for quick response!!
