### ISSUE TITLE
Typo on the Moderator Handbook Document

### ISSUE THREAD

**Issue by Sriparno08** [freeCodeCamp/freeCodeCamp#48725]
### Describe the Issue

In the Moderator Handbook document, you will see a "Moderating Pull Requests" section. Under that section, there is a subsection named "Challenge instruction edits". In that section, there is a sentence that says:

> Contributors may try to add links to resources to the challenges.

The preposition after the word "resources" is incorrect.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/moderator-handbook.md

### Steps to Reproduce

1. Go to [Moderator Handbook](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/moderator-handbook.md)
2. Navigate to the "Challenge instruction edits" subsection located under the "Moderating Pull Requests" section
3. Spot the typo

### Recommended fix or suggestions

The sentence should be changed to:

> Contributors may try to add links to resources for the challenges.

The preposition after "resources" needs to be changed from "to" to "for".

### Screenshots

![Untitled design (1)](https://user-images.githubusercontent.com/89148144/206904825-c5070a54-a139-4c82-90c8-8124e8f92af8.png)

**Comment by naomi-lgbt** [comment]
I believe this is intended - contributors may find links to resources that they think are relevant, and might attempt to add those links **to** the challenge itself.

**Comment by Sriparno08** [comment]
Alright! So, shall I close the issue, @naomi-lgbt?

**Comment by Sboonny** [comment]
I agree with @naomi-lgbt. And you don't seem to mind, so I am closing this issue.

Thank you for reporting it
