### ISSUE TITLE
Missing code block in step 1 of new JS RPG project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48737]
**Describe the bug**

>  Then, create a `div` element with the id `game` within your `body`.

In this string, we are missing code tags around the word `id`.

We can change it to this string

> Then, create a `div` element with `id` set to `game` within your `body`.

Here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/c9e3300d72f8ac434d2e3886ad1df1d0ccc902d1/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/5d5a813321b9e3db6c106a46.md#L10?plain=1

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by MohammedAtallahhh** [comment]
Hey, I can do it

**Comment by Priyas-20** [comment]
Hey !
Could you please assign it to me.
I would be glad to start contributing in open-source with freeCodeCamp.

**Comment by Sboonny** [comment]
There is no assignment, you can open a PR, after you have read out our guidelines
