### ISSUE TITLE
in every js lesson page i have `TypeError: Object.assign is not a function`

### ISSUE THREAD

**Issue by aseds** [FreeCodeCamp/FreeCodeCamp#4873]
in every link from the "basic javascript" section i go(and the later Javascipt lessons, not jQuery lessons or anything else), i have a 
```TypeError: Object.assign is not a function```
two days ago these links worked and i already have completed these lessons but now they're not working. all of them.

- i did reset the code  
- made a hard refresh using the F5 key
- deleted localStorage
- tried the incognito mode    
**still i have the same error.**

and this error is in my console too. 

i tried with my Galaxy Note 4:
in Dolphin browser, i have the error.
but in chrome there is no error!

**Comment by ltegman** [comment]
Is this only on your mobile device that this happens or can you also reproduce this error on a desktop browser?

**Comment by aseds** [comment]
on my laptop:
     Chrome gives:
         `TypeError: Object.assign is not a function`
     Firefox gives:
         `chai is not defined`

on my mobile: 
    Chrome works without an error
    Dolphin browser gives:
       `TypeError: Object.assign is not a function`

**Comment by BerkeleyTrue** [comment]
Looks like I included that in here without thinking. I'll replace it soon.

**Comment by SeanB99** [comment]
Im also having this issue. On any new and completed waypoints and bonfires I get this error. 

Im using Chrome on an andriod phone. Tried clearing data, refreshimg and requesting desktop version.

**Comment by SasankYadati** [comment]
Same issue!
Browser - Firefox(desktop)
TypeError:Object.assign is not a function!

**Comment by Puine** [comment]
Same issue for me since yesterday ...
(Chrome : TypeError:Object.assign is not a function!)

**Comment by manurudh** [comment]
Same TypeError on Safari

**Comment by pritamkumarshahi** [comment]
Same issue..From yesterday...!

Chrome gives: TypeError: Object.assign is not a function
Firefox gives: chai is not defined

**Comment by BerkeleyTrue** [comment]
Thanks everyone. A patch is on the way.
