### ISSUE TITLE
Accessibility Quiz Step 57 instructions not clear

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#48743]
### Describe the Issue

The only way to pass this step is to create a new ruleset that targets both `.info input` and `.info label` and add the `display` property to that new ruleset. But the instructions do not make this clear and the alternative solution of adding the `display` property separately to the existing `.info input` and `.info label` rulesets is being rejected. 

Yes, the hint does explain that a new ruleset should be created, but I think this should be made clear in the instructions since I think a lot of people are going to assume that they should just use the existing rulesets. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-57

### Your code

```
.info input {
  width: 50%;
  text-align: left;
  display: inline-block;
}

.info label {
  width: 10%;
  min-width: 55px;
  display: inline-block;
  text-align: right;
}
```

This does not pass the step even though it accomplishes the goal of the step. 

### Expected behavior

Rewrite the instructions to make it clear that a new ruleset targeting both elements should be created.

> To align the input boxes with each other, create a new ruleset that targets all `input` and `label` elements within an `.info` element and set the `display` property to `inline-block`.

Or

> To align the input boxes with each other, set the `display` property to `inline-block` for all `input` and `label` elements within an `.info` element by creating one new ruleset.

### System

N/A

**Comment by Sboonny** [comment]
I like the first suggestion more, I think we should go with it.

---

Side node: The lesson is about accessibility, and in a previous step, the campers add this selector.

```css
h1,
h2 {
  font-family: Verdana, Tahoma;
}
```

Maybe we should allow for that answer too, and add the text, as far as I know this challenge isn't about setting one ruleset.

**Comment by Sriparno08** [comment]
Hey maintainers, I have made the necessary changes! Have a look!

**Comment by TSKMaster** [comment]
`.info>label, .info>input {
  display: inline-block;
  
}

.info input {
  width: 50%;
  text-align: left;
}

.info label {
  width: 10%;
  min-width: 55px;
  text-align:right;
}`

**Comment by Sboonny** [comment]
Here is the file https://github.com/freeCodeCamp/freeCodeCamp/blob/0607f13adca9b427a5ebb7156e6f1bbadfcc6a4e/curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148da157cc0bd0d06df5c0a.md

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Meet16123** [comment]
use both selector together to use display:inline-block.

.info label, .info input {
  display: inline-block;
}

**Comment by spiritanand** [comment]
Is this issue open? Can you assign it to me if it is?

**Comment by Sboonny** [comment]
Only issues with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by kritikastar** [comment]
This is the solution of this quiz step-57
To align the input boxes with each other, create a new ruleset that targets all input and label elements within an .info element and set the display property to inline-block.

Also, align the label element's text to the right.



.info > input ,.info > label {
  width: 50%;
  text-align: left;
  display:inline-block;
}

.info > label {
  width: 10%;
  min-width: 55px;
  text-align:right;
}
