### ISSUE TITLE
This is valid css for this task

### ISSUE THREAD

**Issue by bmcorum** [FreeCodeCamp/FreeCodeCamp#4874]
Challenge [Waypoint: Style the HTML Body Element](http://www.freecodecamp.com/challenges/waypoint-style-the-html-body-element?solution=%3Cstyle%3E%0A%20%20body%20%7B%20%0A%20%20%20%20background-color%3A%20%23000%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body { 
    background-color: #000;
  }
</style>

```

**Comment by aseds** [comment]
it is solved if we type `black` instead of `#000`

**Comment by AkiraLaine** [comment]
I don't see what's wrong?

**Comment by ltegman** [comment]
The regex that controls the last test and checks if the css rule was properly closed was hard-coded to require the word `black` so it fails when you use a hex color.

**Comment by aseds** [comment]
i remember that in a later lesson it wouldn't accept `#000` instead of `#000000` too.

**Comment by DDaems** [comment]
Nothing wrong here:
>Give your body element the background-color **of** black. 
>!=
>Make your body elements background-color black.

Else rgb(0,0,0), rgba(0,0,0,1), ... would all be correct too.

**Comment by bmcorum** [comment]
I knew as soon as it marked it wrong that the problems are clearly expecting color names and not hex or RBG values. My current knowledge and experience (BSCS with 4+yrs work experience) is above the first several lessons so I must confess I was mostly attempting to break test cases (looking for valid solutions that would get flagged as wrong). I more than likely will look to help with updating and contributing to this project from a programming perspective in the future.

**Comment by SaintPeter** [comment]
@bmcorum https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Create-A-Pull-Request-for-Free-Code-Camp
