### ISSUE TITLE
TypeScript Migrate Cypress Tests

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#48753]
## Guidelines

Take a look at the [Codebase Best Practices](https://contribute.freecodecamp.org/#/codebase-best-practices) - **kebab-case file names**

### Do Not Ignore Linting, Unless **Absolutely** Necessary

We hope to leverage the type-safety that comes with TypeScript. So, do not ignore the compiler's warnings/errors. If you are stuck, feel free to reach out for help.

### Keeping Git History

Sometimes changing the file from `<filename>.js` -> `<filename>.ts?` causes the original file to be deleted, and a new one created, and other times the filename just changes - in terms of Git. Ideally, we want the file history to be preserved.

The best bet at achieving this is to:
1) Rename the file
2) Commit with the flag `--no-verify` to prevent husky from complaining about the errors
3) Refactor to TS for migration, in a separate commit.

**Note:** _Editors like VSCode are still likely to show you the file has been deleted and a new one created. If you use the CLI to `git add .`, then VSCode will show the file as renamed in stage_

## Files to be migrated

- [x] ./cypress/e2e/default/learn/challenges/multifile.js
- [x] ./cypress/e2e/default/learn/challenges/sass.js
- [x] ./cypress/e2e/default/learn/challenges/project-preview.js
- [x] ./cypress/e2e/default/learn/challenges/multifileCertProject.js
- [x] ./cypress/e2e/default/learn/challenges/failed-updates.js
- [ ] /cypress/e2e/default/learn/challenges/projects.js
- [x] ./cypress/e2e/default/learn/challenges/output.js
- [x] ./cypress/e2e/default/learn/coding-interview-prep/intro-page.js
- [x] ./cypress/e2e/default/learn/common-components/navbar.js
- [x] ./cypress/e2e/default/learn/common-components/searchBar.js
- [x] ./cypress/e2e/default/learn/common-components/editor.js
- [x] ./cypress/e2e/default/learn/common-components/footer.js
- [x] ./cypress/e2e/default/learn/common-components/helpButton.js
- [x] ./cypress/e2e/default/learn/donate/donation-block-completion-modal.js
- [x] ./cypress/e2e/default/learn/donate/donate-page-default.js
- [x] ./cypress/e2e/default/learn/donate/donate-page-donor.js
- [x] ./cypress/e2e/default/learn/header/universal-navigation.js
- [ ] ./cypress/e2e/default/learn/redirects/heading-challenge.js
- [x] ./cypress/e2e/default/learn/redirects/es6-to-basic-javascript.js
- [x] ./cypress/e2e/default/learn/redirects/breadcrumbs.js
- [x] ./cypress/e2e/default/learn/responsive-web-design/intro-page.js
- [x] ./cypress/e2e/default/learn/responsive-web-design/basic-css/index.js
- [ ] ./cypress/e2e/default/learn/responsive-web-design/show-cert-from-superblock.js
- [x] ./cypress/e2e/default/learn/challenge-hot-keys.js
- [x] ./cypress/e2e/default/learn/index.js
- [ ] ./cypress/e2e/default/legacy/redirects/challenges.js
- [ ] ./cypress/e2e/default/legacy/redirects/adding-development.js
- [ ] ./cypress/e2e/default/settings/email-change.js
- [x] ./cypress/e2e/default/settings/user-token.js
- [x] ./cypress/e2e/default/settings/username-change.js
- [x] ./cypress/e2e/default/settings/certifications.js
- [x] ./cypress/e2e/default/settings/image-picture-check.js
- [x] ./cypress/e2e/default/settings/settings.js
- [x] ./cypress/e2e/default/user/report-user.js
- [x] ./cypress/e2e/default/user/privacy-terms.js
- [x] ./cypress/e2e/default/user/certifications.js
- [x] ./cypress/e2e/default/landing.js
- [ ] ./cypress/e2e/default/ShowCertification.js
- [ ] ./cypress/e2e/default/tags.js
- [x] ./cypress/e2e/default/top-contributor.js
- [ ] ./cypress/e2e/mobile-learn/test-challenges.js
- [ ] ./cypress/e2e/third-party/donate-page.js
- [ ] ./cypress/plugins/index.js

**Comment by a2937** [comment]
Can I convert some of the files?

**Comment by ShaunSHamilton** [comment]
@a2937 
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by a2937** [comment]
I'll try again if you'll allow me.

**Comment by a2937** [comment]
I forgot to link this issue when I made the pull requests.

https://github.com/freeCodeCamp/freeCodeCamp/pull/49001

https://github.com/freeCodeCamp/freeCodeCamp/pull/48988

**Comment by a2937** [comment]
I have an issue regarding trying to convert sass.js.

Eslint gives me this report for the following lines: "Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead." 

https://github.com/freeCodeCamp/freeCodeCamp/blob/569fc3196b2d3a9a96706f14b13bda48388d2c9a/cypress/e2e/default/learn/challenges/sass.js#L5

I'm a little bit confused regarding why this is happening and how to solve it. I mean maybe it has to do with the global cy variable being used in a call inside the return statement. I can confirm the test works absolutely amazingly however.
