### ISSUE TITLE
Emmet not functioning

### ISSUE THREAD

**Issue by BKinahan** [FreeCodeCamp/FreeCodeCamp#4875]
Emmet auto-complete isn't functioning in the code editor. Everything *seems* to be there in create-editor.js but something must be going wrong.

**Comment by ltegman** [comment]
Thanks for the report -- I can confirm this is the case.

**Comment by ltegman** [comment]
Looks like Codemirror used to include this addon but it's now a separate download. I've put in a PR to add it back :smile:

**Comment by smiller171** [comment]
:+1:
