### ISSUE TITLE
Unclear Penguin Hints Step 12

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#48767]
### Describe the Issue

We have a few issues with hint clarity here.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-12

### Your code

Bad Code:

```
.penguin {
  width: 300px;
  height: 300px;
  margin-top: 75px;
}
```

Hint:

> You should give `.penguin` a margin of `auto`, but found ` `.

Fix:

This is accurate but unclear. Should we clearly state here that no `margin` property was found?

---

Bad Code:

```
.penguin {
  width: 300px;
  height: 300px;
  margin-top: 75px;
  margin: auto;
}
```

Hint:

> You should give `.penguin` a `margin-top` of `75px`, but found `auto`.

Fix:

This is also accurate but unclear. Should we note that order in CSS matters?

### Expected behavior

Clear error messages can help the camper better.

### System

All

**Comment by ShaunSHamilton** [comment]
> Should we clearly state here that no margin property was found?

We can change this to return `undefined` (probably not clear for those who have not done any JS). But, we can put anything we want there (it will always be within `code` tags, though):

> You should give `.penguin` a `margin` of `auto`, but found `""`.

---

> Should we note that order in CSS matters?

I would not. At this point in the curriculum, Campers have covered multiple lessons involving (if not mentioning) ordering.

**Comment by jeremylt** [comment]
Yeah, the penguin is pretty far along.

Is there a way to change the handling of the first point for all challenges?

**Comment by ShaunSHamilton** [comment]
> Is there a way to change the handling of the first point for all challenges?

Yes, but it would be an unwieldy hard-coding. Currently, as you said:
> This is accurate

So, I would not forcefully change it for all.
