### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by manurudh** [FreeCodeCamp/FreeCodeCamp#4876]
Challenge [Bonfire: Diff Two Arrays](http://www.freecodecamp.com/challenges/bonfire-diff-two-arrays) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I get the following error upon page open:

TypeError: undefined is not a function (evaluating 'Object.assign({code:r.removeComments(e),tests:r.tests.slice()})')

Trying to run tests results in the same error above. This error is not unique to this exercise, and pervades everything. Please address. Thanks!

**Comment by ltegman** [comment]
Closing as a duplcate of #4873.

Thanks and happy coding!
