### ISSUE TITLE
Refactor modern-challenge/project submission

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#48770]
The `submitModern` function https://github.com/freeCodeCamp/freeCodeCamp/blob/683c1806599821e0b4def89ae7ba47ee97d1865a/client/src/templates/Challenges/redux/completion-epic.js#L60

is a little convoluted. It would be good to split that into smaller, focused functions that each handle each special case (i.e. multiple choice questions, classic challenges with tests and so on).

Also, it does not seem right to use the `/modern-challenge-completed` endpoint to submit multifile cert projects and JavaScript projects.

**Comment by ShaunSHamilton** [comment]
> Also, it does not seem right to use the `/modern-challenge-completed` endpoint to submit multifile cert projects and JavaScript projects.

Why? Their structure is the same.

**Comment by ojeytonwilliams** [comment]
Their use is different, though. In general mixing up challenges and projects doesn't feel great.

**Comment by Sboonny** [comment]
Can we label this help wanted? there seems no push back for this 🤔
