### ISSUE TITLE
Learning SQL, problem to load the “starting virtual server”

### ISSUE THREAD

**Issue by gilles4** [freeCodeCamp/freeCodeCamp#48788]
### Describe the Issue

In the “learn SQL by Building a Student Database: Part 1”

When Loading remote environment :  I couldn't finished to load the last part; “starting virtual server” and i don't know why. 
   
Checking permissions   ok 
Preparing Virtual Machine  ok
Pulling source image  ok
Reserving resources  ok
Building Remote Environment   ok
Starting virtual server   no ok
 
can't achieve virtual server loading.  Why ? 

Thank you for any advice. 
 

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-sql-by-building-a-student-database-part-1/build-a-student-database-part-1

### Steps to Reproduce

1. Go to ' https://www.freecodecamp.org/learn/"
2. Click on 'Relational Database (Beta)'
3. Scroll down to 'learn SQL by Building a Student Database: Part 1'

### Expected behavior

create the virtual Linux server machine.

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Brave]
- Version: [v1.46.144 (Dec 14, 2022)]

**Comment by moT01** [comment]
Thank you for reporting @gilles4. There's been a few reports of this happening in the last few days. This is a reoccurring issue, although more and more infrequently - we have a [different issue](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/50) where we track reports of this. The recent comments, at the time of writing this, suggest that it should be working again. I would give it another try. If you are still having problems, you can comment on that issue. Thanks and happy coding 🎉
