### ISSUE TITLE
Requesting rewrite of first sentence in step 32 of the new JS course build an rpg 

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48787]
### Describe the Issue

The first sentence of step32 of the new JS course learn-basic-javascript-by-building-a-role-playing-game states the following:

`Use <code>querySelector()</code> to get the other two button elements, using their <code>#button2</code> and <code>#button3</code> <code>id</code>s.`

Attempting to translate the last half of this sentence in Arabic is a challenge because the order of the code elements cannot be changed and in Arabic the phrasing as-is would be nonsensical.
The closest I could get in my attempt would have to be something like "...using <code>#button2</code> and <code>#button3</code> which are the values of their <code>id</code> attributes."

I can do this, but the overall effect is almost to obfuscate what it is we are actually trying to say because of the extreme wordiness that I would resort to.

I, therefore, propose a slight rewording and re-organization for this sentence which is to use :

`Use <code>querySelector()</code> to get the other two <code>button</code> elements using their <code>id</code>s: <code>button2</code> and <code>button3</code>.`

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62fc20387ef88d1d1998aac5.md

### Your code

```

```

### Expected behavior

My suggestion is to rewrite to this:
`Use <code>querySelector()</code> to get the other two <code>button</code> elements using their <code>id</code>s: <code>button2</code> and <code>button3</code>.`

This separates the attribute name 'id' from the values to follow and allows for easier translation.

### System

N/A

**Comment by Sboonny** [comment]
I asked Dario and he said the suggestion is valid, so I am opening this for contribution.

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Dario-DC** [comment]
Sorry @Sboonny I think there is an additional issue with this sentence. The ids should be indicated without `#` before the id name. `button1` is the id; `#button1` is the id selector

**Comment by jeremylt** [comment]
We have a few places where that's unclean in our course content - I agree with dropping that #

**Comment by hbar1st** [comment]
I have removed the hashtags from the expected string.
