### ISSUE TITLE
Something wrong with this waypoint???

### ISSUE THREAD

**Issue by BlackThoughtz** [FreeCodeCamp/FreeCodeCamp#4879]
Challenge [Waypoint: Manipulate Arrays With shift](http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift?solution=var%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%5B%22cat%22%5D%5D%3B%0A%0AremovedFromOurArray%20%3D%20ourArray.shift()%3B%20%2F%2F%20removedFromOurArray%20now%20equals%20%22Stimpson%22%20and%20ourArray%20now%20equals%20%5B%22J%22%2C%20%5B%22cat%22%5D%5D.%0A%0Avar%20myArray%20%3D%20%5B%22John%22%2C%2023%2C%20%5B%22dog%22%2C%203%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AremovedFromMyArray%20%3D%20myArray.shift()%3B%0A%0Avar%20removedFromMyArray%20%3D%20%5B%22John%22%5D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%0A(function(y%2C%20z)%7Breturn%20%27myArray%20%3D%20%27%20%2B%20JSON.stringify(y)%20%2B%20%27%20%26%20removedFromMyArray%20%3D%20%27%20%2B%20JSON.stringify(z)%3B%7D)(myArray%2C%20removedFromMyArray)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = ["Stimpson", "J", ["cat"]];

removedFromOurArray = ourArray.shift(); // removedFromOurArray now equals "Stimpson" and ourArray now equals ["J", ["cat"]].

var myArray = ["John", 23, ["dog", 3]];

// Only change code below this line.

removedFromMyArray = myArray.shift();

var removedFromMyArray = ["John"]

// Only change code above this line.


(function(y, z){return 'myArray = ' + JSON.stringify(y) + ' & removedFromMyArray = ' + JSON.stringify(z);})(myArray, removedFromMyArray);

```

It doesn't have a pass or fail mechanic that other waypoints have.

**Comment by ltegman** [comment]
This has been fixed by PR #4870 and is pending deployment to the production website.

Thanks and happy coding!
