### ISSUE TITLE
New JS course (build an rpg): should "Hello World" be enclosed in backticks

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48806]
### Describe the Issue

Should the string "Hello World" be enclosed in backticks in order for the translators to know that it should not be translated?
Specific strings that I noticed this issue in below:

15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c8bf3980c14c438d2aed.md:
For now, make your `goStore` function output the message `Going to store.` to the console. For example, here is a function that outputs the message "Hello World".

15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c0ab883fd9435cd5c518.md:
Comments allow you to add notes to your code. In JavaScript, single-line comments can be written with `//` and multi-line comments can be written with `/*` and `*/`. For example, here are single and multi-line comments that say "Hello World":

### Affected Page

as described in main description

### Your code

```

```

### Expected behavior

If the string "Hello World" should not be translated, then perhaps it should be enclosed in backticks.

### System

N/A

**Comment by saqib-masood** [comment]
**assign this to me plz**

**Comment by Bl1xvan** [comment]
What do you mean by "translated"?

**Comment by Sboonny** [comment]
Here is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c8bf3980c14c438d2aed.md

---

To fix this issue replace the quotes with backtick \`, so it will be `Hello World`

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Sboonny** [comment]
@Bl1xvan, don't worry about it, it's something related to translation effort, you can find more on Quincy's articles or contribution guide
