### ISSUE TITLE
Tab names are different between desktop layout and mobile layout

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#48807]
### Describe the Issue

In the certification project pages, the tab on the left is "Instructions".
However, if you resize the browser and the page switches to the mobile layout, the tab name changes to "Info".

The "Console" on the desktop layout changes to "Tests" too.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form and other certification projects with built in editor

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form
2. Resize the browser

### Expected behavior

Use the same name for the same content.

### Screenshots

![tab_name](https://user-images.githubusercontent.com/25644062/208709143-2d77c647-53f4-4fb6-af73-f7c89fc9b278.png)

![tab_name_console](https://user-images.githubusercontent.com/25644062/208711362-915401b2-7e0c-445f-ae6e-74206c9cff03.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 108.0.5359.125

**Comment by bbsmooth** [comment]
Technically, I don't think this is a WCAG failure. [Success Criterion 3.2.4](https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification.html) does address consistent identification of functional components. In this scenario, in wide view they are HTML buttons but in narrow view they are tabs, so technically they are not the same component and thus don't fall under 3.2.4.

But for usability I would tend to agree that it would be best if they could use the same terminology since they basically do the same thing.

**Comment by Sboonny** [comment]
We can use "Console" for both mobile and desktop. Do we use "info" for the desktop layout and call it `info.md`?

**Comment by Sboonny** [comment]
To solve this issue: use "Console" and "Instructions" for both layout.

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by ShaunSHamilton** [comment]
We might want to keep in mind that `Instructions` is much longer than `Info`. We do not have much real-estate on mobile.

**Comment by Sboonny** [comment]
Here are words that I can think of are "details", "manual", "guide", and "briefing". 💭 

Is any of them good enough, or do we change the console for now and come back for "instructions" later?

**Comment by ShaunSHamilton** [comment]
My initial thought is: keep everything consistent, and just use the current mobile-naming for desktop as well.

However, I am not entirely happy with the word `Info` for what it denotes. `Content` might be one option, but I also like your suggestion of `Story`.

**Comment by Sboonny** [comment]
I find `Content` or `Context` interesting 🤔.

I vote for `Story` too, if no one else has issue with it, we can go with it, otherwise we go with `Content`.

**Comment by moT01** [comment]
We decided to go with the desktop terms for both, "Instructions" and "Console". And we are going to make another issue about improving the mobile UX to potentially use icons or another solution.

**Comment by DiegoCascavita** [comment]
I think that `info` should remain for responsive design issues on cell phones and `console` since it is the appropriate term when the student goes to vsCode or another IDE 😊
