### ISSUE TITLE
Typos in step 66 of new JS RBG project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48825]
**Describe the bug**
The step has 2 hints which tell the camper to target the wrong button.

Here are the strings.

> You should set the `button1.onclick` property to be the second element of the `button functions` property of the `location` argument.

> You should set the `button2.onclick` property to be the third element of the `button functions` property of the `location` argument.

They should be changed to:

> You should set the `button1.onclick` property to be the first element of the `button functions` property of the `location` argument.

> You should set the `button2.onclick` property to be the second element of the `button functions` property of the `location` argument.

Here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/e451a54d250168e6bd23bde5c2a1426cc4714bf6/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8c1154d3ae11aee80353f.md?plain=1

Pointed out in Crowdin: https://freecodecamp.crowdin.com/translate/690087755819f2f67b26dbee3be0eb53/34753/en-id?filter=basic&value=3#q=1221605

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by arantebw** [comment]
@Sboonny can I work on this one?
