### ISSUE TITLE
Missing hashtag(s) in step 45 of the new js course (build an rpg)

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48822]
### Describe the Issue

Step 45 of the new build an rpg in JS course seems to be missing multiple hashtags. For eg: The following seems to be missing a hashtag in front of the word text (the one in backticks).

Now you need to modify your display text. Change the `innerText` of the `text` to be `You enter the store.`.

The word text in backticks seems to be referring to an element whose id is text. So I believe it should use a hashtag as in #text.

If this is correct, then there are multiple places to be fixed in this step. 

### Affected Page

curriculum/challenges/arabic/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a7bfabe119461eb13ccbd6.md

### Your code

```

```

### Expected behavior

All references to an element whose id is text should be clarified either with a hashtag in front of the id value or by explicitly referring to the text element.

### System

N/A

**Comment by ShaunSHamilton** [comment]
The word `text` is referring to the `text` variable. As such, I do not believe it should be changed to say `#text`.

---

Expanded: _"Change the `innerText` of the `#text` to be `You enter the store.`."_ suggests the HTML should be altered. However, the expectation is the `innerText` property of the `text` variable (object) be set to "...".

---

I suggest the text be changed to:
> Change the `innerText` of the `text` variable to be `You enter the store.`.

Although, I would also be fine with any of:
a) ...`text` object ...
b) ... of `text` to be ...

**Comment by Sriparno08** [comment]
Hey @ShaunSHamilton, shall I go ahead and open a PR with your suggested changes?

**Comment by ShaunSHamilton** [comment]
@Sriparno08 We are still discussing the changes (if any) we might expect here. Once the author, or more contributors chime in about the suggestions, we will open this up for contribution as indicated by either the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label.

**Comment by Sriparno08** [comment]
Alright, @ShaunSHamilton 👍

**Comment by hbar1st** [comment]
hi Shaun, the property 'innerText' is a property of the -variable- or the -element- ?
My understanding is when we teach concepts like innerText or innerHTML we are teaching properties that belong to the elements we retrieve from the querySelector. (these are all properties that we manipulate in the DOM, not in the javascript variable?)

Another way to test this is to say: let's pretend the code was:
`let v = document.querySelector("#text");`

Then would you still say "change the innerText of the variable v"? or would you say "change the innerText of the #text element?"

**Comment by ShaunSHamilton** [comment]
> hi Shaun, the property 'innerText' is a property of the -variable- or the -element- ?

`innerText` is a property of a JavaScript object. That is, we are asking Campers to make use of a JavaScript object. Previously, we defined the variable `text`.

---

In my mind, we can go two ways with this:
1) Have an explicit hint (what we usually do) whereby we tell Campers what to use/change/do
  - If they need to do something to the `<element id="text">`, say `#text`.
  - If they need to do something to the variable `text`, say `text`.
2) Have a vague (actual) hint, which I would phrase:
  - "Set the `#text` element's text content "as rendered" to be `You enter the store.`." [^1]

The difference being:
1) Campers know their code needs to involve the `text` variable, and somehow use a property named `innerText`
2) Campers know what to change, but need to think more in order to know to use `text.innerText = ...`

[^1]: https://html.spec.whatwg.org/#the-innertext-idl-attribute

**Comment by hbar1st** [comment]
I think I'm beginning to understand what I didn't understand before. I was thinking along the lines of 'innerText' being a reference to what will actually change on the page versus the more literal innerText property of the object stored in the variable text.
Part of the confusion may be that I haven't seen all the steps in order. (maybe if I read them all in order it will be obvious)

In other steps the phrasing seems clearer such as when they say:
`You should set the <code>onclick</code> property of <code>button2</code> to be <code>buyWeapon</code>.`

Somehow the word 'property' here made it clearer to me.

Can we go with something similar for eg:
```
Now you need to modify your display text. Change the `innerText` property of the `text` to be `You enter the store.`.
```
ie. adding the word property as needed to affected sentences?

**Comment by ShaunSHamilton** [comment]
> ie. adding the word property as needed to affected sentences?

I would be happy with that. However, I do not like the _"of the `text` ..."_. We should add something like _"of the `text` variable"_

**Comment by hbar1st** [comment]
Okay I understand that.

"... property of the `text` variable to be ..."

Or do it like the other sentence I mentioned which doesn't classify button1 at all. 

"... property of `text` to be ..."

**Comment by ShaunSHamilton** [comment]
I prefer fewer words. So, let us go with:

> Now you need to modify your display text. Change the `innerText` property of `text` to be `You enter the store.`.

@Sriparno08 If you would like to update your PR with the agreed-upon changes? We can see what other reviewers think on the PR.

**Comment by Sriparno08** [comment]
Sure! I am going ahead!
