### ISSUE TITLE
error: plugin failed to initialize free code camp

### ISSUE THREAD

**Issue by larryste1** [FreeCodeCamp/FreeCodeCamp#4882]
Can't run code because of this error error: plugin failed to initialize  it is showing in the lower left corner.  Tried different browsers, computer, and devices same error.  Have a really slow internet connection

**Comment by ltegman** [comment]
Thanks for the report and connection speed detail. I am able to repro this by going to any challenge in Chrome with the devtools set to disable caching and throttling the network connection to 750KB/s or less.

**Comment by larryste1** [comment]
Thanks I was hoping it wouldn't be the speed.

Larry

**Comment by BerkeleyTrue** [comment]
Unfortunately, the we use web worker that pulls down a script from our servers. We have a timeout to check if the script has locked up. I have a PR coming up that will remove this dependency and should alleviate some of this pain.
