### ISSUE TITLE
Button padding on mobile device is too much

### ISSUE THREAD

**Issue by devvsakib** [freeCodeCamp/freeCodeCamp#48848]
### Describe the Issue

left right padding is too much for mobile view and font size is bigger
![image](https://user-images.githubusercontent.com/88339569/209443762-3d574678-82af-4182-9116-1aa5ef1438a7.png)

we can adjust padding and font size for small device
demo:
![image](https://user-images.githubusercontent.com/88339569/209443823-0851a910-5dba-4192-a7b7-f5455216acc8.png)

### Affected Page

https://contribute.freecodecamp.org/

### Steps to Reproduce

set left right padding 1.6rem;
and font size 16/18px

### Expected behavior

if font size 16px+
![image](https://user-images.githubusercontent.com/88339569/209443866-5039a4c9-7d20-4ff6-8e13-238d18b0d61b.png)

if font-size 15px
![image](https://user-images.githubusercontent.com/88339569/209443878-52346d46-fbb6-4f67-8294-5fd59f73b9a4.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by devvsakib** [comment]
please assign me

**Comment by cybraia** [comment]
Hi, I would like to work on this. Please assign it to me if the issue hasn't been resolved.

**Comment by devvsakib** [comment]
@cybraia  i created this issue to work on it🥲

**Comment by emmanuelodii** [comment]
@media screen (min-width: 768px) and (min-width: 1200px) { 
 // if padding == 2rems,
} // For Laptops, Tablets
@media only screen and (max-width: 767px) {
padding == (2 - 2/3) rems
} // For mobile devices.
