### ISSUE TITLE
No matter what and how I write it, it still says there's an error in my code.

### ISSUE THREAD

**Issue by serialki11er** [FreeCodeCamp/FreeCodeCamp#4885]
Challenge [Waypoint: Use Clockwise Notation to Specify the Padding of an Element](http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-padding-of-an-element?solution=%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2020px%2040px%2020px%2040px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3Ared%3B%0A%20%20%20%20padding%3A%2020px%2040px%2020px%2040px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2040px%2020px%2020px%2040px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 20px 40px 20px 40px;
  }
  
  .red-box {
    background-color:red;
    padding: 20px 40px 20px 40px;
  }

  .green-box {
    background-color: green;
    padding: 40px 20px 20px 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

What am I doing wrong???

**Comment by ltegman** [comment]
This code passes for me just fine, but there appears to be a bug in how it runs in Firefox. We have a PR open (#4884) that looks like it will solve this when it is accepted :D

**Comment by serialki11er** [comment]
Was using Weasel on Linux but yeah switching to Chrome solved the problem. Would be nice if it would run smoothly with Fox/Weasel in the future though, thanks :)

**Comment by manoaj** [comment]
I'm also having this issue in Firefox, if we click the "Run" button continuously the code passed and go to next problem. It works only for some problems. try it yourselves.
