### ISSUE TITLE
Unexpected character popup in the code.

### ISSUE THREAD

**Issue by slayeh17** [freeCodeCamp/freeCodeCamp#48857]
### Describe the Issue

While I was writing code for HTML on my phone every time I finished a tag for example ```<head>``` after hitting space or enter it becomes ```<hhead>``` or ```<headd>```, or ```<html>``` becomes ```<hhtml>``` on its own.

Things I've tried: 
<ul>
<li>Changed the keyboard from Microsoft's to Google's</li>
<li>Stopped auto-correct, auto-space, auto-predict, auto-punctuation on both keyboards</li>
<li>Changed browsers</li>
</ul>

<h4>***Can someone please try writing code on freeCodeCamp on their phone just to confirm my issue, as I've only faced this on my phone so far and haven't checked the issue on any other phones.</h4>

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-1

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/'
2. Click on '(New) Responsive Web Design'
3. Scroll down to any of the projects
4. Start writing something from your phone
5. See error

### Expected behavior

Words should not show unexpected characters pop-up after a space or enter.

### System

- Device: [POCO M2 Pro]
- OS: [Android 12]
- Browser: [Chrome, Brave]
- Version: [12]

**Comment by naomi-lgbt** [comment]
Hey there,

We're hard at work improving the mobile experience, but for now the best fix is https://www.freecodecamp.org/news/freecodecamp-mobile/
