### ISSUE TITLE
Unecessary opinion and innaccuracy surrounding notes about classes

### ISSUE THREAD

**Issue by EthanStandel** [freeCodeCamp/freeCodeCamp#48856]
### Describe the Issue

On the topic of ES6 classes in JavaScript, the section in question reads this sentence at the very top of the article:

> It should be noted that the class syntax is just syntax, and not a full-fledged class-based implementation of an object-oriented paradigm, unlike in languages such as Java, Python, Ruby, etc.

This is entirely uneccesary, confusing to beginners, and incorrect by any existing definition of a class. While ES6 classes are certainly a syntax sugar for prototypal inheritence, it doesn't make them "not a full-fledged class-based implementation of an object-oriented paradigm." ES6 provides a syntax which makes ugly prototypal inheritence _look like_ a traditional OOP implementation of classes but it already _behaved like_ classes. This makes it a true class based implementation because it allows for the development & behavior of applications using object-oriented-paradigms with classes and all the features you would expect. And for any possible definition I could find of what a class is, it is the programatic behavior of using it that defines it, not any kind of underlying implementation.

This is especially problematic when Python is listed among the languages that _do_ support a "full fledged class-based implementation." Python is also a runtime scripting language that is dynamically typed, with classes that are also entirely mutable, similar to JavaScript. So if someone happens to know Python then it is _extra_ confusing.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function.md

### Steps to Reproduce

I don't know why the "Steps to Reproduce" section is here. This should be the template for a "content" error, not a challenge error.

### Recommended fix or suggestions

Just remove this sentence as it does nothing to help anyone's understanding of programming or features of JavaScript as a language. It may be helpful to have a section about prototypal inheritence here and that syntax instead before showing the class based syntax so the student understands the underlying implementation. However, I don't feel that an extra section is nearly as valuable as it would be to just  remove this sentence.

**Comment by Sembauke** [comment]
The quote is necessary because it sets the context for understanding the nature of classes in JavaScript. It is important to understand that the class syntax in JavaScript is just syntax sugar, and does not provide the full range of features and behaviors that are characteristic of true class-based object-oriented languages such as Java, Python, and Ruby.

In other words, the class syntax in JavaScript is just a way of writing code that looks like it is using a class-based object-oriented paradigm, but under the hood it is still using the prototype-based model of inheritance that is the fundamental basis of JavaScript. This is an important distinction to be aware of, because it can affect how you write and think about code when using classes in JavaScript.

**Comment by ShaunSHamilton** [comment]
Thank you for opening this issue.

I would be happy removing that sentence.

---

> So if someone happens to know Python then it is extra confusing.

What I take from the sentence is Python is an Object-Oriented Programming language, unlike JavaScript. However, I have no understanding about what makes a language one of another 🤷‍♂️

**Comment by EthanStandel** [comment]
@ShaunSHamilton 

> What I take from the sentence is Python is an Object-Oriented Programming language, unlike JavaScript. However, I have no understanding about what makes a language one of another 🤷‍♂️

If you're referring to what I said in the quote above, then what I meant was that Python classes operate very similarly to JavaScript prototypes/classes. If someone wanted to say that part of what makes a class-a-class would be OOP specific concepts like abstract classes or interfaces... well Python doesn't have those either. If someone wanted to say that what makes a class-a-class was it's compile time immutability... well Python doesn't have that either.

Wikipedia has two articles that compare and contrast [class-based programming](https://en.wikipedia.org/wiki/Class-based_programming) and [prototype-based programming](https://en.wikipedia.org/wiki/Prototype-based_programming). And in the prototype topic, they explain the implementation details of inheritance in prototypal languages and then they compare it with this statement:

> Compare to the [class-based](https://en.wikipedia.org/wiki/Class-based_programming) paradigm, where a "fruit" class would be extended by a "banana" class.

However, this once again recurses into more definitions because for what I can find, the concept of "extension" is a reference to syntax and to mental models of behavior. If the _implementation_ of the extension behavior happens to be prototypal, that seems irrelevant to if it's actual true "extension."

I get that this topic & argument becomes really muddy in deep-definition-hell. However, that kind of lends to my point that the article just shouldn't make a claim here that JavaScript classes are "not a full-fledged class-based implementation of an object-oriented paradigm." From any definition I can find, classes are defined mostly by a programatic behavior in-utilization and partially by the right syntax. Both of which JavaScript now has.

**Comment by Sboonny** [comment]
to solve this issue, follow EthanStandel suggestion and remove the sentence.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by EthanStandel** [comment]
Thank you for opening the PR @a2937, I have been bogged down with with work this month and haven't been very available to the OSS community.
