### ISSUE TITLE
New js course string describing Object key-value pairs uses unnecessary backticks?

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48859]
### Describe the Issue

The following string in the new js course (build an rpg) used code elements for words that are not actual code. I think this should be fixed. What do you guys think? `Object <dfn>properties</dfn> are written as <code>key: value</code> pairs, where <code>key</code> is the name of the property (or the key), and <code>value</code> is the value that property holds.`

### Affected Page

curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8aa98a8289d0a698eee1d.md

### Your code

```

```

### Expected behavior

Backticks should be used for code, not for descriptions of code.

### System

-N/A

### Additional context

The presence of the backticks around the descriptive words prevents translation.

**Comment by naomi-lgbt** [comment]
I disagree here. `key: value` is a specific syntax definition, and the sentence is written in a way that includes the terms as translatable words.

**Comment by hbar1st** [comment]
It is describing a syntax sure. But there is no advantage to not translating those words as they aren't code?
We can still describe the syntax without having to use "key" and "value"?
Would using some regular double quotes still work for the English text?

**Comment by ShaunSHamilton** [comment]
I could go either way here, because we are just wanting to teach [Object Literal Initialisation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer).

However, it is important to note the significance of the words `key`/`keys` and `value`/`values` as they are common within programming. E.g. `Object.keys()` and `Object.values()`

**Comment by hbar1st** [comment]
Okay, I do see Naomi's point in that there is enough to this sentence that when translating we can explain the words key and value adequately, especially given Shaun's comment about adding common programming terms to the learner's lexicon. I will close this request. Thanks for your valuable inputs.
