### ISSUE TITLE
This challenge asks that the code strip punctuation and numbers, but then one of the tests to pass is entirely punctuation and numbers. 

### ISSUE THREAD

**Issue by caseyjohnston** [FreeCodeCamp/FreeCodeCamp#4886]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes?solution=function%20palindrome(str)%20%7B%0A%20%20var%20strStrip%20%3D%20str.toLowerCase().replace(%2F%5CW%2Fgi%2C%20%27%27)%3B%0A%20%20var%20strReverse%20%3D%20strStrip.split(%27%27).reverse().join(%27%27)%3B%0A%20%20if%20(strReverse%20%3D%3D%3D%20strStrip)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  var strStrip = str.toLowerCase().replace(/\W/gi, '');
  var strReverse = strStrip.split('').reverse().join('');
  if (strReverse === strStrip) {
    return true;
  }
  else {
    return false;
  }
  
}



palindrome("eye");

```

**Comment by ltegman** [comment]
The challenge does not ask you to remove numbers, so you would be left with `0000`. Closing as not an issue.

Thanks and happy coding!
