### ISSUE TITLE
Step 62 of new js course (build and rpg) is missing some backticks

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48870]
### Describe the Issue

Step 62’s instructions say:
The `locations` array contains two locations: the town square and the store.

The words “town square” and “store” should be in backticks as they are code and must not be translated.

Also in this sentence:
Currently you are passing that entire array into the update functions. 

The word update should be in backticks as it is the name of a function.
And incidentally the word functions should be singular not plural.

### Affected Page

curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8b6536156c51500739b41.md

### Your code

```

```

### Expected behavior

Use backticks to surround the words that are part of the code.
(and one grammar issue in this step)

### System

N/A

**Comment by marksist300** [comment]
I agree, I think those proposed changes improve the description of the challenge. I've submitted a PR with the specified changes 🙂
