### ISSUE TITLE
share to github gist

### ISSUE THREAD

**Issue by shadowsyntax** [FreeCodeCamp/FreeCodeCamp#4887]
After successful completion of a bonfire. The option to share solution to github gist doesn't work. This just opens a blank new tab.

**Comment by ltegman** [comment]
This has been resolved by PR #4851 and the code is pending deployment to production.

**Comment by TridevGuha** [comment]
I can not find the option to share freecodecamp solutions to git hub  as a new repository. Any guide would be appreciated.

**Comment by ltegman** [comment]
@TridevGuha This was removed as feature bloat. If you want your code in a gist you'll need to copy and paste it manually.

**Comment by TridevGuha** [comment]
okay thanks :) @Itegman
