### ISSUE TITLE
Clarify instructions and hints in step 61 of the cat photo app 

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48871]
### Describe the Issue

For step 61 of the cat photo app <https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-61>, since a lot of people don't read the instruction extra carefully to detect that the checked attribute is requested in 2 places, can we make it more obvious by writing the instruction as follows: Make both the first radio button and the first checkbox selected by default. (That is add the word “both” to the instruction)

In addition the hints can be clarified further by adding the id names to them as per @naomi-lgbt ‘s suggestion (via discord discussion)
For eg. Instead of “ The first radio button is missing the `checked` attribute.” use “ The first radio button (#indoor) is missing the `checked` attribute.”

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-61

### Your code

```

```

### Expected behavior

Update the instruction and hints to be more direct as per the suggestions above.

### System

N/A

### Additional context

File relative path: curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804e5.md

**Comment by naomi-lgbt** [comment]
> For eg. Instead of “ The first radio button is missing the checked attribute.” use “ The first radio button (#indoor) is missing the checked attribute.”

I would do something like:

> Your first radio button with the `id` set to `indoor` should have the `checked` attribute.

**Comment by Sboonny** [comment]
to solve the issue, apply Naomi suggestion

--- 

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
