### ISSUE TITLE
Can't Edit Code

### ISSUE THREAD

**Issue by SarahDunlap** [FreeCodeCamp/FreeCodeCamp#4888]
Hello! I was working on this Bonfire in Chrome and now the page is not responsive.  I tried restarting my computer just in case and I am still not able to edit anything or even click the bug button. I tried in other browsers and it says plugin not responsive. I am able to work on other Bonfires. I just can't work on this one.

Challenge [Bonfire: Missing letters](http://www.freecodecamp.com/challenges/bonfire-missing-letters?solution=function%20fearNotLetter(str)%20%7B%0A%20%20return%20str%3B%0A%7D%0A%0AfearNotLetter(%22abce%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 

Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function fearNotLetter(str) {
  return str;
}

fearNotLetter("abce");

```

**Comment by DDaems** [comment]
>browsers and it says plugin not responsive.

Could you please provide a screenshot of this error, i am unable to reproduce this.

**Comment by SarahDunlap** [comment]
![codecamp](https://cloud.githubusercontent.com/assets/12238386/11535559/03872744-98da-11e5-97f9-db425c52267c.PNG)

**Comment by bugron** [comment]
@SarahDunlap your code, please.

**Comment by SarahDunlap** [comment]
![github2](https://cloud.githubusercontent.com/assets/12238386/11535661/6e35ead0-98da-11e5-8269-df1c9f337ceb.PNG)

**Comment by SarahDunlap** [comment]
Infinite loop

**Comment by bugron** [comment]
Copy-paste here the link in address bar so we can test the code.

**Comment by SarahDunlap** [comment]
http://www.freecodecamp.com/challenges/bonfire-missing-letters

**Comment by bugron** [comment]
The whole link with `?solution=....` part too.

**Comment by SarahDunlap** [comment]
I haven't completed it. I don't know where I could get that link from.

**Comment by bugron** [comment]
No matter you've completed it or not, can't you see the link in your address bar like this?
![](http://i.imgur.com/xYuDVll.png)
If not (which is almost not possible), try changing some code in the editor. If nothing helps, just copy-paste here you code (text, **not** screenshot).

**Comment by SarahDunlap** [comment]
No it is just the one I posted eariler

**Comment by SarahDunlap** [comment]
I can't copy and paste or click on anything or change anything.

**Comment by SarahDunlap** [comment]
I cleared the cache I can edit again.

**Comment by DDaems** [comment]
>If all letters are present in the range, return undefined.

Your code gets in a infinite loop because firstLetterFound is always false and therefor the while loop condition is allways true here. Your code fails to return or change the boolean when a empty string '' or a string that does not start with a 'a' is given.

I have altered and commented your code a bit to help you understand and explain why this is happening, hopefully it is of any help to you.
```
  while(firstLetterFound === false){
    if(alphabet[count] === str[0]){   // This never fires, because str[0] isn't nesscensary 'a'
      for(var i = 0; i < str.length; i++)
        if (alphabet[count + 1] !== str[i]){
            return alphabet[count + i];
        }
    }else{ // Incase our if statement doesn't fire 
       count++; // we increment our count because we want to compare against the next letter in our alphabet.      
                // Note this will allways increment and create a infinite loop when a empty string is given
                // We could prevent this by returning undefined when we are done irritating over ower alphabet
            if(count = 26) return undefined; 
    }
  }
```
@SarahDunlap

**Comment by SarahDunlap** [comment]
Thanks! I got it figured out. This is my code:

function fearNotLetter(str) {
 var alphabet = "abcdefghijklmnopqrstuvwxyz";
 alphabet = alphabet.split("");
 str = str.split("");
 
 for (var i = 0; i < alphabet.length; i++) {
   if (alphabet[i] === str[0]) {
     for (var k = 0; k < str.length; k++) {
       if (alphabet[i + k] !== str[k]) {
         return alphabet[i + k];
       }
     }
   }
   
 }
  
  return undefined;
}

fearNotLetter("abce");
