### ISSUE TITLE
Need visible heading for personal inputs on Settings page

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#48891]
### Describe the Issue

There are several Save buttons on the Settings page which save the current status of the inputs grouped directly above them. For example, the Save button under the Privacy Settings heading saves the status of those "privacy settings" inputs. 

Currently, the accessible name for each of these Save buttons is just "save". In order to make them more accessible for people listening to the page we need to tack on the heading using sr-only text. For example, the Save button for Privacy Settings would be read as "Save Privacy Settings" by a screen reader.

All of the groups of inputs currently have a heading we can use for this except for the four personal information inputs below the username (these are Name, Location, Picture, About). We should decide on a heading we can use for this group of four inputs so we can tack it on to the Save button as sr-only text. Technically, we could visually hide this heading on the page to keep it looking as it is, but I think it would be better if we displayed it. I'm assuming we would style it the same as the other similar headings on the page.

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

Open the Settings page from the main menu. You will see that there is no heading above the four personal information inputs below the username.

### Expected behavior

Add a heading above the four personal information inputs.

### System

N/A

**Comment by Sembauke** [comment]
Here are some possible headings:

1. Personal Information
2. Contact Information
3. Profile Information
4. About Me

Let me know what you think.

**Comment by Sboonny** [comment]
We can reduce the save button, too. Something like this:

---

Delete the save button in privacy setting, because the buttons there are toggle and can save after switching them.

![image](https://user-images.githubusercontent.com/88248797/210340070-d3d518cf-e4c6-454f-96d9-a813ab49ea7e.png)

---

Combine email setting with account setting, and have one save button for all the three of them.

![image](https://user-images.githubusercontent.com/88248797/210340221-4dc14eb8-ef6e-4496-a5a6-cc035290190f.png)
![image](https://user-images.githubusercontent.com/88248797/210340299-c2ff405a-2167-4929-98e9-4438b523115b.png)

**Comment by bbsmooth** [comment]
@Sboonny It sounds like you are proposing a restructuring of the Settings page. Perhaps you should open a new issue for this and then this issue will pretty much become obsolete.

**Comment by Sboonny** [comment]
Open issue #48913 👍.

**Comment by bbsmooth** [comment]
Since issue #48913 has been closed and it appears that we are not going to restructure the Settings page, perhaps we can decide on a heading? 

I like @Sembauke's first suggestion, "Personal Information". Screen reader users would hear "Save Personal Information" when focusing the Save button.

**Comment by Sboonny** [comment]
It should work 👍 , opening this for contribution.

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
