### ISSUE TITLE
Percent label next to progress bar is not vertically aligned.

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#48909]
### Describe the Issue

In the new projects, the `1%` in the image below is not vertically aligned with the progress bar next to it.

![Screen Shot 2023-01-03 at 10 00 30 AM](https://user-images.githubusercontent.com/20648924/210394622-8e4b645e-f907-4c74-a3c0-b8a088b1983b.png)

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design
2. Click on one of the blocks and complete a challenge
3. Go back to https://www.freecodecamp.org/learn/2022/responsive-web-design
4. Find the block where you completed that challenge and make sure it's collapsed to see the progress bar

### Expected behavior

The progress bar and percent label next to it to be vertically aligned

**Comment by Sboonny** [comment]
It's an issue with the `font-family`, if we change it to `system-ui`, it will be centered.

![image](https://user-images.githubusercontent.com/88248797/210410865-010a1978-511e-4372-b53f-26e61d227812.png)


---

to keep the font, we can add `margin-bottom` to the progress-bar, it has class so targeting it is easier for beginners, or add `margin-top` to the `span` element, which has the percentage text in it.

**Comment by Sembauke** [comment]
It is fixable by changing the main font to JetBrains Mono.

**Comment by ahmadabdolsaheb** [comment]
Although we are not changing fonts at the moment, we could simply go with 'Lato' for any text is not a title or code.

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.
