### ISSUE TITLE
Documentation for running single Cypress test seems inaccurate

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#48917]
### Describe the Issue

The documentation for running a single Cypress test does not seem to be correct. The command given in the documentation runs all of the default e2e tests instead of just the one specified.

### Affected Page

https://contribute.freecodecamp.org/#/how-to-add-cypress-tests?id=_2-run-the-cypress-tests

### Steps to Reproduce

Current documentation is:

- To run a single test:

`npm run cypress:dev:run -- --spec=cypress/pathToYourSpec/youSpecFileName.js`

### Recommended fix or suggestions

This worked for me to get a single Cypress test to run:

`npm run cypress -- run --spec=cypress/pathToYourSpec/youSpecFileName.js`

**Comment by ShaunSHamilton** [comment]
Quite right, `cypress:dev:run` already passes a glob to `--spec`.

Whilst we are at it, we can change `cypress/pathToYourSpec/youSpecFileName.js` to `cypress/<path_to_test_file>`

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by AnshPhirani** [comment]
I'll work on this.

**Comment by AnshPhirani** [comment]
can you share the exact file I have edit
