### ISSUE TITLE
Restructure the forms structure in the setting page

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48913]
**Describe the feature**
We have multiple forms with multiple saving buttons in the setting page, I think this confuses the people who are interacting with the page. 

We can have cleaner HTML syntax by having one `form` that carries the camper's account setting, and one save button that save the camper inputs in these setting.

We can do this by:

---

Delete the save button in privacy setting, because the buttons there are toggle and can save after switching them.

![image](https://user-images.githubusercontent.com/88248797/210340070-d3d518cf-e4c6-454f-96d9-a813ab49ea7e.png)

---

Combine email setting with account setting, and have one save button and one form for all the three of them.

![image](https://user-images.githubusercontent.com/88248797/210340221-4dc14eb8-ef6e-4496-a5a6-cc035290190f.png)
![image](https://user-images.githubusercontent.com/88248797/210340299-c2ff405a-2167-4929-98e9-4438b523115b.png)

**Comment by bbsmooth** [comment]
I like the idea of getting rid of the Save button for the privacy settings. That way these toggles will function the same as the toggles that take effect immediately (e.g. Night Mode).

As for combining all the text inputs to use one Save button, I'm wondering if there might be a good reason to keep some of them separate. For example, changing your username seems to be a pretty big deal to me. What if the user accidentally changed that field and didn't notice and then clicked the Save button thinking they were only changing another field? Seems like we might want to keep changing the username as a completely separate function in order to avoid an accident like that.

**Comment by Sboonny** [comment]
Valid point, we can add logic that shows a model with warning, if camper change the email or username, otherwise save without modal like the usual. 🤔

**Comment by ahmadabdolsaheb** [comment]
The current email and account settings are not bad. I would look into other websites for similar patterns. Twitter for example has completely separate save button for changing usernames, etc.. 


> I like the idea of getting rid of the Save button for the privacy settings. That way these toggles will function the same as the toggles that take effect immediately (e.g. Night Mode).

This was implemented on purpose to reduce the api calsl when a user sets privacy settings.

**Comment by harshit-002** [comment]
Hello, I am a newbie, Yesterday I setup freecodecamp locally on my system, and http://localhost:8000/  worked fine, but today on opening the server i am getting this error, I didn't make any changes to any file, I searched StackOverflow, google for hours but couldn't find any solution.
Can someone help me out?

![Screenshot (4)](https://user-images.githubusercontent.com/95224348/211656110-c0493cd8-3439-482e-a9f9-4b5305b42ca9.png)
![Screenshot (5)](https://user-images.githubusercontent.com/95224348/211656137-1caa1afc-11c8-427f-a95f-eb6227ec37fa.png)

**Comment by bbsmooth** [comment]
> This was implemented on purpose to reduce the api calls when a user sets privacy settings.

Ahh, thanks for that info. So it sounds like we would not want to change the functionality of the privacy toggles and continue to require them to use the Save button.

**Comment by Sboonny** [comment]
@harshit-002, please head to [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
