### ISSUE TITLE
Inconsistent use of backticks in old JS curriculum challenge "Subtract One Number from Another with JavaScript"

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48928]
### Describe the Issue

in the old JS curriculum, the challenge titled "Subtract One Number from Another with JavaScript" uses backticks inconsistently.
For eg. The instructions use backticks around the number 12 here: Change the `0` so the difference is `12`.
But the hints do not here:
The variable `difference` should be equal to 12.
nor do they use it around the 45 here:
You should only subtract one number from 45.

I believe the 12 in the instructions doesn't need backticks as it is just a value, while the 45 in the hints should probably be contained in backticks.

### Affected Page

curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/subtract-one-number-from-another-with-javascript.md

### Your code

```

```

### Expected behavior

Use backticks when the number is part of the code. But remove the backticks when the number is just a number.

### System

N/A

**Comment by jeremylt** [comment]
We use code blocks for other numeric literals:

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/multiply-two-numbers-with-javascript
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/divide-one-number-by-another-with-javascript
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/divide-one-decimal-by-another-with-javascript
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/factorialize-a-number

I think we more often put numeric literals into code blocks than we don't

**Comment by jeremylt** [comment]
Right, I think that would be the most consistent in general. I think a few of the steps have the same issue

**Comment by moT01** [comment]
I'm fine with that. The [challenge file is here.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/subtract-one-number-from-another-with-javascript.md) We want to put the two numbers in the hints in backticks. e.g. `` `12` `` and `` `45` ``

**Comment by mdnavarro21** [comment]
Hello, I would like to work on this. This will be my first pull request and it seems simple enough.
