### ISSUE TITLE
rely on local storage to store the sound settings

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#48931]
Edited by Sboonny:

- Shift to local storage.
- Sound value shouldn't be stored in user schema. Remove sound property in user schema.
- `https://api.freecodecamp.org/update-my-sound` disable network call. Also deprecate/delete it as it would no longer be needed.

----

<s>With https://github.com/freeCodeCamp/freeCodeCamp/pull/48762, we have moved to use Local storage after fetching the user data. We should align it with our needs and use the user session instead.

Previous discussions:

> We're using a hybrid of local storage and the session user, right now.  It would be best to remove all reliance on local storage, so that it's consistent across devices.

_Originally posted by @ojeytonwilliams in https://github.com/freeCodeCamp/freeCodeCamp/issues/46372#issuecomment-1148398912_</s>

**Comment by nayabatir1** [comment]
I'll start working on this.
My approach is to create a hook to play audio e.g. `usePlayAudio`. This hooks will conditionally play audio instead of conditionally calling it.

**Comment by spiritanand** [comment]
@nayabatir1 any progress on this? I would like to help you out.

**Comment by nayabatir1** [comment]
@spiritanand You can start too. I haven't made any significant progress, due to some other high priority tasks.

**Comment by nayabatir1** [comment]
Help me understand difference between `fcc-sound` in store and

<details>
  <summary>sound in user</summary>

![image](https://user-images.githubusercontent.com/91016903/217338943-13d8d3db-d76e-4c71-bfcb-5e0591137df5.png)
</details>

If I change Campfire Mode is settings then only `fcc-sound` value is changed.

**Comment by Sboonny** [comment]
I don't think this is a good idea at least the user experiences will be worse not better unlike themes, devices to have different sound system and keeping the same sounds properties on my laptop, and having them in my phone when I don't want to, is annoying.

**Comment by nayabatir1** [comment]
@Sboonny I'm not sure if I understand you correctly. Basically you want user to have flexibility to use different settings for different device, but these settings are synced with user details in db. 
So if in other device user details is fetched then both device will have same settings.

**Comment by Sboonny** [comment]
Yeab, 👍

**Comment by Sembauke** [comment]
We want the user still be able to change this setting from the settings page, but it should no longer be on the user schema. Just in the local storage.

**Comment by nayabatir1** [comment]
- Shift from local storage to redux to store sound value
- sound value shouldn't be stored in user schema
- `https://api.freecodecamp.org/update-my-sound` disable network call. Also remove it as it would no longer be needed.

Did I get it right?

**Comment by Sboonny** [comment]
Yeab, I am not sure about the first one 🤔, but yes the other two are the way to go.

I am not sure about the first one because of lack of experience, I have no specifics. 👍

**Comment by Riya267** [comment]
Hi just letting team know that I have started working on this issue

**Comment by Riya267** [comment]
Hey @Sboonny  I have one Question do you want to move soundVolume from localstorage as well?

**Comment by Sboonny** [comment]
Hey @Riya267, I want the sound system to not rely on db value, and it shouldn't be stored in user schema.

I think🤔, the best experience will be provided, if it's stored in local storage, because redux value will be refreshed which will annoy the user, and user schema value will be consistent between devices, which will lead to annoyance too, because of difference sound system, in different devices.

So the requirement is similar to what @nayabatir1 said here https://github.com/freeCodeCamp/freeCodeCamp/issues/48931#issuecomment-1437509825, but not the shift from local storage to redux store, and his code should stay the same.

**Comment by Riya267** [comment]
Got it @Sboonny .

**Comment by ShaunSHamilton** [comment]
@Sboonny Can we get the issue description updated to what we want?

What you said is the opposite of the current issue description.
