### ISSUE TITLE
Cat Photos Step 27 allows wrong code to pass

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#48940]
### Describe the Issue

This step is allowing code that does not meet the requirements to pass.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-27

### Your code

This passes:

```
<h3>Top 3 things cats hate:</h3>
<ol><li>flea treatment</li></ol>
<ol><li>thunder</li></ol>
<ol><li>other cats</li></ol>
```

### Expected behavior

Step should not allow multiple ordered lists to pass. Should enforce that only one ordered list is used with three list items.

### System

- Device: Desktop
- OS: Linux Fedora 36
- Browser: Firefox
- Version: 108

**Comment by brubru6707** [comment]
Can this even be fixed? I searched through the files and folders (keywords such as "learn-html-by-building-a-cat-photo-app" and "step-17") and did not find the file to the page.

**Comment by jdwilkin4** [comment]
@brubru6707 

Here is the file for this particular challenge
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804d2.md

Right now, this issue still has the `status:waiting triage` label on it.
It is best to wait for the core team members to triage this issue and open it up for contribution with a `first-timers-only` or `help-wanted` label. 👍

**Comment by moT01** [comment]
I think we could just add one more test here. "You should only have one `ol` element". Make it the fourth test. What do you all think?

**Comment by Sboonny** [comment]
This is a good idea, Tom 👍.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
