### ISSUE TITLE
jQuery: console displays "plugin failed to initialize" & inability to pass on to next waypoint

### ISSUE THREAD

**Issue by kp2016** [FreeCodeCamp/FreeCodeCamp#4895]
jQuery waypoints display "plugin failed to initialize" error in the console. After resetting the code it appears the issue only arises once the <script> </script> tags are added.

Then after pressing "ctl+enter" the box with the tasks for the waypoint on the bottom-left disappears. concurrently with the "plugin" error.

I have read several of the other issues people have had and I have tried this in Edge, Chrome, Explorer, and Firefox (all Windows 10). With Firefox I was able to complete the first waypoint but every subsequent waypoint does not let me pass and continue even though the console shows the code doing what it should. I even skipped ahead to the next waypoint to check that I coded it properly. They were exact matches. I then copied and pasted from the third waypoint to the second and had the same experience as before.

I have tried everything I can think of and everything others have mentioned or suggested and I'm at a bit of a loss.  I hope I'm missing something easy and obvious to someone else but at this point I need a direction as to how to proceed

**Comment by ltegman** [comment]
What you're seeing is a combination of issues #4895 and #4865. We are aware of them and have a PR getting QA'd that will resolve this problem. We hope to have it live ASAP but want to make sure we're not introducing any new bugs with it.

Thanks and happy coding!
