### ISSUE TITLE
Build a Nightlife Coordination App

### ISSUE THREAD

**Issue by Bl1xvan** [freeCodeCamp/freeCodeCamp#48950]
### Describe the Issue

The example app for this challenge doesn't seem to be working https://yoyo44.herokuapp.com/.

It just leads to a page saying, "There's nothing here yet"

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app

### Your code

```

```

### Expected behavior

It's supposed to lead to a nightlife coordination app.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Jaya-sys** [comment]
Can you assign this issue to me?

**Comment by jdwilkin4** [comment]
@Jaya-sys 

Thank you for your interest in contributing. 

Any issue labeled with the `first-timers-only` or `help-wanted` label is up for grabs.

Right now, this issue is waiting for triage by the core freeCodeCamp team members and contributors and it not open for contribution yet.

You can read more about our Contributing docs here
https://contribute.freecodecamp.org/#/

**Comment by moT01** [comment]
Did you complete this project @Jaya-sys? We need a working project that we can host as an example.

**Comment by Jaya-sys** [comment]
Hey, can you describe the issue? or can walk through the task ??

**Comment by moT01** [comment]
I couldn't find a working demo after a quick search - they were all hosted on heroku, and are now broken. But I found [this video](https://www.youtube.com/watch?v=k-bZFgaa9Kc) that shows what the project looked like. We need to rebuild the project and host it on our [demo-projects repo](https://github.com/freeCodeCamp/demo-projects) so it has a freecodecamp.rocks URL like the rest of the demo projects.

**Comment by Jaya-sys** [comment]
@moT01  hey i have got an idea! i'll try to implement the project as soon as possible

**Comment by moT01** [comment]
Awesome @Jaya-sys. Make sure it fulfills the user stories on [the project page.](https://www.freecodecamp.org/learn/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app) I think the yelp API should work.

**Comment by Jaya-sys** [comment]
Hey, i got one more question. this is going to be built in pure javascript or can I use a framework such as react ?

**Comment by moT01** [comment]
React is fine

**Comment by Jaya-sys** [comment]
okay will update you soon about the project

**Comment by akshay-km** [comment]
Hi, Can this demo project by done with React and Django?

**Comment by ghughes13** [comment]
Seems there is a PR for this in the /Demo-Projects repo. Linking here to avoid duplicate work - https://github.com/freeCodeCamp/demo-projects/pull/422

**Comment by shuaib128** [comment]
@Jaya-sys Hey is there any update on the demo-app?
@moT01 It looks like its been while the issue was opened and I checked the and it seems the Demo app is still broken. I checked your video and I think I can build a demo app like that.

**Comment by 1jds** [comment]
Hello, 

I have completed this project. See the deployed example here: https://nightlife-8ddy.onrender.com/

Code for the React front-end is here: https://github.com/1jds/nightlife 
Code for the Node/Express server is here: https://github.com/1jds/nightlife-server 
(The React front-end gets built and served as static files from the server.)

Free Code camp is welcome to use this as a working project that can be hosted as an example. I'm happy to refactor anything that needs to be changed.

One thing to note is that this is currently hosted in a way that would probably bottle-neck pretty quickly if experiencing too much traffic.

**Comment by moT01** [comment]
This is awesome @1jds 🎉 🎉 Thanks for creating this. I will take a closer look at it when I get a chance and see what we need to do to get it on the .rocks site with the other projects.
