### ISSUE TITLE
Wrong capitalization of API in timestamp project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48958]
**Describe the bug**
In this line, we use "api", while it should be "API".

> If the input date string is invalid, the api returns an object having the structure `{ error : "Invalid Date" }`

Here is the file

https://github.com/freeCodeCamp/freeCodeCamp/blob/8b5838ef233ca1d6056ad650bb73e34843499a35/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice.md#L109?plain=1

Here how it should look.

> If the input date string is invalid, the API returns an object having the structure `{ error : "Invalid Date" }`

--- 

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by mohdzubairshafi** [comment]
hi can you assign this to me .

**Comment by Sboonny** [comment]
You can open PR directly after reading the docs.

**Comment by srmalkan** [comment]
I have created a PR for the issue, here is the link : https://github.com/freeCodeCamp/freeCodeCamp/pull/48959
