### ISSUE TITLE
CSS Cafe menu Step 22 accepts answer of nesting a div selector inside the body selector 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#48965]
### Describe the Issue

I was assisting a camper in t[his forum post](https://forum.freecodecamp.org/t/html-building-cafe-menu-comment-out-div-step-22/583423) and they were able to pass [step 22](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-22) of the cafe menu project with the following answer.

```
div{/*background-color: burlywood; */}
```
I don't think this answer should be accepted because it is using selector CSS nesting which doesn't have great browser support in native css right now according to [Can I use](https://caniuse.com/css-nesting).  

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-22

### Your code

code that passes
```
body{
  div{/*background-color: burlywood; */}
}
```

### Expected behavior

```
/*background-color: burlywood; */
```

### Screenshots

<img width="713" alt="Screen Shot 2023-01-08 at 12 49 53 AM" src="https://user-images.githubusercontent.com/67210629/211187890-def8a1e8-0010-4db3-90c4-6ad5ef12bf5c.png">

**Comment by moT01** [comment]
I'm not sure what we can do here. The step is to comment out the line, which the person did. Seems tough to make a check for other things like this. I feel like we can probably just leave it but we can see if anyone else has any ideas.

**Comment by bbsmooth** [comment]
The current test is:

```
code.match(/\/\*\s*background-color:\s*burlywood;?\s*\*\//i)
```

We could expand that to make sure only `body {` comes before the commented line and `} follows. That is, if we feel this one aberration is worth the trouble.

**Comment by jdwilkin4** [comment]
I have looked through the forum and it doesn't seem like this is one of the steps that people trip up on that much. 
My guess was that the user here was confused by the last sentence because it mentions the word `div` and that might have been why they wrote it that way. 
I think for now we could close this issue. 

If for some reason it starts to effect a large group of people, then we could revisit it then. 👍
