### ISSUE TITLE
Hii, I am a beginner can someone please help me from where I should start my open source journey. Thank you in advance😊

### ISSUE THREAD

**Issue by Rishabhk2604** [freeCodeCamp/freeCodeCamp#48964]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by jdwilkin4** [comment]
Hi @Rishabhk2604 ! 

Thank you for your interest in our repository.
I would suggest reading through the [contributing docs](https://contribute.freecodecamp.org/#/) first to understand how the process works. 
Any issue marked with a `help-wanted` or `first-timers-only` label is open for contribution.
If you have further questions, I would suggest asking on the [forum](https://forum.freecodecamp.org/) or the [discord](https://discord.com/invite/KVUmVXA) 👍
