### ISSUE TITLE
Error with cloning FreeCodeCamp

### ISSUE THREAD

**Issue by willow0217** [freeCodeCamp/freeCodeCamp#48969]
I'm on the step of seeding the database, I followed all the instruction above and made sure I met all the requirements. Everything was fine until I tried to seed the database. 
When I put: "C:\Program Files\MongoDB\Server\3.6\bin\mongod", replacing "3.6" with "5.0".
Then I put: npm run seed and the error appeared like this:
![image](https://user-images.githubusercontent.com/122182849/211197863-c1545ceb-cdc8-481d-b5ee-d52fcb970267.png)
I've already restarted my computer once and tried to run it again a lot of times. But it didn't work.

Desktop 
 - OS: Windows 11
 - Browser: Brave
 - Version: latest

**Comment by Sboonny** [comment]
Please head to [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by harshit-002** [comment]
@willow0217  As written in the docs, mongod was to be opened in a new tab. Try doing opening mongod in a new tab and then run the command `npm run seed ` in the previous tab

**Comment by willow0217** [comment]
> @willow0217 As written in the docs, mongod was to be opened in a new tab. Try doing opening mongod in a new tab and then run the command `npm run seed ` in the previous tab

I just tried, still not working.

**Comment by andriy-koz** [comment]
> I'm on the step of seeding the database, I followed all the instruction above and made sure I met all the requirements. Everything was fine until I tried to seed the database. When I put: "C:\Program Files\MongoDB\Server\3.6\bin\mongod", replacing "3.6" with "5.0". Then I put: npm run seed and the error appeared like this: ![image](https://user-images.githubusercontent.com/122182849/211197863-c1545ceb-cdc8-481d-b5ee-d52fcb970267.png) I've already restarted my computer once and tried to run it again a lot of times. But it didn't work.
> 
> Desktop
> 
>     * OS: Windows 11
> 
>     * Browser: Brave
> 
>     * Version: latest

Hi @willow0217, you're running `npm run seed` from the `C:/WINDOWS/System32` directory.
I think you should run it from your local freeCodeCamp directory, where the file `package.json` with the declared `seed` script lives.
For example in my case is "~/Documents/freeCodeCamp".

**Comment by willow0217** [comment]
Do you know why that's happening?

**Comment by andriy-koz** [comment]
> Do you know why that's happening?

Did you run `npm ci` before `npm run seed`?
Also do you have a `.env` file in the same directory (you can rename the existing `sample.env` to `.env`).

**Comment by willow0217** [comment]
> Did you run `npm ci` before `npm run seed`? Also do you have a `.env` file in the same directory (you can rename the existing `sample.env` to `.env`). (Always in the freeCodeCamp local directory)
yeah, I did all of those. 
>Did you run `npm ci` before `npm run seed`?
wait...do I have to do that again everytime before I run `npm run seed`?

**Comment by andriy-koz** [comment]
> > Did you run `npm ci` before `npm run seed`?
> 
> wait...do I have to do that again everytime before I run `npm run seed`?

No that's not necessary.

Personally i couldn't make it work on Windows 11 either. 
However it worked on Linux Mint without any problem.
In documentation they recommend setting up a [WSL](https://contribute.freecodecamp.org/#/how-to-setup-wsl) when using Windows.

**Comment by willow0217** [comment]
>No that's not necessary.

>Personally i couldn't make it work on Windows 11 either.
However it worked on Linux Mint without any problem.
In documentation they recommend setting up a [WSL](https://contribute.freecodecamp.org/#/how-to-setup-wsl) when using Windows.

I did set up WSL 2, but I'm not really sure how to use that, or if it was supposed to make much difference.

**Comment by willow0217** [comment]
Happy New Year! Wish you...
    Good luck!
    Peace and safety!
    And happiness everywhere you go!
    New Year(and every other day) is to be celebrated with cheers and joy!
Below are some videos that is sure to bring happiness to you and others on
this auspicious day!
    https://youtu.be/OTrR0zlSrho    《光芒》
    https://youtu.be/Pn65yTFIMcQ    《最美的光》
    https://youtu.be/fMMOr_EFUJs    《山河美》
    If you like these videos, please spread your smile by sharing these
videos with others!
With joyful greetings and best wishes,
Willow
