### ISSUE TITLE
"removedFromOurArray is not defined"

### ISSUE THREAD

**Issue by jrkanu** [FreeCodeCamp/FreeCodeCamp#4896]
The default code for the challenge is presented as such:

    var ourArray = ["Stimpson", "J", ["cat"]];

    removedFromOurArray = ourArray.shift(); // removedFromOurArray now equals "Stimpson" and ourArray now equals ["J", ["cat"]].

    var myArray = ["John", 23, ["dog", 3]];

    // Only change code below this line.

    var removedFromMyArray;

    // Only change code above this line.

    (function(y, z){return 'myArray = ' + JSON.stringify(y) + ' & removedFromMyArray = ' + JSON.stringify(z);})(myArray, removedFromMyArray);

The instructions are to use the `shift()` fucntion to add the first item of `myArray` to `removedFromMyArray`. 

The correct answers is to change line 9 to the following:

    var removedFromMyArray = myArray.shift();

However, doing so throws the console error in the title of this post: `removedFromOurArray is not defined`

This is because the `var` keyword is not used on line 3 when declaring `removedFromOurArray`. Changing it to this:

    var removedFromOurArray = ourArray.shift();

resolves the issue. However, I do not think this was intended to be part of the challenge. Perhaps it should be changed to avoid confusion.

**Comment by ltegman** [comment]
This was fixed by PR #4870 and is pending deployment to the website.

Thanks and happy coding!
