### ISSUE TITLE
Remove the mentioning of Node Package Manager from Intro.json

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48962]
We mention npm and we refer to it as `Node Package Manager`, which isn't the correct way to refer to it.

> "In the Back End Development and APIs Certification, you'll learn how to write back end apps with Node.js and npm (Node Package Manager). You'll also build web applications with the Express framework, and build a People Finder microservice with MongoDB and the Mongoose library."

Here is the file: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/cc0514ea35ecd7f146b09328689baeb828a55498/client/i18n/locales/english/intro.json#L556?plain=1

Here how it should be: 

> "In the Back End Development and APIs Certification, you'll learn how to write back end apps with Node.js and npm. You'll also build web applications with the Express framework, and build a People Finder microservice with MongoDB and the Mongoose library."

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by joeshajan** [comment]
Hey, @Sboonny I would like to fix this issue. Can you assign this to me?

**Comment by jdwilkin4** [comment]
@joeshajan 

Any issue labeled with `first-timer-only` are up for grabs and open to anyone new to the `freeCodeCamp` repo.
You don't need to ask to be assigned to this issue.

Thanks!

**Comment by harshit-002** [comment]
@Sboonny  I a first-timer, and I would like to fix this issue. Can you please assign me this issue?

**Comment by Sboonny** [comment]
Nope

**Comment by jdwilkin4** [comment]
@harshit-002 

>Any issue labeled with first-timers-only are up for grabs and open to anyone new to the freeCodeCamp repo.
You don't need to ask to be assigned to this issue.

Also, please read through our [Contributing guide](https://contribute.freecodecamp.org/#/) so you can learn more about the process 👍
