### ISSUE TITLE
Broken RTL titles in Basic JavaScript course in JavaScript algorithms and data structure

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48967]
**Describe the bug**
Having special character in the slug, title, or heading of the challenges lead to broken structure as shown in the image below. Originally reported by @hbar1st.

![image](https://user-images.githubusercontent.com/88248797/211189654-646b8249-b0fa-4804-846c-b5fafc7c9240.png)

These challenges are the translation of these.

![image](https://user-images.githubusercontent.com/88248797/211189690-48c78050-99ab-4fbb-afee-96214316237c.png)

---

Although we can not add them in the Arabic translation, this is a fix to the side effect, because Arabic isn't the only RTL language with translation efforts. I think it's better to not include special characters in the heading, if they aren't wrapped in spaced, example 'the Logical And Operator &&'.

So I suggest two solutions:

- Delete special character, if they aren't wrapped around spaces, like change "push()" to "push".
- Add code block around functions and methods, to be something like `push()`.

**Comment by bbsmooth** [comment]
Would it be acceptable to spell these out a little more? Instead of

`Manipulate arrays with push()` 

We could do

`Manipulate arrays with the push method`

Not only do we get rid of the special characters but it possibly makes it a little clearer for people listening to the page.

**Comment by Sboonny** [comment]
In translation, that's perfectly fine 👍. Good call.

**Comment by idanhahn** [comment]
:)
