### ISSUE TITLE
Enabling error underling/suggestions

### ISSUE THREAD

**Issue by oriooctopus** [freeCodeCamp/freeCodeCamp#48972]
### Is your feature request related to a problem? Please describe.

![Screenshot 2023-01-08 at 6 35 27 PM](https://user-images.githubusercontent.com/20331238/211229208-6b9f4fde-7cf6-4dad-9bd8-5ba47363ae6b.png)

A core part of the developer experience is that our IDE's help make our job easier by pointing out basic syntax errors. As a developer with several years of experience this is constantly useful. For new developers, it helps avoid tons of frustration and prevent them from getting stuck for long periods of time.

Currently, this feature is not the case with free code camps editor, even though it can be enabled fairly easily via the props of Monaco editor (which we currently use as our code editor). There are a lot of pros and cons to enabling it, so I wanted to start a dialogue here discussing it. In my opinion, it is well worth enabling because I have seen so many people, struggle and get frustrated from basic syntax errors. It seems like one of the major reasons why people give up on coding at the start. I don't think that people would learn more slowly, I think mainly they would just get unstuck more quickly.

### Describe the solution you'd like

Enabling the error highlighting/suggestions/underlining

### Describe alternatives you've considered

To point out some of the cons:
- The suggestions shown in the tool tip are not translatable, but that's also the case with the errors shown in the console. Potential solutions could be 
  - Only enabling it for English users (I remember seeing in our analytics that they accounted for the vast majority of our users), 
  - Keeping it for all language users, but giving them the option to disable it.
  - not introducing it at the very beginning, but instead of waiting a couple dozen lessons, in order to not overwhelmed the user.
- It is also not accessible, but since this is not a core feature I don't think we should let <1% of people's experience remove a potentially useful feature for the rest of users. I would also say that far greater than 1% of users, actually, the mass majority, give up on coding because it's too difficult or frustrating. That's a really hard problem to solve but I think this can help with that.

I also want to suggest that if people are skeptical, perhaps we could test it out on one of the courses and see if he users like it.

### Additional context
This is a common practice amongst universities, bootcamps, and sites like the Odin project.

_No response_

**Comment by bbsmooth** [comment]
It looks like syntax errors (and other types of errors) are currently printed out in the Console pane, so they are already fairly accessible, and thus adding tooltips that give out pretty much the same information isn't going to cause any major accessibility concerns. The console pane may not provide all of the convenience of the tooltips but I think it is a comparable experience in that people who can't utilize the tooltips (which is basically anyone who can't use/doesn't have a mouse) will still have access to pretty much the same information that the tooltips provide. That's not to say we couldn't look at ways to make the squiggly lines in the editor possibly more accessible, just that I don't think we will introduce any WCAG violations by enabling tooltips for these error messages (I'm assuming we will continue to provide them in the Console).

**Comment by ojeytonwilliams** [comment]
For historical context, we deliberately removed the intellisense suggestions for a couple of reasons.  Firstly they weren't working terribly well and secondly we considered them to be distraction to learners. 

We want the learners to have all the information they need and no more. That way they've got a limited set of options (in principle just what we've taught them to that point) to choose between and should not get overwhelmed. https://github.com/freeCodeCamp/freeCodeCamp/issues/37740 contains some relevant discussion.

@raisedadead has definitely given this some thought in the past, so might have a more nuanced perspective.

That said if we can address the a11y concerns Bruce raised as well as the original UX issues, it seems reasonable to add this to the set of things to AB test.  Assuming we can get enough detail to test the hypothesis, of course!

**Comment by raisedadead** [comment]
freeCodeCamp's editor in the first few certifications is not a full IDE, and it doesn't aim to be one in the foreseeable future. 

Not allowing contextual intellisense and prompts is a well-thought-out design choice. 

We understand this comes to you frustrating as a seasoned developer. However, as a seasoned developer, you are unlikely to be working through the basic certifications we have. 

Even if you are (for practice), you are likely to build projects in IDEs of your choice and paste the solutions to get past them. In short, the practice projects are aimed at users who are very new to coding.

For such novice users, we want to put our opinionated choices about lining or other code-analysis tooling into the curriculum.

Once the new users move on to building projects in their coding journal, they are welcome to (and they will) set up their IDE/Editor as they wish. 

You can see this in the later projects that use a full VS Code instance.

Thanks for discussing this, though. We appreciate your feedback :)

**Comment by oriooctopus** [comment]
I guess this all makes sense, thank you!
