### ISSUE TITLE
predetermined variable not initialized causing tasks to complete to not appear

### ISSUE THREAD

**Issue by marcusparsons** [FreeCodeCamp/FreeCodeCamp#4897]
![freecodecamp_bug](https://cloud.githubusercontent.com/assets/10608765/11522235/3d9b443a-9883-11e5-9e46-8260eb216b2f.png)

In this challenge, "removedFromOurArray" isn't properly initialized with a "var" keyword upon creation of the challenge and so the system will not present tasks to complete until you add the "var" keyword to "removedFromOurArray".  Once you do that, then the tasks will show up that need to be completed.

Challenge [Waypoint: Manipulate Arrays With shift](http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = ["Stimpson", "J", ["cat"]];

removedFromOurArray = ourArray.shift(); // removedFromOurArray now equals "Stimpson" and ourArray now equals ["J", ["cat"]].

var myArray = ["John", 23, ["dog", 3]];

// Only change code below this line.

var removedFromMyArray;

// Only change code above this line.


(function(y, z){return 'myArray = ' + JSON.stringify(y) + ' & removedFromMyArray = ' + JSON.stringify(z);})(myArray, removedFromMyArray);

```

**Comment by ltegman** [comment]
This was fixed by PR #4870 and is pending deployment to the website.

Thanks and happy coding!
