### ISSUE TITLE
Documentation images are not displayed when diployed

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#48973]
### Describe the Issue

Although images are added to the markdown using the ![text](path) syntax similar to other images in the directory, the images on authors-analytics-manual.md are not shown when deployed. 

The images load as expected when the path is visited directly.

Might be related: https://github.com/docsifyjs/docsify/issues/1891

### Affected Page

https://contribute.freecodecamp.org/#/authors-analytics-manual

### Steps to Reproduce

Visit the above mentioned path and view the source to see the image elemennts.

### Expected behavior

Images  load locally:
<img width="1963" alt="Screen Shot 2023-01-09 at 10 20 15 AM" src="https://user-images.githubusercontent.com/4591597/211262322-1417d689-52a1-4988-ac3f-cf0fa0c1786c.png">

Images do not load after deployment:
<img width="1978" alt="Screen Shot 2023-01-09 at 10 20 42 AM" src="https://user-images.githubusercontent.com/4591597/211262364-8b649f22-a53d-4cb2-b312-e5489c0e9361.png">

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb I wasn't able to reproduce this with Brave or Chrome (on Ubuntu). Could you check again in case it was a temporary outage of some kind?

**Comment by ahmadabdolsaheb** [comment]
Thanks @ojeytonwilliams, it was uBlock Origin adblocker.
