### ISSUE TITLE
Unclear description on step 24 on "Learn More About CSS Pseudo Selectors By Building A Balance Sheet"

### ISSUE THREAD

**Issue by laquavion** [freeCodeCamp/freeCodeCamp#48985]
### Describe the Issue

The instructions state "In your fourth tr element, add a th element with the text Total Liabilities." However it is not really clear that the user should or should not include a period. Users will have failed previous tasks if the period was omitted (periods are required on previous exercises) , therefore they will most likely add the period which will result in a failed test case. Also, if the period is included after "Liabilities", the error message gives "Your th element should have the text Total Liabilities." Which does not highlight the actual issue. Maybe making a different test case message that looks for the period would make it more understandable?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-24

### Your code

```
<th>Total <span class='sr-only'>Liabilities.</span></th>
<!-- this code returns an error message (stated in the issue) that does not highlight the actual problem -->

```

### Expected behavior

The code above should highlight the issue of the period being present. The test case that is currently in place can confuse users that they have a spelling issue/spacing instead of the actual issue being the period at the end of "Liabilities".

### System

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: Version 108.0.5359.125

**Comment by Sboonny** [comment]
I was thinking, that we could change 

> add a `th` element with the text `Total Liabilities`.

to

> add text `Total Liabilities` to the `th` element.

But this doesn't make a coherent sentence.

---

I am in favor of adding a new test.

**Comment by laquavion** [comment]
I also think a new test case would be good.

**Comment by Jiajun-Jiao** [comment]
Hi! We just opened a [pull request above](https://github.com/freeCodeCamp/freeCodeCamp/pull/50035) to fix it, but it was not accepted @raisedadead . Could you please kindly inform us some feedback about what was going wrong and what else we need to do? So that we can know where to focus. We appreciate any help, thank you!!

**Comment by raisedadead** [comment]
Hi @Jiajun-Jiao 

Thanks for reaching out and creating a pull request. 

For reasons of sanity, we can't accept PRs from forks that organizations maintain. You should make a PR from your own personal GitHub account.

You can collaborate with others and have commits made by multiple people, but one person needs to create the PR (if you want to use the draft mode), and then others may push to the same PR should they wish.

The person making the PR is responsible for ensuring the checklist is followed, tests are working, and so on.

You can also commit on someone's behalf. See: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

Also, please create **good, small, and succinct commit messages** and PR titles.
