### ISSUE TITLE
JavaScript Algorithm and Data Structures

### ISSUE THREAD

**Issue by GradMaven** [freeCodeCamp/freeCodeCamp#48987]
### Describe the Issue

The instruction says: Use bracket notation to find the second-to-last character in the lastName string.

I did: const secondToLastLetterOfLastName = lastName[lastName.length - 2]; // Change this line

and got an error message: ReferenceError: ARA is not defined

I thing there is a bug

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-to-last-character-in-a-string

### Steps to Reproduce

The instruction says: Use bracket notation to find the second-to-last character in the lastName string.

I did: const secondToLastLetterOfLastName = lastName[lastName.length - 2]; // Change this line

and got an error message: ReferenceError: ARA is not defined

I thing there is a bug

### Expected behavior

The test should pass

### Screenshots

![image](https://user-images.githubusercontent.com/109470807/211655674-eb3087e5-1e13-4c55-95ce-4011c8a6af91.png)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Firefox
- Version: 22

**Comment by moT01** [comment]
You have `ARA` on line 1 that is not part of the seed code and it is not commented out. That is trying to be run, but `ARA` isn't defined so you are seeing that error. Delete the `ARA` and it should pass.

**Comment by moT01** [comment]
You're welcome. 

For future reference, you should make a post on the forum if you are stuck on a lesson before creating an issue. They would have been able to help you.

Thanks and happy coding 🎉
