### ISSUE TITLE
Conditions are said to be met but the outcome is wrong?

### ISSUE THREAD

**Issue by BlackThoughtz** [FreeCodeCamp/FreeCodeCamp#4898]
Challenge [Waypoint: Use Conditional Logic with If and Else Statements](http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-if-and-else-statements#?solution=var%20flip%20%3D%20Math.floor(Math.random()%20*%20(1%20-%200%20%2B%201))%20%2B%200%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20flip%20%3D%20Math.floor(Math.random()%20*%20(1%20-%200))%20%2B%200%3B%0A%20%20if%20(flip%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20return%20%27heads%27%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%27tails%27%3B%0A%20%20%7D%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0Avar%20result%20%3D%20myFunction()%3Bif(typeof%20flip%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20flip%20%3D%3D%3D%20%22number%22%20%26%26%20typeof%20result%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20result%20%3D%3D%3D%20%22string%22)%7B(function(y%2Cz)%7Breturn%20%27flip%20%3D%20%27%20%2B%20y.toString()%20%2B%20%27%2C%20text%20%3D%20%27%20%2B%20z%3B%7D)(flip%2C%20result)%3B%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var flip = Math.floor(Math.random() * (1 - 0 + 1)) + 0;

function myFunction() {

  // Only change code below this line.

var flip = Math.floor(Math.random() * (1 - 0)) + 0;
  if (flip === 0) {
    return 'heads';
  } else {
    return 'tails';
  }
  

  // Only change code above this line.

}

var result = myFunction();if(typeof flip !== "undefined" && typeof flip === "number" && typeof result !== "undefined" && typeof result === "string"){(function(y,z){return 'flip = ' + y.toString() + ', text = ' + z;})(flip, result);}

```

No matter if the function returns 0 or 1 I always get heads. It passed me through, but I don't think I did it right still

**Comment by DDaems** [comment]
You added a new variable flip wich overwrites the provided one. And yours isn't exactly correct in this case. :-)
>var flip = Math.floor(Math.random() * (1 - 0 + 1)) + 0; //given
>!=
>var flip = Math.floor(Math.random() * (1 - 0)) + 0; //yours

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Waypoint-Generate-Random-Whole-Numbers-within-a-Range

**Comment by BerkeleyTrue** [comment]
@DDaems Thanks!

Happy Coding!
