### ISSUE TITLE
step 46 of build a balance sheet project has a test that is too stringent

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48984]
### Describe the Issue

Step 46 of the project to build a balance sheet asks learners to add the `!important` term to each property present in the `span[class~="sr-only"]` selector.
Someone on the forum attempted to do this but managed to remove a few spaces that were directly to the right of the colons on some of the properties. This prevented the test from passing but weirdly not because all the removed spaces were required to be added back but only because of this one line ` -webkit-clip-path:inset(50%) !important;` which the hint responded to by saying "Hint
Your span[class~="sr-only"] selector should have the border property set to 0 !important."

Once the learner added back the space to the right of the colon, the test passed.
(again, other lines had also been modified by the learner and had space characters removed but they didn't affect the test, just this one line needed to be adjusted)

I believe this is a too stringent spacing requirement for the test in this step and should be fixed.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-46

### Your code

```
span[class~="sr-only"] {
  border:0 !important;
  clip:rect(1px, 1px, 1px, 1px) !important;
  clip-path:inset(50%) !important;
  -webkit-clip-path:inset(50%) !important;
  height:1px !important;
  width:1px !important;
  position:absolute !important;
  overflow:hidden !important;
  white-space:nowrap !important;
  padding:0 !important;
  margin:-1px !important;
}
```

### Expected behavior

the tests should not care about the spaces to the right of the colons and to the left of the property values.

### System

not applicable

### Additional context

originally found on the forum: https://forum.freecodecamp.org/t/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet-step-46/584056

**Comment by moT01** [comment]
Here's [the file for that step.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/62017f47c87be96457c49f46.md#--hints--) All the tests there check the computed values it looks like except that `-webkit-clip-path` one, which checks the users code. It looks like we can't change that test to check the computed value, but we should change it to be more lenient on the spaces. Maybe regex?

**Comment by Sboonny** [comment]
I remember in the issue triage meeting, we found out the `clip-path` isn't that supported. 

If we are sticking with it, we can remove the `webkit-clip-path`. If it doesn't work, it will fall back to `clip`.

**Comment by Sembauke** [comment]
We want to change the test that checks for the --webkit-clip-path and use a RegEx instead.

**Comment by a2937** [comment]
Is allowing for spaces inside the parentheses valid?
