### ISSUE TITLE
Change Challenge Complete Tweet to @FreeCodeCamp

### ISSUE THREAD

**Issue by Chris2Brooks** [FreeCodeCamp/freecodecamp#49]
(enhancement) 

When selecting "challenge complete" the pop-up gives you an option to tweet about it:

>I just ROCKED Free Code Camp Challenge #4: Build a Responsive Blog Theme http://freecodecamp.com/challenges/4 #learntocode #javascript

Perhaps consider changing the text to include the Free Code Camp username. The same message is conveyed, but gives an additional lead opportunity to the Twitter account:

>I just ROCKED @FreeCodeCamp Challenge #4: Build a Responsive Blog Theme http://freecodecamp.com/challenges/4 #learntocode #javascript

**Comment by QuincyLarson** [comment]
Good idea! I've added your suggestion to the Bonfire branch, and once we merge it into master, we'll push everything up to production and this code will be live. Thanks, and keep the great suggestions coming.

**Comment by QuincyLarson** [comment]
Hi @Chris2Brooks Thanks for pointing this out. I've updated the copy on this based on your recommendation.
