### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue 

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/freecodecamp#490]
The test is satisfied by an opening paragraph tag, but campers should have to close the tag too.

`<p><a href='http://www.catphotoapp.com'>cat photos</a>`

should not pass but this should:

`<p><a href='http://www.catphotoapp.com'>cat photos</a></p>`

**Comment by terakilobyte** [comment]
The first is actually valid html. We've looked at ensuring the closing tag is there but it's a gigantic snarl of not good.
