### ISSUE TITLE
Nutrition Label Step 43

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#49017]
### Describe the Issue

The forum is getting hammered with questions for Nutrition Label Step 43. I think we can improve the last sentence to help with this.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-43

### Current Instructions

This is the current instructions:

> Step 43

> After your last `.divider` element, create a `p` element and give it the text `Total Fat 8g 10%`. Wrap `Total Fat` in a `span` element with the `class` set to `bold`. Wrap `10%` in another `span` element with the `class` set to `bold`. Also wrap the words `Total Fat 8g` in an additional `span` element for alignment.

### Expected behavior

Users are not sure where to put the third span element.

I think we can use the phrase `nesting` in the last sentence to make the intended solution clear:

> Finally, nest these two `span` elements in an additional `span` element for alignment.

If this doesn't work, we may want to consider splitting this step into two parts.

### System

All

**Comment by hbar1st** [comment]
and let's not forget step 53 which has a similar issue in the wording

**Comment by marksist300** [comment]
I'm happy to work on and fix this issue.

**Comment by SanjeevSingh08** [comment]
@jeremylt Just have a review and accept my pull request.

**Comment by Sboonny** [comment]
to fix this issue rephrase step 43 and step 53

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by SanjeevSingh08** [comment]
sorry @Sboonny , But the issue only mentioned about the label 43 so I fixed it. Ok i am making another pull request rephrasing wording of both step 43 and step 53.

**Comment by jeremylt** [comment]
The second and third post talk about updating step 53 - it has the same problem

**Comment by WangaJN** [comment]
//here is the expected code 
<div class="daily-value small-text">
      <p class="bold right">% Daily Value *</p>
      <div class="divider"></div>
      <p><span><span class="bold">Total Fat</span> 8g</span> <span class="bold">10%</span></p>
    </div>
