### ISSUE TITLE
Cat Photo App Setp 56

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#49019]
### Describe the Issue

This remains a high 'stuck' step. Perhaps an example would help.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-56

### Current Instruction

> Step 56

> There's another way to associate an input element's text with the element itself. You can nest the text within a label element and add a for attribute with the same value as the input element's id attribute.

> Associate the text Loving with the checkbox by only nesting the text Loving in a label element and place it to the right side of the checkbox input element.

### Expected behavior

Perhaps this example would help after the first paragraph:

```HTML
<label for="sweet">Sweet</label> <input id="sweet">
```

### System

All

**Comment by bbsmooth** [comment]
I've always thought this part of the instructions might cause some confusion:

"...and place it to the right side of the checkbox input element."

The string "Loving" is already to the right of the input element, so the instructions make it seem like you need to move it when you don't.

**Comment by jeremylt** [comment]
That's a good point.

Perhaps

> There's another way to associate an `input` element's text with the element itself. You can nest the text within a `label` element and add a `for` attribute with the same value as the `input` element's `id` attribute.

> Associate the text `Loving` with the checkbox by nesting only the text `Loving` in a `label` element and giving it an appropriate `for` attribute.

**Comment by Sboonny** [comment]
Here is the file https://github.com/freeCodeCamp/freeCodeCamp/blob/aac04e93c2014d0ea1c4c8c106b6e4cf1b6b1ff3/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5efc4f528d6a74d05e68af74.md

--- 

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by jainamthakkar** [comment]
@jeremylt can you please elaborate what exactly changes needed?

**Comment by jeremylt** [comment]
The instructions for this step need to be updated to what I have written in my last post above

**Comment by piyushyadav1617** [comment]
I want to solve this issue. I am new to contributing, how should I do this so that my commits get accepted?

**Comment by jeremylt** [comment]
You make a fork, add the changes I gave above to the file linked above, then create a PR. I recommend reading the contributing guide.

**Comment by Sboonny** [comment]
To solve the issue **READ** this comment https://github.com/freeCodeCamp/freeCodeCamp/issues/49019#issuecomment-1382254973, after you have **READ** it, **READ** our guidelines so we know that you aren't wasting our time with low efforts contribution.

**Comment by CallmeHongmaybe** [comment]
Hey @piyushyadav1617 do you want to work together on this issue ? You can hit me up on Discord if you want.

**Comment by piyushyadav1617** [comment]
@CallmeHongmaybe, yeah sure I actually need someone along to learn better. I haven't used discord yet, how can I find you and connect?

**Comment by CallmeHongmaybe** [comment]
@piyushyadav1617 you can shoot me an email and I'll send over my Discord handle in return. Thanks
