### ISSUE TITLE
JavaScript Calculator Accepts Invalid Input 

### ISSUE THREAD

**Issue by diegoperezm** [freeCodeCamp/freeCodeCamp#49038]
### Describe the Issue

Example JavaScript Calculator accepts invalid input.

### Affected Page

https://javascript-calculator.freecodecamp.rocks/

### Your code

```
*2=
```
```
/2=
```
```
/2/2=
```

### Expected behavior

It should  ignore invalid input.

### Screenshots

![1](https://user-images.githubusercontent.com/12677127/212497796-da17ae62-4061-4fb4-9cfb-5906fd465284.png)
![3](https://user-images.githubusercontent.com/12677127/212497801-905d88b3-5542-41bd-aaa4-5ecca88a55ba.png)
![4](https://user-images.githubusercontent.com/12677127/212497805-68945581-fb04-459e-bf00-b054a0c0283c.png)

### System

Device: Laptop
OS: Ubuntu 18.04.5 LTS
Browser: Chromium
Version: 90.0.4430.72

### Additional context

https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-javascript-calculator

**Comment by Bl1xvan** [comment]
Please assign this issue to me

**Comment by Hrmn97** [comment]
What if we consider empty integer before expression as NAN and display command to get number from user.

**Comment by RajPabnani03** [comment]
I am interested in doing this part and start my contribution in this community !!!!

**Comment by Bidhu1024** [comment]
Hey Folks, I can resolve this issue. Please assign me. I'll post the correct code soon.

**Comment by RishabhSingh4872962** [comment]
i can fix it assign me

**Comment by varun-p18** [comment]
I can fix it. and this will be my first open source contribution.

**Comment by Aman300801** [comment]
Assign this issue to me. I can fix it and start my first contribution.

**Comment by moT01** [comment]
I don't think this is a bug that necessarily needs to be fixed. Nothing happens when you enter one of these equations (except the error in the console). The calculator fulfills all the user stories - there's no requirements for what should happen when you start with a `*` or `/`. If someone wants to fix the demo project so it ignores those when they're entered first, we would accept the changes - [the demo project is here](https://github.com/freeCodeCamp/demo-projects/tree/main/apps/javascript-calculator)

**Comment by KalliopiPliogka** [comment]
Hello, I see that this issue is  open, I would like to contribute.

**Comment by chaotic-10** [comment]
Hey can I contribute to this project ?

**Comment by cwesterink** [comment]
I would like to work on this.
What is the desired behavior for an invalid input?
Clear the input? Error notification?
