### ISSUE TITLE
 JavaScript Calculator displays an incorrect formula

### ISSUE THREAD

**Issue by diegoperezm** [freeCodeCamp/freeCodeCamp#49045]
### Describe the Issue

 JavaScript Calculator displays an incorrect formula.

### Affected Page

https://javascript-calculator.freecodecamp.rocks/

### Your code

```
+0+0+0+0+0+0+-1=
```

### Expected behavior

- It should not display 3 hyphens before the number 1
- It should not display  hyphens of different types 

### Screenshots

![incorrect-formula](https://user-images.githubusercontent.com/12677127/212694821-9ac9d5e8-5958-48e6-b7ad-3cba69146b62.png)

![incorrect-formulat](https://user-images.githubusercontent.com/12677127/212928588-b06bae0a-0753-4fff-ba1f-d963df053ba7.gif)

### System

Device:  Laptop
OS:      Ubuntu 18.04.5 LTS
Browser: Chromium
Version: 90.0.4430.72

### Additional context

https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-javascript-calculator

**Comment by Rishab49** [comment]
it is working fine only my device
os : windows 10
browser : chrome version 108.0.5359.126

**Comment by timagixe** [comment]
https://user-images.githubusercontent.com/60817786/212723817-9d2c44e6-d17e-4025-b48a-b8171344417b.mov


For me it also seems to be a bit buggy. Please refer to the attached video.

**Comment by Rishab49** [comment]
Where can i find code of this calculator?

**Comment by RishabhSingh4872962** [comment]
i can fix it  please assign me

**Comment by moT01** [comment]
The code for this lives in our [demo-projects repo.](https://github.com/freeCodeCamp/demo-projects)

**Comment by scottykrieg** [comment]
I'd like to add the ability to use keyboard commands as well as mouse-clicked buttons on the calculator.

**Comment by mikeleonida** [comment]
For me it looks like the original buggy input has been fixed as it gives the result in the screenshot. 
Platform: Ubuntu Linux 22.04
Browser: Firefox 108.0.2
![Screenshot from 2023-01-27 15-15-34](https://user-images.githubusercontent.com/74788426/215189669-bffb783a-67f9-4f07-b2d8-32404a19bf17.png)

**Comment by spiritanand** [comment]
Has anyone started on this? I would like to collaborate if anyone has.

**Comment by montycarlos** [comment]
Me gustaría oarticipar

**Comment by CallmeHongmaybe** [comment]
I'm in this one too. Where do we start ?

**Comment by spiritanand** [comment]
@CallmeHongmaybe lets connect over email to collaborate further on this problem.

**Comment by CallmeHongmaybe** [comment]
Okay email sent.

**Comment by spiritanand** [comment]
Hey maintainers,
how can I and @CallmeHongmaybe collaborate on this issue together? Is it possible for two people to collaborate on the same issue?

**Comment by moT01** [comment]
[The code for this project lives here.](https://github.com/freeCodeCamp/demo-projects/tree/main/apps/javascript-calculator) If anyone wants to try and fix this issue, we would accept the changes.

You can collaborate however you want @spiritanand - get in touch with each other and pair up on it.

**Comment by spiritanand** [comment]
Yeah, @moT01! We will solve the problem together, but how will we get both of us assigned as the contributor of the PR we create?

**Comment by CallmeHongmaybe** [comment]
We also have another change coming up right @spiritanand ?

**Comment by jadhavsiid** [comment]
Works fine on my PC

**Comment by ValdineiJunior** [comment]
Platform: Windows 10 Pro
Browser: Chrome Versão 114.0.5735.110
I was testing a few different inputs and found this behavior:
For example, when typed just "=" it gives the result NaN. If you use an operator, it includes NaN in the sum.
As in "= + 15 =" results in "NaN ".
When result is Ifinity as in "10/0" and operator is used, also use Ifinity in the sum.
Only when typing a number does it discard the previous result. I believe it is not necessary to use NaN or Ifinity in sums.
![Screenshot_1](https://github.com/freeCodeCamp/freeCodeCamp/assets/43623234/993dfb19-f632-4414-b7dd-b97e39acf91e)
