### ISSUE TITLE
Variable not defined bug in 'Manipulate Arrays With shift' Waypoint.

### ISSUE THREAD

**Issue by staranjeet** [FreeCodeCamp/FreeCodeCamp#4904]
Variable `removedFromOurArray` should be defined. This is possibly causing a lint error.

![selection_001](https://cloud.githubusercontent.com/assets/4302268/11524252/3a3459b4-98ef-11e5-84c7-b86fafbcbdd8.png)

Workaround for this can be 
`var removedFromOurArray;` just above the line where shift is used.

**Comment by ltegman** [comment]
Fixed by PR #4870

Thanks!
