### ISSUE TITLE
Add debugging challenges to curriculum

### ISSUE THREAD

**Issue by oriooctopus** [freeCodeCamp/freeCodeCamp#49047]
An example of what I mean could be something like:

"The below code is supposed to change the monsters health when the user press is the attack button, but there's an issue. Fix the issue so that the attack button works and all tests pass". The issue could be some sort of common error that users make such as typing in the referenced variable incorrectly or writing the functions syntax wrong, etc

### Is your feature request related to a problem? Please describe.

Right now we only have one type of challenge in our courses which is  where are you right new code to implement a task. If we add the debugging challenges we get the following benefits:
- Breaking up the current monotony of having only one having one type of challenge
- Improve peoples' skills with debugging their own code on normal challenges
- As curriculum curators we now have an additional tool that we can use to emphasize certain concepts.
- it can be a good way to help sharpen people's skills with syntax or help them review a concept

### Describe the solution you'd like

Under the hood this can be implemented the same way as normal coding challenges except that the starting code has a wrong version of the solution as opposed to no solution

### Describe alternatives you've considered

See "additional context" section below

### Additional context

This was discussed on discord. See the messages after https://discord.com/channels/692816967895220344/715074489422970962/1060991198556340364

In the future I think there should be even more types of challenges such as multiple choice challenges (to be clear I'm not talking about heavily relying on this type of challenge, I am talking about using multiple choice challenges occasionally for emphasizing certain concepts). Another type of challenge could be a more freeform, self-evaluation type of code challenge.

**Comment by naomi-lgbt** [comment]
This would be blocked until #49018 is resolved - currently we cannot run tests on code with certain errors.

**Comment by oriooctopus** [comment]
Hmm, I've just left a comment in the issue saying that it shouldn't be an issue/should be easy to resolve if we are only talking about pure JavaScript. Perhaps we can start off with challenges that only involve changing the JavaScript?

**Comment by diegoperezm** [comment]
Hi [oriooctopus](https://github.com/oriooctopus).

> In the future I think there should be even more types of challenges such as multiple choice challenges (to be clear I'm not talking about heavily relying on this type of challenge, I am talking about using multiple choice challenges occasionally for emphasizing certain concepts). Another type of challenge could be a more freeform, self-evaluation type of code challenge.

Something similar to  "The Little Schemer" (Daniel P. Friedman && Matthias Felleisen)   or more like "Lists and Lists" (Andrew Plotkin)?

**Comment by diegoperezm** [comment]
> @diegoperezm can you clarify?



Sure,  @oriooctopus :+1:  .


 - "The Little Schemer"(from https://www.crockford.com/little.html, Douglas Crockford):

> After reading the book, I was changed. In a good way. There are very few books that deeply change the way that you think. This is one of those books.

> The format is a programmed text with questions on the left side and answers on the right. The way you use it is to read a question, think about the question, come up with an answer, and then compare your answer to Friedman's answer.

  As you can see this is different from the traditional approach: explain a concept, show an example and expect that the student have the necessary skills to solve the exercise.

 `The Little Schemer` uses a chain of questions-answers to arrive at the code. The idea is to `think, come up with an answer, and then compare` and  _not_  memorize facts.    

 - "Lists and Lists" (Andrew Plotkin):

     Is a game-tutorial (Interactive Fiction). You try things to solve the exercises, the fact that you have limited options makes it a "guided" tutorial.

**Comment by diegoperezm** [comment]
Anyway. Another option to add debugging challenges is to take the same approach  as the one used in the forum: ask questions (a sort of checklist).

If we use the forum as a reference, many times `asking for help` is limited to write "it doesnt'work/"why doesn't it work?". When someone says "why doesn't it work?" it indicates that they don't have the skills to start analyzing the problem. Knowing what to ask is important when learning  to debug.

This can be easily implemented: add to the "Get Help" button a section:  "checklist" or something similar or it can be done in a more complex way: asking them to write function signatures, comments,  unit tests, use a debugger, etc (this is the approach of the book "How to design programs", Matthias Felleisen, Matthew Flatt, Shriram Krishnamurthi).

Have a nice day.

**Comment by oriooctopus** [comment]
Thanks. Right now I think the courses are setup to have lots of small steps that the user fully solves. I agree that getting the user to think independently on larger problems without the stress of having to get everything right (like what you're saying about seeing the answer after they guess) is useful because it more resembles the real world.

> This can be easily implemented: add to the "Get Help" button a section: "checklist" or something similar or it can be done in a more complex way: asking them to write function signatures, comments, unit tests, use a debugger, etc 

I think this is already mostly done with hints, no?

**Comment by diegoperezm** [comment]
> I think this is already mostly done with hints, no?

Not really, an example:


 - freeCodeCamp Challenge Guide: Where do I Belong

https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-where-do-i-belong/16094

#### Hints:

Hint 1:
The first thing to do is sort the array from lower to bigger, just to make the code easier. This is where sort comes in, it needs a callback function so you have to create it.

Hint 2
Once the array is sorted, then just check for the first number that is bigger and return the index.

Hint 3
If there is no index for that number then you will have to deal with that case too.


#### Forum

OP: 

> Hi there. I am a bit stuck. Would like an input, where is the error. Thanks
 
RandellDawson (Question): 

> If I have the following:
  const arr = [3, 10, 5];
  arr.sort()
What does arr look like after the above code executes? 

OP: 
> According to my limited knowledge should be [3, 5, 10].

RandellDawson: 
> Test the code and see.

---

As you can see is a different approach.

Also, users do not write unit tests,  nor do they write comments, very few have used a debugger before asking on the forum. In general they only focus on finding the answer to pass the challenge.

**Comment by Sembauke** [comment]
We have plans to do this in our upcoming curriculum.
