### ISSUE TITLE
Sign Up button disappears on scroll down

### ISSUE THREAD

**Issue by timagixe** [freeCodeCamp/freeCodeCamp#49046]
### Describe the Issue

When reading some posts on FCC Forum, after scrolling down the sign up button disappears from top navigation menu (top navbar)

### Affected Page

Forum post page (i.e. https://forum.freecodecamp.org/t/responsive-web-design-updates/508345)

### Steps to Reproduce

1. Go to 'https://forum.freecodecamp.org/'
2. Click on  any post i.e. 'https://forum.freecodecamp.org/t/responsive-web-design-updates/508345'
3. Scroll down couple of times
4. See `sign up` button disappears in top nav

### Expected behavior

I believe that sign up button should stay as is and should not hide.

### Screenshots

https://user-images.githubusercontent.com/60817786/212722437-4f58a5a2-1a5b-4da0-9eca-e2e96ff8379b.mp4

### System

- Device: Laptop
- OS: MacOS
- Browser: Chrome
- Version: Version 109.0.5414.87 (Official Build) (arm64)

**Comment by Ankitchaudharyy** [comment]
I can work on this issue. Please assign this to me.

**Comment by RishabhSingh4872962** [comment]
i can also work on this issue

**Comment by aj9045j** [comment]
i want to work on this issue please assign this issue to me

**Comment by ShaunSHamilton** [comment]
The freeCodeCamp Forum is an instance of [Discourse's software](https://www.discourse.org/). As such, this appears to be on their side. It could also be behaviour from a plugin we use.

Either way, this does not appear to be a bug/problem. It looks intentional - although odd.

As such, I am going to close this issue.
