### ISSUE TITLE
Cannot complete with Firefox (exact replica code works in IE)

### ISSUE THREAD

**Issue by sisulla** [FreeCodeCamp/FreeCodeCamp#4909]
Challenge [Waypoint: Add Different Padding to Each Side of an Element](http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element?solution=%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A10px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3Ared%3B%0A%20%20%20%20padding-top%3A%2040px%3B%0A%20%20%20%20padding-right%3A%2020px%3B%0A%20%20%20%20padding-bottom%3A%2020px%3B%0A%20%20%20%20padding-left%3A%2040px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding-left%3A%2040px%3B%0A%20%20%20%20padding-top%3A%2040px%3B%0A%20%20%20%20padding-right%3A20px%3B%0A%20%20%20%20padding-bottom%3A20px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding:10px;
  }
  
  .red-box {
    background-color:red;
    padding-top: 40px;
    padding-right: 20px;
    padding-bottom: 20px;
    padding-left: 40px;
  }

  .green-box {
    background-color: green;
    padding-top: 40px;
    padding-right:20px;
    padding-bottom:20px;
    padding-left: 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by zainamanzoor** [comment]
I have exactly the same problem right now.Have any luck so far ? @sisulla

**Comment by avkrisp** [comment]
Same issue faced with Firefox, any luck?hate to skip the challenge...

**Comment by sisulla** [comment]
I completed it (and the other padding/margin related) challenges using IE and then switched back to Firefox. This way I was able to complete all. Hope it helps.

**Comment by bugron** [comment]
@sisulla thanks for posting. We have a PR which will fix this. The origin of this issue goes to #4865.
