### ISSUE TITLE
Time-line scroller positioning 

### ISSUE THREAD

**Issue by SanjeevSingh08** [freeCodeCamp/freeCodeCamp#49106]
### Describe the Issue

When we scroll the screen and then again go back to the starting of the page, the time-line scroller is wrongly positioned.
https://www.awesomescreenshot.com/video/14184623?key=db941f2c680ddd5d83297c6cfde105a0

### Affected Page

https://forum.freecodecamp.org/t/responsive-web-design-updates/508345

### Steps to Reproduce

1. Go to 'https://forum.freecodecamp.org/t/responsive-web-design-updates/508345'
2.Scroll down to bottom
3. Again go back to top of the page

### Expected behavior

The time line scroller should not be be wrongly positioned

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by chs-mix** [comment]
Hi could I please work on this issue?

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

The freeCodeCamp Forum is an instance of [Discourse's software](https://www.discourse.org/).

This appears to be an issue with their styling: https://github.com/discourse/discourse/blob/main/app/assets/stylesheets/common/topic-timeline.scss

As such, I am going to close this.
