### ISSUE TITLE
TypeError in basic Javascript challenge

### ISSUE THREAD

**Issue by siddhesh-athalekar** [FreeCodeCamp/FreeCodeCamp#4910]
In "Waypoint: Understand Boolean Values", I am getting this error : "Waypoint: Understand Boolean Values" everytime, even after I refresh the page. Even when I am putting the correct value of "return true;", the same error persists and am unable to move to the next challenge.

Please check :)

**Comment by DDaems** [comment]
Can you please use the Bug button at the challenge to report a github issue. 
With your changes allready made in the editor. This will provide us with allot more information.
Thanks

**Comment by abhisekp** [comment]
@siddhesh-athalekar What browser are you using? FCC officially supports only Chrome.

**Comment by bugron** [comment]
@siddhesh-athalekar thanks for posting this issue!
We have an open PR which will fix this. Closing this issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
