### ISSUE TITLE
Create a Module Script 

### ISSUE THREAD

**Issue by sajibcd34pro** [freeCodeCamp/freeCodeCamp#49119]
### Describe the Issue

Here I have submitted everything fine but timeout error is showing repeatedly in console
my code is : <script  type="module" src="index.js"></script>

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/create-a-module-script

### Your code

```
<script type="module" src="index.js"></script>
```

### Expected behavior

My code should work.

### Screenshots

![Screenshot (152)](https://user-images.githubusercontent.com/85417425/214099663-04922821-9dbd-4ac5-8b64-73bdd4361dd3.png)

### System

- Device: PC
- OS: [Windows 10]
- Browser: [Chrome,]

**Comment by jdwilkin4** [comment]
I just ran your code and it is working on my end.

I would suggest reseting the lesson and trying again or trying a different browser.
I was testing it on Google chrome and it passed for me.

**Comment by a2937** [comment]
I was testing it on Firefox on my end and works fine as well. If it doesn't work in either of these two browsers, maybe check your browser plugins and see if they are interfering with the tests.

**Comment by Sboonny** [comment]
Closing because can't replicate
