### ISSUE TITLE
cannot move to next chapter

### ISSUE THREAD

**Issue by yashmehta332** [FreeCodeCamp/FreeCodeCamp#4912]
Challenge [Waypoint: Change the Color of Text](http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text?solution=%3Ch2%20style%3D%22color%3A%20blue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h2 style="color: blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

The color in the mobile changes. But, I cannot move to next chapter. I'm stuck.
Please help.

**Comment by DDaems** [comment]
Your h2 element should be `red`.

**Comment by abhisekp** [comment]
@yashmehta332 You may also use https://gitter.im/FreeCodeCamp/Help for help about these.

**Comment by bugron** [comment]
@yashmehta332 thanks for posting this issue!
@DDaems is correct. As @abhisekp mentioned if you have problems with your code, please, post a message in our [Gitter chat room](https://gitter.im/FreeCodeCamp/Help) first, thanks. Closing this issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
