### ISSUE TITLE
The profile page should make it more obvious that they can edit it

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49133]
### Is your feature request related to a problem? Please describe.

Yes https://github.com/freeCodeCamp/freeCodeCamp/issues/49132, it's easy to add broken results for beginners.

### Describe the solution you'd like

Add button that navigate to the portfolio section in the setting page, this will be QoL improvement, if a URL becomes broken or image becomes broken, and camper can move fast to that section of the page

### Describe alternatives you've considered

The ability to edit it in the portfolio page itself?

**Comment by anonymous-baaka** [comment]
i would like to work on this issue. Please do assign if no one else is working on it right now.

**Comment by Sboonny** [comment]
Only issues with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ahmadabdolsaheb** [comment]
Based on my understanding, we are moving the portfolio setting's to the portfolio itself.

**Comment by Sboonny** [comment]
That what Sem suggested, if you are okay with it, I can open this for contribution or start working on it.

I really don't mind if it's button that send to setting page, or profile page has an edit button for this, just want a better experience for the users.

**Comment by ahmadabdolsaheb** [comment]
Yes, we can open an umbrella issue with some user stories from our discussions. Once that is done, I could go ahead with a mock/wireframe and the feature prs could follow up.

**Comment by Sboonny** [comment]
Point mentioned by Tom in the dev meeting, the setting page isn't well organized, it would be better to move the setting related to profile page, and let campers edit it in the profile section.

**Comment by Sembauke** [comment]
Hey @ahmaxed,

What do you think about adding a button to the profile page that takes you to the settings page to edit your profile?

Or does it not fit the upcoming design?

**Comment by ahmaxed** [comment]
The profile settings should be relocated to the profile page. 
Here is the mock:
https://www.figma.com/design/4M7uEe9kH8hgZdB07lBvj9/Untitled-(Copy)?node-id=0-1

**Comment by ojeytonwilliams** [comment]
Alright, thanks Ahmad. Looks like the feature is already in the works, so we can close this.
