### ISSUE TITLE
Not Testing Solution - Freeze Tab Browser

### ISSUE THREAD

**Issue by gonzalorodriguez** [FreeCodeCamp/FreeCodeCamp#4913]
Challenge [Bonfire: Where do I belong](http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
When I try to run tests, tab browser not response. After that, if I try to reload page, the issue still persist..

My code:
```javascript
function where(arr, num) {
  // Find my place in this sorted array.
arr.sort();
var  i  = 0 ;
var position = 0;
var exit = false;

while(!exit || i < arr.length)
{
     if(num <= arr[i])
     {
          position = i;
          exit = true;
     }
     i++;
}
  return position;
}

where([40, 60], 50);

```

**Comment by DDaems** [comment]
You created yourself a infinite loop,
while `where([40, 60], 50);` test will pass.

`where([3,2,1])` this will fail because
`exit = true` will never happen when 50 > 3, 2, 1

`While(exit === false OR i < arr.length)` resulting in the loop allways looping. Even if I > arr.length

**Comment by gonzalorodriguez** [comment]
Ohh Thank A lot!.
Excuseme for this kind of mistake.
Thanks to show me and teach me, this precaution.
@DDaems

**Comment by bugron** [comment]
Closing this issue as resolved then, thanks @DDaems and @gonzalorodriguez.
