### ISSUE TITLE
"Create a help post on the forum" button not working for RWD certification projects

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#49141]
### Describe the Issue

When I click "Create a help post on the forum" button nothing happens.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form and other RWD certification projects (either new or legacy)

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form
2. Click on 'Get Help' > 'Ask for Help' > ' Create a help post on the forum'
3. Nothing happens. You can see the following error in DevTools' console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at create-question-epic.js:54:68
    at Array.some (<anonymous>)
    at t._tapNext (create-question-epic.js:54:25)
    at t._next (tap.js:44:21)
    at t.next (Subscriber.js:54:12)
    at t._next (filter.js:37:24)
    at t.next (Subscriber.js:54:12)
    at e.observe (Notification.js:22:42)
    at t.dispatch (observeOn.js:41:18)
    at t._execute (AsyncAction.js:63:12)
```

### Expected behavior

You can open a forum post draft with the current code

### Screenshots

https://user-images.githubusercontent.com/25644062/214681210-99a1042d-79b5-4b8e-8501-36f1a4e2a338.mp4

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: Version 109.0.5414.120 (Official Build) (64-bit)

### Additional context

- It's working properly for certification projects other than new/legacy RWD and other challenges.
- After this issue happens, the Change Language functionality stops working too (nothing happens when you click a language) until you refresh the page.

**Comment by gikf** [comment]
Not sure if something changed in the meantime, but I'm not getting this behavior. Draft post is opened normally.

**Comment by bbsmooth** [comment]
I am able to replicate. The console error I am seeing is:

`Uncaught TypeError: e.editableRegionBoundaries is undefined    create-question-epic.js:54:33`

Firefox 108/Fedora 36

**Comment by gikf** [comment]
> Uncaught TypeError: e.editableRegionBoundaries is undefined create-question-epic.js:54:33

I can reproduce this when having anything (even single space) in the `index.html` or `style.css`.
