### ISSUE TITLE
Improve the UX in portfolio section in the setting page

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49144]
The interactive experience with the Portfolio Settings in setting page can be improved. https://www.freecodecamp.org/settings

- [x] We can change the generic alert message from `update your prefernces` to something like "updated the item in your portfolio page".
- [ ] After saving the context of the portfolio item, we can change the button text to "Edit this portfolio item".
- [ ] When the item isn't saved, instead of "Remove the item button", we can add a button that clears the inputs. 
- [ ] To help with #49132, we can display image based on camper input, something like.
- [ ] add `alt` text input to the settings.

```ts
<input onChange={imageUrl = value} />
  <img src={imageUrl} alt="display a preview of the image" />
```

**Comment by bbsmooth** [comment]
If we want to make these portfolio items more accessible we might consider adding an alt text input for the image. Otherwise, I would suggest we use `alt=""` on these images because using the alt text "A screen shot of [title]" does not really provide any useful information for screen reader users.

**Comment by Bidhu1024** [comment]
I can work on this. Do let me know what else you need. @Sboonny

**Comment by Sboonny** [comment]
You can add a conditional rendering to this section in the setting, that display different text for portfolio setting.

![image](https://user-images.githubusercontent.com/88248797/228632878-53cf2af0-d17a-417c-895b-8638e533364a.png)

That should take care of the 2nd or 3rd checkbox, up to you 👍

**Comment by Bidhu1024** [comment]
For sure I can fix this. Please assign the issue to me. @Sboonny

**Comment by Sboonny** [comment]
Feel free to open PR directly. You can find more by reading [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by Bidhu1024** [comment]
Sure @Sboonny

**Comment by Bidhu1024** [comment]
I'm going through the contribution docs now, and soon start the fixes. Thanks @Sboonny

**Comment by alokVerma749** [comment]
> You can add a conditional rendering to this section in the setting, that display different text for portfolio setting.
> 
> ![image](https://user-images.githubusercontent.com/88248797/228632878-53cf2af0-d17a-417c-895b-8638e533364a.png)
> 
> That should take care of the 2nd or 3rd checkbox, up to you 👍
can anybody please explain the required changes here

**Comment by Sembauke** [comment]
Hey @ahmaxed ,

Can you take a look at this and see if we still want this?
