### ISSUE TITLE
Fallback Image for broken image url in portfolio section in portfolio page

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49146]
in https://www.freecodecamp.org/Muhammed-test-account. You will notice "screenshot of zsdaf".

![image](https://user-images.githubusercontent.com/88248797/214813617-90b53edc-f7a2-45e9-8d31-e6e89df77843.png)

Instead of showing alt text, we can fallback to an image. My suggestion is the Glyph from the style guide https://design-style-guide.freecodecamp.org/

**Comment by egomezbpedro** [comment]
Hi @Sboonny,

I tested the same in my own [profile](https://www.freecodecamp.org/fcc21faf009-f16f-485c-b115-f503e4d0827e) and I see a similar outcome as you with the image that you mention. I also tryed to use different [photo](https://t4.ftcdn.net/jpg/00/97/58/97/360_F_97589769_t45CqXyzjz0KXwoBZT9PRaWGHRk5hQqQ.jpg) and it gets rendered correctly.

In the component for the portfolio-projects.tsx I do see that no alt text is implemented. 
```
{image && ( <img alt='' className='portfolio-screen-shot' src={image} /> )}
```
To load another image as alternative if the one provided by the user fails we would need to implement an on error function that loads a fallback image. I'm not that proficient with TS but I will try to craft a PR for this particular approach.

**Comment by shrigharat** [comment]
I would like to work on this issue. Can you kindly assign this issue to me @Sboonny ?

**Comment by Harsh-Mathur-1503** [comment]
I would like to work on this issue.
Can you kindly assign it to me?
@Sboonny

**Comment by Harsh-Mathur-1503** [comment]
@camperbot sure no problem

**Comment by weilirs** [comment]
I clicked the https://www.freecodecamp.org/Muhammed-test-account, but the portfolio section is blank.
<img width="1161" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/62249815/b05ac33a-3943-4fb2-a5d0-7376ddb8bf1b">
