### ISSUE TITLE
/javascript-skills-you-need-for-react-practical-examples/ - .catch() code is missing 2nd closing parentheses 

### ISSUE THREAD

**Issue by tim-andes** [freeCodeCamp/freeCodeCamp#49154]
### Describe the Issue

/javascript-skills-you-need-for-react-practical-examples/ - .catch() code is missing 2nd closing parentheses  

causes error

```
TypeError
Cannot assign to read only property 'message' of object 'SyntaxError: /src/App.js: Unexpected token, expected "," (15:67)

  13 |       .then(response => response.json())
  14 |       .then(data => setAvatar(data.avatar_url))
> 15 |       .catch(error => console.error("Error fetching data: ", error);
     |                                                                    ^
  16 |   }, []);
  17 |  
  18 |   return ('
```

### Affected Page

https://www.freecodecamp.org/news/javascript-skills-you-need-for-react-practical-examples/

### Steps to Reproduce

1. https://www.freecodecamp.org/news/javascript-skills-you-need-for-react-practical-examples/#:~:text=fetch%20data%20from%20my%20GitHub%20API%20using%20the%20Fetch%20API
2. Copy code for react.new
3. Paste code in, see error, add closing parentheses after `error)`

### Recommended fix or suggestions

Review/fix code blocks in article, that's the second broken code block I found in there

### Screenshots

<img width="1129" alt="Screenshot 2023-01-26 at 10 00 28 AM" src="https://user-images.githubusercontent.com/64085493/214900142-1a0edcee-a6ab-4894-851d-228f94ab66ea.png">

**Comment by kuswanth-kumar** [comment]
It looks like there is a missing parenthesis at the end of the console.error statement, if you add it the error will be resolved.

.catch(error => console.error("Error fetching data: ", error));

![Screenshot_20230127_155435](https://user-images.githubusercontent.com/123728186/215063983-290daf14-270a-4914-9f86-94020131e11a.png)

**Comment by scissorsneedfoodtoo** [comment]
Hi @tim-andes, thanks for reporting this and for all of those helpful details.

I went through the article, ran all the code snippets through Prettier, and fixed a few issues, including the one you mentioned here.

The fixes should go live in the next couple of hours.

Please let us know if you find issues in any other articles.
