### ISSUE TITLE
/javascript-skills-you-need-for-react-practical-examples/  - "Ternary operators" code block is missing closing curly brace

### ISSUE THREAD

**Issue by tim-andes** [freeCodeCamp/freeCodeCamp#49153]
### Describe the Issue

Missing a closing curly brace in code block after the ternary expression

### Affected Page

https://www.freecodecamp.org/news/javascript-skills-you-need-for-react-practical-examples/

### Steps to Reproduce

1. https://www.freecodecamp.org/news/javascript-skills-you-need-for-react-practical-examples/#:~:text=Ternary%20operators%20can%20also%20be%20used%20inside%20curly%20braces%20(again%2C%20since%20it%20is%20an%20expression)%3A
2. https://codesandbox.io/ - paste code block in, see error. Add `}` before closing `</div>` tag 

### Recommended fix or suggestions

Add `}` before closing `</div>`

### Screenshots

<img width="1170" alt="Screenshot 2023-01-26 at 9 23 32 AM" src="https://user-images.githubusercontent.com/64085493/214890945-aa17cc7e-db9b-4815-911f-170f6bbd755c.png">

**Comment by kailash-kangne** [comment]
I am not able to find page after fork, please tell me folder path.

**Comment by ShaunSHamilton** [comment]
@kailash-kangne 
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

This issue relates to the news platform. The article content is not open-source, and must be edited by someone with authorization. Hope this clarifies.

**Comment by scissorsneedfoodtoo** [comment]
Hi @tim-andes, thanks for reporting this and for all of those helpful details.

I went through the article, ran all the code snippets through Prettier, and fixed a few issues, including the one you mentioned here.

The fixes should go live in the next couple of hours.

Please let us know if you find issues in any other articles.
