### ISSUE TITLE
Use react suspense to load the element when it's ready, instead of JavaScript

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49151]
We are using JavaScript to wait for API to be ready, then render some components, this isn't the React way to do things.

Example:

```ts
     if (showLoading) {
        return <Loader fullScreen={true} />;
      }
      return <FourOhFour />;
```

https://github.com/Sboonny/freeCodeCamp/blob/240655ecd4c4ead1906c3c07ba10e4ad28af4622/client/src/client-only-routes/show-profile-or-four-oh-four.tsx#L74-L84?plain=1

```ts
  if (showLoading) {
    return <Loader fullScreen={true} />;
  }
```

https://github.com/Sboonny/freeCodeCamp/blob/240655ecd4c4ead1906c3c07ba10e4ad28af4622/client/src/client-only-routes/show-settings.tsx#L149-L151?plain=1

React provides a better way of doing things, https://beta.reactjs.org/reference/react/Suspense#caveats. we can use this instead to provide a better experience for the campers.

For example, there is two searchbars, one optimized and the other isn't. we can use suspense to display the optimized one, while the other one is loading.

```ts
        <Media minWidth={MAX_MOBILE_WIDTH + 1}>
          <Suspense fallback={<SearchBarOptimized />}>
            <SearchBar />
          </Suspense>
        </Media>
```

Here is branch, if you want to mess with the searchBar https://github.com/Sboonny/freeCodeCamp/tree/lazyload/searchbar

This will result in the searchbar being displayed in homepage, and if it take too long to load it display the optimize one.

---

If we do this we can add `Errorbondary` later one https://github.com/bvaughn/react-error-boundary, to have fault tolerance in our codebase, which will allow us to display 3rd component if the API fails, may display a button for camper that refresh the page or a function that ask the API to rerun.

**Comment by SahilAnower** [comment]
Does this issue need help?

**Comment by Sboonny** [comment]
Nope, only issues with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. 

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by SahilAnower** [comment]
Okay Thanks!

**Comment by Vansh-Baghel** [comment]
So if we would want to replace 
This : 
```JS
     if (showLoading) {
        return <Loader fullScreen={true} />;
      }
      return 
```
We can use this :
```JS
<Suspense fallback={<Loader fullScreen={true} />}>
  <FourOhFour />
</Suspense>
```
Right?

**Comment by Sboonny** [comment]
And lazy load the component https://beta.reactjs.org/reference/react/lazy#returns

**Comment by mud1tx** [comment]
@Sboonny I can work on this feature easily as I have already used `Suspense` and know how to lazy load components in suspense. Please assign it to me.

**Comment by Vansh-Baghel** [comment]
> And lazy load the component https://beta.reactjs.org/reference/react/lazy#returns

Noted!!

**Comment by Sboonny** [comment]
@mud1tx, you can open PR after reading our [contribution guide](https://contribute.freecodecamp.org/#/), I remember @Vansh-Baghel wanting to work on this, if you want to collab.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by mud1tx** [comment]
@Sboonny Thanx Sboonny, I will read the guidelines before contributing.

**Comment by Vansh-Baghel** [comment]
@Sboonny Hey I see this code in /show-settings.tsx, so may I wrap the full return with Suspense or let it be the way it is and only change where only one component is rendered and not the whole? 
![image](https://user-images.githubusercontent.com/103327712/233311560-1a3b5c9d-41cd-4504-a064-6e9e81b447d4.png)
