### ISSUE TITLE
Create outline for expanded JQuery section

### ISSUE THREAD

**Issue by gotrhythm88** [FreeCodeCamp/FreeCodeCamp#4915]
Create a list of waypoint titles and content notes to cover more of the JQuery library

**Comment by gotrhythm88** [comment]
Reference - expanded Javascript curriculum outline
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3881

**Comment by benschac** [comment]
https://www.reddit.com/r/javascript/comments/3hq3o0/is_jquery_dying/


Not that FCC.  I'm just a fellow camper, but maybe it's worth it to use someone else's free content like CodeSchool or codecademy and FCC can focus on other fun stuffs?

**Comment by bugron** [comment]
Seems no one is interested to work on this. Closing this issue as stale. @gotrhythm88 thanks for posting.

**Comment by benschac** [comment]
R.I.P Jquery.

**Comment by ghostsleeper7** [comment]
Hello am I messing. Someone's work up I'm trying this class and been at it to long if I'm messed up I'm sorry please advise and I'll do my best to fix
