### ISSUE TITLE
learn-the-css-box-model-by-building-a-rothko-painting challenge - missing information about different css box models

### ISSUE THREAD

**Issue by plxel** [freeCodeCamp/freeCodeCamp#49156]
### Describe the Issue

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/

Challenge called "Learn the **css box model** by..."
There are bunch of steps which describes some parts of the box model, a lot of steps about changing colors etc
But it looks like there is no step describing that there are different models available like content-box, border-box etc
And in the next project https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-7 there is a phrase:

> Normalize your box model by creating a * selector and setting the box-sizing property to border-box as the value.

But there was no information before that about border-box and what is it and why we are setting it to border-box here

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/

### Steps to Reproduce

Just go through challenge

### Recommended fix or suggestions

It will great if "Learn the css box model" project will include information about different box-sizing values

**Comment by kuswanth-kumar** [comment]
*{
  box-sizing : border-box;
}
please check this...I think it is correct
![Screenshot_20230127_152048](https://user-images.githubusercontent.com/123728186/215057385-002d6849-4a21-4b86-ac36-7d60db1e2029.png)

**Comment by plxel** [comment]
@kuswanth-kumar 
yeah, I've seen this. 
but, before that there was no explanation about box-sizing property and what values it can have
it seems to me that it will be nice to learn this in "learn css box model section"

**Comment by Vansh-Baghel** [comment]
I think there is no change being reflected after using the border box on the right hand side, so its quiet tough for user to determine what happened after using it.

**Comment by Nirajn2311** [comment]
We need to add a lesson before this which introduces the `box-sizing` property to give clarification to the user.

**Comment by shivanikumari24** [comment]
body { margin: 0;
font-family: sans-serif;
background-color: #f5f6f7;
}

[  <img width="1280" alt="Screenshot 2023-03-31 at 9 22 33 PM" src="https://user-images.githubusercontent.com/78164260/229171461-ca55eb2f-0be9-4a92-bc66-fd3332d4f35c.png">
](url)

**Comment by CBID2** [comment]
Hi @miyaliu666. This is the issue I’ve trying to solve. I added a lesson on the box-sizing property

**Comment by miyaliu666** [comment]
Hi @CBID2 thank you for the update. As the [doc](https://contribute.freecodecamp.org/#/how-to-translate-files) shows, we usually translate curriculum on Crowdin. If the new lesson is added to Crowdin, I'll translate it into Chinese soon.

**Comment by CBID2** [comment]
> Hi @CBID2 thank you for the update. As the [doc](https://contribute.freecodecamp.org/#/how-to-translate-files) shows, we usually translate curriculum on Crowdin. If the new lesson is added to Crowdin, I'll translate it into Chinese soon.

Thanks @miyaliu666! I added the lesson in the PR that I showed you

**Comment by miyaliu666** [comment]
Hi @naomi-lgbt could you check if we can translate the new step? I don't see it on Crowdin. Thanks.

**Comment by CBID2** [comment]
> Hi @naomi-lgbt could you check if we can translate the new step? I don't see it on Crowdin. Thanks.

Hey @miyaliu666. I think this message on Discord would help: https://discord.com/channels/692816967895220344/986360173381705838/1140124340608847893

**Comment by naomi-lgbt** [comment]
The PR will need to be merged before translations can be made. I've synced the necessary files to allow the tests to pass.
