### ISSUE TITLE
Networking: Write a Web Browser | Duplicated answers, only one right

### ISSUE THREAD

**Issue by TrynaChill** [freeCodeCamp/freeCodeCamp#49164]
### Describe the Issue

So, in the course "Scientific Computing with Python", in the chapter of "Networking: Write a Web Browser", the first exercise asks what the code will create, with multiple choice answer. The problem is that the first and last option ("A simple web server") is duplicated, but only the last one will be marked as correct.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/networking-write-a-web-browser

### Steps to Reproduce

1. See that 1st option and the 4th option is the same
2. Choose the 1st option, get "Sorry, that's not the right answer. Give it another try?" as a response (see first image)
3. Choose the 4th option, having the same text but different position, get "Encore!" as a response (see second image)
![imagen](https://user-images.githubusercontent.com/101139603/215052666-04903e3d-5f1b-4c47-b14a-3113d2dcabd5.png)
![imagen](https://user-images.githubusercontent.com/101139603/215052722-b8922fd0-64f1-4987-bcc4-48f408bd0567.png)

### Recommended fix or suggestions

Put either both options as correct or change the 1st one, which is the wrong one, with a different text

**Comment by gikf** [comment]
Hey @TrynaChill,

Thank you for reporting this issue.

Take a closer look at both answers, they are differing a bit
> A simple web server.
> A simple web browser.

As there isn't anything to fix here, I'm going to close the issue.

Thank you and happy coding.

**Comment by TrynaChill** [comment]
srry, i missread it, im reallly srry
