### ISSUE TITLE
Proposal to change current mono font to JetBrains Mono

### ISSUE THREAD

**Issue by icarusgk** [freeCodeCamp/freeCodeCamp#49174]
### Describe the Issue

# Hello freeCodeCamp Community 😄✌🏻

To start my issue I have to give a little of backstory. It dates back to issue #46530 (first posted on June 16, 2022) where fellow dev `bbsmooth` discusses that he has had "two different forum posts today in which the user thought the lowercase L was the number 1 in the HTML code examples". 

The examples given are that people couldn't identify between `<ul>` and thought it was a `<u1>` instead because of the similarity that the `l` had with the `1` on the font being used at the time: Roboto Mono. You can see screenshots of said problem on the issue listed above.

I know it might be an overkill or seen as innecesary to change the fonts across the `/learn` area again. 
From Roboto Mono `->` to Hack-ZeroSlash `->` and now to JetBrains Mono.
But as I read the issue where it is discussed to change the overall font to Hack-ZeroSlash from Roboto Mono, I noticed JetBrains Mono was not taken into consideration:

![image](https://user-images.githubusercontent.com/38413630/215191823-899d56b2-4004-4797-b845-d5b33af9f2b7.png)

So, in this issue I would like to make some points in favor of `JetBrains Mono` that align with some of the problems discused on issue #46530 and highlight how this font can potentially address them, and to also demonstrate the benefits of using JetBrains Mono over other fonts. 

## The `0 O 1 l | I` problem

In some mono fonts the `0 O 1 l | I` characters look similar and can confuse people, such as the `<ul>` and `<u1>` problem. In other cases people can get confused by a `0` (zero) or a `O` (uppercase O). `Hack-ZeroSlash` aims to solve some of this problems by adding a slash to the zero and be able to distinguish between `l` and `1`, something that `Roboto-Mono` lacked.

`ahmadabdolsaheb` points out that:
> It seems like we need to be looking for a "namely being sans-serif, fixed-width, slashed zero, and sufficient differentiation between the characters 1, l, |, and I." Here is a helpful [thread](https://ux.stackexchange.com/questions/46142/need-a-font-with-unambiguous-letters-for-commonly-confused-characters). [...]
_Originally posted by @ahmadabdolsaheb in https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1188931519_

Other fonts were discussed such as Fira Code (dropped because of ligatures) and as `ahmadabdolsaheb` points out:
> [...] ligatures are great but I am sure new users are going face issues if they cannot find in the keyboard what they see in the example code blocks.
_Originally posted by @ahmadabdolsaheb in https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1240426891_

Fira Mono, Red Hat Mono, and Roboto Plex were also discussed but they were dropped because they didn't quite solved the problem.

Some of reasons they were dropped include:

- **Fira Mono**
  - [[...] I find the ampersand to be a little "weird" [...]](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1241236778)
  - [[...] I like the '&' in Hack better than Fira [...]](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1243665754)
- **Red Hat Mono**
  - [Red Hat Mono is a great alternative, but Hack seems to have a larger community behind it. [...]](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1246428573)
- **Roboto Flex**
  - [In my opinion, Roboto Flex (as found in Google fonts) does not make enough of a distinction between lowercase letter l and uppercase letter I.](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1239942871)

Some of the reasons `Hack-ZeroSlashed` was picked include:
- [[...] I think my real first choice might be Hack (which according to their documentation offers a way to customize glyph styles, so we could have a slashed zero with it) [...]](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1241236778)
- [[...] Hack would be my first choice too [...]](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1243665754)
- [Sure, if there is a slashed zero Hack, that would be pretty good](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1246653155)

`bbsmooth` made a [font comparison website](https://font-selector.surge.sh/) where these different fonts could be compared, but JetBrains Mono was not listed.

Though the discussion tilted in favor of the other fonts at times as in the case of Fira Mono: "[[...] I do think the percentage sign in something like Fira Mono is slightly better](https://github.com/freeCodeCamp/freeCodeCamp/issues/46530#issuecomment-1255219251)", Hack was the font-choice overall.

And I'm not listing or citing some of the comments made in the issue #46530 in a condescending tone or to demonstrate that a wrong choice was made, in any way 🙅🏽‍♂️. The team made the right choice by deciding to use `Hack-ZeroSlash` at the time because it solved the problem of some characters being confused, but I do think that an improvement can be made.

### Introducing `JetBrains Mono`! 🚀✨

[JetBrains Mono](https://www.jetbrains.com/lp/mono/) is a new and exciting font designed specifically for developers. This font has been created with the goal of improving readability, clarity, and productivity for programmers, it offers a range of features that can help to make your code more readable and easier to work with.

## How it solves the `0 O 1 l | I` problem

As listed on their website:

![image](https://user-images.githubusercontent.com/38413630/215212129-8a88ed52-9972-4a6b-963d-8bb266debeef.png)

Although the zero doesn't have a slash on it, I found a [repo](https://github.com/sharpjs/JetBrainsMonoSlashed) that added it.

Here's a comparison of both fonts:

![comparison-fonts](https://user-images.githubusercontent.com/38413630/215236310-1ab201bd-05d7-48a3-9791-dda8d45eda44.png)

There is a noticeable difference between the `l` and `1` characters as well:

![image](https://user-images.githubusercontent.com/38413630/215218105-d93abe2a-e2a6-4b1f-a0c5-7b11306eba5b.png)

It is a sans-serif, fixed-width font by default, and now with the help of the modded font we have a slashed-zero too!

### Comparison between Hack and JetBrains Mono

The following GIF compares both fonts on freeCodeCamp's editor:

![comparison-pf](https://user-images.githubusercontent.com/38413630/215225655-0a42f18d-9856-4521-8dcd-d55d1bb6ce3c.gif)

_The fonts that are being compared are `Hack-ZeroSlash` and `JetBrains Mono Slashed` both with the slashed zero_

We can see that although Hack is a monospaced font, at times it creates this visual illusion around it that some of its characters are of variable width such as:

_(All the following comparisons were made directly on freeCodeCamp's editor are talking about the Hack font)_

- **Parenthesis** - It seems like there's more space inside the parenthesis.

![parenthesis-comparison](https://user-images.githubusercontent.com/38413630/215232108-9121e14e-b724-45cf-89de-d58b3afb4a5a.gif)

- **Brackets** - It seems like there's more space inside the brackets.

![brackets-comporison](https://user-images.githubusercontent.com/38413630/215232111-c41ff6ff-772b-4fbb-9186-bfaf4c01380c.gif)

- **Some characters have incogruent styles**

![characters-comparison](https://user-images.githubusercontent.com/38413630/215232116-c7539e7c-d57f-45ce-8e9d-ca00b318893c.gif)

**And of variable height** too, on the `||` characters for example:

![height-comparison](https://user-images.githubusercontent.com/38413630/215232120-9dc998b5-68e5-47cc-ba96-189e8db77809.gif)

As we can see JetBrains Mono focuses on consistent spacing and legibility, Here's the `learn/` page with both fonts:

![learn-section](https://user-images.githubusercontent.com/38413630/215233011-269afbb1-3763-4c79-82fa-bf6d2c31b0da.png)

And with a GIF to better distiguish the differences:

![learn-page-comparison](https://user-images.githubusercontent.com/38413630/215234294-6184fb03-ef02-4e53-aa44-7da4dc90119b.gif)

This change will also help issue #49054 because as shown in the screenshots above it will reduce the overall width of the contents using the proposed font.

The font will be used without ligatures because as previosly stated "new users are going face issues if they cannot find in the keyboard what they see in the example code blocks".

It is worth highlighting some of the key benefits of using JetBrains Mono over other fonts:

1. It has a larger character set and supports more languages, making it a more versatile option for developers working on projects with a global audience.
2. The font's design is optimized for clarity and readability, with a focus on consistent spacing and legibility. This can help to reduce eye strain and improve productivity for developers who spend long hours in front of the screen.
3. It is actively developed and maintained, with regular updates and improvements to ensure compatibility with new software and technologies, with the latest released happening [2 weeks ago](https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.304)
4. It has a more consistent font design, which can improve the overall aesthetic and readability of the code.

Another important aspect to consider is the [positive feedback](https://user-images.githubusercontent.com/38413630/215235119-96e4273b-7676-43ce-9c58-b8341a1c0e5a.png) JetBrains Mono has received from developers who have used it. [Here's a video that goes into detail about some of its best features](https://youtu.be/yKjpUCCyHu8)

In order to address the issue at hand, I am willing to work on a pull request that implements JetBrains Mono as the default font for freeCodeCamp. I will take into account all the points previously mentioned and make sure that the implementation is smooth and efficient. I will take #47767 as an example for said PR and will also be available to address any concerns or questions that may arise during the process and I am open to feedback and suggestions. I believe that this solution will greatly benefit the learning experience for our users and I am committed to making this happen.

I would also like to clarify I am in no way associated or am affiliated with JetBrains 😅

In conclusion, JetBrains Mono is a great choice for anyone looking to improve their coding experience. With its focus on readability and clarity, JetBrains Mono can help to make code more readable and easier to work with. With this proposal, **we can** take a step towards improving the overall reading and writing code experience for the people learning on freeCodeCamp. By implementing JetBrains Mono as the default font, we can provide a better coding experience for our learners.

### Affected Page

Main freecodecamp.org and several of `/learn/**` pages

### Steps to Reproduce

1. Go to [freecodecamp.org](freecodecamp.org)
2. Click on `'Get Started (it's free)'`
3. See the fonts

### Expected behavior

Replace the current monospace font with JetBrains Mono.

### System

- Device: [Laptop]
- OS: [EndeavourOS Linux]
- Browser: [Chrome]
- Version: [109]

**Comment by Ajuriaa** [comment]
![image](https://user-images.githubusercontent.com/64340735/215237942-ceb0f6ed-28c9-448b-99c5-2ecd1125c856.png)

**Comment by Ajuriaa** [comment]
JetBrains Mono > Hack-ZeroSlashed

**Comment by do-diegoortiz** [comment]
I appreciate the parenthesis and brackets spacing improvement 😎

**Comment by bbsmooth** [comment]
Since I was mentioned in this issue I guess I need to leave a comment :slightly_smiling_face: 

My initial reaction from the few comparisons shown above is that I like the looks of Hack better. For example, I much prefer the parens in Hack (they look more like normal parens I would write). I think the `W` and `w` in JetBrains is harder to read then those in Hack. I think the lowercase `c` looks too close to a lowercase `o` in JetBrains. And I'm not crazy about the JetBrains lowercase `i` either. But those are just my opinions and I'm sure others will feel differently.

Regardless of what I think, if some of the FCC devs want to entertain the possibility of switching then I will add JetBrains to my font comparison app so we can do further testing. Just let me know. 

> This change will also help issue #49054

Changing to JetBrains will not affect this issue. That issue has to do with the amount of visible real estate. That does not change with a different font.

**Comment by icarusgk** [comment]
Thanks for sharing your thoughts on the font comparison @bbsmooth.

I understand your perspective on the letters you shared. I think the design of the `W` is more distinguishable overall, the diagonal lines of the uppercase `W` meet at a more acute angle, which allows it to stand out more and fill the entire line height. This, combined with its consistent design with the lowercase `w`, improves the overall aesthetic and legibility of the code.

On the lowercase `c` and the lowercase `o` looking too close to each other, I think that the context of the code and the surrounding characters can also make it clear that the letter is a `c` or `o` and not cause a confusion between them. The lowercase `c`'s radical cut at the end of strokes fits the pixel grid better as well as the font's consistent spacing and design can also help to make the characters stand out, making it less likely that they will be mistaken for one another.

To better illustrate my points, here's an animated code snippet to help visualize the differences between the two fonts, using the letters you mentioned in your comment:

![wWioc](https://user-images.githubusercontent.com/38413630/215298769-49c9edf9-31b6-411d-8b19-9112680dd3b3.gif)

You can see that on JetBrains, characters remain standard in width as in height. In the `<script>` tag, for example, the `r` and the `i` seem to be farther than they seem like and this kind of behavior is what I meant by: 

> We can see that although Hack is a monospaced font, at times it creates this visual illusion around it that some of its characters are of variable width

It's important to have different perspectives and opinions on design choices like this, so your input on the differences between Hack and JetBrains is valuable, and I appreciate your willingness to add JetBrains Mono to your font comparison app for further testing 😄.

> Changing to JetBrains will not affect this issue. That issue has to do with the amount of visible real estate. That does not change with a different font.

You're right, I did the proper testing following the steps to reproduce in that issue. I apologize for making the claim without verifying it first through testing.

**Comment by g5llo** [comment]
I fully support this proposal to switch to JetBrains Mono as the default font. Its emphasis on readability and clarity make it a great choice for improving the coding experience. The positive feedback from developers who have used it speaks to its effectiveness. Let's enhance the learning experience on freeCodeCamp by implementing JetBrains Mono. #JetBrainsMonoFTW

**Comment by raisedadead** [comment]
Yeah - I agree with the points here – but as the "average normal" user (i.e., I do not have any a11y difficulties). It is generally a much more legible font for coding.

However, Bruce has done a great job pointing out the design choices that could be more challenging for some.

As someone who has been driving the font daily for a couple of years, I would say let's switch, but we want other opinions and side-by-side comparison.

**Comment by Sboonny** [comment]
Does the new font have margin or padding baked in it, that may cause misalignment like in this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/48909?

**Comment by icarusgk** [comment]
The font doesn't have margin built-in into it, I did the steps to reproduce listed on issue #48909 and it [didn't present](https://user-images.githubusercontent.com/38413630/215406069-98445c5f-4bcf-4d8d-8ff0-4ab387ba9091.png) the issue described.

> The context shouldn't be relied on, because we are teaching the code for beginners, and most of them don't have context of what they are doing yet. Furthermore, some of them are not native speakers, if they see soript, they will type soript.

I understand your point, context could be missing for beginners or non-native speakers as they are new to the keywords and syntax of the language they are being introduced too. Some changes could be made to the font to make it adapt more for these issues. Here's a modded font that addresses the issue of the possibility of the lowercase `c` being confused by the lowercase `o` and the extra angle or the `r`:

[`c` and `r` Comparison](https://user-images.githubusercontent.com/38413630/215408911-1fa1d927-8825-4d46-8de8-0a4a93743482.gif)
_I will link to images now, I don't want to clutter the issue more 😅_

It adds more space between the clear cuts of the `c` and lessens the angle of the `r`. In an effort of being less context dependent.

**Comment by icarusgk** [comment]
> As someone who has been driving the font daily for a couple of years, I would say let's switch, but we want other opinions and side-by-side comparison.

Yes, I agree, more opinions on this subject could be helpful. A possible poll on freeCodeCamp's Twitter account could provide valuable insights, as is a change that will impact the website's look and feel and how the user perceives it. 🤔

**Comment by icarusgk** [comment]
> Random question, is there a [Variable version](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#variable_fonts) of the font, or will it be Static?

Yes, there's a variable version as well as WOFF and WOFF2 versions 🚀

**Comment by thainole** [comment]
I appreciate you adding the comparisons between Hack and JetBrains Mono! I like how the latter looks and I think it would indeed be helpful to better distinguish the characters from `l`, `i`, `1`, and also the `0` and `O` characters.

**Comment by nahrivera7** [comment]
Thanks for opening this issue @icarusgk!
I support this proposal.

**Comment by ahmadabdolsaheb** [comment]
I don't have a preference. Since @bbsmooth has done a lot of the research for comparing and choosing the previous font, I defer to him.

**Comment by bbsmooth** [comment]
I appreciate your faith in me @ahmadabdolsaheb, but I'm probably not the best person to make a decision on this. The original issue I brought up in #46530 has been solved with the current font we are using and that's good enough for me. I really have no interest in arguing over tiny differences between the two fonts and trying to prove that one is better than the other (which is a fool's errand since it basically comes down to personal preference). From the examples above, it does appear that JetBrains would fulfill the requirements we are looking for in a font, so I have no reason to block it based on accessibility. I'm just not sure I'm convinced that we need to make the switch, I'm not sure why there is a seemingly sudden push to make the switch, and as I have already noted, I still like the looks of Hack better.

What I am willing to do is add JetBrains to my font comparison app if you and other FCC maintainers are actually willing to consider making the change and if you think adding it to my app would help you in that decision. So just say the word and I will do that.

**Comment by icarusgk** [comment]
Thank you for your response. I understand where you're coming from and I think it's great that you have a personal preference for the Hack font, as well as your position on not wanting to argue about the differences between the fonts and that personal preference plays a role in choosing a font. However, I believe it's crucial to also take into account the impact that the font has on accessibility and user experience. Many people in this issue have already voiced their support for the change, now imagine the people who use freeCodeCamp on a daily basis. It's important to consider the perspectives of all users, not just our own personal preferences. 

While I understand that you may not yet be fully convinced about making the switch, I hope you can keep an open mind and consider all of the factors involved, including accessibility and user experience.

**Comment by raisedadead** [comment]
@bbsmooth thanks for your honest & candid thoughts. 

We have always been proud of our a11y efforts, and you have been a pioneer in recent times in helping us improve that. Your name comes up in meetings and discussions within the team all the time 🙂 and it's our privilege to have your help.

Do you mind adding JetBrains to your comparison app? 

@icarusgk could you help us with where to find a modified version of the font that you updated to address all the concerns? That way, we are testing it one-to-one on Bruce's app.

Thanks.

**Comment by bbsmooth** [comment]
@raisedadead Thank you very much for the kind words. I both apologize, and am delighted that my "spirit" haunts you all during your meetings. But seriously, it is obvious that you all are concerned about accessibilty and that FCC truly wants to make this platform as accessible as possible for everyone. It has been very rewarding volunteering here.

As for the font file, based on the previous time we went through this, I believe the two requirements we need are:

- A slashed zero 
- No ligatures

If someone can point me to that I'll be happy to add it.

**Comment by icarusgk** [comment]
Of course @bbsmooth and @raisedadead, here's the file containing the JetBrains Mono font that has:

- A slashed zero
- No ligatures
- Enhanced `c` and `r` characters based on the suggestions discussed [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/49174#issuecomment-1408092850)

[**Link to the font**](https://drive.google.com/file/d/1E4Vv1UTwyWp0qXESh2l1KTeIWZU_QZl2/view)

Sorry for the delay on this one, my laptop was acting up, it was stuck the boot screen, had to flash the OS to an USB and boot from a live environment. But good news, I've sorted everything out and I'm back in action. Ready to jump back in.

I am thrilled to contribute this font to the app created by @bbsmooth and open to any further modifications or improvements that may enhance its usability.

Thank you for your attention and consideration.

**Comment by bbsmooth** [comment]
I have added the provided JetBrains font file to my [font comparison app](http://font-selector.surge.sh/).

**Comment by icarusgk** [comment]
Amazing @bbsmooth 😄 thank you for adding the font to your app and giving it a chance. I'm excited to hear everyone's opinions and feedback.

**Comment by Nirajn2311** [comment]
Thank you for providing an alternative to Hack. It's seems that it comes down to personal preference. As changing the font in `/learn` would lead us to changing it in all of our platforms and, that's a lot of headwork considering the resources we have in hand. Hence because of the above reasons we're closing the issue.

**Comment by icarusgk** [comment]
@Nirajn2311 I understand that changing the font in /learn could potentially lead to changes across multiple platforms, which could be a lot of work. However, as mentioned in the issue description, I'm willing to create the pull request myself to help with the implementation of the font change taking PR #47767 as an example.

**Comment by ahmadabdolsaheb** [comment]
@icarusgk thank you for your feature request. As Niraj mentioned, the font choice in this case boils down to personal preference. As a result a change is not necessary for the time being. Thank you for your understanding.
