### ISSUE TITLE
Nest the numbers indicating the version of package in code elements

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49181]
In RTL, these texts will be broken, because they are a mix of special character, numbers, which follow different direction in RTL than LTR. 

- ~1.2.13
- 1.2.x
- 1.x.x

To fix these, add code elements around the version number.

File: https://github.com/freeCodeCamp/freeCodeCamp/blob/659f05558904fe5554b1a93fb87311d6904a9e7f/curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm.md

change

> Add version "1.1.0"

to

> Add version `1.1.0`

there are multiple instances in these files 

https://github.com/freeCodeCamp/freeCodeCamp/blob/659f05558904fe5554b1a93fb87311d6904a9e7f/curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-caret-character-to-use-the-latest-minor-version-of-a-dependency.md
https://github.com/freeCodeCamp/freeCodeCamp/blob/659f05558904fe5554b1a93fb87311d6904a9e7f/curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-tilde-character-to-always-use-the-latest-patch-version-of-a-dependency.md

All of them should be wrapped in code elements

----

Speaking of weird interactions. Using special characters that relay on direction will break in RTL, because it will be reverted, in example.

> similar to how the \<head\> section

 will be

> similar to how the >head< section.

we can wrap `<head>` in https://github.com/freeCodeCamp/freeCodeCamp/blob/659f05558904fe5554b1a93fb87311d6904a9e7f/curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/how-to-use-package.json-the-core-of-any-node.js-project-or-npm-package.md

**Comment by Om-Aditya-Jain** [comment]
@Sboonny  I want to contribute towards this issue. Can you assign this issue to me.

**Comment by Sboonny** [comment]
The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
