### ISSUE TITLE
Unclear instruction about  css td width property

### ISSUE THREAD

**Issue by plxel** [freeCodeCamp/freeCodeCamp#49193]
### Describe the Issue

> Create a selector to target your td elements within your table body. Give them a width to fill the viewport, with a minimum and maximum of 4rem. This approach ensures that the width is fixed, whereas setting width specifically would allow the elements to shrink to the container (because we are using flexbox).

The phrase "because we are using flexbox" is not clear here. There was no flexbox for table or tr or td.
It is not clear why setting width to 100vw works in such way

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-52

### Your code

```
tbody td { 
  width: 100vw;
  max-width: 4rem;
  min-width: 4rem;
}
```

### Expected behavior

It will be cool to have clear explanation about setting td width to 100vw in table

### System

- Device: MacBook Pro
- OS: Ventura 13.0.1
- Browser: Chrome
- Version: 109.0.5414.119

**Comment by spiritanand** [comment]
Where is the code of this issue?

**Comment by CallmeHongmaybe** [comment]
@spiritanand I believe it's in the `challenge` folder, written in one of its`.md` files.

**Comment by spiritanand** [comment]
I am waiting for the issue to be triaged by a maintainer.

**Comment by michaeldiestelberg** [comment]
This issue is related and might lead to a different code solution for step 52: https://github.com/freeCodeCamp/freeCodeCamp/issues/49317

**Comment by Nirajn2311** [comment]
The phrase `because we are using flexbox` needs to be removed from the challenge description.
