### ISSUE TITLE
The ability to change font family in the setting page

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49197]
Looking at the proposal in #49174, some may need different font based on their needs, and some may like more stylish font. We can create the ability to choose the font based on user preference.

It can be similar to the theme, applying classes based on JavaScript logic. It may change base on if the font-families don't have the same height, width and don't have margin/padding baked in them.

**Comment by icarusgk** [comment]
I totally agree! Giving users the option to choose their preferred font based on their needs and style preferences is a fantastic idea. This added flexibility will enhance the overall user experience and accommodate a wider range of preferences. The mono fonts (those that meet the requirements) could be fetched from Google Fonts like Figma does it 👀

**Comment by ahmadabdolsaheb** [comment]
It is definitely a nice to have, but the cons out number the pros in this case. close it?
