### ISSUE TITLE
Swap to variable fonts instead of static ones

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49198]
Based on #49197, if we are adding the option to make the user able to pick their fonts, we can move to variable format. 

This will allow the browser to use whatever version of the fonts, whether bold, italic or normal, without the need for multiple files and with the same file space if not faster. 

for more info check: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#variable_fonts

A font that can be turned into Variable format, in our current code base is "Noto-san-arabic" in the RTL layout, https://fonts.google.com/noto/specimen/Noto+Sans+Arabic?subset=arabic&noto.script=Arab

**Comment by raisedadead** [comment]
Just keep in mind that the fonts need to be hosted by us.

**Comment by Vansh-Baghel** [comment]
For this, we need to replace every font appearance right? There are over 1000 places weve used font-family

**Comment by raisedadead** [comment]
Closing as linked issue is no longer in play.
