### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue 

### ISSUE THREAD

**Issue by jcbrodie** [FreeCodeCamp/freecodecamp#492]
Not extremely broken, but the tests passed even though only the first p element was set to size 16. (Directions say to "... set the font size of all p elements to 16 pixels.")

**Comment by QuincyLarson** [comment]
@jcbrodie Ah, you are supposed to change all p elements at the same time in the <style> tag. I will clarify the copy on this. Thanks for reporting it!
