### ISSUE TITLE
Unnecessary use of class in Nutrition Label course

### ISSUE THREAD

**Issue by michaeldiestelberg** [freeCodeCamp/freeCodeCamp#49207]
### Describe the Issue

I was reviewing the final code of the Nutrition Label course and noticed two (related) issues.

1. In the last two steps (66 and 67, coming from 65), the code of the index.html file changes with additional code that didn’t exist in the steps before (and it isn’t added in these steps either).

How it should be:

```
<div class="calories-info">
      <div class="left-container">
        <h2 class="bold small-text">Amount per serving</h2>
        <p>Calories</p>
      </div>
      <span>230</span>
</div>
```

What it becomes:

```
<div class="calories-info">
      <div class="left-container">
        <h2 class="bold small-text">Amount per serving</h2>
        <p>Calories</p>
      </div>
      <span class="right">230</span>
</div>
```

2. The CSS class "right" is used in places where it is not needed. The span elements inside the "daily-value" div that need to be aligned to the right end of the container don't need that class. Flexbox setting "justify-content: space-between" already takes care of that. The "right" class should only be used once, for the p element with the text "% Daily Value *".

Example:

`<p class="indent no-divider">Saturated Fat 1g <span class="bold right">5%</span></p>`

How it should be:

`<p class="indent no-divider">Saturated Fat 1g <span class="bold">5%</span></p>`

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/

### Your code

-

### Expected behavior

-

### System

- Device: MacBook
- OS: macOS Ventura 13.2
- Browser: Safari
- Version: 16.3

**Comment by Nirajn2311** [comment]
Looks like I forgot to change the code in the last two files when I modified the Nutrition Label course recently. Yes, the `right` class has to be removed from all tags except for the `p` element with text `% Daily Value *` in the last two steps.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by depleur** [comment]
Hey, is the code in question the code that the learner submits, or the code that makes [this ](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/)webpage the way it looks?

**Comment by Nirajn2311** [comment]
The code can be found in these 2 files:
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f94786869e1a7fec54375.md
* https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f951dff9317a900ef683f.md
