### ISSUE TITLE
Move Rosetta Code and Project Euler to it's own superblock

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#49229]
### Is your feature request related to a problem? Please describe.

Quincy, asked to move these projects to it's own Super-block instead of having them in the Coding Interview prep section.

### Describe the solution you'd like

The best solution would be to move The Rosetta code and Project Euler section to it's own superblock.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by swwayam** [comment]
Can i take this up?

**Comment by Sembauke** [comment]
closed by @moT01
