### ISSUE TITLE
commonFramework-d332a71687.js Error

### ISSUE THREAD

**Issue by archileta** [FreeCodeCamp/FreeCodeCamp#4922]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy?solution=function%20destroyer(arr)%20%7B%0A%20%20%20%20for(i%20%3D%201%2C%20al%20%3D%20arguments.length%3B%20i%20%3C%20al%3B%20i%2B%2B)%7B%20%20%20%0A%20%20%20%20%20%20%20%20argValue%20%3D%20arguments%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20arr%20%3D%20arr.filter(eliminator)%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20arr%3B%0A%7D%0A%0Afunction%20eliminator(value)%7B%0A%20%20%20%20%2F%2Fconsole.log(%22Current%20i%20value%3A%20%22%20%2B%20argValue)%0A%20%20%20%20%2F%2Fconsole.log(value)%3B%0A%20%20%20%20return%20value%20!%3D%20argValue%3B%0A%7D%0A%0A%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A%2F%2Fdestroyer(%5B1%2C%202%2C%203%2C%205%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A%2F%2Fdestroyer(%5B3%2C%205%2C%201%2C%202%2C%202%5D%2C%202%2C%203%2C%205)%3B%0A%2F%2Fdestroyer(%5B2%2C%203%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A%2F%2Fdestroyer(%5B%22tree%22%2C%20%22hamburger%22%2C%2053%5D%2C%20%22tree%22%2C%2053)%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have been able to successfully run the below code in Chrome's console and on Codecademy.com. When I run on FCC I get the response: "i is not defined". When I look at the console to determine if there are any errors, I see the following message:

```
i is not defined(anonymous function) @ commonFramework-d332a71687.js:1
```

Successful test on other javascript console:  http://bit.ly/1PwjqZa

My code:
```javascript
function destroyer(arr) {
    for(i = 1, al = arguments.length; i < al; i++){   
        argValue = arguments[i];
        arr = arr.filter(eliminator);
    }
    return arr;
}

function eliminator(value){
    return value != argValue;
}



destroyer([1, 2, 3, 1, 2, 3], 2, 3);
//Tested in console returns [1,1]

//destroyer([1, 2, 3, 5, 1, 2, 3], 2, 3);
//destroyer([3, 5, 1, 2, 2], 2, 3, 5);
//destroyer([2, 3, 2, 3], 2, 3);
//destroyer(["tree", "hamburger", 53], "tree", 53)

```

**Comment by ltegman** [comment]
You are creating global variables by leaving off the `var` in front of variable declarations. This is bad practice and fails in strict mode, which is what our tests now run in.

Thanks and happy coding!
