### ISSUE TITLE
missing code elements in challenge 15 of the odin project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49252]
in the odin project, there is a sentence that is worded like 

> You should always have the `meta` tag for the charset encoding of the webpage in the head element: `<meta charset="utf-8">`.

it should be worded like 

> You should always have the `meta` tag for the `charset` encoding of the webpage in the `head` element: `<meta charset="utf-8">`.

Here is the file https://github.com/freeCodeCamp/freeCodeCamp/blob/569fc3196b2d3a9a96706f14b13bda48388d2c9a/curriculum/challenges/english/10-coding-interview-prep/the-odin-project/html-boilerplate-question-c.md#the-charset-meta-element

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by bhagatpratik07** [comment]
can I solve this?
