### ISSUE TITLE
d3 step uses the phrase 'SVG canvas' half way through the course without any explanation

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49266]
### Describe the Issue

About halfway through the D3 (data visualization with D3) course, we see the phrase "SVG canvas" for the first time on this page: https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-labels-to-d3-elements

However prior to this point the course only used the phrase 'SVG area' in reference to the space that the SVG takes up on the screen. No explanation was given in the step for what 'SVG canvas' is which was confusing to me as a translator (why a different word than before?) and as a Java developer who sees 'canvas' as a class for drawing. I did a quick google search for 'svg canvas' and all I got were results suggesting that these are different things.

I propose therefore that all occurrences of 'SVG canvas' be replaced with 'SVG area' in this step and following steps (it is mentioned again later several times). 

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-labels-to-d3-elements

### Your code

```

```

### Expected behavior

replace all occurrences of 'SVG canvas' with 'SVG area' in the D3 curriculum

### System

N/A

**Comment by maciek367** [comment]
here it is used interchangeably https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/create-a-linear-scale-with-d3

can you link to those sites where it is said that this terms are different?

i think that if it is the same thing we can add explanation that svg canvas is the same what svg area is (in order to clarify) or we can still get rid of "svg canvas" term completely and change it to "svg area"

awaiting response

**Comment by hbar1st** [comment]
my personal preference is to use one term through-out. It can be area or it can be canvas.
I'm not really sure why the course started out with 'svg area' and ended up with 'svg canvas'. (And as mentioned earlier, as a Java dev, the word canvas is not used lightly by me, so I prefer we go with the simpler phrase 'svg area' unless there is a reason for not doing so)

**Comment by hbar1st** [comment]
People have started working on this when the discussion has not concluded unfortunately.
One thing I would say also, if we change SVG canvas to SVG area or the reverse, we should make sure the change works grammatically and contextually and not do so in a massive search and replace.

For eg "on the SVG canvas" would probably have to change to "in the SVG area". We would not say "on the SVG area".

**Comment by hbar1st** [comment]
The word area is something everyone understands who has any (even beginner) mathematics background. The word canvas is less clear. We would need to define what is meant by 'canvas'. I hope other people can share an opinion as well.

**Comment by ShaunSHamilton** [comment]
There is no such thing as an _"SVG Canvas"_ - it is a misnomer. In the context of these lessons, _"SVG area"_ is not one specific term - it is an SVG, and we are talking about its physical area.

**To Close**

As such, we can remove all mentions of _"SVG canvas"_, and simply remove the word _"canvas"_.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
