### ISSUE TITLE
d3 step repeats itself about the style() method

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49265]
### Describe the Issue

In the step:
https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/change-styles-based-on-data

We see the text:
"You can use a callback function in the style() method to change the styling for different elements."

Which is a repetition in part of the later sentence "You can use a callback function in the style() method and include the conditional logic."

I feel the first sentence can be skipped entirely and make for a better step overall.

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/change-styles-based-on-data

### Your code

```

```

### Expected behavior

Instead of the current step text, we could rewrite as follows:
```
D3 is about visualization and presentation of data. It's likely you'll want to change the styling of elements based on the data.

For example, you may want to color a data point blue if it has a value less than 20, and red otherwise. You can use a callback function in the style() method and include the conditional logic. The callback function uses the d parameter to represent the data point:
```

### System

N/A

**Comment by maciek367** [comment]
opened pr that gets rid of first sentence
