### ISSUE TITLE
Learn HTML Forms Registration Form - Step 17

### ISSUE THREAD

**Issue by beastvold** [freeCodeCamp/freeCodeCamp#49261]
### Describe the Issue

Instructions ask for nested \<input\> elements within each \<label\>, but do not allow multi-line responses. When the response is submitted with multiple nested line, I get the error:

Test
Sorry, your code does not pass. You're getting there.

Hint
You should add the first input after the label text Enter Your Last Name:, and include a space after the colon.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-17

### Your code

Fails:
```
      <fieldset>
        <label>Enter Your First Name: 
          <input />
        </label>
        <label>Enter Your Last Name: 
          <input />
        </label>
        <label>Enter Your Email: 
          <input />
        </label>
        <label>Create a New Password: 
          <input />
        </label>
      </fieldset>
```

Passes:
```
      <fieldset>
        <label>Enter Your First Name: <input /></label>
        <label>Enter Your Last Name: <input /></label>
        <label>Enter Your Email: <input /></label>
        <label>Create a New Password: <input /></label>
      </fieldset>
```

### Expected behavior

Submitting code should allow for the case of multi-line nesting. (The first segment of failing code above should pass.)

### System

- Device: MacBook Pro
- OS: OS X 10.15
- Browser: Brave
- Version: 1.47.171 Chromium: 109.0.5414.87 (Official Build) (x86_64)

**Comment by swwayam** [comment]
I reproduced the bug and you are right there is an issue, but I think the second code was intentional so that we write a cleaner syntax.

**Comment by Akshaybagai52** [comment]
<fieldset>
        <label>Enter Your First Name: <input ></label>
        <label>Enter Your Last Name: <input ></label>
        <label>Enter Your Email: <input ></label>
        <label>Create a New Password: <input ></label>
      </fieldset>

**Comment by Lawrencmagnat** [comment]
It will be of a good idea if you added the tag <legend> 
![snippet](https://user-images.githubusercontent.com/106784622/218350730-da0157f4-dcec-4d9a-b093-35b7eefb8f0b.png)

**Comment by smashcoder** [comment]
The reason why it doesn't take multi-line nesting are : 

1.  The platform is designed in such a away that it expects the same response as it has in it's program. Even if there is a spelling mistake also still it will not agree that along with spacing.
2. Multi-Line nesting can be done but it is not done in the code which is already done or present in the program to check if both the code done by you and already feed on the page are same or not. 

Solutions: By Adding 'OR' condition during checking can sort this issue.

Example : 
if ( syntax 1 || syntax2 ) {
pass
}
else{
fail
}

Over here syntax 1 is the pre-filled program and syntax 2 will similar response like multi-line nesting or spacing in between

**Comment by Sboonny** [comment]
The last 4 tests should allow the extra line when campers add nested `input` inside the `label`

here is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/b13713c33f7ce3427ef4b52884fb40f8a9b2d1a0/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f805f813eaf2049bc2ceea.md?plain=1#L2


----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.
