### ISSUE TITLE
Change the Media component to our news card component

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49277]
After discussing the media component and how it looks in the profile section, Ahmad request to change it to our Card component similar to how new display it

Small mobile view

![image](https://user-images.githubusercontent.com/88248797/217227692-1c545475-2c62-491e-916a-552881c34fa6.png)

wide view (apply to tablet and wide screens)

![image](https://user-images.githubusercontent.com/88248797/217227436-540118d0-6baf-48cf-89ab-bb157320737f.png)

It should have similar style, but without tags and date 🤔

**Comment by BalanaguYashwanth** [comment]
Hello @Sboonny ,

I saw had raised some pull request, whats the status of PR and Also is this issue still active ?

**Comment by Sboonny** [comment]
I hope the PR closes it, if you are existed about contributing, there are 46 open issue for contribution label help wanted, feel free to pick one.

https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
