### ISSUE TITLE
updates needed to 'getMessage element' phrase in json apis and ajax course

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49274]
### Describe the Issue

curriculum/course/step: 04-data-visualization/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property.md

This file contains the following test message:
Your code should use the document.getElementById method to select the getMessage element.

However, the reference to "getMessage element" in the test message should instead refer to #getMessage element as getMessage is the value of an id attribute.

While we're here also, I noticed that this sentence in the same challenge can be made simpler:
You can implement an onclick event handler which triggers when the user clicks on the element with id getMessage, by adding the following code:

Instead of 'the element with id getMessage' we can just say 'the #getMessage element'? 2 words less but it also makes translating it a lot less wordier for Arabic at least.

### Affected Page

https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property

### Your code

```

```

### Expected behavior

use #getMessage element as described above

### System

N/A

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this. However, I do not see a bug here.

> However, the reference to "getMessage element" in the test should instead refer to #getMessage element as getMessage is the value of an id attribute.

The test is: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/8fe7893b0dc51334d259d459b657093efa565e71/curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property.md?plain=1#L39-L41

That is how the [`getElementById`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) method works - it takes the name of an `id` as a string. The element's `id` is **not** equal to `#getMessage`. The element's `id` **is** `getMessage`.

Hope this clarifies

**Comment by hbar1st** [comment]
I understand that getElementById takes an id, but the test description: "Your code should use the document.getElementById method to select the getMessage element." says that we should use the method to select the getMessage element which is not the same thing as saying "to select the element whose id is getMessage".
The 'getMessage element' suggests something that looks like this `<getMessage>` versus something that has an id attribute.

This is the same standard btw used in all the NRWD course. We say #id-name element when we are referring to an element who id is value is id-name in many places. So we would just be making this sentence adhere to this standard of writing.

**Comment by ShaunSHamilton** [comment]
Ah, thank you for clarifying. I thought you were referring to the test.

**Comment by hbar1st** [comment]
I have made a slight edit to the original description to clarify that the 'test message' is the concern.

**Comment by midikaif** [comment]
Hey @Sboonny @hbar1st @ShaunSHamilton, what is the issue with my PR? please help me
