### ISSUE TITLE
Help Button not Obvious

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#49297]
### Describe the Issue

The new Ask For Help button is not obvious. We have users on the forum frequently not understanding how to find the Ask For Help button.

https://forum.freecodecamp.org/t/new-help-button-not-obvious/571552

### Affected Page

All RWD

### Steps to Reproduce

1. Go to any RWD page
2. Click on 'Check Your Code' a few time
3. See question mark

### Expected behavior

As suggested by @lasjorg, we could include a one word description along with the symbol, for clarity: https://forum.freecodecamp.org/t/new-help-button-not-obvious/571552/7

### System

All

**Comment by jeremylt** [comment]
@naomi-lgbt you said you wanted to circle back to this?

**Comment by bbsmooth** [comment]
I'm all for adding "Reset" and "Help" to those icon buttons. If we did this then we would need to remove the `aria-label` from these buttons as the added text inside those buttons should be the accessible name for each button.

**Comment by Vansh-Baghel** [comment]
@jeremylt I see, may I work on it?

**Comment by Vansh-Baghel** [comment]
@Sboonny Would like to have your thoughts here as well ❤️

**Comment by Sboonny** [comment]
@ahmadabdolsaheb wanted the removal of the text, because it allows extra spacing for the future buttons, and we are moving the new RWD to look similar to the mobile version.

But we don't have the future buttons, and after reviewing https://github.com/freeCodeCamp/freeCodeCamp/pull/48586, we really need to clean the technical debt first.

I am happy with adding this back, maybe only for wide screens 🤔. I don't mind adding them for both either, and changing all of them when the future buttons are added.

**Comment by Vansh-Baghel** [comment]
@Sboonny True, like you can remove the buttons itself for mobile versions as it already have it in the bottom.
![free4](https://user-images.githubusercontent.com/103327712/217748827-e38951ab-2527-4bed-8794-8ce84f49fabb.png)

**Comment by jeremylt** [comment]
I'm not sure if/how complicated it is to implement, but only adding the text for a one word description if the window is wide enough sounds reasonable to me.

**Comment by Vansh-Baghel** [comment]
> I'm not sure if/how complicated it is to implement, but only adding the text for a one word description if the window is wide enough sounds reasonable to me.

Yes, that could be done. Like showing the text for wide screens and removing for the small ones.

**Comment by BalanaguYashwanth** [comment]
Hello @Vansh-Baghel,

So you will like to raise PR and close the ticket ?

**Comment by Vansh-Baghel** [comment]
@BalanaguYashwanth Yes sure, ill do it if its needed.

**Comment by Sboonny** [comment]
> I'm not sure if/how complicated it is to implement, but only adding the text for a one word description if the window is wide enough sounds reasonable to me.

There are values in the curriculum for tablat width, and we have `Media` component for this, not the bootstrap react one.

But to be honest, I think it's for the best to use text in the mobile and desktop for, and when we need to change it later, we will have a better solution then.

**Comment by jeremylt** [comment]
I think tackling this in multiple steps is perfectly reasonable.

That is, adding the one word text now and adjusting as needed in the future for mobile.

**Comment by Vansh-Baghel** [comment]
Yes, the user must have the flexibility to solve the question.

**Comment by jeremylt** [comment]
I don't understand what that means?

**Comment by Sboonny** [comment]
This seems to be a first timer issue, here is the file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/classic/lower-jaw.tsx

to solve this, add `Reset` and `Help` text to their corresponding buttons.

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by Sboonny** [comment]
> I don't understand what that means?

Nah, you got my intent perfectly fine 👍, I shouldn't have diverged the issue.

**Comment by jeremylt** [comment]
> Nah, you got my intent perfectly fine +1, I shouldn't have diverged the issue.

You're good - there was another reply in there that got deleted

**Comment by Vansh-Baghel** [comment]
> there was another reply in there

Apologies, I commented in the wrong commit. (*￣3￣)╭

**Comment by Vansh-Baghel** [comment]
> This seems to be a first timer issue, here is the file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/classic/lower-jaw.tsx
> 
> to solve this, add `Reset` and `Help` text to their corresponding buttons. Don't worry about hiding it for mobile, this issue isn't about it.
> 
> If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

I have already fixed it, may I raise a PR?

**Comment by Sboonny** [comment]
I would leave it for first timers, it's rare that there is an open issue for them

**Comment by lasjorg** [comment]
Doesn't the text need to be translatable? Do they use the `t` function with the text? Pretty annoying function name BTW, good luck doing a search for that identifier in the code.

One thing that might also communicate the ask for help button purpose a bit better is if the circle was a speech bubble. But it clashes a bit with the design and when I tried doing a mock it didn't look very good. I tried it with both a round and square bubble. The buttons might just be too small for such an icon.

---

As an aside.

What would be really slick is having an onboarding step. I'm sure it would be a lot of work, especially with internationalization and accessibility in mind (and depending on the implementation).

**Comment by Sboonny** [comment]
> Doesn't the text need to be translatable? Do they use the t function with the text? Pretty annoying function name BTW, good luck doing a search for that identifier in the code.

oh god, you are right, I wanted to forget it 🤣.

> One thing that might also communicate the ask for help button purpose a bit better is if the circle was a speech bubble. But it clashes a bit with the design and when I tried doing a mock it didn't look very good. I tried it with both a round and square bubble. The buttons might just be too small for such an icon.

👍🤔 Maybe we redesign it entirely, let me open issue after this one about making the buttons bigger and then we can implement the image.

>  the alignment I had to create the icon from two icons and I didn't bother doing a very good job.

Didn't notice 😅, as long as the icons don't have `role` and `label`, I am happy, I think they look good 👍

**Comment by lasjorg** [comment]
Well, it was just an example. But I do think it communicates its purpose a bit better. Just to be clear, I would still suggest we add the text.

We should probably clue in @ahmadabdolsaheb and hear what they have to say.

**Comment by ahmadabdolsaheb** [comment]
Replacing texts with icons was an experiment to minimize space used for those buttons and have a predictable ui in regards to localization. 

The issue with adding and removing the text based on screen size is that editor pane itself changes size regardless of the viewport width.  As a result, a user could be using a desktop and have a narrow editor (lower jaw).

Using icons for buttons is common practice for mobile, but require some getting used to in Desktops. 
I don't know if a best.

Having the icon with the text could work. Since the width of translated texts have different widths, we need to make sure that the overflown row is scrollable vertically.

Youtube uses a similar pattern even for small screens on their web app. 

Screen Shot 2023-02-16 at 4.32.19 PM
<img width="376" alt="1" src="https://user-images.githubusercontent.com/4591597/219384579-9d272e57-eef4-4e2e-bdad-34931eb64400.png">

**Comment by jeremylt** [comment]
I think the issue is that while the reset button is somewhat ubiquitous, the help button isn't super obvious. That symbol doesn't intuitively mean "click this button to go to the forum to ask questions"

**Comment by bbsmooth** [comment]
On a side note, I don't think the YouTube button example above is the best example of accessibility and I think it probably fails [SC 1.4.10](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html). I know it seems strange that a site like YouTube would have obvious WCAG failures, but this is not the only one. Make your browser approximately 1280px wide and try zooming in 400% while watching a video (be sure to read the comments). I think you will find that you need a lot of horizontal scrolling.

Moral of the story: Big sites that should be able to do better can still have accessibility issues.

**Comment by ahmadabdolsaheb** [comment]
@jeremylt, I am open to replacing the icon to see if that helps resolve the issue.

**Comment by hbar1st** [comment]
> What would be really slick is having an onboarding step. I'm sure it would be a lot of work, especially with internationalization and accessibility in mind (and depending on the implementation).

I have been wanting such a thing especially for translated content because of the added confusion of not having the correct keyboard settings by default (people from certain European countries use  keyboards for example that don't have backslashes).

The issue I opened though has been  closed #48943.

**Comment by jeremylt** [comment]
A button for requesting help should not require an onboarding step to understand.

**Comment by lasjorg** [comment]
No, onboarding shouldn't be required to understand what the main buttons do.

But it's also not uncommon to have an onboarding step that quickly goes through the UI. Lots of sites have onboarding, even when the UI is/should be self-explanatory.

It is a "nice to have", not a "need to have", which is why I called it slick. It can also help improve initial engagement and communicate an overall tone of the site.

Anyways, I made a PR for the button just so we have something.

**Comment by ahmadabdolsaheb** [comment]
If the issue continues after the icon change, we could re-add the one word descriptions.
Additionally, we could have the button light up when the button appears to add more emphasis.

**Comment by jeremylt** [comment]
I thought that we agreed that adding a single word would be a good idea above?

I don't understand why using a word to communicate is a bad thing here. Icons aren't a universal replacement for words.

**Comment by ahmadabdolsaheb** [comment]
Let's do single word and show the buttons in multiple lines based on the width of the instructions pane.

**Comment by DEVelooper29** [comment]
I am interested to make this issue my stepping stone in the journey of Open Source contribution. Can someone please brief me up what has to be done finally after the discussion?

**Comment by ahmadabdolsaheb** [comment]
Action items:
Replace the icons with descriptive words (reset, help)for the buttons in `lower-jaw-icon-bar`.
Replace 'lower-jaw-icon-bar' with a more descriptive class name.
Make sure 'lower-jaw-icon-bar' contents wrap when the pane is too small.

**Comment by DEVelooper29** [comment]
Okay. I'll do that

> Action items: Replace the icons with descriptive words (reset, help)for the buttons in `lower-jaw-icon-bar`. Replace 'lower-jaw-icon-bar' with a more descriptive class name. Make sure 'lower-jaw-icon-bar' contents wrap when the pane is too small.

**Comment by ahmadabdolsaheb** [comment]
@DEVelooper29, I just updated the spec. Let's have both the icon and the word next to one another for this iteration.

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by ahmadabdolsaheb** [comment]
@anubhav1206 there is an attached pr that is being reviewed for this issue.
