### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue 

### ISSUE THREAD

**Issue by katiequin335** [FreeCodeCamp/freecodecamp#493]
Approves challenge as completed though only one requirement has been satisifed("Your webpage should have an image element."). Other requirement("Your image should have have a src attribute that points to the kitten image.") still has a red X by it. However, the move to next challenge button is still lit up green.

**Comment by terakilobyte** [comment]
Thanks, the tests have been updated and will go live soon. Let us know if you see anything else amiss!

**Comment by chetan17S** [comment]
I have a best tricky solution .You just continuously press RUN TESTS button till you get a Submit your result notification.This trick works great because I also stuck in this problem.
Thanks.......
