### ISSUE TITLE
in `https://www.freecodecamp.org/news/learn-solidity-handbook/#how-typing-works`   some contens is not display

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#49305]
### Describe the Issue

 some contens is not display

`And the bytes I got returned were represented in hexadecimal form as: ` is not display.

![image](https://user-images.githubusercontent.com/6524977/217772201-6ec666f7-b5a8-412e-9b0b-26b7e7c58012.png)

### Affected Page

https://www.freecodecamp.org/news/learn-solidity-handbook/#how-typing-works

### Steps to Reproduce

nothing

### Expected behavior

it should be display.

### Screenshots

![image](https://user-images.githubusercontent.com/6524977/217772326-908b0811-916a-4b99-8bae-60aec77493df.png)

### System

- Device: [Laptop]
- OS: [ Windows 10,]
- Browser: [ Chrome]
- Version: [ 109.0.5414.120]

**Comment by balaji-sivasakthi** [comment]
I understand your issue. it should be readable right.
![Screenshot (31)](https://user-images.githubusercontent.com/65065614/217881103-cb585b82-80ad-4db8-8d5e-c045b743e17a.png)

**Comment by balaji-sivasakthi** [comment]
I found that the value  of  0x0000... is in `work-break:normal`, but it should be `work-break:break-all`.

**Comment by balaji-sivasakthi** [comment]
I think this issue is not related to the code because it causes problems with the style of the news. So we can contact the author via email or other social media to change the style.

https://www.freecodecamp.org/news/author/zubin/

**Comment by Nirajn2311** [comment]
@scissorsneedfoodtoo The code snippet needs to go into a code block in our ghost editor to make the paragraph readable. The respective article is linked above in the issue description.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @luojiyin1987, and for the ping @Nirajn2311.

I just went in and updated the article so that long hex string is in a code block.

The fix should go live within the next few hours.

Please let us know if you notice any other issues in this article.
