### ISSUE TITLE
Nutrition Label Step 31 - Grammatical errors

### ISSUE THREAD

**Issue by Zebulon-Hopper** [freeCodeCamp/freeCodeCamp#49335]
CSS Learn Typography/Nutrition Label: Step 31
“Create an .small-text selector and set the font-size to” the “an” should actually be an “a”.

Windows 11/ Chrome browser Version 110.0.5481.78 (Official Build) (64-bit)

**Comment by jeremylt** [comment]
It helps if you use the New Issue template.

Link to challenge: https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-31

Suggested correction: 

> Create a `.small-text` selector and set the `font-size` to `0.85rem`, which would calculate to be roughly `13.6px` (remember that you set your html to have a `font-size` of `16px`).

**Comment by Akashzxr** [comment]
iam new to opensource can i work on this issue?

**Comment by Vansh-Baghel** [comment]
@Zebulon-Hopper Would you like to solve this issue? Or shall I go for it? Feel free to try 😀

**Comment by Akashzxr** [comment]
iam new to opensource i love to work on this issue.

**Comment by saadbitcoin** [comment]
Yes you can

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Sboonny** [comment]
To solve this issue, change this line from

> Create an `.small-text` selector and set the `font-size` to `0.85rem`, which would calculate to be roughly `13.6px` (remember that you set your `html` to have a `font-size` of `16px`).

to

> Create a `.small-text` selector and set the `font-size` to `0.85rem`, which would calculate to roughly `13.6px` (remember that you set your `html` to have a `font-size` of `16px`).

Here is the file
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f522dea4f776f64dc3e91.md

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.
