### ISSUE TITLE
Prevent preformatted text from wrapping in JS course “constructing strings with variables”

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49359]
### Describe the Issue

The use of preformatted text within regular text causes a problem for Arabic language comprehension when the preformatted text is allowed to wrap. The user cannot always see whether there is a space character at the point the line wraps so it is better to place preformatted text that is longer than one word in a code block to prevent wrapping.
In the indicated step, we see this issue in two spots.

Here: 

`ourStr` would have a value of the string `Hello, our name is freeCodeCamp, how are you?`.

And:

Set `myName` to a string equal to your name and build `myStr` with `myName` between the strings `My name is ` and ` and I am well!`

For both, we see multi-word backs-ticked phrases. And for both of these we would need them to be in a code block and not added inline to the sentences.

for eg the second one should become:

Set `myName` to a string equal to your name and build `myStr` with `myName` between the strings 
```text
My name is 
```
and 
```text
and I am well!
```

This would prevent the strings from wrapping and obscuring the spacing. As an illustration of the issue, please  review the screenshot provided of the Arabic JS course page and notice how the first wrapped sting that begins with “Hello,..” appears. The substring “are you” is wrapped down to the next line and the space that is normally observed when the line doesn’t wrap, is not visible.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/constructing-strings-with-variables

### Your code

```

```

### Expected behavior

We need a way to prevent formatted text from wrapping or a way for the spacing to be visible if it is allowed to wrap.

### Screenshots

![6B39C176-2AAB-45BD-82B0-D3CB67AD6EBC](https://user-images.githubusercontent.com/35541470/218308378-ff13330a-e5d1-4cc1-8e43-06816e0a1235.png)

### System

N/A

**Comment by hbar1st** [comment]
another page with a similar issue is https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-first-character-in-a-string

The issue is with the inline code segment `const firstName = "Charles"` which is allowed to wrap and becomes hard to read.

**Comment by naomi-lgbt** [comment]
I wonder if we could get away with not breaking inline code at all?

**Comment by hbar1st** [comment]
Not sure what you meant there @naomi-lgbt ? (Not breaking?)

**Comment by naomi-lgbt** [comment]
Yeah, prevent any sort of word-break or wrapping on inline code.

**Comment by hbar1st** [comment]
I think the pre tag is meant to be non wrapping by default.

I also saw online that if you set the white-space CSS property to the value of pre, then that will also prevent wrapping.

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by bbsmooth** [comment]
This has a help wanted tag but I am unsure what the suggested fix is?

**Comment by Sboonny** [comment]
To fix this issue, add `white-space` property with `break-spaces` for the code inside the instructions.

**Comment by bbsmooth** [comment]
Thanks @Sboonny, that's what I thought, I just wanted to make sure.

Second question, is this just to be applied to the specific challenge linked to above or on a global scale?

**Comment by Sboonny** [comment]
Global state, the issue is in old JavaScript, and the new JavaScript has multiple strings that will have the same issue
