### ISSUE TITLE
Basic JS, Word Blanks needs code blocks

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49370]
### Describe the Issue

The following sentence in the Word Blanks lesson should have a code block (three backticks) surrounding the code section which is directly referring to the completed code block below it on the page.
Instead of:
Consider this sentence - It was really ____, and we ____ ourselves ____.
It should say:
Consider this sentence - 
```
It was really ____, and we ____ ourselves ____.
```

The sentence has been translated because of the missing code blocks (and will not make sense as it's a direct reference to the actual code shown below it)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/word-blanks

### Your code

```

```

### Expected behavior

The sentence with the blanks should be in a code block that does not wrap. (three backticks above and below it)
Instead of:
Consider this sentence - It was really **\_\_\_\_**, and we **\_\_\_\_** ourselves **\_\_\_\_**.
It becomes:
Consider this sentence - 
```js
It was really **\_\_\_\_**, and we **\_\_\_\_** ourselves **\_\_\_\_**.
```

### System

n/a

**Comment by bbsmooth** [comment]
Question for those in the know. Do we have a way to keep content from being translated that doesn't involve using the triple back tick code block?

I would be cool to use sr-only text "Blank" (or something similar) for those underlines to represent missing text. But we can't do that using the code blocks since they are wrapped in a `pre`.

**Comment by naomi-lgbt** [comment]
Do they get wrapped in a `pre` if they're inline code?

**Comment by hbar1st** [comment]
It looks like they are just wrapped in string tags in crowdin at least. I don't see a pre tag.

**Comment by ahmadabdolsaheb** [comment]
pre sounds like a plausible idea. We should go ahead with that.

**Comment by Sboonny** [comment]
The challenge require the sentence to not be translated, and `pre` element don't stop translation, it gives the choice to the translation to translate or not, which isn't ideal.


Here is the file, https://github.com/freeCodeCamp/freeCodeCamp/blob/16f32431461c1becb8d969a7f4c0f2bc0ebfadc1/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/word-blanks.md?plain=1#L2


to solve this issue, change the structure of the sentence to 


 Consider this sentence:
 
```md
It was really ____, and we ____ ourselves ____. 
```

This sentence has three missing pieces- an adjective, a verb and an adverb, and we can add words of our choice to complete it. We can then assign the completed sentence to a variable as follows:

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by Sboonny** [comment]
> Do we have a way to keep content from being translated that doesn't involve using the triple back tick code block?

nope, but I can open an issue for this 👍 

> Do they get wrapped in a `pre` if they're inline code?

yes
