### ISSUE TITLE
[learn-css-transforms-by-building-a-penguin]: step-2 first test

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#49393]
### Describe the Issue

The test fails to catch the difference between an element and class selector

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-2

### Your code

```css
.body {
  background: linear-gradient(45deg, rgb(118, 201, 255), rgb(247, 255, 222));
}
```

The hint is

> You should set `background` to `linear-gradient(45deg, rgb(118, 201, 255), rgb(247, 255, 222))`.

But the first hint should be displayed instead:

> You should use the `body` element selector.

The regex fails to tell the difference between an element and class selector.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/61967e74a8e3690ab6292daa.md

### Expected behavior

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/61967e74a8e3690ab6292daa.md

### System

All

**Comment by ShaunSHamilton** [comment]
We should just use the `getStyle` method on the `CSSHelp` class to look for `'body'`. Examples of this can be seen in other tests.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Ombansal744** [comment]
Hi @ShaunSHamilton, My name is Om Bansal and this is my first time contributing to open source can i work on this issue?

**Comment by jeremylt** [comment]
Go for it - we will accept the first fully correct PR that fixes the issue.
