### ISSUE TITLE
Fix dasherization of Field Guide articles

### ISSUE THREAD

**Issue by biancamihai** [FreeCodeCamp/freecodecamp#494]
"404: We couldn't find a field guide entry with that name. Please double check the name."
takes me to http://www.freecodecamp.com/field-guide/why-doesnt-free-code-camp-teach-technical-interviewing-skills (think is a new article)

**Comment by terakilobyte** [comment]
Thanks for the heads up. This has brought to my attention we'll need to change the structure of your field guides. Clicking the link from the list of field guides should take successfully take you to this one.

**Comment by QuincyLarson** [comment]
@terakilobyte I had to go in and and wholesale reverse your dashification changes last night to fix this. I couldn't figure out why it wasn't working. Anyway, this works again.

**Comment by terakilobyte** [comment]
It's going to need to be overhauled with an internal link like we do with camper news eventually. The issue stems from the fact that punctuation is used within the names, not just at the end.
