### ISSUE TITLE
Update test-challenges/docs for testing specific blocks

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#49403]
https://github.com/freeCodeCamp/freeCodeCamp/pull/49293 stops Windows users from being able to restrict tests to specific blocks or superblocks.

Ideally the all users should be able to run the scripts the same way (maybe just via FCC_BLOCK/FCC_SUPERBLOCK In .env), but regardless the docs will need updating.

**Comment by naomi-lgbt** [comment]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/63889819/219845550-903aa9b9-26cf-4155-9188-2f51afe0a5bc.png">

Are we putting in the work to support non-WSL Windows environments?

**Comment by ShaunSHamilton** [comment]
> Are we putting in the work to support non-WSL Windows environments?

You mean Docker?

**Comment by Sembauke** [comment]
this seems to be in https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges
