### ISSUE TITLE
Padding 40 20 20 40 no worky, padding-top, padding-right, padding-bottom, padding-left no worky

### ISSUE THREAD

**Issue by zack0** [FreeCodeCamp/FreeCodeCamp#4943]
![padding-long](https://cloud.githubusercontent.com/assets/8292714/11541646/8090137a-98f0-11e5-97ed-f561727b68b3.PNG)
![padding-short](https://cloud.githubusercontent.com/assets/8292714/11541647/809fa376-98f0-11e5-8e53-6556fa19d218.PNG)

Challenge [Waypoint: Add Different Padding to Each Side of an Element](http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element?solution=%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%20%20padding-bottom%3A%2020px%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A10px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3Ared%3B%0A%20%20%20%20padding-top%3A%2040px%3B%0A%20%20%20%20padding-right%3A%2020px%3B%0A%20%20%20%20padding-bottom%3A%2020px%3B%0A%20%20%20%20padding-left%3A%2040px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2040px%2020px%2020px%2040px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
    padding-bottom: 20px;
  }

  .yellow-box {
    background-color: yellow;
    padding:10px;
  }
  
  .red-box {
    background-color:red;
    padding-top: 40px;
    padding-right: 20px;
    padding-bottom: 20px;
    padding-left: 40px;
  }

  .green-box {
    background-color: green;
    padding: 40px 20px 20px 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by ltegman** [comment]
Closing as a duplicate of #4885. We have a PR in the works that should fix this.

Thanks and happy coding!

**Comment by zack0** [comment]
I see thanks, I'll try continue in another browser.
