### ISSUE TITLE
Merge data from 2 different accounts

### ISSUE THREAD

**Issue by rafamuz** [freeCodeCamp/freeCodeCamp#49446]
### Describe the Issue

I, with no intention, used another e-mail (because I have 2 emails) and I created another account. But I did some exercises and progress my status, but now I´m only want to use 1 account. Is there a way to delete the other account but transfer my points to the old account? 

### Affected Page

not applied

### Steps to Reproduce

Logged 2 accounts by mistake

### Expected behavior

not applied

### System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Comment by Sboonny** [comment]
Please contact [support@freecodecamp.org](mailto:support@freecodecamp.org), GitHub isn't a suitable place to discuss private information.

**Comment by rafamuz** [comment]
why closed? when this correction will be published?

**Comment by Sboonny** [comment]
Because your personal data should not be discussed in a public topic, and for it to be corrected you need to discuss it with the support section, not the dev team.

Or am I misunderstood you and you want a feature to be add? 🤔
