### ISSUE TITLE
Fix Fibonacci Sequence text

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#49444]
### Describe the Issue

This should be a relatively easy fix for a first-time contributor :)

This challenge says the first two numbers are 1 and 1 when in fact the first two numbers are 0 and 1.

The first few numbers are: 0, 1, 1, 2, 3, 5 and 8

So when you update the text to also check the tests and make sure this doesn't change any of the expected test outcomes.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-odd-fibonacci-numbers

### Your code

```

```

### Expected behavior

The text should correctly state the first numbers as 0, 1, 1, 2, 3, 5 and 8

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

The affected file can be found here: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-odd-fibonacci-numbers.md

**Comment by SantiagoPVazquez** [comment]
Hello! 
I'm a rookie software developer and I'm looking for a "good first issue" to start contributing to open-source projects. 
So could I be assigned to fix this issue please?
