### ISSUE TITLE
Little problem on an exercise.

### ISSUE THREAD

**Issue by rafamuz** [freeCodeCamp/freeCodeCamp#49445]
### Describe the Issue

Hello. There is an error in the description of the tests for this exercise: " The foods object must have the strawberries key with the value of 35 .", but the correct one would be 27 and not 35.

The error was seen using the translation to Portuguese, I don´t know if only this translaton is wrong or there is on the original too.

### Affected Page

https://www.freecodecamp.org/portuguese/learn/javascript-algorithms-and-data-structures/basic-data-structures/add-key-value-pairs-to-javascript-objects

### Your code

let foods = {
  apples: 25,
  oranges: 32,
  plums: 28
};

// Altere apenas o código abaixo desta linha
foods.bananas = 13
foods.grapes = 35
foods.strawberries = 27
// Altere apenas o código acima desta linha

console.log(foods);

### Expected behavior

it´s ok, but the messa is: O objeto foods deve ter a chave grapes com o valor de 35.
it should be O objeto foods deve ter a chave grapes com o valor de 27.

### System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Comment by ShaunSHamilton** [comment]
Thank you for opening this. This is just an issue with the translation; the English version is correct.

I have submitted the correction on [Crowdin](https://translate.freecodecamp.org). This should be fixed, once the correction is QAed, pulled down to GitHub, and deployed.

**Comment by rafamuz** [comment]
> Thank you for opening this. This is just an issue with the translation; the English version is correct.
> 
> I have submitted the correction on [Crowdin](https://translate.freecodecamp.org). This should be fixed, once the correction is QAed, pulled down to GitHub, and deployed.

Done. I upvoted the right translation. and downvoted the wrong one. Thanks. How it the process to be QAed?

**Comment by ShaunSHamilton** [comment]
> How it the process to be QAed?

A Portuguese proofreader on Crowdin needs to approve the suggested translation. We currently have one Portuguese proofreader.
