### ISSUE TITLE
underline contrast is very poor for Arabic language

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49453]
@hbar1st, mentioned in discord that the underlines are hard to read, https://discord.com/channels/692816967895220344/1059910673167040683/1076878867010170931

![show section with underline issue in it](https://user-images.githubusercontent.com/88248797/220284591-83471161-45eb-44e9-8a64-343e30eeb11a.png)

I am open to suggestion about how links in Arabic/RTL language should be styled.
 
The issues aren't only in this section, alert and something I forgot has links with the same style.

She suggested using border-bottom instead of underline.

She suggested using different color for the underline. We need to account for different colors for alerts or different sections of the client.

**Comment by hbar1st** [comment]
The issue comes from the text-decoration: underline colliding with the dots used in Arabic lettering.
There's an interesting discussion here as well

https://github.com/w3c/csswg-drafts/issues/1288

**Comment by hbar1st** [comment]
And one more recent discussion of this here

https://github.com/w3c/alreq/issues/223

**Comment by bbsmooth** [comment]
`text-underline-offset` has [good support](https://caniuse.com/?search=text-underline-offset). 

I think `text-underline-position` might be a better choice but unfortunately `[Safari does not support it](https://caniuse.com/?search=text-underline-position)`.

**Comment by ahmadabdolsaheb** [comment]
We could move forward with adding a slight text-underline-offset for RTL or/and  affected languages.

**Comment by bbsmooth** [comment]
How about we set `text-underline-position` by default and then use CSS `@supports` to add `text-underline-offset` for browsers that don't support `text-underline-position` yet.

**Comment by ahmadabdolsaheb** [comment]
That would work as well.

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.
