### ISSUE TITLE
Refactor the togglebutton from float layout to flex

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49459]
In the setting page, there are buttons that have svg in them, and these buttons use `float` to position the svg.

![image](https://user-images.githubusercontent.com/88248797/220371148-c652c856-fd8d-4b0e-9f81-a20824c84dae.png)

Although it looks fine in normal layout, it is broken in RTL layout. The position is reverted

![image](https://user-images.githubusercontent.com/88248797/220372374-a0f356bc-7a33-4b97-a80c-0adf294ecafd.png)

Here is the CSS file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/helpers/toggle-button.css

And here is the HTML file, if you needed https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/helpers/toggle-button.tsx

Refactoring it to flex should fix the weird positioning in the RTL layout.

---

## Additional Context

- Why not Grid?

Browsers has different way of rendering the SVG size with Grid, although I think the `height` and `weight` will render the SVG with the desired look, it may change based on how browser decided how to render SVG in the future. 

If you want to create a grid that works in safarri, firefox and chrome, go for it. 

- Do I need to be mindful of how it looks in the RTL layout?

No, refactoring it to flex is good enough, if there is weird behavior accruing in the RTL layout, I will fix it in another PR.

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by Govind783** [comment]
Hey could you please assign this issue to me i would like to make the necessary changes from float to flex

**Comment by Sboonny** [comment]
We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by anmolahuja38** [comment]
Hi, I am looking to work on this issue,
I am not able to replicate the issue. Can anyone tell me how can I switch to Arabic/RTL language here?

**Comment by Imshk** [comment]
HEY, I want to work on this issue , please assign me

**Comment by sumitshinde-84** [comment]
hello sir , can you assign me this issue to me?
