### ISSUE TITLE
Share common types

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#49454]
It would help to reduce the complexity of the coupling between our workspaces if we move any common types to a common folder.

This should keep the definitions consistent and avoid situations where `tsc` tries to compile an entire package just for a single type.

_Originally posted by @Sembauke in https://github.com/freeCodeCamp/freeCodeCamp/pull/49293#discussion_r1112826256_

**Comment by ShaunSHamilton** [comment]
I am all for this. Are we thinking just a root `types` directory?

**Comment by ojeytonwilliams** [comment]
Yeah. I think that's all we need.

**Comment by ojeytonwilliams** [comment]
As the complexity of what we're building continues to grow, I think we'll need a more robust solution to this.

In general we need to think harder about how we architect our code and simply sharing types isn't going to cut it.
