### ISSUE TITLE
Instructions and test that are misleading on the Build a Survey Form Project

### ISSUE THREAD

**Issue by mayaliberman** [freeCodeCamp/freeCodeCamp#49478]
### Describe the Issue

In the Responsive Web Design Path on the [Build a Survey Form ](https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form), you instruct the students to use id twice in the HTML document. This stands in contrast to[ MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id), which declares specifically that IDs should be unique, and it is also a bad practice. If you use this attribute more than once, it should be a class, not an ID.
The tests should be updated accordingly. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### Your code

```
<select class="dropdown">
      <option value="" disabled>Select current role</option>
       <option value="1">Full Time Job </option>
        <option value="2">Full Time Learner</option>
         <option value="3">Prefer not to say</option>
          <option value="4">Other</option>
    </select>
```
### Expected behavior

The behavior will remain the same, but the code will be written in better practice.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bbsmooth** [comment]
Hi @mayaliberman, can you be a little more specific about where this is occurring?

**Comment by mayaliberman** [comment]
So in paragraph 12, you instruct the users to use the id attribute, but in the example [project ](https://survey-form.freecodecamp.rocks/), there are two select inputs, which can lead students to use the id attribute twice without noticing the mistake. I recommend that you either omit one select input from the project or change the instructions to use the class attribute on the select. BTW there is no use of the class attribute on this project which is much more common in practice than the id attribute.

**Comment by jeremylt** [comment]
> Inside the form element, you should have a `select` dropdown element with an `id` of `dropdown` and at least two options to choose from

I don't read this as saying to create two separate elements with the same `id`?

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

The instructions only ask for one select element, and only for one element with an `id` of `dropdown`:
> Inside the form element, you should have a select dropdown element with an id of dropdown and at least two options to choose from

> So in paragraph 12, you instruct the users to use the id attribute, but in the example [project ](https://survey-form.freecodecamp.rocks/), there are two select inputs, which can lead students to use the id attribute twice without noticing the mistake. I recommend that you either omit one select input from the project or change the instructions to use the class attribute on the select. BTW there is no use of the class attribute on this project which is much more common in practice than the id attribute.

The example project is just there as an _example_ for general idea. It should **not** be used as a blueprint or boilerplate. The example project also makes the submit button green, but that is not mentioned anywhere in the user stories.

The only requirement is that Campers follow the user stories and pass the tests.

As such, I am going to close this issue.
