### ISSUE TITLE
HTML5 Spec: Placeholders "should not" be used as a replacement for labels

### ISSUE THREAD

**Issue by jpaugh** [FreeCodeCamp/FreeCodeCamp#4947]
This example (Challenge [Waypoint: Add Placeholder Text to a Text Field] has an issue.) uses a placeholder in place of a label (i.e. `cat photo URL`), which violates the [HTML5 Spec,s recommendation] . According to that page, it can break accessibility, which is not good.

*Since this is a tutorial, it is especially important to follow the spec!* Unsuspecting learners could pick up a bad habit here. (Do what you like in your own production code ;-)

 A more apropos placeholder in this particular usage might look like `http://example.com`. (The text `cat photo URL` is certainly more appropriate as a label than a placeholder.)

[HTML5 Spec]: http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-placeholder-attribute
[Waypoint: Add Placeholder Text to a Text Field]: http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%3E%0A

**Comment by ltegman** [comment]
@jpaugh Which challenge are you referring to?

**Comment by jpaugh** [comment]
Sorry about that! Link added.

**Comment by jpaugh** [comment]
@BerkeleyTrue I don't consider it a matter of taste, nor strictly a UX issue, because it is specified by the HTML5 Spec. (If it were not in the spec, I'd freely advocate placeholders instead of labels.)

This issue occurs in 3 places: https://github.com/FreeCodeCamp/FreeCodeCamp/search?utf8=%E2%9C%93&q=placeholder+cat+photo+URL&type=Code

**Comment by ltegman** [comment]
Violating the spec and not fully implementing the recommendations of the spec are two completely different things. This doesn't violate spec, it just doesn't implement the ideal accessibility practices. We welcome PRs if you would like to fix this.

**Comment by jpaugh** [comment]
@ltegman That's a good point, and I missed that. I updated the issue to reflect that, and created a pull request. Thanks!
