### ISSUE TITLE
Build a Bike Shop: The term "subshell" or "sub shell" is not explained when it is first used 

### ISSUE THREAD

**Issue by AdventureBear** [freeCodeCamp/freeCodeCamp#49487]
### Describe the Issue

In the build a bike shop interactive project, the term "subshell", also "sub shell" (1 instance) is first used in step 1450 as an instruction without any definition of what a sub shell / subshell is.   The challenge has been using subshells since much earlier in the tutorial as well as in the prior coding challenges where bash is used to access a PSQL database, but the term is never explained. 

`Take that echo command and the part that formats it, put it in a sub shell, and...`

This creates cognitive friction during this step and doesn't allow for the "interactive video game flow state" that is desired in the FCC curriculum.  

I'd suggestion a simple sentence that explains what a subshell is before using the term as part of a coding instruction step.   It would probably be best to introduce this term back in the Build a student database project since that is the first occurence of using the syntax 

### Affected Page

https://github.com/freeCodeCamp/learn-bash-and-sql-by-building-a-bike-rental-shop/blob/main/TUTORIAL.md#1415-add-bike_info_formatted

### Your code

NA - for instructions issue 

### Expected behavior

NA - for instructions issue 

### System

- Device: [Laptop]
- OS: [e.g. iOS 12.6.1]
- Browser: [Chrome]
- Version: [e.g. 109]

### Additional context

Address how the wording interferes with the flow state described here: 

> https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges
> 
> We want campers to achieve a flow state. We want them to build momentum and blast through our curriculum with as few snags as possible. We want them to go into the projects with confidence and gain a wide exposure to programming concepts

.

**Comment by SwapnilThatte** [comment]
Where should I add the definition of subshell ? can you tell me the name of the file and path of the file ?

Definition of Subshell : A subshell is a child process launched by a shell (or shell script). A subshell is a separate instance of the command processor.

Also, is above definition of subshell correct ?

**Comment by raisedadead** [comment]
Hey @moT01 do you mind taking a look and triage this?
