### ISSUE TITLE
Basic JS steps need updates to facilitate translation

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49484]
### Describe the Issue

Similar to issue #49408 
Please also update another step that has the same issue and should get a similar fix:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-and-operator

The sentence:
"will only return Yes if num is greater than 5 and less than 10. The same logic can be written as:"
should be changed to:
"This will only..."
(adding This is enough to fix it as a reference to the previous code block)

And similarly for this step as well:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-or-operator

### Affected Page

Multiple

### Your code

```

```

### Expected behavior

As described above

### System

N/A

**Comment by jeremylt** [comment]
Proposed change:

> The same effect could be achieved by nesting an `if` statement inside another `if`.
```javascript
if (num > 5) {
  if (num < 10) {
    return "Yes";
  }
}
return "No";
```
> This code will return `Yes` if `num` is greater than `5` and less than `10`. The same logic can be written with the logical and operator.
```javascript
if (num > 5 && num < 10) {
  return "Yes";
}
return "No";
```

Question - do we use `Yes` or `"Yes"` for string literals?

**Comment by azr-arch** [comment]
> Proposed change:
> 
> > The same effect could be achieved by nesting an `if` statement inside another `if`.
> 
> ```js
> if (num > 5) {
>   if (num < 10) {
>     return "Yes";
>   }
> }
> return "No";
> ```
> 
> > This code will return `Yes` if `num` is greater than `5` and less than `10`. The same logic can be written with the logical and operator.
> 
> ```js
> if (num > 5 && num < 10) {
>   return "Yes";
> }
> return "No";
> ```
> 
> Question - do we use `Yes` or `"Yes"` for string literals?

"yes" i think

**Comment by shoaib-31** [comment]
Please assign this issue to me i think can fix this and make my first contribution to open source

**Comment by gikf** [comment]
Hey @shoaib-31

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by shoaib-31** [comment]
I have created a pull request, what should i do next?(It's my first contribution, don't mind my stupid questions please)
