### ISSUE TITLE
Setup sessions

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#49489]
After verifying the Auth0 access token and fetching the user details, we create a session token which will hold the session details and that's sent as a cookie to frontend.

Data to be stored in session token:
* User ID
* Scopes - To Confirm

**Comment by ShaunSHamilton** [comment]
Are we not just going to keep using Passportjs? I have never used it to store custom fields (e.g. scopes), though.

**Comment by Nirajn2311** [comment]
Wait what. I thought we were done with Passport. In that case I'll stop working on the PR until some details are worked out.
