### ISSUE TITLE
Bonfire: Check for Palindromes Last string to be parsed expects true, but it's actually false.

### ISSUE THREAD

**Issue by traianmunteanu** [FreeCodeCamp/FreeCodeCamp#4949]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20str%20%3D%20str.replace(%2F%5CW%2Fg%2C%20%27%27)%3B%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20return%20str%20%3D%3D%20str.split(%27%27).reverse().join(%27%27)%3B%0A%7D%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  str = str.replace(/\W/g, '');
  str = str.toLowerCase();
  return str == str.split('').reverse().join('');
}


palindrome("eye");

```

Last string to be checked is "0_0 (: /-\ :) 0-0" and as you can see the underscore from index 1 doesn't match the hyphen from the last chars. Just a typo, but still.

**Comment by SaintPeter** [comment]
Please re-read the instructions carefully.  You need to remove all non-alphanumeric characters.  If you do so, you'll see that the last test resolves to `0000`.

In the future, please ask for help in the [Bonfire Help Room](https://gitter.im/FreeCodeCamp/HelpBonfires?utm_source=share-link&utm_medium=link&utm_campaign=share-link) before posting an issue.

**Comment by SaintPeter** [comment]
Also, look at all of these closed issues with exactly the same issue reported:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues?utf8=%E2%9C%93&q=is%3Aissue+palindrome
