### ISSUE TITLE
Learn Bash by Building a Boilerplate Can't Proceed on rmdir images part

### ISSUE THREAD

**Issue by plopop0** [freeCodeCamp/freeCodeCamp#49496]
### Describe the Issue

[This part in the Bash course](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md#1150-remove-directory) I'm led to believe that I have to input `rmdir images` and receive an error and proceed to the next stage suggested by [this part in the tutorial](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md#1170-remove)

but upon doing so I'm not able to proceed. even with a soft reset or a hard reset

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate

### Your code

```
rmdir images
```

### Expected behavior

The usual check and progress clock widget indicating I was correct.

### Screenshots

https://user-images.githubusercontent.com/61111771/221210496-fe61a670-5c95-4273-989f-26781b9d461d.mp4

### System

- Device: [Desktop PC]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: [22] idk wat ver

**Comment by hbar1st** [comment]
Can you click into the review area of coderoad (through the hamburger menu at the top of the coderoad tab when you scroll all the way up) and see which step was last checked? (What was the number?)

**Comment by plopop0** [comment]
certainly!
It's the `View the file tree of this folder to make sure all your images are over in their new folder. Don't use any flags.`

![image](https://user-images.githubusercontent.com/61111771/221334090-c8bc10f2-3cb1-4db3-96f5-99747488d74c.png)

**Comment by hbar1st** [comment]
Can you try to click the reset button in the middle of the screen (not the soft reset). And then after it is done, close the bash terminal for good measure and open a new one to try the command in?

**Comment by plopop0** [comment]
It worked now thanks!

**Comment by hbar1st** [comment]
please close this issue. (please consider posting on the forum when you run into trouble before creating an issue to make sure that you get timelier help)
