### ISSUE TITLE
Minor Spelling Mistake in Relational Database (Beta)/Bash

### ISSUE THREAD

**Issue by plopop0** [freeCodeCamp/freeCodeCamp#49490]
![2023-02-24_17h01_48](https://user-images.githubusercontent.com/61111771/221137525-a81cf182-bae5-47af-8942-eb25f6eafc7a.png)

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

**Affected File**: https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md#7701

**Special Instructions to work on this curriculum**: https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad
