### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by BPagoaga** [FreeCodeCamp/freecodecamp#495]
There are two bugs I would like to report: 
- I could not reach my "next challenge" today, the link brought me to the first challenge, which I already completed
- I have "Syntax error, unrecognized expression" in the "Waypoint: Create a text field", which prevent me from going further.

**Comment by QuincyLarson** [comment]
@bpagoaga

The "learn" link will always take you to whichever challenge you were last working on. 

Could you attach a screen shot of the issue you're experiencing with the Create a text field waypoint? 

Thanks for submitting this!

**Comment by terakilobyte** [comment]
Regarding your first issue, this is known behavior. We moved to a
completely new system for serving challenges, and things were moved around
a lot! The first time you logged in the new system wasn't sure where to put
you so it defaulted to the first challenge. None of your progress is lost,
and you are absolutely free to find the challenge you were working on
through the map view. Whichever one you select will be set as your current
challenge, and you can progress linearly from there.

**Comment by QuincyLarson** [comment]
We've fixed this. Thank you for your patience, and for bringing this to our attention!
