### ISSUE TITLE
RTL Translation needs expected output lines to appear in a code block (basic JS course)

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49515]
### Describe the Issue

In the challenge file:
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings.md

This code:
<blockquote>FirstLine<br>    \SecondLine<br>ThirdLine</blockquote>

Currently is displayed in English but starting from the right (aligned to the right) in the Arabic translation.
I believe this is because it was not wrapped in code blocks.

It needs to be fixed as it represents the expected output from the program. (which will always be aligned on the left, not the right)

Screenshots included.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings

### Your code

```

```

### Expected behavior

use code blocks around the lines of expected output

### Screenshots

![arabic-8](https://user-images.githubusercontent.com/35541470/221368344-96596aeb-e9f1-48ab-8925-8deb3048aea9.png)

### System

N/A

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.
