### ISSUE TITLE
Not all objects have prototype property

### ISSUE THREAD

**Issue by rickychou2023** [freeCodeCamp/freeCodeCamp#49526]
### Describe the Issue

When I learned the JavaScript,I saw this expression "Nearly every object in JavaScript has a prototype property which is part of the constructor function that created it.", I give me a vibe that "All objects in JavaScript have prototype property". I don't know if this is my misunderstanding, If not , correct it！💥 It will bring great misleading to novices.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/use-prototype-properties-to-reduce-duplicate-code

### Your code

```
none
```

### Expected behavior

Correct it into below👇🏻
“Nearly every object in JavaScript has a constructor that created it ,and this constructor function has a prototype property.”

### System

- Device: [Laptop]
- OS: [MacOs 13.2]
- Browser: [Chrome]
- Version: [110.0.5481.177]

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

> "Nearly every object in JavaScript has a prototype property which is part of the constructor function that created it.", I give me a vibe that "All objects in JavaScript have prototype property"

I am not sure what you mean by this. I am not sure how you interpret _"all objects"_ from the words _"nearly every object"_

---

Aside from that, I suggest we remove the sentence completely. It does not do much, and is incorrect:

> Every object in JavaScript has a built-in property, which is called its prototype.
> https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#the_prototype_chain

I believe the sentence is referring to some primitives like `number` which do not have a property `prototype`. However, these are not objects, unless referring to the [Number object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number). _man, js is confusing_

**Comment by rickychou2023** [comment]
@ShaunSHamilton Sorry, I am not good at English.I didn't expect MDN to have a similar expression, because I didn't read the English version before.By the way, you just said that this expression is incorrect and gave you your thoughts

> I believe the sentence is referring to some primitives like number which do not have a property prototype.
I remember that not only some primitives like number do not have a property prototype, but also an object like this `const student = { name:"Ricky"}` does not have a property prototype too.
<img width="276" alt="image" src="https://user-images.githubusercontent.com/81011929/221421348-d6d4aef8-2945-42e1-85f8-d3498fc1d58f.png">
It seems that only functions have a property prototype.

**Comment by ShaunSHamilton** [comment]
All JavaScript objects have prototypes - not just functions: https://replit.com:/@Sky020/Nodejs

Hope this clarifies

**Comment by ojeytonwilliams** [comment]
I agree with @ShaunSHamilton - that sentence is confusing at best. I vote we remove it.

**Comment by rickychou2023** [comment]
> All JavaScript objects have prototypes - not just functions: https://replit.com:/@Sky020/Nodejs
> 
> Hope this clarifies

@ShaunSHamilton Sorry to reply you so late, did you mean that "the prototype exists in its prototype chain" can be called "an object have a prototype"?But I think that only "the prototype exists in itself" can be called "an object have a prototype"😀.Indeed, this sentence is not clear enough, it will be confusing, just like the one between the two of us.

**Comment by rickychou2023** [comment]
Sorry to reply your so late. Well, I think I may be aware of the key to the problem. I just looked at the definition of _Property_. _Property_ included three parts: https://developer.mozilla.org/en-US/docs/Glossary/Property/JavaScript

- key
- value
- some attributes

I used to think that _Property_ only refers to the key. Okay, I admit that I have always been wrong before🥹.
Then I looked at the definition of _Prototype_ again, but unfortunately I did not find a very clear definition. I only saw the following sentence

> Each object has a private property which holds a link to another object called its prototype.

I seem to understand _Prototype_ as an object, it does not contain Key, right? If so, The _Property_ cannot be put together with _Prototype_, because Property contains Key + Value + Attributes, but _Prototype_ is just a value, and it is an Object Value.
Although there is such an expression in MDN:

> Every object in JavaScript has a built-in property, which is called its prototype.
> https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#the_prototype_chain

But there is also such a note below:

> The property of an object that points to its prototype is not called prototype
> https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#the_prototype_chain

This really makes me feel confused🤥.

**Comment by ShaunSHamilton** [comment]
@rickychou2023 I suggest you ask your questions on [the forum](https://forum.freecodecamp.org/).

---

To summarise:

- Everything in JavaScript is an object. **except for some primitives**
- Every object has a prototype
- Prototypes are objects
- You cannot access an object's prototype by using `myObject.prototype`, because the prototype is not explicitly named `prototype`
- Often, the prototype is called `__proto__`, in which case it is possible to access it using `myObject.__proto__`

If you have any more questions, please head over to the forum. A Github issue is not the best place for such discussion.

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

**Affected file**: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/use-prototype-properties-to-reduce-duplicate-code.md

**Changes to Close**:

- Remove this sentence from the instructions (description):
> Nearly every object in JavaScript has a `prototype` property which is part of the constructor function that created it.
