### ISSUE TITLE
Font Size Not Validating Properly For The Second P Tag, Even If the Second P Tag Font is not set to 16px it is not throwing error

### ISSUE THREAD

**Issue by rajendrach** [FreeCodeCamp/FreeCodeCamp#4953]
Challenge [Waypoint: Change the Font Size of an Element](http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by BerkeleyTrue** [comment]
Passes for me. Which browser are you using?

**Comment by rajendrach** [comment]
I'm sorry it passes for me too, but it should not pass since I had the font size set to color class instead of .p{} it should only pass when is set .p{font-size:16px}

Sent from Outlook




On Wed, Dec 2, 2015 at 4:15 PM -0800, "Berkeley Martinez" <notifications@github.com> wrote:





Passes for me. Which browser are you using?

---

**Comment by SaintPeter** [comment]
Confirmed.

The tests need to check that there are two `p` elements with the style `red-text`.

**Comment by DDaems** [comment]
Allready got a pullrequest ready, commiting it now
