### ISSUE TITLE
Unclear instructions for QA metric-imperial-converter

### ISSUE THREAD

**Issue by konjoinfinity** [freeCodeCamp/freeCodeCamp#49549]
### Describe the Issue

Per request from previous PR:

https://github.com/freeCodeCamp/freeCodeCamp/pull/49541

While completing the metric-imperial-converter challenge I wasted hours attempting to use repl.it, as outlined in the instructions. I never got repl.it to work for this challenge, despite troubleshooting for hours and asking around in the forums. And because I posted in the forums, I found out that glitch.me is an alternative to repl.it. Glitch.me also didn't work for me, as it strips api queries with double slashes ('//'). Nowhere in the instructions does it say "If repl.it doesn't work, try another platform/app hosting service". Render.com finally did work for me.

All it says: "Use a site builder of your choice to complete the project."

A simple line in the instructions saying, "If one site builder does not work for you, try another" would suffice.

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter

### Your code

```
https://broadleaf-jealous-mine.glitch.me/api/convert?input=1//2gal

{"initNum":0.5,"initUnit":"gal","returnNum":1.89271,"returnUnit":"L","string":"0.5 gallons converts to 1.89271 liters"}
```

### Expected behavior

https://broadleaf-jealous-mine.glitch.me/api/convert?input=1//2gal

should output: {'invalid number'}

Please see forum post link below for more information.

### Screenshots

![Screen Shot 2023-02-28 at 11 27 39 AM](https://user-images.githubusercontent.com/46323883/221915816-433f5861-cc25-4f0e-be73-2e0745cc0d1e.png)

![Screen Shot 2023-02-28 at 11 28 35 AM](https://user-images.githubusercontent.com/46323883/221916062-000f0860-25a0-425d-917e-8514ecbe96a1.png)

### System

- Device: Laptop
- OS: MacOS 12.6.1
- Browser/Version: Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (x86_64)](https://brave.com/latest/)

### Additional context

Please see this forum post for more information.

https://forum.freecodecamp.org/t/last-4-metric-tests-for-qa-metric-imperial-converter/594874/1

**Comment by jeremylt** [comment]
I wouldn't say the instructions are "incomplete" since, as you noted, the instructions say

> Working on this project will involve you writing your code using one of the following methods:

> *   Clone [this GitHub repo](https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/) and complete your project locally.
> *   Use [our Replit starter project](https://replit.com/github/freeCodeCamp/boilerplate-project-metricimpconverter) to complete your project.
> *    Use a site builder of your choice to complete the project. Be sure to incorporate all the files from our GitHub repo.

Since the project isn't about how to build and deploy an app, I wouldn't expect the instructions to be focused on that. I wonder if there is an article or video we have on fCC about these hosting options that we could link to in a more central location, like the superblock summary for the relevant courses?

**Comment by lasjorg** [comment]
Personally, I would prefer if we allowed locally submitted projects with a GitHub repo as the source of truth. I realize this would make Git/GitHub (or one of the alternatives) a requirement. But at this point in the camper's learning path, I don't think that is an unreasonable requirement.

After the local project submitted passes all the tests, a new input would show up for a repo link. This wouldn't be checked (except maybe for a valid URL) and would be saved as the solution. The code can be checked if needed and it will likely survive longer than code on some online editor sites.

The requirement for the project to be "live" is an unreasonable requirement and does not work. Any project that is using MongoDB Atlas will have the cluster paused at some point rendering the live solution link invalid and in some cases, the actual code will not be available to be checked. There can be no expectation of the live link remaining available in a working condition passed say a month.

**Comment by naomi-lgbt** [comment]
> Personally, I would prefer if we allowed locally submitted projects

How would we test them?

**Comment by lasjorg** [comment]
We would test what is submitted just as we do now, so the project running on localhost or a live URL. But the URL for the finished project would be allowed to be a repo.

After all the tests have passed the input for the finished project submission would be shown (and not before that).

**Comment by Sboonny** [comment]
The instruction mention our recommendation, we don't mind using different other services to host your own project, but the instruction doesn't mention requiring Replit.

> Use a site builder of your choice to complete the project. Be sure to incorporate all the files from our GitHub repo.

mentioning alternative to other services, will be redundant after mention the ability to pass the test with the other services
