### ISSUE TITLE
The IDE of the web is generating arrays with spaces and is not passing the giving test in the javascript-algorithms-and-data-structures-projects/cash-register

### ISSUE THREAD

**Issue by nzo8222** [freeCodeCamp/freeCodeCamp#49540]
**Describe the bug**
The IDE of the web is generating arrays with spaces and is not passing the giving test

**To Reproduce**

1. Go to 
 https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register
give this code:

function calculateChange(change, cid) {
  
  let arr = [];
  
  let globalChange = change;
  let twenties = cid.filter(elem => elem[0] === "TWENTY").flat();
  if(globalChange > twenties[1] && globalChange > 20)
  {
    globalChange = globalChange.toFixed(2) - twenties[1];
    arr.push(["TWENTY", twenties[1]])
  }

  let tens = cid.filter(elem => elem[0] === "TEN").flat();
  //console.log(globalChange.toFixed(2));
  if(globalChange > tens[1] && globalChange > 10){
    globalChange = globalChange.toFixed(2) - tens[1].toFixed(1);
    arr.push(["TEN", tens[1]])
  }
  //console.log(arr);
  let fives = cid.filter(elem => elem[0] === "FIVE").flat();
  //console.log(globalChange.toFixed(2));
  if(globalChange < fives[1] && globalChange > 5) {
    let residue = globalChange % 5;
    //console.log(residue.toFixed(2))
    let fivesTotal = globalChange - residue;
    //console.log(fivesTotal)
    arr.push(["FIVE", fivesTotal])
    globalChange = residue.toFixed(2);
  }
  //console.log(globalChange);
  let ones = cid.filter(elem => elem[0] === "ONE").flat();
  //console.log(ones);
  if(globalChange < ones[1] && globalChange > 1){
    let residue = globalChange % 1;
    //console.log(residue);
    let oneTotal = globalChange - residue;
    //console.log(oneTotal);
    arr.push(["ONE", oneTotal]);
    globalChange = globalChange - oneTotal;
  }
  let quarters = cid.filter(elem => elem[0] === "QUARTER").flat();
  //console.log(arr);
  if(quarters[1] > globalChange) {
    //console.log(quarters[1]);
    let residue = globalChange % .25;
    //console.log(residue);
    let quarterTotal = globalChange - residue;
    arr.push(["QUARTER", quarterTotal.toFixed(1)])
    globalChange = residue;
  }
  console.log(arr);
  let dimes = cid.filter(elem => elem[0] === "DIME").flat();
  if(dimes[1] > globalChange && globalChange != 0) {
    let residue = globalChange.toFixed(2) % .1;
    //console.log(residue.toFixed(2));
    let dimesTotal = globalChange - residue;
    globalChange = (globalChange.toFixed(2) - dimesTotal.toFixed(2));
    arr.push(["DIME", dimesTotal]);
  }
  console.log(globalChange.toFixed(2));
  
  let penny = cid.filter(elem => elem[0] === "PENNY").flat()
    let localChange = (change % 0.05);
    localChange = parseFloat(localChange.toFixed(2));
    if(localChange < penny[1] && globalChange > 0) {
      globalChange = globalChange - localChange;
      globalChange = parseFloat(globalChange.toFixed(1));
      arr.push(["PENNY", localChange]);
    }
  //console.log(arr[0][0]);
  return arr;
}
function checkCashRegister(price, cash, cid) {
  let total = 0.0;
  for(let i = 0 ; i < cid.length; i++) {
    //console.log(cid[i]);
    total += cid[i][1];
  }
  console.log("Total en caja: " + total);
  let change = cash - price;
  console.log("Total cambio: " + change);
  if(change < total) {
    let arr = calculateChange(change, cid);
    //console.log(arr);
    if(arr.length === 0) {
      return {status: "INSUFFICIENT_FUNDS", change: arr}
    }
    return { status: "OPEN", change: arr}
  }else if( change == total) {
    let arr = calculateChange(change, cid);
    return {status: "CLOSED", change: arr}
  } else {
    let arr = [];
    return {status: "INSUFFICIENT_FUNDS", change: arr}
  }
}

console.log(checkCashRegister(3.26, 100, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.1], ["QUARTER", 4.25], ["ONE", 90], ["FIVE", 55], ["TEN", 20], ["TWENTY", 60], ["ONE HUNDRED", 100]]))

4. the console is returning:

Total en caja: 335.40999999999997
Total cambio: 96.74
[ [ 'TWENTY', 60 ],
  [ 'TEN', 20 ],
  [ 'FIVE', 15 ],
  [ 'ONE', 1 ],
  [ 'QUARTER', '0.5' ] ]
0.04
{ status: 'OPEN',
  change: 
   [ [ 'TWENTY', 60 ],
     [ 'TEN', 20 ],
     [ 'FIVE', 15 ],
     [ 'ONE', 1 ],
     [ 'QUARTER', '0.5' ],
     [ 'DIME', 0.2 ],
     [ 'PENNY', 0.04 ] ] }

**Expected behavior**
It should return the array without spaces and pass the test, I tried 2 days ago and it was working as inteded it showed the array without the spaces and the test were passing

**Screenshots**
![image](https://user-images.githubusercontent.com/38313920/221640690-e355f70e-c37b-4ee7-8c65-eb3d23d910a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Versión 110.0.5481.105 (Build oficial) (64 bits)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by nzo8222** [comment]
sorry to post this here I tried to post it on the forum but it keeps saying you cannot post a link to that host, idk what does it means im reuploading the img on that post and removed all the links from the post and giving it the javascript subject

**Comment by gikf** [comment]
You don't need to add image to post, it doesn't add any new information to it.
