### ISSUE TITLE
well the uncommenting isn't working.  I just started the course.  It's the second question.

### ISSUE THREAD

**Issue by fitadelphia** [FreeCodeCamp/FreeCodeCamp#4954]
Challenge [Waypoint: Uncomment HTML](http://www.freecodecamp.com/challenges/waypoint-uncomment-html?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (MSIE 9.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

```

**Comment by fitadelphia** [comment]
still not working.

**Comment by BerkeleyTrue** [comment]
Looks like the test for this one got mangled in the recent update. Thanks for reporting. Will fix soon

**Comment by jca322** [comment]
+1

**Comment by tthompson899** [comment]
+1

**Comment by sekigahara** [comment]
+1

**Comment by reconcoder** [comment]
Yeah @fitadelphia, I'm having the same issue here.
@BerkeleyTrue, How long will it take to fix this problem?
