### ISSUE TITLE
ES6 JS step introduces rest arguments but drops in an unexplained mention of map/filter/reduce

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#49557]
### Describe the Issue

In the JS ES6 step titled “Use the Rest Parameter with Function Parameters”, the explanation provided makes casual mention of map/filter and reduce without any prior discussion or introduction of these functions. I suggest that this paragraph is either unnecessary at this point or it should explicitly say that these functions will be introduced later.

here is the text of the paragraph for your convenience:
The rest parameter eliminates the need to check the args array and allows us to apply map(), filter() and reduce() on the parameters array.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-the-rest-parameter-with-function-parameters

### Your code

```

```

### Expected behavior

Either drop the paragraph from this topic or explicitly say that these functions will be explained later on.

### System

N/A

**Comment by hbar1st** [comment]
I just noticed that the code in this step also uses the reduce function without explanation as well. I feel sure that I am not the first to notice this (I recall at least one forum post about this). 

I think instead of using reduce the initial code should be changed to use a simple for loop that does the addition.
For eg instead of this:
```
const sum = (x, y, z) => {
  const args = [x, y, z];
  return args.reduce((a, b) => a + b, 0);
}
```
use this:
```
const sum = (x, y, z) => {
  const args = [x, y, z];
  let theSum = 0;
  for (let i = 0; i < args.length; i++) {
    theSum += args[i];
  }
  return theSum;
}
```

Using a for loop wouldn't change the point of this exercise which is to learn how to accept a dynamic number of params with the rest parameter.

**Comment by hbar1st** [comment]
That's great. I guess it hasn't made it out to users yet. I'll try to find the PR or issue, then I will close this.

**Comment by jeremylt** [comment]
The change has made it to users, that's why I can see it. But I think we still need *another* change to drop the mention of specific array methods that haven't been taught yet.

**Comment by hbar1st** [comment]
yes I just looked up the pr #49525 and I see that we do need to drop the paragraph about map/filter/reduce still.
I think I need to clear all the cache in my browser because I didn't see the for loop yesterday when I was going through the step.
