### ISSUE TITLE
Learn HTML by Building a Cat Photo App - Step 67 Lang attribute issue

### ISSUE THREAD

**Issue by ZachDupureur** [freeCodeCamp/freeCodeCamp#49562]
### Describe the Issue

Simple issue. When typing in the attribute for "lang" if you type a space between the attribute and the value it will mark it as incorrect. Even though it may not be proper formatting, it may be confusing for beginners that have used spaces up until this point. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-67

### Your code

```
<html lang = "en">
```

### Expected behavior

It should accept the code as fine and continue to the next lesson. 

### Screenshots

![Capture](https://user-images.githubusercontent.com/70533791/222272185-9fe080e1-680c-46f1-8ebf-5e89c5b7467d.PNG)

### System

- Device: Desktop 
- OS: Windows 10
- Browser: Mozilla Firefox
- Version: 110.0 (64-bit)

**Comment by Dibyajyoti2002** [comment]
Hi! I just removed the space in between and it seems to be working fine as can be seen in the following image where I am getting the option to continue to the next challenge.

![image](https://user-images.githubusercontent.com/72976359/222333412-d8768118-44ad-4dd2-8cbe-0d3345370a90.png)

**Comment by ZachDupureur** [comment]
> Hi! I just removed the space in between and it seems to be working fine as can be seen in the following image where I am getting the option to continue to the next challenge.
> 
> ![image](https://user-images.githubusercontent.com/72976359/222333412-d8768118-44ad-4dd2-8cbe-0d3345370a90.png)
> 

Correct this is the intended way of doing this exercise. What I'm saying is that for beginners that include a space ( which isn't technically wrong ) it may be confusing.

**Comment by CallmeHongmaybe** [comment]
I second this issue.

**Comment by jashgudhka** [comment]
I agree with you, Mr. Zach
I started using FreeCodeCamp this week and started with "(New) Responsive Web Design"
At first, I was confused why it would not work, But then I searched for the issue and found we have to remove the space in between...I also had a similar problem with an attribute in HTML tags but I moved on by not adding the spaces in between.

**Comment by Sboonny** [comment]
Here is the file https://github.com/freeCodeCamp/freeCodeCamp/blob/66438c271f85e9eb6834dcaec2de9c1be8fa9ed6/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804ec.md?plain=1#L12

The test after it has regex that allow spacing, the fix should be similar. 

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by Sagargupta16** [comment]
Hey Can i Get Assigned for this issue?

**Comment by Sboonny** [comment]
Only issues with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by jashgudhka** [comment]
> Here is the file
> 
> https://github.com/freeCodeCamp/freeCodeCamp/blob/66438c271f85e9eb6834dcaec2de9c1be8fa9ed6/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804ec.md?plain=1#L12
> 
> The test after it has regex that allow spacing, the fix should be similar.
> 
> If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

I am excited to try to solve this issue, I will read the guidelines tomorrow and try to find an appropriate solution for it.
Thank you for giving me this opportunity.

**Comment by bbsmooth** [comment]
The last two tests for this step seem to be redundant. The second to last test requires quotes around the value and then the last test just checks for quotes around the value again. So they are doing the same thing but have different hints.

Do we really want to enforce quotes around the value? Yes, it seems like a best practice, but it is not required in this case.

**Comment by bbsmooth** [comment]
Also, if we are going to be lenient on spaces for this tag then we should also allow extra spaces between `html` and `lang` and also at the end of the tag before the closing `>`.

The last test already does this:

```
assert(code.match(/<html\s+lang\s*=\s*('|")en\1\s*>/gi));
```

It seems like the current last test does everything we need and we can just get rid of the second test. If we are going to require quotes around the value then we could add that information to the hint. Personally, I don't think we should require the quotes and we can fix the regexp to make them optional.
