### ISSUE TITLE
Stuck in Specify How Fonts Should Degrade. My code is degrading the font. 

### ISSUE THREAD

**Issue by caos21** [FreeCodeCamp/FreeCodeCamp#4956]
Challenge [Waypoint: Specify How Fonts Should Degrade](http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade?solution=%3C!--%20%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%20--%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.

In my understanding we only need to comment out the "google call" or the first line like this
<code> </code>
because the code has already in h2 the degradation of the fonts ```font-family: Lobster, Monospace;```
(After  reset code I have )

```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
But it does not work. I reset the code and refresh (F5) but I can't proceed to the next exercise.

My solution:

![code](https://cloud.githubusercontent.com/assets/12665566/11548708/42daadf0-992d-11e5-85a7-9f886c87afb2.png)

**Comment by jmaud** [comment]
This still seems to be broken.  I'm having the same issue as the OP.

**Comment by CodeFlangela** [comment]
I have the exact same problem with degrading my code as well, I cannot move to the next exercise. If I remove the  , then 2 of my problems are correct. But if I add them in, my 2 correct ones become incorrect and I'm correct on the other 2 that were wrong. There seems to be no correct answer. My code is attached below: Can someone please help me here?  Thanks, AF


<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family:, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by CodeFlangela** [comment]
Sorry!

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family:, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by angelsuaste2414** [comment]
The comment in css is not  instead use /* */ to comment your code.

**Comment by angelsuaste2414** [comment]
The comment in css is not  instead use /* */ to comment your code.

**Comment by angelsuaste2414** [comment]
Before Monospace you need to erase the comma ",".  Sorry for my english i speak spanish.

**Comment by CodeFlangela** [comment]
Okay, thank you so much for replying. Let me try it now.

**Comment by CodeFlangela** [comment]
h2 {
    font-family /*Lobster*/  Monospace;
  }

**Comment by angelsuaste2414** [comment]
And why not erase the Lobster word? You can't?

2016-08-11 16:26 GMT-05:00 Angela Foster <notifications@github.com>:

**Comment by BerkeleyTrue** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.


Happy Coding

**Comment by angelsuaste2414** [comment]
Yeah hahaha, sorry.

2016-08-11 16:28 GMT-05:00 Berkeley Martinez <notifications@github.com>:

**Comment by CodeFlangela** [comment]
Yikes! Sorry I thought that's where I went. Work with me here, work with me. I will go there directly. 

Thanks much

Angela Foster

**Comment by locinj** [comment]
The **
  }

**Comment by axel8591** [comment]
You simple need to add your comment tag just below the script tag.

**Comment by bhundu07** [comment]
@caos21 i used your method to degrade lobster to Monospace buy putting the comments around the link for google fonts and it worked.thanx so much.

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: lobster,Monospace
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by byrdndocean** [comment]
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by byrdndocean** [comment]
Put your comment tags around the google link at the top

**Comment by pingati3000** [comment]
Solution:

**Comment by emmanuel180** [comment]
i have similar issues ...... degrading to monospace from lobster

**Comment by super032208** [comment]
comment the google links like this  and then in the CSS Style delete and rewritten like this h2{font-family: Lobster,monospace; } and Ready for the next challenge

**Comment by khan97** [comment]
<link href="https://fonts.googleapis.com/css?family=                     " rel="stylesheet" type="text/css">
