### ISSUE TITLE
Use less ambiguous switch example code

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#49577]
### Describe the Issue

It isn't a huge deal, but I do think the camper has a point, see the forum thread for more info. I think updating the example code with something less ambiguous wouldn't be a horrible idea.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/selecting-from-many-options-with-switch-statements

### Your code

Current example 

```
switch (lowercaseLetter) {
  case "a":
    console.log("A");
    break;
  case "b":
    console.log("B");
    break;
}
```

New example (I can't think of anything better right now, you get the point).
```
switch (heroName) {
  case "Spider-Man":
    console.log("Peter Parker");
    break;
  case "Batman":
    console.log("Bruce Wayne");
    break;
}
```

### Expected behavior

Less ambiguous example code that does not involve letter case logic or identifiers with the word `case` in it when teaching about `switch` and `case`.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/remove-lowercase-and-uppercase-from-switch-statement-examples/595946

**Comment by John-I-Am** [comment]
I agree, the example is unnecessarily confusing. I have submitted a pull request that uses a classic fruit example. The console log is also more explicit on what is being selected.

Additionally, may I suggest that we also change the instructions to be more explicit? So instead of: 

`1` - `alpha`  

it'll be something like:

`val = 1` - `answer = alpha`

Additionally, additionally, may I also suggest we expand the explanation on strict equality testing? So add a simple sentence like:

"Strings with different cases will be treated as different values"

**Comment by lasjorg** [comment]
> Additionally, may I suggest that we also change the instructions to be more explicit?

I guess the conditions can be clarified, but I don't remember seeing this being a problem.

> "Strings with different cases will be treated as different values"

That isn't how strict equality works. It has to do with type coercion. Letters with different casings always have different values.

```
"s" == "S"
// false
```


```
const number = '1';

switch (number) {
  case 1:
    console.log(typeof number); // nothing is logged
    break;
  case '1':
    console.log(typeof number); // string
    break;
}

if (number == 1) {
  console.log(typeof number); // string
}

if (number === 1) {
  console.log(typeof number); // nothing is logged
}
```

**Comment by John-I-Am** [comment]
Yes I get that, but for this specific example, I just thought it would be good to keep it simple. 

On second thought, the explanations / instructions are good enough. Lets leave it as it is.

**Comment by praneeth16042003** [comment]
hello can you please tell me why my pull requests are getting blocked when I am trying to close an issue
