### ISSUE TITLE
Allow console.log without failing test

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#49596]
### Describe the Issue

It would be nice if we allowed the camper to log out the result without having the last test fail because of it.

One option might be to use code comments as delimiters to help make the regex more targeted.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/divide-one-decimal-by-another-with-javascript

### Your code

```

```

### Expected behavior

The camper should be allowed to log out the result without failing with the correct code.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/basic-javascript-divide-one-decimal-by-another-with-javascript/596393

**Comment by naomi-lgbt** [comment]
We could update the test to check for the assignment operator, instead of just a variable reference:

```js
assert(code.match(/quotient\s*=/g).length === 1);
```

**Comment by Sboonny** [comment]
Here is the file for the challenge:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/divide-one-decimal-by-another-with-javascript.md

**Comment by Sboonny** [comment]
Go for it.

**Comment by adilrana03** [comment]
Can I work on this issue?
