### ISSUE TITLE
@ occurrences of "and" found but it won't let me pass the waypoint

### ISSUE THREAD

**Issue by jwianniello** [FreeCodeCamp/FreeCodeCamp#4959]
My code:
```javascript
var test = (function() {
  var testString = "Ada Lovelace and Charles Babbage designed the first computer and the software that would have run on it.";
  var expressionToGetSoftware = /software/gi;

  // Only change code below this line.

  var expression = /and/gi;

  // Only change code above this line.

  return testString.match(expression).length;
})();(function(){return test;})();

```
Original code has   var expression = /./gi;

Instructions say to switch "." to "and".  To pass it says "Your regular expression should find two occurrences of the word and."  The functions produces two occurrences of and but this red x won't turn to a check and let me complete the waypoint.

**Comment by cbRoy** [comment]
This worked fine when I completed it before. Just opened the WP and ran my same code, and boom finds the 2 but still has red x.

**Comment by jwianniello** [comment]
@cbRoy Ok, thanks for the response.  So it's not just me right? The same thing happened to me on the next waypoint.

**Comment by ADude2** [comment]
Same is happening for me as well!  Console log is returning "2" and the "Your regular expression should find two occurrences of the word and." test is still failing

**Comment by EQuimper** [comment]
So is just a bug ?

**Comment by SaintPeter** [comment]
Yup, confirmed.

This does appear to be a site bug.

**Comment by ADude2** [comment]
I'll take care of it.

**Comment by SaintPeter** [comment]
The problem is that `test` collides with an existing variable used in the infrastructure.

**Comment by ADude2** [comment]
Could it be that 
```
"tests": [
        "assert(test==2, 'message: Your <code>regular expression</code> should find two occurrences of the word <code>and</code>.');",

```

test should be === instead of == ?
