### ISSUE TITLE
Code with infinite loop can incorrectly pass tests

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#49594]
### Describe the Issue

Having infinite loop in code can lead to passing tests, when they should not pass (due to having infinite loop).

I guess this is a very specific case for loop protection. I was playing around with code hitting maximum call stack size. While changing it into iterative version, I encountered intermediate state that's passing, but it should not.

Loop protection breaks out of the infinite loop, but further code is still executed. In this case that coincidentally means returning the right number.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/smallest-common-multiple

### Your code

```
function getNumber(num, min, max) {
  while (true) {
    for (let i = min; i <= max; i++){
      if(num % i !== 0){
        num = num + max;
        break;
      }
    }
  }
  return num;
}


function smallestCommons(arr) {
  const sortedArr = arr.sort(function(a, b){return a-b});
  const min = sortedArr[0];
  const max = sortedArr[sortedArr.length -1];

  return getNumber(max, min, max);
}
```

### Expected behavior

Code should not pass tests.

### System

n/a

**Comment by ojeytonwilliams** [comment]
The only fix I see is to automatically fail any solution that runs into the loop protect limits.

That said, I think this is enough of an edge case that it's fine to leave it alone.
