### ISSUE TITLE
Combine prism and prims-night CSS files

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49625]
There are multiple blockers for adding opt-in system theme PR https://github.com/freeCodeCamp/freeCodeCamp/pull/48757, simple one of them is the existence of files that don't use the variables in variables.css and create their own colors or style for the dark and light themes.

It would make my life easier if this file become one, with unanimous styles, and it uses variables in variables.css instead, so whenever we add new themes or create new themes, we don't have to update it, and just update the variables.css file.

But it isn't simple, because there are different styles and weird ones, as showing different cursor based on the theme and different spacing.

Here are the files

[prism-night.css](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/layouts/prism-night.css)
[prism.css](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/layouts/prism.css)
[variables.css](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/layouts/variables.css)

**Comment by Vansh-Baghel** [comment]
I didn't quite got what's the problem here. Do we need to store all the css file into 1 file?

**Comment by Sboonny** [comment]
- combine prism and prism-night
- stop using dark-pallete as selector
- the properties used for dark mode and light mode, can be discussed and made into one style that apply for both cases
- the color properties can use variables from variables.css file instead of set in stone values, because these vales won't work with new themes.

**Comment by ahmadabdolsaheb** [comment]
Sounds like a plan. How about keeping a files for the global variables (variables.css) and another prism specific one (prism + prism-night)

**Comment by Sboonny** [comment]
If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by nyni123** [comment]
Hi @Sboonny 

To achieve the consolidation of styles into one file:

1) I will copy the contents of prism-night.css and prism.css into a new file, let's call it prism-themes.css.
2) Then I will replace all the hardcoded colors and styles in prism-themes.css with the variables defined in variables.css.
3) As mentioned above, there may be some styles in these files that are specific to certain themes, such as different cursor styles or spacing so I will use CSS variables to define these theme-specific styles, and then reference them in consolidated prism-themes.css file

please confirm if my approach is appropriate for the FreeCodeCamp community

**Comment by Sboonny** [comment]
Welcome, and thanks for taking interest in this PR.

You are correct on the first three points, but the 3rd can be easier.

we don't need variables for the spacing and cursor style, it can be combined and applied in both themes, without changing the value based on the theme state.

**Comment by nyni123** [comment]
okay so I will Replace all hardcoded colors and styles in prism-themes.css with the variables defined in variables.css right? 
if yes can I start working on this?

**Comment by Sboonny** [comment]
Go for it 👍

**Comment by hectoraldairah** [comment]
Hi! This is still a live issue? I'd like to help consolidate the styles for prism.

**Comment by ellenfang77** [comment]
Hi, I would like to work on this issue
