### ISSUE TITLE
Fully type t function to get keys values as auto-complete in typescript

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49621]
While using the `t` function in multiple instances, I had issue with misspelling of keys or its values, this cased small bugs which keys value didn't show, or weird bugs in user validation which broke tests for weird reason.

Looking at the docs, if I am not misunderstanding it, we can have the keys show as auto-complete which can help with developer experience as it will be unlikely to have misleading typos.

https://react.i18next.com/latest/typescript

Here is an example of the files

https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple-multi-namespaces

Issue with the feature, it may cause lag in auto-complete, because of how big our JSON files are.

**Comment by ShaunSHamilton** [comment]
If this is easy to maintain, then I like the sound of it.

Our JSON files are quite small. So, I do not see that being a problem

**Comment by ojeytonwilliams** [comment]
Sounds good to me.  If I understand correctly, we should upgrade to the latest i18next and react-i18next and then follow https://www.i18next.com/overview/typescript.  Then some basic profiling would be good (just a comparison of `tsc` before and after).

@Sboonny is this something you wanted soon or can we open this up to contributors?

**Comment by Sboonny** [comment]
Looking at my ToDo list, I don't think I need to interact with the translations string for a while.

I am happy to open this for contribution.

---

To solve this issue, fully type the `t` function, so that TypeScript auto-completes strings when someone use it

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.
