### ISSUE TITLE
Do not manage PM2 with pnpm

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#49653]
As seen [here](https://contribute.freecodecamp.org/#/devops?id=first-install-1) we are installing and managing PM2 with pnpm as a dependency. 

This is not a great idea when we might have purged the repo of `node_modules` and need to manage the process. 

PM2 should instead be installed and used from the Global scope.

**Comment by raisedadead** [comment]
> what actions would you like to perform that you can't currently?

Doesn't matter. 

The issue is it leaves us to work with the API servers in a certain order which could be catastrophic.

Systemd depends on PM2 to be available at a certain location which can be purged by some of our scripts or using git clean etc. 

The API instance is lost if the system restarts during deployment instead of loading the last state gracefully.

pnpm should not manage PM2, or at least not where it is installed and how it is run.

As I always say, the tool should work for me, not the other way around.

**Comment by ojeytonwilliams** [comment]
> The API instance is lost if the system restarts during deployment instead of loading the last state gracefully.

Thanks for explaining - I'd not considered the possibility of the server rebooting after we'd cleaned out node_modules.

**Comment by Sembauke** [comment]
Seems like this was resolved, closing as is:
https://github.com/freeCodeCamp/freeCodeCamp/pull/49658#issuecomment-1637921186
