### ISSUE TITLE
Formatting issue on the 404 page

### ISSUE THREAD

**Issue by DylanDevelops** [freeCodeCamp/freeCodeCamp#49666]
### Describe the Issue

On the 404 page for [https://www.freecodecamp.org/404](https://www.freecodecamp.org/404), the `"` on the quote is clipped past the box it should be inside.

### Affected Page

https://www.freecodecamp.org/404

### Steps to Reproduce

Look at the quote on the 404 page.

### Expected behavior

The `"` should be inside the quote box.

### Screenshots

<img width="936" alt="Screenshot 2023-03-10 at 12 27 41 PM" src="https://user-images.githubusercontent.com/48571264/224410014-1930ff87-7095-413c-b4ec-2ae07911941c.png">

<img width="712" alt="Screenshot 2023-03-10 at 12 30 34 PM" src="https://user-images.githubusercontent.com/48571264/224410197-a9c4c878-0e9f-4b87-9757-b7361c4bc65f.png">

### System

- Device: Macbook Pro
- OS: OSX
- Browser: Safari
- Version: 16.1

**Comment by ArdonitSaliji** [comment]
What do you mean inside?

**Comment by DylanDevelops** [comment]
I feel like the quotation mark looks weird not being inside of the box the quote is in. its slightly sticking out of the box.

**Comment by Saikat-Mandal** [comment]
I want to work on this issue. Please assign it to me.

**Comment by ArdonitSaliji** [comment]
> I feel like the quotation mark looks weird not being inside of the box the quote is in. its slightly sticking out of the box.

It is not that noticeable I think.
This ticket should be closed maybe.

**Comment by DylanDevelops** [comment]
> > I feel like the quotation mark looks weird not being inside of the box the quote is in. its slightly sticking out of the box.
> 
> It is not that noticeable I think. This ticket should be closed maybe.

I'm afraid I have to disagree. Even if it's simple, having consistent and good formatting makes the website look so much more official and better. If people get certifications from this website, we should strive to make it look as consistent and professional as possible. Especially when companies might look at the website to see job applicants' certifications and such.

@Saikat-Mandal If you would like to work on it, just get started as issues are not assigned on this repository. Just create a pull request linked to this issue when fixed.

**Comment by Saikat-Mandal** [comment]
@DylanDevelops yeh , got it , i will be working on it then.

**Comment by ShaunSHamilton** [comment]
Issues with the `help wanted` label are open for contribution. Please read the contributors docs: https://contribute.freecodecamp.org

**Comment by DylanDevelops** [comment]
@ShaunSHamilton Any idea where the 404 page is to be edited?

**Comment by ArdonitSaliji** [comment]
For gods sake don't waste time on a quote, where you can do something 100x more productive.

**Comment by jeremylt** [comment]
The background box definitely looks shifted a little bit low to me.

**Comment by Saikat-Mandal** [comment]
Should I work on it or not then?

**Comment by jeremylt** [comment]
The issue has not been marked as ready for contributions with the `help wanted` label. If you have questions about how our contribution process works, please read our [contributing guidelines](https://contribute.freecodecamp.org/).

**Comment by Saikat-Mandal** [comment]
@jeremylt yeh , got it .

**Comment by DylanDevelops** [comment]
> The issue has not been marked as ready for contributions with the `help wanted` label. If you have questions about how our contribution process works, please read our [contributing guidelines](https://contribute.freecodecamp.org/).

@jeremylt I think if you would like to mark the issue with the `help wanted` tag, it's ready for that. Would you be willing to provide where the 404.html file we need to edit is or a better way of finding files? (I'd like to know this for the future!)

@ArdonitSaliji thinks it is a waste of time but I have to disagree as I think even if it's small, it's something to change and if someone wants to change it, they should not be told it's a waste of time lol.

**Comment by jeremylt** [comment]
I'm not part of the decision making process for marking contributions as ready to accept contributions. I agree this is a good idea but have no idea how someone would go about it.

**Comment by DylanDevelops** [comment]
@jeremylt Sounds good. Do you know if the 404 page is even something we can edit? Do you know any higher-up maintainers that would know the answer to this? Let me know!

**Comment by Saikat-Mandal** [comment]
@DylanDevelops yes it should be editable .

**Comment by devharsh007** [comment]
Assign it to me please. I wold like to work on it.

**Comment by Saikat-Mandal** [comment]
@devharsh007 please read the discussions before asking to assign an issue.

**Comment by DylanDevelops** [comment]
@devharsh007 Once we get this figured out, I believe @Saikat-Mandal has dibs on it.

**Comment by Nirajn2311** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

The file to be edited is here - https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/FourOhFour/index.tsx

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by DylanDevelops** [comment]
@Saikat-Mandal you're up if you want to contribute. just make sure to tag #49666 in your pull request! :)

**Comment by Saikat-Mandal** [comment]
> @Saikat-Mandal you're up if you want to contribute. just make sure to tag #49666 in your pull request! :)

Yeh got it.

**Comment by Saikat-Mandal** [comment]
Hey @DylanDevelops I am getting this error while trying to run in localhost. I don't want to mess up the code so i am asking here.
I haven't worked with typescript before. From the error i got to know the stripe module is missing from the path mentioned. Can you please tell me like where to install this module and how.

![error](https://user-images.githubusercontent.com/75900118/225353062-a29a3b5e-531d-446f-b494-6fd1a8244398.png)

**Comment by DylanDevelops** [comment]
Hmm, I'm not sure. What are you trying to do that's causing the console error?

**Comment by Saikat-Mandal** [comment]
@ShaunSHamilton OK i will see.

**Comment by Saikat-Mandal** [comment]
> Hmm, I'm not sure. What are you trying to do that's causing the console error?

let me just try with pnpm then i will update.
