### ISSUE TITLE
Bonfire: Make A Person 

### ISSUE THREAD

**Issue by mgeno216** [FreeCodeCamp/FreeCodeCamp#4967]
I think there may be an issue with the following test in the Make A Person Bonfire:

```
bob.getFullName() should return "Bob Curry" after bob.setLastName("Curry")
```

After working my solution for a bit, I gave up and checked the solution posted on the [gitter help section](https://gitter.im/camperbot/bonfire-make-a-person) and tried the code. The test also failed on the posted solution. I included the solution below for convenience.

```js
var Person = function(firstAndLast) {
  var fullName = firstAndLast;

  this.getFirstName = function() {
    return fullName.split(" ")[0];
  };

  this.getLastName = function() {
    return fullName.split(" ")[1];
  };

  this.getFullName = function() {
    return fullName;
  };

  this.setFirstName = function(name) {
    fullName = name + " " + fullName.split(" ")[1];
  };

  this.setLastName = function(name) {
    fullName = fullName.split(" ")[0] + " " + name;
  };

  this.setFullName = function(name) {
    fullName = name;
  };
};

var bob = new Person('Bob Ross');
bob.getFullName();
```

**Comment by SaintPeter** [comment]
Confirmed. 

May be related to #4958 

Seeing this in the console:
![image](https://cloud.githubusercontent.com/assets/553494/11552293/b89aaf40-9937-11e5-966f-af7d39f755d8.png)

**Comment by SaintPeter** [comment]
[Solution Link](http://www.freecodecamp.com/challenges/bonfire-make-a-person?solution=var%20Person%20%3D%20function(firstAndLast)%20%7B%0A%20%20var%20fullName%20%3D%20firstAndLast%3B%0A%0A%20%20this.getFirstName%20%3D%20function()%20%7B%0A%20%20%20%20return%20fullName.split(%22%20%22)%5B0%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.getLastName%20%3D%20function()%20%7B%0A%20%20%20%20return%20fullName.split(%22%20%22)%5B1%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.getFullName%20%3D%20function()%20%7B%0A%20%20%20%20return%20fullName%3B%0A%20%20%7D%3B%0A%0A%20%20this.setFirstName%20%3D%20function(name)%20%7B%0A%20%20%20%20fullName%20%3D%20name%20%2B%20%22%20%22%20%2B%20fullName.split(%22%20%22)%5B1%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.setLastName%20%3D%20function(name)%20%7B%0A%20%20%20%20fullName%20%3D%20fullName.split(%22%20%22)%5B0%5D%20%2B%20%22%20%22%20%2B%20name%3B%0A%20%20%7D%3B%0A%0A%20%20this.setFullName%20%3D%20function(name)%20%7B%0A%20%20%20%20fullName%20%3D%20name%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person(%27Bob%20Ross%27)%3B%0Abob.getFullName()%3B)

**Comment by mgeno216** [comment]
The solution link you posted didn't work for me. Same test not passing. For reference,
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.

**Comment by SaintPeter** [comment]
Sorry, I meant to say that it was a FAILING solution link.  This is a confirmed bug and is not fixed.  Feel free to move on to the next waypoint until we can get a fix for this.

**Comment by BerkeleyTrue** [comment]
There is a flaw in the test:

```js
"assert.strictEqual((function () { bob.setFirstName("Haskell"); return bob.getFullName(); })(), 'Haskell Ross', 'message: <code>bob.getFullName()</code> should return "Haskell Ross" after <code>bob.setFirstName("Haskell")</code>.');",

"assert.strictEqual((function () { bob.setLastName("Curry"); return bob.getFullName(); })(), 'Bob Curry', 'message: <code>bob.getFullName()</code> should return "Bob Curry" after <code>bob.setLastName("Curry")</code>.');", 
```

So the first test sets the first name to Haskell, and the second test sets the last name to Curry. The second test here should look for `Haskell Curry` but it expects `Bob Curry`. Simple typo. 

This one is up for grabs. Anyone up for a PR?

**Comment by gasperno** [comment]
After the modification, 
1) The test passes when I test with the solution provided in the .json file.
2) npm run test-challenges fails. 
I modified the assert to 'HaskellCurry' and test case passes. It's weird to me.

**Comment by QuantumNinja92** [comment]
i've the same problem, what should i do ?!

**Comment by AbdouSeck** [comment]
My code works with nodejs on sublime text 3 but when I submit it on FCC, it indicates that `bob.getFullName()` is not returning "Bob Curry" after `bob.setLastName("Curry")`:

```

var Person = function(firstAndLast) {

  var fullname = firstAndLast;

  this.getFullName = function() {
      return fullname;
    };

  this.getFirstName = function() {
    return fullname.split(" ")[0];
  };
  this.getLastName = function() {
    return fullname.split(" ")[1];
  };
  this.setFirstName = function(first) {
    fullname = first+" "+fullname.split(" ")[1];
  };
  this.setLastName = function(last) {
    fullname = fullname.split(" ")[0]+" "+last;
  };
  this.setFullName = function(name) {
    fullname = name;
  };
};

var bob = new Person('Bob Ross');
bob.setLastName("Curry");
console.log(bob.getFullName());
```
If this is not an actual bug, could someone please point out what's wrong with my code?

**Comment by SaintPeter** [comment]
This is an actual bug.  We're working on it.
