### ISSUE TITLE
sign in screen

### ISSUE THREAD

**Issue by Ankit1696** [freeCodeCamp/freeCodeCamp#49687]
### Describe the Issue

**sign in screen -** 

options - 1. continue with google 
             - 2. continue with github 
             - should contain  google and github log that will more attract a user to sign in.
             - if lets say I'm a user and I come to sign in on this page I see page having no logo I wouldn't like to sign in as compare to sign in with log.
             - in my point of view this screen looks little bit odd to me.
             - I have attached the screenshot along with this comment pls check it and improve it.

![Screenshot from 2023-03-12 12-52-18](https://user-images.githubusercontent.com/44586620/224530616-e5c43889-0e1b-4c47-af7d-c3b635dc28b8.png)

### Affected Page

https://auth.freecodecamp.org/login?state=hKFo2SB5TkJZNmJOMjh4Rlc5WTM5VjdnMktuVHBfWTAyaEptdaFupWxvZ2luo3RpZNkgQktiZmJ0WlJuakIwSXF0MnJBNzdXT0xiYkJOSTNUS0ijY2lk2SBhVUR2OWpWcVRmeEJSRTFsNjBOQTVBZjd5VENHRTRjeQ&client=aUDv9jVqTfxBRE1l60NA5Af7yTCGE4cy&protocol=oauth2&response_type=code&redirect_uri=https%3A%2F%2Fapi.freecodecamp.org%2Fauth%2Fauth0%2Fcallback&scope=openid%20profile%20email

### Steps to Reproduce

1. Go to '...' Main page, right upper corner you'll see sign in option.
2. Click on '...' Sign in
3. Now here you'll see continue with google and continue with github without logo.

### Expected behavior

These two sign in options must contain logo along with it as it'll help to increase no of users.

### Screenshots

![Screenshot from 2023-03-12 12-52-18](https://user-images.githubusercontent.com/44586620/224530818-795689b8-ffdd-4c67-8123-cea040b15d32.png)

### System

Laptop
Ubuntu
firefox

**Comment by Saikat-Mandal** [comment]
Hello  , please assign me me this issue. I want to work on it .

**Comment by Aadish1233** [comment]
Hello, can u please allow  me to make  changes

**Comment by Ankit1696** [comment]
Sure you can make changes all you need to do clone the project take a pull
request,  fix the issue. create a merge request and assign review process
to the admin.

**Comment by ShaunSHamilton** [comment]
An issue with the `help wanted` label is open for contribution. Please read the [contributors guide](https://contribute.freecodecamp.org)

**Comment by Aadish1233** [comment]
From where should I clone the project and add pull request

**Comment by Saikat-Mandal** [comment]
@Aadish1233 see this [contributers guide](https://contribute.freecodecamp.org/#/). You will get know how to clone.

**Comment by Aadish1233** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/120332757/224735273-44c4baf9-0a3c-41c6-8c36-f2df20d5b6d5.png)

**Comment by Aadish1233** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/120332757/224736194-f7806a2d-7c68-4f88-840b-abf92d0703c2.png)
I have done almost but I am confuse in pull

**Comment by devharsh007** [comment]
**Assign it to me** please ill want to work on it

**Comment by ahmadabdolsaheb** [comment]
Here is the repo: https://github.com/freeCodeCamp/auth0-templates
Assignment is not necessary, the first comprehensive pr is considered for review.

**Comment by Aadish1233** [comment]
@Saikat-Mandal  you need to install that  module
npm install @stripe/stripe-js
Hope that it helps u

**Comment by Saikat-Mandal** [comment]
@Aadish1233 yeh got it.  btw did set up your's in windows or linux / unix.

**Comment by Aadish1233** [comment]
@Saikat-Mandal  
windows

**Comment by ojeytonwilliams** [comment]
Hi. There's no need to install anything to create this PR. The repository you should be working with is https://github.com/freeCodeCamp/auth0-templates not https://github.com/freeCodeCamp/freeCodeCamp.

The template is just a single html file and that's what needs to be updated.

**Comment by Saikat-Mandal** [comment]
@Aadish1233 did you use npm or pnpm

**Comment by Aadish1233** [comment]
npm

**Comment by Vivek-04022001** [comment]
Hello, I'm wondering if it's possible for people who are not part of the project to contribute. If the answer is yes, could you please provide guidance on how to do so?

**Comment by raisedadead** [comment]
See: https://github.com/freeCodeCamp/auth0-templates/pull/35

**Comment by Abhi2359** [comment]
> Here is the repo: https://github.com/freeCodeCamp/auth0-templates Assignment is not necessary, the first comprehensive pr is considered for review. Please link your pr to this issue.

This is giving 404 Error

**Comment by raisedadead** [comment]
The repo has been made private and someone from @freeCodeCamp/staff will work on this PR when ready. Please explore other help-wanted issues.

**Comment by raisedadead** [comment]
The repo is public again, but we are taking a different approach to this with the New ULP screens from Auth0 instead of the classic screen.

The icons come by default now. We are testing this in staging right now and will ship it to production in the coming weeks.

Here is a sample of who it will look

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1884376/236629242-5bb4075f-309d-48d0-8f6b-281e22589cc9.png">
