### ISSUE TITLE
Comment Tests Breaking

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#49698]
We currently have tests that check for comments in seed code, and assert that the comment exists in the English dictionary for translation.

This works *fine*, until we get PRs like #49684, #49686, and #49688 - updating an *existing* English comment will break the tests because the i18n challenge file has the old comment text.

I see a couple of approaches to fixing this:

- Instruct contributors to sync the changes to the i18n challenges (not ideal, tbh).
- Update the test to check if the English challenge file has been modified?
- Change the test to not throw a failure, but instead trigger a warning? AFAIK we're just validating that the comment can be translated, do we need that to be a blocker?

**Comment by Sboonny** [comment]
Can we have a workflow similar to the files in `/locales`? here is [`translation.json`](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/translations.json)

**Comment by raisedadead** [comment]
Let's update the localized test workflow to leave a comment (see later) on the PRs when it fails, and there is also a change to English files. This is the likely scenario we want to address.

The comment could be: 

> Hi,
>
> It Looks like the localization tests have failed. This is normal when there are significant curriculum changes in the English version.
>
> Please check with the dev-team if this means a Crowdin sync is required to address the scenario. They will confirm and take over helping you through the PR.
> 
> Thanks for your understanding and contribution.

**Comment by Sboonny** [comment]
We are happy with the current workflow
