### ISSUE TITLE
Waypoint: Sift through Text with Regular Expressions

### ISSUE THREAD

**Issue by lawrenceet** [FreeCodeCamp/FreeCodeCamp#4969]
Challenge [Waypoint: Sift through Text with Regular Expressions](http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions?solution=0uiom%2Cunh*-i.nn%0A%5B%5Dh%270oo09o0%2089uoj%20op9%0Abb%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tllkiyh%20uyuuu64o0oipvar%20test%20%3D%20(function()%20%7B9ol-p%3B.%20%3B%0A-%3Dpb~!%26*%7B%7D%20%20var%20testString%20%3D%20%22Ada%20Lovelace%20and%20Charles%20Babbage%20designed%20the%20first%20computer%20and%20the%20software%20that%20would%20have%20run%20on%20it.%22%3B%0A%20%20var%20expressionToGetSoftware%20%3D%20%2Fsoftware%2Fgi%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20var%20expression%20%3D%20%2Fand%2Fgi%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%20%20return%20testString.match(expression).length%3B%0A%7D)()%3B(function()%7Breturn%20test%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
0uiom,unh*-i.nn
[]h'0oo09o0 89uoj op9
bb                    tllkiyh uyuuu64o0oipvar test = (function() {9ol-p;. ;
-=pb~!&*{}  var testString = "Ada Lovelace and Charles Babbage designed the first computer and the software that would have run on it.";
  var expressionToGetSoftware = /software/gi;

  // Only change code below this line.

  var expression = /and/gi;

  // Only change code above this line.

  return testString.match(expression).length;
})();(function(){return test;})();

```

**Comment by lawrenceet** [comment]
Getting errors on first two lines of code. Not sure how to fix it.

**Comment by SaintPeter** [comment]
I don't know what the deal is, but that challenge seed is garbled.  It has very odd characters that should not be there.  

Try hitting "reset" on the code and making the change again.

**Comment by lawrenceet** [comment]
I just hit reset and it corrected itself. Thank you for your help!
