### ISSUE TITLE
Create Map for Themes

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49697]
While working on adding the system theme in #48757, there are multiple instances which needs updating the values affected my the theme.

Here are the out of norm instances that are affected by the themes: 

- tones 

https://github.com/freeCodeCamp/freeCodeCamp/blob/0811e8ca463735c8b0782f41d8b3ecac4b8160da/client/src/utils/tone/index.ts#LL9-L10C70

- editor

https://github.com/freeCodeCamp/freeCodeCamp/blob/0811e8ca463735c8b0782f41d8b3ecac4b8160da/client/src/templates/Challenges/classic/editor.tsx#L1217

- walletButtons

https://github.com/freeCodeCamp/freeCodeCamp/blob/0811e8ca463735c8b0782f41d8b3ecac4b8160da/client/src/components/Donation/walletsButton.tsx#L104

- stripe-card-form

https://github.com/freeCodeCamp/freeCodeCamp/blob/0811e8ca463735c8b0782f41d8b3ecac4b8160da/client/src/components/Donation/stripe-card-form.tsx#L87

- paypal-button

https://github.com/freeCodeCamp/freeCodeCamp/blob/0811e8ca463735c8b0782f41d8b3ecac4b8160da/client/src/components/Donation/paypal-button.tsx#L97

Because of these files, whenever someone tries to add new theme, they have to account for all of them.

To sort this we can change the `Themes` enum, into a Map, so it can hold these values inside of it, and we can use redux to know what type of theme we have, then use it to display the properties

https://github.com/freeCodeCamp/freeCodeCamp/blob/0811e8ca463735c8b0782f41d8b3ecac4b8160da/client/src/components/settings/theme.tsx#L7-L10

example:

```ts
const themes= new Map<string, Record<keyType, TypeOfValue>>([
      [
 'default', { paypal-button: someValue1, stripe-card-form: someValue2, walletButtons: someValue3, editor: someValue4, tones: 
 someValue5}
 ],
]);
    
    Themes.get(themeFromRedux)?.property;
```

**Comment by ShaunSHamilton** [comment]
I would suggest we not use a Map. Using a Map in this way would cause a connection of completely different types, and would bring them out of their respective scopes.

This would be difficult to maintain from a TypeScript point of view, as well as a logical point of view.

**Comment by Sboonny** [comment]
> Using a Map in this way would cause a connection of completely different types, and would bring them out of their respective scopes.

I disagree about this part, these types aren't really different, as all of them are string and all of them are in the scope of the Theme.

> This would be difficult to maintain from a TypeScript point of view, as well as a logical point of view.

I have bad news for you, it's already difficult to maintain, it's hard to be aware of these files and their connection to the Theme, so whenever someone tries to add changes to themes, or create new one, they won't be aware about how the editor is using logic to assign its theme https://github.com/freeCodeCamp/freeCodeCamp/issues/48936

The other parts are fine currently, because it requires the camper to log in to interact with the music or the donation, but what if I add a system theme, and people keep talking about JavaScript logic and ignore the huge area that adding new theme affect.

Because maintainers don't know how big the Theme's scope is, having a map that have properties which indicate where the Theme is changing is better than the current system.

**Comment by Sboonny** [comment]
Do you have another suggestion that isn't a Map?

**Comment by ShaunSHamilton** [comment]
>Do you have another suggestion that isn't a Map?

This is exactly what an enum is for - multiple variants. So, an enum.

**Comment by Sboonny** [comment]
because I was going to type that the current enum isn't with multiple variants, isn't a good option to hold the data for the Themes, and I feel like this is going on circle.

Can I just assign you, and you create an enum that will make it possible to change all of the 5 places that the theme changes? without the need to update them in every PR that create a new theme?

**Comment by Sboonny** [comment]
Closed because the PRs, that needs this are closed and the need for it isn't there anymore.

**Comment by Sboonny** [comment]
I am closing this, because creating the map, is creating an abstraction, as shown in the PR linked to the issue.

I will post more context of how I thought map was good idea in the PR, and why it can't be added to the current codebase.
