### ISSUE TITLE
Bonfire: Sum All Primes failing to pass sumPrimes(977)

### ISSUE THREAD

**Issue by Puine** [FreeCodeCamp/FreeCodeCamp#4976]
Hi, I have problem with the bonfire : Sum All Primes . Here is my code :
```javascript
function sumPrimes(num) {
  var arr = [];
  var sum = 0;
  for(var i=2; i<=num; i++){
    arr = [];
    for(var j=1; j<i+1; j++){
      if(i%j===0){
        arr.push(j);
      }
    }
    if(arr[1] === i ){
      sum = sum+i;
    }
  }
  return sum;
}

sumPrimes(977);

```
It works fine with sumPrimes(10), but I have this answer for 977 :  " Error : Potential Infinite loop at line 4 " . So I cant pass the test ... any idea ? Is this a bad thing to have a for loop inside another ?

**Comment by BerkeleyTrue** [comment]
@Puine Looks like you code is passing for me. What browser are you using?

**Comment by bugron** [comment]
Can reproduce on FF and on Chrome. In FF throws error on starting at `sumPrimes(300)` and in Chrome starting at `sumPrimes(726)`. Looks like when script execution time exceeds some value loopProtect throws an error.

**Comment by BerkeleyTrue** [comment]
We can increase the timeout. At the moment it is at 100ms

**Comment by argvil19** [comment]
+1 Same issue.  My code:

```
function sumPrimes(num) {
  var curr = 0;
  var total = 0;
  var nums = [];
  while (curr <= num) {
    for (var i=0;i<=curr;i++) {
      if (curr % i === 0) {
        nums.push(i);
      }
    }
    if (nums.length === 2) {
      total += curr;
    }
    nums = [];
    curr++;
  }
  return total;
}
```

**Comment by BerkeleyTrue** [comment]
@argvil19 @Puine You can add the following line `// noprotect` to your code to disable infinite loop protection. Be aware that if you're code does loop infinitely it will crash your browser and make it extremely difficult to close.

Happy Coding!

**Comment by Puine** [comment]
Thanks !

**Comment by BerkeleyTrue** [comment]
@Puine We have increased the timeout so you may not need it now. Happy Coding!

**Comment by DannyCoder** [comment]
@BerkeleyTrue I just resolved the same issue by adding <code>//noprotect</code> to my code. You may want to increase the timeout again, or post the <code>//noprotect</code> flag in the challenge wall as a workaround. I experienced the same problem on an another challenge, and was banging my head against the wall trying to fix a valid solution :)

**Comment by dinghino** [comment]
Same here. been stuck for the last 20 minutes trying to understand why it didn't work. I think you should really add the tip for the `//noprotect` and/or increase the timeout.

This is the code I used, that got stuck at the `977` test.
```javascript

function sumPrimes(num) {
  var primes = [2],
      isPrime; // boolean
  
  for (var i=3; i <= num; i+=2) {      // skip all even
    isPrime = true;
    for (var n in primes) {            // check known primes
      
      if(i % primes[n] === 0) {        // we found another
        isPrime = false;
        break;                         // stop searching
      }
    }
 
    if(isPrime) primes.push(i);
  }
  num = primes.reduce(function(a, b) {return a + b; });

  // sum all the values of the primes array and return
  return num;
}
```

Managed to complete with the `//noprotect` flag and then I did some testing;
* skipping all even values it took 0.016s to complete
* incrementing `i` with `++` it goes up to about 0.05s

These values should be inside your safe limits, but still it failed at first without the flag. After completing the challenge and while doing the time testing i removed the `//noprotect` and it passes everything without any issue.

just for final note, the machine i'm using is a surface pro 3 i7, windows 10 on chrome 54.0.2840.99m

**Comment by akberj** [comment]
Why not use Math.sqrt() to make it simpler?
----
function sumPrimes(num) {
  var test=0;
  for(var x=2; x<=num;x++){
  if(add())
   test+=x;
 }
   //---simple true or false function for primes---
  function add(){
 for(var i = 2, s = Math.sqrt(x); i <= s; i++)  
  if(x % i ===0) 
 return false;
 return x!==1;  
  }
 return test;
}
 sumPrimes(977);

**Comment by texas2010** [comment]
@akberj 
Please do not post your solution on here. This GitHub Issues are for reporting bugs on the website only.

Happy Coding!
