### ISSUE TITLE
Won't Accept Correct Solution on Step 51 on Safari Browsers

### ISSUE THREAD

**Issue by DylanDevelops** [freeCodeCamp/freeCodeCamp#49767]
### Describe the Issue

On safari on a MacBook, the correct solution refuses to be accepted. The exact same code is, however, accepted on the chrome browser.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-51

### Your code

```html
<div class="daily-value small-text">
      <p class="bold right no-divider">% Daily Value *</p>
      <div class="divider"></div>
      <p><span><span class="bold">Total Fat</span> 8g</span> <span class="bold">10%</span></p>
      <p class="indent no-divider">Saturated Fat 1g <span class="bold">5%</span></p>
      <div class="divider"></div>
      <p class="indent no-divider"><span><i>Trans</i> Fat 0g</span></p>
</div> 
```

### Expected behavior

It should accept this as the same code was accepted when I tested it on the chrome browser.

### Screenshots

<img width="1512" alt="Screenshot 2023-03-19 at 8 26 28 PM" src="https://user-images.githubusercontent.com/48571264/226232614-46d2522e-2bbd-4aaa-9961-62aadf6010fd.png">

<img width="1512" alt="Screenshot 2023-03-19 at 8 26 09 PM" src="https://user-images.githubusercontent.com/48571264/226232572-2545dedc-b051-4fbb-abc7-b3054f5ccfc9.png">

### System

- Device: Macbook Pro
- OS: MacOS
- Browser: Safari
- Version: 16.1

**Comment by scissorsneedfoodtoo** [comment]
Hi @DylanDevelops, thanks for taking the time open this issue and for all of these helpful details.

I just tried submitting your solution on both Chrome and Safari (specifically `<p class="indent no-divider"><span><i>Trans</i> Fat 0g</span></p>`) and am able to pass the solution in both browsers.

There could be a few things going on here. First, it looks like you might be running a slightly out-of-date version of Safari. I tested the challenge in Safari 16.3, which seems to be the latest version. You may need to update Safari to version 16.3 for the tests for this step to work.

Next, it looks like you're running some extensions on Safari. I'm not sure what extensions those are, but please try disabling them, refreshing the page, and submitting your code again. It's possible that one of the extensions is affecting the tests in Safari.

Could you try those things and let us know if you're still having issues with this step?

**Comment by Sboonny** [comment]
Hi @DylanDevelops, we are closing the issue because we couldn't duplicate it, if the issue exists after following the instruction provided in this comment https://github.com/freeCodeCamp/freeCodeCamp/issues/49767#issuecomment-1480726042, please reopen the issue, with more context. 

Thank you for opening the issue, and happy coding.

**Comment by cr5459** [comment]
I also had this issue for whatever reason.
