### ISSUE TITLE
Editor cursor position bugged in Chromium after reload

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#49771]
### Describe the Issue

For me, both in Chrome and Edge (without any extensions) the cursor position is off by some characters (a tab?). It seems to happen after reloading the page (hard refresh) or even directly navigating to a challenge URL.

1. Go to `https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1` and complete the step.

2. Advance to the next challenge and check the cursor position, it should be fine.

3. Reload the page (hard refresh) and check the cursor position again, it is now off.

![cursor-position](https://user-images.githubusercontent.com/28780271/226340636-3ff3fd73-5234-4bde-b755-d0f370d91427.gif)

Doesn't seem to happen in Firefox or when I tried it in the JS curriculum.

Is this reproducible for anyone else?

---

The only PR I found briefly looking at the commits for the editor is https://github.com/freeCodeCamp/freeCodeCamp/pull/49477

Might be causing this?

Edit: I tried reverting the code from the PR and it didn't seem to help so I'm guessing that isn't it. Honestly not sure what is causing it but it seems to have happened between the Feb 28 build and the later production build.

Edit 2: For anyone reading this looking for a fix.

- A normal (soft) page refresh should fix it.
- Firefox seems unaffected.

### Affected Page

https://www.freecodecamp.org/learn

### Your code

```

```

### Expected behavior

The cursor position should not be borked after a page reload.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum:
https://forum.freecodecamp.org/t/misaligned-cursor/599520
https://forum.freecodecamp.org/t/my-cursor-keeps-going-to-odd-spots-when-i-try-to-code/600071

**Comment by Sboonny** [comment]
couldn't replicate on edge version 111.0.1661.44

on chrome version 111.0.5563.65, I did have the issue tho, with some area isn't formatted correctly 

This picture from step 4 on cafe menu

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-4

![image](https://user-images.githubusercontent.com/88248797/226348028-3d8162c7-58fa-4adc-a4e9-6764ec3e24e5.png)

**Comment by lasjorg** [comment]
@Sboonny Make sure it is a hard refresh.

I didn't think it would matter but it seems like it does. I will update the repro steps.

**Comment by lasjorg** [comment]
Forum report

https://forum.freecodecamp.org/t/misaligned-cursor/599520

**Comment by Sboonny** [comment]
Yeab, still show sometime in chrome 👍, couldn't replicate on edge

**Comment by lasjorg** [comment]
Added another forum report on this bug.

I'm actually surprised we have not yet seen more reports of this bug. But I'm guessing it is because it doesn't seem to trigger when just going through the curriculum using the normal ways of advancing between challenge steps.

But man when this bug hits you it makes helping with challenges on the forum an absolute nightmare. I pretty much have to use Firefox (which I don't mind).

**Comment by bbsmooth** [comment]
Wow, this is a weird bug. Just confirming as well that the only time I can trigger this is by doing a hard refresh (Shift + Reload button) using either Chrome or Edge on Win11. Firefox does not seem to be affected on Win11. None of these browsers seem to be affected on Linux. A soft refresh fixes the problem.

**Comment by scissorsneedfoodtoo** [comment]
Could you give us more details about your setup, @teddybeard78? What browser were you using when you experienced this issue, and what version was it? Also, which OS are you running?

**Comment by teddybeard78** [comment]
Chrome, latest version, Windows 10
