### ISSUE TITLE
Create a test to make sure that editor theme is in sync with the app theme

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49784]
The test should account for this issue #48936, TL;DR of the issue, the editor had different theme than the one in the user preferred, and the test should make sure that the themes are always the same

<img width="1400" alt="Screen Shot 2023-01-03 at 3 12 59 PM" src="https://user-images.githubusercontent.com/4591597/210774718-a54c08cc-1915-4379-aa5e-8fe554f1a8ff.png">

The test should account for two different state of the user, and 3 different states of the theme:

## while the user is logged out:

- visit /learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-23
- set your preferred-scheme to light, themes should be in sync
- set your preferred-scheme to dark, themes should be in sync

Note to set preferred-scheme from devtools press <kbd>Ctrl + P</kbd>, then press <kbd>></kbd> and select it.

## while the user is logged in

- visit /learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-23
- set your theme to default, themes should be in sync
- set your theme to night, themes should be in sync

### Additional context

Thanks to Tom link, you can find out how to test colors through Cypress through this article https://blog.devgenius.io/how-to-make-a-cypress-test-for-prefers-color-scheme-dark-42337138f727

Note: although I mentioned Cypress you are free to use any tools in the E2E folder

Here is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/classic/editor.tsx

Maybe I missed something, if you think there is more, please add it. 

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by hectoraldairah** [comment]
How the Monaco editor should look with  `preferred-scheme ` with dark value?
I don't see any difference

**Comment by Fishbite** [comment]
Ctrl + P is a windows command to print the current document. Choose another key combination to avoid problems.

**Comment by ojeytonwilliams** [comment]
It's chrome devtools that uses that shortcut.

**Comment by Fishbite** [comment]
Correct, not Firefox, MS Edge.... If the user is not specifically focused on the chrome devtools panel on a Windows m/c,  it will pop-up the print dialogue .

**Comment by ojeytonwilliams** [comment]
Right, but the context was setting the preferred theme inside devtools.

**Comment by Fishbite** [comment]
Sure, and it is just a note after all, but chrome is not specifically mentioned and ctrl+p currently displays an open file dialogue... in chrome. I'm just think it would probably be wiser to pick another key-combo.

**Comment by Sboonny** [comment]
Please, let's not discuss something isn't progressing the issue forward, so far there hasn't been a discussion on how the test can be implement.

If you are looking for ways to access the preferred-color-scheme in your browser, there are multiple guides online.


there is [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help

**Comment by a2937** [comment]
I can't run onBeforeLoad before the window is ready because there will be no window object yet. I've tried using onLoad but the app isn't entering dark mode.

**Comment by a2937** [comment]
I'm managed to make some progress. I finally have the dark theme show up. It appears that window.matchMedia was used more heavily than I thought. Now I just need to find the right class names for the editor palette and we should be golden.

**Comment by Sboonny** [comment]
That's the tricky part, there is no className for the editor, it uses a object to set its style, we are only adding values through defineTheme

https://github.com/freeCodeCamp/freeCodeCamp/blob/7f21c5b4aeebcb8ffb4444e21fc3b1f5cd8d1b52/client/src/templates/Challenges/classic/editor.tsx#L195-L230

Here is the original file in monaco-editor https://github.com/microsoft/vscode/blob/93028e44ea7752bd53e2471051acbe6362e157e9/src/vs/editor/standalone/common/themes.ts

**Comment by a2937** [comment]
Hang on. I'm still a little confused about something. I think I'm doing something wrong here or there's an error that I didn't see in the console. The editor itself isn't turning to dark-theme despite everything else is dark. Additionally while signed in on the local website instance I have running, it also appears fine.

**Comment by NoelCov** [comment]
@a2937 Hey there, I was looking into this and was wondering if you're still working on it? I want to pick something up but not if someone is already working on it. Thanks! :)
