### ISSUE TITLE
Remove -webkit-clip-path property from sr-only class

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#49792]
### Describe the Issue

The Building a Balance Sheet course uses the `sr-only` class (beginning on [Step 31](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-31)) to visually hide text for accessibility. This class is using the fallback `-webkit-clip-path` property which is not needed any more as all browsers have supported `clip-path` for quite a while now. Furthermore, all modern recommended patterns for visually hiding text do not include it.

[The anatomy of visually-hidden](https://www.tpgi.com/the-anatomy-of-visually-hidden/)
[WebAIM: Invisible Content Just for Screen Reader Users](https://webaim.org/techniques/css/invisiblecontent/)
[CSS-Tricks: Inclusively Hidden](https://css-tricks.com/inclusively-hidden/)

I think it would be a good idea if we removed it from the course as campers are never going to use `-webkit-clip-path` and do not need to learn it here. It will also allow us to remove a regex test for step 31 (see PR #49546). 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-31

### Your code

N/A

### Expected behavior

Course does not use `-webkit-clip-path` in `sr-only` class.

### System

N/A

**Comment by ShaunSHamilton** [comment]
I am happy for this to be removed, for the reasons you have outlined.

I did not create this project/step, but did create one using `.sr-only`, and also used the `-webkit-clip-path` property, because it **was** in Bootstrap 4's  CSS at the time of writing: 

```css
.sr-only{position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;-webkit-clip-path:inset(50%);clip-path:inset(50%);border:0}
```

I now see it has been removed, as of `4.1.3`.

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

**To Close Issue:**

- Remove mention/instruction of `-webkit-clip-path`.
- Remove test looking for the property
- Remove the property from all following lessons/steps

**Affected Files**

- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/61fdac1e31692f9a9ad97295.md
- All files thereafter.

**Notes:**

- Be sure to read the contributors docs
- Only make changes to the **English** files
