### ISSUE TITLE
install node-gyp  command "node-gyp configure" not found binding.gyp

### ISSUE THREAD

**Issue by godsgods** [freeCodeCamp/freeCodeCamp#49797]
### Describe the Issue

execute command ‘node-gyp configure’ tip 'binding.gyp not found (cwd: D:\nodejs\node_global) while trying to load 
gyp: binding.gyp not found (cwd: D:\nodejs\node_global) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\nodejs\node_global\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_global\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\nodejs\node_global
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

### Affected Page

no

### Your code

```
gyp: binding.gyp not found (cwd: D:\nodejs\node_global) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\nodejs\node_global\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_global\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\nodejs\node_global
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
```

### Expected behavior

1

### System

node version:18.15.0
npm version:9.6.2
node-gyp version:9.3.1
python version: 3.6
windows version: win11

**Comment by scissorsneedfoodtoo** [comment]
Hi @godsgods, thanks for your patience and for all the details you provided.

Just to confirm, did you run into this error while setting up freeCodeCamp locally?

Also, you mentioned that you're using Windows 11. Are you setting up fCC locally with WSL2, or are you using a native Windows shell like PowerShell, or another tool like Git Bash?

**Comment by raisedadead** [comment]
To add, we are not supporting development natively on Windows anymore. That is if you have a Windows machine – you should use WSL2 for a Linux like environment right within Windows.

If you are stuck consider checking StackOverflow or similar sites because the errors are not directly linked to the fCC codebase.

Alternatively you can try our one-click GitPod based setup

**Comment by godsgods** [comment]
i'm use powershell, sure, try use gitpod, thanks
