### ISSUE TITLE
The ES6 challenges of JavaScript Algorithms and Data Structures missing the promise finally challenge

### ISSUE THREAD

**Issue by xgqfrms** [freeCodeCamp/freeCodeCamp#49810]
### Describe the Issue

# The `ES6` challenges of JavaScript Algorithms and Data Structures missing the promise `finally` challenge

## candidate file name

`complete-a-promise-with-finally`

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/complete-a-promise-with-finally

### Your code

```js
const makeServerRequest = new Promise((resolve, reject) => {
  // responseFromServer is set to false to represent an unsuccessful response from a server
  let responseFromServer = false;
    
  if(responseFromServer) {
    resolve("We got the data");
  } else {  
    reject("Data not received");
  }
});

makeServerRequest.then(result => {
  console.log(result);
});

makeServerRequest.catch(error => {
  console.log(error);
});

makeServerRequest.finally(() => {
  console.log("finally");
});

```

### Expected behavior

```js

const makeServerRequest = new Promise((resolve, reject) => {
  // responseFromServer is set to false to represent an unsuccessful response from a server
  let responseFromServer = false;
    
  if(responseFromServer) {
    resolve("We got the data");
  } else {  
    reject("Data not received");
  }
});

makeServerRequest.then(result => {
  console.log(result);
});

makeServerRequest.catch(error => {
  console.log(error);
});

// Only change code below this line

```

### System

- Device: Laptop
- OS: macOS 13.1 (22C65)
- Browser: Chrome
- Version: Version 111.0.5563.64 (Official Build) (x86_64)

### Additional context

> PR

https://github.com/freeCodeCamp/freeCodeCamp/pull/49811

**Comment by raisedadead** [comment]
Have you gotten a chance to discuss this on the forum?

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/pull/49811#issuecomment-1483979642, in future please consider a discussion with others on the forum.

Thanks and happy contributing.
