### ISSUE TITLE
Make spacer component smarter by accepting children

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49828]
We have instances which `Spacer` is used to provide spacing for both side of the component to wrap it up in specific space

Example: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/49ab3866d77a0c4704a2070dcfe9e610ea5e3d6d/client/src/components/profile/profile.tsx#L125-L135

We can make the Spacer component smarter, and allow it to accept children, so the code be like.

```ts
<Spacer size='medium' > 
 {isLocked ? renderMessage(isSessionUser, username, t) : null} 
 {!isLocked || isSessionUser ? renderProfile(user) : null} 
 {isSessionUser ? null : ( 
   <Row className='text-center'> 
     <Link to={`/user/${username}/report-user`}> 
       {t('buttons.flag-user')} 
     </Link> 
   </Row> 
 )} 
 </Spacer>
```

But in doing so, we need to:

- change the current values and how the padding is calculated, the old layout shouldn't change with the new spacers.
- change which padding has the new value, I think paddingBlock, which is paddingTop and paddingBottom, is the new padding property 🤔.

---

I am requesting this because this will make live simpler, and we have to worry about less `div` elements while controling the layout, and if we have specific cases, we can still use `<Spacer />`

**Comment by Sboonny** [comment]
There is an abstraction with `size`, we need address, it's better if we can specify the direction of the padding. but this can be sorted in another issue, for now to solve this issue please allow `<Spacer />` to have children prop inside of it, but the current styles of the curriculum shouldn't change.

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by Vansh-Baghel** [comment]
@Sboonny Hey I am trying to figure out what is the old layout and how must new layout be in terms of padding. Could you help me know one?
Till now I added the children prop at /client/src/components/helpers/spacer.tsx, and modified /client/src/components/profile/profile.tsx which works fine IMO (Not sure how to crosscheck on localhost, atleast it doesn't give any error).

**Comment by Sboonny** [comment]
@Vansh-Baghel, it was difficult to understand what you mean without looking at an example of code, so to answer you:

- yes the direction will be in a second issue, but the spacing and values should still be in this issue so the pages won't look different
- Of course, please raise a PR after reading the guideline, nicely done 👍.
- The Spacer shouldn't affect the children inside of it, think of it as creating a container with margin-block to space the children inside of it from other area

**Comment by Vansh-Baghel** [comment]
@Sboonny I guess we could close this issue 🤔👀

**Comment by Sboonny** [comment]
will be closed when the height is removed in the other PR 👍
