### ISSUE TITLE
Multifile Editor hints don't always match users code when running tests too quickly

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#49836]
### Describe the Issue

If I enter a bad solution in the multifile editor and run the tests, the hint doesn't always match the hint my code should produce - seemingly when I run the tests too quickly in succession.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1

### Steps to Reproduce

On step 1 of the cat photo app, the code `<h1>CatPhotoApps</h1>` should produce the hint: ``Your `h1` element's text should be `CatPhotoApp`...``

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1
2. It should have the default code in the editor: `<h1>Hello World</h1>`
3. Run the tests
4. The hint should read ``The text `CatPhotoApp` should be present in the code. You may want to check your spelling.``
5. Quickly change the code to `<h1>CatPhotoApps</h1>` and run the tests again
6. The hint may still show the previous hint
7. If it doesn't, quickly use undo to change the code back to the default, and the hotkeys to run the tests
8. Hint may still show text for when using code `<h1>CatPhotoApps</h1>`

### Expected behavior

It to show the correct hint.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Jiajun-Jiao** [comment]
I'm currently using Chrome on MacOS 13.1. I've tried the change as quickly as I could, but cannot reproduce the error. I've attached the screen recording below:

https://user-images.githubusercontent.com/97413019/227628189-e59aee71-a234-4d45-8a9d-37e0a0251fb0.mov

**Comment by moT01** [comment]
This is difficult to reproduce, I am closing it for now. It is unlikely a camper will run into this problem.
