### ISSUE TITLE
Step 96-New Web design Certificate

### ISSUE THREAD

**Issue by mrfantasticllc** [freeCodeCamp/freeCodeCamp#49841]
### Describe the Issue

Step 96Passed
Give wave four waypoints starting at 10%, and incrementing by 10%.

1.The tests allow duplicate waypoints for the four required percentages.
2.The tests allow other waypoint values not specified in the instructions.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-96

### Your code

```

```
@keyframes wave {
  10% {  

  }
  20% {

  }
  10% { 

  }
  30% {

  }
  10% {

  }
  40% {

  }
  10% {

  }
  50% {
    
  }
}

### Expected behavior

When I read the instructions, I thought it said do four wave points starting at ten and add ten to each one. Once I failed. I calculated it to do each ten and add ten percent to each one after. I guess even though I did not read the instructions the way they were adviced I found a bug. I passed and when I went to next step it automatically fixed my mistake and removed the 50% also.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

The instructions from what I read confused me to do four tens and add ten percent under each one. I was able to find the bug due to this so yay I am pleased to help. By doing a total of four I was able to add 50 percent, on the last one too. My suggestion to fix the sentence on instructions, would be to not say make four waves starting at ten. Instead maybe you could say make four waves start at 10 percent and then for the rest add ten percent to each one for a total of four waves only.

**Comment by Sboonny** [comment]
We should add new test with hint as following

> You should have 4 waypoints in your keyframe.


Here is the test

```ts
assert([...[...new __helpers.CSSHelp(document).getCSSRules('keyframes')].find(rule => rule?.name === 'wave')?.cssRules].length
```


----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by ArslanYM** [comment]
Can I work on this ?

**Comment by Sboonny** [comment]
go for it

**Comment by ArslanYM** [comment]
> We should add new test with hint as following
> 
> > You should have 4 waypoints in your keyframe.
> 
> Here is the test
> 
> ```ts
> assert([...[...new __helpers.CSSHelp(document).getCSSRules('keyframes')].find(rule => rule?.name === 'wave')?.cssRules].length
> ```
> 
> If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

This test should be at the last of the other tests right? I mean after completing the other tests. Checking for 4 wavepoints should be the last one right?

**Comment by Aatyagi** [comment]
@Sboonny , I am a first-timer so I do not really know where to make these changes . Also do I need to add the logic using jest or can I just add itthe call-back function of the event listener of that button .

**Comment by ArslanYM** [comment]
@Sboonny I have made the changes (addition of code which is mentioned in the above screenshot) in this file : 
![fixx](https://user-images.githubusercontent.com/104521101/229005182-5ca87fcb-c331-43a1-9f81-8b8eda733a82.png)


This should work now right?

**Comment by Aatyagi** [comment]
@ArslanYM yeah you can work since obviously you got it assigned  to yourself first . I am just here to learn . I just want to get familiar with the workflow that's it .
