### ISSUE TITLE
Found a bug when linking to step from forum help requestion on link to the step under their code 

### ISSUE THREAD

**Issue by mrfantasticllc** [freeCodeCamp/freeCodeCamp#49868]
### Describe the Issue

Hello. I found a bug when you click the step link from freecodecamp to view the step for the person needing help. When I click the link from freecodecamp to view the step, It has a problem with my keyboard and mouse to click correct area. When I try on my own profile to do the step it is fine. It will not allow me to stay in the area I shoudl to type or space out.

### Affected Page

https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-17/600876

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

It did not allow me to do as usual at all. I could not test it out due to this bug problem

### Screenshots

![Web capture_26-3-2023_20213_forum freecodecamp org](https://user-images.githubusercontent.com/98601747/227813258-58005bcb-2675-45cd-8a4b-c5f52b1a0d9a.jpeg)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Sboonny** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #49771, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
