### ISSUE TITLE
Typo in Post Data with the JavaScript XMLHttpRequest Method module

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#49875]
### Describe the Issue

In [Post Data with the JavaScript XMLHttpRequest Method](https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method) module, currently, the instruction says:

You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and uses the `true` Boolean to make it asynchronous. The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header. Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. The document's HTML can be updated. Finally, the `send` method sends the request with the `body` value, which the `userName` key was given by the user in the `input` field.

Instead of this, the instruction should be as follows:

You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and uses the `true` Boolean to make it asynchronous. The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header. Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.

**NOTE:** The last two sentence of the paragraph should be - _**The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.**_

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method.md

### Expected behavior

In [Post Data with the JavaScript XMLHttpRequest Method](https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method) module, the instruction should be as follows:

You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and uses the `true` Boolean to make it asynchronous. The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header. Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.

**NOTE:** The last two sentence of the paragraph should be - _**The document's HTML can be updated now. Finally, the `send` method sends the request with the `body` value, in which the value of the `userName` key was given by the user via the `input` field.**_

### Screenshots

![image](https://user-images.githubusercontent.com/36872756/228220117-89f80721-6a36-49fd-9bad-f18d381a5d4a.png)

### System

- Device: MacBook Pro
- OS: MacOS 13.3
- Browser: Chrome

**Comment by ShaunSHamilton** [comment]
Hello there,

As this is the old section of the curriculum, I am happy for it to get minor changes.

That being said, I think it would be better to clear up the entire paragraph:

> You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and uses the `true` Boolean to make it asynchronous. The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header. Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. The document's HTML can be updated. Finally, the `send` method sends the request with the `body` value, which the `userName` key was given by the user in the `input` field.

To:

> You've seen several of these methods before. Here the `open` method initializes the request as a `POST` to the given URL of the external resource, and passes `true` as the third parameter - indicating to perform the operation asynchronously.
>
> The `setRequestHeader` method sets the value of an HTTP request header, which contains information about the sender and the request. It must be called after the `open` method, but before the `send` method. The two parameters are the name of the header and the value to set as the body of that header.
>
> Next, the `onreadystatechange` event listener handles a change in the state of the request. A `readyState` of `4` means the operation is complete, and a `status` of `201` means it was a successful request. Therefore, the document's HTML can be updated.
>
> Finally, the `send` method sends the request with the `body` value. The `body` consists of a `userName` and a `suffix` key.
