### ISSUE TITLE
not taking the answer

### ISSUE THREAD

**Issue by zhangtreefish** [FreeCodeCamp/FreeCodeCamp#4987]
I attempted to italicize the content by :
$("#target4").wrapInner("<i></i>");
 and got no response.
Here is the doc for wrapInner: http://api.jquery.com/wrapInner/

**Comment by ltegman** [comment]
Your call to wrapInner doesn't contain any element to wrap it in. If the string parameter contained an `i` tag this will pass.

In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for code questions.

Thanks and happy coding!

**Comment by zhangtreefish** [comment]
It is weird the <i></i> disappeared on this post for me. When I click the edit pen they show up. 

You are right, the site is working, my real problem was that  a Vagrant machine was running at the time I submitted the answer; when I turned that off, it passed. Thank you!
