### ISSUE TITLE
Preview in Steps not loading in pop-out window or after being toggled

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#49886]
### Describe the Issue

On the initial loading of a Step the preview is showing in the preview pane, but if you either open the preview in the pop-out window or toggle the preview pane off/on then the preview does not load again.

### Affected Page

All Steps in New RWD

### Steps to Reproduce

1. https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-55
2. Open preview in pop-out window (preview does not load)
3. Reload page
4. Use Preview button to toggle preview pane off/on (preview does not load)

### Expected behavior

Preview should load in both pop-out window and after the preview pane has been toggled off/on.

### System

Verified with Chrome/Firefox on both Linux and Win11.

### Additional context

Possibly related to issue #47608, but I think this is newer and slightly different.

**Comment by bbsmooth** [comment]
Just discovered that if you make any change in the editor (such as adding a single space) then the preview will refresh and display again.

**Comment by lasjorg** [comment]
When the preview is blank the iframe attributes are not updated either (which makes sense I guess, it looks to be the default values).

Blank before updating:
```
<iframe class="challenge-preview-frame" id="fcc-main-frame" title="Challenge Preview"></iframe>
```
After updating:
```
<iframe id="fcc-main-frame" title="freeCodeCamp Survey Form preview" lang="en" class="challenge-preview-frame"></iframe>
```

It feels like a state issue.

**Comment by bbsmooth** [comment]
The preview also disappears if you toggle the Instructions on any of the certification projects.
