### ISSUE TITLE
Warn user on failed submission for backend project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49883]
Thanks to @shootermv PR #46734, campers don't navigate to next challenge when the API call fails, which is the intended behavior.

But there is no feedback to campers that API call failed, and they left wondering why when they press submit button for the backend project, nothing work.

It would be nice to have alert message of what happened, to give indication to campers that the API call failed.

Edit: I am hoping this issue solve in the client only, changing the API will be extra effort while we are remake a new one, if this issue isn't solvable in the client, please ping me and I will close it.

---

Edit: If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by cto234** [comment]
Does the submitted link matter for recreating this issue if I followed the instructions to mimic the API failure as described in the linked issue?

**Comment by Sboonny** [comment]
Submitting project is a way to do it, you can also change the disabled attribute in submit button, to work without url.

**Comment by Ismailtlem** [comment]
this is done ?

**Comment by Sboonny** [comment]
yeab, a warning should be displayed when it fails
