### ISSUE TITLE
Challenge name is not showing up for forum posts

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#49884]
### Describe the Issue

When a user creates a new post using the ask for help button in the challenge, the challenge name is not showing up

<img width="791" alt="Screen Shot 2023-03-28 at 10 44 46 AM" src="https://user-images.githubusercontent.com/67210629/228324909-0d47ca53-3d1a-47fd-ac6d-1151a672cda6.png">

### Affected Page

https://forum.freecodecamp.org/

### Steps to Reproduce

1. Go to https://forum.freecodecamp.org/
2. Click on click on one of the posts generated from the ask for help buttons - https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-2/601196
3. Scroll down to to see the following challenge name missing

<img width="791" alt="Screen Shot 2023-03-28 at 10 44 46 AM" src="https://user-images.githubusercontent.com/67210629/228325358-92707100-238c-4fed-8229-c3e11f4e89d4.png">

### Expected behavior

Should show the correct challenge name

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Looks like the challenge title is not being passed anymore:
https://github.com/freeCodeCamp/freeCodeCamp/blob/05f0ef1dab86e6f92f555faacd85ef04f85ffe16/client/src/templates/Challenges/redux/create-question-epic.js#L95
