### ISSUE TITLE
learn-bash-and-sql-by-building-a-bike-rental-shop-build-a-bike-rental-shop

### ISSUE THREAD

**Issue by duartenunes86** [freeCodeCamp/freeCodeCamp#49896]
### Describe the Issue

learn-bash-and-sql-by-building-a-bike-rental-shop-build-a-bike-rental-shop

Challenge:

And set the available column to false for the bike rented. Below the end of the if statement that inserts a new customer, add five more comments; get customer_id, insert bike rental, set bike availability to false, get bike info, and send to main menu

My code:

<div class="nH aHU" style="position: relative; color: rgb(32, 33, 36); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="nH hx" style="background-color: transparent; color: rgb(34, 34, 34); min-width: 502px; padding: 0px;"><div class="nH" jslog="20686; u014N:xr6bB; 1:WyIjdGhyZWFkLWE6ci0yNTUyMjc2MTQyNzQxMzgzODEyIixudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxbXV0." role="list"><div class="h7 ie nH oy8Mbf" role="listitem" aria-expanded="true" tabindex="-1" style="clear: both; padding-bottom: 0px; max-width: 100000px; outline: none;"><div class="Bk" style="position: relative; margin-bottom: 0px; border-width: 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(239, 239, 239); border-right-color: initial; border-left-color: initial; border-image: initial; border-bottom-color: initial; border-radius: 0px; float: left; width: 1576px;"><div class="G3 G2" style="padding-top: 0px; background-color: transparent; border-right: 0px; border-bottom: 0px rgba(100, 121, 143, 0.12); border-left: 0px; border-image: initial; border-top: none; border-radius: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px;"><div><div id=":x8"><div class="adn ads" data-message-id="#msg-a:r-5679818228153611096" data-legacy-message-id="1872dceab041ae22" style="border-left: none; padding: 0px; display: flex;"><div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 1504px;"><div class=""><div id=":mv" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWE6ci0yNTUyMjc2MTQyNzQxMzgzODEyIixudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxbXV0.; 4:WyIjbXNnLWE6ci01Njc5ODE4MjI4MTUzNjExMDk2IixudWxsLFtdXQ.." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":x7" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="ltr"><div style="color: rgb(223, 223, 226); background-color: rgb(42, 42, 64); font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 14px; line-height: 19px; white-space: pre-wrap;"><div><span style="color: rgb(114, 133, 183);">#!/bin/bash</span></div><br><div>PSQL=<span style="color: rgb(209, 241, 169);">"psql -X --username=freecodecamp --dbname=bikes --tuples-only -c"</span></div><br><div><span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\n~~~~~ Bike Rental Shop ~~~~~\n"</span></div><br><div><span style="color: rgb(187, 218, 255);">MAIN_MENU</span>() {</div><div>  <span style="color: rgb(235, 187, 255);">if</span> [[ <span style="color: rgb(255, 157, 164);">$1</span> ]]</div><div>  <span style="color: rgb(235, 187, 255);">then</span></div><div>    <span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\n</span><span style="color: rgb(255, 157, 164);">$1</span><span style="color: rgb(209, 241, 169);">"</span></div><div>  <span style="color: rgb(235, 187, 255);">fi</span></div><br><div>  <span style="color: rgb(187, 218, 255);">echo</span> <span style="color: rgb(209, 241, 169);">"How may I help you?"</span> </div><div>  <span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\n1. Rent a bike\n2. Return a bike\n3. Exit"</span></div><div>  <span style="color: rgb(187, 218, 255);">read</span> MAIN_MENU_SELECTION</div><br><div>  <span style="color: rgb(235, 187, 255);">case</span> <span style="color: rgb(255, 157, 164);">$MAIN_MENU_SELECTION</span> <span style="color: rgb(235, 187, 255);">in</span></div><div>    1) RENT_MENU ;;</div><div>    2) RETURN_MENU ;;</div><div>    3) EXIT ;;</div><div>    <span style="color: rgb(153, 255, 255);">*</span>) MAIN_MENU <span style="color: rgb(209, 241, 169);">"Please enter a valid option."</span> ;;</div><div>  <span style="color: rgb(235, 187, 255);">esac</span></div><div>}</div><br><div><span style="color: rgb(187, 218, 255);">RENT_MENU</span>() {</div><div>  <span style="color: rgb(114, 133, 183);"># get available bikes</span></div><div>  AVAILABLE_BIKES=<span style="color: rgb(209, 241, 169);">$(</span><span style="color: rgb(255, 157, 164);">$PSQL</span><span style="color: rgb(209, 241, 169);"> "SELECT bike_id, type, size FROM bikes WHERE available = true ORDER BY bike_id")</span></div><br><div>  <span style="color: rgb(114, 133, 183);"># if no bikes available</span></div><div>  <span style="color: rgb(235, 187, 255);">if</span> [[ <span style="color: rgb(153, 255, 255);">-z</span> <span style="color: rgb(255, 157, 164);">$AVAILABLE_BIKES</span> ]]</div><div>  <span style="color: rgb(235, 187, 255);">then</span></div><div>    <span style="color: rgb(114, 133, 183);"># send to main menu</span></div><div>    MAIN_MENU <span style="color: rgb(209, 241, 169);">"Sorry, we don't have any bikes available right now."</span></div><div>  <span style="color: rgb(235, 187, 255);">else</span></div><div>    <span style="color: rgb(114, 133, 183);"># display available bikes</span></div><div>    <span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\nHere are the bikes we have available:"</span></div><div>    <span style="color: rgb(187, 218, 255);">echo</span> <span style="color: rgb(209, 241, 169);">"</span><span style="color: rgb(255, 157, 164);">$AVAILABLE_BIKES</span><span style="color: rgb(209, 241, 169);">"</span> <span style="color: rgb(153, 255, 255);">|</span> <span style="color: rgb(235, 187, 255);">while</span> <span style="color: rgb(187, 218, 255);">read</span> BIKE_ID BAR TYPE BAR SIZE</div><div>    <span style="color: rgb(235, 187, 255);">do</span></div><div>      <span style="color: rgb(187, 218, 255);">echo</span> <span style="color: rgb(209, 241, 169);">"</span><span style="color: rgb(255, 157, 164);">$BIKE_ID</span><span style="color: rgb(209, 241, 169);">) </span><span style="color: rgb(255, 157, 164);">$SIZE</span><span style="color: rgb(255, 197, 143);">\"</span><span style="color: rgb(209, 241, 169);"> </span><span style="color: rgb(255, 157, 164);">$TYPE</span><span style="color: rgb(209, 241, 169);"> Bike"</span></div><div>    <span style="color: rgb(235, 187, 255);">done</span></div><br><div>    <span style="color: rgb(114, 133, 183);"># ask for bike to rent</span></div><div>    <span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\nWhich one would you like to rent?"</span></div><div>    <span style="color: rgb(187, 218, 255);">read</span> BIKE_ID_TO_RENT</div><br><div>    <span style="color: rgb(114, 133, 183);"># if input is not a number</span></div><div>    <span style="color: rgb(235, 187, 255);">if</span> [[ <span style="color: rgb(153, 255, 255);">!</span> <span style="color: rgb(255, 157, 164);">$BIKE_ID_TO_RENT</span> <span style="color: rgb(153, 255, 255);">=~</span> ^[0-9]+$ ]]</div><div>    <span style="color: rgb(235, 187, 255);">then</span></div><div>      <span style="color: rgb(114, 133, 183);"># send to main menu</span></div><div>      MAIN_MENU <span style="color: rgb(209, 241, 169);">"That is not a valid bike number."</span></div><div>    <span style="color: rgb(235, 187, 255);">else</span></div><div>      <span style="color: rgb(114, 133, 183);"># get bike availability</span></div><div>      BIKE_AVAILABILITY=<span style="color: rgb(209, 241, 169);">$(</span><span style="color: rgb(255, 157, 164);">$PSQL</span><span style="color: rgb(209, 241, 169);"> "SELECT available FROM bikes WHERE bike_id = </span><span style="color: rgb(255, 157, 164);">$BIKE_ID_TO_RENT</span><span style="color: rgb(209, 241, 169);"> AND available = true")</span></div><br><div>      <span style="color: rgb(114, 133, 183);"># if not available</span></div><div>      <span style="color: rgb(235, 187, 255);">if</span> [[ <span style="color: rgb(153, 255, 255);">-z</span> <span style="color: rgb(255, 157, 164);">$BIKE_AVAILABILITY</span> ]]</div><div>      <span style="color: rgb(235, 187, 255);">then</span></div><div>        <span style="color: rgb(114, 133, 183);"># send to main menu</span></div><div>        MAIN_MENU <span style="color: rgb(209, 241, 169);">"That bike is not available."</span></div><div>      <span style="color: rgb(235, 187, 255);">else</span></div><div>        <span style="color: rgb(114, 133, 183);"># get customer info</span></div><div>        <span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\nWhat's your phone number?"</span></div><div>        <span style="color: rgb(187, 218, 255);">read</span> PHONE_NUMBER</div><br><div>        CUSTOMER_NAME=<span style="color: rgb(209, 241, 169);">$(</span><span style="color: rgb(255, 157, 164);">$PSQL</span><span style="color: rgb(209, 241, 169);"> "SELECT name FROM customers WHERE phone = '</span><span style="color: rgb(255, 157, 164);">$PHONE_NUMBER</span><span style="color: rgb(209, 241, 169);">'")</span></div><br><div>        <span style="color: rgb(114, 133, 183);"># if customer doesn't exist</span></div><div>        <span style="color: rgb(235, 187, 255);">if</span> [[ <span style="color: rgb(153, 255, 255);">-z</span> <span style="color: rgb(255, 157, 164);">$CUSTOMER_NAME</span> ]]</div><div>        <span style="color: rgb(235, 187, 255);">then</span></div><div>          <span style="color: rgb(114, 133, 183);"># get new customer name</span></div><div>          <span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\nWhat's your name?"</span></div><div>          <span style="color: rgb(187, 218, 255);">read</span> CUSTOMER_NAME</div><br><div>          <span style="color: rgb(114, 133, 183);"># insert new customer</span></div><div>          INSERT_CUSTOMER_RESULT=<span style="color: rgb(209, 241, 169);">$(</span><span style="color: rgb(255, 157, 164);">$PSQL</span><span style="color: rgb(209, 241, 169);"> "INSERT INTO customers(name, phone) VALUES('</span><span style="color: rgb(255, 157, 164);">$CUSTOMER_NAME</span><span style="color: rgb(209, 241, 169);">', '</span><span style="color: rgb(255, 157, 164);">$PHONE_NUMBER</span><span style="color: rgb(209, 241, 169);">')")</span> </div><div>        <span style="color: rgb(235, 187, 255);">fi</span></div><div>        </div><div>        <span style="color: rgb(114, 133, 183);">#get customer_id</span></div><br><div>        <span style="color: rgb(114, 133, 183);">#insert bike rental</span></div><br><div>        <span style="color: rgb(114, 133, 183);">#set bike availability to false</span></div><br><div>        <span style="color: rgb(114, 133, 183);">#get bike info</span></div><br><div>        <span style="color: rgb(114, 133, 183);">#send to main menu</span></div><div>        </div><div>      <span style="color: rgb(235, 187, 255);">fi</span></div><div>    <span style="color: rgb(235, 187, 255);">fi</span></div><div>  <span style="color: rgb(235, 187, 255);">fi</span></div><div>}</div><br><div><span style="color: rgb(187, 218, 255);">RETURN_MENU</span>() {</div><div>  <span style="color: rgb(187, 218, 255);">echo</span> <span style="color: rgb(209, 241, 169);">"Return Menu"</span></div><div>}</div><br><div><span style="color: rgb(187, 218, 255);">EXIT</span>() {</div><div>  <span style="color: rgb(187, 218, 255);">echo</span> -e <span style="color: rgb(209, 241, 169);">"\nThank you for stopping in.\n"</span></div><div>}</div><br><div>MAIN_MENU</div><div class="yj6qo"></div><div class="adL"><br></div></div></div><div class="adL"></div></div></div><div class="hi" style="border-bottom-left-radius: 1px; border-bottom-right-radius: 1px; padding: 0px; width: auto; background: rgb(242, 242, 242); margin: 0px;"></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: transparent;"><div class="gB xu" style="border-top: 0px; padding: 0px;"><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":mu">

  | ReplyForward
-- | --

</div></div></div></div></div></div></div></div></div></div><div class="nH"></div><div class="nH"></div></div></div><div class="nH" style="color: rgb(32, 33, 36); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-and-sql-by-building-a-bike-rental-shop/build-a-bike-rental-shop

### Your code

```

```
#!/bin/bash

PSQL="psql -X --username=freecodecamp --dbname=bikes --tuples-only -c"

echo -e "\n~~~~~ Bike Rental Shop ~~~~~\n"

MAIN_MENU() {
  if [[ $1 ]]
  then
    echo -e "\n$1"
  fi

  echo "How may I help you?" 
  echo -e "\n1. Rent a bike\n2. Return a bike\n3. Exit"
  read MAIN_MENU_SELECTION

  case $MAIN_MENU_SELECTION in
    1) RENT_MENU ;;
    2) RETURN_MENU ;;
    3) EXIT ;;
    *) MAIN_MENU "Please enter a valid option." ;;
  esac
}

RENT_MENU() {
  # get available bikes
  AVAILABLE_BIKES=$($PSQL "SELECT bike_id, type, size FROM bikes WHERE available = true ORDER BY bike_id")

  # if no bikes available
  if [[ -z $AVAILABLE_BIKES ]]
  then
    # send to main menu
    MAIN_MENU "Sorry, we don't have any bikes available right now."
  else
    # display available bikes
    echo -e "\nHere are the bikes we have available:"
    echo "$AVAILABLE_BIKES" | while read BIKE_ID BAR TYPE BAR SIZE
    do
      echo "$BIKE_ID) $SIZE\" $TYPE Bike"
    done

    # ask for bike to rent
    echo -e "\nWhich one would you like to rent?"
    read BIKE_ID_TO_RENT

    # if input is not a number
    if [[ ! $BIKE_ID_TO_RENT =~ ^[0-9]+$ ]]
    then
      # send to main menu
      MAIN_MENU "That is not a valid bike number."
    else
      # get bike availability
      BIKE_AVAILABILITY=$($PSQL "SELECT available FROM bikes WHERE bike_id = $BIKE_ID_TO_RENT AND available = true")

      # if not available
      if [[ -z $BIKE_AVAILABILITY ]]
      then
        # send to main menu
        MAIN_MENU "That bike is not available."
      else
        # get customer info
        echo -e "\nWhat's your phone number?"
        read PHONE_NUMBER

        CUSTOMER_NAME=$($PSQL "SELECT name FROM customers WHERE phone = '$PHONE_NUMBER'")

        # if customer doesn't exist
        if [[ -z $CUSTOMER_NAME ]]
        then
          # get new customer name
          echo -e "\nWhat's your name?"
          read CUSTOMER_NAME

          # insert new customer
          INSERT_CUSTOMER_RESULT=$($PSQL "INSERT INTO customers(name, phone) VALUES('$CUSTOMER_NAME', '$PHONE_NUMBER')") 
        fi
        
        #get customer_id

        #insert bike rental

        #set bike availability to false

        #get bike info

        #send to main menu
        
      fi
    fi
  fi
}

RETURN_MENU() {
  echo "Return Menu"
}

EXIT() {
  echo -e "\nThank you for stopping in.\n"
}

MAIN_MENU

### Expected behavior

Challenge passed

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
Computer at a library

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Ask for Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.
