### ISSUE TITLE
Use fixture to assign variables instead of `const` and `let` in cypress

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49899]
Our cypress tests are flaky, and we have been getting this error multiple times 

> An invalid or illegal string was specified

Here is one of the actions: https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/4562071757/jobs/8049118275?pr=49825

---

Although I don't know the cause, I know that using `const`, `let` and `var` is antipattern by cypress.

https://docs.cypress.io/guides/references/best-practices#Assigning-Return-Values

Here is a copy of selector we have in the codebase.

https://github.com/freeCodeCamp/freeCodeCamp/blob/e77baf55a4125f248c6cfdcc028994161617a688/cypress/e2e/default/learn/challenges/multifile.ts#L4-L11

So hopefully to reduce the flakiness, we can use fixtures instead. Chapter uses fixture in multiple tests, we can copy the same approach

fixture folder: https://github.com/freeCodeCamp/chapter/tree/main/cypress/fixtures

and here how the fixture code usage will look like: 

https://github.com/freeCodeCamp/chapter/blob/183f080be5fb96567cc3e7847616ae5866cc130b/cypress/e2e/chapters/%5BchapterId%5D.cy.ts#L11-L13

**Comment by naomi-lgbt** [comment]
> Trying to assign the return value of Commands with const, let, or var.

It looks like the anti-pattern is specifically for Cypress commands, like `cy.get()` - I don't believe using a selectors object is an antipattern.

**Comment by Sboonny** [comment]
True, before I close this, is there a way to use fixture that is beneficial and reduce flakeness. 🤔


We only have `example.json`.

**Comment by naomi-lgbt** [comment]
I'm not sure that fixtures would do anything for the flakiness in this case.

**Comment by Sboonny** [comment]
closed in favor of #49966
