### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/drop-it-like-its-hot has an issue 

### ISSUE THREAD

**Issue by rodocite** [FreeCodeCamp/freecodecamp#499]
Basic Algorithm Scripting - Bonfire #34 - Drop it Like It's Hot link gives error: 

404: We couldn't find a challenge with that name. Please double check the name.

Browser: Chrome 43.0.2357.65

**Comment by terakilobyte** [comment]
Thanks a bunch, that darned apostrophe was getting in the way. The challenge has been renamed no "Drop it"!
