### ISSUE TITLE
Waypoint: Make Unique Objects by Passing Parameters to our Constructor

### ISSUE THREAD

**Issue by eagle122** [FreeCodeCamp/FreeCodeCamp#4992]
I'm getting the error of  "TypeError: Attempted to to assign to readonly property"
This error code was there before I entered my code in.
This is how my code looks  I did not change anything below the code line.  I'm thinking this is a bug since the error was there before I put in my code.

var Car = function() {
  //Change this constructor
  this.wheels = 4;
  this.seats = 1;
  this.engines = 1;
};

//Try it out here
var myCar = function(){
  this.wheels = 6;
  this.seats = 3;
  this.engines = 1;
}

// Only change code above this line

(function() {return JSON.stringify(myCar);})();

**Comment by ltegman** [comment]
This error is not present when the seed code is run, it is caused by your solution code. You're calling an anonymous function where the instructions are asking you to use your constructor (which should have been modified to use parameters).

Please ask for help with challenges in the [Help Chat](https://gitter.im/FreeCodeCamp/Help)

Thanks and happy coding!

**Comment by dorbor** [comment]
var Car = function(wheels, seats, engines) {
  //Change this constructor
  this.wheels = wheels;
  this.seats = seats;
  this.engines = engines;
};

//Try it out here
var myCar = new Car(3,1,2);

**Comment by richa-coder** [comment]
var Car = function(wheels, seats, engines) {
 this.wheels = wheels;
  this.seats = seats;
  this.engines = engines;
};
//Try it out here
var myCar = new Car(2,6,3);
myCar = new Car(3,1,2);
myCar = new Car(4,4,2);

This should work.

**Comment by no-stack-dub-sack** [comment]
Hi @richa-coder! This issue was closed some time last year - are you supplying a solution or asking a question? Does the code you provided not work on your end?

Thanks!
