### ISSUE TITLE
Typo in Waypoint: Use Hex Code for Specific Colors

### ISSUE THREAD

**Issue by caos21** [FreeCodeCamp/FreeCodeCamp#4993]
Challenge [Waypoint: Use Hex Code for Specific Colors](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.

The text "The word ```Hexademical``` can be broken down into the words hexa and decimal. " is wrong, must be ```Hexadecimal```

**Comment by benschac** [comment]
Can I take this issue?

**Comment by DDaems** [comment]
Feel free to do so ;-)

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

**Comment by benschac** [comment]
I'm new to waffle, how do I assign and move the issue into in progress?

**Comment by DDaems** [comment]
You actually can't i believe, never really used the Waffle board. Anyway you could just reply to a issue.
Like you did here, but carefully check if the issue doesn't have any references to commints/pull requests. So you don't and up, writing a fix. That is allready been done by someone else ;-)
