### ISSUE TITLE
Resolve Flaky Cypress Tests

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#49966]
#49947 updated Cypress to 11 and unblocked the Firefox CI. There's a couple of specs that are temporarily skipped due to flakiness. We should fix the specs and remove them from the exclusion list.

- [ ] [challenge-hot-keys](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/cypress/e2e/default/learn/challenge-hot-keys.ts)
- [ ] [multifile](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/cypress/e2e/default/learn/challenges/multifile.ts)
- [x] [multifile-cert-projects](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/cypress/e2e/default/learn/challenges/multifile-cert-project.ts)

**Comment by gikf** [comment]
The problems arise when tests are running on firefox, specifically headless. There's cypress bug `https://github.com/cypress-io/cypress/issues/5023`, related to some issues with focus when running headless, or without browser in focus, which seems to be coming and going. Possibly cypress `12.x` doesn't have this issue, but I haven't checked that.

To _reproduce_ errors locally, cypress has to be run with headless firefox:
`pnpm run cypress:dev:run --browser firefox`

I was looking at the `challenge-hot-keys.ts`, which might not be as easy to work around, as it needs to keep the focus between two keys pressed. Some option could be excluding the suite from tests when it's run on firefox only - https://docs.cypress.io/api/cypress-api/isbrowser#Test-configuration-browser.

**Comment by Sboonny** [comment]
Confetti test is flaky too, it fails occasionally without someone changing the logic related to its logic https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/6431899232/job/17466110395?pr=51833
