### ISSUE TITLE
Possible Change to Switch Introduction

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#49976]
### Describe the Issue

One could argue that this text is telling the learner that you can only use `console.log()` statements inside of a switch and no other code statements:

> If you have many options to choose from, use a switch statement. A switch statement tests a value and can have many case statements which define various possible values. Statements are executed from the first matched case value until a break is encountered.

> Here is an example of a switch statement:
```
switch (fruit) {
  case "apple":
    console.log("The fruit is an apple");
    break;
  case "orange":
    console.log("The fruit is an orange");
    break;
}
```
> case values are tested with strict equality (===). The break tells JavaScript to stop executing statements. If the break is omitted, the next statement will be executed.

I don't know that I agree, but we could possibly make it more explicit what we mean by "[case] Statements are executed". 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/selecting-from-many-options-with-switch-statements

### Your code

N/A

### Expected behavior

Possible clearer language

### System

N/A

**Comment by nyni123** [comment]
Hi @jeremylt 
Introduction text could be revised to something like:

"If you have many options to choose from, use a switch statement. A switch statement tests a value and can have many case statements which define various possible values. Any valid JavaScript statements can be executed inside a case block, from the first matched case value until a break is encountered."

This revised language makes it clear that any valid JavaScript statement can be used inside a case block, and removes any potential confusion or limitation that may have been interpreted from the previous language.

**Comment by jeremylt** [comment]
I like it. Small adjustment

> If you need to match one value against many options, you can use a switch statement. A switch statement compares the value to the case statements which define various possible values. Any valid JavaScript statements can be executed inside a case block, from the first matched case value until a break is encountered.

**Comment by nyni123** [comment]
@jeremylt 
Thank you for your feedback! I'm glad you like the suggested change. Could you please let me know what small adjustment you had in mind? I want to make sure I address any concerns or suggestions before submitting a pull request. Thank you!

**Comment by jeremylt** [comment]
I posted it above:

> If you need to match one value against many options, you can use a switch statement. A switch statement compares the value to the case statements which define various possible values. Any valid JavaScript statements can be executed inside a case block, from the first matched case value until a break is encountered.
