### ISSUE TITLE
Not working? jQuery add class "animated" & "shake" to al ".well" elements

### ISSUE THREAD

**Issue by SkoobGeneral** [FreeCodeCamp/FreeCodeCamp#4997]
Challenge [Waypoint: Target Elements by Class Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22button%22).addClass(%22animated%20bounce%22)%3B%0A%20%20%20%20%24(%22.well%22).addClass(%22animated%20shake%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
    $(".well").addClass("animated shake");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
#4556

**Comment by del-dow** [comment]
I have the same issue. If I copy and paste the code it works fine ,however, typing the code directly doesn't work.

**Comment by paigep** [comment]
Same issue here, working on Google Chrome.
Have tried making a new $(document).ready(function(){... , have tried the above, and have tried replacing the original button animated bounce code with the new well animated shake code, and I've found that the well shake will not work in the preview box, nor can I pass the lesson.

can confirm that copy-and-pasting the entire code newly into the page allows me to pass the lesson, but writing it by hand into the text editor will not work.

**Comment by sludge256** [comment]
@del-dow @paigep Could you provide more details?

-Browser, OS and/or device
-URL from the browser after you manually enter in the correct code (please use Markdown to format the link so it's not super long)
-A copy of your code in as text

**Comment by EmreAkkiray** [comment]
works fine on mine....

**Comment by Scoodood** [comment]
Make sure it's "shake" not "bounce", because I had the typo too

**Comment by Danultimate** [comment]
I have the same issue.. I tried to refresh, copy/paste the code, nothing work for me.

**Comment by myrNG** [comment]
Hello!

I have the same issue here. But works fine on the FCC's editor online BUT, when i want to train on my own IDE (Sublime Text), it doesn't work. I don't understand why?
I'm gonna keep searching explanations on the web but if someone found out why, i'm interested!
Thank you! `:)

`<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

		
	</head>
	<body>
		
		<div class="container-fluid">
			<h3 class="text-primary text-center">jQuery Playground</h3>
			<div class="row">
				<div class="col-xs-6">
					<h4>#left-well</h4>
					<div class="well" id="left-well">
						<div class="btn btn-default target" id="target1">#target1</div>
						<div class="btn btn-default target" id="target2">#target2</div>
						<div class="btn btn-default target" id="target3">#target3</div>
					</div>
				</div>
				<div class="col-xs-6">
					<h4>#right-well</h4>
					<div class="well" id="right-well">
						<div class="btn btn-default target" id="target4">#target4</div>
						<div class="btn btn-default target" id="target5">#target5</div>
						<div class="btn btn-default target" id="target6">#target6</div>
					</div>
				</div>
			</div>
		</div>

		
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
		<script>
			$(document).ready(function() {
				$("#target1").css("color", "red"); // Permet de modifier les propriétés d'un élément en CSS
				$("#target1").prop("disabled", true); // Permet d'ajuster les propriétés d'un élément - code qui ne fonctionne pas sur Chrome et Firefox
				$("#target4").remove(); // Permet de retirer un élément
				$("#target2").appendTo("#right-well"); // Permet de déplacer un élément
				$("#target5").clone().appendTo("#left-well"); // Permet de cloner un élément. Il s'agit ici d'une function chaining: on clone puis on déplace l'élément
				$("#target1").parent().css("background-color", "red"); // Permet d'accéder au parent de l'élément sélectionné - code qui ne fonctionne pas sur Chrome et Firefox
				$("#right-well").children().css("color", "orange"); // Permet d'accéder aux enfants de l'élément sélectionné
				$(".target:nth-child(2)").addClass("animated bounce"); // Sélecteur CSS qui permet de sélectionner un énième enfant d'un élément sélectionné - code qui ne fonctionne pas avec Chrome et Firefox
				$(".target:even").addClass("animated shake"); // Sélecteur de CSS - ne fonctionne pas sur Chrome et Firefox
			});
		</script>
	</body>
</html`

**Comment by hasanshahoud** [comment]
![target html elements with selectors using jquery free code camp](https://cloud.githubusercontent.com/assets/20051470/17031458/97f13694-4f74-11e6-94e1-d6742a4d2f6a.png)

guys thats why its does't work out with you//

**Comment by SainiRavi** [comment]
1) look at this website to download Animate.css
https://daneden.github.io/animate.css/

2) To add Jquery library here is google api link.
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"> </script>

**Comment by LalMasta** [comment]
i had the same issue with shake, got it work by making the "C" in .addClass capital letter

**Comment by aysrl** [comment]
I had the same issue a couple hours ago. If you want to do this out of the FCC editor, just download animate.css here https://daneden.github.io/animate.css/, then add the link element to your head just like this:
<head>
	<title>iring itom</title>
	<link rel="stylesheet" type="text/css" href="main.css">
	<link rel="stylesheet" type="text/css" href="animate.css"> <-- Here is the animate.css -->
	<link href="css/bootstrap.min.css" rel="stylesheet">
</head>

**Comment by manuelruizp** [comment]
Add this to your head, friends:
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

**Comment by mohamedwahshey** [comment]
This is not a bug, you just have to write **.addClass** not **.addclass**

with a CAPITAL C, and it'll all work fine, that's why when you copy it it works.

It's a real troll i know but this is how it works :D 

like **.appendTo** not **.appendto** lol

works for me BTW
You welcome :D
