### ISSUE TITLE
Mentor Feature

### ISSUE THREAD

**Issue by kevinvangelder** [freeCodeCamp/freeCodeCamp#49999]
### Is your feature request related to a problem? Please describe.

Some of my friends and family want to learn to code. I point them to FreeCodeCamp as a great resource, but I have no insight into their progress or the quality of their code solutions and as such am not able to provide quality mentorship advice.

### Describe the solution you'd like

Allow students to assign another user as a mentor. The mentor account would able to see progress of the student and give feedback on their code solutions (maybe initially on a exercise-by-exercise basis and eventually on a line-by-line basis like GitHub PR reviews).

### Describe alternatives you've considered

I could review progress with them over a video call, but that requires both parties to be available at the same time rather than asynchronous.

**Comment by naomi-lgbt** [comment]
This seems like something that might work well with our upcoming [classroom mode](https://github.com/freeCodeCamp/classroom).

**Comment by codewithfan** [comment]
It is awesome to receive some notification once the mentee completes a section, like an email, or from the mentor's perspective, a timeline on where they are with a course.
