### ISSUE TITLE
Clunky wording in CSS Markers step 5

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#49998]
### Describe the Issue

The wording on this step is a bit awkward. Based on [a forum post](https://forum.freecodecamp.org/t/learn-css-colors-by-building-a-set-of-colored-markers-step-5/603118), the wording `You should add a new meta element for each attribute you want to specify.` isn't quite accurate.

This resulted in the camper writing the following code:

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/616965351e74d4689eb6de30.md

### Your code

```
  <head>
    <meta charset="utf-8">
    <meta name='viewport'>
    <meta content='width=device-width, initial-scale=1.0'>
    <title>Colored Markers</title>
  </head>
```

### Expected behavior

I'm not sure how to better describe this, tbh.

### System

System info isn't relevant for a verbiage issue (:

**Comment by bbsmooth** [comment]
Agreed, that is clunky. Just to get the ball rolling.

> You can have multiple self-closing `meta` elements on a web page. Each `meta` element is used to add information about the page that cannot be expressed by another HTML element.

**Comment by anishlukk123** [comment]
is anyone working on this, but i can take this up

**Comment by naomi-lgbt** [comment]
Hey there,

This issue is still under discussion and has not been opened up for contribution yet.

**Comment by nyni123** [comment]
Hi there, 

I read through the issue related to the wording in step 5 of the 'Learn CSS Colors by Building a Set of Colored Markers' challenge, and I think I might have a suggestion for how to improve the wording. Here's a revised version of the step that I came up with:

'Add a new meta element for each attribute that you want to specify. To specify the viewport attributes, add the following meta element to the head of your HTML document:
<meta name='viewport' content='width=device-width, initial-scale=1.0'>'

I hope this helps clarify the step for other campers. Let me know if you have any feedback or if there's anything else I can do to help with this issue.

**Comment by jeremylt** [comment]
Simpler language is better. Complex sentence structure is harder for learners (and non-learners tbh) to understand.

> You can have multiple self-closing `meta` elements on a web page. Each `meta` element adds information about the page that cannot be expressed by other HTML elements.

> Add another self-closing `meta` element within the `head`. Give it a `name` attribute set to `viewport` and a `content` attribute set to `width=device-width, initial-scale=1.0` so your page looks the same on all devices.

We really need to go on a linguistic simplification campaign though the lessons. I just haven't had the time to do so.

**Comment by vdwaseem** [comment]
What did we finalize?

**Comment by naomi-lgbt** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-colors-by-building-a-set-of-colored-markers/616965351e74d4689eb6de30.md

The `description` of the challenge should be updated to the following text:

```md
You can have multiple self-closing `meta` elements on a web page. Each `meta` element adds information about the page that cannot be expressed by other HTML elements.

Add another self-closing `meta` element within the `head`. Give it a `name` attribute set to `viewport` and a `content` attribute set to `width=device-width, initial-scale=1.0` so your page looks the same on all devices.
```

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
