### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by Toreador78** [FreeCodeCamp/freecodecamp#500]
Challange responses with 'Syntax Error' even in 'mint' state or with complete empty code-file

**Comment by QuincyLarson** [comment]
@toreador78 Could you link to a screen shot? Which browser/operating system are you using? Thank you so much for helping us debug this!

**Comment by QuincyLarson** [comment]
We've fixed this. Thank you for your patience, and for bringing this to our attention!
