### ISSUE TITLE
English subtitles youtube

### ISSUE THREAD

**Issue by Mount-Ta1** [freeCodeCamp/freeCodeCamp#50028]
Can you upload English subtitles for youtube videos? I need to use a chrome plug-in to translate to understand. The automatically generated subtitles experience is very poor and the speed is very slow, which makes me unable to understand the content. I sincerely hope to upload English subtitles, thank you very much

**Comment by raisedadead** [comment]
Thanks for reaching out. This issue tracker is for the issues related to the codebases on GitHub. Please reach out to the community forum: https://forum.freecodecamp.org for your query.
