### ISSUE TITLE
Wrap border around code elements in the instruction

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50034]
Mentioned once in issue triage meeting, we can add border to indicate when is the code starts and ends, something like this.

![image](https://user-images.githubusercontent.com/88248797/230955452-b9eaf8f0-8be7-418a-a8e7-9f8c28e7b5ac.png)

![image](https://user-images.githubusercontent.com/88248797/230955640-423af82b-e1e3-486a-a25c-132939bd43c0.png)

Some styling can make the border look better.

**Comment by bbsmooth** [comment]
Would this be used only for code samples, or would it apply to any content that is wrapped in a `code` element?

**Comment by Sboonny** [comment]
If the styles are good, it can enhance the looks in all code samples, and it will be less work. 🤔

**Comment by abhaykv04** [comment]
Upon reviewing the attached images, one potential area for improvement is the dark, boxy border surrounding the snippets. This design element may create confusion, particularly in the light theme, as it could be mistaken for buttons. Although the overall concept is sound, it may be necessary to exercise greater discretion in selecting visual styles to ensure optimal user experience.

**Comment by bbsmooth** [comment]
Another option, we could reverse the colors on the code elements. We currently do change the background slightly, but not enough to make a difference (at least from an accessibility perspective). 

Light mode:

![contrast1](https://user-images.githubusercontent.com/5926192/231276748-2f4a6646-e74f-40b3-84b4-0eca7e2ef488.png)

Dark mode:

![contrast2](https://user-images.githubusercontent.com/5926192/231277120-3affd857-a906-43e7-9275-c49123217266.png)

**Comment by bbsmooth** [comment]
@Sboonny Ya, we can definitely tone it down a little. I will add new images with a "calmer" contrast.

To be honest, I'm not excited about the borders. I think it makes the text look too busy.

**Comment by Vansh-Baghel** [comment]
May I change the text wrapper border to grey? Or are we planning for something different?

**Comment by Sboonny** [comment]
unfortunately not yet, still waiting for whenever a designer is free to look at it, this isn't an issue, so I am not hurrying it.

**Comment by ahmadabdolsaheb** [comment]
how about we lose the background and go for a ` {solid var(--quaternary-background);`
<img width="361" alt="Screenshot 2023-05-09 at 2 27 00 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/21203f02-a739-43a6-8590-9cc0965ce163">
<img width="360" alt="Screenshot 2023-05-09 at 2 26 51 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/7c297125-43f8-4d44-8004-ccddcfac3841">

**Comment by bbsmooth** [comment]
@ahmadabdolsaheb I fear those light borders won't help people who have color vision issues since they don't have enough contrast with the background. Granted, we are using a different font for the code so we already have a distinguishing feature. But if we feel we need to add additional information to help people know when the code begins and ends then we should make sure everyone can see it :slightly_smiling_face:

**Comment by bbsmooth** [comment]
> My only issue with the reversing the background is my eyes are getting watery from looking at the text, I am in favor of it, if they are different colors.

This following are using quaternary colors, which is as light as we can currently go using the existing color palette. If this isn't soft enough then we'll have to create some new colors.

![example1](https://github.com/freeCodeCamp/freeCodeCamp/assets/5926192/b958551d-4bbf-4b2a-8739-234d5e6b75f6)

![example2](https://github.com/freeCodeCamp/freeCodeCamp/assets/5926192/4974a728-f2dc-40d3-a8da-800377aebdfa)

**Comment by ahmadabdolsaheb** [comment]
I think using two colors would make it harder to read for everyone. We can move forward with the light border and iterate on it if necessary.

**Comment by ahmadabdolsaheb** [comment]
A border needs to be added to the code elements in the challenge/step description.
https://github.com/freeCodeCamp/freeCodeCamp/issues/50034#issuecomment-1539998589

**Comment by ahmadabdolsaheb** [comment]
@arunkumar0398, please go ahead 👍. No assignment is necessary as described in our [contribution guidelines](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.
