### ISSUE TITLE
Waypoint: Target the Children of an Element Using jQuery Run(Ctrl + enter) not working 

### ISSUE THREAD

**Issue by rajendrach** [FreeCodeCamp/FreeCodeCamp#5003]
Challenge [Waypoint: Target the Children of an Element Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").child().css("color", "green");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by ltegman** [comment]
The waypoint is asking you to change the `color` not the `background-color`. In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) rather than filing a bug.

Thanks and happy coding!

**Comment by rajendrach** [comment]
Sure thanks, sorry for the inconvenience, I raised the bug because it is not showing what the error as it shows in the rest of the modules

Sent from Outlook




On Thu, Dec 3, 2015 at 3:13 PM -0800, "Logan Tegman" <notifications@github.com> wrote:





The waypoint is asking you to change the `color` not the `background-color`. In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) rather than filing a bug.

Thanks and happy coding!

---

**Comment by rajendrach** [comment]
Hi I chsaw caked it I'm changing the color not the background color for right-well Id to green can you please check it again

Sent from Outlook




On Thu, Dec 3, 2015 at 3:13 PM -0800, "Logan Tegman" <notifications@github.com> wrote:





The waypoint is asking you to change the `color` not the `background-color`. In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) rather than filing a bug.

Thanks and happy coding!

---

**Comment by ltegman** [comment]
Now that you're changing the `color` the code passes perfectly for me. Does the problem continue if you refresh the page? Are you getting any errors in the console?

**Comment by rajendrach** [comment]
I'm not getting errors or nothing , it just says nothing I refreshed the page couple of times , I even did the later tasks but this one is not working on google chrome

Sent from Outlook




On Thu, Dec 3, 2015 at 3:23 PM -0800, "Logan Tegman" <notifications@github.com> wrote:





Now that you're changing the `color` the code passes perfectly for me. Does the problem continue if you refresh the page? Are you getting any errors in the console?

---

**Comment by ltegman** [comment]
Don't know how I didn't see this the first time -- your code is calling `child` when it should be calling `children`.

**Comment by rajendrach** [comment]
Sorry my bad thanks for the help, this has been. Great so far thanks to the whole community.

Sent from Outlook




On Thu, Dec 3, 2015 at 3:29 PM -0800, "Logan Tegman" <notifications@github.com> wrote:





Don't know how I didn't see this the first time -- your code is calling `child` when it should be calling `children`.

---
