### ISSUE TITLE
Cleaning the tech debt in the client

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50046]
Ahmad has pointed out these points in this PR  #49664

- toggle-button.tsx in the helper folder could be removed since it is not used anywhere.
- checkIconStyle should be moved to a CSS file.
- we have toggle buttons in video courses (scientific-computing-with-python, etc.), the newly added toggles should replicate the style of the pre-exiting toggles for consistency.

_Originally posted by @ahmadabdolsaheb in https://github.com/freeCodeCamp/freeCodeCamp/pull/49664#pullrequestreview-1381121628_

---

I am opening an issue, so they don't get lost to time

**Comment by bbsmooth** [comment]
> we have toggle buttons in video courses (scientific-computing-with-python, etc.), the newly added toggles should replicate the style of the pre-exiting toggles for consistency.

Can you point to an example of what you want the toggle buttons to look like?

**Comment by bbsmooth** [comment]
> toggle-button.tsx in the helper folder could be removed since it is not used anywhere.

I was sure I had removed it but apparently not. My brain not work well.

**Comment by Sboonny** [comment]
> I was sure I had removed it but apparently not. My brain not work well.

Most likely, I have messed up with the merge conflicts, I remember needing to keep the files, then re delete them, I may have deleted one of the two. 🤔

> Can you point to an example of what you want the toggle buttons to look like?

I think the odin, python and the new math curriculum has radio inputs, and not only they have similar styles, they don't have  `fieldset` and `legend` elements.

https://github.com/freeCodeCamp/freeCodeCamp/blob/28cbf6a4bdd2f81b936845112ecb8d23e4faa45a/client/src/templates/Challenges/video/show.tsx#L249-L274

**Comment by Anujvaid45** [comment]
hello, @Sboonny 
I was looking to contribute towards this issue and I am a bit confused regarding it
We have to style the newly added toggle buttons according to the already existing toggle buttons 
Anything else expected in this issue?

**Comment by Vansh-Baghel** [comment]
That was a huge discussion to read upto. I am looking to forward to fix these minors changes, if @bbsmooth is not already working on it.

**Comment by Vansh-Baghel** [comment]
@Sboonny Can you explain that how is  --answers-- working as buttons in every tab? So that I could get to the root of buttons and cross-check after shifting checkIconStyle to CSS files from using it as style in html elements.

**Comment by Vansh-Baghel** [comment]
Any updates on this issue?

**Comment by Sboonny** [comment]
Hi @Vansh-Baghel and @Anujvaid45, there are two task in this issue. 

- [ ] Delete toggle-button.tsx.
- [ ] Align the styles between them, most of them are in shows.tsx as shown in the linked PR and the first comment.

If you want to collaborate to solve this issue, feel free to discuss this in discord or the forum. 

---

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by bbsmooth** [comment]
> we have toggle buttons in video courses (scientific-computing-with-python, etc.), the newly added toggles should replicate the style of the pre-exiting toggles for consistency.

Just to be clear, you are saying that the toggle radio buttons on the Settings page should look like the radio button answer options in the scientific-computing-with-python course, with the white background and a light gray border? I'm assuming they would still stay side-by-side? Would there be a gap between each box, like we currently have with the On/Off button toggles?

**Comment by Vansh-Baghel** [comment]
Other than settings page which is: 
![Screenshot_2023_0418_104727](https://user-images.githubusercontent.com/103327712/232678020-00a85228-84d2-4c72-a34a-2c5bd6b7c17b.jpg)
Do we have any other page where do we have to replace?

**Comment by bbsmooth** [comment]
> I think the odin, python and the new math curriculum has radio inputs, and not only they have similar styles, they don't have fieldset and legend elements.

Yes, the questions on those pages need quite a bit of accessibility help. I will start working on bringing them up to speed. But this is a separate issue from the styling of the radio button toggles on the Settings page, which can be fixed now.

**Comment by Sboonny** [comment]
> you are saying that the toggle radio buttons on the Settings page should look like the radio button answer options in the scientific-computing-with-python course, with the white background and a light gray border? I'm assuming they would still stay side-by-side? Would there be a gap between each box, like we currently have with the On/Off button toggles?

I am in favor of the other way, we should have the exam buttons look like the setting one.

**Comment by Sboonny** [comment]
> Other than settings page which is: ![Screenshot_2023_0418_104727](https://user-images.githubusercontent.com/103327712/232678020-00a85228-84d2-4c72-a34a-2c5bd6b7c17b.jpg) Do we have any other page where do we have to replace?

This image shouldn't be possible after this commit https://github.com/freeCodeCamp/freeCodeCamp/pull/49664/commits/38bfc249632dd10bf222c94e0def18fd19af2af7

what am I missing? is browsers treating the styles differnetly?

**Comment by Anujvaid45** [comment]
hello @Sboonny 
So basically you want the exam buttons to look like radio buttons given in the settings page right?

**Comment by Sboonny** [comment]
Because of miscommunication, I have moved it to discussion until a certain plan is created.

**Comment by ahmadabdolsaheb** [comment]
> @Sboonny @ahmadabdolsaheb Just to be clear, you are saying that the toggle radio buttons on the Settings page should look like the radio button answer options in the scientific-computing-with-python course, with the white background and a light gray border?

> I'm assuming they would still stay side-by-side? Would there be a gap between each box, like we currently have with the On/Off button toggles?

Everything should stay the same, but the selected input should have a ring inside. 

<img width="32" alt="Screenshot 2023-04-18 at 3 56 46 PM" src="https://user-images.githubusercontent.com/4591597/232784742-7ea81815-97bc-45fe-8051-544b5bfe4a27.png">
<img width="26" alt="Screenshot 2023-04-18 at 3 57 03 PM" src="https://user-images.githubusercontent.com/4591597/232784789-7dde75be-0f9d-430d-9b43-ab32e1c457f1.png">

**Comment by Vansh-Baghel** [comment]
I've done this. OMW to raises a good PR!!
