### ISSUE TITLE
Convert JSON Data to HTML passes with incomplete sollution

### ISSUE THREAD

**Issue by andreiepure** [freeCodeCamp/freeCodeCamp#5004]
Challenge [Waypoint: Convert JSON Data to HTML](http://www.freecodecamp.com/challenges/waypoint-convert-json-data-to-html?solution=fccss%0A%20%20%24%28document%29.ready%28function%28%29%20%7B%0A%0A%20%20%20%20%24%28%22%23getMessage%22%29.on%28%22click%22%2C%20function%28%29%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON%28%22%2Fjson%2Fcats.json%22%2C%20function%28json%29%20%7B%0A%0A%20%20%20%20%20%20%20%20var%20html%20%3D%20%22%22%3B%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20json.forEach%28function%28val%29%7B%0A%20%20%20%20%20%20%20%20%20%20var%20key%20%3D%20Object.keys%28val%29%3B%0A%20%20%20%20%20%20%20%20%20%20console.log%28JSON.stringify%28key%29%29%3B%0A%20%20%20%20%20%20%20%20%7D%29%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24%28%22.message%22%29.html%28html%29%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D%29%3B%0A%20%20%20%20%7D%29%3B%0A%20%20%7D%29%3B%0Afcces%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.

Steps to repro:
1. Go to http://www.freecodecamp.com/challenges/waypoint-convert-json-data-to-html
2. paste the below snippet in the solving section the following code 
3. Click CTRL+ENTER

``` javascript
        json.forEach(function(val){
          var key = Object.keys(val);
          console.log(JSON.stringify(key));
        });
```

Expected: test should fail
Actual: test passes

From what I see, the test passes even with syntax problems...

My code:

``` html
<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json", function(json) {

        var html = "";
        // Only change code below this line.

        json.forEach(function(val){
          var key = Object.keys(val);
          console.log(JSON.stringify(key));
        });

        // Only change code above this line.

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
   </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

**Comment by benschac** [comment]
I thought FCC only supported Chrome?

**Comment by DDaems** [comment]
> Then, let's loop through our JSON, adding more HTML to that variable. When the loop is finished, we'll render it.

I think your test should pass, but only if the returned data would be passed in the `html` var.
I tested your code a bit more, to see how much i could reduce. And apperently i only need
```
// Only change code below this line.
json.forEach
// Only change code above this line.
```
to pass the test. This assert should be altered to check against the returned value.
Altho the goal of this waypoint just seems to be a copy/paste one. Maybe we should alter it a little bit. To actually make it a challenge thats worthwhile completing.


@benschac FCC goal is to support as many browsers as possible, certainly the mainstream ones: Chrome, FF, Safari, Edge

**Comment by SaintPeter** [comment]
Confirmed.  The issue is that we don't have the infrastructure in place yet to properly test asynchronous events.  At this time we're basically just checking the editor for certain strings.

All of the jQuery lessons need better, more comprehensive tests.

**Comment by chiptus** [comment]
How can I start to work on this? Are we waiting for the infrastructure? Or is the solution would be building it?

**Comment by yzhbankov** [comment]
Does anybody work on this issue? Can i work on it?

**Comment by erictleung** [comment]
@chiptus @yzhbankov I think we're still waiting on the infrastructure to test async actions. The most you can do at this point, as pointed out above, is to just check they are using some code in the editor. However, there are many variants of implementing the code so trying to regex all answers might be difficult.

Also, note that this challenge has been changed in the `staging` branch. You can see the changes [here](http://beta.freecodecamp.com/en/challenges/json-apis-and-ajax/convert-json-data-to-html) on the beta site.
