### ISSUE TITLE
Question URL at responsive-web-design seems inconsistent

### ISSUE THREAD

**Issue by Vansh-Baghel** [freeCodeCamp/freeCodeCamp#50068]
### Describe the Issue

* I am using gitpod and running the repository using localhost.
* Facing issue in url that the following shared section redirects to wrong question from 1 till 44th question
* Not facing this issue at official website url : https://www.freecodecamp.org/learn/2022/responsive-web-design/ , but just opened this issue if its a bug for others as well.

### Affected Page

 `/learn/2022/responsive-web-design/` url of localhost

### Steps to Reproduce

1. Go to 'https://8000-[YOUR_USERNAME]-freecodecam-a5iepuqc08u.ws-us94.gitpod.io/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app'
2. Scroll down to '**Courses**'
4. Visit any question before 45 ie from 1 to 44.

### Expected behavior

* Question 1 should redirect to question 1, now its going to 44th question's url.
* From question 2 till 44, its redirecting to n - 1th question ie 2nd is opening question 1 and so on.

### Screenshots

Images on hover to show the url

![Screenshot 2023-04-15 155141](https://user-images.githubusercontent.com/103327712/232208737-7a7531b2-3d79-450d-8ece-297200959a0c.png)
![image](https://user-images.githubusercontent.com/103327712/232208814-aa7cf20a-1742-4b0f-bac2-98129ca6302e.png)
![Screenshot 2023-04-15 160334](https://user-images.githubusercontent.com/103327712/232208971-1a4a844f-2e20-4b97-add0-c52ab4a56df3.png)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

* Facing this issue only on localhost and not on official url. I didn't make any changes which could lead to such behaviour.

**Comment by Sboonny** [comment]
I couldn't duplicate this on gitpod on my end, can you make sure that you are at latest commit in the upstream/main.

**Comment by Vansh-Baghel** [comment]
@Sboonny Hey you could close this issue, as I am not facing the same issue again. Not sure why I was having such bug back then.
