### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue 

### ISSUE THREAD

**Issue by coderHacker** [FreeCodeCamp/freecodecamp#501]
Please tell us in detail here how we can make this challenge better.

when i have completed this waypoint, it goes direct to "zipline-build-a-pomodoro-clock", could you please lookat this.

**Comment by QuincyLarson** [comment]
@coderHacker I think we've fixed this issue. Thank you for submitting this!
