### ISSUE TITLE
Map and Curent Placement Don't Match.

### ISSUE THREAD

**Issue by vgibson15** [FreeCodeCamp/FreeCodeCamp#5010]
My map location and what activities I have completed don't match up. This is very fustrating I dont want to spend 10 - 15 trying to just enter through several steps to find what activity I haven't done. Is there another to get to the place I actually left off without having to go through several tasks. This has happened to me the last 2 times I've used the program. Perhaps, it's all the updates you are doing

Challenge [Waypoint: Use Hex Code to Color Elements White](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-white) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: #FFFFFF;
  }
</style>

```

**Comment by AlexMogoryan** [comment]
dont mention backgound, at list i get it rite like this

![screenshot 1](https://cloud.githubusercontent.com/assets/15803277/11584385/a268f234-9a74-11e5-8416-afc1d12682d5.png)

**Comment by bugron** [comment]
@AlexMogoryan thanks for posting this issue!
Վստա՞հ եք, որ սրանք նոր վարժություններ չեն, նոր վարժությունների թիվն արագ աճում է ու քարտեզի վրա դրանք ցուց են տրված որպես դեռ չանցած:
Are you sure these not completed challenges aren't new challenges (our curriculum grows in in time)?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by DDaems** [comment]
@vgibson15  'learn' will automaticly show the challenge last visited.If your doing challenges all over the place in no direct order. Use Map and the visual indenticators to find out wich challenges you didn't do. 

@AlexMogoryan You shouldn't be able to pass the test like that so thanks for reporting.
```
#ffffff
```
Actually passes the test too.
I'll send in a PR to fix this

**Comment by marhyorh** [comment]
@vgibson15 i think there's a problem with mozilla for now but if you want to continue from where you left off, click the learn button on the navbar
