### ISSUE TITLE
Justify readme text 

### ISSUE THREAD

**Issue by caioreius** [freeCodeCamp/freeCodeCamp#50103]
### Describe the Issue

I'm trying to put the text all formatted in the README, I believe it's more organized and better to see, I also added a button to go back to the beginning of the README, it makes it easier to navigate the README.

### Affected Page

README.md

### Steps to Reproduce

There are no steps.

### Recommended fix or suggestions

There are no steps.

**Comment by bbsmooth** [comment]
[WCAG SC 1.4.8](https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation) specifically requires that text not be justified. From the understanding document:

> People with certain cognitive disabilities have problems reading text that is both left and right justified. The uneven spacing between words in fully justified text can cause "rivers of white" space to run down the page making reading difficult and in some cases impossible. Text justification can also cause words to be spaced closely together, so that it is difficult for them to locate word boundaries. 

Granted, this SC is AAA and so we technically don't have to meet it, but it's an easy one to meet and there is no reason not to abide by it.

**Comment by caioreius** [comment]
I understood. Thank you.
