### ISSUE TITLE
Preview Saga is called twice when loading the editor

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50113]
While using the editor in any of the step challenge, you will have different layout mobile and desktop, we are using different components for these layouts.

Pros:
- the editor isn't supported for mobile, so we can have somewhat of a support for it.
- the styling and layout will become easier.

Cons:
- loading the same Redux actions twice. (adding console log, to preview sage here will show twice)
- losing the state when camper change the layout manually, it act similar to refreshing the page (lose focus, maybe reimport components, and such)

----

I think it's better overall if that section is deleted.

**Comment by Sembauke** [comment]
I am not sure what you mean by deleting the mobile layout. It does seem pretty useful to me.

Do you mean that both the mobile layout and the web layout are loaded depending on the screen size while the user is already present on the site?

**Comment by ShaunSHamilton** [comment]
> the preview saga is called twice whenever the preview is mounted.

Are you sure this is not just because you are in development mode? Does this happen for a production build?

**Comment by Sboonny** [comment]
I don't know how to test it in production, redux dev tools doesn't show anything on

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-4

**Comment by ojeytonwilliams** [comment]
@Sboonny one option is to build the client locally. That should enable redux dev tools. Just to be on the safe side, I'd add the console log you suggested, too.

**Comment by Sboonny** [comment]
It has the console log run three time in built environment.

Thanks to Oliver help, I was able to run it by these commands 

```console
pnpm run build
cd client
pnpm dlx serve -p 8000 public
```

**Comment by smithbinky** [comment]
> I am not sure what you mean by deleting the mobile layout. It does seem pretty useful to me.
> 
> Do you mean that both the mobile layout and the web layout are loaded depending on the screen size while the user is already present on the site?

just seen will look into.sje.l
