### ISSUE TITLE
Answer seems right but it's not the solution?

### ISSUE THREAD

**Issue by Pistacue** [FreeCodeCamp/FreeCodeCamp#5016]
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays?solution=function%20largestOfFour(arr)%20%7B%0A%20%20var%20b%20%3D%20arr.length%3B%0A%20%20var%20Z%20%3D%20%5B%5D%3B%0A%20%20%0A%20%0A%20%20%20%20for(i%20%3D%200%3Bi%20%3C%20b%3Bi%2B%2B)%7B%0A%20%20%20%20var%20r2%20%3D%20%5B%5D%3B%0A%20%20%20%20var%20r1%20%3D%20arr.shift()%3B%0A%20%20%20%20var%20z%20%3D%20r1.length%3B%0A%20%20%20%0A%20%20%20%20for(p%3D0%3Bp%3Cz%3Bp%2B%2B)%7B%0A%20%20%20%20%20%20if(r1%5Bp%5D%20%3E%20r2)%7B%0A%20%20%20%20%20%20r2%20%3D%20r1%5Bp%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%2F*%20%0A%20%20for(p%20%3D%200%3Bp%20%3C%20z%3Bp%2B%2B)%7B%0A%20%20%20%20%20%20var%20g%20%3D%20r1.shift()%3B%0A%20%20%20%20%20%20if(g%20%3E%20r2)%7B%0A%20%20%20%20%20%20%20%20r2.shift()%3B%0A%20%20%20%20%20%20%20%20r2.unshift(g)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20*%2F%20%20%20%20%20%0A%20%20%20%20Z.push(r2)%3B%20%0A%20%7D%0A%0A%20%20return%20Z%3B%20%0A%7D%0A%0AlargestOfFour(%5B%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I think i found a solution that doesn't get approved, maybe someone can tell me why? The first code is working right, but the second code is not letting me through even my answer seems good.
Here is screenshot: http://i.imgur.com/MdVwjsm.png
My code:
```javascript
function largestOfFour(arr) {
  var b = arr.length;
  var Z = []; 
    for(i = 0;i < b;i++){
      var r2 = [];
      var r1 = arr.shift();
      var z = r1.length;
   
      for(p=0;p<z;p++){
        if(r1[p] > r2){
        r2 = r1[p];
      }
    }
    
    Z.push(r2); 
 }
  return Z; 
}

largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

Here is the second code
```javascript
function largestOfFour(arr) {
  var b = arr.length;
  var Z = []; 
    for(i = 0;i < b;i++){
    var r2 = [];
    var r1 = arr.shift();
    var z = r1.length;

      for(p = 0;p < z;p++){
      var g = r1.shift();
      if(g > r2){
        r2.shift();
        r2.unshift(g);
      }
    }

    Z.push(r2); 
 }
  return Z; 
}

largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by DDaems** [comment]
Your indeed returning the correct values, but your are pushing arrays onto a array. Wich creates a multi-dimentional array. And your expected to just return a normal one.
`[1,2,3,4,..] =! [[1],[2],[3],[...]]`

:+1: for the solution you created.
you could convert to string and back to array before returning the value :-)

**Comment by DDaems** [comment]
Your indeed returning the correct values, but your are pushing arrays onto a array. Wich creates a multi-dimentional array. And your expected to just return a normal one.
`[1,2,3,4,..] =! [[1],[2],[3],[...]]`

:+1: for the solution you created.
you could convert to string and back to array before returning the value :-)

**Comment by DDaems** [comment]
Your indeed returning the correct values, but your are pushing arrays onto a array. Wich creates a multi-dimentional array. And your expected to just return a normal one.
`[1,2,3,4,..] =! [[1],[2],[3],[...]]`

:+1: for the solution you created.
you could convert to string and back to array before returning the value :-)

**Comment by Pistacue** [comment]
@DDaems Thanks a lot, it feels good to know why it wasn't working :smile: 

Your answer also helped me with Bonfire: Chunky Monkey, so double thanks! :+1:

**Comment by bugron** [comment]
Then closing this issue as resolved, Feel free to reopen if you still experience problems, thanks.
