### ISSUE TITLE
Change the action name from previewMounted to updatePreview in show file

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50169]
The action `previewMounted` follow the same name as the prop in the `Preview` component, which mean that the action can be passed to the `Preview`, while it need the challenge data to trigger the action.

Optional, for more context on the issue, please read https://github.com/freeCodeCamp/freeCodeCamp/issues/49886, luckily Oliver solved it in this PR #50108.

To make it harder to create the same issue, we can rename the action to `updatePreview`, like how we are doing with nav-links.tsx

here is the example
```ts
import { hardGoTo as navigate, openSignoutModal } from '../../../redux/actions';
```

---

so we can do the same with the `previewMounted` action and name it to `updatePreview` or something, in the [show.tsx](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/classic/show.tsx).

the code should look like this 

```ts
import {
  cancelTests,
  challengeMounted,
  createFiles,
  executeChallenge,
  initConsole,
  initTests,
  previewMounted as updatePreview,
  updateChallengeMeta,
  openModal,
  setEditorFocusability,
  setIsAdvancing
} from '../redux/actions';
```

and the action in the dispatch will be changed to this,

```ts
const mapDispatchToProps = (dispatch: Dispatch) =>
  bindActionCreators(
    {
      createFiles,
      initConsole,
      initTests,
      updateChallengeMeta,
      challengeMounted,
      executeChallenge,
      cancelTests,
      updatePreview,
      openModal,
      setEditorFocusability,
      setIsAdvancing
    },
    dispatch
  );
```

---

## additional context

Doing this will provide analytic typing that was missing by having the action, so if you try to revert #50108 as a test, TypeScript will warn you

**Comment by haddercone** [comment]
HI @Sboonny . I'm a first time contributor and would like to work on this issue. As you've mentioned in the issue that we need to change `previewMounted` to `updatePreview` in import statement and in `mapDispatchToProps`.
if my understanding is correct then, i would like to proceed with this issue.
Thanks :)

**Comment by Sboonny** [comment]
Go for it

**Comment by Sboonny** [comment]
The issue seems to require too much effort for rare edge cases, which can be spent on making the file typescript instead. I am closing it.
