### ISSUE TITLE
feature flags for client

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#50171]
### Problem

For situations where we would like to disable sections of curricula, or show notes/warnings to Campers that sections are down, it would be nice to have feature-flags so that the whole client + server do not need to be re-built.

### Suggested Tools

- _I have no experience with any_

### Alternatives

We can create our own, but this would be time consuming, and would likely need to be a separate application, as it would need to be hot-reloadable.

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb If I correctly recall, you have/had done some research into adding feature flags and the like?

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton I don't think this is compatible with our current approach (i.e. building the client from scratch each time we want to deploy). However, I like the idea and it's something that Next can easily handle.

**Comment by ShaunSHamilton** [comment]
Whilst researching, I realised [GrowthBook](https://docs.growthbook.io/overview) sounds familiar... 🤦‍♂️

**Comment by moT01** [comment]
I think we're safe to close this since we have this implemented. Let me know if I am mistaken.
