### ISSUE TITLE
Encountered an error when trying to import the exported conversation file

### ISSUE THREAD

**Issue by hanif2061400** [freeCodeCamp/freeCodeCamp#50174]
Encountered an error when trying to import the exported conversation file
![c933e0621783adff71f6e8846d1b9e9](https://user-images.githubusercontent.com/8436305/234036464-83485738-16ee-4d5c-b385-86fc54762972.png)

_Originally posted by @baichisong in https://github.com/mckaywrigley/chatbot-ui/issues/642_

**Comment by Sboonny** [comment]
I am closing this issue because as far as I can tell, this isn't related to freeCodeCamp
