### ISSUE TITLE
Record Collection still could be clearer

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#50182]
### Describe the Issue

This part is still tripping people up

> If prop is tracks and value isn't an empty string, add the value to the end of the album's tracks array. You need to create this array first if the album does not have a tracks property.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection

### Your code

Usually one piece or another gets lost:

```javascript
function updateRecords(records, id, prop, value) {
  if (value === "") {
     delete records[id][prop];
  } else if (prop !== "tracks" && value !== "") {
    records [id][prop] = value;
  } else if (prop === "tracks" &&  value !== "" && records[id].hasOwnProperty ("tracks") === false){
    records [id][prop] = [value];
  }
  return records;
} 
```

### Expected behavior

Maybe this is clearer

> If `prop` is `tracks` and `value` isn't an empty string, update the album's `tracks` array. You need to create this array first if the album does not have a `tracks` property. Then, add the `value` to the end of the album's `tracks` array.

Side note - I still don't love the fact that we say `tracks` like a variable instead of `"tracks"` like a string literal. I think that's confusing here. (I know, I know, the style guide hates "s)

### System

All

**Comment by jeremylt** [comment]
I'm still not clear on the reason why string literals in inline code blocks are forbidden by the style guide since it makes the instructions less clear in this case. @naomi-lgbt do you have some context?

**Comment by naomi-lgbt** [comment]
I don't remember the full reason, only that it was a decision made as part of our i18n efforts. 

We reference a discussion in [this old PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/40838) but I can't for the life of me find where that discussion is.
