### ISSUE TITLE
Bonfire: Check for Palindromes The Final input is wrong palindrome("0_0 (: /-\ :) 0-0")

### ISSUE THREAD

**Issue by rajendrach** [FreeCodeCamp/FreeCodeCamp#5019]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%0A%20%20console.log(str)%3B%0A%20%20%20str%20%3D%20str.replace(%2F%2C%2Fg%2C%20%22%22)%3B%0A%20%20console.log(str)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C.%2Fg%2C%20%27%20%27)%3B%0A%20%20console.log(str)%3B%0A%20%20str%20%3D%20str.replace(%2F%20%2B%2Fg%2C%20%22%22)%3B%0A%20%20console.log(str)%3B%0A%20%20str%20%3D%20str.replace(%2F_%2Fg%2C%20%27-%27)%3B%0A%20%20console.log(str)%3B%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20if%20(str%20%3D%3D%3D%20str.split(%22%22).reverse().join(%22%22))%7B%0A%20%20%20%20return%20true%3B%0A%7Delse%7B%0A%20%20return%20false%3B%0A%7D%0A%20%20%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.

Please describe how to reproduce this issue, and include links to screenshots if possible.

<b>The Final Input is supposed to be palindrome("0_0 (: /-\ :) 0-0") but it is passing palindrome("0_0 (: /- :) 0-0")
Which is not a palindrome but it is checking for true, but my code is returning false, for your reference added the console at every debug point and attached the console for your reference.
Thanks </b>
![capture](https://cloud.githubusercontent.com/assets/12751421/11595895/7760ffd4-9a77-11e5-84c1-fbc3ffe82d6e.PNG)

My code:
```javascript
function palindrome(str) {
  // Good luck!
 
  console.log(str);
   str = str.replace(/,/g, "");
  console.log(str);
  str = str.replace(/\./g, ' ');
  console.log(str);
  str = str.replace(/ +/g, "");
  console.log(str);
  str = str.replace(/_/g, '-');
  console.log(str);
  str = str.toLowerCase();
  if (str === str.split("").reverse().join("")){
    return true;
}else{
  return false;
}
  
}



palindrome("eye");

```

**Comment by ltegman** [comment]
This is a palindrome regardless, because the challenge asks you to remove all non-alphanumeric characters. Once you've done this the only thing left is `0000`, which is a palindrome :smile:

Thanks and happy coding!

**Comment by vjford1962** [comment]
For my .replace I originally had:
.replace(/\W|\s/g,'')
This didn't get rid of the underscore, and kept the evaluation from being true.
All I did was add an "OR" as follows, to search for the underscore and replace with ' '
I don't know if there's another way to do it, but it worked for me.
Note next to my s, I put OR Underscore ------ |_
The final replace was this, and it worked.
.replace(/\W|\s|_/g,'') 

Good luck, and remember if you get stuck, Google it.
