### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/freecodecamp#502]
Apparently the input type="text" doesn't work? I've tried to add a form to it as well... Is this a bug?

**Comment by QuincyLarson** [comment]
@Stiino0 I wasn't able to reproduce this. Which browser/operating system were you using? Please verify that this still isn't working on your end. Thank you for helping us debug this!

**Comment by denmch** [comment]
I had this happen on my iPad earlier and thought it was isolated there, but this issue made me suspect it was a Safari issue. I can confirm having just tried in Safari 8 on OSX. Before even attempting a solution the test output reads as follows:

> Syntax error, unrecognized expression

This persists despite a valid solution and you cannot pass.

**Comment by Stiino0** [comment]
Hi,

I had this happen on Windows 7 64bit, latest version/build of Firefox (not on machine right now so don't know what version that is) had the exact same message like you, Den!

I'll test Tomorrow and report back to you, should you still not be able to reproduce the issue.

Good night!

Verstuurd vanaf mijn iPhone

**Comment by Stiino0** [comment]
Didn't happen anymore, I've successfully been able to complete the waypoint!

Thanks!

Subject: Re: [freecodecamp] Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue  (#502)
From: sten77@hotmail.com
Date: Tue, 26 May 2015 23:21:56 +0200
To: reply@reply.github.com
CC: freecodecamp@noreply.github.com

Hi,
I had this happen on Windows 7 64bit, latest version/build of Firefox (not on machine right now so don't know what version that is) had the exact same message like you, Den!
I'll test Tomorrow and report back to you, should you still not be able to reproduce the issue.
Good night!

Verstuurd vanaf mijn iPhone
Op 26-mei-2015 om 20:40 heeft Den McHenry <notifications@github.com> het volgende geschreven:

I had this happen on my iPad earlier and thought it was isolated there, but this issue made me suspect it was a Safari issue. I can confirm having just tried in Safari 8 on OSX. Before even attempting a solution the test output reads as follows:



Syntax error, unrecognized expression



This persists despite a valid solution and you cannot pass.
