### ISSUE TITLE
Variable names in For In Seed Code

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#50204]
### Describe the Issue

This seed code can lead to a bit of confusion because the global variable name and parameter name are pretty similar

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for---in-statement

### Your code

```
const users = {
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}

function countOnline(usersObj) {
  // Only change code below this line

  // Only change code above this line
}

console.log(countOnline(users));
```

### Expected behavior

What about
```
const myFriends = {
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}

function countOnline(allUsers) {
  // Only change code below this line

  // Only change code above this line
}

console.log(countOnline(myFriends));
```
`allUsers` isn't my favorite if someone has another idea. I just don't like `varNameWithType` when the type isn't strictly needed.

### System

All

**Comment by unnatijadhav** [comment]
@jeremylt can I work on this if anyone is not working?

**Comment by jeremylt** [comment]
This issue isn't ready for PRs yet

**Comment by gikf** [comment]
One idea for naming:
`users` -> `example` or `exampleUsers`
`usersObj` -> `users`

**Comment by jeremylt** [comment]
I went with something other than `users` because

1) that's the example

2) at least one learner has has said `user in users` was a little hard to grok at first

We could change the example (and maybe we should in light of 2?)

**Comment by lasjorg** [comment]
I can appreciate the idea behind it but I don't think the names should imply they are different things, `friends` and `users` are not the same thing.

Wouldn't just changing to `allUsers` for the parameter and leaving the object name as is work?

`function countOnline(allUsers)`

`user in allUsers`

**Comment by jeremylt** [comment]
We can use that as the parameter name; I like it better than `usesObj`.

This still doesn't fully handle the user complaint though.

```javascript
const users = {
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}

function countOnline(allUsers) {
  // Only change code below this line

  // Only change code above this line
}

console.log(countOnline(users));
```

I see two problems

1) `usersObj` is a really awkward variable name. Swapping to `allUsers` fixes this.

2) Given the example, its an easy bug for users to write `user in users` instead of the intended `user in allUsers`. Not sure if we want to address this or ignore this. Changing the global object name seems to be the best way to address this.

**Comment by jeremylt** [comment]
Maybe what really needs to be done is to change the example to something else, like maybe `food in refrigerator` or something like that?

**Comment by lasjorg** [comment]
Not sure how I feel about the parameter name but it might work.

```
const allUsers = {
  Alan: {
    online: false,
  },
  Jeff: {
    online: true,
  },
  Sarah: {
    online: false,
  },
};

function countOnline(usesToCount) {
  let count = 0;
  for (const user in usesToCount) {
    if (usesToCount[user].online) count++;
  }
  return count;
}

console.log(countOnline(allUsers));
```

**Comment by jeremylt** [comment]
I like the direction.

How about

Instructions
---

Sometimes you need to iterate through all the keys within an object. You can use a <dfn>for...in</dfn> loop to do this. The <dfn>for...in</dfn> loop looks like:

```javascript
const refrigerator = {
  'milk': 1,
  'eggs': 12,
};

for (const food in refrigerator) {
  console.log(food);
}
```

This code logs `milk`  and `eggs`, with each value on its own line.

We defined the variable `food` in the loop head and this variable was set to each of the object's keys on each iteration, resulting in each food's name being printed to the console.

---

We've defined a function `countOnline` which accepts one argument, `allUsers`. Use a <dfn>for...in</dfn> statement inside this function to loop through the `allUsers` object and return the number of users whose online property is set to `true`. An example of an object which could be passed to `countOnline` is shown below. Each user will have an `online` property set to either `true` or `false`.

Seed Code
---

```javascript
const users = {
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}

function countOnline(allUsers) {
  // Only change code below this line

  // Only change code above this line
}

console.log(countOnline(users));
```

---

I think this way we use your better parameter name and we swap the example for something that doesn't lead the learner to the `user in users` bug.

**Comment by lasjorg** [comment]
I think it looks good.

---

As an aside, if we are documenting how `for...in` works we should show how to access the properties on the object (in the example).

I know we have taught how to use variables with objects and making them bridge the gap might force the learner to think about it more. But it feels a little wrong to me to teach `for...in` without actually showing how to use it.

**Comment by jeremylt** [comment]
Small tweak for that:

Instructions
---

Sometimes you need to iterate through all the keys within an object. You can use a <dfn>for...in</dfn> loop to do this. The <dfn>for...in</dfn> loop looks like:

```javascript
const refrigerator = {
  'milk': 1,
  'eggs': 12,
};

for (const food in refrigerator) {
  console.log(food, refrigerator[food]);
}
```

This code logs `milk 1`  and `eggs 12`, with each key-value pair on its own line.

We defined the variable `food` in the loop head and this variable was set to each of the object's keys on each iteration, resulting in each food's name being printed to the console.

---

We've defined a function `countOnline` which accepts one argument, `allUsers`. Use a <dfn>for...in</dfn> statement inside this function to loop through the `allUsers` object and return the number of users whose online property is set to `true`. An example of an object which could be passed to `countOnline` is shown below. Each user will have an `online` property set to either `true` or `false`.

Seed Code
---

```javascript
const users = {
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}

function countOnline(allUsers) {
  // Only change code below this line

  // Only change code above this line
}

console.log(countOnline(users));
```

---

I think this way we use your better parameter name and we swap the example for something that doesn't lead the learner to the `user in users` bug.
