### ISSUE TITLE
The test is not working how should

### ISSUE THREAD

**Issue by migueljo** [FreeCodeCamp/FreeCodeCamp#5020]
Challenge [Waypoint: Write Reusable JavaScript with Functions](http://www.freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions?solution=var%20a%20%3D%204%3B%0Avar%20b%20%3D%205%3B%0A%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20return%20a%20%2B%20b%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AourFunction(a%2C%20b)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0Aif(typeof%20myFunction%20!%3D%3D%20%22undefined%22)%7B%0Avar%20f%3DmyFunction(a%2Cb)%3B%0A(function()%7Breturn%20f%3B%7D)()%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var a = 4;
var b = 5;

function ourFunction(a, b) {
  return a + b;
}

// Only change code below this line.

ourFunction(a, b);

// Only change code above this line.

if(typeof myFunction !== "undefined"){
var f=myFunction(a,b);
(function(){return f;})();
}

```

**Comment by gasperno** [comment]
> Create and call a function called myFunction that returns the sum of a and b.

The last sentence in the description. 
@migueljo Please use chatroom before creating an issue here.

**Comment by BerkeleyTrue** [comment]
@gasperno Thanks for you're help

Happy Coding!

**Comment by migueljo** [comment]
ohh, yes you're right, I'm sorry it was my bad
