### ISSUE TITLE
Full stack certification rendering oddly

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#50212]
...I am pretty sure the Full Stack Cert should not show "Solution":
<img width="670" alt="image" src="https://user-images.githubusercontent.com/51722130/235151537-94846fe8-c48b-40a3-b524-b277d512d39b.png">

_Originally posted by @ShaunSHamilton in https://github.com/freeCodeCamp/freeCodeCamp/issues/50206#issuecomment-1527511751_

**Comment by ojeytonwilliams** [comment]
I like the second mock - no unnecessary verbiage.

**Comment by bbsmooth** [comment]
If we are going to continue to code this list as a table then it would be cool if we kept a table header in there. If you don't want the header to be visible on the page then you can wrap the text in as `span` put the `sr-only` class on it.
