### ISSUE TITLE
Put ui-components into hiatus

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50237]
While working on adding small spacing changes in this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/50208, that is lost when linking the ui-components library, one of the changes is in the toggle button in our setting page.

![image](https://user-images.githubusercontent.com/88248797/235442998-28e70152-b216-4e4d-8351-de8950f9ba81.png)

Unfortunately, I tried to test the ToggleButton in the ui-components library, and wondering if the change can be fixed by simple swap to the components.

But the results are worse, and now we have to sort the issue in two different issues in two places.

![image](https://user-images.githubusercontent.com/88248797/235443176-caa110a4-5e4a-477d-8290-e888a5240f0b.png)

Just because I don't want the discussion to derail, although there are small issues like one in the `Button` components, different button weight and wrong sizes. There are situations which the components, even with "tests" and "storybook", don't produce a good alternative to the one used in bootstrap.

my point is that the workflow aren't producing a good alternative and because of how the ui-components structured, we can't package only one component and leave the rest, we have to take the good and the bad of the ui-components, and the amount of effort put into creating test and storybook for it to have a chance to produce a component that works in the story but in the repo, which is failing, is heartbreaking.

----

This is why, I think, we should do this on the reverse order:

- Create a quick components in learn, and to unblock the React 17 quickly. we can copy the code in ui-components, but because we aren't taking all the components and all the styles, we are fixing one issue at a time.
- Check them in real working environment.
- Remove bootstrap.
- Move the components that are used in multiple repos into the ui-components/component-name package.
- Create a copy of the environment from the repo into the storybook inside that package.

---

I am opening the issue, because I think that the issue in the ui-component may take at least a week and we can create a component in learn at most an hour

**Comment by ahmadabdolsaheb** [comment]
I am open to unblocking the react 17 without the component library; however, I think we should move forward with the current plan for the following reasons.
- The presets from the current setup of the component library are adding styles that affect the learn UI. That issue could be resolved by customizing the base config in tailwind and making sure we are using similar presets with bootstrap 3. 
- Building components in learn while bootstrap is connected is a short lived solution. Once bootstrap styles and presets are removed from learn, we would be back at square one since presentation of the in learn components will be dramatically effected.
- The number of components added can be adjusted by commenting out the components that need further development from src/index.ts.

**Comment by Sboonny** [comment]
This PR focus isn't about the styles, it's about we have started at the wrong square one, yes building components in learn while bootstrap is connected is short lived solution, but it will provide a better square one than the current one.

Although the focus weren't in the styles and I don't want to discuss it, but let's discuss it to hammer my point, for example: 

In this commit https://github.com/freeCodeCamp/freeCodeCamp/pull/50208/commits/41510a57e84db453b90469bbec3102323b02c3f8, I have added the missing base styles that are missing, everything works fine in the next commit https://github.com/freeCodeCamp/freeCodeCamp/pull/50208/commits/44c08166594d6aa00b3d22155b7dd0c98d7d3551#diff-307c58367ced3d03a9a2c0a95931af44760dc85ddbff7f974ad663275f56acba and everyone is happy, except the one who creates the commits, without accounting for any component, so the package is only tailwind and its styles, they have to do the following:

- find the issue, if they are lucky to notice it.
- come up with the missing styles, if they know what is missing.
- Build the package.
- copy the base.css.
- paste it in the client.
- import it in the client.
- test if your change is doing this needed.
- - if it's doing what is needed, you have fixed the issue.
- - if it isn't, repeat from the second step forward, which is an distressing experience.

Note: I am not accounting for linking the package because to find the issue you will need to use the package.

**Comment by Sboonny** [comment]
So yes, I am asking us to take the easy route build the component in the learn, add tailwind to learn, change tailwind in learn, then build packages for every components we need to use.

This or start finding another way to make the change I do in the ui-component reflect without the need to build, copy, paste, and import.

I want to make a change, test the change, then decide if I need to update or is it enough.

**Comment by ahmadabdolsaheb** [comment]
To my understanding there are two issues that need to be fixed:

1) Styles interference: tailwind could be configured to remove its presets (preflight). We would need to find the preset styles used in bootstrap 3 and include them in storybook so the component is developed under a similar environment as learn.

2) Hot reloading for components imported from ui-library in learn: This could be achieved by adjusting the scripts in packapge.json. Additionally, adding the presets to storybook might be sufficient.

**Comment by Sboonny** [comment]
I couldn't make it work after:

- disabling [preflight](https://tailwindcss.com/docs/preflight).
- add bootstrap styles to the base.
- change the variables name to reflect the current variables name in the ui-components.


All that is left is deleting base, and "add" the missing styles from the components library.

**Comment by ahmadabdolsaheb** [comment]
only the normalize.css of the bootstrap styles should be added. I will take a look.

**Comment by ahmadabdolsaheb** [comment]
Here is the contents of the minified bootstrap.min.css:
1.  normalize.css v3.0.3 (current version is 8)
2. element selectors 
3. bootstrap class name selectors

Here is what I think we should do to make the new components that are used in learn look like storybook.
1. include a normalize v3.0.3(200 lines) to  either the storybook preview or the base file.
2. add the applicable element selectors to the `tailwind.config.js`

**Comment by Sboonny** [comment]
What happens when you remove the 200 lines from the bootstrap file?

**Comment by ahmadabdolsaheb** [comment]
If we include the normalize v3.0.3 in our base, nothing should happen.
Otherwise, you would get less browser consistency.

**Comment by Sboonny** [comment]
I am confused, where is normalize coming from?

**Comment by ahmadabdolsaheb** [comment]
Sounds like a plan.
