### ISSUE TITLE
Create Exam Environment (backend)

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#50253]
We want to create an exam environment where campers can complete and pass an exam to earn certifications. This is a starting point for how we might be able to do some (mostly backend) of it - just rough thoughts at the moment.

We can put the questions in a database:
```
Exams <collection> {
  title: "X Certification",
  questions: [
    {
      question: "How are you?",
      wrong_answers: ["good", "okay", "poor", "terrible", "not sure", "other"],
      correct_answer: "great"
    },
    ...more questions
  ]
}
```

Each question should have more answers than will show up in the exam so we can randomly generate the answers that will show up. e.g. the above question will have maybe four options displayed (including the correct answer) when the question is shown.

Each exam in the database will have more questions than the exam consists of so we can randomly get 50 of the 100 available questions or something.

Then we can generate an exam on our server:
```
.get('/generate-exam') {
  // get all questions for "X Certification" from database;
  const exam = [];
  // while exam.length < number_of_questions_in_exam
    const newQuestion = {
      "question": randomQuestion
      "answers": [wrong_answer, wrong_answer, correct_answer, wrong_answer] // random answers, random order
    }
    exam.push(newQuestion);
  return exam to client;
}
```

The purpose of putting these in the database and creating the exam on the server is so the client doesn't know the correct answers.

`<CLIENT STUFF HERE>`

Then the client can send the completed exam back to the server where we can check it - the shape would be something like:
```
exam_from_client = {
  title: "X Certification",
  time_taken_to_complete: 19:30,
  questions: [
    {
      question: "How are you?",
      camper_answer: "good"
    },
    ...rest of questions/answers
  ]
}
```
and the endpoint:
```
.post('/check-exam') {
  // get all questions for "X Certification" from database;
  const examResult = [];
  // loop through camper exam and compare with correct answer
    const questionResult = {
      question,
      camperAnswer,
      correct: boolean
    }
    examResult.push(questionResult)
    
    // store exam result in User object?
  return examResult to client;
}
```

More client:
Then we can display the campers result. e.g. `90% Correct, You Passed!` with the list of the questions, their answers, and if it was correct or not.

Some issues with this:
- how easy will we be able to translate the db info?
- if we change the correct answer in the database and camper tries to submit - it would cause issues

**Comment by ShaunSHamilton** [comment]
> we change the correct answer in the database

Why would we do this?

**Comment by moT01** [comment]
I dunno, maybe there was a mistake.

**Comment by Ankit5kumar** [comment]
Yes, we can create the enviorment for the exam.
So, What's your thought.
I can handle backend of it.
let me know.

**Comment by ugpec79** [comment]
The environment for the exam can be built and the issues mentioned in the request can be handled.
I can handle the backend portion so if you are interested let me know

**Comment by Nirajn2311** [comment]
> if we change the correct answer in the database and camper tries to submit - it would cause issues

If we consider that a questions answer is mistakenly marked then we would have to store the users responses(or their latest or best attempt) so as to calculate the score on each load. This way the score gets updated if an answer is changed in the future.

But I think we can prevent wrong marking of answers by cross verifying them 2-3 times before storing them.
