### ISSUE TITLE
[Wiki] Campsite list: Parana entry under Argentina doesn't belong there

### ISSUE THREAD

**Issue by junrrein** [FreeCodeCamp/FreeCodeCamp#5025]
In https://github.com/FreeCodeCamp/freecodecamp/wiki/List-of-Free-Code-Camp-city-based-Campsites

The "Parana" entry under Argentina doesn't correspond to Parana city in Argentina, but to Apucarana, state of Parana, Brazil.

Apucarana is already mentioned under Brazil, so the Argentina entry should just be removed.

**Comment by BerkeleyTrue** [comment]
@junrrein Please open this issue up in the wiki repo https://github.com/freecodecamp/wiki/issues

Happy Coding!
