### ISSUE TITLE
Testing Objects for Properties: Be explicit about parameters

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#50255]
### Describe the Issue

A lot of campers do not understand they have to use the parameters and keep creating an object inside the function.

I know this is verbose.

> Modify the function `checkObj` to test if the object passed to the function parameter `obj` contains the specific property passed to the function parameter `checkProp`. If the property passed to `checkProp` is found on `obj`, return that property's value. If not, return "Not Found".

Not sure if we need an example that uses a function as well:

```
function hasProperty(object, property) {
  console.log(object.hasOwnProperty(property));
}

hasProperty({ top: "hat", bottom: "pants" }, "top");
```

We might also want to add a call to the function in the seed code

```
function checkObj(object, prop) {
  // Only change code below this line
  return "Change Me!";
  // Only change code above this line
}

console.log(checkObj({gift: "pony", pet: "kitten", bed: "sleigh"}, "gift"))
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties

### Your code

```



```

### Expected behavior

Campers should understand the function signature with its parameters and use them properly.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/search?expanded=true&q=Basic%20JavaScript%20-%20Testing%20Objects%20for%20Properties%20%23javascript

**Comment by lasjorg** [comment]
> Did we not recently spend time removing a bunch of these?

I think so but I'm not entirely sure why?

Seeing the function invocation can help in understanding the function definition. I think we are taking it for granted that they should look at the test output to see the invocation when in fact it is just the test status people look at.

> Might as well. But, this is after many lessons teaching/involving arguments and parameters.

Yes, they should know better by now, but they don't. In fact, not understanding parameters/arguments is an overall issue we see. It can not have been reinforced properly because we see it all the time.

My best guess is that too many of the challenges have premade functions and in not forcing people to write the function definition and invocation campers are left not to fully understand it.

**Comment by ShaunSHamilton** [comment]
> I think so but I'm not entirely sure why?

I think they were confusing Campers 🙃 . Campers would write their function as though only the example call was what was being tested - they hard-coded based on the seed example call.

**Comment by lasjorg** [comment]
I guess that makes some sense but that too points to the same issue. There is a disconnect between, writing and running the code.

**Comment by jeremylt** [comment]
I like the more explicit instructions. I'm not sure if the sample function call is the right band-aid for learners not understanding what a function call does?

**Comment by jeremylt** [comment]
There's a non-insignificant number of learners who don't seem to understand much about how a function call works. I'm not sure that giving more examples of the thing they don't understand will target the underlying reason of why they don't understand it. The problem is though, I'm not sure why the idea of a function call's arguments giving values to the parameters is such a mysterious idea for some of the learners.
