### ISSUE TITLE
browser challenge screen display issue

### ISSUE THREAD

**Issue by Naveedy** [FreeCodeCamp/FreeCodeCamp#5026]
i am not able to get complete display of screen on browser both chrome and firefox.
just display challenge detail frame on left and no code window frame is shown

any help how to fix this. thanks.
![screen](https://cloud.githubusercontent.com/assets/14126677/11608602/d9fc7664-9b8f-11e5-8941-a47c65ea5eea.png)

**Comment by gasperno** [comment]
Can you see what's in the console? You can open the console by Ctrl+Shift+I in Chrome. See if there are any errors and paste it here?

**Comment by ltegman** [comment]
I can not repro this. Do you get any errors in the console when this happens?

**Comment by Naveedy** [comment]
Thanks guys.
Got it resolved. My Hotspot shield settings were interfering. I was using challenges earlier on my laptop. just yesterday switched to my Home PC and getting this abnormal behavior.

thanks a lot.
