### ISSUE TITLE
Putting accordion in waypoint accomplishment.

### ISSUE THREAD

**Issue by bishisht** [FreeCodeCamp/FreeCodeCamp#5029]
Hello to FCC lovers out there. :) Why don't we put waypoints accomplished shown in profile page inside accordion and categorize them? 
What do you think of this idea, do reply.

**Comment by bugron** [comment]
@bishisht thanks for posting. See https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5667. Closing this issue.
