### ISSUE TITLE
[Wiki] Campsite list: San Francisco and San Jose entries under Costa Rica doesn't belong there 

### ISSUE THREAD

**Issue by cumanacr** [FreeCodeCamp/FreeCodeCamp#5030]
Hi, in the Camp City based campsites:
https://github.com/FreeCodeCamp/freecodecamp/wiki/List-of-Free-Code-Camp-city-based-Campsites

San Francisco and San Jose entries under Costa Rica really belongs to United States.

Both will be removed, besides I the camp city based for Costa Rica, San Pedro, would be added here's the link:
https://www.facebook.com/groups/free.code.camp.costa.rica.san.pedro

I follow challenge instructions and report new group to @QuincyLarson but someone on the chats room told me raise the issue here too.

Regards

**Comment by BerkeleyTrue** [comment]
@cumanacr Please open up this issue on the wiki repo https://github.com/freecodecamp/wiki/issues

Happy Coding!
