### ISSUE TITLE
JavaScript Challenges - Console Errors not Clearing

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#50317]
### Describe the Issue

Some users are encountering the error in the linked video. See the forum for more discussion.

https://forum.freecodecamp.org/t/bugged-challenges/608886

### Affected Page

All

### Steps to Reproduce

https://imgur.com/DSGS08c

### Expected behavior

Console error messages should clear so users can run code

### System

various

**Comment by lasjorg** [comment]
If I revert the change from https://github.com/freeCodeCamp/freeCodeCamp/pull/50088 it seems to fix it.

**Comment by shresth-kumar-lal** [comment]
I am also facing this issue while doing javascript datastructures and algorithms course.
The

**Comment by AVICHOUDHARY790** [comment]
I also face this issue while doing a JavaScript data structures and algorithms course.
The console errors are stuck and the solution is to refresh the page every single time.

**Comment by ojeytonwilliams** [comment]
> If I revert the change from #50088 it seems to fix it.

Thanks for tracking that down, @lasjorg, it was defintiely the culprit.
