### ISSUE TITLE
Test running (Ctrl + Enter) gets stuck

### ISSUE THREAD

**Issue by zowhair** [freeCodeCamp/freeCodeCamp#50322]
### Describe the Issue

The test running (Ctrl + Enter) features gets stuck in case whenever there's an error in specifically in code editor while learning at : learn/front-end-development-libraries/redux . 
whenever if some error occurs in code while writing, it stucks on that error and Ctrl + Enter also dont work and user needs to do refresh repeatedly. 

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/use-a-switch-statement-to-handle-multiple-actions

### Steps to Reproduce

1. Go to code editor 
2. write some bug 
3. bug occurs the (ctrl + enter) functionality to stuck
4. This force user to refresh the page again and again 

### Expected behavior

When there's a bug in the code editor, syntax error on any error., on deleting or pressing backspace the below console should also listen the event and should behave actively and on realtime 

### Screenshots

![image](https://user-images.githubusercontent.com/24860770/237020984-5a4ab3c1-1891-4646-899e-2e35f532ec31.png)

I just removed the bug and tried to enter (Ctrl + Enter) it didnt work even on removing the error

### System

- Device : Linux Ubuntu ( 22.04)
- chrome  Version 113.0.5672.63 (Official Build) (64-bit)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #50317, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
