### ISSUE TITLE
Previous accepted solution to bonfire isn't displayed when accessing solution from profile

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#5033]
http://www.freecodecamp.com/challenges/bonfire-arguments-optional?solution=function%20add()%20%7B%0A%20%20var%20args%20%3D%20Array.prototype.slice.call(arguments)%3B%0A%20%20var%20isNumber%20%3D%20function(num)%20%7B%0A%20%20%20%20return%20(Number(num)%20%3D%3D%3D%20num)%20%3F%20num%20%3A%20undefined%3B%0A%20%20%7D%3B%0A%20%20for%20(var%20i%3D0%3B%20i%3C%20args.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(!isNumber(args%5Bi%5D))%20%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20if%20(args.length%20%3D%3D%3D%202)%20%7B%0A%20%20%20%20return%20args.reduce(function(x%2Cy)%20%7B%20return%20x%2By%3B%7D)%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20function(num)%20%7B%0A%20%20%20%20%20%20%20%20if%20(isNumber(num)%20%3D%3D%3D%20undefined)%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20console.log(args%5B0%5D%20%2B%20%22%20%22%2Bnum)%3B%0A%20%20%20%20%20%20%20%20%20%20return%20args%5B0%5D%20%2B%20num%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%7D%0A%7D%0A%0Aadd(2)(3)%3B%0A

That is the link to my solution for the Arguments Optional Bonfire.

What is displayed to me when I click that link is the default "starter code" as if I'd reset the bonfire
```
function add() {
  return false;
}

add(2,3);
```
The "displayer of previous solution" functionality seems to be intermittently broken, I can retrieve my prior solutions on some bonfires, but not others.

**Comment by ltegman** [comment]
I can confirm that this code URI does not correctly populate the editor.

**Comment by P1xt** [comment]
I can confirm that (although it doesn't populate the editor) that that's the exact link present on my profile.

Additionally, my solution doesn't appear when I select that bonfire from the map, or when I select the solution link from my profile.

**Comment by SaintPeter** [comment]
Interesting -
When I click the link from @P1xt's profile page (http://www.freecodecamp.com/P1xt), I can get the solution:
```js
function add() {
    var args = new Array(arguments.length);
    for (var i = 0; i < args.length; ++i) {
        //i is always valid index in the arguments object
        args[i] = arguments[i];
    }
  
    // Use typeof 
    if (typeof args[0] !== 'number' || typeof args[1] !== 'number') 
      return;
   
    if (args.length == 2) {
        return args[0] + args[1];
    }
  
    // You will never get here because of line 9
    if (args.length == 1) {
        a = args[0];  // use var
        return function(b) {
            return a + b;
        };
    }
}

add(2,3);
```

**Comment by SaintPeter** [comment]
Also, I am able to click the URL above and it worked for me.

I'm wondering if it's a browser type issue?  

@P1xt says they are using "Chrome on Ubuntu 14.04"

**Comment by P1xt** [comment]
SaintPeter ... that solution you got. Was the cache of YOUR solution to the problem. Mine was different than that.

**Comment by BerkeleyTrue** [comment]
type:
```js
common.codeUri.parse()
``` 
In the console, this attempts to parse the uri for a solution. Something there is failing because that uri returns null

**Comment by P1xt** [comment]
@SaintPeter My solution was actually:
```
function add() {
  var args = Array.prototype.slice.call(arguments);
  var isNumber = function(num) {
    return (Number(num) === num) ? num : undefined;
  };
  for (var i=0; i< args.length; i++) {
    if (!isNumber(args[i])) {
      return undefined;
    }
  }
  if (args.length === 2) {
    return args.reduce(function(x,y) { return x+y;});
  } else {
      
      return function(num) {
        if (isNumber(num) === undefined) {
          return undefined;
        } else {
          console.log(args[0] + " "+num);
          return args[0] + num;
          
        }
      };             
  }
}
```

**Comment by P1xt** [comment]
@BerkeleyTrue A number of my solutions are failing in this same way. I went back through and for all of them that fail to display, that function (common.codeUri.parse()) returns null. Which is odd, because they were accepted solutions. If it helps any, they all worked across the board just over a week ago.
