### ISSUE TITLE
Profile Solution links should use slug, not title

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5034]
From a [profile page](http://www.freecodecamp.com/saintpeter) 

Here is a (partial) typical link from the profile page:
`http://www.freecodecamp.com/challenges/Bonfire:%20Check%20for%20Palindromes?solution=etc...`

The URL is using the display title for the challenge, not the slug.  

The slug for palindromes should be:
`http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=etc...`

**Comment by BerkeleyTrue** [comment]
@SaintPeter This is on purpose, we do not store the slug when user submits a challenge

**Comment by SaintPeter** [comment]
The slug should be a more reliable way to loading the challenge, though.  Can't it be "calculated" from the title?

**Comment by BerkeleyTrue** [comment]
During our testing this was the most reliable way.

**Comment by SaintPeter** [comment]
Ok, after reviewing the "unDasherize" function, I will concede the point. Still, it offends me to see such ugly URLs.
