### ISSUE TITLE
Code is working but won't recognize as correct

### ISSUE THREAD

**Issue by co8erboy** [FreeCodeCamp/FreeCodeCamp#5037]
Challenge [Waypoint: Sort Arrays with sort](http://www.freecodecamp.com/challenges/waypoint-sort-arrays-with-sort#?solution=var%20array%20%3D%20%5B1%2C%2012%2C%2021%2C%202%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Aarray.sort(function(a%2C%20b)%20%7B%0A%20%20return%20b%20-%20a%3B%0A%7D)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7B%20return%20array%3B%20%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

function longestString(input){
	
	var stringArray = input.split(' ');
	var letterCount = 0;
	var arrayLength = stringArray.length;	

	for (i = 0; i < arrayLength; i++) {
		var x = stringArray[i].length;
		if (x > letterCount) {
			letterCount = x;
		}
	}
	return letterCount;
}
longestString();
![screen shot 2015-12-06 at 2 33 40 am](https://cloud.githubusercontent.com/assets/16131220/11612296/ced6aa02-9bc1-11e5-951c-5abdf351983e.png)

My code:
```javascript
var array = [1, 12, 21, 2];

// Only change code below this line.

array.sort(function(a, b) {
  return b - a;
});

// Only change code above this line.

(function() { return array; })();

```

**Comment by bugron** [comment]
@co8erboy that's because you've changed the function name from `findLongestWord` to `longestString`. Closing as not an issue with the tests, thanks for posting.

**Comment by co8erboy** [comment]
Thank you! sorry about that
