### ISSUE TITLE
Inner progress bar will not be visible when completion modal is re-opened

### ISSUE THREAD

**Issue by mmatsumoto1026** [freeCodeCamp/freeCodeCamp#50386]
### Describe the Issue

Inner progres bar will not be showed when the camper re-open the completion modal after they close the modal. 

### Affected Page

https://www.freecodecamp.org/learn/college-algebra-with-python/learn-ratios-and-proportions/introduction-to-college-algebra-with-python

### Steps to Reproduce

1. Go to any challenges which has the button to show the completion modal after solving the challenge.
2. Click on the button (such as "Run the Tests(Ctrl + Enter)" of JavaScript Algorithms and Data Structures challenges, or "Check your answer" of College Algebra with Python challenge) after solving the challenge.
3. The Inner progress bar will be showed with animation in pop up completion modal, and under the progress bar, completion percentage will be showed by text as "xx% complete"
4. Close the completion modal once. (The camper may do this for reveiw the challenge)
5. Then re-open the modal by clicking the button, the inner progress bar will not be showed, though completion percentage text will also be there and convey the camper the proper percentage.

### Expected behavior

The inner progress bar will be showed when the completion modal is re-opened.
(I'm not sure this should be with animation or not)

### Screenshots

![inner_progress_bar_is_not_showed](https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/ca6b7bf1-79d5-489e-83b2-756016bec122)

### System

- Device: iPhone SE and Laptop(64 bit)
- OS: iOS 15.7.5 and Windows 11
- Browser: Chrome, Firefox, Edge, Brave for Laptop, or Chrome on iPhoneSE
- Version: Chrome => 113.0.5672.93 (Official Build), Firefox => 113.0, Edge => 113.0.1774.42 (Official Build)

**Comment by naomi-lgbt** [comment]
I am able to reproduce this on production. 

A quick fix would be to move the `applyAnimation` declaration out of the global context and into the `useEffect` hook in https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/ProgressBar/progress-bar-inner.tsx.
