### ISSUE TITLE
Cannot remember web language on /learn

### ISSUE THREAD

**Issue by wodecx** [freeCodeCamp/freeCodeCamp#50382]
### Describe the Issue

Each time I open the web it will go to the English version on /learn. Why not let us choose the language in the settings?

### Affected Page

https://www.freecodecamp.org/japanese/learn/

### Steps to Reproduce

1. Start bookmark 'https://www.freecodecamp.org/japanese/learn//'
2. Go to 'https://www.freecodecamp.org/learn/'

### Expected behavior

It should go to 'https://www.freecodecamp.org/japanese/learn/' as I want

### System

- Device: Desktop computer
- OS: Windows 10
- Browser: Chrome

**Comment by Gergo06-py** [comment]
I noticed, that if you go to: https://www.freecodecamp.org/japanese/learn
it opens the Japanese site.
But if you open: https://www.freecodecamp.org/japanese/learn/
it redirects you to: https://www.freecodecamp.org/learn/
The main difference between the two is the slash after the learn, in the second link.

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to mention this. We are tracking this issue here: https://github.com/freeCodeCamp/freeCodeCamp/issues/44818
