### ISSUE TITLE
College Algebra with Python - One Step Multiply needs rounding

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#50393]
### Describe the Issue

In the Notebook associated with the challenge, the single step multiplication does not always generate an even one two three division. Repeating fractions can occasionally occur. 

### Affected Page

https://www.freecodecamp.org/learn/college-algebra-with-python/learn-ratios-and-proportions/ratios-and-proportions-extra

### Your code

The notebook's code

```python
# One-step multiply
def one_step_mult():
    # Uses string_frac(<input string>)
    import random
    a = random.randint(1,11)
    b = random.randint(2,24)
    print(a, "x = ", b)
    ans_in = (input("x = "))
    answer = b/a
    # test
    if string_frac(ans_in)==answer:
        print("Correct! \n")
    else:
        print("Try again")
        print("The correct answer is ", answer, "\n")
```

### Expected behavior

The generation should print round to two decimal places in the challenge and use it for the step 

### Screenshots

![Capture](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/ec9edaf8-6601-46c8-817f-3978a7f32339)

### System

- Device:  Desktop
- OS: Windows 10
- Browser: FireFox
- Version: 113.0.1

**Comment by naomi-lgbt** [comment]
Thanks for reporting - I've passed this on to the team.

**Comment by edatfreecodecamp** [comment]
I changed the code in the original notebook. Let me know if you don't see the change, and I will check other copies of it. Thanks for letting me know about this

**Comment by naomi-lgbt** [comment]
Closing as resolved.
