### ISSUE TITLE
Cannot Open links in the faux "iPhone" display.  iframe errors result.

### ISSUE THREAD

**Issue by 2amar** [FreeCodeCamp/FreeCodeCamp#5039]
Challenge [Waypoint: Link to External Pages with Anchor Elements](http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp.com%22%3E%22cat%20photos%22%3C%2Fa%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<a href="http://freecatphotoapp.com">"cat photos"</a>

```

**Comment by 2amar** [comment]
when i run the rest "You need an a element that links to http://freecatphotoapp.com" is not passing

**Comment by bugron** [comment]
@2amar thanks for posting. Can't reproduce your issue. Can you post a screenshot? Are there any errors in your browser's console?

**Comment by syedirfan7** [comment]
even i am facing the same issue 

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
<p>Here's a <a href="http://freecatphotoapp.com">"cat photos"</a>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by syedirfan7** [comment]
some how when i kept the anchor tag just below the </style> tag i completed the challenge but didn't know the reason and even then if i i click on the anchor ("cat photos") it doesn't redirect me
below is the error i see in the console window
````
5waypoint-link-to-external-pages-with-anchor-elements:1 Refused to frame 'http://freecatphotoapp.com/' because it violates the following Content Security Policy directive: "frame-src *.gitter.im *.gitter.im https: *.vimeo.com *.twitter.com *.ghbtns.com 'self' blob: 104.236.218.15 *.freecodecamp.com http://www.freecodecamp.com http://freecodecamp.com https://www.freecodecamp.com https://freecodecamp.com https://freecodecamp.org *.freecodecamp.org http://www.freecodecamp.org ws://freecodecamp.com/ ws://www.freecodecamp.com/ *.gstatic.com *.google-analytics.com *.googleapis.com *.google.com *.gstatic.com *.doubleclick.net *.twitter.com *.twitch.tv *.twimg.com 'unsafe-eval' 'unsafe-inline' *.bootstrapcdn.com *.cloudflare.com https://*.cloudflare.com localhost:3001 ws://localhost:3001/ http://localhost:3001 localhost:3000 ws://localhost:3000/ http://localhost:3000 *.ionicframework.com https://syndication.twitter.com *.youtube.com *.jsdelivr.net https://*.jsdelivr.net *.ytimg.com *.bitly.com http://cdn.inspectlet.com/ https://cdn.inspeclet.com/ wss://inspectletws.herokuapp.com/ http://hn.inspectlet.com/ *.googleapis.com *.gstatic.com https://hn.inspectlet.com/ https://*.github.com".

**Comment by SaintPeter** [comment]
Confirmed.  You cannot click/open the link in the "iPhone" frame.

**Comment by SaintPeter** [comment]
Related to #4623

**Comment by ltegman** [comment]
I think the bug was saying you can't pass the tests. I'm not having any issues passing the tests.
