### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by jcbrodie** [FreeCodeCamp/freecodecamp#504]
Test text doesn't match up with the challenge. The challenge is related to the form and submit button, but the text in the tests is talking about checkboxes (and has the wrong sizes). 

The tests pass when you do the challenge correctly though, it's just the text on the screen that's incorrect (I think).

**Comment by QuincyLarson** [comment]
Thanks, @jcbrodie. We've now fixed this.
