### ISSUE TITLE
Waypoint: Size your Images

### ISSUE THREAD

**Issue by DrFontaine** [FreeCodeCamp/FreeCodeCamp#5040]
I've been having a really hard time with this.  I've done what the assignment required but however I do the homework it still shows as me doing it incorrectly.  I don't understand what I am doing wrong

Lesson:
CSS has a property called width that controls an element's width. Just like with fonts, we'll use px (pixels) to specify the image's width.  For example, if we wanted to create a CSS class called larger-image that gave HTML elements a width of 500 pixels, we'd use:

<style>
  .larger-image {
    width: 500px;
  }
</style>

Assignment:
Create a class called smaller-image and use it to resize the image so that it's only 100 pixels wide.

Homework:
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .smaller-image {
    width: 100px;
  }
  
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by KrishnaYeolekar** [comment]
Are you sure you are adding the class to the image tag ?
Example - 
````html
<img src="" class="smaller-image">
````

**Comment by DrFontaine** [comment]
No, I did not do that.... feel a little silly.  Thanks @KrishnaYeolekar

**Comment by NcHusker** [comment]
Thanks for this! I'm glad I'm not the only one who couldn't figure this out today!

**Comment by KrishnaYeolekar** [comment]
You're welcome :smile:

**Comment by ltegman** [comment]
Thanks for the help @KrishnaYeolekar :+1:

**Comment by medhatrinky** [comment]
m not getting the run case..??
where should i put the class= smaller-image

**Comment by naga-socks** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image{
    width:100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back." img class = "smaller-image">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Teekay22** [comment]
Thanks FCC guys
