### ISSUE TITLE
Use the Spread Operator to Evaluate Arrays In-Place: Show the array literal spread syntax

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#50414]
### Describe the Issue

We should show the syntax needed to solve the challenge.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-the-spread-operator-to-evaluate-arrays-in-place

### Your code

```



```

### Expected behavior

Teach people the knowledge they are meant to know to solve the challenge.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/es6-use-the-spread-operator-to-evaluate-arrays-in-place/610696

**Comment by naomi-lgbt** [comment]
I'd propose updating the example text from:

````md
...arr returns an unpacked array. In other words, it spreads the array. However, the spread operator only works in-place, like in an argument to a function or in an array literal. The following code will not work:

```md
const spreaded = ...arr;
```
````

To:

````md
...arr returns an unpacked array. In other words, it spreads the array. However, the spread operator only works in-place, like in an argument to a function or in an array literal. For example:

```md
const spreaded = [...arr];
```

However, the following code will not work:

```md
const spreaded = ...arr;
```
````

**Comment by lasjorg** [comment]
As an aside.

The use of `Function.prototype.apply()` in the example is a language feature that hasn't been taught. I'm not even sure where in the curriculum it is taught, if at all. Seems a little odd.

**Comment by naomi-lgbt** [comment]
IMHO the example is fine - I think it's explained enough for the context of the challenge.

If there's a preference to remove it though, I wouldn't object.

**Comment by lasjorg** [comment]
I mean this is just after the basic JS section, I'm not sure someone that has only looked at JS for like a week or two will feel quite the same way about it.

It isn't something I have seen a lot of forum posts about, if any. But I still find it a bit odd to use `apply` in an example before the students know anything about it. The context is kind of lost if you do not understand what `apply` does.

Anyway, I don't have a terribly strong opinion on it, just don't really agree with using code that contains language constructs that haven't been taught.

**Comment by naomi-lgbt** [comment]
Tracking in https://github.com/freeCodeCamp/freeCodeCamp/issues/50434
