### ISSUE TITLE
Add progress indicators to maps

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#50412]
Here's some mocks:
<img width="240" alt="1" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/7809b703-e426-4570-8d71-a30dca24bf74">
![2](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/b2e29e8f-92fd-4588-980e-cc27317d6454)

**Comment by bbsmooth** [comment]
Hey @moT01 I'm sure you probably discussed this in meetings and such, but could you give a brief overview of what the purpose of this feature is for? It would help in determining the accessibility issues that need to be considered.

**Comment by moT01** [comment]
Mainly, to clarify the order of how to go through the curriculum. It also splits the superblocks/buttons up into sections, which gives some more context to the buttons. It also shows a small overview of your progress - e.g. if you earn a cert, the number turns into a cert icon (tentative plan anyway).

**Comment by ahmadabdolsaheb** [comment]
How does this feature affects https://github.com/freeCodeCamp/freeCodeCamp/issues/41403?

**Comment by moT01** [comment]
Here's some more details of what I think we want here. We want the superblock buttons arranged into four (five with upcoming) groups:  
```
Stage 1: Front End Development
 1 Responsive Web Design Certification
2 Javascript Algorithms and Data Structures Certification
3 Front End Development Libraries Certification
4 Data Visualization Certification
 
 Stage 2: Back End Development
  5 Relational Database Certification
6 Back End Development and APIs Certification
7 Quality Assurance Certification
8 Information Security Certification
 
 Stage 3: Python & AI
  9 Scientific Computing with Python Certification
10 Data Analysis with Python Certification
11 Machine Learning with Python Certification
12 College Algebra with Python Certification

Stage 4: Extra Learning
- Coding Interview Prep
- Project Euler
- Legacy Responsive Web Design

Upcoming Curriculum
- Javascript Algorithms and Data Structures (Beta) Certification
- The Odin Project
- Example Certification
```

Note that the `Upcoming Curriculum` section is hidden in production.

The first three stages above should have icons next to them, similar to this:
 
 <img width="766" alt="Clipboard - June 8, 2023 7_03 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/3b054d66-b78d-40c1-89d0-dc2ea732fd77">
 
   If they have the certification, they get the icon with the ribbons. If not, they get the icon without.  The last two groups of buttons do not need any icons.  The buttons can then be the full width. There is potentially something on [this issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/50436) and its associated PR we can use for that icon.
   
   Between the numbered icons should be the dashed arrows, as in the image.

The icons within the buttons should stay on the left.

<hr>

Some questions:
Do we want different icons next to the last two groups, maybe continue with the numbers or just plain circles, so the buttons are the same width?
What do we want for the heading of stage 4?

Does this all sound good @ahmadabdolsaheb? Is there anything else you can add?

**Comment by bbsmooth** [comment]
I kind of envision the semantics as follows:

- Each stage heading would be an `h2` and would need an `id` attribute
- The list of courses underneath each heading would be an `ol` or `ul` (depending if they are numbered or not)
- Each list would be named using `aria-labelledby` pointing to the `id` of its heading
- We would need to add the appropriate sr-only text so that screen reader users hear the number, the status, and the name of the course. For example, "Course 1, Responsive Web Design Certification, Completed", or "Course 2, Javascript Algorithms and Data Structures Certification, not completed".

Since these numbers are just the suggested order for beginners and do not have to be followed, I would recommend we add a brief paragraph explaining that above the first stage heading.

**Comment by moT01** [comment]
I will bring up the paragraph at the next meeting. I don't personally like it on the landing page - maybe the /learn page. But I think you might be onto something. If we need a paragraph to explain what the things mean, maybe we aren't communicating it good enough through the UI. We are trying to communicate the suggested order.

**Comment by ahmadabdolsaheb** [comment]
@bbsmooth, I understand your concern. When users signup, they are shown a few paragraphs. One of them says the followings:
 "If you are new to programming, we recommend you start at the beginning and earn these certifications in order."
I am making that whole section a bit more concise, so we might be able to squeeze a sentence there to make things clearer. 

@moT01, Thanks for putting requirements together. I don't think we should have a stage 4. Might also be a good idea to give the Legacy Responsive Web Design the ribbon since it is/was a certification.

**Comment by ahmaxed** [comment]
@moT01, I was wondering if there are any updates for the requirements ?

**Comment by moT01** [comment]
No @ahmaxed. We don't necessarily have every detail figured out, but I think we're close enough that we can open this up to contributors and refine things on the PR.

**Comment by moT01** [comment]
I could mention that I made a mock of this some time back, you can [see the code here.](https://github.com/freeCodeCamp/freeCodeCamp/compare/main...moT01:freeCodeCamp:mock-learn-map-with-superblock-progress-indicators) 

<details><summary>It looks like this</summary>

![Screen Shot 2023-07-06 at 9 26 10 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/bd25cd70-95b3-406c-84f7-3ed6e75618d7)

</details>

Note that this is not how we want it to look - we want it to look like we discussed above. But some of the code may be able to be reused - not sure. It may be better to just start from scratch.

**Comment by CallmeHongmaybe** [comment]
So which design are we going to move on with ? IMHO the very first design looks nicest.

**Comment by moT01** [comment]
We decided on [the one in this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/50412#issuecomment-1585086022) @CallmeHongmaybe. I think we can change it in the future if we want. The important thing we want to try and communicate with this is the suggested order of the curriculum. The numbers should do that, regardless of what design we use.

**Comment by CallmeHongmaybe** [comment]
Thanks for replying back. I was wondering where you made the mock for the suggested design, just to be sure not to do any duplicate work and waste anyone's time :)

**Comment by moT01** [comment]
The mock for the suggested design is an image created by @ahmaxed - so the code for that isn't created yet. I don't see a whole lot that can be reused from the code I shared, maybe some of [the map logic/rendering](https://github.com/freeCodeCamp/freeCodeCamp/compare/main...moT01:freeCodeCamp:mock-learn-map-with-superblock-progress-indicators#diff-081c4e752c8171a7169d5f14c546fbac8ca29ebe79129f963ff516385b38e71dR152) and possibly some of the CSS.

**Comment by CallmeHongmaybe** [comment]
Thanks. I'll see where I can add for the mock.

**Comment by CallmeHongmaybe** [comment]
So here's the rough draft built with here. Let me know what should be changed in the design, and how do we retrieve data for the users' number of fully completed lessons and the users' current certification ?

![localhost_8000_learn_](https://github.com/freeCodeCamp/freeCodeCamp/assets/44527246/97fb1277-6c07-48ed-92c5-dd3d763cc4f6)

**Comment by ahmaxed** [comment]
Thanks for working on this feature, @CallmeHongmaybe. Here is the design we are going with: https://github.com/freeCodeCamp/freeCodeCamp/issues/50412#issuecomment-1585086022
Please use the same font state title, decorate the completion state accordingly and use a dashed line for the arrows. 

The state of the certifications could be pulled from the userSelector from redux like this: https://github.com/freeCodeCamp/freeCodeCamp/blob/120ad721a3f96431adc1c3f1ba0718a667b82bc0/client/src/client-only-routes/show-settings.tsx#L24

**Comment by CallmeHongmaybe** [comment]
@ahmaxed if you don't mind can you provide me the svg or the CSS code of the ribbon ?

**Comment by CallmeHongmaybe** [comment]
Also, is it true that only signed-in users can see the ribbons ?

**Comment by ahmaxed** [comment]
Yes, only signed in users with completed certifications see the ribbons.
https://github.com/freeCodeCamp/freeCodeCamp/pull/49717

**Comment by ahmaxed** [comment]
Here is the ribbon SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" width="45" height="50" viewBox="0 0 45 50" fill="none">
<path d="M25 35.3418L35.4851 28L44.5957 41.0113L36.2658 39.7151L34.1106 48.353L25 35.3418Z" fill="black"/>
<path d="M9.11059 29L19.5957 36.3418L10.4851 49.353L8.85418 41.0821L-4.67677e-07 42.0113L9.11059 29Z" fill="black"/>
<circle cx="21.9999" cy="21" r="20" stroke="black" stroke-width="2"/>
<circle cx="21.9999" cy="21" r="17.5" fill="black" stroke="white" stroke-width="3"/>
<path d="M23.9709 13.4545V28H22.2095V15.3011H22.1243L18.5732 17.6591V15.8693L22.2095 13.4545H23.9709Z" fill="white"/>
</svg>
```

The last path is the number. Feel free to remove or replace it a dynamic number.

**Comment by CallmeHongmaybe** [comment]
Thank you. 
I've tried the steps below to seed the database with certified user but when I opened the localhost, the page shows nothing and when I click the menu button the Profile `<li>` isn't even there. 
`pnpm run create:config`
`pnpm run seed:certified-user`
`pnpm run develop`

**Comment by ahmaxed** [comment]
You probably need to sign in. 

If you cannot find what you are looking for in the documentation, feel free to ask for help in:

The Contributors category of [our community forum](https://forum.freecodecamp.org/c/contributors).
The #Contributors channel on [our chat server](https://discord.gg/PRyKn3Vbay).

**Comment by CallmeHongmaybe** [comment]
Unfortunately you can't sign in unless you sign out, and when you sign out same error happens. 
Will have this discussed on the chat server.

**Comment by jeremylt** [comment]
It was in the shuffle, but I liked @bbsmooth suggestion that we call them "Track 1" etc instead of "Stage 1", especially since many of these are fine to do in a different order.

Also, one of these days we should really revisit the "Scientific Computing" name of that python certificate, because its contents absolutely **are not** "Scientific Computing".

**Comment by CallmeHongmaybe** [comment]
Okay I'll change the titles from Stage to Track. 
And is it appropriate to rename "Scientific Computing" to "General Python Programming" ?

**Comment by ahmaxed** [comment]
Great naming suggestions. There might already be a renaming in the works for the Scientific Computing. Since the renaming is a bit involved for a certification, let's make a separate issue to track the feedback the progress on that.

We can move forward with "Stage" for now until we hear back from @QuincyLarson about using "Track".

**Comment by Amit-Morade** [comment]
I would like to work on this

**Comment by moT01** [comment]
There's a PR with quite a bit of work done on it for this @Amit-Morade. Perhaps you could pick up where that left off - and maybe try to communicate with @CallmeHongmaybe to see where he left off.

Otherwise, you can start from scratch if you want. This has a help wanted label, so we will accept a PR that makes these changes. Be sure to check out our [contributor guidelines](contribute.freecodecamp.org/) if you haven't already.

**Comment by a2937** [comment]
Hi there. Are a lack of arrows a deal breaker?

**Comment by ahmaxed** [comment]
@a2937, not a deal breaker. However, Quincy requested the arrows to emphasize the order of completion a bit more.

**Comment by a2937** [comment]
I was having a ton of trouble with the arrows.
