### ISSUE TITLE
Require JSDocs for api

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#50417]
To help with maintenance of the new api, we want a lint rule to require JSDoc comments on exported functions.

**Comment by Sboonny** [comment]
Why tho? we have TypeScript

**Comment by ojeytonwilliams** [comment]
Naomi and I discussed a bit in chat https://chat.freecodecamp.org/group/dev-team?msg=4PoegPD6fTDStuNod, but the gist was: yes TS and good variable names are helpful, but JSDocs make intellisense even more helpful.

For example, Cypress has awesome JSDocs, so you can see almost everything you need by mousing over a function. Fastify, in contrast, relies on the types which are pretty opaque, so you have no choice but to go to their docs.

I think it's worth trying them out in the new api. If it turns out to be too annoying we can always disable the rule.
