### ISSUE TITLE
(Bonfire: Diff Two Arrays) Test inconsistencies / missing exercise constraint

### ISSUE THREAD

**Issue by alvinkoh** [FreeCodeCamp/FreeCodeCamp#5042]
Hi guys,

I managed to complete the challenge, but believe that there are inconsistencies in the expected test results / exercise constraints
* `["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"] should return ["diorite", "pink wool"]` is inconsistent with `[], ["snuffleupagus", "cookie monster", "elmo"] should return ["snuffleupagus", "cookie monster", "elmo"]`
* `[1, "calf", 3, "piglet"], [7, "filly"] should return [1, "calf", 3, "piglet", 7, "filly"]` is true only if there is no sorting
* The exercise description does not require that the results be sorted alphabetically.

My code does not do any alphabetical sorting.  It considers each array in turn, and discards any element that appears in both arrays.

That my code was accepted suggests that
a. The submission tests are wonky, or 
b. The tests don't expect alphabetical sorting, and that the current wording may confuse others.

# Proposals
a. Require that the results be sorted alphabetically (add exercise constraint, update descriptions of test outcomes), or
b. Change the expected test results for `["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]` so that it is `["pink wool", "diorite"]` (no sorting expected)

# Related Issue
I saw that caeldom raised a related issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4133

I tried caeldom's solution, and it give the results:
1. `["pink wool"]`
2. `["diorite", "pink wool"]`
3. `[]`
4. `[4]`
5. `[4, "piglet"]`
6. `["cookie monster", "elmo", "snuffleupagus"]`
7. `[1, 3, 7, "calf", "filly", "piglet"]`

I really like that caeldom's solution is more concise than my code, but the outcomes are inconsistent with the listed test results.

If sorting is not expected (and actually considered a bug), then the arr.filter logic will not work. 

If sorting is required:
* Result 5 is inconsistent with `[1, "calf", 3, "piglet"], [1, "calf", 3, 4] should return ["piglet", 4]`.
* Result 7 is inconsistent with `[1, "calf", 3, "piglet"], [7, "filly"] should return [1, "calf", 3, "piglet", 7, "filly"]`.

**Comment by ltegman** [comment]
I'm not sure I understand the problem? The wording of the challenge doesn't enforce order and the tests don't either.

**Comment by alvinkoh** [comment]
Yes, that's my experience too.  However, the challenge states that `["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"] should return ["diorite", "pink wool"]`.  Without sorting, the return value will be `["diorite", "pink wool"]`.

I was further confused by the response to #4133 (though that doesn't seem to be the production behavior).

The change is probably as small as updating the expected results stated in the challenge.

**Comment by ltegman** [comment]
#4133 was fixed :smile: . I don't think updating the order is a solution because the output order is algorithm dependent. The reason the tests ended up ordered like they are is that the algorithm most people end up using outputs them in the order displayed. The items have to be in some order, and there's always a chance that won't match the output of the user's function.

However, if someone wants to put in a PR that adds text like "The order of items in the output array does not matter." or something to that effect I don't see a problem with it.

**Comment by alvinkoh** [comment]
I understand where you're coming from w.r.t offering flexibility.  The output is either sorted or unsorted (but not both?) depending on the approach we use.

I'm just suggesting that the test results in the challenge description (below the output box on the left) may be confusing since they suggest both sorted and unsorted behaviors happening with the same program:

```
["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"] should return ["diorite", "pink wool"]
```
AND
```
[], ["snuffleupagus", "cookie monster", "elmo"] should return ["snuffleupagus", "cookie monster", "elmo"]
```

I have the impression that the results should either be
* unsorted (what I got from my code, and what was accepted), OR
````
["pink wool", "diorite"]
["snuffleupagus", "cookie monster", "elmo"]
````
* sorted (what caeldom got with #4133)
````
["diorite", "pink wool"]
["cookie monster", "elmo", "snuffleupagus"]
````

Has someone submitted code that mixes the behaviors?  I'm curious to see if there's some algorithm that may result in another outcome.

This is a small thing anyway.  I'm just bringing it up because I look at the expected test outcomes before I code, so there was some logical inconsistency during design time.

Thanks for the nice work on the site!
