### ISSUE TITLE
Certifications Redesign

### ISSUE THREAD

**Issue by estefaniacn** [freeCodeCamp/freeCodeCamp#50436]
### Is your feature request related to a problem? Please describe.

Our goal is to update the design of the certifications to this new format:

![New Certification](https://github.com/freeCodeCamp/freeCodeCamp/assets/85124911/616003b8-dd6e-4ca3-9ec9-38074286e650)

### Describe the solution you'd like

We should implement this new design following these important aspects:

- The implementation should be responsive.
- The QR Code should take users to the freeCodeCamp certification.
- The URL at the bottom should correspond to the freeCodeCamp certification.
- The implementation should include the digital version of Quincy's signature. 

### Describe alternatives you've considered

To incorporate the feedback provided by the team:
- The QR Code and the blue ribbon with the freeCodeCamp glyph should be approximately the same size. We considered different sizes and if they have approximately the same size, the design looks balanced.

**Comment by naomi-lgbt** [comment]
One thing we'll want to ensure in the redesign is that we do not break the printed layout of the certification.
