### ISSUE TITLE
College Algebra with Python : String Fractions not used in single step

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#50437]
### Describe the Issue

In the "Learn to Solve For X: Extra" , it only converts the fraction for the original equation and not the user input. I believe it should use the string faction method for both.  I believe especially considering it won't be major to implement and the addition will not remove any already valid answers. Like all that needs to be done is use the following codeblock:

```python 

# One-step multiply
def one_step_mult():
    # Uses string_frac(<input string>)
    import random
    a = random.randint(1,11)
    b = random.randint(2,24)
    print(a, "x = ", b)
    print("Round your answer to two decimal places.")
    ans_in = (input("x = "))
    answer = round(b/a,2)

    # test
    if round(string_frac(ans_in),2) == answer:
        print("Correct! \n")
    else:
        print("Try again")
        print("The correct answer is ", answer, "\n")
```

### Affected Page

https://www.freecodecamp.org/learn/college-algebra-with-python/learn-how-to-solve-for-x/how-to-solve-for-x-extra

### Your code

```python
# One-step multiply
def one_step_mult():
    # Uses string_frac(<input string>)
    import random
    a = random.randint(1,11)
    b = random.randint(2,24)
    print(a, "x = ", b)
    print("Round your answer to two decimal places.")
    ans_in = (input("x = "))
    answer = round(b/a,2)
    # test
    if string_frac(ans_in)==answer:
        print("Correct! \n")
    else:
        print("Try again")
        print("The correct answer is ", answer, "\n")
```

### Expected behavior

I expected to 17/11 to be considered as a valid answer to the problem `11x = 17`. 

### Screenshots

![Capture](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/42fed2b3-8a35-4d96-b069-657a1873acd9)

### System

- Device: Desktop
- OS: Windows 10
- Browser: FireFox
- Version: 113.0.1

**Comment by naomi-lgbt** [comment]
Thanks for reporting. I've flagged this internally for review.

**Comment by munneb10** [comment]
Is anyone working on this Issue

**Comment by munneb10** [comment]
I have solved this issue. Please assign this issue to me.
Thanks

**Comment by naomi-lgbt** [comment]
Hi @munneb10, thanks for your interest in contributing! Only staff have access to edit the notebook template, so unfortunately this issue isn't open for contribution.

**Comment by munneb10** [comment]
@naomi-lgbt No problem, Thanks for informing.

**Comment by moT01** [comment]
@edatfreecodecamp has all the notebooks on his account - he will have to fix it for now, until we move those to the fCC org.

**Comment by edatfreecodecamp** [comment]
I just fixed the issue
