### ISSUE TITLE
My code seems to be correct, but the website is telling me that 'My <h2> element should be blue. But, it is blue! Can anyone help me?

### ISSUE THREAD

**Issue by nandinimenon** [FreeCodeCamp/FreeCodeCamp#5046]
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {
  color:blue;
  };
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by ltegman** [comment]
The code you posted doesn't have an `h2` element in it. Is this the code you're trying to submit?

**Comment by ltegman** [comment]
Closing as not an issue with the tests. Thanks and happy coding!
