### ISSUE TITLE
Redux - test doesnt take createStore into consideration

### ISSUE THREAD

**Issue by TomasKsk** [freeCodeCamp/freeCodeCamp#50460]
### Describe the Issue

This challenge should push the programmer to create the Redux.store() at the end of the challenge. But it passes with declaring this:
```
const store = null;
```
Now it was explained to me, that the site creates its store on its own, but i think the programmer should be expected to do that even if he forgot - like me :)

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/write-a-counter-with-redux

### Your code

```
const INCREMENT = 'INCREMENT'; // Define a constant for increment action types
const DECREMENT = 'DECREMENT'; // Define a constant for decrement action types

const counterReducer = (state = 0, action) => {
  switch(action.type) {
    case INCREMENT:
      return state + 1;
    case DECREMENT:
      return state - 1;
    default:
      return state;
  }
}; // Define the counter reducer which will increment or decrement the state based on the action it receives

const incAction = () => {
  return {type: INCREMENT}
}; // Define an action creator for incrementing

const decAction = () => {
  return {type: DECREMENT}
}; // Define an action creator for decrementing

const store = null;


```

### Expected behavior

The test should fail if Redux.createStore() wasnt used

### System

- Device: [Laptop]
- OS: [X11; Linux x86_64]
- Browser: [Chrome]
- Version: [113.0.0.0]

**Comment by munneb10** [comment]
Hi @TomasKsk where the test cases are written for it.

**Comment by hanswang123456** [comment]
I was able to just log the store to console and it does give the code provided. Specifically if you would want to assert the names of the functions:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/50556568/93a46250-c721-498e-a7ea-6f827b04ca2a)
