### ISSUE TITLE
I can't find mongodb version 4.2.x. Is that version still required to run app locally?

### ISSUE THREAD

**Issue by jmetev1** [freeCodeCamp/freeCodeCamp#50487]
### Describe the Issue

The setup instructions here https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/how-to-setup-freecodecamp-locally.md suggest that I need MongoDB Community Server | 4.2.x. I've tried through docker and through macos homebrew instructions and can't get any 4.2 version. 4.4.x is available. Is that acceptable? If so, should I update this doc?

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/how-to-setup-freecodecamp-locally.md

### Steps to Reproduce

Try to follow one of options for setting up MongoDB Community Server | 4.2.x

### Recommended fix or suggestions

Maybe 4.4.x is ok?

**Comment by jmetev1** [comment]
i searched the tags on docker https://hub.docker.com/r/mongodb/mongodb-community-server/tags and no 4.2 is available.

this article https://stackoverflow.com/questions/57856809/installing-mongodb-with-homebrew suggests other ways but the result is always ```
No available formula with the name "mongodb-community@4.2". Did you mean mongodb-community@4.4, mongodb-community@5.0 or mongodb-community
```

**Comment by jmetev1** [comment]
i found this pr https://github.com/freeCodeCamp/freeCodeCamp/pull/45292 which suggests that 4.4 should work fine. so i guess i should update the docs?

**Comment by jmetev1** [comment]
or there are other docker images available of 4.2.x. https://hub.docker.com/_/mongo/tags?page=1&name=4.2.
 But people trying to follow directions won't get to them if we point them to starting from here: [MongoDB Community Server](https://docs.mongodb.com/manual/administration/install-community/) because mongo only points to their docker images.

**Comment by jmetev1** [comment]
i also see that in /api/README.md there are docker instructions there. should i use that or is that for something different?

**Comment by raisedadead** [comment]
Hi @jmetev1, thanks for the issue. We recommend asking around in our chat and forum when you are troubleshooting.

The docs need to be updated to the version we are using right now. I have created a PR.

It will be available soon at https://contribute.freecodecamp.org

I hope this helps.

**Comment by jmetev1** [comment]
I see that the docs have been updated to mongo 5.0. But maybe should the docs point to https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api/README.md as the best way to set up mongo? That's what I used and it seems like the easiest option. @raisedadead

**Comment by raisedadead** [comment]
Thanks for pointing that out. 

The `/api` directory is a newer API in the works. It will have a full docker-based setup that is more convenient than the current workflow.

We will release cleaner and easy-to-follow docs when that happens. Meanwhile we will stick to the docs you see at: [contribute.freecodecamp.org](https://contribute.freecodecamp.org/)
