### ISSUE TITLE
deprecate /account endpoint

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50483]
Discussed in today meeting, that the endpoint don't get a warrant traffic to maintain it, and it could be moved to deprecated section because of how rarely it is requested.

**Comment by munneb10** [comment]
Hi @Sboonny
Are you mentioning this end point
https://github.com/freeCodeCamp/freeCodeCamp/blob/a91544b43baecfcdb4510f6f763a7d73aaf24e8b/api/src/routes/user.ts#L4
Thanks.
