### ISSUE TITLE
Code portfolio calendar not in sync with portfolio dates

### ISSUE THREAD

**Issue by george-stepanek** [FreeCodeCamp/FreeCodeCamp#5049]
Hi, my portfolio calendar shows my last two items on December 2 and 4, but the projects table shows them as December 1 and 3. It looks like they're working off of different time-zones. Not sure which would be correct (hey, I'm from New Zealand, I'm used to being on a different day from the rest of the world) but they should at least be consistent...

**Comment by mtroiani** [comment]
I noticed what appears to be the same thing yesterday. The calendar showed that I completed 5 items on Jan 22nd, while the projects list had 3 for Jan 22nd and 2 for Jan 23rd. I'm in UTC-8.

**Comment by bugron** [comment]
Is this still an issue?

**Comment by george-stepanek** [comment]
I believe so, but I haven't checked recently myself, because I've now finished all 3 certifications... :smile:

**Comment by ltegman** [comment]
There have been a lot of changes to the way the calendar and streaks work since this bug was filed. If someone runs into this issue again please file a new issue. Thanks and happy coding!
