### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-all-of-our-buttons has an issue 

### ISSUE THREAD

**Issue by bluestealth** [FreeCodeCamp/freecodecamp#505]
In the challenge the instructions incorrectly refer to the like button.
You should add a <i class="fa fa-trash"></i> within your like button element. -> should be delete button.
You should add a <i class="fa fa-info-circle"></i> within your like button element. -> should be info button.

**Comment by QuincyLarson** [comment]
Thanks, @bluestealth. We've fixed these.
