### ISSUE TITLE
GET /certificate/showCert/:username/:certSlug

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50501]

**Comment by Rajeev1011** [comment]
,,,,,,,@,,,,,,,,SSL protocol certificate is necessary for me & you further run way who's suited..... Thankkkkkkkk____?
5

**Comment by Rajeev1011** [comment]
> ,,,,,,,@,,,,,,,,SSL protocol certificate is necessary for me & you further run way who's suited..... Thankkkkkkkk____?
