### ISSUE TITLE
/donate/add-donation analytics

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#50503]
Right now, this endpoint returns either

 `{ error: 'User must be signed in for this request.' }` 

or 

```
{
 type: 'danger',
 message: 'Something went wrong.'
}
```

both with status 500. Ideally they should be 401 and 400 (when the user is already donating) respectively and standardized (https://github.com/freeCodeCamp/freeCodeCamp/issues/50184)

500 should only be sent when the server encounters something unexpected.

@ahmadabdolsaheb we don't want to mess up the analytics, so could you confirm/deny if these changes will cause any issues?

**Comment by ahmadabdolsaheb** [comment]
Right now we are not reporting errors to analytics so altering the status and message should not effect anything.
