### ISSUE TITLE
Issue with Quality Assurance certification coding challenge

### ISSUE THREAD

**Issue by Madeee1** [freeCodeCamp/freeCodeCamp#50511]
### Describe the Issue

In the QA lessons, they require the user to render the index page using Pug. Everything is good up until before the "Implement the Serialization of a Passport User" lesson.

On this lesson, Pug is used to render the index home page conditionally depending on if the Mongo database is connected successfully or not. Using a callback function to Mongo client to render the page differently.

**The problem starts here:**
If following the lesson, the assumed stance is to add onto the code and not remove anything except explicitly told to as far as I understand. In following this, the "Implement the Serialization of a Passport User" lesson tells the user to add in the functionality to check on the DB connection and conditionally render the Pug home page.

Because Pug is unable to rerender and send out the same page using res.render(), the tests will fail and the home page won't be conditionally rendered based on the Database connection.
The user will probably assume that they shouldn't delete the 
`app.route('/').get((req, res) => {
  res.render('index', { title: 'Hello', message: 'Please log in' });
});` code that is written from the lessons before
Because they aren't being told to, but because of this the test will fail and the user will need to debug something that is quite hard to find without any help, especially because users will probably assume something is wrong with the code they added insetad.

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/implement-the-serialization-of-a-passport-user

### Your code

```
'use strict';
require('dotenv').config();
const express = require('express');
const myDB = require('./connection');
const fccTesting = require('./freeCodeCamp/fcctesting.js');
const session = require('express-session');
const passport = require('passport');
const { ObjectID } = require('mongodb');

const app = express();

app.set('view engine', 'pug');
app.set('views', './views/pug');

app.use(session({
  secret: process.env.SESSION_SECRET,
  resave: true,
  saveUninitialized: true,
  cookie: { secure: false }
}));

app.use(passport.initialize());
app.use(passport.session());

fccTesting(app); // For fCC testing purposes
app.use('/public', express.static(process.cwd() + '/public'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.route('/').get((req, res) => {
  res.render('index', { title: 'Hello', message: 'Please log in' });
});

myDB(async client => {
  const myDataBase = await client.db('database').collection('users');

  app.route('/').get((req, res) => {
    res.render('index', {
      title: 'Connected to Database',
      message: 'Please log in'
    });
  });

  passport.serializeUser((user, done) => {
    done(null, user._id);
  });
  
  passport.deserializeUser((id, done) => {
    myDataBase.findOne({ _id: new ObjectID(id) }, (err, doc) => {
      done(null, doc);
    });
  });

}).catch(e => {
  app.route('/').get((req, res) => {
    res.render('index', { title: e, message: 'Unable to connect to database' });
  });
});
  
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Listening on port ${PORT}`);
});


```

### Expected behavior

The code is what I think the normal user would expect to work according to the lesson specifications, but it does not.
Something along the lines of 

> Remove the previous rendered page by Pug and provide only 1 render because Pug is unable to rerender and send out the same page.

### System

- Language: English
- Device: Laptop
- OS: Windows 10
- Browser: Firefox

### Additional context

I am doing the certification and came across this problem that I think is an unnecessary issue

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

>Because they aren't being told to, but because of this the test will fail and the user will need to debug something that is quite hard to find without any help, especially because users will probably assume something is wrong with the code they added insetad.

In my opinion, this lesson is far enough into the curriculum (it is an "Advanced" block) that not providing every bit of information is more of a good (teachable) thing.

The lesson does emphasize:
> Now you want to connect to your database, then start listening for requests. The purpose of this is to not allow requests before your database is connected or if there is a database error.

This implicitly tells Campers what needs to be done, and, from past experience, Campers should know not to have two of the same route defined - or at least be able to debug when this does not work.

I appreciate that I have spent too much time on this section of the curriculum; I am out of touch with what most Campers actually have been through. So, if this is a common pain point, I think this sentence could be reworded:

> To accomplish this, encompass your serialization and app routes in the following code:

However, a lot of these lessons are already a _"copy-pasta the given code"_. So, I suggest **not** being as explicit as:
> Remove the previous rendered page by Pug and provide only 1 render because Pug is unable to rerender and send out the same page.

**Comment by Madeee1** [comment]
Hey! I appreciate the response!
I agree that my solution is much too explicit. Especially given that I wrote it not long after I spent a bit too much time debugging

I do not know if this is a common pain point or not that needs fixing, as I do see your point that given the copy-pasta nature, debugging like this can really increase Campers' understanding!

**Comment by naomi-lgbt** [comment]
Given the lack of activity, I'll go ahead and close this as stale.

If we see this being a tripping point for more campers, we can certainly reopen and re-evaluate at a later date. :3
