### ISSUE TITLE
Issue with wording on Bonfire: Falsy Bouncer

### ISSUE THREAD

**Issue by shadowfool** [FreeCodeCamp/FreeCodeCamp#5052]
Challenge [Bonfire: Falsy Bouncer](http://www.freecodecamp.com/challenges/bonfire-falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20return%20arr.filter(function(object)%7B%0A%20%20%20%20return%20Boolean(object)%3B%0A%20%20%7D)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The instructions state to "remove" falsey values from an array. As my solution only returns a modified static state of arr, is it possible to add a test that makes sure arr no longer contains the falsey values?

My code:
```javascript
function bouncer(arr) {
  return arr.filter(function(object){
    return Boolean(object);
  });
}

```

**Comment by SaintPeter** [comment]
We don't distinguish between returning an array without the missing values and actually altering the underlying array.  If, for example, we had said "Modify arr in-place", that would be another issue entirely.

Closing as this will not be changed.
