### ISSUE TITLE
CodeAlly Down flag is too wide

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#50526]
The message we show when CodeAlly is down is too wide on the project pages.

On the superblock page, it looks right:
![Screen Shot 2023-05-26 at 11 07 49 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/c247f3ed-4bd5-42c2-a10d-e8f373f85e37)

On the project page, it's too wide.
![Screen Shot 2023-05-26 at 11 07 35 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/ba078009-e24e-4430-a44f-859f879acc65)

It should match the width of the rest of the elements. And we could probably add a little margin above the message while we're at it.

**Comment by Nitz2611** [comment]
Hey! can i work on this?

**Comment by gikf** [comment]
Hey @Nitz2611

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by jenasuraj** [comment]
i wanna fix it
