### ISSUE TITLE
"Run Test" Seemingly not responding

### ISSUE THREAD

**Issue by clmurphree16** [FreeCodeCamp/FreeCodeCamp#5053]
In Waypoint: SIze Your Image. I believe my code is correct, but the "run test" button is seemingly unresponsive. Code attached below. 
![fcc](https://cloud.githubusercontent.com/assets/16170322/11617791/d8cd1306-9c58-11e5-878f-7a2f203b3f3d.JPG)

**Comment by opsappsdev** [comment]
Me too
