### ISSUE TITLE
Override Styles in Subsequent CSS - Needs improved tests

### ISSUE THREAD

**Issue by ksngits** [FreeCodeCamp/FreeCodeCamp#5054]
Challenge [Waypoint: Override Styles in Subsequent CSS](http://www.freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: blue;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 class="blue-text">Hello World!</h1>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by SaintPeter** [comment]
Confirmed.

It looks like we need to confirm that the SAME `h1` element has both classes, not two SEPARATE `h1` tags.

Thanks @ksngits, for bringing this to our attention.

**Comment by gasperno** [comment]
There are three test cases.
1) check if h1 has a pink-text class
2) check if h1 has a blue-text class
3) check if the text inside h1 is blue in color.

I think I would __remove__ two tests 1 and 2 and add a test that checks if there is a h1 element with both pink-text and blue-text.  Message would be 'Your h1 class must have both 'blue-text' and 'pink-test'. Would you __agree__ with removing two tests? Or instead __recommend__ to add this new test?

**Comment by ksngits** [comment]
Yes, @gasperno, I welcome  your suggestion.

**Comment by KrishnaYeolekar** [comment]
@gasperno @ksngits What if i add a additional test case with message 
" Both <code>blue-text</code> and <code>pink-text</code> should belong to the same <code>h1</code> element. "
