### ISSUE TITLE
Should the "check your code" button and the instructions be in between the lines of the code editor?

### ISSUE THREAD

**Issue by jmetev1** [freeCodeCamp/freeCodeCamp#50569]
### Describe the Issue

I feel like this is not supposed to look this way. But if I'm wrong, sorry!

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-2

### Your code

```


none
```

### Expected behavior

i think the instructions and button should be below the editor.

### Screenshots

<img width="781" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20405975/2e1e688c-3801-4ffa-b9a9-7071ba60e319">

### System

- Device: 2022 macbook pro
- OS: macos 13.3.1 (a) 
- Browser: chrome
- Version:  113.0.5672.126 (Official Build) (arm64)

**Comment by lasjorg** [comment]
The current locations make it very clear what part of the code you have to update.

I will say, it can maybe get a little bit awkward if the section you have to update contains a lot of code. A few CSS-related challenges come to mind, but it isn't an issue in my opinion.

**Comment by jmetev1** [comment]
got it. i'll close it.
