### ISSUE TITLE
search bar at top of page unable to find challenge

### ISSUE THREAD

**Issue by jmetev1** [freeCodeCamp/freeCodeCamp#50574]
### Describe the Issue

I wanted to get back to the challenge i was working on "Write a Counter with Redux", so i searched for it in search bar from home page. The result is : https://www.freecodecamp.org/news/search/?query=Write%20a%20Counter%20with%20Redux with no results. Is that expected? 

Kind of separate: Should anyone ever land on that page of empty results? It seems like a very unhelpful place. 

Kind of separate 2: Using the search bar from locally running instance "http://localhost:8000/" actually takes you to search on prod "https://www.freecodecamp.org/news/search/?query=write%20a%20counter%20with%20redux"

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Go to 'home page'
2. Click on 'search bar', enter "Write a Counter with Redux"
3. see no results;

### Expected behavior

I would hope that search would find the exercise.

### System

- Device: macbook pro 2022
- OS: macos
- Browser: chrome latest

**Comment by jmetev1** [comment]
I see this was done deliberately in https://github.com/freeCodeCamp/freeCodeCamp/pull/36656/files . But it sounds like maybe that was intended to be temporary?

**Comment by moT01** [comment]
Yes, this is intentional for now. I don't think we want to add challenges back to the this search at the moment. There is a tentative plan to add or move the search to the /learn page and include challenges and other things in the search.

**Comment by jmetev1** [comment]
To me it seems like the thing about freecodecamp is that most users are transitory, they come in and use it for a week to year probably and then move on. So the people who maintain it understand the weird things but probably most users think it's weird as hell that they can't search for a challenge. So i guess i'll close this?

**Comment by ahmaxed** [comment]
Thank you for bringing this to our attention. 

There are some initiatives such as https://github.com/freeCodeCamp/freeCodeCamp/issues/48800 that will help users navigate between challenges and help users find previously visited concepts easier. 

I will close this issue for now, but I will look into the search queries too see if there are any patterns.
