### ISSUE TITLE
In Machine Learning course the Linear regression example is actually Linear classification

### ISSUE THREAD

**Issue by Boh0iQuee3** [freeCodeCamp/freeCodeCamp#50590]
I  am reporting what I think is a mistake in the “Machine Learning with Python” course.

In __Module 3: Core Learning Algorithms__, linear regression is introduced with an exercise of predicting the survivability of a person from the Titanic passenger data. The mistake is I think this is actually a linear _classification_, not a linear _regression_. Because regression is for predicting a continuous value such as the age, weight, or height of a person; while classification is for predicting a discrete value like whether a person survives or not.

I hope this is clear enough. If not, I can clarify further.

**Comment by Himasnhu-AT** [comment]
@Boh0iQuee3 Thank you for your review. I want to review this issue further.

**Comment by vikas70607** [comment]
Can you include some url to the course

**Comment by piyushdubey490** [comment]
Hey Maintainer , Can you Assign this issue to me . I will review the thing and report and if there is some mistake then i will edit changes
