### ISSUE TITLE
Consider not running github actions on PR's from first timers

### ISSUE THREAD

**Issue by jmetev1** [freeCodeCamp/freeCodeCamp#50593]
**Describe the bug**
Running ci for any pr has two downsides, costs and potential abuse of ci.  I'm not sure if cost is a concern, but seeing a pr like #50577 makes me think people are trying to run things we don't want.

Or #50583 , we can see that github action closed it automatically, but also ran all the tests for it, correct? And more generally I see that a lot of pr's get closed without merging due to being total spam or just not great. I think there are a few possible solutions.
1. (more mild). Don't run tests if pr is autoclosed. 
2. (more dramatic and more work) Require someone with higher permissions to run ci.
3. something else?

This [github article](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) says `By default, all first-time contributors require approval to run workflows.` but maybe that doesn't apply here because it doesn't appear to be that way currently.

Hope this is helpful.

**Comment by jmetev1** [comment]
One example: we probably didn't want to run whatever this pr was trying to do eh? https://github.com/freeCodeCamp/freeCodeCamp/pull/50577/files

**Comment by raisedadead** [comment]
This is already enabled to our liking. We tweak the restriction during high-interaction periods like hacktoberfest.

We have a discord and a forum for general queries that do not warrant an issue. When in doubt, it is helpful to check first and then report.
