### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by bluestealth** [FreeCodeCamp/freecodecamp#506]
Wrap each of your checkboxes inside its own div with the class "col-xs-4". -> Wrap your submit button inside its own div with the class "col-xs-5".
Wrap each of your checkboxes inside its own div with the class "col-xs-4". -> Warp your text input field inside its own div with the class "col-xs-7".
Wrap your all of your checkboxes inside one div with the class "row".  -> Wrap your text input field and submit button inside one div with the class "row".

**Comment by QuincyLarson** [comment]
@bluestealth We've now fixed this. Thanks!
