### ISSUE TITLE
Reddit - Give Mods/Staff Flair

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5060]
FCC Staff should be given some sort of distinctive coloring/flagging on the Reddit forums.  I didn't even realize that I was reading a post by Quincy the other day until I saw the name.  We need to take advantage of the mod tools to set a distinctive color and/or icon.

I think the same changes that enable user flair enable mod flair:
https://www.reddit.com/r/modhelp/comments/m58qm/user_flair_tutorial_7_easy_steps_to_enable/

It's probably as easy as setting some CSS.

**Comment by ltegman** [comment]
This is live on our reddit now.
