### ISSUE TITLE
What is TCO (Tail Call Optimization)

### ISSUE THREAD

**Issue by carl-parrish** [FreeCodeCamp/FreeCodeCamp#5061]
http://www.2ality.com/2015/06/tail-call-optimization.html is a decent explanation as it relates to javascript but honestly the best source I know of explains it for Ruby. http://nithinbekal.com/posts/ruby-tco/

**Comment by jameswinegar** [comment]
Why would you use TCO instead of refactoring into a loop structure?

**Comment by bugron** [comment]
cc @brianamarie

**Comment by bugron** [comment]
Moved this issue to Hikes repository, see https://github.com/FreeCodeCamp/hikes/issues/166. @carl-parrish thanks for posting. Closing.
