### ISSUE TITLE
Redesign the testimonial section

### ISSUE THREAD

**Issue by kaleemullah786** [freeCodeCamp/freeCodeCamp#50611]
### Describe the Issue

Testimonials can be made better by redesigning and adding a slider for better feel

### Affected Page

https://www.freecodecamp.org

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/'

### Expected behavior

design a better looking card

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bbsmooth** [comment]
> design a better looking card

This is a pretty broad and generic description of the problem. Can you be a little more specific about what issues you have with the testimonial cards and what improvements you would make?

**Comment by kaleemullah786** [comment]
Something like this:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/108057345/5f52ec3b-1660-4a69-ba8f-73014bdde7d2)

**Comment by bbsmooth** [comment]
I understand that carousels are all the rage and a lot of sites use them, but to be honest, they are an accessibility nightmare and I highly recommend we do not use one here.

That's not to say we can't use your styling if people like it better than the current styling. Just don't turn it into a carousel.

**Comment by kaleemullah786** [comment]
> I understand that carousels are all the rage and a lot of sites use them, but to be honest, they are an accessibility nightmare and I highly recommend we do not use one here.
> 
> That's not to say we can't use your styling if people like it better than the current styling. Just don't turn it into a carousel.

I agree.

**Comment by munsuyog** [comment]
The testimonial section can be designed something like this with a dark background. 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/36353964/dc68e491-925a-4a23-905c-138124f0a9c9)

**Comment by ahmaxed** [comment]
Thank you all for your feedback. We need a mechanism to see if the new changes affect conversion. Currently A/B testing is configured for singed in users.  Once that changes, we could A/B the whole landing page.

**Comment by Shobhitsingh-2503** [comment]
Is this issue still open I would Like to work on the testimonial section @ahmaxed ?

**Comment by ahmaxed** [comment]
Thank you for your interest. We need to configure Growthbook first.

**Comment by imparth7** [comment]
Is this issue still open I would Like to work on your testimonial as you describe to create like this https://dribbble.com/shots/6255426-Daily-UI-Challenge-039-Testimonials @imparth7.

**Comment by imparth7** [comment]
> The testimonial section can be designed something like this with a dark background. ![image](https://user-images.githubusercontent.com/36353964/243271228-dc68e491-925a-4a23-905c-138124f0a9c9.png)

This is looking so good also creating like this is more effective for freecodecamp website.

**Comment by KSSaiTeja** [comment]
i am interested to do this design. i will be happy to work on this issue if this assigned to me.

**Comment by ahmaxed** [comment]
We would need to finalize the growthbook set up so we could measure the effectiveness of the changes easier.

**Comment by ahmaxed** [comment]
I am closing this issue in favor of a complete landing page redesign:
https://github.com/freeCodeCamp/freeCodeCamp/issues/54656
