### ISSUE TITLE
The first line of sample code has a problem

### ISSUE THREAD

**Issue by Jane2016** [FreeCodeCamp/FreeCodeCamp#5063]
I kept getting an error message "SyntaxError: Unexpected token var" even though I have checked my code, then I noticed the first line "-+var Car = function() {" has extra -+ signs in the beginning. Deleting the two signs solves the problem. Apparently they have been smuggled into the sample!

**Comment by gasperno** [comment]
Please provide details for the issue. Provide more details on how to replicate the issue, the waypoint of URL, screenshot of the issue and your browser details. 
Read this link for instructions on [how to create an issue]
(https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue).
Happy Coding!

**Comment by SaintPeter** [comment]
My guess is that the default code was corrupted in some way.  Can you please try resetting the code and trying again?

In the future please provide a link to the relevant challenge.

**Comment by ltegman** [comment]
Closing as stale. Please open an issue with more details if you are still having problems.

Thanks and happy coding!
