### ISSUE TITLE
Motivational quotes might be confusing

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#50634]
Carrying on from #46429:

Some of the `compliments` in our [quotes object](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/motivation.json), such as `They're in another castle`, may not make sense to campers.

Some of these are pop-culture references, like `"Legen - wait for it - dary!",` and `"Moon Prism Power!"`. As someone who is familiar with those two particular phrases, seeing them pop up in my learning journey was a nice treat. However, campers who are not familiar with the references might not understand the meaning here.

Do we want to go through and clean up the ones that don't directly compliment the camper?

Original Conversation: https://github.com/freeCodeCamp/freeCodeCamp/pull/46429#issuecomment-1581267853

**Comment by moT01** [comment]
I vote to leave them. I didn't get some of them - but the ones I did, were nice to see.

**Comment by bbsmooth** [comment]
Ya, I'm fine with leaving them. My main concern is that we should also make it clear to screen reader users that they have passed the step by unhiding the check mark icon from them and giving it an accessible name like "Step completed". Then they would hear "Step completed", and then the quote.

**Comment by ahmadabdolsaheb** [comment]
Thank you for creating a separate issue to address the quotes.
How about keeping the success message. And having the quote in the row of its own so there is no confusion?
In future iterations we could make the success message shorted and merge both if necessary.

**Comment by ahmadabdolsaheb** [comment]
How about this for the success state so there is no confusion. 

<img width="567" alt="Screenshot 2023-06-09 at 4 31 10 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/f1fc94df-581c-4014-a812-18ac02ae1756">

**Comment by CBID2** [comment]
So…is this issue solved or???

**Comment by ahmadabdolsaheb** [comment]
Yes, the related pr will be modified accordingly.
