### ISSUE TITLE
setInterval/clearInterval probably needs an introduction

### ISSUE THREAD

**Issue by WaveFunctionP** [FreeCodeCamp/FreeCodeCamp#5064]
Challenge [Zipline: Build a Pomodoro Clock](http://www.freecodecamp.com/challenges/zipline-build-a-pomodoro-clock) has an issue.

A discussion came up on reddit that I believe would be relevant here:

https://www.reddit.com/r/FreeCodeCamp/comments/3vp1ag/which_part_of_the_curriculum_of_fcc_do_you_think/cxq6tjx?context=3

I believe setInterval/clearInterval, and timing in general, is of enough usefulness to warrant its own introduction earlier. Particularly because the api usage is inconsistent.

"The critical error is that, besides the api designer being on crack and making you register and unregister using different methods, you have to define "var foo = function(){};" and then you can unregister foo for some arcane reason."

**Comment by ltegman** [comment]
I definitely agree that it deserves an introduction, especially given how unintuitive everything about it is.

**Comment by SaintPeter** [comment]
I could see a couple of waypoints on timing and asynchronous events, as part of a larger section on functions with callbacks.

**Comment by BerkeleyTrue** [comment]
This work has moved to https://github.com/FreeCodeCamp/CurriculumExpansion
