### ISSUE TITLE
Error when checking typeof string and type of number 

### ISSUE THREAD

**Issue by coded9** [FreeCodeCamp/FreeCodeCamp#5065]
Challenge [Waypoint: Using typeof](http://www.freecodecamp.com/challenges/waypoint-using-typeof#?solution=console.log(typeof%20%22Ashok%22)%3B%0Aconsole.log(typeof%200)%3B%0Aconsole.log(typeof%20%5B%5D)%3B%0Aconsole.log(typeof%20%7B%7D)%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
console.log(typeof "Ashok");
console.log(typeof 4);
console.log(typeof []);
console.log(typeof {});



```
typeof 4  and typeof "Ashok" is returning undefined

**Comment by ltegman** [comment]
The "console" on the left of the page displays the return value of the last function call. In this case that's console.log, which has a return value of `undefined`. If you open up the developer tools in Chrome you'll see what is being console.logged and it is correct.

This is not passing because the challenge regex is looking for you to have logged the exact same values as the example code, even though it doesn't specify that is the case. I'm leaving this bug open because someone should change the test to accept any value of the given type.

**Comment by alan1001110** [comment]
I'll do this (change to accept any value of the given type).

**Comment by alan1001110** [comment]
I'll do this (change the test to accept any value of the given type).

**Comment by alan1001110** [comment]
@ltegman 

I've got something I think will work for most of what I think is likely to come up in this exercise. A lot of the syntax checking I was thinking to do with regex just gets done by the browser.  The big exception I can think of would be if the user were to assign a value to a variable and then do `console.log(typeof var);`.  

I could try to make the tests work for variables that don't change value after declaration, and for weird edge cases. But that leaves a couple problems.  First, the line length for the `assert(...)` will get really long.  Second, I can't think of a way to deal with a variable that changes value, (at least not the way the waypoint is currently structured).  It also seems like it's probably more work than it's worth.

Thoughts?  Should I just put in a PR for what I've got?  

I also am wondering generally about quality checks/confidence level before submitting a PR, both for this and in the future.  In this case, I composed the regex (only slightly changing the existing), did a few tests for each, and converted to JSON   .. and then of course did a few edits to the JSON by hand. :-)  How much QA should I be doing before submitting a PR?  I don't have FCC running locally.

      [
        "assert(editor.getValue().match(/console\\.log\\(typeof[\\( ](\".*\"|'.*')\\)?\\);/gi), 'message: You should <code>console.log</code> the <code>typeof</code> a string.');",
        "assert(editor.getValue().match(/console\\.log\\(typeof[\\( ](-?\\d+\\.?\\d*)\\)?\\);/gi), 'message: You should <code>console.log</code> the <code>typeof</code> a number.');",
        "assert(editor.getValue().match(/console\\.log\\(typeof[\\( ]\\[.*\\]\\)?\\);/gi), 'message: You should <code>console.log</code> the <code>typeof</code> an array.');",
        "assert(editor.getValue().match(/console\\.log\\(typeof[\\( ]\\{.*\\}\\)?\\);/gi), 'message: You should <code>console.log</code> the <code>typeof</code> a object.');"
      ]

**Comment by SaintPeter** [comment]
Well, getting FCC running locally should be a goal.  It can be very challenging to debug complex regex just in the JSON.

Also, if you get FCC running locally, you can "easily" get COM1000 running locally and it's an order of magnitude easier to write regexes when you don't have to double-escape everything.

RE: Your Regexes -  
What about legal whitespace?  I use `\s*` between each and every character where it would be valid to have whitespace.

If you need a hand:   
https://gitter.im/FreeCodeCamp/HelpContributors

**Comment by alan1001110** [comment]
I did the regex without JSON first, then added the extra escapes afterwards, which was super-easy.  What I shouldn't have done is later tweak the regex in the JSON :stuck_out_tongue_winking_eye: 

Okay, I'll allow more white space, get rid of some false positives, test the regex, convert to JSON, commit, and do a PR.  I'll ignore use of variables.

Sound good?

**Comment by SaintPeter** [comment]
Sounds like a plan to me :smile:
