### ISSUE TITLE
I've tricked the test to pass without passing any arguments to the contructor

### ISSUE THREAD

**Issue by svlasov** [FreeCodeCamp/FreeCodeCamp#5066]
Challenge [Waypoint: Make Unique Objects by Passing Parameters to our Constructor](http://www.freecodecamp.com/challenges/waypoint-make-unique-objects-by-passing-parameters-to-our-constructor#?solution=var%20Car%20%3D%20function(wheels%2C%20seats%2C%20engines)%20%7B%0A%20%20%2F%2FChange%20this%20constructor%0A%20%20this.wheels%20%3D%20wheels%20%7C%7C%203%3B%0A%20%20this.seats%20%3D%20seats%20%7C%7C%201%3B%0A%20%20this.engines%20%3D%20engines%20%7C%7C%202%3B%0A%7D%3B%0A%0A%2F%2FTry%20it%20out%20here%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A(function()%20%7Breturn%20JSON.stringify(myCar)%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function(wheels, seats, engines) {
  //Change this constructor
  this.wheels = wheels || 3;
  this.seats = seats || 1;
  this.engines = engines || 2;
};

//Try it out here
var myCar = new Car();

// Only change code above this line

(function() {return JSON.stringify(myCar);})();

```

**Comment by ltegman** [comment]
I don't actually see this as a problem. The use of default values in the constructor shows a knowledge of what you're doing and I don't think someone who knows to do that is someone who doesn't know how to pass parameters to something.

I'm leaving this open for discussion but I don't personally have a problem with this passing.

**Comment by DDaems** [comment]
Neither do i, code is legit.

**Comment by svlasov** [comment]
Ok then :)

**Comment by ltegman** [comment]
Awesome, and good job with the default values in your constructor! :smile:
