### ISSUE TITLE
Accessing Nested Objects - Allow destructuring?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#50662]
### Describe the Issue

Probably not all that important, although it is valid syntax and it does what is asked for.

```
const myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Valid, non-passing code
const { 'glove box': gloveBoxContents } = myStorage.car.inside;
console.log(gloveBoxContents) // maps

// Expected solution
// const gloveBoxContents = myStorage.car.inside["glove box"];
```

Tests
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/accessing-nested-objects.md

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-nested-objects

### Your code

```



```

### Expected behavior

Allow destructuring?

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by augerT** [comment]
The prompt does specifically say "Use dot notation for all properties where possible, otherwise use bracket notation."

**Comment by lasjorg** [comment]
> The prompt does specifically say "Use dot notation for all properties where possible, otherwise use bracket notation."

I was originally going to mention that specific part of the challenge text. Initially, it did almost make me not open the issue as well. But then when I re-read it again a few times it isn't actually saying you _have to_ dot onto all the properties.

What it is saying is that if you can dot onto the property do that, otherwise if you can't, use bracket notation. So the way I understand it is, it is referring to properties you can't access using dot notation and how you should use bracket notation when that is the only possible way of doing it. It isn't actually saying you can't use destructuring. At least that is how I read the intention of the sentence.

Anyway, like I said, I don't think supporting it is that important. But allowing (or not allowing) destructuring also does not seem to be part of the requirements.

**Comment by ojeytonwilliams** [comment]
That's a fair point, @lasjorg. There is a bit of ambiguity about that sentence.

On reflection, I've changed my mind. There's shouldn't be any harm in accepting solutions that use destructuring.

**Comment by Jordan2018** [comment]
Testing 122
https://kdta.io/zGfN9

**Comment by Jordan2018** [comment]
Testing 133: https://kdta.io/mscqJ

**Comment by Riya267** [comment]
Hi @ojeytonwilliams @lasjorg , I have implemented the changes needed to resolve the destructure issue. Could you please take a moment to review the pull request I have raised? 
Thank you!
