### ISSUE TITLE
reverse 

### ISSUE THREAD

**Issue by Gorannn** [FreeCodeCamp/FreeCodeCamp#5068]
Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse#?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20array.reverse(function(val)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0Areturn%20val%0A%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.

var newArray = array.reverse(function(val)
                            {
return val
});
                            

// Only change code above this line.


```

**Comment by ltegman** [comment]
Reverse does not take a callback. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for help in the future.

Thanks and happy coding!
