### ISSUE TITLE
Improvement in Pass an Array as Props module

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#50687]
### Describe the Issue

Currently, the second paragraph within the [Pass an Array as Props](https://www.freecodecamp.org/learn/front-end-development-libraries/react/pass-an-array-as-props) module happens to be as follows:

The child component then has access to the array property `colors`. Array methods such as `join()` can be used when accessing the property. `const ChildComponent = (props) => <p>{props.colors.join(', ')}</p>` This will join all `colors` array items into a comma separated string and produce: `<p>green, blue, red</p>` Later, we will learn about other common methods to render arrays of data in React.

For the sake of more clarity and to make it easier to read, I think the above paragraph should be as follows:

The child component then has access to the array property `colors`. Array methods such as `join()` can be used when accessing the property. 

```jsx
const ChildComponent = (props) => <p>{props.colors.join(', ')}</p>
``` 

This will join all `colors` array items into a comma separated string and produce: `<p>green, blue, red</p>` Later, we will learn about other common methods to render arrays of data in React.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/pass-an-array-as-props

### Expected behavior

For the sake of more clarity and for better readability, the second paragraph within the [Pass an Array as Props](https://www.freecodecamp.org/learn/front-end-development-libraries/react/pass-an-array-as-props) module should be as follows:

The child component then has access to the array property `colors`. Array methods such as `join()` can be used when accessing the property. 

```jsx
const ChildComponent = (props) => <p>{props.colors.join(', ')}</p>
``` 

This will join all `colors` array items into a comma separated string and produce: `<p>green, blue, red</p>` Later, we will learn about other common methods to render arrays of data in React.

### Screenshots

<img width="519" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/36872756/bc71fcaa-5b98-4e8d-a37b-0a0800ab11da">

### System

- Device: Laptop
- OS: macOS 13.0.1
- Browser: Chrome
- Version: 107.0.5304.110

**Comment by theprasadjadhav** [comment]
please assign this to me
