### ISSUE TITLE
running locally i can't access other language versions

### ISSUE THREAD

**Issue by jmetev1** [freeCodeCamp/freeCodeCamp#50680]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**

**To Reproduce**
The real url for spanish is https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator so i expect that when running locally I could click on globe icon and then choose spanish to go to:
http://localhost:8000/espanol/learn/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator
But instead i get gatsby dev 404 page.

**Expected behavior**
I expect to be able to get to spanish version page.

**Screenshots**
<img width="1429" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20405975/fa9b87a2-fd95-4809-a6a0-86324226fa65">

**Additional context**

**Comment by naomi-lgbt** [comment]
This is actually because the app doesn't build every language at once. It builds a single language - our internationalised sites are separate instances of the application.

The language selector does not work locally because there is, in fact, nothing at the `/espanol` endpoint.

**Comment by ojeytonwilliams** [comment]
We could add a note to: https://contribute.freecodecamp.org/#/troubleshooting-development-issues like

---

## Working with other languages

To see how the client renders in another language go to [testing the client app in a world language](https://contribute.freecodecamp.org/#/how-to-work-on-localized-client-webapp?id=testing-the-client-app-in-a-world-language) 

---

I think that should be enough.
