### ISSUE TITLE
Local Scope and Functions semicolon issue

### ISSUE THREAD

**Issue by lawfets** [freeCodeCamp/freeCodeCamp#50692]
### Describe the Issue

I think that semicolons are a must in javascript. Nevertheless I made a variable and didn't finish the line with a semicolon. It still executed fine without mistakes.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions

### Your code

```
function myLocalScope() {
  // Only change code below this line
  let myVar = 5   // no semi colon present, still executes ok
  console.log('inside myLocalScope', myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log('outside myLocalScope', myVar);


```

### Expected behavior

I expected it to fail. in codepen I got a clear warning the semicolon was missing. In freecodecamp it didn't fail.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
windows 10
vivaldi browser 6.1.3035.75 (Stable channel) (64-bit)

JavaScript | V8 11.4.183.19

**Comment by bbsmooth** [comment]
> I think that semicolons are a must in javascript.

Semicolons are not required in JS. But there are situations in which not using a semicolon can have an unexpected result. I personally always use them and would encourage everyone else to as well. So personally, I think they are a "must". But technically they are not.

I think that one of the guiding principles of FCC is that valid code should always pass, even if it isn't what we would consider a "best practice". So I'm guessing that FCC will want to continue to allow JS without semicolons to pass.
