### ISSUE TITLE
Improve hint for CatPhotoApp step 15

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#50705]
### Describe the Issue

I've run into this enough in the forums that it might be time to fix it. A lot of people leave off the closing `a` tag when turning the image into a link. The hint they get is:

"You should only add one opening anchor (a) tag. Please remove any extras."

Which is confusing since the objective of the step is to add a second link to the page and the hint makes it sound like there should only be one. Instead, the hint should probably remind them that an anchor element needs both an opening and closing `a` tag. Whether we want to spell it out even further by telling them that they are missing the closing `a` tag I will leave up to the hive mind.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-15

### Your code

```
<a href="https://freecatphotoapp.com"><img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back.">
```

### Expected behavior

If we don't want to be too explicit we could do something like:

"Hint: Creating a link with the anchor element requires both an opening and closing `a` tag."

Or:

"Hint: You must use both an opening and closing `a` tag to create a link."

Or if we want to be more direct:

"Hint: You are missing a closing `a` tag after the image."

### System

N/A

**Comment by jeremylt** [comment]
I think being explicit about a closing tag being needed is the way to go this early in the curriculum

**Comment by Sembauke** [comment]
> I think being explicit about a closing tag being needed is the way to go this early in the curriculum

Let us go with this.

**Comment by AsheerAF911** [comment]
Yeah I read through your Issue and it is quite confusing to get this hint. The explicit hint you mentioned is the way to go.

**Comment by ValdineiJunior** [comment]
Can I make that change ? I just did this locally and works.

**Comment by bbsmooth** [comment]
@ValdineiJunior This has a help wanted tag, so anyone is free to open a PR for this.

**Comment by jeremylt** [comment]
I think that we need to decide exactly what to change - just changing the text of the hint without changing the associated test will cause more problems

**Comment by Jiaxi-Wu-Dev** [comment]
hello

**Comment by EMG2023** [comment]
Is this designed just to discourage newbies like me? Over an hour on this step. No previously posted code nor clarifications helped... just sent me down new rabbit holes. You need to know code to decipher the clarifications. Must be part of a hazing process. THIS code works as of the date of this posting: <a href="https://freecatphotoapp.com"><img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg" alt="A cute orange cat lying on its back."></a>
<h1>Now I know I am crazy enough to continue down this road/ rabbit hole universe</h1>

**Comment by jeremylt** [comment]
@EMG2023 please use the freeCodeCamp forum if you have questions about your code or you get stuck. forum.freeCodeCamp.org
