### ISSUE TITLE
Intent to join Github Organization

### ISSUE THREAD

**Issue by purnimanagpal23** [freeCodeCamp/freeCodeCamp#50707]
**Is your feature request related to a problem? Please describe.**
Not a member of freecodecamp github organization

**Describe the solution you'd like**
As mentioned in one of the youtube videos on [youtube](https://www.google.com/search?q=how+to+contribute+in+open+source+freecodecamp&oq=how+to+contribute+in+open+source+freecodecamp&aqs=chrome..69i57j33i160l3.8852j0j7&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:2e0d09a7,vid:yzeVMecydCE) , it was mentioned that we can raise the issue to be added in the opensource community

#### Kindly send me the invite to be added to github organization.

**Describe alternatives you've considered**
An invite to my account can help me be a part of the community to learn and contribute

**Additional context**
No response
```[tasklist]
### Tasks
```

**Comment by jdwilkin4** [comment]
HI @purnimanagpal23 ! 

> it was mentioned that we can raise the issue to be added in the open source community

The best way to get involved with freeCodeCamp is by contributing. 

You can find our contributing documentation here
https://contribute.freecodecamp.org/#/

Any open issues that are marked with the `help-wanted` or `good-first-issue` labels are open for contribution.

If you ever need help when working on an issue, then you can reach out on the [discord](https://discord.com/invite/PRyKn3Vbay) or [forum](https://forum.freecodecamp.org/c/contributors/3).

Hope that helps 👍
