### ISSUE TITLE
POST /user/user-token

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#50720]

**Comment by ShaunSHamilton** [comment]
I am just thinking about the logic of this for Post-MVP:

Currently, it appears `id` is unique, and `userId` is not. So, many tokens can be associated with any one `userId`, but the `id` should be unique.

1) Why would/could we want a one-to-many of `userId`-`id`?
2) Why do we use `nanoid` to create the `id`s, when we could just use `ObjectId` with `_id` and be guaranteed uniqueness from MongoDB's side?

**Comment by ojeytonwilliams** [comment]
1. I'm pretty sure we want at most one token per user. All that needs to happen is that the VM has a token that it use to prove to us that one of our users created it. I can't see a reason to have more than one active at once, though.
2. I don't think we do. What matters is that the token can't be forged and that the id is unique. So, yeah, ObjectIds should be fine.

I went with the current implementation just because that was the path of least resistance.

**Comment by ojeytonwilliams** [comment]
The only problem I can see with using ObjectId is that it will invalidate old tokens. However, getting a new token is easy: try to start a RDB lesson.

That means that, as long as we can get people to reload the site, we should be fine to drop the current UserToken collection and start fresh.

**Comment by ShaunSHamilton** [comment]
Well, I am not sure if we would just have a completely new collection or reuse this one, but I think our implementation becomes a bigger deal once we use this for API Keys - why I brought the above up.

**Comment by ojeytonwilliams** [comment]
Sorry, I mean drop the collection in the db and recreate it with an updated schema.

i.e. we have

```prisma
model UserToken {
  id      String   @id @map("_id")
  created DateTime @db.Date
  ttl     Float
  userId  String   @db.ObjectId

  @@index([userId], map: "userId_1")
}
```

and we want that, but with

```prisma
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
```

> I think our implementation becomes a bigger deal once we use this for API Keys

Shouldn't we use a different collection entirely?

**Comment by ShaunSHamilton** [comment]
> Shouldn't we use a different collection entirely?

Maybe, but this does have what we want: unique id, ttl, and maybe scopes
