### ISSUE TITLE
Waypoint: Clone an Element Using jQuery: I completed the code and now the phone simulator is showing THREE target5 buttons!

### ISSUE THREAD

**Issue by johan718** [FreeCodeCamp/FreeCodeCamp#5072]
Challenge [Waypoint: Clone an Element Using jQuery](http://www.freecodecamp.com/challenges/waypoint-clone-an-element-using-jquery#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target1%22).prop(%22disabled%22%2C%20true)%3B%0A%20%20%20%20%24(%22%23target4%22).remove()%3B%0A%20%20%20%20%24(%22%23target2%22).appendTo(%22%23right-well%22)%3B%0A%20%20%20%20%24(%22%23target5%22).clone().appendTo(%22%23left-well%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

## Issue

I believe I've found bug in the phone simulation in **Waypoint: Clone an Element Using jQuery**:

I entered the code to clone ```target5``` and append it to ```left-well```, and now I see three **target5** buttons in the phone simulator. FCC says my code is correct and advances me to the next challenge. The following challenges also show three target5 buttons:
* Waypoint: Target the Parent of an Element Using jQuery
* Waypoint: Target the Children of an Element Using jQuery

@qualitymanifest confirms this issue on his **Linux** box.

![image](https://cloud.githubusercontent.com/assets/5673126/11647398/76751658-9d35-11e5-8fcf-112ab89c6920.png)

## My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by ltegman** [comment]
I can confirm this behavior in both Chrome and Firefox. For me it only happens on page load, but not if I remove the line and then add it back in. It looks like the script is being run twice on page load.

**Comment by johan718** [comment]
Funny thing: when I ```command+a``` selected all my code to copy it, the extra button disappeared as well.

I couldn't begin to imagine why that is. Maybe ```unfocus```?

**Comment by KethuSingh** [comment]
Even i got this bug. but if i start editing the code it disappears, it again appears while page loading. I just moved to another task.

**Comment by czanon** [comment]
+1 The same as stated by you guys...either in Firefox (Developer Edition) and Chrome...last update in both. Bahhh very wierd...

**Comment by augmt** [comment]
Both [`common.updatePreview$`][1] and [`common.getJsOutput`][2] are called within [`common.executeChallenge$`][3]. They also evaluate JavaScript which leads to scripts being run twice on resets, test runs, and page load.

[1]: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/74d5c0bf006b31c5f37f7d27b676773b35cd1284/client/commonFramework/update-preview.js#L62-L96
[2]: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/74d5c0bf006b31c5f37f7d27b676773b35cd1284/client/iFrameScripts.js#L13-L26
[3]: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/74d5c0bf006b31c5f37f7d27b676773b35cd1284/client/commonFramework/execute-challenge-stream.js#L18-L58

**Comment by johan718** [comment]
@ltegman you may want to check out @augmt's last comment.

**Comment by johan718** [comment]
@ltegman you may want to check out @augmt's last comment.

**Comment by trigal2012** [comment]
+1

**Comment by satishag** [comment]
Same issue... Is something in the library causing this behaviour?

**Comment by HoBi** [comment]
I think it's a bug with iframe on loading page. Just generate an iframe after a page is fully loaded?

**Comment by LujunWeng** [comment]
+1
I agree that the script is being run twice.

**Comment by iorrah** [comment]
+1

The script running twice.

When we run `alert("test");` we can see the `alert` message twice.

**Comment by maverick2** [comment]
+1

**Comment by smrajagopal** [comment]
So, script runs twice. I think the second time it runs is the proper one. Because the first time it runs roots back to a GoogleAnalyticsObject related script element at the least that is what I see from my developer console which I don't understand why:

![image](https://cloud.githubusercontent.com/assets/1938039/12075769/b8d2947c-b1b1-11e5-84c9-0da4bdac8c7a.png)

FYI. Just posting my observation. Not making any conclusion here!

**Comment by patsul12** [comment]
So it's clear that at some point the jQuery is being run twice, 

What's interesting is that if you change the code to look like this:
```
<script>
  $(document).bind("ready",function(e) {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```
the issue is resolved.

![before](http://imgur.com/3DIl3Ms.png)
![after](http://i.imgur.com/Pk1MwUV.png)

**Comment by TimKolo** [comment]
![new bitmap image](https://cloud.githubusercontent.com/assets/16649852/12574665/6b1ad2f0-c41f-11e5-92ca-c29c94a28394.jpg)

**Comment by santakmishra** [comment]
:+1:

**Comment by santakmishra** [comment]
+1

**Comment by cwkatzmann** [comment]
+1

**Comment by hostmaked** [comment]
+1

**Comment by ander-yamamoto** [comment]
+1

**Comment by efaryna** [comment]
+1

**Comment by mattlayton1986** [comment]
+1

**Comment by HuskyNator** [comment]
+1

**Comment by hrokr** [comment]
+1

I'd also add in a screenshot, but that's been done enough times before.

**Comment by barasof** [comment]
+1

**Comment by tinydoll** [comment]
+1

**Comment by hitman-snipe** [comment]
![image](https://cloud.githubusercontent.com/assets/8645675/13723153/37a9c6a8-e871-11e5-83b6-ec75f3747a6e.png)
I have this problem too.
This was my **first bug report** on GitHub. thank you.

**Comment by TushVins** [comment]
Same here

**Comment by MuraliNunna** [comment]
Yeah, i confirm the bug too..

**Comment by ltegman** [comment]
More comments confirming this bug are not necessary. We know this is a problem. All that's left if for someone to take ownership of fixing it.

**Comment by skeeve42** [comment]
+1

**Comment by WouterJoosse** [comment]
+1

**Comment by prakashpalanisamy** [comment]
+1 reproducible in firefox, safari and chrome on page reload, code-reset and run-test actions.

**Comment by gowtham1997** [comment]
+1

**Comment by erictleung** [comment]
As it was [mentioned earlier](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5072#issuecomment-198749940), this is a known issue and we are just waiting for someone to pick this up and fix it. Thus, we are locking this issue from further comment. You are free to "react" this to this issue with "+1" or other reactions using this button:

![image](https://cloud.githubusercontent.com/assets/2754821/15237957/d3d757a2-1887-11e6-8a9c-56f5b6449dd4.png)

**Comment by Bouncey** [comment]
Would disabling the `live reload` type behaviour of the iframe help the issue?
