### ISSUE TITLE
Suspected improper passing of parameters

### ISSUE THREAD

**Issue by isaacdozier** [FreeCodeCamp/FreeCodeCamp#5073]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy#?solution=function%20destroyer(arr%2Ca%2Cb%2Cc)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20var%20base%20%3D%20arr.filter(function(x)%7B%0A%20%20%20%20return%20x%20!%3D%3D%20a%20%26%26%20x%20!%3D%3D%20b%20%26%26%20x%20!%3D%3D%20c%3B%0A%20%20%7D)%3B%0A%20%20return%20base%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr,a,b,c) {
  // Remove all the values
  var base = arr.filter(function(x){
    return x !== a && x !== b && x !== c;
  });
  return base;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
This waypoint has an issue in regards to the parameters in use. The directions specifiy "1 or more parameters", this is in addition to the `arr` parameter. This means there is a need to add an indefinite amount of parameters to the function to properly filter the array in question.

`destroyer([1, 2, 3, 1, 2, 3], 2, 3);` <-this is wrong
should be this: 
`destroyer([[1, 2, 3, 1, 2, 3], 2, 3]);` 
or this 
`destroyer([1, 2, 3, 1, 2, 3], [2, 3]);`<-(would need additional parameter added to default code)

My current solution works but is NOT based on any parameter standard.

**Comment by ltegman** [comment]
The problem of having an unspecified number of parameters is why the sidebar links to an article about the [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments). You can use this to iterate through however many arguments are passed in.

Thanks and happy coding!

**Comment by isaacdozier** [comment]
Thanks! I realized this soon after I submitted this issue. It may be worth looking into re-wording the explanation. There is quite a jump in logic compared to the previous excersises, which up to this point used a set number of arguments.

consider that this is an easy implemented solution that passes:
```
function destroyer(arr,a,b,c){...
```
This one seems easy to cheat by accident and not even know it.

**Comment by ComputerRepairLasVegas-DJ** [comment]
Here is my code

function destroyer(arr) {
  // Remove all the values
  var args = [].slice.call(arr);
  console.log(arr.length + ' ' + args.toString());
  return arr;
}


the console shows 
6 1,2,3,1,2,3
6 1,2,3,1,2,3
7 1,2,3,5,1,2,3
5 3,5,1,2,2
4 2,3,2,3
3 tree,hamburger,53

from the reading I have done it should be
3 [1,2,3,1,2,3], 2, 3

**Comment by ComputerRepairLasVegas-DJ** [comment]
Ok.  Follow up.
Once I realized that the arr in the argument area of the destroyer function was unnecessary I got the challenge complete.

HINT
function destroyer() {
 var args = [].slice.call(arguments);
// rest of code
}
