### ISSUE TITLE
/news: Links heading 404 

### ISSUE THREAD

**Issue by testwithmukul** [freeCodeCamp/freeCodeCamp#50731]
### Describe the Issue

I found that 3 links on one of the /news page mentioned in the "Affected Page" are going 404. Seems the pages have been unpublished since I found those in web archives. The links are the following:

1. [Certified Associate in Software Testing (CAST)] - (https://www.softwarecertifications.org/cast/)
2. [Certified Test Engineer (CSTE)] - (https://www.softwarecertifications.org/cste/)
3. [Certified Software Quality Analyst (CSQA)] - (https://www.softwarecertifications.org/csqa/)

### Affected Page

https://www.freecodecamp.org/news/how-to-become-a-quality-assurance-engineer-qa-engineer-career-guide/

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/news/how-to-become-a-quality-assurance-engineer-qa-engineer-career-guide/'
2. Scroll down to or search using [cmd + f] or [ctrl + f] 'Do you need certifications to become a good QA engineer?'
3. Click on any of 3 below mentioned hyperlinks mentioned in Description.

### Expected behavior

The links should lead to the right path!

### System

- Device: [Galaxy M51, Macbook Air]
- OS: [Android 12, Mac OS 12.6.5]
- Browser: [Chrome, Brave]
- Version: [Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (x86_64)](https://brave.com/latest/)]

**Comment by ojeytonwilliams** [comment]
@jdwilkin4 could you take a look?

**Comment by jdwilkin4** [comment]
Hi @testwithmukul ! 

The article has been updated and the 404 links have been removed. 👍

**Comment by testwithmukul** [comment]
Thanks @jdwilkin4 and @ojeytonwilliams for the quick action. I am happy that I was able to contribute to such an esteemed organisation/community.
