### ISSUE TITLE
Help setting up .env file

### ISSUE THREAD

**Issue by ChristianLapinig** [FreeCodeCamp/FreeCodeCamp#5074]
When I run the command `npm run first-time`, I get a few errors. I'm wondering if it has to do with how I set up my `.env` file. This is how I have it set up:

```
MONGOHQ_URL='mongodb://localhost:27017/freecodecamp'


MANDRILL_PASSWORD=‘XXXXXX’
MANDRILL_USER=‘XXXXXXXX@gmail.com’


SESSION_SECRET=secretstuff
COOKIE_SECRET='this is a secret'

PEER=stuff
DEBUG=true
```

**Comment by ltegman** [comment]
`npm run first-time` causes problems for a lot of people. Could you paste the error you are getting?

**Comment by ChristianLapinig** [comment]
![screen shot 2015-12-07 at 8 45 17 pm](https://cloud.githubusercontent.com/assets/11323135/11647974/7ec76052-9d23-11e5-946e-cfb2420d2735.png)

**Comment by ChristianLapinig** [comment]
@ltegman

**Comment by ltegman** [comment]
Looks like `npm run create-rev` fails if the file already exists. What happens if you run `node seed/ && node seed/nonprofits`? Does that command work?

**Comment by ChristianLapinig** [comment]
I'm getting this

![screen shot 2015-12-07 at 9 00 09 pm](https://cloud.githubusercontent.com/assets/11323135/11648142/94399714-9d25-11e5-9cb3-c3e078510f8c.png)

**Comment by ltegman** [comment]
I think if you add entries for everything listed in the example .env this should resolve. You can just copy and paste from the example, it doesn't have to be real API keys. Let me know if that works.

**Comment by ChristianLapinig** [comment]
`node seed/ && node seed/nonprofits` seemed to work fine, but I still get the same errors

**Comment by ChristianLapinig** [comment]
It works when I run`gulp`

**Comment by gasperno** [comment]
@ChristianLapinig 
```
MONGOHQ_URL='mongodb://localhost:27017/freecodecamp'

FACEBOOK_ID=stuff
FACEBOOK_SECRET=stuff

GITHUB_ID=stuff
GITHUB_SECRET=stuff

GOOGLE_ID=stuff
GOOGLE_SECRET=stuff

LINKEDIN_ID=stuff
LINKEDIN_SECRET=stuff

MANDRILL_PASSWORD=stuff
MANDRILL_USER=stuff

TRELLO_KEY=stuff
TRELLO_SECRET=stuff

TWITTER_KEY=stuff
TWITTER_SECRET=stuff
TWITTER_TOKEN=stuff
TWITTER_TOKEN_SECRET=stuff

BLOGGER_KEY=stuff

SESSION_SECRET=secretstuff
COOKIE_SECRET='this is a secret'

PEER=stuff
DEBUG=true
```

I think you should leave the other keys and secrets in the same place. Do not delete them from .env file. Since you have MANDRILL_PASSWORD and MANDRILL_USER, replace the values against them. Leave the remaining lines intact.

**Comment by ChristianLapinig** [comment]
Ok so gulp runs the application fine, but npm run first-time has been giving me the same errors. Using the .env file from the example and everything seems to work (At least I think it does)

**Comment by SaintPeter** [comment]
FYI, for more direct support, you can get help here:
https://gitter.im/FreeCodeCamp/HelpContributors

**Comment by ltegman** [comment]
`run first-time` will not work after once. As soon as the `create-rev` part runs successfully it will fail. All it is is `create-rev` + `node seed/` so you're all good now :smile: Let us know if you have any more questions but I'm closing this bug!
