### ISSUE TITLE
Learn Bash module - In exercise 70.1, explicitly mention that it will give permission denied error

### ISSUE THREAD

**Issue by rahulsiloniya** [freeCodeCamp/freeCodeCamp#50752]
### Describe the Issue

The prompt for exercise 70.1 reads,
> Now, instead of using `sh` or `bash` to run your script. You can run it by executing the file and it will default to bash. Run your script by executing it with `./questionnaire.sh`

But it is intended to give a permission denied error.

Someone might think that this is an error and waste a lot of time figuring it out. The prompt should instead read,
> Now, instead of using `sh` or `bash` to run your script. Try executing it with `./questionnaire.sh` and read the error prompt.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-scripting-by-building-five-programs/build-five-programs

### Your code

```
./questionnaire.sh
```

### Expected behavior

Suggested prompt

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome

**Comment by moT01** [comment]
What do you think of this @rahulsiloniya:

``Now, instead of using `sh` or `bash` to run your script. You can run it by executing the file and it will default to bash. Execute your script with `./questionnaire.sh`. You will get a permission denied error.``

**Comment by rahulsiloniya** [comment]
@moT01 Yes, that is correct and understandable. We can go with that.
By the way, I couldn't figure out the `TUTORIAL.md` or any other file which was on CodeAlly virtual editor in the repo.
