### ISSUE TITLE
Learn More About CSS Pseudo Selectors By Building A Balance Sheet - Step 16 - Missing test

### ISSUE THREAD

**Issue by cremzeeee** [freeCodeCamp/freeCodeCamp#50790]
### Describe the Issue

As i love free code camp.org ; I would like to inform the problem and stay as minimal as i can.
staight on problem.

in : Responsive Web Design   > 
Learn More About CSS Pseudo Selectors By Building A Balance Sheet>
15.

QUALITY CONTROL
DEGRADING CODE ROBUSTNESS. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-16

### Your code

```

problem in line (51) answer passed though it is incomplete.

```
47:  <tr class="data">
48:               <th>Savings <span class="description">Funds set aside for emergencies.</span></th>
49:               <td>$500</td>
50:              <td>$650</td>
51:              <td >$728</td>
52:              </tr>

### Expected behavior

47:  <tr class="data">
                <th>Savings <span class="description">Funds set aside for emergencies.</span></th>
                <td>$500</td>
                <td>$650</td>
------> <td class="current">$728</td> <---------- answered passed without this line of code.
              </tr>

### Screenshots

![pending submission to freecodecamp org](https://github.com/freeCodeCamp/freeCodeCamp/assets/137513038/822c3769-7733-4788-8058-0df9ab64acb8)
![PENDING FREECODECAMP ORG](https://github.com/freeCodeCamp/freeCodeCamp/assets/137513038/d9525403-2e8a-448e-971b-f10f705b97ca)

### System

- Device: [Asus f17 gaming]
- OS: [ Windows 11]
- Browser: [Chrome]

### Additional context

thanks for such a go tutorial platform!

**Comment by cremzeeee** [comment]
Expected behavior

 <tr class="data">
                <th>Savings <span class="description">Funds set aside for emergencies.</span></th>
                <td>$500</td>
                <td>$650</td>
---->        <td class="current">$728</td> <-------
              </tr>

**Comment by ojeytonwilliams** [comment]
Hi @cremzeeee, thanks for the report. Could you share your full code here so that we can dig into what's going wrong?

**Comment by cremzeeee** [comment]
> Hi @cremzeeee, thanks for the report. Could you share your full code here so that we can dig into what's going wrong?

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Balance Sheet</title>
    <link rel="stylesheet" href="./styles.css">
  </head>
  <body>
    <main>
      <section>
        <h1>
          <span class="flex">
            <span>AcmeWidgetCorp</span>
            <span>Balance Sheet</span>
          </span>
        </h1>
        <div id="years" aria-hidden="true">
          <span class="year">2019</span>
          <span class="year">2020</span>
          <span class="year">2021</span>
        </div>
        <div class="table-wrap">
          <table>
            <caption>Assets</caption>
            <thead>
              <tr>
                <td></td>
                <th><span class="sr-only year">2019</span></th>
                <th><span class="sr-only year">2020</span></th>
                <th class="current"><span class="sr-only year">2021</span></th>
              </tr>
            </thead>
            <tbody>
              <tr class="data">
                <th>Cash <span class="description">This is the cash we currently have on hand.</span></th>
                <td>$25</td>
                <td>$30</td>
                <td class="current">$28</td>
              </tr>
              <tr class="data">
                <th>Checking <span class="description">Our primary transactional account.</span></th>
                <td>$54</td>
                <td>$56</td>
                <td class="current">$53</td>
              </tr>
              <tr class="data">
                <th>Savings <span class="description">Funds set aside for emergencies.</span></th>
                <td>$500</td>
                <td>$650</td>
-->>      <td class="current">$728</td>   <<----------- here if I press (control+enter) if i didnt exclude (class="current")then too it accepts it and proceeds ahead. sir it must give error here.(this is the working code sample.)
              </tr>
              <tr class="total">
              </tr>
            </tbody>
          </table>
          <table>
          </table>
          <table>
          </table>
        </div>
      </section>
    </main>
  </body>
</html>

**Comment by ojeytonwilliams** [comment]
Thanks for sharing that @cremzeeee, but the code you shared passes the tests. That's expected, since it has `class="current"` in the correct place. If I remove `class="current"` then it fails, as it should.

From your screenshot, it looked like you'd entered invalid code (i.e. without `class="current"`) and managed to pass the tests. However, I've been unable to replicate this behaviour.

If you have an example of invalid code that passes, could you share it here?

**Comment by gikf** [comment]
@cremzeeee first screen shot mentions step 15, the second one shows 16. Isn't the issue in the step 16?

**Comment by cremzeeee** [comment]
> Thanks for sharing that @cremzeeee, but the code you shared passes the tests. That's expected, since it has `class="current"` in the correct place. If I remove `class="current"` then it fails, as it should.
> 
> From your screenshot, it looked like you'd entered invalid code (i.e. without `class="current"`) and managed to pass the tests. However, I've been unable to replicate this behaviour.
> 
> If you have an example of invalid code that passes, could you share it here?



> 
sorry sir my mistake 
but it is there in step 16 

code


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Balance Sheet</title>
    <link rel="stylesheet" href="./styles.css">
  </head>
  <body>
    <main>
      <section>
        <h1>
          <span class="flex">
            <span>AcmeWidgetCorp</span>
            <span>Balance Sheet</span>
          </span>
        </h1>
        <div id="years" aria-hidden="true">
          <span class="year">2019</span>
          <span class="year">2020</span>
          <span class="year">2021</span>
        </div>
        <div class="table-wrap">
          <table>
            <caption>Assets</caption>
            <thead>
              <tr>
                <td></td>
                <th><span class="sr-only year">2019</span></th>
                <th><span class="sr-only year">2020</span></th>
                <th class="current"><span class="sr-only year">2021</span></th>
              </tr>
            </thead>
            <tbody>
              <tr class="data">
                <th>Cash <span class="description">This is the cash we currently have on hand.</span></th>
                <td>$25</td>
                <td>$30</td>
                <td class="current">$28</td>
              </tr>
              <tr class="data">
                <th>Checking <span class="description">Our primary transactional account.</span></th>
                <td>$54</td>
                <td>$56</td>
                <td class="current">$53</td>
              </tr>
              <tr class="data">
                <th>Savings <span class="description">Funds set aside for emergencies.</span></th>
                <td>$500</td>
                <td>$650</td>
                <td class="current">$728</td>
              </tr>
                <tr class="total">
                <th>Total <span class="sr-only">Assets</span></th>
                <td>$579</td>
                <td>$736</td>
                -------><td >$809</td><----- here it is i tested it right now. without including class="current" it proceeds further.
            </tbody>
          </table>
          <table>
          </table>
          <table>
          </table>
        </div>
      </section>
    </main>
  </body>
</html>

**Comment by cremzeeee** [comment]
> @cremzeeee first screen shot mentions step 15, the second one shows 16. Isn't the issue in the step 16?

yes in hurry i was not able to give accurate problem details.
IT IS IN STEP 16

THANKS BRO

**Comment by cremzeeee** [comment]
Silly me newbie.

**Comment by ojeytonwilliams** [comment]
Okay, that makes sense, thanks for clarifying.

To fix this, there needs to be one more test that asserts that `class="current"` is set on the third `td` element.

**Comment by cremzeeee** [comment]
sir did u get what i am able to say?
as if not possibel is it allowed to express it on video call?
if okay so? like on ms teams.
