### ISSUE TITLE
Can't copy all code in monaco using a touchscreen

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#50792]
### Describe the Issue

We often ask people to paste their current code into the forum but I'm not sure there is a good way to copy all of your code from the monaco editor using a touch screen device. I have found that you can copy one line of code by holding your finger on the line for just a bit and then when you let up you will get a context sensitive pop-up menu with the Copy option, and selecting that will put only the current line in your clipboard. (This is using Chrome on my older Android phone, your mileage may vary with other devices.) But I'm not finding a way to copy all of the code in the editor at once.

I've been searching the monaco-editor github repo and have found several issues complaining about this, but I have yet to find a solution. The answer seems to be that monaco does not officially support mobile devices (which I'm assuming they mean to include any touch screen interfaces) and thus we are lucky it works as well as it does with touch screens, and anything that doesn't work is probably not going to get fixed.

### Affected Page

Any step

### Steps to Reproduce

While using a touch device (no keyboard or mouse cheating):

1. Go to any step (preferably a later one with lots of code in the editor)
2. Attempt to copy all of the code in the editor at once using whatever methods you can think of

I'm not able to do it and I don't think it is possible, but if you find a way please let me know.

### Expected behavior

It would be nice if we could add some way to copy all of the code in the editor for touch screen users. 

Some ideas:

- Perhaps it might be possible to add a "Copy all" option to the context sensitive pop up menu. Or we could add a "Select all" option, but then they would have to use two steps to copy all of their code. I think a "Copy all" option might be better.
- The context sensitive menu includes the "Command Palette". We could probably add a "Copy all" (or "Select all") option to the palette (we've added other options in the past, such as the hack to work around a bug in JAWS).
- Add a "Copy all" button to the UI. It could float in the top right corner of the editor. Or we could add it somewhere in the lower jaw.
- Add a "Copy all" (or "Select all") option to the command palette and add a button for the command palette.

The first two options are somewhat dependent on how many touch screen devices support the long finger press to bring up the context menu. I think we'd want to do some testing to make sure most of them will work. Adding a button will ensure that all touch screen users are able to use this feature.

### System

- Device: moto G6 phone
- OS: Android 9
- Browser: Chrome
- Version: 114

**Comment by gikf** [comment]
I was able to copy all by using Gboard to select all lines and then copying from editor. 

- Move cursor at the start of code.
- Go to _Text Editing_ in Gboard. It could be hidden behind three dots tab.
- After pressing the select to start selection, down button can be used to select all lines.
- Holding finger on the editor will bring up editor context menu, with copy option. Pressing it will copy the multiline selection.

It's a bit cheating, and definitely inconvenient.

**Comment by naomi-lgbt** [comment]
> Add a "Copy all" button to the UI. It could float in the top right corner of the editor. Or we could add it somewhere in the lower jaw.

I think adding it to the lower jaw makes the most sense.

**Comment by bbsmooth** [comment]
Thanks @gikf, I was thinking that someone would chime in with a method that I didn't think of or know about. So I stand corrected (just a little bit :slightly_smiling_face: ). If we don't want to provide an easier mechanism then we definitely need to document methods that can be used (such as yours) so that campers using a touch screen can figure out how to do it.

**Comment by ojeytonwilliams** [comment]
I'd go with adding it to the commands + context menu. It's easy enough to implement and lets us preserve the fairly limited amount of screen real estate we have.

**Comment by Jordan2018** [comment]
Hello testing Custom link GH: 

https://jordan.kdta.io/pEWio

**Comment by Jordan2018** [comment]
Testing custom link 5:

https://jordan.kdta.io/GnfrV

**Comment by Jordan2018** [comment]
Testing short link 1/8:
https://kdta.io/Yak1G

**Comment by medhatnar** [comment]
still not working
