### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by miyagui** [FreeCodeCamp/freecodecamp#508]
Syntax error, unrecognized expression

**Comment by terakilobyte** [comment]
Challenge completes if you follow the instructions by adding `<input type="text">`. Without a more descriptive error and providing your attempted code we can't troubleshoot your attempted solution.

**Comment by miyagui** [comment]
I have problems with 4 of the challenges so far. Any time I see "Syntax
error, unrecognized expression" I can't finish it.
I know I did it right, I continued and checked how the solution was on the
next challenge and it was correct all 4 times.

Regards,
Jonathan

-Miya
http://miyadojo.com

**Comment by miyagui** [comment]
Sorry wrong file extension.

-Miya
http://miyadojo.com
