### ISSUE TITLE
Improvement in Introducing Inline Styles module

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#50804]
### Describe the Issue

Currently, the instructions in [Introducing Inline Styles](https://www.freecodecamp.org/learn/front-end-development-libraries/react/introducing-inline-styles) module happens to be as follows:

> Add a `style` attribute to the `div` in the code editor to give the text a color of red and font size of `72px`.
> 
> Note that you can optionally set the font size to be a number, omitting the units `px`, or write it as `72px`.

The instructions tell the users that instead of setting the font size property to a number ( i.e. 72 ), they can optionally set the font size property to `72px` but don't inform the user that `72px` needs to be enclosed within quotes i.e. `72px` needs to be a string value. Furthermore, the word **_units_** in the second sentence should be changed to **_unit_** because in this particular case, we are just referring to a single unit i.e. `px`. Considering this, I think the instructions of [Introducing Inline Styles](https://www.freecodecamp.org/learn/front-end-development-libraries/react/introducing-inline-styles) module should be reworded as follows:

> Add a `style` attribute to the `div` in the code editor to give the text a color of red and font size of `72px`.
> 
> Note that you can optionally set the font size to be a number, omitting the unit `px`, or write it as `72px`, where `72px` needs to be enclosed within quotes.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/introducing-inline-styles

### Expected behavior

The instructions in [Introducing Inline Styles](https://www.freecodecamp.org/learn/front-end-development-libraries/react/introducing-inline-styles) module should be as follows:

> Add a `style` attribute to the `div` in the code editor to give the text a color of red and font size of `72px`.
> 
> Note that you can optionally set the font size to be a number, omitting the unit `px`, or write it as `72px`, where `72px` needs to be enclosed within quotes.

### Screenshots

<img width="517" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/36872756/b3aebe47-5e81-49fa-88c9-d4a411a9d601">

### System

- Device: Laptop
- OS: macOS 13.0.1
- Browser: Chrome
- Version: 107.0.5304.110

**Comment by shoaib-31** [comment]
Hello there, I would like to contribute by fixing this issue,I wanted to ask whether I have to be assigned to this issue to contribute of I can start right away?
Also, can you please guide me on where can i find that component to contribute?
Thanks :)

**Comment by arkadx13** [comment]
Oh~ I see. I was so confused why 72px doesn't work. Good thing I found this issue. Thanks for posting

**Comment by naomi-lgbt** [comment]
I'm not sure about this. The instructions explicitly mention that this is a JavaScript Object, which at this point in the curriculum is something that campers should be familiar with.

I would be okay with something like:

> Note that you can optionally set the font size to be the number `72`, omitting the unit `px`, or the string `72px`.

**Comment by lasjorg** [comment]
Or maybe just update the literal value shown. Considering the part "or write it as" it should show the actual value to write.

> Note that you can optionally set the font size to be a number, omitting the units `px`, or write it as `"72px"`
