### ISSUE TITLE
Can't connect via IP

### ISSUE THREAD

**Issue by PKMNinja** [FreeCodeCamp/FreeCodeCamp#5081]
My school blocks FCC and I used to be able to connect via IP using 45.55.96.82 and now it just shows a 404 error. I have pinged it again and the IP address hasn't changed. If this was done on purpose then close the issue and I will find out a way to get there somehow.

**Comment by BerkeleyTrue** [comment]
@PKMNinja We disable direct access through the ip. Otherwise someone could point their domain at it and server FCC as their own.

Why does your school block FCC?

**Comment by PKMNinja** [comment]
They use just a general filter and the filter catches it for it being a forum. They do this with gitter, but at least gitter makes sense.

**Comment by SaintPeter** [comment]
@PKMNinja Do you know what blocking software they're using?  Maybe we can appeal that classification.   Clearly not a forum.

**Comment by PKMNinja** [comment]
@SaintPeter I believe it is http://www.iboss.com/ I can confirm for certain tomorrow at school.

**Comment by PKMNinja** [comment]
@SaintPeter Yes, I just checked and it is iboss network security banned because of forum content.

**Comment by SaintPeter** [comment]
I spent some time looking around the iboss site and there doesn't appear to be any sort of method for reporting an incorrectly calssified website.  Free Code Camp did used to have a forum, so I guess technically it was once a "forum".   

My only suggestion would be to contact your school administration and ask them to whitelist this clearly educational site.

Sorry.

**Comment by PKMNinja** [comment]
@SaintPeter thank you for checking it out. I will send a couple e emails around the IT department. See what I can do. Thank you once again for seeing what you could do.
