### ISSUE TITLE
Go to next challenge is throwing an error for certificate challenge

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#50812]
### Describe the Issue

When completing the RWD portfolio certificate challenge and clicking "Go to next challenge" (or using Ctrl + Enter) an error is thrown in the browser console and it does not advance to the next challenge. I have _not_ tested this as signed-in or with other certificate challenges.

> Uncaught TypeError: Cannot read properties of null (reading 'includes')

Code that throws

https://github.com/freeCodeCamp/freeCodeCamp/blob/prod-current/client/src/templates/Challenges/redux/completion-epic.js#L209
```
const isNextChallengeInSameSuperBlock = nextChallengePath.includes(superBlock);
```

PR that introduced the code
https://github.com/freeCodeCamp/freeCodeCamp/pull/50033

It was changed again here (not in prod)
https://github.com/freeCodeCamp/freeCodeCamp/pull/50011

Didn't look into it more.

### Affected Page

https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

### Your code

```



```

### Expected behavior

To work?

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum thread: https://forum.freecodecamp.org/t/responsive-web-design-projects-build-a-personal-portfolio-webpage-is-complete-but-doesnt-submit/618254

**Comment by ojeytonwilliams** [comment]
Thanks for the analysis, @lasjorg, it saved me time trying to debug this.
