### ISSUE TITLE
CSS for changing color.  

### ISSUE THREAD

**Issue by Signzfun** [FreeCodeCamp/FreeCodeCamp#5082]
Below is the challenge I have been working on for a few days and I can't seem to get the color of the element to change.  Curious to know if I am missing something or if it is truly a glitch?  Any help would be greatly appreciated.

John

Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0Ah2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0ACatPhotoApp%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.1.1; SM-T900 Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
h2 {color: blue;}
</style>
CatPhotoApp
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by codemzy** [comment]
A good place to ask for help with challenges is in the chat...

You don't have a h2 element in your html, you are declaring h2 to be blue in your style, but then you also should have a h2 element in your html.

e.g. 

`<h2>CatPhotoApp</h2>`

With the above code, the CatPhotoApp text would be blue, as it is declared as h2 in your html, and you have asked for all h2 elements to be blue in your css (your style).

**Comment by Signzfun** [comment]
Thank you.  Will give that a try.  Old dog learning new tricks. LOL

**Comment by ltegman** [comment]
Thanks for the help @codemzy. Happy coding!
