### ISSUE TITLE
Add note on React 18 incompatibility to frontend challenges

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#50823]
### Describe the Issue

Seeing how often this issue still comes up we should probably do something about it.

We have talked about this before but it never really got any traction. The question is where should the note be added and what should it say?

We have an open issue we can link to as well if needed.

https://github.com/freeCodeCamp/freeCodeCamp/issues/45922

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/

### Your code

```



```

### Expected behavior

Warn the camper about React 18 and the test issues.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by naomi-lgbt** [comment]
> You mean the layouts?

Yes, exactly. We don't have a system to add a banner to a specific challenge *yet*, so that would need to be implemented.

**Comment by raisedadead** [comment]
But in this specific case we can add it to the whole of front-end libs at least, no?

**Comment by naomi-lgbt** [comment]
Yeah, we could add an alert on the superblock page itself.

**Comment by Riya267** [comment]
is this done??

**Comment by Riya267** [comment]
alright . I have a question though - 
Do you want similar alert message that has been used for all superblocks Intros i.e note for all the superblocks
