### ISSUE TITLE
Waypoint Use Comments to Clarify Code - Test does not catch multiple comments

### ISSUE THREAD

**Issue by smiller171** [FreeCodeCamp/FreeCodeCamp#5083]
http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code

supposed to create a specific comment. does not check proper comment syntax. The following code passes even though the comment syntax is wrong and it is rendering the intended comment as text:
```html
<!-->Only change code above this line.</!-->
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by SaintPeter** [comment]
Confirmed.

Tests should likely be updated to check for one and only one comment opener and comment closer.

Possibly test for the presence of the text between the comment markers.  Don't want too ugly of a Regex, though.

**Comment by ltegman** [comment]
Seems like a fun regex problem. If someone else really wants it they can take it, but if not I'd like to work on this tonight.

**Comment by SaintPeter** [comment]
Haha - you can have dibs.  Hope you have your COM1000 up and running.
