### ISSUE TITLE
Unnecessary horizontal scrollbars in step instructions

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#50845]
### Describe the Issue

Some steps are placing unnecessary horizontal scrollbars on plain text content. The content is being treated as a code example and thus is not line wrapping normally. Also, the content is coded as one continuous line with no newlines, thus causing a very long horizontal scroll and making it more difficult to copy. 

There are exceptions for having horizontal scrollbars in WCAG, but those exceptions are for content "which require two-dimensional layout for usage or meaning" ([SC 1.4.10](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)). Actual code examples can fall under this exception, but I think it would be much harder to argue that pure text content like this "requires" that it not line wrap normally in order to be understood.

There are several instances of this in the CSS Magazine course: Steps 11, 12, 13, 15, 16, 17. These are the ones I know of.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-grid-by-building-a-magazine/step-11

### Your code

N/A

### Expected behavior

Present this non-code content on the page in a way that it is allowed to line wrap normally. I am able to do this by removing `white-space: pre` from the `code` element. I'm noticing we are using `markup` to code this in the challenge files:

```
```markup
Soon the freeCodeCamp curriculum will be 100% project-driven learning...
```

This causes the `code` element to have the class `language-markup`. If we are only using `markup` for these types of non-code examples then perhaps we can use that class to remove the `white-space` property.

### System

N/A

**Comment by Akshaybagai52** [comment]
Hello @raisedadead @bbsmooth can I work on this issue
