### ISSUE TITLE
tab completion on comments is not correct

### ISSUE THREAD

**Issue by smiller171** [FreeCodeCamp/FreeCodeCamp#5084]
If I type `!--<tab>` or `<!--<tab>` I would expect it to complete to `<!--  !-->`. Instead it completes to `<!--></!-->` which is incorrect HTML

**Comment by ltegman** [comment]
The Free Code Camp editor does not have typical "tab completion" it has [emmet](http://emmet.io/) which creates full HTML tags or CSS properties from shorthand. Emmet does not have a shorthand for comments (AFAIK) so it assumes you want a `!--` HTML tag.

Thanks and happy coding!

**Comment by smiller171** [comment]
@ltegman still seems like a bug, but probably one that should be submitted to emmet
