### ISSUE TITLE
Add Vue.js 3 to the /learn "Front End Development Libraries" Section 

### ISSUE THREAD

**Issue by icarusgk** [freeCodeCamp/freeCodeCamp#50843]
### Is your feature request related to a problem? Please describe.

The absence of Vue.js 3 as a learning resource hinders the ability of students to explore other framework options which are more powerful and simpler.

### Describe the solution you'd like

![Frame 71(1)](https://github.com/freeCodeCamp/freeCodeCamp/assets/38413630/cf7d1135-fe25-4063-94c3-be3abfd0e4a8)

I would like to suggest adding Vue.js 3 to the "Front End Development Libraries" section of freeCodeCamp's learning platform 😄

By including Vue.js 3 in the curriculum, students will have access to a widely used and beginner-friendly JavaScript framework, expanding their learning opportunities and giving them an alternative to the solutions already provided. 

This addition would enhance the overall learning experience and provide students with more comprehensive front-end development knowledge, as Vue adheres more closely to web standards being HTML-compatible unlike other frameworks, eliminating the need for a <JSX /> transpilation process.

### Describe alternatives you've considered

While the current freeCodeCamp portfolio currently includes Bootstrap, jQuery, Sass, React, and Redux as front-end development libraries, the absence of Vue.js 3 is noticeable. With the development of a [new portfolio](https://github.com/freeCodeCamp/freeCodeCamp/issues/48244) underway, the inclusion of Vue 3 would be a significant enhancement.

By integrating Vue.js 3 directly into the freeCodeCamp platform, students would benefit from a cohesive and seamless learning experience. They wouldn't have to rely on external tutorials or search for additional resources outside the platform, all the necessary materials would be readily available as they are for the rest of the frameworks and tools already in the portfolio.

### Additional context

Vue.js has earned a strong following and a loyal community owing to its user-friendly nature, adaptable design, and comprehensive documentation. Integrating Vue.js 3 into the freeCodeCamp portfolio provides students with a diverse selection of front-end development libraries to explore. This comprehensive offering empowers students to not only choose the tools that align with their personal preferences but also ensures they acquire the vital skills necessary to thrive in the dynamic and competitive industry of web development.

The addition of Vue.js 3 not only broadens students' horizons but also introduces them to less complex alternatives that can achieve the desired results with ease. For instance, Vue 3's built-in [Fine-grained Reactivity](https://vuejs.org/guide/scaling-up/state-management.html#what-is-state-management) eliminates the need for additional libraries like Redux for React. This streamlined approach empowers students to choose the most suitable tools for different tasks, optimizing their development workflow. 🚀

**Comment by romule** [comment]
**Please**

**Comment by awaisalwaisy** [comment]
Yes Please. Upvoted...

**Comment by JoshuaB94** [comment]
100% support this proposal. React has long been the forefront of Frontend Development courses for many years now but it is time to diverse the course material. Vue.js is becoming more popular in the enterprise sector, that at my current employer it has been the framework of choice for a greenfield project. Also the learning curve is less and a lot more fun in my opinion.

**Comment by Ajuriaa** [comment]
Upvote!

**Comment by DominusKelvin** [comment]
I totally agree and will be more than happy to contribute to the content of this section of FreeCodeCamp

**Comment by DominusKelvin** [comment]
Great job @icarusgk

**Comment by icarusgk** [comment]
as @DominusKelvin I'm also willing to contribute to this course's content and creation as well 🙌🏼 Count me in!

**Comment by DominusKelvin** [comment]
Let's do this

**Comment by Seyid-cmd** [comment]
Yes,Please upvoted

**Comment by IzuchukwuSamson** [comment]
Upvoted

**Comment by asilhome** [comment]
Yes.

**Comment by silvesterwali** [comment]
yes

**Comment by claranceliberi** [comment]
Vue is a mature and widely used framework. It should be there in the list of courses.

**Comment by PaulElisha** [comment]
Yes, please.

**Comment by AdityaTD** [comment]
You have my vote :)

**Comment by Ericwiz** [comment]
Yes, yes please... Vue.js will be a great addition to the freecodecamp library.

**Comment by tajespasarela** [comment]
yes please 🙏🏻

**Comment by mfaizshahid** [comment]
Yes, please add

**Comment by Aurion72** [comment]
Nuxtjs > Nextjs

**Comment by goncanegis** [comment]
Yes please. Vue is certainly underrated and Nuxt 3 has great developer experience as well as performance.

**Comment by Redemption198** [comment]
Yes, also don't forget about Nuxt.

**Comment by mrcego** [comment]
Supporting this proposal. Vue is love 💚

**Comment by kasvith** [comment]
Supporting this

**Comment by joranquinten** [comment]
Yes yes yes

**Comment by feyisayo1** [comment]
Yes!!!!

**Comment by TranceDevCode** [comment]
Please add VueJS and Nuxt, we need that!

**Comment by davidboom95** [comment]
+1

**Comment by petitkriket** [comment]
I find Vue a bit more approchable than React. I hope it can help to lower the access bar a bit and help some people to gain enough trust to go further and eventually land their first job

**Comment by GelipeGC** [comment]
Please add vuejs and nuxt

**Comment by alfredomtzrmz** [comment]
Nuxt +1

**Comment by Xavviieerr** [comment]
Yes! Please

**Comment by axelthereal** [comment]
Less goo 🚀

@DominusKelvin should be guy 🔥

**Comment by Classic-The-Demigod** [comment]
Yes yes yes 🔥🔥😭😭

**Comment by rebornay** [comment]
Yes please add Vue

**Comment by rejkee** [comment]
Much needed!

**Comment by yoan0102** [comment]
Yes please add Vue

**Comment by syhrimr** [comment]
**Upvoted**. Please add Vue 3 and Nuxt

**Comment by ingmanuelcaicedo** [comment]
Of course, it's necessary bringing new resources about Vue 3 and Nuxt 3.
I hope so.

**Comment by lennyAiko** [comment]
Vue is simple, amazing and powerful. Upvote!!

**Comment by AlexSilvaEneque** [comment]
It would be great!

**Comment by Davixe7** [comment]
Upvote!

**Comment by drfcozapata** [comment]
Yes, please. Add Vue.js 3

**Comment by iamsabbirsobhani** [comment]
Please add Vuejs to the freeCodeCamp.

**Comment by QuincyLarson** [comment]
Hey everyone, thanks for sharing your thoughts on this.

We would love to add some interactive Vue.js lessons to the freeCodeCamp curriculum.

We are in the process of overhauling our Front End Libraries certification, and making it fully project-oriented like the Responsive Web Design certification is.

We are also adding a lot of supplemental courses https://www.freecodecamp.org/learn

Our core curriculum can focus on teaching front end development concepts using React, and we can offer a supplemental Vue.js module as well for people who are interested in it.

Would you all be interested in coming up with a list of project ideas, and figuring out which Vue concepts to introduce in which ways? For perspective, here's what our Responsive Web Design curriculum is structured like. You can copy this sheet and use it as a template for developing your own Google sheet that lays out the concepts and projects for Vue, then share it here on this proposal thread: https://docs.google.com/spreadsheets/d/1gI-CUIZ11327LViQuS2t8Awb4xdT5ZEHf_nJ28mSHwo/edit?usp=sharing

**Comment by bassbassbuff** [comment]
We want Vue!

**Comment by icarusgk** [comment]
Thank you @QuincyLarson for your response and for considering the addition of Vue.js to the freeCodeCamp curriculum 💚

I would be more than interested in collaborating with the community to come up with a list of project ideas and determine which Vue concepts to introduce and how to present them effectively in the supplemental Vue 3 module. I appreciate the opportunity to contribute to the development of this space in freeCodeCamp's platform.

With the help of Vue's awesome community, I will create a Google sheet based on the template shared, outlining the concepts and how they can be used in projects. Once we've made considerable progress on it, I will share it on this issue for further discussion and input.

Thank you for considering the community involvement in shaping the Vue 3 module, and we look forward to collaborating with you on this exciting addition to the freeCodeCamp curriculum. 😄

**Comment by Ericwiz** [comment]
Thanks for considering our request @QuincyLarson , we'll do well to curate a list of projects and concepts we would love to be covered in the curriculum.

**Comment by jaserleney** [comment]
Please Vue 3 Setup Ando Nuxt 3

**Comment by ecofriend** [comment]
+1

**Comment by faisalmushtaq007** [comment]
Please full stack project using GoLang as backend and Vue.js as frontend.

**Comment by ilkin0** [comment]
I would love for comprehensive/beginner friendly full Vue 3 course as a Back end developer

**Comment by lsolano2707** [comment]
Pleaseee

**Comment by oceangravity** [comment]
+1

**Comment by RDistinct** [comment]
cant wait 💪
