### ISSUE TITLE
Getting an error message ( in console ) on submitting the correct solution

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#50865]
### Describe the Issue

When the user submits the correct solution for the [Register a Store Listener](https://www.freecodecamp.org/learn/front-end-development-libraries/redux/register-a-store-listener) module, then they end up with the following error message within the console:

> Build error, open your browser console to learn more.

Given that the user is submitting the correct solution ( since all the unit tests are getting passed and `// tests completed` is getting printed in the console ), then showing such an error message ( along with other messages ) to the user could make them feel a bit confused.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/redux/register-a-store-listener

### Your code

```jsx
const ADD = 'ADD';

const reducer = (state = 0, action) => {
  switch(action.type) {
    case ADD:
      return state + 1;
    default:
      return state;
  }
};

const store = Redux.createStore(reducer);

// Global count variable:
let count = 0;

// Change code below this line
function incrementCount(){
  return count++;
}
store.subscribe(incrementCount());
// Change code above this line

store.dispatch({type: ADD});
console.log(count);
store.dispatch({type: ADD});
console.log(count);
store.dispatch({type: ADD});
console.log(count);
```

### Expected behavior

In order to avoid any sort of ambiguity and to keep things as clear as possible, I believe when the user submits their solution and if their submitted solution is entirely correct, then they should be getting the following messages only ( within the console ):

> // running tests
// tests completed

### Screenshots

<img width="1440" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/36872756/f4cb9013-b776-4225-b8ee-92ae842160c7">

### System

- Device: Laptop
- OS: macOS 13.0.1
- Browser: Chrome
- Version: 107.0.5304.110

**Comment by ojeytonwilliams** [comment]
Hi, @AnonSar, thanks for the report. The code you shared does have a small bug - it should be
```
store.subscribe(incrementCount); // not incrementCount()
```
since subscribe expects to be passed a function.

That said, there are a few things going wrong in the client:

- The error should be reported, but it's not appearing in either the fcc or browser consoles
- The 3rd test should fail because it's not receiving a function

**Comment by Shubhdeep02** [comment]
hey!!! @AnonSar   Is the issue still open ????
