### ISSUE TITLE
Polish the completed step styles of the grid map in the courses

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#50874]
the current font weight is too big, and could be improved visually.

<img width="240" alt="thumb-Clipboard - June 22, 2023 13_13" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/899c3a78-04f0-4af9-ab3e-17765a035c27">

Reducing the font weight of non completed to `400`, and the font weight of completed one to `600` or `700` can improve them 
<img width="223" alt="Clipboard - June 22, 2023 14_34" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/d1e73f25-b494-464e-a65a-015830026423">

---

@naomi-lgbt suggested adding border, which I like the idea of.

<img width="240" alt="thumb-Clipboard - June 22, 2023 14_47" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/38bb3403-3a3a-4c12-9965-1a036eb024c0">

Generally, I prefer box shadows over borders, but that is personal preference.

![Clipboard - June 29, 2023 12_49 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/4de8a8a3-b7dc-4958-a270-3187781233b1)

---

@bbsmooth, what do you think about polishing the steps?

**Comment by MadsaraManzar** [comment]
I am just getting started with open source. I would be grateful if anyone could guide and help me contribute.

**Comment by Akshaybagai52** [comment]
Hello @Sboonny can you assign this issue to me I would love to contribute to it

**Comment by Sboonny** [comment]
Thank you, both of you, for the interest in closing the issue, but the issue isn't triaged.

You can find out, how to contribute though [our guideline](https://contribute.freecodecamp.org/).

You can check issues with [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label, they are triaged and open for contribution.

**Comment by moT01** [comment]
There's a PR open that does most of these things. I edited its description so it closes this.

**Comment by naomi-lgbt** [comment]
> Generally, I prefer box shadows over borders, but that is personal preference.

I love me some shadows, but I don't think they'd stand out enough visually.

**Comment by bbsmooth** [comment]
I said most of my peace in the associated PR. As long as we do something other than the background color change then we are technically accessible. But being technically accessible and actually accessible are two different things. I've never really liked relying on the font change, but at least right now it is dramatic enough to notice. If we are going to reduce it then I really think we should add something else, like @naomi-lgbt's borders.
