### ISSUE TITLE
Step Challenges: In Mobile version, Button Size is wrong and 'Go to previous' click not working

### ISSUE THREAD

**Issue by gasperno** [FreeCodeCamp/FreeCodeCamp#5087]
Hi,
When I render the page in mobile version and load [step challenge] (http://www.freecodecamp.com/challenges/waypoint-learn-how-free-code-camp-works), I could see two issues:
1) In step challenges, Go to next button is sized wrong. Only occupying half the space.
2) Go to my previous step button does not perform any action.  
![screenshot 2015-12-08 at 14 35 30](https://cloud.githubusercontent.com/assets/7889179/11666154/fe38225a-9db8-11e5-93b9-bcf279cbcf7d.png)
`UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53`

**Comment by SaintPeter** [comment]
Two obvious issues:
```
.challenge-step-counter.large-p.col-sm-2.col.xs-12.text-center (#{index + 1} / #{description.length})
```
should be `col-xs-12`

```
.btn.btn-primary.col-sm-5.col-xs-6.challenge-step-btn-next(id='#{index}' class=step[3] ? 'disabled' : '') Go to my next step
```
Should be `col-xs-12`

**Comment by gasperno** [comment]
Cool.
I could identify the second one but dint see the first. I will do this.
