### ISSUE TITLE
Test Relies On Variable In User Editable Code

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#50887]
### Describe the Issue

The tests for this problem rely upon a variable in the user editable code. If the users delete this variable, then a correct solution will not pass the tests. We should update the tests to not do this.

### Affected Page

https://www.freecodecamp.org/learn/project-euler/project-euler-problems-1-to-100/problem-18-maximum-path-sum-i

### Your code

```javascript
function maximumPathSumI(triangle) {
  // Copy the triangle
  //   Note: not needed if we are ok with mutating the input
  const triangleCopy = triangle.map(row => [...row]);
  // Find max path
  for (let i = 1; i < triangleCopy.length; i++) {
    triangleCopy[i][0] += triangleCopy[i - 1][0];
    for (let j = 1; j < i; j++) {
      triangleCopy[i][j] += Math.max(triangleCopy[i - 1][j - 1], triangleCopy[i - 1][j]);
    }
    triangleCopy[i][i] += triangleCopy[i - 1][i - 1];
  }
  return Math.max(...triangleCopy[triangleCopy.length - 1]);
}

// NOTE: global variable deleted from seed code here
```

### Expected behavior

Tests should be isolated.

### System

All

**Comment by ShaunSHamilton** [comment]
Agreed. As we have done with other challenges, the test text should include the raw function call value.

TODO:
- Remove `testTriangle` from seed.
- Change test text to explicitly mention the argument passed to the function
- Change the test to locally use its own "`testTriangle`"

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by jeremylt** [comment]
Note: the second version of this problem has the same issue:
https://www.freecodecamp.org/learn/project-euler/project-euler-problems-1-to-100/problem-67-maximum-path-sum-ii
