### ISSUE TITLE
Remove border from solution code

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#50890]
### Describe the Issue

Unnecessary borders are displayed around each line in the solution code of certification projects.

### Affected Page

For example: https://www.freecodecamp.org/certification/sidemt/javascript-algorithms-and-data-structures

### Steps to Reproduce

1. Go to someone's certification page
2. Click on 'View' (> 'View Code') to see the solution code

### Expected behavior

Each line in the solution code should not have borders around it

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25644062/ca25fb88-60ac-4c0d-832e-ff2e334883de)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 114.0.5735.199 (Official Build) (64-bit)

### Additional context

The border seems to be added in #50693

**Comment by nikhilgarg26** [comment]
Hi the borders on the code doesnt seem to be a good UX. I would like to take up this issue.

**Comment by blu3IceCube** [comment]
Hello! I would like to work on this issue. Seems to be a quick fix.

**Comment by ojeytonwilliams** [comment]
Hey. Contributions are very welcome. Please take a look at https://contribute.freecodecamp.org/#/ to get started.

**Comment by blu3IceCube** [comment]
@sidemt Hey! I am working on this issue and have made changes to the css but now I need an account to check if the changes actually worked or not. Could you please provide me the account login details if possible?

**Comment by nikhilgarg26** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/116938919/a02a5e07-10c6-48da-9a72-6f7f1d1a7e69)
Would this sample look better ?

**Comment by blu3IceCube** [comment]
I have fixed the issue and created a pull request #50897 . Please review it and let me know if there are any concerns.

**Comment by Sboonny** [comment]
To solve the issue move the classes added in https://github.com/freeCodeCamp/freeCodeCamp/pull/50693/files, to CSS selector that affects the challenges' layout, or not affect the setting layout.

**Comment by blu3IceCube** [comment]
Simply removing the border property in global.css fixes the issue 

![Screenshot 2023-07-05 194418](https://github.com/freeCodeCamp/freeCodeCamp/assets/111587317/9fe68b01-bdbd-4dda-a59f-99cdcad28cff)

![Screenshot 2023-07-05 194452](https://github.com/freeCodeCamp/freeCodeCamp/assets/111587317/a8b28f28-3e45-46c7-964a-b4c5d333ed43)

Is it fine if done this way? I have reverted the changes I made to the bootstrap file back to its original form.

**Comment by heysolomon** [comment]
Hello  I would like to request to be assigned to fix this
