### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-inform-with-the-paragraph-element has an issue 

### ISSUE THREAD

**Issue by deadwishd** [FreeCodeCamp/freecodecamp#509]
the test is checking for a <p> tag but says it needs a <h2> tag
![challenge 3](https://cloud.githubusercontent.com/assets/5685082/7811515/b90216b6-03ab-11e5-8f82-202488e62760.png)

**Comment by QuincyLarson** [comment]
Thank you for bringing this to our attention. We've now fixed this!
