### ISSUE TITLE
Timeline on profile is using dashed name for new RWD steps

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#50903]
### Describe the Issue

The timeline on the profile page is using the dashed block names for only the new RWD steps/challenges.

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/mot01
2. See dashed block names for new RWD steps/challenges

### Expected behavior

It should display the proper title.

e.g. `Learn CSS Grid by Building a Magazine - Step 80`
instead of 
`learn-css-grid-by-building-a-magazine - Step 80`

### Screenshots

![Screen Shot 2023-07-05 at 11 03 16 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/d0294448-f228-4b38-a0b5-4339a5dce726)

**Comment by Dhruviika** [comment]
I want to work on this issue. Please assign this to me.

**Comment by moT01** [comment]
Feel free to make a PR that fixes it @Dhruviika. You should take a look at our [contributor guidelines](https://contribute.freecodecamp.org/#/) if you haven't already.

**Comment by moT01** [comment]
To fix this, we want to get the block title from the [`intro.json` files. Here's the English one.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json#L114)
To get the title from the intro file, you need to use [something like this.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/codeally/show.tsx#L210)
The [area that needs to be changed is in the `time-line.tsx` file.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/profile/components/time-line.tsx#L275)
In that file, add the `superBlock` to the graphql query and `edges` loop, then use it and the `blockName` to get the titles - something like this: ``t(`intro:${superBlock}.blocks.${blockName}.title`)``

**Comment by Dhruviika** [comment]
I am new to contributing to this project. I have resolved this issue in my local machine but I am facing problem in committing the changes to a PR. The error is related to "lint-staged" command. Will anybody provide me with resource or any kind of explanation as to why this error is occurring?

**Comment by Tudiman555** [comment]
@Dhruviika could you please elaborate the issue, i think you are failing to commit due to pre-commit lint checks.If you are using vscode i suggest you to install eslint plugin for vs code to know more about the issue.

**Comment by ojeytonwilliams** [comment]
Thanks, @Sahilll15, it's great that you're looking to help, but we already have an open PR that fixes this.

If you'd still like to contribute, I recommend taking a look at our [contribution guidelines](https://contribute.freecodecamp.org/#/).
