### ISSUE TITLE
Fix Security Hall of Fame hyperlink

### ISSUE THREAD

**Issue by AnonSar** [freeCodeCamp/freeCodeCamp#50907]
### Describe the Issue

The 3rd point within the [Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/security#guidelines) subsection of [freeCodeCamp's Security Policy](https://github.com/freeCodeCamp/freeCodeCamp/security), contains a hyperlink to the Hall of Fame list which seems to be broken at the moment because when the user clicks on that hyperlink, they end up with a [404 - page not found](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/security-hall-of-fame.md) error.

> 3. While we do not offer any bounties or swags at the moment, we'll be happy to list your name in our [Hall of Fame](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/security-hall-of-fame.md) list, provided the reports are not low-effort.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/security

### Steps to Reproduce

In order to reproduce the error, the user can simply click the **Hall of Fame** hyperlink within the 3rd point of the [Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/security#guidelines) subsection of [freeCodeCamp's Security Policy](https://github.com/freeCodeCamp/freeCodeCamp/security):

> 3. While we do not offer any bounties or swags at the moment, we'll be happy to list your name in our [Hall of Fame](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/security-hall-of-fame.md) list, provided the reports are not low-effort.

### Recommended fix or suggestions

The Hall of Fame hyperlink should be configured to redirect the users to the following link:

> (/docs/security-hall-of-fame.md) i.e. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/security-hall-of-fame.md

**Comment by gikf** [comment]
Link appears to be broken only on one page - https://github.com/freeCodeCamp/freeCodeCamp/security/policy

I'm not sure if after such change link at contribute documentation https://contribute.freecodecamp.org/#/security - which currently works fine.

**Comment by moT01** [comment]
I left a comment on the linked PR with what I think we could do. Basically, change it to a direct link to the page: https://contribute.freecodecamp.org/#/security-hall-of-fame - so both links should work then.

**Comment by naomi-lgbt** [comment]
That wouldn't work, because it would break the i18n links.

**Comment by moT01** [comment]
I agree with Naomi here and I think we should leave this how it is.

**Comment by naomi-lgbt** [comment]
One potential solution would be to create a `SECURITY.md` file in the root directory, have that just contain a link pointing to the contributing website, and set that file as our policy.

I feel like we used to have one but removed it? Can't remember why tho.

**Comment by raisedadead** [comment]
The behavior is intentional. 

The docs are not supposed to be used via GitHub. They have special formatting and markup.

As for the SECURITY.md, we have a security.txt on the site and the GitHub interface also has proper configs:

<img width="1234" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/2ceac9ac-475f-4bbd-b6e0-f5229973304f">
