### ISSUE TITLE
Add an attractive popup in the /learn section to notify about the actions.

### ISSUE THREAD

**Issue by vrsabha-arhata** [freeCodeCamp/freeCodeCamp#50934]
### Is your feature request related to a problem? Please describe.

- I have this problem with the popups and the notification handles that come every now and then, when I as a user perform any actions on the platform.
- The pop-ups can be modified in a way that user do not have to manually close that particular section of web specifically.

### Describe the solution you'd like

- The popups can be replaced using Toastify which will automatically go within the set time period.
- It can be used in different colors and lengthy messages can be written as well.
- The notification will be held for a longer time period once a person is hovering on the notification.

### Describe alternatives you've considered

If I would have to consider alternatives I would go with Toastify, as it is open source and easy to set in the code.

### Additional context

One can also make any kind of changes in the code and make ideal notification.
The notification related can be completion of a problem/exercise, account/profile settings saved, etc.

**Comment by bbsmooth** [comment]
@vrsabha-arhata 

> I have this problem with the popups 

You stated you have a problem with the popup but you didn't tell us what that problem is. Can you be more specific?

**Comment by Smit1610** [comment]
@vrsabha-arhata  Can you please assign to me ?

**Comment by deep-yad** [comment]
can you please assign it to me?

**Comment by Sembauke** [comment]
going to close this as stale.
