### ISSUE TITLE
Celestial bodies database: test passing without required foreign key

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#50935]
### Describe the Issue

The user story says 'Each planet should have a foreign key that references one of the rows in star'. The test passes without the required foreign key.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/build-a-celestial-bodies-database-project/build-a-celestial-bodies-database

### Your code

```



```

### Expected behavior

The test should not pass without a foreign key referencing a row in the star table.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/105294544/5a61d2f1-2e8f-42d4-b074-b620fef534e1)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by moT01** [comment]
Thanks for reporting @Dario-DC 👍 This should be all fixed up. Note that if you have already start the project, the changes will not be applied there.
