### ISSUE TITLE
FCC Menu Bar Drops Down and Block Content

### ISSUE THREAD

**Issue by fire69water** [FreeCodeCamp/FreeCodeCamp#5095]
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![2015-12-09](https://cloud.githubusercontent.com/assets/3821989/11678748/305bce3e-9e7d-11e5-8823-afbaf16bcb58.png)

When I use Chrome or Firefox for my FCC learning sessions, I encounter the above problem of the FCC menu bar dropping a few inches and blocking the content. This happens after the appearance of popup ads, the menu bar.

**Comment by ltegman** [comment]
Are saying that you see ads on Free Code Camp? If so there is a virus or adware either in your browser or on your computer, because Free Code Camp is ad-free.

**Comment by fire69water** [comment]
Oh, I get it. It's Wajam! Damn you, Wajam. (Shake fist at Wajam).
