### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by beme08** [freeCodeCamp/freeCodeCamp#50967]
### Describe the Issue

//TYPO:
//Remove the word "to" from the sentence below. 

<p>... 
They'll also learn how to the tech industry works.
... </p>

//Should be:

<p>
They'll also learn how the tech industry works. 
</p>

### Affected Page

https://www.freecodecamp.org/news/freecodecamp-math-computer-science-degree-update/

### Steps to Reproduce

//TYPO:
//Remove the word "to" from the sentence below. 

### Recommended fix or suggestions

//TYPO:
//Remove the word "to" from the sentence below. 

<p>... 
They'll also learn how to the tech industry works.
... </p>

//Should be:

<p>
They'll also learn how the tech industry works. 
</p>

### Screenshots

![Screenshot_20230713-160936](https://github.com/freeCodeCamp/freeCodeCamp/assets/28564750/2ee9d5b3-62bb-4f40-8969-16c49d7ce5bf)

**Comment by Connor-Skudlarek** [comment]
Taking a look at the page right now, it looks to have been fixed.

https://www.freecodecamp.org/news/freecodecamp-math-computer-science-degree-update/#:~:text=They%27ll%20also%20learn%20how%20the%20tech%20industry%20works.

**Comment by ojeytonwilliams** [comment]
Thanks for the report @beme08 and for checking @Connor-Skudlarek.

I'm closing this as it has been fixed.
