### ISSUE TITLE
Streak still seems to be broken

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5096]
Here's a screen shot. Note that it is showing longest streak as only 3 days: 

![](https://www.evernote.com/l/AqRy7QMDOMpKHr1Kj0-JXE5u9uUaZkG6PO0B/image.png)

Here's the camper's code portfolio: http://www.freecodecamp.com/bipeen

**Comment by LenaBarinova** [comment]
@QuincyLarson I can look into this and fix it. It seems that everything is being recorded correctly to the user profile (in ```mongodb``` there are all the ```processTimestamps``` for my user profile), so the problem most likely is in the Streak calculation on a server side.
I also noticed, that ```day``` and ```days``` in the Streak message are not correct. It shows ```1 days``` in my test profile.
<img width="864" alt="screen shot 2015-12-09 at 3 52 05 pm" src="https://cloud.githubusercontent.com/assets/2317409/11702608/e074165a-9e8c-11e5-8ecc-5819cb0d2880.png">
