### ISSUE TITLE
Dark Mode Functionality Request for FreeCodeCamp Documentation Reading Site

### ISSUE THREAD

**Issue by ketansahugit** [freeCodeCamp/freeCodeCamp#50976]
### Describe the Issue

I would like to request the addition of dark mode functionality to the FreeCodeCamp documentation reading site. As the site primarily serves as a platform for reading and learning, it would greatly benefit users who experience discomfort or eye strain when viewing bright pages for an extended period of time. By implementing a dark mode option, users would have the flexibility to choose their preferred reading experience, enhancing overall usability and accessibility.

### Affected Page

https://contribute.freecodecamp.org/#/

### Steps to Reproduce

1. Open the FreeCodeCamp documentation reading site.
2. Click on "Read our contributing guidelines" button.
3. Navigate to any section or page of the documentation.
Note the absence of dark mode functionality and the resulting bright page appearance.

### Expected behavior

Upon enabling dark mode, the colors, backgrounds, and text elements of the site should be adjusted to create a visually comfortable reading experience for users. Dark mode should provide a high contrast environment that reduces eye strain and improves readability, especially in low-light conditions.

### System

- OS: Windows 10
- Browser: Google Chrome
- Version: 114.0.5735.199 (Official Build) (64-bit)

### Additional context

I believe that implementing dark mode functionality on the FreeCodeCamp documentation reading site would significantly enhance user experience and accessibility. I am interested in contributing to this feature request and would appreciate it if the assigned developers could consider assigning this issue to me. I am excited to collaborate and help improve the FreeCodeCamp platform for the benefit of all users.

**Comment by hamdankalyar** [comment]
assign this task to me. I like to contribute to this issue

**Comment by ambeshchandra** [comment]
Kindly assign task

**Comment by Upendra-Jaiswal** [comment]
kindly assign this task to me

**Comment by Upendra-Jaiswal** [comment]
Hi @ketansahugit  I think it is good idea to get enabled to dark mode according to system/browser settings. it will look unprofessional to give button to enable/disable dark mode on web page. These are my thoughts.  your suggestions are welcome.

**Comment by ketansahugit** [comment]
@Upendra-Jaiswal,  good point. Let's wait for others' opinions on enabling dark mode based on system/browser settings instead of providing a toggle. Gathering feedback will help us make an informed decision. Thanks for bringing it up!

**Comment by premsingh-10** [comment]
kindly assign task to me

**Comment by shaiwart** [comment]
A welcomed change.

**Comment by hadighahroudi** [comment]
@Upendra-Jaiswal it's actually possible using window.matchMedia Api. Although not all browsers support this.

`var darkMode = () => window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches; `

**Comment by naomi-lgbt** [comment]
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions. Please note that this issue has not been triaged yet, so is not ready for pull requests.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by raavan4m3** [comment]
https://github.com/raavan4m3/darkmode.git

**Comment by HARSHITHASALADI1** [comment]
Hello, 
        This is my first open source project. It would be grateful if you assigned this work to me.
