### ISSUE TITLE
docs: Documentation on setting up Cypress out-of-sync/incorrent

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#50991]
It seems the [Cypress section of the fCC docs](https://contribute.freecodecamp.org/#/how-to-add-cypress-tests) are outdated/incorrect. I was trying set it up but all of the commands described in the docs have problems and throws errors.

The `pnpm run cypress:dev:run` command fails a few tests.

The `pnpm run cypress:prd:run` command mentioned in the doc doesn't even exist.

The command to run a specific test described in the doc `pnpm run cypress -- run --spec=cypress/e2e/default/landing.ts` does not work.

**Comment by ShaunSHamilton** [comment]
This is what I see:

```bash
<--- Last few GCs --->

[5598:0x6b32000]   471706 ms: Mark-sweep 4970.2 (5046.9) -> 4965.6 (5047.4) MB, 272.2 / 0.0 ms  (average mu = 0.343, current mu = 0.028) allocation failure; scavenge might not succeed
[5598:0x6b32000]   471979 ms: Mark-sweep 4970.1 (5049.4) -> 4967.6 (5048.9) MB, 269.3 / 0.0 ms  (average mu = 0.210, current mu = 0.014) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7b3f0 node::Abort() [/home/shauh/.nvm/versions/node/v18.14.2/bin/node]
```

But, I cannot then explain why CI is passing, unless this is device specific.

**Comment by ShaunSHamilton** [comment]
> The command to run a specific test described in the doc pnpm run cypress -- run --spec=cypress/e2e/default/landing.ts does not work.

Looks like this is `pnpm` specific, and needs to be `pnpm run cypress run --spec=...`

**Comment by Twaha-Rahman** [comment]
> This is what I see:
> 
> ```shell
> <--- Last few GCs --->
> 
> [5598:0x6b32000]   471706 ms: Mark-sweep 4970.2 (5046.9) -> 4965.6 (5047.4) MB, 272.2 / 0.0 ms  (average mu = 0.343, current mu = 0.028) allocation failure; scavenge might not succeed
> [5598:0x6b32000]   471979 ms: Mark-sweep 4970.1 (5049.4) -> 4967.6 (5048.9) MB, 269.3 / 0.0 ms  (average mu = 0.210, current mu = 0.014) allocation failure; scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
>  1: 0xb7b3f0 node::Abort() [/home/shauh/.nvm/versions/node/v18.14.2/bin/node]
> ```
> 
> But, I cannot then explain why CI is passing, unless this is device specific.

Yeah... I got that too. Btw... I'm on -
 - Ubuntu 23.04
 - Node v18.13.0
 -  pnpm 8.6.7

**Comment by Twaha-Rahman** [comment]
> > The command to run a specific test described in the doc pnpm run cypress -- run --spec=cypress/e2e/default/landing.ts does not work.
> 
> Looks like this is `pnpm` specific, and needs to be `pnpm run cypress run --spec=...`

I looked up the Cypress docs before and they said to use exactly what you did but with `npx` instead of `pnpm`. Is there any reason behind using `pnpm`?

**Comment by ShaunSHamilton** [comment]
> Is there any reason behind using pnpm?

I keep forgetting why we changed, but, if I correctly recall, npm handled our mono-repo in a bad way for different versions of React (node_modules were not set up nicely).
@ojeytonwilliams Could you please confirm/elaborate? _I might actually write the reason down, this time._

**Comment by ojeytonwilliams** [comment]
There were two main motivations for switching to pnpm.

Firstly, it provides better isolation of the workspaces because it does not hoist all of the dependencies into the root. That means each workspace has to declare the dependencies it needs, rather than relying another workspace's dependencies.

Secondly, and less importantly, it's way faster.

Anyways, for the question at hand, it should not make any difference if you use `pnpm cypress`, `pnpm run cypress` or `npx cypress`. They all end up calling the cypress script in node_modules/.bin/cypress.

Honestly I'm not sure why Cypress eats so much memory, but it does. Or, at the very least, running it and `pnpm run develop` at the same time needs a lot of memory (I've not dug into which is the culprit, though I suspect it's our client or Gatsby). I have 16GB of ram and still run into issues occasionally, so the fact you're running into problems with 5 (6?) isn't surprising.

Unfortunately, until we know what the underlying issue is or (if it's the client) migrate to a different framework, there's not a lot you can do. Sorry about that!

**Comment by ShaunSHamilton** [comment]
> so the fact you're running into problems with 5 (6?) isn't surprising.

I have 24

**Comment by ShaunSHamilton** [comment]
The client is dying - Cypress is killing it.

**Comment by Twaha-Rahman** [comment]
> Honestly I'm not sure why Cypress eats so much memory, but it does. Or, at the very least, running it and `pnpm run develop` at the same time needs a lot of memory (I've not dug into which is the culprit, though I suspect it's our client or Gatsby).

@ojeytonwilliams I've observed this previously when I was writing tests with Cypress. There is some sort of memory leak somewhere because I used to use Cypress to watch for changes and reload. I used to have only 8 GB of memory back then and every single time it reloaded, I could clearly see an increase in memory consumption and this memory would not get freed and kept on accumulating. After a few refreshes, I had to `cntr` + `c` and terminate the command and restart it. However, I do have to admit, I am not entirely sure where this memory leak is happening. But this memory leak was there from the very beginning, that's absolutely clear.


> I have 16GB of ram and still run into issues occasionally, so the fact you're running into problems with 5 (6?) isn't surprising.

@ojeytonwilliams Just to clarify, I have 16GB  of RAM and still ran into the same issue. I'll see if I can reproduce it.

**Comment by ojeytonwilliams** [comment]
Thanks, @Twaha-Rahman. It's good to know this has been a problem for a while. So, you saw the leaks whenever Cypress reloaded?

Anyways, it's possible to up the amount of memory a node process uses (Cypress or the client) and I think that will have to be the solution for now.

**Comment by ojeytonwilliams** [comment]
It's really bad, @Twaha-Rahman. I tried upping the memory too and encountered the same problems you did.

The only thing that I could do to get a full run to complete was to build and serve the client first:

```
pnpm run build
pnpm run serve:client
```

You can get away with `pnpm cypress:dev:watch` for a bit if the client is in development mode, but not long :(

I'm not sure what the best advice is, though. If you're just running a few tests _probably_ increase the memory and hope for the best? I'm not sure.

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams  I just tried your commands and all but 9 tests pass. It isn't clear from your reply so I'll need ask this to clarify: Did all the tests pass on your side?

For anybody who's following this issue, here's what I ran (In order) ->


Terminal no. 1:
```sh
pnpm run build
pnpm run serve:client
```

Terminal no. 2:
```sh
cd api-server && pnpm run start
```

Terminal no. 3:
```sh
npx cypress run --browser chrome
```

**Comment by ojeytonwilliams** [comment]
> Did all the tests pass on your side? 

No, there's more that needs to be done before all the tests can pass. We use https://github.com/freeCodeCamp/client-config/blob/master/serve.json to handle some redirects and without that config those tests will fail. That file needs to be in client/public/serve.json and then you can run `pnpm run start-ci` instead of `start`.

If you're curious the full set of working steps can be found in the workflow https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.github/workflows/e2e-web.yml and we know that works because it runs all the time.

**Comment by Twaha-Rahman** [comment]
@ojeytonwilliams You are right. After following your steps, only these two tests fail.

![Screenshot from 2023-07-24 14-55-58](https://github.com/freeCodeCamp/freeCodeCamp/assets/39026437/d22fef0c-05d3-4cbb-bece-3fc8bb0de545)
![Screenshot from 2023-07-24 14-55-35](https://github.com/freeCodeCamp/freeCodeCamp/assets/39026437/4a7e1516-3f04-438c-8ccb-91a8b52afb86)


For anybody who's following this issue, here's what I ran (In order) ->

First, I copied `serve.json` and pasted it in `client/public`. 

(Get the `serve.json` file from [here](https://github.com/freeCodeCamp/client-config))

Terminal no. 1:
```sh
pnpm run build
pnpm run start-ci
```

Terminal no. 2:
```sh
npx cypress run --browser chrome
```

**Comment by ojeytonwilliams** [comment]
Ah, sorry @Twaha-Rahman, I forgot about email.  The workflow sets up mailhog to catch the requests:
 https://github.com/freeCodeCamp/freeCodeCamp/blob/10eb1d9630ec2170e9a2ba5a698581a8845cb498/.github/workflows/e2e-web.yml#L90-L93

We have some docs on that, too: https://contribute.freecodecamp.org/#/how-to-catch-outgoing-emails-locally?id=installing-mailhog

I'm pretty sure that's it, but the tests are flaky and even if everything is set up correctly they can randomly fail.

**Comment by Sembauke** [comment]
We will be moving away from Cypress soon
