### ISSUE TITLE
landing page certification list includes non-certifications

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#51000]
### Describe the Issue

Previously, we have left out the Coding Interview Prep section from the landing page, because it falls under the heading _"Earn free verified certifications in:"_, but we do not have certifications for Coding Interview Prep.

I assume with all the changes to the coding interview prep section, this slipped by. But, I also know we had test/s ensuring this did not happen.

Is this now on purpose, and we should probably change the heading? Or, is this a bug?

### Affected Page

https://freecodecamp.org/

### Steps to Reproduce

1. Go to https://freecodecamp.org
2. Scroll down to the certifications list
3. See Coding Interview Prep and Project Euler superblock

**Comment by ShaunSHamilton** [comment]
Our landing page tests are here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/90efc431495d828324e742e91f4adaeba5f9d4ea/cypress/e2e/default/landing.ts#L68-L76

It is weird because this should fail, as I see 15 certifications - not 11.

**Comment by CallmeHongmaybe** [comment]
Just to clear things here, and making sure that I understand this correctly...are we going to wait until the task in the earlier issue to be done first then we fix the cypress issue later ?

**Comment by raisedadead** [comment]
@moT01 what's the best quick fix here (like your recommended code change)?

**Comment by KSSaiTeja** [comment]
I am interested to work on this issue. could anyone help me to fix the issue.. Please?

**Comment by ngdangtu-vn** [comment]
Well, in term of html structure, I agree that Coding Interview Prep and Project Euler items should not be in the cert section. But from visitors' POV, I don't see any problem. More specifically, visitors will see a whole cert section as syllabe section of the site or at least that what I see.

So do you want to change the meaning of it in HTML struct (class name, and js variables) or you want it to be separated as 2 distinguish sections from visitors' POV?

**Comment by vitkarpov** [comment]
@moT01 I believe this issue should be closed since https://github.com/freeCodeCamp/freeCodeCamp/pull/50435 is merged now. I found this issue by "help wanted" filter, and it's misleading for newcomers looking for a good first issue.
