### ISSUE TITLE
Build a Mario database - Step 340 - Tests don't match instructions given

### ISSUE THREAD

**Issue by joaodavidsilva** [freeCodeCamp/freeCodeCamp#51015]
### Describe the Issue

I deleted the row as the instructions in the exercise implied, but after doing that the test would not pass because I was supposed to have the Luigi row still available. So I created the row again, but in the next exercise, I was supposed to SELECT * FROM second_table to check if Luigi was gone, like it should be.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

```
DELETE FROM second_table WHERE username='Luigi';
```

### Expected behavior

It was expected that after deleting the last added record to the database, with id 3 and username 'Luigi', the tests should pass, as seen by the explanations in the screenshot.

### Screenshots

<img width="879" alt="Screenshot 2023-07-19 at 10 26 01" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/7389336/78783965-ce06-4af5-8b26-95dea3c17e27">

### System

- Device: Macbook Pro M1 Max 32GB 512GB
- OS: OSX Monterey
- Browser: Chrome
- Version: Version 114.0.5735.198 (Official Build) (arm64)

### Additional context

<img width="879" alt="Screenshot 2023-07-19 at 10 36 28" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/7389336/ea8b33ee-b0c0-4a8c-b6d7-05730bed1091">

```[tasklist]
### Luigi bug fixing
- [ ] Prepare local environment
- [ ] Run the exercise locally
- [ ] Test exercises
- [ ] Look at tests
- [ ] Find error
- [ ] Fix error
```

**Comment by gikf** [comment]
If I understood this correctly:
1. `Luigi` row was deleted
2. Step was not passing
3. After adding `Luigi` back, the step passed
4. Next step doesn't pass as `Luigi` is in database.


Could you confirm whether that's the case? Screenshots indicate only that test with deleting row passed at some point.

Unless there was something more happening, the tests for relevant don't explain, why deleting row wouldn't make test pass.  
https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/v1.0.5/.freeCodeCamp/test/340.test.js
https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/v1.0.5/.freeCodeCamp/test/350.test.js

**Comment by joaodavidsilva** [comment]
> If I understood this correctly:
> 
> 1. `Luigi` row was deleted
> 2. Step was not passing
> 3. After adding `Luigi` back, the step passed
> 4. Next step doesn't pass as `Luigi` is in database.
> 
> Could you confirm whether that's the case? Screenshots indicate only that test with deleting row passed at some point.
> 
> Unless there was something more happening, the tests for relevant don't explain, why deleting row wouldn't make test pass. https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/v1.0.5/.freeCodeCamp/test/340.test.js https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/v1.0.5/.freeCodeCamp/test/350.test.js

Yes, that's correct, however I checked the tests and it should work, I'm confused as to why it happened... The error I got, implied that Luigi should exist.

**Comment by joaodavidsilva** [comment]
<img width="879" alt="Screenshot 2023-07-19 at 23 37 09" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/7389336/cb770e1a-ba81-46c9-a7a5-227797c30272">

I continued the exercise, and now, after deleting Luigi, it's asked that I delete Mario, and it says that Luigi should still exist.

**Comment by gikf** [comment]
Looks like test might be stuck at some previous step. Try reseting the step.

**Comment by joaodavidsilva** [comment]
> Looks like test might be stuck at some previous step. Try reseting the step.

It worked, thanks. It was simpler after all.
