### ISSUE TITLE
Users can backspace themselves out of the editable regions

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#51021]
### Describe the Issue

A user can hold down the backspace key on their keyboard and keep going thus proceeding upwards and upwards out of the section of the file meant to be edited. A challenge may have you want to edit lines 36 and 37, but users can backspace themselves all the way back to line 25 at least. 

### Affected Page

https://www.freecodecamp.org/learn

### Steps to Reproduce

1. Go to an challenge like [one of the cat photo challenges](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-36) 
2. Click on the editable region 
3. Hit and hold backspace while in the backspace so that it progresses several lines upwards 

### Expected behavior

If the user hits backspace too far, the user is to be clamped to at minimum where the editable region starts. 

### Screenshots

![Capture](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/b8110552-c6c2-43d8-a593-6cdc45bab6ac)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

It could be a potential source of issues for new developers.

**Comment by bbsmooth** [comment]
I'm not sure I'm understanding the issue here. Backspace deletes things. If the user holds down the backspace key they are going to delete a bunch of stuff. The solution is to reset the step to get it back.

Can you give further information on why this is an issue and possibly a solution?

**Comment by a2937** [comment]
It's currently possible for campers to accidentally copy and paste a bunch of stuff in an effort to restore things before they consider hitting the reset step button. And may potentially responsible for unexplainable issues when campers are trying to validate their code. 

As for a possible solution, I was thinking of defining edit regions. Blocks of code that campers can only edit during the challenge; in this case it would be the circled sections of the capture I provided. It is where the code is when the challenge initially starts after all. Campers should be able to add lines inside the region but not go before it. 

![Capture](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/5adad6f3-6353-448e-9a2c-0156c6c6f09d)

**Comment by bbsmooth** [comment]
> I was thinking of defining edit regions. Blocks of code that campers can only edit during the challenge;

I had a feeling that's what you were thinking of :slightly_smiling_face: I also suggested this a while back but it didn't go anywhere. I believe the intent is to allow people to experiment with the code and thus not limit their ability to edit any part of the file.

**Comment by naomi-lgbt** [comment]
>  I believe the intent is to allow people to experiment with the code and thus not limit their ability to edit any part of the file.

Exactly this. We specifically did not want to restrict where a camper could edit the code.

**Comment by ojeytonwilliams** [comment]
Right. Placing artificial limits on what the camper can do is something we've considered and rejected.

There are two reasons for this

1. It's an intensely frustrating user experience
2. It breaks the illusion that what you're doing is 'real'

Any remotely curious camper is likely to want to tinker with the code just to find out what happens. If we confine them to the editable region, that's no longer possible.

Also real editors don't work like this, so it would take us another step away from a real developer experience.

---

In principle we could track if someone has modified code outside the editable region and warn people if, say, their tests fail. However, are there many cases where people have been stuck with broken code due to this?

**Comment by naomi-lgbt** [comment]
> However, are there many cases where people have been stuck with broken code due to this?

I don't believe so. The few that I've seen on the forum were quickly identified because we added the ERMs to the code in the Get Help forum post.
