### ISSUE TITLE
HTML test passing when it shouldn't. Responsive Web Design Certification.

### ISSUE THREAD

**Issue by Bolonius** [freeCodeCamp/freeCodeCamp#51059]
### Describe the Issue

This happens on step 14 of the _Learn HTML Forms by building a Registration Form challenge_. Instructions ask for four `<label>` html elements to be placed but the code passes without adding any closing tag, or partially adding any below four.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-14

### Your code

```
<form method="post" action='https://register-demo.freecodecamp.org'>
      <fieldset>
        <label>
        <label>
        <label>
        <label>
      </fieldset>
      <fieldset></fieldset>
      <fieldset></fieldset>
    </form>
```

### Expected behavior

The test should fail if any `<label>` tag is not properly closed, since it's not a self closing tag.

### Screenshots

![Screenshot from 2023-07-24 19-48-56](https://github.com/freeCodeCamp/freeCodeCamp/assets/138831516/66de93dd-1f17-4028-8b83-1b081b2ad61a)

### System

- Device: [Laptop]
- OS: [Fedora 38 Workstation]
- Browser: [Brave]
- Version: [1.56.11 Chromium 115]

**Comment by Jordan2018** [comment]
This is testing Github:    https://kdta.io/9TU4P

**Comment by Jordan2018** [comment]
Testing github; https://kdta.io/MmOhm

**Comment by VENOMM9** [comment]
hello , saw this interesting task and decided to pick it up. The reason is because the label tag is an inline element and when it does not have any content within it , it automatically closes itself .

**Comment by Bolonius** [comment]
I was under the assumption the label tag was not a void element, but you are right.

**Comment by jeremylt** [comment]
A `label` element *is not* a void element. What's happening here is that your browser is attempting to repair malformed HTML for you (and getting it right in this case).

**Comment by lasjorg** [comment]
Well, it isn't really getting it right. It is closing the label elements in such a way that they end up nested inside each other which isn't valid HTML.

But it is making the test pass because we are just counting the number of label elements and the browser does do that correctly.

---

The "Tag omission" rule for the `label` element is "Neither tag is omissible"

https://html.spec.whatwg.org/multipage/forms.html#the-label-element

https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission

**Comment by sammyifelse** [comment]
Hii, saw this issue and decided to write about it. As the label tag is an inline element so it passes the test

One more reason can be that the in this label tag we are just counting the number of the label elements so this issues passes away
