### ISSUE TITLE
Repl.it no longer makes it simple to use dotenv files

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#51051]
### Describe the Issue

As I discovered last night's research, dotenv files are no longer directly editable on Repl.it. They actually use a feature called `secrets` now. The instructions need updated to ensure future campers don't have any trouble following the Node and Express lessons 

More about secrets: https://docs.replit.com/programming-ide/workspace-features/secrets

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file

### Your code

```
let express = require(‘express’);
let app = express();
app.get(“/”, (req, res) => res.sendFile(${__dirname}/views/index.html));
app.use(“/public”, express.static(${__dirname}/public))
app.get(“/json”, (req, res) => {
let response = “”;
if (process.env.MESSAGE_STYLE === “uppercase”) {
response = “Hello World”.toUpperCase();
} else {
response = “Hello World”;
}
res.json({
message: response
});
});
```

### Expected behavior

The lesson plan should be clear for campers regarding how to set up dotenv files in the updated Replit website. 

### System

- Device: Desktop Computer
- OS:  Windows 10 
- Browser: FireFox
- Version: 115.0.2

### Additional context

This could negatively impact a lot of the unit test writing curriculum given that `NODE_ENV=test` has to be set in the dotenv files.  Especially considering once campers fork the boilerplate project they won't actually have the value for `NODE_ENV` set.

**Comment by anuragchauhan766** [comment]
The note is already given in the task:

>Note: If you are using Replit, you cannot create a .env file. Instead, use the built-in SECRETS tab to add the variable.
