### ISSUE TITLE
Responsive Web design ( learn CSS color by building a set of colored markers) Step 5

### ISSUE THREAD

**Issue by codenamsensei** [freeCodeCamp/freeCodeCamp#51067]
These are the instructions=> You can have multiple self-closing meta elements on a web page. Each meta element adds information about the page that cannot be expressed by other HTML elements.
Add another self-closing meta element within the head. Give it a name attribute set to viewport and a content attribute set to width=device-width, initial-scale=1.0 so your page looks the same on all devices.

This is what I did 
  <head>
    <meta name="viewport"         content="width=device-width, intial-scale=1.0">
    <meta charset="utf-8">
    <title>Colored Markers</title>
  </head>.  

But I keep getting Error =>Your new meta element should have a name attribute set to viewport, and a content attribute set to width=device-width, initial-scale=1.0.

**Comment by bbsmooth** [comment]
This should be posted to the [forum](https://forum.freecodecamp.org/).

**Comment by codenamsensei** [comment]
Thanks 👍
