### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue 

### ISSUE THREAD

**Issue by miyagui** [FreeCodeCamp/freecodecamp#511]
Syntax error, unrecognized expression

**Comment by QuincyLarson** [comment]
Please send us a screen shot so we can better understand this error. Thanks!

**Comment by QuincyLarson** [comment]
We've fixed this. Thank you for your patience, and for bringing this to our attention!

**Comment by miyagui** [comment]
No need to thank me, thank you for all your work. I'll try to finish the
challenges as fast as I can so I can help you guys too. This course is
great!
Keep it up!

Regards,
Jonathan.

-Miya
http://miyadojo.com
