### ISSUE TITLE
Learn Typography by Building a Nutrition Label - Step #41 Typo in Instructions (English)

### ISSUE THREAD

**Issue by noahbowman** [freeCodeCamp/freeCodeCamp#51116]
### Describe the Issue

There appears to be a slight typo in the English instructions on Step 41 of "Learn Typography by Building a Nutrition Label". The instructions are displayed on the `styles.css` file and read as:

> **Step 41**
> The text `* Daily Value %` should be aligned to the right. Create a `.right` selector and use the `justify-content` property to do it.

The typo is with the text: `* Daily Value %`. The `%` and `*` characters are flipped in the instructions when compared to how it actually is in the `index.html`'s paragraph element `<p class="bold right">% Daily Value *</p>` for step 41. This paragraph element is added in step 40 with the correct and expected text `% Daily Value *` as part of the exercise.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-41

### Your code

The following code is what the challenge starts with

**index.html**
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Nutrition Label</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
  <link href="./styles.css" rel="stylesheet">
</head>

<body>
  <div class="label">
    <header>
      <h1 class="bold">Nutrition Facts</h1>
      <div class="divider"></div>
      <p>8 servings per container</p>
      <p class="bold">Serving size <span>2/3 cup (55g)</span></p>
    </header>
    <div class="divider large"></div>
    <div class="calories-info">
      <div class="left-container">
        <h2 class="bold small-text">Amount per serving</h2>
        <p>Calories</p>
      </div>
      <span>230</span>
    </div>
    <div class="divider medium"></div>
    <div class="daily-value small-text">
      <p class="bold right">% Daily Value *</p> <!-- The correct text added during step 40 is here -->
    </div>
  </div>
</body>
</html>
```
**styles.css** - where the instructions are displayed
```
* {
  box-sizing: border-box;
}

html {
  font-size: 16px;
}

body {
  font-family: 'Open Sans', sans-serif;
}

.label {
  border: 2px solid black;
  width: 270px;
  margin: 20px auto;
  padding: 0 7px;
}

header h1 {
  text-align: center;
  margin: -4px 0;
  letter-spacing: 0.15px
}

p {
  margin: 0;
  display: flex;
  justify-content: space-between;
}

.divider {
  border-bottom: 1px solid #888989;
  margin: 2px 0;
}

.bold {
  font-weight: 800;
}

.large {
  height: 10px;
}

.large, .medium {
  background-color: black;
  border: 0;
}

.medium {
  height: 5px;
}

.small-text {
  font-size: 0.85rem;
}

.calories-info {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
}

.calories-info h2 {
  margin: 0;
}

.left-container p {
  margin: -5px -2px;
  font-size: 2em;
  font-weight: 700;
}

.calories-info span {
  margin: -7px -2px;
  font-size: 2.4em;
  font-weight: 700;
}
```

### Expected behavior

The expected instructions would read with  `% Daily Value *` instead of  `* Daily Value %`:

> **Step 41**
> The text `% Daily Value *` should be aligned to the right. Create a `.right` selector and use the `justify-content` property to do it.

This would match the actual text value for the paragraph element the instructions are referencing.
`<p class="bold right">% Daily Value *</p>`

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/34799961/2c0ab070-78d0-4ee3-9527-0e54ea3a16a6)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/34799961/d23549f0-8838-4fab-a462-cad54a9e1f4d)

### System

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: Version 115.0.5790.110 (Official Build) (64-bit)

### Additional context

I would like to point out that I have only seen this issue with English and I am not sure if other languages are also impacted.

**Comment by gikf** [comment]
Thanks for opening this issue.

This looks something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/635bde33c91c80540eae239b.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
