### ISSUE TITLE
Add test for i18n CTAs

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#51117]
In relation to #51115, we should add tests that check:

- The "Help us translate" badge does not appear on any English blocks
- The "Help us translate" badge does not appear on any i18n blocks when the superblock is audited
- The "Help us translate" badge does appear on i18n blocks when the superblock is not audited

**Comment by Riya267** [comment]
There was some branching issue so this pull request is closed by bot so I will raise another one with the discussed changes

**Comment by Riya267** [comment]
yes sure

**Comment by Riya267** [comment]
I have reopened the pull request https://github.com/freeCodeCamp/freeCodeCamp/pull/51164 and I have updated the test cases based on our earlier discussion kindly review the pull request.

Thanks
