### ISSUE TITLE
SOLID Article missing images (found!)

### ISSUE THREAD

**Issue by tvance-vant4ge** [freeCodeCamp/freeCodeCamp#51126]
### Describe the Issue

This fine article sadly is missing a couple key images.  Apparently the authors blog (which hosted the images) is no longer a valid domain.
https://www.freecodecamp.org/news/solid-principles-explained-in-plain-english/

I was able to find the images on the wayback machine and will attach them here. 

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/73345229/b7490eb9-eb7f-486e-9c83-d546d8a3c130)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/73345229/13a7d60c-e201-4917-8d8c-47610c3ade27)

### Affected Page

https://www.freecodecamp.org/news/solid-principles-explained-in-plain-english/

### Steps to Reproduce

go to the linked article above and find the broken links under the Open-Closed Principle and the Interface Segregation Principle.

### Recommended fix or suggestions

host the images I provided somewhere and change the href in the article.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/73345229/eba757f9-caec-4fa5-bd07-d52dc371a79a)

**Comment by naomi-lgbt** [comment]
Thanks for reporting this. I'll pass it along to our editorial team.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for bringing this to our attention, @tvance-vant4ge, and for finding those images with the Wayback Machine.

It looks like the images have both been fixed.

Please let us know if you notice issues in any other articles.
