### ISSUE TITLE
Bonfire: Smallest Common Multiple

### ISSUE THREAD

**Issue by jnmorse** [FreeCodeCamp/FreeCodeCamp#5112]
Challenge [Bonfire: Smallest Common Multiple](http://www.freecodecamp.com/challenges/bonfire-smallest-common-multiple#?solution=function%20smallestCommons(arr)%20%7B%0A%20%20%20%20var%20found%20%3D%20false%2C%0A%20%20%20%20%20%20%20%20current%20%3D%201%2C%0A%20%20%20%20%20%20%20%20min%20%3D%20arr.reduce(function%20(a%2C%20b)%20%7B%20return%20Math.min(a%2C%20b)%3B%20%7D)%2C%0A%20%20%20%20%20%20%20%20max%20%3D%20arr.reduce(function%20(a%2C%20b)%20%7B%20return%20Math.max(a%2C%20b)%3B%20%7D)%2C%0A%20%20%20%20%20%20%20%20checkArr%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20%20%20function%20mod%20(num)%20%7B%0A%20%20%20%20%20%20%20%20return%20current%20%25%20num%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20function%20check%20(a%2C%20b)%20%7B%0A%20%20%20%20%20%20%20%20return%20(a%20%3D%3D%3D%200%20%7C%7C%20a%20%3D%3D%3D%20true%20%26%26%20b%20%3D%3D%3D%200)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20for%20(var%20i%20%3D%20min%3B%20i%20%3C%3D%20max%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20checkArr.push(i)%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20console.log(min%2C%20max%2C%20checkArr)%3B%0A%0A%20%20%20%20while%20(found%20%3D%3D%3D%20false)%20%7B%0A%20%20%20%20%20%20%20%20found%20%3D%20checkArr.map(mod).reduce(check)%3B%0A%0A%20%20%20%20%20%20%20%20current%20%2B%3D%20(found)%20%3F%200%20%3A%201%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20console.log(current)%3B%0A%20%20%0A%20%20%20%20return%20current%3B%0A%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I've inputed the below code after coping it from a text file on my computer that I used to test it before submiting it.  Once  I click run test, all test pass aside from the last one. "smallestCommons([1, 13]) should return 360360."

My code:
```javascript
function smallestCommons(arr) {
    var found = false,
        current = 1,
        min = arr.reduce(function (a, b) { return Math.min(a, b); }),
        max = arr.reduce(function (a, b) { return Math.max(a, b); }),
        checkArr = [];
  
    function mod (num) {
        return current % num;
    }

    function check (a, b) {
        return (a === 0 || a === true && b === 0);
    }

    for (var i = min; i <= max; i++) {
        checkArr.push(i);
    }
  
  console.log(min, max, checkArr);

    while (found === false) {
        found = checkArr.map(mod).reduce(check);

        current += (found) ? 0 : 1;
    }
  
  console.log(current);
  
    return current;
}
```
If I run this on my own via the comman line with node or open a new window and open a page loading the script in I get the currect results but in chrome or firefox if I check the console from the page on your site I get completely different results.

Firfox shows 218914, Chrome Shows 318908, Node returns 360360 and loading it via a html document in firefox also returns 360360 which is the number it wants.

[Chrome Console](https://drive.google.com/file/d/0BxyToqXKviaySjI1Um5qSERVUms/view?usp=sharing)

[Firefox Console](https://drive.google.com/file/d/0BxyToqXKviayVE9HUnZHWEdmRU0/view?usp=sharing)

[terminal](https://drive.google.com/file/d/0BxyToqXKviayLUxYLVo0WURhZ2s/view?usp=sharing)

**Comment by ltegman** [comment]
This is due to an infinite loop detector we have that is triggering a false positive because due to the nature of this problem and the test case the code has a long runtime. If you add the line `//noprotect` to the top of your script it will disable the loop detection and your code should pass.

I'm leaving this open because I feel like this will not be an uncommon occurrence for people on this particular bonfire. @SaintPeter and @BerkeleyTrue how do you feel about adding a note about our loop detection to this and any other challenges likely to run long enough to trigger false positives?

**Comment by geoff616** [comment]
+1 with: https://gist.github.com/geoff616/52acc21fe0634a550514 which returns correct answer in latest FF and Chrome

**Comment by geoff616** [comment]
Thanks @Itegman, adding `//noprotect` made it pass!

**Comment by SaintPeter** [comment]
@ltegman This was actually one of two that I thought were most likely to have an issue.  In fact, with the original timeout, it failed with my current solution.  This is affected by computer and browser speed.

@BerkeleyTrue We might double it to 1000.  I figure we keep increasing it until we stop getting issues.  :wink:

**Comment by BerkeleyTrue** [comment]
@SaintPeter I think you may be right.

**Comment by SaintPeter** [comment]
Issue Confirmed.  Change to loop detect timeout pending.

**Comment by venkatraj** [comment]
//noprotect passed.
 But even using while(i<(Number.MAX_VALUE)) makes it infinite loop?

**Comment by cyber2024** [comment]
This is still an issue... //noprotect worked but users should be warned in the lesson.
