### ISSUE TITLE
Add MS Trophy validation

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#51135]
Add validation for MS trophy challenges that was added in https://github.com/freeCodeCamp/freeCodeCamp/pull/51016

**Comment by moT01** [comment]
I believe this can be closed. The changes in the linked PR were removed here: https://github.com/freeCodeCamp/freeCodeCamp/pull/51372. I looked over the endpoint in the new and old API and the new API looks up to date.

**Comment by ojeytonwilliams** [comment]
Thanks, Tom. I've double checked and the apis appear to be in sync.
