### ISSUE TITLE
GET /exam/:id

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#51133]

**Comment by moT01** [comment]
Added to current API with https://github.com/freeCodeCamp/freeCodeCamp/pull/51062 - will need to add all the associated functions that the endpoint needs.

**Comment by sanket-1305** [comment]
I want to work on this issue, please Elaborate the issue, and as I am a beginner will need your support

**Comment by Sheersendu** [comment]
Hey, @moT01 I would like to work on the following issue. I have experience working with APIs.
