### ISSUE TITLE
Google Ads Overlap Content on News Post

### ISSUE THREAD

**Issue by DylanDevelops** [freeCodeCamp/freeCodeCamp#51138]
### Describe the Issue

I was reading the freeCodeCamp article linked below, and the ads on the page overlapped the content I was trying to look at.

### Affected Page

https://www.freecodecamp.org/news/use-svg-images-in-css-html/#:~:text=SVG%20images%20can%20be%20written,element%20in%20your%20HTML%20document.&text=body%3E-,If%20you%20did%20everything%20correctly%2C%20your%20webpage%20should,exactly%20like%20the%20demo%20below.

### Steps to Reproduce

1. Go to the page
2. Scroll down a little
3. See the overlap

### Expected behavior

It should not be overlapping.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/48571264/3e587447-e49a-4c7f-88bd-118410d382b0)

### System

- Device: Windows PC
- OS: Windows 11
- Browser: Chrome

**Comment by Tusharjagi** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/12596457/9793ea02-f24a-4dda-b432-1dabceb842c7)
we have lots of space on the right side, we can move this ads container to the right side.
If you have any other suggestions please let me know or if you agree to this implementation then I will raise an MR

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo please check.

**Comment by DylanDevelops** [comment]
I can work on a fix if you point me in the right direction for where to edit the main news posts formatting.

**Comment by raisedadead** [comment]
Thanks @DylanDevelops - the changes will have to be made on the freeCodeCamp/news repo, but we are limiting PRs on that repo due to technical limitations with deployments and the CI.

Kris should be the best person to investigate and fix this.

Of course, you are welcome to work on it locally and suggest recommendations if you have any. Reach out to us in the chat if you have more questions.

Thanks.

**Comment by DylanDevelops** [comment]
It's totally fine! I'll let you guys handle it and the original PR author who started it.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this, @DylanDevelops. I went in and fixed the embeds for this article manually. Those fixes are live now, and the ads no longer overlap the CodeSandbox embeds.

I'll go ahead and close this now. I'll also look into ways we can update our styling to limit the width for these types of embeds from CodeSandbox and Codepen across all of our articles.

**Comment by DylanDevelops** [comment]
Thanks for fixing this! Cheers!
