### ISSUE TITLE
POST  /exam-challenge-completed

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#51134]
Added with https://github.com/freeCodeCamp/freeCodeCamp/pull/51062 - will need to add all the associated functions that the endpoint needs.

**Comment by sanket-1305** [comment]
I want to work on this issue can you please Elaborate!

**Comment by Sheersendu** [comment]
Hi @moT01 I would like to work on this issue and I have experience working with APIs.

**Comment by moT01** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/51295
