### ISSUE TITLE
success pop up not centered

### ISSUE THREAD

**Issue by Dhananjaymahajan2001** [freeCodeCamp/freeCodeCamp#51151]
### Describe the Issue

The success you have logged in is not centered properly. It looks odd and can be corrected.

### Affected Page

https://www.freecodecamp.org/learn/?messages=success%5B0%5D%3Dflash.signin-success

### Steps to Reproduce

1. Go to 'sign in'
2. Click on 'login and lgoin to your account'
3. The green pop up of success you have logged in is not showing properly

### Expected behavior

the success you have logged in should be centered and the x sign at the right edge.

### Screenshots

# Wrong
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/78074728/82ebeb52-c006-4c60-812a-e7d22af9f7a4)
# Corrected
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/78074728/7578024e-3f0e-4889-9123-e1c8ec7285b6)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Edge
- Version: 115.0.1901.188

### Additional context

I know how to solve the problem so should I do it or let someone else do it.

**Comment by ShaunSHamilton** [comment]
@ahmaxed Do you think the text should be centered? As is? Or, justified with the main content?

<img width="651" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/bdbed152-24cb-4554-9375-e332d6f86862">

**Comment by Shubhdeep02** [comment]
hey @Dhananjaymahajan2001!!! Is the issue still open??

**Comment by ahmaxed** [comment]
The text is left adjusted, but it could be adjusted to use the grid systems's margins and padding.
Since the Alert component is already created in the ui-component library, I would defer this change until the Alert component is consumed in the client directory.
