### ISSUE TITLE
[BUG] Not submitting correct answer . 

### ISSUE THREAD

**Issue by KISHANsingh0001** [freeCodeCamp/freeCodeCamp#51171]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
[bug] If I go to the [README.md] and then go to the Table of Contents then click the certifications section then I click the 
 Learn html by building a cat photo App section which is under of  Responsive Web Design certification. then l start the project .
then in step 1 section we have to put text [CatPhotoApp] in the h1 tag . when I put the text [CatPhotoApp] in the h1 tag and submit the code so my answer is not submitting and show this[Sorry, your code does not pass. Keep trying.] of message.

![Screenshot 2023-08-06 154410](https://github.com/freeCodeCamp/freeCodeCamp/assets/126978912/1c8417ec-89fc-4397-88ad-0aacc270366f)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by meaayush** [comment]
Hi @KISHANsingh0001 ,
As mentioned in error message of your screenshot, you're probably using some extension that is causing this issue. I have tried submitting myself and faced no issue. Trying disabling all your extensions and resubmit the challenge again.
For your reference, I have attached a screenshot of my successful submission below. :)

![freecodecamp_reply](https://github.com/freeCodeCamp/freeCodeCamp/assets/83123197/cef4ab83-9272-4baa-9e44-83aaf8a88999)

**Comment by KISHANsingh0001** [comment]
Ok Ok  Thankyou

**Comment by KISHANsingh0001** [comment]
Thanks

**Comment by GUdokermensz** [comment]
> Hi @KISHANsingh0001 ,
> As mentioned in error message of your screenshot, you're probably using some extension that is causing this issue. I have tried submitting myself and faced no issue. Trying disabling all your extensions and resubmit the challenge again.
> For your reference, I have attached a screenshot of my successful submission below. :)
> 
> ![freecodecamp_reply](https://github.com/freeCodeCamp/freeCodeCamp/assets/83123197/cef4ab83-9272-4baa-9e44-83aaf8a88999)
> 


```

```

```

```
