### ISSUE TITLE
Unable to advance past this point in either Chrome or Firefox

### ISSUE THREAD

**Issue by Bennettd77** [FreeCodeCamp/FreeCodeCamp#5118]
Challenge [Waypoint: Learn how Script Tags and Document Ready Work](http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work#?solution=fccss%24(document).ready(function()%20%7B%20%7D)%3Bfcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>$(document).ready(function() { });</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by ltegman** [comment]
I am not able to repro this. The tests pass for me in Chrome and Firefox.

Could you give us more details on what the problem is? Do some of the tests not pass? Do they pass but it doesn't give you the option to submit and move on? When it doesn't work do you get any errors in the console?

**Comment by Bennettd77** [comment]
All tests pass and upon submit it hangs up on the "congrats" pop up. It simply sits there and spins but never goes to the next challenge. After a few minutes it times out.

![fcc](https://cloud.githubusercontent.com/assets/7851939/11698308/8fbe4cf2-9e83-11e5-8d99-112a8fa057ea.JPG)

**Comment by ltegman** [comment]
@Bennettd77 Hmm. Are you behind any VPNs or Firewalls or do you have any browser extensions that might block connections like ad-block?

**Comment by Bennettd77** [comment]
Well. I am at Texas Tech University on my work computer that is on the TTU Network but I have done all 108 of my finished challenges at the same machine. I think I am going to turn my machine off and then back on. I mean . . . ya never know.

**Comment by Bennettd77** [comment]
Well . . . poop. Reboot no worky. What's worse is that submitting the tested challenge on my iPhone 6+ does the exact same thing and my iPhone is connected to FCC via AT&T and not my campus' WiFi so I am not even on the TTU network.

**Comment by ltegman** [comment]
And you're not seeing any errors in the console when this happens?

**Comment by Bennettd77** [comment]
No sir. No errors are present. All three tests are check-marked green and the congrats pop-up presents itself as always, it just never goes away after I submit. This just started happening too. I have been on this site every day all this week and part of last week. I love this place.

**Comment by ltegman** [comment]
@BerkeleyTrue, any ideas on this? I'm at a loss.

**Comment by Bennettd77** [comment]
Wait, there are console errors:

(program):7 Uncaught SyntaxError: Unexpected token <
(program):7 Uncaught SyntaxError: Unexpected token <
http://www.freecodecamp.com/completed-bonfire/ Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by BerkeleyTrue** [comment]
@Bennettd77 Sounds like you are having a connection issue

**Comment by ltegman** [comment]
Yeah, that's exactly what this appears to be, given that console error. Apologies, but if that's the case there's not really anything we can do on our end :/

Thanks and happy coding!

**Comment by bharadwajpenydala** [comment]
Even I am facing the same issue.

**Comment by bharadwajpenydala** [comment]
Is there any alternative for this?

**Comment by avnvgrv** [comment]
need solution for this issue? facing the issue on these browsers:
chrome  47.0.2526.106 m
mozilla firefox  38.0.5
internet explorer 11

**Comment by Anshumakkar** [comment]
Please look into this issue, I am also having same issue, even after pop up it keep rotating and it does not advance to next challenge.Is there any solution I am using Chrome 
 47.0.2526.106 m

**Comment by stopandcatchfire** [comment]
Also having this issue in Chrome 47.0.2526.106 m.  Haven't had any issues thus far with the other 123 waypoints.

**Comment by stopandcatchfire** [comment]
Ok tried messing around, and if I am not logged in it will let me advance.  Logged in gets me stuck.  Ring any bells?

**Comment by stopandcatchfire** [comment]
Ok I've managed to resolve this myself by moving the jQuery code below the last /div.  Works in chrome and firefox.

**Comment by Combinations** [comment]
I had the same issue on campus WiFi. what stopandcatchfire suggested worked for me. odd.
