### ISSUE TITLE
Project Euler Problem 6: Sum square difference

### ISSUE THREAD

**Issue by nibble0101** [freeCodeCamp/freeCodeCamp#51192]
### Describe the Issue

The current instruction says:
> Find the difference between the sum of the squares of the first n natural numbers and the square of the sum.

The above statement  would be interpreted as:
>   sum of the squares - square of the sum

```math
(1^2 + 2^2 + ... + n^2) - (1 + 2 + ... + n)^2
```

However, the tests expect 
> square of the sum - sum of the squares 

```math
(1 + 2 + ... + n)^2 - (1^2 + 2^2 + ... + n^2) 
```

Even the example in the description talks about:
> difference between the sum of the squares of the first ten natural numbers and the square of the sum

But goes ahead to calculate:
> square of the sum - sum of the squares

```math
1^2 + 2^2 + ... + 10^2 = 385
```
```math
(1 + 2 + ... + 10)^2 = 552 = 3025
```
```math
3025 − 385 = 2640
```

### Affected Page

https://www.freecodecamp.org/learn/project-euler/project-euler-problems-1-to-100/problem-6-sum-square-difference

### Your code

```



```

### Expected behavior

The instruction amended to match what the tests expect.

### System

Chrome

**Comment by gikf** [comment]
You are right that _sum of the squares_ - _square of sum_ is not the same as _square of sum_ - sum of the squares_.

What I'm not sure, is whether perhaps the math language used in the challenge is implying to find sort of _distance_ between the two. For which, at worst using the absolute value would might be needed.

**Comment by jeremylt** [comment]
This is the wording Project Euler itself uses

> The sum of the squares of the first ten natural numbers is,

> 1^2 + 2^2 + ... + 10^2 = 385.

> The square of the sum of the first ten natural numbers is,

> 1^2 + 2^2 + ... + 10^2 = 385.

> Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 - 385 = 2640.

> Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

We probably should not deviate too much from that.

**Comment by jeremylt** [comment]
This issue is not ready for contributing. We don't know yet if we will deviate from the wording given by Project Euler or if so how we will deviate from the wording given by Project Euler.

**Comment by AbhinavHaridas** [comment]
Aight

**Comment by naomi-lgbt** [comment]
Going to go ahead and close this, as we generally don't want to deviate from the original challenge text.
