### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by techsarry** [freeCodeCamp/freeCodeCamp#51200]
### Describe the Issue

It is not really an issue but how can one run the GitHub code to see the output without using the app because since began using this on website I have been in the dark😩

### Affected Page

@freecpdemm

### Your code

```

It is not really an issue but how can one run the GitHub code to see the output without using the app because since began using this on website I have been in the dark😩

Run console

```

### Expected behavior

There should be a console result 

### Screenshots

![64E5DC86-0A02-4C19-8EAA-068FD6302860](https://github.com/freeCodeCamp/freeCodeCamp/assets/140967699/04b17438-eaab-46d5-ae7b-05a012a72e9b)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

because since began using this on website I have been in the dark😩

**Comment by gikf** [comment]
Hey @techsarry

I'm not entirely sure what exactly is a problem. From what I understand you have a question regarding using code from this repository. Such question is more suited for a post on forums - https://forum.freecodecamp.org/. You can also take a look at the contributing documentation, https://contribute.freecodecamp.org/#/index.

Thank you and happy coding.
