### ISSUE TITLE
Learn CSS Animation by Building a Ferris Wheel Step 23 Failing Test in Safari

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#51225]
### Describe the Issue

We got a report that the current test for Step 23 of the Learn CSS Animation by Building a Ferris Wheel project fails in the latest version of Safari. The test works as expected in Firefox and Chrome.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-animation-by-building-a-ferris-wheel/step-23

### Your code

```css
animation: cabins 10s linear infinite;
```

### Expected behavior

This test should pass with the above code like it does in Firefox and Chrome.

### System

- Device: Macbook Air
- OS: macOS
- Browser: Safari
- Version: 16.5.2

### Additional context

In [the file for step 23](https://github.com/freeCodeCamp/freeCodeCamp/blob/b9832f4029b5f370171f8d33529df237a65261b2/curriculum/challenges/english/14-responsive-web-design-22/learn-css-animation-by-building-a-ferris-wheel/614100d7d335bb2a5ff74f1f.md?plain=1#L19) of this project, the CSS helper (`new __helpers.CSSHelp(document).getStyle('.cabin')?.animation`) returns the string `10s linear 0s infinite normal none running cabins` when the correct code is submitted in both Chrome and Firefox.

In the latest version of Safari, the CSS helper returns `10s linear infinite cabins`.

The test in the [English version of the step](https://github.com/freeCodeCamp/freeCodeCamp/blob/b9832f4029b5f370171f8d33529df237a65261b2/curriculum/challenges/english/14-responsive-web-design-22/learn-css-animation-by-building-a-ferris-wheel/614100d7d335bb2a5ff74f1f.md) should be updated to check for both strings so learners using all supported browsers can complete this step.

If this is an issue for other people running Safari, this would be a good candidate for someone's first PR.

**Comment by lasjorg** [comment]
Another arguably more verbose option is to look at each individual property. I suspect they will never change values or be different between browsers so that might be more future-proof than looking at the shorthand value.

```
animationName
animationDuration
animationTimingFunction
animationIterationCount
```

**Comment by scissorsneedfoodtoo** [comment]
Thanks for sharing that, @lasjorg. I agree – it would be much more future-proof to test those properties / values individually.

I'm not sure what our CSS Helper library returns for each individual property in the browsers we support. But if they're consistent across Chrome, Firefox, and Safari, testing each one would be a much better approach.
