### ISSUE TITLE
Bug!! progress is not saving after successfully completing the project challenge.. help!!

### ISSUE THREAD

**Issue by divyansshu** [freeCodeCamp/freeCodeCamp#51242]
### Describe the Issue

 In Back End Development and APIs project challenge. When I successfully complete a project and submit it, no response appears...and the page does not redirect to the next challenge..

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/

### Steps to Reproduce

i don't know about this step...

### Expected behavior

In the previous challenges, I was successful in completing them and submitting them. I was receiving a response indicating the progress of my challenge completion. I was then redirected to the next challenge ...
But now the response is no longer showing nor am I being redirected to the next challenge even though I have passed all the test cases.

### Screenshots

![Screenshot 2023-08-12 133318](https://github.com/freeCodeCamp/freeCodeCamp/assets/120498621/511f313e-4702-4642-b3b7-8f52b9288630)

as you can see all the test cases have passed ....but no response...

### System

- Device: [windows, Laptop]
- OS: [ Windows 11]
- Browser: [ Chrome]
- Browser Version: [15.0.5790.171]

**Comment by gikf** [comment]
Link to the project from image: https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/request-header-parser-microservice

Does this happen for you only on this project?

**Comment by divyansshu** [comment]
no, not only for this ..This is happening for all the projects challenge
after "Timestamp Microservice"...  [image: Screenshot 2023-08-12 174932.png]

**Comment by lasjorg** [comment]
Do you get the modal if you are not signed in and submit it?

Your project is online correct? You can pass all the tests and still get the "Remember to submit a publicly visible app URL." message that is telling you it must be online (like on Replit or Glitch).

**Comment by divyansshu** [comment]
ohh yeah!!... Now I see it...I was using localhost://3000. That's why it
didn't work, but after using Replit's public URL it worked.
Thank you very much...

**Comment by divyansshu** [comment]
The problem is now clear to me. I'm closing this issue because it's resolved..if anyone has the same problem..don't use a local URL from your machine..
You can either deploy it and then submit it, or you can use replit..
