### ISSUE TITLE
Palindromes: ("1 eye for of 1 eye.") should return true

### ISSUE THREAD

**Issue by ubcgga** [FreeCodeCamp/FreeCodeCamp#5125]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20p%20%3D%20str.replace(%2F%5Cs%7C%5Cd%7C%5B%2C!%40%23%24%25%5E%26*()-%3A_.%5D%2Fg%2C%20%27%27).toLowerCase().split(%22%22).reverse(%22%22).join(%22%22)%3B%0A%20%20str%3D%20str.replace(%2F%5Cs%7C%5Cd%7C%5B%2C!%40%23%24%25%5E%26*()-%3A_.%5D%2Fg%2C%22%22).toLowerCase()%3B%0A%20%20if(str%20%3D%3D%3D%20p)%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%2F%2F%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%22race%20car%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var p = str.replace(/\s|\d|[,!@#$%^&*()-:_.]/g, '').toLowerCase().split("").reverse("").join("");
  str= str.replace(/\s|\d|[,!@#$%^&*()-:_.]/g,"").toLowerCase();
  if(str === p){
    return true;
  } else{
    return false;
  }
//  return true;
}



palindrome("race car");

```

**Comment by gasperno** [comment]
Why do you consider '1 eye for of 1 eye' to be a palindrome? 
It is not a palindrome, so it should return false.

**Comment by alan1001110** [comment]
@ubcgga For the bonfire, delete punctuation, spaces and symbols, but keep numerals.

**Comment by SaintPeter** [comment]
Closing as this is not an issue with the site.

**Comment by cowarrior1** [comment]
function palindrome(str) {
var as=str.replace(/[.,-\/#!$%\^&\*;:{}=\-_`~()]/g,"");
  var finalas=as.replace(/\s{2,}/g," ").toLowerCase();
  var word= finalas.split("").reverse().join("");
  if (word==finalas){
   return true;
 }
  
  else
    return false;
}

**Comment by bkowshik** [comment]
Yes. Although the problem statement says **remove all non-alphanumeric characters**, I removed the numbers as well. My script is as follows;

```
// Return the reversed sentence.
function reverse(sentence) {
  letters = sentence.split('');
  letters = letters.reverse();
  return letters.join('');
}

# Return true if sentence is a palindrome, false otherwise.
function palindrome(sentence) {
  sentence = sentence.toLowerCase();
  var characters = [];
  for (var i = 0; i < sentence.length; i++) {
    var character = sentence[i];
    if ((character >= 'a' && character <= 'z') || (character >= '0' && character <= '9')) {
      characters.push(character);
    }
  }
  sentence = characters.join('');
  return sentence == reverse(sentence);
}
```

**Comment by iarobinson** [comment]
I made the same mistake @ubcgga!

Numbers like '1234567890' aren't to be removed when comparing palindromes.

My solution = 

`
function palindrome(str) {
  var cleanStr = '';
  var lowerStr = str.toLowerCase();
  var nonAlphaNum = '_ ,.(:/-\\:)-|'.split('');

  for (var i = 0; i < str.length; i += 1) {
    if (nonAlphaNum.indexOf(lowerStr[i]) === -1) {
      cleanStr += lowerStr[i];
    }
  }

  var cleanStrRev = cleanStr.split('').reverse().join('');
  
  if (cleanStr === cleanStrRev) {
    return true;
  }

  return false;
}`

**Comment by FavianIoel** [comment]
Tthis is my clean code , hope you like it 😄 
```
function palindrome(str) {
str = str.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
var strR =str.split("").reverse().join("").toUpperCase();
return str === strR ? true: false;
}
```

**Comment by texas2010** [comment]
@FavianIoel, Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by suraj-davariya** [comment]
Everyone who is misguided please consider that they asked to remove all the non-alphanumeric characters. Do not remove numbers because its a part of the alphanumeric keyboard!
Try this:
`str = str.replace(/[\W\s\_]/gi,"");`

**Comment by MihaelaMarinca** [comment]
function palindrome(str) {
   str = str.toLowerCase().replace(/[\W\s\_]/gi,"");
   return str === str.split("").reverse().join("");
}


palindrome("eye");
