### ISSUE TITLE
Provide a code example for Step 12 of the cat photo project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#51258]
### Describe the Issue

I know that [step 12 ](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12)of the cat photo app has been rewritten a few times, but it still stumps a lot of beginners on the [forum](https://forum.freecodecamp.org/search?expanded=true&q=Learn%20HTML%20by%20Building%20a%20Cat%20Photo%20App%20-%20Step%2012%20after%3A2023-06-01). 
I think we should add a code example of how to nest an anchor element in a paragraph element. 

## Proposed change 
Please read through the updated change in this comment here
https://github.com/freeCodeCamp/freeCodeCamp/issues/51258#issuecomment-1693784945

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

**Comment by 2div** [comment]
Hi, i would like to do this task.
Can you please assign to me if nobody doing it.

**Comment by jdwilkin4** [comment]
@2div 

The following issue has not been triaged yet.
Issues marked with the `Good first Issue` or `Help wanted` labels are available for contribution.
You can read about the contributing guidelines [here](https://contribute.freecodecamp.org/#/index)

**Comment by bbsmooth** [comment]
Relevant issue #49023.

From that issue:
  - Add test specifically to catch extra spaces in link text
  - Reword instructions so that it is clear the existing words "cat photos" in the middle of the `p` element should be changed into a link.

**Comment by lasjorg** [comment]
Considering the previous challenge has a code example I don't see why this one can't have one as well.

But the text is pretty verbose, I'm not sure we need to repeat what they did in the previous challenge to explain this step.

> You can turn any text into a link, such as the text of a `p` element.
> 
> ```
> <p>Visit the <a href="https://forum.freecodecamp.org/">freeCodeCamp</a> forum.</p>
> ```
> 
> In the text of your `p` element, turn the words `cat photos` into a link by adding opening and closing anchor `a` tags around these words. Then set the `href` attribute to `https://freecatphotoapp.com`

**Comment by jeremylt** [comment]
If we put in an example, it definitely should be less verbose. I'm inclined to agree that learners just aren't ready to move away from the copy-paste-edit approach yet by Step 12, so more guidance needed on this Step.

---

I think that the the () are needed grammatically. We can either say

1) `a` element

2) anchor element

3) anchor (`a`) element

but 

"anchor `a` element" doesn't work. We can insert code inline as part of a sentence, but it has to act like a valid part of speech.

**Comment by bbsmooth** [comment]
I'm also seeing a lot of `herf` attributes in the forum. We might want to add a test to check for this.

**Comment by jeremylt** [comment]
Agreed

**Comment by bbsmooth** [comment]
I think we should make the example resemble the solution as much as possible. Thus, the linked text should be in the middle of a sentence. To expand on what @jdwilkin4 suggested, how about something like:

> `<p>I think <a href="https://www.freecodecamp.org/">freeCodeCamp</a> is great.</p>`

If that's too cheesy then please suggest an alternative.

**Comment by jdwilkin4** [comment]
> I think we should make the example resemble the solution as much as possible

I totally agree because we are still really early in the curriculum and this approach will help a lot of beginners understand how to do the challenge.

**Comment by jdwilkin4** [comment]
Thanks for all of the comments guys.

I think we should go with this solution 

You can turn any text into a link, such as the text of a `p` element.

```
<p>I think <a href="https://www.freecodecamp.org/">freeCodeCamp</a> is great.</p>
```
In the text of your `p` element, turn the words cat photos into a link by adding opening and closing anchor `a` tags around these words. Then set the href attribute to https://freecatphotoapp.com

Any final thoughts before we open this up to contribution?
@jeremylt @bbsmooth @lasjorg

**Comment by jeremylt** [comment]
Small tweak - 'text inside of a `p` element'?

Since we aren't talking about everything in the p element?

**Comment by jdwilkin4** [comment]
I opening this issue up for contribution now that the core contributors have finished discussing.

**NOTE** You **do not** need to ask to be assigned to this issue.
Any issue with the `good first issue` label is up for grabs. 

Please read through the [contributing guidelines](https://contribute.freecodecamp.org/#/) and [code of conduct](https://github.com/freeCodeCamp/freeCodeCamp/blob/d31e910f3a4078e01eec87eb181c544f32a0dea4/CODE_OF_CONDUCT.md)

## File you need to make changes to
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md

## Updated instructions for step 12

You can turn any text into a link, such as the text inside of a `p` element.

```
<p>I think <a href="https://www.freecodecamp.org/">freeCodeCamp</a> is great.</p>
```

In the text of your `p` element, turn the words cat photos into a link by adding opening and closing anchor (`a`) tags around these words. Then set the `href` attribute to `https://freecatphotoapp.com/`

**Comment by lasjorg** [comment]
The suggested change looks good to me. But `cat photos` should be inside a code block.

**Comment by jdwilkin4** [comment]
I have updated it, thanks 👍

**Comment by Raxch23** [comment]
for Step 12 :         <p>See more <a href="https://freecatphotoapp.com">cat photos</a>.</p>
it's not working... any advise?

**Comment by gikf** [comment]
Hey @Raxch23,

Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

Thank you and happy coding.
