### ISSUE TITLE
Challenge(Destructuring via rest elements): Be more explicit about the requirements

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#51252]
### Describe the Issue

It happens every so often that people change the `shorterList` identifier to something else. I would suggest we be more explicit in the requirements about not changing it.

Yes, if they read the code and the code comments it should be clear that you can not abide by the code comment and still change the `shorterList` identifier because you have to return `shorterList`. But, that doesn't seem to stop people from doing it anyway.

I suggest we change the challenge text to be more explicit. We might potentially add a test for it as well that checks for the `shorterList` identifier in code if needed.

> Use a destructuring assignment with the rest syntax to emulate the behavior of `Array.prototype.slice()`. `removeFirstTwo()` should return a sub-array of the original array `list` with the first two elements omitted and the rest of the elements added to `shorterList`.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-parameter-to-reassign-array-elements

### Your code

```



```

### Expected behavior

Do not rely on code comments for requirements that can be explicitly stated.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

https://forum.freecodecamp.org/t/es6-destructuring-via-rest-elements/629405

**Comment by ShaunSHamilton** [comment]
Personally, I would just add a test:
> You should return `shorterList` from the function.

But, am happy to go with your sentence too.

**Comment by naomi-lgbt** [comment]
I like the idea of adding a test, yeah.

**Comment by bbsmooth** [comment]
Can we do both? If people are changing the variable name with what we have now then it seems like we should be proactive instead of telling them they were bad after the fact and then they have to rewrite their code (or reset the lesson).

**Comment by naomi-lgbt** [comment]
Actually, can we go the other way? I think the tests could be refactored to not care what variables are used, so long as destructuring is used and the correct value is returned.

**Comment by ShaunSHamilton** [comment]
Yes, I would prefer Naomi's latest, as it prevents bloat in the description/instructions.

---

I do not like the idea of adding more of the same instruction because _Campers do not read_. If an instruction is given once, that should be enough. If a Camper opens a forum post about it - good. They have done just the thing devs need to learn, and they can be referred to what they _did not read_. Programming is all about the specific, little things. _rant over_

**Comment by lasjorg** [comment]
I tend to agree. It seems more like a limitation of the test than anything important of the requirements.

---

@ShaunSHamilton The instructions are not explicit about having to use the `shorterList` identifier. There is nothing in the requirements that says the `shorterList` identifier can't be renamed. It is only the code comment that implies this.

**Comment by ShaunSHamilton** [comment]
> It is only the code comment that implies this.

This counts as part of the instructions. The code comment is an instruction to the Camper.

**Comment by lasjorg** [comment]
> This counts as part of the instructions. The code comment is an instruction to the Camper.

I think it is a poor way of specifying requirements - implicit requirements through code comments are unnecessary when we can just make a clear sentence.

Or at least have the test message make sense. I mean if you saw that assert message what would your initial thoughts about what was wrong with your code be?

I agree people should read the code comments but I don't think they can excuse the lack of clear instructions, proper assert messages, or better tests (which seems like the correct solution here, to fix the tests).

**Comment by naomi-lgbt** [comment]
Okay, I've drafted a PR so we can start discussing actual implementation approaches. 😁
