### ISSUE TITLE
Dead Links using hash symbol

### ISSUE THREAD

**Issue by Dachepally3097** [FreeCodeCamp/FreeCodeCamp#5126]
I have replaced href with the #, and the link is dead. FreecodeCamp is not moving to the next challenge. 
Challenge [Waypoint: Make Dead Links using the Hash Symbol](http://www.freecodecamp.com/challenges/waypoint-make-dead-links-using-the-hash-symbol#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20%23%3D%22http%3A%2F%2Fwww.freecatphotoapp.com%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a #="http://www.freecatphotoapp.com">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by gasperno** [comment]
Hi @Dachepally3097 , 
You are supposed to write `<a href="#">` instead of `<a #="http://www.freecatphotoapp.com">`
We have an friendly community that helps you in resolving issues related to waypoints. Please visit [this ink] (https://gitter.im/FreeCodeCamp/Help) to get your questions answered.
Happy Coding.

**Comment by ltegman** [comment]
@gasperno is correct. Thanks and happy coding!

**Comment by Priya2013** [comment]
what's wrong with this code?
![make_dead_link](https://cloud.githubusercontent.com/assets/4607371/14998787/c9b85c68-1142-11e6-9ef0-c57824ae231a.jpg)

**Comment by dwd2010** [comment]
@Priya2013, You could ask help at [Help Chat Room](https://gitter.im/FreeCodeCamp/Help). 

Happy Coding!

**Comment by Priya2013** [comment]
It's not the right place to ask?

**Comment by dwd2010** [comment]
@Priya2013, I dont have answer for your question. when you ask a help at chat room. they will help you with your challenges.

**Comment by determinedforce** [comment]
The correct answer would be: "I don't know. Ask in the chat room." Easy Peezy

**Comment by determinedforce** [comment]
I was confused as well. The wording of that paragraph should be changed. "....to turn it into a dead link." To me that means the link would stay thus 'href' would be replaced with the hashtag.

**Comment by Rahat-Noman** [comment]
I am facing the same problem .with this challenge

**Comment by sahelsson** [comment]
gasperno gave us the correct answer, just scroll up.

**Comment by paulinafischer** [comment]
<p>Click here for <a href="#">cat photos</a>.</p>

**Comment by paulinafischer** [comment]
just <p>Click here for <a href="#">cat photos</a>.</p>

**Comment by paulinafischer** [comment]
(<p>Click here for <a href="#">cat photos</a>.</p>)

**Comment by paulinafischer** [comment]
``<p>Click here for <a href="#">cat photos</a>.</p>

**Comment by paulinafischer** [comment]
`<p>Click here for <a href="#">cat photos</a>.</p>`

**Comment by codeismybaby** [comment]
Hi, Can some one please help me to solve this problem? Your a element should be a dead link with a href attribute set to "#". I did this <p>Click here for <a href="#">cat photos</a>.</p>

**Comment by codeismybaby** [comment]
<a href="#">cat photos</a>

**Comment by codeismybaby** [comment]
it is not making my link dead link href:"#"

**Comment by Notch6886** [comment]
dude

**Comment by Notch6886** [comment]
lol

**Comment by Notch6886** [comment]
@codeismybaby its href="#"

hoped i helped u out

```
<a href="#">
```

**Comment by YanivStern** [comment]
This is the pattern you should write:
<p>Click here for <a href="#">cat photos</a>.</p>
If it doesn't work- refresh the page- then try again.

**Comment by MaDTrX** [comment]
i tried <a href="#"> didn't work

**Comment by khan777** [comment]
same probleeeeemoo. did everything..

**Comment by MaDTrX** [comment]
Just refresh and do the same thing, its right.

**Comment by ImJustKenny** [comment]
its <a href="#" delete the http://whateveritis.com or what ever


![screenshot_11](https://cloud.githubusercontent.com/assets/25495736/22581524/759d8258-e995-11e6-882c-f77f05e51f77.png)
