### ISSUE TITLE
Old Twitter Logo

### ISSUE THREAD

**Issue by Ayushtx** [freeCodeCamp/freeCodeCamp#51278]
### Describe the Issue

This is a minor issue, the twitter logo on the profile page is that white bird but actually its an "X" symbol so i believe we should change that logo to the latest one.

### Affected Page

https://www.freecodecamp.org/Adarshtx

### Steps to Reproduce

1. Just go on anyone's code camp public profile
2. There you can see the old twitter logo

### Expected behavior

Just expecting a new twitter logo there

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome

**Comment by Programmer-Dost** [comment]
In everyone's profile? Where can I find the code for it? I am working on this issue!!

**Comment by jeremylt** [comment]
This issue has not been marked as ready for contributions yet

**Comment by azr-arch** [comment]
has the contributions started yet ?

**Comment by jeremylt** [comment]
Still no. We'll clearly indicate when an issue is ready for a contribution

**Comment by lasjorg** [comment]
The icon is now `faXTwitter`

`https://fontawesome.com/icons/x-twitter?f=brands&s=solid`

Searching shows at least two locations. Not sure if the icon is only used with the FA React components.

```
client/src/components/share/share-template.tsx
client/src/components/profile/components/social-icons.tsx
```

The current dependencies should be good to go (tested).

**Comment by sridhar-dev** [comment]
@lasjorg, I think so we need to change both the icons that you mentioned

**Comment by lasjorg** [comment]
I would think so. But until someone from the dev team chimes in I'm not sure what the plan is.

**Comment by shreyaspathak11** [comment]
i would like to work on it

**Comment by ShaunSHamilton** [comment]
This seems fine to open up for contributions. I cannot see any more uses of the Twitter logo on the platform other than what @lasjorg mentioned:

> ```bash
> client/src/components/share/share-template.tsx
> client/src/components/profile/components/social-icons.tsx
> ```

**Note:** We do use `fa-twitter` in the curriculum, but this should not be changed. _At least not in the same pr / yet_. For this issue, we are concerned with just the platform code.

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by IndranilChutia** [comment]
i want to work on this issue

**Comment by MikeJakuszewski** [comment]
Can I work on this issue?
