### ISSUE TITLE
Lost all my completed waypoints & bonfires while switching laptops

### ISSUE THREAD

**Issue by darrynwu** [FreeCodeCamp/FreeCodeCamp#5129]
I finished subjects #1-#8 on the "Map."  However, when I brought a new laptop, went to log in there using my Github account, it seems to have lost everything.  Meaning it looks like I never finished anything.

**Comment by bugron** [comment]
@darrynwu is this still an issue for you?

**Comment by darrynwu29** [comment]
No, it is working fine now.  Sorry, forgot to update.  Thanks

**Comment by bugron** [comment]
Then closing this issue as resolved. Thanks for posting.
