### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue 

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/freecodecamp#513]
Bug? Code is correct but doesn't work.

**Comment by QuincyLarson** [comment]
@Stiino0 Thanks for bringing this to our attention. We've fixed this!

**Comment by Stiino0** [comment]
Thank you so much for fixing this, and i'm glad I could help with reporting, happy to do something for the community!!

Cheers,

Stiino0

Verstuurd vanaf mijn iPhone
