### ISSUE TITLE
Add Number of Hours to the Certifications

### ISSUE THREAD

**Issue by estefaniacn** [freeCodeCamp/freeCodeCamp#51305]
### Is your feature request related to a problem? Please describe.

Currently, the redesigned certifications do not include the approximate number of hours of coursework required to complete the certifications. 

### Describe the solution you'd like

Our goal is to add the text "representing 300 hours of coursework" to the text of the certifications. 

### Describe alternatives you've considered

The redesigned certifications did not include the approximate number of hours of coursework required. This modification was requested by members of the community.

**Comment by jeremylt** [comment]
See #51215
