### ISSUE TITLE
Stop making assumptions about names

### ISSUE THREAD

**Issue by smiller171** [FreeCodeCamp/FreeCodeCamp#5130]
In the first few waypoints dealing with strings you work a lot with first name and last name. This seeds bad ideas in people's heads about names. See link: http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by SaintPeter** [comment]
While it is indeed true that not everyone has a "first" or "last" name in the sense that this exercise calls for, there is no strong requirement that they enter anything particular at all.  I am reasonably confident that anyone who is capable of reading the problem understand the CONCEPT of first and last names.  Moreover, if you're going to be doing work in the English speaking world, you're going to have to deal with this concept.
