### ISSUE TITLE
Need proper introduction for CSS id selector

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#51319]
### Describe the Issue

I believe that [step 8 of the accessibility quiz](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-8) is the first time the CSS id selector is introduced. (I searched the previous courses and did not find it. Even though the registration form uses the `id` attribute on some HTML elements it does not style them with the id selector.) The instructions for step 8 ask the user to style the image using its `id` as the selector but they don't explain how to do that. The user only gets this information from a hint if they don't do it correctly.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-8

### Your code

N/A

### Expected behavior

I think it is preferable if we explain how to use the `id` selector in the instructions instead of having the user fail and then telling them how to do it through a hint. Since step 8 already has a considerable amount of content explaining the `max` function, one option would be to create a new step just for explaining the `id` selector. Step 9 has the user add `padding` to the image, so we could create a new step before the current step 8 with an explanation on how to target by `id` and have them add the `padding` in that step instead (since they are already familiar with that property). This new step would be similar to [step 26 in the Cafe Menu.](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-26).

But if adding a step is a pain then we could swap step 8 and step 9 since step 9 has a relatively small amount of content, and add the explanation of the `id` selector there.

Or we could look for a place in a previous course to use the id selector. It does seem a little odd to wait so long to use it since it is a pretty popular selector.

Or I suppose we could do nothing and keep relying on the hint to give them the information after the fact. To be honest, I don't recall seeing too many issues about this in the forums. I did a search and maybe found one or two that were about this issue out of the thirty or so I looked at. So perhaps the hint method is doing its job? It just seems to me that an important and common selector like this should be clearly explained up front. This isn't something they would be able to deduce from information they have already learned. They would need to go to an outside source to figure it out since it is a completely new selector.

### System

N/A

**Comment by lasjorg** [comment]
I think the id selector should be used and explained in "Learn Basic CSS by Building a Cafe Menu" which introduces CSS selectors. I see no reason why it can't be.

Maybe for the wrapping `div` element (so `#menu` instead) or for the `footer` element.

**Comment by JayRKyd** [comment]
If no one is working on this issue i'd like to give it a shot

**Comment by naomi-lgbt** [comment]
I like the idea of introducing it earlier, yeah.

I would propose editing [Step 20](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-20) of the Cafe Menu to set the `id="menu"` attribute on the `div`, then editing [Step 21](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-21) to teach the `#menu` selector.

**Comment by lasjorg** [comment]
For anyone doing this PR remember the change has to be reflected through all the seed code. So it is not just changing two challenges. But the two, and all following seed code (CSS selector and HTML attribute). And BTW, this challenge has 91 steps.
