### ISSUE TITLE
way point is not clear on initial value

### ISSUE THREAD

**Issue by alkazemi** [FreeCodeCamp/FreeCodeCamp#5132]
hi
although i knew how to pass the challenge it didn't make sense to me and i had to google reduce functions to understand how it's working since it's not clear and the example given should return the value -22 not 30. i calculated the array multiple times and subtracted the numbers in different ways to get -30 but i couldn't until i played around with the code and removed the initial value which is 0 and realise that the code wont work without it so i googled further and understood the reasoning and meaning of the code. 

i think the initial value part should be stated clearly and the code explained better perhaps with a table like the website i found as the current explanation is confusing for a newcomer like myself

thanks

**Comment by ltegman** [comment]
Please link to the challenge you are referring to.

**Comment by alkazemi** [comment]
Sorry about that here:
http://www.freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce

**Comment by sludge256** [comment]
The code will work with or without the initial value of 0.

The last half of the instructions is where you need to read carefully.
"Here is an example of reduce being used to **subtract** all the values of an array:"

"Use the reduce method to **sum** all the values in array and assign it to singleVal."

**Comment by bugron** [comment]
Closing this issue as stale. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first. Feel free to reopen if you still experience problems, thanks.
