### ISSUE TITLE
Tests for Cat Painting Step 8 Too Strict

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#51330]
### Describe the Issue

You can only pass this step if you put everything on one line and have a space after the comma.

P.S. You cannot have a space before the first color either, or after the last percentage.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/step-8

### Your code

For example, this will not pass:

```
background: linear-gradient(
  #5e5e5e 85%,
  #45454f 100%
);
```

### Expected behavior

Any valid CSS should be able to pass.

### System

N/A

### Additional context

This has come up several times in the forum in the past few ~~days~~hours.

**Comment by lasjorg** [comment]
Tests: `https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646c5ace05e4be4211407935.md`

Shouldn't we just be checking the computed styles instead?

---

Example:

Your `linear-gradient` function should set the first color to be `#5e5e5e` at `85%`.

```js
const gradientBackgroundImage = new __helpers.CSSHelp(document).getStyle('.cat-head')?.getPropVal('background-image', true);
const firstGradient = gradientBackgroundImage.split(/rgb/)[1];
assert.equal(firstGradient,'(94,94,94)85%,');
```

Your `linear-gradient` function should set the second color to be `#45454f` at `100%`.

```js
const gradientBackgroundImage = new __helpers.CSSHelp(document).getStyle('.cat-head')?.getPropVal('background-image', true);
const secondGradient = gradientBackgroundImage.split(/rgb/)[2];
assert.equal(secondGradient,'(69,69,79)100%)');
```

**Comment by RockyPukar1** [comment]
#51339 fixes this issue.

I have also added a compulsory check for space after background: .

**Comment by lasjorg** [comment]
@RockyPukar1 This issue has not been opended to contribution yet. Please do not create PRs until it has.

---

I think using the computed styles is a better option.

The current regex also has some `\s+` that should be `\s*` I would think as the spaces are not required.

**Comment by TanishqRinjay** [comment]
Can I work on this?
This will be my first contribution, please guide me through this

**Comment by RockyPukar1** [comment]
@TanishqRinjay  I have already started working on this. If you are first time in open source contribution you can start with the issues that has label as first-timers-only or good-first-issue. Otherwise, if you are comfortable you can start from here too.

**Comment by bonheur832** [comment]
> ### Describe the Issue
> You can only pass this step if you put everything on one line and have a space after the comma.
> 
> P.S. You cannot have a space before the first color either, or after the last percentage.
> 
> ### Affected Page
> https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/step-8
> 
> ### Your code
> For example, this will not pass:
> 
> ```
> background: linear-gradient(
>   #5e5e5e 85%,
>   #45454f 100%
> );
> ```
> 
> ### Expected behavior
> Any valid CSS should be able to pass.
> 
> ### Screenshots
> _No response_
> 
> ### System
> N/A
> 
> ### Additional context
> This has come up several times in the forum in the past few ~days~hours.

Thanks alot!
