### ISSUE TITLE
React Zipline - User leaderboard

### ISSUE THREAD

**Issue by roelver** [FreeCodeCamp/FreeCodeCamp#5133]
Uses: ReactJS and jQuery (for API calls)
API-URL: http://fcctop100.herokuapp.com/api/fccusers/[recent|alltime]/:sortColumnName

User Stories:

As a user I can see the leading FCC users based on the total score in the past 30 days (incl. bonus)
As a user I can switch to the all-time overview and back to the 30 days
As a user I can change the order of the list on one of the other columns
As a user I can refresh the statistics of one of the users
 
Demo: http://codepen.io/rokidoki/full/MKWVKW/

**Comment by SaintPeter** [comment]
:heart: Love this idea!

**Comment by LenaBarinova** [comment]
@QuincyLarson, @roelver I'd love to do this one!

**Comment by SaintPeter** [comment]
@LenaBarinova Would you be able to design the API endpoint as well?

**Comment by LenaBarinova** [comment]
@SaintPeter Yes. I think I'll do it a couple of iterations. My first idea would be:
Iteration1. UI part + API method to get all the points for users from current user profiles in mongodb
Iteration2. Create some kind of points aggregation persistence (as key-value). Probably even store 30 days and all the rest in two different places. Update those aggregates either periodically or on challenge complete event (I'd prefer the second option).

Haven't thought about this problem too much yet, once I have a vision - I'll share it.

**Comment by roelver** [comment]
@LenaBarinova + @SaintPeter , Are you aware that this is already completed? The demo codepen is a UI on top of the API from the current leaderboard I made: http://fcctop100.herokuapp.com . It's ready for use as example for ziplines.
It would be great however if the data could be updated more efficiently and/or the API to be hosted on the FCC site.

**Comment by LenaBarinova** [comment]
@roelver why then it was labeled as a ```help wanted```?

**Comment by roelver** [comment]
I don't know. @QuincyLarson ? 
Well, the design is not award-winning. ;-) If you want to make a nicer UI, I can give you the specs for the API.

**Comment by SaintPeter** [comment]
@roelver Am I correct that your version just uses web-scraping?  Or is there an API endpoint I am not aware of?  Ideally I'd like to get that API endpoint created and re-target your existing interface to use the API.

Huh:
http://fcctop100.herokuapp.com/api/fccusers/recent/username

That returns data.  Although everything is 0s for now.  So maybe it needs to be completed?

**Comment by SaintPeter** [comment]
OH - that's pulling from YOUR data, and we already know there is an issue with your ability to scrape.

So I do believe there is a need for an official FCC API endpoint, as proposed by @LenaBarinova.

**Comment by roelver** [comment]
The [codepen version](http://codepen.io/rokidoki/full/MKWVKW/) is a React frontend on my leaderboard database on Heroku. @QuincyLarson asked for that so I gave it a try. The column Community Help is a new value he suggested. 
Of course it would be better if the scores came from an API on top of FCC data, but that may be too short notice for the launch in January. On the other hand, adding the aggregated counters to the existing user data, wouldn't be too hard. That's all it needs for backing the leaderboard, and maybe a couple of indexes to speed up the descending sort. That would allow all FCC users to appear in the leaderboard, while now only users with a Github profile are listed. I suspect those are the real fanatics, though. :wink:

**Comment by SaintPeter** [comment]
Well, ideally @LenaBarinova could turn it around in such a short time frame because: 1) we're open source, so many hands makes light work and 2) She's some sort of genius or something.

**Comment by roelver** [comment]
Can we decide to add a couple of attributes to the FCC user collection just like that? Aren't there performance and storage considerations here? And there must be a process running to keep the counters up-to-date, or would you include that in the current method that registers the completed assignment or brownies?

**Comment by SaintPeter** [comment]
Sure, why not?  Adding a couple of counters won't break our piggy-bank.  Running a nightly or twice daily update probably won't break anything.  Maybe it could be phased?  Honestly, I have no idea.  I presume that there exist efficient ways to do these things.

What @LenaBarinova said above makes sense to me:
> Iteration1. UI part + API method to get all the points for users from current user profiles in mongodb
Iteration2. Create some kind of points aggregation persistence (as key-value). Probably even store 30 days and all the rest in two different places. Update those aggregates either periodically or on challenge complete event (I'd prefer the second option).

I would say we move forward until @BerkeleyTrue or @QuincyLarson say no.  Considering that Quincy proposed the Zipline to begin with, I think we have a mandate.

**Comment by LenaBarinova** [comment]
@roelver I wouldn't suggest adding any aggregated data to profiles. In my mind it should be something separate in storage (new collection for just this use case) and asynchronous from current challenge completion registration.

**Comment by QuincyLarson** [comment]
@LenaBarinova Sorry for the confusion. I added the help wanted label and forgot to remove it once @roelver mentioned his interest. It looks like you two are already discussing this. Perhaps you can collaborate on this?

@BerkeleyTrue and I can start working on a custom endpoint for this. Please let us know what data you all need.

**Comment by roelver** [comment]
@QuincyLarson I described the interface in [issue #5322](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5322)
I wrote an update node script to export the data to a CSV file https://github.com/roelver/fccexport. You could use that as a starter and update a Mongo collection instead.
I agree with @LenaBarinova that it is safer to use a new collection for the leaderboard data. A document in my current database looks like this:
```
> db.fccusers.find({username: "roelver"})
{ "_id" : ObjectId("5616e35ecc915403001ad57e"), "username" : "roelver", "existing" : true, "points" : 387, "ziplines" : 10, "waypoints" : 244, "bonfires" : 46, "basejumps" : 5, "__v" : 40, "img" : "https://avatars.githubusercontent.com/u/476351?v=3", "lastUpdate" : ISODate("2015-12-16T03:29:44.344Z"), "total" : 1125, "basejumpsRecent" : 1, "bonfiresRecent" : 0, "pointsRecent" : 16, "totalRecent" : 76, "waypointsRecent" : 8, "ziplinesRecent" : 0, "following" : [ "SaintPeter" ], "community" : 82, "communityRecent" : 7 }
```
the property 'existing' indicates that this user has a profile page on FCC with this username. The "following" array is a feature on the Heroku leaderboard for Github authenticated users.

**Comment by QuincyLarson** [comment]
@roelver I will talk with @BerkeleyTrue about implementing this. We planned to go "open data" sooner rather than later, and this may be a good excuse for us to do so sooner. We will be extremely careful about not exposing sensitive user data (basically the only thing we have that isn't already public is email address).
