### ISSUE TITLE
Test Variable Collides With Common User Variable 

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#51344]
### Describe the Issue

The test variable here should be prefaced with an _ or something like that to prevent colliding with a common user variable name.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person.md

### Your code

```javascript
const Person = function(first, last) {
  let firstName = first;
  let lastName = last;

  this.getFirstName = function() {
    return firstName;
  };

  this.getLastName = function() {
    return lastName;
  };

  this.getFullName = function() {
    return this.getFirstName() + " " + this.getLastName();
  };

  this.setFirstName = function(first) {
    return firstName = first;
  };

  this.setLastName = function(last) {
    return lastName = last;
  };

  this.setFullName = function(first, last) {
    this.setFirstName(first);
    this.setLastName(last);
    return this.getFullName();
  };
};

// an instance of Person named as lowercase `person`.
// If the variable name is not `person` (such as "bob") , it would get passed.
const person = new Person("Bob", "Ross");
console.log(person.getFullName());

```

### Expected behavior

Valid code should pass

### System

All

**Comment by gikf** [comment]
From the individual tests:
```
const person = new Person('Bob', 'Ross');
```
can be moved to the `## --after-user-code--`. This alone would be enough to make it not affected by such collision. Additionally using underscore after that, while not necessary also would be fine.

**Comment by jeremylt** [comment]
This is entirely user written code above. The user's choice of variable name conflicts with the variable name in the test suite, so we need to use a less common variable name in the test suite.

**Comment by naomi-lgbt** [comment]
Whoops - this one was my fault haha.

**Comment by naomi-lgbt** [comment]
To confirm the fix:

Within the [challenge file](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person.md), all instances of the `person` variable **in the tests** should be changed to `_person`.

**Comment by Riya267** [comment]
@naomi-lgbt  I have added this minor fix Please review Thanks
