### ISSUE TITLE
success alert on the top does not collapse itself

### ISSUE THREAD

**Issue by DeadAnjali** [freeCodeCamp/freeCodeCamp#51357]
### Describe the Issue

Success alert below the navbar(e.g. after updating profile) does not collapse itself which can be inconvenient for the user.

### Affected Page

https://www.freecodecamp.org/learn

### Steps to Reproduce

1. Go to 'Profile'
2. Update anything on your profile
3. A success alert will appear on screen
4.It does not collapse and stays on all pages until the website has been refreshed for another session

### Expected behavior

All types of alerts should automatically collapse after some time and shouldn't have to be closed by the user.

### Screenshots

![Screenshot (1456)](https://github.com/freeCodeCamp/freeCodeCamp/assets/122856861/3a88195c-8ba2-4e56-9b1c-7bc0fd18e4ae)

### System

- Browser: [e.g. Microsoft Edge, ]

**Comment by gikf** [comment]
Could you expand on the reasons why do you think such change should be made?

While I'm not able right now to find specifics, I'm fairly sure that's an intentional design decision.

**Comment by rameshvoodi** [comment]
@gikf there's no need for a change, it was intensional.

**Comment by naomi-lgbt** [comment]
Yes, this is an intentional design decision to allow learners as much time as they need to read and understand an alert message.
