### ISSUE TITLE
jest not recognized error when trying run ui-components tests at windows

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/freeCodeCamp#51356]
### Describe the Issue

im trying to run tests of `ui-components`,  
as it says in the docs - im running `pnpm run test-ui-components` command  
im getting `'jest' is not recognized as an internal or external command ` error message on the terminal
im using 
windows 11
node v20.1.0

### Affected Page

https://contribute.freecodecamp.org/#/how-to-work-on-the-component-library

### Your code

```
pnpm run test-ui-components



```

### Expected behavior

tests should run

### Screenshots

![not-recognized](https://github.com/freeCodeCamp/freeCodeCamp/assets/1336862/57202bfb-83c3-4ebb-a68e-d6e5feaf2396)

### System

- Device: Desktop
- Windows 11
- Browser: Chrome 
- Version: node 20.1.0

**Comment by gikf** [comment]
Looks like some dependency issue. 

I've double checked on gitpod to make sure there's no issues

**Comment by gikf** [comment]
Looks like some issue with dependency. `jest` should be installed as a dev dependency along other dependencies. Perhaps that didn't happen?

I've double checked on gitpod to make sure similar issue doesn't occur on different OS.

**Comment by shootermv** [comment]
I think may be this issue should be closed since now i see that running
project at windows native not recommended.
And tests do run at WSL
