### ISSUE TITLE
Example code not outputting on screen?

### ISSUE THREAD

**Issue by jamieschmid** [FreeCodeCamp/FreeCodeCamp#5136]
Somewhere in the beginning of this section, I stopped seeing the output panel below the code window; I see there's output code IN there but just an empty white space below. The output code's been really helpful and I know it's just returning a number or a letter right now but it still would be enourmously helpful for exploring the new concept and troubleshooting.
I was in Chrome and changed to Safari to make sure it wasn't a browser issue but it's the same in both.
Any info on this? Is it deliberate or is it just not showing up for me for some reason?

**Comment by ltegman** [comment]
Could you please let us know what section you're in and at what specific challenge you stopped seeing output? Thanks!

**Comment by jamieschmid** [comment]
Hmm.. It actually hasn't shown at all on any of the Basic JavaScript challenges. Attaching screencaps. I've tried in both Chrome and Safari.
<img width="1290" alt="screen shot 2015-12-12 at 4 35 54 pm" src="https://cloud.githubusercontent.com/assets/6207905/11764670/aeee894e-a0ee-11e5-80ed-e44980e20c62.png">
<img width="1292" alt="screen shot 2015-12-12 at 4 35 03 pm" src="https://cloud.githubusercontent.com/assets/6207905/11764671/af0fd220-a0ee-11e5-937e-6b34a6e202ad.png">

**Comment by jamieschmid** [comment]
Ok so I *think* I've figured out what's going on. Instead of how all challenges leading up to this section have behaved, this section shows output on the success screen in the lower left of the screen (see my screencap attached); and it only shows after I have successfully completed that challenge? If this is the case I'm assuming the normal area is reserved for browser output in upcoming challenges.. ?
<img width="1432" alt="screen shot 2015-12-12 at 4 53 30 pm" src="https://cloud.githubusercontent.com/assets/6207905/11764744/44e6be06-a0f1-11e5-87cb-ccf477cd9181.png">

**Comment by BerkeleyTrue** [comment]
Anyone else experiencing this?

**Comment by sludge256** [comment]
I have experienced it in the past and someone mentioned it in chat fairly recently. They will reappear if you attempt to run any code though.

**Comment by bugron** [comment]
Seems this is fixed now. Closing. Feel free to reopen if you still experience problems, thanks.
