### ISSUE TITLE
Adjust Crowdin Schedules

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#51362]
Uploads: Everyday
Downloads: Twice a week

This should suffice our deployment targets which are usually ~~Mondays~~ Tuesdays? and Thursdays (optional) at around UTC+3

We can shake it up so that PRs can be merged on Mondays and Wednesdays?

**Comment by naomi-lgbt** [comment]
So downloads should be triggered on Mondays and Wednesdays?

**Comment by raisedadead** [comment]
Yes, or a day before, for all we care. As long as they are:

1. Twice a week only
2. Merged on Mondays and Wednesdays for deployments on Tuesdays and Thursdays
