### ISSUE TITLE
Bonefire: Error Potential infinite loop

### ISSUE THREAD

**Issue by Dishant15** [FreeCodeCamp/FreeCodeCamp#5139]
I am at Bonfire: Smallest Common Multiple; and it gives me this potential infinite loop error. I checked my code localy and it does not have infinite loop and also gives correct output. But i can not pass the bonefire as i can not even submit code due to this error.
After that i went to one of my old code that is Bonfire: Chunky Monkey that i have already passed and also has nested loops. And as expected this error shows up again here is the screen shot:

![screen shot 2015-12-11 at 9 15 19 am](https://cloud.githubusercontent.com/assets/3438538/11735535/36639ffc-9fe8-11e5-9395-64d982241a3f.png)

This code has already passed before so i think this error is due to a recent update which is failing to detect infinite loop.

My code:
```javascript
function chunk(arr, size) {
  var l = 0;
  var ansArray = [];
  while(l<arr.length){
    var arrTemp = [];
    size = l+size > arr.length ? arr.length - (l+size) : size;
    for(var i=0;i<size;i++){
      arrTemp.push(arr[l+i]); 
    }
    ansArray.push(arrTemp);
    l = l+size;
  }
}

chunk([0, 1, 2, 3, 4, 5], 4);

**Comment by shl-kfy** [comment]
@Dishant15 
I think your code has bug.
see more at http://jsfiddle.net/s557g4x7/4/
the reason for infinite loop is $var l$ becoming negative during __while loop__,
F12 into debug to see the results in the console of the browser you use.

curious about why the first time this code pass tests

**Comment by ltegman** [comment]
As @shl-kfy points out, your code legitimately has an infinite loop in it. If you're ever concerned that the protection is flagging a false positive you can add `//noprotect` to the top of the file, but you open yourself up to the possibility of locking up the page, which is what will happen in this case.

Thanks and happy coding!
