### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/freecodecamp#514]
unrecognized expression, but it is correct:

<'label><'input type='checkbox' name='personality' checked> Loving<'/label>

**Comment by ianseabrook** [comment]
Also seeing this issue.

**Comment by terakilobyte** [comment]
it looks like you've erroneously added a ' to your `<'label>` tags.

**Comment by Stiino0** [comment]
Hi Nathan,

Sorry: the ' are there because I couldn't get the html code to spel out in the comment, it only showed the text between elements.

I don't know how to quote code in github comments!!

So embarassing...

Verstuurd vanaf mijn iPhone
