### ISSUE TITLE
example text can be corrected? 

### ISSUE THREAD

**Issue by AnnieMouse13** [FreeCodeCamp/FreeCodeCamp#5140]
Challenge [Waypoint: Target HTML Elements with Selectors Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I don't know if any other browser (I use FireFox 42.0 on Windows 10) shows the same issue that mine does. In the example for the code (addClass) there is no semicolon.  I found it on the wiki, but it was a bit of frustration to get it to work. I've attached a screen clip to demonstrate how it looked on my screen.

![capture1](https://cloud.githubusercontent.com/assets/10452839/11735682/2a683dd0-9f92-11e5-853f-e8659bad9790.PNG)

My code:
```html
<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by ltegman** [comment]
This code isn't technically wrong since semicolons aren't required in Javascript, but using semicolons is FCC's preferred style, so these should be added to the example. Thanks for pointing this out :smile:

**Comment by redarrow** [comment]
This was fixed in my pull request 5161 but I made a mistake and didn't add the issue number
