### ISSUE TITLE
Improve UX on invalid URL submissions by user

### ISSUE THREAD

**Issue by tawfiqkhalilieh** [freeCodeCamp/freeCodeCamp#51419]
### Describe the Issue

I was collecting my first trophy in the new Freecodecamp X Microsoft Foundational C# with Microsoft and I'm getting 500 status code when I try to connect my freecodecamp account to my Microsoft account to collect the trophy
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/511b703f-b4be-4166-b131-eaee67eff552)

### Affected Page

https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/write-your-first-code-using-c-sharp/trophy-write-your-first-code-using-c-sharp

### Steps to Reproduce

1. go to https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/
2. start doing the first phase (Trophy - Write Your First Code Using C#)
3. solve all the challenges.
4. try to connect to your Microsoft account

### Expected behavior

The backend crashs and shows 500 status code (Something went wrong)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/1a4da27e-e792-4575-b541-e9ca22218533)

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/10160c33-bbd3-4db5-987e-0e4db3178769)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/cfd5075d-5981-477b-8e60-0ee6f94b3d53)

### System

- Device: PC
- OS: Windows 11
- Browser: Brave ( chromium )
- Version: Version 1.57.53 Chromium: 116.0.5845.114 (Official Build)  (64-bit)

**Comment by tawfiqkhalilieh** [comment]
here is the response
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/3bd62123-f38f-4149-89a0-c65b51b3df02)

**Comment by tawfiqkhalilieh** [comment]
Its hapenning in all the phases
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87164562/8f0e3dd8-bb6f-49aa-a4df-af0db4573f04)

**Comment by ShaunSHamilton** [comment]
There seems to be some confusion about which link to submit. The expected link format is:

```
https://learn.microsoft.com/<LOCALE>/users/<USERNAME>/transcript/<UNIQUE_ID>
```

We should definitely improve the error, but maybe the instructions to get the URL need more work as the priority.

**Comment by ShaunSHamilton** [comment]
I do see that the URL we used to test also does not work saying the "transcript is no longer available".

**Comment by moT01** [comment]
If you want @ojeytonwilliams 👍 The front end form could use some help. I only added a [`length > 0` check](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/ms-trophy/link-ms-user.tsx#L147) cause it was last minute. We could validate that it's a valid transcript link, and give better feedback if it's not - "Please use a valid Microsoft transcript URL for your account" or something.

**Comment by ShaunSHamilton** [comment]
I am struggling to think of a way to write this in the current api with translatable error messages - there will be dozens of them, because there are many ways linking/submitting can be _done incorrectly_.

So far, this is what I can think of adding to the API:
```js
const transcriptValidity = validateTranscriptUrl(msTranscriptUrl);
if (!transcriptValidity.ok) {
  return res.status(422).send(transcriptValidity.error);
}

function validateTranscriptUrl(urlString) {
  try {
    const url = new URL(urlString);
    const { hostname, pathname } = url;
    if (hostname !== 'learn.microsoft.com') {
      return {
        ok: false,
        error: 'URL should come from `learn.microsoft.com` domain'
      };
    }
    const pathSegments = pathname.split('/');
    const [locale, users, username, transcript, uniqueId] = pathSegments;
    if (
      !locale ||
      users !== 'users' ||
      transcript !== 'transcript' ||
      !username ||
      !uniqueId
    ) {
      return {
        ok: false,
        error:
          'URL should follow format `https://learn.microsoft.com/<LOCALE>/users/<USERNAME>/transcript/<UNIQUE_ID>`'
      };
    }
    return { ok: true, error: null };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}
```

**Comment by ShaunSHamilton** [comment]
Ideally, we would also:
- If URL is valid, check user's Microsoft learn account has completed necessary/any modules
  - If not, respond in kind.

**Comment by daVinci13** [comment]
Workaround, open link in each section, complete all on Microsoft site, go back and verify.

**Comment by raisedadead** [comment]
> I am struggling to think of a way to write this in the current api with translatable error messages - there will be dozens of them, because there are many ways linking/submitting can be done incorrectly.

This need not be done on the API side at all. This should be done one the client. I have opened another issue for it if you want to continue working on it.
