### ISSUE TITLE
API Basejump - Image search

### ISSUE THREAD

**Issue by george-stepanek** [FreeCodeCamp/FreeCodeCamp#5141]
Uses: Request (https://www.npmjs.com/package/request)
API: https://developers.google.com/custom-search/json-api/v1/introduction

User stories:
1. I can get the image URLs, alt text and page urls for a set of images relating to a given search string
2. I can paginate through the responses by adding a ?offset=2 parameter to the URL
3. I can get a list of the most recently submitted search strings

Demo: 
* https://cryptic-ridge-9197.herokuapp.com/api/imagesearch/lolcats%20funny?offset=10
* https://cryptic-ridge-9197.herokuapp.com/api/latest/imagesearch/

**Comment by QuincyLarson** [comment]
This is really well done! I think this is basically done! So it's basically just using the Google image search API?

It's probably not necessary to show the ID for the search queries - just showing what they were and when they occurred is probably plenty.

**Comment by george-stepanek** [comment]
@QuincyLarson Cool, thanks! I've updated to show just the relevant fields.
