### ISSUE TITLE
Email unsubscription 

### ISSUE THREAD

**Issue by bogem** [FreeCodeCamp/FreeCodeCamp#5142]
1. So, I can unsubscribe from e-mails by this link:  http://www.freecodecamp.com/unsubscribe/albertnigma@gmail.com
But **any** person can unsubscribe from e-mails **any** FreeCodeCamp user by providing another e-mail address in the end of this link. For example, http://www.freecodecamp.com/unsubscribe/sahat@me.com

2. Also, then I write wrong e-mail address in the end of this link (for example http://www.freecodecamp.com/unsubscribe/hui@sfbjfbdfknfjdnkfjsk.com), I get only this:
`Cannot GET /unsubscribed/hui@sfbjfbdfknfjdnkfjsk.com`

**Comment by BerkeleyTrue** [comment]
Vulnerability implies there can be damage done to users data or information leaked.

While it is true that anyone can be unsubscribed from emails, you would still need there email to do it which is information we do NOT give out. 

The most harm you could do is prevent someone from getting our emails. That endpoint doesn't do anything but set a flag on the user object.

Also, if a user is not found matching that email, then the user is simply redirected, so not sure where you are seeing that error message.

**Comment by bogem** [comment]
But most of FreeCodeComp users are your Github repository stargazers. So I can get their emails if there are public

Yes, I ain't right, that it is vulnerability, but I think the email unsubscription must be implemented another 
way

Hm. Now I don't get message `Cannot GET ...`, but see redirection. All is ok
