### ISSUE TITLE
propose to change image provider

### ISSUE THREAD

**Issue by ekremkaraca** [FreeCodeCamp/FreeCodeCamp#5143]
Hey guys,

Because of imgur being blocked in Turkey, we can't see images hosted in imgur. Do you have a chance to change image provider or host on your own server?  

Here's a sample:

![img](http://s23.postimg.org/p525rdw4r/Waypoint_Browse_Camper_News_Free_Code_Camp.jpg)

**Comment by ltegman** [comment]
I know there has been talk about moving away from imgur due to the possibility of them starting to enforce a ban on using imgur as a CDN. I don't know what the timeline on that is or what alternative provider is being looked at. Hopefully someone else can shed some light on that.

**Comment by BerkeleyTrue** [comment]
@ekremkaraca We are moving to AWS s3, albeit slowly.

**Comment by bugron** [comment]
cc @QuincyLarson

**Comment by QuincyLarson** [comment]
Our goal is to remove virtually all images from FCC with the forthcoming redesign, which will make it easy to move the remainder to S3
