### ISSUE TITLE
Polish the Code elements styles because it looks like a button

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#51447]
The code elements inside the challenge have the same border as the buttons, which cased confusion for me multiple time, as I expected something to happen when I clicked over them.

I think we should do one of these two:

- Polish the styles, so they don't look like buttons.
- ~Add functionality for when they are clicked, "copy code" or something alike~

**Comment by Sboonny** [comment]
There is a discussion of how they should look in this issue, it should provide more context and valid options https://github.com/freeCodeCamp/freeCodeCamp/issues/50034#issuecomment-1504008319

**Comment by moT01** [comment]
I think that, for the most part, we don't want the "copy code" type buttons. I believe we intentionally removed the copy/paste shortcuts, in the right-click menu of Monaco, to discourage copy/pasting.

Wondering how big of a problem this is - have we seen any other people mention issues about it?

**Comment by Sboonny** [comment]
> Wondering how big of a problem this is - have we seen any other people mention issues about it?

No idea, similar to the original issue, this is an enhancement that I am requesting, not an actual issue.

**Comment by ValkonX33** [comment]
can you tell how to recreate this issue

**Comment by Sboonny** [comment]
image of what I am talking about.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/9b73efd7-4a91-476f-8fc9-9fdcb545ad42)

**Comment by ValkonX33** [comment]
can i work on this?

**Comment by ValkonX33** [comment]
can you guide me how can i do this?

**Comment by SoumyaSubhrajit** [comment]
@Sboonny I think the selected text color is right in some way because it match the background , I think we need to focus on the btn part, we need to change the size or color to look different from the selected text, what's your opinion on this?

**Comment by Sboonny** [comment]
@ValkonX33, there is no plan decided yet, when a plan is decided, a PR can be opened to close this.

--- 

@SoumyaSubhrajit 

I do like the idea of changing the button style instead.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/4b7a893a-5a0d-4a77-b6ed-08eb838fd7a8)

but it will be too much work, there are places that will break because of the small difference in their styles, which should be accounted for, and it will need to be updated in ui-components too.

---

I would wait for other prolific contributors' feedback about this, because how big the change will be.

**Comment by SoumyaSubhrajit** [comment]
@Sboonny I agree with you because it will need changes in every component and maybe it cause an issue, or we can change the btn color and size in the main component that should render in all child components, what's your take on this?

**Comment by ShaunSHamilton** [comment]
@Sboonny I do not see this as a problem, because the button has a pointer and background change on hover. The text does not.

As these are bog-standard expectations with buttons, do you still expect something to happen when you click on the text?

If yes, why not change the border for the code text instead of changing the button (which we have had around for a lot longer than the text)

**Comment by Sboonny** [comment]
@SoumyaSubhrajit, unfortunately changing the button is hard and will be harder when I am done with swapping the [button](https://github.com/freeCodeCamp/freeCodeCamp/pull/51443) components, because it will need to account for specificity too.

We should come back to the button after the ui-component has moved to its own repo, most of the issues that the changes will face should be solved by then.

---

Let's focus on polishing the code element

**Comment by SoumyaSubhrajit** [comment]
@Sboonny okay got it any other specific area that needs to focus on?

**Comment by naomi-lgbt** [comment]
> Why not change the border for the code text

We could go with a dashed border

**Comment by KSSaiTeja** [comment]
I am interested to work on this issue. can i start working on this and raise a PR?

**Comment by KSSaiTeja** [comment]
ok. will wait until it's open for PR

**Comment by ShaunSHamilton** [comment]
Does anyone have examples of how other sites/platforms/resources write/display similar text?

**Comment by KSSaiTeja** [comment]
@ShaunSHamilton do you me post some example ideas or resources to take reference?

**Comment by ShaunSHamilton** [comment]
Yes. How do other sites style inline code? What is common?

**Comment by naomi-lgbt** [comment]
MDN just uses a different font (and slightly different background?)

<img width="600" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/4b2bbc7d-4d56-413e-ba0b-2981fe48d88d">

Google uses a different font and more distinct background

<img width="658" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/78e34130-ae51-4206-b2e5-c7582fff7261">

The border that we use is not a common approach, but we specifically added it to clarify spacing around strings.

**Comment by ShaunSHamilton** [comment]
We could border each space:
<img width="447" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/4aab4cc0-bd37-4d7a-b8d9-875c0d090e0f">

**Comment by naomi-lgbt** [comment]
I'm not sure I'm a fan of that, tbh.

**Comment by Sboonny** [comment]
the border wasn't added to solve a spacing but as enhancement that indicate the text inside the code element is one long string, with the different layout spacing cause by the slider.

the images are from [step 4 in rothko painting](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-4):
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/1334f5f2-9d19-4dea-ae2b-f006683b7031)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/36dcfe63-cd9a-45f8-9de0-b51ecf5edb08)

if removing a border is an option, we can go with the way tailwind did, by adding backtick ` before and after the code element.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/c0e97cf7-8a45-4ed7-8275-5f55e29e801f)

> We could go with a dashed border

We are using dashed boarder as indicator that a step isn't complete, I am worried that there will be misunderstanding that the code element isn't complete somehow.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/405d18f8-8ca6-4681-bc7c-10c4df88d72d)

**Comment by deanglukler** [comment]
Hi there, first time contributor.  I tried changing the text color and removing the border.


<img width="510" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/32249655/c1b9c3b1-8c28-4e32-8952-43a36a0e8fd5">


<img width="501" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/32249655/e502a04f-fd12-4365-8a18-2b7451c8cb0b">

**Comment by Asifdecoder** [comment]
can we contribute to it now?

**Comment by ahmaxed** [comment]
@deanglukler, the border does not need to be removed.
Find out where the background color and the border color is being applied and change them with the followings:
https://github.com/freeCodeCamp/freeCodeCamp/issues/51447#issuecomment-1789033518

@Asifdecoder, the issue is open for first time contributors. I will change the label if a pr is not submitted within a week or so.
