### ISSUE TITLE
Bf:Where do I belong, work around

### ISSUE THREAD

**Issue by kush-agra** [FreeCodeCamp/FreeCodeCamp#5144]
by my understanding,the code requires you to sort the array the array and then by using loop and if cases figure out where the number should be added and then return the index of that position.

but one can easily solve the bonfire by first adding the element then sorting it and then returning the index of that element , which makes it waay too easy as seen in my code below
```
function where(arr, num) {
  arr.push(num); //first push
  arr.sort(function(a,b){ //then sort
  return b < a;
    });
  n = arr.indexOf(num); //finally return index
  return n;
}

where([40, 60], 50);
```

**Comment by ltegman** [comment]
I don't personally have a problem with this. I see the point of the bonfires being less about implementation and more about thinking through how to solve a problem. Coming up with this solution using built-in methods shows a good thought process.

Leaving open for discussion. @FreeCodeCamp/issue-moderators and @BerkeleyTrue, do you see this as circumventing the spirit of the challenge?

**Comment by BerkeleyTrue** [comment]
@ltegman This is a question better answered by @SaintPeter 

Personally, this seems like it took thought to come up with. There are other bonfires that can now be solved with only one ES2015 method, and these we should test for.

**Comment by SaintPeter** [comment]
I believe this is an acceptable solution.  I've actually seen this quite a few times.  I don't think it's any better/worse than looping through and stopping when the number meets certain criteria.

In fact, this is one of two provided solutions on the Wiki:  
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Bonfire-Where-do-I-belong#code-solution-2

@ltegman is right - We care less about precisely how you got the solution than the fact that you got a solution.  With the exception of ES2015, "single function to solve it" solutions, we won't block any valid solution.

Thanks for your concern!  Usually we get people complaining that things are too hard.  :wink:
