### ISSUE TITLE
React Zipline: Markdown Preview App

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5147]
User Stories:

- I can type GitHub-flavored Markdown into a text area.
- I can see a preview of the output of my markdown that is updated as I type.

Demo: http://dillinger.io/

**Comment by Chris-Cates** [comment]
@QuincyLarson Working on this as per your request. :)

**Comment by BerkeleyTrue** [comment]
:+1: These are going to be fun :)

**Comment by QuincyLarson** [comment]
@Chris-Cates Thanks for tackling this progress. How is it coming along?

**Comment by QuincyLarson** [comment]
@Chris-Cates can you update us on your progress?

**Comment by ltegman** [comment]
I could be missing something but I was looking to mess around with this and I don't actually see a way to accomplish this with the gitter API. There's no way I can see to use their API to get a list of rooms for an Org without knowing the ID for the org and the only way to get that ID is by having the user associated with your OAuth token in that room.

Apologies if there's a way to do this that I'm not seeing.

**Comment by QuincyLarson** [comment]
Thanks for looking into this @ltegman. Hey @BerkeleyTrue, could you take a look and confirm whether this is the case? If so, we'd need to change the nature of this challenge. I was thinking about making a twitter hashtag viewer, but Twitter recently made it difficult to make a lot API calls.

**Comment by QuincyLarson** [comment]
Rather than worry about consuming an API, I think it makes sense to showcase React's data flow. I've updated the user stories and renamed this challenge accordingly.

**Comment by HermanFassett** [comment]
@QuincyLarson This is pretty much my first react project, so I relied on the react tutorial (namely [this part](https://facebook.github.io/react/docs/tutorial.html#adding-markdown)) and [this tutorial](http://voidcanvas.com/react-tutorial-two-way-data-binding/) probably too much, but here's a first try:
http://s.codepen.io/hermanfassett/debug/EPywYy
I will probably make Write and Preview tabs to make it easier to view, but for now this is what I have. Tell me what you think.

**Comment by SaintPeter** [comment]
@HermanFassett I did a quick test and that works really well.  Very slick!  Code looks good too.

**Comment by HermanFassett** [comment]
Thanks @SaintPeter so the data binding is fine as it is? And is it fine to get the markdown like that? It almost felt like cheating, all done for me... The only thing that doesn't really work is links but I think that's due to the nature of codepen.

**Comment by SaintPeter** [comment]
RE: Data Binding -
I have no idea, since I'm not remotely a React expert, but it did looks mostly correct to me, from the other React I've seen @terakilobyte write.  Maybe he can comment?

RE: using a library
I think that's totally the way to go.  I might go as far as to link the library in the Zipline description.  The challenge is the React portion, not the Markdown->HTML solution.  No one writes their own Markdown parser when they can just `npm install` or link to a CDN.

**Comment by QuincyLarson** [comment]
@HermanFassett this works amazingly! Great work!

**Comment by orvisevans** [comment]
I was looking to get a start on the curriculum during a break from work, so I worked through the React tutorial (http://facebook.github.io/react/docs/tutorial.html) and this zipline today.  It's a great starter challenge to get comfortable with react!  The tutorial and this challenge dovetail nicely.
Here's what I came up with: http://codepen.io/orvis/full/VeKoKw/
