### ISSUE TITLE
API Basejump: URL shortener

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5148]
User stories:

- I can pass a URL as a parameter and I will receive a shortened URL in the JSON response.
- If I pass an invalid URL that doesn't follow the valid http://www.example.com format, the JSON response will contain an error instead.
- When I visit that shortened URL, it will redirect me to my original link.

**Comment by george-stepanek** [comment]
Happy to do this one!

**Comment by QuincyLarson** [comment]
Hi @george-stepanek this is a good start, but I was hoping that instead of using an existing URL shortener (Google's), this would actually create a new record in the database with both a shortened URL and the full URL it corresponds to. And then if you tried to visit that short URL, it would forward to the full URL. 

Thus, if your domain was urlshortener.herokuapp.com, I could do urlshortener.herokuapp.com/http://google.com and it would return urlshortener.herokuapp.com/fdS542, and when I then went to urlshortener.herokuapp.com/fdS542, it would take me to google.com.

Could you implement this?

**Comment by HermanFassett** [comment]
How's this?
https://shurli.herokuapp.com/
Can create with:
https://shurli.herokuapp.com/new/https://www.google.com
or
https://shurli.herokuapp.com/new/www.google.com
I might need more to check if url is valid, otherwise might mess up code if someone creates a url of a short id

**Comment by george-stepanek** [comment]
@QuincyLarson Happy to make that change, but it looks like @HermanFassett is already onto it... :)

**Comment by HermanFassett** [comment]
Updated to check for `.` in url so short id's won't be posted. Also fixed error with not including queries. 
I'm also thinking of adding custom short urls. Do you think that could be a possible bonus user story?

**Comment by QuincyLarson** [comment]
@george-stepanek I agree - @HermanFassett's app looks like exactly what we need.
@HermanFassett Wow - this works great! Yes - I think it should ensure it's a valid URI first and return an error if it isn't. I'm adding that to the user stories above.

**Comment by QuincyLarson** [comment]
@HermanFassett I've updated the user stories. I see that your app already detects invalid URLs (though you might want to tighten up the regex it uses to check them a bit), so I will mark this issue as closed, and we will use your project as the example project for the Basejump. Great work here, to both you and @george-stepanek!

**Comment by Deftwun** [comment]
@HermanFassett  I'm getting a Heroku application error when I click the link. Problem with Procfile maybe??

**Comment by HermanFassett** [comment]
@Deftwun I'm not at home with a computer but I'll check into it when I get a chance, thanks for letting me know

**Comment by HermanFassett** [comment]
@Deftwun the logs weren't enlightening and restarting the app made it live again, but I'll keep my eye out for what could have caused that.
