### ISSUE TITLE
Permanent redirect in FCC express backend challenge

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#51483]
### Describe the Issue

When trying to submit the code for the env challenge, an error is reported by the editor.

`[Error: Unexpected token < in JSON at position 0]` 

Upon further analysis , the content it is trying to parse is `<a href="https://boilerplate-express.a2937.repl.co/json">Permanent Redirect</a>.`  The href being the Repl.it url. 

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file

### Your code

```js
app.get("/json", function(req, res) {

  var objectMessage = {
    "message": "Hello json"
  };

  if (process.env.MESSAGE_STYLE == "uppercase") {
    objectMessage.message = objectMessage.message.toUpperCase();
  }
  else {
    //Do nothing
  }
  res.json(objectMessage);
})
```

### Expected behavior

I expect to be able to submit the challenge correctly without any issues. 

### Screenshots

![Capture](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/1e99412e-38e3-466c-8a24-56a8f71c0dc2)

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 117.0 (64-bit) 

### Additional context

The issue is formally on [this repo](https://github.com/freeCodeCamp/fcc-express-bground-pkg) in index.js. I'm not quite sure how to resolve this though and would like a hint. I know it redirects with the `https` library, but how do I get to the resource route so things can proceed?

**Comment by ShaunSHamilton** [comment]
Thanks for taking the time to open this.

I am unable to reproduce any error with this challenge. Are you able to provide more information about your code? Maybe share your Replit code link.

**Comment by gikf** [comment]
I used the code from issue to pass the challenge without any troubles. It was on a fresh started replit from the boilerplate, with passed previous challenges in that section.

**Comment by a2937** [comment]
I guess I should have updated my node_modules. I'm going to close this issue then.
