### ISSUE TITLE
JS: Regular Expressions: Restrict Possible Usernames: А bit wrong regular expression passed the tests

### ISSUE THREAD

**Issue by dmitrykurmanov** [freeCodeCamp/freeCodeCamp#51498]
### Describe the Issue

I think that I could pass all the challenge tests with a little bit of wrong regular expression.

If I understand everything correctly the name **A1111111** is correct by challenge's conditions. Meanwhile, I completed the challenge with the regular expression that doesn't respect this *username*.

So I propose to add a new test to check that the regex should match the string **A1111111**.

_But I am not sure we need to do it because to be fair this challenge is already very tricky enough ._

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

### Your code

```js
let username = "JackOfAllTrades";
let userCheck = /^[a-z][a-z]+\d*$|^[a-z]\d\d$/ig; // this regexp passed all tests
let result = userCheck.test(username);

username = "a1111111"; // but this is also valid name
userCheck = /^[a-z][a-z]+\d*$|^[a-z]\d\d*\d$/ig; // I added \d* to respect new username;

// Could we add a new test to check "a1111111" match?
```

### Expected behavior

We tested to check the regex should match the string **A1111111*.

### System

- OS: Windows 10
- Browser: Chrome (latest)

### Additional context
Here is my profile https://www.freecodecamp.org/fcc3b9f4f93-981a-4ffe-b8a4-3203871cd8c7 if it could help.

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you for taking the time to open this.

As you correctly pointed out, the issue is in the way we test this portion of the regex: `^[a-z]\d\d$`

The issue is we need to test for so many different variations of this that should match. That is:

> We tested to check the regex should match the string *A1111111.

We could add a test like that, but this **invalid** regex passes:

```javascript
let userCheck = /^[a-z][a-z]+\d*$|^[a-z]\d\d\d?\d?\d?\d?\d?$/ig;
```

Obviously, that is a bit extreme. However, it does prove the point that without directly testing the trillions of correct permutations, an invalid solution will pass.

---

I will leave this open for discussion in the case someone can think of a decent way to test this.

**Comment by dmitrykurmanov** [comment]
> I will leave this open for discussion in the case someone can think of a decent way to test this.

please feel free to decline my offer. This is just an educational task, so it probably shouldn't be too difficult...

**Comment by Vijaykv5** [comment]
I would love to work on this issue...May you can assign me

**Comment by ShaunSHamilton** [comment]
@SoumyaSubhrajit The issue is how to mention in the test text what is being tested. Look at the other test texts - they are all specific about the input.

**Comment by dmitrykurmanov** [comment]
> I will leave this open for discussion in case someone can think of a decent way to test this.

I think it could be tested via the `Math.random` but it could be confusing for campers to see a bit different test conditions.

Probably, it would be okay to add one more concrete condition to the challenge ("names with any numbers at the end should pass the test"), and to check it just add a test with random from 50 to 100 digits at the end. I think it will be ok.

But I am still not sure that doing this challenge more complex makes sense because it is already hard
