### ISSUE TITLE
C# Certification Control variable scope lesson question issue

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#51497]
### Describe the Issue

The "Control Variable Scope and Logic Using Code Blocks in C#" in the "Add Logic to C# Console Applications" has an question that doesn't really feel quite right for this section. The question is "Which of the following describes the affect of a `using` statement?". The thing is `using` statements aren't covered in the foundational MS Learn Path. It'd be a little unfair to new learners to answer this question with the given material.

### Affected Page

https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/add-logic-to-c-sharp-console-applications/control-variable-scope-and-logic-using-code-blocks-in-c-sharp

### Your code

N/A

### Expected behavior

When answering questions on the FreeCodeCamp foundational certification path, prior C# knowledge should not be required to answer questions. 

A question like the following might be better suited for this particular lesson. 

What is the scope of a local variable declared inside a method in C#?

a) It's accessible only within the method where it's declared.
b) It can be accessed from any method within the same class.
c) It's accessible globally from any part of the program.
d) It's only visible within the same class, but different methods can't access it.

### System

- Device: Desktop
- OS: Windows 10
- Browser: FireFox
- Version: 117 

### Additional context

I only checked out this certification path for practice reasons.

**Comment by GaryBleasdale** [comment]
I came across the same issue.  I had to read up on the using statement using different resources in order to answer the question and be able to continue my learning path.

**Comment by AndyTBurke** [comment]
I've created a pull request to fix this issue. Since all the other questions are taken from the "Knowledge Check" portion of related tutorial, I just used the first question found here: https://learn.microsoft.com/en-us/training/modules/csharp-code-blocks/6-knowledge-check
