### ISSUE TITLE
React Zipline: Conway's game of life

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5149]
I can play Conway's game of life.

Demo (doesn't yet use React/SASS): http://codepen.io/Cheezily/full/pjmEzQ

User stories:
- When I first arrive at the game, it will randomly generate a board and start playing
- I can start and stop the board
- I can set up the board
- I can clear the board
- When I press start, the game will play out.
- Each time the board changes, I can see how many generations have gone by

**Comment by QuincyLarson** [comment]
We have a demo! http://codepen.io/rasheinstein/full/QyjxGG/ - thanks @rasheinstein!

**Comment by Cheezily** [comment]
Here's the demo of the one FCC asked me to redo in React:

http://codepen.io/Cheezily/pen/RrrbXW

**Comment by QuincyLarson** [comment]
Great work! I'm closing this one.
