### ISSUE TITLE
Changing the text in the share button in FreeCodeCamp News 

### ISSUE THREAD

**Issue by CBID2** [freeCodeCamp/freeCodeCamp#51505]
### Describe the Issue

Content that is posted on X (Twitter) goes by posts instead of tweets, so I think it would be best for the button to say "Post a thanks" instead of "Tweet a thanks" to avoid confusion.  

### Affected Page

https://www.freecodecamp.org/news/basic-html5-template-boilerplate-code-example/

### Steps to Reproduce

1. Go to Freecode Camp News
2. Pick an article
3. Scroll down to the bottom
4. Click on the "Tweet a Thanks button"

### Expected behavior

The button should say "Share a Post" instead. 

### Screenshots

<img width="789" alt="current button name" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/105683440/a2891761-f7b7-4d0b-9ef1-2f29bde49aba">

### System

- Device: Mac
- OS: iOS 24
- Browser:  Chrome
- Version: 22

**Comment by naomi-lgbt** [comment]
I would change the text to `If you read this far, say thanks to the author to show them you care.`, and then the button `Say Thanks`.

`Tweet` was an iconic word that was tightly coupled to the Twitter brand. If you click a "tweet" button, you know you're going to Twitter.

"Share a Post" is ambiguous and could refer to pretty much any social platform.

**Comment by CBID2** [comment]
> I would change the text to `If you read this far, say thanks to the author to show them you care.`, and then the button `Say Thanks`.
> 
> `Tweet` was an iconic word that was tightly coupled to the Twitter brand. If you click a "tweet" button, you know you're going to Twitter.
> 
> "Share a Post" is ambiguous and could refer to pretty much any social platform.

Good point @naomi-lgbt! I came up with post because that’s what they’re called now but the text you came up with makes more sense! 😊

**Comment by ParthasarathiMahana** [comment]
Hi, can I start working on it? @ShaunSHamilton @CBID2 @naomi-lgbt

**Comment by CBID2** [comment]
> Hi, can I start working on it? @ShaunSHamilton @CBID2 @naomi-lgbt 

Hi @ParthasarathiMahana! I'm going to work on this issue.

**Comment by ParthasarathiMahana** [comment]
Ok no problem, @CBID2 thank you.

**Comment by ParthasarathiMahana** [comment]
can you help me set up the project on my local machine I am getting some error while setting it up?? @CBID2

**Comment by ParthasarathiMahana** [comment]
when I tried running "pnpm run seed" the error I got was "sh: 1: npm-run-all: not found
 ELIFECYCLE  Command failed."

**Comment by CBID2** [comment]
> can you help me set up the project on my local machine I am getting some error while setting it up?? @CBID2 

I'm still pretty new to the codebase, so the best advice I can give you @ParthasarathiMahana is to reread [the Contributing Guide](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally). If it's too much, then use Gitpod.

**Comment by ParthasarathiMahana** [comment]
> > can you help me set up the project on my local machine I am getting some error while setting it up?? @CBID2
> 
> I'm still pretty new to the codebase, so the best advice I can give you @ParthasarathiMahana is to reread [the Contributing Guide](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally). If it's too much, then use Gitpod.

Thanks @CBID2 , I am using gitpod

**Comment by SoumyaSubhrajit** [comment]
@ParthasarathiMahana it Indicates that you failed during the installation process and it needs to change while you install all the dependencies change` npm install` to `pnpm install` and then follow the next procedure

> when I tried running "pnpm run seed" the error I got was "sh: 1: npm-run-all: not found  ELIFECYCLE  Command failed."

**Comment by ParthasarathiMahana** [comment]
> @ParthasarathiMahana it Indicates that you failed during the installation process and it needs to change while you install all the dependencies change` npm install` to `pnpm install` and then follow the next procedure
> 
> > when I tried running "pnpm run seed" the error I got was "sh: 1: npm-run-all: not found  ELIFECYCLE  Command failed."
> 
> 

@SoumyaSubhrajit Thanks alot for your help.

**Comment by mahe1999mh** [comment]
Hi @ParthasarathiMahana  can I start working on it?

**Comment by CBID2** [comment]
> Hi @ParthasarathiMahana can I start working on it?

Hi @mahe1999mh. I expressed interest in solving this issue. If you'd like, you can review my PR once I get the approval from the maintainers :)

**Comment by KSSaiTeja** [comment]
I think i will fix this in less than 5 min. could you please allow me to work on this issue?

**Comment by CBID2** [comment]
> I think i will fix this in less than 5 min. could you please allow me to work on this issue?

Hi @KSSaiTeja. This issue has not been approved yet and I also expressed interest in working on it.

**Comment by KSSaiTeja** [comment]
I am interested to work on this issue. i will fix it in less than. 5 minutes. @CBID2 please give me a chance to raise a PR for me. As a beginner it would help me a lot.

Hope you will give a chance to me.

**Comment by Tanush-J** [comment]
I don't think we can edit the news template because I can't find the template in the codebase. I think the whole article is fetched from a server in an HTML file.

**Comment by CBID2** [comment]
> I don't think we can edit the news template because I can't find the template in the codebase. I think the whole article is fetched from a server in an HTML file.

I had the same issue as well @Tanush-J

**Comment by naomi-lgbt** [comment]
The file can be found in our [news repository](https://github.com/freeCodeCamp/news/blob/86f13f512dbb62ae849e4bfa3ac90d70b99470a4/config/i18n/locales/english/translations.json#L37), however due to the way the CI needs to run, pull requests from forks aren't able to be accepted.

**Comment by CBID2** [comment]
> The file can be found in our [news repository](https://github.com/freeCodeCamp/news/blob/86f13f512dbb62ae849e4bfa3ac90d70b99470a4/config/i18n/locales/english/translations.json#L37), however due to the way the CI needs to run, pull requests from forks aren't able to be accepted.

I see @naomi-lgbt. So how can this be solved?
