### ISSUE TITLE
React Zipline 5: Rogue-like Game

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5151]
- I have health, a level, and a weapon. I can pick up a better weapon. I can pick up health items.
- I start in the center of a map. All the items and enemies on the map are arranged at random.
- I can move anywhere within the map's boundaries , but I can't move through an enemy until I've beaten it.
- I can move throughout a map, discovering items.
- Much of the map is hidden. When I take a step, all spaces that are within one space of me are revealed.
- When I beat an enemy, the enemy goes away and I get XP, which eventually increases my level.
- When I fight an enemy, we take turns damaging each other until one of us loses. I do damage is based off of my level and my weapon. The enemy does damage based off of its level. Damage is somewhat random within a range.
- When I find and beat the boss, I win.
- The game should be challenging, but theoretically winnable.

**Comment by george-stepanek** [comment]
You've used the word "rouge" rather than "rogue"... does this mean it should be gender-swapped? ;)

**Comment by BerkeleyTrue** [comment]
hehe, good catch. :+1: 

Fixed

**Comment by QuincyLarson** [comment]
Here's an example Roguelike game (the demo can be much simpler than this): http://www.desktopdungeons.net/HTML5/

**Comment by rasheinstein** [comment]
Good challenge. I'll try come up with something in the coming days

**Comment by QuincyLarson** [comment]
@rasheinstein Great! This is a big challenge (the final React challenge) and if you can't do it, someone else will need to start working on it, so please update us every day on your progress.

**Comment by rasheinstein** [comment]
This is as far as I have gone. I can easily modify the code to change the size and number of cells. and I can navigate using the arrow keys. Also, I can easily change the background image if I want. I'd keep adding more features as time goes on

**Comment by rasheinstein** [comment]
http://codepen.io/rasheinstein/full/dGGxbp

**Comment by ltegman** [comment]
It needs some UI love (which are upcoming in the next couple days) and I'm gonna refactor the code, but I believe [this codepen](http://codepen.io/ltegman/full/obLXKQ/) will hit all the user stories.

- [x] _I have health, a level, and a weapon. I can pick up a better weapon. I can pick up health items._
  + Orange tiles are weapon upgrades, green tiles are health pickups
- [x] _I start in the center of a map. All the items and enemies on the map are arranged at random._
  + You start in a random area of the map, hopefully that's alright. The map is procedurally generated so there is the "center" is not predictable. Items and enemies are randomly placed.
- [x] _I can move anywhere within the map's boundaries , but I can't move through an enemy until I've beaten it._
- [x] _I can move throughout a map, discovering items._
- [x] _Much of the map is hidden. When I take a step, all spaces that are within one space of me are revealed._
  + The line of sight is 7 spaces. The map I make it so large that only 1 space of view is pretty brutal.
- [x] _When I beat an enemy, the enemy goes away and I get XP, which eventually increases my level._
- [x] _When I fight an enemy, we take turns damaging each other until one of us loses. I do damage is based off of my level and my weapon. The enemy does damage based off of its level. Damage is somewhat random within a range._
  + Currently there's no animation to indicate this is happening (part of the UI tweaks I need) but every time you try to "move" into an enemy you attack it and if your attack is not strong enough to kill the enemy you will get attacked back.
- [x] _When I find and beat the boss, I win._
  + This occasionally seems glitchy, but there is a boss. Looking into glitches tomorrow.
- [x] _The game should be challenging, but theoretically winnable._
  + The boss is way too easy right now. Will tweak.

**Comment by SaintPeter** [comment]
@ltegman Any way you could leave "seen" walls a grey color or something?  I find it very hard to "navigate" without being able to see the walls.  I think that's a typical feature in rogue-likes.  I'd like to add it as a user story, if only to make it more playable.

**Comment by ltegman** [comment]
@SaintPeter That wouldn't be a problem. I think first I'll implement a button to toggle the darkness, in part because it's easier and partly because it would use a much more traditional React data-flow than my current implementation of keypress controls does. Then after that I can work on adding some memory of what you've seen so it's slightly less frustrating.

**Comment by QuincyLarson** [comment]
@ltegman This looks great. One thing I noticed is if I die, the game just stops responding. Is it possible for there to be some indication that I've died and maybe an option to restart the game?
This looks amazing and props for all your hard work on this! It's almost ready to go. I'll start recording videos tomorrow (though I can do this last).

**Comment by ltegman** [comment]
I'll look into it -- it's supposed to restart the game automatically after the player dies, but it's possible there's a bug with it. I'll do a cleanup pass and look into that the boss fight tonight to make sure that both the death and win conditions are working correctly. I'm also hoping to get optional wall memory going like @SaintPeter suggested. Will let you know when I'm done with that but it will be either tonight or tomorrow sometime.

**Comment by ltegman** [comment]
Win/lose condition bugs are fixed. Toasts now let the user know if either one of those things happened as well. Optional amenities like mobile swipe controls and wall memory are hopefully coming tomorrow! :)

**Comment by QuincyLarson** [comment]
Per our discussion in Gitter, excellent work, @ltegman!
