### ISSUE TITLE
React Zipline: Recipe Box

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5152]
User Stories:
- I can create recipes that have names and ingredients
- I can see an index view where the names of all the recipes are visible
- I can click into any of those recipes to view it
- I can edit these recipes
- I can delete these recipes
- Everything is stored in my browser's local storage

Demo: http://codepen.io/GeoffStorbeck/full/bVKyzd/

**Comment by techstonia** [comment]
Does this need to be ported to React? I could do it if needed.

**Comment by QuincyLarson** [comment]
@techstonia Yes - we just need an implementation that makes use of React and Sass. If you could help with this port, that would be really helpful!

**Comment by HermanFassett** [comment]
@QuincyLarson is this good enough? http://codepen.io/hermanfassett/full/bEeabr/

**Comment by SaintPeter** [comment]
Some thoughts:
1) I should be able to click anywhere on the "bar" to open the recipe, not just on the name/title.
2) What about a "quantity" field?  Most recipes have an ingredient and an amount
3) Do we also want to have a "description" or "Instructions" field?  Like "Bake at 650 for XX time"?  While it does add some complexity, I think it's interesting complexity.

Looking at the code, to my naive eyes it looks solid.  Kinda blows me away how simple something like this is in React.

**Comment by HermanFassett** [comment]
Ok @SaintPeter tested a little bit of adding that in a fork, but will take time. Descriptions shouldn't be hard, but I'll have to change how ingredients are added. I was just following @QuincyLarson 's user stories... Or looking again at the demo without react, maybe it would be best just to have one large ingredient directions textarea? 
As far as the bar clicking goes I'll see what I can do, though I'm using the default collapsible panels from react-bootstrap

**Comment by QuincyLarson** [comment]
@HermanFassett Thanks - I just saw this.

I agree with @SaintPeter's feedback, but I think it looks fine as is. Campers can add those additional touches for personalization later.

**Comment by darkom05** [comment]
Just a ques...why are you using a global update() + a global object? Isn't this anti-pattern?

**Comment by HermanFassett** [comment]
@darkom05 to be completely honest with you, I was very new to React when I made this and probably did it in a very hacky way... I haven't looked back since. It very well could be :smile:

**Comment by SaintPeter** [comment]
@darkom05 SSSHHH!! You're not supposed to look at the code.  ;)
