### ISSUE TITLE
API Basejump: Filesize Checker

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5153]
Use stories:
- I can submit a FormData object that includes a file upload
- When I submit something, I will receive the file size in bytes within the JSON response

**Comment by george-stepanek** [comment]
How about an image upload microservice that returns (say) the size of the uploaded file? It'll people a chance to work with binary POST data....

**Comment by QuincyLarson** [comment]
This is a really cool idea. Could it also detect the type of file, or any other metadata?

Also, is it possible to post to this rather than clicking a button in the web view and uploading? It would be ideal if all functionality could involve restful API calls.

**Comment by george-stepanek** [comment]
@QuincyLarson Yep, the web page is just simple a demo/test harness which posts to https://cryptic-ridge-9197.herokuapp.com//api/fileanalyse/ . (I'll update the page to say that.)

The data we get is, for example:
```
{ fieldname: '0',
  originalname: 'WM.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  destination: './uploads',
  filename: 'f148b758c5e00fd5466109a0cf5eb059',
  path: 'uploads/f148b758c5e00fd5466109a0cf5eb059',
  size: 72336 }
```

**Comment by QuincyLarson** [comment]
Hi @george-stepanek this may sound like a silly question, but is there a way to pass the file as an argument - or perhaps a link to a file on the internet? Because ideally we don't want any sort of UI on these API challenges - just an endpoint that returns JSON.

**Comment by george-stepanek** [comment]
Hi, @QuincyLarson, if we're limited to URLs that can be put into an address bar, then that means we can only do GET APIs, not POST. The intent of this one is to get familiar with handling form submission for POST APIs, which kind-of requires the developer to create some kind of form as a test framework.

Or they could use something like this: https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en ...
