### ISSUE TITLE
API Basejump: Request Header Parser

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5154]
User stories: 
- I can get the IP address, language and operating system for my browser.

Demo: https://cryptic-ridge-9197.herokuapp.com/api/whoami/

**Comment by george-stepanek** [comment]
How about something that gives the campers a bit of familiarity with HTTP headers, for example:

User stories: As a user I can get the IP address, operating system info and language for my browser.
Demo: https://cryptic-ridge-9197.herokuapp.com/api/whoami/

**Comment by QuincyLarson** [comment]
Hi @george-stepanek That's a great idea! You're doing this on the server side? Are there any other headers we should include in this?

**Comment by george-stepanek** [comment]
I tried to pick out the 'interesting' headers, but I can certainly add more if you want. The raw data we get is, for example:
```
{ host: 'fcc-api-basejumps-stepang.c9users.io',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36',
  dnt: '1',
  'accept-encoding': 'gzip, deflate, sdch',
  'accept-language': 'en-GB,en-US;q=0.8,en;q=0.6',
  cookie: 'connect.sid=s%3AZ0r3pQbyexcH90etkYTHYMc8idW5Y3d9.Jod3MCFmMEXymRRFnbR5%2Fg0g9cGUKv2K9NGjnKgwJGk',
  'if-none-match': 'W/"53-yT5W4ocH9UNAxGlG0kbmSA"',
  'x-forwarded-proto': 'https',
  'x-forwarded-port': '443',
  'x-region': 'ae',
  'x-forwarded-for': '121.98.92.63',
  connection: 'keep-alive' }
```
