### ISSUE TITLE
Fix Typo in CSS Flexbox Project Step 21

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#51555]
### Describe the Issue

In [Step 21](https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-21), we have a typo here

<img width="537" alt="Screenshot 2023-09-14 at 11 52 32 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/4c3ed6e1-bde4-44ff-84ac-d52e21662839">

The correction should be `also known as`. NOT `also knowns as`

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-flexbox-by-building-a-photo-gallery/step-21

## Current Directions with Typo

Your images need some space between them.

The `gap` CSS shorthand property sets the gaps, also knowns as gutters, between rows and columns. The `gap` property and its `row-gap` and `column-gap` sub-properties provide this functionality for flex, grid, and multi-column layout. You apply the property to the container element.

Give your `.gallery` flex container a `gap` property with `16px` as the value.

## New directions with typo fixed

Your images need some space between them.

The `gap` CSS shorthand property sets the gaps, also known as gutters, between rows and columns. The `gap` property and its `row-gap` and `column-gap` sub-properties provide this functionality for flex, grid, and multi-column layout. You apply the property to the container element.

Give your `.gallery` flex container a `gap` property with `16px` as the value.

## How to Contribute 

Here is the file you will need to update

https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/main/curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/6153a04847abee57a3a406ac.md

This will be open to `first time` contributors only

Please read through the [contributing docs](https://contribute.freecodecamp.org/#/index) before working on this issue
Any issue marked with `help wanted` or `first timers only` label does not need assignment, and is free to work on.

The maintainers will prioritize pull requests for those who follow the directions of the contributing docs and properly fill out the pull request template.

If you need any help, please reach out on the freeCodeCamp [forum](https://forum.freecodecamp.org/) or [discord](https://discord.com/invite/KVUmVXA)

Happy Contributing 💯

**Comment by dotmantosh** [comment]
You must have a great eye for English before you can see that typo. That's good tho.
