### ISSUE TITLE
API Basejump: Timestamp microservice

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5155]
User stories:
1) I can pass a string as a parameter, and it will check to see whether that string contains either a unix timestamp or a natural language date (example: January 1, 2016)
2) If it does, it returns both the Unix timestamp and the natural language form of that date.
3) If it does not contain a date or Unix timestamp, it returns null for those properties.

**Comment by awesomeaniruddh** [comment]
I wouldn't mind doing this one :)

**Comment by HermanFassett** [comment]
I don't want to jump ahead of @awesomeaniruddh here, but I saw this and decided I'd try it out.
Here's the baseurl: https://timestamp-hermanfassett.c9users.io/
API usage like: https://timestamp-hermanfassett.c9users.io/:timestamp
Example: https://jsfiddle.net/5nuL6fr6/4/
I can change things if it's not what is needed. I think maybe my parameter checking isn't definite enough as it accepts date types beyond unix or natural language date.

**Comment by QuincyLarson** [comment]
@HermanFassett Wow - great work! This is exactly how I envisioned it!

@awesomeaniruddh thanks for offering, but I think this is finished.

**Comment by HermanFassett** [comment]
I ported it over to Heroku here: https://timestamp-ms.herokuapp.com/
