### ISSUE TITLE
Warn about Glitch incompatibility with metric-imperial converter project

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#51569]
### Describe the Issue

We see this every so often and it might warrant a note. See the examples for more context.

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter

### Your code

```



```

### Expected behavior

Warn the user so they do not waste time debugging something that is out of their control.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Examples:
https://forum.freecodecamp.org/t/metric-imperial-converter-on-glitch/455434
https://forum.freecodecamp.org/search?q=Glitch%20Metric-Imperial%20Converter

**Comment by ShaunSHamilton** [comment]
Thanks for opening this. I forgot this was still a thing.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

**To Close This Issue**

- Change this file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/metric-imperial-converter.md
- Add the following to the **description**:

```markdown
**Note:** This project's tests do not work when using `glitch.com`.
```

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by KSSaiTeja** [comment]
should i add `**Note:** This project's tests do not work when using `glitch.com`.` and raise a PR regarding this, or else anything else have to be done.

As i am beginner a help from @ShaunSHamilton will be more motivational to me and happy if this is the only change and getting a chance to merge my PR.

Hope you will give a reply for this..

**Comment by KSSaiTeja** [comment]
@ShaunSHamilton I have raised PR. Regarding this issue.. Please review my PR.
