### ISSUE TITLE
Text refering to keyboard layout in javascript OR operator is not true for UK keyboards. 

### ISSUE THREAD

**Issue by eleven-scribe** [freeCodeCamp/freeCodeCamp#51587]
### Describe the Issue

Would add clarity for brits if this was included. (I know the UK keyboard may be used less globally than the American layout, but its a small tweak that could be added. Hope it's okay to suggest it).

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-or-operator

Text states: "The logical or operator is composed of two pipe symbols: (||). This can typically be found between your Backspace and Enter keys." 

Could add something like: "On a UK keyboard this symbol is found in the bottom left corner, under 'a' and to the left of 'z'."

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-or-operator

### Your code

```



```
Text states: "The logical or operator is composed of two pipe symbols: (||). This can typically be found between your Backspace and Enter keys." 

### Expected behavior

Could add something like:  "On a UK keyboard this symbol is found in the bottom left corner, under 'a' and to the left of 'z'. "

### System

- Device:  Laptop]
- OS: Windows 10,
- Browser: vivaldi
- Version:

**Comment by naomi-lgbt** [comment]
I worry that this would become a slippery slope to cover all the "common" keyboard layouts. I think the use of the word `typically` in the existing text is sufficient.

**Comment by DylanDevelops** [comment]
I agree that this change is not necessary. Saying `typically` covers the most common but lets people know that it isn't always found there.

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

I agree with the others; we cannot start mentioning specific keyboard layouts. The current verbiage is there to help as much as reasonable for _many_ to find the `|` key.

As such, I am going to close this.
