### ISSUE TITLE
Typo error in an article about HTML tables by Hillary Nyakundi

### ISSUE THREAD

**Issue by nandhakumar-ss** [freeCodeCamp/freeCodeCamp#51588]
### Describe the Issue

https://www.freecodecamp.org/news/html-tables-table-tutorial-with-css-example-code/

This is the article i found the typo error.

In this article, under the title **How to Style HTML Tables using CSS** there is a typo.
Under this heading in the article, in the second paragraph there is a line -> Afterall you wouldn't want your reader to stare at data divided by only a sinle line. 
Here see the last two words it says sinle line which doesn't makes sense. the correct word is single line.

This is the issue I found. I looking forward that the error will be resolved soon.

update me after the error is resolved

### Affected Page

https://www.freecodecamp.org/news/html-tables-table-tutorial-with-css-example-code/

### Steps to Reproduce

there is a typo error in a single word.
In this article, under the title **How to Style HTML Tables using CSS** there is a typo.
Under this heading in the article, in the second paragraph there is a line -> Afterall you wouldn't want your reader to stare at data divided by only a sinle line. 
Here see the last two words it says sinle line which doesn't makes sense. the correct word is single line.

### Recommended fix or suggestions

its a small typo error in a word so the owners can just change the typo error.

In this article, under the title **How to Style HTML Tables using CSS** there is a typo.
Under this heading in the article, in the second paragraph there is a line -> Afterall you wouldn't want your reader to stare at data divided by only a sinle line. 
Here see the last two words it says sinle line which doesn't makes sense. the correct word is single line.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/144907462/6dd45f84-c8b2-4b68-be93-e652b5bc425d)

**Comment by SWAMIADITYA** [comment]
i would like to solve error please assign me

**Comment by sanketshevare** [comment]
Can i work on this issue?

**Comment by jdwilkin4** [comment]
Hi @sanketshevare and @SWAMIADITYA !

Issues marked with the `help wanted` and `good first issue` are available for contribution.

This issue is not marked with that label and not available for contribution.

Please read through the [contributing](https://contribute.freecodecamp.org/#/) docs to learn more about how to contribute to freeCodeCamp

**Comment by jdwilkin4** [comment]
Hey @nandhakumar-ss !

Thank you for spotting this issue.
I will go ahead and message the editorial team so they can resolve this issue.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this issue, @nandhakumar-ss.

I just checked the article in our CMS and it seems like someone on our editorial team fixed this typo. The correction should go live within the next few hours.

Thanks again, and please let us know if you notice any other issues in this or other articles.
