### ISSUE TITLE
D3 Zipline: Visualize Economic Data with a Bar Chart

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5159]
User stories: 

1. I can see US Gross Domestic Product by quarter, over time.
2. I can mouse over a bar and see a tooltip with the GDP amount and exact year and month that bar represents.

demo: http://codepen.io/MutantSpore/full/pgyrwB/

**Comment by mutantspore** [comment]
Hi :) after @AdventureBear  invited me to also work on this project I have done a variety of things which I feel improve the look, functionality and access to the data required.

Such as:
- Generally tidied up font sizes and positioning of elements to give  a more "pleasing" result.
- changed the mouse over sending the text to a box at the top left and made it use a tool tip instead. The data displayed in that has also be simplified and styled. I used a tooltip as it 's more common, and the data is in view all the time without trying to move the mouse and also look back up at the top to see the data.
- A small repeating image is used for the background but that could be removed as the background color I have chosen works well too.
- the anonymous use of the API used has a DAILY limit of 50 calls. To get this done I actually personally signed up for a key to allows 2000 per hour. I then got the data and saved it as a json file on my personal web server. I have it also dumping to console in the code or you can grab it from my site to host it on FCC servers:

http://2am.ninja/json/gdp.json

That should solve key/rate issues

- Here is my fork of @AdventureBear 's original project

http://codepen.io/MutantSpore/full/pgyrwB/

I have tried to make it look professional but not complicated.

Hope you like it
Bruce

**Comment by mutantspore** [comment]
Ok I just read the user stories. Sorry, I was looking at examples from the World Bank etc and the just give the year but as I see the data is in financial quarters, I could show the date as month - year if you like. I personally think anything more is not useful. Though it could be written Q2 - 1978 also.

let me know.
Bruce

**Comment by mutantspore** [comment]
I can understand that an info box may be slightly easier to do, not much though as you have to still do mouse overs/leave etc . It's harder to use though, especially with the short columns on the left and you have to keep looking back and forth.

**Comment by mutantspore** [comment]
Ok again.. lol
Well I just implemented Month - Year
for example:

September - 1986

**Comment by QuincyLarson** [comment]
Hi @mutantspore first of all, great work! This looks awesome, and builds nicely on the work that @adventurebear has already accomplished.

I am not married to the idea of an info box - these could just as easily be tooltips. Are tooltips easier to do in D3? If so, I think we should change the user story.

**Comment by QuincyLarson** [comment]
Regarding the dataset, this doesn't change very often. We can host the JSON file on our servers.

**Comment by mutantspore** [comment]
added the commas for the dollar values in the tootip

**Comment by moigithub** [comment]
hello... found a small bug on code.. tooltip

`"from_date":` "1947-01-01",
...
  "data": [
    [
      "1947-01-01",
      243.1
    ],`
when u mouseover on the first bar (left side) it says "December 1946"
and according to the data... doesnt match
had same bug on my code.. 
..u probably doing `new Date(  "1947-01-01" )` which give "Dec 1946" (didnt saw ur code, but that was what i did)
solution is adding the time on the Date creation
`new Date(  "1947-01-01 00:00:00" )`

**Comment by mutantspore** [comment]
Yes, I saw that a while ago and corrected my version but I haven't done anything about updating the FCC fork or my pen. I'll look into it.

Sent from my iPhone

On Mar 4, 2016, at 7:24 PM, Mois?s Man <notifications@github.com<mailto:notifications@github.com>> wrote:


hello... found a small bug on code.. tooltip

"from_date": "1947-01-01",
...
"data": [
[
"1947-01-01",
243.1
],
when u mouseover on the first bar (left side) it says "December 1946"
and according to the data... doesnt match
had same bug on my code..
..u probably doingnew Date( "1947-01-01" )which give "Dec 1946" (didnt saw ur code, but that was what i did)
solution is adding the time on the Date creation
new Date( "1947-01-01 00:00:00" )`

-

**Comment by mutantspore** [comment]
I realized awhile ago that the date calculation was off in this project and fixed my personal version on Codepen but I didn't do anything about the FCC fork of it. I don't actually think I personally can, so here is my corrected Pen if someone can do something about it. 

http://codepen.io/MutantSpore/full/pgyrwB/
