### ISSUE TITLE
Basic Node and Express - Serve Static Assets - Pass when serving root folder

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#51590]
### Describe the Issue

Challenge can be passed with solution that will serve files from the root folder, not just `/public` directory. Ref https://github.com/freeCodeCamp/boilerplate-express/pull/140.

By using `__dirname` as a path serving static assets, and not giving explicit path to the `app.use()`, the static assets will be served from `__dirname` (root folder in this case) at the `/` (root) path. Since `/public` folder is then served where it is expected to be served, this fulfills test requirements:
https://github.com/freeCodeCamp/freeCodeCamp/blob/dfffaed393496a96543bf0409105ff0b8981e9be/curriculum/challenges/english/05-back-end-development-and-apis/basic-node-and-express/serve-static-assets.md?plain=1#L24-L42

However, using _just_ `__dirname` serves also other files and directories, starting from the root folder. Ie. `/myApp.js` or `/server.js`.

---

Reasonable solution seems to be adding test that will check if one of the files from root folder (ie. `/server.js` are not served as static assets.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/serve-static-assets

### Your code

To reproduce:
1. Use replit starter from https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/meet-the-node-console
2. Add to myApp.js, below line `2`:
```javascript
viewPath = __dirname + '/views/index.html';
const publicPath = __dirname;

app.use(express.static(publicPath));

app.get('/', function (req, res) {
    res.sendFile(viewPath);
})
```
3. Run replit
4. Test on https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/serve-static-assets passes
5. `{replit live address}/public/style.css` works, so is `{replit live address}/myApp.js` or `{replit live address}/server.js`.

### Expected behavior

Files outside of `/public` folder should not be served as static assets. Otherwise the test should fail.

### System

-

**Comment by ShaunSHamilton** [comment]
@gikf Thanks for opening this.

> Reasonable solution seems to be adding test that will check if one of the files from root folder (ie. /server.js are not served as static assets.

This does sound like a reasonable fix.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
