### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-import-a-google-font has an issue 

### ISSUE THREAD

**Issue by Paulie-P** [FreeCodeCamp/freecodecamp#516]
The challenge can be completed by simply typing in font-family: 'Lobster'; , Rather than requiring the prior import from google fonts "href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css

**Comment by QuincyLarson** [comment]
Nice catch! (no pun intended) I'll see if I can write another test to check for that.

**Comment by QuincyLarson** [comment]
Thanks for reporting this. I've fixed and will deploy soon.

**Comment by SamusBailey** [comment]
Thanks this helped me out here in 2015 on the 5th of August at 3:34 in the morning

**Comment by Paulie-P** [comment]
@SamusBailey I'm not quite sure how I helped, but you're more than welcome!
