### ISSUE TITLE
when i return math.random() i get the error: math is not defined 

### ISSUE THREAD

**Issue by IsThis-Code** [FreeCodeCamp/FreeCodeCamp#5160]
Challenge [Waypoint: Generate Random Fractions with JavaScript](http://www.freecodecamp.com/challenges/waypoint-generate-random-fractions-with-javascript#?solution=function%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20math.random()%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A%0A(function()%7Breturn%20myFunction()%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {

  // Only change code below this line.

  return math.random();

  // Only change code above this line.
}

(function(){return myFunction();})();

```

**Comment by BerkeleyTrue** [comment]
Try capitalizing math. In the future please use the help chat before posting a bug report.

Happy Coding!

**Comment by IsThis-Code** [comment]
LMAO thanks man I did use chat no one responded but I'll try to be more diligent.
