### ISSUE TITLE
Some bugs found

### ISSUE THREAD

**Issue by debasish-itobuz** [freeCodeCamp/freeCodeCamp#51626]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**

**To Reproduce**
<img width="1680" alt="Screenshot 2023-09-21 at 4 49 44 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/130981715/4d4d5f34-b7c9-4f0f-8880-0cea17816228">
<img width="1680" alt="Screenshot 2023-09-21 at 4 57 21 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/130981715/02898bc8-6d2a-4eed-b99d-d0a88b2ce30b">

website link : https://www.freecodecamp.org/news/javascript-concepts-to-know-before-learning-node-js/

when I am going through this blog I found some bugs.. 

kindly update the function spelling here “An arrow **functoion** can also take an argument."

Another update is also needed: "The this keyword in JavaScript refers **to to** an object",
2 times to is used.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Parvezkhan0** [comment]
I would like to work on this issue.

**Comment by jevil25** [comment]
I cloned the repo and tried to find the code which has this text but, I am unable to find it. 
Is it fetched from somewhere while loading the page?

**Comment by THEFZNKHAN** [comment]
i want to fix this issue but i am unable to find that file where this definitions is written, can someone tell me where i can find this and fix the code please!!

**Comment by debasish-itobuz** [comment]
I have shared the link and screenshots, kindly check and let me know.

**Comment by THEFZNKHAN** [comment]
Yes sir, I check the website and found the mistake but inside the repo code I can't find that page (file) where this website text is written. 
Is this blog fetch from any other database?

**Comment by ShaunSHamilton** [comment]
@jevil25 and @THEFZNKHAN News articles can only be edited by the author or editorial team.

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by jevil25** [comment]
@ShaunSHamilton Okay got it, Thank you

**Comment by THEFZNKHAN** [comment]
Okay.
Thank you 😇

**Comment by debasish-itobuz** [comment]
You're welcome!

**Comment by harshitkandpal** [comment]
hi is the issue resolved? or can I handle it?

**Comment by ShaunSHamilton** [comment]
> News articles can only be edited by the author or editorial team.

As such, I am limiting conversation to collaborators.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching these issues, @debasish-itobuz, and for the helpful details you provided. I just fixed these typos and a few other minor things. The updated article should go live within a few hours after the next build.

Please let us know if you notice other issues in this or any other articles.
