### ISSUE TITLE
Advertise the freeCodeCamp mobile app for mobile devices.

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#51630]
### Is your feature request related to a problem? Please describe.

It would be nice to Advertise the freeCodeCamp mobile app for mobile users. This will improve their experience. Currently what I am thinking :

1. A pop up:
"It seems you are using a mobile device. Try the freeCodeCamp Moible App." This would be shown once on every block for the available superblocks.

2. Advertising the app in the footer like this:
<img width="316" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/46919888/c8f34cec-bdb7-4e3f-8bf6-f94b6cdd4441">

3. A link in the Navbar to a seperate page that links the IOS and Android version. With a paragraph of what is features. 

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by shahank42** [comment]
Hi, I want to work on this issue. Can I be assigned to it?

**Comment by mintusingh77** [comment]
I want to work on this issue. Please assign me

**Comment by ShaunSHamilton** [comment]
Personally, I dislike the _"download our app"_ pop-ups a lot. So, I would go with suggestion 2.

**Comment by shahank42** [comment]
> Personally, I dislike the _"download our app"_ pop-ups a lot. So, I would go with suggestion 2.

Is there any reason why both suggestion 2 and 3 can't be done?

**Comment by shahank42** [comment]
> > Is there any reason why both suggestion 2 and 3 can't be done?
> 
> In general, we try to keep the navbar as uncluttered as reasonable. In this case, a link to an app store would not necessarily be too bad, but there is a point where there are too many links in a navbar.
> 
> To be clear, I am fine with both, but think just one change would be enough, and the links to the apps in the footer is a common convention.

Yes that makes sense. 
If it's fine then I would like to try and work on it.

**Comment by mintusingh77** [comment]
I want to work please. It's my first open source

**Comment by ShaunSHamilton** [comment]
Let us wait to hear from @ahmaxed what he thinks about the UI.

**Comment by ahmaxed** [comment]
We would need to have the stores in the footer. 
If users are completing challenges through the mobile layout, they should be notified at least once.
Not sure if a modal is the way to go, but a flash message is definitely plausible.

**Comment by Sembauke** [comment]
A flash message should be good too. These 3 suggestions are optional of course.  

@ahmaxed , which do you suggest the most?

**Comment by kunal144** [comment]
How about a slider pop up from underneath the navbar with a timeout function or can also use a close button.

**Comment by bbsmooth** [comment]
> It would be nice to Advertise the freeCodeCamp mobile app for mobile users. This will improve their experience.

I have nothing against the mobile app, I'm just wondering what the main improvements are over the web-based app? If the web-based app is deficient in some areas then it seems like we should fix up the web-based app.

**Comment by ahmaxed** [comment]
@Sembauke, the footer option.

**Comment by Sembauke** [comment]
@ahmaxed Lets go with the footer option then. Could you care to make a mock up for it?

**Comment by Sembauke** [comment]
@bbsmooth There are some ux improvements for mobile devices in the web version. 
See #46178

**Comment by ahmaxed** [comment]
<img width="878" alt="Screenshot 2023-09-27 at 2 38 51 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/8fd67759-bd0e-4099-85a2-cc4c3f10b787">

**Comment by Bharat-vivek** [comment]
can you please pill the request

**Comment by Nirajn2311** [comment]
> what the main improvements are over the web-based app?

The editor in the website has been the major pain point in mobile devices because monaco editor is not designed for mobile devices. It has a lot of issues when used in the web like scroll issues, not being able to select text, keyboard not opening etc.

**Comment by AyushMann29** [comment]
I think solution 2 is the best as it does not annoy mobile users by popping on screen and computer users would also get to know about the feature being available for phone easily.

**Comment by atul320** [comment]
I wanted to address this issue. I would like to propose two solutions, if feasible:

1. We can implement a condition in the styling that, when the screen size is smaller than or equal to a certain size, a pop-up screen will appear after 10-15 seconds to prompt users to install the app. However, if the user closes that pop-up, it will not annoy them further.

2. Another option is to save user cookies. If the user is using a phone, we can scroll down to the footer where links to download the app from the Play Store and App Store are typically located, following the usual standards.

**Comment by hariomgehlot** [comment]
I have Created a PR lets see if it solves this.

**Comment by arjunpras** [comment]
I have created a PR, and also have attached screen shot for mobile and bigger screen devices. Please review it and let me know if any changes needed.
