### ISSUE TITLE
Bug found in a code

### ISSUE THREAD

**Issue by debasish-itobuz** [freeCodeCamp/freeCodeCamp#51659]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Error in this line: let plusFour = (a) => return a + 4;
"return" should not be used in a single line arrow function expression.

It should be :  let plusFour = (a) =>  a + 4;

**To Reproduce**
link :  https://www.freecodecamp.org/news/javascript-concepts-to-know-before-learning-react/
See error

**Expected behavior**

**Screenshots**
<img width="1680" alt="Screenshot 2023-09-22 at 10 45 30 AM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/130981715/f34402ab-5a4e-46c1-a6aa-f24856a28351">

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ayushsingh82** [comment]
U can write in another way 

function plusFour(a){
return a+4;
}

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to report this.

I have limited conversation to collaborators, as news articles can only be edited by the author or editorial team.

**Comment by naomi-lgbt** [comment]
Thanks for reporting this.

I've updated the code snippet - the fix will ship in the next deployment run.
