### ISSUE TITLE
Confusing placement of active editor for Cat Painting Step 8

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#51667]
### Describe the Issue

I've run into this several times in the forum in the past week. The active editor is placed within the existing `.cat-head` rule set and apparently people don't notice that and instead create a new `.cat-head` rule set and add the `background` there.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/step-8

### Your code

This is what I'm seeing in the forum:

```
.cat-head {
  width: 205px;
  height: 180px;
  border: 1px solid #000;
  border-radius: 46%;

/* User Editable Region */

.cat-head {
  background: linear-gradient(#5e5e5e 85%, #45454f 100%);
}

/* User Editable Region */

}
```

### Expected behavior

I think the active editor should include the entire existing `.cat-head` rule set so that it is clear it already exists and that that is where the `background` property should be added. We can add an empty line at the bottom of the rule set to indicate where the `background` property should go.

### System

N/A

**Comment by lasjorg** [comment]
I definitely agree.

I went ahead and made a PR that moves the editable region to include the full selector.
