### ISSUE TITLE
'connected successfully to mongo' message displayed even there is no connection when running 'pnpm run seed' script

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/freeCodeCamp#51676]
### Describe the Issue

when mongodb is off at dev environment and someone trying to run seed script
'connected successfully to mongo' message displayed 

### Affected Page

 'pnpm run seed' 

### Steps to Reproduce

1. turn mongo down
2. try to run 'pnpm run seed' 
3. you will see errror message at the terminal but still 
at the begining - 'connected successfully to mongo' message displayed 

### Expected behavior

in case mongodb is not running - you should see Failed to connect to mongo message

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/1336862/e8d94395-44c8-4347-b850-6281c035340d)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by SozeKeyzer** [comment]
hi i would like to work on this issue

**Comment by ojeytonwilliams** [comment]
Thanks for the report, @shootermv and thanks for the offer of help, @SozeKeyzer.

Anyone is free to work on this, but we recommend new contributors read our contribution guide first: https://contribute.freecodecamp.org/#/

**Comment by sv129899** [comment]
HI I WOULD LIKE TO WORK ON THIS ISSUE

**Comment by papidb** [comment]
Hey @ojeytonwilliams the [pr](https://github.com/freeCodeCamp/freeCodeCamp/pull/51683) is up, can you help me take a look at it? Thanks.
