### ISSUE TITLE
"On to my next challenge" doesn't work

### ISSUE THREAD

**Issue by duttakapil** [FreeCodeCamp/freecodecamp#517]
When clicking on "I've completed this challenge" for the Object Oriented JavaScript Challenges, you see a pop up with a button for going to the next challenge but it doesn't seem to work.

**Comment by terakilobyte** [comment]
Make sure you hard refresh your browser. Temporarily disabling your cache from your developer console also works. Tested and verified in Chrome, Firefox, and Safari.
