### ISSUE TITLE
Waypoint: Iterate over Arrays with map

### ISSUE THREAD

**Issue by jennytech** [FreeCodeCamp/FreeCodeCamp#5170]
Challenge [Waypoint: Iterate over Arrays with map](http://www.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C3%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.map(function(val)%7B%0A%20%20return%20val%20*%203%3B%0A%7D)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7Breturn%20newArray%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,3];

// Only change code below this line.

var newArray = oldArray.map(function(val){
  return val * 3;
});

// Only change code above this line.

(function() {return newArray;})();

```

**Comment by sludge256** [comment]
The instructions at the end are:
"Use the map function to **add 3** to every value in the variable oldArray."

**Comment by ltegman** [comment]
@sludge256 is correct.

Thanks and happy coding!
