### ISSUE TITLE
Waypoint: Iterate over Arrays with map

### ISSUE THREAD

**Issue by jennytech** [FreeCodeCamp/FreeCodeCamp#5171]
var oldArray = [1,2,3,4,5,3];

// Only change code below this line.

var newArray = oldArray.map(function(val){
  return val * 3;
});

// Only change code above this line.

(function() {return newArray;})();

**Comment by sludge256** [comment]
Assuming you are on:
<a href="http://www.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map">Waypoint: Iterate over Arrays with map</a>

The instructions at the end are:
"Use the map function to **add 3** to every value in the variable oldArray."

**Comment by sludge256** [comment]
Duplicate of #5170
