### ISSUE TITLE
JavaScript Calculator bug

### ISSUE THREAD

**Issue by lohithreddym4** [freeCodeCamp/freeCodeCamp#51727]
### Describe the Issue

During my testing of various inputs, I noticed a specific behavior. When typing only "=" as input, the result is NaN. However, if an operator is used, NaN is included in the operation. For example, "= + 15 =" results in "NaN". Similarly, when the result is Infinity, as in "10/0", and an operator is used, Infinity is included in the sum. Only when typing a number does the previous result get discarded. In my opinion, it is unnecessary to use NaN or Infinity in sums.

### Affected Page

https://javascript-calculator.freecodecamp.rocks/

### Steps to Reproduce

1.click "="
2.click "+"
3.enter 15 
4.click "="

### Expected behavior

When clicking "=" for the first time, the calculator should remain idle until a number is entered. It should also ignore any operators.

### Screenshots

![Screenshot 2023-10-01 141339](https://github.com/freeCodeCamp/freeCodeCamp/assets/77874493/cdd907b8-803d-46d9-83a9-a7cf15b659fc)

### System

- Device: [Laptop]
- OS: [Windows 11]
- Browser: [Chrome]

**Comment by JoelJaison394** [comment]
Can I work on this issue?

**Comment by Gauravtripathii** [comment]
I would love to work on this issue

**Comment by codrrk08** [comment]
Hi Joel, I'll be glad to work on this issue.

**Comment by codrrk08** [comment]
Hi, I'll be glad to work on this bug.

**Comment by Shivam14142** [comment]
Hi @lohithreddym4 Interested in working on this issue But can you tell whether something should appear on calculator while clicking on '=' or by default 0 should appear on screen as I have tried similar operation on other calculator and instead of displaying NAN they are displaying 0
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/107758914/c0843ca5-9cab-42cf-b9ad-17e41fbacb4d)

**Comment by Mehulparekh144** [comment]
I would like to work on this issue.

**Comment by techmannih** [comment]
hello @ojeytonwilliams ,
I want to work on this issue ......please assign me 
thank you.

**Comment by VitthalGund** [comment]
Hey,
I have already solved this issue on codepen while completing the challenge.
You can check the demo [here](https://codepen.io/Sahil-29P/full/LYMdKqd)
or Link: https://codepen.io/Sahil-29P/full/LYMdKqd

I can implement it very well just tell the location source on this github repository and assign this issue to me.

**Comment by NawinKumarSharma** [comment]
hi, I would like to work on this issue.

**Comment by lohithreddym4** [comment]
helllo @Gauravtripathii @Mehulparekh144 @codrrk08 @VitthalGund @NawinKumarSharma @techmannih  ,
I found this issue ... can you please work on another issue.

**Comment by VinayakGaikwad101** [comment]
I'd greatly appreciated if this was assigned to me I'm new to hacktoberfest and open source

**Comment by TanyyshaJ** [comment]
Hi! I'd love working on this issue!

**Comment by jeremylt** [comment]
Please wait until an issue has been marked as ready for contributions. 

For any project, it's best to read how that project wants/needs help: 
https://contribute.freecodecamp.org/

**Comment by Ashutoshkumar7970** [comment]
hii bro, i want work on this issue please assigned to me or for another ...please

**Comment by jeremylt** [comment]
> hii bro, i want work on this issue please assigned to me or for another ...please
>  

Please read my comment immediately above yours

**Comment by TezzMore** [comment]
Hey! I'll be glad to work on this issue.

**Comment by jeremylt** [comment]
> Hey! I'll be glad to work on this issue.

Please read my comment about explaining how it's best to actually read a project's contributing guidelines

**Comment by digital-dev-07** [comment]
Dear Contributors, 

Join my team on Hackquad and HacktoberFest 2023. 1 contribution will count for both Hacksquad and HacktoberFest. Increase your chances of winning certificates and swags from both the contests.

https://www.hacksquad.dev/invite/cln8n87c80011mn06bjd8f1f3

**Comment by Smritigit1202** [comment]
hello sir, can I work in this issue?

**Comment by jeremylt** [comment]
> hello sir, can I work in this issue?
> 

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by mevipinmaurya** [comment]
i would like to resolve this problem Kindely assign me thanks!!

**Comment by jeremylt** [comment]
> i would like to work on this issue can you please assign to me

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by saumit123** [comment]
hey I need the file location

**Comment by enarddpascua** [comment]
Can I work on this issue?

**Comment by jeremylt** [comment]
> hey I need the file location

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by Chirag19gupta** [comment]
I have the solution for the bug, can you please assign me.

**Comment by jeremylt** [comment]
> I have the solution for the bug, can you please assign me.

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by jeremylt** [comment]
Yeah, I'm definitely fine with leaving the sample as only meeting the functional requirements laid out in the certification project.

**Comment by naomi-lgbt** [comment]
Closing this as unnecessary to fix - it's not included in the project spec, and we don't want to update the spec in a way that potentially invalidates previously submitted projects.
