### ISSUE TITLE
[BUG] Wrong Symbols used in the Example TestCases on a JS Question

### ISSUE THREAD

**Issue by AnuragM23** [freeCodeCamp/freeCodeCamp#51726]
### Describe the Issue

According to the first 3  test cases, the 'tick' (symbol/button) means the test case is correct and the 'cross'(x) represents the  wrong ones. But later in the examples the wrong cases are also represented by the tick.
e.g Test Case '007' supposed to be cross but it is tick out there. and many more 👇👇👇.  
![Screenshot from 2023-10-01 12-33-03](https://github.com/freeCodeCamp/freeCodeCamp/assets/94822228/35cd7cee-f4f5-4919-a965-8c88c82a67b5)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

### Your code

```js
let username = "JackOfAllTrades";
let userCheck = /^[a-zA-Z]+[0-9]*$/; // Changed this Line
let result = userCheck.test(username);

username = "BadUs3rnam3"; // should be false.
result = userCheck.test(username);
if(username.length < 2) result=false; // Edge case for single digit usernames 

```

### Expected behavior

The Examples Test Cases like '007', '9', 'BadUs3rnam3' etc. should have cross(x) symbol at the beginning since they does not support the problem statement. 

![Screenshot from 2023-10-01 13-18-47](https://github.com/freeCodeCamp/freeCodeCamp/assets/94822228/2f50ebf3-9384-4545-acbd-9586fc6f474d)

### System

- Device: Laptop
- OS:  Ubuntu 20.04
- Browser: Chrome
- Version: latest

**Comment by rajdeep-biswas** [comment]
I can take this up.

**Comment by ieahleen** [comment]
The tick is if your code pass the test, and the cross is if you don't pass the test. It doesn't matter if the test say "it should match" or "it should not match"

**Comment by lohithreddym4** [comment]
The regular expression /^[a-zA-Z]([0-9]{2,}|[a-zA-Z]+\d*)$/ is correct, and there is a mistake in the pattern mentioned earlier

**Comment by ieahleen** [comment]
Please expand on why you think there is a mistake
