### ISSUE TITLE
How to fight Imposter Syndrome

### ISSUE THREAD

**Issue by carl-parrish** [FreeCodeCamp/FreeCodeCamp#5173]
http://www.forbes.com/sites/margiewarrell/2014/04/03/impostor-syndrome/

**Comment by carl-parrish** [comment]
https://www.braintreepayments.com/blog/overcoming-imposter-syndrome/

**Comment by carl-parrish** [comment]
https://open.buffer.com/impostor-syndrome-8-tips-i-wish-i-had-known/

**Comment by bugron** [comment]
cc @brianamarie

**Comment by BerkeleyTrue** [comment]
This should be moved to the hikes repo.

**Comment by bugron** [comment]
Moved this issue to Hikes repository, see https://github.com/FreeCodeCamp/hikes/issues/165. @carl-parrish thanks for posting. Closing.
