### ISSUE TITLE
Cannot claim Front-end Cert

### ISSUE THREAD

**Issue by natac13** [FreeCodeCamp/FreeCodeCamp#5174]
I just completed the last project for the front-end certificate. 
![completechallenges](https://cloud.githubusercontent.com/assets/10660283/11767707/5646d270-a183-11e5-8736-8e8e731b6ae3.png)

But get an error on step 3 to try again later??? 

![fccerror](https://cloud.githubusercontent.com/assets/10660283/11767714/90364bc8-a183-11e5-80f5-ef15543ea91b.png)

The strange avatar pic in the top middle of the page is real and appears after clicking the big button to open the new link to verify the work is done. It is also clickable like the normal avatar in the top right corner.

**Comment by SaintPeter** [comment]
Confirmed.  We've got several reports of this bug.

@BerkeleyTrue can you check this out?

**Comment by BerkeleyTrue** [comment]
Looking into it.

**Comment by natac13** [comment]
Sweet thanks to both of you!

**Comment by BerkeleyTrue** [comment]
Can y'all give it a try again and see if it works now?

**Comment by natac13** [comment]
@BerkeleyTrue You got it! Thanks so much! So happy to get my certificate! Excited for the react challenges to help solidify what I learned making this project. React and Redux are amazing.

**Comment by BerkeleyTrue** [comment]
@natac13 Congratulations!

**Comment by carefulAxe** [comment]
Hi, I am experiencing the same issue. Error in console says:

Failed to parse SourceMap: https://www.freecodecamp.com/challenges/rx.all.map

Here's my screenshot:

![image](https://cloud.githubusercontent.com/assets/9951362/14366007/90582354-fcc5-11e5-988d-6b43c46f1d80.png)
