### ISSUE TITLE
pnpm run deploy ERROR: "develop:client" exited with 1.  ELIFECYCLE  Command failed.  ELIFECYCLE  Command failed with exit code 1.

### ISSUE THREAD

**Issue by Himanshu-holmes** [freeCodeCamp/freeCodeCamp#51751]
⠋ Building development bundle
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed.
ERROR: "develop:client" exited with 1.
 ELIFECYCLE  Command failed.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by raisedadead** [comment]
Thanks for the issue. Please read our [contributing guidelines](https://contribute.freecodecamp.org), and use the issue template.
