### ISSUE TITLE
Waypoint: Add Images to your Website (HTML5/css course, lesson #16)

### ISSUE THREAD

**Issue by DavOnGit** [FreeCodeCamp/FreeCodeCamp#5176]
In this lesson you have to add an image to your html/css project.

This is the link provided: https://bit.ly/fcc-relaxing-cat
and if you put this on your image tag it desn't show anythink.

If you pass the link on the browser it acually redirect you to:
https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg
that correctly show the 'relaxing cat'.

I think this need to be fixed (this is not a problem if u are intermediate or advanced on html, but if u are on first steps on coding, this can cause unnecessary pain :))

**Comment by eirism** [comment]
The link worked correctly for me, using `<img src="https://bit.ly/fcc-relaxing-cat"/>`, and it also works correctly in github markdown: <img src="https://bit.ly/fcc-relaxing-cat"/>

**Comment by DavOnGit** [comment]
Ok, it works if i open it on Firefox , but on IceDragon browser it does't redirect and does't show.
This can be fixed giving also the second link:

"Try it with this image:
https://bit.ly/fcc-relaxing-cat or
https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg"

**Comment by ltegman** [comment]
We do not support the IceDragon browser. Please switch to Firefox or Chrome if you continue experiencing problems.

Thanks and happy coding!

**Comment by Gabriel2700** [comment]
Having trouble with 'Add images to your website'
<img src="https://bit.ly/fcc-relaxing-cat"/>
  alt="kittens relaxing.">

**Comment by eagertolearn912** [comment]
need help

**Comment by eagertolearn912** [comment]
it said i need to have a alt attribute
