### ISSUE TITLE
Multi-Sign Up with same eMail Address

### ISSUE THREAD

**Issue by 5k9m** [FreeCodeCamp/FreeCodeCamp#5177]
I just hit the wrong link while trying to log in - instead of "If you originally signed up using your email address, you can sign in here." I hit "Or sign up using your email address here." by accident. And because I had all my data pre-filled by auto-form, I signed up a new account. Which made me wonder: do you really want people to be able to register multiple accounts with the very same eMail address?

**Comment by BerkeleyTrue** [comment]
Do you mind sending me your email address on Gitter.

**Comment by BerkeleyTrue** [comment]
I can confirm that there are two instances of that email in our records.

**Comment by bugron** [comment]
@5k9m @BerkeleyTrue is this still an issue?

**Comment by BerkeleyTrue** [comment]
Nope, this has been fixed.
