### ISSUE TITLE
Waypoint: Condense arrays with reduce ,it return 30.But I don't know which array number add = 30

### ISSUE THREAD

**Issue by jennytech** [FreeCodeCamp/FreeCodeCamp#5178]
Challenge [Waypoint: Condense arrays with reduce](http://www.freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce#?solution=var%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20singleVal%20%3D%20array.reduce(function(previousVal%2CcurrentVal)%20%7B%0A%20%20%20%20return%20previousVal%20%2B%20currentVal%3B%0A%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7Breturn%20singleVal%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [4,5,6,7,8];

// Only change code below this line.

var singleVal = array.reduce(function(previousVal,currentVal) {
    return previousVal + currentVal;
});
                             

// Only change code above this line.

(function() {return singleVal;})();

```

**Comment by ltegman** [comment]
Github issues are only for site bugs. Please us the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need help with a challenge.

Thanks and happy coding!
