### ISSUE TITLE
Typographyproject: Step-43 Misleading  instructions

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#51786]
### Describe the Issue

To begin with, the directions implied that there would be 3 spans that weren't interconnected for alignment.

My initial assumption would be that the solution would be something like:

```html 
 <p><span class="bold">Total Fat </span><span>8g</span><span class="bold">10%</span> 
```

Nowhere did it seem to imply that a span was supposed to be nested inside another span. But when I looked at the code for the next challenge, that became clear. However, I ran into another problem; spacing of my elements will cause the tests to fail. I like my opening and closing tags to be on separate lines usually, but here it will break the test. The tests need a little work. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-43

### Your code

```
   <div class="daily-value small-text">
      <p class="bold right">% Daily Value *</p>
      <div class="divider"></div>
     <p>
       <span>
         <span class="bold"> 
           Total Fat  
           </span> 
           8g</span>
         <span class="bold">
           10%
          </span>
      </p>
    </div>
```

### Expected behavior

I expect the instructions to clarify that the span for "Total Fat" is supposed to be nested inside another span where "8g" is supposed to be. Additionally I'd like the tests to be a little more spacing resistant so that if the right answer is rendered, the tests don't fail. 

### Screenshots

![My solution](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/632c1b41-3ee8-4410-9a11-a89a965fa20e)

### System

- Device: Desktop Computer
- OS: Windows 10 
- Browser: Firefox
- Version: 118.0.1

**Comment by legendary0911** [comment]
can you assign this to me

**Comment by naomi-lgbt** [comment]
> can you assign this to me

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by bbsmooth** [comment]
> Nowhere did it seem to imply that a span was supposed to be nested inside another span.

This is the final line of the instructions:

"Finally, nest the `Total Fat` span element and the text `8g` in an additional span element for alignment."

To me this is saying that a `span` is going to be nested within another `span`, but maybe there is a way to make it clearer?

"Finally, nest both the first `span` you added around the words `Total Fat` and the text `8g` in a new `span` to help with alignment."

Or ya, go with @naomi-lgbt's suggestion and break it into separate steps.

**Comment by jeremylt** [comment]
> Nowhere did it seem to imply that a span was supposed to be nested inside another span.

> Finally, nest the Total Fat span element and the text 8g in an additional span element for alignment.

It does say to put a span in a span in the instruction.


BUT

I also think it would be clearer to put that third bit into another step immediately after this one.

**Comment by a2937** [comment]
Yeah dividing this up into two separate steps might help quite a bit.

**Comment by bbsmooth** [comment]
Steps 53, 54, and 55 do the same thing as this step (i.e. add three `span`s to the text with the third `span` wrapping one of the previous `span`s). If the solution for this step is to split it into two then do we need to split 53, 54, and 55 as well?

I do think a rewrite of the instructions will suffice (for all of these steps). Unless we think that having the user add three `span`s in a single step is too much. Perhaps something like the following:

---
After your last `.divider` element, create a `p` element and give it the text `Total Fat 8g 10%`. Then add the following `span` elements to the text as follows:

- Wrap the text `Total Fat` in a `span` element with the `class` of `bold`.
- Wrap the text `10%` in another `span` element with the `class` of `bold`.
- Wrap both the first `span` you added around the words `Total Fat` and the text `8g` together in a single new `span` to help with alignment.
---

**Comment by jeremylt** [comment]
I think once we show the user the target once, they should be able to replicate it down the line with the other steps much more easily, so I'm much less worried about those later steps.

Rewriting those other 3 steps for clarity is probably a good idea though.

**Comment by naomi-lgbt** [comment]
Going to open this up for contribution. A PR which resolves this issue will:

- Break step 43 into two steps, using the second step to add the final `span` separately
- Update step 53, 54, and 55 to better delineate the requirements as suggested above.

**Comment by ganesh-159th** [comment]
I will do my best to contribute to resolving these issues

**Comment by ganesh-159th** [comment]
I'm currently working on making updates to the "Learn Typography by Building a Nutrition Label" project in the freeCodeCamp curriculum. However, I'm unable to locate the JSON files that correspond to each step of the curriculum, such as step-43.json, step-44.json, etc.

Could you please provide me with the specific file path or directory where these JSON files are located? This information will help me proceed with the necessary modifications as per our recent discussions.
