### ISSUE TITLE
Unreadable text in a table in Nigth Mode

### ISSUE THREAD

**Issue by abomo** [freeCodeCamp/freeCodeCamp#51785]
### Describe the Issue

On the **JavaScript Algorithms and Data Structures** challlenge **Escape Sequences in Strings** 
 https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings, a table doent display all the element in Nigth Mode.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings

### Your code

```



```
;

### Expected behavior

;

### Screenshots

![Dark mode](https://github.com/freeCodeCamp/freeCodeCamp/assets/21217284/78f34acc-7034-46a1-973d-a4f5fc5edf35)
![Ligth mode](https://github.com/freeCodeCamp/freeCodeCamp/assets/21217284/d21ef8ea-e75a-46e4-9668-acd38ee5587f)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Prajwalr2003** [comment]
### Hello Sir, I am Prajwal Rangari, i am very interested in contributing on this issue.
### i saw this issue
![freecodecamp](https://github.com/freeCodeCamp/freeCodeCamp/assets/113047858/cd62436e-bac3-4c71-b96f-2e108773f9f7)

### and solved it as
![freecodecamp table issue](https://github.com/freeCodeCamp/freeCodeCamp/assets/113047858/241a0b29-9633-4d93-abbc-b1d10faeeb7a)

so i request you to please assign this issue to me

**Comment by naomi-lgbt** [comment]
> so i request you to please assign this issue to me

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by Prajwalr2003** [comment]
I apologize for my previous request to assign the issue. I understand and respect the project's guidelines as outlined in the contributing guide. I'll refrain from requesting issue assignment and will focus on issues marked as 'ready for contributions' or help wanted.
Thank you for your guidance.

**Comment by Sboonny** [comment]
I don't like the markdown files having styles affected by bootstrap, I think it's best for the long run to delete the classes from these twelve files, this will fix the border as well
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/17ab7b1f-3bce-4e6a-8b35-cdf17dcd5484)

---

my least favorite approach is to add more properties in these selectors, it should solve the issue

https://github.com/freeCodeCamp/freeCodeCamp/blob/3d2746cdcfd546f2a3a0724729adf91bec140857/client/src/components/layouts/global.css#L501-L510C2

---

last option is to delete this selector `.table-striped>tbody>tr:nth-of-type(odd)` in bootstrap.min.css

**Comment by naomi-lgbt** [comment]
I'm fine with deleting the bootstrap classes, but then we should implement our own. The striped table is a nice look and I'd like to preserve it.

**Comment by Sboonny** [comment]
if the classNames are deleted, adding the styles is a simple, it will be adding selector and property, I am okay with that.

-----


If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our prolific contributors will guide you through this.

**Comment by lasjorg** [comment]
Do we make all tables have a striped style by default or create a new class for it?

**Comment by Sboonny** [comment]
All tables in challenge instructions, until we have tailwind, or something a like in the code base, I prefer the fewer cases of unique styles
