### ISSUE TITLE
Font color and Table bg row color is same

### ISSUE THREAD

**Issue by shsalman114** [freeCodeCamp/freeCodeCamp#51795]
### Describe the Issue

# Font color and bg row color is same

Table background row color and font color is **same**. Can't see the value in the given table

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/counting-cards

### Steps to Reproduce

1. Go to the provided link
2. Click on "Table'
3. Select the 1st row text

### Expected behavior

Background **row** color should be *light dark*

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/142220108/e97635ce-bb8b-4f3c-9e21-d7d2e3c882f3)

![fcc](https://github.com/freeCodeCamp/freeCodeCamp/assets/142220108/589515d7-6527-412a-8cc9-cf51438c8d58)

### System

- Device: [Laptop]
- OS: [ Windows 10]
- Browser: [Chrome]
- Version: [117]

**Comment by SteffiArockia15** [comment]
i would like to work on this

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #51785, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
