### ISSUE TITLE
Illegible table text in night mode

### ISSUE THREAD

**Issue by WilliamSpanfelner** [freeCodeCamp/freeCodeCamp#51828]
### Describe the Issue

The Cash Register project in the JavaScript Algorithms and Data Structures course displays data in a table in which 50% of the data/headings are almost entirely obscured.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register

### Your code

```
;


```

### Expected behavior

;

### Screenshots

![1fcc](https://github.com/freeCodeCamp/freeCodeCamp/assets/102249249/3e056a69-544e-4415-a457-dee0a21000aa)
![2fcc](https://github.com/freeCodeCamp/freeCodeCamp/assets/102249249/33e448b5-8bb1-4399-a856-198757ea288c)

### System

- Device: Laptop
- OS: macOS 11.7.10 (20G1427)
- Browser: Firefox 118.0.1, Safari 16.6.1
- Version: 118.0.1, 16.6.1

### Additional context

<table class="table table-striped">
<tbody>
<tr>
<th>Currency Unit</th>
<th>Amount</th>
</tr>
<tr><td>Penny</td><td>$0.01 (PENNY)</td></tr><tr><td>Nickel</td><td>$0.05 (NICKEL)</td></tr><tr><td>Dime</td><td>$0.1 (DIME)</td></tr><tr><td>Quarter</td><td>$0.25 (QUARTER)</td></tr><tr><td>Dollar</td><td>$1 (ONE)</td></tr><tr><td>Five Dollars</td><td>$5 (FIVE)</td></tr><tr><td>Ten Dollars</td><td>$10 (TEN)</td></tr><tr><td>Twenty Dollars</td><td>$20 (TWENTY)</td></tr><tr><td>One-hundred Dollars</td><td>$100 (ONE HUNDRED)</td></tr></tbody></table>

**Comment by droidbg** [comment]
@WilliamSpanfelner I like to pick this up.

**Comment by coder-002** [comment]
where can i find the code leading to this error? should I clone main project or from other? I am new to opensource. Trying to solve issue

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #51785, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
