### ISSUE TITLE
Logged in to a random user account

### ISSUE THREAD

**Issue by aayn** [FreeCodeCamp/FreeCodeCamp#5182]
So, I had gone afk for 20 minutes, and when I came back, my display profile on the top right corner had changed to some other guy's.(Mine is same as my Github dp) I was(still am when writing this) logged in and as [this guy](http://www.freecodecamp.com/dakshshah96).
The progess(waypoints and ziplines) that I see are also not mine.

Turns out, both of us live in the same city and had the same number of brownie points when this happened.
![not-me](https://cloud.githubusercontent.com/assets/9693267/11769527/6077df06-a1fa-11e5-920c-556e440aa719.png)

**Comment by aayn** [comment]
I went back to my own account after a few refreshes, but what I'd like to know is what caused this? Could be rather serious issue.

**Comment by BerkeleyTrue** [comment]
Did you sign in and where given another account or did you move from one page to another and saw that your image/points changed?

**Comment by aayn** [comment]
I was already logged in. I was doing [this](http://www.freecodecamp.com/challenges/bonfire-where-art-thou) zipline and I had submitted the solution. Then, I went afk, came back, and submitted the same solution again(as I was still on the same page). After this particular submit, I was logged in as that guy.

**Comment by dakshshah96** [comment]
@BerkeleyTrue FYI, that's my FCC profile he was logged in to.

**Comment by aayn** [comment]
Update: This keeps happening now. The same thing happened twice again.

**Comment by BerkeleyTrue** [comment]
I'm at a loss. @dakshshah96 Are you experiencing this?

**Comment by aayn** [comment]
He is. He told it to me in chat.

**Comment by dakshshah96** [comment]
@BerkeleyTrue Yes, it happened yesterday when I returned to Free Code Camp and refreshed the page after being away for a few hours.

<img width="1280" alt="screenshot 2015-12-15 18 44 06" src="https://cloud.githubusercontent.com/assets/7896438/11835426/7c5f6284-a3e4-11e5-971f-fe7fb9d28279.png">

**Comment by bugron** [comment]
@aayn @dakshshah96 is this still an issue for you?

**Comment by bugron** [comment]
This seems user specific. Closing. Feel free to reopen if you still experience problems and thanks for posting.
