### ISSUE TITLE
How to Prepare for React Interviews – Front-End Technical Interview Guide

### ISSUE THREAD

**Issue by Davidkramer1999** [freeCodeCamp/freeCodeCamp#51836]
### Describe the Issue

On chrome when the article is not in full width it breaks the sandbox (code example)
Can fix this issue?

### Affected Page

https://www.freecodecamp.org/news/prepare-for-react-technical-interviews/

### Steps to Reproduce

Try to reduce the size of window 

### Recommended fix or suggestions

Make the sandbox reposnive

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/74869455/429d8fc2-4405-4aa0-9437-f6d8f314e28d)

**Comment by dhawansolanki** [comment]
I would like to contribute for this issue. Thanks

**Comment by himanshukesarwani-dev** [comment]
Hi David, this issue seems interesting to me. I understand the issue and want to work on it to find a reliable solution. Can you please assign this issue to me?

**Comment by Davidkramer1999** [comment]
Hello i wil try to solve it...

**Comment by Divyanshu1020** [comment]
@Davidkramer1999 and @himanshukesarwani-dev 
I have small request from you, I also understand this error/bug but when I try open this in Gitpod ( recommended in "[how-to-setup-freecodecamp-locally](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally)") 

i wasn't able to find the location of file or folder. Can you give me guide How can I find location of file in next time 
**I know what to do but didn't know how to do**

**Comment by jeremylt** [comment]
This issue has not been marked as ready for contributions yet.

**Comment by Madhur72** [comment]
Can I work on this issue ?

**Comment by jeremylt** [comment]
> Can I work on this issue ?

Please stop and read our contributing guide.

https://contribute.freecodecamp.org/

This issue is not marked as ready for contributions or help wanted. Also, we do not assign issues.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @Davidkramer1999.

I went into our CMS and updated those CodeSandbox embeds so they're all responsive. The updates should go live within the next few hours after the next build.

Please let us know if you notice issues in this or any other article.
