### ISSUE TITLE
Accessing Nested Objects: Object shape should be part of the requirements/tests

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#51870]
### Describe the Issue

Every so often a camper will change the `glove box` property to something that can be accessed using dot notation instead of accessing the original property using bracket notation.

It does clearly say:

> assign the contents of the `glove box` property

But I think having a test that checks the object shape wasn't changed might help.

> You should not change the `myStorage` object or any of its properties.
```js
assert.isDefined(myStorage.car.inside['glove box']);
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/accessing-nested-objects

### Your code

```



```

### Expected behavior

Make it clear the shape of the object should not be changed.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Just one example https://forum.freecodecamp.org/t/basic-javascript-accessing-nested-objects/643224

**Comment by mujtbkhn** [comment]
hey lasjorg, i am attempting for my first ever contribution from the description above i can understand that some camper is changing the value of glove box that makes it accessible using dot notation but we want it only accessible using bracket notation can you please provide me with some more information so that i can contribute? thank you!

**Comment by gikf** [comment]
Sounds reasonable, as one of the tests is already implicitly checking if relevant property is not changed, but hint text won't say much about that issue.

**Comment by lasjorg** [comment]
An issue with the help wanted or first timers only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

Change needed:

Add a new test that informs/warns the camper if they try to alter the object's shape. It can be a deep object compare or just the most relevant/likely property to be changed, i.e. the `glove box` property.

File to work on:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/accessing-nested-objects.md
