### ISSUE TITLE
Broken link in the Article on How to Contribute to Open Source Projects – A Beginner's Guide

### ISSUE THREAD

**Issue by shettyvarshaa** [freeCodeCamp/freeCodeCamp#51897]
### Describe the Issue

Under the subheading 'How to find an Open Source Project to Contribute to' in the Article  on [How to Contribute to Open Source Projects – A Beginner's Guide](https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/), there is a broken link '[Contributor Ninja](https://contributor.ninja/)'

### Affected Page

https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/

### Steps to Reproduce

1. Go to '[How to Contribute to Open Source Projects – A Beginner's Guide](https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/)'
2. Scroll down to 'How to find an Open Source Project to Contribute to'
3. Click on '[contributor ninja](https://contributor.ninja/)'

### Expected behavior

The broken link can be removed and replaced with

- [Contrib](https://gauger.io/contrib/#/language/javascript)
- [Ovio.org](https://ovio.org/projects)

## News Article : 
![article](https://github.com/freeCodeCamp/freeCodeCamp/assets/112955692/ea1d850a-e4d8-452e-8ac0-01dfc8816757)

## Error :

![error](https://github.com/freeCodeCamp/freeCodeCamp/assets/112955692/bf3ad75d-ad31-45b3-9d4b-52bd181fd4ee)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Ahmad-06** [comment]
ShaunSHamilton mentioned in another issue that "News articles can only be edited by the author or editorial team."

For reference, the original comment can be found at: https://github.com/freeCodeCamp/freeCodeCamp/issues/51626#issuecomment-1732258155

**Comment by jdwilkin4** [comment]
HI @shettyvarshaa ! 

Thank you for opening up this issue.
I have gone ahead and messaged the editorial team about this so it can be fixed.

cc @scissorsneedfoodtoo

**Comment by AbbeyRenn** [comment]
Thanks all, fixed!
