### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by vishim** [FreeCodeCamp/freecodecamp#519]
The challenge does not show anything meaningful, it says 
Syntax error, unrecognized expression

![t](https://cloud.githubusercontent.com/assets/5598054/7813293/9301325c-03b1-11e5-9e37-9946fe521fa3.jpg)

**Comment by QuincyLarson** [comment]
@vishim Please check again to see whether this is now fixed. If it works now, please let me know. Otherwise, please tell us which browser and operating system you're using. Thanks!

**Comment by QuincyLarson** [comment]
We've fixed this. Thank you for your patience, and for bringing this to our attention!
