### ISSUE TITLE
Move the confetti logic to the related redux-saga

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#51908]
### Is your feature request related to a problem? Please describe.

The following steps will improve the functionality and maintainability of the confetti feature:
1. The confetti logic should be moved to the related redux-saga (execute-challenge-saga).
2. The confetti should pop at the end of each block completion instead of certification projects.

Self-note: When Growthbook is fully incorporated with redux, put the confetti behind an AB test to measure its effect on user progress.

**Comment by ahmaxed** [comment]
[a2937](https://github.com/a2937), in case you are still interested.

**Comment by a2937** [comment]
Thank you. I'll happily take on this issue.

**Comment by 07tAnYa** [comment]
kindly assign this to me , I can work on this

**Comment by ahmaxed** [comment]
No assignment is necessary as described in our [contribution guidelines](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.

**Comment by Yash-Ambekar** [comment]
@ahmaxed  Can you please elaborate more on the issue?

**Comment by airwakz** [comment]
Assign this issue to me i will work on this asap
