### ISSUE TITLE
Certificate is not responsive for small screen devices

### ISSUE THREAD

**Issue by Chetan-KK** [freeCodeCamp/freeCodeCamp#51926]
### Describe the Issue

# Certificate is not responsive for small screen devices

here is screenshot of this certificate on small device
![d](https://github.com/freeCodeCamp/freeCodeCamp/assets/44507196/4f78b8dc-cddf-4508-b850-8f904a18630f)

### Affected Page

https://www.freecodecamp.org/certification/Chetan-KK/javascript-algorithms-and-data-structures

### Steps to Reproduce

1. Go to '[certificate page](https://www.freecodecamp.org/certification/Chetan-KK/javascript-algorithms-and-data-structures)'
3. Scroll down to 'Certificate'

### Expected behavior

- certificate should not need to be responsive it should be in same format for all screen sizes

### Screenshots

![d](https://github.com/freeCodeCamp/freeCodeCamp/assets/44507196/4f78b8dc-cddf-4508-b850-8f904a18630f)

### System

- Device: [Realme X2]
- OS: [android 11]
- Browser: [Chrome]
- Version: [116.0.5845.164]

**Comment by majithecoder** [comment]
Hi Admin could you assign the issue  to me?

**Comment by IamSAL** [comment]
I'm willing to undertake this issue.

**Comment by Chetan-KK** [comment]
no, we have to make it as it should be same on all devices

**Comment by jeremylt** [comment]
@majithecoder @IamSAL please read our contributing guide:
https://contribute.freecodecamp.org/

This issue has not been triaged or marked as ready for contributions. Also, we do not assign issues.

**Comment by jeremylt** [comment]
I don't see a problem in making the certificate responsive. It should look nice on whatever screen size you are currently using.

**Comment by Chetan-KK** [comment]
every certificate has a specific height and width and it needs to look same on mobile or pc

**Comment by jeremylt** [comment]
Why does it need to look the same on mobile or pc?

**Comment by lasjorg** [comment]
I agree, I don't see why someone on a large desktop monitor should be looking at some tiny version of the certificate just because that will fit on your phone.

---

There is a fixed height on `information` and position on `information-container` which both seem unnecessary.

Using `min-height` and some `padding-top` instead looks just fine to me and works on all screen sizes (as far as I can tell).

**Comment by naomi-lgbt** [comment]
> Edit: I assume there is no easy way to see the certificate in dev?

If you `pnpm run seed:certified-user` you can set up a pre-certified user account. Then when you visit the local instance the auth flow will sign you in as that user (unless you run into cookie issues like I **always** do haha).

**Comment by Chetan-KK** [comment]
alright, let's just make it responsive so nothing overlaps on each other
