### ISSUE TITLE
Content misalignment on the profile page

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#51955]
### Describe the Issue

This issue was reported on Discord: https://discord.com/channels/692816967895220344/693145545878929499/1162395054237831301.

The certification links are shifted to the left instead of being centered:

<img width="751" alt="Screenshot 2023-10-13 at 21 56 47" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/86813a2d-4d84-416f-ab73-f0102878cd83">

### System

N/A

**Comment by januslinhc** [comment]
Hi can i work for it for hacktoberfest?

**Comment by shivani2190** [comment]
Assign this task to me

**Comment by vanshraghav** [comment]
PLEASE ASSIGN ME WITH THIS ISSUE

**Comment by Tanishka-22** [comment]
I trust my skills to be able to help you regarding this issue. Kindly consider me for the Assignment

**Comment by chaotic-10** [comment]
Could you please Assign the task to me

**Comment by devuser200** [comment]
@huyenltnguyen any comments?

**Comment by moT01** [comment]
There's a number of PR's to fix this in different ways - do we want to center the buttons or make them full width? Formerly they were centered. I think it looks good either way.

Also, I did a little digging on this issue and provided some [more context in a review.](https://github.com/freeCodeCamp/freeCodeCamp/pull/52008#pullrequestreview-1682466920)

**Comment by developer-gagandeep-singh** [comment]
@moT01 @huyenltnguyen   
Hey Tom,
Hey Huyen Nguyen,
Could you please review my PR and tell me what improvements I can make for next time.
