### ISSUE TITLE
Add Top 100 contribor on readme.md file

### ISSUE THREAD

**Issue by MuhammadNizamani** [freeCodeCamp/freeCodeCamp#51953]
### Is your feature request related to a problem? Please describe.

No, It will just look good for contributor

### Describe the solution you'd like

I will use like for contributor link

### Describe alternatives you've considered

NA

**Comment by jeremylt** [comment]
I don't see a need to do this. Such a list would become frequently out of date, and its already viewable here:
https://github.com/freeCodeCamp/freeCodeCamp/graphs/contributors

**Comment by MuhammadNizamani** [comment]
I know that but it's look nice in contributor section like I have added this idea in this repo 
https://github.com/spotDL/spotify-downloader/tree/dev

**Comment by MuhammadNizamani** [comment]
ok then I should close this issue
