### ISSUE TITLE
Remove docsify tabs from docs

### ISSUE THREAD

**Issue by developer-gagandeep-singh** [freeCodeCamp/freeCodeCamp#51958]
### Describe the Issue

**ISSUE :** On the Contribution Guide Page, there is a UI issue. Tab text for unselected tabs is not displayed. Here is the screenshot:

### Affected Page

https://contribute.freecodecamp.org

### Steps to Reproduce

**Visit these pages -** 
https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=configuring-dependencies
https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=step-3-start-mongodb-and-seed-the-database

Other pages using this _Common Component_ may also experience this issue. Consider checking those pages as well.

### Expected behavior

The text must appear for Tab either it is selected or not

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/118912986/47ce3b0c-0b1f-46fc-a68d-d4ca8418f08c)

### System

- Device: Laptop
- OS: Windows 10 Version 22H2
- Browser: Chrome 118

**Comment by januslinhc** [comment]
Hi can i work for it for hacktoberfest?

**Comment by Chirag77302** [comment]
Hey @developer-gagandeep-singh , I would like to work on this issue. You can assign this to me.

**Comment by bbsmooth** [comment]
These tabs are also not implemented properly and thus accessibility is poor.

**Comment by M0hitReddy** [comment]
i guess "[https://contribute.freecodecamp.org/](https://contribute.freecodecamp.org/)" this page is not open source.

**Comment by ieahleen** [comment]
> i guess "https://contribute.freecodecamp.org/" this page is not open source.

@M0hitReddy I guess you have not read the contributing guidelines then... it's open source, created with docsify from the `./docs` folder.

I wonder if it is a docsify issue or a markdown issue

**Comment by ieahleen** [comment]
The section in the code is
```
<!-- tabs:start -->

#### **macOS/Linux**

\```console
cp sample.env .env
\```

#### **Windows**

\```console
copy sample.env .env
\```

<!-- tabs:end -->
```

and the documentation from the docsify-tabs plugin we are using https://jhildenbiddle.github.io/docsify-tabs/

there may be something to adjust somewhere

**Comment by bbsmooth** [comment]
Well, good to know that the tabs implementation in their documentation is not implemented correctly either. At least we know that it's not something we are doing :slightly_smiling_face:

**Comment by ieahleen** [comment]
Oh, so it is to report a bug to them! On the documentation I see it correctly tho.

Oh, at this point then we should remove all the customization from the html file and the link to the script and rework the sections to not be tabs but just show the options one after the other

**Comment by M0hitReddy** [comment]
> > i guess "https://contribute.freecodecamp.org/" this page is not open source.
> 
> @M0hitReddy I guess you have not read the contributing guidelines then... it's open source, created with docsify from the `./docs` folder.
> 
> I wonder if it is a docsify issue or a markdown issue

My bad !  I did not know about docsify

**Comment by M0hitReddy** [comment]
> The section in the code is
> 
> ```
> 
> 
> #### **macOS/Linux**
> 
> \```console
> cp sample.env .env
> \```
> 
> #### **Windows**
> 
> \```console
> copy sample.env .env
> \```
> 
> 
> ```
> 
> and the documentation from the docsify-tabs plugin we are using https://jhildenbiddle.github.io/docsify-tabs/
> 
> there may be something to adjust somewhere

Well My bad ! I did not know about docsify.

**Comment by developer-gagandeep-singh** [comment]
These are **working fine in Dark Mode**.I think the problem is only in light mode.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/118912986/c69b653d-e11d-4f84-9dd6-c79292786264)

**Switching to dark mode :-**
Click the top-left **Bulb icon** to switch between dark/light modes.

**Comment by mughalmuneeb786** [comment]
@developer-gagandeep-singh I just found the fix let me update by pull request .

**Comment by ShaunSHamilton** [comment]
> For the minimal amount of information that tabs are being used for, I would suggest that we stop using them.

@bbsmooth Would a table be decent for this info? I am not sure how accessible Markdown tables are, but I would assume for something simple they just work.

**Comment by bbsmooth** [comment]
@ShaunSHamilton We could probably make a table work but I'm not sure it is needed and might just add more overhead than is needed for screen reader users. I think just making each tab a sub-heading with the content below is the best approach.

**Comment by ShaunSHamilton** [comment]
Something I forgot: We no longer support native Windows development of this repo. So, having a few specific commands for it in the docs is unnecessary, if not misleading.

In that case, let us fix this by splitting the current tabs into just the applicable command/info.

All the files needing changed are in this repository under the `docs/` folder. Search for any uses of Docsify Tabs, and replace them with just the information related to Linux.

---

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by Amit-Morade** [comment]
Can I work on it?

**Comment by trana5197** [comment]
Hi @ShaunSHamilton , Is this issue still up for grabs? I would like to contribute to it. Thank you. Awaiting your reply.

**Comment by lakshmi930** [comment]
Hi, is this issue still up for grabs?

**Comment by ieahleen** [comment]
An issue with the [first timers only](https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only) Open for anyone doing contributions for first time. You do not need permission to work on these.label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

Please read the issue well, including all the comments in the thread, so you are sure what needs to be done: @januslinhc @Chirag77302 @M0hitReddy @mughalmuneeb786 @nandirb @Amit-Morade @trana5197 @lakshmi930

**Comment by lasjorg** [comment]
@ShaunSHamilton What about the mobile app? There is no mention of it not supporting Windows in the initial "Attention" section or in the README. It does mention WSL2 in the Troubleshooting section.

Anyway, all there is in the tabs are copy commands. So maybe they do not need to be tabs.

https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-mobile-app-locally

https://github.com/freeCodeCamp/mobile/blob/main/README.md

**Comment by ShaunSHamilton** [comment]
@lasjorg 
> What about the mobile app?

I forgot those docs were here as well. @Sembauke @Nirajn2311 Does the mobile repo support Windows development?

**Comment by Nirajn2311** [comment]
Yes the mobile app support development in Windows

**Comment by trana5197** [comment]
@ieahleen @ShaunSHamilton  I have read the contribution guidelines and code of conduct. Still, I am not able to understand how to start the server locally or on gitpod. Can you please help me out as this is my first contribution. Thank you!

**Comment by ieahleen** [comment]
@trana5197 I suggest reaching out on the forum or discord server for better flow of comunication, so that here can stay focused on discussing the issue

**Comment by 5enox** [comment]
Just Use
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/146219543/b823024f-d2c7-4a4b-964a-81321e05e71a)

`--docsifytabs-tab-color             : #404040;`

as the color of The Text not selected is set to white it's not visible changing it to like dark grey will fix the issue, but will have to add fix to every tab , sorry if any issues come up it's my first time contributing

**Comment by lasjorg** [comment]
This is not just about the styles anymore.

The tabs fail on the accessibility front and because they are (mainly) used to document commands for non-supported OSs we are removing them.

As for the few copy commands left on the mobile app docs I assume we can just replace the tabs with something else.

**Comment by sabasyedcodes** [comment]
I would like to contribute to this issue. This is my first open source contribution ! Excited  Haha
