### ISSUE TITLE
Spacing breaking test:  Learn HTML by Building a Cat Photo App - Step 12

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#51961]
### Describe the Issue

A camper managed to fail the challenge despite having a close enough correct solution for the challenge. It even displays correctly in the browser. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-13

### Your code

```
<p>See more <a href="https://freecatphotoapp.com">  cat photos </a> in our gallery.</p
```

### Expected behavior

I do not believe the tests should be failing if there are spaces around the words "cat photos" in the anchor element.  The user should be proceeding to another challenge. 

### System

- Device: Desktop 
- OS: Windows 10
- Browser: FireFox
- Version: 118.0.2

**Comment by jeremylt** [comment]
I think here we should actually expect correct whitespace.

**Comment by bbsmooth** [comment]
They shouldn't be messing with that `p` element in the first place in step 13. I think step 12 is more relevant for this issue.

And yes, a lot of people add extra spaces in the link text and get bit by this. This was mentioned in issue #49023 and I think the consensus is that a test should be added specifically to check for the extra white space.

I would normally agree that extra white space should not be an issue and the tests should not be so strict about it. But for link text I can see the reasoning. If you add extra white space after "photos" then you will see the underline on the link extend past the word "photos" into the white space after the word. This is one of those few instances where white space actually does make a difference.

**Comment by renurao1306** [comment]
Hey, I am a first-timer and I would like to solve this issue

**Comment by jeremylt** [comment]
Please read our contributing guide. This issue is not marked as ready for contributions and we do not assign issues.

**Comment by Yash-Ambekar** [comment]
@jeremylt There is a test where the user is prompted for typos. So instead of writing a test for just detecting whitespaces can't we just mention to avoid whitespaces in that prompt? 

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/96481913/392d1480-c3ad-4c64-8589-c7e2aec0d087)

**Comment by jeremylt** [comment]
I think it would probably be better to mention whitespace separately since it's early in the curriculum

**Comment by Yash-Ambekar** [comment]
@jeremylt Sorry if I am wrong about this but do you mean we should make the test less strict and allow whitespaces?

**Comment by jeremylt** [comment]
> I think here we should actually expect correct whitespace.

Nope. I think we should check whitespace and spelling separately.

**Comment by Yash-Ambekar** [comment]
> > I think here we should actually expect correct whitespace.
> 
> Nope. I think we should check whitespace and typos separately.

Does this work then?

----------------------------------------------------------------------------------------
The link's text should be `cat photos`. You have either added whitespaces before or after the text

```javascript
const nestedAnchor = $('p > a')[0];
const hasWhiteSpaceBeforeCat = /^\s+/.test(nestedAnchor );
const hasWhiteSpaceAfterPhotos = /\s+$/.test(nestedAnchor );
assert(
  hasWhiteSpaceBeforeCat || hasWhiteSpaceAfterPhotos
);```

**Comment by jeremylt** [comment]
The test for the p element content probably also needs an adjustment to be agnostic to whitespace? And then this test for whitespace would follow?

**Comment by Yash-Ambekar** [comment]
@jeremylt This regex pattern `/^(\S+\s\S+)+$/` tests true for sentences with single whitespace between words and no whitespaces before and after the starting and ending word respectively. You can try below code for verifying that
```javascript
function testWhiteSpaces(inputString) {

  const pattern = /^(\S+\s\S+)+$/;

  const result = pattern.test(inputString);

  return result;
}

console.log(testWhiteSpaces(' Extra white spaces '))
console.log(testWhiteSpaces('Extra  white  spaces'))
console.log(testWhiteSpaces('Extra white spaces'))

So I can write a single test to verify if there are no extra whitespaces between words and no whitespaces before and after the first and last word.

**Comment by jeremylt** [comment]
> The test for the p element content probably also needs an adjustment to be agnostic to whitespace? And then this test for whitespace would follow?

I'm talking about modifying the *current* test that checks for*both* typos and spaces at the same time.

**Comment by Yash-Ambekar** [comment]
> > The test for the p element content probably also needs an adjustment to be agnostic to whitespace? And then this test for whitespace would follow?
> 
> I'm talking about modifying the _current_ test that checks for_both_ typos and spaces at the same time.

This is the current test for only typos written in the source.

-----------------------------------------------------------------------------------
The link's text should be cat photos. You have either omitted the text or have a typo.

```javascript
const nestedAnchor = $('p > a')[0];
assert(
  nestedAnchor.innerText.toLowerCase().replace(/\s+/g, ' ') === 'cat photos'
);```

----------------------------------------------------------------------------------------

As far as I can understand you want this modification to the test right?

```javascript
const nestedAnchor = $('p > a')[0];
const pText = document.querySelector('p').innerText.toLowerCase(); //get the inner text which includes text inside anchor tag
const typoCheck = nestedAnchor.innerText.toLowerCase().replace(/\s+/g, ' ') === 'cat photos'; //checking for typos
const whiteSpacesCheck = /^(\S+\s\S+)+$/.test(pText);
assert(
  typoCheck || whiteSpacesCheck 
); //if either is false then it will fail
```

**Comment by jeremylt** [comment]
I'm saying that test needs to be two tests.

**Comment by Yash-Ambekar** [comment]
This is my last try at understanding the proposed solution.

I have three options of writing the test:
1. Simply telling the users to avoid whitespaces when the typo test fails and this text is prompted to the user 'The link's text should be cat photos. You have either omitted the text or have a typo or have extra whitespaces.' and not adding a new test.

2. Write separate tests for checking typos and whitespaces.

The link's text should be cat photos. You have either omitted the text or have a typo.
```js
const nestedAnchor = $('p > a')[0];
assert(
  nestedAnchor.innerText.toLowerCase().replace(/\s+/g, ' ') === 'cat photos'
);
``` 
**AND**
The link text seems to contain extra whitespaces.
```js
const pText = document.querySelector('p').innerText.toLowerCase(); //get the inner text which includes text inside anchor tag
const whiteSpacesCheck = /^(\S+\s\S+)+$/.test(pText);
assert(
  whiteSpacesCheck 
); 
```

3. Combine both the tests into one single test.
The link's text should be cat photos. You have either omitted the text or have a typo or have extra whitespaces.
```js
const nestedAnchor = $('p > a')[0];
const pText = document.querySelector('p').innerText.toLowerCase(); //get the inner text which includes text inside anchor tag
const typoCheck = nestedAnchor.innerText.toLowerCase().replace(/\s+/g, ' ') === 'cat photos'; //checking for typos
const whiteSpacesCheck = /^(\S+\s\S+)+$/.test(pText);
assert(
  typoCheck || whiteSpacesCheck 
); //if either is false then it will fail 
```

Please tell me which option solves the issue. If none of them are correct then please elaborate more on the proper solution I am unable to understand the proposed solution. Also sorry if this is causing you inconvenience.

**Comment by jeremylt** [comment]
Your option 2 is almost correct, but those two tests cannot be quite like that.

First we should check if the contents of the a element match the correct text *with or without spaces*. So ' cat photos ' or 'cat photos ' or '  cat photos  ' or 'cat photos' should all pass while 'foo bar' would not.

Then we should check if the contents of the a element are exactly 'cat photos'.

The tests have to be in order.

**Comment by a2937** [comment]
I found another challenge that deals with the same anchor and spacing issue. 

 https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-31

I'd like to try to come up with some regex myself for the tests. I'll add an additional comment with some ideas.

**Comment by a2937** [comment]
I was thinking a little something for the [latest one](https://github.com/freeCodeCamp/freeCodeCamp/curriculum\challenges\english\14-responsive-web-design-22\learn-html-forms-by-building-a-registration-form\60fab8367d35de04e5cb7929.md) I mentioned right before the last test

You should not have extra spaces around the `terms and conditions`.

```js
assert.notMatch('fieldset:nth-child(3) + label > input + a')?.textContent, /^\s+.*\s+$/);
```

**Comment by Yash-Ambekar** [comment]
@jeremylt Is this the correct way now?

The link's text should be cat photos. You have either omitted the text or have a typo.

```js
// checks for typo
const nestedAnchor = $('p > a')[0];
const innerText = nestedAnchor.innerText.toLowerCase();
assert(
	/^\s*cat photos\s*$/.test(innerText)
);
```

**NEXT TEST**

The link's text should be cat photos. You either have leading or ending whitespaces.

```js
//checks for whitespaces
const nestedAnchor = $('p > a')[0];
const innerText = nestedAnchor.innerText.toLowerCase();
assert(
	/^(\S+\s\S+)+$/.test(innerText)	
);
```

**Comment by jeremylt** [comment]
The second test doesn't need to be that complicated. It should match for the string literal without extra spaces.

**Comment by Yash-Ambekar** [comment]
> The second test doesn't need to be that complicated. It should match for the string literal without extra spaces.

yeah sorry I was too engrossed in learning regex xD
You can check the second test I have updated it.

**Comment by Yash-Ambekar** [comment]
@jeremylt should I raise a PR then? or is this issue not open for PRs?

**Comment by lasjorg** [comment]
I think the actual implementation details of the tests are better suited in a PR. I will open this up to contribution.

If other challenges need the same change we can collect them in this issue and make it more general.

---


An issue with the help wanted or first timers only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by AmineAouragh** [comment]
hey everyone i think that when it comes to whitespaces - the user includes whitespaces before or after or in both sides of the anchor text - if we want to ignore whitespaces i think a regex should just be included in the source code and replaces it with an empty string ''" like @Yash-Ambekar showed in a code earlier. So that wouldn't be a big issue later on. And about typos normally they shouldn't be allowed. Like if the user is supposed to type 'cat photos' and instead they type 'cat photo' that obviously shouldn't pass and they shouldn't be able to go to the next challenge until they enter the exact anchor text asked. Hope this was understandable.

**Comment by jeremylt** [comment]
I think we agreed above that we don't want to ignore the whitespaces

**Comment by AmineAouragh** [comment]
oh ok i get it

**Comment by Thebuilderekes** [comment]
I did the last instruction to delete the entire anchor element below the p element and it passed.
