### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue 

### ISSUE THREAD

**Issue by DoctorFactorial** [FreeCodeCamp/freecodecamp#520]
Solution produces results equal to those asserted but but fails same tests, below. Code to replicate included, below. 

assert(largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]).should.eql([9,35,97,1000000]));Cannot read property 'eql' of undefined

(largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]])).should.eql([5,27,39,1001]);Cannot read property 'eql' of undefined

function largestOfFour(arr) {
  maxArr = [];
  maxNum = 0;
  for (var x in arr) {
    for(var y in arr[x]) {
      if (arr[x][y] > maxNum) maxNum = arr[x][y]; 
    }
    maxArr.push(maxNum);
    maxNum = 0;
  }
  return maxArr;
}

**Comment by terakilobyte** [comment]
Fixed with a previous commit. Thanks for the heads up!
