### ISSUE TITLE
RWD curriculum registration form  - Incorrect pre-existing code in step 30

### ISSUE THREAD

**Issue by barla-x88** [freeCodeCamp/freeCodeCamp#52029]
### Describe the Issue

This step requires a person to add a checkbox to a form but there is already markup for a checkbox in pre-existing code.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-30

### Expected behavior

The pre-existing markup for the checkbox should not be there in pre-existing code.

### Screenshots

![bug_step30_Registration_Form](https://github.com/freeCodeCamp/freeCodeCamp/assets/79461537/86033257-5120-45da-8c0c-099ffa6b9846)

**Comment by shoaib-31** [comment]
![Screenshot from 2023-10-19 17-23-04](https://github.com/freeCodeCamp/freeCodeCamp/assets/103197883/bcdedce0-b510-4d08-93a2-eeb759a76d1b)
I have update the pre-written code. Hope it fixes the issue after getting merged.
