### ISSUE TITLE
Incorrect information in “Learn Network Architecture Basics for Beginners” news article

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52037]
### Describe the Issue

What the address spaces consist of is wrong in this article.

> IP version 4 is the most widely used IP address format and consists of four 32-bit numbers separated by dots.

> IP version 6 is the latest IP address format, which uses eight 128-bit numbers separated by colons.

### Affected Page

https://www.freecodecamp.org/news/network-architecture-basics/

### Steps to Reproduce

Read?

### Recommended fix or suggestions

IPv4 uses a 32-bit address space consisting of four 8-bit octets. IPv4 is written in a decimal notation where each octet is separated by a dot.

IPv6 uses a 128-bit address space consisting of eight 16-bit segment/quartet. IPv6 is written in hexadecimal notation, separated into eight groups of 16-bits by the colons.

---

Long time since I took my CCNA and I'm no expert so please correct it as needed.

https://www.redhat.com/sysadmin/what-you-need-know-about-ipv6

https://datatracker.ietf.org/doc/html/rfc791

https://datatracker.ietf.org/doc/html/rfc4291

---

Edit: forgot the forum post that reported this.

https://forum.freecodecamp.org/t/incorrect-information-in-learn-network-architecture-basics-for-beginners-article/645554

**Comment by nikita812** [comment]
can I work on this

**Comment by olandodeflexy** [comment]
@lasjorg I would like to work on this.

**Comment by jdwilkin4** [comment]
Hi @olandodeflexy and @nikita812 ! 

Issues for the news publication are only worked on by the staff.
To learn more about how to contribute to freeCodCamp, please read through the contributing docs here 
https://contribute.freecodecamp.org/#/

**Comment by jdwilkin4** [comment]
Hey @lasjorg ! 

Thanks for creating this issue.
I have reported it to the editorial team 👍 

I am also going to cc @scissorsneedfoodtoo on this too 👍

**Comment by olandodeflexy** [comment]
> Hi @olandodeflexy and @nikita812 !
> 
> Issues for the news publication are only worked on by the staff. To learn more about how to contribute to freeCodCamp, please read through the contributing docs here https://contribute.freecodecamp.org/#/

Thanks @jdwilkin4 for the clarification. I will do that.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this issue, @lasjorg, and for your helpful suggestions.

I used your suggestions as a base to fix the text in the article. The fixes should go live within the next few hours.

Please let us know if you notice any other issues in this or other articles.
