### ISSUE TITLE
the search result links hide when you hover over them in dark mode

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#52043]
**Describe the bug**
if you type something in searchbar while using the dark mode, and hover over the produced links, it will hide the link.

**To Reproduce**
1. Go to 'https://contribute.freecodecamp.org/#/index'
2. Search something
3. Hover over it
4. See how the hover is hiding the result

**Screenshots**
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/88248797/74af1cba-d221-4ad4-8270-1fd48c28dff9)

 - Browser: chrome

**Comment by YKS113** [comment]
Can you please assign this to me

**Comment by RitzyKingS** [comment]
Hi there! 😊

I've been looking into the issue you reported regarding dark mode and hover behavior on the search results. I'd like to contribute a fix, but I'm having trouble locating the exact code or files that need modification. 🤔

Could you please provide more specific details about the file or code that's related to this issue? A direct link to the relevant code or even just the file path would be immensely helpful.

Your guidance would ensure that I'm making the correct changes to address this problem effectively. 🚀

Thank you! 🙌
