### ISSUE TITLE
Tests for Cat Painting step 3 are too strict regarding attribute order

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#52057]
### Describe the Issue

The tests fail when the `href` attribute is placed before the `rel` attribute in the `link` tag. The tests pass when you reverse it and place the `rel` attribute before the `href` attribute.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/step-3

### Your code

This fails but should pass:

```
<link href="./styles.css" rel="stylesheet">
```

### Expected behavior

Update tests to accept attributes in either order.

### System

N/A

**Comment by JamesCartar** [comment]
I want to contribute to this issue. This is the my first time, actually.

**Comment by lasjorg** [comment]
Agree, the attribute order shouldn't matter. I will open this up to contribution.

---

An issue with the help wanted or first timers only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
