### ISSUE TITLE
Add vertical scroll arrows to monaco editor

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#52067]
### Is your feature request related to a problem? Please describe.

Currently we are suppressing the up/down scroll arrows that the monaco editor provides:

```
scrollbar: {
      horizontal: 'hidden',
      vertical: 'visible',
      verticalHasArrows: false,
      useShadows: false,
      verticalScrollbarSize: getScrollbarWidth()
    },
```

WCAG 2.2 [SC 2.5.7](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html) now requires that any dragging movements must have an alternative "single pointer" option that allows the user to perform the same functionality as dragging would allow but with only having to use a single pointer input (such as an "arrow" button in this case). 

There is an exception to SC 2.5.7 if the dragging mechanism is provided by the browser itself and not modified in any way. But the monaco editor implements its own scrolling mechanism and does not rely on the browser to provide scrolling, so this exception does not apply.

An argument could be made that the user is currently able to single click on the scroll gutter either above or below the visible scrolling cursor which allows the editor to scroll with a single click. I would argue that this is very close to replacing the dragging movement of the scroll bar except that it does not allow for the finer granularity of scrolling to a precise location in the editor (i.e. the jumps it makes can be very big).

But really, we should just do this regardless of what WCAG requires because it has the potential to help people who have trouble with dragging movements.

### Describe the solution you'd like

I can think of two approaches here:

1. Enable the arrow buttons to always show in the editor
2. Allow the user to turn on the arrow buttons as needed. How exactly this would be done can be decided below.

Another related new WCAG requirement is [SC 2.5.8 Target Size](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html) which requires that the minimum size for a pointer input is `24x24px`. Since the user has the ability to set the width of the scroll bar to `25px` and the default arrow buttons provided by monaco are the same width as the scroll bar, we are good as far as width is concerned. But my testing with the scroll arrows turned on shows that the height of the arrow button does not match the width at `25px` (it is significantly smaller), and thus we would need to do some extra work to make sure the height of the button was also `25px`.

I am happy to work on this, I just need to know which approach we want to take and if it is the second one, how we want to implement it.

### Describe alternatives you've considered

I'm not sure I can think of any at this time. Scrolling seems like an integral part of the editor and there is probably not a solution we would accept that would allow us to get rid of it.

**Comment by ShaunSHamilton** [comment]
Just because my memory is bad: Why do we have scrolled content at all in "accessibility mode"?

Specifically, why do we not _just_ wrap any content that would otherwise cause a scrollbar - avoiding the issue 🤫 

---

Otherwise, I am in favour of the simpler approach of having the arrow buttons always visible.

**Comment by bbsmooth** [comment]
> why do we not _just_ wrap any content that would otherwise cause a scrollbar - avoiding the issue

The scroll bar I am referring to in this issue is the vertical scrollbar on the right-hand side of the editor, which is there in almost every step for everyone.

In regards to accessibility mode, that prevents lines of code from wrapping in the editor on purpose so that the are easier to work with when using a screen reader. But even when accessibility mode is activated, monaco does not display a horizontal scroll bar on the editor.

**Comment by ShaunSHamilton** [comment]
> I am referring to in this issue is the vertical scrollbar on the right-hand side of the editor,

Sorry. My brain completely skipped the word "vertical".
In that case:
> I am in favour of the simpler approach of having the arrow buttons always visible.

**Comment by Dhruvabhat24** [comment]
Can you assign it to me I will try my best to do 
This will be my first attempt towards open source contribution
