### ISSUE TITLE
Typo: responsive-web-design step-28

### ISSUE THREAD

**Issue by AceTylerCholine** [freeCodeCamp/freeCodeCamp#52079]
### Describe the Issue

On step 28 of the Responsive Web Design module there is a minor typo in the instructions. The first sentence of the instructions is: _Currently when someone **submit** the form, they can submit it without checking the radio inputs._

The word submit should be replaced with submit**s**.

This is the absolute smallest of typos, but I wanted to help make this masterpiece of a website one-step closer to perfect.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-28

### Your code

```



```

### Expected behavior

On step 28 of the Responsive Web Design module there is a minor typo in the instructions. The first sentence of the instructions is: _Currently when someone **submit** the form, they can submit it without checking the radio inputs._

The word submit should be replaced with submit**s**.

This is the absolute smallest of typos, but I wanted to help make this masterpiece of a website one-step closer to perfect.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bbsmooth** [comment]
Hey @AceTylerCholine, welcome to fCC.

For small typos like this, you don't even need to open an issue, you can just submit a PR directly if you like. This is mentioned in the [Contributor FAQ](https://contribute.freecodecamp.org/#/FAQ?id=i-found-a-typo-should-i-report-an-issue-before-i-can-make-a-pull-request).

**Comment by AceTylerCholine** [comment]
Thank you @bbsmooth
