### ISSUE TITLE
Learn: profile icon isn't centered in nav

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52083]
### Describe the Issue

The profile icon in the nav isn't centered within it's border.

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/
2. Sign in if you aren't
3. Look at profile icon at the top right - see that it isn't centered

### Expected behavior

It to be centered

### Screenshots

![Screen Shot 2023-10-24 at 4 34 56 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/92b0fb3d-051d-4fe5-a735-c4c8a2d434ff)

^ See problem - the icon has too much space at the top

I opened the devtools and played around for a quick second. Removing the line-height added by bootstrap fixed the issue:

<img width="471" alt="Screen Shot 2023-10-24 at 4 35 21 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/e8e2d355-6bb8-4ddc-9f33-216f1957d518">

### System

I only gave this a quick test on firefox.

**Comment by bbsmooth** [comment]
I just noticed that I'm seeing a blue border around my avatar. Has it always been like this? It's the same color as the keyboard focus outline. Technically, it is not a WCAG failure, but it might be nice if we used a different border color.

**Comment by moT01** [comment]
Blue is a top contributor - [it's been like that for quite a while.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/helpers/border-color-picker.ts)

**Comment by bbsmooth** [comment]
Thanks for that @moT01. I had no idea that the blue border meant something. Do we have that documented anywhere so that people know what those colors mean?

**Comment by NormanEWright** [comment]
After checking, I'm seeing a gold border.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/16324702/1fea1b3d-2e6d-48b9-82cb-d6d925f036b8)
Removing the line-height (set to 0) on the .avatar-nav-link centers the profile image.

**Comment by moT01** [comment]
> Do we have that documented anywhere so that people know what those colors mean?

I don't believe we have anything that tells people what the colors mean @bbsmooth. Do you want to create a separate issue about that? I think it could use some discussion and we should probably find a way to convey that info to campers. It may give some incentive to contribute or donate.

**Comment by ahmaxed** [comment]
Although the donors see the following message after a successful payment, The colors are not communicated explicitly anywhere. 

<img width="636" alt="Screenshot 2023-10-26 at 3 46 16 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/39586bce-9cb1-4b8d-8fcb-a2b3578b56f4">
