### ISSUE TITLE
Conveying the meaning of the colored borders around the profile icon link

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#52102]
### Is your feature request related to a problem? Please describe.

Recently (as in yesterday) I discovered that the blue border around my profile icon link in the header actually meant something, in this case that I was a top contributor. I had no idea that this blue border was intended to convey that message. I thought everyone's profile link had that color and I was about to create a PR to change it since it's the same color as the keyboard focus indicator.

In [issue #52083](https://github.com/freeCodeCamp/freeCodeCamp/issues/52083#issuecomment-1778257170) @moT01 pointed out that not only is there blue for top contributors, but also gold if you have donated, and purple if you have both donated and are a top contributor. I asked if we had this information available anywhere so people who have those colored borders would know why and the consensus was probably not.

So I'm opening this issue to discuss the following:

1) Is it important that we convey the significance of the colored borders, not only to people who have them but perhaps to all users as a way to incentivize contributions and donations?
2) If yes, how do we do that?

### Describe the solution you'd like

To be determined...

### Describe alternatives you've considered

N/A

**Comment by ahmaxed** [comment]
So we have 4 border colors:
1- default: some shade of gray
2- donor: gold
3- top-contributor: blue
4- top-contributor + donor: violet

Yes we should communicate it to everyone, but it is easier to do it when users get a new border. 
The donors are informed about the border and asked to contact support if they don't see it on their profile.
The top contributors could also be informed through the annual top contributor announcement email or article.

How to Use the Website page might be a good temporary place to explain these for everyone.

In general, we would need a more robust badging system where users can get recognition based on their contribution to the community and see the available options.
