### ISSUE TITLE
[UI Components] Styling issues in Button component

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52115]
### Describe the Issue

I found the following issues in the `ui-components`'s Button component:

| Issue | Screenshot |
| --- | --- |
| Button has incorrect border style | <img width="349" alt="Screenshot 2023-10-26 at 11 48 43" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/ecb85481-9aab-4bce-b9d1-96580f34f95a"> |
| Button link (a link that looks exactly like a button) doesn't have a border | <img width="749" alt="Screenshot 2023-10-26 at 11 46 38" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/0ac81ac1-6dfe-45d9-ae3a-eb5fd5c22f09"> |
| Download link is not rendered correctly on Storybook | <img width="775" alt="Screenshot 2023-10-26 at 11 44 53" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/cb3295ab-5d55-488b-8116-1599907d8853"> |
| Disabled button has a focus outline on click | <img width="229" alt="Screenshot 2023-10-26 at 14 33 31" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/1c9885e5-81a6-4db9-aa86-c5c6735031d2"> |

### Affected Page

Currently only on Storybook

**Comment by Tabindanoor** [comment]
I want to contribute in it.. 
kindly let me

**Comment by lucifer100201** [comment]
I want to contribute in it..
kindly let me work on this issue
