### ISSUE TITLE
Center Flash Message for Better Alignment

### ISSUE THREAD

**Issue by JeevaRamanathan** [freeCodeCamp/freeCodeCamp#52123]
### Describe the Issue

Current Behavior:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/64531160/0286e384-6264-42d7-8e4a-aef986dc42fc)

The flash message is currently aligned in a way that leaves unnecessary space around the close icon, making it look unbalanced and less visually appealing.

### Affected Page

NA

### Steps to Reproduce

NA

### Expected behavior

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/64531160/4f414657-cf3b-4ebc-a3df-db79cd7a64e2)

It would be better to center the flash message for improved alignment and visual appeal. 

### System

- Device: [Laptop]
- Browser: [Chrome]

### Additional context

I'm willing to work on this issue.

**Comment by hamzamehmood67** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by moT01** [comment]
I don't think we want this centered. Some previous discussion on this issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/44835
