### ISSUE TITLE
Standardize the English spelling we use in our curriculum and documentation

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52136]
### Describe the Issue

This issue came from https://github.com/freeCodeCamp/freeCodeCamp/pull/52120#discussion_r1373357971, where we found that we are using "labeled" (American English) and "labelled" (British English) interchangeably in our curriculum. 

I have always assumed that freeCodeCamp uses American English, but I don't think we have communicated this isn't explicitly.

### Affected Page

https://contribute.freecodecamp.org and https://www.freecodecamp.org/learn/

### Steps to Reproduce

N/A

### Recommended fix or suggestions

- Clarify which English spelling we use in user-facing and contributor-facing content
- Mention the official English variant in the following guides:
  - https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges
  - https://contribute.freecodecamp.org/#/how-to-work-on-the-docs-theme?id=work-on-the-content-of-the-docs
- Update the spelling of "labelled" in the curriculum files following the chosen English variant, as pointed out in https://github.com/freeCodeCamp/freeCodeCamp/pull/52120#discussion_r1373357971. (The other standardization / spelling changes can be done opportunistically)

**Comment by ojeytonwilliams** [comment]
> I have always assumed that freeCodeCamp uses American English

That's correct. I thought we did spell that out somewhere, but apparently not. Thanks for raising the issue, @huyenltnguyen.

**Comment by Sembauke** [comment]
https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges - we should probably add it in this section of the contribution docs ([Challenge descriptions/instructions](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=challenge-descriptionsinstructions))

**Comment by jeremylt** [comment]
Thanks for the issue - I agree it should be added to the docs in the Challenge descriptions part and we should scrub for labelled vs labeled in the user facing text. The second is probably a good beginner friendly PR.

**Comment by rtallarr** [comment]
sent my first pr #52231 , any comments or help is appreciated
