### ISSUE TITLE
JS Key Value Pair Challenge - Valid Solution Fails

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52186]
### Describe the Issue

This solution code should pass but doesn't.

Also, we should update the seed code to use `const` instead of `let`.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/add-key-value-pairs-to-javascript-objects

### Your code

```javascript
const newFoods = {
  bananas: 13,
  grapes: 35,
  strawberries: 27
}

Object.keys(newFoods)
  .forEach(food => foods[food] = newFoods[food]);
```

### Expected behavior

Valid code should pass.

### System

All

**Comment by lasjorg** [comment]
I guess the regex has to be scoped to the `foods` object.

`Object.assign` doesn't work either for the same reason.

```
Object.assign(foods, newFoods);
```


Tests: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/add-key-value-pairs-to-javascript-objects.md

**Comment by jeremylt** [comment]
That sounds right, though I'm no regex wizard so I'm probably not the best person to puzzle out how to write that regex.

Though maybe it doesn't have to be that fancy - we should check that the entire object literal should be left as given, right?

**Comment by lasjorg** [comment]
> we should check that the entire object literal should be left as given, right?

Correct.

The assert message should probably be changed as well as we do not care if the properties are "set using dot or bracket notation".

> Do not add properties directly to the `foods` object.

Or something like that.

**Comment by lasjorg** [comment]
An issue with the help wanted or first timers only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by sarahcode2112** [comment]
Hi jeremylt and lasjorg, thank you for pointing out this issue and discussing possible solutions :)

I am working on a [draft PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/52302) to fix this issue. (First PR in the codebase!) 

I am troubleshooting some problems with setting up FreeCodeCamp, to test my changes. I will mark the draft PR as 'ready for review' after I successfully run the app and test the changes.

**Comment by sarahcode2112** [comment]
Thank you jeremylt for reviewing the draft PR :)

I added your suggestion, fixed the regex, and tested the changes on GitPod. I have [marked the PR as 'ready for review'](https://github.com/freeCodeCamp/freeCodeCamp/pull/52302). I left a comment on the PR about one tiny concern with the regex.
