### ISSUE TITLE
False positive on Cafe Menu step 73

### ISSUE THREAD

**Issue by avelican** [freeCodeCamp/freeCodeCamp#52181]
### Describe the Issue

False positive on Cafe Menu step 73:

```
.item p {
  display: inline-block;
  margin:5px;
}
```

Causes the test to pass, but it's wrong, since it breaks the layout (by also adding a 5px margin to each side).

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-73

### Your code

```
.item p {
  display: inline-block;
  margin:5px;
}
```

### Expected behavior

Test should fail

### System

- Device: Laptop
- OS: Windows 10
- Browser: Brave
- Version: 1.59.124 (Chromium 118.0.5993.117)

**Comment by ieahleen** [comment]
the tests check only `margin-top` and `margin-bottom`, but to check that `margin-right` and `margin-left` have not changed, how could we do?
if using, only `margin`, it should be `margin: 5px 0 5px 0` probably. We can check that the `margin-right` and `margin-left` are 0, anything above 0 breaks the layout.

**Proposal**: Maybe a test saying to not change `margin-right` and `margin-left`?
