### ISSUE TITLE
Typo in "How to Write for freeCodeCamp News" article

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52180]
### Describe the Issue

There is a missing space in the article:

> This helps the freeCodeCampEditorial team learn about your writing style, what you like to write about, and whether you'd be a good fit for the publication.

### Affected Page

https://www.freecodecamp.org/news/how-to-write-for-freecodecamp/

### Steps to Reproduce

N/A

### Recommended fix or suggestions

Add a space between "freeCodeCamp" and "Editorial".

### Screenshots

<img width="746" alt="Screenshot 2023-10-31 at 00 57 11" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/f9eadbfd-919f-4da9-9119-3d112fa2e5d5">

**Comment by iemafzalhassan** [comment]
Hi, I would like to work on this.

**Comment by VaibhavSharma24** [comment]
@huyenltnguyen Are you working on this issue ?

**Comment by patryk77k** [comment]
@huyenltnguyen can you assign me to this issue?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching this @huyenltnguyen. I just fixed this typo, and the update should go live within a few hours after the next build.

Please let us know if you notice other issues in this or any other articles.
