### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue 

### ISSUE THREAD

**Issue by mdanro** [FreeCodeCamp/freecodecamp#522]
Please tell us in detail here how we can make this challenge better.
The completion is inverted, completing the anchor will highlight the adress and completing the anchor adress will highlight as done the anchor text

**Comment by QuincyLarson** [comment]
Thank you for bringing this to our attention. We've now fixed this!
