### ISSUE TITLE
The devcontainer.json in the repository cannot be built because the Dockerfile cannot be built.

### ISSUE THREAD

**Issue by trukhinyuri** [freeCodeCamp/freeCodeCamp#52211]
### Describe the Issue

The devcontainer.json in the repository cannot be built because the Dockerfile cannot be built.
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.devcontainer/Dockerfile

### Affected Page

The devcontainer.json in the repository cannot be built because the Dockerfile cannot be built. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.devcontainer/Dockerfile

### Your code

The devcontainer.json in the repository cannot be built because the Dockerfile cannot be built.
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.devcontainer/Dockerfile

### Expected behavior

The devcontainer.json in the repository cannot be built because the Dockerfile cannot be built.
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.devcontainer/Dockerfile

### Screenshots

The devcontainer.json in the repository cannot be built because the Dockerfile cannot be built.
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/.devcontainer/Dockerfile

### System

IntelliJ IDEA 2023.3

### Additional context

The devcontainer.json in the repository cannot be built because the Dockerfile cannot be built.

**Comment by ShaunSHamilton** [comment]
Hello there,

I can start a codespace without any problems. It just takes a while because we are still using the old way of installing Nodejs.

As such, I am closing this issue, unless more information can be provided to reopen.
