### ISSUE TITLE
platform gamification for motivation

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52210]
### Is your feature request related to a problem? Please describe.

To help motivate Campers to continue learning, it could be beneficial adding more auxiliary content/challenges to the platform.

Specifically, extending the current _streak_ implementation to encourage steady learning.

### Describe the solution you'd like

Some example ideas:

1. Redoing lessons (probably after a certain amount of time has passed) could count towards another point in the streak
  - https://forum.freecodecamp.org/t/it-would-be-better-if-redoing-exercises-would-count-towards-coding-streaks/646726
2. We could revisit the "badges" implementation to award badges for completing "challenges" (e.g. Reach 100 day streak)

### Describe alternatives you've considered

We have often discussed overhauling the current profile page to be more useful. This possibly plays into that.

**Comment by ahmaxed** [comment]
Thanks for bringing this up. There is a lot we could gamify, but the streak seems to be the most effective.

Streak:
Based on our previous discussions, it seemed like our current streak implementation lacks precision in that it does not take  time zones into account. 
Making the streaks more precise might be a good starting point. 
We could expand this feature by adding redoing previous challenges or making progress on projects.
Once that is done, we could introduce milestone badges. 

Badges:
Is pulling the discourse api for badges still on the table?

We could devote an issue to discuss the requirements of each gamification feature as well.

**Comment by ShaunSHamilton** [comment]
> Is pulling the discourse api for badges still on the table?

100%. https://github.com/freeCodeCamp/freeCodeCamp/pull/43168 my last impl worked, but I am sure it would be even easier to impl now that I understand more.

**Comment by jeremylt** [comment]
I think overall revamping and expanding the gamification is a good idea. But I'm not wild on encouraging repeating the easier content since that's a common trap/procrastination strategy for new learners. Maybe a simple limit like you can only repeat a lesson once for it to count towards the streak?

**Comment by ShaunSHamilton** [comment]
> Maybe a simple limit like you can only repeat a lesson once for it to count towards the streak?

Either this or a limit of repeat once every year.

**Comment by moT01** [comment]
What about different values (xp) for different challenges. Many challenges are kind of easy -> 1 point. Euler challenges and cert projects take some time -> many points.

**Comment by ahmaxed** [comment]
We could introduce badges for each cert and badges for meaningful progress in each of those.

**Comment by ShaunSHamilton** [comment]
In my opinion, there should not be a badge for each cert; the cert is basically a badge in itself.
I would have badges like: _Completed 5 certs_, _completed 10 practice projects_, _completed 100 lessons_, _completed 15 certification projects_
