### ISSUE TITLE
Create a multi-step "Ask for Help" form for all challenges

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#52223]
### Is your feature request related to a problem? Please describe.

It's a little frustrating when campers don't always give enough context for their issues and I need to manually insert their code to figure out what's going on. For a lot of them, they just leave the description as "Describe your issue in detail here.".  

### Proposal

At the minute the UX looks like so:

<details>
<summary>Screenshots of the current UI</summary>

<table>
<tr>
 <td>Step 1</td>
 <td>
  
<img width="639" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/ed2aaf61-661d-421d-9b22-f7a429aefe82">

 </td>
<tr>
 <td>Step 2</td>
 <td>

<img width="608" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/80123e39-f766-40a8-8c18-d56f1dd462bb">

 </td>
<tr>
 <td>Step 3</td>
 <td>
 
<img width="630" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/1884376/9e18b879-3eb8-4ec0-8a46-1a80c9b83d68">

 </td>
</table>

</details>

The current goal is to:

- Try and nudge users to attempt the challenge a few times before showing them the help button – **we should keep this**.
- Show an interstitial modal that should nudge them into 1) read-search-ask methods and 2) checking previous answers on the forum – this is mostly ignored if we are to be honest.
- Capture whatever information we can and create a post on the forum.

But users often do not fill out the details in the post for several reasons, which could be (not limited to) a daunting blob of text on the post, language barriers, or plainly out of getting tired of the UX.

We can improve this (as agreed by several mods in the comments below) by refactoring that Help Modal (the interstitial modal from Step 2 in the screenshots above) to a radically different UX.

*The idea is to teach HOW TO ASK GOOD QUESTIONS*

The user stories are:

- Try and nudge users to attempt the challenge a few times before showing them the help button – **we should keep this**.
- Get rid of the links for "read-search-ask" and "search-similar-posts" — users ignore this.
- Create a multi-step UI within the modal that incrementally teaches them the philosophy from the links:
  1. Copy and structure the verbiage from the "read-search-ask" and "see-similar-posts" into a checklist-style feature within the UI. This can be something they have to check off once, to confirm they understand the concept, thereby making it less in the face.
  2. Create a form that can be dynamic to each category of the challenges/lessons (superblocks) so that we capture the necessary information.
  3. Include additional details in the form that the users **have to fill**, which could vary based on the superblock.
  4. Once the details are validated, create a post on the forum using the URI format.
  5. Bonus: list similar posts in the forum on the help modal using the discourse API.

---

<details>
<summary>Original Request</summary>

### Describe the solution you'd like

If we were to somehow run the tests before the "ask for help" page shows up, and send that information to the post along with the challenge id into the post template; it'd come populated . From there we wouldn't necessarily need them to edit the description, though additional context is always a blessing. 

### Describe alternatives you've considered

There is the always forcing users to change the text "Describe your issue in detail here." to something else but I'm sure at least one camper would just erase it or find a way to avoid discussing the problem. 

</details>

**Comment by raisedadead** [comment]
I can see where you are coming from, and this can be tricky with the URI & query param-based implementation we have right now.

Essentially, we need more robust "sanity" checking before posts are created.

That said, here is what I propose:

- We need to rebuild the ask for help feature so that it is a "form" as in a modal where the user has to enter all the information that we want them to.
- Can we collect additional information in the said modal such that the test run information and other things can be made available?
- We then leverage the same URI pattern we have been using to create the posts.

I will let some folks from @freeCodeCamp/moderators chime in and suggest what they think of this. But do know that there will be some R&D and experimentation (like code) involved before we can freeze the feature.

If it helps let's take this discussion on the forum (for easy of comments from more mods).

**Comment by ShaunSHamilton** [comment]
> We need to rebuild the ask for help feature so that it is a "form" as in a modal where the user has to enter all the information that we want them to.

This sounds like an excellent feature that I think would improve the HX (Help Experience) the most. So, I would start with this, and we can trial it before moving to collecting (inserting) more information.

One reason to not add more information is the URI can only carry so many characters. So, many more lessons would require Campers to copy-pasta their own code into the forum topic.

**Comment by jeremylt** [comment]
I think it would be very helpful to have a form interface where the users have to provide some context in order to make a forum post. I am not sure why its the case, but it certainly seems like the general quality of questions has gone down a bit since the new curriculum has rolled out, and I'm a bit worried that those students are missing out on developing some very important skills.

**Comment by moT01** [comment]
This is an issue with [the C# posts](https://forum.freecodecamp.org/c/c-sharp) as well. Most don't provide any details.

**Comment by raisedadead** [comment]
Thanks a lot for confirming everyone. I have updated the OP to reflect some ideas that came to my mind. We should move this into a "mock-up" phase. 

Will someone be interested in coming up with a mockup of the UI? 

We could then get some feedback from @huyenltnguyen @ahmaxed before moving forward with the code and discussing other aspects of the feature.

**Comment by lasjorg** [comment]
A form would be nice.

I'm sure even if we make parts required some people will fill in random text just to get the submission to go through. But what can you do, at least we tried.

Making the ask for help "bar" too high is also a concern. I'm all for teaching people how to ask better questions so they can get better answers. But if done too aggressively it can become a form of gatekeeping. It is easy for developers to lose track of just how hard everything was as a beginner.

**Comment by jeremylt** [comment]
I'd  be pretty happy just to not see `Describe your issue in detail here.` and to rarely see `It doesn't work` or `It broke`.

**Comment by ahmaxed** [comment]
Here is what I think could be included in the form:

- [ ] I have tried the [Read-Search-Ask](https://forum.freecodecamp.org/t/19514) method
- [ ] I searched for similar question that has [already been answered on the forum](https://forum.freecodecamp.org/search?q=learn-html-by-building-a-cat-photo-app%20-%20Step%2032).
- [ ] I will describe the issue in the forum post in details to help moderators assist me.

We can replace the last item with a text area if there is no substantial character limit. 

Once the form is full, we can activate the 'Create a help post on the forum' button.

Additionally, we could include an item that suggests priority for posts that have context to encourage users.

**Comment by naomi-lgbt** [comment]
> We can replace the last item with a text area if there is no substantial character limit.

The character limit, *including* our template and the camper's code, is 4096.

**Comment by jeremylt** [comment]
Honestly, we can probably cut back somewhat on the amount of code we send - maybe just 6 lines pre/post the editable region (or more if they changed a ton of code?)

**Comment by ahmaxed** [comment]
Let's move forward with the bullet points and the description box. We can optimize in the next iterations.
Here is my suggested text. Feel free to improve it. 

Fill out the following form to create a help forum post.

- [ ] I have tried the [Read-Search-Ask](https://forum.freecodecamp.org/t/19514) method
- [ ]  I searched for similar question that has [already been answered on the forum](https://forum.freecodecamp.org/search?q=learn-html-by-building-a-cat-photo-app%20-%20Step%2032).
Describe your issue in details:




For the description box we can enforce a minimum char count if necessary.

**Comment by jeremylt** [comment]
Do we anticipate people reading these checkboxes? People don't actually read the PR checkboxes

**Comment by lasjorg** [comment]
I suggest we start by giving people the benefit of the doubt.

You don't notice the people that do read the guidelines, you notice the people that didn't.

**Comment by jeremylt** [comment]
Sure, but let me put it another way. What does the checkboxes give us?

**Comment by lasjorg** [comment]
They should not have to ask questions they can find the answers for themselves and we shouldn't have to answer them if they can.

It is just a checklist to help them do that before posting to the forum. It doesn't even matter much to me how effective the list is, only that it is there to help if and when it can.

**Comment by naomi-lgbt** [comment]
I think the point isn't that people will read the checkboxes or not, I think the point is will the checkboxes be any more effective than the bright red alert?

<img width="442" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/50690685-dc95-4b80-9df4-217fe5c2c1bd">

**Comment by lasjorg** [comment]
Are you saying the modal isn't effective or that the checklist won't be as effective?

How effective does it have to be?

Do we have any actual analytics data about how effective it is?

Removing it can not possibly be more effective.

---

I mainly care that the information is there to help when it can.

**Comment by jeremylt** [comment]
I think the information should be there. I'm not sure that making the information a checkbox makes the engagement higher - click without thinking is sorta the problem with the current setup

**Comment by ShaunSHamilton** [comment]
We could add a manual CAPTCHA before they may post. E.g. _Answer this complicated question about programming to post on the forum_

**Comment by jeremylt** [comment]
Ha, a "do not check" box would be funny.

I suppose what I'm saying is that I don't think the checkbox makes anyone more likely to read, so why not just provide the information without a checkbox? Simpler is better.

**Comment by naomi-lgbt** [comment]
> why not just provide the information without a checkbox?
The argument there is that we are already doing this. And it's not effective.

Personally, I'm a fan of keeping the barrier of entry to getting help as low as possible.

**Comment by jeremylt** [comment]
I suspect it will be identically effective with or without checkboxes. I don't have a strong objection to including the checkboxes - I just think it adds visual complexity without changing user behavior. We can always try and see

**Comment by ArielLeslie** [comment]
> Personally, I'm a fan of keeping the barrier of entry to getting help as low as possible.

Maybe it's just me because I'm old and cranky, but the current pattern means that I am helping far fewer people than ever. I used to read every request for help topic on the forum. Now I flatly refuse to even open a single topic that has a title generated by the "Ask for help" button. Such a high percentage of them still say "Tell us what’s happening: Describe your issue in detail here.", that I've pretty much abandoned the forum. From my perspective, someone who isn't engaging with the process enough to form a sentence isn't getting help; they're just getting solutions which they can get from Googling if that's what they want.

**Comment by naomi-lgbt** [comment]
Oh absolutely. I just don't think adding checkboxes is the way to improve that.

**Comment by ArielLeslie** [comment]
I don't think a checkbox will change anything, but I actually would like to _add_ a barrier so that you can't spam the forum by just clicking (which a checkbox wouldn't do because they can just click through it).

I am not connected enough with the technical implementation to make helpful suggestions, but if I could just have my way, the modal would have a textbox with the "Tell us what's happening" prompt and a minimum length - similar to the forum's minimum length requirement but with something like "Please tell us more" as the validation text instead of revealing the character requirement.

**Comment by jeremylt** [comment]
Yeah, for user code, I think if they don't have changes outside of the editable region then we're probably safe to send only the editable region.

**Comment by ArielLeslie** [comment]
Fully implement Git and send a Diff instead of the code itself. 😆 
(I joke. That's actually what I do at work and its fuckin' hard.)

**Comment by ShaunSHamilton** [comment]
> Separately, is it possible to run a script that scans these posts and has camperbot post a message reminding the user on the etiquette

This can be easily done (example below):

<img width="603" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/83518fa5-d47b-48da-8e44-2b71a7720d1f">

**Comment by ShaunSHamilton** [comment]
What do we think about enabling such a feature (above)?

It is easy, and can be switched on/off as we see fit. The only thing is the wording of the reply:
> You appear to have created this post without editing the template. Please edit your post to **Tell us what’s happening**  in your own words.
> Learning to describe problems is hard, but it is an important part of learning how to code.
> Also, the more you say, the more we can help!

**Comment by naomi-lgbt** [comment]
I would honestly go that route before I'd build in a form.

**Comment by ArielLeslie** [comment]
If that's something we can do with the available tools, then I'm all for it.

**Comment by naomi-lgbt** [comment]
@ShaunSHamilton do you want to go ahead and set that up?

I think the verbiage you quoted is a sufficient starting point.

**Comment by ShaunSHamilton** [comment]
I have enabled that automation for just the `HTML-CSS` category. I will keep a close eye on it for the next few hours.

The main thing I can see being an issue is Campers **actually** taking the time to fill in the `Tell us what's happening` section, but _forgetting_ to remove the `Describe your issue...` line. In this case, the bot will still reply. I will see if there is a way to regex the input such that any additional info is treated as "filled in".

**Comment by ArielLeslie** [comment]
It seems to be well received: 
https://forum.freecodecamp.org/t/new-system-response/650936
![forum screeenshot](https://github.com/freeCodeCamp/freeCodeCamp/assets/6234475/1057e750-1053-4631-a239-a67ff331a9ed)

**Comment by jeremylt** [comment]
Unfortunately, this approach doesn't help with this sort of thing:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25011573/e9ae071b-d755-4b0b-9078-4dcb9926314a)
Though, I don't think there is a way to avoid a camper being determined to *not* ask a question.

---

I'm also worried that we may see more of this sort of thing
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25011573/1f25866e-c9fb-4191-ab2b-7a5b4eb08507)
Which is also fairly useless for anyone answering and avoids the entire point of getting the camper to form questions in their own words

**Comment by ArielLeslie** [comment]
You know me. I'm perfectly happy to just unlist those threads on the basis of being unproductive/spam.

**Comment by ieahleen** [comment]
We still need to keep in mind that the more characters are used in the template, the shorter the code that is copied over automatically and would need the user to copy and paste

**Comment by raisedadead** [comment]
I agree with Jeremy and others here. 

The checkboxes will not be of much help. We should focus on collecting the information we need as moderators/contributors in helping campers.

And be as friendly and accommodating as possible while trying to filter "low-effort" questions.

**Comment by TamiAharoni** [comment]
I'm eager to contribute
Can I join? please point me more specifically how can I help here?
