### ISSUE TITLE
Remove groups related sentence from footer

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#52259]
### Describe the Issue

Following sentence needs to be removed from all footers.

`We also have thousands of freeCodeCamp study groups around the world.`

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

Scroll down on non-challenge pages to see the footer.

### Requested Change

Adjust the the following paragraph:

`Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to the public. We also have thousands of freeCodeCamp study groups around the world.`

To:

`Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to the public. `

```[tasklist]
### Footers to be adjusted
- [x] Learn | https://github.com/freeCodeCamp/freeCodeCamp/pull/52283
- [ ] Forum
- [ ] News
```

```[tasklist]
### Tasks
```

**Comment by zoheballadin** [comment]
Can i work on this issue please? thank you

**Comment by ShaunSHamilton** [comment]
An issue with the  https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by tushar-droid** [comment]
Hey guys, just issued a pull request on the issue. Pretty fun working on my first open souce contribution hope it makes the cut. 
Cheers  : )

**Comment by raisedadead** [comment]
The footers on news and forum must be updated by a member of @freeCodeCamp/staff due to limitations on contributions and validations for the respective repo – out of scope for a first-timer.
