### ISSUE TITLE
Free Code Camp on The Changelog!

### ISSUE THREAD

**Issue by adamstac** [FreeCodeCamp/FreeCodeCamp#5225]
Howdy from [The Changelog](https://changelog.com/)!

We'd love to get y'all on the show sometime in the new year. Who would be best to have on the show to talk about this project and what you're up to? Feel free to send an email to editors@changelog.com to coordinate.

If you haven't heard of the show, The Changelog is published every week on Friday and covers what's fresh and new in open source. You can listen to the show here http://thechangelog.com/podcast/ or here http://5by5.tv/changelog

Looking forward to talking to y'all!

Adam, EIC

**Comment by QuincyLarson** [comment]
Hey @adamstac - long time fan of The Changelog! It would be an honor to be on your show! I'll send you an email.

**Comment by adamstac** [comment]
Thanks, you're so quick @QuincyLarson! Looking forward to talking with you.
