### ISSUE TITLE
"Ask for Help" Modal text legibility

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52273]
### Describe the Issue

I was looking at #52233 and I wonder if we should improve the legibility of that heading text as well.

- The default Bootstrap `line-height: 1.1` isn't great here.
- The `Hack-ZeroSlash` font used with `font-weight: 700` makes it harder to read in my opinion.

Here is the Modal with `line-height: 1.5rem` and the default `font-weight: 400` for the heading.

![modal](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/1dcd7f91-870e-49d4-af28-72c31b06457d)

And here is the original

![modal-original](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/0f90a764-560f-45eb-8d44-b8cbd004dbf2)

### Affected Page

Any challenge with "Get Help"

### Steps to Reproduce

Open the Modal

### Expected behavior

Better legibility of the heading text.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by dmateen** [comment]
![Screenshot from 2023-11-08 19-29-59](https://github.com/freeCodeCamp/freeCodeCamp/assets/63250699/af667e4c-7d38-4b71-8755-85c6ec2782a4)

Isn't it already correct?

**Comment by lasjorg** [comment]
I don't know what you mean by correct.

I'm suggesting changing the `line-height` and `font-weight` to make it easier to read. I'm talking about the `h3` with the Read-Search-Ask link in it to be clear.

---

It is less of an issue in light mode than dark mode but I still think the legibility can be improved by the suggested changes.

**Comment by moT01** [comment]
I don't think it's hard to read, but it does feel a little condensed and I do think it looks better with a little more space. With the added space, we may not need to make the adjustments to the link underlines.
