### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue 

### ISSUE THREAD

**Issue by saurabh73** [FreeCodeCamp/freecodecamp#523]
I have wrapped my image in anchor tag, still it's not getting accepted.
Code snippet.
<p>Click here for <a href="#"><img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/></a></p>

**Comment by terakilobyte** [comment]
Chances are you haven't provided an href to your `<a>` tag. It works if you do.
