### ISSUE TITLE
English Curriculum: Add challenge parser tests for fill in the blank

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52309]
### Describe the Issue

A "fill in the blank" style challenge was added as part of the upcoming English Curriculum. Part of that included adding some new things to the challenge parser. Here is the parser file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/challenge-parser/parser/plugins/add-fill-in-the-blank.js. No tests were created with that addition. We want to create tests, similar to the others, to make sure it's working properly.

**Comment by devanshi-jain** [comment]
Ok, im gonna try fixing this.

**Comment by moT01** [comment]
Let us know if you have any questions or anything @devanshi-jain 👍

**Comment by devanshi-jain** [comment]
hey @moT01, i've encountered 11 security vulnerabilities that I'm having difficulty resolving, this is when simply running npm audit. am i missing something?

**Comment by vanessalin0226** [comment]
Hi, I would like to work on this issue!

**Comment by moT01** [comment]
Sorry for the delay here @devanshi-jain. I don't think it should be an issue - is it preventing you from running the repo?
