### ISSUE TITLE
English curriculum: find/create icon for map/superblock button

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52306]
### Describe the Issue

The English curriculum was added as an upcoming change:

![Screen Shot 2023-11-09 at 12 20 05 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/9a8b503f-c5e8-4e32-8a9b-5ae8abd9e3ac)

The icon on the button is the same as the Project Euler superblock. We need a new icon. Not quite sure what it should look like. I believe this is the first superblock/cert of many to come. e.g. "A2 English", "A3 English", etc. So potentially we want an icon that we can reuse or just slightly tweak for all of the English certs.

Maybe something like this:

![Screen Shot 2023-11-09 at 12 28 38 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/7f5dbbb9-20d4-4102-9c13-63c082c372f9)

But a `2` instead of the Chinese? symbol. Or possibly a box with four squares - `A2` on the top, `EN` on the bottom.

**Comment by dmateen** [comment]
Do we have to change SHOW_UPCOMING_CHANGES to true in sample.env for or have to do something else to make the upcoming changes visible?

**Comment by dmateen** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/63250699/d696d2dd-9637-4f20-aa24-92c124736389)

Done!

**Comment by dmateen** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/63250699/e8c479ee-3531-4b11-a984-b3a35dd3308b)
Although, this look much better so sending a PR with this SVG
