### ISSUE TITLE
C# note contrast illegible

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52301]
### Describe the Issue

<img width="810" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/2a896cdd-b088-4754-8d63-37c22239ef83">

### Affected Page

https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam

### Steps to Reproduce

1. Complete all the trophy challenges
2. Use night theme
3. Navigate to the exam page

### Expected behavior

UI to be legible.

### System

- Browser: Chrome

### Additional context

<details>
  <summary>Light theme is fine</summary>

<img width="742" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/ec659802-733a-4753-8f1f-5bda6de06ab3">

</details>

**Comment by Sriparno08** [comment]
Hey @ShaunSHamilton, I would like to work on this.

Can you tell me the file that I will be working with?

**Comment by dmateen** [comment]
Hey @ShaunSHamilton, how can we complete the trophy challenges when working in the dev environment?

**Comment by ShaunSHamilton** [comment]
@Sriparno08 @dmateen To test locally, I just alter the database to have the relevant challenges in the `completedChallenges` array. That is, I `db.user.update({email: "foo@bar.com"}, {$set:{completedChallenges: [...]}})`, but I now see we have a `pnpm run seed -- --seed-trophy-challenges` flag.

**Comment by moT01** [comment]
Taking a look at this, I noticed that the `--seed-trophy-challenges` flag doesn't work. [This PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/52337#issuecomment-1808557090) should fix that. Also, it was added that the surveys and exams get seeded when you run the seed command. So to see that alert - you need to seed the trophy challenges, and then delete the `Survey` collection.

**Comment by moT01** [comment]
The [file with the issue is here.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/exam/components/foundational-c-sharp-survey-alert.tsx) The fix is to import `Panel` from `@freecdoecamp/ui` instead of `react-bootstrap` and give the panel a `variant='info'` prop. You can remove the `bsStyle='info'` prop. I only played with it for a short time, but I think this will fix it all up.

**Comment by Sriparno08** [comment]
Hey @moT01, I'm following the steps that you've mentioned in [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/52339).

Can you tell me how to delete the `Survey` collection in MongoDB?
