### ISSUE TITLE
Whether we should recommend setting up local environment with `seed:certified-user` instead of `seed`

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52300]
### Describe the Issue

I had a facepalm moment when I was working on a set of Playwright tests. The tests passed locally but failed in CI, and turned out I was seeding my DB with demo user (`pnpm run seed`) while we seed CI with certified user (`pnpm run seed:certified-user`):

https://github.com/freeCodeCamp/freeCodeCamp/blob/65673ee2fc5cd617f97bba1e3929b07e1daece93/.github/workflows/e2e-playwright.yml#L133

The failure was expected then, because the tests were working with different user data.

---
I'm now wondering if we should recommend developing with `seed:certified-user` over `seed` in general. If we are okay with this, we will need to update the following section of the [setup guide](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=step-3-start-mongodb-and-seed-the-database):

<img width="1088" alt="Screenshot 2023-11-09 at 17 12 23" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/91921363-98f2-455b-9de5-02e2afa8ace6">

If we still recommend developing with `seed`, then we should add a note in the following section of the [Playwright guide](https://contribute.freecodecamp.org/#/how-to-add-playwright-tests?id=_1-ensure-development-environment-is-running) to ensure `seed:certified-user` is run before tests are written and executed:

<img width="1074" alt="Screenshot 2023-11-09 at 17 15 49" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/42f06428-bcca-48da-9fa3-9a81ee428904">

**Comment by ojeytonwilliams** [comment]
I think most people want to use the 'new' user and we do mention `seed:certified`, so the setup docs seem fine. However, it's definitely not correct to recommend `seed` in the Playwright guide.

Seems like a simple enough fix, though: the Playwright should say `pnpm run seed:certified`.

**Comment by moT01** [comment]
I think updating the playwright guide would be enough - but we could add a note in the main area that says something like "Use this if you are going to run playwright tests"
