### ISSUE TITLE
Clear search input of home page on search

### ISSUE THREAD

**Issue by amitabh-sahu** [freeCodeCamp/freeCodeCamp#52322]
### Describe the Issue

When we search on [news page](https://www.freecodecamp.org/news), the search field gets cleared on search. But, when we search on [home page](https://www.freecodecamp.org) results will open on a separate tab "/news" with the search query and the origin tab still has the searched query.

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Go to [freecodecamp](https://www.freecodecamp.org/)
2. Click on the search field and type your query then press enter
3. A separate tab "/news" is open with the searched query
4. The origin tab search field is not clear and still has the searched query

### Expected behavior

As performing a search on [home page](https://www.freecodecamp.org/) the result shows on a separate tab, the origin tab search field should get cleared.

### System

- Device: Laptop
- OS: macOS
- Browser: Chrome

**Comment by ghulamrabbani883** [comment]
I am new to open source, but have knowledge of front-end and I think I can resolve this issue, can I work on this

**Comment by jdwilkin4** [comment]
HI @ghulamrabbani883 ! 

This issue has not been triaged yet so it is not available for contribution.
Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/) to learn how to contribute to freeCodeCamp.

Issues marked with `help wanted` or `first timers only` are available for contribution.

**Comment by rajvinder-kaur** [comment]
hey i wanna work on it

**Comment by ahmaxed** [comment]
The search on the landing page and the rest of the platform are intentionally different; However, it does not hurt to make them function as similar as possible.
