### ISSUE TITLE
Skip actions when they aren't relevant

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52341]
### Describe the Issue

Not sure if we want to do this - creating an issue for discussion.

When a change is made to a part of our repo that isn't related to building the site, we run the entire CI suite. There isn't really a problem with the actions right now, they seem to be keeping up pretty good.

But what comes to mind, is that when a PR only touches the `docs` folder, for instance, we run the whole suite. Changing things in only the docs folder doesn't have an effect (theoretically) on if the site will build or if the e2e tests will pass, etc.

We get several PR's a week that only touch the docs folder - that includes the crowdin downloads. If we skip some of the CI suite on those (node and e2e, for instance), it would free up actions.

The docs come to mind, cause it's the area that's the most noticeable, and gets frequent PR's - but there's probably other areas that we could do the same. The challenge-editor, for instance.

Just opening up a discussion to see what people think.

**Comment by ShaunSHamilton** [comment]
I have been thinking about this too. It should be pretty easy to add to the actions.

Oliver and I briefly discussed how we might use Turborepo to cache test artifacts between runs, and then only have relevant changed files cause rebuilds and re-runs of tests. But this would a) require Turborepo, b) take a while to implement correctly. _Interesting idea, though_

**Comment by ojeytonwilliams** [comment]
For docs, specifically, we were planning to move them to a separate repo: https://github.com/freeCodeCamp/freeCodeCamp/issues/51420

Turbo repo should be able to help us out with anything that remains in the monorepo. A little bit at least.

**Comment by moT01** [comment]
Closing this. The issue is kind of vague and the docs have since been moved, which is the main thing I thought we could do to help.
