### ISSUE TITLE
Migrate Button component in donation form

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52349]
## Context

This issue is to track the migration of Button component in the donation form, as part of #52092. I need to cut a separate issue for this as I encountered some incompatibilities in the `ui-components` library and wanted to document them.

There are two display types of the donation form:

| Type | Visual |
| --- | --- |
| As page content | <img width="1680" alt="Screenshot 2023-11-14 at 17 23 31" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/c4ed0fe1-8fec-41e2-ba1c-b6191114f4d4"> |
| As a modal | <img width="1680" alt="Screenshot 2023-11-14 at 17 25 17" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/583a7a0a-6dd4-45dd-b083-798688d19ec9"> |

There are four buttons that we need to make changes to:

| Button | State | Visual |
| --- | --- | --- |
| Donate | at rest | <img width="934" alt="Screenshot 2023-11-14 at 15 51 01" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/e1d22afc-aa40-4bab-ad42-20568547aca4"> |
| Donate | hovered | <img width="924" alt="Screenshot 2023-11-14 at 17 38 50" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/681c56dd-fa2c-4e2e-a992-81a9e7e2b7c8"> |
| Edit amount | at rest | <img width="919" alt="Screenshot 2023-11-14 at 17 40 35" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/f141b300-2ceb-4b0d-8155-bdda46973a07"> |
| Edit amount | hovered | <img width="921" alt="Screenshot 2023-11-14 at 17 41 53" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/8cab0f93-d218-4116-9b32-a4fa7e7fd303"> |
| Close / Ask me later (only displayed on the donation modal) | at rest | <img width="934" alt="Screenshot 2023-11-14 at 15 51 01" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/cd2fba85-bec0-42f3-9a71-0c7667f0f907"> |
| Close / Ask me later (only displayed on the donation modal) | hovered | <img width="927" alt="Screenshot 2023-11-14 at 16 07 24" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/8e46efd6-aa79-4fd7-99c4-3c82ffd8dcf1"> |
| Try again | at rest | <img width="916" alt="Screenshot 2023-11-14 at 17 47 01" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/d548bdc8-819a-494f-8c2f-38ffa755b74a"> |
| Try again | hovered | <img width="918" alt="Screenshot 2023-11-14 at 17 47 46" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/ec6added-76fb-4b84-9c77-87c40bad49d3"> |

### "Edit amount" and "Ask me later" buttons having unsupported styles

The "Edit amount" and "Ask me later" buttons are styled with the `.btn-link` class from Bootstrap, which strips off the border and adds an underline to the text, making the buttons look like a link. However, the Button from `ui-components` does not support this variant.

**Approaches:**
1. Use `ui-components` Button, but override its CSS
2. Convert the buttons to the native `<button>` element, style them using a combination of our CSS and Bootstrap's CSS

**Decision:** I'll go with (2) as it's a cleaner approach. We can decide if `ui-components` Button should support this display variant after the migration.

### "Donate" button having unsupported styles

Similar to the above case, the "Donate" button is an odd one as its styles don't match the one in `ui-components` (round border, custom color token, different font weight, etc.). The component has a lot of CSS overrides that I think it's better to let it use a native `<button>` instead.

I think I'm seeing a pattern here. There is a CTA button on the landing page that also needs custom CSS, so perhaps we could build a `CallToActionButton` component in `ui-components` or add this as a variant to the existing Button.

**Decision:** Temporarily use the native `<button>` element for this one. We will revisit the library after the migration.

### "Try again" button does not blend well with the alert box

The `primary` variant of Bootstrap is blue while ours is gray, and putting it on the alert isn't really aesthetic on dark mode (also notice the button border is almost invisible).

| Theme | State | Visual |
| --- | --- | --- |
| Dark | at rest | <img width="926" alt="Screenshot 2023-11-14 at 18 06 50" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/a72f57d4-2eff-41d6-9dc8-9192c40f7fdd"> |
| Dark | hovered | <img width="925" alt="Screenshot 2023-11-14 at 18 06 57" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/1828a24c-61cd-487c-a53c-a51b206987e8"> |
| Light | at rest | <img width="924" alt="Screenshot 2023-11-14 at 18 11 03" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/5615738f-0c9d-4954-8d7b-dadb85a2d140"> |
| Light | hovered | <img width="925" alt="Screenshot 2023-11-14 at 18 11 09" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/62800723-d401-4c2a-82bc-e8e10880790f"> |

(I'm pretending to be a designer here.)
I don't think this is the `Button`'s fault, but rather, it's because `Alert` doesn't have dark mode, and it being too bright in dark mode increases the contrast, making the Button stand out more. Maybe dimming `Alert` background in dark mode would help.

**Approaches:**
1. Keep using the `primary` variant and sort our the `Alert` styling instead
2. Replace the `primary` variant with `info`
    It looks a little better with `info`, but the usage is a bit wrong semantically:

    <img width="926" alt="Screenshot 2023-11-14 at 18 14 09" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/db796864-494c-4333-8991-d54a060236eb">
3. Consider this button a special case, use the native `<button>` element and style it following Bootstrap

**Decision:** I think (1) is the proper fix, but I want to avoid making things worse (and not to mention scope creep). So I'll go with (3) for now as a stop-gap solution. We can revisit the component library and address its usage limitation after the migration.

**Comment by ahmaxed** [comment]
Thanks for laying out all of the different variations.
Using native elements and styling them should work for both of the instances. We can decide on the next iteration what to do with them.
