### ISSUE TITLE
Donation modal's "edit amount" button is overflowing on mobile

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52356]
### Describe the Issue

While working on #52349, I found that the "Edit amount" button is overflowing on mobile:

<img width="431" alt="Screenshot 2023-11-15 at 01 43 38" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/1a22a2f0-afef-4ae1-bc36-bff7ef8fa256">

### Steps to Reproduce

I don't know how to trigger the modal in production, but to reproduce the issue locally:

1. Change this line to `show={true}` so that the modal appears:
  https://github.com/freeCodeCamp/freeCodeCamp/blob/124bf1464039081ac3653716764a65ef9cc28d42/client/src/components/Donation/donation-modal.tsx#L153 
2. Open the browser devtools, toggle the responsive mode, and select a mobile device
2. Go any page
3. Click the "Donate" button on the modal
4. See the "Edit amount" button

### Expected behavior

The button is pushed to the edge of the screen is because:
- There is a width constraint and the elements don't have enough space:
  - https://github.com/freeCodeCamp/freeCodeCamp/blob/124bf1464039081ac3653716764a65ef9cc28d42/client/src/components/Donation/donation.css#L301
- The elements are displayed in the same row with:
  -  https://github.com/freeCodeCamp/freeCodeCamp/blob/124bf1464039081ac3653716764a65ef9cc28d42/client/src/components/Donation/donation.css#L304-L305

I think the fix for this should be changing the arrangement logic on mobile: have the elements stack vertically, rather than keeping displaying them in a row. It's because even if we can address the issue for English, we can't guarantee that the overflow won't happen in other languages.

### System

- Device: iPhone SE, Samsung S8+ (via browser devtools)

**Comment by pothuguntaumesh** [comment]
Hi, I'm new to open source contribution, but I've good understanding of react.  Can I work on this?

**Comment by Nkiriobasi** [comment]
I'll fix this

**Comment by Jeevan-Neupane** [comment]
> Hi, I'm new to open source contribution, but I've good understanding of react. Can I work on this?

Did you set up the code in your computer

**Comment by Jeevan-Neupane** [comment]
> Hey @pothuguntaumesh and @Nkiriobasi, thank you for your interest in contributing!
> 
> This issue has not gone through the triage process and not yet open for contribution.

Can you help me with set up the code in my computer since I am just a beginner to the open source

**Comment by Jeevan-Neupane** [comment]
> @Jeevan-Neupane I recommend taking some time to read through our [contributing guidelines](https://contribute.freecodecamp.org/) first. You can also join [our Discord server](https://discord.gg/PRyKn3Vbay) if you have any questions or need assistance.

Link is expired please can you send me again

**Comment by Jeevan-Neupane** [comment]
> @Jeevan-Neupane I recommend taking some time to read through our [contributing guidelines](https://contribute.freecodecamp.org/) first. You can also join [our Discord server](https://discord.gg/PRyKn3Vbay) if you have any questions or need assistance.

Thank you

**Comment by ahmaxed** [comment]
the confirmation text and the edit amount button both should stay in the same row in a 350px width element.
The text and the button should be on two sides of the containing element.
If the contents are colliding in the containing element, the button should overflow to the next line below the text.
Achieving this might be more straight forward using grid.
