### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue 

### ISSUE THREAD

**Issue by mdanro** [FreeCodeCamp/freecodecamp#524]
Please tell us in detail here how we can make this challenge better.
Completion is triggered only by 
###<code>
###<a href="#">
###</code> 
###instead of 
###<code>
###<a href="#"><img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/></a>
###</code>
###

**Comment by terakilobyte** [comment]
Thanks for the report. We've since hardened the tests!
