### ISSUE TITLE
Improve error messages in the Python curriculum console

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#52411]
### Is your feature request related to a problem? Please describe.

When an exception is raised the console output can be difficult to understand:

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/105294544/7dfd3050-de29-4e8a-9ee9-66087c8afd42)

### Describe the solution you'd like

It would be nice to show only this portion (ideally with the correct line number):

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/105294544/8878e6d1-f265-4aae-9398-861aa0690f90)

### Describe alternatives you've considered

Another possibility could be to create a test that catches the exception type and shows only that to the user as a sort of dynamic hint and leave all the pyodide stuff in the console.
For example:

>Your code should be valid. Error found: IndentationError

**Comment by ojeytonwilliams** [comment]
>> Proxy errors to the console. We don't need to redirect stdout, since the terminal shows that, but errors do need to be shown ref. https://github.com/freeCodeCamp/freeCodeCamp/issues/52411

>Personally, I have always disliked having a "Shell" and a "Console" (e.g. Replit). I would prefer we not do the same, and, instead have a single terminal we:

>Allow campers to type in
Show the output of running the code in
I do not see benefit from further separating the experience to an actual dev/local environment.

originally posted by @ShaunSHamilton here:
https://github.com/freeCodeCamp/freeCodeCamp/issues/52536#issuecomment-1853985281

I don't have a strong opinion about where the errors need to go, but I wanted to note that, as of https://github.com/freeCodeCamp/freeCodeCamp/pull/52526, they're currently only appearing in the browser console. That will need fixing as part of the resolution to this issue.

**Comment by naomi-lgbt** [comment]
Is this something we want to open up for contributors to iterate on?

**Comment by ojeytonwilliams** [comment]
@naomi-lgbt it's okay, I should be able to work on this soon (this week).
