### ISSUE TITLE
Add freeCodeCamp podcast page to the nav menu 

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52417]
### Is your feature request related to a problem? Please describe.

I'm wondering if we could add Podcast to the navigation dropdown menu for convenient access.

### Describe the solution you'd like

Add Podcast to the dropdown menu. The link should either be https://www.freecodecamp.org/news/tag/podcast/ or https://freecodecamp.libsyn.com/. I _think_ we would want to direct users to the former link, though it doesn't have all of the podcast episodes listed.

**Comment by namrata18s** [comment]
@huyenltnguyen I would like to work on this issue. Thankyou!

**Comment by moT01** [comment]
I like the idea of linking the podcast in the nav. I would vote for the second link cause you can immediately start playing the episodes on that page. Also, the espanol and chinese clients could probably link to those podcasts:

https://freecodecamp-in-chinese.transistor.fm/
https://freecodecamp-en-espanol.transistor.fm/
