### ISSUE TITLE
table in multifile editor description css

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52424]
### Describe the Issue

Tables in the multifile editor do not appear correct:

<details>
  <summary>What tables should look like</summary>

<img width="361" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/ea9a57c6-6aeb-4b66-9b8c-852a698c4c91">

</details>

<details>
  <summary>What tables looks like</summary>

<img width="546" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/8ce465c0-bd75-480c-b827-13842b5a2d92">

</details>

This appears to just be a CSS issue, but I am not sure where it goes wrong.

**Comment by ArvindParekh** [comment]
Hi. I tried looking it up, but could not find the file you're talking about. Could you provide more info on this?

**Comment by sohamtembhurne** [comment]
Hi @ShaunSHamilton, can you please provide more info on this and a link to the webpages would be of great help

**Comment by ShaunSHamilton** [comment]
@ArvindParekh and @sohamtembhurne , we do not have any code with the issue in production. The issue is when a multifile project step's markdown includes a table. To test, you will have to add a table to any of the challenges using the multifile editor (the editor with the instructions embedded in it. E.g. Responsive Web Design challenges).
