### ISSUE TITLE
Repl.it run command not setup for campers

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#52455]
### Describe the Issue

From what I've learned on the forum, the Repl.it run command configuration has changed. As a result, when a camper goes to hit run; they get the following stacktrace. 

`
node:internal/modules/cjs/loader:1075
throw err;
^

Error: Cannot find module ‘/home/runner/boilerplate-npm/index.js’
at Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
at Module._load (node:internal/modules/cjs/loader:925:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
at node:internal/main/run_main_module:23:47 {
code: ‘MODULE_NOT_FOUND’,
requireStack:
}`

And because they're still learning, they have no idea what to do. 

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package

### Expected behavior

The Run command wasn’t setup yet. 

The instructions should be like:  

-  Start by importing the project on Replit.
-  Next, you will see a .configure window.
-  Hit the Done button to set Replit's run task to `npm run start` 
    

### Screenshots

![The new layout](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/0eb97211-7aad-4563-8fea-0bc9949477f0)

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 120.0.1 

### Additional context

I discovered this because of an issue on FreeCodeCamp's forums.

**Comment by gikf** [comment]
To clarify, it looks similar to what was before, but there are some changes:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/60067306/5108a510-1c4f-4791-9a1f-127dcbfe5adf)

Current instructions:
>If you use Replit, follow these steps to set up the project:
\- Start by importing the project on Replit.
\- Next, you will see a .replit window.
\- Select Use run command and click the Done button.

**Comment by naomi-lgbt** [comment]
Could probably update `- Next, you will see a .replit window.` to `- Next, you will see a "Configure Replit" window?`

**Comment by scissorsneedfoodtoo** [comment]
Closing via https://github.com/freeCodeCamp/freeCodeCamp/issues/53470
