### ISSUE TITLE
Make c# course more fluid

### ISSUE THREAD

**Issue by davidbuckleyni** [freeCodeCamp/freeCodeCamp#52473]
I Find the csharp course at present very broken.  Having to flip back and forth between learn and the free code camp is very frustrating and brakes train of thought would a simple interface fix this. 
Am currently doing entry level python course and its interface is night and day difference.

**Comment by davidbuckleyni** [comment]
Yeah that sounds good a been using csharp for 20 years so appreciate this put it on wider discussion if you want first.

**Comment by davidbuckleyni** [comment]
ill get the link its the offical phython entry course

**Comment by moT01** [comment]
Revisiting this - I don't think we want to reduce the C# challenges to just one per section. It would make it a little easier to go through, but it would leave very little on freeCodeCamp. I like having more challenges on the site.

Do you have any other ideas for how to make it more fluid @davidbuckleyni?

**Comment by davidbuckleyni** [comment]
Hi sorry if you sign up with the python basic certification they supplied you can see what am talking about

**Comment by moT01** [comment]
Can you share a link?

**Comment by moT01** [comment]
Closing this as stale. Feel free to open a new issue if you think something needs to be changed - maybe it will get some more attention. Thanks and happy coding 🎉
