### ISSUE TITLE
[Profile timeline] Content of the View button wraps if it contains an icon

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52491]
### Describe the Issue

In the timeline section of the profile page, the content of the view solution button would wrap if it contains an icon:

<img width="775" alt="Screenshot 2023-11-23 at 17 24 49" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/e7e9d930-4fab-4650-86a1-e08fc170a220">

This issue is because the Solution column doesn't have an adequate width, and I think we could fix this by wrapping the columns inside the `Col` component and giving them some sufficient width value. However, this solution won't work on mobile as screen real estate is still an issue there (challenge titles would wrap onto multiple lines if they are too long).

We might want to take this opportunity to revisit the design of the section (related to #48234), rather than trying to address the responsiveness issue. I'm opening this as a separate issue to surface the bug and to discuss the approach (fixing the issue vs implementing the new design). The issue can be closed and discussion can be moved to #48234 if we decide to go with the redesign approach.

### Affected Page

https://www.freecodecamp.org/{username}

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/{username}
2. Scroll down to the timeline section
3. Find challenges/projects that have solution button being a link (the RWD's Build a Survey Form is an example)
4. See the button display

**Comment by Sembauke** [comment]
Let us revisit this component when we decide what we want to do with it on the profile page.
