### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by achock** [FreeCodeCamp/freecodecamp#525]
the error says that Wrap each of your checkboxes inside its own div with the class "col-xs-4". While in the instructions it says that the input should be col-xs-7 and the button col-xs-5

**Comment by QuincyLarson** [comment]
Thank you for pointing this out! We've fixed this and the fix should be live in the next few minutes.

**Comment by Bouncey** [comment]
@BerkeleyTrue this is happening quite a bit. Your bot is assigning me to
legacy issues. Is this an issue with waffle? It has happened 3-4 times
recently

**Comment by BerkeleyTrue** [comment]
It could be someone with access is assigning you through waffle.
