### ISSUE TITLE
Running `seed:certified-user` should add the user's Microsoft account to the DB

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52510]
### Describe the Issue

When running the dev environment as a certified user, we have all C# trophies completed but the user's MS transcription link is not linked:

<img width="1680" alt="Screenshot 2023-12-08 at 15 27 16" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/8c119dc9-4bbf-4944-82d9-3a9b15dc7d53">

While this is a possible scenario (the user links their account to claim trophies, then unlinks it), it seems like an edge case to me, and it shouldn't be the default behavior when we first setup the dev environment.

### Affected Page

Any C# trophy page. Example: `/learn/foundational-c-sharp-with-microsoft/write-your-first-code-using-c-sharp/trophy-write-your-first-code-using-c-sharp`

### Steps to Reproduce

1. Seed the local environment with `seed:certified-user`
2. Go to `/learn/foundational-c-sharp-with-microsoft/write-your-first-code-using-c-sharp/trophy-write-your-first-code-using-c-sharp`
3. See the "link MS account" section on the page

### Expected behavior

The `seed:certified-user` command should add the user's Microsoft account / transcription link to the DB.

And the trophy pages should look similar to this:

<img width="1680" alt="Screenshot 2023-12-12 at 11 57 20" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/cfd21833-3184-45fe-a482-88b71ca6f5b6">

### Additional context

This issue was discovered here: https://github.com/freeCodeCamp/freeCodeCamp/pull/52445#discussion_r1420122664.

**Comment by ieahleen** [comment]
what link should be added?

**Comment by ojeytonwilliams** [comment]
Thanks, @huyenltnguyen, I agree that this is a weird default. The fix should just be to add an MsUsername record with a userId of the certified user. @moT01 can you confirm/deny?

**Comment by moT01** [comment]
Confirmed.

Here's what my entry looks like when I link my account locally:

```
  {
    _id: ObjectId('65785b25d4c5bd0565c0184d'),
    userId: ObjectId('5bd30e0f1caf6ac3ddddddb5'),
    ttl: 77760000000,
    msUsername: 'moT01'
  }
```

We don't save the transcript link anywhere, so I'm fine with using my username if we want.
