### ISSUE TITLE
Correct verbiage in "Handle a Fulfilled Promise with then" challenge

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52527]
### Describe the Issue

I realize it is probably just an oversimplification but the part that may need correction is.

> The `then` method is executed immediately after your promise is fulfilled with `resolve`.

I think this should say the `then` `onFulfilled` handler is called when the promise becomes fulfilled. Or something to that effect.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/handle-a-fulfilled-promise-with-then

### Your code

```



```

### Expected behavior

More precise verbiage.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/es6-handle-a-fulfilled-promise-with-then/655319

Specs/MDN:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.prototype.then

**Comment by naomi-lgbt** [comment]
I'd say something like:

> The callback within the `then` method is executed immediately after your promise is fulfilled with `resolve`.

I think mentioning the `onFulfilled` might get confusing.

**Comment by lasjorg** [comment]
The thing is, it takes two callbacks. An `onFulfilled` and the optional `onRejected`. So we may have to make the distinction. The name is just the spec definition. It might be less confusing if we show the signature.


> This can be achieved by using the `then` method.
>
> `Promise.prototype.then ( onFulfilled, onRejected )`
>
> The `then` method schedules callback functions for the eventual completion of a Promise — either fulfillment or rejection. One of the `onFulfilled` and `onRejected` handlers will be executed to handle the current promise's fulfillment or rejection. When the promise is fulfilled with `resolve` the `then` methods `onFulfilled` handler is called.

I pretty much just stole the text from MDN. I think we are far enough into the curriculum that a little technical lingo isn't the worst. It might be a bit verbose although it explains it better if you ask me.

**Comment by naomi-lgbt** [comment]
I could go with that, yeah.
