### ISSUE TITLE
Interactive C++ Course

### ISSUE THREAD

**Issue by praneel-patel** [freeCodeCamp/freeCodeCamp#52533]
### Is your feature request related to a problem? Please describe.

It is not related to a problem, however, I wanted to contribute towards FCC by making a C++ course. I will teach C++ on FCC just like with the other courses. 

### Describe the solution you'd like

I just want FCC head or moderator to review this request and let me know about what I should be considering. 

### Describe alternatives you've considered

There are no alternatives. However, if I do not get approved for this, then maybe the person who rejected me is correct and I should try again.

**Comment by ojeytonwilliams** [comment]
Hi @praneel-patel thanks for the offer of help. I'm not sure if are intending to support C++ in the immediate future, though. @ShaunSHamilton you know the backend plans better than I do: could you confirm/deny?

**Comment by ShaunSHamilton** [comment]
Hello @praneel-patel 
Thank you for taking the time to open this.

We are probably quite a few months away from having the infrastructure to teach something like C++. Specifically, teaching browser tools in the browser is easy, but anything else (especially compiled languages) requires a dedicated server/VM to run the code. Currently, we do not have the ability to spin up such a server.

As such, I suggest thinking about contributing a C++ course to the freeCodeCamp YouTube channel: https://www.freecodecamp.org/news/how-to-create-a-great-technical-course/ (also contains info on how to contribute)
