### ISSUE TITLE
[python]: learn-string-manipulation-by-building-a-cipher

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52578]
**TO FIX POST BETA RELEASE**

- 3: #53050 
- 12: #52932 
- 15: unclear hint #53041
- 16: unclear explanation #52820 
- 38: unclear if statement explanation #52738 
- 57: #53170
- 71: #52976
- 75: #52931 
- 82: #53044
- 83:  unclear explanation #53042
- 91: #53046

**Comment by Dario-DC** [comment]
- 38: unclear `if` statement explanation #52738
- 16: unclear explanation #52820
- 83: unclear explanation
- 15: unclear hint
