### ISSUE TITLE
[python]: learn-classes-and-objects-by-building-a-sudoku-solver

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52585]
**TO FIX POST BETA RELEASE**

**General Suggestions**

- ~Have Campers create/instantiate a class and call the `str`/print method so they can see some output in the early lessons~
- ~NO `we`, `us` -> use `you`~
- ~Test hints (text) should end in a period (`.`)~

**Fixes**

- ~3: when referencing "Board", use codeblocks~
- ~4: add indentation to seed code, and include class + method in editable region~
- ~4: is it an _"attribute"_ or a _"property"_ ? it's an attribute.~
- ~5: add indentation to seed~
- ~8: add empty line to seed~
- ~9: add empty line to seed~
- ~10: add indentation to seed~
- ~12: indentation inconsistent~
- ~13: instructions unclear about requirement, and use of `start`~
- ~14: add empty line to seed~
- ~14: break into separate steps with individual variables for each op~
- ~15: probably remove step as part of fixing 14~
- ~16: add empty line to seed~
- ~17: add empty line to seed~
- ~18: add empty line to seed~
- ~19: add empty line to seed~
- ~20: add indentation to seed~
- ~21: add empty line to seed~
- ~21: switch description and instruction - always try to place the instruction (actionable thing for Camper) at the end~
- ~22: add indentation to seed~
- ~22: switch description and instruction~
- ~23: add empty line to seed~
- ~25: switch description and instruction~
- ~25: unclear what "inner condition" refers to~
- ~28: add indentation to seed~
- ~28: told to include `pass`, but next lesson seed does not~
- ~29: add indentation to seed~
- ~30: add indentation to seed~
- ~31: add indentation to seed + include `try` in editable region~
- ~32: "the code"? explain what returns~
- ~33: add indentation + include `try` in editable region~
- ~34: add indentation + include `try` in editable region~
- ~36: add indentation to seed~
- ~39: add indentation to seed~
- ~40: add indentation to seed~

**Comment by zairahira** [comment]
- 53: https://github.com/freeCodeCamp/freeCodeCamp/pull/52452#discussion_r1421605205
- 60: https://github.com/freeCodeCamp/freeCodeCamp/pull/52452#discussion_r1421721548
- 30: Explain try/ catch

**Comment by Dario-DC** [comment]
5: I would like to add the puzzle to solve to the code.
After that it would be nice to print the board for testing purposes before the complete program is ready. Just to add some interactivity while building the final code.

**Comment by zairahira** [comment]
The input puzzle is there in step 5. Interactivity can definitely be introduced for testing :+1:

**Comment by Dario-DC** [comment]
> The input puzzle is there in step 5. Interactivity can definitely be introduced for testing 👍

The puzzle is introduced, but it's not in the seed code until the last step.

**Comment by Dario-DC** [comment]
#53047
