### ISSUE TITLE
[python]: learn-lambda-functions-by-building-an-expense-tracker

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52580]
**TO FIX POST BETA RELEASE**

- 1: add more hints to recall the function declaration syntax (and maybe split the step to add the parameters in a new step)
- 4: it would be great to provide more info about dictionaries and dictionary keys and highlight the difference between `"amount"` and `amount`
- 7: add another hint and reword the current one
- 8: `Leave the placeholders empty for now.` doesn't seem to fit.
- 11: #53420
- 13: #53135
- 16: #53463

**Comment by Dario-DC** [comment]
See also #52722

**Comment by ilenia-magoni** [comment]
Since the adding of quotes around strings, step 9 is a good place to repeat that if your string is surrounded with a kind of quote, then you need to escape or use a different kind of quote as this step require `f'Amount: {expense["amount"]}, Category: {expense["category"]}'`

**Comment by gikf** [comment]
> Since the adding of quotes around strings, step 9 is a good place to repeat that if your string is surrounded with a kind of quote, then you need to escape or use a different kind of quote as this step require `f'Amount: {expense["amount"]}, Category: {expense["category"]}'`

F-string is a bit special case here, which additionally changed very recently in Python `3.12`

For f-strings:
- Python pre-`3.12`
    - Using backslash `\` is not allowed in any part inside of the `{}`. 
    - Using the same quotes inside of the `{}` is not allowed.
- Python `3.12+`:
    - Using backslash `\` is allowed inside of the `{}`.
    - Using the same quote inside of the `{}` is allowed, even without escaping, but not encouraged.
