### ISSUE TITLE
[python]: learn-algorithm-design-by-building-the-shortest-path-algorithm

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52582]
**TO FIX POST BETA RELEASE**

```markdown
- <step-number>: <bug description>
```

- 2: ~'occupation': 'Lumberjack`~
- 3: ~Keys must be unique whitin~
- 4, 6, 9: ~'occupation': 'Lumberjack`~
- 6: ~Then, after declaring `copper`~
- 9: ~The syntax is the following:~
- 12: ~Would be nice to change the description to be more explicit about `A` referencing `B`~
- 13: ~Another description where the outcome is unknown. Be more explicit about how to represent the data structures.~
- 23: ~Test should not assume consistent spacing. I.e. 4 spaces within the function, but 2 within the `for` loop - specifically, the `(\s*).....\1\1`~
- 21-25 https://github.com/freeCodeCamp/freeCodeCamp/issues/53395
- 29: ~In other languages, `val`, `val_1`, and `val_2` might not be clear in the code examples, because it is not explained what they refer to~
- 30: ~Same as 29~
- 30: Hint should explicitly give answer. ~Test should allow different order of comparing variables~
- 34: ~Test needs to be expanded to allow multiple correct answers (e.g. `while len(unvisited) != 0`, `while unvisited != []`, `while len(unvisited) > 0`)~
- 37: ~In instructions, mention `pass`~
- 38: ~to fill temporarily~
- 39: ~Explicitly mention answer in hint~
- 40: ~Mention `pass` in instructions~
- 42: ~Explicitly mention answer in hint, else statement~
- 43: ~`outside the nested conditionals` suggests outside all `if/else` statements - not just the inner-most.~
- 44: ~Does `del unvisited[current]` not work?~
- 45: ~This sentence does not read right: `The first one happens because in the nested if you are trying to access that might not exist in your paths dictionary.`~
- 47: ~the step requires to use slice to copy a list. How to do it should be clarified.~
- 52: ~Instructions suggest `return distances and paths`. Explicitly mention answer in hint~

**Comment by Dario-DC** [comment]
11: add graph image

1-10: consider to remove this step from this project and improve the explanation in the initial steps of the expense tracker project
