### ISSUE TITLE
A11y text in animations is hidden in day mode

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#52592]
In https://github.com/freeCodeCamp/freeCodeCamp/pull/52557 you can see the dialogue text in night mode, but not otherwise. The issue is that the font changes colour, but the background image does not.

**Comment by bbsmooth** [comment]
Ha, this explains why I didn't think there were any captions, I never looked at it in dark mode.

**Comment by naomi-lgbt** [comment]
I had the same thought haha
