### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by mdanro** [FreeCodeCamp/freecodecamp#526]
The challenge completes only if the first radiobox and checkbox is checked, otherwise failse.
The text is misleading 
One of the radio buttons on your form should be checked by default.
 One of the checkboxes on your form should be checked by default.
should either validate if one is checked or text should be first radio / first option to be checked

**Comment by QuincyLarson** [comment]
Awesome! Other campers were reporting this but we weren't able to isolate why they couldn't get it to pass. I will update the copy.

**Comment by lsumner** [comment]
I keep getting this message and don't understand why:
Your first radio button on your form should be checked by default.
Passed
Your first checkbox on your form should be checked by default.

this is my code:
 <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"checked> Outdoor</label><br>
    <label><input type="checkbox" name="personality"checked> Loving</label>
    <label><input type="checkbox" name="personality"checked> Lazy</label>
    <label><input type="checkbox" name="personality"checked> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
