### ISSUE TITLE
Revert CI changes after deploying

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#52613]
https://github.com/freeCodeCamp/freeCodeCamp/pull/52612 
https://github.com/freeCodeCamp/freeCodeCamp/pull/52610
https://github.com/freeCodeCamp/freeCodeCamp/pull/52611
https://github.com/freeCodeCamp/freeCodeCamp/pull/52625

The github settings Quincy changed - the auto run workflows setting (see chat)
Commented out tests from this PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/52600

All need reverting.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52609
https://github.com/freeCodeCamp/freeCodeCamp/pull/52607
https://github.com/freeCodeCamp/freeCodeCamp/pull/52606

Should be reopened

**Comment by naomi-lgbt** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/52622 needs reverting

**Comment by ojeytonwilliams** [comment]
> #52622 needs reverting

If we have time, it should be folded into learn.spec.ts

**Comment by naomi-lgbt** [comment]
Should be able to tackle this soon - think we've almost got everything sorted.
