### ISSUE TITLE
Inconsistent button order in modals

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52615]
## Describe the bug

In the exit exam modal, the primary button comes first then the close button, while the reset progress and delete account modals have it the other way around.

We have been displaying buttons from the most used/important to the least (check code -> save code -> get help), so I think the reset progress and delete account modals should be changed to follow the pattern. It's to maintain the consistency and to prevent the user from clicking the wrong button with their muscle memory (the color in this case helps, but non-sighted users won't have the cue).

| Modal | Page | Screenshot |
| --- | --- | --- |
| Exit exam | https://www.freecodecamp.org/learn/foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam | <img width="623" alt="Screenshot 2023-12-20 at 00 50 06" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/e5be0d4b-83f7-4e83-9b1f-5f3a2dfbe3c9"> |
| Reset progress | https://www.freecodecamp.org/settings | <img width="916" alt="Screenshot 2023-12-20 at 00 51 50" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/bf34375b-5432-4e36-89e1-5dcf0a88c40f"> |
| Delete account | https://www.freecodecamp.org/settings | <img width="914" alt="Screenshot 2023-12-20 at 01 05 24" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/c8c2a126-8f2a-498d-9a02-319ab089da70"> |

## Expected behavior

The button order of the reset progress and delete account modals should be flipped.

**Comment by naomi-lgbt** [comment]
Other way around, I think. The exit exam should be flipped.

If the top button is the most commonly used one, then we should set that to the non-destructive action here. That way, if someone clicks it out of muscle memory and not intention, they haven't done something irreversible.

**Comment by moT01** [comment]
Yup, I think the exam one should be flipped - that's how it is in the danger zone on the settings too

**Comment by Hari-Shankar-Karthik** [comment]
Yes, I agree. The 'Reset progress' and 'Delete account' buttons should be reversed. The affirmative option always comes first, followed by the negative option.

**Comment by adamresemius** [comment]
Hello,

I have flipped the order of the buttons. This should reflect the structure that it appears as.

**Comment by moT01** [comment]
Follow the [instructions here to make a PR with your changes](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) @adamresemius

**Comment by mishalp** [comment]
@huyenltnguyen  I have flipped the order of exit-exam model buttons, Please review it
