### ISSUE TITLE
Network error when running Cypress locally

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52635]
## Describe the bug

I consistently got the following error when running Cypress locally:

```
     CypressError: `cy.visit()` failed trying to load:

http://localhost:3000/signin

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:8000

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

This error occurred while creating the session. Because the session setup failed, we failed the test.
```

## Steps to reproduce

- Run `pnpm run develop`
- Run either `cypress:dev:watch` or `cypress:dev:run --spec path/to/spec.ts`
- Cypress attempts to run, but will fail with the above error

## System

- OS: MacOS Sonoma

## Solution

I was able to resolve the issue by adding `--host 0.0.0.0` to the `develop:client` command and re-run `pnpm run develop`. 

I've been having some strange issues lately with localhost so I think this is due to my local setup, but I'm reporting still, to check if anyone was/is experiencing the same problem. We can add a note to the Cypress guide if I'm not the only one ran into it.

**Comment by moT01** [comment]
Solution: Remove Cypress
