### ISSUE TITLE
[Multi-file template] Issues with panel toggle buttons

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52641]
### Describe the Issue

I found 2 issues with this template:
- The "Instructions" toggle button is not highlighted when it is on (`aria-expanded="true"`)
- When the instructions panel is closed, the editor toggle buttons disappear

| Instructions on | Instructions off |
| --- | --- |
| <img width="1680" alt="Screenshot 2023-12-20 at 16 12 36" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/b8923dc9-e8a7-4b19-845a-8da6e8666ffc"> | <img width="1680" alt="Screenshot 2023-12-20 at 16 18 37" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/34ddd5c5-97bd-4ebc-b213-13ea07897698"> |

### Affected Page

Projects that use the multi-file template. Example: https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form
2. Check the display of the "Instructions" button. It's not highlighted even though the instructions panel is open
3. Click the "Instructions" button
4. See the disappearance of the editor toggle buttons

### Expected behavior

I expect that:
- The "Instructions" toggle button should be highlighted when it is on
- The editor toggle buttons should be on the screen when the instructions panel is closed

But will wait for the core team to confirm.

**Comment by blizet** [comment]
I have made the necessary changes so go throught it once and let me know if it can be merged

**Comment by ShaunSHamilton** [comment]
@huyenltnguyen I take it to close this issue, just the issue of the buttons disappearing needs to be fixed? The highlighting issue should be fixed in a different PR?

**Comment by ShaunSHamilton** [comment]
Ah. Ok, then we can open this up to have both issues fixed. Thank you for clarifying.

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

---

To close this issue:
1) Highlight toggles when they are enabled
2) Prevent editor "files" from hiding, when Instructions is disabled
