### ISSUE TITLE
Document new tools

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#52642]
Need to document the rename challenge tool and the i18n sync tool.

Sometime later this week. Not urgent.

**Comment by ilenia-magoni** [comment]
I can take this on?

**Comment by ojeytonwilliams** [comment]
Go for it, @ilenia-magoni. Thanks!

**Comment by ilenia-magoni** [comment]
I will start with the rename challenge tool, for the i18n sync, I will wait news if it works now
