### ISSUE TITLE
RPG - Teaches Ternary Anti-pattern

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52669]
## Update - Details on the change that needs to be implemented
https://github.com/freeCodeCamp/freeCodeCamp/issues/52669#issuecomment-1876021919

### Describe the Issue

Step 140 teaches the ternary expression by introducing what many people consider a ternary anti-pattern. On the forum and Discord we often stress that a ternary is not a general purpose replacement for an if-else. My usual phrasing is that if you are not using the return value of the ternary, you are probably "code golfing" instead of using a ternary as intended. Many linters across many languages will complain about "discarded return value" or similar.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-140

### Your code

```javascript
// Note - ternary expression return value is ignored
fighting === 2 ? winGame() : defeatMonster();
```

### Expected behavior

Curriculum should not teach anti-patterns.

We could introduce the ternary instead by using it to ensure that displayed health values don't go negative.

### System

All.

**Comment by jeremylt** [comment]
Step 148 demonstrates using the ternary without discarding the return value of the ternary expression.

**Comment by jeremylt** [comment]
I would probably object less if this wasn't the very first introduction to a ternary expression. Putting this as the introduction of a ternary implies that the main function of a ternary is to replace an if-else expression.

**Comment by ArielLeslie** [comment]
I think that's more of a C thing. While in JS/TS, we _usually_ are using ternaries to assign a value, it's not an anti-pattern to call a (probably void) function.  In JS/TS it's considered normal to turn extremely simple if/else blocks to ternary where it is more readable. What's more uncommon about this example (in my experience) is that there's logic in the conditional. I almost always see ternaries where we are just using the truthiness of a variable.

**Comment by jeremylt** [comment]
Fair. I wouldn't object if this was taught *after* the ternary was introduced with usage of its return value.

**Comment by lasjorg** [comment]
Also, the verbiage is wrong. An if/else is not an expression, it is a statement.

A ternary is an expression. Or more precisely, the ternary operator evaluates an expression and depending on if it evaluates to true or false executes one of the appropriate expressions.

---

But I agree, it isn't a good use of a ternary. It should evaluate to one of the expressions and use the value, not run side effect functions.

**Comment by jdwilkin4** [comment]
Hey team! 

So I am trying to figure out where we landed with this.

Is the game plan to rewrite this use of a ternary to a regular if else statement and then teach the ternary operator in another project like the music player project?

**Comment by lasjorg** [comment]
I would suggest we change it. I don't think this is how we want to teach the ternary operator. 

But we are asking them to rewrite an existing if/else so I'm not sure what to do with this step. There doesn't seem to be a good place for a ternary in this project.

---

I'm a little surprised that not a single function in this project uses parameters, takes arguments, or returns values.

It would be nice to have some pure functions that return values, functions that do logic and cause top-level variables to be updated, and functions that update the DOM based on the current state of the program (render function). That type of code is usually easier to reason about I find.

Anyway, the only reason I started to think about this was if we did have functions that returned values they would be useable in a ternary. But all we have are side effect functions. Some might not even call them functions, as they do not take or return values (obviously as JS has implicit function returns they do all return undefined, making them functions).

**Comment by jdwilkin4** [comment]
I looked through the project and there is one function that does return a value which is the `getMonsterAttackValue` function. 

Right now, step [148](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-148) has campers return the result of a ternary.

We could remove step 140 all together and then teach ternary in step 148 instead.

**Comment by lasjorg** [comment]
Yeah, I must not have been looking at the last step of the project as I thought I was. I see the functions now, like `getMonsterAttackValue` and `isMonsterHit` are examples of the type of function I was thinking of.

I agree,, we should just remove step 140 completely and teach ternary in step 148.
