### ISSUE TITLE
Incorrect info in the new Python curriculum description

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#52663]
### Describe the Issue

The description of the new Scientific Computing with Python (Beta) curriculum contains info related to the previous certification.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/

### Steps to Reproduce

See affected page

### Expected behavior

The description should be updated to not include networking, relational databases and data visualization.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/105294544/84c33dce-ada9-4459-98db-0f2d80b3281a)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Humayun-glitch** [comment]
I can help with solving the issue.

**Comment by Humayun-glitch** [comment]
Can you point me to the file here on GitHub that needs updating? I can help.

**Comment by gikf** [comment]
> Can you point me to the file here on GitHub that needs updating? I can help.

I believe that's https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/i18n/locales/english/intro.json

**Comment by Humayun-glitch** [comment]
@gikf Yup found it. Will update it and create a pull request. Why didn't I look through this file? even though I saw it. Thanks!
