### ISSUE TITLE
[python]: running tests too many times causes memory issue

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#52661]
**To reproduce**

1) Go to a python (pyodide) challenge
2) Click "Check your code" in quick succession
3) Look in browser console

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/9b75d834-c159-45c8-996a-3af0e9fb1f2d)

**Comment by naomi-lgbt** [comment]
Easy fix: https://downloadmoreram.com/

**Comment by ShaunSHamilton** [comment]
I can no longer reproduce this issue.
