### ISSUE TITLE
Misleading Certification Name

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52662]
### Describe the Issue

With the rollout of the new curriculum beta, this feels like a good time to fix the misleading name of this certificate. "Scientific computing" is a specific discipline and this certificate and its projects don't have anything to do with "scientific computing". We should use a less misleading name.

See here for a brief list of some "scientific computing" topics:
https://en.wikipedia.org/wiki/Computational_science#Methods_and_algorithms

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/

### Your code

N/A

### Expected behavior

Course name should accurately reflect the course content. "Python Algorithms and Data Structures" is probably more accurate, and would mirror our introductory JavaScript course name.

### System

All

**Comment by naomi-lgbt** [comment]
Flagged internally for review.

**Comment by QuincyLarson** [comment]
@jeremylt Thanks for your thoughts on this. The term "Scientific Computing" is quite vague to begin with. But it sounds more interesting than "even more algorithms and data structures."

We want to add some additional projects to further justify use of this name. Currently, the Python cert only has 15 projects total and we'd like to eventually have closer to 20.

Can you think of any of the approaches listed here where we could create projects that teach them?

**Comment by jeremylt** [comment]
"Scientific computing" is a little broad, but it is a term of art used by research software engineers to describe writing code in support of science.

I've actually taught some introductory scientific computing topics. The most basic projects I would consider part of the field of scientific computing would involve calculus or statistics, but I don't think those topics are prerequisites for any of our current material.

The swinging pendulum is one of the most basic projects in the category:
https://en.wikipedia.org/wiki/Pendulum
This is a great example because its doing exactly what the name of scientific computing suggests - taking a principal from science and recreating it on the computer.
However, coding the introductory simulation of this pendulum requires understanding second derivatives.

**Comment by jeremylt** [comment]
Note - the certificate content is still not Scientific Computing in the sense used professionally, but it at least has some content that's closer now. But I'm not surprised we're just sticking with the name.

**Comment by ilenia-magoni** [comment]
@jeremylt the new plan for the curriculum will be bigger certs, so this is not something we are going to worry anymore as it will be Legacy soon
