### ISSUE TITLE
[React] - The React render method lesson should be updated

### ISSUE THREAD

**Issue by yellowsamuray** [freeCodeCamp/freeCodeCamp#52675]
In the Front End Development Libraries Certification lesson, specifically React lesson on 'Render HTML Elements to the DOM' it is still using [ReactDOM.render]. I know this method still works, but I believe it should be updated to [ReactDOM.createRoot] as [ReactDOM.render] is running the root API in legacy mode and will create a warning that it's deprecated.

**To Reproduce**
1. Go to [Freecodecamp react render lesson](https://www.freecodecamp.org/learn/front-end-development-libraries/react/render-html-elements-to-the-dom)

**Additional context**

For reference : this is a link to React's github discussion on the root API
[React discussion on root API](https://github.com/reactwg/react-18/discussions/5)

**P.S. To open the link in new tab, press [CTRL+click] for Windows & Linux or [CMD+click] on MacOS**

**Comment by naomi-lgbt** [comment]
Our curriculum is still running on React 16, I believe, so this migration wouldn't be possible just yet. But something we can keep in mind when we move to a project-based Front End Libraries approach. :3

**Comment by yellowsamuray** [comment]
Thank you for the information. 😁
