### ISSUE TITLE
Fix Building a Cipher Step 81 test feedback

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#52673]
### Describe the Issue

User received mis-leading feedback from test.

Feedback received:

`Sorry, your code does not pass. Keep trying. Your encryption variable should have the value of encrypt(text, custom_key).`

However if you open the console it shows an error for both variables:
`// running tests
Your encryption variable should have the value of encrypt(text, custom_key).
Your decryption variable should have the value of decrypt(encryption, custom_key).
// tests completed`

The encryption variable was ok, but the decryption variable was wrong.

User's code:
`encryption = encrypt(text, custom_key)
print(encryption)
decryption = decrypt(encryption, custom_key, -1)
print(decryption)`

I was able to pass the test by removing the 3rd argument from the decrypt function call:
`decryption = decrypt(encryption, custom_key)`

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-81

### Your code

```
encryption = encrypt(text, custom_key)
print(encryption)
decryption = decrypt(encryption, custom_key, -1)
print(decryption)


```

### Expected behavior

Feedback should indicate the problem is with the decryption variable, not the encryption variable

### Screenshots

![Screenshot 2023-12-20 191302](https://github.com/freeCodeCamp/freeCodeCamp/assets/79821659/c40b1ae2-1e08-47d1-b026-87637abc34aa)
![Screenshot 2023-12-20 191250](https://github.com/freeCodeCamp/freeCodeCamp/assets/79821659/3667f3ae-8f5a-4950-a179-8897ad9aa528)

### System

User Agent is: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

### Additional context

none

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #52448, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
