### ISSUE TITLE
Fix Broken link in Odin project challenge and update first answer - Links and Images Question H

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#52670]
### Describe the Issue

We recently got a [report](https://forum.freecodecamp.org/t/links-and-images-links-and-images-question-h/656943/2) of a broken link in the [Links and Images Questions H challenge](https://www.freecodecamp.org/learn/the-odin-project/top-links-and-images/links-and-images-question-h).

Under the assignments section, there is a link to read an article about the different image formats.
<img width="843" alt="Screenshot 2023-12-20 at 3 11 59 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/10c82c70-78bf-4167-854a-c7a5cf745557">

However, that link no longer works. 
We should use a link from our own fcc publication instead to fix this.

## How to contribute 

This is a small fix so I am opening this up for contribution for first timers only.
Please read through the fix below and read through our [contributing](https://contribute.freecodecamp.org/#/) guide.
There will be no assignment for this issue. 
Feel free to work on it and create a PR. 

## How to fix the issue

Here is the file you will be working with
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/16-the-odin-project/top-links-and-images/links-and-images-question-h.md

Replace the old link here:
```
# --assignment--

Read about the  <a href="https://www.internetingishard.com/html-and-css/links-and-images/#image-formats" target="_blank">four main image formats</a> that can be used on the web.
```

with this new change here

```
# --assignment--

Read about the  <a href="https://www.freecodecamp.org/news/image-file-types-picture-format-extensions-jpeg-gif-png-svg-tiff/" target="_blank">four main image formats</a> that can be used on the web.
```

Also, let's change the first multiple choice answer here

```
## --answers--

TIFF, GIF, PNG, and SVG.

---
```

and change it to this new option here

```
## --answers--

MOV, GIF, PNG, and SVG.

---
```

### Affected Page

https://www.freecodecamp.org/learn/the-odin-project/top-links-and-images/links-and-images-question-h

### Your code

N/A

### Expected behavior

The link should be replaced with this one here

https://www.freecodecamp.org/news/image-file-types-picture-format-extensions-jpeg-gif-png-svg-tiff/

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by bowen-anth** [comment]
Thanks, for the write up, I was the one that made the post! I didn't know FCC was open source on here. I just tried my first pull request for this, thanks!
