### ISSUE TITLE
Python Scientific Computing with Python (Beta) - Should ignore end of line whitespace

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#52685]
### Describe the Issue

The challenge is failing if there is whitespace after a colon. Python's whitespace rules aren't quite that extreme.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm/step-33

### Your code

```
    if verify_card_number(translated_card_number):
        print('VALID!')
    else: 
        print('INVALID!')

```

### Expected behavior

Python challenges should ignore end-of-line whitespace characters

### Screenshots

![with whitespace](https://github.com/freeCodeCamp/freeCodeCamp/assets/6234475/dd609e47-5d73-429e-ba99-a1151e5a416f)

![without whitespace](https://github.com/freeCodeCamp/freeCodeCamp/assets/6234475/257a993b-9efd-4d9f-84f7-0365aa664091)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: 120.0.6099.130

**Comment by ArielLeslie** [comment]
First reported in [this forum post](https://forum.freecodecamp.org/t/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm-step-33/657187)

**Comment by plamoni** [comment]
I think the problem might be here:

https://github.com/freeCodeCamp/curriculum-helpers/blob/e86048735ba32c5f28b5c64e4c3039a3a022dda0/lib/index.ts#L145C80-L145C85

The regular expression contains `(?<block_condition>${escapedBlockPattern})\\s*:\\n(?<block_body>.*?)`. The fact that the `\\n` comes directly after the `:` suggests that it simply won't match trailing whitespace. I think the fix would be to add `\\s*` directly after the `:` to be more permissive.

**Comment by gikf** [comment]
Reopening, problems with space after `else:` appear to be present again. From different challenge - https://forum.freecodecamp.org/t/learn-recursion-by-solving-the-tower-of-hanoi-puzzle-step-39/670149.

```
python-test-evaluator.ts:158 TypeError: Cannot read properties of null (reading 'block_body')
    at eval (eval at evaluatedTestString (python-test-evaluator.ts:83:13), <anonymous>:4:24)
    at evaluatedTestString (python-test-evaluator.ts:83:13)
    at new Promise (<anonymous>)
    at ctx.onmessage (python-test-evaluator.ts:78:39)
```

I don't remember if I've seen it working on production. Does anybody know?

**Comment by ilenia-magoni** [comment]
@Dario-DC and @ojeytonwilliams are working on new AST based helpers that can be used to avoid such issues.

**Comment by Dario-DC** [comment]
Do we still have this issue? Or we can close this?

**Comment by ilenia-magoni** [comment]
I have not seen reports anymore of this on the forum, closing as solved
