### ISSUE TITLE
A2 English for Developers Task 63 ("Awesome") Fails with correct capitalization

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#52682]
### Describe the Issue

The prompt is "_________. My computer and drawing tablet are great, too." and the word to fill in is "awesome". If the user correctly capitalizes the exclamation as "Awesome", the test fails. It only succeeds with lowercase "awesome".

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-63

### Your code

```
Awesome. My computer and drawing tablet are great, too.


```

### Expected behavior

Capitalization that is appropriate for the sentence structure should be accepted.

### Screenshots

![screenshot of the failure](https://github.com/freeCodeCamp/freeCodeCamp/assets/6234475/5abb57de-bd1c-4509-9e53-c250e7e2ef0d)

![screenshot of the success](https://github.com/freeCodeCamp/freeCodeCamp/assets/6234475/d41ef3ae-f8cd-4072-8405-30129bd066aa)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: 120.0.6099.109

### Additional context

First reported in [this forum thread](https://forum.freecodecamp.org/t/learn-greetings-in-your-first-day-at-the-office-task-63/657104)

**Comment by naomi-lgbt** [comment]
This should have been fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/52660 but I forgot to QA the deployment yesterday. 😭

**Comment by ArielLeslie** [comment]
What I'm hearing is "Naomi does time travel".  That's the story and we're sticking to it.

**Comment by ArielLeslie** [comment]
Closed by https://github.com/freeCodeCamp/freeCodeCamp/pull/52660
