### ISSUE TITLE
RPG Project Uninitalized Variables

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52692]
### Describe the Issue

The use of the undeclared variable on this step is confusing for some learners. Do we want to be using undeclared variables in this project?

We do note that
> Use dot notation to set the onclick property of your button1 to the variable goStore. This variable will be something you write later.

but I can definitely see how that still feels strange to users, esp this early on

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-37

### Your code

```
button1.onclick = goStore; // This variable isn't declared!!
```

### Expected behavior

minimize user friction

### System

All

**Comment by lasjorg** [comment]
The order is a little weird. We do the same in the next step with buttons 2 and 3.

I would prefer having steps 39-42 before 37-38. Or at the very least an empty function declaration. But that would move the explanation of how to write a function forward anyway.

**Comment by ShaunSHamilton** [comment]
Personally, I agree; I prefer anything referenced having been already defined. @jeremylt do you think @lasjorg 's suggestion makes sense to then close this?

> having steps 39-42 before 37-38.

That said, when I code, I often reference things I have yet to define. So, it is not like it is an uncommon thing to do.

**Comment by jeremylt** [comment]
Yeah' that seems like a reasonable fix to me
