### ISSUE TITLE
Update tests for step 1 of RPG game

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#52699]
### Describe the Issue

There seem to be a high number of posts on the forum for this step.
https://forum.freecodecamp.org/search?q=Learn%20Basic%20JavaScript%20by%20Building%20a%20Role%20Playing%20Game%20-%20Step%201%20in%3Atitle

Most have to do with this failing test

You should have a `div` element.

```js
const div = document.querySelector('div');
assert.exists(div);
```

## Edit to original post
If the user passes two opening title tags like so: `<title>RPG - Dragon Repller<title>` the wrong hint shows and that is why people are coming to the forum so much.

I do like @huyenltnguyen suggestion of adding a test to check for the correct closing tag. We have done that in previous projects so that should help here. 

If you are interested in working on this please read through the contributing docs first
https://github.com/freeCodeCamp/freeCodeCamp/blob/e8f6266405da8a85a1208f1e576aedcdaf369f8c/CONTRIBUTING.md

Here is the file that needs updating
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/5d5a813321b9e3db6c106a46.md

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-1

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by sagarkashyap989** [comment]
hello, 
i read the issue, and i have some question related to this issue,
why would you want to pass `title` closing tag incorrectly (`<title>_xyz_<title>` instead of `<title>_xyz_</title>`) ?
if we just pass normal `title` tag the code will pass successfully

**Comment by sagarkashyap989** [comment]
> I think in this case, the test failed because `<title>` doesn't have a closing tag and interferes with the next query, so maybe we need to have a test that checks for the existence of `</title>`.
> 
> If I place `<title>` above `<link>` and remove the closing tag, I'll get "Your code should have a link element.".
> 
> ```html
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8" />
>     <title>RPG - Dragon Repller</title> 
>     <link rel="stylesheet" href="style.css" />
>   </head>
>   <body>
>     <div id = "game" >
> 
>     </div>
>   </body>
> </html>
> ```
> 
> And I'm able to pass the challenge with the following code:
> 
> ```html
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8" />
>     <title>RPG - Dragon Repller</title> 
>     <link rel="stylesheet" href="style.css" />
>   </head>
>   <body>
>     <div id = "game" >
> 
>     </div>
>   </body>
> </html>
> ```


Yes you are right, but it's asked in the issue, the description that the code without proper closing tag, should pass.

**Comment by jdwilkin4** [comment]
Hey @sagarkashyap989 ! 

Yes, you are correct.
I hadn't seen the two opening title tags when I created this issue.

But we still have an issue with multiple people failing this first step with the tests pointing to the wrong reason why they are failing.

So it would be better to strengthen our tests so people know exactly why and how to pass the step.
I do like @huyenltnguyen 's idea of also checking to make sure they have opening and closing tags.
