### ISSUE TITLE
Add some keyboard shortcuts to A2 English for Developers

### ISSUE THREAD

**Issue by kmbenjel** [freeCodeCamp/freeCodeCamp#52696]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like

I wish if there's a hotkey, like Space to run the new video, sometimes Ctrl+enter does not submit the input.
Anything in this direction would be more helpful.

### Describe alternatives you've considered

NA

**Comment by gikf** [comment]
I'm not sure if that's browser specific, but I'm able to use {Ctrl + Enter} to submit the answer rather consistently (I cannot remember a case when it didn't).

I agree it'd be nice to have key that would play the video/audio, without the need to focus on it first.

**Comment by kmbenjel** [comment]
I'm not sure, my browser is the latest Chrome on MacOS (Ventura)
I could only use {Ctrl + Enter} after submitting, just to pass to the next
subject!

**Comment by naomi-lgbt** [comment]
My concern with adding a shortcut to play the audio would be ensuring it was still accessible.

**Comment by bbsmooth** [comment]
If we did a two key command that included either `Ctrl` or `Alt` then we would be fine as far as accessibility is concerned. If we wanted to do a single key command then that would be OK too as long as it would be disabled when turning off Enable Keyboard Shortcuts in the Settings.

**Comment by naomi-lgbt** [comment]
I'd be okay with something like Ctrl+Space, then.
