### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by Lucidize** [FreeCodeCamp/freecodecamp#527]
Adding checked does not let me progress. Looks like a bug as it's a simple task.

**Comment by terakilobyte** [comment]
Unable to reproduce. Ensuring both a regular checkbox and a radio button are both checked produces the expected behavior.

**Comment by Lucidize** [comment]
Must have been a bug with the browser as it has worked today. Thanks.
