### ISSUE TITLE
What is a Derivative? #hikes

### ISSUE THREAD

**Issue by jameswinegar** [FreeCodeCamp/FreeCodeCamp#5271]

**Comment by zackharley** [comment]
How in detail are these hikes supposed to be?

**Comment by jameswinegar** [comment]
@zackharley Conceptual understanding with some T/F questions at the end

**Comment by zackharley** [comment]
@jameswinegar So what kind of content should be submitted to resolve these hike issues?

**Comment by jameswinegar** [comment]
Content you think is important, T/F questions, graphics you think could be beneficial, etc.

**Comment by jameswinegar** [comment]
Consolidation as per Berkeley's Request.
