### ISSUE TITLE
[Playwright] Improve tests of the setting page to ensure inputs have associated label

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52727]
## Description

Some input fields on the setting page didn't have an associated label. This appeared to be a regression during the UI component migration, but the issue was fixed via https://github.com/freeCodeCamp/freeCodeCamp/pull/52723.

We have tests for the page, but some test cases are missing and some are using the `getByTestId()` query, which doesn't cover the accessibility aspect of the elements.

## Expectation

The files that needs to be changed are: 
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/email-settings.spec.ts
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/internet-presence-settings.spec.ts
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/settings.spec.ts

The PR should include the following changes:

- Add tests for the About Settings section, and use `getByLabel()` to query the inputs
- Add tests for the Email Settings section, and use `getByLabel()` to query the inputs
- Update the Internet Presence Settings test case to use `getByLabel()` in place of `getByTestId()`
- Update the Portfolio Settings test case to use `getByLabel()` in place of `getByTestId()`
- Remove `data-playwright-test-label` attributes that become unused after the test changes

**Comment by altsun** [comment]
Hi, I see this file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/internet-presence.spec.ts was removed

**Comment by altsun** [comment]
Hi @huyenltnguyen, I've created a PR, what new tests should I add? I'm not sure about "About Settings" section, I only find "Account Settings" in "Settings" page, and "About" input in "Personal Information" section
