### ISSUE TITLE
Test Output to Console Readability

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52724]
### Describe the Issue

Can we numerate the tests in the console output to make the output clearer?

### Affected Page

All

### Your code

```
// running tests
Your p element should have an opening tag. Opening tags have the following syntax: <elementName>.
Your p element should have a closing tag. Closing tags have a / just after the < character.
Your p element's text should be See more cat photos in our gallery. You have either omitted the text or have a typo.
Your p element should be below the h2 element. You have them in the wrong order.
// tests completed
// console output
```

### Expected behavior

```
// running tests
Test 1: Your p element should have an opening tag. Opening tags have the following syntax: <elementName>.
Test 2: Your p element should have a closing tag. Closing tags have a / just after the < character.
Test 3: Your p element's text should be See more cat photos in our gallery. You have either omitted the text or have a typo.
Test 4: Your p element should be below the h2 element. You have them in the wrong order.
// tests completed
// console output
```

### System

All

**Comment by ShaunSHamilton** [comment]
I am for this feature as well 👍

**Comment by NiharPhansalkar** [comment]
Hello, I would like to try and work on this issue.

**Comment by NiharPhansalkar** [comment]
How should this issue be solved? Since a variable as such cannot be declared inside a `.md` file, will I have to manually enter the text `Test {number}` in every file of curriculum?

**Comment by gikf** [comment]
That'd be a bit tedious. Better would be adding numbers when tests are executed. I'm not exactly sure where would be the best place to do that, but `executeChallengeSaga` or `executeTests` in https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/redux/execute-challenge-saga.js look promising for it.

**Comment by savvycolleen** [comment]
I started looking into this yesterday as well! I have the code set up and running locally on my device, and I've read over all of the contributing guidelines. I was looking at editing in the curriculum-server/data/curriculum.json (which is massive), but maybe what you listed above is better? I did just join the discord as mentioned above, so maybe I can get some advice there!
