### ISSUE TITLE
[New Python curriculum's Expense Tracker Project]: missing tests and hints, tests that are supposed to pass, and more.

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#52722]
### Describe the Issue

- some tests and hints for functions are syntactically correct, but they still fail.
- there are no tests in some steps to check whether a statement (or a piece of code) to be removed is removed. This is happening to the `pass` statement the most.
- some descriptions and hints that can be better

### Affected Page

https://www.freecodecamp.dev/learn/scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/

### Your code

Syntactically correct functions like this do not pass some tests:
```py
def add_expense():
    
```

A code like this should not pass the tests, but they do:
```py
def print_expenses(expenses):
    pass
    for expense in expenses:
        pass
```

More in the screenshots section.

### Expected behavior

- Tests should pass for syntactically correct functions
- Functions with the pass statement and content in them should pass tests
- Some hints should not have in them the precise code to add 

## Some tests and hints for functions are syntactically correct, but they still fail
     - step 1: this should pass because the function has already been defined:
![Screenshot 2023-12-22 at 7 37 47 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/b16d0e4a-043a-4784-bd8c-f00d2d962483)

The test did not pass until the `pass` statement was added. It's the same for step 6, and other functions:

![Screenshot 2023-12-22 at 7 43 45 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/c4de1618-a80f-417d-8287-fa33a25893a1)

## Some tests are not checking whether a statement (or a piece of code) to be removed is removed. This is happening to the `pass` statement the most. Screeshots below.
     - step 7: the tests should not pass because the function has the `pass` statement right inside it:
 
![Screenshot 2023-12-22 at 7 51 03 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/ef5b1961-6f36-4c91-a3e4-9c12f3bcb9b1)

     It's the same for step 16:

![Screenshot 2023-12-22 at 7 53 51 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/190741a5-8577-4568-bdd4-151962fc9c12)

The steps that follow every step using the `pass` statement should be checked for issues like this.
    - step 15: the test should pass because the test variable is already removed, so the next hint should be about removing the `print` statement:
    
![Screenshot 2023-12-22 at 7 57 39 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/f8e8b9e6-b558-4ff8-a6a5-bffc75b66a5b)

## Descriptions and hints that can be better
     - step 18: campers might not know they need to have the `return` statement here. It is better to specifically mention the `return` statement:
     
![Screenshot 2023-12-22 at 8 00 56 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/c2413919-71a0-42fc-89fa-a3a4789e4caf)

     - step 25: to avoid confusion, it is better to have a description like `After the print() call, add another print statement to print the string 1. Add an expense.`
  
![Screenshot 2023-12-22 at 8 06 01 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/d0f68b28-69b9-4a6f-ad3e-b1aec0556d04)

     - step 28: Many hints, like this specifically show the code to add. While it is not bad on all occasions, it would be better not to do it where the code is not that hard to guess. For example, the hint here can be like "You should have an input statement with the text `Enter your choice: '`. Assign it to a `choice` variable."
     
![Screenshot 2023-12-22 at 8 09 57 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/f641e37c-505d-4ba2-8476-e211f85457bb)

     - step 29: the hint here can be written like "You should have an if statement with condition choice == 1":
     
![Screenshot 2023-12-22 at 8 17 09 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/8e54cb1e-9c1b-4477-a3f5-82f086f85453)

By the way, the test isn't even passing. It seems there's no hint for the code `amount = input()`.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
> Some tests and hints for functions are syntactically correct, but they still fail
The test did not pass until the pass statement was added. It's the same for step 6, and other functions:

There needs to be _something_ in function, otherwise that's a `SyntaxError`.

**Comment by Ksound22** [comment]
> > Some tests and hints for functions are syntactically correct, but they still fail
> > The test did not pass until the pass statement was added. It's the same for step 6, and other functions:
> 
> There needs to be _something_ in function, otherwise that's a `SyntaxError`.

I think that's an `IndentationError` instead. 

Don't you think a test for the `def` keyword and the function identifier should pass, then there should be a separate test to check for the `pass` statement?

**Comment by Dario-DC** [comment]
The tests for this project have been written in a very short time. They need to be improved.

To be able to pass the test by writing the function declaration without the body, it's necessary to write a test that does not run the code. Otherwise, if you don't add `pass` or something else inside the body, you get an indentation error.

To do this consistently for every project in the curriculum, I think it would be convenient to modify the helper that retrieves the function body, since it does not work if the function is empty.

**Comment by gikf** [comment]
> I think that's an `IndentationError` instead.
> 
> Don't you think a test for the `def` keyword and the function identifier should pass, then there should be a separate test to check for the `pass` statement?

Hm, you might be right about the specific error.

I do agree splitting it into two tests would be an improvement.

**Comment by jeremylt** [comment]
The screenshot for step 1 is also missing the required parameters. Do the tests check for those?

**Comment by Ksound22** [comment]
> The screenshot for step 1 is also missing the required parameters. Do the tests check for those?

A separate test should check for the parameter.

**Comment by Dario-DC** [comment]
There's already a separate test that checks for the parameters. If you mean a separate test for each parameter, since this is the third project, it might still have sense to include those.

**Comment by ShaunSHamilton** [comment]
It sounds like we have three improvements here:
1) Add tests for all _aspects_ of instructions (e.g. If instructions say "remove x", there should be a test that `x` is removed)
2) Unless required for the lesson, tests should be written to accept code that "does not run"
3) Tests should be split into multiple parts. Especially, in the earlier sections of the curriculum

Personally, I would be fine with this being all done in 1 PR.

---

Something related is: https://github.com/freeCodeCamp/freeCodeCamp/issues/52448

That is, it can be confusing to get the first hint as the "failure condition", even thought the issue is an unrelated syntax error.

**Comment by Dario-DC** [comment]
I agree that getting the first hint even when the issue is not related with that bit of code is very confusing. To avoid it, tests should be probably restructured for the entire curriculum.
