### ISSUE TITLE
forum help post, markdown issue

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#52735]
The help post now has this header:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/e81d43a9-2d6d-4d16-86be-3dc1e1f132d4)
which is `### ### Your code so far`
It should have only one set of hashtags.

**Comment by edwinhung** [comment]
Could you clarify where you see this? I don't seem to have this issue on my end.

**Comment by ieahleen** [comment]
I did not specify, sorry, it's for posts that have the following message
```
WARNING

The challenge seed code and/or your solution exceeded the maximum length we can port over from the challenge.

You will need to take an additional step here so the code you wrote presents in an easy to read format.

Please copy/paste all the editor code showing in the challenge from where you just linked.
```
