### ISSUE TITLE
Fix issue in step 9 Calorie Counter

### ISSUE THREAD

**Issue by goobric** [freeCodeCamp/freeCodeCamp#52731]
### Describe the Issue

I have followed the exact instructions for step 9
reset page
hard reset page
same error
see attached screen images

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-9

### Your code

```
<div class="controls">
            <span>
              <label for="entry-dropdown">Add food or exercise:</label>
              <select id="entry-dropdown" name="options" />
              <button id="add-entry" type="button">Add Entry</button>
            </span>
          </div>
```

### Expected behavior

The current tests to pass:
// running tests
You should add a button element to your span element.
Your button element should come after your select element.
Your new button element should have an id attribute set to add-entry.
Your new button element should have the text Add Entry.
// tests completed

### Screenshots

![231223_fCC_JS_CC_err01step9](https://github.com/freeCodeCamp/freeCodeCamp/assets/23141638/ca85f4dd-298b-4022-aa0e-4a0b754148c9)
![231223_fCC_JS_CC_err02step9](https://github.com/freeCodeCamp/freeCodeCamp/assets/23141638/ca570c21-1c87-44ee-a4d7-33a3a93b0994)

### System

- Device: [Laptop]
- OS: [Ubuntu 22.04]
- Browser: [Fire Fox]
- Version: [121]

**Comment by goobric** [comment]
hi @huyenltnguyen 
Thank you, yes I noticed this afterwards! :-/
I was focusing on the Error provided by fCC regarding the code; therefore I was focusing on what was wrong with the <button> element and its associated code.
It is a shame that the 'Test' didn't state that the closing select element wasn't present!

**Comment by goobric** [comment]
...with the button element...

**Comment by jai12789** [comment]
Your HTML code looks mostly correct, but there is an issue with the placement of the closing tag for the <select> element. The <select> element should have closing tags </select> rather than a self-closing tag.

This Should be the code 

<div class="controls">
  <span>
    <label for="entry-dropdown">Add food or exercise:</label>
    <select id="entry-dropdown" name="options"></select>
    <button id="add-entry" type="button">Add Entry</button>
  </span>
</div>
