### ISSUE TITLE
RPG step 58: clarify instructions

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52734]
### Describe the Issue

I think we can make the instructions more clear. They are a bit confusing.

> Add one final property to the object named `text`. Give this property the same string value as the one assigned to `text.innerText` in the `goTown` function.

Or something like that.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-58

### Your code

```



```

### Expected behavior

Clear instructions.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-58/657565

**Comment by jdwilkin4** [comment]
I think that is much clearer.

We can open this up for contribution 👍

**Comment by ytrkptl** [comment]
Hi, is someone working on this issue? If not, I'd like to contribute.
