### ISSUE TITLE
Syntax errors prevent tests running without clear indication (other than in console)

### ISSUE THREAD

**Issue by ovr58** [freeCodeCamp/freeCodeCamp#52749]
### Describe the Issue

Can not pass the code checking, nothing happens.
entering the string and pressing the check button has no effect and I can't get through this step.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-asynchronous-programming-by-building-an-fcc-forum-leaderboard/step-41

### Your code

```
const allCategories = {
  299: { category: "Career Advice", className: "career" },
  409: { category: 'Project Feedback', className = 'feedback' }
};


```

### Expected behavior

after pressing 'Check Your Code' button message must appear bellow it and text on the button must change to some thing like 'Go to the next step'

### Screenshots

![Снимок экрана 2023-12-24 170054](https://github.com/freeCodeCamp/freeCodeCamp/assets/106969823/526b4d30-82b5-478d-b96b-6b64d8efe522)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
There's syntax error in the above code:
```
SyntaxError: unknown: Invalid shorthand property initializer. (10:49)

   8 | const allCategories = {
   9 |   299: { category: "Career Advice", className: "career" },
> 10 |   409: { category: 'Project Feedback', className = 'feedback' }
     |                                                  ^
  11 | };
  12 |
  13 | const timeAgo = (time) => {
```

I'm going to leave issue open for now, as it might be worth improving how this problem is communicated (other than in console, which might not be open).

**Comment by ovr58** [comment]
Yes I know about this error. but should not the pressing the test button gets a msg or something - the issue is that nothing happens when I press the button
![Снимок экрана 2023-12-24 173521](https://github.com/freeCodeCamp/freeCodeCamp/assets/106969823/567d2871-8426-4cec-8093-a0fc3df26f04)

**Comment by ovr58** [comment]
expected the msg like one on the screenshot but it is not there when mistakes on the step mentioned above
![Снимок экрана 2023-12-24 173855](https://github.com/freeCodeCamp/freeCodeCamp/assets/106969823/a168d53e-0778-4d13-8d01-a2c00a671264)

**Comment by ShaunSHamilton** [comment]
The Python curriculum has the opposite problem. If there is a syntax error, the first hint shows as the "failure" reason.

In the Python curriculum's case, there are two kinds of test:
1) Just testing the Camper\s code as a string
2) Testing the Camper's code by evaluating it

As far as I am aware, we always evaluate the JS code. So, I think we are best with a default message showing up:
> Your code failed to run. Check the console for more information.

**Comment by jdwilkin4** [comment]
I vote for showing a default message since this comes up frequently in the forum. 

I am going to go ahead and open this up for contribution to get the ball rolling

**Comment by Ksound22** [comment]
Aren't we supposed to close this issue now since [#54694](https://github.com/freeCodeCamp/freeCodeCamp/pull/54694) has fixed it?

**Comment by naomi-lgbt** [comment]
I think this is fine to close, yeah
