### ISSUE TITLE
False positive on cafe menu step 64

### ISSUE THREAD

**Issue by Richy-28** [freeCodeCamp/freeCodeCamp#52757]
### Describe the Issue

False positive on cafe menu step 64,
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-64
Was able to pass the test with incorrect coding,

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-64

### Your code

```
<p> <a href="https://www.freecodecamp.org"<p> Visit our website</a></p> 



```

### Expected behavior

Test should fail.

### System

- Device: [Desktop]
- OS: [Windows 11]
- Browser: [Chrome]
- Version: [120.0.6099.111]

**Comment by lasjorg** [comment]
I would suspect there are multiple instances of this throughout the curriculum seeing how good the browser is at ignoring and "fixing" errors in HTML. I'm not sure it is possible to account for all of them and I'm sure we do not want to litter the test code with regular expressions.

Has using an HTML validator as part of the code checking been considered? It would catch a lot of malformed HTML and I imagine its output can be piped into our test output (somehow?).

**Comment by iprime2** [comment]
Hey @Richy-28 @lasjorg, I have solved this issue by matching the a/anchor tag with the exact HTML syntax.
```
<a href="https://www.freecodecamp.org"><p>Visit our website</a>
```

By using/adding this code we can assert the correct format of a/anchor tag
```js
assert(/<a\s+href="https:\/\/www\.freecodecamp\.org">Visit our website<\/a>/.test(document.querySelector("footer > p > a").outerHTML));
```

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/29702609/55bb46dc-4057-4a48-8825-767fede0b4df)

I hope you like my solution, please let me know if it satisfy requirment so I can push and create pull request.

**Comment by ShaunSHamilton** [comment]
> I would suspect there are multiple instances of this throughout the curriculum seeing how good the browser is at ignoring and "fixing" errors in HTML. I'm not sure it is possible to account for all of them and I'm sure we do not want to litter the test code with regular expressions.

For this reason, this is expected behaviour. The browser automatically "fixes" a lot of HTML syntax issues. The resultant HTML is what the instructions ask for. As such, we allow the code to pass.

We much prefer lenient tests to too strict regex. Also, often, we just care about the outcome more so than the exact implementation.

---

> Has using an HTML validator as part of the code checking been considered?

https://github.com/freeCodeCamp/freeCodeCamp/issues/46463
