### ISSUE TITLE
Todo App: Step 17 forEach callback implicit return

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52768]
### Describe the Issue

I'm not sure I see the point of the `forEach` callback having an implicit return seeing as you can't use the return for anything. I don't know that it helps code readability either.

Current final code:

```
const updateTaskContainer = () => {
  tasksContainer.innerHTML = "";

  taskData.forEach(
    ({ id, title, date, description }) =>
      (tasksContainer.innerHTML += `
      <div class="task" id="${id}">
        <p><strong>Title:</strong> ${title}</p>
        <p><strong>Date:</strong> ${date}</p>
        <p><strong>Description:</strong> ${description}</p>
        <button onclick="editTask(this)" type="button" class="btn">Edit</button>
        <button onclick="deleteTask(this)" type="button" class="btn">Delete</button> 
      </div>
    `)
  );
};
```

With callback function body:

```
const updateTaskContainer = () => {
  tasksContainer.innerHTML = "";

  taskData.forEach(({ id, title, date, description }) => {
    tasksContainer.innerHTML += `
      <div class="task" id="${id}">
        <p><strong>Title:</strong> ${title}</p>
        <p><strong>Date:</strong> ${date}</p>
        <p><strong>Description:</strong> ${description}</p>
        <button onclick="editTask(this)" type="button" class="btn">Edit</button>
        <button onclick="deleteTask(this)" type="button" class="btn">Delete</button> 
      </div>
    `;
  });
};
```

If we want an implicit return, I would prefer a map. The exact formatting is up for debate.

```
const updateTaskContainer = () => {
  tasksContainer.innerHTML = taskData
    .map(
      ({ id, title, date, description }) => `
        <div class="task" id="${id}">
          <p><strong>Title:</strong> ${title}</p>
          <p><strong>Date:</strong> ${date}</p>
          <p><strong>Description:</strong> ${description}</p>
          <button onclick="editTask(this)" type="button" class="btn">Edit</button>
          <button onclick="deleteTask(this)" type="button" class="btn">Delete</button> 
        </div>
      `
    )
    .join("");
};
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-17

### Your code

```



```

### Expected behavior

No implicit return or a map. I guess it is just a matter of opinion.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
I am personally leaning towards No implicit return for this step and the following seed code.

**Comment by ShaunSHamilton** [comment]
I definitely prefer the second code example using the `forEach(() => {...})`.

**Comment by jdwilkin4** [comment]
## Note to interested contributors

This issue has been opened up for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

Starting with step 17, we will remove the implicit return as discussed and use the following pattern `forEach(() => {...})`.
Make sure to update the appropriate tests and seed code for steps 18- end including the final solution found in the last step.

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

Happy coding!

**Comment by v-i-k-a-s** [comment]
Hi @jdwilkin4  ,
Have make changes in regular expression , seed code and hint from step17-step58 , to allow pattern `forEach(() => {...})`.
Let me know in case if i  missed something 
Thanks
