### ISSUE TITLE
[RPG Project] - Unclear instructions for step 77

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#52778]
### Describe the Issue

I had no clue what the challenge actually wanted. It's only when I saw the hint text that I realized what it actually wanted. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-77

### Your code

```
function buyHealth() {
  if(gold >= 10)
  {
    gold -= 10;
    health += 10;
    goldText.innerText = gold;
    healthText.innerText = health;
  }
}
```

### Expected behavior

I would suggest rephrasing the challenge text ,making it clear that the goal is to create a placeholder conditional with the literal word "condition" being required in the condition spot. 

### System

- Device: Desktop 
- OS: Windows 10
- Browser: Firefox
- Version: 121.0

**Comment by jdwilkin4** [comment]
I agree that the directions could be more clear about the placeholder for the condition.

We could just restate the hint text in the initial directions.

This could be the new last line in the directions,

```md
For now, your `if` statement should have the string `condition` for the condition.
```

**Comment by a2937** [comment]
Won't the hint text have to be changed as well to accommodate? I mean hints don't offer anything of value if they completely restate what's in the directions.

**Comment by jdwilkin4** [comment]
> I mean hints don't offer anything of value if they completely restate what's in the directions.

I don't think this is necessarily true. 
Sometimes people rush through a challenge and miss it the first time in the directions.
Then when it pops up again in the hints, and they are not able to pass, they are able to pass the challenge.
Sometimes people just need to see it again a few times before it clicks to what the issue is.

Take a look at [step 20](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-20) of the RPG game. The directions say to declare a variable called xp. 
Then we have a test that says the same thing here:

You should declare a variable named `xp`.

```js
assert.match(code, /xp/);
```

**Comment by a2937** [comment]
I do see what you mean. However, maybe we shouldn't completely restate the whole line word per word? A slight reword might be nice.

**Comment by jdwilkin4** [comment]
That rewording works for me 👍 

This is a small enough fix that it can be opened up for first timers only contribution 

## Information for interested first time contributors

Here is the file you will need to update

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8c4db0710f3260f867a92.md

Change the text from

```md
For now, follow that pattern to use a string condition inside your if statement.
```

to this updated version here

```md
For now, the `if` statement condition should be set to the string `condition` as a placeholder. 
```

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

Happy coding!

**Comment by JackBerezhnov** [comment]
I would like to contribute to this change and I already fixed the file, but for some reason when I try to write git add 62a8c4db0710f3260f867a92.md. It gives me that "fatal: pathspec '62a8c4db0710f3260f867a92.md' did not match any files"
Did I miss something? Thank you!

**Comment by jdwilkin4** [comment]
@JackBerezhnov 

You will need to reference the complete file name

```bash
git add curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8c4db0710f3260f867a92.md
```
