### ISSUE TITLE
Purpose of accessibility button on English video player

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#52771]
### Describe the Issue

There is an "accessibility" button in the bottom right corner of the video player for the new English courses. Currently, the only function of this button seems to be toggling the captions on and off. Is this button going to do anything else? If not, then I suggest we use a closed caption icon instead and change the name of the button to "closed captions" and use the `aria-pressed` attribute to manage its state.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-1

### Steps to Reproduce

N/A

### Expected behavior

Captions off:
```
<button aria-label="closed captions" aria-pressed="false"> ... </button>
```
Captions on:
```
<button aria-label="closed captions" aria-pressed="true"> ... </button>
```

### System

N/A

**Comment by Sahillather002** [comment]
can you pls provide the icon you want to replace , i will work to change it .

**Comment by ShaunSHamilton** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/52543#issuecomment-1858694870

Sounds like it is currently planned to just toggle captions. In this case, we can go with changing the icon **used** here: https://github.com/freeCodeCamp/freeCodeCamp/blob/34347235df5a93291798e90623179ae4b5df31b9/client/src/templates/Challenges/components/scene/scene.tsx#L203

_As an aside_, I would also change the logic to `showDialogue`.

**Comment by ShaunSHamilton** [comment]
YouTube adds that red, bottom border:

| Unpressed | Pressed |
| ------------ | -------- |
| <img width="143" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/e6af846d-128b-420d-9ce5-f8fae1d4903d"> | <img width="128" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/5b12f1d4-d833-4465-b46d-aca33dd16ca3"> |
