### ISSUE TITLE
Missing instructions for Step 6 of the JS Beta Certification - Learn Basic JavaScript by Building a Role Playing Game

### ISSUE THREAD

**Issue by leta91** [freeCodeCamp/freeCodeCamp#52774]
### Describe the Issue

Hi,
I noticed that partial instructions are given to complete step 6 (that is part of the Beta version of the new JS certification)

The current instructions at step 6 say:
"Similar to your `#stats` element, your `#monsterStats` element needs two `span` elements. Give them the class `stat` and give the first element the text `Monster Name: ` and the second the text `Health: `. After the text in each, add a `strong` element **with an empty nested `span` element**."

At step 7 the HTML code has the two `span`, those created in the previous step after `Monster Name: ` and `Health: ` ,with respectively:

- `<span id="monsterName"></span>`
- `<span id="monsterHealth"></span>`

Also _at step 34 and 35_ the `id` of these two `span` are both used in the code

**Instructions at step 34:**

"Just like you did with the buttons, create variables for the following `id`s and use `querySelector()` to give them the element as a value:

`text`, `xpText`, `healthText`, `goldText`, `monsterStats`, and `monsterName`.

Remember to declare these with the `const` keyword, and name the variables to match the `id`s."

**Instructions at step 35:**

Finally, use `querySelector()` to get the `#monsterHealth` element. Because you have already declared a `monsterHealth` variable earlier, you need to use a different variable name for this element.

Declare a new variable with the `const` keyword and name it `monsterHealthText`.

### Affected Page

 https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-6

### Your code

```
     <div id="monsterStats">

     </div>
```

### Expected behavior

I think the instructions of step 6 should include the request to:

- add to the the two `span` (created after the texts `Monster Name: ` and `Health: ` )
the `id` of `monsterName` for the first `span` and the `id` of `monsterHealth` for the second `span`

### Screenshots

![step6fCC](https://github.com/freeCodeCamp/freeCodeCamp/assets/109817389/7b653dd3-ad9b-494b-a58f-846b8eadfdb4)

![step7fCC](https://github.com/freeCodeCamp/freeCodeCamp/assets/109817389/af41e869-09cf-478a-a4ef-c7bf554e7bcb)

### System

Device: [e.g. iPhone 6, Laptop]
OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
Browser: [e.g. Chrome, Safari]
Version: [e.g. 22]

**Comment by leta91** [comment]
@huyenltnguyen You are welcome 👍

**Comment by jdwilkin4** [comment]
Hey @leta91 ! 

Good catch! 

We will go with @huyenltnguyen phrasing for the updated instructions.

We will go ahead and open this up for a `help wanted `contribution
