### ISSUE TITLE
Inefficient solution for the "Problem 78: Coin partitions" challenge.

### ISSUE THREAD

**Issue by WOLFRIEND** [freeCodeCamp/freeCodeCamp#52772]
### Describe the Issue

When trying to run tests on the local machine, one of them failed with the following error:
`AssertionError: expected 51999 to equal 55374`.
The test that fails is related to: `curriculum/challenges/english/18-project-euler/project-euler-problems-1-to-100/problem-78-coin-partitions.md`

This behavior occurs on a freshly forked repository without any changes made.
But, strangely, in the web interface itself https://www.freecodecamp.org/learn/project-euler/project-euler-problems-1-to-100/problem-78-coin-partitions when you click the `Run the Tests (Ctrl + Enter)` button or in the pipelines, this error does not exist.

### Affected Page

https://www.freecodecamp.org/learn/project-euler/project-euler-problems-1-to-100/problem-78-coin-partitions

### Your code

Running the following command:
```
pnpm run test:curriculum
```

Causes the error:
```
oleksandr.tkachenko@SOF-X-L-2301 freeCodeCamp % pnpm run test:curriculum

> @freecodecamp/freecodecamp@0.0.1 test:curriculum /Users/oleksandr.tkachenko/WOLFRIEND/Dev/freeCodeCamp
> cd ./curriculum && pnpm test


> @freecodecamp/curriculum@0.0.0-next.4 test /Users/oleksandr.tkachenko/WOLFRIEND/Dev/freeCodeCamp/curriculum
> ts-node ./node_modules/mocha/bin/mocha.js --delay --exit --reporter progress --bail

⠧ Populate tests.


  23923 passing (4m)
  116 pending
  1 failing

  1) Check challenges
       Check challenges (english)
         project-euler-problems-1-to-100
           Problem 78: Coin partitions
             Check tests against solutions
               Solution 1 must pass the tests:
     Test text: <p><code>coinPartitions(1000000)</code> should return <code>55374</code>.</p>
  AssertionError: expected 51999 to equal 55374
      at eval (eval at ctx.onmessage (http://127.0.0.1:8080/js/test-evaluator-bb607458058e945d60ce.js:18292:26), <anonymous>:46:8)
      at ctx.onmessage (http://127.0.0.1:8080/js/test-evaluator-bb607458058e945d60ce.js:18292:26)



 ELIFECYCLE  Test failed. See above for more details.
 ELIFECYCLE  Command failed with exit code 1.

```

### Expected behavior

The test should be passed successfully without any errors.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/41586082/60a43714-c947-47ea-acb5-e7725e28ae0a)

### System

- Device: MacBook Pro, 16-inch, 2021, Apple M1 Max.
- OS: macOS Sonoma 14.2.1 (23C71).
- Browser: N/A.
- Version: N/A/
- Node version: v20.10.0.
- pnpm version: 8.12.1.
- MongoDB version: 7.0.2.

### Additional context

This behavior was first discussed with @huyenltnguyen here: https://github.com/freeCodeCamp/freeCodeCamp/issues/52750#issuecomment-1868991073.

I'll try to investigate more in this issue and figure out how to fix it. But, if you have any idea what this might be related to, I would be grateful if you point me in the right direction.

**Comment by gikf** [comment]
Test is checking if solution in the file - https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/18-project-euler/project-euler-problems-1-to-100/problem-78-coin-partitions.md#--solutions-- - passes tests for the challenge.

The final test for Project Euler challenges usually require solution that's efficient. If it's not efficient enough it might fail in some conditions/environments.

**Comment by weilirs** [comment]
so the current solution in the file - [main/curriculum/challenges/english/18-project-euler/project-euler-problems-1-to-100/problem-78-coin-partitions.md#--solutions--](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/18-project-euler/project-euler-problems-1-to-100/problem-78-coin-partitions.md?rgh-link-date=2023-12-26T08%3A17%3A53Z#--solutions--) - is not efficient enough?

**Comment by lasjorg** [comment]
The solution code does pass.

But if you add the final test directly in the editor you can also see it is triggering the infinite loop protection. Not sure why the local test is halted (if that is the case) but the online test is allowed to run to completion.

**Comment by jeremylt** [comment]
I can research a faster solution

**Comment by WOLFRIEND** [comment]
If you run this solution in any sandbox, just separately, in isolation from tests, it works correctly and returns the correct result. But, apparently, this solution is too resource-intensive, and therefore the test fails with an error. Perhaps it exceeds the test time limits or something like that.

Although the test passes successfully on the web page, when creating a pull-request, there is a checkmark indicating:
"I have tested these changes either locally on my machine, or GitPod."

And accordingly, people cannot honestly check it, since the test will fail.

I'm also still trying to find a faster solution. But there may even be a problem in setting up the test environment.

**Comment by WOLFRIEND** [comment]
I believe that I managed to find a new solution that gives the same result, and I've created a pull request with the updated solution: https://github.com/freeCodeCamp/freeCodeCamp/pull/52880.
This solution is ~ x2 times faster, and all tests are passed:

<img width="928" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/41586082/9a5051cc-ce1d-45c0-8245-9475afd850aa">

Could, you, take a look, please?
