### ISSUE TITLE
RPG Step 118 instructions are not clear enough

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#52781]
### Describe the Issue

The tests are requiring that the variable `monsterHealth` be used to set `monsterHealthText.innerText` but this is not mentioned in the instructions and the hint for this test is vague at best.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-118

### Your code

This code is technically correct but not accepted:

```
function goFight() {
  update(locations[3]);
  monsterHealth = monsters[fighting].health;
  monsterStats.style.display = "block";
  monsterName.innerText = monsters[fighting].name;
  monsterHealthText.innerText = monsters[fighting].health;
}
```

Changing the last line to use `monsterHealth` is required to pass:

```
function goFight() {
  update(locations[3]);
  monsterHealth = monsters[fighting].health;
  monsterStats.style.display = "block";
  monsterName.innerText = monsters[fighting].name;
  monsterHealthText.innerText = monsterHealth;
}
```

### Expected behavior

The hint you get when you use `monsterHealthText.innerText = monsters[fighting].health;` is:

"You should set the `innerText` property of `monsterHealthText` to be the `health` value of the current monster. Remember that you assigned this value to a `monsterHealth` variable."

The first sentence in this hint is stating something that is already true but makes it sound like it is false. Using `monsters[fighting].health` is a valid way to get the `health` value of the current monster. So the user has fulfilled the requirement of the first sentence but is being told they haven't, which is confusing. Reminding them in the second sentence that they have already saved this value off to the `monsterHealth` variable might help some people make the connection that the tests want them to use that variable instead of `monsters[fighting].health`, but I have just been going back and forth with someone in the forums that isn't getting this message, so I don't think it is explicit enough.

If the tests are going to require that the variable `monsterHealth` be used then I think the instructions need to explicitly state this. Perhaps something like:

> Now, set the `innerText` property of `monsterName` to be the `name` property of the current monster. Do the same for `monsterHealthText` and the `health` property. Recall that you have already saved off the monster's health in the `monsterHealth` variable. You must use this variable to set the `innerText` for the monster's health.

And then the hint can be updated to be more explicit as well.

> You must use the `monsterHealth` variable to set the `innerText` for the monster's health.

### System

N/A

**Comment by jdwilkin4** [comment]
Hey @bbsmooth ! 

I agree with updating the directions here because this step does come up a lot on the [forum](https://forum.freecodecamp.org/search?expanded=true&q=118%20%23javascript).

Since this is a small fix, I will go ahead and open this up for contribution for first timers only
