### ISSUE TITLE
MathJax is not rendered in upper jaw

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#52794]
### Describe the Issue

MathJax is not rendered in upper jaw, this means new JS and Python curriculum.
Example:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/60067306/87643008-862d-4e07-a74e-1980a9b99df1)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-46

### Steps to Reproduce

1. Go to challenge from new JS or Python curriculum, which includes MathJax tags.
2. See MathJax is not rendered.

### Expected behavior

MathJax properly rendered in the description in the upper jaw, for example:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/60067306/58327f48-0d34-4b7a-b438-37de3b22d613)

### System

n/a

**Comment by ShaunSHamilton** [comment]
Thanks for bringing this up. I did look into this a while back, but it is currently very convoluted to add MathJax to the multifile editor.

My current suggestions are:
1) Try add the script manually to each Markdown file that needs it
2) Change the step to use HTML to render the equations

Otherwise, maybe someone braver than me can attempt to overhaul the MathJax logic.

**Comment by gikf** [comment]
Do you recall any specific caveats? This is what I did when I was making the _fixed_ screenshot above https://github.com/gikf/freeCodeCamp/commit/edd6841eb2599426e6d3ea7cff58d425821b5881. Comparing it with how it's added elsewhere  (https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/components/side-panel.tsx), other than not checking if it's a specific block or superBlock, or if MathJax was loaded before; it doesn't seem more complicated. I guess adding the skipped checks could be creating the troubles?

**Comment by ShaunSHamilton** [comment]
> Do you recall any specific caveats?

_Sooo many_ caveats 🙃 . I just didn't think to add this line to the editor 🤦‍♂️ 

```js
mathJaxScriptLoader();
```

One thing we might want to double-check is whether anything needs changing for `client/utils/tags.tsx` as well.
