### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue 

### ISSUE THREAD

**Issue by charlesrb** [FreeCodeCamp/freecodecamp#528]
The link for bootstrap stylesheet is too long for the column.

![bootstrap_stylesheet](https://cloud.githubusercontent.com/assets/11678482/7813911/dabf0d00-03be-11e5-83dd-c0d637983bb4.jpg)

**Comment by QuincyLarson** [comment]
Thank you for spotting this! I've fixed this issue.
