### ISSUE TITLE
Potentially confusing use of brackets in challenges text

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52809]
### Describe the Issue

Example:

> Use the `+=` operator to add `Your [weapon] breaks.`

I think it is easy to misinterpret this in challenges where bracket notation is used in the code, as it is in this project.

Not sure what the solution is. I feel like this might also be another instance where the lack of string notation is an issue.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-155

### Your code

```



```

### Expected behavior

Do not use [initializer/literal syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators#primary_expressions) in the challenge guide text to avoid confusion.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-155/658923

**Comment by jdwilkin4** [comment]
Maybe we could wrap the word weapon in a set of `<>`

<img width="589" alt="Screenshot 2023-12-29 at 4 04 45 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/6cfd31b3-c2a6-4ebf-966b-3b95d744f27d">

**Comment by lasjorg** [comment]
That would work better.

It does have the potential of being interpreted as an HTML tag. But in the context of what the challenge is asking for that shouldn't be an issue.

I do not have a better suggestion. So I'd say we go with `<>`

I assume the change affects more than just this step but I'm not sure how often `[]` is used in this and other challenges.

**Comment by jdwilkin4** [comment]
> I assume the change affects more than just this step but I'm not sure how often [] is used in this and other challenges.

Yeah, I am not really sure how many other steps this occurs in. 
I guess for now we can open up this issue for first timers contribution 👍 

## Note to first time contributors 

This issue has been open up for first timers only contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

The file you need to change is this one
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa226207f33d3ad4c6f546.md

Please apply the changes discussed here
https://github.com/freeCodeCamp/freeCodeCamp/issues/52809#issuecomment-1872397826

Happy coding!

**Comment by jdwilkin4** [comment]
It looks like we found three more instances of this issue in these steps here 

https://github.com/freeCodeCamp/freeCodeCamp/pull/52844#pullrequestreview-1799613052

To anyone interested in working on this issue, please make sure to make the updates to step 155 and the other steps listed in the comment above

**Comment by luqmanalzobe** [comment]
Hello, I have now gone ahead and updated my pull request and fixed the other steps including 119, 120, and 128 alongside 155.
