### ISSUE TITLE
JavaScript Algorithms and DataStructures (beta): console tab is always closed by default

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [freeCodeCamp/freeCodeCamp#52802]
### Describe the Issue

If the student opened console tab while doing some challenge step
then, after submitting correct solution for the step, and being redirected to next challenge step,
they will end up with the console tab being closed.

Such flow may be considered not the best user experience, especially for users, who would prefer to have the console tab always opened while working with JavaScript code.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8

### Steps to Reproduce

1. Go to some challenge step. I guess any would do, but I will drop a link to one of them. <https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-35>
2. Open the console.
3. Complete the challenge. The correct solution for the one mentioned above is to add the line `pauseButton.addEventListener("click", pauseSong);`
4. Hit the `Submit and go to next challenge` button.
5. After being redirected to the next step's page, you should see that the console is closed again.

### Expected behavior

I see two possible options for the expected behaviour:

#### To make console be opened always by default
My personal opinion is that it would be more comfortable for working with JS, rather than have console closed by default. This is subjective though. It may be not the best experience for those who would prefer to use console only from time to time while going through lessons.
As an example of such experience, the old **JS course** or React lesson from **Front End Development libraries** course may be used.
<https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/>
<https://www.freecodecamp.org/learn/front-end-development-libraries/#react>
#### To make console be opened or closed based on the console state from previous challenge
If I would have the console opened while doing this step <https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-35>,
after completing challenge and going for next one (<https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-36>),
console should be also opened.

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: [e.g. 22]

**Comment by Piyush-onGIT** [comment]
I would like to work on this issue.

**Comment by ShaunSHamilton** [comment]
I see two PRs here:
1) Default the console to open for JS curriculum
2) Save controls (tabs) state to browser local storage

To close this issue, I suggest we just go with 1. The second will require more discussion about priority.

---

@scissorsneedfoodtoo Do you have an opinion about defaulting the console to be open for the new JS stuff?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for the mention, @ShaunSHamilton.

A contributor who reviewed very early versions of the project-based JS curriculum suggested that we keep the console open by default for all the new JS projects, and I agree. Many include steps that involve logging things to the console, and learners can any syntax errors more easily.

Like you mentioned, this can be handled with at least two PRs. The first can keep the console open by default for the JS curriculum, and the second can deal with storing learner preferences for the console state to local storage. I do like the behavior suggested by @huyenltnguyen, too, though it will require more discussion.

**Comment by naomi-lgbt** [comment]
Rather than defaulting to the console being open, which **is not something we can do on mobile**, I think the instructions should be updated to explicitly mention how to check the console.

**Comment by moT01** [comment]
This has some good discussion, but it is quite stale. Going to close this in favor of a more recent duplicate issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/55619
