### ISSUE TITLE
Music Player step #67: userData.songs is not highlighted

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [freeCodeCamp/freeCodeCamp#52805]
### Describe the Issue

![for the #67 step 2023-12-28 190405](https://github.com/freeCodeCamp/freeCodeCamp/assets/108119145/f8f8a970-f5c5-4885-a6af-cdf2a7834902)

As can be seen on the picture, in the instructions for the step, the last mentioning of `userData.songs` is not highlighted like other variables, method names etc. usually are. Examples on the picture would be `filter()` or `song.id`. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-67

### Your code

```



```

### Expected behavior

`useData.songs` at the very end of the instructions should be highlighted.

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: [e.g. 22]

**Comment by iprime2** [comment]
Here is Screenshot to the fix.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/29702609/37d63c38-eba5-43b9-9a89-e43382bf5cb3)
