### ISSUE TITLE
Music Player #59: only part of the code snippet is highlighted correctly 

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [freeCodeCamp/freeCodeCamp#52806]
### Describe the Issue

The error message has a correct line of code for solution.
```js
song?.title ? `Play ${song.title}` : "Play"
```
Part of it is highlighted, part of it is not(red shape on the picture below).
![musicplayer-issue-step59-2023-12-28 205058](https://github.com/freeCodeCamp/freeCodeCamp/assets/108119145/7ea95384-7ce8-4239-aeb0-0f13728e0cba)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-59

### Your code

```js
const setPlayButtonAccessibleText = () => {
  const song = userData?.currentSong || userData?.songs[0];
  playButton.setAttribute(
    "aria-label",
    song?.title ? `Play ${song.title}` : "Playy" // intentional typo to make the error message show up
  );
};


```

### Expected behavior

In the error message, the whole line
```js
song?.title ? `Play ${song.title}` : "Play"
```
should be highlighted.

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: [e.g. 22]

**Comment by ieahleen** [comment]
already fixed in #52745
