### ISSUE TITLE
RPG step 6 spaces - HTML formatting issue

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52811]
### Describe the Issue

Prettier formatted HTML will fail the "Health" text test. If you add text to the nested span you can see the spacing is correct.

```
<div id="monsterStats">
  <span class="stat">
    Monster Name: 
    <strong>
      <span></span>
    </strong>
  </span>
  <span class="stat">
    Health: 
    <strong>
      <span></span>
    </strong>
  </span>
</div>
```

The test is also relying on `textContent` for the space which won't allow for proper formatting.

I'm not sure what the best option is here but having the camper add placeholders would allow us to test for the space more easily.

```
<div id="monsterStats">
  <span class="stat">
    Monster Name: 
    <strong>
      <span>Slime</span>
    </strong>
  </span>
  <span class="stat">
    Health: 
    <strong>
      <span>10</span>
    </strong>
  </span>
</div>
```

```
const spans = document.querySelectorAll(`#monsterStats > span`);
spans[0].innerText.includes('Monster Name: Slime')
spans[1].innerText.includes('Health: 10')
```

Tests: https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a23d1c5f1c93161f3582ae.md

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-6

### Your code

```



```

### Expected behavior

Proper formatted HTML should not fail the test.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-6/659144

I know they also added an extra space but the issue remains the same.

**Comment by jdwilkin4** [comment]
I was playing around with it locally, and was able to pass the test using your prettier formatted code with the following modifications to these tests here

```js
const spans = document.querySelectorAll(`#monsterStats > span`);
spans[0].innerText.includes('Monster Name: ');
```

```js
const spans = document.querySelectorAll(`#monsterStats > span`);
spans[1].innerText.includes('Health: ');
```

```js
const spans = document.querySelectorAll(`#monsterStats > span`);
assert.match(spans[0].innerHTML, /Monster Name:\s+[\s\S]<strong>/);
assert.match(spans[1].innerHTML, /Health:\s+[\s\S]<strong>/);
```
>I'm not sure what the best option is here but having the camper add placeholders would allow us to test for the space more easily.

Maybe instead of using placeholders we can modify the last test above to check for additional spaces

<img width="724" alt="Screenshot 2023-12-29 at 4 19 01 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/8045fe12-0c95-4593-aed1-783a62bb8962">

**Comment by lasjorg** [comment]
Isn't the second test failing? Or are you saying replace the first and second tests with the third?

Using a regex is always an option. I would prefer not using regex but it might be a better option than having to make changes to challenge text and the seed code.

**Comment by jdwilkin4** [comment]
yeah, I think some sort of regex based solution is probably the way to go.
I'll go ahead and open this up for contribution 👍

**Comment by Aksshay88** [comment]
@lasjorg I am interested to solve the issue 
will you assign me this issue

**Comment by lasjorg** [comment]
@Aksshay88 There is already a PR in progress.

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
