### ISSUE TITLE
[Odin project] HTML Foundations Questions H, I and J have duplicate text

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#52824]
### Describe the Issue

These three challenges in the HTML foundations have the exact same text.

https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-h
https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-i
https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-j

We should update the text for all three lessons so the campers doesn't have to the read the same text again.

happy to hear suggestions 😃 

### Affected Page

https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-h

https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-i

https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-j

### Your code

N/A

see explanation 

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by KhushiSharma0313** [comment]
As a new contributor, I'm eager to propose unique and engaging content to address the duplicate text in HTML Foundations Questions H, I, and J on The Odin Project.


HTML Foundations Question H:
Proposed Update:
Let's jump into the world of HTML with an exciting project: building a virtual art gallery. Picture HTML tags as your artistic tools, shaping and showcasing your collection online. Whether it's paintings, digital art, or photography, we'll use HTML to create an interactive online gallery that brings your creativity to life.

HTML Foundations Question I:
Proposed Update:
Ready to take your HTML skills up a notch? Let's build an engaging online portfolio. Each HTML element is like a dedicated space for your various projects—your own digital exhibit. We'll use HTML to craft a sleek and functional portfolio that not only showcases your work but also makes it easy for visitors to explore and appreciate your talent.

HTML Foundations Question J:
Proposed Update:
Now, let's dive into the world of CSS! In this challenge, HTML forms the solid foundation of a dynamic blog, and CSS steps in to add that visual charm. Together, we'll create a blog that's not just informative but visually appealing. Imagine HTML as the structure and CSS as the artist's brush, giving your blog a unique and captivating look.

**Comment by lasjorg** [comment]
Are we even allowed/supposed to change the text?

My suggestion would be the same as in the other issue, combine the steps. Also, we might want to add some of the missing resources linked to on the original page.

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

**Comment by jdwilkin4** [comment]
> Are we even allowed/supposed to change the text?

According to the beta page [here](https://www.freecodecamp.org/learn/the-odin-project/), it does have this message at the bottom

> This course is unofficial, and not endorsed by The Odin Project. Changes to The Odin Project curriculum content have been made, and all instructional material for this course is licenced under [CC-BY-SA-NC 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

It looks like we are able to "remix" and "adapt" it to our liking as mentioned here 
https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by lasjorg** [comment]
I didn't see that. The only issue I can see is the ShareAlike stipulation.

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

I'm not sure if there are any issues with the BSD 3-Clause License we use and the CC-BY-SA-NC 4.0 stipulation.

---

Anyway, it seems like a lot of new text would be needed just to spread out the questions over multiple challenges. It would be easier to combine some of the questions on the same page. It doesn't really make sense to me to have the same text in so many places just because we want the questions spread out over multiple challenges.

**Comment by Sembauke** [comment]
Hey Everybody,

I am open to suggestions, I will be refining these questions starting from this week. The main problem for many of the projects are that there's not enough text to spread them out over multiple challenges without duplicating text.

I am not sure about adding more text that's not present in The Odin Project. That just seems plain wrong, as it will change the original feel of this awesome project.

Also remember that repetition is important.

**Comment by jdwilkin4** [comment]
Are we not able to have multiple questions on the same page like @lasjorg suggested?

**Comment by Sembauke** [comment]
We could do this, yes. If that is the best option. I will get that going.

**Comment by jdwilkin4** [comment]
Yeah, I personally like that option 👍
