### ISSUE TITLE
[Odin project] HTML Foundations Questions A and B have duplicate text

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#52821]
### Describe the Issue

The first two challenges in the HTML foundations have the exact same text.

https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-a
https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-b

I feel like it would be better to update the text for one of these challenges so campers don't read through the same thing twice.

The text is mainly talking about the structure and syntax of an HTML element.
So it feels like that text better matches the question in lesson B. 

So we could probably just update the text for lesson A.

### Affected Page

https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-a

### Your code

n/a

See explanation above

### Expected behavior

We shouldn't have duplicated text instructions for two lessons in a row

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Piyush-onGIT** [comment]
I would like to work on this issue

**Comment by jdwilkin4** [comment]
Hey @Piyush-onGIT ! 

Thank you for your interest in contributing. 

Any issue labeled with the `first-timers-only` or `help-wanted` label is up for grabs.

Right now, this issue is waiting for triage by the core freeCodeCamp team members and contributors and it is not open for contribution yet.

You can read more about our Contributing docs here
https://contribute.freecodecamp.org/#/

**Comment by lasjorg** [comment]
Is there a reason for not just combining the two as they are on the original page?

https://www.theodinproject.com/lessons/foundations-elements-and-tags

I don't think having two questions on the same step should be an issue.

**Comment by jdwilkin4** [comment]
> I don't think having two questions on the same step should be an issue.

I am going to defer to @Sembauke on this one since he led the development on these challenges 👍
