### ISSUE TITLE
[Odin project] HTML Foundations Questions C has missing backticks for index.html mention

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#52822]
### Describe the Issue

In [lesson C](https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-c), each time `index.html` is mentioned it is wrapped in backticks. But the last time it is mentioned, there are no backticks. For consistency, we should update the last mention of `index.html` to be wrapped in backticks.

## Proposed change

Here is the file that needs updating

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/16-the-odin-project/top-learn-html-foundations/html-foundations-question-c.md

Here is the change needed in this sentence here

```md
This is because web servers will by default look for an `index.html` page when users land on your websites - and not having one will cause big problems.
```

## How to contribute

This issue is open to `first timers only` for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

Happy coding!

### Affected Page

https://www.freecodecamp.org/learn/the-odin-project/top-learn-html-foundations/html-foundations-question-c

### Your code

N/A

see explanation above

### Expected behavior

see explanation above

## Before 

<img width="802" alt="Screenshot 2023-12-29 at 7 58 03 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/fc65f49c-5e60-4e3a-8d47-5c739ade62c4">

## After
<img width="788" alt="Screenshot 2023-12-29 at 7 59 43 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/5401f695-1848-4b1b-b12b-47e83b7f6ac3">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Piyush-onGIT** [comment]
I want to work on this, I am a first timer.

**Comment by annimukherjee** [comment]
Hi, 
I too would like to contribute to this issue!

I feel it would be a great entry into open-source contribution...
