### ISSUE TITLE
Music Player Step 59: Not accepting the mixing of single and double quotes

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#52823]
### Describe the Issue

In Step 59 of the Music Player project, the following code is valid as JavaScript code, but our test doesn't accept it. Notice that `aria-label` and `Play` are wrapped with different quotes.

```js
playButton.setAttribute('aria-label', song?.title ? `Play ${song.title}` : "Play");
```
or
```
playButton.setAttribute("aria-label", song?.title ? `Play ${song.title}` : 'Play');
```

The test is here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/72188ba85b57cadee5680630d9f154dd22839e8b/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/6555de565387a2efe90a6ccc.md?plain=1#L34-L38

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-59

### Your code

Reported in these forum posts:
https://forum.freecodecamp.org/t/step-59/659525
https://forum.freecodecamp.org/t/learn-basic-string-and-array-methods-by-building-a-music-player-step-59/658715

### Expected behavior

- If we want to allow the mixing of single and double quotes, we should fix the test.
- If not, we should add a hint to guide users to use either single or double quotes.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25644062/f3230b8f-aecd-4cb8-bb81-6dfbfb81a222)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
Yeah, I agree that campers should be able to pass with either types of quotes because technically they did get the question right.

I have opened this up for contribution 👍
