### ISSUE TITLE
Learn Introductions in an Online Team Meeting: task 95 requires two full stops in a row after abbreviation

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52839]
### Describe the Issue

I'm no language genius but I don't think the requirement is correct. I'm not sure you are supposed to use two full stops in a row after an abbreviation. Not sure if both are correct or what?

https://www.sussex.ac.uk/informatics/punctuation/capsandabbr/abbr#:~:text=Note%20also%20that%2C%20when%20an,full%20stops%20in%20a%20row

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-introductions-in-an-online-team-meeting/task-95

### Your code

```



```

### Expected behavior

Maybe don't end the sentence in an abbreviation if it makes it unclear.

Or do not require two full stops.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

forum: https://forum.freecodecamp.org/t/learn-introductions-in-an-online-team-meeting-task-95/659832

**Comment by igorgetmeabrain** [comment]
I agree that this could be unnecessarily confusing. I also believe that it is technically incorrect to end a sentence with two full stops (periods) even when the sentence ends with an abbreviated word. As I understand it (grammatically) the single full stop serves a dual purpose in this case.

**Comment by Sahillather002** [comment]
Should we add comma to first full stop ? 
If yes i am happy to do so?

**Comment by lasjorg** [comment]
I would agree with that. But I would assume that's also more work than just removing the period at the end.

**Comment by ShaunSHamilton** [comment]
@lasjorg Oh. Right. I completely forgot the video/audio matched the sentence.

In that case, I change my suggestion to just removing the period oat the end.
