### ISSUE TITLE
Incorrect variable name in Step 5 of merge sort algo

### ISSUE THREAD

**Issue by MrAndyStorey** [freeCodeCamp/freeCodeCamp#52837]
### Describe the Issue

In step 5 of the merge sort algorithm it asks you to use the variable name right_array, upon doing so the hint tells you to use right_part instead (which is right given step 4 asks you to create the left_part).

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-5

### Your code

```
def merge_sort(array):
    middle_point = len(array) // 2
    left_part = array[:middle_point]
    right_part = array[middle_point:]
```

### Expected behavior

as above

### Screenshots

<img width="668" alt="Screenshot 2023-12-30 at 20 32 33" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/77452018/6a028e4d-0c7d-4413-9827-aa8c33bc41c8">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #52833, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
