### ISSUE TITLE
Learn Basic JavaScript by building an RPG game step 129 wrong hint

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#52849]
> You should add the result of `Math.floor(gold + monsters[fighting].level * 6.7)` to `gold`.
> 
> `assert.match(defeatMonster.toString(), /gold\s*\+=\s*Math\.floor\(\s*monsters\[fighting\]\.level\s*\*\s*6\.7\s*\)/);`

the hint text should not have `gold +` inside `Math.floor`

**Comment by ieahleen** [comment]
This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8eefe2e68b66ac563816b.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by altsun** [comment]
Hi, I would like to work on this
