### ISSUE TITLE
Statistical Hikes #hikes

### ISSUE THREAD

**Issue by jameswinegar** [FreeCodeCamp/FreeCodeCamp#5285]
Please add comments for some of the below hike ideas, an example description is provided for "[What is Statistics?](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5285#issuecomment-164360710)"

- [ ] What is Statistics?
- [ ] What is Probability?
- [ ] What is a Mean?
- [ ] What is a Standard Deviation and Variance?
- [ ] What is a Probability Distribution?
- [ ] What is a Normal Distribution?
- [ ] What is a Binomial Distribution?
- [ ] What is an Exponential Distribution?
- [ ] What is a Poisson Distribution?
- [ ] What is AB Testing?
- [ ] What is a t-test?
- [ ] What is a Hypothesis?
- [ ] What is a p-value?
- [ ] What is Bayes Theorem?
- [ ] What is Analysis of Variance?
- [ ] What is Bootstrapping?
- [ ] What is a Markov Chain?
- [ ] What is Regression?

**Comment by jameswinegar** [comment]
What is Statistics
------------------------
A hike defining what statistics is.

"Statistics is the study of data including how you collect, organize, transform, analyze, and present it"

Example statistic problems, bioinformatics, data aggregation, etc.

How to make sense of your data, someone can't be 20 meters tall etc.

Mention common terms and reference that they'll be introduced in other hikes.

1) Is statistics the study of numbers? F
2) Is data presentation a part of statistics? T
3) Do statisticians clean data? T

**Comment by cdikibo** [comment]
#What is a Standard Deviation and Variance

Variance is the sum of squared deviations of each observation from the mean divided by the sample size aka n-1 

Standard Deviation is the "typical" departure of an observation from the mean or simply put the square root of the variance 

1) Is degree of freedom and n-1 different? F

**Comment by cdikibo** [comment]
# What is a Mean

Mean is the sum of all individual observations divided by the number of observations(n) or simply put the average value

**Comment by cdikibo** [comment]
# What is a Probability Distribution

Probability Distribution is a frequency distribution about which predictions can be made.

**Comment by cdikibo** [comment]
# What is a Binomial Distribution

Binomial Distribution applies to random variables that take on only a finite and specified number of values or categories 

Real life examples 
* coin toss
* gender 
* games of chance

**Comment by cdikibo** [comment]
# What is a Normal Distribution 

Normal Distribution applies to random variables that can take on an infinite number of values

**Comment by cdikibo** [comment]
# What is a Poisson Distribution

Poisson Distribution is used to test for the *random pattern hypothesis*, which states that the pattern of items in space or time is random 

Procedure for Poisson 
1. Obtain a random sample
2. Calculate the mean 
3. Calculate P 
4. Multiply P by total number sampling units n to get expected number sampling units for each Xi
5. Test for goodness of fit using X^2

**Comment by QuincyLarson** [comment]
I am moving these to individual issues on https://github.com/FreeCodeCamp/hikes/issues/
