### ISSUE TITLE
Linear Algebra #hikes

### ISSUE THREAD

**Issue by jameswinegar** [FreeCodeCamp/FreeCodeCamp#5286]
Please add comments for some of the below hike ideas, an example description is provided for "[What is Statistics?](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5285#issuecomment-164360710)"

- [ ] What is a Vector?
- [ ] What is a Matrix?
- [ ] What is a Determinate?
- [ ] What is a Vector Space?
- [ ] What is a Span?
- [ ] What is a Basis?
- [ ] What is a Derivative?
- [ ] What is an Integral?
- [ ] Finding the Minimum and Maximum of Functions!
- [ ] What is an Eigenvalue?
- [ ] What does Orthogonal mean?
- [ ] What is the Gram-Schmidt Process?

**Comment by QuincyLarson** [comment]
Moved to individual hikes issues.
