### ISSUE TITLE
Wrong answer is the correct one in [Learn Greetings in your First Day at the Office - Task 24]

### ISSUE THREAD

**Issue by FairyPenguin** [freeCodeCamp/freeCodeCamp#52869]
### Describe the Issue

[Learn Greetings in your First Day at the Office - Task 24](https://forum.freecodecamp.org/t/learn-greetings-in-your-first-day-at-the-office-task-24/660072)

The speaker says "Let me show you to your desk".

but the answers are different the right answer is "the conference room" which wasn’t in the dialogue, the right answer should be "The desk".

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-24

### Your code

```

The answers here missing the right answer

```

### Expected behavior

The speaker says "Let me show you to your desk".

but the answers are different the right answer is "the conference room" which wasn’t in the dialogue, the right answer should be "The desk".

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/37639473/9c61c34c-1e44-476b-bb08-261f9eed5183)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #52708, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
