### ISSUE TITLE
Machine Learning #hikes

### ISSUE THREAD

**Issue by jameswinegar** [FreeCodeCamp/FreeCodeCamp#5287]
Please add comments for some of the below hike ideas, an example description is provided for "[What is Statistics?](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5285#issuecomment-164360710)"

- [ ] What is Machine Learning?
- [ ] What is Hadoop?
- [ ] What is Spark?
- [ ] What is Linear Regression?
- [ ] What is Logistic Regression?
- [ ] What is Feature Engineering?
- [ ] What are Clustering Algorithms?
- [ ] What is K-Means?
- [ ] What is Bayesian Statistics?
- [ ] What is a Neural Network?
- [ ] What is Deep Learning?
- [ ] What is a Stochastic Process?
- [ ] What is Brownian Motion?
- [ ] What is a Gaussian Process?
- [ ] What is a Support Vector Machine?
- [ ] What is a Random Forest?
- [ ] What is Monte Carlo?
- [ ] What is Random Sampling?
- [ ] What is Natural Language Processing?

**Comment by QuincyLarson** [comment]
I've added these to https://github.com/FreeCodeCamp/hikes/issues/
