### ISSUE TITLE
A typo in A2 English for Developer - Learning greetings in your first day at the office.

### ISSUE THREAD

**Issue by Neonnati** [freeCodeCamp/freeCodeCamp#52870]
### Describe the Issue

Jake is explaining the purpose of his visit to Sarah. He's there to hand over something that Sarah needs, which will permit him (should be her) access to certain areas.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-154

### Your code

<!DOCTYPE html>
<html lang="en"
<head></head>
<body></body>
</html>

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Next step has similar error.

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-155
> What is Sarah referring to with `it` in his question `Is it contactless?`

Should be
> What is Sarah referring to with `it` in **her** question `Is it contactless?`

**Comment by rijuoddusual1999** [comment]
Hii @Neonnati @huyenltnguyen @gikf  excellent catch. Solved it locally, will be raising a PR soon. This my first valid pull request, pls assign me if possible

**Comment by rijuoddusual1999** [comment]
Hii @huyenltnguyen @gikf @Neonnati fixed the typos in both the task (154 & 155)

![Screenshot from 2024-01-02 02-12-12](https://github.com/freeCodeCamp/freeCodeCamp/assets/113231164/41ef596c-5414-4766-9a00-23f872c95831)


![Screenshot from 2024-01-02 02-11-39](https://github.com/freeCodeCamp/freeCodeCamp/assets/113231164/d1bdeff1-c25f-4947-92d6-a3073c90c8a8)


Hope it clear all the test and get merged
