### ISSUE TITLE
How do Computers work? #hikes

### ISSUE THREAD

**Issue by jameswinegar** [FreeCodeCamp/FreeCodeCamp#5288]
Please add comments for some of the below hike ideas, an example description is provided for "[What is Statistics?](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5285#issuecomment-164360710)"

- [ ] How does RAM work?
- [ ] How does a CPU work?
- [ ] How does a GPU work?
- [ ] What does a Motherboard do?
- [ ] How do Hard Drives work?

**Comment by QuincyLarson** [comment]
I've added these to https://github.com/FreeCodeCamp/hikes/issues/
