### ISSUE TITLE
Standard Hikes #hikes

### ISSUE THREAD

**Issue by jameswinegar** [FreeCodeCamp/FreeCodeCamp#5289]
Please add comments for some of the below hike ideas, an example description is provided for "[What is Statistics?](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5285#issuecomment-164360710)"

- [ ] How to use Regular Expressions!
- [ ] Introduction to Markdown!
- [ ] What Is Continuous Delivery?
- [ ] What is Continuous Integration?
- [ ] What is an IDE?
- [ ] Introduction to the Command Line!
- [ ] What is Build Automation?
- [ ] What are Unit Tests?
- [ ] What is Test Driven Development?
- [ ] Style Guides for Programmers?
- [ ] What is an API?
- [ ] Basic Error Handling!
- [ ] What is Version Control?
- [ ] Why Comment your code?
- [ ] What is Object Oriented Programming?
- [ ] What is Imperative Programming?
- [ ] What is Vagrant?
- [ ] What is Docker?
- [ ] What is NPM?
- [ ] What is Bower?
- [ ] What is SQL?
- [ ] What is NoSQL?
- [ ] What are the differences between NoSQL and SQL?
- [ ] What is a Data Structure?
- [ ] What makes a File System?
- [ ] What is a Graph?
- [ ] What is a Tree?
- [ ] What is an Array?
- [ ] What is a Dictionary?
- [ ] What is a Linked List?
- [ ] Searching through a Linked List vs Array!
- [ ] What is a Hash Table?
- [ ] What is a Queue?
- [ ] Different types of trees!
- [ ] What is a Matrix?
- [ ] What is a Data Frame?
- [ ] Shortest Path on a Graph!
- [ ] What makes an algorithm?
- [ ] What is an Embarrassingly Parallel Algorithm?
- [ ] What are Threads?
- [ ] What is a Compiler?
- [ ] What is a Linker?
- [ ] What is an Interpreter?
- [ ] What is Assembly?
- [ ] What is a Kernel?
- [ ] What is Cache?
- [ ] What is Just-in-Time Compilation?
- [ ] What is a Java Virtual Machine?
- [ ] What is Garbage Collection?
- [ ] What are Ports?

**Comment by ltegman** [comment]
For Types of Trees @zackharley mentioned Binary search trees and AVL trees. I'd add B-Trees and Red-Black trees.

**Comment by QuincyLarson** [comment]
I've made all these ideas individual issues on our Hikes repo
