### ISSUE TITLE
Legacy JS Certification should be labeled with "Legacy" and moved on profile page

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52902]
### Describe the Issue

The Legacy curriculum all have the "Legacy" label in front of them except the old JS curriculum:

<details>
<summary>Map</summary>

<img width="523" alt="Screenshot 2024-01-02 at 7 41 02 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/fbc4e5d4-f7d5-479c-90d1-de96e45775df">

</details>

<details>
<summary>Superblock Page</summary>

<img width="572" alt="Screenshot 2024-01-02 at 7 41 46 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/5569b9bb-b8cf-4940-b478-203b23a700f4">

</details>

<details>
<summary>Settings</summary>

<img width="514" alt="Screenshot 2024-01-02 at 7 42 15 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/d140b841-d8ed-422e-a9e7-8b650ace1912">

</details>

<details>
<summary>Certification</summary>

<img width="850" alt="Screenshot 2024-01-02 at 7 40 26 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/d54dc730-492c-4799-ad9c-e4ef0f5725d1">

</details>

In all the images above, it should say "Legacy JavaScript Algorithms and Data Structures"

Also, on the profile page, it should be moved to the Legacy area:

<details>
<summary>image</summary>

<img width="599" alt="profile" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/698916e5-fcc4-42a9-85c0-6f7317c9ef76">

</details>

**Comment by rijuoddusual1999** [comment]
@moT01 can you kindly pls share the steps to reproduce, if it is possible

**Comment by Asin-Junior-Honore** [comment]
I can work on this.

**Comment by Asin-Junior-Honore** [comment]
@moT01 I can work on this.

**Comment by ShaunSHamilton** [comment]
@moT01 I do not see anything more to discuss here. Shall we open this for contribution or handle it internally?

**Comment by mmatsumoto1026** [comment]
Should we also put the label in front of the old JS curriculum title in `.breadcrumb-left`?

**Comment by mmatsumoto1026** [comment]
It seems that in the unordered list element under the Legacy Full Stack Certification heading in setting page we include the old JS curriculum title.

Should we only show the title with "Legacy" label?

Or, with modifing the logic of `fullStackClaimable` variable, should we allow campers who have the old and/or new JS curriculum certification to claim the Legacy Full Stack Certification, then show the title such as `JavaScript Algorithms and Data Structures (Legacy and/or Beta)`?

**Comment by ieahleen** [comment]
reopening as the PR was reverted
