### ISSUE TITLE
Bonfire: Pig Latin - Incorrect test case

### ISSUE THREAD

**Issue by dakshshah96** [FreeCodeCamp/FreeCodeCamp#5291]
In Bonfire: Pig Latin, one of the test cases is: `translate("glove")` should return `"oveglay"`.

Whereas according to Pig Latin, `translate("glove")` is supposed to return `"lovegay"`.

<img width="291" alt="screenshot 2015-12-14 20 56 36" src="https://cloud.githubusercontent.com/assets/7896438/11789070/4109db14-a2a5-11e5-9a0a-b851f8f6b62f.png">

**Comment by manurampandit** [comment]
Though from example, it seems like the problem statement should be modified to say repeat till you find consonant(s) but this is not what is expected from this problem. May I know what correctness did you found out in this issue from your end to close this issue?
