### ISSUE TITLE
Stripe js has a memory leak

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#52910]
### Describe the Issue

After using the learn platform for a while, the heap size used by stripe starts growing.

Here are the contexts from chrome browser's memory tab related to the leak:
js-stripe.com:m-outer-***
js-stripe.com:controller-***
js-stripe.com:payment-request-inner-google-pay-***
pay.google.com:payframe

Here is how we are using stripe in the client
@stripe/react-stripe-js: 1.16.5: used for card element and payment button (payment-wallets)
@stripe/stripe-js 1.54.2: used to loadStripe in multiple components and used to redirectToCheckout for the update-stripe-card page.

The redirectToCheckout has been newly introduced that might be causing this issue.

### Affected Page

https://www.freecodecamp.org/

### Screenshots

<img width="527" alt="Screenshot 2024-01-03 at 12 07 22 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/dda0fbab-1a06-405d-aa66-74086b540275">

### System

chrome on mac

### Additional context

Here is a link to a related forum topic for additional context: https://forum.freecodecamp.org/t/stripe-memory-leak-slower-and-slower-fcc-page/660102

**Comment by Sembauke** [comment]
When does the memory leak? Any specific steps that need to be followed? 

@ahmaxed
