### ISSUE TITLE
A2 English Task 95 - Incorrect Grammar

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52923]
### Describe the Issue

The expected answer for the final blank is `Corp.`, but this means that the sentence ends as `from FCC Corp..`

Using two periods at the end of a sentence is incorrect. In English, one period will handle both the abbreviation of corporation and the termination of the sentence.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-introductions-in-an-online-team-meeting/task-95

### Your code

N/A

### Expected behavior

Correct grammar should be used.

Chicago Manual of Style: https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Punctuation/faq0040.html

MLA Style: https://style.mla.org/abbreviation-period-end-sentence/

Grammarly: https://www.grammarly.com/blog/period/

### System

All

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #52839, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

**Comment by jeremylt** [comment]
Ack, my searching was poor!
