### ISSUE TITLE
[Music Player project] Update explanation for sort method

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52936]
## Describe the bug

The first issue is the challenge expects inline `return` and doesn't accept the following code:

```js
const shuffle = () => {
  userData?.songs.sort(() => {
    return Math.random() - 0.5;
  });
};
```

The second issue is the explanation of the `sort()` method is quite rush. We tell the user how to fix the default behavior of the method by adding a callback with `a` and `b`, but we don't explain what they are and how the result of `a - b` would determine the sort order.

And the instruction of the challenge could be improved a bit. Instead of:

> Use the `sort()` method on the `userData?.songs` array. For the callback, introduce `Math.random()`, and subtract `0.5`.

We could perhaps change it to:

> Use the `sort()` method on the `userData?.songs` array. Pass a callback to the method, within the callback, return the result of `Math.random() - 0.5`.

## Affected page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-62

## Additional context

This was brought up by some campers in Discord:
- https://discord.com/channels/692816967895220344/718214639669870683/1190332221110886480
- https://discord.com/channels/692816967895220344/718214639669870683/1192118266815062076

(The users didn't elaborate on what's confusing. The issues listed are from me trying out the challenge myself.)

**Comment by bbsmooth** [comment]
Ya, I ran into this about a week ago. I guess I was too lazy to open an issue though :disappointed:  

https://forum.freecodecamp.org/t/learn-basic-string-and-array-methods-by-building-a-music-player-step-62/658928

I think we need to do more than just give them the callback to copy and paste. We need to explain what `sort` expects the callback to return, which will help make sense as to why we are subtracting `0.5` from `random`.

**Comment by jdwilkin4** [comment]
I don't think the numbers example here to introduce the `sort` method is a good one to use here. That example would be better used in the number sorter project later on. 

I think this challenge should use a different example to explain the `sort` method. 

Here is my proposal for the updated challenge

# --description--

The `sort()` method converts elements of an array into strings and sorts them in place based on their values in the `UTF-16` encoding.

```js
const names = ["Tom", "Jessica", "Quincy", "Naomi"];
names.sort() // ["Jessica", "Naomi", "Quincy", "Tom"]
```

The `sort()` method also accepts a callback function which you can use to randomize an array. One way to randomize an array of items would be to subtract `0.5` from `Math.random()` which produces random values that are either positive or negative. This makes the comparison result a mix of positive and negative values, leading to a random ordering of elements.

```js
const names = ["Tom", "Jessica", "Quincy", "Naomi"];
names.sort(() => Math.random() - 0.5);
```

Use the `sort()` method on the `userData?.songs` array. Pass a callback to the method, and return the result of `Math.random() - 0.5`.

**Comment by lasjorg** [comment]
> The `sort()` method also accepts a callback function which you can use to randomize an array.

To me, this sentence almost makes it sound like randomizing is the purpose of the callback. It is fine to say that you can use the callback to randomize, but it should not be the first mention of what the callback is used for. It is a compare function that defines the sort order.

> The `sort()` method accepts a compare callback function that defines the sort order....some explanation of how it works. It can also be used to randomize an array by...some explanation of how it works.

The MDN page has a tabel which might be useful when explaining the callback.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by jdwilkin4** [comment]
I like that approach of introducing sort earlier.
I can work on a PR to update these changes 👍
