### ISSUE TITLE
[Football Team Cards] Step 30 should clarify if truthiness check is expected

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52937]
### Describe the Issue

The challenge asks the user to:

> use a ternary operator to check if `isCaptain` is true.

So the following code should pass:

```js
<h2>${name} ${isCaptain === true ? '(Captain)' : ''}</h2>
```

But the challenge only accepts truthiness check:

```js
<h2>${name} ${isCaptain ? '(Captain)' : ''}</h2>
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-30

### Expected behavior

I think either the instruction should be changed to:

> use a ternary operator to check if `isCaptain` is truthy.

Or the test should accept the explicit `=== true` check.

**Comment by jdwilkin4** [comment]
> Or the test should accept the explicit === true check.

I vote we update the tests to accept both valid answers
