### ISSUE TITLE
[python]: cipher/step-75 instructions

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#52931]
### Describe the Issue

Instructions need to be adjusted. The current state is:

>Modify the if condition by calling .isalpha() on char.
```
if char == ' ':
```

Follow this to the letter, and you get:
```
if char.isalpha() == ' ':
```

However the solution is:
```
if char.isalpha():
```

Proposed change to the instruction:
>Delete the `if` condition `char == ' '` and replace it by calling the `isalpha()` function on `char`. `if` should execute if `char` is letters.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-75

### Your code

```
NA


```

### Expected behavior

NA

### Screenshots

NA

### System

NA

**Comment by gikf** [comment]
I saw also one or two cases when camper changed it to exactly correspond do the current code:
```python
if not char.isalpha():
```
But adding `not` is in the next step.

**Comment by pkdvalis** [comment]
> But adding `not` is in the next step.

I've noticed this in a few places. Sometimes you need to ignore the logic and implement the instructions word for word. Other times understanding the logic will help you solve the challenge.

Maybe in cases like this we can notify the user to ignore the logic of the step, and if this is just an interim step that the logic isn't complete yet and just to follow the instructions.

As an overall guiding philosophy of instruction, I'm a fan of introducing the tool, .isalpha() in this case, and then giving pseudo code-like logic to implement. Explaining `isalpha()` is already well done in Step 75, imo.

We could then give pseudo code to implement:

>Modify your `if` statement condition so that it will execute if `char` is all letters.

This way they are implementing the logic of the sentence into code, not just blindly adding `isalpha()` to `char`.

Then maybe later as a hint we can be more explicit:
>Delete the condition `char == ' '` and replace it by calling the `.isalpha()` function on `char`
