### ISSUE TITLE
Cannot get inside of the existing button tag element with cursor

### ISSUE THREAD

**Issue by charleyblue** [FreeCodeCamp/FreeCodeCamp#5293]
Hi, I an unable to insert the cursor into the button element to continue with this lesson. I cleared the browsers cache (Chrome) and came back and am still unable to insert my cursor.

Challenge [Waypoint: Style Text Inputs as Form Controls](http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
      </div>
    </div>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by SaintPeter** [comment]
What do you mean by "Can't Get Inside" - you mean you can't place the cursor in?  What happens when you click?  Can you use the arrow keys on your keyboard to move the cursor around?  Can you select/delete the button and re-type it?

This code: ` <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>` looks correct.  How were you able to create that?

**Comment by charleyblue** [comment]
Hi Rex,

So, while at school on an enterprise version of Windows 7, I got to a point
in the subject lesson where I could not insert the cursor into the button
tag. Up to that lesson, I could insert the cursor thorough out the code
editor. I cleared the browser cache, rebooted the system but still was not
able to click into certain areas. And, no, it was really weird as the
cursor would jump to the end of the editor if I tried arrow keys. I was
able to progress through the lessons until I got to this particular one and
then all weirdness broke out!

However, the IT tech had done some updating earlier in the morning and I am
not sure if this is causing issues. I was getting Windows error messages so
I left a note for the tech and will have to wait until tomorrow to see if
he was able to take care of the OS issues. Then I'll see if I can repeat
the issue in the editor. I am able to continue with the lessons on my home
system. Thank you for getting back to me.

Warmest Wishes,

Charley Blewett

**Comment by SaintPeter** [comment]
I'm going to close this as a user/configuration specific issue.  If you find that you are able to reproduce across multiple systems/platforms, then let us know.

What was not clear to me is why you couldn't navigate the cursor using the arrow keys.

**Comment by acoombs12** [comment]
Possible solution:
I was having the same issue with this lesson. I could not get my cursor to go beyond line 68 in the code and needed to work on line 70. I tried in both Safari and Chrome with arrow keys and clicking on line 70 and the cursor would not go there. My system runs El Capitan for the OS. While in Chrome I put my cursor as far as it would go (Start of line 69) and hit the delete button. Now I am able to get my cursor into the line 70.

**Comment by wumpafruits** [comment]
I'mhaving this same exact issue right now. I can't click into the text below line 68. I can't insert my code accomplish one of the goal's exercises.

**Comment by sneakykate** [comment]
You know what seemed to work (same problem in Chrome, El Capitan), was deleting a few blank lines from the top.

**Comment by wumpafruits** [comment]
I just use Internet Explorer anytime I can't click into a line. So far it was only those few challenges for me in Boostrap.

**Comment by vlory73** [comment]
Using Chrome and also not possible to edit below line 68 (on exercise _Style Text Inputs as Form Controls_). Deleting lines from the top is the way to by-pass the problem.

**Comment by smariecode** [comment]
I was having the same issue, using Chrome. I could not get my cursor to the end of line 69 as 'acoombs12' suggested, so I ended up  deleting the </div> on line 73 and retyping it, and after that I was able to modify line 69

**Comment by Ambition101** [comment]
I figured out how to fix this issue. Look at the very top of your code editor, and if the first line is space down then all you have to do is bring that line to the very top. The problem should be fixed after that. Refer to the images attached. 
![screen shot 2017-02-01 at 8 39 56 am](https://cloud.githubusercontent.com/assets/20441870/22508973/26a59ece-e85a-11e6-8291-4c7dc87bcf8b.png)
![screen shot 2017-02-01 at 8 40 22 am](https://cloud.githubusercontent.com/assets/20441870/22508972/26a18352-e85a-11e6-86a4-3572824e646b.png)

**Comment by texas2010** [comment]
@Ambition101, 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

by the way, this challenge dont have a issue anymore.  it suppose to be fine.   plus this issue is very old.

**Comment by Ambition101** [comment]
@texas2010 Thank you for your kind message. Please excuse my helpful comment as I'm new to the community.

**Comment by texas2010** [comment]
@Ambition101 no problem.
