### ISSUE TITLE
The instruction video is slightly different from the list of instructions in the job.

### ISSUE THREAD

**Issue by numfin** [FreeCodeCamp/FreeCodeCamp#5294]
http://i.imgur.com/B7ivADG.png
Challenge [Zipline: Build a Pomodoro Clock](http://www.freecodecamp.com/challenges/zipline-build-a-pomodoro-clock) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by SaintPeter** [comment]
Yup.  I don't know what, if anything, we're going to do with those videos.

**Comment by bugron** [comment]
cc @QuincyLarson

**Comment by erictleung** [comment]
A simple, temporary "fix" could be to just have a checkbox say mentioning just follow the rules and user stories on the webpage and do not follow the video's requirements. But then mention you're welcome to complete the extra rules and user stories from the video for an extra challenge. Thoughts?
