### ISSUE TITLE
Legacy certs should say "legacy" on profile page

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52948]
### Describe the Issue

The legacy certs all have the word legacy in front of them - e.g.
[On the map](https://www.freecodecamp.org/learn) (There's an open issue to add it to the legacy JS cert)
[On the settings page](https://www.freecodecamp.org/settings#certification-settings)
[On the certifications themselves](https://www.freecodecamp.dev/certification/fccf734afde-f462-420f-acd1-7207e8fa05cc/legacy-data-visualization)

But we don't have "Legacy" in front of the cert names on the profile page - e.g. [example 1](https://www.freecodecamp.dev/fccf734afde-f462-420f-acd1-7207e8fa05cc), [example 2](https://www.freecodecamp.org/mot01)

<details><summary>image</summary>

<img width="702" alt="Screenshot 2024-01-04 at 9 10 28 AM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/1d8ed0c5-4b2a-477b-a8f3-85b8a45b3761">

</details>

### Affected Page

https://www.freecodecamp.org/mot01

### Expected behavior

These should all say "View Legacy <cert>"

**Comment by jdwilkin4** [comment]
This should be good to go to open up for contribution right?
Or was there something else needed to discuss?

**Comment by shanmukh-sai2003** [comment]
I think changing the key values in the translation.json file will fix this bug.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/104721888/8e933a19-1a16-4c66-b3eb-e9138244f73c)

@moT01  I want to work on this issue can you please assign me?

**Comment by moT01** [comment]
Feel free to make a PR @shanmukh-sai2003. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
