### ISSUE TITLE
Javascript (new) course bug the solution isn't correct

### ISSUE THREAD

**Issue by AutoAFK** [freeCodeCamp/freeCodeCamp#52953]
### Describe the Issue

At the lesson **Learn Intermediate OOP by Building a Platformer Game** - Lesson 103

It requires that the solution will be:
```js
setTimeout(() => (
      checkpointScreen.style.display = 'none'
    ), 2000)
```
**Notice**: the `( )` after the arrow (`=>`). it should be `{}` instead

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-103

### Your code

```js

setTimeout(() => {
      checkpointScreen.style.display = 'none'
 }, 2000)

```

### Expected behavior

The lesson should be passed.

### System

- Device: [Computer]
- OS: [Windows 10]
- Browser: [Chrome]
- Version: [120.0.6099.131]

**Comment by jdwilkin4** [comment]
Hi @AutoAFK ! 

We currently have an open issue that address this 
https://github.com/freeCodeCamp/freeCodeCamp/issues/52892

We also have a [PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/52913) under review, that should resolve this issue so I am going to close this as a duplicate
