### ISSUE TITLE
Add option to hide upper and lower jaws?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#52954]
### Is your feature request related to a problem? Please describe.

I'm not sure how much value this might add, but it could be kinda neat to have a button to hide/collapse the upper and lower jaw in the step based challenges, so users could see their code all together.

### Describe the solution you'd like

I think a way to collapse them would be the way to go. Then they could stay in place, but just be minimized.

### Describe alternatives you've considered

Hide them completely with a button in the action row.

**Comment by ahmaxed** [comment]
I think it would be useful to have the code and instructions separated.
IMHO we could remove further friction if we have an option to move the instructions to another tab, and fix the action buttons.
That way, users would know where to go without scrolling. That is just an idea, I have no data to proof its usability.

**Comment by mayankkamboj47** [comment]
@ahmaxed I like the simplicity of having the instructions in another tab, but I can imagine it interrupting the flow to switch tabs every challenge, especially because FCC challenges are ~2 mins each

**Comment by ahmaxed** [comment]
@mayankkamboj47, I understand. Once the instruction tab is opened, it could stay open for the upcoming challenges.

**Comment by mayankkamboj47** [comment]
No, I mean if the coding tab is separate, the users are going to inevitably have to switch tabs per challenge to start writing code

**Comment by MrShadowDev** [comment]
[[UI BROKEN] #57039](https://github.com/freeCodeCamp/freeCodeCamp/issues/57039)

I agree with you guys I opened a similar feedback issue that cna be relevant.

I think that the panel is flooding the screen it should be on the left or like the image below.


![Image](https://github.com/user-attachments/assets/6da5338f-33a3-4089-91f7-6c9d46f418ed)

Or add an option to choose between wihich layouts to use so users are free to choose what they like.

**Comment by MrShadowDev** [comment]
@Sembauke why not planned
