### ISSUE TITLE
Superblock Titles Too Large, Missing from Inline

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5295]
There are two issues with the new super-blocks:

1. The titles in the top "table of contents" are HUGE, much too large for the sections they are over.  They need to be smaller so the table of contents can actually function as a table of contents.
   * It may also make sense to make these into links
   * The h3 size of the old headings would be fine.

2. The Superblock titles are not actually inline in the actual content - you can't scroll down and see the Superblock titles in between content.  There it might make sense to have them super huge (h1 size) and with a line underneath them (hr maybe) to break up the content below.

**Comment by BerkeleyTrue** [comment]
The titles have been made smaller. Is the second point still an issue?

**Comment by SaintPeter** [comment]
I think it probably makes sense to have the superblock titles inline with the content and possibly linked to them as well.  I know that long term this will be a moot point, but there is a lot of content there now and it should be made navigable.

**Comment by BerkeleyTrue** [comment]
coolio. We'll keep this open for anyone who wants to tackle this.

**Comment by minseokim** [comment]
SaintPeter, which files/pages are you referring to when it comes to the super-blocks?

**Comment by SaintPeter** [comment]
@minseokim, there are 4 superblocks:
* Getting Started
* Front End Development Certification
* Data Visualization Certification
* Back End Development Certification

They are the top level blocks on the table of contents.  I believe they should also be displayed inline below the TOC, where they naturally occur in the challenge map.

**Comment by bugron** [comment]
@SaintPeter is this still an issue?

**Comment by SaintPeter** [comment]
Nope, this was fixed by the new Map.  Thanks!
