### ISSUE TITLE
Change the editable region and update directions for step 123 RPG game project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#52962]
### Describe the Issue

On the [forum](https://forum.freecodecamp.org/search?q=step%20123), we have a lot of campers confused on which line to edit for step [123](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-123) of the RPG game project. 

We should update the editable region to make it more clear where they should write their answer.
We should probably also update the directions to say to add to the existing `monsterHealth` variable 

## suggested updated change in text

```md
Following this pattern, use the addition operator (`+`) to add a random number between `1` and the value of `xp` to your `monsterHealth -= weapons[currentWeapon].power`.
```

## suggested change for starting editable region

```js
function attack() {
  text.innerText = "The " + monsters[fighting].name + " attacks.";
  text.innerText += " You attack it with your " + weapons[currentWeapon].name + ".";
  health -= monsters[fighting].level;
  --fcc-editable-region--
  monsterHealth -= weapons[currentWeapon].power;
  --fcc-editable-region--
}
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-123

### Your code

see explanation above

### Expected behavior

change the editable region and update description like mentioned above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by lasjorg** [comment]
I would suggest we change this sentence as well.

> JavaScript offers the built-in `Math` utility which offers a number of mathematical tools.

I wouldn't call it a utility, it is an object. Repeating "offers" twice like that also sounds a bit odd to me.

> The `Math` object in JavaScript contains static properties and methods for mathematical constants and functions.

It is a little formal perhaps, but more correct.

---


Also, shouldn't we allow the minimum value to be inside `Math.floor` as well?

```
Math.floor(Math.random() * xp + 1)
```

Expected code

```
Math.floor(Math.random() * xp) + 1;
```

The examples on MDN have the minimum value inside `Math.floor`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

**Comment by JamesCartar** [comment]
> The Math object in JavaScript contains static properties and methods for mathematical constants and functions.

I suggest including the word _built-in_ in the description for the campers to know it is the built-in function of JavaScript.

**Comment by lasjorg** [comment]
> I suggest including the word `built-in` in the explanation for the campers to be clear, it is the _built-in_ function of JavaScript.

It is a global object, built-in seems redundant. You can tack that on to anything, is `map` built-in?

> If we allow the minimum value to be inside of `Math.floor`, the explanation should update this line.

Not sure I see what that has to do with the location of the minimum value but I'm fine with an expanded explanation of what the random function returns

**Comment by JamesCartar** [comment]
I agree, that `Math` is the global object and `.random()` is the built-in function of the Math object. 

> Not sure I see what that has to do with the location of the minimum value but I'm fine with an expanded explanation of what the random function returns.

I also vote for this line:

```
One of those is Math.random(), which generates a random number from 0 (inclusive) to 1 (exclusive).
```

**Comment by jdwilkin4** [comment]
Thanks for your comments. 
We will go ahead and open this up for contribution

# Note to contributors 
This is has been opened up for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## What needs to be changed
Here is the file that needs to be updated
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8e4dc6a60f85bf256a0cb.md

You will need to update the description to be this instead

```md
# --description--

The `Math` object in JavaScript contains static properties and methods for mathematical constants and functions. One of those is `Math.random()`, which generates a random number from `0` (inclusive) to `1` (exclusive). Another is `Math.floor()`, which rounds a given number down to the nearest integer.

Using these, you can generate a random number within a range. For example, this generates a random number between 1 and 5: `Math.floor(Math.random() * 5) + 1;`.

Following this pattern, use the addition operator (`+`) to add a random number between `1` and the value of `xp` to your `monsterHealth -= weapons[currentWeapon].power`.
```
You will also need to update the tests to accept both valid forms of using `Math.floor `here

```js
Math.floor(Math.random() * xp + 1)
```

```js
Math.floor(Math.random() * xp) + 1;
```

**Comment by 001Pytom** [comment]
monsterHealth -=
    weapons[currentWeapon].power + Math.floor(Math.random() * xp + 1);
    
    this is the correct solution to that step 121
