### ISSUE TITLE
Python Building a Cipher Step 71 - Instructions are not correct

### ISSUE THREAD

**Issue by annafkt** [freeCodeCamp/freeCodeCamp#52976]
### Describe the Issue

According to the instructions the user should update the **first** and **second** comments in the code.

In fact, it is the **second** and **third** comments that need to be changed.

The hints are correct, though.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-71

### Your code

```



```

### Expected behavior

The instructions should tell the user to update the **second** and **third** comments.

### Screenshots

<img width="480" alt="instructions" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/44895565/03054c2b-4eb3-43e8-a3d5-c9ae819f0add">
<img width="557" alt="code" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/44895565/84467592-0900-42e6-9e29-eaef4e3843d3">
<img width="492" alt="hint01" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/44895565/d7cfb92a-7295-487b-8c88-fc5e18967c4e">
<img width="477" alt="hint02" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/44895565/7ff3cff4-c27c-4fd3-90c5-b56425dabc4f">

### System

- Device: Laptop
- OS: Windows 11 Home
- Browser: Firefox
- Version: 121.0

**Comment by Dario-DC** [comment]
Thank you for opening this issue. I will include this fix in a larger PR.

**Comment by yonrasgg** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87682163/ce920985-f36f-4ace-a938-d636e0fd8062)

Im facing a similar issue regarding the step 71 it does not allow me to mark it as completed.

**Comment by gikf** [comment]
@yonrasgg please share your code by copying it and pasting here, instead of using image.

**Comment by yonrasgg** [comment]
> @yonrasgg please share your code by copying it and pasting here, instead of using image.

```
text = 'Hello Zaira'
custom_key = 'python'

def vigenere(message, key, direction):
    key_index = 0
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    final_message = ''

    for char in message.lower():
        # Append space to the message
        if char == ' ':
            final_message += char
        else:        
            # Find the right key character to encode/decode
            key_char = key[key_index % len(key)]
            key_index += 1

            # Define the offset and the encrypted/decrypted letter
            offset = alphabet.index(key_char)
            index = alphabet.find(char)
            new_index = (index + offset*direction) % len(alphabet)
            final_message += alphabet[new_index]

    return final_message
    
encryption = vigenere(text, custom_key, 1)
print(encryption)
decryption = vigenere(encryption, custom_key, -1)
print(decryption))
```

**Comment by Dario-DC** [comment]
Hey @yonrasgg you have a syntax error in the last line

**Comment by yonrasgg** [comment]
> Hey @yonrasgg you have a syntax error in the last line

my fault for typo, however it still showing the message:
> Sorry, your code does not pass. Keep trying.
>
> Your second comment should be Find the right key character to encode/decode.
text = 'Hello Zaira'
custom_key = 'python'

def vigenere(message, key, direction):
    key_index = 0
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    final_message = ''

    for char in message.lower():
        # Append space to the message
        if char == ' ':
            final_message += char
        else:        
            # Find the right key character to encode/decode
            key_char = key[key_index % len(key)]
            key_index += 1

            # Define the offset and the encrypted/decrypted letter
            offset = alphabet.index(key_char)
            index = alphabet.find(char)
            new_index = (index + offset*direction) % len(alphabet)
            final_message += alphabet[new_index]

    return final_message
    
encryption = vigenere(text, custom_key, 1)
print(encryption)
decryption = vigenere(encryption, custom_key, -1)
print(decryption)

---
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/87682163/43e592d9-ba98-48b3-bf93-326d1e9b0e5e)

**Comment by Dario-DC** [comment]
Are you able to see these lines in the editor? 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/105294544/dff01f83-50c0-4525-af85-d820cc24a998)

**Comment by yonrasgg** [comment]
> Are you able to see these lines in the editor? ![image](https://private-user-images.githubusercontent.com/105294544/294784183-dff01f83-50c0-4525-af85-d820cc24a998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjA0MjYsIm5iZiI6MTcwNDY2MDEyNiwicGF0aCI6Ii8xMDUyOTQ1NDQvMjk0Nzg0MTgzLWRmZjAxZjgzLTUwYzAtNDUyNS1hZjg1LWQ4MjBjYzI0YTk5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QyMDQyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjIwZjE0M2YwODBiMzQ1MTRmNDc3NGRiNGNmNDkzMjMzZmRkZWZjMzFjZTg0NzcxMzIwNWUwM2FhYTBkZGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uvvl9ZSzZSgO_AmfoGHfhXktm1bt_Zsl5DLfF-t5GiE)

Yes y reset the step and type changes manually and now it works, great thank you very much I'm able to mark it as completed!
