### ISSUE TITLE
Waypoint: Get Set for Ziplines should include instructions to add bootstrap.js to Camper's Codepen

### ISSUE THREAD

**Issue by jwithington** [FreeCodeCamp/FreeCodeCamp#5297]
Currently the instructions for the [Get Set for Ziplines Waypoint](http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines) tell folks to set up their CodePen in a specific way, including adding the Boostrap CSS and some other additions. 

However, it doesn't mention adding the actual bootstrap.js in the JS cog. It should, in order to help folks get up and running with a fully "bootstrapped" codepen. 

This may also require updating the animated .gif that shows in step 6[here](http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines).

**Comment by SaintPeter** [comment]
Yes, this is true, but Bootstrap.js is not technically requried for most features of Bootstrap to work.  Iactually think that the vast majority of campers will never use it.  Any feature which DOES require it typicallly says so on the Bootstrap site.  

The getting started section is just that:  Getting started.  It doesn't tell you everything that you will need to do to complete your projects, it just gives the most basic outline.

I'm interested to hear other feedback, but I think this is good the way it is.

**Comment by ltegman** [comment]
I agree with this. The `Get Set for Ziplines` Waypoint only adds in a couple css files as an example in order to show how that is done and briefly uses the functionality of both css files that are added. Adding in more resources would be overkill for what is just a brief introduction to Codepen.
