### ISSUE TITLE
Building a Spreadsheet - step 17: setting hyphenated attribute values as properties

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#52987]
### Describe the Issue

I haven't looked at much of the new curriculum but I assume the fact that you need to convert the hyphenated aria attribute value to camel case for the property has been explained at some point?

Should using `setAttribute` not also be a valid way of setting attributes?

Do we teach `setAttribute` anywhere?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-17

### Your code

```



```

### Expected behavior

- Explain how to set the aria attribute as a property if it has not been explained.
- Allow the use of  `setAttribute` for setting attributes.
- Teach the `setAttribute` method somewhere if it has not been taught.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
> Should using setAttribute not also be a valid way of setting attributes?
> Do we teach setAttribute anywhere?

`setAttribute` and `removeAttribute` were first introduced in the music player project 
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-50

We also have campers use `el.ariaLabel` in the Todo app

But we are currently removing most of the aria labels based on this conversation here
https://github.com/freeCodeCamp/freeCodeCamp/issues/52981

So it looks like this step will need to update the tests to accept both valid forms of setting the attribute

```js
 input.ariaLabel = letter + number;
```

```js
input.setAttribute('aria-label', letter + number);
```

**Comment by lasjorg** [comment]
I would prefer if the explanation was more explicit about all hyphenated attribute values being camel case as properties. You might be able it infer it but I would prefer if it was stated explicitly.

> All hyphenated HTML attribute values, like `aria-label` are camel case as properties `ariaLabel`.

Or something like that. It might be worded better.

music player step 75
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-75

**Comment by jdwilkin4** [comment]
It might be easier to create a new step 18 to properly teach the `el.attribute` syntax to let them know there is another way to update an attribute since campers will only be familiar with `setAttribute` at this point.

We could do something like this

# --description--

In earlier projects you learned about the `setAttribute` method. Another way to update an attribute in JavaScript is to use the following syntax:

```js
el.attribute = value;
```

The property names for hyphenated HTML attribute values, such as `aria-label`, follow camel case, becoming `ariaLabel`.

```js
el.ariaLabel = "Aria Label Value";
```

Set the `aria-label` attribute for the `input` element to the same value as the `id` attribute.

**Comment by aaqib605** [comment]
I've observed that using template literals to assign values is not allowed. While it may not be essential in this specific case, I believe there should be flexibility to use template literals when setting attribute values. 
What are your thoughts on this?
<img width="1440" alt="Screenshot 2024-01-09 at 6 28 13 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/78491606/1851481e-6bea-4bb7-9360-e8011f786e5b">

**Comment by jdwilkin4** [comment]
Hi @aaqib605 ! 

Based on what I have see on the forum so far, I would imagine most people probably wouldn't use template literals here but we could just update the tests to allow for that option.

**Comment by jdwilkin4** [comment]
I am going to go ahead and open this back up for contribution

## Note to contributors 
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## What should be changed
We are going to move forward with the changes discussed here
https://github.com/freeCodeCamp/freeCodeCamp/issues/52987#issuecomment-1879926549

This means adding a new step 18 to properly teach this syntax.
Please read through the docs here on how to insert a new step
https://github.com/freeCodeCamp/freeCodeCamp/issues/52987#issuecomment-1879926549

**Comment by aaqib605** [comment]
> We are going to move forward with the changes discussed here

Sounds great.
