### ISSUE TITLE
Streamroller does not pass

### ISSUE THREAD

**Issue by yaser-eftekhari** [FreeCodeCamp/FreeCodeCamp#5299]
Challenge [Bonfire: Steamroller](http://www.freecodecamp.com/challenges/bonfire-steamroller#?solution=var%20output%20%3D%20%5B%5D%3B%0Afunction%20recursion(arr)%20%7B%0A%20%20var%20i%3B%0A%20%20if(Array.isArray(arr))%20%7B%0A%20%20%20%20for(i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20recursion(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20output.push(arr)%3B%0A%20%20%7D%20%20%0A%7D%0Afunction%20steamroller(arr)%20%7B%0A%20%20recursion(arr)%3B%0A%20%20return%20output%3B%0A%7D%0A%0Asteamroller(%5B1%2C%20%7B%7D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var output = [];
function recursion(arr) {
  var i;
  if(Array.isArray(arr)) {
    for(i = 0; i < arr.length; i++) {
      recursion(arr[i]);
    }
  }
  else {
    output.push(arr);
  }  
}
function steamroller(arr) {
  recursion(arr);
  return output;
}

steamroller([1, {}, [3, [[4]]]]);
```

**Comment by ltegman** [comment]
You are initializing `output` in globally. This means that after the first time the function runs `output` is not empty and your function will return an incorrect result. You should initialize `output` in the `streamroller` function and have it as a parameter to your `recursion` function.

Thanks and happy coding!
