### ISSUE TITLE
Bonfire Challenges

### ISSUE THREAD

**Issue by yaskyj** [FreeCodeCamp/freecodecamp#53]
I've had to reenter many of the challenges after pressing 'Take me to the next challenge.'
Also, on several of the challenges the test console output show errors (e.g. Unexpected Token) with no output concerning the test, but it still passes. I'll get a screenshot shot the next time it happens.

**Comment by terakilobyte** [comment]
Thanks for the report. This is caused by the user not entering a test correctly. We'll work on hardening it up.

**Comment by yaskyj** [comment]
I don't believe I changed test text provided, but I could be wrong. But now that you mention that, if I change the test text I get the 'is not defined' error. It still gives the 'Take me to my next challenge' modal, but it will bring me back to the same test. If I do the same thing once more, it brings me to the next test.

**Comment by terakilobyte** [comment]
Both of these issues have been address in pull request #55.
