### ISSUE TITLE
Allow no parenthesis around parameter - Step 72 Platformer Game

### ISSUE THREAD

**Issue by RodrigoHLC** [freeCodeCamp/freeCodeCamp#53018]
### Describe the Issue

```
const platforms = platformPositions.map(
  platform => new Platform(platform.x, platform.y)
);
```
Should be accepted as an answer, but the site only accepts the answer if `platform` is wrapped in parenthesis like:

```
const platforms = platformPositions.map(
  (platform) => new Platform(platform.x, platform.y)
);
```

Task: 
"Step 72
In the map callback function, pass in platform for the parameter and implicitly return the creation of a new Platform instance with the platform.x and platform.y values passed in as arguments."

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-72

### Your code

```
const platforms = platformPositions.map(
  platform => new Platform(platform.x, platform.y)
);
```

### Expected behavior

Should be accepted as an answer.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
Hi @RodrigoHLC ! 

Thank you for reporting this issue.

I have opened it up for contribution for any interested contributors that want to work on it.

We also need to update the description for this step because it is missing backticks for the mention of the `map` method.

## Updated description

```md
In the `map` callback function, pass in `platform` for the parameter and implicitly return the creation of a new `Platform` instance with the `platform.x` and `platform.y` values passed in as arguments.
```

**Comment by RodrigoHLC** [comment]
Thank you for your reply Jessica. While I've been using fCC for about a year, I just learned about this issue tracker yesterday and this is my first day using it, so apologies if I miss anything. I'm still learning the ropes ^^'
