### ISSUE TITLE
Error spreading "allSongs" in next line for Step 9 of "Learn Basic String and Array Methods by Building a Music Player"

### ISSUE THREAD

**Issue by rahuljindal1** [freeCodeCamp/freeCodeCamp#53011]
### Describe the Issue

While doing the exercise I observed an inconsistency in the code test of the spread operator when applied to the `allSongs` array. An error occurs when attempting to spread `allSongs` on the next line within the object literal while the test passes when the spread operation is conducted inline. Also in the exercise statement, it is not being mentioned to spread `allSongs` inline

**Error Received:**
```
Your `userData` object should have a songs key set to `[...allSongs]`.
```

Spreading both inline and on next line is correct. So, We should probably make test pass for both the cases

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-9

### Your code

```
let userData = {
  songs: [
    ...allSongs
  ]
};
```

### Expected behavior

We should probably make test pass for spreading `allSongs` both inline or on next line.

### Screenshots

<img width="774" alt="Screenshot 2024-01-07 at 9 05 09 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/a02c5acc-f67a-4f5b-b693-e95c7b63d76d">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Paras20222** [comment]
I am Working on this issue

**Comment by Kashinathpat** [comment]
> I am Working on this issue

@Paras20222 Sorry, I forgot to mention that I was working on this. Also, I didn't see that you were working on this
