### ISSUE TITLE
Learn Greetings in your First Day at the Office - Task 32 - Sentence doesn't match audio

### ISSUE THREAD

**Issue by wblondel** [freeCodeCamp/freeCodeCamp#53010]
### Describe the Issue

The fill-in-the-blank sentence doesn't match what the character says.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-32

### Your code

The written sentence is:
`Thanks, Maria, for ___ me around the ___.`

### Expected behavior

The character says:
`Thanks for ___ me around the ___, Maria.`

### System

- Device: all
- OS: all
- Browser: all
- Version: all

**Comment by aakash-a-dev** [comment]
I am first time here and thank you @huyenltnguyen for the steps. I have followed the steps you told and adding my pr here.

**Comment by thejon07** [comment]
make a video and drop it will that be okay

**Comment by thejon07** [comment]
if i change the text will that be okay ?
