### ISSUE TITLE
Google Maps Showing all free code camp cities.

### ISSUE THREAD

**Issue by bishisht** [FreeCodeCamp/FreeCodeCamp#5301]
Don't you guys think if there is something like Google Maps Showing all FreeCodeCamp City points.

**Comment by bishisht** [comment]
If there is something like free code camp cities shown in google maps it would be great. also the feature show me nearest city is great :)

**Comment by SaintPeter** [comment]
Yes.  This would be awesome!

**Comment by nicolanrizzo** [comment]
I created a Google Maps map with all FreeCodeCamp cities.
To edit: [Edit page](https://www.google.com/maps/d/edit?mid=zH0hxoM17_fk.kDBMlxfk0BZ8&usp=sharing)
To embed in the wiki page: 
```html
<iframe src="https://www.google.com/maps/d/u/0/embed?mid=zH0hxoM17_fk.kDBMlxfk0BZ8" width="640" height="480"></iframe>

**Comment by SaintPeter** [comment]
@nicolanrizzo This is amazing.  So awesome!

**Comment by CodeNonprofit** [comment]
@nicolanrizzo Fantastic.

**Comment by nicolanrizzo** [comment]
Unfortunately, it seems that GitHub does not allow to add an iframe to a wiki page (sources: [[1]](https://github.com/gollum/gollum/issues/171) [[2]](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#videos), also YouTube videos are embedded in a iframe normally).

BUT, I/we can create a .geojson file and use [this GitHub feature](https://help.github.com/articles/mapping-geojson-files-on-github/) to show our map. You can view an example [here](https://github.com/benbalter/dc-wifi-social/blob/master/bars.geojson).

Through this approach we can show **only** the map (and not the map with the cities list). I have already written a couple of js functions to convert the Markdown list to a .csv file; therefore, converting the list to a .geojson file will not take too much time I think.

**Comment by SaintPeter** [comment]
@nicolanrizzo I've basically just created an image of the map and linked it to the google map.  I've got a PR open: FreeCodeCamp/wiki#163 (see above).

How difficult is it to generate the .geojson file?  That looks slick.

My only concern is going to be maintaining this map going forward.  Ultimately I'd like to see us with a true database of campsites and have it automatically generate the data file.  I imagine Google has an API to allow us to update the map programatically.  Once we move to the Gatsby site maybe we can add some automation.

**Comment by nicolanrizzo** [comment]
To create the .geojson file I have to:
1. Create functions to parse the markdown list (done). (.md -> array of addresses).
2. Create functions to retrieve coordinates from city names using the [Google Maps Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro) (almost done). (array of addresses -> array of coordinates)
3. Create functions to write the .geojson file from coordinates (to do). (array of coordinates -> .geojson file).
I think that I can do it.
But it seems that a database-based solution is by far more efficient and easier to update. And the [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/markers) allows to update the map automatically.

**Comment by mhelmetag** [comment]
@SaintPeter once the wiki is moved to a gatsby site, we can definitely use the Google Maps JS api to automagically populate a map from the a list of campsite attributes (probably a json file too).

**Comment by SaintPeter** [comment]
My personal preference would be to stick with the Google Maps in an iframe.  While the .geojson is ok, it doesn't have the same features and usability that Google does.  It sounds like you almost have code to touch the Google Maps already.

I'll see if I can't spec out a campsite database and interface and get an issue opened for it.  This seems like something that should be very straightforward to add to the site.

RE: which issue tracker
I figure whichever one gets the job done is the right one.  :smile:
