### ISSUE TITLE
[python]: cipher/step-15 unclear hint

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#53041]
### Describe the Issue

The current hint is exactly the same as the original instruction:
>You should pass `text[0].lower()` to the `find()` method.

Here's a summary of the 6 forum posts opened:
```
no attempt: 2
find(text[0].lower())
print(find(text[0].lower()))
find(text[0].lower())
find(text[0]).lower()
```

It seems like people are adding a new find() line.

**Proposal to change the hint:**
>Modify this line: `index = alphabet.find(text[0])`. Add `.lower()` to `text[0]`

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-15

### Your code

```

N/A

```

### Expected behavior

N/A

### Screenshots

N/A

### System

N/A

**Comment by naomi-lgbt** [comment]
"Remove the last `print()` call. Then, update your `alphabet.find(text[0])` call to use `text[0].lower()` as the argument."

**Comment by Dario-DC** [comment]
Hey @naomi-lgbt I'm working on improving the cipher project and I'm adding additional steps. I will include this change into my PR.

**Comment by pkdvalis** [comment]
> "Remove the last `print()` call. Then, update your `alphabet.find(text[0])` call to use `text[0].lower()` as the argument."

Would this be for the instruction, or hint?

**Comment by Dario-DC** [comment]
I think this is for the instructions since there's a separate hint for removing the print call.
