### ISSUE TITLE
[python]: cipher/step-82: unclear variable name

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#53044]
### Describe the Issue

This is related to Issue #53042

**Existing Instruction:**
>Change your text variable into `mrttaqrhknsw ih puggrur`.

Instructions are to change
>text = 'Hello Zaira!''

This will no longer be "plain text", "unencrypted text", or "clear text". It will be "encrypted text" or "cipher text". This is a bit confusing in the next step when we ask to print Encrypted Text: `text`, since this variable was previously plain, unencrypted text.

**Proposed Change**
I propose we change the variable name as well.
> Delete the line `text = 'Hello Zaira!''`. Declare a new variable called `encrypted_text` and assign it this string: `"mrttaqrhknsw ih puggrur"`

It could be `encrypted_text` or `ciphertext`. 
`encrypted_text` is probably more clear.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-82

### Your code

NA

### Expected behavior

NA

### Screenshots

NA

### System

NA

**Comment by Dario-DC** [comment]
Thanks for reporting this. I think the confusion arises from the fact that the change from the encryption process to the decryption is not highlighted enough. I've already worked on changing these steps locally and there will be a PR to improve the cipher soon.

**Comment by pkdvalis** [comment]
No problem! I was just trying to fill out what's already listed in #52578 This was confusing when I was troubleshooting forum posts totally out of context Step 83.

I think plaintext and ciphertext are commonly used in the encryption world. Might be a good idea to introduce that nomenclature here? Especially since we are switching between encryption/decryption.

I need to have a run through this from beginning to end though for a deeper understanding.

**Comment by Dario-DC** [comment]
Honestly, my idea is that `text` should be used either for encrypt or decrypt. What should be improved is the explanation of what's happening. Anyway I will consider to add a step and change the variable name if that can help campers.

**Comment by pkdvalis** [comment]
I see, what about `input` ? It's more generic but I think that would be descriptive of either and would avoid changing the variable name later.

Maybe it's just me but `text` to me indicates "clear text" or "plain text", a message that I should be able to read. I wouldn't refer to encrypted data or an enciphered message as text.

That would imply `output` for the final decrypted message, or encrypted output. I would rename the `final_message` return variable in the function to `output`. Again, to me, `final message` indicates a decrypted message (an encrypted message being an interim state for transit or storage).

While we're at it I could also see renaming:
`encryption` and `decryption` to
`encrypted` and `decrypted`

"Encryption" sounds like a process and "Encrypted" like an encrypted message.

**Comment by Re1nGer** [comment]
is this issue already resolved ?

**Comment by pkdvalis** [comment]
The way the instructions are presented seems more clear now, and there haven't been anymore forum posts about this since it's been changed. (It's now Step 86 and 88)

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-86

https://forum.freecodecamp.org/search?q=Cipher%2086%20%23python
https://forum.freecodecamp.org/search?q=Cipher%2088%20%23python

I would say this is successfully resolved.
