### ISSUE TITLE
Inconsistent optional chaining for "userData.currentSong"  in multiple steps of Music Player project

### ISSUE THREAD

**Issue by rahuljindal1** [freeCodeCamp/freeCodeCamp#53043]
### Describe the Issue

I noticed that for completing Step 36, optional chaining not to be used for accessing `userData.currentSong`

**Success Case:**
<img width="400" height="300" alt="Screenshot 2024-01-08 at 9 06 07 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/f379e12c-b0a2-4d74-ad60-3ef26b29e6ad">

**Error Case**:
<img width="400" height="300" alt="Screenshot 2024-01-08 at 9 05 57 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/3288a17d-78a8-4863-a9fd-7d8d2077ec8e">

While for completing step 38, it is opposite where it is required to use optional chaining to access `userData.currentSong`

**Success Case:**
<img width="400" height="300" alt="Screenshot 2024-01-08 at 9 06 41 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/29f8d667-5ee6-4e48-a20f-8884aaed281b">

**Error Case**:
<img width="400" height="300" alt="Screenshot 2024-01-08 at 9 06 21 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/90f58aad-9ea6-4a14-b6cb-88cf06491160">

This inconsistent behavior is causing confusion when to use and not to use optional chaining. It should be consistent or may be mentioned in the task description how we need to access the property.

_**Note:** I have not checked every Step for the same behavior. These are two which I noticed._

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-36, https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-38

### Your code

Success Case on Step 36:
```
const getCurrentSongIndex = () => userData?.songs.indexOf(userData.currentSong)
```

Error Case on Step 36:
```
const getCurrentSongIndex = () => userData?.songs.indexOf(userData?.currentSong)
```

Success Case on Step 38:
```
const playNextSong = () => {
  if (userData?.currentSong === null) {
    playSong(userData?.songs[0].id)
  }
}
```

Error Case on Step 38:
```
const playNextSong = () => {
  if (userData.currentSong === null) {
    playSong(userData?.songs[0].id)
  }
}
```

### Expected behavior

Optional chaining should be consistent or may be mentioned in the task description how we need to access the property.

### Screenshots

Already shared in the description

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
Thank you for reporting this issue.

I have gone through and looked at the final solution and it looks like there are many more instances where this inconsistency is happening.

 I will go through and address all of the tests and update all of the seed code to fix the consistency issues.

**Comment by rahuljindal1** [comment]
Just wanted to mention that I have found similar optional chaining issue on Step 72 of the same exercise for `userData.song`.

At every other place we were accessing `song` on `userData` with optional chaining but on this specific exercise it is being accessed directly.

<img width="400" height="300" alt="Screenshot 2024-01-10 at 9 00 49 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/a09e29d0-d1c2-4b22-aede-43964dbe4112">


<br />
<br />

Please LMK if I need to open new issue for it.
