### ISSUE TITLE
Potential bad wording in step 20 of learn regular expressions by building a password gen

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#53045]
### Describe the Issue

The wording seems like it could be potentially confusing. 

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/step-20

### Your code

```
new_password = generate_password(8)
```

### Expected behavior

Something along the lines of "Finally use the assignment operator to set `new_password` equal to the return value of `generate_password` with `8` passed as the function argument." might be better? I'm pretty sure saying "assign the function call" could be a little confusing, and it might not be right way to describe things. I'm interested in additional opinions. 

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 121.0

### Additional context

It was reported in this thread

 https://forum.freecodecamp.org/t/learn-regular-expressions-by-building-a-password-generator-step-20/662194.

**Comment by Enecode** [comment]
Hi @jdwilkin4 Can I be assigned this issue?

**Comment by a2937** [comment]
Hi there, Thanks for your interest in contributing. This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by a2937** [comment]
Hi there, Thanks for your interest in contributing. This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by naomi-lgbt** [comment]
"Finally, assign the result of calling `generate_password` to a `new_password` variable. Pass `8` as the argument to your `generate_password` call."
