### ISSUE TITLE
Bonfire: Title Case a Sentence - found a bug

### ISSUE THREAD

**Issue by Heretic888** [FreeCodeCamp/FreeCodeCamp#5304]
Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20%20%20var%20str2%20%3D%20%22I'm%20%22%20%2B%20str.charAt(4).toUpperCase()%20%2B%20%22%20%22%20%2B%20str.charAt(6).toUpperCase()%20%2B%20%22ittle%20%22%20%2B%20str.charAt(13).toUpperCase()%20%2B%20%22ea%20%22%20%2B%20str.charAt(17).toUpperCase()%20%2B%20%22ot%20%22%3B%0A%20%20%20%20return%20str2%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
On this photo you will see that I had right solution(I know only for first part(!)) but the programm did't pass me further. Please correct this.
![555](https://cloud.githubusercontent.com/assets/13378337/11810078/883c2dba-a33c-11e5-9022-1f5f45c9357a.jpg)

My code:
```javascript
function titleCase(str) {
    var str2 = "I'm " + str.charAt(4).toUpperCase() + " " + str.charAt(6).toUpperCase() + "ittle " + str.charAt(13).toUpperCase() + "ea " + str.charAt(17).toUpperCase() + "ot ";
    return str2;
}

titleCase("I'm a little tea pot");
```

**Comment by ltegman** [comment]
You are adding a space at the end of the return value you are creating, which should not be there.

In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to make sure what you're seeing is a site issue before filing a bug.

Thanks and happy coding!

**Comment by MariaTaborda** [comment]
Hi Heretic, 
Does you code work for every instance? the idea is to create a function that works for every instance not only for the first.
