### ISSUE TITLE
Building a Cipher: step 3 - use a less ambiguous word

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53050]
### Describe the Issue

The instructions.

> For now, print your `text` variable to the screen by including the variable name between the opening and closing parentheses of the print() function.

The word "including" might be misinterpreted as the `text` variable + something more. That something more might be understood as quotes.

I would suggest using "adding" or "putting" instead.

> For now, print your `text` variable to the screen by adding the variable name between the opening and closing parentheses of the `print()` function.

We should change it in the hint as well

> You should pass `text` to your `print()` function by adding the name of this variable within parentheses.

We might also test for quotes or just make it part of the hint

> You should pass `text` to your `print()` function by adding the name of this variable within parentheses. Do not put quotes around the variable name.

---

As suggested in the thread, a code example with the `print()` function passed a variable as an argument might also help.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-3

### Your code

```



```

### Expected behavior

Use less ambiguous words.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/step-3-not-making-sense/662472

**Comment by pkdvalis** [comment]
I think this could also use a concrete example:

```
a = "Apple"
print(a)
```
>This will print the string "Apple" because it is stored in the variable `a`.

**Comment by lasjorg** [comment]
I agree, an example would help.

Considering this is step 3 in the very beginning of the camper learning Python (and for all we know coding) the first time they are asked to use a variable it should be the main focus of the challenge. I would suggest switching the order of importance here.

Start by explaining how to use a variable, then explain `print` and show an example of using a variable with the `print` function. Do not start by explaining the `print` function.

**Comment by Dario-DC** [comment]
I will open a PR to change many steps in this project soon. Considering my current draft, this step does not exist anymore as is. The camper is asked to add an empty `print()` call and pass a variable only in the next step.
