### ISSUE TITLE
Create script to update certified user

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#53056]
### Describe the Issue

We could use a script to update [the certified user data](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/scripts/seed/certified-user-data.js). It should add all the existing challenges to the `completedChallenges` of that object that aren't already in there. Note that some of the challenges require solutions or other info - we will want to include the info needed.

**Comment by naomi-lgbt** [comment]
Why do we need a script to update it? Running `pnpm run seed:certified` should just reseed it?

**Comment by moT01** [comment]
Closing as stale.
