### ISSUE TITLE
Missing solutions to selected exercises

### ISSUE THREAD

**Issue by camilodelvasto** [FreeCodeCamp/FreeCodeCamp#5305]
Challenge [Bonfire: Chunky Monkey](http://www.freecodecamp.com/challenges/bonfire-chunky-monkey) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I solved this and other bonfires some days ago. Now I wanted to check the solution again but it wasn't possible via the map, it was showing just the initial code. My solution is stored, though, as I can see it on my activity page (clicking there will show a different url with a *solution* param on it).

My code:
```javascript
function chunk(arr, size) {
  
  return arr;
}

chunk(["a", "b", "c", "d"], 2);

```

**Comment by SaintPeter** [comment]
Solutions are availible from your [Profile Page](http://www.freecodecamp.com/camilodelvasto) which can be accessed by clicking on your brownie points in the upper right hand corner of the FCC interface.

I see your solution to Chunky Monkey there:
```
function chunk(arr, size) {
  var temp = [], newArr = [];
  for(var i = 1; i <= arr.length; i++){
    temp.push(arr[i-1]);
    if (i%size === 0) {
      newArr.push(temp);
      temp = [];
    }
  }
  if (temp.length > 0) newArr.push(temp);
  return newArr;
}
```

Solutions are not "saved" on the map, per se.  They are saved in local storage for a limited time so when you are working on the problem you can come back and see the code you're working on.  Once you have submitted a completed solution, or if you clear your cache, the local storage is no longer maintained.

Closing as this is not a site issue.

**Comment by camilodelvasto** [comment]
@SaintPeter thanks for the explanation and the work done!
