### ISSUE TITLE
Correct String "undefined"

### ISSUE THREAD

**Issue by chrwatson** [FreeCodeCamp/FreeCodeCamp#5306]
Challenge [Waypoint: Declare String Variables](http://www.freecodecamp.com/challenges/waypoint-declare-string-variables#?solution=var%20firstName%20%3D%20'Chris'%3B%0Avar%20lastName%20%3D%20'Watson'%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0Aif(typeof%20myFirstName%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20myLastName%20!%3D%3D%20%22undefined%22)%7B(function()%7Breturn%20myFirstName%20%2B%20'%2C%20'%20%2B%20myLastName%3B%7D)()%3B%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var firstName = 'Chris';
var lastName = 'Watson';


// Only change code above this line.

if(typeof myFirstName !== "undefined" && typeof myLastName !== "undefined"){(function(){return myFirstName + ', ' + myLastName;})();}

```

**Comment by ltegman** [comment]
You did not create two new string variables with the names `myFirstName` and `myLastName` as the challenge asks of you. In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for challenge help.

Thanks and happy coding!
