### ISSUE TITLE
what  is the problem in this  code ? i did not  understand

### ISSUE THREAD

**Issue by alpha0021** [FreeCodeCamp/FreeCodeCamp#5307]
![screenshot from 2015-12-15 20-23-54](https://cloud.githubusercontent.com/assets/16195600/11821450/df2302ca-a369-11e5-82b6-a1191cdbb32e.png)

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help)

Thanks and happy coding!
