### ISSUE TITLE
Clarify instructions for Cafe Menu step 58

### ISSUE THREAD

**Issue by bbsmooth** [freeCodeCamp/freeCodeCamp#53074]
### Describe the Issue

The instructions ask to style both the `h1` and `h2` elements with the same font family, but they do not make it clear that the tests will only accept one ruleset using the `h1, h2` selector. Granted, if the user creates separate rulesets for `h1` and `h2` the hint will tell them to use an `h1, h2` selector. But I think it is much better to be explicit about this in the instructions instead of telling the user they aren't doing it the way we want them to after the fact. I suppose you could argue that the phrase "Style both the `h1` and the `h2` elements..." implies that we want them in one ruleset but I'm not sure that's clear enough and I just ran into someone in the forums who certainly didn't interpret it that way.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-58

### Your code

N/A

### Expected behavior

Change the last sentence in the instructions to something like:

"Style both the `h1` and the `h2` elements using only one selector list so that only these elements' text use Impact font."

Or there may be some better wording? I'm not sure if we have used the term "selector list" enough that they would understand what that means?

### System

N/A

**Comment by naomi-lgbt** [comment]
"Style both the `h1` and the `h2` elements using a single selector so that these elements' text use Impact font."
