### ISSUE TITLE
Typo on A2 English for Developers (Beta) - Dialogue 1: A Mobile Developer Joins the Team - Task 10

### ISSUE THREAD

**Issue by herminiotorres** [freeCodeCamp/freeCodeCamp#53089]
### Describe the Issue

This task has this sentence:

`Mobile` means something that can be moved or used on the go, like mobile phones or tablets.

So, I think it might want to say: `used on they go` instead of `used on the go`.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-introductions-in-an-online-team-meeting/task-10

### Your code

n/d

### Expected behavior

n/d

### System

n/d

**Comment by RGHANILOO** [comment]
i don't really see a problem in the language used. 
"Mobile means something that can be moved or used on the go..." is correct in my opinion. "Used on they go" does really make sense .

**Comment by jdwilkin4** [comment]
Hi @herminiotorres ! 

The current language used in the challenge is correct so we will not move forward with this change
