### ISSUE TITLE
Each character of the numbered list's index appears on it's own line on mobile

### ISSUE THREAD

**Issue by Demon000** [FreeCodeCamp/FreeCodeCamp#5309]
Link to the page: http://www.freecodecamp.com/map
How to replicate: Open the Map page on a mobile phone(or simulate a small screen).
Screenshot: 
![screenshot_2015-12-15-23-57-35](https://cloud.githubusercontent.com/assets/12939434/11825438/a583ea5c-a387-11e5-9196-0f736d69c5bd.png)

**Comment by SaintPeter** [comment]
Confirmed.

**Comment by BerkeleyTrue** [comment]
cc/ @LenaBarinova

**Comment by LenaBarinova** [comment]
I'm on it.

**Comment by josh3336** [comment]
i think its line 136 in main.less
word-wrap: break-word;

**Comment by Demon000** [comment]
@josh3336 Confirmed as solution.
