### ISSUE TITLE
(Javascript Course) Learn Form Validation by Building a Calorie Counter, Step 56 - test doesn’t accept right answer

### ISSUE THREAD

**Issue by Rods10** [freeCodeCamp/freeCodeCamp#53097]
### Describe the Issue

The test asks us to create a for loop. However, when I wrote code with acceptable logic the test rejected it. I just switched the positions of the variables in the conditional statement of the for loop, while keeping the same condition.

### Affected Page

Step 56

### Your code

```
Correct Answer that wasn’t accepted
  for (let i=0; list.length>i ; i++){
  }

Correct Answer that was accepted
  for (let i=0; i<list.length ; i++){
  }
```

### Expected behavior

Code should accept the first answer.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
We currently have a PR in the works to refactor this project to use the `for...of` loop instead of a regular `for` loop.
https://github.com/freeCodeCamp/freeCodeCamp/issues/52767

So we will not be moving forward with this change
