### ISSUE TITLE
Move Automated Testing and Debugging before Basic Algorithm Scripting

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#5311]
### Moving [Automated Testing and Debugging](http://www.freecodecamp.com/map#automated-testing-and-debugging) before [Basic Algorithm Scripting](http://www.freecodecamp.com/map#basic-algorithm-scripting) and renaming it to [*Debugging*](#) .

Campers come to Bonfires wondering and asking about doubts even when they could solve themselves if they had good tools e.g. using `console.log`

It will be useful to sneak in http://jsbeautifier.org and http://repl.it 
They're *pretty useful*.
These will very much benefit campers.

**Comment by ltegman** [comment]
I don't think encouraging users to use online editors outside of Free Code Camp is a good idea. We should be seeking to make Free Code Camp's editing experience good enough that most users won't find themselves wanting to leave it.

I do agree though that a debugging section should come before the first bonfires.

**Comment by SaintPeter** [comment]
This seems reasonable to me.  I would actually argue that we need a separate section talk talks about debugging.  The automated testing part will come later.

RE: Repl.it
I still recommend this to campers every single time I help.  Unless and until we have a viable faux console to work with, it really is a better solution than keeping dev tools open.

**Comment by abhisekp** [comment]
And i added http://jsbeautify.org just because we don't have any "Copy Solution" button yet.
Or show a tooltip-alike small menu on selection of some code which has two menu items
- copy selection
- copy solution (all)

**Comment by erictleung** [comment]
Closing in favor of https://github.com/FreeCodeCamp/CurriculumExpansion/issues/46 for challenge sequence reorganization conversation
