### ISSUE TITLE
New JS Curriculum: two instances of explanation for the `textContent` property

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#53122]
### Describe the Issue

There's an explanation for the `textContent` property of DOM in both the **music player project** and the **date formatted project**.

The explanation occurred in [step 56](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-56) of the music player project and [step 14](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-14) of the date formatter project.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-14

### Your code

N/A

### Expected behavior

The explanation should only be in the music player project since it comes before the date formatted project in the curriculum.

This explanation should not be in the date formatter project because campers are expected to have encountered it in the music player project. This would make them focus on only what's necessary for that step in the date formatter project. 

### Screenshots

![Screenshot 2024-01-11 at 2 11 20 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/ce840872-bcc7-4067-93d6-602112fa6b7a)

![Screenshot 2024-01-11 at 2 11 08 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/3fb85be1-4be7-4b35-b2a7-abdb38b9c57a)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by segunajibola** [comment]
Can I work on this?

**Comment by Ksound22** [comment]
> Can I work on this?

Absolutely. The freeCodeCamp documentation has everything you need to get started: https://contribute.freecodecamp.org

**Comment by segunajibola** [comment]
Thanks, will check it and work on it.
