### ISSUE TITLE
Misleading description for Step 15 of "Learn Modern JavaScript Methods By Building Football Team Cards"

### ISSUE THREAD

**Issue by rahuljindal1** [freeCodeCamp/freeCodeCamp#53126]
### Describe the Issue

In the description it is being mentioned that after setting the value in freezed object, we need to add a `console.log` and open the console to see an `Uncaught TypeError`.

It is creating the illusion that `console.log` is doing something because of which value is getting consoled while that is not being the case and it is during runtime when the code is encountering update in freezed object then an error is getting thrown and because of absence on try catch it is getting thrown as Uncaught type and is being shown on console.

For a new developer, it can be very confusing and get result in misleading information.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-15

### Your code

```
 myFavoriteFootballTeam.team = "USA"


```

### Expected behavior

I think test should get passed without actually asking for adding `console.log`.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ieahleen** [comment]
The thing is that there is no way to have a step in which the tests pass on the starting code, all steps need to have the camper change something

**Comment by rahuljindal1** [comment]
Exactly

**Comment by jdwilkin4** [comment]
> I think test should get passed without actually asking for adding console.log.

I vote we remove step 15 all together because in the the next step 16, you have to remove the console statement and `myFavoriteFootballTeam.team = "USA";`.

Since the lesson was originally supposed to be about logging things to the console, if we remove it we might as well remove the lesson completely.

It wouldn't make sense to have campers write `myFavoriteFootballTeam.team = "USA";` and then immediately delete it in the next lesson without doing anything with it. 

That is my proposal moving forward.

Thoughts, before we open this up for contribution?

**Comment by ieahleen** [comment]
it makes sense to have the camper look at the browser console to see the error, also as a reminder that they can see things in the console, imo
But also, we could remove the step entirely too, if it's too confusing, and the next one if the next one just removes the line

**Comment by jdwilkin4** [comment]
> it makes sense to have the camper look at the browser console to see the error, also as a reminder that they can see things in the console, imo

Yeah, I like it when we have campers log things to the console too.

But in this case, trying to add a note about the purpose of the console statement might cause more confusion then it helps.
Plus I think step 14 does a good job of explaining what the `Object.freeze` method is. And I haven't seen anyone confused about how this method works from the previous step.

So we will move forward with making the update

**Comment by jdwilkin4** [comment]
# Note to contributors 

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Changes that need to be made

We are going to remove step 15 
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-modern-javascript-methods-by-building-football-team-cards/63d12fe2a595263e8f5084f7.md

You can learn about how to remove a step here
https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects?id=how-to-work-on-practice-projects

We also need to update step 16

Here is the new updated description

```
# --description--

The next step is to access the key called `sport` from the `myFavoriteFootballTeam` object and assign it to a new `const` variable called `sport`.

Remember you can use dot notation for this. 
```
and you will need to remove the following tests from step 16

You should remove your assignment of the `USA` string to `myFavoriteFootballTeam.team`. 

```js
assert.notMatch(code, /myFavoriteFootballTeam\.team\s*=\s*('|"|`)USA\1\s*/);
```

You should remove your `console.log` for `myFavoriteFootballTeam.team`.

```js
assert.notMatch(code, /console\.log\(\s*myFavoriteFootballTeam\.team\s*\)/);
```
