### ISSUE TITLE
Symmetric difference

### ISSUE THREAD

**Issue by coded9** [FreeCodeCamp/FreeCodeCamp#5312]
My browser gets stuck when I open this bonfire..Unable to proceed

![image](https://cloud.githubusercontent.com/assets/9302330/11826889/acbd8236-a34d-11e5-8744-90210161f65f.png)

**Comment by ltegman** [comment]
You very likely have an infinite loop in your locally saved code. Please try following [this wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage) and let us know if that solves the problem.

**Comment by SaintPeter** [comment]
Alternatively, you may be able to disable auto-run to save your code:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run

**Comment by coded9** [comment]
Thank you ! My code has an infinite loop.Issue is addressed :+1:

**Comment by ltegman** [comment]
Glad to hear it! Thanks and happy coding!
