### ISSUE TITLE
Building a Spam Filter - Step 5: Incorrect assert message for second test

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53134]
### Describe the Issue

> You should assign the `isSpam()` function call to `result.textContent`.

We are not assigning the function call to anything.

Not 100% sure what the expected error in the code is that we are testing for here. It might be its position.

> You should call the `isSpam()` function after the assignment operator `=` and before the `?` ternary operator.

Also, if you forget to use the `.value` property on the `messageInput` you are passing to `isSpam` you will get this assert message, which is confusing. I don't think this test should care about the argument to `isSpam`, only the function call position (if that is what we are testing for here).

tests: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-regular-expressions-by-building-a-spam-filter/641cdf57c3f7ee276e1d9b32.md

---

As an aside. We have all the elements and event listeners ready to be used, can't the test use them for at least the last three tests?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-regular-expressions-by-building-a-spam-filter/step-5

### Your code

```



```

### Expected behavior

Give the correct assert messages.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
> We are not assigning the function call to anything.

We could use this wording for the hint text

```md
You should update the `result.textContent` value to be the result of the  `isSpam` function call.
```

> Not 100% sure what the expected error in the code is that we are testing for here. It might be its position.

> You should call the isSpam() function after the assignment operator = and before the ? ternary operator.

I believe so.
It looks we are testing for `result.textContent = isSpam()` and then the next few tests are for the ternary

> I don't think this test should care about the argument to isSpam

I feel like we still need to check for the actual user message here `isSpam(messageInput.value)` because if the camper does something like this `isSpam(messageInput)` then they might be missing the point of the challenge. 

So I think we should update the tests to better check for that. 

But also, I think the description could be updated to better explain why they need to make these changes. 

Something like this could work

```md
# --description--

When the user supplies a message and clicks on the 'Check message' button, your application should check if that message is spam or not. 

Start by creating a ternary expression that checks the truthiness of `isSpam(messageInput.value)`. If true, set the `textContent` property of the `result` element to `Oh no! This looks like a spam message.`. Otherwise, set the `textContent` property of the `result` element to `This message does not seem to contain any spam.`. Set `result.textContent` to the result of your ternary expression.

Below your ternary, set the `value` of `messageInput` to an empty string.
```

> As an aside. We have all the elements and event listeners ready to be used, can't the test use them for at least the last three tests?

Maybe? 🤔 
It would be nice to cut down on the regex here

**Comment by lasjorg** [comment]
> We could use this wording for the hint text
> 
> ```
> You should update the `result.textContent` value to be the result of the  `isSpam` function call.
> ```

"the result of the  `isSpam` function call" makes it sound like the element will be assigned the function return value. We are not assigning the result of the function call. We are assigning the expression the ternary condition evaluates to based on what `isSpam` returns.

```
const result.innerText = isSpam(someArg) ? 'Value result will contain if isSpam returns true' : 'Value result will contain if isSpam returns false'
```

- For test 2, if we only care about the position of the `isSpam` function then:
  - Because the regex includes the argument it will cause a false positive where the position can be correct but if you do not use the correct argument you get this assert message.
  - The assert message should be about the function position without making it sound like its return value is being assigned to the `result` element.

> I feel like we still need to check for the actual user message here `isSpam(messageInput.value)` because if the camper does something like this `isSpam(messageInput)` then they might be missing the point of the challenge.

We check the argument in test 3 and the hint shows the function call with the expected argument.

> You should use ternary syntax to check the truthiness of `isSpam(messageInput.value)`.
