### ISSUE TITLE
At least one camper encountered reporting HTTPS "not safe" issue for accessing Medium publication

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5313]
![](https://gm1.ggpht.com/Xtv7F0xaKTFUwnJuqzsGpcgwl-B4PrzhNi-buY4ndgNXCXt9uI65fTKcKqCC1iApYQsIYJCZPfIeIr5cj2Rv1w8eTShrLwX-G_D-mB4rzUWyXdPFUv9ZwSjJAXYEATg2IKZCPUT3srcRFMKZWL5W2Jkw79VQPjQfmvBYL7K3UYsA6aoLSS9nfYyV6Sv4fLnity15JvWrwjj8vIJyDZdHGDIMXBpscT9WlAxpumZxRsO7GZLwYCB4HR1UoDcQcJl12djyGn4N2nc4wKYprE4J5G57SnJYeUaY7Us_M_x8SvWHDsrZ0hqOtMDzkSjMpg6cAkTBrJMjCCYnjpj1KW7ZSr-5o5bDzBMUMoategEu7ARk-ol7ozuYIOtwgXTxAshjBNr89_h1HX7IrStJ_od2yls98rkRqI0vq3XYFrDA2OpvmLVqRlnAWUaZTQQEy0qXPxUqkgda7hFC75_OOpQgVRq0hvx-y45WKc72piP5PvBcFKL5fviFyILxTg6ShwdKqLQRcEvAEpHnC2_imffVyT7d-Du-dF__uIOq0vzPosUgCOJU-Z0CUgvb5rvocfLzzqPnP4_oQybJgCMNBQShocSLpQQk6-jO5khOcIzL8tDtIomgjIkw76rwLnNTcsiNJu8sDO4RLKWy2am6GMhS1t3hKg9XG9mdz2j-DDI=s0-l75-ft-l75-ft)

**Comment by BerkeleyTrue** [comment]
@QuincyLarson The link you posted does not work
