### ISSUE TITLE
challenge editor stopped working on gitpod

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#53131]
Port 3200 has a JSON
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/84aa5a5f-0f1c-4611-8d87-23965bc8d11b)

Port 3300 doesn't fetch
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/c486026f-7065-4f4a-a9f1-9b853e2270ce)

In the terminal I get
```
Error: ENOENT: no such file or directory, scandir '/workspace/freeCodeCamp/curriculum/challenges/english/favicon.ico'
```
I don't know if that's related

**Comment by gikf** [comment]
For some reason it doesn't like the default API url.

I've changed the `VITE_CHALLENGE_EDITOR_API_LOCATION` in `/workspace/freeCodeCamp/tools/challenge-editor/client/.env` file from the internal one `localhost...` to the external one - `https://3200-...gitpod.io`.
