### ISSUE TITLE
Building an Expense Tracker - Step 13 - `map` object print out not explained

### ISSUE THREAD

**Issue by ChiaraGambone** [freeCodeCamp/freeCodeCamp#53135]
### Describe the Issue

Step 13 teaches the use of the map() function with the lambda function `test = lambda x: x * 2` on an array of integers.
The exercise console doesn't show the result of this operation, but instead displays

`>>> <map object at 0x10fe398>`

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/step-13

### Your code

```
def add_expense(expenses, amount, category):
    expenses.append({'amount': amount, 'category': category})
    
def print_expenses(expenses):
    for expense in expenses:
        print(f'Amount: {expense["amount"]}, Category: {expense["category"]}')

def total_expenses(expenses):
    pass
    
test = lambda x: x * 2
print(map(test, [2, 3, 5, 8]))

expenses = []

```

### Expected behavior

I expect I should see the result of this operation in the console.

### Screenshots

![nucTLRXdar](https://github.com/freeCodeCamp/freeCodeCamp/assets/31727137/6ff29561-fd6d-46a4-a955-c045ca0cd3a6)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Firefox
- Version: 121.0.1 (64-bit)

**Comment by ieahleen** [comment]
that's correct, it outputs a map object, that's the output on the console. One would need to use `list()` or `tuple()` on the map object before printing to see the elements. This step could be changed maybe to show the elements on the console with those.

**Comment by gikf** [comment]
Maybe better would be wrapping it in the `list()` in a new step? I'm not sure if this was mentioned elsewhere, or is it later, but that would be good point to briefly explain why `map` or `filter` don't simply return changed lists.

**Comment by Dario-DC** [comment]
> Maybe better would be wrapping it in the `list()` in a new step? I'm not sure if this was mentioned elsewhere, or is it later, but that would be good point to briefly explain why `map` or `filter` don't simply return changed lists.

Adding one o two steps to expand on `map` and `filter` and show a readable output would be great.

**Comment by techlism** [comment]
I am trying to work on this.. one simple solution is make it a list  or iterate over using a loop.
What should be implemented ?

**Comment by lasjorg** [comment]
Why are we even asking them to print that?

This is also different between Python 2 and Python 3. So maybe that is worth mentioning?

https://www.learnpython.org/en/Map%2C_Filter%2C_Reduce

**Comment by ChiaraGambone** [comment]
> that's correct, it outputs a map object, that's the output on the console. One would need to use `list()` or `tuple()` on the map object before printing to see the elements. This step could be changed maybe to show the elements on the console with those.

thank you for the explanation, makes sense but since the step explicitly tells you to print the result, it did seem like a console bug.
As a learner, i think it only makes sense that this is explained properly then

**Comment by techlism** [comment]
Okay now since we know that it is python3 and there was a need of printing. So what should be done.
