### ISSUE TITLE
Building the Merge Sort Algorithm: multiple steps allow tests to pass without checking if the `pass` keyword is removed

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#53139]
### Describe the Issue

The descriptions of steps 12, 13, and 29 state that the `pass` keyword should be removed (or replaced), but the tests pass without removing (or replacing) it.

### Affected Page

- https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-12
- https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-13
- https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-29

## The following code pass the tests for their respective steps

Step 12 code:
```py
while left_array_index < len(left_part) and right_array_index < len(right_part):
        pass
        if left_part[left_array_index] < right_part[right_array_index]:
            pass
```

Step 13 code:
```py
while left_array_index < len(left_part) and right_array_index < len(right_part):
        if left_part[left_array_index] < right_part[right_array_index]:
            pass
            array[sorted_index] = left_part[left_array_index]
```

Step 29 code:
```py
if __name__ == '__main__':
    pass
    numbers = [4, 10, 6, 14, 2, 1, 8, 5]
```

### Expected behavior

Each of the steps should check that the `pass` keyword is removed (or replaced).

### Screenshots

Step 12:
![Screenshot 2024-01-11 at 10 10 36 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/47be660b-a740-4933-95f2-5727b06653ad)

Step 13:
![Screenshot 2024-01-12 at 7 53 21 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/7659fe34-be6a-4c61-b8ac-90a1b09bcf64)

Step 29:
![Screenshot 2024-01-11 at 10 29 34 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/8a777ba2-01d9-4780-b72e-9c1179a775bb)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Steps 19 and 23 aren't allowing tests to pass with the `pass` keyword in the editor (because it should be removed or replaced), so the same should apply to steps 12, 13, and 29.
![Screenshot 2024-01-11 at 10 20 26 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/442036e2-7cf7-43a1-bfa7-72419086044a)

![Screenshot 2024-01-11 at 10 23 38 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/b253540e-0790-40b4-9cfa-3568a72cc843)

**Comment by IsabelaPO** [comment]
I would like to have a go at this for a university project.
