### ISSUE TITLE
Flaky test in Project Euler Problem 84

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#53140]
## Describe the bug

A test of Project Euler Problem 84 failed randomly in CI:

<img width="1680" alt="Screenshot 2024-01-12 at 14 26 58" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/4357dc83-e3da-4d5d-972a-4943e67fc11e">

The failure can be seen here: https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/7498904426/job/20414989793?pr=52980.

## Affected page

- Challenge page: https://www.freecodecamp.org/learn/project-euler/project-euler-problems-1-to-100/problem-84-monopoly-odds
- Challenge file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/18-project-euler/project-euler-problems-1-to-100/problem-84-monopoly-odds.md

## Steps to reproduce

Running `test:curriculum` multiple times on the challenge.

## Expected behavior

The test should always pass.

**Comment by gikf** [comment]
Some additional context https://github.com/freeCodeCamp/freeCodeCamp/pull/42161#issuecomment-842289195
