### ISSUE TITLE
Building the Merge Sort Algorithm: the steps using `if` statements do not allow the use of parenthesis to wrap the conditions

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#53141]
### Describe the Issue

The `if` statements in steps 12, 26, and 28 do not allow the use of parenthesis to wrap the conditions of the `if` statements. This is indeed not needed, but it's valid. 

In addition, in these steps, things could be difficult for someone coming from a language that enforces the use of parenthesis to wrap the conditions of a conditional statement (say JavaScript).

### Affected Page

- https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-12
- https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-26
- https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/step-28

## The following code do not pass

Step 12 code:
```py
while left_array_index < len(left_part) and right_array_index < len(right_part):
        if (left_part[left_array_index] < right_part[right_array_index]):
            pass
```

Step 26 code:
```py
def merge_sort(array):
    if (len(array) <= 1):
        pass
```

Step 28 code:
```py
if (__name__ == '__main__'):
    pass
```

### Expected behavior

Parenthesis should be allowed to wrap the conditions of the `if` statements since that's a valid syntax

### Screenshots

Step 12:
![Screenshot 2024-01-12 at 8 39 13 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/262e393a-6f91-4de0-8c1a-10d13283fcc4)

Step 26:
![Screenshot 2024-01-12 at 8 39 25 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/373d8743-b47d-4dfc-931b-fa64debd6ac1)

Step 28:
![Screenshot 2024-01-12 at 8 39 42 AM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/987ee839-5c72-4c57-9807-f43e5510c32e)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Dario-DC** [comment]
There are many cases in which parentheses are not allowed by the test, although the code is valid. In my opinion, the use of parentheses should be discouraged when not required. Anyway, if I understood correctly, re-writing all the tests to use the upcoming ast-based helpers can overcome this inconvenient.

**Comment by Dario-DC** [comment]
It would be great to have the tests for these steps re-written using the new [ast-based helpers](https://opensource.freecodecamp.org/curriculum-helpers/python.html#ast-based-helpers).

Here's an example of a test written with those:
https://github.com/freeCodeCamp/freeCodeCamp/blob/fcf577ead157697fadb215409ba05ce1ce211965/curriculum/challenges/english/20-upcoming-python/learn-python-by-building-a-blackjack-game/5daa813381b9e3db6c126b43.md?plain=1#L28
