### ISSUE TITLE
Bug in Waypoint: Manipulate Arrays With push - push is not defined

### ISSUE THREAD

**Issue by dnoliver** [FreeCodeCamp/FreeCodeCamp#5314]
Challenge [Waypoint: Manipulate Arrays With push](http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push#?solution=var%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%5B%22cat%22%5D%5D%3B%0A%0AourArray.pop()%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22Stimpson%22%2C%20%22J%22%5D%0A%0AourArray.push(%5B%22happy%22%2C%20%22joy%22%5D)%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%5B%22happy%22%2C%20%22joy%22%5D%5D%0A%0Avar%20myArray%20%3D%20%5B%22John%22%2C%2023%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2FmyArray.pop()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray.push(%22dog%22%2C3)%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(z)%7Breturn%20'myArray%20%3D%20'%20%2B%20JSON.stringify(z)%3B%7D)(myArray)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = ["Stimpson", "J", ["cat"]];

ourArray.pop(); // ourArray now equals ["Stimpson", "J"]

ourArray.push(["happy", "joy"]); // ourArray now equals ["Stimpson", "J", ["happy", "joy"]]

var myArray = ["John", 23, ["cat", 2]];

myArray.pop();

// Only change code below this line.
myArray.push(["dog", 3])


// Only change code above this line.

(function(z){return 'myArray = ' + JSON.stringify(z);})(myArray);

```

stacktrace 
```
TypeError {message: "myArray.push(...) is not a function"}
```

**Comment by BerkeleyTrue** [comment]
Wow, that is super weird.

**Comment by ltegman** [comment]
Not sure why that's the error message this throws, because the reason this is failing is the missing semicolon.

**Comment by BerkeleyTrue** [comment]
Oh yes. I remember this now. 

@ltegman That is true.

What is really happening is due to the parenthesis used on the following line

```js
(function(z){return 'myArray = ' + JSON.stringify(z);})(myArray);
```

The JS interpreter ignores whitespace, so you end up with
```js
myArray.push("dog",3)(function(z){return 'myArray = ' + JSON.stringify(z);})(myArray);
```

The JS interpreter then attempts to call the return of `myArray.push()` as a function with the argument `function(z){return 'myArray = ' + JSON.stringify(z);}`. 

@dnoliver This is the reason you should always use semicolons. 


Happy Coding!

**Comment by dnoliver** [comment]
Well, I think it is ok to not accept code with missing semicolons. But the error message is really weir :)

**Comment by BerkeleyTrue** [comment]
JavaScript error messages aren't usually very helpful, but the message makes sense in this case. Since you are trying to call the return from myArray.push as a function. JavaScript attempts to identify this as `myArray.push(...)`.
