### ISSUE TITLE
Unclear instructions on Step 6 of "Learn localStorage by building a Todo App"

### ISSUE THREAD

**Issue by rahuljindal1** [freeCodeCamp/freeCodeCamp#53151]
### Describe the Issue

On Step 6, It is not clear from the instructions that code to remove `hidden` class should be put in the event handler callback.
Also, I do not think that anywhere in exercise before Step 6, `toogle` method on `classList` being used or explained, which can be confusing for new developers that a new method to be used.

**Description:**
<img width="566" alt="Screenshot 2024-01-12 at 8 54 23 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/c225342a-dac2-4a46-9a46-d18f1c3c7648">

<br />
<br />

Instead a much better explanation is provided in the Assertion error

> Your event listener should include a callback function for the second argument using arrow syntax without curly braces. Then you should use the classList property and its toggle method on the taskForm, to toggle the class hidden

<br />

**Error Message:** 
<img width="628" alt="Screenshot 2024-01-12 at 8 54 11 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/ee5ea68b-2b70-4b54-b1e2-1c63889e16f1">

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-6

### Your code

```



```

### Expected behavior

More clear instructions to be provided with explanation to use new `toogle` method on `classList`

### Screenshots

Attached in the description

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
I think the description and hint text can both be updated here

# --description--

Now, you will work on opening and closing the form modal.

In earlier projects, you learned how to add and remove classes to an element with `el.classList.add()` and `el.classList.remove()`. Another method to use with the `classList` property is the <dfn>toggle</dfn> method. 

The `toggle` method will add the class if it is not present on the element, and remove the class if it is present on the element.

```js
element.classList.toggle("class-to-toggle");
```

Add an event listener to the `openTaskFormBtn` variable and pass in a `click` event for the first argument and an empty callback function for the second argument. 

For the callback function, use the `classList.toggle()` method to toggle the `hidden` class on the `taskForm` element.

Now you can click on the "Add new Task" button and see the form modal.

## Updated hint text

The third hint text should say this instead 

```md
Your event listener's callback function should contain `taskForm.classList.toggle("hidden")`. 
```
Also, we should allow either valid answer and not be so strict about the callback function not including curly braces.
The tests should be updated so either of these answers passes

```js
openTaskFormBtn.addEventListener("click", () =>
  taskForm.classList.toggle("hidden")
);
```
```js
openTaskFormBtn.addEventListener("click", () => {
  taskForm.classList.toggle("hidden")
});
```

**Comment by lasjorg** [comment]
Same here, `openTaskFormBtn` is an element. You can not really attach an event listener to a variable.
