### ISSUE TITLE
<p> colour is not changing and <p2 > colour have changed

### ISSUE THREAD

**Issue by reethupolepally** [FreeCodeCamp/FreeCodeCamp#5315]
Challenge [Waypoint: Change the Font Size of an Element](http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%20%20%7D%0A%20%20.font-size%20%7B%0A%20%20%20%20font-size%3A16px%3B%0A%20%20%7D%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%20%20%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%20%3E%3Cp%20class%3D%22font-size%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff%20%3C%2Fp%3E%0A%3Cp2%20class%3D%22red-text%22%20%3E%3Cp2%20class%3D%22font-size%22%3Epurr%20jummp%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2Cshed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched%3C%2Fp2%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
     }
  .font-size {
    font-size:16px;
  }
  }
  
</style>
  
<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text" ><p class="font-size">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff </p>
<p2 class="red-text" ><p2 class="font-size">purr jummp eat the grass rip the couch scratched sunbathe,shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched</p2>
```

**Comment by ltegman** [comment]
There's quite a bit wrong with your solution code. `p2` is not a valid tag, you're opening more tags than you're closing and you shouldn't be making a new css class rule for `.font-size`, you should just be changing the font size in the `.red-text` rule.

In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for challenge help.

Thanks and happy coding!
