### ISSUE TITLE
Update descriptions, hint text and tests for Step 7 and 8 of  Todo App

### ISSUE THREAD

**Issue by rahuljindal1** [freeCodeCamp/freeCodeCamp#53153]
### Describe the Issue

In the description, it is explained how `showModal()` method to be used on `confirmCloseDialog` and it is a built in method for `dialog` elements.

While in the hint it is being mentioned that  `showModal()` to be set on `confirmCloseDialog`, which I do not think is a correct statement. Setting `showModal()` is giving the illusion that `showModal() `to be assigned to `confirmCloseDialog` as value.

More appropriate hint would have been: 
> Your event listener should use arrow syntax to call the `showModal()` method on `confirmCloseDialog`.

`set` to be replaced with `call`

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-7

### Your code

```



```

### Expected behavior

Adding a more appropriate hint like: 
> Your event listener should use arrow syntax to call the `showModal()` method on `confirmCloseDialog`.

`set` to be replaced with `call`

### Screenshots

<img width="600" alt="Screenshot 2024-01-12 at 9 14 16 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/ca8cf295-80c0-481d-b1d2-d2d455cc9c50">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
We should update the descriptions to include code snippets for the showModal and close methods. And update the tests to not be strict about curly braces for the callback and accept any valid answer. 

## Changes for step 7
# --description--

The HTML `dialog` element has a `showModal()` method that can be used to display a modal dialog box on a web page.

```js
dialogElement.showModal();
```

Add an event listener to the `closeTaskFormBtn` variable and pass in a `click` event for the first argument and a callback function for the second argument.

For the callback function, call the `showModal()` method on the `confirmCloseDialog` variable. This will display a modal with the `Discard` and `Cancel` buttons.

### updated hint text for 3rd test
```md
Your event listener's callback function should call the `showModal()` method on the `confirmCloseDialog` variable.
```
The test should be updated to allow for either valid answer here

```js
closeTaskFormBtn.addEventListener("click", () => {
  confirmCloseDialog.showModal();
});
```
```js
closeTaskFormBtn.addEventListener("click", () => confirmCloseDialog.showModal());
```

## Changes for step 8
# --description--

If the user clicks the `Cancel` button, you want to cancel the process and close the modal so the user can continue editing. The HTML `dialog` element has a `close()` method that can be used to close a modal dialog box on a web page.

```js
dialogElement.close();
```

Add an event listener to the `cancelBtn` element and pass in a `click` event for the first argument and a callback function for the second argument.

For the callback function, call the `close()` method on the `confirmCloseDialog` variable.

### updates to test 3 hint text

```md
Your event listener's callback function should call the `close()` method on `confirmCloseDialog` variable.
```
The test should be updated to allow for either valid answer here

```js
cancelBtn.addEventListener("click", () => confirmCloseDialog.close());
```
```js
cancelBtn.addEventListener("click", () => { 
confirmCloseDialog.close()
});
```

```js
cancelBtn.addEventListener("click", () => 
confirmCloseDialog.close()
);
```

**Comment by lasjorg** [comment]
I would suggest calling `confirmCloseDialog` an element.

Sure it is a variable, but it contains an element and that element is the one that has the method on it.
