### ISSUE TITLE
Partial description in Step 8 of "Learn localStorage by building a Todo App"

### ISSUE THREAD

**Issue by rahuljindal1** [freeCodeCamp/freeCodeCamp#53154]
### Describe the Issue

In the description it is not being mentioned that there should not be any curly braces for the arrow function and when code is being written with curly braces, only then from the hint we can get the idea that curly braces not to be added.

**Step 8 Error:**
<img width="400" height="300" alt="Screenshot 2024-01-12 at 9 25 49 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/e682306c-1b9c-4e9f-9510-e3b755af807e">

While in the previous step ( Step 7 ), tests are getting passed with and without braces. Because of which it seems like Step 8 will follow the same, while that is not happening at the moment. I think this should be consistent across steps to remove any ambiguity.

**Step 7 Success with braces:**
<img width="400" height="300" alt="Screenshot 2024-01-12 at 9 29 17 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/9e7458cd-de3a-4f3c-a81b-c33fbc9a347a">

**Step 7 Success without braces:**
<img width="400" height="300" alt="Screenshot 2024-01-12 at 9 29 39 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/64740698/8ce33ea2-d517-4a10-8961-c37113ff7eae">

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-8

### Your code

Added in the description

### Expected behavior

Info for adding curly braces in the description and having a consistent workflow for using arrow functions

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Njong392** [comment]
I don't think it's a case special to step 8, but yeah. Just like other steps I think the code should pass with/without braces.

**Comment by lasjorg** [comment]
In my opinion, the only time we should require an expression body is if the function returns a value and we want that return to be implicit. Otherwise, the tests should not care if it is using an expression body or a concise body (body block).

As this function does not return a value both forms should be valid.

**Comment by jdwilkin4** [comment]
I am going to close this issue because my proposed solution in your other issue here will allow for any valid solution to pass and remove the mention of curly braces. 

https://github.com/freeCodeCamp/freeCodeCamp/issues/53153
