### ISSUE TITLE
RPG - Step 40 - 41: Passing with wrong code

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53163]
### Describe the Issue

Edited steps to reflect the new order (was 41-42 before).

The tests will pass if you invoke the callbacks instead of assigning the definition/identifier.

40 passing with incorrect code.
```js
button1.onclick = goStore();
```

41 passing with incorrect code.
```js
button1.onclick = goStore();
button2.onclick = goCave();
button3.onclick = fightDragon();
```

Edit: In fact, as long we match on the start of the function name you can put whatever you want after. So this will pass as well.

```js
button1.onclick = goStoressss;
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-40

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-41

### Your code

```



```

### Expected behavior

The test should not allow function invocation.

The test should match the actual function identifier.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by iprime2** [comment]
@lasjorg Hey, How are you i want ask something.
Are expecting the test should pass on these code
```
button1.onClick = goStore();
```

**Comment by lasjorg** [comment]
No, the tests should not pass when invoking the functions.
