### ISSUE TITLE
Building a Music Player - Step 87 last requirement is poorly worded and uses a regex test

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53160]
### Describe the Issue

The last requirement is poorly worded.

> After that, create a `nextSongExists` constant that checks if a next song exists.

The `nextSongExists` is a variable containing the evaluation of an expression. It does not check for anything. Checking for something is an action.

There is no hint in the initial requirement of how we are expecting them to solve this. Leaving it in the hints seems kind of mean. They think of the problem, come up with a solution, write the solution, and then are told "No, it _must_ be written like this".

---

As is the case for other challenge steps this is using a regex and expects a fixed solution.

If all we cared about was that the `nextSongExists` variable contained the correct boolean value, how it is arrived at, doesn't matter. If we want to teach a specific solution to a problem that should be the focus of the challenge step and included in the challenge text and requirements.

Tests: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/655b49333d9f265bc1512152.md

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-87

### Your code

```



```

### Expected behavior

1. Clarify requirements.
2. If a single solution is required, teach that solution.
3. Do not pretend to ask for code that solves a problem when that isn't the requirement.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
> If all we cared about was that the nextSongExists variable contained the correct boolean value

Yeah, that is the goal.
We could update the last test to use chai's assert methods instead of purely regex tests 

> The nextSongExists is a variable containing the evaluation of an expression. It does not check for anything. Checking for something is an action.

Any suggestions for rewording?


> Expected behavior
Clarify requirements.

Personally, I am leaning towards breaking this step up into 2 steps because there is a lot going on already.
I think that will make it easier to clean up the directions.

**Comment by lasjorg** [comment]
The problem is the variable is scoped to the function. It would need to be assigned to a top-level variable or the function would need to return the value for us to have access to it.

I guess we can have them return the value out of the function so we can test it and then have them remove that return again in the next step.

---

The rewording/clarification is only if we can't test the value and require a fixed solution. Because if that is the case, we can't just ask them to solve a problem yet expect a single fixed solution. We would need to include the solution and how to write it as part of the challenge text.

**Comment by jdwilkin4** [comment]
> I guess we can have them return the value out of the function so we can test it and then have them remove that return again in the next step.

I like this option

**Comment by lasjorg** [comment]
It does seem like the best option.

Oh, and I forgot about this, we should still change this.

> After that, create a `nextSongExists` constant that checks if a next song exists.

Maybe something like

> Create a `nextSongExists` constant that contains the boolean value `true` or `false` depending on if the next song exists.

**Comment by jdwilkin4** [comment]
That rewording works for me.

I'll go ahead and open this up for contribution

**Comment by gduteaud** [comment]
Weighing in as someone currently taking this course: "After that, create a nextSongExists constant that checks if a next song exists." feels very vague. I wrote
`const nextSongExists = currentSongIndex + 1 > allSongs.length ? true : false;`
and was surprised at the hint suggesting `userData?.songs[currentSongIndex + 1] !== undefined` as undefined was barely discussed at all so far in the course. 

Hope this feedback is helpful!

**Comment by jdwilkin4** [comment]
Hey @gduteaud ! 

Thanks for your feedback.

If you have any more feedback as you go through the course, we encourage you to open up an issue on GitHub so we can update the curriculum and make it easier for beginners 👍

**Comment by lasjorg** [comment]
Also, just to be clear. If we update the test to only check the value contained in `nextSongExists` it won't matter how you get to the correct value.

That should be our goal, let the camper solve this any way they want to.

But I agree. That part of the sentence should also be updated as I suggested.

**Comment by lasjorg** [comment]
This does bring up one issue with the curriculum. If we do allow any valid solution, the code the camper has written will not be the same code that will be in the next step (seed code).

I think explaining how the code from one step is not carried over to the next step is probably something that would need to be explained to help clear up some confusion.

I would prefer if we allowed any valid solution when possible but I also think there are times when teaching a specific solution to a problem is OK to do. But it must be done deliberately and not as a problem-solving exercise. It should be clear one specific solution to a problem is being taught and we should guide them through that solution.

**Comment by DivyaMaddipudi** [comment]
So, Do we have to allow the camper to write multiple codes that give the same output?

For example, 

1. const nextSongExists = currentSongIndex + 1 > allSongs.length ? true : false; 
2. userData?.songs[currentSongIndex + 1] !== undefined

If both are correct, do we have to pass the test?

**Comment by jdwilkin4** [comment]
@DivyaMaddipudi 

> If both are correct, do we have to pass the test?

Yes. We should not force a fixed solution here.
Instead, we should allow campers to pass with any valid solution like you mentioned.

**Comment by PedroRamos360** [comment]
The link to the page in the issue is: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-82. Shouldn't it be: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-87  ?

I opened the page and did not find what you were talking about the variable `nextSongExists` looking at the file to change however I found that the problem was in step 87.

**Comment by lasjorg** [comment]
Changes are being made that move steps around. The code file linked to is still correct. I updated the title and challenge link.
