### ISSUE TITLE
Audio in English curriculum doesn't play on some iOS devices

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#53165]
### Describe the Issue

The audio in the English curriculum isn't playing on some iOS devices. Here's a forum post which first mentioned the issue: https://forum.freecodecamp.org/t/no-sound-on-ipad-iphone-a2-english-for-developers/663538

A few people on have tested and here's what they said...

It worked for some on these devices:
iOS 17.2.1 Safari
iPad 8 Safari / Chrome
iPhone 12 iOS 17.1.2 Safari / Chrome

It didn't work for some on these devices:
iPhone 12, iOS 16.6.1 Safari / Chrome 120.0.6099.119
iPhone 8 iOS 16.7.2

Seems like it might be a device settings issue.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/

### Expected behavior

It to play the audio.

Edit: Seems like it might be an issue with iOS. I upgraded my iPhone from 16.6.1 (didn't work on Safari or Chrome) to 17.2.1, and it works now on Safari and Chrome (same chrome version).

**Comment by Sembauke** [comment]
I can't reproduce it either on Iphone 14 Pro, neither on MacOs Sonoma
