### ISSUE TITLE
Learn String manipulation by Building a Cipher - Step 57: Mismatch Variable Name 

### ISSUE THREAD

**Issue by jharemza** [freeCodeCamp/freeCodeCamp#53170]
### Describe the Issue

In the Scientific Computing with Python (Beta) course, module Learn String manipulation by Building a Cipher, Step 57 the variable name is mismatched be tween the instructions and the error message.

In the instructions the variable name is referred to as `key_char`. Whereas in the error message I received, the variable is referred to as `key_index`.

The instructions read:

> ### Step 57
> Next, inside the `else` block, declare a variable called `key_char` and assign it the value of `key` at the index `key_index` mod(`%`) the length of `key`.

As shown in the code I submitted generated an error because my modulo declaration was outside the index square brackets. However, the suggestion portion of the error message used a distinctly different name from the instructions.

> You should assign `key[key_index % len(key)]` to your `key_index` variable.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-57

### Your code

```python
        # Append space to the message
        if char == ' ':
            encrypted_text += char
        else:
            key_char = key[key_index] % len(key)


```

### Expected behavior

My expectation is the suggestion portion of the error message should read:

You should assign `key[key_index % len(key)]` to your `key_char` variable.

### Screenshots

![step 57 screenshot](https://github.com/freeCodeCamp/freeCodeCamp/assets/47305462/361c8901-98b3-4b90-a5b2-8cd0a8573482)

### System

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 120.0.6099.217 (Official Build) (64-bit)

### Additional context

I did test a fix to my sub mitted code and the following was accepted as correct:

```python
        # Append space to the message
        if char == ' ':
            encrypted_text += char
        else:
            key_char = key[key_index % len(key)]
```

**Comment by Vijaychandra-Govindapalle** [comment]
Hey, I was trying to work on this issue using gitpod , but when i run the command for  the challenge editor  it is showing me the error: failed to fetch .
![Screenshot 2023-11-02 090051](https://github.com/freeCodeCamp/freeCodeCamp/assets/118375565/49a39bd2-b7c6-4ba4-b822-26ca3c65962f)

**Comment by gikf** [comment]
Hey @Vijaychandra-Govindapalle this issue is not a place for problems with using challenge editor in github. What you are experiencing can be tracked at https://github.com/freeCodeCamp/freeCodeCamp/issues/53131
