### ISSUE TITLE
Remove extra space between lines

### ISSUE THREAD

**Issue by sharmarahul8222** [freeCodeCamp/freeCodeCamp#53188]
### Describe the Issue

There is extra space is coming in .gitignore file at line no. 66.

### Affected Page

.gitignore file

### Steps to Reproduce

In the Code Repository: 
  1. Go to the .gitignore file.
  2. Scroll down to the line no 66.
  3. Remove the extra space between lines.

### Recommended fix or suggestions

Just delete the extra space between lines.

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this is intended. As such I'm going to close the issue.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
