### ISSUE TITLE
RPG - Step 120: Text inside code block is visually missing the starting space

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53198]
### Describe the Issue

The text `You attack it with your <weapon>.` has a space in front of it that you can't see in the challenge text.

Not sure if it has to be a fenced code block (three backticks) for the space to show up. I assume it is because it is missing the `pre` element when it is just a single backtick code block. Maybe there is a setting as well that we can enable for it?

> On a new line, add the string
> 
> ``` 
>  You attack it with your <weapon>
> ```
> 
> to the text value, replacing `<weapon>` with the player's current weapon.

That or we need to mention it in the text or hints.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-120

### Your code

```



```

### Expected behavior

To see the spaces in the required text.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-120

**Comment by tix980** [comment]
Hello @jdwilkin4, Can I take on this issue?

**Comment by jdwilkin4** [comment]
@tix980 

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ieahleen** [comment]
a fenced code block works, but there isn't much difference visually, I don't see the space at the beginning either way. I would vote explicitly writing it somewhere

**Comment by lasjorg** [comment]
Being explicit about it is a good idea.

We should still use a code block just to make sure the camper can copy the text with the space included.

**Comment by israelone** [comment]
If the whole purpose is to separate both sentences, why don't we add an empty space after the first line like below? That way the camper wouldn't have to worry about spaces
![Screenshot 2024-01-18 124410](https://github.com/freeCodeCamp/freeCodeCamp/assets/22969168/cba4d1a6-9be5-4a88-b4ca-2695c27aa48b)

**Comment by lasjorg** [comment]
I guess aesthetically it might look better to move it to the previous step as that would allow for the use of a single backtick code block and still show the ending space.

But either way, we should probably still be explicit about the space.

**Comment by a2937** [comment]
This is a fairly recent thing, but this step has been shuffled to step 119. Not step 120 as it was previously.
