### ISSUE TITLE
Text formatting Waypoint: Get JSON with the jQuery getJSON Method

### ISSUE THREAD

**Issue by aric87** [FreeCodeCamp/FreeCodeCamp#5320]
The requirement text has an extra `\` as if it was trying to be escaped. ```Don\'t forget to make the .html change the contents of the message box so that it contains the result of the getJSON.```

**Comment by erictleung** [comment]
Looks like this issue was fixed but didn't close correctly. I guess Github is a little picky on how to close issues :stuck_out_tongue:

**Comment by HoBi** [comment]
@ltegman maybe close this? :-)
