### ISSUE TITLE
Avoid inline handlers and using HTML event attributes

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53202]
### Describe the Issue

I know this would be a lot of changes but I would really prefer if we didn't do that whenever possible.

A few inline handlers in dynamically added HTML isn't the end of the world but adding them to static HTML rubs me the wrong way. It is usually also discouraged in teaching materials (e.g. MDN, etc.).

Using HTML event attributes `ele.onclick = fn` is again usually discouraged and here I'm not sure I see a good reason for (pretty much ever) doing that. We should teach adding event listeners using `addEventListener` on the elements.

I know this is highly opinionated. I just feel like beginners should be shown good practices when possible. After that, any developer that wants to do it their way can do that.

### Affected Page

https://www.freecodecamp.org/learn

### Your code

```



```

### Expected behavior

Teach the best practices when possible.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment]
Do you have specific projects/steps in mind with this feedback?

**Comment by lasjorg** [comment]
I think this was based on the RPG challenge and the statistics calculator inline form submit handler (there was an issue around this time).

I also kept seeing people doing it in their code when asking for help (certificate projects) so I guess I just assumed it was more prevalent in the curriculum as well, but it doesn't seem to be the case. At least when I quickly looked over the challenges it didn't seem like much of an overall issue.

RPG handlers (I'd prefer if we taught addEventListener)
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-174

statistics calculator inline form submit handler (don't think this needs to be inline)
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-50

spreadsheet input onchange update handler (this seems fine)
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-103


I wouldn't mind if we changed the RPG handlers. I assume it was an intentional decision, but seeing as it is the first introduction to event handlers it might also give the wrong idea.

**Comment by jdwilkin4** [comment]
> I wouldn't mind if we changed the RPG handlers. I assume it was an intentional decision, but seeing as it is the first introduction to event handlers it might also give the wrong idea.

Yeah, I think it would be good to change the RPG project to use add Event listener.

I am currently working on the rewrite for the RPG project, so I can add those changes in there
https://github.com/freeCodeCamp/freeCodeCamp/pull/53803

**Comment by jdwilkin4** [comment]
After playing around with the RPG project, to change it to use addEventListener, you would also need to use removeEventListener and additional steps to teach that in order for the functionality to work properly. 

That would be probably be best in a separate PR and it would be good to hear from the other mods and staff on what they think.

**Comment by lasjorg** [comment]
Keeping it as is isn't a huge deal.

I just wish it wasn't the first introduction to event listeners or that the camper was in a better position (i.e. not the first challenge) to see the difference between this approach and using `addEventListener`.

---

Another option would be to use an [abort controller](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) but that might be beyond the scope of the challenge and it isn't the easiest to explain.

I only tested it a bit, there might be some bugs with it I didn't catch.

https://github.com/lasjorg/fCC-Role-Playing-Game-AbortController

I guess rerendering or just recreating the buttons is an option as well.

**Comment by jdwilkin4** [comment]
There are no inline handlers in the new cert. only `addEventListener` and `removeEventListener` is used.
