### ISSUE TITLE
update tests in RPG game to only match let and not depend on var

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53209]
### Describe the Issue

This issue is responsible for refactoring these tests here to no longer depend on `var` for the RPG .
https://github.com/freeCodeCamp/freeCodeCamp/pull/53166/commits/d3d78afe04b4498bdbeacd3555c950ee5527000b

Once this PR is resolved and merged in, then we can update the tests mentioned above
https://github.com/freeCodeCamp/freeCodeCamp/pull/53127

The full context of the conversation can be seen here
https://github.com/freeCodeCamp/freeCodeCamp/pull/53166

### Affected Page

n/a

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by moT01** [comment]
Update: still waiting on the PR in the description to be merged.

**Comment by jdwilkin4** [comment]
I think we can just close this because the RPG project is not in the new cert and this project will be legacy once the new cert is launched.
