### ISSUE TITLE
Nutrition label step 61 missing tests

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/freeCodeCamp#53210]
This step is passing even if protein is not bold

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-61

> Use the necessary classes to remove the bottom border, and a span to make the Protein bold.

```
      <p class="no-divider">Protein 3g</p>
      <div class="divider large"></div>
```

**Comment by nannapanenir** [comment]
I have added this code below code !

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/40239045/9b4d1f2f-5623-462a-ba3d-b45d417382f7)

The output it showing as 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/40239045/ba2b29a7-7400-457d-82a7-19da2c173c0e)

is this the result your looking for ! or can you be little more specific  - ieahleen what your looking for


Thanks.

**Comment by a2937** [comment]
Hi there @nannapanenir . We are looking for the _tests_ for the challenge to be altered. Not the intended results of the challenge. I appreciate the enthusiasm though.
