### ISSUE TITLE
Content Security Policy Disables Browser Sync

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/FreeCodeCamp#5321]
Only effects the autorefresh from browser-sync when running FCC in a local dev environment.

@BerkeleyTrue Not sure if you feel this is important enough to add an exception to the security policy for it or if you'd rather just ditch the feature.

![a_map_to_learn_to_code_and_become_a_software_engineer___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/11850639/7cf8c27c-a3e3-11e5-91bd-3596817219bf.png)

**Comment by SaintPeter** [comment]
This is an issue for me as well.

**Comment by BerkeleyTrue** [comment]
We can add the exception in dev mode only

**Comment by BerkeleyTrue** [comment]
This is fixed.
