### ISSUE TITLE
API for leaderboard

### ISSUE THREAD

**Issue by roelver** [FreeCodeCamp/FreeCodeCamp#5322]
*** related to issue [#5133](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5133) ***

The database for the FCC leaderboard that currently runs on [Heroku](http://fcctop100.herokuapp.com) has a couple of disadvantages.
* The data is refreshed manually (by me)
* The user results are gathered by screen scraping the [FCC user page](http://www.freecodecamp.com/roelver).
* The only way to get a list of userid's is by calling the API on the [FCC main Gitter chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp). This causes that the leaderboard exposes only users that have registered for the Gitter chat and use their Github-login for the FCC account.
* Currently the Gitter API is restricted to the first 100 users, with no option to skip and read the next batch of 100.
* The fornt-end is written in Angular
    
I created a [new front-end in React](http://codepen.io/rokidoki/full/MKWVKW/), but it is using an API on top of the database at Heroku. To resolve all the other issues the API should move to the FCC site, pulling data from the user database, either by adding count properties to the user collection or create a new collection for the leaderboard.

For each user the total points (brownies), number of completed basejump, zipline, bonfire and waypoint challenges has to be counted. Another score is the "community help", being the number of points gathered otherwise than by completing challenges. 
These items are counted both over the past 30 days and all time.
The database should not include the users that choose to hide the challenge results ()

The API should:
* return an array of the **all time** top 100 ranked users, ordered by (descending) total points, community help score, number of completed basejump, zipline, bonfire or waypoint challenges.  (example http://fcctop100.herokuapp.com/api/fccusers/alltime/basejumps ) 
* return an array of the **past 30 days** top 100 ranked users, ordered by (descending) total points, community help score, number of completed basejump, zipline, bonfire or waypoint challenges. (example http://fcctop100.herokuapp.com/api/fccusers/recent/community )
* allow a single user to be refreshed, no return data. (example http://fcctop100.herokuapp.com/api/fccusers/update/roelver ) 

The userid, github-avatar (img) and the last update timestamp should be returned as well. Another total score should be returned with bonus incentives for completed basejumps, ziplines and bonfires. The current leaderboard computes this total score = points + (basejumps * 60) + (ziplines * 30) + (bonfires * 3).

**Comment by QuincyLarson** [comment]
Here's @roelver's schema: https://drive.google.com/open?id=0B1oM2t1pBZSTRk90dGdsWHpNNXI0VE5TMi03VU9UeWpPZE1B

**Comment by QuincyLarson** [comment]
I'm adding @BerkeleyTrue to this so he can help us decide how to best go about exposing the relevant endpoint.

**Comment by QuincyLarson** [comment]
Hi @roelver quick question what are the two URLs I should use if I want total points recently and total points of all time? I was unable to figure those out. I've simplified your pen to just have a column for recent points and total points and I want to provide campers with just two URLs to those specific endpoints: http://codepen.io/FreeCodeCamp/pen/qbqqJm

Thanks!

**Comment by QuincyLarson** [comment]
@roelver we're going to work on the open API later. 

With the curriculum expansion, this particular challenge will be moved into the "extra practice projects" section and will receive a lot less attention as a result.
