### ISSUE TITLE
Update tests for step 91 of spreadsheet project to accept multiple solutions

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53225]
### Describe the Issue

The expected solution for step 91 is the following 

```js
 if (!value.includes(element.id) && value.startsWith('=')) {
    element.value = evalFormula(value.slice(1));
  }
```
However, the directions don't mention using the `slice` method

> The first argument for your evalFormula call needs to be the contents of the cell (which you stored in value). However, the contents start with an = character to trigger the function, so you need to pass the substring of value starting at index 1.

Since the directions mention `"Passing the substring of the value"` then a camper could write this and then be surprised to learn that the `slice` method is expected. 

```js
element.value = evalFormula(value.substring(1));
```
we should update instructions here to let campers know that there is an expected solution.
Or update the tests to allow for multiple valid solutions.

Open to hearing thoughts

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-91

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Njong392** [comment]
It would be interesting to see how campers can achieve the same result with both methods since they do the same job fairly, so I'm up for modifying the test to accept multiple valid solutions. As per the solutions it can accept, I looked up a few methods, and stuff like `substr` is now said to be 'legacy'... ?  So if we do validate the option of modifying the tests, only `slice` and `substring` would be accepted?

**Comment by lasjorg** [comment]
We could use the event. That way it is only the value set on the element we care about.

But I can't figure out how to do the assert inside a window load event (we have to wait for the DOM). I see the assert in the browser console but the test just passes anyway.


```
window.addEventListener("load", () => {
  const event = new Event("change");
  const inputElement = document.getElementById("A1");
  inputElement.value = "=123";
  inputElement.dispatchEvent(event);
  assert.equal(inputElement.value, "123");
});
```

```
const update = event => {
  const element = event.target;
  const value = element.value.replace(/\s/g, "");
  if (!value.includes(element.id) && value.startsWith('=')) {
    element.value = evalFormula(value.slice(2));
  }
}
```

```
Uncaught AssertionError: expected '23' to equal '123'
```

I tried a few different things (try/catch, throwing, assert.fail, promise delays and try/catch) but I can't get the test to fail properly. There is apparently something about how the tests run I don't understand.

**Comment by naomi-lgbt** [comment]
Rather than that approach, we could **mock** the event.

```js
const mock = {target: {value: "=123"}};
update(mock);
assert.equal(mock.target.value, "123");
```

Or some such.

**Comment by Ksound22** [comment]
> It would be interesting to see how campers can achieve the same result with both methods since they do the same job fairly, so I'm up for modifying the test to accept multiple valid solutions. As per the solutions it can accept, I looked up a few methods, and stuff like `substr` is now said to be 'legacy'... ? So if we do validate the option of modifying the tests, only `slice` and `substring` would be accepted?

@jdwilkin4 I think we should go with something like this

**Comment by jdwilkin4** [comment]
I am going to go ahead and open this up for contribution.
So it looks like instead of updating the directions to expect one solution, we will just update the tests to accept multiple valid solutions.

It looks like the conversation in this thread has focused on different approaches to update the tests but I think that we can leave that actual implementation up to the contributor. 👍
