### ISSUE TITLE
Update directions and hint text for step 31 of spreadsheet project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53221]
### Describe the Issue

We got some feedback here about the spreadsheet project step 31

https://forum.freecodecamp.org/t/feedback-learn-functional-programming-by-building-a-spreadsheet/663204

They mentioned that if you try to use an OR operator here then the hint does not tell you what's wrong.

### Incorrect answer
```js
 if (!value.includes(element.id) || value.startsWith('=')) {

  }
```
### correct answer
```js
  if (!value.includes(element.id) && value.startsWith('=')) {

  }
```
I think the easiest fix would be to just update the directions and hint text to explicitly mention the use of the AND operator. 

## Note to first time contributors 
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/64497e0e5e5a2c2329785af4.md

## Updates to the directions

```md

# --description--

Spreadsheet software typically uses `=` at the beginning of a cell to indicate a calculation should be used, and spreadsheet functions should be evaluated.

Use the `&&` operator to add a second condition to your `if` statement that also checks if the first character of `value` is `=`.
```
## updates to the hint text

```md
# --hints--

You should use the `&&` operator to add a second condition to your `if` statement that also checks if the first character of `value` is `=`. You may use `[0]`, `.startsWith()`, or `.charAt(0)`.
```

Happy coding

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-31

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by domlimm** [comment]
@jdwilkin4 Hey Jessica, may I open a PR to fix this issue? Thank you!
