### ISSUE TITLE
Typo in step 11 of new Javascript Cert "Learn localStorage by Building a Todo App" challenge

### ISSUE THREAD

**Issue by gduteaud** [freeCodeCamp/freeCodeCamp#53227]
### Describe the Issue

Instructions text says "findIndex is an array method that lets find the index of the first element in an array that satisfies a given testing function."

Following the style of previous similar statements in the course, "lets find" should probably say "lets **you** find".

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-11

### Your code

```



```

### Expected behavior

"lets you find" instead of "lets find"

### System

- Device: laptop
- OS: Windows 11
- Browser: Chrome
- Version: 120

**Comment by jdwilkin4** [comment]
Hey @gduteaud ! 

That's a good catch.

But after reading through the directions there are a few things that could be cleaned up to simplify it a bit and there are a few things missing like the `<dfn><dfn>` markers to indicate a new term is being introduced.

Let's go with this revised description 

````md
# --description--

You will need to determine whether the task being added to the `taskData` array already exists or not. If the task does not exist, you will add it to the array. If it does exist, you will update it. To accomplish this, you can use the <dfn>findIndex()</dfn> method.

The `findIndex` array method finds and returns the index of the first element in an array that meets the criteria specified by a provided testing function. If no such element is found, the method returns `-1`.

Here's an example:

```js
const numbers = [3, 1, 5, 6];
const firstEvenNumIndex = numbers.findIndex((num) => num > 3);

console.log(firstEvenNumIndex); // prints index 2
```

Use `const` to declare a variable called `dataArrIndex` and assign it the value of `taskData.findIndex()`. For the `findIndex()` method, pass in an arrow function with `item` as the parameter. 

Within the arrow function, check if the `id` property of `item` is strictly equal to the `id` property of `currentTask`.
````

I'll go ahead and open this up for contribution.
