### ISSUE TITLE
Clarify instructions for step 28 of music player project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53226]
### Describe the Issue

We have a lot of confusion on the [forum](https://forum.freecodecamp.org/t/learn-basic-string-and-array-methods-by-building-a-music-player-step-28/657246) about the purpose of the `playSong` function in this step.

here are the current directions

> You need to hook up the playSong function to a click event listener so the songs will start playing when the play button is clicked.

> Add a click event listener to the playButton element, then use arrow syntax to pass in a callback with an empty pair of curly braces.

That first sentence of hooking up the `playSong` function to the event listener makes it seem like that is going to be part of the solution.

A better wording for the description should be this 

## updated instructions 

```md
# --description--

In previous steps you built out the functionality for playing a song. Now you need to add the functionality to the play button so that it will play the current song when it is clicked on.

Use the `addEventListener()` method and pass in a `click` event for the first argument and an empty callback function with arrow syntax for the second argument. Ex.(`()=>{}`). 
```
thoughts on the updated directions before it is opened up for contribution?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-28

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Njong392** [comment]
I think the updated version sounds a lot better because the challenge has nothing to do with the `playSong` function, and implementing that part doesn't come up until later in the challenge.

**Comment by jdwilkin4** [comment]
I will go ahead and open this up for contribution 👍
