### ISSUE TITLE
Update directions of step 58 for spreadsheet project 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53222]
### Describe the Issue

We got this feedback on the forum for step 58 of the spreadsheet
https://forum.freecodecamp.org/t/feedback-learn-functional-programming-by-building-a-spreadsheet/663204

Here is direct quote from the learner on the forum

>Chain a function call to what function? I think chaining a function call is the wrong terminology. I thought what is depicted in example is currying, not most people would call function chaining. i.e. func1().func2()

>I guess you could consider currying function chaining, but it might be a point of confusion.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-58

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Naming is hard. `obj.func1().func2()` is more _method_ chaining.

I guess instructions could be changed to not use _chaining_, but to indicate using the returned function from the `addCharacters` directly and calling it straight away.

**Comment by lasjorg** [comment]
I think chaining implies a dot operation, which as pointed out would make it a method (function on an object).

I might call it an immediately invoked function, just as an IIFE is an immediately invoked function expression.


> JavaScript allows you to immediately invoke returned functions:
> 
> ```
> myFunc(1)("hi");
> ```
> 
> Immediately invoke the function returned from your `addCharacters(char1)` call, and pass `char2` as the argument.

**Comment by jdwilkin4** [comment]
Yeah, that revised explanation is much easier to understand. 
let's go with that
