### ISSUE TITLE
Update instructions for step 25 of spreadsheet project to better explain the expected solution

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53220]
### Describe the Issue

We got some feedback on the forum here 

https://forum.freecodecamp.org/t/feedback-learn-functional-programming-by-building-a-spreadsheet/663204

One of the things they brought up, was that they were confused by the answer for step 25.

The instructions say the following 

```md
To keep track of all of your spreadsheet's functions, declare a spreadsheetFunctions object. Using destructuring syntax, set sum, average, and median as properties and values on the spreadsheetFunctions object.
```
When a camper thinks of destructuring, they will probably write something like this because that is what we taught them in the past

```js
const { sum, average, median } = spreadsheetFunctions;
```
however the following code will throw syntax errors because `sum`, `average` and `median` are already defined. 

The tests are expecting this answer 

```js
const spreadsheetFunctions = {
  sum,
  average,
  median
}
```
but we never taught them that approach before.

We should update the directions to better explain the expected solution.
Maybe should include some sort of code example of what we are expecting

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-25

### Your code

see explanation above 

### Expected behavior

see explanation above 

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Right, I don't think that's destructuring syntax, rather than defining new object and using short notation. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#property_definitions

**Comment by jdwilkin4** [comment]
Maybe this updated description could work

# --description--

In JavaScript you can use the shorthand notation for the <dfn>object initializer</dfn> syntax to declare an object literal. 

The following example uses object initializer syntax to declare an object with properties of `dog`, `cat` and `horse`, all set to strings.

```js
const dog = 'Buddy';
const cat = 'Whiskers';
const horse = 'Spirit';

const animals = {
  dog,
  cat,
  horse
};
```

To keep track of all of your spreadsheet's functions, declare a `spreadsheetFunctions` object. Using the shorthand notation for the object initializer syntax, set `sum`, `average`, and `median` as properties and values on the `spreadsheetFunctions` object.

**Comment by jdwilkin4** [comment]
This could replace the last hint text 

```md
You should use the shorthand notation for the object initializer syntax to assign your properties.
```

**Comment by lasjorg** [comment]
I would suggest we log out the object to make clear how the variable names and values connect to the object properties key/value pairs.

> The following example declares a `user` object with the properties `userId`, `firstName`, and `loggedIn`.

```
const userId = 1;
const firstName = "John";
const loggedIn = true;

const user = {
  userId,
  firstName,
  loggedIn,
};

console.log(user); // { userId: 1, firstName: 'John', loggedIn: true }
```

> Object properties consist of key/value pairs. When using shorthand property name syntax, the name of the variable becomes the property key and its value the property value.

---

> as properties and values

Properties are key/value pairs so it should just be "as properties" or as "the key/value pairs".

**Comment by jdwilkin4** [comment]
It looks like this would be the final version based on the feedback

# --description--

Object properties consist of key/value pairs. When using the shorthand property name syntax, the name of the variable becomes the property key and its value the property value.

The following example declares a user object with the properties `userId`, `firstName`, and `loggedIn`.

```js
const userId = 1;
const firstName = "John";
const loggedIn = true;

const user = {
  userId,
  firstName,
  loggedIn,
};

console.log(user); // { userId: 1, firstName: 'John', loggedIn: true }
```

To keep track of all of your spreadsheet's functions, declare a `spreadsheetFunctions` object. Using the shorthand notation for the object initializer syntax, set `sum`, `average`, and `median` as properties on the `spreadsheetFunctions` object.

**Comment by lasjorg** [comment]
> declares a `user` object

---

Maybe we still want this at the start?

> You can use shorthand property names when declaring an object literal.

Just to put what we are teaching upfront before the explanation of it.

**Comment by jdwilkin4** [comment]
I updated the description above
