### ISSUE TITLE
Waypoint: Build Web Apps with Expressjs - Suggestion: Needs some context

### ISSUE THREAD

**Issue by ThumbSnail** [FreeCodeCamp/FreeCodeCamp#5323]
*Not a bug, just a suggestion*:  I feel this waypoint would benefit from a brief introduction or a little context.  Perhaps adding an additional step to the waypoint that links to an article such as...

http://evanhahn.com/understanding-express/

...would be beneficial to other students?  That article gives a good, quick overview of Expressjs and, most importantly, **directly connects it with the Node HTTP server material we just learned in the previous waypoints**.  Without that connection, when I was going through the first few exercises, all I was thinking was:  What on earth is this?  Why am I doing this?  What's going on?

**Comment by ChloeIsis** [comment]
My experience was similar to Jeff's.

**Comment by erictleung** [comment]
@FreeCodeCamp/issue-moderators I don't have Express.js experience to evaluate this sufficiently, but I'm all for giving context to lessons. Should we have this one check box before running the `git clone` command in the challenge? For quick access, here's a link to [Waypoint: Build Web Apps with Expressjs](https://www.freecodecamp.com/challenges/build-web-apps-with-expressjs). 

> - [ ] ...
> - [ ] Read this article on Understanding Express.js (http://evanhahn.com/understanding-express/)
> - [ ] ...

**Comment by raisedadead** [comment]
How about :
> - [ ] Read this article on [Understanding Express.js](http://evanhahn.com/understanding-express/)
