### ISSUE TITLE
Buttons not displayed.

### ISSUE THREAD

**Issue by Stephen-254** [freeCodeCamp/freeCodeCamp#53254]
### Describe the Issue

I was taking the Calories Counter lesson and step 28 won't show the buttons, I have tried disabling extensions, using different browsers and clearing browser caches, I even deleted website data, but still no positive response. Also, the instructions and Editor are all gone.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-28

### Your code

```
const calorieCounter = document.getElementById('calorie-counter');
const budgetNumberInput = document.getElementById('budget');
const entryDropdown = document.getElementById('entry-dropdown');
const addEntryButton = document.getElementById('add-entry');
const clearButton = document.getElementById('clear');
const output = document.getElementById('output');
let isError = false;

function cleanInputString(str) {
  const regex = /[+-\s]/g;

}


```

### Expected behavior

I expected the button and instructions to show up.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #49475, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
