### ISSUE TITLE
Upgrade required functionality for calculator zipline

### ISSUE THREAD

**Issue by TimRizzo** [FreeCodeCamp/FreeCodeCamp#5325]
Challenge [Zipline: Build a JavaScript Calculator](http://www.freecodecamp.com/challenges/zipline-build-a-javascript-calculator) has an issue.

Even if it's added under the heading of 'optional user story', the calculator really ought to provide more helpful feedback than 'NaN' in certain scenarios such as 0 / 0, and not allow users to enter multiple decimal points for a single operand(which if allowed also creates a Nan situation). The current example pen doesn't do this, but it doesn't take a lot more to provide it and gets the gears turning about code handling wacky user input. 

User Agent is: <code>Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.

**Comment by SaintPeter** [comment]
We no longer allow for optional user stories - we list the minimum requirements.  We fully expect users to take the Ziplines and run with them.  If you'd like to do something more interesting than NaN, you're more than welcome to.  We're just not requiring it specifically.

Thanks for the suggestion.
