### ISSUE TITLE
Fix misleading instructions in todo app step 46

### ISSUE THREAD

**Issue by gduteaud** [freeCodeCamp/freeCodeCamp#53258]
### Describe the Issue

Step instructions state:
"Check if the user made changes while trying to edit a task by verifying that the titleInput value is not equal to currentTask.title, the dateInput value is not equal to currentTask.date, **and** the descriptionInput value is not equal to currentTask.description"

Writing the code that actually does this (using the logical AND operator) results in an error that says:
"Your formInputValuesUpdated variable should check if titleInput.value is not equal to currentTask.title **or** dateInput.value is not equal to currentTask.date."

From the context of what is being asked it is clear that the logical OR operator should indeed be used to check whether any, rather than all, of the field values has been modified.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-46

### Your code

```

const formInputValuesUpdated = titleInput.value !== currentTask.title && dateInput.value !== currentTask.date && descriptionInput.value !== currentTask.description;


```

### Expected behavior

Instructions should say to "Check if the user made changes while trying to edit a task by verifying that the titleInput value is not equal to currentTask.title, the dateInput value is not equal to currentTask.date, **or** the descriptionInput value is not equal to currentTask.description"

rather than **and**

### Screenshots

<img width="713" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/153011332/23a46122-040a-411f-a65c-5ce47ba323ab">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Ksound22** [comment]
Thanks for the suggestion. I'm gonna badge this as a `first timer only` so open source beginners can grab it.

**Comment by jdwilkin4** [comment]
## Note to first timer contributors

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
Recent changes were made to this project that hasn't shown up in production yet. So the step numbers will be different here
So this is the correct file that needs to be update. 
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/64fb1c4dc0feb219149a7c7d.md

## Change needed

```md
Inside the `closeTaskFormBtn` event listener, use `const` to create another variable named `formInputValuesUpdated`. Check if the user made changes while trying to edit a task by verifying that the `titleInput` value **is not equal to** `currentTask.title`, the `dateInput` value **is not equal to** `currentTask.date`, or the `descriptionInput` value **is not equal to** `currentTask.description`.
```

Happy coding

**Comment by nicolealaine** [comment]
Thanks for marking this for first timers! I'm going to work on it now :)

**Comment by Theertha-santhosh** [comment]
Hi, I'd like to work on this issue as my first contribution.
