### ISSUE TITLE
Update platformer project to match the new final version

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#53262]
The platformer final code has been updated https://github.com/freeCodeCamp/CurriculumExpansion/tree/main/javascript-algorithms-and-data-structures/Learn-Intermediate-OOP-by-Building-a-Platformer-Game

So the steps have to be updated as well

**Comment by jdwilkin4** [comment]
Hey @ieahleen ! 

Can you provide more details specifically was changed here?

If we are going to open this up for contribution, it will help people know where to look for the new changes so they don't miss anything.

Thanks 👍

**Comment by ieahleen** [comment]
The project was updated so that the checkpoint collection is more strict, and the things drawn in the canvas resize appropriately if the canvas is shorter than 500px

**Comment by jdwilkin4** [comment]
@ilenia-magoni 
I am working on updating the platformer project but looking at the final solution here and it looks like the order property here is never referenced anywhere

https://github.com/freeCodeCamp/CurriculumExpansion/pull/359/files

we could probably just leave the ` this.order = z;` out completely

**Comment by ilenia-magoni** [comment]
it looks like a sensible thing @jdwilkin4
