### ISSUE TITLE
In Map, List Numbers are slightly below or above the Waypoint title

### ISSUE THREAD

**Issue by gasperno** [FreeCodeCamp/FreeCodeCamp#5327]
I noticed that the ordered list in the [Freecodecamp Map] (http://www.freecodecamp.com/map) is misaligned.
![screenshot 2015-12-16 at 19 08 31](https://cloud.githubusercontent.com/assets/7889179/11857684/716ddbd2-a428-11e5-960f-e1e87a57d390.png)
Notice that the numbers in the above image are not aligned with text. They are below the text.
![screenshot 2015-12-16 at 19 10 04](https://cloud.githubusercontent.com/assets/7889179/11857705/a175d51e-a428-11e5-8b25-fc9414ec2b42.png)
Waypoints under Getting Started and HTML section are properly aligned as in the above image.
![screenshot 2015-12-16 at 19 12 28](https://cloud.githubusercontent.com/assets/7889179/11857730/f88bc26e-a428-11e5-904d-be88d3ad7fde.png)
In the above image, numbers look slightly above text.

**Comment by ltegman** [comment]
I can't repro this. Regardless of screen width the numbers are always lined up correctly for me (testing in Chrome)

**Comment by BerkeleyTrue** [comment]
I believe this may have been fixed. see https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5332

**Comment by ltegman** [comment]
Closing this as no repro.

Thanks and happy coding!
