### ISSUE TITLE
Penguins do not fly, they swim (Learn CSS Transforms by Building a Penguin  - Step 86)

### ISSUE THREAD

**Issue by wblondel** [freeCodeCamp/freeCodeCamp#53288]
### Describe the Issue

On the 86th step of the "Learn CSS Transforms by Building a Penguin" course in the "Responsive Web Design" certification, this fun fact is shown:

> Fun fact: Penguins cannot fly without wings.

I believe this is a mistake, because even with wings, [penguins cannot fly](https://oceanservice.noaa.gov/facts/penguinsfly.html). However, they need them to swim.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-86

### Your code

N/A

### Expected behavior

In my opinion, the fun fact should be replaced with:

> Fun fact: Penguins cannot swim without wings.

### System

- Device: all
- OS: all
- Browser: all
- Version: all

### Additional context

On step 93, the "wings" are called "flippers", which is actually the correct word. We might want to consolidate the use of the word "flippers".

**Comment by ShaunSHamilton** [comment]
Hello there,

This is a bit of jest in the lesson intended to give a chuckle. That sentence is there as a segue into the instructions.

It is meant to be like that 🙂 

Hope this clarifies

**Comment by wblondel** [comment]
Hi @ShaunSHamilton ,

Mmmh, I get that the intent is to give a chuckle, but the other two fun facts are actually true and make sense:

> Fun fact: Penguins cannot stand without at least two feet.

> Fun fact: Most, if not all, flippers are not naturally rectangles.

The one on step 86 do not make sense in my opinion
