### ISSUE TITLE
Check your code section disappear when toggle

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#53300]
### Describe the Issue

'Check your code' should be displayed either way if both tabs are toggled or not, if one tab is checked or not. 'Check your code' should be independent of tabs

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-11

### Steps to Reproduce

1. Go to 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-11'
2. Click on 'index.html and style.css' so both are not selected, 'check your code' will disappear, when index.html is selected, 'check your code' isn't displayed, but only when you toggle style.css in checked, 'check your code' shows

### Expected behavior

Either index.html or style.css is selected, 'check your code' should be visible all the time as it is indepedent of both, it is there to check the code.

### Screenshots

<img width="1417" alt="Screenshot 2024-01-21 at 12 16 13" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/8664996/2edc13c2-6b2d-4a9d-968c-bf8e988bb951">

<img width="1428" alt="Screenshot 2024-01-21 at 12 17 12" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/8664996/cc63fd5c-c9e6-4298-a341-0332253a10e7">

<img width="1421" alt="Screenshot 2024-01-21 at 12 17 46" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/8664996/7f7a6078-7a69-4a7f-bd47-3afa4648ff61">

### System

- Device: Laptop
- OS: Version 13.4 (22F66)
- Browser: Chrome
-:Version :  117.0.5938.132 (Official Build) (arm64)

**Comment by ieahleen** [comment]
It's not indipended of either tab, it's exaclty around the code that has to be changed. I will mark this as feature request

**Comment by bbsmooth** [comment]
I'm curious as to what the justification is for this request? @mahassan can you explain a little more why this would be helpful?

**Comment by mahassan** [comment]
> I'm curious as to what the justification is for this request? @mahassan can you explain a little more why this would be helpful?

@bbsmooth on a page the button should be independent of any hide or show div's especially if it is Call to action button, a person might unchecked/hide both div, the CTA will be hidden too.  I want to check my code either way so CTA should be independent.

**Comment by mayankkamboj47** [comment]
I agree with @mahassan, but making "check my code" a fixed element common to all tabs will further reduce room for actual code on the user's screen. If we're doing it, let us make it an option to make the description+checkmycode collapsible first.
