### ISSUE TITLE
Adding Donation SVG Animation

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#53335]
### Is your feature request related to a problem? Please describe.

We are experimenting with adding an SVG animation to our donation modal that highlights most of benefits of donating to freeCodeCamp.

Since the animation does not have audio, I need to make sure each bullet points are read and clearly communicated. 

After the animation is completed, the users should see an illustration of the bear, the bullet point, 'become a supporter' button, and a 'maybe later' button.

If the users click on the maybe later button, the modal closes.

If the users click on the 'become a supporter' button, they will go to tier selection, and then to the payment form. 

Feedback is appreciated. 🙏

![initial-bear-assets](https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/e0503389-f5e3-4c44-831a-003cb08c51bb)
Also @bbsmooth, accessibility recommendations are highly appreciated.

**Comment by trs-web** [comment]
I think 20 seconds is way too long, especially since the only "feature" that users receive is the ability to remove the pop-up. Turns 'freecodecamp' into a money grab, in my opinion.
