### ISSUE TITLE
Typo in "Target a Specific Child of an Element" waypoint

### ISSUE THREAD

**Issue by Naii** [FreeCodeCamp/FreeCodeCamp#5334]
I've found a typo in [Waypoint: Target a Specific Child of an Element Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery) in the following paragraph:

> Here's how you would give the third element in each well bounce:

In my opinion "give" needs to be replaced with "make" because the expression is "make bounce" and not "give bounce". Or it could be "give a bounce", so only an "a" would be missing in this case.

The two corrections could therefore be:

1:
> Here's how you would make the third element in each well bounce:

2: 
> Here's how you would give the third element in each well a bounce:

I'm not a native English speaker, so native speakers please correct me if I'm wrong.

**Comment by sludge256** [comment]
I think it's because they're referring to bounce as in the class name not the action/verb bounce. So instead of saying:
>Here's how you would give the third element in each well bounce

Does,
>Here's how you would give the third element in each well the bounce class

seem more understandable?

Your proposals work too depending on which bounce (class or verb) FCC wants to refer to.

For comparison, [
Waypoint: Target HTML Elements with Selectors Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery) seems to be more explicit/clear
>For example, let's make all of your button elements bounce. Just add this code inside your document ready function:

>`$("button").addClass("animated bounce")`

>Note that we've already included both the jQuery library and the Animate.css library in the background so that you can use them in the editor. So you are using jQuery to apply the Animate.css bounce class to your button elements.

**Comment by Naii** [comment]
Thank you @sludge256, your proposal is more understandable to me and I would like to see it written like that — especially in the interest of other people reading and wanting to understand it.

Your example for comparison is also very good.

Who would make the change in the text / code now?

**Comment by SaintPeter** [comment]
I like this change for clarity.  I'll flag it help wanted and anyone can submit a pull request.

**Comment by Naii** [comment]
Thank you @SaintPeter :+1:

**Comment by shubhekshajalan** [comment]
Hey, I am a beginner and I'd like to work on this. Should I change it to:
1. Here's how you would make the third element in each well bounce
or
2. Here's how you would give the third element in each well a bounce

**Comment by raisedadead** [comment]
Done @Naii !
