### ISSUE TITLE
Archive Legacy Responsive Webdesign

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#53341]
### Is your feature request related to a problem? Please describe.

We should probably think about archiving the legacy Responsive web design and archive it somewhere outside the repository.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by jdwilkin4** [comment]
What is going to happen to all of the links associated with the RWD cert?
Will they just be re routed back to the fcc learn page?
