### ISSUE TITLE
Update strict tests for Todo App - Step 5

### ISSUE THREAD

**Issue by pmpkata** [freeCodeCamp/freeCodeCamp#53351]
### Describe the Issue

The code doesn't pass if you open the curly braces.

### Affected Page

https://forum.freecodecamp.org/t/learn-localstorage-by-building-a-todo-app-step-5/666974

### Your code

```
const taskData = [];
let currentTask = {

};


```

### Expected behavior

I expected to pass, I was assuming code would be put into this object at a later time.

this is the expected solution:

```
const taskData = [];
let currentTask = {};
```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
# Note to interested contributors 

The tests can be rewritten to better use the existing assert methods from chai.
https://www.chaijs.com/api/assert/

Something like this should work. Please test everything on your end too, but this should cut down on the amount of regex tests used and better utilize the other assert methods

# --hints--

You should have a `const` variable called `taskData`.

```js
assert.match(code, /const\s+taskData\s*=/);
```

You should assign an array to your `taskData` constant.

```js
assert.isArray(taskData);
```

Your `taskData` array should be empty.

```js
assert.isEmpty(taskData);
``` 

You should use `let` to create a `currentTask` variable.

```js
assert.match(code, /let\s+currentTask/);
```

You should assign an object to your `currentTask` variable.

```js
assert.isObject(currentTask);
```

Your `currentTask` object should be empty.

```js
assert.isEmpty(currentTask);
```
