### ISSUE TITLE
Learn advanced array methods by building a statistics calculator, step 35. Update example in the instructions

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [freeCodeCamp/freeCodeCamp#53358]
### Describe the Issue

Intsruction says:

Here's an example that gets the smallest number from an array:
`Math.min(1, 9, 11, -3, 0.5);`

The given example, however, has nothing to do with an array; it is an example with the numbers given as input parameters.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-35

### Your code

```



```

### Expected behavior

Two options, I guess either will do:

1. Rephrase this part `Here's an example that gets the smallest number from an array`.
2. Change the example itself, by including actual array.
  ```js
  const array1 = [2, 3, 1];

console.log(Math.min(...array1));
// Expected output: 1
  ```

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome

**Comment by jdwilkin4** [comment]
Let's go with the updating the example and rename the example array here too

```js
const numbersArr = [2, 3, 1];

console.log(Math.min(...numbersArr));
// Expected output: 1
```
