### ISSUE TITLE
do not have test case for steamroller([[["a"]], [["b"]]])

### ISSUE THREAD

**Issue by maple10001** [FreeCodeCamp/FreeCodeCamp#5336]
Challenge [Bonfire: Steamroller](http://www.freecodecamp.com/challenges/bonfire-steamroller#?solution=function%20steamroller(arr)%20%7B%0A%20%20%2F%2F%20I'm%20a%20steamroller%2C%20baby%0A%20%20console.log(arr)%3B%0A%20%20var%20res%20%3D%20%5B%5D%3B%0A%20%20flatten(arr)%3B%0A%20%20%0A%20%20function%20flatten(arr)%20%7B%0A%20%20%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20if(!Array.isArray(arr%5Bi%5D))%20%7B%0A%20%20%20%20%20%20%20%20res.push(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20flatten(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20console.log(arr%2B'%20%2B%2B%2B%2B%20'%2Bres)%3B%0A%20%0A%20%20return%20res%3B%0A%20%20%0A%7D%0Asteamroller(%5B1%2C%20%5B2%5D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function steamroller(arr) {
  // I'm a steamroller, baby
  console.log(arr);
  var res = [];
  flatten(arr);
  
  function flatten(arr) {
    for(var i = 0; i < arr.length; i++) {
      if(!Array.isArray(arr[i])) {
        res.push(arr[i]);
      }
      flatten(arr[i]);
    }
  }
  
  console.log(arr+' ++++ '+res);
 
  return res;
  
}
steamroller([1, [2], [3, [[4]]]]);

```

**Comment by ltegman** [comment]
This is not a site issue. Your solution causes a `Maximum call stack size exceeded` error when run with that test case. (Basically the recursive version of an infinite loop). Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Helphttps://gitter.im/FreeCodeCamp/Help) for help with challenges.

Thanks and happy coding!

**Comment by PawelProchnicki** [comment]
In your code lacks "else" tag.
