### ISSUE TITLE
Easy first pull request: add additional compliments for /learn UI

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#53365]
### Describe the Issue

We occasionally update our user interface to include new compliments to learners, which they see when they complete a coding challenge.

Here are some new pop-culture (video games / anime) reference compliments that we'd like to add to our existing roster of 100 or so messages.

Your mission: to find the right file to add these, and to add them to the right place without breaking the JSON formatting:

```
    "King of the Pirates!",
    "Thunder Breathing First Form!",
    "It's time to duel!",
    "You better believe it!",
    "Do a barrel roll!",
    "You can do this all day!",
    "It's super effective!",
```

I'll give you a hint for how you can find this file: one of the compliments is: "Everything's coming up Milhouse!"

Be sure to only modify the English JSON file. Open a pull request, we'll review it, and you can get your first accepted pull request.

### Affected Page

freecodecamp.org/learn

### Steps to Reproduce

Search the GitHub repo to find the correct file to modify. See description for a hint.

### Expected behavior

Compliments should be added to JSON file

### System

Any

**Comment by SejuSpeaks** [comment]
i submitted a pull request. sorry if anything is wrong this is my first ever, I read the articles and ran around for a while looking to push it.

**Comment by jdwilkin4** [comment]
Hi @SejuSpeaks ! 

I am reviewing your PR now 👍 

> sorry if anything is wrong this is my first ever

No need to be sorry.
It is all part of the learning process 👍

**Comment by ashutoshsabale** [comment]
This is my first PR, kindly review it. If there any additional suggestions or instructions kindly share  with us, I'm ready to make necessary adjustments.
