### ISSUE TITLE
Javascript Beta Certification

### ISSUE THREAD

**Issue by MayankTripathi033** [freeCodeCamp/freeCodeCamp#53371]
### Describe the Issue

Can anyone please help me rectify this problem, I am getting this problem after clicking on javascript beta certification.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/

### Steps to Reproduce

Step 1: Launch the freeCodeCamp on localHost.
Step 2: click on the options javascript javascript-algorithms-and-data-structures-v8.

### Recommended fix or suggestions

Maybe the problem is in the database.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/97526176/8e6bf030-3b44-4065-80ec-184fe3f15f6d)

**Comment by ilenia-magoni** [comment]
please make sure you have the latest version of the code, use `pnpm run clean-and-develop` and clean the browser cache and local storage for localhost. If you need more help please reach out at discord or forum, which asre a more adequate environment for back and forth discussion

**Comment by jdwilkin4** [comment]
I am going to go ahead and close this, but if you need more assistance please reach out on the discord or forum as mentioned earlier 👍
