### ISSUE TITLE
Stray Code in Cash Register Boilerplate 

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#53374]
### Describe the Issue

Stray code is populated in the boilerplate for the Cash Register project 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register

### Your code

```
let price = 1.87;
let cid = [
  ["PENNY", 1.01],
  ["NICKEL", 2.05],
  ["DIME", 3.1],
  ["QUARTER", 4.25],
  ["ONE", 90],
  ["FIVE", 55],
  ["TEN", 20],
  ["TWENTY", 60],
  ["ONE HUNDRED", 100]
];
```

### Expected behavior

User should have blank project to start

### System

All

**Comment by jdwilkin4** [comment]
I believe this was actually intentional as to show campers the correct data structure for the cid array. 

@scissorsneedfoodtoo thoughts?

**Comment by jeremylt** [comment]
Hmm, its in there without an explanatory comment and has confused at least one user.

**Comment by jdwilkin4** [comment]
It looks like the boilerplate code is possibly referenced here

> If you'd like to test your application with different values for price and cid, make sure to declare them with the let keyword so they can be reassigned by our tests.

but being more explicit would be better.

we could rework this section here 

> There are a few variables you'll need to use in your code:

>price: the price of the item as a floating point number.
>cash: the amount of cash provided by the customer for the item, which is provided via an input element on the page.
>cid: cash-in-drawer, a 2D array listing available currency in the cash drawer.

## proposed new version

```md
In the `script.js` file, you have been provided with the `price` and `cid` variables. The `price` variable is the price of the item, and the `cid` variable is the cash-in-drawer, which is a 2D array listing the available currency in the cash drawer.

The other variable you will need add is the `cash` variable, which is the amount of cash provided by the customer for the item, which is provided via an `input` element on the page.
```

**Comment by mayankkamboj47** [comment]
@jdwilkin4 I think the proposed version looks good.
