### ISSUE TITLE
Update description and hint text for step 15 of date formatter project

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#53386]
### Describe the Issue

The particular instruction for what to do in step 15 goes this way:

>Chain the addEventListener method to dateOptionsSelectElement where the first argument is change and the second argument is an empty arrow function.

This could be a bit hard to understand, as the sentence is too long and has no fullstop or comma.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-15

### Your code

N/A

### Expected behavior

The description can go like this:
> Chain the addEventListener method to dateOptionsSelectElement. Set the first argument of the addEventListener to `change`, and the second argument to an empty arrow function.

Or something better.

### Screenshots

![Screenshot 2024-01-27 at 12 45 59 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/426c33c4-a479-404f-af0d-ab9ee09e31b6)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
We should mention to pass in the string change.
Also, it looks like there is a missing test to make sure they have attached the event listener to the variable.

# Note to contributors 
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-the-date-object-by-building-a-date-formatter/65388bbcbf6928b83fc424d1.md

## Changes that need to be made 

### Updates to the description

Attach the `addEventListener` method to the `dateOptionsSelectElement`. The first argument of the event listener should be the string `change` and the second argument should be an empty arrow function.

### Updates to the tests

The first test should check that the camper added the event listener to the select element 

````md
# --hints--

You should attach the `addEventListener` method to the `dateOptionsSelectElement`.

```js
assert(code.match(/dateOptionsSelectElement\.addEventListener\s*\(/g));
```
````

Then the second test should be the one to check for the change event 

````md
Your event listener should listen for a `change` event.

```js
assert(code.match(/dateOptionsSelectElement\.addEventListener\s*\(\s*('|")change\1/g));
```
````
then the third one is fine
Happy coding
