### ISSUE TITLE
Editor scroll bar arrow is displayed in front of menu dropdown

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#53385]
### Describe the Issue
The arrow icon of the editor scroll bar is displayed in front of menu dropdown.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25644062/80160f1c-4806-4799-aee5-6a5ca95b2d73)

### Affected Page

Any challenge where the custom scroll bar appears on the right

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
2. Close preview pane
3. Open menu

It is more visible when you set the editor scrollbar width to be wider in your settings.

### Expected behavior

The arrow icon should be hidden by the Menu dropdown

### Screenshots

See above

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 120.0.6099.225 (Official Build) (64-bit)

**Comment by ashutoshsabale** [comment]
This is because z-index of scroll-bar button and and arrow background is more than the nav-bar panel opening from menu button.
