### ISSUE TITLE
My code returns Short And Stout  but it won't mark it with a check.  It passes on all the other sentences fine. I double checked it in jfiddle and it was fine.

### ISSUE THREAD

**Issue by sarabethz** [FreeCodeCamp/FreeCodeCamp#5339]
Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence#?solution=var%20wordsArray%20%3D%5B%5D%3B%0Avar%20lettersArray%20%3D%20%5B%5D%3B%0Avar%20upCaseWord%3D%20%5B%5D%3B%0Avar%20newString%3B%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20wordsArray%3D%20str.toLowerCase().split('%20')%3B%0A%20%20for%20(var%20i%3D0%3B%20i%3CwordsArray.length%3B%20i%2B%2B)%7B%0A%09lettersArray%5Bi%5D%3DwordsArray%5Bi%5D.charAt(0).toUpperCase()%3B%0A%20%20%7D%0A%20%20for(var%20x%3D0%3B%20x%3CwordsArray.length%3B%20x%2B%2B)%7B%0A%09%20%20upCaseWord%5Bx%5D%3DlettersArray%5Bx%5D%3B%0A%09%09%0A%20%20%20%20for%20(var%20y%20%3D0%3B%20y%3CwordsArray%5Bx%5D.length-1%3By%2B%2B)%7B%0A%20%09%09upCaseWord%5Bx%5D%3D%20upCaseWord%5Bx%5D%2BwordsArray%5Bx%5D.charAt(y%2B1)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%20%20newString%3DupCaseWord.join('%20')%3B%0A%20%20%20%20return%20newString%3B%0A%0A%7D%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var wordsArray =[];
var lettersArray = [];
var upCaseWord= [];
var newString;
function titleCase(str) {
  var wordsArray= str.toLowerCase().split(' ');
  for (var i=0; i<wordsArray.length; i++){
	lettersArray[i]=wordsArray[i].charAt(0).toUpperCase();
  }
  for(var x=0; x<wordsArray.length; x++){
	  upCaseWord[x]=lettersArray[x];
		
    for (var y =0; y<wordsArray[x].length-1;y++){
 		upCaseWord[x]= upCaseWord[x]+wordsArray[x].charAt(y+1);
    }
  }
    newString=upCaseWord.join(' ');
    return newString;

}
titleCase("sHoRt AnD sToUt");

```

**Comment by sludge256** [comment]
It's because the scope of your variables are global.
Look at this to see what your output would be if you made multiple function calls as opposed to each function call getting a "clean" version of the code.

https://jsbin.com/gasudubeja/edit?js,console

**Comment by BerkeleyTrue** [comment]
@sludge256 Thank you.

@sarabethz Please use the help room before when you get stuck.

Happy Coding!

**Comment by sarabethz** [comment]
Thanks!..I will use the help room next time. :)
