### ISSUE TITLE
New JavaScript Projects tests can fail if code depends on change event of input field

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#53390]
**Describe the bug**
A bit of mouthful. Most of the tests in new projects are directly setting the `value` of input field. This can create unexpected troubles if camper's code depend on the `onchange` of the said input field.

For example camper added `onchange` to the input field (`inputField`). Function was updating global `value`, which was later used by the function when the action button was clicked. Because `inputField.value = 'something'` is not triggering `onchange` on the `inputField`, the `value` was empty, and results failed.

While _all_ worked well when checked by hand.

There's couple options:
- Add to tests action, performed after value is changed, that will trigger _possible_ `onchange` on the input field. For example `inputField.dispatchEvent(new Keyboard('keyup', {key: 'ArrowRight'}))` should work.
- Add specific note to projects to not depend on events of input field.
- Keep it as it is.

**Additional context**
https://forum.freecodecamp.org/t/problem-with-palindrome-checker/667410

**Comment by jdwilkin4** [comment]
> Add to tests action, performed after value is changed, that will trigger possible onchange on the input field. For example inputField.dispatchEvent(new Keyboard('keyup', {key: 'ArrowRight'})) should work.

I am kinda of leaning towards this option.

Let's see what the others think

**Comment by naomi-lgbt** [comment]
Yes, I agree - let's go that route.

**Comment by Deep512** [comment]
Hi @gikf, When you say
> Add to tests action, performed after value is changed, that will trigger possible onchange on the input field. For example inputField.dispatchEvent(new Keyboard('keyup', {key: 'ArrowRight'})) should work.

You mean add to all the places where the coding test expects an input and then some action(a button is clicked, or user presses enter) is performed which results in an output? Or just the palindrome checker?

**Comment by gikf** [comment]
Hey @Deep512,

all the certification projects from _JavaScript Algorithms and Data Structures (Beta)_:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-palindrome-checker-project/build-a-palindrome-checker.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-pokemon-search-app-project/build-a-pokemon-search-app.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-roman-numeral-converter-project/build-a-roman-numeral-converter.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-telephone-number-validator-project/build-a-telephone-number-validator.md

**Comment by Deep512** [comment]
One last question @gikf 
When we make changes here, do I make them in the English category only
Or across all languages?

**Comment by gikf** [comment]
@Deep512, English only, other languages will be later updated using translation workflow.

**Comment by Deep512** [comment]
@gikf @jdwilkin4 @naomi-lgbt  Have raised a PR for this issue, please review

**Comment by Nthaz** [comment]
I'm new to this and would be waiting to see what others say and learn along the way
