### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue 

### ISSUE THREAD

**Issue by ajboilanger** [FreeCodeCamp/freecodecamp#534]
Seemed to pass after putting the beginning paragraph tag. Doesn't look like it checked for the closing tag.

**Comment by terakilobyte** [comment]
This is a known issue across all waypoints. Not providing a closing tag is actually valid html is a lot of situations! http://www.w3.org/TR/html5/syntax.html#optional-tags

**Comment by terakilobyte** [comment]
This is not to say we don't want to enforce good style (including those optional closing tags). We're continuing to look into how to do this without pattern matching.
