### ISSUE TITLE
Update description for step 5 of calorie counter project

### ISSUE THREAD

**Issue by JoyShaheb** [freeCodeCamp/freeCodeCamp#53409]
### Describe the Issue

Instructions unclear on adding the word "Lunch" on the legend tag. instructions are give to add "lunch" on `id` but its unclear for the `Lunch` inside the `legend` tag.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/e5510c3c-ca37-4383-946d-5d8979cd0132)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-5

### Your code

```
<fieldset id="lunch">
  <legend>Lunch</legend>
  <div class="input-container"></div>
</fieldset>
```

### Expected behavior

should have clear instructions on adding "Lunch" on the `legend` tag

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/e5510c3c-ca37-4383-946d-5d8979cd0132)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Njong392** [comment]
This is a great observation! I think we would also need to specify in the instruction that the `div` element should have a class of `input-container` because that only comes in the hint too.

**Comment by jdwilkin4** [comment]
We can just reuse the text from the previous step.

## updated description for step 5

```md
Next, create a `fieldset` element with the `id` set to `lunch`.

Within that element, create a `legend` element with the text `Lunch`, and an empty `div` with the `class` set to `input-container`.
```

## Note to first timers

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63b60821c855d01b1eda3c0b.md

Happy coding

**Comment by Mishra-Pravin** [comment]
@JoyShaheb @jdwilkin4 @Njong392 I have created a pull request that addresses this issue. Here is the link: https://github.com/freeCodeCamp/freeCodeCamp/compare/main...Mishra-Pravin:freeCodeCamp:patch-1
