### ISSUE TITLE
SyntaxError: Illegal Break Statement

### ISSUE THREAD

**Issue by timbec** [FreeCodeCamp/FreeCodeCamp#5341]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%0A%20%20%2F%2Fhave%20to%20remove%20all%20non-alphanumeric%20characters%20-%20punctuation%2C%20spaces%2C%20symbols.%20Assume%20you%20have%20to%20use%20regular%20expressions%20for%20this.%20%0A%20%20var%20stripWord%20%3D%20str.replace(%2F%5CW%7C%5Cs%7C_%2Fg%2C'')%3B%0A%20%20%0A%20%20%2F%2Fset%20all%20words%20to%20lowercase%0A%20%20var%20palinWord%20%3D%20stripWord.toLowerCase()%3B%20%0A%20%20console.log(palinWord)%3B%20%0A%20%20%0A%20%20%20%20%2F*%20reverse%20palinWord%20for%20comparison*%2F%0A%20%20var%20checkPalindrome%20%3D%20palinWord.split('').reverse().join('')%3B%0A%20%20console.log(checkPalindrome)%3B%20%0A%20%20%0A%20%20%20%2F*%20Check%20to%20see%20if%20str%20is%20a%20Palindrome*%2F%0A%20%20%20if%20(palinWord%20%3D%3D%3D%20checkPalindrome)%20%7B%0A%20%20%20%20%20return%20true%3B%0A%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20return%20false%3B%20%0A%20%20%20%7D%0A%0A%20%0A%7D%0A%0A%0A%0Apalindrome(%22A%20man%2C%20a%20plan%2C%20a%20canal.%20Panama%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![screenshot 2015-12-17 16 37 19](https://cloud.githubusercontent.com/assets/1399745/11882794/9f9a141c-a4dc-11e5-94f9-ad11f4fae886.png)

My code:
```javascript
function palindrome(str) {
  
  //have to remove all non-alphanumeric characters - punctuation, spaces, symbols. Assume you have to use regular expressions for this. 
  var stripWord = str.replace(/\W|\s|_/g,'');
  
  //set all words to lowercase
  var palinWord = stripWord.toLowerCase(); 
  console.log(palinWord); 
  
    /* reverse palinWord for comparison*/
  var checkPalindrome = palinWord.split('').reverse().join('');
  console.log(checkPalindrome); 
  
   /* Check to see if str is a Palindrome*/
   if (palinWord === checkPalindrome) {
     return true;
   } else {
     return false; 
   }

 
}



palindrome("A man, a plan, a canal. Panama");
```

I keep getting SyntaxError: Illegal Break Statement. There is no 'break' statemet and the above code runs without error in the console and passes all the examples. After going through and taking everything out one by one then replacing them, I found the statement only appears at the following statement: 

    /* reverse palinWord for comparison*/
  var checkPalindrome = palinWord.split('').reverse().join('');
  console.log(checkPalindrome); 

Thanks, 

Tim

**Comment by ltegman** [comment]
Well, that's interesting. Something about this is triggering loopProtect to run even though there is no loop. If you run your code with a commend of `//noprotect` at the top it will run fine.

Now that we've vendored loopProtect we should probably look into this. Here's what the code looks like once it gets hit by loopProtect:

```js
function palindrome(str) {
  
  //have to remove all non-alphanumeric characters - punctuation, spaces, symbols. Assume you have to use regular expressions for this. 
  var stripWord = str.replace(/W|s|_/g,'');
  
  //set all words to lowercase
  var palinWord = stripWord.toLowerCase(); 
  console.log(palinWord); 
  
    /* reverse palinWord ;loopProtect.protect({ line: 10, reset: true }); for comparison*/{
if (loopProtect.protect({ line: 10 })) break;

  var checkPalindrome = palinWord.split('').reverse().join('');
}

  console.log(checkPalindrome); 
  
   /* Check to see if str is a Palindrome*/
   if (palinWord === checkPalindrome) {
     return true;
   } else {
     return false; 
   }

}

palindrome("A man, a plan, a canal. Panama");
```

**Comment by SaintPeter** [comment]
It looks to me like the regex is triggering on the word `for`.  I'm thinking we either need to improve the regex (to look for a `for\s*\(`) or somehow have it ignore comments.  I suspect the former is much easier.

**Comment by timbec** [comment]
HI Logan, 

   I added //noprotect and it did indeed pass. I didn't think to remove comments and try with that (being a total beginner with regex). But thanks, both for the answer and the impressively quick response. 

  Best, 

   Tim

**Comment by BerkeleyTrue** [comment]
Loop protect definitely isn't perfect. The only way to make it perfect is to make it actually parse JS, which would involve a lot of work for a couple of edge cases. 

Loop protect was definitely a stepping stone for us on the way to actually using an AST parser and analyzing the AST for infinite loops.

We can definitely make improvements to the regex's to keep us going in the mean time.

**Comment by CaroleAnneHannon** [comment]
It's because the 2nd comment has the word "for" in it.
