### ISSUE TITLE
Animation not loading in Depth-First-Search challenge

### ISSUE THREAD

**Issue by nastaran-motiee** [freeCodeCamp/freeCodeCamp#53414]
### Describe the Issue

The animation content which is referred as part of the [Depth-First-Search](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/depth-first-search) challenge explanation is not loading.

### Affected Page

https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/depth-first-search

### Expected behavior

Loading animation

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/33676320/33fc04a4-2333-4320-8b51-1c9a71e11bb9)

### System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [Chrome, Microsoft Edge]

**Comment by ilenia-magoni** [comment]
It seems it was hosted on github and now it's not present anymore.
Challenge file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/data-structures/depth-first-search.md

If we can find the image, it should probably be added to our [cdn](https://github.com/freeCodeCamp/cdn)

**Comment by gikf** [comment]
The same case is with https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/breadth-first-search

**Comment by ilenia-magoni** [comment]
Where did the images come from?

**Comment by moT01** [comment]
I found the two images we used on the wayback machine ([depth-first](https://web.archive.org/web/20200918054712/https://camo.githubusercontent.com/aaad9e39961daf34d967c616edeb50abf3bf1235/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f372f37662f44657074682d46697273742d5365617263682e676966), [breadth-first](https://web.archive.org/web/20201023042753/https://camo.githubusercontent.com/2f57e6239884a1a03402912f13c49555dec76d06/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f342f34362f416e696d617465645f4246532e676966)) - it looks like they are the same as on wikipedia ([depth-first](https://en.wikipedia.org/wiki/Depth-first_search), [breadth-first](https://en.wikipedia.org/wiki/Breadth-first_search)) - so probably taken from there. Not sure if we are supposed to use those without providing attribution.

**Comment by ilenia-magoni** [comment]
We need to provide attribution as wikipedia uses license [CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0), now the question is where... the cdn from where we would serve the images or the challenge page or something else entirely?

**Comment by moT01** [comment]
Wonder if we should just make our own images. They're pretty simple.

**Comment by royjohnlee** [comment]
oh I came from https://github.com/freeCodeCamp/freeCodeCamp/issues/55183 .

Would like to help drive this so i can learn more about CDNs

**Comment by ilenia-magoni** [comment]
the block is creating the images here @royjohnlee

**Comment by moT01** [comment]
Adding a help wanted label here. We want someone to create new images similar to the ones linked and added to our CDN. Then we can update the challenges to use those.
