### ISSUE TITLE
Update if statement explanation for RPG game step 76

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53429]
### Describe the Issue

Right now, we have two steps dedicated to teaching an `if` statement.
The first step has campers move all of the function code inside an if statement with the string `condition` for the condition.
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-76
Then the next step, has them change the string `condition` to the condition `gold >=10`.
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-77

I think this can be simplified and combined into just one step.
Also, I think this will give us a better chance to explain what an if statement is and how the condition works. 

## proposed new directions

````md
# --description--

What if the player doesn't have enough gold to buy health? When you want to run code conditionally, you can use the <dfn>if</dfn> statement.

An `if` statement is used to make decisions in code. The keyword `if` is followed by a condition in parentheses. If the condition is true, the code inside the curly braces `{}` is executed. If the condition is false, the code inside the curly braces is skipped.

Here is an example of an `if` statement:

```js
const num = 5;
if (num >= 3) {
  console.log("This code will run because num is greater than or equal to 3.");
}
```

Start by placing all of the code in your `buyHealth` function inside an `if` statement. For the `if` statement condition,  check if `gold` is greater than or equal to `10`.
````
thoughts?

### Affected Page

multiple urls

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Nitz2611** [comment]
Hi, @jdwilkin4 I want to know that, do i have to delete step 78 or just removing the description of step 78 can fix this?

**Comment by jdwilkin4** [comment]
@Nitz2611 

This issue hasn't been triaged yet.

Only issues marked with help wanted or first timers only will be available for contribution. Please do not start working on this yet because we don't know if we will move forward with this change. 

If we do decide to move forward with this change, then steps 77 & 78 will become just one which means removing step 78

**Comment by jdwilkin4** [comment]
Update: The live site was just updated with the latest changes in main.

So I updated the step numbers that this issue is referring to

**Comment by jdwilkin4** [comment]
I am going to go ahead and open this up for contribution since I think this change will make it more clear how if statements work
