### ISSUE TITLE
Update step 65 instructions to make it clear on correct syntax

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53427]
### Describe the Issue

There is a lot of confusion on the correct syntax for step 65
https://forum.freecodecamp.org/search?q=step%2065%20%23javascript%20Role%20Playing%20Game

A lot of campers are struglling to get to here 

```js
location["button text"][0]
```
instead, we have these types of answers

```js
location["button text"[0]]
location["button text[0]"]
```

We should simplify the directions and show the syntax.

## updated directions 

```md
# --description--

`location["button text"]` is an array with three elements. Change the `button1.innerText` assignment to be `location["button text"][0]` which represents the first element of the array.
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-65

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8b9770050d217d2247801.md

Happy coding

**Comment by Macky151203** [comment]
can i work on this issue
