### ISSUE TITLE
Update directions for onclick in RPG game

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53425]
### Describe the Issue

We still have a lot of confusion on the forum about step 41

https://forum.freecodecamp.org/search?q=step%2041%20%23javascript%20Role%20Playing%20Game

I think adding a code example of what they need to do will help.

Here is my proposed update to the step.

## updated description
````md
# --description--

`button1` represents your first `button` element. These elements have a special property called `onclick`, which you can use to determine what happens when someone clicks that button.

You can access properties in JavaScript a couple of different ways. The first is with <dfn>dot notation</dfn>. Here is an example of using dot notation to set the `onclick` property of a button to a function reference.

```js
button.onclick = myFunction;
```

In this example, `button` is the button element, and `myFunction` is a reference to a function. When the button is clicked, `myFunction` will be called.

Use dot notation to set the `onclick` property of your `button1` to the function reference of `goStore`. Note that `button1` is already declared, so you don't need to use `let` or `const`.
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-41

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Just a note - that will be step 40 currently https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c2fccf186146b59c6e96.md
