### ISSUE TITLE
Labs page button isn't centered

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5343]
[Labs](freecodecamp.com/labs)
![](https://www.evernote.com/l/AqSCRnDct_xKXosF3TkQjicd4JKX8cHP9b4B/image.png)

**Comment by mhelmetag** [comment]
File to be modified is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/0096c2c953d0b747f0ac1c29333579c28044b321/server/views/resources/labs.jade).

I'll take a crack at it after work.

**Comment by mhelmetag** [comment]
Aww... I was going to do that...

**Comment by raisedadead** [comment]
Oh I am so sorry @mhelmetag. Do you still want to? I haven't done the Pull request yet!
