### ISSUE TITLE
Bonfire: Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by munozu** [FreeCodeCamp/FreeCodeCamp#5344]
I've managed to write some incorrect code that freezes the browser, whoops! 
I am unable to reset or delete the code due to the browser freezing upon each visit. 
As I navigate to the bonfire page my solution is included in the URL, perhaps it is loading and running the code and crashing before I can fix code. Hmmm....

here is a screenshot

![image](https://cloud.githubusercontent.com/assets/13267580/11886394/d0f8f96e-a57d-11e5-90e2-602b84aaafe4.png)

**Comment by ltegman** [comment]
You can either [Disable Code Autorun](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) or [Delete the Solution From Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage)

Thanks and happy coding!
