### ISSUE TITLE
Change infinite loop detected message

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#5345]
When a user tries their code with a long running loop message only warns them of an infinite loop detection. 

We should change this message so that it lets them know how to disable it if needed. This will hopefully reduce the number of issues we get when there is a valid long running loop.

The message can be changed here:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework/add-loop-protect.js#L8

**Comment by shubhekshajalan** [comment]
Hey, I'd like to work on this. How can the message be altered to accommodate the changes you propose?

**Comment by SaintPeter** [comment]
@shubhekshajalan If you can't figure out how to make the change, you're not qualified to make the change.  The file is linked above.  Feel free to give it a go, but the whole point of "help wanted" is that you make and test the change yourself.

**Comment by BerkeleyTrue** [comment]
@SaintPeter I think @shubhekshajalan is asking what the message should look like, not how to change the message.

**Comment by geoff616** [comment]
Just submitted a PR for this: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5378

**Comment by kentcdodds** [comment]
@SaintPeter, that kind of comment has no place in open source, and certainly no place on a FreeCodeCamp repo (I'm sure @QuincyLarson would agree). It's been several months since your comment. I hope this behavior is behind you. I'm sure it's against the FreeCodeCamp code of conduct. Please keep the open source and FreeCodeCamp community friendly and welcoming to newcomers.

**Comment by QuincyLarson** [comment]
@kentcdodds Thanks for bringing this to my attention. This is the first time I'd seen this issue.

@shubheksha Sorry about @SaintPeter's discouraging comment. I think he misunderstood you. Either way, he shouldn't have responded so briskly and unconstructively. 

@shubheksha If you're still open to contributing to our open source project, we would welcome your contributions, and I'll do everything I can to remove any obstacles or ambiguities you encounter.
