### ISSUE TITLE
Add border-radius to the elements in the free code camp header

### ISSUE THREAD

**Issue by PedroRamos360** [freeCodeCamp/freeCodeCamp#53452]
### Describe the Issue

I was looking at the home page and realized there is no border-radius in the search bar or buttons. I believe it would look way better with a litte of border-radius and way more professional. In the screenshots session there is a comparison of the header using components with border-radius vs without it.

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Open the freeCodeCamp home page https://www.freecodecamp.org/

### Expected behavior

To solve this issue it is expected that the developer adds the style border-radius with 5px in each of the elements presented in the image.

## With 5px border-radius
![Screenshot from 2024-01-30 11-07-40](https://github.com/freeCodeCamp/freeCodeCamp/assets/53490820/361fa15a-4461-403c-98e0-55867f35b4d2)
## Without
![Screenshot from 2024-01-30 11-07-49](https://github.com/freeCodeCamp/freeCodeCamp/assets/53490820/01575887-8f45-40ac-8b1b-865cdfb3da74)

### System

- Device: [Laptop]
- OS: [Ubuntu 20.04]
- Browser: [Microsoft Edge]
- Version: [119]

**Comment by gikf** [comment]
Could you provide more reasoning for this suggestion? This makes header not consistent with the rest of the page where border radius is not used.

**Comment by PedroRamos360** [comment]
@gikf Most modern web pages use rounded corners in buttons, it is a good way to show that they are interactive elements in the page, makes the interface look more professional and it looks more like there was put effort to make the webpage look better (since the default elements are usually sharp corners).
I did not realize the inconsistency it would lead with the rest of the interface, still, I believe that it would be a good update and maybe it would be possible to change the rest of the elements too.
It's just a suggestion that I would implement if the website were mine.

**Comment by ahmaxed** [comment]
Thank you @PedroRamos360.  The sharp edges are part of the effort to adapt IDE look and feel when went for a redesign in 2019. After bootstrap is removed from the codebase in favor of our own component library, we will go back to the drawing board and redesign the website. 
https://github.com/freeCodeCamp/freeCodeCamp/issues/52030

I am closing this issue and the related pr accordingly for now, but we will revisit your suggestions for the redesign.
