### ISSUE TITLE
Challenge Editor Error: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by weilirs** [freeCodeCamp/freeCodeCamp#53457]
### Describe the Issue

When opening the Challenge Editor I saw this "Unexpected token '<', "<!doctype "... is not valid JSON" error.

### Affected Page

Challenge Editor

### Steps to Reproduce

1. run `pnpm run challenge-editor`
2. Go to http://localhost:3300
3. See error

### Expected behavior

There should be no errors.

### Screenshots

<img width="538" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/62249815/67f2306b-34f3-4d6e-b563-7e055e97fb48">

### System

- Device: Macbook M1
- OS: MacOS 13.4.1 (22F82)
- Browser: Chrome

**Comment by gikf** [comment]
I've checked latest code on gitpod and haven't encountered any issues.

Make sure you have `.env` file up to date for challenge editor, there was variable name change lately.

**Comment by weilirs** [comment]
> I've checked latest code on gitpod and haven't encountered any issues.
> 
> Make sure you have `.env` file up to date for challenge editor, there was variable name change lately.

Hmmm... I merged the latest changes but still having it.

**Comment by gikf** [comment]
Check if the challenge editor's client `.env` matches `sample.env`.

**Comment by weilirs** [comment]
Oh, this is the reason. thanks!
