### ISSUE TITLE
Error in instructions in step-76 in Music Player

### ISSUE THREAD

**Issue by Valeriavb7** [freeCodeCamp/freeCodeCamp#53465]
### Describe the Issue

There shouldn't be optional chaining when assignin.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-76

### Your code

```
if (userData?.currentSong?.id === id) {
    userData.currentSong = null;
    userData.songCurrentTime = 0;
    pauseSong();
    setPlayerDisplay();
  }
```

### Expected behavior

The instruction should be : If there is a match then set userData.currentSong to null and userData.songCurrentTime to 0.

### System

- Device: [ Laptop]
- OS: [ Windows 10]
- Browser: [Chrome]
- Version: [22]

**Comment by jdwilkin4** [comment]
It looks like the seed code for the remaining steps(step 77 - end) is correct.
So only the directions for step 76 will need to be updated to reflect that.
