### ISSUE TITLE
Bonfire completed before even starting it

### ISSUE THREAD

**Issue by ChristianLapinig** [FreeCodeCamp/FreeCodeCamp#5346]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy#?solution=function%20destroyer(arr%2Ca%2Cb%2Cc)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20var%20base%20%3D%20arr.filter(function(x)%7B%0A%20%20%20%20return%20x%20!%3D%3D%20a%20%26%26%20x%20!%3D%3D%20b%20%26%26%20x%20!%3D%3D%20c%3B%0A%20%20%7D)%3B%0A%20%20return%20base%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr,a,b,c) {
  // Remove all the values
  var base = arr.filter(function(x){
    return x !== a && x !== b && x !== c;
  });
  return base;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
I finished the `Falsy Bouncer` Bonfire and when I came to this challenge, it seemed like it was already completed. I ran it to see if it would throw an error and the code worked. Prior to this I have never worked on this Bonfire

**Comment by SaintPeter** [comment]
That is very odd.

Two things:

1. Can you confirm you're logged in as you?
   * Are you logged in from a personal or public computer?

2. Try resetting the code to see if the reset code passes.

**Comment by ChristianLapinig** [comment]
I am logged in as myself using my GitHub account

Here is the Bonfire when I got to it
![screen shot 2015-12-17 at 11 49 15 pm 2](https://cloud.githubusercontent.com/assets/11323135/11892000/dec11136-a518-11e5-9a18-77b847d2cb5c.png)

Here it is when I hit the reset button
![screen shot 2015-12-17 at 11 49 27 pm 2](https://cloud.githubusercontent.com/assets/11323135/11892015/fe0ac5c8-a518-11e5-8e2f-88fbfcf2aa9d.png)

**Comment by bugron** [comment]
@ChristianLapinig is this still an issue for you?

**Comment by bugron** [comment]
Closing this issue as stale. @ChristianLapinig feel free to reopen if you still experience problems, thanks.
