### ISSUE TITLE
Learn Lambda functions by building an expense tracker step 16 instructions unclear 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#53463]
### Describe the Issue

A lot of assumptions have to be made in order to understand step sixteen of this project. While lambda expressions were introduced back in step eleven, they might not have been fully explained. It barely explained the basic syntax , and wasn't extremely clear on the parameter's purpose. Secondly, this step did not clarify that the lamda expression parameter was indeed a dictionary. 

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/step-16 

### Your code

```
def total_expenses(expenses):
    lambda expense: expense['amount']
```

This is the solution the challenge wants, as said in the hint text. 

### Expected behavior

Back in step eleven, lamda expressions could be explained a little better. Maybe like explaining that lamda expression variables are just like the parameters passed into normal functions. And as for step sixteen, pointing out that the parameter is meant to be a dictionary could have been helpful instead of it just being implied. 

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 122.0

**Comment by tomitokko** [comment]
This is a fix for this issue @Dario-DC 
https://github.com/freeCodeCamp/freeCodeCamp/pull/53989

**Comment by MiguelAngelEc** [comment]
Gracias.
