### ISSUE TITLE
CSS media query issues on check lists.

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#5347]
Anywhere from 1000px width to when the UI goes into responsive mode the numbers on the check list move into it's respective check box.  Image posted bellow

<img width="1109" alt="screen shot 2015-12-17 at 9 08 15 pm" src="https://cloud.githubusercontent.com/assets/2502947/11887478/a3909926-a502-11e5-9b42-8a92dc2ec569.png">

**Comment by SaintPeter** [comment]
Confirmed, although this is a pretty marginal corner case. There is maybe a 200px wide zone where there is overlap.

**Comment by benschac** [comment]
It happens quite a bit for me.  Regardless I just want a softball for my
first issue :)

On Thu, Dec 17, 2015 at 9:53 PM, Rex Schrader <notifications@github.com>
wrote:

> Confirmed, although this is a pretty marginal corner case. There is maybe
> a 200px wide zone where there is overlap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5347#issuecomment-165655171>
> .
>



-- 
*Benjamin Schachter *• Project Manager
* <http://www.dramafever.com/>*    |   bschachter@dramafever.com

**Comment by sonalkr132** [comment]
This really isn't the issue with new UI (width < 760px). However, now checkboxes are awkwardly too far. 
![screenshot from 2016-01-23 13-09-16](https://cloud.githubusercontent.com/assets/7680662/12529103/b46368fe-c1d2-11e5-8469-7f843271e5c4.png)
