### ISSUE TITLE
Broken Link to "The Hall of Fame List" in the security tab of this repository

### ISSUE THREAD

**Issue by ahujaesh** [freeCodeCamp/freeCodeCamp#53476]
### Describe the Issue

In [this](https://github.com/freeCodeCamp/freeCodeCamp?tab=security-ov-file) file if you go point three of the "Guidelines" section, it states "While we do not offer any bounties or swags at the moment, we'll be happy to list your name in our [Hall of Fame](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/security-hall-of-fame.md) list, provided the reports are not low-effort." The link to this file does not work, and just gives you this error : "404 - page not found".  Note: this is not an error in a coding challenge, but in your security policy.

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp?tab=security-ov-file

### Steps to Reproduce

1. Go to the security policy [here](https://github.com/freeCodeCamp/freeCodeCamp?tab=security-ov-file)
2. Scroll down to point three of the "Guidelines" page
3. Click on the link to the hall of fame

### Expected behavior

I expected to be taken to a .md file with the hall of fame, but instead encountered an error

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/86844958/98ba7bec-a27e-483e-b785-cbe65d804101)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/86844958/c7b56774-a907-4d25-bd18-7a47a18c2137)

### System

- Device: [Chromebook]
- OS: [Chrome OS]
- Browser: [Google Chrome]
- Version: [I don't know]

**Comment by dyx9** [comment]
The original link is relative, it works if you click it from the [docs folder](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/docs/security.md) where all the docs are. However, it does not work if you click on it from the [tab view](https://github.com/freeCodeCamp/freeCodeCamp?tab=security-ov-file) of the main page of the repo, so I have updated the link with an absolute URL, it should work for both.

**Comment by gikf** [comment]
Link works as well from the documentation - https://contribute.freecodecamp.org/#/security
