### ISSUE TITLE
Migrate to Gitpod

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#53470]
## Learn updates
This can be a single PR that does the following:
- Update challenge / project descriptions for a superblock with instructions and links to run the boilerplate on Gitpod
  - Links should use the `https://gitpod.io/?autostart=true#<boilerplate-repo-url>` structure.
  - Notes on how to set up the project on Replit can be removed (the `.replit` window with startup commands etc.).

```[tasklist]
- [x] Back End Development and APIs Certification (https://github.com/freeCodeCamp/freeCodeCamp/pull/53496)
- [x] Quality Assurance (https://github.com/freeCodeCamp/freeCodeCamp/pull/53472)
- [x] Data Analysis with Python (https://github.com/freeCodeCamp/freeCodeCamp/pull/53582)
- [x] Information Security (https://github.com/freeCodeCamp/freeCodeCamp/pull/53515)
- [x] Machine Learning with Python (https://github.com/freeCodeCamp/freeCodeCamp/pull/53584)
```

## Boilerplate updates
**These should not be merged until just after the updates for Learn are live**

Each PR below should:
- Remove config files that were added with Replit in mind (`.gitattributes`, `.gitconfig`, `.prettierignore`, and so on).
- Add a `.gitpod.yml` file that:
  - Uses the `gitpod/workspace-node` image.
  - Makes port `3000` public so Learn tests can access the URL, and sets `onOpen` to `open-preview` to preview window with the client view. **Note:** This shouldn't be necessary for the Python projects.
  - Runs `npm install` on `init` and the `command` `npm run start` for Node projects. For Python projects, the command should just install any necessary packages.
  - Installs the fCC Dark VS Code theme extension.
- Add a `.vscode/settings.json` file that:
  - Enables the fCC Dark VS Code theme

## Back End Development and APIs
- [x] Managing Packages with NPM (https://github.com/freeCodeCamp/boilerplate-npm/pull/667)
- [x] Basic Node and Express (https://github.com/freeCodeCamp/boilerplate-express/pull/155)
- [x] MongoDB and Mongoose (https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/61)
- [x] Timestamp Microservice (https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/103)
- [x] Request Header Parser Microservice (https://github.com/freeCodeCamp/boilerplate-project-headerparser/pull/42)
- [x] URL Shortener Microservice (https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/67)
- [x] Exercise Tracker (https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/83)
- [x] File Metadata Microservice (https://github.com/freeCodeCamp/boilerplate-project-filemetadata/pull/30) 

## Quality Assurance
- [x] Quality Assurance and Testing with Chai (https://github.com/freeCodeCamp/boilerplate-mochachai/pull/117)
- [x] Advanced Node and Express (https://github.com/freeCodeCamp/boilerplate-advancednode/pull/33)
- [x] Metric-Imperial Converter (https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/pull/29)
- [x] Issue Tracker (https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/31)
- [x] Personal Library (https://github.com/freeCodeCamp/boilerplate-project-library/pull/24)
- [x] Sudoku Solver (https://github.com/freeCodeCamp/boilerplate-project-sudoku-solver/pull/31)
- [x] American British Translator (https://github.com/freeCodeCamp/boilerplate-project-american-british-english-translator/pull/33)

## Data Analysis with Python
- [x] Mean-Variance-Standard Deviation Calculator (https://github.com/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator/pull/15)
- [x] Demographic Data Analyzer (https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer/pull/16)
- [x] Medical Data Visualizer (https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/pull/30)
- [x] Page View Time Series Visualizer (https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer/pull/16)
- [x] Sea Level Predictor (https://github.com/freeCodeCamp/boilerplate-sea-level-predictor/pull/15)

## Information Security
- [x] Information Security with HelmetJS (https://github.com/freeCodeCamp/boilerplate-infosec/pull/74)
- [x] Information Security with Bcrypt (https://github.com/freeCodeCamp/boilerplate-bcrypt/pull/17)
- [x] Stock Price Checker (https://github.com/freeCodeCamp/boilerplate-project-stockchecker/pull/38)
- [x] Anonymous Message Board (https://github.com/freeCodeCamp/boilerplate-project-messageboard/pull/30)
- [x] Port Scanner (https://github.com/freeCodeCamp/boilerplate-port-scanner/pull/6)
- [x] SHA-1 Password Cracker (https://github.com/freeCodeCamp/boilerplate-SHA-1-password-cracker/pull/6)
- [x] Secure Real Time Multiplayer Game (https://github.com/freeCodeCamp/boilerplate-project-secure-real-time-multiplayer-game/pull/25)

## Machine Learning with Python
- [x] Rock Paper Scissors (https://github.com/freeCodeCamp/boilerplate-rock-paper-scissors/pull/11)

## Create a forum guide post with a Gitpod tutorial
Current draft here: https://forum.freecodecamp.org/t/how-to-use-gitpod-in-the-curriculum/668669

## Other Tasks
- [x] Add a note to the top of each superblock with a link to the forum guide post (https://github.com/freeCodeCamp/freeCodeCamp/pull/53500)
- [x] Adjust solution form for Gitpod (Note: this should get merged and deployed before the PR below https://github.com/freeCodeCamp/freeCodeCamp/pull/53511)
- [x] Require Github link for backend projects (https://github.com/freeCodeCamp/freeCodeCamp/pull/53512)

## Will Close
Once all the changes here have been merged / deployed, the following issues can be closed:

- https://github.com/freeCodeCamp/freeCodeCamp/issues/52455
- https://github.com/freeCodeCamp/freeCodeCamp/issues/51585
- https://github.com/freeCodeCamp/freeCodeCamp/issues/50258
- https://github.com/freeCodeCamp/freeCodeCamp/issues/52810

**Comment by ShaunSHamilton** [comment]
Are we going to do the same thing the RDB does by only showing a note at the top of the superblock page linking to the guide post?
<img width="677" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/b4c04dea-f2a3-4b03-ac8a-9a6bde9d2ba6">

**Comment by scissorsneedfoodtoo** [comment]
@ShaunSHamilton, yes, I think it would be a good idea to link to the forum guide post at the top of each superblock. That should answer some FAQs that learners have about working with Gitpod, and will hopefully cut down on the number of new forum posts that get opened up.

**Comment by ShaunSHamilton** [comment]
**For Discussion**

Seeing as many cloud IDE providers now use ephemeral apps/links, we will not **require** the solution link to be in the database. As such, the github link will be required.

That said, there might/will still be some Campers who want their solution links to be visible on their certifications, because they have hosted their apps somewhere permanent.

So, questions:
a) Are we going to allow Campers to save their solution links to the db (as we do now)?
b) If so, how are we going to prevent ephemeral links from being submitted?
c) If so, how are we going to make it clear to Campers not to submit ephemeral links?

**Comment by ShaunSHamilton** [comment]
>  I guess we could check that it's live at the time of submission

Right. We already do, and have to do, this. The tests run against a live app.

> trying to block certain domains or whatever... feels like a whack-a-mole type thing - those services may change the way they do things

Why would we block domains? At most (what we already do), we give a warning/note to Campers when they try to paste known "editor" urls in the "live app" field, because that is a common misunderstanding Campers have - which link to submit for the tests.

> Are we going to require it be a Github URL or should we allow whatever URL?

We are (as we already do) going to allow any url. I just used this language, because that is the variable name in the code:
https://github.com/freeCodeCamp/freeCodeCamp/blob/1972f39b6888cebfa15bdabebb0e9ebb12341777/client/src/templates/Challenges/projects/solution-form.tsx#L52-L55

**Comment by ShaunSHamilton** [comment]
The question is:
If we store the `solutionLink` in the db, are we ok with most links pointing to non-existent pages on certifications/profiles?

**Comment by moT01** [comment]
> Why would we block domains?

I'm not sure why we would block domains - I guess my thought was that, we know gitpod URL's stop working so we wouldn't allow them or something.

> If we store the solutionLink in the db, are we ok with most links pointing to non-existent pages on certifications/profiles?

Yea, I see the problem. I like the idea of having the ability to submit and show the solutions on my profile, and it makes sense - but if most solutions are going to end up not working, then maybe it's not worth it. I still don't see a whole lot of downside to storing the solutions - and we can choose to not display them on the profiles if we want. I dunno, maybe it would be confusing for campers to submit a URL and then it doesn't get displayed anywhere. I'm kind of in the middle, but I think I would vote to continue storing the solutions and including the links on the profile.

**Comment by ShaunSHamilton** [comment]
> and we can choose to not display them on the profiles if we want.

How would this be decided? A checkbox next to the submission field that says:
> [ ] Save and display my app URL on my profile. NOTE: If your app is not permanently hosted, this will cause your profile/certifications to have dead links.

**Comment by ShaunSHamilton** [comment]
What about the `take-home-projects` block? Are we going to leave it as is? Or, also require the source code?

**Comment by moT01** [comment]
> What about the take-home-projects block? Are we going to leave it as is? Or, also require the source code?

I'm not sure - they're definitely not as important at the moment. I would say probably yes for the full stack projects. The rest of them can be completed on codepen though - I don't think we need a github link for those. They could probably be left how they are for now, but we could probably convert them to use the multifile editor?

**Comment by ShaunSHamilton** [comment]
This should close: https://github.com/freeCodeCamp/freeCodeCamp/issues/52455
