### ISSUE TITLE
Add code example for `Math.abs` introduction in step 81 calorie counter

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53487]
### Describe the Issue

Whenever we introduce a new concept, we should include a code example.
Sometimes we do this and sometimes we don't which creates inconsistency in the curriculum. 
To fix this let's update the description to include a code example.

## updated description for step 81 
````md
# --description--

When the user has a calorie deficit, the `remainingCalories` value will be negative. You don't want to display a negative number in the result string.

`Math.abs()` is a built-in JavaScript method that will return the absolute value of a number.

```js
const num = -5;
Math.abs(num); // 5
```

In your `span` text, wrap your `remainingCalories` reference in `Math.abs()` to ensure that the value is positive.
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-81

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9e769df38c92635c158ba.md

Happy coding

**Comment by incruder1** [comment]
hello @jdwilkin4, can I solve it?
