### ISSUE TITLE
Provide code example for first mention of `toLowerCase` method in step 79 calorie counter

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53486]
### Describe the Issue

We introduce the `toLowerCase` method in step 79, but do not provide a code example.
For consistency, we should provide code examples for these methods when they are first introduced.

## updated step 79 description
````md
When you need to lower case a string, you can use the <dfn>toLowerCase()</dfn> method. This method returns the calling string value converted to lower case.

```js
const firstName = 'JESSICA';
console.log(firstName.toLowerCase()); // Output: jessica
```

Your `output.innerHTML` string will need a `span` element. Create that, and give it a `class` attribute set to the `surplusOrDeficit` variable. Your `surplusOrDeficit` variable should be converted to lower case using the `toLowerCase()` method.

Do not give your `span` any text yet.
```` 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-79

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9e63bb1e32d23b6adbe44.md

Happy coding

**Comment by netanelben** [comment]
Hello :) newbie here, I am going to tackle this task. PR will be published soon.

**Comment by Niwpas** [comment]
The step actually wants you to include the whole span element in a template literal and then in **${xya}** to add the surplusOrDeficit variable using the **toLowerCase()** method, like this:  ### **output.innerHTML = `<span class="${surplusOrDeficit.toLowerCase()}"></span>`;**
