### ISSUE TITLE
Bonfire: Boo who - Add test cases to fix workaround.

### ISSUE THREAD

**Issue by thongvo** [FreeCodeCamp/FreeCodeCamp#5349]
Challenge [Bonfire: Boo who](http://www.freecodecamp.com/challenges/bonfire-boo-who#?solution=function%20boo(bool)%20%7B%0A%20%20%2F%2F%20What%20is%20the%20new%20fad%20diet%20for%20ghost%20developers%3F%20The%20Boolean.%0A%20%20if(bool%20%3D%3D%3D%20null)%20return%20false%3B%0A%20%20%0A%20%20if(bool.toString()%20%3D%3D%20%27true%27%20%7C%7C%20bool.toString()%20%3D%3D%20%27false%27%20%26%26%20bool%20!%3D%3D%20null)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0Aboo(%27false%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function boo(bool) {
  // What is the new fad diet for ghost developers? The Boolean.
  if(bool === null) return false;
  
  if(bool.toString() == 'true' || bool.toString() == 'false' && bool !== null) {
    return true;
  } else {
    return false;
  }
  
}

boo('false');

```

**Comment by SaintPeter** [comment]
Confirmed.

We need two tests that should return false for the string literals `"true"` and `"false"`.
