### ISSUE TITLE
Update hint text for step 61 of calorie counter project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53499]
### Describe the Issue

We have this post on the forum
https://forum.freecodecamp.org/t/learn-form-validation-by-building-a-calorie-counter-step-61/668041

The camper was trying to pass step 61 with this code 

```js
function getCaloriesFromInputs(list) {
  let calories = 0;

  for (let i = 0; i < list.length; i++) {
    const currVal = cleanInputString(list[i].value);
    const invalidInputMatch = isInvalidInput(currVal);

    if (invalidInputMatch) {
      alert(`Invalid Input: ${invalidInputMatch[0].value}`);
    }
  }
}
```
The hint text was telling them this
```md
You should use template literal syntax to display the first value in the `invalidInputMatch` array after the `Invalid Input: ` text.
```

We should update the wording to make it more clear that they should get the first element of that `invalidInputMatch` array.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-61

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by shanmukh-sai2003** [comment]
"You should display the first element in the `invalidInputMatch` array after `Invalid Input: ` text using template literal."

does the above sentence satisfy the requirement?

**Comment by jdwilkin4** [comment]
@shanmukh-sai2003 

That's works for me 👍
