### ISSUE TITLE
Dice Game Step 67 a lot less than required seems to pass

### ISSUE THREAD

**Issue by SabuWolf96** [freeCodeCamp/freeCodeCamp#53493]
### Describe the Issue

Normally I felt the tests are to sensitive, now this one is the complete opposite. 
I haven't even done everything (and maybe something wrong) and I got a pass.

I feel like this isn't supposed to happen

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-algorithmic-thinking-by-building-a-dice-game/step-67

### Your code

```
totalScoreText.innerHTML = totalScore;
scoreHistory.innerHTML = "";


```

### Expected behavior

It shouldn't pass this early into the Step, but it did

### Screenshots

![Issue_DiceGame](https://github.com/freeCodeCamp/freeCodeCamp/assets/18598177/6eca041a-4c23-4b3e-8b2a-7894b0973f43)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by SabuWolf96** [comment]
It only checks for `scoreHistory.innerHTML = "";`
The rest is irrelevant

**Comment by gikf** [comment]
Tests are matching changes to `currentRoundRollsText.textContent` and `currentRoundText.textContent` that are done in different function.

**Comment by gikf** [comment]
@shanmukh-sai2003 these three lines are present in the seed code at the start of step, but in different functions.
```
totalScoreText.textContent = totalScore;
currentRoundRollsText.textContent = rolls;
currentRoundText.textContent = round;
```

Related tests are passing because of these lines, as tests don't contain any additional regex to make sure matched lines are ones added in correct place.

**Comment by shanmukh-sai2003** [comment]
Does that mean assert.match() is trying to match the regular expression on the entire seed code? I thought it was just matching against the added lines.

How can we make sure that regex matches only the added lines?

**Comment by gikf** [comment]
It's checked against whole code. Only way to limit that scope is either by adding more constraints to the regex. Or limit the _code_ that's checked against, some challenges are doing that by splitting code on specific text/line, and then using the part where change is expected.
