### ISSUE TITLE
Closing curly brace and the closing parenthesis issue

### ISSUE THREAD

**Issue by gutter-blake** [freeCodeCamp/freeCodeCamp#53504]
### Describe the Issue

The solution requires closing curly brace and closing parenthesis to be on the same same line and I do not understand why. Please help in clarifying why.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-18

### Your code

```
const renderSongs = (array) => {
const songsHTML = array
.map((song)=> {
…
}
).join(“”)
};


```

### Expected behavior

This solution should pass but it is not

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
Laptop
Windows 10
Firefox
122

### Additional context

The solution requires closing curly brace and closing parenthesis to be on the same same line and I do not understand why.

**Comment by gikf** [comment]
It's just test being strict. This will be fixed in #53480.
