### ISSUE TITLE
Challenge Editor shows error

### ISSUE THREAD

**Issue by altsun** [freeCodeCamp/freeCodeCamp#53525]
**Describe the bug**
Hi team, I see a new error in Challenge Editor

**To Reproduce**
1. Open the terminal and cd to freeCodeCamp root folder
2. run `pnpm run challenge-editor`
3. Open the browser, go to  http://localhost:3300/

**Expected behavior**
Challenge Editor should work properly.

**Screenshots**
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/23631165/fbaaac51-f4cc-4181-93ec-346be2138e97)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 120

**Comment by gikf** [comment]
Please make sure your `.env` file for challenge editor is up to date. There was change of the env variable name not so long ago.

**Comment by altsun** [comment]
Hi @gikf, I recopied `sample.env` to `.env`, but the error still happens

**Comment by gikf** [comment]
I should likely be more precise. Could you double check that was `/tools/challenge-editor/client/.env`?

**Comment by altsun** [comment]
Thanks @gikf, it works now
