### ISSUE TITLE
step 65 of calorie counter project unclear instruction

### ISSUE THREAD

**Issue by JoyShaheb** [freeCodeCamp/freeCodeCamp#53531]
### Describe the Issue

The instruction doesn't say that the user needs to declare a es6 arrow function and not a regular function.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/f6a49f12-5304-4cc5-aca3-fa3050fd5db2)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-65

### Your code

```
const calculateCalories = (e)=>{}
```

### Expected behavior

should accept both regular and es6 arrow functions

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/f6a49f12-5304-4cc5-aca3-fa3050fd5db2)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by JoyShaheb** [comment]
@jdwilkin4 your thoughts on this ?

**Comment by jdwilkin4** [comment]
> should accept both regular and es6 arrow functions

I have tested this and the current tests accept both regular and arrow functions 

> The instruction doesn't say that the user needs to declare a es6 arrow function

Arrow functions aren't taught until the music player project.
So the camper will need to write a regular function.

I am able to pass with a regular function
<img width="741" alt="Screenshot 2024-02-04 at 10 31 42 AM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/a248c0d5-3f81-45b3-8e9e-12b3113df5cc">

**Comment by JoyShaheb** [comment]
my apologies, i mentioned the wrong step and wrong project, we can close this, I'll open up another one with appropriate descriptions, Thanks @jdwilkin4
