### ISSUE TITLE
Issue while getting red text in h2

### ISSUE THREAD

**Issue by rdharmegowda** [FreeCodeCamp/FreeCodeCamp#5353]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%3Cstlye%3E%0A%20%20.red-text%20{%0A%20%20color%3A%20red%3B%0A%20%20}%0A%3C%2Fstlye%3E%0A%0A%3Ch2%20class%3D%20%22red-text%22%3E%20CatPhotoApp%20%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
![issue](https://cloud.githubusercontent.com/assets/11192129/11895412/7b166bc2-a5a4-11e5-9cb8-7765b8416f23.JPG)

Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<stlye>
  .red-text {
  color: red;
  }
</stlye>

<h2 class= "red-text"> CatPhotoApp </h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by edwardp11** [comment]
<stlye>
  .red-text {
  color: red;
  }
</stlye>

-----------------------------------------

<style> and </style> have syntax errors. You have "<stlye>" there.

**Comment by tv1ster** [comment]
```
</style>, not <stlye>
```

**Comment by ltegman** [comment]
@tv1ster is correct that you misspelled style. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm that your problem is really a bug before filing a Github issue.

Thanks and happy coding!

**Comment by rdharmegowda** [comment]
Hi everyone,

Oh yeah, my apologies.

Thanks for all your responses.

Regards
Ramesh

On Friday 18 December 2015, Logan Tegman <notifications@github.com> wrote:

> @tv1ster <https://github.com/tv1ster> is correct that you misspelled
> style. In the future please visit the Help Chat
> <https://gitter.im/FreeCodeCamp/Help> to confirm that your problem is
> really a bug before filing a Github issue.
>
> Thanks and happy coding!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5353#issuecomment-165852301>
> .
>


-- 
Sent from iPhone Mobile
