### ISSUE TITLE
 unclear instructions platformer game step 78

### ISSUE THREAD

**Issue by RGHANILOO** [freeCodeCamp/freeCodeCamp#53538]
### Describe the Issue

following task ask for : 
` Inside that array, add a boolean expression that checks if the player's y position plus the player's height is less than or equal to the platform's y position. `

reading this line suggests/ indicates to me writing an "if" statement inside of the array although that could be my understanding of the sentence

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-78

### Your code

```




```

### Expected behavior

my suggestion would be to update the sentence to the following 

` Populate this array with a boolean expression that evaluates whether the sum of the player's y position and height is less than or equal to the platform's y position `

### System

- Device: [macBook pro]
- OS: [Ventura 13.4.1 ]
- Browser: [chrome ]
- Version: [121.0]

**Comment by jdwilkin4** [comment]
Hi @RGHANILOO ! 

Thank you for creating this issue.

I think the re wording makes sense.
The only thing, I would change would be the first part of that sentence. We should mention explicitly that they are adding to the `collisionDetectionRules` array.

I will go ahead and open this up for contribution for `first timers only`

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/64c9e90c433fde2e870285a3.md

## Updated instructions
```md
Inside the callback function, create a new `const` variable called `collisionDetectionRules` and assign it an empty array. 

Inside the `collisionDetectionRules` array, add a boolean expression that evaluates whether the sum of the player's `y` position and height is less than or equal to the platform's `y` position.
```

Happy coding

**Comment by zishpanchal** [comment]
Hi I have have fixed this issue as well but I have made 2 commits in #53551 which also contains the fix for this issue.

**Comment by developwithabhinav** [comment]
I updated the instructions of step 78 and committed the changes. Please have a look at that
Thank you

**Comment by developwithabhinav** [comment]
I am sorry but since I am new to open-source contributions, I accidentally closed the previous PR. I am making a new Pull Request please have a look at that.
