### ISSUE TITLE
Regex tests are to strict for step 9 of TODO project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53547]
### Describe the Issue

We had a camper on the forum unable to pass step 9.
https://forum.freecodecamp.org/t/learn-localstorage-by-building-a-todo-app-step-9/670010

This was their code

```js
discardBtn.addEventListener("click", () => {

confirmCloseDialog.close()

taskForm.classList.toggle("hidden")}

);
```
the issue was their formatting not matching what the regex test is expecting here

````
```js
assert.match(code, /discardBtn\.addEventListener\(\s*('|"|`)click\1\s*,\s*\(\s*\)\s*=>\s*\{\s*confirmCloseDialog\.close\(\s*\);?\s*taskForm\.classList\.toggle\(\s*('|"|`)hidden\2\s*\);?\s*\}\s*\);?/)
```
````
we should allow for any correct answers to pass and not be strict about formatting here because these are still beginners getting the hang of it. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-9

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
This was actually fixed in #53480 :smile:
