### ISSUE TITLE
JavaScript - Waypoint: Declare JavaScript Variables bug

### ISSUE THREAD

**Issue by melwinalm** [FreeCodeCamp/FreeCodeCamp#5354]
The code windows has used 'ourName' as the variable. But the explanation on the left window says 'myName' as the variable.

**Comment by sludge256** [comment]
That's because it is an example.
At the bottom of the instructions:
>Now, use the var keyword to create a variable called myName. Set its value to your name, in double quotes.

>**Look at the ourName example if you get stuck.**

It may be helpful if they added:
```
//Only change code under this line
```
like they do with some of the other waypoints, but you can still pass simply by changing the name of the existing variable.

**Comment by ltegman** [comment]
The description text is incorrect though. In the following text it refers to `myName` where it should be referring to `ourName`:

> Let's create our first variable and call it "myName".
> 
> You'll notice that in `myName`, we didn't use a space, and that the "N" is capitalized. JavaScript variables are written in camel case. An example of camel case is: camelCase.

**Comment by sludge256** [comment]
You're right. I'll pay more attention next time. I wasn't sure which part of the explanation they were referencing and noticed the `myName` at the bottom first.
