### ISSUE TITLE
Unclear instructions Step 61- Python Password generator

### ISSUE THREAD

**Issue by zairahira** [freeCodeCamp/freeCodeCamp#53545]
### Describe the Issue

Some campers seem overwhelmed with the Step 61 of Password Generator.
[Here](https://forum.freecodecamp.org/search?q=Learn%20Regular%20Expressions%20by%20Building%20a%20Password%20Generator%20-%20Step%2061) are some of the reported issues on the forum.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/step-61

### Your code

-

### Expected behavior

Simplify and break the instruction further. 
More suggestions are welcome on how to improve further.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by marzsec20** [comment]
i am stuck here as well
