### ISSUE TITLE
update instructions for step 110 for rpg project

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#53555]
### Describe the Issue

The instruction are not clearing, it take times to know what it is saying

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-111

### Your code

```
NA
```

### Expected behavior

The heading should read 
> Following the same pattern as fightSlime, use that code in the fightBeast and fightDragon functions. Remember that beast is at index 1 and dragon is at index 2. Also, remove the console.log call from your fightDragon function.

### Screenshots

<img width="832" alt="Screenshot 2024-02-05 at 21 30 18" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/8664996/99fc7fa8-8252-40e3-a410-54d402a23316">

### System

- Device: Laptop
- OS: Mac
- Browser: Chrome

**Comment by jdwilkin4** [comment]
It looks like the steps have been update on main but not live on the site.

So the step you are referring will be step 110 here.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8dfcf7fb1044d2f478fd1.md

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8dfcf7fb1044d2f478fd1.md

## updated description

```md
Following the same pattern as the `fightSlime` function, use that code in the `fightBeast` and `fightDragon` functions. Remember that `beast` is at index `1` and `dragon` is at index `2`. Also, remove the `console.log` call from your `fightDragon` function.
```

Happy coding
