### ISSUE TITLE
FreeCodeCamp Santa Barbara Campsite listed as in Honduras

### ISSUE THREAD

**Issue by mhelmetag** [FreeCodeCamp/FreeCodeCamp#5356]
There probably is a Santa Barbara in Honduras but... there's also a Santa Barbara, CA... I think most of the people in the current Facebook group are associating the group with the campsite in Santa Barbara, CA. I can make another facebook group one in CA or we could just update the list of campsites.

Thoughts on how to proceed?

(Trying to integrate FreeCodeCamp gatherings into a current Learn to Program meetup in Santa Barbara)

**Comment by BerkeleyTrue** [comment]
Please open this issue in the [wiki](https://github.com/freecodecamp/wiki) repo.

Happy Coding!

**Comment by mhelmetag** [comment]
Oh woops! Thanks!

**Comment by BerkeleyTrue** [comment]
@mhelmetag No worries. Not many know it is there.
