### ISSUE TITLE
Fix step 47 TODO app tests to allow for inequality and strict inequality operator

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53588]
### Describe the Issue

We had a camper on the forum try to pass step 47 with this code.

https://forum.freecodecamp.org/t/learn-localstorage-by-building-a-todo-app-step-47/670549

```js
const formInputValuesUpdated = titleInput.value != currentTask.title || dateInput.value != currentTask.date || descriptionInput.value != currentTask.description;
```
The description do not specify that the answer has to use the strict inequality. Only the last hint does.

```js
const formInputValuesUpdated = titleInput.value !== currentTask.title || dateInput.value !== currentTask.date || descriptionInput.value !== currentTask.description;
```
the tests should be updated to allow for both

Also the tests expect a certain order.

The tests shouldn't force a particular order.
All valid answers should be accepted. 

Update this last hint text here

```js
Your `formInputValuesUpdated` variable should have the value `titleInput.value !== currentTask.title || dateInput.value !== currentTask.date || descriptionInput.value !== currentTask.description`.
```
It should be updated to this so we don't force order or preference over inequality operators.

```md
Your `formInputValuesUpdated` variable should check if `titleInput.value` is not equal to `currentTask.title`, `dateInput.value` is not equal to `currentTask.date`, or `descriptionInput.value` is not equal to `currentTask.description`.
```

And if there is a way to rewrite the tests to use less regex and more of the other assert methods, that would be even better
https://www.chaijs.com/api/assert/#method_assert

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-47

### Your code

see example above

### Expected behavior

see example above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by a2937** [comment]
Would it be reasonable to create something like a context variable holding onto the variables created during the challenge?  I wanna try to use the `vm` npm module to safely evaluate all the code in the test runner so they'll be available for tests so there's actually a way to use the evaluated code rather than strings.

**Comment by a2937** [comment]
The problem is the only reasonable place I can think of to install and use this would be the workspace root, and in `frame-runner.ts`. Somewhere around here. https://github.com/freecodecamp/freeCodeCamp/blob/74050224847ce59254a1d3714a979078c9a5e935/tools/client-plugins/browser-scripts/frame-runner.ts#L80

**Comment by jdwilkin4** [comment]
> Would it be reasonable to create something like a context variable holding onto the variables created during the challenge? I wanna try to use the vm npm module to safely evaluate all the code in the test runner so they'll be available for tests so there's actually a way to use the evaluated code rather than strings.

It definitely sounds interesting.

I think for the scope of this issue, we should stick with the existing assert methods from Chai.

I would suggest opening a separate issue, with your idea and get feedback from the team. Because this could be applied to other steps as well if the general consensus would be to move forward with this

**Comment by a2937** [comment]
I was experimenting all day, but couldn't get it to actually work. The `vm` module wouldn't resolve no matter what in the browser and a simple `eval` seemed to just slow things down horribly.

**Comment by jeremylt** [comment]
Why not specify strict equality here? I thought in general it was a best practice to use strict over allowing for coercision.

**Comment by jdwilkin4** [comment]
> I thought in general it was a best practice to use strict over allowing for coercision.

I think it really depends on the situation. 

In this case, we are only dealing with user input which will always return a string. Allowing campers to pass with the inequality operator is fine because they have demonstrated their understanding of the concept.

**Comment by jeremylt** [comment]
Have they demonstrated why they know using == will be fine here?

**Comment by jdwilkin4** [comment]
Well the challenge asks them to check if the inputs are not equal. 
So if they respond with either `!==` or `!=` then they have understood the task.

If we weren't sure what data types we would be dealing and were concerned about coercion, then we should push for only using strict inequality.

I don't think campers should be marked wrong if they use `!=` here because it is perfectly safe to do so in this case.

**Comment by jeremylt** [comment]
Generally, one of the biggest weaknesses I've seen with JavaScript learners is an understanding of types since they are not explicitly defined. I agree the comparison with != is valid here but would honestly be surprised if most of our learners could articulate why.

**Comment by jdwilkin4** [comment]
Most will probably end up using the `!==` because that was taught to them earlier.
But for the few who want to use the `!=`, they will be able to pass with this change in the tests.

> I'd at least keep the solution template using !== as we push users though our tutorials

Yeah, I agree with that 👍
