### ISSUE TITLE
Create Campsite Database, Interface, Connect to Google API

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5358]
We need a campsite database to simplify management of campsites and to auto-populate a map showing the locations of campsites to allow users to find a campsite close to them.
### Database Structure

| Field Name | Type | Notes |
| --- | --- | --- |
| id | ObjectId | Unique Campsite ID |
| city | string | City Name |
| country | string | Country Name - Populate from Dropdown |
| subdivision | string | State/Province, etc |
| coordinates | object | Lat/Long object |
| google_id | string | unique google id for map element |
| url | string | Social Media URL (IE: Facebook Link) |
| createdBy | ObjectId | FCC User who created the record |
| createdOn | date | Campsite Record Creation date |
| display | boolean | Display/Don't Display (for Moderation) |
### Interface

**Route**: /campsites
- Default View
  Simple single page display with Embedded Google Map.  Below the map is a hierarchical, alphabetic display of all campsites, same as on the Wiki page.
- Add Campsite Button 
  Pops up a modal with the appropriate fields.
  Do Google API lookup on submit to validate location of city and fill in sub-division?
  On submit send an e-mail to moderators?
- Moderation
  Table on default view shows "unapproved" campsites
  Click "Approve" to toggle display state, posts to Google API
  Click "Delete" to remove campsite
  Click "Edit" to change location, etc.
### Google API

Upon approval, coordinates are sent to the Google API to update the map.

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by evaristoc** [comment]
:+1:

**Comment by geoff616** [comment]
Took a stab at this.

Very rough around the edges, and currently running as a standalone app: https://campsite-test-geoff616.c9users.io/ with the source: https://github.com/geoff616/campsiteTest

Happy to try to clean it up and integrate into the main app if this is in the right direction.

**Comment by SaintPeter** [comment]
@geoff616 This is really slick!  I just tried it out.  Works well.

**Comment by hallaathrad** [comment]
I'm in :)

**Comment by shojaala** [comment]
7241
