### ISSUE TITLE
Remove `.clear` class styles from calorie counter project

### ISSUE THREAD

**Issue by wendywo-dev** [freeCodeCamp/freeCodeCamp#53580]
### Describe the Issue

Hi, I found a styling class that doesn't seemed to be used in the HTML or JavaScript code,

```
.clear {
  background-color: var(--light-pink);
  color: var(--dark-red);
  border-color: var(--dark-red);
}
```

The original HTML only specified the id "clear" but not the class "clear"
`<button id="clear" type="button">Clear</button>`

I personally just add a new class to the button tag to solve the problem:
`<button id="clear" class="clear" type="button">Clear</button>`

Hope this helps.
Also, thank you all very much for this certification course.
Hope to contribute more in the future. Thanks.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-1

### Your code

```
<button id="clear" class="clear" type="button">Clear</button>


```

### Expected behavior

The clear button should have a light-pink background color and dark red text color.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
Hi @wendywo-dev ! 

That is a good catch.

It looks like in the original development of this project there were going to be some styles with for the class of clear but it was never added.

We can remove that class completely from the CSS files 👍

**Comment by jdwilkin4** [comment]
Looking at the original styled button, I think it is best to leave those `clear` styles out. 👍

**Comment by jdwilkin4** [comment]
# Note to Contributors 

If you are going to work on this issue, make sure to remove the following class from all 94 steps.

This is the class that will be removed

```css
.clear {
  background-color: var(--light-pink);
  color: var(--dark-red);
  border-color: var(--dark-red);
}
```
