### ISSUE TITLE
Code duplicity in " Learn Modern JavaScript Methods by Building Football Team Cards" lesson in "JavaScript Algorithms and Data Structures" course

### ISSUE THREAD

**Issue by bwyoungy** [freeCodeCamp/freeCodeCamp#53592]
### Describe the Issue

I noticed there is quite a bit of code duplicity. The raw information of the players is hardcoded both on the index.html page and in the script page in the players array.

I would suggest deleting the information from the HTML page (have an empty #player-cards div), and call the setPlayerCards function after it's definition (as in the code below (copied the relevant part))

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-48

### Your code

```
const setPlayerCards = (arr = players) => {
  playerCards.innerHTML += arr
    .map(
      ({ name, position, number, isCaptain, nickname }) =>
        `
        <div class="player-card">
          <h2>${name} ${isCaptain ? "(Captain)" : ""}</h2>
          <p>Position: ${position}</p>
          <p>Number: ${number}</p>
          <p>Nickname: ${nickname !== null ? nickname : "N/A"}</p>
        </div>
      `
    )
    .join("");
};

setPlayerCards();

playersDropdownList.addEventListener("change", (e) => {};


```

### Expected behavior

The behaviour will be the same but with hardcoding of the information only once.
Ideally we'd have the hardcoded information outside of the code in an external file or server, but that's not been taught yet at this stage

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
> Ideally we'd have the hardcoded information outside of the code in an external file or server, but that's not been taught yet at this stage

Yeah, I don't think we should update the project to move the data elsewhere only to have campers use fetch to access that data.

Fetch isn't taught until the last two projects. I think it would be best to leave it as is.

**Comment by jdwilkin4** [comment]
> I would suggest deleting the information from the HTML page (have an empty #player-cards div), and call the setPlayerCards function after it's definition (as in the code below (copied the relevant part))

Yeah, this would involve add on extra step, and removing the HTML from the seed code which wouldn't be that much to change.

I would be more on board with this change then fetching the data from elsewhere.

But let's hear from the rest of the team to see what they think.

**Comment by bwyoungy** [comment]
> > Ideally we'd have the hardcoded information outside of the code in an external file or server, but that's not been taught yet at this stage
> 
> Yeah, I don't think we should update the project to move the data elsewhere only to have campers use fetch to access that data.
> 
> Fetch isn't taught until the last two projects. I think it would be best to leave it as is.

I agree :)
Was mentioning it as a general point. I of course think it's for a later point of the course to work in this way
