### ISSUE TITLE
Update description for step 118 of RPG project

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#53601]
### Describe the Issue

The instruction isn't clear to use 'compound assignment' e.g. now it says
> On a new line, add the string You attack it with your <weapon>. to the text value, replacing <weapon> with the player's current weapon. Additionally, remember that this line of text starts with a space so it will properly display.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-119

NOTE: This is actually step 118 in the main branch.

### Your code

```
NA
```

### Expected behavior

On a new line, add compound assignment to the string `You attack it with your <weapon>`. to the text value, replacing <weapon> with the player's current weapon. Additionally, remember that this line of text starts with a space so it will properly display.

### System

- Device: Laptop
- OS: macOS
- Browser: Chrome
- Version:  121.0.6167.139

**Comment by developwithabhinav** [comment]
Hi, I am unable to find the file which needs changes. Can you please tell how to find it out for future?

**Comment by mahassan** [comment]
> Hi, I am unable to find the file which needs changes. Can you please tell me how to find it out?

@developwithabhinav https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-119

**Comment by developwithabhinav** [comment]
Well, I was asking about how to find it from the GitHub repository. Thanks mahassan, I got it now.

**Comment by jdwilkin4** [comment]
HI @mahassan ! 

Thank you for opening this issue.

I would suggest that we tweak your suggestion to fix a couple of missing grammar things. Also we should specify that we are specifically looking for the addition assignment operator. 


## updated description

```md
On a new line, use the addition assignment operator(`+=`), to add the string `" You attack it with your <weapon>."` to the `text` value, replacing `<weapon>` with the player's current weapon. Additionally, remember that this line of text starts with a space so it will properly display. 
```
