### ISSUE TITLE
Update directions for current step 120 of RPG project

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#53604]
### Describe the Issue

The instruction are not clear, right now it says
> Set monsterHealth to monsterHealth minus the power of the player's current weapon. Remember you have the currentWeapon variable and the power property.

### Affected Page

Edit: This is actually step 120 in the main branch

### Your code

```
NA
```

### Expected behavior

Set monsterHealth to monsterHealth minus the power of the player's current weapon. Remember you have the currentWeapon which is not initialized variable and the power property on weapons array.

### System

- Device: Laptop
- OS: macOS
- Browser: Chrome

### Additional context

I think it should be more detail about what and where is currentWeapon, power property and how to access it like in previous.

**Comment by jdwilkin4** [comment]
> Remember you have the currentWeapon which is not initialized variable

It looks like currentWeapon is initalized with the value of 0 here

```js
let currentWeapon = 0;
```
Then it is updated over time throughout the project.

I think for that second sentence it should be clear about syntax on how to access those values since beginners are still struggling with that. Being more explicitly will help confusion on the forum posts.

Let's go with this change.

## updated description
```md
Set `monsterHealth` to `monsterHealth` minus the power of the player's current weapon. 

Remember that you can access the power of the player's current weapon using `weapons[currentWeapon].power`.
```

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8e49f4df7af5ae2d7a616.md

Happy coding
