### ISSUE TITLE
Request to add 2-3 steps to responsive web design: cat painting to demistify CSS triangles

### ISSUE THREAD

**Issue by dearestalexander** [freeCodeCamp/freeCodeCamp#53607]
### Is your feature request related to a problem? Please describe.

I was a little confused by the process to create cat ears. After mentioning it on 100 days of code channel (discord) I saw at least one other person hadn't understood it. So maybe more?

- In step 23 we start to draw the first cat ear <div class=”cat-left-ear”></div>
- We go straight to the CSS trick with thick borders and transparent sides
- At this point in the learners journey they are still not that familiar with the process of using <div></div> to create squares & rectangles and the different ways they can then manipulate those
- This made for a slightly frustrating few steps in an otherwise enjoyable exercise.
- (at first before searching for tutorials on this I thought it was utilising ‘layers’ somehow to reveal colours of the parent <div> - wrong lol).

### Describe the solution you'd like

I'd like to add 2-3 steps. I have drafted out a sample of what they could look like. Please see my notes: 
[Cat painting proposal](https://tulip-attack-b0f.notion.site/Exercise-Learn-Intermediate-CSS-by-Building-a-Cat-Painting-382da14c6cb04dd08ff4efa134b6ec54?pvs=4)

### Describe alternatives you've considered

I don't think any alternative is needed. It's just a judgement call whether to leave it as it is which would require some learners to do some additional research or to make modification to add a step or two. I think it's good to have learners do some side research, my worry is that some people will just skip it blindly following the instructions and not understand.

**Comment by naomi-lgbt** [comment]
I'd be okay with adding these steps - it'll be good clarification for folks who struggle to visualise how the triangle comes to be.

**Comment by dearestalexander** [comment]
@naomi-lgbt is this something I can help to implement, or do I need to be more experienced or qualified with freecodecamp? I'd be happy to read up / learn about how to do it if possible.

**Comment by naomi-lgbt** [comment]
You absolutely can! It's open for contribution - I encourage you to start with [our contributing docs](https://contribute.freecodecamp.org)

**Comment by dearestalexander** [comment]
Ok great, I'll get started on the documents and then work on this one.
