### ISSUE TITLE
Update instructions for step 127 of RPG project

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#53632]
### Describe the Issue

The instruction read as follows
> In your defeatMonster function, set gold equal to gold plus the monster's level times 6.7. You can get the monster's level with the level property.
Here is an example of setting num to num plus 5 * 8: num += 5 * 8. Use Math.floor() to round the result down.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-127

### Your code

```
NA
```

### Expected behavior

> In your defeatMonster function, set gold equal to gold plus the monster's level times 6.7. You can get the monster's level with the level property (don't forget that monsters is a Array and each array can be accessed by a number. We use fighting to access the index
Here is an example of setting num to num plus 5 * 8: num += 5 * 8. Use Math.floor() to round the result down.

### System

- Device: Laptop
- OS: macOS
- Browser: Chrome

**Comment by jdwilkin4** [comment]
Let's simplify it to the following: 

```md
In your `defeatMonster` function, set `gold` equal to `gold` plus the monster's level times `6.7`. Remember you can get the monster's level by using `monsters[fighting].level`.

Here is an example of setting `num` to `num` plus `5` * `8`: `num += 5 * 8`. Use `Math.floor()` to round the result down.
```

# Note to contributors 
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8eefe2e68b66ac563816b.md

Happy coding
