### ISSUE TITLE
Create guide for adding token to Gitpod after logging out of FCC

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#53630]
Users who log out of freecodecamp.org automatically have their `userToken` deleted from the user record: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/3b9ae66a6447dd19053b624a322534243d15ba5b/api-server/src/server/boot/authentication.js#L71

Since their Gitpod VM is created with (and persists) that token, they will no longer be able to submit their projects, even after logging back in to freecodecamp.org.  We should find some way to fix this.

One possibility is to use `gp env CODEROAD_WEBHOOK_TOKEN=<users-token>` in the Gitpod workspace, but we'd first need to show them their token.

First discussed here:
https://github.com/freeCodeCamp/freeCodeCamp/pull/53612#discussion_r1484110151

**Comment by ShaunSHamilton** [comment]
Why not **not** delete the token?

**Comment by moT01** [comment]
Deleting the token is a security measure - suggested by Mrugesh.

**Comment by moT01** [comment]
Closing as stale.
