### ISSUE TITLE
New English curriculum titles are not displayed appropriately in timeline

### ISSUE THREAD

**Issue by mmatsumoto1026** [freeCodeCamp/freeCodeCamp#53643]
### Describe the Issue

In the timeline table on the profile page, the title of each task of the New English curriculum is now displayed as `Task 3`, but each of the three courses contains a task with the same name, so campers can not recognize at a glance which course's task have been completed.

### Affected Page

/username

### Steps to Reproduce

1. Go to profile page after solving a task of new English curriculum
2. Scroll down to the table under the `Timeline` heading
3. See the curriculum title 

### Expected behavior

Like the Steps in new RWD or new JS Algorithms and Data Structures Certification, the title will be displayed with block name title and a dash.

### Screenshots

<details>
<summary>The title of each task of New English Curriculum on the timeline table</summary>

![New_English_curriculum_title_on_the_timeline_table](https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/384b61a8-25f4-452b-8657-a36b0dd4a00d)
</details>

### System

- Device: Laptop
- OS: Windows 11 Home
- Browser: Chrome
- Version: 121.0.6167.161 (Official Build) (64-bit)

**Comment by moT01** [comment]
Thanks for pointing this out @mmatsumoto1026. I think that solution works. We want to make it so the English challenges display the block and the challenge title in the same way the RWD and new JS do. One issue with that is that we would get a pretty long title on those dialogue challenges. e.g. In the image above "Dialogue 1: Maria Introduces Herself to Tom" would probably become "Learn Greetings in your First Day at the Office - Dialogue 1: Maria Introduces Herself to Tom". I think that's fine though. I'm going to add the help wanted label.

**Comment by netanelben** [comment]
Im going to take a look at this one 👀

**Comment by arunkumar0398** [comment]
Is there still anyone working on this?

**Comment by Re1nGer** [comment]
> Thanks for pointing this out @mmatsumoto1026. I think that solution works. We want to make it so the English challenges display the block and the challenge title in the same way the RWD and new JS do. One issue with that is that we would get a pretty long title on those dialogue challenges. e.g. In the image above "Dialogue 1: Maria Introduces Herself to Tom" would probably become "Learn Greetings in your First Day at the Office - Dialogue 1: Maria Introduces Herself to Tom". I think that's fine though. I'm going to add the help wanted label.

So, just to clarify: Task 1 in the block 'Learn Greetings in your First Day at the Office' then would be 'Learn Greetings in your First Day at the Office - Task 1', is that correct interpretation ?

**Comment by abhinavkgrd** [comment]
Heyy @moT01 , I would like to work on this. I have setup the gitpod environment using the contribution guide.

But, I am facing a issue. when I try to open the profile page for the default logged in test account. It shows the Gatsby.js development 404 page. Can you please help me with this. Is there some env config i need to change to fix this ?

**Comment by mmatsumoto1026** [comment]
Thanks for your interest in this issue.

> But, I am facing a issue. when I try to open the profile page for the default logged in test account. It shows the Gatsby.js development 404 page. Can you please help me with this. Is there some env config i need to change to fix this ?

When I faced a similar issue before, I was able to resolve it by referring to [this comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/50912#pullrequestreview-1517025630).
