### ISSUE TITLE
Learn Functional Programming by Building a Spreadsheet - `has2` not recognized as spreadsheet function

### ISSUE THREAD

**Issue by DBailey0629** [freeCodeCamp/freeCodeCamp#53641]
### Describe the Issue

The spreadsheet function "has2" (first defined in step 97 as of Feb 10) does not work in the spreadsheet page. I think this is because the regex in the function applyFunction doesn't recognize it as a function.
The regex:
const functionCall = /([a-z]*)\(([0-9., ]*)\)(?!.*\()/i;

I think the regex needs to change to: /([a-z2]*)\(([0-9., ]*)\)(?!.*\()/i
or: /([a-z0-9]*)\(([0-9., ]*)\)(?!.*\()/i

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-97

### Your code

```
const functionCall = /([a-z]*)\(([0-9., ]*)\)(?!.*\()/i;


```

### Expected behavior

When a formula in the spreadsheet is:
=has2(1,2,3)
The cell updates to "true"
When formula is
=has2(4,5,6)
The cell updates to "false"

### System

- Device: [ Laptop]
- OS: [MacOS 14.3]
- Browser: [Chrome]
- Version: [120]

**Comment by Nitz2611** [comment]
I agree that it needs to be adjusted to properly recognize the "has2" function.
To resolve this issue, I propose the following regex adjustment:
`const functionCall = /([a-z0-9]*)\((([0-9., ]*|)\))(?![^(]*\()/i`
