### ISSUE TITLE
Get all the expected results, but not pass the test. Bonfire: Seek and Destroy

### ISSUE THREAD

**Issue by KyraYang** [FreeCodeCamp/FreeCodeCamp#5365]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20var%20from%20%3D%20Array.prototype.slice.call(arguments%2C0%2C1).toString().split('%2C')%3B%0A%20%20var%20del%20%3D%20Array.prototype.slice.call(arguments%2C1)%3B%0A%20%20function%20same(fro)%7B%0A%20%20%20%20return%20fro%20!%3D%20this%3B%7D%0A%20%20for%20(i%3D0%3Bi%3Cdel.length%3Bi%2B%2B)%7B%0A%20%20%20%20from%20%3D%20from.filter(same%2Cdel%5Bi%5D)%3B%0A%20%20%7D%0A%20%20return%20from%3B%20%0A%7D%0Adestroyer(%5B3%2C%205%2C%201%2C%202%2C%202%5D%2C%202%2C%203%2C%205)%3B%0A) has an issue.
My code is here,
```
function destroyer(arr) {
  // Remove all the values
  var from = Array.prototype.slice.call(arguments,0,1).toString().split(',');
  var del = Array.prototype.slice.call(arguments,1);
  function same(fro){
    return fro != this;}
  for (i=0;i<del.length;i++){
    from = from.filter(same,del[i]);
  }
  return from; 
}
destroyer([1, 2, 3, 1, 2, 3], 2, 3);
```
I tried all the example and get the expected return, but still can't pass the test. Please help!

**Comment by ltegman** [comment]
You're turning the array elements into strings, but the test cases expect that they still be numbers.

Thanks and happy coding!
