### ISSUE TITLE
script tag placing in JavaScript course

### ISSUE THREAD

**Issue by bwyoungy** [freeCodeCamp/freeCodeCamp#53665]
### Describe the Issue

In the freeCodeCamp curriculum, you teach to place the `<script>` tag on the HTML page at the end of the `<body>` tag, so that it loads after the HTML. 
In a different course I took, we were taught to use the attribute `defer` on the tag and that way can leave it in the `<head>` tag. (for example: `<script src="script.js" defer></script>`)
When I tried doing so while working on the certification programs, it didn't work, while it did when I ran the same code on my computer externally from the freeCodeCamp site.

I was wondering why it's like this (and also if it should be fixed)

### Affected Page

All JavaScript course programs

### Steps to Reproduce

1. Go to a certification program in the JavaScript course
2. use `<script src="script.js" defer></script>` in the `<head>` tag
3. The script won't run after the HTML, as it should due to defer

### Expected behavior

I'd expect a script tag with defer to run after the HTML, even if placed in the head tag

### System

- Device: VivioBook ASUS Laptop
- OS: Windows 11 Home
- Browser: Mozilla Firefox

**Comment by ilenia-magoni** [comment]
That's probably for how the JavaScript is executed in the browser, notice that we don't have a real filesystem to work with, as the code written in the editor has to be executed and displayed in the browser

**Comment by Sembauke** [comment]
We have a weird way of handling the code, the way you learnt it is correct.
