### ISSUE TITLE
Unclear explanation of the charset attribute in Learn HTML by Building a Cat Photo App: Step 69 

### ISSUE THREAD

**Issue by htmlHxcker** [freeCodeCamp/freeCodeCamp#53666]
### Describe the Issue

This particular lesson does not correctly explain the `charset` attribute. It says _"Tell the browser to parse the markup into multiple languages by creating a meta element as a child of the head element. Set its charset attribute to UTF-8."_ which implies that the charset attribute can automatically translate the markup. 

Compare this with the explanation from Learn Basic CSS by Building a Cafe Menu: Step 3 which says _"Inside the head element, nest a meta element with an attribute named charset set to the value utf-8 to tell the browser how to encode characters for the page. Note that meta elements are self-closing."_

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-69

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
I agree with updating the text here

Let's go with this change

````md
You can set browser behavior by adding self-closing `meta` elements in the `head`. Here's an example:

```html
<meta attribute="value">
```

Inside the `head` element, nest a `meta` element with an attribute named `charset`. Set to the value `utf-8` which tells the browser how to encode characters for the page. 

Note that `meta` elements are self-closing.
````
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/62bb4009e3458a128ff57d5d.md

Happy coding
