### ISSUE TITLE
Update tests and description for step 8 of music player

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53676]
### Describe the Issue

I think the description and tests could be clearer.

Here is the updated description:

```md
Your music player should keep track of the songs, the current song playing, and the time of the current song. To do this, you will need to create an object to store this information.

Start by using the `let` keyword to declare a new variable called `userData`. Assign an empty object to your `userData` variable.
```
Also, the current tests use a singular regex. 

In this case, there are other assert methods that we could use here that also help make the tests more granular.

Here are my proposed updates the tests.

````md
You should have a variable called `userData`.

```js
assert.isDefined(userData);
```

You should use the `let` keyword to create the `userData` variable.

```js
assert.match(code, /let\s+userData\s*=/)
```

You should assign an empty object to your `userData` variable.

```js
assert.deepEqual(userData, {});
```
````

Double check on your own to make sure the tests work
If you want to use other assert methods that is fine too. 👍 

Just make sure we are not using just one regex solution. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-8

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by srikanth-kandi** [comment]
> Also, the current tests use a singular regex.
> 
> In this case, there are other assert methods that we could use here that also help make the tests more granular.
> 
> Here are my proposed updates the tests.
>
> Double check on your own to make sure the tests work If you want to use other assert methods that is fine too. 👍
> 
> Just make sure we are not using just one regex solution.

Hello @jdwilkin4, do you mean to completely replace the current tests with proposed tests or to append proposed tests to existing ones?

**Comment by jdwilkin4** [comment]
@srikanth-kandi 

I want the old tests completely replaced with new ones.

We shouldn't have just one test for this.

We should have tests for the following:

1. check to make sure the camper has created the variable
2. check to make sure the camper is using let to create the new variable
3. check to make sure the camper is assigning an empty object to that new variable

These changes will make the tests more granular and help campers understand where they went wrong.
Plus using other built in assert methods in this case is better then just one singular regex test that tests for everything 👍
