### ISSUE TITLE
Multiple Conditional (Ternary) Operators test case failed

### ISSUE THREAD

**Issue by Zydiag** [freeCodeCamp/freeCodeCamp#53681]
### Describe the Issue

test case failed while completing challange `Use Multiple Conditional (Ternary) Operators`

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-multiple-conditional-ternary-operators

### Your code

```js

function checkSign(num) {
  //return num <0 ?  "negative" : num>0 ? "positive" : "zero"
  return num >=0 ?  num>0 ? "positive" : "zero" :  "negative" 
}

checkSign(10);

```

### Expected behavior

the second case should have passed the test case but it failed the following
- should use multiple conditional operators

### System

- Device: [Laptop]
- OS: [Fedora workstation 39]
- Browser: [Thorium]

**Comment by ketansahugit** [comment]
@Zydiag Agreed, the solution seems correct and should have been accepted. I've addressed this issue in my pull request. Thanks for bringing it up!

**Comment by Zydiag** [comment]
hi @huyenltnguyen I think i mistook it
when learning it mentioned using multiple ternary operator. I used multiple of them as It wasn't clear that it should be at the end or not 
It make sense from the if else logic that mentioned in the docs. 
sorry i should have been more careful

**Comment by ojeytonwilliams** [comment]
It's a bit of an odd question. It asks learners to format the ternary, and then doesn't check the formatting, and it rejects solutions (like this one) that do include multiple ternaries.

I think it's fine if either a) the tests accept this solution or b) the tests reject it, but are clear about why. Using @huyenltnguyen's example:

> The ternaries must follow the pattern of `findGreaterOrEqual` i.e. `conditionOne ? valueIfConditionOneIsTrue : conditionTwo ? valueIfConditionTwoIsTrue : valueIfAllConditionsAreFalse`"
