### ISSUE TITLE
Grammatical error in instructions - odin project, recipe page

### ISSUE THREAD

**Issue by franciscomelov** [freeCodeCamp/freeCodeCamp#53696]
### Describe the Issue

error:
`You should have a <ol> with the the steps as the list items <li>.`

### Affected Page

https://www.freecodecamp.org/learn/the-odin-project/top-build-a-recipe-project/top-build-a-recipe-project

### Your code

```



```

### Expected behavior

it should be:
`You should have a <ol> with the steps as the list items <li>`

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/16-the-odin-project/top-build-a-recipe-project/top-build-a-recipe-project.md

## Corrections that need to be made

Remove the duplicate word `the` from this hint text here
<img width="581" alt="Screenshot 2024-02-13 at 6 53 28 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/ae44b4f7-013e-4b43-91d6-ceb39d454067">



Happy coding
