### ISSUE TITLE
Update description and tests for step 34 of music player

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53701]
### Describe the Issue

The step asks campers to check if `userData?.currentSong` is `null`. 
But I don't see why we need to just check for null here. 

This should also be an acceptable answer

```js
if (!userData?.currentSong) {
    playSong(userData?.songs[0].id);
}

```

I don't see the need to only check for null.
We should just check if `userData?.currentSong` is falsey. That will allow for multiple correct answers instead of one.

Update the description and tests here to allow for multiple valid conditions instead of just one.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-34

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Uhm, is changing seed code for further steps required? It's not mentioned, but changing description to _falsey_ kind of implies that.

**Comment by jdwilkin4** [comment]
The goal of this issue is to allow for multiple correct answers instead of just `userData?.currentSong === null`
So it is fine if the rest of the steps use the `userData?.currentSong === null` in the seed code as long as campers are allowed to have answers like this 

```js
if (!userData?.currentSong) {
    playSong(userData?.songs[0].id);
}
```
