### ISSUE TITLE
Missing explanation for newly presented code - Step 63 - JS Beta Certification - Role Playing Game

### ISSUE THREAD

**Issue by leta91** [freeCodeCamp/freeCodeCamp#53710]
### Describe the Issue

Hi,
I noticed that the code within the `update(location)` appears all of a sudden without an explanation

The last time that the `update(location)` function was presented, it was empty 
(Step 50 https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-50 )  

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-63

### Your code

```
function update(location) {
  button1.innerText = "Go to store";
  button2.innerText = "Go to cave";
  button3.innerText = "Fight dragon";
  button1.onclick = goStore;
  button2.onclick = goCave;
  button3.onclick = fightDragon;
  text.innerText = "You are in the town square. You see a sign that says \"Store\".";
}
```

### Expected behavior

I think that the code within `update(location)` should have a brief explanation on why the code within was automatically added in this step

### Screenshots

![fCC-step63](https://github.com/freeCodeCamp/freeCodeCamp/assets/109817389/4faa4d5b-3f7d-41c1-ae52-e9ce42580c69)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Take a look at the step 59 - https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-59, isn't that what you are asking for?

**Comment by leta91** [comment]
@gikf I forgot about step 59, thanks
I am going to close this issue
