### ISSUE TITLE
Stuck at Bonfire: Missing letters

### ISSUE THREAD

**Issue by ThijsHermans** [FreeCodeCamp/FreeCodeCamp#5371]
Challenge [Bonfire: Missing letters](http://www.freecodecamp.com/challenges/bonfire-missing-letters#?solution=function%20fearNotLetter(str)%20%7B%0A%20%20var%20alphabet%20%3D%20%22abcdefghijklmnopqrstuvwxyz%22%3B%0A%20%20var%20iBegin%20%3D%20alphabet.indexOf(str.split(%22%22)%5B0%5D)%3B%0A%20%20var%20corr%20%3D%200%3B%0A%20%20var%20output%20%3D%20%5B%5D%3B%0A%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(alphabet.indexOf(str.split(%22%22)%5Bi%5D)%20!%3D%3D%20(iBegin%20%2B%20i%20%2B%20corr))%20%7B%0A%20%20%20%20%20%20%20%20output.push(alphabet.split(%22%22)%5BiBegin%20%2B%20i%20%2B%20corr%5D)%3B%0A%20%20%20%20%20%20%20%20corr%20%3D%20corr%20%2B%201%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20if%20(output%5B0%5D%20%3D%3D%3D%20%22%22)%20%7B%0A%20%20%20%20return%20undefined%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20output%3B%0A%7D%0A%0AfearNotLetter(%22abce%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

Dear FCC staff, 

the code below gives the correct answers to all questions, yet somehow, none of the grading marks goes green. Is this a bug or am I doing something wrong?

My code:
```javascript
function fearNotLetter(str) {
  var alphabet = "abcdefghijklmnopqrstuvwxyz";
  var iBegin = alphabet.indexOf(str.split("")[0]);
  var corr = 0;
  var output = [];

  for (var i = 0; i < str.length; i++) {
    if (alphabet.indexOf(str.split("")[i]) !== (iBegin + i + corr)) {
        output.push(alphabet.split("")[iBegin + i + corr]);
        corr = corr + 1;
        }
  }
  
  if (output[0] === "") {
    return undefined;
  }
  
  return output;
}

fearNotLetter("abce");
```

Kind regards,

Thijs

**Comment by ltegman** [comment]
Your code is returning an array when it should be returning a string.

Thanks and happy coding!
