### ISSUE TITLE
allow tests to run without source code link

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#53715]
For the "Back 4" certification projects, the source code URL is a required input to submit.

However, it would be nice to allow the tests to still run without the link being there. That is, currently, a link has to be provided before the tests can run:

<img width="613" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/984a1cbb-5e64-44b2-b06a-1c3a7179798a">

The reason this would be useful is, when Campers are developing, they might not have a public repo with their solution pushed. Once they have something working, they might push their work.

**Comment by lasjorg** [comment]
It would also be useful when helping people with their code. As it is now, it's just more work.

**Comment by naomi-lgbt** [comment]
These challenges still pop the "Submit and Complete" modal, yes?

If so, that modal triggers the API call. We could check if there's a source code input in the form data, and if so assert it is not empty?

**Comment by ShaunSHamilton** [comment]
> We could check if there's a source code input in the form data, and if so assert it is not empty?

Yes. This is already possible. We do this elsewhere in the form config.
