### ISSUE TITLE
JS Palindrome Checker Preview Displays White Screen

### ISSUE THREAD

**Issue by Mezalyth** [freeCodeCamp/freeCodeCamp#53727]
### Describe the Issue

JavaScript Algorithms and Data Structures > Build a Palindrome Checker Project
2/13/2024, the preview window displayed the expected content and styles.
2/14/2024, the preview only shows a white screen.
Other projects and past challenges in the same curriculum display normally.
Editing the code in any of the text boxes does not refresh or update the preview. The console does get updated.
<img width="2545" alt="Screenshot 2024-02-14 at 1 27 19 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/86799855/defa5988-cc2e-4fdd-9004-c826f7521042">

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-palindrome-checker-project/build-a-palindrome-checker

### Your code

HTML
```
<head>
  <title>Palindrome Checker</title>
  <link rel="stylesheet" href="./styles.css">
</head>

<body>
  <h1 class="title">Palindrome Checker</h1>
  <p><strong>Enter a word, phrase, or string of numbers here to check if it's a palindrome!</strong></p>
  <p>A palindrome is a word or phrase that can be read the same way forwards and backwards, <em>ignoring punctuation, case, and spacing.</em></p>
  <form>
  <input id="text-input"></input>
  <button id="check-btn">Check</button>
  </form>
   <div id="result"></div>
<script src="./script.js" type="text/javascript"></script>
</body>
```
CSS
```
body {
  color: white;
  background-color: #222;
  margin: 30px;
  text-align: center;
}

input {
  width: 80%;
  margin: 10px;
  padding: 10px;
}

button {
  border-radius:50px;
  padding: 10px 60px;
  margin: 0 auto;
  display: block;
  background-color: #0cf;
}

form {
  padding: 10px;
  border-radius: 6px;
  background-color: #444;
}


```
JS
```
//define variables
const textInput = document.getElementById("text-input");
const checkButton = document.getElementById("check-btn");
const result = document.getElementById("result");

const cleanString = (textInput.value) => {
  return input.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
}


///[^a-zA-Z0-9]/g regex to clean 

/*
- If it has something:
-Take textInput and remove punctuation, case, and spacing
- define as cleanedInput
- get the length of cleanedInput
- find the middle
-- the middle is the length/2
- See if the first half forward is the same as the second half reverse
- need to define firstHalf and secondHalf
- if they are, say it's a palindrome
- if unequal, say not a palindrome
*/

const checkIfPal = () => { //Palindrome checker function

}

//Click button. If blank, error. If not, run script.
checkButton.addEventListener("click", () => {
  if (textInput.value.length <= 0) {
  alert('Please input a value');
  } else { 
    checkIfPal();
  }
}); 



```

### Expected behavior

Expected a preview of the content and styles in the Preview window pane. Screenshot from Codepen below

### Screenshots

![Screenshot 2024-02-14 at 1 30 37 PM](https://github.com/freeCodeCamp/freeCodeCamp/assets/86799855/12e69521-8fa0-4ea2-8333-7d57a5070323)

### System

- Device: Mac Studio 2022
- OS: macOS Sonoma 14.2.1
- Browser: Chrome
- Version: Version 121.0.6167.160 (Official Build) (arm64)

**Comment by gikf** [comment]
Thank you for reporting this issue.

I'm not sure why syntax error is not displayed in console, but `cleanString` function has incorrectly defined parameter.

Instead of asking for help here, please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.

Thank you and happy coding.

**Comment by Mezalyth** [comment]
Sorry, was the assumption that I was asking for code help?

I'm not concerned about my code, that is still in creation and I'm looking
forward to doing the challenge, it's just that I can't because the display
pane is white.

Ignore the code, ignore the console, I supplied it because it was requested
in the support ticket form, but the bug that I have is irrelevant to my
actual skill but more so the fact that the preview does not work.
