### ISSUE TITLE
Python input exception handling

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#53741]
**Describe the bug**
In Python lessons `input` misbehaves when it's in `try` `except` blocks and the learner stops making changes in the editor. The issue is that `except` catches all exceptions, including the `KeyboardInterrupt` that _should_ stop the code executing.

**To Reproduce**
1. Go to any Python lesson, e.g. https://www.freecodecamp.dev/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-3
2. Enter the code below
3. Wait a few minutes
4. See "hi", "why are we here?" repeating in the terminal
5. Click on the terminal
6. Type anything into terminal
7. See it duplicate

```py
while True:
    try:
        name = input('hi')
        print('hello, ', name)
    except:
        print('why are we here?')
        pass
```

**Expected behavior**
If the input times out the terminal should reset (i.e. stop executing python code and send a `{ type: 'stopped' }` message to the main thread)

**Screenshots**
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/15801806/06e727c2-0482-49af-a70e-277f73905200)

**Additional context**
We can work around this when writing projects, by catching named exceptions i.e. `except ValueError:` not `except:`. However this doesn't help if a learner writes code to catch all exceptions.

Finally, `sys.exit()` raises an exception, so doesn't solve the issue. `os._exit` stops pyodide entirely which is a potential solution, since we could simply terminate and recreate the worker in this case.

**Comment by gikf** [comment]
I don't know if that's strange or not, but the exception that's caught is `NetworkError`:
```
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.freecodecamp.dev/python/intercept-input/'
```

> We can work around this when writing projects, by catching named exceptions i.e. `except ValueError:` not `except:`.

As a part of learning always should be emphasized catching specific exceptions.

**Comment by ojeytonwilliams** [comment]
Nope, that's expected. `input` is implemented via a synchronous http request that the worker initiates. Browsers will eventually terminate the request, though, and that raises an exception.

The code, if you're curious:

https://github.com/freeCodeCamp/freeCodeCamp/blob/32e499d6acc5c2ff5c8f0dca2e437d6d90d470bf/tools/client-plugins/browser-scripts/python-worker.ts#L71-L86

> As a part of learning always should be emphasized catching specific exceptions.

That's true, they should. The problem is that our app's behaviour is pretty strange. There's no way for a learner to understand what's going on without digging into our source code.

**Comment by gikf** [comment]
I'm still confused by this. However problem doesn't seem to lie in catching `KeyboardInterrupt`. `KeyboardInterrupt` is not inheriting from `Exception`, but from `BaseException`, so this shouldn't behave the same way, but it does:

```python
while True:
    try:
        name = input('hi')
        print('hello, ', name)
    except Exception:
        print('why are we here?')
        pass
```

As a side note - is it even possible to use `Ctrl + C` in the fCC's terminal on page as an interrupt? I haven't had much luck with that.
