### ISSUE TITLE
Update code example for ternary operator in step 146 of RPG project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53754]
### Describe the Issue

We are still getting a lot of people on the forum confused on how to do step 146 of RPG project.
They are looking to the current example and returning strings when the directions say to return the variable `hit` and the number `0`.

In order to clear up confusion, we should chose a different example.
I know that this is updated code example is very similar to what they need to do in the step. But I think that is what they need at this stage. 

## updated code example
````md
Here is an example of returning a value using an `if-else` statement and a refactored example using a ternary operator:

```js
// if-else statement

if (score > 0) {
  return score
} else {
  return default_score
}

// ternary operator
score > 0 ? score : default_score

```
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-146

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa1eec891ed731db227a36.md

Happy coding

**Comment by Prasad-JB** [comment]
Hi there! I'd love to help improve this example for clarity. Could I work on updating the code block to use the actual hit variable (and number 0) instead of strings, as suggested? I’ll make sure the PR follows the contribution guidelines. Thanks!

**Comment by majestic-owl448** [comment]
@Prasad-JB this issue was closed in 2024...
