### ISSUE TITLE
Fix spacing issue for step 33 of football team cards

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53769]
### Describe the Issue

A camper was unable to pass the test with either of the following answers

```js
  <p>Nickname: ${nickname ? nickname : "N/A" }</p>
```
```js
<p>Nickname: ${nickname !== null ? nickname : "N/A" }</p>
```

The issue had to deal with spacing after the `"N/A"`

This has to be fixed because they got the correct answer

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-33

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by KilroyWasHere-cs-j** [comment]
I'd love to take a crack at this. However, I'm struggling to find the relevant files the [page ](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-33). If someone could help point me in the right direction that would be amazing!

**Comment by gikf** [comment]
@KilroyWasHere-cs-j it's here https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-modern-javascript-methods-by-building-football-team-cards/63e9718d7d490bb3940d5a0a.md

**Comment by KilroyWasHere-cs-j** [comment]
@gikf Awesome! I'll take a look later! Thanks again for the help, I much appreciate it!
