### ISSUE TITLE
Original Sample Code is Innacurate

### ISSUE THREAD

**Issue by bitsoda** [FreeCodeCamp/FreeCodeCamp#5376]
Challenge [Waypoint: Iterate Odd Numbers With a For Loop](http://www.freecodecamp.com/challenges/waypoint-iterate-odd-numbers-with-a-for-loop#?solution=var%20ourArray%20%3D%20%5B%5D%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%2010%3B%20i%20%2B%3D%202)%20%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0A%0Avar%20myArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afor%20(var%20i%20%3D%201%3B%20i%20%3C%2010%3B%20i%20%2B%3D%202)%20%7B%0A%20%20myArray.push(i)%3B%0A%7D%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0Aif(typeof%20myArray%20!%3D%3D%20%22undefined%22)%7B(function()%7Breturn%20myArray%3B%7D)()%3B%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 7520.63.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the sidebar text description of how to solve the Waypoint it reads:

"Let's change our initialization and final-expression so we can count by odd numbers."

The original sample code is:

    for (var i = 0; i < 10; i += 2) 

which presents an issue because the final-expression is already set to 2, so the user won't have to change it like the waypoint asks us to.

The original sample code should be changed to:

    for (var i = 0; i < 10; i += 1)

**Comment by raisedadead** [comment]
IMO, this is a problem with the original sample code, in the editor window (Can be seen if you do areset). 

Instead of below
```javascript
for (var i = 0; i < 10; i += 2) 
````
it should be
```javascript
for (var i = 0; i < 10; i += 1) 
````
because the point of the exercise is to illustrate the significance of altering the loop iteration by changing the `initialization` and the `final-expression` values.

**Comment by bitsoda** [comment]
Good point, raisedadead. I've edited the subject text to reflect this.

**Comment by SaintPeter** [comment]
I concur.  I'm editing these waypoints right now, so this will be resolved in the new Basic Javascript release.
