### ISSUE TITLE
update directions for step 51 of RPG project

### ISSUE THREAD

**Issue by franciscomelov** [freeCodeCamp/freeCodeCamp#53778]
### Describe the Issue

The instructions say:
Create a variable called locations and set it to an empty array.

But the correct answer is:
`const locations = [];`

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-51

### Your code

```



```

### Expected behavior

Shouldn't it say:
Create a constant called locations and set it to an empty array.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
I agree with the change in directions. We should also update the directions to mention the context for what this locations is about. 

I will go ahead and open this up for first timers only contribution

## Note to contributors 
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Changes that need to be made

```md
In your role playing game, you will be able to visit different locations like the store, the cave and the town square. You will need to create a data structure that will hold the different locations. 

Use `const` to create a variable called `locations` and assign it an empty array.
```

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8a929e4260d08093756d2.md

Happy coding
