### ISSUE TITLE
Lack of spacing inside a function somehow disables a loop.

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#5377]
Challenge [Bonfire: Roman Numeral Converter](http://www.freecodecamp.com/challenges/bonfire-roman-numeral-converter) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.

A simple line break makes the difference between pass or fail in this bonfire. 

Somehow having that ```return m;``` in a separate line, enables the 2k and 3k results.
Am I unknowingly missing a weird rule in JS?

<img width="1375" alt="screen shot 2015-12-19 at 15 24 30" src="https://cloud.githubusercontent.com/assets/2107110/11915091/cf1cb990-a664-11e5-90c8-82cc258e7c70.png">
<img width="1391" alt="screen shot 2015-12-19 at 15 26 20" src="https://cloud.githubusercontent.com/assets/2107110/11915097/e876a6bc-a664-11e5-84a4-6a7c8a3019d6.png">

My ugly code, for reproduction:
```javascript
function convert(num) {
  num=num.toString();
  var rPlaces = [['I','V','X'],['X','L','C'],['C','D','M']], r='', length=num.length, place=0,m='',
  ms = function(placeVal, place){
    for(var x=1;x<=placeVal*Math.pow(10,place-3);x++)m+='M'; return m;};
    
  return r+=num.split('')
          .map(function(placeVal,index){place=length-index-1;
            return (place>2)?(ms(placeVal,place)):
              (placeVal==1)?rPlaces[place][0]:
              (placeVal==2)?rPlaces[place][0]+rPlaces[place][0]:
              (placeVal==3)?rPlaces[place][0]+rPlaces[place][0]+rPlaces[place][0]:
              (placeVal==4)?rPlaces[place][0]+rPlaces[place][1]:
              (placeVal==5)?rPlaces[place][1]:
              (placeVal==6)?rPlaces[place][1]+rPlaces[place][0]:
              (placeVal==7)?rPlaces[place][1]+rPlaces[place][0]+rPlaces[place][0]:
              (placeVal==8)?rPlaces[place][1]+rPlaces[place][0]+rPlaces[place][0]+rPlaces[place][0]:
              (placeVal==9)?rPlaces[place][0]+rPlaces[place][2]:null;
              }).join('');   
    }
convert(36);

```

**Comment by SaintPeter** [comment]
Confirmed.

This is an issue with our loop protect code.  When you scrunch your code up like that it can't really get a word in edgewise.  If you use curly braces around `{m+='M';}`, it works.  It's a best practice to put curly braces around the statements for if and for elements, even if they are only one line.  

Honestly, your code is so ugly that I don't think this is something we are going to spend time on trying to fix this.  It took me several minutes to even figure out what your code was trying to do.  This is not "code golf", you don't get extra credit for fitting everything onto one line.  Code for readability and maintainability.

Thanks and happy coding.

**Comment by hallaathrad** [comment]
Thanks for the advice, and yes, I agree with you entirely :) My code is horrible... somewhat on purpose as I do indeed frequently play "code golf", just to see  what I can get away with. 
Loved the term though, btw. Very appropriate. Didn't know it was "a thing".

About the weird bug, at least now I know it is known and tolerated by you, and not just an ignorant me misunderstanding JS capabilities.
