### ISSUE TITLE
Cash Register Project: Directions require improperly represented cents 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#53792]
### Describe the Issue

It feels improper for this kind of challenge to accept a decimal like `19.5` with only one decimal point. Money has a significant figure amount of two decimals points, and it is more symbolic of actual activities. It's not a major issue but it would be feel more correct. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register

### Your code

```
N/A 
```

### Expected behavior

Numbers with two decimal places should be used in the directions i.e `19.5` should be `19.50`. 

### System

- Device: Desktop
- OS: Windows 10 
- Browser: Firefox
- Version: 122.0.1

**Comment by naomi-lgbt** [comment]
I believe this was to maintain parity with the old certification requirements, where the expected array had numbers:

```js
[
  ["PENNY", 1.01],
  ["NICKEL", 2.05],
  ["DIME", 3.1],
  ["QUARTER", 4.25],
  ["ONE", 90],
  ["FIVE", 55],
  ["TEN", 20],
  ["TWENTY", 60],
  ["ONE HUNDRED", 100]
]
```

It is worth noting that in general, the user stories for the new certifications match the user stories for the old certifications, requiring only the minimal changes necessary to get the DOM tests to pass.

The idea is that a camper can come back, take their old cert code, and resubmit under the new cert without having to rewrite the entire project.

**Comment by a2937** [comment]
Oh I see. We can carry on then.
