### ISSUE TITLE
Learn Basic CSS by Building a Basic Cafe Menu: instructions are incomplete in step 17

### ISSUE THREAD

**Issue by jotas6** [freeCodeCamp/freeCodeCamp#53791]
### Describe the Issue

Step 17, has the following instructions 

<img width="580" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/80299581/95a1b7a4-7959-40ff-b712-a8dd831fa749">

It can be seen that `<meta name="viewport" content="width=device-width,` is incomplete.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-17

### Your code

```
<meta name="viewport" content="width=device-width,
```
Not sure how relevant this is for this issue, but I am placing the code here since it is required

### Expected behavior

Pass the test. Instead, the following is suggested:

> Your `meta` element should have a `content` attribute with a value of `width=device-width, initial-scale=1.0`.

Which is how I realized that the instructions were incomplete at first. Changing the code for what is suggested makes the test pass.

### System

- Device: MacBook Air M2, 2022
- OS: Sonoma 14.2.1
- Browser: Safari
- Version: 17.2.1

**Comment by naomi-lgbt** [comment]
<img width="306" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/9e66b63f-d080-4572-95dd-0fe756877df4">

It looks like your browser has decided not to display the scrollbar. It is not an incomplete code snippet.

**Comment by jotas6** [comment]
Yes, I just tried it on Firefox and the scrollbar is there.

Thank you!

**Comment by naomi-lgbt** [comment]
Glad I could help!
