### ISSUE TITLE
Shofthand operations not working in "Learn Basic JavaScript by Building a Role Playing Game" Step 71 and 72

### ISSUE THREAD

**Issue by AkhilTrivediX** [freeCodeCamp/freeCodeCamp#53793]
### Describe the Issue

The step states we have to add Health and reduce gold expected as:
`gold = gold - 10;`
`health = health - 10;`

But tests should also pass for shorthand operators:
`gold -= 10;`
`health -= 10;`
It shows failed tests and may cause confusion among learners that shorthand are not used in javascript.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-73

### Your code

```
function buyHealth() {
  gold -= 10;
  health+=10;
}
```

### Expected behavior

I expected tests to passed with shorthand operators or we can mention is problem statement that shorthand operators are not allowed.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Brave

**Comment by naomi-lgbt** [comment]
This is intentional. Complex assignment operators for addition and subtraction are taught in step 74:

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-74
