### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text has an issue 

### ISSUE THREAD

**Issue by Benlewis3k** [FreeCodeCamp/freecodecamp#538]
When I was going through the challenges, "Go to my next challenge" skipped over this challenge.

**Comment by QuincyLarson** [comment]
Thank you for reporting this. This is seems to be caused by accidentally clicking the "Go to my next challenge" button more than once. We are fixing it so this can't happen in the future.
