### ISSUE TITLE
Quality assurance challenges on Gitpod

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53801]
### Describe the Issue

It seems like you have to comment out all the failing tests on Gitpod. Unlike when running it locally or using Replit.

Not sure if there is anything we can do about it or if we have to update the challenge with that information.

---

Also, I didn't check any other challenges. I assume some testing was done on the challenges before we made the switch to Gitpod?

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/

### Your code

```



```

### Expected behavior

Challenges running on Gitpod should work the same as before the switch, or we should warn about it.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/quality-assurance-and-testing-with-chai-learn-how-javascript-assertions-work/673387

**Comment by lasjorg** [comment]
As an aside, why is there a VS Code theme config in the repo files?

**Comment by maruthiaws0808** [comment]
As an aside, w
hy is there a VS Code theme config in the repo files?

**Comment by ShaunSHamilton** [comment]
I have no issue completing the challenges. No commenting out of irrelevant code required.

**Comment by lasjorg** [comment]
Maybe there is just some inconsistency. I tried it one time and it failed but the next time (new GitPod) it worked just fine.

As an aside, I would suggest we add `--watch` to the start script (or use nodemon) just to avoid issues with people forgetting to restart the server. I have seen others on the forum make that mistake more than once. Although this is not anything specific to Gitpod.

**Comment by lasjorg** [comment]
@ilenia-magoni but why? I find it very jarring to have my theme replaced.

**Comment by ilenia-magoni** [comment]
@lasjorg to make it feel a continuation of the rest of freeCodeCamp I think. I suggest a new issue if you want to continue discussing this

**Comment by ShaunSHamilton** [comment]
> As an aside, I would suggest we add --watch to the start script (or use nodemon) just to avoid issues with people forgetting to restart the server. I have seen others on the forum make that mistake more than once. Although this is not anything specific to Gitpod.

We specifically did not add `nodemon` or similar to these, and actually spent a while removing it from many of these boilerplates a few years back.

**Comment by lasjorg** [comment]
> We specifically did not add `nodemon` or similar to these, and actually spent a while removing it from many of these boilerplates a few years back.

Just to get rid of the dependency or what?

Because the `--watch` flag is well supported now. What about adding a `dev` script to the backend projects if nothing else?

I don't see the benefit of forcing people to restart the server manually after each change, I don't know anyone who prefers to work like that. I also think forgetting to restart the server between changes is a fairly common issue for beginners.

By the way, you didn't close the issue.

**Comment by ShaunSHamilton** [comment]
> Just to get rid of the dependency or what?

Yes. `npm run start` is not difficult, and if Campers want to implement their own _watcher_ then that is easy enough to do.

We did not want the confusion that could come with automatically restarting. It is not a "natural" thing. So, I definitely would not add it to the first project.

Besides, we have never had `nodemon` for most of the projects.

> By the way, you didn't close the issue.

😅
