### ISSUE TITLE
Convoluted Flip Code

### ISSUE THREAD

**Issue by bitsoda** [FreeCodeCamp/FreeCodeCamp#5380]
Challenge [Waypoint: Use Conditional Logic with If and Else Statements](http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-if-and-else-statements#?solution=var%20flip%20%3D%20Math.floor(Math.random()%20*%20(1%20-%200%20%2B%201))%20%2B%200%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Aif%20(flip%20%3D%3D%3D%200)%20%7B%0A%20%20return%20%22heads%22%3B%0A%7D%20else%20%7Breturn%20%22tails%22%3B%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0Avar%20result%20%3D%20myFunction()%3Bif(typeof%20flip%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20flip%20%3D%3D%3D%20%22number%22%20%26%26%20typeof%20result%20!%3D%3D%20%22undefined%22%20%26%26%20typeof%20result%20%3D%3D%3D%20%22string%22)%7B(function(y%2Cz)%7Breturn%20'flip%20%3D%20'%20%2B%20y.toString()%20%2B%20'%2C%20text%20%3D%20'%20%2B%20z%3B%7D)(flip%2C%20result)%3B%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 7520.63.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I'm new to JS, but can't the code for the flip variable be simplified to

    var flip = Math.floor(Math.random() * 2);

instead of

    var flip = Math.floor(Math.random() * (1 - 0 + 1)) + 0;
?

**Comment by AkiraLaine** [comment]
@bitsoda Yeah, it can. I'm gonna open a PR for this.

**Comment by SaintPeter** [comment]
This Waypoint has been completely rewritten.  Should be out at the end of the month.
