### ISSUE TITLE
if and else state waypoint

### ISSUE THREAD

**Issue by iallfree** [FreeCodeCamp/FreeCodeCamp#5381]
I thought I  went through this waypoint already.. but I am having troubles with it- this time.. 
I felt everything was correct. except it wouldn't let me pass the tails flip and if I changed the tails value it wouldn't let me pass the heads..  etc etc.. but  I tried reloading the code to try again and it did this to me..
It didn't load anything back up so I can start fresh.. 

![screenshot 1](https://cloud.githubusercontent.com/assets/16330271/11916118/2c5e7a16-a68e-11e5-9286-1d0ccb9e4788.png)

**Comment by ltegman** [comment]
This waypoint is not broken. If you are struggling with it please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and happy coding!
