### ISSUE TITLE
Should challenge repositories have VS Code theme settings?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53823]
### Describe the Issue

I get the branding or continuation idea but it seems kind of rude to change people's editor theme. I didn't even notice the `.vscode` folder the first time it happened and thought my theme had broken and started to mess with my editor settings.

Anyway, I find it a little intrusive.

### Affected Page

https://github.com/freeCodeCamp/boilerplate-express

### Your code

```



```

### Expected behavior

Not to have my editor theme changed.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by naomi-lgbt** [comment]
That *seems* like it might have been intentional? @ShaunSHamilton?

**Comment by a2937** [comment]
While it is a little rude, this is a great way to set the mood and a reminder that this is a FreeCodeCamp challenge that we're working on rather than a personal project.

**Comment by naomi-lgbt** [comment]
It makes sense for the learner, assuming they're not familiar with gitpod.

A nuisance for devs tho haha

**Comment by a2937** [comment]
There is something else I can note. It doesn't automatically install the theme for the user as I found out when I tried it out on another PC. So honestly it isn't worth it, unless it automatically installs the theme in GitPod.

**Comment by ilenia-magoni** [comment]
It probably made sense in the CodeAlly VMs, and it was kept while doing the migration of all the other projects

**Comment by ojeytonwilliams** [comment]
> affects the workspace - NOT the user settings

I think the issue is precedence. Even though it doesn't touch user settings, it will still override them for this workspace.

**Comment by ShaunSHamilton** [comment]
> I think the issue is precedence.

Right. I was just clarifying this was specifically done just for freeCodeCamp projects.

**Comment by lasjorg** [comment]
I wouldn't mind it if it only affected pre-made setups but I do mind it when I clone down a repo and it changes my theme.

For people who often have to clone down the repos when helping learners with their projects, it can get annoying.

**Comment by ojeytonwilliams** [comment]
I guess one option would be to add a Gitpod task to create the settings.json if it doesn't exist.

That's a bit more work, but might be an okay compromise.

**Comment by a2937** [comment]
> I wouldn't mind it if it only affected pre-made setups but I do mind it when I clone down a repo and it changes my theme.
> 
> For people who often have to clone down the repos when helping learners with their projects, it can get annoying.


I can doubly verify. I can even explain the issue I've had with this. 

1) Download the repo to the computer 
2) Open up the folder in a local Visual Studio Code without FreeCodeCamp Dark Theme installed, but some other color extension. 
3) Observe as the background turns bright white 
4) Time gets spent hunting down the original color theme extension.

**Comment by ilenia-magoni** [comment]
I'm opening this for help, for removing the theme

**Comment by ShaunSHamilton** [comment]
Are we wanting to remove this for all boilerplates?

**Comment by lasjorg** [comment]
My vote would be yes, at least for the repos.

If the theme can be implemented as part of a Gitpod task/config as suggested, that would be fine. I don't mind the Gitpod boilerplate's having a theme.

**Comment by a2937** [comment]
> My vote would be yes, at least for the repos.
> 
> If the theme can be implemented as part of a Gitpod task/config as suggested, that would be fine. I don't mind the Gitpod boilerplate's having a theme.

Would something like this work? 

```image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - before: mkdir .vscode | echo -e '{\n"workbench.colorTheme":"freeCodeCamp Dark Theme"\n}' >> .vscode/settings.json
  - init: npm install
    command: npm run start 

vscode:
  extensions:
    - https://github.com/freeCodeCamp/freecodecamp-dark-vscode-theme/releases/download/v1.0.0/freecodecamp-dark-vscode-theme-1.0.0.vsix```

**Comment by a2937** [comment]
This way we're setting the setting before gitpod officially starts.

**Comment by ShaunSHamilton** [comment]
@a2937 I do not think it is worth the effort.  We should just remove the files, and keep the config as simple as possible.

**Comment by Ayush02jain** [comment]
Although it depends on the user but sometimes I also feel frustrating as I customized the editor theme according to me.

**Comment by lasjorg** [comment]
Let's not do that again :dizzy_face:
