### ISSUE TITLE
[English course] Play button isn't a square

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#53839]
### Describe the Issue

The width and height of the play button aren't equal. The issue is invisible unless the focus outline shows up.

<img width="999" alt="Screenshot 2024-02-23 at 23 09 17" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/7925915c-61d0-4167-b9dd-2e71bbae6511">

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-1

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-1
2. Tab to the play button
3. See that the focus outline isn't a square

### Expected behavior

The issue here is because the image isn't a square, and `button` just scales with its content (the image). We would want to use CSS to crop the image to a square.

**Comment by areebqazi** [comment]
@huyenltnguyen if possible can you tell me about the where i can find the file in the project as I am new to contributions and I dont understand the codebase quite well but I can definitely fix the issue .
