### ISSUE TITLE
In Javascript course, replace macaroons with macarons.

### ISSUE THREAD

**Issue by DBailey0629** [freeCodeCamp/freeCodeCamp#53859]
### Describe the Issue

Hi! French macarons are spelled with a single "o". Since it is part of the code from step 7, all steps from 7 to 60 need updating.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-oop-by-building-a-shopping-cart/step-7

### Your code

```
const products = [
  {
    id: 1,
    name: "Vanilla Cupcakes (6 Pack)",
    price: 12.99,
    category: "Cupcake",
  },
  {
    id: 2,
    name: "French Macaroon",
    price: 3.99,
    category: "Macaroon",
  },
  {
    id: 3,
    name: "Pumpkin Cupcake",
    price: 3.99,
    category: "Cupcake",
  },
  {
    id: 4,
    name: "Chocolate Cupcake",
    price: 5.99,
    category: "Cupcake",
  },
  {
    id: 5,
    name: "Chocolate Pretzels (4 Pack)",
    price: 10.99,
    category: "Pretzel",
  },
  {
    id: 6,
    name: "Strawberry Ice Cream",
    price: 2.99,
    category: "Ice Cream",
  },
  {
    id: 7,
    name: "Chocolate Macaroons (4 Pack)",
    price: 9.99,
    category: "Macaroon",
  },
  {
    id: 8,
    name: "Strawberry Pretzel",
    price: 4.99,
    category: "Pretzel",
  },
  {
    id: 9,
    name: "Butter Pecan Ice Cream",
    price: 2.99,
    category: "Ice Cream",
  },
  {
    id: 10,
    name: "Rocky Road Ice Cream",
    price: 2.99,
    category: "Ice Cream",
  },
  {
    id: 11,
    name: "Vanilla Macaroons (5 Pack)",
    price: 11.99,
    category: "Macaroon",
  },
  {
    id: 12,
    name: "Lemon Cupcakes (4 Pack)",
    price: 12.99,
    category: "Cupcake",
  },
];


```

### Expected behavior

All instances of "macaroon" need to be replaced with "macaron".

### System

- Device:  Laptop]
- OS: macOS
- Browser: chrome
- Version: 121

**Comment by JoyShaheb** [comment]
@jdwilkin4 looks funny ? how did we miss that while development ? also I'm not sure about the food spelling as well ?

**Comment by jdwilkin4** [comment]
@JoyShaheb 

There are two types of cookies (macaron and macaroon). You can learn more about it here
https://www.foodandwine.com/macaron-vs-macaroons-7373000

In development, we accidentally referenced the other cookie of macaroon. Mistakes happen 👍
