### ISSUE TITLE
Quality Assurance - Issue Tracker

### ISSUE THREAD

**Issue by limeiscool** [freeCodeCamp/freeCodeCamp#53853]
### Describe the Issue

None of the GET request examples/Tests mention to be able to GET with _id param, However during one of the PUT request tests there is a GET request sent with an ID, i struggled to find this Bug in my code, i feel adding one extra Functional test for GET request specifically requiring to be able to GET by IDs, If using mongoDB like i was the ID needs the toString Method in order to be read as a string. i attached a screen shot shows the PUT test with the GET request at the bottom

### Affected Page

https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker

### Your code

```



```

### Expected behavior

Either extra functional test requiring to be able to GET with an ID, or 
Updated index.html with GET example that shows GET with an ID

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/77919503/8c8eff21-682a-4ad7-b605-9b51579d06db)

### System

- Device: [Desktop]
- OS: [Windows 11 WSL Ubuntu 22.04.3 LTS]
- Browser: [Chrome]
- Version: [122.0.6261.70 ]

**Comment by naomi-lgbt** [comment]
This requirement would be covered by:

> You can send a GET request to /api/issues/{projectname} and filter the request by also passing along any field and value as a URL query (ie. /api/issues/{project}?open=false). You can pass one or more field/value pairs at once.

I'd be fine adding another check inside that existing test to look at the `?id=` param.

**Comment by limeiscool** [comment]
i see now the "any field" and value, this was a lack of knowledge at the time, being able to get data by an "id" is imperative.

Id like to propose a solution to the test above,
- change query of `getMultiple` to GET the post created by carol and assigned to eric, this keeps the get Multiple aspect but returns 1 doc instead.

- use the `_id` of `getMultiple[0]` to GET `getCopy` and assert that `_id` of `getMultiple[0]` is equal to `_id` of `getCopy`

```javascript
const getMultiple = await $.get(url + '? 
created_by=Carol&assigned_to=Eric');
    assert.isArray(getMultiple);
    assert.lengthOf(getMultiple, 1);

// could write copyId inline instead
const copyId = getMultiple[0]._id
const getCopy = await $.get(url + `?_id=${copyId}`);
    assert.isArray(getCopy);
    assert.lengthOf(getCopy, 1);
    assert.equal(getCopy[0]._id, copyId, 'filtering by _id should return the correct document')
```

**Comment by naomi-lgbt** [comment]
I'm hesitant to rewrite the entire tests, when instead we could update the test I indicated to try a query by ID (which we know won't break existing projects because a later test relies on that functionality).

**Comment by limeiscool** [comment]
Agreed my proposed solution would be for the existing GET test that you indicated, you could just drop in `copyId` and `getById` after existing `getMultiple`, this adds a query by ID. The current tests only query by `created_by` and `assigned_to`

```javascript
const copyId = getMultiple[0]._id
const getById = await $.get(url + `?_id=${copyId}`);
    assert.isArray(getById);
    assert.lengthOf(getById, 1);
    assert.equal(getById[0]._id, copyId, 'should be able to query a document by _id')
```
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/77919503/91533037-c921-41c5-8093-2856743a199e)

**Comment by naomi-lgbt** [comment]
Ah, I see. Yes, that would be a good approach.

I'll go ahead and open this one up.
