### ISSUE TITLE
Expression of Interest: Voluntary Contribution for Arabic Translation

### ISSUE THREAD

**Issue by mejbass** [freeCodeCamp/freeCodeCamp#53865]
Hello freeCodeCamp Team,

I hope this message finds you well. My name is Bassam Mejlaoui and I am reaching out to express my strong interest in contributing voluntarily to the translation of the freeCodeCamp curriculum into Arabic.

**Background:**

- I have already joined the freeCodeCamp Discord server and the forum.
- I have filled out the contributor form expressing my intent to contribute to Arabic translations.

**Skills and Commitment:**
- I am a Native Arabic Speaker and have a strong command of technical terminology.
- I am committed to dedicating time and effort to ensure accurate and high-quality translations.

**Next Steps:**
- I have begun familiarizing myself with the Crowdin platform and the available translation projects.
- I am eager to receive guidance on any specific guidelines or workflows for Arabic translations.

**Request for Guidance:**
- Could you please direct me to any specific guidelines or contacts for Arabic translations?
- I am eager to start contributing and would appreciate any assistance or information you could provide.

Thank you for your time and consideration. I am looking forward to being part of the freeCodeCamp translation community and contributing to making programming education accessible to Arabic speakers.

Best regards,
Bassam Mejlaoui

**Comment by ShaunSHamilton** [comment]
Hello there,

The best thing to do is head to [the freeCodeCamp Discord server](https://discord.gg/KVUmVXA) where you can start in the `Localization > #start-here` channel.

For now, I am going close this. Thanks for your interest in contributing 🚀
