### ISSUE TITLE
Bonfire Chunky Monkey - Needs more test cases

### ISSUE THREAD

**Issue by debojitm** [FreeCodeCamp/FreeCodeCamp#5386]
I was able to pass the tests with the below code, however, I should not have been able to. Instead of Math.round I should have used Math.ceil

The test cases passed even with my incorrect solution because arr.length/size always rounded to the next higher integer with the given test cases.

Challenge [Bonfire: Chunky Monkey](http://www.freecodecamp.com/challenges/bonfire-chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20%2F%2Fvar%20sliced%20%3D%20arr.slice(0%2C%20size)%3B%0A%20%20%2F%2Fvar%20multiDimensional%20%3D%20%5B%5D%3B%0A%20%20%2F%2FmultiDimensional.push(sliced)%3B%0A%20%20%2F%2Fvar%20secondSliced%20%3D%20arr.slice(size%2C%20size%20%2B%20size)%3B%0A%20%20%2F%2FmultiDimensional.push(secondSliced)%3B%0A%20%20var%20x%20%3D%200%3B%0A%20%20var%20y%20%3D%20size%3B%0A%20%20var%20multiDimensional%20%3D%20%5B%5D%3B%0A%20%20var%20i%20%3D%201%3B%0A%20%20while%20(i%20%3C%3D%20Math.ceil(arr.length%2Fsize))%20%7B%0A%20%20%20%20multiDimensional.push(arr.slice(x%2C%20y))%3B%0A%20%20%20%20x%20%3D%20x%20%2B%20size%3B%0A%20%20%20%20y%20%3D%20y%20%2B%20size%3B%0A%20%20%20%20i%20%2B%2B%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20multiDimensional%3B%0A%20%20%0A%7D%0A%0Achunk(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%5D%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function chunk(arr, size) {
  // Break it up.
  //var sliced = arr.slice(0, size);
  //var multiDimensional = [];
  //multiDimensional.push(sliced);
  //var secondSliced = arr.slice(size, size + size);
  //multiDimensional.push(secondSliced);
  var x = 0;
  var y = size;
  var multiDimensional = [];
  var i = 1;
  while (i <= Math.round(arr.length/size)) {
    multiDimensional.push(arr.slice(x, y));
    x = x + size;
    y = y + size;
    i ++;
  }
  
  return multiDimensional;
  
}

chunk([0, 1, 2, 3, 4, 5], 5);

```

**Comment by ltegman** [comment]
Here's an example of input that will yield the wrong answer with this solution: `chunk([0, 1, 2, 3, 4, 5, 6], 3);`. It will be missing the final element of the array in the output.

**Comment by iflipd** [comment]
Can you give an example(s) of the desired result?  What should and shouldn't be happening here?  Thanks!
