### ISSUE TITLE
Check your code button not working -     Learn Basic JavaScript by Building a Role Playing Game

### ISSUE THREAD

**Issue by zbrcic** [freeCodeCamp/freeCodeCamp#53875]
### Describe the Issue

When I click the "Check your code" button nothing happens, either by mouse or by ctrl+enter. reset button works fine.
I dont know what causes it to stop responding, I thought copy pasteing might have to do with it, but seems random, sometimes clearing the cookies and cashe + restarting everything helps (i've turned off adbocker and tried firefox, edge and chrome too)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-89

### Your code

```
function buyWeapon() {
  if (gold >= 30) {
    gold -= 30;
    currentWeapon++;
    goldText.innerText = gold;
    let newWeapon = weapons[currentWeapon].name;
    text.innerText = "You now have a new weapon.";
  }
}


```

### Expected behavior

I expect to have my code checked, and be offered help if check fails but nothing happens

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/126713564/f06419b2-fb1c-4ba5-a8cb-0306ab79d43c)

### System

- Device: PC
- OS: Windows 10,
- Browser:  firefox, chrome, edge

**Comment by zbrcic** [comment]
Okay i have a new development. it stops working when I type in double quotes " sign

**Comment by zbrcic** [comment]
i've skipped to the next step and reached step 98, which stops working when i use equals sign on line 104 (button2.onclick =)

**Comment by gikf** [comment]
Thank you for reporting this issue.

That can happen when there are errors in the code, if you take a look at the console there should be some error displayed. There's earlier issue tracking this #52749.

Regarding the specific problem with the code, forum will be a more appropriate place for that. Please click the **"Help"** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours and can help determine if there is an issue with your code or the challenge's tests.

Thank you and happy coding.
