### ISSUE TITLE
COC?

### ISSUE THREAD

**Issue by alison985** [FreeCodeCamp/FreeCodeCamp#5387]
Hi,

I'm just wondering what your code of conduct is for this project?

Thanks,
Alison

**Comment by raisedadead** [comment]
Please feel to ask queries at Gitter : https://gitter.im/FreeCodeCamp/FreeCodeCamp
or you can read more on the blog : http://medium.freecodecamp.com/

This issue base dedicated to report bugs, in the FreecodeCamp, not for general queries.

Thanks!

**Comment by alison985** [comment]
Thanks @raisedadead !

It's here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Code-of-Conduct

**Comment by raisedadead** [comment]
:+1:
