### ISSUE TITLE
RUN TESTS or Submit the Code not woking

### ISSUE THREAD

**Issue by CrypticGuy** [FreeCodeCamp/FreeCodeCamp#5388]
When I am trying to submit the code no action takes place, the screen remains still as it is. I have tried numerous waypoints to see if a particular one is not working, but the same problem still exists. ASAP
Thank You

**Comment by raisedadead** [comment]
@CrypticGuy : Check if your brpwser has coookies enabled, also clear your browser cache.
You should also refer : https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug
If issue still persists, please post screen shots, and detailed steps.
Thanks.

**Comment by KyleSu** [comment]
I'm having this issue now on both firefox and chrome. It seems to apply only to Waypoint 37 for me in "HTML5 and CSS" since I've completed way points both before and after that specific one. I've cleared the cache on both browsers but the problem remains.

**Comment by ltegman** [comment]
If you are still experiencing this problem please reopen with more details and repro steps. Thanks and happy coding!
