### ISSUE TITLE
typo - English for developers - 4th course, Dialog 1, Task2 - work not workin

### ISSUE THREAD

**Issue by pchomik101** [freeCodeCamp/freeCodeCamp#53919]
### Describe the Issue

The word 'in' is double

I like to workin in the morning.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/task-2

### Steps to Reproduce

-Proceed to the 4th course 'Learn How to Talk About a Typical Workday and Tasks'
-Proceed to Task 2
-Observe the third sentence 'I like to workin in the morning.

### Recommended fix or suggestions

I like to work in the morning.

### Screenshots

![workin](https://github.com/freeCodeCamp/freeCodeCamp/assets/153861556/8993cd62-c215-4a0a-b9b2-8acfdcf7fb26)

**Comment by meifi-moogle** [comment]
Hi, I will try to fix it if that's ok!
