### ISSUE TITLE
Typo - Learn Basic String and Array Methods by Building a Music Player - Step 18

### ISSUE THREAD

**Issue by etzvi** [freeCodeCamp/freeCodeCamp#53912]
### Describe the Issue

Hello,

I believe there is a typo in the join() method example on Learn Basic String and Array Methods by Building a Music Player - Step 18

```
const exampleArr = [“This”, “is”, “a”, “sentence”];
const sentence = exampleArray.join(" "); // Separator takes a space character
console.log(sentence); // Output: “This is a sentence”
```

I expect:

`const sentence = exampleArray.join(" “);`

should actually be:

`const sentence = exampleArr.join(” ");`

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-18

### Your code

```

const exampleArr = [“This”, “is”, “a”, “sentence”];
const sentence = exampleArray.join(" "); // Separator takes a space character
console.log(sentence); // Output: “This is a sentence”

```

### Expected behavior

It's just a typo in the example explaining the join() method.

### Screenshots

![Screenshot from 2024-02-28 17-28-47](https://github.com/freeCodeCamp/freeCodeCamp/assets/69493065/743ab020-5302-4956-bd54-39be6b16c2df)

### System

N/A

**Comment by jdwilkin4** [comment]
Good catch. 

I will open it up for first timers contribution

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/654215fe7b4a899ddceb3b60.md

## Changes that need to be made
The code example in this step needs to be updated to reference the correct array name

```js
const exampleArr = ["This", "is", "a", "sentence"];
const sentence = exampleArr.join(" "); // Separator takes a space character
console.log(sentence); // Output: "This is a sentence"
```

Happy coding
