### ISSUE TITLE
typo - English for developers - 4th course, Task 5 - her not his

### ISSUE THREAD

**Issue by pchomik101** [freeCodeCamp/freeCodeCamp#53920]
### Describe the Issue

Sophie is misgendered in the first sentence of task5 of the 4th course

'In this part of the dialogue, Sophie talks about his morning activities.'

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/task-5

### Steps to Reproduce

-Proceed to the 4th course 'Learn How to Talk About a Typical Workday and Tasks'
-Proceed to Task 5
-Observe the first sentence 'In this part of the dialogue, Sophie talks about his morning activities.'

### Recommended fix or suggestions

Please change the first sentence to:

In this part of the dialogue, Sophie talks about her morning activities.

### Screenshots

![his](https://github.com/freeCodeCamp/freeCodeCamp/assets/153861556/ddf1499f-7529-46be-8454-991495183dfd)

**Comment by kunalg12** [comment]
Already create a pull request for #53921 issue.
