### ISSUE TITLE
Floating "Visit the Cirriculum" button on forums 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#53937]
### Describe the Issue

The "Visit the curriculum" text is floating outside of the tool bar. 

### Affected Page

https://forum.freecodecamp.org/

### Steps to Reproduce

1. Go to the home page. 
2. Look in the upper lefthand corner 
3. See error 

### Expected behavior

It should remain stationary in the upper left hand part of the screen where it belongs. 

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/58de1c11-9965-4851-b6a7-e986c6641eef)

### System

- Device: Desktop 
- OS: Windows 10
- Browser: Firefox 
- Version: 123.0

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #53910, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
