### ISSUE TITLE
Visit the Curriculum not displaying correctly in viewport

### ISSUE THREAD

**Issue by Supravisor** [freeCodeCamp/freeCodeCamp#53947]
### Describe the Issue

The link text "Visit the Curriculum" in the top left corner of the forum pages is not inline with the freeCodeCamp logo.

### Affected Page

https://forum.freecodecamp.org/

### Steps to Reproduce

1. Go to 'https://forum.freecodecamp.org/'
2. See error at the top left of the viewport.

### Expected behavior

The affected link text is inline with the freeCodeCamp logo.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/c8a26ed9-16fe-41f4-b293-e9d302dc8bbb)

### System

NA

**Comment by Supravisor** [comment]
Is this something a first timer can do?

**Comment by ilenia-magoni** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue https://github.com/freeCodeCamp/forum-theme/issues/112, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
