### ISSUE TITLE
Gitpod should have Python extension for Python projects

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#53965]
The Gitpod environment doesn't have python support natively, an extension that adds a Run button could be added to the setup to make life easier for campers.
In my local VSCode environment I have it:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/c90ce4a5-d6ca-49c6-9e37-6d619f36264d)

**Comment by ilenia-magoni** [comment]
or we should teach to run `python3 main.py` to test the code

**Comment by ShaunSHamilton** [comment]
> or we should teach to run `python3 main.py` to test the code

I have been advocating for this for a while, but it is difficult when our editor has no terminal.

---

We can add extensions to the gitpod config, but I would prefer to add a line to the first project mentioning `python main.py`. Button clicks should not be the thing we teach first.

**Comment by a2937** [comment]
Pardon me for this silly question, but which project is our first Python project that uses Gitpod? Unless we actually have a terminal where users can run the command; that information probably isn't going to stick.

**Comment by ilenia-magoni** [comment]
GitPod is used in the final projects of the Data Analysis with Python certification

**Comment by ojeytonwilliams** [comment]
> I would prefer to add a line to the first project mentioning python main.py. Button clicks should not be the thing we teach first.

This seems reasonable, but where is this code? In the main repo? If it's somewhere a contributor can modify, we can open this up for first-timers.

**Comment by a2937** [comment]
The instructions for the projects can be found on the main [repo](https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects). The individual Gitpod projects themselves live in their own specific repository under the FreeCodeCamp organization.

**Comment by ojeytonwilliams** [comment]
Thanks, @a2937. So, the fix is to update https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/mean-variance-standard-deviation-calculator.md so that it explains how to start running the code in Gitpod.

**Comment by a2937** [comment]
Wait can't we edit the gitpod.yml to have the task? https://www.gitpod.io/docs/introduction/languages/python#start-tasks

**Comment by ShaunSHamilton** [comment]
> Wait can't we edit the gitpod.yml to have the task? https://www.gitpod.io/docs/introduction/languages/python#start-tasks

> > We can add extensions to the gitpod config, but I would prefer to add a line to the first project mentioning python main.py. Button clicks should not be the thing we teach first.
> https://github.com/freeCodeCamp/freeCodeCamp/issues/53965#issuecomment-1985552721
