### ISSUE TITLE
A very minor tweak in description of Math.floor. Waypoint 35

### ISSUE THREAD

**Issue by LeoFib** [FreeCodeCamp/FreeCodeCamp#5397]
(Waypoint #35)Original text reads:
"Finally, let's use another function, Math.floor() to round the number down to its nearest whole number.
This technique will gives us a whole number between 0 and 19."
...........................................................................................................

(Perhaps this issue is one of style, but,)

Clearly, both Math.round() and Math.floor() "round down to...nearest whole number".

I would merely suggest, for absolute expository clarity, the insertion of a short sentence to emphasize the distinction between the two.

I hope it's not a bother to consider this.

The core utility and power of the new function introduced in this waypoint needs to leap out at you from the text IMHO...

Thank you to whomever reads this for your hard work.
--Beau
___________________________________________________
Original:
Finally, let's use another function, Math.floor() to round the number down to its nearest whole number.
This technique will gives us a whole number between 0 and 19....

Suggested Tweak:

a) Finally, let's use another function, Math.floor() to round the number down to its nearest whole number--no matter it's value. 

b) Finally, let's use another function, Math.floor() to round the number down to its nearest whole number regardless of its value.

(or an additional sentence appended.)
c)Math.floor() never rounds up."

**Comment by SaintPeter** [comment]
I'm amenable to this change, but I'm a little confused about what your proposed final wording is.  I suggest you put it in the form of a
> quoted text of the entire waypoint

So we can see what the final full text will look like.  Just give your best proposal and we'll work from there.  

Here is the current text:
> It's great that we can generate random decimal numbers, but it's even more useful if we use it to generate random whole numbers.

>First, let's use Math.random() to generate a random decimal.

>Then let's multiply this random decimal by 20.

>Finally, let's use another function, Math.floor() to round the number down to its nearest whole number.

>This technique will gives us a whole number between 0 and 19.

>Note that because we're rounding down, it's impossible to actually get 20.

>Putting everything together, this is what our code looks like:

>`Math.floor(Math.random() * 20);`

> See how Math.floor takes (Math.random() * 20) as its argument? That's right - you can pass a function to another function as an argument.

> Let's use this technique to generate and return a random whole number between 0 and 9.

**Comment by LeoFib** [comment]
It's great that we can generate random decimal numbers, but it's even more useful if we use it to generate random whole numbers.

First, let's use Math.random() to generate a random decimal.

Then let's multiply this random decimal by 20.

Finally, let's use another function, Math.floor() to round the number down to its nearest whole number.

Math.floor() only rounds numbers down--never up. For example, whether our number is 6.2, 6.5 or 6.9, Math.floor() will always give us 6.

This technique of placing Math.random() inside of Math.floor() will give us a whole number between 0 and 19.

Note that because Math.floor() only rounds down, it's impossible to actually get 20.

Putting everything together, this is what our code looks like:

Math.floor(Math.random() * 20);

See how Math.floor takes (Math.random() * 20) as its argument? That's right - you can pass a function to another function as an argument.

Let's use this technique to generate and return a random whole number between 0 and 9.

**Comment by AkiraLaine** [comment]
@SaintPeter I can open a PR for this if you think it's a good change :smile:

**Comment by LeoFib** [comment]
@AkiraLaine @SaintPeter 
HI Gents!

Yes, I'd like to open a PR, as I've never had an opportunity to contribute. I thought it best to wait for permission.

By the way, Nice website, Akira! I love your donate button at the top! lol :D Merry Xmas!

**Comment by AkiraLaine** [comment]
@LeoFib I'll let you do it if you get the green light! Thanks, Musare is still under development :smile

**Comment by SaintPeter** [comment]
@LeoFib This looks pretty good.  One minor tweak:
> Note that ~~because~~ **since** Math.floor() only rounds down, it's impossible to actually get 20.

Go ahead and submit a PR and I will test and approve.

**Comment by LeoFib** [comment]
THANKS!

**Comment by erictleung** [comment]
@LeoFib you still wanna take care of this one?

Also, just for reference, this challenge has moved since the addition of other problems so this issue now refers to the [Generate Random Whole numbers with JavaScript](http://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript) challenge.

**Comment by LeoFib** [comment]
I really would love to. I'm asleep right now, but would really like to get
back to it. trivial, though it may be, it's the use of github successfully
is the whole point -->not lost on you, I suppose. :)

I'll be in touch in 24 hours!

Thanks so much!

~Beau

**Comment by drk7891** [comment]
Is this still open, or is @LeoFib taking care of this?

**Comment by LeoFib** [comment]
Yes drk7891,

I believe the description of Math.floor() is nice and explicit.

Thanks to all!
