### ISSUE TITLE
Typo in command instructions for git revert file article

### ISSUE THREAD

**Issue by hminsky2002** [freeCodeCamp/freeCodeCamp#53976]
### Describe the Issue

In the instructions for the article [Git Revert File – Reverting a File to a Previous Commit](https://www.freecodecamp.org/news/git-revert-file-reverting-a-file-to-a-previous-commit/), 
the command for logging the changes to a file in oneline is incorrect. 

`$ git log -- oneline` 
is what is written,
where the correct command would be
`$ git log --oneline` 

This happens again in a few subsequent code blocks.

### Affected Page

https://www.freecodecamp.org/news/git-revert-file-reverting-a-file-to-a-previous-commit/

### Steps to Reproduce

Read the page, verify that the provided command is not correct.

### Recommended fix or suggestions

Change all text occurrences of 
`$ git log -- oneline` 
to `$ git log --oneline` 

### Screenshots

<img width="816" alt="Screen Shot 2024-03-04 at 3 22 25 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/18370464/1fc15e38-d9bf-43e4-88b7-136ca1e8e43a">
<img width="953" alt="Screen Shot 2024-03-04 at 3 27 09 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/18370464/88157ba8-22da-43df-bc4a-b400f5f11530">

**Comment by jdwilkin4** [comment]
Hi @hminsky2002 ! 

Thank you for reporting this. 
I have notified the editorial team 👍
