### ISSUE TITLE
Update description for step 5 of spam filter project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#53973]
### Describe the Issue

We need to show the proper syntax for assiging the result of a ternary operator to a variable's text content as mentioned in this [forum post](https://forum.freecodecamp.org/t/answer-explanation-learn-regular-expressions-by-building-a-spam-filter-step-5/676768).

Let's go with this updated description

````md
Back in your event listener, you need to update the text of the `result` element. You can use a `ternary` operator to achieve this task.

Here is an example of assigning the result of a ternary operator to an element's text content:

```js
el.textContent = condition ? "Use this text if the condition is true" : "Use this text if the condition is false";
```

After the `if` statement, use a ternary operator to check the truthiness of calling `isSpam()` with `messageInput.value` as the argument. If true, set the `textContent` property on the `result` element to `Oh no! This looks like a spam message.`. Otherwise, set it to `This message does not seem to contain any spam.`

Then set the `messageInput` element's `value` property to an empty string.
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-regular-expressions-by-building-a-spam-filter/step-5

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-regular-expressions-by-building-a-spam-filter/641cdf57c3f7ee276e1d9b32.md

Happy coding

**Comment by lasjorg** [comment]
I guess I'm fine with being this explicit about it and showing an example.

But I would hope by now in the curriculum (this challenge is far in) we have promoted the proper usage of the ternary so that it might be handled just in the assert hints.

Also, the hint in the assert for the code posted on the forum isn't super helpful in guiding the camper to the desired syntax.

**Comment by jdwilkin4** [comment]
I am not sure how the assert messages would be updated here to show the syntax. Unless we just give them the answer here.

I am open to ideas for changes
