### ISSUE TITLE
[python] Scientific Computing with Python projects test output

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#53984]
### Describe the Issue

The new platform for the Scientific Computing with Python projects does not give very much feedback. Without the diff and assertion output from the tests on replit it's extremely difficult to know what the problem is.

**Case 1**
For example this error:
>"create_spend_chart should print a different chart representation. Check that all spacing is exact."

https://forum.freecodecamp.org/t/scientific-computing-with-python-projects-budget-app/677107/5

There is no other information at all in the preview or console areas. It's not even clear if the calculation is correct or if it's just a spacing issue. 

To solve this I had to look for the test data and expected output on github to find that the problem was an extra newline at the very end (pretty common for this project.) I also use `repr` to print raw string data to compare, so you can see newlines clearly, but that's never introduced.

**Case 2** 
Here is another example:
https://forum.freecodecamp.org/t/scientific-computing-with-python-projects-arithmetic-formatter/676946

Again, without the diff and assertion output these are extremely more difficult. It was already difficult for learners to understand that error output without a primer.

**Case 3**
In this case there was a syntax error that prevented any code from running, but no output at all to determine the problem.
https://forum.freecodecamp.org/t/scientific-computing-with-python-projects-budget-app/676810

A "There was a syntax error before any code could be run" message or a real Python syntax error would be helpful here.
```
line 9
    amount_str = f' {format(entry["amount"], '.2f')}'
                                               ^
SyntaxError: invalid decimal literal
```

Proposed solution:

If the fails/hints could output actual and expected raw string data in the console, that would be something to go by.

Additionally, it would help if the example in the instructions had explicit information about how many spaces there need to be, if it should end with a space, or newline, etc.

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/scientific-computing-with-python-projects/budget-app

### Your code

```

NA

```

### Expected behavior

NA

### Screenshots

NA

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
NA

### Additional context

NA

**Comment by naomi-lgbt** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/8ff5aeb3-3535-4456-b42e-8e7bbbc6d030)

It does print to the browser console. Might not hurt to pipe some of this into the platform console.

**Comment by ilenia-magoni** [comment]
Case 3 should be fine now after next deployment
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/8e1a52d5-c1b4-4da0-bb56-a2840623a58a)

**Comment by dasiff** [comment]
The issue is especially bad when the spacing corresponds to the specifications given, but the testing unit is expecting spaces at the end of the line (I still haven't passed; see also https://forum.freecodecamp.org/t/not-passing-chart-test-scientific-computing-with-python-projects-budget-app/690267).  Proposed solution: ignore spaces at the end of each line

**Comment by ilenia-magoni** [comment]
I would say

TODO: teach campers to look at the browser console

**Comment by dasiff** [comment]
The test is too sensitive to trailing blank spaces:
pyodide.asm.js:9 AssertionError: '\nPercentage spent by category\n100|\n 90[298 chars]    ' != 'Percentage spent by category\n100|       [383 chars] t  '
Even looking at the console as a student I don't know what that means!

TODO: test should ignore spaces at the end of each line

**Comment by ilenia-magoni** [comment]
@dasiff if you need help please write on the forum, not here.
