### ISSUE TITLE
Teach that restarting the server between changes is needed

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#53988]
### Describe the Issue

We see far too many campers on the forum who do not understand that the server has to be restarted between changes.

I didn't look through all of the curricula but it should be made clear early on. Personally, I would also suggest we teach the options of using `--watch` or `nodmon`. It doesn't have to be more than a comment in the early backend challenges.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis

### Your code

```



```

### Expected behavior

Not to have to mention this every time someone has an issue with a backend challenge.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
I have always liked using `nodemon`. It might be nice to have that already added in the starter repo and gitpod. That way it will be taken care of for them. 

Adding a note could be nice though too. 

thoughts @scissorsneedfoodtoo ?

**Comment by lasjorg** [comment]
It was intentionally removed from all repos.

See the last 3 comments in this issue.
https://github.com/freeCodeCamp/freeCodeCamp/issues/53801

---

I don't understand why we are making it more difficult for the camper than it has to be or expect beginners to not trip up on this.

We haven't even taught (afaik) that a server has to be restarted before the changes take effect. We should make that clear and teach the solutions to server auto restarting. Even if the camper has to add it manually.

I think this is a case of developers forgetting what it was like to be a beginner.

**Comment by jdwilkin4** [comment]
ohh that's interesting that the `--watch` flag was removed from the repos. 
I am pretty out of the loop with the changes being made to the backend certs. 

In this case, I don't see any harm with adding a note about how to auto restart the server using `--watch`.

**Comment by lasjorg** [comment]
Just to clarify, I don't think we were using `--watch` in the start scripts but we did use `nodemon` in a few of the repos and that was removed.

I'd like to response to this from that issue:

> Yes. `npm run start` is not difficult, and if Campers want to implement their own watcher then that is easy enough to do.

This I do not agree with. For beginners, it is difficult.

A lot of campers do not even know they need to restart the server between changes. Most do likely not know about arrow-up in the terminal to get to previous commands, meaning they have to write `npm run start` after every change they make to the server file. Which when learning or debugging challenge projects can add up to tons of restarts.

Secondly, saying they can just implement their own watcher and it is easy to do completely misses the point. Yes, if you know about it it is easy, if you don't know about it, and we do not even teach it, then it isn't easy.

> In this case, I don't see any harm with adding a note about how to auto restart the server using `--watch`.

That would be my suggestion as well. Preferable as early as possible.

**Comment by jdwilkin4** [comment]
Looking at the challenges, we could place a note in the first section for working with the `package.json`. But the note might work better in the section set of challenges for node and express since they will be writing more code and probably benefit more from the automatic restart of the server.

https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/meet-the-node-console

we could add a note at the end of that first set of instructions.
something along these lines

````md
If you are running these challenges locally, you can add a package called `nodemon` that will automatically restart the server when you make changes to your `.js` files. Without this package, you will need to manually start(`npm start`) and stop (`Ctrl + C`) the server each time.

Once you have [cloned the repo locally](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository), you can add `nodemon` by following these steps in the terminal: 

1. `cd boilerplate-express/`
2. `npm install nodemon --save-dev`
3. `npm i`
4. Update the `start` command inside the `package.json` file to `"start": "nodemon server.js"`

Now when you start the server(`npm start`) and make changes to your `myApp.js` file, the server will automatically restart for you and apply those changes. 
````

**Comment by lasjorg** [comment]
What I have is longer but I think it might be worth going into it a bit more.

> The server must be restarted after making changes to its files.
> 
> You can stop the server from the terminal using `Ctrl + C` and start it using Node directly (`node mainEntryFile.js`) or using a run script in the `package.json` file with `npm run`.
> 
> For example, the `"start": "node server.js"` script would be run from the terminal using `npm run start`. The `start` command (and a few others) works without `run`, that is `npm start` works the same as `npm run start`. If no command is provided, `npm run` will list the available scripts.
> 
> To implement server auto restarting on file save Node provides the `--watch` flag you can add to your start script `"start": "node --watch server.js"` or you can install an npm package like `nodemon`. We will leave this to you as an exercise.
>  
> Hint: Most terminals let you use the up/down arrow keys to access the history of previously entered commands.


---

I can shorten it a bit by removing some of the `npm run` information.

**Comment by ShaunSHamilton** [comment]
We are hoping to move off of the first few projects soon, and do have a decent lesson outline with a lot of the previous curricula's "missed bits": https://github.com/freeCodeCamp/back-end-development-and-apis/blob/master/curriculum/locales/english/learn-nodejs-by-building-a-web-server.md#--description---7

So, for the current curricula, I would go with short, simple, and quick changes. That is, without deliberating on pedagogy.

**Comment by lasjorg** [comment]
How soon is soon?

I don't see an issue with adding some more information to the current challenge. As I said, I can shorten it a bit but it is already written and is easy and quick to add.

---

> The server must be restarted after making changes to its files.
> 
> You can stop the server from the terminal using `Ctrl + C` and start it using Node directly (`node mainEntryFile.js`) or using a run script in the `package.json` file with `npm run`.
> 
> For example, the `"start": "node server.js"` script would be run from the terminal using `npm run start`.
> 
> To implement server auto restarting on file save Node provides the `--watch` flag you can add to your start script `"start": "node --watch server.js"` or you can install an npm package like `nodemon`. We will leave this to you as an exercise.

**Comment by ShaunSHamilton** [comment]
> How soon is soon?

I am terrible at estimations 😅 . 2nd quarter.
