### ISSUE TITLE
Archiving Scientific Computing with Python boilerplates

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#53992]
Considering _Scientific Computing with Python_ projects are now run in browser, perhaps it's time to archive their boilerplates? Otherwise it might look like they also should be maintained and changes to _curriculum version_ should be reflected in boilerplates (unless that's actually a case).

https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter
https://github.com/freeCodeCamp/boilerplate-budget-app
https://github.com/freeCodeCamp/boilerplate-polygon-area-calculator
https://github.com/freeCodeCamp/boilerplate-probability-calculator
https://github.com/freeCodeCamp/boilerplate-time-calculator

**Comment by ShaunSHamilton** [comment]
Quite right. It completely slipped my mind to do this. Thanks @gikf
