### ISSUE TITLE
Explain in this step that the HTML entity won't work with innerText

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#54003]
### Describe the Issue

Edit: Updated issue.

The camper is asked to add the `"You die. &#x2620;"` to the `text` property which won't work with this step's current code.

As pointed out this will be fixed in a later step but I question leaving it as is. It is just going to be confusing. I would suggest updating this step with a comment about it so it isn't misinterpreted as a bug.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-136

### Your code

```html
<p class="nope"></p>
<p class="yes"></p>
```

```js
document.querySelector('.nope').innerText = "&#x2620;"
document.querySelector('.yes').innerHTML = "&#x2620;"
```

### Expected behavior

Acknowledge the flaw in the code in this step and mention it will be fixed later.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-basic-javascript-by-building-a-role-playing-game-step-136-large-bug/677592

**Comment by Supravisor** [comment]
In step 138 this issue is resolved.
```
Step 138
In order for the &#x2620; emoticon text to properly display on the page, you will need to use the innerHTML property.

The innerHTML property allows you to access or modify the content inside an HTML element using JavaScript.

Here is an example of updating the content for this paragraph element using the innerHTML property.

<p id="demo">This is a paragraph.</p>
document.querySelector("#demo").innerHTML = "Hello, innerHTML!";
In the update function, change text.innerText to text.innerHTML.
```

**Comment by lasjorg** [comment]
@Supravisor Nice catch. Never did any of the challenges.

I have my reservations about this not being mentioned in the challenge. I will update the issue.

**Comment by jdwilkin4** [comment]
I think it makes sense to add a note to this step.

It could be the copy and paste sentence from step 138

> In order for the &#x2620; emoticon text to properly display on the page, you will need to use the innerHTML property.

**Comment by Supravisor** [comment]
How about:

>In a later step, you will use another property for the &#x2620; emoticon text to properly display on the page.

**Comment by jdwilkin4** [comment]
That works 👍
