### ISSUE TITLE
Not submitting -- Help

### ISSUE THREAD

**Issue by Theycallmedom** [FreeCodeCamp/FreeCodeCamp#5400]
Challenge [Waypoint: Change the Color of Text](http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h2 style="color:blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

My challenge ist submitting or even checking to see if i did it right. I have tried everything to try and get past this. Any help would be much appreciated.

**Comment by BerkeleyTrue** [comment]
Try changing `blue` to `red`.

Please use the help chat when you are stuck. 


Happy Coding!
