### ISSUE TITLE
[UI Components] Update the CSS of hover and focus states of CloseButton

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#54011]
## Description

The `CloseButton` component of `ui-components` is missing hover and focus styles. We would like to add them in so that we can replicate the current display in /learn.

Comparison:

| ui-components | /learn |
| --- | --- |
| ![close-button](https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/b56c8780-ad91-4a7d-bb08-9599409bf2d1) | ![learn-close-button](https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/2e19a1f5-0ba0-4803-ad7a-40a56fbd03da) |

## Requirements

- Add hover and focus styles to the `CloseButton` component
- Remove the `close` class from the `CloseButton` component in `Flash`, and ensure that the change doesn't introduce any visual regression:
    https://github.com/freeCodeCamp/freeCodeCamp/blob/9f71d1c3ace1a4bebb7027c08c5e64a893825d96/client/src/components/Flash/index.tsx#L38-L41 

Relevant files:
- `CloseButton` implementation: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/ui-components/src/close-button/close-button.tsx
- Custom CSS in /learn: https://github.com/freeCodeCamp/freeCodeCamp/blob/9f71d1c3ace1a4bebb7027c08c5e64a893825d96/client/src/components/layouts/global.css#L179-L192

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i'm interesting in this issue if there is no currenlty working on it

**Comment by sarmadH97** [comment]
Hi @Amrani-Farouk-Hossam-Eddine, Did you start working on it ?

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
> Hi @Amrani-Farouk-Hossam-Eddine, Did you start working on it ?

to be completly honest with you i really want to contribute to freeCodeCamp and i got lost in the guide and i need some help if you already familuar with it

**Comment by sarmadH97** [comment]
I'm new to this too, I'll let you know if i figure it out

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
i worked on it and i made a PR
