### ISSUE TITLE
Update hint text Spreadsheet Step 31

### ISSUE THREAD

**Issue by Supravisor** [freeCodeCamp/freeCodeCamp#54021]
### Describe the Issue

The wording of the hint text does not match the instructions.  The word *not* is missing from the hint. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-31

### Your code

```
# --description--

Now you need to check if the `value` does not include the `id` of the element. Create an `if` condition to do so.

# --hints--

You should create an `if` block.

```js
assert.match(code, /const\s+update\s*=\s*(?:\(\s*event\s*\)|event)\s*=>\s*\{\s*const\s+element\s*=\s*event\.target\s*;?\s*const\s+value\s*=\s*element\.value\.replace\(\s*\/\\s\/g\s*,\s*('|"|`)\1\s*\)\s*;?\s*if\s*\(/);
```

Your `if` condition should check if `value` includes the `id` of the `element`.

### Expected behavior

Your `if` condition should check if `value` does not include the `id` of the `element`.

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/4b7702bb-b64c-469a-9099-8c3366dd798a)

### System

NA

**Comment by moT01** [comment]
For some more context, the challenge is expecting `if (!value.includes(element.id)) {}`, but if you input something like this: `if (value.includes(element.id)) {}` (no `!`), the hint is ``Your `if` condition should check if `value` includes the `id` of the `element`.``

It should check that it does **not** include the id. So we can change the hint to the suggestion - I would change `if` to `that` though:

``Your `if` condition should check that `value` does not include the `id` of the element`.``

What do you think @Supravisor?

**Comment by ilenia-magoni** [comment]
Sounds like there is a conclusion for what to change the hint to, so I am opening this for contributions
