### ISSUE TITLE
Most common incorrect answers for step-1

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#54024]
### Describe the Issue

Here is the list of the most common incorrect answers for learn-html-by-building-a-cat-photo-app/step-1

| editable_file_contents                                          | unique_user_count |
|---------------------------------------------------------------------|-------------------|
| `<html><body><h1>Hello World</h1></body></html>`                    | 57672             |
| `<html><body><CatPhotoApp>Hello World</CatPhotoApp></body></html>`  | 4829              |
| `<html><body><CatPhotoApp>Hello World</h1></body></html>`           | 3114              |
| `<html><body><h1>CatPhotoApp</h1></body></html>`                    | 1988              |
| `<html><body><h1>Cat Photo App</h1></body></html>`                  | 1829              |
| `<html><body><h1>Hello World</h1><h1>CatPhotoApp</h1></body></html>`| 857               |
| `<html><body><CatPhotoApp>Hello World<CatPhotoApp></body></html>`   | 825               |
| `<html><body><h1>Hello World</CatPhotoApp></body></html>`           | 823               |
| `<html><body><h1>Hello World</h1></body></html>`                    | 479               |
| `<html><body><h1>CatPhotoAppp</h1></body></html>`                   | 389               |

To see the indentations and line breaks: https://docs.google.com/spreadsheets/d/1P4a1kfRIVk5Q9pfuIqsoF3cQc6ehQiMST4ISArtbvSc/edit?usp=sharing

### Considerations:
1. The right answer is also included in the failed variations. Either google analytics is [misfiring](https://github.com/freeCodeCamp/freeCodeCamp/blob/138a80f6ca09df04f30ee7ce97ebe1bfcf39436d/client/src/templates/Challenges/redux/execute-challenge-saga.js#L145-L151), or there is an issue with our evaluations logic extensions, tests, browser extensions, etc.
2. It seems like a lot of users are confused about the placement of CatPhotoApp
3. Adding a copy button feature for the code blocks might help with reducing the misspellings of CatPhotoApp
4. Having the default seed as the wrong answer could mean users are just testing the UI. I could AB test disabling the button if seed does not change and see if there is an improvement in user behaviour.

### Goals:
Reducing the bounce rate ( people leaving the platform ) on the entry challenges is highly critical. Increasing the percentage of the people who go to the next challenge would significantly increase all of our metrics. 

### Suggestions
Oliver suggested changing the instructions to say 'change its text from "Hello World" to "CatPhotoApp"' should clarify it a bit further. 

Other suggestions? I am all hears. 

### Affected Page
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1

```[tasklist]
### Tasks
- [ ] update instruction
- [ ] investigate why correct answers are failing
- [ ] write tests for common variations (after the new instrucstions are in)
```

**Comment by ojeytonwilliams** [comment]
Thanks, Ahmad. One thing we can do with this information is tailor the hints to the most common mistakes.

For example, given `<html><body><CatPhotoApp>Hello World</CatPhotoApp></body></html>` we could say 
> The type of tags should be `h1`. You should replace `<CatPhotoApp>` with `<h1>` and `</CatPhotoApp>` with `</h1>`

also, if they've not modified the code at all, it could say something like

> You need to modify the code. To get started, click on the line `<h1>Hello World</h1>` above and start typing.

Also, playing with it now, I noticed that the editor doesn't automatically get focused when the learn clicks "Start Coding". Was that intentional? It seems like it would help if a user could immediately start typing and see things change.

**Comment by moT01** [comment]
```
The code below contains an HTML `h1` element. The element has an opening tag, `<h1>`,
a closing tag, `</h2>`, and the text that the element will display goes in between the tags.
You can see `Hello World` displayed in the browser preview.

Change the text of the `h1` element below from `Hello World` to `CatPhotoApp` and watch
the browser preview update to display the new text.
```

**Comment by ahmaxed** [comment]
Great feedback there is some more context.

> 1. What's the difference between the two?
> `<html><body><h1>Hello World</h1></body></html>` 57672 `<html><body><h1>Hello World</h1></body></html>` 479

There is a spacing difference. Refer to the link in the description for spacing and indentation.

> 5. There are 2218 misspellings of CatPhotoApp, mostly due to spaces, so not sure how effective a copy button feature is.

If we allow users to copy the text, it would remove the variations.

**Comment by ahmaxed** [comment]
I want to alter the initial text as little as possible so we could associate the changes in text to changes in user behaviour easier. 

How about only changing this:

```
Find the h1 element and change its text to:

CatPhotoApp
```

to this:

```
Change the text of the `h1` element below from `Hello World` to `CatPhotoApp` and watch
the change in the preview.

When you are done, press the "check your code button" to see if it's correct.
```

**Comment by moT01** [comment]
I would be fine with that @ahmaxed 👍 So the full instructions would look like this:

```
HTML elements have opening tags like <h1> and closing tags like </h1>.

The text for an element goes between its opening and closing tags.

Change the text of the `h1` element below from `Hello World` to `CatPhotoApp` and watch
the change in the preview.

When you are done, press the "check your code button" to see if it's correct.
```

Here's a suggestion with some minor adjustments that I like a little better:

```
HTML elements have opening tags like <h1> and closing tags like </h1>. The text an element will display goes between its opening and closing tags.

Change the text of the `h1` element below from `Hello World` to `CatPhotoApp` and watch
the change in the browser preview.

When you are done, press the "check your code button" to see if it's correct.
```

^-combined first two paragraphs into one
 -changed "The text for an element" to "The text an element will display"
 -changed "preview" to "browser preview"

I'm just guessing, but I think that a lot of the issues might have to do with information overload. There's instructions, and the preview, and code editors, and nav bars, and more. The user is not familiar with most of it, and the instructions don't really explain any of it. So I think the more clear we can make things for users on the first step, the better. That's why I keep making suggestions that somewhat explain the things and are as explicit as possible - e.g. "the code below", "the browser preview", "the text an element will display", etc.

**Comment by ahmaxed** [comment]
Wonderful, let's go with your last suggestion.

I assume once the new instruction is in, the new failed challenges will look different.
As a result, writing tests for the current variations might not be necessary. 

I will double check if there are overlaps. We could write tests for those.

**Comment by jdwilkin4** [comment]
I haven't check the analytics since the changes were merged in. But looking at the forum it looks like there is still some confusion on how to go about the first step 

It looks like campers are either not sure what to do, so they don't write anything. Or they are writing `<catPhotoApp>` like the results show.

Here are a few postings from the forum within the last week and a half

https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-1/683131
https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-1/684136
https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-1/683382
https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-1/683480
https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-1/684804

This tells me there is still a high volume of guessing going on. 

IMO, I think it would be better to start with a blank page instead of giving them the h1 element and asking them to change the text. That might be leading to some of the confusion. 

By having them write the h1 element, then they will get to see the result appear on the page instead of just the text changing. So it might be a better learning experience overall. 

Something like this might work

````html
HTML elements have an opening and closing tag with content in between.

Here is the basic syntax:

```html
<openingTag>content</closingTag>
```

Notice how the syntax of the closing tag includes a forward slash `/` before the element name. 

The first element you will learn about is the `h1` element. The `h1` element is a heading element and is used for the main heading of a webpage.

```html
<h1>This is a main heading</h1>
```

Create an `h1` element and give it the text `CatPhotoApp`.

When you are done, press the "Check Your Code" button to see if it's correct.
````

**Comment by Supravisor** [comment]
Mentioned earlier about a visualisation for the required code.

> 4. .. animation guiding the learner through the step
>    https://supravisor.github.io/TestPod/
QUOTE EDITED

Starting with a blank page is also a good idea.  However, may lead to lots of syntax errors for beginners to navigate.

One of the things Campers who post on the forum for RWD is that they do not understand the hints or error messages.
Catch-22: you have to understand code syntax to recognise syntax errors displayed in the hint message.

Here is a selection from the last ten days or so:
* https://forum.freecodecamp.org/t/learn-the-css-box-model-by-building-a-rothko-painting-step-11/684853
* https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-60/684760
* https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-48/684613/2
* https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-57/684289/10
* https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-50/684286
* https://forum.freecodecamp.org/t/learn-accessibility-by-building-a-quiz-step-67/683822/10
* https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-38/682998
* https://forum.freecodecamp.org/t/learn-basic-css-by-building-a-cafe-menu-step-44-got-stuck-here-help-would-be-greatly-apprecciated/683648
* https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-33/683393
* https://forum.freecodecamp.org/t/learn-html-forms-by-building-a-registration-form-step-52/683363
* https://forum.freecodecamp.org/t/stucked-in-step-14-of-learn-html-by-building-a-cat-photo-app/683298
* https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-3/683218
* https://forum.freecodecamp.org/t/learn-css-variables-by-building-a-city-skyline-step-112/683183

**Comment by ahmaxed** [comment]
The new changes have been in for a week. I will put together another document for the most common mistakes to see if anything has changes. The analytics does not show a considerable change.

**Comment by jdwilkin4** [comment]
@Supravisor 

> Mentioned earlier about a visualisation for the required code.

The visualization looks cool but I haven't seen any animations or links for any of the steps.
So that might not be an option for the curriculum

**Comment by a2937** [comment]
I wonder if it's possible to make little info icons that explain some of the hint text in the event it's potentially confusing.

**Comment by a2937** [comment]
I just had a thought. What if and hear me out, that last one (the one with CatPhotoApp in h1) failed because of an indentation issue. Is there a way to double check this?

**Comment by hbar1st** [comment]
just wondering how this went? (was there an improvement?)
I'm still having to explain to people what an element is vs what is a tag.
But I haven't seen all that much step 1 issues.

**Comment by ahmaxed** [comment]
Here is a sample of the failed challenges after the initial changes took place:
|all_editable_file_contents | unique_user_count|
|-------------------|-------------------|
|`<html>  <body>    <h1>Hello World</h1>  </body></html>` | 53744|
|`<html>  <body>    <h1>Cat Photo App</h1>  </body></html>`| 2888|
|`<html>  <body>    <h1>CatPhotoApp</h1>  </body></html>`| 1922|
|`<html>  <body>    <h1>This is a main heading</h1>  </body></html>` | 756|
|`<html>  <body>    <h1>Hello World</h1>    <h1>CatPhotoApp</h1>  </body></html>` | 563|
|`<html>  <body>    <CatPhotoApp>Hello World</CatPhotoApp>  </body></html>` | 508|
|`<html>  <body>    <h1>cat photo app</h1>  </body></html>` | 424|
|`<html>  <body>    <h1>CatPhotoApp<h1>  </body></html>` | 382|
|`<html>  <body>    <h1>Cat PhotoApp</h1>  </body></html>` | 334|
|`<html>  <body>    <h1>CatPhotApp</h1>  </body></html>` | 333|
|`<html>  <body>    <h1>Hello World</h1>      </body></html>` | 294|
|`<html>  <body>    <h1>Cat photo app</h1>  </body></html>` | 261|
|`<html>  <body>    <h1>Hello World</h1>    <h1>Hello World</h1>  </body></html>` | 255|
|`<html>  <body>    <h1>Hello World CatPhotoApp</h1>  </body></html>` | 250|
|`<html>  <body>        <h1>Hello World</h1>  </body></html>` | 245|
|`<html>  <body>    <h1>CarPhotoApp</h1>  </body></html>` | 219|
|`<html>  <body>    <h1>CatPhotoAppp</h1>  </body></html>` | 218|
|`<html>  <body>    <h1>Hello World</h1>  </body></html><h1>CatPhotoApp</h1>` | 215|
|`<html>  <body>    <h1>CatPhotoApp/h1>  </body></html>` | 207|
|`<html>  <body>    <h1>CatPhotoApp</h1>    <h1>Hello World</h1>  </body></html>` | 199|
|`<html>  <body>    <CatPhotoApp>Hello World</h1>  </body></html>` | 198|
|`<html>  <body>    <h1>Hello World</h1>    <h2>CatPhotoApp</h2>  </body></html>` | 189|
|`<html>  <body>    <h2>Hello World</h2>  </body></html>` | 179|
|`<html>  <body>    <h1>CatPhoto App</h1>  </body></html>` | 172|
|`<html>  <body>    <h1>CatPhotosApp</h1>  </body></html>` | 154|
|`<html>  <body>    <h1>CatPhotoAp</h1>  </body></html>` | 149|
|`<html>  <body>    <h1></h1>  </body></html>` | 144|
|`<html>  <body>    <h1>Hello World</CatPhotoApp>  </body></html>` | 141|
|`<html>  <body>    <h1>Hello world</h1>  </body></html>` | 140|
|`<html>  <body>    <h1>Hello World<h1>  </body></html>` | 135|
|`<html>  <body>    <h1CatPhotoApp</h1>  </body></html>` | 135|
|`<html>  <body>    <h1>Cat Photo</h1>  </body></html>` | 135|
|`<html>  <body>    <h1>Hello</h1>  </body></html>` | 132|
|`<html>  <body>    <h1>CAT PHOTO APP</h1>  </body></html>` | 128|
|`<html>  <body>    <h1>CatPhotoApp </h1>  </body></html>` | 126|
|`<html>  <body>    <h1>Hello World</h1>  </body></html><h1>Hello World</h1>` | 125|
|`<h1>CatPhotoApp</h1>  <body>    <h1>Hello World</h1>  </body></html>` | 116|
|`<html>  <body>    <h1> CatPhotoApp </h1>  </body></html>` | 116|
|`<html>  <body>    <h1>CatPhoto</h1>  </body></html>` | 114|
|`<html>  <body>    <h1>Check Your Code</h1>  </body></html>` | 113|
|`<html>  <body>    <h1>cat photo</h1>  </body></html>` | 109|
|`<html>  <body>    <h1>hello world</h1>  </body></html>` | 107|
|`<html>  <body>    <h1>Hello World</h1>CatPhotoApp  </body></html>` | 103|
|`<html>  <body><h1>Hello World</h1>  </body></html>` | 100|

**Comment by ahmaxed** [comment]
Many might just clicking the button to see what happens.

**Comment by ilenia-magoni** [comment]
Considering we are working on the new stuff, and step 1 will not be the first things they see anymore, should I try to implement any changes from this? cc/ @jdwilkin4

**Comment by Sembauke** [comment]
Let us go with this:

```
HTML elements have opening tags like <h1> and closing tags like </h1>. The text an element will display goes between its opening and closing tags.

Change the text of the `h1` element below from `Hello World` to `CatPhotoApp` and watch
the change in the browser preview.

When you are done, press the "check your code button" to see if it's correct.
```

**Comment by jdwilkin4** [comment]
@ilenia-magoni 

Sorry, I missed this comment from earlier.
I think what we ended up going with for the new cert works well 👍  
So we don't need to apply any additional changes to that first step of the workshop.
