### ISSUE TITLE
The intro text is shown twice in the user journey

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#54045]
### Describe the Issue

The the following text is displayed twice in the user journey. Once on /learn when the user is not signed in, and once immediately after the user signs in on /email-sign-up

"Please slow down and read this.

freeCodeCamp is a proven path to your first software developer job.

More than 40,000 people have gotten developer jobs after completing this – including at big companies like Google and Microsoft.

...
"

Since all singed in users see the /email-sign-up/ instance, should the one on /learn be removed?

### Affected Page

https://www.freecodecamp.org/learn

### Screenshots

/learn
<img width="1056" alt="Screenshot 2024-03-11 at 10 41 03 AM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/b5e4354f-90c9-405d-84d1-ebe28406fa90">

/email-sign-up
<img width="1055" alt="Screenshot 2024-03-11 at 10 40 37 AM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/3fff88b8-1d04-47f7-a353-3b56010a43f8">

**Comment by fuelmessenger** [comment]
:sparkles: Thanks to the community, there's an estimated bounty value of **$6.81 USD** for a successful merge request of this issue via contributions such as **9.750 STORJ** tokens. Happy coding :grinning:
Details and T&Cs at [joinfuel.io](https://joinfuel.io)

**Comment by MohsinFarooq** [comment]
perhaps we could keep a summarised message on the /learn route but not remove everything?

**Comment by AdityaRaj150** [comment]
we can put a nice label text on the arrow, something like know our mission or know more about us.

**Comment by Sembauke** [comment]
I think this is fine as is. Most people won't read it anyway!
