### ISSUE TITLE
Issue with sync I/O

### ISSUE THREAD

**Issue by AromaR** [FreeCodeCamp/FreeCodeCamp#5404]
Challenge [Waypoint: Start a Nodejs Server](http://www.freecodecamp.com/challenges/waypoint-start-a-nodejs-server) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2597.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps and a description on how to reproduce the issue.

Happy Coding!
