### ISSUE TITLE
Clearer Instructions - Step 61 of the JS (Beta) Certification - Calorie Counter Project

### ISSUE THREAD

**Issue by leta91** [freeCodeCamp/freeCodeCamp#54041]
### Describe the Issue

Hi,
I think that the instructions contained on Step 61 should be clearer by removing the double quotes around `Invalid Input: ` as the double quotes should not be rendered 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-61

### Your code

```
if (invalidInputMatch) {

    }
  }
}
```

### Expected behavior

Here is my suggestion on how to rephrase this part of the instructions, by simply removing the double quotes around `Invalid Input: `

Using a template literal, in your `if` block, call the `alert()` function to tell the user `Invalid Input: `, followed by the first value in the `invalidInputMatch` array.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment]
Thank you for your feedback, the quotes are there intentionally. See #51036
