### ISSUE TITLE
Unclear compilation error in Python course with keyword typo

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#54052]
### Describe the Issue

If campers make a typo like using "While" instead of "while" for their loop construct, they have no idea if it's a spacing problem or they're using the wrong keyword. There must be a way to let them know what kind of issue they're facing. 

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/step-24

### Your code

```
 While True:
        password = ''
        # Generate password
        for _ in range(length):
            password += secrets.choice(all_characters)
```

### Expected behavior

The console should inform the camper that the phrase `While` was unexpected or something among those lines. If a compilation error is happening, the camper should always know what it means instead of guessing. 

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/cb12823c-758a-4cdc-90a2-c4defe9bdfcd)

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 123.0.1

### Additional context

First reported in this thread: https://forum.freecodecamp.org/t/learn-regular-expressions-by-building-a-password-generator-step-24/678788 

I also am fairly sure someone accidentally left a `console.log` statement in `execute-challenge-saga.js` regarding `newTest` and it should probably be removed.

**Comment by Supravisor** [comment]
There is an indication.  The keyword will appear blue, instead of black. A visual accessibility issue.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/6db7c2e5-8806-469c-b0e5-4580148c3b25)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/ba92c1d3-21b3-4175-8ca4-54d77bcac9c2)

**Comment by a2937** [comment]
While that is true and the syntax highlighting is a wonderful thing; I don't think some less savvy campers will pay attention to the highlighted words.

Additionally, some of them might not pick up on why some words are highlighted in the FreeCodeCamp Code Editor. I don't believe at any point up to this section it ever gets explained, though it has been a while since I did a deep dive into the curriculum.

A clear definitive message leaves absolutely zero ambiguity in what kind of error was performed. It'd be one thing if the camper gets some kind of feedback saying they must have a `while` loop , but right now, all this error gives a compilation error. If a camper hasn't encountered it before,  they could easily misinterpret this error as an indentation issue.

**Comment by Dario-DC** [comment]
My idea is we should provide a clear indication of the line that caused the error, and other information you would normally get from a traceback. This would help campers and it is also necessary to introduce exceptions.

**Comment by ilenia-magoni** [comment]
@ojeytonwilliams how is it going with the managing of the exceptions?

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams how is it going with the managing of the exceptions?

I haven't had chance to look at it, sorry. I may soon be blocked on some other things I need to work on and so have time for this, but I'm not sure.

**Comment by JohanSebastian117** [comment]
Thanks, found what was wrong with my code by googling and finding this post lol

**Comment by naomi-lgbt** [comment]
I'd be okay with opening this up to contributions, for anyone feeling a li'l ambitious.

**Comment by Dario-DC** [comment]
Now that #54185 has been merged, is this still needed?

**Comment by naomi-lgbt** [comment]
I don't believe so?

**Comment by Dario-DC** [comment]
I'm going to close it. I didn't realize that Oliver's PR didn't link to this issue.
