### ISSUE TITLE
[UI Components] Remove border width override from Tabs

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#54054]
## Description

Remove the following classes from the `Tabs` component:
- `border-t-[0px]`
- `border-r-[0px]`
- `border-l-[0px]`

Code: https://github.com/freeCodeCamp/freeCodeCamp/blob/dab0213d1600cd95c411393cfa37425e1d6818c2/tools/ui-components/src/tabs/tabs.tsx#L9

## Context

https://github.com/freeCodeCamp/freeCodeCamp/pull/54044#discussion_r1519553439

**Comment by shootermv** [comment]
sorry for misunderstanding -  what is the thing which need to be done?

**Comment by joelali5** [comment]
Hi @huyenltnguyen, I'm a first time contributor, and I'd like to help out with this issue. Please let me know if I should go ahead to work on this. Thanks
