### ISSUE TITLE
GA/node seed - Add most recent file commit hash to GA

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5405]
### Purpose
Capture changes to challenge files in the GA data.  This can be done by reporting on the most recent commit hash for the challenge file.  This can be looked up against the main repo to get a perfect link to a given change or collection of changes.

### Process
1. When reading in the files during the `node seed` process, also collect the most recent git hash for each file.  
This can be done from the command line:   
`git log -n1  --pretty=format:%h -- seed/challenges/01-front-end-development-certification/basic-javascript.json`  
Example Output:  
`513f2aa`
2. Store in a property like `challenge.recentHash` during `node seed`
3. When outputting to GA, append this hash to the completion message.

**Comment by evaristoc** [comment]
To find out how to transfer that information

**Comment by evaristoc** [comment]
Fragments of Dialog at Gitter (SaintPeter, evaristoc):

evaristoc said: 

> @SaintPeter: if we cannot get the reference number of the version of any change, can we add a random hash value generator to COM1000? Then the number would be added as an additional value and loaded with the challenge, as an additional number, which should be "invisible" to the users. We can then create a reference to capture that number.
> 
```
> ....
var randomString = function(length) {
     var str = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
     var result = '';
     for (var i = length; i > 0; --i) result += str[Math.round(Math.random() * (str.length - 1))];
     return result;
};
```

> we should also need to make a clear reference to that number somewhere, we may need an external script that capture and order that information somewhere, or use (what is left of...) the database to make a reference...



SaintPeter said:

> Not everyone uses COM right now, so we can't guarantee that it will be created/modified. We could just as easily write a hash function in the seeder that hashes the challenge and generates a "unique ID"
> @evaristoc Which . . actually . . . seems really trivial to do. We'd maybe use the title, description, challenge seeds, and tests as the content (maybe convert them to JSON) and just run an MD5 sum on them, every time we read them in.

**Comment by SaintPeter** [comment]
I did some further investigation and I think I convinced myself that the way to go would be a Checksum.  This one looks promising: https://www.npmjs.com/package/adler32

The only downside/problem is that it only tells you if a challenge has CHANGED, it doesn't necessarily tell you what the change was - The only information you would have is when the change started, so you'd have to go back and comb through the repo history based on date.  

My solution, as described above, was to include an SHA1 hash as well.  I spent a couple hours trying to extract an SHA1 has for a single file using `nodegit`.  It's definitely possible with the command line version (see above), but I could not get the sample code from nodegit to provide an SHA1 history for just one file.  It seemed that I was getting all changes, not just the ones affecting my file.

Regardless, if the checksum change detection is sufficient, I can get a PR going soon, I think.

**Comment by evaristoc** [comment]
That is great... tell if we can develop a sort of change control file based on those numbers? Or even some memory storage in the db. For me, the hash would be useful to follow changes in Google Analytics. If required we can go after those changes by comparing in Github... a bit cumbersome but better than what we have now...

Let's start by having the checksum and see how it goes.

**Comment by SaintPeter** [comment]
Additional thoughts:
How can we turn this check-sum into a date field?

### How to solve it, logic
#### Setup:

1. Create a "Challenge History" collection in MongoDB
2. Each challenge gets a top level entry by ID
3. Each entry has a sub-object with checksums and dates

#### Per `node seed` operation:

1. Lookup each challenge in the challenge history
2. Check to see if an entry exists for the current challenge ID  
    a. If it does, return that challenge  
    b. if it does not, create a new entry and return that challenge
3. Check to see if the checksum exists  
   a. If it does, return the associated date  
   b. If it does not, create a new entry for the checksum with the current date and return that date
4. Write the current date to the challenge/challenge collection

#### During challenge display:

1. Append the current date to the title

### Possible Issues
* On live the initial date that a challenge is loaded will affect the version of that challenge
* There may be multiple days separation between a specific change being loaded into a file and it actually going live on the servers.  It may be non-trivial to determine the prior version.
* Any `node seed` operations on development machines will also be sent to ga, potentially muddying the data.  This will primarily affect `load` and `ran-code` sub-events

**Comment by SaintPeter** [comment]
Question:
Can we tag ga events as having come from non-production?

**Comment by QuincyLarson** [comment]
We don't think we need this at this point. Camper feedback should suffice for now.
