### ISSUE TITLE
[UI Components] Use ByRole query Dropdown tests

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#54067]
## Description

Update the tests of the Dropdown component to use `getByRole()` in place of `getByText()`.

The trigger button can be queried by the `button` role:

```ts
const dropdownTrigger = screen.getByRole('button', { name: 'button text' });
```

The menu items can be queried by the `menuitem` role: 

```ts
const menu = screen.getByRole('menu')
const menuItem = within(menu).getByRole('menuitem', { name: 'item text' });
```

---
File needs to be updated: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/tools/ui-components/src/drop-down/drop-down.test.tsx.

**Comment by sankalp414** [comment]
As of I understood by the description of the issue is that you wanted to replace getByRole() to getByText() in the test file of the dropdown component if that's the case I would love to contribute to it
