### ISSUE TITLE
All tests for the `for...of` loop in the Dice game should allow campers to use `let` or `const`

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54065]
### Describe the Issue

We had this issue on the forum where the camper was unable to pass the test for step 71 with the following code.
https://forum.freecodecamp.org/t/learn-intermediate-algorithmic-thinking-by-building-a-dice-game-step-71/679051

```js
for(let num of arr){
  
}
```
The test is expecting the use of `const` inside the loop. But `let` is valid too.

 After a quick scan of the final solution, it looks like the `for...of` loop is used four times.
I have checked the tests, but it is possible that all 4 instances have the same issue where `const` is expected.
Update all 4 instances of the `for...of` tests to accept the use of `let` or `const`

### Affected Page

multiple pages

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by PrajvalaRC** [comment]
I verified other for loops at step 35, 38 and 57. All these accepts the use of let or const or var.
