### ISSUE TITLE
Dice Game - Missing some small straights

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#54079]
### Describe the Issue

You can get a small straight with `"12346"` but that's excluded.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-algorithmic-thinking-by-building-a-dice-game/step-84

### Your code

```js
  if (smallStraightsArr.some(straight => uniqueNumbersStr.includes(straight))) {
    updateRadioOption(3, 30);
  }
```

### Expected behavior

All valid small straights captured.

We should put Step 85 before the current Step 84, then update Step 84 to use something like the logic given above.

### Forum Post

https://forum.freecodecamp.org/t/learn-intermediate-algorithmic-thinking-by-building-a-dice-game-step-87/679303

### System

All

**Comment by gikf** [comment]
Alternative is adding the 4 valid cases that have 5 digits - `"13456", "12456", "12356", "12346"` - to the `smallStraightsArr`.

**Comment by jeremylt** [comment]
I think you have some invalid cases in there. You would also want to include the large straights - you can always score a large straight as a small straight if you want.

This does sorta make it the `smallStraightWithJunkIncluded` array? Which is why I proposed matching against the valid small straights.

**Comment by gikf** [comment]
> I think you have some invalid cases in there. You would also want to include the large straights - you can always score a large straight as a small straight if you want.

:eyes: Sorry, my brain suddenly forgot straight is not just random digit missing.

**Comment by jdwilkin4** [comment]
I am not sure understand the reasoning for switching steps 84 and 85.
Should the code still work keeping the original order and then just modifying step 84?

**Comment by jeremylt** [comment]
Step 85's current code is simpler than Step 84 needs to be. I think its better to introduce a simpler case of an idea first

**Comment by jdwilkin4** [comment]
I am fine with switching 85 and 84. 
Then the original 84 could test for the updated solution you original proposed as well as the one proposed on the forum.

**Comment by a2937** [comment]
I do have a question. What should every valid solution have in common? I mean I see that they all iterate through the `smallStraights` array with a callback function.  

I think I might have something but want to double check.

**Comment by jdwilkin4** [comment]
I have removed the help wanted label for now so a better consensus can be reached. 

There are basically two possible approaches here

Approach No.1:

Have campers provide the following solution mentioned in the issue

```js
  if (smallStraightsArr.some(straight => uniqueNumbersStr.includes(straight))) {
    updateRadioOption(3, 30);
  }
```
if we are going to go down this route, then the directions and the hints need to be way more explicit that this is the preferred answer.
Because as it stands right now, very few are going to reach to this answer on their own. 
Most will probably use some sort of loop like mentioned in the forum post.
https://forum.freecodecamp.org/t/learn-intermediate-algorithmic-thinking-by-building-a-dice-game-step-87/679303/5

Jeremy's solution is cleaner then trying to use some sort of forEach or for loop.
but the directions would need to be clearer to guide them to that solution. And possibly have this step be broken up into two if that were the case.

Approach No.2:

Allow for multiple answers from campers and adjust the tests accordingly.
This might be harder to test but it would allow for a variety of answers because as mentioned earlier, most would not arrive to the solution presented in the issue on their own.

**Comment by a2937** [comment]
My rough draft attempts to handle approach two, but I know I definitely missed something important.

**Comment by Nitz2611** [comment]
I agree that Approach No.1 has its merits in terms of providing a cleaner solution, but it does require clearer guidance for campers to reach that answer. I also see the value in Approach No.2, allowing for flexibility in solutions while adjusting tests accordingly.

**Comment by jeremylt** [comment]
The two approaches can't really be mixed and matched though since the array is set on a previous step.

**Comment by jdwilkin4** [comment]
After thinking about it for a few hours, I think approach two will be the best option.
I think most campers will lean towards using some sort of forEach or for loop to loop through each straight in the `smallStraightArr` and then have the if statement inside that loop. 

I'll go ahead and open this back up for contribution

**Comment by jeremylt** [comment]
Woops, mixed up my 'approaches' that I thought were Approach 1 and Approach 2. Nevermind my last comment.

Is this one of those tested by regex? I could see that being messy to capture all the user variants.

**Comment by jdwilkin4** [comment]
> Is this one of those tested by regex? I could see that being messy to capture all the user variants.

The open PR's have updated the tests to not include regex solutions

**Comment by JoyShaheb** [comment]
@jeremylt @jdwilkin4 @a2937 @Nitz2611 guys I'm sorry to join late on the conversation but here's my suggestion.
We can use `Union Sets` to cover this case where a large straight is also a small straight. 
The suggested code 
```
  const largeStraightLogic = ["12345", "23456"];
  const smallStraightLogic = ["1234", "2345", "3456", ...largeStraightLogic];
```
The Result for `12345` as first large straight
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/d3f9ef3b-4bc7-4df5-98d2-d785851a30c6)

The Result for `23456` as second and last large straight
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/17000cf5-707b-47e7-850c-0da6fd7c9a8b)

Note: The code 👇 incase if you want to reproduce the same thing to test the solution
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/ebc44413-3386-4db1-a9d5-b47b2db9e193)

**Comment by jeremylt** [comment]
> ```
>   const largeStraightLogic = ["12345", "23456"];
>   const smallStraightLogic = ["1234", "2345", "3456", ...largeStraightLogic];
> ```


This misses `"12346"` as a valid small straight though, right?

**Comment by JoyShaheb** [comment]
> > ```
> >   const largeStraightLogic = ["12345", "23456"];
> >   const smallStraightLogic = ["1234", "2345", "3456", ...largeStraightLogic];
> > ```
> 
> This misses `"12346"` as a valid small straight though, right?

it doesn't because the small straight on the serial `1-2-3-4-6` is `1-2-3-4` which is already covered on the array code
```
  const largeStraightLogic = ["12345", "23456"];
  const smallStraightLogic = ["1234", "2345", "3456", ...largeStraightLogic];
```

**Comment by jeremylt** [comment]
I don't see how adding in only the large straights helps then, as every large straight contains a small straight as a substring, by definition of a large and small straight.

**Comment by JoyShaheb** [comment]
> I don't see how adding in only the large straights helps then, as every large straight contains a small straight as a substring, by definition of a large and small straight. You still need to check if the rolled values contain a substring which is one of the valid small straights.

okay my bad, didn't see that case coming !
