### ISSUE TITLE
Add example to show campers basic markup structure for step 17 of RPG project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54075]
### Describe the Issue

We still have a high number of campers struggling with the step on how to nest the strong elements inside the existing span elements
https://forum.freecodecamp.org/search?q=step%2017%20%20%23javascript%20rpg%20after%3A2024-02-01

We should add an example of the syntax so they understand what the markup should look like.

## updated instructions 

````md
Wrap the numbers `0`, `100`, and `50` in `span` elements, and wrap those new `span` elements in `strong` elements. Then give your new `span` elements `id` values of `xpText`, `healthText`, and `goldText`, respectively.

Your answer should follow this basic structure:

```html
<span class="stat">TEXT <strong><span id="VALUE">TEXT</span></strong></span>
```
```` 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-17

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a23c1d505bfa13747c8a9b.md

Happy coding

**Comment by caffeine-addictt** [comment]
@jdwilkin4
Hey! Mind if I pick this up?

**Comment by ayushshrestha** [comment]
It was hard to understand that Instructions.

Finally got the clue

<span class="stat">XP: <strong><span id="xpText">0</span></strong></span>
<span class="stat">Health: <strong><span id="healthText">100</span></strong></span>
<span class="stat">Gold: <strong><span id="goldText">50</span></strong></span>
