### ISSUE TITLE
Certification Project not working only inside freeCodeCamp

### ISSUE THREAD

**Issue by Emeryx** [freeCodeCamp/freeCodeCamp#54083]
### Describe the Issue

On the "JavaScript Algorithms and Data Structures (Beta)" courses on the first certification project, The palindrome checker - The code works flawlessly on my localhost live server from Visual Studio Code with the same code but not inside freeCodeCamp. In fact, It won't show up a result at all besides the alert that the input is null

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-palindrome-checker-project/build-a-palindrome-checker

### Your code

HTML:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Palindrome Checker</title>
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
        <h1>Is it a Palindrome?</h1>
        <div id="interactive-menu">
            <form id="IsPalindrome">
                <label for="text-input">Enter in text to check for a palindrome</label><br><br>
                <input type="text" id="text-input">
                <button id="check-btn">Check</button>
            </form>
            <div id="result"></div>
        </div>
        <div id="explanation">
            <p>&#128161; A palindrome is a word or sentence that's spelled the same way both forward and backward, ignoring punctuation, case, and spacing.</p>
        </div>
        <script src="script.js"></script>
    </body>
</html>


```
CSS:
```
*,::before,::after{
    box-sizing:border-box;
    text-align:center;
}
body{
    font-size:22px;
    overflow:hidden;
    background-color:rgb(28, 16, 56);
}
#text-input{
    height:30px;
}
input,button{
    font-family:Verdana, Geneva, Tahoma, sans-serif;
    color:rgb(39, 14, 0);
}
h1{
    color:rgb(255, 254, 253);
    font-family:Verdana, Geneva, Tahoma, sans-serif;
}
p,span{
    font-family: monospace;
    color:rgb(2, 19, 0);
    letter-spacing:2px;
}
label{
    font-family: monospace;
    color:rgb(2, 19, 0);
}
body{
    margin: 5% 40% 5% 40%;
    display:flex;
    flex-direction:column;
    gap:32px;
}
div{
    width:100%;
}
button{
    background-color:rgb(65, 226, 73);
    color:rgb(2, 19, 0);
    border:3px solid rgb(2, 19, 0);
    border-radius:16px;
    -webkit-border-radius:16px;
    -moz-border-radius:16px;
    -ms-border-radius:16px;
    -o-border-radius:16px;
    padding:10px;
    cursor:pointer;
}
#explanation{
    background-color:rgb(65, 226, 73);
    padding:10px;
    border-radius:32px;
    -webkit-border-radius:32px;
    -moz-border-radius:32px;
    -ms-border-radius:32px;
    -o-border-radius:32px;
}
#text-input{
    border:none;
    border-bottom: 3px solid rgb(39, 14, 0);
}
#interactive-menu{
    background-color:white;
    padding:40px 10px 10px 10px;
    border-radius:32px;
    -webkit-border-radius:32px;
    -moz-border-radius:32px;
    -ms-border-radius:32px;
    -o-border-radius:32px;
    margin-top:-7%;
}
#result{
    margin: 20px 0;
}
@media (max-width:1384px) and (min-width:790px){
    body{
        margin: 5% 30% 5% 30%;
    }
}
@media (max-width:789px) and (min-width:466px){
    body{
        margin: 5% 20% 5% 20%;
    }
}
@media(max-width:465px){
    body{
        margin: 5% 10% 5% 10%;
    }
}
```
JS:
```
const checkBtn = document.getElementById("check-btn"); // Const button element
const alphanumericChars= /[a-zA-Z0-9]/g; // [] regex character class and global flag
const result = document.getElementById("result");
const isPalindrome = () => { // Main function, Checks if the text input is a Palindrome. Goes to yesPalindrome() and noPalindrome() accordingly
    const input = document.getElementById("text-input").value;
    if(input=="" || input==null){ // No value
        return alert("Please input a value");
    }
    const filteredInputArr = input.toLowerCase().match(alphanumericChars);
    const inputInvertedArr = [filteredInputArr[filteredInputArr.length-1]];
    for(i=filteredInputArr.length-2;i>=0;i--){ // Creates an inversion of the filtered input and puts it into inputInvertedArr
        inputInvertedArr.push(filteredInputArr[i]);
    }
    if(filteredInputArr.every((element,index)=>element===inputInvertedArr[index])){ // Checks if all the elements inside filteredInputArr are equal to inputInvertedArr's
        return yesPalindrome(input);
    }
    return noPalindrome(input);
}
const yesPalindrome = (input) => {
    result.innerHTML=`<span style="font-weight:bold">${input} </span><span>is a palindrome</span>`;
}
const noPalindrome = (input) => {
    result.innerHTML=`<span style="font-weight:bold">${input} </span><span>is not a palindrome</span>`;
}
document.getElementById("IsPalindrome").addEventListener("submit",(event)=>{event.preventDefault();isPalindrome()}); // What does the form do when it's submitted
checkBtn.addEventListener("click",isPalindrome); // What the button does when clicked


```

### Expected behavior

I expect to pass the test? It's working great on my localhost

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/7b645d39-8f77-4182-a70f-f9a3aac99e1a)

Inside freeCodeCamp the button won't do anything:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/2373d47a-6000-41f1-971d-ffb7594feffc)

Outside freeCodeCamp:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/bcb3a878-6739-4680-a15a-6c5ae5d7bee7)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/bf103c60-9d0e-4cd5-9390-72906e89b6ea)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/00ac8a35-e461-4e78-b0d8-52efe5d1d502)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/7426d84e-8ec2-4bdc-9d98-709f4be6f990)

### System

- Device: PC
- OS: Windows 10
- Browser: Chrome and Opera GX
- Version: Chrome 122.0.6261.128, Opera GX LVL5 (core: 107.0.5045.60) (Kind of unsure specifically about the Opera GX version?)

### Additional context

I tried setting the eventListener for when #check-btn is clicked instead of the whole form being submitted, But kept it because of the way I want the input to be sent when I click enter on my keyboard

I also tried setting an onClick action attribute on the HTML #check-btn element itself

I also tried removing the span elements from the javascript file, inside the yesPalindrome and noPalindrome arrow functions

Huge thanks in advance if hopefully there's a fix for this

**Comment by tatbatAli** [comment]
Also there's an issue in this storie "When the #text-input element contains the text 1 eye for of 1 eye. and the #check-btn element is clicked, the #result element should contain the text "1 eye for of 1 eye. is not a palindrome". This sentence "1 eye for of 1 eye." is a palindrome but in storie it's the opposite. I completed all the stories but this it give me a false mark.

**Comment by gikf** [comment]
@Emeryx 

Thank you for reporting this issue.

Editor on page runs in the strict mode. This means that all variables have to be declared. If you take a look at the console, after running tests, there's couple errors `Uncaught ReferenceError: i is not defined`. Because of that I'm going to close this issue.

Thank you and happy coding.

- - -

@tatbatAli

By the requirements defined in the project, the `1 eye for of 1 eye.` string is not a palindrome.  Please click the **"Get Help"** button on the challenge on freeCodeCamp and choose the **"Ask for help"** option, which will help you create a question in the right part of the forum.

Happy coding
