### ISSUE TITLE
Boilerplates still reference replit

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#54088]
All the boilerplates should be audited and the replit reference should be removed

for example:
https://github.com/freeCodeCamp/boilerplate-infosec/blob/715c6f120d69826eb87ea002f2642306c28ab28d/views/index.html#L23-L27

here the "fork on replit" text and link should be removed.

**Comment by shootermv** [comment]
is there something that should be placed instead of the fork-on-replit link? (after its removal)

**Comment by Supravisor** [comment]
1. https://github.com/freeCodeCamp/boilerplate-infosec/blob/715c6f120d69826eb87ea002f2642306c28ab28d/views/index.html
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/bc8f07fee4f4f552a07307ee55cec65903945da9/client/src/pages/learn/information-security/information-security-with-helmetjs/index.md

**Comment by shootermv** [comment]
@Supravisor - is those list of files are files there the replit link should removed?

**Comment by VKSGit2017** [comment]
@Supravisor , Is the below reference to Replit still required considering Codespace in GitHub?

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/30977545/73b4b5a5-e06f-4fff-a57e-1911efe1e666)

**Comment by ilenia-magoni** [comment]
@VKSGit2017 no, it's not, that's one of the files being changed by the linked PRs. At this point only the boilerplate for info-sec is still mentioning replit, the others have a PR

**Comment by ilenia-magoni** [comment]
have the other boilerplates been checked?

**Comment by samGreer** [comment]
> have the other boilerplates been checked?

I searched for replit in the freeCodeCamp org and it seems like the only boilerplate that still mentions it has been archived

**Comment by ilenia-magoni** [comment]
Thank you @samGreer ! I am closing this issue as completed
