### ISSUE TITLE
Confusion Regarding Additional "strong" Element in ".stat" Elements

### ISSUE THREAD

**Issue by devkan** [freeCodeCamp/freeCodeCamp#54081]
### Describe the Issue

I've noticed a potential area of confusion in the HTML structure that involves the use of strong elements within .stat elements. According to the instructions received, there seems to be a misunderstanding regarding the need for an additional strong element in the first .stat element. 
However, upon reviewing the provided code snippet, it appears that the strong element is already correctly implemented within each .stat element, including the first one.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-17

### Your code

```html
<span class="stat">XP: <strong><span id="xpText">0</span></strong></span>
<span class="stat">Health: <strong><span id="healthText">100</span></strong></span>
<span class="stat">Gold: <strong><span id="goldText">50</span></strong></span>
```

### Expected behavior

The expected behavior, as per the initial instructions, is that each .stat element should contain a single strong element wrapping a span element with the appropriate ID. 
The current implementation matches this expectation.

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 122.0.6261.112

### Additional context

This is my first time making a pull request, and I'm not sure if I've done it correctly. 
If there are any mistakes, please let me know. 
Thank you for giving me this opportunity.

**Comment by ilenia-magoni** [comment]
I don't understand what you are reporting, the `strong` elements are not present in the starting code

**Comment by devkan** [comment]
I'm sorry. 
It's my first time making a PR, so I ended up creating a new issue instead. 
Apologies once again.

**Comment by devkan** [comment]
I'm sorry.
It's my first time making a PR, so I ended up creating a new issue instead.
Apologies once again.
