### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-headline-with-the-h2-element has an issue 

### ISSUE THREAD

**Issue by shcolligan** [FreeCodeCamp/freecodecamp#541]
I don't know if "bugs" is where typos go, but.... the checklist on this page has:

Create an h2 elements.

There should not be an s at the end.

(Also: This report a bug button took me to Github, but as an FCC student at HMTL level I don't yet have a Github account or Github orientation.)

**Comment by terakilobyte** [comment]
Thanks for the heads up. This is already fixed in a pending push to production. Keep em coming though.

Regarding the github account stuff, it's true users may not have one yet but it's a very easy signup process.

**Comment by shcolligan** [comment]
Nothing is easy if you are new, and your teachers give you no warning or
explanation...

**Comment by terakilobyte** [comment]
That's a good point. We'll make sure to add a "Sign up for GitHub" waypoint in the "Intro to FreeCodeCamp" section. Thanks!
