### ISSUE TITLE
Add a Note on How the Players are Numbered for team cards project

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#54118]
### Describe the Issue

In football, the number 1 jersey is always reserved for the number 1 goalkeeper in the team. In any case where the number 1 goalkeeper is not wearing the number 1 jersey, it means they prefer that other number they're wearing.

In the project, one of the team forwards, Sergio Almirón has the number 1. This is because the squad is numbered alphabetically according to surname (Almirón starts with A).

We need to add a note to both step 1 and 12 that the squad is numbered based on the players' surnames.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-1, https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-12

### Your code

N/A

### Expected behavior

There should be a way to let campers know how the players are numbered.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Look here for more details: https://en.wikipedia.org/wiki/1986_FIFA_World_Cup_squads

**Comment by jdwilkin4** [comment]
The note could be this

```md
_NOTE_:  The numbers for the team are organized alphabetically by last name. This differs from conventional numbering where the numbers correspond with what is on the player's jerseys. 
```

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-modern-javascript-methods-by-building-football-team-cards/63c620161fc2b49ac340ffc4.md

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-modern-javascript-methods-by-building-football-team-cards/63d1214a0ac7a9389793269b.md

Happy coding
