### ISSUE TITLE
An Error in "Regular Expressions (RegEx) in JavaScript – A Handbook for Beginners"

### ISSUE THREAD

**Issue by Tsukistar** [freeCodeCamp/freeCodeCamp#54126]
### Describe the Issue

I wanted to bring to your attention an error I discovered in the article titled "Regular Expressions (RegEx) in JavaScript – A Handbook for Beginners." In Part 2 of the article, specifically in the section "How to Use Regular Expressions in JavaScript," there is a code block near the paragraph  " You can use regular expressions with various methods available for both the RegExp and String objects in JavaScript. Some methods like test(), exec(), and others have this syntax:  ".   The code block reads:

```javascript
regex.methodname(string) 
// example 
string.test(string)
```

### Affected Page

https://www.freecodecamp.org/news/regex-in-javascript/#how-to-use-regular-expressions-in-javascript

### Steps to Reproduce

It's a tiny error in an article.

### Recommended fix or suggestions

Upon careful examination, it appears that the 'test()' method is incorrectly applied to the 'string' object. However, according to JavaScript syntax, 'test()' is a method of the RegExp object. Thus, the correct code should be:

```javascript
regex.methodname(string) 
// example 
regex.test(string)
```

**Comment by jdwilkin4** [comment]
HI @Tsukistar ! 

I have alerted the editorial team

**Comment by jdwilkin4** [comment]
Heard back from the editorial team and they have alerted me that the article has been updated.
As a result, I am going to close this issue
