### ISSUE TITLE
Learn Basic Algorithmic Thinking by Building a Number Sorter - Step 34

### ISSUE THREAD

**Issue by notS0Solo** [freeCodeCamp/freeCodeCamp#54136]
### Describe the Issue

Test fails every time with the same fail message.  "Your while loop should decrement `j` inside the loop." I've tried every different iteration of code that decrements `j`. I've consulted Slack and Google. The code works.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-algorithmic-thinking-by-building-a-number-sorter/step-34

### Your code

```
const insertionSort = (array) => {
  for (let i = 1; i < array.length; i++) {
    const currValue = array[i];
    let j = i - 1;
   while (j >= 0 && array[j] > currValue) {
      array[j + 1] = array[j];
      j--;
    }
   array[j + 1] = currValue;
  }
}


```

### Expected behavior

I expected the test to pass. The code works. 

### Screenshots

![Monosnap Learn Basic Algorithmic Thinking by Building a Number Sorter:Step 34](https://github.com/freeCodeCamp/freeCodeCamp/assets/114703625/676800a7-1f35-416a-a339-f487b94887fb)

### System

- Device: [macOS Monterey]
- OS: [version 12.6.5]
- Browser: [Chrome]
- Version: [122.0.6261.129]

### Additional context

I've tried every iteration of Javascript code that decrements. None work. I've consulted multiple sources and all say the code works. I have followed the recommended troubleshooting steps-- https://www.freecodecamp.org/news/how-to-report-a-bug-to-freecodecamp/.

**Comment by jdwilkin4** [comment]
Looking at the tests it looks like the test doesn't account for extra information.

Right now you are provided the full solution but it looks like the breakdown of the steps wants you to arrive at that solution over time.

For example, here is the answer for step 34

```js
const insertionSort = (array) => {
  for (let i = 1; i < array.length; i++) {
    const currValue = array[i];
    let j = i - 1;

    while (j >= 0 && array[j] > currValue) {

      j--;
    }
  }
}
```
here step 35

```js
const insertionSort = (array) => {
  for (let i = 1; i < array.length; i++) {
    const currValue = array[i];
    let j = i - 1;

    while (j >= 0 && array[j] > currValue) {
      array[j + 1] = array[j];
      j--;
    }

  }
}
```
here is step 36
```js
const insertionSort = (array) => {
  for (let i = 1; i < array.length; i++) {
    const currValue = array[i];
    let j = i - 1;

    while (j >= 0 && array[j] > currValue) {
      array[j + 1] = array[j];
      j--;
    }
    array[j + 1] = currValue;
  }

}
```
so it looks like the test would need to find a different way to test for the specific information the steps want and ignore any extra code the user provides

**Comment by notS0Solo** [comment]
I had tried simpler versions of the code, as well, as the code I posted. So I went back and looked at my previous attempts. I had tried the correct solution. It didn't work because I had an extra closing bracket. So thank you!

**Comment by JoyShaheb** [comment]
@jdwilkin4  should we write a case where users can input anything they want before and after the code `j--` or should we just close this issue ?

**Comment by jdwilkin4** [comment]
I vote we close this issue because the main issue seems to be resolved.
I haven't seen this pop up a lot on the forum, so we can leave the tests as is for now.
If this does become an issue later on, then we can revisit this at that time and proceed from there.
