### ISSUE TITLE
Waypoint: Condense arrays with reduce

### ISSUE THREAD

**Issue by Nadir-Git** [FreeCodeCamp/FreeCodeCamp#5413]
To my understanding, the summing should return 30 but it returns 0 and takes it as the correct answer. Have I understood it wrongly or is this any bug? Kindly help me to get clarity on this one.

**Comment by Jinishc** [comment]
It does return 30. I think you should check your code.
![screenshot from 2015-12-22 16 47 28](https://cloud.githubusercontent.com/assets/5639238/11954112/c848ee40-a8cb-11e5-8784-89ec350af0b1.png)

**Comment by ltegman** [comment]
I am unable to pass this challenge with 0 as my output. If you continue experiencing this problem please provide steps to reproduce, including the code you are submitting.
