### ISSUE TITLE
Confirm that each route that should be public or private actually is

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#54143]
As Tom pointed out in https://github.com/freeCodeCamp/freeCodeCamp/pull/53997#discussion_r1529986855, some routes that need to be public are not. We should make sure that all the routes are public/private as determined by
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/middlewares/request-authorization.js

It should also be completely unambiguous what any given route is. For example, we could separate routes into folders: /routes/public and /routes/private

**Comment by moT01** [comment]
Here's a few endpoints that need to be open I believe: https://github.com/freeCodeCamp/freeCodeCamp/blob/c1137b0900ad098fee2fca430d11f69dfc909d3b/api-server/src/server/middlewares/csurf.js#L17

Those two donate ones haven't been created yet.

**Comment by zeffanine-aimen** [comment]
Hi @ojeytonwilliams and the freeCodeCamp team,

I've been reviewing the issue #54143 regarding the visibility of routes and have some suggestions that I believe could enhance the clarity and maintainability of the route authorization logic.

**Proposed Changes:**
- **Separate Public and Private Routes**: Create two new directories within the `routes` folder: `public` and `private`. This will make it easier for contributors to understand which routes are accessible without authentication.
- **Refactor the `isAllowedPath` Function**: Update the function to dynamically build the list of public paths based on the files present in the `public` routes directory. This approach could reduce the complexity of the current regex-based system and improve scalability.

**Benefits:**
- **Clarity**: Having a clear separation of public and private routes in the file structure will make it easier for new contributors to understand the codebase.
- **Maintainability**: By dynamically generating the list of public routes, we can avoid potential errors that might arise from manually updating regex patterns as new routes are added or changed.

**Next Steps:**
I would like to implement these changes and submit a PR for review. However, before proceeding, I wanted to discuss with you to ensure that these changes align with the project's goals and standards.

I'm looking forward to your feedback and any suggestions you might have.
note : "I am a beginner"

**Comment by ojeytonwilliams** [comment]
The current differences between the old and new apis are

## Deprecated endpoints which have become public

- /refetch-user-completed-challenges 
- /certificate/verify-can-claim-cert
- /api/github
- /account

Since all they do is respond with a generic message, I don't think anything needs to be done.

## Signout

/signout is now public. I don't see how this could be an issue, but the api does a little more than simply respond, so I'll change it.

**Comment by ojeytonwilliams** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/56359 is in, so this can be closed.
