### ISSUE TITLE
I want to learn cord

### ISSUE THREAD

**Issue by subhendupaul** [FreeCodeCamp/FreeCodeCamp#5414]
Challenge [Waypoint: Headline with the h2 Element](http://www.freecodecamp.com/challenges/waypoint-headline-with-the-h2-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Cdiv%3E%0A%20%20%3Cp%3Ehi%3C%2Fp%3E%0A%3C%2Fdiv%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<div>
  <p>hi</p>
</div>
```

**Comment by JTLX** [comment]
What is the issue?

**Comment by ltegman** [comment]
Please reopen with a description of the problem and steps to reproduce if you are experiencing a bug. Otherwise please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help)

Thanks and happy coding!
