### ISSUE TITLE
Donation progress bar UI/UX

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#54156]
### Describe the Issue

The progress bar animation gives off a stuck-loading vibe. I'd suggest not animating the progress and just filling it in.

As mentioned in the forum thread this can be labeled better as well. E.g. "Progress toward donation goal" or whatever.

### Affected Page

https://www.freecodecamp.org/learn

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Less potentially confusing UX/UI

### Screenshots
![progress-bar](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/b3559557-e26e-41e5-a98b-809222cb5788)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/freecodecamp-wont-load/680791

**Comment by imonish8** [comment]
I guess that is progress of how much they have made so far to reach 20,000 monthly supporters. But I  would prefer a circle or 360 pie graph to show the progress 

That must have confuse supporters and supporter must have just stopped donations too.

Can I make one for it? 

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/115737071/11c4c44d-fad2-425e-8e57-166f1fdd3c1e)

**Comment by lasjorg** [comment]
@imonish8 The issue has not been triaged yet so I would wait.

My issue is not with the use of a progress bar but what an animated progress bar represents and how it is interpreted. Users may associate it with a loading state.

The block would work better with a heading as well.

**Comment by bbsmooth** [comment]
I agree that a heading would be a good addition. I'm not exactly sure what that heading should read, but it should help explain what the percentage is for, and it should be an `h2`. The percentage is currently in an `h3`, but it's not acting as a heading, so it should be in a `p` element, and we might need to add some visually hidden text after the percenrage to help screen reader users understand what it is for (depending on the heading text). 

Also, can we get rid of the `hr` between the text and the Donate button? You can barely see it, and I'm not sure what purpose it serves, and it's just extra unnecessary noise that screen reader users have to listen to.

**Comment by Vijaykv5** [comment]
I would love to work on this if the issue has been triaged

**Comment by lasjorg** [comment]
Just to be clear, this is also based on user feedback. The user thought the page was stuck loading. Not saying that the feedback from a single user is a great metric, but I do understand why someone might think that.

If the progress bar was filling in, having that type of animation would be fine. The fact that it stays at the same progress for as long as it does (the user will likely never see it move in real-time) makes the animation more ambiguous.

As I said, it would work better with a heading. But if we need to "label" a UI element to explain what its purpose is, then there might also be an issue with the UI element semantics.

---

Personally, I'm also not particularly crazy about the look/style. Maybe just a simple gradient, going from red/orange to teal/green might work.

Simple example:
![progress-bar](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/0890dda2-a27a-4437-a034-42bc862824b9)
