### ISSUE TITLE
Learn Regular Expersions by Building a Password Generator Step 47

### ISSUE THREAD

**Issue by ludusregio** [freeCodeCamp/freeCodeCamp#54157]
### Describe the Issue

Learn Regular Expressions by Building a Password Generator Step 47 states the following as a request.
>Now, create your fourth pattern to match any non-alphanumeric character. Combine the a-z, A-Z, and 0-9 ranges into a single character class and add a ^ as the first character to negate the pattern.

The wording: "create your fourth pattern" is ambiguous enough to promote confusion in what it is asking, since the code already contains a four patterns sets. Furthermore, there's a built-in assumption in the request that the reader will be able to identify which one is the fourth pattern (top to bottom, bottom to top. randomly?) which adds no value in the learning process.

```
        constraints = [
            (nums, r'\d'),
            (lowercase, r'[a-z]'),
            (uppercase, r'[A-Z]'),
            (special_chars, r'')
        ]  
```

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/step-47

### Your code

N/A

### Expected behavior

N/A

### System

N/A

### Additional context

I believe a clearer request could had been issue, like:
>>Now, modify the given fourth member of the array `constraints` to form a pattern that matches any non-alphanumeric character. Combine the a-z, A-Z, and 0-9 ranges into a single character class and add a ^ as the first character to negate the pattern.

**Comment by Dario-DC** [comment]
Honestly, it seems pretty straightforward to count from top to bottom (which has been already done in previous steps). Also, the word "create" is used since the pattern is an empty string.  But if it helps I'm happy with @zairahira 's suggestion:
> modify the last constraint pattern to match ...

**Comment by ludusregio** [comment]
> Honestly, it seems pretty straightforward to count from top to bottom (which has been already done in previous steps). Also, the word "create" is used since the pattern is an empty string. But if it helps I'm happy with @zairahira 's suggestion:
> 
> > modify the last constraint pattern to match ...
When you do not know, things are not that simple or straightforward. It is perfectly normal not to know quite yet what a pattern is (the learner is in the process of understanding) even if a previous step introduces it.

**Comment by zairahira** [comment]
I'll open this up for contribution. Let's go with this updated description:

```
In a character class, you can combine multiple ranges by writing one range after another inside the square brackets (without any additional characters). For example: `[a-d3-6]` is the combination of `[a-d]` and `[3-6]`.

Now, modify the last constraint pattern to match any non-alphanumeric character. Combine the `a-z`, `A-Z`, and `0-9` ranges into a single character class and add a `^` as the first character to negate the pattern.
```

**Comment by Dario-DC** [comment]
> There are evidence in the forum that shows people thinking that the pattern is the whole tuple.

I see your point. But if that is the case, what a pattern is should be clarified/repeated way before than this step (this does not mean we are not going to modify this step).

Probably, the entire logic behind the validation of the generated password should be clarified a bit.
