### ISSUE TITLE
Move spam filter project earlier in the JS certification

### ISSUE THREAD

**Issue by mjodonnell** [freeCodeCamp/freeCodeCamp#54168]
### Describe the Issue

Is it possible that the new Beta Javascript curriculum is out of order at one particular place? I am at the “Learn…While Building a Spreadsheet” part of the curriculum and it seems to be asking me to implement RegEx in ways we haven’t explored at all up to this point (unless I am overlooking something). I see, though, that the next task/exercise is “Learn RegEx…”

Was this an oversight? Or have I missed something?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-37

### Your code

```
//??//


```

### Expected behavior

As noted in description, it doesn't seem like we have learned this much RegEx in the course up to this point. I wondered if these exercises were placed out of order as RegEx is explored in more depth in the next exercise.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
In the early development stages, that was the original order. But as revisions where being made, it looks like it was overlooked to move this project earlier on in the block. 

I think this project would work better in the beginning of this block before the number sorter project.

We will wait to hear from the rest of the JS team though.

**Comment by jdwilkin4** [comment]
We will move forward with updating the ordering.

## Note to interested contributors
We are going to change the ordering for this block only. The rest of the project order should not be changed.

Here is the current block 
<img width="904" alt="Screenshot 2024-04-01 at 8 45 40 AM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/67210629/0225b86f-19be-4885-8e27-b4c76558ec55">

The new order should be the following:

1. spam filter
2. number sorter
3. stats calculator 
4. spreadsheet

in each of the project `meta.json` files, there is an order key and value like `  "order": 17,`
So you will need to update the order for those projects so it matches the new order described above. 

If you need help on where to make updates, you can look to this older PR
https://github.com/freeCodeCamp/freeCodeCamp/pull/52529/files

**Comment by samGreer** [comment]
Hi all, I just submit a PR for this, following the order listed in @jdwilkin4's comment! PR can be found here: https://github.com/freeCodeCamp/freeCodeCamp/pull/54280

Let me know if I misunderstood anything or need to make any changes!
