### ISSUE TITLE
Doesn't seem to have a function call, but works in console.

### ISSUE THREAD

**Issue by Jurtly** [FreeCodeCamp/FreeCodeCamp#5417]
Challenge [Waypoint: Count Backwards With a For Loop](http://www.freecodecamp.com/challenges/waypoint-count-backwards-with-a-for-loop#?solution=var%20ourArray%20%3D%20%5B%5D%3B%0A%0Afor%20(var%20i%20%3D%2010%3B%20i%20%3E%200%3B%20i%20-%3D%202)%20%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0A%0Avar%20myArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afor%20(var%20i%20%3D%209%3B%20i%20%3E%200%3B%20i%20-%3D%202)%20%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = [];

for (var i = 10; i > 0; i -= 2) {
  ourArray.push(i);
}

var myArray = [];

// Only change code below this line.

for (var i = 9; i > 0; i -= 2) {
  ourArray.push(i);
}


```
<p color="#333"> ???? Is the function missing to call? Sorry, still noob </p>

**Comment by sludge256** [comment]
Change the name of the array you are pushing values to.

**Comment by Jurtly** [comment]
wow. thank you so much!

*must. read. slower*
