### ISSUE TITLE
Add Gitpod instructions on how to share code/workspaces

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#54189]
### Describe the Issue

It is often difficult to help people because we do not get access to their code on Gitpod.

Can we please include information on how to ask for help and share code/workspaces in the [How to Use Gitpod in the Curriculum](https://forum.freecodecamp.org/t/how-to-use-gitpod-in-the-curriculum/668669) thread?

Gitpod docs

https://www.gitpod.io/docs/configure/workspaces/collaboration

### Affected Page

https://www.freecodecamp.org/learn/

### Your code

```



```

### Expected behavior

Access to code so we can help people

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Thanks for bringing this up. The main issue I see is:

> **Access to secret information** - Snapshotted workspaces do not grant access to Gitpod environment variables, Gitpod authentication or Git credentials within a snapshot. However, you should use caution that you did not store any secret or private information in any files of a workspace snapshot before generating a snapshot URL.

That is, Campers who include a `.env` file with their PATs/keys, will need to be sure to delete the file before snapshotting.

**Comment by lasjorg** [comment]
I guess all we can do is warn people in the instructions. As it is now, it's hopeless trying to help people without access to their code. This seems like an oversight on our part when switching to Gitpod.

Gitpod not having a way to share code without leaking env files is also pretty silly. It could be something as simple as if a file is git ignored it shouldn't be part of the snapshot. Or some config option to purge env files on snapshots. They really should have a solution for this.

One option would be to instruct the campers to use the user variables instead of env files.

https://gitpod.io/user/variables

**Comment by naomi-lgbt** [comment]
> One option would be to instruct the campers to use the user variables instead of env files.

I feel like that's just right back into the Replit `.env` mess from last year.

I wonder if it would be better to teach campers how to push from GitPod to a git repo.

**Comment by lasjorg** [comment]
Not sure. All I know is, it is really difficult to help people with their code when you can't see it.

**Comment by naomi-lgbt** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/77809380-122b-47dd-b4eb-eda3398a9485)

Okay, I [added a section](https://forum.freecodecamp.org/t/how-to-use-gitpod-in-the-curriculum/668669#how-can-i-share-my-workspace-to-get-help-8) to the forum post.

**Comment by Mofazzal-Hossain-Evan** [comment]
facing this problem, Error running command gitpod.workspaces.connectInCurrentWindow_context: Invalid URL: https:/<REDACTED: user-file-path>. This is likely caused by the extension that contributes gitpod.workspaces.connectInCurrentWindow_context.
