### ISSUE TITLE
Remove isBeta flag from challenge meta

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#54191]
### Describe the Issue

Many of the meta.json files have an `isBeta` flag. I'm pretty sure it doesn't do anything. There's some other area where this variable exists - [see here.](https://github.com/search?q=repo%3AfreeCodeCamp%2FfreeCodeCamp%20isBeta&type=code) It says it's for showing things during dev or on .dev, but we have `showUpcomingChanges` for that now. If we aren't using it anywhere, we can probably remove it from all of those locations.

**Comment by mercy-manynge** [comment]
Hello, I'm interested to do this one.
It's my first time though.

**Comment by utf26** [comment]
@mercy-manynge how do you setup the project?
I need actual .env file and setup instructions please.

**Comment by moT01** [comment]
Thanks for your interest @mercy-manynge @utf26. This issue is still being triaged. We are not sure if we want to do this yet. I would look for an issue with a help wanted label. You can learn more about how to set things up and contributing in our [contributing documentation](https://contribute.freecodecamp.org/#/index)

**Comment by mercy-manynge** [comment]
Thank you @moT01

**Comment by naomi-lgbt** [comment]
I think this should be fine to remove, yeah. I'm not seeing it being consumed anywhere.
