### ISSUE TITLE
The left side of the "Skip to content" button's outline is not visible

### ISSUE THREAD

**Issue by mmatsumoto1026** [freeCodeCamp/freeCodeCamp#54194]
### Describe the Issue

It seems that the left side of the "Skip to content" button's outline is extending off the screen.

### Affected Page

Pages with `Header` component

### Steps to Reproduce

1. Go to [/learn](https://www.freecodecamp.org/learn) page
2. Press Tab key once to be focused on the "Skip to content" button and make it visible
3. See the outline of the button

### Expected behavior

The position of the button should be properly aligned and the outline should be visible.

### Screenshots

<details>
<summary>"Skip to content" button in /learn page</summary>

<img src="https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/6a537732-c4c0-4e7e-a54a-d042b31d07fb" width="500">
</details>

### System

- Device: Laptop
- OS: Windows 11 Home
- Browser: Chrome
- Version: 123.0.6312.58 (Official Build) (64-bit)

### Additional context

With reffering this [fCC's article](https://www.freecodecamp.org/news/how-to-add-skip-to-main-content-links-to-a-website/), the button and its outline should probably be aligned to the left edge of the search bar (on screens wider than or equal to 980px) or the fCC logo (on screens less than 980px).

**Comment by Lalithkumarponnambalam** [comment]
hello @gikf,
Could you please explain the expected behavior where the **"skip to button"** will be aligned correctly on the page, and also confirm if my understanding is correct that the **skip to button** should only be visible when the tab is clicked?
