### ISSUE TITLE
fix assertion test on step 68 on music player project 

### ISSUE THREAD

**Issue by Re1nGer** [freeCodeCamp/freeCodeCamp#54192]
### Describe the Issue

The method  ```setAttribute()``` should be placed outside of function ```setPlayButtonAccessibleText()```, but the test passes in both cases, which is supposed to be wrong. 

According to the test in ```curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/6555de565387a2efe90a6ccc.md```: 

> You should not modify the existing `setPlayButtonAccessibleText` function and its content.

```js
assert.match(code, /const\s+setPlayButtonAccessibleText\s*=\s*\(\s*\)\s*=>\s*\{\s*const\s+song\s*=\s*userData\?\.currentSong\s*\|\|\s*userData\?\.songs\s*\[\s*0\s*\]\s*;?\s*.*\s*.*\s*.*\s*.*\s*\}\s*;?/)
```
So, it seems that the assertion above doesn't work. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-68

### Your code

```
```

### Expected behavior

The test should not pass if ```setAttribute()``` method is used inside ```setPlayButtonAccessibleText()```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Could you provide example code that should not be passing? From the step context it appears that attribute should be set within the `setPlayButtonAccessibleText` function, not outside of it.

**Comment by Re1nGer** [comment]
@gikf sure, here's an example code that should fail: 
```
const setPlayButtonAccessibleText = () => {
  const song = userData?.currentSong || userData?.songs[0];
  playButton.setAttribute("aria-label", song?.title ? `Play ${song.title}` : 'Play');
};
```
I making an assumption that it should fail by one of the tests that's written in ```.md``` file, but this test never fails. 
you can also set this up like this: 
```
const setPlayButtonAccessibleText = () => {
  const song = userData?.currentSong || userData?.songs[0];
};
playButton.setAttribute("aria-label", song?.title ? `Play ${song.title}` : 'Play');
``` 
and it will pass too. At least one of the should fail.

**Comment by aliomarmohamed** [comment]
Hi,
that is my first project to contribute to so I need some help , I noticed that when i clicked on  NightMode button  the word  "NightMode" does not changed to "lightMode" so I want to fix this bug , but I need some help

**Comment by gikf** [comment]
Hey @aliomarmohamed

this issue is not a place for that. Please see https://contribute.freecodecamp.org/#/ for the Contribution Guidelines. For creating new issue please check https://github.com/freeCodeCamp/freeCodeCamp/issues/new/choose.

**Comment by gikf** [comment]
> You should not modify the existing `setPlayButtonAccessibleText` function and its content.

@Re1nGer, wording might not be ideal, however the intent is to make sure the function code present at the start of step: 
```javascript
const setPlayButtonAccessibleText = () => {
  const song = userData?.currentSong || userData?.songs[0];
};
```
Is still there after function is modified to set the desired attribute.

The case with `playButton.setAttribute(...)` being outside of the `setPlayButtonAccessibleText` function should not pass.

**Comment by Re1nGer** [comment]
@gikf I see, so then, the test case should make sure ```playButton.setAttribute(...)``` is indeed inside ```setPlayButtonAccessibleText ```
