### ISSUE TITLE
Use disclosure widget to show/hide more details in challenges

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#54190]
### Describe the Issue

I can't remember if we have talked about this before.

With the current editor layout explaining a concept and giving example code can get awkward. Because the instructions are inside the code it can push the code too far away from the instructions.

It would be nice to have the option to disclose more details and example code in the challenge text.

```
Base explanation

<details>
  <summary>More details:</summary>
  More detailed explanation and code example
</details>

Requirements
```

### Affected Page

https://www.freecodecamp.org/learn

### Your code

```



```

### Expected behavior

Less shallow explanations because of limitations in the layout and allowing the camper to disclose more details as needed.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Sembauke** [comment]
Why not make the upper-jaw scrollable? Make it have a fixed height and a shown scrollbar, when needed.

**Comment by lasjorg** [comment]
That doesn't hide the content.

The idea is to have more information if the camper needs it, without having it take up space before they need it. Or just quickly toggle it visible/hidden as needed.

**Comment by gova646** [comment]
Could you please provide a more detailed explanation of the issue. Also can you please provide the links to the respeccive pages where the changes are required.In the link https://www.freecodecamp.org/learn/ I donot see summary in it.

**Comment by a2937** [comment]
Okay so near as I can tell, we want the code examples collapsible. Which seems to be coming from right around here right? https://github.com/a2937/freeCodeCamp/blob/1cab4b5797a50618ab51dc91441167e983e3f715/client/src/templates/Challenges/components/prism-formatted.tsx

**Comment by moT01** [comment]
Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/52954
