### ISSUE TITLE
Create a "Sign up for a GitHub account" waypoint

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#542]
This issue references #541.

**Comment by denmch** [comment]
I think my idea for a Waypoint to help reduce duplicate bug reports could fit into or follow this one.

Here's how I described it on Slack:

> Another possibility to reduce the number of duplicate bug reports: an early Waypoint
> on getting started with github by following projects you’re interested in and, more
> importantly, reporting bugs. The big takeaway would be a kind of workflow or best
> practices, i.e., confirm and isolate the bug if you can (cross-browser, etc.), check
> to see if it’s a known issue, file an issue with an appropriate level of detail.

**Comment by BerkeleyTrue** [comment]
Anyone want to help out here?

**Comment by denmch** [comment]
If there's no objection, I wouldn't mind tackling this one.

**Comment by BerkeleyTrue** [comment]
Go for it!

**Comment by QuincyLarson** [comment]
Hey all, this is now implemented as part of Gitter. I will re-record this video and give a quick tour of GitHub while I'm at it.
