### ISSUE TITLE
loopProtect.protect problem

### ISSUE THREAD

**Issue by aaronclong** [FreeCodeCamp/FreeCodeCamp#5420]
loopProtect.protect causes problems for every for loop!!!!
```javascript
           var conquer=function(divide){
                var m=divide.length, biggest=0;
                for(var i=0; i<m; i++){
                    if(biggest<divide[i]) biggest=divide;
                 }
                 return biggest;
           };
```

**Comment by ltegman** [comment]
Please provide more details, like what challenge you are working on and exact steps to reproduce.

**Comment by aaronclong** [comment]
It is in ***bonfire: Find the Longest Word in a String***. The last for loop of every program I write gets blocked even if they identical to the one prior. I think it is the website's js interfering. It is not a natural javascript feature.

**Comment by ltegman** [comment]
Please provide the entirety of the code that is getting incorrectly blocked so that we can attempt to reproduce, not just part of it.

**Comment by aaronclong** [comment]
```javascript
function findLongestWord(str) {
  var divide=function(str)
  {
    var m=str.length, word, amount=[];
    for(var i=0; i<m; i++){
         if(str[i]===" ")
          {
             var size=word.length;
             amount.push(size);
          }
          else word+=str[i];
    }
    return amount;
  };
  
  var conquer=function(){
    var m=divide.length, biggest=0;
    for(var i=0; i<m; i++){
      if(biggest<divide[i]) biggest=divide;
    }
    return biggest;
  };
  return conquer ;
}

findLongestWord("The quick brown fox jumped over the lazy dog");

```

**Comment by ltegman** [comment]
Loop protect is not the problem. Your code is returning a function and the contents of that function are being output to the console. Please in the future use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to ensure that what you're seeing is a bug with the site and not with your code.

Thanks and happy coding!
