### ISSUE TITLE
Step 61: Given instructions differs from expected results (typo or misleading instructions).

### ISSUE THREAD

**Issue by AquaRush** [freeCodeCamp/freeCodeCamp#54219]
### Which curriculum?

JavaScript Algorithms and Data Structures (Beta) > Learn Basic JavaScript by Building a Role Playing Game > Step 61

### Description of instructions:

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25262287/1d35700c-35d3-42d1-90a5-a75f21bfe6e1)

### Expected user input:

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25262287/157f3bb0-777c-47fa-bc04-e96164d38d59)

### Results as per user input:

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25262287/5d69f7d8-8525-4550-96f4-30725c213e94)

### The issue:

**Step 61** states that you need to pass `location` as an argument to the `update()` function but the unit tests watchес for **locations** which is a constant variable that contains an object of items, instead of `location`, the user should use `locations` instead, which could confuse some people as there is an object called `locations` and also a function called `update()` that has an argument `location`.

### Possible solutions:

While we had a small discussion regarding that tiny issue, my personal opinion is that the first `location` should be renamed to `locations` which is expected from users to enter in first place.
The other solution would be to rephrase the instructions by removing the backticks of the first `location` so it's not marked down and people only see the final given instructions of 
> Pass your `locations` array into the `update` call.

leading to a successful submission of the problem.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-61

### Your code

```JS
function goTown() {
  update(location);
}
```

### Expected behavior

```JS
function goTown() {
  update(locations);
}
```

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/25262287/86907a05-a5d7-43c4-bfb1-c4a157bc5d9b)

### System

- Device: Desktop
- OS: Windows 11 Pro
- Browser: Brave
- Version: 1.64.109 Chromium: 123.0.6312.58 (Official Build) (64-bit)

**Comment by angad-singhh** [comment]
I am new to open source and would love to make a contribution  | The issue you have provided is only a typing error in the front-end as the the code passes when we pass update(locations)-{locations as a argument}, so we only need to change the typing error in the STEP-61 instruction.

| I am working on it, will be making a PR |

**Comment by jdwilkin4** [comment]
Let's go with this rewording.

````md
Now it is time to use your `update` function. Pass in your `locations` array into the `update` function call.

You pass arguments by including them within the parentheses of the function call. For example, calling `myFunction` with an `arg` argument would look like:

```js
myFunction(arg)
```
````

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8b3cc436db8139cc5fc09.md

Happy coding
