### ISSUE TITLE
[The Odin Project] Typo in Links and Images lessons

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#54214]
## Description

The word "finally" should be capitalized.

<img width="585" alt="Screenshot 2024-03-26 at 13 15 32" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/95251017-f0f0-489a-b595-88865af56ea8">

## Affected pages

- https://www.freecodecamp.org/learn/the-odin-project/top-links-and-images/links-and-images-question-b
- https://www.freecodecamp.org/learn/the-odin-project/top-links-and-images/links-and-images-question-c

## Changes needed

Capitalize the word "finally" in the following files:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/16-the-odin-project/top-links-and-images/links-and-images-question-b.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/16-the-odin-project/top-links-and-images/links-and-images-question-c.md

**Comment by omair-muhammad** [comment]
@huyenltnguyen, Can you please assign this to me, I want to work on it.
