### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by yashdeeph709** [FreeCodeCamp/FreeCodeCamp#5422]
There should be a way to run specific test cases in free code camp so that we can focus on a particular testcase at a time otherwise it just blows our console with lots of output which is quiet tough to filter.

**Comment by AkiraLaine** [comment]
@yashdeeph709 I believe FCC will eventually have a feature for users to make their own test cases.

**Comment by yashdeeph709** [comment]
no i am not talking about my test cases but i am saying that we can choose which one to run with in those provided otherwise default is to run all

**Comment by ltegman** [comment]
If you want to see only a specific test case you can copy and paste it into the bottom of your editor. Only running a subset of tests is not something that seems worth the coding time and UI clutter to implement.

Thanks and happy coding!
