### ISSUE TITLE
Incorrect font listed in style guide

### ISSUE THREAD

**Issue by jenna5376** [freeCodeCamp/freeCodeCamp#54224]
### Describe the Issue

The typography section of the [design style guide](https://design-style-guide.freecodecamp.org/#typography) states that Roboto Mono is the primary monospace font. However, when I checked font-family using developer tools, the monospace fonts used were Hack and Hack-ZeroSlash.

### Affected Page

https://design-style-guide.freecodecamp.org/#typography

### Steps to Reproduce

Update the design style guide page to include correct font family names 

### Recommended fix or suggestions

Roboto Mono should be replaced with Hack and/or Hack-ZeroSlash.

### Screenshots

<img width="594" alt="Screen Shot 2024-03-26 at 12 57 59 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/62906996/a759115c-bb40-4c8e-b67c-c1fd4e37fd80">

**Comment by mohmmadAyesh** [comment]
it also contain Lato font in other pages so whats your suggested changes removing roboto mono and use hack Lato instead?
also provide a link to download the Lato font or hack font?

**Comment by jenna5376** [comment]
@mohmmadAyesh Not sure if Roboto Mono is still being used but yes, I think it should be replaced with Hack. They already have documentation and download link for Lato

**Comment by naomi-lgbt** [comment]
Correct - Roboto was replaced with Hack-ZeroSlash in #47767.

I would want to confirm with @ahmaxed that we are not actively using Roboto on other platforms before removing it, but I think we should be fine to add Hack-ZeroSlash at the very least.

**Comment by jenna5376** [comment]
@naomi-lgbt 
I see. Once that is confirmed I would be happy to work on this!

**Comment by ahmaxed** [comment]
Yes,  Hack-ZeroSlash is our monospace font which we will be using for code in our platform.
Menlo has also been replaced by Hack-ZeroSlash.

**Comment by naomi-lgbt** [comment]
Awesome, I'll open this up for contribution.

In our https://github.com/freeCodeCamp/design-style-guide repo, a PR should be made to remove both Roboto and Menlo from our fonts, and add Hack-ZeroSlash.

**Comment by jenna5376** [comment]
@naomi-lgbt Opened a PR!
