### ISSUE TITLE
Improve instruction Step-12 of the Python case converter project.

### ISSUE THREAD

**Issue by zairahira** [freeCodeCamp/freeCodeCamp#54232]
### Describe the Issue

Some campers are confused whether the solution is a single line print statement or two separate statements.
Some forum queries can be viewed [here](https://forum.freecodecamp.org/search?q=Learn%20Python%20List%20Comprehension%20By%20Building%20a%20Case%20Converter%20Program%20-%20Step%2012)

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter-program/step-12

### Your code

Some campers found the solution to be:

```py
def main():
    convert_to_snake_case('aLongAndComplexString')
    print(convert_to_snake_case)
```

instead of:

```py
def main():
    print(convert_to_snake_case('aLongAndComplexString'))
```

### Expected behavior

The updated instruction can be something like this:

```
Within the `main()` function, remove the `pass` statement and substitute it with a `print()` call. Pass `convert_to_snake_case(`'aLongAndComplexString'`)` as an argument to the `print` call in order to display the function's return value.
```

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by zairahira** [comment]
Team, need your suggestions if the description can be further improved. 
We can then open the issue to `first timers only`.

**Comment by lasjorg** [comment]
The instruction says to call the function, give it an input, and print the function output.

I'm fine with clarifying instructions if needed, but we should be mindful about not feeding them the answer. That diminishes the learning experience.

To me, the incorrect answer example points to a camper not understanding what a function return is more than unclear instructions.

We can be more explicit about wrapping the function call inside the print to avoid campers creating variables for the return.

```md
Inside the `main()` function, replace `pass` with a `convert_to_snake_case()` call. Pass the string `'aLongAndComplexString'` as input to the function. Put the function call inside a `print()` function to print its output.
```

---

I would prefer "argument" and "return value" but input and output are the same, so if that follows the style used throughout we should keep it.
