### ISSUE TITLE
Unclear instruction: Learn String Manipulation by Building a Cypher Step 3

### ISSUE THREAD

**Issue by samGreer** [freeCodeCamp/freeCodeCamp#54234]
### Describe the Issue

The second paragraph of the instructions (shown below) uses parentheses twice.
<img width="615" alt="Screenshot 2024-03-27 at 13 27 32" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/93655422/bf5cb23b-1011-4918-9282-c8723003bccb">
Given that this is a lesson about the syntax for how to call a function, I think the use of parentheses is confusing

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-3

### Your code

N/A (not a coding issue)

### Expected behavior

N/A (not a coding issue)

### System

- Device: [MacBook Air]
- OS: [macOS]
- Browser: [Firefox]
- Version: [123.0]

**Comment by larymak** [comment]
The issues have been addressed in the PR https://github.com/freeCodeCamp/freeCodeCamp/pull/54051

**Comment by zairahira** [comment]
Hi @samGreer I do not see the word "parentheses" used twice, I hope I understood the issue correctly.
Also, what would you suggest the updated instruction to be?

**Comment by Dario-DC** [comment]
If I understood correctly you mean the parentheses in `print()`, right? @samGreer

**Comment by Rabberpoli** [comment]
The only parentheses I can see on second paragraph are the following:

- **... call (run)**
- **... call (invoke)**

If I understood correctly, right? @samGreer

If so, these are just used syntactically, so they should be ignored

**Comment by samGreer** [comment]
Hi @zairahira, thanks for the questions. By "parentheses", I mean the symbols "(" and ")", not the word. Apologies for the confusion.

My proposed solution would be rewriting the second paragraph as follows:

Functions are reusable code blocks that you can call/run/invoke when you need them. To call a function, you just need to write a pair of parentheses next to its name. You will learn more about functions very soon.

My issue with the previous was that the use of parentheses in the paragraph previously indicated to me examples of syntax, while not actually being examples of syntax. I think this rewriting clears up that confusion, and means that parentheses are used in this step during examples of function calls, which I think reads clearer

**Comment by Dario-DC** [comment]
Okay, I had missed the first sentence of your post @samGreer . 

I would go with:
```
Functions are reusable code blocks that you can call, or invoke, to run their code when you need them. To call a function, you just need to write a pair of parentheses next to its name. You will learn more about functions very soon.
```

**Comment by zairahira** [comment]
> Okay, I had missed the first sentence of your post @samGreer .
> 
> I would go with:
> 
> ```
> Functions are reusable code blocks that you can call, or invoke, to run their code when you need them. To call a function, you just need to write a pair of parentheses next to its name. You will learn more about functions very soon.
> ```
Thanks for the clearification @samGreer 👍️
I'd suggest we go with this modified instruction.
