### ISSUE TITLE
Google Pay displays wrong amount

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#54245]
### Describe the Issue

If any amount other than the default amount is selected,  Google Pay still shows the default amount.

### Affected Page

freeCodeCamp.org/donate

### Your code

```



```

### Expected behavior

The amount displayed in Google Pay should be the same as the amount selected.

### Screenshots

<img width="1331" alt="Screenshot 2024-03-29 at 5 24 54 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/21ebdb3d-b5e2-4f82-b9d1-730e204d9b2d">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context for testing

Stripe and paypal keys are needed for the button to show up.
If only Stripe keys are used,  remove ```&& loading.paypal``` from https://github.com/freeCodeCamp/freeCodeCamp/blob/3c0e1e57f340465b9d9c897d67c1b88c075e7e10/client/src/components/Donation/donate-form.tsx#L254

Apple pay only shows up in https, so a tunnel such as ngrok is need. 
if ngrok is used, running ```ngrok http 8000``` in the console while the app is running locally should give you a https url.

**Comment by Rabberpoli** [comment]
Yep, just tried with another import (40$) and still shows 20$ on google pay.
That's definitely a bug; I could try to look for a fix after it has been triaged

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/31985931/be24f56f-6b86-433a-bd57-0ced38a7293e)

**Comment by Raghul-V** [comment]
@ahmaxed , @Rabberpoli I tried opening the webpage in my laptop (Windows)... I was not able to see the Google Pay option but when opened in my mobile (android) google pay appeared. I cannot figure out where in the codebase does it actually renders different pages for different OS devices in which the page is opened. Can you help with that???

**Comment by Rabberpoli** [comment]
@Raghul-V I think GPay or ApplePay button showing mechanism depends on Stripe's logic.

If you look at `donate-form.tsx`, you can see this element: `<WalletsWrapper ... />` which has, inside, `<PaymentRequestButtonElement` that directly comes from Stripe. So the reason you can't see anything on your laptop could be that you have not configured any payment type for that browser. For example I can see GPay option both on my laptop and my mobile.

Just one question for @ahmaxed: how can you test payment options on local environment (gitpod)? Because every time I try to donate I get stuck on loading icon.

**Comment by ahmaxed** [comment]
@Raghul-V, google pay shows up only if you have a configured google pay on your browser.
@Rabberpoli, if you have the stripe keys, remove ```&& loading.paypal``` from https://github.com/freeCodeCamp/freeCodeCamp/blob/3c0e1e57f340465b9d9c897d67c1b88c075e7e10/client/src/components/Donation/donate-form.tsx#L254

**Comment by ahmaxed** [comment]
Adding a prop key={amount} to  <PaymentRequestButtonElement does help, helps mounting a new instance with the amount change. However, it will display the previously selected amount. For instance, if a user first selects 20, then 10, then 5, 10 will be displayed as the amount in the google pay pop up.
