### ISSUE TITLE
<i> used instead of <em> in Waypoint: Change Text Inside an Element Using jQuery

### ISSUE THREAD

**Issue by lyonsinbeta** [FreeCodeCamp/FreeCodeCamp#5425]
Challenge [Waypoint: Change Text Inside an Element Using jQuery](http://www.freecodecamp.com/challenges/waypoint-change-text-inside-an-element-using-jquery#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target4%22).html(%22%3Cem%3E%23target4%3C%2Fem%3E%22)%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Instructions and automated tests require `<i></i>` to be used when this case should call for `<em></em>`. The code below works, but isn't marked as passing by the automated test.

My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>#target4</em>")
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by SaintPeter** [comment]
That is because you were instructed to add the `<i>` tag, not the `<em>` tag.  The two are not equivalent.  `i` means to italicize the text, as in the case of highlighting latin words, or otherwise displaying text as italic.  `em` means to add emphasis to the text.  While in English it is common to add emphasis with italics, it has a secondary, semantic meaning for screen readers that the word should be emphasized.  

In this case we are applying a stylistic, not semantic change.

Closing as this is not an issue with the site.  Thanks and happy coding!

**Comment by andreykaipov** [comment]
@SaintPeter While this is not an issue with the site, I think this lesson may be rather confusing for an attentive student.

In the Bootstrap lesson [Add Font Awesome icons to our buttons](http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons`<i>`) that occurs before this lesson, we are told the following

> The `i` element was originally used to make other elements italic, but is now commonly used for icons.

I recommend adding a note into this lesson about how the `<i>` tag was used creatively in that aforementioned Bootstrap lesson. Alternatively, we could just switch this lesson to use the `<em>` tag.

**Comment by sloyless** [comment]
@SaintPeter I understand what you said about screenreaders, but the `<i>` tag just isn't used for italics anymore, and as @andreykaipov said in the previous course (not but ~10 lessons earlier) it is implicitly stated that the `<i>` tag is more commonly used for the FontAwesome icons and has been replaced with `<em>` for general italics.

I think it should be changed in this lesson to `<em>` to prevent confusion.

**Comment by ltegman** [comment]
That doesn't change the fact that `<i>` is semantically correct. There shouldn't be any confusion since the lesson explicitly asks you to use `<i>`.

**Comment by rrenwick** [comment]
Sorry @SaintPeter, I have to agree with @andreykaipov & @sloyless - `<i>` by itself is not even recommended by the W3C anymore - according to this link they don't consider it semantic either: [https://www.w3.org/International/questions/qa-b-and-i-tags](https://www.w3.org/International/questions/qa-b-and-i-tags)
While this is not a problem with the site, I believe it would be beneficial for new learners to understand that `<em>` is more often a better choice and not just copy the outdated `<i>` suggestion for italics, at least without a semantic class name.

**Comment by ltegman** [comment]
@rrenwick. That article simply suggests that authors carefully consider if there is a more semantically appropriate tag when using an `<i>`. I think this thread and a couple others like it are proof that we have carefully considered if another tag would be more semantically appropriate and the fact is, it wouldn't.

**Comment by sludge256** [comment]
For further consideration:
>Font Awesome is designed to be used with inline elements (we like the <i> tag for brevity, but using a <span> is more semantically correct).
[Source](https://fortawesome.github.io/Font-Awesome/examples/)

**Comment by rrenwick** [comment]
Fair enough @ltegman, you guys obviously have a better insight to the issues and learning problems encountered - I was just surprised to encounter this tag still being recommended.

**Comment by sludge256** [comment]
PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7823 resolves this issue.
