### ISSUE TITLE
Ability to reset the courses

### ISSUE THREAD

**Issue by SoraTheWeirdo** [freeCodeCamp/freeCodeCamp#54255]
### Is your feature request related to a problem? Please describe.

So I've tried out freeCodeCamp a few years ago, and I then had a burnt out. I stop using fCC and now started to get back into it. Since I remember little to none of the things I've learn, I decided to start over from the very beginning. The issue is that all the courses I've done the first time has changed color (to indicate I've complete it), so when I get off for the night and resume the next day (sometimes days or week later), I've forgotten where I left off at.

### Describe the solution you'd like

Some sort of button that you can click (or if you start back on #1 of any courses, it will say "Would you like to reset your progress for this course" or something) to turn this
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/112508103/b2791222-9b0a-4f2d-8528-8717d0a1cd40) into this 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/112508103/f5cb82c1-0d86-4aff-85de-15d87c04e1c9)

### Describe alternatives you've considered

None

### Additional context

While I understand that you could simply press on your profile to resume, I still think it'd be a nice feature to just have a reset button to visually indicate it

I also understand once you've completed something, if you go back to it, it go back to Ground 0, so none of your work are saved

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #47464, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
