### ISSUE TITLE
[JS Curriculum] Spreadsheet Step 34 missing implicit return test

### ISSUE THREAD

**Issue by juancaorg** [freeCodeCamp/freeCodeCamp#54259]
### Describe the Issue

When working with the [JS Spreadsheet at step 34](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-34), it mentions the following instructions to complete the challenge:

> In your evalFormula, declare an idToText arrow function which takes an id parameter.

> Your idToText function should return the result of calling .find() on the cells array with a callback function that takes an cell parameter and returns cell.id === id.

And that's alright, but when running the following correct solution, it doesn't pass and throws the following error:

```js
const evalFormula = (x, cells) => {
  const idToText = (id) => { return cells.find(cell => cell.id === id) };
}
```

> You should assign idToText the result of calling the .find() method on your cells array.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-34

### Your code

```js
const evalFormula = (x, cells) => {
  const idToText = (id) => { return cells.find(cell => cell.id === id) };
}
```

### Expected behavior

The current test error that it throws is misleading and it's happening because there's a missing test for the above code, which is expecting an implicit return.

A test should be added to let the user know that an implicit return is expected and can reach to the expected solution:

```js
const evalFormula = (x, cells) => {
  const idToText = (id) => cells.find(cell => cell.id === id);
}
```

Updating the challenge instruction would be appreciated too.

On the other hand, there's a similar case where a correct test is running. When executing the following solution, this happens:

```js
const evalFormula = (x, cells) => {
  const idToText = (id) => cells.find(cell => {return cell.id === id});
}
```

> Your callback function should use an implicit return.

This is tested using the following test:

```js
assert.notMatch(code, /const\s+evalFormula\s*=\s*\(\s*x\s*,\s*cells\s*\)\s*=>\s*{\s*const\s+idToText\s*=\s*(\(\s*id\s*\)|id)\s*=>\s*cells\.find\(\s*(\(\s*cell\s*\)|cell)\s*=>\s*\{/);
```

### Screenshots

![CleanShot 2024-03-31 at 15 02 53](https://github.com/freeCodeCamp/freeCodeCamp/assets/47751447/c930c0d4-cc7a-4a7f-aed9-93f56fe59f39)

### System

- Device: Laptop
- OS: macOS 13.6.6
- Browser: Chrome
- Version: 123

**Comment by juancaorg** [comment]
Hey @Rabberpoli, how about being more specific like other the other challenges? Something like the following:

> In your `evalFormula`, declare an `idToText` arrow function which takes an id parameter.
>
> Your `idToText` function should return the result of calling .find() on the cells array with a callback function that takes an cell parameter and returns cell.id === id.
>
> Note: your `idToText` function should use an implicit return.

And the test error text should be the same when the condition is not met:

> Your `idToText` function should use an implicit return.

That's my opinion, ofc. Appreciate that you ask.

When able, please submit the PR and let's see what the maintainers think 🤝

**Comment by Rabberpoli** [comment]
Hi @juancaorg and @Supravisor,
I've submitted a PR using juan suggestion about instructions; then I added a test assertion just to give explicit error on implicit return.

Supravisor PR just fixed text instructions but not added a test, so I did it.

Moreover I updated both English page and Italian one, not sure about other languages grammar so I didn't touch them but can be reproduced once merged this PR
