### ISSUE TITLE
JS (beta) certification - Not response/suggestion whe  you try checking code

### ISSUE THREAD

**Issue by JuanSposada** [freeCodeCamp/freeCodeCamp#54263]
### Describe the Issue

There is not response or suggestion when you try to check your code (ctrl + Enter) with a wrong response.
Also the preview screen crashes

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-81

### Your code

```

function buyWeapon() {
  if(gold >= 3)
}

```

### Expected behavior

We expected a suggestion or at least an announcement like keep trying.

### Screenshots

![Captura desde 2024-03-31 22-44-40](https://github.com/freeCodeCamp/freeCodeCamp/assets/106193987/b6bd5231-a644-41f0-a831-33f261f0cc61)

### System

- Device: [Laptop]
- OS: [Ubuntu 22.04]
- Browser: [Mozilla Firefox]
- Version: [123]

**Comment by jdwilkin4** [comment]
Hi @JuanSposada ! 

There is already an open issue about this here

https://github.com/freeCodeCamp/freeCodeCamp/issues/52749

If you wish to comment, you can do so there 👍
