### ISSUE TITLE
Infinilte Loop Preview window bug in JS (beta) certification

### ISSUE THREAD

**Issue by JuanSposada** [freeCodeCamp/freeCodeCamp#54260]
### Describe the Issue

The preview windows in JS certification, first project 'Building a Role playing Game' , step 51, goes in infinite loop if you put write :

const location = [ ]

instead of: 
const locations = [ ]

here is a scrreenshot of the issue. 

![Captura desde 2024-03-31 16-24-33](https://github.com/freeCodeCamp/freeCodeCamp/assets/106193987/addb47a8-a502-4dbd-9fb1-d0bd059dc551)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-51

### Your code

```

`const location= []`

```

### Expected behavior

Just keep the normal preview window

### Screenshots

![Captura desde 2024-03-31 16-24-33](https://github.com/freeCodeCamp/freeCodeCamp/assets/106193987/0744d90f-159f-43c3-a7a7-5d6f91167c79)

### System

- Device: [Laptop]
- OS: [Ubuntu 22.04]
- Browser: [mozilla firefox]
- Version: [123]

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #52733, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
