### ISSUE TITLE
Enhancement Request: For MacOS, add text that says “⌘+ Enter to submit lesson"

### ISSUE THREAD

**Issue by CoolHandLouis** [freeCodeCamp/freeCodeCamp#54270]
### Is your feature request related to a problem? Please describe.

SUMMARY: On MacOS platform, it’s not made clear that Command+Enter can be used to submit lessons, despite the fact that this keyboard shortcut does work and is preferable. I suggest making this clear to Macbook users.

DISCUSSION:
Currently, the lessons say: Check Your Code (Ctrl + Enter). On Mac, the Ctrl key is in a slightly awkward position compared to the Command Key. The Command key is very easy and quick to hit.

This might seem like a small request, but I think that the change would be greatly appreciated and helpful to those who are (a) on Macs and (b) appreciate keyboard shortcuts.  My personal story is I "suffered" through the lessons for awhile, trying to get accustomed to Ctrl + Enter, but it was always a little bother. Once I figured out the "trick" of getting to the next page via ⌘+ Enter, I thought, "I wish I had known about that earlier!"

(Staff requested I open this as an issue: https://forum.freecodecamp.org/t/enhancement-request-text-that-says-enter-to-submit-lesson-on-mac/683217.)

### Describe the solution you'd like

This could possibly be implemented in one of two ways:

* Change the text on MacOS to “Check Your Code (Command + Enter)”.  Or perhaps “Check Your Code (⌘+ Enter)"

* Pop up on MacOS that says “You can also use Command+Enter to check your code.” On the popup, also include a checkbox: “Don’t show this again.”

### Describe alternatives you've considered

None.

**Comment by bbsmooth** [comment]
I'll add my two cents here. I think we should remove the extra hint text completely and the button should just read "Check Your Code". This information can be made available in the keyboard shortcuts helper dialog that we already have available.

**Comment by Sembauke** [comment]
I disagree, Bruce. In order for people to find this modal they would need to enable it in the settings first. Then go through a couple of technical tricks to get it to show up. Which is hard for a casual user to comprehend.

This change would be for the better. I will put a Help wanted label on it!

**Comment by Rabberpoli** [comment]
Hi everyone! I've just submitted this PR: #54276 which should enhance labelling on "check-code" button.

My solution, at the moment, provides the following label: `Check Your Code (⌘+ Enter)` which was the fastest way to improve the current situation; I've also seen you talked about showing pop-up... we could think about it but I think that updating the label should be better in terms of maintaining and testing stuff

Let me know what you think about it
