### ISSUE TITLE
Waypoint: Iterate over Arrays with map accepts incorrect code after initial pass

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#5428]
Challenge [Waypoint: Iterate over Arrays with map](http://beta.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20garbage%3B%2F%2F%3D%20oldArray.map(Math.floor)%3B%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function()%20%7Breturn%20newArray%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**After** you pass the test once you can submit "incorrect" code and still pass.

Seems like a minor issue but it would affect people copying and pasting code from chat when assisting others if they have already finished this waypoint.
After some more testing though, hitting the reset button does seem to fix this but I personally usually just paste over all my old code instead of hitting reset.

My code:
First pass:
```javascript
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray.map(function(val) {
  return val + 3;
});

// Only change code above this line.

(function() {return newArray;})();
```
Second pass:
```javascript
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var garbage;//= oldArray.map(Math.floor);
// Only change code above this line.

(function() {return newArray;})();

```
On this user-agent I believe it checks for the existence and valid use of `.map()` while on,

`Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko`
it seems to also check for the correct array and values which can be hard-coded after initial pass.

**Comment by HoBi** [comment]
:+1:

**Comment by SaintPeter** [comment]
Confirmed.  I was able to do this on Chrome.  Maybe the tests are stateful in some way?

**Comment by easher** [comment]
This issue isn't unique to this way point. the next waypoint 
[waypoint-condense-arrays-with-reduce](http://beta.freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce) can reproduce the same issue. Tests pass as expected here:
```javascript
var array = [4,5,6,7,8];

// Only change code below this line.

var singleVal = array.reduce(function(a,b){
  return a + b;
});
// Only change code above this line.

(function() {return singleVal;})();
```

Then if you try this right after test passes,  the reported unexpected behavior of tests passing happens here:
```javascript
var array = [4,5,6,7,8];

// Only change code below this line.

//var singleVal = array.reduce(function(a,b){
 // return a + b;
//});
// Only change code above this line.

(function() {return singleVal;})()
```
But if you try this right after tests pass, tests still fail appropriately: 
```javascript
var array = [4,5,6,7,8];

// Only change code below this line.

var singleVal = array.reduce(function(a,b){
  return a - b;
});
// Only change code above this line.

(function() {return singleVal;})()
```
Tests also fail appropriately in the waypoint that this was reported when submitting invalid code. It appears only to be when there is no code or disabled code that produces this issue.

**Comment by natac13** [comment]
If we declare the newArray variable in the seed code then upon removal of the code to pass the test we will get a failing test once again. 


```
var oldArray = [1,2,3,4,5];
var newArray = [];

// Only change code below this line.

var garbage;//= oldArray.map(Math.floor);
// Only change code above this line.

(function() {return newArray;})();
```

The second test still passes since `.map()` is used in a comment. Perhaps the test for that should be changed to be a little more strict.... 
I would be happy to make these changes and PR them if everyone is happy with my thoughts.
Would even like to do the over twitch stream

**Comment by SaintPeter** [comment]
@natac13 Absolutely.  We're open to suggestions as to how to more effectively test.

While you're at it, you can move the display function to the tail.  You may need to add a "tail" to do so.

**Comment by natac13** [comment]
@SaintPeter not exactly sure what you mean by move the display function to the tail...

**Comment by SaintPeter** [comment]
@natac13 Like this:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/27780d3d5d49aad0d0caf11aa0d097b4eb9f99f0/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L44

**Comment by natac13** [comment]
Understand now Thanks!

**Comment by vipuldcoder** [comment]
what is the need of this >> "(function() {return newArray;})();" we also can do like this 
//var newArray = oldArray.map(function(val){
     val = val + 3;
    return val ; 
                });//

**Comment by alexlo0319** [comment]
Is in the exaple for this section but in the example it has a * sign and is + for your assignment. It says it in the requirement  "add three to each value" the key word is ADD.

**Comment by knezinho** [comment]
ADD is **+** so when you write:
var newArray = oldArray.map(function(val) {
return val + 3;
});
console.log(newArray);
console.log(oldArray);
Result is  [4,5,6,7,8] for newArray, because it ADDS  3 to each value of oldArray...
