### ISSUE TITLE
Update certification footer for exam-based certifications

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#54282]
On exam-based certifications, we should change the footer verbiage slightly to reflect the fact that it's an exam (and not submitted projects). See screenshot below.

<img width="1270" alt="freecodecamp_org_certification_harrykimpel_foundational-c-sharp-with-microsoft" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/985197/7089703b-25d0-4b14-a44d-bda2f4e1d192">

**Comment by a2937** [comment]
@moT01 Can I have this issue please?

**Comment by moT01** [comment]
Go for it @a2937, I would change the first line to `As part of this certification, (user) passed the following exam:` - and the line below it to `If you suspect that this exam violates the academic honesty policy, please report this to our team.`

**Comment by a2937** [comment]
Oh. Got it. My gut reaction was to add in a translation key specifically for exams and then make the footer conditionally visible. 

I'm still learning how to separate the requested requirements from the actual requirements.

**Comment by moT01** [comment]
Actually, lets just omit that line at the bottom @a2937. As requested in the image.
