### ISSUE TITLE
Help issue: searching for topic from coding pages

### ISSUE THREAD

**Issue by neshi47** [freeCodeCamp/freeCodeCamp#54291]
### Issue Summary:
When attempting to search for help from the code editing page on FreeCodeCamp, the information passed to the forum search contains hyphens in the exercise title. However, most forum posts are titled differently, without hyphens. This results in failed searches as the forum doesn't recognize the hyphenated title format.

### Additional Details:
This issue is not a critical bug but rather a quality-of-life improvement. It would enhance the user experience by aligning the search parameters between the code editing page and the forum search functionality.

Please let me know if further information is required. Thank you.

### Affected Page

https://forum.freecodecamp.org/search?q=

### Steps to Reproduce

1. Input incorrect code to solve a challenge multiple times until the Help button appears.
2. Click Help.
3. Click on the underlined link "check if your question has already been answered on the forum" when the "Ask for Help" prompt appears.
4. This leads to a forum.freecodecamp.org page automatically searching your issue as `learn-basic-javascript-by-building-a-role-playing-game - Step 127`.
5. The search doesn't bring up any instances of forum topics as they are titled differently, e.g., `learn basic javascript by building a role playing game - Step 127`.
6. Search for the topic manually after being prompted with "no previously asked similar questions" to trigger the link to "create a new topic."
7. Copy the previously searched, hyphenated string into the topic creation title form.
8. Now, forum topics appear, but only after attempting to create a new topic.

### Expected behavior

The link passed from the coding page to the help page should be formatted without hyphens in the exercise title to match the typical forum post title format. For example:

```
search?q=Learn%20Basic%20Javascript%20by%20Building%20a%20Role%20Playing%20Game%20-%20Step%20127
```

### System

- Device: Macbook Pro, Windows Desktop
- OS: Windows 10, macOS Monterey 12.7.4
- Browser: Chrome

**Comment by sushilpandeyy** [comment]
Apologies for the oversight, I didn't notice the recently raised PR addressing the same issue.
