### ISSUE TITLE
Clarifying instruction text

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#5429]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter)

>Use `filter` to remove all elements from `array` that are greater than 5.

Should be changed to:
>Use `filter` to remove all elements from `oldArray` that are greater than 5.

This would make the directions a bit more clear and reflects what is presented in the code editor.
It may also prevent users from using the `array` part from the example.
```javascript
array = array.filter(function(val) {

  return val !== 5;

});
```
It's also worth considering editing the test descriptions to be more specific, but I think they're descriptive enough as is.

**Comment by PatriquePorto** [comment]
Do you have any problema to resolve this challenge?

**Comment by SaintPeter** [comment]
Confirmed.
