### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue 

### ISSUE THREAD

**Issue by appijumbo** [FreeCodeCamp/freecodecamp#543]
Just put this in  
**********
etc.....

.thick-green-border {
    width: 100px;
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<img class='thick-green-border smaller-image' src='https://bit.ly/fcc-kittens'/> 

........etc
**********
and it says its ok, but it isn't as although it fulfils the criteria, the 'smaller-image' class has been deleted and incorporated into the thick-green-border' class.  

I think it's supposed to be

******
etc.....
  
  .smaller-image {
   width: 100px;
  }
  
  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<img class='thick-green-border smaller-image' src='https://bit.ly/fcc-kittens'/>

....etc
******

**Comment by QuincyLarson** [comment]
I'm not sure I follow you. Is there any way you could send me a screen shot?

**Comment by appijumbo** [comment]
Hi Quincy, here is the code

```
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

/* **** Note that the smaller-image class definition is missing ****/

  .thick-green-border {
 width: 100px;    /*** width contained inside the border class ****/
 border-color: green;
 border-width: 10px;
 border-style: solid;
 }
  
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
and a screen shot
![waypoint add borders around your elements v1](https://cloud.githubusercontent.com/assets/10559688/7831882/abed2d6a-0452-11e5-91a6-f4602f357ac2.jpg)

Both "smaller-image" and "thick-green-border" classes are in the class attribute, but the "smaller-image" isn't actually defined in the <style> content. The code works fine as all the definitions of the class have been put under the "thick-green-border" class, but I don't believe this is what your trying to get the FCC user to achieve.

So I think what we're supposed to be coding is this 

```
 <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
 
  .smaller-image{
   width: 100px;
 } 
  
  .thick-green-border {
 border-color: green;
 border-width: 10px;
 border-style: solid;
 }
  
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

(Many apologies if Im barking up the wrong tree here!)

Regards, T

**Comment by terakilobyte** [comment]
I've greatly increased the thoroughness of the tests for this challenge. Thanks for the report.
