### ISSUE TITLE
Hindi Language Support

### ISSUE THREAD

**Issue by sudhanshuku01** [freeCodeCamp/freeCodeCamp#54302]
### Is your feature request related to a problem? Please describe.

I would like to propose the addition of **Hindi** language support to FreeCodeCamp.

### Describe the solution you'd like

 With a large population of Hindi speakers worldwide, including India, Nepal, and other regions, providing content in Hindi would greatly enhance accessibility and inclusivity for learners who prefer or are more comfortable with the Hindi language.

### Describe alternatives you've considered

**Impact:**
Reach a wider audience.
Empower Hindi-speaking learners.

### Additional context

![Screenshot 2024-04-04 221026](https://github.com/freeCodeCamp/freeCodeCamp/assets/106875588/d2cda544-8d40-4662-a99e-ab5bdf91b6b3)

**Comment by ilenia-magoni** [comment]
You are welcome to joining the translation efforts, article: https://www.freecodecamp.org/news/help-translate-freecodecamp-language/
