### ISSUE TITLE
Flyout Chat not connecting in Google Chrome Browser

### ISSUE THREAD

**Issue by ChrisRanieri** [FreeCodeCamp/FreeCodeCamp#5431]
Challenge [Waypoint: Construct JavaScript Objects with Functions](http://www.freecodecamp.com/challenges/waypoint-construct-javascript-objects-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Im having an issue here where the flyout chat is not letting my type in Google Chrome, I have to open the chat in a new window. i attached a picture, when I click the chat button it just loads

<img src='http://i64.tinypic.com/1z19oue.png'>

**Comment by ltegman** [comment]
I can't repro this in the same version of google Chrome as you. Do you have an extensions like popup blockers or are you using a proxy or VPN? Do you see any errors in the console?

**Comment by ChrisRanieri** [comment]
No VPN, I disabled my pop up blocker and under inspect element I am getting this.

**Comment by ltegman** [comment]
I'll leave this open for a while just to see if anyone else is able to reproduce this, but it's looking to me like a connection or system issue on your end.

**Comment by ChrisRanieri** [comment]
Sounds good. Thank you, I will keep you updated on what I find when I debug. Happy holidays man 

Chris

**Comment by BerkeleyTrue** [comment]
@ChrisRanieri Are you able to log into Gitter normally?

**Comment by ChrisRanieri** [comment]
Yup I can log in normally when I open the chat in a new window
