### ISSUE TITLE
update wording for step 24 of football team cards project

### ISSUE THREAD

**Issue by JoyShaheb** [freeCodeCamp/freeCodeCamp#54320]
### Describe the Issue

it is confusing whether campers will pass string of 'Players' or variable named `players`. i think the wording should be cleared on the hint.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/5549a05f-9f7a-4375-96f2-a2fb630bbc82)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-24

### Your code

```
const setPlayerCards = (arr = 'players') => { };
```

### Expected behavior

Your `arr` parameter should have a default value pointing towards the variable named `players`.

something like this should be on the hint @jdwilkin4 ? 

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/aa717611-73ab-4002-854f-9d6d2c4f406f)

### System

- OS: [Windows 11]
- Browser: [Chrome]

**Comment by fuelmessenger** [comment]
:sparkles: Thanks to the community, there's an estimated bounty value of **$76.30 USD** for a successful merge request of this issue via contributions such as **6.825 UNI** tokens. Happy coding :grinning:
Details and T&Cs at [joinfuel.io](https://joinfuel.io)

**Comment by jdwilkin4** [comment]
I think ti would be best to update the description to reminder them where players came from

some thing like 

```md
Remember that you destructured the `players` variable from the `myFavoriteFootballTeam` object on line 175.
```
