### ISSUE TITLE
Missing test: Learn String Manipulation by Building a Cipher

### ISSUE THREAD

**Issue by samGreer** [freeCodeCamp/freeCodeCamp#54328]
### Describe the Issue

Step 16 (and presumably most steps) have no check that the line "shift = 3" stays in the code. 

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-16

### Your code

```
text = 'Hello World'
alphabet = 'abcdefghijklmnopqrstuvwxyz'
index = alphabet.find(text[0])
print(index)
print(text.lower())

```

### Expected behavior

The above code clears the challenge, but (to my understanding) it should not because code that will be used later has been deleted

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

I'm not sure what the feeling around fixing this issue is, given that it's low stakes (the code will return in the next step) and multiple steps are affected. If people think action should be taken on this, I can go through the code for each challenge and see which steps are missing this check.

**Comment by zairahira** [comment]
The line of code `shift = 3` is not part of the solution for that step, it wont be tested. I hope I understood the issue correctly.

**Comment by Dario-DC** [comment]
In each step, only the relevant part of code for that step is tested (what you need to change).

This does not mean that the code will work if something outside the tested portion is changed, but we are not going to write specific tests to check that.
