### ISSUE TITLE
Learn Advanced Array Methods by Building a Statistics Calculator - Step 27 -- Not _really_ a duplicate

### ISSUE THREAD

**Issue by fera3024** [freeCodeCamp/freeCodeCamp#54333]
### Describe the Issue

In my personal opinion, and with the number of issues/forum questions on this topic since the original issue was opened [#52753].

The wording on Step 27 is so confusing that even once I found the solution here on github and on fCC forum, I still dont exactly understand how or why we were doing what we are asked to do. I have the window open with the little green "congratulations bar" and I'm still looking for a clear explanation as to why.

Step 27 is written as:

"Remember that the .forEach() method allows you to run a callback function for each element in the array.

Use the .forEach() method to loop through the array. In the callback, use the el parameter to access the counts object and increment the count for each number."

as a _camper_ my initial thought is something along the lines of ...

```const getMode = (array) => {
const counts = {};
array.forEach((el) => counts[el]++);
}
```

now that was my gut thought, even a variation with curly brackets. 
I know I am still trying to grasp how forEach works and how manipulating an array is supposed to be done. 
But, the step is so vague that even now it isn't obvious why i need to check-for/define a 0 value.
I'm assuming its because forEach is undefined. Again, thats after a really long time searching and reading solved forums. I just refused to copy the answer. I really wanted to.

I saw in a previous issue a discussion about spreading the steps out, but then saw it was marked as closed, as if the issue was solved. The previous step description had the missing hints, without the callback hints included now. I'm just, confused as to what was actually updated because the solution is still, complicated for an introductory course.

Otherwise, loving the whole curriculum and i am aware this is a Beta. 11/10 highly recommend 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-27

### Your code

```
const getMode = (array) => {
  const counts = {};
  array.forEach((el) => counts[el] = (counts[el] || 0) + 1)
  
}


```

### Expected behavior

The above is the working code, below is whats implied, as a student, from the description.

```const getMode = (array) => {
const counts = {};
array.forEach((el) => counts[el]++);
}
```

The link below is to one of the forum questions i found that had some advice that I attempted to follow : 

https://forum.freecodecamp.org/t/learn-advanced-array-methods-by-building-a-statistics-calculator-step-27/666678/3
link included in help : 

```array.forEach((el) => {
  if (counts[el]) {
    counts[el]++;
  } else {
  counts[el] + 1;
});
```

when this didnt work, or any variations, i kept looking and found github issues

### System

- Device: MacMini
- OS: Sonoma 14.4
- Browser: Chrome
- Version: 123.0.6312.107 (Official Build) (arm64)

### Additional context

#53938 #52753 issues reported on the same step.

Otherwise, loving the whole curriculum and i am aware this is a Beta. 11/10 highly recommend 
in fact, i've told everyone i know, in casual conversation, super way to invest in yourself is to do this coursework

**Comment by fera3024** [comment]
To reiterate, I am a student/camper. 
If I am missing something that others are not, fair, but i feel like, because the answer is accessible/can-be-copied online, that feedback likely isnt coming in regarding the phrasing except through late forum comments saying something along the lines of "i was struggling too, thanks for posting the answer/solution"

**Comment by gikf** [comment]
Thank you for reporting this issue.

The relevant steps were just updated, changes are already present in the codebase, but they still might not appear in the production. After the next deployment they should reach production as well.

I believe the most of the previous step 27 will be now in the step 30 - https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-advanced-array-methods-by-building-a-statistics-calculator/65ca2d0625aa3a3201067f70.md. Please take a look at the wording and whether that addresses your concerns.

**Comment by fera3024** [comment]
that it far easier to understand. Thank you for the resource. It gives just enough to know what pieces we are working with but does require us to think about how to use them properly. 
Definitely addresses the concern. 
I have found this lesson to be one of the more confusing but it does introduce a lot of new aspects, as it should. Thanks again

**Comment by jdwilkin4** [comment]
Hi @fera3024 ! 

Thanks for opening up this issue.

As mentioned, the new updates were merged in a couple of days but they aren't live yet on the site.

I am going to close this issue.

But if you have an comments about the new changes, then please feel free to open up a new issue.
Thanks!
