### ISSUE TITLE
Waypoint: Size your Images - "Run Tests" keeps failing - Please help

### ISSUE THREAD

**Issue by sethusrinivasan** [FreeCodeCamp/FreeCodeCamp#5434]
My code:
-------------
I am not sure what i was missing, can you please help?

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>

  .smaller-image {
    width: 100 px;
  }
  
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2>CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to seek help.

Thanks and happy coding!
