### ISSUE TITLE
Forum Theme issues

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#54356]
There are various things that are not colored as they should in the forum theme:

Bookmark button, inactive:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/70aa206c-5b9b-4734-9108-e01d468cbdc6)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/3edc2f6b-fbde-4c24-bc13-4adf387c4036)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/48afed95-358a-4a25-a69e-0cb00c43e984)

Bookmark button, hover: (hovered edit button provided for confront)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/c4008dfe-ec40-4406-9160-d5130f70b495)![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/35bd7a58-f3cb-440b-8c36-48d459991f8b)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/240f0148-c2fb-406d-9742-fc8af8e00e72)![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/40e2e101-1053-4348-8bbd-23e1647a9132)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/fbe02a32-f60b-48f9-b50d-6761eddca4ff)![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/a319fa00-7f86-489e-92bd-943f7b1def0c)

nav-bar buttons not visible in day theme:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/b671d7fe-1acd-495f-9b19-576db3698621)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/2d464e40-d759-48b1-a9ec-3d4dc26d82a2)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/b1e9a0f4-e7d8-43a5-8c91-0aa86b953d92)

**Comment by ShaunSHamilton** [comment]
Could be related to: https://github.com/freeCodeCamp/forum-theme/pull/120

**Comment by raisedadead** [comment]
I have landed the linked PR, and updated the forum themes but it doesn't seem to have any effect. In retrospect, I have always hated the idea of having to maintain a theme for the forum. We should have changed the color schemes and called it a day!

**Comment by raisedadead** [comment]
Hey @ahmaxed can you investigate this on priority please!
