### ISSUE TITLE
Save Changes button in Challenege Editor Displays Unformatted Alert

### ISSUE THREAD

**Issue by benzoms** [freeCodeCamp/freeCodeCamp#54354]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
When using the challenge editor, upon saving changes, the confirmation alert that pops up reads:
`{"message":"Your changes have been saved and are ready to commit!"}`. 
It should instead read simply: 
`Your changes have been saved and are ready to commit!`. 

**Affected Pages**
Error will appear after saving on on any challenge editor challenge.
For example: (http://localhost:3300/07-scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher).

**To Reproduce**
1. Run the challenge editor with `pnpm run challenge-editor` 
2. Go to (http://localhost:3300)
3. Navigate to any specific challenege. 
4. Pressing the save changes button will then produce the alert with the unformatted message.

**Expected behavior**
The alert should display: 
`Your changes have been saved and are ready to commit!`. 

**Screenshots**
Currently, the alert displays like this:
<img width="448" alt="broken" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/31530092/e8d6b7db-a08b-4f69-b019-075b0a9088ed">

When instead it should look like:
<img width="452" alt="fixed" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/31530092/641dd80f-00a3-4beb-b8c2-b0244a4e0649">

**System**
- Device: Macbook Pro
- OS: Ventura 13.1
- Browser: Chrome
- Version: 123.0.6312.59 (Official Build) (x86_64)

**Recommended fix or suggestions**
The code that handles requests for the challenge editor does not correctly handle saveRoute requests because it expects the incoming object to have the fields `stdout` and `stderr`. I propose a fix where we edit the route handler to check if the incoming objeect posses a `message` field, and if so, `alert()` the message directly instead of using `JSON.stringify()`.

**Additional context**
I will be monitoring this issue closely for the next few hours and I am ready and willing to fix this issue.

**Comment by moT01** [comment]
Sounds good @benzoms, I think we would accept this change. Feel free to make a PR.
