### ISSUE TITLE
Fix tests for step 28 of Authors page project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54367]
### Describe the Issue

A camper on the forum was unable to pass the step.
https://forum.freecodecamp.org/t/learn-fetch-and-promises-by-building-an-fcc-authors-page-step-28/684960

This was their code

```js
   authorContainer.innerHTML = `<p class = "error-msg">There was an error loading the authors</p>`;
```
The failing test was this one 

````md
Your `p` element should have the class `error-msg`.

```js
assert.match(code, /(`|"|')<p\s+class=("|')error-msg\2>/)
```
````

The test needs to be updated to account of spacing

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-fetch-and-promises-by-building-an-fcc-authors-page/step-28

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Karimaljandali** [comment]
I'd like to pick this issue up

**Comment by jdwilkin4** [comment]
@Karimaljandali 

Any issue marked with the `help wanted` label is free to work on. We do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)


Happy coding
