### ISSUE TITLE
Issue with  Learn Advanced Bash by Building a Kitty Ipsum Translator in Relational Database Cert

### ISSUE THREAD

**Issue by NicholaSinks** [freeCodeCamp/freeCodeCamp#54368]
### Describe the Issue

For this challenge: 

> Take a look at the stderr.txt file. The error was redirected to the file and nothing printed in the terminal. You used 2> to redirect stderr. Similarily, you can use 1> to redirect stdout. Enter echo hello bash again and use it to redirect stdout to the stdout.txt file.

I have entered the correct command and even directly copied and pasted from a hint I found on the github for this lesson. The command I'm entering is:
`echo hello bash 1> stdout.txt`
But CodeRoad says I need to enter the correct command

I have tried resetting CodeRoad and GitPod, as well as changing browsers, and killing the terminal and starting a new one, but none of that works. I'm on windows 11 I used Microsoft Edge and Google Chrome in my attempts. I'm happy to provide more information if need be.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-advanced-bash-by-building-a-kitty-ipsum-translator/build-a-kitty-ipsum-translator

### Your code

`echo hello bash 1> stdout.txt`

### Expected behavior

Expected CodeRoad test to pass.

### Screenshots

![Screenshot 2024-04-11 204340](https://github.com/freeCodeCamp/freeCodeCamp/assets/165679758/668975d7-b861-4e0f-8666-7fd7f2b04523)

### System

Device: Desktop
OS: Windows 11
Browser: Microsoft Edge, Google Chrome
Version: Latest

**Comment by moT01** [comment]
There's some issues with continuing a course - if you start a course, take a break, and then try to continue it on another browser, it won't work. CodeRoad stores your current lesson in browser storage - so if you change browsers, the result it that it appears like you are on the lesson you left off, but the tests will be running the test for the first step or something. Did you happen to change browsers @NicholaSinks? If so, you could try to continue the course using the browser you started with. If you start the course from the beginning, does the issue happen again?

**Comment by NicholaSinks** [comment]
I was using the same browser I started with when the error began. I only changed browsers to test if it would fix the problem. And yes, if I start the course from the beginning, by resetting CodeRoad, the error still happens and only on the exact step mentioned.

**Comment by NicholaSinks** [comment]
@moT01 So I checked my topic I pushed to the FreeCodeCamp Forum and someone replied stating that they had the same problem, and got the test to pass by entering the solution from the previous lesson, `bad_command 2> stderr.txt`
Here's a link to that reply: https://forum.freecodecamp.org/t/learn-advanced-bash-by-building-a-kitty-ipsum-translator/684802/3?u=nicksinks01

So I tried it myself just now and the test passed. So it seems multiple people are experiencing this issue but at least that should narrow down the problem.

**Comment by moT01** [comment]
Thanks for reporting @NicholaSinks. This should be fixed now. Do you want to give it another try and confirm?

To anyone coming across this in the future. The issue was that one of the commits to main had `90.1` in the commit message. This lead to coderoad trying to load that commit. I had to reword the commit and force push to main.

**Comment by moT01** [comment]
Closing as fixed. See previous comment.
