### ISSUE TITLE
Reset Code Button Missing

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#54360]
### Describe the Issue

The "reset" button went missing on the projects editor

### Affected Page

Any page with older style editor
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-palindrome-checker-project/build-a-palindrome-checker

### Expected behavior

The reset button should be present.

### System

All

**Comment by Sembauke** [comment]
There is no need for a reset button here, you can just remove all code?

**Comment by jeremylt** [comment]
The cash register starts with code

**Comment by jdwilkin4** [comment]
I think we should have a reset button for the odin remix projects
https://www.freecodecamp.org/learn/the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-a

If a camper is a working through one of those challenges, and messes up their HTML, then they should have the ability to reset it. 

But also, for the JS certs, sometimes it is easier to just click reset and start with a clean slate.

Plus the other editors have the reset button, so we should have it for consistency sake IMO.

**Comment by a2937** [comment]
This seems like a great place to start investigating in my opinion. These seem to be multifile cert projects after all. 

https://github.com/a2937/freeCodeCamp/blob/c29216fe46d2ce1d4424ff2ceaae5c302a4564c2/client/src/templates/Challenges/components/tool-panel.tsx#L95
