### ISSUE TITLE
Fix tests for step 25 of Football team cards to allow for arrow function callbacks or regular functions 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54380]
### Describe the Issue

A camper on the forum ran into an issue here 

https://forum.freecodecamp.org/t/learn-modern-javascript-methods-by-building-football-team-cards-step-25/685021

They wanted to know why they couldn't pass with a regular function for the callback.

```js
playerCards.innerHTML += arr.map (function( ) { });
```

 the directions don't specify it should be an arrow function instead.
but both answers should pass.
So the tests should be updated. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-25

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by iamabjain** [comment]
Hi, Can I work on fixing this issue ? I would need some help in locally setting up so that I can test my code changes.
