### ISSUE TITLE
don't understand what exactly get result

### ISSUE THREAD

**Issue by 01kapils** [FreeCodeCamp/FreeCodeCamp#5438]
Challenge [Waypoint: Use Bracket Notation to Find the NthtoLast Character in a String](http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nthtolast-character-in-a-string#?solution=var%20firstName%20%3D%20%22Ada%22%3B%0A%0Avar%20thirdToLastLetterOfFirstName%20%3D%20firstName%5BfirstName.length%20-%203%5D%3B%0A%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0Avar%20secondToLastLetterOfLastName%20%3D%20lastName%5BlastName.length%20-%201%5D%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(v)%7Breturn%20v%3B%7D)(secondToLastLetterOfLastName)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var firstName = "Ada";

var thirdToLastLetterOfFirstName = firstName[firstName.length - 3];

var lastName = "Lovelace";

var secondToLastLetterOfLastName = lastName[lastName.length - 1];


// Only change code above this line.

(function(v){return v;})(secondToLastLetterOfLastName);

```

**Comment by raisedadead** [comment]
You code is incorrect:
`var secondToLastLetterOfLastName = lastName[lastName.length - 1]`

Change it to:
`var secondToLastLetterOfLastName = lastName[lastName.length -` **2** `]`

Finally, please ask for help in the chat here : [Help](gitter.im/FreeCodeCamp/Help) before reporting bug.
Hope this helps! :)
