### ISSUE TITLE
add a "Click to copy code" button 

### ISSUE THREAD

**Issue by JoyShaheb** [freeCodeCamp/freeCodeCamp#54387]
### Is your feature request related to a problem? Please describe.

All popular website like tailwind css and documentation websites have a common feature of "Click to copy code" button on every code snippet. I believe we can also implement the same feature on our /learn platform

an example from our online /learn code editor.
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/41103233-19c0-4d59-9fa6-f7c60bda0cc2)

### Describe the solution you'd like

users should be able to click and copy code through a small button on top right position of the code snippet
something like this example from [Shadcn UI](https://ui.shadcn.com/docs/installation/vite)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/61899866/53344952-4e4e-4cc0-aaf7-83ae34e8fafe)

### Describe alternatives you've considered

.

**Comment by JoyShaheb** [comment]
@Nirajn2311 @naomi-lgbt  @scissorsneedfoodtoo

**Comment by naomi-lgbt** [comment]
I'd push back against this, actually.

There aren't many steps where we ask campers to copy code. Adding a button is just going to result in more forum posts for all of the steps where we have *generic example* code that campers think they should copy because of this button.

**Comment by Sembauke** [comment]
Sorry @JoyShaheb, it does not seem like a good idea to me either. It also just adds more clutter. We should keep that to a minimum.
