### ISSUE TITLE
Update hint text and description for step 28 of date formatter project

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#54398]
### Describe the Issue

In step 28 of the date formatter project, the hint shows the solution, which is not hard to explain. This might not be ideal for learning, as a camper (especially a JS) beginner can go ahead and copy the solution from the hint without bothering to understand what the code does.

![Screenshot 2024-04-15 at 15 39 53](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/31f7f83d-66e2-4f77-8bca-0b9836d10fb1)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-28

### Your code

N/A

### Expected behavior

The solution should not be in the hint text because it can be described. We could go with something like this:

```md
You should interpolate the `month`, `day`, `year`, `hours`, and `minutes` in the backticks of the `mm-dd-yyyy-h-m` case. Don't forget `month`, `day`, and `year` should be separated with a hyphen. You also have to have the texts Hours and Minutes after the `hour` and `minute` interpolations.
```

 If the text is too long, it is better to break the hint text and test into two.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
The same text is in the description, it would make sense to change description to not give out answer at the start.

**Comment by jdwilkin4** [comment]
> The solution should not be in the hint text because it can be described. We could go with something like this:

Based on the activity I have seen on the forum, I think campers will struggle with connecting "interpolate the `month`, `day`, `year`, `hours`, and `minutes`" with the desired format we are asking from them.

I think it would be best to show them the desired format in the description.

something like this for the description

```md
When the user selects the `Month, Day, Year, Hours, Minutes` option from the dropdown, you need to display the date in the format `mm-dd-yyyy h Hours m Minutes`.

Inside the `case` for `mm-dd-yyyy-h-mm`, use string interpolation to assign the formatted date from above to the `textContent` property of `currentDateParagraph`. Make sure to use the `month`, `day`, `year`, `hours`, and `minutes` variables in your answer.
```

**Comment by Ksound22** [comment]
> > The solution should not be in the hint text because it can be described. We could go with something like this:
> 
> Based on the activity I have seen on the forum, I think campers will struggle with connecting "interpolate the `month`, `day`, `year`, `hours`, and `minutes`" with the desired format we are asking from them.
> 
> I think it would be best to show them the desired format in the description.
> 
> something like this for the description
> 
> ```
> When the user selects the `Month, Day, Year, Hours, Minutes` option from the dropdown, you need to display the date in the format `mm-dd-yyyy h Hours m Minutes`.
> 
> Inside the `case` for `mm-dd-yyyy-h-mm`, use string interpolation to assign the formatted date from above to the `textContent` property of `currentDateParagraph`. Make sure to use the `month`, `day`, `year`, `hours`, and `minutes` variables in your answer.
> ```

So we should leave the hint as is and modify the description text?

**Comment by jdwilkin4** [comment]
for the hint text we could go with this

```md
Your answer should follow this format: `mm-dd-yyyy h Hours m Minutes`. Replace `mm`, `dd`, `yyyy`, `h`, and `m` with the `month`, `day`, `year`, `hours`, and `minutes` variables you created earlier.
```

**Comment by Ksound22** [comment]
> for the hint text we could go with this
> 
> ```md
> Your answer should follow this format: `mm-dd-yyyy h Hours m Minutes`. Replace `mm`, `dd`, `yyyy`, `h`, and `m` with the `month`, `day`, `year`, `hours`, and `minutes` variables you created earlier.
> ```
> 
> 

Ok. Let's open it up for contribution then.

**Comment by jdwilkin4** [comment]
# Note to contributors 

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-the-date-object-by-building-a-date-formatter/65389de504d0f2ca10e92a57.md

## updates to description
please use this for the updated description
https://github.com/freeCodeCamp/freeCodeCamp/issues/54398#issuecomment-2057685848

## updates to hint text
please use this for the updated hint text
https://github.com/freeCodeCamp/freeCodeCamp/issues/54398#issuecomment-2059524340

Happy coding
