### ISSUE TITLE
What is wrong? I can't complete the challenge somehow..

### ISSUE THREAD

**Issue by TadasDigital** [FreeCodeCamp/FreeCodeCamp#5439]
![untitled](https://cloud.githubusercontent.com/assets/16428240/11995751/fe909bc6-aa5e-11e5-8e53-edcf188ba952.png)

**Comment by raisedadead** [comment]
I can't see the radio button code in the screen shot. Yet, to confirm:

1. Have you nested you **radio buttons** ( **NOT** the regular buttons below the image) within their divs?

```
<form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    ...
</form>
```

Then it wont pass.

2. Apply the mentioned classes to the div elements for the radio buttons.

Please refer the link : [Help! I Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Post your code here, if you feel its correct and yet the test is not passing, (Copy & Paste from the editor window)

**Comment by Hufflepalian** [comment]
Where are your form elements, OP?

The "Indoor/Outdoor" buttons are your radio buttons. You have three other buttons selected.

Where you see your form tags, below these three buttons, that is where your radio buttons are. Frame them both in one "div" tag with the class "row". Frame each button with another "div" tag, this time with "col-xs-6" as a class.

Good luck, OP. :)

**Comment by ltegman** [comment]
Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for help with challenges. Github issues are got bugs or feature requests.

Thanks and happy coding!

**Comment by TadasDigital** [comment]
Thank you!
