### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue 

### ISSUE THREAD

**Issue by inesllopart** [FreeCodeCamp/freecodecamp#544]
The challenge asks for: Wrap your image element inside an anchor element that has its href attribute set to "#".

My code is:

<p>Click here for <a href='#'><img src='https://bit.ly/fcc-kittens'></a></p>

And when I hover over the image, the mouse cursor becomes a link clicking pointer. However I cannot complete the challenge. 

Thank you, 
Ines

**Comment by denmch** [comment]
I just tried this and couldn't duplicate it. It passed as expected.

BTW, you want to be sure to wrap your code in back ticks (check out [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) and scroll down to Syntax Highlighting to see how it works). Without marking that as code, it renders as html. I was onl;y to read your code because it the bot posted it to the Slack chat in plain text.

**Comment by QuincyLarson** [comment]
@inesllopart I can't read your code because GitHub is interpreting it literally. Please put a:
``` on blank lines before and after your code.

**Comment by QuincyLarson** [comment]
This seems to be passing in Safari, Firefox and Chrome on Mac. I don't know what issue you are experiencing. Here is the code I used:

```
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
  .thick-green-border {
    border-color: green; 
    border-width: 10px; 
    border-style: solid; 
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
