### ISSUE TITLE
update editable regions for step 47 of calorie counter 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54402]
### Describe the Issue

A camper on the forum was unable to pass the lesson

https://forum.freecodecamp.org/t/learn-form-validation-by-building-a-calorie-counter-step-47/685533/2

this was their code

```js
/* file: script.js */
// User Editable Region

function addEntry() {
    const targetInputContainer = document.querySelector(`#${entryDropdown.value} .input-container`);
    const entryNumber = targetInputContainer.querySelectorAll('input[type="text"]').length;
    const HTMLString = `<label for="${entryDropdown.value}-${entryNumber}-name">Entry ${entryNumber} Name</label>`
}

// User Editable Region
```
the issue was here

```js
    const HTMLString = `<label for="${entryDropdown.value}-${entryNumber}-name">Entry ${entryNumber} Name</label>`
```
the tests only accept it if the label is on the next line like this

```js
    const HTMLString = `
     <label for="${entryDropdown.value}-${entryNumber}-name">Entry ${entryNumber} Name</label>`
```
see suggested fix down below about updating the editable regions

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-47

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
I remembered this issue here where there were issues with the newlines

https://github.com/freeCodeCamp/freeCodeCamp/issues/52741

So, I feel like an easier fix would be to just fix the editable regions 

Here should be the new fix:

```js
function addEntry() {
  const targetInputContainer = document.querySelector(`#${entryDropdown.value} .input-container`);
  const entryNumber = targetInputContainer.querySelectorAll('input[type="text"]').length;
  const HTMLString = `
  --fcc-editable-region--
  <label>Entry ${entryNumber} Name</label>`;
  --fcc-editable-region--
}
```

**Comment by naomi-lgbt** [comment]
I'm going to flag this one for first-timers only.
