### ISSUE TITLE
Collect Feedback from campers on every completed challenge

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5441]
As per this Reddit Comment:
https://www.reddit.com/r/FreeCodeCamp/comments/3y0h71/honestly_where_does_freecodecamp_lack/cya1330

We should be collecting (optional) user feedback after every completed challenge.  Add additional buttons/interface elements to the existing "Challenge Completion" popup, or some other feedback mechanism if we move to toasts.

General ideas might be:  
* Thumbs up/Thumbs Down
* 5 Star/10 Star rating
* "Comment on this Challenge"
* "How could this challenge be improved?"
* Structured questions like "Favorite Part"/"Least Favorite Part

Feedback should be tied to the file version: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5405

Possibly use GA to capture the data?

Would love additional comments from @QuincyLarson, @terakilobyte, @evaristoc, and @FreeCodeCamp/issue-moderators

**Comment by SaintPeter** [comment]
As per @terakilobyte:
4 Radio Buttons
>What can we most improve?
Instructions
References
Seed Code
Nothing, it's great

Plus:
Tell us what you thought about it.

**Comment by guipsamora** [comment]
Awesome idea!! 
I'd add a level question, something like.
How was this challenge? Radio buttons
- Easy-peasy
- Easy
- At my level
- Hard
- Superhard

**Comment by GregFoley** [comment]
I think the basic feedback you'd want to collect on each challenge would be:
1) a rating, stars or numerical; and
2) an open-ended feedback form, e.g. "likes, dislikes, and suggestions for improvement"

**Comment by xangria** [comment]
The sort of feedback that would be helpful for me as a learner to give is something along these lines: 
1) Do you have previous experience with this concept? Yes/No. 

2) Rate the difficulty of the challenge on a scale of 1-#. 
3) Was the challenge explained clearly? Yes/No. If no, how could the instructions be clarified?

**Comment by raisedadead** [comment]
Let's get this implemented.
/cc @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
Tagging @evaristoc

**Comment by QuincyLarson** [comment]
I like still like the idea of just gathering better passive data, rather than asking people. We have a lot of data we're not analyzing, like the number of tries and the amount of time it takes to complete the challenge. I feel like we get a better understanding by looking at these data than pestering campers for subjective reviews. 

Once we're making better use of these data, I could definitely see randomly prompting campers with a  thumbs up / meh / thumbs down option in toasts after completing challenges.
