### ISSUE TITLE
Updates to step 40 and 41 of Number Sorter Challenge 

### ISSUE THREAD

**Issue by katereverie** [freeCodeCamp/freeCodeCamp#54420]
### Describe the Issue

The instruction asks the challenger to "return a single subtraction calculation using a and b" without providing a piece of contextual information that if `a` and `b` are both number-like string, `a` - `b` will return a numeric result. 

First coming into the challenge, my thought process was to convert `a` and `b` into numbers, using `Number()` or `parseInt()`. But neither method passed the test. Later, I suspected that the calculation (`a` - `b`) without converting `a` and `b` into numbers first will still return a number, I passed the test. 

I am not sure whether this counts as a bug in the test. Nevertheless, I thought it would be clearer for the challengers had they been provided with the relevant information. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-algorithmic-thinking-by-building-a-number-sorter/step-41

### Your code

```

  const sortedValues = inputValues.sort((a, b) => {
    return Number(a) - Number(b);
  });

```

### Expected behavior

I expected this code to pass the test. 
I was informed that the callback function should return `a - b`, but not informed about the reason why `Number(a) - Number(b)` doesn't pass.

### System

- Device: Laptop
- OS: Windows 11
- Browser: FireFox
- Version: 125.0.1

**Comment by naomi-lgbt** [comment]
I'm not sure updating this is necessary. In the step previous, it's explained how the numbers are sorted, so the camper should already know it's an array of numbers.

I'd rather see step 40 updated to explain that `a` and `b` represent elements in the array being sorted.

**Comment by jdwilkin4** [comment]
To me, it looks like the core issue brought up here is that campers are not 100% sure what the data types are in the `inputValues` array. So we could update step 40 to explain that a and b represent the numbers in the array being sorted.

But we could also expand on the steps where campers convert the input values from strings to numbers.


Step 7 is where the string inputs were converted to numbers
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-algorithmic-thinking-by-building-a-number-sorter/step-7

But we could update the flow to be this instead

## updated step 7

 // have one step to just have the string dropdown values like this
   const inputValues = [
    ...document.getElementsByClassName("values-dropdown")
  ].map((dropdown) => dropdown.value);

## new step 8
// have a step to log this information to the console so they can see the strings for themselves
 console.log(inputValues)

## new step 9
  // then have a step to refactor input values to create an array of numbers 
  const inputValues = [
    ...document.getElementsByClassName("values-dropdown")
  ].map((dropdown) => Number(dropdown.value));

## new step 10
have campers remove the console statement and resume with the rest of the steps
  console.log(inputValues)


that way, now they will see exactly what values they are working with and they will know for sure they are working with number values.

**Comment by a2937** [comment]
Beyond the `parseInt` being unnecessary,  what was wrong with that answer? Secondly what kind of message do we give campers that try to add those things in step 40; it should probably be made clear why the tests aren't passing. 


Though I will add the following,  those modifications to the steps are a really great idea and I couldn't think that of that on my own.

**Comment by jdwilkin4** [comment]
I went ahead and created this separate issue here to breakdown the `inputValues` array
https://github.com/freeCodeCamp/freeCodeCamp/issues/54434

But as for this issue, let's go with this updated description for step 40.

````md
Notice how the number `10` is placed at the beginning of the array. This is because the default behavior of `.sort()` is to convert the numbers values to strings, and sort them alphabetically. And `10` comes before `2` alphabetically.

To fix this, you can pass a callback function to the `.sort()` method. The callback function has two parameters - for yours, use `a` and `b`. The parameters of `a` and `b` represent the number values in the array that will be sorted.

Leave the function empty for now.
````
As for step 41, let's keep the description as is.
I am cool with adding in the updates to the tests that @a2937 made.
