### ISSUE TITLE
Split chalenges into separated files

### ISSUE THREAD

**Issue by HoBi** [FreeCodeCamp/FreeCodeCamp#5443]
Hello, I have took a look at your architecture of chalenges and it is really awful. Why do you have only 1 file for each "section"?

For example, `01-front-end-development-certification/basic-javascript.json` file has **2322 lines** and there is only English and probably Spanish translation of description! Imagine you have translate for 10, 20 languages... I have no idea how can it be clearly. :no_entry:  

What about split each chalenge to separated file (probably with some `$$-` prefix), for example - `01-front-end-development-certification/basic-javascript/07-something.json`

**Comment by BerkeleyTrue** [comment]
@HoBi Thanks for the feedback. We have an editor and soon there will be very little reason to edit challenges directly. 

Happy Coding!
