### ISSUE TITLE
Learn Bash by Building a Boilerplate - Glitched in step 106.5 

### ISSUE THREAD

**Issue by Emeryx** [freeCodeCamp/freeCodeCamp#54432]
### Describe the Issue

I at least think it's step 106.5? Weird name for a step, I found it here https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md#1065-list

The previous step asks to move a file to the folder before the current one the terminal is in, Then this step  asks to check if the file was moved to another folder using ls

In my case, I think I went too fast and the file is still already located in the same folder, And on the other folder

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/16bc1c2b-fc73-47d6-ae82-64b7096653ec)

(Even after resetting, This is the same result)

Removing the requested file and hitting ls again does not work and does not get me past this stage

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/32bc6a1b-9b76-4414-88fb-ff17914feb18)

I'm not sure what to do with this bug, I am really 98% certain this is not my fault and may need a fix 

Thanks in advance

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate

### Your code

```
camper: /website$ cd /workspace/project/website/images
camper: /images$ ls
```

### Expected behavior

I expect to pass the test after hitting ls on the terminal but the conditions aren't met because when i reset my program it doesn't update to the correct state, and updating it manually does not help, Neither does removing the file from both folders, Creating it on images and moving it to the parent folder again

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by moT01** [comment]
I was unable to reproduce this. If it was cause by you going too fast, I'm not sure how we can fix that.

The test for that step checks that you entered the `ls` command while in the `project/website/images` folder.

It appears like you did that @Emeryx. You didn't happen to rename the `project` folder by accident? Unlikely.

We can try some debugging. What do you see when you enter this command: `cat /workspace/project/freeCodeCamp/.mocharc.json`

You could check the CodeRoad logs to see if anything something happened between steps. Click the `OUTPUT` tab in the terminal, you can see it in your screenshots - then find the dropdown on the right and select `CodeRoad (logs)` - then see what the commands say between steps `1060.1` and `1065.1` (It's just two steps.) - and share the output if you could.

**Comment by Emeryx** [comment]
I haven't renamed the folder, I went through all the steps methodically

Upon writing down `cat /workspace/project/freeCodeCamp/.mocharc.json` i get:
```
{
  "spec": ["./test/1065.test.js"],
  "reporter": "mocha-tap-reporter",
  "fail-zero": false,
  "timeout": "5000",
  "grep": "/./"
}
```

Accessing my current CodeRoad Logs (After restarting the Gitpod workplace), It looks like this and stays like this even when I go to the `images` directory and hit `ls`

```
coderoad v0.19.4
STATE: "Setup.Startup"
ROUTE: "Setup.Startup": On level unknown, step unknown
EDITOR_STARTUP
Continuing tutorial from progress: level 1065 step 1065.1
LOAD_STORED_TUTORIAL
EDITOR_TUTORIAL_CONTINUE_CONFIG
Tutorial: Learn Bash by Building a Boilerplate (2.0.0)
Command: ./freeCodeCamp/setup.sh
COMMAND_START
Calling command: ./freeCodeCamp/setup.sh
EDITOR_LEVEL_ENTER
EDITOR_STEP_ENTER
STATE: "Tutorial.Level.Load"
ROUTE: "Tutorial.Level.Load": On level 1065, step 1065.1
STATE: "Tutorial.Level.Normal"
ROUTE: "Tutorial.Level.Normal": On level 1065, step 1065.1
Calling command: git log -n 1 --pretty=format:%s 010dcccfea5e53774228ef332f66d16fb431b00e
Calling command: git log -g --grep='1065.1'
Command output: 
COMMAND_SUCCESS
Command: ./freeCodeCamp/reset.sh
COMMAND_START
Calling command: ./freeCodeCamp/reset.sh
Calling command: git cherry-pick -X theirs 010dcccfea5e53774228ef332f66d16fb431b00e
Command output: 
COMMAND_SUCCESS
cherry-pick-commit failed: Command failed: git cherry-pick -X theirs 010dcccfea5e53774228ef332f66d16fb431b00e
error: Cherry-picking is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed

Calling command: git stash --include-untracked
STATE: "Tutorial.Level.Normal"
ROUTE: "Tutorial.Level.Normal": On level 1065, step 1065.1
STATE: "Tutorial.Level.Normal"
ROUTE: "Tutorial.Level.Normal": On level 1065, step 1065.1
STATE: "Tutorial.Level.Normal"
ROUTE: "Tutorial.Level.Normal": On level 1065, step 1065.1
STATE: "Tutorial.Level.Normal"
ROUTE: "Tutorial.Level.Normal": On level 1065, step 1065.1
```

I guess it will not show information about steps 106

**Comment by Emeryx** [comment]
Oh my god. When pressing the run button on CodeRoad it finally got me to the next stage, I just haven't done that - It always worked automatically before

Still with the header.png being present though

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/162888472/d5775858-6cd5-48a0-82cd-bcd202315845)

**Comment by moT01** [comment]
The tests are supposed to run automatically. Something happened that caused them to stop doing that. It likely wasn't anything you did. I'm not quite sure what causes that - it's difficult to reproduce. Curious, are you running the course in Gitpod or locally?
