### ISSUE TITLE
npm run only-once error

### ISSUE THREAD

**Issue by RDominique** [FreeCodeCamp/FreeCodeCamp#5444]
I'm following the Getting-Started instructions on https://github.com/FreeCodeCamp/FreeCodeCamp

After the command rpm run only-once, I get this (see below)...

Some help please.

[npm-debug.txt](https://github.com/FreeCodeCamp/FreeCodeCamp/files/72194/npm-debug.txt)

**Comment by ltegman** [comment]
Did you have mongo running when you ran this script? What happens if you run `node seed/`?

**Comment by MyNameIsURL** [comment]
As Itegman said, you may not have mongo installed and running.  Try opening up a terminal window and typing "mongo" without the quotes and the mongo interface should pop up.  If you have installed mongo and you just haven't started it, type "mongod" without the quotes and that will start mongo.
