### ISSUE TITLE
Problem with step 46 in Accessible Quiz

### ISSUE THREAD

**Issue by TundraCoder** [freeCodeCamp/freeCodeCamp#54457]
### Describe the Issue

This problem is supposed to target only the anchor elements inside the list.  It however accepts an answer that targets all anchor elements on the page which renders the footer link unreadable.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-46

### Your code

```
a {
  color: _#dfdfe2;
}




```

### Expected behavior

It should have marked this wrong because it did not specifically target the links in the list.

### Screenshots

![Screenshot 2024-04-20 093547](https://github.com/freeCodeCamp/freeCodeCamp/assets/167368703/f514cc84-ec00-4405-9806-c8f2aaf6ea3f)

### System

- Device: PC
- OS: Windows 11
- Browser: Edge
- Version: 124

**Comment by jdwilkin4** [comment]
It looks like a PR was created a few hours ago to address this issue

**Comment by jdwilkin4** [comment]
I went ahead and linked the issue with the PR
