### ISSUE TITLE
Fix Waypoint: Override Class Declarations by Styling ID Attributes

### ISSUE THREAD

**Issue by willnwhite** [FreeCodeCamp/FreeCodeCamp#5446]
should say to declare #orange-text above .pink-text and .blue-text to prove that id overrides class in CSS: if it's declared below them, it could just be overriding them because of it being declared below them

**Comment by HoBi** [comment]
:+1:

**Comment by bugron** [comment]
See the last paragraph:
> Note: It doesn't matter whether you declare this css above or below pink-text class, since id attribute will always take precedence.
Closing this issue. @willnwhite thanks for posting.
