### ISSUE TITLE
Update step 37 tests for pyramid project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54466]
### Describe the Issue

A camper on the forum had issues with passing step 37 of the pyramid project
https://forum.freecodecamp.org/t/learn-introductory-javascript-by-building-a-pyramid-generator-step-37/686331

This was their code
```js
for (const row of rows) {

  result = row + result ;

  console.log(result);
}
```

Their code is correct but the tests expect a certain order of `result = result+row`
The tests should be updated to expect either correct answer

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-37

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by heartofstoneclothing** [comment]
const character = "#";
const count = 8;
const rows = [];

for (let i = 0; i < count; i = i + 1) {
  rows.push(i);
}

let result = ""

for (const row of rows) {

  result = `result` + `row`;

  console.log(result);

}

This worked for me, it took a while but realized I needed to swap the result with the row...
This was helpful thank you

**Comment by cym561** [comment]
Thank you for this,I was really stuck
