### ISSUE TITLE
Accessibility: Additional Themes

### ISSUE THREAD

**Issue by ShadowOfNyxx** [freeCodeCamp/freeCodeCamp#54475]
### Is your feature request related to a problem? Please describe.

I'm hard of sight and find it hard to read off of dark mode. When I use light mode they tend to be too bright, causing other visual issuers.

### Describe the solution you'd like

Addition of additional themes (Such as Solarised Light)

### Describe alternatives you've considered

Possibly adjusting the current light mode to be slightly darker

**Comment by naomi-lgbt** [comment]
Rather than building in more themes for us to maintain, I'd love to go to an approach that allows campers to define their own custom theme.

**Comment by lasjorg** [comment]
Just FYI, there is a high contrast theme you can try. But it might not do the job.

<kbd>F1</kbd> > Type "theme" (it is called "Toggle High Contrast Theme")
