### ISSUE TITLE
the goals disappeared, could not refresh to get goals back

### ISSUE THREAD

**Issue by MissMogly** [FreeCodeCamp/FreeCodeCamp#5447]
Challenge [Waypoint: Manipulate Arrays With pop](http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop#?solution=var%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0Avar%20removedFromMyArray%20%3D%20myArray.pop()%3B%20%2F%2F%20removedFromOurArray%20now%20equals%203%2C%20and%20ourArray%20now%20equals%20%5B1%2C2%5D%0A%0Avar%20myArray%20%3D%20%5B%22John%22%2C%2023%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20removedFromMyArray%3B%20%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(y%2C%20z)%7Breturn%20'myArray%20%3D%20'%20%2B%20JSON.stringify(y)%20%2B%20'%20%26%20removedFromMyArray%20%3D%20'%20%2B%20JSON.stringify(z)%3B%7D)(myArray%2C%20removedFromMyArray)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = [1,2,3];

var removedFromMyArray = myArray.pop(); // removedFromOurArray now equals 3, and ourArray now equals [1,2]

var myArray = ["John", 23];

// Only change code below this line.

var removedFromMyArray; 

// Only change code above this line.

(function(y, z){return 'myArray = ' + JSON.stringify(y) + ' & removedFromMyArray = ' + JSON.stringify(z);})(myArray, removedFromMyArray);

```

**Comment by sludge256** [comment]
Does running the test (ctrl+enter) show the goals?

**Comment by ltegman** [comment]
Your code has a syntax error that is preventing the tests from running. Fix that error and the tests will run. Thanks and happy coding!
