### ISSUE TITLE
Add `package.json` scripts for playwright

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#54488]
We should add `package.json` scripts for running Playwright tests.

In the root level `package.json`, add these two scripts:

```
"playwright:run": "playwright test",
"playwright:watch": "playwright test --ui"
```

**Comment by mahmudhmh** [comment]
@naomi-lgbt added playwright `run` and `watch` to the root level `package.json` and passed all the tests need review to be merged @ 
you can check the pr #54493
