### ISSUE TITLE
the last item is obviously not a palindrome so why it should return true?

### ISSUE THREAD

**Issue by peluhovskiy** [FreeCodeCamp/FreeCodeCamp#5448]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%7B%0A%09%09%09%09%09var%20deCap%20%3D%20str.toLowerCase()%3B%0A%09%09%09%09%09var%20strAr%20%3D%20%5B%5D%3B%0A%09%09%09%09%09var%20j%20%3D%200%3B%0A%09%09%09%09%09var%20i%20%3D%200%3B%0A%09%09%09%09%09%0A%09%09%09%09%09while%20(i%20%3C%3D%20deCap.length%20-%201)%7B%0A%09%09%09%09%09%09if%20(deCap%5Bi%5D%20!%3D%3D%20%22.%22%20%26%26%20deCap%5Bi%5D%20!%3D%3D%20%22%2C%22%20%26%26%20deCap%5Bi%5D%20!%3D%3D%20%22%20%22)%7B%0A%09%09%09%09%09%09%09strAr%5Bj%5D%20%3D%20deCap%5Bi%5D%3B%0A%09%09%09%09%09%09%09j%20%2B%2B%3B%0A%09%09%09%09%09%09%7D%0A%09%09%09%09%09%09i%20%2B%2B%3B%0A%09%09%09%09%09%7D%0A%09%09%09%09%09%0A%09%09%09%09%09var%20newStr%20%3D%20strAr.join('')%3B%0A%09%09%09%09%09var%20revAr%20%3D%20strAr.reverse()%3B%0A%09%09%09%09%09var%20revStr%20%3D%20revAr.join('')%3B%0A%09%09%09%09%09%0A%09%09%09%09%09if(revStr%20%3D%3D%20newStr)%7B%0A%09%09%09%09%20%20%09%09return%20true%3B%0A%09%09%09%09%09%7D%20else%20%7B%0A%09%09%09%09%09%09return%20false%3B%0A%09%09%09%09%09%7D%0A%09%09%09%09%7D%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str){
					var deCap = str.toLowerCase();
					var strAr = [];
					var j = 0;
					var i = 0;
					
					while (i <= deCap.length - 1){
						if (deCap[i] !== "." && deCap[i] !== "," && deCap[i] !== " "){
							strAr[j] = deCap[i];
							j ++;
						}
						i ++;
					}
					
					var newStr = strAr.join('');
					var revAr = strAr.reverse();
					var revStr = revAr.join('');
					
					if(revStr == newStr){
				  		return true;
					} else {
						return false;
					}
				}

palindrome("0_0 (: /-\ :) 0-0"); // it's obviously not a palindrome (but demands to be true in the assignment)

```

**Comment by sludge256** [comment]
>You'll need to remove all **non-alphanumeric characters (punctuation, spaces and symbols)** and turn everything lower case in order to check for palindromes.

0_0 (: /-\ :) 0-0 will turn into 0000
