### ISSUE TITLE
Learn localStorage by Building a Todo App step 18 random wording

### ISSUE THREAD

**Issue by Supravisor** [freeCodeCamp/freeCodeCamp#54490]
### Describe the Issue

Wording in the description suggests a random number will appear in the console.
The number generated is not random.  It is a result of the calculation of the number of millisecond elapsed since January 1, 1970 00:00:00 UTC

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-18

### Your code

```
Open up the console to see the result with a random number added.
```

### Expected behavior
Remove the following text:
```
Open up the console to see the result with a random number added.
```

On a new line, the following text to appear:
```
Open up the console to see the result with a unique number based on the `Date.now()` static method added to the `id` property value.
```

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/913c85c8-24d9-402d-ab28-cc64c6ab67f3)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by omair-muhammad** [comment]
Hi, Can you mention the files where this change should be made.

**Comment by jdwilkin4** [comment]
> Open up the console to see the result with a unique number based on the `Date.now()` static method added to the `id` property value.

This could be simplified to say "Open up the console to see the result"

**Comment by jdwilkin4** [comment]
# Note to contributors 

This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/650300a25b6f72964ab8aca6.md

## updated description
```md
To make the `id` more unique, add another hyphen and use <dfn>Date.now()</dfn>.

`Date.now()` returns the number of milliseconds elapsed since `January 1, 1970 00:00:00 UTC`.

```js
console.log(Date.now()); // 1628586800000
```

To see the new result, click on the `"Add New Task"` button. Then add a title of `WALK DOG` and click on the `"Add Task"` button. 

Open up the console to see the result.
```

Happy coding
