### ISSUE TITLE
Article "The JavaScript DOM Manipulation Handbook" code example typo

### ISSUE THREAD

**Issue by Liumingxun** [freeCodeCamp/freeCodeCamp#54503]
### Describe the Issue

the code example have a typo, which access the property should be `nextElementSibling`, `previousSibling` and `previousElementSibling`, the original text is `.next` and `.previous`

### Affected Page

https://www.freecodecamp.org/news/the-javascript-dom-manipulation-handbook/

### Steps to Reproduce

NA

### Recommended fix or suggestions

NA

### Screenshots

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/36471625/5b539e39-3563-4941-a34e-c2a4bb456191)

**Comment by naomi-lgbt** [comment]
Thanks for catching this. I've updated the article - it should go out in the next build.
