### ISSUE TITLE
Test case bug in Check for Palindromes

### ISSUE THREAD

**Issue by natetwo** [FreeCodeCamp/FreeCodeCamp#5450]
The last test case in the bonfire is wrong. It says "palindrome("0_0 (: /-\ :) 0-0") should return true." However it should return false b/c 0_0 != 0-0.
http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes
Thanks in advance for looking into the matter.

**Comment by prayashm** [comment]
Refer #5448
