### ISSUE TITLE
Update tests for step 62 of pyramid project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54502]
### Describe the Issue

A camper on the forum was trying to pass this step with the following code:
https://forum.freecodecamp.org/t/learn-introductory-javascript-by-building-a-pyramid-generator-step-62/686710

```js
function padRow(rowNumber, rowCount) {
  const spaces = "·".repeat(rowCount - rowNumber); 
    return spaces + character.repeat(rowNumber * 2 - 1) + spaces;
}
```

Their issue was that they shouldn't have the `"."` but instead us an empty space `" "` like the directions say.

With the correct modications, this is a valid answer

```js
function padRow(rowNumber, rowCount) {
  const spaces = " ".repeat(rowCount - rowNumber);
  return spaces + character.repeat(rowNumber * 2 - 1) + spaces;
}
```

but with the current tests, it would fail because we are checking for `" ".repeat(rowCount - rowNumber)` twice. 

```js
assert.lengthOf(code.match(/" ".repeat/g), 2);
```
either valid answer should pass

## valid answers

```js
function padRow(rowNumber, rowCount) {
  const spaces = " ".repeat(rowCount - rowNumber);
  return spaces + character.repeat(rowNumber * 2 - 1) + spaces;
}
```
or 

```js
function padRow(rowNumber, rowCount) {
  return " ".repeat(rowCount - rowNumber) + character.repeat(rowNumber) + " ".repeat(rowCount - rowNumber);
}
```
## updates to tests

remove this test completely

````md
You should call .repeat() on your two " " strings.

```js
assert.lengthOf(code.match(/" ".repeat/g), 2);
```
````
And instead just have one test for the final result.
This way multiple answer pass

here is the updated test

````md
You should call `.repeat()` on your `" "` strings to repeat them `rowCount - rowNumber` times.

```js
assert.equal(padRow(1, 3), "  #  ");
```
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-62

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660f374d532dc41189cc9cc2.md

Happy coding

**Comment by hnrykm** [comment]
Can I pick this one up?
