### ISSUE TITLE
Please I need help:  "The property nickname of myCar should be a string."

### ISSUE THREAD

**Issue by Amenorhu** [FreeCodeCamp/FreeCodeCamp#5451]
Challenge [Waypoint: Make Instances of Objects with a Constructor Function](http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20%20this.wheels%20%3D%204%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:41.0; WUID=f96eca778104a82e91bd25d625bc08b3; WTB=2937) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.
var Car = function() {
   this.wheels = 4;
};

var myCar = new Car();


```

**Comment by AkiraLaine** [comment]
@Amenorhu Your code should look like this:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var myCar = new Car();
myCar.nickname = "Somthing";
```

But in the future, please do not ask for help  here. We have a chat room just for that: [Help](https://gitter.im/FreeCodeCamp/Help)

**Comment by Amenorhu** [comment]
Thanks got it!

**Comment by balls777** [comment]
half the time they are not wording the sentence right !!!
