### ISSUE TITLE
Fix punctuation for step 55 of forum leaderboard project

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#54527]
### Describe the Issue

The first sentence in the description of step 55 of the forum leaderboard project goes like this:

```md
Inside, the first td element, add an embedded expression ${}.
```

The first comma is not needed. Though it doesn't change the meaning but the flow, it's weird and unnecessary.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-asynchronous-programming-by-building-an-fcc-forum-leaderboard/step-55

### Your code

N/A

### Expected behavior

There should not be a comma after the word "Inside". The sentence should be "Inside the first td element, add an embedded expression ${}."

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-asynchronous-programming-by-building-an-fcc-forum-leaderboard/645763874fd6d901c273db29.md

## Changes that need to be made
```md
Inside the first `td` element, add an embedded expression `${}`. Inside that expression, call the `forumCategory` function with the argument of `category_id`. 
```

Happy coding
