### ISSUE TITLE
Provide explanation for difference between normal CSS declaration and jQuery call

### ISSUE THREAD

**Issue by willnwhite** [FreeCodeCamp/FreeCodeCamp#5453]
On reading

> `$("#target1").css("color", "blue");`
> This is slightly different from a normal CSS declaration, because the CSS property and its value are in quotes, and separated with a comma instead of a colon.

And not knowing about JS yet, I'm sure I'd ask "Why?"

Suggest "'css("color", "blue");' is "passing" values to the CSS engine for it to change them, rather than you changing them directly (as we've been doing so far)."

**Comment by ltegman** [comment]
I don't think this is necessary. JQuery and CSS and very different things with completely different syntax. We show the correct syntax in the example so if users are following along with the instructions there will be no problem. Thanks and happy coding!
