### ISSUE TITLE
Update Step 79 & 80 of Building a Platformer Game

### ISSUE THREAD

**Issue by katereverie** [freeCodeCamp/freeCodeCamp#54540]
### Describe the Issue

Implicitly returning the callback passed into `.forEach()` won't pass the test.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-79

### Your code

```
    if (keys.rightKey.pressed && isCheckpointCollisionDetectionActive) {
      platforms.forEach(platform => platform.position.x -= 5);
    }

```

### Expected behavior

This should pass at least for this step, and the following step as well.
I found out later that curly brackets are missed here. 
The hint/error message is also not helpful here because the code provided above does exactly what the hint asks campers to do.
I suggest adding "Please use curly brackets for the callback for this step" or modifying the corresponding test.

### Screenshots

![Screenshot 2024-04-26 at 08-14-22 freeCodeCamp org](https://github.com/freeCodeCamp/freeCodeCamp/assets/143613315/b7b3b9c8-cb20-4d6b-af55-e0f78059dccc)

### System

- Device: Laptop
- OS: Windows 11
- Browser: FireFox
- Version: 125.0.2 (64-bit)

**Comment by naomi-lgbt** [comment]
Yes, these two steps should be updated to allow for implicit returns.
