### ISSUE TITLE
User can create a task with the white space/blank title - todoApp

### ISSUE THREAD

**Issue by code-liana** [freeCodeCamp/freeCodeCamp#54588]
### Describe the Issue

***STEPS TO REPRODUCE:***
1. Start todo App
2. Click on "Add New Task" button
3. On the "Title" field click on the "Space" key (long key on your keyboard) to create a blank space
4. Click on "Add Task"

***ACTUAL RESULT:***
The user created empty task even though title field is required

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-65

### Your code

```JavaScript
taskForm.addEventListener('submit', (e) => {
    e.preventDefault();
    addOrUpdateTask();
});
```

### Expected behavior

User should not be able to create an empty title, as it goes against what we set on HTML. 
```HTML
<input required type="text" class="form-control" id="title-input" value="" />
```
_________________________________________________________________________
as discussed with @jdwilkin4 under the issue https://github.com/freeCodeCamp/freeCodeCamp/issues/54524

_________________________________________________________________________
Ex. of expected behavior 1:

```JavaScript
const isTitleEmpty = (val) => !val.trim().length


taskForm.addEventListener("submit", (e) => {
  e.preventDefault();

  if(isTitleEmpty(titleInput.value)){
    alert("Please provide a title")
    return
  }
  
  addOrUpdateTask();
});
````

Ex. of expected behavior 2:
***JS***
```JavaScript
const errorMessage = document.getElementById("errorMessage");
const isEmpty = (str) => !str || !str.trim();

taskForm.addEventListener('submit', (e) => {
    e.preventDefault();
    if (!isEmpty(titleInput.value)) {
        addOrUpdateTask();
    } else {
        // Create an error message element
        errorMessage.textContent = "Error: title cannot be an empty value!";
        errorMessage.style.display = "block";

        // Remove the error message after 3 seconds
        setTimeout(() => {
            errorMessage.style.display = "none";
        }, 3000);
    }
});
```
***HTML***
```HTML
<div class="task-form-body">
          <label class="task-form-label" for="title-input">Title</label>
          <input required type="text" class="form-control" id="title-input" value="" />
          <label id="errorMessage" style="display: none; color: red; font-weight: bold;"></label>
          <label class="task-form-label" for="date-input">Date</label>
          <input type="date" class="form-control" id="date-input" value="" />
          <label class="task-form-label" for="description-input">Description</label>
          <textarea class="form-control" id="description-input" cols="30" rows="5"></textarea>
</div>
```

### Screenshots

![Screenshot 2024-04-30 141823](https://github.com/freeCodeCamp/freeCodeCamp/assets/24833079/99730128-0f9a-46f9-9360-9cc01849d8db)

### System

Device: Laptop
OS: Windows 11 Home
Browser: Chrome
Version: 124.0.6367.61

**Comment by Bhanubediya** [comment]
Hi Is this issue open ?

**Comment by jdwilkin4** [comment]
@Bhanubediya 

Issues marked with help-wanted or first-timers-only are open for contribution.
You can read the contributing guidelines here
https://contribute.freecodecamp.org/#/index

**Comment by jdwilkin4** [comment]
Personally I like the idea of showing an alert.
But we will wait to hear from the other team members on their thoughts.

If we do go with ex 2., then we shouldn't use inline styles like in the example. The styles should be inside the stylesheet instead. And setTimeout will need to be taught because this is the first time it has shown up.

**Comment by a2937** [comment]
Form validation usually shows up in an error message but I'm not that opposed to an alert. 

Plus we have a great opportunity to teach a new method.

**Comment by code-liana** [comment]
Timeout is introduced to the campers in the next project "Decimal to binary converter".

I think it would be good to go with the alert option.

**Comment by a2937** [comment]
At what point should we introduce the `if` to the equation. I was thinking roughly around step 40.

**Comment by naomi-lgbt** [comment]
This can be added as a new step at the end of the challenge, explaining the presence of the bug (similar to the current last step).

We should use the alert example. The step should have the camper add:

```
  if(isTitleEmpty(titleInput.value)){
    alert("Please provide a title")
    return
  }
```

**Comment by bharateshwq** [comment]
Hey can i contribute to this issue?

**Comment by AshmitGupta** [comment]
Should the task also require the camper to create the function 'isTitleEmpty' or can that just be included in the seed code so that the camper just has to add what @naomi-lgbt suggested?

**Comment by naomi-lgbt** [comment]
We could just do a truthiness check on the value, I think? Updated my comment above.

**Comment by AshmitGupta** [comment]
Ahh yess, I think that would work

**Comment by AshmitGupta** [comment]
Actually, we would have to add the `.trim()` to `titleInput.value` so that it checks for whitespace as well. 

Final code:

```js
if(!titleInput.value.trim()){
  alert("Please provide a title");
  return;
}

Let me know if this looks good

**Comment by naomi-lgbt** [comment]
Sure!
