### ISSUE TITLE
Update code example for step 18 of pyramid project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54584]
### Describe the Issue

We are getting a lot of confusion on the forum about step 18.
The confusion stems from not know how to log the `rows` array to the console.

So we should update the code example in the description to log the example array.
That should help with what is expected to do. 

## updated description

````md
Arrays are special in that they are considered <dfn>mutable</dfn>. This means you can change the value at an index directly.

For example, this code would assign the number `25` to the second element in the array:

```js
let array = [1, 2, 3];
array[1] = 25;
console.log(array); // prints [1, 25, 3]
```

Update the **third** element of your `rows` array to be the number `10`. Then print the `rows` array to your console.
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-18

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660f07d231941bc11719f664.md

Happy coding

**Comment by Rajatnadda** [comment]
let array = [1, 2, 3];
array[1] = 25;
console.log(array); // prints [1, 25, 3]
```
