### ISSUE TITLE
"Update Task" is shown instead of "Add Task" when the user clicks on "Add New Task" - todoApp

### ISSUE THREAD

**Issue by code-liana** [freeCodeCamp/freeCodeCamp#54589]
### Describe the Issue

***STEPS TO REPRODUCE:***
1. Click on "Add New Task"
2. Add title and anything else you want, but not required
3. Click on "Add Task"
4. Then click on "Edit"
5. Then click on the X icon to cancel editing 
6. Click again on "Add New Task" and observe the button

***ACTUAL RESYLT:*** 
"Update Task" text displayed on the button

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-65

### Your code

```JavaScript
const addOrUpdateTask = () => {
    //This line is not triggered on every Add New Task addOrUpdateTaskBtn.innerText = "Add Task"
    addOrUpdateTaskBtn.innerText = "Add Task"
    const dataArrIndex = taskData.findIndex((item) => item.id === currentTask.id)

    const taskObj = {
        id: `${titleInput.value.toLowerCase().replace(/[^A-Za-z0-9\-\s]/g, '').split(" ").join("-")}-${Date.now()}`,
        title: titleInput.value,
        date: dateInput.value,
        description: descriptionInput.value
    };

    if (dataArrIndex === -1) {
        taskData.unshift(taskObj)
    } else {
        taskData[dataArrIndex] = taskObj
    }
    localStorage.setItem("data", JSON.stringify(taskData));
    updateTaskContainer();
    reset();
};

```

### Expected behavior

The user should see "Add Task" text on the button
___________________________________________________________________________
Based on my best understandingwe can just move ```addOrUpdateTaskBtn.innerText = "Add Task"``` to the reset() function.

In this case  button text will always be changed to "Add Task" when the user click on "Add New Task"

```JavaScript
const reset = () => {
    addOrUpdateTaskBtn.innerText = "Add Task"
    titleInput.value = "";
    dateInput.value = "";
    descriptionInput.value = "";
    currentTask = {};
    taskForm.classList.toggle('hidden');
}
```

### Screenshots

![Animation](https://github.com/freeCodeCamp/freeCodeCamp/assets/24833079/a386c105-1a12-4f8f-908a-5e86e95a4386)

### System

Device: Laptop
OS: Windows 11 Home
Browser: Chrome
Version: 124.0.6367.61

**Comment by Bhanubediya** [comment]
Hi @code-liana can I work on this issue ?

**Comment by code-liana** [comment]
@Bhanubediya I don't know FreeCodeCamp process and how they prioritize and work on issues, so I'm not the right person to ask that, but I can mention few people that already say on threads. Maybe they can help you.

 @naomi-lgbt @jdwilkin4 @Ksound22

**Comment by Bhanubediya** [comment]
> @Bhanubediya I don't know FreeCodeCamp process and how they prioritize and work on issues, so I'm not the right person to ask that, but I can mention few people that I already saw before on the threads. Maybe they can help you.
>
> @naomi-lgbt @walking @Ksound22
Thanks for the info.

**Comment by Deep512** [comment]
@Bhanubediya Based on my understanding after looking at a number of issues, until and unless the status label gets updated, the requirement of the solution isn't determined.
So you should wait for them to discuss it (you can also propose solutions). They'll update the status of the issue after that.

**Comment by Supravisor** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/issues/53076 Looks like this issue was raised and merged in January.

**Comment by code-liana** [comment]
@Supravisor thanks, appreciate it. I looked for similar issue. Must have missed it. 

Just a question though. Shouldn't it already be merged than to the main branch? It's still reproducible on the js course. Where is January and it is April already

**Comment by code-liana** [comment]
@Supravisor after looking at the previous issue that was opened and the code that was merged it looks to me like the solution did not provide the user with the desired outcome of having the button changed. I think the right solution would be to add ```addOrUpdateTaskBtn.innerText = "Add Task"``` to the ```reset()``` function instead of ```addOrUpdateTask()```.

So this issue is post fix provided in the issue you mentioned. 
My code in the end looks like the fix says (you can see it above in "Your code" section) and it does not work properly.  https://github.com/freeCodeCamp/freeCodeCamp/pull/53094/files#diff-f68daec32d088edbacd5df716591705d3dd7eabb2dd352fbd583878fd630215fR301


![Fix didn't fix it](https://github.com/freeCodeCamp/freeCodeCamp/assets/24833079/50e4ba53-61b6-438b-98ca-1f2c59089a4a)

**Comment by Ksound22** [comment]
> Hi @naomi-lgbt @walking @Ksound22 can I work on this issue ?

We normally don't assign issues. The first person to file a comprehensive PR gets it.

Please look out for the 'Help wanted' badge when we are done discussing the way forward for the issue.

**Comment by Ksound22** [comment]
Thanks for catching this.

**Comment by jdwilkin4** [comment]
It looks like the fix would need to be the following:

1. current step 52 would need to be removed 
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-52

2. all of the seed code would need to be updated to remove `addOrUpdateTaskBtn.innerText = "Add Task";` from the addOrUpdateTask function

3. remove this last sentence of `With that, you've completed this project.` from current step 65
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-65

4. then add a new step at the very end(new step 66) to mention the bug and have them fix the bug

**Comment by jdwilkin4** [comment]
For interested contributors, make sure to read through the docs on how to properly add and remove steps
https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects?id=how-to-work-on-practice-projects

**Comment by CALOPEZ05** [comment]
Hilo
