### ISSUE TITLE
I chose Simplified Chinese, but the display is English

### ISSUE THREAD

**Issue by xiqing01** [freeCodeCamp/freeCodeCamp#54581]
### Describe the Issue

@
![屏幕截图 2024-04-30 153710](https://github.com/freeCodeCamp/freeCodeCamp/assets/128521705/4a4dd1ed-786b-4c5d-a4f1-82a444ec85ab)

### Affected Page

https://www.freecodecamp.org/chinese/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-30

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

11

### Screenshots

![屏幕截图 2024-04-30 153710](https://github.com/freeCodeCamp/freeCodeCamp/assets/128521705/6e073f01-0735-4068-8372-c75cd1a00b00)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by xiqing01** [comment]
@
![Uploading 屏幕截图 2024-04-30 155109.png…]()

**Comment by Dario-DC** [comment]
I don't think it's a bug. This step is simply not translated yet (probably because it's been updated) and it falls back to English.
Hope this clarifies.

**Comment by ilenia-magoni** [comment]
You can partecipate in the translation of the curriculum if you want: https://www.freecodecamp.org/news/help-translate-freecodecamp-language/

Once the step is translated it will be released.
