### ISSUE TITLE
Learn String Manipulation by Building a Cipher : Step 13 regex too strict

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#54590]
### Describe the Issue

Even though the camper calls all of the requisite methods, the camper can't proceed to the next challenge because they call `print` then the method. There's probably quite a few other Python challenges where this is the case. 

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-13

### Your code

```
text = 'Hello World'
shift = 3
alphabet = "abcdefghijklmnopqrstuvwxyz"
print(alphabet.find(text[0]))
```

### Expected behavior

The camper should be able to proceed to the next challenge. 

### System

- Device: Desktop 
- OS: Windows 10 
- Browser: Firefox
- Version: 125.0.2

### Additional context

I'm looking forward to using the Python AST parser again.

**Comment by pkdvalis** [comment]
Most of the language for instructions is explicit and needs to be followed exactly. If we make this question more flexible that might set an expectation of flexibility in answers going forward. The code need to be consistent with the beginning of Step 14 as well, which does not have `print()`

What if the instructions were modified to explicitly ask the result to be printed?

>At the end of your code, call `.find()` on your alphabet string and pass `text[0]` to the method. Note that a method is just a function that belongs to an object (you will learn more about that in another project). Print the result by writing this line in a call to `print()`.

`print()` has already been introduced at this point, but would this be too complex for Step 13? This is the 13th step in the first project for Python. As it stands, this result is eventually printed in Step 15.

This means if the user uses `print()` here step 14 would also need to be updated.

In step 14 `print()` would be removed and the result assigned to a variable instead.
In step 15 we print the variable.

**Comment by Dario-DC** [comment]
Considering that the result of `.find()` will be printed after two steps, I'd keep the current sequence of steps:
- step 13: `alphabet.find(text[0])`
- step 14: `index = alphabet.find(text[0])`
- step 15: `print(index)`

Regarding the strictness, probably calling `print` should not prevent campers from proceeding to the next step. As @a2937 pointed out, there are several steps in which this occurs and I think we should try to be consistent.

Although regex tests can be easily modified to allow the code with the `print` call to pass, we are switching to ast-based helpers to write tests, and I don't see an easy way to do the same in this case. The AST structure is different and we cannot take into account every time that campers might decide to print something where the instructions don't ask for that.
