### ISSUE TITLE
Add spinner to camper news search

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#546]

**Comment by QuincyLarson** [comment]
This looks like a good spinner: http://lea.verou.me/2013/11/cleanest-css-spinner-ever/

**Comment by LumenTeun** [comment]
I'm not seeing any mention of a license on that page, open or not; could FCC legally use it?

**Comment by QuincyLarson** [comment]
I'll have to check with the author. I'll tweet at her.


- Quincy Larson
"Anyone who has begun to think, places some portion of the world in
jeopardy." - John Dewey

**Comment by LumenTeun** [comment]
Smart. I'm trying to implement it in the meantime. A small concern, the background color of FCC (#eee) is the same as some of the parts of the spinner. This could easily be rectified by changing the colors, but I kind of like how it looks. [Example here](http://codepen.io/LumenTeun/pen/jPLRYq?editors=110)

**Comment by LumenTeun** [comment]
Okay, so I think I got this to work over [here](https://github.com/LumenTeun/freecodecamp/commit/bd3bbeba88fc71db55dbaa5476a567cf6ba42f7d), but my local database is completely empty, so searches are over in fractions of a second. If you can try it out and see if it works (and Lea approves), I'll create a PR and we'll be good to go.

**Comment by LumenTeun** [comment]
No response from Lea yet, @QuincyLarson?

**Comment by BerkeleyTrue** [comment]
@ahstro Did you ever form a PR for this?

**Comment by ahstro** [comment]
I did not because we had not gotten a response from Lea and I didn't want to clog up the PR section. I can create on now if you want to?

**Comment by BerkeleyTrue** [comment]
Yeah if you are up for it.

**Comment by ahstro** [comment]
You're going to want to test it with your database as well. I my empty one loaded very quickly; I tried making it infinite, and that looked good, but it's not the real thing.

**Comment by BerkeleyTrue** [comment]
We are going to move away from this for now. We may revisit in the future.
