### ISSUE TITLE
Default to being signed in for playwright tests

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#54609]
Our Playwright tests sign in before every test, via the https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/global-setup.ts, but they don't use the authentication cookies by default. This is counterintuitive, since it's natural to assume that this means the test runner will be signed in.

To fix this, we should change the https://github.com/freeCodeCamp/freeCodeCamp/blob/main/playwright.config.ts so that the projects use the generated `storageState`. Then it should be possible to remove all the `test.use({ storageState: 'playwright/.auth/certified-user.json' });`, but it will be necessary to manually sign out whenever the tests need the browser to be signed out. This can be achieved with `test.use({ storageState: { cookies: [], origins: [] } });`.

Original discussion:
https://github.com/freeCodeCamp/freeCodeCamp/pull/54481#discussion_r1581288800

**Comment by ojeytonwilliams** [comment]
Hey @huyenltnguyen it's not urgent, but I just wanted to check if you're still planning to work on this? No worries if not - we can open this up for contribution.

**Comment by Sembauke** [comment]
Discussed with Huyen I will be taking a jab at this.
