### ISSUE TITLE
Advise users to turn off autorun on Codepen when doing Ajax Ziplines

### ISSUE THREAD

**Issue by noinkling** [FreeCodeCamp/FreeCodeCamp#5460]
By default, Codepen reloads the page automatically when your code changes. While this is usually a useful feature, when doing Ajax requests it can easily lead to an external API being hammered unintentionally, often resulting in the developer being blocked temporarily from making further successful requests (may have to wait an hour or two, or even a day before it works again, depending on the API).

After diagnosing someone having this issue in the chat, and after having it myself in the past, it seems a good idea to advise users to turn off this feature for Ziplines where Ajax calls are being made, in order to prevent the frustration and confusion that can result. This can be achieved by going to "Settings" > "Behavior" and unchecking "AUTO UPDATE PREVIEW". Doing this makes a "run" button appear where the pen can be reloaded manually instead.

If we want to go a step further, it should also be mentioned that using local sample data when possible during development is a good practice, save for when actual requests are needed.

**Comment by ltegman** [comment]
I like this suggestion a lot. It's both likely to help campers stay out of trouble and considerate of the services whose APIs our students end up hitting.

**Comment by bugron** [comment]
cc @QuincyLarson. What do you think about adding a few steps in `Get Set for our Front End Development Projects` challenge?

**Comment by SaintPeter** [comment]
This seems very reasonable to me.

**Comment by matthewfortier** [comment]
@Itegman @SaintPeter Hi there, this seems like a change that I would love to work on. Can I get some details on where I can find this tutorial, what files would need to be changed, and maybe some guidelines for writing tutorials and how you would like them to be written. Thanks!
