### ISSUE TITLE
Got a bug!!

### ISSUE THREAD

**Issue by sumitgupta477** [FreeCodeCamp/FreeCodeCamp#5462]
Challenge [Waypoint: Comment out HTML](http://www.freecodecamp.com/challenges/waypoint-comment-out-html#?solution=%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%0A--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--
<h1>Hello World</h1>

<p>Hello Paragraph</p>

-->

<h2>CatPhotoApp</h2>


```

**Comment by sumitgupta477** [comment]
This is not working whenever I select the freecodecamp.

**Comment by BerkeleyTrue** [comment]
While true, you have to actually change the order of the lines of code. The instructions clearly state to comment out code, not move it around.

**Comment by ltegman** [comment]
I agree that this isn't a problem, since the instructions say to change the comments but not the order of the HTML itself.

**Comment by panther911** [comment]
The code is not working because you put both your h1 and p elements in the same comment tag. If you put each element in it's own comment it will work regardless of the order. I'm guessing the system checks if each element is enclosed within it's own comment tag.

**Comment by BerkeleyTrue** [comment]
Closing as not an issue

Happy Coding!
