### ISSUE TITLE
Inadequate

### ISSUE THREAD

**Issue by githuvlad** [freeCodeCamp/freeCodeCamp#54639]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
I came across this forum by accident, of course it’s impossible to understand anything there, I started creating topics to explain this, but people are completely inadequate, they simply block the student, no matter what he writes, on the forum everything is done in favor of these inadequate people, here even negative feedback is not missed)

**Comment by Sembauke** [comment]
Sorry to hear you have trouble navigating the forum. Is there any particular issue would like to address?

**Comment by githuvlad** [comment]
I just wanted to give some feedback about www.freecodecamp.org, you are right, I never understood the navigation on Github because everything is confusing and unclear.

**Comment by Sembauke** [comment]
Alright, if you have any questions about coding challenges please defer to forum.freecodecamp.org

**Comment by githuvlad** [comment]
This will not be possible, since the admin has set a ban on writing anything on the forum)
