### ISSUE TITLE
Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by rphares** [FreeCodeCamp/FreeCodeCamp#5463]
This is *by far* the most frequent question I see in the main chat/receive PMs about. It comes up several times a day. The answers they provide aren't syntax/conceptual issues, it is just that many campers seem to think they are supposed to add all three classes to the last one, #target1. Not sure of the best solution-it's seems straightforward to me- but I think it may be this line that causes the confusion to some of our non-native speakers:

`Although it is possible to add multiple classes in a single .addClass() call, let's add them to the same element in three different ways.`

Maybe it is because `although` that is confusing, and stronger emphasis (such as "We *can* add multiple classes in a single..... But this time, let's add one class ...") might help? Or something else, heh.

Cheers!

**Comment by ltegman** [comment]
Thanks for bringing this pattern to our attention. This waypoint has been modified a couple times already in an attempt to clarify wording, but I'm open to further changes. I certainly don't think your suggested change would make it any more unclear and it does have the potential to make it more clear.

I'd be interested in input from other @FreeCodeCamp/issue-moderators

**Comment by SaintPeter** [comment]
I suggested that @rphares submit this and I agree, it needs some love.

How about this:

> Now you know three ways of targeting elements: by type: $("button"), by class: $(".btn"), and by id $("#target1").

> Using `.addClass()`, add only one class at a time to the same element, three different ways:

> Add the animated class to all elements with type button.

> Add the shake class to all the buttons with class .btn.

> Add the btn-primary class to the button with id #target1.'

**Comment by f1rf1n** [comment]
While the last comment is a lot clearer true, you can't actually do that correctly.
Because of the second part:
"Add the shake class to all the buttons with class .btn. "
the tests do not allow button.btn as a valid selector. But it does accept just .btn as a selector, this selects every with the .btn class though, not just buttons?

**Comment by re4ect** [comment]
I also posted another issue with the same challenge. It has to do with why the waypoint is asking to add one class with each of the three selectors. While ate the same time it says the #target1 element should have the classes animated‚ shake and btn-primary. So is it one class or three classes?

**Comment by f1rf1n** [comment]
The other two classes are inherited from the parents, re4ect.

**Comment by re4ect** [comment]
@f1rf1n  Thanks for the reply but it has been resolved.

**Comment by haasDev** [comment]
@re4ect This issue is labeled as help wanted but your last comment says it has been resolved.  Look to do my first oss contribution and thought this would be a good place to start if it hasn't been resolved.  Let me know.

**Comment by raisedadead** [comment]
#### This open for first timers only!

Update the instructions in the challenge to :

> Now you know three ways of targeting elements: by type: `$("button")`, by class: `$(".btn")`, and by id `$("#target1")`.

> Using `.addClass()`, add only one class at a time to the same element, three different ways:

> Add the `animated` class to all elements with type `button`.

> Add the `shake` class to all the buttons with class `.btn`.

> Add the `btn-primary` class to the button with id `#target1`.

References:
https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors 

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).
and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by tianz** [comment]
Hi, new user here. I'm setting up my environment and see if I can help with this one.

**Comment by raisedadead** [comment]
@tianz Awesome! Good luck. Let us know if you are stuck in the help chat room mentioned in the comment above and also go through the contributing guidelines.
