### ISSUE TITLE
[python] : update instructions for steps that raise exceptions

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#54647]
The following steps need to be updated to explain why the code raises an exception. The description should be adjusted depending on the situation.

### Learn String Manipulation by Building a Cipher #54724 
- [x] step 23
- [x] step 25
- [x] step 32
- [x] step 46
- [x] step 53
- [x] step 54

### Learn How to Work with Numbers and Strings by Implementing the Luhn Algorithm #54753 
- [x] step 20
### Learn Regular Expressions by Building a Password Generator #54804
- [x] step 54 (the test need to be changed to require `pass`)
### Learn Tree Traversal by Building a Binary Search Tree #54789 
- [x] step 30
### Learn Classes and Objects by Building a Sudoku Solver
No steps found
### Bisection method
No steps found
### Learn Data Structures by Building the Merge Sort Algorithm
No steps found
### Learn Recursion by Solving the Tower of Hanoi Puzzle
No steps found
### Learn Lambda Functions by Building an Expense Tracker
No steps found

> **TODO:**

### Learn Python List Comprehension by Building a Case Converter Program
Should review after changes to project in #54051
### Learn Algorithm Design by Building a Shortest Path Algorithm
No step found.

**Comment by ilenia-magoni** [comment]
I have created a PR for the cipher project.

**Comment by zairahira** [comment]
I'll go through the Binary Search Tree, The Bisection method and the Sudoku Solver next week.

**Comment by ilenia-magoni** [comment]
I'm going to work on the Luhn algorithm project

**Comment by zairahira** [comment]
Working on Merge sort and Tower of Hanoi next.
