### ISSUE TITLE
Waypoint: Style Multiple Elements with a CSS Class: has a typo

### ISSUE THREAD

**Issue by smsrkr** [FreeCodeCamp/FreeCodeCamp#5464]
Challenge [Waypoint: Style Multiple Elements with a CSS Class](http://www.freecodecamp.com/challenges/waypoint-style-multiple-elements-with-a-css-class) has an issue.

The instructions text says this
>But also remember that class declarations don't use a period, like this:
>````
><h2 class="blue-text">CatPhotoApp<h2>
>````
>Apply the red-text class to your h2 and p elements.

The closing </h2> tag doesn't have the slash.

**Comment by michaelaharvey** [comment]
I fixed and submitted a pull request here: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5465

**Comment by gasperno** [comment]
@michaelaharvey Please mention "closes #<Issue Number>" by editing your pull request description. That ensures github to automatically close your issue after merging your PR.
