### ISSUE TITLE
RD Certification - Learn Advanced Bash by Building a Kitty Ipsum Translator - Bugs/Typos I have found

### ISSUE THREAD

**Issue by andrebdinis** [freeCodeCamp/freeCodeCamp#54645]
### Describe the Issue

Hello!

I will detail **5 issues** I have found, by stating the **text of the step** (I did not know how to find the number of the steps, and I have reached my GitPod monthly usage limit) and the **issue in question**.

### **1. STEP:** “cat can take a filename as an argument. Use it again with your name.txt file as an arguement to print the contents of the file.”
- TYPO: **arguement** instead of **argument**.

### **2. STEP:** “It doesn’t look like that’s an option. But there is a -o flag that will says it will put the matches on their own lines. Try that one with that command instead of the -c flag.”
- TYPO: **that will says it will** instead of **that says it will**.

### **3. STEP:** “You can use sed to change each line number in that output. Start by entering the last command and pipe the output into sed that replaces [0-9] with 1.”
- UNWANTED BEHAVIOR: The code passes even when I type the regex pattern without the ‘s’ at the “sed” command (which results in an error):
```shell
grep -n 'meow[a-z]*' kitty_ipsum_1.txt | sed '/[0-9]/1/'
sed: -e expression #1, char 8: unknown command: 1’`
``` 
- SOLUTION: The only acceptable code should be:
```shell
grep -n 'meow[a-z]*' kitty_ipsum_1.txt | sed 's/[0-9]/1/'
``` 

### **4. STEP:** “Now, it should replace catnip with dogchow and cat with dog. Use the script the translate the first ipsum file again. Search the results with grep for any words that start with dog. Part of that search pattern should be [a-z]*. Make sure to show the results in color.”
- TYPO: **Use the script the translate the first** instead of **Use the script to translate the first**.

### **5. STEP:** “Okay, your script is finished. Translate the kitty_ipsum_1.txt file and put the output into a new doggy_ipsum_1.txt file.”
- PROBLEM: it does not accept as a solution the command with the input redirection (but it should work as well, right?): 
```shell
./translate.sh < kitty_ipsum_1.txt > doggy_ipsum_1.txt
``` 

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-advanced-bash-by-building-a-kitty-ipsum-translator/build-a-kitty-ipsum-translator

### Your code

Already mentioned in the issue description.

### Expected behavior

Already mentioned in the issue description.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Brave
- Version: 1.65.123

**Comment by jdwilkin4** [comment]
Hey @moT01 ! 

Would you have time to look into this issue?
Thanks!

**Comment by andrebdinis** [comment]
Thank you, @moT01. I hope the information was clear enough.
