### ISSUE TITLE
The test passes even though the syntax is not correct | Cat Photo App step-8

### ISSUE THREAD

**Issue by zxc-w** [freeCodeCamp/freeCodeCamp#54642]
### Describe the Issue

the challenge is to add `src` attribute to `<img>` element.

you will pass with this solution:
```HTML
<img src = "https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg"
```

which is missing the closing angel bracket `>`.

tried it from a camper topic at the forum here: [Forum](https://forum.freecodecamp.org/t/learn-html-by-building-a-cat-photo-app-step-8/688447)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-8

### Your code

```HTML
<img src="https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg"
```

**This should not pass**

### Expected behavior

A hint message appears, preventing the camper from passing.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Endekalu-Zemenu** [comment]
May I fix issue #54642?
