### ISSUE TITLE
Landing page redesign

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#54656]
### Is your feature request related to a problem? Please describe.

We are planning to redesign our landing page to increase the number of sign ups (conversion rate). 
Feel free to share your suggestions, wire-frames, and designs. 
The designs should generally follow our command-line-chic aesthetics.
I will be doing some research on conversion rate optimization for landing pages and share my findings here.
Finally, we will AB test multiple variations and merge the winning design. 

ref #50611
ref #https://github.com/freeCodeCamp/freeCodeCamp/issues/54656

**Comment by SilverJinx** [comment]
@ahmaxed I'd be happy to pick this up. I noticed you mentioned the need for 'growthbook'  in the referenced issue. Are we still waiting on that or am I free to get going? 😉

**Comment by ahmaxed** [comment]
Here is the redesign for the top of the landing page. 
The growthbook is configured and the section with the gradient background is currently being AB tested.

<img width="791" alt="Screenshot 2024-09-13 at 12 51 40 PM" src="https://github.com/user-attachments/assets/6bc60ee1-8544-4a5a-a25a-0b998a87e2b3">

**Comment by codewithtyler** [comment]
This is looking good but that cards section just looks a bit odd with everything left aligned. Not sure I have suggestions how to make it look better just throwing in my 2 cents on the look of this page so far.

**Comment by iamabhiCH** [comment]
i am looking into this enhancement, could you please assign this to me @codewithtyler

**Comment by ilenia-magoni** [comment]
@iamabhiCH this issue is not open for contribution, only issues with the help wanted label are open for contribution

**Comment by ojeytonwilliams** [comment]
Hey @ahmaxed this is still in the works, right?

**Comment by ahmaxed** [comment]
This can be closed while I run AB tests in the background.
