### ISSUE TITLE
Error on build-curriculum

### ISSUE THREAD

**Issue by DelphiCoder** [freeCodeCamp/freeCodeCamp#54658]
** About The Error **

`$ npm run develop` appears to run correctly until it tries to build the curriculum.  Then it generates the following error:

```
> @freecodecamp/curriculum@0.0.0-next.4 build D:\fcc\curriculum
> ts-node --project ../tsconfig.json ../tools/scripts/build/build-curriculum  

D:\fcc\node_modules\ts-node\dist\index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\fcc\node_modules\remark-directive\index.js from D:\fcc\tools\challenge-parser\parser\index.js not supported.
Instead change the require of D:\fcc\node_modules\remark-directive\index.js in D:\fcc\tools\challenge-parser\parser\index.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (D:\fcc\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (D:\fcc\tools\challenge-parser\parser\index.js:2:19)
    at m._compile (D:\fcc\node_modules\ts-node\dist\index.js:857:29) {        
  code: 'ERR_REQUIRE_ESM'
}
 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
ERROR: "build:curriculum" exited with 1.
```

I thought that I might need to add JavaScript's ESM module support, so I edited the `package.json` file to add the 
```
"type": "module",
```
line, but the same error still occurs.

** Desktop Specifics: **
Node Version is v20.12.2
NPM Version is 10.7.0
OS is Windows 11 Pro
Memory is 64.0 GB
Processor is Intel i7-11700 @ 2.50GHz
Installation is on D:\fcc\

** Steps Taken to Reproduce Error: **
1. I installed from `https://github.com/freeCodeCamp/freeCodeCamp` into `D:\fcc`
2. Copied the "sample.env" file to ".env" only.
3. Ran `npm i`
4. Ran `npm ci`
5. Ran `npm run seed` but got missing `mongodb` module error.
6. I have MongoDB installed and I am using it on several projects. So I ran `npm i mongodb`
7. Then again ran `npm run seed` to get module not found on `joi-objectid`, so I ran `npm i joi-objectid`
8. Then again I ran `npm run seed` and the reply was that it was successfully seeded.
9. I checked the seeding inside the MongoDB Compass App and I can see that `freecodecamp` documents are there.
   I can see "Exam", "Survey", and "user" documents are seeded. If there are supposed to be more, I don't see any at the moment.
10. Ran `npm run develop` and this is where I encountered the error I mentioned already.
11. Added the `"type": "module",` to the `package.json` file but the cannot build curriculum error persists.

** What To Do Next **

I'm at a loss here.  Can anyone give me an insight other than install it on Linux?  Anyone have this running on Windows 11 Pro?

Thank you

**Comment by gikf** [comment]
Hey,

development on native Windows is not currently supported. You may use WSL - https://contribute.freecodecamp.org/#/how-to-setup-wsl. Other details how to set up development can be found at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally - you will need also `pnpm` instead of `npm`.

**Comment by DelphiCoder** [comment]
Thank you for your feedback.

I will look into the WSL route as I'm already familiar with that.
