### ISSUE TITLE
Leaderboard and Interactive quizzes

### ISSUE THREAD

**Issue by Dopplenum** [freeCodeCamp/freeCodeCamp#54659]
### Is your feature request related to a problem? Please describe.

The leaderboard ensures that there is competitive nature 

### Describe the solution you'd like

JUst make interactive leaderboard and add quizzes

### Describe alternatives you've considered

Just make leaderboard for the students

**Comment by naomi-lgbt** [comment]
Thanks for sharing your feedback. We specifically avoid excessive gamification in our platform as it encourages rushing through material instead of taking the time to learn the information correctly.
