### ISSUE TITLE
Improve Waypoint: Override Styles in Subsequent CSS

### ISSUE THREAD

**Issue by wakqasahmed** [FreeCodeCamp/FreeCodeCamp#5466]
If the below line says

```class="class1 class2" or class="class2 class1"```

instead of

```class="class1 class2"```

it will provide more clarity that it is not the order of multiple classes you introduce that affects but how they are ordered in css.

Can i go ahead and start doing my first contribution?

**Comment by ltegman** [comment]
Rather than showing both examples I'd prefer a note afterwards acknowledging that the order classes are listed in does not matter. And you're free to open a PR if you would like :smile:
