### ISSUE TITLE
The check is made to add border radius property not on which CSS style it is added on 

### ISSUE THREAD

**Issue by daksh844** [FreeCodeCamp/FreeCodeCamp#5467]
Challenge [Waypoint: Add Rounded Corners with a Border Radius](http://www.freecodecamp.com/challenges/waypoint-add-rounded-corners-with-a-border-radius) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }

  .smaller-image {
    width: 100px;
    border-radius:10px;
    
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment]
I prefer the result oriented tests like we have now, but I'm open to a PR that adds a regex test to ensure it's in the correct CSS rule.

**Comment by LatashaH** [comment]
Hi. This thing is Not working for me and it holding me back. I have correct code and it will not run correctly on a chrome browser on android. Two people looked at it and said it worked. I dont want to put a bug report on something that works. But its sorta crazy. Thanks for your time.

**Comment by SaintPeter** [comment]
@LatashaH If you want to share your code we can take a look, but we have not been getting reports like this since we pushed the fix out.

**Comment by sludge256** [comment]
@SaintPeter 
The issue was "resolved" in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6823
