### ISSUE TITLE
Remove '>>>' from Python editor

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#54685]
The three angular brackets are present in the Python editor terminal
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/26656284/5dd907ab-8883-440e-a027-5a132b199d5b)

As such printing anything will indent the first line, and only the first line, by those characters.
This makes it difficult to see outputs that require precise formatting, like the output of final project Arithmetic Formatter.

**Comment by deeseeker** [comment]
can you assign this task to me?
