### ISSUE TITLE
add more tests to rosetta code Tokenize a string with escaping

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#54687]
https://github.com/freeCodeCamp/freeCodeCamp/blob/dea35985c1490728a5a4dd5032ee22bae34b6ddd/curriculum/challenges/english/22-rosetta-code/rosetta-code-challenges/tokenize-a-string-with-escaping.md#L83

**Comment by juancaorg** [comment]
Hey @ilenia-magoni, any more context on this issue? Seems pretty empty to be already opened with the `help wanted` label.

**Comment by ilenia-magoni** [comment]
@juancaorg the challenge needs more tests
