### ISSUE TITLE
Logic behind returning this specific string ?

### ISSUE THREAD

**Issue by anirban93** [FreeCodeCamp/FreeCodeCamp#5468]
It said for third string:
truncate("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length) should return "A-tisket a-tasket A green and yellow basket".

But why ? the str.length is 43 which is way greater than 3.  shouldn't it omit las 3 characters and add "..." ?

**Comment by anirban93** [comment]
So.. there is something going on back end ? The third string was something else like "peter piper.." ?
I don't know why this is messed up but when i've tricked with a else if, console shows different string.
![free_code](https://cloud.githubusercontent.com/assets/5820924/12010425/89dea092-acd0-11e5-8e9e-5811df32057e.png)

**Comment by ltegman** [comment]
There is nothing wrong with this challenge. It is asking you to truncate the string and add ellipsis only when the length parameter is less than the length of the string passed in, and in `truncate("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length)` the length is equal so the string should not be truncated.

If you need further assistance please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help)

Thanks and happy coding!
