### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue 

### ISSUE THREAD

**Issue by appijumbo** [FreeCodeCamp/freecodecamp#547]
This code gets passed o.k.
<p><a href='http://www.catphotoapp.com'>see my cat photos</a></p>

but I believe it should be
<p>click here for <a href='http://www.catphotoapp.com'>cat photos</a></p>

**Comment by denmch** [comment]
@appijumbo You want to be sure to wrap your code in back ticks (check out [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) and scroll down to Syntax Highlighting to see how it works). Without marking that as code, it renders as html. I was only able to read your code because the bot posted it to the Slack chat in plain text.

**Comment by appijumbo** [comment]
oops thanks! will do

**Comment by denmch** [comment]
Both examples are equally valid, but the first is actually preferable (as far as Google is concerned). Longer hyperlinked phrases give Google more context for links and without looking spammy. They actually have a small affect on search rankings, if you're into SEO, and "click here" is kind of a holdover from the early days of the web, when people needed sites to tell them explicitly where to click. People have a more intuitive sense of how web interfaces work, and "click here" has gone by the wayside.

**Comment by appijumbo** [comment]
o.k, that seems reasonable. 
Saying 'click here' is a bit like saying 'push to open' on a door, rather than just 'push' I guess!

**Comment by BerkeleyTrue** [comment]
@appijumbo Does that fix your issue?

**Comment by appijumbo** [comment]
Yes thanks ;)

**Comment by BerkeleyTrue** [comment]
Thanks for filing! Good luck with the rest of the challenges!
