### ISSUE TITLE
Frontend code tests

### ISSUE THREAD

**Issue by yjcxy12** [FreeCodeCamp/FreeCodeCamp#5470]
After the [PR#5181](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5181), I tried to write some tests to test console output. Which should make QA process easier.

Although I found with current frontend code structure, it is not easy to write unit tests. The functions are put in with window.common object, in order to test specific function, global dependencies are needed.

Any thoughts or suggestions on this?

**Comment by bugron** [comment]
Closing this issue as stale. @yjcxy12 thanks for posting. Not sure if we'll be do something in near future because if I understand correctly this requires some kind of refactoring and/or changing `commonFramework` structure.

**Comment by ghostsleeper7** [comment]
I'm trying to.read a code could you please help as I don't know how to commit or access tools I'm on cell phone
