### ISSUE TITLE
Use a darker color for the fCC logo in the donation animation

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#54700]
## Description

I'm wondering if we should change the fCC logo to `#0a0a23` in the donation animation:

<img width="256" alt="Screenshot 2024-05-08 at 14 39 53" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/7f354e64-e6a7-46d8-9d5d-e73de64f7fe2">

<img width="419" alt="Screenshot 2024-05-08 at 14 41 07" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/59e708ce-6178-4d98-8eec-0c660cd0eb01">

That gives a better contrast against the orange/yellow background, and makes the logo stands out more.

Alternatively, we could keep the logo color as-is, but change the background to `#0a0a23`, which would match our branding.

**Comment by a2937** [comment]
The white on black does fit really well and is our most recognized color combination. https://design-style-guide.freecodecamp.org/

**Comment by a2937** [comment]
<img width="419" alt="updated-patch" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/f681cdbc-5a8b-4bd7-81d0-c95362aa678e">

<img width="256" alt="update-patch-fly" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/919e4530-1040-4304-a86e-0c2b8e7151ce">


These samples seem pretty improved with our proper logos present.

**Comment by naomi-lgbt** [comment]
IMHO we should not remove the gold. That has become our "supporter" colour:

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/cada7a62-4891-4974-8a73-839e936cda00)
