### ISSUE TITLE
what is wrong 

### ISSUE THREAD

**Issue by shiechihchien** [FreeCodeCamp/FreeCodeCamp#5471]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%3Ch2%20class%3D%22red-text%22%3E%20CatPhotoApp%20%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h2 class="red-text"> CatPhotoApp </h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance.

Thanks and happy coding!
