### ISSUE TITLE
Alignment Issue: Elements Misaligned on Homepage

### ISSUE THREAD

**Issue by alokranjan609** [freeCodeCamp/freeCodeCamp#54726]
### Describe the Issue

![Screenshot 2024-05-09 184030](https://github.com/freeCodeCamp/freeCodeCamp/assets/108021303/e392814d-4f3e-41ee-a047-6fb946992da6)
Frequently asked question segment is not aligned with the previous elements on the homepage

### Affected Page

https://www.freecodecamp.org/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/
2. Scroll down to frequently asked questions
4. See the misalignment of frequently asked questions segment with the previous elements

### Expected behavior

The frequently asked question segment should be aligned with the previous elements of the homepage for a better UI

### Screenshots

![Screenshot 2024-05-09 184030](https://github.com/freeCodeCamp/freeCodeCamp/assets/108021303/8e77d81f-57f0-4097-88ac-ddd60d2f1bde)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Brave
- Version: 1.64.122

**Comment by ahmaxed** [comment]
Yes, we can standardize all of them. My changes are effecting the landing top section.
