### ISSUE TITLE
Surface code syntax errors to UI

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#54734]
### Is your feature request related to a problem? Please describe.

We frequently get forum posts about the submit button not working. It is almost always because the code written has syntax errors preventing the code and tests from running.

### Describe the solution you'd like

It would be nice if after the first click/submit the button would change to an error state if the code had syntax errors.

Not really sure how to best surface thrown syntax errors, or when to update/re-update the button state. Maybe on button click, it changes to an error state and on any code update it changes back to the default state until clicked again (where it will stay at the default state or change back to an error state again).

And yes, I realize the error is in the console. But it would be nice to surface it to the UI.

![Syntax error](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/370d2750-8d6e-4690-b1ae-d4ac14187e3a)

### Describe alternatives you've considered

It could be surfaced to some other UI element.

### Additional context

As an aside, I'm not sure how we signal code errors to visually impaired users right now. But this change might also count as an accessibility help if the button was updated to signal errors to screen readers.

**Comment by ilenia-magoni** [comment]
Now I wonder how accessible is the python terminal... now syntax errors are in the terminal for python, but the terminal updates for every character written in the code window.

**Comment by hbar1st** [comment]
I’ve seen a design where a red border can be added around the console frame to indicate visually that something is wrong so just wanted to mention it in case it is more desirable than modifying the submit button.
