### ISSUE TITLE
Learn Introductory JavaScript by Building a Pyramid Generator - Step 20 - instructions refer to `rows[2]` instead of `rows[rows.length - 1]`

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#54741]
### Describe the Issue

in step 20 of the JS building a pyramid generator project, the step refers to the " rows[2] assignment" but should instead refer to the "rows[rows.length - 1]" assignment as that is the line in the code at that moment (not the "rows[2]" line.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-20

### Your code

```
console.log(rows[0]);
rows[rows.length - 1] = 10;
```

### Expected behavior

As the step begins with the code as given above, the instructions shouldn't say "rows[2]" to refer to the line "rows[rows.length - 1]"
(therefore a small correction to the correct line of code is needed)

### Screenshots

![js-step-20](https://github.com/freeCodeCamp/freeCodeCamp/assets/35541470/6f2881fb-8141-4618-9117-9db3304fd1af)

### System

- Device: laptop
- OS: windows
- Browser: chrome
- Version:

**Comment by gikf** [comment]
Second test also will need to be changed accordingly.
