### ISSUE TITLE
Bonfires made inaccessible by infinite recursion

### ISSUE THREAD

**Issue by jamesbrown0** [FreeCodeCamp/FreeCodeCamp#5476]
I've made two bonfires inaccessible by writing recursive functions and running tests. The page crashes on load so I can't edit the code.

**Comment by ltegman** [comment]
You can either [disable code auto-run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) or [clear the code from local storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage) to unfreeze your page.

Thanks and happy coding!
