### ISSUE TITLE
Rename currentWeapon variable to currentWeaponIndex

### ISSUE THREAD

**Issue by ElectricCowBoy123** [freeCodeCamp/freeCodeCamp#54777]
### Describe the Issue

The `currentWeapon` variable could be better called `currentWeaponIndex` reflecting that it is a variable that is to be used to index the array `weapons`

# Proposal
Rename all instances of `currentWeapon` to `currentWeaponIndex` to make it clearer in the examples

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/

### Your code

```

N/A

```

### Expected behavior

N/A

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
> Rename all instances of currentWeapon to currentWeaponIndex

I like the new name change but it shouldn't be all instances.
It should be most instances.

The only time it shouldn't change is when `currentWeapon` is declared in this new scope here

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-105

So `currentWeapon` makes sense there

**Comment by ElectricCowBoy123** [comment]
> The only time it shouldn't change is when `currentWeapon` is declared in this new scope here
> 
> https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-105
> 
> So `currentWeapon` makes sense there

Ah, yes indeed missed that one, I agree!
