### ISSUE TITLE
Feedback on teaching for loops steps in JS Beta Build a Pyramid Project

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#54770]
### Describe the Issue

I noticed that the beta JS course attempts to teach for loop syntax before introducing conditional statements. Wouldn’t it make it easier to understand loops by first teaching conditional logic and its uses in code? I find the current order to be off-putting even from my perspective as a has-been soft. dev, so I imagine newbies would too. Has this order found success so far?

I would also add that I have never come across a programming course or book that introduces loops ahead of conditionals. 

My other thought is when teaching loops, we should really start with the simplest loop type available, which to me is a while loop, but I understand if there are other schools of thought on this.

first attempt to discuss this on the forum here: 
https://forum.freecodecamp.org/t/question-about-about-pyramid-project-and-general-thoughts-on-new-js-curriculum/690061/27

I would also suggest that the project can 'meander' a bit more in order to teach the concepts better by going through a series of learning exercises like the following (all within the same project):

1- learn how to make a pyramid manually by printing out 1, then 2 then 3 hashes for example to form a 3+ row pyramid.
(brute force method of creating a pyramid is a classic and should be introduced so learners can gain an appreciation for loops later)

2- learn if statements and booleans in general

3- learn while loops and make a pyramid of #s with a while loop (perhaps it would be a flat pyramid on 2 sides versus a centered one here)

4- modify the while loop to print the pyramid with alternate characters depending on whether the row is even or odd (for eg use `#` if even and `$` if odd)

5- learn for loops and create the pyramid again more efficiently

ps. I would also argue that step 28 starting sentence of "To generate a pyramid, you will need to create multiple rows.." makes a, rather large, assumption that the reader knows what the heck a generated pyramid is at this point. These learners may have no clue about what is meant here as it wasn't shown to them in any context prior? (at least within the confines of this course)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-28

### Your code

N/A

### Expected behavior

An idealized centered version of a pyramid can be built in this project but should -not- be built till we have learned how to make a left-handed pyramid first like this:
```
#
##
###
####
```

and a multiple-symbol pyramid like this:
```
####
$$$
##
$
```

among other variations and using multiple methods so as to learn problem solving with conditionals and loops in bite-sized pieces with clear progressions for newbies with no prior coding experience.

### System

N/A

**Comment by hbar1st** [comment]
In my initial comment I said: "ps. I would also argue that step 28 starting sentence of "To generate a pyramid, you will need to create multiple rows.." makes a, rather large, assumption that the reader knows what the heck a generated pyramid is at this point. These learners may have no clue about what is meant here as it wasn't shown to them in any context prior? (at least within the confines of this course)" 
I will be creating a separate issue for this as Quincy has agreed that it is something that can be addressed. (see forum post: https://forum.freecodecamp.org/t/way-of-learning/689345/4 ) 

Remaining concerns about value of teaching for loops before conditionals are taught are hopefully to be addressed here.

**Comment by hbar1st** [comment]
just because this has been on my mind today, has anyone also ever considered that trying to teach so many fundamental concepts of JS in one project may be asking for too much? That is may be better to create a simple project for eg to teach the idea of variables only, another project for conditionals and loops, another for functions etc? Perhaps if each project focused on a fundamental part of the JS language, the students can gain more from their interaction with each project and have a much better understanding of what they're doing and --why-- as they move forward in the projects. Almost like chapters of a book but with each project emphasizing one building block in the language. Maybe even a super simple project just to teach things like tabbing and commenting and logging could be included in there somewhere.

**Comment by naomi-lgbt** [comment]
This is a big one, so let's break it down a bit.

> trying to teach so many fundamental concepts of JS in one project may be asking for too much?

No different than teaching so many fundamental concepts in one Basic JS section. This is really meant to be a surface level explanation of what campers will need to start going through the rest of the projects.

> My other thought is when teaching loops, we should really start with the simplest loop type available, which to me is a while loop, but I understand if there are other schools of thought on this.

Sure, that's the order we used in the Basic JS section, so we can switch it here.

> I would also suggest that the project can 'meander' a bit more in order to teach the concepts better by going through a series of learning exercises

Agreed. We have a lot of freedom with this project specifically to play around with different approaches and ordering.

> I would also argue that step 28 starting sentence of "To generate a pyramid, you will need to create multiple rows.." makes a, rather large, assumption that the reader knows what the heck a generated pyramid is at this point. These learners may have no clue about what is meant here as it wasn't shown to them in any context prior? (at least within the confines of this course)

I'd argue this has been resolved by the proper addition of the preview modal.

---

Regardless of where we land on this, I do think we'll need to approach this across multiple PRs.

**Comment by hbar1st** [comment]
Yes the last point has been addressed. So we need to look more closely at some of the pain points like for loops and trying harder to explain the why of something before the how. For for loops that is easily done by making someone try to do a series of repetitions, then replacing those repetitions with a for or a while. I also wish that we could explain variables better. 

I agree that multiple issues are raised and may require multiple PRs

**Comment by naomi-lgbt** [comment]
Let's also pull in the feedback I dropped in a [separate issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/55319).

> My gf is going through the JS curriculum, and the first review project immediately starts off with constructing a loop to iterate through an array.
> 
> The introductory project teaches a LOT of loops, but only touches on array indices in a couple of steps. We may want to expand those steps - perhaps something like adding another loop instruction to loop through an array?

> Should also probably ~~teach~~ reinforce that arrays are 0 indexed.

**Comment by jdwilkin4** [comment]
Since the new cert will be launched soon, I am going to close this.

You can find the press release for this cert here 

https://www.freecodecamp.org/news/freecodecamp-turns-10-major-curriculum-updates/

But as to the issue at hand, here is how the new cert will handle intro JS topics.

The JS portion will start off with several modules specifically scoped to certain concepts. 

The first module just focuses on variables and strings.
Then the second one focuses on booleans, conditionals and numbers.
Then we have functions. 
etc.

here is a video showing a preview of the type of content in the new cert
https://www.youtube.com/watch?v=1fZ0hTX-ut4

As for the pyramid project, that has been moved down to the review JS fundamentals module in the cert and has been restructured as a lab. Labs are projects with a blank code editor and user stories. So you can see that in the video.
