### ISSUE TITLE
Unwanted update of my excercises!

### ISSUE THREAD

**Issue by acanicoba** [FreeCodeCamp/FreeCodeCamp#5479]
Hello I find that if you go to other camper's excercise to check how they resolved them, it update yours!! 

I finished a Bonfire and after i wanted to check how other did and i lost my program, I had to start it over again...!

**Comment by ltegman** [comment]
The code stored in local storage is simply the code you most recently had in the editor for that challenge. There is no way to differentiate between your code and that of someone else. Your solution will still always be saved as it was at the time of your submission and accessible from your profile.

Thanks and happy coding!
