### ISSUE TITLE
Teach unreachable code and scope in separate lessons for pyramid project

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#54809]
### Describe the Issue

on starting step 51 of the JS Beta project to build a pyramid generator, I noticed that we're being asked to add a variable declaration and that the editor has an empty line within the padRow function but -after- the return statement. As these blank lines are meant to be suggestive to learners (nudging them as to where to type), this empty line after the return seemed to be badly placed as it shouldn't suggest that placing code after a return statement is acceptable (or that it could work with the console log in the local scope for eg which also would not work in this case)
Suggest to place the empty line within the function above the return statement instead.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-51

### Your code

N/A

### Expected behavior

empty line within padRow function should be placed above the return statement (not below it)

### System

N/A

**Comment by hbar1st** [comment]
ugh, I just saw step 52. I don't understand why step 51 would suggest that a person should create a new variable after the return only to point it out as wrong in the next step. step 51 should show us that a 'correct' declaration of the variable in a local scope will result in a ref. error when the variable is referenced beyond that scope.

As for teaching people not to put code after the return, that should be a -separate- and -unrelated- step in this case.

**Comment by lasjorg** [comment]
I agree, it seems like an odd choice.

Unreachable code and variable scope should be taught separately.

**Comment by jdwilkin4** [comment]
@naomi-lgbt or @Ksound22 ?

Are either of you free to make these updates?

I don't want to open a PR right before I go on vacation. 

Thanks 👍

**Comment by Ksound22** [comment]
> @naomi-lgbt or @Ksound22 ?
> 
> Are either of you free to make these updates?
> 
> I don't want to open a PR right before I go on vacation.
> 
> Thanks 👍

Can we open it up for suggestions?

**Comment by naomi-lgbt** [comment]
I'd prefer to see the instructions updated to specify putting the variable after the return - I think it's valuable information to teach.

**Comment by lasjorg** [comment]
This is the first time campers will be taught about variable scope. They may have coded for less than half a day.

Adding unreachable code as part of teaching variable scope can muddy the water for the learner, where they may end up making a correlation between the two that doesn't exist.

I would suggest we split it up into separate steps that focus on each topic.

**Comment by naomi-lgbt** [comment]
I could work with that, yes
