### ISSUE TITLE
Typo in Step 43 of Building a Cipher

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#54837]
### Describe the Issue

```diff
--- This clause can be added to the end of an `if` statement to execute alternative code if the condition is of the `if` statement is false
+++ This clause can be added to the end of an `if` statement to execute alternative code if the condition of the `if` statement is false
```

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-43

### Expected behavior

Update the following file with the suggested change above:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/6553995f412dd8122ed38e4a.md

**Comment by Jaiharishan** [comment]
Can I work on this

**Comment by Jaiharishan** [comment]
Fixed this typo. Have attached the PR here.
#54840
