### ISSUE TITLE
Waypoint: Escape Sequences in Strings[beta] space before word

### ISSUE THREAD

**Issue by qmikew1** [FreeCodeCamp/FreeCodeCamp#5485]
Quotes are not the only characters that can be escaped inside a string. Here is a table of common escape sequences: <--displays correctly in plain text; however, red/italics markdown on word 'escaped' merges into next word: inside. (i.e., escapedinside)

**Comment by abhisekp** [comment]
@qmikew1 Since the *`escaped`* is in italics, it looks close to the first letter of next word but I think it's not an issue.

**Comment by jbmartinez** [comment]
It looks fine on my screen, perhaps it can be even better adding `&nbsp;` after *escaped*

**Comment by SaintPeter** [comment]
This looks correct to me:
![image](https://cloud.githubusercontent.com/assets/553494/12023241/6c537ecc-ad4c-11e5-9956-7bd0af74b213.png)
