### ISSUE TITLE
No link to go back to homepage

### ISSUE THREAD

**Issue by JLH13** [freeCodeCamp/freeCodeCamp#54867]
### Describe the Issue

After I was on freeCodeCamp for a while, there was something I wanted to check on the homepage, which is: https://www.freecodecamp.org, and I noticed that there was no way to get back to that page. The “freeCodeCamp” graphic link at the top takes you to https://www.freecodecamp.org/learn. There are also no links at the upper right menu or on the bottom of the web page that will take you to https://www.freecodecamp.org. What I had to do was hit the back arrow many times until it took me back to https://www.freecodecamp.org. I would suggest that the “freeCodeCamp” graphic link at the top of the page take you to https://www.freecodecamp.org and not https://www.freecodecamp.org/learn, since there is already a link to that in the upper right menu.

### Affected Page

https://www.freecodecamp.org

### Steps to Reproduce

1. Go to https://www.freecodecamp.org
2. Click on any of the links that take you to a different page.
3. Try to get back to https://www.freecodecamp.org without using the back arrow.

### Expected behavior

There should be a link that takes the user back to https://www.freecodecamp.org when they are not on that page.

### System

- Device: 2020 Apple MacBook Air M1
- OS: Sonoma 14.0
- Browser: Safari
- Version: 17.0

**Comment by VP-66** [comment]
Hi there! I have also experienced this same situation and thought of the same improvement - it makes logical sense for the title graphic to re-direct to "https://www.freecodecamp.org/" as compared to "https://www.freecodecamp.org/learn". 

If the owners are happy with change, I can help to work on it :)

**Comment by raisedadead** [comment]
Thank you for reporting this, but this behavior is a conscious design choice. Our analytics tell us that people prefer using the learn map more than the landing page – which is optimized for first time visitors.

You are able to type in the URL: `www.freecodecamp.org` in your address bar to land on the homepage should you be "interested" in seeing the landing page.

We appreciate your feedback, happy coding.
