### ISSUE TITLE
Update step 18, 28, 38 hints for calorie counter project

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#54868]
### Describe the Issue

The instructions in step 18 of the js beta to build a calorie counter says:

Start by declaring a cleanInputString function that takes a str parameter.

However if you misspell the function's name you receive this hint:

You should declare a cleanInputString variable.

I believe this message should be changed to say "function" instead of "variable"

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-18

### Your code

```

function cleanInputStrin(str) {}

```

### Expected behavior

the hint should refer to a `function` not a `variable`

### System

N/A

**Comment by hbar1st** [comment]
Similar issue was seen in step 28 where the hint said: 
You should declare an isInvalidInput variable.

while the instructions were again to create a function:
Start by creating a function called isInvalidInput – it should take a single str parameter.

**Comment by Supravisor** [comment]
From Pyramid Generator
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-42
>A function is a block of code that can be reused throughout your application. Functions are declared with the following syntax:
>```
>function name(parameter) {
>
>}
>```
>The function keyword tells JavaScript that the name variable is going to be a function. parameter is a variable that represents a value that is passed into the function when it is used. A function may have as many, or as few, parameters as you'd like. Like a for loop, the space between the curly braces is the function body.
>

Here, Campers are introduced to the idea of functions as JavaScript code for a variable.

**Comment by hbar1st** [comment]
Step 42 mentioned in the previous comment should be fixed. It should say: “The function keyword tells JavaScript that the name keyword is going to be a function.”
(Replacing ‘variable’ with ‘keyword’)

My understanding is that a function is actually an object in js but I would be surprised if a js course starts telling learners to “declare an object called myFunction” instead of saying “declare a function called myFunction”.

**Comment by jdwilkin4** [comment]
@hbar1st @Supravisor 

Step 42 should be a separate issue IMO.
It shouldn't be lumped in with the corrections being made to the calorie counter steps
