### ISSUE TITLE
Waypoint: Replacing IfElse chains with Switch [beta] possible spacing of title

### ISSUE THREAD

**Issue by qmikew1** [FreeCodeCamp/FreeCodeCamp#5489]
Waypoint: Replacing IfElse chains with Switch

Should this be:

Waypoint: Replacing If Else chains with Switch

(unknown if intentional )

**Comment by abhisekp** [comment]
@qmikew1 That is because the Title is attached to what it shows in the "URL". So it automatically removes any invalid URI character.
In the map, it shows "If/Else" but in the instruction it shows IfElse (without the `/`).

@SaintPeter this is more of a bug in the architecture (i guess).

**Comment by SaintPeter** [comment]
Confirmed.  I'll change all of the titles so they have a space in them, but all others will have the slash.
