### ISSUE TITLE
Challenge url

### ISSUE THREAD

**Issue by ekojsalim** [FreeCodeCamp/freecodecamp#549]
Broken url on 'view my solution' in the profile page. It leads to 'http//'

Analysis:
```
a(href="http://" + challenge.solution, target='_blank')
```
Eg:

`http://http://codepen.io/AdventureBear/pen/vEoVMw`
evaluates to
`http//codepen.io/AdventureBear/pen/vEoVMw`

**Comment by BerkeleyTrue** [comment]
Hello @ekojsalim Thanks for reporting this issue. I am looking into it.

**Comment by QuincyLarson** [comment]
This is basically fixed now, but we could improve the Angular validation in the future.
