### ISSUE TITLE
Waypoint: Concatenating Strings with Plus Operator [Beta] grammar

### ISSUE THREAD

**Issue by HermanFassett** [FreeCodeCamp/FreeCodeCamp#5490]
>In JavaScript, the + operator when used with a String value, it is called concatenation operator.

Grammatically speaking this should probably read something more like

>In JavaScript, the + operator when used with a String value is called the concatenation operator.

**Comment by CaroleAnneHannon** [comment]
Adding another one to this:

The first test says
myStr should have a value of This is the start. This is the end

but it only accepts a value of This is the start. This is the end.

so I think it's missing a period in the test directions

Also it shows undefined in the viewer

**Comment by abhisekp** [comment]
@HermanFassett I think the earlier statement 
> "In JavaScript, the + operator when used with a String value, it is called concatenation operator."

is better to understand.

**Comment by HermanFassett** [comment]
@abhisekp but it is incorrect English.

**Comment by SaintPeter** [comment]
Updated:
![image](https://cloud.githubusercontent.com/assets/553494/12023613/03c291aa-ad50-11e5-87c5-9464aedf5e75.png)
