### ISSUE TITLE
Combine step 21 -22 and steps 41 - 42 for cat painting project

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#54912]
### Describe the Issue

Steps 21 and 22 of the RWD project to build a cat painting should be combined as they are just asking the learner to add two divs (one to the .cat-left-ear and one to the .cat-right-ear)
Two steps to add 2 divs is unnecessary (this should be easy for learners who've been through all the previous projects)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/step-21

### Your code

```



```

### Expected behavior

Instead of a step for each inner ear div, a single step should suffice with instructions similar to:

Create two div elements. First inside .cat-left-ear element with class cat-left-inner-ear, and second inside .cat-right-ear element with class cat-right-inner-ear.

### System

N/A

**Comment by hbar1st** [comment]
also note, steps 41 and 42 have a similar issue and can be combined as well

**Comment by jdwilkin4** [comment]
# Note to contributors 

For the updated step 21, this should be the starting seed code to make it clear where campers need to write their code
And of course the instructions and tests will need to be updated to properly merge current step 22 into step 21.
Then delete step 22

```html
    <div class="cat-ears">
          --fcc-editable-region--
          <div class="cat-left-ear">
            
          </div>
          <div class="cat-right-ear">
            
          </div>
          --fcc-editable-region--
        </div>
```

For the updated step 41, here is the updated seed code to show where the updates need to be made

```html
   <div class="cat-eyes">
          --fcc-editable-region--
          <div class="cat-left-eye">
            
          </div>
          <div class="cat-right-eye">
            
          </div>
          --fcc-editable-region--
        </div>  
```

**Comment by vaibhav-ace** [comment]
Hi, I have created a PR for this issue. I hope this PR solves the issue. Please let me know if any changes are required. A compelte description of the PR and steps I took to solve the issue are in the PR description. Thanks!

**Comment by cheenu-1824** [comment]
@vaibhav-ace, I have looked through your PR and tested locally, the changes look good to me. Code review also looks good with no specific problems!
