### ISSUE TITLE
[python]: scope is never taught and taken for granted during the entire curriculum

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#54924]
**Describe the bug**
Some campers are struggling to understand what's going on when they get `NameError`s because they try to use variables not available in that scope. This happens mainly because the scope is never mentioned.

**Expected behavior**
We should introduce a few steps at the beginning of the curriculum to introduce variable scope.

**Comment by zairahira** [comment]
Scope is an important concept. We can introduce a few steps either in the beginning or modify the existing code:

- Attempt to print the `key_index` outside the body of `vigenere()`

```py
print(key_index)  

# output in console
Traceback (most recent call last):
  File "main.py", line 26, in <module>
NameError: name 'key_index' is not defined
```

Then explain the cause of the error.
Remove the `print` statement later on to resolve the issue.

**Comment by Dario-DC** [comment]
I think we can introduce the scope in the cipher project around step 50, when we have the following code:

```py
text = 'Hello Zaira'
shift = 3

def caesar():
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    encrypted_text = ''
    for char in text.lower():
        if char == ' ':
            encrypted_text += char
        else:
            index = alphabet.find(char)
            new_index = (index + shift) % len(alphabet)
            encrypted_text += alphabet[new_index]
    print('plain text:', text)
    print('encrypted text:', encrypted_text)
```
We can ask to print `alphabet` outside the function --> `NameError: name 'alphabet' is not defined`
We might need to add at least a couple of steps, one to add the `print` and one to remove it (the removal can be done in an existing step too).

BTW, another thing I realized we have never mentioned is that you cannot reference a variable before declaring it.

**Comment by gikf** [comment]
Related to scope there are also `global` and `nonlocal` keywords, but introduction to scope is probably not the best place to mention them.

**Comment by tomitokko** [comment]
I am going to add the steps to introduce scope. These are what I will do:

- Add a step to `print` the `alphabet` variable outside the function, and explain why there is an error
- Add another step to remove the `print`

Should I move forward with this?

**Comment by Dario-DC** [comment]
> I am going to add the steps to introduce scope. These are what I will do:
> 
>     * Add a step to `print` the `alphabet` variable outside the function, and explain why there is an error
> 
>     * Add another step to remove the `print`
> 
> 
> Should I move forward with this? @Dario-DC @zairahira

I think you can go ahead with this :+1:

**Comment by zairahira** [comment]
> I am going to add the steps to introduce scope. These are what I will do:
> 
> * Add a step to `print` the `alphabet` variable outside the function, and explain why there is an error
> * Add another step to remove the `print`
> 
> Should I move forward with this? @Dario-DC @zairahira

Sure Tomi, that seems the right way 👍️

**Comment by zairahira** [comment]
> BTW, another thing I realized we have never mentioned is that you cannot reference a variable before declaring it.

The best place would be the early steps of the Cipher project. Need to explore where exactly.

**Comment by Dario-DC** [comment]
Actually, what I meant was something like:
```py
print(text)
text = 'Hello World'
```
I saw several posts on the forum where people are trying to do something with variables before the declaration.

I'd consider to add an example similar to the one above and explain why is not valid, without adding new steps.
