### ISSUE TITLE
Waypoint: Access MultiDimensional Arrays With Indexes [Beta] spelling

### ISSUE THREAD

**Issue by HermanFassett** [FreeCodeCamp/FreeCodeCamp#5492]
>When you use brackets to access your array, the first set of bracket refers to the entries in outer-most array, and each subsequent level of brackets refers to the next level of entry in.

the first set of bracket**s**? And I find the ending quite confusing with the `entry in`... Not sure what is supposed to be conveyed.

**Comment by CaroleAnneHannon** [comment]
also "entries in outer-most array" probably needs a "the" before "outer"
