### ISSUE TITLE
Add review step for variables and console statements in pyramid project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#54931]
### Describe the Issue

One of the things we have heard from campers going through the gradebook review project is they felt like they had to go through the pyramid project again for review.

While that is not necessarily a bad thing, my guess is that there is a lot of new concepts being introduced one after another and campers could benefit more from having review steps throughout. This will help them slow down and digest better the new information they just received in the previous steps.

Here are my proposed changes.

We should add two new steps after the current step 11 here
 **NOTE** Step numbers are subject to change since this course is still in beta. So that is why I am attaching this step here. Add two new steps after this one here.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef55dd468079679ee0092.md

## updated description and suggested hints for the first new step

````md
Now it is time to review the concepts you have learned so far. This review step is to ensure you have a good grasp on the basics so you can apply them to the pyramid generator project later on. 

In this step you will need to do the following:

- Use the `let` keyword to declare a variable called `profession` and assign it the string `"teacher"`.
- Use the `let` keyword to declare a variable called `age`. **Do not** assign it a value.
- Log to the console the value of the `age` variable. You should see `undefined` in the console.
- Log to the console the value of the `profession` variable. You should see `"teacher"` in the console.
````

Here is what we should test for in the hints section

- You should declare a variable called `profession`.
- You should use `let` to declare the `profession` variable.
- You should assign the string `"teacher"` to the `profession` variable.
- You should have a variable called `age`
- You should use `let` to declare the `age` variable.
- You should log `age` to the console.
- You should log `profession` to the console.

This should be the updated seed contents

````js
## --seed-contents--

```js
let character = 'Hello';
--fcc-editable-region--

--fcc-editable-region--
```
````

## updated description and suggested hints for the second new step

````md
Now that you have finished with the review, you can remove all of the code you just wrote in the previous step. 
````

Here is what we should test for in the hints section

- You should not have a variable called `profession`.
- You should not have a variable called `age`.
- You should not have a `console.log` statement for `age`.
- You should not have a `console.log` statement for `profession`.

This should be the updated seed contents

````js
## --seed-contents--

```js
let character = 'Hello';
--fcc-editable-region--
let profession = 'teacher';
let age;
console.log(age);
console.log(profession);
--fcc-editable-region--
```
````

### Affected Page

multiple

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
If you are new to adding steps to the curriculum, then please read through the docs here
https://contribute.freecodecamp.org/how-to-work-on-practice-projects/#how-to-work-on-practice-projects

**Comment by cheenu-1824** [comment]
Hi, I have made a PR and would love to merge it into the codebase. All testing has been done and the description is present in the PR itself. Thanks!
