### ISSUE TITLE
Fix ribbons for Legacy superblocks

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#54935]
(Edited) Currently, the ribbons for legacy curriculum are not working correctly.
![legacy_ribbons](https://github.com/freeCodeCamp/freeCodeCamp/assets/25644062/2f814630-6052-438d-9028-83fa2a89c46a)

- `Legacy Responsive Web Design Challenges` should **not** show the ribbon, because the RWD certification is now tied to the new "Responsive Web Design Certification" listed at the very top of the list.
- `Legacy JavaScript Algorithms and Data Structures Certification` should show the ribbon, because there are two separate certifications: the legacy JS certification and the new JS certification.

When the user completes all the challenges & earns all the certifications (including the legacy JS certification), it should look like this:
![legacy_ribons](https://github.com/freeCodeCamp/freeCodeCamp/assets/25644062/b85cd585-58ec-46bb-b99f-54366805a0e3)

**Comment by VP-66** [comment]
Hi @Sembauke! 

Just wanted to know exactly what the "Ribbons" are in this context. Am I correct in understanding that it means the icons next to the legacy course names ? 

Would love to hear back on this!

**Comment by Sembauke** [comment]
The ribbons are the circles next to the blocks. We only want to delete them from the Legacy superblocks.

**Comment by VP-66** [comment]
I have made a PR addressing this issue. Note currently it only removes the Ribbons, however, maintains the other styling as it is. If we want to modify the other styling to make the curriculums in-line, I am happy to do so.

**Comment by VP-66** [comment]
Hi @sidemt , thank you so much for your feedback! I have noted the changes and understand the expected outcomes, I will continue to work on this PR to address these!

Thanks once again :)

**Comment by lasjorg** [comment]
@Sembauke @sidemt Can you please update the issue?

**Comment by lasjorg** [comment]
I'm a little confused by how it looks right now.

- In the core curriculum, some of the ribbons have fill colors, and some don't. Does this signify anything, or is it just the design?
- "Learn English for Developers" and "Prepare for the developer interview job search" both do not have any completed check or ribbons. Should they?
- The 3 legacy are all different, RWD has the completed check and ribbon, the JS is missing both, the Python has the check but not the ribbon.

![learn](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/fa7dde5f-5131-4caf-a415-7aa61ef0ee13)

**Comment by ojeytonwilliams** [comment]
Hey, we're currently discussing changes to the learn map internally which could make this redundant.
