### ISSUE TITLE
Critique of new /learn IDE UI

### ISSUE THREAD

**Issue by lvl-6** [freeCodeCamp/freeCodeCamp#54945]
### Describe the Issue

I miss the old UI, when there were 3 panels (Instructions | Code | Output), that was a lot more intuitive because I could see all the instructions and feedback, and I could navigate around my code easily.

This new layout just looks messy, it leaves a lot of blank space, the instructions are getting in the way while I'm trying to code, and it almost captures the feeling of trying to code while a cat walks across the keyboard. And it's forcing me to do a whole lot of scrolling too, especially when I finish the task and press CTRL+Enter, as it doesn't automatically scroll to the feedback.

I was told to give feedback on the GitHub so I hope I'm going about it the correct way, basically my issue is that I don't like the new UI, sorry to whoever made it but we need to go back.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-5

### Steps to Reproduce

1. Go to any /learn page with coding activities
2. Look at it
3. See error

### Expected behavior

I expect to be presented with a good UI, like the OG one.

### Screenshots

![Screenshot from 2024-05-23 10-59-06](https://github.com/freeCodeCamp/freeCodeCamp/assets/24364368/a5b0bc42-ae2f-4913-81cd-72fc07f7ffc7)Example of offending layout.

### System

- Device: PC
- OS: Fedora 40
- Browser: Firefox
- Version: 126.0

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you for the feedback. Personally, I also prefer the old layout, and, whilst it is possible to render the "new" challenges in the old layout, the instructions **assume** you have an indication of where to put your code. So, I have wondered if it would be possible to have a "setting" for which layout to prefer, but the instructions would not be useful for most of the new challenges in the old layout.

One thing I have considered is putting an indication in the editor where the "jaws" (as we call them) would have been. Something like:
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/51722130/860fee94-8817-4ad2-8d64-1bd7d2783284)

This would be a relatively non-intuitive UI, though. So, it might be more confusing than not for some Campers.

**Comment by lvl-6** [comment]
Thanks for the response. I haven't saw the new challenges yet, but I would assume that whoever writes the instructions could clarify it by adding one more sentence to tell you to code "in the marked area" or "between the blue lines", whenever it's not clear. Although after a few exercises surely most users should be able to draw a connection between the special lines and the "working area" (as I'm calling it).

Although I'm not sure as I've yet to see a new challenge, it could be a silly suggestion. I would also like to see a toggle for this, that would make me happy enough, I don't imagine I'd personally have much trouble figuring out where to put my code (assuming it isn't a huge monolithic file).

**Comment by ilenia-magoni** [comment]
> I haven't saw the new challenges yet

You are going through the new challenges

**Comment by lvl-6** [comment]
Wait what? CatPhotoApp isn't new. Unless... the challenge is... doing it with the new UI in the way?

**Comment by ilenia-magoni** [comment]
CatPhotoApp was present in the old curriculum, yes, but the challenges have been reworked for the new format, and the app never reached the complexity it has now. Check the Legacy section for comparison

**Comment by lasjorg** [comment]
@ShaunSHamilton Maybe code folding would work. Just not sure how great the API for doing it programmatically is.

`https://github.com/microsoft/monaco-editor/issues/4024#issuecomment-1859756820`

So we fold the code before and after the "editable region" of the code.

**Comment by ShaunSHamilton** [comment]
> Maybe code folding would work.

If you are talking about in addition to another indicator, then that is a decent idea! The only thing I would worry about is Campers not knowing how to unfold regions.

**Comment by Louliett** [comment]
I completely agree with @lvl-6. The old layout (3 panels) was really intuitive: 
The task was described on the left panel, including the continue and tips buttons;
Your solution was in the middle (imitating a code editor together with a console);
On the right panel was displayed the visual result.
Now the task is presented in some windows ingrained in the coding area. It looks confusing and unnatural.
I try to keep an open mind and adjust to the change but it's really hard to read the code when there are windows with text placed here and there other the coding area. :(
![Screenshot 2024-06-05 at 18 15 04](https://github.com/freeCodeCamp/freeCodeCamp/assets/34436208/b6b0e6e6-5841-4956-b827-2b3ee2aa0608)
