### ISSUE TITLE
Add example for Destructuring assignment within arrow functions in platformer project

### ISSUE THREAD

**Issue by oliver90001** [freeCodeCamp/freeCodeCamp#54956]
### Describe the Issue

Destructuring is explained in earlier challenges but primarily when 'automatically' or bulk copying object properties , to a list of variables in curly brackets. This question although similar has this being done in an arrow functions input. I spent around 2 hours trying to get to the bottom of this question, when in reality the answer was fairly straight forward once principles were understood in relation to this different context (arrow functions parameters). 

Maybe some tips or an example would of helped, I realise that you are trying to enable people to do these operations without prompting, but usually a few examples are given when a topic is moderately new or complex. I felt there was strong indication in question to construct an answer that conformed to the simpler type of destructuring, without too much indication, that this was wrong, only very careful reading of questions grammar might lead you to understand that the answer lay in the functions parameter code, not the body.

A brief example or few sentences would of made alot of difference to my experience, which is normally great.

I have been asked to construct this issue in response to help received on the forum. I have put the code that I thought erroneously was how to do this , along with correct method

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-59

### Your code

Wrong way....
`window.addEventListener("keydown", (event) => {  {key}}= event});`

Where this is correct answer ....

`window.addEventListener("keydown", ({ key }) => { `
});

### Expected behavior

Bit more help , thats all, there is no coding error

### System

- Device:  Laptop
- OS: Windows 10
- Browser: Chrome
- Version: 124

**Comment by jdwilkin4** [comment]
We can add this example to the end of the directions.

## updated instructions

````md
Now it is time to add the event listeners that will be responsible for calling the `movePlayer` function.

Start by adding an `addEventListener` to the global `window` object. 

For the arguments, pass in the `keydown` event and an arrow function that uses the destructuring assignment to get the `key` property from the `event` object in the event listener parameter. 

Here is the syntax for using the destructuring assignment in the parameter list of the arrow function:

```js
btn.addEventListener('click', ({example}) => {
  console.log(example);
});
```
````

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/64c72e52133d687e8e6a60f6.md

Happy coding

**Comment by oliver90001** [comment]
Thanks very much , might help people get through this task a little quicker 
Oliver
    On Friday 24 May 2024 at 00:28:42 BST, Jessica Wilkins ***@***.***> wrote:  
 
 


This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the contributors channel, or on the contributors sub-forum

Files that need to be changed

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/64c72e52133d687e8e6a60f6.md

Happy coding

**Comment by aliarnoos** [comment]
Hi, this is my first time doing open source, and I would be happy to handle this

**Comment by masoudhsd** [comment]
Hi fellow developers
Is this issue still open?

**Comment by LemonadeCodeGirl** [comment]
Hello! is it possible to be assigned this issue? Thank you!

**Comment by lasjorg** [comment]
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
