### ISSUE TITLE
Lesson: Use PropTypes to Define the Props You Expect

### ISSUE THREAD

**Issue by AriZeto** [freeCodeCamp/freeCodeCamp#54980]
### Describe the Issue

I had noticed that in the lesson, “React: Use PropTypes to Define the Props You Expect”, that there is an expectation that users are more familiar with the types of props that can be passed within function components, specifically their PropType declaration. 

While users may not be too uncomfortable handling the task of passing props and their types throughout their react components, it may be beneficial to remind the user through additional examples on how to handle this.
Regarding PropTypes, I believe that examples that may be beneficial that could be included would be: Arrays and Objects.
Additionally, I believe that while this may not be too big of an issue for those that are more comfortable with React and type safety, this could strengthen and reinforce necessary concepts and skills when programming. Additionally, this is beneficial as it would make any potential debugging process easier.

I believe that by incorporating this change, it can better understand the necessities in how PropTypes can ensure that newer programmers (or those in need of a refresher) develop react applications that include the best practices, as well as its necessity within modern react apps. 

Finally, I am aware that [freeCodeCamp has this article going further into PropTypes. Perhaps, this should be linked within the lesson?](https://www.freecodecamp.org/news/how-to-use-proptypes-in-react/)

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/use-proptypes-to-define-the-props-you-expect

### Your code

I simply suggest incorporating some sort of foot note regarding the benefits of PropTypes (and examples), such as:
```
Benefits to utilizing PropTypes:
Incorporating PropTypes will ensure that components obtain their expected type of data. By doing this, you will ensure that your code is easier to debug, and is a better maintained, modern react app. In regards to debugging, ensuring PropTypes is useful for locating errors during development - as well as ensuring best practices too.

FreeCodeCamp provides an article on PropTypes:

[To learn more about PropTypes, visit FreeCodeCamp's article on PropTypes](https://www.freecodecamp.org/news/how-to-use-proptypes-in-react/)

Example utilizing PropTypes that contains strings within an array.

MyComponent.propTypes = {
  handleClick: PropTypes.func.isRequired,
  items: PropTypes.arrayOf(PropTypes.string).isRequired
};
```

### Expected behavior

I expect that by providing the additional article on PropTypes from FreeCodeCamp could better reinforce this lesson. In addition, I believe that by providing a declaration of a PropType (such as my array example) would further better understand the concept for newer programmers.

### System

- Device: Macbook Pro w/M1 Pro Silicon (2021 model).
- OS: macOS Sonoma 14.4.1 
- Browser: Firefox
- Version: 126.0 (64-bit)

**Comment by naomi-lgbt** [comment]
I'm not sure this change needs to be made, especially given that the FE Libs curriculum is next on our list for a rewrite.

**Comment by naomi-lgbt** [comment]
Yeah, we already link to the official documentation. That should be more than sufficient.
