### ISSUE TITLE
Reaccessing Home Page

### ISSUE THREAD

**Issue by mpdillingerOSU** [freeCodeCamp/freeCodeCamp#54984]
### Is your feature request related to a problem? Please describe.

For this, I have noticed that once you move onto other pages within the website, there is not currently an easy way of returning to the Home Page. It is not in the dropdown menu, and the website icon on the navigation bar for donate and other pages of the main platform actually returns the user to the Curriculum Page, not the Home Page. As such, there needs to be an easy way of navigating back to the actual Home Page. It just seems odd that one cannot easily return to the Home Page without having to enter the URL. As such, it creates an odd navigational map from a UX perspective. This is especially important for a new user if they want to access the FAQs on the Home Page in order to better understand the website.

### Describe the solution you'd like

As such, with the dropdown produced by the "Menu" button, it would make sense to also add a "Home" selection where we also find "Donate" and "Curriculum" selections. With this, the user can now easily access the three main pages of the main platform.

### Describe alternatives you've considered

The other alternative would be to have the website icon/name take the user back to the Home Page, rather than the Curriculum Page - as this is the typical external standard that most websites use for the icon/name acting as a shortcut.

**Comment by naomi-lgbt** [comment]
Thank you for reporting this, but this behavior is a conscious design choice. Our analytics tell us that people prefer using the learn map more than the landing page – which is optimized for first time visitors.

You are able to type in the URL: www.freecodecamp.org in your address bar to land on the homepage should you be "interested" in seeing the landing page.

We appreciate your feedback, happy coding.
