### ISSUE TITLE
Waypoint: Multiple Identical Options in Switch Statements [Beta] spelling

### ISSUE THREAD

**Issue by HermanFassett** [FreeCodeCamp/FreeCodeCamp#5498]
>ommitted

should be omitted

**Comment by abhisekp** [comment]
Addressed in [https://github.com/SaintPeter/FreeCodeCamp/pull/8](https://github.com/SaintPeter/FreeCodeCamp/pull/8/files#diff-5fbffcdf48f7976dd3b0216c387eebc2R3209)
