### ISSUE TITLE
Waypoint: Passing Values to Functions with Arguments [Beta]

### ISSUE THREAD

**Issue by CaroleAnneHannon** [FreeCodeCamp/FreeCodeCamp#5499]
I think the first line should either end with "a parameter" or "parameters". "form of parameter" sounds weird.

**Comment by CaroleAnneHannon** [comment]
Also I keep getting "RangError: Maximum call stack size exceeded" when running

**Comment by abhisekp** [comment]
@CaroleAnneHannon I don't get any range errors. What's your code?

**Comment by SaintPeter** [comment]
New text:
![image](https://cloud.githubusercontent.com/assets/553494/12023753/7b49f460-ad51-11e5-9694-08b60564f773.png)

**Comment by abhisekp** [comment]
@SaintPeter it's `into` the function, not `in to` the function.

**Comment by SaintPeter** [comment]
Got it.

**Comment by lucabarbetti** [comment]
Hello,
I get the message **RangeError: Maximum call stack size exceeded** with the following code:
```
function myFunction(a, b) {
  console.log(a + b);
}
myFunction(10, 5);
```
