### ISSUE TITLE
Statistics calculator - Step 5: should not require an anonymous callback

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#54997]
### Describe the Issue

I don't think this should require an anonymous callback when you can just pass `Number` as the callback. It should pass with both.

Expected:
```
const numbers = array.map((el) => Number(el));
```

Valid code not passing:

```
const numbers = array.map(Number);
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-5

### Your code

```



```

### Expected behavior

Valid code should pass.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by sanjeevmurmu** [comment]
i think elements in the number array are not in numerical format so the anonymous function is mapped over all the elements of the array to convert each element into a number using the Number constructor

**Comment by lasjorg** [comment]
@sanjeevmurmu It works exactly the same without the anonymous function. Constructor functions like Number, Boolean, String and so forth can all be passed directly as the callback.

```js
console.log([1, "Hi", false, null, ""].filter(Boolean)); // [1, "Hi"]
console.log([1, 2, 3].map(String)); // ["1", "2", "3"]
console.log(["1", "2", "3"].map(Number)); // [1, 2, 3]
```

**Comment by a2937** [comment]
While I do understand that it is a valid solution, I think the purpose of this lesson was to demonstrate how to pass a callback function into the `map` method.  As taken from the lesson page: 

> The `.map()` method takes a callback function as its first argument. This callback function takes a few arguments, but the first one is the current element being processed 

While passing in the `Number` constructor is valid and gives the right output, it doesn't seem to properly demonstrate the point of the lesson.

**Comment by lasjorg** [comment]
> I think the purpose of this lesson was to demonstrate how to pass a callback function into the `map` method.

That is what `["1", "2", "3"].map(Number)` does, it is passing `Number` as the callback.

> While passing in the `Number` constructor is valid and gives the right output, it doesn't seem to properly demonstrate the point of the lesson.

I don't think that is the point of the lesson. It is teaching `map`, but in doing so seem to be suggesting that you _have to_ use an anonymous callback function, when you do not. Wrapping the `Number` constructor achieves nothing in this case, it is in fact just creating an extra function when it isn't needed.

Here is an example that would require wrapping the function (because we have to pass the radix).

```js
console.log(["01010", "10100", "11110"].map((number) => parseInt(number, 2)));
```

This step isn't specifically teaching about using an anonymous callback function, seeing as it doesn't mention anything about it. I don't think we can claim that is what is being taught.


Valid code should for the most part always pass. As such, I see no good reason not to update the regex to accept `Number` directly as the callback.

---

This step barely is even teaching `map`. Considering this section of the curriculum is named "Learn Advanced Array Methods", I find the step pretty shallow. I'd suggest at least describing the API and how to use the method, even if that means having more steps.

I did look into updating this step, but I don't think we can fit it all into one step.

**Comment by aaqib605** [comment]
> While I do understand that it is a valid solution, I think the purpose of this lesson was to demonstrate how to pass a callback function into the `map` method. As taken from the lesson page:
> 
> > The `.map()` method takes a callback function as its first argument. This callback function takes a few arguments, but the first one is the current element being processed
> 
> While passing in the `Number` constructor is valid and gives the right output, it doesn't seem to properly demonstrate the point of the lesson.

I agree.

**Comment by lasjorg** [comment]
This is the requirement:

> Add a callback function to your `.map()` method that converts each element to a number.

As such, passing `Number` as the callback should pass. There is absolutely no reason why it shouldn't.

If we want to teach using a wrapping callback function, we should use `parseInt` and have them pass in `10` as the radix. That would necessitate wrapping the function call.

---

You need to understand the difference between the two. This concept is not isolated to this type of higher order function. The challenge requirement is equivalent to forcing an event handler to be wrapped inside an anonymous callback function when you can just pass the handler directly.

**Comment by naomi-lgbt** [comment]
I agree, the test case is irrelevant to the instructions. Here's what I'd propose:

- Leave the instructions as they are.
- Update the tests to allow passing `Number` as a reference.
