### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by kschweikert** [FreeCodeCamp/freecodecamp#550]
the syntax checker and mobile viewer have had compounding issues for me as a work through this tutorial in firefox. 
this is how this challenge loaded without my changing any of the text. The mobile view shows duplicated content which doesn't match the code
![capture](https://cloud.githubusercontent.com/assets/10518995/7820217/fe83589a-03b4-11e5-912b-799752684b5a.PNG)

**Comment by QuincyLarson** [comment]
Interesting. Several people have reported this. I'll open up Firefox and see if I can figure out what's wrong. It works fine in Chrome.

**Comment by kschweikert** [comment]
yes it is definitely working better in chrome, thanks

**Comment by denmch** [comment]
There's a Sandbox access violation in Safari 8.

**Comment by QuincyLarson** [comment]
Awesome - 7-11 at 3:00? Please write back to confirm.


- Quincy Larson
"Anyone who has begun to think, places some portion of the world in
jeopardy." - John Dewey

**Comment by QuincyLarson** [comment]
Fixed
