### ISSUE TITLE
Website slows down/learn

### ISSUE THREAD

**Issue by LanternJack** [freeCodeCamp/freeCodeCamp#55017]
### Describe the Issue

When I change browser zoom settings of my mobile browser to 75% it becomes almost impossible to type or remove any challenge code — letters are missing, I have to do everything really carefully to prevent the situation when I delete a part of code that I still need.

When I pass a challenge with a default zoom settings — everything almost ok, but keyboard sometimes doesn't appears immediately and I have to touch my screen multiple times to call the keyboard.

When I used the application for passing the Responsive Web Design set of challenges I didn't faced such a problem.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-24

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

The text is inputting and deleting without any delays. Keyboard appears upon touching the line of the code.

### System

- Device: Realme c25 (rmx 3191)
- OS: UI 4 (Android 13)
- Browser: Mozilla, Kiwi, Yandex, Google Chrome

**Comment by shwetd19** [comment]
Hey there 👋,

I just saw of issue #55017 about the typing and keyboard responsiveness on mobile browsers. Sounds like a crucial bug to tackle for a smooth coding experience. I'd love to jump in and help resolve this. My recent projects have involved optimizing user interfaces for better interaction, which I believe could be beneficial here. Would it be possible to give this issue a shot? 

Excited to contribute!
Cheers,
@shwetd19

**Comment by LanternJack** [comment]
Hi, @huyenltnguyen, thanks for your reply. I have no idea how, but the issues have disappeared about 2 days ago, wow. I had the following issues, but there is everything ok by now:

(1) When the font size level is 75% the website works much slower (sorry, I was wrong about a zoom level in my first message);
(2) This issue is exactly described by you ("When the page first loads, the keyboard does show up. But if we close the keyboard and tap on the editor, it becomes hit-and-miss.").
