### ISSUE TITLE
Challenge completion indicator should not have side margin

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55047]
## Description

A2 English blocks have challenges whose title is displayed next to a completion indicator. The indicator is having a right margin, which creates a gap between the indicator and the text.

<img width="746" alt="Screenshot 2024-05-31 at 22 49 13" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/fc6e9480-1362-465b-8c64-bf093e0bbfbf">

This issue is because the indicator has a `badge` class:

https://github.com/freeCodeCamp/freeCodeCamp/blob/29326e64242782dbfeef744bf978a70be8a66091/client/src/templates/Introduction/components/challenges.tsx#L35

This `badge` class was harmless as it didn't have any CSS rules associated, until we added badges to the user profile page, which caused a class name collision:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/29326e64242782dbfeef744bf978a70be8a66091/client/src/components/profile/components/camper.tsx#L67
- https://github.com/freeCodeCamp/freeCodeCamp/blob/29326e64242782dbfeef744bf978a70be8a66091/client/src/components/profile/components/camper.css#L89-L91

## Affected page

https://www.freecodecamp.org/learn/a2-english-for-developers/

## Changes needed

- Remove the `badge` class from:
  - https://github.com/freeCodeCamp/freeCodeCamp/blob/29326e64242782dbfeef744bf978a70be8a66091/client/src/templates/Introduction/components/challenges.tsx#L35
  - https://github.com/freeCodeCamp/freeCodeCamp/blob/29326e64242782dbfeef744bf978a70be8a66091/client/src/templates/Introduction/components/challenges.tsx#L45
- Rename the `badge` class in `camper.tsx` to `camper-badge` to avoid future collision

**Comment by derfman9303** [comment]
I can take this one, but I don't seem to have the permissions to assign myself to this issue. 🤷

**Comment by derfman9303** [comment]
Awesome, thanks for clarifying!
