### ISSUE TITLE
Waypoint: Assignment with a Returned Value [Beta]

### ISSUE THREAD

**Issue by CaroleAnneHannon** [FreeCodeCamp/FreeCodeCamp#5505]
"Call process function with an argument of 7 and assign it's return value to the variable processed."

it's -> its

Also it says processed should have a value of 10 in the first test, and the directions say to pass 7. Well (7+3) / 5 is equal to 2, not 10.

processed is not visible in the output so a person couldn't check this.

**Comment by SaintPeter** [comment]
Added a tail function to display the output of `processed` and updated the text.

**Comment by SaintPeter** [comment]
Also added a "the"
> Call the process function
