### ISSUE TITLE
Dedicated section teaching callbacks

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#55052]
### Is your feature request related to a problem? Please describe.

Campers do not understand callbacks well.

I see this everywhere on the forum. Even with people far into the backend part of the curriculum. It happens with higher order functions, with handler functions, with callbacks such as done, take your pick.

I know we technically teach them as part of teaching other subjects but, we might want to consider a short section dedicated just to using callbacks, just as we have one on async.

### Describe the solution you'd like

A new short section dedicated to callbacks.

### Describe alternatives you've considered

It might be possible to combine it with teaching async. But there isn't really a one to one correlation in all cases.

### Additional context

Edit: Maybe we also make it a point to teach what is meant by functions as first-class citizens/First-class Function

https://developer.mozilla.org/en-US/docs/Glossary/First-class_Function

Again, to expand. The main issue is they are not able to identify a callback and do not understand how to use a callback, so they tend to invoke the function or not understand the idea of passing a function around as a value.

**Comment by a2937** [comment]
I wanna see this added to our JavaScript section as well.

**Comment by naomi-lgbt** [comment]
We could totally add a project to teach this - I'm not sure what it would be, though. Any thoughts or ideas?

**Comment by a2937** [comment]
The project has to involve data being modified or used in different ways if we're using functions in my opinion. Something along similar lines to using array.includes or array.some. 

One of the possible ideas I had involved some sort of book collection where you can filter by genre, year published, author name, positive reviews, summary. Maybe even exclude based on the same criteria. 

What do you think Naomi?

**Comment by naomi-lgbt** [comment]
That could certainly work. Also need to figure out where in the curriculum this is going to go.

**Comment by a2937** [comment]
My current thoughts are to put it roughly around the projects right before the Cash Register certification project. The certification project needs additional practice projects in front of this, and this is basically intermediate functional programming.

**Comment by a2937** [comment]
Actually I was wondering something. Can't we put into the `Review Javascript Fundamentals By Building a Gradebook Project`?

**Comment by lasjorg** [comment]
I would prefer if this was a short challenge, maybe no more than 10–15 steps. If we bury them inside a large project, I fear we are back to the initial problem where they are never the main focus of what is taught. The focus should be on what a callback is and how functions can be passed as values to be called later.

It could be as simple as an array of objects and using a few higher order functions to perform various operations on the objects. And maybe one or two event handlers. Nothing we do not already teach, but with callbacks as the main focus.

1. What is a callback.

2. How do you use a callback.

3. Why would you use a callback.

4. Examples of higher order functions changing behavior depending on what callback is passed to them.

5. Example of event listeners and why you have to pass the handler function and not call it.

Simple stuff, but with the focus constantly on callbacks. Just to really drive it home.

**Comment by a2937** [comment]
Okay. I do see your logic. I'll see what I can come up.
