### ISSUE TITLE
Bonfire: Caesars Cipher [Beta] spelling

### ISSUE THREAD

**Issue by HermanFassett** [FreeCodeCamp/FreeCodeCamp#5506]
>(IE: spaces, punctiation)

should be punctuation I assume. Also, IE makes me think Internet Explorer where as i.e. makes me think more id est or that is. No biggie.

**Comment by SaintPeter** [comment]
![image](https://cloud.githubusercontent.com/assets/553494/12024025/d5775be6-ad54-11e5-9676-616c0256470c.png)

**Comment by abhisekp** [comment]
@SaintPeter Is it easier to understand for beginners? 
> *do pass them on*
