### ISSUE TITLE
Remove unused avatar class

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55067]
## Description

The `default-avatar` class is not used and can be removed.

## Changes needed

Remove `default-avatar` class from:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/ebf8d8fda9c48e3d77ae3779f05d08c70395d175/client/src/components/helpers/avatar-renderer.tsx#L47
- https://github.com/freeCodeCamp/freeCodeCamp/blob/ebf8d8fda9c48e3d77ae3779f05d08c70395d175/client/src/assets/icons/default-avatar.tsx#L11

**Comment by AnmolxSingh** [comment]
Hi @huyenltnguyen 
I am new to open source can this issue be assigned to me.
