### ISSUE TITLE
Remove `border-color` from `.confirm-donation-btn`

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55069]
## Description

The `.confirm-donation-btn` class has both `border-color` and `border: none` set:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/5eb055817a48eaf120fceda730eec3c9c57144ea/client/src/components/Donation/donation.css#L448
- https://github.com/freeCodeCamp/freeCodeCamp/blob/5eb055817a48eaf120fceda730eec3c9c57144ea/client/src/components/Donation/donation.css#L453

The `border-color` rule is redundant and should be removed as the border is hidden anyway due to `border: none`.

I'm also getting a complaint from CodeFactor because of those rules:

<img width="799" alt="Screenshot 2024-06-03 at 15 57 54" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/52bb8cb9-04c6-43a6-97ea-1f2316c70809">

## Changes needed

- Remove the `border-color` rule from `donation.css`

**Comment by KartikChinda** [comment]
hi @huyenltnguyen , I'd love to work on this issue, please assign it to me.
