### ISSUE TITLE
Bonfire: Steamroller freezes the tab

### ISSUE THREAD

**Issue by DiegoRBaquero** [FreeCodeCamp/FreeCodeCamp#5507]
I have the following code: https://www.dropbox.com/s/5wcyhzeqgeutajn/Screenshot%202015-12-27%2022.42.36.png?dl=0

The tab dies 1 second after loaded. I can't do anything.

**Comment by ltegman** [comment]
You must have an infinite loop. You can either [Disable Code Auto-Run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) or [Clear the Solution from localStorage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage).

Thanks and happy coding!
