### ISSUE TITLE
A2 English for Developers (Beta) - Missing space between sentences

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#55078]
### Describe the bug
In the A2 English for Developers courses there's few occurrences of space missing, after the dot ending one sentence, and the uppercase letter starting next sentence.

Here are the lines with affected sentences. They need to have space added between dot and uppercase letter from different sentences:
https://github.com/freeCodeCamp/freeCodeCamp/blob/fde6a505fd1cf4df9990bab10c967ba2bfcb8e65/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a505171c360103cf718f9.md?plain=1#L12
https://github.com/freeCodeCamp/freeCodeCamp/blob/fde6a505fd1cf4df9990bab10c967ba2bfcb8e65/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a52d92a586612be333b16.md?plain=1#L26
https://github.com/freeCodeCamp/freeCodeCamp/blob/fde6a505fd1cf4df9990bab10c967ba2bfcb8e65/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/657e44fe476035667aab9114.md?plain=1#L12
https://github.com/freeCodeCamp/freeCodeCamp/blob/fde6a505fd1cf4df9990bab10c967ba2bfcb8e65/curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e4e3b02a2128049c344c8.md?plain=1#L29

- - -

This is something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a505171c360103cf718f9.md
2. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a52d92a586612be333b16.md
3. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/657e44fe476035667aab9114.md
4. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e4e3b02a2128049c344c8.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by SeanSweeney04** [comment]
I can do this

**Comment by royjohnlee** [comment]
forgot to link my pull request from yesterday

**Comment by harishcalvin** [comment]
@Sembauke May I know why my PR is closed? I submitted my PR earlier than @royjohnlee. Can I know if there are any mistakes I have made?

**Comment by ilenia-magoni** [comment]
@harishcalvin you ignored the camperbot message and did not do any updates. Also please do not ping random maintainers, you can join our Discord community for more direct interaction if you want.
