### ISSUE TITLE
Test too strict in Sudoku Solver project, step 74

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#55085]
**Describe the bug**
Instructions ask to modify the list comprehension to give a string only when the item is not zero, and an asterisk character otherwise. The accepted answer is:
```py
row_str = [str(i) if i else '*' for i in row]
```
But other answers like `row_str = [str(i) if i != 0 else '*' for i in row]` or `row_str = ['*' if i == 0 else str(i) for i in row]` are equally valid.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/step-74

**Expected behavior**
Although the instructions ask for a specific solution, it might not be clear enough. Therefore it would be better to modify the test to accept multiple solutions.

**Comment by a2937** [comment]
While I do agree, I'm not quite sure how to modify the test to make sure that the two others are seen as possibilities are the moment. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/10fae3d41be65b97169576ea1b12839becdf0983/curriculum/challenges/english/07-scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/660ac44c7eec868220318297.md#L17


I don't think our helper method is equipped enough to handle this. 

https://github.com/freeCodeCamp/curriculum-helpers/blob/0cfc80043d9b9029c021c07c3096d69ba0be09c6/python/py_helpers.py#L322

**Comment by Dario-DC** [comment]
I would say something like this:

```js
({ test: () => runPython(`
node =_Node(_code).find_class("Board").find_function("__str__").find_for_loops()[0].find_bodies()[0].find_variable("row_str").find_comp_expr()
expressions = ["str(i) if i else '*'", "'*'" if i == 0 else str(i)"]
assert any(node.is_equivalent(expr) for expr in expressions)
`) }) 
```
Providing all the possible solution in the `expressions` list.
