### ISSUE TITLE
Missing instruction in learn-basic-css-by-building-a-cafe-menu

### ISSUE THREAD

**Issue by danielh2222** [freeCodeCamp/freeCodeCamp#55087]
### Describe the Issue

I think I found  bug in my coding class in "learn-basic-css-by-building-a-cafe-menu". In step 60 we have to create a class selector for "Est. 2020"  and make the font style italic. but in line 13 where we originally wrote <p>Est. 2020</p> should we not add "class="established" within the p value. if not can you please explain it to me

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-60

### Your code

```
Index.html
<p>Est. 2020</p>
Style.ccs
.established {font-style: italic}


```

### Expected behavior

Index.html
<p class="established">Est. 2020</p>
Style.ccs
.established {font-style: italic}

### System

- Device:macbook
- OS: ios 14
- Browser: Chrome
- Version: ? idk

### Additional context

Not a problem but I just want to say I have enjoyed learning up to this point!

**Comment by a2937** [comment]
We add the class in step 61. 

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-61

**Comment by danielh2222** [comment]
Thank you, I only saw after I posted it and moved on with the exercise. Apologies for the inconvenience
