### ISSUE TITLE
View Code Option for React After Completion

### ISSUE THREAD

**Issue by ashishkhanal30** [freeCodeCamp/freeCodeCamp#55086]
### Is your feature request related to a problem? Please describe.

I completed all the 47 lessons for React. However, the code for the completed lessons are not saved. How do I review the lessons without having to rewrite all the lessons again?

### Describe the solution you'd like

One of the contributor mentioned the codes are not saved to prevent inconsistencies and local storage issues. 

However, if there was a text file containing solution of the lessons viewable to students after completion of the course segment it would be helpful.

### Describe alternatives you've considered

I resolved the lesson within the editor.

**Comment by ShaunSHamilton** [comment]
Hello there 👋 

I am not sure this would be a good idea to add. One of the last things we want is to make it very easy for Campers to see the solution to all the challenges very easily.

I suppose, we could only make the solution available once the challenge has been completed. What would the UI be, though? A button on each page with "Show Solution"?

**Comment by naomi-lgbt** [comment]
> However, if there was a text file containing solution of the lessons viewable to students after completion of the course segment it would be helpful.

Solutions for all of our front-end challenges can be found in our codebase, as well as on the forum.

> I suppose, we could only make the solution available once the challenge has been completed.

Given that the completion modal for non-step-based challenges includes a button to download your code, I don't see a need to go this far.

**Comment by ashishkhanal30** [comment]
> I suppose, we could only make the solution available once the challenge has been completed. What would the UI be, though? A button on each page with "Show Solution"?
I was thinking maybe a tab that holds a read-only file. Inside the file, codes with the title of challenge that way "show solutions" is not required for each rather a single tab holds solutions of all. And  of course the review has to be made available only after completion of all challenges.

**Comment by naomi-lgbt** [comment]
I don't see a point to bake that in, to be honest.

**Comment by ashishkhanal30** [comment]
> I don't see a point to bake that in, to be honest.

I understand that there are ways around it. Was just bringing it up thinking it might be helpful and convenient.

**Comment by shwetd19** [comment]
@shwetd19

Hey there 👋,

Just wanted to share the idea of showing solutions after finishing challenges. I get why some folks might think it's a good idea, but I worry it might take away from the learning experience a bit. How about we only show the solutions after someone finishes a challenge? And for the UI, maybe a simple tab that says "Solutions" could hold all the answers in a read-only file? Just a thought. What do you guys think?

Cheers,
Shwetas @shwetd19
