### ISSUE TITLE
The typos and errors I found [beta]

### ISSUE THREAD

**Issue by luishendrix92** [FreeCodeCamp/FreeCodeCamp#5508]
#### Waypoint: Storing Values with the Equal Operator
Right where it says `Assign the value 7 to variable a`, it should be `to the variable a`.
Same goes with `Assign the contents of a to variable b.` as it should have a `the`.

#### Waypoint: Understanding Uninitialized Variables
The word "concatenate" was mispelled in `If you concatanate a string with an undefined variable`.

#### Waypoint: Finding a Remainder in Javascript
In the Usage section, there's a "the" missing: `checking the remainder of division of the number by 2.` so it should be `of the division`.

#### Waypoint: Concatenating Strings with the Plus Equals Operator
The instructions ask you to concatenate two sentences with this description: `"This is the first line. " and "This is the second line." using the += operator` but I'm not sure if the word **"line"** is correct here, it may be confused with a line break, instead, I suggest using the word **"sentence"**.

#### Waypoint: Passing Values to Functions with Arguments
At the beginning of the explanation, `Functions can take input in the form of parameter.` should be `form of a parameter` separating "of" and "paramenter" with "a".

#### Waypoint: Passing Values to Functions with Arguments
If I execute my function with a negative value in a parameter, the last test case `Call myFunction after you define it` fails, however, it passes when I use positive values. This happens even though it outputs the correct negative value (I executed `myFunction(5, -10)`) of -5 in the output section.
I also think I saw a "Maximum Call Stack Exceeded" error in the output section but I couldn't reproduce the bug.

#### Waypoint: Local Scope and Functions
Declaring a variable inside the function is pretty ambiguous, one could declare it without assigning any value at all and it would be undefined both inside (because of no assignment) and outside (out of scope). Also, I didn't see what the test case was once I completed the waypoint, only the green checkmark icon.

#### Waypoint: Comparison with the Strict Equality Operator
In the instructions, it says `Use strict equality operator in if statement so ` when there should be a "the" separating "Use" and "strict" as `Use the strict equality operator`.

#### Waypoint: Comparison with the Strict Inequality Operator
We are talking about the "Strict" Inequality Operator, however, in the first line of the explanation it says `The inequality operator (!==) is the opposite` which would look better as `The strict inequality operator`.

#### Waypoint: Comparison with the Less Than Equal To Operator
In here `If the number to the left is less than or equl the number to the right` it says "or equl" and it should instead say "or equal to".

#### Waypoint: Comparisons with the Logical And Operator
I think it may look more clear if the keyword "and" in the explanation when refering to the logical operator, was in uppercase so it'd say "AND". The same goes for the *Waypoint: Comparisons with the Logical Or Operator*.

#### Waypoint: Comparisons with the Logical Or Operator
` returns true if either ofoperands is true.` Might look better if it said `returns true if at least one of the operands is true`, sometimes, we write more than two operands. Not to mention the lack of separation between "of" and "operands".

#### Waypoint: Introducing Else If Statements
Inside the example code it says `if (num > 15) { return "Bigger then 15";`, change "then" to "than".

#### Waypoint: Selecting from many options with Switch Statements
The instructions are unclear to newcomers, I saw a column of numbers and related them to the "val" argument passed to the function, but there's nothing wrong with mentioning that it should be according to that "val" variable passed to the function.

#### Waypoint: Adding a default option in Switch statements
During the explanation, I encountered a grammatic error: `statement which will be executed if no matching case are found` is wrong because case, being a keyword that may not be ok to put as plural, it's convenient to put `no matching case was found`. Or maybe change it to plural.

#### Waypoint: Accessing Objects Properties with Bracket Notation
At the start of the explanation, `The second way to access the properties of an objectis bracket notation ([]).` can be read and note that there is no separation between "object" and "is", it says "objectis".

#### Waypoint: Accessing Objects Properties with Variables
In the part that says `This can be very useful for itterating through`, "itterating" is spelled "iterating".

#### Waypoint: Using Objects for Lookups
This part of the example code is missing commas `,` after each lookup set of `property: value`:

```
var alpha = {
  1:"Z"
  2:"Y"
  3:"X"
...
  4:"W"
  24:"C"
  25:"B"
  26:"A"
};
```

I also don't think it's necessary to have a variable "result" declared since the user will create another one called "lookup", this leaves the variable "result" without a purpose in life.

#### Waypoint: Testing Objects for Properties
`Sometimes it is useful to check of the property of a given object exists or not.` Check where it says "of the property", it should be "if the property".

Also, in `Modify function checkObj to` it should be `Modify the function checkObj to`. Not forgetting about `If not return "Not Found".` that is missing a comma between "not" and "return", for pausing and grammar purposes of course.

#### Waypoint: Introducing JavaScript Object Notation JSON
In `JSON is flexible becuase it allows`, "because" is mispelled, it says "becuase".

#### Waypoint: Accessing Nested Objects in JSON
Inside the instructions: `Only use object notation for properties with a space in their name.` I believe your need to change "object notation" to "bracket notation".

#### Waypoint: Modifying JSON Values
Nothing appears for me in here.

## From me with love

I'm still completing the last 2 bonfires, however, if I see any problem with my solutions I'll be quick to post it here!

**Comment by AkiraLaine** [comment]
I'm on it.

**Comment by AkiraLaine** [comment]
@luishendrix92 Thanks for all of this! 

@SaintPeter I didn't touch the following:
1. Waypoint: Passing Values to Functions with Arguments 
2. Waypoint: Local Scope and Functions
3. Waypoint: Modifying JSON Values

**Comment by SaintPeter** [comment]
Switch Statements: 
![image](https://cloud.githubusercontent.com/assets/553494/12024504/73166d0c-ad59-11e5-871e-ecc3a1e7ed5c.png)

Hope that is clearer.

BTW, many of these are dupes, but not all.

**Comment by SaintPeter** [comment]
While you did have some dupes, you also managed to catch a great number of things that others did not.  Thank you!

**Comment by ashleemb** [comment]
On the JS "Finding a Remainder in JavaScript" exercise, the bit about the modulus operator and remainder operator not being the same thing is incorrect (for the JavaScript language)

source: https://msdn.microsoft.com/en-us/library/9f59bza0(v=vs.94).aspx

**Comment by bugron** [comment]
@ashleemb [ECMAScript does not currently have a modulo operator](http://wiki.ecmascript.org/doku.php?id=strawman:modulo_operator). See this [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder_%28%29) too.

**Comment by ashleemb** [comment]
Gotcha. Thanks!

On Wednesday, January 27, 2016, Arsen Melikyan <notifications@github.com>
wrote:

> @ashleemb <https://github.com/ashleemb> ECMAScript does not currently
> have a modulo operator
> <http://wiki.ecmascript.org/doku.php?id=strawman:modulo_operator>. See
> this MDN article
> <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder_%28%29>
> too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5508#issuecomment-175528592>
> .
>


-- 
Ashlee M. Brown
ashleemariebrown93@gmail.com
+1 541 632 3143
Connect with me on LinkedIn <https://nl.linkedin.com/in/ashleemb>
