### ISSUE TITLE
Poor list introduction in Expense Tracker project of SCWP

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#55084]
**Describe the bug**
Lists are introduced for the first time in the Expense Tracker project, but there's no mention that list elements can be referenced by their index, similarly to the characters in a string.

**Expected behavior**
We should add a brief explanation, possibly in [step 2](https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/step-2)

Although this is not the purpose of this project, we could add a few steps to make campers familiarize with lists (indexing, appending/inserting elements, modifying an element etc.) in a similar way to what we have done with dictionaries in the Shortest Path Algorithm project starting from [step 2](https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/step-2) up to step 14.

**Comment by a2937** [comment]
I am completely for adding a few additional steps to the Expense tracker project. It would provide practical experience with lists that can't be resolved from just brief explanations alone. Great suggestion.
