### ISSUE TITLE
Discrepancies in solution dropdown text on /setting and /certification

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55096]
## Description

On /settings, the solution dropdown shows its items as "Front End" and "Back End":

<details>
  <summary>Image</summary>

<img width="780" alt="Screenshot 2024-06-06 at 00 25 45" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/98163a7a-8e0a-459e-80b4-fbb48afe8c55">
</details>

While on the /certification page, the items are "solution" and "source":

<details>
  <summary>Image</summary>

<img width="902" alt="Screenshot 2024-06-06 at 00 25 57" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/0f66d9ac-a1f1-438e-892e-7418c1b15dd1">

</details>

## Affected page:

- /settings#cert-information-security-and-quality-assurance
- /certification/username/information-security-and-quality-assurance

## Changes needed

I'm not sure if the discrepancies are intended. If they are not, I think the items should be "solution" and "source", since the project page asks for those links:

<details>
  <summary>Image</summary>

<img width="785" alt="Screenshot 2024-06-06 at 00 37 11" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/96103d79-a308-4042-bf01-0c055b6e796f">
</details>

Additionally: 
- "solution" and "source" should be capitalized
- There should be a space between the text and the icon

**Comment by naomi-lgbt** [comment]
I'm in agreement - Solution and Source.

**Comment by Narkunan** [comment]
Hi naomi can you assign this to me
