### ISSUE TITLE
Misleading instruction (660ef0f7c4b8e68ccd1f0786)

### ISSUE THREAD

**Issue by NilsGke** [freeCodeCamp/freeCodeCamp#55093]
### Describe the Issue

on [660ef0f7c4b8e68ccd1f0786](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef0f7c4b8e68ccd1f0786.md) it says 
`Note that strings are immutable, which means once they are created, they cannot be changed.`
For a beginner, this could be misleading, as they might think, they cannot change the variable. 

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef0f7c4b8e68ccd1f0786.md

### Expected behavior

A description like: `The string is immutable, so it cannot be changed (the variable value itself however can be changed`

**Comment by jeremylt** [comment]
We should avoid parenthetical information like that whenever we can, in my opinion. It makes the sentence much harder to parse.

**Comment by ojeytonwilliams** [comment]
Is it even worth mentioning here? The lesson doesn't show any consequences of immutability, so it might simply be better to remove the sentence.

**Comment by jeremylt** [comment]
I feel like it should be mentioned somewhere, but probably the first lesson where its needed

**Comment by lasjorg** [comment]
I think it is part of teaching strings.

Here is how MDN words it:

> In [JavaScript](https://developer.mozilla.org/en-US/docs/Glossary/JavaScript), [primitive values](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) are immutable — once a primitive value is created, it cannot be changed, although the variable that holds it may be reassigned another value.

But it would certainly be worth circling back to it when it becomes relevant to make sure the practical implication of it is shown.

**Comment by ganesh-159th** [comment]
The description accurately mentions that strings in JavaScript are immutable, meaning their contents cannot be changed once created. However, it's important to clarify that while strings themselves are immutable, the variables holding them can be reassigned to new values. Therefore, no changes are necessary in this instance. @NilsGke

**Comment by NilsGke** [comment]
I agree, the description is correct, though for someone encountering variables, strings and immutability for the first time, they might get confused, thinking they cannot change the variable as it is a string, which is immutable.

[Two lessons later](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef31a5be625914a0102cd.md) you learn how to reassign variables. Maybe not mentioning immutability at this early stage is the better choice.

**Comment by ganesh-159th** [comment]
Good point! Reassigning variables is key. Perhaps mentioning immutability later reinforces the distinction between variable and data type 
 @NilsGke

**Comment by naomi-lgbt** [comment]
I would be fine moving it to somewhere closer to where something like array mutation is taught.

**Comment by lasjorg** [comment]
I think we should at least update the text to say the variable can be reassigned another value.

This early on in the learning process, the difference between a "value" and a "variable containing a value", is likely not that well understood.

In some other challenge step, we then show what it actually means that a primitive value is immutable. After they know how to index into a value, then we can show an attempt to update an immutable value directly and explain why it doesn't work.

**Comment by naomi-lgbt** [comment]
Let's start there, then. A PR which resolves this issue will update the text:

> Note that strings are immutable, which means once they are created, they cannot be changed.

To the text:

> Note that strings are immutable, which means once they are created, they cannot be changed. The variable can still be reassigned another value.
