### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by SimpliciTea** [FreeCodeCamp/freecodecamp#551]
Syntax error, unrecognized expression

from base code when the waypoint loads. <input type='text'> beneath lists doesn't complete challenge.

**Comment by QuincyLarson** [comment]
Thank you for bringing this to our attention. We'll fix this.

**Comment by QuincyLarson** [comment]
Fixed!

**Comment by SimpliciTea** [comment]
sweeeeet thanks man!
