### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Quammy93** [freeCodeCamp/freeCodeCamp#55107]
### Describe the Issue

The issue with the provided code is that the input string temp = "5 degrees" contains non-numeric characters. When you attempt to convert this string to a float using float(temp), Python will raise a ValueError because "5 degrees" is not a valid float representation.

### Affected Page

Python for Everybody: More Conditional Structures

### Your code

```
temp = "5 degrees"

# Extract the numeric part from the string
temp_numeric = ''.join(filter(str.isdigit, temp))

# Convert the numeric part to float
if temp_numeric:
    fahr = float(temp_numeric)
    cel = (fahr - 32.0) * 5.0 / 9.0
    print(cel)
else:
    print("Invalid temperature input.")

```

### Expected behavior

Extract the Numeric Part: The code will extract the numeric part of the string temp, which is "5" from "5 degrees".

Convert to Float: The code will then convert the extracted numeric string to a float, resulting in 5.0.

Temperature Conversion: The code will convert the Fahrenheit temperature (5.0 degrees Fahrenheit) to Celsius using the formula (fahr - 32.0) * 5.0 / 9.0.

Print the Result: Finally, the code will print the converted Celsius temperature.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Extract Numeric Part: Use filter(str.isdigit, temp) to extract the numeric characters from the string. filter(str.isdigit, temp) will create an iterator that includes only the digit characters from temp. ''.join(...) converts this iterator back into a string.

**Comment by gikf** [comment]
Thank you for reporting this issue.

That initial code is supposed to raise exception. Question asks which lines should be put into the `try` block to make code execute without exceptions.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.

**Comment by Dario-DC** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #55053, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
