### ISSUE TITLE
Resetting code in some new JS certification projects is not working

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#55100]
### Describe the bug
For some of the new JS certification projects resetting code/lesson is not working.

When trying to reset code/lesson in couple projects, nothing happens other than error is displayed in browser's console:
> Uncaught TypeError: e.seedEditableRegionBoundaries is undefined
> Uncaught TypeError: Cannot read properties of undefined (reading 'slice')

What's strange it happens for me only on two projects:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-palindrome-checker-project/build-a-palindrome-checker

### To Reproduce
1. Log in (or be logged in).
2. Go to affected certification project.
3. Save code.
4. Reload page.
5. Press _Reset this lesson_.
6. Press _Reset this lesson_ in the displayed modal.
7. Nothing happens, modal is still visible, in console appears error.

### Expected behavior
Being able to reset code/lesson.

### Additional context
Resetting appear to work fine in at least:
- Other new JS certification projects
- New JS practice projects
- Projects in Python certification
- Projects in Old JS curriculum

**Comment by ojeytonwilliams** [comment]
Thanks for the detailed report, @gikf. I was able to reproduce this by saving a JS project and then attempting to reset. When you do that, `seedEditableRegionBoundaries` gets wiped and subsequent resets fail. I guess the reason you saw that on only two projects was that those were the only two you'd saved.

I'll have a fix shortly - I'm just working on the tests.

**Comment by gikf** [comment]
I can confirm saving code make it starts happening for another project. 👍 

Can't say I remember saving it before, but I'm copying code back and forth when debugging campers' solutions on forums, so I must have clicked save or pressed the key shortcut once or twice.
