### ISSUE TITLE
Symmetric Difference

### ISSUE THREAD

**Issue by kemosabe73** [FreeCodeCamp/FreeCodeCamp#5511]
Challenge [Bonfire: Symmetric Difference]
Link: http://www.freecodecamp.com/challenges/bonfire-symmetric-difference

Hello guys, I am in the Bonfire: Symmetric Difference. 

Here is my problem, sym dif refers to the elements in two sets that are in either the first or second set, but not in both.

But one of the following test is:
` sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5] `

Why is 5 part of the symmetric difference when all sets have it ? Shouldn't the response be only `[1,4]`? Help will be much appreciated.

**Comment by raisedadead** [comment]
@kemosabe73  Will need to see your code for this.

IMO, Please check for help at: [Help Chat](https://gitter.im/FreeCodeCamp/Help). You will get instant help there.

If you still feel there is a bug, follow: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug first!

Hope this helps!

**Comment by ltegman** [comment]
Github issues are for bugs, not challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance. Thanks and happy coding!
