### ISSUE TITLE
JavaScript Algorithms and DataStructures (beta): Inssue with "findIndex" Method

### ISSUE THREAD

**Issue by darkpsinight** [freeCodeCamp/freeCodeCamp#55115]
### Describe the Issue

I encountered an issue while completing a task (Step 11) on freeCodeCamp. The test involves using the `findIndex` method to determine whether a task already exists in an array and then either updating it or adding a new task. The problem appears to be related to the comparison order in the arrow function passed to `findIndex`.

```js
const taskData = [];
let currentTask = {};

const dataArrIndex = taskData.findIndex((item) => currentTask.id === item.id); // This causes an error
```
When I change the comparison order, the code works without any issues:
```js
const dataArrIndex = taskData.findIndex((item) => item.id === currentTask.id); // This works fine
```
![image (1)](https://github.com/freeCodeCamp/freeCodeCamp/assets/60811247/fdc393b4-69b6-4bf2-9a49-3c6771221c17)
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/60811247/7e34a147-8545-4b6a-97f1-3b8dc6ef7630)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-11

### Your code

```js
const taskData = [];
let currentTask = {};

const dataArrIndex = taskData.findIndex((item) => currentTask.id === item.id); // This causes an error
```
and
```js
const dataArrIndex = taskData.findIndex((item) => item.id === currentTask.id); // This works fine
```

### Expected behavior

-

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Ksound22** [comment]
You didn't mention the issue caused.
