### ISSUE TITLE
CSS Media Queries and Grid Layout Adjustments

### ISSUE THREAD

**Issue by ganesh-159th** [freeCodeCamp/freeCodeCamp#55124]
### Describe the Issue

Issues Encountered:
Missing place-items Property Error:

Error Message: Your .image-wrapper selector should have a place-items property set to center.
Resolution: Added place-items: center; to .image-wrapper to center the items both horizontally and vertically within the grid cells.
Spanning Full Width of Grid Error:

Error Message: Create an .image-1, .image-3 rule and give it a grid-column property set to 1 / -1.
Resolution: Added a rule for .image-1 and .image-3 to set grid-column: 1 / -1;, making the first and third images span the full width of the grid.
Responsive Layout for 720px Error:

Error Message: Start with a @media query for only screen with a max-width of 720px. Inside, create an .image-wrapper selector and give it a grid-template-columns property of 1fr.
Resolution: Added a @media query for screens with a maximum width of 720px, setting grid-template-columns: 1fr; for .image-wrapper.
Responsive Layout for 600px Error:

Error Message: Create another @media query for only screen with a max-width of 600px. Within, create a .text-with-images rule and give it a grid-template-columns property of 1fr.
Resolution: Added a @media query for screens with a maximum width of 600px, setting grid-template-columns: 1fr; for .text-with-images.
Persistent Errors:

Despite making the above adjustments, the error persists indicating that the code may still not be correctly implemented according to the requirements

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-grid-by-building-a-magazine/step-78

### Your code

```
.image-wrapper {
  display: grid;
  grid-template-columns: 2fr 1fr;
  grid-template-rows: repeat(3, min-content);
  gap: 2rem;
  place-items: center;
}

.image-1,
.image-3 {
  grid-column: 1 / -1;
}

@media only screen and (max-width: 720px) {
  .image-wrapper {
    grid-template-columns: 1fr;
  }
}

@media only screen and (max-width: 600px) {
  .text-with-images {
    display: grid;
    grid-template-columns: 1fr;
  }
}



```

### Expected behavior

1) Centered Items in .image-wrapper:

The items within .image-wrapper should be centered both horizontally and vertically due to the place-items: center; property.
2) Spanning Full Width for .image-1 and .image-3:

The first and third images with the classes .image-1 and .image-3 respectively should span the full width of the grid due to the grid-column: 1 / -1; property.
3) Responsive Layout for 720px:

When the screen width is 720px or less, the grid within .image-wrapper should collapse into a single column layout (grid-template-columns: 1fr;).
4) Responsive Layout for 600px:

When the screen width is 600px or less, the .text-with-images should collapse into a single column layout (grid-template-columns: 1fr;).

### Screenshots

<img width="1440" alt="Screenshot 2024-06-08 at 12 57 23 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/112203904/85b5c645-ae9b-49fc-b556-e1c93962e553">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ganesh-159th** [comment]
hi @huyenltnguyen 
No, I have tried refreshing the page and resubmitting the code, but it is still showing the same error. I have modified the code again, and it is still showing the same error.

If you don't mind, could you paste this updated code and try it again?
.image-wrapper {
  display: grid;
  grid-template-columns: 2fr 1fr;
  grid-template-rows: repeat(3, min-content);
  gap: 2rem;
  place-items: center;
}

.image-1,
.image-3 {
  grid-column: 1 / -1;
}

@media only screen and (max-width: 720px) {
  .image-wrapper {
    grid-template-columns: 1fr;
  }
}

@media only screen and (max-width: 600px) {
  .image-wrapper {
    grid-template-columns: 1fr;
  }

  .text-with-images {
    display: grid;
    grid-template-columns: 1fr;
  }
}
thanks!

**Comment by ganesh-159th** [comment]
the same error 
<img width="1440" alt="Screenshot 2024-06-10 at 2 48 50 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/112203904/849c6d61-7a36-4769-99d7-2de987c0f378">
@huyenltnguyen  i have only changed that particular line only but is showing the same error

**Comment by gikf** [comment]
At the start of this step there's 162 lines, on your screen there are up to 186, that doesn't seem to be right. Try resetting the code and then adding only:

```css
@media only screen and (max-width: 600px) {
  .text-with-images {
    grid-template-columns: 1fr;
  }
}
```

**Comment by ganesh-159th** [comment]
thank you @gikf the issue has resolve  thanks for help

**Comment by ganesh-159th** [comment]
The issue referenced in #55124 has been resolved
