### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by iallfree** [FreeCodeCamp/FreeCodeCamp#5512]
![screenshot 7](https://cloud.githubusercontent.com/assets/16330271/12015981/96dcbf10-ad0a-11e5-822a-c2dfb451dd84.png)
I have a semicolon there I have new there because that is what is being asked..  and the other things listed.

**Comment by raisedadead** [comment]
What you have is:
```
var myCar = new function( "twin" ) {
  nickname.wheels = 4;
  nickname.engines = 1;
  nickname.seats = 1;
  myCar.nickname = "twin";
};
```

This has many many syntax errors. 

1. **Invalid new**
You can't do : `var myCar = new function ...`
What you should do : `var myCar = new Car()`
You can instantiate an object while declaring it like this.

2. **Invalid property** `nickname`
Please read the instructions carefully.
You are supposed to do : 
```
var myCar = new Car();
myCar.nickname = "Some Nick Name"
```

Please ask for help at [Help Chat](https://gitter.im/FreeCodeCamp/Help) for other issues in your code.

Finally it does mention in the message in the screenshot that "Is new necessary"? So please check the instructions, thoroughly. :smiley: 

Hope this helps! and Goodluck! :+1:

**Comment by ltegman** [comment]
@raisedadead is correct. Happy coding!
