### ISSUE TITLE
Typo in step 87 of Building a Cipher

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55143]
## Description

There is a typo in step 87 of Building a Cipher:

```diff
--- For example: 'Hello' + ' there!' results in 'Hello there!.
+++ For example: 'Hello' + ' there!' results in 'Hello there!'.
```

## Affected page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-87

## Changes needed

Fix the typo in the following file:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/6555db4a7b788e15795674e5.md

**Comment by PRANJALI-SANKPAL** [comment]
Is someone working on this issue? If not, I want to work on it.
