### ISSUE TITLE
Step 103 Pyramid Generator doesn't say where to write the code

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55158]
### Describe the Issue

There is no mention of where to write the code, but the tests expect the two line right below the `numbers` array declaration.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-103

### Your code

```
const numbers = [1, 2, 3];

const unshifted = numbers.unshift(5);
console.log(unshifted);
console.log(numbers);

const shifted = numbers.shift();
console.log(shifted);


```

### Expected behavior

I would expect to know where to write, or for code to be accepted anyway

### System

=

**Comment by Ksound22** [comment]
I agree that where to put the code should be in the description.

Let's make this a first-timers-only issue to encourage new and intending contributors.

**Comment by Ksound22** [comment]
# Note to First-time Contributors

Below is the part of the description that needs to be changed. What you need to do is to specify that the `shifted` variable should be declared right under the `numbers` array, and that the console log should follow it.

![Screenshot 2024-06-11 at 13 39 01](https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/7f1de4ec-e306-47e5-a8c3-865665600479)

Happy coding!
