### ISSUE TITLE
uncomment

### ISSUE THREAD

**Issue by medhatrinky** [FreeCodeCamp/FreeCodeCamp#5516]

**Comment by medhatrinky** [comment]
i m not geeting it to run

**Comment by medhatrinky** [comment]
http://www.freecodecamp.com/challenges/waypoint-comment-out-html#?solution=%3C!--h1--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0Ah2%0A%3Ch2

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need assistance. Thanks and happy coding!
