### ISSUE TITLE
HTML editor loaded empty

### ISSUE THREAD

**Issue by pmanolak** [FreeCodeCamp/FreeCodeCamp#5517]
![screen shot 2015-12-28 at 16 14 50](https://cloud.githubusercontent.com/assets/1267874/12019863/3b73e6a2-ad7e-11e5-97ee-0aae9e3ef4f5.png)
Challenge [Waypoint: Create a Bootstrap Headline](http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by ltegman** [comment]
This is intentional. You'll notice the sidebar text says:
> Now let's build something from scratch to practice our HTML, CSS and Bootstrap skills.

Thanks and happy coding!
