### ISSUE TITLE
Quick Reviewing for Past Completed Projects

### ISSUE THREAD

**Issue by GalaxyM105** [freeCodeCamp/freeCodeCamp#55182]
### Is your feature request related to a problem? Please describe.

I just finished the CatPhotoApp project, but it's been a while and I want to go back through the individual steps quickly to refresh my knowledge. It's hassle if I have to type in the answers again for each step when I just want to be able to review the current step's lesson and then immediately go on to the next step's lesson.

### Describe the solution you'd like

If I have already completed steps in a lesson, then I want to be able to go back through the lesson again without having to redo the lessons answers. I want to be able to go back and click on the first step....review the lesson information.....and then have a button inside that step's lesson that when I push it will go to the next step's lesson without having to enter the answer and have the site check that my answer is right again. 

### Describe alternatives you've considered

The alternative would be to have to type in the answers again for each step before I can go on to the next step. This is good if it is the first time I am going through a projects steps, but makes it a lot slower to refresh myself with what I have learned from the project.

### Additional context

The button would only need to be available if a user has already completed all the steps in the project.

**Comment by ojeytonwilliams** [comment]
Hi @GalaxyM105, if you have the keyboard shortcuts on, you can navigate to the next and previous lessons with `n` and `p` respectively. To turn them on, you can go to [settings](https://www.freecodecamp.org/settings) and click the button labled Enable Keyboard Shortcuts.

Does that do what you need?

**Comment by GalaxyM105** [comment]
OMG, THANK YOU!! 😄  I noticed that one has to click into the editing field for each exercise and then click CTRL+n to go to the next exercise. Definitely beats having to go back to the whole exercise list to go to the next exercise, but would be quicker if we could implement a single button action for it to go to the next or previous step without having to first click into the editor box. Or perhaps have the editor box already active when going to the next exercise. Either way, this will definitely help me greatly knowing this shortcut exists! Thank you so much! 😄

**Comment by ojeytonwilliams** [comment]
>  Or perhaps have the editor box already active when going to the next exercise

It will be if you complete a challenge, but not if you navigate with `n` and `p`. However, you can always focus the editor with `e`, so that should make life a little easier.

Anyways, the main issue seems resolved, so I'm closing this. Cheers.
