### ISSUE TITLE
Bug in Waypoint: Create a Block Element Bootstrap Button

### ISSUE THREAD

**Issue by estroid** [FreeCodeCamp/FreeCodeCamp#5518]
http://www.freecodecamp.com/challenges/waypoint-create-a-block-element-bootstrap-button

I tried to input the following code, but it wasn't accepted:

<button class="btn-block">Like</button>

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance. Thanks and happy coding!
