### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue 

### ISSUE THREAD

**Issue by GhostParticle** [FreeCodeCamp/freecodecamp#552]
You do not have to complete the image tag code for completion. As long as you type in <img src=  it allows you to go ahead to the next waypoint. It should require the tag to complete before being ready to move on. **See image
![waypoint](https://cloud.githubusercontent.com/assets/10119077/7820560/d65bc4e8-03ae-11e5-8fe7-7e60ea528a88.PNG)

**Comment by QuincyLarson** [comment]
This is now fixed. Thank you for submitting this!
