### ISSUE TITLE
Fill in the blank size doesn't fit the letters

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#55211]
### Describe the Issue

In the fill in the blank challenges, the size of the blanks are based on the number of characters in that blank. It's 11px per letter, plus an additional 11px buffer - [here's the code.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/fill-in-the-blank/show.tsx#L386) This works pretty good, but sometimes you get a word with really wide letters and it doesn't fit:

<img width="774" alt="Screenshot 2024-06-17 at 5 36 44 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/12e9c914-72d1-45e4-bf1f-3b917c1e8f95">

^ You can see `When` is a little too wide to fit because it has wide letters. Other times, you have a bunch of narrow letters like with `descriptive` in the image. That fits, but there's more space on each side than needed.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/

### Steps to Reproduce

The challenge I noticed this on is still in beta, so you will have to run the repo with upcoming changes shown to see this specific one - but you can see it in any of the fill in the blank challenges.
1. Go to http://localhost:8000/learn/a2-english-for-developers/learn-how-to-document-code-for-a-project/task-38
2. Type `When` in the first blank
3. See that one of the letters gets cut off. The `W` in firefox, the `n` in Chrome. So browsers are handling it differently.
4. Type `descriptive` in the third blank
5. See the extra space in the input before and after the word.

See the image above

### Expected behavior

The answers to fit in the blanks better.

### Solutions

I think the solution I would prefer is to make a map of the letters and their spacing and make the size of the input based on what letters are in the answers. Or perhaps just a default size of the 11px or something, and a small group of narrow letters that get maybe 8, and small group wide letters that get maybe 13 or something.

Or perhaps we could use a monospace font.

**Comment by lasjorg** [comment]
Not sure why, but this is what it looks like for me (Chrome, and in incognito).

![task-38](https://github.com/freeCodeCamp/freeCodeCamp/assets/28780271/6cc45c21-7583-47e2-8d91-177f7e674df7)

Also, the text color doesn't seem to change to white in night mode.

**Comment by a2937** [comment]
I'm only using the font for the blanks, but the point remains the same.

**Comment by ItsNehaOjha** [comment]
I think using 14 maxlength will be be a better solution.

**before :**

![befor](https://github.com/freeCodeCamp/freeCodeCamp/assets/88748867/a246c88e-6a00-4a3c-a60c-eff90046c2bb)


**after**


![devChallenge](https://github.com/freeCodeCamp/freeCodeCamp/assets/88748867/44a5f2a6-ad3a-49cd-a518-85dfe8059fc5)

**Comment by naomi-lgbt** [comment]
> I think using 14 maxlength will be be a better solution.

That's not a viable solution. That's hard-coding a value for this one specific input. They're dynamically generated we can't do that.

**Comment by naomi-lgbt** [comment]
> Or perhaps we could use a monospace font.

I think this is the way to go. Then we can reliably know the size of every character, space our inputs accordingly, and we get the added feature of visual feedback when a word is too long for that blank.

**Comment by naomi-lgbt** [comment]
> Sure it's fine for say the word "When" but for "descriptive", it's a little bigger than the blank.

This is because the spacing is configured for 11px wide characters. I'd be willing to bet that monospace font is bigger. :)
