### ISSUE TITLE
Selected Fill in the blank input gets cut off

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#55212]
### Describe the Issue

When the blanks in a fill in a blank challenge overlap vertically, the top selection box gets cut off:

<img width="767" alt="Screenshot 2024-06-17 at 5 39 59 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/27aa7b5b-5a24-43ff-ab27-562dcbe1c74f">

^ See the two blanks in the sentence are above and below one another. When you click the first blank, the blue selection box is cut off - presumably because the input below is in front of the first input.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-clarify-information-in-different-interactions/task-36

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/a2-english-for-developers/learn-how-to-clarify-information-in-different-interactions/task-36
2. Click on the first blank in the sentence
3. See the blank get cut off

### Expected behavior

The box to be visible

#### Solutions

We could adjust the spacing so the input doesn't get cut off,
or move the z-index of the input to the front when it's selected.

**Comment by lasjorg** [comment]
We might also consider increasing the `line-height`. The lines are pretty close together.

Not sure why we are using `rem` for the unit, usually `line-height` is set using unitless values, which would make the `1.5` we have on the `p` elements work much better.

Also, the font-size is set using `em` for whatever reason (unlike most if not all other `p` font styles I have seen in our CSS). Not that changing it to `rem` does anything (currently at least).
