### ISSUE TITLE
Build a Pokémon Search App Project - element id typo

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#55217]
### Describe the bug
There's typo in two hints. Instead of `#types` element it mentions `#type`.

- - -

This is something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-pokemon-search-app-project/build-a-pokemon-search-app.md

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by lasjorg** [comment]
I was making a PR for a different issue and saw this, so I added the fix to the PR.
