### ISSUE TITLE
Typecheck error in editor tests

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55232]
## Description

There is a `focusEditor()` util function we use in e2e tests.

The function previously took `page`, `isMobile`, and `browserName`, but we refactored it to only accept `page` and `isMobile`. There are a couple places that are still passing `browserName` to the function, which is causing a typecheck error:

<img width="1139" alt="Screenshot 2024-06-20 at 13 15 05" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/049ef8cd-95d4-4188-87e2-85b435c33347">

## Changes needed

Remove `browserName` from the function call in the following files:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/editor.spec.ts
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/lower-jaw.spec.ts
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/progress-bar.spec.ts

**Comment by vshws** [comment]
Can i contribute in this issue?

**Comment by Rahul-Srivastava-21** [comment]
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/155877546/d437d0c5-748b-4ad7-99ea-e7df88705c8f)
While I try to commit to the forked repo I get this error 
I don't what it is but its not letting me commit my modified files
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/155877546/b84f53e2-19cd-4766-8094-5a6abcc8d261)
