### ISSUE TITLE
Tekst doesn't render orange on a Ubuntu Phone

### ISSUE THREAD

**Issue by RDominique** [FreeCodeCamp/FreeCodeCamp#5523]
On a Ubuntu Phone, the text doesn't render orange. When I run the test, the last test "Your h1 element should be orange" fails.
First I thought it was a Ubuntu Phone bug or at least a ubuntu browser app bug but... If I copy the text in a independent html-file en browse to it, the text renders nicely orange.

![screenshot20151228_112523920](https://cloud.githubusercontent.com/assets/10077984/12023915/f8a08bc0-ad9e-11e5-89be-026ae232303b.png)

Challenge [Waypoint: Override Class Declarations by Styling ID Attributes](http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-by-styling-id-attributes) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
  
</style>
<h1 id="orange-text" class="pink-text blue-text">Hello World!</h1>

```

**Comment by ltegman** [comment]
The code from your screenshot is incorrect and is making the text green. I can't repro this in Firefox mobile -- it works fine in my tests. Given that the code you took a screenshot of is incorrect I am going to close this until someone else can repro it.

**Comment by RDominique** [comment]
Thanks for the quick follow-up. The code under 'My code:' is correct. I feel stupid to ask but what is the error in the code from the screenshot?

**Comment by AngelKyriako** [comment]
@RDominique this has happened to me as well. Did u figure a way to bypass the challenge?


@ltegman  I use mint which is also an ubuntu based OS.

`<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }

  #orange-text: {
    color: orange;
  }
  
  .pink-text {
    color: pink;
  }
  
  .blue-text {
    color: blue;
  }   
  
</style>
<h1 id="orange-text" class="pink-text blue-text">Hello World!</h1>
`

Cheers

**Comment by AngelKyriako** [comment]
I opened the browser sources and checked that the variable "common.challengeSeed" did not have the id related html/css code in it.

Hitting enter into the last character of the browser makes the mobile display to refresh and display Hello World! orange as expected.

However, the "common.challengeSeed" variable is not refreshed with the new code and thus I cannot complete the challenge

**Comment by hallaathrad** [comment]
@AngelKyriako your problem probably is just the `:`after the `#orange-text`

**Comment by AngelKyriako** [comment]
@hallaathrad thanks, I retried in windows and it worked. But I guess it worked cause I skiped : and not because of the OS

cheers
