### ISSUE TITLE
Don't use underscores in fill in the blank challenges

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#55244]
### Describe the Issue

The fill in the blank challenges use an underscore to represent blanks. [Here's an example](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/651dd5386ffb500e3f2ce47a.md)(see it in the "sentence" heading).

Underscores are part of markdown syntax, and it was causing some issues when trying to parse the markdown while working on the CAP API. See [one of the issues it caused here.](https://github.com/freeCodeCamp/freeCodeCamp/pull/55014/)

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/task-2

### Potential Solutions

In the PR I linked, we discuss using `=` instead. I think that would be a valid alternative.

This would require changing all the underscores in all the fill in the blank challenges to equal signs and updating the [view component here.](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/fill-in-the-blank/parse-blanks.ts#L22)

Not sure if `=` is the best character, we considered some others and that seemed the best.

We didn't really consider any alternatives to just changing the character, like maybe changing structure of the markdown so it doesn't use a placeholder blank characters. Maybe it could look something like this...

Instead of `Hi, _ _! I'm Tom McKenzie. It's a pleasure to meet you.`

It could be `["Hi, ", " ","! I'm Tom McKenzie. It's a pleasure to meet you."]`

So the blanks would be where the array is split or something. I don't know how much I like that from a challenge creator perspective.

**Comment by a2937** [comment]
Personally I like the idea of just changing the character. It doesn't require a lot of work to modify to get working.

For the record, here is a great sample to look at for the fill in the blank section. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/1e7ac71d8bd1e1a36447e465092855a15033a01a/curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b0b0c01616c2382ee7dc1.md#L20-L30

**Comment by a2937** [comment]
It's peak perfection with a character used to represent the blank in my humble opinion. Provided that the equal sign doesn't have a special role in markdown, I'm all for it.

**Comment by ShaunSHamilton** [comment]
I would say the fact escaping the underscore did not work is pointing out a bigger issue with our parsing.

I suggest we get the parser workflow working as expected, because we will have challenges with more Markdown syntax in them we do not want transformed. E.g. the upcoming backend stuff teaches some Markdown.

**Comment by ojeytonwilliams** [comment]
> I would say the fact escaping the underscore did not work is pointing out a bigger issue with our parsing.

That's true, but using a symbol that's less likely to be interpreted by Markdown parsers makes it easier to write lessons. `=` does mean something, but it seems way less likely that a lesson would have equals at all, let alone have outside of a code block.

Fixing the parser workflow is also important, but I think it's independent.

**Comment by naomi-lgbt** [comment]
> In the PR I linked, we discuss using = instead. I think that would be a valid alternative.

Agreed, I think this is the route to go.

**Comment by a2937** [comment]
This is precisely **_not_** the route to go with. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/ee903593029009a00735709ed263e6cc85d9b294/curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-use-basic-programming-vocabulary-in-conversations/662b7d0fda698d0d84ac67f4.md

In Task 27 of the Learn How To Use Programming Vocabulary In Conversations module, an equal sign is used to explain how to define a variable inside of Python.  If we replace all the blanks with equal signs, the challenge will not be parsed correctly due to the extra already existing equal sign.

**Comment by a2937** [comment]
The BLANK option still seems variable at the moment.

**Comment by naomi-lgbt** [comment]
Honestly, we don't need that second sentence in that challenge at all.

**Comment by naomi-lgbt** [comment]
> The BLANK option still seems variable at the moment.

I do like this, as long as it's case sensitive. We're likely to use `blank` in a sentence, but `BLANK` is pretty darn uncommon.
