### ISSUE TITLE
Move the portfolio edit functionality from the settings page to the portfolio

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#55258]
### Is your feature request related to a problem? Please describe.

To improve the user experience, the edit functionally should be as close to the section that it is editing. As a result, the following sections should be ported from settings page to a modal that opens by clicking the edit button on the portfolio page:

- Username
- Personal Information
	- name
	- location
	- picture
	- about
- Your Internet Presence
	- Github
	- Twitter
	- Linkedin (x)
	- Personal website

<img width="522" alt="Screenshot 2024-06-21 at 4 53 07 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/77d0a7b1-d733-4a1a-b8b1-19a7943954e3">

**Comment by sushma1031** [comment]
Hi, could I work on this?

**Comment by rain64x** [comment]
Can I get this task assigned to me?

**Comment by theSamyak** [comment]
> Can I get this task assigned to me?

"Help wanted" labeled issues are open to everyone. You don't need permission to work on them.
