### ISSUE TITLE
Add comments on completed parts of code

### ISSUE THREAD

**Issue by Alexeigithubproject** [freeCodeCamp/freeCodeCamp#55267]
### Is your feature request related to a problem? Please describe.

I am in the Javascript section and I keep losing track of the project i am trying to do. Some steps will take me a few minutes to solve, and when i finally complete them and return to the already written code, i forget what the functions that were previously created do, or will do.

### Describe the solution you'd like

Adding a few comments (//) on completed parts of the code, for example, functions, just as a reminder of what they are doing would help with that.

### Describe alternatives you've considered

Adding a few comments (//) on completed parts of the code, for example, functions, just as a reminder of what they are doing would help with that.

### Additional context

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/171625546/f3206dfb-5790-4800-a6d3-fe3a871e3004)

**Comment by ilenia-magoni** [comment]
what kind of comments do you suggest? can you provide some examples?

**Comment by Vaishnavi-Sharma2105** [comment]
@ilenia-magoni I am new to open Source, here, according to the problem/issue that is faced by @Alexeigithubproject, I suggest that a short comment or pseudo code can be added to the large functions so that the person can keep a track of what is happening.

**Comment by ilenia-magoni** [comment]
@Vaishnavi-Sharma2105 those are still not examples, can you provide an example of this?

**Comment by hbar1st** [comment]
i really like this suggestion as well as it will help campers who are returning to completed projects recall important aspects in the project. For example, just before the switch statement in the Date Formatter project we could have a comment like this:
// checks the user's selected date format and updates the presented date

**Comment by gikf** [comment]
Comments are not exactly the place for that. Ideally _what is happening_ should be clear from the code itself.

> i really like this suggestion as well as it will help campers who are returning to completed projects recall important aspects in the project. For example, just before the switch statement in the Date Formatter project we could have a comment like this: // checks the user's selected date format and updates the presented date

In this specific case, it would be better to extract the callback function to give it descriptive name instead.

**Comment by naomi-lgbt** [comment]
Comments aren't the way to go, here. We should either improve the code's readability (and therefore teach best practises), or improve the instructions in steps.

Learning to read code is an essential skill too, and this gives a great way to practise that. 😉
