### ISSUE TITLE
 Suggestion to Improve Visual Appeal by Removing Border from Login Page

### ISSUE THREAD

**Issue by ItsNehaOjha** [freeCodeCamp/freeCodeCamp#55268]
### Describe the Issue

The login page currently features a border around the login form, which does not align with modern design aesthetics. This border gives the form a dated look and detracts from the overall visual appeal of the page. Removing this border will streamline the design, providing a cleaner and more contemporary user interface.

### Affected Page

SignIn page 

### Steps to Reproduce

1. Go to [freeCodeCamp](https://www.freecodecamp.org/fccc317f0ff-f683-4999-8b25-c4901a7cfef1)
2. Click on '[SignIn](https://auth.freecodecamp.org/u/login/identifier?state=hKFo2SBCalNpaWdpSjhmV05sWU5mYVhTdWU2Y2dYcEhNeTdvRaFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIFdUOHkwVHhRdXF4d3NvVWFjSEJ5ZzJpc183SThRa0JTo2NpZNkgYVVEdjlqVnFUZnhCUkUxbDYwTkE1QWY3eVRDR0U0Y3k)'
3. See the border

### Expected behavior

The login form should be presented without  a border, creating a more streamlined and visually appealing interface

![after login](https://github.com/freeCodeCamp/freeCodeCamp/assets/88748867/a761057b-5a8e-48bf-9cf2-692c01da05c6)

### Screenshots

login page before:

![login](https://github.com/freeCodeCamp/freeCodeCamp/assets/88748867/637823a1-4cb7-4b8b-ab3d-dddec84b560f)

login page after:

![after login](https://github.com/freeCodeCamp/freeCodeCamp/assets/88748867/59e25ed2-3641-46d8-93ad-118e45563a91)

### System

Device: Laptop
OS: Windows 10
Browser: Chrome
Version: 91

### Additional context

Removing the border will enhance the user experience by making the login page look cleaner and more inviting. This small change can significantly improve the visual impact of the login page and align it with current design standards.

**Comment by brandon-crisp** [comment]
Pretty certain this is managed via the authentication prompt builder on Auth0 (it looks like an Auth0 login, esp. with the state in the URL), so this wouldn't be something to be fixed via code here on GitHub.

**Comment by rohan220217** [comment]
@brandon-crisp I tried to fix it but the sign-in page redirect me to Auth0, So I think the login UI doesn't depend on this code.

**Comment by naomi-lgbt** [comment]
The border aligns with our [command-line chic design](https://design-style-guide.freecodecamp.org/), and is in parity with modals on our primary site.
