### ISSUE TITLE
Missing backticks

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55278]
Missing backticks around `transform`:
https://github.com/freeCodeCamp/freeCodeCamp/blob/e5a5a308faebe00eb72353de172103dded6f90a9/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646de5dc8988076a1d992afd.md?plain=1#L10

Same here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/e5a5a308faebe00eb72353de172103dded6f90a9/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646de8478d6f796bfbdccfb2.md?plain=1#L10

`passport-github` needs to be wrapped in backticks:
https://github.com/freeCodeCamp/freeCodeCamp/blob/76cd4ecd35902129c2703b923d2c41034371f630/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication-ii.md?plain=1#L38

same here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/76cd4ecd35902129c2703b923d2c41034371f630/curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication-ii.md?plain=1#L53

`label` should be wrapped in backticks:
https://github.com/freeCodeCamp/freeCodeCamp/blob/76cd4ecd35902129c2703b923d2c41034371f630/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fab8367d35de04e5cb7929.md?plain=1#L10

`label` and `fieldset` should be wrapped in backticks:
https://github.com/freeCodeCamp/freeCodeCamp/blob/76cd4ecd35902129c2703b923d2c41034371f630/curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60fab8367d35de04e5cb7929.md?plain=1#L18

**Comment by ilenia-magoni** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. See the first post for the list of files that you should be looking at to work on a fix.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by Rahul-Srivastava-21** [comment]
@ilenia-magoni I have made the required changes and all checks have been passed 
Please have a look into this.
