### ISSUE TITLE
Update GitHub gifs in intro waypoints to reflect new UI

### ISSUE THREAD

**Issue by firstdoit** [FreeCodeCamp/FreeCodeCamp#5527]
GitHub has a new UI for repos, and we need to re-record some gifs. For example: http://www.freecodecamp.com/challenges/waypoint-create-a-github-account-and-join-our-chat-rooms

**Comment by marhyorh** [comment]
@firstdoit I don't think that would be necessary. The main point of that waypoint is to let users create a github account and it's not difficult to do that.

**Comment by firstdoit** [comment]
Indeed, it's not a pressing concern. I just preferred to add this reminder so I can do it later :)

**Comment by marhyorh** [comment]
Okay :+1:

**Comment by bugron** [comment]
cc @QuincyLarson

**Comment by firstdoit** [comment]
Sorry for taking such a long time :grimacing:

**Comment by QuincyLarson** [comment]
Please note I recently updated the GitHub onboarding (I didn't realize this issue existed so I didn't reference it). It now shows email confirmation and everything.

**Comment by firstdoit** [comment]
Hi, @QuincyLarson :) The original problem reported remain, however - the current GIF shows the old Github interface.
