### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55275]
One "not" should be removed:
https://github.com/freeCodeCamp/freeCodeCamp/blob/e5a5a308faebe00eb72353de172103dded6f90a9/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da4b16937be43ba24c63d.md?plain=1#L59

---

It should be variable, singular:
https://github.com/freeCodeCamp/freeCodeCamp/blob/e5a5a308faebe00eb72353de172103dded6f90a9/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/646d39c156fe94b7482c3ab6.md?plain=1#L26

---

It should be "its", without the apostrophe:
https://github.com/freeCodeCamp/freeCodeCamp/blob/e5a5a308faebe00eb72353de172103dded6f90a9/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/646d4813c17b37d1e261a566.md?plain=1#L10

**Comment by ilenia-magoni** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by rohan220217** [comment]
@ilenia-magoni pls review and merge the PR #55277

**Comment by sidharthaA** [comment]
@ilenia-magoni Please let me know if this PR needs any changes. It is my first contribution to open source. Had fun going through all the documentation @https://contribute.freecodecamp.org/how-to-open-a-pull-request/ and setting up the project using gitpod.io as described @https://contribute.freecodecamp.org/how-to-setup-freecodecamp-locally/.

Please review and merge my PR if everything looks all right.
Thanks!

**Comment by Prasad-JB** [comment]
Hi there! I’d love to help by fixing these typos in the JavaScript curriculum. Could you please assign this issue to me? I’ll ensure the changes respect formatting and guidelines. Thank you!

**Comment by majestic-owl448** [comment]
@Prasad-JB this issue has been completed in June of 2024, you are a bit late.

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
