### ISSUE TITLE
Typo "binairy"

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55276]
https://github.com/freeCodeCamp/freeCodeCamp/blob/e5a5a308faebe00eb72353de172103dded6f90a9/curriculum/challenges/english/10-coding-interview-prep/data-structures/add-a-new-element-to-a-binary-search-tree.md?plain=1#L17

**Comment by ilenia-magoni** [comment]
Thanks for opening this issue.

This looks like something that can be fixed by "first-time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

https://github.com/freeCodeCamp/freeCodeCamp/blob/e5a5a308faebe00eb72353de172103dded6f90a9/curriculum/challenges/english/10-coding-interview-prep/data-structures/add-a-new-element-to-a-binary-search-tree.md

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by rohan220217** [comment]
I have fixed in my #55277 PR
