### ISSUE TITLE
semicolon or semi-colon: unify the curriculum

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55297]
Can we choose one and stick to it? There are both throughout the curriculum.

**Comment by bbsmooth** [comment]
All the grammar sites seem to use semicolon. Besides, why type an extra character if you don't have to?

**Comment by lasjorg** [comment]
My vote is for semicolon as well.

**Comment by mmatsumoto1026** [comment]
Some investigation was made about the use of "semicolon" and "semi-colon".

1. Referencing dictionalies

 - [Longman English dictionary](https://www.ldoceonline.com/Letters%20&%20punctuation-topic/semicolon) : "semicolon" and "semi-colon" are both introduced, but in Examples from the Corpus, "semicolon" is solely used.
 - [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/semicolon) : "semicolon" is introduced with referencing the word and "semi-colon" is also described in the writing for punctuation.

2. In open source communities

 - [Wikipedia](https://en.wikipedia.org/wiki/Semicolon) largely uses "semicolon". (In Wiki, "semi-colon" is a quote from the world of [broadcasting](https://www.bbc.co.uk/worldservice/learningenglish/grammar/learnit/learnitv55.shtml) of [journalism and literature](https://en.wikipedia.org/wiki/Semicolon#cite_ref-36), not the realm of technology)
 - [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement) uses "semicolon".

3. In programming language documentations

 - [Python 3.12.4 documentation](https://docs.python.org/3/search.html?q=semicolon) uses "semicolon".
 - [ECMA-262 14th Edition](https://262.ecma-international.org/11.0/#sec-rules-of-automatic-semicolon-insertion) uses "semicolon".
 - [c++ reference documentation](https://en.cppreference.com/w/c/language/statements) uses "semicolon".
 - In Java documentation, although "semi-colon" is used in [some parts](https://docs.oracle.com/en/java/javase/22/jmx/getting-started.html), it seems that "semicolon" is generally used.

Therefore, it seems that our campers will generally see the "semicolon" in the places they learn the programming.

**Comment by ilenia-magoni** [comment]
I'm opening this for contribution. All instances of semi-colon should be replaced with semicolon.

This could probably be resolved with a search and replace command, so I remind: change only files in the English folder, not other language folders.

**Comment by gagan-bhullar-tech** [comment]
@ilenia-magoni created PR. Please review.

**Comment by ilenia-magoni** [comment]
@gagan-bhullar-tech please do not ping maintainers to ask for review
