### ISSUE TITLE
Spreadsheet - Step 86: Clarify object access

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#55294]
### Describe the Issue

This part of the text:

> return the function found at the `fn` property of your spreadsheetFunctions object

Can be misinterpreted as `fn` being a property on the spreadsheetFunctions object.

At this point in the curriculum, campers should know that parameters are variables and as such the identifier is not the name of a property. Nevertheless, I suggest we change the text.

I know it is more verbose. I'm also not sure if calling `fn` a variable to help jock the memory of the camper is a good idea or not.

> The `fn` parameter will be passed the name of a function, such as `"SUM"`. Update `apply` to implicitly return the function from your spreadsheetFunctions object using the `fn` variable as the key for the object access.
> 
> Remember that `fn` might not contain a lowercase string, so you'll need to convert it to a lowercase string.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-86

### Your code

```



```

### Expected behavior

Don't imply `fn` is a property on the object.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-javascript-programming-by-building-a-spreadsheet-step-86/696840

**Comment by naomi-lgbt** [comment]
Yes, let's update the text as noted above.
