### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue 

### ISSUE THREAD

**Issue by Yuripac** [FreeCodeCamp/freecodecamp#553]
You can explain how put more classes in the same element. And I found a bug. The exercise can be completed without the .blue-text's style. 

ps: I love FreeCodeCamp s2

**Comment by terakilobyte** [comment]
The only way I can reproduce this is to add the class `blue-text` to the markup without actually implementing the class. Is this what you meant?

**Comment by QuincyLarson** [comment]
Thanks! We've added explanation for how to add multiple classes to a single element.
