### ISSUE TITLE
Expand introductory JS project's array steps

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#55319]
My gf is going through the JS curriculum, and the first review project immediately starts off with constructing a loop to iterate through an array.

The introductory project teaches a LOT of loops, but only touches on array indices in a couple of steps. We may want to expand those steps - perhaps something like adding another loop instruction to loop through an array?

**Comment by naomi-lgbt** [comment]
Maybe also include a `for...of` loop? Thought I taught that in there but apparently not.

**Comment by ilenia-magoni** [comment]
> Maybe also include a `for...of` loop? Thought I taught that in there but apparently not.

it's in there, but it may need reinforcement like the other things
