### ISSUE TITLE
Random Background Color Changer Step 3 placement of method

### ISSUE THREAD

**Issue by Supravisor** [freeCodeCamp/freeCodeCamp#55312]
### Describe the Issue

A camper had an issue with code not passing due to the placement of the Math.floor() static method.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-debugging-by-building-a-random-background-color-changer/step-3

### Your code

```
function getRandomIndex() {
   console.log(Math.floor(Math.random() * darkColorsArr.length));
}
```

### Expected behavior

Both
```
   console.log(Math.floor(Math.random() * darkColorsArr.length));
```
and
```
   console.log(Math.floor(darkColorsArr.length * Math.random()));
```
should pass the challenge.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Here is a link to the forum post.
https://forum.freecodecamp.org/t/learn-basic-debugging-by-building-a-random-background-color-changer-step-3/694680/2

**Comment by suraj-9849** [comment]
I would like to work on this issue

**Comment by gagan-bhullar-tech** [comment]
Started looking into this.
