### ISSUE TITLE
[Luhn Algorithm] Elaborate how string slicing works

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55329]
## Description

In step 10 of Luhn Algorithm, we teach campers how to create a substring using the `[]` operator. I think the explanation is a little short and could improved by:
- Adding comment next to each example, showing the result of each `[]` operation (we are currently communicating the value via the variable name, but I don't think it's clear enough)
- Mention that the starting index is inclusive, and the ending index is exclusive

Additionally, I think we could: 
- Change `string[x:y:h]` to `string[start:stop:step]` to have the syntax more self-descriptive
- Mention that the default value of `step` is 1

## Affected page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm/step-10

## Suggested changes

Perhaps the description should be changed to:

````md
You have accessed elements (characters) of a string before, using the index operator `[]`. You can also use the index operator to access a range of characters in a string with `string[start:stop:step]`:

```python
my_string = 'camperbot'
my_string[0:6] == 'camper' # True
my_string[0:6:3] == 'cp' # True
```

Where `start` is the starting index (inclusive), `stop` is the ending index (exclusive), and `step` is the amount of characters to skip over. If not specified, `step` is default to 1.

Create a variable named `card_number_reversed` and assign it the value of the first 4 characters of `card_number`.
````

**Comment by Dario-DC** [comment]
Different project but same kind of example: https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-recursion-by-solving-the-tower-of-hanoi-puzzle/step-3

I remember we decided not to use `start, stop, step` because of translations, but using them in the code example and then explain what they mean is fine :+1:

**Comment by naomi-lgbt** [comment]
@fhsinchy @Dario-DC are we able to open this up for contribution?

**Comment by Dario-DC** [comment]
Personally, I'd prefer to change the snippet into the following:

```py
my_string = 'camperbot'
my_string[0:6] == 'camper' # True
my_string[0:6:3] == 'cp' # True
```
I agree with all the rest.

**Comment by fhsinchy** [comment]
> Whoops, sorry. I just noticed that Farhan is assigned to the issue.
> 
> @fhsinchy Are you working on this or could we mark this one up-for-grabs?

Yeah please mark this as up for grab @huyenltnguyen.
