### ISSUE TITLE
Steps 23, 24, and 25 of the date formatter project can be combined

### ISSUE THREAD

**Issue by Ksound22** [freeCodeCamp/freeCodeCamp#55331]
### Describe the Issue

In the steps 23, 24, and 25 of the date formatter, campers are asked campers to use the `split()`, `reverse()`, and `join()` methods on a `formattedDate` variable.

I think these steps should be combined, since steps 18 through 22 detailed how to use those methods and chain them.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-23, https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-24, https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-25

### Your code

N/A

### Expected behavior

The steps should be combined

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by naomi-lgbt** [comment]
Agreed - opening for contribution.

**Comment by patrickwcode** [comment]
I will look into this and give it my best shot.
