### ISSUE TITLE
Font Awesome Waypoint: Including Font Awesome CDN?

### ISSUE THREAD

**Issue by ScottBrenner** [FreeCodeCamp/FreeCodeCamp#5535]
For [this](http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons) waypoint, shouldn't it be mentioned that you have to include Font Awesome's CDN to add the icons?

**Comment by qmikew1** [comment]
Font Awesome question is interesting, I think somewhere in the curriculum there's "a behind the scenes comment" re: bootstrap
(i.e.,sort of separate but interrelated -and, we've included it for you.)  
The [repo](https://fortawesome.github.io/Font-Awesome/) directs to [this](http://www.bootstrapcdn.com/#fontawesome_tab) CDN
And other places will link to [cloudflare](http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css)
Might be difficult to recommend a single source; however, would agree that it could be confusing to a new user.

**Comment by ScottBrenner** [comment]
Yeah, I remember the behind-the-scenes Bootstrap CDN. But the Font Awesome CDN has to be included separately, right?

**Comment by qmikew1** [comment]
I'm not a maintainer. Just another camper commenting on your comment. I agree that it could be confusing to some folks; just with the qualifier that there could possibly be multiple CDN (and that could confuse folks more) sources. Just, partially,  echoing sentiment.

**Comment by dabowheel** [comment]
Font Awesome is included automatically. You don't need to include it yourself.

**Comment by qmikew1** [comment]
I think the original comment (yes, it's true that a lot of this stuff is included for user 'behind the scenes') was directed at situation when one starts to create things outside of the exercises, and needs to actually include external references what have you.

**Comment by ltegman** [comment]
I agree that this should be mentioned in much the same way that we handle it in the bootstrap lessons.
