### ISSUE TITLE
Cash Register - `--after-user-code--` is not evaluated before tests in production

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#55356]
### Describe the bug
Code in the `--after-user-code--` doesn't seem to be evaluated in production for Cash Register project.

- (Edit)This appear to be related to the code saving / resetting.
- In development there isn't such issue. Including building production client and serving it.
- This is actually the only challenge from the _new_ challenges that is using `--after-user-code--`. Old challenges are working fine when using `--after-user-code--`. Both when names start with `_` and not. Initially I though the `_` might be somehow deciding factor, but there isn't any other _new_ challenge to check that.
- After adding `_randomNumber` function to user code, error moves _normally_ to the next used in test non-defined variable - `_money` and then `_denomRegexes`.

### To Reproduce
1. (Be logged in, and have previously saved code for project).
2. Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register
3. Enter solution. Example: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md#--solutions--
4. Run tests.
5. See `[ReferenceError: _randomNumber is not defined]` errors.

### Expected behavior
Code present in the `--after-user-code--` should be evaluated after the user code, and before running tests.

### Additional context
- (Edit) When logged out there's different error, or no errors at all(?!).
- This might be somehow related to saving / resetting code.

**Comment by ojeytonwilliams** [comment]
Thanks again for the detailed report, @gikf!

You were dead right about the issue: it's due to the fact that saved challenges don't include head or tail (aka `--before-user-code--` and `--after-user-code--`) and we were just using them in place of challengeFiles (which does have that stuff).

**Comment by lasjorg** [comment]
I have marked this as a showstopper seeing as it is affecting camper's ability to complete a certificate project.

It would be nice to get the fix in as soon as possible, so the forum isn't filled with support threads for this.

**Comment by janicesiega** [comment]
13. When price is less than the value in the #cash element, total cash in drawer cid is greater than the change due, individual denomination amounts allows for returning change due, and the #purchase-btn element is clicked, the value in the #change-due element should be "Status: OPEN" with required change due in coins and bills sorted in highest to lowest order.
