### ISSUE TITLE
Update the rendering logic of block tags

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55367]
## Description

I noticed that some grid-based blocks are having an empty `<div className='tags-wrapper'>`:

<img width="1063" alt="Screenshot 2024-06-28 at 22 25 43" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/b762de25-d221-452a-90d6-b9fea06ff2e0">

The following rendering logic should be updated so that the div is also hidden if `!isAudited`:

https://github.com/freeCodeCamp/freeCodeCamp/blob/3a20e90e5d36e82d85a89bb96bbc6275791c6684/client/src/templates/Introduction/components/block.tsx#L274-L283

## Affected page

I think the issue exists in all grid-based projects on the English version of /learn. Here is one: https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app.

**Comment by lasjorg** [comment]
You just want the div inside the conditional?

Is `tags-wrapper` only used for the "Certification Project" tag?

**Comment by shivansh84ya** [comment]
assign this issue to me

**Comment by shivansh84ya** [comment]
assign #55367 issue to me
