### ISSUE TITLE
Wrong condition specified in documentation of Expense Tracker, Step 25, Scientific Computing with python 

### ISSUE THREAD

**Issue by mohammmmmmmmmmed** [freeCodeCamp/freeCodeCamp#55376]
> A while loop is another kind of loop that runs a portion of code until a specified condition is **True**:

>Example Code
>`while condition:`
>`     <code>`

>Below the expenses list, create a while loop. Use True for the condition, and print the string '\nExpense Tracker' inside the loop body to show the title of the program.

Highlighted portion should instead be changed to False, since while loops terminate when their condition is false.

**Comment by Supravisor** [comment]
As an alternative

"A while loop is another kind of loop that runs a portion of code until a specified condition is <b>`met`</b>:"

**Comment by kosenijr** [comment]
My suggestion for clarity

"A while loop is another kind of loop that runs a portion of code`, repeatedly, as long as` a specified condition `is met`."

**Comment by Dario-DC** [comment]
I would go with:
```md
A `while` loop is another kind of loop that runs a portion of code as long as a specified condition is `True`. The loop terminates when the condition becomes `False`:
```
