### ISSUE TITLE
Challenges still accept code even when it's missing a closing tag

### ISSUE THREAD

**Issue by SoraTheWeirdo** [freeCodeCamp/freeCodeCamp#55384]
### Describe the Issue

The form element is missing a closing tag, but the challenge still accept it and let me move onto the next step

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-forms-by-building-a-registration-form/step-11

### Your code

```html
  <body>
    <h1>Registration Form</h1>
    <p>Please fill out this form with the required information</p>
    <form action="https://register-demo.freecodecamp.org">
  </body>
```

### Expected behavior

It should respond with "You are missing the closing tag", instead of accepting it and letting you move onto the next step

### Screenshots

![344431262-30cc7f10-3d3c-4547-a21a-17b19fe6f25a](https://github.com/freeCodeCamp/freeCodeCamp/assets/112508103/b6315476-880c-4c57-9721-73a1b3abd6fb)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

According to @lasjorg 
> I'm guessing the browser is auto closing it, and we don't have a regex test for it.
It should result in a valid form element, because the browser will close it. However, the element technically does not have any "Tag omission" so it should have an end tag in the HTML (even if it gets added to the DOM by the browser).

**Comment by ilenia-magoni** [comment]
This is no more the first project, it would become regex galore, and when possible instead we prefer to not use regex, so fixing all these tests is probably not worth it

**Comment by lasjorg** [comment]
We don't need to keep testing for closing tags everywhere. But this challenge is about building a form, so having one test to check the initial form element is created correctly doesn't seem unreasonable.

**Comment by naomi-lgbt** [comment]
Agreed, this seems like a good reason to regex test a closing tag. Opening for contribution.
