### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by iallfree** [FreeCodeCamp/FreeCodeCamp#5539]
![screenshot 8](https://cloud.githubusercontent.com/assets/16330271/12037887/cb87d9e8-ae18-11e5-9ab4-60bea69d2c3d.png)

the code runs.. I moved on to the next waypoint. I am not asking for help. I am just seeing there are the x near each of these parameters and it was written correctly

**Comment by iallfree** [comment]
![screenshot 9](https://cloud.githubusercontent.com/assets/16330271/12037906/fdf5228c-ae18-11e5-98e3-1e222c28934f.png)

actually.. here is a better view that all the codes were running correctly.. but this is showing up..

**Comment by raisedadead** [comment]
First thing : Please refer [Bug Help Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) and [Creating a new Issue](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue) guidelines, while posting a bug.

Can you please post your passing code here too? I can't seem to reproduce this by guessing the code in the screenshot.

Thanks!

**Comment by iallfree** [comment]
That is the passing code that you see in the picture. ;)

**Comment by BerkeleyTrue** [comment]
@iallfree Paste your code here or this issue will be closed.

The guidelines @raisedadead posted above are here to help you get the help you need as quickly as possible.

**Comment by iallfree** [comment]
@BerkeleyTrue  I posted a photo of what the code was doing. It is there. It is something wrong on the sites. End. Nothing on my code processing error.  The code above in the photo IS the passing code.  And I read the guidelines.. and offered the best of my knowledge What I thought was a "bug" if you guys don't see it. than it's not my problem.
