### ISSUE TITLE
Challenge seems unclear what the objectives and rules are

### ISSUE THREAD

**Issue by Lewiscowles1986** [FreeCodeCamp/FreeCodeCamp#5540]
Challenge [Bonfire: DNA Pairing](http://www.freecodecamp.com/challenges/bonfire-dna-pairing) has an issue.

The text is completely unclear as to what the task is, please revise

```
its quite simple, you get a string, and for every character of the string you need to put that character with its pair in an array
so if a character is an a
you should put ['A', 'T'] in the array
if it is t, ['T', 'A']
if it is G, ['G', 'C'], and if it is C, ['C', 'G']
```
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function pair(str) {
  return str;
}

pair("GCG");

```

**Comment by QuantumNinja92** [comment]
you'll get series of characters which is a string, for every character in the string you need to pair it with the appropriate DNA character, it if is A pair it with T, and if it is T pair it with A, the same goes for C and G

**Comment by SaintPeter** [comment]
We have actually received very few complaints about this specific bonfire.  I can't tell if you're proposing alternate text or if that's the text that is there?

Keep in mind that "in the real world" you will sometimes be given problems in domains you are not especially familiar with.  Going out an researching and applying that knowledge is a real programmer skill.

I'd like to see what text addition you'd propose.

**Comment by Lewiscowles1986** [comment]
the text shared is how someone on the help explained the task, it seems a lot more clear-cut, as the text next to the task didn't make much sense.

**Comment by Lewiscowles1986** [comment]
Also btw, solved in under 5 minutes once I understood the task, the problem is that if the task is unintelligible, you cannot pass it. The text I pasted was what was shared to me by a member of the community. It's incredibly clear what the task is from that (can't say the implementation was too hard to come up with once I knew what the goal was)
