### ISSUE TITLE
The lesson accepted a wrong answer

### ISSUE THREAD

**Issue by jessemetalpoet** [FreeCodeCamp/FreeCodeCamp#5541]
On the lesson "Waypoint: Change the font size of an element" I noticed that i put in a code that looked wrong but I wasn't sure if it was correct or not.  The code I put in is located below:

This is what I put but the lesson accepted it and moved on to the next one:

<style>
  .red-text {
    color: red;
    font-size:16px;
  }
</style>

This is the correct code which is shown in the next lesson:

<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
  }
</style>

**Comment by panther911** [comment]
Your code works because both P elements have the .red-text class. The first solutions sets all elements with the class .red-text to 16px , including the h2 element. If you remove the red-text class from your p elements, your solution will not be accepted.

**Comment by jessemetalpoet** [comment]
Awesome thanks!
