### ISSUE TITLE
Upgrade React InstantSearch to v7

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55410]
## Description

We are using React InstantSearch v6 for the search bar on /learn, and this version is [deprecated](https://www.algolia.com/doc/deprecated/instantsearch/react/v6/api-reference/instantsearch).

Migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/#migrate-from-react-instantsearch-v6-to-react-instantsearch-v7.

**Comment by a2937** [comment]
I see a potential issue in the form of focus buttons. The hook replacement that was suggested only works with function based components, not class based.

**Comment by a2937** [comment]
Months later I have a question. Do the focus shortcut keys actually do anything? The keycodes seem unusual.
