### ISSUE TITLE
Bonfire: Sorted Union not enough parameters

### ISSUE THREAD

**Issue by Rudeclis** [FreeCodeCamp/FreeCodeCamp#5542]
The function for Sorted Union uses the parameters arr1 ,arr2 and arr3, but the last test has 4 arrays.

**Comment by raisedadead** [comment]
The instructions state that the function can take two or more arguments (variable no of parameters).
For this, you need to use the `arguments` object : Refer [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) also mentioned in the instructions as useful links.

Just a hint, something like:
```javascript
function someFunction(){
    var args = arguments; // array of parameters
    var firstArg = arguments[0]; // or first parameter
...
}

// all the below are valid.
someFunction(1,2,3);
someFunction(1,2,3,4);
```

The `arguments` object is inbuilt into JavaScript functions, please refer the documentation linked above.

Hope this helps!

If you still get stuck don't hesitate to ask for assistance @ [Help Chat](https://gitter.im/FreeCodeCamp/Help)

**Comment by Rudeclis** [comment]
Ah right it's the point of the Bonfire. 
I guess my method was technically speaking a failure then. Thanks for clearing that up
