### ISSUE TITLE
Build Football Team Cards project description - Mentioning switch statements as if they're new

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55432]
### Describe the Issue

The description of the project to build football team cards in the js beta curriculum says:
>In this project, you will build a set of football team cards and learn about nested objects, object destructuring, default parameters, event listeners, and switch statements.

But switch statements were introduced in the date formatter project (step 16, 17). 
I think the description should be modified therefore to not mention learning switch statements.

I haven't actually done this project, so I don't actually know if it re-teaches switch statements or not.
(it would be nice if the date formatter description mentioned learning about switch statements though)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-1

### Your code

N/A

### Expected behavior

N/A

### System

N/A

**Comment by lasjorg** [comment]
I don't really get the title of this challenge, what "modern javascript methods" is it referring to, is it just the `Object.freeze`? Because surely both map and filter has already been taught at this point.

I'm also not sure the switch is really needed. It seems a little verbose and a lot of boilerplate.

```js
playersDropdownList.addEventListener("change", (e) => {
  playerCards.innerHTML = "";

  switch (e.target.value) {
    case "nickname":
      setPlayerCards(players.filter((player) => player.nickname !== null));
      break;
    case "forward":
      setPlayerCards(players.filter((player) => player.position === "forward"));
      break;
    case "midfielder":
      setPlayerCards(
        players.filter((player) => player.position === "midfielder")
      );
      break;
    case "defender":
      setPlayerCards(
        players.filter((player) => player.position === "defender")
      );
      break;
    case "goalkeeper":
      setPlayerCards(
        players.filter((player) => player.position === "goalkeeper")
      );
      break;

  default:
    setPlayerCards()

  }
});
```

Compared to say:

```js
playersDropdownList.addEventListener("change", (e) => {
  playerCards.innerHTML = "";
  const optionValue = e.target.value;
  
  const filteredPlayers = players.filter((player) => {
    return optionValue === "nickname"
      ? player[optionValue] !== null
      : player.position === optionValue;
  });

  filteredPlayers.length ? setPlayerCards(filteredPlayers) : setPlayerCards();
});
```

**Comment by naomi-lgbt** [comment]
Let's go ahead and remove switch statements from the description and the first step.

**Comment by lasjorg** [comment]
I feel like the switch used in the code is because the idea of the challenge, among other things, was to teach it. It takes up a lot of the total code.

Not mentioning it, doesn't really change that fact. Not unless, we remove the switch from the code as well.

**Comment by naomi-lgbt** [comment]
> Not mentioning it, doesn't really change that fact. Not unless, we remove the switch from the code as well.

That's a fair point. I'd be fine rewriting the challenge to use the example you shared earlier.

**Comment by AshmitGupta** [comment]
Hi! I am a new, first time contributor. Can I put up a PR for this issue? Seems like a simple fix, just removing 'switch statements' from description and first step

**Comment by lasjorg** [comment]
It could be seen as reinforcement.

I'm not saying we _have to_ remove it, I'm just saying it seems like part of the point of this challenge was to teach the switch, which is why it is in the description and the code.

Not sure how often we use switch statements, but this project is definitely reinforcing it. So we might want to keep it just for that reason. This also isn't the first time we teach `map` and it is in the description as well.

Maybe that could be it, reinforcement.

> This project will cover concepts like, default parameters, `Object.freeze()`, and reinforce your knowledge of the `switch` statement and `map()` method.

Or something like that?

**Comment by hbar1st** [comment]
changing the description slightly seems like an easy way to fix the issue

**Comment by naomi-lgbt** [comment]
> This project will cover concepts like, default parameters, Object.freeze(), and reinforce your knowledge of the switch statement and map() method.

I like this copy, yeah.
