### ISSUE TITLE
Combining steps 7-9 in build a football team cards

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55437]
### Describe the Issue

steps 7-9 of build a football team cards project all ask for key-value pairs to be added to the project code.
They are simple and can easily be collected into one step with an instruction like the one below:

Below the team property, add three new property key-value pairs.
A key named `sport` and a string value of `"Football"`.
A key named `year` and a number value of `1986`.
A key named `isWorldCupWinner` and a boolean value set to `true`.

Note that step 6 also asks for a property to be added but we can leave that one as-is as a kind of 'warm-up' step (in case people forgot how to do it). While step 10 asks for another key-value pair but the text there is longer and so probably is best left as-is.

Alternatively, step 10 can be simplified if we rolled the initial instruction into the previous (newly combined) step.
So we could make the combined step say all the above plus this line:
A new key called `headCoach` with a value of an empty object.

Then in step 10 we can simplify the instruction down to:
Inside the headCoach object, add a property with a key of coachName and a string value of "Carlos Bilardo". Below that property, add another key called matches with a number value of 7.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-7

### Your code

N/A

### Expected behavior

The newly combined step would have to provide test+hints for the three different properties being added.

### System

N/A

**Comment by shivansh84ya** [comment]
hi @hbar1st,  
Could you assign this issue to me ?
Thank you

**Comment by gikf** [comment]
Hey @shivansh84ya

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by lasjorg** [comment]
I think combining the three steps sounds reasonable enough, I'm just not sure if it is worth the step shuffling. It seems to cause issues for learners on the forum, so maybe we shouldn't do it too often unless it is really necessary.

**Comment by hbar1st** [comment]
I understand that perspective but since this is still in beta it would seem like now is the best time for changes.

**Comment by lasjorg** [comment]
It just seems like a very minor change, compared to the potential confusion it can cause by shuffling the steps.

I'm not opposed to the change, but I do think we should be mindful when changing the step count/order and carefully consider if it is truly worth it.

**Comment by hbar1st** [comment]
If steps 7-9 are combined, what will the campers see if they are mid-step (either on 7/8/9)?

**Comment by jdwilkin4** [comment]
@hbar1st 

> what will the campers see if they are mid-step (either on 7/8/9)?

If campers log in after the update, then they will see current step 10 where 8 used to be and current step 11 where 9 used to be.

**Comment by hbar1st** [comment]
So for sure they will see step 7 is not blue (not completed), but if they were on step 10, which is now step 8, will they be able to continue?

**Comment by jdwilkin4** [comment]
> So for sure they will see step 7 is not blue (not completed)

Yes, that is correct.

> but if they were on step 10, which is now step 8, will they be able to continue?

They will see a few steps that will show as not done and just backtrack from there and continue.

**Comment by hbar1st** [comment]
Maybe then it is just a minor bit of confusion?

**Comment by harshalgunjal69** [comment]
I am working on this issue, and foun out that the same webpage is being served in many other languages. Do, I have to make changes for all languages?
