### ISSUE TITLE
Sea Level Predictor - Gitpod boilerplate dependencies issue

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#55475]
### Describe the Issue

Error thrown:

`AttributeError: module 'numpy.typing' has no attribute 'NDArray'`

The issue seems to be with the `PIL` dependencies and/or NumPy. Not really sure if it is a peer dependency or if PIL is part of the docker image.

Forum post for context https://forum.freecodecamp.org/t/data-analysis-with-python-projects-sea-level-predictor/699393

### Affected Page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/sea-level-predictor

### Your code

```



```

### Expected behavior

The Gitpod boilerplate not to throw errors.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
I updgraded `numpy` with `pip`:
```
pip install numpy --upgrade
```
It installed `1.24.4` version. After that `scipy` was giving errors, and after upgrading it:

```
pip install scipy --upgrade
```

To the `1.10.1` version project appears to work fine.

`requirements.txt` might need updating to these versions.
