### ISSUE TITLE
Javascript Waypoint Typo [Beta]

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/FreeCodeCamp#5547]
### Waypoint: Initializing Variables with the Equal Operator
http://beta.freecodecamp.com/challenges/waypoint-initializing-variables-with-the-equal-operator

"inital" should be "initial" in "Creates a new variable called myVar and assigns it an inital value of 0."

**Comment by SaintPeter** [comment]
Fixed on live.
