### ISSUE TITLE
Typo in [Beta] Waypoint: Bring your JavaScript Slot Machine to Life

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#5548]
Challenge [[Beta] Waypoint: Bring your JavaScript Slot Machine to Life](http://beta.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Instructions:
>This jQuery will select the first slot and update **it's** HTML to display the correct number.

Should be `its`.

**Comment by SaintPeter** [comment]
Sorry, Bring your Javascript Slot Machine to Life is beta only.  It's not officially part of the released curriculum.
