### ISSUE TITLE
Teach operator precedence

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#55495]
### Describe the Issue

I did a search for "operator precedence" and it only showed up one time, and that was for an Odin Project (not even sure if we are using it).

`curriculum/challenges/english/16-the-odin-project/top-learn-variables-and-operators/learn-variables-and-operators-lesson-h.md`

Unless we don't call it that or something, I would _strongly_ suggest we add it to the curriculum.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/

### Your code

```



```

### Expected behavior

Campers should be taught about operator precedence.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/platformer-game-step-33/699397

**Comment by naomi-lgbt** [comment]
IMHO this seems like a good case for a smaller project before the RPG game?

**Comment by lasjorg** [comment]
Technically, the pyramid generator project is making use of it, if we look at:

```
character.repeat(2 * rowNumber - 1)
```

A camper would need to know that operator precedence makes it

```
(2 * rowNumber ) - 1
```
And not
```
2 * (rowNumber  - 1)
```

So maybe it needs to be introduced in this project?

**Comment by naomi-lgbt** [comment]
Maybe a quick introduction to PEMDAS in that step, and then a project to further explore it? I'm not sure how heavily we need to teach this, tbh.

**Comment by lasjorg** [comment]
A brief introduction would be in order. There isn't much to the basic and most common cases (+-*/).

Although, with enough effort (or lack thereof) you can definitely string together some longer calculations that can be hard to read.

So teaching it could also be part of teaching the importance of not over relying on it, i.e. writing the calculations in the "best" order and proper grouping using parentheses when needed.

I think very few people know the full precedence list off of the top of their head. And it's not like we need to go beyond the basics.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence

**Comment by naomi-lgbt** [comment]
My knowledge extends to PEMDAS 🤣 

Okay, we should be fine to add a quick explanation in the step where character.repeat(2 * rowNumber - 1) is introduced.

**Comment by jdwilkin4** [comment]
We will go ahead and open this up for contribution.
We will just use Naomi's suggestion here

https://github.com/freeCodeCamp/freeCodeCamp/issues/55495#issuecomment-2248789903

As for the new cert, there is a lecture video covering operator precedence

**Comment by hbar1st** [comment]
for clarification, which step is the one that is to be updated?

**Comment by jdwilkin4** [comment]
@hbar1st 

It looks like step 70

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-70

**Comment by hbar1st** [comment]
Maybe the rewrite is to change this text in the step from:

>You can pass full expressions as an argument. The function will receive the result of evaluating that expression. For example, these two function calls would yield the same result:

to

>You can pass full expressions as an argument. The function will receive the result of evaluating that expression. For example, these two function calls below would yield the same result. (Note that the order of operations rule PEMDAS - Parenthesis, Exponents, Multiplication, Division, Addition, Subtraction - applies):
