### ISSUE TITLE
[Beta] Typo in Waypoint: Concatenating Strings with the Plus Equals Operator

### ISSUE THREAD

**Issue by jbmartinez** [FreeCodeCamp/FreeCodeCamp#5549]
Challenge [Waypoint: Concatenating Strings with the Plus Equals Operator](http://beta.freecodecamp.com/challenges/waypoint-concatenating-strings-with-the-plus-equals-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3B%0A%0A%0A) has an issue.

In the instructions one can read
> Build myStr over several lines by concatenating these two strings: "This is the first sentance. " and "This is the second sentance." using the += operator.

I think it should say "sentence" instead of "sentance" in both instances.

**Comment by SaintPeter** [comment]
Thanks :smile:.
Wish I could spell.

**Comment by SaintPeter** [comment]
Fixed on live.
