### ISSUE TITLE
Typo suit instead of suite

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#55504]
### Describe the bug
There's typo in assertion message: _suit_ instead of _suit**e**_
https://github.com/freeCodeCamp/freeCodeCamp/blob/0a99796dd388b7a04a84603349fd473c465bf21e/curriculum/test/test-challenges.js#L456

- - -

This is something that can be fixed by "first time" code contributors to this repository. Here are the files that you should be looking at to work on a fix:

List of files:

1. https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/test/test-challenges.js

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Sometimes we may get more than one pull requests. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by devXaks** [comment]
Respected Moderators
Kindly assign the issue to me. 
Thanks and Regards
Akshat

**Comment by gikf** [comment]
Hey @devXaks

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by devXaks** [comment]
Respected Moderators,
Since it was the first time I was contributing to an open source project, it took some time to review some guidelines before I contribute. Being said that first PR that comprehensively solves the issue is accepted and since the issue was not closed yet, I think that I can contribute. Please excuse me if I did something wrong, I will surely make a note of it contributing the next time
With Regards
Akshat
