### ISSUE TITLE
Decimal to binary converter - Step 77 - DRY acronym not explained

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55508]
### Describe the Issue

Step 77 of the decimal to binary converter project (js beta) says this:
Now your showAnimation() function is set up. But if you look closely at your checkUserInput() function, you'll notice that it's not very DRY – you're calling parseInt() to convert numberInput.value into a number several times.

I don't think the DRY acronym was introduced before and so this would be a confusing sentence to parse.
If the acronym is required, then a definition should be presented.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-recursion-by-building-a-decimal-to-binary-converter/step-77

### Your code

N/A

### Expected behavior

N/A

### System

N/A

**Comment by lasjorg** [comment]
Even if we do give a definition, the principle is introduced pretty haphazardly.

It's perfectly fine that we make the camper aware that some code is being repeated that should be consolidated. But I don't think we need to introduce the DRY principle.

---

The DRY principle has both pros and cons. Mentioning it as an absolute, without any depth to the subject, is questionable. This is especially true for learners/beginners, which tend to create premature abstractions and over-abstractions the minute they hear about the DRY principle.

**Comment by hbar1st** [comment]
I personally think the lesson works without any reference to DRY

**Comment by lasjorg** [comment]
My initial reaction is also to just remove it.

---

Maybe something like:

> Now your  `showAnimation()`  function is set up. If you look at your  `checkUserInput()`  function, you'll notice that it's calling  `parseInt()`  to convert  `numberInput.value`  into a number several times.
> 
> To fix this, create a new variable to store the converted number. Then you only have to convert the number once and can use it throughout the function.
> 
> Create a new variable called  `inputInt`  and assign it the number converted from  `numberInput.value`.

**Comment by hbar1st** [comment]
would it also be possible to say something about why it is desirable to not call parseInt several times?
Is it a good time to mention for eg that this is waste of processing power or can introduce errors in the code or something like that which would be relevant to know?

**Comment by naomi-lgbt** [comment]
Sure, building on lasjorg's suggestion:

> Now your  `showAnimation()`  function is set up. If you look at your  `checkUserInput()`  function, you'll notice that it's calling  `parseInt()`  to convert  `numberInput.value`  into a number several times.
>
> This is generally a poor practice, for reasons like performance concerns or even just the fact that you'd have to change your logic in multiple places to update the `parseInt()` call.
> 
> To fix this, create a new variable to store the converted number. Then you only have to convert the number once and can use it throughout the function.
> 
> Create a new variable called `inputInt` and assign it the number converted from  `numberInput.value`.
