### ISSUE TITLE
Bonfire: DNA Pairing Bug

### ISSUE THREAD

**Issue by Fogthecatman** [FreeCodeCamp/FreeCodeCamp#5550]
Challenge [Bonfire: DNA Pairing](http://www.freecodecamp.com/challenges/bonfire-dna-pairing) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This code should function correctly, I am placing the smaller arrays at index positions in the larger array. The printout of the code puts all the characters in 1 sequential array when this isn't the case.

The final array is correct, but clicking the run button to finish the project doesn't.

I have tried both .push and [i] to append these arrays but running the code doesn't work.

My code:
```javascript
function pair(str) {
  var pairArr = [];
  
  for(var i = 0; i < str.length; i++){
    var smallerArr = [];
    
    if(str.charAt(i) === 'G'){
      smallerArr.push(['G', 'C']);
    }
    
    else if(str.charAt(i) === 'C'){
      smallerArr.push(['C', 'G']);
    }
    
    else if(str.charAt(i) === 'A'){
      smallerArr.push(['A', 'T']);
    }
    
    else if(str.charAt(i) === 'T'){
      smallerArr.push(['T', 'A']);
    }
    
    pairArr[i] = smallerArr;
  }
  console.log("TESTING " + pairArr);
  return pairArr;
}

pair("ATCGA");

```

**Comment by sludge256** [comment]
The FCC code output doesn't display brackets for arrays currently as referenced in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5097.

However as long as the true output is correct you should be able to pass the tests.

Your code output is:
```js
[[["A", "T"]], [["T", "A"]], [["C", "G"]], [["G", "C"]], [["A", "T"]]]
```
and the expected result is:
```js
 [["A","T"],["T","A"],["C","G"],["G","C"],["A","T"]]
```

**Comment by ltegman** [comment]
@sludge256 is correct. Thanks and happy coding!
