### ISSUE TITLE
Is the MongoDB version Outdated for Local Development

### ISSUE THREAD

**Issue by michaelhiiva** [freeCodeCamp/freeCodeCamp#55511]
### Describe the Issue

The current MongoDB version listed for setup is 5.0 yet the latest version is 7.0 which means we are 2 major releases behind: https://www.mongodb.com/docs/manual/reference/versioning/. Is Freecodecamp behind on the versions?

### Affected Page

https://contribute.freecodecamp.org/how-to-setup-freecodecamp-locally/

### Steps to Reproduce

N/a

### Recommended fix or suggestions

Potentially update the version to 7.0+.

**Comment by ShaunSHamilton** [comment]
Thank you for bringing this up.

Indeed, we are on version 7. So, any mention of a different version should be updated in the contributor documentation.

---

The files needing changed can be found here: https://github.com/freeCodeCamp/contribute

An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by ojeytonwilliams** [comment]
Version 7 may work, but we're still on 6. The mongo node driver is on 3.6.9 which is compatible with mongodb 6, but not 7. See https://www.mongodb.com/docs/drivers/node/current/compatibility/

**Comment by ShaunSHamilton** [comment]
So we are. Thank you for correcting. I will edit my above comment.
_I really thought we had upgraded_

**Comment by hbar1st** [comment]
please don't forget to update this file? https://github.com/code-demigod/freeCodeCamp-1/blob/master/docs/how-to-setup-freecodecamp-locally.md

**Comment by salignatmoandal** [comment]
Hello, this is my first contribution in open source. I saw that it was a good contribution for beginners. Can you help me in my first contribution?

**Comment by michaelhiiva** [comment]
@salignatmoandal This has already been addressed in pull request https://github.com/freeCodeCamp/contribute/pull/219. If you look above your comment, you can see that a pull request has been linked to this issue.
