### ISSUE TITLE
Calorie counter (js beta) project should teach why input fields cannot be retrieved early

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55513]
I have noticed that many people working on the palindrome project will fail to realize that trying to grab the value of an input field outside of an event handler will not work. (I've had to help many people understand that they need to move their whatever.value code down into the event handler. I think people are trying to include it early (when they're defining the variables that get the html elements globally) because they haven't seen what happens when you do that. Or they haven't linked that the global values are evaluated at a different time than the click handlers.

Therefore I suggest that somewhere before the calories counter project's step 18 is presented, a step or two are added to deliberately make that mistake. (Like maybe it makes them grab the value and try to log it globally and then explains why the log shows nothing)

Thanks

**Comment by gikf** [comment]
This is slightly touched in the Building a Role Playing Game:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-15
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-16

**Comment by hbar1st** [comment]
Not what I meant. Step 16 talks about the script tag. But what I am seeing in people’s code in the forum is an attempt to retrieve values in global scopes. (Their script tag may be in the correct place but they’re not understanding that the value will be retrieved too early).

**Comment by hbar1st** [comment]
May I ask why this is not planned?

**Comment by ojeytonwilliams** [comment]
This seems to have been closed prematurely - it does sound like there is room for improvement here.

**Comment by hbar1st** [comment]
I agree with your comment @ojeytonwilliams, especially as it would be fairly easy to make the necessary improvement/clarification in one of the projects just by asking the user to get the value in the global scope ( a deliberate error) and explaining why it doesn't work, then moving it to an event listener to see the better result.

**Comment by naomi-lgbt** [comment]
I am opening this issue for contribution.

A PR which resolves this issue should:
- Insert a new step 38 into the Calorie Counter project which instructs the campers to try logging the value of `entryDropdown.value` and see what happens when they interact with the dropdown element. The step should also explain that behaviour.
- Update the current step 38 (now step 39) to include instructions to remove the console log before defining the new function. The seed code should be updated to include the log statement.

**Comment by ilenia-magoni** [comment]
@kamalxdev please don't ping maintainers asking for review, you have opened a PR, it will be reviewed
