### ISSUE TITLE
doctype is referred to as a preamble in the specs

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#55528]
### Describe the Issue

https://developer.mozilla.org/en-US/docs/Glossary/Doctype

https://html.spec.whatwg.org/multipage/syntax.html#the-doctype

I think in most places we call it a declaration.

It isn't a big deal. But we might want to consider using the same terminology as the specs.

### Affected Page

https://www.freecodecamp.org/learn/

### Your code

```



```

### Expected behavior

Terminology of the specs.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by naomi-lgbt** [comment]
This is an interesting one. The HTML spec calls it a preamble, but [used to call it a definition](https://www.w3.org/TR/1998/REC-html40-19980424/sgml/dtd.html).

The XML spec, however, does call it a [declaration](https://www.w3.org/TR/2008/REC-xml-20081126/#sec-prolog-dtd). Or a [definition](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-doctype). 

The W3 also calls it a [declaration](https://www.w3.org/QA/2002/04/valid-dtd-list.html) [sometimes](https://www.w3.org/TR/html-polyglot/#doctype). 

---

From personal experience, I've never heard it called anything other than a declaration. I would worry that saying "preamble" instead might just result in more confusion?

**Comment by lasjorg** [comment]
- The word "definition" could be historical and related to DTD (document type definition).
- The word "declaration" could simply be that writing a doctype, means it has been "declared", which seems reasonable enough. But saying it has been declared and calling it a declaration isn't necessarily the same thing.
- The word "preamble" could be a more generic term, related to its position in the document, more than some other word that might describe its various valid forms and implications ([rendering mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode)).

Digging long and hard enough, it would be possible to find the instance where the doctype became known as a preamble. But nevertheless, it is what the specs call it.

---

I'm not sure a beginner would be any more confused about the word preamble, than they would definition, or declaration. Although, it is possible.
