### ISSUE TITLE
Editor get stuck after console opened

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#55520]
### Describe the Issue

If a challenge has a error and if I open to see the error, the IDE/editor become unresponsive. I does not let you type anything, the only way to is to refresh.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/bind-this-to-a-class-method

### Your code

```
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      text: "Hello"
    };
    // Change code below this line
    this.handleClick = this.handleClick(this)
    // Change code above this line
  }
  handleClick() {
    this.setState({
      text: "You clicked!"
    });
  }
  render() {
    return (
      <div>
        { /* Change code below this line */ }
        <button onClick={()=>{
          this.handleClick()
        }}>Click Me</button>
        { /* Change code above this line */ }
        <h1>{this.state.text}</h1>
      </div>
    );
  }
};
```

### Expected behavior

After I see error in console. I should be able to edit the code in IDE

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
Hey @mahassan

Could you provide specific steps to reproduce the issue? I haven't noticed such behavior when using code from issue. Additionally, what browser and OS are you using?

**Comment by mahassan** [comment]
@gikf 
Like my code posted above have some issue, if you solve that challenge as such, then
1- Open the console (like you are trying to find the errror)
2 - The editor for fcc become unresponsive like one cannot type it in
3-  Closr the edtior but still the editor is unresponsive

**Comment by ojeytonwilliams** [comment]
Thanks @mahassan Could you share the browser and OS version, too?

**Comment by mahassan** [comment]
Version 126.0.6478.127
macOS sonoma

**Comment by ojeytonwilliams** [comment]
Cheers. 126.0.6478.127 is the version of Chrome?

**Comment by mahassan** [comment]
@ojeytonwilliams yes

**Comment by ojeytonwilliams** [comment]
One of the team was able to reproduce the problem. Thanks again for bringing this to our attention.

**Comment by Sembauke** [comment]
I can not reproduce this error anymore, and the instructions are unclear. Please reopen this issue if you're still experiencing this.
