### ISSUE TITLE
Count failed Project attempts towards the streak

### ISSUE THREAD

**Issue by Bharath314** [freeCodeCamp/freeCodeCamp#55525]
### Is your feature request related to a problem? Please describe.

Currently, whenever I attempt a certification project, there is always a risk of losing my streak. Projects usually take more than a day to complete and may take up to a week if I really want it to be good.

### Describe the solution you'd like

I'd like even failed project submission to count towards a streak.

### Describe alternatives you've considered

Currently if I really wanted to maintain a streak, I'd have to submit a really shoddy project that games the user stories.

**Comment by Supravisor** [comment]
To continue your streak while attempting a project, you could start a new course.  Do about five challenges a day until you complete the project.

**Comment by Bharath314** [comment]
While I agree this is a fair solution, this works when your express purpose is to maintain the streak. You would want to maintain a streak to enforce the habit of coding every day, not the other way around - coding every day to maintain a streak. From my understanding, the certification projects are placed strategically to reinforce concepts taught in the previous guided projects. From a learning point of view, I think starting the next guided project just to maintain a streak would be detrimental to a learner, lest they fall into a rut of mechanically grinding through steps, without really learning. Having project submissions count towards the steak will incentivize people to make some effort every day without losing motivation from a broken streak or ending up in a path where they game the system to just maintain their streak.

**Comment by Supravisor** [comment]
Sometimes the certification projects can take Campers a few weeks to complete.
So another option is to start the projects earlier.  Take a look at all the certification projects, then write down what is required to fulfil user stories.  Each time a module or practice project is completed, or new material is learnt, review what was learnt and see what can be applied towards the certification projects.  There is no requirement to submit any of the projects in any particular order, Campers are free to choose what they learn and the pace they learn.

Also, the first part of practice projects is usually coding to reinforce past lessons, so attempting a few challenges each day will maintain a Camper's streak, without much detriment to learning - depending on the course (RWD, JS, PYTHON).

**Comment by lasjorg** [comment]
I don't think we should count failed attempts, that would really allow people to game the system. I'd much prefer a "really shoddy project" that passes the tests, then people submitting empty projects and having that count.

You can resubmit the certification projects as many times as you'd like and slowly improve it over time, sort of how you would work on real code. I don't know anything about how the streaks are implemented, so I'm not sure if resubmitting counts or not.

**Comment by Bharath314** [comment]
I'm pretty sure the resubmissions don't count. Maybe a middle ground could make sense - a submission only counts towards your streak if it passes at least one user story more than the previous submission.

**Comment by naomi-lgbt** [comment]
> I'm pretty sure the resubmissions don't count.

That is [correct](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/boot/challenge.js#L185-L200).

**Comment by lasjorg** [comment]
> Maybe a middle ground could make sense - a submission only counts towards your streak if it passes at least one user story more than the previous submission.

Not sure if I see that happening. I would assume that would require a fair few changes.

It would also make the submissions more expensive if we have to maintain some "requirements passed count". I guess it could be cached client side, so if nothing has changed in the "passed count" between submissions, we do not contact the server again. But still, anytime you pass or fail something new it would have to update server side and store it.

Unless there is a simple solution to it, it seems a little overkill.

**Comment by Bharath314** [comment]
I agree that this would be difficult to implement. I do think a feature like this would be important to keep learner engagement though. I'm guessing a lot of learners drop off when they reach projects. Apps and games use streaks to maintain consistent engagement. Maintaining a streak has to be as low cognitive effort as possible to be successful. A look through the data of learner engagement during projects might reveal whether such a feature is necessary or not.

Then again, fCC is working on a lot of stuff already, so it might be better to put this into an idea bin to look at later.

My own learning journey has been going slow and I'd really love to be able to actually contribute to fCC at some point. I really love what you guys are doing :)
