### ISSUE TITLE
Back end certificate not showing up, nor is it claimable

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5553]
Accounts that should show the back end certificate aren't, and the certificate doesn't seem to be accessible.

![](https://www.evernote.com/l/AqRSNjfx8AZMAJZuegnoOmHrttMe59M8muYB/image.png)

**Comment by QuincyLarson** [comment]
@BerkeleyTrue It is also not possible to claim the back end cert.

**Comment by BerkeleyTrue** [comment]
Works fine. 

Happy Coding!

**Comment by tommy1962** [comment]
Same here. Only mind is Front-end  cert problem
