### ISSUE TITLE
cant go to the next step.

### ISSUE THREAD

**Issue by GOGOLDATTA** [FreeCodeCamp/FreeCodeCamp#5554]
Challenge [Waypoint: Create a Bootstrap Headline](http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline#?solution=%3Ch3%20class%3D%22text-primary%20text-center%22jQuery%20Playground%3C%2Fh3%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h3 class="text-primary text-center" jQuery Playground </h3> 
I cant go to the next step .Please help.




```

**Comment by P1xt** [comment]
@GOGOLDATTA you need a closing brace after the quoted class.
<h3 class="text-primary text-center"> jQuery Playground </h3>

**Comment by GOGOLDATTA** [comment]
thanx
