### ISSUE TITLE
dice game step 9 (js beta) needs to fix one of the hints

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55563]
### Describe the Issue

In step 9 of the review algorithmic thinking by building a dice game project (js beta), if you make a mistake in the line of code that is supposed to add the new li element, you will see this hint:
`When updateScore(10, "hi") is called, your new list element should have the text hi: 10.`

Notice that this hint says that the end result is hi: 10 with no space to the left of the colon?
But the instructions say:
`add a new list item to the score history with the format ${achieved} : ${selectedValue}.` 
Here we see a space to the left (and right) of the colon.

The test will not pass if you do not add that space to the left. So it is quite confusing when people are seeing the exact result being printed and logged from the hint but their code does not pass.

A fix for this is to add one space to the left of the colon in the hint text.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-9

### Your code

```
const updateScore = (selectedValue, achieved) => {
  score += selectedValue
  totalScore.textContent = `${score}`;
  scoreHistory.innerHTML += `<li>${achieved}: ${selectedValue}</li>`
}
```
(this is sample code from a camper on the forum)
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-9/701542

### Expected behavior

The hint should show the correct spacing.

### System

N/A

**Comment by huutryrus** [comment]
:)
