### ISSUE TITLE
cash register project sample app gives irregular results in repeated tests

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55566]
### Describe the Issue

I was messing around with the sample cash register project given by fCC here: https://cash-register.freecodecamp.rocks/
and managed to end up with a negative number in the "Change in drawer" nickels area. Please see the screenshot attached: 
![negative-cash-register](https://github.com/user-attachments/assets/b89f8be8-481f-4c5e-a42c-93bc5471dd83)

(please note my default font size in Chrome is 'large' so that's why the display looks bad, as the app was probably not optimized for this)

When I ran into this first issue, I tried to recreate, but I couldn't quite remember how I got to this point and somehow I ended up with another issue, but this time the cid was exactly .01 and I was trying to get it to give me that last cent but it refused to do so. Here's a screenshot of this second issue: 
![unreachable-penny-cash](https://github.com/user-attachments/assets/412ad766-6198-49b3-95da-b814afe76169)

Thankfully for this second issue I was able to recreate by typing: 338.6, then enter, then 3.32 then enter then 3.27 then enter.

I also ran into a third issue when I tried to type: 338.6 alone which was the nickels were showing as very long floats
![longFloatCash](https://github.com/user-attachments/assets/1d335ecd-32d0-409c-9b8f-a3e28c3d8341)
 
As these may all be related to number handling in the app, I've placed all the images here for your ref. Unfortunately I was not able to think of the steps that may have led to the very first issue with the negative nickel.

### Affected Page

https://cash-register.freecodecamp.rocks/

### Your code

N/A

### Expected behavior

cid should not have negative values ever and all change should be accessible even if only 1 cent left provided cash-price = 0.01
change values should never have more than 2 decimal places.

### System

N/A

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue https://github.com/freeCodeCamp/demo-projects/issues/559, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
