### ISSUE TITLE
Step 55 | JavaScript Algorithms and Data Structures (Beta)

### ISSUE THREAD

**Issue by xTektonicx** [freeCodeCamp/freeCodeCamp#55572]
### Describe the Issue

Up to this point we've learned quite a bit of different things. Prior to step 55 we learned how to create functions and how we can use them. In step 54 we learned to return a name parameter.

One thing we didn't learn before being tossed in the deep end by saying "Before moving on, take a moment to review how functions work" is how to do multiple arguments. I was completely stuck. I had to google how to use multiple arguments in a function. It's pretty easy. I just hadn't learned to do that yet. Step 55 could've been used to teach us multiple arguments rather than throwing us in the deep end.

I'd be curious to know how many users fail at Step 55 and quit the course out of frustration and thinking they couldn't do it.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-55

### Your code

```

I eventually figured it out. Just here for feedback.

```

### Expected behavior

-

### Screenshots

![image](https://github.com/user-attachments/assets/b3c72576-369e-4e4c-a8d9-7f24961b7e99)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by hbar1st** [comment]
please re-open. If you check the forum you will find multiple posts about this step with people who are not knowing how to react when asked for multiple parameter function for the first time.
Ideally, either this step or an earlier one should explain that multiple parameters can be used and they need to be comma-delimited.

**Comment by jeremylt** [comment]
I'll recreate this as an actionable issue

**Comment by hbar1st** [comment]
Will the new issue link to this one or refer to this one?

**Comment by plamoni** [comment]
> Will the new issue link to this one or refer to this one?

It doesn't. But you can find the new issue here: https://github.com/freeCodeCamp/freeCodeCamp/issues/55573

**Comment by plamoni** [comment]
Well, I guess now it does because it back-linked when I mentioned that issue here. 😀
