### ISSUE TITLE
Can't add the X account link to my profile 

### ISSUE THREAD

**Issue by M-AminAlizadeh** [freeCodeCamp/freeCodeCamp#55579]
### Describe the Issue

When I want to add my **x account** to my profile the format of the link must be `https://twitter.com/username` but the domain nowadays is `https://x.com/username` and when I add it with **x** instead of **twitter** it shows me an error 
![Screenshot from 2024-07-20 11-59-15](https://github.com/user-attachments/assets/a021ce50-1c88-4253-be72-b6bc0719655d)

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

1. Go to the settings of your profile
2. Find the **Your Internet Presence** section
3. Try to add/change the Twitter account link

### Expected behavior

It should allow both domains to be entered not only **twitter.com**

### Screenshots

![image](https://github.com/user-attachments/assets/83c3271f-b47f-4e8a-b125-68095bdca559)

### System

- Device: [Desktop]
- OS: [Ubuntu 22.04]
- Browser: [Firefox v128.0 - 64bit]

### Additional context

If the context is not enough for the issue reply to this issue and mention my username

**Comment by yuik371** [comment]
![Screenshot 2024-07-20 at 9 35 38 PM](https://github.com/user-attachments/assets/47be8a83-c57f-4151-8711-78781492248b)

Huh?? That's me too!!!

**Comment by narcelin** [comment]
Hello, I am new to contributing so please inform me if I am doing anything wrong.

The [allowedSocialsAndDomains](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/boot/settings.js) Line254 effects social link validation. Twitter.com could be changed to X.com for a quick patch although moderators may want to redefine all twitter references to x. May also want to allow either or (x.com || twitter.com).

[Twitter input placeHolder Location](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/settings/internet.tsx) Line239

**Comment by M-AminAlizadeh** [comment]
Hey @narcelin

Yes, I think the same but I think it should not be changed to **x.com** we have to change the value to _array_ instead of _string_
like this:

``` js
const allowedSocialsAndDomains = {
  githubProfile: 'github.com',
  linkedin: 'linkedin.com',
  twitter: ['twitter.com', 'x.com'],
  website: ''
};
```

then use a _conditional statement_ to be sure the entered data from a user to this input includes one of these two.
