### ISSUE TITLE
Certifications on profile page should be rendered in a `ul`

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55574]
## Description

On the user profile page, certifications aren't presented as a group:

```html
<!-- Pseudo code -->
<h2>freeCodeCamp Certifications</h2>
<a>View Responsive Web Design Certification</a>
<a>View JS Certification</a>
<a>View Python Certification</a>
```

<details>
  <summary>Image</summary>
  <img width="1347" alt="Screenshot 2024-07-20 at 01 59 27" src="https://github.com/user-attachments/assets/15407845-fd78-4dab-8e05-0c7f71d60755">
</details>

Instead, they should be moved to a `ul`, and the list should have a label:

```html
<!-- Pseudo code -->
<h2 id="fcc-certifications">freeCodeCamp Certifications</h2>

<ul aria-labelledby="fcc-certifications">
  <li><a>View Responsive Web Design Certification</a></li>
  <li><a>View JS Certification</a></li>
  <li><a>View Python Certification</a></li>
</ul>
```

## Affected page
The issue is in both the "freeCodeCamp Certifications" and "Legacy Certifications" sections on the profile page (https://www.freecodecamp.org/username or http://localhost:8000/certifieduser).

**Comment by tusharkaran** [comment]
can I work on this ?

**Comment by ojeytonwilliams** [comment]
Yes, @tusharkaran, issue with the help wanted label are open for all contributors. You're very welcome to work on this.

**Comment by tusharkaran** [comment]
can you assign me this ?

**Comment by tusharkaran** [comment]
@ojeytonwilliams can you please tell me how to run this application ?
I cannot find it in README file .

**Comment by tusharkaran** [comment]
Sorry I m new to open source contribution . will ask people on discord. Did not mean to be rude.
