### ISSUE TITLE
Waypoint: Local Scope and Functions

### ISSUE THREAD

**Issue by nvnehi** [FreeCodeCamp/FreeCodeCamp#5559]
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%205%3B%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Safari/537.36</code>.

The test asks you to remove the second console.log() to pass. When you remove the second console.log() it still fails. You have to remove both console.log() calls to pass(including the one inside myFunction().)

Reproducible every time by removing the console.log() outside of myFunction(), as asked by test. I'm assuming this is a bug in the test and not the text as there's no reason to remove the console.log() call within myFunction().

**Comment by ltegman** [comment]
This issues with this are twofold. First, the instructions are asking you to add a variable named `myVar` inside the function, but the tests aren't testing for that. If you don't add the variable the `console.log` inside the function will fail because the variable does not exist, causing the test to fail (even when you've removed the second `console.log`. We should probably add a first test that checks to make sure the user has created the variable.

Secondly, the test is checking for there to only be one instance of the string `"console.log"` in the editor window, but if you don't remove the comment there will be two instances of that string even once the second `console.log` has been removed.

**Comment by abhisekp** [comment]
This can be rectified by replacing the existing test with the following test
```js
assert(typeof myVar === 'undefined', 'message: No global <code>myVar</code>');EOL
assert(/var myVar/.test(code), 'message: Add a local <code>myVar</code>');
```

But if the use mistakenly creates a global variable and runs the test, then subsequent tests will fail unless the browser is refreshed.

**Comment by DiegoRBaquero** [comment]
@ltegman Removing the comment worked for the time being. OCD attacked.

**Comment by koallen** [comment]
I have to remove the comment for the test to pass.

**Comment by niallmurphy-ie** [comment]
If you've made it to this page for help, then refresh the page before trying the above solutions.

**Comment by jegger79** [comment]
Thanks niallmurphy-ie 
Had me scratching my head...

**Comment by Topzie** [comment]
Thank you niallmurphy-ie. You saved my life. (Well at least, some minutes of it).

**Comment by cedevita** [comment]
@niallmurphy-ie @jegger79 exactly! so strange :) thanks for advice

**Comment by TheGiwi** [comment]
JavaScript does not only confuse the students but the instructors also.
I came across a few JS tests on Codecademy that just wouldn't function like they said.
\you just had to hack to get passed.

**Comment by ferhotguy** [comment]
Refreshing the page does the trick.

**Comment by TylerL-uxai** [comment]
I ran in to this issue, and refreshing the page didn't solve it.

**Comment by MaxTan** [comment]
Thank you @niallmurphy-ie

**Comment by anastasi5** [comment]
Neither removing the console.logs nor refreshing the page worked...

**Comment by abhisekp** [comment]
@anastasi5 I suggest you please verify your code in [![**`FreeCodeCamp/HelpJavaScript`**](https://img.shields.io/badge/Gitter_Chat_Room:-FreeCodeCamp/HelpJavaScript_⮭-006400.svg?style=flat-square&maxAge=2592000 "FreeCodeCamp/HelpJavaScript")](https://gitter.im/FreeCodeCamp/HelpJavaScript)  chat room.

**Comment by fagbolaoluwagbenga** [comment]
function myLocalScope() {
 var myVar = 5;
  console.log(myVar);
}


// Run and check the console
// myVar is not defined outside of myLocalScope

......MORE LIKE THIS
// Now remove the console log line to pass the test
