### ISSUE TITLE
Cat photo app - step 56 example should be updated?

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55597]
Since step 56 of the cat photo app continues to cause confusion for campers, and the most common reason cited for this is that the example code shown shows the text on the opposite side of the input compared to how the actual app code is written, why don't we consider just removing the example code entirely?

If people already know what an attribute is, then adding the for attribute should be easy to do. They don't need the example?

If they don't know how to do it, then they will ask on the forum which is what everyone does for this step anyway. We may lessen the total number of questions if we just erase the sample code.

Just a thought.

**Comment by jeremylt** [comment]
Learners still don't have a good grasp of attributes at this point, so I don't think this is a good idea

**Comment by hbar1st** [comment]
what if we show a deconstructed example?
Instead of:
Here is an example of using the for attribute to associate a label with an input element:
We could say:

Given an input element as below:
`<input id="breakfast" type="radio" name="meal" value="breakfast">`
An example of a label that is associated to this input element is:
`<label for="breakfast"> Breakfast </label>`

**Comment by jeremylt** [comment]
I think that would help since the entire point is that we're associating two elements that otherwise are unconnected

**Comment by lasjorg** [comment]
We already have a test for its position, but it needs to be move up in order of tests. I have made a PR that refactors the tests, it should help to better catch the most common errors. It should allow us to keep the example as is.

**Comment by lasjorg** [comment]
If the test tells them where the label element should be located, why would that not work?

We can change the example as well, but I just think it is a generic example, and not really related to the actual requirements. The requirements and test/hints is what should tell the camper what they should write.

**Comment by jeremylt** [comment]
Why wait until the test messages to fix the misconception though instead of trying to get ahead of an extremely common mistake? Ideally, the lesson text should not lead students down a wrong path, but that's what it's doing now because it's implying that the label has to come to the left. The students don't know enough to know that the label can go anywhere relative to the input unless we make it obvious.

**Comment by lasjorg** [comment]
We can update the example if needed.

But the camper should be able to read the requirements and follow the tests to figure out the required code. And I think having an example that doesn't exactly match, forcing them to figure out the requirements, could be part of the learning process.

> Ideally, the lesson text should not lead students down a wrong path, but that's what it's doing now because it's implying that the label has to come to the left.

Well, it shouldn't imply that, even with the example, as long as the requirements are clear. I would be in favor of updating the requirements.

> Associate the text `Loving` with the checkbox by nesting only the text `Loving` in a `label` element and giving it an appropriate `for` attribute. The `label` element should be located to the right of the checkbox.

**Comment by jeremylt** [comment]
I think that was there previously and also generated confusion.

**Comment by lasjorg** [comment]
I added the new example code.
