### ISSUE TITLE
js array some() function lessons out of order in the js beta curriculum

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55592]
### Describe the Issue

In the building a spam filter project's step #12's instructions, we are told: "Remember that arrays have a .some() method. " However, we cannot remember as it was not taught. In fact it is not actually taught until step 100 of the building a spreadsheet project as far as I'm aware:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-100

I suggest that the part of lesson 100 that applies to teaching the some() method be moved into the spam filter project's step 12.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-regular-expressions-by-building-a-spam-filter/step-12

### Your code

N/A

### Expected behavior

Adding the missing lesson for some() before or during step 12 of the building a spam filter project. 

### System

N/A

**Comment by BOSE-git** [comment]
Hello I am a first timer, can i take up this issue? because adding the .some() function explaination to step 12 will solve this issue and i think it will be pretty easy to do that..
