### ISSUE TITLE
Learn Fetch and Promises by Building an fCC Authors Page - Step 24: Typo

### ISSUE THREAD

**Issue by andrebdinis** [freeCodeCamp/freeCodeCamp#55594]
### Describe the Issue

There is a typo in the following sentence:

> (...). First, if you click the Load More Authors button a couple of **time**, you'll see that it won't add more authors to the page. (...)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-fetch-and-promises-by-building-an-fcc-authors-page/step-24

### Your code

.

### Expected behavior

Rectify typo from **time** to **times**.

### System

- Device: Laptop
- OS: Windows 11 Pro 23H2 22631.3880
- Browser: Brave
- Version: Version 1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by jdwilkin4** [comment]
This has been opened for First Timers only contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da9ea9b847a49fe6ee9b6.md

## Changes needed to be made
```md
First, if you click the `Load More Authors` button a couple of times,
```

Happy coding
