### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue 

### ISSUE THREAD

**Issue by bmerri** [FreeCodeCamp/freecodecamp#556]
Please tell us in detail here how we can make this challenge better.
This challenge was solved only by entering <p> tag as follows (other challenges have similar bugs: only enter half the solution -> challenge complete): 

`<p> <a href='http://www.catphotoapp.com'>cat photos</a>`

![image](https://cloud.githubusercontent.com/assets/581078/7821194/11cd5f12-03bb-11e5-86f9-ce566dc843fd.png)

**Comment by QuincyLarson** [comment]
@bmerri Thank you for your submission. Please note that this actually works as designed. We're using a very loose regular expression to verify that the text is there. We don't want people to fail this because of a minor typo.
