### ISSUE TITLE
RangeError with correct solution on Waypoint: Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by BKinahan** [FreeCodeCamp/FreeCodeCamp#5560]
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20myFunction(c%2C%20d)%7B%0A%20%20console.log(c%20%2B%20d)%3B%0A%7D%0AmyFunction(2%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

Running tests outputs `RangeError: Maximum call stack size exceeded` and no tests pass.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.

function myFunction(c, d){
  console.log(c + d);
}
myFunction(2, 3);

```

**Comment by ltegman** [comment]
Huh, I'm unable to repro this using the exact same code. Anyone else seeing this error?

**Comment by BKinahan** [comment]
Just noticed it's mentioned in #5499 so it's not just me.. However I just reopened the waypoint page now and the tests were passed before running the tests, and running the tests was successful. Not sure what's going on there.

**Comment by nicolefffe** [comment]
I am having this problem too.

```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
function myFunction(arg1, arg2) {
  console.log(arg1 + arg2);
}

myFunction(5, 4);
```
No test cases pass and I get the error: RangeError: Maximum call stack size exceeded

**Comment by nicolefffe** [comment]
I also re-entered the waypoint from the map and the same code passed the tests, so it is a mystery :)

**Comment by lucabarbetti** [comment]
Test successfully passed after reloading the page.

**Comment by masondz** [comment]
Reloading the page also worked for me.

**Comment by harwluk** [comment]
having same issue. reloaded the page worked for me, too.

**Comment by ngorton91** [comment]
Getting this same error

**Comment by danjm75** [comment]
same problem. Is there an actual fix, or did I miss it?

**Comment by abhisekp** [comment]
Works for me now. Was getting range stack error previously.

**Comment by danjm75** [comment]
man I wish I would have refreshed like 15 minutes ago. that was a waste of time. oh well, I'll just subtract that time from my retirement!

**Comment by atan77** [comment]
I got the same error initially and then with a reload from the map it validated ok with no change to solution

**Comment by SaintPeter** [comment]
@BerkeleyTrue I have periodically been able to reproduce this, but refreshing the browser makes it go away.  Any ideas what might be going on here?  I'm presuming it's related to the test architecture.

**Comment by BerkeleyTrue** [comment]
Does it only happen on page initial page load (with default code) then on refresh with completed code it is fixed?

**Comment by SaintPeter** [comment]
It appears to happen on initial page load, then after refreshing it is fixed . . . but if you load the page, paste in the solution and try to run it, it fails.

**Comment by AkiraLaine** [comment]
Same problem here. With @SaintPeter's solution, it passed.

**Comment by KrisVos130** [comment]
I can reproduce this by being in an anonymous tab on Chrome, going to the challenge from the map and then just clicking submit. After that, when you clear your Local Storage and do the same thing, then the error happens again. You don't need to modify any code for the error to happen either.

**Comment by DDaems** [comment]
You can just do a reset, change something in the challenge field. adding a random space or whatever. And hit refresh ;-). Still i think the reset button should reset the localstorage item too. Wich it atm doesn't seem to do.

**Comment by srkchandru** [comment]
Refresh the page.It worked for me!

**Comment by bssatya** [comment]
Same here. Page refresh worked...

**Comment by onetallorder** [comment]
Reloading the page resolved this issue for me.

**Comment by ArielLeslie** [comment]
I ran into this a couple days ago as well.  Sometimes I had to refresh several times before it would work.

**Comment by denmch** [comment]
I had this happen with several of the new JS Waypoints over the last few days. In each case a hard refresh cleared it up.

**Comment by SimpliiD** [comment]
I just reproduced this error after initially loading using the 'learn' button, but refreshing fixed it. Also running in Chrome.

**Comment by edendecko** [comment]
reloading page work for me.

**Comment by shahh** [comment]
Refreshing the page worked for me too.

**Comment by AnnasLab** [comment]
Page refresh solve the problem
