### ISSUE TITLE
Submit exercise shortcut

### ISSUE THREAD

**Issue by mneisi** [freeCodeCamp/freeCodeCamp#55627]
### Is your feature request related to a problem? Please describe.

Freecodecamp Curriculum

### Describe the solution you'd like

At the moment some basic shortcuts exist on the platfrom, one of those shortcuts being `ctrl` + `enter` which checks the code, but after checking the code you would have to click the submit button manually, maybe it would be a good idea to add the same `ctrl` + `enter` shortcut to the submit button.
![image](https://github.com/user-attachments/assets/7b64e368-fe24-4ecc-8d93-8c62fb0a4353)
![image](https://github.com/user-attachments/assets/34fd21c5-6391-43ec-90a9-6916b4a6b723)

### Describe alternatives you've considered

Another idea would be to have a live code check and one button which submits the code.

### Additional context

There is another shortcut: `esc` + `n` that navigates to the next exercise,  which we can access by enabling the extra shortcuts from settings, but this shortcut only navigates and doesn't submit the exercise.

**Comment by gikf** [comment]
It still should be possible to use `ctrl` + `enter` when _Submit and go to next challenge_ is displayed. I guess it just would be needed to change the text, with version for mac as well. Similarly how it's done in the completion modal.

**Comment by mneisi** [comment]
> It still should be possible to use `ctrl` + `enter` when _Submit and go to next challenge_ is displayed. I guess it just would be needed to change the text, with version for mac as well. Similarly how it's done in the completion modal.

you're right, it didn't work for me the first time I tried it, but I tried it now and it works.

I guess just fixing the text would be good, or maybe add live check?

**Comment by naomi-lgbt** [comment]
Yes, we should only need to update the text.

**Comment by saam-rgb** [comment]
We can use `Shift` + `Enter` to submit and go to next challenge
