### ISSUE TITLE
Unable to claim Back End certificate

### ISSUE THREAD

**Issue by george-stepanek** [FreeCodeCamp/FreeCodeCamp#5562]
As part of the recent changes the Full Stack certificate I had previously claimed was removed, but the corresponding waypoint was still marked as done, and this waypoint was reused for the new Back End certificate. I have now completed the additional API challenges, but when I click through the waypoint again I don't get the Back End certificate added to my profile (http://www.freecodecamp.com/george-stepanek).

**Comment by QuincyLarson** [comment]
Hi George,

Yes - I noticed this earlier today. Thank you for opening the issue. @Berkeleytrue is working getting this fixed along with the new Data Visualization certification.

**Comment by QuincyLarson** [comment]
I'm going to close this as duplicate and update this issue: #5553

**Comment by ltegman** [comment]
Closing as duplicate, per Quincy's instructions.
