### ISSUE TITLE
Extra spacer in the donate page

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/freeCodeCamp#55622]
### Describe the Issue

There is an extra spacer in the top of the donate page. It might be cause by the donate page or its wrappers. The spacer should be removed or adjusted so it does not show up unecessarly.

### Affected Page

https://www.freecodecamp.org/donate

### Steps to Reproduce

The issue is viewable locally or on production by viewing the donate page. 

### Screenshots

<img width="1067" alt="Screenshot 2024-07-23 at 3 02 34 PM" src="https://github.com/user-attachments/assets/a717d548-d3d2-4881-8d75-ae6d387f2229">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by catychelpan** [comment]
Hi, can I be assigned to this task?

**Comment by shootermv** [comment]
sorry, the issue not so clear for me...
there is extra space in the screenshot? can you please mark it somehow?
