### ISSUE TITLE
[bug]: moving editable region on refresh

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#55636]
1) Navigate to a multifile challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-9
2) Input some code over multiple lines:

```js
const updateScore = (selectedValue, achieved) => {
  totalScore += selectedValue.value;
  // some comment
}
```

3) Save code `Ctrl + S`
4) Refresh page

![image](https://github.com/user-attachments/assets/43055120-db6e-4557-9d13-4995028a94fa)

Seen in: https://forum.freecodecamp.org/t/user-editable-area-gets-smaller-after-refreshing-page/702480

---

I assume this has to do with the container defaulting to the size it is originally given (e.g. 1 line), even though the saved code spans more.

**Comment by ShaunSHamilton** [comment]
An issue with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by a2937** [comment]
This is where the bounds come from. A function called `getEditableRegionFromRedux` in `editor.tsx`. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/25b6fb50a1d451a28954650595aa1ff07e262f7c/client/src/templates/Challenges/classic/editor.tsx#L327-L333 

In order to fix this, we're going to have to save the current editable region boundaries and then load from them in this function.

**Comment by dwrik** [comment]
@a2937

Would a `localStorage` based solution be appropriate for this scenario?

**Comment by ShaunSHamilton** [comment]
@dwrik The editable region boundaries are already persisted in local storage, as shown in the screenshot. The issue is when the editor component is mounted, it is preferring the editable regions defined in the challenge seed, as opposed to using the boundaries kept in the saved code from local storage.
