### ISSUE TITLE
variable/argument name not using camelCase

### ISSUE THREAD

**Issue by harwluk** [FreeCodeCamp/FreeCodeCamp#5565]
Earlier in the basic Javascript section, FCC takes extra effort to introduce and reinforce the use of camelCase, but Bonfire: Convert Celsius to Fahrenheit ignores the rule. 

The code still works, so not a bug per se, but may be confusing for beginners if they wonder why FCC is not following the convention introduced just a few waypoints before.

**Comment by ltegman** [comment]
The variable names are also very vague and would not make sense unless explained in the sidebar.

**Comment by gasperno** [comment]
@ltegman 
I think we can replace `Tf` with `farenheit` and `Tc` with `celsius` as variable names. Would you agree?
Same modifications in the description.

**Comment by ltegman** [comment]
@gasperno Sounds like a good way to go to me :smile:
