### ISSUE TITLE
Settings page - not possible to save after clearing picture URL

### ISSUE THREAD

**Issue by gagan-bhullar-tech** [freeCodeCamp/freeCodeCamp#55653]
### Describe the Issue

Save button does not get enabled even if the picture URL is valid

### Affected Page

https://www.freecodecamp.org/settings

### Steps to Reproduce

Here are the steps to reproduce.

1. Go to https://www.freecodecamp.org/settings page
2. Go to picture field and edit the value.
3. The message `URL must link directly to an image file` will be visible below the field
4. Save button does not enable even if the URL entered is valid

### Expected behavior

Save button should get enabled and the message below the field should go away in both conditions
1. Picture url is valid
2. Picture url does not have value

### System

- Device: [Laptop]
- OS: [MacOS]
- Browser: [Chrome]
- Version: [126.0.6478.183]

**Comment by lsyversen** [comment]
It works for me. I think you have to edit the username and then it'll work.

**Comment by gikf** [comment]
Steps to reproduce:
1. Enter valid image URL
2. Press enabled _Save_ button
3. Reload page
4. Remove image URL, leaving empty field
5. _URL must link directly to an image file_ is displayed, _Save_ button is disabled.

**Comment by gagan-bhullar-tech** [comment]
@gikf Created PR to fix to remove `URL must link directly to an image file` message if picture URL is empty.

But on click of Save, it is again populating the default URL. Is that by design ?

**Comment by gikf** [comment]
> But on click of Save, it is again populating the default URL. Is that by design ?

I don't think it is, but it appears api-server currently is also not allowing to update to empty picture URL.
