### ISSUE TITLE
Clear challenge layout in browser storage when logging out

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#55664]
The layout of the challenge editor panes gets saved to local storage so it can persist between challenges. We could probably remove that when you log out.

_Originally posted by @moT01 in https://github.com/freeCodeCamp/freeCodeCamp/pull/55621#pullrequestreview-2194295648_

**Comment by SarthakPaandey** [comment]
May you assign this task to me? I want to work on this.

**Comment by moT01** [comment]
We do not typically assign issues @SarthakPaandey. We need to figure out if we want it and what a solution might be. You can feel free to give your opinion on if this is something we should do and how to do it. Otherwise, you can look for [issues with the help wanted label](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) and make a fix for those. Thanks.

**Comment by ojeytonwilliams** [comment]
I'm not sure it's worth it. I'd either keep the layout around for all users (signed in or out) or just delete it when they sign out.

I like the former. While we can remove it, I don't see a reason to.
