### ISSUE TITLE
Update React.js Curriculum: Transition from OOP to Functional Programming and Hooks

### ISSUE THREAD

**Issue by M-AminAlizadeh** [freeCodeCamp/freeCodeCamp#55675]
### Is your feature request related to a problem? Please describe.

Yes it is about the [Front End Development Libraries](https://www.freecodecamp.org/learn/front-end-development-libraries/#react)

As you know in the last 3 years almost all of the UI apps built with React library use functions and hooks

But the FCC curriculum still doesn't change it 

![image](https://github.com/user-attachments/assets/692fb81e-9a7a-43f5-a669-870e381a5aad)

### Describe the solution you'd like

I suggest changing the curriculum from OOP to FP (update the course) exactly like the changes for the **Responsive web design** and **JavaScript algorithms & DS**

### Describe alternatives you've considered

- Transition lessons from class components to functional components.
- Introduce hooks such as `useState`, `useEffect`, `useContext`, etc.
- Provide examples and exercises to practice these hooks.
- Update existing projects and challenges to use functional components and hooks.

### Additional context

I am willing to help contribute to these changes and work with the curriculum team to ensure a smooth transition. This update will significantly enhance the learning experience for future FreeCodeCamp learners.

**Comment by jdwilkin4** [comment]
Hi @M-AminAlizadeh ! 

This is already being worked on so I going to close this issue
