### ISSUE TITLE
Make the Danger Zone safer by adding a confirmation safeguard that requires typing a specific phrase

### ISSUE THREAD

**Issue by gylotip** [freeCodeCamp/freeCodeCamp#55684]
### Is your feature request related to a problem? Please describe.

The Danger Zone contains stuff about resetting all progress and deleting accounts. Currently, you only have to click on the “Yes” button or anything similar to perform these dangerous actions. I think leaving this just like the way it is could cause lots of progress loss:

[Screenshot_2024-07-28-21-32-37-799_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/3db35b6d-2b58-41bc-9184-3ce9522374c1)

[Screenshot_2024-07-28-21-33-15-253_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/d28437d1-adb6-4ef4-908a-1603c2661fc5)

### Describe the solution you'd like

My suggestion is to add a failsafe, where you type something like “I agree that all progress will be lost” (without quotes), just like in GitHub:

[IMG_20240728_214736](https://github.com/user-attachments/assets/4b8ab203-f40e-4fdb-9b22-18941fe041e4)

### Describe alternatives you've considered

No alternatives would fit for the solution because the failsafe must take a lot of time for users in order to protect users from progress loss accidents. So, it is crucial to make the failsafe be a typing specific phrase, which takes a lot of time so that users will not experience progress loss accidents.

**Comment by ojeytonwilliams** [comment]
That seems reasonable to me. Can anyone think of a reason not to go this route?

cc: @huyenltnguyen @ahmaxed

**Comment by naomi-lgbt** [comment]
It's a pretty standard pattern on modern apps, anymore.

**Comment by ahmaxed** [comment]
It is a good idea. I suggest making the phrase short so it is not too laborious.

**Comment by Gylotip** [comment]
> It is a good idea. I suggest making the phrase short so it is not too laborious.

I mean, this is not something you would do occasionally. You would do this maybe one or two times in your life, so the long phrase should remain, in my opinion.
