### ISSUE TITLE
Golang article includes outdated guidance and broken link(s)

### ISSUE THREAD

**Issue by bcdady** [freeCodeCamp/freeCodeCamp#55680]
### Describe the Issue

The [Golang](https://www.freecodecamp.org/news/go-golang-programming-language/) page suggests the Alloy project as a good starting point. There are 2 issues with this suggestion.
1. The link to the Alloy project results in a blank page (in my experience, all pages at the growthmetrics.io domain are blank)
2. The Alloy setup instructions include using [glide](https://github.com/Masterminds/glide), a deprecated tool. It's [README states](https://github.com/Masterminds/glide?tab=readme-ov-file#go-modules) 
> The Go community is now using Go Modules to handle dependencies. Please consider using that instead of Glide. Glide is now mostly unmaintained.

### Affected Page

https://www.freecodecamp.org/news/go-golang-programming-language/

### Steps to Reproduce

Visit <https://www.freecodecamp.org/news/go-golang-programming-language/>

### Recommended fix or suggestions

Option 1: Keep referencing the Allow project, and update Freecodecamp's Golang instructions to use active web links and Golang-native techniques.
Option 2: Update Freecodecamp's Golang instructions to use Golang-native techniques with a different project from Alloy

I volunteer to work on option 1, and welcome community feedback during the PR.

**Comment by bcdady** [comment]
I noticed the owner/maintainer of the Alloy project has made "0 contributions [to GitHub] in the last year", so I think it's a good idea to find an active Golan project to use instead of Alloy.

**Comment by Sembauke** [comment]
Hey @bcdady,

Thanks for letting us know. We are very busy at the moment with the news platform internally, but I have alerted a colleague that operates in this area of the platform.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for bringing this to our attention, @bcdady. I just went in and removed the section referencing Alloy from that article. The update should go live within the next few hours.

Please let us know if you notice issues in this or any other articles on News.
