### ISSUE TITLE
Typo in Scientific Computing with Python (Beta) > Learn Interfaces by Building an Equation Solver

### ISSUE THREAD

**Issue by AlanBrad** [freeCodeCamp/freeCodeCamp#55693]
### Describe the Issue

I have completed this, but noticed there is an error in the code which doesn't seem to cause any problems during the lessons.

In lesson 20 we use an if statement (seen in the first code block below) and the action is `continue`.

This stays the same in steps 21 through 25. However from steps 26 onwards `continue` has been replaced by `coefficient` as highlighted in the second code block below. (Please note that I did not change the code and have pressed Reset a number of times but the code stays the same)

Please advise

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/#learn-interfaces-by-building-an-equation-solver

### Your code

First code block:
```
    def __str__(self):
        terms = []
        for n, coefficient in self.coefficients.items():
            if not coefficient:
                continue
```
Second code block:
```
    def __str__(self):
        terms = []
        for n, coefficient in self.coefficients.items():
            if not coefficient:
                coefficient
```

### Expected behavior

I expect code that passed to stay the same and be correct - is the code in the second code block above correct?

### System

- Device: HP Laptop
- OS: Windows 10
- Browser: Firefox
- Version: 128.0.2

**Comment by Dario-DC** [comment]
Thanks for reporting this. The answer is no, that snippet of code is not correct and it should be fixed.

Each occurrence of
```py
            if not coefficient:
                coefficient
```
should be replaced with
```py
            if not coefficient:
                continue
```
