### ISSUE TITLE
Not able to complete Bonfire task as the Provided tests and their expected results are wrong.

### ISSUE THREAD

**Issue by Sh7K** [FreeCodeCamp/FreeCodeCamp#5569]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Not able to complete Bonfire task as the given tests and their expected results are wrong.

Task-Bonfire: Check for Palindromes

http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20newStr%20%3D%20str.replace(%2F%5Cs%2B%2Fg%2C%20'')%3B%0A%20%2F%2F%20alert(newStr)%3B%0A%20%20var%20checkPalindrome%20%3D%20newStr.split('').reverse().join('')%3B%0A%20%20alert(checkPalindrome)%3B%0A%20%20return%20newStr%3D%3DcheckPalindrome%3Ftrue%3Afalse%3B%0A%20%20%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A

My code:
function palindrome(str) {
  // Good luck!
  var newStr = str.replace(/\s+/g, '');
 // alert(newStr);
  var checkPalindrome = newStr.split('').reverse().join('');
  alert(checkPalindrome);
  return newStr==checkPalindrome?true:false;
  
}
![fcc](https://cloud.githubusercontent.com/assets/16490176/12056247/57f6a1c4-af5a-11e5-9444-754d2270e044.PNG)

palindrome("eye");

```
Unfortunately those highlighted sentences aren't palindrome and hence I cannot complete the task.

**Comment by ltegman** [comment]
From the lesson text:

>You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

Thanks and happy coding!
