### ISSUE TITLE
Should examples of logged strings be inside quotes?

### ISSUE THREAD

**Issue by MonicaZhang1** [freeCodeCamp/freeCodeCamp#55698]
### Describe the Issue

Currently, the description for Step 5 states:

The console allows you to print and view JavaScript output. You can send information to the console using console.log(). For example, this code will print `"Naomi"` to the console:

```
let developer = "Naomi";
console.log(developer);
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-5 

### Your code

```

```

### Expected behavior

The provided code will print `Naomi` without quotes to the console. Since this is part of the introductory Javascript course, some users might expect the quotes to be part of the print statement. To clarify, specify that it prints `"Naomi" without the quotes` or state it prints `Naomi`. 

### System

N/A

**Comment by lasjorg** [comment]
We should probably remove the quotes from logged string values in examples. Seeing as the value that is logged does not have quotes.

We should use quoted strings for string values when asking for value assignments, or DOM string values (like attributes). Not for showing the output of console logs of strings. That is, unless it is logging a quoted value `console.log('"test"')`.

I'm not sure how consistent we are now, but I suspect we are showing quoted values, at least it looks like it.

---

As an aside, the browser console uses syntax highlighting to distinguish between strings and numbers. It would be cool if our console did the same. It is handy that you can see if a value is a string or a number.

**Comment by lasjorg** [comment]
I changed the title, seeing as this isn't isolated to just this challenge step.

**Comment by hiteshkasar** [comment]
We can give more information like **_String_** has to be passed with single/double quotes then that will consider and print as a normal string or sequence of characters. The rest we can pass without quotes like **_Numbers_** and **_Booleans_**.

**Comment by moT01** [comment]
I would say there should not be quotes in descriptions like this.
