### ISSUE TITLE
missed opportunity to teach ascii table character-to-number conversions in spreadsheet proj step 11

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55704]
### Describe the Issue

in the spreadsheet project (js beta), step 11 suggests to campers that in order to create a range of characters, they need to convert their characters to a number. But they never mention why. This would have been a great opportunity to talk about the ASCII table and discuss how letters and their number codes are related instead of just giving instructions that must make absolutely no sense to a beginner.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-11

### Your code

n/a

### Expected behavior

before telling the camper to use .charCodeAt() to convert their single character to "a number", the step should talk about the significance of that number and how it relates back to the character (via a lesson on the ASCII table hopefully). This may involve adding an extra step or two to complete this explanation well.

### System

N/A

**Comment by naomi-lgbt** [comment]
I'd be fine with expanding the text to mention a bit more:

> Your range function expects numbers, but your start and end values will be strings (specifically, they will be single characters such as A).
> 
> Thankfully, every possible character has a corresponding ASCII character code. You can convert a character to its ASCII code with the `.charCodeAt()` method.
> 
> Convert your start and end values in your range() call to ASCII codes by using the .charCodeAt() method, passing the number 0 as the argument to that method.

**Comment by hbar1st** [comment]
I appreciate that but it would still leave everyone in the dark who has never heard of the concept of representing characters as numbers? A real lesson could cover it though.

**Comment by naomi-lgbt** [comment]
Sure, but I don't think it's a concept that necessarily warrants it's own step or lesson. I think it's important to remember that we aren't going to be the single source of information - there's too much to teach.

This seems like a case where providing more information ultimately distracts from the goal, which is teaching the camper how to code.

**Comment by hbar1st** [comment]
Can you elaborate more on why teaching this idea (that characters are represented as numbers) is not warranting of its own lesson.

There's no question that we cannot be the single source of information to all concepts that a programmer needs to know. It's just that in this case, it is such a basic concept that is taught in all intro to programming courses I'm aware of (even at a high-school level).

**Comment by naomi-lgbt** [comment]
Because the spreadsheet project is already overly complicated and shoving more into it isn't going to be helpful? And ASCII codes aren't a deep enough topic to create a whole new project from. And no other project in the curriculum uses charCodeAt - which *might* be something to fix, but honestly the only time I've ever used `charCodeAt` was for leetcode I don't think I've ever used it in production.

**Comment by hbar1st** [comment]
yeah I agree it is overly complicated. But I was of the opinion that explaining why it does things better would be helpful.
I don't really have a comment on teaching charCodeAt per se but I will say that it seems the only time I have ever needed to use something like that in real life was to print out a copyright symbol (and to look up codes for symbols that I didn't want to get translated). That's pretty much it for me.

**Comment by luis-411** [comment]
Hi all,
I noticed this issue and have already created a branch in my fork to work on a solution considering this discussion. I wanted to check if it’s okay for me to proceed with this and submit a pull request, as the issue doesn’t have a "help wanted" label.

Please let me know if there are any specific guidelines or considerations I should follow before opening the PR. Thank you!

My suggestion wold be:

> Your `range` function expects numbers, but your `start` and `end` values will be strings (specifically, they will be single characters such as `A`).
>In computing, characters are often represented as numbers using systems like `ASCII`, where each character has a unique numeric code (e.g., 'A' is 65). This makes it easier to manipulate characters, as we can treat them like numbers.
>Convert your `start` and `end` values in your `range()` call to numbers by using the `.charCodeAt()` method on them, passing the number `0` as the argument to that method.

**Comment by ilenia-magoni** [comment]
@luis-411 the issues open for contribution are those with the 'help wanted' label, this is not one of them
