### ISSUE TITLE
Building a Dice Game - Step 14 - passing with incorrect code

### ISSUE THREAD

**Issue by SucreJ** [freeCodeCamp/freeCodeCamp#55703]
### Describe the Issue

Hey, I found a way to pass this step with a false code. Campers can also have access to the arrays used to test the validity of the code so it's possible to use them.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-14

### Your code

```
function checkForStraights(arr){
  console.log(arr);
  const sorted = arr.sort((a,b)=>a-b);
  console.log(sorted);
  const difference = (sorted[4]-sorted[3])+(sorted[3]-sorted[2])+(sorted[2]-sorted[1])+(sorted[1]-sorted[0]);
  console.log(difference);
  if(difference === 5 || difference === 3){
    updateRadioOption(3, 30);
  }
  if(difference === 4){
    updateRadioOption(3, 30);
    updateRadioOption(4, 40);
  }
  else{
    updateRadioOption(5, 0);
  }
}

rollDiceBtn.addEventListener("click", () => {
  if (rolls === 3) {
    alert("You have made three rolls this round. Please select a score.");
  } else {
    rolls++;
    resetRadioOptions();
    rollDice();
    updateStats();
    getHighestDuplicates(diceValuesArr);
    detectFullHouse(diceValuesArr);
    checkForStraights(diceValuesArr);
  }
});


```

### Expected behavior

The code should not pass because some arrays (for Example [1, 1, 4, 4, 4]) are considered as straights by it even though they're not.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Also If the camper do not put diceValuesArr as the parameter for the function but replace it with another array when called in the event Listener, the code still passes. That's not a major issue though.

**Comment by Medha170** [comment]
I want to work on this issue. Please assign it to me.

**Comment by msudipta888** [comment]
this issue is still open or closed

**Comment by elifortes** [comment]
this issue is still open, I tried the code above and it's still passing.

**Comment by naomi-lgbt** [comment]
> Campers can also have access to the arrays used to test the validity of the code so it's possible to use them.

This isn't really an issue. 

> Hey, I found a way to pass this step with a false code.

Yup. That code doesn't really do what we'd expect. We should probably expand the tests to cover more input possibilities.
