### ISSUE TITLE
spreadsheet project (js beta) step 25 vague instructions

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55708]
### Describe the Issue

Trying to work out a solution for step 25 of the spreadsheet project (js beta) that will be accepted by the test is made harder by the vague instructions.
I attempted several solutions which were not accepted. One of which is below (in the 'your code' section of the template)

The "problem" with this attempt was that I interpreted the instructions differently than the test was expecting.
The instructions say:
> you'll need to round the middle value up.

And so I did that like this:
`  const middle = Math.ceil(length / 2 - 1);`
but the answer wants this to be done in the else statement of the ternary like this:
`: sorted[Math.ceil(middle)];`

I think the instructions need to be clearer or the step needs to be less strict in its checking. (For eg. the instructions could say: If it's odd, round the middle value up and use it to return the number at that index. Do not modify the `middle` variable's initialization statement.)

Another concern is the way the step said:
>If it is, return the average of the number at the middle index and the number after that.

By the time I completed this step I'd forgotten about the function we wrote back on step 23 (I guess I have a bad memory or took a long break in between, who knows?). So I wrote this instead of using the average function:
```
const median = nums => {
  const sorted = nums.slice().sort((a, b) => a - b);
  const length = sorted.length;
  const middle = Math.ceil(length / 2 - 1);
  return isEven(length) ? (sorted[middle] + sorted[middle + 1]) / 2 : sorted[middle];
}
```
Because I had the Math.ceil on the line above the return, the hints were not able to detect the issue.
It would be great if the instructions could be more specific and say "Remember to use your `average` function."

A third suggestion: adding "Don't forget to use the sorted array." may also be a useful tip to give.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-25

### Your code

```
const median = nums => {
  const sorted = nums.slice().sort((a, b) => a - b);
  const length = sorted.length;
  const middle = Math.ceil(length / 2 - 1);
  return isEven(length) ? average([sorted[middle], sorted[middle+1]]) : sorted[middle];
}
```

### Expected behavior

Adding more specific instructions would be helpful if the test requires a very specific answer.

### System

N/A

**Comment by naomi-lgbt** [comment]
Honestly, since we're returning the value (finally) we don't need to test the implementation approach at all. We can just test that the function returns expected values from the inputs.
