### ISSUE TITLE
Python for pentesting solutions wording 

### ISSUE THREAD

**Issue by bchoquer** [freeCodeCamp/freeCodeCamp#55709]
### Describe the Issue

This issue relates to the wording of the python-for-pen-testing curriculum. First, each page has sections for the "video solutions" but since the questions only need a numerical answer the only thing in the section is a number, which is a little confusing. The answer selections are also not numbered, so if you are going to provide a numerical answer to the question the options should be numbered. 
I also noticed that the 'developing an nmap scanner' part 1 and 2 don't provide a description for nmap as a tool which could be applicable here. 

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/python-for-penetration-testing/developing-an-nmap-scanner-part-1.md

### Steps to Reproduce

This is just an issue with the md page, so to view visit the freeCodeCamp/curriculum/challenges/english/09-information-security/python-for-penetration-testing folder in GitHub 

### Recommended fix or suggestions

Add more descriptions to the top of the pen-testing modules with information about nmap, and then fix the wording of the markdown to say answer instead of video solution 

### Screenshots

![Screenshot 2024-07-30 at 7 03 20 PM](https://github.com/user-attachments/assets/e0d55186-154b-4269-ae8b-06882f616b76)

**Comment by ojeytonwilliams** [comment]
Hi, thanks for the report, but, while "--video-solution--" isn't the best wording, it's a developer facing issue and we have [extensive documentation](https://contribute.freecodecamp.org/how-to-help-with-video-challenges/) about how to create a video challenge.
