### ISSUE TITLE
Decrement a Number with Javascript (correct  is --i; but is not accepted)

### ISSUE THREAD

**Issue by pmanolak** [FreeCodeCamp/FreeCodeCamp#5570]
Challenge [Waypoint: Decrement a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-decrement-a-number-with-javascript#?solution=var%20myVar%20%3D%2011%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar--%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 11;

// Only change code below this line
myVar = myVar--;


```

i--; first assign the value and the decrement the value. Here the correct answer in order to get 10 is the operator --i;

**Comment by ltegman** [comment]
When using the `variable--` shorthand you don't assign it. You simply do `variable--` rather than `variable = variable--;`. The lesson explains this.

Thanks and happy coding!
