### ISSUE TITLE
Challeng always showing incorrect

### ISSUE THREAD

**Issue by unaisshemim** [freeCodeCamp/freeCodeCamp#55702]
### Describe the Issue

A2 English for Develpers 
Small Talk - category
level -15
answer- on computers ---> showing the answer is wrong.

### Affected Page

https://www.freecodecamp.org/learn/a2-english-for-developers/learn-conversation-starters-in-the-break-room/task-15

### Your code

```

issue

```

### Expected behavior

should be completed without any errors

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by div02-afk** [comment]
Just checked
The answer for task 15 is : games on computers

**Comment by lasjorg** [comment]
Please use [the forum](https://forum.freecodecamp.org/) for help with the challenges.

As this is not an issue with the challenge, I will close this issue.
