### ISSUE TITLE
build a cash registor rest button not working

### ISSUE THREAD

**Issue by Hudi-Silberg** [freeCodeCamp/freeCodeCamp#55719]
### Describe the Issue

When I am trying to rest the lesson in build a cash register certificate project on js the project doesn't reset

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register

### Your code

```

NA

```

### Expected behavior

Lesson to be rest

### System

- Device: [Ubuntu]
- OS: [Ubuntu 20.04]
- Browser: [Chrome, Firefox]

**Comment by gikf** [comment]
Hey @Hudi-Silberg

To clarify. Have you saved code for that project? In that case, _resetting_ will bring back the saved code, even if it's empty - see this issue #55354.

**Comment by Sembauke** [comment]
Closed as duplicate.
