### ISSUE TITLE
Accessibility Issue - Search bar contrast

### ISSUE THREAD

**Issue by nmbog** [freeCodeCamp/freeCodeCamp#55711]
**Describe the bug**
Per Web Content Accessibility Guidelines, a contrast ratio of at least 4.5:1 is required for normal text to achieve Level AA compliance. A contrast ratio of at least 7:1 is required to achieve Level AAA compliance for normal text.

The current contrast ratio for the search bar (top left corner, 'Search 10,700+ tutorials') is 4.25:1.

**To Reproduce**
See above.

**Expected behavior**
See above.

**Screenshots**
<img width="479" alt="Screenshot 2024-07-30 at 8 10 33 PM" src="https://github.com/user-attachments/assets/22d6dae7-64d5-44d0-b20d-40c76949e8df">
<img width="906" alt="Screenshot 2024-07-30 at 8 30 27 PM" src="https://github.com/user-attachments/assets/6cdfdacb-9f18-4b61-8e68-1ef1ab368943">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Safari
 - Version: 17.4.1

**Comment by honeydewdrop** [comment]
Hi,
When testing, I changed the text/icon colors to an orange (#ffc168) used throughout the files. Is this fine?
Thanks

**Comment by bbsmooth** [comment]
The color for the placeholder text is set to `--gray-15` which is `#d0d0d5`. This gives a contrast of `7:1` with the background. But a reduced opacity of `0.7` is being applied, which brings the contrast ration down just under `4.5:1`. So it seems that we could just raise the opacity a little to get it above `4.5:1`. Using the [WebAIM Contrast Checker](https://webaim.org/resources/contrastchecker/), we would only need to raise it to `0.72` to get it to `4.57:1`. Of course, that's just the bare minimum, I would urge you to raise it even higher :slightly_smiling_face:
