### ISSUE TITLE
Opening new tabs instead of redirecting on current page

### ISSUE THREAD

**Issue by boycech** [freeCodeCamp/freeCodeCamp#55734]
**Describe the bug**
Opening new tabs on the website rather than redirecting current page.

**To Reproduce**
When I click certain links on the website for example from this page :https://www.freecodecamp.org/news/command-line-for-beginners/, If I click 'free 3,000-hour curriculum', 'Forum', 'Donate', or any of the guides below on the bottom it links to new tabs which seems unnecessary unless it was done on purpose and it is a choice made by the team. 

**Expected behavior**
Instead of opening new tabs, it could just redirect on the current page. If I do this activity from the home page it does redirect on the same page rather than opening new tabs like it does here. 

**Desktop (please complete the following information):**
 - OS:  Mac OS
 -  Browser:  safari
macOS Ventura (version 13)

**Additional context**
Please let me know if this is a bug or just a stylistic choice. My main issue is that it opens a lot of tabs on my computer and I always end up having to go through them all to close them.

**Comment by tusharkaran** [comment]
Is this fixed ? can i work on this ?

**Comment by nairvismaya** [comment]
can you assign me this

**Comment by Sembauke** [comment]
Hey @boycech,

This was done on purpose, we want to prevent progress from being lost while doing any learning on the site.
