### ISSUE TITLE
Support popup appears mid tutorials

### ISSUE THREAD

**Issue by codewithtyler** [freeCodeCamp/freeCodeCamp#55745]
### Describe the Issue

Every few lessons I get the Become a Support popup. I don't mind that yall ask for donations but every 2-5 lessons is really annoying. It would be great if you could make it so that it only pops up once you complete an entire module like completing the Cat Photo App module or the Cafe Menu module rather than it popping up every 3-5 lessons within the 69 lessons of the Cat Photo App module. It would also be nice for those of us who can't afford to donate to have an option underneath the ask me later to set it the popup to don't ask me again. If I had the means to support I would.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-7

### Steps to Reproduce

1. Go through the Cafe Menu module
2. Continue through the lessons
3. You'll see the popup every few lessons

### Expected behavior

Show the popup at the end of the the entire module and give me the option to not show this popup again and if clicked save that setting to my account. You can even add a setting in my account to re-enabled the popup. If you don't want to add the link to disable the popup then at least fix it so that the popup appears at the end of the module.

### Screenshots

![image](https://github.com/user-attachments/assets/a3a4c5f7-dad5-437b-8ee3-083d33d9eec7)

### System

- Device: Custom Build Desktop Computer
- OS: Windows 10
- Browser: Chrome
- Version: 127.0.6533.89

**Comment by moT01** [comment]
Thanks for your input @codewithtyler 👍 

We are continuously adjusting our methods to try and get more supporters without it turning people away - so this is constantly changing.

Every 2-5 lessons does seem like it might be a bit much. Just floating an idea - what if we had a second modal that was shorter/faster to show during the middle of the project instead of this one. Then show this one at the end of projects.

**Comment by codewithtyler** [comment]
I think one at the halfway point of the module and one at the end of the module would be way better than what it is now.

**Comment by ahmaxed** [comment]
Thank you for reporting this. It should be every 20. I am investigating.

**Comment by ahmaxed** [comment]
I was wondering if you refresh your page every few challenges?

**Comment by codewithtyler** [comment]
I have the following extensions installed:

- Bitwarden
- Dark Reader
- UBlock Origin
- vidIQ Vision for YouTube
- IPX - Influencer Profits Extension
- Global Twitch Emotes
- Keepa
- Anori

**Comment by ahmaxed** [comment]
@huyenltnguyen, thanks for looking into it.

That is all true, but the logic changes when a user is shown the modal.

https://github.com/freeCodeCamp/freeCodeCamp/blob/6b9979ae50cd7202d85beab843729d9b3d2322fe/client/src/redux/selectors.js#L56-L60

So the current logic in summary is the following:

If a user has not completed 10 challenges in total, show the modal after 10th challenge and every 20 after that.
If a user with more then 10 completed challenges, show the modal after 3 challenges and every 20 after that.

Let me know if you see any inconsistencies in the logic.

**Comment by ahmaxed** [comment]
@codewithtyler, appreciate it.

Could you confirm that you are having the same issue when using your browser in incognito mode where there are no active extensions?

Also, what are the ways you close/skip the donation modal?

**Comment by ahmaxed** [comment]
Since the length of the video is 20 seconds, we do want to show the modal if the modal was displayed less than 20 seconds ago. Here is the related pr for more context: https://github.com/freeCodeCamp/freeCodeCamp/pull/54817

**Comment by ojeytonwilliams** [comment]
Ah, I see the logic. It's so you can't simply reload the page to skip? It might help to explain that in the saga, since it's not obvious from the code.

**Comment by codewithtyler** [comment]
> If a user has not completed 10 challenges in total, show the modal after 10th challenge and every 20 after that.
> If a user with more then 10 completed challenges, show the modal after 3 challenges and every 20 after that.

I think this is what I'm seeing. I think my confusion is in the fact the code @huyenltnguyen showed above mentions that it does the check per session. Seeing as I'm spending multiple days in a row going through the modules it may seems like it's a bit much. I do like @moT01's suggestion of having the modal show in the middle and again at the end of each module. This way you still suggest the donation but it comes across as less aggressive to people.

**Comment by hbar1st** [comment]
I've also noticed the donation box appear at inconsistent times. I tried to stay vigilant and take screenshots each time but i eventually forgot to keep doing it for my proof. I have some screenshots though (I started taking screenshots at step 9, and then again at 29 and 49 which seems consistent with every 20 steps except that I started with step 9, not 3?? not sure how that happened, but I definitely did see the modal at step 3 too, it is just that by the time I decided to try to screenshot it, I was already at step 9 then). This was the js platformer project btw if that makes any diff. Unfortunately I didn't keep up the screenshots after step 49. Sorry about that!) My theory is that because I switch between my laptop and my cell-phone when working on challenges, that something about that switch caused the 'jump'.

**Comment by ahmaxed** [comment]
@hbar1st, if you close browser/tab or refresh your page, the logic might restart.

**Comment by hbar1st** [comment]
Oh okay. Are you aware of the performance issue that was being discussed (the editor would perform slowly on occasion)? The workaround for this is to close the tab and reopen it. I’ve been doing this on occasion to make sure I get the fastest performance. This would then explain why it would seem that the donation popup shows up every few steps.

**Comment by ahmaxed** [comment]
Thanks for letting me know. I will try to keep the logic somewhere else to make sure it does not interfere with refreshes.

**Comment by codewithtyler** [comment]
Performance issues aside. I think I identified my issues above based on @ahmaxed's comment. I'm curious to hear what everyone thinks about @moT01's suggestion of having the modal appear twice: once midway through the module and one at the end of the module. This in my opinion would mitigate the issue of the modal feeling annoying at times.

**Comment by ahmaxed** [comment]
I will make sure to AB test Tom's idea to see how it effects user behaviour.

**Comment by ahmaxed** [comment]
We would need to move the completionCount state from the redux store to sessionStorage so it will not be effected by refreshes.

**Comment by ahmaxed** [comment]
@hbar1st, I am wondering if you still experiencing the slow down. It seems to have been resolved. 
https://github.com/freeCodeCamp/freeCodeCamp/issues/55745
Could you do a hard refresh and see if the issue have been resolved?

**Comment by moT01** [comment]
To clarify my suggestion earlier - I meant that we could have a shorter modal to show in the middle of projects - not just once in the middle of the project, but many times (if needed) in the middle of the project. Projects have great variability in length, so I think we still need to show it more than once in places. e.g. some projects are 20 steps long, some are almost 200.

**Comment by moT01** [comment]
I looked around a little and found a few issues related to the editor slowing down (there may be more):
https://github.com/freeCodeCamp/freeCodeCamp/issues/55017
https://github.com/freeCodeCamp/freeCodeCamp/issues/54736
https://github.com/freeCodeCamp/freeCodeCamp/issues/54716

Looks like a number of steps have been taken to improve things.

**Comment by hbar1st** [comment]
@ahmaxed unfortunately I am not working on any curriculum at the moment but I will keep an eye out if I return to it.

**Comment by ahmaxed** [comment]
Thanks for the suggestion, I will add that to the AB test queue.

**Comment by codewithtyler** [comment]
You're welcome and thank you to being open to my ideas.
