### ISSUE TITLE
spreadsheet project (js beta) step 102 should say that the input array will be sorted

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55746]
### Describe the Issue

The instructions for step 102 of the spreadsheet project (js beta) want us to "use the first two numbers from an array to generate a random whole number." They also say that "The range for this number starts at the smaller positive number (inclusive) among the first two numbers and ends just before the sum of these two numbers." 
However, looking at the solution, no effort is made to sort out which number is smallest before finding the random value.
This tells me that this step is assuming we know that the array is in ascending sorted order.

I would like the step to just say this explicitly. For eg it could say:
Create a random property. This property should use the first two numbers from an array that has been sorted in ascending order to generate a random whole number. 

(the change is I said 'an array that has been sorted in ascending order')

Or, we could just not care in what order the random number gets generated? (and change the instructions to say to get a random number between the first two numbers of the array regardless of which one goes first?)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-102

### Your code

N/A

### Expected behavior

instructions can be more explicit or checks can be more lenient

### System

N/A

**Comment by gikf** [comment]
I wrote about this also on discord - I'm not sure why the constraint to have the first number smaller. There's no reason to not allow first number to be higher than second one. Both will give number from different, valid ranges:
- `=random(5, 10)` -> number from `5` to `14`.
- `=random(10, 5)` -> number from `10` to `14`.

**Comment by naomi-lgbt** [comment]
Yeah, I'd just update the text to say:

> Create a random property. This property should use the first two numbers from an array to generate a random whole number. The range for this number starts at the first number (inclusive) of the two and ends just before the sum of these two numbers. Use the Math.floor() and Math.random() methods for the calculation.
