### ISSUE TITLE
dice game (js beta) - step 13 instructions are incorrect

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55760]
### Describe the Issue

in step 13 of the dice game (js beta), the instructions say:
>Your detectFullHouse function should check if the user has rolled three of one number and two of another number. If so, it should update the third radio button to display a score of 25, with the correct attributes. If not, it should update the last radio button to display a score of 0, with the correct attributes.

However when we look at the code in the following step 14 for this function we see this:
```js
const detectFullHouse = (arr) => {
  const counts = {};

  for (const num of arr) {
    counts[num] = counts[num] ? counts[num] + 1 : 1;
  }

  const hasThreeOfAKind = Object.values(counts).includes(3);
  const hasPair = Object.values(counts).includes(2);

  if (hasThreeOfAKind && hasPair) {
    updateRadioOption(2, 25);
  }

  updateRadioOption(5, 0);
};
```

Notice how the last radio button is updated regardless of the full house check? But the instructions said: "If not, it should update the last radio button...".
People are trying to follow this instruction and failing and not understanding why (they use an if-else statement for example as in the code below)

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-13

### Your code

```
/* file: script.js */
// User Editable Region

const detectFullHouse = () => {
  const counts = {};

  for (const num of diceValuesArr) {
    if (counts[num]) {
      counts[num]++;
    } else {
      counts[num] = 1;
    }
  }

  const values = Object.values(counts);
  if (values.includes(3) && values.includes(2)) {
    updateRadioOption(2, 25);
  } else {
    updateRadioOption(5, 0);
  }
};

const resetRadioOptions = () => {
  scoreInputs.forEach((input) => {
    input.disabled = true;
    input.checked = false;
  });

  scoreSpans.forEach((span) => {
    span.textContent = "";
  });
};

const resetGame = () => {
  diceValuesArr = [0, 0, 0, 0, 0];
  score = 0;
  round = 1;
  rolls = 0;

  listOfAllDice.forEach((dice, index) => {
    dice.textContent = diceValuesArr[index];
  });

  totalScore.textContent = score;
  scoreHistory.innerHTML = "";

  currentRoundRolls.textContent = rolls;
  currentRound.textContent = round;

  resetRadioOptions();
};

rollDiceBtn.addEventListener("click", () => {
  if (rolls === 3) {
    alert("You have made three rolls this round. Please select a score.");
  } else {
    rolls++;
    resetRadioOptions();
    rollDice();
    updateStats();
    getHighestDuplicates(diceValuesArr);
    detectFullHouse();
  }
});

// User Editable Region
```

### Expected behavior

The instructions should be changed to match the requested code:

Your detectFullHouse function should check if the user has rolled three of one number and two of another number. If so, it should update the third radio button to display a score of 25, with the correct attributes. It should also update the last radio button to display a score of 0, with the correct attributes.

However, I noticed that the functions getHighestDuplicates and detectFullHouse are both updating the last radio button. So it seems like one of these need not do that? (so we could just not ask for this in this step since it is gonna get updated elsewhere anyway?)

### System

N/A

### Additional context

I noticed this issue when I was attempting to help a camper on the forum:
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-13/704683/2

https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-13/700417/4?u=hbar1st

**Comment by RomeoIndiaJulietUniform** [comment]
I don't know why we are updating the (5,0) radio button when there is a non zero value i.e. full house, three of a kind, four of a kind ? Anything positive integer will result in more high score. I think we should only implement the last radio button the zero one when nothing above works.  

If you any confirmed implementation logic, I would like to work on this issue :)

**Comment by naomi-lgbt** [comment]
I propose updating the text to:

> Your detectFullHouse function should check if the user has rolled three of one number and two of another number. If so, it should update the third radio button to display a score of 25, with the correct attributes. Regardless, it should always update the last radio button to display a score of 0, with the correct attributes.

**Comment by naomi-lgbt** [comment]
> I feel like updating the last radio should just happen independently of the various functions like getHighestDuplicates or detectFullHouse

In a production app, sure. Here, I think the reinforcement of how `if` conditions work and how code after an `if` block executes and such is good.

**Comment by hbar1st** [comment]
Okay fair enough, thanks.
