### ISSUE TITLE
Waypoint: Decrement a Number with Javascript You can easily decrement or decrease a variable by one with the -- operator.  i--;  is the equivalent of  i = i - 1;  Instructions Change the code to use the -- operator on myVar

### ISSUE THREAD

**Issue by marksayers96** [FreeCodeCamp/FreeCodeCamp#5576]
Challenge [Waypoint: Decrement a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-decrement-a-number-with-javascript#?solution=var%20myVar%20%3D%2011%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%3B%0A%0AmyVar%20--%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS armv7l 7520.62.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
var myVar = 11;

// Only change code below this line
myVar = myVar;

myVar --;
```javascript
var myVar = 11;

// Only change code below this line
myVar = myVar;

myVar --;
```

**Comment by ltegman** [comment]
The space is valid syntax and the regex should be adjusted to account for it.

**Comment by lasred** [comment]
What exactly was the issue here?

**Comment by SaintPeter** [comment]
This issue should have been resolved with my pull request.  I added a "\s*" between the variable and the ++ and -- checks, to allow whitespace.  This issue can been closed for a long time.
