### ISSUE TITLE
Error do not change above the line

### ISSUE THREAD

**Issue by theWhiteFox** [FreeCodeCamp/FreeCodeCamp#5577]
Challenge [Waypoint: Storing Values with the Equal Operator](http://www.freecodecamp.com/challenges/waypoint-storing-values-with-the-equal-operator#?solution=%2F%2F%20Setup%0Avar%20a%20%3D%207%3B%0Avar%20b%20%3D%20a%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var a = 7;
var b = a;

// Only change code below this line
 

```

**Comment by ltegman** [comment]
This is not a bug. Variables can be changed after instantiation, so you can do what the instructions ask below the comment.

**Comment by theWhiteFox** [comment]
OK thanks "change code below the line.

**Comment by VSatyavani** [comment]
// Setup
var a;
var b = 2;
// Only change code below this line
var a=7;
b=a;

**Comment by VSatyavani** [comment]
// Example
var ourVar = 19;

// Only change code below this line
var a = 9; // This is equal to 9

**Comment by VSatyavani** [comment]
// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";

a = 6;
b = 15;
c = "I am a String!"

**Comment by RandellDawson** [comment]
@VSatyavani Please use the [forum](https://freecodecamp.org/forum) to ask questions concerning trouble with a challenge.  Thank you.
