### ISSUE TITLE
Bonfure Meet Bonfire

### ISSUE THREAD

**Issue by jazzthespazz** [FreeCodeCamp/FreeCodeCamp#5579]
Explanation:

This is very simple, they just want you to get familiar with how their Bonfires work.

The they should be we.

**Comment by ltegman** [comment]
I'm not sure where you're seeing the text you're referring to. I don't see it in that Bonfire.

**Comment by jazzthespazz** [comment]
Sorry, I mean on the solution page thingy....

**Comment by ltegman** [comment]
The solutions are written by the community, meaning `they` may be more appropriate than `we` depending on who wrote it, so this isn't an issue.

Thanks and happy coding!
