### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue 

### ISSUE THREAD

**Issue by polivmi1** [FreeCodeCamp/freecodecamp#558]
Syntax error, unrecognized expression
Syntax error, unrecognized expression

instead of tasks

**Comment by terakilobyte** [comment]
Could you provide a screenshot of this? I'm unable to reproduce it.

**Comment by denmch** [comment]
It happens for me in Safari:
![screen shot 2015-05-26 at 12 30 15 pm](https://cloud.githubusercontent.com/assets/2019665/7821356/02087412-03a3-11e5-8771-5d0168ad8bf4.png)

**Comment by polivmi1** [comment]
![screen](https://cloud.githubusercontent.com/assets/5646007/7821392/9edb663c-03ee-11e5-8bf9-21448f8afd40.png)

Firefox 38.0.1 ...happens with tasks 30,35,36,38

**Comment by terakilobyte** [comment]
ok, thanks. Are you running any browser addons?

**Comment by polivmi1** [comment]
Adblock Plus, but happens if it is off

**Comment by QuincyLarson** [comment]
We've fixed this. Thank you for your patience, and for bringing this to our attention!
