### ISSUE TITLE
Example texts being incorrectly highlighted in Build a Gradebook App

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#55803]
## Description

The example texts are plain text so they shouldn't have syntax highlighting applied.

<img width="584" alt="Screenshot 2024-08-10 at 00 06 57" src="https://github.com/user-attachments/assets/73295d64-37a5-4283-94f8-5cb9e0231557">

## Affected page

- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-js-fundamentals-by-building-a-gradebook-app/step-1
- https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-js-fundamentals-by-building-a-gradebook-app/step-4

## Changes needed

Remove `js` from the following code blocks:
- https://github.com/freeCodeCamp/freeCodeCamp/blob/18fe86897e07e9e027a7d9f4beb78f369c63d361/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-js-fundamentals-by-building-a-gradebook-app/662693f82c91a66be46c881b.md#L16
- https://github.com/freeCodeCamp/freeCodeCamp/blob/18fe86897e07e9e027a7d9f4beb78f369c63d361/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-js-fundamentals-by-building-a-gradebook-app/6626b8dcf5057f896f948440.md#L16
- https://github.com/freeCodeCamp/freeCodeCamp/blob/18fe86897e07e9e027a7d9f4beb78f369c63d361/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-js-fundamentals-by-building-a-gradebook-app/6626b8dcf5057f896f948440.md#L22

**Comment by abhayrsr** [comment]
Hi, I am a first-timer here. Would love to work on this issue.

**Comment by dhruv0206** [comment]
Hi, I am first time contributor, Please assign me this task.

**Comment by gikf** [comment]
@huyenltnguyen, to clarify is the intent to remove the `js`, but keeping the formatted block (from what I remember the bare ` ``` ` might not be allowed, it might be required to use different _lang_ instead - `md`, `markup`, etc.). Or remove the ` ```js ``` ` completely?

**Comment by uditbaliyan** [comment]
I'd love to work on this "good first issue." I've gone through the contribution guidelines and the relevant files. Could you please assign it to me?

**Comment by uditbaliyan** [comment]
Syntax Highlighting
Many Markdown processors support syntax highlighting for fenced code blocks. This feature allows you to add color highlighting for whatever language your code was written in. To add syntax highlighting, specify a language next to the backticks before the fenced code block.

This info is from https://www.markdownguide.org/extended-syntax/

**Comment by uditbaliyan** [comment]
![image](https://github.com/user-attachments/assets/73852665-3106-485f-a9b6-125ce6f87c96)

removing js was working fine on my github markdfown viewer

![image](https://github.com/user-attachments/assets/d5e4f0e1-e137-4133-9877-d62cab5e7a72)

**Comment by lasjorg** [comment]
Wouldn't updating the pseudo code with actual code examples make more sense?

```js
`Class average: ${someAverage}. Your grade: ${someGrade}. You passed the course.`
```

```js
`Class average: ${someAverage}. Your grade: ${someGrade}. You failed the course.`
```

```js
average = total / count
```
