### ISSUE TITLE
Build a Mario Database Unable to complete due to bug

### ISSUE THREAD

**Issue by Alexeigithubproject** [freeCodeCamp/freeCodeCamp#55801]
### Describe the Issue

Hello, I've tried completing the Build a Mario Database about two times now, and reach almost 50%, around that time, the terminal stops showing me the Tables and databases I've created when i type  \l or SELECT * FROM characters. However the test WILL accept the input and will count it as correct.

The issue is though that nothing is being displayed anymore and i don't know what to fix if i mistakenly insert something incorrect.

So i was stuck on +- 50%  and tried hitting the reset button. When i did that the connection was lost and i could not go on anymore. So the reset button is definitely not working there.

This has happened twice now and i really don't feel like taking  this test again. If i complete the other tests is there a way for you to complete this one for me

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-relational-databases-by-building-a-mario-database/build-a-mario-database

### Your code

```

--

```

### Expected behavior

I would expect for the reset button to work as expected.

I would like to have this autocompleted if possible, when i complete the other tests

### Screenshots

![image](https://github.com/user-attachments/assets/5fed8984-6fe5-4680-b8b9-7e0e3254002b)

This is the 3rd time it happens

### System

- Device: PC
- OS: [ Windows 11]
- Browser: [ Chrome]
- Version: latest

**Comment by gikf** [comment]
Hey,

Thank you for reporting this issue.

Could you clarify couple things?
- Do you remember what was the task when the problem appeared?
- How exactly terminal behaves when it happens? Does it not show anything at all? Is anything new that's attempted to be written to it?

**Comment by Alexeigithubproject** [comment]
Hello,

Well if i remember correctly, this happened when i few steps after i created the characters table and started adding rows. Not entirely sure at which step to be honest.

I apologize if i don't use the correct terms here, but i am not a programmer so i'll try my best :D

The behavior is this: i am asked to view my table 
-I type SELECT * FROM characters
-I hit enter and the table in the terminal does not show, it just takes me to the next line 
- If i hit ctrl + Enter the step will be completed

Not sure about your last question, but I can only say this, I would probably be able to complete the exercise without viewing the tables but i am pretty sure that i must have replaced some rows with wrong data as i was not sure which ID i had to use. 

So, i tried to reset but the connection keeps getting lost, (see SS)

I hope i answered your questions!

**Comment by gikf** [comment]
It's normal that after reset, connection is being lost and psql needs to re-connect. Unless issues with connection are persisting after that.

> The behavior is this: i am asked to view my table
> -I type SELECT * FROM characters
> -I hit enter and the table in the terminal does not show, it just takes me to the next line

This description sounds like there might be missing semicolon at the end of line. In such case command is not executed, but prompt waits for the rest of the command and ending semicolon. I'm not sure if in such case test would pass though.

**Comment by Alexeigithubproject** [comment]
Here is the same issue:

I am after the step that I create the first_database. I accidentally typed "CREATE DATABASE first_database;" twice, and then tried to hit \l, but it didn't show anything
![image](https://github.com/user-attachments/assets/264c5c5b-e3d7-4a0f-8e0f-1013be2b1634)

Tests pass but i get nothing in the terminal

![image](https://github.com/user-attachments/assets/95a2d1fb-736f-4e4b-bfc3-47c8882131dc)


I have tried connecting back to the database by entering"psql --username=freecodecamp --dbname=postgres"
after the RESET but it did not succeed at the step i was. However, it appears that it does work early on in the course.

**Comment by gikf** [comment]
That's strange indeed. So far I wasn't able to reproduce the issue. Could you share the history of the terminal from before screenshots were taken as well?

Could you try closing the _stuck_ terminal with psql and running psql again in another one?

**Comment by naomi-lgbt** [comment]
I'm going to go ahead and close this as CNR. If we receive reproducable steps to trigger this error, we can re-evaluate.
