### ISSUE TITLE
Solution already solved upon starting new waypoint 

### ISSUE THREAD

**Issue by ryanfristoe** [FreeCodeCamp/FreeCodeCamp#5581]
Challenge [Waypoint: Multiply Two Numbers with JavaScript](http://www.freecodecamp.com/challenges/waypoint-multiply-two-numbers-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var product = 8 * 10;

// Only change code above this line.

(function(z){return 'product='+z;})(product);

```

the solution was already solved for upon starting the new waypoint. This happened for the new addition, subtraction, and the multiplication waypoints.

**Comment by abhisekp** [comment]
@ryanfristoe The solution comes with the default source `var product = 8 * 0;`
You need to put a `1` before the `0` to make the `product = 80`

**Comment by ltegman** [comment]
This means you or someone else using your computer has completed this waypoint before the changes. The seed code does not look like this, so it is coming from the copy saved to your localStorage. You can press the reset button if you would like to start fresh.

Thanks and happy coding!
