### ISSUE TITLE
Missing tests for check correct indentation - Step 6

### ISSUE THREAD

**Issue by ewaforman** [freeCodeCamp/freeCodeCamp#55839]
### Describe the Issue

User has to use the space bar on keyboard to add two more spaces in front of the p element. After adding these two spaces test passes. But when user adds more spaces for other elements like main or h1, tests also pass - although html is not easy to read.  Should it works that way? Should tests pay attention for all spaces not only for h2 and p elements in this case?

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-6

### Your code

```
                  <main>
           <h1>CatPhotoApp</h1>
      <h2>Cat Photos</h2>
      <!-- TODO: Add link to cat photos -->
      <p>See more cat photos in our gallery.</p>
                             </main>


```

### Expected behavior

Whole html text should be easy to read and tests should check all html lines and elements, not only spaces for h2 and p elements.  

### Screenshots

![Screenshot_232](https://github.com/user-attachments/assets/e0b39445-c8af-419c-896f-d69de7370ff9)

### System

- Device:  Laptop
- OS: Windows 11
- Browser: Chrome Version: 127.0.6533.99

**Comment by naomi-lgbt** [comment]
IMHO, this step is fine as-is.
