### ISSUE TITLE
Test case bug in Concatenating Strings with Plus Operator waypoint

### ISSUE THREAD

**Issue by nathan-q** [FreeCodeCamp/FreeCodeCamp#5583]
In the waypoint, a solution with single quotes returns an error.

![screenshot from 2015-12-30 13 01 16](https://cloud.githubusercontent.com/assets/15369999/12057486/74bf9766-aef6-11e5-9806-5ab686ea9841.png)

The same answer with double quotes returns a correct submission.

![screenshot from 2015-12-30 13 01 16](https://cloud.githubusercontent.com/assets/15369999/12057498/9b495822-aef6-11e5-8d51-ea8b00797edf.png)

The code for the waypoint currently:

"solutions": [
        "var ourStr = \"I come first. \" + \"I come second.\";\nvar myStr = \"This is the start. \" + \"This is the end.\";"

Maybe a solution:

"solutions": [
        "var ourStr = \"I come first. \" + \"I come second.\";\nvar myStr = \"This is the start. \" + \"This is the end.\";\nvar myStr = \'This is the start. \' + \'This is the end\';\nvar myStr = \"This is the start. \" + \'This is the end\';\nvar myStr = \'This is the start. \' + \"This is the end\";"

**Comment by nathan-q** [comment]
Correct screen shot for the double quote case:

![screenshot from 2015-12-30 13 01 55](https://cloud.githubusercontent.com/assets/15369999/12057596/7c227824-aef7-11e5-9ba4-97088322fb55.png)

**Comment by fdolzanes1** [comment]
`var myStr = "This is the start." + " This is the end.";`

**Comment by IshemaJohnRobert** [comment]
tnx morefdolzane1

**Comment by meizaifeng** [comment]
`var myStr = "This is the start. " + "This is the end.";   //"This is the start. "There is a space `

**Comment by LogicBlows** [comment]
"This is the start."+" "+ "This is the end.";
