### ISSUE TITLE
fcc authors page project skips too many concepts that need to be explained before step 2 is presented

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55845]
### Describe the Issue

In step 2 of the fcc authors page project (js beta), the following intro paragraph is provided:
>The Fetch API is a built-in JavaScript interface to make network requests to a server. It has a fetch() method you can use to make GET, POST, PUT, or PATCH requests. In this project, you'll make a GET request to a URL for a JSON file with information about authors on freeCodeCamp News.

We have quite a few concepts here that a beginner would have no clue about and they're being presented here with zero introduction.
1- API - does anyone who has never programmed before know what an API is?
2- built-in interface - again, what should people understand  from these words having never been exposed to interfaces or whatever is meant by 'built-in' here?
3- network requests - maybe people know that 'network' is the internet, but do they have an idea about what a request is?
4- JSON file - we haven't talked about JSON files at all. Or even what JSON format is except if you count talking about JSON.stringify back in the todo list app.

It seems like these concepts may represent a whole project that is missing? Or maybe this 29 step project really needs at least 4 more steps to give even the smallest intro for these concepts? Or at the very least, can we simplify the text of this step -drastically- to just say something more easily digestible by a newbie (perhaps this is the hardest of all options)?

Note that it isn't until we get to the "Back End Development and APIs" curriculum that we are introduced to the concepts above. Here's the intro from Basic Node and Express section:
https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/serve-json-on-a-specific-route

To be clear about where I stand, I wholeheartedly think that an earlier introduction to these concepts belongs in a JS course, absolutely yes. I just want it to be a much more complete one than the above sentence.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-fetch-and-promises-by-building-an-fcc-authors-page/step-2

### Your code

N/A

### Expected behavior

define the new concepts over a number of steps or rewrite step 2 to use words that the camper has already learned about

### System

N/A

**Comment by lasjorg** [comment]
We could certainly provide some definition and brief descriptions for parts of this. But we can't get people programming quickly and also teach them computer science at the same time.

---

As an aside. It makes it sound like the fetch API is part of JavaScript, when in fact it is part of the [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API). The runtime must support it (e.g. it wasn't even in Node until more recently). Part of the text is taken almost verbatim [from MDN](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), but the changes to it, makes it sound like it is a core JavaScript feature and not part of the Web APIs.

**Comment by hbar1st** [comment]
It sounds like we agree that something is missing in this step in terms of providing some definitions or explanation.

But just to throw it out there, if I want to not use any of these new terms to explain something like this I may say (please don't take this as a suggestion to change the text but just as an illustration of how the text can be changed to make it more digestible)

At some point in your coding journey you'll need to get some data from the internet. For example, you may need to work on creating a weather app and need to get weather predictions from an online source to do that. This data can be retrieved by asking for it online from the server (that is, a computer) that has this data. To do this we need to make use of an API (Application Programming Interface) which is a layer of code created to allow people outside an organization to access its internal data. It is similar to an app you would use to order products online but the code in this case allows you to request data instead.

Here is how you can make a GET request with the fetch() method (which is just a type of request that gets data):

`fetch("url-goes-here")`

Make a GET request to this URL: "https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json". Don't terminate your code with a semicolon yet.

**Comment by naomi-lgbt** [comment]
Opening this one up if anyone is interested in poking at it.

**Comment by a2937** [comment]
I almost prefer just simplifying all the terms for this step. Though I really think at some point there should be some kind of computer science intro that explains what XML and JSON files are before the start of the curriculum.
