### ISSUE TITLE
Pyramid Project (JS Beta) - Step 50 Semicolon check too strict

### ISSUE THREAD

**Issue by Bharath314** [freeCodeCamp/freeCodeCamp#55855]
### Describe the Issue

Not adding a semicolon in [Step 50](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-50) can cause the step to not pass. A semicolon isn't really necessary here.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-50

### Your code

```
console.log(call)
```

### Expected behavior

The test should pass even without the semicolon.

### Screenshots

![image](https://github.com/user-attachments/assets/daed8503-0bbd-4b73-ad96-1196e33a2399)

### System

n/a

**Comment by PD1710** [comment]
I have debugged the problem. To run the code without using semicolons, you should avoid using a semicolon where you call "call = padRow()."

**Comment by lasjorg** [comment]
It is intentional. You can voice your opinion on this in the related issue.

https://github.com/freeCodeCamp/freeCodeCamp/issues/53694
