### ISSUE TITLE
Learn Advanced Array Methods by Building a Statistics Calculator (Step 26) – wrong validation

### ISSUE THREAD

**Issue by Kaylen7** [freeCodeCamp/freeCodeCamp#55866]
### Describe the Issue

I passed all checks without using the sorted array for calculating the median. I am guessing the checks use an initial array that is already sorted ?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-26

### Your code

```
const getMedian = (array) => {
  const sorted = array.sort((a, b) => a - b);
  if (array.length % 2 === 0){
    return getMean([array[array.length/2], array[array.length/2-1]])
  }
  return array[Math.floor(array.length/2)]
}
```

### Expected behavior

My input should not pass validation, as it does not use the sorted array. 

### System

- Browser: Brave

**Comment by sanjeevmurmu** [comment]
Actually the sort method changes the original array to its sorted version which is why it is passing all the checks in case you don't want the original array to be altered you have to use the toSorted method

**Comment by Kaylen7** [comment]
True! Now that I think of it this is explained in Step 58, where `.slice()` is used before `.sort()` to make a shallow copy of the array. Then the issue should be about moving this explanation to step 26 or perhaps commenting the fact that the original array is mutated... 🤔

In step 27, the provided code calls `sorted`, that's why I thought calling `array` should not pass checks.

**Comment by lasjorg** [comment]
Step 21 should definitely explain that `sort` mutates the array. That or we need a new step to explain it and the alternatives such as creating a shallow copy or using `toSorted`.

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-21



This text in Step 26

> Make sure to work with the `sorted` array to find the middle numbers.

Completely ignores the array mutation. Mutating the array and then suggesting the return value has to be used makes it sound like the method is non-mutating. Sure, the variable name `sorted` is better but the array mutation should not be ignored.

If the requirement is to use `sorted` that test needs a regex.

---

Just in general, if we are not relying on the array mutation (which we really shouldn't) we should create a copy or use `toSorted`. Mutating an array and treating it as if it wasn't is a really bad idea.

**Comment by lasjorg** [comment]
I would suggest we:

1. Briefly mention `sort` mutates the array in step 21.
2. Add a new step between 25-26 that changes `sort` to `toSorted` and explains the difference.
3. Update step 26 (now 27 with the new step added) to not use a mix of `array` and `sorted` for no reason, and test for the use of the `sorted` variable.
4. Update the function in the seed code for all remaining steps:

```
const getMedian = (array) => {
  const sorted = array.toSorted((a, b) => a - b);
  const median =
    sorted.length % 2 === 0
      ? getMean([sorted[sorted.length / 2], sorted[sorted.length / 2 - 1]])
      : sorted[Math.floor(sorted.length / 2)];
  return median;
}
```

**Comment by naomi-lgbt** [comment]
Opening this up for contribution. A PR which resolves this issue will follow lasjorg's suggestion above.
