### ISSUE TITLE
Script displayed in preview when using specific CSS

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#55861]
### Describe the Issue

Someone on the forum reported unexpected behaviour from the fcc editor here:
https://forum.freecodecamp.org/t/cash-register-cryptic-error-in-preview-screen/705785

Can someone take a look because it is not clear whether it is a bug or a limitation?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register

### Your code

```

* {
  margin: 0;
  padding: 0;
  display: block;
}

```

### Expected behavior

CSS should not cause errors in editor

### System

Laptop/windows/chrome

**Comment by lasjorg** [comment]
It isn't related to the editor, it would happen in any environment. The script tag in the head has `display: none` by default given to it by the browser. It happens with the title element as well, the text that should only be a window/tab title will appear on the page.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>This is a title, not a page element</title>
    <link rel="stylesheet" href="styles.css" />
    <script>
      "this should not be visible";
    </script>
  </head>
  <body>
    <script src="script.js"></script>
  </body>
</html>
```

```css
* {
  display: block;
}
```

**Comment by hbar1st** [comment]
That is interesting and good to know. I am okay with whatever is decided as my only concern was getting the issue looked into just in case there was something that required a response of some kind.

**Comment by naomi-lgbt** [comment]
I'm going to go ahead and open this for contribution.

A PR which resolves this issue should:
- Update the `createHeader` function to inject the following CSS:

```css
  <style>
    head *, script {
      display: none !important;
    }
  </style>
```

- Add a regression test to ensure these elements cannot be rendered in the preview.

**Comment by Ayushjhawar8** [comment]
naomi how to add a regression test .. can you teach?

**Comment by Othniel01** [comment]
@naomi-lgbt 

Hi I am new here, I was able to make this contribution. I hope it helps. 
My pull request addresses the issue where script elements were being rendered in the preview mode, causing confusion for people.

at #56570
