### ISSUE TITLE
Saving your code closes editor panes

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#55864]
### Describe the Issue

I didn't test this too thoroughly, but when writing code for one of the savable projects, I saved my code and the CSS pane closed.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form
2. Open both the HTML and CSS editor panes
3. Write some code in one of them
4. Click the "save your code" button or press `ctrl+s`
5. The CSS pane closes

### Expected behavior

The panes should stay how I had them.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Possibly somewhat related: https://github.com/freeCodeCamp/freeCodeCamp/issues/55619

**Comment by sanjeevmurmu** [comment]
Along with not keeping the styles.css tab open it is also not adding the styles to the page when the css is written in the styles.css

**Comment by vinayak9303** [comment]
Can I work on this isuue?

**Comment by lasjorg** [comment]
@moT01 You have to be signed in as well. At least, it didn't happen when signed out and saving to local storage.

---

@sanjeevmurmu  It is applying the styles just fine for me. Did you remember to link to the CSS file?

@vinayak9303 We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

**Please make sure you read** [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by mahmoodalisha** [comment]
I totally understand the issue you are facing. I would be really delightful to write some code and solve the problem...assign this issue to me please.

**Comment by sanjeevmurmu** [comment]
> 
> @sanjeevmurmu It is applying the styles just fine for me. Did you remember to link to the CSS file?
> 
Yes my bad i forgot to link it as i thought it will already be linked to it

**Comment by dhanushkn97** [comment]
I am statring new here I cloned and extracted repo to my local machine and I made changes in the code. I am not getting how to run this locally (hoe to run this project locally ) need guide or steps can any one help me?

**Comment by moT01** [comment]
There's instructions linked above: contribute.freecodecamp.org/how-to-setup-freecodecamp-locally/ - is there anything specific you are stuck on @dhanushkn97 - I recommend just running the code following the instruction before making changes to make sure it's all working.
