### ISSUE TITLE
Challenge [Waypoint: Subtract One Number from Another with JavaScript] Solution is already there.

### ISSUE THREAD

**Issue by oeyece** [FreeCodeCamp/FreeCodeCamp#5586]
Challenge [Waypoint: Subtract One Number from Another with JavaScript](http://www.freecodecamp.com/challenges/waypoint-subtract-one-number-from-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var difference = 45 - 33;

// Only change code above this line.

(function(z){return 'difference='+z;})(difference);

```

As title says, the solution is already present so there is nothing to solve.

**Comment by ltegman** [comment]
This is leftover from you or someone else on your computer having visited this challenge previously. Please press the reset button to start fresh with the new seed code.

Thanks and happy coding!
