### ISSUE TITLE
Building a cipher - step 40: remove parentheses around space requirement

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/freeCodeCamp#55878]
### Describe the Issue

When surrounding the quotes around parentheses, the challenge refuses to allow campers to proceed even though it is technically the right answer. 

### Affected Page

https://www.freecodecamp.org/learn/scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/step-40

### Your code

```
text = 'Hello World'
shift = 3
alphabet = 'abcdefghijklmnopqrstuvwxyz'
encrypted_text = ''

for char in text.lower():
    print(char == (' '))
    index = alphabet.find(char)
    new_index = index + shift
    encrypted_text += alphabet[new_index]
    print('char:', char, 'encrypted text:', encrypted_text)
```

### Expected behavior

The camper should be able to pass the challenge as normal with the provided code. 

### System

- Device: Desktop 
- OS: Windows 10
- Browser: Firefox
- Version: 129.0.1

**Comment by jeremylt** [comment]
That's an odd piece of syntax that makes the intent less clear. I don't know that we should go out of our way to support such uncommon usage?

**Comment by gikf** [comment]
@jeremylt Generally I agree. Having said that, if such excuse is used to change test with regex to test using python's ast helpers, effectively accepting any kind of weird code styling. As long as it's valid syntax - that's fine with me.

**Comment by naomi-lgbt** [comment]
Actually, I'm gonna say we *shouldn't* allow it here. I have a feeling it's a result of campers just (mindlessly?) copy-pasting from the text instead of reading and understanding it:

![image](https://github.com/user-attachments/assets/767c69ce-226a-4229-9941-9cff857c8ff6)

**Comment by jeremylt** [comment]
Ouch, good point!

**Comment by a2937** [comment]
It didn't occur to me the `why` someone would do it. Yeah no we're not doing this.

**Comment by lasjorg** [comment]
I would suggest we remove the parenthesis from the requirements.

> At the beginning of your loop body, print the result of comparing `char` with a space `' '` using the equality operator `==`.

---

I never understood why we sometimes put code inside parenthesis like this. It inevitably results in some people copying it verbatim.

I will re-open and repurpose this issue. @a2937 I hope you do not mind

**Comment by lasjorg** [comment]
@a2937 Never mind, I will open an new issue for it instead.
