### ISSUE TITLE
Why doesn't this pass the Waypoint: Concatenating Strings with Plus Operator?  

### ISSUE THREAD

**Issue by gsc229** [FreeCodeCamp/FreeCodeCamp#5587]
Challenge [Waypoint: Concatenating Strings with Plus Operator](http://www.freecodecamp.com/challenges/waypoint-concatenating-strings-with-plus-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start." + "This is the end.";



```

**Comment by ltegman** [comment]
You first string is missing a space at the end. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for help in the future before filing a bug. Thanks and happy coding!

**Comment by gsc229** [comment]
Okay, thanks.
