### ISSUE TITLE
Zipline: Build a Camper Leaderboard - Confusion

### ISSUE THREAD

**Issue by alanbuchanan** [FreeCodeCamp/FreeCodeCamp#5588]
I believe [Zipline: Build a Camper Leaderboard](http://www.freecodecamp.com/challenges/zipline-build-a-camper-leaderboard) can be considered buggy because of the confusing instructions.

1. The contents of the two json files, as linked in the instructions, are of the exact same campers. Shouldn't one be of the top from the past 30 days, and the other of the top from all time?

2. The information in the json files seems incorrect. There are a large number of campers with 0 points, for example. They do not match the campers in the video, or in the Codepen example.

3. The instructions are ambiguous. Are we operating on one set of data or two?!

4. When you says you must use SASS, do you strictly mean SASS only, as opposed to SCSS? I believe the distinction should be made crystal clear.

**Comment by QuincyLarson** [comment]
Hi @alanbuchanan Thanks for pointing out these ambiguities. 


We will recommend SCSS, which is the more popular flavor (and the one Bootstrap 4 will use).

**Comment by roelver** [comment]
You should use the following URLs as endpoint depending on the sort column:
recent: http://fcctop100.herokuapp.com/api/fccusers/top/recent
alltime: http://fcctop100.herokuapp.com/api/fccusers/top/alltime

Then the data is already sorted

**Comment by roelver** [comment]
I fixed the URLS in the challenge. See pull request #5758. This issue is fixed.
