### ISSUE TITLE
Collapsible code blocks do not resize the editor

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#55880]
**Describe the bug**

The collapsible code blocks introduced by https://github.com/freeCodeCamp/freeCodeCamp/pull/54561 do not re-render the editor when they're expanded or contracted.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2
2. Click on Example Code
3. See large gap below instructions
4. Scroll the editor window
5. See large gap _above_ instructions
6. Click on Example Code
7. See description cover editor (lines 3 and 4)

**Expected behavior**
The editor should resize whenever the description changes size. 

**Screenshots**
![image](https://github.com/user-attachments/assets/1e2dd11a-b4ac-413b-8932-5a82927f9d2d)

after scrolling

![image](https://github.com/user-attachments/assets/edaba843-8f96-4001-bcd1-c021125a0972)

after second click

![image](https://github.com/user-attachments/assets/1937e736-1783-45c7-8c66-ef3ec3d27775)

**Additional context**

The collapsible code should probably be a React controlled component. There is an open issue https://github.com/facebook/react/issues/15486, but it's easily worked around https://github.com/facebook/react/issues/15486#issuecomment-488028431

**Comment by ojeytonwilliams** [comment]
As a side note, making every code block collapsible adds a lot of clutter. Some are large and obtrusive, but when it's a small snippet, the details element seems pointless.

For example https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-4 has 

![image](https://github.com/user-attachments/assets/f80b998d-7988-4701-a7f7-6093114cc260)

It would be nice if we weren't forced into choosing between highlighted and collapsible or un-highlighted and not.

**Comment by ShaunSHamilton** [comment]
I agree the code should not be automatically collapsed.

**Comment by lasjorg** [comment]
> As a side note, making every code block collapsible adds a lot of clutter. Some are large and obtrusive, but when it's a small snippet, the details element seems pointless.

Personally, I think it adds a bit of structure.

Beyond its main purpose as a collapsible section with code highlighting, I think it works as an element that help guide the user (a landmark).


> Explanation
> Example
> Requirements


Even when it contains a single line of code, it reinforces that flow.

In fact, I think an overall design of the jaw that puts each segment into a more distinct sub-block might be an idea worth considering. Not sure if it makes sense, but we could do the same for screen readers.

---

Having said that, I wouldn't mind it being a component with some option props. Like the collapse state, or whatnot.
