### ISSUE TITLE
unclear test criterion

### ISSUE THREAD

**Issue by jstoebel** [FreeCodeCamp/FreeCodeCamp#5590]
Challenge [Bonfire: Word Blanks](http://www.freecodecamp.com/challenges/bonfire-word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%20%20result%20%3D%20%5BmyAdjective%2C%20myNoun%2C%20myVerb%2C%20myAdverb%5D.join(%22%20%22)%20%2B%20%22.%22%3B%0A%0A%20%20%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

for this challenge the second criterion is unclear it reads:
```
wordBlanks("","","","") should return at least 30 characters with empty inputs 
```

This is somewhat unclear to me as I don't understand why a function call with all empty strings should more than 30 characters.

**Comment by MrJMGregory** [comment]
Had to ask for help in glitter.im.  The second test point has caught out many people.

It is not clear that you are expected to user more strings than just those supplied in the function arguments.  Instead reads that you should produce a 30 character string if all the function argument are empty strings.

**Comment by ltegman** [comment]
@SaintPeter Any insight into this?

**Comment by SaintPeter** [comment]
The point of "Madlibs" it to make a "Fill in the blanks" type sentence.  If you have not included any static strings with the strings you're adding, then you have not made a sentence.

I guess I need to add additional verbiage to this one.

**Comment by lox429** [comment]
I'm not sure what level of knowledge you should have prior to commencing these free courses as I went in assuming it builds from the first lesson.I was not aware of the need to include the +'s between strings to create the sentence. Total noob but maybe worth considering to include in the instructions? Thanks.

**Comment by SaintPeter** [comment]
The whole point of these "Checkpoints" is to have you apply the knowledge that you have learned in prior waypoints.  These also act as an introduction to the idea of Bonfires, AKA "Blank Page" challenges.  We don't give you any hints because you're supposed to figure it out on your own.

**Comment by wayne13** [comment]
I have no idea what to do here.

**Comment by ewillison** [comment]
If Waypoints are supposed to lead to Checkpoints. This Checkpoint does not follow the logic of previous waypoints it is a confusing off the beaten path construct.
