### ISSUE TITLE
Flexibility on passing the test requirements.

### ISSUE THREAD

**Issue by NoMoney03** [freeCodeCamp/freeCodeCamp#55902]
### Describe the Issue

The test "Build a Pokémon Search App Project - Build a Pokémon Search App" has some stories that require me to have certain elements with specific IDs to be present in the project. Now, nowhere does it say that those elements must strictly be present in the index.html file. So, when I created those elements with the exact Id-naming requirements in script.js. The test did not pass. I think the tests should pass as long as the elements are present in the project regardless of the file they are in.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-pokemon-search-app-project/build-a-pokemon-search-app

### Your code

```
<!-- file: index.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pokemon Search Project</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>

<div id="headingAndInput">

<h1 id="page-heading">Pokemon Search App</h1>

<label for="search-input">Search for Pokémon Name or ID:</label>
<input id="search-input" required>
<button id="search-button">Search</button>

</div>

<div id="pokemonData">

</div>

    
    <script src="script.js"></script>
  </body>
</html>



```
```
/* file: script.js */
const input = document.getElementById("search-input");
const btn = document.getElementById("search-button");
const heading = document.getElementById("page-heading");
const dataDiv = document.getElementById("pokemonData");


btn.addEventListener("click", ()=>{

async function fetchData(){
  try{
    const inputValue = input.value.toLowerCase();
    const response = await fetch(`https://pokeapi-proxy.freecodecamp.rocks/api/pokemon/${inputValue}`)
    
  
  if (!response.ok){
    alert("Pokémon not found")
  } 
    const data = await response.json();
    console.log(data)
    dataDiv.innerHTML = `
        <h2 id="pokemon-name">${data.name.toUpperCase()}</h2>
        <img id="sprite"src="${data.sprites.front_default}" alt="${data.name}">
        <p id="pokemon-id">Id: ${data.id}</p>
        <p id="height">Height: ${data.height}</p>
        <p id="weight">Weight: ${data.weight}</p> 
        <p id="hp">Hp: ${data.stats[0].base_stat}</p> 
        <p id="attack">Attack: ${data.stats[1].base_stat}</p> 
        <p id="defense">Defense: ${data.stats[2].base_stat}</p> 
        <p id="special-attack">Sp. Attack: ${data.stats[3].base_stat}</p> 
        <p id="special-defense">Sp. Defence: ${data.stats[4].base_stat}</p> 
        <p id="speed">Speed: ${data.stats[5].base_stat}</p> 
        <p id="types">Type: ${data.types.map(obj => obj.type.name).join(", ").toUpperCase()}</p> 
      `;

  }
  catch(error){
    console.log(error)
    

  }
}
fetchData()
})
```
/* file: styles.css */
body{
    background-color: black;
    color: white;
    
}
```

```

### Expected behavior

Expected the code to pass since the required elements were present in the project.

### System

- Browser: Microsoft Edge [Version 127.0.2651.105 (Official build) (64-bit)]

### Additional context

I am only talking about the tests 3 to 13 here. Ignore other tests as I have not completed the project as of submitting this request.

**Comment by gikf** [comment]
It's not as much in which file they are, but at which point they are present on page. Tests 3-13 are using similar wording as tests 1 & 2. 1 & 2 clearly must be present on load to be able to fulfill further tests.

Similarly tests 14+ are very clear that specific actions must be taken before result can be checked. That's not a case for 1-13 tests.

**Comment by NoMoney03** [comment]
I understand that the wording is similar but in both the modules of API in "JavaScript Algorithms and Data Structures (Beta)", the elements are created in the script.js and not in the index.html. So, when the elements created in the "Build a Pokémon Search App Project" in script.js do not pass, It seems counter-intuitive to teach that in the first place. Also, it makes the test seem more rigid than flexible on methods.

**Comment by NoMoney03** [comment]
> It's not as much in which file they are, but at which point they are present on page. Tests 3-13 are using similar wording as tests 1 & 2. 1 & 2 clearly must be present on load to be able to fulfill further tests.
> 
> Similarly tests 14+ are very clear that specific actions must be taken before result can be checked. That's not a case for 1-13 tests.

I understand that the wording is similar but in both the modules of API in "JavaScript Algorithms and Data Structures (Beta)", the elements are created in the script.js and not in the index.html. So, when the elements created in the "Build a Pokémon Search App Project" in script.js do not pass, It seems counter-intuitive to teach that in the first place. Also, it makes the test seem more rigid than flexible on methods.

**Comment by Sembauke** [comment]
Thank you for your feedback, I see how this might be a bit confusing.

We should add a second note:  Please note that the first 13 steps must be completed inside the `index.html` file.  We should put this note above the user stories.
