### ISSUE TITLE
Build a Student Database: Part 1

### ISSUE THREAD

**Issue by Alexeigithubproject** [freeCodeCamp/freeCodeCamp#55938]
### Describe the Issue

After the step in which i create the last column called gpa :

ALTER TABLE students ADD COLUMN gpa NUMERIC(2,1);

I am asked to display the details of students, by entering " \d students" but it doesn't work. Tried to reset the step, tried creating a new terminal, still won't accept the input even when i am copy pasting it from the Hints.

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-sql-by-building-a-student-database-part-1/build-a-student-database-part-1

### Your code

```


ALTER TABLE students ADD COLUMN gpa NUMERIC(2,1);
\d students


```

### Expected behavior

Expected to work after entering the correct input

### Screenshots

![image](https://github.com/user-attachments/assets/072ad51d-b6ce-4087-bae1-bdd7cf878c0d)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by philippeSendze** [comment]
Hey ! Try :
`\d students;`
Make sure you have the semi-colon at the end.

**Comment by philippeSendze** [comment]
Hey ! Try to clear everything and write : 

`\d students;`

Make sure you have the semi-colon at the end. I saw in the picture that you tried it once, but PostgreSQL considers everything before a semi-colon as a single instruction (so it took every lines before, until the previous semi-colon). Tell me if that solves your problem !

**Comment by Alexeigithubproject** [comment]
I guess it will work if that was the mistake :D . The hint was misleading then xD

thanks
