### ISSUE TITLE
anchor and p tag issues

### ISSUE THREAD

**Issue by xchillisauce** [freeCodeCamp/freeCodeCamp#55930]
### Describe the Issue

![Screenshot 2024-08-23 223146](https://github.com/user-attachments/assets/e0c1536a-ca2d-4c09-8bde-9fef44aee2ac)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

```
 <p>See more <a 
      href="https://freecatphotoapp.com">cat photos</a> 
      in our gallery.</p>


```
 

### Expected behavior

i want this code to pass but keeps getting error

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by lasjorg** [comment]
Please use the forum to get support with the curriculum.

https://forum.freecodecamp.org
