### ISSUE TITLE
Suggestion: Expand most recent module been worked on

### ISSUE THREAD

**Issue by codewithtyler** [freeCodeCamp/freeCodeCamp#55934]
### Is your feature request related to a problem? Please describe.

No, it is not related to a problem.

### Describe the solution you'd like

This morning I opened up FreeCodeCamp and went back into the Responsive Web Design certification. I'm currently on the Learn Accessibility by Building a Quiz module. However, when you go into the certification the Cat Photo App module is always expanded. I think it would be nice if the site kept a record of which lesson you last completed and automatically expanded the module for that lesson. So in my case when I login instead of the Cat Photo App module being expanded I instead see it collapsed and the Learn Accessibility by Building a Quiz module is expanded since the last lesson I did was in there. I would think if this is done then it would also be a good idea to have a link at the top of the page that lets you jump to your currently active module. This would save some scrolling time and would help keep the user productive.

### Describe alternatives you've considered

The only alternative I can think of would require a front end redesign of our the certification courses works. I'm thinking something like a side nav with the list of modules and each module can be expanded in the side nav to show the lesson and you click on the lesson then to the right of that you see the lesson. This would actually modernize the UI a good bit if you did something like this but I do understand that this alternative suggestion would be a huge undertaking. I would like to someday give back to the FCC community maybe doing something like this in the future would be something myself and others would be interested in.

**Comment by ahmaxed** [comment]
Having the card block with the last completed challenge expanded is good idea. 
Once the api is in use, we will be able to include a link to the latest attempted challenge in the curriculum page.

**Comment by codewithtyler** [comment]
> Hey @codewithtyler,
> 
> Thank you for your suggestion. To view your current project make sure to look at the progressbar which will display a percentage.
> 
> I am not sure if we want this, I will ask our UX designer.

If you're talking about this progress bar then yeah I'm aware of it and it's good indicator to now how far I am in that module of the certification. However this is halfway down the page on the Responsive Web Design certification. Which means I have to scroll halfway down the page to see my progress. 

![image](https://github.com/user-attachments/assets/10f21402-a6af-4f5e-b417-efab8ecbd72d)


If you scroll to the top of the page you'll see that the Cat Photo section is automatically expanded. Why have this expanded when I've already completed that module?

<img width="581" alt="image" src="https://github.com/user-attachments/assets/0ed7eee2-8780-46b7-840b-e807cf9f43b4">

My thoughts were what if we don't expand the first section (aka the Cat Photo section) once it's been completed. Then above that you have something that shows your current progress and when it is clicked will scroll you down to the next lesson of the section you're actually working on.

**Comment by hbar1st** [comment]
I like the suggestion but I would want to know: what happens if a step is added in the cat photo app that makes the project appear incomplete? Will fCC treat the project as incomplete and end up opening it up automatically? (Essentially forcing the person to notice and complete the new steps in order for this feature to work properly?)

Or, maybe fCC know that you completed this module before and so it just always remembers that even if new steps are added?

Just a thought.

**Comment by ilenia-magoni** [comment]
@hbar1st with the new curriculum how progress is tracked is changing and it will be easier to implement this one

**Comment by codewithtyler** [comment]
@Sembauke When will this be rolled out? I saw the PR got merged but the cat photo app is still showing as expanded for me despite being past that project.

**Comment by Sembauke** [comment]
Hi @codewithtyler,

I think the linked pr just missed the release window. It really depends on the devops team. But I think it will be somewhere around the first or second week of January.

**Comment by codewithtyler** [comment]
Ah ok thanks I wasn't aware of release windows. I just assumed it was an auto CI/CD that pushes to production once something is merged.
