### ISSUE TITLE
Empty negative space in responsive 

### ISSUE THREAD

**Issue by mahassan** [freeCodeCamp/freeCodeCamp#55952]
### Describe the Issue

There is empty space towards the end of screen, the scroll bar arrows are too small as well. Not only 1 page is affected but all pages in responsive web design

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-20

### Steps to Reproduce

1. Go to 
2. Click on https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-1
3. If screen is small, scroll down and you will see the issue
<img width="1092" alt="Screenshot 2024-08-28 at 11 42 37" src="https://github.com/user-attachments/assets/c88dfcf8-77ab-4825-8556-fc8de2dbf75d">

### Expected behavior

There should not be a negative space, I have highlighted negative space and extra small scroll button in the image.
<img width="1532" alt="Screenshot 2024-08-28 at 13 36 41" src="https://github.com/user-attachments/assets/6efe3a28-9544-4cb7-b9c5-efea3cbc999a">

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by roger-alok** [comment]
Hey, Can you please elaborate as I am not getting any negative spaces. I am using laptop

**Comment by mahassan** [comment]
@roger-alok here I made a loom video https://www.loom.com/share/0dca5105bf5b4195892e0131d3af1ec1?sid=c0beccf4-ccc2-487c-be6e-8baf1a8d99a5

**Comment by Mrpai2318** [comment]
@mahassan I am on my laptop I am not seeing any negative spaces. I have no idea why it is happening only to you.

https://github.com/user-attachments/assets/4431da2f-8861-48da-a099-045f0c363557

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #55931, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
