### ISSUE TITLE
Step 149 of RPG needs to have backticks removed

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55974]
https://github.com/freeCodeCamp/freeCodeCamp/blob/c3581899b3b8cb849c35f578bd53017d5b390a99/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa1eec891ed731db227a36.md?plain=1#L12

Here the "ternary operator" text should be translatable, the backticks should be removed.

---

This looks like something that can be fixed by "first-time" code contributors to this repository. The files that you should be looking at in linked above:

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by lasjorg** [comment]
@waleedsid please do not link to our issue tracker on PRs in your own repo. It is just confusing and makes it look like a PR has been made.

Just to be clear, to new contributors, this issue is still open for contribution.

**Comment by suryatejess** [comment]
Can I work on this?

**Comment by lasjorg** [comment]
@suryatejess We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by ANAMASGARD** [comment]
I HAVE MADE A PULL REQUEST PLEASE CHECK IT

**Comment by coleaydelotte** [comment]
Just submitted a pull request fixing the issue.
