### ISSUE TITLE
Build a telephone number validator project missing backtick

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55975]
https://github.com/freeCodeCamp/freeCodeCamp/blob/c3581899b3b8cb849c35f578bd53017d5b390a99/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-telephone-number-validator-project/build-a-telephone-number-validator.md?plain=1#L38

the end of the line is missing a backtick

---

This looks like something that can be fixed by "first-time" code contributors to this repository. The files that you should be looking at in linked above:

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by akhilk2802** [comment]
Hey, Would love to take up this issue, could you please assign it to me 
Thanks

**Comment by gikf** [comment]
Hey @akhilk2802

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by akhilk2802** [comment]
okay, thanks
