### ISSUE TITLE
cat painting step 47 missing comma

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#55989]
https://github.com/freeCodeCamp/freeCodeCamp/blob/8debeb2d2987a23a1e7be95210d8656d8100b784/curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646de7b64467e96b7d35b5cd.md?plain=1#L10

this sentence is missing a comma after "absolute".

---

This looks like something that can be fixed by "first-time" code contributors to this repository. You should look at the file linked above.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by VDXD** [comment]
Mam, can you please tell me how can i fix those details you mentioned i have no idea how to do
