### ISSUE TITLE
Bonfire - Title Case a Sentence

### ISSUE THREAD

**Issue by Maximization** [FreeCodeCamp/freecodecamp#56]
As it is at the present moment, the starting code format for *Title Case a Sentence* misses a semi-colon at the end of the last line as shown in the picture.

![Semi-colon error on Title Case a Sentence challenge](http://i.imgur.com/2wHGev5.png)

I would've fixed the issue myself but I think this comes from the challenge seed in the db.

**Comment by terakilobyte** [comment]
Resolved in PR #57
