### ISSUE TITLE
Bad Step in Learn Advanced Array Methods by Building a Statistics Calculator - Step 59

### ISSUE THREAD

**Issue by TwentyFourGrit** [freeCodeCamp/freeCodeCamp#56015]
### Describe the Issue

Step 59 of the "Learn Advanced Array Methods by Building a Statistics Calculator" lesson asks the user to fix that the .sort() method is mutating the array which it is called on by adding a .slice(), but this was already addressed in Step 26 by replacing the .sort() method with a .toSorted() method. You can of course get past this final step by reverting to the .sort() method and then following the instructions of Step 59, but you really shouldn’t have to. I took this to the forums and staff suggested I post the issue here.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-59

### Your code

```
/* file: script.js */
// User Editable Region

const getMedian = (array) => {
  const sorted = array.toSorted((a, b) => a - b);
  const median =
    sorted.length % 2 === 0
      ? getMean([sorted[sorted.length / 2], sorted[sorted.length / 2 - 1]])
      : sorted[Math.floor(sorted.length / 2)];
  return median;
}

// User Editable Region
```

### Expected behavior

This step should not exist, as what it addresses had already been remedied by a prior step.

### Screenshots

![image](https://github.com/user-attachments/assets/b5d0a652-275a-4aa4-87f3-2378a41245de)

### System

- Device: Desktop
- OS: Windows 10 x64
- Browser: Brave
- Version: v1.69.162 Chromium: 128.0.6613.120 (Official Build) (64-bit)

**Comment by ilenia-magoni** [comment]
It seems step 59 is to be deleted and step 58 to be set as last step of the challenge. I will open this for contributions
