### ISSUE TITLE
Natural Language Processing With RNNs: Training the Model

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#56029]
### Describe the Issue

The answer here is incorrect:
```
A: './checkpoints'
B: ModelCheckpoint
C: checkpoint_callback
```
The question:
```
checkpoint_dir = __A__
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt_{epoch}')

checkpoint_callback = tf.keras.callbacks.__B__(
    filepath=checkpoint_prefix,
    save_weights_only=True
)

history = model.fit(data, epochs=2, callbacks=[__C__])
```
Here is the code from the notebook:
```
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

history = model.fit(data, epochs=50, callbacks=[checkpoint_callback])
```

```
A: './checkpoints'
```
should be changed to 
```
A: './training_checkpoints'
```

### Affected Page

https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/natural-language-processing-with-rnns-training-the-model

### Your code

```

NA

```

### Expected behavior

NA

### Screenshots

NA

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by gikf** [comment]
What's the question to answer though? 🙂

**Comment by pkdvalis** [comment]
It's this fill-in-the-blanks:

The question:
```
checkpoint_dir = __A__
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt_{epoch}')

checkpoint_callback = tf.keras.callbacks.__B__(
    filepath=checkpoint_prefix,
    save_weights_only=True
)

history = model.fit(data, epochs=2, callbacks=[__C__])
```

**Comment by gikf** [comment]
> Fill in the blanks below to save your model's checkpoints in the `./checkpoints` directory and call the latest checkpoint for training:

**Comment by pkdvalis** [comment]
Ok, I see it now... thanks!
