### ISSUE TITLE
Introduce Unit Testing Lessons

### ISSUE THREAD

**Issue by pmbenjamin** [FreeCodeCamp/FreeCodeCamp#5602]
**Suggestion:**
Would it be feasible to introduce **"Unit Testing"** material (e.g. waypoints, bonfires, hikes ...etc) to FCC students?

The case for learning **Unit Testing**:
- One could make an argument that, in addition to all the core JS concepts we learn in FCC (e.g. algorithms, full-stack development, data visualization ...etc), **unit testing** is among the highly valued skills/know-how that employers look for in developers.
- **Unit Testing** leads to better, more stable code.
- **Unit Testing** is a necessity when contributing to open-source projects. Contributors are expected to know how to test their changes before committing them.

So, why not start teaching this acquired skill, or at least put it on the students' radar, as early in the learning process as possible so it feels natural to the next generation of developers as opposed to treating it as an after-thought?

**Comment by DDaems** [comment]
:+1:

**Comment by abhisekp** [comment]
:+1:

**Comment by smrajagopal** [comment]
:+1:

**Comment by RandomlyKnighted** [comment]
:+1:

**Comment by ltegman** [comment]
Closing in favor of #5847. Please continue any discussion in that thread. Thanks and happy coding!
