### ISSUE TITLE
Cannot login with a Freecodecamp.org account on the Freecodecamp Forums

### ISSUE THREAD

**Issue by Sprinting** [freeCodeCamp/freeCodeCamp#56034]
### Describe the Issue

Hi, 

I can not login to the freecodecamp forums via OAuth using the freecodecamp.org account. I _can_ log in to the course website, however.

### Affected Page

forum.freecodecamp.org

### Steps to Reproduce

1. Go to 'forum.freecodecamp.org'
2. Click on 'Sign in'
3. Scroll  to 'Login via Freecodecamp.org account'. Attempt to login via an identity provider (I used google)
4. Am redirected to the the "Let us create your account" modal

This is unexpected because my account exists on the website, and I can login the course website just fine. I also can not sign up with my own username on the forums.

In addition, after the oauth loop, the welcome modal does not render correctly

### Expected behavior

I am signed in to the forums. 

### Screenshots

![image](https://github.com/user-attachments/assets/85988ffc-534c-43f8-8433-4ce697fdd49a)

### System

- Device: [e.g. iPhone 6, Laptop]: Desktop Computer
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]: Windows
- Browser: [e.g. Chrome, Safari]: Edge 
- Version: [e.g. 22]: Version 128.0.2739.42 (Official build) (64-bit)

**Comment by ilenia-magoni** [comment]
Have you ever been on the forum before? If not, you need to create an account to start using it, even if you are authenticating via the freeCodeCamp account

**Comment by Sprinting** [comment]
Hi
Yes, my username on the forum is Sprinting. I last logged in in 2019 but I do have the account confirmation emails on my email.

**Comment by kartik1112** [comment]
@Sprinting i tried following your steps but could not find any bugs
