### ISSUE TITLE
Building Cat Photo App Issue

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/freeCodeCamp#56035]
### Describe the Issue

So when following the step and things the examples on laptop are not drawing in correctly. They are drawing in, in a way that makes it look like it is 3 lines rather then one line.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-12

### Your code

```
<p>See more <a 
href="https://freecatphotoapp.com">cat photos</a> 
in our gallery.</p>
```

### Expected behavior

I expected it to be right as it looked similar to the example above.

### Screenshots

![image](https://github.com/user-attachments/assets/bfbffe87-a1c3-4476-bf68-daaf341eb667)

### System

- Device: Laptop
- OS: Windows 11
- Browser: Chrome
- Version: Most recent version

**Comment by prabhunandanm66** [comment]
Hey @Chubbywolf99 ,
 I think you have pressed enter key after anchor tag that is causing the issue, Please try to write in a single line continuously without using enter.
let me know if you need any further help.

**Comment by ilenia-magoni** [comment]
There are many help requests on the forum for this, but it started recently, I wonder if there was some changes to the UI that caused the code block to wrap

**Comment by swarupe7** [comment]
> There are many help requests on the forum for this, but it started recently, I wonder if there was some changes to the UI that caused the code block to wrap

Hii @ilenia-magoni ,  im swarup  a guy who  recently started my development journey  could you guide me on how to contribute to these open source projects

**Comment by jeremylt** [comment]
I really don't think we should adapt the tests to allow those line breaks that don't belong there
