### ISSUE TITLE
Wrap keywords in `<code>` tag

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#56033]
## Description

Keywords in the following sentence should be wrapped within `<code>`.

https://github.com/freeCodeCamp/freeCodeCamp/blob/aa88ca709a333bbdfd4dd8c8baa3bde9bb7f429c/client/i18n/locales/english/intro.json#L1733

## Changes needed

Update the file with this change:

```diff
--- main, nav, article and footer elements.
+++ <code>main</code>, <code>nav</code>, <code>article</code> and <code>footer</code> elements.
```

**Comment by coson-lu** [comment]
I can work on this.

**Comment by Saichandra2520** [comment]
@coson-lu Are you still working on this?

**Comment by coson-lu** [comment]
@Saichandra2520 I submitted a pull request (#56037) that is waiting to be reviewed.

**Comment by trulyabdullah** [comment]
I would like to work on this.

**Comment by MainakSil** [comment]
I can work on this.
