### ISSUE TITLE
Machine Learning with Python - Tensorflow

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#56030]
### Describe the Issue

I've run into problems running these notebooks because the information is old and these functions have been deprecated and no longer work. The tutorials on tensorflow.org that they are based on have been updated and it seems this information is old enough to not be useful anymore, especially when it relates to specific functions or syntax.

Should this section be moved to legacy, or totally removed, until it can be updated?

If I go through the material just to check the boxes it feels a bit silly since I know it's wrong now and actually does not run. I'll have to check the updated tutorials after this.

Alternatively, the questions could be updated to ask about concepts which are still relevant (instead of specific syntax).

For context here is the problem I encountered first, and this has occurred more going forward:

Getting the following error trying to run the notebook linked from the video:
[https://colab.research.google.com/drive/1ysEKrw_LE2jMndo1snrZUh5w87LQsCxk](https://colab.research.google.com/drive/1ysEKrw_LE2jMndo1snrZUh5w87LQsCxk)
```
----> 4   tokens = keras.preprocessing.text.text_to_word_sequence(text)
      5   tokens = [word_index[word] if word in word_index else 0 for word in tokens]
      6   return sequence.pad_sequences([tokens], MAXLEN)[0]

AttributeError: module 'keras.preprocessing' has no attribute 'text'
```

Most of the info I could find is saying that these modules and functions are deprecated, and they are posts from 4 years ago or longer.

I tried downgrading keras from 3.4.1 to 2.2.0 but that broke other imports.

### Challenge Information:
TensorFlow - Natural Language Processing With RNNs: Making Predictions
https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/natural-language-processing-with-rnns-making-predictions

### Affected Page

https://www.freecodecamp.org/learn/machine-learning-with-python/

### Your code

```


NA
```

### Expected behavior

NA

### Screenshots

NA

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
NA

### Additional context

https://www.tensorflow.org/text/tutorials/text_classification_rnn

https://forum.freecodecamp.org/t/tensorflow-natural-language-processing-with-rnns-making-predictions-keras-preprocessing-has-no-attribute-text/709467/

https://forum.freecodecamp.org/t/tensorflow-core-learning-algorithms-building-the-model/709721

**Comment by YashShukla925** [comment]
Hii,
I solved the issue but i do not find specific path where i have to make these changes. 
Could you specify the path of the file

**Comment by manuelguijarrosanchez** [comment]
The only way to solve this problem is to edit directly the file [https://colab.research.google.com/drive/1ysEKrw_LE2jMndo1snrZUh5w87LQsCxk](https://colab.research.google.com/drive/1ysEKrw_LE2jMndo1snrZUh5w87LQsCxk). For that you need permission I guess from moderators. 

As  @pkdvalis  says, it is necessary to rewrite parts because the code is deprecated and gives error. I think it would be interesting to update this tutorial because after 4 years there may be more deprecated or even code that is not recommended to use.

In the information it says that the owner is techwithtimm@gmail.com 

![Screenshot from 2024-09-09 21-13-36](https://github.com/user-attachments/assets/dfdb40cd-aed1-499e-9da3-d78a6f5ca4f3)

**Comment by YashShukla925** [comment]
https://colab.research.google.com/drive/1PX5-2NtGQlcWvNCEd8NcrylDS8oDdVgX#scrollTo=SOc7U3Au-nqy   
@pkdvalis 
I upgraded the modules used in this colab.
review this colab and make necessary changes

**Comment by Sembauke** [comment]
We will be rehashing our python curriculum next year. Stay tuned.
