### ISSUE TITLE
 Inconsistent Page Behavior After Login/Logout – No Redirect to Home or Login Page

### ISSUE THREAD

**Issue by dipanshurdev** [freeCodeCamp/freeCodeCamp#56053]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
I’ve noticed that when I log in or log out of FreeCodeCamp, the page remains the same and does not redirect to a relevant page. (e.g., profile page after login and login/home page after logout).  

**To Reproduce**
1. Go to ***Profile***
2. Click on ***Log out***
4. See that ***Page stays the same***
5. And after that, if we ***Login to any other account***
6. Page stays to ***the old user's account and doesn't redirect to the currently logged user's account***

**Expected behavior**

After logging in, the User should be redirected to his profile page without needing to refresh the page.
After logging out, the User should be redirected to the login or Home page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windos]
 - Browser: [e.g. Chrome]
 - Version: [e.g. ]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Jaishree2310** [comment]
@dipanshurdev @gikf,  Can you please assign this issue to me ?
Thank you!

**Comment by gikf** [comment]
Hey @Jaishree2310

Issues labelled with `help wanted` or `first timers only` are open for contributions.

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by naomi-lgbt** [comment]
> After logging in, the User should be redirected to his profile page without needing to refresh the page.

No. Redirecting someone to a different page when they log in is an anti-pattern. They should be returned to the same page they were on when they started the login flow.

**Comment by ojeytonwilliams** [comment]
I agree with Naomi. Changing the page without the user explicitly requesting a change is confusing at best.
