### ISSUE TITLE
How I can use the translations to Spanish?

### ISSUE THREAD

**Issue by unluisco** [FreeCodeCamp/FreeCodeCamp#5606]
I want to study using translations in Spanish, which is the link?

**Comment by cesarve77** [comment]
Maybe this can help:

https://defensor.info:3000/map

**Comment by unluisco** [comment]
thanks, but there is an official link?

**Comment by cesarve77** [comment]
I dont know

**Comment by bugron** [comment]
Thanks all for comments. Let's keep the discussion in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5888.
