### ISSUE TITLE
Create an icon for B1 English

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#56061]
## Description

The B1 English icon isn't available, so we are temporarily using the A2 icon for this superblock.

<img width="709" alt="Screenshot 2024-09-11 at 05 43 53" src="https://github.com/user-attachments/assets/5d0227a1-d798-4bf7-90f6-8d0fea864401">

An icon for B1 should be created (it should look similar to the A2).

## Reference

Link to the A2 icon: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/assets/icons/a2-english.tsx.

## Note

You will need to make the following change to your `.env` file in order to see the B1 superblock:

```env
SHOW_NEW_CURRICULUM=true
```

**Comment by VDXD** [comment]
i changed the .env file please check
