### ISSUE TITLE
Standardize Quotation Marks in Attribute Values

### ISSUE THREAD

**Issue by Stephen-254** [freeCodeCamp/freeCodeCamp#56081]
### Describe the Issue

Without quotation marks on the type attribute value, all tests pass successfully. However, it is the opposite when the value is in quotation marks. 

Having quotation marks on attribute values is standard and considered best practice. 

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-69

### Your code

```

function calculateCalories(e) {
  e.preventDefault();
  isError = false;
  const breakfastNumberInputs = document.querySelectorAll("#breakfast input[type='number']");
}

```

### Expected behavior

With or without quotation marks, the test should pass.

### Screenshots

![Screenshot 2024-09-12 165412](https://github.com/user-attachments/assets/d816a654-f794-4c43-86e8-0eb44fbd5847)

### System

- Browser: [e.g. Chrome, Safari]

**Comment by ilenia-magoni** [comment]
If it's considered best practice maybe the whole project needs to be updated

**Comment by av6-github** [comment]
@ilenia-magoni @Stephen-254 I have created a pull request from a forked repo. I wasn't able to test the fix myself but I think it should do the trick. Can anyone possibly guide me on how to test it locally or in any other way? Thanks in advance!

**Comment by ilenia-magoni** [comment]
@av6-github to open the PR you checked a checkbox to confirm you read the contributing guidelines, so please actually do that

**Comment by av6-github** [comment]
> @av6-github to open the PR you checked a checkbox to confirm you read the contributing guidelines, so please actually do that

thanks!
