### ISSUE TITLE
step 22 hotel feedback form small fixes

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#56098]
https://github.com/freeCodeCamp/freeCodeCamp/blob/db5854ecf6900af4ce952b4d2bd536ea75aa9671/curriculum/challenges/english/25-front-end-development/workshop-hotel-feedback-form/66a96127422411756204bc1b.md?plain=1#L10-L12

Needed fixes:
```md
Below the label element => Below the `label` element
another checkbox input => another checkbox `input`
Add another label => Add another `label`
```

---

This looks like something that can be fixed by "first-time" code contributors to this repository. The files you should look at to work on a fix are those linked above.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by trulyabdullah** [comment]
I have submitted a PR above that fixes this issue. Please tell me if I need to improve this PR
