### ISSUE TITLE
"Waypoint: Comparisons with the Logical Or Operator" instructions

### ISSUE THREAD

**Issue by noinkling** [FreeCodeCamp/FreeCodeCamp#5609]
Challenge [Waypoint: Comparisons with the Logical Or Operator](http://www.freecodecamp.com/challenges/waypoint-comparisons-with-the-logical-or-operator#?solution=function%20myTest(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3E%2020%20%7C%7C%20val%20%3C%2010)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(15)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Instructions say:

> Combine the two if statements into one statement which returns "Inside" if val is between 10 and 20, inclusive. Otherwise, return "Outside".

The way I interpet these instructions means I'd likely have to use `&&` (which disagrees with the examples and the test given to use `||`), or else unnecessarily complicate the condition.

Presumed intended solution that doesn't seem to be in agreement with these instructions:

```javascript
function myTest(val) {
  // Only change code below this line

  if (val > 20 || val < 10) {
    return "Outside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
myTest(15);

```

I believe instead it should read:

> Combine the two if statements into one statement which returns "**Outside**" if val is **not** between 10 and 20, inclusive. Otherwise, return "**Inside**".

Or if you don't want to be that explicit, it should at least be worded differently from how it is now, like:

> Combine the two if statements into one statement so that the **function** returns "Inside" if val is between 10 and 20, inclusive. Otherwise, return "Outside".

While still a little confusing for newbies about how it relates to the code, at least this way you're not implying that `return "Inside";` should be within the `if` statement (especially when it already exists at the bottom of the function in the editor and isn't supposed to be modified).

**Comment by ltegman** [comment]
Agreed, the wording is a little misleading!

**Comment by SaintPeter** [comment]
I like the verbiage.  PR submitted.  Thanks!

**Comment by PurpleZerg** [comment]
21 days past - the issue is still live

**Comment by tesla809** [comment]
How do I go about fixing the issue? First time trying to contribute to the code

**Comment by SaintPeter** [comment]
Here is the current verbiage:
> Combine the two if statements into one statement which returns "Outside" if val is not between 10 and 20, inclusive. Otherwise, return "Inside".

What is the problem?

**Comment by davida26** [comment]
@tesla809 @PurpleZerg - @SaintPeter fixed this to the above the changes are live.

The issue I see is the challenge progression leading to some confusion here. Perhaps allowing the user to create their own return statements would avoid confusion.

```javascript
function myTest(val) {
  // Only change code below this line

  if (user solution here) {
    return "Outside"; // <--- remove this and allow user to set as needed
  }

  // Only change code above this line -REMOVE
  return "Inside"; // <--- remove this and allow user to set as needed
}

// Change this value to test
myTest(10);
```

Example:  

Working with <= and >= then moving to this challenge causes confusion (confused me too at the beginning) while you could solve with those, you would need to change a few things for that to make sense and fulfill the challenge requirements.

Breaking this down - let us assume the following:
val = 10; Seems to me the majority of problems would occur here and at 20

1. If you use this:
val <= 10 || val >= 20
TRUE || FALSE = TRUE
outputs: OUTSIDE, when you need it to say INSIDE since the return line is coded in already.

2. val < 10 || val > 20 same as @noinkling suggested
FALSE || FALSE = FALSE
outputs: INSIDE and solves the problem but we did need to use the <= / >=

hope this helps.

**Comment by rOluochKe** [comment]
function testLogicalOr(val) {
  // Only change code below this line
  if (val < 10 || val > 20) {
    return "Outside";
  }
  // Only change code above this line
  return "Inside";
}
// Change this value to test
testLogicalOr(15);


this works fine

**Comment by texas2010** [comment]
@rOluochKe 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by TheDevWizard** [comment]
This works fine, but you got to make sure that you look at how you construct your code.
