### ISSUE TITLE
Backtick issues in various files

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#56105]
There are some small issues that need to be fixed in the following files:

https://github.com/freeCodeCamp/freeCodeCamp/blob/efe1b655a0ee7038dc631b3b37f1782550794968/curriculum/challenges/english/25-front-end-development/workshop-hotel-feedback-form/66a97ca8c4cbae7d0bb6e0ad.md?plain=1#L10
`` option text `` => `` `option` text ``

https://github.com/freeCodeCamp/freeCodeCamp/blob/efe1b655a0ee7038dc631b3b37f1782550794968/curriculum/challenges/english/25-front-end-development/workshop-hotel-feedback-form/66a962954f4e0d76223b37ed.md?plain=1#L14
`` for attribute `` => `` `for` attribute ``

https://github.com/freeCodeCamp/freeCodeCamp/blob/efe1b655a0ee7038dc631b3b37f1782550794968/curriculum/challenges/english/16-the-odin-project/top-learn-block-and-inline/learn-block-and-inline-lesson-g.md?plain=1#L9
`` inline `elements` `` => `` `inline` elements ``

https://github.com/freeCodeCamp/freeCodeCamp/blob/efe1b655a0ee7038dc631b3b37f1782550794968/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/6672e579cc11472272ab23e6.md?plain=1#L17
`` `"Check your code"` button `` => `` "Check your code" button ``

https://github.com/freeCodeCamp/freeCodeCamp/blob/efe1b655a0ee7038dc631b3b37f1782550794968/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef0f7c4b8e68ccd1f0786.md?plain=1#L10
`` `String` `` => `` String ``

---

This looks like something that can be fixed by "first-time" code contributors to this repository. The files you should look at to work on a fix are those linked above.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by itsjatinnagar** [comment]
Hi @ilenia-magoni, I'd like to work on this issue.
Thanks

**Comment by gikf** [comment]
Hey @itsjatinnagar

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
