### ISSUE TITLE
Suggestion: "Go to next undone challenge"

### ISSUE THREAD

**Issue by DiegoRBaquero** [FreeCodeCamp/FreeCodeCamp#5612]
Hello,

I would like to suggest that FCC defaults to "Go to next undone challenge" once a challenge is done.

Mentioned it on Gitter and some people liked it.

Thank you for all the great work.

**Comment by SaintPeter** [comment]
I believe that the "Learn" button at the top of the challenge map does this.

**Comment by DiegoRBaquero** [comment]
@SaintPeter That does the trick :+1:

**Comment by kprenesti** [comment]
The Learn button goes to the last task you looked at, whether you finished it or not.  Making it go to the last UNDONE task would be more helpful, I think.

**Comment by DiegoRBaquero** [comment]
@kprenesti You are right, when I tested what @SaintPeter said I was at my first undone actually haha.

I would love if "Learn" took you to the first undone challenge.

**Comment by ltegman** [comment]
@DiegoRBaquero The problem with having learn take you to the first undone challenge is that if someone skips some of the optional waypoints and is working on bonfires it would be cumbersome for the button to keep taking them back to the challenges they skipped.

**Comment by DiegoRBaquero** [comment]
How about skipping those optionals if there are done challenges after them? Wouldn't that solve it?

**Comment by raisedadead** [comment]
Is this necessary any longer, the map aside show, challenges which are completed with a check box and scroll to the recent challenge automatically.

Closing as stale. Please comment if you feel this should be taken up.
