### ISSUE TITLE
Building a Spreadsheet - Step 60 - confusing explanation regarding function “currying”

### ISSUE THREAD

**Issue by darkpsinight** [freeCodeCamp/freeCodeCamp#56156]
#### Description:

The phrase *"innermost function reference from `addCharacters`"* in **Step 60** is unclear. It doesn't accurately describe the currying process of the `addCharacters` function.

#### Suggested Fix:

Update the text to: *"The `.map()` function receives the function returned from `addCharacters`, which takes two arguments in sequence."*

#### Additional Info:

This will make it clearer for users who may not be familiar with currying.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-60

### Your code

```
-


```

### Expected behavior

-

### Screenshots

![Screenshot 2024-09-18 141758](https://github.com/user-attachments/assets/24636da5-528d-4de5-a8a1-e4e4b5fa1099)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

```[tasklist]
### Tasks
```

**Comment by ilenia-magoni** [comment]
I agree that the description could be better, but your description is not accurate, `map` is not receiving a function, but that innermost function, `num => charRange(...).map(...)` receive values from the first two functions called

**Comment by naomi-lgbt** [comment]
I am opening this up for contribution.

A PR which resolves this issue should:
- Update the instructions to read `` Now that your `.map()` function is receiving the returned `num =>  charRange(...).map(...)` function reference from the curried `addCharacters` calls, it will properly iterate over the elements and pass each element as `n` to that function. ``
