### ISSUE TITLE
Just need to replace 'k' with 'j'

### ISSUE THREAD

**Issue by strongdan** [FreeCodeCamp/FreeCodeCamp#5615]
Challenge [Waypoint: Nesting For Loops](http://www.freecodecamp.com/challenges/waypoint-nesting-for-loops#?solution=function%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20for%20(var%20i%3D0%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20for%20(var%20j%3D0%3B%20j%20%3C%20arr%5Bi%5D.length%3B%20j%2B%2B)%0A%20%20%20%20product%20*%3D%20arr%5Bi%5D%5Bj%5D%3B%20%20%20%20%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2606.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
The sample code in this challenge reads as follows:
var arr = [
  [1,2], [3,4], [5,6]
];
for (var i=0; i < arr.length; i++) {
  for (var j=0; k < arr[i].length; j++) {
    console.log(arr[i][j]);
  }
}

I believe in the second for loop you need the k to be a j in order for things to iterate properly

**Comment by ltegman** [comment]
This has been fixed by PR #5567 and is pending deployment to the website. Thanks and happy coding!
