### ISSUE TITLE
Typo found Waypoint: Understanding Uninitialized Variables

### ISSUE THREAD

**Issue by zrsmith75** [FreeCodeCamp/FreeCodeCamp#5616]
In this assignment we are given sample variables to initialize, a = 5, b = 10, c = "I am"; however, the assignment criteria states to make a = 6, b = 15 and c = "I am". The assignment grades correct based on the Instructions in the paragraph instead of the assignment criteria. 

p.s. If I did this incorrectly, please accept my apology, as this is my first attempt! 

Challenge [Waypoint: Understanding Uninitialized Variables](http://www.freecodecamp.com/challenges/waypoint-understanding-uninitialized-variables#?solution=%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%205%3B%0Avar%20b%20%3D%2010%3B%0Avar%20c%20%3D%20%22I%20am%20a%22%3B%0A%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Initialize these three variables
var a = 5;
var b = 10;
var c = "I am a";


// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```
![bugfcc](https://cloud.githubusercontent.com/assets/8953340/12061558/8f1092a0-af46-11e5-8a08-71b7a6b7f658.PNG)

**Comment by ltegman** [comment]
I'm not quite sure I understand the problem. It looks to me like it marks everything as correct if you follow the instructions and that the instructions and test cases are worded correctly. Am I missing something?

**Comment by zrsmith75** [comment]
The variables requested in the instructions that are graded, ie the ones with the check marks give a positive answer that is not stated. 
As you can see, the first one says:
a should be defined and have a value of 6
b should be defined and have a value of 15

However, if you look at my code, I had to enter a = 5; and b = 10; in order to get a passing answer. In my experience so far, all the criteria established by the red x must be met exactly as stated to pass, here it is not. Maybe I am missing something, but the graded criteria is not what I had to enter to pass.

**Comment by SaintPeter** [comment]
Oooooh, I get it.

The criteria should probably read:
>a should be defined.  a should have a final value of 6
>b should be defined.  b should have a final value of 15

Or possibly break them into separate tests entirely.  Is that what you mean?

**Comment by zrsmith75** [comment]
Partly, though the grader needs to use those values to grade against. Currently those are considered incorrect.

**Comment by SaintPeter** [comment]
I don't know what you mean then.  Can you please spell out what you would like the tests to look like?

**Comment by zrsmith75** [comment]
I have included a new image that shows the grading criteria does not match the answers provided, yet it was graded correctly! 

![bugfcc](https://cloud.githubusercontent.com/assets/8953340/12061907/321375c8-af4f-11e5-9a5b-507704da6517.PNG)

**Comment by SaintPeter** [comment]
Of course they are not equal.  They are modified by the code below.  You are given explicit instructions in the **Instructions** section as to what to set them to.  Only when you set them that way will you get final values as described in the tests.

**Comment by zrsmith75** [comment]
I see, sorry I wasted your time.

**Comment by ongiti** [comment]
@zrsmith75 : You are brillient person. The instructions were not clear to me either. code camp maybe should consider unless it is a tricky exam questions where student should fail. i like you apologise before you a question is the only way one gets help. you are a good lad
