### ISSUE TITLE
[HACKTOBERFEST 2024] - Semantic HTML Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56175]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the `Quiz Name` quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-name`.

**All quiz questions need to relate to one of these topics:**

- Importance of semantic HTML
- Importance of having good structural hierarchy 
- Difference between presentational and semantic HTML
- emphasis element 
- Idiomatic Text element
- strong element 
- Bring Attention To element
- description lists 
- Inline Quotation element
- Block Quotation element
- Abbreviation element
- Address element
- `<time>`: The (Date) Time element
- The Superscript element
- The Subscript element
- The code element
- `<u>`: The Unarticulated Annotation (Underline) element
- The ruby element
- `<s>`: The Strikethrough element

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by ReenaChidrala** [comment]
i want to solve issues @naomi-lgbt pls assign me

**Comment by ReenaChidrala** [comment]
can i clam this

**Comment by naomi-lgbt** [comment]
@ReenaChidrala you are already assigned #56228 - Please leave this quiz for another contributor.

**Comment by GustaGabe** [comment]
Can you assign to me ?

**Comment by uditbaliyan** [comment]
Can you assign to me this issue?

**Comment by Nishant-k-sagar** [comment]
Hey @naomi-lgbt, I would like to work on this issue, and start my open source contribution with hacktoberfest.
Kindly assign this issue to me, as I have gone through docs too

**Comment by Anandraj2908** [comment]
I want to work on this issue. Could you assign this issue to me?

**Comment by calvinrodrigues500** [comment]
@naomi-lgbt Can you please assign this to me.

**Comment by ilenia-magoni** [comment]
The issue has already please assigned, pelase stop asking
