### ISSUE TITLE
incement operator result is not checked

### ISSUE THREAD

**Issue by raju249** [FreeCodeCamp/FreeCodeCamp#5617]
Challenge [Waypoint: Increment a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar++;


```

The test still shows 
```
myVar = 87
```

**Comment by ltegman** [comment]
The increment operator removes the needs for assignment. Your code should simply be `myVar++;`. We've merged a PR that seeks to make this more explicitly clear in the instructions.

Thanks and happy coding!

**Comment by raju249** [comment]
Thanks @ltegman :)
