### ISSUE TITLE
[HACKTOBERFEST 2024] - CSS Relative and Absolute Units Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56182]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the CSS Relative and Absolute Units quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-css-relative-and-absolute-units`.

**All quiz questions need to relate to one of these topics:**

- absolute units (e.g. px, pt)
- percentages
- ems and rems
- vh and vw
- calc()

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
@freecodecamp/curriculum-admins

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by spartanns** [comment]
I would like to work on this one, please.

**Comment by jdwilkin4** [comment]
HI @spartanns 

Rahul has been assigned. But there are still plenty of issues open 👍

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).
