### ISSUE TITLE
Semi-colon bug

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#5619]
Waypoint: Concatenating Strings with the Plus Equals Operator

This code doesn't pass since I need a semi-colon at the end of ```myStr.....```:
```javascript
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = "This is the first. ";
myStr += "This is the second sentence."
```

But this code does pass:
```javascript
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = "This is the first. ";
myStr += "This is the second sentence."
;
```

**Comment by ltegman** [comment]
I can't get either of these solutions to pass, and neither should because the first string isn't correct. With the correct strings it will pass with or without the semicolon. Thanks and happy coding!

**Comment by AkiraLaine** [comment]
@ltegman Sorry. After changing ```myStr``` it passes fine. But it still passes after putting the ";" on another line, which it shouldn't do.

**Comment by ltegman** [comment]
Since the semi-colon isn't required in javascript there's technically nothing wrong with putting the semicolon on the next line. Definitely bad practice, but not actually incorrect syntax.

**Comment by SaintPeter** [comment]
I'm pretty sure that you can have an unlimited amount of white space between the end of the statement and your semicolon, including line feeds.

If it's not causing a syntax error, we're not testing for it.

**Comment by AkiraLaine** [comment]
@SaintPeter Not sure what you mean? I tested with the semi-colon on a new line straight after my last line of code. I just wanted to point it out. :smile:

**Comment by jamella1** [comment]
Okay ready for the ultimate dumb? It wouldnt work ANY which way until I put both strings assigned to myStr WITHOUT concatenating, and then used += underneath for the period ONLY.
