### ISSUE TITLE
[HACKTOBERFEST 2024] - Strings Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56197]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Strings quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-javascript-strings`.

**All quiz questions need to relate to one of these topics:**

- bracket notation (and extracting character form string)
- template literals and interpolation
- escape sequences and new lines
- String constructor
- substrings
- `prompt()` method
- string object vs primitive
- ASCII and charCodeAt() and fromCharCode()
- toString()
- includes()
- slice()
- toLowerCase() toUpperCase()
- replace()
- repeat()
- trim()

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by rachhanari** [comment]
i want to slove this issue

**Comment by rachhanari** [comment]
@naomi-lgbt hi  i want to slove this issue please assign me

**Comment by pepitacodes** [comment]
Hi, I would like to work in this issue if still available please, thank you~

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).

**Comment by a2937** [comment]
### It has been seven days without activity. This issue is now open for reassignment.

**Comment by ByteXenon** [comment]
Can you assign this issue to me?

**Comment by nitesh2920** [comment]
I can work on it

**Comment by tg-100** [comment]
Hello! I would like to take this up. Thanks.

**Comment by naomi-lgbt** [comment]
@pepitacodes you were next in line, so this issue has been assigned to you. Let us know if you are no longer interested.

**Comment by naomi-lgbt** [comment]
@ByteXenon you're up!
