### ISSUE TITLE
[HACKTOBERFEST 2024] - Problem Solving and Algorithmic Thinking Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56216]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Problem Solving and Algorithmic Thinking quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-problem-solving-and-algorithmic-thinking`.

**All quiz questions need to relate to one of these topics:**

- problem solving approaches

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by INVOKER2002** [comment]
hey there , @naomi-lgbt , i would love to work on this issue , if possible please assign it to me .

**Comment by gikf** [comment]
Hey @harshitaadam,

you are already assigned to different issue - https://github.com/freeCodeCamp/freeCodeCamp/issues/56215.

**Comment by INVOKER2002** [comment]
@gikf should i also include questions regarding dynamic programming or should i keep it only till the basic stuff , what kind of difficulty do you wat for the quiz .

**Comment by naomi-lgbt** [comment]
Sorry for the lack of topics on this one - the section covered by this quiz is rather small. It does look like it's more basic algorithms. For example, something like a Roman numeral converter, or an ROT-13 cipher solver.

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).

**Comment by a2937** [comment]
### It has been seven days without activity. This issue is now open for reassignment.

**Comment by Bharatkgupta** [comment]
@naomi-lgbt I'd like to contribute to this issue. Could you assign it to me?

**Comment by tg-100** [comment]
Hi! I'd like to contribute to this issue.

**Comment by naomi-lgbt** [comment]
@Bharatkgupta all yours!
