### ISSUE TITLE
[HACKTOBERFEST 2024] - Asynchronous JavaScript Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56222]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Asynchronous JavaScript quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-asynchronous-javascript`.

**All quiz questions need to relate to one of these topics:**

- What is asynchronous programming?
- async attribute for script elements
- fetch API
- HTTP methods
- res.json()
- promises and promise chaining
- .then(), .catch(), .finally()
- async/await
- Geolocation API and getCurrentPosition()

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by khatri7** [comment]
I would like to work on this

**Comment by mendoncamaria** [comment]
Hi. I would like to work on this. If possible do assign it to me. Thanks.

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).

**Comment by a2937** [comment]
### It has been seven days without activity. This issue is now open for reassignment.

**Comment by khatri7** [comment]
I can take this up!

**Comment by Abhi0049k** [comment]
@naomi-lgbt , can you assign this issue to me

**Comment by naomi-lgbt** [comment]
@khatri7 you are already assigned to #56204 

@Abhi0049k this one's all yours!
