### ISSUE TITLE
[HACKTOBERFEST 2024] - Testing Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56229]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Testing quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-testing`.

**All quiz questions need to relate to one of these topics:**

- unit testing vs functional testing vs e2e testing
- usability testing
- compatibility testing
- performance testing
- security testing
- accessibility testing
- tools to run automated tests (playwright, jest, etc)
- cross-browser testing
- CI/CD
- Automated tests on Github
- External tools like CircleCI or TravisCI

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by ReenaChidrala** [comment]
i want to solve issues pls assign to me @naomi-lgbt

**Comment by ReenaChidrala** [comment]
i want to solve this  issues

**Comment by gikf** [comment]
Hey @ReenaChidrala,

you are already assigned to different issue - https://github.com/freeCodeCamp/freeCodeCamp/issues/56228.

**Comment by Rizvi-Faiz** [comment]
i would like to work on this @naomi-lgbt @gikf

**Comment by Rizvi-Faiz** [comment]
I would like to solve this issue @gikf @naomi-lgbt can you please assign this to me

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).

**Comment by a2937** [comment]
### It has been seven days without activity. This issue is now open for reassignment.

**Comment by Muhammad-Rebaal** [comment]
Hi  @naomi-lgbt !
Assign this issue to me , I'll work on it.

**Comment by naomi-lgbt** [comment]
@Muhammad-Rebaal you have been reassigned to #56191 - we're going to keep this issue available for a new contributor.

**Comment by SahilWMI** [comment]
hey @naomi-lgbt can i work on this issue??

**Comment by naomi-lgbt** [comment]
@SahilWMI all yours!

**Comment by AyushAchary67** [comment]
Hey i would really like to contribute to this!

**Comment by naomi-lgbt** [comment]
Hey @AyushAchary67, I just gave you #56211 - let's leave this one for another contributor.

**Comment by Arnavthakare19** [comment]
Hey @naomi-lgbt can I work on this issue

**Comment by gikf** [comment]
Hey @Arnavthakare19,

I've assigned it to you.
