### ISSUE TITLE
[HACKTOBERFEST 2024] - Graphs and Trees Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56220]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Graphs and Trees quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-graphs-and-trees`.

**All quiz questions need to relate to one of these topics:**

- What are graphs? (types like scatterplot, bar graph)
- Depth first and breadth first search
- Matrices and adjaceny lists
- Trees and tries

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by Tanuj1718** [comment]
can you please assign it to me?

**Comment by Emminence23** [comment]
please review my work , I have made both definition based and brain storming based problems on all the topics mentioned

**Comment by Tanuj1718** [comment]
@naomi-lgbt  I have followed all the rules and guidelines, can you please tell me why my PR gets rejected again?

**Comment by ilenia-magoni** [comment]
@Tanuj1718 Following the special rules for the hacktoberfest issues, you have not been assigned to this issue, only who is assigned can open a PR

**Comment by Tanuj1718** [comment]
@ilenia-magoni  @naomi-lgbt  can you please assign it to me as I have first created the PR when this issue got open.

**Comment by ilenia-magoni** [comment]
@Tanuj1718 stop creating PRs for an issue you have not been assigned to. Once (if) you are assigned, you can open the PR.

**Comment by Rizvi-Faiz** [comment]
Can you assign this issue to me @ilenia-magoni @naomi-lgbt

**Comment by Geeky99** [comment]
@naomi-lgbt Can you assign this to me, please?

**Comment by naomi-lgbt** [comment]
A quick note to maintainers - the contributor assigned to this issue is a regular member of our Discord community. She's got other obligations that will prevent her from making a pull request until later this month.

Please do not unassign this issue after 7 days - we have already spoken on Discord about extending the time period so she's able to make a contribution.

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).

**Comment by Sembauke** [comment]
Why is this blocked?

**Comment by ilenia-magoni** [comment]
@Sembauke because it has been moved to a different section, see the google sheet

**Comment by jdwilkin4** [comment]
I am closing this issue because as mentioned earlier graphs and trees has been moved to the python chapter. 
Also, the remaining quizzes will be completed in house.
