### ISSUE TITLE
[HACKTOBERFEST 2024] - Bash Commands and Command Line Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56230]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Bash Commands and Command Line quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-bash-commands`.

**All quiz questions need to relate to one of these topics:**

- Terminal vs. command line
- Short-cuts in command line to speed up your workflows
- bash scripting and some basic commands
- command options/flags
- navigating the fs in the terminal
- One of the courses before this quiz is [located here.](https://github.com/freeCodeCamp/learn-bash-by-building-a-boilerplate/blob/main/TUTORIAL.md) Any commands or topics covered in that course can be used in the quiz. Here's a partial list: `pwd`, `ls`, `cd`, `mv`, `rm`, `cp`, `mkdir`, `touch`, `--help` flag, `find`, `rmdir`, recursive flag, 

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by ReenaChidrala** [comment]
i want to solve issues @naomi-lgbt

**Comment by shubha987** [comment]
I want to work on this issue . Please assign me @naomi-lgbt

**Comment by ReenaChidrala** [comment]
i want to solve issues

**Comment by swaindhruti** [comment]
Hello @naomi-lgbt,

I'd like to take on this quiz. I have `hands-on experience with Bash commands, command-line navigation, and scripting`, and I'm confident I can effectively cover the topics mentioned. Could you please assign this issue to me?

Thank you!

**Comment by gikf** [comment]
Hey @ReenaChidrala,

you are already assigned to different issue - https://github.com/freeCodeCamp/freeCodeCamp/issues/56228.

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).
