### ISSUE TITLE
[HACKTOBERFEST 2024] - Git Quiz

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/freeCodeCamp#56235]
> [!IMPORTANT]
> This issue is part of our 2024 Hacktoberfest initiative. If you are interested in working on this issue, refer to our [top-level tasks](https://github.com/freeCodeCamp/freeCodeCamp/issues/56170) to see if this issue is claimed, or to claim it if it is not.

This issue is to create the Git quiz.

The file you should be working on is found in `/curriculum/challenges/english/25-front-end-development/quiz-git`.

**All quiz questions need to relate to one of these topics:**

- What is version control
- Purpose of/benefits to sites like Github and Gitlab
- Installing and setting up git
- security requirements like SSH/GPG keys
- What is a repository
- How to push to repository
- How to contribute to other people's repositories
- How to create new branch
- What is a pull request
- What does code review process look like
- How do you use github pages to deploy a project
- How to remain in sync with remote
- `.gitignore` and what to include
- Branching strategies
- Merge conflicts and resolution (rebase too)
- One of the interactive courses before this quiz is [located here.](https://github.com/freeCodeCamp/learn-git-by-building-an-sql-reference-object/blob/main/TUTORIAL.md) Any commands or topics covered in that course can be used in the quiz as well. Here's a partial list: status, staged/unstaged changes, adding and committing changes, log/commit history, stashing and popping changes, merging branches, squashing/rewording/dropping commits, reverting commits, resetting, .gitignore

> [!CAUTION]
> Questions which do not fall under these topics will be rejected.

You are welcome to include code blocks in your questions, but please keep them short (four lines or less).

Please do NOT open a pull request until you have completed all questions. Your quiz should have **exactly 20 questions**.

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing. This issue will be opened for contribution when Hacktoberfest starts on October 1st.

> [!CAUTION]
> Pull requests which are **created before** October 1st will not be eligible for Hacktoberfest. We appreciate enthusiasm, but encourage you to hold off on contributing to this issue until the event has begun.

If you wish to be notified when this issue is opened for contribution, subscribe to notifications:

![image](https://github.com/user-attachments/assets/a1f1f2f5-8c64-403a-a5be-5d5495d8f886)

**Comment by naomi-lgbt** [comment]
# This issue is now open
If you would like to work on this issue, please leave a comment so we can assign it to you.

[Be sure to read our contributing guidelines](https://contribute.freecodecamp.org).

**Comment by farihaNaqvi** [comment]
Could you please assign this to me

**Comment by Dhairya-A-Mehra** [comment]
I would like to work on the Git quiz issue for Hacktoberfest 2024. Could you please assign this issue to me?

**Comment by franfreezy** [comment]
i can work on this

**Comment by khatri7** [comment]
I would like to work on this

**Comment by INVOKER2002** [comment]
i would love to work on making an interactive and comprehensive quiz regarding git and version control . If possible please assign this issue to me . surely , you wont be disappointed :).

**Comment by Muhammad-Rebaal** [comment]
Hi @naomi-lgbt 
Could you please assign this to me ?

**Comment by swaindhruti** [comment]
Hi @naomi-lgbt,

I'd love to work on this Git quiz. I have prior experience with these concepts and have used Git extensively in projects. Could you please assign this issue to me?

Thank you!

**Comment by naomi-lgbt** [comment]
# This issue has been assigned a contributor. To prevent extraneous notifications, the issue is now locked. If you have any questions, please reach out to me in our [Discord community](https://chat.freecodecamp.org).
