### ISSUE TITLE
Waypoint: Chaining If Else Statements : doesn't take into account if lines are commented out

### ISSUE THREAD

**Issue by MiLeung** [FreeCodeCamp/FreeCodeCamp#5623]
Challenge [Waypoint: Chaining If Else Statements](http://www.freecodecamp.com/challenges/waypoint-chaining-if-else-statements#?solution=function%20myTest(num)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(num%20%3C%205)%7B%0A%20%20%20%20return%20'Tiny'%3B%0A%20%20%7D%0A%20%20else%20if(num%20%3C%2010)%7B%0A%20%20%20%20return%20'Small'%3B%0A%20%20%7D%0A%20%20else%20if(num%20%3C%2015)%7B%0A%20%20%20%20return%20'Medium'%3B%0A%20%20%7D%0A%20%20else%20if(%20num%20%3C%2020)%7B%0A%20%20%20%20return%20'Large'%3B%0A%20%20%7D%0A%20%20else%20if(num%20%3E%3D%2020)%7B%0A%20%20%20%20return%20'Huge'%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2Freturn%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(7)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(num) {
  // Only change code below this line
  if(num < 5){
    return 'Tiny';
  }
  else if(num < 10){
    return 'Small';
  }
  else if(num < 15){
    return 'Medium';
  }
  else if( num < 20){
    return 'Large';
  }
  else if(num >= 20){
    return 'Huge';
  }
  
  //return "Change Me";
  // Only change code above this line
}

// Change this value to test
myTest(7);

```

Test things "//return "Change Me";" is a return statement when it's just commented out.

**Comment by SaintPeter** [comment]
You are correct.  We are using a regular expression to count the number of `return` statements.  We cannot parse the javascript to find "active" `return` statements.  I guess you'll just have to delete the line.

Sorry, not something we can fix.  Thanks and happy coding!

**Comment by MK-Emon** [comment]
![git](https://cloud.githubusercontent.com/assets/20726260/19000275/7b26ad2e-8763-11e6-8ae3-30632ff65191.JPG)

I have done as said but still i am having this problem. plz help

**Comment by texas2010** [comment]
@MK-Emon 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by Kaushishal** [comment]
@MK-Emon  

In your first else if return  statement S for "small" should be uppercase not lower case.

**Comment by AntoineDS** [comment]
@MK-Emon The S in Small should be Uppercase

**Comment by Al-AmeenIb** [comment]
@MK-Emon .... Ur code is right except changing testSize(7) and making sure ur curly braces are pointing to else if.  Also remove the curly braces in front of else return "change me" n dt of d double //....
Happy Coding!

**Comment by Cor73xX** [comment]
@ MK-Emon ... You have a typo. Where you have " small" you should have "Small".

**Comment by taosang1992** [comment]
I also have problem about this challenge.
Finally ,I found all words that need be returned is lowercase.
Samll——>small.
Tiny——>tiny.
……

**Comment by MihaelaMarinca** [comment]
this is the correct answer: 

function testSize(num) {
  // Only change code below this line
 if(num < 5){
    return 'Tiny';
  }
  else if(num < 10){
    return 'Small';
  }
  else if(num < 15){
    return 'Medium';
  }
  else if( num < 20){
    return 'Large';
  }
  else if(num >= 20){
    return 'Huge';
  }
  // Only change code above this line
}

// Change this value to test
testSize(5);

**Comment by texas2010** [comment]
@MihaelaMarinca 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by MihaelaMarinca** [comment]
sorry, i didn;t know.

**Comment by ExillustX** [comment]
just uppercase all return strings:
`"example" to "Example"`

**Comment by TahsinTabassum** [comment]
@MiLeung  you should have testSize instead of myTest 👍
