### ISSUE TITLE
Cash register: Test 17 fails sometimes

### ISSUE THREAD

**Issue by DanTGL** [freeCodeCamp/freeCodeCamp#56241]
### Describe the Issue

Test 17 is incorrect sometimes, it fails around 10% of the time.

One incorrect case is
```
cash = 50
price = 22.7
cid = [
  [ 'PENNY', 0 ],
  [ 'NICKEL', 0 ],
  [ 'DIME', 0.7 ],
  [ 'QUARTER', 2 ],
  [ 'ONE', 1 ],
  [ 'FIVE', 55 ],
  [ 'TEN', 70 ],
  [ 'TWENTY', 140 ],
  [ 'ONE HUNDRED', 0 ]
]
```
result is `OPEN TWENTY: $20.00 FIVE: $5.00 ONE: $1.00 QUARTER: $1.00 DIME: $0.30`
which is correct based on the input, but it's supposed to be `INSUFFICIENT_FUNDS` according to the test

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-cash-register-project/build-a-cash-register

### Your code

```js

let price = 79.35;
let cid = [ [ 'PENNY', 0.03 ],
  [ 'NICKEL', 0 ],
  [ 'DIME', 0.9 ],
  [ 'QUARTER', 3.75 ],
  [ 'ONE', 7 ],
  [ 'FIVE', 70 ],
  [ 'TEN', 90 ],
  [ 'TWENTY', 200 ],
  [ 'ONE HUNDRED', 1400 ] ];

const CurrencyValue = [
  1,
  5,
  10,
  25,
  100,
  500,
  1000,
  2000,
  10000,
];

const cashInput = document.getElementById("cash");
const purchaseButton = document.getElementById("purchase-btn");
const changeDueSpan = document.getElementById("change-due");

function calcChangeDue(cash) {
  function currenciesToString(arr) {
    return arr.reduce((str, val) => str + (val[1] !== 0 ? ` ${val[0]}: $${(val[1] / 100).toFixed(2)}` : ""), "")
  }

  console.log(cid)

  // Uses integers for arithmetic to avoid floating-point errors
  const cash_pennies = Math.round(cash * 100);

  const cid_pennies = cid.map(elem => [elem[0], Math.round(elem[1] * 100)]);
  const totalDrawer = [cid_pennies[0][1]];

  for (let i = 1; i < cid_pennies.length; i++) {
    totalDrawer.push(totalDrawer[i - 1] + cid_pennies[i][1]);
  }

  // Close if drawer contains the exact amount of change requested
  if (totalDrawer[cid_pennies.length - 1] === cash_pennies) {
    return "CLOSED" + currenciesToString(cid_pennies);
  }

  const recur = (idx, cashLeft) => {
    if (totalDrawer[idx] < cashLeft) {
      return null;
    }

    for (let currency = cid_pennies[idx][1]; currency >= 0; currency -= CurrencyValue[idx]) {
      if (currency > cashLeft) continue;

      if (currency == cashLeft) {
        return [[cid_pennies[idx][0], currency]]
      }
      if (idx > 0) {
        if (currency + totalDrawer[idx - 1] < cashLeft) {
          break;
        }

        const recursive = recur(idx - 1, (cashLeft - currency));
        if (recursive != null) {
          return [[cid_pennies[idx][0], currency], ...recursive];
        }
      }
    }

    return null;
  }
  const result = recur(cid.length-1, cash_pennies);

  if (result == null) {
    return "INSUFFICIENT_FUNDS";
  }

  return "OPEN" + currenciesToString(result);
}

purchaseButton.addEventListener("click", () => {
  const cash = Number.parseFloat(cashInput.value);
  console.log(cash, price);
  if (cash < price) {
    alert("Customer does not have enough money to purchase the item");
  } else if (cash === price) {
    changeDueSpan.innerText = "No change due - customer paid with exact cash";
  } else {
    const changeDue = calcChangeDue(cash - price);

    console.log(changeDue);
    
    changeDueSpan.innerText = "Status: " + changeDue;
  }
  console.log();
});

```

### Expected behavior

The individual denomination amounts should make it impossible to return the needed change.

### System

- Device: Desktop
- OS: Windows 10
- Browser: Firefox

**Comment by ilenia-magoni** [comment]
do you mean this one?
https://github.com/freeCodeCamp/freeCodeCamp/blob/4cf810f18eb7ea623e9e976ee4fb379bb712910d/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md?plain=1#L375-L415

It looks like there is some imprecision in the checks in the test, and it would need to be changed

**Comment by DanTGL** [comment]
> do you mean this one?
> 
> https://github.com/freeCodeCamp/freeCodeCamp/blob/4cf810f18eb7ea623e9e976ee4fb379bb712910d/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md?plain=1#L375-L415
> 
> It looks like there is some imprecision in the checks in the test, and it would need to be changed

Yes, that's the one

**Comment by ilenia-magoni** [comment]
I'll open it for contribution.

Note, also this needs to be checked and changed: https://github.com/freeCodeCamp/freeCodeCamp/blob/4cf810f18eb7ea623e9e976ee4fb379bb712910d/curriculum/challenges/english/25-front-end-development/lab-cash-register/66c58d2477d7622ddc30ae06.md

**Comment by gikf** [comment]
This is a bit peculiar case. Problem comes from the way test is calculating the values for cash drawer. There's assumption that from each higher denomination, the possible maximum will be used before moving to the smaller denomination.

Test calculations:
```
Denomination
twenties     27,3 -   20  =  7,3
fives         7,3 -    5  =  2,3
ones          2,3 -    1  =  1,3
quarters      1,3 - 1,25  =  0,05
```
Because of that `QUARTER` amount is way higher, as it cannot complete the change on it own.

However, when it would be taken less of quarters:
```
Denomination
quarters      1,3 -   1   =  0,3
dimes         0,3 - 0,3   =  0,0
```

To be honest I'm a bit torn, since none of the explicit tests, to get the right answer, require to take less than  possible of the denomination. Perhaps it would be the best to add another explicit test, which would make clear such situation can be expected?

**Comment by a2937** [comment]
I believe writing another explicit test might be the right answer here.

**Comment by gikf** [comment]
To be clear, the currently expected `INSUFFICIENT_FUNDS` is wrong for such cases. It is possible to get such change, as demonstrated, so test is not calculating the cash in drawer amounts correctly for this case.

**Comment by a2937** [comment]
How are we supposed to know that the change in the next coin slot will be enough to cover the required amount of change?

**Comment by ilenia-magoni** [comment]
The random test needs to be fixed to avoid such situations. We don't require a solution more complex than what we have, that consider the values in order. It's the test that needs to be changed to avoid proposing such `cid`s
