### ISSUE TITLE
Learn Accessibility By Building a Quiz - Step 25 

### ISSUE THREAD

**Issue by goliardus** [freeCodeCamp/freeCodeCamp#56258]
### Describe the Issue

Adding the requirements and running the tests works (**_Within the first span element, add the text Question.
In the second span element, add the text Question._**). But the CSS code that would target the class is already present and fully fleshed, so no text is displayed. The dissonance comes when reaching Step 26, that explains what kind of CSS code would hide the aforementioned class, and explicitly says that the **_The `.sr-only` text is still visible._** while also showing the text in the prepared environment.

It might be confusing for a new learner to see that no text is shown at step 25 (No concept before that point did that) and then find that step 26 _is_ showing the expected final result of a succesful step 25 (as is always the case), without the .`sr-only` CSS code being present yet.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-25

### Your code

```
            <h3><span class="sr-only">Question</span>1</h3>
            <fieldset class="question"></fieldset>
          </div>
          <div class="question-block">
            <h3><span class="sr-only">Question</span>2</h3>

```

### Expected behavior

The text _**Question**_ should appear twice in step 25 rendering HTML window, after modifying the code according to the test requirements.

### Screenshots

**@Step 25**
![step25bug](https://github.com/user-attachments/assets/cffacbd1-9c2e-46c6-ae16-1c409a5559bd)
![step25bug_2](https://github.com/user-attachments/assets/a9776746-54e7-49a0-82c0-ab86e1112a09)
**@Step26**
![step26aftermath](https://github.com/user-attachments/assets/0924c4e3-f5f6-4574-86f7-27993f24d7e0)

### System

- Device: [Laptop]
- OS: [Pop_OS! (Ubuntu 22.04)]
- Browser: [Brave Browser ]
- Version: [1.70 (Chromium 129)]

**Comment by ilenia-magoni** [comment]
it makes sense to move giving the class to the element to a later step or writing the css code for the class in a later step
