### ISSUE TITLE
Building a Platformer Game - Step 90

### ISSUE THREAD

**Issue by darkpsinight** [freeCodeCamp/freeCodeCamp#56260]
### Describe the Issue

There is an error in the code provided in Step 90 regarding the collision detection logic for platforms.
**The problem is:** The fourth condition `player.position.y <= + platform.height + platform.position.y` contains a syntax error (the unnecessary `+` before `platform.height`) and will not correctly evaluate the player's vertical position relative to the platform.

**Recommendation:** Please update the course materials to reflect the correct condition in the collision detection logic.

Thank you!

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-90

### Your code

-

### Expected behavior

-

### Screenshots

![correct](https://github.com/user-attachments/assets/07b2abf4-b746-418a-94b4-a6453141721c)
![wrong](https://github.com/user-attachments/assets/cf156d64-1cae-4629-bc81-e8406564a443)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by 0xprathamesh** [comment]
Hey @darkpsinight can u assign this issue to me!

**Comment by ShaunSHamilton** [comment]
Hello there 👋 

> The fourth condition player.position.y <= + platform.height + platform.position.y contains a syntax error (the unnecessary + before platform.height) and will not correctly evaluate the player's vertical position relative to the platform.

This is the starting (seed) code:

```js
    const platformDetectionRules = [
      player.position.x >= platform.position.x - player.width / 2,
      player.position.x <=
        platform.position.x + platform.width - player.width / 3,

    ];
```

The third and fourth conditions are added by YOU. So, if there is an unnecessary `+`, only you can remove it. Also, your issue description and screenshot do not match. So, I am unsure what problem you are referring to.

As such, I am going to close this issue. If you can explain where the problem in the content is, then we will reopen this issue. Thank you.

**Comment by darkpsinight** [comment]
Hi @ShaunSHamilton , The test seems to fail because the expected order `(platform.position.y + platform.height)` isn't being followed, even though both are equivalent.
1+2 = 3
2+1 != 3 ?

**Comment by ShaunSHamilton** [comment]
Ah. Ok, I understand what you mean now. Thank you for explaining further.

The current tests are too strict with the expected input:

```js
assert.match(code, /const\s+platformDetectionRules\s*=\s*\[\s*player\.position\.x\s*>=\s*platform\.position\.x\s*-\s*player\.width\s*\/\s*2\s*,\s*player\.position\.x\s*<=\s*platform\.position\.x\s*\+\s*platform\.width\s*-\s*player\.width\s*\/\s*3\s*,\s*player\.position\.y\s*\+\s*player\.height\s*>=\s*platform\.position\.y\s*,\s*player\.position\.y\s*<=\s*platform\.position\.y\s*\+\s*platform\.height\s*,?\s*\]\s*;?/)
```

The solution should probably be to test the value of `platformDetectionRules` with mocked data.

**Comment by ilenia-magoni** [comment]
Opening for contribution, the test should be updated to at least accept both orders

Optional the part of testing with mocked data instead of regex, but it would make the test more robust for sure
