### ISSUE TITLE
Typo in Basic HTML Quiz

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#56277]
## Description

The word "in" should be remove:

```diff
--- A boolean attribute in can be present or absent
+++ A boolean attribute can be present or absent
```

## Changes needed

Apply the change to

https://github.com/freeCodeCamp/freeCodeCamp/blob/c3cebba832d2be009f9728a5c2cd0f7a48469b1b/curriculum/challenges/english/25-front-end-development/quiz-basic-html/66df3b712c41c499e9d31e5b.md#L114

**Comment by harshsbhat** [comment]
can I work on this?
