### ISSUE TITLE
String is missing a quote

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#56273]
In this paragraph in the code block the string `Twice` is missing a quote:

https://github.com/freeCodeCamp/freeCodeCamp/blob/945504d9e0ab681bfca675d5f16545f285853e40/curriculum/challenges/english/07-scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/66694bfa435cef241f6f9a68.md#L21

---

This looks like something that can be fixed by "first-time" code contributors to this repository. THe file you should be looking at to work on a fix is the one linked above.

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by DFwJZ** [comment]
Thank you @ilenia-magoni for identifying and reporting this issue. As a first-time contributor, I'm excited to help:) 

I've submitted a pull request to address the missing quote in the Python list example within the Lambda functions lesson. The PR can be found here: 

[https://github.com/freeCodeCamp/freeCodeCamp/pull/56274](https://github.com/freeCodeCamp/freeCodeCamp/pull/56274)
