### ISSUE TITLE
String not passing properly

### ISSUE THREAD

**Issue by LeoKnox** [FreeCodeCamp/FreeCodeCamp#5627]
The last palindrome '0_0 (: /-\ :) 0-0' is not being passed properly. When it is passed to the function and immediately displayed it is missing the '\' hence the result in the screenshot '0_0 (: /- :) 0-0'. In the screenshot I tried replacing the '\' with a '/' and it still yields the same result. So it is not a display or return issue.

[fcc-palindrome-bug](https://cloud.githubusercontent.com/assets/11515813/12062461/e3aa5b92-af51-11e5-92cd-b88b5cddb4a8.png)

Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20%2F%2Fstr%3D%20str.toLowerCase()%3B%0A%20%20str%20%3D%20str.replace(%2F%5Cu005C%2F%2C%20%22%2F%22)%3B%0A%20%20%2F%2Fstr%20%3D%20str.replace(%2F%5Cu0028%2Fg%2C%20%22)%22)%3B%0A%20%20%2F%2Fstr%20%3D%20str.replace(%2F%5Cu005F%2Fg%2C%20%22-%22)%3B%0A%20%20%2F%2Fstr%20%3D%20str.replace(%2F%5B%5Cs%2C.%5D%2Fg%2C%20%22%22)%3B%20%2F%2FWorks%20don't%20touch!%0A%20%20return%20str%3B%0A%20%20var%20o%20%3D%20%5B%5D%3B%0A%20%20i%3D0%3B%0A%20%20while%20(i%20%3C%20str.length-i)%20%7B%0A%20%20%20%20if%20(str.charAt(i)%20!%3D%3D%20str.charAt(str.length%20-%20i%20-%201))%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%2F%2Freturn(str.charAt(20))%3B%0A%20%20%20%20%20%20%20%20return(false)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20else%0A%20%20%20%20%20%20i%2B%2B%3B%0A%20%20%7D%0A%20%20oneA%20%3D%20str.charAt()%3B%0A%20%20oneB%20%3D%20str.maxLength%20-%201%3B%0A%20%20return(true)%3B%0A%7D%0A%0A%0A%0Apalindrome(%220_0%20(%3A%20%2F-%5C%20%3A)%200-0%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  //str= str.toLowerCase();
  str = str.replace(/\u005C/, "/");
  //str = str.replace(/\u0028/g, ")");
  //str = str.replace(/\u005F/g, "-");
  //str = str.replace(/[\s,.]/g, ""); //Works don't touch!
  return str;
  var o = [];
  i=0;
  while (i < str.length-i) {
    if (str.charAt(i) !== str.charAt(str.length - i - 1))
      {
        //return(str.charAt(20));
        return(false);
      }
    else
      i++;
  }
  oneA = str.charAt();
  oneB = str.maxLength - 1;
  return(true);
}



palindrome("0_0 (: /-\ :) 0-0");

```

**Comment by TheGreenHabi** [comment]
Hi @LeoKnox.
That is true, because ```\``` is escape character in JS. From description of this bonfire
```
remove all non-alphanumeric characters (punctuation, spaces and symbols) 
```
When you do this everything should be ok.

**Comment by DDaems** [comment]
here is your bug: `palindrome("0_0 (: /-\ :) 0-0");` You forgot to escape ;-)

FFC assert:
```
"assert(palindrome(\"0_0 (: /-\\ :) 0-0\") === true, 
'message: <code>palindrome(\"0_0 (: /-\\ :) 0-0\")</code> should return true.');"
```

As you can see it does get passed properly in the test. ;-)

**Comment by ltegman** [comment]
Thanks and happy coding!

**Comment by LeoKnox** [comment]
I know that, but it doesn't mean this isn't a bug.

**Comment by DDaems** [comment]
Its not a bug. The `\` character is a escape character and you need to escape it like this `\\` . This is how JS and most other languages work. You need to escape characters that have special meaning l, so the vompiler knows that you actually want the literal character. Also when writing a string with simglenqoutes. And you would like to use them in your string. You need to escape it with the backslash: `'ain\'t'`;
