### ISSUE TITLE
Missing semicolon in a CSS rule.

### ISSUE THREAD

**Issue by sharabshrestha99** [freeCodeCamp/freeCodeCamp#56284]
### Describe the Issue

.price {
  text-align: right;
  width: 25%
}

Line 156 of the [Github](https://github.com/freeCodeCamp/freeCodeCamp/blob/28ad751427db0d622f3ef0c79daceca74137f27f/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e270702a8456a664f0df.md?plain=1#L156) file within the freeCodeCamp curriculum.

Impact:

While functionally harmless in modern browsers, adding the semicolon improves code consistency and maintainability.

Discussion:

The comments on the issue highlight:
It's likely a typo since other CSS rules in the challenge have semicolons.
While not strictly an error, adding the semicolon for consistency is recommended.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-85

### Steps to Reproduce

1. Go to '[Github](https://github.com/freeCodeCamp/freeCodeCamp/blob/28ad751427db0d622f3ef0c79daceca74137f27f/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e270702a8456a664f0df.md?plain=1)'
2. Click on 'Code Edit'
3. Scroll down to 'Line 156'
4. Add ; at last character

### Expected behavior

The default code has not ; sign
In css part
It does look like a typo: https://github.com/freeCodeCamp/freeCodeCamp/blob/28ad751427db0d622f3ef0c79daceca74137f27f/curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e270702a8456a664f0df.md?plain=1#L156

### Screenshots

![image](https://github.com/user-attachments/assets/007b8321-4049-4046-8045-a6d1524b24fd)
![image](https://github.com/user-attachments/assets/344c805c-e38b-4022-9d8b-b504a4109914)

### System

- Device: Laptop
- OS: Windows 11
- Browser: edge

### Additional context

Current Status:

The issue is labeled as help wanted and type: bug.
Multiple pull requests have been linked that might fix this issue:
Update 5f3ef6e0f8c230bdd2349716.md by sharabshrestha99
fix(curriculum): typo error on css file by brunades
Additional Notes:

A comment offers a reference for further details on semicolons in CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions

**Comment by ilenia-magoni** [comment]
it's not necessarily an error, the last rule doesn't need semicolon, but it could be added for consistency yeah

The list of files in which this is present is (44 files):
```
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3cade99dda4e6071a85dfd.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e01f288a026d709587.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e03d719d5ac4738993.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e04559b939080db057.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e050279c7a4a7101d3.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e05473f91f948724ab.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e056bdde6ae6892ba2.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e06d34faac0447fc44.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e07276f782bb46b93d.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0819d4f23ca7285e6.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e087d56ed3ffdc36be.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0a81099d9a697b550.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0b431cc215bb16f55.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0e0c3feaebcf647ad.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0e9629bad967cd71e.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0eaa7da26e3d34d78.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3ef6e0f8c230bdd2349716.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3f26fa39591db45e5cd7a0.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f459225127805351a6ad057.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f459a7ceb8b5c446656d88b.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f459cf202c2a3472fae6a9f.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f459fd48bdc98491ca6d1a3.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45a05977e2fa49d9119437.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45a276c093334f0f6e9df4.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45a5a7c49a8251f0bdb527.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45a66d4a2b0453301e5a26.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45b0731d39e15d54df4dfc.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45b25e7ec2405f166b9de1.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45b3c93c027860d9298dbd.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45b45d099f3e621fbbb256.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45b4c81cea7763550e40df.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45b715301bbf667badc04a.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e270702a8456a664f0df.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e36e745ead58487aabf2.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e7a4750dd05b5a673920.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46e8284aae155c83015dee.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46ede1ff8fec5ba656b44c.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f46fc57528aa1c4b5ea7c2e.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f4701b942c824109626c3d8.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f475bb508746c16c9431d42.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f716ad029ee4053c7027a7a.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f716bee5838c354c728a7c5.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f7b87422a560036fd03ccff.md:  width: 25%
./english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f7b88d37b1f98386f04edc0.md:  width: 25%

```

I will open this for contribution.

**Comment by plamoni** [comment]
Some additional context on last-rule semi-colons for those who might be interested: https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#css_declaration_blocks

![image](https://github.com/user-attachments/assets/244dd4e0-8a46-43bc-94ea-c602ebc0883e)

But I agree that omitting it is inconsistent with other steps and so it was likely a typo and we should fix it for consistency.

**Comment by BinaryBhakti** [comment]
is this still open? I would like to contribute

**Comment by ilenia-magoni** [comment]
hey @BinaryBhakti 

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
