### ISSUE TITLE
Unclear answer option in Basic HTML Quiz 

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#56280]
## Description

I'm not sure how to fix this sentence, probably `The mouse cursor is over the link.` or `The link is being hovered on.`?

https://github.com/freeCodeCamp/freeCodeCamp/blob/28ad751427db0d622f3ef0c79daceca74137f27f/curriculum/challenges/english/25-front-end-development/quiz-basic-html/66df3b712c41c499e9d31e5b.md#L808

**Comment by ojeytonwilliams** [comment]
`The mouse cursor is over the link` is pretty clear.
