### ISSUE TITLE
Build Five Programs - Step 8

### ISSUE THREAD

**Issue by ultrasin** [freeCodeCamp/freeCodeCamp#56297]
### Describe the Issue

I could execute the file without getting the permission denied error as the task said it would. I am not sure if I did have permission beforehand or maybe it is disabled on the challenge's end. I think it is worth to have a look into it just in case.
![no error permission](https://github.com/user-attachments/assets/5a13e0b0-f82b-4169-92a7-ea76e0fadd27)

### Affected Page

https://www.freecodecamp.org/learn/relational-database/learn-bash-scripting-by-building-five-programs/build-five-programs

### Your code

```

#!/bin/bash
echo hello questionnaire

```

### Expected behavior

"Now, instead of using sh or bash to run your script. You can run it by executing the file and it will default to bash. Execute your script with ./questionnaire.sh. **You will get a permission denied error**."

### System

- Device: Desktop PC
- OS: Win 10 x64 - 10.0.19045
- Browser: Firefox
- Version: Ver. 130.0.1

**Comment by gikf** [comment]
I didn't encounter such issue. Are you doing this tutorial on Gitpod, or locally?

**Comment by ultrasin** [comment]
I am doing it on gitpod VM using vs code browser. I can continue the
tutorial, however. It was strange to have a different output than it
should.

**Comment by naomi-lgbt** [comment]
![Image](https://github.com/user-attachments/assets/f8c9ea08-37cb-4f67-b084-d1dba9c53f6d)

Following the steps in a brand new workspace, I also cannot reproduce this. Going to close as CNR.
