### ISSUE TITLE
no response on submit button 

### ISSUE THREAD

**Issue by jackysfbay** [FreeCodeCamp/FreeCodeCamp#5629]
Challenge [Waypoint: Add a Submit Button to a Form](http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20fccfaa%3D%22%23%22%3E%0A%20%20%20%20%3Cinput%20%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%2F%3E%0A%20%20%20%20%3Cinput%20%20type%3D%22submit%22%20value%3D%22submit%22%2F%3E%0A%3C%2Fform%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL">
</form>

```

**Comment by raisedadead** [comment]
Duplicate of #5630 

Please follow [bug report guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug). You can also ask for help at [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by jackysfbay** [comment]
I did read the bug report guidelines, and clean the crashes. At the same time , I switched different browsers, I run the codes on my IDE, it works.(code), but freecodeCamp IDE cannot submit the codes, no response the Run test button.!!!!

**Comment by sludge256** [comment]
There is no button element in your code.

**Comment by jackysfbay** [comment]
Because I cleared the code, and try to submit the code. However, although the codes is clean, the run test button still didn't work.

**Comment by sludge256** [comment]
So are you attempting to use the run test button(submit) with or without a button element in your code?

**Comment by jackysfbay** [comment]
whatever I submit the my new codes or the clean codes. If I submit the clean codes, the console will give me a alert message. But I clicked the run test button many times, it has no response.

**Comment by sludge256** [comment]
Can you post your "new" code?

**Comment by jackysfbay** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<style>
    h2{
        color: blue;
    }
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball
    run catnip eat the grass sniff.</p>

<a href="http://freecatphotoapp.com">cat photos</a>

<ol>
    <li>Java</li>
    <li>Ruby</li>
    <li>CSS</li>
</ol>
<form action="/submit-cat-photo">
    <input  type="text" placeholder="cat photo URL"/>
    <input  type="submit" value="submit"/>
</form>
</body>
</html>

**Comment by jackysfbay** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
    .red-text {
        color: red;
    }

    h2 {
        font-family: Lobster, Monospace;
    }

    p {
        font-size: 16px;
        font-family: Monospace;
    }

    .thick-green-border {
        border-color: green;
        border-width: 10px;
        border-style: solid;
        border-radius: 50%;
    }

    .smaller-image {
        width: 100px;
    }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
    <input  type="text" placeholder="cat photo URL"/>
    <input  type="submit" value="submit"/>
</form>
</body>
</html>

**Comment by jackysfbay** [comment]
it is from Waypoint: Add a Submit Button to a Form

**Comment by jackysfbay** [comment]
<code>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
    .red-text {
        color: red;
    }

    h2 {
        font-family: Lobster, Monospace;
    }

    p {
        font-size: 16px;
        font-family: Monospace;
    }

    .thick-green-border {
        border-color: green;
        border-width: 10px;
        border-style: solid;
        border-radius: 50%;
    }

    .smaller-image {
        width: 100px;
    }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
    <input  type="text" placeholder="cat photo URL"/>
    <input  type="submit" value="submit"/>
</form>
<code></code>
</body>
</html>
</code>

**Comment by BplaysD** [comment]
Llkigtyutttiyyyft

On Thursday, 31 December 2015, Jacky Cao <notifications@github.com> wrote:

> Because I cleared the code, and try to submit the code. However, although
> the codes is clean, the run test button still didn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5629#issuecomment-168158608>
> .
>


-- 
Sent from Gmail Mobile

**Comment by jackysfbay** [comment]
<textarea>
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
    .red-text {
        color: red;
    }

    h2 {
        font-family: Lobster, Monospace;
    }

    p {
        font-size: 16px;
        font-family: Monospace;
    }

    .thick-green-border {
        border-color: green;
        border-width: 10px;
        border-style: solid;
        border-radius: 50%;
    }

    .smaller-image {
        width: 100px;
    }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
    <input  type="text" placeholder="cat photo URL"/>
    <input  type="submit" value="submit"/>
</form>
<code></code>
</body>
</html>

</textarea>

**Comment by sludge256** [comment]
Use a button element instead of an input element.
The run test button does in fact work but you are not passing the test(s) since it expects a `button` element.

**Comment by jackysfbay** [comment]
oh.... my mistakes,,,,,thank you very much !

**Comment by sludge256** [comment]
Don't forget to close the duplicate https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5630

**Comment by BplaysD** [comment]
Hi FreeCodeCamp/FreeCod,

I&#39;d like to include you in my network to share updates and stay in touch.

- Dean

Confirm that you know Dean: https://www.linkedin.com/e/v2?e=0-imn0r9xp-lq&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=DOtNh91y&invitationId=6122996591365283841








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-imn0r9xp-lq&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHFxVyfkFwOjwAAAVPlBA6MbdVBjjH5DR87hr2lS5wUNvIEtD0Qh-b01b2NqrD_5VBvgNwA_w21OBgkhuyCPXJzu-pD6BGQRu89LGhOEW916mKBq0pIPn_D9LvSJ5qDL0rV6rAlVFwnSnLd67_FUfLvQHwPEZN-qGw29618j8ikryIVxybjCX2I_cnRFJp6at9k&eid=0-imn0r9xp-lq


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-imn0r9xp-lq&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
