### ISSUE TITLE
Waypoint: Decrement a Number with Javascript

### ISSUE THREAD

**Issue by HoBi** [FreeCodeCamp/FreeCodeCamp#5632]
Challenge [Waypoint: Decrement a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-decrement-a-number-with-javascript#?solution=var%20myVar%20%3D%2011%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar--%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 11;

// Only change code below this line
myVar = myVar--;
```

This code returns `11`, but in test is number `10`, for which works `myVar = --myVar;`, but that does not pass "Use the -- operator on myVar".

**Comment by Mr-Kumar-Abhishek** [comment]
:+1:  
This test expect to post fix decrement operator , however having `myVar = myVar` does confused me too. Either keep it and include feature for prefix decrement operator or remove the line ``myVar = myVar` after comment all together.

The solution is to remove the second line `myVar =myVar` and just put `myVar--`.

While assigning with postfix decrement , the decrement value is not assigned instead the original value is assigned. However when assigning with prefix decrement operator the decrement operator is applied.

**Comment by HoBi** [comment]
This given example `myVar = --myVar;` is not so obvious, but for example `this Var = --myVar;` is common practise and this lesson should probably teach and also allow both ways.

**Comment by Mr-Kumar-Abhishek** [comment]
I agree these two tests should teach both postfix decrement/increment  operators and prefix decrement/increment operators or at least allow use of both . Although, I am not sure what is the importance of variables names here. Having different or having same , they both makes sense but keeping `myVar = myVar` when solution is just `myVar--` or `myVar++` doesn't makes sense to me.

**Comment by ltegman** [comment]
prefix decrement is very uncommon in javascript and this waypoint is specifically teaching postfix. Postfix will pass as long as you're not doing assignment since postfix negates the need for assignment.

**Comment by SaintPeter** [comment]
This is why this comment was added to the description:
![image](https://cloud.githubusercontent.com/assets/553494/12068552/5f288b4a-afc5-11e5-9ea6-d924ccd9487d.png)

**Comment by Mr-Kumar-Abhishek** [comment]
@SaintPeter thank you for the clarification , however @ltegman it doesn't hold any water whether what is commonly used JavaScript in choosing between prefix and postfix increment/decrement operators, they are included in the language for a reason.
