### ISSUE TITLE
js beta, music player project, step 43 asks for falsey condition but accepts null check

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#56335]
### Describe the Issue

in step 43 of the js beta music player project, we are asked to:
>add an if to check if userData?.currentSong is falsey.

But if you type an if like below, it is accepted even though that's not a falsey check?
```
if (userData?.currentSong === null) {
  playSong(userData?.songs[0].id)
}
```

I also looked at the code in step 44 and the condition doesn't seem to be a general falsey check there either, so maybe this step 43's instructions should be updated to say "add an if to check if userData?.currentSong is null"?

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-43

### Your code

```
if (userData?.currentSong === null) {
  playSong(userData?.songs[0].id)
}
```

### Expected behavior

a rewrite of the instructions is needed to be clearer about not requiring a falsey check but just a check against null.

### System

N/A

**Comment by ilenia-magoni** [comment]
iirc the tests were updated to be more accepting of conditions that would still work for the project but weren't what the user stories ask

**Comment by hbar1st** [comment]
Hmm. I am not sure this issue fits the behaviour? It is really the description that is too restrictive in this case and doesn’t match the test?

**Comment by hbar1st** [comment]
It looks like when someone tried to fix the tests to allow the falsey answer they also changed the description in reverse to make it more restrictive that it was?

**Comment by lasjorg** [comment]
Allowing any falsy value, through type coercion, implicitly allows all falsy values. However, we are not expecting the value to be an empty string or `undefined`, so allowing explicit falsy value checks that isn't `null` wouldn't be correct.

`null` is the explicit falsy value used by the code to denote "not set" or "unset", so allowing an explicit check for that value is fine. But I don't think the test should allow for an explicit `undefined` value check. I don't believe there is a code path where the property being `undefined` means the same as it being `null`. If it is `undefined`, I would assume something went wrong. Not that I thoroughly looked at the code.

So if anything, we should update the test to not allow an explicit `undefined` check but keep the `null` check.

**Comment by hbar1st** [comment]
My confusion remains with the description. Someone sees this step’s description and posts on the forum with their code only checking for null, my first instinct is to say: hey, the instructions said check for a falsey not check for null. (This actually happened by the way which is why I opened this). Then I found out that actually the test didn’t care that the person wrote code that only checked for null. My point is this; if the test wants a null check then pls make the step ask for a null check and not a falsey check.

**Comment by lasjorg** [comment]
I assume we wanted to allow a falsy check instead of only a literal `null` check, and in doing so we also change the written requirements to say a falsy check.

I don't have an issue with removing the literal `null` and `undefined` part of the regex test.

But the requirement doesn't state how the falsy check should be preformed, that is, it doesn't say it has to be an implicit coercion. So we might want to allow using `Boolean()` as well.

**Comment by naomi-lgbt** [comment]
I'm in the opposite camp (lasjorg's original camp?). There are other conditional points in the code flow that use an explicit `null` check, and the property is initialised to `null` in the code.

It does not make sense to then allow a falsy condition in the step. We should revert the tests to require an explicit `null` comparison.

**Comment by lasjorg** [comment]
I'm inclined to agree, but it is more an opinion.

Strictly speaking, `null` is used as an intentional value and other falsy values are not expected. Could you check for a `null` by using implicit coercion? Sure. But in doing so, you are allowing potentially unexpected values to pass the check.

**Comment by lasjorg** [comment]
I will give my vote to revert the change back to a strict `null` check.

A falsy check seems too broad and allows for unexpected values.

**Comment by naomi-lgbt** [comment]
I'm going to open this up for contribution. A PR which resolves this issue will update the instructions and tests for the linked step to require an explicit null check.

**Comment by ilenia-magoni** [comment]
@bwithnomi We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
