### ISSUE TITLE
The correct output is shown in the console but code fails.

### ISSUE THREAD

**Issue by cybot1711** [FreeCodeCamp/FreeCodeCamp#5633]
Challenge [Waypoint: Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/waypoint-return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(%20a%20%3C%200%20%7C%7C%20b%20%3C%200)%20%7B%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  if ( a < 0 || b < 0) {
    return "undefined";
  }
  
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

```

**Comment by TheGreenHabi** [comment]
Hi. Your code has flaw.
```"undefined"``` should be ```undefined```. Without quotes.
Here is more information about this property:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/undefined

**Comment by cybot1711** [comment]
Thanks I thought it musr return a string

**Comment by ltegman** [comment]
Thanks for your help @TheGreenHabi.

Thanks and happy coding!

**Comment by trigal2012** [comment]
I had the same issue, it's not clear that the code should NOT return a string.
