### ISSUE TITLE
Bug in return statement text in 'Else If' waypoint.

### ISSUE THREAD

**Issue by smrajagopal** [FreeCodeCamp/FreeCodeCamp#5634]
Return statement Issue: 
JS Line 3: Return statement text should be "Greater than 10" instead of "10 or bigger"

Challenge Link : http://www.freecodecamp.com/challenges/waypoint-introducing-else-if-statements

Browser Version : v47.0.2526.106 (64-bit)
Operating System Version : Mac OS X 10.11.2

Steps to reproduce: 
1. Go to the above challenge link and check the text.
2. (Optional)Read/Run the below test case in the above waypoint challenge page
- myTest(10) should return "Between 5 and 10"

Screenshot 1: 
![image](https://cloud.githubusercontent.com/assets/1938039/12063758/19fa0a98-afda-11e5-8484-4d2c578336d1.png)

Screenshot 2:
![image](https://cloud.githubusercontent.com/assets/1938039/12063761/2dc68b64-afda-11e5-8c42-3fad1ea94755.png)

**Comment by Mr-Kumar-Abhishek** [comment]
:+1: 

yes "10 or bigger" means `val >= 10`

**Comment by smrajagopal** [comment]
This same waypoint has some more minor bugs associated with it (in the test cases). 
They are :
1. Following is the test case print message
  - myTest(5) should return "Smaller than 5"
but should instead print the message as
  - myTest(5) should return "Between 5 and 10"
2. Following is the test case
  - myTest(4) should return "Smaller than 5"
but should instead be the following, because 0 is what is passed to function checked in developer console.
  - myTest(0) should return "Smaller than 5"

To save PR Reviewer time, I am merging this very minor issues in one and creating one commit to fix this.
