### ISSUE TITLE
Waypoint: Make Images Mobile Responsive

### ISSUE THREAD

**Issue by pawan-rgcer** [FreeCodeCamp/FreeCodeCamp#5635]
Even after adding desired img tag with correct src it is not showing running cat images. I am stuck here..

**Comment by sludge256** [comment]
Can we see your code?

**Comment by smrajagopal** [comment]
@pawan-rgcer :
Do you know that you can actually get instant help (mostly) for such issues in [FreeCodeCamp's Help Chatroom](https://gitter.im/FreeCodeCamp/Help)?

Also you may read this before posting an issue:
[Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by ltegman** [comment]
Closing as there is no code and repro steps. Please checkout the help chat room and refile this issue with more information if it is indeed a bug. Thanks and happy coding!
