### ISSUE TITLE
Learn Function Basics - Learn Function Basics Lesson C

### ISSUE THREAD

**Issue by New-Dev24** [freeCodeCamp/freeCodeCamp#56350]
### Describe the Issue

The challenge or lesson asks the user to provide answer by looking at or by executing the sample code provided in front of him/her but the sample doesn't provide any output in console.

### Affected Page

https://www.freecodecamp.org/learn/the-odin-project/top-learn-function-basics/learn-function-basics-lesson-c

### Your code

```
The answer is correct but the example code doesn’t produce any output at the first place. A user can only see output after calling the function.

let x = 10;

function myFunction() {
  let x = 20;
  console.log(x);
}
This piece of code doesn’t produce any output. But

let x = 10;

function myFunction() {
  let x = 20;
  console.log(x);
}

myFunction();
This one does.


```

### Expected behavior

When a user try that piece of code he/she should see an output in console.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by dareckolo** [comment]
Can I work on this and just add the myFunction(); at the end?

**Comment by ilenia-magoni** [comment]
hi @dareckolo

Thanks for your interest in contributing.

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by ilenia-magoni** [comment]
Ok, yes, it makes sense to add a function call in the code snippet. I'm opening this up for contributors to work on.

This is the piece of code that needs to be changed:

https://github.com/freeCodeCamp/freeCodeCamp/blob/03fa03c66ec7301fbc5d10e0009d2daa0e59ca4e/curriculum/challenges/english/16-the-odin-project/top-learn-function-basics/learn-function-basics-lesson-c.md#L42-L49

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by rs0125** [comment]
Hi @ilenia-magoni 

I'd like to work on this issue and submit a pull request to address it. This will be my first issue.
I just wanted to know if the video-solution is correct on that page. Just seems to say '2'. 
Is that intentional or is it missing a zero.

Either way I'll add the function call in the code snippet and send a merge req right away.
Thanks!

**Comment by ilenia-magoni** [comment]
Hey @rs0125. We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by myselfsatyam** [comment]
```js 
 let x = 10; 
  
 function myFunction() { 
   let x = 20; 
   console.log(x); 
 } 
 ```
