### ISSUE TITLE
Remove TODO comment left in Python Equation Solver project

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#56367]
### Describe the Issue

There was a TODO comment left in the hints for the Equation Solver project

<img width="759" alt="Screenshot 2024-09-30 at 11 11 37 AM" src="https://github.com/user-attachments/assets/42099e86-0d7d-45dd-ad5f-eafe5b0028d4">

The hint should be updated to the following:

```md
You should modify the pattern passed as the first argument to the `re.sub()` call using a negative lookbehind.
```

### Affected Page

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-interfaces-by-building-an-equation-solver/664ef4623946e65e18d59764.md

### Your code

see explanation above

### Expected behavior

see explanation above

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

## Files that need to be changed
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/07-scientific-computing-with-python/learn-interfaces-by-building-an-equation-solver/664ef4623946e65e18d59764.md

Happy coding

**Comment by nrhitik** [comment]
i would like to work on this issue, could you please assign this issue to me.

**Comment by developer-mohitsoni** [comment]
can you please add label to this issue as "Hacktoberfest"

**Comment by srirangamuc** [comment]
Hi, I'd like to contribute to this issue! I'll update the hint for the re.sub() call to use a negative lookbehind and submit a PR shortly. Thanks for the opportunity!

**Comment by codexkunal** [comment]
Hello! I'm interested in resolving this issue by refining the __str__ method within the Equation class. My plan is to adjust the re.sub() function to incorporate a negative lookbehind, ensuring that the digit '1' is only replaced when it isn't preceded by another digit. This approach will prevent unintended substitutions in multi-digit numbers. I'll prepare a pull request with these modifications soon. Thank you for considering my contribution!

**Comment by parthasdey2304** [comment]
I would like to contribute to this issue. I have contributed to hacktoberfest last year as well. Please assign it to me.

**Comment by ilenia-magoni** [comment]
@developer-mohitsoni the repo has the label, the issue label don't matter.

@developer-mohitsoni @srirangamuc @codexkunal @parthasdey2304 

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by jdwilkin4** [comment]
@codexkunal 

>  I'm interested in resolving this issue by refining the str method within the Equation class.

Please do not make any changes outside what is outlined in the issue.
The scope of the issue to only update the hint text to remove the TODO comment. Any other changes will not be accepted in a PR

Thank you 👍

**Comment by codexkunal** [comment]
@jdwilkin4 Thank you for the clarification! I'll ensure the changes in my PR are limited to updating the hint text and removing the TODO comment, as specified in the issue. I appreciate the guidance!

**Comment by developer-mohitsoni** [comment]
@ilenia-magoni Thanks for the clarification Mam
