### ISSUE TITLE
Ambiguity in Instructions for Using Template Literals and Interpolation in User Card Creation Task

### ISSUE THREAD

**Issue by darkpsinight** [freeCodeCamp/freeCodeCamp#56386]
### Describe the Issue

I suggest changing the phrase 'template interpolation' to 'template literals,' because [These](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) are correctly referred to as template literals, which support string interpolation.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-fetch-and-promises-by-building-an-fcc-authors-page/step-12

### Your code

```

-

```

### Expected behavior

-

### Screenshots

![image](https://github.com/user-attachments/assets/74b5cb8f-1d92-4fa4-b32e-e5665caa2456)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment]
it should be "string interpolation". Template literals are already mentioned a few words before, it would be extremely redundant.

I'm opening this issue for first timers to make the change "template interpolation" -> "string interpolation".

This change needs to be done twice in this file:
https://github.com/freeCodeCamp/freeCodeCamp/blob/03fa03c66ec7301fbc5d10e0009d2daa0e59ca4e/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da6dcb6e4c9463d54c75b.md#L10
https://github.com/freeCodeCamp/freeCodeCamp/blob/03fa03c66ec7301fbc5d10e0009d2daa0e59ca4e/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da6dcb6e4c9463d54c75b.md#L23-L24

Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.

**Comment by ShivamSingh22** [comment]
Hi, I guess @developer-mohitsoni has raised his PR with the needed change. I haven't contributed before to any open source project. I thought this was an easy one to do to get started. Please tell any easy code or non-code contributions to be made. Happy to help.

**Comment by Nishant-k-sagar** [comment]
I am able to make the required change and happy to start open source contribution with hacktoberfest @developer-mohitsoni .
/assign

**Comment by ilenia-magoni** [comment]
@Shi974 @Nishant-k-sagar 
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by Akchhya** [comment]
This pull request resolves the issue of incorrect terminology in the JavaScript curriculum where "template interpolation" was used. The correct term is "string interpolation," as template literals support string interpolation.

I have made the following changes:

Replaced "template interpolation" with "string interpolation" in the two locations within the file.  Fix :#56434

**Comment by developer-mohitsoni** [comment]
After reading the contributing guidelines, I now understand the mistake I made in my PR.
