### ISSUE TITLE
Data Analysis Medical Data Visualizer - duplicated instructions

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#56413]
### Describe the Issue

There are two sets of instructions here "Tasks" and "Instructions". I think the numbered instructions were added recently to make the steps more clear? There is a task that is not included in the numbered instructions:

"diastolic pressure is higher than systolic (Keep the correct data with (df['ap_lo'] <= df['ap_hi']))"

This does not appear in the numbered instructions and I think a few campers have missed it for this reason:

[https://forum.freecodecamp.org/t/data-analysis-with-python-projects-medical-data-visualizer/713956/](url)
[https://forum.freecodecamp.org/t/data-analysis-with-python-projects-medical-data-visualizer/714175](url)

That said, having both is a bit redundant and makes the project instructions very long.

This part of the Tasks:
```
Normalize the data by making 0 always good and 1 always bad. If the value of cholesterol or gluc is 1, make the value 0. If the value is more than 1, make the value 1.
```
Is repeated verbatim later in the Instructions:
```
3. Normalize data by making 0 always good and 1 always bad. If the value of cholesterol or gluc is 1, set the value to 0. If the value is more than 1, set the value to 1.
```

### Affected Page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer

### Your code

```
NA

```

### Expected behavior

NA

### Screenshots

NA

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by prachidoddi** [comment]
Data Analysis Medical Data Visualizer #56413 ill do this

**Comment by ilenia-magoni** [comment]
@prachidoddi this issue is not open for contribution, only issues with the "help wanted" or "first timers only" label are open for contribution

**Comment by naomi-lgbt** [comment]
This issue is now opened for contribution.

A pull request which resolves this issue should:
- Remove the `Tasks` section from the project instructions.
- Add the missing `` diastolic pressure is higher than systolic (Keep the correct data with `(df['ap_lo'] <= df['ap_hi']))` `` as new first list item under instruction number 11.

**Comment by royjohnlee** [comment]
Remove `Task` and all it's content or just remove the title?

**Comment by naomi-lgbt** [comment]
Remove task and all of its content.

**Comment by gikf** [comment]
Completed with #56508
