### ISSUE TITLE
Reset does not clear localstorage item

### ISSUE THREAD

**Issue by DDaems** [FreeCodeCamp/FreeCodeCamp#5643]
Hitting the reset button does not clear the localstorage.
When i hit f5 all my oldcode is back, i find this really annoying for offline debugging.

**Comment by ltegman** [comment]
You can get around this by pressing any key while inside the editor window after resetting the code, but it would be nice if the reset button did this for you, even if it just did it by faking a keypress event.

**Comment by BerkeleyTrue** [comment]
This should be the default behavior. Seems to be broken. The code that does this is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework/end.js#L74)

**Comment by DDaems** [comment]
I can take a look at it tommorow. First we are going to celebtrate nrwyears eve
