### ISSUE TITLE
Details that are making errors in some codes

### ISSUE THREAD

**Issue by iallfree** [FreeCodeCamp/FreeCodeCamp#5644]
Challenge [Waypoint: Manipulate Arrays With pop](http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop#?solution=var%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0Avar%20removedFromOurArray%20%3D%20ourArray.pop()%3B%20%2F%2F%20removedFromOurArray%20now%20equals%203%2C%20and%20ourArray%20now%20equals%20%5B1%2C2%5D%0A%0Avar%20myArray%20%3D%20%5B%22John%22%2C%2023%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20removedFromMyArray%20%3D%20myArray.pop()%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(y%2C%20z)%7Breturn%20%27myArray%20%3D%20%27%20%2B%20JSON.stringify(y)%20%2B%20%27%20%26%20removedFromMyArray%20%3D%20%27%20%2B%20JSON.stringify(z)%3B%7D)(myArray%2C%20removedFromMyArray)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
![screenshot 10](https://cloud.githubusercontent.com/assets/16330271/12064736/62615556-af90-11e5-8424-3ac9e836896b.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/16330271/12064737/63e1e2ce-af90-11e5-94e4-3b4777703137.png)

OK... there are two issues here... one the example code is not written correctly... in the one that was loaded into the message from the site you will see that there is a bracket missing from JOHN... 

In the second photo that I uploaded - this is what happened when I did a refresh of the screen.. the bottom json  code is now missing. 

This happened with another waypoint. After comparing with another code, I noticed it wasn't exactly my code that was giving me trouble. It was the additional code that did not belong in the code ... I was working on .push and .pop was in the code example.(That I wasn't suppose to change according the // comments..  I took the .pop codes out and also fixed the bracket  at the end of John array(again I wasn't suppose to change in the example..  but just add .dog 3.. etc..  ..Well after I changed these errors, it passed and now I am here again. Just after the other problem. I am catching this problem.  It may not be a bug- but the lack of detail on the author's end. 
And someone should notice. 

Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = [1,2,3];

var removedFromOurArray = ourArray.pop(); // removedFromOurArray now equals 3, and ourArray now equals [1,2]

var myArray = ["John", 23, ["cat", 2]];

// Only change code below this line.

var removedFromMyArray = myArray.pop();

// Only change code above this line.

(function(y, z){return 'myArray = ' + JSON.stringify(y) + ' & removedFromMyArray = ' + JSON.stringify(z);})(myArray, removedFromMyArray);

```

**Comment by iallfree** [comment]
it was a copy paste issue.. because it continues....

**Comment by SaintPeter** [comment]
The definition of this challenge changed while you were working on it.  Resetting the code was probably the right thing to do.  I presume that doing so fixed the issue?

**Comment by iallfree** [comment]
It didn't change sorry..
