### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by spybat2010** [FreeCodeCamp/FreeCodeCamp#5645]
Challenge [Waypoint: Appending Variables to Strings](http://www.freecodecamp.com/challenges/waypoint-appending-variables-to-strings#?solution=%2F%2F%20Example%0Avar%20anAdjective%20%3D%20%22awesome!%22%3B%0Avar%20ourStr%20%3D%20%22Free%20Code%20Camp%20is%20%22%3B%0AourStr%20%2B%3D%20anAdjective%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20someAdjectiv%3D%20%22awesome!%22%3B%0Avar%20myStr%20%3D%20%22Learning%20to%20code%20is%20%22%3B%0AmyStr%20%2B%3D%20someAdjectiv%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// Only change code below this line
var someAdjectiv= "awesome!";
var myStr = "Learning to code is ";
myStr += someAdjectiv;

```

**Comment by ltegman** [comment]
You misspelled the variable name. It should be `someAdjective`.

Thanks and happy coding!
