### ISSUE TITLE
Add close or a exit button on a searching window

### ISSUE THREAD

**Issue by Nayanj041** [freeCodeCamp/freeCodeCamp#56464]
### Is your feature request related to a problem? Please describe.

when i clicked on a searching tab but when i want to go back i don't fine any close and exit option on a tab

### Describe the solution you'd like

simply add (X) to close that search window

### Describe alternatives you've considered

there is an alternative to make it attractive by adding backward arrow (<-)

### Additional context

![Image](https://github.com/user-attachments/assets/219bb8ba-a4ea-4dad-9b40-2199acf508ac)

**Comment by gikf** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue https://github.com/freeCodeCamp/contribute/issues/377, so we are closing it as a duplicate.

If you think we're wrong in closing this issue, please request for it to be reopened and add further clarification. Thank you and happy coding.
