### ISSUE TITLE
Completed Waypoints should be noted as completed

### ISSUE THREAD

**Issue by duffn** [FreeCodeCamp/FreeCodeCamp#5646]
Since you are always taken to the next Waypoint in the sequence, when going back to complete new Waypoints in a section it's difficult to tell if you are on a new Waypoint or a Waypoint that you've already completed. 

Once I've completed Waypoint 30, I'm taken to 31 which I've already completed. It is not clear, however, when in Waypoint 31 that it has already been completed.
![screen shot 2015-12-31 at 6 54 22 am](https://cloud.githubusercontent.com/assets/3457341/12064907/7010027e-af8b-11e5-916d-3f2609d5ccec.png)

Completed Waypoints should somehow be noted as such while in the Waypoint.

**Comment by hellawindy** [comment]
I think it should be shown in the waypoint if it's completed or not.

**Comment by wakqasahmed** [comment]
@duffn @hellawindy: I feel you both are right and both suggestions are mutually exclusive.

duffn's pointed issue seems to me a bug, while hellawindy's is an additional feature.

Admin, please assign it to me.

**Comment by SaintPeter** [comment]
@wakqasahmed I can't assign it to you, but you're welcome to submit a PR.  How do you propose to fix it?

**Comment by wakqasahmed** [comment]
@SaintPeter have added status into each waypoint, if approved I will add them in bonfire as well.

Regarding the bug, i think it requires an additional function to get next uncompleted challenge and then attach its challengeId with the anchor tag of popup.

Let me know if you agree with the solution and I will work on it.

**Comment by SaintPeter** [comment]
I'm amenable to your proposed solution, so long as it doesn't add too much overhead to the page construction.  A single scan through the user challenge data should suffice to generate a list of "next incomplete challenge" ids.

I, too, have been annoyed that this does not work the way I expect.

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5753 is merged.
