### ISSUE TITLE
Learn Regex by Building Spam filter - Step 24 - Passing with incorrect regex

### ISSUE THREAD

**Issue by laserlemon23** [freeCodeCamp/freeCodeCamp#56471]
### Describe the Issue

Small error with accepted answers on this step. See screenshot. I typed in three [e3] characters in "free" and none in money, and it was accepted.

Lesson is trying to set up a spam filter that will flag the text "fr33 mon3y" or similar variations.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-regular-expressions-by-building-a-spam-filter/step-24

### Your code

```

const freeRegex = /fr[e3]|[e3]|[e3] money/i;
// this is incorrect but accepted

```

### Expected behavior

Although my answer does indeed have three instances of [e3], the correct (and only) solution for this step should be:

```

const freeRegex = /fr[e3][e3] mon[e3]y/i;
// this is correct, and also accepted

```

### Screenshots

![Image](https://github.com/user-attachments/assets/b7ac58cb-7062-4da4-8ad7-0f067187543e)

### System

User Agent is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

[a very old iMac 😄 ]

### Additional context

I first made a forum post about it here: [https://forum.freecodecamp.org/t/learn-regular-expressions-by-building-a-spam-filter-step-24/711716](url)

**Comment by gikf** [comment]
Looks like tests are currently only checking if the `freeRegex` matches the string, but not what is matched. The `/fr[e3]|[e3]|[e3] money/i` due to alternatives (`|`) can match as little as single character from `e` or `3`.

**Comment by taiwo2** [comment]
I would like to work on this

**Comment by ilenia-magoni** [comment]
hey @taiwo, thank you for your interest in contributing

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by taiwo2** [comment]
@ilenia-magoni Thanks for the guidance

**Comment by a2937** [comment]
> Looks like tests are currently only checking if the `freeRegex` matches the string, but not what is matched. The `/fr[e3]|[e3]|[e3] money/i` due to alternatives (`|`) can match as little as single character from `e` or `3`.

I had a potentially great idea to how to do a full match. But it would involve not using `assert.match` and instead comparing the first index of the regex matches to the original string. I know we prefer specific ChaiJS methods, but it seems like a reasonable approach.

**Comment by ilenia-magoni** [comment]
@a2937 If the way of checking doesn't have a specific assertion method, use a different one, maybe `assert.isTrue` if you expect a boolean

**Comment by Atikrg** [comment]
const freeRegex = /fr[e3]|[e3]|[e3] money/i;
*I think. The following is getting accepted because | symbol act as an logical OR operator. in freeRegex*
