### ISSUE TITLE
Cafe menu: Step 40 - whitespace clarification

### ISSUE THREAD

**Issue by cayu007** [freeCodeCamp/freeCodeCamp#56474]
Sorry for my English. I’ve been going through the course, and the first part on HTML seemed fine for a beginner. However, in the second part, which covers CSS, there are things I don’t quite understand, especially the part where HTML spaces are removed to explain how ‘display’ works. Personally, I think this could lead to confusion.

for exemple, "Step 40Passed
That worked, but there is still a little space on the right of the price.

You could keep trying various percentages for the widths. Instead, use the back space key on your keyboard to move the p element with the class price next to the p element with the class flavor so that they are on the same line in the editor. Make sure there is no space between the two elements." This explanation can lead to bad practices because, in HTML, manually removing spaces is not the correct way to align elements. Although it might seem like removing the spaces between the `<p>` elements fixes the visual issue, this is not an appropriate solution. Whitespace should not be manipulated to achieve the desired layout. Instead, CSS properties such as display, margin, or padding should be used to properly and flexibly control the spacing and layout of elements. Removing spaces in the HTML code can lead to readability and maintenance issues in the long run, and it is not considered a good practice.

Step 40: https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-40

**Comment by ShoomanKhatri** [comment]
Can  you show the preview, and assign it to me?

**Comment by sameer6699** [comment]
I am working on this issue

**Comment by gikf** [comment]
Hi @ShoomanKhatri, @sameer6699,

This issue has not been triaged yet, and a solution has not been agreed upon.

Issues labelled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by jumpingoat** [comment]
@gikf I guess the solution could be to incorporate both ways. Just changin the CSS width property for price class to 48% seems to solve the problem, however for the beginner it isn't intuitive, so maybe the solution is to show both methods and explain good practices.

**Comment by cayu007** [comment]
If I were you, I would use and explain 'display: flex'.

**Comment by cayu007** [comment]
> [@gikf](https://github.com/gikf) I guess the solution could be to incorporate both ways. Just changin the CSS width property for price class to 48% seems to solve the problem, however for the beginner it isn't intuitive, so maybe the solution is to show both methods and explain good practices.

In my opinion, that is not correct. You just need to use 'display: flex' and its options to do it properly. If you do it by eye using percentages, you don't have real control. Besides, that's what the 'display: flex' property is for. It's a very important and widely used property.

**Comment by jumpingoat** [comment]
> > [@gikf](https://github.com/gikf) 
> In my opinion, that is not correct. You just need to use 'display: flex' and its options to do it properly. If you do it by eye using percentages, you don't have real control. Besides, that's what the 'display: flex' property is for. It's a very important and widely used property.

Yeah, the thing is, we're talking about first CSS learning experience and Flexbox is an intermediate theme and it's always been. Getting it too early wouldn't be, imho, wise at all. Getting over this part of the curriculum isn't supposed to be the end of the learning curve. It's like with the learning process at school. First you learn things that maybe aren't always right, but their purpose is a bit different, usually they help you to get the knowledge step by step. E.g. in karate you're supposed to learn big , static moves before you'll learn how to shorten them and use your whole body mechanics.

**Comment by EzMav3ick** [comment]
@jumpingoat  absolutely spot on grid and flexbox are intermediate themes as well as animations 
so its wise to move in basic css direction where he learns  basic commands and progress towards animations -> flex ->grid -> responsive design

**Comment by iamabhiCH** [comment]
I am currently looking into this issue, could you please assign it to me? @gikf

**Comment by ilenia-magoni** [comment]
@iamabhiCH this issue is not open for contributions

**Comment by lasjorg** [comment]
There still isn't really any actionable suggestion given here.

Step 39 explains why the new line is creating an extra space. We could update the description to specifically include spaces as well. So it is explained that both a new line or a space will create a space on the page between the elements.
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-39

With that explained, why removing the space in step 40 does what it does should be clear. Or, at least, it was explained. We can't really give an in-depth explanation of how inline/inline-block elements works with whitespace in a single challenge step.

**Comment by Supravisor** [comment]
To avoid causing confusion for Campers, mention there are several ways to approach the spacing and alignment of the text and price.  Over several steps the Camper will test and implement code that achieves the desired layout shown in the preview in step 1.

**Comment by naomi-lgbt** [comment]
Opening this up for contribution - a PR which resolves this issue should update the instructions for Step 39 to read:

```md
Well that did not work. Styling the `p` elements as `inline-block` and placing them on separate lines in the code creates an extra space to the right of the first `p` element, causing the second one to shift to the next line. White space characters can cause this issue as well.

One way to fix this is to make each `p` element's width a little less than `50%`. Change the `width` value to `49%` for each class to see what happens.
```

**Comment by Supravisor** [comment]
For step 40 of Cafe Menu the width property values are already set to `49%`

>.flavor {
  text-align: left;
  width: 49%;
}

>.price {
  text-align: right;
  width: 49%;
}

**Comment by naomi-lgbt** [comment]
Yes, because step 39 instructs the camper to do so.

**Comment by Supravisor** [comment]
Gotcha
