### ISSUE TITLE
Waypoint: Record Collection - wrong tests processing

### ISSUE THREAD

**Issue by ketus** [FreeCodeCamp/FreeCodeCamp#5647]
Using this function:

![image](https://cloud.githubusercontent.com/assets/9350920/12065128/39550cba-afd2-11e5-84db-ff9ad175a8d3.png)

I am getting corrrect behaviour, but tests return as if it was wrong.
ie. When i test with:
    update(1245, "tracks", "Addicted to Love");
both Chrome and built-in console shows correct output

![image](https://cloud.githubusercontent.com/assets/9350920/12065196/0a6d4e2a-afd3-11e5-9060-dbe303c56d3c.png)

but tests

![image](https://cloud.githubusercontent.com/assets/9350920/12065159/9f70b0ee-afd2-11e5-9134-b147f362e606.png)

Same with other input:

![image](https://cloud.githubusercontent.com/assets/9350920/12065176/ccfa24e6-afd2-11e5-8e08-e7b000e50777.png)

**Comment by ltegman** [comment]
I can't test your exact code without you posting text of it instead of images but it looks like you didn't follow the part of the instructions that says:

>Always return the entire collection object.

Thanks and happy coding!

**Comment by ketus** [comment]
That is exactly the case. It would be nice not to have that limitation, though. Thanks for feedback!
