### ISSUE TITLE
CSS class to style an element not working on android

### ISSUE THREAD

**Issue by JimL92** [FreeCodeCamp/FreeCodeCamp#5649]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%20%0A%20%20.red-text%20%7B%0A%20%20%20%20%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%20%20%0A%20%20%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%20%3C%2Fh2%3E%0A%20%20%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 6.0.1; Nexus 6 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  
  .red-text {
    
    color: red;
    
  }

</style>

<h2 class="red-text">CatPhotoApp </h2>
  
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by ltegman** [comment]
There are illegal whitespace characters in your css, so this won't pass no matter what platform you're on. I don't know how or why they got there, perhaps android introduced them, but if you retype it yourself from scratch it should pass.

Thanks and happy coding!
