### ISSUE TITLE
Remove jQuery from tests for  Video Compilation Page lab

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#56492]
There are a few jQuery tests here that should be removed and updated to not use jQuery.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/lab-video-compilation-page/669e81368e52b3a5c35a2dc5.md

**Comment by Ritesh2351235** [comment]
@jdwilkin4 Can you elaborate more i could see some jQuery elements should they be converted to vanilla javascript?

**Comment by jdwilkin4** [comment]
Yeah, just remove all jQuery from the testing section.

It's 2024. There is no reason to use jQuery at all. 👍

**Comment by Ritesh2351235** [comment]
Sure I'm  on it
