### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue 

### ISSUE THREAD

**Issue by rkora** [FreeCodeCamp/freecodecamp#565]
Did anyone else encounter any issue with this challenge? 
I've inserted the command <input style='text'> at the end of the my code. The input text box displayed OK on the right side. However, I have this error message: "Syntax error, unrecognized expression".

Any pointer will be appreciated.

**Comment by QuincyLarson** [comment]
We've fixed this. Thank you for your patience, and for bringing this to our attention!

**Comment by rkora** [comment]
Thank you!
