### ISSUE TITLE
[Shopping List Workshop] Missing space in function declaration

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#56500]
## Description

This is just a typo/formatting issue.

For consistency, there should be a space between `()` and `{` in function declaration:

```diff
---function getShoppingListMsg(){
+++function getShoppingListMsg() {
```

## Changes needed

Fix the issue in the following files:

- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/workshop-shopping-list/66c64ad16796c7f2419b45c5.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/workshop-shopping-list/66c72a55418cc9247b710827.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/workshop-shopping-list/66c72b0ffbc5522525768558.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/workshop-shopping-list/66c72f4d0528bd268a82107b.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/workshop-shopping-list/66c726c34ecf1e238aa9d7d5.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/workshop-shopping-list/66c730183f4020275cbf0611.md

**Comment by AbhinRustagi** [comment]
Can it be assigned to me?

**Comment by ianujvarshney** [comment]
can i work on this issue ?
