### ISSUE TITLE
Not sure what I am doing wrong with this waypoint.

### ISSUE THREAD

**Issue by juanocasio** [FreeCodeCamp/FreeCodeCamp#5653]
Challenge [Waypoint: Stand in Line](http://www.freecodecamp.com/challenges/waypoint-stand-in-line#?solution=%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0Afunction%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20var%20singleItem%3B%0A%20%20arr.push(item)%3B%0A%20%20myArr%20%3D%20arr%3B%0A%20%20singleItem%20%3D%20myArr.shift()%3B%0A%20%20%0A%20%20return%20singleItem%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0Aconsole.log(queue(myArr%2C%2010))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0Aconsole.log(myArr%5B4%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myArr = [1,2,3,4,5];

function queue(arr, item) {
  // Your code here
  var singleItem;
  arr.push(item);
  myArr = arr;
  singleItem = myArr.shift();
  
  return singleItem;  // Change this line
}

// Display Code
console.log("Before: " + JSON.stringify(myArr));
console.log(queue(myArr, 10)); // Modify this line to test
console.log("After: " + JSON.stringify(myArr));
console.log(myArr[4]);

```
I have entered the following code and it seems to be satisfying the requirements, however the thrid one is showing as not met

**Comment by ltegman** [comment]
You shouldn't be using `myArr` in your function. You should only be using `arr` and the test will pass in `myArr` as the first argument. Because you're using `myArr` inside the function it's getting modified by every call to `queue` not just calls where it is passed in.

Thanks and happy coding!

**Comment by smrajagopal** [comment]
@juanocasio : I would highly encourage you to read this
[Function Parameters in Javascript] (http://www.w3schools.com/js/js_function_parameters.asp)

From that, when function changes an object (in this case our array) property, it changes the original value. Changing `arr` inside the function is more than enough to receive the effect on `myArr`. Just shift an element in `arr`. :-)

**Comment by trueskawka** [comment]
You're shifting the first element of the array twice.
