### ISSUE TITLE
Non-bug Issue with Waypoint: Accessing Nested Arrays in JSON

### ISSUE THREAD

**Issue by swicken** [FreeCodeCamp/FreeCodeCamp#5654]
The issue with the waypoint is that the example does not really match the setup in the problem. 

The example in the Waypoint is as follows

```javascript
var ourPets = { 
  "cats": [
    "Meowzer",
    "Fluffy",
    "Kit-Cat"
  ],
  "dogs:" [
    "Spot",
    "Bowser",
    "Frankie"
  ]
};
ourPets.cats[1]; // "Fluffy"
ourPets.dogs[0]; // "Spot"
```

Where the example is formatted like this
```javascript
// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = ""; // Change this line

```

In your example you can access the object type by dot notation as it is defined outside of the object. However in the problem doing myPlants.trees.list[1]; returns 'trees' as undefined. I accomplished accessing it by going myPlants[1].list[1]; however this is not explained in the example. 

I could be doing this wrong but chat gave me the same answer.

**Comment by SaintPeter** [comment]
I would say that you have successfully understood the content of the lesson.  The examples don't always exactly match what you are asked to do . . . and that's a good thing, I think.

**Comment by AlexMogoryan** [comment]
yes SaintPeter I agree, but it should have some material to read in order to understand, otherwise it will take more time to research an object... however thank you for this experience is jest another way of learning, sometimes is heard but worth it ;)

**Comment by faintlywonky** [comment]
"Understood the content of the lesson"? The answer was only rudimentarily related to the content of the lesson. The lesson requires syntax that has not been explained properly, and the student is left to guess what the syntax might be.

Giving a student an exercise that has not been explained sufficiently and then expecting them to just keep trying different things until they hit on a solution is just frustrating, especially when there is no book or manual to consult. Googling examples does not help, either. The examples found in that way are too complex for a beginner and/or not applicable to the lesson.

**Comment by jastuccio** [comment]
This challenge is confusing to me.  I have been coding for a few years now.  I am not a js expert, but also not just starting to learning to code.  I am unable to figure out this challenge from the example provided after 15 minutes.  Clarification or a closer example to the challenge would really be appreciated.  I plan to create a gist when I figure this problem out.
