### ISSUE TITLE
Phrasing of Question

### ISSUE THREAD

**Issue by abrown820** [FreeCodeCamp/FreeCodeCamp#5655]
Challenge [Waypoint: Stand in Line](http://www.freecodecamp.com/challenges/waypoint-stand-in-line#?solution=%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0Afunction%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0Aarr.push(item)%3B%0Avar%20delFirst%20%3D%20arr.shift()%3B%0Areturn%20delFirst%3B%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0Aconsole.log(queue(%5BmyArr%5D%2C%2010))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Could this question be re-phrased such that:
"add the item onto the end of the array, then remove and return the first element of the array..."
resembles something closer to:
"add the item onto the end of the array, then remove and return the (now removed) first element of the array."

I spent ages wondering why I couldn't pass after returning the new first element of the array.

**Comment by ltegman** [comment]
This wording seems redundant and more confusing to me, but I'll leave it open for discussion.

**Comment by ShaggyTech** [comment]
I agree with @abrown820.  I was returning the first element of the new array, as that is what I understood the instructions to be at first.  It may be redundant but it will help remove some confusion.  Another alternative could be the following:
  
> "Add the item onto the end of the array, then remove the first element of the array.  **The queue function should return the element that was removed.**"

**Comment by SaintPeter** [comment]
>"Add the item onto the end of the array, then remove the first element of the array. The queue function should return the element that was removed."

:+1: 

This works for me.  Nice and clear.
