### ISSUE TITLE
confusing instructions about camelCase

### ISSUE THREAD

**Issue by smdavis0** [FreeCodeCamp/FreeCodeCamp#5656]
Challenge [Waypoint: Understanding Case Sensitivity in Variables](http://www.freecodecamp.com/challenges/waypoint-understanding-case-sensitivity-in-variables#?solution=%2F%2F%20Setup%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AStUdLyCapVaR%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

Instructions are a bit misleading regarding the answer that is expected. Not all 3 variables are to be changed to camelCase. If you're stuck, use this.

My code:
```javascript
// Setup
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Only change code below this line

StUdLyCapVaR = 10;
properCamelCase = "A String";
titleCaseOver = 9000;


```

**Comment by SaintPeter** [comment]
I have a PR pending for just this issue.
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5657

Should be live soon.
