### ISSUE TITLE
--fcc-actual-- and --fcc-expected-- not working in hints

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#56572]
`--fcc-actual--` and `--fcc-expected--` are not being replaced by their values in hints:

![Image](https://github.com/user-attachments/assets/97d9332b-dcec-4216-a070-ff4e092f80cf)

While in the console the actual and expected values are visible:

![Image](https://github.com/user-attachments/assets/b38cfb98-b4e8-45e6-8f21-ce74eb04dee3)

To reproduce, go to any challenge that uses `--fcc-actual--` and/or `--fcc-expected--`:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-74

**Comment by revolving-leslie** [comment]
Happening for me in hints for step 76: https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-css-transforms-by-building-a-penguin/step-76

**Comment by ShaunSHamilton** [comment]
@revolving-leslie Thank you for mentioning, but the fix has not been deployed yet.
