### ISSUE TITLE
Waypoint: Record Collection: tracks should have a length of 1 no passing

### ISSUE THREAD

**Issue by MiLeung** [FreeCodeCamp/FreeCodeCamp#5658]
Challenge [Waypoint: Record Collection](http://www.freecodecamp.com/challenges/waypoint-record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20update(id%2C%20prop%2C%20value)%20%7B%0A%20%20%0A%20%20if(!value)%7B%0A%20%20%20%20delete%20collection%5Bid%5D%5Bprop%5D%3B%0A%20%20%7D%0A%20%20%0A%20%20if(collection%5Bid%5D%20%26%26%20value%20%26%26%20prop%20%3D%3D%20'tracks')%7B%0A%20%20%20%20%2F%2Fcollection%5Bid%5D%5Bprop%5D%5Bcollection%5Bid%5D%5Bprop%5D.length%5D%20%3D%20value%3B%0A%20%20%20%20collection%5Bid%5D%5Bprop%5D.push(value)%3B%0A%20%20%7D%0A%20%20%0A%20%20if(collection%5Bid%5D%20%26%26%20value)%7B%0A%20%20%20%20collection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%20%7D%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0A%2F%2Fupdate(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%2F%2Fupdate(2548%2C%20%22tracks%22%2C%20%22%22)%3B%0Aupdate(1245%2C%20%22tracks%22%2C%20%22Addicted%20to%20Love%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
  
  if(!value){
    delete collection[id][prop];
  }
  
  if(collection[id] && value && prop == 'tracks'){
    //collection[id][prop][collection[id][prop].length] = value;
    collection[id][prop].push(value);
  }
  
  if(collection[id] && value){
    collection[id][prop] = value;
  }
  return collection;
}

// Alter values below to test your code
//update(5439, "artist", "ABBA");
//update(2548, "tracks", "");
update(1245, "tracks", "Addicted to Love");
```

the "After update(1245, "tracks", "Addicted to Love"), tracks should have a length of 1" does not pass when clearly there is one and only one item in the tracks property of collection['1245'].  

I suspect the issue is that JS objects automatically order the object properties, so in our case, the 1245 property is moved to the beginning of the collection object as the first property.

**Comment by ltegman** [comment]
Your code pushes correctly in the if block of: 
```javascript
if(collection[id] && value && prop == 'tracks'){
  //collection[id][prop][collection[id][prop].length] = value;
  collection[id][prop].push(value);
}
```
and then overwrites that change (which created an array with length 1) in the following block:
```javascript
if(collection[id] && value){
  collection[id][prop] = value;
}
```
Replacing the array with a string with length > 1.

Thanks and happy coding!

**Comment by MiLeung** [comment]
Thanks!

**Comment by JBreezy11** [comment]
Hey I have similar code to this yet and it's doing the same thing 

```function update(id, prop, value) {

  if(collection[id] && prop === "tracks" && value) {
    collection[id][prop] = value;
  } else if(value) {
    collection[id][prop] = value;
  } else if(!value) {
    delete collection[id][prop];
  }
  return collection;
}
```
i'm assuming it's this line ```else if(value) {
    collection[id][prop] = value; ``` that overwrites it but isn't it suppose to leave it alone since it the test is suppose to run on my first if statement only? Am I overthinking this?

**Comment by scottyzen** [comment]
This is how I got it to pass.
```
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
  if(value !== "" && prop !== "tracks"){    
    collection[id][prop] = value;
  }else if(!value){
    delete collection[id][prop];
  }else{
    collection[id][prop].push(value);
  }
  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");
```

**Comment by sami3d** [comment]
please don't laugh at my code guys (i've done it the hard way I think!!)

I am facing a wired problem though. My codes run perfectly in codepen.io and result is as expected. But when I run it in the codecamp's editor, it comes up with the over writing issue.

here is my code(ignore my too much commenting): 

`// Setup
var collection = {
  "2548": {
    "album": "Slippery When Wet",
    "artist": "Bon Jovi",
    "tracks": [
      "Let It Rock",
      "You Give Love a Bad Name"
    ]
  },
  "2468": {
    "album": "1999",
    "artist": "Prince",
    "tracks": [
      "1999",
      "Little Red Corvette"
    ]
  },
  "1245": {
    "artist": "Robert Palmer",
    "tracks": []
  },
  "5439": {
    "album": "ABBA Gold"
  }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

function updateRecords(id, prop, value) {
  
  // this is a function to check if empty arguments being passed as value
  function valueCheck(p1){
    if(value === ""){
      // do nothing 
      //console.log("There is nothing in the passed argument");
    } else {
      return p1;
    }
  }
  
  if (collection[id].hasOwnProperty(prop)) {
    //  property exists. update needed
    //  but if it is tracks then needed to be pushed to the existing tracks array
    if (prop == "tracks") {
      // console.log("property exists. it is track. an array. push there please");
      valueCheck(collection[id][prop].push(value)); // there is a array exists,
      // collection object updated with a new track name, yahoo
    } else {
      // console.log("property exists. its not a track either. simpluy Update it");
      valueCheck(collection[id][prop] = value); 
    }
  } else {
    //  property doesnt exists, needed to be added
    //  but if it is tracks then needed to create a new array with the 
    if (prop == "tracks") {
      var tracks = [value];
      valueCheck(collection[id].tracks = tracks);
      // console.log("property doesnt exist. it is a track. Create an array and add in the object.");
      // console.log(collection); // works fine
    } else {
      valueCheck(collection[id][prop] = value); // simply add the value
      // console.log("property doesnt exist. its not tracks either. add it simply");
    }
    console.log(collection);
    return collection;
  }
}

  // Alter values below to test your code
  updateRecords(5439, "artist", "ABBA");
  updateRecords(5439, "tracks", "Take a Chance on Me");
  updateRecords(2548, "artist", "");
  updateRecords(1245, "tracks", "Addicted to Love");
  updateRecords(2548, "tracks", "");`

**Comment by sami3d** [comment]
please don't laugh at my code guys (i've done it the hard way I think!!)

I am facing a wired problem though. My codes run perfectly in codepen.io and result is as expected. But when I run it in the codecamp's editor, it comes up with the over writing issue.

here is my code(ignore my overloaded comments):

```
// Setup
var collection = {
  "2548": {
    "album": "Slippery When Wet",
    "artist": "Bon Jovi",
    "tracks": [
      "Let It Rock",
      "You Give Love a Bad Name"
    ]
  },
  "2468": {
    "album": "1999",
    "artist": "Prince",
    "tracks": [
      "1999",
      "Little Red Corvette"
    ]
  },
  "1245": {
    "artist": "Robert Palmer",
    "tracks": []
  },
  "5439": {
    "album": "ABBA Gold"
  }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

function updateRecords(id, prop, value) {
  
  // this is a function to check if empty arguments being passed as value
  function valueCheck(p1){
    if(value === ""){
      // do nothing 
      //console.log("There is nothing in the passed argument");
    } else {
      return p1;
    }
  }
  
  if (collection[id].hasOwnProperty(prop)) {
    //  property exists. update needed
    //  but if it is tracks then needed to be pushed to the existing tracks array
    if (prop == "tracks") {
      // console.log("property exists. it is track. an array. push there please");
      valueCheck(collection[id][prop].push(value)); // there is a array exists,
      // collection object updated with a new track name, yahoo
    } else {
      // console.log("property exists. its not a track either. simpluy Update it");
      valueCheck(collection[id][prop] = value); 
    }
  } else {
    //  property doesnt exists, needed to be added
    //  but if it is tracks then needed to create a new array with the 
    if (prop == "tracks") {
      var tracks = [value];
      valueCheck(collection[id].tracks = tracks);
      // console.log("property doesnt exist. it is a track. Create an array and add in the object.");
      // console.log(collection); // works fine
    } else {
      valueCheck(collection[id][prop] = value); // simply add the value
      // console.log("property doesnt exist. its not tracks either. add it simply");
    }
    console.log(collection);
    return collection;
  }
}

  // Alter values below to test your code
  updateRecords(5439, "artist", "ABBA");
  updateRecords(5439, "tracks", "Take a Chance on Me");
  updateRecords(2548, "artist", "");
  updateRecords(1245, "tracks", "Addicted to Love");
  updateRecords(2548, "tracks", "");
```
