### ISSUE TITLE
Instructions encourage a double space

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#5659]
Challenge [Waypoint: Constructing Strings with Variables](http://www.freecodecamp.com/challenges/waypoint-constructing-strings-with-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName;
var myStr;



```

If you look at the challenge itself, the instructions encourage a space after "My name is " as well as a space before " and I am swell." We need only one space.

**Comment by ltegman** [comment]
There's a space on both strings because a name is being concatenated in between them and should have a space on either side of it. Closing, but let me know if I've misunderstood and I'll reopen.
