### ISSUE TITLE
Waypoint: Testing Objects for Properties typo

### ISSUE THREAD

**Issue by zoobert** [FreeCodeCamp/FreeCodeCamp#5660]
![screen shot 2015-12-31 at 11 46 12 am](https://cloud.githubusercontent.com/assets/3254367/12067755/4a8b06c4-afb4-11e5-997a-958227353d34.png)

For the tests:

> checkObject("gift") should return "kitten". 

Instead this should read 
> checkObject("pet") should return "kitten".

**Comment by smrajagopal** [comment]
@zoobert  @ltegman 

Is this fixed already or a random issue? Because, I couldn't reproduce

![image](https://cloud.githubusercontent.com/assets/1938039/12067939/05d5a7b2-b029-11e5-903e-f45cc4475c1e.png)

and script seems to fine as well as I see the code.

**Comment by SaintPeter** [comment]
This was fixed yesterday.  I see it as being correct.

**Comment by star-tux** [comment]
![capture](https://cloud.githubusercontent.com/assets/16047058/12114226/629c338a-b3a8-11e5-8320-e91bd36c8b56.JPG)

checkObj("house") return "Not Found" as you can see. Can anybody fix this, please.
