### ISSUE TITLE
Test "At least 30 characters with empty inputs" on Waypoint: Word Blanks

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#5661]
Challenge [Waypoint: Word Blanks](http://www.freecodecamp.com/challenges/waypoint-word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This test is tripping up a disproportionate amount of campers. I find it to be a tedious task without educational merit, as they've already proven the knowledge of concatenating strings by creating spaces between the word blanks. We should remove this test IMO.

**Comment by ltegman** [comment]
I completely agree. I'm about to open a PR to fix this.

**Comment by CraneWing** [comment]
What does the error even mean, "should return at least 30 characters with empty inputs". What characters? I tripped up on this one. I don't get it

**Comment by patrol7171** [comment]
I was thinking that this was configured with a typo...instead of 30 characters it probably should be just 3 characters for an empty string.  Those 3 characters would be for spaces between the words.   I actually added 30+ spaces after a period just to pass this, so I know it definitely has a bug.
