### ISSUE TITLE
Adding a second solution on a challenge breaks test-challenges

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5662]
When I add a second solution to any challenge and run `npm run test-challenges`, I get an error like this:
`plan != count`

It appears that it's either not generating tests for the second solution, or not properly counting the number of solutions \* number of tests.

**Comment by ltegman** [comment]
Since solutions are only being use to make sure changes to tests don't make unexpected changes to the solution do we need the ability to store more than one solution?

**Comment by bugron** [comment]
If we still need to be able to test more than one solution we can change `.doOnNext(t => solutions.length ? t.plan(plan) : t.end())` to `.doOnNext(t => t.end())` in `seed/test-challenges.js`, that worked for me.

**Comment by QuincyLarson** [comment]
I agree with @ltegman that the solutions are only meant to help with CI and verify that the challenges are solvable. If a use case arises where we actually need a second solution, we can revisit this.
