### ISSUE TITLE
How to differentiate between deep and shallow copies in JavaScript - Issue with UI

### ISSUE THREAD

**Issue by ankursharma12345** [freeCodeCamp/freeCodeCamp#56635]
I learn the deep and shallow copy in js and while scrolling towards the end , I found that there is an image and below that image the whole code for showing image is showing![Image](https://github.com/user-attachments/assets/55b3eb79-8bc5-494a-8f41-a42cd06e1326)
Please look at this image.

**Comment by ojeytonwilliams** [comment]
cc: @scissorsneedfoodtoo

**Comment by ilenia-magoni** [comment]
@karanvishesh No, only issues with "help wanted" label are available for contributors

**Comment by adarshdeshp** [comment]
Hi @ankursharma12345! I'd like to work on this issue. Could you please let me know if you need to assign it to me first, or if I can start working on it right away? Thank you!

**Comment by adarshdeshp** [comment]
While waiting for an assignment, I'll start working on the issue and will submit a PR soon. Please let me know if there's anything I should be aware of.

**Comment by adarshdeshp** [comment]
Hi @ankursharma12345! I noticed @ilenia-magoni mentioned that issues need a "help wanted" label for contributors. Would it be possible to add this label to the issue, or should I wait for another one to become available? Thanks for your guidance!

**Comment by ilenia-magoni** [comment]
@adarshdeshp you can't work on this issue, articles are not in a repo, I will not add the help wanted label to this issue

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @ankursharma12345. I just went in and fixed the issues with the image attributions, and a few other things.

Please let us know if you notice another other issues in this or other articles.
