### ISSUE TITLE
Allow accessing content only after sign in

### ISSUE THREAD

**Issue by sp9324** [freeCodeCamp/freeCodeCamp#56630]
### Describe the Issue

To allow a user to access content (courses) on the website only after they are signed in. This will help track their progress better. 

### Affected Page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/data-analysis-example-a

### Steps to Reproduce

1. Go to https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/data-analysis-example-a
2. This can be accessed without signing in.

### Expected behavior

I will implement a sign in popup if assigned. This pop up will allow user to access content only after they are signed in.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Hello there :wave:

freecodecamp.org is a free platform. The mission includes providing learning resources to **everyone**. So, seeing as the ToS include an age requirement of >13 to create an account, in order for people younger than 13 years of age to use the curriculum, it must be available without an account.

On top of this, some people do not have email addresses - another requirement to create an account. So, in order for these people to access the content, it has to be available to signed-out users.

As such, we will not be implementing your suggestion.
