### ISSUE TITLE
Spreadsheet project step 98 needs minor clarification

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#56663]
### Describe the Issue

In the step 98 of the js beta spreadsheet project, the instructions fail to specify the order of the numbers to be returned in the result array(s). For eg does it want the first two numbers in the order they are given in the input array? And does it want the last two numbers in the order they are given in the input array? This lack of information can lead to code like the one below being rejected without a clear explanation why.
It would be good to be explicit in the instructions about the expected order of the numbers in the final array.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-functional-programming-by-building-a-spreadsheet/step-98

### Your code

```
lasttwo : nums => [nums[nums.length-1], nums[nums.length-2]]

```

### Expected behavior

Directly state that the expected array needs to retain the same order of elements as the input array.

### System

N/A

### Additional context

Original forum post that revealed the issue 
https://forum.freecodecamp.org/t/learn-functional-programming-by-building-a-spreadsheet-step-98/716040?u=hbar1st

**Comment by naomi-lgbt** [comment]
This issue is now open for first time contributors. A PR which resolves this issue will update the step instructions to read:

```md
Add a `firsttwo` property which takes a `nums` parameter and returns the first two elements of the `nums` array in order. Then add a `lasttwo` property which returns the last two elements of the `nums` array in order.
```

**Comment by Ris345** [comment]
would love to contribute to this issue!

**Comment by ilenia-magoni** [comment]
Hey @Ris345 Thank you for your interest in contributing. We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
