### ISSUE TITLE
js beta dice game step 14 should give a more elaborate example

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#56674]
### Describe the Issue

The number of times someone on the forum has posted asking for help with step 14 of the dice game (js beta project) is not small. Many of these people have the same mistake of assuming that the checkForStraights function need only to check for consecutive numbers in the dice array. (and they are always surprised to learn that this is not the case). I don't know if this is because they are not imagining that the diceValuesArr contains an unordered list of dice rolls or not. Whatever the reason, I think to mitigate this issue, a more elaborate example can be added to the step to do away with that assumption once and for all.
Specifically instead of:

>A small straight is when four of the dice have consecutive values in any order (Ex. 1234) resulting in a score of 30 points. A large straight is when all five dice have consecutive values in any order (Ex. 12345) resulting in a score of 40 points.

We can have this:

A small straight is when four of the dice have consecutive values in any order (Ex. in a roll of 44123, we have 1234) resulting in a score of 30 points. A large straight is when all five dice have consecutive values in any order (Ex. in a roll of 31245, we have 12345) resulting in a score of 40 points.

It makes the text longer, but it may save some confusion. Please see a sample list of forum posts all sharing this confusion below.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-14

### Your code

N/A

### Expected behavior

Change the description to give a more elaborate example illustrating the unordered array as a starting point.

### System

N/A

### Additional context

https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/710121/4
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/708650/11
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/706200/5
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/707520/4
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/712629/2
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/713961/12
https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/716221

**Comment by lasjorg** [comment]
Seems like a good idea to have at least one of the examples show a random order. I would be fine with us using what you have suggested.

**Comment by hbar1st** [comment]
just to be clear: one of the examples also features a duplicate roll as sometimes we see people miss that scenario as well. They may still miss it, but we have the example to point to if they do.

**Comment by kamalxdev** [comment]
interesting, can I work on this?

**Comment by ilenia-magoni** [comment]
Hey @kamalxdev Thank you for your interest in contributing. We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by SOHAIB-code-png** [comment]
hey assign me this issue

**Comment by ilenia-magoni** [comment]
Stop asking, we don't assign issues @SOHAIB-code-png
