### ISSUE TITLE
Dice Game: Step 14 - Missing test for function call

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#56688]
### Describe the Issue

The requirement states.

> Call your `checkForStraights` function when the `rollDiceBtn` is clicked to complete your dice game!

There is no test for this.

Challenge file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-algorithmic-thinking-by-building-a-dice-game/657e230500602983e01fff6e.md

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/review-algorithmic-thinking-by-building-a-dice-game/step-14

### Your code

```



```

### Expected behavior

Test that the function is called when the button is clicked.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/review-algorithmic-thinking-by-building-a-dice-game-step-14/716363

**Comment by ilenia-magoni** [comment]
Let's open this for contribution. The PR should add a new test that checks for the presence of that function call

**Comment by SOHAIB-code-png** [comment]
hey assign me this issue I would like to contribute

**Comment by ilenia-magoni** [comment]
hey @SOHAIB-code-png, thank you for your interest in contributing. We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by N-nishita** [comment]
please assign

**Comment by gikf** [comment]
Hey @N-nishita,

please read comment that's just above yours and addresses your request - https://github.com/freeCodeCamp/freeCodeCamp/issues/56688#issuecomment-2421878191.

**Comment by altsun** [comment]
I think my PR #57367 may close this issue too

**Comment by altsun** [comment]
@ilenia-magoni Thanks, I linked this issue in my PR
