### ISSUE TITLE
js beta shopping cart - step 35 code checking too strict for braces

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#56686]
### Describe the Issue

in the js beta shopping cart project , step 36 does not allow the code below to pass
```
[...addToCartBtns].forEach(
  (btn) => btn.addEventListener("click", (event) => {})
);
```
and instead needs braces to be added in order to allow the code to pass as below:
```
[...addToCartBtns].forEach(
  (btn) => {btn.addEventListener("click", (event) => {})}
);
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-oop-by-building-a-shopping-cart/step-35

### Your code

```
[...addToCartBtns].forEach(
  (btn) => btn.addEventListener("click", (event) => {})
);

```

### Expected behavior

I would expect the code without the extra braces to pass.

### System

N/A

### Additional context

forum post that triggered this https://forum.freecodecamp.org/t/learn-basic-oop-by-building-a-shopping-cart-step-35/716369

**Comment by yaxit24** [comment]
The issue is that without braces, the arrow function implicitly returns the result of the single expression, which doesn't allow for complex logic in the event handler, so thence by Adding braces clarifies the function body, enabling the event listener to be defined correctly.
Please assign me the project.

**Comment by ilenia-magoni** [comment]
I don't know if there was a pedagogical reason... even if the tests are changed to be accepting of the implicit return one I don't think the seed need to be changed, considering that the returned value doesn't matter, having a body in the function is in line with that.

Considering that there is no explicit mention of wanting the function either way, I agree on making the tests accept also the version without braces

**Comment by ilenia-magoni** [comment]
I am opening for contributions, the expected change is: change the tests in the step to accept both versions, with and without braces

**Comment by prashu0705** [comment]
Hello! I would like to propose a solution to the issue regarding the strict code checking for braces in step 35 of the JavaScript beta shopping cart project.

Current Situation

As described, the current implementation requires the use of braces for the arrow function in the following code:
[...addToCartBtns].forEach(
  (btn) => {btn.addEventListener("click", (event) => {})}
);
However, the following version without braces is also valid:
[...addToCartBtns].forEach(
  (btn) => btn.addEventListener("click", (event) => {})
);
Suggested Change

I propose that the test conditions for this step be modified to accept both versions of the arrow function. This would allow for a more flexible approach to writing concise code while still being pedagogically sound.

Rationale
JavaScript Flexibility: JavaScript allows for implicit returns in arrow functions without braces, which can lead to cleaner and more readable code.
User Experience: Allowing both styles accommodates different coding preferences and encourages learners to explore the language's flexibility.
Please let me know if you need any further details or if there's a specific format you'd prefer for this change. I'm happy to help!

Thank you!

**Comment by ilenia-magoni** [comment]
@prashu0705 that's what I said, the issue is open for contributions, the expected change is to have the tests accept both versions

**Comment by ilenia-magoni** [comment]
Please make sure you read our [guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in our [chat room](https://discord.gg/PRyKn3Vbay) or our [forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing; our moderators will guide you through this.

Sometimes we may get more than one pull request. We typically accept the most quality contribution followed by the one that is made first.

Happy contributing.
