### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade has an issue 

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/freecodecamp#567]
The "Go to my next Challenge button" is enabled without meeting the first two conditions : 
-Your h2 element should degrade to the font "Monospace" when "Lobster" is not available.
-Your h2 element should degrade to the font "Monospace" when "Lobster" is not available.

Also the conditions are repeats; there should be only 1.

**Comment by QuincyLarson** [comment]
@jessienobata are you using Firefox? Try using Chrome. Our Waypoints are having a lot of issues in Firefox right now.

**Comment by JesseNoBata** [comment]
Yes Firefox; I notice it was duplicating a lot of the requirements.

**Comment by terakilobyte** [comment]
@jesseNoBata thanks for the report. This stems from #585 in a firefox-ish way. Closing this issue as firefox issues will be resolved when I have can tackle #585.
