### ISSUE TITLE
Waypoint: Escape Sequences in Strings (probably mini console bug)

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#5673]
Challenge [Waypoint: Escape Sequences in Strings](http://www.freecodecamp.com/challenges/waypoint-escape-sequences-in-strings#?solution=var%20myStr%20%3D%20%22%5C%5C%20%5Ct%20%5Ct%20%5Cr%20%5Cn%22%3B%20%2F%2F%20Change%20this%20line) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "\\ \t \t \r \n"; // Change this line
```
The point is:
1) if I use the same line for assignment and declaration, i.e. result looks like:
```javascript
var myStr = "\\ \t \t \r \n"; // Change this line
```
, then mini console log (under reset/help/bug buttons) returns: undefined (which is probably a bug)
2) because if I use another line to assign the variable, so that result looks like:
```javascript
var myStr; // Change this line
myStr = "\\ \t \t \r \n";
```
, then mini console returns: \ (which is probably correct)

This does not prevent a user from passing the challenge on Ctrl+Enter, so this issue's probably not substantial.

**Comment by ltegman** [comment]
This is due to the fact that by default we're taking the return value of whatever the last line of code is and an interesting aspect of javascript is that variable assignments have return values but variable declarations do not. However, we can get around this by adding a display function in the tail section of the challenge json that will always display the `myStr` variable.

**Comment by gasperno** [comment]
@ltegman Is the solution correct? 
The solution that is accepted is `var myStr="\\ \t \t \r \n";`.
I feel the encoded `myStr` should be `var myStr="\\ \\t \\t \\r \\n";`
This encodes these characters and print them on screen as `\ \t \t \r \n` .

**Comment by pratikr1593** [comment]
I was just missing out on the spaces, you gotta give only single space. else it won't work

**Comment by fdolzanes1** [comment]
`var myStr = "\\ \t \t \r \n"; // Change this line`

**Comment by anhlv8888** [comment]
correct :var myStr= 'FirstLine\n\\SecondLine\\\rThirdLine';

**Comment by dwd2010** [comment]
@anhlv8888 this place is not for put answer on here. You could help people at FreeCodeCamp chat room. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by anhlv8888** [comment]
thanks , :)
@dwd2010

**Comment by coderkak** [comment]
var mystr = "FirstLine\n\\SecondLine\\\rThirdLine";
This is the correct

**Comment by nguyenhoaihuy** [comment]
This is my solution:
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by texas2010** [comment]
@nguyenhoaihuy, Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by kellykevin** [comment]
@fdolzaneits1  it's true but what about implementing the text inside the myStr?

**Comment by barankurtulusozan** [comment]
There is a space in myStr.
Whomever will look at this topic, Please use 
alert(myStr);
 in line 3

**Comment by francis951** [comment]
this code isn't working for me atall

var myStr="\\ \t \t \r \n"; // Change this line


what should i do friend am completely stuck!

**Comment by kellykevin** [comment]
Hello my friend ? can you try with this one line below ?
 var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";
Thank you ...

**Comment by texas2010** [comment]
@francis951 @kellykevin 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
