### ISSUE TITLE
Replace Spacer with the one from @freecodecamp/ui

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#56744]
## Description

We have implemented a `Spacer` component in our component library (`@freecodecamp/ui`), so the existing `Spacer` in the /learn client should be replaced with that:

```diff
--- import { Loader, Spacer } from '../components/helpers';
+++ import { Spacer } from '@freecodecamp/ui';
```

Note that this is not a direct swap. The `size` prop needs to be updated as follows:

| /learn Spacer | @freecodecamp/ui Spacer |
| --- | --- |
| `xxSmall` | `xxs` |
| `small` | `xs` |
| `xSmall` | `s` |
| `medium` | `m` |
| `large` | `l` |
| `exLarge` | `xl` |
| `doubleXL` | `xxl` |

## Changes needed
 
- Migrate all Spacer usages to `@freecodecamp/ui` following the mapping above
- Remove the Spacer component from the codebase: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/components/helpers/spacer.tsx

**Comment by a2937** [comment]
Hmmm... That's a little odd. Am I reading the chart right; `small` maps to `xs` and `xSmall` maps to `s`?
