### ISSUE TITLE
"Learn Basic CSS By Building Cafe Menu" Step 45 not marking as pass but continuing on to step 46

### ISSUE THREAD

**Issue by Esrrlyg** [freeCodeCamp/freeCodeCamp#56750]
### Describe the Issue

going through the course "Learn Basic CSS By Building Cafe Menu" step by step through the online editor all steps registered completion apart from step 45, despite the solution being correct and it progressing on to step 46.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-45

### Your code

```
.flavor {
  text-align: left;
  width: 75%;
}

.price {
  text-align: right;
  width: 25%;
}
```

### Expected behavior

test the code, pass the code as per lesson parameters and progress to step 46

### Screenshots

Timeline shows completion of steps 43, 44, 46
![Image](https://github.com/user-attachments/assets/518bed24-a6dd-46d9-9c79-8ab76cb91e46)
Timeline shows completion of steps 90, 91, and 45 after going back and redoing it
![Image](https://github.com/user-attachments/assets/ff8c505f-ce88-43f4-827f-48ea42543f52)

### System

- Device: [Desktop]
- OS: [Windows 10]
- Browser: [Firefox]
- Version: [131.0.3 (64-bit)]

### Additional context

I know that I did not miss this step the first time round either willingly or mistakenly as the steps always progressed correctly. 
It was just at the end of the final step, when it brought me back to the cirriculum page (https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-basic-css-by-building-a-cafe-menu) showing step 45 as not completed (showing default square icon opposed to the blue highlighted icon)

**Comment by jdwilkin4** [comment]
Hi @Esrrlyg ! 

Whenever a practice project is updated, then it will show up in the timeline as not completed since changes were made to the step.

It looks like changes where made here in this PR
https://github.com/freeCodeCamp/freeCodeCamp/pull/56296

When that happens, you are free to ignore it and continue with the rest of the project. Only the certification projects count towards the claiming of the certification. 

Hope that helps

**Comment by Esrrlyg** [comment]
Cheers for the quick reply, however I'm unclear how with typo changes which were merged 3 weeks ago would impact the recording of completing all of the challenges today (18/10/2024).

Forgive me if I'm completely wrong but surely that wouldn't matter as they were merged well before I started on this section.

I am happy to ignore it and continue onwards to the next practice project, it just striked me as odd thats all.

**Comment by jdwilkin4** [comment]
> however I'm unclear how with typo changes which were merged 3 weeks ago would impact the recording of completing all of the challenges today (18/10/2024).

We don't deploy the site everyday.
We just did a deployment today which is why the new changes showed up. Hope that helps

**Comment by jdwilkin4** [comment]
Since this has been resolved, I am going to close the issue 👍
