### ISSUE TITLE
Language style needs to be adjusted

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#56766]
The styling guide for writing challenges say to not use the first person pronouns (we, let's...), and instead using always second person (you). There are some places where the text needs to be adjusted.
If you want to contribute, you should adjust the sentences the minimum necessary to move away from using first person to second person. A PR can solve all or only one workshop (in that case, mention only the Issue, do not link to close)

## workshop cafe menu
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-cafe-menu/5f3477aefa51bfc29327200b.md#L12

## workshop node and express
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb0367417b2b2512bed.md#L21-L22
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb0367417b2b2512bed.md#L29-L30
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb0367417b2b2512bee.md#L11-L12
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb0367417b2b2512bee.md#L27
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb0367417b2b2512bef.md#L11-L12
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb0367417b2b2512bef.md#L19-L20
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb0367417b2b2512bf0.md#L15
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb1367417b2b2512bf1.md#L13-L14
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb1367417b2b2512bf2.md#L17
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb1367417b2b2512bf4.md#L24
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb2367417b2b2512bf5.md#L11-L12
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb2367417b2b2512bf8.md#L11
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-node-and-express/587d7fb2367417b2b2512bf8.md#L15

## workshop npm packages
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-npm-packages/587d7fb5367417b2b2512c03.md#L11-L12

## workshop nutritional label
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-nutritional-label/615f4bfb9de4a16703b56eb6.md#L10

## workshop recipe tracker
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-recipe-tracker/66fbcf750a62784cf11f5634.md#L10
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-recipe-tracker/670e4f45f7116c0f216a5177.md#L10

## workshop rothko painting
https://github.com/freeCodeCamp/freeCodeCamp/blob/89fd487d1551b94b2863336a1713df727f158e35/curriculum/challenges/english/25-front-end-development/workshop-rothko-painting/60a3e3396c7b40068ad6996e.md#L14

**Comment by Subas-mohanty** [comment]
Is this issue asking to change first person pronouns(we, let's...)  with second person pronouns(you) in the mentioned file ? But as I can see the files are already using second person pronouns where necessary. Am I right ? Or the issue is asking something else ?

**Comment by Dario-DC** [comment]
All those sentences use we and/or let's. They should be modified to use the second person (you).

I guess in cases like "We have created a separate `styles.css` file for you" we want to modify the sentence into something like:

"A separate `styles.css` file has been created for you"

**Comment by Subas-mohanty** [comment]
Does the changes need to be done only in the mentioned file or throughout the document ?

**Comment by ilenia-magoni** [comment]
@Subas-mohanty the mentioned files where mentioned because they need to be changed. A PR has already be opened, thank you for your interest in contributing.
