### ISSUE TITLE
Data Analysis Medical Data Visualizer - missing instructions BMI

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#56776]
### Describe the Issue

It looks like the instructions for the overweight column were removed in a recent update.

Current instructions:
```
2. Create the overweight column in the df variable
```

Previously:
```
- Add an `overweight` column to the data. To determine if a person is overweight, first calculate their BMI by dividing their weight in kilograms by the square of their height in meters. If that value is > 25 then the person is overweight. Use the value `0` for NOT overweight and the value `1` for overweight.
```
Original can be found here:
https://github.com/freeCodeCamp/freeCodeCamp/pull/56508/files

### Affected Page

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer

### Your code

```
NA


```

### Expected behavior

NA

### Screenshots

NA

### System

- Device: [e.g. iPhone 6, Laptop]NA
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by N-nishita** [comment]
assign
