### ISSUE TITLE
Replace "then" with "than" in sample code on left.

### ISSUE THREAD

**Issue by tracylm** [FreeCodeCamp/FreeCodeCamp#5678]
No problem with code. Typo in text where "then" is used instead of "than". See attached image.

![type in waypoint introducting else if statements](https://cloud.githubusercontent.com/assets/10949098/12069506/053b2560-b002-11e5-8f62-f403ccbd2e3d.jpg)
Challenge [Waypoint: Introducing Else If Statements](http://www.freecodecamp.com/challenges/waypoint-introducing-else-if-statements#?solution=function%20myTest(val)%20%7B%0A%20%20if%20(val%20%3E%2010)%20%7B%0A%20%20%20%20return%20%22Greater%20than%2010%22%3B%0A%20%20%0A%20%20%7D%20else%20if%20(val%20%3C%205)%20%7B%0A%20%20%20%20return%20%22Smaller%20than%205%22%3B%0A%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Between%205%20and%2010%22%3B%0A%20%20%7D%0A%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  if (val > 10) {
    return "Greater than 10";
  
  } else if (val < 5) {
    return "Smaller than 5";
  
  } else {
    return "Between 5 and 10";
  }
}             
// Change this value to test
myTest(7);


```

**Comment by ShaggyTech** [comment]
@SaintPeter This appears to have been fixed already.

**Comment by ltegman** [comment]
@ShaggyTech is correct that this is fixed in staging.
