### ISSUE TITLE
Update the criteria for passing quizzes

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#56790]
## Description

The description of the quizzes are currently:

```
Answer all of the questions below correctly to pass the quiz.
```

However, we are making the quizzes more forgiving, and campers can pass with at least 85% correct answers. So the description should be changed to something like:

```
To pass the quiz, you must answer at least 85% of the questions correctly.
```

## Changes needed

Update the description of all quizzes in https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/25-front-end-development.

## Other notes

Related discussion: https://github.com/freeCodeCamp/freeCodeCamp/pull/56644#discussion_r1811528907.

**Comment by tarun9142** [comment]
you merged your own pr. It was marked help wanted thats why i raised.
