### ISSUE TITLE
Missing punctuation in user stories

### ISSUE THREAD

**Issue by khushi144** [freeCodeCamp/freeCodeCamp#56813]
### Describe the Issue

This document has no full-stop at the end of each "User Stories".

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-palindrome-checker-project/build-a-palindrome-checker

### Your code

At the end of each "User Stories" add punctuation.

### Expected behavior

.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment]
Please wait for an issue to be triaged before opening a PR for it.

**Comment by khushi144** [comment]
> Please wait for an issue to be triaged before opening a PR for it.
I will take care next time.

**Comment by brambhattabhishek** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me?
