### ISSUE TITLE
"Error" in ( Responsive Web Design: Learn CSS by building a set of Colored Markers in Italian Language)

### ISSUE THREAD

**Issue by SouL321321** [freeCodeCamp/freeCodeCamp#56816]
### Describe the Issue

I was doin' the Responsive Web Design: Learn CSS by building a set of Colored Markers (with Italian translation) and I realized that there is a "error" about the Steps.. Im actually in Step 27 but there's wrote Step 37.
I dont know if this is the right way to "report" a bug/issue... then first of all sorry for the disturb.. 
and I hope u a nice day!

### Affected Page

https://www.freecodecamp.org/italian/learn/2022/responsive-web-design/learn-css-colors-by-building-a-set-of-colored-markers/step-27

### Your code

```
Step 37
Now that you have the primary RGB colors, it's time to combine them.

Per la funzione rgb nella regola .container, imposta rosso, verde e blu al valore massimo di 255.

```

### Expected behavior

Step 27
Now that you have the primary RGB colors, it's time to combine them.

Per la funzione rgb nella regola .container, imposta rosso, verde e blu al valore massimo di 255.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by SouL321321** [comment]
Thanks to you for your availability!
Have a nice day

**Comment by ilenia-magoni** [comment]
The string in crowdin has been changed, then it will go through the usual pipeline. Thank you for reporting this, you can also use the `translation-discussion` channel in Discord if you find other translation mistakes, or if you want to partecipate in the tranlsation.
