### ISSUE TITLE
college-algebra-with-python Sanskrit

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#56827]
### Describe the Issue

For this question:
```
Which of the following languages can you not use in Google Colaboratory?
HTML
LaTex
English
Sanskrit
```
The correct answer is "Sanskrit" but you can use Sanskrit for text fields in Colab as much as you can use English. Screenshot attached. I imagine you can use any language for these fields? 

There is some discussion about this here:
https://forum.freecodecamp.org/t/learn-fractions-and-decimals-fractions-and-decimals-extra/692690

"The question is which language is NOT mentioned in the video."

But that isn't the question. I guess you can infer which language isn't mentioned in the video, but you can in fact use Sanskrit in Google Colab.

The question could be changed to "What language listed here is not mentioned in the video?" I don't think this is a good question because it assumes you have not only total recall of every word in the video but also recall of words NOT mentioned in the video?

I would suggest:
```
Which of the following languages can you use in a Google Colaboratory text field?
HTML
LaTex
English
All of the Above
```

With `All of the Above` as the correct answer.

### Affected Page

https://www.freecodecamp.org/learn/college-algebra-with-python/learn-fractions-and-decimals/fractions-and-decimals-extra

### Your code

```

NA

```

### Expected behavior

NA

### Screenshots

![Image](https://github.com/user-attachments/assets/77951c0c-9f5a-4a2c-a875-9c2f6946466b)

### System

- Device: [e.g. iPhone 6, Laptop] NA
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by brambhattabhishek** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me?
