### ISSUE TITLE
football team card project- step 27 function not returning anything

### ISSUE THREAD

**Issue by kamalxdev** [freeCodeCamp/freeCodeCamp#56834]
### Describe the Issue

While I was working on the issue #56666 , I got to know the function `setPlayerCards` in not returning anything, while results in no change in the DOM .

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-modern-javascript-methods-by-building-football-team-cards/step-27

### Your code

```
const setPlayerCards = (arr = players) => {

playerCards.innerHTML += arr.map(
    ({ name, position, number, isCaptain, nickname }) => {
      return `
        <div class="player-card">
          <h2>${name}</h2>
        </div>
      `;
    }
  );

```

### Expected behavior

It should return the div element.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context
This would also help in solve #56666
Would like to work on this, if approved

**Comment by brambhattabhishek** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me?

**Comment by AVTG** [comment]
This works fine.

const setPlayerCards = (arr = players) => {


  playerCards.innerHTML += arr.map(
    ({ name, position, number, isCaptain, nickname }) => {
      return `
        <div class="player-card">
          <h2>${isCaptain?"(Captain)":""}${name}</h2>
        </div>
      `;
    }
  );
};

**Comment by ilenia-magoni** [comment]
weren't you working on this in your PR? you can do both things in the same PR
