### ISSUE TITLE
You should have four break statements error

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#5686]
Waypoint: Replacing If Else Chains with Switch

The code below should pass but gets blocked since the tests are checking for 4 break statements instead of five.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line  
  switch(val){
    case "bob":
      answer = "Marley";
      break;
    case 42:
      answer = "The Answer";
      break;
    case 1:
      answer = "There is no #1";
      break;
    case 99:
      answer = "Missed me by this much!";
      break;
    case 7:
      answer = "Ate Nine";
      break;
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(7);
```

**Comment by SaintPeter** [comment]
Test should probably read `>= 4`.

Technically we don't need the last break.

**Comment by AkiraLaine** [comment]
I'll change it :smile:

**Comment by njwda** [comment]
I can't get pass this one: Here is my code:  


function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
   switch (val){
    case val ==="bob":
      answer="Marley";
      break;
      
       case val === 42:
      answer="The Answer";
      break;
      
          case val === 1:
      answer="There is no #1";
      break;
      
          case val === 99:
      answer="Missed me by this much!";
      break;
          case val === 7:
      answer="Ate Nine";
  break; 
  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch("bob");



Any advice? thanks

**Comment by atjonathan** [comment]
@njwda, Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
