### ISSUE TITLE
[ Full Stack Cert ] - update descriptions and tests for business card lab

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#56868]
There are a few updates we need to make to the following business card lab 

Here is the file that needs updating

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/lab-business-card/6690e10ebe2181212abc9652.md

List of updates

1. Remove all jQuery from hints section
2. All mentions of `margin`, `padding`, `class` and `div` need to be inside backticks (``). This mainly applies to the user stories, but also double check the hints as well.

**Comment by jdwilkin4** [comment]
This has been opened for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)



Happy coding

**Comment by An525ish** [comment]
hey, I'd like to work on this issue

**Comment by gauravsharmaworld** [comment]
hey i like to contribute

**Comment by gikf** [comment]
Hey @An525ish, @gauravsharmaworld 

Please read previous comment - https://github.com/freeCodeCamp/freeCodeCamp/issues/56868#issuecomment-2438411475, it explains everything.
