### ISSUE TITLE
Waypoint: Stand in Line - unable to use splice instead of shift?

### ISSUE THREAD

**Issue by krisgesling** [FreeCodeCamp/FreeCodeCamp#5689]
Challenge [Waypoint: Stand in Line](http://www.freecodecamp.com/challenges/waypoint-stand-in-line#?solution=%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%5D%3B%0A%0Afunction%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr.push(item)%3B%0A%20%20%2F%2Fitem%20%3D%20arr.splice(0%2C1)%3B%0A%20%20item%20%3D%20arr.shift()%3B%0A%20%20return%20item%3B%0A%7D%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0Aconsole.log(queue(%5B2%5D%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0</code>.

The challenge is probably wanting the user to use `shift()` rather than `splice(0,1)` but it seems like the solution should still pass. Below is my code with the successful line commented out and the unsuccessful splice code uncommented. This fails the first two tests and passes the third.

My code:
```javascript
// Setup
var myArr = [];

function queue(arr, item) {
  // Your code here
  arr.push(item);
  item = arr.splice(0,1);
  // item = arr.shift();
  return item;
}

// Display Code
console.log("Before: " + JSON.stringify(myArr));
console.log(queue([2], 1)); // Modify this line to test
console.log("After: " + JSON.stringify(myArr));

```

**Comment by ShaggyTech** [comment]
Most likely because splice() returns an array of what was spliced, the tests are looking for ```item``` to NOT be in an array.

**Comment by ltegman** [comment]
@ShaggyTech is correct. Thanks and happy coding!

**Comment by krisgesling** [comment]
Thanks ShaggyTech! I did ask in the help room but it's a bit hectic in there at the moment
