### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-padding-of-an-element has an issue 

### ISSUE THREAD

**Issue by vishim** [FreeCodeCamp/freecodecamp#569]
This challenge does not test the Clockwise Notation to Specify the Padding of an Element
; it rather is repeat of a previous challenge

**Comment by BerkeleyTrue** [comment]
Thanks @vishim for reporting this issue. I have verified that it is indeed not fully testing the result.

This answer passes the test
`padding: 0 0px 20px 40px;`

 but in reality the answer should be 
`padding: 40px 20px 20px 40px;`

Solution to this is to add two more test to make sure padding on the top and right side are correct.

**Comment by QuincyLarson** [comment]
I'm adding this.

**Comment by QuincyLarson** [comment]
Actually, some one has fixed this. Works, I'm closing this issue. Thanks @shamoo and @terakilobyte!
