### ISSUE TITLE
Golf Waypoint "Go Home!" Error

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#5691]
Waypoint: Golf Code
Please describe how to reproduce this issue, and include links to screenshots if possible.

The last 2 tests for "Go Home!" should pass, but it doesn't.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  
    if(strokes == 1  ) {
 return "Hole-in-one!";
} else if (strokes <= par-2) {
return "Eagle";
} else if (strokes == par-1) {
return "Birdie";
} else if (strokes == par) {
return "Par";
} else if (strokes == par+1) {
return "Bogey";
} else if (strokes == par+2) {
return "Double Bogey";

} else {
return "Go Home";
}
 
  // Only change code above this line
}

// Change these values to test
golfScore(5, 9);

```

![image](https://cloud.githubusercontent.com/assets/11958359/12069902/c7295a94-b0a6-11e5-82b0-13db54b64183.png)

**Comment by ltegman** [comment]
You're not including the `!` at the end.

Thanks and happy coding!
