### ISSUE TITLE
Step 50 of Statistics Calculator doesn't give useful hint if you are missing starting value of reduce

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#56938]
### Describe the Issue

The step doesn't give a useful hint if you are missing the initial value of the reduce.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-advanced-array-methods-by-building-a-statistics-calculator/step-50

### Your code

```js
const getVariance = (array) => {
  const mean = getMean(array);
  const differences = array.map(
    el => el - mean
  );
  const squaredDifferences = differences.map(
    el => el ** 2
  );
  const sumSquaredDifferences = squaredDifferences.reduce((acc, el) => acc + el);

}


```

### Expected behavior

I would expect an hint that said that you are missing the starting value of the reduce.

### Screenshots

![Image](https://github.com/user-attachments/assets/b28ad62e-ac88-4dd3-a93c-2000d12d80e7)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by AshishVyas03** [comment]
Hi, I noticed task is currently unassigned, and I'd be interested in taking it on. Could you assign it to me so I can get started?

Thanks!

**Comment by ilenia-magoni** [comment]
Hi, @AshishVyas03 

Thanks for your interest in contributing.

This issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to create a pull request to reflect the issue consensus. Please also note that we typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

**Comment by Subas-mohanty** [comment]
Does the hint and the test data taken from the related .md file, for example all hint and test data for step 49 is coming from the .md file having title : step 49

**Comment by Subas-mohanty** [comment]
After doing my research I found that each challenge with an unique Id and title is present in the meta.json file and all the details and test data about that challenge are present in the Id.md file, where all the hint and code samples also present. Am i going in the right direction ?

**Comment by Subas-mohanty** [comment]
Thanks for informing, I am new to open source and I was trying to understand the codebase, here is my break down : 

The hint for the reduce callback that you mention in the issue resides in this file right : https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-advanced-array-methods-by-building-a-statistics-calculator/6352fcb156834128001ea945.md

And do you want a hint something like this when right arguments are not passed to the reduce callback,


Your `reduce` callback should have an initial value in the second argument.

```js
assert.match(getVariance.toString(), /sumSquaredDifferences\s*=\s*squaredDifferences\.reduce\(\s*function\s*\(\s*acc\s*,\s*el\s*\)\s*\{\s*return\s*acc\s*\+\s*el\s*;\s*\}\s*)/);
```

**Comment by gikf** [comment]
Note: additional step were added to the project. Currently step 50 is affected by the issue.
