### ISSUE TITLE
Adding sections that talks about project management / working on a team / working within a company

### ISSUE THREAD

**Issue by eccentricafterglow** [FreeCodeCamp/FreeCodeCamp#5693]
Hi ya'll!

I noticed this may be a request that needs to be broken out into several parts / tickets:

What I've noticed with people who are new to software development at times is they feel out of the loop when it comes to the nuts and bolts of project work / working with other disciplines such as PM / Producer, UX, QA, etc... It may help the campers to have some sort of documentation, videos, or some sort of information to help them get a sense of what it's like to work on a team or within a company. 

Also, it will be helpful to talk about how to manage a project, and the different kinds of way a project can be managed -- such as how does Agile development works, or Waterfall method. For the majority of places that I've worked (web apps) at have used Agile. Although, that has usually depended on what kind of project is being built, and the company's preferences. 

If anyone needs elaboration or has questions -- feel free to reach out to me. I work as a software QA Analyst that works on web apps and mobile apps.

**Comment by ltegman** [comment]
Interested to hear @FreeCodeCamp/owners thoughts on if this is within the scope of Free Code Camp and should be added to the curriculum down the line.

**Comment by BerkeleyTrue** [comment]
This issue is better suited for hikes as these aren't actionable challenges.

**Comment by ltegman** [comment]
Closing this as something not appropriate for the challenge structure of the main Free Code Camp curriculum. I suggest opening an issue on https://github.com/FreeCodeCamp/hikes if this is something you would still like to see added. Thanks and happy coding!
