### ISSUE TITLE
Cat photo app step 14 has a typo

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#56999]
Step 14 of Cat Photo App in RWD, and also the Cat Photo App workshop in the new cert have a typo:

![Image](https://github.com/user-attachments/assets/976c2348-4d50-42c5-b72e-f873133899f1)

It should be "attribute" instead

**Comment by Agung1606** [comment]
can i work on this issue?

**Comment by ilenia-magoni** [comment]
@Agung1606 @avneets0419 Thank you for your interest in contributing.
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
