### ISSUE TITLE
passing front end libraries challenge without doing it

### ISSUE THREAD

**Issue by Stu-Air** [freeCodeCamp/freeCodeCamp#56993]
### Describe the Issue

context - before on FCC site challenges (not Codepen) I would finish the course click off the screen and and the congrats box would disappear without clicking go to the next challenge, resulting in not registering completed. I just click the submit button and go to next challenge. 

no Codepen account / save created for this as after the first one it had passed so I just didn't set one up. set up in VScode and copy paste into Codepen

I thought I had done about above for the front end challenges which involves completing the challenge on Codepen. on my 4th challenge, I had clicked off the FCC page to get just run the test one time and make sure I took a copy of the link. I had actually press the go to next challenge not realising that it was the 5th challenge and submitted and passed with out doing anything. 

I assume that the link must be the same for all challenges and its not checking the code submitted. In my case would be blank anyway as i have no account

### Affected Page

Front end libraries 

### Steps to Reproduce

1. Go to 'FCC front end libraries.'
2. Click on 'any challenge scroll to the bottom click the Code pen link copy link.'
3. Scroll down to 'bottom of the FCC front end challenge and submit '
4. No error just no work 

### Expected behavior

not to pass . i understand you don't that forcing a codepen account is not ideal.

### System

- Device: PC
- OS: Archlinux
- Browser: Firefox
- Version: 131.0.3

**Comment by ilenia-magoni** [comment]
It relys on Academic Honesty, but also your cert could be removed if you don't supply links for working projects. With the [new cert](https://www.freecodecamp.org/news/freecodecamp-turns-10-major-curriculum-updates/) this will not be an issue anymore

**Comment by Stu-Air** [comment]
thanks, just wanted to make you aware in case you weren't
