### ISSUE TITLE
Will read only lowest console.log statement, saying unfinished for one of the test cases

### ISSUE THREAD

**Issue by inkblotty** [FreeCodeCamp/FreeCodeCamp#5700]
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0A%2F%2FourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20myFunction(num1%2C%20num2)%7B%0A%20%20return%20num1%2Bnum2%3B%0A%7D%0A%0Aconsole.log(myFunction(1%2C2))%3B%0Aconsole.log(myFunction(7%2C9))%3B%0AmyFunction(1%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
//ourFunction(10, 5); // Outputs 5

// Only change code below this line.

function myFunction(num1, num2){
  return num1+num2;
}

console.log(myFunction(1,2));
console.log(myFunction(7,9));
myFunction(1,2);

```

**Comment by inkblotty** [comment]
![freecodecampissue](https://cloud.githubusercontent.com/assets/14206003/12070192/4cf0ff8a-b023-11e5-89e7-ca2d8c8c1042.png)

**Comment by ShaggyTech** [comment]
Look again at the inside of the example function to see what you should be doing inside your function.  Pay special attention to this part of the instructions:
> and outputs their sum to the dev console

**Comment by inkblotty** [comment]
Haha.. My first github issue is a silly one.. Thanks!

**Comment by DDaems** [comment]
@inkblotty please close your issue if it is resolved, thanks ;-)
