### ISSUE TITLE
Waypoint: Passing Values to Functions with Arguments (probable result checker issue)

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#5701]
Challenge [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments#?solution=%2F%2F%20Example%0Afunction%20ourFunction(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunction(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afunction%20myFunction(param1%2C%20param2)%20%7B%0A%20%20console.log(param1%2Bparam2)%3B%0A%7D%0AmyFunction(%22booyakasha%22%2C%22%20ali%20pali%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 5841.83.0) AppleWebKit/537.36 (KHTML like Gecko) Chrome/36.0.1985.138 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
function myFunction(param1, param2) {
  console.log(param1+param2);
}
myFunction("booyakasha"," ali pali");
```
note: **myFunction("booyakasha"," ali pali");**

Response is:
```javascript
ok > myFunction should be a function
ok > myFunction(1,2) should output 3
ok > myFunction(7,9) should output 16
not ok > Call myFunction after you define it
```
note: **not ok > Call myFunction after you define it**

If my code is:
```javascript
// Example
function ourFunction(a, b) {
  console.log(a - b);
}
ourFunction(10, 5); // Outputs 5

// Only change code below this line.
function myFunction(param1, param2) {
  console.log(param1+param2);
}
myFunction(548,958);
```
note: **myFunction(548,958);**

Response is:
```javascript
ok > myFunction should be a function
ok > myFunction(1,2) should output 3
ok > myFunction(7,9) should output 16
ok > Call myFunction after you define it 
```
note: **ok > Call myFunction after you define it**

Conclusion: result checker considers function not called, even though it is, if strings are passed as parameters.

PS: just checked combination param1 = int, param2 = str; checker returns failure => if at least one param is a string, checker most probably doesn't work in a correct way.

**Comment by JoleDev** [comment]
![image](https://cloud.githubusercontent.com/assets/9546456/12070734/c5304b98-b0ac-11e5-833b-6559c7932549.png)


Even if the both parameters are integers it is not working properly.

**Comment by DDaems** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1902
 
Here is a proper regex that resolves this issue:
`function myFunction[\s\S]+myFunction\(\s*\d+\s*,\s*\d+\s*\)`

I'm having a bit of a hangover, so i'm browsing on my laptop. Because of this, I'm not creating a PR. If someone else wants try, keep in mind that you still need to do the escaping. ;-)

**Comment by ShaggyTech** [comment]
Should the test still pass if the camper only supplies 1 argument for the function?  Should there be a separate test to state the camper needs to supply 2 arguments?

**Comment by ShaggyTech** [comment]
Or how about using the same test and changing the wording to something like 
>Call myFunction after defining it, making sure to give it two arguments.

**Comment by ShaggyTech** [comment]
Fixed the original issue with #5713

Also changed the wording of the last test to remind the camper to pass myFunction two arguments.
From:
```Call myFunction after defining it.```
To:
```Call myFunction after defining it, making sure to pass it two arguments.```

**Comment by IrenaGlisic** [comment]
![screen shot 2016-07-12 at 11 40 23](https://cloud.githubusercontent.com/assets/20281096/16762640/9fe1b528-4825-11e6-8db3-76880e09cd4e.png)

**Comment by IsmaelBarba** [comment]
Thanks Irena. Im still lost on this one. But I really appreciate the help.

ish

**Comment by OgunniyiOwamamwen** [comment]
// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs (c,d){
  console.log(c+d);
}
functionWithArgs(7,9);

**Comment by vstarmoore** [comment]
I'm not sure I'm doing wrong can someone pls help me?


function FunctionWithArgs(param1, param2) {
console.log(param1 + param2);
}
  FunctionWithArgs(1, 2);
  FunctionWithArgs(7, 9);
