### ISSUE TITLE
JS- spam filter step 2 not clear enough

### ISSUE THREAD

**Issue by pkdvalis** [freeCodeCamp/freeCodeCamp#57058]
### Describe the Issue

There is a mod comment here:
[https://forum.freecodecamp.org/t/learn-regular-expressions-by-building-a-spam-filter-step-2/686105](url)

"the instructions aren’t clear enough. They want you to use an arrow function for the callback."

Original instructions:
>Step 2
Attach an event listener to your checkMessageButton, listening for the click event. Give it an empty callback function.

Proposed instructions:
>Step 2
Attach an event listener to your checkMessageButton, listening for the click event. Give it an empty callback arrow function.

It could emphasize arrow even more:
>Step 2
Attach an event listener to your checkMessageButton, listening for the click event. Give it an empty callback function using arrow function syntax.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-regular-expressions-by-building-a-spam-filter/step-2

### Your code

```


NA
```

### Expected behavior

NA

### Screenshots

NA

### System

- Device: [e.g. iPhone 6, Laptop]NA
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by jdwilkin4** [comment]
I vote we leave the text as is and update the test to accept either regular or arrow functions
