### ISSUE TITLE
Refactor steps 8-13 in authors workshop

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#57072]
These steps really could just be merged into one step.
This workshop, comes at the very end of the entire JavaScript section. And campers will have way more practice with the additional labs and workshops in the new full stack cert before they reach this point. So it doesn't need to be broken down as much as it is right here.

Here is the link to the workshop:

https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/_meta/workshop-fcc-authors-page

## updated description 

Here is an idea of what the new description can be but it can also be refined a little bit

````md
Now, it is time to create the function that will be responsible for displaying the authors on the page. 

Start by creating a function called `displayAuthors` that takes an `authors` parameter. Your function should then loop through the `authors` array and add a card for each author to the `authorContainer` `div`. 

The card should have the following structure:

```html
<div id="${index}" class="user-card">
  <h2 class="author-name">${author}</h2>
</div>
```

**Tips:**

- You can use any type of loop to iterate over the `authors` array. Ex. `for`, `forEach`, `map`, etc.
- You should use the `innerHTML` property to add the card to the `authorContainer` inside the loop. You will also need to use template literal syntax to add the markup.
````

The goal is to make this more open ended, allow for more correct solutions, and get campers thinking more about how to solve this.

## updating tests

For the tests, we really should only care about 3 things

- Did campers create a function called `displayAuthors`? It doesn't matter if they use arrow syntax or regular. The test could be the `isFunction` assert
- Did campers create a function with the parameter `authors`? This one can be a regex to test for the parameter. So something like this should work. Ex `assert.match(code, /displayAuthors\s*(?:=\s*)?\(\s*authors\s*\)\s*/);`
- When the `displayAuthors` function is called, `authorContainer` `div` updated properly with author cards?

For this one, we could have a few tests that pass in different array examples.
Maybe something like this

````md
When the `displayAuthors` function is called with an author's array, it should add a card for each author to the `authorContainer` `div`.

```js
const exampleAuthors = [
  {
    "author": "Quincy Larson",
  },
  {
    "author": "Jessica Wilkins",
  },
];

const expectedCardResult = `
<div id="0" class="user-card">
  <h2 class="author-name">Quincy Larson</h2>
</div>
<div id="1" class="user-card">
  <h2 class="author-name">Jessica Wilkins</h2>
</div>
`;
displayAuthors(exampleAuthors);
assert.equal(authorContainer.innerHTML, expectedCardResult);
```
````

haven't tested it but something along those lines should work. And we could add a few tests to check against different arrays to make sure they don't hardcode a result

**Comment by RGHANILOO** [comment]
Hey all, 

in order to tackle this issue we would be using the Challenge Editor ? just wanted to check if my understanding was correct

**Comment by jdwilkin4** [comment]
You can use either the challenge editor or run the script manually
https://contribute.freecodecamp.org/how-to-work-on-practice-projects/#using-the-scripts-manually

**Comment by a2937** [comment]
Hey I have a silly question. At this point in the curriculum,  what do the campers have to work with to solve the problems?

**Comment by jdwilkin4** [comment]
This workshop comes at the very end of the JavaScript chapter.
So they will have already done dozens of workshops and labs working with JS fundamentals like strings, objects, arrays, etc.
They will also be very familiar with the common string and array methods, higher order functions, regex, DOM manipulation, dates, JSON, maps, sets, working with forms, local storage, CRUD, classes, functional programming, recursion, etc. 

Just before this workshop, there will be a lecture block talking about async JS.

- What is asynchronous JavaScript and how does it differ from synchronous JavaScript?
- How does the `async` attribute work inside `<script>` elements and how does it differ from the `defer` attribute?
- What is the Fetch API and what are common types of resources that are fetched from the network?
- How does the Fetch API work with common HTTP methods and `res.json()`?
- What are promises and how does promise chaining work? (talk about `.then` and `.catch` here)
- What is async/await and how does it work?
- How does the JavaScript engine work and what is a JavaScript runtime?
- What is the Geolocation API and how does `getCurrentPosition` work?

So this whole workshop, will be reworked to be more opened ended because they will have more information then in the current beta JS version.

But for this step, we can just give them prompt to ask them to create this `displayAuthors` function on their own, and they will have skills and experience to figure that out because of the dozens of labs that come before this.

**Comment by a2937** [comment]
![Challenge Editor](https://github.com/user-attachments/assets/0588e5a9-22c3-450e-9299-6463e8550e3e)


Is it just me or are the step tools missing?

**Comment by ilenia-magoni** [comment]
@a2937 yes they are missing, there is some setting somewhere that doesn't have them for the full-stact cert
