### ISSUE TITLE
nothing happening after clicking run and the output window on right is blank.

### ISSUE THREAD

**Issue by rajdeep1008** [FreeCodeCamp/FreeCodeCamp#5708]
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%0A%20%20h2%20%7Bcolor%3A%20%3B%7D%0A%0A%3C%2Fstyle%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>

  h2 {color:blue;}

</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


```

**Comment by smrajagopal** [comment]
@rajdeep1008 : I do not see anything wrong with your code and there is no steps to reproduce the issue in your post. 

Suggestions:
- You may close this issue for now and try the following
- You may actually try to refresh your webpage or restart your browser and see if the issue still persists (again this looks something only appearing at your end and not for everyone). 
- I would highly encourage you to use [FreeCodeCamp's Help Chatroom] (https://gitter.im/FreeCodeCamp/Help) for help with this. 
- If all the above failed for you, come back and open a new issue following the guidelines from [here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue)

**Comment by ltegman** [comment]
If the output window is blank and the run tests button is not working javascript execution on your page is likely broken. Here are some things you can try to see if you can fix this: Restart your browser, clear your browser cache, disable browser extensions.

Closing as this is not a site issue but something going wrong with your browser/connection. Thanks and happy coding!

**Comment by rajdeep1008** [comment]
Hello sir/madam
i tried everything from refreshing my browser to trying fcc on a different
computer, still i am facing the same issue on other computers as well.
Please check if there's any problem on html css waypoints.
regards,
rajdeep1008

**Comment by Amohamed86** [comment]
I am also experiencing issues towards the finishing point of the CSS Selectors to Style Elements. I'm unable to run test the code, furthermore I have tried all of the recommended pointers in regards to resolving this issue without success.
