### ISSUE TITLE
Todo app - Step 44: Passes with incorrect code

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#57089]
### Describe the Issue

The regex test allows you to pass with this code.

```js
const deleteTask = (buttonEl) => {
  const dataArrIndex = taskData.findIndex(
    (item) => {
      item.id === buttonEl.parentElement.id
      buttonEl.parentElement.remove();
      taskData.splice(dataArrIndex, 1)
    }
  );
}
```

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-localstorage-by-building-a-todo-app/step-44

Tests:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/64faf874364ec308f875f636.md

### Your code

```

```

### Expected behavior

To not pass with incorrect code.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-localstorage-by-building-a-todo-app-step-44/719638/4

**Comment by hbar1st** [comment]
is an extra check needed to make sure the arrow function is not edited in this case?
