### ISSUE TITLE
TypeError: Finding a Remainder in Javascript

### ISSUE THREAD

**Issue by DDaems** [FreeCodeCamp/FreeCodeCamp#5709]
Challenge [Waypoint: Finding a Remainder in Javascript](http://www.freecodecamp.com/challenges/waypoint-finding-a-remainder-in-javascript#?solution=%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20remainder%20%3D%2011%20%25%203%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36 OPR/34.0.2036.25</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Only change code below this line

var remainder = 11 % 3

```
if i add a semicolon at the end it does pass.

**Comment by smrajagopal** [comment]
@DDaems Initial look into this and I see the following from Developer Console when the error is thrown

```
var remainder = 11 % 3
(function(y){return 'remainder = '+y;})(remainder);
```
leading to incorrectly interrupting your code as `3(...)(remainder);` and since as we know `3` is not a function, we get `TypeError: 3 is not a function` as error.

Hence it is always good to add `;` at the end of each statement because we have no idea what other code runs along in the backend.

More detailed explanation can come from core FCC member (if required)

**Comment by DDaems** [comment]
@smrajagopal The supplied code is still valid and should not trow a TypeError. Its a bug, that should be addressed.

**Comment by ltegman** [comment]
This is an unavoidable side effect of the way the code is executed and there's a linting error on the side saying a semicolon should be added, so I don't think this is a problem.

Thanks and happy coding!

**Comment by DDaems** [comment]
@ltegman 

I agree that this isn't a really big problem, certainly nothing dealbreaking. 
But this is still a bug that could be pointed out to the module creator/maintainers.

Can we maybe leave it open temporarly with some tags as: 'low-priority', 'fcc-core', 'hard'?
Untill someone has passed it along to the creator/maintainers of the module.
So this bug doesn't dissapear in the void, because its not all to important.


@BerkeleyTrue @SaintPeter
Opinions on this?

**Comment by ltegman** [comment]
I'll leave it up to @BerkeleyTrue whether this is something that should be reopened for a fix or not. I've seen similar bugs closed in the past which is why I closed it.

**Comment by BerkeleyTrue** [comment]
> The supplied code is still valid and should not trow a TypeError.

This is a syntax error and the reason you should always use semicolons. Always use semicolons and you won't run into this problem.

Happy Coding!

**Comment by redeyesblackdragon** [comment]
The answer is "var remainder = 2; 11 % 3;" ...

**Comment by DDaems** [comment]
I have no idea why you bumped this issue providing a answer, because its exactly not what this is about. Anyway, i might aswell thank you. Else i likely wouldn't have fixed it. ;-)

**Comment by redeyesblackdragon** [comment]
I bumped this issue for the sole purpose of you not having a idea lmao

**Comment by ncarrasco** [comment]
Other!.
![remainder](https://cloud.githubusercontent.com/assets/12000912/20404444/64a01778-acdb-11e6-940b-094fc991dd19.PNG)

**Comment by texas2010** [comment]
@ncarrasco 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Kermet24** [comment]
You have var remainder = 11 % 3
but you should have
 var remainder = 11 % 3;

**Comment by samizle** [comment]
The answer is: 
var remainder = 2;
remainder = 11 % 3;
