### ISSUE TITLE
Calorie Counter - Step 45: single/double quote order shouldn't matter

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#57090]
### Describe the Issue

The test is expecting the double quotes for the inner string. It should allow for both.

```
"input[type='text']"
```

or

```
'input[type="text"]'
```

Tests:

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c2164c0df38a382062c4af.md

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-45

### Your code

```



```

### Expected behavior

Allow any order for the quotes.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

### Additional context

Forum: https://forum.freecodecamp.org/t/learn-form-validation-by-building-a-calorie-counter-step-45/719651

**Comment by hbar1st** [comment]
i see another issue with the same step where it accepts .length() as valid. (I can fix this and the original issue together)
