### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue 

### ISSUE THREAD

**Issue by pachecocarlos1988** [FreeCodeCamp/freecodecamp#571]
dont work

**Comment by vishim** [comment]
works for me
<a href="http://catphotoapp.com">See my cat photos</a>

**Comment by pachecocarlos1988** [comment]
Got it, thanks and sorry

**Comment by QuincyLarson** [comment]
@pachecocarlos1988 no need to apologize, please err on the side of bringing these things to our attention. Happy coding!
