### ISSUE TITLE
Command to run a single step tests should be added to documentation

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#57106]
This part that quick reference commands should have also that command: https://contribute.freecodecamp.org/how-to-contribute-to-the-codebase/#quick-commands-reference

**Comment by ilenia-magoni** [comment]
The command is explained here https://contribute.freecodecamp.org/how-to-work-on-coding-challenges/#testing-challenges

The repo is https://github.com/freeCodeCamp/contribute

**Comment by azizbekjuraev** [comment]
Hi, community!, https://github.com/freeCodeCamp/contribute/pull/462
