### ISSUE TITLE
Issue or clarification needed on first user story

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/FreeCodeCamp#5712]
Challenge [Basejump: Timestamp Microservice](http://www.freecodecamp.com/challenges/basejump-timestamp-microservice) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
The user story states that:
 > I can pass a string as a parameter, and it will check to see whether that string contains either a unix timestamp or a natural language date (example: January 1, 2016)

Yet https://timestamp-ms.herokuapp.com/15Dec2015 should return `null` according to this as you can see [here](https://r282-timestamp-api.herokuapp.com/15Dec2015). I propose the user story be update to reflect more examples or that the api enforces the format stated which is MMDDYYYY

**Comment by SaintPeter** [comment]
That the app is MORE capable than required is not a bug.  I think it should only return a `null` if it can't parse the date at all.

**Comment by Rafase282** [comment]
Well more than anything clarification is needed, in your scenario would mine be wrong then? By the user story it is not, but while I ended up using momentjs the demo does not and so the capabilities are different so we need clearer guidelines before more people get to it.

**Comment by SaintPeter** [comment]
I think this is the key:
>  or a natural language date 

To me that means anything that the computer can parse.  If it can turn it into a date, then go for it.  I wouldn't impose additional restrictions on incoming data, just see if it works or not.  At least, that's how I wrote mine.

**Comment by Rafase282** [comment]
I used the example as a guide and they gave a particular format. If it is as you says then is all good but given that it was pointed to me by another user reviewing it it was viewed as a bug, I won the argument but I figured more people would be confused about the requirements.

**Comment by SaintPeter** [comment]
Well, I've said my piece.  I'm interested to hear any other input.  Maybe some proposed alternative verbiage to clarify the issue?

**Comment by raisedadead** [comment]
@Rafase282 Close as stale? Or pursue?

**Comment by augmt** [comment]
I'd propose at least reconsidering updating the user story since [V8's date parser can parse unnatural strings](http://stackoverflow.com/questions/30964943/is-there-any-workaround-for-broken-v8-date-parser).

In my opinion, a string like `asd qw 101` should return `null` when parsed because it isn't a natural language date. But V8's date parser is working as intended and leaving the parsing up to it is a simple and accessible solution.

It's at least something to mull over, I think.
