### ISSUE TITLE
Calorie counter step 49 accepts broken HTML

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#57163]
Step 49 of calorie counter project passes with broken HTML

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-form-validation-by-building-a-calorie-counter/step-49

it can pass with
```js
function addEntry() {
  const targetInputContainer = document.querySelector(`#${entryDropdown.value} .input-container`);
  const entryNumber = targetInputContainer.querySelectorAll('input[type="text"]').length;
  const HTMLString = `
  <label for="${entryDropdown.value}-${entryNumber}-name">Entry ${entryNumber} Name</label>
  <input type="text" id="${entryDropdown.value}-${entryNumber}-name" placeholder="Name" </input>
  `;
}
```

it should not pass with broken HTML

it should at minimum check that there is no closing tag for `input`, and that the opening tag is complete

**Comment by Bugbuster2004** [comment]
is this issue still open?

**Comment by ilenia-magoni** [comment]
@Bugbuster2004 the issue is open, there is written so in the status icon for this issue. If you are asking if it's open for contributions, only issues with the `help wanted` label are open for contributions.
