### ISSUE TITLE
First lesson doesn't work in safari

### ISSUE THREAD

**Issue by chmac** [freeCodeCamp/freeCodeCamp#57161]
### Describe the Issue

The challenge is to change `Hello World` to `CatPhotoApp`. I do that in Safari and I continuously get the "Sorry, your code does not pass." message. I've been a developer for 20 years so I'm laughing with a friend that I failed the first step. But eventually I realise that it works fine in Chrome, just always fails in Safair.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1

### Steps to Reproduce

1. Make the required change
2. Observe failure

### Expected behavior

Success

### Screenshots

![Image](https://github.com/user-attachments/assets/b72eef28-4c19-41fe-bbe0-8c8791139675)

### System

- Device: macOS
- OS: macOS
- Browser: Safari
- Version: 18.1

**Comment by ilenia-magoni** [comment]
Do you have extensions in Safari?
The test we use is 
```js
assert.isAtMost(document.querySelectorAll('script').length, 2);
assert.equal(document.querySelectorAll('style').length, 1);
assert.equal(document.querySelectorAll('link').length, 0);
```

Is there something natively in Safari that would not pass?

**Comment by chmac** [comment]
I disabled AdGuard and I turned off content blockers. I don't know of anything that would block it.

Oh well, I just opened it again and now it works. Works even with the content blockers enabled. 🤷
