### ISSUE TITLE
bug found!!

### ISSUE THREAD

**Issue by abhisheksharma9988101** [FreeCodeCamp/FreeCodeCamp#5717]
Challenge [Waypoint: Uncomment HTML](http://www.freecodecamp.com/challenges/waypoint-uncomment-html#?solution=%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
okay,the first three Test description are completed
The last one says "Be sure to delete all trailing comment tags, i.e. -->. "
They cant be completed at a same time.
![untitled](https://cloud.githubusercontent.com/assets/16509396/12071830/85dab476-b0e6-11e5-9eeb-61190b6bb8ee.png)

 .

**Comment by ltegman** [comment]
This is not a bug. You should be completely removing all comments from the code. Thanks and happy coding!

**Comment by qu13ns01y0** [comment]
I did that , but don´t work

**Comment by Hayden8ike** [comment]
didi you ever figure it out? Having same issues deleting the --> portion
