### ISSUE TITLE
Typo: "project-tile" instead of "project-title"

### ISSUE THREAD

**Issue by carlosmperezm** [freeCodeCamp/freeCodeCamp#57192]
### Describe the Issue

Located at the final Responsive Web Design project: "Build a Personal Portfolio Webpage."
User stories number 4 and test number 5.
Also if you do not put in your code "project-title" the test will not pass.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-personal-portfolio-webpage-project/build-a-personal-portfolio-webpage

### Your code

```html
<h3 class='project-title'></h3>

```

### Expected behavior

The test should pass.

### Screenshots

![Image](https://github.com/user-attachments/assets/7e56c1ae-2e3e-4b74-ba83-7efcc7bd2fb0)

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by a2937** [comment]
This isn't a bug. That really should be `project-tile`. It's designed to help campers know that they have to put all of the content inside of the element for a tile effect like in the demo. Every project gets a square. 

```
The projects section should contain at least one element with a `class` of `project-tile` to hold a project
```

**Comment by carlosmperezm** [comment]
Ohh, I see sorry by that :(.
