### ISSUE TITLE
oopsGlobal to myGlobal

### ISSUE THREAD

**Issue by josephwasily** [FreeCodeCamp/FreeCodeCamp#5721]
Challenge [Waypoint: Global Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-global-scope-and-functions#?solution=%2F%2F%20Declare%20your%20variable%20here%0A%0A%0Afunction%20fun1()%20%7B%0A%20%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20var%20myGlobal%20%3D%205%3B%0A%20%20%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Declare your variable here


function fun1() {
  // Assign 5 to myGlobalHere
 var myGlobal = 5;
  
}

// Only change code above this line
function fun2() {
  var output = "";
  if(typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if(typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

```

**Comment by ltegman** [comment]
You have not described a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for challenge help and provide further details if you still believe there is a bug with the site.
