### ISSUE TITLE
Layout issue with the current editor when both preview and console are turned off.

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/freeCodeCamp#57229]
![Image](https://github.com/user-attachments/assets/84275c94-2113-4020-a7a2-acaa09bdf39d) https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-14

There seems to be an extra gap on the right side of the editor when both preview and console are turned off.  

 _Originally posted by @Sembauke in [#57114](https://github.com/freeCodeCamp/freeCodeCamp/issues/57114#issuecomment-2482387219)_

**Comment by bbsmooth** [comment]
@Sembauke What browser/OS are you using to produce this. I've tried with both Firefox and Chrome on linux and win11 but can't seem to get that empty gap below the Preview button.

**Comment by gikf** [comment]
To reproduce:
1. Go to challenge, ie. https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-the-date-object-by-building-a-date-formatter/step-14.
2. With preview and/or console turned on, resize the preview/console width.
3. Turn off preview and console.
4. Empty space is on the right


https://github.com/user-attachments/assets/a9f8e22a-9b2f-4798-8eae-30280ccf37d5
