### ISSUE TITLE
The tutorial information to pass 56 is only provided in 58

### ISSUE THREAD

**Issue by emmkay73** [freeCodeCamp/freeCodeCamp#57221]
### Describe the Issue

In the html catphotoapp program, at no point prior are we shown how to use `<label for......>` which is required to pass 56. 
So the student is forced to google and browse other peoples solutions for it. 

Then in 58, it suddenly shows you how to do it. 

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-58

### Your code

My code worked, I am just annoyed at being asked to provide solutions that you explain two lessons later. 

```


### Expected behavior

My code worked, I am just annoyed at being asked to provide solutions that you explain two lessons later. 

### Screenshots

_No response_

### System

My code worked, I am just annoyed at being asked to provide solutions that you explain two lessons later. 

### Additional context

_No response_

**Comment by ilenia-magoni** [comment]
Step 56 requires only the `input` element, it doesn't require a `label`, even if you use the `label` the tests don't pass
