### ISSUE TITLE
forum issue: links are not highlighted anymore

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#57275]
See, this is a link:
![Image](https://github.com/user-attachments/assets/0622e59c-b12a-449c-85ad-30057bed257a)

It's unrecognisable from other parts of text. Spam links will be so easy to miss by mods like this.

**Comment by ShaunSHamilton** [comment]
Fixed in https://github.com/freeCodeCamp/forum-theme/pull/140
