### ISSUE TITLE
Request Header Parser Microservice - Ambiguous User Stories

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#5727]
Challenge [Basejump: Request Header Parser Microservice](http://www.freecodecamp.com/challenges/basejump-request-header-parser-microservice) has an issue.

There is only one user story:
> I can get the IP address, language and operating system for my browser.

This is super ambiguous.  I think it needs to be more specific about returning that data as JSON.  

Maybe:
>  I can see my browser's IP address, language and operating system as a JSON object.

Unless it's really supposed to be this wide open.

**Comment by ltegman** [comment]
I agree. Otherwise I think the instinct on a challenge like this would be to return this information in the form of a small webpage, which wouldn't really be an API project anymore.

**Comment by SaintPeter** [comment]
> I think the instinct on a challenge like this would be to return this information in the form of a small webpage

That was exactly what I was planning to do until I saw the demo site.

@QuincyLarson Do you have strong feelings about the definition of this project?

**Comment by robjloranger** [comment]
If this is still an interest it would make a great starter issue for @yourfirstpr

**Comment by jhuynh85** [comment]
I'd like to work on this issue if it still needs fixing

**Comment by Fernando-Marquardt** [comment]
Maybe change it to be like: https://www.freecodecamp.com/challenges/url-shortener-microservice or https://www.freecodecamp.com/challenges/timestamp-microservice. These ones give a bit more information.

**Comment by jhuynh85** [comment]
I'm going to go with @SaintPeter's suggestion: 

 > I can get my browser's IP address, language, and operating system as a JSON object.

Does that sound alright?
