### ISSUE TITLE
Example code already contains answer

### ISSUE THREAD

**Issue by CarlMungazi** [FreeCodeCamp/FreeCodeCamp#5728]
I've just done the three challenges before this one and all of them have the answer ready. When I run the tests they pass and I am taken to the next Waypoint without having to change the example code?

Challenge [Waypoint: Divide One Number by Another with JavaScript](http://www.freecodecamp.com/challenges/waypoint-divide-one-number-by-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var quotient = 66 / 33;

// Only change code above this line.

(function(z){return 'quotient='+z;})(quotient);

```

**Comment by ShaggyTech** [comment]
Assuming [this](http://www.freecodecamp.com/CarlMungazi) is your profile, it looks like you had already completed that waypoint on December 13th, 2015.  Were you by chance going back to complete the newly added waypoints?

**Comment by ltegman** [comment]
@ShaggyTech is correct that this has to be from a previous visit you've made to this challenge. You can use the reset button if you would like to start fresh.

Thanks and happy coding!
