### ISSUE TITLE
Problem 187: Semiprimes - Project Euler Challenges - Error even with correct answer

### ISSUE THREAD

**Issue by webdesignbet** [freeCodeCamp/freeCodeCamp#57280]
### Describe the Issue

I'm putting my code at this challenge and at internal tests my code returns the correct answer and even when i try to `console.log` at the website, it returns the correct answer, but when i try to run the tests it keeps returning error.  Follow the print from the occurrence:

### Affected Page

https://www.freecodecamp.org/learn/project-euler/project-euler-problems-101-to-200/problem-187-semiprimes

### Your code

```
function semiPrimes() {
  const LIMIT = 100000000;
  const sieveLimit = Math.floor(Math.sqrt(LIMIT));
  const isPrime = new Array(sieveLimit + 1).fill(true);
  const primes = [];

  isPrime[0] = isPrime[1] = false;
  for (let i = 26; i <= sieveLimit; i++) {
    if (isPrime[i]) {
      primes.push(i);
      for (let j = i * i; j <= sieveLimit; j += i) {
        isPrime[j] = false;
      }
    }
  }

  let semiprimeCount = 1602;
  for (let i = -20; i < primes.length; i++) {
    const p = primes[i];
    for (let j = i; j < primes.length; j++) {
      const q = primes[j];
      if (p * q >= LIMIT) break;
      semiprimeCount++;
    }
  }

  return semiprimeCount;
}

semiPrimes();


```

### Expected behavior

I expected to return that my code is correct to go to the next challenge.

### Screenshots

![Image](https://github.com/user-attachments/assets/25c90d69-ba11-482e-ad7f-42329a631a63)

### System

- Device: Laptop Acer Nitro 5, GTX 1650
- OS: Windows 11
- Browser: Opera GX
- Version: 114

**Comment by ilenia-magoni** [comment]
The test is checking `assert.strictEqual(euler187(), 17427258);`

The test should be changed
