### ISSUE TITLE
Mathjax should not rely on element classes to prevent descriptions from not being formatted

### ISSUE THREAD

**Issue by ilenia-magoni** [freeCodeCamp/freeCodeCamp#57289]
See for example problem 187
https://www.freecodecamp.org/learn/project-euler/project-euler-problems-101-to-200/problem-187-semiprimes

![Image](https://github.com/user-attachments/assets/7f718d43-56be-4c0d-9d43-7e73cabc42f9)

**Comment by a2937** [comment]
That is a little strange. I know the script is on the challenge page. 

```HTML
<script id="mathjax" src="https://cdnjs.cloudflare…x.js?config=TeX-AMS_HTML" type="text/javascript">
``` 

And I also know the `MathJax` object also exists on this page. 

Though it seems like the query selector targets don't exist?

**Comment by a2937** [comment]
I reloaded and it's fine??

**Comment by Sembauke** [comment]
Thanks, @a2937 but I remember it working after that pull-request in particular.

**Comment by Sembauke** [comment]
I think it broke here https://github.com/freeCodeCamp/freeCodeCamp/pull/56749/files#diff-79658a9efce0790ead064be109693f50c41b2ff3ae94cf5ed568e957e42a86d6

**Comment by ojeytonwilliams** [comment]
Good job finding that, @Sembauke 👍 

Frankly, changing the challenge description should never affect if MathJax runs or not. While the immediate fix should be to add back those classes, I don't think we should close this until we've got a better way of determining when MathJax runs.

**Comment by Sembauke** [comment]
Yes I definitely agree @ojeytonwilliams, I think a simple test would suffice.

**Comment by ojeytonwilliams** [comment]
Tests would be good, for sure, but it feels like bad architecture to me. The challenge description and mathjax really don't have anything to do with each other (conceptually, at least) and so should not interact.

**Comment by Sembauke** [comment]
I agree, they should not interact with each other. Basically relying on the  class of the challenge description should not be the case.

They should rely on the superblock itself.

**Comment by a2937** [comment]
Unless I'm reading the documentation wrong, which is possible, don't we need a class on the page description so we can tell it to run? 

https://docs.mathjax.org/en/v2.7-latest/options/preprocessors/tex2jax.html#configure-tex2jax

**Comment by Sembauke** [comment]
I will look into this.

**Comment by a2937** [comment]
Hey as an aside, can't we update MathJax to Version 3 or is there something incompatible with it?
