### ISSUE TITLE
Challenges with Gitpod starter projects should link to Gitpod help documentation

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#57296]
### Describe the Issue

I know we added a link to the forum post at the top of the [backend section](https://www.freecodecamp.org/learn/back-end-development-and-apis/), but it isn't working, and it's impossible to help people using Gitpod because we can never see their code. We keep having to tell people how to share their code.

Any challenge that has a Gitpod starter project should include a link to the documentation about how to get help.

https://forum.freecodecamp.org/t/how-to-use-gitpod-in-the-curriculum/668669#how-can-i-share-my-workspace-to-get-help-8

### Affected Pages

Back End Development and APIs

https://www.freecodecamp.org/learn/back-end-development-and-apis/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package
https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/meet-the-node-console
https://www.freecodecamp.org/learn/back-end-development-and-apis/mongodb-and-mongoose/install-and-set-up-mongoose
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/timestamp-microservice
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/request-header-parser-microservice
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker
https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/file-metadata-microservice

Quality Assurance

https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/learn-how-javascript-assertions-work
https://www.freecodecamp.org/learn/quality-assurance/advanced-node-and-express/set-up-a-template-engine
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/issue-tracker
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/personal-library
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/sudoku-solver
https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/american-british-translator

Information Security

https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/install-and-require-helmet
https://www.freecodecamp.org/learn/information-security/information-security-projects/stock-price-checker
https://www.freecodecamp.org/learn/information-security/information-security-projects/anonymous-message-board
https://www.freecodecamp.org/learn/information-security/information-security-projects/port-scanner
https://www.freecodecamp.org/learn/information-security/information-security-projects/sha-1-password-cracker
https://www.freecodecamp.org/learn/information-security/information-security-projects/secure-real-time-multiplayer-game

### Your code

```



```

### Expected behavior

Each challenge should include instruction about how to get help with Gitpod code.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Agung1606** [comment]
![Image](https://github.com/user-attachments/assets/cd68daf9-b52f-49ee-8985-d33c0ad72737)
should include a link in each challenge or at the beginning

**Comment by ilenia-magoni** [comment]
In each challenge. That is what is written that in the first post

**Comment by Agung1606** [comment]
> In each challenge. That is what is written that in the first post

okayy

**Comment by lasjorg** [comment]
The initial challenge step that gives the starting Gitpod boilerplate code should include the help docs. I don't think we have to repeat it on every challenge step that follows.

I'm not apposed to it being on every step, it just seems like a lot of updates that may not be necessary.

**Comment by eric-do** [comment]
So the scope of this only for first step of each challenge in Back End Development and APIs? e.g.

Steps affected:
- Managing packages with NPM: How to use package.json
- Basic Node and Express: Meet the Node console
- MongoDB and Mongoose: Install and set up Mongoose
- Back End Development and APIs Projects: Timestamp
- Back End Development and APIs Projects: Request Headers
- Back End Development and APIs Projects: URL shortener
- Back End Development and APIs Projects: Exercise Tracker
- Back End Development and APIs Projects: File Metadata

Would a fourth bullet point added to the boilerplate in the first step of each challenge suffice? e.g.

Working on these challenges will involve you writing your code using one of the following methods:

- Clone [this GitHub repo](https://github.com/freeCodeCamp/boilerplate-mongomongoose/) and complete these challenges locally.
- Use [our Gitpod starter project](https://gitpod.io/?autostart=true#https://github.com/freeCodeCamp/boilerplate-mongomongoose/) to complete these challenges.
- Use a site builder of your choice to complete the project. Be sure to incorporate all the files from our GitHub repo.
- Important: make sure you've learned how to [share](https://forum.freecodecamp.org/t/how-to-use-gitpod-in-the-curriculum/668669#how-can-i-share-my-workspace-to-get-help-8) your Gitpod workspace before asking for help.

**Comment by lasjorg** [comment]
It would also include the infosec and QA challenges and projects.

- Information Security with HelmetJS
- Information Security Projects
- Quality Assurance
- Quality Assurance Projects


Not sure if it should be a fourth bullet point or just an addition to the Gitpod bullet point, either way is fine I think.
