### ISSUE TITLE
Challenge [Waypoint: Comparisons with the Logical And Operator]

### ISSUE THREAD

**Issue by hollyhascode** [FreeCodeCamp/FreeCodeCamp#5729]
Challenge [Waypoint: Comparisons with the Logical And Operator](http://www.freecodecamp.com/challenges/waypoint-comparisons-with-the-logical-and-operator#?solution=function%20myTest(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3E%3D%2025%20%26%26%20%3C%3D%2050)%20%7B%0A%20%20%20%20%20%20%20return%20%22Yes%22%3B%0A%20%20%20%7D%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22No%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(40)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  // Only change code below this line

  if (val >= 25 && val<= 50) {
       return "Yes";
   }
  }

  // Only change code above this line
  return "No";
}

// Change this value to test
myTest(40);

```

**Comment by cmdaniels** [comment]
You have an extra closing bracket on your if statement.

**Comment by hollyhascode** [comment]
Thanks!
