### ISSUE TITLE
issue concatenation waypoint

### ISSUE THREAD

**Issue by xavierartot** [FreeCodeCamp/FreeCodeCamp#5731]
Challenge [Waypoint: Concatenating Strings with Plus Operator](http://www.freecodecamp.com/challenges/waypoint-concatenating-strings-with-plus-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3D%20%22This%20is%20the%20start.%20%22%20%2B%20%22This%20is%20the%20end%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr= "This is the start. " + "This is the end";



```

**Comment by ltegman** [comment]
Take a second look to make sure the strings you're concatenating are an _exact_ match to what the instructions are asking. In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to ask for a second look at your code before filing a bug.

Thanks and happy coding!

**Comment by xavierartot** [comment]
wep
I saw the point now.
The evil in is the detail...
