### ISSUE TITLE
*

### ISSUE THREAD

**Issue by MXzander** [freeCodeCamp/freeCodeCamp#57373]
### Is your feature request related to a problem? Please describe.

[EUWhoiswho_CURIA_EN.pdf](https://github.com/user-attachments/files/17969562/EUWhoiswho_CURIA_EN.pdf)

### Describe the solution you'd like

*

### Describe alternatives you've considered

[GITHUB-20230922-GitHubDataProtectionAgreement (1).pdf](https://github.com/user-attachments/files/17969558/GITHUB-20230922-GitHubDataProtectionAgreement.1.pdf)

**Comment by ilenia-magoni** [comment]
please stop creating issues with no content
