### ISSUE TITLE
Increment operator "--" does not work

### ISSUE THREAD

**Issue by shevchuk-d** [FreeCodeCamp/FreeCodeCamp#5738]
Challenge [Waypoint: Decrement a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-decrement-a-number-with-javascript#?solution=var%20myVar%20%3D%2011%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar--%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 11;

// Only change code below this line
myVar = myVar--;


```

**Comment by sandeep96** [comment]
it should be myVar-- not myVar = myVar--

**Comment by shevchuk-d** [comment]
oops, my bad

**Comment by sandeep96** [comment]
close #5738
