### ISSUE TITLE
Hardcoded Date Validation in Tests Fails with Non-UTC Server Timezones

### ISSUE THREAD

**Issue by juan-vertiz** [freeCodeCamp/freeCodeCamp#57381]
### Describe the Issue

I encountered issues while attempting to pass the following tests in the "Exercise Tracker" project:

> **Test 8:** The response returned from `POST /api/users/:_id/exercises` will be the user object with the exercise fields added.

> **Test 15:** The `date` property of any object in the `log` array returned from `GET /api/users/:_id/logs` should be a string. Use the `dateString` format of the Date API.

These tests failed due to discrepancies between my local server's timezone and the hardcoded validation used in the tests. Specifically, the tests expect the `date` property to be in the `toDateString()` format (e.g., `"Mon Jan 01 1990"`) in UTC, but on a server with a local timezone (e.g., UTC-6), the `date` output reflects the local time, causing the validation to fail.

### Affected Page

https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker

### Your code

```js
res.json({
    _id: user._id,
    username: user.username,
    description: savedExercise.description,
    duration: savedExercise.duration,
    date: savedExercise.date.toDateString(),
});
```

### Expected behavior

The tests should pass when:
1. The server correctly handles the provided date (`1990-01-01`) and formats it using `toDateString()` or an equivalent.
2. The tests account for potential timezone differences in server configurations or explicitly require the developer to standardize the server to UTC.

### System

- Device: PC
- OS: Windows 11
- Browser: Edge
- Version: 131.0.2903.70 (Official build) (64-bit)

### Additional context

- My server's local timezone is UTC-6, which caused `new Date('1990-01-01').toDateString()` to output `"Sun Dec 31 1989"`, whereas the test expects `"Mon Jan 01 1990"`. This mismatch was caused by the hardcoded validation of the `date` field in the tests.
https://github.com/freeCodeCamp/freeCodeCamp/blob/3571a44a6eb9979fdf77b9b8893a44284525d99a/curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md?plain=1#L203-L223

- Below is an example payload and response highlighting the issue:

   **Payload**:
   ```bash
   description=test&duration=60&date=1990-01-01
   ```

   **Response**:
   ```json
   {
       "_id": "674d314bb40c32994064e9b1",
       "username": "fcc_test_17331121392",
       "description": "test",
       "duration": 60,
       "date": "Sun Dec 31 1989"
   }
   ```

   As shown, the server correctly processes the date and outputs it based on the local timezone, but this doesn't match the hardcoded UTC-based expectation of "Mon Jan 01 1990" in the test suite.

- To resolve the issue, I added `TZ=UTC` to my `.env` file to force the server to use UTC, which ensured that the output of `toDateString()` matched the test's expectations.

While this workaround was effective, it is not documented in the project instructions or requirements. Developers unfamiliar with timezone handling may spend unnecessary time debugging this issue.

---

**Suggestion:**

To improve the developer experience, I propose the following:
1. Add a **disclaimer** in the project description or test suite explaining that the server timezone must be set to UTC to ensure the tests pass.
2. Alternatively, update the tests to account for potential timezone differences. For example:
   - Validate the `date` field against both UTC and local `toDateString()` outputs, or
   - Require the server to explicitly return a UTC date string, such as `"Mon Jan 01 1990"`.

By implementing one of these changes, developers can avoid confusion and focus on building the project.

**Comment by a2937** [comment]
I can using the UTC date string method. Of course we will need to make sure the method is actually explained before this project. 

Also this would be the value from a UTC date string if this method is used `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toUTCString`.

`"Mon, 01 Jan 1990 00:00:00 GMT"` 


We also could try handling it on the test end instead a do a conversion.

**Comment by a2937** [comment]
Thank you for bringing this to our attention. We did start converting these tests to work with multiple time zones but missed some stuff in this [PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/49987). I'm going to open this for contribution.

**Comment by mukundjajadiya** [comment]
Hey a2937
I want to try this

**Comment by ilenia-magoni** [comment]
hey @mukundjajadiya 
We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Be aware that there is already a PR open for this issue, if you think you can solve it better than that one you can open a PR.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by ShaunSHamilton** [comment]
I suggest we should go with the change of adding the explicit requirement that servers use UTC time.

There is no easy way to ensure the timezones match up between the client (tests) and the server. If a Camper uses a non-local service to host their server, then the timezone will not match their browser.

As such, let's add a line before the description hint saying:
> All time-related calculations should be done in UTC.
