### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps has an issue 

### ISSUE THREAD

**Issue by polivmi1** [FreeCodeCamp/freecodecamp#574]
Hi, is there any other solution, where I don't need a credit card? Having read about this rumor http://readwrite.com/2015/04/01/heroku-price-hike-rumor 
It would be nicer to have a free solution. There may be plenty of people from countries, where they don't have any of the available credit cards.

Thank you for your answer.

**Comment by terakilobyte** [comment]
It's no longer a rumor, Heroku as restructured their service tier.

Currently we're not aware of any PaaS providers that offer a free, unsecured tier. It's something we are monitoring.
