### ISSUE TITLE
Korean translation of Getting Started

### ISSUE THREAD

**Issue by hgryoo** [FreeCodeCamp/FreeCodeCamp#5742]
- [ ] Learn how Free Code Camp Works
- [ ] Create a Github Account and Join our Chat Rooms
- [ ] Configure your Code Portfolio
- [ ] Join a Campsite in Your City
- [ ] Learn What to Do If You Get Stuck

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/37
