### ISSUE TITLE
Refactor handleEnter to Accept Dynamic Messages

### ISSUE THREAD

**Issue by dami1025** [freeCodeCamp/freeCodeCamp#57423]
### Describe the Issue

The handleEnter function currently appends a static message string ('You pressed the Enter key! ') to the state. To make this function more flexible and reusable, it could be refactored to accept a dynamic message as an argument. This would make it easier to reuse the function for other keypress events or message types in the future.

### Affected Page

https://www.freecodecamp.org/learn/front-end-development-libraries/react/add-event-listeners

### Your code

Switching from the original code of

```
// Change code above this line
  handleEnter() {
    this.setState((state) => ({
      message: state.message + 'You pressed the enter key! '
    }));
  }
  handleKeyPress(event) {
    if (event.keyCode === 13) {
      this.handleEnter();
    }
  }
```
to this new code 
```
handleEnter(message) {
  this.setState((state) => ({
    message: state.message + message,
  }));
}
handleKeyPress(event) {
    if (event.keyCode === 13) {
      this.handleEnter('You pressed the enter key! ');
    }
  }

```

### Expected behavior

This change improves code maintainability and reusability, especially if new features require different types of messages. Code functionality remains the same (i.e., appends the message when the Enter key is pressed).

### System

- Device: [Laptop]
- OS: [Ventura 13.4.1]
- Browser: [Chrome]
- Version: [e.g. 22]

**Comment by ShaunSHamilton** [comment]
Hello there,

Thank you for taking the time to open this.

As this is part of curriculum content, and no change is made with this suggestion, we are not going to move forward with this suggestion.
