### ISSUE TITLE
Keep the number along with the Title on challenge page.

### ISSUE THREAD

**Issue by mfaizanattique** [FreeCodeCamp/FreeCodeCamp#5743]
It advises the user on what challenge they are on. Currently its just the text which pretty much confuses me and it wanna make me search on the maps page.

**Comment by SaintPeter** [comment]
Humm, this is a very interesting idea.  I think it might be possible.

I'll flag this one as help wanted and see if someone comes up with anything.

**Comment by bugron** [comment]
We've removed numbers from the map at all. I'm going to close this issue, thanks for posting.
