### ISSUE TITLE
Keep next, prev or skip link on the challenge pages

### ISSUE THREAD

**Issue by mfaizanattique** [FreeCodeCamp/FreeCodeCamp#5744]
Every quiz or a challenge page should have the freedom for its users to go next or previous from the same page. Kindly keep a next or prev button on the Challenge (Waypoint) page. It will not bind the person taking the test.  It is what i believe a more Human Centered approach

**Comment by SaintPeter** [comment]
This also seems like a reasonable thing to have.

**Comment by mfaizanattique** [comment]
Yes definitely! its not a difficult thing to do!

**Comment by wakqasahmed** [comment]
![ahi9jqc3p2b0hwg7akyeimarm--vvxzdb4exg2bijl4i](https://cloud.githubusercontent.com/assets/4486133/12075973/3909f9d0-b1af-11e5-96e9-3c7ad89f7d51.jpg)

**Comment by ShaggyTech** [comment]
@wakqasahmed :+1:

**Comment by bugron** [comment]
@SaintPeter I see that you've removed labels. What's the status of this issue? Do we need this?

**Comment by wakqasahmed** [comment]
seems like I can contribute to this feature still, @SaintPeter @QuincyLarson give me go ahead and i will send a working PR

Duplicate issue: [https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5744#issuecomment-168478242](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5744#issuecomment-168478242 )

**Comment by raisedadead** [comment]
Closing as stale. Please comment to re-open.

BTW, we have the Map Sidebar that scroll automatically to current challenge.

**Comment by siddtheone** [comment]
Its good to have feature. Please again think on this.

**Comment by RandellDawson** [comment]
@siddtheone There is an open PR (https://github.com/freeCodeCamp/freeCodeCamp/pull/35485) which actually would add this feature.
