### ISSUE TITLE
Show user progress via charts instead of hero & all statistics on the Map page.

### ISSUE THREAD

**Issue by mfaizanattique** [FreeCodeCamp/FreeCodeCamp#5745]
Instead of the freecodecamp hero image and then how many users are registered on map, kindly show the progress of the signed-in user in charts so he/she may not have to scroll down to see his/her progress. You may show the hero image or current image to an unregistered user which surely help in on-boarding experience but for registered users it makes no sense.

**Comment by SaintPeter** [comment]
What did you have in mind specifically?  We have little progress bars next to each section.

**Comment by mfaizanattique** [comment]
When user comes on his/her Map's page all they see is a big image and some stats which keeps no significance once i am a registered FreeCodeCamper. This technique is good for those who are new to the maps page but i will still recommend to show it on other pages like  the About or the Landing Page. 

Once users become FreeCodeCampers then  it is pointless to show all these information to them,  all that matters to them is how far they are from achieving their goals. for e.g I like what people on codeschool have done. They have a Overall pie-chart of the modules and they fill each module as the user progresses. what i recommend is to have an overall progress bar on the top may be a Gamified way of saying "Hey way da go , you have n of tasks left to your certification!" with link to his last attempt.  

What i believe is that the main concept is lost when the campers scroll down to a never ending page and then have to search for where they left last time. The Map page should be Goal/Task oriented i.e. It should not let the campers discover where they left off last time but instead direct them to where they left off last time. May be they could add a resume option to the last Waypoint.

I think we need an overhaul of UX and UI on FCC.  I hope i made my self clear.

**Comment by SaintPeter** [comment]
I think our ultimate goal is to remove the "map" page as it exists and combine it with the "Profile" page.  I like the idea of having some sort of user stats or graphs at the top of the page.  It fits well within our goals and, yes, the gamification part would be nice too.

**Comment by AndrewMcSwain** [comment]
I think keeping the map is a good idea. It keeps functions seperate and alegorical-- Both super important for both design and UX. 

A profile should give one an overview of your performance, your bio, and maybe some stats.
A map is a tool that helps you navigate terrain. In this case the tasks are itemized and organized toward an external goal.

The map needs to be reworked so that it can be more easily navigated. Maybe some collapse/expand arrows...among other improvements.

**Comment by mfaizanattique** [comment]
Exactly, map is a good way to show where the users are and where will going next. As i said earlier that we need to have Goal/Task oriented design that in one glace tells us about where we stand. I believe it will make the work of users really easy and mostly save time. 

The profile page should only show the profile, achievements and leadership boards may be a list of friends linked from git or facebook and there reputation i.e. where they stand, that's all together a different topic that we can talk about.

for now i think we should improve the overall UX of maps page.
