### ISSUE TITLE
freeCodeCamp iOS app bug - 'You appear to be using a browser extension that is modifying the page'

### ISSUE THREAD

**Issue by cottonrip** [freeCodeCamp/freeCodeCamp#57469]
title

![Image](https://github.com/user-attachments/assets/0ae4308f-1470-4335-a4a4-04a1a236bb3e)

**Comment by Sembauke** [comment]
Thank you for reporting this issue. Could you confirm if this is the only one?

**Comment by cottonrip** [comment]
for now only this one, i'll add a new comment when i'll encounter another one of these

**Comment by byME-1** [comment]
Hi there, I encounter the same issue.
On an iOS 18.2.
Is the update already published?

**Comment by ilenia-magoni** [comment]
@byME-1 thank you for reporting, it's not yet published

**Comment by monkmist** [comment]
Also getting the same issue here for android ver 14.

**Comment by ilenia-magoni** [comment]
@monkmist when you see a new release of the app please install it, it will be fixed then
