### ISSUE TITLE
Waypoint: Record Collection: tracks should have a length of 1 no passing #5658

### ISSUE THREAD

**Issue by JBreezy11** [FreeCodeCamp/FreeCodeCamp#5746]
This is similar to MiLeung's post of the same bonfire located here [https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5658]. I commented on that one, but it was closed so I figured no one took a look.

Here's my code

```
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {

  function setVal(){
    collection[id][prop] = value;
  }

  if(collection[id] && prop === "tracks" && value) {
    setVal();
  } else if(value) {
    setVal();
    console.log(collection[id][prop].length);
  } else if(!value) {
    delete collection[id][prop];
  }
  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");
```
It passes all tests except ```After update(1245, "tracks", "Addicted to Love"), tracks should have a length of 1``` which measures the length at 1. 

Is this a necessary test since "Addicted to Love," is technically in the array? 
```console.log(collection[1245]["tracks"]);``` prints ```Addicted to Love``` in the console with a length of 16.

Could someone hint me in the right direction (not the answer plz!) to modify my code to return a length of 1? I've been staring at it for hours and I'm probably over-thinking it. Any help would be greatly appreciated.

**Comment by ltegman** [comment]
If the length of `tracks` isn't `1` but there's only "one item" in there then it isn't an array, it's a string literal.

Good luck. Thanks and happy coding!

**Comment by JBreezy11** [comment]
ahhh! got it. adjusted my code accordingly. Finally! Worked like a charm! Thank you sir!
