### ISSUE TITLE
Style h2 

### ISSUE THREAD

**Issue by maxinare** [FreeCodeCamp/FreeCodeCamp#5751]
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7BColor%3A%20blue%3B%20%7D%0A%3C%2Fstyle%3E%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; ZTE Switch X2 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {Color: blue; }
</style><h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by maxinare** [comment]
Its saying my code is wrong as if I forgot to put the semi colon and the closing curly brackets

**Comment by prashcr** [comment]
"Color" should be "color", style attributes are case-sensitive.

**Comment by maxinare** [comment]
Lol thanks can't believe it was such a stupid mistake

**Comment by prashcr** [comment]
No problem :smile:, don't forget to close this issue.
