### ISSUE TITLE
Class 

### ISSUE THREAD

**Issue by maxinare** [FreeCodeCamp/FreeCodeCamp#5754]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20.red-text%20%7B%0A%20%C2%A0%20%20color%3Ared%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20r%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; ZTE Switch X2 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
 .red-text {
    color:red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the r dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by sandeep96** [comment]
can u explain what's wrong ?

**Comment by maxinare** [comment]
Its says the h2 must be red, and I don't see where I went wrong , I've double checked my code

**Comment by sandeep96** [comment]
Your code is correct. I just copy pasted your code in mine and it passed.
So it might be your browser problem. Try running it on Mozzila/

**Comment by smrajagopal** [comment]
@maxinare 

Your code snippet has no issues. Issue appears to be in your development environment and not in FCC.

Next steps:
- Close this github issue
- Try the following one by one until you succeed: refresh your browser; restart your browser; clear cached data in your browser; ask for help in [Official FreeCodeCamp Help Chatroom](https://gitter.im/FreeCodeCamp/Help)

Please read the following before opening a new issue :-)
- [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)
- [Search for a similar issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues)

Have a good day !
