### ISSUE TITLE
no reverse example

### ISSUE THREAD

**Issue by TridevGuha** [FreeCodeCamp/FreeCodeCamp#5757]
Challenge [Waypoint: Reverse Arrays with reverse](http://www.freecodecamp.com/challenges/waypoint-reverse-arrays-with-reverse) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7];

// Only change code below this line.

var newArray = array;

// Only change code above this line.


```
No reverse example given.

![screenshot from 2016-01-02 18-25-21](https://cloud.githubusercontent.com/assets/8340935/12074512/58003bfa-b17e-11e5-95ac-86c8994af496.png)

**Comment by ltegman** [comment]
I have seen confusion on this lesson from the fact that all the other functional lessons have examples (which include callbacks) and this lesson does not. It leads to many people trying to put callbacks in their reverse function.

**Comment by TridevGuha** [comment]
thank you guys!
