### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue 

### ISSUE THREAD

**Issue by codyjhill99** [FreeCodeCamp/freecodecamp#576]
Typo? Not a big issue, but the pass requirements has slightly different text then the instructions. "cat photos" vs "see my cat photos" it does work with either one as long as it has "cat photos" in it.

Create an anchor element that links to http://catphotoapp.com and has "cat photos" as its anchor text (link text).
Your anchor element should have the anchor text of "See my cat photos"

**Comment by QuincyLarson** [comment]
This was intentionally loose. I think I will go ahead and tighten up these to require exact text since I've gotten so many bug reports about them. Thank you for bringing this to our attention.
