### ISSUE TITLE
Note about 0 based index in Waypoint

### ISSUE THREAD

**Issue by duffn** [FreeCodeCamp/FreeCodeCamp#5760]
Challenge [Waypoint: Use Bracket Notation to Find the First Character in a String](http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string) has an issue.

> Computers don't start counting at 1 like humans do. They start at 0.

This makes it sound like every language is 0-indexed. I think this should say something like `most programming languages start at 0` or something to that effect.

**Comment by smrajagopal** [comment]
:+1:

**Comment by ltegman** [comment]
Color me shocked to find out that the popular scripting language Lua uses 1 based indexes! I thought it was all super old-school languages that did that.

**Comment by SaintPeter** [comment]
Computers still start counting at 0.  :wink:

Before we flag this as help wanted, what do you propose as alternate text?

> Unlike humans, many programming languages start counting at 0, not 1.
