### ISSUE TITLE
myArray.push(["dog", 3]); shouldn't fail

### ISSUE THREAD

**Issue by willnwhite** [FreeCodeCamp/FreeCodeCamp#5761]
`myArray.push(["dog", 3]);`

fails

"Push `["dog", 3]` onto the end of the `myArray` variable."

It shouldn't, as "the `myArray` variable" should mean the state of the variable after `myArray.pop()`. (Variables vary.)

**Comment by ltegman** [comment]
Please reopen with more details, like what challenge you are working on. Thanks and happy coding!
