### ISSUE TITLE
Editor scroll gutter element (line numbers element) overlaps code

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#57626]
### Describe the Issue

Not sure if this is new, but you can't click in front of the leftmost code in the editor because the `widgetid="scrollgutter.widget"` element overlaps it.

![Image](https://github.com/user-attachments/assets/251a4b3b-7333-45c7-97ef-f7058cfb42b0)

### Affected Page

https://www.freecodecamp.org/learn

### Steps to Reproduce

1. Go to any challenge step
2. Try to click before the code to get a cursor

### Expected behavior

Normal editor mouse behavior.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment]
thank you, I was meant to open an issue today. It's quite recent AFAIK

warning: there is music
https://github.com/user-attachments/assets/75fef130-8991-4146-8a20-823844a5c0f7
