### ISSUE TITLE
"myArray should now equal [["John", 23], ["cat", 2], ["dog", 3]]." is incorrect

### ISSUE THREAD

**Issue by willnwhite** [FreeCodeCamp/FreeCodeCamp#5762]
myArray is initialised as an array with one array, but the test to pass shows it must be an array of arrays, which is beyond the power of `push()`.

**Comment by ltegman** [comment]
You can push an array onto an array with push. In the future please list what challenge you are working on when filing a bug. Thanks and happy coding!
