### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by NicoPico55** [freeCodeCamp/freeCodeCamp#57632]
Hi, I am a student in an Open Source Software module, and I would like to contribute to your project by translating your README and other documents to english, german or french in order to make it more accessible.

**Comment by Sembauke** [comment]
Hey @NicoPico55,
Thank you for showing interest in translating our resources. While our README isn't currently translatable we do have a guide on how to translate other resources:

https://contribute.freecodecamp.org/how-to-translate-files

If you have any problems setting up, please join our Discord and we will help you further.
