### ISSUE TITLE
No feedback when you miss a question or give wrong answer

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#57642]
When you click the `check your answer` button to pass the comprehension checks after each [lecture video of the upcoming FSD cert](https://www.freecodecamp.dev/learn/full-stack-developer/lecture-what-is-css/what-is-css), if you miss a question no feedback is given.

If you give a wrong answer you need to scroll up to see the feedback. In both cases, it would be useful to provide a simple message right above the `check your answer` button saying something like `You have unanswered questions and/or incorrect answers."

![Image](https://github.com/user-attachments/assets/ee608f3a-13a4-4c38-82c7-9798a0a67ad8)

**Comment by a2937** [comment]
Hmm is it possible to trigger a banner flash from that component?
