### ISSUE TITLE
Small Glitch

### ISSUE THREAD

**Issue by RiotMike** [FreeCodeCamp/FreeCodeCamp#5764]
So the challenges request you to "Change the 0 so the difference is 12.", but instead you can just change the var to = 12 .

Challenge [Waypoint: Subtract One Number from Another with JavaScript](http://www.freecodecamp.com/challenges/waypoint-subtract-one-number-from-another-with-javascript#?solution=var%20difference%20%3D%2045%20-%200%3B%0A%0A%0Avar%20difference%20%3D%2012%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var difference = 45 - 0;


var difference = 12;
```

**Comment by ltegman** [comment]
Good point. We can check to make sure there is only one instance of the word `difference` and that the number 45 is still there.

**Comment by pallavrustogi** [comment]
I think this issue is still persisting.

**Comment by SaintPeter** [comment]
@pallavrustogi Can you please explain what you mean?  The code has been changed.  If your code is different you may try hitting the "reset" button to refresh it to the new code.
