### ISSUE TITLE
Waypoint: Size your Images

### ISSUE THREAD

**Issue by denzo15lll** [FreeCodeCamp/FreeCodeCamp#5765]
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
   .smaller-image {

    width: 100px;

  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

-Your img element should have the class smaller-image.
-Your image should be 100 pixels wide.

not sure what the problem is

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need assistance. Thanks and happy coding!
