### ISSUE TITLE
Manipulate Arrays With pop (Reset and ran test)

### ISSUE THREAD

**Issue by eaglem4n15** [FreeCodeCamp/FreeCodeCamp#5766]
![image](https://cloud.githubusercontent.com/assets/11012268/12075327/140ab31c-b142-11e5-998f-8ddbe21746a0.png)

Hi all,

I had trouble with the step "myArray should only contain [["John", 23]]." because initially the code was missing the square brackets so when I ran the test it will appear as "John", 23. 

So I went ahead and added the brackets when it specifically said not to but I did and it fixed the problem.

But it didn't sit right with me so I reset the problem and the code changed. I am surprised that it passed when I ran the test. (As seen in picture)

I knew that this was wrong so I assigned myArray.pop() to var removedFromMyArray.

Please confirm if this is correct because now I can not go back to the initial code when I first started the challenge.

**Comment by SaintPeter** [comment]
Yes, we recently changed the definition of this challenge.  The saved code does not automatically update, but hitting reset did.  You're good to go!  Happy Coding!
