### ISSUE TITLE
Waypoint: Shopping List - badly written test

### ISSUE THREAD

**Issue by HoBi** [FreeCodeCamp/FreeCodeCamp#5767]
Challenge [Waypoint: Shopping List](http://www.freecodecamp.com/challenges/waypoint-shopping-list#?solution=var%20myList%20%3D%20%5B%5D%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myList = [];
```

In this example 2. and 3. tests pass even if the `myList` variable is not an array.

>The first elements in each of your sub-arrays must all be strings

>The second elements in each of your sub-arrays must all be numbers

I believe [these variables](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1747-L1749) should be `false` at a beggining and set to true only if the condition is `true`, not otherwise (`true` -> `false`) like it is now.

**Comment by SaintPeter** [comment]
Darnit, I thought I'd fixed that.  I must have gone back and forth on those about 3 times.

You're welcome to write a PR.

**Comment by HoBi** [comment]
OK
