### ISSUE TITLE
Problem with spaces

### ISSUE THREAD

**Issue by mckillem** [FreeCodeCamp/FreeCodeCamp#5768]
Challenge [Waypoint: Accessing Objects Properties with Bracket Notation](http://www.freecodecamp.com/challenges/waypoint-accessing-objects-properties-with-bracket-notation#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20%22an%20entree%22%3A%20%22hamburger%22%2C%0A%20%20%22my%20side%22%3A%20%22veggies%22%2C%0A%20%20%22the%20drink%22%3A%20%22water%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20entreeValue%20%3D%20testObj%20%5B%22an%20entree%22%5D%3B%20%20%20%2F%2F%20Change%20this%20line%0Avar%20drinkValue%20%3D%20testObj%20%5B%22the%20drink%22%5D%3B%20%20%20%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testObj = {
  "an entree": "hamburger",
  "my side": "veggies",
  "the drink": "water"
};

// Only change code below this line

var entreeValue = **testObj ["an entree"];**   // Change this line
var drinkValue = **testObj ["the drink"];**    // Change this line

```
If marked text is with spaces it can't pass.
![screen shot 2016-01-02 at 18 45 59](https://cloud.githubusercontent.com/assets/9692212/12075459/9f098d14-b181-11e5-9951-5b3757715bf5.png)

**Comment by ltegman** [comment]
Confirmed. Test should be made to tolerate a space between the variable name and the opening square bracket.

**Comment by mckillem** [comment]
And the next one is the same.

**Comment by ar94952** [comment]
// Setup
var testObj = {
  "an entree": "hamburger",
  "my side": "veggies",
  "the drink": "water"
};

// Only change code below this line

var entreeValue = testObj ["an entree"];   // Change this line
var drinkValue = testObj ["the drink"];    // Change this line

take off the asterisks...??????
