### ISSUE TITLE
Challenge http://www.freecodecramp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue

### ISSUE THREAD

**Issue by polivmi1** [FreeCodeCamp/freecodecamp#577]
![screen](https://cloud.githubusercontent.com/assets/5646007/7824297/22c01c78-0402-11e5-8b8e-3dffde74650b.png)

**Comment by QuincyLarson** [comment]
Thank you for pointing this out. I have fixed this and will push the fix shortly.
