### ISSUE TITLE
Checkpoint: Stand in Line 404

### ISSUE THREAD

**Issue by duffn** [FreeCodeCamp/FreeCodeCamp#5770]
`Checkpoint: Stand in Line` returns a 404 error.

http://www.freecodecamp.com/challenges/checkpoint-stand-in-line

<img width="624" alt="screen shot 2016-01-02 at 11 19 25 am" src="https://cloud.githubusercontent.com/assets/3457341/12075599/e1f72986-b142-11e5-85f2-977701585869.png">
<img width="1177" alt="screen shot 2016-01-02 at 11 18 29 am" src="https://cloud.githubusercontent.com/assets/3457341/12075600/e35aa6ea-b142-11e5-80d9-ab99fadddb75.png">

**Comment by ltegman** [comment]
Any ideas, @SaintPeter or @BerkeleyTrue?

**Comment by BerkeleyTrue** [comment]
Fixed now. Thanks for reporting.

Happy Coding!
