### ISSUE TITLE
The Sentence Maker lab from the JS functions module does not ask to use functions

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/freeCodeCamp#57710]
This was discussed and apparently never implemented. User stories and tests should be modified to use functions, since this lab has been placed in that module.

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/lab-sentence-maker/66c057041df6394ca796bf33.md?plain=1

**Comment by zairahira** [comment]
Can we move it to "JavaScript Variables and Strings" section for now?

**Comment by Dario-DC** [comment]
Probably the best solution. I think either before or after the chat bot lab works.

**Comment by Dario-DC** [comment]
I made a PR. Let me know what you think about the order @zairahira
