### ISSUE TITLE
Learn Present Perfect while Talking About Accessibility - Bob is replaced by James

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#57753]
In one of the sections of [Learn Present Perfect while Talking About Accessibility](https://www.freecodecamp.org/learn/b1-english-for-developers/#learn-present-perfect-while-talking-about-accessibility), one character - Bob - present in the initial dialogue is replaced by James in two tasks, while Bob makes it back after that.
- [Dialogue 3](https://www.freecodecamp.org/learn/b1-english-for-developers/learn-present-perfect-while-talking-about-accessibility/dialogue-3-voice-command-features) - First appearance of Bob in this section.
- [Task 61](https://www.freecodecamp.org/learn/b1-english-for-developers/learn-present-perfect-while-talking-about-accessibility/task-61) - James replaces Bob, using Bob's lines, as it seems. Similar thing happens in task 62.
- [Task 68](https://www.freecodecamp.org/learn/b1-english-for-developers/learn-present-perfect-while-talking-about-accessibility/task-68) - Bob is back, in the tasks 63-67 neither one appeared.

**Comment by a2937** [comment]
You're right Bob's line in Dialog 3 were given to James in Task 61. And in Task 62, James is taking over the dialog while Bob is being asked about.
