### ISSUE TITLE
Typo in HTML ids vs classes lecture

### ISSUE THREAD

**Issue by mdmillerdev** [freeCodeCamp/freeCodeCamp#57766]
### Describe the Issue

Hello,

I noticed a typo in one of the HTML lectures.

One of the questions to verify the user watched the video is as follows:

What happens if you try to use duplicate an `id` in your HTML?

### Affected Page

https://www.freecodecamp.org/learn/full-stack-developer/lecture-html-fundamentals/what-are-ids-and-classes

### Steps to Reproduce

The error is on question `#2` of the page linked above.

### Recommended fix or suggestions

I believe what the author was going for was:

What happens if you try to duplicate an `id` in your HTML?

But, I think it could be better posed as:

What happens if you use the same `id` more than once in your HTML?

**Comment by jdwilkin4** [comment]
There are a few other changes that need to be made for the questions following this lecture video


For the feedback for the first question, it should be changed to this

```md
### --feedback--

Remember that an `id` name is unique and should only be used once per HTML document.

```

It needs to be changed in all areas.

Also, for that second question, I don’t think the feedback is all that helpful.

Let’s change it to this instead

```md
### --feedback--

Think about how using duplicate `id` names in your HTML can affect your CSS and JavaScript.

```

For interested contributors, here is the file you need to update

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/lecture-html-fundamentals/6708382cf088b216580a9ff1.md
