### ISSUE TITLE
Make the fullstack cert to the top of the whole curriculam

### ISSUE THREAD

**Issue by Sazid99246** [freeCodeCamp/freeCodeCamp#57775]
### Describe the Issue

The fullstack certification is now situated at the bottom of all the curriculam.

### Affected Page

https://www.freecodecamp.org/learn/

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

As you requested everyone in the discord and in news, to move from previous certifications to the new full stack certification, I think it is necessary now to put this certification to the top of all other certifications. Because, if anyone is new to freecodecamp's curriculam, he/she may opt to the responsive web design certification as it is on the top right now.

### System

- Device: [e.g. iPhone 6, Laptop]
- OS: [e.g. iOS 14, Windows 10, Ubuntu 20.04]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by ilenia-magoni** [comment]
Thank you for your suggestion, once the Certified Full Stack Developer Curriculum has gone some time in open beta, and some more features are added, it will be moved at the top. As such, I am closing this issue.
