### ISSUE TITLE
Line nr 8 with correct code b = 3 *= b; it's not working same with previous +=

### ISSUE THREAD

**Issue by krzyszczep** [FreeCodeCamp/FreeCodeCamp#5777]
Challenge [Waypoint: Assignment with Times Equals](http://www.freecodecamp.com/challenges/waypoint-assignment-with-times-equals#?solution=var%20a%20%3D%205%3B%0Avar%20b%20%3D%2012%3B%0Avar%20c%20%3D%204.6%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20*%3D%205%3B%0Ab%20%3D%203%20*%20b%3B%0Ac%20%3D%20c%20*%3D%2010%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var a = 5;
var b = 12;
var c = 4.6;

// Only modify code below this line

a = a *= 5;
b = 3 * b;
c = c *= 10;



```

**Comment by krzyszczep** [comment]
Apologise for weak eng or language mistakes

**Comment by ltegman** [comment]
This code is not correct. `*=` negates the need for the `=` assignment. Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance.
