### ISSUE TITLE
Update Feedback for SVG lecture

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#57786]
For the first question you are provided with this hint if you get it wrong

<img width="1014" alt="Image" src="https://github.com/user-attachments/assets/45172264-2fb9-4ab1-b37d-83ac13bd1a2d" />

A better hint would be to just direct them to the beginning of the video where this was discussed.

```md
### --feedback--

Review the video starting at the 14 second mark.
```

Make sure to update the feedback in all places it occurs

Same issue with the second question.

<img width="879" alt="Image" src="https://github.com/user-attachments/assets/9ffd34f4-406b-4ee0-b646-637c5ad2210c" />

This hint doesn't seem to be helpful to guide users to the correct answer which is the first option.

Again, we should just direct them to the place where it was discussed in the video.

```md
### --feedback--

Review the video starting at the 38 second mark.
```

Make sure to update the feedback in all places it occurs

The last feedback needs to be updated too.

Here is the current version.

<img width="844" alt="Image" src="https://github.com/user-attachments/assets/0894384c-ab37-4ebb-ba25-32a45a9da981" />

While true, it doesn't help guide users to the correct answer.

Here is the updated feedback.

```md
### --feedback--

Review the video starting at the 53 second mark.
```

Make sure to update the feedback in all places it occurs

**Comment by asr1325** [comment]
Hi @jdwilkin4,

I want to work on this issue. I plan to update the feedback messages to include specific timestamps from the video, ensuring they provide clear guidance to users. I'll submit a pull request once the changes are ready.

Thank you!

**Comment by ilenia-magoni** [comment]
@asr1325 We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.
