### ISSUE TITLE
Syntax error unrecognized expression: waypoint-check-radio-buttons-and-checkboxes-by-default

### ISSUE THREAD

**Issue by polivmi1** [FreeCodeCamp/freecodecamp#578]
![screen](https://cloud.githubusercontent.com/assets/5646007/7824316/5260fa24-0402-11e5-9e80-cafc1dcea14e.png)

**Comment by BerkeleyTrue** [comment]
Hey @polivmi1 Thanks for submitting this issue.

unfortunately I cannot replicate it.

Can you give us more context?
also, try hitting cmd(or ctrl on windows) + shift + r and see if that fixes your issue.

**Comment by polivmi1** [comment]
There has been same problem on Waypoint: Create a Text Field and @QuincyLarson somehow solved it. Nothing I tried fixes it. No plugins, that could be a problem.

**Comment by BerkeleyTrue** [comment]
This issue keeps popping up so we will be closing this and tracking here #585
