### ISSUE TITLE
Assuming have an issue with Testing a string.

### ISSUE THREAD

**Issue by 7urkm3n** [FreeCodeCamp/FreeCodeCamp#5780]
Challenge [Waypoint: Quoting Strings with Single Quotes](http://www.freecodecamp.com/challenges/waypoint-quoting-strings-with-single-quotes#?solution=var%20myStr%20%3D%20'This%20string%20has%20%22double%20quotes%22%20in%20it.%20And%20%22probably%22%20lots%20of%20them.'%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = 'This string has "double quotes" in it. And "probably" lots of them.';
```

<a href="http://tinypic.com?ref=w01chz" target="_blank"><img src="http://i64.tinypic.com/w01chz.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ltegman** [comment]
Your string is completely different than the one given in the seed code. Please press reset and start over.
Thanks and happy coding!
