### ISSUE TITLE
Troubles with strict Equality / Inequality tests on new waypoints 58 - 60

### ISSUE THREAD

**Issue by Em-Ant** [FreeCodeCamp/FreeCodeCamp#5784]
Challenge [Waypoint: Comparison with the Strict Inequality Operator](http://www.freecodecamp.com/challenges/waypoint-comparison-with-the-strict-inequality-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This challenge and the preceding waypoint 58 (Comparison with strict equality ) returned  unexpected errors on the last test, but they allowed me to pass anyway. I tried to repeat the challenges, re-submitting the same solutions, and the tests were OK.

![screenshot](https://cloud.githubusercontent.com/assets/12955734/12076258/04195be0-b1a4-11e5-800c-52b325ac2b7c.jpg)

**Comment by SaintPeter** [comment]
Your code looks correct and I am not able to reproduce the error.  Do you actually have a screenshot of the "Submit and go to your next challenge" modal up with a red X test still present?

**Comment by Em-Ant** [comment]
No I haven't (sorry), but the "submit and go" pop up was there just before taking the screen-shot. I had to close it to scroll the left panel, in order to show the error clearly. I am not able to reproduce the error any more. As I wrote, I experienced the errors only the **FIRST TIME** I submitted the solutions. I tried to repeat the challenges few times, even after clearing the browser cache and cookies, but now the tests were all OK.

**Comment by ltegman** [comment]
Unfortunately if we can't repro the problem there's no way for us to troubleshoot and fix it. I also wouldn't consider it a huge problem that the wrong test result was displayed, because the challenge let you pass with the correct code, which is the important part.

Thanks and happy coding!
