### ISSUE TITLE
Waypoint: Local Scope and Functions

### ISSUE THREAD

**Issue by alizagoldberg** [FreeCodeCamp/FreeCodeCamp#5786]
I saw that removing the comment about removing console.log would remove the bug, but that method did not work for me. Did anyone find another solution?

Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20'use%20strict'%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0Aconsole.log(myVar)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 'use strict';
  
  
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);


```

**Comment by ltegman** [comment]
There is a comment in the seed code that says `// now remove the console log line to pass the test`. You need to do that, because the final `console.log(myVar);` is referencing an undefined variable and crashing the code.

**Comment by Stanleynd** [comment]
See the image to know what you're expected to do.
![freecodecamp](https://user-images.githubusercontent.com/39798429/41037029-eb5bbb70-6989-11e8-9a84-28e51f7768e3.png)

Just as @Itegman said, there is a line demanding console.log to be remove before test will run.
Line 11// Now remove the console log line to pass the test,
so you have to remove console.log which is line 10.
Thanks.
