### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-build-a-cash-register has an issue 

### ISSUE THREAD

**Issue by miguelc1221** [FreeCodeCamp/freecodecamp#579]
Please tell us in detail here how we can make this challenge better.
The Advanced Algorithm Scripting challenges don't seem to show completed after completing the challenges.

**Comment by terakilobyte** [comment]
I'm unable to reproduce this issue. We've sorted out quite a bit around some issues that may have caused this. Can you confirm whether you are able to complete it and it show completion?

**Comment by terakilobyte** [comment]
I'm closing this issue for now, feel free to reopen it if you can reproduce it.
