### ISSUE TITLE
Move "Note" in instructions to be inline with text?

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#5790]
Challenge [Waypoint: Create Decimal Numbers with JavaScript](http://www.freecodecamp.com/challenges/waypoint-create-decimal-numbers-with-javascript#?solution=var%20ourDecimal%20%3D%205.7%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myDecimal%20%3D%205.5%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourDecimal = 5.7;

// Only change code below this line
var myDecimal = 5.5;


```

The "Note" is just awkwardly floating there. 
![image](https://cloud.githubusercontent.com/assets/2754821/12076658/171b879e-b169-11e5-939f-36e0a556e2c4.png)

Might I suggest it be more inline like this?
![image](https://cloud.githubusercontent.com/assets/2754821/12076660/25f4aa02-b169-11e5-8171-f0b02b769243.png)

Or with actual emphasis like so.
![image](https://cloud.githubusercontent.com/assets/2754821/12076675/1d251dde-b16a-11e5-972b-69d0e79f363f.png)

**Comment by ltegman** [comment]
I'll leave it up to @SaintPeter which is preferred. I think both look better than it is now, but inline probably makes more sense so it doesn't take emphasis away from the instructions.

**Comment by SaintPeter** [comment]
Ahh .. . it looks like I mixed it up a bit.  In about half the cases I did:
`<strong>Note</strong><br>More Text Here`
and in the other half I put an actual line break, which gives the extra space.
![image](https://cloud.githubusercontent.com/assets/553494/12077024/f49b488e-b17d-11e5-9f78-6afcd0ecd73e.png)
I'll cook up a PR.
