### ISSUE TITLE
Insufficient tests for Waypoint: Concatenating Strings with Plus Operator

### ISSUE THREAD

**Issue by nickpapoutsis** [FreeCodeCamp/FreeCodeCamp#5792]
Challenge [Waypoint: Concatenating Strings with Plus Operator](http://www.freecodecamp.com/challenges/waypoint-concatenating-strings-with-plus-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22%20This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.

Putting the space at the beginning of the 2nd string does not pass the second test.

Tested on Firefox, Chrome Dev and Edge (latest versions).

My code:
```javascript
// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start." + " This is the end.";
```

**Comment by ltegman** [comment]
It asks you to combine two specific strings. If the space isn't in the same place it isn't the same set of strings.

Thanks and happy coding!

**Comment by avensut** [comment]
I've been the same issue.
