### ISSUE TITLE
Caesar Replacement Checkpoint - Profile Lookup

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#5795]
Me and @SaintPeter have discussed the replacement for the Caesar checkpoint. 

It's going to be a Camper Lookup Checkpoint:

Make a function that takes a "camper" and a property as parameters and if that property exists, return that property is in. If the camper does not exist, return "No such Camper". If the property doesn't exist, return "Camper has no such property".

```javascript
var campers = [
    {
        "username": "SaintPeter",
        "title": "The Chosen One",
        "HP": 3000,
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
     {
        "username": "AkiraLaine",
        "title": "Time Traveler",
        "HP": 2000,
        "likes": ["Magic", "Javascript", "Cookies"]

    }
]

function lookUp(camper, prop){
    var answer;

    return answer;
}

lookUp("AkiraLaine", "likes");
```

@SaintPeter gave me the green light to make it. I'm currently setting up FCC locally and will start working on it.

**Comment by SaintPeter** [comment]
I'm not sure if we should use actual campers in the list.  It may also make sense to make the data a little more succinct so we can have more like 5-10 records.

**Comment by DDaems** [comment]
>["Pizza", "Coding", "Brownie Points"]  :laughing:

**Comment by AkiraLaine** [comment]
@SaintPeter For the actual challenge, I'm changing the objects to different "contacts" instead of campers.

**Comment by AkiraLaine** [comment]
Update:
Challenge is done. Made some basic tests. But needs some improvements .

**Comment by SaintPeter** [comment]
Can you post the code, or post a link to the branch on your fork so we can pull it down to test?
