### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue 

### ISSUE THREAD

**Issue by levyian** [FreeCodeCamp/freecodecamp#580]
Please tell us in detail here how we can make this challenge better.
Waypoint: Create a Set of Checkboxes and Waypoint: Create a Set of Radio Buttons throws syntax errors before the challenge is started. After completing the challenge a green checkmark shows up beside one of the requirements but the syntax errors are still there preventing one from moving on the next challenge and completing the present one.

**Comment by BerkeleyTrue** [comment]
Thank you for reporting this. Please see #585 where we will be addressing syntax error issues.
