### ISSUE TITLE
Use of jargon in Waypoint: Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by gitasong** [FreeCodeCamp/FreeCodeCamp#5800]
This Waypoint uses jargon in a way that newcomers find inaccessible and frustrating.

1) First of all, the explanation uses the term "local variable," which hasn't been defined yet in any of the prior Waypoints. If my recall of the new map serves me, you define it in the *next* Waypoint, so you're essentially using it before you define it. That's a no-no for the purposes of comprehension.

2) The paragraph "Functions can take input with parameters. Parameters are local variables that take on the value of the arguments which are passed into the function" is full of jargon. For seasoned programmers, terms like "take input," "local variables" (see #1 above), "take on the value," and "passed into the function" are straightforward terms; to newcomers who are just seeing an explanation of functions for the first time, this is incomprehensible. Also, it doesn't *clearly* differentiate between parameters and arguments, which I've found that many seasoned programmers confuse or can't distinguish. 

A more straightforward rewriting of the paragraph for newcomers would be something like: "**Parameters** are *variables* that act as placeholders for the values that are to be input to a function when it is called. When a function is defined, it is typically defined along with one or more parameters. The actual *values* that are input (or "passed") into a function when it is called are known as **arguments.**"

This should, of course, be preceded somewhere in the Waypoints by a discussion of functions as input-output machines, rather like the standard explanation of functions in math.

**Comment by ltegman** [comment]
Good critiques. I like quite like your suggested replacement explanation :+1:

**Comment by SaintPeter** [comment]
I like it too!  Good stuff.

**Comment by gitasong** [comment]
Excellent! And thank you. :)  I hate jargon with a passion, and have been trained, in all my fields, to talk to laypersons in (relatively) jargon-free terms, or at least to define terms as I use them. Also, being a relative beginner myself, I have a good grasp of what "beginner's mind" feels like, and know what sorts of locutions will trip beginners up. Any time you need a jargon check for a piece of writing, throw it my way. :)

**Comment by krisgesling** [comment]
Submitted a PR with the new wording.
My first commit to a shared github repo so hoping I ticked all the boxes
