### ISSUE TITLE
Waypoint: Quoting Strings with Single Quotes

### ISSUE THREAD

**Issue by mehadi07** [FreeCodeCamp/FreeCodeCamp#5801]
I tried but i can`t solve this challenge can anyone please help me out with this problem.

![capture](https://cloud.githubusercontent.com/assets/16364700/12077369/3c698e8e-b1ae-11e5-8eaa-c2e0bc79072c.JPG)

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to ask for assistance. Thanks and happy coding!

**Comment by mehadi07** [comment]
my bad .. thanks
