### ISSUE TITLE
Checkpoint: Convert Celsius to Fahrenheit

### ISSUE THREAD

**Issue by mehadi07** [FreeCodeCamp/FreeCodeCamp#5802]
i didn`t found any possible solution.
I need help to solve this out. 
Can anyone help me to solve this problem.
thank you
![capture1](https://cloud.githubusercontent.com/assets/16364700/12077382/862837c8-b1ae-11e5-94ab-8c1a94856392.JPG)

**Comment by SaintPeter** [comment]
Github issues are not for asking for code assistance.  Please ask for help in the [Help Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

Thanks and Happy Coding!
