### ISSUE TITLE
Korean translation of Gear up for Success

### ISSUE THREAD

**Issue by hgryoo** [FreeCodeCamp/FreeCodeCamp#5804]
- [ ] Browse Camper News Complete
 - [ ] Reference our Wiki Complete
 - [ ] Join our LinkedIn Alumni Network Complete
 - [ ] Commit to a Goal and a Nonprofit Complete

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/39
