### ISSUE TITLE
The function returns [object Object]

### ISSUE THREAD

**Issue by ledminh** [FreeCodeCamp/FreeCodeCamp#5809]
Challenge [Bonfire: Where art thou](http://www.freecodecamp.com/challenges/bonfire-where-art-thou#?solution=function%20where(collection%2C%20source)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20What%27s%20in%20a%20name%3F%0A%20%20%0A%20%20var%20keyArr%20%3D%20Object.keys(source)%3B%0A%20%20%0A%20%20for(var%20iCollection%20%3D%200%3B%20iCollection%20%3C%20collection.length%3B%20iCollection%2B%2B)%7B%0A%20%20%20%20%0A%20%20%20%20var%20currentObj%20%3D%20collection%5BiCollection%5D%3B%0A%20%20%20%20%0A%20%20%20%20var%20same%20%3D%20true%3B%0A%20%20%20%20for(var%20iKey%20%3D%200%3B%20iKey%20%3C%20keyArr.length%20%26%26%20same%3B%20iKey%2B%2B)%7B%0A%20%20%20%20%20%20if(!currentObj.hasOwnProperty(keyArr%5BiKey%5D)%20%7C%7C%20currentObj%5BkeyArr%5BiKey%5D%5D%20!%3D%20source%5BkeyArr%5BiKey%5D%5D)%0A%20%20%20%20%20%20%20%20same%20%3D%20false%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20if(same)%0A%20%20%20%20%20%20arr.push(currentObj)%3B%0A%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0Awhere(%5B%7B%20first%3A%20%22Romeo%22%2C%20last%3A%20%22Montague%22%20%7D%2C%20%7B%20first%3A%20%22Mercutio%22%2C%20last%3A%20null%20%7D%2C%20%7B%20first%3A%20%22Tybalt%22%2C%20last%3A%20%22Capulet%22%20%7D%5D%2C%20%7B%20last%3A%20%22Capulet%22%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.

Although my code has already passed all the tests from this Bonfire but I noticed that the small black area in the left column right below the Bonfire's instruction where the result is usually displayed displays ```[object Object]``` (Check the screenshot below to see what I mean).

I don't know whether it's because of my code or it's a bug.

My code:
```javascript
function where(collection, source) {
  var arr = [];
  // What's in a name?
  
  var keyArr = Object.keys(source);
  
  for(var iCollection = 0; iCollection < collection.length; iCollection++){
    
    var currentObj = collection[iCollection];
    
    var same = true;
    for(var iKey = 0; iKey < keyArr.length && same; iKey++){
      if(!currentObj.hasOwnProperty(keyArr[iKey]) || currentObj[keyArr[iKey]] != source[keyArr[iKey]])
        same = false;
    }
    
    if(same)
      arr.push(currentObj);
      
  }
   
  return arr;
}

where([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" });

```

![2016-01-03](https://cloud.githubusercontent.com/assets/12500215/12078037/f131b52e-b1b5-11e5-8ef9-33cc3f5a5211.png)

**Comment by SaintPeter** [comment]
This is because our courseware takes the last value returned and displays it in our little faux console.  Since `where` returns an object, that's how it is displayed.  This is not a problem with your code.

We are working on improving the display.

Thanks and Happy Coding.
