### ISSUE TITLE
Suggestion: test case not check if any letter is been used more that the based.

### ISSUE THREAD

**Issue by ajoyac** [FreeCodeCamp/FreeCodeCamp#5810]
Challenge [Bonfire: Mutations](http://www.freecodecamp.com/challenges/bonfire-mutations#?solution=function%20mutation(arr)%20%7B%0A%20%20%20dict%3D%7B%7D%3B%0A%20%20based%3Darr%5B0%5D.toLowerCase()%3B%0A%20%20word%3Darr%5B1%5D.toLowerCase()%3B%0A%20%20for%20(var%20i%3D0%3Bi%3Cbased.length%3Bi%2B%2B)%7B%0A%20%20%20%20if%20(dict.hasOwnProperty(based%5Bi%5D))%0A%20%20%20%20%20%20dict%5Bbased%5Bi%5D%5D%2B%3D1%3B%0A%20%20%20%20else%0A%20%20%20%20%20%20dict%5Bbased%5Bi%5D%5D%3D1%3B%0A%20%20%7D%0A%20%20for%20(i%3D0%3Bi%3Cword.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20if%20(!dict.hasOwnProperty(word%5Bi%5D))%0A%20%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function mutation(arr) {
   dict={};
  based=arr[0].toLowerCase();
  word=arr[1].toLowerCase();
  for (var i=0;i<based.length;i++){
    if (dict.hasOwnProperty(based[i]))
      dict[based[i]]+=1;
    else
      dict[based[i]]=1;
  }
  for (i=0;i<word.length;i++){
     if (!dict.hasOwnProperty(word[i]))
         return false;
  }
  return true;
}

mutation(["hello", "hey"]);

```

**Comment by bugron** [comment]
Closing this issue as stale. Feel free to reopen with more details about the issue. Thanks for posting.
