### ISSUE TITLE
its not running the test to check.

### ISSUE THREAD

**Issue by saloni471** [FreeCodeCamp/FreeCodeCamp#5812]

**Comment by sludge256** [comment]
Please read https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue
It's hard to help with almost no information about your issue.
Most of the time your issues can be resolved in the [Help chat](https://gitter.im/FreeCodeCamp/Help) as Github issues are for site related issues.
