### ISSUE TITLE
Bonfire: Validate US Telephone Numbers (result checker issue)

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#5813]
Challenge [Bonfire: Validate US Telephone Numbers](http://www.freecodecamp.com/challenges/bonfire-validate-us-telephone-numbers#?solution=function%20telephoneCheck(str)%20%7B%0A%20%20%2F%2F%20valid%20patterns%0A%20%20var%20p0%20%3D%20new%20RegExp(%27%5E%5B1%5D%5C%5Cb%27)%3B%0A%20%20var%20p01%20%3D%20new%20RegExp(%27%5E%5B1%5D%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p02%20%3D%20new%20RegExp(%27%5E%5B1%5D%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p03%20%3D%20new%20RegExp(%27%5E%5B1%5D%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p04%20%3D%20new%20RegExp(%27%5E%5B1%5D%5C%5C(%5C%5Cd%5C%5Cd%5C%5Cd%5C%5C)%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p05%20%3D%20new%20RegExp(%27%5E%5B1%5D%5C%5Cs%5C%5C(%5C%5Cd%5C%5Cd%5C%5Cd%5C%5C)%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20%0A%20%20var%20p1%20%3D%20new%20RegExp(%27%5E%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p2%20%3D%20new%20RegExp(%27%5E%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p3%20%3D%20new%20RegExp(%27%5E%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p4%20%3D%20new%20RegExp(%27%5E%5C%5C(%5C%5Cd%5C%5Cd%5C%5Cd%5C%5C)%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20var%20p5%20%3D%20new%20RegExp(%27%5E%5C%5C(%5C%5Cd%5C%5Cd%5C%5Cd%5C%5C)%5C%5Cs%5C%5Cd%5C%5Cd%5C%5Cd-%5C%5Cd%5C%5Cd%5C%5Cd%5C%5Cd%24%27)%3B%0A%20%20%2F%2F%20simple%20not%20full%20validator%0A%20%20%2F%2Fif%20(str.match(p0)%20%7C%7C%20str.match(p1)%20%7C%7C%20str.match(p2)%20%7C%7C%20str.match(p3)%20%7C%7C%20str.match(p4))%7Breturn%20true%3B%7Delse%7Breturn%20false%3B%7D%0A%20%20%2F%2F%20complex%20full%20validator%0A%20%20if%20(str.match(p01)%20%7C%7C%20str.match(p02)%20%7C%7C%20str.match(p03)%20%7C%7C%20str.match(p04)%20%7C%7C%20str.match(p05)%20%7C%7C%20str.match(p1)%20%7C%7C%20str.match(p2)%20%7C%7C%20str.match(p3)%20%7C%7C%20str.match(p4))%7Breturn%20true%3B%7Delse%7Breturn%20false%3B%7D%0A%0A%7D%0AtelephoneCheck(%22555-555-5555%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 5841.83.0) AppleWebKit/537.36 (KHTML like Gecko) Chrome/36.0.1985.138 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code (presumably, this is one way how the test should have been passed, but for current result checker it is excessive):
```javascript
function telephoneCheck(str) {
  // valid patterns
  //var p0 = new RegExp('^[1]\\b');
  var p01 = new RegExp('^[1]\\s\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d$');
  var p02 = new RegExp('^[1]\\s\\d\\d\\d\\s\\d\\d\\d\\s\\d\\d\\d\\d$');
  var p03 = new RegExp('^[1]\\s\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d$');
  var p04 = new RegExp('^[1]\\(\\d\\d\\d\\)\\d\\d\\d-\\d\\d\\d\\d$');
  var p05 = new RegExp('^[1]\\s\\(\\d\\d\\d\\)\\s\\d\\d\\d-\\d\\d\\d\\d$');
  
  var p1 = new RegExp('^\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d$');
  var p2 = new RegExp('^\\d\\d\\d\\s\\d\\d\\d\\s\\d\\d\\d\\d$');
  var p3 = new RegExp('^\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d$');
  var p4 = new RegExp('^\\(\\d\\d\\d\\)\\d\\d\\d-\\d\\d\\d\\d$');
  var p5 = new RegExp('^\\(\\d\\d\\d\\)\\s\\d\\d\\d-\\d\\d\\d\\d$');
  // invalid validator, which passes all tests (it doesn't validate correctly for numbers with country codes)
  //if (str.match(p0) || str.match(p1) || str.match(p2) || str.match(p3) || str.match(p4)){return true;}else{return false;}
  // valid validator
  if (str.match(p01) || str.match(p02) || str.match(p03) || str.match(p04) || str.match(p05) || str.match(p1) || str.match(p2) || str.match(p3) || str.match(p4)){return true;}else{return false;}
}
telephoneCheck("555-555-5555");
```
**Now down to details**
Presumably, this code should not let user pass the test, because it does not correctly validate phone numbers with country code, but result checker tells everything's fine
```javascript
function telephoneCheck(str) {
  // valid patterns
  var p0 = new RegExp('^[1]\\b');
  var p1 = new RegExp('^\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d$');
  var p2 = new RegExp('^\\d\\d\\d\\s\\d\\d\\d\\s\\d\\d\\d\\d$');
  var p3 = new RegExp('^\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d$');
  var p4 = new RegExp('^\\(\\d\\d\\d\\)\\d\\d\\d-\\d\\d\\d\\d$');
  var p5 = new RegExp('^\\(\\d\\d\\d\\)\\s\\d\\d\\d-\\d\\d\\d\\d$');
  // invalid validator, which passes all tests (it doesn't validate correctly for numbers with country codes)
  if (str.match(p0) || str.match(p1) || str.match(p2) || str.match(p3) || str.match(p4)){return true;}else{return false;}
}
telephoneCheck("1 (555) 555-5555");
```
Actually the problem is here:
```javascript
function telephoneCheck(str) {
  var p0 = new RegExp('^[1]\\b');
  if (str.match(p0)){return true;}else{return false;}
}
telephoneCheck("1 (555) 555-5555");
```
Watch result checker response:
```code
ok > telephoneCheck("555-555-5555") should return a boolean.
ok > telephoneCheck("1 555-555-5555") should return true.
ok > telephoneCheck("1 (555) 555-5555") should return true.
not ok > telephoneCheck("5555555555") should return true.
not ok > telephoneCheck("555-555-5555") should return true.
not ok > telephoneCheck("(555)555-5555") should return true. 
ok > telephoneCheck("1(555)555-5555") should return true.
ok > telephoneCheck("1 555 555 5555") should return true.
ok > telephoneCheck("1 456 789 4444") should return true.
ok > telephoneCheck("123**&!!asdf#") should return false.
ok > telephoneCheck("55555555") should return false.
ok > telephoneCheck("(6505552368)") should return false
ok > telephoneCheck("2 (757) 622-7382") should return false.
ok > telephoneCheck("0 (757) 622-7382") should return false.
ok > telephoneCheck("-1 (757) 622-7382") should return false
ok > telephoneCheck("2 757 622-7382") should return false.
ok > telephoneCheck("10 (757) 622-7382") should return false.
ok > telephoneCheck("27576227382") should return false.
ok > telephoneCheck("(275)76227382") should return false.
ok > telephoneCheck("2(757)6227382") should return false.
ok > telephoneCheck("2(757)622-7382") should return false.
ok > telephoneCheck("555)-555-5555") should return false.
ok > telephoneCheck("(555-555-5555") should return false. 
```

**Comment by patsul12** [comment]
You can do the bonfire using a single regex. I'm assuming that is what the tests are looking for.

**Comment by ltegman** [comment]
Ahh, so the issue is that we don't currently have any tests where the country code is correct but there is a problem somewhere else in the number. Adding a test case like `telephoneCheck("1 555) 555-5555");` should solve this problem.
