### ISSUE TITLE
Pay attention at the 2th and 6th tests. Both should return another arrays. 

### ISSUE THREAD

**Issue by redday059** [FreeCodeCamp/FreeCodeCamp#5818]
Challenge [Bonfire: Drop it](http://www.freecodecamp.com/challenges/bonfire-drop-it#?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20var%20args%20%3D%20Array.prototype.slice.call(arguments)%3B%0A%20%20var%20first%20%3D%20args%5B0%5D%3B%0A%20%20var%20callback%20%3D%20args%5B1%5D%3B%0A%20%20var%20t%20%3D%20first.filter(callback)%3B%0A%20%20return%20t%3B%0A%7D%0A%0Adrop(%5B0%2C%201%2C%200%2C%201%5D%2C%20function(n)%20%7Breturn%20n%20%3D%3D%3D%201%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drop(arr, func) {
  // Drop them elements.
  var args = Array.prototype.slice.call(arguments);
  var first = args[0];
  var callback = args[1];
  var t = first.filter(callback);
  return t;
}

drop([0, 1, 0, 1], function(n) {return n === 1;});

```

**Comment by redday059** [comment]
In the task:
drop([0, 1, 0, 1], function(n) {return n === 1;}) should return [1, 0, 1]
I think it should return [1, 1]
In the task:
drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, 2].
I think it should return [3, 9]

**Comment by ltegman** [comment]
Read the instructions over again. It's asking to remove all items __until__ a condition is true.

In the future please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm what you're seeing is a site issue before filing a bug. Thanks and happy coding!
