### ISSUE TITLE
But with Waypoint: Local Scope and Functions

### ISSUE THREAD

**Issue by ssaing** [FreeCodeCamp/FreeCodeCamp#5819]
I've seen the similar issues people have been having.  I'm not able to complete this one and I've removed the global console log and the comments as well.

function myFunction() {
var myVar;
  
  
  console.log(myVar);
}
myFunction();

**Comment by ltegman** [comment]
Try refreshing the page and if that doesn't work clearing your browser cache, because this code passes just find for me. Thanks and happy coding!

**Comment by t3chm4n** [comment]
I refreshed the page (ctrl f5 on chrome) and it worked. Thanks for the tip @Itegman ;)
