### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-import-a-google-font has an issue 

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#582]
I'm glad this is included...it would be great if you could "teach people to fish" with this one...

Show new users where to find google fonts,  & where to get the linking code.

**Comment by BerkeleyTrue** [comment]
Hey @AdventureBear 

While we a really greatful for you are taking time filling this issue, we are currently being inundated with issues. Since this is not actually a bug with the code I will be closing this.
