### ISSUE TITLE
The mobile screen is blank and run tests does not work

### ISSUE THREAD

**Issue by ziafkhan** [FreeCodeCamp/FreeCodeCamp#5823]
![123](https://cloud.githubusercontent.com/assets/16511145/12080146/fa93a574-b277-11e5-9fb9-a4854f485f3f.png)

Challenge [Waypoint: Inherit Styles from the Body Element](http://www.freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

Things i have done:
Cleared out everything from the beginning of time in chrome.
Tried in private browsing
Restarted the PC
I even tried Internet Explorer

This has happened before but seemed to fix itself after a while.

My code:
```html
<style>
  body {
    background-color: black;
    
  }

</style>

```

**Comment by jundc1006** [comment]
Same issue here, it doesn't accept my answer:

<style>
  body {
    background-color: green;
    font-family:Monospace;
  }

</style>
<h1>Hello World</h1>

**Comment by bugron** [comment]
This may be a connection issue. Try to follow instructions from [this article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc) if you still have this issue. After that if the issue is not solved feel free to reopen, thanks.
