### ISSUE TITLE
HTML entities codes doesn't pass instead of strings

### ISSUE THREAD

**Issue by amrme** [FreeCodeCamp/FreeCodeCamp#5824]
Challenge [Bonfire: Convert HTML Entities](http://www.freecodecamp.com/challenges/bonfire-convert-html-entities#?solution=function%20convert(str)%20%7B%0A%20%20%0A%20%20%2F%2F%20new%20tmp%20string%20for%20hoding%20subStrings%0A%20%20var%20tmp%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20%2F%2F%20get%20the%20char%20code%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%3D%20str.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%2F%2F%20any%20char%20%3C%2065%20will%20not%20be%20an%20alphabitical%20character%0A%20%20%20%20%2F%2F%2032%20is%20the%20space%0A%20%20%20%20if%20(str.charCodeAt(i)%20%3C%2065%20%26%26%20str.charCodeAt(i)%20!%3D%2032)%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20str%20%3D%20%22%26%23%22%20%2B%20str.charCodeAt(i)%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%2F%2F%20insert%20the%20new%20char%20inside%0A%20%20%20%20%20%20%20%20tmp.push(%22%26%23%22%20%2B%20str.charCodeAt(i))%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%2F%2F%20if%20it's%20a%20regular%20char%20just%20put%20it%20back%0A%20%20%20%20else%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20tmp.push(str%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20join%20the%20string%0A%20%20str%20%3D%20tmp.join(%22%22)%3B%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0Aconvert(%22Dolce%20%26%20Gabbana%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(str) {
  
  // new tmp string for hoding subStrings
  var tmp = [];
  
  // get the char code
  for (var i = 0; i <= str.length; i++) {
    // any char < 65 will not be an alphabitical character
    // 32 is the space
    if (str.charCodeAt(i) < 65 && str.charCodeAt(i) != 32)
      {
        // str = "&#" + str.charCodeAt(i);
        
        // insert the new char inside
        tmp.push("&#" + str.charCodeAt(i));
      }
    // if it's a regular char just put it back
    else
      {
       tmp.push(str[i]);
      }
  }
  
  // join the string
  str = tmp.join("");
  
  return str;
}

convert("Dolce & Gabbana");

```

It doesn't accept HTML codes instead of strings, I wrote the solution in a generic way where I search for the decimal value of the ASCII character and check if it was an entity then convert it to HTML codes such as &#38 ; (without the space) for & instead of &amp ; because it's much more generic and better in that way, but unfortunately it doesn't pass the test

**Comment by ltegman** [comment]
I don't see this as a problem. The bonfire asks for you to use entities, we provide a link that shows you exactly what those entities are, and the spec explicitly shows you that entities are expected. Your code is good, but you're simply not solving the problem we asked you to solve.

I'll leave this open for discussion briefly in case anyone else on the team has a differing opinion on this.

**Comment by amrme** [comment]
Ok, I'll write another function that does the conversion needed to pass the test, thanks!

**Comment by bugron** [comment]
Closing this issue. Feel free to reopen if you still experience problems, thanks.

**Comment by amrme** [comment]
I already wrote the extra function that day, thanks!
