### ISSUE TITLE
Waypoint: Escaping Literal Quotes in Strings confusing instruction

### ISSUE THREAD

**Issue by CaroleAnneHannon** [FreeCodeCamp/FreeCodeCamp#5825]
**Instruction**
Use backslashes to assign the following to myStr variable:

"I am a "double quoted" string inside "double quotes""

--

The above instruction begs the question whether the first and last " are supposed to be displayable as well, or whether they're just there to indicate the string's existence.

I would propose that:

--
**Instruction**
Use backslashes to assign the following to myStr variable:

I am a "double quoted" string inside "double quotes"

--
makes it clearer that the answer should be
var myStr = "I am a \"double quoted\" string inside \"double quotes\"";
and not
var myStr = "\"I am a \"double quoted\" string inside \"double quotes\"\"";

(if you console.log the above it makes it clear what the confusion would be)

**Comment by SaintPeter** [comment]
I don't think I can see the difference or maybe I don't understand.  I can't tell if GitHub is removing formatting or if I'm just confused.

I *think* I get what you're saying. So . . . maybe yes?

**Comment by OriBon** [comment]
I felt that the instructions were pretty clear. If it is causing confusion then I think that's a PEBKAC issue where the user is simply not grasping how to utilize the escape character.
`myStr` is meant to be a string. If we alter the instructions to say `I am a "double quoted" string inside "double quotes"` then myStr would be improperly syntaxed and therefore not a string.
Changing the string to single quotes instead might be a better solution.

**Comment by DanielMW34** [comment]
Which literal does the solution output, option A or, option B?

A) "I am a "double quoted" string inside "double quotes""

B) I am a "double quoted" string inside "double quotes"

**Comment by SaintPeter** [comment]
B

**Comment by DerekKHarris** [comment]
I agree with what CaroleAnneHannon suggested.  I found the directions confusing.

It should go without saying that when you are assigning a string you should surround it with double quotes so we don't need those included in the sentence.

**Comment by davida26** [comment]
Hey guys - noticed the confusion here. 

It basically comes down to the instructions being rather vague and the main point of confusion being here:

*Instruction*
>Use backslashes to assign the following to myStr variable:
>"I am a "double quoted" string inside "double quotes""

Notice the " before I am and "" at the end.

A solution here would be: 

```javascript
var myStr = "\"I am a \"double quoted\" string inside \"double quotes\"\"";
```
so the output matches the above. 

However the solution does not require the first or last quote mark being escaped.
```javascript
var myStr = "I am a \"double quoted\" string inside \"double quotes\"";
```

This in turn outputs:
I am a "double quoted" string inside "double quotes" 
which does not match the 
"I am a "double quoted" string inside "double quotes"" and is clear area of confusion.

**Comment by zerialchua** [comment]
Thanks! This helps!:D

**Comment by SaintPeter** [comment]
Ok, so the confusing thing is that the string is quoted.  

I'm open to suggestions as to how to better communicate the requirements.  I think we could just say:
> ### Instruction
> Use backslashes to assign the following to myStr variable:

>`I am a "double quoted" string inside "double quotes"`

The last line would be wrapped in the `<code>` tags to highlight it.

Would that clear things up?

**Comment by davida26** [comment]
@SaintPeter - yes that would def clear it :+1:

**Comment by profoundhub** [comment]
I found this question still very confusing.

**Comment by mk485eg** [comment]
var myStr =  "I am a \"string inside\".";  
i need your support why it is not working .

**Comment by nwease** [comment]
hey guys I am feeling rather dumb at the moment as I have read all the comments here and used this:

var myStr= "I am a \"double quoted\" string inside \"double quotes\"";

yet it still does not work. I understand the confusion around the double quotes in "I am a but what do I do to get this dam thing to compile correctly? Driving me crazy at the moment.

**Comment by Ramya09Srinivasan** [comment]
please make it clear for me this again

**Comment by alex1nd** [comment]
dot

var myStr = "I am a \"double quoted\" string inside \"double quotes\".";

**Comment by anhlv8888** [comment]
correct answer : var myStr="I am a \"double quoted\" string inside \"double quotes\".";

**Comment by abbey5567** [comment]
var myStr="I am a \"double quoted\" string inside \"double quotes\".";
is not working

**Comment by hmake98** [comment]
I tried that code, but it does not work!

my code is var myStr = "I am a \"double quoted\" string inside \"double quotes\"";

but this code is not compiled! if there is an correction please tell me.

**Comment by AmfInfoTech** [comment]
this is solution   "I am a \"double quoted\" string inside \"double quotes\".";

**Comment by texas2010** [comment]
@AmfInfoTech 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
