### ISSUE TITLE
Test case bug in Shopping List waypoint

### ISSUE THREAD

**Issue by Salvero** [FreeCodeCamp/FreeCodeCamp#5827]
Challenge [Checkpoint: Shopping List](http://www.freecodecamp.com/challenges/checkpoint-shopping-list) has an issue.

Unable to pass the test, I believe it could be bug.  Please see screenshot and my code example. 

My code:
```javascript
var myList = ["mike", "dog", 32, "city", 3, 9];
```

![issue](https://cloud.githubusercontent.com/assets/9256193/12080728/3e5d7424-b232-11e5-8167-4abda13b3361.png)

**Comment by ltegman** [comment]
You're not creating a multidimensional array. In the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to be sure what you're seeing is actually a site bug before filing an issue.

Thanks and happy coding!
