### ISSUE TITLE
Test case bug and instruction in Escape Sequences in Strings waypoint

### ISSUE THREAD

**Issue by Salvero** [FreeCodeCamp/FreeCodeCamp#5828]
Challenge [Waypoint: Escape Sequences in Strings](http://www.freecodecamp.com/challenges/waypoint-escape-sequences-in-strings) has an issue.

Instructions:
Encode the following sequence, separated by spaces:
backslash tab tab carriage-return new-line and assign it to myStr

My code:
```javascript
var myStr = "\b backslash \t tab \t tab \r carriage-return \n new-line"; // Change this line

```

I've notice many campers have confused with this waypoint, could you please to explain more clearly?

<b>EDIT:</b>
I figure out some issue, here's final solution despite poor description in the Waypoint. 

```javascript
var myStr = "\\ \t \t \r \n";
```

Thanks! :+1:

**Comment by re4ect** [comment]
Crap I thought it was suppose to be single quotes instead of double quotes.

**Comment by NathanielPowers** [comment]
@re4ect Single quotes are also a solution. See [here](https://stackoverflow.com/questions/242813/when-to-use-double-or-single-quotes-in-javascript) for thoughts on the quotes conventions.

**Comment by lylynaheng** [comment]
I thought the result would be backslash tab tab carriage-return new-line base on the table of common escape sequences.

**Comment by jamuhuri** [comment]
This should work too  '\\ \t \t \r \n';

**Comment by SYuvaraj** [comment]
var myStr = "\\ \t \t \r \n"; works

**Comment by codebykashfi** [comment]
thanks bruh!

**Comment by amitsingh17051** [comment]
its not working

**Comment by voirs** [comment]
This is what worked for me 
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by alexolive** [comment]
var myStr= "FirstLine\n\\SecondLine\\\r\ThirdLine";

just copy that, this works!

You have 2 backslashes from both sides from SecondLine because you need do display it as the challenge says!

you welcome :)

**Comment by texas2010** [comment]
@alexolive 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by duodushu** [comment]
151Escape Sequences in Strings？it's not working?
var myStr="\\ \t \t \r \n"; 
what's wrong?

**Comment by Jeetg57** [comment]
Correct Answer is:
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";
Hope this helps...

**Comment by texas2010** [comment]
@Jeetg57 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by wellpinho** [comment]
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";
this is solution.

**Comment by Jeetg57** [comment]
Really sorry, I was still new to the forum so I didn't know all the
instructions

**Comment by reenaakumari** [comment]
myStr should have encoded text with the proper escape sequences and no spacing.
myStr should have one newline character \n
myStr should have one carriage return character \r
myStr should have two correctly escaped backslash characters \\

**Comment by Mehedi61** [comment]
"FirstLine\n\tSecondLine\nThirdLine";

This works fine.
