### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue 

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#583]
this is in general for all the html/css challenges up to this point. 

It seems to me that the displayed instructions, before the "more" link, tell you the steps to make the test pass.   The "more" is an explanation (ie teaching) of the topic.  

I feel like these should be reversed...that it's easy to hack through the challenges just following the instructions without reading the teaching part.  

I've had this feeling for more than one challenge in the html/css, and even though I know the material fairly well, i feel like a new user could get caught up in completing these in a very mechanical fashion.

**Comment by QuincyLarson** [comment]
@adventurebear we wanted to show more experienced developers exactly what needed to be done so they could keep moving. You're right, some of them can be completed simply by copy and pasting (same with Codecademy and a lot of other coding challenges).  I don't want to frustrate people by making them scan through text to try to figure out what needs to be done.

The other alternative would be for us to move the test up top and have them be the description of what exactly needs to be done, and use the text purely for instruction. What do you think about that?

**Comment by AdventureBear** [comment]
I guess the question is who is the audience?   

If it's experienced developers, is there a way to "test out"...give them a single challenge with specs and have them submit a completed kitty app from a skeleton.  THat's just an idea 

Even though for this part I am 'experienced' it feels friction-ey to me.  

Maybe the solution is somewhere inbetween.  Teaching up top with a 1 sentence intro of WHAT the teaching is about... then "learn more" or "steps to pass".     I realize that's an extra click for both users.

Or maybe 1 sentence : 

**Objectives**
"The next 4 challenges will teach you how to choose a font, change your paragraph text to red and have a fallback font in case your first choice isn't available.  
*To pass this challenge: *  
-import lobster font from google fonts
-set h2 & p to use lobster font
-use monospace as  a backup
 
**OR**  
*Learn more about this step*

 ... (click here for more instruction)

----
MORE HERE

**Comment by terakilobyte** [comment]
I'm closing this as an issue here as it's nothing wrong with the code itself but more a content discussion issue.
