### ISSUE TITLE
"Run Test" function does not work and move on to next challenge

### ISSUE THREAD

**Issue by Darla013** [FreeCodeCamp/FreeCodeCamp#5830]
Challenge [Waypoint: Nest an Anchor Element within a Paragraph](http://www.freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment]
This is expected because you have not completed the challenge and have failing tests.

Thanks and happy coding!

**Comment by sludge256** [comment]
To be more specific you currently have two anchor elements. Delete the one that is not nested and it should pass. The original intention of the waypoint is for you to modify the existing anchor element.
