### ISSUE TITLE
missing comma?

### ISSUE THREAD

**Issue by mauroyamaguchi** [FreeCodeCamp/FreeCodeCamp#5837]
Challenge [Waypoint: Introducing JavaScript Object Notation JSON](http://www.freecodecamp.com/challenges/waypoint-introducing-javascript-object-notation-json#?solution=var%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201993%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%2C%0A%20%20%2F%2F%20Add%20record%20here%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Tsuyoshi%20Hiroshi%22%2C%0A%20%20%20%20%22title%22%3A%20%22Tonboyou%22%2C%0A%20%20%20%20%22release_year%22%3A%201987%2C%0A%20%20%20%20%22formats%22%3A%20%5B%0A%20%20%20%20%20%20%22CD%22%2C%0A%20%20%20%20%20%20%22DVD%22%2C%0A%20%20%20%20%20%20%22LP%22%5D%0A%20%20%7D%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1993,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ], 
    "gold": true
  }, <---------------------perhaps is a missing a comma, here?
  // Add record here
  {
    "artist": "Tsuyoshi Hiroshi",
    "title": "Tonboyou",
    "release_year": 1987,
    "formats": [
      "CD",
      "DVD",
      "LP"]
  }
];


```

**Comment by conorseed** [comment]
This just saved me! Couldn't figure out what I had done wrong, but adding the comma meant the test passed :)

**Comment by ShaggyTech** [comment]
I think there should be further instruction (maybe a "Note: ") that let the camper know about adding the comma between objects if there is more than one object in the array.  If it's already there when they start this waypoint, then they probably wouldn't even notice the comma there.

**Comment by Crosswood** [comment]
I agree. The notation to "// Add record here" is assumed to indicate, based on similar, earlier examples, that all modifications to the code should be below the notation. There should be something explaining how that comma works.

**Comment by qveksnela** [comment]
i'm so angry about it, b'cause there was no any word about com

**Comment by RvQ** [comment]
Now there is but it still got me googeling
Note
You will need a comma in between objects in JSON objects with more than one object in the array.

**Comment by atmosphereasmr** [comment]
Thank you so much!
