### ISSUE TITLE
Adjust Padding Waypoint (#40) is not accepted in Safari.

### ISSUE THREAD

**Issue by cloudclear** [FreeCodeCamp/FreeCodeCamp#5839]
Note: Switch browsers to resolve. Stay away from Safari, in general, for FCC?

**Comment by ltegman** [comment]
We used to only support Chrome but after a recent refactor we should work equally well on all modern browsers.

I am able to complete that challenge just fine in 9.0.2 on OS 10.11.2.

Anyone else able to repro this in Safari?

**Comment by sawant** [comment]
Completed fine in Sarari, Version 8.0.5 (10600.5.17) on OS X 10.10.3.

**Comment by bugron** [comment]
Seems this is user specific. Closing, thanks for posting.
