### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue 

### ISSUE THREAD

**Issue by ribeirojpn** [FreeCodeCamp/freecodecamp#584]
The steps are with the phrase "Syntax error, unrecognized expression"

**Comment by BerkeleyTrue** [comment]
Thank you for reporting this. Please see https://github.com/FreeCodeCamp/freecodecamp/issues/585 where we will be addressing syntax error issues.
