### ISSUE TITLE
D3 Waypoints

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#5845]
We need to:
1. create rough list (using checkboxes) of which concepts we want to teach, in what order
2. start building the challenges
3. QA the challenges and refine their copy

**Comment by mutantspore** [comment]
Ok you twisted my arm... I'll have a go at getting together your point #1 initially.
I'm sure at least @AdventureBear and hopefully @Storbeck will be able to review the initial list. I'm sure others are qualified also.
I don't have clue how the FCC teaching system works but I'm sure I'll be made aware along the way.

**Comment by QuincyLarson** [comment]
@mutantspore Awesome! I bet @benmcmahon100 or @SaintPeter could sit down on Skype later and walk you through the details of getting the challenges themselves together. 
For now, just get the rough list of what you'd like to teach, in what sequence, and we'll go from there.

**Comment by cdikibo** [comment]
# My Proposal for D3 Waypoints

**Comment by fraziern** [comment]
I consider myself a rank D3 beginner, but I'm fairly comfortable with the fcc PR workflow and I'd love to help put together challenges once the list is in place.

**Comment by mutantspore** [comment]
Ok I have left a longer message with @cdikibo but basically my 72 year old mother-in-law has had a car crash and is in hospital with fractured leg and other cut/bumps and bruises. There is talk of surgery and weeks of rehab. She will be ok but it will take time and I can already see my "spare" time being soaked up, I can't now commit to this in the way I had intended. I will try to comment, review, test and check anything that you need help with but I have to step back a pace. @AdventureBear is very keen to help though her time is limited also.

**Comment by carl-parrish** [comment]
Really looking forward to this. Let me know if I can help in any way.

**Comment by ColeDCrawford** [comment]
Also looking forward to this, starting to learn D3 for some digital humanities data viz projects.

**Comment by ZviRackover** [comment]
What is the status of the work on this item? Can we please get an update?

**Comment by pramodvspk** [comment]
I can help you out with D3.js, I have completed 3 D3 projects and have medium level experience on D3.js. I need someone to guide me so that I can start working on this, as this is the first time I am working with a code base

**Comment by BerkeleyTrue** [comment]
This work has moved to https://github.com/FreeCodeCamp/CurriculumExpansion
