### ISSUE TITLE
Bonfire: Symmetric Difference (difference length)

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#5850]
Challenge [Bonfire: Symmetric Difference](http://www.freecodecamp.com/challenges/bonfire-symmetric-difference#?solution=function%20sym(args)%20%7B%0A%20%20var%20symDif%20%3D%20%5B%5D%3B%0A%20%20symDif.push(3%2C4%2C5%2C4%2C5%2C5%2C5%2C5)%3B%0A%20%20%2F%2FsymDif.push(1%2C4%2C5%2C1%2C5%2C5%2C5%2C5)%3B%0A%20%20%2F%2FsymDif.push(7%2C4%2C6%2C2%2C3%2C3%2C3%2C4)%3B%0A%20%20return%20symDif%3B%0A%7D%0A%0Asym(%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D)%3B%0A%2F%2Fsym(%5B1%2C%202%2C%205%5D%2C%20%5B2%2C%203%2C%205%5D%2C%20%5B3%2C%204%2C%205%5D)%3B%0A%2F%2Fsym(%5B1%2C%201%2C%202%2C%205%5D%2C%20%5B2%2C%202%2C%203%2C%205%5D%2C%20%5B3%2C%204%2C%205%2C%205%5D)%3B%0A%2F%2Fsym(%5B3%2C%203%2C%203%2C%202%2C%205%5D%2C%20%5B2%2C%201%2C%205%2C%207%5D%2C%20%5B3%2C%204%2C%206%2C%206%5D%2C%20%5B1%2C%202%2C%203%5D)%3B%0A) has an issue.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sym(args) {
  var symDif = [];
  //#1
  symDif.push(3,4,5,4,5,5,5,5);
  //#2
  //symDif.push(1,4,5,1,5,5,5,5);
  //#3
  //symDif.push(7,4,6,2,3,3,3,4);
  return symDif;
}
//#1
sym([1, 2, 3], [5, 2, 1, 4]);
//#2
//sym([1, 2, 5], [2, 3, 5], [3, 4, 5]);
//sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]);
//#3
//sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3]);
```

Result checker response for cases 1, 2 and 3:
```code
#1 (return is: [3,4,5,4,5,5,5,5])
ok > sym([1, 2, 3], [5, 2, 1, 4]) should return [3, 5, 4].
not ok > sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5]
not ok > sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]) should return [1, 4, 5].
not ok > sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3]) should return [ 7, 4, 6, 2, 3 ]. 

#2 (return is: [1,4,5,1,5,5,5,5])
not ok > sym([1, 2, 3], [5, 2, 1, 4]) should return [3, 5, 4].
ok > sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5]
ok > sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]) should return [1, 4, 5].
not ok > sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3]) should return [ 7, 4, 6, 2, 3 ]. 

#3 (return is: [7,4,6,2,3,3,3,4])
not ok > sym([1, 2, 3], [5, 2, 1, 4]) should return [3, 5, 4].
not ok > sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5]
not ok > sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]) should return [1, 4, 5].
ok > sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3]) should return [ 7, 4, 6, 2, 3 ]. 
```
Not sure if symmetric difference can be of any length as long as it includes only right digits.

**Comment by SaintPeter** [comment]
I don't know what you are saying here.  Are you saying that so long as the first elements match that it passes the test, regardless of if it's much longer?

**Comment by rfprod** [comment]
yes, if I understand it right [3,4,5,4,5,5,5,5] is invalid answer if result must be [3, 5, 4] (not depending on the order).

**Comment by SaintPeter** [comment]
Confirmed.

Looks like the test cases need some additional work.
