### ISSUE TITLE
Description and tests don't match

### ISSUE THREAD

**Issue by legend911** [FreeCodeCamp/FreeCodeCamp#5852]
Challenge [Checkpoint: Stand in Line](http://www.freecodecamp.com/challenges/checkpoint-stand-in-line#?solution=%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0Afunction%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20myArr.push(item)%3B%0A%20%20%0A%20%20myArr.splice(0%2C%201)%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0Aconsole.log(queue(myArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(myArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myArr = [1,2,3,4,5];

function queue(arr, item) {
  // Your code here
  myArr.push(item);
  
  myArr.splice(0, 1);
  return item;  // Change this line
}

// Display Code
console.log("Before: " + JSON.stringify(myArr));
console.log(queue(myArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(myArr));

```

You are asked the follow, (Add the item onto the end of the array, then remove the first element of the array.). However, you are tested on this (queue([2], 1) should return 2). The test requires you to order the queue after inserting 1. The description doesn't state you must reorder the array.

**Comment by legend911** [comment]
<img width="774" alt="issue 1" src="https://cloud.githubusercontent.com/assets/9207522/12090691/12c29410-b2bf-11e5-82e8-c9d2e172cae2.png">

**Comment by legend911** [comment]
Now I just don't understand why my code isn't solving this checkpoint.

<img width="774" alt="issue 2" src="https://cloud.githubusercontent.com/assets/9207522/12090858/72768d84-b2c0-11e5-8d45-50c590080ad3.png">

**Comment by ltegman** [comment]
You're operating on `myArr` and not the array that's being passed into the function. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to get confirmation that what you're seeing is a site bug before filing a Github issue.

Thanks and happy coding!

**Comment by jyapyuco** [comment]
I'm having the same problem as @legend911 even though I used arr instead of myArr within the queue function.

![bug](https://cloud.githubusercontent.com/assets/11827122/12119561/6619b2bc-b407-11e5-8126-6ddae61a3528.png)

**Comment by sludge256** [comment]
`splice()` will return an array and not a number as expected by the tests.

**Comment by t3chm4n** [comment]
Try using push and shift array functions...
