### ISSUE TITLE
checkpoint: celsius to fahrenheit

### ISSUE THREAD

**Issue by ThijsHermans** [FreeCodeCamp/FreeCodeCamp#5853]
The code below is obviously bugged. There is no input variable named 'fahrenheit'. It should be replaced with 'celsius'. It would be advisable to give a better look before closing other topics: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5802

Kind regards!

Standard code:
```javascript
function convert(celsius) {
  // Only change code below this line
  

  // Only change code above this line 
  if ( typeof fahrenheit !== 'undefined' ) {
  return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(30);

```

Correct code
```javascript
function convert(celsius) {
  // Only change code below this line
  

  // Only change code above this line 
  if ( typeof celsius !== 'undefined' ) {
  return celsius;
  } else {
    return 'celsius not defined';
  }
}

// Change the inputs below to test your code
convert(30);

```

**Comment by ltegman** [comment]
>You are given a variable `celsius` representing a temperature in Celsius. Create a variable `fahrenheit` and apply the algorithm to assign it the corresponding temperature in Fahrenheit.

Please read the instructions carefully before filing a bug. Thanks and happy coding!
