### ISSUE TITLE
Checkpoint: convert celsius to fahrenheit should be reverse

### ISSUE THREAD

**Issue by dany-on-demand** [FreeCodeCamp/FreeCodeCamp#5854]
## As evidenced by [democracy](http://strawpoll.me/6448113) everyone prefers Celsius to Fahrenheit units.

Logically it follows that the checkpoint should be about converting Fahrenheit units to Celsius.

The equation is the same just in reverse: `(fahrenheit - 32) * 5/9`

**Comment by ltegman** [comment]
Thanks but this doesn't effect the learning outcome of this waypoint.
