### ISSUE TITLE
Incorrect Initialization of Example Code

### ISSUE THREAD

**Issue by Khawaga** [FreeCodeCamp/FreeCodeCamp#5856]
Challenge [Waypoint: Manipulate Arrays With pop](http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop#?solution=%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20removedFromOurArray%20%3D%20ourArray.pop()%3B%20%0A%2F%2F%20removedFromOurArray%20now%20equals%203%2C%20and%20ourArray%20now%20equals%20%5B1%2C2%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20removedFromMyArray%3B%0A%0A%0A) has an issue.
User Agent is: <code>Chrome/49.0.2610.0</code>.

When first opening this Waypoint I am presented with the following example code, which would result in a failed submission as the array is not initialized properly:

![before reset](https://cloud.githubusercontent.com/assets/7104015/12092951/e17063de-b308-11e5-9a54-d14e6d635fcd.PNG)

After pressing the "Reset" button the correct code shows up:

![after reset](https://cloud.githubusercontent.com/assets/7104015/12092958/e888d7d2-b308-11e5-9ee3-f796bc38e2ff.PNG)

Please note that the first piece of code is initialized by default, and I have not made any changes to it. This is not the only Waypoint affected with this issue, as the previous one (Manipulate Arrays With push), and several following Waypoints also have similar behavior.

**Comment by ltegman** [comment]
This means you or someone else has already visited this waypoint before and it is loading code from localStorage rather than starting fresh from the new seed code. This is normal behaviour after a waypoint has been visited. You can press the reset button to start fresh, as you have discovered.

Thanks and happy coding!
