### ISSUE TITLE
Error not using "=" to concat when I am

### ISSUE THREAD

**Issue by cohenpts** [FreeCodeCamp/FreeCodeCamp#5857]
Challenge [Waypoint: Concatenating Strings with Plus Operator](http://www.freecodecamp.com/challenges/waypoint-concatenating-strings-with-plus-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20'This%20is%20the%20start.%20'%20%2B%20'This%20is%20the%20end.'%20%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = 'This is the start. ' + 'This is the end.' ;



```

**Comment by nigeljoy** [comment]
Please descrive the error or issue. That title doesn't make sense

**Comment by HoBi** [comment]
This is not pass with single quotes (`'`), only with double quotes (`"`). It's a bug in test I think.

**Comment by SaintPeter** [comment]
The issue is the space before the `;` - it looks like the tests are overly specific.  I was able to get it to pass with the supplied code by removing the space before the semicolon.

**Comment by HoBi** [comment]
@SaintPeter :+1: you are right. *I replaced that space while I changed single quotes to double quotes so that works.*

I can probably fix that tomorrow, but if anybody wants to do that, take it.
