### ISSUE TITLE
Waypoint states that I changed the Global var when unchanged 

### ISSUE THREAD

**Issue by cohenpts** [FreeCodeCamp/FreeCodeCamp#5858]
Challenge [Waypoint: Global vs Local Scope in Functions](http://www.freecodecamp.com/challenges/waypoint-global-vs-local-scope-in-functions#?solution=%2F%2F%20Setup%0Avar%20outerWear%20%3D%20%22T-Shirt%22%3B%0A%0Afunction%20myFunction()%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20outerWear%20%3D%20%22sweater%22%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20outerWear%3B%0A%7D%0A%0AmyFunction()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var outerWear = "T-Shirt";

function myFunction() {
  // Only change code below this line
  outerWear = "sweater";
  
  
  // Only change code above this line
  return outerWear;
}

myFunction();

```

**Comment by sludge256** [comment]
It's because of:
```js
outerWear = "sweater";
```
You have to modify the code so that it changes the value of local variable instead of the global variable.
https://gitter.im/FreeCodeCamp/Help is a good resource if you need more clarification.

**Comment by ltegman** [comment]
@sludge256 is correct. Thanks and happy coding!
