### ISSUE TITLE
Instructions Do Not match Challenge description

### ISSUE THREAD

**Issue by msuzio** [FreeCodeCamp/FreeCodeCamp#5859]
Challenge [Waypoint: Multiply Two Decimals with JavaScript](http://www.freecodecamp.com/challenges/waypoint-multiply-two-decimals-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
the issue is that the challenge instructions say:
Instructions

Change the 0.0 so that product will equal 5.0.
when the example code to change does not have a 0.0 term in it.  I believe the instructions intended to say to change the "2.0"

My code:
```javascript
var product = 2.0 * 2.5;


// Only change code above this line.

(function(y){return 'product='+y;})(product);

```

**Comment by sludge256** [comment]
This is what I get when I load the waypoint.
![image](https://cloud.githubusercontent.com/assets/10524623/12096639/8aa3e5a4-b2cb-11e5-8b6e-b1b71828b68e.png)

I believe this may be related to all the other cases where people are getting already completed waypoints.

**Comment by ltegman** [comment]
You are looking at an old version of the code that must be from a previous visit to this waypoint before we recently rewrote the JS curriculum. Please press the reset button to start from the new seed code.

Thanks and happy coding!
