### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue 

### ISSUE THREAD

**Issue by millinet** [FreeCodeCamp/freecodecamp#586]
Basically - and funny - when I paste this "<img src="http://bit.ly/fcc-kittens" - the new editor is broken (guess special characters?)

**Comment by BerkeleyTrue** [comment]
@millinet Thanks for reporting.

Do you mean the editor itself breaks and is unusable?

**Comment by millinet** [comment]
Ok. So only pasting this: "   <img src="http://bit.ly/fcc-kittens    " makes the bullet list hidden or broken

**Comment by millinet** [comment]
Weird bug. I admit. No one would do this ^^

**Comment by BerkeleyTrue** [comment]
Not sure what is going on here but adding `">` returns everything to normal.

@millinet Thanks again for reporting but since this is not breaking(or at least not completely) I am going to close this issue. Thanks again and good luck with the rest of the challenges!

**Comment by millinet** [comment]
I understand ;)
