### ISSUE TITLE
Wapoints have cide examles alreafy solved

### ISSUE THREAD

**Issue by msuzio** [FreeCodeCamp/FreeCodeCamp#5860]
Challenge [Waypoint: Divide one Decimal by Another with JavaScript](http://www.freecodecamp.com/challenges/waypoint-divide-one-decimal-by-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
This wapoint and the prior two all three have example code that already has the correct answer, not matching the chanhe instructions that seem to describe another code block that starts out as incorrect.
My code:
```javascript
var quotient = 4.4 / 2.0;


// Only change code above this line.

(function(y){return 'quotient='+y;})(quotient);

```

**Comment by ltegman** [comment]
This is code from a previous version of the waypoint, meaning to must have visited and worked on this waypoint before. Please press the reset button if you would like to start over.

Thanks and happy coding!
