### ISSUE TITLE
Checkpoint: Record Collection

### ISSUE THREAD

**Issue by HoBi** [FreeCodeCamp/FreeCodeCamp#5861]
Challenge [Checkpoint: Record Collection](http://www.freecodecamp.com/challenges/checkpoint-record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20update(id%2C%20prop%2C%20value)%20%7B%0A%0A%20%20if%20(value%20!%3D%3D%20%22%22)%20%7B%0A%20%20collection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%20%20%20%0A%20%20%20%20if%20(prop%20%3D%3D%3D%20%22tracks%22)%20%7B%0A%20%20%20%20%20%20if%20(collection%5Bid%5D.hasOwnProperty('tracks'))%20%7B%0A%20%20%20%20%20%20%20%20collection%5Bid%5D.tracks.push(value)%3B%20%20%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20collection%5Bid%5D.tracks%20%3D%20%5Bvalue%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20delete%20collection%5Bid%5D%5Bprop%5D%3B%0A%20%20%7D%0A%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0Aupdate(5439%2C%20%22tracks%22%2C%20%22Addicted%20to%20Love%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {

  if (value !== "") {
  collection[id][prop] = value;
    
    if (prop === "tracks") {
      if (collection[id].hasOwnProperty('tracks')) {
        collection[id].tracks.push(value);  
      } else {
        collection[id].tracks = [value];
      }
    }    
  } else {
    delete collection[id][prop];
  }

  return collection;
}

// Alter values below to test your code
update(5439, "tracks", "Addicted to Love");
```

The 3rd test (`After update(1245, "tracks", "Addicted to Love"), tracks should have a length of 1`) still failing and I have no idea why, and I think my code should work. I also discuss it on chat, but nobody knows why it is not passing. Maybe the test is wrong?

Console tells me `TypeError: collection[id].tracks.push is not a function`.

By the way, the test for it is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3959).

**Comment by 0x0936** [comment]
Tested this in dev console then in the challenge on live site. The issue is that `collection[id][prop]` is being overwritten by value when value is not empty. Fixing the order of conditionals does allow for `collection[id].tracks.push(value)`. Here is one way of writing it:

```
if (value !== "" && prop !== "tracks") {
  collection[id][prop] = value;
} else if (value !== "" && prop === "tracks") {
  if (collection[id].hasOwnProperty('tracks')) {
    collection[id].tracks.push(value);  // this now works!
  }
} else if (value !== "" && prop !== "tracks") {
  collection[id][prop] = value;
} else {
  delete collection[id][prop];
}
```

**Comment by HoBi** [comment]
@0x0936 Ahh, I can see it now. So it was my bad, haha. I moved the `collection[id][prop] = value;` to else statement after `prop === "tracks"` and it works now.

Sorry, my fault.
