### ISSUE TITLE
Need to have examples with stand alone complete code

### ISSUE THREAD

**Issue by prasannamate** [FreeCodeCamp/FreeCodeCamp#5863]
The examples given on timbre.js website look good, but need to have complete code that can be copy pasted in a text file and tried out in a browser by itself.

**Comment by ltegman** [comment]
If you are indeed experiencing an issue please file another bug that follows [these guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue)
