### ISSUE TITLE
Basic Javascript lesson order

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#5864]
Based on this conversation,
[January 4, 2016 11:36 AM](https://gitter.im/FreeCodeCamp/Help?at=568ac9d93c689402692605ed)

Shouldn't [#48 Waypoint: Write Reusable JavaScript with Functions](http://www.freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions)
to [#54 Waypoint: Assignment with a Returned Value](http://www.freecodecamp.com/challenges/waypoint-assignment-with-a-returned-value)

Come before
[#22 Checkpoint: Convert Celsius to Fahrenheit](http://www.freecodecamp.com/challenges/checkpoint-convert-celsius-to-fahrenheit)
[#37 Checkpoint: Word Blanks](http://www.freecodecamp.com/challenges/checkpoint-word-blanks)

I haven't gone through all the new material yet so I'm not 100% sure what knowledge campers should have up to certain points. However, it seems that moving these checkpoints elsewhere may help them comprehend the existing code that is presented if they are aware of how functions work first.

**Comment by SaintPeter** [comment]
You have perfectly described by torment.  There is always a bit of a chicken and egg problem when doing this sort of curriculm - how can we teach X when they don't know Y.  I went back and forth over this during the building of the curriculum, but I ultimately decided that users could "handle" the idea of using a pre-laid-out function without too much explanation for these two challenges.  Ultimately, I don't think that that is where campers are having problems.

I'm open to suggestions, of course.  It just seemed better to introduce more complex concepts later, after establishing a foundation with other concepts.

**Comment by sludge256** [comment]
Yea I would agree that they're definitely still doable without having gone through those waypoints first.
I went back and looked at the checkpoints in more detail. The instructions do push them in the right direction even though they may not understand where the values came from or how they got there and work.

I wonder if new campers would prefer to see the function they're working on,
```
function convert(celsius) {
  // Only change code below this line
  

  // Only change code above this line
  if ( typeof fahrenheit !== 'undefined' ) {
  return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(30);
```
Or alternatively, seeing and modifying snippets,
```js
var fahrenheit = celsius; //modify this line
```
In the case that all the code around
```js
  // Only change code below this line

  // Only change code above this line
```
adds to their confusion or makes the problem seem more complex than it actually is.

Some things I've noticed are that some users miss the fact that the parameters are there to be used (despite variable names being mentioned in the instructions) and sometimes try using hard coded values too.
However, it seems fine for now I just thought it was something worth considering and discussing.

**Comment by SaintPeter** [comment]
Keep in mind that, as a "checkpoint", this is intended to be more of a "blank page" challenge.  If we added the sample code, even as simple as it is, they would lose the experience of "starting from nothing" . . . even if they're really not.  

Our purpose is not to eliminate all possible confusion.  I would consider some confusion to be "good" confusion.   That said, if you're getting the same question over and over, then maybe we do need to revisit this.  I don't spend as much time as I once did in the help rooms, so your feedback is appreciated.
