### ISSUE TITLE
a glitch

### ISSUE THREAD

**Issue by rainingcatsanddogs** [FreeCodeCamp/FreeCodeCamp#5866]
Challenge [Waypoint: Turn an Image into a Link](http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>


<p>Click here for <a href="#">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<a href="#"><img src="http://bit.ly/fcc-running-cats"></a>
```

**Comment by sludge256** [comment]
>Nest the **existing** img element within an a element.

You've done what the waypoint asks but on an img element that you have created yourself at the bottom.

**Comment by ltegman** [comment]
@sludge256 is correct. Thanks and happy coding!

**Comment by jthrons69** [comment]
Sent from Yahoo Mail on Android 
 
  On Mon, Jan 4, 2016 at 2:57 PM, sludge256<notifications@github.com> wrote:   

Nest the existing img element within an a element.


You've done what the waypoint asks but on an img element that you have created yourself at the bottom.
