### ISSUE TITLE
Use an ID Attribute to style an Element

### ISSUE THREAD

**Issue by nandinimenon77** [FreeCodeCamp/FreeCodeCamp#5867]
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  #cat-photo-element{
    background-color: green;
  }
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }

  .gray-background {
    background-color: gray;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<div class="gray-background">
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="/submit-cat-photo" id="cat-photo-form">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
 
Your form element should have the background-color of green. Haven't I?

**Comment by username1001** [comment]
Nope. Read the directions carefully: your 'form element' should have the background-color of green. You have your "background-color:green" in the wrong place(div id).

**Comment by ltegman** [comment]
Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance with challenges and only create Github issues once others have confirmed the problem is with the site and not your code.

Thanks and happy coding!

**Comment by thandarlin** [comment]
Uphyowai.linn.13@gmail.com
On Jan 5, 2016 3:32 AM, "nandinimenon77" <notifications@github.com> wrote:
>
> #cat-photo-element{ background-color: green; } red-text { color: red; }
h2 { font-family: Lobster, Monospace; } p { font-size: 16px; font-family:
Monospace; } thick-green-border { border-color: green; border-width: 10px;
border-style: solid; border-radius: 50%; } smaller-image { width: 100px; }
gray-background { background-color: gray; }
