### ISSUE TITLE
Is the Current Year 2016 or  2015?

### ISSUE THREAD

**Issue by vanblargan** [FreeCodeCamp/FreeCodeCamp#5869]
With the the new year now recently 2016...
The test still stays:
friendly(["2015-07-01", "2015-07-04"]) should return ["July 1st","4th"].
But shouldn't both years be ommited only if first year is the current year (which is 2016, not 2015).

However, the test also says:
friendly(["2016-03-01", "2016-05-05"]) should return ["March 1st","May 5th"]
which implies it is following the rule that the current year is 2016.

Am I missing something here?

**Comment by vanblargan** [comment]
This is for Bonfire: Friendly Dates.

**Comment by SaintPeter** [comment]
Sounds like we need to update the tests on this one . . . or maybe make them more generic.

**Comment by jbmartinez** [comment]
I incremented the year in every test except the last one in #5891, some of the tests didn't need to be updated but I did it anyways. That should be enough for passing the tests during 2016, but I think those tests could be more generic

**Comment by gasperno** [comment]
@SaintPeter I think this issue can be closed now.
