### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue 

### ISSUE THREAD

**Issue by mdanro** [FreeCodeCamp/freecodecamp#587]
In the example of HERE IS MY HANDLE HERE IS MY SPOUT
the first letter is capitalized, the exercise should specify that the other part of the word should be lower cased.

**Comment by terakilobyte** [comment]
@mdanro Thanks for the feedback. Part of the purpose of this and a lot of bonfires is to get people looking at the output of the test to determine what may not be functioning correctly! Also, this is actually the definition of title casing something. http://www.grammar-monster.com/lessons/capital_letters_title_case.htm
