### ISSUE TITLE
Add Elements Within Bootstrap Wells

### ISSUE THREAD

**Issue by AnebiBenjamin** [FreeCodeCamp/FreeCodeCamp#5872]
Challenge [Waypoint: Add Elements within your Bootstrap Wells]

Although the instruction says ```Nest three button elements within each of your well div elements``` ,
I was left scratching my head, because I created only two Well Div elements earlier. 
Hence, after adding the ```buttons``` , I got 4 instead of the 6 indicated

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  
  <div class="row">
   
    <div class="col-xs-6">
    
      
      <div class="well">
        <button> </button>


      </div>
    </div>
   
    <div class="col-xs-6">
      
      
      <div class="well">
        <button> </button>


      </div>
    </div>
  </div>
</div>

```

**Comment by AnebiBenjamin** [comment]
- [ ] fixed issue #5872 . 
It was a simple fix. I had been over thought the problem, but after a walk and a few minutes doing something else, I discovered that all that was needed were two extra ```button```  elements  to be nested within each div element containing the ```.well``` classes.

**Comment by mohannadsawalhi** [comment]
First well 3 button
Second well 3 button :)

**Comment by Lerocha6** [comment]
Can´t find the mistake, I´m stuked on this challeng...

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  
  <div class="row">
   
     <div class="col-xs-6">  
    <div class="well">
       <button></button>
      </div>
    </div>
    
     <div class="col-xs-6">
      <div class="well">
     <button></button>
    </div>
    </div>
  
   <div class="col-xs-6">
       <div class="well">
         <button></button>      
    </div>    
  </div>
  
 </div>
</div>

**Comment by kaungkhant620** [comment]
this one is OK....
my code:

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button> </button>



      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
         <button> </button>


      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button> </button>
    
    
     </div>
    </div>
    
    <div class="col-xs-6">
      <div class="well">
        <button> </button>



      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button> </button>



      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button> </button>



      </div>
    </div>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  </div>
</div>

**Comment by Robinhoeh** [comment]
This worked for me!


<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button></button>
          <button></button>
            <button></button>


      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
          <button></button>
            <button></button>
        



      </div>
    </div>
  </div>
</div>

**Comment by Robinhoeh** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button></button>
          <button></button>
            <button></button>


      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
          <button></button>
            <button></button>
        



      </div>
    </div>
  </div>
</div>

**Comment by texas2010** [comment]
@Lerocha6 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by texas2010** [comment]
@Robinhoeh 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by pognat** [comment]
Don't read too much into what is being asked.  The hint is in the second section.  Nesting 3 buttons in the wells.  Took me a bit but finally received the aha moment when I broke it down.
