### ISSUE TITLE
palindrome("1 eye for of 1 eye.") -> "eyeforofeye" should return true 

### ISSUE THREAD

**Issue by crapfruit** [FreeCodeCamp/FreeCodeCamp#5874]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20expr%20%3D%20%2F%5B%5Ea-z%5D%2Fgi%3B%0A%20%20str%20%3D%20str.replace(expr%2C%20%22%22)%3B%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20var%20revStr%20%3D%20str.split(%22%22).reverse().join(%22%22)%3B%0A%20%20console.log('currentString%3A%20'%2C%20str)%3B%0A%20%20console.log('reversedString%3A%20'%2C%20revStr)%3B%0A%20%20var%20result%20%3D%20(revStr%20%3D%3D%3D%20str)%3B%0A%20%20console.log('result%3A%20'%2C%20result)%3B%0A%20%20return%20result%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36 OPR/34.0.2036.25</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var expr = /[^a-z]/gi;
  str = str.replace(expr, "");
  str = str.toLowerCase();
  var revStr = str.split("").reverse().join("");
  console.log('currentString: ', str);
  console.log('reversedString: ', revStr);
  var result = (revStr === str);
  console.log('result: ', result);
  return result;
}



palindrome("eye");

```
![issue-5874-palindrome](https://cloud.githubusercontent.com/assets/12182625/12104514/80d1e52c-b34c-11e5-81f6-179d504ded1f.png)

**Comment by sludge256** [comment]
Don't remove numbers from the string.

**Comment by BerkeleyTrue** [comment]
@sludge256 is correct, you should not remove the numbers.

Try
```js
var expr = /[^a-z0-9]/gi;
```

Also, you may want to `toLowerCase` before `replace`

Happy Coding!

**Comment by suraj-davariya** [comment]
@crapfruit  please consider that they asked to remove all the non-alphanumeric characters. Do not remove numbers because its a part of the alphanumeric keyboard!
Try this:
`str = str.replace(/[\W\s\_]/gi,"");`
