### ISSUE TITLE
the instructions do not match the goals checklist

### ISSUE THREAD

**Issue by MissMogly** [FreeCodeCamp/FreeCodeCamp#5875]
Challenge [Waypoint: Understanding Uninitialized Variables](http://www.freecodecamp.com/challenges/waypoint-understanding-uninitialized-variables#?solution=%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0Avar%20a%20%3D%205%3B%0Avar%20b%20%3D%2010%3B%0Avar%20c%20%3D%20%22I%20am%20a%22%3B%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
the instructions do not match the goal checklist
My code:
```javascript
// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line
var a = 5;
var b = 10;
var c = "I am a";
a = a + 1;
b = b + 5;
c = c + " String!";


```
![image](https://cloud.githubusercontent.com/assets/13266366/12104814/dec97fd0-b303-11e5-8e44-741f4aaa3607.png)

**Comment by ShaggyTech** [comment]
The problem with this one appears to be that the last test is allowing the camper to change the code below the line and still pass the test.  I'll see if I can fix this one.

**Comment by username1001** [comment]
You changed the wrong code. To fix this, hit the 'reset' button, and start over. There's a comment that says "Do not change code below this line", I'm guessing you missed it. No big deal. Now, work with the code above that comment, the variables that aren't assigned anything: var a; var b; var c; assign them what the directions say to(that is, initialize them). Good luck!

**Comment by SaintPeter** [comment]
There is a limited extent to our ability to detect improper user behavior.  I can't tell if you deliberately didn't follow the instructions or simply didn't see them.

Ultimately, though, it does appear that you understood the concepts, so that's a win.

I'm going to close this because there is only so much we can do.

**Comment by ShaggyTech** [comment]
@SaintPeter I think I realized what the issue was that @MissMogly as pointing out.  The instructions state: 
>Initialize the three variables a, b, and c with **5, 10**, and "I am a"

The test says:
> a should have 6
>b should have 15

I just originally misunderstood what the issue was.  If you can reopen this I'll add the fix.

**Comment by MissMogly** [comment]
That's it!!!! sorry all i had found it on my lunch break at work and
couldn't really respond with a lot of detail. Thanks Brandon Eichler for
finding it!

Megan kamphaus

**Comment by SaintPeter** [comment]
Ahh, i understand.   Yes,  the test details ć could be clearer.

**Comment by ShaggyTech** [comment]
@SaintPeter  I've figured a way to make sure the code hasn't been changed below the line.  Can I still do a pull request even though this issue is closed?

**Comment by ShaggyTech** [comment]
@SaintPeter I know you already closed this issue but I've been trying to make this work for several hours and figured I would make the pull request anyways. #5879 Fixes this.  Try it out and let me know what you think.  It could also be adjusted slightly and used in other waypoints/bonfires as well.

Even if it doesn't get used I've at least exploded my brain with new regex knowledge :+1:

**Comment by ShaggyTech** [comment]
I've had to make a new branch and do another PR because I somehow messed up the last one.  My apologies.  New PR is #5880
