### ISSUE TITLE
Include vim keyboard! + UX Improvements

### ISSUE THREAD

**Issue by AndrewMcSwain** [FreeCodeCamp/FreeCodeCamp#5877]
It's a pipedream, I know. 
.
Is the map a good idea?
The map is a good idea, for reasons I explained here [https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5745]. It's a good concept. 

Navigation
*Access to a simplified map on exercise.
*Arrows keys to navigate exercises.
*an input box between the arrows <o> to skip foward and backwards a set number of exercises
*find next unfinished exercise (especially important after this recent update to Basic Javascript)

**Comment by ltegman** [comment]
I defer UI stuff to @QuincyLarson but I don't see any of this happening besides potentially going to the next unfinished challenge.

1 and 3 would add a lot of UI clutter to a view that is already stretching the limits of how much it is trying to accomplish in the real estate available to it, 2 is very likely to catch people off guard rather than help them.

Anyways, I'm interested to hear what other people think.

**Comment by SaintPeter** [comment]
We have a number of plans for improving the overall navigation of the site, but none of them include adding vim style navigation . . . that said, if you wanted to modify the site and add it, we might be willing to accept the PR, so long as it's not too ugly or slows down the site.

I will say that I see the primary use of the site as being completely linear - you start where you start, you move forward, completing waypoints/bonfires/etc as you go.

**Comment by QuincyLarson** [comment]
We can definitely consider adding VIM-style editing shortcuts to our code editors (though I don't think we should go so far as to allow for the multiple modes). 

We are working on our hotkey milestone here: https://github.com/FreeCodeCamp/freecodecamp/milestones

**Comment by pmyjavec** [comment]
@QuincyLarson, this is one of the killer features of Hacker Rank IMO. Is it something you would look at doing just in the editor?

**Comment by QuincyLarson** [comment]
@pmyjavec If we were to add something like this, it would be a ways down the line. We probably couldn't properly simulate VIM (with the 3 modes) without a significant overhaul of the editor.
