### ISSUE TITLE
På

### ISSUE THREAD

**Issue by kattenodin** [FreeCodeCamp/FreeCodeCamp#5878]
Challenge [Waypoint: Use the Javascript Console](http://www.freecodecamp.com/challenges/waypoint-use-the-javascript-console#?solution=%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; LG-D955 Build/KOT49I.D95520b) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps and a description on how to reproduce the issue.

Happy Coding!
