### ISSUE TITLE
Screen frozen after executing code once, Bonfire:Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by Toe125** [FreeCodeCamp/FreeCodeCamp#5882]
![frozen](https://cloud.githubusercontent.com/assets/15791247/12108157/45001290-b3af-11e5-9c89-0cc2374e69fb.png)

I executed the code once to test it, now whenever I go to this page the screen freezes before I can do anything. I can't interact with anything on the page (ex: can't type in code or click learn,map,chat etc. tabs at top).

I have tried refreshing the page, and closing/opening the entire browser again.

**Comment by ltegman** [comment]
You have an infinite loop in your code. You can either [disable code auto-run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) or [clear the solution from localStorage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage). Thanks and happy coding!
