### ISSUE TITLE
Waypoint: Selecting from many options with Switch Statements

### ISSUE THREAD

**Issue by username1001** [FreeCodeCamp/FreeCodeCamp#5884]
I'm getting errors in this waypoint. Each time I use "break;", it says: unreachable 'break' after 'return'. But I passed the waypoint. Should I have used something other than return? Or is this a bug?
![fcc](https://cloud.githubusercontent.com/assets/11285175/12109626/917415c6-b338-11e5-8451-478127eb3856.PNG)

**Comment by raisedadead** [comment]
Its not a bug, your `break` statement is indeed unreachable, because in the code above, in all of the case statements you have added a `return` statement before the `break`. Hence when the code executes, it will return (exit out of function `myTest`), before the break statement.

Your code passes because, its actually a logical error, i.e, the code may look correct but logically wont be executed, hence the warning on the editor window.

Please ask for further guidance at [Help Chat](https://gitter.im/FreeCodeCamp/Help) and also refer [these guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by MariamShqair** [comment]
you should say :

answer = "alpha";
answer = "gamma";
answer = "delta";

have a good day ^_^

**Comment by ltegman** [comment]
@raisedadead and @MariamShqair are correct. Thanks and happy coding!

**Comment by LucianoBritis** [comment]
The coding does not by scanning the code "break" note that if you remove your code is clean, but not answer the last topic of the exercise.

function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch (val){
    case answer = 1:
    return("alpha");
    break;
      
    case answer = 2:
    return("beta");
    break;
      
    case answer = 3:
    return ("gamma");
    break;
      
    case answer = 4:
    return("delta");
 } 
  
  // Only change code above this line  
  return answer;
}

// Change this value to test
myTest(1);

**Comment by PankajShandilya** [comment]
![download](https://cloud.githubusercontent.com/assets/7963866/12537746/b108acd0-c2ec-11e5-81da-7e338f50b806.png)

**Comment by viraj89** [comment]
```
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val)
  {
    case 1:
      answer = "alpha";
      break;
      
      case 2:
      answer= "beta";
      break;
      
      case 3:
      answer= "gamma";
      break;
      
      case 4:
      answer= "delta";
      break;
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(1);
```

This should be your error or warning free code. 
@username1001 Did you notice at the top we created an empty string -  `var answer="";` And that's where we can save the alpha, beta, gamma and delta. 

Another thing we all and @PankajShandilya need to remember is - when to use break and when to use return. 
break is used to exit from a loop. (here switch case is loop) 
return is used to exit from the function. (hence `  return answer;  `)

read about break and return more here - https://goo.gl/bhhudP

**Comment by PankajShandilya** [comment]
Thanks brother i understand the term. 

thank you again for
very quick response.

**Comment by elvinege** [comment]
`function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case 1:
      answer = "alpha";
      break;
      
    case 2:
      answer = "beta";
      break;
      
    case 3: 
      answer = "gamma";
      break;
      
    case 4:
      answer = "delta";
  // Only change code above this line  
  return answer;
  }
}
// Change this value to test
myTest(1);`

I couldn't find an error in this code block. I could pass last 3 part of this exercise but I couldn't pass from first three.

**Comment by raisedadead** [comment]
@elvinege 
You have a problem here:
```javascript
return answer;
}
}
```
move the `}` after `return answer` to line marked with `<<--------------------` below
```javascript
answer = "delta";
} // <<--------------------
// Only change code above this line
```

if you need further help, please visit [Help Chat](https://gitter.im/FreeCodeCamp/Help)

**Comment by aaronk73** [comment]
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch (val){
    case 1:
      answer ="alpha";
      break;
      case 2:
     answer = "beta";
      break;         
      case 3:
     answer = "gamma";
      break;
      case 4:
      answer = "delta";
  
  }
  // Only change code above this line  
  return answer;  

}

// Change this value to test
myTest(1);

**Comment by thinnling** [comment]
Thank you everyone.  This really helped me understand switch statements better.

**Comment by mcmellan** [comment]
i cant seem to know what I am doing wrong. I don't know if I am being too clumsy, but sometimes I'll have a code that would not work then I refresh or clear my cache and the same code would go through. 
![screen shot 2016-06-03 at 5 16 22 pm](https://cloud.githubusercontent.com/assets/16537628/15796234/69587f1c-29af-11e6-8e35-b5a605266339.png)

**Comment by Olaof** [comment]
Here's indeed the right solution after a few research, simplest the best:
function caseInSwitch(val) {
  var answer = "";
  switch (val) {
    case 1:
      answer = "alpha";
      break;
    case 2:
      answer = "beta";
      break;
    case 3:
      answer = "gamma";
      break;
    case 4:
      answer = "delta";
      break;
      
  }
  

  
  // Only change code above this line  
  return answer;  

}
// Change this value to test
caseInSwitch(1);

**Comment by jmizrachi** [comment]
`
function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case 1:
      answer="alpha";
      break;
    case 2:
      answer="beta";
      break;
    case 3: 
      answer="gamma";
      break;
    case 4: 
      answer="delta";
      break;
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);
`

So the thing is you are not returning a value. You are setting the variable answer to different values based on the different cases.

**Comment by jmizrachi** [comment]
``
function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case 1:
      answer="alpha";
      break;
    case 2:
      answer="beta";
      break;
    case 3: 
      answer="gamma";
      break;
    case 4: 
      answer="delta";
      break;
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);

**Comment by jmizrachi** [comment]
```

function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case 1:
      answer="alpha";
      break;
    case 2:
      answer="beta";
      break;
    case 3: 
      answer="gamma";
      break;
    case 4: 
      answer="delta";
      break;
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);

```

**Comment by BEBEDYDY** [comment]
function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  switch (val){
    case 1:
      answer="alpha";
     
      break;
    case 2:
      answer ="beta";
     
      break;
    case 3:
      answer ="gamma";
      
      break;
    case 4:
      answer ="delta";
      
      break;
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(2);




after return you can not use break.

**Comment by tameg73** [comment]
function is not myTest(val) it is caseInSwitch(val) and that is mistake

**Comment by DragutinDjokovic** [comment]
case (val = 1):
   answer = "alpha";
   break;

**Comment by ypokkinen** [comment]
You have an other error too. In instructions it reads: case values are tested with strict equality (===).
So you aren't testing right case values.You should test like this:  case === 1:

**Comment by RomingArt** [comment]
I was not able to make it work with strict equality but I used the code below to pass the section if people think it is wrong please leave a comment. Thanks 
`function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case 1:
      answer = "alpha";
         break;
    case 2:
       answer = "beta";
         break;
    case 3:
       answer = "gamma";
         break;
    case 4:
        answer = "delta";
         break;   
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(2);`

**Comment by Badh-Guy-Concept** [comment]
I also just had the same issue but i got it fixed
`function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
      case 1:
     return "alpha";
      break;
    case 2:
      return "beta";
      break;
    case 3:
     return "gamma";
      break;
    case 4:
      return "delta";
      break;
  }
  
  
  // Only change code above this line  
  return answer;  
}
`

**Comment by wsvincent** [comment]
@RomingArt I think the wording of this lesson is causing your confusion. You are not checking if "val" equals "alpha"; instead you are checking if "val" equals 1. The case operator handles the equality check for us automatically. If "val" equals the result of "case" then it asks us to assign the value "val" to "answer", which is done with the assignment operator ("=").

**Comment by MightyJoeW** [comment]
@MariamShqair OOOH!! Thank you! I forgot that 'answer' was a variable and could be set equal to the strings. I had console.log in there and was so confused.

**Comment by Badhan-abhishek** [comment]
why my UI of freecodecamp is basic type?
![ca](https://user-images.githubusercontent.com/25399508/42564965-c9b4efee-851f-11e8-9f7f-d14ad81d6da1.JPG)
