### ISSUE TITLE
How to remove all non-alphanumeric characters in string

### ISSUE THREAD

**Issue by LakshyaPandey** [FreeCodeCamp/FreeCodeCamp#5885]
I tried my level best to solve Bonfire: Check for Palindrome
The issue coming again and again is on using replace() only the first occurrence of the non-alphanumeric is replaced.
![untitled](https://cloud.githubusercontent.com/assets/16239522/12110683/e9b1a75e-b3b4-11e5-8401-ef79af91f6b1.jpg)

**Comment by raisedadead** [comment]
Please ask for guidance at [Help Chat](https://gitter.im/FreeCodeCamp/Help), github issues are for bugs only.

Thanks.
