### ISSUE TITLE
Bonfire is mysteriously filled with a working solution when I login today.

### ISSUE THREAD

**Issue by ziming** [FreeCodeCamp/FreeCodeCamp#5886]
Today I login and to my surprise Caesars Cipher bonfire is filled with a working solution. I'm pretty sure I did not write that code. Any idea what happened?

Challenge [Bonfire: Caesars Cipher](http://www.freecodecamp.com/challenges/bonfire-caesars-cipher#?solution=function%20rot13(encodedStr)%20%7B%0A%20%20var%20codeArr%20%3D%20encodedStr.split(%22%22)%3B%20%20%2F%2F%20String%20to%20Array%0A%20%20var%20decodedArr%20%3D%20%5B%5D%3B%20%2F%2F%20Your%20Result%20goes%20here%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20codeArr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%0A%20%20%20%20var%20num%20%3D%20encodedStr.charCodeAt(i)%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20if%20(num%20%3E%3D%2065%20%26%26%20num%20%3C%3D%2077)%20%7B%0A%20%20%20%20%20%20num%20%2B%3D%2013%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if%20(num%20%3E%3D%2078%20%26%26%20num%20%3C%3D%2090)%20%7B%0A%20%20%20%20%20%20num%20-%3D%2013%3B%0A%20%20%20%20%7D%0A%20%20%20%20decodedArr.push(String.fromCharCode(num))%3B%0A%20%20%7D%0A%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20%0A%20%20return%20decodedArr.join(%22%22)%3B%20%2F%2F%20Array%20to%20String%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function rot13(encodedStr) {
  var codeArr = encodedStr.split("");  // String to Array
  var decodedArr = []; // Your Result goes here
  // Only change code below this line
  
  for (var i = 0; i < codeArr.length; i++) {
    
    var num = encodedStr.charCodeAt(i);
        
    if (num >= 65 && num <= 77) {
      num += 13;
    }
    else if (num >= 78 && num <= 90) {
      num -= 13;
    }
    decodedArr.push(String.fromCharCode(num));
  }


  // Only change code above this line
  
  return decodedArr.join(""); // Array to String
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");


```

**Comment by ziming** [comment]
It turns out a few of my other bonfire codes are replaced with the codes of some other campers solutions that I previously viewed when I check out their profile. Not sure how many exercises are affected.

**Comment by ziming** [comment]
Tested and confirmed it. By just viewing someone else bonfire.etc solution, their code will automatically replace mine for that exercise.

**Comment by ltegman** [comment]
This is expected. The editor saves code after visiting a challenge regardless of how you got there and whose code it is. Thanks and happy coding!

**Comment by ziming** [comment]
I don't think it is expected, when I view someone profile my expectation is to see how others approach the same problem. Not that I want their code to replace my code.

But nevermind.

**Comment by DDaems** [comment]
@ltegman it might be worth looking into this though. And look if we can't change the default behavior to only save the changes when a person actually made a change to the code into the editor. Atm the editor loads in the passed solution trough a encoded string and automaticly updates the corresponding localstorage item related to the challenge, likely because it assumes that the editor is being used when the solution gets injected.

I was unable to find the root cause of this problem, but this as far as i could pinpoint it. When i was searching why Reset button didn't work as expected. I fixed it injecting the defaultcode into the addressbars solution query as a workaround. Which in turn would be injected in the code-editor and the code-editor inturn would update the localstorage item.

**Comment by ltegman** [comment]
@ziming @DDaems I just can't see any good way to implement this. Sure, your intention this time may have just been to click on it an look at it, but what if you want to mess around with it, iterate on it, or break it? How do I know you just want to do that temporarily and never see the work you did from it again?

I'm sure there are occassions people load up a code solution from someone else's profile and don't ever do anything in the editor. In that case, your solution would work @DDaems, but then if I want to make sure users who want to can take advantage of this by posting up the intricate behavior rules of code storage. Plus, I just don't think that's the majority of cases. I think most of the time people want to play around with the code, which brings us back to my first point.

**Comment by DDaems** [comment]
@ltegman If people actually want to play around with others peoples code. There is currently no way to make a distinction between the two. Without adding any additional tracking and poluting the localstorage with a temporary item for these cases.

**Comment by SaintPeter** [comment]
One possible solution is to use an "Incognito" window when you're viewing other people's code/links:
![image](https://cloud.githubusercontent.com/assets/553494/12162326/4c7cb5a8-b4b5-11e5-9b4f-53f5a9fd294e.png)
That won't write to "your" localStorage.

I have to agree with @ltegman, our primary concern will always be for the individual camper's ease of use.  In the bad old days we didn't store code at all which resulted in much wailing and gnashing of teeth.

**Comment by DDaems** [comment]
@SaintPeter i allways forget that mode exists :-)

**Comment by ziming** [comment]
How about when you view others code, It is in read only mode? then if I want to play with it I can copy the code and paste in my own code challenge myself?

**Comment by DDaems** [comment]
@ziming no i'm afread you need to read others code using incognito mode like @SaintPeter suggested. Else it will overwrite yours
