### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-padding-of-an-element has an issue 

### ISSUE THREAD

**Issue by BaxterChi** [FreeCodeCamp/freecodecamp#589]
The objectives right now are pretty confusing:

<ul>
<li>Your green-box class should give the bottom of elements 20px of padding.</li>
<li>Your green-box class should give the left of elements 40px of padding.</li>

This suggests, to me at least, that through Clockwise Notation it is possible to assign padding to just the Bottom and Just the Left. Total NewB here, but it seems to me that you have to assign it to the top/bottom and left/right. I can't find anyway other than padding-bottom, etc to change the top without changing the top.

**Comment by QuincyLarson** [comment]
Hi @BaxterChi Thank you for submitting this. I looked at the wording on this, and I think it's pretty clear, and if other people have similar issues with this, we can go back to the drawing board.

**Comment by BerkeleyTrue** [comment]
This is a duplicate of https://github.com/FreeCodeCamp/freecodecamp/issues/572
