### ISSUE TITLE
The challenge "waypont: Target the same element with multiple jQuery Selectors" seems to have multiple conflicts

### ISSUE THREAD

**Issue by re4ect** [FreeCodeCamp/FreeCodeCamp#5890]
Whenever the waypoint asks to "Only add one class with each of the three selectors." I am also told that my "#target1 element should have the classes animated‚ shake and btn-primary."

What I am trying to say is why is the waypoint telling me to only add one class with each of the three selectors, when the waypioint is also telling me to add more than one class to #target1?

![screenshot-www freecodecamp com 2016-01-05 06-13-50](https://cloud.githubusercontent.com/assets/14848245/12113945/43db41fe-b374-11e5-8579-8e8fad697a3d.png)

**Comment by re4ect** [comment]
I am also not able to finish the challenge because it will not accept one class or three classes with the #target1 selector.

Or maybe I screwed up some how and I don't know it...yet.

**Comment by raisedadead** [comment]
The correct solution would be:
```javascript
$(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });
```

Apart from that to clear the confusion that you have:
1.

**Comment by raisedadead** [comment]
The correct solution would be:
```javascript
$(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });
```

Apart from that to clear the confusion that you have:
1. `Only add one class with each of your three selectors.` - Refer the code that I have posted.
2. `Your #target1 element should have the classes animated‚ shake and btn-primary.` - This test case means that when jQuery code (the code above) is executed, then the net effect would be that the `<button>` element will have these three classes, as a result of your JavaScript (jQuery code). 

Hope this helps! Goodluck.

**Comment by re4ect** [comment]
When it come to the addClass I always forget to capitalize the word Class that is why it won't accept my answers. 

And thank you for clarifying that for me

**Comment by raisedadead** [comment]
Sure thing. Happy to help! :smile:

**Comment by GonzandRobles** [comment]
Everything clear now, thanks

**Comment by MajideB** [comment]
7378
Thanks

**Comment by mk485eg** [comment]
try to make one  "     "  not for each element

**Comment by Saraswati-rajkumar** [comment]
$("button").addClass("animated shake");
    $(".btn").addClass("animated shake");
    $("#target1").addClass("animated shake");
    $("#target1").addClass("animated shake btn-primary");

Only add one class with each of your three selectors.

This is the passing I don't know where I am wrong please help

**Comment by texas2010** [comment]
@Saraswati-rajkumar 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by williamlionel** [comment]
<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
    $("#target1").addClass("animated shake btn-primary");
  });
</script>

Just that. Good Luck

**Comment by AkhilAkku95** [comment]
@raisedadead tnx broii :)

**Comment by Croasdell** [comment]
this worked for me ..

<script> $(document).ready(function() { 
    $("button").addClass("animated"); 
    $(".btn").addClass("shake"); 
    $("#target1").addClass("btn-primary"); 
    $("#target1").addClass("animated shake btn-primary");
  }); 
</script>

**Comment by lokirajagopal** [comment]
nobody told me capitalise C in  Class thank u

**Comment by mayankpatel15** [comment]
<script>
  $(document).ready(function() {
$("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1 ").addClass("btn-primary");
  });
</script>

**Comment by DBaldwin107** [comment]
Note to me:

• don't use a <.> when you need a <-> AND
• don't add syntax that is not asked for in the challenge.
