### ISSUE TITLE
Incorrect explanation of the `+`

### ISSUE THREAD

**Issue by ryentzer** [FreeCodeCamp/FreeCodeCamp#5892]
Challenge [Waypoint: Find Numbers with Regular Expressions](http://www.freecodecamp.com/challenges/waypoint-find-numbers-with-regular-expressions#?solution=%2F%2F%20Setup%0Avar%20testString%20%3D%20%22There%20are%203%20cats%20but%204%20dogs.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20expression%20%3D%20%2Fd%2B%2Fg%3B%20%20%2F%2F%20Change%20this%20line%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%2F%2F%20This%20code%20counts%20the%20matches%20of%20expression%20in%20testString%0Avar%20digitCount%20%3D%20testString.match(expression).length%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The content is this:

>For numbers this is often written as /\d+/g, where the + following the digit selector allows this regular expression **to match one or more numbers**.

the `+` in this case is to match one or more digits, not one or more numbers. The `g` is a global match flag which will find all the numbers.

**Comment by SaintPeter** [comment]
I agree.  What alternative text do you propose?
