### ISSUE TITLE
Completed and passed challenge, cannot submit, just hangs

### ISSUE THREAD

**Issue by amberjo789** [FreeCodeCamp/FreeCodeCamp#5896]
Challenge [Bonfire: Caesars Cipher](http://www.freecodecamp.com/challenges/bonfire-caesars-cipher#?solution=function%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20var%20chr%3B%0A%0A%20%20for(var%20i%20%3D%200%3B%20i%3Cstr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(str.charCodeAt(i)%20%3E%3D78)%7B%0A%20%20%20%20%20%20chr%20%3D%20String.fromCharCode(str.charCodeAt(i)-13)%3B%0A%20%20%20%20%20%20result%20%3D%20result.substr(0%2Ci)%2Bchr%2Bresult.substr(i%2C%20chr.length)%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if(str.charCodeAt(i)%20%3C%2078%20%26%26%20str.charCodeAt(i)%20%3E%2064)%7B%0A%20%20%20%20%20%20chr%20%3D%20String.fromCharCode(str.charCodeAt(i)%2B13)%3B%0A%20%20%20%20%20%20result%20%3D%20result.substr(0%2Ci)%2Bchr%2Bresult.substr(i%2C%20chr.length)%3B%0A%20%20%20%20%7D%20%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20chr%20%3D%20String.fromCharCode(str.charCodeAt(i))%3B%0A%20%20%20%20%20%20result%20%3D%20result.substr(0%2Ci)%2Bchr%2Bresult.substr(i%2C%20chr.length)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function rot13(str) { // LBH QVQ VG!
 
  var result = "";
  var chr;

  for(var i = 0; i<str.length; i++){
    if(str.charCodeAt(i) >=78){
      chr = String.fromCharCode(str.charCodeAt(i)-13);
      result = result.substr(0,i)+chr+result.substr(i, chr.length);
    }
    else if(str.charCodeAt(i) < 78 && str.charCodeAt(i) > 64){
      chr = String.fromCharCode(str.charCodeAt(i)+13);
      result = result.substr(0,i)+chr+result.substr(i, chr.length);
    } 
    else{
      chr = String.fromCharCode(str.charCodeAt(i));
      result = result.substr(0,i)+chr+result.substr(i, chr.length);
    }
  }
  
  return result;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

**Comment by amberjo789** [comment]
Like the title explains, I have completed and passed the code challenge. When I try to "submit and go to the next challenge" the graphic just keeps spinning. I have tried "ctrl + enter" and tried switching from Firefox, to Chrome, and to Internet Explorer. Each time the screen just hangs when I try to submit and move on.

**Comment by amberjo789** [comment]
![image](https://cloud.githubusercontent.com/assets/5623979/12125529/4d311822-b3b1-11e5-9f06-a2f04309acdb.png)

**Comment by raisedadead** [comment]
@amberjo789 If this issue is still reproducible for you, can you please share a screenshot of your browser console when this happens:

You need to:
1. Reproduce this issue as you mentioned.
2. Hit F12, to launch the browser's dev tools.
3. Click on the Console tab
4. Share the screen shot.

Thanks.

**Comment by darthredskin** [comment]
![121232323123213](https://cloud.githubusercontent.com/assets/3140597/12344693/dc957dfe-bb05-11e5-8589-14b672d8bddf.jpg)

This same error happens to me as well, but for a different waypoint.

**Comment by raisedadead** [comment]
@darthredskin Thanks!
Can you please take a screenshot of your browser console too? The steps are in my comment above.

**Comment by matty22** [comment]
I've had this happen, but I just waited a few minutes and it resolved itself.

**Comment by prollycause** [comment]
currently happening to me on every challenge and i alt tab for a about 3 minutes for it to load.  there is nothing in the chrome dev tools console log.

**Comment by sludge256** [comment]
@prollycause 
The servers are experiencing high load currently so it's an unrelated issue.

**Comment by prollycause** [comment]
@sludge256 ah i was thinking that was the case! i guess more people are using fcc which is good.

**Comment by dennislixin** [comment]
The same error here.

![image](https://cloud.githubusercontent.com/assets/3445866/12771703/935673e6-ca6e-11e5-8081-9e303813cf94.png)

**Comment by sludge256** [comment]
@dennislixin I believe your issue is actually related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6633
Please try switching to FireFox for now.

**Comment by dennislixin** [comment]
@sludge256 It works with FireFox. Thanks for you help.

**Comment by bkowshik** [comment]
I have this issue too.

The behaviour is not consistent though. Sometimes the transition to the next exercise is smooth. But, sometimes the browser hangs.

@QuincyLarson Why is this marked as `help_wanted`? How can I help?

**Comment by bkowshik** [comment]
### An Idea
How about we **prefetch the next lesson** so that for the campers the next lesson loads instantaneously and the cycle continues?

**Comment by mtam2** [comment]
@bkowshik Tests are ran client-side on the browser so that speed is dependent on your computer/browser. The "Submit and go to my next challenge" requests the next page from the server and FCC servers experience fluctuating load.

**Comment by bugron** [comment]
Is this still an issue?

**Comment by prollycause** [comment]
Shouldn't be no

**Comment by bugron** [comment]
@prollycause OK, closing this issue. If anyone still experiences problems, please, comment here, thanks.
