### ISSUE TITLE
wrong output

### ISSUE THREAD

**Issue by jaiyow** [FreeCodeCamp/FreeCodeCamp#5897]
The output should be shown in the array form to let the coder if he has been able to divide the array into chunks or not.It is simply printing the whole original array back when the code is correct.

**Comment by sludge256** [comment]
It's a [known issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5097) with a fix being worked on https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5181.
