### ISSUE TITLE
Tweets on the about page

### ISSUE THREAD

**Issue by Maximization** [FreeCodeCamp/freecodecamp#59]
Is there a reason a live twitter feed hasn't been implemented yet on the about page? One reason I could think of is from a marketing perspective, wanting to have selective tweets.

However, they seem a bit outdated now and every time I see the page they're always the same. Perhaps it would be a good idea to insert a live twitter feed following @FreeCodeCamp ? If it's desirable I could take a look into it.

**Comment by QuincyLarson** [comment]
I've updated the about page to use a standard Twitter stream. You can check it out here: http://www.freecodecamp.com/learn-to-code
