### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-an-ordered-list has an issue 

### ISSUE THREAD

**Issue by shcolligan** [FreeCodeCamp/freecodecamp#590]
I copied and pasted in preparation for creating the OL list.
The "Correct -- You're Done!" thingy got triggered after I edited the first UL into a OL --- but before I edited the closing UL tag.
My "correct" code reads:
<p>Things cats hate:</p>
<ol>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>                <--- note closing UL not OL

**Comment by QuincyLarson** [comment]
This is because this is valid HTML. Actually detecting whether you typed the closing tag without significantly slowing down the app is quite challenging.
