### ISSUE TITLE
1 555)555-555 test case not working as expected

### ISSUE THREAD

**Issue by nscalf561** [FreeCodeCamp/FreeCodeCamp#5900]
As the title says, the test case for 1 555)555-555 isn't working as expected.  When plugging in 
```javascript
function telephoneCheck(str) {
 // Good luck!
    var regex = /^1?\s?(\()?\d{3}(\))?[\s-]?\d{3}[\s-]?\d{4}$/gm;
    return regex.test(str);
}
```

It's returning 1 555)555-555 as True, while the console will return false.

**Comment by SaintPeter** [comment]
Your regular expression is wrong.  You have the opening and closing parentheses as being individually optional, but in reality they must both be present.

Here is my solution:
```js
function telephoneCheck(str) {
  var telRe = /^1* *(\d{3}|\(\d{3}\))[- ]*\d{3}[- ]*\d{4}$/;
  
  return telRe.test(str);
}
```
Note that I accept either `(\d{3}|\(\d{3}\))`

In the future, I encourage you to seek assistance in the [HelpBonfires](https://gitter.im/FreeCodeCamp/HelpBonfires) room prior to filing an issue.

Thanks and Happy Coding!

**Comment by nscalf561** [comment]
The error was that when your expression correctly returned the answer to
the 1 555)555-555 test case, it said that test case failed. Once I passed
all test cases correctly it was marked correct.

On Tuesday 5 January 2016, Rex Schrader <notifications@github.com> wrote:

> Your regular expression is wrong. You have the opening and closing
> parentheses as being individually optional, but in reality they must both
> be present.
>
> Here is my solution:
>
> function telephoneCheck(str) {
>   var telRe = /^1* *(\d{3}|\(\d{3}\))[- ]*\d{3}[- ]*\d{4}$/;
>
>   return telRe.test(str);
> }
>
> Note that I accept either (\d{3}|\(\d{3}\))
>
> In the future, I encourage you to seek assistance in the HelpBonfires
> <https://gitter.im/FreeCodeCamp/HelpBonfires> room prior to filing an
> issue.
>
> Thanks and Happy Coding!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5900#issuecomment-169160382>
> .
>


-- 
*Nicholas Scalf*
Palm Beach Gardens Wolf PAC Organizer
*www.wolf-pac.com* <http://www.wolf-pac.com/?recruiter_id=7777>
561-283-9786
