### ISSUE TITLE
Challenge [Bonfire: Pig Latin] getting 'undefine' while all tests pass locally.

### ISSUE THREAD

**Issue by fangmobile** [FreeCodeCamp/FreeCodeCamp#5903]
Challenge [Bonfire: Pig Latin](http://www.freecodecamp.com/challenges/bonfire-pig-latin#?solution=function%20translate(str)%20%7B%0A%20%20%20%20var%20result%3B%0A%20%20%20%20switch%20(str.charAt(0))%7B%0A%20%20%20%20%20%20%20%20case%20%27a%27%3A%0A%20%20%20%20%20%20%20%20case%20%27i%27%3A%0A%20%20%20%20%20%20%20%20case%20%27o%27%3A%0A%20%20%20%20%20%20%20%20case%20%27u%27%3A%0A%20%20%20%20%20%20%20%20case%20%27e%27%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20result%20%3D%20str%20%2B%20%27way%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20default%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20done%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20switch%20(str.charAt(i))%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%27a%27%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%27i%27%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%27o%27%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%27u%27%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20case%20%27e%27%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2Fdo%20your%20thing%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20done%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20result%20%3D%20str.slice(i%2C%20str.length)%20%2B%20str.substr(0%2C%20i)%20%20%2B%20%27ay%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20default%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2Fdo%20nothing%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(done)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%2F%2Fout%20of%20loop%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20result%3B%0A%7D%0A%0Atranslate(%22california%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function translate(str) {
    var result;
    switch (str.charAt(0)){
        case 'a':
        case 'i':
        case 'o':
        case 'u':
        case 'e':
            result = str + 'way';
            break;
        default:
            for (var i = 1; i < str.length; i++){
                var done = false;
                switch (str.charAt(i)){
                    case 'a':
                    case 'i':
                    case 'o':
                    case 'u':
                    case 'e':
                        //do your thing
                        done = true;
                        result = str.slice(i, str.length) + str.substr(0, i)  + 'ay';
                        break;

                    default:
                        //do nothing
                        break;
                }
                if (done){
                    break;//out of loop
                }
            }
    }
    return result;
}

translate("california");

```

**Comment by fangmobile** [comment]
unit test all passed locally:
I added module exports locally for unit test consumption.
```
it ("Pig Latin", function(){
        var translate = require ("PigLatin");
        expect(translate("california")).toBe("aliforniacay");
        expect(translate("paragraphs")).toBe("aragraphspay");
        expect(translate("glove")).toBe("oveglay");
        expect(translate("algorithm")).toBe("algorithmway");
        expect(translate("eight")).toBe("eightway");

    });
```

**Comment by fangmobile** [comment]
as found by @dcnr 
adding a console.log statement above the for loop makes it pass.
Looks like a bug to me.

**Comment by ltegman** [comment]
loopProtect is completely mangling this code. Here's what it does:

Original code:
```javascript
default:
    for (var i = 1; i < str.length; i++){
        var done = false;
```

loopProtect Mangled:
```javascript
        defa;loopProtect.protect({ line: 12, reset: true }); ult:
            for (var i = 1; i < str.length; i++){;
if (loopProtect.protect({ line: 12 })) break;

                var done = false;
```

You can disable loopProtect with a `// noprotect` comment to get around this (although it sounds like you already found a way).

Hopefully someone will have a chance to dive into the code and figure out what is going on with this edge case.

**Comment by ltegman** [comment]
I've opened the following PR in the loop-protect repo to fix this: https://github.com/jsbin/loop-protect/pull/9. I'll leave this open until they merge.
