### ISSUE TITLE
answer will not go through even when correct. 

### ISSUE THREAD

**Issue by stephyli** [FreeCodeCamp/FreeCodeCamp#5906]
Challenge [Waypoint: Concatenating Strings with the Plus Equals Operator](http://www.freecodecamp.com/challenges/waypoint-concatenating-strings-with-the-plus-equals-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%22This%20is%20the%20first%20sentence.%22%3B%0A%0AmyStr%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr ="This is the first sentence.";

myStr+= "This is the second sentence.";

```

**Comment by OriBon** [comment]
You need a space somewhere to separate the sentences.
Either put a space in the string at the end of `
var myStr ="This is the first sentence.";`
Or a space at the beginning of the string in `myStr+= "This is the second sentence.";`.

**Comment by stephyli** [comment]
works. thanks!!!!

**Comment by ltegman** [comment]
Please double check with the [Help Chat](https://gitter.im/FreeCodeCamp/Help) that your issue is indeed a bug before opening a Github issue. Thanks and happy coding!
