### ISSUE TITLE
not sure what this module is asking. my answer does not work: var myStr= \\" "\t" "\t" "\r" "\n" ";

### ISSUE THREAD

**Issue by stephyli** [FreeCodeCamp/FreeCodeCamp#5907]
Challenge [Waypoint: Escape Sequences in Strings](http://www.freecodecamp.com/challenges/waypoint-escape-sequences-in-strings#?solution=var%20myStr%3D%20%5C%5C%22%20%22%5Ct%22%20%22%5Ct%22%20%22%5Cr%22%20%22%5Cn%22%20%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr= \\" "\t" "\t" "\r" "\n" ";



```

**Comment by sludge256** [comment]
I would encourage the use of [Help Chat](https://gitter.im/FreeCodeCamp/Help) in these situations as Github issues are meant for site related issues/bugs. Sometimes it can be hard to get noticed when the chat is moving quickly but you can always try mentioning someone's name directly to get their attention.

If you get rid of all the extra quotes and treat it as one single string, based on a quick glance, I believe your code should work.

**Comment by stephyli** [comment]
thank you!!! works!!!!!

**Comment by ltegman** [comment]
Thanks and happy coding!

**Comment by ashrafmscs** [comment]
thanks @sludge256
