### ISSUE TITLE
Moving on from "Waypoint: Add Font Awesome Icons to all our Buttons"

### ISSUE THREAD

**Issue by chloegott** [FreeCodeCamp/FreeCodeCamp#5909]
I wrote the code, which didn't seem as if it would give me any major issues, as the directions explained. However, when I ran the tests, the tests "Add an i element with the classes fa and fa-thumbs-up." as well as "Your fa-thumbs-up icon should be located within the Like button." say that they are not completed. "Nest your i element within your button element." and "Make sure your i element has a closing tag." are both completed.

My code is as follows:
```
<div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-info-thumbs-up"></i> Like</button>
    </div>
```

is there a potential problem with the site preventing me from moving forward with my challenges?

**Comment by raiden357** [comment]
I am having the same problem. the only one that passes is "Make sure your i element has a closing tag"
here is my code: <button i class="fa fa-thumbs-up btn btn-block btn-primary">Like</i></button>

**Comment by raiden357** [comment]
<button i class="fa fa-thumbs-up btn btn-block btn-primary">Like</i> </button>

**Comment by chloegott** [comment]
Hi,

I fixed mine with a ton of troubleshooting and discovered I had added in an unnecessary FA button, which prevented me from continuing (silly me!). What seems to be wrong in your code is the placement of the i class. If you look at mine in the original, you see I set up a separate i class within the button class. Changing that should fix it.

Hope I helped!

**Comment by raiden357** [comment]
thanks for the response, 2 people helped about 40 minutes ago,I had forgot to close out a element. #

**Comment by kawald** [comment]
Exactly where in the button class does the I class go? I have tried a few locations and got a thumbs up button icon but, there were 3 other thumbs as well, and I did not get a Go.

**Comment by wolff2016** [comment]
Great solution!

**Comment by 6eyezzz** [comment]
Im having trouble finding where exactly to put the i class :/ tried a few spots but cant find where to put it :c

**Comment by ecmed** [comment]
<button class= "btn btn-block btn-primary"> <i class="fa fa-thumbs-up"> </i>Like</button>

This is how the correct code needs to be.

**Comment by ecmed** [comment]
![screenshot 2017-05-28 20 54 49](https://cloud.githubusercontent.com/assets/29006197/26531378/2d29c72c-43e8-11e7-86a0-616d9efcb019.png)

That is how the correct code should look :)

**Comment by iamseanhooker** [comment]
`<div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumps-up"></i>Like</button>
    </div>`

I am wondering why this is declared the right code and still not letting me pass the lesson? Interesting.

**Comment by Pepperwheel** [comment]
@iamseanhooker You’ve got a typo in your code: ‘thumps’ instead of ‘thumbs’. Hope that helps!
