### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue 

### ISSUE THREAD

**Issue by shcolligan** [FreeCodeCamp/freecodecamp#591]
This one declared me to be correct/done as soon as I typed the word "placeholder" --- it did not wait for me to actually supply the placeholder text.

My "correct" html code:
`<input type='text' placeholder>`

**Comment by QuincyLarson** [comment]
We've fixed this and will have it live soon. Thank you for your patience, and for bringing this to our attention!

**Comment by shcolligan** [comment]
I hit similar issues (premature "success") on most of the lessons following, but didn't want to post them all, esp not to the public chat, not knowing if you had already gotten reports...

BTW, I love the little success dance of the "Go to next challenge" green box.
