### ISSUE TITLE
Bonfire: Sum All Odd Fibonacci Numbers (infinite loop)

### ISSUE THREAD

**Issue by Samedy** [FreeCodeCamp/FreeCodeCamp#5911]
Test run to 4000000 value can make browser freeze.

**Comment by BerkeleyTrue** [comment]
@Samedy Please provide you code

**Comment by Samedy** [comment]
for(i=2; i<=num-1; i++)
  {
      // Next fibonacci number = previous + one before previous
      // Translated to JavaScript:
      fib[i] = fib[i-2] + fib[i-1];
  }

above code could lead to infinite loop.

**Comment by ltegman** [comment]
@Samedy The full code, not just a piece of it.

**Comment by Samedy** [comment]
function sumFibs(num) {
  var i;
  var fib = [];

  fib[0] = 0;
  fib[1] = 1;
  for(i=2; i<=num; i++)
  {
      // Next fibonacci number = previous + one before previous
      // Translated to JavaScript:
      fib[i] = fib[i-2] + fib[i-1];
  }
 return fib;
}

above code i just want to test i have all the number that i need to sum.

**Comment by ltegman** [comment]
@Samedy This is not a problem with the test, this is a problem with your code being too slow. You're creating a 4 million item array. That's a recipe for disaster.

**Comment by Samedy** [comment]
I just want the author to lower the test run value so this kind of problem could not happen.

**Comment by ltegman** [comment]
@Samedy The point of the test is to cause you to rethink your solution if it is too slow to handle a number that large. There are a relatively simple solutions that can solve this problem for 4000000 in under a second.
