### ISSUE TITLE
After adding social networking to portfolio it should redirect to user's page

### ISSUE THREAD

**Issue by trishnaguha** [FreeCodeCamp/FreeCodeCamp#5912]
After adding other profiles to freecodecamp portfolio it should redirect back to [user's page](http://www.freecodecamp.com/trishnaguha).
But it is redirecting to [waypoint-learn-what-to-do-if-you-get-stuck](http://www.freecodecamp.com/challenges/waypoint-learn-what-to-do-if-you-get-stuck)

**Comment by pmbenjamin** [comment]
I am not able to replicate this.
From my experience, it seems to be re-directing back to the last page I was on before going into my Account to add/update profiles.

**Comment by raisedadead** [comment]
Closing this as stale. Please feel free to comment to re-open.
