### ISSUE TITLE
Challenge Checkpoint: Counting Cards Description

### ISSUE THREAD

**Issue by dhanvi** [FreeCodeCamp/FreeCodeCamp#5916]
Challenge [Checkpoint: Counting Cards](http://www.freecodecamp.com/challenges/checkpoint-counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20'J'%3A%0A%20%20%20%20case%20'Q'%3A%0A%20%20%20%20case%20'K'%3A%0A%20%20%20%20case%20'A'%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%20%20%0A%20%20%0A%20%20if(count%3E0)%7B%0A%20%20%20%20return%20count%2B%22%20Bet%22%3B%0A%20%20%7D%0A%20%20if(count%3C%3D0)%7B%0A%20%20%20%20return%20count%2B%22%20Hold%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      break;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count--;
      break;
    default:
      break;
  }  
  
  if(count>0){
    return count+" Bet";
  }
  return count+" Hold";
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

The problem is with description of the checkpoint they have asked us to return the count and the string 

There is no clear explanation saying that we need to return a variable by concatenating the count with `"Hold"` or `"Bet"`. 

You took the general assumption as the return var as string 

one could also say to return a array of variable like 

```javascript
  return [count,"Hold"];
  
  return [count,"Bet"];
```

So here the issue to fix is the description of the challenge

**Comment by SaintPeter** [comment]
It does say:
![image](https://cloud.githubusercontent.com/assets/553494/12162033/cfa082e2-b4b1-11e5-83ad-b6055cc5399f.png)

Additionally, the tests say:
![image](https://cloud.githubusercontent.com/assets/553494/12162042/efc2855c-b4b1-11e5-9548-8ad4ce3d2ed5.png)

Note that there are quotes around the expected output.  

How would you propose that the directions be updated?

**Comment by dhanvi** [comment]
I didn't observe the expected expected output section that clearly 

may be clarifying about how to return both the things  (for example saying that the function should return a string var or something similar)

**Comment by SaintPeter** [comment]
Here are the current instructions:
>  The function will then return the current count and the string "Bet" if the count is positive, or "Hold" if the count is zero or negative.

I am open to suggestions as to how to make this clearer.

**Comment by erictleung** [comment]
Here's an alternate description:

> The function will then return **a string with** the current count and the string "Bet" if the count is positive, or "Hold" if the count is zero or negative. **The current count and the player's decision (`"Bet"` or `"Hold"`) should be separated by a single space.**

To really drive home the format of the output, maybe also put the "Example Output" in quotations as well, like so:

![image](https://cloud.githubusercontent.com/assets/2754821/12220178/39bfb0c0-b71a-11e5-8cf1-d157f49f8268.png)

**Comment by SaintPeter** [comment]
I would be amenable to this change as well.
