### ISSUE TITLE
unsure about this

### ISSUE THREAD

**Issue by WCat13** [FreeCodeCamp/FreeCodeCamp#5917]
Challenge [Waypoint: Accessing Objects Properties with Variables](http://www.freecodecamp.com/challenges/waypoint-accessing-objects-properties-with-variables#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3D%2016%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%20%5BplayerNumber%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0Aconsole.log(player)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;       // Change this Line
var player = testObj[playerNumber];   // Change this Line
console.log(player);
```
I know I have issues ;).  I also think this one does as well.

I am trying to understand this better and was getting 'undefined' in console.  I would like to see the result of what I did.  I feel  my answer is incorrect even though it's passing.  I threw in the console.log(player) to help better understand by returning 'Montana' and even more confused now.

Thanks for any insight in Advance.

**Comment by dhanvi** [comment]
First of all this is not the place to ask help :-1: you should be asking it here https://gitter.im/FreeCodeCamp/Help so next time don't create issues for help 

your target here to access object properties with variables which can be done by using the bracket notation. So `myObject[myVariable]` can access what ever property in the myVariable but you can't do so using `myObject.myVariable`  

Guys this is not a issue close this issue :-1:

**Comment by dhanvi** [comment]
@WCat13 hope my answer had helped you :smile:

**Comment by ManOnACodingMission** [comment]
Should the console display **player ="Montana"** ?  It is showing **undefined** even though the code is correct (and passed).
