### ISSUE TITLE
Bonfire: Mutations - wrong test case

### ISSUE THREAD

**Issue by sardware** [FreeCodeCamp/FreeCodeCamp#5919]
Challenge [Bonfire: Mutations](http://www.freecodecamp.com/challenges/bonfire-mutations#?solution=function%20sortString(str)%7B%0A%20%20return%20str.toLowerCase().split('').sort().join('')%3B%0A%7D%0A%0Afunction%20count(str%2Cchar)%7B%0A%20%20var%20c%20%3D%200%3B%0A%20%20var%20pos%20%3D%20str.indexOf(char)%3B%0A%20%20while%20(pos%20!%3D%3D%20-1)%7B%0A%20%20%20%20c%2B%2B%3B%0A%20%20%20%20pos%20%3D%20str.indexOf(char%2Cpos%2B1)%3B%0A%20%20%7D%0A%20%20return%20c%3B%0A%7D%0A%0Afunction%20mutation(arr)%20%7B%0A%20%20var%20lastChar%20%3D%20''%3B%0A%20%20var%20s1%20%3D%20sortString(arr%5B0%5D)%3B%0A%20%20var%20s2%20%3D%20sortString(arr%5B1%5D)%3B%0A%20%20var%20l2%20%3D%20s2.length%3B%0A%20%20var%20res%20%3D%20true%3B%0A%20%20for%20(var%20i%3D0%3B%20i%20%3C%20l2%3B%20i%2B%2B)%7B%0A%20%20%20%20if%20(s2%5Bi%5D%20%3D%3D%3D%20lastChar)%20continue%3B%0A%20%20%20%20lastChar%20%3D%20s2%5Bi%5D%3B%0A%20%20%20%20if%20(count(s1%2ClastChar)%20%3C%20count(s2%2ClastChar))%7B%0A%20%20%20%20%20%20res%20%3D%20false%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20res%3B%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sortString(str){
  return str.toLowerCase().split('').sort().join('');
}

function countSorted(str,char){
  var c = 0;
  var pos = str.indexOf(char);
  while (str[pos++] === char) c++;
  return c;
}

function mutation(arr) {
  var lastChar = '';
  var s1 = sortString(arr[0]);
  var s2 = sortString(arr[1]);
  var l2 = s2.length;
  var res = true;
  for (var i=0; i < l2; i++){
    if (s2[i] === lastChar) continue;
    lastChar = s2[i];
    if (countSorted(s1,lastChar) < countSorted(s2,lastChar)){
      res = false;
      break;
    }
  }
  return res;
}

mutation(["Mary", "Aarmy"])

```
The testcase is mutation(["Mary", "Aarmy"]), the system says it should return true because it doesn't care about only one 'a' in the first string, but i think it should return false due to the problem description.

**Comment by SaintPeter** [comment]
> Return true if the string in the first element of the array contains **all of the letters of the string** in the second element of the array.

It says "all of the letters of the string", it doesn't say anything about quantity, just presence.  This is reinforced by all of the test cases which support that notion.  This is not an error, this is the definition.

You may want to try a solution that uses `indexOf` to search one string for the presence of another.  Your current solution does not conform well to the problem as described.

Happy Coding!
