### ISSUE TITLE
Checkpoint: Record Collection

### ISSUE THREAD

**Issue by MariamShqair** [FreeCodeCamp/FreeCodeCamp#5920]
Challenge [Checkpoint: Record Collection](http://www.freecodecamp.com/challenges/checkpoint-record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20update(id%2C%20prop%2C%20value)%20%7B%0Aif(value%20!%3D%3D%20%22%20%22)%7B%0A%20%20if(prop%20%3D%3D%20%22album%22%20%7C%7C%20prop%20%3D%3D%20%22artist%22%20)%0A%20%20collection.id%5Bprop%5D%3Dvalue%3B%0A%20%20else%20if(prop%20%3D%3D%20%22tracks%22)%7B%20%0A%20%20collection.id.prop.push(value)%3B%0A%20%20%7D%7D%0A%20else%20delete%20collection.id.prop%3B%0A%0A%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0Aupdate(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
if(value !== " "){
  if(prop == "album" || prop == "artist" )
  collection.id[prop]=value;
  else if(prop == "tracks"){ 
  collection.id.prop.push(value);
  }}
 else delete collection.id.prop;


  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");


```

**Comment by ltegman** [comment]
Issue does not describe a problem. Thanks and happy coding!

**Comment by santosh7227** [comment]
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
 if(value !== "" && prop !== "tracks") {
    collection.id[prop] = value;
  } else if (prop === "tracks" && value !== "") {
    collection.id[prop].push(value);
  } else if(value === "") {
    delete collection[prop];
  }

 
  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");




The Error:
TypeError: Cannot set property 'artist' of undefined

I think even if the 'artist' is undefined it should add a property with name 'artist' and value as passed above.

**Comment by SaintPeter** [comment]
The problem is that `id` is not a property of `collection`.  `id` is a variable that contains the name of a property of `collection`.  You must use bracket notation to access it.  IE  `collection[id]`

**Comment by MariamShqair** [comment]
@santosh7227 
@SaintPeter 
thank you very much

my code after solving errors:

function update(id, prop, value) {
if(value !== ""){
  if(prop == "album" || prop == "artist" )
  collection[id][prop]=value;
  else if(prop == "tracks"){ 
  collection[id][prop].push(value);
  }}
 else delete collection[id][prop];


  return collection;
}

**Comment by syedirfan7** [comment]
```js
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {

  var objId=id; 
 var objProp=prop;
  if (value!==""&& prop!=="tracks")

{
    collection[objId][objProp]=value;
  }
  if (value!==""&&prop==="tracks")
{
  //var objprop=prop;
  collection[objId][objProp].push(value);
}
  
  if (value===""){
    
    delete collection[objId][objProp];
  }
  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");
```
I wanted to know whether my approach is correct  for the above algorithm

also 
after many hit and trail i got the combination ```collection[objId][objProp]``` (successful approach)

why did other approach did not lead me to the answer like 
```
collection.objId.objProp
collection[objId].objProp
```

and other combinations ?

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code questions.  Please ask for help in [HelpJavascript Chat](https://gitter.im/FreeCodeCamp/HelpJavascript) or [CodeReview Chat](https://gitter.im/FreeCodeCamp/CodeReview).

Thanks and Happy Coding!

**Comment by dalcoo** [comment]
function updateRecords(id, prop, value) {
  if(value===""){
    delete collection [id][prop];
  }
  else if(prop!=="tracks"){
   collection[id][prop]=value;
  }
else{
  collection [id][prop]= [];
 collection [id][prop].push(value);
}
    return collection;

}
// Alter values below to test your code
updateRecords(5439, "tracks", "Take a chance");

**Comment by aarontaylor** [comment]
I updated this to work with later versions of this problem:

This would go in the function.
```
  if (value === '') {
    delete collection[id][prop];
  } else if (prop !== 'tracks') {
    collection[id][prop] = value;
  } else {
    if (!collection[id].hasOwnProperty(prop)) {
      collection [id][prop]= [];
      collection[id][prop].push(value);
    } else {
      collection[id][prop].push(value);
    }
  }

  return collection;
```

**Comment by PabloVent** [comment]
Thanks Aaron, very nice solution.  I've been very confused by the wording of that particular challenge. Particularly this bit: "If prop does not contain the key "tracks", then update or set the value for that incomplete prop."
I was wondering, if the property does not exist, how can you give a value to it?  I think I need to understand what "value" means in this context. I understand it means give the missing prop a name/value which is tracks which is encapsulated in:

else if (prop !== 'tracks') {
    collection[id][prop] = value;

**Comment by Sipionix** [comment]
aarontaylor, you can make it even simpler :+1: 
```
  if (value === undefined) {
    delete collection[id][prop];
  } 
  else if (prop !== 'tracks') {
    collection[id][prop] = value;
  } 
  else {
    if (!collection[id].hasOwnProperty(prop)) 
        collection [id][prop]= [];
    collection[id][prop].push(value);
  }

  return collection;
```

**Comment by jyifan1** [comment]
// Setup
var recordCollection = {
  2548: {
    albumTitle: 'Slippery When Wet',
    artist: 'Bon Jovi',
    tracks: ['Let It Rock', 'You Give Love a Bad Name']
  },
  2468: {
    albumTitle: '1999',
    artist: 'Prince',
    tracks: ['1999', 'Little Red Corvette']
  },
  1245: {
    artist: 'Robert Palmer',
    tracks: []
  },
  5439: {
    albumTitle: 'ABBA Gold'
  }
};

// Only change code below this line
function updateRecords(records, id, prop, value) {
  
  if(prop !== "tracks" && value !== '') {
    records[id][prop] = value;
  }
  else if(prop === "tracks" && !records[id].hasOwnProperty("tracks")) {
    records[id][prop] = [];
    records[id][prop].push(value);
  }
  else if(prop === "tracks" && value !== '') {
       records[id][prop].push(value);
  }
  else if(value === '') {
    delete records[id][prop];
  }
  return records;
  
}


updateRecords(recordCollection, 5439, 'artist', 'ABBA');
