### ISSUE TITLE
Appending Variables to strings

### ISSUE THREAD

**Issue by alice3217** [FreeCodeCamp/FreeCodeCamp#5922]
Challenge [Waypoint: Appending Variables to Strings](http://www.freecodecamp.com/challenges/waypoint-appending-variables-to-strings#?solution=%2F%2F%20Example%0Avar%20anAdjective%20%3D%20%22awesome!%22%3B%0Avar%20ourStr%20%3D%20%22Free%20Code%20Camp%20is%20%22%3B%0AourStr%20%2B%3D%20anAdjective%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20someAdjective%3D%20%22alot%20of%20fun%22%3B%0Avar%20myStr%20%3D%20%22Learning%20to%20code%20is%20%22%3B%0AmyStr%20%2B%3D%20someAdjective%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// Only change code below this line

var someAdjective= "alot of fun";
var myStr = "Learning to code is ";
myStr += someAdjective

```

**Comment by ltegman** [comment]
Bug does not describe a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need help and file a bug with details and repro steps if they confirm what you are seeing is a site issue. Thanks and happy coding!

**Comment by mohannadsawalhi** [comment]
; end

**Comment by ieube** [comment]
Getting a error keeps telling me to Append someAdjective to myStr using the += operator. I dont see a error with the code. Does anyone see something I dont.

// Example
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// Only change code below this line

var someAdjective;
var myStr = "Learning to code is ";
someAdjective += myStr;

**Comment by Preeetrockz** [comment]
we have to write like this -
// Example
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// Only change code below this line

var someAdjective = "awesome!!";
var myStr = "Learning to code is ";
myStr += someAdjective;

**Comment by Stanleynd** [comment]
If you can remember how you declare myName in the previous lesson and you are ask to out concatenate it with it some strings. e.g:
1.var myName = "John.";
2.var myStr = " Loves guns."; //some strings
3. myName += myStr; //concatenationation
4. John loves guns .//Output

On the next lesson you're expected to do the same but this time is (Appending Variables to Strings) see code below.
1. var someAdjective = "i hate.";
2.var myStr = "school";
3.myStr += someAdjective;


Set someAdjective and append it to myStr using the += operator.
