### ISSUE TITLE
Waypoint: Label Bootstrap Buttons - Little change in Instructions

### ISSUE THREAD

**Issue by gauravmak** [FreeCodeCamp/FreeCodeCamp#5923]
http://www.freecodecamp.com/challenges/waypoint-label-bootstrap-buttons

Instructions on this task should inform the user to prefix hash to id before setting the text for the buttons I think.

**Comment by OriBon** [comment]
This waypoint already has six test requirements which indicate that you'll need a hash tag in your text.
```
Give your button element with the id target1 the text #target1.
Give your button element with the id target2 the text #target2.
Give your button element with the id target3 the text #target3.
Give your button element with the id target4 the text #target4.
Give your button element with the id target5 the text #target5.
Give your button element with the id target6 the text #target6.
```

**Comment by gauravmak** [comment]
Yes, that helped me to complete the test. But like other waypoints, one should be able to pass the test just by reading the instructions I thought.

**Comment by SaintPeter** [comment]
Please propose alternate instructions and we'll see what we can do.

**Comment by gauravmak** [comment]
Option 1) Add one more line : 
-> "Note: Prefix id with hash(#) while labeling the buttons."

Option 2) Change last line : 
-> "Give each of your button elements text that corresponds to their #id."

**Comment by denmch** [comment]
It is a little unclear. I think a better solution would be to ask campers to give each button "text that corresponds to it's id selector." This does less hand-holding and expects the student to synthesize knowledge (i.e., make the connection that `#target1` is the CSS selector that grabs the `id="target1"` attribute.

**Comment by gauravmak** [comment]
I agree.
Well, its not a very big issue. Actually, when I tried after reading instructions, my test failed and after checking the requirements below, I quickly added hash to each button and asked in gitter chat if instructions can be better. Was advised to open issue. that's it :)

**Comment by carlos1ready** [comment]
#crosthwaite50@icloud.com

**Comment by SaintPeter** [comment]
> Give each of your button elements text that corresponds to it's id's selector.

I like this.  You're right, @denmch, it gives a hint but still requires the camper to make the connection.

**Comment by mithun2017** [comment]
<button class="btn btn-default target" id="target1" text="#target1"></button>

help me

**Comment by texas2010** [comment]
@mithun2017 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
