### ISSUE TITLE
Waypoint: Local Scope and Functions

### ISSUE THREAD

**Issue by AliciadW** [FreeCodeCamp/FreeCodeCamp#5924]
Hi guys

I seem to be having an issue with this Waypoint that I haven't seen in any of the other posts.

The test asks for a global myVar variable as well as a local myVar variable. 

Here is my code:

var myVar = "strict";

function myFunction() {
  var myVar = "strict";
  console.log(myVar);
}
myFunction();

It acknowledges the local myVar variable, but keeps on telling me that I have no global myVar variable. I have tried renaming, removing the local variable, refreshing my browser and clearing the cache, but to no avail.

Is this a bug or am I missing something? I asked on the help room and it seems that my code is correct...

**Comment by yjcxy12** [comment]
The initial code does not have the line 
```javascript
var myVar = "strict";
```

The purpose of the test is that you run the test first, and console outputs myVar is not defined. Comments under asks user to remove the line 
```javascript
console.log(myVar);
```
to pass the test.

Error message is definitely misleading as it should be 'globol myVar should not be defined'

**Comment by AliciadW** [comment]
Hi yjcxy12

I have removed the line

console.log(myVar);

where they ask for it to be removed. If I remove the line in the function it says

console.log never called

**Comment by AliciadW** [comment]
Hi yjcxy12

I did another waypoint just now, went back and clicked run test again and it worked... :-)

**Comment by ltegman** [comment]
Sounds like this is resolved. :smile: Happy coding!

**Comment by marauderlabs** [comment]
@ltegman I'm still stuck with this issue.. Tried all solutions. Can somebody help me here...

**Comment by hram908** [comment]
After correcting the code I was told to refresh the page by @HassHz

**Comment by DragutinDjokovic** [comment]
Just refresh it after the write code is written.

**Comment by faizsehal** [comment]
refresh the page 'globol myVar should not be defined' should green and run the test pass :)

**Comment by maxfettes** [comment]
After countless code rearranging, it really only needed the page to be refreshed. :)
