### ISSUE TITLE
Waypoint: Introducing JavaScript Object Notation JSON- Needs Comma

### ISSUE THREAD

**Issue by brettfelts** [FreeCodeCamp/FreeCodeCamp#5925]
Challenge [Waypoint: Introducing JavaScript Object Notation JSON](http://www.freecodecamp.com/challenges/waypoint-introducing-javascript-object-notation-json#?solution=var%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201993%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%2C%0A%20%20%2F%2F%20Add%20record%20here%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Daft%20Punk%22%2C%0A%20%20%20%20%22title%22%3A%20%22Homework%22%2C%0A%20%20%20%20%22release_year%22%3A%201997%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CD%22%2C%20%0A%20%20%20%20%20%20%22Cassette%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/47.0.2526.73 Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1993,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
 
];


```
The curly bracket ending the Billy Joel object needs a comma, otherwise the next artist object wont be processed by the browser.

**Comment by ltegman** [comment]
Closing as a duplicate of #5837

**Comment by brettfelts** [comment]
Thanks!

**Comment by leahhills** [comment]
Hey guys. I must have looked over the note part of the instructions for this challenge, because afterwards I noticed it did mention the comma thing. Hahah I wish it was in big bold letters! I too spent too much time figuring out that all that I needed was a comma.
![introducing json object](https://cloud.githubusercontent.com/assets/26134976/25420050/674b4208-2a13-11e7-8c90-d27896f35a6e.JPG)
