### ISSUE TITLE
Remove quotations to make it easier to read

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#5927]
Challenge [Bonfire: Convert HTML Entities](http://www.freecodecamp.com/challenges/bonfire-convert-html-entities#?solution=function%20convert(str)%20%7B%0A%20%20%2F%2F%20%26colon%3B%26rpar%3B%0A%20%20return%20str%3B%0A%7D%0A%0Aconvert(%22Dolce%20%26%20Gabbana%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(str) {
  // &colon;&rpar;
  return str;
}

convert("Dolce & Gabbana");

```

It gets a little hard to read the double quotation and apostrophe marks with all those quotation marks around them. Maybe better to put them and the other symbols in `<code>` tags for increased legibility.

Currently:
![image](https://cloud.githubusercontent.com/assets/2754821/12154772/478d4588-b476-11e5-8ea2-14453184210b.png)

Update:
![image](https://cloud.githubusercontent.com/assets/2754821/12154703/ec1b236e-b475-11e5-80f9-4ae54695bbb3.png)

**Comment by SaintPeter** [comment]
I agree.  File a PR, I'll accept.
