### ISSUE TITLE
Incorrect text

### ISSUE THREAD

**Issue by lalov1** [FreeCodeCamp/FreeCodeCamp#5929]
It says: 
"// Only change code above this line"
I had to change the code below it to get it to work.

**Comment by bencassidy** [comment]
lalov1, which exercise was this?

**Comment by lalov1** [comment]
Waypoint: Selecting from many options with Switch Statements

**Comment by ltegman** [comment]
There is no need to change anything below that line. Try a different approach if yours made you go outside the rules of the way point. 

Thanks and happy coding!
