### ISSUE TITLE
Bonfire: Return Largest Numbers in Arrays

### ISSUE THREAD

**Issue by thorgall** [FreeCodeCamp/FreeCodeCamp#5930]
I wrote a correct solution which did all that was required and I think better than it was asked.
This works. However, it does not let me pass.

var myArr = [];
function largestOfFour(arr) {
  // You can do this!
  for (var i = 0; i < arr.length; i++) {
 myArr.push(Math.max.apply(null, arr[i]));
  }
  return myArr;
}

**Comment by bencassidy** [comment]
thorgall, which exercise was this?

**Comment by sludge256** [comment]
It's because `myArr` is a global variable and doesn't get cleared upon subsequent function calls.

**Comment by SaintPeter** [comment]
@sludge256 is correct.

Thanks and Happy Coding!
