### ISSUE TITLE
Suggestion for JavaScript if/else waypoints and checkpoints

### ISSUE THREAD

**Issue by quatridunull** [FreeCodeCamp/FreeCodeCamp#5936]
All the new exercises are great, and help clarify a lot of concepts, but I think there is one thing missing from the way if/else statements are taught. One of the challenges that people face when understanding control statements is how to properly order each case.

For instance, if we want to output "less than one" when the input is less than one, and "less than two" when the input is less than two but greater than one, and "greater than or equal to two" otherwise, this is correct:
<pre><code>
function foo(x) {
  if ( x < 1 ) {
    return "less than one";
  }
  else if ( x < 2 ) {
    return "less than two";
  }
  else {
    return "greater than or equal to two";
  }
}
</code></pre>

While this is wrong because the function will return "less than two" when what we really want is "less than one":
<pre><code>
function bar(x) {
  if ( x < 2 ) {
    return "less than two";
  }
  else if ( x < 1 ) {
    return "less than one";
  }
  else {
    return "greater than or equal to two";
  }
}
</code></pre>

Currently, FCC's JavaScript section does not teach this while teaching control statements because it always presents the statements in the correct order. That is, FCC's directions would say:
>Output "less than one" when the input is less than one, and "less than two" when the input is less than two but greater than one, and "greater than or equal to two" otherwise.

just as I have said earlier in this issue, which is in the same order that the code should be written. 
However, if instead the order of directions were swapped like so:

>Output "less than two" when the input is less than two but greater than one, "less than one" when the input is less than one, and "greater than or equal to two" otherwise. Note that the order of each conditional statement can affect your code's output!

then this would give campers an opportunity to learn for themselves how order matters, and which order they need to put the comparisons.

So I think if there was a waypoint similar to the example I just gave, and another one using the less than comparator, and the Golf Code checkpoint was modified to switch around the ordering, then the lessons on if/else statements could teach this important concept.

**Comment by SaintPeter** [comment]
I agree, this is a good idea.  This could possibly be another waypoint and/or possibly modify some of the other points to reinforce this.

Maybe "Understanding Logical Order in If Else Statements" and just use your example above, or similar.

**Comment by gitasong** [comment]
I second this suggestion. :)
