### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by gitasong** [FreeCodeCamp/FreeCodeCamp#5938]
Challenge [Waypoint: Use Conditional Logic with If Statements](http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-if-statements#?solution=%2F%2F%20Example%0Afunction%20ourFunction(testMe)%20%7B%0A%20%20if%20(testMe%20%3E%2010)%20%7B%20%0A%20%20%20%20return%20%22Yes%22%3B%0A%20%20%7D%0A%20%20return%20%22No%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Afunction%20myFunction(testMe)%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20if%20(testMe%20%3E%205)%20%7B%0A%20%20%20%20return%20%22Yes%22%3B%0A%20%20%7D%0A%20%20return%20%22No%22%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyFunction(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(testMe) {
  if (testMe > 10) { 
    return "Yes";
  }
  return "No";
}

// Setup
function myFunction(testMe) {

  // Only change code below this line.
  if (testMe > 5) {
    return "Yes";
  }
  return "No";
  
  
  // Only change code above this line.

}

// Change this value to test
myFunction(10);

```
The instructions for this Waypoint are somewhat unclear. They state `Create an if statement inside the function to return "Yes" if testMe is greater than 5. Return "No" if it is less than or equal to 5`; however, the last sentence raises the question as to whether an *else* statement is required for the additional condition. Since *else* statements haven't been taught yet, that would seem to argue for a "no," but the wording suggests an *else* statement is expected. 

If an *else* statement is not necessary to handle the second condition, the final sentence should be changed to `Return "No" otherwise.` I would also like to see a discussion somewhere along the line of the utility and logic of a final *else* statement vs. no final *else* statement, as this shows up as a key logical step in the last few beginning Bonfires.

**Comment by SaintPeter** [comment]
When I was re-writing the Basic Javascript Curriculum, I explicitly and deliberately decoupled if and else statements.  When hanging out in the help rooms I saw that people would slavishly include an else for every single if they wrote and I wanted to break that habit before it started.  That's why these waypoints are presented in this order.

You'll note that there is no mention of `else` anywhere in the curriculum prior to this introduction (I don't think anyway) so a truly new user wouldn't know to even try to use `else`.

I also wanted them to think about what being greater than vs less than equal to meant.

I don't necessarily object to the idea of `return "no" otherwise`, but I don't think it's critical either.

**Comment by gitasong** [comment]
I hear you. Still, I would argue that the wording calls for two explicit conditions, not one explicit and one implicit. So if you'd like to avoid the slavish use of *else*, even in the minds of those who know about it, I would argue for the wording change. :)

**Comment by SaintPeter** [comment]
I'm open for a PR if you're up to it.  :wink:

**Comment by gitasong** [comment]
Don't know what that is or how to do it. :/

**Comment by SaintPeter** [comment]
A PR is a Pull Request:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Create-A-Pull-Request-for-Free-Code-Camp

Tell you what -
If you propose the whole text, or the part that you'd like to change, I can see about actually making the change.

**Comment by gitasong** [comment]
Sure! I would simply go with

`Create an if statement inside the function to return "Yes" if testMe is greater than 5 and return "No" otherwise.`

**Comment by gitasong** [comment]
And thanks much! Git is not something I want to fork around with before I'm ready, if you get my drift. ;)

**Comment by gitasong** [comment]
Thanks, @SaintPeter , @raisedadead !
