### ISSUE TITLE
toker

### ISSUE THREAD

**Issue by tOker67** [FreeCodeCamp/FreeCodeCamp#5939]
Challenge [Waypoint: Add a Negative Margin to an Element](http://www.freecodecamp.com/challenges/waypoint-add-a-negative-margin-to-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.4; Z970 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding:10px;
  }
  
  .red-box {
    background-color:red;
    padding: 20px;
    margin: -15px;
  }

  .green-box {
    background-color: green;
    padding: 20px;
    margin: 20px;
  }
</style>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by ltegman** [comment]
Bug does not describe a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm what you're seeing is actually a bug and then file a bug with details and repro steps.
