### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by smeloa** [FreeCodeCamp/freecodecamp#594]
One of the instructions reads: 

Wrap your all of your checkboxes inside one div with the class "row".

This challenges is not about the checkboxes, it should instead be:

Wrap your text-area and button inside one div with the class "row".

**Comment by terakilobyte** [comment]
Thanks for the report. It's been fixed in commits!
