### ISSUE TITLE
Bug in Waypoint: Escaping Literal Quotes in Strings.

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#5940]
Link: http://www.freecodecamp.com/challenges/waypoint-escaping-literal-quotes-in-strings

While asking for the user to assign the example string to the variable, this waypoint took the following code as a valid answer.

``` js
var myStr; "I am a \"double quoted\" string inside \"double quotes\"" //change this line
```

**Comment by PrashantBisht** [comment]
You have missed one full stop at the end of sentence apply it and you will pass test cases.
myStr="I am a \"double quoted\" string inside \"double quotes\".";

**Comment by BEBEDYDY** [comment]
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line
you should be careful the spacing between strings.
and var myStr = 
not var myStr ;
