### ISSUE TITLE
'code above' comment

### ISSUE THREAD

**Issue by DrCo** [FreeCodeCamp/FreeCodeCamp#5943]
Challenge [Waypoint: Using Objects for Lookups]

I had a problem with the comment line. My correct answer included

  // Only change code above this line
  return result[val];

After changing the switch to an object, I had to ignore the comment line for my version of the answer. I'd suggest moving "  // Only change code above this line " beneath the initial line " return result; ".

**Comment by ltegman** [comment]
This is not necessary. If you had to disregard the instructions you need to think about how else you could solve it without doing that. Thanks and happy coding!
