### ISSUE TITLE
I don't know what‘s that mean.

### ISSUE THREAD

**Issue by zoudifan** [FreeCodeCamp/FreeCodeCamp#5944]
Challenge [Checkpoint: Word Blanks](http://www.freecodecamp.com/challenges/checkpoint-word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20%20%20var%20result%20%3DmyNoun%2C%20myAdjective%20%2C%20myVerb%20%2C%20myAdverb%20%3B%0A%20%20%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%20%0A%0A%20%20%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
    var result =myNoun, myAdjective , myVerb , myAdverb ;
    // Your code below this line
   

    // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by OriBon** [comment]
For this exercise you'll need to use string concatenation to link each of the arguments together.
Such as `var myString = "Max is my " + myNoun` and so on.

Github Issues is primarily for filing bug reports and suggestions/improvements.
You are encouraged to use the Gitter chatroom for help with the exercises. It is very active at all times of the day with plenty of people who will happily help if they can. Good luck!
https://gitter.im/FreeCodeCamp/FreeCodeCamp

**Comment by ltegman** [comment]
Thanks and happy coding!
