### ISSUE TITLE
Waypoint: Introducing JavaScript Object Notation JSON instructions

### ISSUE THREAD

**Issue by dting** [FreeCodeCamp/FreeCodeCamp#5947]
Challenge [Waypoint: Introducing JavaScript Object Notation JSON](http://www.freecodecamp.com/challenges/waypoint-introducing-javascript-object-notation-json) has an issue.

Small nitpick about the instructions:

> **Instructions**
Add a new album to the myMusic JSON object. Add `artist` and `title` **strings**, `release_year` **year**, and a `formats` **array of strings**.

(Bold added)

The first and third items of the list are type, the middle item is not a type. For consistency and clarity (year could be represented as a string), maybe change it to: 

> **Instructions**
Add a new album to the myMusic JSON object. Add `artist` and `title` **strings**, `release_year` **number**, and a `formats` **array of strings**.

or:

> **Instructions**
Add a new album to the myMusic JSON object. Add `artist` and `title` **strings**, `release_year` **year (number)**, and a `formats` **array of strings**.

**Comment by SaintPeter** [comment]
Good observation.  PR Welcome.

Also, WELCOME BACK!

**Comment by dting** [comment]
Any preference on what to change it to? I'll do a PR this weekend if no one else wants to get their feet wet with this easy change.

Thanks! Awesome work on the new content. Really great stuff.

**Comment by SaintPeter** [comment]
> Add a new album to the myMusic JSON object. Add artist and title strings, release_year number, and a formats array of strings.

Looks good to me.  I like it without the parentheses.  

We've got a fair number of active helpers, so there is a good chance someone will pick this one up.

RE: New Content
Thanks, it was a lot of work, but it appears to be paying off.
