### ISSUE TITLE
Commenting the If / else if code does not pass the result .

### ISSUE THREAD

**Issue by piyushdanej** [FreeCodeCamp/FreeCodeCamp#5949]
HI all , In the "Waypoint: Replacing If Else Chains with Switch" when I comment the if / else if code, FCC should pass me but the bullet for "You should not use any else statements" still has the red cross mark. When I DELETE the if /else if code only then it passes me . Ideally It should also pass me if I comment the code .

```
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case "bob":
      answer = "Marley";
      break;
    case 42:
      answer = "The Answer";
      break;
    case 1:
      answer = "There is no #1";
      break;
    case 99:
      answer = "Missed me by this much!";
      break;
    case 7:
      answer = "Ate Nine";
      break;
       }
  
  /*if(val === "bob") {
    answer = "Marley";
  } else if(val === 42) {
    answer = "The Answer";
  } else if(val === 1) {
    answer = "There is no #1";
  } else if(val === 99) {
    answer = "Missed me by this much!";
  } else if(val === 7) {
    answer = "Ate Nine";
  } */
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(7);
```

**Comment by SaintPeter** [comment]
Unfortunately, our tests cannot parse Javascript to determine that you have commented out a section.  This is simply beyond our current capabilities.  This will not be fixed in the foreseeable future.

Thanks and Happy Coding!
