### ISSUE TITLE
wayPoint:resize your image

### ISSUE THREAD

**Issue by wellmoni** [FreeCodeCamp/FreeCodeCamp#5951]
This is my code but am not getting the 100 px image width please I really need  help me out.

 <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace; 
   
  }
 .smaller-image {
    
    width: 100px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2> 

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat"/>
  
<img class="smaller-image">https://bit.ly/fcc-relaxing-cat</img>

**Comment by raisedadead** [comment]
Ask for help at : [Help Chat](https://gitter.im/FreeCodeCamp/Help)
Also please refer these [guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/#found-a-bug)

**Comment by ltegman** [comment]
@raisedadead is correct. Thanks and happy coding!
