### ISSUE TITLE
Waypoint: Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by rlabuonora** [FreeCodeCamp/FreeCodeCamp#5953]
The explanation text says:

See how `Math.floor` takes `(Math.random() * 20)` as its argument? That's right - you can pass a function to another function as an argument.

But the function call is `Math.floor(Math.random() * 20);` 
It's not passing the function as an argument, it's calling it and passing the result of the call times 20.

**Comment by ltegman** [comment]
Very true.

**Comment by pmbenjamin** [comment]
So, suggested wording:
**Before:**
```
See how Math.floor takes (Math.random() * 20) as its argument? That's right - you can pass a function to another function as an argument.
```

**After:**
```
We are calling Math.random(), multiplying the result by 20, then rounding down using Math.floor() function.
```

**Comment by raisedadead** [comment]
@pmbenjamin :+1:

**Comment by pmbenjamin** [comment]
Perhaps, a clearer description:
```
We are calling Math.random(), multiplying the result by 20, then passing the value to Math.floor() function to round the result down to the nearest whole number.
```

**Comment by ltegman** [comment]
@pmbenjamin Your latest one sounds good to me. It's a little bit wordier, but I think it describes what is going on much more clearly and accurately :+1:
