### ISSUE TITLE
Is it Correct? Sorry for asking But only want to know is it legit way?

### ISSUE THREAD

**Issue by rowhitswami** [FreeCodeCamp/FreeCodeCamp#5955]
Challenge [Waypoint: Finding a Remainder in Javascript](http://www.freecodecamp.com/challenges/waypoint-finding-a-remainder-in-javascript#?solution=%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myVar%20%3D%2011%20%25%203%3B%0Avar%20remainder%20%3D%20myVar%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Only change code below this line
var myVar = 11 % 3;
var remainder = myVar;


```

**Comment by ltegman** [comment]
Assigning it to myVar first adds an unnecessary extra step, but there's nothing wrong with it. This isn't what Github issues are for, so in the future please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and happy coding!
