### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Philosophist** [FreeCodeCamp/FreeCodeCamp#5958]
Challenge [Waypoint: Accessing Objects Properties with Variables](http://www.freecodecamp.com/challenges/waypoint-accessing-objects-properties-with-variables#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3D%2016%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%5BplayerNumber%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;       // Change this Line
var player = testObj[playerNumber];   // Change this Line

```
propName in the example should have quotation marks. I wasn't sure at first if the playerNumber value should be a string with quotes or an integer because it looked like propName didn't need quotation marks.

**Comment by ltegman** [comment]
Quotes are not necessary for the property names in an object literal unless you want to include something like a space in your name.

Thanks and happy coding!

**Comment by Philosophist** [comment]
Then why did ["16"] not work, but [16] worked? I think you need to test the
example code for yourself to see that the quotes are required.
