### ISSUE TITLE
copied other's code to my code by looking at another camper's profile.

### ISSUE THREAD

**Issue by gDollaZ** [FreeCodeCamp/FreeCodeCamp#5959]
I was attempting to do the Bonfire: Diff Two Arrays and wanted to find a simpler solution than the one I came up with, so I went to chat and then had a look at a fellow camper's profile. I had my freecodecamp code window open on the same problem and then I checked the code by going to their profile and then clicked view my solution to see their code, when I returned to my code window their code was transferred into my window.

**Comment by Oxyrus** [comment]
That happened to me this morning, the submit button should dissappear when you're looking at other's code.

**Comment by sludge256** [comment]
Reference: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5886
If you scroll down @SaintPeter suggests opening fellow campers' solutions in a private window.

**Comment by BerkeleyTrue** [comment]
You're code is still stored on you're profile and accessible through your profile page. It is not stored on individual challenges. We store you're latest code in the editor in localStorage. This is meant as a way to save progress incase you need to step away, not a long term storage system or to store your valid solutions.

Happy Coding!
