### ISSUE TITLE
Editor not passing correct code

### ISSUE THREAD

**Issue by gitasong** [FreeCodeCamp/FreeCodeCamp#5961]
Challenge [Checkpoint: Golf Code](http://www.freecodecamp.com/challenges/checkpoint-golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(strokes%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20return%20%22Hole-in-one%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%3D%20(par%20-%202)%20%26%26%20strokes%20%3E%201)%20%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20par%20-%201)%20%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20par)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20par%20%2B%201)%20%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20par%20%2B%202)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Go%20Home!%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(1%2C%201)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes === 1) {
    return "Hole-in-one";
  } else if (strokes <= (par - 2) && strokes > 1) {
    return "Eagle";
  } else if (strokes === par - 1) {
    return "Birdie";
  } else if (strokes === par) {
    return "Par";
  } else if (strokes === par + 1) {
    return "Bogey";
  } else if (strokes === par + 2) {
    return "Double Bogey";
  } else {
    return "Go Home!";
  }
  
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(1, 1);

```
My code checks out (i.e. returns the correct values) in repl.it, but doesn't pass for test cases (4, 1) and (1, 1) in the FCC editor, even though the console shows the correct return values. Please confirm.

**Comment by SaintPeter** [comment]
Your code is not correct.  You are missing an exclamation point for hole in one.  

Thanks and Happy Coding!

**Comment by ltegman** [comment]
You're missing an exclamation point. Thanks and happy coding!

**Comment by gitasong** [comment]
LOL—no wonder! ;)
