### ISSUE TITLE
Problem with Increment.

### ISSUE THREAD

**Issue by tsevillano** [FreeCodeCamp/FreeCodeCamp#5963]
Challenge [Waypoint: Increment a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%20%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar ++;


```

**Comment by tsevillano** [comment]
And I have a problem with this lines:

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar++;

```

**Comment by ltegman** [comment]
Please read the challenge instructions carefully and don't use github issues for help. This is not a bug. Thanks and happy coding!
