### ISSUE TITLE
Test should pass 

### ISSUE THREAD

**Issue by sidsarasvati** [FreeCodeCamp/FreeCodeCamp#5964]
Challenge [Waypoint: Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/waypoint-return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(%20a%20%3C%200)%20%7B%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%20%0A%20%20if(b%20%3C%200)%20%7B%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%0A%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  if( a < 0) {
    return "undefined";
  } 
  if(b < 0) {
    return "undefined";
  }

  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

```

**Comment by ltegman** [comment]
The directions say to return `undefined` not `"undefined"`. Please make sure what you're seeing is actually a bug in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) before filing bugs. Thanks and happy coding!

**Comment by ulbenson** [comment]
.......why nunu why

**Comment by AlexMogoryan** [comment]
Yes, Itegman is corre, return  undefined;
Thanks
No bug here lol

**Comment by sdiscul4** [comment]
the correct answer is

// Setup
function abTest(a, b) {
  // Only change code below this line
  if(a < 0 || b < 0){
    return undefined;
  }
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

happy codding!!!!!!!!!!!!!!!

**Comment by texas2010** [comment]
@sdiscul4 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by AgbajeMike** [comment]
The undefined is not a string. Remove the quote from it. My code that passed shown below.
Happy coding.
function abTest(a, b) {
  // Only change code below this line
  if (a<0||b< 0) {
    return undefined;
  
  // Only change code above this line
  }else{
  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

**Comment by texas2010** [comment]
@AgbajeMike 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
