### ISSUE TITLE
Test passes successfully even if we don't end the code with ';'

### ISSUE THREAD

**Issue by vishukamble** [FreeCodeCamp/FreeCodeCamp#5966]
Challenge [Waypoint: Declare String Variables](http://www.freecodecamp.com/challenges/waypoint-declare-string-variables#?solution=%2F%2F%20Example%0Avar%20firstName%20%3D%20%22Alan%22%3B%0Avar%20lastName%20%3D%20%22Turing%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myFirstName%20%3D%22Vishu%22%3B%0Avar%20myLastName%20%3D%22Kamble%22%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var firstName = "Alan";
var lastName = "Turing";

// Only change code below this line
var myFirstName ="Vishu";
var myLastName ="Kamble"

```

Please add an additional check for syntac errors.

**Comment by ltegman** [comment]
This is valid javascript, so this is fine. You can get yourself into trouble by leaving off semicolons, but there's nothing syntactically incorrect about it. Thanks and happy coding!
