### ISSUE TITLE
Test passed even if we don't enter string and just put " "

### ISSUE THREAD

**Issue by vishukamble** [FreeCodeCamp/FreeCodeCamp#5967]
Challenge [Checkpoint: Shopping List](http://www.freecodecamp.com/challenges/checkpoint-shopping-list) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myList = [["",23,21,24,56,78],["",21,43,56,23,78],["",23,12,23,4,5,],["",23,1,2,3,4],["",23,54,32,67,87]];
```
The test includes: The first elements in each of your sub-arrays must all be strings
My code does not have strings but since it starts and ends with ", it passes the test.
Try adding a check to see if the first elements of all sub-arrays have a (length>0)

**Comment by denmch** [comment]
Try this: `typeof "";` and you'll see that `""` is actually a string. It's an empty string, but a string nonetheless.

**Comment by SaintPeter** [comment]
The tests cannot possibly be comprehensive.  I figure if you're smart enough to fool the tests in this way, you're more than smart enough to have learned the lesson I'm trying to teach.  While I could put a length check in there, the checking code for this is already kinda hairy, so I'm not going to.

Do appreciate you bringing it to our attention, but this is a solid "won't fix".

Thanks and happy coding!
