### ISSUE TITLE
 Bonfire: Title Case a Sentence

### ISSUE THREAD

**Issue by MariamShqair** [FreeCodeCamp/FreeCodeCamp#5970]
Challenge [Bonfire: Title Case a Sentence](http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence#?solution=%20%20%20%20function%20titleCase(str)%20%7B%0A%20%20%20%20%20%20var%20titCa%2Cword%2CfirstLitter%3B%20%0A%20%20%20%20%20%20word%3D%22%22%3B%0A%20%20%20%20%20%20str%3Dstr.toLowerCase('%20')%3B%0A%20%20%20%20%20%20titCa%3Dstr.split(%22%20%22)%3B%0A%20%20%20%20%20%20for(var%20i%3D0%3Bi%3CtitCa.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20%20%20titCa%5Bi%5D%3DtitCa%5Bi%5D.split(%22%22)%3B%0A%20%20%20%20%20%20firstLitter%20%3D%20%20titCa%5Bi%5D%5B0%5D.toUpperCase('')%3B%0A%20%20%20%20%20%20%20%20titCa%5Bi%5D%5B0%5D%3D%20firstLitter%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20word%3D%20word%2B%22%20%22%2B%20titCa%5Bi%5D.join('')%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%0A%20%20%0A%20return%20word%3B%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
please help with this code ,it give true result but I can't pass issue :angry: 
this is the issue :: 
Return the provided string with the first letter of each word capitalized. Make sure the rest of the word is in lower case.

this is My code:
```javascript
    function titleCase(str) {
      var titCa,word,firstLitter; 
      word="";
      str=str.toLowerCase(' ');
      titCa=str.split(" ");
      for(var i=0;i<titCa.length;i++){
        titCa[i]=titCa[i].split("");
      firstLitter =  titCa[i][0].toUpperCase('');
        titCa[i][0]= firstLitter;
        
     word= word+" "+ titCa[i].join('');
      }
       
  
 return word;
}

titleCase("sHoRt AnD sToUt");

```

**Comment by kirah1314** [comment]
Your codes create an extra space in front of the first word.
This is what comes out of the console: => ' Short And Stout'

**Comment by MariamShqair** [comment]
How to solve please me  more  details>>

**Comment by pmbenjamin** [comment]
@MariamShqair I don't think this is a bug in the challenge. In the future, I would ask other students on the live [FreeCodeCamp/Help](https://gitter.im/FreeCodeCamp/Help) chat. 

In the meantime, I hope this helps:  [REPL.IT](https://repl.it/Bc0l/1)

**Comment by MariamShqair** [comment]
@pmbenjamin 
I'm trying to solve this issue again and again and it give me the same problem , It put the sentence between ' 'single quotation marks..
:tired_face:

**Comment by MariamShqair** [comment]
Finally it's worked the final code:
function titleCase(str) {
 var pieces = str.split(" ");
    for ( var i = 0; i < pieces.length; i++ )
    {    pieces[i]=pieces[i].toLowerCase();
        var j = pieces[i].charAt(0).toUpperCase();
        pieces[i] = j + pieces[i].substr(1);
    }
    return pieces.join(" ");}
       
  


titleCase("sHoRt AnD sToUt");

**Comment by royshouvik** [comment]
@MariamShqair Please close this issue if your problem is resolved. Thanks.

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
