### ISSUE TITLE
Waypoint: Return a Value from a Function with Return

### ISSUE THREAD

**Issue by CursedCat** [FreeCodeCamp/FreeCodeCamp#5972]
Challenge [Waypoint: Return a Value from a Function with Return](http://www.freecodecamp.com/challenges/waypoint-return-a-value-from-a-function-with-return#?solution=%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20timesFive(numb)%20%7B%0A%20%20return%20numb%20*%205%3B%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line
function timesFive(numb) {
  return numb * 5;
}


```
/* problem in this waypoint is that it is not complete yet i can pass it , it should be more like this 
function plusThree(num) {
  return num + 3;
}
var answer = plusThree(5); // 8

but var answer = plusThree(5); is missing
*/

**Comment by SaintPeter** [comment]
You're suggesting that we also have the user invoke the function?

**Comment by CursedCat** [comment]
yes i think that is what it means , it took me long time to realize that timesfive had a background of 5.
or explain it in a comment , thanks.

**Comment by SaintPeter** [comment]
I'm not sure that there is anything to fix here. This is pretty much operating as designed.
