### ISSUE TITLE
Extra semicolons at the top and bottom of the HTML Preview

### ISSUE THREAD

**Issue by antoineLeclercq** [FreeCodeCamp/FreeCodeCamp#5973]
Two semicolons at the top and bottom of the phone screen.
![screen shot 2016-01-08 at 12 05 11 pm](https://cloud.githubusercontent.com/assets/15240972/12204095/26bfea82-b600-11e5-85f9-82bcf5848499.png)

**Comment by sludge256** [comment]
They appear on all the lessons with a phone preview. I was hoping to submit a fix but haven't had the time to look into it yet.

**Comment by antoineLeclercq** [comment]
Indeed they do appear on all lessons with a phone preview. But I don't think they were appearing a few days ago.

**Comment by sludge256** [comment]
The earliest that I was made aware of them and checked, was two days ago. Anytime before that I am unsure of.

**Comment by SaintPeter** [comment]
This is my bad.

I added them for another reason, not realizing they'd break the HTML waypoints.

**Comment by anirudhE** [comment]
It might be due to some garbage in source code@freecodecamp.:)
