### ISSUE TITLE
Waypoint: Concatenating Strings with Plus Operator

### ISSUE THREAD

**Issue by nf15** [FreeCodeCamp/FreeCodeCamp#5977]
Where I made a mistake?  var myStr = "This is the start." + "This is the end.";

**Comment by sludge256** [comment]
>Build **myStr** from the strings "`This is the start. `" and "`This is the end.`" using the + operator.
Pay close attention to spaces in the given strings also.

In the future please use https://gitter.im/FreeCodeCamp/Help for non-site related issues.

**Comment by nf15** [comment]
Thanks.

**Comment by SaintPeter** [comment]
Closing as this is not a site related issue.

**Comment by mihaelamardare** [comment]
@sludge256  your answer helped me also, thanks
