### ISSUE TITLE
palindrome("0_0 (: /-\ :) 0-0") should return true. is wrong

### ISSUE THREAD

**Issue by Kalurege** [FreeCodeCamp/FreeCodeCamp#5982]
without writing code this cannot be a palindrome.one starts as 0_ while the reverse starts as 0-
so it should return false

**Comment by sludge256** [comment]
>You'll need to remove all non-alphanumeric characters **(punctuation, spaces and symbols)** and turn everything lower case in order to check for palindromes.

**Comment by Kalurege** [comment]
cool.actually it does say in the question.i just saw palindrome and straight went to coding :) thanks

**Comment by MarcDearden** [comment]
Thank you for helping, I appreciate the help.
