### ISSUE TITLE
Map data across globe is inaccurate when zooming.

### ISSUE THREAD

**Issue by fugalfunkster** [FreeCodeCamp/FreeCodeCamp#5985]
As you zoom in, the points wander. Something static might be better?

Update by @raisedadead
Challenge has been renamed to 
https://www.freecodecamp.com/challenges/map-data-across-the-globe

**Comment by fugalfunkster** [comment]
Here's my static version: http://codepen.io/fugalfunkster/full/gPgxeP/

**Comment by ltegman** [comment]
Confirmed.

**Comment by bugron** [comment]
@fugalfunkster @ltegman is this still an issue?

**Comment by fugalfunkster** [comment]
Yep. Looks unchanged from when I first noticed the bug.

**Comment by davidbrodrick32** [comment]
Xzibit Xzibit-aaQ C 3 R READ T RD F FT BR



Sent from my Samsung device

-------- Original message --------

**Comment by eddyerburgh** [comment]
Yep, problem still there. I recommend taking out the zoom functionality.

**Comment by davidbrodrick32** [comment]
Hi,

Your friend davidbrodrick28@gmail.com has decided to give you 103 GB free cloud storage space with Degoo. With Degoo you never have to lose a photo ever again!

Just click here to get started: https://degoo.com/g/VXNrTY?email=reply@reply.github.com&utm_source=web-api&utm_content=text

Let me know if you have any questions. I'll gladly help!

Best Regards
Carl Hasselskog
CEO, Degoo
