### ISSUE TITLE
Suggestion for improving News page

### ISSUE THREAD

**Issue by GFore** [FreeCodeCamp/FreeCodeCamp#5987]
Suggestion for improving the News page in FCC: Provide other options for sorting the articles, especially to allow sorting by post date. The number of articles is growing quickly, and it's hard to quickly jump to the ones you haven't read since the order changes constantly based on upvotes. If you had the option to sort by post date, then you could quickly skip the ones you've seen.

**Comment by SaintPeter** [comment]
I like this idea.  This should be easy enough to do with our API.

**Comment by bugron** [comment]
Good idea. By the way, you can search your (or any other camper's) posts by using `@username` as a Camper News search query, where `username` is yours or the camper's username whose posts you're looking for.

**Comment by SaintPeter** [comment]
@bugron What that suggests to me is that we could update the placeholder text:
![image](https://cloud.githubusercontent.com/assets/553494/12218064/6e5998c0-b6c8-11e5-83a4-e7419502d88c.png)

That would make it clearer that you can search by submitter.

**Comment by bugron** [comment]
Looks great.

**Comment by benmcmahon100** [comment]
This will be solved once the React version of the news is complete

**Comment by bugron** [comment]
Closing this issue because Camper News is being removed for some reason.
