### ISSUE TITLE
conditional checking fails

### ISSUE THREAD

**Issue by ufairiya** [FreeCodeCamp/FreeCodeCamp#5988]
Below if different values of a, b are provided,the condition failed
failed cases are : abTest(-2,2) should return undefined
abTest(2,-2) should return undefined

// Setup
function abTest(a, b) {
  // Only change code below this line
  if(a < 0) { return "undefined";}
  if(b < 0) { return "undefined";}
    
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

**Comment by sludge256** [comment]
>Instructions
Modify the function abTest so that if a or b are less than 0 the function will immediately exit with a **value** of undefined.

Return the value `undefined` not "`undefined`" as a string.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined
