### ISSUE TITLE
The example presented for the challenge "Target the Parent of an Element Using jQuery" does not work

### ISSUE THREAD

**Issue by re4ect** [FreeCodeCamp/FreeCodeCamp#5989]
[Target the Parent of an Element Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery#?solution=fccss%0A%20%20%24%28document%29.ready%28function%28%29%20{%0A%20%20%20%20%24%28%22%23target1%22%29.css%28%22color%22%2C%20%22red%22%29%3B%0A%20%20%20%20%24%28%22%23target1%22%29.prop%28%22disabled%22%2C%20true%29%3B%0A%20%20%20%20%24%28%22%23target4%22%29.remove%28%29%3B%0A%20%20%20%20%24%28%22%23target2%22%29.appendTo%28%22%23right-well%22%29%3B%0A%20%20%20%20%24%28%22%23target5%22%29.clone%28%29.appendTo%28%22%23left-well%22%29%3B%0A%20%20%20%20%0A%20%20%20%20%24%28%22%23left-well%22%29.parent%28%29.css%28%22background-color%22%2C%20%22red%22%29%0A%20%20%20%20%0A%20%20%20%20%0A%20%20}%29%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cbody%3E%0A%20%20%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fbody%3E%0A)

The challenge presents the user with the example $("#left-well").parent().css("background-color", "blue") but that example does not create a background color. By looking at the picture you can tell it does not work which begs the question, why even add the example to the challenge?

PS. I found the correct method for the challenge, but I still don't understand why you would show a different method to the user when the method does not work correctly.

![screenshot-www freecodecamp com 2016-01-09 02-19-43](https://cloud.githubusercontent.com/assets/14848245/12215047/4de0ec0a-b679-11e5-8766-881b0c318f62.png)

**Comment by sludge256** [comment]
The example code does work. What you have in the editor does not match the example code.

**Comment by re4ect** [comment]
@sludge256 How is it wrong? I did exactly what it asks, I have typed the layout multiple times and I even copied the example to compare and check what I am doing wrong. I have gone over this multiple times and yet I don't see anything wrong.

**Comment by sludge256** [comment]
If you look at the the example code there is nothing within the parenthesis of `parent()` while your code does.

**Comment by re4ect** [comment]
I hate to break it to you but the parent() is between ("#left-well") the .css

PS. the example is as follows $("#left-well").PARENT().css("background-color", "blue") 
(the parent() is capitalized so you can see what I am talking about).

**Comment by sludge256** [comment]
The code you used in your screenshot is:
```js
$("#left-well").parent("#target1").css("background-color", "red")
```

**Comment by re4ect** [comment]
This is what my answer is but the challenge is not accepting it. And what about the .parent() method? I still need it just like the challenge says.

![screenshot-www freecodecamp com 2016-01-09 03-28-54](https://cloud.githubusercontent.com/assets/14848245/12215210/31770d08-b681-11e5-9e1c-a12f31ef907c.png)

**Comment by sludge256** [comment]
You are calling the `parent()` method on `#left-well` when the instructions ask for it to be called on `#target1`.

**Comment by re4ect** [comment]
The way I am reading it is like this it's saying to put #target1 between the empty parenthesis.
