### ISSUE TITLE
Manage NPM Packages with NPM - 03 login : unable to create new user 

### ISSUE THREAD

**Issue by YannHulot** [FreeCodeCamp/FreeCodeCamp#5992]
Trying to go through 03 login but unable to add a user with the adduser command.

This is the message i get in my npm-debug file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm',
1 verbose cli   'whoami' ]
2 info using npm@3.5.3
3 info using node@v4.1.1
4 verbose stack Error: this command requires you to be logged in.
4 verbose stack     at EventEmitter.whoami (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/lib/whoami.js:41:18)
4 verbose stack     at Object.commandCache.(anonymous function) (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/lib/npm.js:216:13)
4 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/bin/npm-cli.js:74:30)
4 verbose stack     at doNTCallback0 (node.js:407:9)
4 verbose stack     at process._tickCallback (node.js:336:13)
5 verbose cwd /home/ubuntu/workspace
6 error Linux 4.2.0-c9
7 error argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "whoami"
8 error node v4.1.1
9 error npm  v3.5.3
10 error code ENEEDAUTH
11 error need auth this command requires you to be logged in.
12 error need auth You need to authorize this machine using `npm adduser`
13 verbose exit [ 1, true ]

```

and this is what i get after trying to add a user with the adduser command:

```
yannhulot:~/workspace/ProjectFolder $ npm adduser
Username: yann
Password: 
Email: (this IS public) yann@pc.com
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "adduser"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.3
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:yann
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/ProjectFolder/npm-debug.log
yannhulot:~/workspace/ProjectFolder $ 
```
Any help on how to solve the problem would be appreciated. Thanks.

**Comment by YannHulot** [comment]
I have also reported the issue on https://github.com/npm/npm/issues . Will update if I hear from them first.

**Comment by SaintPeter** [comment]
I am utterly without context here.  What is "03 Login"?  What are you even talking about?  Is this about the NPM waypoints?

**Comment by YannHulot** [comment]
My apologies, I am new to all this. Yes, it is about the npm waypoints: manage NPM packages with NPM. Step 3 of how-to-npm also known as : "03 login", does not seem to work. I have followed the instructions but somehow the command "adduser" to create a new user doesn't work. Also the command "whoami" doesn't work either. If you look at my first message you will see the two error messages: the npm-debug.log is at the top  and the one at the bottom of my message is from the command line. 
Being new to this, I am not excluding the fact that I could be the one making a mistake but would like to know if this is a known bug and if it is then how do I fix it. Thank You and again sorry about the lack of context of my first message.

**Comment by SaintPeter** [comment]
Have you tried starting at step 1 again?  The error seems to suggest that you didn't complete either the add use or the login step correctly.

I seem to recall a LOT of discussion on these steps, but I can't seem to find it.  The consensus seemed to be that prior steps were not being completed correctly.   Try starting from the beginning and see if that helps.

**Comment by YannHulot** [comment]
Hi thanks for the quick reply. I have successfully completed step 1 and step 2. I have tried on 2 different workspaces. I understand that how-to-npm is only a third party package and that you may not have a way to fix it .  I just wanted to let you know that there is a problem and that some campers may be facing the same issue. In the meantime I will try to find other tutorials to follow. Thank you for your help.

**Comment by SaintPeter** [comment]
I think you misunderstand the instructions.  You need to do an adduser command:
```
saintpeter@how-to-npm:~/workspace/test $ npm whoami
npm ERR! Linux 4.2.0-c9
npm ERR! argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "whoami"
npm ERR! node v0.10.35
npm ERR! npm  v3.5.3
npm ERR! code ENEEDAUTH

npm ERR! need auth this command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/test/npm-debug.log
saintpeter@how-to-npm:~/workspace/test $ npm adduser
Username: happycamper
Password: 
Email: (this IS public) happy@example.com
saintpeter@how-to-npm:~/workspace/test $ npm whoami
happycamper
```

I get the same "error" that you do, but I see that I need to add my user, which I do, and then it works.

>Because this is just a tutorial adventure, remember, we're not
*actually* creating an account anywhere.  However, when you run
this in the Real World, it'll create a real account, with a page
on npmjs.com and the ability to publish packages that real live
humans can install and enjoy.

>To see who you're logged in as, run `npm whoami`

>**To create your account, run `npm adduser`**

Emphasis added.

**Comment by SaintPeter** [comment]
Unless I have misunderstood you issue, of course.

**Comment by YannHulot** [comment]
Hi again and thank you for taking the time to reply to me. I just tried again to run the command "npm adduser" after successfully completing the first 2 steps in a new workspace. When I type the command "npm adduser", I am asked to provide a username, password and email. after doing all those things , I still get the error message. Same one as above. One thing is different on your workspace though. Your node version is 0.10.35 whereas mine is 4.1.1. Could that be the problem? 

```
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "adduser"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.3
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:yann
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/ProjectFolder/npm-debug.log
yannhulot:~/workspace/ProjectFolder $ 

```

**Comment by SaintPeter** [comment]
Confirmed.  It does appear to have something to do with versions.
```
saintpeter:~/workspace/test $ npm whoami
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "whoami"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.3
npm ERR! code ENEEDAUTH

npm ERR! need auth this command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/test/npm-debug.log
saintpeter:~/workspace/test $ npm adduser
Username: test
Password: 
Email: (this IS public) test@example.com
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "adduser"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.3
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:test
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/test/npm-debug.log
saintpeter:~/workspace/test $ 
```

**Comment by YannHulot** [comment]
Ok. Great thank you for taking the time to reply to my inquiries. Is there a way that can I change my version of node? If not could you point me towards another tutorial? Thank you.

**Comment by SaintPeter** [comment]
Yes, `nvm` - node version manager - is installed on c9 by default.  Please let me know if you are able to find the solution.  I doubt you are the only one having this issue.

**Comment by YannHulot** [comment]
I will try again later on after changing the node version to 0.10.35. If it works I will let you know and maybe you could add a warning on the side column of this page: http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm explaining that if campers have the 4.1.1 version of node installed, they would need to revert to node 0.10.35 in order to complete the waypoints. Thanks again for your time. I really appreciate it.

**Comment by ltegman** [comment]
Closing this issue as it is a bug with how-to-npm. We have #3685 tracking the fact that there are issues with this module necessitating improvements to our npm lesson.

**Comment by SaintPeter** [comment]
@ltegman I reviewed that issue and it's unrelated to this specific issue.  This appears to be new and separate.  The other one is about tags.

**Comment by ltegman** [comment]
It's tracking that using how-to-npm exposes us to external bugs and we need something better. Regardless, this is a how-to-npm bug.

**Comment by bernardndegwa** [comment]
Was the issue resolved?
Thanks.

**Comment by YannHulot** [comment]
No, at least not for me. I have skipped ahead to the tutorial: Start a node.js server.

**Comment by ManBearPigg** [comment]
**Working solution as of April 2, 2016**

Complete Step 3: "Start a project" _before_ Step 2: "Login". Use the same login credentials in step 2 that you established in step 3.

**Comment by dfghj44444** [comment]
I met the issue and after reverted npm to 0.10.35,nothing change 
every time adduser ,it told me
Error: connect ECONNREFUSED
