### ISSUE TITLE
It does not return Birdie with golfscore(4,3). what is wrong with my code?

### ISSUE THREAD

**Issue by farooqy** [FreeCodeCamp/FreeCodeCamp#5994]
Challenge [Checkpoint: Golf Code](http://www.freecodecamp.com/challenges/checkpoint-golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20%20if%20(strokes%20%3D%3D%3D%201)%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3C%3D%20par%20-%201)%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20-%201)%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par)%7B%0A%20%20%20%20return%22Par%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20%2B%201)%7B%0A%20%20%20%20return%22Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if%20(strokes%20%3D%3D%20par%20%2B%202)%7B%0A%20%20%20%20return%22Double%20Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3E%3D%20par%20%2B%203)%7B%0A%20%20%20%20return%22Go%20Home!%22%3B%0A%20%20%7D%0A%20%20else%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(4%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2612.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
    if (strokes === 1){
    return "Hole-in-one!";
  }
  else if (strokes <= par - 1){
    return "Eagle";
  }
  else if (strokes == par - 1){
    return "Birdie";
  }
  else if (strokes == par){
    return"Par";
  }
  else if (strokes == par + 1){
    return"Bogey";
  }
  else if (strokes == par + 2){
    return"Double Bogey";
  }
  else if(strokes >= par + 3){
    return"Go Home!";
  }
  else 
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(4, 3);

```

**Comment by studenton** [comment]
The error is in eagle portion.
```html 
else if (strokes <= par - 1){
    return "Eagle";
  }
```

It should be strokes<=par-2

**Comment by SaintPeter** [comment]
@studenton is correct.

Issues are for bug reporting, not code help.  You should ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) before posting a bug.
