### ISSUE TITLE
bug in Waypoint: Change the Font Size of an Element online text editor

### ISSUE THREAD

**Issue by ajinkyaT** [FreeCodeCamp/FreeCodeCamp#5996]
Challenge [Waypoint: Change the Font Size of an Element](http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20h1%20%7B%0A%0A%20%20font-size%3A%2016px%3B%0A%0A%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3E%20Purr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  h1 {

  font-size: 16px;

}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text"> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by studenton** [comment]
You have to change the font size of all p elements. So the code should be like this
```
<style>
  .red-text {
    color: red;
  }
  p {

  font-size: 16px;

}
</style>
```

**Comment by SaintPeter** [comment]
@studenton is correct.

Issues are for bug reporting, not code help.  You should ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) before posting a bug.

**Comment by ajinkyaT** [comment]
Sorry for my mistake hence forth I will take care of it.
