### ISSUE TITLE
Test is wrong

### ISSUE THREAD

**Issue by LookOnTheBrightSide** [FreeCodeCamp/FreeCodeCamp#5997]
![screen shot 2016-01-09 at 2 03 00 pm](https://cloud.githubusercontent.com/assets/7965221/12215929/c966855a-b6d9-11e5-82d9-0a76cdd3a740.png)
Challenge [Waypoint: Returning Boolean Values from Functions](http://www.freecodecamp.com/challenges/waypoint-returning-boolean-values-from-functions#?solution=function%20isLess(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Fix%20this%20code%0A%20return%20a%20%3D%3D%3D%20b%3B%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AisLess(10%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function isLess(a, b) {
  // Fix this code
 return a === b;
}

// Change these values to test
isLess(10, 15);

```

**Comment by TravisHi** [comment]
Your code isn't fulfilling the requirements of the Waypoint.

Works as expected when you change the return statement to match the criteria requests.

There's a hint in the name of the function :)

**Comment by LookOnTheBrightSide** [comment]
my bad...

**Comment by mohannadsawalhi** [comment]
switch (isLess){
    
  case a, b:
 
  return a > b;

  default :
    
    return a < b;
 
    
}

**Comment by mehadi07** [comment]
function isLess(a, b) {
 
  return (a <= b);
}


isLess(10, 15);

This one will work too

**Comment by Shahadot-shr** [comment]
function isLess(a, b) {
  // Fix this code
 return a <= b;
}

// Change these values to test
isLess(10, 15);
