### ISSUE TITLE
Confusing question

### ISSUE THREAD

**Issue by kurapikats** [FreeCodeCamp/FreeCodeCamp#5998]
Hi, on all 103 JS questions, this is the only part I got confused. 
and on the chat room, there's 3 campers also couldn't understand it.

-70.Checkpoint: Golf Code

**Comment by TravisHi** [comment]
What part(s) did you and they not understand?

**Comment by kurapikats** [comment]
the table reference for par/strokes return.

**Comment by SaintPeter** [comment]
Issues are for bug reporting, not code help.  You should ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) before posting a bug.

Our many dedicated helpers will be able to answer your questions there.

In the future you should consider what specifically you are looking for help for - both in filing an issue and in asking for help.  It's no good to say "I don't understand" without stating what yout don't understand.  We can't read your mind.  Tell us what you think and what you've tried . . . or at least tell that to the folks in the Help room.

Thanks and Happy Coding!
