### ISSUE TITLE
titleCase challenge

### ISSUE THREAD

**Issue by hk99** [FreeCodeCamp/freecodecamp#60]
I'm getting an error on this challenge and can't continue.

![img](https://cloud.githubusercontent.com/assets/5067958/5951389/bb553160-a71b-11e4-8f55-44547fbe3709.png)

**Comment by terakilobyte** [comment]
Thanks for notifying us. A fix is waiting to go live to the servers. I'll close this issue when that happens and we verify it on the live site.

**Comment by QuincyLarson** [comment]
Sorry for the delay. I just verified this is now fixed.
