### ISSUE TITLE
not about Caesar's Cipher, I'm having problems with the Chunky Monkey page

### ISSUE THREAD

**Issue by HengTom** [FreeCodeCamp/FreeCodeCamp#6005]
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![bugissue](https://cloud.githubusercontent.com/assets/14630340/12218788/1c52daf8-b6de-11e5-9fc6-654a5f1e01a7.jpg)

```

**Comment by HengTom** [comment]
the page doesn't work when I open the bonfire challenge and chrome has me kill the page

**Comment by SaintPeter** [comment]
You possible have an infinite loop.  You can disable the auto run by modifying the URL:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run

Barring that, you can delete your code from Local Storage:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage

Please let us know if either of those helps.

**Comment by Pwter** [comment]
(i=1)*size will set your i variable to 1 one making it an infinite loop

**Comment by ltegman** [comment]
Good catch @Pwter. Closing as not an issue with the site.
