### ISSUE TITLE
Challenge passes, but the console does not show a change in parameters

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/FreeCodeCamp#6008]
Challenge [Waypoint: Return a Value from a Function with Return](http://www.freecodecamp.com/challenges/waypoint-return-a-value-from-a-function-with-return#?solution=%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20timesFive(num)%20%7B%0A%20%20return%20num%20*%205%3B%0A%7D%0Avar%20answer%20%3D%20timesFive(10)%3B%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line
function timesFive(num) {
  return num * 5;
}
var answer = timesFive(10);




```

**Comment by vicky002** [comment]
@tommygebru Can you please reproduce the error and add a screenshot? I tried and it's working fine for me.

**Comment by bugron** [comment]
@tommygebru thanks for posting this issue!
Are you talking about this?
![](http://i.imgur.com/QskvKyE.png)

If yes it is hardcoded to be what you see:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1989

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ltegman** [comment]
This is expected. Thanks and happy coding!
