### ISSUE TITLE
Chrome shows violates Content Security Policy directive

### ISSUE THREAD

**Issue by vicky002** [FreeCodeCamp/FreeCodeCamp#6009]
```
waypoint-say-hello-to-html-elements:1 Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewogICAgLy8gaHR0cHM6Ly9k…ogICAgZ2EucmVtb3ZlID0gbm9vcGZuOwogICAgd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' .google-analytics.com .gstatic.com https://*.cloudflare.com .cloudflare.com https://.gitter.im https://*.cdnjs.com .cdnjs.com https://.jsdelivr.com .jsdelivr.com .twimg.com https://*.twimg.com 'self'".
```

![Uploading image.png…](https://files.gitter.im/FreeCodeCamp/FreeCodeCamp/yHQW/code3.JPG)

Reference : https://developer.chrome.com/extensions/contentSecurityPolicy

**Comment by bugron** [comment]
@vicky002  thanks for posting this issue!
Seems you have a similar issue as in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5999 so let's keep the discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by BerkeleyTrue** [comment]
@vicky002 Where are you located?

**Comment by vicky002** [comment]
Mumbai.
