### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-html5-to-require-a-field has an issue 

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#601]
the prior challenge already had placeholder text as a requirement & test to pass.  The starting HTML code in this challenge removes the previously entered placeholder text and adds it as a new requirement. (redundant for the user)

**Comment by terakilobyte** [comment]
It looks like this has been fixed in a previous commit. Thanks for the report.
