### ISSUE TITLE
Missing semicolon in string declaration for valid Javascript

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6012]
Challenge [Waypoint: Declare String Variables](http://www.freecodecamp.com/challenges/waypoint-declare-string-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var firstName = "Alan";
var lastName = "Turing";

// Only change code above this line.

```

In the instructions, the string declaration in the code example is missing a semicolon in order for it to be valid Javascript code.

![image](https://cloud.githubusercontent.com/assets/2754821/12220379/089432d6-b725-11e5-9f74-e88259bed3fe.png)

**Comment by AkiraLaine** [comment]
Doing it now :smile:
