### ISSUE TITLE
Extra unnecessary space in one of the strings in the instructions

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6013]
Challenge [Waypoint: Concatenating Strings with the Plus Equals Operator](http://www.freecodecamp.com/challenges/waypoint-concatenating-strings-with-the-plus-equals-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr;



```

Extra unnecessary space in one of the strings in the instructions:

![image](https://cloud.githubusercontent.com/assets/2754821/12220428/2a35a32e-b726-11e5-9fce-39deb05f04bf.png)

**Comment by SaintPeter** [comment]
This is deliberate, because you need to remember to add spaces between things when you're concatenating.  There should be a `Note` in each of these concatenation challenges which speaks to that.

**Comment by erictleung** [comment]
Ah I guess I read the challenge too fast. This challenge does have a note about adding a space to the string. Thanks for pointing that out! I'll go ahead and close this.

**Comment by samthedog99** [comment]
Isn't it proper grammar to add TWO spaces after a period?  This answer only accepts one space.

**Comment by erictleung** [comment]
There's quite a debate on one-space versus two-space (http://www.writersdigest.com/online-editor/how-many-spaces-after-a-period). Up to others on whether they want to accept only one or also two spaces.

**Comment by ltegman** [comment]
One in most common in digital media and you can't even display two spaces in HTML without going to extra effort, so we will be sticking with one space.
