### ISSUE TITLE
Stand In Line

### ISSUE THREAD

**Issue by Maedel1915** [FreeCodeCamp/FreeCodeCamp#6024]
I'm thinking Stand In Line is poorly designed. I passed it, but only because the tests that do not use myArr (ie queue([], 1) and queue([2], 1)) just happen to have the same values as myArr where it matters. It is continuing to us myArr. I don't think this would be clear to Javascript learners. It makes it seem like it wants you to pass parameters by reference which is not a Javascript feature, and I believe many people would "pass" this checkpoint without understanding what's going on.

Just thought I'd let you know :-)

**Comment by SaintPeter** [comment]
We actually have a fix in staging for this, which changes the default code to look like this:
```js
function queue(arr, item) {
  // Your code here
  
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];
```

You're definitely not the ONLY one to be confused by this one.
