### ISSUE TITLE
Missing period in instructions

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6026]
Challenge [Waypoint: Storing Values with the Equal Operator](http://www.freecodecamp.com/challenges/waypoint-storing-values-with-the-equal-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var a;
var b = 2;

// Only change code below this line
a = 7;
b = a;

```

Missing period in first sentence of instructions.

![image](https://cloud.githubusercontent.com/assets/2754821/12223309/252299de-b788-11e5-9927-88bfbc8b1fa4.png)

**Comment by SaintPeter** [comment]
I eagerly await your PR.
