### ISSUE TITLE
Concatenating Strings with Plus Operator - Allow assignment after definition

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6028]
From [This Comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5898#issuecomment-170384568)

The second test is over-broad.  It forces you to do assignment on the same line as definition which is not a requirement of the challenge.

This should be valid code:
```js
var myStr;
myStr = "This is the start." + " This is the end.";
```

The test should be broken into two:
1)  See if the + operator has been used, between two strings, regardless of quote type
2)  Other checks to make sure it's assigned to `myStr`, with an appropriate error message, regardless of quote type.

Right now you can make errors not related to using a `+` that say you're not using `+`.

**Comment by 0x0936** [comment]
Great catch :+1:
