### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue 

### ISSUE THREAD

**Issue by chartman4** [FreeCodeCamp/freecodecamp#603]
Please tell us in detail here how we can make this challenge better.

This challenge accepted : <a href="http://catphotoapp.com"> cat photos >
as an answer.

**Comment by chartman4** [comment]
This is not what I wrote in the FreeCodeCamp bug dialog box, I have since fixed it but I believe it was 
"<a href='http://www.catphotoapp.com'>cat photos >" that it allowed.

**Comment by terakilobyte** [comment]
Thanks for the report. This issue has been raised before and addressed in a commit, so closing it.
