### ISSUE TITLE
Can't advance past Bonfire: Search and Replace

### ISSUE THREAD

**Issue by Owhyze1** [FreeCodeCamp/FreeCodeCamp#6036]
My code produces the correct answers for this bonfire, but it won't let me advance to the next bonfire. I'm not sure if this is the right place to ask for help in fixing this.

Challenge [Bonfire: Search and Replace](http://www.freecodecamp.com/challenges/bonfire-search-and-replace) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by sludge256** [comment]
Could you provide your code?

**Comment by Owhyze1** [comment]
function myReplace(str, before, after) {
  
  // substring located before the location of the second argument
  var firstHalf = [];
  
  // substring located after the location of the second argument
  var secondHalf = [];
  
  // final string with second argument replaced with third argument
  var replacement = []; 
  
  // all words in first argument 
  var words = str.split(" ");
  
  
  // search for second argument
  for (var w = 0; w < words.length; w++) {
    
    if (words[w] == before) {
      
      firstHalf = words.splice(0,w);
      
      secondHalf = words.splice(1);
    }
  }
    
  
  // check case of orginal word
  var letters = words.join("").split("");
  
  
  if (letters[0] == letters[0].toUpperCase()) {
    var afterLetters = after.split("");
    afterLetters[0] = afterLetters[0].toUpperCase();
    
    after = afterLetters.join("");    
  }

    
    
    replacement = firstHalf.join(" ") + " " + after + " " + secondHalf.join(" ");
  
 
  return replacement;
  

}

myReplace("Let us go to the store", "store", "mall");

**Comment by Owhyze1** [comment]
Oh nevermind. I figured it out. I added an extra space. Thanks anyway :)
