### ISSUE TITLE
Not sure waypoint should be advocating using "text-danger" class to make text red

### ISSUE THREAD

**Issue by twinbrookcoffee** [FreeCodeCamp/FreeCodeCamp#6037]
In [Waypoint: Use Spans for Inline Elements](http://www.freecodecamp.com/challenges/waypoint-use-spans-for-inline-element), the waypoint tells us to make a particular word red by applying the class `text-danger`. I'm not sure it's a good idea to do so as it encourages people to use whatever css class is at hand and ignore semantics.

**Comment by TravisHi** [comment]
PM @QuincyLarson with suggestions. I think the github issues are exclusively for bugs :)

**Comment by ltegman** [comment]
Github issues can be used to any suggested changes and are the appropriate way to handle something like this.

However, I don't see this as a problem. A lot of people's problem with bootstrap generally is that the classes are not semantic. I'll leave this open for discussion to get any other input, but I think this is just a reality of using bootstrap.

**Comment by TravisHi** [comment]
Thanks for clearing that up for me @ltegman :smile:

**Comment by SaintPeter** [comment]
I don't have an issue with using `text-danger`.  I use `btn-danger` all the time to get a red button.  You use what you have available.  I could see where this might get funky if you were using a customized/themed version of Bootstrap with different base colors and you expected `text-danger` to be red and it was not . . . but honestly, this is just a basic intro to Bootstrap.

**Comment by ltegman** [comment]
Closing this then. From what I've seen it is very common to use bootstrap classes for purely the color and not any particular semantic meaning. And this doesn't impact accessibility since classes are not read by screen readers. Thanks and happy coding!
