### ISSUE TITLE
Instruction missing from Challenge 39?

### ISSUE THREAD

**Issue by Pastshelfdate** [FreeCodeCamp/FreeCodeCamp#6038]
And you quoted the wrong part of my code.  My problem is that I followed your instructions and example to the letter.  The three check boxes functioned, and all the label test was displayed.  I didn't see where you said to enter a paragraph element as a heading, displaying "Personality."  It turned out that was the only thing missing from my code.

Once I got past the horrendous setup procedure that took me over an hour, the actual coding challenges have been a joy.  Generally you've all done a wonderful job.  But you don't seem to realize that some of the best coders are very careful to follow the directions exactly.  We try to think "How would a computer handle this?"  So if you leave something out, I don't try to second-guess you.  

That's why your setup Challenge text for one repeated button threw me off.  "Open in new tab ..." seemed to me to be instructions.  So I right-clicked the button, to open it in  a new browser tab, and lost way too much time trying to get the result to work.  The next step button was faded out, so I was stuck.

Challenge [Waypoint: Check Radio Buttons and Checkboxes by Default](http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.1000 Chrome/30.0.1599.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality"> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

```

**Comment by SaintPeter** [comment]
I feel like I've come in on the middle of a conversation . . . are you talking to someone?  Who is "you"?

I'm not sure what your specific concern with THIS waypoint is.  Is there something wrong with the instructions?  Please clarify.

Or did you mean to complain about the way the step challenges work?

**Comment by ltegman** [comment]
Closing as stale. Please open a new issue with further details if you are still experiencing a problem. Thanks and happy coding!
