### ISSUE TITLE
Feature: Badge system

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/FreeCodeCamp#604]
Not sure if this has been addressed before, but while doing the HTML/CSS challenges, it's kind of a long slog,e ven as someone who understood all the syntax & challenges.   A "breadcrumb" indicator (step 5 of 32 in HTML/CSS) would reduce clicking back to the map page that Terrakilobyte mentioned was happening...would provide a less distracting user experience. 

Also when moving continuously from the HTML section to the box model section, the cat app is suddenly dropped, then picked up again for the bootstrap section.  Again some sort of gamification or "share your cat app" special popup for twitter would be fun and motivating. 

It feels a little anticlimatic to finish the HTML/CSS then hit bootstrap and have another 16 to go. Some sort of ballons or animated woodsy animals would fit well at the transition. :) 

I hope these don't sound like complaints, rather user experience suggestions!

**Comment by AdventureBear** [comment]
along these lines...just finished the entire html/css section.   There should definately be some sort of pat on the back for completing the cat photo app!
ideas:
-pop up with congratulatory text and tweet link similar to bonfires
-save the code to a dynamic page in the users profile so they can share the link and see the photo app displayed (like the dash challenges)
-earn a badge
-text suggesting to take a break, here's a good coders stretch, tc.

**Comment by terakilobyte** [comment]
I like the suggest and badging is something we want to add, but it's going to be pretty far back in the list at the moment. As mentioned in some of your other suggestions, a PR would be great to see from an industrious camper ;) ;)

**Comment by onebree** [comment]
:+1:

**Comment by Kallaway** [comment]
I agree with this one, so far for me one of the biggest advantages of FCC was that it has checkboxes all over that lets me actually track my progress. I was pleasantly surprised by the fact that, similar to GitHub, daily activity gets mapped on a calendar. However, badges would make the progress even more enjoyable, especially when it comes to longer items of the overall progress map.

**Comment by onebree** [comment]
It would be good to receive a badge every time we complete a section of Waypoints or Bonfires. Like how Codecademy gives you a badge for completing an entire skill track.

**Comment by GJSmith3rd** [comment]
I made a request in number 913 for badges without knowledge of this feature request ticket. I'm specifically hoping for Open badges that can imported/exported and displayed outside of the FFC site like in a Mozilla BackPack.

**Comment by onebree** [comment]
@GJSmith3rd I tweeted FCC about Mozilla Open Badges a couple weeks ago. I think it would be great, especially on LinkedIn.

**Comment by tesla809** [comment]
Actually this is one of the best ideas out there. 

The purpose of FreeCodeCamp is to train people in web development and programming skills so that they can eventually find great jobs as a result. 

However, the biggest source of friction for this is the improper and outdated credentialing system that HR officers use to narrow potential candidates for a job. 

The idea of badges that are shown on twitter and especially Linkedin are great because they reduce the risk of hiring a free code camp member. Credentials from say a university are sort of a lazy filter system that HR people use to narrow candidates down for a position. But creating a list of badges where people are rigorously tested with new skills is by far more useful and can open the door to more opportunity.

This along with a portfolio of work, a blog, a github page, list of MOOC taken,  and perhaps more coding challenge like those on hacker rank provide a better description of a person than just a resume, cover letter and a college degree.

Perhaps a tool that can aggregate all of the online is necessary.

**Comment by santakmishra** [comment]
I think Mozilla Openbadges is the best way to go. A badge system would be really beneficial IMO. Has anyone done any work along these lines?

**Comment by BlackGuyCoding** [comment]
Is this feature request going to happen?

**Comment by atjonathan** [comment]
cc/ @FreeCodeCamp/issue-moderators 

Can someone open this as `help wanted` if we're gonna try and implement this! Just waiting for the signal @BlackGuyCoding ...

**Comment by BlackGuyCoding** [comment]
@atjonathan thanks.

How did you get the Free Code Camp member badge on your profile?

**Comment by atjonathan** [comment]
@BlackGuyCoding I'm a Core Team member @FreeCodeCamp, and therefore am a member of the organization.

**Comment by BlackGuyCoding** [comment]
Ahh I see. Ok cool.

**Comment by atjonathan** [comment]
@QuincyLarson @FreeCodeCamp/issue-moderators, what sort of badges do we want?

**Comment by R-2pa** [comment]
Some info for badge issuing platforms:
A currently list of badge issuing platforms can be found here: [Participating services](https://openbadges.org/about/participating-services). Many platforms offer integrations with other applications or open APIs for new integrations. Some platforms are also available as open source software for issuers who wish to customize their badging applications further or get involved directly in collaborating to advance the implementation of Open Badges.

A Open Source achievement recognition and tracking system [Badgr](https://info.badgr.io/).

**Comment by codemzy** [comment]
This is nothing official, no official badging system or anything... but just released my first open source project https://codemzy.github.io/codebadges/ for progress badges that can be displayed on portfolios etc. 😅
