### ISSUE TITLE
Recommended Hint

### ISSUE THREAD

**Issue by Philosophist** [FreeCodeCamp/FreeCodeCamp#6041]
Challenge [Zipline: Build a Wikipedia Viewer](http://www.freecodecamp.com/challenges/zipline-build-a-wikipedia-viewer) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi, I just wanted to recommend this resource as a hint for this challenge:
https://en.wikipedia.org/wiki/Special:ApiSandbox#action=query&titles=Main%20Page&prop=revisions&rvprop=content&format=jsonfm

**Comment by SaintPeter** [comment]
Sounds like a good idea.
