### ISSUE TITLE
Issue with running this module

### ISSUE THREAD

**Issue by jonexume** [FreeCodeCamp/FreeCodeCamp#6043]
I have come across an issue when trying to hit run on the below module.  It does nothing.  I have gone back and reset my internet settings, tested to make sure there is a connection and nothing improves.  Please advise.

Challenge [Waypoint: Fill in the Blank with Placeholder Text](http://www.freecodecamp.com/challenges/waypoint-fill-in-the-blank-with-placeholder-text#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3Ekitty%20ipsum%20text%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>kitty ipsum text</p>

```

**Comment by haih** [comment]
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by ltegman** [comment]
@jonexume Doe you see a failed test below the run test/reset/etc buttons on the left and text in the phone? If so this is expected behavior as nothing 'happens' when you run the tests if you haven't passed the challenge besides the tests updating their status if needed.

**Comment by jonexume** [comment]
Thank you everyone it is working now.  Thanks for the input.
