### ISSUE TITLE
Clicking Submit after successful solution redirects to a much earlier lesson

### ISSUE THREAD

**Issue by rmoffat** [FreeCodeCamp/FreeCodeCamp#6045]
Challenge [Waypoint: Use Comments to Clarify Code](http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I completed the Waypoint "Use Comments to Clarify Code," ran the code below, received a success message, clicked "Submit and go to next challenge" and was redirected to the Waypoint "Browse Camper News" at http://www.freecodecamp.com/challenges/waypoint-browse-camper-news 

My code:
```html
<!-- Only change code above this line -->
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by rmoffat** [comment]
Never mind - I did not realize I finished a section and was beginning a new section. The transition from the code editor to a page that looked like the Introduction pages confused me. The Submit after receiving a success message actually goes to the correct page.

**Comment by hallaathrad** [comment]
:+1:
