### ISSUE TITLE
Waypoint: Add Placeholder Text to a Text Field     ( bug in placeholder exercise)

### ISSUE THREAD

**Issue by KeaDC** [FreeCodeCamp/FreeCodeCamp#6046]
has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>

<input type="text">

<input type="text" placeholder="cat photo URL">

(the above line is reading as incorrect )
Name of exercise:  Waypoint: Add Placeholder Text to a Text Field


```

**Comment by sludge256** [comment]
You're supposed to add the placeholder text to the existing input not create a new input.

**Comment by JBuji** [comment]
I passd "Add Placeholder Text to a Text Field"
 challange puting TWO lines:

<input type="text" placeholder="cat photo URL">
<input type="text" placeholder="cat photo URL">

But it's strange.

**Comment by JBuji** [comment]
I passed "Add Placeholder Text to a Text Field"
challenge putting TWO lines:
`<input type="text" placeholder="cat photo URL">`
`<input type="text" placeholder="cat photo URL">`
But it's strange. /FCC bug/
Sorry I'm new on FCC & I've  lost this lines in my earlier Comment
