### ISSUE TITLE
the challenge should say greater than or equal to. u cant complete the challenge just putting a greater than operator

### ISSUE THREAD

**Issue by incognitonerd** [FreeCodeCamp/FreeCodeCamp#6048]
Challenge [Waypoint: Filter Arrays with filter](http://www.freecodecamp.com/challenges/waypoint-filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0Avar%20newArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AnewArray%20%3D%20oldArray.filter(function(val)%20%7B%0A%0A%20%20return%20val%20%3C%3D%205%3B%0A%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];
var newArray = [];

// Only change code below this line.

newArray = oldArray.filter(function(val) {

  return val <= 5;

});

```

**Comment by sludge256** [comment]
The challenge text seems correct to me. In your code you are returning values less than or equal to 5 which would remove values greater than 5.

If I'm missing something let me know.
