### ISSUE TITLE
Sentences missing periods in different Waypoints

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6051]
The following Waypoints have missing periods in sentences. All the missing periods are in places that are preceded by `<code>` tagged words. Sometimes, adding a period *might* confuse a learner if they see the period is too close to a special character (e.g. "`-->`."). Thoughts?

[Waypoint: Uncomment HTML](http://www.freecodecamp.com/challenges/waypoint-uncomment-html)

![image](https://cloud.githubusercontent.com/assets/2754821/12229247/99c92e20-b7fa-11e5-9763-176e68487f04.png)

[Waypoint: Comment out HTML](http://www.freecodecamp.com/challenges/waypoint-comment-out-html)

![image](https://cloud.githubusercontent.com/assets/2754821/12229257/aa258a02-b7fa-11e5-9e62-42472d94f747.png)

[Waypoint: Specify How Fonts Should Degrade](http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade)

![image](https://cloud.githubusercontent.com/assets/2754821/12229469/e28eeb66-b7fc-11e5-982a-9ce38b969784.png)

[Waypoint: Add Borders Around Your Elements](http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements)

![image](https://cloud.githubusercontent.com/assets/2754821/12229533/a08e6bf0-b7fd-11e5-8ea0-5ea2b5d5a1b6.png)

[Waypoint: Use HTML5 to Require a Field](http://www.freecodecamp.com/challenges/waypoint-use-html5-to-require-a-field)

![image](https://cloud.githubusercontent.com/assets/2754821/12229633/8b60576a-b7fe-11e5-9854-aa10c7538fbf.png)

[Waypoint: Create a Set of Radio Buttons](http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons)

![image](https://cloud.githubusercontent.com/assets/2754821/12229664/c637c382-b7fe-11e5-81c9-16bcdd43f12e.png)

[Waypoint: Create a Set of Checkboxes](http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes)

![image](https://cloud.githubusercontent.com/assets/2754821/12229772/a65e5304-b7ff-11e5-823d-ebceb1f2c08c.png)

[Waypoint: Inherit Styles from the Body Element](http://www.freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element)

![image](https://cloud.githubusercontent.com/assets/2754821/12229985/ac6b4fb6-b801-11e5-8df8-3828daf90e3d.png)

[Waypoint: Override All Other Styles by using Important](http://www.freecodecamp.com/challenges/waypoint-override-all-other-styles-by-using-important)

![image](https://cloud.githubusercontent.com/assets/2754821/12230018/ff1b2cb8-b801-11e5-8b4c-8d053298fd49.png)

[Waypoint: Use Hex Code to Color Elements White](http://www.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-white)

![image](https://cloud.githubusercontent.com/assets/2754821/12230034/243be79e-b802-11e5-95be-a5e4d7e3a607.png)

And almost all HTML 5 and CSS Waypoints about hex codes and RGB values (54 -- 68).

**Comment by bugron** [comment]
@erictleung thanks for posting this issue!
I think this is done on purpose. We had lots of issues opened by campers who just copy-pasted a code from the description with a trailing period and then they didn't realize why they were failing tests. I agree with you, there must be periods but let's left things as they are, thanks. Closing.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
