### ISSUE TITLE
bug in bonfire-smallest-common-multiple

### ISSUE THREAD

**Issue by velmuruganvelayutham** [FreeCodeCamp/FreeCodeCamp#6054]
Challenge [Bonfire: Smallest Common Multiple](http://www.freecodecamp.com/challenges/bonfire-smallest-common-multiple#?solution=function%20smallestCommons(arr)%20%7B%0A%0A%20%20%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%20%20%20%20var%20n%20%3D%201%3B%0A%20%20%20%20var%20found%20%3D%20false%3B%0A%20%20%20%20%2F%2Fswap%20elements%20if%20first%20element%20is%20smaller%20than%20second%0A%20%20%20%20if%20(arr%5B0%5D%20%3E%20arr%5B1%5D)%20%7B%0A%20%20%20%20%20%20%20%20var%20temp%20%3D%20arr%5B0%5D%3B%0A%20%20%20%20%20%20%20%20arr%5B0%5D%20%3D%20arr%5B1%5D%3B%0A%20%20%20%20%20%20%20%20arr%5B1%5D%20%3D%20temp%3B%0A%20%20%20%20%7D%0A%20%20%20%20%2F%2Ffind%20out%20all%20the%20numbers%20between%20the%20given%20arguments%0A%20%20%20%20for%20(var%20i%20%3D%20arr%5B0%5D%3B%20i%20%3C%3D%20arr%5B1%5D%3B%20i%2B%2B)%20%7B%0A%0A%20%20%20%20%20%20%20%20newArr.push(i)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20%2F%2Ffind%20out%20the%20smallest%20common%20multiple%0A%20%20%20%20while%20(!found)%20%7B%0A%20%20%20%20%20%20%20%20n%2B%2B%3B%0A%20%20%20%20%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20newArr.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(n%20%25%20newArr%5Bj%5D%20!%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20found%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(n%20%2B%20%22%20is%20%22%20%2B%20found)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20found%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20n%3B%0A%7D%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function smallestCommons(arr) {

    var newArr = [];
    var n = 1;
    var found = false;
    //swap elements if first element is smaller than second
    if (arr[0] > arr[1]) {
        var temp = arr[0];
        arr[0] = arr[1];
        arr[1] = temp;
    }
    //find out all the numbers between the given arguments
    for (var i = arr[0]; i <= arr[1]; i++) {

        newArr.push(i);
    }

    //find out the smallest common multiple
    while (!found) {
        n++;
        for (var j = 0; j < newArr.length; j++) {
            if (n % newArr[j] !== 0) {
                found = false;
                console.log(n + " is " + found);
                break;
            } else {
                found = true;
            }
        }
    }
    return n;
}

smallestCommons([1,5]);

```

**Comment by bugron** [comment]
@velmuruganvelayutham thanks for posting this issue!
Please, provide the description of your issue, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by velmuruganvelayutham** [comment]
final test case is getting failed even after my solution is correct.. 
![Uploading error-challenge.PNG…]()

**Comment by ltegman** [comment]
@velmuruganvelayutham Your code is too slow and is getting flagged by our infinite loop detector. You can either try coming up with a more efficient solution or put `// noprotect` in your code to submit as is (just be prepared for the page to lock for about 10 seconds after you submit your code). Thanks and happy coding!

**Comment by velmuruganvelayutham** [comment]
thanks @ltegman . It works fine..
