### ISSUE TITLE
undefined with double quotation marks couldn't pass the Challenge Waypoint: Return Early Pattern for Functions

### ISSUE THREAD

**Issue by williamwang2016** [FreeCodeCamp/FreeCodeCamp#6056]
Challenge [Waypoint: Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/waypoint-return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(a%20%3C%200%20%7C%7C%20b%20%3C%200)%20%7B%0A%20%20%20%20return%20undefined%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if (a < 0 || b < 0) {
    return "undefined";
  }
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

```

**Comment by bugron** [comment]
@williamwang2016 thanks for posting this issue!
I've just passed the challenge with your code. Can you. please, post a screenshot of the issue?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
