### ISSUE TITLE
Bonfire: Arguments Optional - Task needs to be explained better

### ISSUE THREAD

**Issue by LisaBlore** [FreeCodeCamp/FreeCodeCamp#6059]
This is so hard to understand if you are new to programming. I was not sure if the problem could have been stated more clearly or if I just didn't understand the problem because I didn't know anything about closures before starting it. It would be really helpful if there were some waypoints to help explain this first. Also, if you look in the Wiki help files, knowing HINT 3 is critical. Therefore, it should be stated right in the Bonfire.

Challenge [Bonfire: Arguments Optional](http://www.freecodecamp.com/challenges/bonfire-arguments-optional) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function add() {
  return false;
}

add(2,3);

```

**Comment by hallaathrad** [comment]
Unless I'm entirely misreading the instructions, what this exercise requires from the camper is to curry things up a little. Come to think about it, I can't remember seeing the term mentioned anywhere before this point (and it is in fact not even described as such in these instructions).

@LisaBlore I'm sure you've already studied the subject, if only by need as you seem to have done, but just in case and to help you let the subject sink in, [check this article out](https://medium.com/@kbrainwave/currying-in-javascript-ce6da2d324fe#.6wh2ubjmo).
It helped me get things done and understood when I first approached the topic.


Maybe we can add that and other articles to the references? [This one](http://www.sitepoint.com/currying-in-functional-javascript/) has more of a "for beginners" feel to it.

**Comment by raisedadead** [comment]
@LisaBlore  an article has been added on the wiki [about currying here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Currying).
