### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-practice-functional-programming has an issue 

### ISSUE THREAD

**Issue by levyian** [FreeCodeCamp/freecodecamp#606]
The video in the challenge doesn't match the challenge.
Challenge - functional programming
Video - learning javascript on codeacademy.

**Comment by terakilobyte** [comment]
@quincylarson Could you find the right video code for this?

**Comment by levyian** [comment]
Hi Quincy,


The video showed was for the code-academy JS track. I just checked and it still remains so. I was able to start the challenge and am about half way through. Just wanted to let you guys know in case others might find it confusing and get stuck.






Thanks,
George.





From: Nathan
Sent: ‎Wednesday‎, ‎May‎ ‎27‎, ‎2015 ‎9‎:‎15‎ ‎AM
To: FreeCodeCamp/freecodecamp
Cc: George Levy





@quincylarson Could you find the right video code for this?

**Comment by QuincyLarson** [comment]
@levyian Thank you for catching this! I will add the correct video tonight.
