### ISSUE TITLE
Waypoint: Assignment with a Returned Value - Improve Example Code

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6062]
Challenge [Waypoint: Assignment with a Returned Value](http://www.freecodecamp.com/challenges/waypoint-assignment-with-a-returned-value) has an issue.

The example is confusing because it calls for a `var`, which is not needed in the solution:
`var ourSum = sum(5, 12);`
Should change to:
`ourSum = sum(5, 12);`

**Comment by ammpereira** [comment]
Yes, indeed it has an issue.

Here is my code with no javascript errors on console of the browser:
// Setup
var processed = 0;

function process(num) {
  return (num + 3) / 5;
}

// Only change code below this line
var processed = 2;

function process(num) {
  return (num + 3) / 5;
}
  console.log('test');

**Comment by ammpereira** [comment]
I forgot the number 7, but it remains the same :/

**Comment by n2diy** [comment]
Shouldn't you remove var from the example code too? This just killed me for four hours.

**Comment by SaintPeter** [comment]
The `var` is required there.  We have to define the variable.

Possibly we could change the order of things and make an actual example.  That seems reasonable.

**Comment by JoleDev** [comment]
![code screen print](https://cloud.githubusercontent.com/assets/9546456/14339818/38512154-fc9f-11e5-9e59-95d52bcadc48.jpg)

What is the wrong with this code, I have done the exact same thing as explained in the example. I tried this three months before but couldn't solved it, and i again came back after three months, still could not  resolve the same.

**Comment by erictleung** [comment]
@JoleDev there shouldn't be a space after `processArg`.

**Comment by PlinySoun** [comment]
No luck.. eventhough I dont have the space behind.. bug?

**Comment by bugron** [comment]
@PlinySoun our tests are looking for `processArg` not `processArc`.

**Comment by kgashok** [comment]
TIL JS is _so_ sensitive to spaces!

**Comment by ParanoidWizard66** [comment]
If anyone still needs help the code you input is processed = processArg(7);

**Comment by llabrie** [comment]
THANK YOU!!

**Comment by 0b4cL** [comment]
Why does processed = processArg(7); work? Why does it equal 7?

**Comment by fcanmekikoglu** [comment]
`
// Example
var changed = 0;

function change(num) {
  return (num + 5) / 3;
}

changed = change(10);

// Setup
var processed = 0;

function processArg(num) {
  return (num + 3) / 5;
}

// Only change code below this line
var processed = 2;

function processArg(a){
  return (a-5); 
}

processed=processArg(7);




`

**Comment by sanosempati** [comment]
THANK  YOU ALL 👍

**Comment by OgunniyiOwamamwen** [comment]
// Only change code below this line
var processed = 2;

function processArg(num) {

return (num * 1 ) / 3.5;
}
processed = processArg(7);
