### ISSUE TITLE
Undefined Variables in the instructions

### ISSUE THREAD

**Issue by OriBon** [FreeCodeCamp/FreeCodeCamp#6066]
Challenge [Waypoint: Logical Order in If Else Statements](http://www.freecodecamp.com/challenges/waypoint-logical-order-in-if-else-statements#?solution=function%20myTest(val)%20%7B%0A%20%20if(val%20%3C%205)%20%7B%0A%20%20%20%20return%20%22Less%20than%205%22%3B%0A%20%20%7D%20else%20if(val%20%3C%2010)%20%7B%0A%20%20%20%20return%20%22Less%20than%2010%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Greater%20than%20or%20equal%20to%2010%22%3B%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(7)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![screenshot from 2016-01-11 16 04 12](https://cloud.githubusercontent.com/assets/10662057/12246658/aea46fe8-b87d-11e5-83e8-308477a0d92b.png)

`num` would be an undefined variable in these instructions.
I believe it should instead say `else if (x < 2)` for the first set of instructions, and `else if (x < 1)` for the second set of instructions.

**Comment by greglose** [comment]
Hello - I would like to learn how to add to the project and this seems like an easy item. I'm up for fixing it. Tx

**Comment by SaintPeter** [comment]
@greglose 
* [How To Fork And Maintain a Local Instance of Free Code Camp · FreeCodeCamp/FreeCodeCamp Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Fork-And-Maintain-a-Local-Instance-of-Free-Code-Camp) 
* [How To Create A Pull Request for Free Code Camp · FreeCodeCamp/FreeCodeCamp Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Create-A-Pull-Request-for-Free-Code-Camp)

Support here:
[HelpContributors Chat Room](https://gitter.im/FreeCodeCamp/HelpContributors)

**Comment by raisedadead** [comment]
Hi @greglose !

I just made the changes, but you can go ahead and try this, I will not create a PR.
Follow the instructions @SaintPeter mentions

Goodluck! :smiley:

**Comment by greglose** [comment]
Oh that's ok - I'll pick another. Tx

On Mon, Jan 11, 2016 at 2:43 PM, Mrugesh Mohapatra <notifications@github.com
> wrote:

> Hi @greglose <https://github.com/greglose> !
>
> I just made the changes, but you can go ahead and try this, I will not
> create a PR.
> Follow the instructions @SaintPeter <https://github.com/SaintPeter>
> mentions
>
> Goodluck! [image: :smiley:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6066#issuecomment-170699611>
> .
>



-- 

Greg Lose
