### ISSUE TITLE
Waypoint: Logical Order in If Else Statements

### ISSUE THREAD

**Issue by renelis** [FreeCodeCamp/FreeCodeCamp#6067]
Challenge [Waypoint: Logical Order in If Else Statements](http://www.freecodecamp.com/challenges/waypoint-logical-order-in-if-else-statements#?solution=function%20myTest(val)%20%7B%0A%20%20if(val%20%3C%2010)%20%7B%0A%20%20%20%20return%20%22Less%20than%2010%22%3B%0A%20%20%7D%20else%20if(val%20%3C%205)%20%7B%0A%20%20%20%20return%20%22Less%20than%205%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Greater%20than%20or%20equal%20to%2010%22%3B%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(4)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  if(val < 10) {
    return "Less than 10";
  } else if(val < 5) {
    return "Less than 5";
  } else {
    return "Greater than or equal to 10";
  }
}
             
// Change this value to test
myTest(4);

```

the `myTest(5) should return "Less than 5"` point won't work... I believe my code is fine

**Comment by SaintPeter** [comment]
You have precisely underscored the reason for this waypoint:
Imagine for a moment that your val === 4.

```
If ( 4 < 10 ) {
   return "Less than 10";
}
```
Because 4 is always less than 10, it will not ever get to the next statement, `val < 5`.

Was this not clear from the instructions?  This is a new waypoint.

**Comment by renelis** [comment]
Thanks

**Comment by SaintPeter** [comment]
Closing as not an issue.

**Comment by Preeetrockz** [comment]
you just need to rearrange the code !! i got this :)

**Comment by texas2010** [comment]
@Preeetrockz 
Please do not post your solution on here. This GitHub Issues are for reporting bugs on the website only.

Happy Coding!
