### ISSUE TITLE
I'm sure I got the code to turning an image to a link, but it's not recognizing it

### ISSUE THREAD

**Issue by dustylover** [FreeCodeCamp/FreeCodeCamp#6068]
According to the instructions, I think I have this one right, but it's not being recognized and allowing me to move forward to the next lesson. Please help.

This is what showed up on the lesson: <a href="#"><img src="http://bit.ly/fcc-running-cats"></a>

The picture shows up fine in my window, but I cannot get it recognized and move on to the next lesson. I think there is a bug somewhere.

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p><a href="#"><img src="http://bit.ly/fcc-running-cats"></a></p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by sludge256** [comment]
Do you mind posting the code between back-ticks?
Like so:
```
code here
```
Also, please provide the name of the exercise.
