### ISSUE TITLE
Waypoint: Use Conditional Logic with If Statements

### ISSUE THREAD

**Issue by Raulerson** [FreeCodeCamp/FreeCodeCamp#6070]
My answer returns correct but the test doesn't complete. is my coding bunk or is this a legit bug?

![image](https://cloud.githubusercontent.com/assets/16291684/12248335/aad50b08-b886-11e5-9a31-eca7e61b1368.png)

**Comment by sludge256** [comment]
The casing of your return strings is important.

**Comment by ashrafmscs** [comment]
"Yes"   Y must be capital
