### ISSUE TITLE
Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by GilbertoCS** [FreeCodeCamp/FreeCodeCamp#6072]
Challenge [/challenges/waypoint-target-the-parent-of-an-element-using-jquery](http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

![bug1](https://cloud.githubusercontent.com/assets/2317290/12250946/f917d194-b8b1-11e5-9325-47dce714db80.jpg)

My code:

```
undefined

```

**Comment by SaintPeter** [comment]
Please try refreshing the page.  If that doesn't work, try pressing the "Reset" button.  Also, check your dev console for errors.

**Comment by GilbertoCS** [comment]
I try that.
The error on console is
 waypoint-target-the-parent-of-an-element-using-jquery:30 Uncaught SyntaxError: Unexpected token ILLEGAL

**Comment by SaintPeter** [comment]
It looks like the page is corrupt in some way.

Press F12 to open the dev console.  Press and hold your mouse on the normal refresh button until a menu pops up.  Choose "Empty Cache and Hard Reload".  See if that helps at all.

**Comment by GilbertoCS** [comment]
Nope, I tried that too and the result was the same. But I think that the problem is some code injection from an extension on the browser.

**Comment by ltegman** [comment]
Closing this is not an issue with the site. Thanks and happy coding!
