### ISSUE TITLE
Waypoint: Logical Order in If Else Statements - Small Mistake in the Tests Explanation?

### ISSUE THREAD

**Issue by amenshamen** [FreeCodeCamp/FreeCodeCamp#6073]
Challenge [Waypoint: Logical Order in If Else Statements](http://www.freecodecamp.com/challenges/waypoint-logical-order-in-if-else-statements#?solution=function%20myTest(val)%20%7B%0A%20%20if(val%20%3C%205)%20%7B%0A%20%20%20%20return%20%22Less%20than%205%22%3B%0A%20%20%7D%20else%20if(val%20%3C%2010)%20%7B%0A%20%20%20%20return%20%22Less%20than%2010%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Greater%20than%20or%20equal%20to%2010%20test%22%3B%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(7)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.

My code:
```javascript
function myTest(val) {
  if(val < 5) {
    return "Less than 5";
  } else if(val < 10) {
    return "Less than 10";
  } else {
    return "Greater than or equal to 10";
  }
}
             
// Change this value to test
myTest(7);
```

It is only a minor mistake but the first Test being done to check the code says `>myTest(5) should return "Less than 5"` - Im pretty sure it should say `>myTest(4) should return "Less than 5"` tho since 5 isnt less than 5. This seems to be only a mistake in this Text and not in the test itself since the correct code is accepted.

**Comment by marcusparsons** [comment]
I thoroughly agree with you, amenshamen.  The logic here isn't right.  It should be a number smaller than 5 in the test case in order for the logic to make sense because 5 is not less than 5.

**Comment by cybot1711** [comment]
Agreed.

**Comment by mihai54321** [comment]
Agreed.

**Comment by DiegoRBaquero** [comment]
Was about to make and issue too. Agreed +1

**Comment by 4mifix** [comment]
I have the same code that you have and it's not working. Something is amiss!

**Comment by Smorano1224** [comment]
Agreed.  Was about to report the bug.

**Comment by redeyesblackdragon** [comment]
agree

**Comment by OsvaldoGlez** [comment]
SOLUTION : 
function orderMyLogic(val) {
  if (val > 5 && val < 10) {
    return "Less than 10";
  } else if (val > 1 && val < 5) {
    return "Less than 5";
  } else {
    return "Greater than or equal to 10";
  }
}

// Change this value to test
orderMyLogic(4);

**Comment by jasdeep92** [comment]
SOLUTION :
function orderMyLogic(val) {
if (val > 5 && val < 10) {
return "Less than 10";
} else if (val > 1 && val < 5) {
return "Less than 5";
} else {
return "Greater than or equal to 10"; 
}
}
THERE SHOULD BE SOME CORRECTION.... IN FIRST IF STATEMENT IF WE PUT VAL >=5....IT WILL BE MORE LOGICAL BECAUSE IF WE DONT PUT >= INSTEAD PUT ONLY > ...THEN WHILE INVOKING THE FUNCTION...IF WE GIVE ARGUMENT AS 5 THEN IT WILL RETURN GREATER THAN OR EQUAL TO 10....
JUST A THOUGHT.....WHAT YOU SAY

**Comment by texas2010** [comment]
@jasdeep92 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by misterds** [comment]
why  in the  free code  camp  this  code is not  work ning 
function myTest(val) {
  if(val < 5) {
    return "Less than 5";
  } else if(val < 10) {
    return "Less than 10";
  } else {
    return "Greater than or equal to 10";
  }
}

// Change this value to test
myTest(4);

 i teste  in the  console  and is  working , admin   can you fix  please

**Comment by joshuaeyenike** [comment]
thanks @misterds for helping me solve the problem.

**Comment by nazmulhooque** [comment]
Answer
function orderMyLogic(val) {
  if (val < 5) {
    return "Less than 5";
  } else if (val < 10) {
    return "Less than 10";
  } else {
    return "Greater than or equal to 10";
  }
}

orderMyLogic(7); // Less than 10

**Comment by nazmulhooque** [comment]
Mr. @misterds 
Please use this code

function orderMyLogic(val) {
  if (val < 5) {
    return "Less than 5";
  } else if (val < 10) {
    return "Less than 10";
  } else {
    return "Greater than or equal to 10";
  }
}

orderMyLogic(7); // Less than 10
