### ISSUE TITLE
Tests for correct submissions shouldn't console.log()

### ISSUE THREAD

**Issue by matty22** [FreeCodeCamp/FreeCodeCamp#6076]
Recently, there's been a change to how the tests work or I am losing my mind. I don't remember in the basic bonfires section there being all of these console.logs automatically generated when I hit the Run Tests button to test code I'd written. Now that I'm in intermediate bonfires using console.log() to debug or watch for changes happening in real time, for example, putting a console.log() before and after an if or loop to see how things have changed, is much harder because all of the tests for each required case console.log on each submit.

For example, here is the web console for Diff Two Arrays. I currently have just one console.log() in the code:

![2016-01-11_2031](https://cloud.githubusercontent.com/assets/7202935/12254868/5edf7e2e-b8a2-11e5-8b27-efeb5ad86340.png)

Not sure if this is a bug or intended, but it makes the console harder to use to solve each test case rather than easier because it unintuitively does things behind the scenes that I did not direct it to in my code.

**Comment by ltegman** [comment]
This is expected. If your code has a `console.log` it will execute that once for every time the code is run (or once for every test). In the specific case you are running into you may find a vast majority of these to be noise, but in the future or someone else doing this same bonfire may want to see every tests `console.log`. There is no programatic way to determine which `console.log` for which test will actually be helpful to the user, so there's really no option but to display them all.

Thanks and happy coding!
