### ISSUE TITLE
Checkpoint: Record Collection

### ISSUE THREAD

**Issue by Hemalatah** [FreeCodeCamp/FreeCodeCamp#6079]
Challenge [Checkpoint: Record Collection](http://www.freecodecamp.com/challenges/checkpoint-record-collection) has an issue.
Considering secong condition of update function,
'value' is not pushed in to the array of prop, it saved as string instead.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
  //collection[i];
  if (value !== "" && collection[id][prop] !== "tracks") {
    collection[id][prop] = value;
  } else if (value !== "" && collection[id][prop] === "tracks") {
    collection[id][prop].push(value);
  } else if (value === "") {
    delete collection[id][prop];
  }
  return collection;


}

// Alter values below to test your code
update(1245, "tracks", "Addicted to Love");


```

**Comment by SaintPeter** [comment]
You need to test `prop` to see if it is equal to "tracks".  Right now you're testing then CONTENT of whatever `collection[id][prop]` is pointing to, which will never be "tracks".

In the future you should ask for help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link).  Issues are for bugs with the site.

Thanks and Happy Coding!

**Comment by Hemalatah** [comment]
Thanks!! Got it!
