### ISSUE TITLE
A minor update could be done http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-button 

### ISSUE THREAD

**Issue by ShaklinSyed** [FreeCodeCamp/freecodecamp#608]
The description of the waypoint asks to create a button with class of "btn" and with value of "like this photo". But as soon as we give a class name of "btn" the waypoint gets completed. it doesnt check if we have added value for the button.

**Comment by terakilobyte** [comment]
Thanks, fixed in a commit!
