### ISSUE TITLE
Fibonacci Bonfire locks up browser

### ISSUE THREAD

**Issue by MarysTurtle** [FreeCodeCamp/FreeCodeCamp#6084]
Challenge [Bonfire: Sum All Odd Fibonacci Numbers](http://www.freecodecamp.com/challenges/bonfire-sum-all-odd-fibonacci-numbers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
This error occurs in Firefox, Edge, and Chrome.  I have had other members of FCC attempt the same code with the same results.  The code below will work in other forums, including other Bonfire pages, proving that the code is valid.  

My code:
```javascript
function sumFibs(num) {
  var myArr = [1, 1];
  for (var i = 2; i < 5; i++) {
    myArr.push(myArr[i-2] + myArr[i-1]);
  } //end for
  return myArr;
  
}

sumFibs(4);
```

**Comment by bugron** [comment]
@MarysTurtle thanks for posting this issue!
Are there any errors in your browser's console?
Your code isn't blocking my browser. I don't know if this will help but you can try to add `// noprotect` comment to your code to disable the loop protection.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ltegman** [comment]
I have a feeling that at some point your for loop said `(var i = 2; i < num; i++)`. If that was the case your code would run extremely slowly for the `4000000` test case since you would be making a 4 million item array.

As your code stands now this problem can not be reproed, so I am closing this. Thanks and happy coding!

**Comment by MarysTurtle** [comment]
@ltegman Yes, you are correct that it said (var i = 2; i < num; i++).  Why would that have created such a large array?  I used repl.it to insert the exact same code and it works fine.  The variable num is equal to the value 4, so shouldn't it produce the same result as if the value 4 was in its spot?

**Comment by ltegman** [comment]
@MarysTurtle When you are running that code in Free Code Camp it is running all the test cases, one of which is 4 million. If you ran that same code on repl.it with 4 million you'll run into the same problem.

**Comment by MarysTurtle** [comment]
@ltegman That makes sense.  I didn't even think about it that way.  I will find another solution.  Thanks for the help.  Sorry for resorting to 'report a bug', but that's what was suggested to me in the chat rooms.  Thanks again!

**Comment by ltegman** [comment]
Not a problem! Good luck!
