### ISSUE TITLE
Random Error In Curriculum 

### ISSUE THREAD

**Issue by genesisjoec** [FreeCodeCamp/FreeCodeCamp#6085]
![fcc error](https://cloud.githubusercontent.com/assets/11507581/12266455/d58f09fc-b908-11e5-97aa-cc829bff52e5.JPG)
Challenge [Waypoint: Modify Array Data With Indexes](http://www.freecodecamp.com/challenges/waypoint-modify-array-data-with-indexes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.



```

**Comment by bugron** [comment]
@genesisjoec thanks for posting this issue!
Are there any errors in your browser's console? Are you behind any proxy or anonymizing software?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by genesisjoec** [comment]
No to all of your inquiries. It did not effect the functionality of the challenge. I've progressed passed it already.

**Comment by bugron** [comment]
Have you tried to post this in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter)? Does anyone else experience a similar situation? Because it is very hard to investigate such a user specific thing. That could be, for example, a bad connection.

**Comment by genesisjoec** [comment]
I did not post it in Gitter.

**Comment by ltegman** [comment]
This looks like a connection issue on your end. Without any error logs or an ability to repro the problem on your end there's really no way we can help. Sorry about that!
