### ISSUE TITLE
Unable to complete Waypoint

### ISSUE THREAD

**Issue by edwintcloud** [FreeCodeCamp/FreeCodeCamp#6087]
Challenge [Waypoint: Local Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-local-scope-and-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 'use strict';
  
  
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);

// now remove the console log line to pass the test


```

**Comment by alistermada** [comment]
@edwintcloud You need to remove the console log line outside of myFunction(), as it says in the commented code.

**Comment by ltegman** [comment]
Closing as not an issue.
