### ISSUE TITLE
Bonfire: Symmetric Difference test as shown is incorrect

### ISSUE THREAD

**Issue by BoDonkey** [FreeCodeCamp/FreeCodeCamp#6088]
![image](https://cloud.githubusercontent.com/assets/13168224/12271254/2add4850-b928-11e5-9b7f-985a94e388fa.png)
I have completed this challenge successfully and my implementation comes back with the answer [1, 2, 4, 5, 6, 7, 8, 9]. When I run the tests this passes. The third set of numbers contains a 4 and since no other set contains a 4, this should be in the final returned symmetric difference. 

Again to reiterate, it is just the list of expected results that is incorrect, not the actual tests that are being run.

**Comment by ltegman** [comment]
Whoops, looks like I typoed this one. Good catch!

**Comment by divisionparzero** [comment]
got a solution that worked.  just add:

.reduce(function(a,b){
    if (a.indexOf(b) < 0 ) a.push(b);
    return a;
  },[]);

to the end of the last return statement and it works.
