### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue 

### ISSUE THREAD

**Issue by JasonGoldstein2** [FreeCodeCamp/freecodecamp#609]
the lessons says:

Your image should have a border with a width of 10 pixels.

I entered 'border-width: 10px;' in CSS and its not working.

**Comment by ShaklinSyed** [comment]
I did go through that lesson and i am pretty sure it works fine. if possible could u please add the complete code or a screenshot of the issue.

**Comment by JasonGoldstein2** [comment]
I went back and re-did it, seems to act fine now.   thanks!

**Comment by gigantor84** [comment]
I'm having a similar issue. My code seems right but I still get a red X on the border width.
![border](https://cloud.githubusercontent.com/assets/12537002/7829225/eebbc520-03f3-11e5-934a-1688dacf23f9.jpg)

**Comment by terakilobyte** [comment]
Great, thanks for the updated report. Closing the issue since it's working now.
