### ISSUE TITLE
Error with test case 

### ISSUE THREAD

**Issue by hellspawn14** [FreeCodeCamp/FreeCodeCamp#6091]
Challenge [Bonfire: Where do I belong](http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong#?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20arr%20%3D%20arr.sort(function%20(a%2C%20b)%7B%0A%20%20%20%20%20%20return%20a%20-%20b%3B%0A%20%20%20%20%7D)%3B%0A%20%20%0A%20%20var%20minAbsDist%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%0A%20%20%7B%0A%20%20%20%20minAbsDist.push(%5BMath.abs(arr%5Bi%5D%20-%20num)%2C%20i%5D)%3B%0A%20%20%7D%0A%20%20%0A%20%20var%20min%20%3D%20%20minAbsDist%5B0%5D%5B0%5D%3B%20%0A%20%20var%20index%20%3D%200%3B%0A%20%20%2F%2F%20noprotect%0A%20%20for%20(var%20k%20%3D%200%3B%20k%20%3C%20minAbsDist.length%3B%20k%2B%2B)%0A%20%20%7B%0A%20%20%20%20%2F%2F%2Fwindow.alert(%22%5B%22%20%2B%20minAbsDist%5Bk%5D%5B0%5D%20%2B%20%22%2C%20%22%20%2B%20minAbsDist%5Bk%5D%5B1%5D%20%2B%20%22%5D%22)%3B%0A%20%20%20%20if%20(minAbsDist%5Bk%5D%5B0%5D%20%3C%3D%20min)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20min%20%3D%20minAbsDist%5Bk%5D%5B0%5D%3B%0A%20%20%20%20%20%20index%20%3D%20minAbsDist%5Bk%5D%5B1%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20if%20(arr%5B0%5D%20%3D%3D%3D%202)%0A%20%20%7B%0A%20%20%20%20if(arr%5B1%5D%20%3D%3D%3D%205)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if(arr%5B2%5D%20%3D%3D%3D%2010)%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20index%20%2B%3D%201%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20%2F%2Fwindow.alert(index)%3B%0A%20%20return%20index%3B%0A%7D%0A%0Awhere(%5B10%2C%2020%2C%2030%2C%2040%2C%2050%5D%2C%2035)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

There's an error with the last test in this challenge because array length is 3 (meaning the array has 3 elements) but the success test case points that the right answer is 3. 

where([2, 5, 10], 15) should return 3.

When the case correct case scenario should be from 0 to 2 considering the 0 element. 

Please change the test scenario to make it work, Thanks.

My code:
```javascript
function where(arr, num) {
  arr = arr.sort(function (a, b){
      return a - b;
    });
  
  var minAbsDist = [];
  for (var i = 0; i < arr.length; i++)
  {
    minAbsDist.push([Math.abs(arr[i] - num), i]);
  }
  
  var min =  minAbsDist[0][0]; 
  var index = 0;
  for (var k = 0; k < minAbsDist.length; k++)
  {
   
    if (minAbsDist[k][0] <= min)
    {
      min = minAbsDist[k][0];
      index = minAbsDist[k][1];
    }
  }
  

  // Find my place in this sorted array.
  //window.alert(index);
  return index;
}

where([10, 20, 30, 40, 50], 35);

```

**Comment by ltegman** [comment]
If you were adding `15` onto an array of `[2, 5, 10]` you would need to add it onto the end, which would be index `3`, so this test is correct. Thanks and happy coding!

**Comment by hellspawn14** [comment]
The goal of the challenge wasn't to add a number, it the goal was and i quote : " Return the lowest index at which a value (second argument) should be inserted into an array (first argument) once it has been sorted. "

**Comment by ltegman** [comment]
It doesn't say you'd remove any elements from the array, which means the insertion point would have to be index `3`, since there's smaller numbers occupying indexes `0`, `1`, and `2`. If you inserted a index `2` it would displace number `10` into index `3` and they would be out of order.
