### ISSUE TITLE
Waypoints: Assignment with Plus Equals & with Minus Equals - 

### ISSUE THREAD

**Issue by Davidslc** [FreeCodeCamp/FreeCodeCamp#6092]
In the results area, the variable C shows up as a string (c = '19') instead of an integer.  

<img width="256" alt="screen shot of issue" src="https://cloud.githubusercontent.com/assets/10160841/12277650/b874c0d8-b939-11e5-9e65-ddfb0af59f02.png">

**Comment by ltegman** [comment]
The only variable in `Waypoint: Finding a Remainder is JavaScript` is `remainder`. Are you sure that's the challenge you are seeing this issue on?

**Comment by Davidslc** [comment]
Sorry, it's the Assignment with Plus Equals Waypoint. The Assignment with Minus Equals has the same issue.
<img width="233" alt="plus_minus_result" src="https://cloud.githubusercontent.com/assets/10160841/12277839/e97ee3e2-b93a-11e5-944b-f713c4df7a0f.png">

**Comment by ltegman** [comment]
Can confirm there is an issue in the display function for these challenges.

**Comment by bugron** [comment]
I can confirm too.
