### ISSUE TITLE
Waypoint: Assignment with Times Equals - Result should be int

### ISSUE THREAD

**Issue by Davidslc** [FreeCodeCamp/FreeCodeCamp#6096]
The result of the last variable C displays as a string instead of an integer.

<img width="237" alt="times_equals" src="https://cloud.githubusercontent.com/assets/10160841/12278284/706a7752-b93d-11e5-93fd-524545d34681.png">

**Comment by beechd** [comment]
You could parse the string into an integer using parseInt().

You could either:
parseInt('46');
parseInt(c);
