### ISSUE TITLE
Waypoint: Escaping Literal Quotes in Strings doesn't accept correct answer

### ISSUE THREAD

**Issue by lisapps** [FreeCodeCamp/FreeCodeCamp#6099]
Challenge [Waypoint: Escaping Literal Quotes in Strings](http://www.freecodecamp.com/challenges/waypoint-escaping-literal-quotes-in-strings#?solution=var%20myStr%20%3D%20%22%5C%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%5C%22%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "\"I am a \"double quoted\" string inside \"double quotes\"\""; // Change this line



```
Is this not the correct answer?

**Comment by ltegman** [comment]
You have an extra set of escaped double quotes on either side of your string that should not be there. Thanks and happy coding!

**Comment by lisapps** [comment]
Ah, then the problem is confusing but I don't see how that can be fixed with that sentence. The sentence itself describes what it is, and I was trying to preserve those quotes. Thanks!
