### ISSUE TITLE
Bonfire:  Pairwise - instructions are confusing

### ISSUE THREAD

**Issue by YannHulot** [FreeCodeCamp/FreeCodeCamp#6105]
Hi , I am sorry to reopen this issue but I am currently trying to find the solution of this bonfire and I am really confused. I am a bit relieved that I don't seem to be the only one but even after reading the previous messages, I still can't wrap my head around this problem. 

Why does test 1 return 11 ? 

```
Return the sum of all indices of elements of 'arr' that can be paired with 
one other element to form a sum that equals the value in the second
 argument 'arg'. 
If multiple sums are possible(Which sum are you talking about?), return the smallest sum.
 Once an element has been used, it cannot be reused to pair with another.

``` 
In the explanation above you are talking about sums but which one are you talking about? The sums of the indices of the elements or sums of the the elements of the array, both? I don't want to be nitpicking but, FreeCodeCamp is an international community and many campers picked up English as a second language. I have been living in an english speaking country for at least 4 years now and I have been told repeatedly that my english skills are quite good but even I got confused by this exercise.  If I got confused , then it is a bad sign because that means that all those people with lower English skills will struggle even more. 

Take the first example: 
( [ 1, 4, 2, 3, 0, 5], 7 )

In this case arr[1] + arr[3] = 7     sumIndices1 = 4
         and   arr[2] + arr[5] = 7      sumIndices2 = 7

If I follow the instructions correctly,  the test should return the smallest sum of indices from a pair. In this case it should be 4. Why does the solution ask us to add sumIndices1 and sumIndices2 . Nowhere in the description is it written that in case of multiple pairs  of elements , we should return the total sum of all the indices. 

I believe you should provide more examples and/or explain in better way how you are supposed to find the expected results. 

Thank You.

**Comment by nikrb** [comment]
confused me too, have you seen @richchurcher 's [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3375#issuecomment-141822919)?
