### ISSUE TITLE
Add CSS color as blue in this challenge; code not accepted.

### ISSUE THREAD

**Issue by smglaser** [FreeCodeCamp/FreeCodeCamp#6107]
Challenge [Waypoint: Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%20h2%20%7Bcolor%3Ablue%3B%7D%20%3C%2Fstyle%3E%20%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style> h2 {color:blue;} </style> >CatPhotoApp</h2>



```

**Comment by steelo808** [comment]
```html
<style>
  .h2 {
    color: blue;
  }
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

``` try this  code
