### ISSUE TITLE
When I click the "Run tests" button on the "Label Bootstrap Buttons" Waypoint nothing happens.

### ISSUE THREAD

**Issue by TheLurkingDev** [FreeCodeCamp/FreeCodeCamp#6108]
This occurs even if I do not edit the code supplied when the page loads. The dialog box never opens after "Run tests" is clicked.

I am using Firefox 43.0.4 in Windows 8.1.

Challenge [Waypoint: Label Bootstrap Buttons](http://www.freecodecamp.com/challenges/waypoint-label-bootstrap-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1"></button>
        <button class="btn btn-default target" id="target2"></button>
        <button class="btn btn-default target" id="target3"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4"></button>
        <button class="btn btn-default target" id="target5"></button>
        <button class="btn btn-default target" id="target6"></button>
      </div>
    </div>
  </div>
</div>

```

**Comment by sludge256** [comment]
The box will only pop up if you have the correct code. The test(s) will still run with incorrect code.
Attempt the waypoint again and ask in [Help Chat](https://gitter.im/FreeCodeCamp/Help) (supply the name of the waypoint and your code) if you are still unable to pass. 
If you truly feel as though it's a bug feel free to post the code that does not work in a new comment here.

**Comment by caramiame** [comment]
The code is correct but the test won't process the result. Phone simulation reflects the text on the buttons as directed.  Seems like a bug.  I even moved my id's in front of classes and still would not run.  When I reset the editor, id's followed classes, anyway.  Text reflects correctly but code will not allow user to advance.

RE:Give your button element with the id target1 the text #target1, etc

<div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">target1</button>
        <button class="btn btn-default target" id="target2">target2</button>
        <button class="btn btn-default target" id="target3">target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">target4</button>
        <button class="btn btn-default target" id="target5">target5</button>
        <button class="btn btn-default target" id="target6">target6</button>

**Comment by SaintPeter** [comment]
@caramiame 
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by burnleyt** [comment]
On this exercise you are instructed to label the "buttons" .  Just like you labeled the well in the exercise before this.  However i have done this and still can not get it to pass.  I labeled each of the 6 buttons with the hash and no spaces and it still will not pass.  Here is my code.  Can anyone spot the problem?

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <h4>#target1</h4>
        <button class="btn btn-default target" id="target1"></button>
        <h4>#target2</h4>
        <button class="btn btn-default target" id="target2"></button>
        <h4>#target3</h4>
        <button class="btn btn-default target" id="target3"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <h4>#target4</h4>
        <button class="btn btn-default target" id="target4"></button>
        <h4>#target5</h4>
        <button class="btn btn-default target" id="target5"></button>
        <h4>#target6</h4>
        <button class="btn btn-default target" id="target6"></button>
      </div>
    </div>
  </div>
</div>

**Comment by burnleyt** [comment]
My apologies I thought it would paste the actual code. Maybe someone can help me figure this out?  

 `<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <h4>#target1</h4>
        <button class="btn btn-default target" id="target1"></button>
        <h4>#target2</h4>
        <button class="btn btn-default target" id="target2"></button>
        <h4>#target3</h4>
        <button class="btn btn-default target" id="target3"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <h4>#target4</h4>
        <button class="btn btn-default target" id="target4"></button>
        <h4>#target5</h4>
        <button class="btn btn-default target" id="target5"></button>
        <h4>#target6</h4>
        <button class="btn btn-default target" id="target6"></button>
      </div>
    </div>
  </div>
</div>
`
