### ISSUE TITLE
Waypoint: Understand String Immutability Bug?

### ISSUE THREAD

**Issue by davidslee101** [FreeCodeCamp/FreeCodeCamp#6109]
Challenge [Waypoint: Understand String Immutability](http://www.freecodecamp.com/challenges/waypoint-understand-string-immutability#?solution=%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyStr%20%3D%20%22Hello%20Word%22%3B%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myStr = "Jello World";

// Only change code below this line
myStr = "Hello World";
myStr[0] = "H"; // Fix Me



```
This solution should work, but it doesn't on the webpage - http://www.freecodecamp.com/challenges/waypoint-understand-string-immutability#?solution=%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyStr%20%3D%20%22Hello%20Word%22%3B%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A

**Comment by sludge256** [comment]
While you may have changed `myStr` to have the right value, part of your code is still trying to mutate the string which causes the test to fail. That's why `// Fix Me` is there.

**Comment by vease1999** [comment]
Thanks sludge.  I had issues with this as well because I wasn't thinking about the fact that I was still trying to alter an immutable string.  I understand now.
