### ISSUE TITLE
New FCC code output box no longer provides useful error messages

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#6111]
When users make syntax errors they will no longer get the usual error message.

For example:
Old output
![error old](https://cloud.githubusercontent.com/assets/10524623/12284386/2e22cba2-b964-11e5-9aa4-51429cbccb1c.png)

New output
![error new](https://cloud.githubusercontent.com/assets/10524623/12284489/c0d6665c-b964-11e5-9966-57e13b0b14a3.png)

**Comment by bugron** [comment]
@sludge256 thanks for posting. I've created a PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6110 which will fix this.
