### ISSUE TITLE
Problem submitting "Waypoint: Global Scope and Functions"

### ISSUE THREAD

**Issue by LComplex** [FreeCodeCamp/FreeCodeCamp#6113]
Challenge [Waypoint: Global Scope and Functions](http://www.freecodecamp.com/challenges/waypoint-global-scope-and-functions#?solution=var%20myGlobal%20%3D%2010%3B%2F%2F%20Declare%20your%20variable%20here%0A%0A%0Afunction%20fun1()%20%7B%0A%20%20oopsGlobal%20%3D%205%3B%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20%20%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myGlobal = 10;// Declare your variable here


function fun1() {
  oopsGlobal = 5;// Assign 5 to oopsGlobal Here
  
}

// Only change code above this line
function fun2() {
  var output = "";
  if(typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if(typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

```

I've pressed to reset my code multiple times thinking that I followed the instructions wrong somehow but the only output I'm receiving the from the log is "{}". I asked in the FCC's help chat and those who responded said they saw nothing wrong with the code. I'd like to complete this waypoint but after trying all the variations I could I could never get a full clear. Thanks for your input.

**Comment by SaintPeter** [comment]
Your code passes for me.  Can you open your dev console and look for any page errors?

**Comment by LComplex** [comment]
Dev console as in the console in chrome?

**Comment by SaintPeter** [comment]
Yes.  F12 on windows.  If you are getting page load errors or something, that might indicate an issue with a plugin or your connection.

**Comment by LComplex** [comment]
I ended up not even having to check the console. I went back to the waypoint and I had the green check points. Thank you though for getting to my problem so quickly. In case this happens again in the future if there's indications of load errors in the console does that mean the solution might just be to refresh the full page as opposed to resetting the code?

**Comment by SaintPeter** [comment]
Yes.  It's possible the page just got into a "bad state".  Sometimes something didn't load right . . . it's the nature of the interwebs for ya.  Packet gets lost, everything goes to heck.  ;)

Happy Coding!
