### ISSUE TITLE
Bonfire: Smallest Common Multiple : At times my solution is accepted and sometimes it isn't.

### ISSUE THREAD

**Issue by PizzaPalace** [FreeCodeCamp/FreeCodeCamp#6114]
Challenge [Bonfire: Smallest Common Multiple](http://www.freecodecamp.com/challenges/bonfire-smallest-common-multiple#?solution=function%20smallestCommons(arr)%20%7B%0A%20%20%0A%20%20var%20i%20%3D%20arr%5B0%5D%3B%0A%20%20var%20j%3D%20arr%5B1%5D%3B%0A%20%20%0A%20%20if(j%20%3C%20i)%7B%0A%20%20%20%20%0A%20%20%20%20var%20temp%20%3D%20j%3B%0A%20%20%20%20j%20%3D%20i%3B%0A%20%20%20%20i%20%3D%20temp%3B%0A%20%20%7D%0A%20%20%0A%20%20console.log(%22i%20%22%20%2B%20i)%3B%0A%20%20console.log(%22j%20%22%2B%20j)%3B%0A%20%20%0A%20%20var%20lcm%20%3D%20j%3B%0A%20%20for(var%20k%3Dj%3B%3B%20k%2B%2B)%7B%0A%20%20%20%20var%20islcm%20%3D%20true%3B%0A%20%20%20%20%0A%20%20%20%20for(var%20l%3Dj%3B%20l%3E%3Di%3B%20l--)%7B%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%20if(k%25l%20!%3D%3D%200)%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20islcm%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20if(islcm)%7B%0A%20%20%20%20%20%20lcm%20%3D%20k%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20console.log(lcm)%3B%0A%20%20return%20lcm%3B%0A%7D%0A%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Run this code.Ever so often the the answer is accepted and the 'proceed to the next question' dialog is shown. Otherwise the last test case shows an error. Could this be a problem with range ?

My code:
```javascript
function smallestCommons(arr) {
  
  var i = arr[0];
  var j= arr[1];
  
  if(j < i){
    
    var temp = j;
    j = i;
    i = temp;
  }
  
  console.log("i " + i);
  console.log("j "+ j);
  
  var lcm = j;
  for(var k=j;; k++){
    var islcm = true;
    
    for(var l=j; l>=i; l--){
       
      if(k%l !== 0){
        
        islcm = false;
        break;
      }
      
    }
    
    if(islcm){
      lcm = k;
      break;
    }
    
  }
  console.log(lcm);
  return lcm;
}


smallestCommons([1,5]);

```

**Comment by bugron** [comment]
@PizzaPalace thanks for posting this issue!
It's our loop protection mechanism is working. Your code is evaluating too long. Add `//noprotect` comment at the beginning of your code to be able to pass the challenge

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by PizzaPalace** [comment]
Thank you very much !
