### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by Buzzlightyear90** [FreeCodeCamp/freecodecamp#612]
I selected the buttons as checked but the waypoint is not noticing that the buttons are checked.

**Comment by ShaklinSyed** [comment]
Duplicate of #607

**Comment by terakilobyte** [comment]
Thanks for the report. Closing this duplicate issue.
