### ISSUE TITLE
When using splice, test cases are failing.

### ISSUE THREAD

**Issue by ymohammad** [FreeCodeCamp/FreeCodeCamp#6124]
I have tested the code and it is returning required value. But it is failing the test cases.

Challenge [Checkpoint: Stand in Line](http://www.freecodecamp.com/challenges/checkpoint-stand-in-line#?solution=function%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr.push(item)%3B%0A%20%20%2F%2Fitem%20%3D%20arr%5B0%5D%3B%0A%20%20item%20%3D%20arr.splice(0%2C1)%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(%5B%5D%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item) {
  // Your code here
  arr.push(item);
  
  item = arr.splice(0,1);
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue([], 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by ltegman** [comment]
The tests are asking you to return a value but your splice call is returning a 1 element array. Thanks and happy coding!

**Comment by ymohammad** [comment]
Thanks Itegman.

**Comment by AndrewSC208** [comment]
I am having a similar issue for some reason the below is not working, however when testing in a browser it will pass all tests.

	function queue(arr, item) {
  		// Your code here
  		arr.push(item);
  
 	 	item = arr.splice(0,1);
  
  		return item.toString();
	}

**Comment by ltegman** [comment]
@AndrewSC208 Calling item.toString() means that if the element was a number you will be returning a string instead, which will not match the test.

**Comment by AndrewSC208** [comment]
Thanks for the quick response Itegman!
