### ISSUE TITLE
Uncomment bug

### ISSUE THREAD

**Issue by AbboudJr** [FreeCodeCamp/FreeCodeCamp#6125]
Challenge [Waypoint: Uncomment HTML](http://www.freecodecamp.com/challenges/waypoint-uncomment-html#?solution=%3C!--%20--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!-- -->
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>


```

Its says remove all the --> when I remove the --> in the first row it turns off, I can't move on..

**Comment by SaintPeter** [comment]
It actually says:
> You can start a comment with 

> Uncomment your h1, h2 and p elements.

That means you need to remove both the start: `<!--` and end `-->` tags.

Passing code would look like this:
```html
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
```

Issues are not for coding help.  In the future please ask for assistance in [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) before posting here.

Thanks and Happy Coding!
