### ISSUE TITLE
Validation bug at Profile lookup challenge

### ISSUE THREAD

**Issue by ggviana** [FreeCodeCamp/FreeCodeCamp#6127]
Challenge [Checkpoint: Profile Lookup](http://www.freecodecamp.com/challenges/checkpoint-profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intruiging%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%2C%0A%5D%3B%0A%0A%0Afunction%20lookUp(firstName%2C%20prop)%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20matching%2C%20contact%3B%0A%0A%20%20matching%20%3D%20contacts.filter(function%20(contact)%20%7B%0A%20%20%20%20return%20contact.firstname%20%3D%3D%3D%20firstname%3B%0A%20%20%7D)%3B%0A%0A%20%20if%20(matching.length%20%3C%201)%20return%20%27No%20such%20contact%27%3B%0A%0A%20%20contact%20%3D%20matching%5B0%5D%3B%0A%20%20%0A%20%20if%20(!(prop%20in%20contact))%20return%20%27No%20such%20property%27%3B%0A%20%20%0A%20%20return%20contact%5Bprop%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp(%22Akira%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intruiging Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    },
];


function lookUp(firstName, prop){
  // Only change code below this line
  var matching, contact;

  matching = contacts.filter(function (contact) {
    return contact.firstname === firstname;
  });

  if (matching.length < 1) return 'No such contact';

  contact = matching[0];
  
  if (!(prop in contact)) return 'No such property';
  
  return contact[prop];
  // Only change code above this line
}

// Change these values to test your function
lookUp("Akira", "likes");

```
It appears to be dumping the code at the output box.

**Comment by sludge256** [comment]
What do you mean when you say "dumping code at the output box"?
This is what I see with your code:
![image](https://cloud.githubusercontent.com/assets/10524623/12302572/a02e1e6a-b9da-11e5-8218-49266ffec63e.png)

This error message should be helpful though
>Uncaught ReferenceError: firstname is not defined
