### ISSUE TITLE
Misspelled intriguing in Checkpoint: Profile Lookup

### ISSUE THREAD

**Issue by stopandcatchfire** [FreeCodeCamp/FreeCodeCamp#6129]
Just saying

**Comment by sludge256** [comment]
Where do you see this?

**Comment by stopandcatchfire** [comment]
Lesson 98 in Basic Javascript: Checkpoint: Profile Lookup.  The Sherlock
object under "likes".  Just noticed it and was bugging me :)

-Nick

**Comment by sludge256** [comment]
Thanks for pointing it out. I did recall noticing it also but could not remember where.

**Comment by stopandcatchfire** [comment]
NP! I'll let you know if I run into any other irregularities.

**Comment by stopandcatchfire** [comment]
Oh another thing, I'm not sure if you saw my comments or not, in the jQuery
sequence when people were having trouble moving to the next lesson even
when all tasks were completed and the success message popped up.  I got
around it by moving the script tags below the html and it got through.  Not
sure why, but maybe that helps when the issue pops up again in future.
