### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-fill-in-the-blank-with-placeholder-text has an issue 

### ISSUE THREAD

**Issue by JeffersonMoreau** [FreeCodeCamp/freecodecamp#613]
This is actually more a bug with the general layout of the lessons.  If you're zoomed in in the browser(I've tested FireFox and Chrome), none of the buttons are clickable(More information, report bug, get help, etc). Upon zooming out, those buttons become clickable again. Thought you should know.

Thanks, 

Jeff Morrow

**Comment by terakilobyte** [comment]
Thanks for the report. This is tied to #596 and will be address there!
