### ISSUE TITLE
The current example calculator does not allow for chaining of operations.

### ISSUE THREAD

**Issue by dwhitebud** [FreeCodeCamp/FreeCodeCamp#6130]
The current example calculator, while extremely well done from a front end perspective, does not allow for chaining of operations. Since this is now a requirement, the example should be capable of doing this.

It also has some quirks with decimal points that might want to be addressed (allows for multiple decimal points, places the decimal point at the second position until another digit has been entered)

**Comment by SaintPeter** [comment]
@storbeck - Is this something you want to look into?

**Comment by dwhitebud** [comment]
I should clarify, it does chain operations, but only if you press equals. It does not update the value along the way. My mistake if this is the desired functionality.

**Comment by simondiep** [comment]
@dwhitebud If you are referring to http://www.freecodecamp.com/challenges/build-a-javascript-calculator  :  I've noticed the user stories, site, and demo video are all slightly different.  The chaining user story is a bit vague, which could have been intentional.  However, since the demo video and the current live example on Codepen implement the solution in different ways, this could be confusing for new developers.

I'd suggest either updating the user story to be more clear on what chaining means, or to update the demo video to use the new Codepen example.

**Comment by bugron** [comment]
@dwhitebud @SaintPeter @storbec any updates on this issue?

**Comment by storbeck** [comment]
I don't have time to work on this, the example is forked off of mine to the FreeCodeCamp codepen account so the issue isn't blocked. It is working as it was originally designed, this is a new feature request.

**Comment by bugron** [comment]
@storbeck OK. In that case we need to replace the example project with one that satisfies all user stories.

**Comment by StevePaytosh** [comment]
If anyone is curious how to implement chaining, one way to do this would be using reverse polish notation (or post fix notation). It utilizes a stack to order all the operators at the end of the expression, so a (theoretically) infinite number of operations can be executed in the proper order.

**Comment by asantos00** [comment]
The basic calculators normally "simulate" a click in the "=" when you enter the second operator, they do not worry about the polish notation, only by the order of the numbers and operators.

Something like 4 + 5 * (calculator automatically does 4 + 5) and then it does the multiplication.
Maybe that's a simpler solution than implementing the solution with the chaining using the polish notation refered by @StevePaytosh .

**Comment by SamAI-Software** [comment]
Different calculators have different logic.

Google Calculator (browser version)
- allows chaining operations
- **without** updating the value before pressing "equal"
- **does** follow operator precedence.

Windows Standard Calculator
- allows chaining operations
- **with** updating the value before pressing "equal"
- **does not** follow operator precedence. Here is a [check-list](https://github.com/SamAI-Software/test-ur-calc).

[Official FCC's example calculator for this challenge](https://codepen.io/FreeCodeCamp/full/rLJZrA/) 
- allows chaining operations
- **without** updating the value before pressing "equal"
- **does not** follow operator precedence.

There are many other different variants of calculators with different functionality and logic. FCC's example calculator has a logic that is somewhere between Google's and Windows' variant, so it's not a bug, it's just different logic.
