### ISSUE TITLE
Bug in 'Record Collection' Checkpoint

### ISSUE THREAD

**Issue by akbarbmirza** [FreeCodeCamp/FreeCodeCamp#6131]
Solving the problem using dot notation does not work correctly, and instead seems to delete the collection.

Chrome Dev Tools provide the error:
`Uncaught TypeError: Cannot set property 'prop' of undefined`

To solve the problem, I had to use bracket notation.

For instance, to change a property I did this:
```
if (value !== "" && prop !== "tracks")
    collection[id][prop] = value;
```

**Comment by SleeplessByte** [comment]
You can never use dot notation, if you want a variable to act as the accessor name.
````JavaScript
var baz = { 'foo': 'bar' }

baz.foo // 'bar'
baz[ 'foo' ] // 'bar'

var access = 'foo'

baz.access // no property `access` / undefined
baz[ access ] // 'bar'
````

How would JavaScript know when you want the variable to act like the NAME of the variable and when like it's contents?

That said,

````Javascript
collection.id // undefined, there is no id index in collection
collection.id.prop // cannot set property `prop` of undefined
undefined.prop = value // cannot set property `prop` of undefined
````

**Comment by sludge256** [comment]
Closing as a non-site issue. Feel free to ask in [Help Chat] for clarification if @SleeplessByte 's explanation is unclear to you.
