### ISSUE TITLE
Issue with //http://www.freecodecamp.com/challenges/waypoint-accessing-objects-properties-with-variables//

### ISSUE THREAD

**Issue by emalgamatedsoy** [FreeCodeCamp/FreeCodeCamp#6132]
Challenge [Waypoint: Accessing Objects Properties with Variables](http://www.freecodecamp.com/challenges/waypoint-accessing-objects-properties-with-variables#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3D%2016%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%5BplayerNumber%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0Aconsole.log(player)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.

My code:
```javascript
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;       // Change this Line
var player = testObj[playerNumber];   // Change this Line
console.log(player);

```````````````````````````````````````````````````````````````````````````````````````````````````````````````

Hey!

So I have just done the waypoint "accessing-objects-properties-with-variables" 
and I have found a bug!!!

var playerNumber = 16;       // Change this Line
var player = testObj[playerNumber];   // Change this Line
console.log(player);

output : ""
------------------------------------------------------------------------------------------------------------------------------

The console that returns the output from javascript doesn't return the value "Montana"

instead.. It returns the value ""..

I love the new lessons that you've included in the javascript.. though I found this bug irritable..

It could be that I'm using gecko on firefox ...

I want to point out the problem to you guys!

Thanks for the consideration!!

I'll attach a picture for you guys of the issue

![errorwaypointaccessingobjectpropertieswithvar](https://cloud.githubusercontent.com/assets/16180935/12305016/9a48b1ba-ba00-11e5-8791-1ea36ac0cf21.png)
.

**Comment by sludge256** [comment]
The FCC code output window is not the same as viewing the console of your browser. You'll notice that   the output remains the same even if you remove your `console.log()` statement. 
Before we switched to a new method of displaying output I believe for this lesson it would simply remain blank.

**Comment by emalgamatedsoy** [comment]
Thank you for the clarification.
Also, great response time!
