### ISSUE TITLE
Waypoint: Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by Anebimeta4** [FreeCodeCamp/FreeCodeCamp#6136]
Challenge [Waypoint: Escaping Literal Quotes in Strings]
My code seems alright, but would not compile correctly

My code:
```javascript
var myStr = "I am a \"double quoted\" string inside \"double quotes\"  "; // Change this line



```

**Comment by sludge256** [comment]
Get rid of the two spaces at the end of your string and it will pass.

[Help Chat](https://gitter.im/FreeCodeCamp/Help) is the preferred place for these types of questions. Github issues are reserved for site related bugs and discussions.

**Comment by Anebimeta4** [comment]
Thank you @sludge256

**Comment by mrcotter001** [comment]
var myStr = "I am a \"double quoted \"string inside\"double quotes\"";

**Comment by mrcotter001** [comment]
does not work pls help

**Comment by ltegman** [comment]
@mrcotter001 Github issues are not for code help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance.

**Comment by mrcotter001** [comment]
var myStr = "I am a \"double quoted\" string inside \"double quotes\"";

got it
