### ISSUE TITLE
Conditions are not displayed.

### ISSUE THREAD

**Issue by AlexMogoryan** [FreeCodeCamp/FreeCodeCamp#6137]
Challenge [Waypoint: Iterate Through an Array with a For Loop](http://www.freecodecamp.com/challenges/waypoint-iterate-through-an-array-with-a-for-loop#?solution=%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%20%7B%0A%20%20myTotal%20%2B%3D%20myArr%5Bi%5D%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

conditions are not displayed ... not abele to continue.

![screenshot 7](https://cloud.githubusercontent.com/assets/15803277/12309230/4dca2ace-ba6b-11e5-8433-05c1f8609e15.png)

**Comment by sludge256** [comment]
Able to reproduce on 
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36`

It does still pass if the correct code is provided. Your code uses the variable named `myTotal` when the instructions ask for a variable called `total`.

**Comment by AlexMogoryan** [comment]
ou that's right, i passed, but i only see conditions after i passed...
tanks sludge256
