### ISSUE TITLE
Challenge does not read new properties

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/FreeCodeCamp#6139]
Challenge [Waypoint: Make Instances of Objects with a Constructor Function](http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var myCar;

```

**Comment by ltegman** [comment]
Does not described a problem. Please visit the help chat for challenge help. Thanks and happy coding!
