### ISSUE TITLE
UI / UX Suggestion: Fixed left sidebar for waypoints

### ISSUE THREAD

**Issue by fidelscodes** [FreeCodeCamp/freecodecamp#614]
When "more information" is clicked on the left sidebar, the length of the page requires scrolling to read the complete instructions. Just thought it would be better if that section was fixed and was scrollable. Sort of the way it works on Codecademy.

**Comment by terakilobyte** [comment]
On the longer challenge scrolling the page is required anyway. Given our current layout there's no way to make the more information panel fixed without it covering other important elements up. I'm closing this issue for now as the current UI works and we're more focused on ensuring all the challenges are performing their job well.
