### ISSUE TITLE
console does not read new parameters

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/FreeCodeCamp#6140]
Challenge [Waypoint: Make Unique Objects by Passing Parameters to our Constructor](http://www.freecodecamp.com/challenges/waypoint-make-unique-objects-by-passing-parameters-to-our-constructor#?solution=var%20Car%20%3D%20function(wheels%2C%20seats%2C%20engines)%20%7B%0A%20%20%2F%2FChange%20this%20constructor%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.seats%20%3D%201%3B%0A%20%20this.engines%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2FTry%20it%20out%20here%0Avar%20myCar%20%3D%20new%20Car()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function(wheels, seats, engines) {
  //Change this constructor
  this.wheels = 4;
  this.seats = 1;
  this.engines = 1;
};

//Try it out here
var myCar = new Car();

```

**Comment by ltegman** [comment]
Does not describe a problem. Please visit the help chat for challenge help. Thanks and happy coding!
