### ISSUE TITLE
Nesting For Loops

### ISSUE THREAD

**Issue by JordanDJackson** [FreeCodeCamp/FreeCodeCamp#6143]
This exercise does not include the array that it wants you to multiply in the function. It mistakenly only includes the values placed inside the function that you are supposed to build. I then had to create the array manually to solve the problem.

**Comment by SaintPeter** [comment]
On the contrary:
> Modify function multiplyAll so that it multiplies the product variable by each number in the sub-arrays of `arr` 

`arr` is a parameter provided by the function.  When the function is called with an arbitrary `arr`, you can perform the operations on `arr` without ever knowing what is in it.

If you would care you share your actual code, I can show you how to correct it.

Better yet:  Take it by the [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link) where you can likely get some interactive help and explanation.

**Comment by JordanDJackson** [comment]
Yes. I understand. I am just saying that the array "arr" was not present in the exercise. I had to build it myself. I am used to it being included if it is going to be used. It just really confused me. I know how to solve it now, I was just hoping to save other learners those ten minutes I lost.

**Comment by SaintPeter** [comment]
Nope, it's right here:
```js
multiplyAll([[1,2],[3,4],[5,6,7]]);
```
When you call `multiplyAll`, the first parameter that is passed becomes `arr` inside the function.  That's how parameters work.

Closing as this is not a site issue.  As before, I strongly encourage you to take your code by the [Help Chat](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

Thanks and happy coding!

**Comment by auranga** [comment]
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  for (var i=0; i < arr.length; i++) {
    
    for (var j=0; j < arr[i].length; j++) {
      product = (arr[i][j] * product);
    }
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code

multiplyAll([[1,2],[3,4],[5,6,7]]) ;

**Comment by Shamel1** [comment]
Need help.....

**Comment by ltegman** [comment]
@Shamel1 Github issues are not for code help. Please visit the [HelpJavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) or [General Help Chat](https://gitter.im/FreeCodeCamp/Help). Thanks and happy coding!

**Comment by heyhey2015** [comment]
really simple 
for(var i=0; i < arr.length; i++){ 
  
  for(var j=0; j < arr[i].length; j++){ 
    product *= arr[i][j];

**Comment by heyhey2015** [comment]
``for(var i=0; i < arr.length; i++){ 
  
  for(var j=0; j < arr[i].length; j++){ 
    product *= arr[i][j];

**Comment by profoundhub** [comment]
Here is what I got : 

```
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line  
  for (var p=0; p < arr.length; p++) {
    for (var q=0; q < arr[p].length; q++) {
      console.log(arr[p][q]);                  
      product *= arr[p][q];  
    }
  }
  return product;
  // Only change code above this line  
}
// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);
```

**Comment by Shraddha99** [comment]
@profoundhub did that work?

**Comment by profoundhub** [comment]
@Shraddha99 , yes, it does work! ...Try it!

**Comment by Satorios** [comment]
@profoundhub 

While working on it, I literally had the same code as you except the variable "p" was "i" and "q" was "j". It didn't work until I changed them from "i" to "p" and "j" to "q". I find that strange.

**Comment by chuckiebluestar** [comment]
Thanks for this.  I was tripped up on 
**product = arr[i]*arr[j]**
instead of **product *= [i][j]**

**Comment by gringogidget** [comment]
I feel this challenge to be a bit annoying because we haven't yet learned what arr.length is.  Up until now I just thought a variable went before it and when I noticed arr is not defined I was like.. wth.

**Comment by lokeshtoserve** [comment]
Hope this will work for you. 
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
```  for (var i=0; i < arr.length; i++) {
  for (var j=0; j < arr[i].length; j++) {
  product*=arr[i][j]; ```
  }
  }
  // Only change code above this line

 return product;


}
// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);

----------------------------------------------------------
Just Multiply each array element when for loop counts itself.
:+1:

**Comment by TheeGrassHopper** [comment]
function multiplyAll(arr) {
  var product = 1;
  for(var i = 0; i < arr.length; i++){
    for(var a = 0; a < arr[i].length; a++){
      console.log(product *= arr[i][a]);
    }
  }
  return product;
}
// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);

**Comment by veemix** [comment]
Asking people to go to chat when the chat really doesn't function well (you can't specifically go to chat for that one problem) is clearly not a solution. You need to change the "chat" on the site so that it has separate chat for each problem and provides solutions there.

**Comment by Lombardoh** [comment]
I'm late to the party, but you need to add a validation, otherwise product will be multiplied by NaN and mess up the result


function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  for(var i=0; i < arr.length; i++){
    for(var j=0; j < arr.length; j++){
      if(arr[i][j]) //Here it validates if the position in the array its not NaN
        product= product* arr[i][j];
      
    }
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);

**Comment by gowshiselva** [comment]
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  for (var i=0; i < arr.length; i++) {
  for (var j=0; j < arr[i].length; j++) {
   
   product *= arr[i][j] ;}}
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);

**Comment by gowshiselva** [comment]
above code worked for me, important thing is we need to set product=1

**Comment by siaxiong** [comment]
i agree that chat does not help most of the time

**Comment by dcolclasure** [comment]
I have found that chat works well for me but I guess it can depend on your time zone.  In addition I have learned that the people assisting understand the code very well but don't always understand or remember what it's like to be learning code for the first time.  I'm not trying to trash on them I just want to emphasize that solution to work around that is being persistent until you get the solution you're looking for.  Sometimes they come across as blunt or rude but maybe that comes with the territory.

If you don't get the help you need at first be patient and just keep asking even if you sound like a broken record.  Typically they are learning too, just different stuff.  I have seen this work in my personal experience.

Let me know if this does not help.

**Comment by Aibolat1993** [comment]
Hi guys! It is a bad habit when you are just copy somebody's code, try to do it yourself

**Comment by iebert1** [comment]
Works well!

function multiplyAll(arr) {
  var product = 1;
  for (var i = 0; i < arr.length; i++){
    for (var j = 0; j < arr[i].length; j++){
     product *= arr[i][j];
    }
  }
  return product;
}
multiplyAll([[1,2],[3,4],[5,6,7]]);

**Comment by ad22323n** [comment]
Can someone explain these for loop to me please.
for(var i=0; i<arr.length; i++){
    for(var j=0; j<arr[i].length; j++)

**Comment by lorduwahz** [comment]
@ad22323n 
Because it is a nested array i.e, a main array and other sub arrays, you have to loop through the main, and use it as medium to loop through its sub arrays. Hence you have the second for loop embedded in the curly brackets of the first for loop. 
I hope it helps.

**Comment by AliFox15** [comment]
@ad22323n It is like to select every element within your muti-dimensional array.if it is a rectangle,The first loop is to select height,the second is like to select width...I am a newbie,so please don't flame me.

**Comment by ad22323n** [comment]
Thank you guys , it was really understandable

**Comment by snntaylan** [comment]
can someone help me ?

```
function multiplyAll(arr) {
  var product = 1;
  console.log(arr);
  console.log(arr.length);
  
  for (var i=0; i < arr.length; i++) {
  }
    for (var j=0; j < arr[i].length; j++) {
      
      console.log(arr[i][j]);
      
      product=product * arr[i][j];
    }
    
    
  return product;
  
}
```

**Comment by apolloman** [comment]
You should understand length property!
`[[1, 2], [3, 4], [5 , 6]].lenght === 3;` - This is the first loop!
Nested loop helps to enter into each  sub Arrays[index] inside the Main Array ) and multiply each index to product

**Comment by collabitron** [comment]
I don't understand how to solve this problem. I understand how to access each element in each sub array, but how do I store each element within the sub array, to then multiply them, without moving on to the next sub array and using those numbers, too?

I only want to multiple all of the numbers within each sub array, but I'm unsure of how to code such that I extract each element of the sub array (and no other sub array), understand when I have collected the full number of elements within the sub array, and then multiply them.

**Comment by kubila** [comment]
There are some missing explanations and instructions in Basic JavaScript section(I mean they need more detail). We can find the solution at the end but it takes some time. Just saying.
