### ISSUE TITLE
Golf Store

### ISSUE THREAD

**Issue by DivaWeb** [FreeCodeCamp/FreeCodeCamp#6144]
One of the test is marked 

golfScore(5, 5) should return "Par

This can not be returned as par because there is already another test for par which is correct

golfScore(4, 4) should return "Par"

I am unable to complete this lesson because of this. 

This is for Checkpoint Golf Score in basic javascript. I have included my code as well.

function golfScore(par, strokes) {
  // Only change code below this line
  if (par - 3 && strokes ==1){
    return "Hole-in-one!";
  }
  else if (par - 2 && strokes == 2){
    return "Eagle";
  }
  else if ( par - 1 && strokes == 3){
    return "Birdie";
  }
  else if( par  && strokes== 4){
    return "Par";
  }
  else if( par + 1 && strokes == 5){
    return "Bogey";
  }
  else if( par + 2 && strokes == 6){
    return "Double Bogey";
    
  }
  else if (par + 3 && strokes >6 ){
    return "Go Home!";
  }
    // Only change code above this line
}

// Change these values to test
golfScore(5,5);

**Comment by ltegman** [comment]
5,5 and 4,4 are both valid cases for Par. If that doesn't work for your solution you are approaching the problem incorrectly. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for challenge help. Thanks and happy coding!

**Comment by athomasbeck** [comment]
Another issue with this challenge though. golfScore(5, 2) is not an eagle like the check says it should be. That is a double-eagle, which makes this challenge incorrect.
