### ISSUE TITLE
Tests Failing on Waypoint: Adding a default option in Switch statements

### ISSUE THREAD

**Issue by jeremyroe** [FreeCodeCamp/FreeCodeCamp#6145]
Challenge [Waypoint: Adding a default option in Switch statements](http://www.freecodecamp.com/challenges/waypoint-adding-a-default-option-in-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20val%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(a)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I believe this code to be accurate and correct however all tests seem to fail and no output is returned regardless of what I try on this waypoint.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
switch(val){
  case "a":
      answer = "apple";
      break;
  case "b":
      answer = "bird";
      break;
    case "c":
      answer = "cat";
      break;
    default:
      answer = "stuff";

  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(a);


```

**Comment by ltegman** [comment]
You have a red lint error in the gutter of the editor. This means something is very wrong with your code. You're missing a closing brace. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm what you're seeing is a site error and not an issue with your code. Thanks and happy coding!

**Comment by sludge256** [comment]
Besides missing a closing brace, the test value you are using will cause this error
`ReferenceError: a is not defined`

Make sure to wrap your input with quotation marks if you want them to be treated as a string.
(Normally, these error messages would appear in the output box but currently they do not. A fix is on the way.)

**Comment by jeremyroe** [comment]
My mistake - Thanks guys
