### ISSUE TITLE
Test gives correct outcome, but I cannot pass exercise

### ISSUE THREAD

**Issue by Cereal-Coder** [FreeCodeCamp/FreeCodeCamp#6146]
![screen shot 2016-01-14 at 5 39 48 am](https://cloud.githubusercontent.com/assets/15092795/12315958/5aadc604-ba81-11e5-8492-7942300d7154.png)
Challenge [Waypoint: Replacing If Else Chains with Switch](http://www.freecodecamp.com/challenges/waypoint-replacing-if-else-chains-with-switch#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20switch%20(val)%20%7B%0A%20%20%20%20%0A%20%20%20%20case%20'bob'%3A%0A%20%20%20%20answer%20%3D%20%22Marley%22%3B%0A%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20case%20'42'%3A%0A%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20case%20'1'%3A%0A%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20case%20'99'%3A%0A%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%20%20break%3B%0A%20%20%20%20%0A%20%20%20%20case%20'7'%3A%0A%20%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest('1')%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  
  switch (val) {
    
    case 'bob':
    answer = "Marley";
    break;
      
    case '42':
    answer = "The Answer";
    break;
      
    case '1':
    answer = "There is no #1";
    break;
      
    case '99':
    answer = "Missed me by this much!";
    break;
    
    case '7':
    answer = "Ate Nine";
    break;
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest('1');


```
Thanks for reviewing :)

**Comment by ltegman** [comment]
You're checking for strings when you should be looking for numbers. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to get confirmation that the error you're seeing is indeed a site error and not an issue with your code. Thanks and happy coding!

**Comment by Cereal-Coder** [comment]
Usually I do check the Help Chat, this time I was pretty sure there was and error... Sorry about that and thanks :)
