### ISSUE TITLE
Sum all primes - solution works on chrome but not firefox.

### ISSUE THREAD

**Issue by Crintz** [FreeCodeCamp/FreeCodeCamp#6149]
Challenge [Bonfire: Sum All Primes]

User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Just thought i'd put this up here - this code is passing on chrome but not on firefox - its failing on the sumPrimes(977) test case. 
![capture1](https://cloud.githubusercontent.com/assets/10933049/12319633/b8739888-baf7-11e5-8d2b-3805f78c475a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10933049/12319634/b8746786-baf7-11e5-879a-6616b7313763.PNG)

My code:
```javascript
function sumPrimes(num) {
  var arr = [];
  for(var i = 2; i <= num; i++){
    arr.push(i);
  }
  var arr2 = arr;
  var finArr = [];
  for(var j = 4; j <= num; j++){
    for(var k = 0; k < arr2.length; k++){
      if(arr[k] < j && j % arr2[k] === 0){
          for(var l = 0; l < arr2.length; l++){
            if(j === arr2[l]){
              arr2.splice(l,1);
            }
          }
         }
    }
  }
  return arr2.reduce(function(a,b){
    return a + b;
  });
}

sumPrimes(977);

```

**Comment by sludge256** [comment]
It appears as though your code is triggering the loop protection.
Try adding:
```js
//noprotect
```
to the top of your code.

For future reference in case you disable loop protect and create an infinite loop this is how to disable the [auto run](https://github.com/freecodecamp/freecodecamp/wiki/Disable-Code-Auto-Run).

**Comment by Y-Taras** [comment]
thanks for solution, it helped me)
