### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/bonfire-truncate-a-string has an issue 

### ISSUE THREAD

**Issue by mdanro** [FreeCodeCamp/freecodecamp#615]
the text is misleading.
Truncate a string (first argument) if it is longer than the given maximum string length (second argument). Return the truncated string with a '...' ending.

The truncated string + '...' should equal the maximum string length, slicing the string to the max string length will not pass the assert.

**Comment by mdanro** [comment]
It is in the description...

**Comment by mdanro** [comment]
Please move the part "Note that the three dots at the end add to the string length." up in the first sentence

**Comment by LumenTeun** [comment]
This seems to have been addressed in a recent commit; changes are present in staging, but not on the website. Should probably be closed soon?
