### ISSUE TITLE
Please why is this code not working 

### ISSUE THREAD

**Issue by ibnahmadbello** [FreeCodeCamp/FreeCodeCamp#6152]
Challenge [Bonfire: Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays#?solution=function%20largestOfFour(arr)%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20var%20largeArr%20%3D%20%5B%5D%3B%0A%20%20var%20first%20%3D%200%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20arr%5Bi%5D.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20if%20(arr%5Bi%5D%5Bj%5D%20%3E%20first)%7B%0A%20%20%20%20%20%20%20%20first%20%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20largeArr.push(first)%3B%0A%20%20%7D%0A%20%20return%20largeArr%3B%0A%7D%0A%0AlargestOfFour(%5B%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function largestOfFour(arr) {
  // You can do this!
  var largeArr = [];
  var first = 0;
  for (var i = 0; i < arr.length; i++){
    for (var j = 0; j < arr[i].length; j++){
      if (arr[i][j] > first){
        first = arr[i][j];
      }
      
    }
    largeArr.push(first);
  }
  return largeArr;
}

largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by ibnahmadbello** [comment]
The above code return [27, 27, 39, 1001] instead of [27, 5, 39, 1001].

**Comment by raisedadead** [comment]
That's because after you traverse through the first set of arrays, i.e. `[13, 27, 18, 26]` the value of `first` is `27`, so when you traverse through `[4, 5, 1, 3]`, the condition `if (arr[i][j] > first)` fails.

So you must, reset the `first` to `0`, after `  largeArr.push(first)`.

Happy coding! In future please ask for assistance in the (Help Chat Room)[https://gitter.im/FreeCodeCamp/Help], Github issues are for bugs only.

Thanks!

**Comment by ibnahmadbello** [comment]
Thanks. I later resolved it in the chat room.
