### ISSUE TITLE
what is the issue in this code, can any one check it, i don't understand where is the bug

### ISSUE THREAD

**Issue by ashrafmscs** [FreeCodeCamp/FreeCodeCamp#6154]
var count = 0;

function cc(card) {
  // Only change code below this line
  if(card==2 || card==3 || card==4 ||  card==5 || card==6)
    count++;
    else if(card==7 || card==8 || card==9)
      count+=0;
  else if(card==10 || card=='j' || card=='Q' || card=='K' || card=='A')
    count-=0;
  
  if(count<=0){
    return card+" Hold";
  }
  else if(count>0){
    return card +" Bet";
  }
  
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
 cc('A');
--------------------------------------------------
when i run this it shows

Cards Sequence 2, 3, 4, 5, 6 should return "5 Bet"
Cards Sequence 7, 8, 9 should return "0 Hold"
Cards Sequence 10, J, Q, K, A should return "-5 Hold"
Cards Sequence 3, 2, A, 10, K should return "-1 Hold"

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [help chat](https://gitter.im/FreeCodeCamp/Help) for assistance. Thanks and happy coding!
