### ISSUE TITLE
The power level is only 9000

### ISSUE THREAD

**Issue by JEBtheGamer1** [FreeCodeCamp/FreeCodeCamp#6155]
It's supposed to be over 9000. Get your memes right FreeCodeCamp.

Challenge [Waypoint: Target the same element with multiple jQuery Selectors](http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors#?

**Comment by sludge256** [comment]
Compliment messages aren't specific to any one exercise but I'll see to it that this mistake is corrected.

**Comment by raisedadead** [comment]
Refering http://dragonball.wikia.com/wiki/It's_Over_9000!

Changing the Meme from `Power level 9000!` to `Power level? It's over 9000!` should be a correction IMO.

Correct? If agreed, will do the changes accordingly.

**Comment by SaintPeter** [comment]
\*facepalms\*

**Comment by raisedadead** [comment]
Hahaha.. yeah! but some do take their meme's seriously :laughing:

**Comment by BerkeleyTrue** [comment]
@SaintPeter hehe. Had the same reaction. Figured I'd let y'all handle it.
