### ISSUE TITLE
issue with function 49.Waypoint: Passing Values to Functions with Arguments Incomplete   NEW

### ISSUE THREAD

**Issue by roniRamon** [FreeCodeCamp/FreeCodeCamp#6157]
the function should pass but it is not ... the console show problem in line 6 which make no sense...
any idea???? i uploaded a screen shot 

<img width="1307" alt="screen shot 2016-01-14 at 11 02 04 am" src="https://cloud.githubusercontent.com/assets/15132399/12334368/8fc39440-baae-11e5-94aa-3d91e70f5acc.png">

**Comment by ltegman** [comment]
Please post a link to the challenge you are working on and text of your full code solution so that we don't have to manually type out the code in your screenshot.

**Comment by roniRamon** [comment]
http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments

function myFunction(c, d) {
  console.log(c + d);
}

myFunction(100, 3);

**Comment by roniRamon** [comment]
Thank you for the fix :)

**Comment by ltegman** [comment]
Code passes fine on my end and it sounds like this is resolved. Closing. Thanks and happy coding!
