### ISSUE TITLE
will not accept. 

### ISSUE THREAD

**Issue by mjohnstonee** [FreeCodeCamp/FreeCodeCamp#6158]
Challenge [Waypoint: Escaping Literal Quotes in Strings](http://www.freecodecamp.com/challenges/waypoint-escaping-literal-quotes-in-strings#?solution=var%20myStr%3B%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/537.86.3</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr; "I am a \"double quoted\" string inside \"double quotes\"";



```

**Comment by ltegman** [comment]
Look closely at your code. This is not a bug. Thanks and happy coding!
