### ISSUE TITLE
Make Instances of Objects with a Constructor

### ISSUE THREAD

**Issue by nabilhel** [FreeCodeCamp/FreeCodeCamp#6159]
Challenge [Waypoint: Make Instances of Objects with a Constructor Function](http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A%0Avar%20myCar%20%3D%20new%20car%20()%3B%0A%0A%0A%20%20%2F%2FmyCar.wheels%20%3D%204%3B%0A%20%20myCar.nickname%20%3D%20%22something%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.



var myCar = new car ();

  myCar.nickname = "something";

  //myCar.wheels = 4;


```
i think nothing wrong with my 
code  but can pass challenge

**Comment by sludge256** [comment]
Pay attention to casing when referencing variables. There is no constructor named `car`, however there is one called `Car`.

**Comment by nabilhel** [comment]
thanks  done
