### ISSUE TITLE
Broken navigation on the "Jobs" page.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#6160]
The navigation is broken on the jobs page at http://freecodecamp.com/jobs

Visiting the jobs page, the nav bar changes to:
![2](https://cloud.githubusercontent.com/assets/1884376/12338349/29f1d758-bb35-11e5-8c85-9ab3cc9eae39.PNG)

where as the correct nav bar on other pages is:
![0](https://cloud.githubusercontent.com/assets/1884376/12338394/59588780-bb35-11e5-9317-edda1f528d93.PNG)

The **Links** should be **About**.

I have fixed this locally, and checked, but have run into a side issue that was apparently pre-existing on the **Jobs** page nav bar. The spacing between the **Links** (or corrected to **About**) and the **Sign In** button is seems off as seen below:
![3](https://cloud.githubusercontent.com/assets/1884376/12338428/8b767a38-bb35-11e5-8de7-20eb6cecaa17.PNG) ![4](https://cloud.githubusercontent.com/assets/1884376/12338433/950ff6fa-bb35-11e5-9ab7-a5928af20eca.PNG)

However it seems to be correct on the other pages like **Home** or **Map** pages as seen below:
![5](https://cloud.githubusercontent.com/assets/1884376/12338472/be90a876-bb35-11e5-9afe-1877546e95bc.PNG)

Solution : The fix can be done by changing the `common/app/components/Nav/links.json`
 
```javascript
{
  "content": "Links", //Change this to About
  "link": "/links" //Change this to about
}]
```

However I am not sure where to fix the CSS for the spacing part of the secondary issue.

**Comment by SaintPeter** [comment]
@BerkeleyTrue - Looks like @BerkeleyTrue's changes to the site didn't make it into the Jobs section.

**Comment by BerkeleyTrue** [comment]
I'll fix on the redesign branch

**Comment by bugron** [comment]
Closing this issue as it is fixed.
