### ISSUE TITLE
Shows error with correct answer (myVar--1;)

### ISSUE THREAD

**Issue by michaeljheath** [FreeCodeCamp/FreeCodeCamp#6162]
Challenge [Waypoint: Decrement a Number with Javascript](http://www.freecodecamp.com/challenges/waypoint-decrement-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 11;

// Only change code below this line
myVar--1;


```

**Comment by alistermada** [comment]
@michaeljheath You need to remove `1` from your answer.  The `--` operator already decrements by 1.

**Comment by BerkeleyTrue** [comment]
Your code has a syntax error. Please use the help chat you get stuck.

Happy Coding!
