### ISSUE TITLE
Waypoint: Local Scope and Functions

### ISSUE THREAD

**Issue by kkrugler** [FreeCodeCamp/FreeCodeCamp#6165]
In trying out this Waypoint in advance of my students, I'm confused by two things:

 * the unexplained use of the 'use strict' literal (yes, I know why it's being used, but throwing that into the mix, where it looks like an aborted snippet of code, is really odd).
 * the instructions don't talk about first wanting to run (after adding myVar) without any other changes, and **expecting** to get a gnarly stack frame dump, and then following instructions in the code comments to remove the second console.log statement.

Why not just remove the 'use strict' directive, and both console.log commands, and just have a check for whether myVar is defined outside of the function, e.g. 
```javascript
var isDefined = (typeof myVar === 'undefined');
```

**Comment by re4ect** [comment]
Well this is odd four days and no response? Is some one sleeping at the wheel?

**Comment by erictleung** [comment]
@SaintPeter, should we remove the `use strict;` or keep it?

**Comment by SaintPeter** [comment]
I don't have a good answer for this because I don't fully understand this one myself - I ended up not writing the whole thing.  The idea of local and global variables is important to understand but very difficult to illustrate in a practical way.  We have the "use strict" there to keep a global from being created accidentally.  I'm not quite sure how we would explain it, but it's absolutely needed.

I'm open to suggestions.

**Comment by kkrugler** [comment]
I guess I'm missing something here. It seems like you want to catch the case of the variable being created as a global, a that's the mistake a programmer would make when they forget to use "var".

If the template was set up as:
``` javascript
function myFunction() {

  // Don't change code below this line!
  return myVar;
}

myFunction();
```
and then the test verified that
``` javascript
typeof myVar === 'undefined'
```
wouldn't that catch the cases of (a) no variable is defined, or (b) variable is set to something without using 'var'?

**Comment by SaintPeter** [comment]
The issue is that if a global variable is created it cannot be "unset".  That would lead to situations where campers accidentally created the wrong type of thing, then could not "go back" without refreshing the page, which was even more confusing.

**Comment by bugron** [comment]
@kkrugler @SaintPeter any updates on this issue?

**Comment by kkrugler** [comment]
@SaintPeter - based on http://perfectionkills.com/understanding-delete/, if a global variable is created inside a function (missing the 'var' keyword) then it seems like it should be deletable. I assume it's a property of the window. So you could add a "delete <window ref>.myVar" at the end of the test code to clear it out, yes?
