### ISSUE TITLE
iterate through an array with for loop

### ISSUE THREAD

**Issue by FarzanehNezarati** [FreeCodeCamp/FreeCodeCamp#6166]
Challenge [Waypoint: Iterate Through an Array with a For Loop](http://www.freecodecamp.com/challenges/waypoint-iterate-through-an-array-with-a-for-loop) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line

var myTotal = 0;
for(i = 0 ; i < myArr.length ; i++){
  myTotal += myTotal[i];
}

```
it has error of:
line:22, column:116

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!
