### ISSUE TITLE
Waypoint: Use Bracket Notation to Find the First Character in a String

### ISSUE THREAD

**Issue by BrandynDuff** [FreeCodeCamp/FreeCodeCamp#6167]
// Setup
var firstLetterOfLastName = "";
var lastName = "Lovelace";
firstLetterOfLastName = lastName[0];

is my answer.. and its not giving it to me.. it just says "LoveLace" vs  "L"

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by Vinpan1** [comment]
just put the "L" on the first line of code.
