### ISSUE TITLE
Different name for the function in the "checkpoints" (just confusing)

### ISSUE THREAD

**Issue by JSampaioL** [FreeCodeCamp/FreeCodeCamp#6168]
Challenge [Waypoint: Generate Random Whole Numbers within a Range](http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range#?solution=%2F%2F%20Example%0Afunction%20ourFunction(ourMin%2C%20ourMax)%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%7D%0A%0AourFunction(1%2C%209)%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20randomRange(myMin%2C%20myMax)%20%7B%0A%0A%20%20return%20Math.floor(Math.random*(myMax-myMin%2B1)%20%2B%20myMin)%3B%20%2F%2F%20Change%20this%20line%0A%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0Avar%20myRandom%20%3D%20randomRange(5%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.

The function the user has to write is called **randomRange**, but it is referred to in the "checkpoints" (bottom left) as **myFunction**:
- The random number generated by **myFunction** should be an integer, not a decimal.
- **myFunction()** should use use both myMax and myMin, and return a random number in your range.

**Comment by SaintPeter** [comment]
You are correct.  The test messages are wrong.  Good catch!

**Comment by Checkmatez** [comment]
Also there is double word "use use" in this checkpoint.
I didn't want to start a new issue for this :smiley:

**Comment by sludge256** [comment]
@Checkmatez feel free to file an issue. It makes things easier to track and gives us an issue to reference.
