### ISSUE TITLE
Converts

### ISSUE THREAD

**Issue by Gnilemcire** [FreeCodeCamp/FreeCodeCamp#6169]
Hi. So i came up with the variable for fahrenheit and pressed run test to see if I defined it correctly. It then passed as if it was correct. Yay for it being correct cause it stumped me a bit, but I didn't change any of the inputs to give me any of the values it asked for. It was nice to pass it, but I feel like we should have to do all of them to get a green light since those are some of the ones needed checked too. Thank you and hope this helped and wasn't a waist of time. - Eric 

Challenge [Checkpoint: Convert Celsius to Fahrenheit](http://www.freecodecamp.com/challenges/checkpoint-convert-celsius-to-fahrenheit#?solution=function%20convert(celsius)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20fahrenheit%20%3D%20((celsius%20*%209)%20%2F%205)%20%2B%2032%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20if%20(%20typeof%20fahrenheit%20!%3D%3D%20'undefined'%20)%20%7B%0A%20%20return%20fahrenheit%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20'fahrenheit%20not%20defined'%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0Aconvert(30)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.22 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(celsius) {
  // Only change code below this line

var fahrenheit = ((celsius * 9) / 5) + 32;

  // Only change code above this line
  if ( typeof fahrenheit !== 'undefined' ) {
  return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(30);
```

**Comment by ltegman** [comment]
I'm not sure I understand what your issue is. Are you saying to think you should have needed to change the following line to the different values used in the test cases to pass?
```js
// Change the inputs below to test your code
convert(30);
```

**Comment by Gnilemcire** [comment]
That is correct. It asked for multiple different ones, but passes without doing them. Or maybe if it just didn’t have the list of them red x-ed it wouldn’t even be an issue. I understand the formula works for them all just kinda confusing.

**Comment by ltegman** [comment]
The tests are there to make sure your solution works consistently for a number of different inputs. Making you change the number to run each of those tests would be tedious and wouldn't teach you about programming. The call inside the editor is just there in case one of the tests wasn't passing like you thought it should and you want to display the output your code is giving to the console. Thanks and happy coding!

**Comment by Gnilemcire** [comment]
Right on, thanks for your time.
