### ISSUE TITLE
Bonfire Steamroller - does not accept solution 

### ISSUE THREAD

**Issue by PizzaPalace** [FreeCodeCamp/FreeCodeCamp#6170]
Challenge [Bonfire: Steamroller](http://www.freecodecamp.com/challenges/bonfire-steamroller#?solution=%2F%2Fno%20protect%0Avar%20res%20%3D%20%5B%5D%3B%0Afunction%20steamroller(arr)%20%7B%0A%20%20%2F%2F%20I%27m%20a%20steamroller%2C%20baby%0A%20%20steamroll(arr)%3B%0A%20%20%0A%20%20return%20res%3B%0A%7D%0A%0Afunction%20steamroll(arr)%7B%0A%20%20%0A%20%20for(var%20i%3D0%3B%20i%3Carr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(Array.isArray(arr%5Bi%5D))%7B%0A%20%20%20%20%20%20steamroll(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20res.push(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A%0Asteamroller(%5B1%2C%20%5B2%5D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//no protect
var res = [];
function steamroller(arr) {
  // I'm a steamroller, baby
  steamroll(arr);
  
  return res;
}

function steamroll(arr){
  
  for(var i=0; i<arr.length; i++){
    if(Array.isArray(arr[i])){
      steamroll(arr[i]);
    }
    else{
      res.push(arr[i]);
    }
  }
}


steamroller([1, [2], [3, [[4]]]]);

```

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by PizzaPalace** [comment]
Thanks. Sorry, but I did not not know about the issue report rules. But the solution appears ok. I tested it on all the cases.
