### ISSUE TITLE
Bonfire: Mutations. A solution that shouldn't have passed

### ISSUE THREAD

**Issue by ivangeorgiew** [FreeCodeCamp/FreeCodeCamp#6173]
Challenge [Bonfire: Mutations](http://www.freecodecamp.com/challenges/bonfire-mutations#?solution=function%20mutation(arr)%20%7B%0A%20%20return%20arr%5B1%5D.toString()%20!%3D%3D%20%22hey%22%20%26%26%20arr%5B1%5D.toString()%20!%3D%3D%20%22neo%22%3B%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
I don't think that was the supposed solution and still it passed :D.

My code:
```javascript
function mutation(arr) {
  return arr[1].toString() !== "hey" && arr[1].toString() !== "neo";
}

mutation(["hello", "hey"]);

```

**Comment by SaintPeter** [comment]
It has always been possible to "game" the tests.  It will likely remain so forever.  Imagine for a moment that we put some code in to check for the strings "hey" and "neo" - then you could encode the strings as ASCII characters, etc.  We deliberately leave the solutions open ended to allow creative problem solving.

Ultimately, the only ones who will be "cheated" are those who don't complete the challenges. Also, if they want this sort of code publicly available on their profiles . . more power to them.

**Comment by ivangeorgiew** [comment]
You are absolutely right I just made it as a joke :D.
