### ISSUE TITLE
Bonfire Caesars Cipher. Getting the right answer.Still not passing.

### ISSUE THREAD

**Issue by kunal047** [FreeCodeCamp/FreeCodeCamp#6174]
![screenshot from 2016-01-15 16 33 19](https://cloud.githubusercontent.com/assets/7374689/12351755/32380434-bba6-11e5-9081-f8bc25854885.png)

Challenge [Bonfire: Caesars Cipher](http://www.freecodecamp.com/challenges/bonfire-caesars-cipher#?solution=var%20st%20%3D%20''%3B%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%7B%0A%20%20%20%20var%20q%20%3D%20str.charCodeAt(i)%3B%0A%20%20%20%20if%20(str.charCodeAt(i)%20%3E%3D%2065%20%26%26%20str.charCodeAt(i)%20%3C%3D%2090)%7B%0A%20%20%20%20%20console.log(st)%3B%0A%20%20%20%20%20%20var%20res%20%3D%20str.charCodeAt(i)%20%2B%2013%3B%0A%20%20%20%20%20%20if(res%20%3E%2090)%7B%0A%20%20%20%20%20%20%20%20var%20v%20%3D%20res%20-%2090%3B%0A%20%20%20%20%20%20%20%20res%20%3D%2064%20%2B%20v%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20var%20val%20%3D%20String.fromCharCode(res)%3B%0A%20%20%20%20%20%20st%20%3D%20st.concat(val)%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20var%20ok%20%3D%20String.fromCharCode(q)%3B%0A%20%20%20%20%20%20st%20%3D%20st.concat(ok)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20return%20st%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20CVMMN!%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var st = '';
function rot13(str) { // LBH QVQ VG!
  for(var i = 0; i < str.length; i++){
    var q = str.charCodeAt(i);
    if (str.charCodeAt(i) >= 65 && str.charCodeAt(i) <= 90){
     console.log(st);
      var res = str.charCodeAt(i) + 13;
      if(res > 90){
        var v = res - 90;
        res = 64 + v;
      }
      var val = String.fromCharCode(res);
      st = st.concat(val);
    }
    else{
      var ok = String.fromCharCode(q);
      st = st.concat(ok);
    }
      
  }
  
  return st;
}

// Change the inputs below to test
rot13("SERR CVMMN!");

```

**Comment by ltegman** [comment]
Creating global variables for function specific storage is a bad idea. Think about what happens when that function is called more than once. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm what you're seeing is actually a bug before creating an issue. Thanks and happy coding!

**Comment by LDWX** [comment]
I have got the same problem. How did you resolve it ?

**Comment by kunal047** [comment]
@LDWX Just by writing `var st = '';` inside function !
