### ISSUE TITLE
Improve spacing on step-style challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6176]
@hallaathrad brought up this point:

![](https://www.evernote.com/l/AqRJx3e7FdJOIKuJda1DSSFow0IHJCAAwIoB/image.png)

**Comment by QuincyLarson** [comment]
Fixed by https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6178

**Comment by howdareu1221** [comment]
I feel that 2b very affective

**Comment by hallaathrad** [comment]
I like that change :).

@howdareu1221 please rephrase?
