### ISSUE TITLE
Code for challenges not showing up in editor

### ISSUE THREAD

**Issue by PossibilityZero** [FreeCodeCamp/FreeCodeCamp#6184]
After the recent update, previously written code for challenges which have not yet been submitted do not show up after selecting the challenge. 

The data is still there in the local storage, so it can (sort of, all in one line) be recovered. It just doesn't show up on the editor.

Come to think of it, this is probably what is making people think they've lost their code for their submitted challenges as well: even though that's saved elsewhere, it doesn't show up when they select the challenges.

**Comment by Greenheart** [comment]
> Come to think of it, this is probably what is making people think they've lost their code for their submitted challenges as well: even though that's saved elsewhere, it doesn't show up when they select the challenges.

This sounds like a possible explanation. Maybe the there were some changes to how the new client works which makes local data from the older app-versions unusable?

**Comment by PossibilityZero** [comment]
@QuincyLarson I think I've figured this out. Looking through my local storage, the new challenges are stored with just their names as the key, whereas the old challenges have "Waypoint: " or "Bonfire: " in front.

**Comment by PossibilityZero** [comment]
There are several ways to deal with this:

1) Changing the naming convention back to the old one:
 This will have the drawback of creating the exact same problem, for people writing code during the different naming convention.

2) Naively looking for old versions of the code if there is no new version
 This could work, but for people that have edited (or perhaps even accessed, I don't know how long it takes before storing in local storage) under the new system, their old solutions would not be accessed.

3) Adding an option to replace the current solution with old versions, for people that have old versions stored.
 As long as there is an undo option, so people can decide to go back if they don't like their old solutions, I feel this is the best. It will however be a backwards-compatibility thorn.

4) Just add a bit of text, or a link to a wiki page explaining how to access local storage and retrieve their old solutions.
 This might be the safest option, but I haven't figured out how to get linebreaks out from local storage, so any code retrieved this way is on one line and needs reformatting.

**Comment by bugron** [comment]
Closed by #6246.
