### ISSUE TITLE
New Buggy Layout?

### ISSUE THREAD

**Issue by pyoo0225** [FreeCodeCamp/FreeCodeCamp#6189]
The new layout for the site is quite buggy. I can select things from the map on the sidebar, but I can't close it. I managed to close it by deleting the map bar with node, but that only works on the current page. Is anyone else having these kinds of issues?

**Comment by bugron** [comment]
@pyoo0225 this is the button that closes the map sidebar.
![](http://i.imgur.com/0wSvdAB.png)

**Comment by pyoo0225** [comment]
@bugron 
![screen shot 2016-01-15 at 11 15 08](https://cloud.githubusercontent.com/assets/16324148/12362636/4808b024-bb79-11e5-8989-90a717491e1b.png)

Now, the map is not showing. Sadly, the button does not work for me, no matter what types of restarts I do. Is there a way to change the layout to the old one?

**Comment by bugron** [comment]
@pyoo0225 are there any errors in your browser's console?

**Comment by pyoo0225** [comment]
@bugron The errors state that there's an issue with the server.
![screen shot 2016-01-15 at 11 20 45](https://cloud.githubusercontent.com/assets/16324148/12362790/09ff5462-bb7a-11e5-8d11-7b35a4cd88ea.png)
![screen shot 2016-01-15 at 11 20 01](https://cloud.githubusercontent.com/assets/16324148/12362791/0a1bd16e-bb7a-11e5-9dac-676758b613c2.png)

**Comment by bugron** [comment]
@pyoo0225 where are you located?

**Comment by pyoo0225** [comment]
@bugron If you're talking about site-wise, I am on Word Blanks for Javascript. If you're talking physical location, I am at school, in CA. Is this, by chance, an issue with the school's firewall?

**Comment by bugron** [comment]
@pyoo0225 yes, that could make sense, try using some browser addon like `Browsec` if it is possible.

**Comment by pyoo0225** [comment]
@bugron do you know how any other addons? I am currently using Safari, so I cannot use browsec

**Comment by bugron** [comment]
@pyoo0225 try to google. I'm on FF.

**Comment by pyoo0225** [comment]
@bugron I think I will try and fix this issue once I am back home. Thanks for now, though

**Comment by ZufengW** [comment]
I had the same issue. I was going to post a "New issue", but I'll leave the details here instead:

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2</code>.

The sidebar appears blank when loading any page on the site. (can't close)
I can click the map button to show the map. (still can't close)
The cross in the upper left doesn't do anything.

However, the sidebar works on <code> Google Chrome Version 47.0.2526.111 (64-bit)</code> on the same computer.

The open sidebar blocks all the buttons behind it and I had to delete it in the web inspector to access them.

**Comment by bugron** [comment]
This seems user specific and depends on the connection. Closing. Feel free to reopen if you still experience problems, thanks.
