### ISSUE TITLE
golfScore(4, 1) results in Hole in One but test is not green

### ISSUE THREAD

**Issue by chris0612** [FreeCodeCamp/FreeCodeCamp#6190]
Challenge [Golf Code](http://www.freecodecamp.com/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(strokes%20%3D%3D%201)%7B%0A%20%20%20%20return%20%22Hole-in-one%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%3D%20par%20-2)%20%7B%0A%20%20%20%20return%20%22Eagle%22%3B%20%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%20par%20-1)%20%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20par)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%20par%20%2B1)%20%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%20par%20%2B2)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Go%20Home!%22%3B%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(4%2C%201)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes == 1){
    return "Hole-in-one";
  } else if (strokes <= par -2) {
    return "Eagle"; 
  } else if (strokes == par -1) {
    return "Birdie";
  } else if (strokes === par) {
    return "Par";
  } else if (strokes == par +1) {
    return "Bogey";
  } else if (strokes == par +2) {
    return "Double Bogey";
  } else {
    return "Go Home!";  
  }
  
  
  // Only change code above this line
}

// Change these values to test
golfScore(4, 1);

```
![screen shot 2016-01-15 at 19 40 14](https://cloud.githubusercontent.com/assets/1708721/12361717/07c48636-bbc0-11e5-93a7-22b2ba47f729.png)

**Comment by chris0612** [comment]
Same goes for golfScore(1, 1)

**Comment by ltegman** [comment]
Make sure your strings you output are an exact match for what the test is looking for. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to make sure what you're seeing is actually a bug. Thanks and happy coding!

**Comment by chris0612** [comment]
Thx!!!!  I will do that.

**Comment by c-daniels** [comment]
Hi @ltegman ,
I have exactly the same issue as @chris0612 (the same exact scoring issues i.e. (4, 1) and (1, 1) do not respond with the correct response as highlighted by Chris' code above). I have checked that my strings are exactly what was requested several times (as I see that Chris missed an exclamation mark etc) and even run the code through Notepad++ which has no issues with logging to the console the correct responses. Am I missing something else? As I believe there is still an unresolved bug on this particular exercise. Thanks for any help you can provide.
Craig

**Comment by AkiraLaine** [comment]
@c-daniels Could you paste your code here?

**Comment by chris0612** [comment]
Hi @c-daniels, have you tried to reset your code. Sometimes it works wonders! or reset your browser cache.

**Comment by BEBEDYDY** [comment]
function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes === 1){return "Hole-in-one!"}
  else if(strokes <= par - 2){return "Eagle"}
  else if(strokes == par - 1){return "Birdie"}
  else if(strokes === par){return "Par"}
  else if(strokes == par + 1){return "Bogey"}
  else if(strokes == par + 2	){return "Double Bogey"}
  else if(strokes >= par + 3){return "Go Home!"}
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);
golfScore(4, 1);
golfScore(5, 2);
golfScore(4, 3);
golfScore(4, 4);
golfScore(1, 1);
golfScore(5, 5);
golfScore(4, 5);
golfScore(4, 7);
golfScore(5, 9);

**Comment by 190898** [comment]
thanks bebedydy

**Comment by dwd2010** [comment]
@BEBEDYDY, this place is not for put answer on here.  You could help people at FreeCodeCamp chat room. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Mohamedsalmaan** [comment]
@BEBEDYDY  Superb

**Comment by vivekshiva4** [comment]
@chrswndrs in your code "Hole-in-one"; you are missing ! this one.
"Hole-in-one!";
