### ISSUE TITLE
Add https encryption to the site

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/FreeCodeCamp#6192]
Even though FCC isn't a site that involves a lot of personal information or money, wounld't it be a great improvement to get an SSL-certificate and enable HTTPS?

Because when I log in using my OAuth-github tokens to your site using http, aren't my access-tokens stored as plain-text cookies in my browser and sent in plain text using http to your servers, which theoretically could be vulnerable to a Man-in-the-middle attack?
Or am I wrong?

No matter the case, I think this would be a huge improvement since it would show that this community really cares about it's users security and integrity.

Keep the great work up! :)

**Comment by jnmorse** [comment]
I think adding SSL would be a decent idea.  Getting a cert is possibly a lot easier now, or least don't necessarily have to shell out a good amount of cash for one.  Let's Encrypt was a project I heard about that lets you get one for free even.

https://letsencrypt.org/

**Comment by ingochris** [comment]
+1 Yes, Let's Encrypt is very easy to use. 
Please, let's enable and maintain SSL for a more secure FCC using this tool: 
https://github.com/letsencrypt/letsencrypt

**Comment by nvnehi** [comment]
Agree, would solve some issues as well(using the https codepen trying to pull data from http fcc causes mixed content errors in firefox for example, thus not allowing it to work despite working in chrome.)

**Comment by jncampbell** [comment]
+1. 

Someone shared a project with HN that allows you to get HTTPS through LetsEncrypt for free. Here's the link: https://news.ycombinator.com/item?id=11002635. One of the creators answered questions in post's comments so it might be worth a read.

**Comment by BerkeleyTrue** [comment]
Thanks everybody. SSL is in the works. 

Happy Coding!

**Comment by Greenheart** [comment]
Great news, keep it up! @BerkeleyTrue

**Comment by abhisekp** [comment]
SSL is not forced in the sign in page http://www.freecodecamp.com/email-signin

**Comment by ltegman** [comment]
@abhisekp This isn't in place yet, it just isn't really a repo issue people can work on, so it was closed.
