### ISSUE TITLE
Twenty-two Solutions missing. Tried hard reset & deleting history. Old solutions missing code.

### ISSUE THREAD

**Issue by carlos-j-arias** [FreeCodeCamp/FreeCodeCamp#6193]
Twenty-two Solutions that I completed today are missing. Tried hard reset & deleting history. The last solution that shows is missing code however it is still marked as completed. I only know I did 22 today because the "calendar streak" shows that number.

**Comment by ltegman** [comment]
I can confirm that I'm not seeing these solutions in his profile. Any ideas @BerkeleyTrue or @QuincyLarson?

**Comment by trueskawka** [comment]
Same here - completed four items today, wanted to share my solutions, no can do.

**Comment by KellenKolbeck** [comment]
My profile shows my last completed solution as "Create a Set of Radio Buttons", which would be about 40 waypoints. However, I've completed over 200 waypoints and am currently in the "Basic JavaScript" section. The points for completing these waypoints are being added to my profile and my progress is shown in the map. The only thing that doesn't seem to be either saving or updating is the solutions to these waypoints.

**Comment by ellemwano** [comment]
Same problem here

**Comment by chrigugegl** [comment]
Same or similar problem here. Lost my streak because my challenges from yesterday were not counted. When I go to my Map or Profile it shows the last challenge I solved before yesterday. Plus, when I signed in yesterday and today, I was redirected not to my last challenge but to the beginning of the onboarding process, as if I were new here. Today is my twelfth day in a row, though.
Thank you for looking into it.
And generally, thank you very much for building and maintaining this platform! I appreciate it.
cheers, chrigugegl

**Comment by chrigugegl** [comment]
Today, the problem persisted. I was sent to onboarding, again. When I went first on my Profile it looked again like I lost my streak and my solved challenges were forgotten. Then I went through my Map to continue solving more than three challenges, realizing that I could continue from where I stopped yesterday. Back on the Profile it now says I have a twelve day streak.

**Comment by trueskawka** [comment]
Newly completed Ziplines appear in the profile.

**Comment by CEREBR4L** [comment]
My solutions are also 3 days behind at this point! 
Hope we get a fix...

**Comment by TheLurkingDev** [comment]
I would very much like to know if the solutions we have completed during this time have been fully lost before proceeding much further. There were a good number of these that I wanted to commit to my notes.

**Comment by trueskawka** [comment]
They weren't lost - I can navigate back to my solutions from map. The only problem is I can't share them, because the links are generic, e.g. http://www.freecodecamp.com/challenges/binary-agents

**Comment by BerkeleyTrue** [comment]
Looks like a bug in display solutions on the map page creeped up after a faulty git rebase. I'll put together a solution.

**Comment by BerkeleyTrue** [comment]
Also, we did not touch any code related to saving solutions. Everything should still be on you user data. It is just not displaying correctly.

**Comment by ingochris** [comment]
I suspect this is associated with the recent retirement of the "Bonfire/Waypoint/Zipline/BaseJump" nomenclature, according to what I've gathered from Gitter.

**Comment by Sockworth** [comment]
I'm a bit late to this party but wanted to add that I'm having similar problems - the work I've completed is marked off as done in my map, but when I click into my solution it isn't there. Has there been a resolution to this?
