### ISSUE TITLE
challenge "Use Abbreviated Hex Code" has code parsing problem

### ISSUE THREAD

**Issue by bumbeishvili** [FreeCodeCamp/FreeCodeCamp#6194]
second test fails for this solution
![untitled](https://cloud.githubusercontent.com/assets/6873202/12366866/552cd414-bbf7-11e5-90db-174b4ee2748c.png)

but when i write semicolon next to abbreviated hex code, without white space, then test passes

**Comment by SaintPeter** [comment]
Confirmed.  Tests need to allow whitespace before semi colon.
