### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by nitiblack** [FreeCodeCamp/FreeCodeCamp#6195]
Challenge [Escape Sequences in Strings](http://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = backslash tab tab carriage-return new-line ; // Change this line



```

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance. Thanks and happy coding!
