### ISSUE TITLE
help me plz

### ISSUE THREAD

**Issue by nitiblack** [FreeCodeCamp/FreeCodeCamp#6197]
Challenge [Word Blanks](http://www.freecodecamp.com/challenges/word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%20%20%0A%0A%20%20%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
    var result = "";
    // Your code below this line
    

    // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by nitiblack** [comment]
how to add these codes
wordBlanks("","","","") should return a string.
wordBlanks("dog", "big", "ran", "quickly") should contain all of the passed words separated by non-word characters (and any additional words in your madlib).
wordBlanks("cat", "little", "hit", "slowly") should contain all of the passed words separated by non-word characters (and any additional words in your madlib).

**Comment by SaintPeter** [comment]
@nitiblack Sorry, but we do not provide code support in issues.  

Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by BEBEDYDY** [comment]
unction wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result = myNoun+ " " + myAdjective + " " + myVerb + " " + myAdverb;

  // Your code above this line
  return result;
  
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
wordBlanks("cat", "little", "hit", "slowly");


here you go.
