### ISSUE TITLE
Color of the 'New' in the map page

### ISSUE THREAD

**Issue by psaiprasant** [FreeCodeCamp/FreeCodeCamp#6200]
In the map page: http://www.freecodecamp.com/map
The color of the 'New' label should be different so that it will help identify the newly added waypoints.

**Comment by SaintPeter** [comment]
Agreed.

**Comment by gasperno** [comment]
The color brown for the label 'New' looks as below. 
![new](https://cloud.githubusercontent.com/assets/7889179/12385368/5320ff2c-bd70-11e5-816d-bd1ee00b8ed3.png)

Any suggestions or approvals?

**Comment by SaintPeter** [comment]
How about a nice slate blue?
![image](https://cloud.githubusercontent.com/assets/553494/12385801/9f30c65a-bd74-11e5-9c03-f2fd94ff88e0.png)

This is the color we're going to be using for links inside the challenges.

**Comment by gasperno** [comment]
Did you mean #3366FF or #737CA1? 
I tried both. I felt that green and slate blue are not complimentary. But I would not consider my opinion the best. I will take you word for it if you suggest a different hex. :)

**Comment by SaintPeter** [comment]
I used `#31708f`

We want to avoid "red" or reddish colors, I think.

**Comment by psaiprasant** [comment]
The objective is to make sure that the color of the word 'New' should be distinct so that it will help the users identify the newly added ones. And I think we can go with the previous slate blue color it looks good even now. 

However this is just my opinion :)

Thanks,
Sai

**Comment by BerkeleyTrue** [comment]
We can use the .info class for these. That class should make the text blue.

**Comment by SaintPeter** [comment]
This is `text-info`:
![image](https://cloud.githubusercontent.com/assets/553494/12407444/3b5c3a4a-be0c-11e5-823e-5af8ba61681d.png)

**Comment by BerkeleyTrue** [comment]
:+1:
