### ISSUE TITLE
Fade completed challenges in map

### ISSUE THREAD

**Issue by sguermond** [FreeCodeCamp/FreeCodeCamp#6202]
Because the text for completed and not completed challenges is the same color and the checkmark is much closer to the text, it is hard to see where you are at a glance. 

I suggest either reusing the faded/not faded styling or making the checkmarks more distinct from the text (by color or placement) for easier distinction.

**Comment by SaintPeter** [comment]
I agree, this would be a good thing to add back in.

**Comment by bugron** [comment]
Closed by https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6354. Thanks for posting.
