### ISSUE TITLE
Can't access profile page

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#6205]
If I click my brownie points or my profile picture, this happens:
![2016-01-16](https://cloud.githubusercontent.com/assets/11958359/12370629/e7f4eb3c-bc6b-11e5-9d00-82c8f861697c.png)

**Comment by SaintPeter** [comment]
When I try to reach your profile page, I get the same error.

@BerkeleyTrue Can you take a look at the server logs, see what is going on here?

http://www.freecodecamp.com/akiralaine
