### ISSUE TITLE
Target the Parent of an Element Using jQuery - No chains allowed??

### ISSUE THREAD

**Issue by ahorton01** [FreeCodeCamp/FreeCodeCamp#6206]
In attempting to test myself a bit, in this challenge I tried to save space by chaining the new instruction to an existing jQuery function, so the first line read:

    $("#target1").css("color", "red").parent().css("background-color", "red");

The code editor had no problem previewing this code with the desired outcome, but the lesson would not pass until I erased the chain and added the complete extra line:

    $("#target1").parent().css("background-color", "red");

OK, so I was getting ahead of myself a little, but don't I get brownie points for simplifying the code? Or at least some acknowledgement that it was not incorrect to do it that way?

**Comment by SaintPeter** [comment]
It can be very challenging to write tests that cover all possible correct solutions.  Unfortunately, we are targeting the "lowest common denominator" here, so we really have to look for code that matches the specific requirements of the waypoint.

So . . . you're right . . but you're too smart for our tests.  Sorry.  :wink:.

Thanks and Happy Coding!
