### ISSUE TITLE
Code Editor: Font Size of Text

### ISSUE THREAD

**Issue by sealocal** [FreeCodeCamp/FreeCodeCamp#6208]
I think it'd be awesome if I could adjust the size of the text inside the code editor - perhaps with a +/- button element that changes this font size value:

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/master/client/less/main.less#L645

**Comment by Greenheart** [comment]
I've used the browser-zoom up until now but this sounds like a good idea.

**Comment by hallaathrad** [comment]
Sounds like something React will be able to help us with ;)
