### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by webdevjedi25** [FreeCodeCamp/freecodecamp#621]
One of the requirements are not fulfilled (Wrap your all of your checkboxes inside one div with the class "row".) even though the codes have fulfilled the requirement. Per checking my code 3 times, I know I have fulfilled the requirement. Kindly check and see if this is just an error on my part. Thank you.

Here are my codes:
===================
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class='row'>
  <div class='col-xs-8'>
    <h2 class='text-primary text-center'>CatPhotoApp</h2>
  </div>
  <div class='col-xs-4'>
    <a href='#'><img class='img-responsive thick-green-border' src='https://bit.ly/fcc-kittens'/></a>
  </div>
</div>
<br>
<img src='http://bit.ly/fcc-kittens2' class='img-responsive'>
<br>
<div class='row'>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-primary'><i class='fa fa-thumbs-up'></i> Like</button>
  </div>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-info'><i class='fa fa-info-circle'></i> Info</button>
  </div>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-danger'><i class='fa fa-trash'></i> Delete</button>
  </div>
</div>
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <br>
  <div class='row'>
    <div class='col-xs-6'>
      <label><input type='radio' name='indoor-outdoor'> Indoor</label>
    </div>
    <div class='col-xs-6'>
      <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
    </div>
  </div>
  <div class="row">
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Loving</label>
    </div>
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Lazy</label>
    </div>
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Crazy</label>
    </div>
  </div>
  <br>
  <div class='col-xs-7'>
    <input type='text' class='form-control' placeholder='cat photo URL' required></div>
  <div class='col-xs-5'>
  <button type='submit' class='btn btn-primary'><i class='fa fa-paper-plane'></i> Submit</button></div>
</form>
===================

Here is a screenshot:

![error](https://cloud.githubusercontent.com/assets/10734660/7830843/8e5963a0-0483-11e5-8a3c-98cc647d60d8.png)

**Comment by webdevjedi25** [comment]
Codes wont appear like in a text editor and it also won't appear if I comment it out. Here are the codes, by the way:

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class='row'>
  <div class='col-xs-8'>
    <h2 class='text-primary text-center'>CatPhotoApp</h2>
  </div>
  <div class='col-xs-4'>
    <a href='#'><img class='img-responsive thick-green-border' src='https://bit.ly/fcc-kittens'/></a>
  </div>
</div>
<br>
<img src='http://bit.ly/fcc-kittens2' class='img-responsive'>
<br>
<div class='row'>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-primary'><i class='fa fa-thumbs-up'></i> Like</button>
  </div>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-info'><i class='fa fa-info-circle'></i> Info</button>
  </div>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-danger'><i class='fa fa-trash'></i> Delete</button>
  </div>
</div>
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <br>
  <div class='row'>
    <div class='col-xs-6'>
      <label><input type='radio' name='indoor-outdoor'> Indoor</label>
    </div>
    <div class='col-xs-6'>
      <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
    </div>
  </div>
  <div class="row">
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Loving</label>
    </div>
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Lazy</label>
    </div>
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Crazy</label>
    </div>
  </div>
  <br>
  <div class='col-xs-7'>
    <input type='text' class='form-control' placeholder='cat photo URL' required></div>
  <div class='col-xs-5'>
  <button type='submit' class='btn btn-primary'><i class='fa fa-paper-plane'></i> Submit</button></div>
</form>

**Comment by webdevjedi25** [comment]
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class='row'>
  <div class='col-xs-8'>
    <h2 class='text-primary text-center'>CatPhotoApp</h2>
  </div>
  <div class='col-xs-4'>
    <a href='#'><img class='img-responsive thick-green-border' src='https://bit.ly/fcc-kittens'/></a>
  </div>
</div>
<br>
<img src='http://bit.ly/fcc-kittens2' class='img-responsive'>
<br>
<div class='row'>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-primary'><i class='fa fa-thumbs-up'></i> Like</button>
  </div>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-info'><i class='fa fa-info-circle'></i> Info</button>
  </div>
  <div class='col-xs-4'>
    <button class='btn btn-block btn-danger'><i class='fa fa-trash'></i> Delete</button>
  </div>
</div>
<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <br>
  <div class='row'>
    <div class='col-xs-6'>
      <label><input type='radio' name='indoor-outdoor'> Indoor</label>
    </div>
    <div class='col-xs-6'>
      <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
    </div>
  </div>
  <div class="row">
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Loving</label>
    </div>
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Lazy</label>
    </div>
    <div class='col-xs-4'><label><input type='checkbox' name='personality'> Crazy</label>
    </div>
  </div>
  <br>
  <div class='col-xs-7'>
    <input type='text' class='form-control' placeholder='cat photo URL' required></div>
  <div class='col-xs-5'>
  <button type='submit' class='btn btn-primary'><i class='fa fa-paper-plane'></i> Submit</button></div>
</form>
-->

**Comment by noinkling** [comment]
That test has a typo, it should tell you to wrap your input field and button in the `.row` div, not the checkboxes.

**Comment by webdevjedi25** [comment]
Alright! That worked! Thank you very much! :)

**Comment by noinkling** [comment]
The "bug" is still present so you can leave it open. If you want to fix it yourself, you can open a pull request. If you look [here](https://github.com/FreeCodeCamp/freecodecamp/blob/master/seed_data/challenges/bootstrap.json#L1190) it seems like an easy fix.

**Comment by webdevjedi25** [comment]
I'm actually lost with Github. Tried opening a pull request but I really don't know where to go. I guess I
ll study Github first?

**Comment by terakilobyte** [comment]
Thanks for bringing this issue up. We've cleaned up the copy!
