### ISSUE TITLE
Chunky Monkey: Infinite Loop is the Solution?

### ISSUE THREAD

**Issue by mtp525** [FreeCodeCamp/FreeCodeCamp#6210]
This is for the chunky monkey bonfire: http://www.freecodecamp.com/challenges/chunky-monkey

I found the solution, but I'm not sure why it works, and why my code (only slightly different), didn't work.  Could someone explain?  The correct solution is:

function chunk(arr, size) {
var newArray = [];
  for (var i=0; i<arr.length; i){
    newArray.push(arr.slice(i,i+=size));
  }
 return newArray; 
}

In the above code's for loop, "i" never increments, and stays 0 the whole time (from what I can tell).  Why would this 1) not be an infinite loop and 2) not keep returning the same array (which would be in this case arr.slice(0,0+size)?

Similarly, I thought my code would be the solution, which changes the for loop slightly:

function chunk(arr, size) {
  
var newArray = [];
  for (var i=0; i<arr.length; i+=size){
    newArray.push(arr.slice(i,i+=size));
  }
 return newArray;
}

In my loop above, "i" increments until it covers the entire length which sounds ilke what the solution should be.  Instead it only returns the first array (arr.slice(0,0+=size)), which is what I thought would happen with the correct code!

Can someone explain to me what's going on here?  Thank you in advance!

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help) or [CodeReview Chat](https://gitter.im/FreeCodeCamp/CodeReview).

Thanks and Happy Coding!
