### ISSUE TITLE
Popular request: create a Night Mode with dark CSS

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6212]
Here's an example of a "night mode wikipedia app": ![](https://lnikki.la/assets/posts/wikipedia-night-mode.jpg?cb=cb8dc03ec07c44cc42966ab77c4a7c06)

Some campers have created unofficial night mode skins for FCC, and I think we can create a good one that can be toggled on campers' code portfolios.

**Comment by alistermada** [comment]
For anyone who wants work on this, you can download a useful Chrome extension called [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?utm_source=chrome-app-launcher-info-dialog) that lets you change a site's CSS live. Very useful for previewing a design.

I'm using it to change FCC's new #FFFFFF background that's searing my eyeballs. :smile:
Nothing wrong with using pure white, but there's just so much white space on some pages I had to darken it a bit for myself.

**Comment by nightwalkerkg** [comment]
I made few "tests" just to see how it will look like. 
![](http://i.imgur.com/eqgprmB.png)
![](http://i.imgur.com/pTmJnxG.png)
![](http://i.imgur.com/EkQHVMp.png)

They are mostly the same with some minor changes.

**Comment by alistermada** [comment]
@nightwalkerkg Looks good! I like the third one as it visually separates instructions from the tests and conditions with a different font color. However, the link in the text ("Mad Libs") is hard to separate from the rest of the text. Would suggest a different color for that.

**Comment by Aoxom** [comment]
![fcc dark](http://i.imgur.com/ZnLTyiV.png)
My simple dark theme!

**Comment by Greenheart** [comment]
@nightwalkerkg I like your third version, but as @alistermada mentioned - change the link color. Also maybe add **a few pixels of padding** to the code-markup in instructions.

@Aoxom Really neat and clean look!

This feature will be a great addition so please keep this up! :)

**Comment by netschki** [comment]
![snapshot2](https://cloud.githubusercontent.com/assets/12996034/12874835/824ab352-cddc-11e5-8337-8c24d5717bf0.png)

Here is my idea

**Comment by hallaathrad** [comment]
I like @netschki's take... the colours seem to match the "light" palette quite nicely. I've been working on a dim one like his as well.

**Comment by Greenheart** [comment]
Nice work @netschki!
But will it be usable by those who need higher contrast? Maybe the text needs to be a bit lighter?

**Comment by netschki** [comment]
@Greenheart Don't mix up these two, we are here speaking of a "Night Mode" not of a high Contrast mode for Accessibility reasons.
And in my Opinion a so called Night Mode shouldn't have strong contrast or even white in it, on the other side a High Contrast Mode, i would make a slightly darker Screen, increase Text Size and make the text white

**Comment by Greenheart** [comment]
@netschki That's a good point! Keep up the good work! :)

**Comment by hallaathrad** [comment]
just as a matter of curiosity, @netschki... you're only changing the colours, right?

**Comment by netschki** [comment]
@hallaathrad yes, but this was only a draft - Would you change more?
the colors i used:
Background color: #2b2b2b2
white Text: #AAAAAA
buttons(Run, Help, etc.): green; text color of the button: #AAAAAA
in the continuous text i removed the background only left the "pink" highlighting

@Greenheart sorry for the harsh tone it was already late and i did not prove read it.
i don't think creating a Contrast Mode is more work then a Night Mode, maybe we can add this, then you have 3 options in the settings (normal, Night, contrast)

**Comment by nightwalkerkg** [comment]
@netschki i like your solution, but i would just make the pink text bolder.
