### ISSUE TITLE
i believe i'ts correct. 

### ISSUE THREAD

**Issue by Necmttn** [FreeCodeCamp/FreeCodeCamp#6215]
Challenge [Understand String Immutability](http://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyStr%20%3D%20%22Hello%20World%22%3B%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myStr = "Jello World";

// Only change code below this line
myStr = "Hello World";
myStr[0] = "H"; // Fix Me



```

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance.
