### ISSUE TITLE
not working.

### ISSUE THREAD

**Issue by Necmttn** [FreeCodeCamp/FreeCodeCamp#6216]
Challenge [Local Scope and Functions](http://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0Aconsole.log(myVar)%3B%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  'use strict';
  
  
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);

// now remove the console log line to pass the test


```

**Comment by ltegman** [comment]
You haven't done what the problem is asking. Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need assistance. Thanks and happy coding!
