### ISSUE TITLE
Multiple identical options in switch-case statements - Bad lesson in my opinon

### ISSUE THREAD

**Issue by OfirLauber** [FreeCodeCamp/FreeCodeCamp#6219]
Hey guys,
I think this challenge does a good job at demonstrating the fact that if you forget the "break;" the next case gets executed.. but, I honestly think you shouldn't teach people using switch-case this way.
I wouldn't allow similar code in my project... "if - else" statements gets it done nicer.
I think this lesson's purpose should be only to demonstrate what happens when you forget using "break;" and it should include a note that you shouldn't write similar code.

Challenge [Multiple Identical Options in Switch Statements](http://www.freecodecamp.com/challenges/multiple-identical-options-in-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch%20(val)%20%7B%0A%20%20%20%20case%201%3A%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Low%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Mid%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20answer%20%3D%20%22High%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case 1:
    case 2:
    case 3:
      answer = "Low";
      break;
    case 4:
    case 5:
    case 6:
      answer = "Mid";
      break;
    case 7:
    case 8:
    case 9:
      answer = "High";
      break;
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(1);


```

**Comment by SaintPeter** [comment]
I agree in general that for this specific example it might be easier to accomplish with an if-else block.  This code really just intended to illustrate the functionality, not to be the perfect use case.  It can be hard to come up with "real world" examples that are simple to explain and illustrate the topic well.

I'd be open to an alternative solution and tests, if you had something to propose.

**Comment by alistermada** [comment]
You can also use switch statements for [multi-case chained operations](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/switch) by allowing case statements to fall through, executing operations until it hits a break. MDN's example might be a little awkward to write using if-else statements.

This might be a better exercise to show a useful case for ignoring a break.

**Comment by SaintPeter** [comment]
@alistermada I think that would actually be way more confusing to new coders.  The use case here is something I've done in production code (obviously not exactly with numbers like this).  I think it's useful.

**Comment by OfirLauber** [comment]
@SaintPeter So actually I disagree, I don't think you should use this use case on production code (I think you should never ignore a break on a switch-case).

My alternative solution is simply adding a note on the instructions:
"Please note this example intends to demonstrate what happens when you forget a "break;",
falling through cases is bad practice, and you should use if-else statements instead"

**Comment by BerkeleyTrue** [comment]
> I don't think you should use this use case on production code

The intent of these challenges is to teach the language. This is valid JavaScript syntax. Adding some note about production assumes you know the project, the production environment, and the team working on the project. I don't think we can or should make these assumptions. 

While I don't like switch statements and they also violate the open/closed principal (see: https://lostechies.com/derickbailey/2014/01/28/killing-switch-statements-with-a-registry-an-example-and-screencast/) I don't think there is anything inherently wrong or anything that needs to be modified with this challenge.

**Comment by SaintPeter** [comment]
@OfirLauber I disagree that it is a bad practice.  To my way of thinking switches are fairly self documenting and certainly a better alternative than a giant chain of if/else statements.

As @BerkeleyTrue said, we are teaching the language.  I believe this is a valid and expected usage of switch statements.

**Comment by tokasravi9000** [comment]
The correct answer is:

switch(val){
    case 1:
    case 2:
    case 3:  
      answer = "Low";
    break;
    
    case 4:
    case 5:
    case 6:  
      answer = "Mid";
    break;
      
    case 7:
    case 8:
    case 9:  
      answer = "High";
      
  }

**Comment by ftcosta** [comment]
I must disagree too. It's efficient, can be formatted to be compact and legible. One can easily tie this example to a real world situation for categories of user ids with distinct permissions for instance. 
```
function sequentialSizes(val) {
  var answer = ""; // Only change code below this line
  switch(val) {
    case 1: case 2: case 3: answer = 'Low' ; break;
    case 4: case 5: case 6: answer = 'Mid' ; break;
    case 7: case 8: case 9: answer = 'High'; break;
  }  // Only change code above this line  
  return answer;  
} // Change this value to test
sequentialSizes(1);
```
