### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue 

### ISSUE THREAD

**Issue by RFenolio** [FreeCodeCamp/freecodecamp#622]
This isn't exactly a bug, but in the description for the challenge, there is an image that shows how bootstrap lays out elements on a page. This image is way too small to see or read any of the text in the image, and there doesn't seem to be a good way to get a larger version of the image.

**Comment by terakilobyte** [comment]
Thanks, we've updated the copy to have the image link to the specific section of the bootstrap website!
