### ISSUE TITLE
New accordion map adds unnecessary complexity, is confusing 

### ISSUE THREAD

**Issue by juggernate** [FreeCodeCamp/FreeCodeCamp#6220]
While the new map folding/accordion functionality makes the initial map view cleaner, it introduces more complexity in getting an overview of where one is what they have completed. 
Where before the user needed to scroll down and just see checked / unchecked, now the user must make several clicks to drill down. If the user wasn't sure where they were before they will need to drill down in several sections to find out.
If a user navigates to an item their place is "lost" when they pull up the map again. If the user wants to visit new items that are interspersed between previously completed items, this makes navigation difficult and time consuming.
If accordion is necessary I would suggest either expanding all items by default, and/or having an expand/contract all button as the map should be a quick way to see progress and navigate therein.

**Comment by Em-Ant** [comment]
I totally agree.

**Comment by juggernate** [comment]
See also issue #6186 Adding completion and certification filters might be a cleaner solution

**Comment by SaintPeter** [comment]
We agree and are actively working all of these issues:
* Progress Bars of some sort are not gone forever - just during this transitional time.
* Automatic opening of the accordion to the current (or last) location is planned.
* All of this will be much faster and cleaner once we finish converting the site to React.

**Comment by juggernate** [comment]
@SaintPeter great to hear! I couldn't find any info and wasn't sure where to look so just wanted to bring it up in case. Thanks!

**Comment by SaintPeter** [comment]
We've got a PR staged right now, #6211, which fixes the auto-scroll.

**Comment by bugron** [comment]
Is this still an issue?

**Comment by juggernate** [comment]
The added expand-collapse all takes makes this much easier to navigate
