### ISSUE TITLE
Increment a Number with Javascript ++ not working properly

### ISSUE THREAD

**Issue by Darla013** [FreeCodeCamp/FreeCodeCamp#6226]
Challenge [Increment a Number with Javascript](http://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%20%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar ++;


```

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by romaan7** [comment]
getting same issue on Chrome it still gives output as 87

**Comment by SaintPeter** [comment]
@romaan7 GitHub Issues are still not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by janschreiber** [comment]
@romaan7 @Darla013 Read the instructions for the challenge very carefully. There is no bug in the challenge.

> The entire line becomes `i++;`

**Comment by sweetvoice78** [comment]
i am having a problem as well.

**Comment by theflametrooper** [comment]
@sweetvoice78 GitHub Issues are still not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by Sharuk06** [comment]
it is ☺☺
var myVar = 87;

// Only change code below this line
myVar++ ;

**Comment by dwd2010** [comment]
@Sharuk06 
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
