### ISSUE TITLE
Redirected to /map-aside on login

### ISSUE THREAD

**Issue by alistermada** [FreeCodeCamp/FreeCodeCamp#6230]
If I click on the map link on the nav to open up the map-aside, close it back, then sign in, I get redirected to http://www.freecodecamp.com/map-aside. Should redirect to http://www.freecodecamp.com/map, I think.

**Comment by SaintPeter** [comment]
I'm having a hard time reproducing this issue.   Can you please go through it step by step?

**Comment by alistermada** [comment]
Assuming you're not logged in:
1. Go to http://www.freecodecamp.com/
2. Click on 'Map' on the navbar.
3. Close the Map-aside that pops up on the right.
4. Click 'Sign In' on the navbar.
5. Sign in. Note: I signed in with Github.

I'm on Chrome by the way.

**Comment by SaintPeter** [comment]
Ok, got it.  Thanks for the excellent instructions.
