### ISSUE TITLE
[Bug] Wrong names of challenges in Profile Page

### ISSUE THREAD

**Issue by aluzardo** [FreeCodeCamp/FreeCodeCamp#6234]
Step to reproduce:

1. Go to an old user profile, for example mine http://www.freecodecamp.com/aluzardo

Expected: Show all the challenges with the correct category name.
Actual: I can see some challenges with the old categories names “Bonfires, Waypoints…”

**Comment by aluzardo** [comment]
This issue could be similar than #6179

**Comment by SaintPeter** [comment]
Closing as duplicate of #6179
