### ISSUE TITLE
Challenge is not accepting the answer

### ISSUE THREAD

**Issue by re4ect** [FreeCodeCamp/FreeCodeCamp#6235]
Challenge  Word Blanks 

my code:

![screenshot-www freecodecamp com 2016-01-16 19-11-24](https://cloud.githubusercontent.com/assets/14848245/12375229/b78041d4-bc86-11e5-9def-cfaaca64bd7b.png)

I have been told I am editing code that should not be edited. But I don't see anything wrong with the code.

**Comment by alistermada** [comment]
Yea, the instructions in the commented code do seem confusing. In reality, the part below where it tells you to "change the words here to test your function" doesn't need to be changed at all for the solution to pass. It's just for testing arguments to the wordBlanks() function and outputting the results on to the console on the left.

The bottom part should remain `wordBlanks([arguments])` where `[arguments]` are the four strings that you want to pass to wordBlanks() to test the output. It could be any four strings you want.

Also, your solution is not correct. Your results shouldn't be outputting the variable names themselves. If you need more help, I recommend going to https://gitter.im/FreeCodeCamp/Help.

**Comment by aluzardo** [comment]
Sorry it is not an Issue is a problem in your code.

You need use the parameters of the function (myNoun, myAdjetive, myVerb, myAdverb) to generate a string.

If you generate the string like this `"myNoun, + myAdjetive, + myVerb, + myAdverb"` your result string is `"myNoun, + myAdjetive, + myVerb, + myAdverb"``

You need put the parameters outside quotes "" for example `result = myNoun+" "+ myAdjetive+" "+ myVerb + " "+ myAdverb;`
One correct solution could be: 

<img width="1430" alt="screen shot 2016-01-17 at 00 46 05" src="https://cloud.githubusercontent.com/assets/11529571/12375304/da4e0f48-bcb3-11e5-9fb1-7682087e99c9.png">

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by siguniang** [comment]
result = myNoun+" "+ myAdjetive+" "+ myVerb + " "+ myAdverb;
why need   +" "+  ,like this?
