### ISSUE TITLE
[Enhancement] Show hours of code in the user profile page

### ISSUE THREAD

**Issue by aluzardo** [FreeCodeCamp/FreeCodeCamp#6236]
Problem: I am not able to see how many hours I have been learning in freecodecamp.

Solution: Show how many hours the users have been learning in freecodecamp in the user page.

**Comment by Greenheart** [comment]
Might be a nice feature, but what time should we track in that case?

* Time online, with FCC-tabs open and active?
* Time actually spent in challenges actively typing?

I think the biggest problem would be to track projects built on for example Cloud9 or CodePen.

**Comment by alistermada** [comment]
One alternative would be to simply get a time value of each challenge completed based on what section of the curriculum that challenge is a part of. 

For example the map states that Basic Front End Development Projects have a time value of 100 hours. There are 4 challenges in that section (not including the introductory "Get Set for our Front End Development Projects"). Therefore completing one challenge in that section would add 25 hours to your record.

Of course, this won't be a very accurate measure of hours spent learning as each camper finishes the projects at different times. It would be mainly to show how much of the 2,080-hour curriculum they've completed and how many more hours of challenges they need to complete.

**Comment by QuincyLarson** [comment]
@aluzardo The problem is much of the coding takes place off of FreeCodeCamp.com - on CodePen, c9.io, and on local computers. So, like @alistermada said, this wouldn't be an accurate measure. We aren't looking for "information", we're looking for "insights".  And giving campers information that isn't accurate or useful is a net negative imho.
