### ISSUE TITLE
Typo, 12-step Introduction Sequence

### ISSUE THREAD

**Issue by corderophilosophy** [FreeCodeCamp/FreeCodeCamp#6238]
![screenshot 2016-01-16 at 7 28 44 pm](https://cloud.githubusercontent.com/assets/16176521/12375245/63750f42-bc87-11e5-8cc3-beb849238749.png)

Text reads: "We have a even offer a job board where employers specifically hire campers who've earned Free Code Camp certifications." 

Should be something like, "We even have a job board..." or "We even offer a job board..." but not both.

**Comment by smarshy** [comment]
Hi, could fix this easily. Which of the two corrections is preferred?

**Comment by SaintPeter** [comment]
How about:
> We even offer a job board where . . .

**Comment by bugron** [comment]
This issue is closed by https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6239.
