### ISSUE TITLE
Using Objects for Lookups

### ISSUE THREAD

**Issue by robwelan** [FreeCodeCamp/FreeCodeCamp#6240]
![screen shot 2016-01-17 at 1 06 00 pm](https://cloud.githubusercontent.com/assets/6440917/12375702/33dfe204-bd1b-11e5-9317-51c31cde51bc.png)
Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Avar%20phoneticLookup%20%3D%20%7B%0A%20%20%22alpha%22%3A%20%22Adams%22%2C%0A%20%20%22bravo%22%3A%20%22Boston%22%2C%0A%20%20%22charlie%22%3A%20%22Chicago%22%2C%0A%20%20%22delta%22%3A%20%22Denver%22%2C%0A%20%20%22echo%22%3A%20%22Easy%22%2C%0A%20%20%22foxtrot%22%3A%20%22Frank%22%0A%7D%3B%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0Avar%20val%20%3D%20%22bravo%22%3B%0Aval%20%3D%20phoneticLookup%5Bval%5D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var phoneticLookup = {
  "alpha": "Adams",
  "bravo": "Boston",
  "charlie": "Chicago",
  "delta": "Denver",
  "echo": "Easy",
  "foxtrot": "Frank"
};

// Change this value to test
var val = "bravo";
val = phoneticLookup[val];

```

**Comment by AkiraLaine** [comment]
You are not suppose to change the whole code. Just change the ```switch``` statement to a lookup table.

If you need help, please go to the [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or the [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is used only for issues.

**Comment by NemanjaMandic** [comment]
Write this:
var result = "";

  var lookap = {
     "alpha": "Adams",
     "bravo": "Boston",
     "charlie": "Chicago",
     "delta": "Denver",
     "echo": "Easy",
     "foxtrot": "Frank"
  };

  return lookap[val];
}

**Comment by mihaelamardare** [comment]
Hello,
I just passed this exercise and I believe that was too tricky.  In the default code you should write that it's ok if you change the **return** command too. I had a hard time because I though I'm not supposed to change it...

**Comment by barbieo37** [comment]
I am having a problem with this because the example does not even show where the "lookup" operation is meant to be. Why have an example if it leaves out what is supposed to be happening?

**Comment by pabl0iD** [comment]
Changing return result; to return lookup[val]; should be allowed

**Comment by anuragpy** [comment]
Even without changing the result we can do it;
Here's the solution--
 // Only change code below this line
var lookup = {
    "alpha" : "Adams",
    "bravo" :"Boston",
    "charlie" : "Chicago",
    "delta" : "Denver",
    "echo" :"Easy",
    "foxtrot":"Frank"
  };
  result = lookup[val];
// Only change code above this line
return result;

**Comment by obentou** [comment]
Agreed, the wording of this is absurdly confusing. Even if the instructions stated something like "use `lookup` to **find** the parameter `val` would have helped to clarify things. FreeCodeCamp has a lot of places like this in their exercises...clearly if enough people are having problems than it in fact is not clear enough. Ugh.

**Comment by claudiocoding** [comment]
..... 
result = lookup[val];
  // Only change code above this line
  return result;
