### ISSUE TITLE
challenge passes a sample test (myBike.gear should remain undefined)

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/FreeCodeCamp#6241]
Challenge [Make Object Properties Private](http://www.freecodecamp.com/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20gear%20%3D%204%3B%0A%0A%0Athis.getGear%20%3D%20function()%7B%0A%20%20%20%20return%20gear%3B%0A%7D%3B%0Athis.setGear%20%3D%20function(change)%7B%0A%20%20%20%20return%20gear%3B%0A%7D%3B%0A%0A%0A%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
var gear = 4;


this.getGear = function(){
    return gear;
};
this.setGear = function(change){
    return gear;
};



};

var myCar = new Car();

var myBike = new Bike();

```

**Comment by SaintPeter** [comment]
What is supposed to be the issue here?  Your code looks correct and it passes.  Do you believe it should not?

**Comment by ltegman** [comment]
@SaintPeter Their `setGear` method isn't actually modifying the variable, they're just setting it to the number the test is expecting so it passes.

**Comment by tommygebru** [comment]
Oh my I have not used my email in soooo long ! Hey Rex, Logan is right some
coders are having a difficult time passing the challenge and copy +pasting
the "loophole" on gitter..... before others have a chance to really
comprehend the challenge!

**Comment by SaintPeter** [comment]
It sounds like we need several other setGear/getGear checks for values other that 4.

**Comment by jestintab** [comment]
@tommygebru Your setGear function is wrong. It should accept the gear value and assign it to the gear variable and getGear fn will return the value.
