### ISSUE TITLE
Bug on Safari "Change the Font Size of an Element"

### ISSUE THREAD

**Issue by jamesbvsh** [FreeCodeCamp/FreeCodeCamp#6242]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by SaintPeter** [comment]
Can you please describe the issue in greater detail?

**Comment by jamesbvsh** [comment]
Sure it's very simple. The above code should pass the code test. Text on the phone displays at 16px, so the rule is being applied correctly. The assignment is to change the phone size of all <p> tags. Could there be a problem with using a web browser other than Chrome? I'm currently running Chrome. Thanks.

**Comment by sludge256** [comment]
Provided code passes for me. Have you tried refreshing the page or restarting your browser? I'm aware of one other person having encountered the same issue on this lesson.

**Comment by SaintPeter** [comment]
@jamesbvsh Are you zooming in or out at all?  We've periodically gotten reports that zooming in or zooming in for the text can break these challenges.

**Comment by jamesbvsh** [comment]
Changing the zoom fixed the issue. That's unfortunate because I have bad eyesight, but I can always just hit ```command + 0``` before submitting

**Comment by SaintPeter** [comment]
There are a very limited number of challenges where this makes a difference.  

It is interesting that this one had the issue because I though we just released a fix for it.  We are currently checking if the font size is 15 or greater.  If it's failing for you when you're zoomed in, I'm wondering what font size it thinks it is.

**Comment by SaintPeter** [comment]
Can anyone dig into this on Safari on Mac - zoom in and see if the code above passes?

**Comment by jamesbvsh** [comment]
Yeah, I can see how that causes a problem. Safari has a weird zoom feature, that usually messes up div positioning, and cuts off edges of words, or moves nav panels over content in dynamic web apps like facebook. I also have an add blocker installed, so don't know if that affects things.

And I would be able to tell you if this was on Chrome, with a quick element inspection. But good luck fixing things and thanks again.

**Comment by Mvk1982** [comment]
have the same problem wit IE11 <style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Mvk1982** [comment]
sorry my copy/paste function is crap. but I have the exact same code and i'm not zoomed in I refreshed the page but it still  won't let me pass.

**Comment by jamesbvsh** [comment]
To format code in comments, try using three quotes on ether side of the code (on the top left).
type ``` ` ```, below the ~ symbol.

**Comment by Ravi-Sankar** [comment]
I am facing the above issue in Internet explorer 11.Can some one please help. I restarted the browser also.

**Comment by SaintPeter** [comment]
@Ravi-Sankar 
I was not able to reproduce this issue in IE 11.  Were you able to pass by resetting your zoom to 100%?  Or are you using the "Text Size" selector?  When I changed that it did not appear to affect the page.

Please give me steps to reproduce.

**Comment by Ravi-Sankar** [comment]
@SaintPeter 
I passed the test by testing in Google Chrome browser. 
And when I tried in internet explorer 11 again today,I still found the issue.Below is the code. Besides I checked my zoom is set at 100%.

Thanks for the reply.
---------------------------------------------

<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

-----------------------

**Comment by SaintPeter** [comment]
Has anyone passed this test in IE and Safari?  I am still unable to reproduce.

**Comment by ltegman** [comment]
I can repro in Safari Mac with one normal zoom-in to the page.

**Comment by SaintPeter** [comment]
Perfect.  So it looks like the test fixes we mad didn't work.

Flagged for fixing.

**Comment by ErinaVidal** [comment]
Has this been fixed yet? I seem to be having the same issue, and Ive tried it on 3 different browsers, checked the code over and over again, but nothing seems to be working.

**Comment by ecmed** [comment]
copy and paste link into safari, make sure browser is zoomed into 100% and zoom in on text aswell. As long as your code is right it will pass. for some reason it wont work in chrome.

**Comment by greencleanique** [comment]
I'm using a windows phone 

-----Original Message-----
