### ISSUE TITLE
Waypoint: Comparisons with the Logical Or Operator

### ISSUE THREAD

**Issue by neal1991** [FreeCodeCamp/FreeCodeCamp#6245]
Challenge [Waypoint: Comparisons with the Logical Or Operator](http://codecamp.ucai.cn/challenges/waypoint-comparisons-with-the-logical-or-operator#?solution=function%20myTest(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%20%20%0A%20%20if%20(val%3C%3D20%26%26val%3E%3D10)%20%7B%0Areturn%20%22Inside%22%3B%0A%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Outside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(15)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
The val is asked to be between 10 and 20. So the logical operator should be "&&" instead of "||".
My code:
```javascript
function myTest(val) {
  // Only change code below this line  
  if (val<=20&&val>=10) {
return "Inside";

  }
  // Only change code above this line
  return "Outside";
}

// Change this value to test
myTest(15);

```

**Comment by SaintPeter** [comment]
The same logic can be written as an Or statement if you reverse your "Inside" and "Outside" labels.

Please follow the instructions.

Thanks and Happy Coding!

**Comment by Usama123456** [comment]
I also have this issue
@SaintPeter your suggestion is not working
`

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
