### ISSUE TITLE
Suggestion: should accept "grey" or "gray" on Give a Background Color to a Div Element (and everything else)

### ISSUE THREAD

**Issue by freecodecamper** [FreeCodeCamp/FreeCodeCamp#6247]
This was previously reported in ##5432.  That issue was closed with the comment that the spec allows only "gray" and a link to the spec.  I believe if you follow the link, it'll show both "grey" and "gray" as acceptable for color x808080.

**Comment by duffn** [comment]
Yes, they should both be acceptable.

https://www.w3.org/TR/css3-color/
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

>Several keywords denote the same colors:
darkgray / darkgrey
darkslategray / darkslategrey
dimgray / dimgrey
lightgray / lightgrey
lightslategray / lightslategrey
gray / grey
slategray / slategrey

**Comment by duffn** [comment]
This was fixed at some point after #5432 was closed. The test is already now
```
"assert($(\".gray-background\").css(\"background-color\") === \"rgb(128, 128, 128)\", 'message: Your <code>div</code> element should have a gray background.');"
```

**Comment by ltegman** [comment]
Closing as not an issue.

**Comment by surfer190** [comment]
Could we remove the requirement of spelling `gray-background` with the american spelling? It should accept a classname of `grey-background`.
