### ISSUE TITLE
Testing Objects for Properties

### ISSUE THREAD

**Issue by moksha1** [FreeCodeCamp/FreeCodeCamp#6249]
Challenge [Testing Objects for Properties]
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.

Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"  };

function checkObj(checkProp) {
  // Your Code Here
  
if (myObj.hasOwnProperty("checkProp")=== true); 
  {return myObj[checkProp];}                                                 
 return "Not Found" ;   }

// Test your code by modifying these values
checkObj("house");

``` 
I'm using a firefox browser and cannot get a screen-shot to paste - sorry.  My issue is the final  'return "Not Found";  ' statement in this exercise will not execute when the condition is false.  I checked the format of this exercise with one from a previous exercise (Chaining If Else Statements), and it is the same basic format once you comment out the extra if-else statements there.  I did not find any other solutions in Git Hub or elsewhere online. I did notice some people used an 'else' in front of ' return "Not Found" ;  ', but when I attempt it, I get an error, otherwise, the editor does not show any other errors for my code.

**Comment by alayek** [comment]
You have a semicolon after the `if` statement.

It should be 
```
if(myObj.hasOwnProperty("checkProp")=== true)
```

You have written 

```
if (myObj.hasOwnProperty("checkProp")=== true); 
```

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by MikeKovacs** [comment]
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  if (myObj.hasOwnProperty(checkProp)) {
    return myObj[checkProp];
  } else {
    return "Not Found";
  }
}

// Test your code by modifying these values
checkObj("gift");

**Comment by MikeKovacs** [comment]
thanks for the help SaintDICK...idiot... don't get involved if you can't/won't help..

**Comment by samsara2011** [comment]
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if (myObj.hasOwnProperty(checkProp)){
      
  return myObj[checkProp];
} else 
    return "Not Found";
  }

// Test your code by modifying these values
checkObj("gift");

**Comment by joufflu** [comment]
Why the brackets in ?

> return myObj[checkProp];

**Comment by GeniaT** [comment]
Hi @joufflu ,

I was wondering the same as I first wrote "**return myObj.checkProp;**" instead of "**return myObj[checkProp];**"
From what I understand, since checkProp isn't a real property here but rather a var representing a property, the 1st way to write doesn't work.

**Comment by Stothetone** [comment]
@GeniaT 
almost correct. checkProp in this case is a String and the dot-notation uses identifiers.

**Comment by jialin128** [comment]
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  return (myObj.hasOwnProperty(checkProp) ? myObj[checkProp] : "Not Found");
}

// Test your code by modifying these values
checkObj("gift");

**Comment by mejiaadonay** [comment]
function checkObj(checkProp) {
  return (myObj.hasOwnProperty(checkProp))? myObj[checkProp] : "Not Found";
}

**Comment by anastasi5** [comment]
OK, this is another example of not getting enough information from the sample code.  Nowhere in there is the suggestion that an if/return/else statement should be used....

**Comment by Tatendaz** [comment]
@anastasi5 come on you can think for yourself, you have learnt everything in the question. ill just drop this for future people looking for help
![screen shot 2016-09-21 at 1 37 07 am](https://cloud.githubusercontent.com/assets/20145676/18692628/eea7cfa0-7f9b-11e6-9d94-f3db8d78b35d.png)

**Comment by texas2010** [comment]
@Tatendaz 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by anastasi5** [comment]
I don't think the question was very clear..  Again, no mention of using the
if/return command... I was going crazy trying to follow the example... I
may switch to codeacademy.

**Comment by JuvasArray** [comment]
The answer could be simplified like that:
function checkObj(checkProp) {
if (myObj.hasOwnProperty(checkProp))
return myObj[checkProp];
else return "Not Found";
}

**Comment by Mongues** [comment]
On Sep 21, 2016 09:14, "Stacey" <notifications@github.com> wrote:
>
> I don't think the question was very clear.. Again, no mention of using the
> if/return command... I was going crazy trying to follow the example... I
> may switch to codeacademy.
>
> On Tue, Sep 20, 2016 at 7:41 PM, Lance <notifications@github.com> wrote:
>
> > @Tatendaz <https://github.com/Tatendaz>
> > Please do not post your solution on here. You could help people at
> > FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on
> > the website only.
> >
> > Happy Coding!
> >
> > —
> > You are receiving this because you were mentioned.
>
> > Reply to this email directly, view it on GitHub
> > <
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6249#issuecomment-248468373

**Comment by majiang666** [comment]
good!

**Comment by oussamajibari** [comment]
the problem was with the double quotes. use if (myObj.hasOwnProperty(checkProp)=== true) instead of if (myObj.hasOwnProperty("checkProp")=== true)

**Comment by adambugaj** [comment]
What would be, if we want to replace 'if/else" with **"switch"** method?

`switch (checkProp) {
    case checkProp:
      myObj.hasOwnProperty(checkProp) === true;
      return myObj[checkProp];
     case checkProp:
      myObj.hasOwnProperty(checkProp) === false;
      return "Not Found";`

"Pony" and "Kitten" works on this code (first part), but the second ("Not Found") does not. Some sugestion to solve it out? ( Is it even permissible to use it with this method? )

**Comment by ronalto7777** [comment]
This is my code:

`// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  var objPro = myObj[checkProp];
  
if(myObj.hasOwnProperty(checkProp)){
   return objPro;
  }
  else
return "Not Found";
}
// Test your code by modifying these values
checkObj("house");
`

it is error because there is wrong semicolon placing (; in) your if (condition);{}

**Comment by nando0204** [comment]
I wouldn't create a new var like ronalto7777 did, "var objPro = myObj[checkProp];"

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  
  if(myObj.hasOwnProperty(checkProp)){
return myObj[checkProp];
}
else
return "Not Found";
}

// Test your code b modifying these values
checkObj("gift");

**Comment by psways** [comment]
flsaf

**Comment by psways** [comment]
I found that both creating a variable and not creating one works:

var objPro = myObj[checkProp];
return objPro;

vs. 

return myObj[checkProp];

What are the benefits of creating a new variable though?? Truly curious and not trying to be rude. Is it so that we can simplify the return statement and make it look cleaner. Would it also help with debugging? Why do this, because some codes in freeCodeCamp does this sometimes too:

var result = "";
var result = lookup[val];
return result;

instead of:

return lookup[val];

???

**Comment by preshin** [comment]
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if(myObj.hasOwnProperty(checkProp))
    return myObj[checkProp];
  else
  return "Not Found";
}

// Test your code by modifying these values
checkObj("gift");
checkObj("pet");
checkObj("house");

this code works !! 
:) :)

**Comment by stanchev88** [comment]
You can even omit === true from the conditional statement since the only output which Boolean datatype produce is either true or false :

if (myObj.hasOwnProperty("checkProp"));
{return myObj[checkProp];}
return "Not Found" ; }

**Comment by shtscompany** [comment]
this is the working code
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
return (myObj.hasOwnProperty(checkProp) ? myObj[checkProp] : "Not Found");
  
  }

// Test your code by modifying these values
checkObj.hasOwnProperty("gift");

**Comment by texas2010** [comment]
@shtscompany  
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Pixiwix** [comment]
I'm not sure where else to put this piece of .02, but honestly, the chat room is NOT helpful.  For people who are really trying hard to put in the effort that it takes to learn to code (for me, with ZERO tech background), it seems like there would be a forum available to help.  This feels like the 50 millionth time I've tried finding help through the forums and it's really offputting to just see moderators telling people to use the (useless and unhelpful) chat room.  It's frustrating learning to code as it is, and this insistence on using a form of "help" that isn't helpful is making it so much worse.

**Comment by munteanu1107** [comment]
A clean solution can be : 

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
      var response = myObj.hasOwnProperty(checkProp);

  return response ? myObj[checkProp] : "Not Found";
}

// Test your code by modifying these values
checkObj("gift");

**Comment by texas2010** [comment]
@munteanu1107 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Apollovishwas** [comment]
why should we use brackets
           return myObj[checkProp];

**Comment by adityagyawali** [comment]
@Apollovishwas to access myObj Properties ...

**Comment by RashidShamsi** [comment]
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
return myObj[checkProp] || "Not Found";
}
// Test your code by modifying these values
checkObj("gift");

**Comment by texas2010** [comment]
@RashidShamsi 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by benjaminspak** [comment]
Dude the no solution rule is really dumb, and you shouldn't enforce it.

**Comment by whzarthur** [comment]
if(myObj.hasOwnProperty(checkProp))
  return myObj[checkProp];
  else
    return "Not Found";

more simple

**Comment by whzarthur** [comment]
`if(myObj.hasOwnProperty(checkProp))
  return myObj[checkProp];
  else
    return "Not Found";`
more simple

**Comment by whzarthur** [comment]
`if(myObj.hasOwnProperty(checkProp))`
 ` return myObj[checkProp];`
`  else`
    `return "Not Found";`
more simple

**Comment by Shejtan** [comment]
Why is this not working?

function checkObj(checkProp) {
  // Your Code Here
  
  return (myObj.hasOwnProperty(checkProp)===true) ? myObj[checkProp] : "Not found";
}
