### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-clean-up-your-form-using-linebreaks has an issue 

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/freecodecamp#625]
Windows 7 PRO SP1 64 bit 
Firefox 38.0.1

When the page is loaded, only the following text shows up but not the whole text. When clicking on the text, all text shows.

Showed text:
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {

--> Screenshot is from issue #626 but it's the same issue so that shouldn't matter
![waypoint_mobile_responsive_images_free_code_camp](https://cloud.githubusercontent.com/assets/11710334/7833162/e6d16e02-0464-11e5-92c2-e19288b13e8d.png)

**Comment by terakilobyte** [comment]
Thanks for the report. I'm closing this issue to track this collective issue is #653
