### ISSUE TITLE
The challenge word blanks needs some fixing (maybe)?

### ISSUE THREAD

**Issue by re4ect** [FreeCodeCamp/FreeCodeCamp#6251]
Challenge:  Word Blanks  [http://www.freecodecamp.com/challenges/word-blanks](Word Blanks)

Now that I finished the challenge I would like to point out some things that make no sense, for example.

1.) Why does the challenge use the cat wordblanks as a example? Its not like the wordblanks are automatically added in the code editor. I just think it would make more sense for the cat wordblanks to be at the bottom where the dog wordblanks are.

2.) Also at the bottom of the code editor the sentence "Change the words here to test your function" makes no sense. Why Does it say change the words here? Shouldn't it say  "Do not change the words here to test your function" (without the quotes of course)?

And another thing is why does the challenge let me pass when the cat word blanks are not in the code editor? 

![screenshot-www freecodecamp com 2016-01-17 06-09-06](https://cloud.githubusercontent.com/assets/14848245/12377220/a9ad16a6-bce3-11e5-8fc2-7704359c5df1.png)

**Comment by re4ect** [comment]
If this challenge does not need fixing than let me know and I will close this.

**Comment by SaintPeter** [comment]
1) When each test is run, your function `wordBlanks` is called with different parameters.  The output is then checked using regular expressions to make sure that the words that were passed in show up in the output that the function generates.

2)  The purpose of the last line is to enable you to test your code - that output will appear in the "output" box above the texts.

I agree that this challenge could use some love, but I'm not sure how to make it clearer.  If you have ever played "Madlibs", this is supposed to be like that.

**Comment by re4ect** [comment]
I'll close it, after all not much can be done about it.

**Comment by nickg33** [comment]
I would say that this challenge seems out of place - function is introduced with no explanation, it seems like you have jumped ahead.

**Comment by siguniang** [comment]
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result=myNoun+" "+myAdjective+" "+myVerb+" "+myAdverb;
  //result="dog, big, ran ,quickly";
  //result="cat, little, hit ,slowly";
  
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
wordBlanks("cat", "little", "hit", "slowly");
