### ISSUE TITLE
Typo: "camelCase" instead of "cameLCase"

### ISSUE THREAD

**Issue by Nipponshin** [FreeCodeCamp/FreeCodeCamp#6252]
Challenge [Understanding Case Sensitivity in Variables](http://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;

```

The issue seems to be only visible, copying and pasting the text gives the right word.
![camelcase](https://cloud.githubusercontent.com/assets/6318505/12377407/e5430e40-bd25-11e5-8950-7905cf69539a.png)

**Comment by abhisekp** [comment]
@Nipponshin the letter `L` is written in lowercase but it just appears block letter due to the font.

**Comment by hallaathrad** [comment]
It's the font stack. @Nipponshin sees menlo or monaco, while @abhisekp sees consola or courier new (for some reason he doesn't see the first two...  linux maybe?)

**Comment by Nipponshin** [comment]
Ha... Interesting. I'm on Windows 10 :D.

On Sun, Jan 17, 2016 at 3:13 PM Justin Richardsson <notifications@github.com>
wrote:

> It's the font stack. @Nipponshin <https://github.com/Nipponshin> sees
> menlo or monaco, while @abhisekp <https://github.com/abhisekp> sees
> consola or courier new (for some reason he doesn't see the first two...
> linux maybe?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6252#issuecomment-172323830>
> .
>
-- 

Jesus Ruppel
sumry.me/nipponshin
<https://sumry.me/nipponshin?ref=email_signature_personal>
<https://sumry.me/nipponshin?ref=email_signature_personal>

**Comment by bugron** [comment]
@Nipponshin thanks for posting. @abhisekp is correct, closing this issue.

**Comment by hallaathrad** [comment]
and then this @nightwalkerkg

**Comment by nightwalkerkg** [comment]
@hallaathrad Consolas font is causing the issue. After removing it the the L looks fine.

**Comment by hallaathrad** [comment]
@nightwalkerkg I thought it was Consolas the one showing a lowercase that looks like it's an upper.

**Comment by nightwalkerkg** [comment]
@hallaathrad Yeah, also it being Italic is just making it worse. :P Just remove it and it should work fine.
