### ISSUE TITLE
Does not accept the answer if you complete the name assignment.  

### ISSUE THREAD

**Issue by orkist** [FreeCodeCamp/FreeCodeCamp#6253]
The instructions are : Instructions
Use the var keyword to create a variable called myName. Set its value to your name, wrapped in double quotes.

The answer only checks out as correct if you create the variable.  If you set a value it is wrong.

Challenge [Declare JavaScript Variables](http://www.freecodecamp.com/challenges/declare-javascript-variables#?solution=%2F%2F%20Example%0Avar%20myName%3B%0A%0A%2F%2F%20Define%20myName%20below%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var myName;

// Define myName below this line


```

**Comment by bugron** [comment]
@orkist thanks for posting this issue!
I've just passed this challenge with your code. Are there any error's in your browsers console? Have you trued resetting your code the the "Reset" button?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by orkist** [comment]
You are welcome!

**Comment by shimaanamara** [comment]
Use the var keyword to create a variable called myName.
