### ISSUE TITLE
Return Entry Pattern for Functions has an issue

### ISSUE THREAD

**Issue by mallikarjun92** [FreeCodeCamp/FreeCodeCamp#6255]
Challenge [Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(a%20%3C%200%20%7C%7C%20b%20%3C%200)%20%7B%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(3%2C3)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  if (a < 0 || b < 0) {
    return "undefined";
  }
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(3,3);

```

**Comment by mallikarjun92** [comment]
Instructions was:
Modify the function abTest so that if a or b are less than 0 the function will immediately exit with a value of undefined.

**Comment by mallikarjun92** [comment]
i cant move to next chapter pls help

**Comment by bugron** [comment]
@mallikarjun92 `undefined` should not be string, remove double quotes. And next time, if you have problems with your code, please, post a message in our [Gitter chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) first, thanks.

**Comment by mallikarjun92** [comment]
thanx!

**Comment by gringogidget** [comment]
This is kind of a silly wording of the question.

> Instructions
> Modify the function abTest so that if a or b are less than 0 the function will immediately exit with a value of undefined.

I would assume this means (a || b > 0); 

Wouldn't it make more sense to say "a as well as b are less than 0", which would be (a > 0 || b > 0);?

**Comment by BEBEDYDY** [comment]
// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if (a < 0 || b < 0) {
    return undefined;
  }
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

**Comment by olquin** [comment]
mallikarjun92 you are more than likely forgetting that undefined is a keyword, not a string.

**Comment by mukai154** [comment]
It's weird... 
I tried putting (a || b < 0) but that doesn't work. 
Wonky...

**Comment by waltervanwoudenberg** [comment]
@mukai154 I had the same thing!

**Comment by topklar** [comment]
this is how i go past that waypoint


// Setup
function abTest(a, b) {
  // Only change code below this line
  if (a < 0 || b < 0){
   return undefined;
  } else { 
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}
} 

// Change values below to test your code
abTest(2,-2);

**Comment by gruvemiami** [comment]
@topklar I literally had the same exact solution as yours, but kept getting syntax error. Mine just had different spacing and line breaks. I copied/pasted yours, and it worked....This problem needs revision.

**Comment by JideLambo** [comment]
I tried using this approach and it didn't work. I believe this is supposed to be correct

// Setup
function abTest(a, b) {
// Only change code below this line
if ((a || b) < 0){
return undefined;
} else { 
// Only change code above this line

return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}
}

// Change values below to test your code
abTest(2,-2);

**Comment by texas2010** [comment]
@JideLambo 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by capuche777** [comment]
This was my code lines and I could go to the next

`// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if (a < 0 || b < 0) {
    return undefined;
  }
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);`

**Comment by killgrey** [comment]
// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if (a<0 || b<0) {
    return;
  }
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(-1,-4);

// Here's mine

**Comment by texas2010** [comment]
@killgrey, Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by adamorlowskipoland** [comment]
@texas2010 
The chat is so messy, and . have so much smartasses you can't get help there.

**Comment by faerthen** [comment]
I agree--that chatroom is a complete disaster. Why can't there just be a chat page for each challenge?

**Comment by rapidfirer56** [comment]
had a hard time with this challenge also because of the instructions wording so i just tried this:

// Setup
function abTest(a, b) {
  // Only change code below this line
 switch(a<0){
   case a<0:
  return undefined;
 }
  switch(b<0){
    case b<0:
      return undefined;
  }
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

**Comment by saadmo** [comment]
Thank goodness I'm not alone, I thought I was dumb for trying (a || b < 0)

**Comment by benjaminspak** [comment]
Okay.. But why is (a < 0 || b < 0) better than (a || b < 0)?

**Comment by jdorman0** [comment]
Guys, I know this is not the medium as you should be [using the chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript), but I see so many people here doing the same thing, so I wanted to point this out. 

Remember that when you use the logical operators, you are actually setting multiple conditions and they evaluate to true or false. 

Example: `if (a || b < 0) return undefined;` that actually evaluates to `if A==TRUE OR b IS LESS THAN 0` which is not the solution you are looking for.  `if ((a||b)<0)` simply isn't a valid conditional statement.

Hope this helps.

_Mod: The only reason I posted this is because this page is a top result for this question and it will likely never die, so my example above is only a hint, not the solution._

**Comment by tokasravi9000** [comment]
The Solution is below:

 // Only change code below this line
   if (a < 0 || b < 0) {
    return undefined;
  }
