### ISSUE TITLE
Blank Panel on Safari

### ISSUE THREAD

**Issue by xTimpi** [FreeCodeCamp/FreeCodeCamp#6256]
Hi,
I just can't use the website with Safari as of the release of the new design.
At any given time there is a blank panel on the right site of the webpage, the only links I can click on are map and chat, they both pop out a new panel that overlaps the blank one, but if I close the panel it does not dismiss the blank one. [Screenshot for clarification](https://imgur.com/Fwk4yjU)

Website works fine on Chrome or Firefox on my computer, so I guess its just an safari Issue?

**Comment by ltegman** [comment]
Huh. We had one report of this when we added the slideout gitter chat a couple months ago but I wasn't able to repro then and I still can't now. Leaving this open in case anyone else can repro and investigate root cause.

**Comment by sludge256** [comment]
Possibly related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6189

**Comment by CoeusCC** [comment]
I noticed it running both Chromium and Midori on a Raspberry Pi. The issue is older browsers do not support the `transform` property. A fallback to the previous behavior via feature detection or simple cascading properties would be sufficient.

**Comment by LXsource** [comment]
Had the same problem on someone else's pc.

The pc I use with Linux/Firefox has no problem.

TEMPORARY SOLUTION: I used an ad blocker and set it to block all of the ASIDE elements. That seems to be working for now and they're proceeding through html/CSS course.

**Comment by hallaathrad** [comment]
Is this issue still going on for anyone? If so, please reach out to me on gitter, and let's see if I can get it over with :)

**Comment by raisedadead** [comment]
Closing as stale.
Please feel free to comment to re-open.

/cc @hallaathrad
