### ISSUE TITLE
comment doesn't work!

### ISSUE THREAD

**Issue by vjs17** [FreeCodeCamp/FreeCodeCamp#6257]
Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?

I have found that i put switch statement in comments(/*....*/) still it didn't pass my last test case which is "You should not use case, switch, or if statements"  unless i delete whole switch statement.
My code:
```javascript
// Setup
function phoneticLookup(val) {
  var result = {
    "alpha": "Adams",
    "bravo": "Boston",
    "charlie": "Chicago",
    "delta": "Denver",
    "echo": "Easy",
    "foxtrot": "Frank"
    //"": "undefined"
  };

  // Only change code below this line
  /*switch(val) {
    case "alpha": 
      result = "Adams";
      break;
    case "bravo": 
      result = "Boston";
      break;
    case "charlie": 
      result = "Chicago";
      break;
    case "delta": 
      result = "Denver";
      break;
    case "echo": 
      result = "Easy";
      break;
    case "foxtrot": 
      result = "Frank";
  }*/

  // Only change code above this line
  return result[val];
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by ltegman** [comment]
There's a reasonable limit to how smart we can make our regex. Making sure they call check that the match it finds isn't inside a comment isn't feasible. I'm sorry for in inconvenience, but in cases like this you'll just have to delete the switch/case code. Thanks and happy coding!
