### ISSUE TITLE
cannot get through the error "Do not change code above the line" in the task checklist.

### ISSUE THREAD

**Issue by ajinkyaT** [FreeCodeCamp/FreeCodeCamp#6258]
Challenge [Storing Values with the Equal Operator](http://www.freecodecamp.com/challenges/storing-values-with-the-equal-operator#?solution=%2F%2F%20Setup%0Avar%20a%3D7%3B%0Avar%20b%20%3D%20a%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var a=7;
var b = a;

// Only change code below this line


```

**Comment by ltegman** [comment]
I'd suggest not changing code above the `// Only change code below this line` line in order to pass the `Do not change code about the line` test. Thanks and happy coding!

**Comment by flemm2016an** [comment]
Hi everyone,

I've tried both ways still won't let me pass challenge... maybe something wrong?

**Comment by Snave713** [comment]
I just noticed that you must only add code and not change it.  

//Only change code below this line
var a = 7;
var b = a;

**Comment by hasaral** [comment]
// Setup
var a;
var b = 2;

// Only change code below this line
a = 7;
b = a;
