### ISSUE TITLE
Local Scope and Functions - doesn't work

### ISSUE THREAD

**Issue by tzupoaia** [FreeCodeCamp/FreeCodeCamp#6259]
Challenge [Local Scope and Functions](http://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20%0A%20%20%20var%20myVar%20%3D%20%22test%22%3B%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0Aconsole.log(myVar)%3B%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  'use strict';
  
   var myVar = "test";  
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);

// now remove the console log line to pass the test


```
href="http://content.screencast.com/users/Pisstt/folders/Default/media/d1d59d3a-6ca0-493b-9910-3c421028f88b/2016-01-17_1925.png"><img class="embeddedObject" src="http://content.screencast.com/users/Pisstt/folders/Default/media/d1d59d3a-6ca0-493b-9910-3c421028f88b/2016-01-17_1925.png" width="600" height="300" border="0" /></a>

**Comment by ltegman** [comment]
```js
// run and check the console 
// myVar is not defined outside of myFunction
console.log(myVar);

// now remove the console log line to pass the test
```
Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for help. Github issues are not for challenge help. Thanks and happy coding!

**Comment by tzupoaia** [comment]
@ltegman As a suggestion on usability, it would be great to update the challenge since it is not clear what you need to do to pass it. You follow the instructions and you expect the output on the left side. The instructions and outcome are always on the left. The challenge asks you to define myVar, you complete the required line then the message shows you that you didn't. I (as user/student) am not used to read the comments on the right side and you are focused between the requirement and the updated line. Then, oh, there is a line to be removed but there is no clue that you need to follow the comments. I didn't notice that. 

At least, it would be great to show the error line. I saw that there was an opened issue regarding the challenge. So, it is not a single case.

Thanks.

**Comment by sandyvern** [comment]
Even when you manage to add a local variable and then follow the directions in the comment to remove the last console line you still can't pass the test....

**Comment by staceygoodwin** [comment]
@sandyvern - I had the same issue and just had to do a refresh and it worked.

**Comment by lwsmallwood** [comment]
Also required a refresh for this to work, did not work initially.

**Comment by erikvangameren** [comment]
I had the same issue

**Comment by erikvangameren** [comment]
Hm. After refresh it worked, thanks!

**Comment by tomengland** [comment]
can confirm this is a bug.  need to refresh in order to pass.

**Comment by Treevil** [comment]
I had the same issue and refresh the page doesn't help me.

**Comment by lmaes** [comment]
Was getting pretty desperate thinking of what I'd done wrong. Thank you commenters for confirming this is a bug. Refresh did it for me.

**Comment by ander-yamamoto** [comment]
I had the same issue.
The code was correct but it was considered wrong.
After a refresh (F5) the same code was considered correct.

I am using Chrome v48.0.2564.109 m
Is there any way to reopen this issue? I think it is definitely a bug!

**Comment by MontyFuss** [comment]
Yep, requires a refresh to make it work.

**Comment by anasufovic** [comment]
Still an issue

**Comment by nikhilb1208** [comment]
Need to refresh to make t work

**Comment by raisedadead** [comment]
Hello Everyone! 
We sincerely apologize for the inconveniences that you all have been facing.

I am not 100% sure how to tackle the Refresh issue that you have been facing ATM, but We are really are open for any way that can help you overcome this.

Coming to the clarification as pointed in the [comment ](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6259#issuecomment-172509910)above by @tzupoaia 
We could address that, along with a possible hint to refresh if you are stuck?

Please let us know what would be the best way.

/cc @FreeCodeCamp/issue-moderators Should we re-open this?

**Comment by raisedadead** [comment]
Note to contributors:

1. Adding additional information in the instructions to go through the Comments might help the confusion.
2. Also add something on the lines to refesh the browser if you are stuck

**Comment by dmsanchez86** [comment]
![camp](https://cloud.githubusercontent.com/assets/8863296/14148916/48e22e16-f667-11e5-9a92-d3d6846b541d.png)

**Comment by raisedadead** [comment]
To consider the [comment here](https://gitter.im/FreeCodeCamp/HelpContributors?at=56fc143ad9b73e635f67b59a) while trying to resolve this?

**Comment by redsherrry** [comment]
stucked in here too

**Comment by rayjon** [comment]
Had to refresh in order to past the tests. There's still a bug here.

**Comment by Kalmuraee** [comment]
+1

**Comment by dreysin82** [comment]
function myLocalScope() {
  'use strict';
  var myVar = "teste";
  
  console.log();
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log();

// Now remove the console log line to pass the test

**Comment by harsiandy** [comment]
+1 

I already removed a line that contain console.log(myVar); and refresh my browser both in Safari and Chrome but still stuck in that Local Scope and Function Challenges.

**Comment by ahkay** [comment]
I had to refresh as well on Chrome

**Comment by ricyoung** [comment]
This is still happing. 
I had to reset the code, redo the code, then refresh, then run tests to make it work.

**Comment by Deryckaus** [comment]
Hey all. i did the refresh . worked like a charm. thanks!

**Comment by ogora** [comment]
Yep this challenge is vaguely worded. Then there is that comment 'use strict' that for newbies like me causes utter confusion. The fact that you have to reset the code and refesh browser does not help. This is like the umpteenth challenge where I had just about given up and came back and tried with same code and worked. without explanation why it failed the first 1000 times i tried . funny that i just wrote 

var myVar = "myVar";  .....and it worked. Then i deleted the second console.log ..and it worked.
