### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue 

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/freecodecamp#626]
Same issue like in #625
Same settings. Attached a screenshot to even better show you guy!

![waypoint_mobile_responsive_images_free_code_camp](https://cloud.githubusercontent.com/assets/11710334/7833153/d749b11a-0464-11e5-9700-811f8962c397.png)

**Comment by terakilobyte** [comment]
closing as a duplicate of #625, thanks!

**Comment by forevermelody** [comment]
I'm having trouble with this waypoint -- is it just me? Or is there a problem?

**Comment by DivaPrincess** [comment]
Appears to be a problem here but no solution yet.🙍🏻

**Comment by forevermelody** [comment]
Aww, bummer - I was on a roll.

**Comment by LumenTeun** [comment]
Since @terakilobyte closed this on May 27, this should be fixed. If you, @forevermelody, need help figuring out what went wrong and suspect it might be an error with your code, @ me on Gitter or ask in our [help chat room](https://gitter.im/FreeCodeCamp/Help).

**Comment by forevermelody** [comment]
Apparently you had to remove the s from the https in the second kitty photo. Thanks!
