### ISSUE TITLE
Introducing Else if Statements has inconsistent spacing

### ISSUE THREAD

**Issue by kkrugler** [FreeCodeCamp/FreeCodeCamp#6262]
In all the other exercises I've seen, there's a space between the 'if' and the opening '(', but not in the starting code for this one:

My code:
```javascript
function myTest(val) {
  if(val > 10) {
    return "Greater than 10";
  }
  
  if(val < 5) {
    return "Smaller than 5";
  }
             
  return "Between 5 and 10";
}
             
// Change this value to test
myTest(7);


```

**Comment by TravisHi** [comment]
Are you asking for help @kkrugler? Or is the Waypoint formatting different to other Waypoints?
