### ISSUE TITLE
Not change global variable

### ISSUE THREAD

**Issue by botika** [FreeCodeCamp/FreeCodeCamp#6263]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch%20(card)%20%7B%0A%20%20%20%20case%202%2C3%2C4%2C5%2C6%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%2C'J'%2C'Q'%2C'K'%2C'A'%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20count%2B(count%20%3E%200%20%3F%20'%20Bet'%20%3A%20'%20Hold')%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  switch (card) {
    case 2,3,4,5,6:
      count++;
      break;
    case 10,'J','Q','K','A':
      count--;
      break;
  }
  
  return count+(count > 0 ? ' Bet' : ' Hold');
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc('K'); cc('A');

```

Not change global variable count.
http://stackoverflow.com/questions/15604177/changing-global-variable-from-within-function

**Comment by SaintPeter** [comment]
The problem with your code has nothing to do with the linked article.  You are not using the `case` syntax properly.

Issues are not for code problems, however you can get help in [HelpJavascript Chat](https://gitter.im/FreeCodeCamp/HelpJavascript).

Thanks and Happy Coding!
