### ISSUE TITLE
Amazon S3 seems to be unresponsive (blocked?) in China

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6266]
![](https://www.evernote.com/l/AqR3C7nursFCybAU36z6-zOcuYgrERdr0M0B/image.png)

@BerkeleyTrue's move to CloudFlare may fix this issue.

**Comment by BerkeleyTrue** [comment]
Cloudflare will not fix this issue since we are serving from amazons servers. It seems like it is temporary and may come back. We will probably have this issue with any CDN we choose unless it is a CDN directly in china
