### ISSUE TITLE
On purpose preceding space in sidebar map section titles?

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6268]
I'm using Chrome and when I open up the Challenge Map sidebar, I noticed this extra space in front of second tier section titles like this when I hover over the text (there's a space in front of `Join`):

![screen shot 2016-01-17 at 20 12 39](https://cloud.githubusercontent.com/assets/2754821/12383123/f1a61296-bd56-11e5-9dce-23978ad8d225.png)

Comparatively, first tier section titles, like `Front End Development Certification`, do not have a preceding space when you hover over it:

![screen shot 2016-01-17 at 20 13 03](https://cloud.githubusercontent.com/assets/2754821/12383138/1931d142-bd57-11e5-83fa-b3966a82ee43.png)

So just wondering if this is a bug or if this was on purpose.

**Comment by bugron** [comment]
@erictleung confirmed. [Lines 24 and 25](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/map/show.jade#L24-L25) just needs to be removed.
