### ISSUE TITLE
Make "collapse all challenges" area on SideCar fixed to top.

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#6276]
I really do like the SideCar (I'm assuming that's what your using) Map menu! It gives really quick access to previous challenges. 
It would cool if the "collapse all challenges" area was fixed to top and everything would slide under it. That way, users wouldn't have to scroll all the way up or down if they're looking for something specific - they would just collapse everything and go to the specific component they're looking for.

**Comment by SaintPeter** [comment]
I agree.  Totally makes sense to have it fixed to the top somehow.

**Comment by codeurge** [comment]
I'm going to start working on this now, should have a PR open shortly.
