### ISSUE TITLE
Passes in JSbin  AND individually. 

### ISSUE THREAD

**Issue by timbec** [FreeCodeCamp/FreeCodeCamp#6277]
I've tested this on JSBin by running all the combinations that don't pass on FCC( golfScore(4, 1), golfScore(1, 1), golfScore(4, 7), golfScore(5, 9). They passed there. Then tested individual combinations on the FCC window itself. Individually, they return the correct result but don't pass on the test list below.  

Challenge [Golf Code](http://www.freecodecamp.com/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(strokes%20%3D%3D%3D%201)%20%20%7B%0A%20%20%20%20return%20'Hole-in-One'%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%3D%20(par%20-%202))%20%7B%0A%20%20%20%20return%20'Eagle'%3B%20%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20(par-1))%20%7B%0A%20%20%20%20return%20'Birdie'%3B%20%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20par)%20%7B%0A%20%20%20%20return%20'Par'%3B%20%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20(par%20%2B%201))%20%7B%0A%20%20%20%20return%20'Bogey'%3B%20%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20(par%2B%202))%20%7B%0A%20%20%20%20return%20'Double%20Bogey'%3B%20%0A%20%20%7D%20else%20if%20(strokes%20%3E%3D%20(par%20%2B%203))%20%7B%0A%20%20%20%20return%20'Go%20Home'%3B%20%0A%20%20%7D%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%209)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes === 1)  {
    return 'Hole-in-One';
  } else if (strokes <= (par - 2)) {
    return 'Eagle'; 
  } else if (strokes === (par-1)) {
    return 'Birdie'; 
  } else if (strokes === par) {
    return 'Par'; 
  } else if (strokes === (par + 1)) {
    return 'Bogey'; 
  } else if (strokes === (par+ 2)) {
    return 'Double Bogey'; 
  } else if (strokes >= (par + 3)) {
    return 'Go Home'; 
  }
  
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 9);

```

**Comment by erictleung** [comment]
Double check your return statements to see if they are returning the correct string according to the given table and the associated tests.

**Comment by timbec** [comment]
Hi, 

  I did before I wrote you and just did so again. This is using the FCC console, Chrome: 

   golfScore(4, 1) returns 'Hole In One'
   golfScore(1, 1) returns 'Hole In One'
   golfScore(4, 7) returns 'Go Home'
   golfScore(5, 9) returns 'Go Home'

   Also checked again in JSBin - same result. I can send you a screenshot if it's easier.

**Comment by SaintPeter** [comment]
Your return statements must match EXACTLY.  They do not.

Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by timbec** [comment]
HI Rex, 

  I'm aware this is not for coding problems. As I said before, this passed in jsbin and, as individual tests, in the FCC console. For good measure, I just tested everything in the Chrome DevTools console and it returned the appropriate content there as well. However, I was not aware that I had to have double quotes around the two return statements for it to pass all the tests at once in FCC. This did NOT apply to the other return statements, which passed - hence that seems to me like a bug. Maybe a simple statement saying the return statement  (ie text) must be copied exactly as in the example would be helpful to anyone else who comes after me. To my knowledge this hasn't been an issue before with FCC, unlike with Codeacademy for example. 

   Best, 

   Tim

**Comment by ltegman** [comment]
@timbec the problem wasn't the single quotes. The actual string you were returning in some cases did not exactly match the text you were asked to return.

**Comment by Joll59** [comment]
@timbec did you ever figure this out? your "Hole-in-One"  string is missing "!" at the end.("Hole-in-One**!**") Same goes for "Go Home" it should be "Go Home**!**" i had the same exact problem initially.

**Comment by timbec** [comment]
@Joll59 Well, it passed with this. Note the double quotes on first and last and single quotes in-between. So that's something that probably should be fixed, can be confusing when you're starting out trying to figure out what's wrong and it's just a string that wasn't formatted properly:

 function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes === 1)  {
    return "Hole-in-one!";
  } else if (strokes <= (par - 2)) {
    return 'Eagle'; 
  } else if (strokes === (par-1)) {
    return 'Birdie'; 
  } else if (strokes === par) {
    return 'Par'; 
  } else if (strokes === (par + 1)) {
    return 'Bogey'; 
  } else if (strokes === (par + 2)) {
    return 'Double Bogey'; 
  } else if (strokes >= (par + 3)) {
    return "Go Home!"; 
  }
  
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(4, 1);
golfScore(1, 1);
golfScore(4, 7);
golfScore(5, 9);

**Comment by sdiscul4** [comment]
here is the correct answer

function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes == 1)
    return "Hole-in-one!";
  else if (strokes <= (par - 2))
    return "Eagle";
  else if (strokes == (par - 1))
    return "Birdie";
  else if (strokes == par)
    return "Par";
  else if (strokes == (par + 1))
    return "Bogey";
  else if (strokes == (par + 2))
    return "Double Bogey";
  else if (strokes  >= (par + 3))
    return "Go Home!";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

**Comment by sdiscul4** [comment]
happy coding
