### ISSUE TITLE
Challenge requires more test cases.

### ISSUE THREAD

**Issue by hannahourani** [FreeCodeCamp/FreeCodeCamp#6279]
Challenge [Slasher Flick](http://www.freecodecamp.com/challenges/slasher-flick#?solution=function%20slasher(arr%2C%20howMany)%20%7B%0A%20%20%2F%2F%20it%20doesn't%20always%20pay%20to%20be%20first%0A%20%20if%20(howMany%3E%20arr.length)%7B%0A%20%20%20%20%0A%20%20%20%20return%20%5B%5D%3B%0A%20%20%7Delse%20if%20(howMany%20%3D%3D%3D%200)%7B%0A%20%20%20%20%0A%20%20return%20arr%3B%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%7Delse%7B%0A%20%20%20%20%0A%2F%2F%20%20%20%20return%20arr.slice(arr.length%20-%20howMany%2B1%2C%20arr.length)%3B%0A%20%20%20%20return%20%5B3%5D%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0Aslasher(%5B1%2C%202%2C%203%2C4%2C4%2C4%2C4%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function slasher(arr, howMany) {
  // it doesn't always pay to be first
  if (howMany> arr.length){
    
    return [];
  }else if (howMany === 0){
    
  return arr;
    
    
  }else{
    
//    return arr.slice(arr.length - howMany+1, arr.length);
    return [3];
  }
  
}

slasher([1, 2, 3,4,4,4,4], 2);

```
using a simple conditional, the challenge can be beaten by non-functional code (sometimes accidentally). A few other conditions for the exercise's success could help avert that.

**Comment by SaintPeter** [comment]
Humm, you might be right.

Do you have some proposals for alternate tests that might be a bit more exhaustive?

**Comment by hannahourani** [comment]
I think it might help to have an extra test array that contains strings too. This way, if the users accidentally lands on a 3, there would still be another test case to beat.

I don't think we can account for users faking the results using conditional if they do it on purpose but at least this should stop accidental false positives.

What do you think?

And thanks for the course, really helping me get back up to speed :+1:

**Comment by SaintPeter** [comment]
That seems reasonable to me.

**Comment by ChristianLapinig** [comment]
So something like:
```
slasher(["burgers", "fries", "shake"], 1);
slasher([1, 2, "chicken", 4, "potatoes", "cheese", 5], 5);
```

**Comment by SaintPeter** [comment]
Yup, those would work.

You'll need `assert.deepEqual` to compare arrays.

**Comment by ChristianLapinig** [comment]
Sounds good
