### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text has an issue 

### ISSUE THREAD

**Issue by balajivijayan** [FreeCodeCamp/freecodecamp#628]
Clicking on "Go to my next challenge" leads to waypoints in Basic Algorithm Scripting instead of waypoints in "Basic HTML5 and CSS"

**Comment by terakilobyte** [comment]
I'm unable to reproduce this issue in chrome and firefox. We tightened up some loose code, but if this happens again please reopen the issue.
