### ISSUE TITLE
Improvement concerning Challenge Map visualisation

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#6280]
What do you think about visualizing Challenge Map using SVG libraries?
For example, Raphael.js has a map demo which can be taken as a concept: http://raphaeljs.com/australia.html
Some thoughts on jQuery SVG vs. Raphael: http://stackoverflow.com/questions/588718/jquery-svg-vs-raphael

**Comment by SaintPeter** [comment]
I'm not sure what you had in mind.  It's basically a bullet pointed list.  It's intended to be traversed linearly.  Do you have a specific example of such a list being displayed in some innovative way?

**Comment by rfprod** [comment]
Well, yes, technically it is a bullet pointed list (just like tasks list when one plays a single player strategy game with a linear plot), but it can be visualized as an actual map. Consider it data visualization.

**Comment by SaintPeter** [comment]
Sure - I'm just asking for an example.  

I mean, you could do some sort of node for each section/sub-section, with challenges hanging off them, but that removes the linear nature of the curriculum.  Many challenges are specifically intended to be done in sequence.

I'm not opposed to anything that would increase clarity for users, especially if it's nifty and uses cool web features (I love SVG), but the idea "use graphics" is not actionable for me.

**Comment by rfprod** [comment]
One more not: This map should not offer a user to select a task (not to break sequential nature), just to view progress in a fancy way at a glance.

**Comment by rfprod** [comment]
[Understanding the GitHub Flow] (https://guides.github.com/introduction/flow/index.html) is a brief example of how it may work (but SVG elements should only represent previous events as a result of user actions, not invoke any; and SVG elements corresponding completed tasks should differ in, for example, color from uncompleted).

**Comment by SaintPeter** [comment]
I'll take your suggestion under advisement.  If you come up with any brilliant additions, please let us know.  

Thanks and Happy Coding!
