### ISSUE TITLE
Very subtle change in font in instructions

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6282]
Challenge [Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function myFunction() {

  // Only change code below this line.

  return Math.random();
}

```

If you look closely, the paragraph before and after the ordered list are different sizes. The code that generates this has those two paragraphs and the order list in one string. It might help to split them up into three separate strings to make it easier to read the code itself later.

![image](https://cloud.githubusercontent.com/assets/2754821/12400400/aa5745f8-bdd4-11e5-9f55-0aeb65bab563.png)

**Comment by SaintPeter** [comment]
Very subtle.  Definitely there.

The issue is that the text following the `ol` element is not being wrapped.  A simple line break should fix  that.  The secondary issue is that the `ol` needs to be defined as 16pt for challenges.  This can be found in `challenge.less`.
