### ISSUE TITLE
Unnecessary code tagged strings within blockquote tags

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6283]
[Access MultiDimensional Arrays With Indexes](http://www.freecodecamp.com/challenges/access-multidimensional-arrays-with-indexes) and [Understand String Immutability](http://www.freecodecamp.com/challenges/understand-string-immutability) have text in code tags within a blockquote already. The code tagged strings need to be removed. You can see them because they are highlighted again within the code block.

Access MultiDimensional Arrays with Indexes:

![image](https://cloud.githubusercontent.com/assets/2754821/12400794/13efe982-bdd7-11e5-990f-7971015a0f79.png)

Understand String Immutability: 

![image](https://cloud.githubusercontent.com/assets/2754821/12400806/22fbf7a4-bdd7-11e5-80c1-7f14fd9b2a35.png)

**Comment by SaintPeter** [comment]
Agreed, these just just be in the block quote.
