### ISSUE TITLE
Local instance cannot access Javascript challenges

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6284]
For some reason, my local instance cannot load any Javascript challenges, except for the first one, Comment your JavaScript Code. I can view all the other section challenges.

Whenever I try loading a Javascript challenge in my browser, my `gulp` window looks like its looping around a lot and cannot find the challenge.

Here I have opened the side map (`/map-aside`) and clicked on Understand Boolean Values and it tries to take me to Declare Javascript Variables, which is the challenge right after Understand Boolean Values. It then just continues to cascade and tries looking for things.

![image](https://cloud.githubusercontent.com/assets/2754821/12401245/18cd9d34-bdda-11e5-83c6-33d5a7b6d7bf.png)

I checked the live version and it seems that Understand Boolean Values is a new challenge or something got moved around.

**Live version**:

![image](https://cloud.githubusercontent.com/assets/2754821/12401400/f711eeec-bdda-11e5-8a5a-c38cea339b0d.png)

**Development Version**:

![image](https://cloud.githubusercontent.com/assets/2754821/12401413/0a2ca3dc-bddb-11e5-9130-ef3c06935c77.png)

I rebased my local instance and ran `npm install` and `bower install` to make sure things are most up-to-date.

Not sure if this is related but when starting up `gulp`, I get this red message:

![image](https://cloud.githubusercontent.com/assets/2754821/12401561/14671656-bddc-11e5-9905-c12a9bb1f4fb.png)

My setup:
- Mac OS X
- Chrome 47.0.2526
- npm 3.5.2
- node 4.2.4
- bower 1.7.2
- gulp 3.9.0
- mongod 3.0.7

**Comment by BerkeleyTrue** [comment]
Please remove and re-install your npm dependencies.

**Comment by erictleung** [comment]
I no longer get that red message but it still is looping around trying to find the correct Javascript challenge. It keeps on looking for the next challenge below it in the map and goes into this almost infinite loop.

**Comment by BerkeleyTrue** [comment]
Did you re-seed after re-install npm deps?

**Comment by erictleung** [comment]
Ah I didn't. I just did and everything works now. I guess my local seeded database was a little out of sync or something. Thanks @BerkeleyTrue!
