### ISSUE TITLE
commented if/else statement is still evaluated in "Replacing If Else Chains with Switch" section

### ISSUE THREAD

**Issue by mellisa1234** [FreeCodeCamp/FreeCodeCamp#6285]
If I don't erase all the if/else statement, the coding won't pass the test. 

Even though my answer was right, the commented if/else is still being tested by the program.
I mean something like this :
```
 /*
  if(val === "bob") {
    answer = "Marley";
  } else if(val === 42) {
    answer = "The Answer";
  } else if(val === 1) {
    answer = "There is no #1";
  } else if(val === 99) {
    answer = "Missed me by this much!";
  } else if(val === 7) {
    answer = "Ate Nine";
  }
  */
```

**Comment by SaintPeter** [comment]
You are correct.  Unfortunately our tests can't parse JavaScript to ignore things in comments.  There is a limit to the complexity of our testing system.  

Sorry, can't reasonably fix this.

Thanks and Happy Coding!
