### ISSUE TITLE
Set the Font Family of an Element passes with incorrect code

### ISSUE THREAD

**Issue by rphares** [FreeCodeCamp/FreeCodeCamp#6286]
A camper pointed out that this challenge can be passed with the following code:

```
var code = "formatted";
<style>
  .red-text {
    color: red;
    font-family: Monospace;
  }

  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

This does not meet the objectives of the lesson (*make all of your p elements use the Monospace font*), but both Takumar and I were able to recreate the issue.

Suggested solution: adjusting the test
```
"tests": [
        "assert($(\"p\").css(\"font-family\").match(/monospace/i), 'Your <code>p</code> elements should use the font <code>Monospace</code>.')"
      ]
```

When discussing with Takumar, he found that the next challenge, "Import a Google Font", has a similar test and could also be adjusted. (I did not verify his finding, as i don't know how to check the tests, but trust his assessment :) )

**Comment by SaintPeter** [comment]
I agree, this needs to be fixed.  @rphares - this is your chance!  You can fix this and file a PR!  It'll be epic!

**Comment by JayaDarby** [comment]
I would like to work on this issue if possible.

**Comment by SaintPeter** [comment]
Go for it @JayaDarby!  I was just giving @rphares a hard time.  :wink:

**Comment by JayaDarby** [comment]
Ok I will fix this today.

**Comment by robjloranger** [comment]
I have a fix I think, but can't test yet cause I have to head to work and couldn't get mongo installed in time.
https://github.com/robjloranger/FreeCodeCamp/tree/fix/%236286_font-family
