### ISSUE TITLE
Run Tests button is unresponsive

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/FreeCodeCamp#6287]
Challenge [Title Case a Sentence](http://www.freecodecamp.com/challenges/title-case-a-sentence) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  return str.toLowerCase().split("");
}

titleCase("I'm a little tea pot");

```

**Comment by farazfazli** [comment]
Your code is incorrect. Please read the requirements:

titleCase("I'm a little tea pot") should return a string.
titleCase("I'm a little tea pot") should return "I'm A Little Tea Pot".
titleCase("sHoRt AnD sToUt") should return "Short And Stout".
titleCase("HERE IS MY HANDLE HERE IS MY SPOUT") should return "Here Is My Handle Here Is My Spout". 

Your output:
["i","'","m"," ","a"," ","l","i","t","t","l","e"," ","t","e","a"," ","p","o","t"]

**Comment by SerhiiLihus** [comment]
```js
function titleCase(str) {
  return str.toLowerCase().split("");
}
```

First of all you need to return a string. In your code, after using **split('')** you'll receive array of lower cased **letters**, and spaces. Use **split(" ")** to divide string only by **spaces** between words.

Algorithm:
You need to walk through the array and change first letter in each word, and concatante it with the rest of the word. After that use **join(" ")**, to return modified string.

Here is the working sample of code that passed all given tests:
```js
function titleCase(str) {
  return str.split(' ').map(function(value){
    return value.charAt(0).toUpperCase() + value.substr(1).toLowerCase();
  }).join(' ');
}
```

**Comment by ltegman** [comment]
In the future please make sure that what you're seeing is a problem with the site and not your solution by getting a second opinion in the [Help Chat](https://gitter.im/FreeCodeCamp/Help). Thanks and happy coding!
