### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue 

### ISSUE THREAD

**Issue by amuganda** [FreeCodeCamp/freecodecamp#629]
Please tell us in detail here how we can make this challenge better.
![bug]

![bug](https://cloud.githubusercontent.com/assets/11375264/7833513/4dcd58d8-045f-11e5-8552-73a4dcdadd12.PNG)

Just a small suggestion as there are very few instances where HTML can be completed without a closing tag. Challenge is marked as complete I've only added <a href"#"  but I am allowed to move on. I think to make it a passing solution the element should be wrapped inside an anchor element. 

Given a coder enters Waypoint 629 and wishes to complete the task
When wrapping the img with anchor tags 
and
giving the href attribute the dummy link "#" 
Then the challenge is marked as complete

**Comment by terakilobyte** [comment]
Thanks for the report, this has been addressed in a referenced commit!
