### ISSUE TITLE
Waypoint: Adding a default option in Switch statements

### ISSUE THREAD

**Issue by jayuhasz** [FreeCodeCamp/FreeCodeCamp#6294]
Challenge [Adding a default option in Switch statements](http://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.

Statement 1 should have a semi-colon in the example similar to the line ending semi-colon for Statement 2.

**Comment by SaintPeter** [comment]
Darnit, thought we fixed that one.

**Comment by zicmic** [comment]
i think there is still some issue !

**Comment by SaintPeter** [comment]
@zicmic You're welcome to open another issue with your code, but I strongly encourage you to ask for help in [Help JavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to get confirmation of the bug before you open an issue.  We see many issues opened for "site bugs" where it's simply a programming error.

Thanks and Happy Coding!

**Comment by W12S12E12** [comment]
https://github.com/mcfly-io/generator-mcfly

**Comment by susanwinters214** [comment]
It's not working for me either. It drops to default every time.
``function myTest(val) {
 var answer = "";
  // Only change code below this line
  switch(answer) {
    case "a":
      answer="apple"; 
      break;
    case "b":
      answer="bird"; 
      break;
    case "c":
      answer="cat"; 
      break;
   default:
      answer="stuff"; 
      break;
        }
    
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest("b");

**Comment by CDEguia** [comment]
This appears to be a code issues  try changing the
switch(answer)
To
switch(val)

Candelario Daniel Eguia

University of La Verne 2016
Computer Science and Engineering in Software

**Comment by BEBEDYDY** [comment]
unction switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch (val){
    case "a":
      answer = "apple";
      break;
    case "b":
      answer = "bird";
      break;
    case "c":
      answer ="cat";
      break;
    default:
      answer ="stuff";
      
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(c);

**Comment by HarleyGreaves** [comment]
Was this issue ever resolved? 
I am having the same issue, 
whether i change switch to val or answer i still get the reference error
function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case a:
      answer = "apple";
      break;
    case b:
      answer = "bird";
      break;
    case c:
      answer = "cat";
      break;
    default:
      answer = "stuff";
  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(1);

**Comment by erictleung** [comment]
@HarleyGreaves if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by raphaeldv** [comment]
@HarleyGreaves 

Works for me, try adding CASE  "a" , "b", "c" to your code and it will work

**Comment by duodushu** [comment]
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case "a":
      answer="apple";
      break;
    case b:
      answer="bird";
      break;
    case c:
      answer="cat";
      break;
    default:
      answer="stuff";
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(1);

**Comment by theWhiteFox** [comment]
There is no need to make so many changes to the code.
*Hint* what is the `(val)` you are trying to match.
`// Change this value to test
switchOfStuff("a");`

**Comment by ShaunBastin** [comment]
People keep saying use the help forum but the help forum is not viewable on my i6s phone.

**Comment by MihaelaMarinca** [comment]
the only mistake that usually all of us is that we tried to invoke the function **switchOfStuff(with the wrong value)**. Remember: the solution: 
 !! switchOfStuff("b"); !! --> the case "b", or "c" or "a". (not a, b, or c,or 1, or another values.)

the correct result:


function switchOfStuff(val) {
  var answer = val;
  // Only change code below this line
switch (answer){
  case "a":
      answer = "apple";
      break;

  case "b":
      answer = "bird";
      break;
  
  case "c":
      answer = "cat";
      break;
  
  default:
      answer =  "stuff";
}
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff("b");

**Comment by gordonms1** [comment]
var answer = ""; (Is fine and should not be changed.)

Switch should look like this:

switch (val) 

I saw that everyone, even myself, was using (answer) instead of (val). Use (val) Your code should work then.
