### ISSUE TITLE
Map shows Oradell, Nevada, United States instead of Oradell, New Jersey, United States

### ISSUE THREAD

**Issue by farazfazli** [FreeCodeCamp/FreeCodeCamp#6295]
The [FreeCodeCamp cities map](https://www.google.com/maps/d/u/0/embed?mid=zH0hxoM17_fk.kDBMlxfk0BZ8) says "Oradell, Nevada" even though Oradell is in New Jersey. It is pointing to the correct location but the location text is wrong in the csv file.
 
![Wrong Text](http://i.imgur.com/XDTqfhh.jpg)
![Oradell, Nevada](http://i.imgur.com/Izo2K0V.jpg)

**Comment by bugron** [comment]
@hallaathrad can you check this, please?

**Comment by hallaathrad** [comment]
fixed! Thanks for letting me know @farazfazli

**Comment by farazfazli** [comment]
You're welcome @hallaathrad! :smiley:
