### ISSUE TITLE
Title case a sentence: Issue with strict mode

### ISSUE THREAD

**Issue by dstarr1492** [FreeCodeCamp/FreeCodeCamp#6297]
```js
function titleCase(str) {
  
str = str.split(" ");

  for (var i = 0; i < str.length; i++){
    
 str[i][0] =  str[i][0].toUpperCase();
  }
  

  return str;
}

titleCase("I'm a little tea pot");
```
I keep receiving an error message that reads: Assignment to read-only properties is not allowed in strict mode but I never declared a strict mode at the beginning of my code

**Comment by ltegman** [comment]
Our code execution runs in strict mode. You are trying to mutate a string, which is an immutable data type. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for further help.

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
