### ISSUE TITLE
Waypoint: Accessing Objects Properties with the Dot Operator

### ISSUE THREAD

**Issue by jayuhasz** [FreeCodeCamp/FreeCodeCamp#6298]
Challenge [Accessing Objects Properties with the Dot Operator](http://www.freecodecamp.com/challenges/accessing-objects-properties-with-the-dot-operator#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20%22hat%22%3A%20%22ballcap%22%2C%0A%20%20%22shirt%22%3A%20%22jersey%22%2C%0A%20%20%22shoes%22%3A%20%22cleats%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AhatValue%20%3D%20testObj.hat%3B%20%20%20%20%20%20%2F%2F%20Change%20this%20line%0AshirtValue%20%3D%20testObj.shirt%3B%20%20%20%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
This waypoint is not very clear in what's being requested. You are being asked to declare certain variables without being told what to name the variables in the instructions.

My code:
```javascript
// Setup
var testObj = {
  "hat": "ballcap",
  "shirt": "jersey",
  "shoes": "cleats"
};

// Only change code below this line

hatValue = testObj.hat;      // Change this line
shirtValue = testObj.shirt;    // Change this line

```

**Comment by alistermada** [comment]
I don't think you're supposed to declare any new variables. I just reset the code on the Waypoint and I see that hatValue and shirtValue are already declared:

```javascript
// Setup
var testObj = {
  "hat": "ballcap",
  "shirt": "jersey",
  "shoes": "cleats"
};

// Only change code below this line

var hatValue = testObj;      // Change this line
var shirtValue = testObj;    // Change this line

```

The conditions for passing the tests (in the bottom left of the page) clearly tell you what the value of what hatValue and shirtValue should be and that dot notation should be used.

**Comment by erictleung** [comment]
I think there are two things that are making this challenge a little confusing: the example code and what is being asked for.

The example code can be changed to look like so:

```
var myObj = {
  prop1: "val1",
  prop2: "val2"
};
var prop1val = myObj.prop1; // val1
var prop2val = myObj.prop2; // val2
```

This way, it doesn't confuse the camper on why there's a `var` in the editor.

Secondly, the instructions can be changed to:

> Read in the property values of `testObj` using dot notation. Set the property `hat` to the variable `hatValue` and the property `shirt` to `shirtValue`.

Thoughts?

**Comment by SaintPeter** [comment]
@erictleung I'm game.  We have enough confused people in the help channels on this one, I'm willing to try anything.

**Comment by sethspearman** [comment]
Actually I think that this...
"Set the property hat to the variable hatValue and the property shirt to shirtValue."...
Should read like this...
"Set the variable hatValue to the property hat and the  property shirt to variable shirtValue to the property shirt.

I think this is the only way it can work if you only modify the two referenced change lines.  

Am  I right ?

**Comment by 4mifix** [comment]
This one gave me hell and I remember it well. @erictleung that fix may work better to clarify what is asked for to complete the challenge.

**Comment by erictleung** [comment]
Mmm I agree. Reading it more carefully, I can see how the instructions can be misinterpreted. We can open this up again and myself or anyone else can rewrite this to something like:

> Set the variable `hatValue` equal to the object property `hat` and set the variable `shirtValue` to equal the object property `shirt`.

**Comment by sethspearman** [comment]
Eric, that wording would work well.

Seth

**Comment by W12S12E12** [comment]
for java http://stackoverflow.com/questions/3920928/java-objects-instanceof?answertab=active

**Comment by bravo1c** [comment]
i have to say i complely agree with you all, i was stuck on this wondering why this wasn't working.

**Comment by patribezek** [comment]
It worked! I couldn't pass until i reset my code and do this:

`// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;       // Change this Line
var player = testObj[playerNumber];   // Change this Line`

**Comment by erictleung** [comment]
@patribezek if you get stuck or have questions with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by drcharlie98** [comment]
I am noticing a pattern in the challenges: the simplest thinking wins the day.

**Comment by ar94952** [comment]
still confused with the instructions... 

it is asking for 2 dot notations, but also asking for a specif string that doesn't match the val1.prop1

**Comment by zeonji** [comment]
Accessing Objects Properties with the Dot Operator 

just add the . (dot)  wkwkwk

```

// Setup
var testObj = {
  "hat": "ballcap",
  "shirt": "jersey",
  "shoes": "cleats"
};

// Only change code below this line

var hatValue = testObj.hat;      // Change this line
var shirtValue = testObj.shirt;    // Change this line

```

**Comment by 4mifix** [comment]
The issue with this challenge is the Operator wording, in Java most people know the word dot operator and in Javascript we use dot notation. Basically the same thing but in this challenge for a beginner programmer the semantics can be confusing. With a little research and reading the difference becomes clear. I was confused about both until I did the research. .Operator and .Notation slight difference but the challenge is about accessing Objects. Dot operator originated in Java.
