### ISSUE TITLE
validation failed

### ISSUE THREAD

**Issue by dooglus** [FreeCodeCamp/FreeCodeCamp#6299]
Challenge [Fill in the Blank with Placeholder Text](http://www.freecodecamp.com/challenges/fill-in-the-blank-with-placeholder-text#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum</p>

```

I was asked to use "the first few words of this kitty ipsum text". I copied the first two words, but it failed validation. I tried copying the first three words instead, and that worked.

Google defines 'a few' as "a small number of".
synonyms:	a small number, a handful, one or two, a couple, *two or three*.

Edit: it appears that copying 3 or more words works, but copying just 2 of them doesn't.

**Comment by dooglus** [comment]
This isn't bike-shedding. It is rejecting valid solutions very early on in the first lesson, when it is important not to discourage people.

Are reports like this not wanted?

**Comment by M108** [comment]
Just discovered this. Yeah, "first few" should be "first three". Why have the ambiguity?

**Comment by dooglus** [comment]
Having worked through most of the rest of the programming exercises I wonder if the aim is to get programmers used to working from low-quality specifications. Even if that is the case, I think having a poorly specified problem this early on runs too high a risk of putting people off forever.

**Comment by M108** [comment]
> I wonder if the aim is to get programmers used to working from low-quality specifications.

That's certainly an interesting idea. I could imagine some sort of course where you must sort through (intentionally) ambiguous and unintelligible requirements to potentially satisfy an irate product manager or customer with unrealistic deadlines. Call it "Worse-case scenario" training :D

**Comment by SaintPeter** [comment]
> Call it "Worse-case scenario" training

Call it:  Situation Normal training.

**Comment by M108** [comment]
Yes. Situation Normal Training™
