### ISSUE TITLE
incorrect error message - "1.0 has no decimal point"

### ISSUE THREAD

**Issue by dooglus** [FreeCodeCamp/FreeCodeCamp#6306]
Challenge [Create Decimal Numbers with JavaScript](http://www.freecodecamp.com/challenges/create-decimal-numbers-with-javascript#?solution=var%20ourDecimal%20%3D%205.7%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myDecimal%20%3D%201.0%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourDecimal = 5.7;

// Only change code below this line
var myDecimal = 1.0;


```

This gave an error: "myDecimal should have a decimal point". But it does have a decimal point.

The test is:

`assert(myDecimal % 1 != 0, 'message: <code>myDecimal</code> should have a decimal point');`

The request to "Create a variable `myDecimal` and give it a decimal value" should perhaps specify that the decimal part needs to be non-zero. Or the error message needs fixing.

My last issue was closed without comment. Are "nit picks" like this unwelcome in general? I'd like to help improve the site, but if you would rather I keep these issues to myself I can do.

**Comment by SaintPeter** [comment]
It may be more accurate to request a "fractional" decimal number.  1.0 is actually an integer.

Go ahead an bring your nit-picks.  Worst case we close it without fixing.

**Comment by ltegman** [comment]
"Decimal value" implies that there is actually a _value_ after the decimal point and not just a point.

**Comment by dooglus** [comment]
The error message is still wrong:

    "assert(myDecimal % 1 != 0, 'message: <code>myDecimal</code> should have a decimal point'); "

**Comment by AkiraLaine** [comment]
@dooglus The change specifically says the decimal number needs to have a fractional part, so there is no need to change the test.

**Comment by zeonji** [comment]
myDecimal = ourDecimal;

**Comment by amaanam1238** [comment]
Try this code it will work:- 

var ourDecimal = 5.7;

// Only change code below this line
var myDecimal= 8.888;
✔✔✔✔✔
