### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/zipline-wikipedia-viewer has an issue 

### ISSUE THREAD

**Issue by biancamihai** [FreeCodeCamp/freecodecamp#631]
This is not a bug just a suggestion how can this zipline be improved. Since the wikipedia api allows this you can add a user story to load the data based on pagination or why not an infinite scroll. This could be a great exercise for the camper to bring all the data not just the first page http://en.wikipedia.org/wiki/Special:ApiSandbox#action=query&list=search&format=json&srsearch=Albert%20Einstein&sroffset=0&srlimit=3

**Comment by terakilobyte** [comment]
It'd be great to see a PR on this... ;)

**Comment by biancamihai** [comment]
K, I will implement it in my zipline :)

**Comment by biancamihai** [comment]
and here you have a wikipedia search on infinite scroll http://codepen.io/biancamihai/full/YXpjqM/ please ignore my great designer skills :D this can be done more simple with pages at the bottom or a load more button ... or or or

**Comment by QuincyLarson** [comment]
Nice work, @biancamihai! If you can update your codepen to fulfill these other two user stories, I will make yours the example Zipline and also add the infinite scroll as a bonus user story:
Bonus User Story:As a user, I can click a button to see a random Wikipedia entry.
Bonus User Story:As a user, when I type in the search box, I can see a dropdown menu with autocomplete options for matching Wikipedia entries.

**Comment by biancamihai** [comment]
Yeah well don't think that replacing the existing example with this one will be ok. That one is so much more beautiful (design ui ux). Perhaps just add it as an alternative if you want too.
I do have 2 questions for this bonus user stories.
Bonus User Story: As a user, I can click a button to see a random Wikipedia entry. - random from the results already  displayed? :)
Bonus User Story:As a user, when I type in the search box, I can see a dropdown menu with autocomplete options for matching Wikipedia entries. - something like my prev searches? So if I search "snow white", "snippet" the next time when I search something and type "sn" I should see this in an autocomplete? 

Thanks!

**Comment by QuincyLarson** [comment]
@biancamihai Random meaning a random article from Wikipedia in general.

I think it should be typeahead for all Wikipedia articles, rather than a filtered search.

Also, regardless of aesthetics, yours is quite functional (and beautiful in its minimalism) and I do think it could become the example project.

**Comment by biancamihai** [comment]
OK, I will add the functionality on Tuesday or Wednesday night.

**Comment by QuincyLarson** [comment]
Great! I will close this issue for now. Thank you for your hard work on this Zipline!

**Comment by biancamihai** [comment]
When you guys have time check this out http://codepen.io/biancamihai/full/YXpjqM/ let me know if it needs other improvements. (@terakilobyte - react gave me a hard time on this :D)
