### ISSUE TITLE
Using iFrame in HTML

### ISSUE THREAD

**Issue by rdharmegowda** [FreeCodeCamp/FreeCodeCamp#6310]
Hi,

Any help will be appreciated.

I am using the below code to embed the parent HTML page i.e. "XYZ.html". The issue is, the URL links and also Windows.Print function is not working when I use with iFrame.

please suggest.

Thanks in advance for any help.

CODE:

<iframe src="XYZ.html" width="1200" height="2000"  ></iframe>

**Comment by AkiraLaine** [comment]
Hi. You haven't pasted any code. Also, if you need any help please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is used for issues only :smile:

**Comment by ltegman** [comment]
Closing as not an issue. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need challenge help. Thanks and happy coding!
