### ISSUE TITLE
An additional explanation in instruction about quoted lines may additionally help learners

### ISSUE THREAD

**Issue by devarsh1997** [FreeCodeCamp/FreeCodeCamp#6313]
Challenge [Override Styles in Subsequent CSS](http://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3Ablue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.

Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color:blue;
  }
</style>
<h1 class="pink-text blue-text">Hello World!</h1>

```
# Just A Suggestion
Lines from instruction, "Create an additional CSS class called blue-text that gives an element the color blue. Make sure it's below your pink-text class declaration." 

I understand this serves the purpose for the waypoint and following the instruction I solved it but **why** does it occur might supplement knowledge more and be helpful to learner in future.

**Comment by raisedadead** [comment]
I guess your are right, some thing like the 

*CSS class `.blue-text`'s attributes overrides the `.pink-text` class because it is declared below `.blue-text` class.*

Or do you prefer some other text?
Thanks.

**Comment by SaintPeter** [comment]
Maybe something to the effect of:
> The *order* of the class declarations in the `<style>` section are what is important.  The second declaration will always take precedence over the first.
> Because `.blue-text` is declared second, it overrides the attributes of `.pink-text`

I think a general cleanup of this description would be helpful.

**Comment by devarsh1997** [comment]
Yeah @SaintPeter and @raisedadead it makes sense to change to what you guys are considering. Exactly what I desired to know more about.
