### ISSUE TITLE
Stand in Line (max call stack size exceeded)

### ISSUE THREAD

**Issue by pallavihegde1** [FreeCodeCamp/FreeCodeCamp#6318]
Challenge [Stand in Line](http://www.freecodecamp.com/challenges/stand-in-line#?solution=var%20arr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0Afunction%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20var%20singleItem%3B%0A%20%20arr.push(item)%3B%0A%20%20%0A%20%20singleItem%20%3D%20arr.shift()%3B%0A%0A%20%20return%20singleItem%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(arr))%3B%0Aconsole.log(queue(arr%2C10))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(arr))%3B%0Aconsole.log(arr%5B4%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arr = [1,2,3,4,5];

function queue(arr, item) {
  // Your code here
  var singleItem;
  arr.push(item);
  
  singleItem = arr.shift();

  return singleItem;  // Change this line
}

// Display Code
console.log("Before: " + JSON.stringify(arr));
console.log(queue(arr,10)); // Modify this line to test
console.log("After: " + JSON.stringify(arr));
console.log(arr[4]);
```

dont know , whats wrong with the code. Please suggest

**Comment by raisedadead** [comment]
Hi @pallavihegde1 

Your code passes for me, try cleaning up your cache and cookies etc, as mentioned here : [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Goodluck!

**Comment by pallavihegde1** [comment]
@raisedadead thanks :) it passed now

**Comment by bugron** [comment]
Closing this issue as resolved.
