### ISSUE TITLE
Case specific coding

### ISSUE THREAD

**Issue by JEBtheGamer1** [FreeCodeCamp/FreeCodeCamp#6321]
I've been noticing this for a while now, and it's a bit irritating. Most of the challenges have this "issue" and that is that they are not only dependent on the correct spelling and phrases to be in the code, but also are case specific. I guess this is bikeshedding, but that's who I am :smiley: 
I don't know how Code Camp works in the background, but wouldn't it be fairly simple to add a `.lower()` or whatever the equivalent is? I guess it's a bit petty, it's kinda like the auto bracket closing (which could use a toggle but for the most part is helpful :smile: ).

**Comment by sludge256** [comment]
I think that the strictness promotes good habits. Campers should be thoroughly reading instructions to ensure that they are fulfilling all requirements, including, but not limited to, expected output types and values. It also has the benefit of promoting awareness of case sensitivity which is also important (variable,function,method names, etc).

**Comment by OriBon** [comment]
I really don't think we should be considering the option of allowing improper spelling, phrasing, and case sensitivity in an environment in which all three are crucial to proper performance and running of a program.

**Comment by BerkeleyTrue** [comment]
@OriBon Is correct, it is not about proper spelling but about getting the correct result from your algorithm.

Also Free Code Camp, not Code Camp.

**Comment by JEBtheGamer1** [comment]
Ah. Point taken, it's nice to know that's it has a reason :smile:

**Comment by BerkeleyTrue** [comment]
Happy Coding!
