### ISSUE TITLE
Feature Request: receive feedback on algorithm efficiency.

### ISSUE THREAD

**Issue by Stacey-Gammon** [FreeCodeCamp/FreeCodeCamp#6323]
For the algorithm challenges, it would be nice to get feedback on the efficiency of your implementation - not just if that implementation gives the correct output.  It would also be pretty cool to see how the speed of your implementation compares against others (e.g. "your answer is in the 96th percentile for efficiency").

P.S. I am a git and FreeCodeCamp newbie, so hopefully posting this feature request is okay and I am doing everything correctly.  :)

**Comment by BerkeleyTrue** [comment]
@Stacey-Gammon While it would it be a nice feature, we do not want to enforce the idea the the algorithms are where campers should stay. Many campers make the mistake of constantly going back to these challenges and not advancing to the projects, which are the bread and butter of becoming a developer.

In the long run, finding all the solutions/fastest solutions don't help you build out applications. And applications are what will wow potential employers/clients not that you found 6 different ways to reverse a string. Without these experiences, campers don't really know when and where are the best places to apply these algorithms.

Happy Coding!
