### ISSUE TITLE
Golf Code Term corrections

### ISSUE THREAD

**Issue by The1030Club** [FreeCodeCamp/FreeCodeCamp#6326]
In the results you force the user to state an Eagle as two and three strokes under par. Technically the term for three strokes under par is an 'Albatross' or a 'Double Eagle'.

This is only really an issue when using the ===. Below is my suggested answer exception.

```
function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes === 1) {
    return "Hole-in-one!";
  } 
  else if (strokes === (par - 3)) {
    return "Albatross";
  } 
  else if (strokes ==== (par - 2)) {
    return "Eagle";
  } 
  else if (strokes === (par - 1)) {
    return "Birdie";
  } 
  else if (strokes === par) {
    return "Par";
  } 
  else if (strokes === (par + 1)) {
    return "Bogey";
  } 
  else if (strokes === (par + 2)) {
    return "Double Bogey";
  } 
  else if (strokes >= (par + 3)){
    return "Go Home!";
  } 
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);
```

**Comment by SaintPeter** [comment]
We are fully aware of the additional terminology, but wanted to not have this already large if else chain turn into a monstrous chain.  The expected values are in the table in the problem description.

Remember:  the purpose of this exercise is not to teach about funny golf terminology, but to have users apply if else statements in a "real world" type problem.

Thanks and Happy Coding!

**Comment by BEBEDYDY** [comment]
function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes === 1){return "Hole-in-one!"}
  else if(strokes <= par - 2){return "Eagle"}
  else if(strokes == par - 1){return "Birdie"}
  else if(strokes === par){return "Par"}
  else if(strokes == par + 1){return "Bogey"}
  else if(strokes == par + 2	){return "Double Bogey"}
  else if(strokes >= par + 3){return "Go Home!"}
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);
golfScore(4, 1);
golfScore(5, 2);
golfScore(4, 3);
golfScore(4, 4);
golfScore(1, 1);
golfScore(5, 5);
golfScore(4, 5);
golfScore(4, 7);
golfScore(5, 9);

Idk what i did but it works on me. uh....

**Comment by ryander** [comment]
Also came here to post this issue. It's confusing when you are looking for a solution to a problem if the answer is incorrect. If you don't want to include the extra if statement then don't test "golfScore(5, 2)"

**Comment by wtfudgecakes** [comment]
It should be correct. It invalidates the obvious solution
  if (strokes == 1)
  {
    return names[0];
  }
  else
  {
    const index = strokes - par + 3;
    return index < 6 ? names[index] : names[6];
  }
