### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue 

### ISSUE THREAD

**Issue by appijumbo** [FreeCodeCamp/freecodecamp#633]
Challenge says 'Give the green box a padding of 40 pixels on its top and left side, but only 20 pixels on its bottom and right side.' but the 'Go to next challenge' is passed before entering the right side padding.

![waypoint add different padding to each side of an element v1](https://cloud.githubusercontent.com/assets/10559688/7836170/3c373488-0476-11e5-9c5e-1beec941a779.jpg)

Cheers
T

**Comment by terakilobyte** [comment]
Thanks, I've resolved this with a commit!
