### ISSUE TITLE
Waypoint validate but doesn't appear

### ISSUE THREAD

**Issue by xavierartot** [FreeCodeCamp/FreeCodeCamp#6330]
Hello,
my waypoint are validate, but when I want to come back to reading again, my solution are not here anymore?
Thank you

**Comment by SaintPeter** [comment]
Solutions are stored in two places:
1) In temporary local storage on your browser.  These are time limited (by your browser) and may be cleared when you clear your cache, etc.
2) In our database, where they are accessible from your profile page.  Your latest solution will always be available there.

Confirm that your solutions are on your profile page and that you are able to access them from there.

**Comment by xavierartot** [comment]
I have an access from the profil page, thanks

**Comment by ltegman** [comment]
This is expected behavior then since localStorage code saving is not meant to be permanent. Thanks and happy coding!
