### ISSUE TITLE
Challenge says "give each element a unique ID" but it assumes that target1 through target3 are in the left, and target 4 through target6 are in the right.

### ISSUE THREAD

**Issue by byosh** [FreeCodeCamp/FreeCodeCamp#6331]
[Challenge - Give Each Element a Unique ID](http://www.freecodecamp.com/challenges/give-each-element-a-unique-id#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A)

**Comment by byosh** [comment]
I had interlaced the numbers so left has 1, 3, 5 and right has 2, 4, 6 and this was wrong because 2 was not in left and 5 was not in right.

**Comment by alistermada** [comment]
I can't see your code with the link you posted, but does it look like this:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button id="target1" class="btn btn-default target"></button>
        <button id="target3" class="btn btn-default target"></button>
        <button id="target5" class="btn btn-default target"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button id="target2" class="btn btn-default target"></button>
        <button id="target4" class="btn btn-default target"></button>
        <button id="target6" class="btn btn-default target"></button>
      </div>
    </div>
  </div>
</div>

```

Yea, I'm getting the same problem you described where `target2` and `target5` aren't considered valid unless they are in the `left-well` and the `right-well` respectively. All other tests pass.

**Comment by SaintPeter** [comment]
Like this:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1"></button>
        <button class="btn btn-default target" id="target3"></button>
        <button class="btn btn-default target" id="target5"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target2"></button>
        <button class="btn btn-default target" id="target4"></button>
        <button class="btn btn-default target" id="target6"></button>
      </div>
    </div>
  </div>
</div>
```

I guess I never considered that someone wouldn't just number them 1-6 starting at the top of the code.

I'd be ok with an additional instruction explicitly specifying that 1-3 go in the left well, 4-6 in the right.

**Comment by craigbuster56** [comment]
this free code academy is awesome

**Comment by Nishant8** [comment]
it should be like this :)

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1"></button>
        <button class="btn btn-default target" id="target2"></button>
        <button class="btn btn-default target" id="target3"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4"></button>
        <button class="btn btn-default target" id="target5"></button>
        <button class="btn btn-default target" id="target6"></button>
      </div>
    </div>
  </div>
</div>

**Comment by Nishant8** [comment]
https://www.freecodecamp.com/nishant8

**Comment by dwd2010** [comment]
@Nishant8, This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by abdoullfurya** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1"></button>
        <button class="btn btn-default target" id="target3"></button>
        <button class="btn btn-default target" id="target2"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target5"></button>
        <button class="btn btn-default target" id="target4"></button>
        <button class="btn btn-default target" id="target6"></button>
      </div>
    </div>
  </div>
</div>
