### ISSUE TITLE
Slasher Flick with slice or splice

### ISSUE THREAD

**Issue by AEA2002** [FreeCodeCamp/FreeCodeCamp#6332]
Challenge [Slasher Flick](http://www.freecodecamp.com/challenges/slasher-flick#?solution=function%20slasher(arr%2C%20howMany)%20%7B%0A%20%20%2F%2F%20it%20doesn%27t%20always%20pay%20to%20be%20first%0A%20%20arr.splice(0%2ChowMany)%3B%0A%20%20if%20(howMany%3D%3D%3D0)%7B%0A%20%20%20%20howMany%20%3D%20arr.length-howMany%3B%20%20%0A%20%20%20%20arr%3Darr.slice(0%2ChowMany)%3B%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0Aslasher(%5B1%2C%202%2C%203%5D%2C%200)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function slasher(arr, howMany) {
  // it doesn't always pay to be first
  arr.splice(0,howMany);
  if (howMany===0){
    howMany = arr.length-howMany;  
    arr=arr.slice(0,howMany);
  }
  return arr;
}

slasher([1, 2, 3], 0);

```
I can solve Slasher Flick with *slice or splice* in the last line of the if statement
```JavaScript
 arr=arr.splice(0,howMany);
 arr=arr.slice(0,howMany);
```
However, only slice works in this version:
```JavaScript
 arr.slice(0,howMany);
```

**Comment by ltegman** [comment]
This is expected. Slice and splice perform very different functions. Thanks and happy coding!

**Comment by AEA2002** [comment]
@ltegman 
>Slice and splice perform very different functions.

That's my point, both slice (see code above) and splice (see code below) worked in the last line of the if statement in my code. (I removed the last part of my original comment, since I think it may have confused the issue.)

```JavaScript
function slasher(arr, howMany) {
  // it doesn't always pay to be first
  arr.splice(0,howMany);
  if (howMany===0){
    howMany = arr.length-howMany;      

  // code with splice
    arr=arr.splice(0,howMany);
  }
  return arr;
}
slasher([1, 2, 3], 0);
```

**Comment by ltegman** [comment]
This still isn't surprising. Both slice and splice return the same thing, it's just that one mutates the array and one doesn't. Both are valid ways to solve this problem. If you have further questions you should visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance.
