### ISSUE TITLE
Change the Font Size of an Element  :Bug? Why the code can't pass?

### ISSUE THREAD

**Issue by ss611470** [FreeCodeCamp/FreeCodeCamp#6335]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
     
  }
  p {
    
  font-size: 16px;
    
  }
</style>


<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by fewtime** [comment]
- You need 2 `p` elements with Kitty Ipsum text.

In your code, you just have 1 `p` element, so the code can't pass.

**Comment by ss611470** [comment]
It can't pass cause
Give elements with the p tag a font-size of 16px.') 
but i set it

**Comment by fewtime** [comment]
Your code works for me.
Are you zooming in or out in your browser? 
Maybe this [issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6242) can help you.

**Comment by ss611470** [comment]
No zooming , I'm using IE11

**Comment by SaintPeter** [comment]
Confirmed - on Chrome I can't get the run button to work at all on this one.  No error messages in the console.

**Comment by sludge256** [comment]
Here is another report of the issue occurring on IE 11
https://gitter.im/FreeCodeCamp/Help?at=569ec3fa5de13b3f15e40ea5

To my knowledge I have not been able to reproduce this on Chrome or FF yet.

**Comment by ryetika** [comment]
Same issue, can't complete the challenge in IE11 because "Give elements with the p tag a font-size of 16px.') " does not turn green.
In chrome I don't even see the output.

**Comment by thunsber** [comment]
Having this problem as well

**Comment by Frithan** [comment]
```html
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>
```

its worth pointing out that this will also pass but really shouldn't.

**Comment by TridevGuha** [comment]
use ctrl+ or ctrl- to zoom browser to 100% ,it will work. @ss611470

**Comment by GreatORC** [comment]
+1 IE11 I have the same problem!

**Comment by heimdallur** [comment]
had to complete it on my iPhone and revert back to pc for the rest... not a solution but a quick workaround.

**Comment by Brijesh0108** [comment]
hi all ,
i pass font-size:16px; in p element but still not working

**Comment by TridevGuha** [comment]
do not use IE

**Comment by Brijesh0108** [comment]
Thankz for help.
But,Sorry i cant't understand

**Comment by ezine15** [comment]
ya that code worked for me as well.... thanks, I was like missing a closing tag which is "}" in this case ..

**Comment by msprabha06** [comment]
thank you so much ya that code worked

**Comment by akashramesh13** [comment]
First it didnt work for me too, Then I **zoomed out** and found it working.I am a mac user and I am using chrome. Hope this helps others. To zoom out -> press command and "-" ( Minus ) button at the same time.

**Comment by sattol** [comment]
<style>
.blue-text{color:blue;}
p{font-size: 16px ; }
</style>
try this it will work

**Comment by Suresh84** [comment]
@sattol, thanks bud.

**Comment by Rgalan08** [comment]
This worked for me....initializing p and place it with brackets " {}"
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Purva7** [comment]
Code 

`<style>
  .red-text {
    color: red;
    
  }
  p{
   font-size:16px;
    }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>`

**Comment by texas2010** [comment]
@Purva7 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
