### ISSUE TITLE
The length should be sixteen and not one

### ISSUE THREAD

**Issue by mansipattani** [FreeCodeCamp/FreeCodeCamp#6339]
Challenge [Record Collection](http://www.freecodecamp.com/challenges/record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20update(id%2C%20prop%2C%20value)%20%7B%0A%20if%20(value%20!%3D%3D%20%22%22%20%26%26%20collection%5Bid%5D%5Bprop%5D%20!%3D%3D%20%22tracks%22)%20%7B%0A%20%20%20%20collection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%20%7D%20%0A%20%20else%20if%20(value%20!%3D%3D%20%22%22%20%26%26%20collection%5Bid%5D%5Bprop%5D%20%3D%3D%20%22tracks%22)%20%7B%0A%20%20%20%20collection%5Bid%5D%5Bprop%5D.push(value)%3B%0A%20%20%7D%20%0A%20%20else%20if%20(value%20%3D%3D%3D%20%22%22)%20%7B%0A%20%20%20%20delete%20collection%5Bid%5D%5Bprop%5D%3B%0A%20%20%7D%0A%20%20return%20collection%3B%0A%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0Aupdate(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
 if (value !== "" && collection[id][prop] !== "tracks") {
    collection[id][prop] = value;
  } 
  else if (value !== "" && collection[id][prop] == "tracks") {
    collection[id][prop].push(value);
  } 
  else if (value === "") {
    delete collection[id][prop];
  }
  return collection;

}

// Alter values below to test your code
update(5439, "artist", "ABBA");


```

**Comment by ltegman** [comment]
This test case is correct. Read over the directions carefully and visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help. Thanks and happy coding!

**Comment by aniketkudale** [comment]
Yeah, No issues! just follow basics. Happy coding!

Here's my solution!

```js
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {

  if (value!=="" && prop !=="tracks")
    {
      collection[id][prop] = value;
    }
  else if (prop == "tracks" && value !=="")
    {
      collection[id].tracks = [value];
    }
  else if (prop == "tracks" && value === "")
    {
      delete collection[id][prop];
    }
  else if  (prop!=="tracks" && value === "")
    {
      delete collection[id][prop];
    } 
    
  return collection;
}

// Alter values below to test your code
update(2548, "tracks", "");


```

**Comment by mihaelamardare** [comment]
I know that this section in closed but man...is too hard this exercise. I just could't resolve it without the code from above. And I still don;t understand how do you calculate the length and where is in the code above? And...for the lessons about objects this exercise is just too tricky.

Anyway, I'll keep on going but is on my mind now that I don;t understand this exercise and ...it's disappointing.

**Comment by aniketkudale** [comment]
'Length' here means number of tracks/songs in that record.

**Comment by genesisjoec** [comment]
I tend to agree with user who said this was too hard too soon. I've been on this challenge for the last 3 days. I've been searching on every website I know, using the chat feature and no one could steer me in the right direction. I was knocking challenges out left and right until I came to this one and it stopped me dead in my tracks. Very very frustrating.  Perhaps, a more helpful description/instructions would be more useful. @QuincyLarson

**Comment by genesisjoec** [comment]
Based on the instructions, I found myself trying to figure out how to append to and push to an array.

**Comment by aniketkudale** [comment]
I hope you solved it, don't give up, Happy Coding!
