### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-pair-program-on-bonfires has an issue 

### ISSUE THREAD

**Issue by cvorak** [FreeCodeCamp/freecodecamp#634]
Not a bug, but just a note. I'm Ubuntu(laptop) and Fedora(workstation) user, and there is not Screen Hero version for any linux platform. I believe that vast number of developers use linux, and it's just sad to exclude them. Just a thought... Back to Virtual Machine with Win7... :(

**Comment by terakilobyte** [comment]
@cvorak thanks for the feedback. We're not really excluding people, it's a representation of the state of the market. We've just found screenhero to be superior to the alternatives (like teamviewer).

Thanks for the feedback. We're always on the lookout for better tools so if you find one let us know.
