### ISSUE TITLE
Basic algorithm (Chunky Monkey)

### ISSUE THREAD

**Issue by Saladg** [FreeCodeCamp/FreeCodeCamp#6343]
Challenge [Chunky Monkey](http://www.freecodecamp.com/challenges/chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20%20var%20myArray%3D%5B%5D%3B%0A%20%20%20var%20count%3D0%3B%0A%20%20%20while%20(count%3Carr.length)%0A%20%20%20%7B%0A%20%20%20%2F%2F%20add%20to%20myArray%20values%20between%20current%20index%20and%20size%0A%20%20%20myArray.push(arr.slice(count%2Ccount%2Bsize))%3B%0A%20%20%20%2F%2F%20increase%20count%0A%20%20%20count%2B%3Dsize%3B%0A%20%20%20%7D%0A%2F%2Freturn%20document.write(%22My%20new%20array%3A%20%22%2B%20myArray)%0Areturn%20myArray%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.4.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function chunk(arr, size) {
  // Break it up.
   var myArray=[];
   var count=0;
   while (count<arr.length)
   {
   // add to myArray values between current index and size
   myArray.push(arr.slice(count,count+size));
   // increase count
   count+=size;
   }
//return document.write("My new array: "+ myArray)
return myArray;
}

chunk(["a", "b", "c", "d"], 2);

```
The output to this code when i tried with document.write(myArray); ==a,b,c,d and not as displayed in the console [["a", "b"], ["c", "d"]]
I am a beginner, kindly confirm

**Comment by raisedadead** [comment]
Please use console.log to check any output. Also the output would be visible in the Browser console and not in the FCC's challenge console. You can open your console using F12 (Developer Tools).

Also please refer [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by ltegman** [comment]
When you document.write it calls the array.toString() method, which displays what you are seeing. The console is displaying what you would see from JSON.toString(array). As suggested, please visit the help chat for further help. Thanks and happy coding!

**Comment by Saladg** [comment]
Thanks a lot, I will try and learn more

**Comment by Saladg** [comment]
Thanks a lot. Am also told that: "When you document.write it calls the
array.toString() method, which displays what you are seeing. The console is
displaying what you would see from JSON.toString(array)."


On Wed, Jan 20, 2016 at 4:13 PM, Mrugesh Mohapatra <notifications@github.com

**Comment by zhixinyiye** [comment]
function chunkArrayInGroups(arr, size) {
  // Break it up.
  var newArr = [];

  for(var j= 0;j<(((arr.length)/size));j++){
    newArr.push(arr.slice(j*size,(j+1)*size));
  }
  return newArr;
}

console.log(chunkArrayInGroups([], 2));
