### ISSUE TITLE
Nested arrays in JSON bug?

### ISSUE THREAD

**Issue by billsrambo** [FreeCodeCamp/FreeCodeCamp#6345]
Example code doesn't match the code in the problem window -- 

Example: 
var ourPets = { 
  "cats": [
    "Meowzer",...

Problem:
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",...

Changing the problem code to match the example by removing type: and list: (with brackets to match) satisfies the first requirement ("secondTree should equal "pine"") but the second requirement ("Use dot and bracket notation to access myPlants")  will not update when what I assume is the correct answer is used: myPlants.trees[1] 

If the problem code is left alone and the above answer is entered, this problem occurs: "TypeError: Cannot read property '1' of undefined"

------

Challenge [Accessing Nested Arrays in JSON](http://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = myPlants.trees[1]; // Change this line


```

**Comment by llovera** [comment]
Hello billsrambo
One way to solve the problem is: var secondTree = myPlants[1].list[1];
This is because myPlants is an array with 2 items (flowers and trees ,with myPlants[1] indicate the second one= trees ) .

// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line
var secondTree = myPlants[1].list[1]; // Change this line

**Comment by SaintPeter** [comment]
@llovera is correct.  In the future, please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by IsmaelBarba** [comment]
Thanks LLovera. I really had a hard time with this one. And didn't get much help in the Help Chat.

Once I am able to see the solution I am able to put it together and get a real understanding on how it works.

Thanks again.

**Comment by JadeTao** [comment]
Array is numbered from"0" not "1".

**Comment by marxcom** [comment]
`// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = myPlants[1].list[1]; // Change this line`

This worked for me.

**Comment by ar94952** [comment]
// Setup
var myPlants = [
{
type: "flowers",
list: [
"rose",
"tulip",
"dandelion"
]
},
{
type: "trees",
list: [
"fir",
"pine",
"birch"
]
}
];

// Only change code below this line
var secondTree = myPlants[1].list[1]; 

this worked too.  you don't need the end notation "//change this line"

**Comment by texas2010** [comment]
@ar94952 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by ko5320** [comment]
2017/3/23 23:01，"Lance" <notifications@github.com>寫道：

**Comment by masoodshahnoori** [comment]
> Hello billsrambo
> One way to solve the problem is: var secondTree = myPlants[1].list[1];
> This is because myPlants is an array with 2 items (flowers and trees ,with myPlants[1] indicate the second one= trees ) .
> 
> // Setup
> var myPlants = [
> {
> type: "flowers",
> list: [
> "rose",
> "tulip",
> "dandelion"
> ]
> },
> {
> type: "trees",
> list: [
> "fir",
> "pine",
> "birch"
> ]
> }
> ]; 
> 
> // Only change code below this line
> var secondTree = myPlants[1].list[1]; // Change this line

good job sweet heart :*
