### ISSUE TITLE
issues with switch

### ISSUE THREAD

**Issue by frempongandrews** [FreeCodeCamp/FreeCodeCamp#6349]
Even though the answer is right, it won't let me pass.

my answer is as follows:

    switch (val){
        case "bob" :
         answer = "Marley";
         break;
      
     case 42 :
      answer = "The Answer";
      break;
      
     case 1 :
      answer = "There is no #1";
      break;
      
     case 99 :
      answer = "Missed me by this much!"; 
      break;
      
     case 7 :
      answer = "Ate Nine";  
  
These are the issue identified by the corrector:

You should not use any else statements
You should not use any if statements
You should have at least four break statements

Obviously I am not using neither if or else statements

**Comment by luksprog** [comment]
Do you by any chance commented out the initial if-else code? From what I've seen the tests will fail if either "if" or "else" is present(as actual code or just present in a comment)

**Comment by SerhiiLihus** [comment]
Can you show us full code, that you wrote for this task?

**Comment by bugron** [comment]
@frempongandrews thanks for posting. Closing. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks. And feel free to reopen with more details if you still experience problems, thanks.
