### ISSUE TITLE
Some mistake in task.

### ISSUE THREAD

**Issue by SerPry** [FreeCodeCamp/FreeCodeCamp#6350]
Operator || (or) return true if one of arguments or both are true. Ex in callenge says that 
if (num > 10 || num < 5) {
  return "No";
}
return "Yes";
will return "Yes" only if num is between 5 and 10 (5 and 10 included). But it is not correct. In this case we should use && (and) operator.
(Sorry for my English)

**Comment by sludge256** [comment]
This will never evaluate to true
```js
if (num > 10 && num < 5) {
return "No";
}
```

**Comment by tesla809** [comment]
Hey SerPry, can you link the challenge so that I can check it out?

Thanks
Tesla809

**Comment by SerPry** [comment]
Sorry. It is my faulty. You are right I closed issue.  Thank you for support

**Comment by tesla809** [comment]
No problem. Glad to be of some help.
