### ISSUE TITLE
Ceasars Cipher - hyperlinks to ROT13 don't open in new tab

### ISSUE THREAD

**Issue by GFore** [FreeCodeCamp/FreeCodeCamp#6352]
In the description for the Ceasars Cipher bonfire, the hyperlinks to the ROT13 wikipedia article have the logo next to them indicating the page will open in a new window, but when you click the link you are taken to Wikipedia in the same window. Then you have to click the Back button to come back to Free Code Camp. Not a big deal but it is not consistent with how the new window/tab logo is being used with links on this site. Solution is probably to add a target="_blank" attribute to the anchor element for this hyperlink.

**Comment by raisedadead** [comment]
Yup not a pressing issue, but perhaps should be corrected. I'll open a PR.
