### ISSUE TITLE
Can't pass the code size challenge

### ISSUE THREAD

**Issue by codingchampion** [FreeCodeCamp/FreeCodeCamp#6353]
Challenge [Set the Font Family of an Element](http://www.freecodecamp.com/challenges/set-the-font-family-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; MALNJS; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
I think a few other people reported it too but it won't let me pass this question. I did accidently change the zoom during the challenge but when I switched back to 100% and restarted the question it still would not pass me.

**Comment by TravisHi** [comment]
The exercise is asking you to set the font-family of your p elements.

That seems to be missing in your code.

**Comment by jbforth4** [comment]
you need to change the font to something arial. There is nothing changing the font in your code.

**Comment by SerhiiLihus** [comment]
If you read task closer, you'll see that:

> Make all of your **p** elements use the Monospace font.

```css
p {
    font-family: Monospace;
    font-size: 16px;
  }
```

Hope this will help :)

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) when you need assistance. Thanks and happy coding!
