### ISSUE TITLE
Remove unnecessary "the" in front of JavaScript

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6356]
Challenge [Comparison with the Equality Operator](http://www.freecodecamp.com/challenges/comparison-with-the-equality-operator#?solution=%2F%2F%20Setup%0Afunction%20myTest(val)%20%7B%0A%20%20if%20(val%20%3D%3D%2012)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function myTest(val) {
  if (val == 12) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
myTest(10);

```

Maybe change from

![image](https://cloud.githubusercontent.com/assets/2754821/12473611/7fd7ec7e-bfc8-11e5-8355-392a4a06319b.png)

to

> In order for JavaScript to compare...

The "the" in front of JavaScript is a bit odd.

**Comment by SaintPeter** [comment]
I concur.  
> In order for JavaScript to compare . . .

would be fine.
