### ISSUE TITLE
does not recognize var a= b; for a should be assigned to b with = 

### ISSUE THREAD

**Issue by thescientificfangirl** [FreeCodeCamp/FreeCodeCamp#6362]
I am able to get through everything besides this.  Is this a glitch or am I doing something wrong????

**Comment by sludge256** [comment]
Along with the name of the challenge showing us your full code is helpful.
If you want a quicker response to your problem try asking in the [Help chat](https://gitter.im/FreeCodeCamp/Help)

**Comment by bugron** [comment]
Closing as stale. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks. And feel free to reopen with more details if you still experience problems, thanks.
