### ISSUE TITLE
extra "," in Checkpoint: Profile Lookup

### ISSUE THREAD

**Issue by greyhammer** [FreeCodeCamp/FreeCodeCamp#6364]
In the Array at the top of the code, there is an  an extra "," at the end of the array. 

```
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    },  <<<<<<<<<< Right Here 
];
```

**Comment by pttvntrdz** [comment]
So the comma over there only means in your object contacts you could have a fifth object, but if you don't write this fifth object (after the one with the label for the firstName "Kristian") it does not give any error. Usually you don't write the comma after the last object, but it's not an error

**Comment by ltegman** [comment]
It is valid JS, but it's considered bad practice by most codebases and breaks from the usual style arrays are written in the rest of the curriculum.

**Comment by greyhammer** [comment]
Its in the part of the code that the student is not suppose to edit. So I figured it was just a typo and wanted to let someone know.  Are these things someone like me could just fork and then what?

**Comment by ltegman** [comment]
@greyhammer We have a [Contribution Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) if you're interested in submitting a fix.

**Comment by greyhammer** [comment]
I'd like to handle this. It seems like it would be just removing one character.  I want to practice contributing to someone else's project. If that's cool I'll handle it tomorrow morning. Its 8pm here.

**Comment by SaintPeter** [comment]
@greyhammer No need to ask permission - that's what "help wanted" means.

**Comment by greyhammer** [comment]
Alright, I'll handle this one.

**Comment by greyhammer** [comment]
Starting on this now

**Comment by greyhammer** [comment]
Pull Request Submitted #6377
