### ISSUE TITLE
Map content should be centered on full-screen view

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6365]
The column of content on the /map view should be centered on the page when viewed full screen.

## Mockup
![image](https://cloud.githubusercontent.com/assets/553494/12497440/a7d6af2a-c050-11e5-8505-576515593826.png)

I don't think it needs to be centered on the side view, unless centering doesn't interfere with the display.

Ref: https://www.reddit.com/r/FreeCodeCamp/comments/41vr0i/please_bring_back_brownish_fcc_old_version/cz73beo

**Comment by QuincyLarson** [comment]
I agree. You can just throw the map in a     
```
.col-xs-12.col-sm-8.col-sm-offset-2.col-md-6.col-md-offset-3 
```
div and it should just work.
