### ISSUE TITLE
order of classes on html element should not matter (in this instance)

### ISSUE THREAD

**Issue by johndavidhunt** [FreeCodeCamp/FreeCodeCamp#6367]
Challenge [Add Font Awesome Icons to our Buttons](http://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa-thumbs-up fa"></i>Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

In working thru the above example I noticed that I was not able to validate my input and move to the next challenge if I changed the order of classes for the <i> element. In trying to apply font awesome classes of  "fa" and "fa-thumbs-up", I could not be allowed to enter <i class="fa-thumbs-up fa"> it would only allow <i class="fa fa-thumbs-up">. This could have been very frustrating to someone with less experience, although the sample does show the "fa" class first, this really shouldn't be required for the validation of this challenge, it may confuse those who think it must this way, when they work on future projects.
<img width="815" alt="fa_fa-thumbs-up" src="https://cloud.githubusercontent.com/assets/1871911/12500206/0bc97638-c07f-11e5-8927-6349b0a4ba55.png">
<img width="802" alt="fa-thumbs-up_fa" src="https://cloud.githubusercontent.com/assets/1871911/12500207/0bce4b7c-c07f-11e5-8a1f-75cd323aeac5.png">

**Comment by SaintPeter** [comment]
You're technically right (which is the best kind of right), but I don't know if we can be bothered to fix it.  Every single instance of using font awesome on the web shows them using `fa fa-icon-name`.  I suspect that doing it any other way would actually be really unusual.  

We can probably fix the first test without too much trouble, but fixing the second would be miserable, on an already miserable test.

Did you actually have this as a real problem, or was this just you fooling around?

**Comment by johndavidhunt** [comment]
No, I had it as a real problem. I knew the basics of how font awesome worked and I saw the instructions, and I went ahead and added the classes in the order in which I prefer to use them, (more specific first - "fa-thumbs-up fa"), and it didn't work. I tried some other things and it didn't work. Then I thought, "What could be the issue?", and of course I looked at the example and realized that I should copy it exactly to see if that helped, which of course it did. 
Yes, you are of course correct that all examples on the internet currently show the order as you have it "fa-thumbs-up fa", but that is part of the issue, where someone coming into this training might assume that is the way it has to be, instead of just the 'traditional' way of doing it. And they may never discover why.
I understand not feeling like it is worth fixing it, but I thought I could mention it so that if possible you could help save someone the trouble of beating their head against the wall for too long.

Thanks for the response.

**Comment by SaintPeter** [comment]
@FreeCodeCamp/issue-moderators 
Do we think this is worth fixing?

**Comment by alistermada** [comment]
@SaintPeter There doesn't seem to be any con to leaving this open for folks who wanna contribute something, in my opinion.

Besides, in one of the CSS challenges, it said that the order of class names in HTML elements don't matter. It would be strange if it mattered now.

**Comment by SaintPeter** [comment]
Ok, flagged as help wanted.

To potential PR submitters:  http://stackoverflow.com/a/2214962/1420506
