### ISSUE TITLE
Correct return results not registering with a tick.

### ISSUE THREAD

**Issue by jay7525** [FreeCodeCamp/FreeCodeCamp#6368]
Hi
As the title suggest. My results are returning the correct number for the longest length word (apart from the last) But the panel on the left only shows the first task as correctly ticked.

What am I doing wrong? 

```js
var strSplit;
var strSplitLen;
var splitLen = [];
var lenLongest = [];

function findLongestWord(str) {
  strSplit = str.split(" ");
  for (var i = 0; i < strSplit.length; i += 1) {
      splitLen.unshift(strSplit[i].length);
      strSplitLen = strSplit.length;
      lenLongest = splitLen.sort();
  } return lenLongest[strSplit.length-1];
}

findLongestWord("The quick brown fox jumped over the lazy dog");
```

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for challenge help. Thanks and happy coding!
