### ISSUE TITLE
Problem with "Manipulating Arrays With unshift" page

### ISSUE THREAD

**Issue by looyenyi** [FreeCodeCamp/FreeCodeCamp#6369]
![bug](https://cloud.githubusercontent.com/assets/15665548/12501703/1e1bec90-c0fb-11e5-9db4-8165c63d6490.JPG)

There seems to be an extra closing bracket in the suggested answer on the left panel: [["Paul", 35], ["dog", 3]]).

**Comment by SaintPeter** [comment]
@ltegman Am I blind that I can't see this?  These are multi-dimensional arrays, are they not?

**Comment by ltegman** [comment]
Closing bracket is probably the wrong wording. There's a straggling paren at the end of the array that shouldn't be there.

**Comment by sludge256** [comment]
I thought I was going crazy too until I saw the parenthesis.
