### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by GhostParticle** [FreeCodeCamp/freecodecamp#637]
Will not allow to continue. The wrap check boxes in a div with class row was actually done two way-points before this one. As soon as you open the way-point you get a completion for that part. But as soon as you start typing the completion goes away and does not come back even though the code is completed and has been completed since the opening of the way-point. Images show before and after putting code in place. 

![error1](https://cloud.githubusercontent.com/assets/10119077/7838321/da2b63c8-0451-11e5-9249-43bf3bf530f3.PNG)
![error2](https://cloud.githubusercontent.com/assets/10119077/7838322/dc551202-0451-11e5-853f-98c948936268.PNG)

**Comment by terakilobyte** [comment]
Thanks, I've addressed this as part of #621!
