### ISSUE TITLE
Test of function truncate() expects incorrect results; test fails when correct results are given.

### ISSUE THREAD

**Issue by HadziJo** [FreeCodeCamp/FreeCodeCamp#6370]
Challenge [Truncate a string](http://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncate%20(sourceStr%2C%20newMaxLength)%20%7B%0A%20%20var%20srcStrLen%20%3D%20sourceStr.length%3B%0A%20%20var%20rtnString%20%3D%20sourceStr%3B%0A%20%20var%20startIndx%20%3D%200%3B%0A%20%20var%20endIndx%20%3D%20startIndx%20%2B%20newMaxLength%3B%09%0A%20%20var%20minStrLength%09%3D%203%3B%0A%09%09%0A%20%20if(%20srcStrLen%20%3E%20newMaxLength%20)%7B%20%20%2F%2F%20can%20only%20truncate%20if%20new%20size%20is%20less-than%20original%20size%0A%0A%20%20%20%20%09%2F%2F%20ONLY%20if%20new%20Max%20Length%20is%20greater%20than%20minimum%2C%20truncate%3B%20else%20return%20original%20string.%0A%20%20%20%20%20%20if%20(newMaxLength%20%3E%20minStrLength)%20%7B%0A%20%20%20%20%20%20%09%0A%20%20%20%20%20%20%09endIndx%20-%3D%20minStrLength%3B%09%2F%2F%20need%203%20additional%20character%20spaces%20to%20append%20%22...%22%0A%0A%09%09%20%20%20%20rtnString%20%3D%20sourceStr.slice(startIndx%2C%20endIndx)%3B%20%2F%2F%20truncate%20string%20at%20newMaxLength%3B%0A%20%20%20%20%20%20%20%20rtnString%20%2B%3D%20%22...%22%3B%09%09%2F%2F%20append%20%22...%22%20to%20truncated%20string%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%7Delse%20%7B%0A%20%20%20%20%20%20%09rtnString%20%3D%20sourceStr.slice(startIndx%2C%20endIndx)%3B%0A%20%20%20%20%20%20%7D%0A%09%7D%0A%09console.log(%22Return%20String%3A%20%22%2B%20rtnString%20)%3B%0A%09return%20rtnString%3B%0A%7D%0A%0Atruncate(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

****> BUG description follows:
The testing of results claims that my code fails the following (last) two tests: I believe the tests are expecting incorrect results, and thus, announce a failure when correct results are provided by truncate().

     ** 2nd to last test claims:   truncate("A-", 1) should return "A...".
         (correct expected result should be: "A")

     ** Last test claims:  truncate("Absolutely Longer", 2) should return "Ab...".
        (correct expected result should be: "Ab")

HOWEVER, the requirements state clearly that for values of "num" at 3 or less should generate result strings with NO "..." appended to the truncated string (see requirement #5108 3 below):

(1) Truncate a string (first argument) if it is longer than the given maximum string length (second argument). Return the truncated string with a "..." ending.

(2) Note that the three dots at the end add to the string length.
     // the above was a little confusing since I first thought it meant to truncate to num characters,
     // then add another 3 characters ("..."); However, the post processing of results assumes one
     // must truncate to num - 3 length, and then add the "..."; 
     // thus maintaining TOTAL length to "num".           

(3) If the num is less than or equal to 3, then the length of the three dots is NOT added to the string length.

// -------------------------------------------------------------------------------------------------------------

My code:
```javascript
function truncate (sourceStr, newMaxLength) {
  var srcStrLen = sourceStr.length;
  var rtnString = sourceStr;
  var startIndx = 0;
  var endIndx = startIndx + newMaxLength;	
  var minStrLength	= 3;
		
  if( srcStrLen > newMaxLength ){  // can only truncate if new size is less-than original size

    	// ONLY if new Max Length is greater than minimum, truncate; else return original string.
      if (newMaxLength > minStrLength) {
      	
      	endIndx -= minStrLength;	// need 3 additional character spaces to append "..."

		    rtnString = sourceStr.slice(startIndx, endIndx); // truncate string at newMaxLength;
        rtnString += "...";		// append "..." to truncated string
      
      }else {
      	rtnString = sourceStr.slice(startIndx, endIndx);
      }
	}
	console.log("Return String: "+ rtnString );
	return rtnString;
}

truncate("A-tisket a-tasket A green and yellow basket", 11);
...

**Comment by ltegman** [comment]
The __length__ of the three dots is NOT added to the string length. You still add the three dots, they just don't count towards your length cap. Thanks and happy coding!
