### ISSUE TITLE
New Layout

### ISSUE THREAD

**Issue by pattee** [FreeCodeCamp/FreeCodeCamp#6372]
I think the new layout could be improved on the map page, by reducing the size of the portion of the screen that reads, "Challenge Map, Required challenges are marked with a *", and a button to expand or collapse all the challenges. I'm in Firefox 43.0.4. This section is super big for me. It makes it difficult to see the list of challenges on the screen. I can only see about 5 lines of the list of Challenges at once.

**Comment by SaintPeter** [comment]
Already done, pending release.

**Comment by pattee** [comment]
Thanks!
