### ISSUE TITLE
Escape Sequence

### ISSUE THREAD

**Issue by NehaGaba07** [FreeCodeCamp/FreeCodeCamp#6378]
Challenge [Escape Sequences in Strings](http://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStr%20%3D%20%22%20%5C%20%5C%5C%20%5C%20%20%5C%20%5Ct%20%5C%20%20%5C%20%5Ct%20%5C%20%5Cr%20%5C%20%5C%20%5Cn%20%5C%20%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = " \ \\ \  \ \t \  \ \t \ \r \ \ \n \ ";

```

**Comment by ltegman** [comment]
Issue does not describe a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance and if they confirm what you're seeing is a bug with the challenge open an issue with a description of your problem and steps to reproduce. Thanks and happy coding!
