### ISSUE TITLE
Map and Chat Toggle Keyboard Shortcuts

### ISSUE THREAD

**Issue by pmbenjamin** [FreeCodeCamp/FreeCodeCamp#6379]
This suggestion might be a bit pedantic, but now that FreeCodeCamp has collapsible Map and Chat drawers, it would be nice if campers can interact with them using keyboard shortcuts.
Many web applications, like GitHub and Twitter, have similar features.

A FreeCodeCamp implementation might look something like this:
`g` + `m` : Toggle your Map
`g` + `c`  : Toggle Chat

**Comment by SaintPeter** [comment]
This is a great idea and something we plan to do.  Maybe some industrious person will implement it.  It should be trivial.

**Comment by sahat** [comment]
I could give it a shot. Which branch is the site on?

**Comment by bugron** [comment]
@sahat all development goes in `staging` branch,

**Comment by sahat** [comment]
@bugron Thanks.

**Comment by QuincyLarson** [comment]
@sahat This is a bit off topic, - welcome to our humble project, which - as you may know - was built on top of your brilliant Hackathon starter! 

Thank you for putting in all that work to build that project. It made getting Free Code Camp started so much easier.

**Comment by sahat** [comment]
Thank you @QuincyLarson, I may have started the Hackathon Starter, but all credit goes to you and the team for creating one of the most successful GitHub's open-source projects to date.
