### ISSUE TITLE
Change "Greater Than Equal To" to "Greater Than or Equal To"

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6380]
I hope this isn't too nit picky, but the [Comparison with the Greater Than Equal To Operator](http://www.freecodecamp.com/challenges/comparison-with-the-greater-than-equal-to-operator) and [Comparison with the Less Than Equal To Operator](http://www.freecodecamp.com/challenges/comparison-with-the-less-than-equal-to-operator) challenges should change their text from 

> "____ than equal to"

 to

> "____ that **or** equal to"

where "___" is "greater" or "less."

The [Comparison with the Less Than Equal To Operator](http://www.freecodecamp.com/challenges/comparison-with-the-less-than-equal-to-operator) challenge already uses this expression in the editor but not in the description itself.

![image](https://cloud.githubusercontent.com/assets/2754821/12518891/420fb9f2-c0f0-11e5-9a7d-4acd7ddee345.png)

Also, the [MDN JavaScript reference page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators) adds the "or" to describe these symbols.

**Comment by SaintPeter** [comment]
Sure.

I see a PR is already open for this.
