### ISSUE TITLE
Unable to view the Code editor in the browser (Firefix,IE,Chrome)for my challenges since 1/21/2016 EST.

### ISSUE THREAD

**Issue by sravaniduggirala** [FreeCodeCamp/FreeCodeCamp#6381]
Please Help!! 
Unable to view the code editor for my challenges since yday.Tried IE,firefox,chrome and deleted cookies and tried incognito mode.I was able to view without any issues till 1/20/2016.The attached screen is how i see the challenges now.

Attached is the screenshot of what I see when I sign in to freecodecamp.com
![codeeditorerror](https://cloud.githubusercontent.com/assets/2394292/12519447/d3bd041a-c10c-11e5-9101-1afba22f52aa.JPG)

**Comment by pmbenjamin** [comment]
@sravaniduggirala 
Have you tried:
1. From different machines (e.g. laptops, desktops, mobile phone ...etc)?
2. From different networks (e.g. public WiFi, mobile phone 4G-LTE, 3G ...etc)?

I'm essentially trying to rule out a bad machine and/or something in your network blocking certain FCC content?

**Comment by sravaniduggirala** [comment]
@pmbenjamin  I have tried on my Mobile (Android device) ,which is on my mobile network and noticed the same behavior.

**Comment by pmbenjamin** [comment]
Hmm, this is interesting.

Can you try logging out of your account to see if you experience the same behavior as a guest on FCC?

**Comment by sravaniduggirala** [comment]
@pmbenjamin  Just tried.
![codeeditor_asguest](https://cloud.githubusercontent.com/assets/2394292/12521153/da6a8c38-c116-11e5-8cc0-2bbe315f4ee8.JPG)

**Comment by tourshan** [comment]
Hello @pmbenjamin,

I wanted to notify you that I am facing the same problem here. When I open any of the challenges, it does not load the interface, except the condition`s section on the left.  I have deleted my browser`s cache, tried different browsers (IE, Chrome, etc...), but still doesn`t work? Please ,help! Thanks in advance ! :)

**Comment by pmbenjamin** [comment]
Alright. I _**suspect**_ this issue might be isolated to your region.
For instance, two different FCC code-bases _could have been published_ to different regions (e.g. Eastern USA, Pacific USA...etc) and the FCC code-base published to your region may contain a bug.

This is only my speculation as I do not have any insight into the core team's deployment details.

@tourshan and @sravaniduggirala , what regions are you located in?

**Comment by tourshan** [comment]
@pmbenjamin, I`m currently located in  USA, AK (Alaska). I don`t really know, but I will follow the thread here, and hopefully will find a solution of the problem. Thanks!

**Comment by raisedadead** [comment]
Hi @sravaniduggirala and @pmbenjamin, can either of you post a screenshot of the browser console, It can be opened from the Developer Tools (F12), there should be a tab for "Console" when you open the developer tools.

Once you have the console tab open, do a hard refresh (CTRL+F5).

If you see any errors, (should be appearing in red) do post the screenshot.

**Comment by sravaniduggirala** [comment]
@pmbenjamin  I am located in Boston,USA

**Comment by sravaniduggirala** [comment]
@raisedadead  Here is the screenshot
![console](https://cloud.githubusercontent.com/assets/2394292/12521956/daa7b73e-c11b-11e5-9ad6-843987ce3dde.JPG)

**Comment by tourshan** [comment]
![capture](https://cloud.githubusercontent.com/assets/11035140/12521919/17947208-c0fa-11e5-8107-5a234407e69b.PNG)
Hi @raisedadead ,

This is the only error in red that I found so far. I hope FreeCodeTeam is going to find a solution for that as soon as possible ;) Any help would be appreciated! For a moment I thought the problem is in my browser, but looks like there is a request error....

**Comment by sravaniduggirala** [comment]
@raisedadead  This is my console after a hard refresh
![console](https://cloud.githubusercontent.com/assets/2394292/12521995/18d4349c-c11c-11e5-9427-296c02f737d0.JPG)

**Comment by raisedadead** [comment]
@sravaniduggirala @tourshan 
Looks like there is some content being blocked just like this another similar issue #5999 . That reminds me I have to write the Wiki article, about the discussion there.

Since you are using chrome, can you install browsec, its a very light VPN/Anonymiser extenstion, that resolves this.

Here's the link : https://chrome.google.com/webstore/detail/browsec/omghfjlpggmjjaagoclmmobgdodcjboh

Let me know how it goes.

**Comment by sravaniduggirala** [comment]
woow!! thanks @raisedadead .Will try it and let u know.

**Comment by tourshan** [comment]
@raisedadead Thanks!

**Comment by snow8261** [comment]
I have the  same issue, do we have a solution yet ?

**Comment by BerkeleyTrue** [comment]
@sravaniduggirala Where are you located?

**Comment by BerkeleyTrue** [comment]
@sravaniduggirala @tourshan This looks unrelated to FCC. Looks like something is injecting code, most likely ads, into you page through either a plugin or your ISP.

**Comment by sravaniduggirala** [comment]
Hi 
i have logged in today and found that I was able to view and submit challenges without any issues.

**Comment by sravaniduggirala** [comment]
Thank You all for your comments and Suggestions!

**Comment by BerkeleyTrue** [comment]
Happy Coding!

**Comment by tourshan** [comment]
Thanks for the quick responses guys! Happy coding everyone :)
