### ISSUE TITLE
Change "Current Challenge" Default Behavior to be smarter

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6382]
I've seen a number of comments/complaints about the way going to http://freecodecamp.com works for signed in users.  The default behavior is kinda stupid, since it defaults to the "Getting Started" waypoint if the "currentChallenge" cookie is not set.

### Why Cookies don't work
1. Many people use multiple computers to work on Free Code Camp.  Using a cookie to store the `currentChallenge` doesn't work for them.
2. Others share a computer, so they're affected by similar issues.
3. Others clear their cookies for other valid reasons

### Current Default Stinks
Defaulting to the first challenge if the cookie is not set is silly, if we have any information at all about the user.  Say a camper is on the very last back end project, having completed every prior challenge . . . are we REALLY going to default them to the "welcome to Free Code Camp"?  We have a lot of information about a user, we ought to be able to make better default choices.

### Possible Solutions
1. Store the current challenge in the user object.  It's quick and painless and cross-computer compliant
2. If no `currentChallenge` cookie (or user value) is set, default to "last completed challenge + 1"

I think this covers the vast majority of use cases and does the think that is least surprising.

Ping: @BerkeleyTrue @QuincyLarson

**Comment by BerkeleyTrue** [comment]
Fair enough. These are sensible changes. When every a user completes a challenge we'll keep track of that. Then we'll use that information, if it exist, to redirect the user.

**Comment by santakmishra** [comment]
I think there should be a Dashboard landing page for logged in users, displaying some welcome message, the Next Challenge and other quick links/data/statistics, etc. Dropping the user right into a challenge after sign in (even if it's the next challenge) seems kinda abrupt to me.

**Comment by ijbramante** [comment]
Thank you so much for fixing this! Much appreciated!

**Comment by QuincyLarson** [comment]
@santakmishra @SaintPeter we used to have a sort of "welcome screen", but our thinking was, seeing that over and over would get annoying, when what you really want to do is just get back to coding. I don't want to add a "learn" button back to the navbar, either, which this would probably necessitate. I'm open to suggestions. If we had a more information about performance, etc it might be cool to have a dashboard of sorts like @santakmishra is suggesting.

**Comment by Kalcode** [comment]
The cookies aren't setting right either. I always have to sign in and my current cookies for currentChallengeId expires with session. Chrome is set to allow all local cookies to be set. Not PER session, every other cookie site works, but this one doesn't. 

I think the issues run a bit deeper than just a simple user side with cookies.

**Comment by Kalcode** [comment]
Alright i have sent in a pull request to at least fix the expire issue. 

 but i dont have much time to set-up an environment to test it, i am sorry. But examining the code seems to be a oversight of not setting an expire for currentChallengeId, i just used express documentation to set it to far in the future.

I hope this helps, i tested changing the cookie in browser and its works. But that is a far cry from testing the res.cookies() function.

**Comment by BerkeleyTrue** [comment]
This is fixed in Beta

Happy Coding
