### ISSUE TITLE
profile lookup code -bm

### ISSUE THREAD

**Issue by bobbymathews** [FreeCodeCamp/FreeCodeCamp#6383]
Challenge [Profile Lookup](http://www.freecodecamp.com/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%2C%0A%5D%3B%0A%0A%0Afunction%20lookUp(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20text%3D%20%5B%5D%3B%0Afor%20(i%3D0%3B%20i%20%3C%20contacts.length%3B%20i%2B%2B)%20%7B%0A%20%20var%20name1%3D%20contacts%5Bi%5D.firstname%3B%20%2F%2F%20Get%20Id%0Avar%20prop1%20%3D%20contacts%5Bi%5D.prop%3B%20%0A%20%20%0A%0A%20%20%20%20if%20(contacts%5Bi%5D.firstName%20%3D%3D%20firstName%20%26%26%20contacts%5Bi%5D.hasOwnProperty(prop))%0A%20%20%20%20%7Bif%20(prop%20%3D%3D%22likes%22)%20%7Bfor%09(index%20%3D%200%3B%20index%20%3C%20contacts%5Bi%5D.likes.length%3B%20index%2B%2B)%20%7B%0A%20%20%20%20text%20%5Bindex%5D%3D%20contacts%5Bi%5D.likes%5Bindex%5D%3B%0A%7D%7D%0A%20%20%20%20%20else%20%7Bvalue%3D%20contacts%5Bi%5D%5Bprop%5D%3B%7D%0A%7D%0A%20%20%20%20%0A%20%20else%20if%20(contacts%5Bi%5D.firstName%20!%3D%20name1)%0A%20%20%7Bvalue%20%3D%20%22No%20such%20contact%22%3B%7D%0A%20%20%0A%20%20%20%0A%20%20else%20if%20(prop1%20%3D%3D%3D%20null)%0A%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20value%20%3D%20%22No%20such%20property%22%3B%0A%7D%0A%7D%0A%20%20if%20(prop%20%3D%3D%20%22likes%22)%20%7Breturn%20text%3B%7D%0A%20%20else%20%7Breturn%20value%3B%7D%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp(%22Akira%22%2C%20%22address%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    },
];


function lookUp(firstName, prop){
// Only change code below this line
  var text= [];
for (i=0; i < contacts.length; i++) {
  var name1= contacts[i].firstname; // Get Id
var prop1 = contacts[i].prop; 
  

    if (contacts[i].firstName == firstName && contacts[i].hasOwnProperty(prop))
    {if (prop =="likes") {for	(index = 0; index < contacts[i].likes.length; index++) {
    text [index]= contacts[i].likes[index];
}}
     else {value= contacts[i][prop];}
}
    
  else if (contacts[i].firstName != name1)
  {value = "No such contact";}
  
   
  else if (prop1 === null)
     {
        value = "No such property";
}
}
  if (prop == "likes") {return text;}
  else {return value;}
// Only change code above this line
}

// Change these values to test your function
lookUp("Akira", "address");

```

Help button is not working and I am stuck..not sure what to do

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance. Good luck and happy coding!

**Comment by BEBEDYDY** [comment]
function lookUpProfile(firstName, prop){
// Only change code below this line
  for(var i=0;i<contacts.length;i++){
    if(contacts[i].firstName===firstName){
      if(contacts[i].hasOwnProperty(prop)){
        return contacts[i][prop];
      }
      else{
        return"No such property";
      }
    }
   
  }return"No such contact";

// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "likes");





Honestly, I knew the correct code but I don't understand why the `return"No such contact"` isn't after the first if statement.
