### ISSUE TITLE
Replace challenge example apps that don't fulfill user stories

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6386]
We need help going through the following challenges and testing their example apps to verify that they fulfill all of the challenge's user stories.

Note that we've done away with bonus user stories. Don't worry about the user stories show in the videos (I'm getting ready to re-record these videos anyway). 

If a challenge fails to deliver on a user story, find an example app that does. The easiest way to do this is to go to twitter and search "@freecodecamp" and you'll see thousands of tweets from campers, many of which include links to projects they've built. Or, if you've built your own implementation of this challenge already and it fulfills the user stories, you can just link to that.

Submit a pull request that updates these links. Then I will go through, fork them on CodePen, and link to our stable CodePen forks of these apps. 

Here are the challenges I haven't verified yet:

- [ ] http://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage
- [ ] http://www.freecodecamp.com/challenges/build-a-random-quote-machine
- [ ] http://www.freecodecamp.com/challenges/build-a-javascript-calculator
- [ ] http://www.freecodecamp.com/challenges/build-a-pomodoro-clock
- [ ] http://www.freecodecamp.com/challenges/show-the-local-weather
- [ ] http://www.freecodecamp.com/challenges/stylize-stories-on-camper-news
- [ ] http://www.freecodecamp.com/challenges/build-a-wikipedia-viewer
- [ ] http://www.freecodecamp.com/challenges/use-the-twitchtv-json-api
- [ ] http://www.freecodecamp.com/challenges/build-a-tic-tac-toe-game
- [ ] http://www.freecodecamp.com/challenges/build-a-simon-game
- [ ] http://www.freecodecamp.com/challenges/build-a-voting-app
- [ ] http://www.freecodecamp.com/challenges/build-a-nightlife-coordination-app
- [ ] http://www.freecodecamp.com/challenges/chart-the-stock-market
- [ ] http://www.freecodecamp.com/challenges/manage-a-book-trading-club
- [ ] http://www.freecodecamp.com/challenges/build-a-pinterest-clone

**Comment by alistermada** [comment]
Doesn't fulfill all user stories:
1. Random quote machine doesn't have tweet button.
2. Local weather app doesn't have button to toggle between Celsius and Fahrenheit
3. Voting app doesn't allow unauthenticated users see any polls. Can't create new options for existing polls.
4. Stock market app is down (application error on Heroku).
5. Book trading app lacks an option to trade books.
6. Pinterest clone doesn't have placeholder for broken image link. Can't view users' walls without signing in.

Technically fulfills user stories but has a bug:
1. JavaScript calculator % button doesn't do anything

Unconfirmed:
1. Nightlife coordination app (requires a Twitter account to log in, didn't bother making one).

Everything else seems solid. I haven't searched for any replacements yet, but I'll look for some if someone else hasn't in the next 5 hours or so.

**Comment by QuincyLarson** [comment]
@alistermada Thank you for the rundown. I'm updating the issue to reflect the need for replacements for these.

**Comment by QuincyLarson** [comment]
Here's the list:

- [ ] http://www.freecodecamp.com/challenges/build-a-random-quote-machine
- [ ] http://www.freecodecamp.com/challenges/build-a-javascript-calculator
- [ ] http://www.freecodecamp.com/challenges/show-the-local-weather
- [ ] http://www.freecodecamp.com/challenges/build-a-voting-app
- [ ] http://www.freecodecamp.com/challenges/build-a-nightlife-coordination-app
- [ ] http://www.freecodecamp.com/challenges/chart-the-stock-market
- [ ] http://www.freecodecamp.com/challenges/manage-a-book-trading-club
- [ ] http://www.freecodecamp.com/challenges/build-a-pinterest-clone

**Comment by QuincyLarson** [comment]
Actually, @alistermada, since you're doing most of the work here, you should be the one to do the PR and get credit.

Quotes: http://codepen.io/FreeCodeCamp/full/LGQLMX
Calculator: http://codepen.io/FreeCodeCamp/full/zrRzMR
Weather: http://codepen.io/FreeCodeCamp/full/bELRjV
Stock Market: http://watchstocks.herokuapp.com/

**Comment by alistermada** [comment]
@QuincyLarson  Thanks. About the Nightlife Coordination app, I just created a Twitter account and I can confirm that it passes all the user stories. Should we just leave it or do we need the app to have its own authentication?
