### ISSUE TITLE
Add additional stats to the About page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6387]
Before, when we put stats on the map page, we had to be careful about not using too many database queries. Now that we've moved the stats to our about page (http://www.freecodecamp.com/about) - which is accessed much less frequently - we can add a ton more stats.

Here are some things I think we should add ASAP:

- [x] {"isFrontEndCert": true}
- [x] {"isBackEndCert": true}
- [x] {"isDataVisCert": true}
- [ ] {"isFullStackCert": true}
- [x] how many campers are part of our Commit program
- [x] how much money campers have pledged to nonprofits each month
- [x] approximately how many dollars have been donated to nonprofits so far through Commit
- [x] how many minutes campers have spent on Free Code Camp in the last 30 days (note - this is something we would need to approximate based on Google Analytics. I've already done this for how many challenges are complete - a figure which has accelerated and needs updating).
- [x] How many projects we've built for nonprofits (we can manually update this. Currently the number is 17.)
- [x] How much money we've saved nonprofits (the number of projects times $50,000 - which is a conservative estimate of 400 hours of developer time + 100 hours of project manager time - at an estimated $100 per hour)

**Comment by raisedadead** [comment]
@QuincyLarson 

> - [ ] how many alumni are in our Free Code Camp LinkedIn university

Unfortunately, Linkedin, to best of my knowledge doesn't have an API endpoint for Universities, or Alumni, yet. However, it does give us a plugin that we could possibly use, it doesn't exactly serve our purpose. Still if you could check this link https://developer.linkedin.com/plugins/alumni

Preview:
![alumnitool](https://cloud.githubusercontent.com/assets/1884376/12529753/761cfbe8-c1e9-11e5-82fc-a9e6a775a221.gif)

That's the best worst thing close to our needs :disappointed: 

> - [ ] how many stars our main project repo has on GitHub

Its really simple:

`https://api.github.com/repos/FreeCodeCamp/FreeCodeCamp?q=stargazers_count`

The JSON that we receive has a field `"stargazers_count"`

At the time of this comment its :tada: :tada: **61968** :tada: :tada:  

*Word of caution: It needs the API call to be authenticated.*

**Comment by vicky002** [comment]
@QuincyLarson sir thanks for creating this issue! I'll start working on this soon.

**Comment by evaristoc** [comment]
Following this one

**Comment by hallaathrad** [comment]
Yeah, I'm curious about this as well. Followed

**Comment by evaristoc** [comment]
**@vicky002 list:**

> Can we get these Data?
> 
>     Total How many people got the job through FCC?
>     Total number of accounts on FCC
>     Active Accounts
>     Total Code Submissions Till now
>     active users by location
>     Most challenge problem/Bon fire on FCC website
>     Most active user on FCC
>     Number of people who are not from CS background
>     Total number of people who have completed the front-end/back-end of full web course.
>     Total number of message sent on Gitter main FCC channel and help channel.
> 
> also many people asked me if it's possible to download save all their FCC code solutions. So Currently I'm working on FCC Code Downloader

@luishendrix92 worked on a effective code downloader (the Solution Getter)

**Comment by QuincyLarson** [comment]
Note - I am closing this issue because I believe everything we need on the about page is now there.
