### ISSUE TITLE
Bonfire Confirm the Ending

### ISSUE THREAD

**Issue by DavidPhan1992** [FreeCodeCamp/FreeCodeCamp#6390]
In one of the statements for the instructions, "end("He has to give me a new name", "me") should return true." I think this should return false. Please confirm if I am correct.

**Comment by dylanjtw** [comment]
hey, no returning true is correct for that case. ('me' is substring of 'name')

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!
