### ISSUE TITLE
The challenge is missing the original code in the editor (see) sample test 3 & 4

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/FreeCodeCamp#6392]
Challenge [Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line


  

  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

```

**Comment by SaintPeter** [comment]
I don't understand what you're saying the issue is.  

Are you saying that when you loaded the page there was no code?  If so, where did you get the code above?

**Comment by AkiraLaine** [comment]
@SaintPeter He is saying that tests 3 & 4 don't pass.
@tommygebru That's normal - you have to write code to pass the challenge :D

**Comment by ltegman** [comment]
@AkiraLaine is correct. Thanks and happy coding!

**Comment by tommygebru** [comment]
sorry guys I just mean to say If i remember correctly the editor or the
question already had this
return "undefined";
and part of solving the entire challenge was to remove the quotations from
undefined
return undefined;
but i see that, was not the case, it has changed..... is it a bug or an
update to the challenge ?

**Comment by sludge256** [comment]
It's very likely that you clicked on the link to someone's incorrect code while you were in help chat which then saved itself to your local storage.
There have been no changes to the code of this challenge as far as I can tell,
https://github.com/FreeCodeCamp/FreeCodeCamp/blame/f813d33ac5c71f8dec8b4f945ba0e4ff8a99778d/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3019-L3033

**Comment by tommygebru** [comment]
thanks! i understand now +1 Brian
