### ISSUE TITLE
Size your images

### ISSUE THREAD

**Issue by hellomichiyabu** [FreeCodeCamp/FreeCodeCamp#6395]
It seems I don't have any problem in this code, what is the problem?

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  .smaller-image{
    width: 100px;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by raisedadead** [comment]
@hellomichiyabu Please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help), GitHub Issues are for bugs in the site only.

**Comment by hellomichiyabu** [comment]
@raisedadead Sorry for that! And it was the browser zoom problem, and I solved it. Thanks.
