### ISSUE TITLE
Check for Palindromes - Not recognizing true vs false

### ISSUE THREAD

**Issue by whitzhu** [FreeCodeCamp/FreeCodeCamp#6399]
When I come and paste in the check paramteres into the code I get correct responding answer such as 
palindrome("0_0 (: /-\ :) 0-0") should return true. And the output module will output "true".

However, the project criteria on the side doesn't turn green with a check mark. 

![1](https://cloud.githubusercontent.com/assets/12800136/12532246/e4ff12c4-c1c3-11e5-97ad-d51cfdeb070f.PNG)
![2](https://cloud.githubusercontent.com/assets/12800136/12532245/e4f8557e-c1c3-11e5-8a48-142f0088175d.PNG)
![3](https://cloud.githubusercontent.com/assets/12800136/12532244/e4f825a4-c1c3-11e5-825a-32cd5ef29b2a.PNG)

**Comment by ltegman** [comment]
Global variables are bad news. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance with challenges. This is not a bug with the tests. Thanks and happy coding!

**Comment by engincagatay** [comment]
Actually, I think palindrome("0_0 (: /-\ :) 0-0") should return false, instead of true. Isn't it?

**Comment by ltegman** [comment]
@engincagatay Nope. You should be removing all non-alphanumeric characters from the string before checking if it is a palindrome, which would leave you with `0000`.
