### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-button has an issue 

### ISSUE THREAD

**Issue by k1lly** [FreeCodeCamp/freecodecamp#640]
Challenge code is not showed fully untill clicked into editor field.
Screenshots:
Before
![image](https://cloud.githubusercontent.com/assets/2467931/7839955/d6c1799c-049d-11e5-80c1-61a162ce067f.png)
After
![image](https://cloud.githubusercontent.com/assets/2467931/7839989/02ab0168-049e-11e5-8aa5-9b660aa6e96e.png)

**Comment by terakilobyte** [comment]
Thanks for the report. This doesn't only affect this particular challenge, it can happen on a lot. We're looking into this display issue.
