### ISSUE TITLE
Return Largest Numbers in Arrays - Not Recognizing Correct Answer

### ISSUE THREAD

**Issue by whitzhu** [FreeCodeCamp/FreeCodeCamp#6400]
The output is same as suggested out put but program doesn't recognize. 

![1](https://cloud.githubusercontent.com/assets/12800136/12532645/cea00f42-c1cd-11e5-90f1-b824c443364b.PNG)
![2](https://cloud.githubusercontent.com/assets/12800136/12532646/cea2cf5c-c1cd-11e5-802a-346942637c9e.PNG)

**Comment by ltegman** [comment]
This is not an issue with the tests, but a problem with your code. Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance. Thanks and happy coding!
