### ISSUE TITLE
Potential confusion as to what the parameter passed into sumFibs function is

### ISSUE THREAD

**Issue by edward-hong** [FreeCodeCamp/FreeCodeCamp#6408]
Originally, I thought the number passed into the function sumFibs is the num is the number of the index of the Fibonacci sequence rather than the ceiling for what the value of the sequence is.

For example, I thought sumFibs(1000) meant generate 1000 numbers in the Fibonacci sequence and the sum the odd numbers in that sequence. Rather the exercise is asking for summing all odd numbers in the Fibonacci sequence smaller than 1000. Please make a note in the exercise to clear this up as it could cause some confusion

**Comment by AkiraLaine** [comment]
@edward-hong It does say:
> Return the sum of all odd Fibonacci numbers up to and including the passed number if it is a Fibonacci number.

What do you guys think? @FreeCodeCamp/issue-moderators

**Comment by bugron** [comment]
Description is very clear IMHO and I'm agree with @AkiraLaine. Closing this issue. Feel free to reopen if you still experience problems, thanks.
