### ISSUE TITLE
My code works fine on the console of my browser. But when I run the test, it doesn,t show any output.

### ISSUE THREAD

**Issue by asthas** [FreeCodeCamp/FreeCodeCamp#6409]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20while(card%20!%3D%3D%20%22%22)%7B%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20return%20%2B%2Bcount%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20return%20count%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20'J'%3A%0A%20%20%20%20case%20'Q'%3A%0A%20%20%20%20case%20'K'%3A%0A%20%20%20%20case%20'A'%3A%0A%20%20%20%20%20%20return%20--count%3B%0A%20%20%20%7D%0A%20%20return%20count%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%7D%0A%0A%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(4)%3B%20cc(9)%3B%20cc(6)%3B%0A%0Aif(count%20%3E%200)%7B%0A%20%20%20%20console.log('%22'%20%2Bcount%20%2B%20'%20Bet%22')%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20%0A%20%20%20%20console.log('%22'%20%2Bcount%20%2B%20'%20Hold%22')%3B%0A%20%20%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  while(card !== ""){
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return ++count;
    case 7:
    case 8:
    case 9:
      return count;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      return --count;
   }
  return count;
  // Only change code above this line
}
}



// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(4); cc(9); cc(6);

if(count > 0){
    console.log('"' +count + ' Bet"');
  } else {
    
    console.log('"' +count + ' Hold"');
  }
```

**Comment by asthas** [comment]
My code runs on the browser console. But still on running test there is no output

**Comment by AlexPritchard** [comment]
Your function needs to return a string with the count and whether to "Bet" or "Hold".

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](gitter.im/FreeCodeCamp/HelpJavascript) for assistance.
