### ISSUE TITLE
Map's "show incomplete challenges" should hide empty chapters.

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#6414]
The button works great, but as it hides the unfinished stuff, it shouldn't leave a bunch of empty chapter titles behind. Ideally, for someone with just one challenge to complete, should see an almost empty map.
<img width="534" alt="screen shot 2016-01-24 at 14 01 02" src="https://cloud.githubusercontent.com/assets/2107110/12538246/f08360f2-c2a2-11e5-9940-5de1067c4395.png">

----
On a side note, shouldn't the completed challenges be hidden by default, and have the option to show them all instead?

**Comment by SaintPeter** [comment]
It seems reasonable to me that we could hide empty categories.  It may be a non-trivial problem to determine which categories are "empty".

It seems like this problem could be solved (or would need to be solved) in the same manner as a live-filter textbox.  (IE: as you type it filters the list of items)

**Comment by hallaathrad** [comment]
Further enhancement seen in ^ #6575. Visually faded containers when empty (because of all its challenges having been completed). Non-trivial filtering required, methinks.

**Comment by QuincyLarson** [comment]
We have opted to fade and collapse instead of hide as it is less astonishing to users.
