### ISSUE TITLE
Passed But Not Working

### ISSUE THREAD

**Issue by garysa2010** [FreeCodeCamp/FreeCodeCamp#6418]
Challenge [Record Collection](http://www.freecodecamp.com/challenges/record-collection) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
  if (value !== "" && prop !== "tracks"){
    collectionCopy[id][prop] = value;
  } else if (value !== "" && prop === "tracks"){
    collectionCopy[id][prop].push(value);
  } else if (value === ""){
    delete collectionCopy[id][prop];
  }

  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");


```

**Comment by carlosf** [comment]
I might be wrong, but I think they were expecting you to make changes on the collection object.  The  collectionCopy I believe was to be used as a compairson for the test.

**Comment by SaintPeter** [comment]
@carlosf Is correct.  You are modifying the wrong collection.

Issues are not for code problems.  In the future, please ask for help in [Help JavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and Happy Coding!

**Comment by evaldasou** [comment]
Guys,

What is the difference between these two commands below, why my solution was not working with this one: collection[id].prop
but was working when I have used: collection[id][prop]

Simple tests in the browser itself tells me that the first command should work and the second should not:
Input: collectionCopy[1245].artist
Output:=> 'Robert Palmer'
   
Input: collectionCopy[1245][artist]
Output: ReferenceError: artist is not defined

**Comment by ltegman** [comment]
Brackets are used when the property name you want to access is stored in a variable or contains non-alphanumeric characters. For more assistance please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript). Thanks and happy coding!
