### ISSUE TITLE
When I started this Bonfire it already had a solution written, possible bug?

### ISSUE THREAD

**Issue by Fuzyon** [FreeCodeCamp/FreeCodeCamp#6420]
Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20%0A%20%20var%20str1%3Dstr.toLowerCase().replace(%2F%5B%5Ea-zA-Z0-9%5D%2Fgi%2C'')%3B%0A%20%20%2F%2Fvar%20arr%3D%5B%5D%3B%0A%20%20var%20arr%3Dstr1.split('')%3B%0A%20%20arr.reverse()%3B%0A%20%20var%20str2%3D%20arr.join('')%3B%0A%20%20console.log(str2)%3B%0A%20%20if(str1%3D%3D%3Dstr2)%0A%20%20return%20true%3B%0A%20%20else%0A%20%20%20%20return%20false%3B%0A%7D%0A%0A%0A%0Apalindrome(%22e%20y%20%20E%20%20%2C%20%20%20%23%24%23%25%5E%26%25%20%20%20%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  
  var str1=str.toLowerCase().replace(/[^a-zA-Z0-9]/gi,'');
  //var arr=[];
  var arr=str1.split('');
  arr.reverse();
  var str2= arr.join('');
  console.log(str2);
  if(str1===str2)
  return true;
  else
    return false;
}



palindrome("e y  E  ,   #$#%^&%   ");

```

**Comment by sludge256** [comment]
It's likely that you clicked on a link to someone's code while in one of the chat rooms, or elsewhere, which then saved to your browser's local storage.

**Comment by Fuzyon** [comment]
I looked through some other people's code when I didn't remember how to do a certain thing, but I don't think I entered a page with this bonfire. Eitherway, I think that might be the issue.

**Comment by BerkeleyTrue** [comment]
Happy Coding!
