### ISSUE TITLE
missing value check 

### ISSUE THREAD

**Issue by anuengineer** [FreeCodeCamp/FreeCodeCamp#6421]
Challenge [Storing Values with the Equal Operator](http://www.freecodecamp.com/challenges/storing-values-with-the-equal-operator#?solution=%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Ab%20%3D%20a%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var a;
var b = 2;

// Only change code below this line
b = a;

```

I did not assign value 7 to A, but the challenge accepted this as a right answer.

**Comment by bugron** [comment]
@anuengineer thanks for posting this issue!
I'm not able to pass second and third tests with your code, as expected. Please, provide a screenshot of the issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by SaintPeter** [comment]
@anuengineer If you mean that some individual tests have passed, that is correct and expected.  The tests AS A WHOLE are the requirements for completing the challenge.  There are many "half right" answers which will pass some tests, but it is very hard to have an incorrect answer which passes all of the tests.

**Comment by bugron** [comment]
Closing this issue. @anuengineer if you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.
