### ISSUE TITLE
Can't claim Data Vis Certification

### ISSUE THREAD

**Issue by HermanFassett** [FreeCodeCamp/FreeCodeCamp#6423]
Yesterday I finished all challenges for the Data Visualization Certification, and did the Claim Your Certificate step. There were no errors, but the certificate has not shown up on my profile, and it doesn't exist in the db when accessed as a direct link.
![alt](http://i.imgur.com/UCfoPn9.png)

**Comment by SaintPeter** [comment]
@BerkeleyTrue - Can you take a look at this?  I have no way of confirming.

**Comment by nemesiscodex** [comment]
The same happens to me 
![screenshot from 2016-01-27 02-15-51](https://cloud.githubusercontent.com/assets/3976562/12604631/f6a6e558-c49b-11e5-8582-cc3bedf9f788.png)
and with the direct link
![screenshot from 2016-01-27 02-18-21](https://cloud.githubusercontent.com/assets/3976562/12604663/501232a0-c49c-11e5-80bd-1b3cb27ddc1b.png)

**Comment by BerkeleyTrue** [comment]
@HermanFassett @nemesiscodex 

An error in challenge seed made it impossible for anyone to claim certifications but mistakenly let them complete the claim certification challenge.

I've pushed a hotfix to production. Looks like it is working properly. I've gone ahead and removed the faulty challenge from your record. If you visit the challenge to claim your certification again it should be working properly.

**Comment by nemesiscodex** [comment]
Thanks @BerkeleyTrue, it works now!

**Comment by HermanFassett** [comment]
Yep works for me too thanks @BerkeleyTrue
