### ISSUE TITLE
class issue

### ISSUE THREAD

**Issue by CorwinHicks** [FreeCodeCamp/FreeCodeCamp#6426]
Challenge [Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color : red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
It looks like the third test

> Your stylesheet should declare a red-text class and have its color set to red.

doesn't allow spaces between `color` and the colon.

**Comment by AkiraLaine** [comment]
@erictleung That doesn't seem to be the issue. His code passes for me.

**Comment by bugron** [comment]
@AkiraLaine that code isn't passing for me. Also, you can see in [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L391) that @erictleung is correct.

**Comment by AkiraLaine** [comment]
@bugron My bad, I wasn't using his code. Yeah - it doesn't work.
