### ISSUE TITLE
CodePen sample website does not work properly.

### ISSUE THREAD

**Issue by Qudware** [FreeCodeCamp/FreeCodeCamp#6428]
Challenge [Show the Local Weather](http://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by bugron** [comment]
@Qudware please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by Qudware** [comment]
In my browser, the weather does not show up. I have adblock installed if that helps.

**Comment by ltegman** [comment]
The API that gets your location gets flagged by adblock. If you turn it off the zipline will work fine. Thanks and happy coding!
