### ISSUE TITLE
.text function with JQuery

### ISSUE THREAD

**Issue by krischery2150** [FreeCodeCamp/FreeCodeCamp#6435]
I am not sure what I am suppose to be doing here. Could anyone help?

Challenge [Change Text Inside an Element Using jQuery](http://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target4%22).html(%22%3Ci%3Etarget4%3C%2Fi%3E%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<i>target4</i>");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by sahat** [comment]
I just did this problem for the very first time on FreeCodeCamp, so my opinion is pretty unbiased. 

It's a really strange problem, which took me a while to figure out. I was able to italicize the text in 3 different ways without modifying actual HTML, but not the way the test is expecting it.

Anyway, without giving away too much, you already know that you can create new a HTML tag using `.html()` and you can set text on any tag using `.text()`.

**Comment by AkiraLaine** [comment]
> Change the button with id target4 by italicizing its text.

Please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room if you need help. GitHub is for issues only.

**Comment by courtgo** [comment]
Hi there! I got stuck on that too & found your post. The code is missing the # symbol in front of target4 within your italic marks. It should be written as displayed below.

**$("#target4").html("<i>#target4</i>");**

**Comment by courtgo** [comment]
Please use below!

`$("#target4").html("<i>#target4</i>");``

**Comment by royznat** [comment]
used that same code - not working

**Comment by GauravG04** [comment]
use <em> tag instead of <i> it will work...eg shown below..
$("#target4").html("<em>#target4</em>");

**Comment by elzemrany** [comment]
$("#target4").html("<id>#target4</id>");

**Comment by github2552** [comment]
$("#target4").html("<em>#target4</em>");

**Comment by CodesAreHonest** [comment]
The solution is this... 

$("#target4").html("<html>#target4</html>");

**Comment by ignacio-rsg** [comment]
$("#target4").html("<em>#target4</em>");

**Comment by ignacio-rsg** [comment]
$("#target4").html("<<em>>#target4<</em>>");    ( take into consideration it is only one < and >

**Comment by ignacio-rsg** [comment]
between < and > goes em

**Comment by mdxedia** [comment]
Dear Sir,

BINGO>dearest one<typo


[image: --]

Md Xedia
[image: https://]about.me/mxedia
<https://about.me/mxedia?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>
