### ISSUE TITLE
Bug: Scrollbars Overlay in Chrome on Mac OS-X

### ISSUE THREAD

**Issue by santakmishra** [FreeCodeCamp/FreeCodeCamp#6436]
### Bug Description

This is a very specific bug that appears when browsing the FCC challenges in Google Chrome on Mac OS-X. Due to the default auto-hide setting of OS-X for scrollbars, this weird effect takes place where the scrollbars override all elements including slide-out sidebars and pop-over modals/images. It is odd however because the same thing doesn't cause any problems in Safari. The effect is shown in the screenshots attached below:-

![screen shot 2016-01-25 at 3 57 54 pm](https://cloud.githubusercontent.com/assets/13493577/12549286/54b08de0-c382-11e5-82d5-c26777860080.png)
![screen shot 2016-01-25 at 4 03 14 pm](https://cloud.githubusercontent.com/assets/13493577/12549287/54b42cf2-c382-11e5-9f17-7c6c66b11806.png)

The above screenshots were taken in *Google Chrome Version 48.0.2564.82 (64-bit)* on *Mac OS-X El Capitan version 10.11.2*

**To get a better understanding of the bug, watch this [screencast](http://screencast-o-matic.com/watch/cDVTXdhd6L).**
### Possible Solutions

- Anyone facing this problem can change their *Show Scrollbar* settings to *Always* in *System Preferences -> General*.

- However, to really solve the issue, a fix is required in the styling code. A solution discussed [on StackOverflow](http://stackoverflow.com/questions/16874546/strange-z-index-behavior-with-scrollbars-under-chrome) was tested by me and it worked. This was by adding `-webkit-transform: translate3d(0, 0, 0)` to the elements being affected by scrollbars (like the *Map* iframe element). However, I don't understand this fix and a better fix could be used by anyone who actually understands the problem.

Alternatively, the first solution may be added to the Wiki for users facing this problem, so they can solve it.

**Comment by SaintPeter** [comment]
I just want to say that this is quite possibly the best bug report I have ever seen.  Thank you.

Note to collaborators:
If you do attempt to fix this issue please be sure that you can replicate the conditions on OSx 10.11.2.

**Comment by hallaathrad** [comment]
On OS X 10.11.4 with Chrome Version 48.0.2564.82 (64-bit), and trying each one of the settings for the scrollbar. I was not able to replicate this issue. 
Perhaps it's been solved in this latest version of the OS?

**Comment by santakmishra** [comment]
@hallaathrad Hey I just update my OSx to 10.11.3 and the bug disappeared! Guess it was a OS bug after all. Dunno why I was delaying that update. I think we can safely close this issue. One less thing to worry about. :smile:

**Comment by hallaathrad** [comment]
awesomeness :clap:
