### ISSUE TITLE
Correct answer is not accepted

### ISSUE THREAD

**Issue by alozta** [FreeCodeCamp/FreeCodeCamp#6440]
Challenge [Title Case a Sentence](http://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20%0A%20%20String.prototype.replaceAt%3Dfunction(index%2C%20character)%20%7B%0A%20%20%20%20return%20this.substr(0%2C%20index)%20%2B%20character%20%2B%20this.substr(index%2Bcharacter.length)%3B%0A%20%20%7D%3B%0A%20%20%0A%20%20var%20mystr%20%3D%20%22%22%3B%0A%20%20var%20tmp%3D%22%22%3B%0A%20%20var%20strarr%20%3D%20str.split(%22%20%22)%3B%0A%20%20for(var%20i%3D0%3B%20i%3Cstrarr.length%3B%20%2B%2Bi)%7B%0A%20%20%20%20tmp%3Dstrarr%5Bi%5D.toLowerCase()%3B%0A%20%20%20%20tmp%20%3Dtmp.replaceAt(0%2C%20tmp.charAt(0).toUpperCase())%3B%0A%20%20%20%20mystr%20%2B%3D%20tmp%20%2B%20%22%20%22%3B%0A%20%20%7D%0A%20%20return%20mystr%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I don't know why but following code returns what is asked but somehow it is not accepted as correct.

My code:
```javascript
function titleCase(str) {
  
  String.prototype.replaceAt=function(index, character) {
    return this.substr(0, index) + character + this.substr(index+character.length);
  };
  
  var mystr = "";
  var tmp="";
  var strarr = str.split(" ");
  for(var i=0; i<strarr.length; ++i){
    tmp=strarr[i].toLowerCase();
    tmp =tmp.replaceAt(0, tmp.charAt(0).toUpperCase());
    mystr += tmp + " ";
  }
  return mystr;
}

titleCase("I'm a little tea pot");

```

**Comment by alistermada** [comment]
You've got an extra space at the end of the string you returned.

**Comment by bugron** [comment]
@alozta thanks for posting this issue!
@alistermada is correct. Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
