### ISSUE TITLE
I found this bug in a waypoint:Test Case Bug

### ISSUE THREAD

**Issue by Anshumakkar** [FreeCodeCamp/FreeCodeCamp#6441]
WayPoint: Diff Two Arrays 

The way point problem statement is not clear.
Though the algorithm I used has cleared all the Test Cases, but still the problem statement should be make more clearer.
Problem Statement: Compare two arrays and return a new array with any items only found in one of the original arrays.
arr1=['m','i','t'];
arr2=['a','m','i','t','a'];

As per problem statement a new array should be returned which contain items only found in one of the original arrays.
According to this ,output should be ['a','a']because 'a','a' is a separate element only found (twice) in arr2, whereas in my algorithm It passed all the TC's. Kindly clarify the problem statement.

**Comment by ltegman** [comment]
This detail has been intentionally left ambiguous because we found it was too confusing and difficult for some when made a true diffing algo. You can see the discussion which occurred about this in #3758. Thanks and happy coding!
