### ISSUE TITLE
element I got the code correct it says I did not. 

### ISSUE THREAD

**Issue by btcmacroecon** [FreeCodeCamp/FreeCodeCamp#6443]
Challenge [Headline with the h2 Element](http://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%20) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:[Challenge - Headline with the h2 Element (btcmacroecon's solution)](http://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%20)
```html
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
 
```

**Comment by ltegman** [comment]
This code is passing just fine for me. Have you tried refreshing the page? Are you seeing any errors in your browser console?

**Comment by btcmacroecon** [comment]
seemed to work, oddly enough it was at a previous spot I had already made
it past. Worked. thx

I'm having some issues with my eyes, is there a way to change the black
screen to white?

**Comment by SaintPeter** [comment]
Closing as resolved.
