### ISSUE TITLE
My Code Is Correct, but it's not being accepted

### ISSUE THREAD

**Issue by genesisjoec** [FreeCodeCamp/FreeCodeCamp#6449]
Challenge [Adding a default option in Switch statements](http://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%7B%0A%20%20%20%20case%201%3A%0A%20%20%20%20%20%20answer%20%3D%20%22apple%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%202%3A%0A%20%20%20%20%20%20answer%20%3D%20%22bird%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%203%3A%0A%20%20%20%20%20%20answer%20%3D%20%22cat%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20return%20%22stuff%22%3B%0A%20%20%20%20%20%20%0A%20%20%7D%0A%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(5)%3B%0A%0A%20%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case 1:
      answer = "apple";
      break;
    case 2:
      answer = "bird";
      break;
    case 3:
      answer = "cat";
      break;
    default:
      return "stuff";
      
  }
 // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(5);

  
```

**Comment by genesisjoec** [comment]
The first three criteria are not being checked marked, but should be

**Comment by sludge256** [comment]
These are the listed conditions:
```
"a" - "apple"
"b" - "bird"
"c" - "cat"
```
which do not match your cases.

**Comment by genesisjoec** [comment]
Thank you
