### ISSUE TITLE
Assignment with a Returned Value - Improve Challenge Seed

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6450]
Challenge [Assignment with a Returned Value](http://www.freecodecamp.com/challenges/assignment-with-a-returned-value) has an issue.

Here is the current challenge code:
```js
// Setup
var processed = 0;

function process(num) {
  return (num + 3) / 5;
}

// Only change code below this line
```

We need to better organize the example to show how the code is actually used.

```js
// Example
var changed = 0;

function change(num) {
  return (num + 5) / 3;
}

changed = change(10); 

// Setup
var processed = 0;

function process(num) {
  return (num + 3) / 5;
}

// Only change code below this line
```

I'm open to discussion on the specifics of this.  I don't know if this ends up being too long.

As per comments on #6062

**Comment by DizzysContent** [comment]
var changed = 0;

function change(num) {
  return (num + 5) / 3;
}

changed = change(10);

i don't understand that. how does it add up to 10? I've been stuck on this challenge for awhile
