### ISSUE TITLE
Comments in code are wrong, shouldn't say // Only change code above this line. Have to change the return below the line for it to work. 

### ISSUE THREAD

**Issue by JWLumley** [FreeCodeCamp/FreeCodeCamp#6453]
Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20var%20lookup%20%3D%20%7B%0A%20%20%20%20alpha%3A%20%22Adams%22%2C%0A%20%20%20%20bravo%3A%20%22Boston%22%2C%0A%20%20%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20%20%20delta%3A%20%22Denver%22%2C%0A%20%20%20%20echo%3A%20%22Easy%22%2C%0A%20%20%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20lookup%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
 var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };

  // Only change code above this line
  return lookup[val];
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by ltegman** [comment]
There's no reason you can't do `result = lookup[val];` above that line and leave the line below it alone, so this instruction is not wrong. Thanks and happy coding!

**Comment by apslagle** [comment]
I got confused on the same issue. You can just add another return above the line, but having two returns is inefficient coding and implies that the return does not need to be changed, which, as I said, I found confusing.

**Comment by BootsDuly** [comment]
I stared at this for a solid hour before checking this thread: the majority of my code was right all along, but I kept tinkering with everything _but_ the return line because the comments directed me to do that. Super confusing and almost made me give up!

**Comment by Xidousness** [comment]
Agreed, this was a tad confusing. I knew my code was correct but continued to fail. I added (result = lookup[val];) above the return line as noted above. Success.

**Comment by Oc3ans** [comment]
I had the same issue!

**Comment by DovidM** [comment]
Same

**Comment by mrburks** [comment]
So many having trouble with this, after the issue was closed and no changes yet. but the thread is closed. -- Don't get me wrong I'm not knocking "free" i get it. but "pride" and "accomplishment" was what drove the creators of this endeavor to do so. therefore by that token, shouldn't "pride" and "accomplishment" drive the need to be as good as possible? I'd say give the "Not-free" a run for their money!!

**Comment by grzegorzzajac1989** [comment]
Unreachable 'return' after 'return'.

**Comment by Tomllg** [comment]
@Xidousness Thanks ! It was horrible to find the solution

**Comment by Claudron** [comment]
Same here!
