### ISSUE TITLE
Stand in line ||   not sure why the empty array can't be checked, i think there's a bug

### ISSUE THREAD

**Issue by osayi** [FreeCodeCamp/FreeCodeCamp#6457]
Challenge [Stand in Line](http://www.freecodecamp.com/challenges/stand-in-line#?solution=%2F%2F%20%20arr%20%3D%20%5B2%2C4%2C7%2C9%2C3%5D%3B%0Aarr%20%3D%20%5B%5D%3B%0Afunction%20queue(arr%2C%20item)%20%7B%0A%0A%20%20newItem%20%3D%20arr.shift()%3B%0A%20%20arr%20%3D%20arr.push(item)%3B%2F%2F%20Your%20code%20here%0A%20%20if%20(typeof%20arr%20!%3D%3D%20null)%0A%20%20%20%20%7B%0A%20%20return%20newItem%3B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20%7D%0A%20%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(arr))%3B%0Aconsole.log(queue(arr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(arr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//  arr = [2,4,7,9,3];
arr = [];
function queue(arr, item) {

  newItem = arr.shift();
  arr = arr.push(item);// Your code here
  if (typeof arr !== null)
    {
  return newItem;  // Change this line
    }
 
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(arr));
console.log(queue(arr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(arr));

```

**Comment by AkiraLaine** [comment]
I'm assuming you're talking about this test:
> queue([], 1) should return 1
This isn't a bug. You're setting ```newItem``` to a value that doesn't exist. You need to push the item to the array first.

For future reference, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room.
