### ISSUE TITLE
Found the bonfire solved - Issue related

### ISSUE THREAD

**Issue by cerealCode** [FreeCodeCamp/FreeCodeCamp#6460]
Challenge [Caesars Cipher](http://www.freecodecamp.com/challenges/caesars-cipher#?solution=function%20rot13(encodedStr)%20%7B%0A%20%20var%20codeArr%20%3D%20encodedStr.split(%22%22)%3B%20%20%2F%2F%20String%20to%20Array%0A%20%20var%20decodedArr%20%3D%20%5B%5D%3B%20%2F%2F%20Your%20Result%20goes%20here%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20decodedArr%20%3D%20codeArr.map(function(c)%20%7B%0A%20%20%20%20var%20charCode%20%3D%20c.charCodeAt(0)%3B%0A%20%20%20%20if(charCode%20%3E%3D%2065%20%26%26%20charCode%20%3C%3D%2090)%20%7B%0A%20%20%20%20%20%20var%20decodedChar%20%3D%20charCode%20-%2013%20%3C%2065%20%3F%20charCode%20%2B%2013%20%3A%20charCode%20-%2013%3B%0A%20%20%20%20%20%20return%20String.fromCharCode(decodedChar)%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20c%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20decodedArr.join(%22%22)%3B%20%2F%2F%20Array%20to%20String%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function rot13(encodedStr) {
  var codeArr = encodedStr.split("");  // String to Array
  var decodedArr = []; // Your Result goes here
  // Only change code below this line
  decodedArr = codeArr.map(function(c) {
    var charCode = c.charCodeAt(0);
    if(charCode >= 65 && charCode <= 90) {
      var decodedChar = charCode - 13 < 65 ? charCode + 13 : charCode - 13;
      return String.fromCharCode(decodedChar);
    }
    return c;
  });
  
  
  // Only change code above this line
  return decodedArr.join(""); // Array to String
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

I have read the same issue in another thread; I don't know how many times I have compare my solutions and code with other campers, so I have no idea of how many of my codes have been replace. 

Does that have any influence when claiming my certifications? I learn a lot by comparing and reading other approaches, but I want to keep my code or at most do some twitches but manually. 

Isn't it's possible to add like a "lock" after a challenge it's passed, so only the user can manually open and rewrite it? Is it possible to know how many of my challenges have been altered?  

Thanks :)

**Comment by AkiraLaine** [comment]
You should have all of your different solutions on your profile page.

**Comment by cerealCode** [comment]
Profile in Freecodecamp?

**Comment by AkiraLaine** [comment]
Yep :D

**Comment by cerealCode** [comment]
Oh I know that, but I read my solutions get overwrite when I compare my solutions with others. Is that right?

**Comment by cerealCode** [comment]
Also, and most important, does it affect when claiming certifications?

**Comment by AkiraLaine** [comment]
No, it should create a separate solution - so you can see all of your different solutions.
And no. As long as you wrote the original solution.

**Comment by AkiraLaine** [comment]
Closing this since it's not an issue.

**Comment by cerealCode** [comment]
Than for the help :)

**Comment by ltegman** [comment]
If all you're doing is looking at the solution it only saves it to localStorage, not to the DB. Also, I'm fairly certain we no longer store multiple solutions for challenges, so don't submit the other person's answer or it will overwrite the one in your profile.

**Comment by cerealCode** [comment]
So how come I found a challenge I've never made solved, if it's only save the solution when submitted?

**Comment by ltegman** [comment]
It's not saved into the DB, but it is saved to localStorage before being submitted.
