### ISSUE TITLE
สวัสดี

### ISSUE THREAD

**Issue by nuttyto** [FreeCodeCamp/FreeCodeCamp#6462]
Challenge [Say Hello to HTML Elements](http://www.freecodecamp.com/challenges/say-hello-to-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; ALCATEL ONE TOUCH 7042D Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello</h1>

```

**Comment by AkiraLaine** [comment]
Hi @nuttyto. Could you please change the title (in English) and add a description of what sort of bug you are having?

**Comment by santakmishra** [comment]
I think this is just @nuttyto playing around and testing out Github features. The title **สวัสดี** is in Thai and means **Hello** :stuck_out_tongue: 
@AkiraLaine Please close issue :+1:

**Comment by hallaathrad** [comment]
sounds just like what @santakmishra says. closing
