### ISSUE TITLE
Hi, In this escape sequence in string challenge the below answer var myStr= "\\\ \t \t \r \n"  comes with output myStr= "\\ \t \t \r \n" and is correct and lets me move on to next challenge. As i was curious after a few more challenges in challenge constructing strings with variables i tried \\\\ in between and at the start of  var myName which comes back with 2 \\. I have attached the screen shots of this, just was curious which is correct to get 2 \\ should i use 4 \\\\ or 3 \\\. -thanks Manna Iyengar

### ISSUE THREAD

**Issue by Manna-Iyengar** [FreeCodeCamp/FreeCodeCamp#6465]
Challenge [Escape Sequences in Strings](http://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr= "\\\ \t \t \r \n" ; // Change this line


[Github-Escape-Sequence-issue.docx](https://github.com/FreeCodeCamp/FreeCodeCamp/files/105149/Github-Escape-Sequence-issue.docx)

**Comment by hallaathrad** [comment]
You'd need one escape per symbol... therefor \\\\ would give you \\.

This however is not a bug and could've been asked in the chatrooms. Please approach me or anyone on gitter for questions. Issue reporting is for bugs only :)

Thanks

**Comment by Manna-Iyengar** [comment]
Hi Justin,
      I agree to 4 "\\\\" should return 2 "\\". but if you can check the
challenge  on escape sequence in string 3 "\\\" is giving 2 "\\" output
whereas 4 "\\\\" successively is an error and  i checked with 4 "\\ \\"
with space(out of curiosity though i know it is an error because of space)
also gives error. so wanted to know which is correct and whether it is a
bug or not. attached screen shots of various outputs

Thanks
Manna Iyengar

[image: Inline image 1]


[image: Inline image 2]

**Comment by ltegman** [comment]
@Manna-Iyengar We're using `JSON.stringify(myStr)` to do the display on this challenge, which preserves escape characters. If we didn't the output would be worthless since most of the characters we ask you to use are whitespace that you would not see. In normal use where you're not doing `JSON.stringify` you will see the output you would expect from these escape characters.

**Comment by Manna-Iyengar** [comment]
Appreciate your reply and yes i could figure out that the escape sequence
is being preserved and hence the output but if you could make this
challenge a little better or if u could mention somewhere about the
preserving of escape sequence in this particular challenge it would help
right:-).
or else there will be quite few confusions:-).

Thanks
Manna Iyengar
