### ISSUE TITLE
Sample Stock Market App is Offline

### ISSUE THREAD

**Issue by StephenMayeux** [FreeCodeCamp/FreeCodeCamp#6471]
Challenge [Chart the Stock Market](http://www.freecodecamp.com/challenges/chart-the-stock-market) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.

There's an application error on Heroku, and we can't view the example stock market app.

**Comment by sludge256** [comment]
It looks like this will be take care of once https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6396 goes live.

**Comment by bugron** [comment]
Closing this issue as seems it's online now.

**Comment by StephenMayeux** [comment]
@bugron Thanks for the update. Looks like they replaced the old one with something else.
