### ISSUE TITLE
Check for Palindromes - Wrong Return Value

### ISSUE THREAD

**Issue by engincagatay** [FreeCodeCamp/FreeCodeCamp#6473]
The checklist on the left side states that "palindrome("0_0 (: /-\ :) 0-0") should return true." However, in my opinion, it should return false.

![untitled](https://cloud.githubusercontent.com/assets/7080863/12590198/07254bb6-c462-11e5-8cd7-ff838ca60baa.jpg)

**Comment by sludge256** [comment]
You should be removing **everything** that is not alphanumeric which would give you "0000".
Feel free to ask in the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need more clarification.

**Comment by ahmedelsaka862** [comment]
it return true because after you removed all symbols from it, it's length become 0!,
you should write a simple condition before you start,
if(str.length === 0) return true;
