### ISSUE TITLE
Misleading description

### ISSUE THREAD

**Issue by mmayes098** [FreeCodeCamp/FreeCodeCamp#6478]
Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20var%20strRemoveSpace%20%3D%20str.replace(%2F%5Cs%2B%2Fg%2C%20'')%3B%0A%20%20var%20strRemovePunc%20%3D%20strRemoveSpace.replace(%2F%5CW%2B%2Fg%2C%20'')%3B%0A%20%20var%20strLower%20%3D%20strRemovePunc.toLowerCase()%3B%0A%20%20var%20strSplit%20%3D%20strLower.split('')%3B%0A%20%20strSplit.reverse()%3B%0A%20%20var%20testString%20%3D%20strSplit.join('')%3B%0A%20%20if%20(strLower%3D%3D%3DtestString)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0A%0A%0Apalindrome(%22race%20car%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  var strRemoveSpace = str.replace(/\s+/g, '');
  var strRemovePunc = strRemoveSpace.replace(/\W+/g, '');
  var strLower = strRemovePunc.toLowerCase();
  var strSplit = strLower.split('');
  strSplit.reverse();
  var testString = strSplit.join('');
  if (strLower===testString) {
    return true;
  } else {
    return false;
  }
}



palindrome("race car");

```

Not necessarily a bug, per se, but in the description of the challenge it mentions that "You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes." However, if you do this, this last test: palindrome("0_0 (: /-\ :) 0-0") will fail. Just a little misleading in the description, is all.

**Comment by ltegman** [comment]
If you do that the string will become `0000` which would be a palindrome. Please use the [Help Chat] (https://gitter.im/FreeCodeCamp/Help) if you need further assistance. Thanks and happy coding!
