### ISSUE TITLE
Front-End Certification

### ISSUE THREAD

**Issue by kronengold** [FreeCodeCamp/FreeCodeCamp#6479]
Hi,
i completed all steps of Front-End training and claimed the certificate. I was presented with a certificate having wrong name (Berkeley Martinez) and a wrong date (October 3rd, 2015). There is no link on the main portfolio page to the certificate.
Can you look into it and fix it?
Thanks,
Benny

**Comment by SaintPeter** [comment]
@BerkeleyTrue Can you please stop trying to steal other people's certifications?  ;)

@kronengold He ought to be able to look into it.  We've been getting reports about this issue.

**Comment by kronengold** [comment]
@SaintPeter @BerkeleyTrue  Thanks for looking into it.

**Comment by CodeNonprofit** [comment]
@kronengold Hi Benny. When you navigate to the Claim Your Front End Certification challenge and you see the certification, this is just a sample. You must scroll down and complete the remaining 4 steps to actually claim your own. 

Can you verify that you did or did not perform this step? Then we'll go from there.

**Comment by kronengold** [comment]
@CodeNonprofit  Hi Michael, Yes I did go through the 4 steps (did it again) until I got to the **_Congratulations_** step and _**Submit and go to the Next Challenge**_.
Still no certificate.

**Comment by BerkeleyTrue** [comment]
@kronengold An error in challenge seed made it impossible for anyone to claim certifications but mistakenly let them complete the claim certification challenge.

I've pushed a hotfix to production. Looks like it is working properly. I've gone ahead and removed the faulty challenge from your record. If you visit the challenge to claim your certification again it should be working properly.

**Comment by kronengold** [comment]
@BerkeleyTrue  Now the certificate appears - **thanks**. Still...
The problem left is that when you save it as an image (save as), the name and date disappear. When you want to save it (print it) as PDF, it is bigger than both letter, A4 and A3 formats. 
Basically, right now it can only be displayed on FreeCodeCamp or screen capture it or snip it using a tool such as snipping tool in Windows.
Can you fix that (flatten the image) or add a PDF/JPG attachment?

**Comment by 12coderdark** [comment]
no tengo mi cretificado

**Comment by XxTACxTylerxX** [comment]
Hello
