### ISSUE TITLE
Submiting link to camper news results in 404 flash message

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#648]
Links still post successfully. Seems like the logic tries to redirect to the newly created news story with an incorrect url. May be related to dasherizing.

cc @terakilobyte

**Comment by terakilobyte** [comment]
Cool, I'll look into what exactly is going on.

**Comment by BerkeleyTrue** [comment]
Nathan: Man of Action!

**Comment by QuincyLarson** [comment]
I'm pretty sure this is because of your dasherization changes. We just need to update the save() to redirect to the story name dasherized by the new system instead of the old one.
