### ISSUE TITLE
Tests are inconsistent with question

### ISSUE THREAD

**Issue by bighitbiker3** [FreeCodeCamp/FreeCodeCamp#6480]
Challenge [Truncate a string](http://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20if(str.length%20%3E%20num)%7B%0A%20%20%20%20str%20%3D%20str.slice(0%2C%20num)%3B%0A%20%20%20%20str%20%3D%20str%20%2B%20%22...%22%3B%0A%20%20%7D%0A%20%20return%20str%3B%0A%7D%0A%0Atruncate(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This isn't really a bug, but more with the tests being inconsistent.  If the "..." adds to the string length then the bottom two tests are actually producing 4, and 5 characters respectively.  Even though the max number of characters should be 1 and 2 respectively. 

If the bottom two tests were to follow the rules for the other tests they would produce "." and ".." - correct?

**Comment by sludge256** [comment]
From the instructions,
>If the num is less than or equal to 3, then the length of the three dots is not added to the string length.

**Comment by bighitbiker3** [comment]
Wow. My bad 🙃

Elliott McNary
