### ISSUE TITLE
There console log gives the right output but the system, claims it's wrong  

### ISSUE THREAD

**Issue by osayi** [FreeCodeCamp/FreeCodeCamp#6481]
Challenge [Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(a%20%3C%200%20%7C%7C%20b%20%3C%200)%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C-2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if (a < 0 || b < 0){
    
    return "undefined";
  }
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,-2);

```

**Comment by sludge256** [comment]
You should be returning the value `undefined` not a string containing the word "undefined"
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined

**Comment by osayi** [comment]
oh wow, smh thanks!
