### ISSUE TITLE
Stuck on 'size your images'

### ISSUE THREAD

**Issue by eastking11** [FreeCodeCamp/FreeCodeCamp#6484]
![size your images issue - github](https://cloud.githubusercontent.com/assets/13161522/12607158/a975864a-c4a0-11e5-9295-3d02fabb2d87.png)
Challenge [Size your Images](http://www.freecodecamp.com/challenges/size-your-images#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
  .smaller-image {
    width: 100px;
  }
 
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by eastking11** [comment]
Tried reloading the page, checked my browser's zoom multiple times, maybe there's something wrong with the code? I'm still a huge newby but I don't see a problem with it..

**Comment by shaykyasin** [comment]
You haven't solved the challenge yet. Try adding the "smaller-image" class to the "img" element.

Next time when you have a problem, please try following the steps [here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) in order: 

Someone will close the issue as there is no actual bug.

**Comment by eastking11** [comment]
Oh great! Appreciate it and will do.

**Comment by usonokal** [comment]
im having the same problem, im also very new but i cant solve the issue

**Comment by Khamulenko** [comment]
Что же делать в этой сетуации? не ясно

**Comment by MarkPuchalaII** [comment]
Same issue, here. 
I've tried everything. 
I know it isn't me.

My code is right.
I've tried on the following: 

- Microsoft Edge
- Google Chrome
- Mozilla Firefox

 Edt

I think it's because I'm on a Surface Pro 4.
