### ISSUE TITLE
FALSE NEGATIVE: Comparison with the Greater Than Operator 

### ISSUE THREAD

**Issue by rodneystrong** [FreeCodeCamp/FreeCodeCamp#6485]
The exercise allows for nonstrict comparison yet the waypoint doesn't allow you to continue if you do val > '10' instead of val > 10.

Challenge [Comparison with the Greater Than Operator](http://www.freecodecamp.com/challenges/comparison-with-the-greater-than-operator#?solution=function%20myTest(val)%20%7B%0A%20%20if%20(val%20%3E%20100)%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Over%20100%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(val%20%3E%20'10')%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Over%2010%22%3B%0A%20%20%7D%0A%0A%20%20return%20%2210%20or%20Under%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  if (val > 100) {  // Change this line
    return "Over 100";
  }
  
  if (val > '10') {  // Change this line
    return "Over 10";
  }

  return "10 or Under";
}

// Change this value to test
myTest(10);

```

Cheers,
Alex

**Comment by rodneystrong** [comment]
Proof of my third party confirmation from the help section before posting this issue: 
![screen shot 2016-01-27 at 12 24 33 am](https://cloud.githubusercontent.com/assets/539962/12607826/bc7c85d6-c48c-11e5-9e54-8ddd9c504db7.png)
![screen shot 2016-01-27 at 12 24 45 am](https://cloud.githubusercontent.com/assets/539962/12607828/bc7f4078-c48c-11e5-81eb-53b551a95ecd.png)
![screen shot 2016-01-27 at 12 24 56 am](https://cloud.githubusercontent.com/assets/539962/12607825/bc7af09a-c48c-11e5-8847-989a08674f59.png)
![screen shot 2016-01-27 at 12 25 05 am](https://cloud.githubusercontent.com/assets/539962/12607827/bc7d94c6-c48c-11e5-8c11-b13dc6b85ade.png)

**Comment by alistermada** [comment]
Found out why the test is failing in the source code. It's checking to see if there are at least two instances in the code where `val` is immediately followed by `>` and at least one digit (with optional spaces in between). This doesn't catch `val > '10'` since there's a quote before the number.

I think the test case shouldn't be so strict as the rest of the challenge does explicitly mention that data types are converted while comparing.

**Comment by drcharlie98** [comment]
I got 7 green ticks and one red tick on this but I can't understand why. It says "testGreaterOrEqual(10) should return "10 or Over" "  which my test surely do. Unless there is something I am totally missing. Please help :)



`function testGreaterOrEqual(val) {
  if (val >= 20) {  // Change this line
    return "20 or Over";
  }
  
  if (val >= 11) {  // Change this line
    return "10 or Over";
  }

  return "9 or Under";
}

// Change this value to test
testGreaterOrEqual(35 >= 2);
testGreaterOrEqual(35 >= 20);
testGreaterOrEqual(3 >= 7);`

**Comment by zombierevival** [comment]
boi

**Comment by Faikabbaszadeh** [comment]
function testGreaterThan(val) {
  if (val > 100) {  // Change this line
    return "Over 100";
  }
  
  if (val > 10) {  // Change this line
    return "Over 10";
  }

  return "10 or Under";
}

// Change this value to test
testGreaterThan(10);

**Comment by OgunniyiOwamamwen** [comment]
function testGreaterOrEqual(val) {
  if (val >= 20) {  // Change this line
    return "20 or Over";
  }
  
  if (val >= 10) {  // Change this line
    return "10 or Over";
  }

  return "9 or Under";
}

// Change this value to test
testGreaterOrEqual(10);

**Comment by texas2010** [comment]
@OgunniyiOwamamwen, no need to keep posting your code on this issues.  if you want to provide a help to people. please use freeCodeCamp chat room. thanks!
 You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

This GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by power5678** [comment]
whats wrong
thanks

function testGreaterThan(val) {
  if (val>100) { { // Change this line
    return "Over 100";
  }
  
  if (val>10) {  // Change this line
    return "Over 100";
  }

  return "10 or under";
}
return "Over 10";
}
// Change this value to test
testGreaterThan(10);

**Comment by texas2010** [comment]
@power5678 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
