### ISSUE TITLE
Claimed Front End Certificate

### ISSUE THREAD

**Issue by 8BitProxy** [FreeCodeCamp/FreeCodeCamp#6488]
Hey guys I am so sorry but I accidentally claimed my Front End Certificate without meaning to, I was curious to see if it had progress or anything because it said in one of the stages 'Click this to verify' so I ddid and then clicked next and it told me it was added to my profile, I don't think I have done it I have only just finished the HTML section and I am moving on JS now

Thanks!

~Proxy

**Comment by AkiraLaine** [comment]
Don't worry, it won't add it until you have actually done all the challenges required.

Happy Coding :smile:

**Comment by BerkeleyTrue** [comment]
@8BitProxy 
An error in challenge seed made it impossible for anyone to claim certifications but mistakenly let them complete the claim certification challenge.

I've pushed a hotfix to production. Looks like it is working properly. I've gone ahead and removed the faulty challenge from your record. If you visit the challenge to claim your certification again it should be working properly.

Happy Coding!
