### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by bgwilson01** [FreeCodeCamp/freecodecamp#649]
For the first task the exercise says to: "Wrap your all of your checkboxes inside one div with the class "row"." However the checkboxes had already been put into a div with the class row in the previous exercise. To get the exercise to recognize as complete I had to wrap the form text box and submit button in a div with the class "row".

**Comment by terakilobyte** [comment]
Thanks for the report on this. We have a fix in staging along with a bunch of other ones and will push it up soon.
