### ISSUE TITLE
Translation to Spanish: Verify and update translation of advanced-bonfires.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6494]
- [x]  Validate US Telephone Numbers
- [x]  Symmetric Difference
- [x]  Exact Change
- [x]  Inventory Update
- [x]  No repeats please
- [x]  Friendly Date Ranges
- [x]  Make a Person
- [x]  Map the Debris
- [x]  Pairwise

**Comment by bugron** [comment]
@justinian336 you can just reopen and rename your closed issues ;)

**Comment by justinian336** [comment]
@bugron My bad, just noticed the shiny `Edit' button over there. Do you mind if we use these new ones to update the translation for the new curriculum.

**Comment by bugron** [comment]
Of course I don't mind, that was just a tip, thanks for your hard work.

**Comment by justinian336** [comment]
Thanks to you for the tip!

**Comment by vtamara** [comment]
- [ ] Validate US Telephone Numbers
- [ ] Symmetric Difference
- [ ] Exact Change
- [ ] Inventory Update
- [ ] No repeats please
- [ ] Friendly Date Ranges
- [ ] Make a Person
- [ ] Map the Debris
- [ ] Pairwise
