### ISSUE TITLE
Translation to Spanish: Verify and update translation of basic-bonfires.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6495]

**Comment by vtamara** [comment]
- [X] Get Set for our Algorithm Challenges
- [X] Reverse a String
- [X] Factorialize a Number
- [X] Check for Palindromes
- [X] Find the Longest Word in a String
- [X] Title Case a Sentence
- [X] Return Largest Numbers in Arrays
- [X] Confirm the Ending
- [X] Repeat a string repeat a string
- [X] Truncate a string
- [X] Chunky Monkey
- [X] Slasher Flick
- [X] Mutations
- [X] Falsy Bouncer
- [X] Seek and Destroy
- [X] Where do I belong
- [ ] Caesar's Cipher

**Comment by justinian336** [comment]
Shall I do the remaining one?
