### ISSUE TITLE
Translation to Spanish: Verify and update translation of basic-javascript.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6496]
- [x]  Comment your JavaScript Code
- [x]  Declare JavaScript Variables
- [x]  Storing Values with the Equal Operator
- [x]  Initializing Variables with the Equal Operator
- [x]  Understanding Uninitialized Variables
- [x]  Understanding Case Sensitivity in Variables
- [x]  Add Two Numbers with JavaScript
- [x]  Subtract One Number from Another with JavaScript
- [x]  Multiply Two Numbers with JavaScript
- [x]  Divide One Number by Another with JavaScript
- [x]  Increment a Number with Javascript
- [x]  Decrement a Number with Javascript
- [x]  Create Decimal Numbers with JavaScript
- [x]  Multiply Two Decimals with JavaScript
- [x]  Divide one Decimal by Another with JavaScript
- [x]  Finding a Remainder in Javascript
- [x]  Assignment with Plus Equals
- [x]  Assignment with Minus Equals
- [x]  Assignment with Times Equals
- [x]  Assignment with Divided by Equals
- [x]  Convert Celsius to Fahrenheit
- [x]  Declare String Variables
- [x]  Escaping Literal Quotes in Strings
- [x]  Quoting Strings with Single Quotes
- [x]  Escape Sequences in Strings
- [x]  Concatenating Strings with Plus Operator
- [x]  Concatenating Strings with the Plus Equals Operator
- [x]  Constructing Strings with Variables
- [x]  Appending Variables to Strings
- [x]  Find the Length of a String
- [x]  Use Bracket Notation to Find the First Character in a String
- [x]  Understand String Immutability
- [x]  Use Bracket Notation to Find the Nth Character in a String
- [x]  Use Bracket Notation to Find the Last Character in a String
- [x]  Use Bracket Notation to Find the Nth-to-Last Character in a String
- [x]  Word Blanks
- [x]  Store Multiple Values in one Variable using JavaScript Arrays
- [x]  Nest one Array within Another Array
- [x]  Access Array Data with Indexes
- [x]  Modify Array Data With Indexes
- [x]  Access Multi-Dimensional Arrays With Indexes
- [x]  Manipulate Arrays With push()
- [x]  Manipulate Arrays With pop()
- [x]  Manipulate Arrays With shift()
- [x]  Manipulate Arrays With unshift()
- [x]  Shopping List
- [x]  Write Reusable JavaScript with Functions
- [x]  Passing Values to Functions with Arguments
- [x]  Global Scope and Functions
- [x]  Local Scope and Functions
- [x]  Global vs. Local Scope in Functions
- [x]  Return a Value from a Function with Return
- [x]  Assignment with a Returned Value
- [x]  Stand in Line
- [x]  Understanding Boolean Values
- [x]  Use Conditional Logic with If Statements
- [x]  Comparison with the Equality Operator
- [x]  Comparison with the Strict Equality Operator
- [x]  Comparison with the Inequality Operator
- [x]  Comparison with the Strict Inequality Operator
- [x]  Comparison with the Greater Than Operator
- [x]  Comparison with the Greater Than Or Equal To Operator
- [x]  Comparison with the Less Than Operator
- [x]  Comparison with the Less Than Or Equal To Operator
- [x]  Comparisons with the Logical And Operator
- [x]  Comparisons with the Logical Or Operator
- [x]  Introducing Else Statements
- [x]  Introducing Else If Statements
- [x]  Logical Order in If Else Statements
- [x]  Chaining If Else Statements
- [x]  Golf Code
- [x]  Selecting from many options with Switch Statements
- [x]  Adding a default option in Switch statements
- [x]  Multiple Identical Options in Switch Statements
- [x]  Replacing If Else Chains with Switch
- [x]  Returning Boolean Values from Functions
- [x]  Return Early Pattern for Functions
- [x]  Counting Cards
- [x]  Build JavaScript Objects
- [x]  Accessing Objects Properties with the Dot Operator
- [x]  Accessing Objects Properties with Bracket Notation
- [x]  Accessing Objects Properties with Variables
- [x]  Updating Object Properties
- [x]  Add New Properties to a JavaScript Object
- [x]  Delete Properties from a JavaScript Object
- [x]  Using Objects for Lookups
- [x]  Testing Objects for Properties
- [x]  Introducing JavaScript Object Notation (JSON)
- [x]  Accessing Nested Objects in JSON
- [x]  Accessing Nested Arrays in JSON
- [x]  Record Collection
- [x]  Iterate with JavaScript For Loops
- [x]  Iterate Odd Numbers With a For Loop
- [x]  Count Backwards With a For Loop
- [x]  Iterate Through an Array with a For Loop
- [x]  Nesting For Loops
- [x]  Iterate with JavaScript While Loops
- [x]  Profile Lookup
- [x]  Generate Random Fractions with JavaScript
- [x]  Generate Random Whole Numbers with JavaScript
- [x]  Generate Random Whole Numbers within a Range
- [x]  Sift through Text with Regular Expressions
- [x]  Find Numbers with Regular Expressions
- [x]  Find Whitespace with Regular Expressions
- [x]  Invert Regular Expression Matches with JavaScript
- [x]  Create a JavaScript Slot Machine
- [x]  Add your JavaScript Slot Machine Slots
- [x]  Bring your JavaScript Slot Machine to Life
- [x]  Give your JavaScript Slot Machine some Stylish Images

**Comment by jorgeruvalcaba** [comment]
Working on it.

**Comment by justinian336** [comment]
@jorgeruvalcaba roger that! Thank you!

**Comment by vtamara** [comment]
Este archivo había sido traducido antes del cambio de currículo.  Por error se habían perdido las traducciones.  Por lo visto pronto volveran a ser integradas las traducciones que ya se habían hecho ver: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6562

**Comment by vtamara** [comment]
Efectivamente ya nos hicieron el favor de reintegrar las traducciones anteriores.  @jorgeruvalcaba espero que no te haya generado mucho trabajo extra.  Disculpas (aunque yo no las había retirado).

**Comment by vtamara** [comment]
- [X] Comment your JavaScript Code
- [X] Declare JavaScript Variables
- [ ] Storing Values with the Equal Operator
- [ ] Initializing Variables with the Equal Operator
- [ ] Understanding Uninitialized Variables
- [ ] Understanding Case Sensitivity in Variables
- [X] Add Two Numbers with JavaScript
- [X] Subtract One Number from Another with JavaScript
- [X] Multiply Two Numbers with JavaScript
- [X] Divide One Number by Another with JavaScript
- [ ] Increment a Number with Javascript
- [ ] Decrement a Number with Javascript
- [X] Create Decimal Numbers with JavaScript
- [X] Multiply Two Decimals with JavaScript
- [X] Divide one Decimal by Another with JavaScript
- [ ] Finding a Remainder in Javascript
- [ ] Assignment with Plus Equals
- [ ] Assignment with Minus Equals
- [ ] Assignment with Times Equals
- [ ] Assignment with Divided by Equals
- [ ] Convert Celsius to Fahrenheit
- [X] Declare String Variables
- [ ] Escaping Literal Quotes in Strings
- [ ] Quoting Strings with Single Quotes
- [ ] Escape Sequences in Strings
- [ ] Concatenating Strings with Plus Operator
- [ ] Concatenating Strings with the Plus Equals Operator
- [ ] Constructing Strings with Variables
- [ ] Appending Variables to Strings
- [X] Find the Length of a String
- [X] Use Bracket Notation to Find the First Character in a String
- [ ] Understand String Immutability
- [X] Use Bracket Notation to Find the Nth Character in a String
- [X] Use Bracket Notation to Find the Last Character in a String
- [X] Use Bracket Notation to Find the Nth-to-Last Character in a String
- [ ] Word Blanks
- [X] Store Multiple Values in one Variable using JavaScript Arrays
- [X] Nest one Array within Another Array
- [X] Access Array Data with Indexes
- [X] Modify Array Data With Indexes
- [ ] Access Multi-Dimensional Arrays With Indexes
- [X] Manipulate Arrays With push()
- [X] Manipulate Arrays With pop()
- [X] Manipulate Arrays With shift()
- [X] Manipulate Arrays With unshift()
- [ ] Shopping List
- [X] Write Reusable JavaScript with Functions
- [ ] Passing Values to Functions with Arguments
- [ ] Global Scope and Functions
- [ ] Local Scope and Functions
- [ ] Global vs. Local Scope in Functions
- [ ] Return a Value from a Function with Return
- [ ] Assignment with a Returned Value
- [ ] Stand in Line
- [X] Understanding Boolean Values
- [X] Use Conditional Logic with If Statements
- [ ] Comparison with the Equality Operator
- [ ] Comparison with the Strict Equality Operator
- [ ] Comparison with the Inequality Operator
- [ ] Comparison with the Strict Inequality Operator
- [ ] Comparison with the Greater Than Operator
- [ ] Comparison with the Greater Than Or Equal To Operator
- [ ] Comparison with the Less Than Operator
- [ ] Comparison with the Less Than Or Equal To Operator
- [ ] Comparisons with the Logical And Operator
- [ ] Comparisons with the Logical Or Operator
- [ ] Introducing Else Statements
- [ ] Introducing Else If Statements
- [ ] Logical Order in If Else Statements
- [ ] Chaining If Else Statements
- [ ] Golf Code
- [ ] Selecting from many options with Switch Statements
- [ ] Adding a default option in Switch statements
- [ ] Multiple Identical Options in Switch Statements
- [ ] Replacing If Else Chains with Switch
- [ ] Returning Boolean Values from Functions
- [ ] Return Early Pattern for Functions
- [ ] Counting Cards
- [X] Build JavaScript Objects
- [ ] Accessing Objects Properties with the Dot Operator
- [ ] Accessing Objects Properties with Bracket Notation
- [ ] Accessing Objects Properties with Variables
- [X] Updating Object Properties
- [X] Add New Properties to a JavaScript Object
- [X] Delete Properties from a JavaScript Object
- [ ] Using Objects for Lookups
- [ ] Testing Objects for Properties
- [ ] Introducing JavaScript Object Notation (JSON)
- [ ] Accessing Nested Objects in JSON
- [ ] Accessing Nested Arrays in JSON
- [ ] Record Collection
- [X] Iterate with JavaScript For Loops
- [X] Iterate Odd Numbers With a For Loop
- [X] Count Backwards With a For Loop
- [ ] Iterate Through an Array with a For Loop
- [ ] Nesting For Loops
- [X] Iterate with JavaScript While Loops
- [ ] Profile Lookup
- [X] Generate Random Fractions with JavaScript
- [X] Generate Random Whole Numbers with JavaScript
- [X] Generate Random Whole Numbers within a Range
- [X] Sift through Text with Regular Expressions
- [X] Find Numbers with Regular Expressions
- [X] Find Whitespace with Regular Expressions
- [X] Invert Regular Expression Matches with JavaScript
- [X] Create a JavaScript Slot Machine
- [X] Add your JavaScript Slot Machine Slots
- [X] Bring your JavaScript Slot Machine to Life
- [X] Give your JavaScript Slot Machine some Stylish Images

**Comment by jorgeruvalcaba** [comment]
No hay problema, integraré las que faltan. Gracias por avisar @vtamara

**Comment by vtamara** [comment]
Este es el archivo con más cambios de traducción pendientes.   Te pido el favor de hacer commit de lo que llevas para poder apoyar la completación --tal parece que muy pronto empiezan a operar rutas en español con lo cual quedará visible lo que hemos traducido (se estaba hablando de mañana sábado).

**Comment by justinian336** [comment]
@jorgeruvalcaba @vtamara I can work on this tonight if you guys let me know which part is pending to be done.

**Comment by jorgeruvalcaba** [comment]
@vtamara @justinian336 Enterado, el transcurso del día haré commit.

**Comment by jorgeruvalcaba** [comment]
Se integraron las siguientes challenges:

- [x] Storing Values with the Equal Operator.
- [x] Initializing Variables with the Equal Operator.
- [x] Understanding Uninitialized Variables.
- [x] Understanding Case Sensitivity in Variables.
- [x] Increment a Number with Javascript.
- [x] Decrement a Number with Javascript.
- [x] Finding a Remainder in Javascript
- [x] Assignment with Plus Equals
- [x] Assignment with Minus Equals
- [x] Assignment with Times Equals
- [x] Assignment with Divided by Equals
- [x] Convert Celsius to Fahrenheit

Continúo trabajando.

**Comment by vtamara** [comment]
@jorgeruvalcaba te invito a hacer una solicitud de cambio (pull request) de lo que llevas y a solicitar revisión en el canal, después te invito a realizar las mejoras que te sugieran y a seguir traduciendo de arriba hacía abajo.  @justinian336 podría comenzar de abajo hacía arriba.

**Comment by jorgeruvalcaba** [comment]
Listo @vtamara, me parece bien. Continuaré traduciendo de arriba hacia abajo.

**Comment by jorgeruvalcaba** [comment]
Se integraron estos nuevos challenges:

- [x] Escaping Literal Quotes in Strings.
- [x] Quoting Strings with Single Quotes.
- [x] Escape Sequences in Strings.
- [x] Concatenating Strings with Plus Operator.
- [x] Concatenating Strings with the Plus Equals Operator.
- [x] Constructing Strings with Variables.
- [x] Appending Variables to Strings.
- [x] Understand String Immutability
- [x] Word Blanks
- [x] Access Multi-Dimensional Arrays With Indexes

**Comment by jorgeruvalcaba** [comment]
### List updated:

- [x] Comment your JavaScript Code.
- [x] Declare JavaScript Variables.
- [x] Storing Values with the Equal Operator
- [x] Initializing Variables with the Equal Operator
- [x] Understanding Uninitialized Variables
- [x] Understanding Case Sensitivity in Variables
- [x] Add Two Numbers with JavaScript
- [x] Subtract One Number from Another with JavaScript
- [x] Multiply Two Numbers with JavaScript
- [x] Divide One Number by Another with JavaScript
- [x] Increment a Number with Javascript
- [x] Decrement a Number with Javascript
- [x] Create Decimal Numbers with JavaScript
- [x] Multiply Two Decimals with JavaScript
- [x] Divide one Decimal by Another with JavaScript
- [x] Finding a Remainder in Javascript
- [x] Assignment with Plus Equals
- [x] Assignment with Minus Equals
- [x] Assignment with Times Equals
- [x] Assignment with Divided by Equals
- [x] Convert Celsius to Fahrenheit
- [x] Declare String Variables
- [x] Escaping Literal Quotes in Strings
- [x] Quoting Strings with Single Quotes
- [x] Escape Sequences in Strings
- [x] Concatenating Strings with Plus Operator
- [x] Concatenating Strings with the Plus Equals Operator
- [x] Constructing Strings with Variables
- [x] Appending Variables to Strings
- [x] Find the Length of a String
- [x] Use Bracket Notation to Find the First Character in a String
- [x] Understand String Immutability
- [x] Use Bracket Notation to Find the Nth Character in a String
- [x] Use Bracket Notation to Find the Last Character in a String
- [x] Use Bracket Notation to Find the Nth-to-Last Character in a String
- [x] Word Blanks
- [x] Store Multiple Values in one Variable using JavaScript Arrays
- [x] Nest one Array within Another Array
- [x] Access Array Data with Indexes
- [x] Modify Array Data With Indexes
- [x] Access Multi-Dimensional Arrays With Indexes
- [x] Manipulate Arrays With push()
- [x] Manipulate Arrays With pop()
- [x] Manipulate Arrays With shift()
- [x] Manipulate Arrays With unshift()
- [ ] Shopping List
- [x] Write Reusable JavaScript with Functions
- [ ] Passing Values to Functions with Arguments
- [ ] Global Scope and Functions
- [ ] Local Scope and Functions
- [ ] Global vs. Local Scope in Functions
- [ ] Return a Value from a Function with Return
- [ ] Assignment with a Returned Value
- [ ] Stand in Line
- [x] Understanding Boolean Values
- [x] Use Conditional Logic with If Statements
- [ ] Comparison with the Equality Operator
- [ ] Comparison with the Strict Equality Operator
- [ ] Comparison with the Inequality Operator
- [ ] Comparison with the Strict Inequality Operator
- [ ] Comparison with the Greater Than Operator
- [ ] Comparison with the Greater Than Or Equal To Operator
- [ ] Comparison with the Less Than Operator
- [ ] Comparison with the Less Than Or Equal To Operator
- [ ] Comparisons with the Logical And Operator
- [ ] Comparisons with the Logical Or Operator
- [ ] Introducing Else Statements
- [ ] Introducing Else If Statements
- [ ] Logical Order in If Else Statements
- [ ] Chaining If Else Statements
- [ ] Golf Code
- [ ] Selecting from many options with Switch Statements
- [ ] Adding a default option in Switch statements
- [ ] Multiple Identical Options in Switch Statements
- [ ] Replacing If Else Chains with Switch
- [ ] Returning Boolean Values from Functions
- [ ] Return Early Pattern for Functions
- [ ] Counting Cards
- [x] Build JavaScript Objects
- [ ] Accessing Objects Properties with the Dot Operator
- [ ] Accessing Objects Properties with Bracket Notation
- [ ] Accessing Objects Properties with Variables
- [x] Updating Object Properties
- [x] Add New Properties to a JavaScript Object
- [x] Delete Properties from a JavaScript Object
- [ ] Using Objects for Lookups
- [ ] Testing Objects for Properties
- [ ] Introducing JavaScript Object Notation (JSON)
- [ ] Accessing Nested Objects in JSON
- [ ] Accessing Nested Arrays in JSON
- [ ] Record Collection
- [x] Iterate with JavaScript For Loops
- [x] Iterate Odd Numbers With a For Loop
- [x] Count Backwards With a For Loop
- [ ]Iterate Through an Array with a For Loop
- [ ]Nesting For Loops
- [x] Iterate with JavaScript While Loops
- [ ] Profile Lookup
- [x] Generate Random Fractions with JavaScript
- [x] Generate Random Whole Numbers with JavaScript
- [x] Generate Random Whole Numbers within a Range
- [x] Sift through Text with Regular Expressions
- [x] Find Numbers with Regular Expressions
- [x] Find Whitespace with Regular Expressions
- [x] Invert Regular Expression Matches with JavaScript
- [x] Create a JavaScript Slot Machine
- [x] Add your JavaScript Slot Machine Slots
- [x] Bring your JavaScript Slot Machine to Life
- [x] Give your JavaScript Slot Machine some Stylish Images

**Comment by jorgeruvalcaba** [comment]
Challenges translated to Spanish:

- [x] Shopping List.
- [x] Passing Values to Functions with Arguments.
- [x] Global Scope and Functions.
- [x] Local Scope and Functions.
- [x] Global vs. Local Scope in Functions.
- [x] Return a Value from a Function with Return.
- [x] Assignment with a Returned Value.
- [x] Stand in Line.
- [x] Comparison with the Equality Operator.
- [x] Comparison with the Strict Equality Operator.
- [x] Comparison with the Inequality Operator.

**Comment by justinian336** [comment]
Gracias @jorgeruvalcaba, yo voy actualizando la lista conforme vas avanzando.

**Comment by jorgeruvalcaba** [comment]
###New challenges translated to spanish.

- [x] Comparison with the Strict Inequality Operator.
- [x] Comparison with the Greater Than Operator.
- [x] Comparison with the Greater Than Or Equal To Operator.
- [x] Comparison with the Less Than Operator.
- [x] Comparison with the Less Than Or Equal To Operator.
- [x] Comparisons with the Logical And Operator.
- [x] Comparisons with the Logical Or Operator.
- [x] Introducing Else Statements.
- [x] Introducing Else If Statements.
- [x] Logical Order in If Else Statements.
- [x] Chaining If Else Statements.
- [x] Golf Code.
- [x] Selecting from many options with Switch Statements.
- [x] Adding a default option in Switch statements.
- [x] Multiple Identical Options in Switch Statements.
- [x] Replacing If Else Chains with Switch.
- [x] Returning Boolean Values from Functions.
- [x] Return Early Pattern for Functions.
- [x] Counting Cards.
- [x] Accessing Objects Properties with the Dot Operator.
- [x] Accessing Objects Properties with Bracket Notation.
- [x] Accessing Objects Properties with Variables.
- [x] Using Objects for Lookups.
- [x] Testing Objects for Properties.
- [x] Introducing JavaScript Object Notation (JSON).
- [x] Accessing Nested Objects in JSON.
- [x] Accessing Nested Arrays in JSON.
- [x] Record Collection.
- [x] Iterate Through an Array with a For Loop.
- [x] Nesting For Loops.
- [x] Profile Lookup.

With this the list would be completed.

**Comment by justinian336** [comment]
Great work @jorgeruvalcaba, that was a long one! Can you make the PR so we can start the QA?
