### ISSUE TITLE
Translation to Spanish: Verify and update translation of basic-ziplines.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6497]
- [x]  Get Set for our Front End Development Projects
- [x]  Build a Personal Portfolio Webpage
- [x]  Build a Random Quote Machine
- [x]  Build a JavaScript Calculator
- [x]  Build a Pomodoro Clock

**Comment by vtamara** [comment]
- [X] Get Set for our Front End Development Projects
- [X] Build a Personal Portfolio Webpage
- [X] Build a Random Quote Machine
- [X] Build a JavaScript Calculator
- [X] Build a Pomodoro Clock

**Comment by vtamara** [comment]
Working on this one.

**Comment by vtamara** [comment]
Working on this one
