### ISSUE TITLE
Translation to Spanish: Verify and update translation of bootstrap.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6498]
- [ ]  Use Responsive Design with Bootstrap Fluid Containers
- [ ]  Make Images Mobile Responsive
- [ ]  Center Text with Bootstrap
- [ ]  Create a Bootstrap Button
- [ ]  Create a Block Element Bootstrap Button
- [ ]  Taste the Bootstrap Button Color Rainbow
- [ ]  Call out Optional Actions with Button Info
- [ ]  Warn your Users of a Dangerous Action
- [ ]  Use the Bootstrap Grid to Put Elements Side By Side
- [ ]  Ditch Custom CSS for Bootstrap
- [ ]  Use Spans for Inline Elements
- [ ]  Create a Custom Heading
- [ ]  Add Font Awesome Icons to our Buttons
- [ ]  Add Font Awesome Icons to all of our Buttons
- [ ]  Responsively Style Radio Buttons
- [ ]  Responsively Style Checkboxes
- [ ]  Style Text Inputs as Form Controls
- [ ]  Line up Form Elements Responsively with Bootstrap
- [ ]  Create a Bootstrap Headline
- [ ]  House our page within a Bootstrap Container Fluid Div
- [ ]  Create a Bootstrap Row
- [ ]  Split your Bootstrap Row
- [ ]  Create Bootstrap Wells
- [ ]  Add Elements within your Bootstrap Wells
- [ ]  Apply the Default Bootstrap Button Style
- [ ]  Create a Class to Target with jQuery Selectors
- [ ]  Add ID Attributes to Bootstrap Elements
- [ ]  Label Bootstrap Wells
- [ ]  Give Each Element a Unique ID
- [ ]  Label Bootstrap Buttons
- [ ]  Use Comments to Clarify Code

**Comment by vtamara** [comment]
- [X] Use Responsive Design with Bootstrap Fluid Containers
- [X] Make Images Mobile Responsive
- [X] Center Text with Bootstrap
- [X] Create a Bootstrap Button
- [X] Create a Block Element Bootstrap Button
- [X] Taste the Bootstrap Button Color Rainbow
- [X] Call out Optional Actions with Button Info
- [X] Warn your Users of a Dangerous Action
- [X] Use the Bootstrap Grid to Put Elements Side By Side
- [X] Ditch Custom CSS for Bootstrap
- [X] Use Spans for Inline Elements
- [X] Create a Custom Heading
- [X] Add Font Awesome Icons to our Buttons
- [X] Add Font Awesome Icons to all of our Buttons
- [X] Responsively Style Radio Buttons
- [X] Responsively Style Checkboxes
- [X] Style Text Inputs as Form Controls
- [X] Line up Form Elements Responsively with Bootstrap
- [X] Create a Bootstrap Headline
- [X] House our page within a Bootstrap Container Fluid Div
- [X] Create a Bootstrap Row
- [X] Split your Bootstrap Row
- [X] Create Bootstrap Wells
- [X] Add Elements within your Bootstrap Wells
- [X] Apply the Default Bootstrap Button Style
- [X] Create a Class to Target with jQuery Selectors
- [X] Add ID Attributes to Bootstrap Elements
- [X] Label Bootstrap Wells
- [X] Give Each Element a Unique ID
- [X] Label Bootstrap Buttons
- [X] Use Comments to Clarify Code

**Comment by vtamara** [comment]
Working on this one
