### ISSUE TITLE
Translation to Spanish: Verify and update translation of gear-up-for-success.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6500]
- [x]  Browse Camper News
- [x]  Reference our Wiki
- [x]  Join our LinkedIn Alumni Network
- [x]  Commit to a Goal and a Nonprofit

**Comment by vtamara** [comment]
- [X] Learn how Free Code Camp Works
- [X] Create a GitHub Account and Join our Chat Rooms
- [X] Configure your Code Portfolio
- [X] Join a Campsite in Your City
- [X] Learn What to Do If You Get Stuck

**Comment by bugron** [comment]
This issue is closed by https://github.com/FreeCodeCamp/FreeCodeCamp/commit/e474f5338522a3e61f70d9c8f61f8a02eb3a0797.
