### ISSUE TITLE
Translation to Spanish: Verify and update translation of html5-and-css.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6501]
- [x]  Say Hello to HTML Elements
- [x]  Headline with the h2 Element
- [x]  Inform with the Paragraph Element
- [x]  Uncomment HTML
- [x]  Comment out HTML
- [x]  Fill in the Blank with Placeholder Text
- [x]  Delete HTML Elements
- [x]  Change the Color of Text
- [x]  Use CSS Selectors to Style Elements
- [x]  Use a CSS Class to Style an Element
- [x]  Style Multiple Elements with a CSS Class
- [x]  Change the Font Size of an Element
- [x]  Set the Font Family of an Element
- [x]  Import a Google Font
- [x]  Specify How Fonts Should Degrade
- [x]  Add Images to your Website
- [x]  Size your Images
- [x]  Add Borders Around your Elements
- [x]  Add Rounded Corners with a Border Radius
- [x]  Make Circular Images with a Border Radius
- [x]  Link to External Pages with Anchor Elements
- [x]  Nest an Anchor Element within a Paragraph
- [x]  Make Dead Links using the Hash Symbol
- [x]  Turn an Image into a Link
- [x]  Add Alt Text to an Image for Accessibility
- [x]  Create a Bulleted Unordered List
- [x]  Create an Ordered List
- [x]  Create a Text Field
- [x]  Add Placeholder Text to a Text Field
- [x]  Create a Form Element
- [x]  Add a Submit Button to a Form
- [x]  Use HTML5 to Require a Field
- [x]  Create a Set of Radio Buttons
- [x]  Create a Set of Checkboxes
- [x]  Check Radio Buttons and Checkboxes by Default
- [x]  Nest Many Elements within a Single Div Element
- [x]  Give a Background Color to a Div Element
- [x]  Set the ID of an Element
- [x]  Use an ID Attribute to Style an Element
- [x]  Adjusting the Padding of an Element
- [x]  Adjust the Margin of an Element
- [x]  Add a Negative Margin to an Element
- [x]  Add Different Padding to Each Side of an Element
- [x]  Add Different Margins to Each Side of an Element
- [x]  Use Clockwise Notation to Specify the Padding of an Element
- [x]  Use Clockwise Notation to Specify the Margin of an Element
- [x]  Style the HTML Body Element
- [x]  Inherit Styles from the Body Element
- [x]  Prioritize One Style Over Another
- [x]  Override Styles in Subsequent CSS
- [x]  Override Class Declarations by Styling ID Attributes
- [x]  Override Class Declarations with Inline Styles
- [x]  Override All Other Styles by using Important
- [x]  Use Hex Code for Specific Colors
- [x]  Use Hex Code to Color Elements White
- [x]  Use Hex Code to Color Elements Red
- [x]  Use Hex Code to Color Elements Green
- [x]  Use Hex Code to Color Elements Blue
- [x]  Use Hex Code to Mix Colors
- [x]  Use Hex Code to Color Elements Gray
- [x]  Use Hex Code for Specific Shades of Gray
- [x]  Use Abbreviated Hex Code
- [x]  Use RGB values to Color Elements
- [x]  Use RGB to Color Elements White
- [x]  Use RGB to Color Elements Red
- [x]  Use RGB to Color Elements Green
- [x]  Use RGB to Color Elements Blue
- [x]  Use RGB to Mix Colors

**Comment by vtamara** [comment]
- [X] Say Hello to HTML Elements
- [X] Headline with the h2 Element
- [X] Inform with the Paragraph Element
- [X] Uncomment HTML
- [X] Comment out HTML
- [X] Fill in the Blank with Placeholder Text
- [X] Delete HTML Elements
- [X] Change the Color of Text
- [X] Use CSS Selectors to Style Elements
- [X] Use a CSS Class to Style an Element
- [X] Style Multiple Elements with a CSS Class
- [X] Change the Font Size of an Element
- [X] Set the Font Family of an Element
- [X] Import a Google Font
- [X] Specify How Fonts Should Degrade
- [X] Add Images to your Website
- [X] Size your Images
- [X] Add Borders Around your Elements
- [X] Add Rounded Corners with a Border Radius
- [X] Make Circular Images with a Border Radius
- [X] Link to External Pages with Anchor Elements
- [X] Nest an Anchor Element within a Paragraph
- [X] Make Dead Links using the Hash Symbol
- [X] Turn an Image into a Link
- [X] Add Alt Text to an Image for Accessibility
- [X] Create a Bulleted Unordered List
- [X] Create an Ordered List
- [X] Create a Text Field
- [X] Add Placeholder Text to a Text Field
- [X] Create a Form Element
- [X] Add a Submit Button to a Form
- [X] Use HTML5 to Require a Field
- [X] Create a Set of Radio Buttons
- [X] Create a Set of Checkboxes
- [X] Check Radio Buttons and Checkboxes by Default
- [X] Nest Many Elements within a Single Div Element
- [X] Give a Background Color to a Div Element
- [X] Set the ID of an Element
- [X] Use an ID Attribute to Style an Element
- [X] Adjusting the Padding of an Element
- [X] Adjust the Margin of an Element
- [X] Add a Negative Margin to an Element
- [X] Add Different Padding to Each Side of an Element
- [X] Add Different Margins to Each Side of an Element
- [X] Use Clockwise Notation to Specify the Padding of an Element
- [X] Use Clockwise Notation to Specify the Margin of an Element
- [X] Style the HTML Body Element
- [X] Inherit Styles from the Body Element
- [X] Prioritize One Style Over Another
- [X] Override Styles in Subsequent CSS
- [X] Override Class Declarations by Styling ID Attributes
- [X] Override Class Declarations with Inline Styles
- [X] Override All Other Styles by using Important
- [X] Use Hex Code for Specific Colors
- [X] Use Hex Code to Color Elements White
- [X] Use Hex Code to Color Elements Red
- [X] Use Hex Code to Color Elements Green
- [X] Use Hex Code to Color Elements Blue
- [X] Use Hex Code to Mix Colors
- [X] Use Hex Code to Color Elements Gray
- [X] Use Hex Code for Specific Shades of Gray
- [X] Use Abbreviated Hex Code
- [X] Use RGB values to Color Elements
- [X] Use RGB to Color Elements White
- [X] Use RGB to Color Elements Red
- [X] Use RGB to Color Elements Green
- [X] Use RGB to Color Elements Blue
- [X] Use RGB to Mix Colors

**Comment by justinian336** [comment]
Working here.
