### ISSUE TITLE
Translation to Spanish: Verify and update translation of intermediate-bonfires.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6502]
- [x]  Sum All Numbers in a Range
- [x]  Diff Two Arrays
- [x]  Roman Numeral Converter
- [x]  Where art thou
- [x]  Search and Replace
- [x]  Pig Latin
- [x]  DNA Pairing
- [x]  Missing letters
- [x]  Boo who
- [x]  Sorted Union
- [x]  Convert HTML Entities
- [x]  Spinal Tap Case
- [x]  Sum All Odd Fibonacci Numbers
- [x]  Sum All Primes
- [x]  Smallest Common Multiple
- [x]  Finders Keepers
- [x]  Drop it
- [x]  Steamroller
- [x]  Binary Agents
- [x]  Everything Be True
- [x]  Arguments Optional

**Comment by vtamara** [comment]
- [X] Sum All Numbers in a Range
- [X] Diff Two Arrays
- [X] Roman Numeral Converter
- [X] Where art thou
- [X] Search and Replace
- [X] Pig Latin
- [X] DNA Pairing
- [X] Missing letters
- [X] Boo who
- [X] Sorted Union
- [X] Convert HTML Entities
- [X] Spinal Tap Case
- [X] Sum All Odd Fibonacci Numbers
- [X] Sum All Primes
- [X] Smallest Common Multiple
- [X] Finders Keepers
- [X] Drop it
- [X] Steamroller
- [X] Binary Agents
- [X] Everything Be True
- [X] Arguments Optional

**Comment by vtamara** [comment]
Checking this one
