### ISSUE TITLE
Translation to Spanish: Verify and update translation of intermediate-ziplines.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6503]
- [x]  Show the Local Weather
- [x]  Stylize Stories on Camper News
- [x]  Build a Wikipedia Viewer
- [x]  Use the Twitch.tv JSON API
- [x]  Build a Tic Tac Toe Game
- [x]  Build a Simon Game

**Comment by vtamara** [comment]
- [X] Show the Local Weather
- [X] Stylize Stories on Camper News
- [X] Build a Wikipedia Viewer
- [X] Use the Twitch.tv JSON API
- [X] Build a Tic Tac Toe Game
- [X] Build a Simon Game

**Comment by vtamara** [comment]
Working on this one
