### ISSUE TITLE
Translation to Spanish: Verify and update translation of jquery.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6504]
- [x]  Learn how Script Tags and Document Ready Work
- [x]  Target HTML Elements with Selectors Using jQuery
- [x]  Target Elements by Class Using jQuery
- [x]  Target Elements by ID Using jQuery
- [x]  Delete your jQuery Functions
- [x]  Target the same element with multiple jQuery Selectors
- [x]  Remove Classes from an element with jQuery
- [x]  Change the CSS of an Element Using jQuery
- [x]  Disable an Element Using jQuery
- [x]  Change Text Inside an Element Using jQuery
- [x]  Remove an Element Using jQuery
- [x]  Use appendTo to Move Elements with jQuery
- [x]  Clone an Element Using jQuery
- [x]  Target the Parent of an Element Using jQuery
- [x]  Target the Children of an Element Using jQuery
- [x]  Target a Specific Child of an Element Using jQuery
- [x]  Target Even Numbered Elements Using jQuery
- [x]  Use jQuery to Modify the Entire Page

**Comment by vtamara** [comment]
- [X] Learn how Script Tags and Document Ready Work
- [X] Target HTML Elements with Selectors Using jQuery
- [X] Target Elements by Class Using jQuery
- [X] Target Elements by ID Using jQuery
- [X] Delete your jQuery Functions
- [X] Target the same element with multiple jQuery Selectors
- [X] Remove Classes from an element with jQuery
- [X] Change the CSS of an Element Using jQuery
- [X] Disable an Element Using jQuery
- [ ] Change Text Inside an Element Using jQuery
- [X] Remove an Element Using jQuery
- [X] Use appendTo to Move Elements with jQuery
- [X] Clone an Element Using jQuery
- [X] Target the Parent of an Element Using jQuery
- [X] Target the Children of an Element Using jQuery
- [X] Target a Specific Child of an Element Using jQuery
- [X] Target Even Numbered Elements Using jQuery
- [X] Use jQuery to Modify the Entire Page

**Comment by vtamara** [comment]
Checking
