### ISSUE TITLE
Translation to Spanish: Verify and update translation of json-apis-and-ajax.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6505]
- [x]  Trigger Click Events with jQuery
- [x]  Change Text with Click Events
- [x]  Get JSON with the jQuery getJSON Method
- [x]  Convert JSON Data to HTML
- [x]  Render Images from Data Sources
- [x]  Prefilter JSON
- [x]  Get Geo-location Data

**Comment by vtamara** [comment]
- [X] Trigger Click Events with jQuery
- [X] Change Text with Click Events
- [X] Get JSON with the jQuery getJSON Method
- [X] Convert JSON Data to HTML
- [X] Render Images from Data Sources
- [X] Prefilter JSON
- [X] Get Geo-location Data

**Comment by justinian336** [comment]
Checking this one out
