### ISSUE TITLE
Translation to Spanish: Verify and update translation of object-oriented-and-functional-programming.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6506]
- [x]  Declare JavaScript Objects as Variables
- [x]  Construct JavaScript Objects with Functions
- [x]  Make Instances of Objects with a Constructor Function
- [x]  Make Unique Objects by Passing Parameters to our Constructor
- [x]  Make Object Properties Private
- [x]  Iterate over Arrays with .map
- [x]  Condense arrays with .reduce
- [x]  Filter Arrays with .filter
- [x]  Sort Arrays with .sort
- [x]  Reverse Arrays with .reverse
- [x]  Concatenate Arrays with .concat
- [x]  Split Strings with .split
- [x]  Join Strings with .join

**Comment by vtamara** [comment]
- [X] Declare JavaScript Objects as Variables
- [X] Construct JavaScript Objects with Functions
- [X] Make Instances of Objects with a Constructor Function
- [X] Make Unique Objects by Passing Parameters to our Constructor
- [X] Make Object Properties Private
- [X] Iterate over Arrays with .map
- [X] Condense arrays with .reduce
- [X] Filter Arrays with .filter
- [X] Sort Arrays with .sort
- [X] Reverse Arrays with .reverse
- [X] Concatenate Arrays with .concat
- [X] Split Strings with .split
- [X] Join Strings with .join

**Comment by justinian336** [comment]
Working on this now.
