### ISSUE TITLE
Translation to Spanish: Verify and update translation of data-visualization-certificate.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6508]
- [x] Claim Your Data Visualization Certificate

**Comment by justinian336** [comment]
Working on this one.

**Comment by vtamara** [comment]
- [X] Claim Your Data Visualization Certificate

**Comment by vtamara** [comment]
@justinian336 ¿habías hecho un pull request con la traducción inicial de este?  ¿Puedes referenciarlo?

**Comment by justinian336** [comment]
@vtamara no lo he hecho. En este momento pienso traducirlo y hacer el PR, si no hay nadie más haciéndolo.
