### ISSUE TITLE
Translation to Spanish: Verify and update translation of data-visualization-projects.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6509]
- [x]  Visualize Data with a Bar Chart
- [x]  Visualize Data with a Scatterplot Graph
- [x]  Visualize Data with a Heat Map
- [x]  Show Relationships with a Force Directed Graph
- [x]  Map Data Across the Globe

**Comment by vtamara** [comment]
- [ ] Visualize Data with a Bar Chart
- [ ] Visualize Data with a Scatterplot Graph
- [ ] Visualize Data with a Heat Map
- [ ] Show Relationships with a Force Directed Graph
- [ ] Map Data Across the Globe

**Comment by vtamara** [comment]
Thanks @justinian336.  @bugron this one was closed also with #6702

**Comment by bugron** [comment]
Closing this issue then. Thanks @vtamara, @justinian336.
