### ISSUE TITLE
Translation to Spanish: Verify and update translation of react-projects.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6510]

**Comment by justinian336** [comment]
I'm taking this one

**Comment by vtamara** [comment]
- [ ] Build a Markdown Previewer
- [ ] Build a Camper Leaderboard
- [ ] Build a Recipe Box
- [ ] Build the Game of Life
- [ ] Build a Roguelike Dungeon Crawler Game
