### ISSUE TITLE
Translation to Spanish: Verify and update translation of api-projects.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6513]
- [x]  Get Set for our Back End Development Projects
- [x]  Timestamp Microservice
- [x]  Request Header Parser Microservice
- [x]  URL Shortener Microservice
- [x]  Image Search Abstraction Layer
- [x]  File Metadata Microservice

**Comment by vtamara** [comment]
- [X] Get Set for our Back End Development Projects
- [ ] Timestamp Microservice
- [ ] Request Header Parser Microservice
- [ ] URL Shortener Microservice
- [ ] Image Search Abstraction Layer
- [ ] File Metadata Microservice

**Comment by josectello** [comment]
Currently working on this.

**Comment by vtamara** [comment]
@josectello I just used part of the PR that you closed.  Thank you. Blessings.
