### ISSUE TITLE
Translation to Spanish: Verify and update translation of automated-testing-and-debugging.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6514]
- [x]  Use the Javascript Console
- [x]  Using typeof

**Comment by vtamara** [comment]
- [X] Use the Javascript Console
- [X] Using typeof

**Comment by justinian336** [comment]
Verified. No changes are necessary.

**Comment by bugron** [comment]
Closing then. Thanks.
