### ISSUE TITLE
Translation to Spanish: Verify and update translation of dynamic-web-applications.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6516]
- [x]  Build a Voting App
- [x]  Build a Nightlife Coordination App
- [x]  Chart the Stock Market
- [x]  Manage a Book Trading Club
- [x]  Build a Pinterest Clone

**Comment by vtamara** [comment]
- [X] Build a Voting App
- [X] Build a Nightlife Coordination App
- [X] Chart the Stock Market
- [X] Manage a Book Trading Club
- [X] Build a Pinterest Clone
