### ISSUE TITLE
Translation to Spanish: Verify and update translation of nodejs-and-expressjs.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6519]
- [x] Manage Packages with NPM
- [x] Start a Node.js Server
- [x] Continue working with Node.js Servers
- [x] Finish working with Node.js Servers
- [x] Build Web Apps with Express.js

**Comment by vtamara** [comment]
- [X] Manage Packages with NPM
- [X] Start a Node.js Server
- [X] Continue working with Node.js Servers
- [X] Finish working with Node.js Servers
- [X] Build Web Apps with Express.js

**Comment by vtamara** [comment]
@justinian336 podrías por favor poner en la descripción inicial de este problema/issue las cajas de verificación y textos que indican los desafios y su revisión como puse en el comentario?  Es que asi queda bien el progreso al verlo en el listado de problemas y queda listo para ser reusado a futuro.

**Comment by vtamara** [comment]
Lo mismo tocaría en los demas problemas de  verificación/actualización.  Disculpa no haberlo pensado y pedido desde un comienzo.

**Comment by justinian336** [comment]
Entendido. Me imagino que eso va para todos los desafíos que todavía no tienen las cajas de verificación ¿incluso aquellos cuyos issues ya están cerrados?

**Comment by vtamara** [comment]
Todos tienen cajas de verificación puestas por mi, pero no en el comentario inicial que es el que tu puedes crear/editar y que es donde deben quedar las cajas de verificación.

**Comment by justinian336** [comment]
¡Ah, ya te entiendo! Ok, lo voy a hacer durante el día de hoy.

**Comment by vtamara** [comment]
Muchas Gracias. Un detalle es que sólo tu puedes marcar y desmarcar en esas cajas de verificación, así como agregar o retirar.   Yo estaba pensando que se reabriera el issue cuando alguién hiciera cambios a la traducción del archivo y que esa persona marcara o desmarcar, por lo visto lo que toca es que reabran el requerimiento y pongan un comentario posiblemente referenciando el commit con el cambio o agregando un comentario al problema indicando lo que cambio, y que tu marcaras o desmarcaras las cajas de verificación apropiadas.  ¿Te parece bien?

**Comment by justinian336** [comment]
¿Es posible que tú nomines a alguien como `asignado` a un issue, para que esa persona pueda marcar también? ¿O no funciona incluso así?

**Comment by vtamara** [comment]
No puedo asignar issues a gente. Y he notado que incluso en los que yo soy asignado no puedo modificar los comentarios de otras personas (ni el inicial).
