### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-pair-program-on-bonfires has an issue 

### ISSUE THREAD

**Issue by 4ster** [FreeCodeCamp/freecodecamp#652]
1. Cant login screenhero site with slack account. No new sign up due screenhero join slack
2. Can't install screenhero for Mac or Windows. I am using Ubuntu 14.04
3. Link http://freecodecamp.com/bonfires (see item 13.) is not working

**Comment by terakilobyte** [comment]
Screenhero isn't available on linux yet, sadly. The link has been updated. Thanks for the report, we'll keep looking to see if something good comes along for linux. Until then you can try teamviewer.

**Comment by 4ster** [comment]
Yep, I know about alternatives. Thanks.
