### ISSUE TITLE
Little bug in the comparisson

### ISSUE THREAD

**Issue by marianomoreno** [FreeCodeCamp/FreeCodeCamp#6521]
In check-for-palindromes's exercise, the last example's parameter ("0_0 (: /-\ :) 0-0") have symbols wich aren't correctly checked:

"A palindrome is a word or sentence that's spelled the same way both forward and backward, ignoring punctuation, case, and spacing.

You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes."

But, in my code, i don't exclude all of them and i'ts ok finally.

function palindrome(str) {
  // Good luck!
  
  var str1 = "";

  str1 = str.split(".").join('');
  str1 = str1.split(",").join('');
  str1 = str1.split(" ").join('');
  str1 = str1.split("-").join('');
  str1 = str1.split("_").join('');
  str1 = str1.split("(").join('');
  str1 = str1.split(")").join('');
  str1 = str1.toLowerCase();
  console.log(str1);
  strReverse = str1.split('').reverse().join('');

  if(str1===strReverse){
    
    return true;
  }else{
    
    return false;
  }
}

palindrome("Dabale arroz a la zorra el abad");

Check it please to avoid learning errors.

Thanks
Regards

**Comment by ltegman** [comment]
There's only so much we can do to make sure students aren't "coding to the test". We can add more symbols into the tests but ultimately all that does it make it slightly more tedious to "code to the test" but it doesn't prevent it. Thanks and happy coding!
