### ISSUE TITLE
Working answer doesn't work

### ISSUE THREAD

**Issue by angelcj** [FreeCodeCamp/FreeCodeCamp#6522]
Challenge [Title Case a Sentence](http://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20var%20arr%20%3D%20str.toLowerCase().split(%22%20%22)%3B%0A%20%20var%20newStr%20%3D%20%22%22%3B%0A%20%20%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20for%20(var%20y%20%3D%200%3B%20y%20%3C%3D%20arr%5Bi%5D.length%3B%20y%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(y%20%3D%3D%3D%200%20%26%26%20arr%5Bi%5D%5By%5D%20!%3D%3D%20undefined)%20%7B%0A%20%20%20%20%20%20%20%20newStr%20%2B%3D%20arr%5Bi%5D%5By%5D.toUpperCase()%3B%0A%20%20%20%20%20%20%7D%20else%20if%20(arr%5Bi%5D%5By%5D%20!%3D%3D%20undefined)%20%7B%0A%20%20%20%20%20%20%20%20newStr%20%2B%3D%20arr%5Bi%5D%5By%5D%3B%0A%20%20%20%20%20%20%7D%20else%20if%20(arr%5Bi%5D%5By%5D%20%3D%3D%3D%20undefined)%20%7B%0A%20%20%20%20%20%20%20%20newStr%20%2B%3D%20%22%20%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20newStr%3B%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I know it might not be the most inspired answer, but it seems to work.

Here is my code:
```javascript
function titleCase(str) {
  var arr = str.toLowerCase().split(" ");
  var newStr = "";
  
  for (var i = 0; i < arr.length; i++) {
    for (var y = 0; y <= arr[i].length; y++) {
      if (y === 0 && arr[i][y] !== undefined) {
        newStr += arr[i][y].toUpperCase();
      } else if (arr[i][y] !== undefined) {
        newStr += arr[i][y];
      } else if (arr[i][y] === undefined) {
        newStr += " ";
      }
    }
  }
  return newStr;
}

titleCase("sHoRt AnD sToUt");
```

**Comment by ltegman** [comment]
You can't see it unless you highlight the FCC console output (or run your code in a different environment that puts quotes around string output), but your code is adding an extra space to the end of the string. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to confirm what you're seeing is actually a site issue before filing a bug. Thanks and happy coding!
