### ISSUE TITLE
Undefined is not explained.

### ISSUE THREAD

**Issue by ken-atx** [FreeCodeCamp/FreeCodeCamp#6525]
Challenge [Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(a%20%3C%200%20%7C%7C%20b%20%3C%200)%20%7B%0A%20%20%20%20return%20undefined%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  if (a < 0 || b < 0) {
    return undefined;
  }
  
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

```
undefined is not explained so someone trying to complete this challenge could easily be confused.  The example given returns a string which also adds to the confusion.

**Comment by SaintPeter** [comment]
What would you propose as some explanation that would have been helpful to you?

**Comment by thaniri** [comment]
I ran into the same problem. Perhaps a reminder that undefined is not supposed to be a string.

**Comment by ihthisham** [comment]
They should have mentioned that undefined is not a string.

**Comment by bugron** [comment]
In [Declare JavaScript Variables](http://www.freecodecamp.com/challenges/declare-javascript-variables) we already separate them as two different data types and we have [Understanding Uninitialized Variables](http://www.freecodecamp.com/challenges/understanding-uninitialized-variables) which talks about the `undefined` a little bit. When you're at Return Early Pattern for Functions it supposed that you have finished that challenges and already know that `undefined` is not equal to `"undefined"` and that `undefined` and `string` are completely different data types. Also, the instructions say
>Modify the function abTest so that if a or b are less than 0 the function will immediately **exit with a value of undefined**.

**exit with a value of undefined** not **exit with a value of "undefined"**. So it doesn't say return the "undefined" string.

**Comment by ken-atx** [comment]
Yes, the instructions for this challenge are entirely correct and undefined is covered in earlier challenges.  I know as a student, that returning the string “undefined” is a very easy mistake to make.  I suggest adding a hint that you should not return a string will avoid confusion for some students.

Sincerely,
Ken Thompson

**Comment by SaintPeter** [comment]
This is a common question in the Help Rooms.  Here is what I propose:
> **Hint**
Remember that `undefined` is a keyword, not a string.

We could potentially link one or more words in that sentance to [Understanding Uninitialized Variables](http://www.freecodecamp.com/challenges/understanding-uninitialized-variables)

**Comment by ihthisham** [comment]
Thank  you all for clearing the confusion. :) Have a nice day...

**Comment by Jesseeee** [comment]
Also had a bit of trouble with this one since I assumed it was a string that needed to be returned so I was looking in that direction for my error before I realized undefined is also a keyword, a little hint or nudge in the right direction here would certainly be helpful to avoid getting stuck

**Comment by adamorlowskipoland** [comment]
@SaintPeter 
Another smartAss

**Comment by acobserver** [comment]
// Setup
function abTest(a, b) {
  // Only change code below this line
  if ( Math.sign(a)  === -1){
    return undefined;
  }else if ( Math.sign(b)  === -1){
    return undefined;
  }else
  
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

**Comment by texas2010** [comment]
@acobserver 
Please do not post your solution on here. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Woodshadow** [comment]
Glad this post exists. I was very confused how to do undefined. The previous example the problem leads to doesn't really apply.  I'm not sure how else it could have been explained but it wasn't clear to me. Maybe there needs to be a glossary of terms somewhere. It is very hard to go back and find what I am looking for in FCC
