### ISSUE TITLE
p elements set to Monospace, but cannot pass tests

### ISSUE THREAD

**Issue by cwkatzmann** [FreeCodeCamp/FreeCodeCamp#6526]
Challenge [Set the Font Family of an Element](http://www.freecodecamp.com/challenges/set-the-font-family-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%20font-size%3A%2016px%3B%20font-family%3A%20Monospace%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.

Very early along in the process so maybe I'm missing something but it looks to me like this should run. The instructions were to simply make the p elements monospace and I did that. I encounter this issue whether I adjust the font size or not.

My code:
```html
<style>
  .red-text {
    color: red;
  }

  p { font-size: 16px; font-family: Monospace}

</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by TravisHi** [comment]
You're missing a semicolon after "Monospace".

**Comment by cwkatzmann** [comment]
Good catch, but that didn't solve the issue. I had tried it with the semicolon before opening this issue but I must have gotten sloppy after trying some other ideas and didn't retype it.

**Comment by TravisHi** [comment]
Oops, I was wrong anyway, sorry!

**Comment by sludge256** [comment]
Remove the class from your second `p` element and you should be good to go. The original code only has the class `red-text` for the `h2` and first `p` element. The code test does not appear to like the additional red text.

**Comment by SaintPeter** [comment]
Do this:
Reset your code and ONLY make the changes requested.  Don't, for example, randomly put `class="red-text"` on the second `p` element.

That, somewhat counter-intuitively, breaks our test because we're looking for a "bare" `p` element to ensure that you didn't set the monospace font in the `red-text` class.

**Comment by cwkatzmann** [comment]
Thanks guys. That fixed it. I figured out how I got messed up:

I defeated the previous challenge by applying the size modification to the .red-text class and then applying .red-text to the individual p elements. 

When I moved to the next challenge I noticed that the second p element did not have the .red-text class applied and thought that I had made an error, so I reapplied it.

**Comment by SaintPeter** [comment]
Yeah, that prior challenge needs to have its tests fixed to disallow that (incorrect) solution.  We should have an issue on it shortly.

**Comment by FlyingBlueBread** [comment]
I tried your solution but mine didnt work

**Comment by Manuel-Ndim** [comment]
Took off the class and it worked, thanks guys
