### ISSUE TITLE
Translation, i18n. Add routes of the form /:lang/map and /:lang/challenges/:chid

### ISSUE THREAD

**Issue by vtamara** [FreeCodeCamp/FreeCodeCamp#6527]
:lang is code of language i.e: es, fr, ru
:chid is name of challenge as it works currently

/:lang/map should render the map with the names of challenges translated as currently they are in the corresponding file of seeds/challenges (nameLang if it exists or name otherwise to present in english when there is no translation)

/:lang/:chid should render the identified challenge but using the name and description in the target language (as long as it is available as nameLang and descriptionLang in the corresponding seeds/challenges, if it doesnt exist present name and description to present in english challenges that are not translated).

Bonus point: use the library i18next for routes as stated.

**Comment by alistermada** [comment]
Related to #6389?

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
