### ISSUE TITLE
 url images will not show in Codepen unless the URLhas jpg ( css)

### ISSUE THREAD

**Issue by tetsugen** [FreeCodeCamp/FreeCodeCamp#6528]
`.backImg{
  background-image:url("http://lukaesenko.com/wp-content/uploads/2014/12/20140923_A2A10995-Panorama-copy.jpg");
  background-repeat: no-repeat;
   background-position: center;
     background-attachment: fixed;
//the above will work
// this will not
  background-image:url("http://imgur.com/TOfnj6r");
  background-repeat: no-repeat;
   background-position: center;
     background-attachment: fixed;
`

**Comment by SaintPeter** [comment]
This is not an issue with the Free Code Camp site.  You may wish to take this up with Codepen.  Are you certain that it is CodePen specific and not a fundamental property of HTML?

Regardless, we cannot fix it.

Happy Coding!

**Comment by tetsugen** [comment]
Thanks for clearing that up
