### ISSUE TITLE
Code should not pass without setting font-size rule for the p element

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#6530]
[Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element)

Campers are able to pass the tests by setting the font-size in their `red-text` class and applying the class to both p elements instead of creating a rule for `p` elements specifically.

Passing code:
```html
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
The intended solution should be:
```html
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

The current situation can cause confusion when working on the next challenge as evidenced by https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6526 .
In the above issue the user added the class `red-text` to their second `p` element to match the code they had for their previous challenge (this issue's challenge)  which caused the code test(s) to fail.

**Comment by robjloranger** [comment]
sounds familiar.. if its not done by then i'll do it in the morning. 7pm here

**Comment by ilovecoding16** [comment]
The intended solution mentioned works
if font-family:monospace is added to p which is a condition for the problem

  p {
    font-size: 16px;
    font-family:Monospace;
    }

**Comment by robjloranger** [comment]
It doesn't say to set the second paragraph to red-text. That's more an issue with someone adding extra changes beyond that which the instructions ask for.

**Comment by lukebunch** [comment]
I have tried this in many different ways in attempts to pass this level, ultimately convinced that the code was correct when it looked like the "intended solution" as seen above. I'm glad I found this because I have since even tried copy-pasting the intended solution above and submitting it, but it still does not work. I have played with the zoom and everything on my computer, but it is not working. I also tried adding the monospace. Any other ideas?

**Comment by raisedadead** [comment]
I think along with the test case change the instructions should be changed from
> Inside the same `<style>` tag that we created for your `red-text` class, set the `font-size` of all `p` elements to 16 pixels (`16px`).

to

> Inside the same `<style>` tag that we created for your `red-text` class, create one more class for `p` elements and set the `font-size` to 16 pixels (`16px`).

**Comment by robjloranger** [comment]
i agree with @raisedadead except the wording should not be class, we want to style the elements 'p' not create a class and apply it to 'p' elements

**Comment by lukebunch** [comment]
This is really odd. It still won't let me submit it. I tried creating a second style tag, and the iphone screen display on the right makes the appropriate changes, but it does not let me pass the level:

<style>
  .red-text { color: red; }
</style>

<style>
  p {font-size: 16px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by lukebunch** [comment]
![change font size](https://cloud.githubusercontent.com/assets/16925783/12652520/c4f240f0-c5b0-11e5-86a4-e3e6712ec13c.PNG)

**Comment by lukebunch** [comment]
Any ideas you have on how to fix this would be much appreciated! Thanks in advance!

**Comment by raisedadead** [comment]
@lukebunch : you are adding an extra style block. put everything in one `style` block

**Comment by robjloranger** [comment]
```
<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

like this

**Comment by sludge256** [comment]
There are also reports of this challenge not playing well with Internet Explorer 11 if that is the browser you are on.
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6335

**Comment by lukebunch** [comment]
I've tried it every way I can think of. Nothing works...

![change font size](https://cloud.githubusercontent.com/assets/16925783/12652617/3e3f5c9a-c5b1-11e5-9cb5-bb74aec513b4.PNG)

**Comment by robjloranger** [comment]
what browser? it is working as above for me

**Comment by SaintPeter** [comment]
@robjloranger You are correct, a `p` is an element, not a class.

I am ok with changing the instructions as well:
> Inside the same <style> tag that we created for your red-text class, create an entry for `p` elements and set the `font-size` to `16` pixels (16px).

@lukebunch 
Issues are not for code problems.  We are trying to work on improving the instructions for this test.  Please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Others -
Please don't provide code support in issues, since issues are not for code problems.

**Comment by lukebunch** [comment]
I bet that's the issue. I'm on IE... It's a work issued PC....
I'll see if I can get another browser on here. 
Thank you!

**Comment by robjloranger** [comment]
So i have a fix, i removed the double element check in the assertion for font-size as it seemed redundant to check both elements when we can just check the new one that should not have the red-text class. I then added the same fix as I did in Set the font family of an element by skipping 'p' elements that have the red-text class. If that sounds good I'll work on the description.

**Comment by robjloranger** [comment]
everything is passing and failing where it should.
this is the description i came up with..


Inside the same <style> tag that contains your red-text class, create an entry for p elements and set the font-size to 16 pixels (16px).

Note
Due to browser implementation differences, you may need to be at 100% zoom to pass the tests on this challenge. Also, please do not add any extra classes to your new element.

**Comment by lukebunch** [comment]
I tried installing Google Chrome and tested it again with both a single style box and two separate style boxes. Still no luck. And with Chrome I also have a new issue of not being able to close the side bar. If you are able to update it and also change the instructions, I will wait until the lesson has been changed and try again from both browsers. Thanks for your help!

![change font size](https://cloud.githubusercontent.com/assets/16925783/12653158/d2bf4edc-c5b3-11e5-9de5-2113945656d3.PNG)

**Comment by michaelb1115** [comment]
Can't get past this either. Tried all suggestions I saw. Guess I'll wait till tomorrow and see if its fixed.

**Comment by robjloranger** [comment]
@michaelb1115 and @lukebunch please goto [FreeCodeCamp Help Chat](https://gitter.im/FreeCodeCamp/Help) and ask for help there

**Comment by jiajing1993** [comment]
@lukebunch At first, I had the same problem as yours, until I zoom in the browser (command + ).

**Comment by darkHarry** [comment]
try making the second <p> tag to "<p style = "font-size:16px;">...." it worked for me.

**Comment by Shiiitake** [comment]
i still cant pass this level. is it fixed yet ?

**Comment by ilochi** [comment]
@lukebunch thanks for your post, you just saved me some headache. please how can I paste the coding page into my post just as you did not as bellow. thanks once more 
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by KomitaSRB** [comment]
Passing code:
`<style>
  .red-text {
    color: red;
  }
  
  p {
font-size: 16px;
}
</style>

<p class="red-text">kitty ipsum text</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>`

**Comment by texas2010** [comment]
@KomitaSRB 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by 00090** [comment]
I wanted to write about the same task but it was possible to pass the text with "30px" while it requires "16px"

**Comment by Skinteastwood** [comment]
This worked for me. Took me over an hour to change the bottom <p> red I added this to do it to unlock the challenge :       p {color: red; }

<style>
  .red-text   {
    color: red; }
  
  p { font-size: 16px; }
  p {color: red; }
  
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text"> Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. </p>
