### ISSUE TITLE
Comparison with the Equality Operator throwing error

### ISSUE THREAD

**Issue by kellietyler0** [FreeCodeCamp/FreeCodeCamp#6533]
Challenge [Comparison with the Equality Operator](http://www.freecodecamp.com/challenges/comparison-with-the-equality-operator#?solution=%2F%2F%20Setup%0Afunction%20myTest(val)%20%7B%0A%20%20if%20(val%20%3D%3D%20%2212%22)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(10)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function myTest(val) {
  if (val == "12") { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
myTest(10);
```
I'm getting an error that I should try using the == operator. I have used it and the error is not clearing.
![screen shot 2016-01-27 at 8 08 27 pm](https://cloud.githubusercontent.com/assets/14842167/12633860/1a1d5166-c532-11e5-98ad-058817a2da28.png)
![screen shot 2016-01-27 at 8 08 31 pm](https://cloud.githubusercontent.com/assets/14842167/12633859/1a1ccc96-c532-11e5-9090-880fabc28070.png)

**Comment by alistermada** [comment]
Seems to be similar to #6485. I'll work on a fix for this one.

**Comment by kellietyler0** [comment]
I'm getting the same error on strict equal lesson. ===

**Comment by sludge256** [comment]
Despite the failing test not being very descriptive (which we'll look into). You should be comparing the inputs to the value of 12 not the string of "12" as per instructions.

**Comment by kellietyler0** [comment]
Ah! Thank you! That will probably fix it! ;)

**Comment by alistermada** [comment]
@sludge256 Do you think the last test should just be exactly as the message suggests or should the message be rewritten?

**Comment by sludge256** [comment]
I'll get some second opinions on how we want to handle this.

**Comment by SaintPeter** [comment]
Yeah, it probably makes sense to accept `"12"` as well as `12`, since the whole point of this challenge is to highlight that both are equally valid.

**Comment by alistermada** [comment]
Perhaps the instructions could be changed to:
>Add the `equality operator` to the indicated line so that the function will return "Equal" when `val` is equivalent to `12` or `"12"` and "Not Equal" otherwise.

**Comment by SaintPeter** [comment]
I think the key thing here is that we say:
> when val is equivalent to `12`

My intent when I wrote it was that they would compare against a literal `12`, but I think it makes sense to allow a string as well.  I actually think it may be confusing to new coders to put both.  They can use one or the other, but to put both risks them thinking that they NEED both.  (Thanks to @sludge256 for that insight).

I think leaving the instructions as is and updating the test makes the most sense.

**Comment by alistermada** [comment]
Alright, I'll leave the instructions alone. Will change the text to make it less strict.

**Comment by kellietyler0** [comment]
Input: Because the error message was so specific to the equality operator, I didn't even THINK to look at the fact that I had "12" instead of 12. The error message as is creates a bias. All I looked at was the fact that I had, in fact, used the == operator like it asked.

**Comment by alistermada** [comment]
@kellietyler0 Noted. I've changed that last test so that it would pass when you put any string or number in front of `val ==`.

**Comment by darbane** [comment]
Change fuction myTest to testEqual
it works this way
function testEqual(val) {
if (val == "12") { // Change this line
return "Equal";
}
return "Not Equal";
}

// Change this value to test
testEqual("12");

**Comment by Anon3333** [comment]
if (val == 12) { < remove the quotes// Change this line
return "Equal";
}
return "Not Equal";
}
the code above should work :)
// Change this value to test
testEqual(12); < remove quotes

**Comment by frogshelp** [comment]
ur all so way off lol 
it should be like this  add var myVal =12; at the top of the whole code then your 
if (val == myVal) { should be reading that and at the bottom should be three 
teststrict's looking like this
testStrict(10);
testStrict(12);
testStrict("12");
and it will pass thier is no flaw with the challenge nor are u removing any quuotes lol  as i just did all this and all mine passed

**Comment by texas2010** [comment]
@frogshelp 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by RomingArt** [comment]
This is my code and it passed if someone finds something wrong please comment, so I can check it out. 
`// Setup
function testStrictNotEqual(val) {
  // Only Change Code Below this Line
  
  if (val !== 17) {

  // Only Change Code Above this Line

    return "Not Equal";
  }
  return "Equal";
}

// Change this value to test
testStrictNotEqual(10);`
