### ISSUE TITLE
The challenges will not go to next when stepup in local

### ISSUE THREAD

**Issue by NateLing** [FreeCodeCamp/FreeCodeCamp#6534]
1.Drop the data from mongodb.
2.Signup with github
3.When i finish the challenge learn-how-free-code-camp-works,but the next challenge still learn-how-free-code-camp-works.

**Comment by raisedadead** [comment]
The database needs to be seeded after dropping it. run `node seed` before `gulp`, however this is an assumption that you have forgotten.

If not please get in touch with the guys at  [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors), they will definitely sort this out.

Goodluck!

**Comment by bugron** [comment]
Closing as stale. @NateLing feel free to reopen, thanks.
