### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-button has an issue 

### ISSUE THREAD

**Issue by ThiagoFerreir4** [FreeCodeCamp/freecodecamp#654]
Please tell us in detail here how we can make this challenge better.
Small typo:
Challenge reads: your button should have the *test* "like this photo"; 
I think it meant to read: your button should have the *text* "like this photo";

**Comment by terakilobyte** [comment]
Thanks Thiago
