### ISSUE TITLE
Image Search Abstraction Layer example application bug

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#6540]
How to generate it (for this particular search term it is passing an offset value of 91 or more):
https://cryptic-ridge-9197.herokuapp.com/api/imagesearch/lolcats%20funny?offset=91

It may be of the same nature as one I encountered, that's probably why it was found in the example.
The point is in parsing JSON for output. As far as it was found from error reports it is caused by some image urls, but the reason is not clear for me yet.

So, I ended up ignoring bad format like this:
every time JSON item appears to be not valid it is substituted by string: <code>"There was an error parsing JSON. This is most probably due data from Custom Search service response."</code>
https://image-search-rfprod.c9users.io/imagesearch/scifi?offset=55
(string 134): https://github.com/rfprod/image-search/blob/master/app/routes/index.js

**Comment by SaintPeter** [comment]
Is there some reason you're not using `JSON.parse()`?

RE: the offset issue - I think there may be an upper limit on the allowed offset.  I tried to find some docs to back that up but could not.  I just seem to recall reading it somewhere.

**Comment by rfprod** [comment]
If I understand right what piece of code do you mean (regexp check for valid JSON), then <code>JSON.parse()</code> is not used because parsing issue debugging nearly drove me crazy, so I decided to leave <code>JSON.parse()</code> alone for some time.

Yes, there is an upper limit (found it empirically), and there is a specific response: https://image-search-rfprod.c9users.io/imagesearch/scifi?offset=99

**Comment by SaintPeter** [comment]
I think it's really interesting that you were getting invalid JSON from Google (or whoever your API provider is).

I agree that the example could probably handle invalid JSON or other errors more gracefully.  Do you have a reproducible search that causes parse errors?

@george-stepanek - Could you look into the issues with the image search example that @rfprod cites above?

**Comment by rfprod** [comment]
Sure, here's an example. Sadly I will not be able to show you everything, but it should be enough.
Custom Search API request:
<code>https://www.googleapis.com/customsearch/v1?q=scifi&num=5&start=55&cx="+process.env.CUSTOM_SEARCH_API_CX+"&key="+process.env.CUSTOM_SEARCH_API_KEY</code>

Response with substitution for erratic JSON:
> <code>[{"Error":"There was an error parsing JSON. This is most probably due data from Custom Search service response."},{"url":"http://www.gannett-cdn.com/-mm-/ee7b41445d3cfadf83588d2b33a11fb696899bc5/c=0-371-1432-1180&r=x633&c=1200x630/local/-/media/2015/10/07/IAGroup/IowaCity/635798045951048986-Ryan-Portrait.jpg","snippet":"Oct 7, 2015 ... For Iowa City teacher and artist Ryan Bentzinger, imagination is more important than knowledge.","thumbnail":"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSGJ6DuE_6-YsQnUleay4zWXX1IP_tx3m5K8geomwEZFybQDlNyXk6GaE4","context":"http://www.press-citizen.com/story/entertainment/go-iowa-city/2015/10/07/teacher-artist-sci-fi-world-display-cedar-rapids-museum-art-iowa-city/73504776/"},{"url":"http://static.wixstatic.com/media/1d9fb1_4770e2d16fd844359589763d1edac1a0.jpg_srz_870_621_85_22_0.50_1.20_0.00_jpg_srz","snippet":"Afrofuturism is a book and primer on all things dealing with blacks in science fiction, Afrosurrealism, fantasy and the black fantastic by Ytasha L. Womack.","thumbnail":"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR5aw-K4mjlMWzThj0bJuTvbYiDZXLJc_-g4Pncen8HPRz6RGKdskPj4UJF","context":"http://www.iafrofuturism.com/"},{"url":"http://static.wixstatic.com/media/a47680_89f74f6b3e984f8c966ba6e1847032bd.jpg","snippet":"AlbinoRaven Miniatures is a team devoted to create awesome miniatures. Our aim is to produce high quality, interesting looking figures for hobbyists.","thumbnail":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrDsFt-quMQT5V4036rbWseJhlm4sosdSuuHqfSoQGaOJT3Mh8b8kg6APT","context":"http://www.albinoravenmini.com/"},{"url":"http://saltlakecomiccon.com/wp-content/uploads/2015/07/Sci-Fi-Speed-Dating.jpg","snippet":"Back by popular demand, the crew of “Sci-Fi Speed Dating” and Ryan Glitch, the star of “Geek Love” on IGN Start, are returning to Salt Lake Comic Con 2015.","thumbnail":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbRuy_RPZqK4G1n2helD365qPNWQmeI7rWi9Z1S60Z-FOSNynxw5D8_3fg","context":"http://saltlakecomiccon.com/2015-sci-fi-speed-dating/"}]</code>

I modified code a bit to see what object causes JSON parsing error (it is number 1 in response provided before) and here it is:
> <code>{"url":"http://img.bleacherreport.net/img/images/photos/003/476/235/f284357b7e20b60661cc45eec3844f41_crop_exact.jpg?w=1500&h=1500&q=85","snippet":"Jul 22, 2015 ... Barbarisi reports that Girardi then began taking the steps that led to "Portalball"—a mobile app that blends baseball and science-fiction ...","thumbnail":"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ5F5-S_avqFLs-CyAz56Sp4TjggUTGmPD1h0H2_i2SdjkTmY8fmVHaKD8","context":"http://bleacherreport.com/articles/2528576-yankees-manager-joe-girardi-is-releasing-a-sci-fi-baseball-game-application"}</code>

Everything looks fine, but http://jsonlint.com/ tells there is an error in the object:
> Error: Parse error on line 3:
...teps that led to "	Portalball "—a mobil
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'

**Comment by george-stepanek** [comment]
@SaintPeter Looking into it...

**Comment by george-stepanek** [comment]
OK, in the spirit of "[do the simplest thing that works](http://c2.com/cgi/wiki?DoTheSimplestThingThatCouldPossiblyWork)", [my example](https://cryptic-ridge-9197.herokuapp.com/api/imagesearch/lolcats%20funny?offset=91) now handles an invalid offset by just passing back Google's own message:
```
{"error":{"errors":[{"domain":"global","reason":"invalid","message":"Invalid Value"}],"code":400,"message":"Invalid Value"}}
```

**Comment by SaintPeter** [comment]
@rfprod Let me know if this resolves your issue.  If so, go ahead and close it out.

**Comment by rfprod** [comment]
@SaintPeter Yes, this solved the issue.
