### ISSUE TITLE
var myStr =("I am a "double quoted" string inside "double quotes"").

### ISSUE THREAD

**Issue by sanwalatta** [FreeCodeCamp/FreeCodeCamp#6541]
Challenge [Escaping Literal Quotes in Strings](http://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0A%0Avar%20myStr%3D%22%5C%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%5C%22.%22%20%3B%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


var myStr="\"I am a \"double quoted\" string inside \"double quotes\"\"." ;




```

**Comment by fewspider** [comment]
try this
```
var myStr = "I am a \"double quoted\" string inside \"double quotes\""; // Change this line
```

**Comment by alistermada** [comment]
Yea, I understand the confusion. The test message seems to contradict what the instructions ask for.
Instructions: `I am a "double quoted" string inside "double quotes"`
Test: `"I am a "double quoted" string inside "double quotes""`

There needs to be consistency here. @fewspider's got the right answer, by the way.

**Comment by SaintPeter** [comment]
Haha, irony abounds.  We just changed this test to remove the outside double quotes, because people were being confused and double-double quoting, IE:
`myStr = "\"I am a \"double quoted\" string inside \"double quotes\"\"";`

At this point I don't know what to do.

**Comment by bugron** [comment]
I think either we need to remove first and last quotes from the test message or add a note that those should be ignored here.

**Comment by SaintPeter** [comment]
We already removed the quotes.  We just did that as per the discussion here on issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5825.

We can't have it both ways.  Either we include the quotes and risk that someone thinks that they need to include the outer quotes, or we omit them and users are trying to assign bare strings.

I think that maybe some clarifying language is needed.

**Comment by erictleung** [comment]
Maybe in addition to clarifying language, you can also give actual code examples, instead of just the string with escaped characters. (Bold stuffs are text I added.)

> In JavaScript, you can escape a quote from considering it as an end of string quote by placing a backslash (\) in front of the quote.
>
> `var sampleStr = "Alan said, \"Peter is learning JavaScript\".";`
>
> This signals JavaScript that the following quote is not the end of the string, but should instead appear inside the string. **So when you print this to the console you'll get:**
>
> `Alan said, "Peter is learning Javascript"`
> ### Instruction
> Use `backslashes` to assign **a string** to **the** `myStr` variable **so that it will print**:
>
> `I am a "double quoted" string inside "double quotes"`

**Comment by SaintPeter** [comment]
@erictleung That's brilliant.  Great idea.  Feel Free to write a PR for this one.

**Comment by roesinger** [comment]
myStr = "I am a \"double quoted\" string inside \"double quotes\".";
I'm struggling to complete this. myStr should equal (I am a "double quoted" string inside "double quotes").

**Comment by korinka** [comment]
It should be dot there: var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; 
That is a right code.

**Comment by Hassenkhel** [comment]
This how your code should be look like: var myStr = "I am a \"double quoted\" string inside \"double quotes\".";

**Comment by Hassenkhel** [comment]
This is how your code should be look like: var myStr = "I am a \"double quoted\" string inside \"double quotes\".";

**Comment by betapixel** [comment]
Hassenkhel thanks.
Look like was a bug.

**Comment by codelaw90** [comment]
This is still confusing. I did as it says in the instructions, but still not working.

**Comment by vik67562** [comment]
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

this is correct one.

**Comment by vik67562** [comment]
```
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

```

This is correct one . hope this helps .

**Comment by khoboonhua** [comment]
they are very sensitive with space between the line.hmm

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 12 ก.พ. 2017 07:15 "jin feng" <notifications@github.com> เขียนว่า

**Comment by ScottFrederickSchmidt** [comment]
Don't forget the period at the end!!!

var myStr= "I am a \"double quoted\" string inside \"double quotes\".";

**Comment by Axeex** [comment]
Try this

var myStr = "I am a \"double quoted\" string inside \"double quotes\".";

**Comment by leftybookworm** [comment]
I have attempted to try inputting every suggested solution, of which, several were exactly what I had typed in as the code for this challenge:
"I am a \"double quoted\" string inside \"double quotes\"."; 
I ran it earlier and it told me that I am missing the semicolon, there is an unknown identifier, and, now tonight, I ran the same code after looking over it again(I didn't change what I had already typed in the box earlier.) It now runs and returns: 
I am a "double quoted" string inside "double quotes". At least there isn't a list of errors now when I hover over my answer, only, red X's by both of the requirements to complete the challenge, so it still isn't accepting this answer. Is this the right answer? Is there still a bug on this challenge?
This challenge has had me stuck for some time now. Has anyone been able to input a solution and complete this challenge yet?

**Comment by ScottFrederickSchmidt** [comment]
What was the challenge name? I'll double check the solution.  For this one....  "you have a 'singlequote'  inside of the double";  

From what I remember. It was confusing.

**Comment by Taylorwynn26** [comment]
var myStr; myStr = "I am a \"double quoted\" string inside \"double quotes\".";

**Comment by jay3ss** [comment]
I had this same issue (on the beta) with Google Chrome 60.0.3112.78 on Ubuntu 14.04 and the way that I fixed it was to simply just reload the page. I've encountered this with a previous challenge too.

**Comment by jbrandes** [comment]
Was this solved? I'm running into the same problem

**Comment by resaba-kaypee** [comment]
the answer is:
"I am a (backlash)"double qouted(backlash)" string inside (backlash)"double qoutes(backlash)".";

**Comment by ndamane** [comment]
my one is saying You should use two double quotes (") and four escaped double quotes (\").
any help in this would appreciated

**Comment by vlbarner** [comment]
Not a bug but the 'feature'.
Everyone, including myself, is overthinking the purpose of the test. Edit what is given ex. that first line (**var myStr = ""; // Change this line**) is the correct line to use. Writing the corrected line underneath and leaving the pretext 'as is' is the **error!** The programs sees the pretext as incomplete and ignores everything else.
That is my observation, what do you think?

**Comment by Dinesh9418** [comment]
> Challenge [Escaping Literal Quotes in Strings](http://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0A%0Avar%20myStr%3D%22%5C%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%5C%22.%22%20%3B%0A%0A%0A%0A) has an issue.
> User Agent is: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36`.
> Please describe how to reproduce this issue, and include links to screenshots if possible.
> 
> My code:
> 
> ```js
> var myStr="\"I am a \"double quoted\" string inside \"double quotes\"\"." ;
> ```
try this ----->
var myStr = "I am a \"double quoted\" string inside \"double quotes\".";
