### ISSUE TITLE
Variable myStr should equal to ("I am a "double quoted" string inside "double quotes"").as out on console to use java script

### ISSUE THREAD

**Issue by sanwalatta** [FreeCodeCamp/FreeCodeCamp#6542]
Challenge [Escaping Literal Quotes in Strings](http://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0A%0Avar%20myStr%3D%22%5C%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%5C%22.%22%20%3B%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


var myStr="\"I am a \"double quoted\" string inside \"double quotes\"\"." ;




```

**Comment by ltegman** [comment]
Closing as a duplicate. Please don't make multiple issues for the same problem.

**Comment by jonatanR10** [comment]
The method correct
var myStr="I am a \"double quoted\" string inside \"double quotes\"";
