### ISSUE TITLE
timesFive(3) must equal 15. It shows 25.

### ISSUE THREAD

**Issue by ankurfarout** [FreeCodeCamp/FreeCodeCamp#6543]
Challenge [Return a Value from a Function with Return](http://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20timesFive(num1)%7B%0A%20%20return%20num1%20*%205%3B%0A%7D%0AtimesFive(3)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line
function timesFive(num1){
  return num1 * 5;
}
timesFive(3);

```

**Comment by sarahdulat** [comment]
I'm still having this same issue, was it solved back in January only to come back?
