### ISSUE TITLE
File Metadata Microservice example application bug (log inside)

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#6544]
>GET <code>https://cryptic-ridge-9197.herokuapp.com/ [HTTP/1.1 304 Not Modified 627ms]</code>
GET <code>https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js [HTTP/2.0 304 Not Modified 395ms]</code>
ReferenceError: <code>event is not defined cryptic-ridge-9197.herokuapp.com:20:5</code>
TypeError: a is undefined <code>jquery.min.js:2:2724</code>

Reference error is fired when file is selected by clicking Browse.
Type error - after upload button click.

**Comment by AkiraLaine** [comment]
I can't replicate this. Could you tell me what Browser/OS you're using?

**Comment by rfprod** [comment]
User-Agent: Mozilla/5.0 (X11; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0
<a href="http://imgbox.com/35JflovV" target="_blank"><img src="http://0.t.imgbox.com/35JflovV.jpg" alt="image host"/></a>

**Comment by bugron** [comment]
@rfprod I am able to reproduce. This seems Firefox specific.
![](http://i.imgur.com/FEAtW10.png)
Unfortunately there are no any contacts on that page, so if you know the author ping him/her, please.

**Comment by rfprod** [comment]
Also, it may make sense to correct a typo: double "look at" in second sentence.

**Comment by rfprod** [comment]
> Unfortunately there are no any contacts on that page, so if you know the author ping him/her, please.

By the way, I suppose @george-stepanek may be able to do something about the issue.

**Comment by george-stepanek** [comment]
Looking into it...

**Comment by george-stepanek** [comment]
Have fixed the typo and the js issue, and have checked that it works in Firefox... 
https://cryptic-ridge-9197.herokuapp.com/

**Comment by SaintPeter** [comment]
@rfprod Please confirm and close if it's fixed.

**Comment by rfprod** [comment]
Confirmed.
<a href="http://imgbox.com/l7cU8aae" target="_blank"><img src="http://6.t.imgbox.com/l7cU8aae.jpg" alt="image host"/></a>
