### ISSUE TITLE
Emulator not working - When i type anything ,it's just not appearing on the emulator

### ISSUE THREAD

**Issue by amal1994** [FreeCodeCamp/FreeCodeCamp#6545]
Challenge [Say Hello to HTML Elements](http://www.freecodecamp.com/challenges/say-hello-to-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.6.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello</h1>

```

**Comment by raisedadead** [comment]
@amal1994 Have you tried the common troubleshooting steps? Clearing cookies, cache, hard refreshing your browser (Ctrl + F5)? If yes, can you please provide some screenshots?

**Comment by amal1994** [comment]
https://gyazo.com/958393f159ab20a229195c069b0ece14

Yes, i've tried all of the above.Still no improvement

This is the link of the screenshot of my browser window.
It contains the blank emulator as well as the console output..

**Comment by bugron** [comment]
@amal1994 this seems a connection issue. Closing. Feel free to reopen if you still experience problems, thanks.
