### ISSUE TITLE
Needs a better instruction as it gives no example of bootstrap button format

### ISSUE THREAD

**Issue by carlskeel** [FreeCodeCamp/FreeCodeCamp#6546]
Challenge [Create a Bootstrap Button](http://www.freecodecamp.com/challenges/create-a-bootstrap-button#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch2%20class%3D%22red-text%20text-center%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%20%20%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%20%20%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%20%20%3Cimg%20src%3D%22http%3A%2F%2Fbit.ly%2Ffcc-running-cats%22%20class%3D%22img-responsive%22%3E%0A%0A%20%20%3Cbutton%20type%3D%22button%22%20class%3D%22btn%20btn-primary%22%3ELike%3C%2Fbutton%3E%0A%20%20%0A%20%20%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%20%20%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%20%20%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%20%20%3C%2Fform%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
<!-- example below works fine but in the instruction it only has:
*
Create a Bootstrap Button

Bootstrap has its own styles for button elements, which look much better than the plain HTML ones.

Create a new button element below your large kitten photo. Give it the class btn and the text of "Like".
*
It would be better for people new to programming to include an example in the instructions above-
*
w3c examples:
http://www.w3schools.com/bootstrap/bootstrap_buttons.asp.
-->
  <button type="button" class="btn btn-primary">Like</button>
  
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by SaintPeter** [comment]
The instructions say:
> Create a new button element below your large kitten photo. Give it the class btn and the text of "Like".

That is the entirety of what is needed to do this:
`<button class="btn">Like</button>`

If you have been paying attention to the lessons before you should know how to:
1. Create a button element
2. Add a given class to it
3. Put text inside it

Do you feel that you were inadequately prepared to any of the 3 items above?

**Comment by carlskeel** [comment]
I am fine I was saying others may be confused~

**Comment by SaintPeter** [comment]
Not really.  That's why we have the help rooms.

Thanks for your concern and Happy Coding!

**Comment by JashaAdler** [comment]
I do see Carlskeels point, since I was confused. And not because I didn't pay attention, I remembered exactly how to make a button starting with <button.., but that was HTML... The instructions said specifically that "Bootstrap has its OWN (caps mine) styles for button elements..". Logiclly following that what was covered previously is NOT what was being asked for...

**Comment by sashajustice** [comment]
I agree..it is actually quite confusing

**Comment by MysticRiver** [comment]
I agree that this is confusing. It doesn't logically follow from the previous lessons and isn't quite clear. I think better instruction should be given. The fact that several people have an issue with this lesson should be onus enough to change ir.

**Comment by vlrodriguez** [comment]
I found it a bit confusing but I knew memory played a part unfortunately I didnt remember.

**Comment by kmhubert** [comment]
It is confusing.  Don't assume that a beginner knows that when switching from one language (HTML5) to another (Bootstrap), assuming they are different languages (I have no idea) that the commands can remain the same, specifically when you say, in the directions: "Bootstrap has its OWN (caps mine) styles for button elements..".  I had no idea, and the help room didn't, there were enough other people looking for help that my requests went unanswered, so I found myself here.

Freecodecamp is fantastic, I'm really enjoying the process, but it's imperfect.  Having other resources should be celebrated, not derided, SaintPeter.

**Comment by JohnCrowbar** [comment]
I also ran into this challenge, the lesson hasn't followed the flow of its predecessors.

**Comment by dsfold** [comment]
I feel that the challenge is, for a novice, easy enough to complete with a little research but that, as was mentioned above, the bluntness (if you will) of the need for research was not expected. That being said, I had no issue with finding the proper solution to the challenge.

**Comment by davef81** [comment]
Do you feel that you were inadequately prepared to any of the 3 items above?

Yes, I was. The question was poorly worded and the flow was inconsistent. Also, Saint Peter, you think of other people's opinions first before you deride and belittle others.

Otherwise, I have enjoyed Freecodecamp so far.

**Comment by Edneedscode** [comment]
I agree with what most people her say. It is poorly worded for beginners and should sought change.
