### ISSUE TITLE
No repeats please | Test failing, but console is showing the correct and expected result

### ISSUE THREAD

**Issue by impreze** [FreeCodeCamp/FreeCodeCamp#6547]
I've tested my solution in jsfiddle and for the given test cases, it is working correctly. 

When adding my code to FCC, the first case "permAlone("aab") should return a number." is successful and the console shows 2, but fails at permAlone("aab") should return 2.

This happens with the other cases as well:

![Imgur](http://i.imgur.com/4yA0Nul.png)

My code below:
```
`var permArr = [], usedChars = [];

var permute = function(input) {
  var i, ch;
  for (i = 0; i < input.length; i++) {
    ch = input.splice(i, 1)[0];
    usedChars.push(ch);
    if (input.length === 0) {
      permArr.push(usedChars.slice());
    }
    permute(input);
    input.splice(i, 0, ch);
    usedChars.pop();
  }
  return permArr;
};



function permAlone(str) {
	var chars = str.split('');
	var perms = permute(chars);
  var permStr = [];
  
  //create array of strings
  var i, temp=[];
  for (i = 0; i<perms.length; i++){
  	temp.push(perms[i].join(''));
  }
  
  // Test for no repeat
  var uniqueArray = temp.filter(function(elem, pos) {
  	if (/(.)\1+/.test(elem) === false){
    	return elem;
    }
  }); 
  
  return uniqueArray.length;
}

`permAlone('abfdefa');``
```

**Comment by ltegman** [comment]
Using global variables to store function specific things is a bad idea. Please post to the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need further assistance as Github issues are not for challenge help.

**Comment by impreze** [comment]
I've found a [similar case](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1113) searching through Github issues and was able to apply it.
