### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-uncomment-html has an issue 

### ISSUE THREAD

**Issue by DFL1010** [FreeCodeCamp/freecodecamp#655]
Deleting the  uncomments the HTML code (and gives context highlighting in the text editor) but does not show on the preview, or allow the code to pass the requirements. 

Found a workaround of deleting and retyping a part of the code (even one character will suffice). 

Using Chrome 42.0.2311.152 on Linux Mint 17.1.

**Comment by terakilobyte** [comment]
I can't produce this, can you attach a screenshot?

**Comment by benmcmahon100** [comment]
![image](https://cloud.githubusercontent.com/assets/10749142/7844573/48838600-04a9-11e5-915a-b249c30e5b72.png)
tis complete broken in chrome
i think its the asserts have an extra parenthesis

**Comment by DFL1010** [comment]
![image](https://cloud.githubusercontent.com/assets/6044840/7844625/a5272826-04a9-11e5-9e56-af443ca8952b.png)

It's the same in the 'fill in with lorem ipsum placeholder' a few challenges on: copy in the new text, and it doesn't refresh. Delete and retype a bit of the HTML tags, and it'll refresh.
