### ISSUE TITLE
Unreachable 'break' after 'return'

### ISSUE THREAD

**Issue by theWhiteFox** [FreeCodeCamp/FreeCodeCamp#6552]
Challenge [Selecting from many options with Switch Statements](http://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%20%7B%0A%20%20%20%20case%201%3A%0A%20%20%20%20%20%20return%20%22alpha%22%3B%20%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20case%202%3A%0A%20%20%20%20%20%20return%20%22beta%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20case%203%3A%0A%20%20%20%20%20%20return%20%22gamma%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20case%204%3A%0A%20%20%20%20%20%20return%20%22delta%22%3B%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val) {
    case 1:
      return "alpha"; 
      break;
        case 2:
      return "beta";
      break;
        case 3:
      return "gamma";
      break;
        case 4:
      return "delta";      
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(1);


```

**Comment by raisedadead** [comment]
Please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help), GitHub Issues are for bugs in the site only.

**Comment by ltegman** [comment]
Good luck and happy coding!
