### ISSUE TITLE
Validate US Telephone Numbers bug - Passes every test but still fails.

### ISSUE THREAD

**Issue by AWilliams87** [FreeCodeCamp/FreeCodeCamp#6553]
Challenge [Validate US Telephone Numbers](http://www.freecodecamp.com/challenges/validate-us-telephone-numbers#?solution=function%20telephoneCheck(str)%20%7B%0A%20%20var%20regex%20%3D%20%2F%5E(1%5CW)%3F(%5C(%5Cd%7B3%7D%5C)%7C%5Cd%7B3%7D)%5CW%3F%5Cd%7B3%7D%5CW%3F%5Cd%7B4%7D%24%2F%3B%0A%20%20return%20regex.test(str)%3B%0A%7D%0A%0AtelephoneCheck(%221%20555)555-555%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function telephoneCheck(str) {
  var regex = /^(1\W)?(\(\d{3}\)|\d{3})\W?\d{3}\W?\d{4}$/;
  return regex.test(str);
}

telephoneCheck("1 555)555-555");

```

**Comment by sludge256** [comment]
Confirmed [test case] is incorrect.

**Comment by robjloranger** [comment]
I pushed a commit and made a pull request for this.

**Comment by sludge256** [comment]
@FreeCodeCamp/issue-moderators 

Is the intention of this [test](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/f5fa0428a67fdc68d5b9fc55e9da61acb1f48f89/seed/challenges/01-front-end-development-certification/advanced-bonfires.json#L43) to check for missing parenthesis or a missing number?

With the code posted it should pass if the described challenge text of `"1 555)555-555"` is what was actually being tested and not `"1 555)555-5555"`.
However, it's a different matter if the actual test is correct but the challenge text is incorrect.

**Comment by robjloranger** [comment]
yea wait lol, it might just be his regex. it's allowing an optional W between groups of numbers

**Comment by SaintPeter** [comment]
My expectation is that `telephoneCheck("1 555)555-555");` should return `false`.  This is not a passing phone number because it has unmatched parentheses.  

I do not see this as a site/test issue.

**Comment by robjloranger** [comment]
but the actual test for that assert is against 1 555)555-5555
four 5's

**Comment by sludge256** [comment]
Here is the code for convenience
```
"assert(telephoneCheck(\"1 555)555-5555\") === false, 'message: <code>telephoneCheck(\"1 555)555-555\")</code> should return false.');",
```
The test has four 5's at the end while the message only has three 5's at the end

**Comment by SaintPeter** [comment]
Ah, ok.

In that case, yes, we need to fix the typo.
