### ISSUE TITLE
Brownie points from Gitter don't keep the streak alive

### ISSUE THREAD

**Issue by trueskawka** [FreeCodeCamp/FreeCodeCamp#6556]
Hello.

As per definition from Wiki (https://github.com/freecodecamp/freecodecamp/wiki/brownie-points) I understood that Gitter brownie points would keep my streak alive. They show up in my profile as items, but my streak is down to 1.

**Comment by SaintPeter** [comment]
If brownies points did not keep your streak alive, I would not be on day 166 of my streak.

Now, we have some known issues with the time and date of incoming points.  There is currently a PR that is open to address this.  The fixes will be retroactive.  What time zone are you in?  Our server is in EST.  We should allow something like 36 hours between points, though.

**Comment by trueskawka** [comment]
Central European, GMT+1

**Comment by BerkeleyTrue** [comment]
Brownie points from thanks and completing challenges work exactly the same.

See #6697 

Happy Coding!

**Comment by trueskawka** [comment]
So it won't fix the streak? As per my calendar, I haven't broken my streak for the last 27 days, yet it doesn't work properly in my profile.
http://www.freecodecamp.com/trueskawka

**Comment by trueskawka** [comment]
My proper streak is restored.

**Comment by sludge256** [comment]
Yep, https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6850 was implemented.
