### ISSUE TITLE
Uh, Ok... 

### ISSUE THREAD

**Issue by DevCat2016** [FreeCodeCamp/FreeCodeCamp#6558]
Challenge [Uncomment HTML](http://www.freecodecamp.com/challenges/uncomment-html#?solution=%3C!--Comment%20--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--Comment -->
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragraph</p>
```

Hey all, this is the simplest little piece of code, yet I keep getting this error:
"Be sure to delete all trailing comment tags, i.e. -->."

Um, so yeah, there aren't any in my code and the lesson won't allow me to move on...
Any suggestions?

**Comment by CameSawGotserved** [comment]
Having the same issue. Anyone care to shed some light?
