### ISSUE TITLE
Looks like I've got it right?

### ISSUE THREAD

**Issue by adamhanna** [FreeCodeCamp/FreeCodeCamp#6559]
Challenge [Stand in Line](http://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20console.log(arr.length)%3B%0A%20if(arr.length%20%3D%3D%201)%7B%0A%20%20%20return%20arr%5B0%5D%3B%0A%20%7D%20else%20if%20(arr.length%20%3D%3D%3D%200)%7B%0A%20%20%20return%20item%3B%0A%20%7D%20else%7B%0A%20%20arr.push(item)%3B%0A%20%20var%20rem%20%3D%20arr.splice(0%2C1)%3B%0A%20%20%20console.log(rem)%3B%0A%20%20return%20rem%3B%20%20%2F%2F%20Change%20this%20line%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(testArr%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item) {
  // Your code here
  console.log(arr.length);
 if(arr.length == 1){
   return arr[0];
 } else if (arr.length === 0){
   return item;
 } else{
  arr.push(item);
  var rem = arr.splice(0,1);
   console.log(rem);
  return rem;  // Change this line
  }
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by adamhanna** [comment]
It's telling me that this test is failng:

queue([5,6,7,8,9], 1) should return 5

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance! Thanks and happy coding!
