### ISSUE TITLE
Billy Joel - Piano Man released in 1993? :(

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#6561]
Challenge [Introducing JavaScript Object Notation JSON]
My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1993,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
];
```

Alright, so maybe this one isn't too serious but, as a Billy Joel fan, I'm a little upset that the `release_year` 
property is incorrect.  The song was released in 1973.

Is this issue important? No, not at all. But it DOES give new users practice and make Billy Joel fans happy.

**Comment by SaintPeter** [comment]
OMG, how did I not catch this?  I'm the Billy Joel Fan responsible and I must have typoed the release year.  

If we had a "Critical" flag, I'd set it.

:blush:

**Comment by sludge256** [comment]
This and not having correct meme compliments :disappointed:
