### ISSUE TITLE
Assignment with a Returned Value

### ISSUE THREAD

**Issue by ayudyapala** [FreeCodeCamp/FreeCodeCamp#6568]
Challenge [Assignment with a Returned Value](http://www.freecodecamp.com/challenges/assignment-with-a-returned-value#?solution=%2F%2F%20Example%0Avar%20changed%20%3D%200%3B%0A%0Afunction%20change(num)%20%7B%0A%20%20return%20(num%20%2B%205)%20%2F%203%3B%0A%7D%0A%0Achanged%20%3D%20change(10)%3B%0A%0A%2F%2F%20Setup%0Avar%20processed%20%3D%200%3B%0A%0Afunction%20process(num)%20%7B%0A%20%20return%20(num%20%2B%203)%20%2F%205%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Aprocessed%20%3D%20process%20(7)%3B%0A%0A%0A%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var changed = 0;

function change(num) {
  return (num + 5) / 3;
}

changed = change(10);

// Setup
var processed = 0;

function process(num) {
  return (num + 3) / 5;
}

// Only change code below this line
processed = process (7);








```

**Comment by AkiraLaine** [comment]
Hey @ayudyapala, if you need help, please go to our main room or our help room. Although, your code seems correct :D GitHub is for issues only :smile:

**Comment by voirs** [comment]
correct code is: 

processed = process(7); 

(WITHOUT the space between process and (7)

**Comment by texas2010** [comment]
@voirs 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by srishtikashyap18** [comment]
Can anyone help me understand the challenge for "Assignment with a Returned Value".

**Comment by texas2010** [comment]
@srishtikashyap18 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by OgunniyiOwamamwen** [comment]
// Only change code below this line
var processed = 2;

function processArg(num) {

return (num * 1 ) / 3.5;
}
processed = processArg(7);

**Comment by Stanleynd** [comment]
Nothing much but just do this to go next.

// Only change code below this line
processed = processArg(7);

**Comment by isaacton** [comment]
// Only change code below this line
processed = processArg(7);
