### ISSUE TITLE
Unable to join the zipline chat room!!

### ISSUE THREAD

**Issue by manojansh** [FreeCodeCamp/FreeCodeCamp#6571]
Unable to join the zipline chat room!!

**Comment by HoBi** [comment]
Do you mean https://gitter.im/FreeCodeCamp/HelpZiplines? It works fine for me.

**Comment by bugron** [comment]
@manojansh thanks for posting. Any steps to reproduce? Any errors?

**Comment by SaintPeter** [comment]
The HelpZiplines Chat Room is deprecated and will be losing Camperbot support soon.

The new help room for Front End Projects is [HelpFrontEnd](http://gitter.im/FreeCodeCamp/HelpFrontEnd).

**Comment by ltegman** [comment]
Closing as not reproducible. If you continue having trouble with Gitter rooms you should contact their support team as we don't maintain that service.
