### ISSUE TITLE
Using Objects for Lookups

### ISSUE THREAD

**Issue by Luomint** [FreeCodeCamp/FreeCodeCamp#6573]
[image](http://puu.sh/mO5pU/a7b610cbdc.png)

https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6240 was closed incorrectly because it's impossible to complete this challenge without editing the 'var result' which is below the comment that says "only change the code above this line"

**Comment by raisedadead** [comment]
@Luomint It is possible, You just need to figure out a way! :smiley: I don't think its a bug.

Please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help)

Thanks.

**Comment by bugron** [comment]
@Luomint thanks for posting. @raisedadead is correct. 
>closed incorrectly because it's impossible to complete

It is definitely possible. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

**Comment by Luomint** [comment]
I know it is possible, but then you have to redefine the 'result var'. However, by leaving the 'result var' above the line that permits edit, it implies that you shouldn't.

**Comment by SaintPeter** [comment]
@Luomint Did you know that you can [assign values with the equality operator](http://www.freecodecamp.com/challenges/storing-values-with-the-equal-operator)?

**Comment by Luomint** [comment]
@SaintPeter I am only agreeing with people in the previous issue about this, that it feels like you shouldn't assign a new value to it, because 'var result' was intentionally left out of the borders where editing the code is permitted in two different places.
