### ISSUE TITLE
Proper highlighting for completed challenges and their containers

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#6575]
As a follow up on #6414, and as per previous approval by @QuincyLarson in PR #6403:
The fully completed containers (otherwise known as superblocks), should add a `.faded` class to their containers, as shown at the bottom in the following screen capture.
This feature is slightly beyond my skills because of the involved detection for empty chapters...
Thus, "help wanted" applies.

<img width="478" alt="screen shot 2016-01-29 at 09 01 47" src="https://cloud.githubusercontent.com/assets/2107110/12679897/b3cc91da-c674-11e5-907d-7d12c5fc7f2f.png">

------

Furthermore, The default behaviour for the map (or at least the sidebar's) should be that the completed ones are hidden, and then the button would let you see the hidden ones. I cannot think of any reason why any camper would by default want to see the completed from the beginning, when their common idea is to move forward.

This is a secondary idea and would indeed require Quincy's approval.

**Comment by SaintPeter** [comment]
See PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6464

Perhaps this could be added to that feature, since it involves exactly the detection you seek?

**Comment by hallaathrad** [comment]
Since the aesthetics of this issue are being addressed on #6464, maybe the only remaining change for this issue should be the default behaviour of the map (start with hidden completed, then "show completed" with button... and remember the user's preference). Clearly based on @QuincyLarson's input, since it's an UX/UI thing.

On further thought, should that sidebar remain opened as you click through its links for easy navigation, and then close as you click out of it (it being the sidebar)?
