### ISSUE TITLE
freecodecamp not accepting working code-bonfire-Sum All Numbers in a Range

### ISSUE THREAD

**Issue by shatmostak** [FreeCodeCamp/FreeCodeCamp#6576]
Challenge [Sum All Numbers in a Range](http://www.freecodecamp.com/challenges/sum-all-numbers-in-a-range#?solution=var%20ms%3D0%2C%0A%20%20%20%20to%3D%5B%5D%2C%0A%20%20%20%20result%3D0%3B%0A%0Afunction%20sumAll(arr)%20%7B%0A%20%20if%20(arr%5B0%5D%3Earr%5B1%5D)%7B%0A%20%20%20%20ms%3Darr%5B0%5D%3B%0A%20%20%20%20arr.shift()%3B%0A%20%20%20%20arr.push(ms)%3B%0A%20%20%7D%0A%20%20for%20(var%20i%3Darr%5B0%5D%3Bi%3Carr%5B1%5D%2B1%3Bi%2B%2B)%7B%0A%20%20%20%20to.push(i)%3B%0A%20%20%7D%0A%20%20%20result%3Dto.reduce(function(a%2Cb)%7B%0A%20%20%20%20%20return%20a%2Bb%3B%0A%20%20%20%7D)%3B%0A%0A%20%20return%20result%3B%0A%7D%0A%0AsumAll(%5B10%2C5%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ms=0,
    to=[],
    result=0;

function sumAll(arr) {
  if (arr[0]>arr[1]){
    ms=arr[0];
    arr.shift();
    arr.push(ms);
  }
  for (var i=arr[0];i<arr[1]+1;i++){
    to.push(i);
  }
   result=to.reduce(function(a,b){
     return a+b;
   });

  return result;
}

sumAll([10,5]);

```

**Comment by bugron** [comment]
@shatmostak your global variables are failing the tests. Move them into the function's scope.
Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.
