### ISSUE TITLE
Greater than or equal to 

### ISSUE THREAD

**Issue by HemanthVarmaChekuri** [FreeCodeCamp/FreeCodeCamp#6577]
Challenge [Comparison with the Greater Than Or Equal To Operator](http://www.freecodecamp.com/challenges/comparison-with-the-greater-than-or-equal-to-operator#?solution=function%20myTest(val)%20%7B%0A%20%20if%20(val%3E%3D100)%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%2220%20or%20Over%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(val%3E%3D10)%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%2210%20or%20Over%22%3B%0A%20%20%7D%0A%0A%20%20return%20%229%20or%20Under%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(101)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  if (val>=100) {  // Change this line
    return "20 or Over";
  }
  
  if (val>=10) {  // Change this line
    return "10 or Over";
  }

  return "9 or Under";
}

// Change this value to test
myTest(101);
```

**Comment by HemanthVarmaChekuri** [comment]
It is working but it is saying wrong mark

**Comment by sludge256** [comment]
While you are technically correct and should be passing all the tests as they are described, wouldn't it make more sense to change this conditional to more accurately reflect the return message?
```js
if (val>=100) {  // This conditional does not include 20-99
    return "20 or Over";
  }
```
---
Regardless, this is a bug because the tests do not match the challenge text.
```
        "assert(myTest(20) === \"20 or Over\", 'message: <code>myTest(100)</code> should return \"20 or Over\"');",
        "assert(myTest(21) === \"20 or Over\", 'message: <code>myTest(101)</code> should return \"20 or Over\"');",
```
[Link to code for contributors](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/317b27b6149cc4a3d7b2dfe7a2fb8e7d6c20090c/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2391-L2392)

**Comment by HemanthVarmaChekuri** [comment]
Thnq

**Comment by OgunniyiOwamamwen** [comment]
function testGreaterOrEqual(val) {
  if (val >= 20) {  // Change this line
    return "20 or Over";
  }
  
  if (val >= 10) {  // Change this line
    return "10 or Over";
  }

  return "9 or Under";
}

// Change this value to test
testGreaterOrEqual(10);
