### ISSUE TITLE
infinite loop can't access challenge

### ISSUE THREAD

**Issue by Abhinavfreecodecamp** [FreeCodeCamp/FreeCodeCamp#6578]
Challenge [Seek and destroy](http://www.freecodecamp.com/challenges/seek-and-destroy) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

sir i accidently typed //noprotects in a while loop and now after as soon as i open challenge the page goes in infinite loop after that the page crashes please help sir  clear my seek and destroy challenge code

**Comment by sludge256** [comment]
Either of these should solve your problem:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage

**Comment by Abhinavfreecodecamp** [comment]
thanks it works .....

**Comment by designofhumanity** [comment]
no such links
