### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue 

### ISSUE THREAD

**Issue by deadwishd** [FreeCodeCamp/freecodecamp#658]
![waypoint add different padding](https://cloud.githubusercontent.com/assets/5685082/7844711/969b81d6-04b2-11e5-8db2-1c3d8d6286f1.png)
test cases do not work correctly

"tests": [
+        "assert($('.green-box').css('padding-top') === '40px', 'Your <code>green-box</code> class should give the top of elements 40px of padding.')",
         "assert($('.green-box').css('padding-left') === '40px', 'Your <code>green-box</code> class should give the left of elements 40px of padding.')",
+        "assert($('.green-box').css('padding-right') === **'20px'**, 'Your <code>green-box</code> class should give the right of elements **40px** of padding.')",
         "assert($('.green-box').css('padding-bottom') === '20px', 'Your <code>green-box</code> class should give the bottom of elements 20px of padding.')"
       ],

updated with screenshot

**Comment by terakilobyte** [comment]
Thanks, the description of the test has been updated!
