### ISSUE TITLE
Not a challenge

### ISSUE THREAD

**Issue by dennis-wolfers** [FreeCodeCamp/FreeCodeCamp#6580]
Challenge [Confirm the Ending](http://www.freecodecamp.com/challenges/confirm-the-ending#?solution=function%20end(str%2C%20target)%20%7B%0A%20%20return%20str.endsWith(target)%3B%0A%7D%0A%0Aend(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function end(str, target) {
  return str.endsWith(target);
}

end("Bastian", "n");

```

It's not a bug, but I didn't want to post what might be considered a way to cheat. Is using my ridiculously simple solution cheating, or missing the point of the challenge?

**Comment by ltegman** [comment]
That is not the goal of the challenge. We have a bug open about this: #4764. Closing as a duplicate. Thanks and happy coding!
