### ISSUE TITLE
Stuck ont the css section

### ISSUE THREAD

**Issue by Marcusjohnson115** [FreeCodeCamp/FreeCodeCamp#6582]
Challenge [Use a CSS Class to Style an Element](http://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%20h2%20.red-text%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 .red-text{
    color: red;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Marcusjohnson115** [comment]
Caught a road block with css

**Comment by sludge256** [comment]
Closing as it looks like your issue has been resolved in the main chat. In the future please use the help button on the challenge page to connect with the help chat. Github issues are not meant for coding help.

**Comment by revisualize** [comment]
<style>
  h2 .red-text{
    color: red;
  }
</style>
<h2>CatPhotoApp</h2>

this should be your code

<style>
  .red-text{
    color: red;
  }
</style>
<h2 class="red-text">CatPhotoApp</h2>

As described during the instructional section on the left side:

Classes are reusable styles that can be added to HTML elements.

Here's an example CSS class declaration:

<style>
  .blue-text {
    color: blue;
  }
</style>
You can see that we've created a CSS class called blue-text within the <style> tag.

You can apply a class to an HTML element like this:

<h2 class="blue-text">CatPhotoApp</h2>

Note that in your CSS style element, classes should start with a period. In your HTML elements' class declarations, classes shouldn't start with a period.

Inside your style element, change the h2 selector to .red-text and update the color's value from blue to red.

Give your h2 element the class attribute with a value of 'red-text'.
