### ISSUE TITLE
Ability to filter challenge map with realtime search

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6586]
@hallaathrad @bugron @SaintPeter 

As we discussed on our call, we want a search box at the top of the map.

![](https://www.evernote.com/l/AqQ3qSEXW2pIv7MrrWQxAZ7r2N-vrunL0VwB/image.jpg)

**Comment by SaintPeter** [comment]
I'll be working on this one this weekend.
