### ISSUE TITLE
"Copy as..." overzealous popup

### ISSUE THREAD

**Issue by ryanforever** [FreeCodeCamp/FreeCodeCamp#6587]
The new "Copy {Link, as Pretty Code, as Plain Code}" popup feature appears even when I am just trying to highlight part of a line to delete at once. As a result, it is almost always on my screen, and my feeling is that it would be the right move to offer a "Never show this again" option or at least some way to switch it off.

**Comment by hallaathrad** [comment]
This item is currently being worked on, and will be (at least temporarily) removed...
Please pardon our dust as we work on improving the site :)
