### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-clean-up-your-form-using-linebreaks has an issue 

### ISSUE THREAD

**Issue by hrtovey** [FreeCodeCamp/freecodecamp#659]
In personality input label, replace ableist word "crazy" with more precise word "energetic" to be in line with Code of Conduct.

For more information, here's a good breakdown. http://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

**Comment by terakilobyte** [comment]
@hrtovey thanks for the provided link. I've cleaned up the copy!
