### ISSUE TITLE
Front End Certificate Will Not Generate

### ISSUE THREAD

**Issue by otternonsense** [FreeCodeCamp/FreeCodeCamp#6591]
I completed the items marked with a * located before the front end certificate, but then when I completed the "Claim Your Front End Development Certificate" challenge, it did not create a certificate even though it said that it was successful. Am I missing something?

**Comment by SaintPeter** [comment]
Interesting.  We'll look into it.

@BerkeleyTrue - got another one here.

**Comment by mdepak** [comment]
I tried reproducing this issue...ii could complete the front end certification challenge even though the bonfire and zip lines are not completed. And the certificate does not appear ..But the challenge should be completed before the previous challenges are done

**Comment by otternonsense** [comment]
I ran through the challenge again today and it produced a certificate so this can be closed. The challenge looked slightly different (word Sample on certificate of step one and different verbiage in instructions) so it may have been an update the fixed the issue.
