### ISSUE TITLE
"Add Two Numbers With Javascript" Lesson Typo

### ISSUE THREAD

**Issue by sherouk** [FreeCodeCamp/FreeCodeCamp#6595]
Instructions
"Change the 0 so that sum will equal 20." - The sum ALREADY equals 20. Didn't have to change anything.

Challenge [Add Two Numbers with JavaScript](http://www.freecodecamp.com/challenges/add-two-numbers-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var sum = 10 + 10;

// Only change code above this line.

(function(z){return 'sum='+z;})(sum);

```

**Comment by hallaathrad** [comment]
hmmm the original code is:
```js
var sum = 10 + 0;
````
which is not equal to 20. I'm not sure how your code was already 10+10, but if you press reset you'll notice it is as I stated.

**Comment by sherouk** [comment]
Yeah actually just after I sent that I noticed it was already giving me the
answers with the next few challenges until I reset it. I don't know what's
going on with my browser. Thanks!

--
Sherouk Omara
www.sheroukomara.com
219.671.8621

   - *LinkedIn* <http://www.linkedin.com/in/sheroukomara/>

**Comment by hallaathrad** [comment]
Great! it is possible you or someone has already submitted solutions to these exercises? the answers get stored in your machine...

**Comment by sherouk** [comment]
I don't think so. They were all marked as 'new', but I cleared all my
browsing data and history so hopefully it won't happen anymore.

--
Sherouk Omara
www.sheroukomara.com
219.671.8621

   - *LinkedIn* <http://www.linkedin.com/in/sheroukomara/>

**Comment by SaintPeter** [comment]
The `new` tag means that the challenge is new to the website, not that it's new to you.

If you ever viewed someone else's solution to this challenge then their code would be in your local storage.
