### ISSUE TITLE
Math.floor is not a function ?

### ISSUE THREAD

**Issue by warrenonline** [FreeCodeCamp/FreeCodeCamp#6596]
Challenge [Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript#?solution=var%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20Math.floor(Math.random()%20*%2010)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This continually returns "**Math.floor is not a function**". Doesn't Math.floor have to be a function for this to work ?

My code:
```javascript
var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function myFunction() {

  // Only change code below this line.

  return Math.floor(Math.random() * 10);
}

```

**Comment by AkiraLaine** [comment]
I can't reproduce your issue. Your code works for me. Can someone else test this @FreeCodeCamp/issue-moderators

**Comment by ltegman** [comment]
I can't reproduce this either. Please try refreshing the page and clearing you cache if that doesn't work. Please let us know if that clears up the issue and show us a screenshot of your browser console if you are still experiencing the problem.

**Comment by warrenonline** [comment]
I cleared the cache and that fixed the issue. Thanks !
