### ISSUE TITLE
Some challenges are already completed by default

### ISSUE THREAD

**Issue by DevAssasin** [FreeCodeCamp/FreeCodeCamp#6597]
Hello FCC,

I have started with FCC journey, and with a great zeal started with HTML5 stuffs.
I noticed that my first challenge was pre-complete. I thought maybe its a feature to get you acquainted to the system.
But it continued with the subsequent 4-5 challenges. It feels like a bug.
The challenge is already done, and all test cases are in passed state (green tick mark).
Attaching the snapshots.
Please have a look.

Thanks

![fcc_snapshot](https://cloud.githubusercontent.com/assets/16923505/12694006/193fc972-c744-11e5-8ca1-e406580680b4.PNG)

![fcc_snapshot1](https://cloud.githubusercontent.com/assets/16923505/12694008/2e64c50a-c744-11e5-8219-82684cc19815.PNG)

**Comment by AkiraLaine** [comment]
His profile shows that he has not done those challenges: http://www.freecodecamp.com/devassasin

**Comment by AkiraLaine** [comment]
This was a local cache/cookies problem (the user had used FCC with a different account in the past). Clearing them fixed the issue.

**Comment by DevAssasin** [comment]
Yeah..I had an old account in which I had done 50 odd challenges..and they were sitting in my local cache.
Deleting the cache did the trick.
Thanks

**Comment by SparshMc07** [comment]
or try changing your browser
