### ISSUE TITLE
Label correction

### ISSUE THREAD

**Issue by bumbeishvili** [FreeCodeCamp/FreeCodeCamp#6598]
&nbsp;When  I inspect other peoples profile, their solutions column text is `View my solution`, which shows their solutions to challenge, not mine. 

  &nbsp; I think text should be `View his/her solution` or simply `View solution`

![untitled](https://cloud.githubusercontent.com/assets/6873202/12694044/fa530048-c738-11e5-9c57-fa4cda78e3e7.png)

**Comment by raisedadead** [comment]
I agree that changing the Label/Link to "View solution" is a better and generic option.
We of course can have check: 
```
if user is visiting his page 
    then display "View my solution"
else
    display "View solution"
```
But that's just a overkill.

I fell just changing the text to "View solution" should be pretty straight, and generic.

**Comment by emorres25** [comment]
I am new to programming and I want to contribute to open source. I can correct this. Let me.

**Comment by ltegman** [comment]
@emorres25 I'm sorry, but there is already a PR open to fix this.

**Comment by emorres25** [comment]
Its okay! I am getting used to this place as of now. I don't even know how to search for the file that contains the code to be fixed. Sorry! and thanks! :)

**Comment by SaintPeter** [comment]
@emorres25 If you look just above your first message in the chain you can see this:
![image](https://cloud.githubusercontent.com/assets/553494/12703803/a981d04a-c800-11e5-8813-e9209e3869d4.png)

That shows that this issue has a PR.  If you are interested in contributing, please review [Contriburing.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).  You can also get assistance in the [HelpContributors Chat](https://gitter.im/FreeCodeCamp/HelpContributors).
