### ISSUE TITLE
Add world language support

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6609]
~~Note that we want to make the Spanish versions of challenges available at:~~
/es/challenges/challenge-block/challenge-name

If you:
1. visit the Spanish challenge name URL or 
2. visit an English challenge but have Spanish selected as your "worldLanguage" attribute, that challenge's description and name should be in Spanish.

edit(@berkeleytrue):

All urls will have language encoded within. The default will be `/en`.

* Users will set up their preference in the settings page
* Users will chose from those langauges that are 99% complete

**Comment by BerkeleyTrue** [comment]
This will come in the react part of the app.
