### ISSUE TITLE
Sidebar map is distorted on high res monitors

### ISSUE THREAD

**Issue by benmcmahon100** [FreeCodeCamp/FreeCodeCamp#6610]
![image](https://cloud.githubusercontent.com/assets/10749142/12695900/c7545bd6-c753-11e5-9319-9502090c10c6.png)

**Comment by hallaathrad** [comment]
being fixed right now at PR [#6592](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6592)... 
just waiting for the big boss to approve and merge :+1:

**Comment by bugron** [comment]
@benmcmahon100 thanks for posting. Closing as a duplicate of #6564.

**Comment by benmcmahon100** [comment]
@bugron Oops! Awesome!
