### ISSUE TITLE
Cursor in code editor can't be placed beyond a few columns to the right

### ISSUE THREAD

**Issue by mrthnmn** [FreeCodeCamp/FreeCodeCamp#6611]
I have occasionally found that I couldn't place the cursor more than a few columns to the right in the code editor. Different lines will go a different number of columns. Usually I can fix it with some type of refresh or log-out/in. I can't really remember exactly. Today I was not able to fix it with either a hard refresh or logging out/in.

**Comment by mrthnmn** [comment]
I'm using Google Chrome on Windows 7 Professional today. Previously, A recent version of Firefox on Windows 7.

**Comment by raisedadead** [comment]
@mrthnmn Thanks for the issue, could you provide some screenshots too?

**Comment by mrthnmn** [comment]
It's still happening with Firefox on Ubuntu too.

Screenshot:
![screenshot from 2016-01-30 12 52 19](https://cloud.githubusercontent.com/assets/16947760/12697421/a0b91686-c750-11e5-8495-214021d3f2f9.png)

**Comment by SaintPeter** [comment]
I believe there is a known issue with CodeMirror when there are wrapped lines.  If you press space and then delete it will rejigger the code/cursor line matching.  

Give that a try and see if it helps.

**Comment by mrthnmn** [comment]
That did it! Thank you! I tried searching the site for the problem but couldn't find anything.
