### ISSUE TITLE
Palindrome test case error

### ISSUE THREAD

**Issue by odran037** [FreeCodeCamp/FreeCodeCamp#6613]
The last two test cases are switched around:

palindrome("1 eye for of 1 eye."); // should return false.
palindrome("0_0 (: /-\ :) 0-0"); // should return true.

It should instead be true and the second one false;

**Comment by ltegman** [comment]
I can assure you both test cases are correct as they are now. Reread all the instructions for the challenge and visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you still need assistance.

**Comment by odran037** [comment]
Ah you're right. My eyes fooled me.
