### ISSUE TITLE
Consider adding testcases for input 2, 3 and 4 for Roman Numerals

### ISSUE THREAD

**Issue by ShipsWithCannons** [FreeCodeCamp/FreeCodeCamp#6616]
The following works for all given testcases, but doesn't work for 2, 3 and 4. This isn't obvious at first glance. Consider adding a testcase for at least one of these values. Now it's possible to submit broken code for values which should definitely work.

    function convert(num) {
      roman = "";
      for (var i = 0; i < num; i++) {
        //MDCLXVI
        if (!(num % 1000)) { roman += "M"; num -= 1000; }
        else if (!(num % 500)) { roman += "D"; num -= 500; }
        else if (!(num % 100)) { roman += "C"; num -= 100; }
        else if (!(num % 50)) { roman += "L"; num -= 50; }
        else if (!(num % 10)) { roman += "X"; num -= 10; }
        else if (!(num % 5)) { roman += "V"; num -= 5; }
        else if (!(num % 1)){ roman += "I"; num -= 1; }
      }
      roman = roman.split('').reverse().join('');
      var translationMap = {
        DCCCC : 'CM',
        CCCC : 'CD',
        LXXXX : 'XC',
        XXXX : 'XL',
        VIIII : 'IX',
        IIII : 'IV',
      };
      for (var i in translationMap) {
        roman = roman.replace(new RegExp(i,'g'), translationMap[i]);
      }
      return roman;
    }

[Run at Repl.it](https://repl.it/BgEm/2)

**Comment by raisedadead** [comment]
Yup confirmed. Your code indeed passes all the tests, but 
`convert(2);`
`convert(3);`
`convert(4);`
Show incorrect output in the console, that's the only hint of an incorrect code, need additional tests.

I am just wandering anymore corner cases that might come up! 

BTW Good Catch!

**Comment by ShipsWithCannons** [comment]
Credit for the catch goes to [Jonah](http://codereview.stackexchange.com/a/117923/52915).
