### ISSUE TITLE
Weird nav dropdown om jobs page om mobile

### ISSUE THREAD

**Issue by ChristianBertram** [FreeCodeCamp/FreeCodeCamp#6617]
Om the jobs page, when i open the dropdown navigation, it opens a small horisontal box, instead of spanning the intire width og the page. I am using a OnePlus 2

**Comment by alistermada** [comment]
I can recreate the problem by re-sizing my browser on desktop:
![image](https://cloud.githubusercontent.com/assets/12993334/12699532/5aa8cd5c-c7f1-11e5-86af-319275ee06e4.png)

**Comment by sahat** [comment]
Also getting inconsistent UI across IE, Firefox and Chrome. In IE it look completely broken.

I can take a look at it and investigate the issue, then submit a PR.
