### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons has an issue 

### ISSUE THREAD

**Issue by ThiagoFerreir4** [FreeCodeCamp/freecodecamp#662]
Please tell us in detail here how we can make this challenge better.
Small typo:
reads: <i class="fa fa-thumbs-up"></i>
example from: http://fortawesome.github.io/Font-Awesome/icon/thumbs-o-up/ shows: <i class="fa fa-thumbs-o-up"></i> 
Also my code is not passing though it is correct.

**Comment by terakilobyte** [comment]
Couldyou post a screenshot? I was able to get it to pass by adding the <i> element within the button's html (not the attributes) <button stuff><i stuff></i>button text</button>

**Comment by ThiagoFerreir4** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10325354/7845915/db1a78fc-04c2-11e5-9cba-3174506c09d7.png)

**Comment by terakilobyte** [comment]
Also, thumbs-up is also an icon, and the one we want. that's what the test is checking for.

**Comment by ThiagoFerreir4** [comment]
Neither of them are passing.
<i class="fa fa-thumbs-up"></i>
<i class="fa fa-thumbs-o-up"></i>

**Comment by terakilobyte** [comment]
I'm unable to reproduce this in either chrome or firefox. Replace the line with the "like" button with this exactly `<button class='btn btn-block btn-primary'><i class='fa fa-thumbs-up'></i>Like</button>` and post a screenshot please.

**Comment by ThiagoFerreir4** [comment]
Alright, you can close it this as it passed after refreshing it several times. I'm using Chrome btw.
