### ISSUE TITLE
jQuery - animation bounce apply to different buttons

### ISSUE THREAD

**Issue by florianjosefreheis** [FreeCodeCamp/FreeCodeCamp#6623]
Please advice guys, I can't add the animation to the different buttons.
Thanks

Challenge [Target Elements by Class Using jQuery](http://www.freecodecamp.com/challenges/target-elements-by-class-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by raisedadead** [comment]
Thanks @florianjosefreheis, but please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help), GitHub Issues are for bugs in the site only.

**Comment by florianjosefreheis** [comment]
ok, next time I know it. May I ask you if you can support me in this case?
