### ISSUE TITLE
Evaluator doesn't recognize this solution.

### ISSUE THREAD

**Issue by Sajuuk51** [FreeCodeCamp/FreeCodeCamp#6624]
Challenge [Golf Code](http://www.freecodecamp.com/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(strokes%20%3C%202)%20%7B%0A%20%20%20%20return%20%22Hole-in-One!%22%0A%20%20%7D%20else%20if(strokes%20-%20par%20%3C%20-1)%20%7B%0A%20%20%20%20return%20%22Eagle%22%0A%20%20%7D%20else%20if(strokes%20-%20par%20%3C%200)%20%7B%0A%20%20%20%20return%20%22Birdie%22%0A%20%20%7D%20else%20if(strokes%20-%20par%20%3C%201)%20%7B%0A%20%20%20%20return%20%22Par%22%0A%20%20%7D%20else%20if(strokes%20-%20par%20%3C%202)%20%7B%0A%20%20%20%20return%20%22Bogey%22%0A%20%20%7D%20else%20if(strokes%20-%20par%20%3C%203)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Go%20Home!%22%0A%20%20%7D%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(1%2C%201)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The lesson evaluator does not recognize this solution. It says function golfScore needs to return "hole in one" when either golfScore(4, 1); or golfScore(1, 1) is used. The function returns "hole in one" whenever the strokes are less than 2.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes < 2) {
    return "Hole-in-One!"
  } else if(strokes - par < -1) {
    return "Eagle"
  } else if(strokes - par < 0) {
    return "Birdie"
  } else if(strokes - par < 1) {
    return "Par"
  } else if(strokes - par < 2) {
    return "Bogey"
  } else if(strokes - par < 3) {
    return "Double Bogey"
  } else {
    return "Go Home!"
  }
  
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(1, 1);
golfScore(4, 1);
```

**Comment by rantzay** [comment]
Your code is working exactly the way it should as written. Rememeber that the code is read top down and will only read to the first statement that is true and no further.  Adjust your code logic accordingly and you will easily pass this challenge. You are very close to passing already and understand most of the concepts involved.

**Comment by Sajuuk51** [comment]
It should already pass. It meets all the listed requirements.

**Comment by rantzay** [comment]
You are correct. My mistake on that, I only glanced through the code and missed what was going on.  So, the real issue is really small one that trips everyone up from time to time, especially with these types of tutorials.  Your "Hole-in-One!" needs to read "Hole-in-one!"  Make sure all your returned values match the test responses exactly (and in this case the table of values/responses).  One minor detail like an extra space, or in this case a word being capitalized, will throw off the elevator and return a false test.

**Comment by ltegman** [comment]
@rantzay Is correct about your return value not being exactly correct. Thanks and happy coding!
