### ISSUE TITLE
Hi, that's should work - i checked in challenges of other people, but it's not working. I tried everything.

### ISSUE THREAD

**Issue by GripexNoc** [FreeCodeCamp/FreeCodeCamp#6625]
Challenge [Local Scope and Functions](http://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20'Thats%20not%20working...'%3B%0A%7D%0A%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 'Thats not working...';
}

myFunction();

// run and check the console 
// myVar is not defined outside of myFunction

// now remove the console log line to pass the test


```

**Comment by ltegman** [comment]
My guess is that you originally declared it globally, so there was a variable in the global namespace even though your current code doesn't have a global variable. Please try refreshing the page and see if that fixes it.

**Comment by batjko** [comment]
I ran into the same issue here. As suggested by @ltegman suggested, refreshing the page worked.

I think letting the namespace of previous versions of the code hang around is very counter-intuitive. Perhaps this should be pointed out to people where this is a risk.

**Comment by GripexNoc** [comment]
It's working now! Thanks for help guys!
