### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue 

### ISSUE THREAD

**Issue by xracers12** [FreeCodeCamp/freecodecamp#663]
Please tell us in detail here how we can make this challenge better. Padding-right should say 20px in directions on the bottom, it says 40px.

**Comment by terakilobyte** [comment]
Thanks, this is a duplicate of several opened and closed issues and has been addressed in a commit and will be released soon!
