### ISSUE TITLE
for loop

### ISSUE THREAD

**Issue by akshayananddbg** [FreeCodeCamp/FreeCodeCamp#6635]
Challenge [Understanding Uninitialized Variables](http://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%206%3B%0Avar%20b%20%3D%20156%3B%0Avar%20c%20%3D%20%22I%20am%20a%20%22%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Initialize these three variables
var a = 6;
var b = 156;
var c = "I am a ";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by ltegman** [comment]
This does not describe a bug. If you are having trouble with a challenge please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help). Thanks and happy coding!
