### ISSUE TITLE
Zoom related issue on GoogleChrome/Linux Mint

### ISSUE THREAD

**Issue by cladddd** [FreeCodeCamp/FreeCodeCamp#6639]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%0A%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%0A%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

OS is Linux Mint 3.11.0-12, browser :Google Chrome Version 48.0.2564.97 (64-bit)
Zoom is not read correctly although is set to 100% and cannot proceed my task further even after page refresh

My code:
```html
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.
</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.
</p>

```

**Comment by MatheusAN27** [comment]
It's not an issue, based on the link that is on the post I believe the html code is wrong, let me explain:
The problem asks this: 
**Inside the same <style> tag that contains your red-text class, create an entry for p elements and set the font-size to 16 pixels (16px).**

### In your code you do this:
```
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>
```
and add the class_ red-text_ to the second <p> element.

### What you should have done:
```
<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>
```
and don't add any class to the second <p> element.

**Comment by cladddd** [comment]
Ok, sorry, need to read more carefully

Thank you

**Comment by MatheusAN27** [comment]
It's not an issue, based on the link that is on the post I believe the html code is wrong, let me explain:
### The problem asks this:

**Inside the same `<style>` tag that contains your red-text class, create an entry for p elements and set the font-size to 16 pixels (16px).**
### In your code you do this:
```
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>
```
and add the class_ red-text_ to the second `<p>` element.

### What you should have done:
```
<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>
```
and don't add any class to the second `<p>` element.

Sorry for the other answer, it was badly formatted.

**Comment by meenareddyv** [comment]
Hi,

my code is 

<style>
  .red-text {
    color: red;
      }
  p{
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text"> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

But still it is showing some browser zoom error.

**Comment by cladddd** [comment]
Hi my code looked like this:
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
  p {
    font-size: 16px;
  }
</style>


<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed
everywhere stretching attack your ankles chase the red dot, hairball run
catnip eat the grass sniff.
</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed
everywhere rip the couch sleep in the sink fluffy fur catnip scratched.
</p>

and it worked.

If still does not work try adding the font manually to that paragraph
<p style font-size:16x;>Purr jump eat the grass rip the couch scratched
sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip
scratched.
</p>


Cheers,
Claudiu
