### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue 

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/freecodecamp#664]
Challenge doesn't require the closing `</div> tags to be implemented in order to pass.

**Comment by terakilobyte** [comment]
A lot of closing tags are in fact optional. Our tests check what the dom is rendering, not the values in the editor. Thanks for the report, closing this as it's been raised and addressed many times before.
