### ISSUE TITLE
Make it more understandable...

### ISSUE THREAD

**Issue by wolverine2k** [FreeCodeCamp/FreeCodeCamp#6641]
The "Join Strings with .join" challenge is a bit confusing when read quickly for the first time. Suggestion is to include the output of console.log(joinedString) in the example stated:

i.e. 
The following is an example of using join to join all of the elements of an array into a string with all the elements separated by word `Na`:

var joinMe = ["Na ", "Na ", "Na ", "Na ", "Batman!"];
var joinedString = joinMe.join("Na ");
console.log(joinedString);

Output: joinedString = "Na Na Na Na Na Na Na Na Batman!"

Or the example could be made a little bit less confusing by doing the following.

var joinMe = ["Batman ", "Joker!"];
var joinedString = joinMe.join("kills ");
console.log(joinedString);

Output: joinedString = "Batman kills Joker!"

Cheers

**Comment by ltegman** [comment]
I don't think this would be a good example because it relies on having a space on one word and not the other and is also very atypical of how join would be used. Most commonly join is used to join words with a space or some piece of punctuation between them, as is done in the current example. I'll leave this open to get other people's opinions.

**Comment by SaintPeter** [comment]
I would be open to an example that more clearly illustrates what is being added during the join operation.  The key would be something that alternates, like `e i e i o` maybe?  

In reality we don't use `join` with words much.

We just need a good illustration.

**Comment by wolverine2k** [comment]
You are right. I particularly like the below example stolen from w3schools (http://www.w3schools.com/jsref/jsref_join.asp)

var fruits = ["Banana", "Orange", "Apple", "Mango"];
var energy = fruits.join(" and ");
console.log(energy);
Output: Banana and Orange and Apple and Mango

**Comment by bhaskar20** [comment]
Example avoiding spaces alltogether for simplicity
var joinMe = ["Batman","kills", "Joker!"];
var joinedString = joinMe.join("-");
console.log(joinedString);

Output: joinedString = "Batman-kills-Joker!"

**Comment by SaintPeter** [comment]
I am not above stealing, but maybe we could use Veggies or something?
```js
var veggies = ["Celery", "Radish", "Carrot", "Potato"];
joinedString = veggies.join(" and ");
```

**Comment by wolverine2k** [comment]
+1 @SaintPeter

**Comment by jncampbell** [comment]
+1 @bhaskar20

**Comment by SaintPeter** [comment]
ok, if someone wants to take this with the veggies example, I'd love to see a PR for it.

**Comment by kalunlee136** [comment]
Hi, I can work on this one. 

Also, I thought of another example using the existing Batman one:

var joinMe = ["Na ", "Na ", "Na ", "Na ", "Batman!"];
var joinedString = joinMe.join("- ");
console.log(joinedString);

Output: joinedString = "Na-Na-Na-Na-Batman!"

I find this one to be a lot more clear and avoids possible mistakes with white space, similar to @bhaskar20's example.

**Comment by bhaskar20** [comment]
@kalunlee136 your example has some mistakes though

**Comment by kalunlee136** [comment]
@bhaskar20 Did you mean the extra white space on the first "Na " in joinMe? because I just caught that. Woops.

**Comment by wolverine2k** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6732 A pull request is issued! Cheers.
