### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by 267296** [FreeCodeCamp/freecodecamp#665]
In the instructions for the margin, you have the pixel setting for "Top" to 20px instead of 40px.

**Comment by terakilobyte** [comment]
Thanks, commit 119060dc3f8df694bd2ee5214a3fb590fc6210d6 addresses this.
