### ISSUE TITLE
Didnt save my progress

### ISSUE THREAD

**Issue by AirSeeker** [FreeCodeCamp/FreeCodeCamp#6651]
something wrong with //! moment-timezone.js
When i hit "Submit and go to my next challenge" it give me error "Uncaught TypeError: Cannot read property 'join' of null" and its link to //! moment-timezone.js . 30 line in http://www.freecodecamp.com/js/vendor-main-00eff8238f.js

**Comment by SaintPeter** [comment]
What browser/OS are you using?

**Comment by AirSeeker** [comment]
Chrome 48.0.2564.97 m 
Windows 10

**Comment by SaintPeter** [comment]
Any chance that you can try another browser?

**Comment by AirSeeker** [comment]
also tryed microsoft edge. same. 
i will try firefox latter

**Comment by AirSeeker** [comment]
Firefox work good

**Comment by melodysmiles** [comment]
Me too.
Chrome 48.0.2564.97 m doesn't work, but Firefox is fine.

**Comment by AkiraLaine** [comment]
This is the same issue as #6633 - I'll close this issue since it's a duplicate.
