### ISSUE TITLE
Wrong "Verify this certification" link in Data Visualization Certification

### ISSUE THREAD

**Issue by NicolaFerracin** [FreeCodeCamp/FreeCodeCamp#6652]
I noticed the "Verify this certification" link at the bottom of the Data Visualization Certification is not correct. It ends with "/data-vis-certification" while it should end with "/data-visualization-certification".

It looks like the problem lays at line 5 [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4c9026a354af711f291110f683adae34d96090f4/server/views/certificate/data-vis.jade).

**Comment by SaintPeter** [comment]
Your Journeyman project could be to file the PR to fix this.  Good catch!

**Comment by anuragaryan** [comment]
If the issue is still unfixed, can I send the Pull Request?

**Comment by SaintPeter** [comment]
You may absolutely @anuragaryan - That's what it's here for!

Make sure you follow the guidelines in [Contributing.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you get stuck, ask for help in [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors).
