### ISSUE TITLE
Using Objects for Lookups - Need Instructions Clarification

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6657]
Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20var%20lookup%20%3D%20%7B%0A%20%20%20%20alpha%3A%20%22Adams%22%2C%0A%20%20%20%20bravo%3A%20%22Boston%22%2C%0A%20%20%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20%20%20delta%3A%20%22Denver%22%2C%0A%20%20%20%20echo%3A%20%22Easy%22%2C%0A%20%20%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20lookup%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The instructions say:
>Convert the switch statement into a lookup table called lookup. Use it to lookup val and **return the associated string**.

(Emphasis added)

Which leads to this solution:
```javascript
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
 var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };

  // Only change code above this line
  return lookup[val];  // <-----   They modified this line
}
```

I think the confusion is that the instructions say to `return the associated string`.

They should probably say:
> Convert the switch statement into a lookup table called lookup. Use it to lookup val and assign the associated string to the `result` variable.

**Comment by SaintPeter** [comment]
Ref:  #6453

**Comment by jundc1006** [comment]
You should remove the** result** declaration as the accepted result doesn't include it and the instruction should not include _"and assign the associated string to the result variable"._

**Comment by SaintPeter** [comment]
@jundc1006 If you want to open a new issue with your comment we can see about making an adjustment.  Closed issues do not get new actions.

**Comment by lelecarabina** [comment]
This is how I solved it: 
var lookup = {
    "alpha":"Adams",
    "bravo":"Boston",
    "charlie":"Chicago",
    "delta":"Denver",
    "echo":"Easy",
    "foxtrot":"Frank"
  };
  result=lookup[val];

**Comment by adriennecodes** [comment]
This shouldn't be closed.  The solution requires the user to modify the code below the line 

//only change code above this line

 to say 

result = lookup[val];

when the original code reads, 

return result;

**Comment by Vuyi** [comment]
var lookup = {
"alpha":"Adams",
"bravo":"Boston",
"charlie":"Chicago",
"delta":"Denver",
"echo":"Easy",
"foxtrot":"Frank"
};
result=lookup[val]; Is not working.I'm not sure what is wrong

**Comment by RazaKazim** [comment]
var lookup = {
"alpha": "Adams",
"bravo": "Boston",
"charlie": "Chicago",
"delta": "Denver",
"echo": "Easy",
"foxtrot": "Frank"
};
var val = "bravo";
val = lookup[val];

**Comment by cflamenco** [comment]
hi can anybody help me with this problem I encounter?

what would be the proper way to solve this.
thank you

![js](https://cloud.githubusercontent.com/assets/20765708/17391384/2874504c-5a48-11e6-8bb9-35ea797ce689.png)

**Comment by Annamazing** [comment]
you need to add:
  result = lookup[val];

under your var lookup :)

**Comment by misterhtmlcss** [comment]
Need to figure it out, use a desktop coding IDE and here is an example of how I wrote it too. PS. It includes the console.log at the bottom.

`
// Setup
function phoneticLookup(val) {
  var result; // also tweaked the var result too. No need for this "" stuff.

  // Only change code below this line
  var lookup = {
   "alpha": "Adams",
   "bravo": "Boston",
   "charlie": "Chicago",
   "delta": "Denver",
   "echo": "Easy",
   "foxtrot": "Frank"
  };
 
  // Only change code above this line - below is how I did it. Some people tweaked above the line, 
// but that seems overly codie for me
  return result = lookup[val];
}

// Change this value to test - I add console.log sometimes to help figure stuff out.
console.log(phoneticLookup("charlie"));
`
@cflamenco perhaps this is helpful to see how I did it, besides the answer above mine. 
Happy Camping everyone!!

**Comment by JW89** [comment]
"Convert the switch statement into a lookup table called lookup" should be: "Convert the switch statement into a lookup variable". 

Suddenly your talking about lookups and tables. Took me 20 mins to find out a lookup-table is nothing more than a variable named lookup.

**Comment by jonthemod** [comment]
It took me a while to figure out as well. Based on the instructions alone, I had no idea I had to add:

result=lookup[val]

Glad I'm not the only one who had this issue!

**Comment by emanelmaddawy** [comment]
var lookup = {
"alpha": "Adams",
"bravo": "Boston",
"charlie": "Chicago",
"delta": "Denver",
"echo": "Easy",
"foxtrot": "Frank"
};
return lookup[val]
}
phoneticLookup("charlie");
this run with me

**Comment by Boba-nununu** [comment]
wouldnt have gotten past this unless I google-fu'd it and came here.  Ty all

**Comment by Tatendaz** [comment]
@cflamenco  you need to assign lookup[val] to result
![screen shot 2016-09-21 at 1 06 04 am](https://cloud.githubusercontent.com/assets/20145676/18692021/a52833d2-7f97-11e6-8018-d892a24edb0a.png)

**Comment by blydiet** [comment]
do you still need help with the code above?

**Comment by Annamazing** [comment]
No thank you x

**Comment by BGBatten** [comment]
I see an editing adjustment which would help to avoid confusion in Using Objects for Lookups.
The directions correctly instruct the user "... assign the associated string to the result variable."
However, Line 27 states the following and the result variable is on Line 28.
  // Only change code above this line
  return result;
}
Since it is necessary to alter Line 28 to run the code correctly, this is confusing. 
Just passing along an observation.

**Comment by pezz80** [comment]
Why is this not corrected. I almost start to cry trying to follow the  instructions in code

  // Only change code below this line

  // Only change code above this line

:D 


please help us learn

**Comment by astroaisha** [comment]
Heya, thanks for the help with this. I have a question regarding the layout of this challenge. What are the advantages of putting an object in a function? Could we not just return the requested property without the function?

**Comment by hamletv** [comment]
Agreed pezz80.
// Only change code below this line comment is limiting

**Comment by mtpjr88** [comment]
why is val in square braces? ie. 
                              
 return lookup[val];

**Comment by Romanek5** [comment]
I had a problem with it too, no instrustions for that ... : / 
yet return lookup[val]; worked , still a bit dunno how

**Comment by mtpjr88** [comment]
@Romanek5 I'm glad i'm not the only one!

**Comment by Romanek5** [comment]
@mtpjr88 :D next few are probably bugged too :). maybe created by same person ?

**Comment by has7eem** [comment]
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  
  var lookup = {
    "alpha":"Adams",
    "bravo":"Boston",
    "charlie":"Chicago",
    "delta":"Denver",
    "echo":"Easy",
    "foxtrot":"Frank"
  };

  // Only change code above this line
  result = lookup[val];
  return result;

}

// Change this value to test
phoneticLookup("charlie");

**Comment by tino2114** [comment]
This worked for me:

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
 var lookup = {
   "alpha":"Adams",
   "bravo":"Boston",
   "charlie":"Chicago",
   "delta":"Denver",
   "echo":"Easy",
   "foxtrot":"Frank",
   "":undefined
 };
  result = lookup[val];

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

**Comment by Shredattor** [comment]
Thanks for the explanation. It has helped a lot. Cheers,

**Comment by Snowcat8** [comment]
The instructions are a bit annoying and not very clear. Takes awhile to get those as we approach the problem.

**Comment by gelbelle** [comment]
Thank you! I NEVER would've gotten this. I'm working in beta too and it hasn't been changed.

**Comment by levulose** [comment]
this lesson makes zero sense

**Comment by parkhabit** [comment]
Thank you so much. I'm finding the wording of this section on objects far more confusing than it should be.

**Comment by avernoy** [comment]
I would have never thought to change the return line since it is below the
 " // Only change code above this line"

**Comment by ssharps711** [comment]
I was right! Yaaaaaaaaaaay!

**Comment by Qarthic** [comment]
THANK GOODNESS! Thank you!! Thought I was going crazy.
