### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue 

### ISSUE THREAD

**Issue by miguelc1221** [FreeCodeCamp/freecodecamp#666]
Please tell us in detail here how we can make this challenge better.
When using the <div class="row"> the mobile page has space on the right side, you can actually side scroll to the left. In order to fix this, you need to wrap <div class="row"> with a <div class="container">.
Every <div class="row"> must be inside a <div class="container"> in order to fix this issue. But fixing this issues causes other problems in the buttons. The words don't fit in the buttons.

**Comment by terakilobyte** [comment]
Thanks. This is a known side effect of using the iframe as we are. We'll look at improving mobile view in the future but it's not our priority now on coding challenges.
