### ISSUE TITLE
phoneticLookup("") returns undefined in the test, but it won't pass

### ISSUE THREAD

**Issue by thinkhuman** [FreeCodeCamp/FreeCodeCamp#6660]
Challenge [Using Objects for Lookups](http://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20lookup%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%20%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%20%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%20%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%20%22Frank%22%0A%20%20%7D%3B%0A%20%20result%20%2B%3D%20lookup%5Bval%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function phoneticLookup(val) {
  var result = "";
  // Only change code below this line
  var lookup = {
    "alpha": "Adams",
    "bravo": "Boston",
    "charlie":"Chicago",
    "delta":"Denver",
    "echo": "Easy",
    "foxtrot": "Frank"
  };
  result += lookup[val];
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("");

```

**Comment by HoBi** [comment]
The same for me. The test is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/fb83f96ea5cab4f9e43104183a081b609d1544b6/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3473).

Btw., if I add this line before return, it tells me everything is not undefined -> "false".

```js
console.log(result, typeof result === 'undefined');
```

```js
undefined false
undefined false
Adams false
Boston false
Chicago false
Denver false
Easy false
Frank false
undefined false
```

**Comment by ltegman** [comment]
This is not a test problem. If you need challenge help please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript). Thanks and happy coding!

**Comment by thinkhuman** [comment]
If the console in the problem returns "undefined", and the test still won't pass--because 'undefined' isn't being returned--then that's a problem with your FreeCodeCamp environment. I've also tested this code outside the FreeCodeCamp environment, and it works perfectly.

**Comment by ltegman** [comment]
By appending undefined to an empty string with your `result += lookup[val];` code you are implicitly type converting `undefined` to `'undefined'`, which is not the same thing.

**Comment by thinkhuman** [comment]
Nope, that's not what I'm seeing in the environment. But I've learned one thing: this will be the last FreeCodeCamp issue I attempt to file.

**Comment by jcmockbee** [comment]
I also misinterpreted I think and got undefined this way 
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  switch(val) {
    case "alpha": 
      result = "Adams";
      break;
    case "bravo": 
      result = "Boston";
      break;
    case "charlie": 
      result = "Chicago";
      break;
    case "delta": 
      result = "Denver";
      break;
    case "echo": 
      result = "Easy";
      break;
    case "foxtrot": 
      result = "Frank";
      break;
    case "":
      result = "undefined";
     
  }

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("");

**Comment by GonzandRobles** [comment]
Hi, I have a question, val inside ( ) means that is part of a function right?
What does it mean when you put val inside [ ] in the return statement.
Example:

lookup[val]

Thanks
