### ISSUE TITLE
Text Overlapping On Map Page

### ISSUE THREAD

**Issue by OriBon** [FreeCodeCamp/FreeCodeCamp#6661]
It appears that there is some overlapping of the module/section names over the estimated completion time. This does not happen on Chome when I tested it, only on Firefox Dev Edition and regular Firefox.
Common issue? Or my own browsers?

My dimensions are:
Browser window width:	1920
Browser window height:	905
Screen width:	1920
Screen height:	1080

![screenshot from 2016-02-01 16 42 14](https://cloud.githubusercontent.com/assets/10662057/12732460/ae49d934-c903-11e5-9234-7cfc6a35662a.png)

**Comment by SaintPeter** [comment]
@hallaathrad Can you please take a look at this one?

**Comment by hallaathrad** [comment]
The issue is that Lato is not being loaded... like on many other issues I've seen before, this is a common issue (for this and other fonts) while using some linux distros

**Comment by SaintPeter** [comment]
@hallaathrad 
Could we have a "safer" fallback font?

**Comment by hallaathrad** [comment]
This is worth some testing. The site is serving it's own ttf files.
Please see [#6679](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6679) serving woff2 files directly from google's font cdn and I'd have @OriBon test it, if he'd be so kind.

**Comment by OriBon** [comment]
@hallaathrad To test it do I just check beta? If so, it looks better on there.

![screenshot from 2016-02-02 17 00 17](https://cloud.githubusercontent.com/assets/10662057/12765886/bfd2972e-c9ce-11e5-8b3f-207fa7394514.png)

**Comment by hallaathrad** [comment]
Not quite, my friend. Beta is not showing the changes. Let me see if I can figure out a way for you to try it there.
I'll edit this comment on my progress.

**Comment by bugron** [comment]
Seems this issue is fixed. @OriBon thanks for posting.
