### ISSUE TITLE
Correct code and browser zoom on font size challenge, but unable to pass.

### ISSUE THREAD

**Issue by NothingLeft** [FreeCodeCamp/FreeCodeCamp#6664]
I am using Internet Explorer with zoom setting at 100%. Any help would be greatly appreciated. 
![font size code](https://cloud.githubusercontent.com/assets/16979105/12738671/7ecc0036-c928-11e5-8ec1-a2ffdc0dbb9f.PNG)

**Comment by SaintPeter** [comment]
Which version of IE?  Which operating system?

**Comment by alistermada** [comment]
@SaintPeter I notice that the test uses the `Number.parseInt()` method which [Internet Explorer does not support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt#Browser_compatibility). The built-in `parseInt()` function, however,  is [compatible in all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Browser_compatibility). I have no idea why :smile: .

**Comment by jlogan81** [comment]
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>


I'm running IE11 and am unable to get the last challenge to pass.  I verified that I am running my browser at 100% zoom...this is very frustrating. :(

**Comment by raisedadead** [comment]
@jlogan81 The fix is on its way, it will reach to the main website once the PR is merged shortly. :smiley:

**Comment by langzi2015** [comment]
I can't pass the test using fireforks with zoom setting at 100%

**Comment by Olwian** [comment]
Is there still an issue with Google Chrome? I can't get past the challenge.
