### ISSUE TITLE
Objective thinks an actual palindrome should return false?

### ISSUE THREAD

**Issue by Sajuuk51** [FreeCodeCamp/FreeCodeCamp#6666]
Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%2F*%0AObjective%20thinks%20a%20palindrome%20should%20return%20false%3F%0A%0AA%20palindrome%20is%20a%20word%20or%20sentence%20that's%20spelled%20the%20same%20way%20both%20forward%20and%20backward%2C%20ignoring%20punctuation%2C%20case%2C%20and%20spacing.%0A%0AYou'll%20need%20to%20remove%20all%20non-alphanumeric%20characters%20(punctuation%2C%20spaces%20and%20symbols)%20and%20turn%20everything%20lower%20case%20in%20order%20to%20check%20for%20palindromes.%0A%0AObjectives%3A%0A%22palindrome(%221%20eye%20for%20of%201%20eye.%22)%20should%20return%20false.%22%0A%0Aforwards%3A%20%20eyeforofeye%0Abackwards%3A%20eyeforofeye%0A%0AShouldn't%20this%20be%20true%3F%0A*%2F%0A%0Afunction%20palindrome(str)%20%7B%20%20%0A%20%20str%20%3D%20str.replace(%2F%5B0-9%5D%2Fg%2C%20%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5Cs%2Fg%2C%20%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5CW%2Fg%2C%20%22%22)%3B%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20var%20newArr%20%3D%20str.split(%22%22)%3B%0A%20%20newArr.reverse()%3B%0A%20%20var%20newStr%20%3D%20newArr.join(%22%22)%3B%0A%20%20%2F%2Fdebug%0A%20%20%2F%2Freturn%20newStr%3B%0A%20%0A%20%20if(newStr%20%3D%3D%20str)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20return%20false%3B%0A%7D%0A%0Apalindrome(%221%20eye%20for%20of%201%20eye.%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
/*
Objective thinks a palindrome should return false?

A palindrome is a word or sentence that's spelled the same way both forward and backward, ignoring punctuation, case, and spacing.

You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

Objectives:
"palindrome("1 eye for of 1 eye.") should return false."

forwards:  eyeforofeye
backwards: eyeforofeye

Shouldn't the objective require it to be true to pass?
*/

function palindrome(str) {  
  str = str.replace(/[0-9]/g, "");
  str = str.replace(/\s/g, "");
  str = str.replace(/\W/g, "");
  str = str.toLowerCase();
  var newArr = str.split("");
  newArr.reverse();
  var newStr = newArr.join("");
  //debug
  //return newStr;
 
  if(newStr == str) {
    return true;
  }
  return false;
}

palindrome("1 eye for of 1 eye.");

```

**Comment by sludge256** [comment]
Do not remove numbers.
>You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

**Comment by Sajuuk51** [comment]
Ahh, thanks.

**Comment by nickrobson** [comment]
Ironic that the issue with the palindromic ID of 6666 is asking about palindromes..
