### ISSUE TITLE
there is no way to go to the next " chalanges" it doesnt work for 2 days

### ISSUE THREAD

**Issue by iritu** [FreeCodeCamp/FreeCodeCamp#6668]
Challenge [Escape Sequences in Strings](http://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr; // Change this line

myStr = "\\ \t \t \r \n";

```

**Comment by AkiraLaine** [comment]
@iritu Your code works for me. So, I'm assuming this is the same problem as #6633.

Please take a screenshot of your ```console``` and ```network``` tabs (Chrome Dev Tools) and post them on the the above issue :smile:
