### ISSUE TITLE
Minor typo: Challenge http://www.freecodecamp.com/challenges/waypoint-responsively-style-a-radio-buttons has an issue 

### ISSUE THREAD

**Issue by nickbarry** [FreeCodeCamp/freecodecamp#667]
There's a minor, minor typo in the title of this waypoint: 
"Waypoint: Responsively Style a Radio Buttons"
should be 
"Waypoint: Responsively Style Radio Buttons"

**Comment by terakilobyte** [comment]
Thanks, commit 14ff6d5306d51637c1654d83bfb8589c8f7d8b31 addresses this
