### ISSUE TITLE
Error "404:We couldnt find path/_JailedSite.js"

### ISSUE THREAD

**Issue by tatidesigner** [FreeCodeCamp/FreeCodeCamp#6672]
This msg keep coming on the top of my course... Does anybody knows how to fix it?

https://dl.dropboxusercontent.com/u/74034301/img.jpg

**Comment by SaintPeter** [comment]
Where are you located?  Is there any chance that your ISP is injecting ads into your site?  Do you get any error messages in your browser console?

**Comment by bugron** [comment]
This seems a "random" connection error. Try following [this article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc).
Closing. Feel free to reopen if you still experience problems, thanks.
