### ISSUE TITLE
Bug with Factorialize a Number bonfire? 

### ISSUE THREAD

**Issue by minminimal** [FreeCodeCamp/FreeCodeCamp#6675]
Challenge [Factorialize a Number](http://www.freecodecamp.com/challenges/factorialize-a-number#?solution=function%20factorizeMe(num)%20%7B%0A%20%20%0A%20%20var%20myArray%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20var%20multiplyMe%20%3D%201%3B%0A%20%20%0A%20%20for(var%20i%20%3D%201%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%7B%0A%20%20%20multiplyMe%20*%3D%20myArray.push(i)%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2Fvar%20results%20%3D%20myArray.push%5Bi%5D%3B%0A%20%20%0A%20%20return%20multiplyMe%3B%20%20%20%0A%20%20%0A%7D%0A%20%20%0A%20%20factorizeMe(5)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function factorizeMe(num) {
  
  var myArray = [];
  
  var multiplyMe = 1;
  
  for(var i = 1; i <= num; i++){
   multiplyMe *= myArray.push(i);
  }
  
  //var results = myArray.push[i];
  
  return multiplyMe;   
  
}
  
  factorizeMe(5);
```

Returns correct results with the various use cases but i don't get any TICKS. help! :(

**Comment by raisedadead** [comment]
@minminimal  
Your logic is correct but you have renamed the original function name from `factorialize` to `factorizeMe`.

The test case look for a function called `factorialize` and hence fail. 

Rectify and retry. Goodluck!

Please ask your further queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by ltegman** [comment]
@raisedadead Is correct that you need to keep the original function name in order for the tests to properly called the function. Thanks and happy coding!

**Comment by mohannadsawalhi** [comment]
factorialize Not -> factorizeMe

**Comment by pandaxoom** [comment]
returns the correct results but doesn't give me the ticks. Why?
`var total = 1;
function factorialize(num) {
for (var x = 2; x <= num;x++) {
  total = total * x;
}
  
  num = total;
  
  return num;
}

factorialize(0);`

**Comment by ltegman** [comment]
@pandaxoom Global variables are bad. Think about what happens when you run that function twice.
