### ISSUE TITLE
unable to submit and move to next lesson.

### ISSUE THREAD

**Issue by Shumbasdad** [FreeCodeCamp/FreeCodeCamp#6676]
After "Use Hex Code for Specific Colors" when I submit the whole of FCC crashes on my computer. This has not happened before. If i refresh it will come back but as before unable to pass this point. Any ideas?

**Comment by sludge256** [comment]
Is it just stuck on the success pop up?
Are you using Chrome? If so please test it out with FireFox and report back.

**Comment by snow8261** [comment]
I have the same problem, I can not submit in chrome,but it is ok on firefox

**Comment by AkiraLaine** [comment]
Closing as this is the same issue as #6633
