### ISSUE TITLE
back end projects submitted in the past are still displayed as 'basejumps'

### ISSUE THREAD

**Issue by Em-Ant** [FreeCodeCamp/FreeCodeCamp#6677]
![screenshot - 02022016 - 16 06 12](https://cloud.githubusercontent.com/assets/12955734/12753526/cb5bd5da-c9c7-11e5-9674-14970089330e.png)

from my profile http://www.freecodecamp.com/em-ant

**Comment by SaintPeter** [comment]
I don't believe that we will fix these.  Consider it a badge of honor that you completed it before the change!  You're an old-timer now!

Thanks and Happy Coding!

**Comment by Em-Ant** [comment]
Ok! Thanks. I'm proud of it.
