### ISSUE TITLE
suggest online editor add comment support

### ISSUE THREAD

**Issue by fewspider** [FreeCodeCamp/FreeCodeCamp#6678]
`command + /` or `control + /` should be toggle code comment.
Thanks this awesome repo and people who work on it.

**Comment by NolanChan** [comment]
Looking into this

**Comment by gangachris** [comment]
@NolanChan are you still working on this? I'd like to work on it

**Comment by gangachris** [comment]
@bugron There seems to be no reply. I think I'll work on this.
