### ISSUE TITLE
Using live-filter to hide completed challenges

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#6680]
Typing 'incomplete' in our new live-filter should be able to only show these, and hide the already completed challenges. And the same for 'completed'...

 Anyone?

**Comment by hellawindy** [comment]
there were a button to do this. i don't why they removed! i think your suggestion would be a good alternative

**Comment by hallaathrad** [comment]
We removed it because we didn't see it as a relevant feature worth having it's own separate button... but I do think we can possibly integrate it in the filter, as it won't take any additional space.

**Comment by alistermada** [comment]
So basically something like this but live and without the filter buttons?
![image](https://cloud.githubusercontent.com/assets/12993334/12768419/21846240-ca42-11e5-900c-1f5fa6d476ec.png)

GitHub makes it fairly clear how to use their text-based filters by making "is: issue is:open" the default when you open the issue tab. Should we have something like "is: incomplete" be the default setting when users click on the map?

I'm not sure how else to inform users that they can type "complete" or "incomplete" that wouldn't take up space (which would defeat the purpose of removing the filter button).

**Comment by Recursivepaiste** [comment]
Perhaps using a tooltip or something similar when a user hovers over the search bar would be useful? A clean and fairly unobtrusive way of informing the user.

**Comment by SaintPeter** [comment]
I could see updating the placeholder text to something like:
> Type a challenge name or complete/incomplete

I just worry that it would be longer than the text box on some screens.

**Comment by alistermada** [comment]
@SaintPeter That's already too big for the text box even on a large screen. Looks like the text box has a fixed width of 260px.

![image](https://cloud.githubusercontent.com/assets/12993334/12815006/f434f522-cb75-11e5-9e7b-18b1fcede384.png)

**Comment by juggernate** [comment]
I think the hide completed button was far more useful than the type in filter. I don't know the names of many of the challenges so typing for them isn't so helpful, but I do want to quickly filter out the things I've already completed.

**Comment by SaintPeter** [comment]
I think we've come up with a possible solution.  We'll use a "drop down" filter button like the GitHub Interface, but rather than a menu it will have checkboxes that appear below the search box for completed/incomplete/required/whatever.  Then you can have both a filter and search within it.

**Comment by geoff616** [comment]
Took a shot at implementing these with a dropdown. Interested to hear if you think this makes sense.
