### ISSUE TITLE
The "Go to next challenge" button doesnt load the next challenge

### ISSUE THREAD

**Issue by samoguche** [FreeCodeCamp/FreeCodeCamp#6685]
After rounding up the first phase of the basic html, it doesnt load the next challenge.

**Comment by raisedadead** [comment]
@samoguche Is this a possible duplicate of #6633 ? If yes, Do you mind closing this issue and continue the discussion there, with screenshots of the error?

Thanks.

**Comment by AkiraLaine** [comment]
@samoguche Are you using Chrome? If yes, please us FireFox and tell us if that solved the issue.

**Comment by bugron** [comment]
Hopefully, this is fixed not. @samoguche thanks for posting. Closing this issue. Feel free to reopen if you still experience problems, thanks.
