### ISSUE TITLE
`If` statements don't work when put together as `if else` but work individually

### ISSUE THREAD

**Issue by krowlaicos** [FreeCodeCamp/FreeCodeCamp#6688]
Challenge [Profile Lookup](http://www.freecodecamp.com/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUp(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%0A%20%20%0Afor%20(i%20%3D%200%3B%20i%20%3C%20contacts.length%3B%20i%2B%2B)%20%7B%0A%20%20if%20(contacts%5Bi%5D.firstName%20%3D%3D%3D%20firstName%20%26%26%20contacts%5Bi%5D.hasOwnProperty(prop))%20%7B%0A%20%20%20%20return%20contacts%5Bi%5D%5Bprop%5D%3B%0A%20%20%7D%20else%20if%20(contacts%5Bi%5D.firstName%20!%3D%3D%20firstName)%20%7B%0A%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%7D%20else%20if%20(contacts%5Bi%5D.prop%20!%3D%3D%20prop)%20%7B%0A%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%7D%0A%7D%0A%20%20%0A%20%20%0A%2F%2F%20Only%20change%20code%20above%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp(%22Akira%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUp(firstName, prop){
// Only change code below this line


  
for (i = 0; i < contacts.length; i++) {
  if (contacts[i].firstName === firstName && contacts[i].hasOwnProperty(prop)) {
    return contacts[i][prop];
  } else if (contacts[i].firstName !== firstName) {
    return "No such contact";
  } else if (contacts[i].prop !== prop) {
    return "No such property";
  }
}
  
  
// Only change code above
}

// Change these values to test your function
lookUp("Akira", "likes");

```

Each individual `if` statement works but they don't work together when using an `if else` statement.  Not sure why that is the case.

**Comment by alistermada** [comment]
Your `for` loop doesn't check past the first contact object in the `contacts` array because your `lookUp()` function is returned before the loop goes to the next iteration. 

For example, when looking for the contact with the `firstName` of "Kristian", your function checks the first contact to see if its `firstName` is equal to "Kristian" and then returns "No such contact" if it isn't before checking the other contacts.

If you need help on the challenges, please check out the [Help Chat](https://gitter.im/FreeCodeCamp/Help) first as GitHub issues are mainly for reporting bugs. You'll likely get a faster response there.

**Comment by sludge256** [comment]
Please use the help chat. Thanks!
