### ISSUE TITLE
I think  syntax is wrong

### ISSUE THREAD

**Issue by mitoba** [FreeCodeCamp/FreeCodeCamp#6689]
Challenge [Accessing Nested Arrays in JSON](http://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json#?solution=%2F%2F%20Setup%0Avar%20myPlants%20%3D%20%5B%0A%20%20%22flowers%22%3A%20%5B%0A%20%20%20%20%20%20%22rose%22%2C%0A%20%20%20%20%20%20%22tulip%22%2C%0A%20%20%20%20%20%20%22dandelion%22%0A%20%20%20%20%5D%2C%0A%20%0A%20%0A%20%20%20%22trees%22%3A%20%5B%0A%20%20%20%20%20%20%22fir%22%2C%0A%20%20%20%20%20%20%22pine%22%2C%0A%20%20%20%20%20%20%22birch%22%0A%20%20%20%20%5D%0A%20%20%0A%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20secondTree%20%3D%20myPlants.trees.%5B1%5D%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:40.0) Gecko/20100101 Firefox/40.1.0 Waterfox/40.1.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myPlants = [
  "flowers": [
      "rose",
      "tulip",
      "dandelion"
    ],
 
 
   "trees": [
      "fir",
      "pine",
      "birch"
    ]
  
];

// Only change code below this line

var secondTree = myPlants.trees.[1]; // Change this line


```

**Comment by ltegman** [comment]
The original seed code for this challenge is fine. If you need to get back to it you can use the reset button on the side. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need further assistance. Thanks and happy coding!
