### ISSUE TITLE
Store solutions of the same bonfire in a drop-down or similar.

### ISSUE THREAD

**Issue by LumenTeun** [FreeCodeCamp/freecodecamp#669]
As of now, all solutions to bonfires are saved to your profile instead of just the most recent one, which is great; it does, however, clutter up your profile, especially if you play around in the same bonfire a lot, adding stuff and testing it over and over. Could solutions to the same bonfire be stored in some sort of openable menu, so that each bonfire only appears on your profile once? Maybe the solutions part of the profile could look like the Map page and clicking the bonfire would show the solutions?

**Comment by terakilobyte** [comment]
Thanks for the suggestion, this is already mentioned in issue #356. Closing as a duplicate. Please comment in that issue's thread.
