### ISSUE TITLE
Generate Random Whole Numbers with JavaScript: Instructions and test case do not match

### ISSUE THREAD

**Issue by ScottBrenner** [FreeCodeCamp/FreeCodeCamp#6692]
Challenge [Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript#?solution=var%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20Math.floor(10*Math.random())%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.

The instructions say 

> Multiply that random decimal by **20**. 

But the test case says

> You should have multiplied the result of Math.random by **10** to make it a number that is between zero and nine

**Comment by SaintPeter** [comment]
>### Instructions
Use this technique to generate and return a random whole number between 0 and 9.

The `20` is for the example code.

**Comment by SaintPeter** [comment]
Closing as not an issue.  Thanks and Happy Coding!

**Comment by dcofjapan** [comment]
this is still an issue

**Comment by vaspv** [comment]
I worked around it by changing the top line to 10
