### ISSUE TITLE
Stand in Line

### ISSUE THREAD

**Issue by Peajaycodes78** [FreeCodeCamp/FreeCodeCamp#6693]
Challenge [Stand in Line](http://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20queue(arr%2C%20item)%20%7B%0A%20queue%20(%5B2%5D%2C%201)%3B%20%2F%2F%20Your%20code%20here%0A%20%20%0A%20%20return%20item%20(arr)%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item) {
 queue ([2], 1); // Your code here
  
  return item (arr);  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by AkiraLaine** [comment]
Hey @Peajaycodes78! Please visit our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [help](https://gitter.im/FreeCodeCamp/Help) room if you need help.

GitHub is for issues only.

**Comment by Hmay61** [comment]
Here is my answer
function nextInLine(arr, item) {
  // Your code here
  arr.push(item);      //add an new item
  var firstItem = arr.shift(arr);   //remove the first item
  return firstItem;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 7)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

**Comment by BEBEDYDY** [comment]
what means JSON.stringify(testArr) ???
I don't get it , anyone know? please help. Thank you so much.

**Comment by Hmay61** [comment]
Hi Jie，

I think JSON.stringify is just a method that convert JS value to JSON
format.
Because JSON format is much more efficient in data transmission.


Yue He

2016-07-28 15:45 GMT-04:00 Jie <notifications@github.com>:

**Comment by BEBEDYDY** [comment]
Hi , Hmay61 ,
Thank you for your help. I also googled it yesterday. :)

Jie
