### ISSUE TITLE
Javascript execution error: TypeError: cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gititGoro** [FreeCodeCamp/FreeCodeCamp#6694]
I've ensured that the code I wrote runs perfectly on codepen. When I first copied it into the freecodecamp window and ran it, it couldn't understand the toLowerCase() string function. So I wrote my own. Then it gave the error in the title.
![bug](https://cloud.githubusercontent.com/assets/12531162/12774655/a26bf000-ca4f-11e5-8f3e-2780e780bb66.PNG)

Original code pen just to illustrate that it works:
http://codepen.io/gititGoro/pen/wMxYQg

**Comment by ltegman** [comment]
Please provide us with a copy of the exact code you're trying to submit on Free Code Camp. I can't debug something on our website with a codepen link.

**Comment by augmt** [comment]
@gititGoro Your Codepen code (the `getCapitalizationVector` function to be specific) runs into an error when the `before` string is longer than the `after` string, as is the case with the first two tests in the Search and Replace challenge.

**Comment by gititGoro** [comment]
Thank you. My bad. Sorry for wasting your time.
