### ISSUE TITLE
Where does FCC store user data?

### ISSUE THREAD

**Issue by snow8261** [FreeCodeCamp/FreeCodeCamp#6696]
Where does FCC store user data? Does it store in the local storage in user's pc or store in the fcc server? I switch from Chrome to firefox,but i found that I can not view my solved exercise in firefox?

**Comment by jbmartinez** [comment]
Look at your profile, you'll find a list containing all your solutions

**Comment by ltegman** [comment]
It stores them in localStorage for retrieval when visiting a challenge from the map and stores them in the DB to be accessed from your profile. Thanks and happy coding!

**Comment by BerkeleyTrue** [comment]
To clarify. We store all user data in the database, but we do not store in-progress challenges only submitted solutions. These are stored in localStorage in your browser. 

Happy Coding!

**Comment by Lewiscowles1986** [comment]
Has it always been this way? I've for example got points on my profile, but the challenges I completed to earn them have lost their status on the map, which seems a little strange.

**Comment by BerkeleyTrue** [comment]
Did you recently return after a hiatus?

**Comment by Lewiscowles1986** [comment]
yeah about 3 months

**Comment by BerkeleyTrue** [comment]
@Lewiscowles1986 I've send you a message on gitter
