### ISSUE TITLE
Streak is still broken

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6697]
Current Streak number seems flakey at best. It's supposed to have a 36 hour grace period since the most recent brownie point before it resets the streak, but that doesn't seem to be working.
![](https://www.evernote.com/l/AqQ3XyvQUF1Alr02lQqi39Wp4zlS-4LBLnsB/image.png)

**Comment by brutalcrozt** [comment]
any clue?

**Comment by AkiraLaine** [comment]
I have a 0 streak, even though my heat map is pretty filled.

**Comment by SaintPeter** [comment]
I have seen mine start at 0, but as soon as I complete a challenge or otherwise get a point it resets to my current streak.

**Comment by BerkeleyTrue** [comment]
closing in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6721
