### ISSUE TITLE
There is no code to uncomment

### ISSUE THREAD

**Issue by smpvst736** [FreeCodeCamp/FreeCodeCamp#6698]
It says to uncomment code but there is no code to uncomment.

**Comment by AkiraLaine** [comment]
Can you try clearing cache and cookies, then resetting your code? 
If that doesn't work please post a screenshot with your console open (if there are any errors).

**Comment by smpvst736** [comment]
I looked at it again and the code was just very light and hard to see but I
was able to see it and answer the question.  Thank you.
On Feb 3, 2016 7:10 AM, "Akira Laine" <notifications@github.com> wrote:
>
> Can you try clearing cache and cookies, then resetting your code?
> If that doesn't work please post a screenshot with your console open (if
there are any errors).

**Comment by ltegman** [comment]
Closing as resolved.
