### ISSUE TITLE
Map is blank in Safari 8.0.8 

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6699]
![](https://www.evernote.com/l/AqQQYulRD99Btps2JPAHudAfzs4SuGYw8-EB/image.png)

**Comment by bugron** [comment]
@QuincyLarson any errors in browser's console? Is everything OK on Networks tab?

**Comment by bugron** [comment]
Thanks for posting. Closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6256.
