### ISSUE TITLE
FORUM Login infinite loop

### ISSUE THREAD

**Issue by uptownhr** [FreeCodeCamp/freecodecamp#67]
My first time at the forum for freecodecamp following step #2. Instead of using the 'signup', I decided to use 'login' and I was redirected to github for authentication. This part was fine but after being redirected back to freecodecamp, a new window infinitely opened and closed. I had to force close, refresh and use the 'signup'.

**Comment by QuincyLarson** [comment]
I believe this is a problem with Discourse itself, and not with our implementation of Discourse. I'm going to close this ticket and we'll upgrade Discourse in the next week or two.
