### ISSUE TITLE
The browser is not accepting my code blue.

### ISSUE THREAD

**Issue by smpvst736** [FreeCodeCamp/FreeCodeCamp#6700]
Challenge [Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%20%20%0A%20%20%3ECatPhotoApp%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>  
  >CatPhotoApp

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by smpvst736** [comment]
I mean it is not accepting: 
<style>
    h2 {color: red;}
</style>
\
red.  The exercise says to change h2 to red and it is not working.

**Comment by smpvst736** [comment]
I am sorry.  I just looked at the exercise again.  It says to change h2 to blue and it is not accepting blue.
The code is:

<style>
     h2{color: blue}
</style>
and this is not working.

**Comment by nagashreekumar** [comment]
U can try this 
<html>
<style>
p{
color:blue;}
</style>
<p> this is an example</p>
</html>

**Comment by ltegman** [comment]
Your code doesn't have an h2 element for your style to apply to. You can reset the seed code to get this element back. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm what you're seeing is actually a site bug. Thanks and happy coding!
