### ISSUE TITLE
Object Oriented JavaScript - Confusing code exercise descriptions

### ISSUE THREAD

**Issue by simondiep** [FreeCodeCamp/FreeCodeCamp#6701]
There are two exercises dealing with JavaScript array functions that don't change the original array (.map and .filter).  It is very confusing to a learner whether to modify the existing array or to assign the results to a separate array.  Here's a snippet from http://www.freecodecamp.com/challenges/iterate-over-arrays-with-map

`Use the map function to add 3 to every value in the variable oldArray.`

```
var oldArray = [1,2,3,4,5];
var newArray = [];

// Only change code below this line.

newArray = oldArray;
```

The test assertions are all on `newArray`, meaning it doesn't matter if `oldArray` was changed at all.

I have two suggestions, either of which should make these exercises less confusing:

- Remove all references of `newArray` and make the test assertions on `oldArray`

or

- Reword the goal statement to : `Use the map function to add 3 to every value in the variable oldArray, and save the results into variable newArray.  oldArray should not change.`
- Update the starter code to :
```
var oldArray = [1,2,3,4,5];
// Only change code below this line.

var newArray = oldArray;
```

This concept would apply to both:
http://www.freecodecamp.com/challenges/iterate-over-arrays-with-map
http://www.freecodecamp.com/challenges/filter-arrays-with-filter

**Comment by ltegman** [comment]
I like suggestion number two :+1:
