### ISSUE TITLE
Can't add LinkedIn to my profile

### ISSUE THREAD

**Issue by tech4david** [FreeCodeCamp/FreeCodeCamp#6705]
I've got an account on your site and I've successfully added GitHub, Twitter and G+ to my profile, but when I try to add LinkedIn, nothing happens once I've logged in and authorized Free Code Camp. The problem seems to be on your side as the dialog closes after attempting to authorize and when the button is clicked in the future no dialog box pops up as it's already been authorised.

**Comment by SaintPeter** [comment]
I think I've confirmed this.

Did you get a message like: 
![image](https://cloud.githubusercontent.com/assets/553494/12800136/c26d29cc-ca87-11e5-8833-8b7d1073c39a.png)

**Comment by tech4david** [comment]
I didn't get any error at all; it just didn't successfully add it to my profile.

**Comment by BuKinoshita** [comment]
Just tested here, everything worked just fine.

**Comment by tech4david** [comment]
hmm, are you sure it was added to your profile? For me it appears to work at first but it's not actually displayed on the portfolio and the "display LinkedIn on my portfolio" button is still shown - although no error is given. I've tried deauthorizing Free Code Camp and signing in again with LinkedIn but it still won't add to my profile.

**Comment by BuKinoshita** [comment]
![screenshot 2016-02-05 10 02 48](https://cloud.githubusercontent.com/assets/6929565/12849830/acfe1cea-cbef-11e5-89a9-ae3cd0306d86.png)

**Comment by tech4david** [comment]
Still not working for me, do many other people have this issue?

**Comment by thejonathangraham** [comment]
I think it's just you man...

**Comment by bugron** [comment]
@tech4david @SaintPeter any updates on this issue?

**Comment by tech4david** [comment]
Nothing new, still doesn't work for me

**Comment by aaronraimist** [comment]
I am having a somewhat similar problem. The button to "Add my LinkedIn to my portfolio" never goes away for me but I can log in with LinkedIn fine. This seems to suggest it has been added but the logic that determines if the button should be displayed is incorrect.

**Comment by tech4david** [comment]
Yep, that's the problem I'm having. it logs in and authenticates, but the button doesn't go away and the link to my LinkedIn page isn't added to my profile.

**Comment by techtolentino** [comment]
Interesting, I _was able to add_ my LinkedIn account and the button did go away.

<img width="181" alt="fcc_linkedin_added" src="https://cloud.githubusercontent.com/assets/6276074/13283334/e36f3aa8-dab2-11e5-8a1c-de51055329ca.png">

**Comment by Kaos95** [comment]
I have just tried to sign in with linked in a couple times. But I could not even sign in? I keep getting the  'opps something went wrong. Please try again later' message?

**Comment by tech4david** [comment]
Looks like there is definitely some issue seeing as there are at least 3 different results of trying to link at the moment

**Comment by QuincyLarson** [comment]
I suspect this is being caused by the huge amount of duplicate accounts people have accidentally created due to us having too many authentication options. These issues should go away in the near future (we've already removed adding your G+ and Facebook profiles to your FCC account). If anyone has an issue with this email team at freecodecamp com and I'll sort it out for you manually in the database.

**Comment by HasanSakr** [comment]
my linkedin account can't be added to my profile
any help?
