### ISSUE TITLE
Brazilian Portuguese translation of Gear up for Success

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6710]
- [x] Reference our Wiki
- [x]  Join our LinkedIn Alumni Network
- [x]  Join our Subreddit
- [x]  Read Coding News on our Medium Publication
- [x]  Watch us Code Live on Twitch.tv
- [x]  Commit to a Goal and a Nonprofit

**Comment by christophermoura** [comment]
Working on it.

**Comment by christophermoura** [comment]
Status:

- [x] Reference our Wiki
- [x] Join our LinkedIn Alumni Network
- [x] Join our Subreddit
- [x] Read Coding News on our Medium Publication
- [x] Watch us Code Live on Twitch.tv
- [x] Commit to a Goal and a Nonprofit

Waiting the [PR](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7097) to be accepted...

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/48, please continue discussion there, also I noticed the pull request for this was closed as stale, hence I have updated the opening post on the new issue to reflect no competion.
