### ISSUE TITLE
Brazilian Portuguese translation of Basic JavaScript  

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6712]
- [ ] Comment your JavaScript Code
- [ ] Declare JavaScript Variables
- [ ] Storing Values with the Equal Operator
- [ ] Initializing Variables with the Equal Operator
- [ ] Understanding Uninitialized Variables
- [ ] Understanding Case Sensitivity in Variables
- [ ] Add Two Numbers with JavaScript
- [ ] Subtract One Number from Another with JavaScript
- [ ] Multiply Two Numbers with JavaScript
- [ ] Divide One Number by Another with JavaScript
- [ ] Increment a Number with Javascript
- [ ] Decrement a Number with Javascript   
- [ ] Create Decimal Numbers with JavaScript
- [ ] Multiply Two Decimals with JavaScript
- [ ] Divide one Decimal by Another with JavaScript
- [ ] Finding a Remainder in Javascript
- [ ] Assignment with Plus Equals
- [ ] Assignment with Minus Equals 
- [ ] Assignment with Times Equals   
- [ ] Assignment with Divided by Equals
- [ ] Convert Celsius to Fahrenheit
- [ ] Declare String Variables
- [ ] Escaping Literal Quotes in Strings
- [ ] Quoting Strings with Single Quotes
- [ ] Escape Sequences in Strings
- [ ] Concatenating Strings with Plus Operator
- [ ] Concatenating Strings with the Plus Equals Operator
- [ ] Constructing Strings with Variables
- [ ] Appending Variables to Strings
- [ ] Find the Length of a String
- [ ] Use Bracket Notation to Find the First Character in a String
- [ ] Understand String Immutability
- [ ] Use Bracket Notation to Find the Nth Character in a String
- [ ] Use Bracket Notation to Find the Last Character in a String
- [ ] Use Bracket Notation to Find the Nth-to-Last Character in a String
- [ ] Word Blanks
- [ ] Store Multiple Values in one Variable using JavaScript Arrays
- [ ] Nest one Array within Another Array
- [ ] Access Array Data with Indexes
- [ ] Modify Array Data With Indexes
- [ ] Access Multi-Dimensional Arrays With Indexes
- [ ] Manipulate Arrays With push()
- [ ] Manipulate Arrays With pop()
- [ ] Manipulate Arrays With shift()
- [ ] Manipulate Arrays With unshift()
- [ ] Shopping List
- [ ] Write Reusable JavaScript with Functions
- [ ] Passing Values to Functions with Arguments   
- [ ] Global Scope and Functions
- [ ] Local Scope and Functions
- [ ] Global vs. Local Scope in Functions   
- [ ] Return a Value from a Function with Return   
- [ ] Assignment with a Returned Value
- [ ] Stand in Line
- [ ] Understanding Boolean Values
- [ ] Use Conditional Logic with If Statements
- [ ] Comparison with the Equality Operator
- [ ] Comparison with the Strict Equality Operator   
- [ ] Comparison with the Inequality Operator
- [ ] Comparison with the Strict Inequality Operator
- [ ] Comparison with the Greater Than Operator   
- [ ] Comparison with the Greater Than Or Equal To Operator
- [ ] Comparison with the Less Than Operator
- [ ] Comparison with the Less Than Or Equal To Operator
- [ ] Comparisons with the Logical And Operator
- [ ] Comparisons with the Logical Or Operator
- [ ] Introducing Else Statements
- [ ] Introducing Else If Statements   
- [ ] Logical Order in If Else Statements
- [ ] Chaining If Else Statements
- [ ] Golf Code
- [ ] Selecting from many options with Switch Statements
- [ ] Adding a default option in Switch statements
- [ ] Multiple Identical Options in Switch Statements   
- [ ] Replacing If Else Chains with Switch
- [ ] Returning Boolean Values from Functions
- [ ] Return Early Pattern for Functions
- [ ] Counting Cards
- [ ] Build JavaScript Objects
- [ ] Accessing Objects Properties with the Dot Operator
- [ ] Accessing Objects Properties with Bracket Notation   
- [ ] Accessing Objects Properties with Variables
- [ ] Updating Object Properties
- [ ] Add Properties to a JavaScript Object
- [ ] Delete Properties from a JavaScript Object
- [ ] Using Objects for Lookups
- [ ] Testing Objects for Properties
- [ ] Introducing JavaScript Object Notation (JSON)
- [ ] Accessing Nested Objects in JSON
- [ ] Accessing Nested Arrays in JSON
- [ ] Record Collection
- [ ] Iterate with JavaScript For Loops
- [ ] Iterate Odd Numbers With a For Loop
- [ ] Count Backwards With a For Loop
- [ ] Iterate Through an Array with a For Loop
- [ ] Nesting For Loops
- [ ] Iterate with JavaScript While Loops
- [ ] Profile Lookup
- [ ] Generate Random Fractions with JavaScript
- [ ] Generate Random Whole Numbers with JavaScript
- [ ] Generate Random Whole Numbers within a Range
- [ ] Sift through Text with Regular Expressions
- [ ] Find Numbers with Regular Expressions
- [ ] Find Whitespace with Regular Expressions
- [ ] Invert Regular Expression Matches with JavaScript

**Comment by fredericksilva** [comment]
working on it

**Comment by BrunoFDeveloper** [comment]
+1

**Comment by rafaeldevops** [comment]
how can i help with the Brazilian Portuguese translation?

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/50, please continue the discussion on that thread.
