### ISSUE TITLE
Brazilian Portuguese translation of Object Oriented and Functional Programming 

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6713]
- [ ]  Declare JavaScript Objects as Variables
- [ ]  Construct JavaScript Objects with Functions
- [ ]  Make Instances of Objects with a Constructor Function
- [ ]  Make Unique Objects by Passing Parameters to our Constructor
- [ ]  Make Object Properties Private
- [ ]  Iterate over Arrays with .map
- [ ]  Condense arrays with .reduce
- [ ]  Filter Arrays with .filter
- [ ]  Sort Arrays with .sort
- [ ]  Reverse Arrays with .reverse
- [ ]  Concatenate Arrays with .concat
- [ ]  Split Strings with .split
- [ ]  Join Strings with .join

**Comment by danielfsousa** [comment]
Working on it

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/44, @Janainaf @danielfsousa please continue discussions and collaborations there.
