### ISSUE TITLE
Brazilian Portuguese translation of Basic Algorithm Scripting

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6714]
- [ ] Get Set for our Algorithm Challenges
- [ ]  Reverse a String
- [ ]  Factorialize a Number
- [ ]  Check for Palindromes
- [ ]  Find the Longest Word in a String
- [ ]  Title Case a Sentence
- [ ]  Return Largest Numbers in Arrays
- [ ]  Confirm the Ending
- [ ]  Repeat a string repeat a string
- [ ]  Truncate a string
- [ ]  Chunky Monkey
- [ ]  Slasher Flick
- [ ]  Mutations
- [ ]  Falsy Bouncer
- [ ]  Seek and Destroy
- [ ]  Where do I belong
- [ ] Caesar's Cipher

**Comment by christophermoura** [comment]
Working on it!

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/51
