### ISSUE TITLE
Brazilian Portuguese translation of Basic Front End Development Projects

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6715]
- [x] Get Set for our Front End Development Projects
- [ ]  Build a Personal Portfolio Webpage
- [ ]  Build a Random Quote Machine
- [ ]  Build a JavaScript Calculator
- [ ]  Build a Pomodoro Clock

**Comment by Janainaf** [comment]
Working on it!

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/43, please continue discussion there.
