### ISSUE TITLE
Brazilian Portuguese translation of JSON APIs and Ajax

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6717]
- [ ] Trigger Click Events with jQuery
- [ ]  Change Text with Click Events
- [ ]  Get JSON with the jQuery getJSON Method
- [ ]  Convert JSON Data to HTML
- [ ]  Render Images from Data Sources
- [ ]  Prefilter JSON
- [ ]  Get Geo-location Data

**Comment by MatheusGodinho** [comment]
Working on it!
