### ISSUE TITLE
Brazilian Portuguese translation of Intermediate Front End Development Projects

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6718]
- [ ] Show the Local Weather
- [ ]  Stylize Stories on Camper s
- [ ]  Build a Wikipedia Viewer
- [ ] Use the Twitch.tv JSON API
- [ ]  Build a Tic Tac Toe Game
- [ ]  Build a Simon Game

**Comment by MrHormonas** [comment]
i can work on this

**Comment by danilobarion1986** [comment]
I Can help with this too. How do I proceed?

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/53, please continue discussion there.
