### ISSUE TITLE
Brazilian Portuguese translation of Advanced Algorithm Scripting 

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6719]
- [ ] Validate US Telephone Numbers
- [ ]  Symmetric Difference
- [ ]  Exact Change
- [ ]  Inventory Update
- [ ]  No repeats please
- [ ]  Friendly Date Ranges
- [ ] Make a Person
- [ ] Map the Debris
- [ ] Pairwise

**Comment by kevao012** [comment]
Working on it.

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/54
