### ISSUE TITLE
Brazilian Portuguese translation of Claim Your Front End Development Certificate 

### ISSUE THREAD

**Issue by Janainaf** [FreeCodeCamp/FreeCodeCamp#6720]
- [ ] Claim Your Front End Development Certificate

**Comment by Ronaiza** [comment]
work on it!

**Comment by Ronaiza** [comment]
finish

**Comment by raisedadead** [comment]
Closed in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/45, @Janainaf @yesroh please continue discussion there, on that note is this already complete?
