### ISSUE TITLE
Steak is broken though challenges were completed everyday

### ISSUE THREAD

**Issue by LenaBarinova** [FreeCodeCamp/FreeCodeCamp#6721]
This issue was originally reported by @thebgar.

The problem happens when the difference between two dates is bigger than 36 hours, but these dates still fall into two consecutive days.
<img width="932" alt="screen shot 2016-02-03 at 2 56 42 pm" src="https://cloud.githubusercontent.com/assets/2317409/12799925/7bd6cda2-ca86-11e5-9db8-70bb796edd9c.png">

The dates are such:
1. 2016-02-02T04:12:43
2. 2016-02-01T05:32:25
3. 2016-01-31T18:34:15
4. 2016-01-30T17:27:53
5. 2016-01-29T04:15:04
6. 2016-01-28T05:42:50
...

It's obvious, that student has worked everyday (starting from Jan 15 till Feb 2), but when streak is calculated it considers a break between dates 4 and 5. Because in this case the difference between two dates is 1.55 days, which is more than declared constant 1.5.

I want to create this issue as a separate one, since it's not timezone related issue.
Right now I'm fixing this issue and also adding new tests to cover this particular use case.

**Comment by SaintPeter** [comment]
While you're looking at this, can you also look into the "Current Streak 0 days" before a point has been awarded for the current day?  Or is that a related issue?

Is the solution to consider a break of < 48 hours to be inclusive.  I guess someone could technically have completed a challenge at 12:01am on one day and then 11:59pm on the next day and still technically have had two contiguous dates, right? That would be 47:58 difference, I guess.

**Comment by LenaBarinova** [comment]
@SaintPeter I think "Current Streak 0 " might be related to this.

Yeah, I think it's not about the length of the break, but more about was it everyday activity or not. So I'll try to standardize all the dates and then see if work was happening everyday.

**Comment by BerkeleyTrue** [comment]
@LenaBarinova Thanks for tracking down the reason for this issue.

**Comment by rishipuri** [comment]
Noticed this same issue today. Any updates?

**Comment by LenaBarinova** [comment]
@rishipuri, I'm working on it, have it fixed now, but need to do more unit tests. I think I'll create a pull request next week.

**Comment by TheBGar** [comment]
@LenaBarinova greatly appreciate all the hard work on this! Just wish I could help :smiley:

**Comment by URobert** [comment]
HI. I seem to have an issue with the streak calculation too.
I basically did complete challenges/helped out people everyday but I have a discontinuity on Feb 5th when I should not. My calendar shows activity everyday however my streak was broken (and a member sent me print-screen where he sees the gap in the calendar when checking my profile page, although there is no such thing then I check it).

Thanks !

Here is my profile: http://www.freecodecamp.com/urobert

**Comment by LenaBarinova** [comment]
@URobert Thanks for reporting it! The more broken cases we have - the better we can test.
I've fixed this issues and created a pull request. So as soon as it passes ```Beta``` testing - it will go live.
