### ISSUE TITLE
function passes test but fails in my console if logging instead of return; why?

### ISSUE THREAD

**Issue by SteveRaskin** [FreeCodeCamp/FreeCodeCamp#6723]
Challenge [Profile Lookup](http://www.freecodecamp.com/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%2F*%0Afunction%20lookUp(firstName%2C%20prop)%7B%0A%20%20for%20(var%20i%3D0%3B%20i%3Ccontacts.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if%20(firstName%20%3D%3D%3D%20contacts%5Bi%5D.firstName%20%26%26%20contacts%5Bi%5D.hasOwnProperty(prop))%7B%0A%20%20%20%20%20%20return%20contacts%5Bi%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if%20(firstName%20!%3D%3D%20contacts%5Bi%5D.firstName)%7B%0A%20%20%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if%20(!contacts%5Bi%5D%5Bprop%5D.hasOwnProperty)%7B%0A%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A*%2F%0A%0A%0A%0Afunction%20lookUp(firstName%2C%20prop)%20%7B%0A%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20contacts.length%3B%20i%2B%2B)%20%7B%0A%0A%20%20%20%20if%20(firstName%20%3D%3D%20contacts%5Bi%5D.firstName)%20%7B%0A%20%20%20%20%20%20%20%20if%20(contacts%5Bi%5D.hasOwnProperty(prop))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20contacts%5Bi%5D%5Bprop%5D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20return%20%22No%20such%20contact%22%3B%0A%7D%0A%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp(%22Kristian%22%2C%20%22likes%22)%3B%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

function lookUp(firstName, prop) {
  for (var i = 0; i < contacts.length; i++) {
    if (firstName == contacts[i].firstName) {
        if (contacts[i].hasOwnProperty(prop)) {
            return contacts[i][prop];
        }
        else {
          return "No such property";
        }
      }
    }
  return "No such contact";
}








```

**Comment by SaintPeter** [comment]
The reason that it would fail if you're using `console.log` is because `console.log` does not stop the flow of the program.  `return` exits the function immediately and returns a single value. 

Also, maybe more importantly, the code which checks your code is expecting a return value.  Without it it can't do anything.  It's basically checking to see what your function `lookUp` returns.  With out a return . . . there is no return.

In the future, please ask for help in [Help JavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and Happy Coding!

**Comment by SteveRaskin** [comment]
Thx, my bad: in fact it was burnout-related trivial error on my part in how I was calling the function. Time to rest :)
