### ISSUE TITLE
Replacing If Else Chains with Switch: Commented out Code fails the test

### ISSUE THREAD

**Issue by Offloads** [FreeCodeCamp/FreeCodeCamp#6725]
This is a rather small detail, but in this challenge when the original if else code is replaced by the switch statement it does not pass the first two test because the key words of 'if' & 'else' are seen. However, this should pass the test if the code is commented out, it would then be possible to keep a nice record of the changes made. 
![screen shot 2016-02-03 at 12 17 39 am](https://cloud.githubusercontent.com/assets/11233306/12801544/c29e758a-cadd-11e5-95e3-0f8b5fac9685.png)

**Comment by SaintPeter** [comment]
I'm sorry, but our infrastructure doesn't have the complexity to parse JavaScript and ignore comments.  In particular, for earlier challenges where we're looking to make sure you didn't use specific statements, there is just no way to do it.

Thanks and Happy Coding!
