### ISSUE TITLE
Tests pass but user doesn't follow instruction

### ISSUE THREAD

**Issue by mynameissal** [FreeCodeCamp/FreeCodeCamp#6728]
Challenge [Create a Bootstrap Row](http://www.freecodecamp.com/challenges/create-a-bootstrap-row) has an issue.

User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.

Please describe how to reproduce this issue, and include links to screenshots if possible:

- Instructions were: "Create a div element below the h3 tag, with a class of row."
- I put my h3 element within the div with the class set to row.
- All tests passed.
- It should not let me pass because I didn't put the div class row below h3

My code:
```html
<div class="container-fluid">
  <div class="row">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  </div>
</div>


```

**Comment by wolverine2k** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6734 PR for fixing this issue.
