### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue 

### ISSUE THREAD

**Issue by SladeBox** [FreeCodeCamp/freecodecamp#673]
The 2nd objective: Your anchor element should have the anchor text of "See my cat photos".

To be consistent with the lesson, it should read: Your anchor element should have the anchor text of "cat photos"

**Comment by terakilobyte** [comment]
Thanks, commit 08cdc103630b9a95f371557718d40a2b00dc7d7a fixes this inconsistency.
