### ISSUE TITLE
Issues with font-size test on multiple browsers.

### ISSUE THREAD

**Issue by AikaMei** [FreeCodeCamp/FreeCodeCamp#6731]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20purr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Kitty ipsum purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by AkiraLaine** [comment]
What browser/OS are you using?

Also, are you sure that your Zoom is set to 100%?

**Comment by AikaMei** [comment]
I used both mozilla and chrome. The zoom is at 100%.
I got the problem right initially on Jan 20th, but today it is not.

**Comment by AikaMei** [comment]
My friend is also cannot get passed this

**Comment by AikaMei** [comment]
Should I wait for it to get fixed?

**Comment by alistermada** [comment]
Your second `<p>` element shouldn't have any classes.
Under the **Note** in the challenge description:
> Also, please do not add any extra classes to your new element.

**Comment by AikaMei** [comment]
thanks @alistermada it worked!

**Comment by AkiraLaine** [comment]
@alistermada I missed that. Thanks :smile:

**Comment by brb808** [comment]
I'm a little confused why declaring the p class for the text size did not require ".p" with a period in front like .red-text?

**Comment by iamscripted** [comment]
@brb808 the (.) dots  are only used for classes. so that's a way of saying that you want to target just the class name (ie. .red-text).  p  is an element, so it doesn't use that. It also means that all paragraph tags made will be 16px.. well, unless a class is made that declare otherwise.  Just remember this, class and id are used to uniquely customize elements.

**Comment by brb808** [comment]
@iamscripted Thank you for the great explanation.
