### ISSUE TITLE
Requires some more explanation

### ISSUE THREAD

**Issue by devarsh1997** [FreeCodeCamp/FreeCodeCamp#6735]
Challenge [Use Abbreviated Hex Code](http://www.freecodecamp.com/challenges/use-abbreviated-hex-code#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%23F00%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: #F00;
  }
</style>

```

In the explanation of this exercise, there is no explanation or more reasoning behind mechanics about these lines:
> This reduces the total number of possible colors to around 4,000. But browsers will interpret #FF0000 and #F00 as exactly the same color.

 If there is a link where this understanding is outlined in more detail would greatly help a learner here. If underlying explanation is not too complex it could be even explained in this section itself.

**Comment by VibhorThakral** [comment]
In the hexadecimal code #FF0000, FF portion represents the red, 00 represents the green and 00 represents the blue respectively, so when both the values of Red or green or blue are same they can be representated by one letter in this case #F00(red,green,blue), but if the values of red, green and blue are not same for example #004546, you can not shorten the notation, also note that you can not shorten the notation for a single color value like in the above case you can not shorten the notation to #04546, it would not work.
Like this the same can be said for these examples:
#222222= #222 ("  22=2 for rgb  ")
For a deep study I would suggest to refer to MDN:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors

**Comment by SaintPeter** [comment]
It's actually just `16^3 = 4096`.

https://www.w3.org/TR/CSS2/syndata.html - Section 4.3.6 Colors
> The format of an RGB value in hexadecimal notation is a '#' immediately followed by either three or six hexadecimal characters. The three-digit RGB notation (#rgb) is converted into six-digit form (#rrggbb) by replicating digits, not by adding zeros. For example, #fb0 expands to #ffbb00. This ensures that white (#ffffff) can be specified with the short notation (#fff) and removes any dependencies on the color depth of the display.

I'm not sure how to link this explanation in, though.

**Comment by devarsh1997** [comment]
@SaintPeter and @VibhorThakral the explanations makes much more sense. How about we link one of your explanations by stating in the explanation after the lines I cited. For example:

> [Click here](https://www.w3.org/TR/CSS2/syndata.html) to understand in more detail why.

I hope I am making sense.

**Comment by SaintPeter** [comment]
I'm not sure how important this actually is.  Certainly it's trivial to add the link.  I don't necessarily want to add unneeded details.

@FreeCodeCamp/issue-moderators What do ya think?

**Comment by bugron** [comment]
@SaintPeter said:
>I'm not sure how important this actually is.

Agreed. Closing this issue. @devarsh1997 thanks for posting.
