### ISSUE TITLE
Cannot continue after completing the challenge: Target a Specific Child of an Element Using jQuery

### ISSUE THREAD

**Issue by pcrist13** [FreeCodeCamp/FreeCodeCamp#6737]
Won't navigate to the next challenge after completing this one. This occurs on several pages it seems like and I followed someone else's bizarre suggestion to move the everything in the script tags to the bottom of the page. This worked for a little while but stuck on this challenge. 

Just will manually skip forward using the map but this is quite frustrating.

**Comment by sludge256** [comment]
Would you mind providing some more info? Browser/OS and a screenshot or details of any messages that show up in the browser's console upon clicking submit?

**Comment by pcrist13** [comment]
Google Chrome Console:
https://sidecar.gitter.im/dist/sidecar.v1.js Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
http://www.freecodecamp.com/completed-challenge/ Failed to load resource: net::ERR_CONNECTION_RESET

Attached two screenshots showing the code used, and where it gets hung up.
![code](https://cloud.githubusercontent.com/assets/11684076/12823381/df747e34-cb28-11e5-9522-6176df28f272.jpg)
![stuck](https://cloud.githubusercontent.com/assets/11684076/12823383/e3ca9662-cb28-11e5-8eed-b8dd5f899317.jpg)

**Comment by raisedadead** [comment]
@pcrist13 Thanks, Do you mind posting a screenshot of your browser console (F12 > Console Tab), as well?

Are you behind any firewall, VPN or any browser extension? If that's the case can you check if [this wiki article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc) helps you?

**Comment by bugron** [comment]
@pcrist13 hopefully, this is fixed now. Thanks for posting. Closing this issue. Feel free to reopen if you still experience problems, thanks.
