### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-html5-to-require-a-field has an issue 

### ISSUE THREAD

**Issue by ehuggz** [FreeCodeCamp/freecodecamp#674]
The placeholder text was removed from the text field in the code source when entering this challenge and an error occurs showing it is missing. Adding the placeholder and text does not clear the error and I cannot move past this challenge.

**Comment by terakilobyte** [comment]
I'm unable to reproduce this error. Please reopen this issue if it still affects you. https://www.evernote.com/l/AibpWYVjDNNLuL2se0LI36RvZ-6FHhBgyzo
