### ISSUE TITLE
Improve contributor's guide documentation for new contributors

### ISSUE THREAD

**Issue by simondiep** [FreeCodeCamp/FreeCodeCamp#6741]
I'm a new contributor to this project and have run into a few confusing points on CONTRIBUTING.md that I'd like to clarify for other new contributors.

1. waffle.io - From a few other contributors, I've been told this is no longer used.  I'd suggest removing this from the contributor's guide.

2. Installing npm dependencies.  This project has a dependency to [node-gyp](https://github.com/nodejs/node-gyp) which is confusing to set up for new NodeJs developers.  I'd propose to mention this link to get new Node developers started, especially for Windows, since it involves some unusual installations like Visual Studio for the C++ compiler.

3. There isn't any mention of running tests before submitting a pull request.  This is something that could be easily missed and cause a pull request to fail the TravisCI build.  I've learned that one pre-test dependency, JSONLint, doesn't work for the Windows filesystem.  As a workaround, I'd suggest all contributors on Windows to run the tests directly by skipping the pre-test lint run.  
`npm run test-challenges`
An additional step could be to manually run JSONLint on individual files, without using the problem-causing wildcard *.  For non-Windows contributors, it should be mandatory to run `npm test` before a pull request.

**Comment by SaintPeter** [comment]
These all sound like reasonable changes.  Go ahead and get a PR going for it.

**Comment by simondiep** [comment]
I'll get started on it.
