### ISSUE TITLE
Topic: Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by Subh-007** [FreeCodeCamp/FreeCodeCamp#6745]
Challenge [Target the same element with multiple jQuery Selectors]

>   $(document).ready(function() {
>     $("button").addClass("animated zoomIn shake");
>     $(".btn").addClass("shake");
>     $("#target1").addClass("btn-primary");
>   });
> 

1. - Only add one class with each of your three selectors.
2. - Your #target1 element should have the classes animated‚ shake and btn-primary.

How is this possible, or may be i am misunderstanding something.
??

**Comment by AkiraLaine** [comment]
Please read the instructions:
> Using each of the above jQuery selectors and the addClass() function:
>Add the animated class to all elements with type button.
>Add the shake class to all the buttons with class .btn.
>Add the btn-primary class to the button with id #target1.

If you need help please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [help](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room. GitHub is for issues only.
