### ISSUE TITLE
Check for Plaindromes

### ISSUE THREAD

**Issue by EktaSingh** [FreeCodeCamp/FreeCodeCamp#6746]
Hi there,
palindrome("0_0 (: /-\ :) 0-0") should return true.
This is not true since _ and - are not same.

Kindly update.

**Comment by SaintPeter** [comment]
You are incorrect.  Please read the instructions carefully.

You can ask for coding help in [Help JavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and Happy Coding!

**Comment by EktaSingh** [comment]
Yeah right.
Just read.

Thanks,
Ekta Singh
