### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by reanjar** [FreeCodeCamp/FreeCodeCamp#6747]
Challenge [Return Early Pattern for Functions](http://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(a%3C0%20%7C%7C%20b%3C0)%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function abTest(a, b) {
  // Only change code below this line
  if(a<0 || b<0){
    
    return "undefined";
  } 
  
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

```

**Comment by SaintPeter** [comment]
Please read the **Hint** at the bottom of the instructions.

GitHub Issues are not for code problems.  In the future, please ask for help in [Help JavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and Happy Coding!

**Comment by jacob1324756** [comment]
you need to do the "else if" in your code like this look below

// Setup
function abTest(a, b) {
  // Only change code below this line
 if(a < 0)
    return (undefined);
  else if(b < 0)
    return (undefined);
   


  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);
