### ISSUE TITLE
Brazilian Portuguese translation of Getting Started

### ISSUE THREAD

**Issue by andreferreira-me** [FreeCodeCamp/FreeCodeCamp#6755]
- [ ] Learn how Free Code Camp Works Complete
- [ ] Create a GitHub Account and Join our Chat Rooms Complete
- [ ] Configure your Code Portfolio Complete
- [ ] Join a Campsite in Your City Complete
- [ ] Learn What to Do If You Get Stuck

**Comment by andreferreira-me** [comment]
Working on it

**Comment by Ronaiza** [comment]
Hey, voce já terminou? eu terminei a minha e dei o pull. não sei como colocar que já está acabado

**Comment by fredericksilva** [comment]
Oi @Ronaiza da um pull com referencia para o issue ex " `commit -m "#6755 - Finalizei a tradução" ` "

**Comment by andreferreira-me** [comment]
@Ronaiza Havia começado, mas não tinha terminado.. Pode enviar o seu commit, vou enviar as minhas traduções até o final de semana.. Nas próximas, tente pegar um issue que não tenha ninguém trabalhando, ou tente conversar lá pelo Gitter para que não tenhamos trabalho dobrado.

**Comment by raisedadead** [comment]
Hi @andreferreira-me, I have closed this in favor of  https://github.com/FreeCodeCamp/TranslationExpansion/issues/55, please continue the discussion on that thread.
