### ISSUE TITLE
crsumit

### ISSUE THREAD

**Issue by SatyaShivam** [FreeCodeCamp/FreeCodeCamp#6757]
Challenge [Add Borders Around your Elements](http://www.freecodecamp.com/challenges/add-borders-around-your-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
  }
  .thin-red-border {
    border-color: red;
    border-width: 10px;
    border-style: solid;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<img class="smaller-image"> 
<img src="https://bit.ly/fcc-relaxing-cat">
<img class="thick-green-border">
<img class="border-color:green"> 
<img class="border-width:10px">
<img class="border-style:solid">
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by SatyaShivam** [comment]
Give your image a border width of 10px.
Give your image a border style of solid.
The border around your img element should be green.  
 my code is not running its want these all this elements, i can do all this things, but cant solve my code 
plz give me the advice...

**Comment by raisedadead** [comment]
@SatyaShivam Please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help), GitHub Issues are for bugs in the site only.
