### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by t4deu** [FreeCodeCamp/freecodecamp#676]
The "top margin" check description is indicating the wrong value "20px" while the correct to complete the challenge is "40px":

> Your green-box class should give the left of elements 40px of margin.
> Your green-box class should give the bottom of elements 20px of margin.
> Your green-box class should give the top of elements **20px** of margin.
> Your green-box class should give the right of elements 20px of margin.

**Comment by terakilobyte** [comment]
Thanks, closing this as a duplicate of #665
