### ISSUE TITLE
Bonfire Chunky Monkey Solution Issue

### ISSUE THREAD

**Issue by Mashadim** [FreeCodeCamp/FreeCodeCamp#6760]
On Solution #3  newArray should be newArr:

https://github.com/freecodecamp/freecodecamp/wiki/bonfire-chunky-monkey#solution-3

**Comment by SaintPeter** [comment]
@Mashadim Can you please open this issue on the Wiki repo?
https://github.com/FreeCodeCamp/wiki

Thanks and Happy Coding!
