### ISSUE TITLE
Ambiguity in both description and tests-- What to do when card is 7||8||9 -- Counting Cards

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#6761]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20bet%20%3D%20''%3B%0A%20%20if(card%3C%3D6)%7B%0A%20%20%20%20count%20%2B%2B%3B%0A%20%20%7D%20else%20if%20(!(card%3C%3D9))%7B%0A%20%20%20%20%20%20count%20--%3B%0A%20%20%7D%0A%20%20bet%20%3D%20count%20%3E%200%3F%20'%20Bet'%3A'%20Hold'%3B%0A%20%20return%20count%20%2B%20bet%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  var bet = '';
  if(card<=6){
    count ++;
  } else if (!(card<=9)){
      count --;
  }
  bet = count > 0? ' Bet':' Hold';
  return count + bet;
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

#Ambiguity for what to do when `card` is 7, 8, or 9

![image](https://cloud.githubusercontent.com/assets/6234475/12858427/669845aa-cc0d-11e5-94ef-9e38c7503feb.png)

From this, campers seem pretty evenly split between thinking that `count` should be *reset* to `0` or simply *should not be changed*.  
The only test case is:
![image](https://cloud.githubusercontent.com/assets/6234475/12858472/a0075ce0-cc0d-11e5-9d33-b4b4602a0b0d.png)
Which will pass in either case.

This means that you can accomplish the task regardless of how you interpret the instructions, but has been leading to some confusion for people asking for help.

**Comment by SaintPeter** [comment]
Interesting.  I thought that it was clear that these were changes to `count`.

I think we need at least 2 more tests which have some combination of 7/8/9 and other value such that resetting `count` to `0` would fail.  I'm open to suggestions on how to emphasize that for these three values that we should not change `count` at all. . . . or that the `Value` represents a change in the value of `count`, not the final value.

**Comment by eranmor** [comment]
Hi guys,
The code should chekc all options not just numbers, this is my solution and it passed OK:

`var count = 0;

function cc(card) {
  // Only change code below this line
 
 
  if(card >= 2 && card <= 6) {
    count++;
       
  } else if (card >= 7 && card <=9){
          count = count + 0;
    
  } else {
  count--;
  }
  
 if(count > 0){
   return count + " Bet";
 } else 
   return count + " Hold";  
    // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');
`

Hope this helps, 
Happy Coding

**Comment by raisedadead** [comment]
@SaintPeter Adding test cases with combination of 7/8/9 and any other value will help. Additionally we could mention in the instructions as a hint that "Do NOT reset count to 0 when value is 7/8/9"

What do you say?

**Comment by erictleung** [comment]
I didn't see the last comment before making my PR. I didn't add any sentence like "Do NOT reset count to 0 when value is 7/8/9" but if anyone feels I should. I can make those changes real fast.

**Comment by raisedadead** [comment]
@erictleung confirmed from comment [here]( https://gitter.im/FreeCodeCamp/HelpContributors?st=56c2b28bd3f30e0852e63ddb)

**Comment by erictleung** [comment]
I'll go ahead and add that snipit.
