### ISSUE TITLE
I return not found but it doesn't complete the challenge.

### ISSUE THREAD

**Issue by epicgug** [FreeCodeCamp/FreeCodeCamp#6764]
Challenge [Testing Objects for Properties](http://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20if(myObj.hasOwnProperty(checkProp))%20%7B%0A%20%20%20%20return%20myObj%5BcheckProp%5D%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22Not%20Found.%22%3B%0A%20%20%7D%0A%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22house%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 7647.73.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.92 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if(myObj.hasOwnProperty(checkProp)) {
    return myObj[checkProp];
  } else {
    return "Not Found.";
  }

}

// Test your code by modifying these values
checkObj("house");

```

**Comment by TravisHi** [comment]
You have to return _Exactly_ what they ask you for, so just remove the Full stop after "Not Found" in your code

**Comment by epicgug** [comment]
I could have sworn there was a period in the return striing they asked for

**Comment by TravisHi** [comment]
Yeah I did too when I first read it :p

**Comment by mohannadsawalhi** [comment]
NOT FOUND NO "."

**Comment by shadikh** [comment]
return "Not Found .";
it has to be with out   "  .  "    only  "  Not Found ";
