### ISSUE TITLE
nitpicking re: diction

### ISSUE THREAD

**Issue by SteveRaskin** [FreeCodeCamp/FreeCodeCamp#6765]
Challenge [Filter Arrays with filter](http://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0Avar%20newArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AnewArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20%20%20return%20val%20%3C%3D%205%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];
var newArray = [];

// Only change code below this line.

newArray = oldArray.filter(function(val){
    return val <= 5;
});

```
&lt;nitpicking>

Since .filter() "does not mutate the array on which it is called ... and instead constructs a new array", I would suggest the challenge be reworded, e.g.:

"Use filter to create newArray such that it comprises only elements from oldArray that are ... "

&lt;/nitpicking>

**Comment by SaintPeter** [comment]
Normally I'm a 10 cent word kinda guy, but I think the simpler phrasing is easier to translate into other languages.

Also, I think I would say "is comprised of" - I am not sure that it is grammatically correct to say "it comprises only".

Regardless, I don't see much value in the change.

Thanks and Happy Coding!
