### ISSUE TITLE
"Run test" button is irresponsive for Chrome

### ISSUE THREAD

**Issue by xxks-kkk** [FreeCodeCamp/FreeCodeCamp#6766]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>


```

**Comment by SaintPeter** [comment]
It is responsive, your code is just wrong.  You are not supposed to add a class to the new `p` element, as it explicitly says in the instructions.

In the future, please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help) before opening an issue.

Thanks and Happy Coding!

**Comment by xxks-kkk** [comment]
Then it is really a unfriendly design. Click a button, expect something but actually not :(

Then how about now?
```
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

Still not showing anything?

**Comment by SaintPeter** [comment]
I agree that we could do a better job of showing that the tests have completed running.

>**Inside the same `<style>` tag** that contains your red-text class, **create an entry for p elements** and set the font-size to 16 pixels (16px).

**Comment by xxks-kkk** [comment]
Glad to see that. I feel confusing about wording of the hint, "Create an entry for p elements" and I figure out with the help of fellow campers:

```
<style>
  .red-text {
    color: red;
  }
  p{font-size: 16px;
  }
</style>

```
To be honest, I have never seen this kind of usage (element tag followed by properties) until this usage? Would you guys show some example before this usage? Otherwise, I probably will stuck here forever.
