### ISSUE TITLE
not matching backslash in regex

### ISSUE THREAD

**Issue by haasDev** [FreeCodeCamp/FreeCodeCamp#6769]
when I submit my code everything passes except final test.  when debugging I found that the backslash in my regex isn't being matched as it should for some reason.

Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20%0A%20%20str%20%3D%20str.toLowerCase().split(%22%22).filter(function(elem)%7B%20%0A%20%20%20%20return%20elem.match(%2F%5Ba-z0-9%5C-%3A%5C%2F%5C%5C()_%5D%2F)%3B%0A%20%20%7D).join()%3B%0A%20%20%0A%20%20console.log(str)%3B%0A%20%20%0A%20%20return%20str%20%3D%3D%3D%20str.split(%22%22).reverse().join(%22%22)%3B%0A%7D%0A%0A%0A%0Apalindrome(%220_0%20(%3A%20%2F-%5C%20%3A)%200-0%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  
  str = str.toLowerCase().split("").filter(function(elem){ 
    return elem.match(/[a-z0-9\-:\/\\()_]/);
  }).join();
  
  console.log(str);
  
  return str === str.split("").reverse().join("");
}



palindrome("0_0 (: /-\ :) 0-0");

```

**Comment by alistermada** [comment]
Note: The instructions ask you to "remove all non-alphanumeric characters (punctuation, spaces and symbols)". This means your filtered string should only have letters and numbers.

If you are stuck on a challenge, please check out the [Help Chat](https://gitter.im/FreeCodeCamp/Help) first.
