### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue 

### ISSUE THREAD

**Issue by remrobem** [FreeCodeCamp/freecodecamp#677]
Minor: 
The descriptive/Info text says to use "cat photos" as anchor text

Create an anchor element that links to http://catphotoapp.com and has "cat photos" as its anchor text (link text).

The info at the bottom has a different anchor text mentioned:

Your anchor element should have the anchor text of "See my cat photos"

**Comment by terakilobyte** [comment]
Thanks, commit 894428f6e21915993d62f6e1028d3701e30af0bf addresses this.
