### ISSUE TITLE
Nest one Array within Another Array

### ISSUE THREAD

**Issue by kmulligan** [FreeCodeCamp/FreeCodeCamp#6770]
In Basic Javascript --> Nest one Array within Another Array, the example code given isn't nested... I think.

This is the code:
```
// Example
var ourArray = [["the universe", "everything", 42]];

// Only change code below this line.
var myArray = [["Kevin", 32,], 31];
```

My code works and passes. But shouldn't the example be:
``
// Example
var ourArray = [["the universe", "everything"], 42];
``

...to show off the nesting?

**Comment by alistermada** [comment]
A nested array is simply an array within another array. Your code has a nested array (`["Kevin", 32]`), but so does the example (`["the universe", "everything", 42]`). Having other elements (such as the number 42) within the top-level array is irrelevant.

**Comment by kmulligan** [comment]
Gotcha. Thanks. Just was a little confused by the double [[ ]] with nothing else in it.

**Comment by SaintPeter** [comment]
I agree, this example stinks.

The example code should be re-written to show more than one array inside another array.
eg:
```
[[1,2], ["buckle","my"],["shoe", 3, 4]]
```

**Comment by kmulligan** [comment]
Thanks, should I leave this open or close it?

**Comment by sludge256** [comment]
Go ahead and leave it open. It will be closed once a better example is created and accepted. It could even be you who submits the PR ;)
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md
