### ISSUE TITLE
Green checkmarks missing in project view and video view

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6775]
![](https://www.evernote.com/l/AqQfS5l81B9OGJHIFQ9y46utfp7tipzgMvEB/image.png)
![](https://www.evernote.com/l/AqRIb3uizgpEn4vA3J5Bkf5KVOce6nJATkIB/image.png)

**Comment by alistermada** [comment]
I was working on this and I noticed that the view for the video challenges aren't loaded from the `showVideo.jade` file in `freecodecamp\server\views\challenges` but from the `Hike.jsx` file `freecodecamp\common\app\routes\Hikes\components`.

No wonder editing `showVideo.jade` wasn't doing anything.
