### ISSUE TITLE
Wrong testcase? Friendly date ranges

### ISSUE THREAD

**Issue by Pwter** [FreeCodeCamp/FreeCodeCamp#6779]
> friendly(["2016-07-01", "2016-07-04"]) should return ["July 1st","4th"].
> **friendly(["2016-12-01", "2017-02-03"]) should return ["December 1st","February 3rd"].**
> friendly(["2016-12-01", "2018-02-03"]) should return ["December 1st, 2016","February 3rd, 2018"].
> friendly(["2017-03-01", "2017-05-05"]) should return ["March 1st, 2017","May 5th"]
> friendly(["2018-01-13", "2018-01-13"]) should return ["January 13th, 2018"].
> friendly(["2022-09-05", "2023-09-04"]) should return ["September 5th, 2022","September 4th"].
> friendly(["2022-09-05", "2023-09-05"]) should return ["September 5th, 2022","September 5th, 2023"].

I think there is a fault here, you need the year here in the bold line.
it should return ["December 1st, 2016","February 3rd"]

http://www.freecodecamp.com/challenges/friendly-date-range

**Comment by AkiraLaine** [comment]
@Pwter The instructions state:
>  if the date range ends in less than a year from when it begins, do not display the ending year.

Happy Coding :smile:

**Comment by Pwter** [comment]
> Additionally, if the date range begins in the current year and ends within one year, the year should not be displayed at the beginning of the friendly range.
this is the one mentioning the beginning of the range but thanks!:)

**Comment by Pwter** [comment]
Thanks! But isnt that contradicts with this one?

> friendly(["2022-09-05",

 "2023-09-04"]) should return ["September 5th, 2022","September 4th"].

**Comment by AkiraLaine** [comment]
@Pwter Actually this: ```friendly(["2016-12-01", "2017-02-03"])``` should follow this:
> Additionally, if the date range begins in the current year and ends within one year, the year should not be displayed at the beginning of the friendly range.

Not sure about ```friendly(["2022-09-05", "2023-09-04"])``` though. Am I missing something @FreeCodeCamp/issue-moderators

**Comment by Pwter** [comment]
> Additionally, if the date range begins in the current year and ends within one year, the year should not be displayed at the beginning of the friendly range

Is this about the current year as it is 2016 now? I thought it's about the friendly dates.

**Comment by AkiraLaine** [comment]
Current year refers to all ```2016``` dates

**Comment by Pwter** [comment]
Okey, i found the problem, thanks!
