### ISSUE TITLE
Some problems with video challenges

### ISSUE THREAD

**Issue by alistermada** [FreeCodeCamp/FreeCodeCamp#6781]
**1.** After answering a question, the answer remains highlighted in the next question.

![image](https://cloud.githubusercontent.com/assets/12993334/12866492/ee85469e-cd01-11e5-8688-ff2fd3c7bbf0.png)

**2.** ~~Reference to Hikes upon challenge completion.~~ [Fixed]

**3.** Large gaps in the video description.

![image](https://cloud.githubusercontent.com/assets/12993334/12866486/9c079dea-cd01-11e5-9007-a7636eb89ad2.png)

**4.** Clicking on "View this challenge" on my code portfolio for one of my completed video challenges redirects me to the map.

**Comment by Greenheart** [comment]
1. I think that is a desired behavior in order to show what button you selected but I'm not sure.
2. Should probably say "challenge" instead?
3. Probably a design choice to make it easier to skim through. However I agree that it could be decreased a little bit.
4. Verified

**Comment by noncentz** [comment]
Just a heads up in case someone missed it, 
![hmm](https://cloud.githubusercontent.com/assets/8762304/12875980/08de8dbc-cdc4-11e5-9a86-a2419cd563f7.png)

**Comment by alistermada** [comment]
@Greenheart As for number 1, the screenshot shows my answer for Question 1; I didn't click false on Question 2. I don't think answers from the previous question should remain highlighted on the current one.

@noncentz I'm not sure what's up with Question 3. As for the Meet Bonfire solution, the challenge has been renamed so the route it's trying to link to (`\challenges\meet-bonfire`) doesn't exist. That should probably be a separate issue are there are a bunch of other renamed challenges with the same problem.

**Comment by SaintPeter** [comment]
Looks like there was a leftover question here:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/04-video-challenges/jslingo.json#L31

These were part of the template I built when we added these in.  Probably just a simple oversight.

**Comment by CEREBR4L** [comment]
Also you you click on a question and pull it right it will skip the question, should you do this for all the asked questions it will still reward the challenge.

**Comment by Greenheart** [comment]
@CEREBR4L I've noticed that too. However that should be handled in another issue. See if there already is an issue for this by searching or else go ahead an open a new one.

Good job everyone and happy coding! :)

**Comment by ltegman** [comment]
@CEREBR4L Pulling it in either direction is the same as pushing the button that is on that side, so if you were able to pull right for all the questions that means false was the correct answer to all of them.
