### ISSUE TITLE
it doesn't run tests

### ISSUE THREAD

**Issue by shw-eta** [FreeCodeCamp/FreeCodeCamp#6783]
![screenshot from 2016-02-06 21 55 47](https://cloud.githubusercontent.com/assets/17098338/12867830/62e6b042-cd1e-11e5-89b1-02bdc20c81d3.png)

Challenge [Say Hello to HTML Elements](http://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.120 Chrome/37.0.2062.120 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

```

**Comment by itschetan** [comment]
![screenshot 11](https://cloud.githubusercontent.com/assets/17069952/12867990/e8137f22-cd21-11e5-853c-1ec714954194.png)
Its working..!!! Try restaring your browser then try.

**Comment by VibhorThakral** [comment]
Many people are facing this issue even I had it at first I would say you should try using VPN, Browsec is a very good chrome extension for it. :)

**Comment by sludge256** [comment]
Try this:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc

**Comment by shw-eta** [comment]
Thanku guys I have installed browser everything is fine now ! :)

**Comment by shw-eta** [comment]
*browsec
