### ISSUE TITLE
Typo: The past tense of input

### ISSUE THREAD

**Issue by acr187** [FreeCodeCamp/FreeCodeCamp#6787]
![inputed](https://cloud.githubusercontent.com/assets/17096026/12869735/84470d90-cd73-11e5-9011-ecf018e9f838.png)

Challenge [Add Placeholder Text to a Text Field](http://www.freecodecamp.com/challenges/add-placeholder-text-to-a-text-field) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The issue:
I beleive the past tense of input is input and the sentence should read, "Your placeholder text is what appears in your text input before your user has input anything." I've highlighted the word with a red outline.

**Comment by Greenheart** [comment]
I agree, good job finding it!
