### ISSUE TITLE
Japanese translation of Getting Started

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6789]
- [ ] Learn how Free Code Camp Works
- [x] Create a GitHub Account and Join our Chat Rooms
- [ ] Configure your Code Portfolio
- [ ] Join a Campsite in Your City
- [ ] Learn What to Do If You Get Stuck

**Comment by regonn** [comment]
"Create a GitHub Account and Join our Chat Rooms" DONE :tada:

**Comment by justinian336** [comment]
Great job @regonn, marked as completed!

**Comment by erictleung** [comment]
Closing in favor of moving the conversation over to https://github.com/FreeCodeCamp/TranslationExpansion/issues/56
