### ISSUE TITLE
Japanese translation of Advanced Bonfires

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6790]
- [ ] Validate US Telephone Numbers
- [ ] Symmetric Difference
- [ ] Exact Change
- [ ] Inventory Update
- [ ] No repeats please
- [ ] Friendly Date Ranges
- [ ] Make a Person
- [ ] Map the Debris
- [ ] Pairwise

**Comment by erictleung** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/57
