### ISSUE TITLE
Japanese translation of Basic Bonfires

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6791]
- [ ] Get Set for our Algorithm Challenges
- [ ] Reverse a String
- [ ] Factorialize a Number
- [ ] Check for Palindromes
- [ ] Find the Longest Word in a String
- [ ] Title Case a Sentence
- [ ] Return Largest Numbers in Arrays
- [ ] Confirm the Ending
- [ ] Repeat a string repeat a string
- [ ] Truncate a string
- [ ] Chunky Monkey
- [ ] Slasher Flick
- [ ] Mutations
- [ ] Falsy Bouncer
- [ ] Seek and Destroy
- [ ] Where do I belong
- [ ] Caesar's Cipher

**Comment by erictleung** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/58
