### ISSUE TITLE
Japanese translation of Basic Ziplines

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6792]
- [ ] Get Set for our Front End Development Projects
- [ ] Build a Personal Portfolio Webpage
- [ ] Build a Random Quote Machine
- [ ] Build a JavaScript Calculator
- [ ] Build a Pomodoro Clock

**Comment by erictleung** [comment]
Closing in favor of https://github.com/FreeCodeCamp/TranslationExpansion/issues/60
