### ISSUE TITLE
Filtered all results greater than 5

### ISSUE THREAD

**Issue by lamar-frankie** [FreeCodeCamp/FreeCodeCamp#6794]
Challenge [Filter Arrays with filter](http://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%20%3E%3D%206%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val >= 6;
});

my code: 

var newArray = oldArray.filter(function(val){
  return val > 5;
});

the result:
[6,7,8,9,10]

but code doesn't pass

**Comment by AkiraLaine** [comment]
Hey @lamar-frankie, please read the insurrections and tests carefully.

If you need help, go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [JavaScript Help](https://gitter.im/FreeCodeCamp/HelpJavaScript) room. GitHub is for issues only.

**Comment by EthanDproject** [comment]
Frankie i was having problems with this on as well. The instruction is a little confusing.  what i see you need an another that is the opposite do it should look like this 1,2,3,4,5 instead. so you need val<5 instead.

this is the code i did and i passed.
newArray=oldArray.filter(function(x){
  return x<=5;
 });
(function() { return newArray; })();


if this helps
