### ISSUE TITLE
Navbar displaced on certain viewport widths

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#6799]
![](https://www.evernote.com/l/Ar-on4o2CuNGG6D8zfWXtJQHuDTik-htpxsB/image.png)

**Comment by abisz** [comment]
that's because the media query is adjusted for single-digit challenge points. does it make sense to change the "max-width" so the layout is safe up to four-digit points, or does anyone have a better idea?

**Comment by SaintPeter** [comment]
@hallaathrad Want to take a look at this?

**Comment by hallaathrad** [comment]
I'm on it
