### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue 

### ISSUE THREAD

**Issue by ricmclaughlin** [FreeCodeCamp/freecodecamp#680]
The challenge "more information" section and the test include "border-style: solid;" (so they are good) but the challenge description does not include anything about making the border solid.

The description for this challenge is currently "Create a class called "thick-green-border" that puts a 10-pixel-wide green border around an HTML element, and apply it to your cat photo."

The description for this challenge should be changed to "Create a class called "thick-green-border" that puts a 10-pixel-wide green **solid** border around an HTML element, and apply it to your cat photo."

**Comment by terakilobyte** [comment]
Thanks, I took care of this in a commit already!
