### ISSUE TITLE
Challenge Basic JavaScript :: Manipulate Arrays with unshift() description not matching needed solution

### ISSUE THREAD

**Issue by skusku** [FreeCodeCamp/FreeCodeCamp#6805]
The challenge in Basic JavaScript
 "id": "bg9997c9c69feddfaeb9bdef",
 "title": "Manipulate Arrays With unshift()"

asks us to `unshift()` the Array. However you have to first `shift()` the solution and then `unshift()` it in order to proceed.

**Comment by AkiraLaine** [comment]
@skusku You do not have to ```shift()``` the array, that is done for you. 

@FreeCodeCamp/issue-moderators Thoughts?

**Comment by skusku** [comment]
Hmm, I had to shift() before it worked for me. I still feel strange that there's a shift when the description is clearly only about unshift(). The returned answer is in my eyes not what one would expect from the question.

**Comment by AkiraLaine** [comment]
@skusku Could you paste your code here?

**Comment by skusku** [comment]
```
// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();
myArray.unshift(["Paul",35]);

// Only change code below this line.
```

**Comment by skusku** [comment]
and this did not work:
```

// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];

// Only change code below this line.
myArray.unshift(["Paul",35]);


```

**Comment by sludge256** [comment]
@skusku It seems you removed the `shift()` from the default code

This is what I have with a reset to ensure I'm looking at default code:
```js
// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();

// Only change code below this line.
```

**Comment by skusku** [comment]
Oh okay oops! My bad then.
