### ISSUE TITLE
"Missing" Basic JavaScript challenges

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6812]
The last challenge in the JavaScript section is "Invert Regular Expression Matches with JavaScript."

![image](https://cloud.githubusercontent.com/assets/2754821/12874316/a74a0014-cd86-11e5-9204-2a1c33510999.png)

But in the [code base](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4723), there are more challenges:

- Create a JavaScript Slot Machine
- Add your JavaScript Slot Machine Slots
- Bring your JavaScript Slot Machine to Life
- Give your JavaScript Slot Machine some Stylish Images

Additionally, if you run a local instance of FCC, you can see these "extra" challenges:

![image](https://cloud.githubusercontent.com/assets/2754821/12874388/f002f31e-cd87-11e5-8322-8ebe36170547.png)

So is this on purpose or really is a bug?

**Comment by bugron** [comment]
@erictleung that is true. But these challenges are marked as beta (see `"isBeta": true` property for those challenges), that is why they're not in production site.
