### ISSUE TITLE
Need to add Raleigh, NC to the map

### ISSUE THREAD

**Issue by imimpressed** [FreeCodeCamp/FreeCodeCamp#6813]
[Raleigh, NC](https://www.facebook.com/groups/free.code.camp.raleigh) is on the list but not on the map,[ "List of Free Code Camp city based Campsites" ](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/List-of-Free-Code-Camp-city-based-Campsites)on [google maps](https://www.google.com/maps/d/u/0/embed?mid=zH0hxoM17_fk.kDBMlxfk0BZ8).

**Comment by hallaathrad** [comment]
Added ;)
