### ISSUE TITLE
I have completed this session already and have moved onto the next session but it is not showing as complete on my map.  This is also the same with:

### ISSUE THREAD

**Issue by NYCSavage** [FreeCodeCamp/FreeCodeCamp#6816]
Challenge [Add Different Margins to Each Side of an Element](http://www.freecodecamp.com/challenges/add-different-margins-to-each-side-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 10px;
  }
  
  .red-box {
    background-color: red;
    margin-top: 40px;
    margin-right: 20px;
    margin-bottom: 20px;
    margin-left: 40px;
  }

  .green-box {
    background-color: green;
    margin-top: 40px;
    margin-right: 20px;
    margin-bottom: 20px;
    margin-left: 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by NYCSavage** [comment]
I am currently up to "Override Class Declarations by Styling ID Attributes" but according to my map it says the previous session as incomplete (despite completing them):

Add Different Margins to Each Side of an Element Incomplete

Use Clockwise Notation to Specify the Padding of an Element Complete

Use Clockwise Notation to Specify the Margin of an Element Complete

Style the HTML Body Element Incomplete

Inherit Styles from the Body Element Complete

Prioritize One Style Over Another Incomplete

Override Styles in Subsequent CSS Incomplete

Override Class Declarations by Styling ID Attributes Complete

Override Class Declarations with Inline Styles Incomplete

**Comment by NYCSavage** [comment]
I have just gone into each one again, clicked "Run tests" and then they are now marked as complete

**Comment by NYCSavage** [comment]
Forgot to mention, using a Macbook (early 2015 model) brand new out of the box and up to date with all software updates.

**Comment by sludge256** [comment]
This was probably due to the server maintenance and/or the server not being able to handle the high load during a usage peak. Feel free to reopen if the issue persists.

**Comment by jockeytcg** [comment]
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
 #orange-text{
    color:orange:
  }
  
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" >Hello World!</h1>
hello i can not seem to run test to get the orange -text on this code what could be the problem.
