### ISSUE TITLE
Waypoint: Make Object Properties Private- Not checking correctly 

### ISSUE THREAD

**Issue by SirSeanConnerie** [FreeCodeCamp/FreeCodeCamp#6817]
![image](https://cloud.githubusercontent.com/assets/16216332/12875018/bdde3476-cdae-11e5-9171-3ff1303f5b8f.png)

Tried asking on glitter but no response. When I test the code I can return 3 and 1 as required but it won't check as such.

Seems like a minor issue assuming I did nothing wrong.

**Comment by alistermada** [comment]
Your `setGear` function increments `gear` by the argument passed instead of setting it to the argument's value. Note: `gear` isn't reset to 0 by the time `myBike.setGear(3)` is called.
