### ISSUE TITLE
Challenges wont advance

### ISSUE THREAD

**Issue by kira8975** [FreeCodeCamp/FreeCodeCamp#6818]
Challenge [Increment a Number with Javascript](http://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar++;


```

Pretty much when i finish a challenge, it freezes on the popup window. Sometimes it may take 5 minutes, iother times it never advances and other times it just works.

**Comment by nickg33** [comment]
Chrome Version 47.0.2526.111 here, also experiencing similar issue.

**Comment by bugron** [comment]
@kira8975 @nickg33 this will be fixed now. Thanks for posting. Closing this issue. Feel free to reopen if you still experience problems, thanks.

**Comment by landonxjames** [comment]
I'm having the same issue.
Chrome version: 48.0.2564.116 (64-bit)

```
var myVar = 87;

// Only change code below this line
myVar = myVar++;
```
