### ISSUE TITLE
Mismatched error message for Font Size of an Element

### ISSUE THREAD

**Issue by ejg** [FreeCodeCamp/FreeCodeCamp#6819]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  p {
    font-size: 16px;
  }
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
Having `class="red-text"` on the second p tag gives the error message:
**Give elements with the p tag a font-size of 16px. Browser and Text zoom should be at 100%.
![screen shot 2016-02-07 at 7 12 11 pm](https://cloud.githubusercontent.com/assets/213104/12876345/e2902782-cdce-11e5-8bb5-8f1186470ad3.png)
**
I kept trying different zooms and browsers and code order and got the same message. If I change the second p tag to `<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>` the code passes.

It is confusing that the error message is about font size when the real problem is the color of the text.

**Comment by erictleung** [comment]
It appears that the last test is designed to test the new paragraph you added and assumes that there is no class added to it i.e. `<p>...</p>`. This challenge could be modified to either give instructions to make both paragraphs red text or specify that the new paragraph shouldn't have any classes added to it.

**Comment by sludge256** [comment]
The instructions do mention this
>Also, please do not add any extra classes to your new element.

The test text could use an update to better reflect the updated test, and perhaps the word "extra" could be omitted from the mentioned section of the instructions to prevent confusion.

**Comment by ankitaggarwal011** [comment]
I think removing the word "extra" and putting a break between two messages in Note would be enough.

It's also possible to split the last test case into two test cases, one asserting that no classes are attached with test p element and the other to assert the font size is as desired.

**Comment by ejg** [comment]
Just to clarify, the issue is not with the instructions for the exercise. The problem is the error message gives the error as the font-size instead of the class on the second p tag. 

Instead of the font-size message being highlighted as wrong, the second message should be marked wrong with some text like "Make sure each of your p elements has a closing tag and the correct classes".

**Comment by SaintPeter** [comment]
I think it probably makes sense to have two separate tests.  There needs to be a test that ensures that there exists at least one `p` element with no classes, prior to the one that checks the size, since that check is dependent on it not having a class.

**Comment by francisfrances** [comment]
hi everyone
im a newbie on here

i had probs with this question. my code as follows
![image](https://cloud.githubusercontent.com/assets/17091103/12904861/2bdfea48-ceca-11e5-9232-1e10a4b079e6.png)

i changed to explorer fm chrome and got green light no problem

hope this helps

**Comment by francisfrances** [comment]
currently i am refreshing the page and  flicking fm chrome to explorer as i keep getting 
![image](https://cloud.githubusercontent.com/assets/17091103/12905255/867fd794-cecd-11e5-8a14-4724170b0d11.png)
erroneously

**Comment by ankitaggarwal011** [comment]
@SaintPeter, yeah, I propose two changes with respect two this issue:

- Removing "extra" from note description.
- Splitting last test case into two test cases, one for checking whether the p tag has any classes and other checking for font size.

**Comment by SaintPeter** [comment]
@ankitaggarwal011 Sounds good.  Go for it!

**Comment by ankitaggarwal011** [comment]
@SaintPeter, opened a PR #6864. Have a look. Thanks!

**Comment by LeoDTLA** [comment]
@francisfrances thanks for sharing what you did about changing from Chrome to IE to be able to fix that issue, it did help.
