### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-an-ordered-list has an issue 

### ISSUE THREAD

**Issue by Chiouonthis** [FreeCodeCamp/freecodecamp#682]
On this challenge, as in a few other challenges, the green "Go to my next challenge" button is made available to click on BEFORE all steps are finished. In this particular example, I was able to trigger the box to become available before adding the closing </ol> tag. A similar error appeared in the previous exercise, where it did not require a closing </ul> tag before the user could move on.

**Comment by terakilobyte** [comment]
Thanks for this, it's been brought up many times. http://www.w3.org/TR/html5/syntax.html#optional-tags

We're looking at possibly using regex to validate the contents of the editor vs the contents of the DOM. Our tests right now only check the DOM, which browsers are *very* good at interpreting HTML, even seemingly incomplete HTML.
