### ISSUE TITLE
Seek and Destroy Challenge not accepting correct output.

### ISSUE THREAD

**Issue by jle3** [FreeCodeCamp/FreeCodeCamp#6821]
Challenge [Seek and Destroy](http://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20function%20comp%20(element%2C%20index%2C%20array)%7B%0A%20%20%20%20return%20element%20!%3D%3D%20this%3B%0A%20%20%7D%0A%20%20var%20result%20%3D%20arr%3B%0A%20%20var%20arg%20%3D%20arguments%3B%0A%20%20for(var%20i%20%3D%201%3B%20i%3Carg.length%3B%20i%2B%2B)%7B%0A%20%20%20%20console.log(i)%3B%0A%20%20%20%20result%20%3D%20result.filter(comp%2C%20arg%5Bi%5D)%3B%0A%20%20%7D%0A%20%20return%20result%3B%0A%7D%0A%0Adestroyer(%5B%22tree%22%2C%20%22hamburger%22%2C%2053%5D%2C%20%22tree%22%2C%2053)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  // Remove all the values
  function comp (element, index, array){
    return element !== this;
  }
  var result = arr;
  var arg = arguments;
  for(var i = 1; i<arg.length; i++){
    console.log(i);
    result = result.filter(comp, arg[i]);
  }
  return result;
}

destroyer(["tree", "hamburger", 53], "tree", 53);

```

im returning ["hamburger"] as requested in the last checkpoint but it's not being recognized? What am I missing?

**Comment by alistermada** [comment]
I'm not exactly sure why the console is returning `["hamburger"]`, but if you type in `console.log(this)` in your `comp()` function, you'll notice that it logs either a String object or a Number object. One of those JavaScript quirks of assigning a value to `this` I guess. You'll have to convert those objects to their primitive values.

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  As @alistermada say, please ask for help in [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!
