### ISSUE TITLE
Better wording for first paragraph - Create a custom heading bootstrap waypoint

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#6825]
Challenge [Create a Custom Heading](http://www.freecodecamp.com/challenges/create-a-custom-heading

First paragraph reads: "We will make a simple heading for our Cat Photo App by putting them in the same row."

Recommend changing to:

"We will make a simple heading for our Cat Photo App by putting the title and relaxing cat image in the same row."
```

**Comment by SaintPeter** [comment]
I agree, your proposed wording is clearer.
