### ISSUE TITLE
JavaScript Lingo: MDN and Documentation Question issue.

### ISSUE THREAD

**Issue by darrylpargeter** [FreeCodeCamp/FreeCodeCamp#6826]
Going though the new Video Challenge and question 3 on JavaScript Lingo MDN and Documentation doesn't seem to be there. Though clicking true answers it correctly, while false gives me the wrong answers animation.   

![screen shot 2016-02-08 at 12 50 34](https://cloud.githubusercontent.com/assets/10661000/12886093/f699494a-ce62-11e5-8e59-b71c96681e24.png)

**Comment by ltegman** [comment]
@SaintPeter Not sure if you're the right person to ask, but any idea what this question was supposed to be?

**Comment by SaintPeter** [comment]
It looks like it's a leftover from the templates I created.
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/04-video-challenges/jslingo.json#L31

@brianamarie Do you have a 3rd question here, or can you fix this one?
