### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue 

### ISSUE THREAD

**Issue by Chiouonthis** [FreeCodeCamp/freecodecamp#683]
Typing in: 
```
<button 
```
triggers the "Go to my next challenge" button to activate, instead of requiring a complete line of code, like:
```
  <button type="submit">Click to submit</button>
```

**Comment by terakilobyte** [comment]
Thanks, commit 3fbf84cf21843f04d5d2e5676b098517c60bdcea fixes this
