### ISSUE TITLE
Global variable error. 

### ISSUE THREAD

**Issue by rkingkeo** [FreeCodeCamp/FreeCodeCamp#6830]
Challenge [Global vs Local Scope in Functions](http://www.freecodecamp.com/challenges/global-vs-local-scope-in-functions#?solution=%2F%2F%20Setup%0Avar%20outerWear%20%3D%20%22T-Shirt%22%3B%0A%0Afunction%20myFunction()%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20outerWear%3D%22sweater%22%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20outerWear%3B%0A%7D%0A%0AmyFunction()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I did not change the global variable but the program  thinks I did. 

My code:
```javascript
// Setup
var outerWear = "T-Shirt";

function myFunction() {
  // Only change code below this line
  
  outerWear="sweater";
  
  // Only change code above this line
  return outerWear;
}

myFunction();

```

**Comment by raisedadead** [comment]
Yup Confirmed.

**Comment by raisedadead** [comment]
Sorry, my bad.

@rkingkeo Your code actually is incorrect:
```javascript
// Setup
var outerWear = "T-Shirt";

function myFunction() {
  // Only change code below this line

  outerWear="sweater";  // <<<<--------------------- this should be: var outerWear="sweater";

  // Only change code above this line
  return outerWear;
}

myFunction();
```

Please have a look at the example code, in the instruction.
You can further queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by rkingkeo** [comment]
Thank you. It might have just been the computer I was working on.

On Mon, Feb 8, 2016 at 1:45 PM, Mrugesh Mohapatra <notifications@github.com>
wrote:

> Sorry, my bad.
>
> @rkingkeo <https://github.com/rkingkeo> Your code actually is incorrect:
>
> // Setupvar outerWear = "T-Shirt";
> function myFunction() {
>   // Only change code below this line
>
>   outerWear="sweater";  // <<<<--------------------- this should be: var outerWear="sweater";
>
>   // Only change code above this line
>   return outerWear;
> }
> myFunction();
>
> Please have a look at the example code, in the instruction.
> You can further queries at Help Chat <https://gitter.im/FreeCodeCamp/Help>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6830#issuecomment-181487682>
> .
>



-- 
*Sam Kingkeo*

**Comment by praneethkumarpidugu** [comment]
Why is the Test is successful even without a semicolon for local variable ?

**Comment by anshuldawar** [comment]
@praneethkumarpidugu JavaScript (and libraries like jQuery) can run without semicolons thanks to a language feature called Automatic Semicolon Insertion. However I think FCC have chosen to teach all campers to use a consistent code-style. The reason is probably to simplify the learning and let new developers focus on the fundamentals, not details like if they should use semicolons or not.

If you want more information, there's some great videos on YouTube if you search for "semicolons JavaScript". I personally don't use semicolons in my own projects since the last month, but I'm contexts like FCC I try to follow their style guides.

Hope this helped! :)
