### ISSUE TITLE
JavaScript for loop multiple variable initialization not recognized.

### ISSUE THREAD

**Issue by revisualize** [FreeCodeCamp/FreeCodeCamp#6834]
Challenge [Iterate Through an Array with a For Loop](http://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afor%20(var%20i%20%3D%200%2C%20total%20%3D%200%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%20%7B%0A%20%20total%20%2B%3D%20myArr%5Bi%5D%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line

for (var i = 0, total = 0; i < myArr.length; i++) {
  total += myArr[i];
}

```

total should be declared and initialized to 0
total should equal 20
You should use a for loop to iterate through myArr
Do not set total to 20 directly

Within FOR loops you can initialize multiple variables at once during the "[initialization]" step. However, this exercise is not recognizing the multiple var assignment during the initialization process.

It appears to only recognize the definitive declaration of:
```javascript
var total = 0
```

**Comment by SaintPeter** [comment]
Look at you smart people with all your learnin'.  Think you're better 'n all of us!  You're a showoff, that's what it it.  :wink:

Nice solution, actually.

I think we could probably change the regex to specifically look for `total = 0`, dropping the `var` requirement.  The only downside there is that you could technically solve it without the `var` at all, which would be bad.

I'd like some opinions from the other @FreeCodeCamp/issue-moderators.

**Comment by hallaathrad** [comment]
I believe it should look for 'var total' somewhere, as an invisible requirement
