### ISSUE TITLE
Profile page redesign

### ISSUE THREAD

**Issue by nightwalkerkg** [FreeCodeCamp/FreeCodeCamp#6835]
Hey, i have been talking to @hallaathrad and we had an idea to do a new design for the profile page. 
So i set down and did a mock up. 
![](http://i.imgur.com/x9CxLTn.png)

The left side ( sidebar ) and the FCC activity board will be fixed, and only the challanges part of it would scroll. 
Any feedback is welcome on how we can improve it.

**Comment by revisualize** [comment]
Is there a mock up for Mobile Browsers?

**Comment by hallaathrad** [comment]
not quite yet, but it'd look much like the current one (at least for now)

**Comment by BerkeleyTrue** [comment]
Isn't there already an issue open on portfolio redesign?

**Comment by nightwalkerkg** [comment]
@BerkeleyTrue can you link it ?

**Comment by BerkeleyTrue** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5667

**Comment by nightwalkerkg** [comment]
@BerkeleyTrue ah, i didn't see this one at all. @hallaathrad if you want we can close this one and continue there ?

**Comment by hallaathrad** [comment]
Yes, let's do that, please. :) closing this one for that purpose.
