### ISSUE TITLE
Odd spacing between paragraphs and list

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#6840]
Challenge [Generate Random Whole Numbers with JavaScript](http://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function myFunction() {

  // Only change code below this line.

  return Math.random();
}

```

A UI issue, there are larger gaps before and after the ordered list compared to the vertical spaces between normal paragraphs.

**Oddity**:

![image](https://cloud.githubusercontent.com/assets/2754821/12907483/cc23aea6-cea0-11e5-951c-1dc615604ab8.png)

**Normal**:

![image](https://cloud.githubusercontent.com/assets/2754821/12907511/1bee6e1c-cea1-11e5-9199-baa3d69843c1.png)

**Comment by SaintPeter** [comment]
This sounds like a job for @hallaathrad!
