### ISSUE TITLE
Record Collection Challenge: When pushing an integer onto the tracks array you still pass the challenge.

### ISSUE THREAD

**Issue by grim6626** [FreeCodeCamp/FreeCodeCamp#6842]
Challenge [Record Collection](http://www.freecodecamp.com/challenges/record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20update(id%2C%20prop%2C%20value)%20%7B%0A%20%0A%20%20if%20(value%20%3D%3D%3D%20%22%22)%20%7B%0A%20%20%20delete%20collection%5Bid%5D%5Bprop%5D%3B%0A%20%20%7D%20else%20if%20%20(prop%20!%3D%3D%20%22tracks%22)%7B%0A%20%20%20collection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%7D%20else%20if%20(prop%20%3D%3D%3D%20%22tracks%22)%20%7B%0A%20%20%20collection%5Bid%5D%5Bprop%5D.push(%20value%20)%3B%0A%20%7D%20%0A%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0Aupdate(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function update(id, prop, value) {
 
  if (value === "") {
   delete collection[id][prop];
  } else if  (prop !== "tracks"){
   collection[id][prop] = value;
 } else if (prop === "tracks") {
   collection[id][prop].push( value );
 } 

  return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");


```
I've replaced value with several different integers in the collection[id][prop].push( value ); section of the code and they all pass the challenge.  I was trying to test to make sure I was pushing simple values onto the array when I passed unexpectedly.  Here is a screen image of it.

<img width="715" alt="screen shot 2016-02-08 at 10 52 35 pm" src="https://cloud.githubusercontent.com/assets/6686443/12908671/d1b928c6-ceb6-11e5-8015-25921d45bf5e.png">

**Comment by SaintPeter** [comment]
Confirmed.

It sounds like we need to include a test that also checks the actual value of the last track in `tracks` to ensure it was properly added.

**Comment by ankitaggarwal011** [comment]
@grim6626 @SaintPeter, this will not be limited to tracks, as one can hard-code the same in the function for non-tracks field as well. 

A corresponding check has to be made with tracks as well as non-tracks on whether they had been set properly.

**Comment by SaintPeter** [comment]
We do explicitly check that the value has been written for at least one case.  I would be amenable to adding another test, though.  Maybe adding a chase for changing an already set value.

**Comment by ankitaggarwal011** [comment]
@SaintPeter, Yes, the 3rd test-case for this challenge should be updated to check if the value is properly added to the tracks, similar to 1st test-case for artist.

I propose updating the 3rd test-case to check for added value in tracks similar to 1st test-case of artist.
Let me know.

**Comment by SaintPeter** [comment]
@ankitaggarwal011 Sounds good to me.

**Comment by ankitaggarwal011** [comment]
@SaintPeter, opened a PR with the changes, please have a look. Thanks!
