### ISSUE TITLE
Next challenge not loading from 109 even though previous challenge is successfull

### ISSUE THREAD

**Issue by amruthpolavarapu** [FreeCodeCamp/FreeCodeCamp#6844]

**Comment by AkiraLaine** [comment]
Hey @amruthpolavarapu What browser/OS are you using? Can you confirm that it still won't go to the next challenge?

Might be related to #6833

**Comment by amruthpolavarapu** [comment]
Google chrome @AkiraLaine

**Comment by AkiraLaine** [comment]
@amruthpolavarapu Will it still not go to the next challenge?

**Comment by amruthpolavarapu** [comment]
Nope. I am manually going to map and going to other challenges

**Comment by sludge256** [comment]
Is this happening for all challenges? What is the name of the challenge you labeled as #109?

**Comment by amruthpolavarapu** [comment]
Learn how Script Tags and Document Ready Work in jquery

**Comment by sludge256** [comment]
Are there are error messages showing up in the browser's console?

**Comment by amruthpolavarapu** [comment]
Just a sec. I will tell you

**Comment by amruthpolavarapu** [comment]
Refused to load the script 'http://10.226.35.8:15871/cgi-bin/blockpage.cgi?ws-session=1824636845' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' *.google-analytics.com *.gstatic.com https://*.cloudflare.com *.cloudflare.com https://*.gitter.im https://*.cdnjs.com *.cdnjs.com https://*.jsdelivr.com *.jsdelivr.com *.twimg.com https://*.twimg.com vimeo.com 'self'".

http://www.freecodecamp.com/completed-challenge/ Failed to load resource: the server responded with a status of 502 (Connection reset by peer)

**Comment by AkiraLaine** [comment]
Is that all?

**Comment by amruthpolavarapu** [comment]
Ya. This is the error shown in console application

**Comment by AkiraLaine** [comment]
@QuincyLarson @BerkeleyTrue - Could you guys look into this?

**Comment by sludge256** [comment]
Could you give this a try and report back?
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc

**Comment by amruthpolavarapu** [comment]
kk..

**Comment by amruthpolavarapu** [comment]
I am on my company's network. I am not able to install the plugin. I will let you know later.

**Comment by sludge256** [comment]
You should test submitting and loading the next challenge without the plugin first when you get home. If it's the case that it is your work network causing the problems you won't need the plugin when using FCC at home.

**Comment by amruthpolavarapu** [comment]
kk... Thanks for helping..

**Comment by AkiraLaine** [comment]
@amruthpolavarapu Did Browsec work for you?

**Comment by amruthpolavarapu** [comment]
It worked on my home computer without browsec but I am not supposed to install browsec on my company computer. But I believe it will work.

**Comment by AkiraLaine** [comment]
Ok, since it seems that your work connection is the problem, I will close this.

**Comment by tusharacc** [comment]
This issue is still persisting for me. I am using Chrome.Even though I have completed my challenge, I am not getting the challenge # 110. Attached is the error from console.
![image](https://cloud.githubusercontent.com/assets/15858037/12942688/f27949fe-d002-11e5-8eec-a3ce030cf290.png)

**Comment by SaintPeter** [comment]
@tusharacc Did you try https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc ?

Indian ISPs have significant issues with monitoring and modifying web traffic, which is probably why you're seeing the CSP violations - the responses are not coming from valid sites.
