### ISSUE TITLE
Hotkey and other productivity suggestions

### ISSUE THREAD

**Issue by rawreef** [FreeCodeCamp/FreeCodeCamp#6845]
I'd like to maintain a list of suggested hotkeys and other productivity suggestions here (if a Github issue is a good platform for doing that - I'm new to this so I don't know yet.) Please post your suggestions below.

FCC already has some hotkeys:

**GENERAL**
g -> c = go to chat / close chat
g -> m = go to map / close map
Any others???

**IN TEXT EDITOR**
cmd + x = delete line (just like in Sublime Text/Atom/Codepen - not sure about Windows shortcut. Maybe ctrl + x?)
Emmet-style auto-expansions
Any others???

Here are a few other suggestions:

**GENERAL**
g -> s = go to search box in map (and be able to start typing straightaway)

**IN TEXT EDITOR**
cmd + enter = create new line below current line (ctrl + enter on Windows?)
It would be great to take the top 20% of hotkeys from Sublime Text/Codepen/Atom that probably provide 80% of hotkey productivity and use them in the FCC text editor. 

Can anyone else think what that other top 20% of hotkeys should include?

**GENERAL PRODUCTIVITY**
Add a formatted link to the current challenge to the clipboard, so users can quickly paste something like this -- Headline with the h2 Element -- to the help chat.

**Comment by alistermada** [comment]
Suggestions:

* Open/close help chat. Was gonna suggest <kbd>ctrl</kbd> + <kbd>h</kbd>, but that opens up the browsing history tab on Chrome. <kbd>g</kbd> + <kbd>h</kbd> wouldn't work in the text editor.

* Add a formatted link to the current challenge to the clipboard,  so users can quickly paste something like this -- [Headline with the h2 Element](http://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3C!--Hello%2C%20I%20am%20user%20code!--%3E) -- to the help chat.

* Copy as "pretty code". There used to be a tool-tip that gave users an option to copy the code they highlighted as a Markdown-formatted code block depending on the challenge they were on. Users could easily copy their code and paste something this:
```html
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<!--Hello, I am user code!-->
```

Not really sure what buttons to use for those shortcuts.

**Comment by rawreef** [comment]
"Open/close help chat. Was gonna suggest ctrl + h, but that opens up the browsing history tab on Chrome. g + h wouldn't work in the text editor."
>> Would be nice to use g + h, to keep things consistent. So how about a hotkey to come out of the editor first? esc?

"Copy as "pretty code". There used to be a tool-tip that gave users an option to copy the code they highlighted as a Markdown-formatted code block depending on the challenge they were on. Users could easily copy their code and paste something this..."
>> I noticed some problems with that tooltip getting in the way for me, which is probably why it got removed. Would a hotkey combination like cmd/ctrl + c, p, c (Copy Pretty Code) work for this?

**Comment by SaintPeter** [comment]
RE:  g -> s for Search
When you open the map the search field has focus by default.

RE: Formatted Link/Code
This is something we had before, but the UI was horrible.  We definitely plan to revisit it.

**Comment by alistermada** [comment]
> So how about a hotkey to come out of the editor first? esc?

Sounds good to me.

> Would a hotkey combination like cmd/ctrl + c, p, c (Copy Pretty Code) work for this?

I'm not in favor of pressing a button twice in one hotkey. Perhaps we could include the Shift and/or Alt key.

**Comment by SaintPeter** [comment]
One thing we need to consider is discover-ability.  It's all fine and dandy to add a bunch of keyboard shortcuts, but unless we can clearly communicate them to the user, they're not much good.

One thing we have queued up is changing around where the "Run Tests" and other buttons are located.  Once we have more room we can add a "Copy Pretty Code" button.  We could potentially have some sort of "Keyboard Shortcuts" pop-up.

Note that we use CodeMirror as our editor, so we are limited by its capabilities (and features).

**Comment by sahat** [comment]
These are all great suggestions.


@SaintPeter In addition to Keyboard Shortcuts popup, I would also like to chime in and suggest adding a `title` attribute on all applicable buttons that would display a keyboard shortcut on mouse over.

**Comment by TheProjectMarch** [comment]
I would love to see the ability to wrap selected code with other elements via a single selector or an emmet string. Sublime uses `ctrl + shift + g` for this and it's awesome. 

![image](https://cloud.githubusercontent.com/assets/11678851/13967967/5087ad0c-f050-11e5-8a14-b5a567a0fe23.png)

![image](https://cloud.githubusercontent.com/assets/11678851/13968009/8aac8e62-f050-11e5-9114-1846fdce0623.png)

I would love you forever and ever cross my heart.

**Comment by QuincyLarson** [comment]
@rawreef the best place to maintain this list would be on our forum: https://forum.freecodecamp.com/t/free-code-camp-hotkeys/59467

**Comment by rawreef** [comment]
Thanks for the link. 👍
