### ISSUE TITLE
Shop tab not showing

### ISSUE THREAD

**Issue by CEREBR4L** [FreeCodeCamp/FreeCodeCamp#6846]
The shop tab is not showing when on 'jobs' section. 

Screenshot: https://i.gyazo.com/86857d88035748ffd225924e32d40f8f.png

**Comment by alistermada** [comment]
There seems to be a fix for it already: [here](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6804). It just hasn't been applied to the site yet.

**Comment by AkiraLaine** [comment]
Thanks @alistermada! Closing this as it has been resolved.
