### ISSUE TITLE
Target the Parent of an Element Using jQuery waypoint - passed without using parent()

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#6847]
Challenge [Target the Parent of an Element Using jQuery]

I can pass this waypoint without targeting the #target1 parent, like this:
    $("#left-well").css("background-color", "red");

i.e. without using the parent() method.

**Comment by richyvk** [comment]
Now I can't. Don't know what's going on??

**Comment by AkiraLaine** [comment]
Hey @richyvk! 
Can you confirm that you can pass the challenge without using ```.parent()```? Or can't you pass?

**Comment by richyvk** [comment]
Couldn't recreate issue.
