### ISSUE TITLE
Seek help

### ISSUE THREAD

**Issue by annzach** [FreeCodeCamp/FreeCodeCamp#6852]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=%0A%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20%2F%2Fvar%20count%3D0%3B%0A%0A%20%20%20if(card%20%3D%3D%207%7C%7C8%7C%7C9)%7B%0A%20%20%20%20%20%20count%3D0%3B%0A%20%20%20%20%20%20return%20count%20%2B%22%20Hold%22%3B%7D%0A%20%20%20%20%20%0A%20%20%20%20if(card%20%3D%3D%202%7C%7C3%7C%7C4%7C%7C5%7C%7C6)%7B%0A%20%20%20%20count%2B%2B%3B%0A%20%20%20%20return%20count%20%2B%22%20Bet%22%3B%20%7D%0A%20%20%0A%20if(card%20%3D%3D%2010%7C%7C'J'%7C%7C'Q'%7C%7C'K'%7C%7C'A')%7B%0A%20%20%20%20%20--count%3B%0A%20%20%20%20%20return%20count%2B%22%20Hold%22%3B%7D%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%0A%7D%0A%0A%20%20%0A%20%20%0A%20%0A%20%20%0A%20%20%20%20%0A%20%20%2F%2Fif%20%0A%0A%0A%20%20%20%20%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2Freturn%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0A%2F%2Fcc(7)%3B%20cc(8)%3B%20cc(9)%3B%20%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


var count = 0;

function cc(card) {

  // Only change code below this line
   //var count=0;

   if(card == 7||8||9){
      count=0;
      return count +" Hold";}
     
    if(card == 2||3||4||5||6){
    count++;
    return count +" Bet"; }
  
 if(card == 10||'J'||'Q'||'K'||'A'){
     --count;
     return count+" Hold";}
    
    
    
}

  
  
 
  
    
  //if 


      
  
  
  
  //return "Change Me";
  // Only change code above this line


// Add/remove calls to test your function.
// Note: Only the last will display
//cc(7); cc(8); cc(9); 

```

**Comment by annzach** [comment]
can some one tell me why is this code not working?

**Comment by johncurcio** [comment]
Not sure about javascript, but you usually can't do this: ``if (card == 7||8||9)``, you have to write ``if ((card == 7) || (card == 8)...)``, so on. The first if will always evaluate as true, because you'd have a ``if (8)``.

**Comment by SaintPeter** [comment]
Sorry, but Issues are not for code problems.  Please ask for help in [Help JavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and Happy Coding!

**Comment by Bleebler** [comment]
Use some case statements in there instead.
