### ISSUE TITLE
Record Collection JSON object task - http://www.freecodecamp.com/challenges/record-collection

### ISSUE THREAD

**Issue by timpwbaker** [FreeCodeCamp/FreeCodeCamp#6853]
I have searched for a solution to this, but can't find anything. The issue is on http://www.freecodecamp.com/challenges/record-collection

When I run my code it fails the test:
"After update(5439, "artist", "ABBA"), artist should be "ABBA"

However as can be seen from the screenshot of the Firebug Object for object 5439 the artist is "ABBA" and the correct output is being displayed in the output box. 

![screen shot 2016-02-09 at 22 16 10](https://cloud.githubusercontent.com/assets/8363245/12932543/422555f2-cf7b-11e5-80c4-2036687140a3.png)

-------------
Full code:

// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests

// Only change code below this line
function update(id, prop, value) {
 if (value !== "" && prop !== "tracks") {
   collection[id][prop] = value;
 }
 else if (value !== "" && prop === "tracks") {
   collection[id][prop].push(value);
 }
 else if (value === "") {
   delete collection[id][prop];
 }
   return collection;
}

// Alter values below to test your code
update(5439, "artist", "ABBA");

**Comment by SaintPeter** [comment]
It looks like you deleted some required code:
```js
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));
```
I don't know why you got rid of that, but it breaks all of the tests, which are defendant on the copy being present.

You should be able to copy the part of the code you write, reset the code, and paste yours in.  I confirmed that your code DOES pass all tests when the `collectionCopy` variable is properly initialized.

Thanks and happy coding!

**Comment by timpwbaker** [comment]
Thanks Peter! Not sure how I managed that.
