### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue 

### ISSUE THREAD

**Issue by randyleighton** [FreeCodeCamp/freecodecamp#686]
The test shows:
Wrap your image element inside an anchor element that has its href attribute set to "#".to.equal(1);

It also passes when you create <a>, does not include the < a href="#">

**Comment by terakilobyte** [comment]
Commit f6cebdea2755768d20731f281517980c9fc08bae fixes this, thanks!
