### ISSUE TITLE
Numbers too large for debugging

### ISSUE THREAD

**Issue by clarkarnold** [FreeCodeCamp/FreeCodeCamp#6866]
Challenge [Sum All Odd Fibonacci Numbers](http://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=function%20sumFibs(num)%20%7B%0A%20%20var%20currentNum%20%3D%201%3B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%3D0%3B%20i%3C%3Dnum%3B%20i%2B%2B)%20%7B%0A%20%20%20%20var%20nextNum%20%3D%20i%20%2B%20currentNum%3B%0A%20%20%20%20arr.push(nextNum)%3B%0A%20%20%7D%0A%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0AsumFibs(4)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sumFibs(num) {
  var currentNum = 1;
  var arr = [];
  for (var i=0; i<=num; i++) {
    var nextNum = i + currentNum;
    arr.push(nextNum);
  }

  
  return arr;
}

sumFibs(4);

```

While testing and debugging this challenge it continues to crash my browser.  The numbers for the tests should be smaller so it doesn't have to run the code 400000 times if it is buggy, which it probably is.

**Comment by ltegman** [comment]
If you don't want to test the large numbers I'd recommend using something like [repl.it](https://repl.it/) and only running the tests you want to. Part of the challenge of this exercise is making sure you can efficiently calculate the result for a number that large, so we will not be removing that test. Thanks and happy coding!
