### ISSUE TITLE
my code is correct and I followed the directions. I cannot complete this challenge for greater than

### ISSUE THREAD

**Issue by kilik42** [FreeCodeCamp/FreeCodeCamp#6867]
Challenge [Comparison with the Greater Than Operator](http://www.freecodecamp.com/challenges/comparison-with-the-greater-than-operator#?solution=function%20myTest(val)%20%7B%0A%20%20if%20(val%20%3E%209)%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Over%20100%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(val%20%3E%208)%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Over%2010%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20%2210%20or%20Under%22%3B%0A%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(11)%3B%0A%2F%2FmyTest(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  if (val > 9) {  // Change this line
    return "Over 100";
  }
  
  if (val > 8) {  // Change this line
    return "Over 10";
  }
  
  return "10 or Under";
  
}

// Change this value to test
myTest(11);
//myTest(10);

```

**Comment by ltegman** [comment]
This solution is not correct. Please reread the question carefully and visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need help. Thanks and happy coding!
