### ISSUE TITLE
Smallest Common Multiple: Returning correct answer, but not receiving a check next to the test for [1,13]

### ISSUE THREAD

**Issue by hey-its-iota** [FreeCodeCamp/FreeCodeCamp#6869]
```
var primes = [2, 3, 5, 7, 11, 13, 17, 19, 23.../TRUNCATED HERE AS THIS LIST CONTAINS ALL PRIMES UP TO 10,000...];

//this function takes a number and returns an array containing its prime factors or a 1 if it has none.
function pFact(n) {
  var factArr = [];
  var i = 0;
  while (n > 0) {
    while (i < primes.length) {
      if (n % primes[i] === 0) {
        factArr.push(primes[i]);
        n = n / primes[i];
        i = 0;
      } else {
        i++;
      }

    }
    factArr.push(1);
    break;
  }
  return factArr;
}



function smallestCommons(arr) {
  var primeFacts = [];
  var nums = [];
  var result = 1;
  var temp;
  var expoArr = [];

  var min = arr[0];
  var max = arr[1];

  if (min > max) {
    min = arr[1];
    max = arr[0];
  }
  //generate list of numbers
  for (var i = min; i <= max; i++) {
    nums.push(i);
  }

  //run through each number and find the prime factors of each
  //save the results in the primeFacts array as sub arrays.
  for (i = 0; i < nums.length; i++) {
    primeFacts.push(pFact(nums[i]));
  }

  //find the largest prime in the primeFacts array
  
  for (i = 0; i < primeFacts.length; i++) {
    max = 0;
    temp = primeFacts[i];
    for (var j = 0; j < temp.length; j++) {
      max = Math.max(max, temp[j]);
    }
  }
  //chop down the list of primes using the largest prime
  temp = primes.indexOf(max) + 1;
  primes = primes.slice(0, temp);

  //run through the now shortened primes list and find the max
  //number of times each prime is used in any given primeFacts 
  //sub array.  Save this in expoArr.

  for (i = 0; i < primes.length; i++) {
    expoArr[i] = 0;

    for (var j = 0; j < primeFacts.length; j++) {
      temp = primeFacts[j];
      var count = 0;
      for (var k = 0; k < temp.length; k++) {
        if (temp[k] === primes[i]) {
          count++;
        }
        if (count > expoArr[i]) {
          expoArr[i] = count;
        }
      }
    }
  }

  //multiply the result
  for(i = 0; i < primes.length; i++){
    temp = Math.pow(primes[i], expoArr[i]);
    result = result * temp; 
  }

  return result;

}

smallestCommons([1, 13]);
```
I'm not getting a check mark next to the test for 1, 13 when I run the above code.  I am, however, getting check marks next to the other tests.

So, this code doesn't seem to have a speed problem, since it uses the prime factorization method of finding the lowest common multiples, as opposed to brute forcing a large number of multiples until a common one is found.  Moreover, when I hit "Run Tests" I am getting the right returned values 360360 for [1,13] and 60 for [1,5].

What gives?

**Comment by alistermada** [comment]
Type in `console.log(arr, result, primes.length);` just before you return the results for `smallestCommons()`. Notice that primes.length is 0 by the time it gets to the results of the test for `smallestCommons([1, 13])`. 

Since primes is a global variable,  it doesn't get reset to its originally declared value every time `smallestCommons()` is run.

Note, that user-defined tests are run first and their results are what gets outputted to the console on the left. However, they are optional and their results don't determine whether or not the challenge will be passed, which is understandably confusing in this situation.

**Comment by hey-its-iota** [comment]
@alistermada Brilliant, thanks for that.  I hadn't considered that the FCC testing didn't re-initialize the program each time it ran a function call.  The fix turned out to be quite easy.
