### ISSUE TITLE
"Filter Arrays with filter" description needs clarification

### ISSUE THREAD

**Issue by jcubed22** [FreeCodeCamp/FreeCodeCamp#6871]
Challenge [Filter Arrays with filter](http://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%20%7B%0A%20%20return%20val%20%3C%3D%205%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
  return val <= 5;
});

```
I think it just needs more clarification on exactly what you mean by "filtering out," or what the end result should be.  To me, when you're talking about creating a new array with the .filter() method, it sounds like the items that end up in that new array are the items that are "filtered out."  How the filter works itself makes sense (as I was able to easily get the result I THOUGHT I was looking for, i.e. `newArray = [6, 7, 8, 9, 10]`) but I think your wording (i.e. which items are "kept" and which items are "filtered out") is confusing.

**Comment by SaintPeter** [comment]
I agree, this is potentially confusing.

I think it might be safe to say something like:
> `filter` returns a new array with all of the kept elements and none of the filtered out elements.

Do you think that would help?

**Comment by jamigibbs** [comment]
Does this bit below the example clear things up well enough? It seems like adding another explanation would be redundant.

> Use filter to filter out all elements from oldArray that are greater than 5 and store the results into newArray. oldArray should not change.

**Comment by taylorham** [comment]
I'm with @jamigibbs on this one. I just re-took this challenge and had to try 3 different ways to get the 'correct' result. I'd change the 'filter out' terminology, though. Adds confusion to what the result should actually be.

> Use filter to select only the elements from oldArray that are greater than 5 and store the results into newArray. oldArray should not change.

**Comment by SaintPeter** [comment]
How about:
> Use `filter` to create a new array with all the values from `oldArray` which are less than 6.  `oldArray` should not change.

I do agree that the `5` in there makes it a bit harder than it should be, because you assume that you need to use `5` in your filter which is not strictly speaking true.

**Comment by taylorham** [comment]
@SaintPeter This sounds like the best option. +1

**Comment by W12S12E12** [comment]
world press
https://vip.wordpress.com/documentation/code-review-what-we-look-for/

and and https://github.com/sk89q/craftbook/commit/709ab2520b125f6f91431b81c6352256d424a163
