### ISSUE TITLE
Cannot advance to the news task

### ISSUE THREAD

**Issue by biginjapan** [FreeCodeCamp/FreeCodeCamp#6872]
Challenge [Change the Color of Text](http://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%3Ch2%20style%3D%22color%3A%20blue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h2 style="color: blue">CatPhotoApp</h2>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by ltegman** [comment]
You are not completing what the challenge is asking you to. Github issues are not for help, so please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need assistance. Thanks and happy coding!

**Comment by W12S12E12** [comment]
https://www.ibm.com/developerworks/community/blogs/cloudview?sortby=0&maxresults=10&order=asc&lang=es
