### ISSUE TITLE
Should challenge.lastUpdated be added to the streak calculation?

### ISSUE THREAD

**Issue by LenaBarinova** [FreeCodeCamp/FreeCodeCamp#6876]
Since there is a new filed ```lastUpdated``` shouldn't it be added to streak calculation and to the calendar heatmap?

I could do it.

**Comment by SaintPeter** [comment]
I think we intended the streak to be for brownies.  We wouldn't, for example, want someone to just open up a previous challenge, add a useless comment, and save it again.

I'll defer to @QuincyLarson on this, though.

**Comment by sludge256** [comment]
I think we're also trying to discourage people from going back and spending too much time on their algorithms also.

**Comment by bugron** [comment]
cc @BerkeleyTrue.

**Comment by BerkeleyTrue** [comment]
Last updated shouldn't be used for streaks. It's there mostly to let people know we've actually updated the challenge.

@sludge256 Is also right, there is to much emphasize on challenges and not enough on projects.

**Comment by bugron** [comment]
Closing this issue then. @LenaBarinova thanks for posting.
