### ISSUE TITLE
Incorrect Video URL still "loads"

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6877]
If you put in an incorrect video URL you do not get redirected, nor do you get a flash message saying that the video is not found.  Instead you are taken to video display view with a video that never loads.

IE:
http://www.freecodecamp.com/videos/this-is-not-a-video

My expectation would be a redirect back to the map page with a flash message, if possible, same as a bad challenge link.

**Comment by NolanChan** [comment]
Which challenge is this in response to? Just want to look into it and see what I can do

**Comment by ahstro** [comment]
This looks fixed; the link redirects back go `/map`.

**Comment by SaintPeter** [comment]
Closing as resolved.
