### ISSUE TITLE
Test cases are returning the correct value in the console, but it won't let me pass the challenge

### ISSUE THREAD

**Issue by EthanDavis** [FreeCodeCamp/FreeCodeCamp#6880]
Challenge [Golf Code](http://www.freecodecamp.com/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20%20if(strokes%20%3D%3D%201)%7B%0A%20%20%20%20return%20%22Hole-in-one%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3C%3D%20par%20-2)%20%7B%0A%20%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%3D%20par%20-1%20)%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%3D%20par)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%3D%20par%20%2B%201)%7B%0A%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20%20%20%20%20%20%20%20%0A%20%20else%20if(strokes%20%3D%3D%3D%20par%20%2B%202)%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3E%3D%20par%20%2B%203)%7B%0A%20%20%20%20return%20%22Go%20Home!%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(1%2C%201)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
    if(strokes == 1){
    return "Hole-in-one";
  }
  else if(strokes <= par -2) {
     return "Eagle";
  }
  else if(strokes === par -1 ){
    return "Birdie";
  }
  else if(strokes === par) {
    return "Par";
  }
  else if(strokes === par + 1){
   return "Bogey";
  }        
  else if(strokes === par + 2){
    return "Double Bogey";
  }
  else if(strokes >= par + 3){
    return "Go Home!";
  }
  // Only change code above this line
}

// Change these values to test
golfScore(1, 1);

```

**Comment by mohannadsawalhi** [comment]
return "Hole-in-one!";

-!-

**Comment by alekasantos** [comment]
I have the same issue.

**Comment by alekasantos** [comment]
I found out the problem, the text in the return should match exaclty as mentioned by their text, for example, it should be Go Home!, not Go home
