### ISSUE TITLE
Johsthao

### ISSUE THREAD

**Issue by johsnguyen** [FreeCodeCamp/FreeCodeCamp#6881]
Challenge [Build JavaScript Objects](http://www.freecodecamp.com/challenges/build-javascript-objects#?solution=%2F%2F%20Example%0Avar%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myDog%20%3D%20%7B%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%7D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.0; E2312 Build/26.1.B.2.147) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.27 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"]
};

// Only change code below this line.

var myDog = {
  
  
  
  
};

```

**Comment by AkiraLaine** [comment]
Hey @johsnguyen. If you need help, please go over to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) room. GitHub is for issues only :smile:
