### ISSUE TITLE
Tests should be stricter for "Counting Cards" challenge

### ISSUE THREAD

**Issue by devarsh1997** [FreeCodeCamp/FreeCodeCamp#6884]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%20%2B%3D%201%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20count%20%3D%200%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20'J'%3A%0A%20%20%20%20case%20'Q'%3A%0A%20%20%20%20case%20'K'%3A%0A%20%20%20%20case%20'A'%3A%0A%20%20%20%20%20%20count%20-%3D%201%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20if(count%20%3D%3D%205)%7B%0A%20%20%20%20return%20%225%20Bet%22%3B%0A%20%20%7D%0A%20%20%0A%20%20else%20if%20(count%20%3D%3D%3D%200)%7B%0A%20%20%20%20return%20%220%20Hold%22%3B%0A%20%20%7D%0A%20%20%0A%20%20else%20if%20(count%20%3D%3D%20-5)%7B%0A%20%20%20%20return%20%22-5%20Hold%22%3B%0A%20%20%7D%0A%20%20%0A%20%20else%7B%0A%20%20%20%20return%20%22-1%20Hold%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count += 1;
      break;
    case 7:
    case 8:
    case 9:
      count = 0;
      break;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count -= 1;
      break;
  }
  
  if(count == 5){
    return "5 Bet";
  }
  
  else if (count === 0){
    return "0 Hold";
  }
  
  else if (count == -5){
    return "-5 Hold";
  }
  
  else{
    return "-1 Hold";
  }
  
  
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

I don't understand how my code solves the problem. Yet it solves all the challenges required to pass the waypoint. I sort of gamed it. I don't believe my code is right. So this waypoint is probably bugged and needs to be reframed. What do you think, guys?

**Comment by AkiraLaine** [comment]
Yes, I agree - your code shouldn't pass. 
1. For cases 7, 8 and 9, you are setting ```count``` to 0 instead of increment it by 0. 
2. Also, even if the ```if/else``` are techniacally right, that's not what the challenges asks you to do.

The tests should be modified to be a bit strict.

What do you guys think @FreeCodeCamp/issue-moderators?

**Comment by alistermada** [comment]
This seems to be related to #6761.

**Comment by W12S12E12** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp

**Comment by ltegman** [comment]
Closing as a duplicate of #6761. Thanks and happy coding!
