### ISSUE TITLE
Freecodecamp CSS style colour selection is having some problem.

### ISSUE THREAD

**Issue by Sarkar121** [FreeCodeCamp/FreeCodeCamp#6885]
Challenge [Use CSS Selectors to Style Elements](http://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%20%20%20%20%20%20%20%20%20%20%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
   h2 {color: blue;}
          </style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by AkiraLaine** [comment]
This is not a bug. You removed the ```h2``` element from your code.

Click "Reset" to reset you code and try again :smile:

**Comment by W12S12E12** [comment]
https://github.com/bobchao/code-standards/blob/master/index.html

**Comment by machhi08** [comment]
hello

**Comment by machhi08** [comment]
Challenge Use CSS Selectors to Style Elements has an issue.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My Code:

<style>
  h2 {color: red;} CatPhotoApp
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

Thanks

**Comment by theflametrooper** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
