### ISSUE TITLE
escape sequences

### ISSUE THREAD

**Issue by ashokget** [FreeCodeCamp/FreeCodeCamp#6886]
Challenge [Escape Sequences in Strings](http://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStr%20%3D%20%22%20%20%5C%5Cbackslash%5C%5C%20%5C%20%5Cttab%5Ct%20%5C%20%5Cttab%5Ct%20%5C%20%5Crcarriage-return%5Cr%20%5C%20%5Cnnew-line%5Cn%20%20%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "  \\backslash\\ \ \ttab\t \ \ttab\t \ \rcarriage-return\r \ \nnew-line\n  "; // Change this line



```

**Comment by AkiraLaine** [comment]
Hey @ashokget. If you need help, please go over to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) room. GitHub is for issues only :smile:

**Comment by W12S12E12** [comment]
one of http://stackoverflow.com/questions/9738088/automatic-html-escape-sequences-conversion-from-design-view-to-code-view?answertab=votes

and https://github.com/monw3c/qwrap/commit/3131eebc1fdb7c176a713a9fd54edd90b347215b
