### ISSUE TITLE
An idea to improve 'Add New Properties to a JavaScript Object' Challenge

### ISSUE THREAD

**Issue by devarsh1997** [FreeCodeCamp/FreeCodeCamp#6887]
Challenge [Add New Properties to a JavaScript Object](http://www.freecodecamp.com/challenges/add-new-properties-to-a-javascript-object#?solution=%2F%2F%20Example%0Avar%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%0A%7D%3B%0A%0AourDog.bark%20%3D%20%22bow-wow%22%3B%0A%0A%2F%2F%20Setup%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Happy%20Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyDog.bark%20%3D%20%22woof%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"]
};

ourDog.bark = "bow-wow";

// Setup
var myDog = {
  "name": "Happy Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["Free Code Camp Campers"]
};

// Only change code below this line.
myDog.bark = "woof";

```
This challenge can be solved by either adding "bark" property by dot **or** bracket notation. This challenge can be improved by making learner practise both the notations. Thus, learner has experience of solving through both the means before advancing forward. What do you think @FreeCodeCamp/issue-moderators ?

**Comment by ltegman** [comment]
We already have lessons on both notations before this and I don't relish adding even more challenges that force specific syntax. I'll leave this open for discussion, but I personally think it's fine as-is.

**Comment by SaintPeter** [comment]
This is actually an interesting idea.  We could have one property without a space and one with a space and let the user know they need to add it with the appropriate notation . . .

**Comment by devarsh1997** [comment]
That sounds great @SaintPeter and exactly what I intend. Improve challenge not add a completely new challenge as its probably not worth it as @ltegman says.

**Comment by bugron** [comment]
Agreed with @ltegman. Closing. @devarsh1997, @SaintPeter feel free to reopen, @devarsh1997 thanks for posting.
