### ISSUE TITLE
Help! I am Stuck, Thank you.

### ISSUE THREAD

**Issue by adhikarinetwork** [FreeCodeCamp/FreeCodeCamp#6892]

**Comment by raisedadead** [comment]
Please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help), GitHub Issues are for bugs in the site only.

Duplicate of #6893

**Comment by W12S12E12** [comment]
yes yes yes in here http://www.codeproject.com/Articles/20574/Open-Source-QRCode-Library
