### ISSUE TITLE
Help! Convert Celsius to Fahrenheit, Thank you.

### ISSUE THREAD

**Issue by adhikarinetwork** [FreeCodeCamp/FreeCodeCamp#6893]
Challenge [Convert Celsius to Fahrenheit](http://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=function%20convert(celsius)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20if%20(%20typeof%20fahrenheit%20!%3D%3D%20'undefined'%20)%20%7B%0A%20%20%20%20return%20fahrenheit%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20'fahrenheit%20not%20defined'%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0Aconvert(30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(celsius) {
  // Only change code below this line
  

  // Only change code above this line
  if ( typeof fahrenheit !== 'undefined' ) {
    return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(30);

```

**Comment by raisedadead** [comment]
@adhikarinetwork Please ask your queries at [Help Chat](https://gitter.im/FreeCodeCamp/Help), GitHub Issues are for bugs in the site only.

**Comment by adhikarinetwork** [comment]
I think its bug.

**Comment by raisedadead** [comment]
@adhikarinetwork IMHO, your code is just returning string messages, which is not the objective. 
Please read through the instructions and look at the test cases:

> You are given a variable celsius representing a temperature in Celsius. Create a variable fahrenheit and apply the algorithm to assign it the corresponding temperature in Fahrenheit.

You need to convert temperature (in Celsius to Fahrenheit).

If you are stuck ask for help in our [Help Chat](https://gitter.im/FreeCodeCamp/Help).
Thanks.

**Comment by hey-its-iota** [comment]
You haven't added any code to solve this problem... Notice the problem says:
```
  // Only change code below this line


  // Only change code above this line
```
So what you need to do is fill in some code between the lines.  Presumably this would mean declaring a variable `fahrenheit`.  And then do some calculations on the input `celsius` and save the result as `fahrenheit`.  If you search google, you will find the formula for converting celsius to fahrenheit, and all you need to do is implement it in code.

This portion of the code:
```
  if ( typeof fahrenheit !== 'undefined' ) {
    return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}
```
will just return the value of `fahrenheit` if it has any or will return a "not defined" statement if you happened to have left `fahrenheit` undefined.

**Comment by W12S12E12** [comment]
also in ubuntu use http://askubuntu.com/questions/226994/converting-celsius-processor-temperature-to-fahrenheit

**Comment by ltegman** [comment]
Closing as not a site issue.
