### ISSUE TITLE
Friendly Date parameter and return value data type

### ISSUE THREAD

**Issue by dbender** [FreeCodeCamp/FreeCodeCamp#6894]
Challenge [Friendly Date Ranges](http://www.freecodecamp.com/challenges/friendly-date-ranges#?solution=function%20friendly(str)%20%7B%0A%20%20return%20str%3B%0A%7D%0A%0Afriendly(%5B'2016-07-01'%2C%20'2016-07-04'%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function friendly(str) {
  return str;
}

friendly(['2016-07-01', '2016-07-04']);

```
The function friendly() takes an array as its parameter and returns an array (based on the examples and test cases you show). But the boilerplate function you start us with uses the variable 'str' for both. That's misleading; I would recommend 'arr' instead.

**Comment by byrass** [comment]
I agree, seems like an easy fix
