### ISSUE TITLE
Concatenating Strings with Plus Operator Doesn't Work 

### ISSUE THREAD

**Issue by manju4ever** [FreeCodeCamp/FreeCodeCamp#6895]
Challenge [Concatenating Strings with Plus Operator](http://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = 'This is the start. ' + 'This is the end.';
```

**Comment by jamigibbs** [comment]
Are you getting a specific error or is a particular test not passing? I'm able to get this to pass.

**Comment by manju4ever** [comment]
Okay my bad. Sorry for the trouble. Did not read the instructions properly.

**Comment by W12S12E12** [comment]
https://sourceforge.net/p/glew/bugs/120/
