### ISSUE TITLE
Concatenating Strings with the Plus Equals Operator doesn't work

### ISSUE THREAD

**Issue by manju4ever** [FreeCodeCamp/FreeCodeCamp#6896]
Challenge [Concatenating Strings with the Plus Equals Operator](http://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=var%20myStr%20%3D%20%22This%20is%20the%20first%20sentence.%22%3B%0A%0AmyStr%2B%3D%22%20This%20is%20the%20second%20sentence.%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "This is the first sentence.";

myStr+=" This is the second sentence.";
```

**Comment by jamigibbs** [comment]
When the example code is removed, the test fails even if the solution is correct:

```
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";
```

If you Reset and then enter the solution directly below `// Only change code below this line`, it will pass.

**Comment by W12S12E12** [comment]
and also in here http://www.cnblogs.com/cbscan/articles/3540887.html

**Comment by manju4ever** [comment]
Okay my bad. Sorry for the trouble did not read the instructions properly.

**Comment by W12S12E12** [comment]
https://github.com/numbbbbb/the-swift-programming-language-in-chinese/commit/18a78500eab563d6766aa4fe35eb53fb1d14e1f8

**Comment by frogshelp** [comment]
i am on the same challenge right now and it did exactly as jamigibbs wrote  but before i came looking for help and yes it still does not pass the part for the mystr+= will but the upper one for the var myster does not pass is thier a bug in it

**Comment by ittoufiq** [comment]
var myStr = "This is the first sentence. " + "This is the second sentence.";
    myStr += "";

**Comment by osa9j** [comment]
<!DOCTYPE html>
<html>
<body>

<h1>JavaScript Operators</h1>

<p>The assignment operator += can concatenate strings.</p>

<p id="demo"></p>

<script>
var txt1 = "What a very ";
//Use the += operator at this line to add the word 'nice day'

document.getElementById("demo").innerHTML = txt1 += "What a very", and "nice day";
</script>

</body>
</html>
