### ISSUE TITLE
Constructing Strings with Variables doesn't work

### ISSUE THREAD

**Issue by manju4ever** [FreeCodeCamp/FreeCodeCamp#6897]
Challenge [Constructing Strings with Variables](http://www.freecodecamp.com/challenges/constructing-strings-with-variables#?solution=%2F%2F%20Example%0Avar%20ourName%20%3D%20%22Free%20Code%20Camp%22%3B%0Avar%20ourStr%20%3D%20%22Hello%2C%20our%20name%20is%20%22%20%2B%20ourName%20%2B%20%22%2C%20how%20are%20you%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myName%3B%0Avar%20myStr%3B%0A%0AmyName%20%3D%20%22Manjunath%22%3B%0A%0AmyStr%20%3D%20myName%20%2B%20%22%20Desappa%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName;
var myStr;

myName = "Manjunath";

myStr = myName + " Desappa";



```

**Comment by W12S12E12** [comment]
http://stackoverflow.com/questions/2310498/why-doesnt-strings-hashcode-cache-0?answertab=votes

**Comment by manju4ever** [comment]
My bad. Didn't read the instructions properly.

**Comment by W12S12E12** [comment]
https://github.com/1vasari/Lacuna-Web-Client-jQuery/pull/2/files
yes yes
