### ISSUE TITLE
Understand String Immutability - Test not passing

### ISSUE THREAD

**Issue by manju4ever** [FreeCodeCamp/FreeCodeCamp#6899]
Challenge [Understand String Immutability](http://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Amystr%20%3D%20%22Hello%20World%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myStr = "Jello World";

// Only change code below this line

mystr = "Hello World"; // Fix Me

![image](https://cloud.githubusercontent.com/assets/9355984/12980921/81787132-d104-11e5-9fff-000569384a55.png)

**Comment by W12S12E12** [comment]
you can find in  https://code.google.com/archive/

**Comment by jamigibbs** [comment]
Check your camel case in the variable name.

**Comment by jamigibbs** [comment]
I'd also like to recommend posting your questions first in the [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) chat room or the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) room.

**Comment by manju4ever** [comment]
Okay. I will triple check before i log anymore defects. Wrong timings and decisions made by  me. Thanks again.

**Comment by W12S12E12** [comment]
http://stackoverflow.com/questions/2222292/optimize-this-slow-linq-to-objects-query?answertab=active

**Comment by rojasmichael** [comment]
I had a bug with this. But I was able to pass by making it a array. Please see below

// Setup
var myStr = "Jello World";

// Only change code below this line


var myStr = "Hello World";
var myStr1 = ["Hello World"];

myStr1[0] = "H"; // Fix Me

**Comment by BEBEDYDY** [comment]
// Setup
var myStr = "Jello World";


// Only change code below this line
myStr = "Hello World";
 // Fix Me

here you go.
