### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/freecodecamp#690]
WIN7 64bit PRO SP1
Firefox 38.0.1
When opening the page, it doesn't let me click where I want. I wanted to finish the waypoint to have them all completed but when the page is loaded it doesn't let me change the text I want. If I type something somewhere.

If I type something where the cursor is at a time, then I can put the cursor where I want and finish the waypoint. See screenshot
![waypoint_check_radio_buttons_and_checkboxes_by_default_free_code_camp](https://cloud.githubusercontent.com/assets/11710334/7854183/48831706-0517-11e5-80bc-51b6d95a6344.png)

**Comment by terakilobyte** [comment]
Thanks, we'll continue looking into this issue as it can affect multiple challenges!

**Comment by Stiino0** [comment]
It probably will however I haven't tried any as I already done em all up untill jQuery!
