### ISSUE TITLE
Exercise check only first property in "Source"

### ISSUE THREAD

**Issue by Borlandfcsd** [FreeCodeCamp/FreeCodeCamp#6900]
Challenge [Where art thou](http://www.freecodecamp.com/challenges/where-art-thou#?solution=function%20where(collection%2C%20source)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20var%20result%20%3D%20%5B%5D%3B%0A%20%20arr%20%3D%20Object.keys(source)%3B%0A%20%20%0A%20%20for(i%20%3D%200%3B%20i%20%3C%20collection.length%3Bi%2B%2B)%7B%0A%20%20%20%20for(var%20prop%20in%20collection%5Bi%5D)%7B%0A%20%20%20%20%20%20if(arr.length%20%3D%3D%201)%7B%0A%20%20%20%20%20%20%20%20if%20(collection%5Bi%5D.hasOwnProperty(arr%5B0%5D))%7B%0A%20%20%20%20%20%20%20%20%20%20if(collection%5Bi%5D%5Bprop%5D%20%3D%3D%3D%20source%5Barr%5B0%5D%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20result.push(collection%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%20if(arr.length%20%3D%3D%202)%7B%0A%20%20%20%20%20%20%20%20if%20(collection%5Bi%5D.hasOwnProperty(arr%5B0%5D)%20%26%26%20collection%5Bi%5D.hasOwnProperty(arr%5B1%5D))%7B%0A%20%20%20%20%20%20%20%20%20%20if(collection%5Bi%5D%5Bprop%5D%20%3D%3D%3D%20source%5Barr%5B0%5D%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20result.push(collection%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%0A%20%20%7D%0A%20%20%2F%2F%20What's%20in%20a%20name%3F%0A%20%20return%20result%3B%0A%7D%0A%0Awhere(%5B%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D%2C%20%7B%20%22a%22%3A%201%2C%22c%22%3A3%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%2C%20%22c%22%3A%202%20%7D%5D%2C%20%7B%20%22a%22%3A%201%2C%20%22c%22%3A%202%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(collection, source) {
  var arr = [];
  var result = [];
  arr = Object.keys(source);
  
  for(i = 0; i < collection.length;i++){
    for(var prop in collection[i]){
      if(arr.length == 1){
        if (collection[i].hasOwnProperty(arr[0])){
          if(collection[i][prop] === source[arr[0]]){
             result.push(collection[i]);
         }
        }
      }
      else if(arr.length == 2){
        if (collection[i].hasOwnProperty(arr[0]) && collection[i].hasOwnProperty(arr[1])){
          if(collection[i][prop] === source[arr[0]]){
             result.push(collection[i]);
         }
        }
      }
    }  
  }
  // What's in a name?
  return result;
}

where([{ "a": 1, "b": 2 }, { "a": 1,"c":3}, { "a": 1, "b": 2, "c": 2 }], { "a": 1, "c": 2 });

```

![image](https://cloud.githubusercontent.com/assets/12087826/12982911/0ad2513a-d0f8-11e5-8278-0080cc2bb613.png)

My code must dosent work,because i dont check value property "c", but freecodecamp apply my code

**Comment by W12S12E12** [comment]
https://github.com/godghost/qingzhou/commit/d2a94fa71a16a3245a6487c61c4b83aa46a0544d

**Comment by ltegman** [comment]
Please describe in more detail what issue you are experiencing with this challenge.

**Comment by Borlandfcsd** [comment]
ltegman  my code have wrong,

**Comment by Borlandfcsd** [comment]
My code must dosent work,because i dont check  value property "c", but freecodecamp apply my code
