### ISSUE TITLE
Improve Javascript Challenges - Assignment operators +-/*

### ISSUE THREAD

**Issue by cragsify** [FreeCodeCamp/FreeCodeCamp#6902]
Instead of creating 4 challenges that teach you: 

+=, -=, /=, *=

Which is quite laborious and not interesting, there should instead be one challenge teaching you all four, or two challenges, teaching you +-, then /* respectively.

**Comment by AkiraLaine** [comment]
These could be simplified, but I'm not sure if it's necessary.

Thoughts @FreeCodeCamp/issue-moderators?

**Comment by bugron** [comment]
@SaintPeter this issue is yours. I agree with @cragsify that it would be better to have to challengs for `+-` and `/*`.

**Comment by SaintPeter** [comment]
We have made a deliberate decision, based on some research, to only teach a single thing per challenge.  This theoretically allows campers to get into a "flow" state and just bang through the challenges.  Also, as much as you may dislike it, you are much less likely to forget it or confuse the operators.

Thanks and Happy Coding!
