### ISSUE TITLE
Oops! Something went wrong. Please try again later

### ISSUE THREAD

**Issue by D-blaze** [FreeCodeCamp/FreeCodeCamp#6903]
I keep getting this error: "Oops! Something went wrong. Please try again later" when clicking on my map in Basic JavaScript. Also the site seems generally slow and has been for over a week.

Thanks

Dave

**Comment by ltegman** [comment]
We recently deployed an update to the site intended to resolve the speed issues, but it may cause temporary slowdowns while migration occurs. Closing as a duplicate of #6901. Thanks and happy coding!
