### ISSUE TITLE
I cannot go past this challenge, i have gotten help, but... nothing.

### ISSUE THREAD

**Issue by ronnie92** [FreeCodeCamp/FreeCodeCamp#6905]
Challenge [Declare JavaScript Variables](http://www.freecodecamp.com/challenges/declare-javascript-variables#?solution=%2F%2F%20Example%0Avar%20ourName%20%3D%20%22Free%20Code%20Camp%22%3B%0Avar%20myName%20%3D%20%22Ronnie%22%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourName = "Free Code Camp";
var myName = "Ronnie";
// Only change code below this line


```

**Comment by ltegman** [comment]
You should just be declaring the variable, not assigning anything to it. Thanks and happy coding!
