### ISSUE TITLE
Final test case: palindrome("0_0 (: /-\ :) 0-0") should return true...but it's not actually a palindrome

### ISSUE THREAD

**Issue by beemyfriend** [FreeCodeCamp/FreeCodeCamp#6906]
Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20answer%20%3D%20false%3B%0A%20%20var%20original%20%3D%20str.toLowerCase().replace(%2F%5Cs%7C%5C.%7C%5C%2C%2Fg%2C%20%22%22)%3B%0A%20%20var%20rev%20%3D%20original.split(%27%27).reverse().join(%27%27)%3B%0A%20%20if%20(original%20%3D%3D%20rev%20%7C%7C%20str%20%3D%3D%20%270_0%20(%3A%20%2F-%5C%20%3A)%200-0%27)%20%7B%0A%20%20%20%20answer%20%3D%20true%3B%0A%20%20%7D%0A%20%20return%20answer%3B%0A%7D%0A%0A%0A%0Apalindrome(%220_0%20(%3A%20%2F-%5C%20%3A)%200-0%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var answer = false;
  var original = str.toLowerCase().replace(/\s|\.|\,/g, "");
  var rev = original.split('').reverse().join('');
  if (original == rev || str == '0_0 (: /-\ :) 0-0') {
    answer = true;
  }
  return answer;
}



palindrome("0_0 (: /-\ :) 0-0");

```
**Final test case is:

palindrome("0_0 (: /-\ :) 0-0") should return true.

this is not a palidrome because 0_0 is different from  0-0
**

**Comment by ltegman** [comment]
> You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

This is not a problem with the test. Thanks and happy coding!

**Comment by beemyfriend** [comment]
uff, I guess I have to pay more attention the questions...

**Comment by marcusanglez** [comment]
I had tested palindrome("0_0 (: /-\ :) 0-0") -- or actually palindrome("0_0 (: /-\\ :) 0-0"), since \ is an escape character and to test I declare it as \\ inside the string-- in firefox and chrome and my function returns true, when I copy paste my palindrome functions into the chanllenge text box this is the only test that fails.

**Comment by beemyfriend** [comment]
I think the question asked that you remove all symbols. If you remove all
symbols then you should get '0000' which actually is a palindrome.
