### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue 

### ISSUE THREAD

**Issue by lickyourlips** [FreeCodeCamp/freecodecamp#691]
According to this waypoint's requirements, the green-box class should give the _top_ of elements _20px_ of margin. However, in practice it marks that value as incorrect, accepting a value of _40px_ instead.

**Comment by terakilobyte** [comment]
Thanks, closing this as a duplicate of #665
