### ISSUE TITLE
Video challenges : Map link redirects to "/map" instead of drawer

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#6910]
In the video challenges, the Map [link on the navbar](http://www.freecodecamp.com/videos/javascript-lingo-variables--camelcase) is redirecting to http://www.freecodecamp.com/map instead of opening the drawer as in other coding challenges.

**Comment by SaintPeter** [comment]
This is a known issue.  The Video challenges are done entirely in React and the rest of the site will be following soon.  We don't have the sidebar implemented in React yet.

**Comment by raisedadead** [comment]
Thanks for the clarification. :+1:

**Comment by theflametrooper** [comment]
**Normal Challenges:**

![](https://i.gyazo.com/ede57b62ba2b2c03ab39073417e8a3e6.gif)

**Hikes:**

![](https://i.gyazo.com/988ae95e7e447264f230cbb0fe862fcb.gif)
