### ISSUE TITLE
Misleading capitalization

### ISSUE THREAD

**Issue by adius** [FreeCodeCamp/FreeCodeCamp#6913]
Challenge [Caesars Cipher](http://www.freecodecamp.com/challenges/caesars-cipher#?solution=function%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20%0A%20%20return%20str.split('').map(char%20%3D%3E%20char.charCodeAt(0)%20%2B%2013)%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2538.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

You shouldn't write `String.charCodeAt()` because it makes it look like the method would be static class method,
but it is not. Only `String.fromCharCode()` is. So either you write `string.charCodeAt()`, or I think even better: `"a string".charCodeAt()`.

**Comment by ltegman** [comment]
This is how all our MDN links are formatted (https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/bonfireMDNlinks.js). I'd be open to changing these all to String.prototype.method, since that's actually correct. Thoughts, @FreeCodeCamp/issue-moderators?

**Comment by Greenheart** [comment]
I think `"a string".charCodeAt()` might be the best alternative

**Comment by bugron** [comment]
Agreed with @Greenheart and @adius. `"a string".charCodeAt()` is a good alternative.

**Comment by ltegman** [comment]
@bugron The MDN links are links to documentation. Obfuscating what documentation is being linked to behind 'friendly' syntax is doing a disservice to students. Part of programming is learning how to search docs. Knowing that the chatCodeAt method is a part of `String.prototype` is both correct and teaches the student how to search for information when it's not provided to them. Making up proprietary ways of linking to prototype methods is confusing and not helpful in the long run.
