### ISSUE TITLE
Not registering correct answer, regardless of what browser is used

### ISSUE THREAD

**Issue by AliMusa8790** [FreeCodeCamp/FreeCodeCamp#6916]
Challenge [Iterate Through an Array with a For Loop](http://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line
var total = 0;
for (a = 0; a < myArr.length; a++) {
  total += myArr[a];
}


```

**Comment by jamigibbs** [comment]
I can't replicate this. Which of the tests aren't passing for you?

**Comment by AliMusa8790** [comment]
I input:

var myTotal = 0;

for (var i = 0; i < myArr.length; i++) {
  myTotal += myArr[i];
} 

and it gives me an error, even though it seems correct, but it doesn't pass. I chatted in gitter about it and two people confirmed it should be working. However, the code you see now,

var total = 0;
for (a = 0; a < myArr.length; a++) {
  total += myArr[a];
}

works for some reason even though they're identical.

**Comment by jamigibbs** [comment]
The variable you're initializing should be called `total` and not `myTotal`.

**Comment by AliMusa8790** [comment]
Ah, makes sense. Sorry about that. Wasn't trying to use this as a help post. Genuinely thought there was an issue. Thank you.
