### ISSUE TITLE
Won't advance: Code indicates an erro

### ISSUE THREAD

**Issue by Sunady** [FreeCodeCamp/FreeCodeCamp#6918]
Challenge [Change the Color of Text](http://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Ch2%20style%3D%22color%3A%20red%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h2>CatPhotoApp</h2>
<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by jamigibbs** [comment]
Instead of adding another `h2` element, you should be modifying the existing one.

Before posting an issue, consider first (https://gitter.im/FreeCodeCamp/FreeCodeCamp) chat room. :)

**Comment by sludge256** [comment]
In this instance https://gitter.im/FreeCodeCamp/Help would be the most appropriate.
Each challenge has a help button that will point you to the right room depending on which section you're on. Thanks @jamigibbs
