### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-build-web-apps-with-express.js has an issue 

### ISSUE THREAD

**Issue by Anfz** [FreeCodeCamp/freecodecamp#692]
The steps to complete are: 
Complete "Hello World"

Complete "Juggling Async"

Complete "Time Server"

Complete "HTTP Collect"

Complete "Juggling Async"

Complete "Time Server"

I think these are wrong.  Shouldn't it be
![express](https://cloud.githubusercontent.com/assets/7759299/7855148/9dc3fcf8-0562-11e5-9b9b-b3b4e52e4e7d.png)

**Comment by terakilobyte** [comment]
Thanks, commit 268f58505075225d4d2953ccd1ebaf132ddd99c8 closes this.
