### ISSUE TITLE
Profile page is not displaying completed solutions correctly

### ISSUE THREAD

**Issue by revisualize** [freeCodeCamp/freeCodeCamp#6924]
The profile page isn't showing the completed Algorithms and Challenges correctly. It appears that there are Challenges (Old Waypoints) mixed in with the Algorithm (Old Bonfire) solutions.

Please see the screenshot below:
![capture](https://cloud.githubusercontent.com/assets/1588399/12995671/146e97d6-d0de-11e5-8280-f369ac47c6d4.PNG)

**Comment by revisualize** [comment]
Any update?

**Comment by revisualize** [comment]
Note: When I sign out of my profile it shows something completely different from what I see when signed in:

![screenshot from 2016-02-14 19 25 25](https://cloud.githubusercontent.com/assets/1588399/13039210/15e50bca-d351-11e5-9f2a-55d5ef0bd25c.png)

Also, the basic Challenges and Checkpoints are still mixed in with the Algorithm challenges.

**Comment by bugron** [comment]
@revisualize I think you've locked your profile that's why your challenges are hidden when you're logged out (if this is what you're trying to show on that screenshot).
![](http://i.imgur.com/U1tbPnL.png)
I'm going to ping @BerkeleyTrue about the mixed challenges.

**Comment by revisualize** [comment]
Look, I know that all of my challenges are hidden. That isn't the issue. I'm trying to show that I have over 30days of continuous activity.
Signed in I am currently seeing:
Longest Streak: 34 days   Current Streak: 34 days
However, signed out only shows:
Longest Streak: 12 days   Current Streak: 9 days
That is current as of 2016-02-18.

**Comment by raisedadead** [comment]
@revisualize Can you confirm that you still have the mixed challenges?
About the different streaks we have #7468 in discussion. Please feel free to carry it there.

**Comment by revisualize** [comment]
I can confirm that basic Challenges are still mixed in with the Algorithms on my profile page.

**Comment by revisualize** [comment]
At this time the issue is not resolved.

**Comment by revisualize** [comment]
@BerkeleyTrue @raisedadead This issue is not resolved and should not have been closed.

**Comment by QuincyLarson** [comment]
@revisualize @raisedadead have you had a chance to look at this recently? This is an issue we still want to fix. Would either of you be interested in taking a crack at it?

**Comment by raisedadead** [comment]
Nope. Unfortunately this is open. Tagging as Help Wanted. I might take a look once I get some time, but if any one is interested, please have a look.

**Comment by petrgazarov** [comment]
I'd be happy to take this one this week.

**Comment by raisedadead** [comment]
@petrgazarov thanks. do checkout the contributing guide and reach out on the contributors chat if you need any assisstance

**Comment by BerkeleyTrue** [comment]
Is this still in issue in staging? I changed the way the profile page pulls the meta information for a challenge.
