### ISSUE TITLE
Missing green check mark on video view

### ISSUE THREAD

**Issue by alistermada** [FreeCodeCamp/FreeCodeCamp#6929]
There's no green check mark in the view for this video challenge...
![image](https://cloud.githubusercontent.com/assets/12993334/13002391/b39b4de6-d1a0-11e5-87b7-8ad0629e29fc.png)

... even though I've completed it.
![image](https://cloud.githubusercontent.com/assets/12993334/13002405/d03a893a-d1a0-11e5-98f1-0e5bbf7a6d2d.png)

As I've mentioned in #6775 the views for video challenges aren't loaded from `showVideo.jade`.  
It seems the code for the green check marks would be placed here in `freecodecamp\common\app\routes\Hikes\components\Hike.jsx`:
![image](https://cloud.githubusercontent.com/assets/12993334/13002579/1a44cc2e-d1a2-11e5-91c8-b26b1b8242fb.png)

Of course, the view's gonna need access to the variable that states whether or not the challenge is completed

**Comment by NolanChan** [comment]
I'll look into this on Monday (2/22) but if anyone wants to look into this before, be my guest :)

**Comment by NolanChan** [comment]
@alistermada Can I ask where exactly it's not showing up?  I'm a bit confused...


<img width="1122" alt="screen shot 2016-02-26 at 2 04 52 pm" src="https://cloud.githubusercontent.com/assets/1487616/13366709/fa763b58-dc91-11e5-8e07-d488a2d4a437.png">

**Comment by alistermada** [comment]
@NolanChan In the [challenge's page itself](http://www.freecodecamp.com/videos/computer-basics-the-4-basic-parts-of-a-computer). The map correctly marks it complete, but there's no green check mark on the challenge's page similar to what's in other types of challenges:

 
![image](https://cloud.githubusercontent.com/assets/12993334/13372389/d6e2901e-dd73-11e5-9fe4-a518c6930ae2.png)
