### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-custom-heading has an issue 

### ISSUE THREAD

**Issue by lisandroalves** [FreeCodeCamp/freecodecamp#693]
There should be a link to open the 'Bootstrap's 12-column grid layout' image in full size. I had to right click and choose 'Open Image in a New Tab'.

**Comment by terakilobyte** [comment]
Thanks, commit e3fff3808e2cbcfe59345a9c78579f6b92cf9227 closes this.
