### ISSUE TITLE
"Seek and Destroy":Test cases remain in Red even though the output looks correct for each test case

### ISSUE THREAD

**Issue by diyachetak** [FreeCodeCamp/FreeCodeCamp#6931]
Challenge [Seek and Destroy](http://www.freecodecamp.com/challenges/seek-and-destroy#?solution=%0A%0A%0Afunction%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20%2F%2Freturn%20arguments.length%2B%22%20and%20%22%2Barr%3B%0A%20%20function%20remEq(val)%7B%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20if%20(val%20%3D%3D%3D%20this)%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%7D%20%0A%20%20var%20resultArr%3D%5B%5D%3B%0A%20%20%0A%20%20for%20(var%20i%3D1%3B%20i%3Carguments.length%3B%20i%2B%2B)%7B%0A%20%20resultArr%20%3D%20arr.filter(remEq%2Carguments%5Bi%5D)%3B%0A%20%20arr%20%3D%20resultArr%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0Adestroyer(%5B2%2C%203%2C5%2C2%5D%2C%202%2C%203%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript



function destroyer(arr) {
  // Remove all the values
  //return arguments.length+" and "+arr;
  function remEq(val){         
      if (val === this){
      return false;
        }
      else
        {
          return true;
        }
  } 
  var resultArr=[];
  
  for (var i=1; i<arguments.length; i++){
  resultArr = arr.filter(remEq,arguments[i]);
  arr = resultArr;
  }
  
  return arr;
}

destroyer([2, 3,5,2], 2, 3, 5);

```

**Comment by jamigibbs** [comment]
I think the main thing to consider with this challenge is that `arguments` is an (array-like object that you can use `.slice` method)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#Array-like_objects] on to get both the array we want to sort and the sorting numbers. Once you have those variables, you can run it through `.filter` which does the looping for you. There isn't a need for the `for` loop.

**Comment by ltegman** [comment]
I don't know why this works in our in-browser editor, but this code should never work. The second argument of `filter` should be a `this` context, which is an object. When you pass in something that is not an object most runtimes will make it an empty object, which makes your function not work. That's definitely not the way the `this` context parameter of `filter` should be used. If you need help coming up with a different solution please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by diyachetak** [comment]
@jamigibbs I thought of that solution. But the arr (which is the first argument) is available to the function and we need to iterate over the arg1.. argN to find each of them and filter them out.

Am I getting it wrong?

**Comment by diyachetak** [comment]
@ltegman thanks for looking at this. I get your point. I tried different ways. Let me think of it and try out if there are alternate solutions.

**Comment by jamigibbs** [comment]
@diyachetak `arr` is actually just giving you the array to sort. The function isn't actually passing you anything else with that variable so you'll want to slice the `arguments` object to extract the other numbers. 

Like Logan mentioned, it might be better to get some feedback from the Chat room because this doesn't seem to be a bug with the platform.
