### ISSUE TITLE
Wrong Answer? Front-End: Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by mmbmatteo** [FreeCodeCamp/FreeCodeCamp#6934]
Is this wrong?

`<script>
  $(document).ready(function() {
              $("button").addClass("animated bounce"); 
              $(".btn").addClass("animated shake");
              $("#target1").addClass("btn-primary");
  });
</script>`

**Comment by mmbmatteo** [comment]
Solved

**Comment by mmbmatteo** [comment]
`<script>
  $(document).ready(function() {
              $("button").addClass("animated"); 
              $(".btn").addClass("shake");
              $("#target1").addClass("btn-primary");
  });
</script>`

**Comment by MaXwellFalstein** [comment]
The issue outline is correct, the documentation for the question appears to be incorrect.
"Only add one class with each of your three selectors."
"Your #target1 element should have the classes animated‚ shake and btn-primary."

**Comment by ltegman** [comment]
@MaXwellFalstein It's asking you to apply one class for each selector, but since every one of those selectors will grab the `#target1` element you'll end up with every class being applied to the `#target1` element.

**Comment by MaXwellFalstein** [comment]
That is true. That is they correct way round. Thanks @ltegman!
