### ISSUE TITLE
Fix images in "How to start when you are stuck II"

### ISSUE THREAD

**Issue by tasha-a-coder** [FreeCodeCamp/FreeCodeCamp#6935]
How to start when you are stuck (II)[(https://github.com/FreeCodeCamp/freecodecamp/wiki/How-to-start-when-you-are-stuck-(II))

3 of the 4 example images return "Not Found" in the browser.  

@biancamihai
Do you have the original images for the article?

**Comment by biancamihai** [comment]
@tasha-a-coder sorry for that :( ... I will try to search them asap

**Comment by bugron** [comment]
@biancamihai waiting for you to fix this, thanks.

**Comment by raisedadead** [comment]
Closing in favor of FreeCodeCamp/wiki#588
