### ISSUE TITLE
Blank challenges on Map page with broken links

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/FreeCodeCamp#6937]
After this morning's update, I noticed that there are several blank challenges on my Map page:

http://www.freecodecamp.com/wildlifehexagon

The "view this challenge" links  for these are also broken.

**Comment by ltegman** [comment]
@BerkeleyTrue or @SaintPeter: Any leads on what might be at the root of this?

**Comment by BerkeleyTrue** [comment]
Looking into it.

**Comment by BerkeleyTrue** [comment]
Looks like some of challenges completed in your old completedChallenges array didn't have a name property. Which means they don't have a name to display or a to create a link to the challenge. I think we may have been filtering them before and that filter was removed in that commit.

Here is one of the id's for the challenges without a name: bd7114d8c441eddfaeb5bdef

**Comment by bugron** [comment]
@BerkeleyTrue is this issue fixed?

**Comment by crashuniverse** [comment]
We still have old challenges showing up in profile. The solution I have is to not present with the (misleading) link and we should be good.
