### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue 

### ISSUE THREAD

**Issue by AleiaElle** [FreeCodeCamp/freecodecamp#694]
Instructions:
Create a class called "thick-green-border" that puts a 10-pixel-wide green border around an HTML element, and apply it to your cat photo.

The instructions are not indicating what "border-style" is to be used (none, solid, dotted, etc).  Border-style is required to move on to next challenge.

**Comment by terakilobyte** [comment]
Thanks, commit 4dcaac8bc58bab9057f6e08ab28c2a39b8086655 closes this.
