### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by JamshidA** [FreeCodeCamp/FreeCodeCamp#6944]
canceled!

**Comment by jamigibbs** [comment]
The instructions say: 

> Combine the two if statements into one statement

Before posting a Github bug report, remember first to check in the [JavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by JamshidA** [comment]
You are right
I'm really sorry.

On 2/13/16, Brian <notifications@github.com> wrote:
> Closed #6944.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6944#event-549125375


-- 
با احترام
جمشید عجم
