### ISSUE TITLE
New wiki : Issues and suggestions

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#6946]
The new wiki is just great.

**A few things to discuss though refering to the screenshot below:**

![1](https://cloud.githubusercontent.com/assets/1884376/13023994/cc9764b4-d214-11e5-8ee3-3de74e4cdbb3.PNG)

**1. Need to fix the titles**
The titles appear twice in some of the entries, because one is rendered from the file name and the other is from the `#` heading used by the author in the article itself.

This should be an easy fix, by removing the `#` heading and adding a one liner intro text? or may be just removing.

**2. Broken Images**
Of course in some of the articles the images were relatively linked to the `.md` file and the github wiki worked, this has to be replaced.

Since you guys have worked on this maybe you could suggest how it works so the links can be fixed. One thing that I can say is making them absolute paths but I am concerned about breaking things.

**3. Update Wiki Contribution guidelines**
We may need to revisit the wiki contribution guidelines so that the new articles are inline with what the styling if the new wiki, for example Point 1 about titles.

Other general guidelines such as Image sizes, using markdown styling, etc

_**Trivial things:**_
> Consider a different font style:

This might be just me, but IMHO the white space and the thin font is actually not going so well.
> Consider increasing the width of the panel on wide screens?

Okay I know I am just being picky on this one, but it would help in more readability, of course we can let this one go if its too costly UX wise. :wink: 

Please add other points that I might have missed above.

**Comment by raisedadead** [comment]
Not to mention if you guys agree, I can take up fixing some of the things :wink:

**Comment by SaintPeter** [comment]
We have some substantial refactoring to do on the Wiki, including what you describe.  This is going to involve some architectural changes.  Really appreciate the offer, but let us hack on it a bit before we release the hounds.

I'm about to file an issue that describes what I'm thinking.  Feel free to follow along.  ;)

**Comment by raisedadead** [comment]
Oh that's cool! Thanks :+1:

**Comment by QuincyLarson** [comment]
@raisedadead @SaintPeter what's the status of this issue? Have all of these problems been solved?

**Comment by hallaathrad** [comment]
subscribing :+1:

**Comment by raisedadead** [comment]
@hallaathrad @SaintPeter If we could discuss this whenever you have some time, It would be great if any of you can brief me on the current architecture, and any plans or things you are already working? I'll try and help

**Comment by raisedadead** [comment]
ToDo: consider wiki issue FreeCodeCamp/wiki#364, while working on this.

**Comment by hallaathrad** [comment]
Relevant comment by @d3ddd at #7475 
> Is there a way to search the wiki for "frozen" or "stuck" or "reset" and have this wiki article return as a result?

Reposting here to keep alive while closing that one.

**Comment by raisedadead** [comment]
Taking additional issue from #7486 as mentioned by @jstoebel 
> When I pull up the wiki sidebar, and click [Template] (https://freecodecamp.com/wiki/Algorithm-Wiki-Template), nothing happens. The request gets no response

![fcc_screencap](https://cloud.githubusercontent.com/assets/12101566/13670004/37dc31fc-e695-11e5-88a6-d1cd56b06f47.png)

**Comment by raisedadead** [comment]
@jstoebel

[Algorithm-Wiki-Template](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Wiki-Template) from the live wiki at https://github.com/FreeCodeCamp/FreeCodeCamp/wiki

**Comment by raisedadead** [comment]
@evaristoc [found that](https://gitter.im/FreeCodeCamp/CoreTeam?at=56eab6513194fbd11097e582) the wiki redirects the camperbot link on the main page at `freecodecamp.github.io/wiki` redirects to the beta page of freecodecamp.

Adding it to this for future.

**Comment by atjonathan** [comment]
All of these issues have been resolved.
