### ISSUE TITLE
Make A Person is not passing, despite passing in my sandbox environment

### ISSUE THREAD

**Issue by robwelan** [FreeCodeCamp/FreeCodeCamp#6948]
Challenge [Make a Person](http://www.freecodecamp.com/challenges/make-a-person#?solution=var%20Person%20%3D%20function(firstAndLast)%20%7B%0A%09%09%09%09this.firstName%20%3D%20%22%22%3B%0A%09%09%09%09this.lastName%20%3D%20%22%22%3B%0A%09%09%09%09this.fullName%20%3D%20%22%22%3B%0A%09%09%09%09this.setFullName(firstAndLast)%3B%20%0A%09%09%09%7D%3B%0APerson.prototype.getFirstName%20%3D%20function()%20%7B%0A%09%09%09%09return%20this.firstName%3B%0A%09%09%09%7D%3B%0A%09%09%09Person.prototype.getLastName%20%3D%20function()%20%7B%0A%09%09%09%09return%20this.lastName%3B%0A%09%09%09%7D%3B%0A%09%09%09Person.prototype.getFullName%20%3D%20function()%20%7B%0A%09%09%09%09return%20this.fullName%3B%0A%09%09%09%7D%3B%0A%09%09%09Person.prototype.setFirstName%20%3D%20function(firstName)%20%7B%0A%09%09%09%09this.firstName%20%3D%20firstName%3B%0A%09%09%09%09this.fullName%20%3D%20firstName%20%2B%20%22%20%22%20%2B%20this.lastName%3B%0A%09%09%09%7D%3B%0A%09%09%09Person.prototype.setLastName%20%3D%20function(lastName)%20%7B%0A%09%09%09%09this.lastName%20%3D%20lastName%3B%0A%09%09%09%09this.fullName%20%3D%20this.firstName%20%2B%20%22%20%22%20%2B%20lastName%3B%0A%09%09%09%7D%3B%0A%09%09%09Person.prototype.setFullName%20%3D%20function(firstAndLast)%20%7B%0A%09%09%09%09var%20arr%20%3D%20firstAndLast.split(%22%20%22)%3B%0A%09%09%09%09this.firstName%20%3D%20arr%5B0%5D%3B%0A%09%09%09%09this.lastName%20%3D%20arr%5B1%5D%3B%0A%09%09%09%09this.fullName%20%3D%20firstAndLast%3B%0A%09%09%09%7D%3B%0A%09%09%09%0A%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0Abob.getFullName()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Person = function(firstAndLast) {
				this.firstName = "";
				this.lastName = "";
				this.fullName = "";
				this.setFullName(firstAndLast); 
			};
Person.prototype.getFirstName = function() {
				return this.firstName;
			};
			Person.prototype.getLastName = function() {
				return this.lastName;
			};
			Person.prototype.getFullName = function() {
				return this.fullName;
			};
			Person.prototype.setFirstName = function(firstName) {
				this.firstName = firstName;
				this.fullName = firstName + " " + this.lastName;
			};
			Person.prototype.setLastName = function(lastName) {
				this.lastName = lastName;
				this.fullName = this.firstName + " " + lastName;
			};
			Person.prototype.setFullName = function(firstAndLast) {
				var arr = firstAndLast.split(" ");
				this.firstName = arr[0];
				this.lastName = arr[1];
				this.fullName = firstAndLast;
			};
			

var bob = new Person('Bob Ross');
bob.getFullName();

```

Fails on tests:
Object.keys(bob).length
bob.firstName should return undefined. (Why?)
bob.lastName should return undefined. (Why?)

Isn't "Object.keys(bob).length" redundant if the other 9 tests that prove the required functions exist (and are working)?

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance. Thanks and happy coding!

**Comment by robwelan** [comment]
I'm not seeking help. The exercise fails my code despite all tests (except 3) are working. The tests that fail are spurious and can be proven to be spurious by the fact that the other 9 tests prove that Object.keys(bob).length is simply not accurate and that bob.firstName and bob.lastName have an obfuscated meaning at the very least. What are these two tests even for? If this issue is not properly reviewed, I'll escalate further.

**Comment by ltegman** [comment]
The tests are not spurious. This challenge says:

>These methods must be the only available means for interacting with the object.

This means that exposing the variables as properties of the object is not allowed, which is what these tests are checking for. This challenge is looking for you to hide the actual variables and only expose them through getters and setters. Your code does not fulfill this requirement.

**Comment by robwelan** [comment]
Thanks for the reply - your response - whilst informative - is new information to me. For your reference, the instructions simply say "These methods must be the only available means for interacting with the object." It does not say, per your advice "hide the actual variables and only expose them through getters and setters". Perhaps, to avoid confusion, the instructions could be made a little clearer? I'll look at my code now that I know I'm supposed to hide the variables. Case closed now.
