### ISSUE TITLE
"Concatenating Strings with Plus Operator" Possible typo, creating potential confusion

### ISSUE THREAD

**Issue by otherwyze** [FreeCodeCamp/FreeCodeCamp#6949]
The instruction - Build myStr from the strings "This is the start. " - contains a space before the final ending quotes. It won't read as correct unless the user includes this unnecessary space.

**Comment by ltegman** [comment]
The space is necessary because you are combining two sentences together and there should be a space between them. This is a very common circumstance in string concatenation. Thanks and happy coding!
