### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue 

### ISSUE THREAD

**Issue by LeandraH** [FreeCodeCamp/freecodecamp#695]
I think it would be a good idea to add a check for a non-palindrome that has the same first and last letter. I just put in some code that had the return statement in the wrong place and it didn't throw an error because all the non-palindromes differ at the outermost edges.

**Comment by terakilobyte** [comment]
Good suggestion, can we except a PR soon?

**Comment by LeandraH** [comment]
Uhm, I think I'm not quite that far yet but if you're willing to wait a couple of days, you'll get one :)

**Comment by LeandraH** [comment]
Right, panicked there, sorry about that, I think I did it now.

**Comment by BerkeleyTrue** [comment]
Hey @LeandraH. Your last comment made it sound like it worked correctly after all. Can we close this issue?

**Comment by LeandraH** [comment]
Ah, yes, sorry.
