### ISSUE TITLE
Points / items on my profile

### ISSUE THREAD

**Issue by jslirola** [FreeCodeCamp/FreeCodeCamp#6951]
Text Redacted

**Comment by SaintPeter** [comment]
Thank you very much for reporting this.  I have redacted the text since this is a security issue.

**Comment by SaintPeter** [comment]
Hey, really appreciate this report, but in the future if you find a bug that could get someone "free" points or other security type things, it would be good if you contacted the staff privately.  We don't want to let everyone know that there is a bug of this type out there.

We've got a fix now thanks to your quick reporting!  Really appreciate it!

**Comment by jslirola** [comment]
I'm so sorry. I was not sure if the problem was a real bug, the next time i'll contact by private.
