### ISSUE TITLE
Internal Wiki Refactoring

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#6952]
There are several issues with the current Wiki:

1. It is not possible to link to a specific page in the Wiki
2. On the full-page version the address bar/url does not change when changing pages.
3. Images are not properly moved over.
4. Some internal links are not converted correctly

The current framework works like this:
The page is hosted on GH Pages and pulled in to the site via iframe for both the sidebar and into a full page iframe for the full page version.

### Proposed Refactor
1. Use nginx to proxy the page so it hangs off the /wiki url
2. Use an iframe to pull in a copy of the navbar - New endpoint on the main site
3. Implement a sidebar in react on the Wiki side to display the chat/map/wiki when clicked
4. Provide navbar -> react communication to toggle the sidebar displays
5. Only display the navbar in the full page version of the site.

**Comment by bugron** [comment]
Moved this issue to Wiki repository. See https://github.com/FreeCodeCamp/wiki/issues/364.
