### ISSUE TITLE
Twitch Challenge - Wiki link invalid

### ISSUE THREAD

**Issue by nicoschmitt** [FreeCodeCamp/FreeCodeCamp#6961]
Related to challenge /use-the-twitchtv-json-api. 

I think it should be https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-the-Twitchtv-JSON-API.

**Comment by bugron** [comment]
@nicoschmitt thanks for posting, confirmed. Hint 8 need to be updated.
