### ISSUE TITLE
Video challenges: Completed challenges not saved

### ISSUE THREAD

**Issue by undefinedsymbol** [FreeCodeCamp/FreeCodeCamp#6962]
After completing a video challenge, I first see my brownie points increment by 1 and I am directed to the next challenge, but when I havigate away and come back, my recently gained brownie point(s) has/have disappeared and the recently completed challenge(s) is/are not marked as complete.

**Comment by ltegman** [comment]
Closing as a duplicate of #6912. Thanks and happy coding!

**Comment by undefinedsymbol** [comment]
Sorry for the duplicate posting, I did not see it in the issues list when I checked. Thank you!
