### ISSUE TITLE
German translation of Getting started

### ISSUE THREAD

**Issue by undefinedsymbol** [FreeCodeCamp/FreeCodeCamp#6963]
- [ ] Join the Free Code Camp community
 - [ ] Learn how Free Code Camp Works 
 - [ ] Create a GitHub Account and Join our Chat Rooms
 - [ ] Configure your Code Portfolio
 - [ ] Join a Campsite in Your City
 - [ ] Learn What to Do If You Get Stuck

**Comment by codingHahn** [comment]
How can I help?

**Comment by bugron** [comment]
@codingHahn see [my comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6793#issuecomment-182505161), thanks.

**Comment by codingHahn** [comment]
I read it. Plesse put me in a task. ;)

**Comment by abisz** [comment]
Working on it
