### ISSUE TITLE
German translation of HTML5 and CSS

### ISSUE THREAD

**Issue by undefinedsymbol** [FreeCodeCamp/FreeCodeCamp#6964]
- [ ] Say Hello to HTML Elements
- [ ] Headline with the h2 Element
- [ ] Inform with the Paragraph Element
- [ ]  Uncomment HTML
- [ ]  Comment out HTML
- [ ] Fill in the Blank with Placeholder Text
- [ ]  Delete HTML Elements
- [ ]  Change the color of Text
- [ ]  Use CSS Selectors to Style Elements
- [ ] Use a CSS Class to Style an Element
- [ ]  Change the Font Size of an Element
- [ ]  Change the Font Family of an Element
- [ ]  Import a Google Font
- [ ]  Specify How Fonts should degrade
- [ ]  Add Images to your Website
- [ ]  Size your Images
- [ ] Add Borders Around your Elements
- [ ]  Add Rounded Corners with a Border Radius
- [ ]  Make Circular Images with a Border Radius
- [ ]  Link to External Pages with Anchor Elements
- [ ]  Nest an Anchor Element within a Paragraph
- [ ]  Makde Dead Links using the Hash Symbol
- [ ]  Turn an Image into a Link
- [ ]  Add Alt Text to an Image for Accessibility
- [ ]  Create a Bulleted Unordered List
- [ ]  Create an Ordered List
- [ ]  Create a Text Field
- [ ]  Add a Placeholder Text to a Text Field
- [ ]  Create a Form Element
- [ ]  Add a Submit Button to a Form
- [ ]  Use HTML5 to Require a Field
- [ ]  Create a Set of Radio Buttons
- [ ]  Create a Set of Checkboxes
- [ ]  Check Radio Buttons and Checkboxes by Default
- [ ]  Nest Many Elements within a Single Div
- [ ] Give a Background Color to a Div Element
- [ ]  Set the ID of an Element
- [ ]  Use an ID Attribute to Style an Element
- [ ]  Adjusting the Padding of an Element
- [ ]  Adjust the Margin of an Element
- [ ]  Add a Negative Margin to an Element
- [ ]  Add a Different Padding to Each Side of an Element
- [ ]  Add Different Margins to Each Side of an Element
- [ ]  Use Clockwise Notation to Specify the Padding of an Element
- [ ] Use Clockwise Notation to Specify the Margin of an Element
- [ ]  Style the HTML Body Element
- [ ]  Inherit Styles from the Body Element
- [ ] Prioritize One Style Over Another
- [ ]  Override Styles in Subsequent CSS
- [ ]  Override Class Declarations by Styling ID Attributes
- [ ]  Override Class Declarations with Inline Styles
- [ ]  Override All Other Styles by using Important
- [ ]  Use Hex Code for Specific Colors
- [ ]  Use Hex Code to Color Elements White
- [ ]  Use Hex Code to Color Elements Red
- [ ]  Use Hex Code to Color Elements Green
- [ ]  Use Hex Code to Color Elements Blue
- [ ]  Use Hex Code to Mix Colors
- [ ]  Use Hex Code to Color Elements Gray
- [ ]  Use Hex Code for Specific Shades of Gray
- [ ]  Use Abbreviated Hex Code
- [ ]  Use RGB values to Color Elements
- [ ]  Use RGB values to Color Elements White
- [ ]  Use RGB values to Color Elements Green
- [ ]  Use RGB values to Color Elements Blue
- [ ]  Use RGB values to Mix Colours

**Comment by tbgse** [comment]
Here you go

-  Say Hello to HTML Elements
Sag Hallo zu HTML Elementen
-  Headline with the h2 Element
Überschrift mit dem h2 Element
-  Inform with the Paragraph Element
Informiere mit dem Parapraph Element
-  Uncomment HTML
HTML auskommentieren
-  Comment out HTML
HTML auskommentieren
-  Fill in the Blank with Placeholder Text
Vervollständige die Lücke mit Platzhaltertext.
-  Delete HTML Elements
HTML Elemente löschen
-  Change the color of Text
Textfarbe ändern
-  Use CSS Selectors to Style Elements
Nutze CSS Selektoren, um Elemente zu gestalten
-  Use a CSS Class to Style an Element
Nutze CSS Klassen, um Elemente zu gestalten
-  Change the Font Size of an Element
Ändere die Schriftgröße eines Elements
-  Change the Font Family of an Element
Ändere die Schriftfamilie eines Elements
-  Import a Google Font
Importiere eine Google Schriftart
-  Specify How Fonts should degrade
Spezifiziere, wie Schriftarten degradieren sollen
-  Add Images to your Website
Füge Deiner Website Bilder hinzu
-  Size your Images
Skaliere Deine Bilder
-  Add Borders Around your Elements
Gib deinen Elemeten einen Rand
-  Add Rounded Corners with a Border Radius
Erstelle runde Kanten mit Border Radius 
-  Make Circular Images with a Border Radius
Erstelle runde Bilder mit Border Radius
-  Link to External Pages with Anchor Elements
Verlinke externe Websites mit Anker Elementen
-  Nest an Anchor Element within a Paragraph
Verschachtel ein Anker Elemenet in einem Pargraph
-  Makde Dead Links using the Hash Symbol
Erstelle "tote" Links mit dem Hash Symbol
-  Turn an Image into a Link
Verwandle ein Bild in einen Link
-  Add Alt Text to an Image for Accessibility
Füge einen alternativen Text zu einem Bild hinzu, um die Zugänglichkeit zu verbessern
-  Create a Bulleted Unordered List
Erstelle eine ungeordnete Liste mit Aufzählungszeichen
-  Create an Ordered List
Erstelle eine nummerierte Liste
-  Create a Text Field
Erstelle ein Textfeld
-  Add a Placeholder Text to a Text Field
Füge dem Textfeld einen Plathaltertext hinzu
-  Create a Form Element
Erstelle ein Formularelement
-  Add a Submit Button to a Form
Füge einem Formular einen Absenden Button hinzu
-  Use HTML5 to Require a Field
Nutze HTML5, um ein Feld als notwendig zu kennzeichnen
-  Create a Set of Radio Buttons
Erstelle eine Gruppe von Radio Buttons
-  Create a Set of Checkboxes
Erstelle eine Gruppe von Checkboxen
-  Check Radio Buttons and Checkboxes by Default
Markiere Radio Buttons und Checkboxes standartmäßig 
-  Nest Many Elements within a Single Div
Verschachtel diverse Elemente in einem einzigen Div Element
-  Give a Background Color to a Div Element
Gebe einem Div Element eine Hintergrundfarbe
-  Set the ID of an Element
Definiere die ID eines Elements
-  Use an ID Attribute to Style an Element
Nutze das ID Attribut, um ein Element zu gestalten
-  Adjusting the Padding of an Element
Passe das Padding eines Elements an
-  Adjust the Margin of an Element
Passe den Margin eines Elements an
-  Add a Negative Margin to an Element
Gib einem Element einen negativen Margen
-  Add a Different Padding to Each Side of an Element
Gib einem Element unterschiedliche Paddings an jeder Seite
-  Add Different Margins to Each Side of an Element
Gibt einem Element unterschiedliche Margins an jeder Seite
-  Use Clockwise Notation to Specify the Padding of an Element
Nutze die Notation im Uhrzeigersinn, um das Padding eines Elements anzugeben
-  Use Clockwise Notation to Specify the Margin of an Element
Nutze die Notation im Uhrzeigersinn, um den Margin eines Elements anzugeben
-  Style the HTML Body Element
Gestalte das HTML Body Element
-  Inherit Styles from the Body Element
Vererbe Styles des Body Elements
-  Prioritize One Style Over Another
Prioritisiere einen Style vor einem anderen
-  Override Styles in Subsequent CSS
Überschreibe Styles in nachfolgendem CSS
-  Override Class Declarations by Styling ID Attributes
Überschreibe die Deklaration von Klassen durch die Nutzung von ID Attributen
-  Override Class Declarations with Inline Styles
Überschreibe die Deklaration von Klassen durch die Nutzung von Inline Styles
-  Override All Other Styles by using Important
Überschreibe alle anderen Styles durch das Nutzen von Important
-  Use Hex Code for Specific Colors
Nutze Hex Code für spezifische Farben
-  Use Hex Code to Color Elements White
Nutze Hex Code, um Elemente weiß zu färben
-  Use Hex Code to Color Elements Red
Nutze Hex Code, um Elemente rot zu färben
-  Use Hex Code to Color Elements Green
Nutze Hex Code, um Elemente grün zu färben
-  Use Hex Code to Color Elements Blue
Nutze Hex Code, um Elemente blau zu färben
-  Use Hex Code to Mix Colors
Nutze Hex Code, um Farben zu mischen
-  Use Hex Code to Color Elements Gray
Nutze Hex Code, um Elemente grau zu färben
-  Use Hex Code for Specific Shades of Gray
Nutze Hex Code für spezifische Grautöne
-  Use Abbreviated Hex Code
Nutze abgekürzten Hex Code
-  Use RGB values to Color Elements
Nutze RGB Werte, um Elemente zu färben.
-  Use RGB values to Color Elements White
Nutze RGB Werte, um Elemente weiß zu färben
-  Use RGB values to Color Elements Green
Nutze RGB Werte, um Elemente grün zu färben
-  Use RGB values to Color Elements Blue
Nutze RGB Werte, um Elemente blau zu färben
-  Use RGB values to Mix Colours
Nutze RGB Werte, um Farben zu mischen

**Comment by abisz** [comment]
I'm working on it
