### ISSUE TITLE
Issue regarding navigation to next challenge from current challenge 

### ISSUE THREAD

**Issue by tnsurender** [FreeCodeCamp/FreeCodeCamp#6965]
Hi team , 
I am facing trouble while navigation from one challenge to next challenge. It is showing error while I move to next challenge after completion of the current challenge successfully.
I am attaching screenshot also.
Please help.

![image](https://cloud.githubusercontent.com/assets/6574625/13028162/ad13162e-d28c-11e5-829d-48a9daa5cbfb.png)

Regards,
Surender

**Comment by sludge256** [comment]
Duplicate of #6958
