### ISSUE TITLE
Adding a default option in Switch statements not working

### ISSUE THREAD

**Issue by gracetong0630** [FreeCodeCamp/FreeCodeCamp#6966]
Challenge [Adding a default option in Switch statements](http://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case a:
      answer = "apple";
      break;
    case b:
      answer = "bird";
      break;
    case c:
      answer = "cat";
      break;
    default:
      return "stuff";

  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(1);

```

**Comment by gracetong0630** [comment]
I also notice that several exercises ahead of this one is quite confusing.I spent hours on those,could you please make it clearer?

**Comment by jamigibbs** [comment]
I would recommend reviewing the example switch in that challenge. You shouldn't need to `return` the default. 

Before posting a Github bug report, remember first to check in the [JavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by hallaathrad** [comment]
Exactly what Jami said, that's how your default will work. 

Please abstain from posting code questions in the issue board, as this only for verified system issues.
The [instructions for bug reporting](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) are very clear and easy to follow.

This is not a system issue, so I'm closing it.
Happy coding!

**Comment by mohannadsawalhi** [comment]
case "a":
case "c": 

.>>etc

**Comment by lettda** [comment]
Make sure you put the letters in between quotation marks in the cases as well as when you call the function with that value i.e. case "a":.......functionName("a")

**Comment by Greenster** [comment]
Place double quotes on all case letters as if they were strings e.g.  case a: should be case "a".

**Comment by BEBEDYDY** [comment]
unction switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch (val){
    case "a":
      answer = "apple";
      break;
    case "b":
      answer = "bird";
      break;
    case "c":
      answer ="cat";
      break;
    default:
      answer ="stuff";
      
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(c);

ok, I don't want to blah, here is the code. Hope it will help you.

**Comment by BurningWood** [comment]
Yeah it's not working for me and the editor says there are no errors. 


function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  
  switch (val) {
   case "a":
   answer= "apple";

   break;
 
   case "b":
    answer= "bird";
    break;

  case "c":
    answer="cat";
    break;

     default:
   answer= "stuff";
    
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff("a");

**Comment by BurningWood** [comment]
![screenshot 360](https://cloud.githubusercontent.com/assets/5056275/17937799/5520706e-6a5e-11e6-806a-369d6625112c.png)

**Comment by anyacoleman** [comment]
BurningWood you forget a close bracket after   
default: 
answer= "stuff";
}

**Comment by katelynho16** [comment]
function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case "a":
      answer = "apple";
      break;
      
    case "b":
      answer = "bird";
      break;
      
    case "c":
      answer = "cat";
      break;
      
    default:
      answer ="stuff";
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(1);

**Comment by mminhaz1029** [comment]
My Solution 

function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch(val) {
    case "a":
      answer = "apple";
      break;
    case "b":
      answer = "bird";
      break;
    case "c":
      answer = "cat";
      break;
    default:
      answer = "stuff";
  }
  // Only change code above this line  
  return answer;  
}
// Change this value to test
switchOfStuff(1);

**Comment by gitakpaudyal** [comment]
function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case val = "a":
        answer = "apple";
      break;
    case val =  "b":
      answer =  "bird";
          break;
    case val =  "c":
      answer =  "cat";
          break;
    default:
      answer =  "stuff";
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(1);

**Comment by mjquiambao** [comment]
i have the same code but everytime i put switchOfStuff(a); it says a is not defined..

**Comment by mjquiambao** [comment]
got it.. so you need to put "a" for it to work.. thanks..
