### ISSUE TITLE
Profile Lookup Challenge: Functions argument should be `name` instead of `firstName`

### ISSUE THREAD

**Issue by jamigibbs** [FreeCodeCamp/FreeCodeCamp#6967]
http://www.freecodecamp.com/challenges/profile-lookup

The setup object already has a key called `firstName` and this can be rather confusing having the function's object named the same. The solution has it named this way as well:

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4345

**Comment by AkiraLaine** [comment]
@jamigibbs The reason why the argument is called ```firstName``` is because that's the property you need to be checking for. 

I originally called it ```name``` but ```firstName`` is in fact less confusing. Users know exactly that's what they are looking for.

**Comment by AkiraLaine** [comment]
@FreeCodeCamp/issue-moderators I closed this, but what do you guys think?

**Comment by ltegman** [comment]
I also feel that `firstName` is less confusing.

**Comment by SaintPeter** [comment]
I think I was the one who suggested it be changed to `firstName` - which is is sort of confusing, I think it's less confusing than having it generically named.  Then there would be questions about what they're searching for, what they should be comparing.  I have never seen someone come into the helprooms with questions about this - they always have trouble with the search logic instead.

**Comment by AkiraLaine** [comment]
@SaintPeter Yep! You suggested the change.

Should we close this then?

**Comment by jamigibbs** [comment]
I think in addition to being slightly confusing, I was also having some issue getting the correct data that I wanted to complete the solution. For example, this is my solution by changing the parameter to `name`:

```javascript
  for(var i in contacts){
    if(contacts[i].firstName === name){
      return contacts[i][prop] || "No such property";
    }
  }
  return "No such contact";
```

If I hadn't changed the parameter name, then `contacts[i].firstName` would be searching for the object key that's named the function parameter and would throw an undefined error.
