### ISSUE TITLE
Possible bug to pass the challenge

### ISSUE THREAD

**Issue by Andlerario** [FreeCodeCamp/FreeCodeCamp#6969]
Challenge [Concatenating Strings with Plus Operator](http://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0</code>.

Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line, code it gives me wrong

var myStr = "This is the start." + "This is the end.";



```

**Comment by hallaathrad** [comment]
Forgive me, but what's the issue? we need a bit more information in order to be able to assist you.
Also, have you reach out to the [help channel](https://gitter.im/FreeCodeCamp/Help) to verify this bug as it is suggested in the [bug submission guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)?

Please complete the information so we can move forward. Thanks :)

**Comment by Andlerario** [comment]
I need to recreate the same as the example in the first line, the second line is my code and I don`t see what I am doing wrong, in the help channel I got no answers, but it's kind of obvious that there is something wrong to not pass this challenge.

This is the first time I am doing this, I am sure there is nothing wrong with my code, in that case I thought it was wise to report a possible bug, please correct me if im wrong

**Comment by hallaathrad** [comment]
There is in fact an inconspicuous mistake in your code. 
The expected resulting string is "This is the start. This is the end.", where as the console shows you're getting "This is the start.This is the end.". The error is in the missing space after the dot.
Try this instead:
```js
var myStr = "This is the start. " + "This is the end.";
```

This is not an issue with the site, therefor not something you would normally create an "issue report" for. 
If the multiple help channels are not being helpful, you can reach me @hallaathrad directly over gitter, and I'll try to help, but please refrain from posting issues until having confirmed them with others.

I'll see you in gitter if you need further assistance with this and any other code pieces :)
Happy coding!
