### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue 

### ISSUE THREAD

**Issue by ricmclaughlin** [FreeCodeCamp/freecodecamp#697]
The test on this challenge needs to require a closing </p> tag. To reproduce put an opening <p> tag before the <img> tag. Notice that you can go to the next challenge and the tests on the left are all green. We need a test for the closing </p> as well.

**Comment by terakilobyte** [comment]
http://www.w3.org/TR/html5/syntax.html#optional-tags

**Comment by ricmclaughlin** [comment]
Not to belabor the point, but the way I read it a closing </p> tag is not optional when the parent is an anchor.

From the document you referenced (and the document I read when I wrote the bug):

>A p element's end tag may be omitted if the p element is immediately followed by an address, article, >aside, blockquote, div, dl, fieldset, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, nav, ol, >p, pre, section, table, or ul, element, or if there is no more content in the parent element and the parent >element is not an a element.

In other words, the closing p tag is optional **except** in the case of an anchor.
