### ISSUE TITLE
Check for Palindrome error in returning 

### ISSUE THREAD

**Issue by shadymedy** [FreeCodeCamp/FreeCodeCamp#6970]
palindrome("almostomla") should return false.
palindrome("My age is 0, 0 si ega ym.") should return true

This is incorrect. The first one should return true and the second one should return false

**Comment by ltegman** [comment]
Both these test cases are correct. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need assistance with this challenge. Thanks and happy coding!
