### ISSUE TITLE
Safari browser ... can't get pass challenge which I believe has everything correct

### ISSUE THREAD

**Issue by DebSil** [FreeCodeCamp/FreeCodeCamp#6973]
Change the Font Size of an Element Challenge result will not let me pass.  Using Safari browser on a MAC and have tried all zoom sizes.

<style>
  p {
    font-size: 16px; 
  }
  
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by jamigibbs** [comment]
Which of the tests are not passing?

Also before posting a Github bug report, remember first to check in the [help chat room](https://gitter.im/FreeCodeCamp/Help) to verify the issue. :rocket:

**Comment by DebSil** [comment]
Change the Font Size of an Element

**Comment by jamigibbs** [comment]
So sorry, maybe I wasn't clear entirely clear. What I meant was which of the tests on the left side column are not passing (ie. showing a red "X"):

<img width="335" alt="screen shot 2016-02-13 at 2 17 24 pm" src="https://cloud.githubusercontent.com/assets/872479/13029827/89c59fdc-d25c-11e5-9604-c8b0c161f508.png">


Reference: [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element)

**Comment by DebSil** [comment]
My apologies.  Do not add a class attribute to your new p element.

**Comment by jamigibbs** [comment]
Ah great! So it sounds like this isn't a bug in the challenge but perhaps just a misplacement of a class attribute in your second `p` element.

Make sure your second `p` doesn't include a class, like this:

```
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

If that was the case, you can go ahead and close this issue. :+1: 

<img width="403" alt="screen shot 2016-02-13 at 2 23 38 pm" src="https://cloud.githubusercontent.com/assets/872479/13029858/692aeb5a-d25d-11e5-82e7-59a246b20bcf.png">

**Comment by DebSil** [comment]
Neither of my <P> elements contain a class attribute.

**Comment by jamigibbs** [comment]
So then the first paragraph should have the `red-text` class and the second one shouldn't.

**Comment by DebSil** [comment]
Thanks, Jamie:

Not sure why the transition from that test to the previous one eliminated that style, especially since this step does not ask you to put it in.

It’s all resolved now.

Thank you!
Deb
