### ISSUE TITLE
Bonfire, Seek and Destroy - input test data could be improved

### ISSUE THREAD

**Issue by cragsify** [FreeCodeCamp/FreeCodeCamp#6974]
I believe that the input test data for this bonfire in currently not implemented as the designer intended.

The test data is currently structured such that you need to test for optional arguments in the function call. 

An easier way to do this would be to wrap all the arguments in the call in an array. Example below.

Currently test data is: 

`[1, 2, 3, 1, 2, 3], 2, 3`

I propose test code should be:

`[[1, 2, 3, 1, 2, 3], 2, 3]`

I believe that the test code should be formatted similarly to above for all the test data.

**Comment by ltegman** [comment]
This is intentional. Arguments are an array that can be accessed from within the function and this bonfire forces you to take advantage of that.
