### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-set-the-font-family-of-an-element has an issue 

### ISSUE THREAD

**Issue by Crysicia** [FreeCodeCamp/freecodecamp#698]
Error in the exemple : 
For example, if you wanted to set your h2 element's font to "San-serif", you would use the following CSS: h2 { font-family: 'San-serif'; }

Would be : 
For example, if you wanted to set your h2 element's font to "Sans-serif", you would use the following CSS: h2 { font-family: 'Sans-serif'; }

**Comment by terakilobyte** [comment]
Thanks, commit 5fd4ce00303a1cefff4eabbe86d068456b0c2545 fixes this.
