### ISSUE TITLE
Test and Run button not working

### ISSUE THREAD

**Issue by tobiaswik** [FreeCodeCamp/FreeCodeCamp#6981]
Challenge [Set the Font Family of an Element](http://www.freecodecamp.com/challenges/set-the-font-family-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%0A%20%20p%20%0A%20%20%20%20font-size%3A%2016px%3B%0A%0A%20%20font-family%3A%20Monospace%3B%20%0A%7D%0A%3C%2Fstyle%3E%0A%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  
  p 
    font-size: 16px;

  font-family: Monospace; 
}
</style>


<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

Only problem is that I cant press the Test and Run button. Its just all dead and dosnt work anymore

**Comment by AkiraLaine** [comment]
The issue is most probably that you don't have an opening curly brace on your ```p``` tag.

**Comment by tobiaswik** [comment]
<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;

  font-family: Monospace; 
}


So like this?

**Comment by tobiaswik** [comment]
I feel like the browser would tell me something is wrong instead of just nothing. no?

**Comment by tobiaswik** [comment]
Especially since everything looks like it should ( i imagine ) on the little iphone.

**Comment by AkiraLaine** [comment]
Why do you have ```<p>``` tags around your CSS? I think it's better if you reset your code and start again.

**Comment by tobiaswik** [comment]
<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;

  font-family: Monospace; 
}
</style>


<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.

Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

Im sorry but I pretty much have no idea what you are talking about.

**Comment by tobiaswik** [comment]
Wow that last post did not come out anyway near what I expected. 

Tried to copy the code, but the forum just mushed it all together.

**Comment by AkiraLaine** [comment]
@tobiaswik I formatted your code. Is that *exactly* what you have?

**Comment by tobiaswik** [comment]
<style>
  .red-text {
    color: red;
  }
  
    p {
    font-size: 16px;

  font-family: Monospace; 
}

</style>






<h2 class="red-text">CatPhotoApp</h2>



<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.

Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>




Yep, this is what I have.

The thing im all weird about is that I can see on the little iphone that the p segment is monospace, but it still wont let me continue. 

But im sure someone has a logical explanation to my confusion.

**Comment by AkiraLaine** [comment]
Your second ```p``` tag should not have any classes.

If you need help, please go to our [help](https://gitter.im/FreeCodeCamp/Help) room.

**Comment by tobiaswik** [comment]
1. Allright, I somehow didnt realize it wanted me to delete the class from previous step to make the text normal (black instead of red) again. 

Deleted the whole class thing and just added a <p> and now it told me OK. 

2. Isn't this where I came to after pressing the Help button in the coding window? 

3. Thank you very much! I bake allright brownies.

**Comment by JeanFerreira91** [comment]
I had the same problem. There is a mistake in the way the module y redactes. because at the end you can read "All your 'p' elements should have the monospace font" ... And the solution is that the second p element should not be with the class.

I'd lost 15 minutes thinking that I was doing something wrong, but its a redaction mistake. Fix it for the future guys learning.

This can be make people leave the course because the browse don't tells you whats wrong and you just can change the course to another free one.
