### ISSUE TITLE
Counting Cards cannot figure out

### ISSUE THREAD

**Issue by gracetong0630** [FreeCodeCamp/FreeCodeCamp#6982]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0Aif(card%3D%3D2%20%7C%7Ccard%3D%3D3%20%7C%7C%20card%3D%3D4%20%7C%7C%20card%3D%3D5%7C%7C%20card%3D%3D6)%0Acount%3D5%3B%0Aelse%20if(card%3D%3D7%20%7C%7C%20card%3D%3D8%20%7C%7C%20card%3D%3D9)%0Acount%2B%3D0%3B%0Aelse%20if%20(card%20%3D%3D%2010%20%7C%7C%20card%20%3D%3D%20'J'%20%7C%7C%20card%20%3D%3D%20'Q'%20%7C%7C%20card%20%3D%3D%20'K'%20%7C%7C%20card%20%3D%3D%20'A')%0Acount%20%3D1%3B%0Aelse%20%0A%20%20count%3D-1%3B%0A%20%20%0Aif(count%3C%3D%200)%7B%0A%20%20return%20count%2B%22%20Hold%22%3B%7D%0A%20%20%0Aelse%20if%20(count%20%3E0)%7B%20%0A%20%20return%20count%2B%22Bet%22%3B%7D%0A%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
if(card==2 ||card==3 || card==4 || card==5|| card==6)
count=5;
else if(card==7 || card==8 || card==9)
count+=0;
else if (card == 10 || card == 'J' || card == 'Q' || card == 'K' || card == 'A')
count =1;
else 
  count=-1;
  
if(count<= 0){
  return count+" Hold";}
  
else if (count >0){ 
  return count+"Bet";}


  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by AkiraLaine** [comment]
Hey @gracetong0630! If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavascript) room. GitHub is for issues only :smile:
