### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue 

### ISSUE THREAD

**Issue by AlecDataLocker** [FreeCodeCamp/freecodecamp#699]
!important is present but not detected in the urgently-red style. Applies but the last checkmark is not ticked, so the challenge can't be completed. Using Google Chrome on a Mac Yosemite 10.10

**Comment by terakilobyte** [comment]
Thanks, I've fixed this oversight. Refreshing the challenge should now expect the correct attribute for the correct class.
