### ISSUE TITLE
Open Data Initiative: Improvements to Torrent Dataset

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/FreeCodeCamp#6991]
@QuincyLarson, @BerkeleyTrue

* user id's. If not the real one, it should be a hashed one or similar that can be traced to previous datasets.
* date of registration
* To add the aforementioned information I think it would be ok to add an "object" to each camper's subarray like {id:'campershashedid', registrationdate:20160101xxxx, otherchosendata:etc}.
* I am not sure if data about those who are registered but haven't even touched a single exercise is available in the dataset? Should be included if not...
* Those who are registered but opt-in not to show data
* When available, the unsubscribe date (do FCC delete all the data of an unsubscribed??)
* At least a weekly calculation of the number of campers existing in the database, with date of calculation.
* Is there a variable, apart of "name" that indicates if the challenge is bonfire, zipline or any other type of challenge?

**Comment by bugron** [comment]
@evaristoc can you, please, expand a litter bit what means `Torrent Dataset` and what is this issue about for those who don't follow the `DataScience` room, thanks?

**Comment by evaristoc** [comment]
Hi @bugron: it is the dataset described by @QuincyLarson for the Open Data initiative:
https://medium.freecodecamp.com/free-code-camp-christmas-special-giving-the-gift-of-data-6ecbf0313d62#.2dr3l3fav

**Comment by bugron** [comment]
@evaristoc that does the trick, thanks :)
