### ISSUE TITLE
Hikes: Google Analytics

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/FreeCodeCamp#6992]
Add event tracking capabilities to videos

**Comment by brianamarie** [comment]
@Septimus do you have time to look into this, or would you like me to?

**Comment by evaristoc** [comment]
@brianamarie

I was looking that the Hikes files. The implementation should be easy for:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/app/routes/Hikes/components/Lecture.jsx

to capture finishing. A finish event can be implmented inside the taggings.

I would suggest to follow up start and possibly a stop (in time), so we can get an idea if the person is looking for a particular section of interest in the video.

One person that may advice is @ltegman, who owns the setting up?

**Comment by evaristoc** [comment]
@brianamarie
I found that apparently for vimeo videos we should add a pluging:
https://www.sanderheilbron.nl/vimeo.ga.js/

The implementation looks tremendously easy.

We can also partially track youtube videos from GA. My purpose is to create a single view where you can check.

I can help with this implementation but the first person to talk is @BerkeleyTrue.

**Comment by evaristoc** [comment]
@brianamarie 

Regarding youtube channel, I will need you to add an id to a particular page at the youtube channel account. I will pass you eventually the details (how to get that page and the id). It is a simple one step action.

Here just a link of the steps to follow:
http://www.klipfolio.com/blog/connect-youtube-channel-google-analytics

I am still deciding the best way to filter youtube from our main account though... need to give it a thought.

**Comment by brianamarie** [comment]
@evaristoc I tried this, but I believe since I am a manager of the youtube account and not the owner I do not have access to the tracking field. At least, I tried this, but couldn't find anywhere in the 'advanced' settings for a Tracking ID. 

@Septimus Could this be something you could help set up, or would @QuincyLarson need to do this?

**Comment by QuincyLarson** [comment]
I am moving hikes over to use YouTube instead of Vimeo, and we have google analytics active on our youtube channel. I will close this issue with the PR for that.
