### ISSUE TITLE
Translation to Spanish: Add translation of bigonotation.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6996]
- [x] Big O Notation: What It Is and Why You Should Care
- [x] Big O Notation: A Few Examples

**Comment by jherna37** [comment]
I'm on it

**Comment by justinian336** [comment]
Thanks @jherna37, go for it!

**Comment by vtamara** [comment]
@jherna37 por favor disculpa, sólo después de haber enviado la solicitud de cambio vi que habías solicitado trabajar en este.    Por favor envía tu pull request (solicitud de cambio para cancelar la que yo envié).
