### ISSUE TITLE
Translation to Spanish: Add translation of chromedevtools.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6997]
- [x] Chrome Dev Tools: Elements
- [x] Chrome Dev Tools: Network
- [x] Chrome Dev Tools: Sources
- [x] Chrome Dev Tools: Timeline
- [x] Chrome Dev Tools: Profiles
- [x] Chrome Dev Tools: Resources
- [x] Chrome Dev Tools: Audits
- [x] Chrome Dev Tools: Console
- [x] Chrome Dev Tools: Summary

**Comment by vtamara** [comment]
Working on it
