### ISSUE TITLE
Translation to Spanish: Add translation of jslingo.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#6999]
- [ ] JavaScript Lingo: MDN and Documentation
- [ ] JavaScript Lingo: Value Types
- [ ] JavaScript Lingo: Variables & camelCase
- [ ] JavaScript Lingo: Arrays & Objects
- [ ] JavaScript Lingo: Finding and Indexing Data in Arays
- [ ] JavaScript Lingo: Manipulating Data
- [ ] JavaScript Lingo: Math
- [ ] JavaScript Lingo: Loops
- [ ] JavaScript Lingo: Regular Expressions

**Comment by vtamara** [comment]
Working on this one
