### ISSUE TITLE
Translation to Spanish: Add translation of computer-basics.json

### ISSUE THREAD

**Issue by justinian336** [FreeCodeCamp/FreeCodeCamp#7001]
- [x] Computer Basics: The 4 Basic Parts of a Computer
- [x] Computer Basics: More Computer Hardware
- [x] Computer Basics: Chips and Moore's Law
- [x] Computer Basics: Intro to Binary Code
- [x] Computer Basics: Decoding a Binary Number
- [x] Computer Basics: How To Measure Data Size
- [x] Computer Basics: Measuring Data Speed
- [x] Computer Basics: Binary Bytes
- [x] Computer Basics: Types of Computers
- [x] Computer Basics: More on the Motherboard
- [x] Computer Basics: Data Networks
- [x] Computer Basics: IP Addresses
- [x] Computer Basics: How the Internet Works
- [x] Computer Basics: Software
- [x] Computer Basics: Content Delivery Networks
- [x] Analog vs Digital and File Compression
- [x] Routers and Packets
- [x] Source Code
- [x] Variables In Code
- [x] What Do Programmers Do?
- [x] Console and Logging
- [x] Computer Security

**Comment by vtamara** [comment]
Working on this one
