### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue 

### ISSUE THREAD

**Issue by AlecDataLocker** [FreeCodeCamp/freecodecamp#701]
Adding placeholder tag to the <img> element rather than the <input> element validates the "Your text field should have a placeholder attribute." checkbox incorrectly.

**Comment by terakilobyte** [comment]
Could you provide a screenshot? I'm not quite following "Adding a placeholder tag to the element rather than the element...."

**Comment by AlecDataLocker** [comment]
Sorry spaced out and wrote the wrong thing. If you add placeholder tag to the img element rather than the text field the waypoint will say it's correct.
