### ISSUE TITLE
i think eyeforofeye is a palindrome but it it says it suppose to return false

### ISSUE THREAD

**Issue by rigox** [FreeCodeCamp/FreeCodeCamp#7010]
Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%7B%0A%20%20%20str.toLowerCase()%3B%0A%20%20%20var%20rgx%20%3D%20%2F%5Ba-z%5D%2Fgi%3B%0A%20%20%20var%20%20str2%3D%22%22%3B%0A%20%20%20var%20tokens%20%3D%5B%5D%3B%0A%20%20%20%20%0A%20%20tokens%20%3D%20str.split(%22%22)%3B%0A%20%20%0A%20%20%20for(var%20i%3D0%3Bi%3Ctokens.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20%20if(tokens%5Bi%5D.match(rgx))%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20str2%2B%3Dtokens%5Bi%5D.toLowerCase()%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%20%20%20%20var%20i1%20%3D0%3B%0A%20%20%20%20%20var%20i2%3Dstr2.length-1%3B%0A%20%20%20%20%20str2.toLowerCase()%3B%0A%20%20%20%20%20while(i2%3Ei1)%7B%0A%20%20%20%20%20%20%20%20%20%20if(str2.charAt(i1)!%3Dstr2.charAt(i2))%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(str2)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%0A%20%20%20%20%20i1%2B%2B%3B%0A%20%20%20%20%20i2--%3B%0A%20%20%20%20%20%7D%0A%20%20%20%0A%20%20%0A%20%20%20%20console.log(str2)%3B%0A%20%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%221%20eye%20for%20of%201%20eye%22.toLowerCase())%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str){
   str.toLowerCase();
   var rgx = /[a-z]/gi;
   var  str2="";
   var tokens =[];
    
  tokens = str.split("");
  
   for(var i=0;i<tokens.length;i++){
       if(tokens[i].match(rgx)){
            str2+=tokens[i].toLowerCase();
       }
   }
     var i1 =0;
     var i2=str2.length-1;
     str2.toLowerCase();
     while(i2>i1){
          if(str2.charAt(i1)!=str2.charAt(i2)){
             console.log(str2);
              return false;
          }
       
     
     i1++;
     i2--;
     }
   
  
    console.log(str2);
   return true;
}



palindrome("1 eye for of 1 eye".toLowerCase());
```

**Comment by ltegman** [comment]
You should not be removing numbers. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to confirm what you're seeing is a site issue before filing a bug. Thanks and happy coding!
