### ISSUE TITLE
code should work but does not compile

### ISSUE THREAD

**Issue by kilik42** [FreeCodeCamp/FreeCodeCamp#7018]
Challenge [Multiple Identical Options in Switch Statements](http://www.freecodecamp.com/challenges/multiple-identical-options-in-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20switch%20(val)%7B%0A%20%20%20%20%20%20case%201%3A%20%0A%20%20%20%20%20%20case%202%3A%20%0A%20%20%20%20%20%20case%203%3A%20%0A%20%20%20%20%20%20%20%20result%20%3D%20%22Low%22%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%204%3A%20%0A%20%20%20%20%20%20case%205%3A%0A%20%20%20%20%20%20case%206%3A%0A%20%20%20%20%20%20%20%20result%20%3D%20%22Mid%22%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%207%3A%0A%20%20%20%20%20%20case%208%3A%0A%20%20%20%20%20%20case%209%3A%0A%20%20%20%20%20%20%20%20result%20%3D%20%22High%22%3B%0A%20%20%20%20%20%20%20%20%0A%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  
  switch (val){
      case 1: 
      case 2: 
      case 3: 
        result = "Low";
        break;
      case 4: 
      case 5:
      case 6:
        result = "Mid";
        break;
      case 7:
      case 8:
      case 9:
        result = "High";
        

  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(1);


```

**Comment by sludge256** [comment]
The variable you are returning is not being modified by you switch statement.
Please ask in the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to verify that your issue really is a bug before posting on Github. Thank you.

**Comment by mohannadsawalhi** [comment]
WITHOUT BREAK;

**Comment by readytohackk** [comment]
use return

**Comment by Chrisophogus** [comment]
I think this is an issue.
The example code is:

`switch(val) {
  case 1:
  case 2:
  case 3:
    result = "1, 2, or 3";
    break;
  case 4:
    result = "4 alone";
}`

But to complete the challenge your code should be:

`switch (val)   {
  case 1:
  case 2:
  case 3:
    return "Low";
  case 4:
  case 5:
  case 6:
    return "Mid";
  case 7:
  case 8:
  case 9:
    return "High";
}
  `

Or at least that's what I used to pass. Initially my code was as kilik42 above. It was only by searching around that I discovered what I needed to be doing. Whilst the initial description does state "until a break is encountered" the example doesn't match that.
