### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue 

### ISSUE THREAD

**Issue by AlecDataLocker** [FreeCodeCamp/freecodecamp#702]
The initial instructions request creating a placeholder tag that reads "type a cat photo URL here", whereas the validation instructions say to use "cat photo URL". Both work properly but the instructions are ambiguous about what's requested.

**Comment by terakilobyte** [comment]
Thanks, fixed.
