### ISSUE TITLE
Tests aren't showing up for camper, possible CSP issue

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7022]
From the camper, whose tests aren't showing up: 

I have been trying to learn from freeCodeCamp for long time now but Run Test Button is not responding. 

I have already tried on different devices and even deleted my old account and created a new one still the problem persists.

I'm using Ubuntu 14.04 on Dell Laptop, Chrome as browser
Location:: Delhi, India

![](https://www.evernote.com/l/Ar_uWnPk8sZLgou9QaoMJ30Gvi-iolj-bTIB/image.png)

**Comment by bugron** [comment]
@QuincyLarson did the camper try to follow https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc?

**Comment by QuincyLarson** [comment]
@bugron awesome - thanks for the fast feedback. I've emailed him this article, and once he emails me back in the affirmative, I'll close this issue.

**Comment by QuincyLarson** [comment]
@bugron that fixed it. Thanks!
