### ISSUE TITLE
Find the Longest Word in a String has an issue

### ISSUE THREAD

**Issue by TeoBouvard** [FreeCodeCamp/FreeCodeCamp#7026]
Challenge [Find the Longest Word in a String](http://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20maxLength%20%3D%200%3B%0A%0Afunction%20findLongestWord(str)%20%7B%0A%20%20array%20%3D%20str.split(%22%20%22)%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20array.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(array%5Bi%5D.length%20%3E%20maxLength)%20%7B%0A%20%20%20%20%20%20maxLength%20%3D%20array%5Bi%5D.length%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20maxLength%3B%0A%7D%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var maxLength = 0;

function findLongestWord(str) {
  array = str.split(" ");
  for (i = 0; i < array.length; i++) {
    if (array[i].length > maxLength) {
      maxLength = array[i].length;
    }
  }
  return maxLength;
}

findLongestWord("May the force be with you");

```

**findLongestWord("May the force be with you") should return 5 is not accepted but the code indeed return 5.**

![capture d ecran 2016-02-15 a 13 03 02](https://cloud.githubusercontent.com/assets/17164058/13048196/91292814-d3e4-11e5-8322-82a138fd77c7.png)

**Comment by bugron** [comment]
While the solution is correct that test fails because your `maxLength` variable is defined globally. Move the definition into your function.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.
