### ISSUE TITLE
Run test doesn't work after doing the challenge 

### ISSUE THREAD

**Issue by saeidalidadi** [FreeCodeCamp/FreeCodeCamp#7027]
Challenge [Comment out HTML](http://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

```

**Comment by erictleung** [comment]
I would reread the instructions a little more carefully:

> Comment out your `h1` element and your `p` element, but leave your `h2` element uncommented.

Good luck!

**Comment by ltegman** [comment]
Closing as not a site issue. Thanks and happy coding!
