### ISSUE TITLE
the code is correct(since it is working for all other other examples) but only this example(where([5, 3, 20, 3], 5);) is not working. 

### ISSUE THREAD

**Issue by iamharshit** [FreeCodeCamp/FreeCodeCamp#7029]
Challenge [Where do I belong](http://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20arr.sort()%3B%0A%20%20var%20ans%3Darr.length%3B%0A%20%20for(var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%7B%0A%20%20%20%20if(num%3C%3Darr%5Bi%5D)%7B%0A%20%20%20%20%20%20ans%3Di%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0A%2F%2Fwhere(%5B40%2C%2060%5D%2C%2050)%3B%0Awhere(%5B5%2C%203%2C%2020%2C%203%5D%2C%205)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(arr, num) {
  // Find my place in this sorted array.
  arr.sort();
  var ans=arr.length;
  for(var i=0;i<arr.length;i++){
    if(num<=arr[i]){
      ans=i;
      break;
    }
  }
  
  return ans;
}

//where([40, 60], 50);
where([5, 3, 20, 3], 5);
```

**Comment by erictleung** [comment]
I would check what happens when you sort that troublesome array (i.e. `var arr = [5, 3, 20, 5];`) with your sorting code: `arr.sort();`. I hope that helps without giving too much away :) Good luck!

**Comment by yashdeeph709** [comment]
chrome has an issue  when i tried it on console it 
`[5, 3, 20, 3].sort();
[20, 3, 3, 5]`

**Comment by yashdeeph709** [comment]
In this case you have to provide a comparator 
like `function(a,b){a=parseInt(a);b=parseInt(b); if(a>=b){return -1}else{return 1}}`
> If compareFunction is not supplied, elements are sorted by converting them to strings and comparing strings in Unicode code point order. For example, "Cherry" comes before "banana". In a numeric sort, 9 comes before 80, but because numbers are converted to strings, "80" comes before "9" in Unicode order.
**MDN** `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort`

**Comment by yashdeeph709** [comment]
Somebody please close this issue its browser issue

**Comment by ltegman** [comment]
Closing as not a site issue. Thanks and happy coding!
