### ISSUE TITLE
Chunky Monkey needs randomly generated tests

### ISSUE THREAD

**Issue by willnwhite** [FreeCodeCamp/FreeCodeCamp#7031]
Challenge [Chunky Monkey](http://www.freecodecamp.com/challenges/chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20var%20chunks%20%3D%20%5B%5D%3B%0A%20%20chunks.push(arr.slice(0*size%2C%20size))%3B%0A%20%20chunks.push(arr.slice(size%2C%202*size))%3B%0A%20%20if%20(arr.length%20%3E%202*size)%20%7B%0A%20%20%20%20%20%20chunks.push(arr.slice(2*size%2C%203*size))%3B%0A%20%20%7D%0A%20%20return%20chunks%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0</code>.

My code:
```javascript
function chunk(arr, size) {
  var chunks = [];
  chunks.push(arr.slice(0*size, size));
  chunks.push(arr.slice(size, 2*size));
  if (arr.length > 2*size) {
      chunks.push(arr.slice(2*size, 3*size));
  }
  return chunks;
}

```
This very naive code passes the tests, and I don't think it should. This would fail randomly generated tests (arrays of random lengths, random integers).

**Comment by JoshFisk** [comment]
The problem with the tests is they all require between 2, and 3 arrays. Mix the tests to require between 1, and 10 arrays, and the loop-less solution is a lot more painful to write.

**Comment by willnwhite** [comment]
Isn't this exercise supposed to be about teaching you to use a loop when 
there is an indefinite number of something?

**Comment by JoshFisk** [comment]
@willnwhite It is possible to avoid a loop by unwrapping the loop enough times to pass the test.

After rethinking it though, the test could just look at the solution for a loop directly.

**Comment by willnwhite** [comment]
@JoshFisk By unwrapping the loop, do you mean what my code does?

**Comment by JoshFisk** [comment]
@willnwhite Yes, you could unwrap a loop very far if you don't mind the code getting bigger, that's why it should just check that they are using a loop.

**Comment by erictleung** [comment]
This challenge is only in the Basic Algorithm section so I don't think it should be too extremely difficult. I think the tests are sufficient but I guess we could add one or two tests on an output with more than 3 arrays. @FreeCodeCamp/issue-moderators thoughts?

**Comment by SaintPeter** [comment]
I think it would be reasonable to add a test with 4 or 5 "chunks".

**Comment by daniel-chung** [comment]
I added a 5 "chunk" test. The original code of @willnwhite now fails this new test.

**Comment by daniel-chung** [comment]
Sorry I closed the issue because I have another PR pending. Given that it addresses a very different issue I didn't want to combine the two requests (unless you disagree). I temporarily closed PR with the intension of reopening once the other PR is handled.

**Comment by raisedadead** [comment]
@daniel-chung dono't close any issues or PR's without any confirmation. 
Let issue-moderators give their insights.

**Comment by daniel-chung** [comment]
@raisedadead Gotcha, thanks for the advice. This is my first time going through the rodeo so I'm still trying to figure things out :)
I'll reopen the PR and cc issue-moderators

**Comment by daniel-chung** [comment]
@raisedadead @FreeCodeCamp/issue-moderators: Actually I realized I reverted the commits on this branch for this PR so I think I'd need to submit a new PR. Given that, I think it's probably easiest to delete PR #8984 and start over, but let me know what you think.

**Comment by ialmost** [comment]
`function chunk(arr, size) {
  // Break it up.
  var newArr = [];
  for ( var i = 0, m = size; i < arr.length; i+=size,m+=size ) {
    newArr.push(arr.slice(i,m));
  }
  return newArr;
}

chunk(["a", "b", "c", "d"], 2);`

**Comment by ogora** [comment]
This code is wrong but it works
`function chunkArrayInGroups(arr, size) {

  var arr2 = [];
  for(var i = 0; i= arr.length; i++) {
    arr2.push(arr.slice(0, size));
    arr = arr.slice(size);
  }
  return arr2;
 
}

chunkArrayInGroups(["a", "b", "c", "d"], 2);
`

**Comment by willnwhite** [comment]
@ogora What's wrong with that code?

**Comment by ogora** [comment]
@willnwhite  Notice that in the  loop, I put a  "=" instead of an acceptable operator like '<' '>' ' ==' etc accoridng to what we learnt on FCC.  So  the FCC JS hint points out that the operator is wrong but  still accepts the solution and passes.  So my problem with some of these solutions; you get it right or wrong but there is nothing to tell you why you got it right or why a solution that looks right passes.
