### ISSUE TITLE
Feature Request::: add estimated hours required as shown on Map to camper's code portfolio page

### ISSUE THREAD

**Issue by rickstewart** [FreeCodeCamp/FreeCodeCamp#7035]
It would be great if potential employers, as an example, would see the estimated hours required to complete the work being showcased when you give someone a link to your personal portfolio page. Currently it gives your Current and Longest Streak, the option to View 'my project' and View 'solution' for Projects, Algorithms, and Challenges, but does not give the viewer any idea how much work potentially went into achieving it. 

I believe it would be a great selling feature for campers trying to get recognition for all their hard work when having 'outsiders' visiting and reviewing their work.

**Comment by bugron** [comment]
@rickstewart I think we already have certificates for that. Are you talking about how much estimated from 'theoretical' 2000+ hours?

**Comment by ltegman** [comment]
I'm closing this as a previous feature request for this was closed by Quincy not long ago. You can see the details at #6236. Thanks and happy coding!
