### ISSUE TITLE
no colon is being used yet works well??

### ISSUE THREAD

**Issue by senthilbalajijndr** [FreeCodeCamp/FreeCodeCamp#7038]
```
<style>
  h2{color:brown}
  h2{text-align:center}
  h2{background-color:red}
  p{text-align:center}
  p{background-color:blue}
  p{color:yellow}
  </style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by ltegman** [comment]
Please give use more details like what challenge you are working on and a more thorough description of what you think the problem is.

**Comment by bugron** [comment]
@senthilbalajijndr thanks for posting this issue!
Feel free to reopen with more details about the issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
