### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue 

### ISSUE THREAD

**Issue by skmullins** [FreeCodeCamp/freecodecamp#704]
The following HTML is not working for this challenge:
<style>
  .smaller-image {
    width: 100px;
  }
  
  .thick-green-border{
    border-width: 10px; 
    border-color: green;
    border-style: solid;
  }
</style>
<img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>

I'm not sure what I'm doing wrong?

**Comment by terakilobyte** [comment]
Are you adding your class to the image? This code plus adding the class to the image is working just fine for me.

**Comment by andytruett** [comment]
Issue duplicated for me in Firefox 38.0.1 on Win7x64. Worked in Chrome.

Firefox dev tools show TypeError: e is undefined inspectlet.js:27:29717

**Comment by matejhegedus** [comment]
I have the same issue in Firefox 38.0.1. Works in Chrome.
The test "You need to specify a border width of 10px and a border style of "solid"." is not passing.

**Comment by andytruett** [comment]
Screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/7491207/7870314/76525978-0556-11e5-93e3-206f808198c1.jpg)

**Comment by LumenTeun** [comment]
This issue was blocked on the Waffle Board, so I didn't want to make a pull request right away, but I seem to have fixed this issue [here](https://github.com/LumenTeun/freecodecamp/commit/c7bcfd363039bdce5637052bf71952d24e3195f0).
I've tried it on Firefox 38.0.1 and Chromium 43.0.2357.

**Comment by QuincyLarson** [comment]
I've fixed this issue. Thanks everyone!
