### ISSUE TITLE
Data visualization project idea

### ISSUE THREAD

**Issue by brianamarie** [FreeCodeCamp/FreeCodeCamp#7040]
I just found this site for calculating college costs, and all of it is open source on GH. 
http://www.college-costs.com/
https://github.com/cuthbertLab/collegeCosts

I'm not sure if we could reach out to the creator of this to see about his thoughts on this being a data vis challenge, but I think that campers could come up with some really cool ways of displaying this information.

**Comment by QuincyLarson** [comment]
@brianamarie great idea. We can consider doing this later through curriculum expansion.
