### ISSUE TITLE
I get the write answer each time... but it doesnt accept?

### ISSUE THREAD

**Issue by CamMakoJ** [FreeCodeCamp/FreeCodeCamp#7043]
Challenge [Find the Longest Word in a String](http://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=function%20findLongestWord(str)%20%7B%0A%20%20var%20strArray%20%3D%20str.split('%20')%3B%0A%09console.log(strArray)%3B%0A%20%20%2F%2Ffunction%20for%20array%20words%20to%20lengths%0A%20%0A%20%20var%20arrayNum%20%3D%20function(array)%20%7B%0A%20%20%20%20for%20(i%20%3D%200%3B%20i%20%3C%20array.length%3B%20i%2B%2B)%20%7B%0A%20%20%2F%2F%20%20console.log(array%5Bi%5D)%3B%0A%20%20%20%20array%5Bi%5D%20%3D%20array%5Bi%5D.length%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%20array%3B%0A%20%20%7D%3B%0A%09var%20x%20%3D%20arrayNum(strArray)%3B%0A%20%20console.log(x)%3B%0A%09x.sort()%3B%0A%09%20%20console.log(x)%3B%0A%20%20str%20%3D%20x%5Bx.length-1%5D.toString()%3B%0A%20%20%20console.log(str)%3B%0A%20%20%20return%20str%3B%0A%7D%0A%0A%0AfindLongestWord(%22The%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function findLongestWord(str) {
  var strArray = str.split(' ');
	console.log(strArray);
  //function for array words to lengths
 
  var arrayNum = function(array) {
    for (i = 0; i < array.length; i++) {
  //  console.log(array[i]);
    array[i] = array[i].length;
       }
      return array;
  };
	var x = arrayNum(strArray);
  console.log(x);
	x.sort();
	  console.log(x);
  str = x[x.length-1].toString();
   console.log(str);
   return str;
}


findLongestWord("The quick brown fox jumped over the lazy dog");

```

**Comment by raisedadead** [comment]
At the line `str = x[x.length-1].toString();` you are returning a string, no doubt the output appears correct, yet its still a string.

The instructions clearly state:
> Your response should be a number.

If you are still stuck, please ask for help at [Help Chat](https://gitter.im/FreeCodeCamp/Help)

Thanks.

**Comment by CamMakoJ** [comment]
Much appreciated - once that was fixed i also noticed that for numbers >10 i had to adjust to get it to sort numerically instead of lexicographically
