### ISSUE TITLE
NaN issue 

### ISSUE THREAD

**Issue by feliksone** [FreeCodeCamp/FreeCodeCamp#7045]
if NaN is not a number all strings should be removed. What does mean NaN in Falsy Bouncer??
Falsy values in JavaScript are false, null, 0, "", undefined, and NaN. 
But all string values should stay the tips says, 
isNaN('string') == true;
sorry I don`t undestand this. Or strings or numbers, where is my misunderstanding

**Comment by JoshFisk** [comment]
"NaN" stands for "Not a Number".

You can use the Boolean function to convert anything into either true or false. A Falsey value is one that will convert to false when converted to a Boolean value.

As the instructions state "Falsy values in JavaScript are false, null, 0, "", undefined, and NaN."

This means that when converted to a Boolean value, these values will return false, and everything else will return true.

**Comment by ltegman** [comment]
`NaN` is a specific value that is falsy. It's not asking you to check if things are numbers but just to remove any instance of the value `NaN`. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need more help. Thanks and happy coding!
