### ISSUE TITLE
Serbian translation of Getting Started

### ISSUE THREAD

**Issue by stefanivic** [FreeCodeCamp/FreeCodeCamp#7049]
- [ ] Learn how Free Code Camp Works
- [ ] Create a GitHub Account and Join our Chat Rooms
- [ ] Configure your Code Portfolio
- [ ] Join a Campsite in Your City
- [ ] Learn What to Do If You Get Stuck

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #61](https://github.com/FreeCodeCamp/TranslationExpansion/issues/61) via [**ZenHub**](https://www.zenhub.com/)
