### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue 

### ISSUE THREAD

**Issue by AlecDataLocker** [FreeCodeCamp/freecodecamp#705]
Now let's get your form input and your submission button on the same line. We'll do this the same way we have previously: by using a "row" element with "col-xs-*" elements withing it.

"withing" should be corrected to "within"

**Comment by LumenTeun** [comment]
I can not find this, not on the website nor in the staging branch. I think it'd be safe to close this issue.

**Comment by BerkeleyTrue** [comment]
@LumenTeun Thanks!
