### ISSUE TITLE
Serbian translation of HTML5 and CSS

### ISSUE THREAD

**Issue by stefanivic** [FreeCodeCamp/FreeCodeCamp#7050]
- [ ] Say Hello to HTML Elements Complete
- [ ] Headline with the h2 Element Complete
- [ ] Inform with the Paragraph Element Complete
- [ ] Uncomment HTML Complete
- [ ] Comment out HTML Complete
- [ ] Fill in the Blank with Placeholder Text Complete
- [ ] Delete HTML Elements Complete
- [ ] Change the Color of Text Complete
- [ ] Use CSS Selectors to Style Elements Complete
- [ ] Use a CSS Class to Style an Element Complete
- [ ] Style Multiple Elements with a CSS Class Complete
- [ ] Change the Font Size of an Element Complete
- [ ] Set the Font Family of an Element Complete
- [ ] Import a Google Font Complete
- [ ] Specify How Fonts Should Degrade Complete
- [ ] Add Images to your Website Complete
- [ ] Size your Images Complete
- [ ] Add Borders Around your Elements Complete
- [ ] Add Rounded Corners with a Border Radius Complete
- [ ] Make Circular Images with a Border Radius Complete
- [ ] Link to External Pages with Anchor Elements Complete
- [ ] Nest an Anchor Element within a Paragraph Complete
- [ ] Make Dead Links using the Hash Symbol Complete
- [ ] Turn an Image into a Link Complete
- [ ] Add Alt Text to an Image for Accessibility Complete
- [ ] Create a Bulleted Unordered List Complete
- [ ] Create an Ordered List Complete
- [ ] Create a Text Field Complete
- [ ] Add Placeholder Text to a Text Field Complete
- [ ] Create a Form Element Complete
- [ ] Add a Submit Button to a Form Complete
- [ ] Use HTML5 to Require a Field Complete
- [ ] Create a Set of Radio Buttons Complete
- [ ] Create a Set of Checkboxes Complete
- [ ] Check Radio Buttons and Checkboxes by Default Complete
- [ ] Nest Many Elements within a Single Div Element Complete
- [ ] Give a Background Color to a Div Element Complete
- [ ] Set the ID of an Element Complete
- [ ] Use an ID Attribute to Style an Element Complete
- [ ] Adjusting the Padding of an Element Complete
- [ ] Adjust the Margin of an Element Complete
- [ ] Add a Negative Margin to an Element Complete
- [ ] Add Different Padding to Each Side of an Element Complete
- [ ] Add Different Margins to Each Side of an Element Complete
- [ ] Use Clockwise Notation to Specify the Padding of an Element Complete
- [ ] Use Clockwise Notation to Specify the Margin of an Element Complete
- [ ] Style the HTML Body Element Complete
- [ ] Inherit Styles from the Body Element Complete
- [ ] Prioritize One Style Over Another Complete
- [ ] Override Styles in Subsequent CSS Complete
- [ ] Override Class Declarations by Styling ID Attributes Complete
- [ ] Override Class Declarations with Inline Styles Complete
- [ ] Override All Other Styles by using Important Complete
- [ ] Use Hex Code for Specific Colors Complete
- [ ] Use Hex Code to Color Elements White Complete
- [ ] Use Hex Code to Color Elements Red Complete
- [ ] Use Hex Code to Color Elements Green Complete
- [ ] Use Hex Code to Color Elements Blue Complete
- [ ] Use Hex Code to Mix Colors Complete
- [ ] Use Hex Code to Color Elements Gray Complete
- [ ] Use Hex Code for Specific Shades of Gray Complete
- [ ] Use Abbreviated Hex Code Complete
- [ ] Use RGB values to Color Elements Complete
- [ ] Use RGB to Color Elements White Complete
- [ ] Use RGB to Color Elements Red Complete
- [ ] Use RGB to Color Elements Green Complete
- [ ] Use RGB to Color Elements Blue Complete
- [ ] Use RGB to Mix Colors

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #62](https://github.com/FreeCodeCamp/TranslationExpansion/issues/62) via [**ZenHub**](https://www.zenhub.com/)
