### ISSUE TITLE
updating social media link

### ISSUE THREAD

**Issue by Michael-Morris-1** [FreeCodeCamp/FreeCodeCamp#7052]
I've changed my twitter username from mkemo8870 to Mike_Morris_1. How can I update this to my twitter icon on my free code camp profile?

**Comment by bugron** [comment]
@Michael-Morris-1 I think there should be a button like this
![](http://i.imgur.com/mueHiYO.png)
but for Twitter.

**Comment by QuincyLarson** [comment]
@Michael-Morris-1 the only way you can currently update things that don't come from GitHub is to email team@freecodecamp.com - I will go ahead and take care of this for you. I will delete your old Twitter oauth instance and you can sign into the correct Twitter account and re-link it.

**Comment by Michael-Morris-1** [comment]
@QuincyLarson Thank You.
