### ISSUE TITLE
Local Scope and Functions - console.log line removed from outside function but does not pass

### ISSUE THREAD

**Issue by brtong** [FreeCodeCamp/FreeCodeCamp#7053]
Challenge [Local Scope and Functions](http://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%20'use%20strict'%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%2F%2F%20now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 'use strict';
  
  
  console.log(myVar);
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction

// now remove the console log line to pass the test


```

**Comment by sludge256** [comment]
Try refreshing the page.

**Comment by bugron** [comment]
@brtong thanks for posting this issue!
Not sure what is the issue but I don't think this is something withe the site. Closing this issue.
`use strict` is used to enable a special JS mode, see [this article](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Strict_mode) (not related to this issue, though).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
