### ISSUE TITLE
Create a custom Heading

### ISSUE THREAD

**Issue by EdnaMode** [FreeCodeCamp/FreeCodeCamp#7054]
i am getting this error mess

![image](https://cloud.githubusercontent.com/assets/15369700/13065406/01406562-d454-11e5-82b6-73696751ff6f.png)

my code is
![image](https://cloud.githubusercontent.com/assets/15369700/13065487/c8ec16ce-d454-11e5-8812-4945547f0bbf.png)
![image](https://cloud.githubusercontent.com/assets/15369700/13065494/e086a4e8-d454-11e5-9385-37f146b17d35.png)

**Comment by revisualize** [comment]
<div class="col-xs-8"><h2 class="text-primary text-center">CatPhotoApp</h2></div>

**Comment by sludge256** [comment]
Closing as discussion is taking place on Gitter. In the future, please ask in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) as Github issues are for site related bugs and discussions not coding help.

**Comment by EdnaMode** [comment]
k thks brian
