### ISSUE TITLE
Typo in Video Challenges - Computer Basics - Routers and Packets

### ISSUE THREAD

**Issue by resolutedreamer** [FreeCodeCamp/FreeCodeCamp#7057]
The typo is at this link:
http://www.freecodecamp.com/videos/routers-and-packets

In the second question:
![image](https://cloud.githubusercontent.com/assets/3419924/13069180/099e0de4-d437-11e5-9a29-725ff4cd152c.png)

the word "pieces" is spelled incorrectly.

**Comment by bugron** [comment]
@resolutedreamer confirmed. Thanks for posting!

**Comment by resolutedreamer** [comment]
If I want to report a few more typos (on different URLs), should I keep posting them here or should I make a new Issue for each one?

**Comment by bugron** [comment]
@resolutedreamer you can either open new issues or just edit your first comment and rename this issue's title.

**Comment by resolutedreamer** [comment]
Okay, I'll finish going through what I plan to go through today and depending on how many typos I find I'll decide accordingly.
