### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue 

### ISSUE THREAD

**Issue by dreathe** [FreeCodeCamp/freecodecamp#706]
Seems to be a problem with the exercise. The pointers of bottom left appear the message "editor is not defined", and that dont provide enough feedback to finish the exercise.

**Comment by terakilobyte** [comment]
You'll need to perform a hard refresh, that will clear it up.

**Comment by dreathe** [comment]
Thank you for the quick reply. It is working as intended now for me :D
