### ISSUE TITLE
Lexington, MA Campsite is incorrect

### ISSUE THREAD

**Issue by brad-j** [FreeCodeCamp/FreeCodeCamp#7062]
The Lexington, MA Facebook campsite page seems to be for Lexington, KY, not MA. Thanks!

**Comment by bugron** [comment]
@hallaathrad can you check this one too, please?

**Comment by hallaathrad** [comment]
Fixed. :) Thanks for letting me know about this one @brad-j

**Comment by brad-j** [comment]
My pleasure! Keep up the awesome work.
