### ISSUE TITLE
Subtle change in font between paragraphs

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#7065]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  var bet = '';
  if(card<=6){
    count ++;
  } else if (!(card<=9)){
      count --;
  }
  bet = count > 0? ' Bet':' Hold';
  return count + bet;
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

![image](https://cloud.githubusercontent.com/assets/2754821/13080922/9cef3e18-d47f-11e5-8e9b-6cf7fa4bd365.png)

The paragraph after the table in the challenge also has smaller font thant the first paragraph.

**Comment by hallaathrad** [comment]
I'm on it
