### ISSUE TITLE
Stuck because of a comment

### ISSUE THREAD

**Issue by kal11** [FreeCodeCamp/FreeCodeCamp#7067]
Challenge [Uncomment HTML](http://www.freecodecamp.com/challenges/uncomment-html#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!-- Comment -->

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>


```

In this lesson if you make a comment at the first line you won't be able to proceed and you'll be stuck.

**Comment by ltegman** [comment]
This is expected. We have a test that says all trailing comments should be removed (which means all opening comments need to removed, or else everything would be commented). Thanks and happy coding!
