### ISSUE TITLE
Free Code Camp's Main Chat popover window hiding right side of screen

### ISSUE THREAD

**Issue by LXsource** [FreeCodeCamp/FreeCodeCamp#7070]
Set up someone with freecodecamp, but half of their screen is hidden with "Free Code Camp's Main Chat" popover window. Clicking X does nothing. Works ok on Ubuntu (my pc), but they don't have that and it's not working on Windows.

update: Used a popup blocker to block ASIDE elements. Should not be necessary though.

**Comment by bugron** [comment]
@LXsource I think you're experiencing the same thing as in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6256 (even if your browser is not Safari). Closing this issue, you can continue further discussion there. Thanks for posting.
