### ISSUE TITLE
Update CodePen and GitHub onboarding gifs

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7071]
Both of these sites recently changed their on-boarding. I will do this today - I just created this issue to keep everyone posted.

**Comment by M1kep** [comment]
Oooo, meant to make an issue about not being able to sign up to codepen with git-hub, but I'm pretty sure this should fix that.

**Comment by BerkeleyTrue** [comment]
Fixed.

Happy Coding!
