### ISSUE TITLE
Receiving "SyntaxError: Illegal break statement", yet no break statement being used...

### ISSUE THREAD

**Issue by Ramon-Carroll** [FreeCodeCamp/FreeCodeCamp#7072]
Challenge [Smallest Common Multiple](http://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%2F*%20This%20was%20a%20tough%20one%20for%20me.%0ALet's%20use%20the%20Euclidean%20Algorithm%20to%20first%20get%20the%20GCD%20and%20%0Athen%20use%20that%20to%20calculate%20the%20LCM%0AThis%20below%20function%20for%20obtaining%20the%20gcd%20was%20posted%20on%20StackOverflow%20by%20%22alex%22%20at%20%0Ahttps%3A%2F%2Fstackoverflow.com%2Fquestions%2F17445231%2Fjs-how-to-find-the-greatest-common-divisor%2F17445304%2317445304.%20%0A*%2F%0Afunction%20gcd(a%2C%20b)%20%7B%0A%20%20%20%20if%20(!b)%20%7B%0A%20%20%20%20%20%20%20%20return%20a%3B%0A%20%20%20%20%7D%20%20%20%20%0A%20%20%20%20return%20gcd(b%2C%20a%20%25%20b)%3B%0A%7D%0A%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20%20%20var%20newArr%20%3D%20%5B%5D%3B%20%2F*Will%20hold%20the%20range%20of%20numbers%20from%20arr%5B0%5D%20to%20arr%5B1%5D.*%2F%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20arr.sort(function(val1%2C%20val2)%20%7B%20%2F*Order%20the%20array%20from%20least%20to%20greatest.*%2F%0A%20%20%20%20%20%20%20%20return%20val1%20-%20val2%3B%0A%20%20%20%20%7D)%3B%0A%20%20%20%20%0A%20%20%20%20for%20(var%20i%20%3D%20arr%5B0%5D%3B%20i%20%3C%3D%20arr%5B1%5D%3B%20i%2B%2B)%20%7B%20%2F*Create%20the%20full%20range%20of%20values%20under%20consideration.*%2F%0A%20%20%20%20%20%20%20%20newArr.push(i)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%2F*Formula%20to%20use%20is%20LCM(a%2Cb)%20%3D%20a%20*%20b%20%2F%20GCD(a%2C%20b).%20%0A%20%20%20%20Reduce%20array%20by%20recursively%20applying%20the%20formula%20to%20%0A%20%20%20%20the%20first%20two%20values%20until%20there%20is%20only%20one%20value%20left.*%2F%0A%20%20%20%20return%20newArr.reduce(function(a%2C%20b)%20%7B%20%0A%20%20%20%20%20%20%20%20return%20(a%20*%20b)%20%2F%20(gcd(a%2C%20b))%3B%0A%20%20%20%20%7D)%3B%0A%7D%0A%0AsmallestCommons(%5B1%2C%205%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
I keep receiving this error: "SyntaxError: Illegal break statement." That doesn't make any sense, because my code isn't using a break statement anywhere, even in my for loop. The code works and passes all test cases when I log the output in the console. Am I missing something?

My code:
```javascript
/* This was a tough one for me.
Let's use the Euclidean Algorithm to first get the GCD and 
then use that to calculate the LCM
This below function for obtaining the gcd was posted on StackOverflow by "alex" at 
https://stackoverflow.com/questions/17445231/js-how-to-find-the-greatest-common-divisor/. 
*/
function gcd(a, b) {
    if (!b) {
        return a;
    }    
    return gcd(b, a % b);
}

function smallestCommons(arr) {
    var newArr = []; /*Will hold the range of numbers from arr[0] to arr[1].*/
        
    arr.sort(function(val1, val2) { /*Order the array from least to greatest.*/
        return val1 - val2;
    });
    
    for (var i = arr[0]; i <= arr[1]; i++) { /*Create the full range of values under consideration.*/
        newArr.push(i);
    }
    
    /*Formula to use is LCM(a,b) = a * b / GCD(a, b). 
    Reduce array by recursively applying the formula to 
    the first two values until there is only one value left.*/
    return newArr.reduce(function(a, b) { 
        return (a * b) / (gcd(a, b));
    });
}

smallestCommons([1, 5]);

```

**Comment by ltegman** [comment]
For some reason loopProtect is triggering on this code. You can disable it by putting a comment with `// noprotect` at the top of your code. For anyone wanting to look into this the loopProtect output is:
```
/* This was a tough one ;loopProtect.protect({ line: 1, reset: true }); for me.
Let's use the Euclidean Algorithm to first get the GCD and 
then use that to calculate the LCM
This below function for obtaining the gcd was posted on StackOverflow by "alex" at 
https://stackoverflow.com/questions/17445231/js-how-to-find-the-greatest-common-divisor/. 
*/
function gcd(a, b) {;
if (loopProtect.protect({ line: 1 })) break;

    if (!b) {
        return a;
    }    
    return gcd(b, a % b);
}

function smallestCommons(arr) {
    var newArr = []; /*Will hold the range of numbers from arr[0] to arr[1].*/

    arr.sort(function(val1, val2) { /*Order the array from least to greatest.*/
        return val1 - val2;
    });

    for (var i = arr[0]; i <= arr[1]; i++) { /*Create the full range of values under consideration.*/
        newArr.push(i);
    }

    /*Formula to use is LCM(a,b) = a * b / GCD(a, b). 
    Reduce array by recursively applying the formula to 
    the first two values until there is only one value left.*/
    return newArr.reduce(function(a, b) { 
        return (a * b) / (gcd(a, b));
    });
}

smallestCommons([1, 5]);
```

**Comment by Ramon-Carroll** [comment]
Yep, that got it working. Thank you so much! :)

**Comment by raisedadead** [comment]
@ltegman Actually its quite strange with the loop protect logic.
I could pass this challenge with @Ramon-Carroll 's code, without error with a slight change. i.e I added `//` at the top.
```
//
/* This was a tough one for me.
Let's use...
...
...
```

If you notice in your snippet with the loopProtect output
```javascript
...
...
*/
function gcd(a, b) {;
if (loopProtect.protect({ line: 1 })) break;

    if (!b) {
```

there is a `;` after the `function gcd(a, b) {`, which is added by loopProtect.
Perhaps we might need to revisit the way we are eveluating the code from codemirror, i.e `head + code + tail` which is passed through loopProtect.

I'll check further and getback.

**Comment by raisedadead** [comment]
Apparently, as I checked removing the text from the comment block i.e
```javascript
/*

*/
function gcd(a, b) {
```
lets me pass the code.
Digging deeper, I saw that codemirror live refreshes the challenge solution that's encoded in the URL.

I believe there is something that's making this to break the loopProtect logic.

I am not very sure where we are decoding the URL. Can anyone point me to the correct place?
I must admit the archi is a bit complex :sweat_smile: to understand in one go!

**Comment by garbark** [comment]
Please stop sending me the page I don't know what to do with the page all
day I have not been on the page at all thank you for being there for me

Gary M Barker

**Comment by raisedadead** [comment]
@garbark You are recieving this page because you may have accidentally clicked the "Watch" button.
Please visit the https://github.com/FreeCodeCamp/FreeCodeCamp and select "Not Watching"

Refer the screenshot below:
![watcher_picker](https://cloud.githubusercontent.com/assets/1884376/13188974/bff3b710-d77a-11e5-9459-fb73c3879a8e.gif)

**Comment by QuincyLarson** [comment]
This is still relevant, but it only affects a few people. We'll keep this open. Does anyone want to tackle it?

**Comment by ltegman** [comment]
Assuming our power doesn't go out with the incoming NW storm I can take a look at this in the next couple of days. Anyone else is free to take it though since I may or may not lose power.
