### ISSUE TITLE
Answer provided 

### ISSUE THREAD

**Issue by deedbr72** [FreeCodeCamp/FreeCodeCamp#7074]
When I click on the challenge the answer is completed for me.

**Comment by ltegman** [comment]
If this is the case that means you or someone else has already either visited that challenge from another users profile or already completed the challenge. Challenges are pulled from localStorage, so this is not something we can influence.

In the future please file a more informative bug by following our [guide](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue)
