### ISSUE TITLE
 Global Scope and Functions

### ISSUE THREAD

**Issue by sivanyac2** [FreeCodeCamp/FreeCodeCamp#7078]
Challenge [Global Scope and Functions](http://www.freecodecamp.com/challenges/global-scope-and-functions#?solution=%2F%2F%20Declare%20your%20variable%20here%0Avar%20myGlobal%20%3D%2010%3B%0AoopsGlobal()%3B%0A%20%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20function%20fun1()%7B%0A%20%20%20%0A%20%20%20%20oopsGlobal%20%3D%205%3B%0A%0A%20%20%7D%0A%0A%0A%0Aconsole.log(myGlobal)%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20myGlobal()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if%20(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if%20(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Declare your variable here
var myGlobal = 10;
oopsGlobal();
  // Assign 5 to oopsGlobal Here
 function fun1(){
   
    oopsGlobal = 5;

  }



console.log(myGlobal);


// Only change code above this line
function myGlobal() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

```

**Comment by sivanyac2** [comment]
I can't seem to get the output for this waypoint and I think reset it many times.

**Comment by bugron** [comment]
Console thrown an error: `TypeError: ooopsGlobal is not a function`, start from there.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

**Comment by coderkak** [comment]
pls remove oopsGlobal(); from there problem solve
