### ISSUE TITLE
Challenge gets completed 

### ISSUE THREAD

**Issue by spaceguy707** [FreeCodeCamp/FreeCodeCamp#7081]
On my map when I click next its says there is a problem and the assignment is completed. This pretty much makes the site impossible to use. I deleted my old account because I had forgotten some of the old information and a massive update came.

**Comment by QuincyLarson** [comment]
@spaceguy707 we have an issue where there's a "something went wrong" issue that happens once every 5 or so attempts to submit. We are working hard to fix this. Is this the issue you're talking about?

**Comment by hallaathrad** [comment]
The Oops of doom seems to have been resolved, so I'm closing this issue until we confirm the problem is either back or of a different nature.
