### ISSUE TITLE
New dataset for Force-Directed Graph challenge

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7082]
We are retiring Camper News, so we need a new dataset for our Force-Directed Graph challenge (~~http://www.freecodecamp.com/challenges/show-relationships-with-a-force-directed-graph~~).
- [x] Identify an appropriate dataset (preferably a static one, which we can host on FCC)
- [x] implement a working CodePen demo of it
- [ ] I will fork it and record an updated video for it

Update by @raisedadead
Challenge has been replaced with new data set and has been renamed, its available now at
https://www.freecodecamp.com/challenges/show-national-contiguity-with-a-force-directed-graph

We now need a updated video of it.
/cc @Septimus

**Comment by evaristoc** [comment]
campsites?

**Comment by AndrewGHC** [comment]
I've created a dataset for this concept based on the Kevin Bacon Number. That is, actors' proximity to Kevin Bacon based on films they've been in.

Working CodePen example is [here](http://codepen.io/AndrewGHC/pen/mPXjKr). Data is [here](https://github.com/AndrewGHC/kevin-bacon-number/blob/master/kevinBacon.json) and the example is prepared such that it will still work even if the data is modified. Feel free to fork it.

**Comment by erictleung** [comment]
@QuincyLarson what do you think about @AndrewGHC's example? If you need a network-related dataset, there's a [network data repository by UC Irvine](http://networkdata.ics.uci.edu/) designed "to facilitate the scientific study of networks."

**Comment by edward-hong** [comment]
@QuincyLarson any update on this issue? I only need to finish this project to get my dataviz certificate, but I don't want to complete it and have Camper News API get retired afterwards

**Comment by raisedadead** [comment]
Challenge has been replaced with new data set and has been renamed, its available now at
https://www.freecodecamp.com/challenges/show-national-contiguity-with-a-force-directed-graph

We now need a updated video of it.
/cc @Septimus @QuincyLarson

**Comment by atjonathan** [comment]
@QuincyLarson, please record this and send it over to me or Septimus to review.

**Comment by QuincyLarson** [comment]
@atjonathan OK - I will record this when I do the HyperDev work in a few days. Added to my todo list :)

**Comment by QuincyLarson** [comment]
We are removing videos from the updated curriculum, so I won't record a new video for this. So this issue is resolved. Thanks for everyone's help.
