### ISSUE TITLE
Changelog? Versioning?

### ISSUE THREAD

**Issue by shian48263** [FreeCodeCamp/FreeCodeCamp#7084]
For nearly a year following FCC, bit by bit, I found that FCC is slowly transforming into a bigger and bigger network as time passes by. JavaScript community in itself is experiencing several major shifts in 2015, majorly ES6 and React, and I can feel FCC is trying to follow the trend too, and surely getiing better and better.

In last year, the map has undergone several major changes. For a newcomer, he/she may not have known about the shifts. However, for a current old camper, it is sometimes frustrating not being able to review the old map, as being used to it. For examples, shifting from Angular to React, angular-fullstack to clementine, etc. I know this can be overcome by reviewing old issues and commits on GitHub, but this method is still a mess.

The JavaScript community will still be in rapid constant changes in 2016 for Angular 2 is going to release soon (maybe?). So, in my opinion, maybe it is always good and better to keep track on what has changed on the map for fellow campers to be able to review the changes when needed.

**Comment by AkiraLaine** [comment]
@shian48263 FCC does keep a "changelog" per say. Our monthly Saturday Summit is used to tell users of changes occurring at FCC and things that are being worked on/planned for later release. We also write up Wiki articles going over these same changes.

A new wouldn't need to know about the previous Map versions (I don't quite see the point). And I'm not sure why you would want to review any "old" Maps.
