### ISSUE TITLE
Unique Names for Algorithm Function Challenges

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/FreeCodeCamp#7085]
@SaintPeter
In order to facilitate follow up in our chatrooms, better:
* to stick ALWAYS to unique names for the functions (specifically check those named "convert" and "where")
* names should be totally identifiable, perhaps adding a number in order to avoid any similarity with natural language (example "function repeats(..." is not a good naming)

**Comment by SaintPeter** [comment]
This is a great request for our helpers.

Function names should: 
* Be globally unique within Free Code Camp
* Be generally unique - not a common function name in the FCC codebase
* Not be a single natural language word

Examples:
`where` => `whereBelong`
`convert`=> `convertToF`
`diff` => `diffArray`

Be sure when updating the code that you check:
* description
* challengeSeed
* tests
* solutions

Be sure to run `npm run test-challenges` after making the change to test.

We will also need to update corresponding Wiki articles.

When you make a change do not close this issue.  Do post here which one you are updating.  Do reference this issue number in your PR so we can track it.  Make sure your issue title has the challenge/bonfire name and "unique function name" in it.

### Initial List of Updates Needed
- [ ] Where do I belong
- [ ] Convert Celsius to Farhenheit
- [ ] Where art thou
- [ ] Diff Two Arrays

I'll come up with a more comprehensive list in a bit.

**Comment by SaintPeter** [comment]
Here is a comprehensive list of those that we should probably change.

File|Type|Title|Function
----|----|---|----
advanced-bonfires.json |Algorithm| Exact Change | drawer
advanced-bonfires.json |Algorithm| Inventory Update | inventory
advanced-bonfires.json |Algorithm| Friendly Date Ranges | friendly
basic-bonfires.json |Algorithm| Confirm the Ending | end
basic-bonfires.json |Algorithm| Repeat a string repeat a string | repeat
basic-bonfires.json |Algorithm| Truncate a string | truncate
basic-bonfires.json |Algorithm| Chunky Monkey | chunk
basic-bonfires.json |Algorithm| Where do I belong | where
basic-javascript.json |Algorithm| Convert Celsius to Fahrenheit | convert
basic-javascript.json |Challenge| Write Reusable JavaScript with Functions | ourFunction
basic-javascript.json |Challenge| Passing Values to Functions with Arguments | ourFunction
basic-javascript.json |Challenge| Local Scope and Functions | myFunction
basic-javascript.json |Challenge| Global vs. Local Scope in Functions | myFunction
basic-javascript.json |Challenge| Assignment with a Returned Value | change
basic-javascript.json |Challenge| Assignment with a Returned Value | process
basic-javascript.json |Algorithm| Stand in Line | queue
basic-javascript.json |Challenge| Use Conditional Logic with If Statements | ourFunction
basic-javascript.json |Challenge| Use Conditional Logic with If Statements | myFunction
basic-javascript.json |Challenge| Comparison with the Equality Operator | myTest
basic-javascript.json |Challenge| Comparison with the Strict Equality Operator | myTest
basic-javascript.json |Challenge| Comparison with the Inequality Operator | myTest
basic-javascript.json |Challenge| Comparison with the Strict Inequality Operator | myTest
basic-javascript.json |Challenge| Comparison with the Greater Than Operator | myTest
basic-javascript.json |Challenge| Comparison with the Greater Than Or Equal To Operator | myTest
basic-javascript.json |Challenge| Comparison with the Less Than Operator | myTest
basic-javascript.json |Challenge| Comparison with the Less Than Or Equal To Operator | myTest
basic-javascript.json |Challenge| Comparisons with the Logical And Operator | myTest
basic-javascript.json |Challenge| Comparisons with the Logical Or Operator | myTest
basic-javascript.json |Challenge| Introducing Else Statements | myTest
basic-javascript.json |Challenge| Introducing Else If Statements | myTest
basic-javascript.json |Challenge| Logical Order in If Else Statements | myTest
basic-javascript.json |Challenge| Chaining If Else Statements | myTest
basic-javascript.json |Challenge| Selecting from many options with Switch Statements | myTest
basic-javascript.json |Challenge| Adding a default option in Switch statements | myTest
basic-javascript.json |Challenge| Multiple Identical Options in Switch Statements | myTest
basic-javascript.json |Challenge| Replacing If Else Chains with Switch | myTest
basic-javascript.json |Algorithm| Record Collection | update
basic-javascript.json |Algorithm| Profile Lookup | lookUp
basic-javascript.json |Challenge| Generate Random Fractions with JavaScript | myFunction
basic-javascript.json |Challenge| Generate Random Whole Numbers with JavaScript | myFunction
basic-javascript.json |Challenge| Generate Random Whole Numbers within a Range | ourFunction
basic-javascript.json |Challenge| Create a JavaScript Slot Machine | runSlots
basic-javascript.json |Challenge| Add your JavaScript Slot Machine Slots | runSlots
basic-javascript.json |Challenge| Bring your JavaScript Slot Machine to Life | runSlots
basic-javascript.json |Challenge| Give your JavaScript Slot Machine some Stylish Images | runSlots
intermediate-bonfires.json |Algorithm| Diff Two Arrays | diff
intermediate-bonfires.json |Algorithm| Roman Numeral Converter | convert
intermediate-bonfires.json |Algorithm| Where art thou | where
intermediate-bonfires.json |Algorithm| Pig Latin | translate
intermediate-bonfires.json |Algorithm| DNA Pairing | pair
intermediate-bonfires.json |Algorithm| Boo who | boo
intermediate-bonfires.json |Algorithm| Sorted Union | unite
intermediate-bonfires.json |Algorithm| Convert HTML Entities | convert
intermediate-bonfires.json |Algorithm| Finders Keepers | find
intermediate-bonfires.json |Algorithm| Drop it | drop
intermediate-bonfires.json |Algorithm| Everything Be True | every
intermediate-bonfires.json |Algorithm| Arguments Optional | add

**Comment by ltegman** [comment]
@SaintPeter Do we need to worry about the non-algorithm function names, like all the `myTest` ones?

**Comment by SaintPeter** [comment]
@ltegman I'm not sure.  I included them for completeness.  I figure if we're going to look for unique function names, we might as well be through.  I don't know that we get many questions on those.

@evaristoc Check out the complete list here:
[functionNames.xlsx](https://github.com/FreeCodeCamp/FreeCodeCamp/files/135025/functionNames.xlsx)

Let me know if you disagree with my list above.  We can certainly edit it to remove some.

**Comment by alistermada** [comment]
I want to point out that changing the names of the functions makes our solutions incorrect. Not really a big deal since it doesn't affect completion, but still worth noting.

We'll also have to update the wiki with the new function names.

**Comment by TylerMoeller** [comment]
I'm wondering if it's possible to update everyone's solutions now that function names are changing, or let the tests continue to validate the older function names. Several of my solutions are not passing any more because the older function names are still in use, but the tests are expecting the new function names in the code. For example: <a href="https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=function%20end(str%2C%20target)%20%7B%0A%20%20return%20str.substring(str.length%20-%20target.length)%20%3D%3D%3D%20target%3B%0A%7D%0Aend(%22Bastian%22%2C%20%22n%22%2C%20%22%22)%3B">My solution to Confirm The Ending</a>.

**Comment by SaintPeter** [comment]
@TylerMoeller No, it's not really possible, especially since some of the old function names are actually the names of actual JS functions, or plain english words which appear inside of other challenges.

We have made changes in the past to challenges and we will make them in the future.  Yes it causes some consternation, but it's better to move forward then to dwell in the past.

**Comment by TylerMoeller** [comment]
@SaintPeter Thanks, that makes sense. It's unfortunate because folks will want to show off their solutions on their freeCodeCamp profile pages, but if the solutions don't pass, it's probably best to hide them. 

I haven't looked at the test code for these challenges, but it seems at a minimum a check could be performed to tell the user:  `newFunctionName() not found. Please update your code to use function newFunctionName(), we may have changed the function name recently.` 

Anyway, thanks for taking a look - I agree, this is the right move forward. Just hoping we can mitigate some of the adverse side effects.

**Comment by Saerith** [comment]
As a heads up to avoid stepping on toes, I'm currently working through basic-javascript.json.

**Comment by iamrudra** [comment]
Where are we on this?

**Comment by Saerith** [comment]
Wasn't this merged ages ago?

**Comment by raisedadead** [comment]
@erictleung can you confirm and close.

**Comment by erictleung** [comment]
@Saerith @raisedadead thanks. Yeah, I'm pretty sure I looked them over and declared all of them changed by the time I tried making the PR #8062. I'll close this now and if anyone finds anything, they can comment or make another issue. Thanks! Happy coding all!

**Comment by Saerith** [comment]
Thanks Eric!

**Comment by iamrudra** [comment]
Merged but not closed. ;)
