### ISSUE TITLE
Error in variables

### ISSUE THREAD

**Issue by felixtosar** [FreeCodeCamp/FreeCodeCamp#7087]
Challenge [Understanding Uninitialized Variables](http://www.freecodecamp.com/challenges/understanding-uninitialized-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.

Hi,
First sorry for my English, it´s not very good.

The introduction say: "Initialize the three variables a, b, and c with **5, 10,** and **"I am a"** respectively so that they will not be undefined."

And the test suit say: "

- a should be defined and have a value of **6**
- b should be defined and have a value of **15**
- c should not contain undefined and should have a value of **"I am a String!**
"

it should said:

- a should be defined and have a value of **5**
- b should be defined and have a value of **10**
- c should not contain undefined and should have a value of **"I am a!"**.

Bye, Félix.

My code:
```javascript
// Initialize these three variables
var a = 5;
var b = 10;
var c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by newyork-anthonyng** [comment]
@felixtosar 
Hi Felix, I think the confusion is with **when** the test suite is checking the value of the variables.

The test suite is checking the values of a, b and c **after all** of the code is run, not at the beginning of the code. At the end of your program, you have
```
a = 6;
b = 15;
c = "I am a String!";
```
which is what is shown in the test suite.

**Comment by ltegman** [comment]
@newyork-anthonyng is correct. There is nothing wrong with these tests. If you need and further help with this challenge please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help). Thanks and happy coding!

**Comment by MTHO2110** [comment]
// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a = 5 + 1;
b = 10 + 5;
c = "I am a String!";

it remains with this error and does not allow me to continue 
Do not change code below the line

**Comment by sfisowelcome** [comment]
mine does not work.
a = 6;
b = 15;
c = "I am a String!"

**Comment by newyork-anthonyng** [comment]
@sfisowelcome The [Help Chat](https://gitter.im/FreeCodeCamp/Help) is a better place for this question.
