### ISSUE TITLE
Unable to scroll normally when clicking on the map tab (safari 9.0.3)

### ISSUE THREAD

**Issue by angel1a** [FreeCodeCamp/FreeCodeCamp#7088]
This happens many times. When I click on the map tab, I cannot scroll down the list on the right. But I can scroll up normally.
<img width="1280" alt="screen shot 2016-02-17 at 19 37 02" src="https://cloud.githubusercontent.com/assets/16045446/13109369/b980fca8-d5b3-11e5-948b-4d874153fc63.png">
It seems that the "menu" button displays abnormally as well.

**Comment by bugron** [comment]
cc @hallaathrad

**Comment by angel1a** [comment]
More details:

Initially, I open this page, and then click on the map tab. 
Now, I can scroll up and down normally.

<img width="1280" alt="screen shot 2016-02-17 at 20 27 07" src="https://cloud.githubusercontent.com/assets/16045446/13109547/e01359f0-d5b4-11e5-8599-1829ca90e940.png">

Then I click on one of the challenges. 

In the new page, I can only scroll up. But I cannot scroll down.
 
<img width="1280" alt="screen shot 2016-02-17 at 20 27 10" src="https://cloud.githubusercontent.com/assets/16045446/13109554/eddc6478-d5b4-11e5-9b6e-ee3a54316268.png">

**Comment by jamigibbs** [comment]
@hallaathrad It seems to be related to the height applied to the `iframe` element at:

`.map-aside .iframeWrapper iframe`

If I change 'height: 100%` to `min-height: 500px`, it will scroll.

**Comment by hallaathrad** [comment]
hahaha that sidecar thing has been a nightmare. My thoughts if iframes had mothers.
I've been able to replicate and will work on a fix :+1: 
Thanks for your patience, all! We're almost there.

**Comment by hallaathrad** [comment]
Status update for all those affected/interested: I am still working on a fix for this, which includes rebuilding the actual layout for the map and the new wiki. Thanks for your patience!

**Comment by M1kep** [comment]
@hallaathrad a little off topic. But what was the "Oops of Doom"?

**Comment by hallaathrad** [comment]
@M1kep RE https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6960 and similar.

**Comment by jameslbryson89** [comment]
James Bryson
