### ISSUE TITLE
Build a tribute page - Link to wiki needs to be updated

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/FreeCodeCamp#7092]
The link to the "Read-Search-Ask"-page is to the old wiki (GitHub).

Shouldn't it redirect to the new wiki? 
In addition, **other challenges might have the same issue**.

### (EDIT: The new wiki doesn't support external references but maybe that could be a future improvement?)

**Comment by QuincyLarson** [comment]
Thanks for spotting this. I'll update it.

**Comment by M1kep** [comment]
@Greenheart whats the "old wiki" and whats the "new wiki" could you just post the two links? If this isnt done yet I can go through the rest of the challenges and see if any of them reference the old wiki. My only issue is that I'm not to sure what the "old wiki" is :/

Though @QuincyLarson said he'd update it, so Idk if this has been fixed yet.

**Comment by ltegman** [comment]
@M1kep This can't be fixed yet because the new wiki does not generate link URLs. This known issue. I believe we've got some people working on this already, but you're welcome to sync up with @hallaathrad and @SaintPeter in the [HelpContributors chat](https://gitter.im/FreeCodeCamp/HelpContributors) and check if they could use some help on it.

**Comment by hallaathrad** [comment]
hm @ltegman, technically, thanks to https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6938 you could ;)

**Comment by M1kep** [comment]
@hallaathrad when I get home in half an hour or so I'll get started on converting over any old wiki links to the new ones and submit a pr today hopefully

**Comment by M1kep** [comment]
Actually, whenever I try to navigate to, http://www.freecodecamp.com/wiki/How-to-get-help-when-you-get-stuck I just get the wiki homepage, so in not sure if #6938 fixed it....

**Comment by ltegman** [comment]
@M1kep That PR is still waiting to be QAed and merged, so it hasn't been fixed yet.

**Comment by M1kep** [comment]
Ahhhh ok, well I'll subscribe to it so I can submit a pr as soon as it's approved. Sorry for being a nuisance

**Comment by ltegman** [comment]
@M1kep No nuisance! It takes time to get up to speed on everything going on in this repo, so don't feel bad about asking questions to get there :smile:
