### ISSUE TITLE
Add Issue Template for easier issue creation

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#7093]
It looks like Github has [created a new feature](https://github.com/dear-github/dear-github/issues/125) whereby when you make a new issue, it can look for a `issue_template.md` file in the repo to use as an issue template. This will help clarify why the issue was made and what should be done to fix it.

It might not seem obvious what is going on (I was confused when I first saw this), but if you go [here](https://github.com/owncloud/core/issues/new) to a repo using this feature, a new issue is automatically templated.

This can help when a user creates an issue straight from Github instead of from the FCC website where it would template the issue.

**Comment by bugron** [comment]
Wow, awesome, thanks for that @erictleung! Waiting for a nice template.

**Comment by SaintPeter** [comment]
Straw Dog:
```
To Use this Template:
Fill out what you can
Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

## Issue Description
* When Issue Happens
* Steps To Reproduce

## Browser Information
* Browser Name, Version
* Operating System

## Screenshot

```

**Comment by erictleung** [comment]
More official news on templates https://github.com/blog/2111-issue-and-pull-request-templates Looks like you can do PR templates as well.

Documentation on the subject https://help.github.com/articles/helping-people-contribute-to-your-project/

**Comment by hallaathrad** [comment]
:+1: unofficial like button 

(tired of asking for one)
Great find, @erictleung!
