### ISSUE TITLE
CodePen not accepting image links to Google Drive.

### ISSUE THREAD

**Issue by HadziJo** [FreeCodeCamp/FreeCodeCamp#7094]
The URL values used in my anchor tags appear to work fine. However, I  can't convince CodePen to display images using either background-image, or the usual <img> tag. 
I added the 'target="_blank"' hack to these tags, but no difference. All that is displayed is the alt="" text.

Everything works fine if I open the html file from my browser locally (file:///C:/www/default.html).

**Comment by ltegman** [comment]
You'll have to take this up with CodePen. We don't control and can't change anything about the behavior of CodePen. Most likely Google has blocked them to prevent being used as a CDN by CodePen users, but I couldn't say for sure. Thanks and happy coding!
