### ISSUE TITLE
this seems to be ok

### ISSUE THREAD

**Issue by dfainber** [FreeCodeCamp/FreeCodeCamp#7095]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20font-size%3A%2016px%3B%7D%0A%20%20p%20%7Bfont-size%3A%2016px%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed.%3C%2Fp%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed.%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  font-size: 16px;}
  p {font-size: 16px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed.</p>
<p>Kitty ipsum dolor sit amet, shed.</p>


```

**Comment by erictleung** [comment]
I would reread the instructions. You need to add specific text to the second paragraph.

> Create a second `p` element with the following kitty ipsum text: `Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.`

**Comment by bugron** [comment]
@dfainber thanks for posting this issue!
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by dfainber** [comment]
Thxs! Sorry
On qua, 17 de fev de 2016 at 18:37 Eric Leung <notifications@github.com>
wrote:

> I would reread the instructions. You need to add specific text to the
> second paragraph.
>
> Create a second p element with the following kitty ipsum text: Purr jump
> eat the grass rip the couch scratched sunbathe, shed everywhere rip the
> couch sleep in the sink fluffy fur catnip scratched.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7095#issuecomment-185392727>
> .
>
-- 

*Diego F Fainberg*
