### ISSUE TITLE
Buttons Below Challenge NonFunctional

### ISSUE THREAD

**Issue by ESOComputing** [FreeCodeCamp/freecodecamp#71]
Don't know what happened, but around midnight PST we lost functionality with the two buttons 
[I've completed this challenge] and [Show me all challenges]. When you click either/or they do not do anything. I am using Chrome & Win 7, this error is being experienced from other members, this doesn't appear to be isolated. 
https://photos-3.dropbox.com/t/2/AABUlSgswrFhjmjO0xKLwGLO3elOLPO-gOqpVRVrbQMDWA/12/353228789/png/1024x768/2/_/0/4/Screenshot%202015-02-03%2003.03.42.png/CPWvt6gBIAEgAiADKAE/kyy49tuc5krkkjd/AABhbjocnzy13CXPnO-We7rEa/Screenshot%202015-02-03%2003.03.42.png

**Comment by yogin25** [comment]
I have got the same problem, i am using the latest version stable of chrome (Version "40.0.2214.94 (64-bit)"and Linux mint

**Comment by abdulhannanali** [comment]
I am getting the same problem on Google Chrome as well as Firefox. I checked it on Ubuntu as well as Windows 8.1

**Comment by QuincyLarson** [comment]
A big thanks to @ESOComputing @yogin25 and @abdulhannanali for reporting this! I've rolled back to a previous commit, and the buttons seem to work now. We'll investigate this issue before we redeploy our new code!

**Comment by abdulhannanali** [comment]
@QuincyLarson Big Thanks to you.
