### ISSUE TITLE
Challenges with submitted and accepted solutions not showing up after nuking settings and cookies on Chrome

### ISSUE THREAD

**Issue by TheMorkDaddy** [FreeCodeCamp/FreeCodeCamp#7101]
I work on FCC from two different computers (work iMac and home MacBook Pro). Recently, after a necessary nuke of cookies and settings of Chrome on the work Mac, most of my completed challenges on my profile page show the "View this challenge" link instead of the "View solution" link. 

Every challenge listed on my profile page is a completed challenge, hence the completion date. You can't have a completion date without a solution - yet a large chunk of my challenges still show "View this challenge." For instance, in my profile challenges list, "Disable an Element Using jQuery" was completed on August 18 (I finished the entire jQuery section last summer), but my solution is not stored, and it is listed as "View this challenge."

Resubmitting a solution on one challenge does not cause the others to "wake up" and display the correct solutions link, it just adds a "last updated" date to the item. 

Feel free to look: http://www.freecodecamp.com/themorkdaddy

**Comment by Greenheart** [comment]
I get the same behavior and I have two possible theories:

1. FCC olny storing solutions for algorithms and projects, not for regular challenges.
2. You've completed challenges of the old curriculum --> Challenges that no longer exist shows up in your profile but doesn't work properly.

**Comment by BerkeleyTrue** [comment]
Can anyone replicate this?
