### ISSUE TITLE
Use RGB to Color Elements Green

### ISSUE THREAD

**Issue by droymac** [FreeCodeCamp/FreeCodeCamp#7102]
This exercise will not verify. Hard reset did not resolve the issue. Tried in Chrome and Firefox for OS X.

**Comment by Greenheart** [comment]
It works for me. 

Maybe it's something with your browser/computer/network?

**Comment by bugron** [comment]
@droymac thanks for posting this issue!
We can't do anything for you until you provide more information (your code, OS, browser information, screenshots). Closing.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
