### ISSUE TITLE
FreeCodeCamp website, map page, "Last Updated" date

### ISSUE THREAD

**Issue by happycodecamper** [FreeCodeCamp/FreeCodeCamp#7103]
Hi: today is 02/17/2016. However the date that shows on my page says: 02/18/2016
In addition, all the days I completed tasks in 2015 are missing. 
Please verify. Thanks.
![fcc_date_issue](https://cloud.githubusercontent.com/assets/13081636/13132500/071f5aec-d5a8-11e5-81ab-490d2233d58b.JPG)

**Comment by AkiraLaine** [comment]
I believe "last updated" takes the date from the server (hence why it says '18/02/16')? Or am I wrong @FreeCodeCamp/issue-moderators?

I'm not sure what you mean by "all the days I completed tasks in 2015 are missing." - could you clarify?

**Comment by happycodecamper** [comment]
Hi: Here are the issues:
Issue #1: the days are incorrect. As you can see on my example above, yesterday was Feb 17, 2016, and as I was completing the tasks, the column that says "Last Updated" was filling out with the date of Feb 18, 2016. I seems this issue was fixed already.
Issue #2: the days I completed the tasks last year are not showing on the calendar (top page). However this is a minor issue and therefore, please ignore that.
Thanks!

**Comment by AkiraLaine** [comment]
@happycodecamper Could you provide a screenshot of the heatmap (calendar)

**Comment by happycodecamper** [comment]
Hi:
Issue #1: Please see file attached: FCC_dates_20160219.jpg. Today (Feb19, 2016), I have  **not ** done any task yet, but the  **Last Updated column**  is already showing today's date (third column from the left). How is it possible?
Issue #2:  Please see file attached: FCC_calendar_20160219.jpg. My calendar starts on the month of September of 2015. However I started on FCC around July of 2015. Therefore I cannot see any of the tasks I completed before Sep/2015 on this page. As I said before, I consider this is a minor issue, and if it is not possible to be fixed, that's fine.
Thanks, Maria 
![fcc_calendar_20160219](https://cloud.githubusercontent.com/assets/13081636/13192648/25601c72-d723-11e5-89aa-6ba534518789.JPG)
![fcc_dates_20160219](https://cloud.githubusercontent.com/assets/13081636/13192647/255eb706-d723-11e5-9418-5c7f401cc984.JPG)

**Comment by AkiraLaine** [comment]
Cc: @QuincyLarson @BerkeleyTrue
