### ISSUE TITLE
loopProtect lets infinite loops pass Drop It

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/FreeCodeCamp#7105]
As pointed out by @nugoose in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4004#issuecomment-185555456. The following solution will cause an infinite loop on the test case `drop([1, 2, 3, 4], function(n) {return n > 5;})` but loopProtect causes it to break out of the loop and return `arr`, which is the correct result.
```js
function drop(arr, func) {
  while(!func(arr[0])) {
    arr.shift();
  }
  return arr;
}

drop([1, 2, 3, 4], function(n) {return n >= 3;});
```

**Comment by M1kep** [comment]
Not sure how the loop protect is implemented, but couldn't you just return null whenever you break out of a loop? Or just throw an error?

**Comment by wdimac** [comment]
Was thinking of taking this on. Seems like a thrown exception is the right approach...
