### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue 

### ISSUE THREAD

**Issue by MayankJ30** [FreeCodeCamp/freecodecamp#711]
On scrolling down, the bar at the bottom of the page covers the mobile preview making it very hard to see the preview successfully. I'm assuming that this issue might get even more troublesome with longer problems.

A preview that changes it's size dynamically or an option for a full screen preview could be really useful.

P.S, I did notice the scrollbar that is present inside the preview space but that fails to resolve the issue. 
       In normal cases too, my taskbar hides a bit of the content.

![capture](https://cloud.githubusercontent.com/assets/2641144/7868750/c0b7ab8c-0586-11e5-8896-9eb8f26e0180.PNG)

**Comment by QuincyLarson** [comment]
That's a strange issue - i've never seen the phone so low on the page. Which browser are you using? Did you zoom in a lot? 

Note that we're moving to a fixed layout for these waypoints, so this will soon be a nonissue. I'm going to go ahead and close it.

**Comment by MayankJ30** [comment]
I was using Google Chrome on a machine running Windows 8.1 and no, I did
not zoom in a lot.

**Comment by MayankJ30** [comment]
Hey Buddy, How you doing? I just signed up on AskIITians . Do you know about it? I discovered it by chance and boy! it is one of the most comprehensive websites for Foundation (Grade 6-10th)/IIT-JEE/AIPMT preparation. They have tons of FREE Study Material. You know I don't advocate anything like this but I found it to be too good and couldn't resist. You could - Book a Free Trial Here Access Free Study Material Here Ask any question for FREE in their Forum Do give it a try. You would thank me later. Bye Mayank Jain
