### ISSUE TITLE
Accepting wrong answer

### ISSUE THREAD

**Issue by rohitkumar67** [freeCodeCamp/freeCodeCamp#7110]
## Issue Description
- when solving the "Render Images from Data Sources" challenge
- write following code in solution

```
html+="<img src='>"+val.imageLink+"'>";
```

It will not display any image but is still accepted as answer.

**Comment by Greenheart** [comment]
Thanks for ponting this out!

The challenge works just as expected, but the issue here is that FCC accepts the answer without activating the UI-state (you have to click the **Get Message**-button to display the image).

### Maybe this is something that needs clarification?

**Comment by ltegman** [comment]
Currently this test just checks that you used `val.imageLink` in your code and not that you constructed a valid image tag. If someone wants to tackle making a more thorough regex that checks for a validly constructed image tag I'd be game for that.

**Comment by M1kep** [comment]
Sooo I'm not sure if this is an acceptable solution, but I've tested it via [regex101.com](https://regex101.com/) and it seems to work. If this is actually an acceptable solution I guess I can attempt to figure out the whole cloning/branching thing again...

`/(html) *(\+=) *\"<{1}(i|I)(m|M)(g|G) *(s|S)(r|R)(c|C) *= *'{0,1}" *\+ *(val.imageLink) *\+ *" *'{0,1} *>";/g`

[RegEx101.com Version](https://regex101.com/r/gF8iO5/1)

**Comment by Greenheart** [comment]
@M1kep nice job!

Check out the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/.github/CONTRIBUTING.md), they walk you through the process to fork, commit the change and submit a pull request. If you need more help, head to the [FreeCodeCamp/HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room! :)

**Comment by PandaWhisperer** [comment]
Has this been fixed? Looks like there was a pull request that's been merged already.

**Comment by atjonathan** [comment]
@PandaWhisperer, both pull requests seem to be closed. Feel free to create one :smile:

**Comment by systimotic** [comment]
I'd like to take this on, but it seems like it's not possible to create a RegEx that would match every correct case. 
Allowing both `html += img` and `html = html + img` makes things really complicated.
This is what makes it impossible though: `'<img src="' + val.imageLink + '">'` vs `"<img src='" + val.imageLink + "'>"` vs `'<img src=\'' + val.imageLink + '\'>'` vs `"<img src=\"" + val.imageLink + "\">"`. All four of these are working solutions, but a mix of them won't work. As far as I'm aware, there's no way to check whether the quote used before works with the one used now. 

Another thing I have noticed is that around this challenge, all challenges are doable just by copying and pasting, not changing anything. This is not what I'm used to from Free Code Camp.
I think we have three options here:

1. Write a bunch of different regexes to match all the different possibilities. If one of them matches, you pass.
2. Only allow the format as suggested (and copyable) by the instructions.
3. Forget about checking whether the code is right, and check whether the output is right. I'm not sure how viable this is within the the testing environment, as it would require multiple lines of code. I do know that it's doable.

@FreeCodeCamp/moderators What should we do?

**Comment by Greenheart** [comment]
### Ideas for tests:
1. I believe the tests have access to the `fcc-test-frame`, which would allow the following.
`assert(testDOM.querySelectorAll('img').length > 0, 'message: Should render valid images.')`

2. If we know how many images there should be (based on the input data we use to render), we can verify that we get the correct number of images.

3. If we have access to the input data, we can verify that all images were correctly rendered, with the correct `alt`- as well as `src`-attributes by first querying all images and then checking their properties.
`Array.from(document.querySelectorAll('img')).every(img => img.alt === altText && img.src === imageLink)`
If this passes, all images are valid.

The regex solutions could work as well, but it feels like we could get more powerful tests with a proper DOM.

**Comment by systimotic** [comment]
@Greenheart Keep in mind that the images are only generated on a button click. A DOM solution may work, but we would have to simulate a click of the button in the test frame.
The browser also still manages to make a valid image tag out of this, so we would have to look at the source.

**Comment by Greenheart** [comment]
@systimotic Simulating a click is not harder than `document.querySelector('#element').click()`. If we have a DOM, and can run JS, we can do it.

If it makes a valid image, and we have JS as well as a DOM, we can use point 1 and 3 from my comment above :blush:
