### ISSUE TITLE
Type error: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by srinivasdasu** [FreeCodeCamp/FreeCodeCamp#7111]
## FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

## Issue Description
* When i try to execute my inventory update problem-it was throwing Type error: Cannot read property '1' of undefined
* execute my inventory update program

## Browser Information
* Chrome, Version:47.0.2526.111 m
* windows 7

## Screenshot
![freecodecamperror](https://cloud.githubusercontent.com/assets/8493594/13145294/b15c7e86-d675-11e5-9dcd-d976f84e4850.PNG)

**Comment by Greenheart** [comment]
This challenge is working fine for me.

If you need help, please use the [Help-chatroom](https://gitter.im/freecodecamp/help). Only report issues if others in the chatrooms can confirm the issue.

Good luck with your solution and happy coding! :)

**Comment by ltegman** [comment]
This is not a problem with FreeCodeCamp. This means something about your code's logic is broken so it ends up trying to access an array index on an undefined variable. Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance.

**Comment by srinivasdasu** [comment]
Sorry i didn't open this issue for help. I am trying to access an array index of defined variable only. I tried to print on console what i am trying to access, i got the value printed on console but FreeCodeCamp throwing error. I attached the screen shot you can have a look on what i am trying to access .
![error1](https://cloud.githubusercontent.com/assets/8493594/13171215/94783ad8-d717-11e5-9018-77a3707aedcb.PNG)

**Comment by srinivasdasu** [comment]
@Greenheart @ltegman  can you please have a look.

**Comment by Greenheart** [comment]
I still don't think this is an issue with FCC.

The problem seems to be with your code on line 4 to be more specific. 
Search Mozilla developer networks for information on how to use the Array.sort method. I think you're using it wrong. 

Good luck! :)

**Comment by srinivasdasu** [comment]
@Greenheart  Thank you , i know my mistake .It is not an issue of FCC. I resolved my problem.
