### ISSUE TITLE
Search and Replace

### ISSUE THREAD

**Issue by fickojuventino** [FreeCodeCamp/FreeCodeCamp#7113]
I can not run the test on this exercise, while it is possible on other exercises.

**Comment by Greenheart** [comment]
Could you please give some more information? :)

What does your output look like when you run the tests? Edit your post and add **a screenshot**

**Comment by fickojuventino** [comment]
I didnt finish the exercise, only split str into var array, and when i want to return array, it only says "testing challange..".

**Comment by Greenheart** [comment]
Please add **screenshot** to show what your screen looks like when you run the code :)

**Comment by fickojuventino** [comment]
![zz](https://cloud.githubusercontent.com/assets/16888394/13148935/93acacd2-d65f-11e5-8436-93189e17e305.PNG)

**Comment by Greenheart** [comment]
Thanks!
I don't think this is an issue with FreeCodeCamp, but with your code.

#### For help, go to the [HelpJavaScript chatroom](https://gitter.im/freecodecamp/helpjavascript) where there's people that can help you :)

Good luck and happy coding!

**Comment by hallaathrad** [comment]
As @Greenheart explains, this is not a system issue but rather a request for coding assistance.
Closing issue.
