### ISSUE TITLE
Use the Bootstrap Grid to Put Elements Side By Side

### ISSUE THREAD

**Issue by MartinaCarrington** [FreeCodeCamp/FreeCodeCamp#7116]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by ltegman** [comment]
You should be filling the template in with relevant details. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm that what you're seeing is really a bug and file a new issue with the required information if it is. Thanks and happy coding!
