### ISSUE TITLE
Dot notation not working on Testing Objects for Properties

### ISSUE THREAD

**Issue by georgewait** [FreeCodeCamp/FreeCodeCamp#7117]
Challenge [Testing Objects for Properties](http://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20if%20(myObj.hasOwnProperty(checkProp)%3D%3D%3Dtrue)%0A%20%20%20%20return%20myObj.checkProp%3B%0A%20%20else%0A%20%20%20%20return%20%22Not%20Found%22%3B%0A%7D%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22house%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};
function checkObj(checkProp) {
  // Your Code Here
  if (myObj.hasOwnProperty(checkProp)===true)
    return myObj.checkProp;
  else
    return "Not Found";
}
// Test your code by modifying these values
checkObj("house");
```

No matter what I did, the code would not pass the test. However, changing it to bracket notation like below results in passing.

```return myObj[checkProp];```

Not sure if this is a bug or not, so feel free to chime in.

**Comment by sludge256** [comment]
This is not a bug. If you use dot notation it will search for a property with the literal variable name as opposed to the variable's value.
https://medium.com/@prufrock123/js-dot-notation-vs-bracket-notation-797c4e34f01d#.y9gwxa10j

**Comment by georgewait** [comment]
Thanks @sludge256. I wasn't aware of that, but that article helped me understand why my code wouldn't go through.
