### ISSUE TITLE
Minor error in example code for 'use-spans-for-inline-elements'

### ISSUE THREAD

**Issue by blackrat** [FreeCodeCamp/FreeCodeCamp#7118]
In the example code given for highlighting 'hate' text, the supplied colon in the code is omitted.

```<p>Top 3 things cats <span class = "text-danger">hate</span></p>```

should really be:

```<p>Top 3 things cats <span class = "text-danger">hate</span>:</p>```

**Comment by blackrat** [comment]
Actually, now that I've passed that example, it appears it should really be:
```
<p>Top 3 things cats <span class = "text-danger">hate:</span></p>
```

**Comment by Greenheart** [comment]
Confirmed, thanks for reporting! :)

This should probably have the labels **Easy, Help Wanted & Confirmed(?)**
Btw, who can I talk to to join the issue moderators?

**Comment by NolanChan** [comment]
I'm new to helping out at FreeCodeCamp, but this seems easy and I"ll take it :)

**Comment by Greenheart** [comment]
@NolanChan Great! 

Check out the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/.github/CONTRIBUTING.md), they walk you through the process to fork, commit the change and submit a pull request. If you need more help, head to the [FreeCodeCamp/HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room! :)

**Comment by NolanChan** [comment]
Hi @blackrat , which code challenge had this mistake?

**Comment by blackrat** [comment]
Hi @NolanChan. It's in the first set of html code exercises. The URL for the page is http://www.freecodecamp.com/challenges/use-spans-for-inline-elements

**Comment by AYSH20** [comment]
I am trying to edit my code but when I tap on Things cat love, the cursor is at "Th"ings and then it moves to the next line and it is not going ahead with the arrow keys on the keyboard as well.
Is anyone facing this issue too?
