### ISSUE TITLE
Code is correct. I still cant pass. 

### ISSUE THREAD

**Issue by williamjohn90** [FreeCodeCamp/FreeCodeCamp#7119]
Challenge [Title Case a Sentence](http://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20var%20newArr%20%3D%20str.toLowerCase(%22%22).split(%22%20%22)%3B%0A%20%20var%20finalStr%20%3D%20%22%22%3B%0A%20%20for(i%20%3D%200%3B%20i%20%3C%20newArr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20finalStr%20%2B%3D%20newArr%5Bi%5D.charAt(0).toUpperCase()%20%2B%20newArr%5Bi%5D.substring(1%2C%20newArr%5Bi%5D.length)%20%2B%20%22%20%22%3B%0A%20%20%7D%0A%20%20%20return%20finalStr%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  var newArr = str.toLowerCase("").split(" ");
  var finalStr = "";
  for(i = 0; i < newArr.length; i++) {
    finalStr += newArr[i].charAt(0).toUpperCase() + newArr[i].substring(1, newArr[i].length) + " ";
  }
   return finalStr;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```

I understand there is an unnecessary whitespace after the end of the sentence. Nonetheless i think i figured out an elegant way to solve the problem and the system should let me carry on.

**Comment by FreakDroid** [comment]
Your problem is that you always put a space in the last of the string,and always you are creating yourString+" " and thats ins invalid for the test for instance "My Handle Here Is My Spout " !== "Here Is My Handle Here Is My Spout" only put a trim to remove the last space and you are done :+1: 

```
function titleCase(str) {
  var newArr = str.toLowerCase("").split(" ");
  var finalStr = "";
  for(i = 0; i < newArr.length; i++) {
    finalStr += newArr[i].charAt(0).toUpperCase() + newArr[i].substring(1, newArr[i].length) + " ";
  }
   return finalStr.trim();
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");
```

**Comment by ltegman** [comment]
If you're adding unneeded whitespace then your code isn't correct. It's nit-picky and detail oriented, but you have to be that when you're programming. Small details matter. Thanks and happy coding!
