### ISSUE TITLE
charAt error in Videos

### ISSUE THREAD

**Issue by Gangezilla** [FreeCodeCamp/FreeCodeCamp#7120]
When watching any of the videos, if you have the console up, there's an error that continually loops about being unable to read "'charAt' property of undefined". It's not a big deal, however.

#### Browser Information
* This happens in Chrome 48.0.2564.109 and Safari 9.0.
* Mac OS X 10.11

#### Screenshot
![alt-text](https://cloud.githubusercontent.com/assets/8536243/13159208/b15b6d56-d6e4-11e5-875f-ed1f36d4244c.png)

**Comment by Greenheart** [comment]
Confirmed, thanks for reporting! :)

@Gangezilla To fix your screenshot --> add "![alt-text]" before the URL in parenthesis

**Comment by Greenheart** [comment]
Confirmed, thanks for reporting! :)

@Gangezilla To fix your screenshot --> add "![alt-text]" before the URL in parenthesis

**Comment by Gangezilla** [comment]
Okay! I'll fix up the screenshot next time. I wanted to have a look into fixing it, but wasn't sure where to find it :).

**Comment by Greenheart** [comment]
In addition, you can edit comments by clicking the pen in the top right :)

**Comment by Gangezilla** [comment]
Hehe, gotcha. Thanks mate!

**Comment by JoshFisk** [comment]
The error is pointing at the capitalize function in react-vimeo
https://github.com/FreeCodeCamp/react-vimeo/blob/42621bf09126911ea1ab4da504b7fcb432885cb0/src/Vimeo.jsx

**Comment by raisedadead** [comment]
@Gangezilla Are you still getting this? 
/cc @Greenheart

**Comment by raisedadead** [comment]
Closing as stale

**Comment by raisedadead** [comment]
Please comment here. If you can reproduce.

**Comment by sludge256** [comment]
The issue is still present.

**Comment by BerkeleyTrue** [comment]
closing in favor of https://github.com/FreeCodeCamp/react-vimeo/issues/6
