### ISSUE TITLE
Hard to login to chat room - can't scroll to authorize button

### ISSUE THREAD

**Issue by szabgab** [FreeCodeCamp/FreeCodeCamp#7121]
I've just tried to log in to the chat. I clicked on the button to login button that brought up the Oauth authorization page of GitHub, but I could not see the "Authorize button".
It was under the fold and I could not scroll in that window. (OSX , Firefox, 13" screen).

This will probably only happen on small screens and if you are a member of many organizations.

After zooming out and making the fonts smaller I could see the button and get in, but enabling scrolling there would be better.

I am not sure if this is an issue related to FreeCodeCamp or actually GitHub but I did not have the same issue when I signed up on the main page of FreeCodeCamp using my GitHub account.

**Comment by sludge256** [comment]
Could you provide screenshots?

**Comment by szabgab** [comment]
![screen shot 2016-02-19 at 12 32 24 am](https://cloud.githubusercontent.com/assets/48833/13160496/69824584-d6a0-11e5-9c09-37929518dfee.png)
The same problem even if I maximize that window.

**Comment by AkiraLaine** [comment]
Normally you should be able to scroll down. Or just expand the window manually.

From what I can see - you've managed to log in, so I'll close this issue as it's not related to FCC.

**Comment by garbark** [comment]
I have been login for over a hour and I have been put out any visual arts
thank you for being there for other's

Gary M Barker
