### ISSUE TITLE
Binary Agent do not pass tests

### ISSUE THREAD

**Issue by jesusjl** [FreeCodeCamp/FreeCodeCamp#7124]
Binary Agent do not pass tests but result looks ok.

Firefox 43.0.4
 Linux Mint 17

```js

function bin(n,base) {
  return parseInt(n, 2);
} 

var arr = [];
var arr2 = [];
function binaryAgent(str) {
 arr = str.split(' ');
 console.log(arr);
 var str2 = "";
 for(var i = 0; i<arr.length;i++) {
   arr[i] = bin(arr[i]);
   console.log(arr[i]);
   arr2.push(String.fromCharCode(arr[i]));
   console.log(arr2);
 }
  return  arr2.join(""); ;
}

binaryAgent("01000001 01110010 01100101 01101110 00100111 01110100 00100000 01100010 01101111 01101110 01100110 01101001 01110010 01100101 01110011 00100000 01100110 01110101 01101110 00100001 00111111");
```

**Comment by ltegman** [comment]
Global variables are bad. Think about what your code does if you run the function more than once. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to confirm what you're seeing is a site bug and not a bug with your code. Thanks and happy coding!

**Comment by jesusjl** [comment]
Thank you Itegman, you are utterly right! Good to know for the next time. 
Best
