### ISSUE TITLE
Filter Arrays with filter conflicting statements in instructions and test 

### ISSUE THREAD

**Issue by radar4077th** [FreeCodeCamp/FreeCodeCamp#7125]
Challenge [Filter Arrays with filter](http://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%20%3C%206%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![screen shot 2016-02-18 at 8 30 22 pm 2](https://cloud.githubusercontent.com/assets/4451730/13163882/9d267c1a-d67e-11e5-94f2-e43e7f4a272d.png)

Conflicting statements instructions say 

Use filter to create a new array with all the values from oldArray which are less than 6.
oldArray should not change.

Test say 
You should have filtered out all values from the array that are greater than 5.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val < 6;
});

```

**Comment by ltegman** [comment]
To clarify this issue:
>The removing values greater than 5 part isn't actually a problem, since keeping things less than six and removing things great than 5 is the same thing. However, it is an issue that the test case makes it sound like the original array should be modified.

**Comment by Navankur94** [comment]
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
  return val < 6;
});

**Comment by veronicarbulu** [comment]
I got confused with having to delete the last statement (var newArray = oldArray;). That kept me from getting all 4 items correct. I'm guessing we have to delete that, so we don't change the original array (oldArray), correct?
