### ISSUE TITLE
Bug: Answers Already Pre-populated In Challenge

### ISSUE THREAD

**Issue by katwalla** [FreeCodeCamp/FreeCodeCamp#7128]
Challenge [Multiply Two Numbers with JavaScript](http://www.freecodecamp.com/challenges/multiply-two-numbers-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var product = 8 * 10;

// Only change code above this line.

(function(z){return 'product='+z;})(product);

```

**Comment by ltegman** [comment]
See my answer in #7129.
