### ISSUE TITLE
Bug: Answer Is Pre-Populated 

### ISSUE THREAD

**Issue by katwalla** [FreeCodeCamp/FreeCodeCamp#7129]
Challenge [Multiply Two Decimals with JavaScript](http://www.freecodecamp.com/challenges/multiply-two-decimals-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var product = 2.0 * 2.5;


// Only change code above this line.

(function(y){return 'product='+y;})(product);

```

**Comment by ltegman** [comment]
There is nothing about our infrastructure that makes such a thing possible unless you (or someone else using your computer) has visited this challenge before. The localStorage code storage is what you're seeing. It can have been filled by having already solved this challenge or by having visited through a link in someone's profile. Thanks and happy coding!
