### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue 

### ISSUE THREAD

**Issue by MayankJ30** [FreeCodeCamp/freecodecamp#713]
Please correct me if I'm wrong but I did not find any previous reference to the <div> element while doing the course. Wouldn't it be much better to first introduce the <div> tag in the HTML and make the user familiar with its uses instead of directly using it in the Bootstrap section?

**Comment by QuincyLarson** [comment]
Great point. I'm creating a new challenges that introduce the div element and give campers practice wrapping other elements within it.

**Comment by QuincyLarson** [comment]
This is done and merged.
