### ISSUE TITLE
Bug: Answer Is Pre-Populated 

### ISSUE THREAD

**Issue by katwalla** [FreeCodeCamp/FreeCodeCamp#7130]
*This is the third challenge in which the answer is pre-populated.

Challenge [Divide one Decimal by Another with JavaScript](http://www.freecodecamp.com/challenges/divide-one-decimal-by-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var quotient = 4.4 / 2.0;


// Only change code above this line.

(function(y){return 'quotient='+y;})(quotient);

```

**Comment by ltegman** [comment]
See my answer in #7129.
