### ISSUE TITLE
Browser doesn't recognize comments/degradation of H2 element

### ISSUE THREAD

**Issue by innoprog** [FreeCodeCamp/FreeCodeCamp#7132]
https://www.dropbox.com/s/m0fgjoufg4prnk6/Screenshot%202016-02-19%2000.27.32.png?dl=0

I have refreshed and retyped this multiple times only to find that, for some reason, the editor won't recognize that I've commented out and degraded the fonts properly.

**Comment by ltegman** [comment]
You've commented out more than you should have. Closing as not a site issue. Thanks and happy coding!
