### ISSUE TITLE
Error on test

### ISSUE THREAD

**Issue by ledminh** [FreeCodeCamp/FreeCodeCamp#7133]
Challenge [Symmetric Difference](http://www.freecodecamp.com/challenges/symmetric-difference) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.

One of the test is 
` sym([1, 2, 5], [2, 3, 5], [3, 4, 5]) should return [1, 4, 5] `

I believe it should return only [1,4] instead of [1,4,5] since 5 appears in all 3 sets. Am I right?

**Comment by ltegman** [comment]
Please watch the symmetric difference explanation video that is linked to from the sidebar to see why that test is correct. In the future please check with the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to make sure what you're seeing is actually a site bug. Thanks and happy coding!
