### ISSUE TITLE
Error in test case

### ISSUE THREAD

**Issue by ledminh** [FreeCodeCamp/FreeCodeCamp#7134]
Challenge [Exact Change](http://www.freecodecamp.com/challenges/exact-change) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
I believe this test is wrong: 

`drawer(19.50, 20.00, [["PENNY", 0.01], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 1.00], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return "Insufficient Funds". `

It should not return "Insufficient Funds" since the total cash-in-drawer is $1.01 (ONE 1.00 and PENNY 0.01) while the change is only $0.5 (20 - 19.50).

**Comment by M1kep** [comment]
I think its saying that you don't have sufficient fund to give them there 50 cents back
Cause you have 1 1 dollar bill and a penny yet you owe them two quarters, or 10 nickels, or 4 dimes and 2 nickels etc

**Comment by ltegman** [comment]
@M1kep Is correct. You don't have enough change of a small enough denomination to give them change. Thanks and happy coding!
