### ISSUE TITLE
Answer was already there !!!!!

### ISSUE THREAD

**Issue by tnsurender** [FreeCodeCamp/FreeCodeCamp#7135]
Challenge [Modify Array Data With Indexes](http://www.freecodecamp.com/challenges/modify-array-data-with-indexes#?solution=%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0AourArray%5B1%5D%20%3D%203%3B%20%2F%2F%20ourArray%20now%20equals%20%5B1%2C3%2C3%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AmyArray%5B0%5D%20%3D%203%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.

myArray[0] = 3;

```

**Comment by AkiraLaine** [comment]
Since this is a related issue to #7136, I'm closing this
