### ISSUE TITLE
Once again answer was already present in the exercise !!!!!

### ISSUE THREAD

**Issue by tnsurender** [FreeCodeCamp/FreeCodeCamp#7136]
Challenge [Manipulate Arrays With push](http://www.freecodecamp.com/challenges/manipulate-arrays-with-push#?solution=%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.push(%5B%22happy%22%2C%20%22joy%22%5D)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%2C%20%5B%22happy%22%2C%20%22joy%22%5D%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0AmyArray.push(%5B%22dog%22%2C3%5D)%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray.push(%5B%22dog%22%2C3%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.push(["happy", "joy"]); 
// ourArray now equals ["Stimpson", "J", "cat", ["happy", "joy"]]

// Setup
var myArray = [["John", 23], ["cat", 2]];
myArray.push(["dog",3]);

// Only change code below this line.
myArray.push(["dog",3]);


```

**Comment by AkiraLaine** [comment]
Did ever use a different account on FCC? Are you sure you didn't do these before?

Also, could you clear your local cache and cookies and see if that removes the answers.

**Comment by QuincyLarson** [comment]
@tnsurender Please follow these steps to clear your local storage: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser's-Local-Storage
