### ISSUE TITLE
IL91 4952 9399 6123 3252 928

### ISSUE THREAD

**Issue by panyarerkcap** [FreeCodeCamp/FreeCodeCamp#7138]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by Greenheart** [comment]
@panyarerkcap Could you please clarify what you mean?

Is the title encoded in a special format? It's just a lot of numbers in my iOS Chrome browser :P

**Comment by bugron** [comment]
Closing. Feel free to reopen with the description of your issue and if your reopen, please, rename this issue's title to be descriptive.
