### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-negative-margin-to-an-element has an issue 

### ISSUE THREAD

**Issue by n-eisner** [FreeCodeCamp/freecodecamp#714]
When I change the green box margin to -15 the program does not recognize that I have completed the waypoint

**Comment by QuincyLarson** [comment]
This now works in Chrome and Firefox.

**Comment by rezan8** [comment]
This issue still exists for me in Chrome

**Comment by benmcmahon100** [comment]
@rezan8 I cannot replicate this issue there is most likely a bug in your code somewhere or a problem in loading the page

**Comment by rezan8** [comment]
Thanks. Worked on internet explorer for some reason

**Comment by rezan8** [comment]
Just realised that my zoom was not on 100% on chrome that's why it didn't work.
