### ISSUE TITLE
Entered code not carried over to next challenge, then reappers in the following challenge.

### ISSUE THREAD

**Issue by efaryna** [FreeCodeCamp/FreeCodeCamp#7144]
#### Issue Description
* In the "Change Text Inside an Element Using jQuery" challenge the code from the previous lesson "Disable an Element Using jQuery" is not carried over.
Specifically:

$("#target1").prop("disabled", true);

Continuing to the next lesson: "Remove an Element Using jQuery" and the code reappears

#### Browser Information
* Version 48.0.2564.109 m (64-bit)
* Windows 10

**Comment by raisedadead** [comment]
@efaryna Although the HTML and jQuery challenges have a common theme,
Every Challenge is unique with its own sample code in the editor and test cases.

IMHO, this behavior of the code doesn't affect solving the challenge.

Closing. Please feel free to comment if you feel this needs to be improved.
