### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue 

### ISSUE THREAD

**Issue by frenkile** [FreeCodeCamp/freecodecamp#715]
I'm not sure what the error is here that prevents me from submitting this waypoint:

< form action="/submit-cat-photo">
  < input type='text' placeholder='cat photo URL'>
  < button type='submit'>This button submits the form</button>
< /form>

**Comment by matejhegedus** [comment]
The button should have the text "Submit" and also you need a \</button> end tag.
```
<form action="/submit-cat-photo">
  <input type='text' placeholder='cat photo URL'>
  <button type='submit'>Submit</button>
</form>
```
This works for me.

(I believe there is a typo in the text of the exercise: "test value" instead of "text value".)

**Comment by outrofelipe** [comment]
To me works with the following code:
<form action="/submit-cat-photo">
  <input type='text' placeholder='cat photo URL'>
  <button type='submit'>submit</button>
</form>
Try change the text for just 'submit'

**Comment by QuincyLarson** [comment]
We've improved the tests on this challenge and it should be fully fixed.
