### ISSUE TITLE
https://github.com/FreeCodeCamp/FreeCodeCamp.git

### ISSUE THREAD

**Issue by ilovejavascript12** [FreeCodeCamp/FreeCodeCamp#7153]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by sludge256** [comment]
Reopen this if there is an actual issue and provide details to explain the issue.

**Comment by garbark** [comment]
Look I don't know what you talking about and I wake up to hear this all day
and haven't been able to do anything without any problems in the
understanding of what people are saying I don't know what you talking about
thank you

Gary M Barker
