### ISSUE TITLE
Edit Gitter FCC Main Room Summary to reflect current number of Official Rooms. 

### ISSUE THREAD

**Issue by qmikew1** [FreeCodeCamp/FreeCodeCamp#7159]
In main room the following summary (or blurb) appears next to room title:

*Welcome to our main chat room. We have hundreds of official chat rooms for hanging out and getting help. Here’s the list: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Official-Free-Code-Camp-Chat-Rooms*

I know (via the link) that a lot of the rooms were paired down to 11 or 12 total official rooms. Are there really hundreds of rooms? (yes, a bit nitpicky but couldn't -hundreds of - be changed to -many-?)

e.g., 

*Welcome to our main chat room. We have many official chat rooms for hanging out and getting help. Here’s the list: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Official-Free-Code-Camp-Chat-Rooms*

**Comment by AkiraLaine** [comment]
It could be modified I guess. @QuincyLarson what do you think?

**Comment by BerkeleyTrue** [comment]
Done.

Happy Coding!
