### ISSUE TITLE
feature request: Make coding area scroll independently.

### ISSUE THREAD

**Issue by samchalle** [FreeCodeCamp/freecodecamp#716]
It might be more convenient if the instruction and coding area scrolled independently of each other so you can refer to each section without having to continuously scroll up and down.

**Comment by LumenTeun** [comment]
Could someone in charge change the title of this issue?

**Comment by BerkeleyTrue** [comment]
edit: title changed to reflect issue

**Comment by georgekuka** [comment]
Adding the css below to class "CodeMirror-scroll"

'''css
overflow: auto;
max-height: 750px;
'''

Height could be anything, I'm sure there's a responsive solution to have it extend the height of browser window. But this solution works decently across all viewport sizes.

**Comment by benmcmahon100** [comment]
For anyone follow the development of this issue i have a fix ready to go here #1153
