### ISSUE TITLE
Some JS challenges/waypoints are incorrectly mentioned/linked in camper profile

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#7163]
#### Issue Description
* When Issue Happens - When I visit my [profile](http://www.freecodecamp.com/manish-giri) on FreeCodeCamp, and try to access one of the JS challenges(initially called waypoints), on the next page, I get an error - **We couldn't find a challenge with the name Update the Properties of a JavaScript Object. Please double check the name.** 
* Steps To Reproduce
    1. Go to your profile on FCC
    2. Search for challenge _Update the Properties of a JavaScript Object_
    3. As I've already done this challenge, I get the "view solution" option beside it. Click on it.
    4. On the next page, error appears - **We couldn't find a challenge with the name Update the Properties of a JavaScript Object. Please double check the name**

#### Browser Information
* Browser Name, Version - Safari, v 9.0.3
* Operating System - Mac OSX El Capitan

#### Screenshot
![screenshot 2016-02-20 13 06 37 copy](https://cloud.githubusercontent.com/assets/11348778/13198278/ebe96e34-d7d2-11e5-9b35-2544db379ab7.png)

**Comment by hallaathrad** [comment]
@SaintPeter ?

**Comment by ltegman** [comment]
This is another instance of #3806. Whenever we change the name of a challenge the profile link will break. Is there a way we can use the ID saved with the challenge for lookups from the profile to prevent this problem or is this is just a problem we have to live with when a challenge name changes?
