### ISSUE TITLE
counting cards, not sure why it can't return the right output

### ISSUE THREAD

**Issue by zerialchua** [FreeCodeCamp/FreeCodeCamp#7167]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20count%20%3D%20count%20%2B%200%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20%22J%22%3A%0A%20%20%20%20case%20%22Q%22%3A%0A%20%20%20%20case%20%22K%22%3A%0A%20%20%20%20case%20%22A%22%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(count%3E0)%7B%0A%20%20%20%20return%20count%2C%20%22%20Bet%22%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20count%2C%20%22%20Hold%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      break;
  
    case 7:
    case 8:
    case 9:
      count = count + 0;
      break;
      
    case 10:
    case "J":
    case "Q":
    case "K":
    case "A":
      count--;
      break;
  }
  
  if (count>0){
    return count, " Bet";
  }
  else{
    return count, " Hold";
  }
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by erictleung** [comment]
You're almost there. Just reread the instructions a little more carefully.

>  The function will then return a string...The current count and the player's decision (`"Bet"` or `"Hold"`) should be separated by a single space.
> 
> `Example Output`
> `"-3 Hold"`
> `"5 Bet"`

If you need help next time, I would go to the Gitter page at https://gitter.im/FreeCodeCamp/Help Good luck!

**Comment by cannelflow** [comment]
example needs you to return like Example Output
"-3 Hold"
"5 Bet"
and your code is returning like
' Hold'
do like
 if (count>0){
    return count + " Bet";
  }
  else{
    return count + " Hold";
  }
agree with @erictleung if you need help first ask it on chat room

**Comment by ltegman** [comment]
Closing as not a site issue. Thanks and happy coding!
