### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue 

### ISSUE THREAD

**Issue by matejhegedus** [FreeCodeCamp/freecodecamp#717]
There is a typo in this text:
> Add a submit button to your form field with type submit and a test value of "Submit".

I believe
> test value of "Submit".

should be:
> te**x**t value of "Submit".

**Comment by QuincyLarson** [comment]
Nice catch. Thanks! I'll fix this.
