### ISSUE TITLE
Broken link in Terms of Service

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/FreeCodeCamp#7171]
The link "reblogging function", poiting to `en.support.freecodecamp.com` is broken. Do FCC still have a support site?

#### Screenshot
![broken-fcc-link](http://i.imgur.com/GfTEluO.png?1)

**Comment by ltegman** [comment]
I don't know what this should be linking to (if anything). Any insight @QuincyLarson?

**Comment by QuincyLarson** [comment]
@Greenheart this can be deleted. It is left over from Wordpress's ToS (which I interpreted into our ToS - it's creative commons).
