### ISSUE TITLE
Arguments Optional - FreeCodeCamp bug

### ISSUE THREAD

**Issue by dsm23** [FreeCodeCamp/FreeCodeCamp#7176]
Challenge [Arguments Optional](http://www.freecodecamp.com/challenges/arguments-optional#?solution=function%20singleMode(x)%20%7B%0A%20%20cum%20%2B%3D%20x%3B%0A%20%20if%20(cum%20%3D%3D%3D%20x)%20%7B%0A%20%20%20%20%20%20return%20add%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20%20%20return%20cum%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20add()%20%7B%0A%20%20%20%20%0A%20%20%20%20if%20(arguments%5B0%5D%20%3D%3D%3D%20Number(arguments%5B0%5D))%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20if%20(arguments%5B1%5D%20%3D%3D%3D%20undefined)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20singleMode(arguments%5B0%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20if%20(arguments%5B1%5D%20!%3D%3D%20Number(arguments%5B1%5D))%20%7B%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20if%20(arguments%5B1%5D%20%3D%3D%20Number(arguments%5B1%5D))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('hi')%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20sum%20%3D%20arguments%5B0%5D%20%2B%20arguments%5B1%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20sum%3B%0A%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%7D%20%20%0A%7D%0A%0Avar%20cum%20%3D%200%3B%0A%0Aadd(2)(3)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function singleMode(x) {
  cum += x;
  if (cum === x) {
      return add;
  }
  else {
      return cum;
  }
}

function add() {
    
    if (arguments[0] === Number(arguments[0])) {
        
        if (arguments[1] === undefined) {
            return singleMode(arguments[0]);
        }
        if (arguments[1] !== Number(arguments[1])) {      
            return undefined;
        }
        if (arguments[1] == Number(arguments[1])) {
            console.log('hi');
            var sum = arguments[0] + arguments[1];
            return sum;
        }        
    }
    
    else {
        return undefined;
    }  
}

var cum = 0;

add(2)(3);

```

**Comment by ltegman** [comment]
Using global variables for function specific storage is bad news. Think about what your code does if you run it twice. In the future please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to confirm what you're seeing is actually a site bug before filing an issue. Thanks and happy coding!
