### ISSUE TITLE
Conversion of 1KB or Kilobyte to bits in one of the video lessons is incorrect

### ISSUE THREAD

**Issue by pavyer** [FreeCodeCamp/FreeCodeCamp#7177]
* The video in question is [computer-basics-how-to-measure-data-size](http://www.freecodecamp.com/videos/computer-basics-how-to-measure-data-size)

* The text in question is *"The next step up is a Kilobyte, 1024 Bytes, or 1,048,576 bits."* 

* The issue is that 1KB or kilobyte equals 8192 bits. To check the calculation use [bit calculator](http://bit-calculator.com/)

**Comment by scshepard** [comment]
Question: What is the "international" convention say: 1k = 1000 or 1K = 1000?Curious Community College professor would like to know.Thanks!Steve

Date: Sun, 21 Feb 2016 11:13:15 -0800
