### ISSUE TITLE
Clears challenge without closing the text field

### ISSUE THREAD

**Issue by Cephoniss** [FreeCodeCamp/FreeCodeCamp#7185]
Challenge [Add Placeholder Text to a Text Field](http://www.freecodecamp.com/challenges/add-placeholder-text-to-a-text-field) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.

**This challenge will allow you to clear it without actually closing the text field. Able to replicate issue multiple times.**

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type="text"
       placeholder="cat photo URL"

```

**Comment by shw-eta** [comment]
so your input doesn't have closing brace but you passed the challenge ?? is that your prob?

**Comment by shw-eta** [comment]
it could be probably because you would have passed the challenge successfully once with the closing brace and after you open the same challenge it has restored your previous changes to the code
and hence you are able to pass it each time

**Comment by Cephoniss** [comment]
Not really an issue to me, just reporting it as a bug.  First time I attempted the challenge I recall submitting the challenge before closing out the text field as you can see from the code above.  I have since resubmitted the challenge multiple times without actually closing the statement.

**Comment by ltegman** [comment]
@shw-eta Only the code currently in the editor is submitted, so regardless of what has been submitted previously this should not pass. @Cephoniss Thanks for pointing this out.

**Comment by NolanChan** [comment]
@ltegman Should we add a new criteria seeing if it's a valid input element? (So a third check)

<img width="329" alt="screen shot 2016-02-22 at 5 52 36 pm" src="https://cloud.githubusercontent.com/assets/1487616/13239191/3aeea8e4-d98d-11e5-9ba5-6b1b3d67879f.png">

**Comment by ltegman** [comment]
@NolanChan I think making a third check would be the best way to go, that way the regex doesn't have to be super complicated. You can leave checking for the right placeholder to the existing tests and just have the new regex test focus on if a valid text input tag was created.

**Comment by ChristianLapinig** [comment]
I have been able to replicate this issue too

**Comment by Kahagalle** [comment]
How about adding a "Syntax check" as the third check ?
