### ISSUE TITLE
Video didn't math with the description. Build a Random Quote Machine

### ISSUE THREAD

**Issue by ramortegui** [FreeCodeCamp/FreeCodeCamp#7186]
#### Issue Description
* Build a Random Quote Machine
* Go to Build a Random Quote Machine

#### Screenshot

![screenshot_2016-02-21_18-54-32](https://cloud.githubusercontent.com/assets/2103842/13207508/9a055074-d8cc-11e5-9764-f041117433af.png)

**Comment by ramortegui** [comment]
http://www.freecodecamp.com/challenges/build-a-random-quote-machine

**Comment by ltegman** [comment]
We have a similar problem with another project in #5294.

@QuincyLarson: are there plans to update these videos? They also reference the old campsite terminology that we don't use anymore.

**Comment by QuincyLarson** [comment]
@ltegman the plan is to remove these videos completely. I am closing this issue.
