### ISSUE TITLE
Introduce Reactive Programming

### ISSUE THREAD

**Issue by pmbenjamin** [FreeCodeCamp/FreeCodeCamp#7188]
**Functional Programming (FP)** sets up the stage very nicely for **Reactive Programming (RP)**.
I believe it would be beneficial for campers to be exposed to RP paradigms (i.e. observable streams), just as campers are exposed to OOP and FP paradigms.

**Comment by BerkeleyTrue** [comment]
Observables and Streams are outside of the scope of Free Code Camp. 

Happy Coding!
