### ISSUE TITLE
left tips meet highlight problem

### ISSUE THREAD

**Issue by frank0718** [FreeCodeCamp/FreeCodeCamp#7189]
Challenge [Add ID Attributes to Bootstrap Elements](http://www.freecodecamp.com/challenges/add-id-attributes-to-bootstrap-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

not the code issue 
just  the** left tips meet highlight problem**

Give the well on the left the id of left-well.    "id" not highlight , is a bug?
Give the well on the right the id of right-well.  "id" highlight

**Comment by cannelflow** [comment]
instructions are Give the well on the left the id of left-well. Give the well on the right the id of right-well. and while going from your link you don't have id's on your on your div did you tried to ask it on chat forum https://gitter.im/FreeCodeCamp/FreeCodeCamp

**Comment by ltegman** [comment]
The problem is that in the instructuctions the formatting is not consistent. One time `id` is in code blocks and another time it isn't. These should be made consistent.

**Comment by NolanChan** [comment]
So should we highlight the first `id`? Or should we unhighlight the second `id`?

**Comment by frank0718** [comment]
ltegman  is right, just keep "if"  consistent
