### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-try-camper-news has an issue 

### ISSUE THREAD

**Issue by outrofelipe** [FreeCodeCamp/freecodecamp#719]
Do you forget a letter C on string "1.You an also comment on a link. If someone responds to your comment, you'll get an email notification so you can come back and respond to them.". The right is "1.You Can also comment on a link. If someone responds to your comment, you'll get an email notification so you can come back and respond to them."

**Comment by QuincyLarson** [comment]
Thank you for spotting this! I've fixed it.
