### ISSUE TITLE
Challenge Accessing Nested Objects in JSON - bug?

### ISSUE THREAD

**Issue by mrsweety** [FreeCodeCamp/FreeCodeCamp#7191]
Challenge [Accessing Nested Objects in JSON](http://www.freecodecamp.com/challenges/accessing-nested-objects-in-json#?solution=%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove%20box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStorage%20%3D%20myStorage.car.inside%5B%22glove%20box%22%5D%3B%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var myStorage = myStorage.car.inside["glove box"];// Change this line


```

Is this a bug please? , sticking the code into chrome and testing myStorage; returns "maps"  , so seems to push the correct data into myStorage , please help as my brain hurts..

**Comment by mrsweety** [comment]
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var myStorage = myStorage.car.inside["glove box"];
undefined
myStorage;
"maps"

**Comment by FreakDroid** [comment]
If you read the error, you would see what is happening:

> ReferenceError: gloveBoxContents is not defined

For any rason you changed the variable name gloveBoxContents for myStorage. If you see myStorage is the Json, and gloveBoxContents is Where you'll save the value so chage this line:

`var myStorage = myStorage.car.inside["glove box"];`

To

`var gloveBoxContents = myStorage.car.inside["glove box"]; // Change this line`

**Comment by mrsweety** [comment]
Got it :) , thanks .

**Comment by henrihyacinthe** [comment]
var  gloveBoxContents = myStorage.car.inside["glove box"];

**Comment by henrihyacinthe** [comment]
var  gloveBoxContents = myStorage.car.inside["glove box"];

**Comment by texas2010** [comment]
@henrihyacinthe 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
