### ISSUE TITLE
Translation Support - Challenge History and Change Detection

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#7195]
With our various translations coming on-line soon, we're going to start to run into issue with keeping those translations in sync as changes are made to the curriculum.  Luckily we already have a system in place for tracking changes in the challenges which we can leverage to help.
### What is in Place Now

When challenges are read into the database via the `node seed` command, there is a section of code which calculates a 32 bit checksum based on the contents of the English Title, Description, Challenge Seed, and Tests.  These checksums are appended to the Google Analytics submissions we make as challenges are completed.

Code Here:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/index.js#L45
### Requirements

We need to be able to do the following:
1. Subscribe and react to [GitHub Webhooks](https://developer.github.com/webhooks/) for changes on the challenge *.json files.
2. Read in the latest JSON files on `staging` and/or `master` and calculate the current checksum for each challenge.
3. Keep a history, by challenge ID, of seen challenge checksums.  
   When a checksum change occurs:
   - Alert a list of subscribers that a change has occurred (Via e-mail, etc.)
   - Display a "Diff" of a challenge between any two given checksums
4. As a side effect, we should have a searchable history of all changes made to all challenges over time.  It should be possible to analyze past commits to challenge .json files and show the state of a challenge at that time.
5. There will need to be a way to manage e-mail subscriptions, or only subscribe to certain types of changes.  No idea what this would need to look like.
6. Opportunistic:  Data visualization stuff for changes to challenges over time.  It would be nice to visualize the changes (and change size) to a given challenge file.
### Rollout

This should probably be a stand alone, web based tool.  It will need to be web based just to respond to webhook requests.  We can potentially run this on an FCC "utility" server.  It makes sense to have one server so the comparisons only need to be one once per commit.

**Comment by vtamara** [comment]
Thank you for helping.

IMHO using gettext would be easier.  

The sources of the application are changed to send the strins that require translation through a function (typically the function t or _t), that function will return the same string but in the language that must be presented (that depends on user preference, route and/or req.lang or whatever criteria is decided).

A tool (xgettext typically or another one tailored) checks the sources and puts every string that could require translation in a file (e.g locale/fcc.pot).  The same tool (or tools) can be run every time the sources are updated to detect changes in strings.  

For each target language, another tool (msginit or msgmerge) should be run also every time that locale/fcc.pot changes, to udpate the strings to translate in each target language (e.g lcoale/es/fcc.po, locale/pt_BR/fcc.po, .....).  These tools will leave intact translations that don't require updating, but will "mark" strings that require initial translation or updating.

Each translation team checks regularly their file, looking for strings marked as needing update (or inital translation) and translate those strings (or some of them according to their available time).  Whenever a team updates its file another tool (msgfmt) is run to check and to generate a "compiled" version of the translation that is binary, and has indexes that makes finding a translation extremely fast for the function _t or t used in sources.

Besides being very standard and well known procedure for translators, there are many tools that help, there are graphical and web interfaces developed for doing these processes (some are paid, some are open source).

**Comment by SaintPeter** [comment]
I am not familiar with `gettext` at all.  

My primary concern with this proposal is simply to provide an alert to and a history of changes to the "mainline" English tile and description, as well as the challenge seed and tests.  It's possible that some of these changes would not require a corresponding update to the translation, but I figure it's important to highlight all changes.

@bugron's bot, it seems, could be updated to trigger on changes to the *.json files and run an analysis engine.

The key here is to automate the process of tracking changes, removing the need to manually run tools or manually inspect the files.  Are you saying that you have already created tools to automate this process?  What is `xgettext`?

**Comment by vtamara** [comment]
All these tools already exist.  I propose to use them.

**Comment by vtamara** [comment]
Well find way to use them.

**Comment by QuincyLarson** [comment]
@SaintPeter is this still something you're interested in implementing?
