### ISSUE TITLE
Value of b=10 not 15 Pluss c=?I am a String! or I am a String!String! Please check it. Thanks

### ISSUE THREAD

**Issue by DerejeKitaw** [FreeCodeCamp/FreeCodeCamp#7197]
Challenge [Understanding Uninitialized Variables](http://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%3D6%20%3B%20b%20%3D%2010%20%3B%20c%3D'I%20am%20a%20String!'%3B%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a=6 ; b = 10 ; c='I am a String!';
a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by DerejeKitaw** [comment]
a=6 ; b = 15 ; c='I am a String!'; Should make it all green. I observe making b=10 make green

**Comment by DerejeKitaw** [comment]
no issue

**Comment by HedayaAli** [comment]
I have the same issue here, did you solved it yet ??
