### ISSUE TITLE
Image URL in profile need not end with any extension

### ISSUE THREAD

**Issue by thirumal** [FreeCodeCamp/freecodecamp#72]
Please remove this limitation, this is not correct.

Usually gravatars are served as blobs. For example, here's mine: 

https://avatars0.githubusercontent.com/u/1734792

**Comment by QuincyLarson** [comment]
Wow - I didn't realize this was possible! You're right, I'll remove the new form validation today. Thanks for pointing this out.

**Comment by terakilobyte** [comment]
These changes are now integrated so I'm closing this issue.
