### ISSUE TITLE
Option 1 in "Create a Bootstrap Row" is not done with correct solution.

### ISSUE THREAD

**Issue by limbail** [FreeCodeCamp/FreeCodeCamp#7201]
Challenge [Create a Bootstrap Row](http://www.freecodecamp.com/challenges/create-a-bootstrap-row#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.

Hi!,

The first objective is not complete with correct answer:

Objective: Add a div element below your h3 element.

My code:

```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div> <------ here is the div, and the first solution not change.
  </div>
</div>
```

**Comment by cannelflow** [comment]
instructions are Create a div element below the h3 tag, with a class of row. 
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div> <------ here is the div you need to add class name row
  </div>
</div>
its better to ask this in chat forum https://gitter.im/FreeCodeCamp/FreeCodeCamp

**Comment by AkiraLaine** [comment]
Closing this as it's not an issue.

**Comment by limbail** [comment]
Yeah, I know the solution.

The first objective are not clear (tip).

Add a div element below your h3 element. (this one, if u create the div, not change to green.)
Your div element should have the class row (if you complete this, the first one and the second one change to green)
Your row div should be nested inside the container-fluid div
Make sure your div element has a closing tag.

Anyway, thx for answer.

**Comment by jenny0325** [comment]
the solution is
 <div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
<div class="row">    <---it works because it is under the h3 element.
  </div>
  </div>

**Comment by esaky** [comment]
This code make it right.
```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row"></div>
</div>
```

**Comment by EscobarMAldonado** [comment]
<div class=" container-fluid">
   <h3 class="text-primary text-center">jQuery Playground</h3>
      <div class="row "> </div>
         </div>

**Comment by EscobarMAldonado** [comment]
this wiil work!!! 
< div class=" container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
<div class="row "> </div>
  
  
</div>

**Comment by theabstact237** [comment]
i was confused just like you

**Comment by dammyout** [comment]
I also encounter the same error, help me
