### ISSUE TITLE
I am not able to understand this question. Does it mean i should add dots if num>3. if so program is not working with testcases

### ISSUE THREAD

**Issue by amruthpolavarapu** [FreeCodeCamp/FreeCodeCamp#7202]
Challenge [Truncate a string](http://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20%0A%20%20%0A%20%20%0A%20%20%20%20if(num%3E3)%0A%20%20%20%20%7Bstr%3Dstr.slice(0%2Cnum-2)%3B%0A%20%20%20%20%20%20var%20k%3Dstr.concat('...')%3B%0A%20%20return%20k%3B%0A%20%20%20%20%7D%0A%20%20%20else%0A%20%20%7B%20%20%0A%20%20%20%20%20%20str%3Dstr.slice(0%2Cnum)%3B%0A%20%20%20%20return%20str%3B%0A%7D%7D%0A%0Atruncate(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%20%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22.length%20%2B%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncate(str, num) {
  // Clear out that junk in your trunk
  
  
  
    if(num>3)
    {str=str.slice(0,num-2);
      var k=str.concat('...');
  return k;
    }
   else
  {  
      str=str.slice(0,num);
    return str;
}}

truncate("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length + 2);

```

**Comment by AkiraLaine** [comment]
Hey! if you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is for issues only.
