### ISSUE TITLE
Newly added challenges are completely unreasonable especially for a newby! 

### ISSUE THREAD

**Issue by adelevann** [FreeCodeCamp/FreeCodeCamp#7207]
Dear CodeCamp People

I am extremely frustrated with the new challenges brought on. They completely defeat the purpose of 'training' and come across as if one should already know this. I am battling only with the challenges that has the 'new' tag on. I don't know if you assigned a new person to add these challenges but I URGE you to have a look at them as I am now completely bowled over and can't move forward as it's like hitting a horse with a stick from behind while it's already standing against a wall. The questions and statements are very unclear and one can't learn from this! I'm very upset as a lot of time and effort goes into completing these challenges and I am really trying but I just don't understand them!

PLEASE urgently look into this!

Challenge [Convert Celsius to Fahrenheit](http://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(celsius) {
  // Only change code below this line
  

  // Only change code above this line
  if ( typeof fahrenheit !== 'undefined' ) {
    return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(30);

```

**Comment by AkiraLaine** [comment]
Hi @adelevann. Part of learning process is being stuck, failing and trying again. Everybody on FCC has gone through the same Map and have done the same challenges (including this one). 

If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or our [help](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room. GitHub is for issues only.

Happy coding :smile:

**Comment by mas212** [comment]
@adelevann 
function convert(celsius) {
  // Only change code below this line
  var fahrenheit = ((celsius * 9) / 5) + 32;

  // Only change code above this line
  if ( typeof fahrenheit !== 'undefined' ) {
    return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(30);
