### ISSUE TITLE
Voting App Example authentication fails

### ISSUE THREAD

**Issue by jessjo** [FreeCodeCamp/FreeCodeCamp#7209]
#### Issue Description
Steps to reproduce:
- Visit https://fcc-voting-arthow4n.herokuapp.com/  (listed example for build a voting App)
- Click to log in to twitter
- Agree to allow authentication.

Expected results:
Authentication occurs

Actual results:
Site says redirect will occur but I get a blank window. Refreshing still shows me as unauthenticated. Multiple attempts produce same result (but twitter no longer asks me to authorize). Viewing twitter.com verifies I am logged in to twitter.

#### Browser Information
* Browser Name, Version: Chrome Version 48.0.2564.103 (64-bit)
* Operating System: Mac OS X Yosemite

http://www.freecodecamp.com/challenges/build-a-voting-app

It would be great to have this fixed as authentication is the only way you can get an example of building the poll.

**Comment by AkiraLaine** [comment]
This happens for me too,

**Comment by alistermada** [comment]
Two ways to fix this issue:

1.  Contact the creator of this project directly and hope they'll fix this bug.
2.  Link to a different project that meets all user stories and doesn't have this bug

My vote's on option 2.

**Comment by raisedadead** [comment]
@alistermada @AkiraLaine :

Its broken because there is a protocol mismatch:

![1](https://cloud.githubusercontent.com/assets/1884376/13284374/e0c23a50-db19-11e5-850a-691c48b342aa.PNG)

@arthow4n can you confirm, that in the twitter integration dashboard the callback URL path is correctly configured?

**Comment by arthow4n** [comment]
@raisedadead Hi there, thanks for noticing me about the bug.
I've changed the callback URL to https://, and it should be working now.
@alistermada Yes, I didn't know my project  have become the example until now.

**Comment by raisedadead** [comment]
Yup It works now! :+1: 
Thanks a lot for fixing this so fast @arthow4n !

**Comment by bugron** [comment]
Closing this issue as resolved. @jessjo thanks for reporting, @alistermada, @AkiraLaine, @raisedadead thanks for confirming, @arthow4n thanks for fixing.

**Comment by arthow4n** [comment]
I've updated the app with force-ssl on both Github and Heroku running instance.
Connections with http will be redirected to https one now, preventing fail with Twitter log-in under http (due to callback protocol mismatch).
