### ISSUE TITLE
EmptyError Loopback error after Signing In

### ISSUE THREAD

**Issue by techtolentino** [FreeCodeCamp/FreeCodeCamp#7211]
I keep running into this same error when I auth in via Github or Facebook  

`Loopback 500 EmptyError: Sequence contains no elements.`

* I set my Github OAuth ID and Secret in the `.env` file
* I set my Facebook OAuth ID and Secret in the `.env` file
* Everything else in the `.env` template I left as is shown [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

* My Github Authorization Callback URL is `http://localhost:3000/auth/github/callback`
* My Facebook Authorization Callback URL is `http://localhost:3000/auth/facebook/callback`

Here's a screenshot of what I'm running into:

<img width="543" alt="screen shot 2016-02-23 at 7 37 03 pm" src="https://cloud.githubusercontent.com/assets/6276074/13272874/eb8da844-da64-11e5-8cee-75e588b6cbcb.png">

**Comment by ltegman** [comment]
Your callback URL on those APIs should simply be `http://localhost:3000`. Please visit the [Help Contributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat if you need further help getting FCC running locally.

**Comment by techtolentino** [comment]
Thanks @ltegman.

I changed the callback URL as you suggested, but am still getting the same error. I will take this to the Help Contributors chat!

**Comment by ltegman** [comment]
@techtolentino Have you done `node seed` to seed the database? The error message is making me think your DB may be empty.

**Comment by techtolentino** [comment]
Thanks again @ltegman - that worked! I don't know where the `node seed` was in any of the contributing docs. Unless I just totally missed that step somewhere?


At any rate, it helped! Thanks again!

**Comment by ltegman** [comment]
@techtolentino The `npm run only-once` command should have done it, but sometimes there is a hiccup and it doesn't work, so that may have been the case.
