### ISSUE TITLE
Challenge: Override Styles in Subsequent CSS

### ISSUE THREAD

**Issue by spamusubi** [FreeCodeCamp/FreeCodeCamp#7216]
### Issue Description
Challenge: Override Styles in Subsequent CSS
The lesson says that the second declaration takes precendence over the first, however this is not the case in my browser. In my browser, the first declaration has precedence over the second, rendering pink text.

#### Browser Information
* Safari 9.0.3
* OS X Yoesmite 10.10.5

#### Screenshot

**Comment by AkiraLaine** [comment]
Your class declarations is messed up. You define classes like this: ```class="class1 class2"```.

Please make sure you ask in our (main)[https://gitter.im/FreeCodeCamp/FreeCodeCamp] chat if you actually have a bug before opening an issue.

Happy Coding :smile:
