### ISSUE TITLE
Check for Palindromes - Last example default test is wrong.

### ISSUE THREAD

**Issue by hpsauceman** [FreeCodeCamp/FreeCodeCamp#7218]
#### Issue Description
It says "_palindrome("0_0 (: /-\ :) 0-0") should return true_." it returns false as the underscores are different "_-" and the underscore is not removed by "/\W/g"

#### Browser Information
* Chrome 48.0.2564.116

**Comment by AkiraLaine** [comment]
Hey @hpsauceman! Please read the instructions carefully. If you need help, go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is for issues only.

**Comment by hpsauceman** [comment]
Thanks for answering.

Yes I think there is an issue. (I could be wrong as I'm obviously learning - but people skilled at JS won't be doing the lesson to report it). Can you just quickly check the lesson?

I think the test (testing if a string is a palindrome) is supposed to say:

0_0 (: /-\ :) 0_0
or
0-0 (: /-\ :) 0-0
not
0_0 (: /-\ :) 0-0 (this has a small error and is not a palindrome but is supposed to test to true)

**Comment by AkiraLaine** [comment]
It is a palindrome. You need to remove all non-alphanumeric characters. So, the string you are checking will be ```0000```

**Comment by hpsauceman** [comment]
Ok, weirdly mine comes back '0_000' (all the other tests with
non-alphanumeric characters work perfectly).

I'm using /\W/g which I thought would work fine. I guess I'm just not doing
it right yet?

**Comment by dengshilong** [comment]
"_"(underscore) is in \w, so it can be removed by "/\W/g"

**Comment by dengshilong** [comment]
The reason is "_"(underscore) is in \w, so it can't be removed by "/\W/g"

**Comment by hpsauceman** [comment]
Ok, thanks.
