### ISSUE TITLE
Symmetric Difference wrong test case

### ISSUE THREAD

**Issue by rdig** [FreeCodeCamp/FreeCodeCamp#7221]
Hi there,

I believe the last test case for the [Symmetric Difference](http://www.freecodecamp.com/challenges/symmetric-difference) challenge is wrong.

The test is:
`sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3], [5, 3, 9, 8], [1])` should return `[1, 2, 4, 5, 6, 7, 8, 9]`

This, I believe, is wrong, since actually it should return `[7, 4, 6, 2, 5, 9, 8, 1]` because:
`[3, 3, 3, 2, 5]` &Delta; `[2, 1, 5, 7]` = `[3, 1, 7]`
`[3, 1, 7]` &Delta; `[3, 4, 6, 6]` = `[1, 7, 4, 6]`
`[1, 7, 4, 6]` &Delta; `[1, 2, 3]` = `[7, 4, 6, 2, 3]`
`[7, 4, 6, 2, 3]` &Delta; `[5, 3, 9, 8]` = `[7, 4, 6, 2, 5, 9, 8]`
`[7, 4, 6, 2, 5, 9, 8]` &Delta; `[1]` = `[7, 4, 6, 2, 5, 9, 8, 1]`

Plus also think there is a typo in the test text. In ends with `')` which doesn't make sense.

PS: Didn't include code / screenshot since this is a logic issue, not a code issue

**Comment by rdig** [comment]
I am now quite sure this is a bug, since the challenge passes with `[ 7, 4, 6, 2, 5, 9, 8, 1 ]` as the last test result, and not the one provided in the description.

**Comment by erictleung** [comment]
@rdig The tests implicitly ask that the arrays be sorted (you can [see for yourself here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/advanced-bonfires.json#L99-L103)). So if you just sort your returned array, things should be good.

**Comment by rdig** [comment]
@erictleung From the source `json` I see the assertion, and yes, it makes sense since in there it's sorted, but when I first posted the issue, I was referring from the actual challenge description wording, which didn't specify any kind of sort.

I see you submitted a fix for it already, so I guess, thanks :)
