### ISSUE TITLE
Help bug

### ISSUE THREAD

**Issue by AbboudJr** [FreeCodeCamp/FreeCodeCamp#7223]
The botton help and chat are bugged, when I click them, nothing happens, I am having difficulties resolving challegens without any help.

Please fix it ASAP

**Comment by sludge256** [comment]
Try joining using these links: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-Rooms

I assume your issue is the "Join" button is not working in the chat sidecar?

**Comment by techtolentino** [comment]
@AbboudJr did you get this cleared up? Also, can you point to a specific challenge where this is happening along with the browser version as well.

The Help and Chat are working fine for me in Chrome Version 48.0.2564.116 (64-bit)

**Comment by techtolentino** [comment]
@AbboudJr a week has passed since this issue was created - have you been able to dive into more specifics or has this been resolved?

**Comment by BerkeleyTrue** [comment]
Closing as stale. @techtolentino thanks for your help :+1:
