### ISSUE TITLE
Wikimedia viewer JSONP problem

### ISSUE THREAD

**Issue by drdaveg** [FreeCodeCamp/FreeCodeCamp#7225]
NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

JSONP - which is required to solve the CORS issue on the Wikimedia viewer and a few other ziplines simply has stopped working on codepen.io.  I have asked on Glitter, checked dozens of solutions including JSONP plugins,  tried code that worked from other Freecodecampers on line, tried numerous Javascript, Ajax, JQuery, JSONP approaches, etc.  I have spent more effort on overcoming CORS than on the rest of this curriculum combined.

#### Issue Description
A JQuery call produces a CORS error.  Different JSONP issues require access to the JSON file: jquery4u.settings.json (which we don't have on codepen.io).  We could overcome this on our own server by configuring server parameters, but we cannot configure the codepen.io server.  Simple Ajax calls fail (i.e., "failure:").

#### Browser Information
Windows 8, using Chrome and Fireforx

#### Your Code
I have obviously tried a lot of commented out approaches.

var arrResults = [];
var html = '';
var endpoint = "https://en.wikipedia.org/w/api.php?";
var call = endpoint + "format=jsonp&action=query&callback=?&titles="; //prop=info&  jsonpCallback 
var response = "";  
var dataRec = [];

/*
function w3r_callback(data){
   console.log(data);
}

$.getJSON(request,
{
  titles: getItem
},
function(data) {
   console.log
  //$.each(data.items, function(i,item){
  //$("a href=").attr("src", item.media.m).appendTo("#results");
  //if ( i == 10 ) return false;
});
});
*/
/*jsonCallback(
	{ 		"sites": 		[ 			{
				"siteName": "JQUERY4U",
				"domainName": "http://www.jquery4u.com",
				"description": "#1 jQuery Blog for your Daily News, Plugins, Tuts/Tips & Code Snippets."
			},
			{ 				"siteName": "BLOGOOLA", ....			}
      ]);    */      
      
      
/*var api = new mw.Api( {
    ajax: {
        headers: { 'Api-User-Agent': 'Example/1.0' }
    }
} );
*/

//$.getJSON( "ajax/test.json", function( data ) {
//  var items = [];
//  $.each( data, function( key, val ) {    items.push( "<li id='" + key + "'>" + val + "</li>" );   });
//  $( "<ul/>", {     "class": "my-new-list",     html: items.join( "" )    }).appendTo( "body" ); });
//  $.each( data, function( key, val ) {    items.push( "<li id='" + key + "'>" + val + "</li>" );   });
//  $( "<ul/>", {     "class": "my-new-list",     html: items.join( "" )    }).appendTo( "body" ); });
// $.ajax({  dataType: "json",   url: link,  data: response,  success: parseRecords() });

function result(title, snippet) {
  this.title = title;
  this.snippet = snippet;
}

function getRecords() {
  console.log("going to get a wiki page");
  var sought = document.getElementById("searched").value;
  var request = call + sought;
  var response = "";
  var rr = "";
 console.log("using address for items as:"+request);
//  $.getJSON(request, function(json) {
//                  $(".message").html(JSON.stringify(json));   });      

 function jsonpCallback () {
     console.log("in jsonpCallback");  
  }
 /* 
 jQuery.support.cors = true;
 $.ajax({
  url: request, 
  dataType: "jsonp",  // was json
         contentType : "text/html",
        callbackParameter : 'jsonpCallback',  // $.jsonp only; $.ajax uses 'jsonpCallback'
 
  type: 'GET',  // was post in his
  headers: { 'Api-User-Agent': 'Example/1.0'    ,
            'Access-Control-Allow-Origin' : '*' },
  success: function(data) { // parseRecords(response) 
    alert("logging data in ajax success:");
    //alert(data);
    //alert("json parse");
    rr  = JSON.parse(data);  
    console.log(JSON.stringify(rr));
    console.log("done");
  },
   failure: //function(XHR, textStatus, errorThrown) 
      function() { alert("failed"); },
   error: function(XHR, textStatus, errorThrown) {
      alert("something went wrong: "+ textStatus + "|" + errorThrown);
    }
  });
  console.log("past ajax query but still in get records");
*/
  
  $.getJSON(request,
function(data) {
        rr  = JSON.parse(data);  
       console.log(JSON.stringify(rr));
});
  /*
  $.ajax({
    url: link + '&srsearch=' + sought, dataType: 'jsonp', type: 'POST',
    headers: { 'Api-User-Agent': 'Example/1.0' },
    sucess: function(data) {
     // $('.results').empty();  // avoid showing previous results
     // arrResults.length = 0;        // Then we also clear the array with the results 
      var resArr = data.query.search;
      for (var result in resArr) {
        //arrResults.push(new Result(resArr[result].title, resArr[result].snippet));
        html = '<div id="articles" class="article"><a href="https://en.wikipedia.org/wiki/' + resArr[result].title + '"target="_blank">' + resArr[result].title + '<p>' + resArr[result].snippet + '</p></a></div>';
        $('.results').append(html); // Displays the elements to the page
      }}});

  console.log("trying to send REST request from JSP");
  var xhr = new XMLHttpRequest( );  // {mozSystem : true}
  xhr.open("GET",  request, false);  
  xhr.setRequestHeader( 'Api-User-Agent', 'Example/1.0' ); 
  xhr.setRequestHeader( 'Access-Control-Allow-Credentials', 'True');
  xhr.setRequestHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
  xhr.setRequestHeader('Access-Control-Allow-Origin','*');
  xhr.send();    console.log(xhr.statusText);    console.log(xhr.responseText);
  */
 }

**Comment by ltegman** [comment]
I'm sorry, but as your issue says at the top of it:
> NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

`jsonp` definitely does still work in CodePen. Here's a (confirmed working) sample of how you might query the Wikipedia API in codepen:
```js
$.getJSON('http://en.wikipedia.org/w/api.php?format=json&action=query&generator=search&gsrnamespace=0&gsrlimit=10&prop=pageimages|extracts&pilimit=max&exintro&explaintext&exsentences=1&exlimit=max&gsrsearch=' + term + '&callback=?');
```
The `&callback=?` at the end tells jQuery this is a `jsonp` request.
Hope that gets you on the right track! Good luck and happy coding!

**Comment by drdaveg** [comment]
This is a very strange problem: I can take other people's code that works and it doesn't work for me.  I can get it to work intermitently and then not.  Something is wrong with codepen.io.  I have spent more time on this problem than the rest of the course combined.

--------------------------------------------
On Wed, 2/24/16, Logan Tegman <notifications@github.com> wrote:

 Subject: Re: [FreeCodeCamp] Wikimedia viewer JSONP problem (#7225)
 To: "FreeCodeCamp/FreeCodeCamp" <FreeCodeCamp@noreply.github.com>
 Cc: "drdaveg" <drdaveceo@yahoo.com>
 Date: Wednesday, February 24, 2016, 5:27 PM
 
 I'm sorry, but as your issue
 says at the top of it:
 
 
 NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help
 
 
 jsonp definitely does still work in CodePen.
 Here's a (confirmed working) sample of how you might
 query the Wikipedia API in codepen:
 
 $.getJSON('http://en.wikipedia.org/w/api.php?format=json&action=query&generator=search&gsrnamespace=0&gsrlimit=10&prop=pageimages|extracts&pilimit=max&exintro&explaintext&exsentences=1&exlimit=max&gsrsearch=' + term + '&callback=?');
 
 The &callback=? at the end tells jQuery
 this is a jsonp request.
 
 Hope that gets you on the right track! Good luck and happy
 coding!
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by KairatKempirbaev** [comment]
http://api.jquery.com/jQuery.getJSON/
JSONP //Paragraph

If the URL includes the string "callback=?" (or similar, as defined by the server-side API), the request is treated as JSONP instead. See the discussion of the jsonp data type in $.ajax() for more details.
