### ISSUE TITLE
Remove unnecessary comments from Cesar Cypher

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7226]
Unlike the other algorithm challenges, this one still has a lot of comments and declared variables (hold-overs from it originally being a "check point" challenge in our Basic JavaScript block of challenges). These should be removed, and it should be as sparse as our other algorithm challenges.

Challenge [Caesars Cipher](http://www.freecodecamp.com/challenges/caesars-cipher#?solution=function%20rot13(encodedStr)%20%7B%0A%20%20var%20codeArr%20%3D%20encodedStr.split(%22%22)%3B%20%20%2F%2F%20String%20to%20Array%0A%20%20var%20decodedArr%20%3D%20%5B%5D%3B%20%2F%2F%20Your%20Result%20goes%20here%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20decodedArr.join(%22%22)%3B%20%2F%2F%20Array%20to%20String%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function rot13(encodedStr) {
  var codeArr = encodedStr.split("");  // String to Array
  var decodedArr = []; // Your Result goes here
  // Only change code below this line
  
  
  
  // Only change code above this line
  return decodedArr.join(""); // Array to String
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

**Comment by NolanChan** [comment]
Do you mean to remove the code in the `solutions` part?

**Comment by QuincyLarson** [comment]
@NolanChan Yes. I think we should remove this:
```
  var codeArr = encodedStr.split("");  // String to Array
  var decodedArr = []; // Your Result goes here
  // Only change code below this line
```

And change this:
```
  // Only change code above this line
  return decodedArr.join(""); // Array to String
}

// Change the inputs below to test
```
to:
```
  return encodedStr;
}

rot13("SERR PBQR PNZC");
```

**Comment by NolanChan** [comment]
@QuincyLarson but won't the provided solution break the tests? Or at least if I change this code in the solutions to this simplified version, the tests break. I feel like I'm doing something wrong...

**Comment by ltegman** [comment]
@NolanChan The solution shouldn't need to change since the challenge requirements aren't changing. The only thing that needs to change is the seed.

**Comment by erictleung** [comment]
I agree with @NolanChan. This issue is a little confusing. I'm still unsure on which to change: the `challengeSeed` or the `solutions`.

Also, I think this issue might need to be closed because the `challengeSeed` is [already sparsed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L697-L703). The [live site](http://www.freecodecamp.com/challenges/caesars-cipher) even already has the unnecessary comments and variables removed.

![image](https://cloud.githubusercontent.com/assets/2754821/13377742/1ffa1834-dd9d-11e5-986a-889e91530b1a.png)

But the only thing I see that could be changed is change the input parameter `str` to `encodedStr`.

**Comment by ltegman** [comment]
Good catch @erictleung. Looks like this had already been fixed. Quincy must have been seeing a version that got saved into localStorage before the change was made. Closing as resolved.

**Comment by NolanChan** [comment]
@erictleung Whew thanks for confirming! I thought I was crazy
