### ISSUE TITLE
Won't accept the correct answer!

### ISSUE THREAD

**Issue by awanumair** [FreeCodeCamp/FreeCodeCamp#7229]
Challenge [Use RGB to Color Elements White](http://www.freecodecamp.com/challenges/use-rgb-to-color-elements-white#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%0A%20%20%20%20%20%20rgb(225%2C%20225%2C%20225)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: 
      rgb(225, 225, 225);
  }
</style>

```

**Comment by sludge256** [comment]
Closing as [resolved](https://gitter.im/FreeCodeCamp/Help?at=56ce1c91bfb1cf9a7ff2d3cf)

**Comment by AndrewBasore** [comment]
If it's not obvious the solution: The values should be 255 not 225. I just made the same mistake :-)
