### ISSUE TITLE
problem with waypoint 24 in html

### ISSUE THREAD

**Issue by Tedm82** [FreeCodeCamp/freecodecamp#724]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. 

You do not have to create a full paragraph. if you just start to write a p tag it will complete  the challenge. You don't even have to close out the tag

**Comment by LumenTeun** [comment]
I can not reproduce this in neither Firefox nor Chromium. Is it still a problem @Tedm82?

**Comment by QuincyLarson** [comment]
I've added an additional test checking for the closing tag. This should no longer be an issue. Thank you @tedm82 for submitting and @lumenteun for following up.
