### ISSUE TITLE
Migrate from Mandrill to Amazon SES

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7240]
We're currently using Mandrill for sending two emails: 
1. our initial welcome email 
2. our password reset email

Mandrill will no longer be free (it will be non-trivially expensive, like Mailchimp is), so we can move to Amazon SES, which we use for our weekly email blasts.

We need to do this by April 26 at the absolute latest or these emails will stop going out.

@BerkeleyTrue how hard do you think it would be to make this transition? Is it just changing a few environment variables, or will more work need to be done?

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

They give 100,000 free emails per month.

**Comment by BerkeleyTrue** [comment]
@yepher ?

**Comment by richleland** [comment]
If you're open to it, we'd love to have you give [SparkPost](https://www.sparkpost.com) a go - we have a 100k/mo free plan and hang out on http://slack.sparkpost.com if you are interested in chatting with us.

**Comment by richleland** [comment]
We also have a handy dandy [guide](https://www.sparkpost.com/mandrill-migration-guide) :smile:

**Comment by ltegman** [comment]
@richleland Please do not use our Github issues to advertise your service.

**Comment by BerkeleyTrue** [comment]
Do not use our issue tracker to post unrelated adverts. They are removed.

**Comment by richleland** [comment]
Sincerest apologies @BerkeleyTrue @ltegman - message heard loud and clear - sorry for stomping on the issue!
