### ISSUE TITLE
French translation of Getting Started

### ISSUE THREAD

**Issue by thejonathangraham** [FreeCodeCamp/FreeCodeCamp#7244]
ALL Verified - View the PR here - https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7286

- [x] Learn how Free Code Camp Works
- [x] Create a GitHub Account and Join our Chat Rooms
- [x] Configure your Code Portfolio
- [x] Join a Campsite in Your City
- [x] Learn What to Do If You Get Stuck

**Comment by fnonga** [comment]
I can help if you want, im french.

**Comment by fnonga** [comment]
give me push access, i will translate every thing in a good french

**Comment by bugron** [comment]
@fnonga feel free to clone the repo, translate challenges and then open a pull request.

**Comment by bugron** [comment]
@thejonathangraham this issue will be closed once https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7286 is merged. Add `closes #7244` to your PR's comment to auto-close this issue.

**Comment by thejonathangraham** [comment]
@bugron DOne!

**Comment by abisz** [comment]
Hey guys, I was just translating this section and I noticed a mistake in the french version. (Currently) on line 662 ("Configurer votre code portefeuille") the text is in the wrong challenge. It should be one above - therefore one challenge ("Join a Campsite in Your City") is missing a french version

**Comment by theflametrooper** [comment]
@abisz Hey! Could you submit a PR with those changes?

**Comment by abisz** [comment]
I could change the position of the wrong text, but somebody who actually speaks french would need to translate the missing one...

**Comment by theflametrooper** [comment]
@abisz No worries, I'll get someone else onto it ;)
