### ISSUE TITLE
Want pass all test

### ISSUE THREAD

**Issue by Rogers187** [FreeCodeCamp/FreeCodeCamp#7249]
Challenge [Chaining If Else Statements](http://www.freecodecamp.com/challenges/chaining-if-else-statements#?solution=function%20myTest(num)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(num%20%3C%205)%7B%0A%20%20%20%20return%20%22tiny%22%3B%0A%20%20%7D%0A%20else%20if%20(num%20%3C%2010)%7B%0A%20%20%20%20return%20%22small%22%3B%0A%20%20%7D%0A%20else%20if%20(num%20%3C%2015)%7B%0A%20%20%20%20return%20%22medium%22%3B%0A%20%20%7D%0A%20else%20if%20(num%20%3C%2020)%7B%0A%20%20%20%20return%20%22large%22%3B%0A%20%20%7D%0A%20else%20if%20(num%20%3E%3D%2025)%7B%0A%20%20%20%20return%20%22huge%22%3B%0A%20%20%0A%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%7D%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(0)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/48.0.2564.104 Mobile/13D15 Safari/601.1.46</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(num) {
  // Only change code below this line
  if (num < 5){
    return "tiny";
  }
 else if (num < 10){
    return "small";
  }
 else if (num < 15){
    return "medium";
  }
 else if (num < 20){
    return "large";
  }
 else if (num >= 25){
    return "huge";
  
 }
  
  // Only change code above this line

}
// Change this value to test
myTest(0);

```

**Comment by ltegman** [comment]
Pay close attention to the details of what the expected return values are. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need assistance because Github issues are not for challenge help. Thanks and happy coding!

**Comment by cpereversoff** [comment]
I did exactly the same thing, i suggest paying attention to case sensitivity
