### ISSUE TITLE
Issue with loop on Exact Change algorithm

### ISSUE THREAD

**Issue by valmunos** [FreeCodeCamp/FreeCodeCamp#7250]
Challenge [Exact Change](http://www.freecodecamp.com/challenges/exact-change#?solution=function%20drawer(price%2C%20cash%2C%20cid)%20%7B%0A%20%20var%20change%20%3D%20cash%20-%20price%3B%0A%20%20var%20increment%20%3D%20%5B0.01%2C%200.05%2C%200.10%2C%200.25%2C%201.00%2C%205.00%2C%2010.00%2C%2020.00%2C%20100.00%5D%3B%0A%20%20var%20bills%20%3D%200%3B%0A%20%20var%20count%20%3D%200%3B%0A%20%20var%20ledger%20%3D%20%5B%5D%3B%0A%20%20for%20(i%20%3D%208%3B%20i%20%3E%3D%200%3B%20i--)%20%7B%0A%20%20%20%20if%20(change%20%3E%3D%20increment%5Bi%5D%20%26%26%20cid%5Bi%5D%5B1%5D%20%3E%200)%20%7B%0A%20%20%20%20%20%20bills%20%3D%20cid%5Bi%5D%5B1%5D%2Fincrement%5Bi%5D%3B%0A%20%20%20%20%20%20count%20%3D%20bills%3B%0A%20%20%20%20%20%20while%20(count%20%3E%200%20%26%26%20change%20%3E%200)%20%7B%0A%20%20%20%20%20%20%20%20change%20%3D%20change%20-%20increment%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20if%20(change%20%3C%200)%20%7B%0A%20%20%20%20%20%20%20%20%20%20change%20%3D%20change%20%2B%20increment%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20count%20%3D%20count%20-%201%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20ledger.push(%5Bcid%5Bi%5D%5B0%5D%2C%20(bills-count)*increment%5Bi%5D%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%2F%2F%20Here%20is%20your%20change%2C%20ma%27am.%0A%20%20return%20change%3B%0A%7D%0A%0Adrawer(3.26%2C%20100.00%2C%20%5B%5B%22PENNY%22%2C%201.01%5D%2C%20%5B%22NICKEL%22%2C%202.05%5D%2C%20%5B%22DIME%22%2C%203.10%5D%2C%20%5B%22QUARTER%22%2C%204.25%5D%2C%20%5B%22ONE%22%2C%2090.00%5D%2C%20%5B%22FIVE%22%2C%2055.00%5D%2C%20%5B%22TEN%22%2C%2020.00%5D%2C%20%5B%22TWENTY%22%2C%2060.00%5D%2C%20%5B%22ONE%20HUNDRED%22%2C%20100.00%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drawer(price, cash, cid) {
  var change = cash - price;
  var increment = [0.01, 0.05, 0.10, 0.25, 1.00, 5.00, 10.00, 20.00, 100.00];
  var bills = 0;
  var count = 0;
  var ledger = [];
  for (i = 8; i >= 0; i--) {
    if (change >= increment[i] && cid[i][1] > 0) {
      bills = cid[i][1]/increment[i];
      count = bills;
      while (count > 0 && change > 0) {
        change = change - increment[i];
        if (change < 0) {
          change = change + increment[i];
          break;
        }
        count = count - 1;
      }
      ledger.push([cid[i][0], (bills-count)*increment[i]]);
    }
  }
  // Here is your change, ma'am.
  return change;
}

drawer(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);

```
So, the way this code works is it subtracts the available change until the balance reaches zero.  My variable "ledger" is what you would return to see what is being returned to the customer while my "change" variable keeps track of what is still due.  On the fifth test case (price = 100, cash = 3.26) the code returned [["TWENTY", 60.00], ["TEN", 20.00], ["FIVE", 15], ["ONE", 1], ["QUARTER", 0.50], ["DIME", 0.20], ["PENNY", 0.03]], which is one penny short of what it should be returning.  I checked the "change" variable, and it returned 0.009999999999994869, which means that somewhere along the way it subtracted some small fraction in addition to the numbers it was supposed to.  

One workaround would be to multiply everything by 100 and use the round function, but the code should still should've worked.  Can someone give me some insight on what might be going wrong?  thanks.

**Comment by ltegman** [comment]
Javascript numbers are floating point and you're seeing one of the repercussions of that. There are various ways around this documented on the internet. Github issues are not for challenge help so I encourage you to do some googling or visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript). Thanks and happy coding!

**Comment by valmunos** [comment]
Sorry, I really thought it might have been a bug of some sort.
