### ISSUE TITLE
Issue in palindrome

### ISSUE THREAD

**Issue by vinodindia** [FreeCodeCamp/FreeCodeCamp#7251]
#### Issue Description
* How could "0_0 (: /-\ :) 0-0" this expression be a palindrome??
* check the last test case

#### Your Code

function palindrome(str) {
  // Good luck!
  var x = [];
  x= str.split('');
  x.reverse();
  var y = x.join('');
  var str1 = y.replace(/[".,\s]/g,'');
  var str2 = str.replace(/[".,\s]/g,'');
  str1 = str1.toLowerCase();
  str2 = str2.toLowerCase();
  if(str1==str2)
   return str2;
  else
    return str2;
}

palindrome("0_0 (: /-\ :) 0-0");

**Comment by bugron** [comment]
@vinodindia thanks for posting this issue!
See #7218, for example.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ltegman** [comment]
This instructions ask you to remove all non-alphanumeric characters, leaving `0000`. Thanks and happy coding!

**Comment by vinodindia** [comment]
Hey sorry this mean we should take only characters and number and we have to exclude all the special characters..!!

**Comment by vinodindia** [comment]
Thank you Itegman
