### ISSUE TITLE
Console.log tip capitalization

### ISSUE THREAD

**Issue by demipixel** [FreeCodeCamp/FreeCodeCamp#7252]
I haven't done anything else yet, but when I started at Basic Algorithm Scripting, the tip to output to the log seems to be misleading to newer coders:

```
/**
  * Your output will go here.
  * Console.log() -type statements
  * will appear in your browser's
  * DevTools Javascript console.
  */
```

Small issue but someone recommended I make it anyway.

**Comment by bugron** [comment]
@demipixel thanks for posting. So basically someone needs to change `Console.log() -type statements` to `console.log() - type statements`.

**Comment by chanxdesigns** [comment]
Basically everything should be in lowercase in `console.log() `
