### ISSUE TITLE
Text in instructions inconsistent size

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7255]
Challenge [Headline with the h2 Element](http://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
```

Here's a screenshot: 

![](https://www.evernote.com/l/Ar-YDpyZOUJFzYC-NrZrjpgtYP_stLYZYgQB/image.png)

@SaintPeter We should probably audit the challenges to see whether any other challenges have inconsistently-sized text as well.

**Comment by techtolentino** [comment]
I was toying around with this one, and it seems to me like the `<code>h4</code>` is what's breaking the rendering of the font-size. I'm unfamiliar with Jade, if that's in fact what's reading the `html5-and-css.json` file and spitting out the actual html.

However, I'm also seeing that an `h4` is referenced in this block:

```
.challenge-instructions
  for sentence in description
    if (/blockquote|h4|table/.test(sentence))
      !=sentence
    else
      p.wrappable!= sentence
```

I would love tofigured this one out and get my first PR going! But if someone can step in or is already in the process, have at it.

**Comment by raisedadead** [comment]
##### Auditing challenges for any inconsistently-sized text:

*HTML5 and CSS*: 
- Challenge mentioned in the issue description above. Addressed with a PR #7266 already.

*Responsive Design with Bootstrap* : 
- http://www.freecodecamp.com/challenges/label-bootstrap-wells

*Gear up for Success*:
-  :+1: 

*jQuery*:
-  :+1:

**Comment by raisedadead** [comment]
@techtolentino Can you fix the "Label Bootstrap Well" challenge, since you are at this?

**Comment by ltegman** [comment]
Closed by #7266. This is a change to the template, so it will fix any challenge with this problem! :+1:

**Comment by techtolentino** [comment]
@raisedadead i can, which issue is that? Or has it been handled?

**Comment by raisedadead** [comment]
@techtolentino Thanks I guess as per @ltegman it should be resolved with your fix.
