### ISSUE TITLE
Never processes the challenge.

### ISSUE THREAD

**Issue by ryantheleach** [FreeCodeCamp/FreeCodeCamp#7256]
Challenge [Fill in the Blank with Placeholder Text](http://www.freecodecamp.com/challenges/fill-in-the-blank-with-placeholder-text#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsom%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2652.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Kitty ipsom dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by ltegman** [comment]
There's a typo in your kitty ipsum text. Thanks and happy coding!

**Comment by ryantheleach** [comment]
Cheers, I feel dumb now, I did double check and look over it, but sometimes 1 letter mistakes can be missed rather easily.

Do you have any metrics on how many people drop the camp at each stage? Maybe some sort of spell check or something on this stage could help retain campers?
