### ISSUE TITLE
repeating code, unmanageable..

### ISSUE THREAD

**Issue by extrememachinist** [freeCodeCamp/freeCodeCamp#7259]
Trying to complete lessons, but code is becoming unmanageable:
- flags auto duplicate themselves, so instead of `<p>` I get `<pp>`
- same with content, `hello` paragraph becomes `hello world hello world` 
- it is undeleteable as every time I move the cursor it repeats again.
#### Browser Information
- Mozilla Firefox for Mobile, Version 44 (I believe)
- Android 5.1.1
#### Your Code

``` html5
If relevant(it's not)
```
#### Screenshot

Edited format for readability ~ @raisedadead

**Comment by AkiraLaine** [comment]
Hey @extrememachinist, What is your issue about? Could you be more specific? What do you mean by "flags" and "hello world" duplicating?

**Comment by extrememachinist** [comment]
Okay, while navigating and participating in the html code clinic, I attempted (several times, reload, cancel code, close browser...ect) to correct the problem of duplicate anchors as well as duplicate text to no avail. Thus, I am here

**Comment by AkiraLaine** [comment]
Are you talking about the HTML/CSS challenges? If so, which challenge in particular?

**Comment by extrememachinist** [comment]
Yes the HTML challenges. All of the challenges from <p> paragraph on..

**Comment by ltegman** [comment]
I believe this is an android (or mobile) specific problem. It's been a while since I've seen it, but this used to happen to me on Chrome Android. It makes the editor pretty much unusable.

**Comment by extrememachinist** [comment]
Okay, I understand completely. Thank you for the thorough follow up
and concern. I really appreciate all you've done.

**Comment by QuincyLarson** [comment]
@extrememachinist can you confirm whether this is still happening on Android?
