### ISSUE TITLE
HTML5 and CSS: Nest Many Elements within a Single Div Element

### ISSUE THREAD

**Issue by textPreferred** [FreeCodeCamp/FreeCodeCamp#7261]
The text in this assignment is flawed. 

The last two paragraphs read: 
> Try putting your opening div tag above your "Things cats love" p element and your closing div tag after your closing ol tag so that both of your lists are within one div.

and

> Nest your "Things cats love" and "Things cats hate" lists all within a single div element.

The latter of these looks like the real task, while the first one is more like a hint on how to solve this task.

**Comment by textPreferred** [comment]
Created pull request for a fix: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7281

**Comment by raisedadead** [comment]
@textPreferred Please create a PR as per Our [Contributing Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

**Comment by raisedadead** [comment]
@textPreferred  Your PR just rearranges the lines, closing this. Not sure what you are insisting here. Please discuss this in the [HelpChat](https://gitter.im/FreeCodeCamp/Help). We can open this after confirmation.
