### ISSUE TITLE
Cloud9 Readability

### ISSUE THREAD

**Issue by d3ddd** [FreeCodeCamp/FreeCodeCamp#7268]
#### Issue Description
* When Issue Happens

When going through Node.js and Express.js section, many of the challenges use a very light grey font color for certain information and because of Cloud9's color scheme it is almost impossible to read (screen shot attached). Personally, I've had to ask people to help me read those sections and after a few minutes of us guessing we've ended up figuring it out. But it's an unfortunate obstacle.

I'm not sure if there is any way to change this since it is on Cloud9.

----
EDIT: [

I feel dumb for not thinking about this before, but after looking through Cloud9's menus I realized that there are several different theme choices and if you choose a dark theme for the code editor it will ask you if you want to change the 'main theme' to be dark also (sounds like besides the code editor there are only two themes for the main UI - dark and light). The dark theme for the Main UI, which includes the terminal, made reading those sections WAY easier.

POSSIBLE FIX:
In either the video introduction, the list of instructions on FCC or both, it might make sense to tell campers to change to a dark theme (and then to click 'yes' when it asks if you want to change the 'main theme' to dark also) to prevent other campers from not being able to read sections of the challenges.

] END EDIT

-----

* Steps To Reproduce

- Run Most (if not any) of the Node.js and Express.js challenges in Cloud9
- I know for sure that if you run the express challenges that the very first challenge has this issue under the "HINTS" section.

#### Browser Information
* Browser Name, Version - Chrome 48.0.2564.116 (64-bit) 
* Operating System - OSX 10.10.5

#### Screenshot
![screen shot 2016-02-26 at 10 57 38 am](https://cloud.githubusercontent.com/assets/9157052/13362323/827e24e4-dc78-11e5-8536-fe66366b4ac3.png)

**Comment by AkiraLaine** [comment]
You can change the overall theme of the editor as you mentioned, or change the terminal color scheme.

**Comment by sludge256** [comment]
I would not be opposed to adding this hint. Would step 9 be a good spot to place the suggestion?

**Comment by raisedadead** [comment]
I am in favor of the a hint that links to a wiki article with screenshots.
This way it would solve a two way purpose, being a generic article to customizing C9 and a hint to the mentioned challenge.

**Comment by d3ddd** [comment]
https://docs.c9.io/docs/themes

It could be better, but cloud9 has a page on how to change the theme, screenshots included. So creating a wiki article that simply explains the low contrast issue and then links to the cloud9 page might be sufficient.

**Comment by Oxyrus** [comment]
As stated you can use another C9 theme, or try another cloud IDE such as CodeAnywhere, Nitrous, etc.
