### ISSUE TITLE
Code checks out, requirements not met and unable to proceed.

### ISSUE THREAD

**Issue by ehutchllew** [FreeCodeCamp/FreeCodeCamp#7269]
Challenge [Specify How Fonts Should Degrade](http://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">-->
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment]
Your code is passing just fine for me. Could you try refreshing the page to see if that fixes it and then post a screenshot of what you're seeing and the browser console if you can still repro after a refresh?

**Comment by ehutchllew** [comment]
Hey, thanks for taking the time to respond! So apparently it was something in my Firefox browser. I checked it out with Chrome and it worked fine.

**Comment by ltegman** [comment]
Glad to hear it! Thanks and happy coding!
