### ISSUE TITLE
Profile lookup exercise. Unchecked points although the output is correct

### ISSUE THREAD

**Issue by arakita** [freeCodeCamp/freeCodeCamp#7270]
Challenge [Profile Lookup](http://www.freecodecamp.com/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0Avar%20name%20%3D%20%5B%22Akira%22%2C%22Harry%22%2C%22Sherlock%22%2C%22Kristian%22%5D%3B%0Avar%20propDefault%3D%5B%22firstName%22%2C%22lastName%22%2C%22number%22%2C%22likes%22%5D%3B%0Afunction%20lookUp%28firstName%2C%20prop%29%7B%0A%20%20var%20a%3Dname.indexOf%28firstName%29%3B%0A%20%20var%20b%3DpropDefault.indexOf%28prop%29%3B%0A%20%20if%28a%3E-1%26%26b%3E-1%29%7B%0A%20%20%20%20return%20contacts%5Ba%5D%5Bprop%5D%3B%0A%20%20%7D%0A%20%20if%28a%3D%3D-1%29%7B%0A%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%7D%0A%20%20if%28b%3D%3D-1%29%7B%0A%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0AlookUp%28%22Sherlock%22%2C%20%22likes%22%20%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

var name = ["Akira","Harry","Sherlock","Kristian"];
var propDefault=["firstName","lastName","number","likes"];
function lookUp(firstName, prop){
  var a=name.indexOf(firstName);
  var b=propDefault.indexOf(prop);
  if(a>-1&&b>-1){
    return contacts[a][prop];
  }
  if(a==-1){
    return "No such contact";
  }
  if(b==-1){
    return "No such property";
  }

}

lookUp("Sherlock", "likes" );

```

**Comment by arakita** [comment]
Hi, my first three points are unchecked although the output is the same as what is required.

**Comment by ltegman** [comment]
Okay, so this is a weird one. Something about the fact that the variable is called `name` is causing a problem with our test runner. When you call the function in the editor the `name` variable is the array it should be, but when it's called by the testrunner the `name` variable is getting turned into a string, which causes the values returned by `indexOf` to be much higher than your code is expecting. Changing the variable name to something different like `namesList` prevents this from happening. Someone will have to dig into our test running code to figure out the cause of this.

**Comment by arakita** [comment]
ok. Thank you very much. At least my sleepless nights are worth it.

**Comment by JoshFisk** [comment]
@Itegman

It's setting window.name, that is why it's getting converted to a string.

**Comment by AkiraLaine** [comment]
@arakita Although your is technically correct and as you and @ltegman pointed out - there seems to be a test bug (not sure if this is my fault), you were suppose to use ```loops``` and ```object lookups``` for this challenge. As the previous challenges before this teach those concepts. 

Should we specify that this challenge should be completed using ```loops``` and ```lookups```?

**Comment by ltegman** [comment]
@JoshFisk Thanks for the info. I didn't realize `name` was a global variable in browsers. I don't care which way we fall on this (making global variables land on window or not) but it would be nice if the behavior of the editor and the behavior of the test runner matched.

**Comment by JoshFisk** [comment]
So you can find all the reserved variable names like this (for your own browser anyways)
```
var windowProps = [];
for(var prop in this){
  windowProps.push(prop);
}
windowProps.sort();
console.log(windowProps);
```
And block them like this
http://jshint.com/docs/options/#predef

Not sure where to do this in the repo though.

**Comment by thadseaver** [comment]
@AkiraLaine 
> You were suppose to use loops and object lookups for this challenge, as the previous challenges before this teach those concepts.

<snipped>

> Should we specify that this challenge should be completed using loops and lookups?

I would say yes, you should specify if it's required. Here's why...

1) There is (typically) more than one way to complete a challenge. If you're testing for the use of certain code, the user's answer (that may come from knowledge/study outside of FCC) may solve the challenge, yet yield a _wrong_ answer.

2) The fact that the previous challenges taught those concepts is an unfair assumption. I completed the challenges that are just prior to Profile Lookup about 3 months ago. Profile Lookup didn't exist at the time since FCC recently added many new challenges (Profile Lookup being one of them) for the 2,080 hours of coding. After the new challenges were added, I went back and completed all of the new challenges even though they weren't required. For myself, and those users who also went back to complete the extra challenges, it may have been a long time since we completed the challenges just prior to Profile Lookup. It wasn't necessarily a minute ago, or yesterday like your assumption implies. As FCC will possibly be updated in the future, this situation will be repeated.

**Comment by jbemis** [comment]
+1 my my code is correct. checked console output but the second condition doesn't pass out

**Comment by ltegman** [comment]
@jbemis Your code passes just fine for me. You may want to try refreshing the page and resubmitting.

**Comment by jbemis** [comment]
@ltegman I have tried refreshing, but the page still says I haven't passed the second test.

**Comment by sludge256** [comment]
@jbemis Your code also passes for me (assuming the contacts array is still present). Try restarting the browser completely.

**Comment by ltegman** [comment]
You can also try saving your answer in a text editor and then resetting the challenge. Perhaps you accidentally edited part of the lookup object.

**Comment by jbemis** [comment]
@ltegman bingo! thanks for the advice!

**Comment by frank0718** [comment]
i got this issue too, just clear code ,and refresh browser.

**Comment by dhcodes** [comment]
I'm trying to clear our some old issues. Shall we change:
`A lookUpProfile function that takes firstName and a property (prop) as arguments has been pre-written for you.`

to

`Using what you've learned about loops and lookups, complete the lookUpProfile function that takes firstName and a property (prop) as arguments.`

**Comment by Tikam02** [comment]
there is a redefinition of name in the code.line no.39[var name]

var name = ["Akira","Harry","Sherlock","Kristian"];
var propDefault=["firstName","lastName","number","likes"];
function lookUp(firstName, prop){
  var a=name.indexOf(firstName);
  var b=propDefault.indexOf(prop);
  if(a>-1&&b>-1){
    return contacts[a][prop];
  }
  if(a==-1){
    return "No such contact";
  }
  if(b==-1){
    return "No such property";
  }

}

lookUp("Sherlock", "likes" );

**Comment by pleabargain** [comment]
I noticed that this exercise has thrown a lot of errors. 
I did as suggested:
just clear code ,and refresh browser. ctrl + f5
still no joy

I copied the solution from the source(after failing to get ANYTHING to work) but even the source solition is not being accepted.
The history shows a change 8JAN. Is it possible that there was a new bug introduced?
here's the code: 
https://goo.gl/sO7DXR
