### ISSUE TITLE
How do i fixed my hacked laptop or find out who it was

### ISSUE THREAD

**Issue by hunnyboo** [FreeCodeCamp/FreeCodeCamp#7275]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by sludge256** [comment]
Sorry, this isn't something we can help you with, nor is it related to the Free Code Camp site/repository. Try consulting a reputable computer repair shop in your area, or searching for answers using your preferred search engine. You're bound to get results for sites and forums that deal with these types of issues. Good luck!
