### ISSUE TITLE
Site not displaying correctly

### ISSUE THREAD

**Issue by questionmark693** [FreeCodeCamp/FreeCodeCamp#7277]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When I log in to FCC, site does not display as normal (instructions, code, display from left to right) and instead displays from top to bottom.
* Simply go to any challenge, logged in or not-though I know that other people have had trouble reproducing, and my personal computer doesn't have this problem.

#### Browser Information
* Google Chrome, 48.0.2564.116 m
![capture](https://cloud.githubusercontent.com/assets/17020469/13370994/0916b4d0-dcd8-11e5-8a9e-d6681331b114.PNG)

* Windows Server 2008 R2 Enterprise

**Comment by ltegman** [comment]
This is expected. The layout changes when you are on smaller screens. Thanks and happy coding!

**Comment by questionmark693** [comment]
It's a seventeen inch screen....

**Comment by ltegman** [comment]
This process is done with media queries which use resolution.
