### ISSUE TITLE
Bug in directions 

### ISSUE THREAD

**Issue by webdev8183** [FreeCodeCamp/FreeCodeCamp#7278]
Challenge [Truncate a string](http://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20var%20result%3D%22%22%3B%0A%20%20var%20stringsize%3Dstr.length%3B%0A%20%20%0A%20%20if%20(num%3C%3D3)%7B%0A%20%20%20%20result%3D(str.slice(str%2Cnum))%3B%0A%20%20%20%20%20%20%20%20%20%20%20return%20result%3B%0A%20%20%7D%0A%20if%20(str.length%3Enum)%0A%20%20%20result%3D(str.slice(str%2Cnum)%2B%20%22...%22)%3B%0A%20%20%20%20return%20result%3B%0A%20%20%0A%20%0A%20%2F%2F%20return%20str%3B%0A%7D%0A%0Atruncate(%22Absolutely%20Longer%22%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Issue with the directions as 2 of the test cases will fail, since we are told not to add the ... if the number is less than or equal to 3.. 
truncate("A-", 1) should return "A...".
truncate("Absolutely Longer", 2) should return "Ab...".

My code:
```javascript
function truncate(str, num) {
  // Clear out that junk in your trunk
 var result="";
  var stringsize=str.length;
  
  if (num<=3){
    result=(str.slice(str,num));
           return result;
  }
 if (str.length>num)
   result=(str.slice(str,num)+ "...");
    return result;
  
 
 // return str;
}

truncate("Absolutely Longer", 3);

```

**Comment by webdev8183** [comment]
I mean if the num argument passed into the function is less than or equal to 3, per the directions the three dots  ... should not be (added) there, but it looks like the test expects them to be there. 
 I haven't completed the challenge yet, but the directions are a bit off on this one.

**Comment by ltegman** [comment]
The instructions ask you not to include the length of the ellipses into your calculation when the number is less than three, but you still have to add the characters onto the end. Thanks and happy coding!

**Comment by silverrain64** [comment]
What's the proper channel for requesting that this question be rewritten?
