### ISSUE TITLE
Wrap an Anchor Waypoint

### ISSUE THREAD

**Issue by mvoltron** [FreeCodeCamp/freecodecamp#728]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Writing "click here" is not needed to pass the way point.  That is, you can move on without doing that part.
![little bug](https://cloud.githubusercontent.com/assets/5934614/7876632/7950897c-0594-11e5-9b85-89a7c5c327aa.png)

**Comment by QuincyLarson** [comment]
This is now fixed. Thank you for pointing this out!
