### ISSUE TITLE
Challenge "Make Object Properties Private" re-introduction(?) of "this" needs link back to where we used it before

### ISSUE THREAD

**Issue by theoneinskane** [FreeCodeCamp/FreeCodeCamp#7282]
The use of the `this` keyword to determine a public versus a private property in an object came quite some challenges ago, it would be very useful to insert the link back to the previous challenge when it was introduced first for reference. If I knew a bit more about github and git I would try to pull it down and add it myself.

Challenge [Make Object Properties Private](http://www.freecodecamp.com/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20var%20gear%20%3D%204%3B%0A%20%20%0A%20%20this.setGear%20%3D%20function%20(newGear)%7B%0A%20%20%20%20gear%20%3D%20newGear%3B%0A%20%20%7D%3B%0A%20%20%0A%20%20this.getGear%20%3D%20function()%20%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%20%20%0A%20%20%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
  var gear = 4;
  
  this.setGear = function (newGear){
    gear = newGear;
  };
  
  this.getGear = function() {
    return gear;
  };
  
  
};

var myCar = new Car();

var myBike = new Bike();

```

**Comment by raisedadead** [comment]
@theoneinskane Can you point me to the challenge where we used `this` first. Also I feel we should add a link to the [official MDN documentation](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/this).

**Comment by theoneinskane** [comment]
@raisedadead yes! It is: make-instances-of-objects-with-a-constructor-function challenge. I agree link to MDN would be very useful.

**Comment by theoneinskane** [comment]
@raisedadead when it gets the help wanted, does it mean we need some help to do the changes. I would love to try to do the update myself but I am still quite new and not sure how to do everything.

**Comment by raisedadead** [comment]
@theoneinskane You should definitely start by contributing to this one.
I understand that you are not very familiar with git and github, please [check this tutorial](https://try.github.io). This will get you started.

For contributing to this repo you need to go through the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

That's it.

And yup if you are stuck there is a dedicated [help chat room for contributors](https://gitter.im/FreeCodeCamp/HelpContributors), ping us there!

Goodluck!

**Comment by theoneinskane** [comment]
@raisedadead I haven't got the backend part yet and having just spent an hour trying to get node and mongoldb setup on my macbook without being able to get the node mongoldb drivers to install, I am not sure I will get to fixing this any time soon.

**Comment by raisedadead** [comment]
@theoneinskane No worries! Hope to see ya working on others if this one is taken by that time.

**Comment by 3521sdfdJJ** [comment]
new= phone (android-add)/mytelephone.168.000.nod
