### ISSUE TITLE
jQuery Challenge:Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by djaysingh30** [FreeCodeCamp/FreeCodeCamp#7283]
Use the $("button") selector.
Use the $(".btn") selector.
Use the $("#target1") selector.
Only add one class with each of your three selectors.
Your #target1 element should have the classes animated‚ shake and btn-primary.
Only use jQuery to add these classes to the element.

**Run test is not accepting the code**.

<script>
  $(document).ready(function() {
$("button").addClass("animated bounce");
    $(".btn").addClass("animated shake");
    $("#target1").addClass("btn-primary");
  });
</script>

**Comment by Coder9-75** [comment]
I am on this question. It gives instructions on what to add to #target1 but not what to add to button and btn. Any ideas so I can go to next ?

**Comment by Coder9-75** [comment]
I have found that this works, after looking for advice on the Internet 

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });
</script>

**Comment by techtolentino** [comment]
@Coder9-75 it says in the upper instructions:

```
Add the animated class to all elements with type button.

Add the shake class to all the buttons with class .btn.
```


Hope this helps. For future reference, please direct challenge related questions like this to the [FCC/Help Chat room](https://gitter.im/FreeCodeCamp/Help), instead of creating an issue. Tons of people are ready and willing to help you with this.

Again, hope it helps!


Thanks

**Comment by Coder9-75** [comment]
Thank you for the update. 
I feel that would have been better in the lower instructions with the ticks, showing you have done it right, then being in the upper instructions as you say. In other 'upper instructions' it just lets you know what you can do, then asks you to go ahead and perform those actions to somewhere else.
Kind Regards,


Date: Sat, 27 Feb 2016 06:28:01 -0800

**Comment by techtolentino** [comment]
We can close this.

**Comment by raisedadead** [comment]
Thanks @techtolentino .

Closing as resolved.

**Comment by djaysingh30** [comment]
please check before you post anything as resolved or working.
As the problem i was facing still persist.
Just go through the code i have posted and if u find anything wrong with it please do guide me that will help me not just saying this works for me and that works for me.
Thank you for your advises and comments.

**Comment by djaysingh30** [comment]
Issue resolved.

Please ignore the previous comments

**Comment by jowitaz** [comment]
With regards to @techtolentino comment on trying to get some help from the community:  I tried to join the room but I couldn't. I came here to report a bug but instead I've found a solution to a problem I had.  Thank you @Coder9-75

**Comment by ScottFrederickSchmidt** [comment]
Each inherit into each other so here is the code:

<script>
  $(document).ready(function() {
$("button").addClass("animated");
$(".btn").addClass("shake");
$("#target1").addClass("btn-primary");
  });
</script>
