### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by khawaja121** [FreeCodeCamp/FreeCodeCamp#7287]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by ltegman** [comment]
Issue contains no information. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need help and if you find out what you're seeing is truly a bug file a new issue with the template filled in with relevant information. Thanks and happy coding!
