### ISSUE TITLE
Smallest Common Multiple: my solution is wrong, but your site says it's correct

### ISSUE THREAD

**Issue by daryl-lin** [FreeCodeCamp/FreeCodeCamp#7292]
The test cases for this challenge only consist of ranges of [1, x].

It wasn't until after I'd successfully passed this challenge (using my code below) that I realized that my solution is incorrect for ranges that do not begin at 1 (eg. .. [7,9], [11, 13], etc.) .

Perhaps it might be a good idea to throw some other test cases in there.

```js
function smallestCommons(arr) {
    function isPrime(n) {
        var count = 1, sqrt = Math.floor(Math.sqrt(n));
    
        for (var i = 2; i <= sqrt; i++) {
            if (n % i === 0)
                break;
            else
                count++;
        }
        if (count === sqrt)
            return true;
    } 
    var max = arr.sort(function(a, b) {
        return a - b;
        })[1];
    var newArr = [1];
    var prod = newArr.reduce(function(a, b) {
            return a * b;
            });

    for (var i = 2; i <= max; i++) {
        if (isPrime(i)) {
            newArr.push(i);
            prod = newArr.reduce(function(a, b) {
                    return a * b;
                    });
        } else {
            if (prod % i !== 0) {
                for (var j = i - 1; j >= 2; j--) {
                    if (i % j === 0) {
                        newArr.push(i / j);
                        prod = newArr.reduce(function(a, b) {
                                return a * b;
                                });
                        break;
                    }
                }
            }
        }
    }
    return prod;
}
```

**Comment by negyvenketto** [comment]
+1

**Comment by erictleung** [comment]
It does seem weird that they all start at 1. @SaintPeter more tests? Or was there a reason to start them at one?

**Comment by SaintPeter** [comment]
I think that some which start at non-1 values would be fine.   I'm always hip for more tests if it improves the problem or causes it to be solved more completely.

**Comment by DanRom624** [comment]
I was going to write a similar comment, although my solution is correct anyway.
Indeed, the set of tests lack a case in which both values are grater than 1, such as [2,9].
Passing a similar test would guarantee a much more generic solution

**Comment by Rock-son** [comment]
There is also a problem of answer not being mathematically correct. The smallest common multiple of 1 and 5 is not 10, but 5. It's 1 * 5 and 5 * 1.

"We get a multiple of a number when we multiply it by another number. Such as multiplying by 1!, 2, 3, 4, 5, etc, but not zero." - [Smallest Common Multiple](https://www.mathsisfun.com/least-common-multiple.html)
