### ISSUE TITLE
Sean casey

### ISSUE THREAD

**Issue by odinTy** [FreeCodeCamp/FreeCodeCamp#7293]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System
  *Your Code 

```js
If relevant, paste all of your challenge code in here
```

**Comment by odinTy** [comment]
If relevant, paste all of your challenge code in here

**Comment by sludge256** [comment]
If there is an actual issue please edit your post to reflect that, then reopen the issue.
