### ISSUE TITLE
Local Scope and Functions

### ISSUE THREAD

**Issue by EllieAdam** [FreeCodeCamp/FreeCodeCamp#7294]
Challenge [Local Scope and Functions](http://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20var%20myVar%20%3D%2045%3B%0A%20%20%0A%7D%0AmyFunction()%3B%0A%0A%2F%2F%20run%20and%20check%20the%20console%20%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myFunction%0A%0A%0A%2F%2F%20now%20remove%20the%20console.log%20line%20to%20pass%20the%20test%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  var myVar = 45;
  
}
myFunction();

// run and check the console 
// myVar is not defined outside of myFunction


// now remove the console.log line to pass the test

```

**Comment by sludge256** [comment]
Try refreshing the page.

**Comment by EllieAdam** [comment]
I did 10 times :))

**Comment by sludge256** [comment]
The code you provided passes for me. Does closing your browser entirely then opening it again help?
