### ISSUE TITLE
our p element should contain the first few words of the provided additional..

### ISSUE THREAD

**Issue by essxiv** [FreeCodeCamp/FreeCodeCamp#7296]
```
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>kitty ipsum dolor</p>

```

Tried many different forms of:
Kitty Ipsum dolor
kitty ipsum dolor
kitty ipsum text
Kitty Ipsum text

Not letting me continue..

**Comment by alistermada** [comment]
Please read the instructions carefully:
> Create a second p element with the following kitty ipsum text: `Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched`.

One thing I want to note before this issue is closed. The test messages in this challenge have inconsistent format of the term "Kitty Ipsum text". 

In the first test message, it's just plain "Kitty Ipsum text". In the third test message, which this issue references, the term is in code format (`kitty ipsum text`). Might be a cause of confusion for users.

**Comment by AkiraLaine** [comment]
Closing this as it's not an issue. Please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) chat for help

**Comment by sludge256** [comment]
@alistermada I see what you mean. "...of the provided additional..." doesn't seem to quite make sense either. @FreeCodeCamp/issue-moderators should the test description be modified in regards to @alistermada 's observation? We can reopen this issue if so.

**Comment by SimchaCahn** [comment]
Agree with @sludge256

**Comment by anujsinghwd** [comment]
create a second p element with any kitty ipsum text and it works .

**Comment by KhalifKahin** [comment]
Your p element should contain the first few words of the provided additional kitty ipsum text.
![freecode camp](https://cloud.githubusercontent.com/assets/25877762/23101371/fd148712-f6a2-11e6-92ee-1419a87d347f.png)
please help me to fix that problem

**Comment by texas2010** [comment]
@KhalifKahin 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by bullojusaiganesh** [comment]
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched</p>  i can sole this error

**Comment by texas2010** [comment]
@bullojusaiganesh 
Please do not post your solution on here. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Ceeson** [comment]
just copy the text which color is red.

**Comment by raza2022** [comment]
**for all those who land here from googling**
here is the correct place to disscuss and solution as well :)
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-change-the-font-size-of-an-element/16777/4

**Comment by Anil1203** [comment]
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p style="font-size:16px;">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
