### ISSUE TITLE
Added the submit button as desired but still is not accepted

### ISSUE THREAD

**Issue by raju249** [FreeCodeCamp/freecodecamp#730]
![untitled](https://cloud.githubusercontent.com/assets/8307266/7876885/52feae96-05f0-11e5-9a71-70bbe0e688c1.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by QuincyLarson** [comment]
Thank you for pointing this out. I've fixed this.

**Comment by raju249** [comment]
Thanks Mate :)
