### ISSUE TITLE
unable to submit for sizing

### ISSUE THREAD

**Issue by irnw** [FreeCodeCamp/FreeCodeCamp#7300]
Challenge [Size your Images](http://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
   .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
i believe that I was correct in inserting the codes to size the image but was unable to submit the challenge. I tried to skip this challenge and did the next and realised that my codes were actually working on the next challenge.

**Comment by techtolentino** [comment]
In the code above, the img doesn't have the `.smaller-image` class, which it needs to have the `width: 100px;` applied to it.

So basically you have a css style not being applied.

Does that make sense?

**Comment by desireh** [comment]
I ran into this same problem. The instructions indicate that the class should be applied to the CSS style code not directly applied to the image tag.
