### ISSUE TITLE
Wiki doesn't contain all the articles in the repo

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7301]
Several articles that should show up on the wiki don't seem to do so yet.
![](https://www.evernote.com/l/Ar-8Tv7hPbtNQ5Z-5beEIGgq_72TAWKD9-IB/image.png)

**Comment by hallaathrad** [comment]
@SaintPeter RegEx mayhem?

**Comment by SaintPeter** [comment]
@hallaathrad Almost certainly.

**Comment by QuincyLarson** [comment]
@hallaathrad @SaintPeter so that's reasonably easy to fix, right? I think this is a high priority if one of you can dig into it.
