### ISSUE TITLE
Wiki drawer select box should be replaced with a ctrl+f'able listing of all wiki articles

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7302]
Yes, this list would be long, but it would be below the wiki article, and would enable people to use control+f (which many will want to do) in order to find specific content.

I think this would be a big improvement over the current select box interface. I've already talked with @hallaathrad and I believe he agrees. We just need to implement it.

**Comment by hallaathrad** [comment]
Alright, I'll take care of this one, then.

**Comment by QuincyLarson** [comment]
@hallaathrad what is the status on this?

**Comment by atjonathan** [comment]
This can be closed as we have implemented search functionality.
