### ISSUE TITLE
Show Wiki routes

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7303]
Currently the wiki does not update the address bar when a new article is visited. 

More importantly, you cannot jump to a specific wiki article from the URL alone. This makes it impossible to share links to wiki articles, and impossible for Google to index.

**Comment by hallaathrad** [comment]
I'd built that capability to detect the url in the address bar and display the article (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/6938), but closed it as it seemed nobody was interested in that feature.
We can reopen it ;)

**Comment by QuincyLarson** [comment]
@hallaathrad yes - please re-open it. We are definitely interested in that feature.
