### ISSUE TITLE
Title Case A Sentence arrives at the correct result but fails second test.

### ISSUE THREAD

**Issue by kennetpostigo** [FreeCodeCamp/FreeCodeCamp#7304]
Challenge [Title Case a Sentence](http://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20str%20%3D%20str.toLowerCase().split('%20')%3B%0A%20%20str%20%3D%20str.map(function%20(word)%20%7B%0A%20%20%20%20word%20%3D%20word.split('')%3B%0A%20%20%20%20word%20%3D%20word.map(function%20(letter)%20%7B%0A%20%20%20%20%20%20if%20(word.indexOf(letter)%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20return%20letter.toUpperCase()%3B%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20return%20letter%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B%0A%20%20%20%20return%20word.join('')%3B%0A%20%20%20%20%0A%20%20%7D)%3B%0A%20%20str%20%3D%20str.join('%20')%3B%0A%20%20console.log(str)%3B%0A%20%20return%20str%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  str = str.toLowerCase().split(' ');
  str = str.map(function (word) {
    word = word.split('');
    word = word.map(function (letter) {
      if (word.indexOf(letter) === 0) {
        return letter.toUpperCase(); 
      }
      else {
        return letter;
      }
    });
    return word.join('');
    
  });
  str = str.join(' ');
  console.log(str);
  return str;
}

titleCase("I'm a little tea pot");

```
My code result shows in the out put that it results in:
`"I'm A Little Tea Pot"` yet still fails the second test because it say that it doesn't equal that.
<img width="322" alt="screen shot 2016-02-28 at 3 24 16 am" src="https://cloud.githubusercontent.com/assets/8888991/13378208/dad38a00-ddca-11e5-81da-e356e66e4f87.png">

**Comment by alistermada** [comment]
Your output returns `"I'm A LittLe Tea Pot"`. Notice the second `L` in `LittLe` is capitalized when it shouldn't be.

If you're stuck on a challenge, please check out the [Help Chat](https://gitter.im/FreeCodeCamp/Help) first.

**Comment by sludge256** [comment]
Thanks for catching that @alistermada.
Please ask in the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) room if you need more assistance.

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
