### ISSUE TITLE
Without quotes within class tag challenge still works

### ISSUE THREAD

**Issue by stefanknapen** [FreeCodeCamp/FreeCodeCamp#7307]
Challenge [Create a Bootstrap Row](http://www.freecodecamp.com/challenges/create-a-bootstrap-row) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class=row>
  </div>
</div>
```

When I submit this challenge, it is successful, but I think there should be quotes ("") around "row", right? I think it should not work without this quotes. Possibly a bug?

**Comment by techtolentino** [comment]
Is this happening only with `class=row`, or are you noticing it with multiple classes?

**Comment by techtolentino** [comment]
I actually went back and tested this - this bug also happens in the next lesson as well: **Split your Bootstrap Row**

The challenge accepts this as an answer:

```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class=row>

    <div class=col-xs-6></div>
    <div class=col-xs-6></div>    
  </div>
</div>
```

It seems like the regex might possibly be only looking for the classes as strings, not accounting for the wrapping quotes.

I only tested the next lesson, but is this happening across all challenges?

Anyone else care to chime in?

**Comment by ltegman** [comment]
Most of our HTML/CSS tests are not done with regex but by looking for the given piece of HTML/CSS with jQuery. The reason this works is because it's perfectly valid HTML. Best practice is to include quotes all the time, but if there's no spaces in the thing you're assigning to that attribute they're actually not required. Thanks and happy coding!

**Comment by techtolentino** [comment]
Wow, i didn't know that! Thanks @ltegman!

**Comment by techtolentino** [comment]
Wow, i didn't know that! Thanks @ltegman!
