### ISSUE TITLE
Profile Lookup Challenge Possible solution not defined in test runner

### ISSUE THREAD

**Issue by dev6** [FreeCodeCamp/FreeCodeCamp#7308]
Hello folks,
Since this challenge is new, I found a solution with minimum loops to solve it but since the test coder hasn't included the console.log output to be included, my solution, doesn't pass through in all its tests. Here is the code:
```javascript
function lookUp(firstName, prop){
  for (var i = 0; i < contacts.length; i++) {
      if (contacts[i].firstName == firstName) {
          if (contacts[i].hasOwnProperty(prop)) {
            return contacts[i][prop];
          } else if (!contacts[i].hasOwnProperty(prop)) {
            return ("No such property");
          }
        } else {
          return ("No such contact");
     }
 }
```
In the last else loop, if the solution accepted console.log output, this code will pass the test. The return function in the last loop is now ending the for loop which is making the test run incomplete and unable to pass the challenge.
Here is the code which will pass this challenge if console.log output is also allowed in its test run.
```javascript
function lookUp(firstName, prop){
  for (var i = 0; i < contacts.length; i++) {
      if (contacts[i].firstName == firstName) {
          if (contacts[i].hasOwnProperty(prop)) {
            return contacts[i][prop];
          } else if (!contacts[i].hasOwnProperty(prop)) {
            return ("No such property");
          }
        } else {
          console.log ("No such contact");
     }
 }
```

Correct me if I am wrong.

**Comment by ltegman** [comment]
@dev6 If your solution can't work when you return the value then you need to rethink your solution. In the case of our test runner the output of your function is simply logged to the console for you to see, but in the real world `console.log` has very little value apart from logging server errors or writing command line tools. If your function simply `console.logs` the answer it can only be used by someone looking at the console. If it returns the answer it can be used by another piece of code.

Good luck and happy coding!

**Comment by sawsenchaabnia** [comment]
you should put "no such contact " as a default return of the function if nothing is executed in it.
for (var i=0; i< contacts.length; i++){
        
    if (firstName == contacts[i].firstName){
    
         if(contacts[i].hasOwnProperty(prop)){
      
         return contacts[i][prop];
         }else if (!contacts[i].hasOwnProperty(prop)) {
            return ("No such property");
          }
  
  }
  
// Only change code above this line
}
  return "No such contact";
}
