### ISSUE TITLE
WayPoint - Import A Google Font

### ISSUE THREAD

**Issue by kmcelveen** [FreeCodeCamp/freecodecamp#731]
Challenge http://www.freecodecamp.com/challenges/waypoint-import-a-google-font has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Allows you to pass the challenge if you input "Lobster" on the font-family attribute for h2 without making a call to google and inserting the link to the font. The following passes:

<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
  h2{
    font-family: Lobster
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
![screen shot 2015-05-28 at 10 47 00 pm](https://cloud.githubusercontent.com/assets/6963932/7877184/7be8e778-058b-11e5-9513-7ca833935f97.png)

**Comment by QuincyLarson** [comment]
Thank you for pointing this out. I've hardened the test suite on this one.
