### ISSUE TITLE
Add COM1000 + Screenshot to Contributing.md

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#7311]
We should have a link to and a screenshot of the Challenge-o-Matic 1000 (COM1000) in the `Contributing.md` guide.  Many new users do not know it exists and it can save them lots of time and improve the quality of submissions.

https://github.com/FreeCodeCamp/COM1000

**Comment by Kaos95** [comment]
Hi i'm a student have to do a project for university, where I join an open source project. I'm new to all this but I was wondering if I could do this and how?

**Comment by techtolentino** [comment]
@kaos95 if you haven't done so already, peel the [Contributing Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/README.md#contributing). There's great documentation on how to get started with helping.

Also, if you run into any issues, please check the [FCC/HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat team - people are always willing to help out.

**Comment by Kaos95** [comment]
Thanks for your help I'll check it out

**Comment by erictleung** [comment]
@SaintPeter any suggestions on where to host the screenshot? Maybe describe the process of getting COM1000 going within the `Contributing.md` document and then link to a longer article in the Wiki where you could keep the screenshot in the Wiki repo.

**Comment by SaintPeter** [comment]
@erictleung 
You could host it in the [COM Wiki](https://github.com/FreeCodeCamp/COM1000/wiki), maybe?

**Comment by erictleung** [comment]
@SaintPeter yeah, I could do that. They already have [mockup images](https://github.com/FreeCodeCamp/COM1000/blob/production/Challenge_Editor_Mockup.png) made in the repo too.

**Comment by QuincyLarson** [comment]
We haven't been using COM for curriculum development recently, so I'm closing this issue.
