### ISSUE TITLE
Pig Latin challenge in Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by nabilpro** [FreeCodeCamp/FreeCodeCamp#7313]
####  Description
the third example in the test is incorrect and it didn't let me pass it. translate(glove) should be "lovegay" and not "oveglay" as you put there.

#### my Code
function translate(str) {
  var result="";
  switch(str.charAt(0)){
      case 'a':
      case 'A':
      case 'o':
      case 'O':
      case 'i':
      case 'I':
      case 'e':
      case 'E':
      case 'U':
      case 'u': result= str.concat("way");
                break;
      default: result = str.slice(1).concat(str.charAt(0)).concat("ay");
                break;
      
  }
  return result;
}

translate("glove");

**Comment by ltegman** [comment]
> Pig Latin takes the first consonant (or consonant cluster) of an English word, moves it to the end of the word and suffixes an "ay".

`gl` is a consonant cluster. Thanks and happy coding!
