### ISSUE TITLE
Seek and Destroy

### ISSUE THREAD

**Issue by emoudy** [FreeCodeCamp/FreeCodeCamp#7317]
is destoyer([1, 2, 3, 1, 2, 3], 9, 7); missing brakets?  
(I changed the last two arguments to 9 and 7 so I could see what it was grabbing.  Using 1 and 2 was not clear.) 

for example: 
function destroyer(arr) {
  console.log(arr);
} 
// returns [1, 2, 3, 1, 2, 3]

To get the rest, I have to add more arguments: destroyer(arr, x, y)
console.log(arr);  //this returns [1, 2, 3, 1, 2, 3]
console.log(x);    //returns 9
console.log(y);    //returns 7

But if I add brakets: destoyer([[1, 2, 3, 1, 2, 3], 9, 7])  then I can grab everything
console.log(arr);  //returns [[1, 2, 3, 1, 2, 3], 9, 7]

Am I missing the concept or is this exercise missing brackets?  If so, could you point me in the right direction?

**Comment by sludge256** [comment]
There's a hint at the bottom of the instructions that link you to documentation about the [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments). Using it will allow you to grab the values after the first argument without having to add parameters to your function.

Try asking in [HelpJavaScript](gitter.im/FreeCodeCamp/HelpJavaScript) if you need more clarification. Good luck!

**Comment by Pi10tSec** [comment]
+1 on @sludge256

I made the mistake of thinking 'arr' was an array of all arguments.
