### ISSUE TITLE
Instructions and tests mismatch in "Understanding Uninitialized Variables" Challenge

### ISSUE THREAD

**Issue by maxplakhuta** [FreeCodeCamp/FreeCodeCamp#7318]
Hello,
I've noticed a tiny mistake in the "Understanding Uninitialized Variables" task.
There are two sets of variables are given in the task. One set is in the instructions block and the other one is under actual assignment. The assignment variables don't work though.
Sorry for disturbing J
Cheers,
Max

#### Screenshot
https://nimbus.everhelper.me/client/notes/share/407837/eh52zqirhouiknknifin

**Comment by raisedadead** [comment]
Thanks @maxplakhuta

For anyone looking into this check below:
![3](https://cloud.githubusercontent.com/assets/1884376/13412227/c16f4056-df67-11e5-800f-56a758e79cf1.PNG)

**Comment by raisedadead** [comment]
@maxplakhuta Ignore previous comment. This is correct behavior.
The value is incremented by the code in the editor window which is not supposed to be changed.

**Comment by sludge256** [comment]
(Issue was closed before I finished this message but I'll post it anyways)
The tests and the instructions are correct. You **initialize** the variables with the values in the instructions
```js
// Initialize these three variables
var a; //initial value should be assigned
var b; //initial value should be assigned
var c; //initial value should be assigned
```
Then the second block of code is run
```js
a = a + 1;
b = b + 5;
c = c + " String!";
```
which would modify the variable values to match what the tests expect.

**Comment by raisedadead** [comment]
@sludge realized it late. Hadn't noticed it in the editor area. Sorry my bad.
