### ISSUE TITLE
Change Text with Click Events - Test should also accept $('message').text('xxx').  Currently only accepts .html('xxx')

### ISSUE THREAD

**Issue by dougwells** [FreeCodeCamp/FreeCodeCamp#7319]
Challenge [Change Text with Click Events](http://www.freecodecamp.com/challenges/change-text-with-click-events#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%7B%0A%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%20%20%24(%22.message%22).html(%22Here%20is%20the%20message%22)%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("#getMessage").on("click", function(){
      // Only change code below this line.
      $(".message").html("Here is the message");
      
      // Only change code above this line.
    });
  });
</script>


<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
    </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

**Comment by KrisB1022** [comment]
@dougwells Can you further explain what the issues are? I tried the above code and it appears to work.

I'd also recommend using another browser (Chrome or Safari) over Firefox.

**Comment by dougwells** [comment]
Hi Kris,

My experience is that the code below is not accepted by the test engine.  Note, I am using .text() not the .html() that the test apparently prefers.  No biggie either way.  Just trying to help out as a member of the FCC community.  Thanks for you work helping to make FCC better with each passing month ...

Doug Wells

----

<script>
  $(document).ready(function() {
    $("#getMessage").on("click", function(){
      // Only change code below this line.
      
      $(".message").text("Here is the message");
      // Only change code above this line.
    });
  });
</script>

**Comment by dougwells** [comment]
<script>
  $(document).ready(function() {
    $("#getMessage").on("click", function(){
      // Only change code below this line.
      
      $(".message").text("Here is the message");
      // Only change code above this line.
    });
  });
</script>

**Comment by dougwells** [comment]
`<script>
  $(document).ready(function() {
    $("#getMessage").on("click", function(){
      // Only change code below this line.
      
      $(".message").text("Here is the message");
      // Only change code above this line.
    });
  });
</script>`

**Comment by dougwells** [comment]
`<script>
  $(document).ready(function() {
    $("#getMessage").on("click", function(){
      // Only change code below this line.
      
      $(".message").text("Here is the message");
      // Only change code above this line.
    });
  });
</script>`

**Comment by dougwells** [comment]
`<script>
  $(document).ready(function() {
    $("#getMessage").on("click", function(){
      // Only change code below this line.
      
      $(".message").text("Here is the message");
      // Only change code above this line.
    });
  });
`</script>``

**Comment by raisedadead** [comment]
@ltegman is this valid? AFAIK `.html()` is for HTML elements and `.text` is for both HTML and XML. So theoretically, `.text` should be allowed but is this a good practice?

**Comment by ltegman** [comment]
@raisedadead Yeah, either solution to this is valid. Since both work in HTML documents and we're not creating a child HTML element (which would require using `.html`) this should accept both methods.

**Comment by dougwells** [comment]
My guiding principle when using .html() vs .text() hinges on whether I need to include an HTML tag or not.  If I need to include "<li>Another line item</li> then I use .html().  If not, I use .text().  

In this challenge, I would actually argue that .text() is the "better" answer as no HTML tags are needed.

Just my opinion.  Fun to be involved in this positive discussion.  FCC is AWESOME!

**Comment by KrisB1022** [comment]
Here is the difference from jQuery's docs:

> .html() Get the **HTML contents of the first element** in the set of matched elements or set the HTML contents of every matched element.
>.text() Get the combined **text contents of each element** in the set of matched elements, including their descendants, or set the text contents of the matched elements.

More specifically:

- if you need to get/change the HTML tag and contents from an element, AND only need the **first one found**, use [.html()](http://api.jquery.com/html)
- if you need to get/change the **text** AND are okay with getting **all** decedents of the selector, use [.text()](http://api.jquery.com/text)

In this case, I would conclude that since only the text of the selector is being updated, .text() would be the correct answer; however, technically each should pass this test.
