### ISSUE TITLE
"0_0 (: /-\ :) 0-0" is not palindrome or otherwise we should also consider _ and - 

### ISSUE THREAD

**Issue by emattiazzi** [FreeCodeCamp/FreeCodeCamp#7321]
Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20sanitized%20%3D%20str.replace(%2F%5CW%2B%2Fgi%2C%20%22%22%20).toLowerCase()%3B%0A%20%20return%20sanitized%20%3D%3D%3D%20sanitized.split(%22%22).reverse().join(%22%22)%3B%0A%7D%0A%0A%0A%0Aconsole.log(palindrome(%220_0%20(%3A%20%2F-%5C%20%3A)%200-0%22))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var sanitized = str.replace(/\W+/gi, "" ).toLowerCase();
  return sanitized === sanitized.split("").reverse().join("");
}



console.log(palindrome("0_0 (: /-\ :) 0-0"));

```

**Comment by emattiazzi** [comment]
Ok, I should correct the code like this `\W|_`

**Comment by ShenZQ** [comment]
But this string contains a escape symbol--"\", this string actually just is "0_0 (:/-:) 0-0".
So, the bug is also exists.
