### ISSUE TITLE
Seek and Destroy

### ISSUE THREAD

**Issue by emoudy** [FreeCodeCamp/FreeCodeCamp#7322]
I'm getting different values for arguments[0] depending if I have it inside or outside function falsies().  Is this a bug or am I doing something wrong?

function destroyer(arr) { 
  console.log(arguments[0]);  //this returns [1, 2, 3, 1, 2, 3]
  
  function falsies (arr) {
      console.log(arguments[0]);  //this returns 1
  }
  return(arr.filter(falsies));
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

**Comment by ltegman** [comment]
This is not a bug. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) or [HelpJavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance. Thanks and happy coding!
