### ISSUE TITLE
Why does "friends" need to be an array.

### ISSUE THREAD

**Issue by DivaWeb** [FreeCodeCamp/FreeCodeCamp#7325]
Challenge [Build JavaScript Objects](http://www.freecodecamp.com/challenges/build-javascript-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"]
};

// Only change code below this line.

var myDog = {
  
  
  
  
};

```
 You explain how to make the array and then say only that the"friends" needs to be an array. Being a student trying to learn it would be helpful to know why it has to be an array so I know how to use it in the future.

**Comment by techtolentino** [comment]
Arrays are used for storing lists... So any time you have a list of anything, you would typically use an array.

Other examples of things to store in arrays:

- groceries
- classes
- books
- contacts
- etc...


Does that answer your question?

**Comment by DivaWeb** [comment]
ok so I only use an array in this instance if I have multiple items to list. Awesome thank you
