### ISSUE TITLE
Confirm the Ending

### ISSUE THREAD

**Issue by mohannadsawalhi** [FreeCodeCamp/FreeCodeCamp#7329]
Check if a string (first argument) ends with the given target string (second argument).

Remember to use Read-Search-Ask if you get stuck. Write your own code.? 

function end(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (str.indexOf(' ') > -1) {
    str = str.split(' ');
  }
  var lastVal = str[str.length - 1];

  return lastVal.indexOf(target) > -1;
  
  
}

end("He has to give me a new name","me");

------------------------------------------

end("He has to give me a new name", "na") should return false. ----> Error

**Comment by ltegman** [comment]
This is not a site bug. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) or [HelpJavascript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need challenge help. Thanks and happy coding!
