### ISSUE TITLE
Forgot block removal

### ISSUE THREAD

**Issue by jmorelandsbiz** [FreeCodeCamp/freecodecamp#733]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

In order for the buttons to go side-by-side, btn-block needs to be removed. The app doesn't enforce or list this requirement so the behavior doesn't work but the user can continue.

**Comment by QuincyLarson** [comment]
Actually, there is no need to remove the btn-block. The btn-block should remain. You can see this on the subsequent challenge where the buttons are lined up but still have btn-block classes. That said, this challenge does require additional test coverage to ensure campers succeed in actually lining the buttons up. Thanks for submitting this.
