### ISSUE TITLE
Add comma by default to JSON challenge

### ISSUE THREAD

**Issue by DivaWeb** [FreeCodeCamp/FreeCodeCamp#7333]
Challenge [Introducing JavaScript Object Notation JSON](http://www.freecodecamp.com/challenges/introducing-javascript-object-notation-json) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true,  
  },
  // Add record here
 {
    "artist":"Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [
      "CS",
      "8T",
      "LP"],
      "gold": true
    
 }
];


```
As a learning student I would have completed this on my own if the explanation of how to add a second record was done. The explanation does not include that you need a comma after the last curley brace in order to add a second record. I filled in the all the info and had it correct and the only thing that stopped me from completing it, was not knowing the format of adding a second record  includes adding a comma after the last curely braces.

**Comment by AkiraLaine** [comment]
The collection is an ```array``` which you have learned in previous challenges. So, in order to separate items, you know you should put a ```,```.

But the ```,``` should be there by default.

**Comment by M1kep** [comment]
@AkiraLaine so your saying it should be like.....
```js
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },
  // Add record here
];
```
instead of 
```js
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
];
```

**Comment by AkiraLaine** [comment]
Exactly.

**Comment by M1kep** [comment]
@AkiraLaine ok, sound good! Ill get on this then :P

**Comment by AkiraLaine** [comment]
Sorry everyone. @DivaWeb The challenge specifies that you need to add a comma.
>Note
You will need a comma in between objects in JSON objects with more than one object in the array
