### ISSUE TITLE
No response except "//testing challenge..."

### ISSUE THREAD

**Issue by SteveHiChae** [FreeCodeCamp/FreeCodeCamp#7340]
Challenge [Arguments Optional](http://www.freecodecamp.com/challenges/arguments-optional#?solution=function%20add()%20%7B%0A%20%20var%20args%20%3D%20(arguments.length%20%3D%3D%3D%201%20%3F%20%5Barguments%5B0%5D%5D%20%3A%20Array.apply(null%2C%20arguments))%0A%20%20%20%20%20%20.reduce(function%20(prev%2C%20curr)%20%7B%0A%09%20%20%20%20return%20(%20typeof%20prev%20!%3D%3D%20'number'%20%7C%7C%0A%09%09%20%20%20%20%20%20%20%20%20typeof%20curr%20!%3D%3D%20'number'%20%3F%20undefined%20%3A%20prev%20%2B%20curr%20)%3B%0A%20%20%20%20%20%20%7D%2C%200)%3B%0A%20%0A%20%20if%20(arguments.length%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20return%20function%20(x)%20%7B%0A%20%20%20%20%20%20return%20(%20(%20typeof%20args%20!%3D%3D%20'number'%20%7C%7C%20typeof%20x%20!%3D%3D%20'number'%20)%20%3F%20undefined%20%3A%20args%20%2B%20x%20)%3B%20%0A%20%20%20%20%7D%3B%0A%20%20%7D%0A%20%20return%20args%3B%0A%7D%0A%0A%2F*add(2%2C%203)%3B%0Aadd(2)(3)%3B%20*%2F%0Aadd(%22http%3A%2F%2Fbit.ly%2FIqT6zt%22)%3B%0A%2F*add(2%2C%20%223%22)%3B%0Aadd(2)(%5B3%5D)%3B*%2F) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**When I  ran my code, I got only "// testing challenge...".**

My code:
```javascript
function add() {
  var args = (arguments.length === 1 ? [arguments[0]] : Array.apply(null, arguments))
      .reduce(function (prev, curr) {
	    return ( typeof prev !== 'number' ||
		         typeof curr !== 'number' ? undefined : prev + curr );
      }, 0);
 
  if (arguments.length === 1) {
    return function (x) {
      return ( ( typeof args !== 'number' || typeof x !== 'number' ) ? undefined : args + x ); 
    };
  }
  return args;
}

/*add(2, 3);
add(2)(3); */
add("http://bit.ly/IqT6zt");
/*add(2, "3");
add(2)([3]);*/
```

**Comment by raisedadead** [comment]
@SteveHiChae 

The challenge has been recently updated to use a function name `addTogether` instead off `add`
I have tested this with the below snippet (taking your logic):

```js
function addTogether() {
  var args = (arguments.length === 1 ? [arguments[0]] : Array.apply(null, arguments))
      .reduce(function (prev, curr) {
        return ( typeof prev !== 'number' ||
                 typeof curr !== 'number' ? undefined : prev + curr );
      }, 0);

  if (arguments.length === 1) {
    return function (x) {
      return ( ( typeof args !== 'number' || typeof x !== 'number' ) ? undefined : args + x ); 
    };
  }
  return args;
}

addTogether(2,3);
```

This lets me pass the test cases properly except for the `bit.ly` test case. Well that could be a logical error with the provided logic, not sure, but I'll let you figure that out.

Please confirm and close if this is expected. I believe the original issue that you report is resolved.
Thanks and happy coding!

**Comment by alistermada** [comment]
@raisedadead 

If you put `addTogether("http://bit.ly/IqT6zt");` on the bottom of the code, it'll give you an error in the console:

![image](https://cloud.githubusercontent.com/assets/12993334/14586072/16cb36d6-04b6-11e6-92ea-6c3f6588de05.png)

This may have something to do with the fact that `addTogether("http://bit.ly/IqT6zt");` returns a function instead of `undefined`.

**Comment by raisedadead** [comment]
@alistermada Thanks for checking this, the "test freeze" is directly related to the solution/logic implemented by the camper. IMHO, its not related to the challenge itself having a issue, correct?

And I can confirm with your analysis that the addTogether is indeed returning a function as opposed to `undefined` in case of a string as argument.

Refer :
`console.log(typeof addTogether(2, 3));` **<--** Output: _number_
`console.log(typeof addTogether("Hello World"));` **<--** Output: _function_

@SteveHiChae Closing this with the above comments, please feel free to continue the discussion if you still need any assistance with this.
