### ISSUE TITLE
Challenge [Falsy Bouncer] has an issue

### ISSUE THREAD

**Issue by vinodindia** [FreeCodeCamp/FreeCodeCamp#7341]
Challenge [Falsy Bouncer] has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
My code:
```javascript     
         function bouncer(arr) {
         // Don't show a false ID to this bouncer.
         var arr2 = [];
         for(i=0;i<arr.length;i++){
          if(arr[i]!=false||null || 0 || ""|| undefined || NaN)
         arr2.push(arr[i]);
         if(arr[i]==null && isNaN(arr[i])==true)
         arr2=[];
         }
         return arr2;
         }
         bouncer([7, "ate", "", false, 9, NaN]);]
```

My above code has been passed the test cases but it should not pass the test please check and improve test cases

**Comment by lsxliron** [comment]
I think you have a problem in 
```javascript 
if(arr[i]==null && isNaN(arr[i])==true)
```

I am not sure if an element can be `null` and `NaN` at the same time.

```javascript
> var x = null
undefined
> console.log(x)
null
> x == null
true
> isNaN(x)
false
```

Maybe you meant to this?
```javascript
if(arr[i]==null || isNaN(arr[i])==true)```

**Comment by JoshFisk** [comment]
@lsxliron That modification leaves it more broken then the original. The op is not asking for help with the program, he is simply stating that it is passing the tests when it should not be.

**Comment by vinodindia** [comment]
@lsxliron   as @JoshFisk  said I know that my submitted code has some issues but the point is my code should not pass the test, but it did..!! 

and I really appreciate the freecodecamp team for their time and effort for running this awesome service.

**Comment by sd23152243** [comment]
why this issue hase closed, I have met the same issue, how to solve? Thx all the time
