### ISSUE TITLE
Challenge freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side class="btn-block" is redundant

### ISSUE THREAD

**Issue by jastuccio** [FreeCodeCamp/FreeCodeCamp#7344]
"Put the Like, Info and Delete buttons side-by-side by nesting all three of them within one `<div class="row">` element, then each of them within a `<div class="col-xs-4">` element"

I think the Bootstrap markup "btn-block" from the previous exercise is redundant.  The buttons are supposed to be side by side in this exercise using the column grid.

I suggest part of the exercise is to remove the "btn-block" class form each button and tests be written to ensure they are removed.  I would like some feedback about this suggestion before submitting a pull request.

**Comment by techtolentino** [comment]
@jastuccio I'm not sure if `btn-block` would ensure that they're side-by-side though. From what I can tell, `btn-block` is intended to have that button take up the full-width of the parent.

So, having 3 buttons with the `btn-block` class would mean, 3 wide buttons, vertically stacked - not side-by-side.

**Comment by ltegman** [comment]
@techtolentino Is correct that `btn-block` ensure they are the same width as the parent. You can see that the look with and without `btn-block` is very different.
__with__
![use_the_bootstrap_grid_to_put_elements_side_by_side___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/13482633/4321bf02-e0a3-11e5-978a-f71283ce84c1.png)
__without__
![use_the_bootstrap_grid_to_put_elements_side_by_side___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/13482638/4ee049d0-e0a3-11e5-8ec3-5a24bae160b3.png)
Thanks and happy coding!

**Comment by jastuccio** [comment]
Thank you @itegman.  I was confused thinking `btn-block` made the button full screen width instead of full parent width.  The image makes it crystal clear.
