### ISSUE TITLE
Link Account to Reddit, Enable "Thanks" and "Upvote" Detection on Reddit

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#7345]
One of the features of the now deprecated Camper News was receiving brownie points from upvotes.  Additionally, users who help out on help chat can get brownie points from "Thank You" messages.  It should be possible to enable the same features on Reddit.

## FCC Side
There would need to be two changes to FCC:
### Link Reddit Account to FCC
The Reddit API has Oauth support:  https://github.com/reddit/reddit/wiki/OAuth2
There also exists a passport.js plugin for the Reddit API: https://github.com/Slotos/passport-reddit
All that would be required is that the plugin be installed and the UI be wired up to accept Reddit as an authentication source.

Unlike Facebook/LinkedIn, Reddit links should not be visible on user's account pages and we should let users know this clearly.  Very few people want their Reddit account publicly linked to their real identity.

### Reddit Username API for Brownie Points
There would need to be an FCC API endpoint that accepted Reddit usernames for brownie point awards, similar to the existing one that CamperBot uses.   It would need to return "Not Found" errors.

## Reddit CamperBot
We would need a stand alone Reddit Bot for the next two steps.  There are several frameworks for Reddit bots, in particular [MARS](https://github.com/PixelOrange/MARS) looks good.

### "Thanks" Detection
There are several bots that detect certain types of "thanks" equivilents and award Reddit specific flair, etc.  A MARS base is used for the [DeltaBot](https://www.reddit.com/r/DeltaBot/) used on [/r/ChangeMyView](https://www.reddit.com/r/changemyview).  It detects a specific delta symbol and awards the author of the parent post a "delta".  We can simply rewire this to detect "Thanks" or equivilent and award brownie points via the FCC API mentioned above.

We should allow "Thanks" from non-FCC users, but can obviously only award them to FCC users.  An error message would need to have a link to the "Link my Reddit Account to FCC".

### Upvote Detection
I have not dived too deeply into the [Reddit API](https://www.reddit.com/dev/api), but it seems that it should be possible to extract the votes/score of a given link from that API.  Some database would be needed to retain a "current score" for a given post so an actual delta could be measured and determined.  

I would propose that only external links, not "self" links be awarded points.

**Comment by BerkeleyTrue** [comment]
Add more OAuths is definitely something we need to discuss thoroughly. A large percentage of our support tickets are related to us having so many and users confusing which one is already linked to their account.

**Comment by SaintPeter** [comment]
I'm not necessarily proposing that we enable Reddit as an Oauth provider for logging in purposes, but more to link their Reddit account with their FCC account.  

I don't know if our current structure allows for that.
