### ISSUE TITLE
Profile page not showing correct streak count

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/FreeCodeCamp#7346]
This isn't terribly important, but I noticed that the "current streak" on my portfolio page isn't showing the correct number. As of today, my streak should be 19 days, but it is listed as just one. Seems like it might be an issue with the default time zone (?), though it never had a problem before.

http://www.freecodecamp.com/wildlifehexagon

**Comment by rishipuri** [comment]
Your streak seems right. It is 1 day. From what I see, there was nothing on 29th Feb which restarted your streak count.

**Comment by wildlifehexagon** [comment]
I completed a video challenge yesterday, and it shows up as one item on my profile page. Not sure how you are seeing something different...?

**Comment by JoshFisk** [comment]
@wildlifehexagon It might be displaying the calendar in local time, but counting the streak by server time. I agree that it is frustrating if you are using the streak count to keep you motivated.

**Comment by wildlifehexagon** [comment]
@JoshFisk What's weird is that this wasn't a problem before. It's making me think that it was a change made recently (perhaps inadvertently?).

**Comment by raisedadead** [comment]
@wildlifehexagon Are you still facing this?
Can you refer #7468 as well as a know issue for now.

Please feel free to continue your discussion there.

**Comment by olcaysarmaz** [comment]
It looks like I am still having this issue. My calendar shows 30 items on August 30, but not the list of item below. Current streak shows just 1 instead of 7.

![image](https://cloud.githubusercontent.com/assets/8172966/18115779/04c304ae-6f10-11e6-8582-ce94a2e4ab20.png)
