### ISSUE TITLE
Make a Person: trials not visible in left pane

### ISSUE THREAD

**Issue by DavidWeedmark** [FreeCodeCamp/FreeCodeCamp#7347]
Whenever I open the trial, nothing appears below the black output field on the left so I can't see the trials. Refreshing Chrome, logging out and in, clearing cache, and trying MSEdge didn't help.

(NB: I got a temporary fix by pasting someone else's solution and clicking "Run Tests". which made the trials visible with checkmarks. so at least now I can see what I need to do for this one.
However, when I run my own code, the checkmarks remain so I can't see which are working and which are not.)

Challenge [Make a Person](http://www.freecodecamp.com/challenges/make-a-person) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Person = function(firstAndLast) {
    return firstAndLast;
};

var bob = new Person('Bob Ross');
bob.getFullName();

```

**Comment by ltegman** [comment]
Your code is crashing JavaScript execution because it's calling a function that doesn't exist. Remove the call to `bob.getFullName();` until you've written that function and you won't run into any problems with the tests not running. Thanks and happy coding!

**Comment by DavidWeedmark** [comment]
ah but that's not my code. 
it reappears whenever I reset

**Comment by ltegman** [comment]
@DavidWeedmark Could you please post what your code is and any errors you might be getting in either the FCC console on the left hand side and in your browser's error console?

**Comment by DavidWeedmark** [comment]
After clicking reset, and when I first opened the challenge earlier today, the output is
TypeError: bob.getFullName is not a function

The Code is: 
var Person = function(firstAndLast) {
    return firstAndLast;
};

var bob = new Person('Bob Ross');
bob.getFullName();

However, if I delete that last line (the function) and click Run Tests, the output window is empty.

**Comment by ltegman** [comment]
My advice still stands -- that last line where you call the function that doesn't exist is the problem. Once you've written that function you can add it back in. You see nothing in the console when you remove it because your code doesn't currently output anything that could be printed to the console.

**Comment by DavidWeedmark** [comment]
I understand and I'm able to work on it by removing that line. If this isn't happening to anyone else, please don't worry about it. and thank you!
