### ISSUE TITLE
Inaccurate instructions. Tells me to remove all non-AlphaNumeric Characters

### ISSUE THREAD

**Issue by AndrewMcSwain** [FreeCodeCamp/FreeCodeCamp#7348]
The text says to remove all non-AlphaNumeric Characters, but the final criteria on the list is comparing the order of non-AlphaNumeric Characters. If I follow the rules I remove the symbols from the string before the reversal and comparison is made. 

Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20var%20stringVar%20%3D%20str.toLowerCase()%3B%0A%20%20var%20stringLength%20%3D%20str.length%3B%20%0A%20%20var%20alphaNumericArray%20%3D%20%5B%5D%3B%0A%20%20%2F%2Fpush%20letters%20to%20array%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20stringLength%3B%20i%2B%2B)%7B%0A%20%20%20var%20alphaNumericChar%20%20%3D%20stringVar.charAt(i)%3B%0A%20%20%20var%20alphaNumericIndex%20%3D%20i%3B%0A%20%20%20var%20isLetter%20%3D%20%2F%5Cw%2F.test(alphaNumericChar)%3B%0A%20%20%20%2F%2Fvar%20isNumber%20%3D%20%2F%5Cd%2F.test(alphaNumericChar)%3B%0A%20%20%20if%20(isLetter%20%3D%3D%3D%20true%20%2F*%26%26%20isNumber%20%3D%3D%3D%20false*%2F%20%26%26%20alphaNumericChar%20!%3D%3D%20%22%20%22)%0A%20%20%20%20%20alphaNumericArray.push(alphaNumericChar)%3B%0A%20%20%7D%0A%20%20%0A%20%20var%20alphaNumericString%20%3D%20alphaNumericArray.join(%27%27)%3B%0A%20%20%2F%2Freverse%20array%20and%20stringify%0A%20%20var%20reverseAlphaNumericArray%20%3D%20alphaNumericArray.reverse()%3B%0A%20%20var%20reverseAlphaNumericString%20%3D%20reverseAlphaNumericArray.join(%27%27)%3B%0A%20%20var%20returnArray%20%3D%20%5BreverseAlphaNumericString%2C%20alphaNumericString%5D%3B%0A%20%20if(returnArray%5B0%5D%20!%3D%3D%20returnArray%5B1%5D)return%20false%3B%0A%20%20else%20return%20true%3B%0A%20%20%20%20%0A%7D%0A%0A%0A%0Apalindrome(%221%20eye%20for%20of%201%20eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  var stringVar = str.toLowerCase();
  var stringLength = str.length; 
  var alphaNumericArray = [];
  //push letters to array
  for (var i = 0; i < stringLength; i++){
   var alphaNumericChar  = stringVar.charAt(i);
   var alphaNumericIndex = i;
   var isLetter = /\w/.test(alphaNumericChar);
   //var isNumber = /\d/.test(alphaNumericChar);
   if (isLetter === true /*&& isNumber === false*/ && alphaNumericChar !== " ")
     alphaNumericArray.push(alphaNumericChar);
  }
  
  var alphaNumericString = alphaNumericArray.join('');
  //reverse array and stringify
  var reverseAlphaNumericArray = alphaNumericArray.reverse();
  var reverseAlphaNumericString = reverseAlphaNumericArray.join('');
  var returnArray = [reverseAlphaNumericString, alphaNumericString];
  if(returnArray[0] !== returnArray[1])return false;
  else return true;
    
}



palindrome("1 eye for of 1 eye");

```

**Comment by ltegman** [comment]
That's the goal of the final test. It looks like something that shouldn't be a palindrome, but if you're removing all alphanumeric it is one. Thanks and happy coding!

**Comment by sludge256** [comment]
You haven't removed all all non-alphanumeric characters yet.

**Comment by knifejuggler** [comment]
I'm confused by this one too. It says that 'palindrome("1 eye for of 1 eye.") should return false.' Why? The stripped version becomes eyeforofeye which IS a palindrome, so why should it return false?
