### ISSUE TITLE
Request Header Parser Microservice challenge only available in Spanish

### ISSUE THREAD

**Issue by aceting91** [FreeCodeCamp/FreeCodeCamp#7349]
For some reason the [Request Header Parser](http://www.freecodecamp.com/challenges/request-header-parser-microservice) challenge is in Spanish only. 

The [cached version ](http://webcache.googleusercontent.com/search?q=cache:aaATsQUjgcoJ:www.freecodecamp.com/challenges/request-header-parser-microservice+&cd=5&hl=en&ct=clnk&gl=ca)of the challenge is still in English though.

![screen shot 2016-03-01 at 5 41 30 pm](https://cloud.githubusercontent.com/assets/16042593/13444570/0fa0c3a4-dfd5-11e5-91c2-3ea1a8ee3d25.png)

**Comment by ltegman** [comment]
Good catch. Looks like the Spanish translation ended up with the same key in the JSON as the English description, so it grabbed the last one (the Spanish one). I've got a PR in to fix this now :smile:
