### ISSUE TITLE
Article listing Issue Moderator has a broken link

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#7352]
The first link on [this article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-GitHub-Issue-Moderators-AKA-Issue-Mods-Work) is broken. It needs to be updated properly.

**Comment by AkiraLaine** [comment]
@alayek Which link specifically? ```Issue Moderators Team Page```?

**Comment by techtolentino** [comment]
@AkiraLaine I think it _is_ the `Issue Moderators Team Page` that's broken.

I also got a 404.


<img width="781" alt="screen shot 2016-03-02 at 5 00 37 am" src="https://cloud.githubusercontent.com/assets/6276074/13458607/d63e37a4-e033-11e5-94cb-b71fb182a64a.png">

**Comment by AkiraLaine** [comment]
@techtolentino As I said, it's not broken for me.
![2016-03-02](https://cloud.githubusercontent.com/assets/11958359/13458741/329f6cf4-e0c3-11e5-9fb0-c0bd2709de14.png)

**Comment by techtolentino** [comment]
Hmm... that is strange

**Comment by AkiraLaine** [comment]
Same browser: Version 48.0.2564.116 m
Windows 10.

**Comment by techtolentino** [comment]
I'm curious if it works for you because you're a member of the org?

**Comment by alistermada** [comment]
I'm guessing the visibility of teams on FCC's GitHub account is [set to secret](https://help.github.com/enterprise/2.5/user/articles/changing-team-settings/).

@AkiraLaine Try accessing the [issue moderators page](https://github.com/orgs/FreeCodeCamp/teams/issue-moderators) while logged out. Do you get a 404 error?

**Comment by AkiraLaine** [comment]
I can't. Need to log in

**Comment by alistermada** [comment]
I guess @techtolentino's right. Only FCC team members and owners can access the page. Kinda pointless to have the link there on the wiki if nobody else can access it.

**Comment by alayek** [comment]
Alright I can close this issue in that case.

**Comment by techtolentino** [comment]
So, was the resolution to make the page public? Or to remove the link?

**Comment by alistermada** [comment]
@alayek I think this issue should remain open. There should be something done about a link that most people can't access.on a public wiki.

**Comment by alayek** [comment]
Ok reopening...

**Comment by raisedadead** [comment]
@BerkeleyTrue This one is for you to tackle!

**Comment by BerkeleyTrue** [comment]
All teams are already set to visible

**Comment by raisedadead** [comment]
Umm that's strange, I just created an account @dont-raisedadead, he cant access it! Any suggestions?

**Comment by techtolentino** [comment]
I say just remove the link if it's supposed to be private.

**Comment by JoshFisk** [comment]
Maybe you could link to this instead?
https://github.com/orgs/FreeCodeCamp/people

**Comment by techtolentino** [comment]
@joshfisk true, but some members on the `people` page aren't on the `issue Moderators` team (i.e., Berkeley, Quincy)
