### ISSUE TITLE
Test check myTest(51) repeated twice

### ISSUE THREAD

**Issue by cgand** [FreeCodeCamp/FreeCodeCamp#7353]
#### Browser Information
* Safari 9.0.3
* Mac OS X 10.1.3

#### Screenshot
http://cl.ly/0j151r3b0B3H

-----
Updated Description:

[Comparisons with the Logical And Operator](http://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator) has an issue.

A test cases appears repeated. Haven't checked if these are just the messages or actually the entire test is repeated, either a case should be fixed or extra one should be removed.

Refer Screenshot below:
![image](https://cloud.githubusercontent.com/assets/1884376/13459614/e9537608-e09a-11e5-86fe-98129088ae29.png)

**Comment by techtolentino** [comment]
What challenge are you referring to @cgand ?

**Comment by alistermada** [comment]
@techtolentino Looks like [Comparisons with the Logical And Operator](http://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator)

**Comment by cgand** [comment]
> Il giorno 02 mar 2016, alle ore 12:22, Alister Najib Mada <notifications@github.com> ha scritto:
> 
> @techtolentino Looks like Comparisons with the Logical And Operator
> 

Yes, right, is it.
C.

Inviato da iPad

**Comment by techtolentino** [comment]
I'm willing to go in and fix this if someone from FCC can confirm this should be fixed.
