### ISSUE TITLE
Map the debris

### ISSUE THREAD

**Issue by nitiblack** [FreeCodeCamp/FreeCodeCamp#7357]
Challenge [Map the Debris](http://www.freecodecamp.com/challenges/map-the-debris#?solution=function%20orbitalPeriod(arr)%20%7B%0A%20%20var%20GM%20%3D%20398600.4418%3B%0A%20%20var%20earthRadius%20%3D%206367.4447%3B%0A%20%20return%20arr%3B%0A%7D%0A%0AorbitalPeriod(%5B%7Bname%20%3A%20%22sputnik%22%2C%20avgAlt%20%3A%2035873.5553%7D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function orbitalPeriod(arr) {
  var GM = 398600.4418;
  var earthRadius = 6367.4447;
  return arr;
}

orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]);

```

What to fix here 
orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]) should return [{name: "sputnik", orbitalPeriod: 86400}].
orbitalPeriod([{name: "iss", avgAlt: 413.6}, {name: "hubble", avgAlt: 556.7}, {name: "moon", avgAlt: 378632.553}]) should return [{name : "iss", orbitalPeriod: 5557}, {name: "hubble", orbitalPeriod: 5734}, {name: "moon", orbitalPeriod: 2377399}]

**Comment by ltegman** [comment]
Please stop filing issues for things that are not bugs.

Visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help or a second set of eyes to confirm if something is a bug. If someone confirms what you're seeing is a bug please make sure your issue has a detailed description of the problem and steps to reproduce the problem.

Thanks and happy coding!
