### ISSUE TITLE
Getting all correct solutions, but challenge isn't accepted

### ISSUE THREAD

**Issue by Valcaloc** [FreeCodeCamp/FreeCodeCamp#7359]
I've tried a number of strategies, but am not able to get this challenge accepted. Thanks for looking at this issue.  Val

Challenge [Return Largest Numbers in Arrays](http://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=var%20arrNew%20%3D%20%5B%5D%3B%0Avar%20arr%20%3D%20%5B%5D%3B%0A%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20%20%0A%20%20for%20(var%20i%3D0%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20var%20largest%20%3D%200%3B%0A%20%20%20%20for%20(var%20j%3D0%3B%20j%20%3C%20arr.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(arr%5Bi%5D%5Bj%5D%20%3E%3D%20largest)%20%7B%0A%20%20%20%20%20%20%20%20largest%20%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20arrNew.push(largest)%3B%0A%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20arr%20%3D%20arrNew%3B%0A%0A%20return%20arr%3B%20%20%20%0A%20%20%7D%0A%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arrNew = [];
var arr = [];

function largestOfFour(arr) {
  // You can do this!
   
  for (var i=0; i < arr.length; i++) {
    var largest = 0;
    for (var j=0; j < arr.length; j++) {
      if (arr[i][j] >= largest) {
        largest = arr[i][j];
      }
    }
  arrNew.push(largest);
     
    }
   arr = arrNew;

 return arr;   
  }

largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]);

```

**Comment by ltegman** [comment]
Global variables are bad news. Think about what your code does if that function is run twice (or just give it a try and see what it does). Thanks and happy coding!

**Comment by Valcaloc** [comment]
Thanks so much, Logan! I'm still trying to figure out what determines if
the solution is accepted or not. So this was definitely helpful.

Val
