### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements

### ISSUE THREAD

**Issue by dreathe** [FreeCodeCamp/freecodecamp#736]
Seems to be a issue completing this exercise. Even though the code is correct the exercise doesnt let me finish keeps saying the line bellow:

You need to specify a border width of 10px and a border style of "solid".

  .thick-green-border{
    border-width: 10px;
    border-style: solid;
    border-color: green;       
  }

img class='smaller-image  thick-green-border'  img src has been omited just for display porpose

I have even done

border:10px solid green;

doesnt let me finish even if the display is correct.

**Comment by QuincyLarson** [comment]
Thank you for pointing out this huge bug. I've fixed it.
