### ISSUE TITLE
Receiving supports

### ISSUE THREAD

**Issue by Francolpm** [FreeCodeCamp/FreeCodeCamp#7360]
Hi there!
Sorry about this question, I don't trying to spam you, but are you accepting donations or supports?
Because I want to give some of money to FreeCodeCamp as a project, but there is no donate button o something like that.
Also, I want to invite you to beerpay.io, a simple platform to monetize open source projects, like FreeCodeCamp.

Thanks for this work!

**Comment by ltegman** [comment]
Free Code Camp has made a conscious decision not to accept purely monetary donations at this time. If you'd like to send money our way you can purchase any items that are offered in the [shop](http://www.freecodecamp.com/shop). We do not allow advertisements on our Github issues so I have edited out that part of your message. Thanks and happy coding!

**Comment by Francolpm** [comment]
👍 Great @ltegman! 

I'm going to take a look in the shop! 

Cheers!
