### ISSUE TITLE
cant get blue  style blue

### ISSUE THREAD

**Issue by MsMarChe** [FreeCodeCamp/FreeCodeCamp#7363]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by ltegman** [comment]
Issue has no problem description. It looks like you're having a problem solving this challenge, so I'd advise you visit the Gitter Chat for help. If they confirm you're seeing a bug please open a new issue where you fill in the template with the required information. Thanks and happy coding!

**Comment by MsMarChe** [comment]
thanks
