### ISSUE TITLE
Completed Caesars Cipher algorithm passing and moving me backwards to an earlier waypoint

### ISSUE THREAD

**Issue by matthew3454** [FreeCodeCamp/FreeCodeCamp#7364]
#### Issue Description
 I am returned back to the Waypoint: Trigger Click Events with jQuery when I try to move to the next activity. I tried resetting by browser cache with no avail.
* Steps To Reproduce
I punch Ctrl/Enter twice

#### Browser Information
Google Chrome
64 Bit Operating System

#### Your Code

```js
function rot13(str) {
  var answer = [];
  for (var i in str) {
    if (str.charCodeAt(i) < 65 || str.charCodeAt(i) > 91) {
      answer.push(str[i]);
      continue;
    } else {
      if (str.charCodeAt(i) < 78) {
        answer.push(String.fromCharCode(str.charCodeAt(i) + 13));
        continue;
      } else {
        answer.push(String.fromCharCode(str.charCodeAt(i) - 13));
        continue;
      }
    }
  }
  return answer.join("");
}
```

**Comment by ltegman** [comment]
That is the next challenge after Caesar's Cipher on the map, so that's expected.
![trigger_click_events_with_jquery___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/13482242/8d18ff42-e0a0-11e5-8a6b-2536ef4bb7f3.png)
Thanks and happy coding!
