### ISSUE TITLE
Challenge [Introducing Else Statements] 

### ISSUE THREAD

**Issue by W0der** [FreeCodeCamp/FreeCodeCamp#7365]
Challenge [Introducing Else Statements](http://www.freecodecamp.com/challenges/introducing-else-statements#?solution=function%20myTest(val)

Within the example solution, the return statements are missing equal signs:
if (num > 10) {
 return "Bigger than 10";
} else {
 return "10 or Less";
}

Would love to help in fixing this if I could.  Thanks

**Comment by techtolentino** [comment]
I actually think the example is correct. Say we have 11, since it is greater than 10, it'll return "Bigger than 10"

If num = 10, however , it should return "10 or less"

**Comment by alvin-odins** [comment]
what is wrong with this part of introducing else ?


function testElse(val) {
  var result = "";
  // Only change code below this line
  
  if (val > 5) {
    result = "Bigger than 5";
  } else {
    result = "5 or smaller";
  }
  
  
  // Only change code above this line
  return result;
}

// Change this value to test
testElse(4);

**Comment by alvin-odins** [comment]
fixed. thanks. was my mistake
