### ISSUE TITLE
Make a Person: no definition of "arity"

### ISSUE THREAD

**Issue by edward-hong** [FreeCodeCamp/FreeCodeCamp#7366]
It's strange that the description for this exercise says "All functions that take an argument have an **arity **of 1, and the argument will be a string.", when it's simpler just to say something like "All functions that take arguments, take one argument that is a string". Also I feel that the word "arity" is an outdated word after googling the word and finding out that it used to be a property of functions but is now [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arity)

**Comment by ltegman** [comment]
You're right -- that is an incredibly obscure word for anyone without a background in mathematics and not consistent with the wording used by other challenges. This should definitely be changed.

**Comment by eeseesee** [comment]
Looks like a good issue for a first PR! I can work on this if no one has claimed it yet.

**Comment by ltegman** [comment]
@eeseesee Go for it :+1:

**Comment by eeseesee** [comment]
@vtamara I changed the challenge description, but did not update the Spanish version.

**Comment by vtamara** [comment]
@eeseesee, see that @justinian336 suggested a translation as comment to the PR, please adopt it as I suggest in another comment of the PR.

**Comment by srinjay** [comment]
@eeseesee  could you tell me where is the code?

**Comment by vtamara** [comment]
See https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7380/files
