### ISSUE TITLE
Make Object Properties Private 

### ISSUE THREAD

**Issue by mmarinm** [FreeCodeCamp/FreeCodeCamp#7368]
Ok Guys I am getting good values when I am testing code but I don't get it why it doesn't work

Challenge [Make Object Properties Private](http://www.freecodecamp.com/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20var%20%20gear%20%3D%201%3B%0A%20%20this.getGear%20%3D%20function()%20%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%20%20%0A%20%20this.setGear%20%3D%20function(value)%20%7B%0A%20%20%20%20gear%20%3D%20gear%20*%20value%3B%0A%20%20%20%20this.getGear()%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0AmyBike.setGear(1)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
  var  gear = 1;
  this.getGear = function() {
    return gear;
  };
  
  this.setGear = function(value) {
    gear = gear * value;
    this.getGear();
  };
};

var myCar = new Car();

var myBike = new Bike();
myBike.setGear(1);
```

**Comment by ltegman** [comment]
Check what happens if you call `setGear` twice. Your code is not working correctly. Next time please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to confirm what you're seeing is actually a bug before filing a Github issue. Thanks and happy coding!
