### ISSUE TITLE
Change Text with Click Events - I think the explanatory text in incorrect?

### ISSUE THREAD

**Issue by khaduch** [FreeCodeCamp/FreeCodeCamp#7369]
Challenge [Change Text with Click Events](http://www.freecodecamp.com/challenges/change-text-with-click-events) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**I do not think that there is a problem with the code**  I do think that the text 

> When our click event happens, we can use Ajax to update an HTML element.

should say "jQuery" instead of "Ajax"?

Thanks!
Ken

My code:
```html
<script>
  $(document).ready(function() {
    $("#getMessage").on("click", function(){
      // Only change code below this line.
      $('.message').html('Here is the message');
      // Only change code above this line.
    });
  });
</script>


<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
    </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

**Comment by ltegman** [comment]
Good catch -- there is definitely no Ajax going on there!

**Comment by techtolentino** [comment]
I can work on this :)

**Comment by ltegman** [comment]
@techtolentino Go for it! :+1:
