### ISSUE TITLE
copy-and-paste error.

### ISSUE THREAD

**Issue by jmorelandsbiz** [FreeCodeCamp/freecodecamp#737]
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This text for the steps looks like a copy-and-paste error. The second set src looks off: 
Wrap your image element inside an anchor element that has its href attribute set to "#".to.equal(1);
 Make sure to specify the "src" attribute as "#".to.be.true;

**Comment by QuincyLarson** [comment]
I've now fixed this. Thank you for pointing it out.
