### ISSUE TITLE
Golf Code strokes === par

### ISSUE THREAD

**Issue by HaiderJaan** [FreeCodeCamp/FreeCodeCamp#7373]
Challenge [Golf Code](http://www.freecodecamp.com/challenges/golf-code#?solution=function%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(strokes%20%3D%3D%3D%201)%20%7B%0A%20%20%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%20%20%0A%20%20%7D%20else%20if%20(strokes%3C%3D(par-2))%20%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%20else%20if%20(strokes%3D%3D(par%20-%201))%20%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3D%3D%3D%20par)%20%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22par%22%3B%0A%20%20%7D%20else%20if%20(strokes%3D%3D(par%20%2B%201))%20%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%3D%3D(par%20%2B%202))%20%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%3E%3D%20(par%20%2B%203))%20%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22Go%20Home!%22%3B%0A%20%20%7D%20%0A%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function golfScore(par, strokes) {
  // Only change code below this line
  
  if (strokes === 1) {
  
    return "Hole-in-one!";
    
  } else if (strokes<=(par-2)) {
    
    return "Eagle";
  } else if (strokes==(par - 1)) {
    
    return "Birdie";
  } else if (strokes === par) {
    
    return "par";
  } else if (strokes==(par + 1)) {
    
    return "Bogey";
  } else if (strokes==(par + 2)) {
    
    return "Double Bogey";
  } else if (strokes>= (par + 3)) {
    
    return "Go Home!";
  } 
 
  
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

```

**Comment by JoshFisk** [comment]
You need to return "Par", instead of "par".

**Comment by ltegman** [comment]
@HaiderJaan Github issues are not for challenge help. Please confirm what you're seeing is a bug by visiting the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) before filing a Github issue. Thanks and happy coding!
