### ISSUE TITLE
Returning Boolean Values from Functions

### ISSUE THREAD

**Issue by HaiderJaan** [FreeCodeCamp/FreeCodeCamp#7374]
Challenge [Returning Boolean Values from Functions](http://www.freecodecamp.com/challenges/returning-boolean-values-from-functions#?solution=function%20isLess(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Fix%20this%20code%0A%20%20switch%20(a%2Cb)%20%7B%0A%20%20%20%20case%20a%3Cb%20%3A%20%7B%20%20%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%20%7D%0A%20%20%0A%20%20%20%20%20%20%20%0A%20%20%7D%0A%7D%0A%2F%2F%20Change%20these%20values%20to%20test%0AisLess(10%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function isLess(a, b) {
  // Fix this code
  switch (a,b) {
    case a<b : {  
      return true;
      }
  
       
  }
}
// Change these values to test
isLess(10, 15);

```

**Comment by ltegman** [comment]
Issue does not describe a problem. If you need help please visit the Gitter Chat and if they say what you're seeing is a bug file a Github issue with more detail. Thanks and happy coding!

**Comment by NadaH** [comment]
the answer:
function isLess(a, b) {
  // Fix this code
 return a<b;
      }

**Comment by kalel2319** [comment]
the answer:
function isLess(a, b) {
// Fix this code
return a<b;
}

That is what I typed and it doesn't pass the challenge.

**Comment by roaringrussian** [comment]
This is the answer that I got and it passed.
function isLess(a, b) {
  // Fix this code
  return a <= b;
}
// Change these values to test
isLess(10, 15);

**Comment by fisnikp** [comment]
Here is Solution:

function isLess(a, b) {
// Fix this code
return a < b;
}


// Change these values to test
isLess(10, 15);

**Comment by texas2010** [comment]
@fisnikp 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Shahadot-shr** [comment]
>>>>right answer<<<



function isLess(a, b) {
  // Fix this code
 return a <= b;
}

// Change these values to test
isLess(10, 15);

**Comment by texas2010** [comment]
@Shahadot-shr 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Shahadot-shr** [comment]
okkkay!
