### ISSUE TITLE
FreeCodeCamp's Make a Person 

### ISSUE THREAD

**Issue by kenshinman** [FreeCodeCamp/FreeCodeCamp#7375]
Challenge [Make a Person](http://www.freecodecamp.com/challenges/make-a-person#?solution=var%20Person%20%3D%20function(firstAndLast)%20%7B%0A%0A%20%20var%20fullName%20%3D%20firstAndLast%3B%0A%20%20var%20arr%20%3D%20fullName.split(%27%20%27)%3B%0A%0A%20%20this.getFirstName%20%3D%20function()%20%7B%0A%20%20%20%20return%20arr%5B0%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.getLastName%20%3D%20function()%20%7B%0A%20%20%20%20return%20arr%5B1%5D%3B%0A%20%20%7D%3B%0A%0A%20%20this.getFullName%20%3D%20function()%20%7B%0A%20%20%20%20return%20fullName%3B%0A%20%20%7D%3B%0A%0A%20%20this.setFirstName%20%3D%20function(first)%20%7B%0A%20%20%20%20arr%5B0%5D%20%3D%20first%3B%0A%20%20%7D%3B%0A%0A%20%20this.setLastName%20%3D%20function(last)%20%7B%0A%20%20%20%20arr%5B1%5D%20%3D%20last%3B%0A%20%20%7D%3B%0A%0A%20%20this.setFullName%20%3D%20function(firstAndLast)%20%7B%0A%20%20%20%20fullName%20%3D%20firstAndLast%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person(%27Bob%20Ross%27)%3B%0Abob.getFullName()%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Person = function(firstAndLast) {

  var fullName = firstAndLast;
  var arr = fullName.split(' ');

  this.getFirstName = function() {
    return arr[0];
  };

  this.getLastName = function() {
    return arr[1];
  };

  this.getFullName = function() {
    return fullName;
  };

  this.setFirstName = function(first) {
    arr[0] = first;
  };

  this.setLastName = function(last) {
    arr[1] = last;
  };

  this.setFullName = function(firstAndLast) {
    fullName = firstAndLast;
  };
};

var bob = new Person('Bob Ross');
bob.getFullName();
```
This code works perfectly well on my local IDE and in my browser, it returns

**Comment by techtolentino** [comment]
What does it return?

**Comment by ltegman** [comment]
Your code does not return the correct answer if you try doing what the failing test cases are doing. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help. Thanks and happy coding!
