### ISSUE TITLE
I don't think the instructions are clear enough

### ISSUE THREAD

**Issue by talderman** [FreeCodeCamp/FreeCodeCamp#7376]
Challenge [Accessing Objects Properties with Variables](http://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas",
};

// Only change code below this line;

var playerNumber ;       // Change this Line
var player = testObj[16];    // Change this Line

```

**Comment by ltegman** [comment]
Please let us know _what_ about the description you think is unclear and any suggestions you might have for what would make it clearer.

**Comment by talderman** [comment]
It seemed that the solution wants the property name from the bracket notation. Which I don't think is easily done. It wasn't clear to me to just assigning 16 to then to pass playerNumber into the bracket for the testObj. Maybe it was due to the variable in the example was above the object.  Perhaps it is just me trying to over complicate the problem. Feel free to close the issue.
