### ISSUE TITLE
I Think my code should work as it passes in the console log, but it does not pass the test?

### ISSUE THREAD

**Issue by Mason-Rojik** [FreeCodeCamp/FreeCodeCamp#7381]
Challenge [Mutations](http://www.freecodecamp.com/challenges/mutations#?solution=function%20mutation(arr)%20%7B%0A%20%20var%20word0%20%3D%20arr%5B0%5D.toString().toLowerCase()%3B%0A%20%20var%20word1%20%3D%20arr%5B1%5D.toString().toLowerCase()%3B%0A%20%20var%20newArr%20%3D%20word1.split(%22%22)%3B%0A%20%20var%20result%3B%0A%20%20%20%0A%20%20for(i%20%3D%200%3B%20i%20%3C%20word1.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(word0.indexOf(newArr%5Bi%5D)%20%3D%3D%3D%20-1)%7B%0A%20%20%20%20%20%20result%20%3D%20%22false%22%3B%20%0A%20%20%20%20%20%20%7Bbreak%3B%7D%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20%20%20result%20%3D%22true%22%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%7D%20%20%0A%20%20return%20result%3B%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22neo%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function mutation(arr) {
  var word0 = arr[0].toString().toLowerCase();
  var word1 = arr[1].toString().toLowerCase();
  var newArr = word1.split("");
  var result;
   
  for(i = 0; i < word1.length; i++){
    if(word0.indexOf(newArr[i]) === -1){
      result = "false"; 
      {break;}        
       }else{
        result ="true";
       }
  }  
  return result;
}

mutation(["hello", "neo"]);

```

**Comment by ltegman** [comment]
`false` and `"false"` are not the same thing in JavaScript. In the future please check with the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to be sure what you're seeing is a bug before filing a Github issue. Thanks and happy coding!

**Comment by MajideB** [comment]
Thanks

**Comment by Mason-Rojik** [comment]
Thanks ... I tried gitter first and I got no response. but that fixed it!
