### ISSUE TITLE
Profile lookup says Sherlock, likes is wrong even though it outputs correct answer

### ISSUE THREAD

**Issue by TheMorkDaddy** [FreeCodeCamp/FreeCodeCamp#7383]
Challenge [Profile Lookup](http://www.freecodecamp.com/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intruiging%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%2C%0A%5D%3B%0A%0A%0Afunction%20lookUp(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20%20%0A%0A%20%20var%20propexists%20%3D%20false%3B%0A%20%20var%20i%2Cj%2Cnameexists%3Dfalse%3B%0A%20%20for(i%3D0%3Bi%3Ccontacts.length%3Bi%2B%2B)%7B%0A%20%20%20%20if(contacts%5Bi%5D%5Bprop%5D)%7B%0A%20%20%20%20%20%20propexists%20%3D%20true%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20if(propexists)%7B%0A%20%20%20%20for(j%3D0%3Bj%3Ccontacts.length%3Bj%2B%2B)%7B%0A%20%20%20%20%20%20if(contacts%5Bj%5D.firstName%20%3D%3D%20firstName)%7B%0A%20%20%20%20%20%20%20%20nameexists%3Dtrue%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20if(nameexists)%7B%0A%20%20%20%20%20%20return%20contacts%5Bj%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%0A%20%20%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%7D%0A%20%20else%0A%20%20%20%20return%20%22No%20such%20property%22%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp(%22Sherlock%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intruiging Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    },
];


function lookUp(firstName, prop){
// Only change code below this line
    

  var propexists = false;
  var i,j,nameexists=false;
  for(i=0;i<contacts.length;i++){
    if(contacts[i][prop]){
      propexists = true;
      break;
    }
  }
  if(propexists){
    for(j=0;j<contacts.length;j++){
      if(contacts[j].firstName == firstName){
        nameexists=true;
        break;
      }
    }
    if(nameexists){
      return contacts[j][prop];
    }
    else
      return "No such contact";
  }
  else
    return "No such property";

// Only change code above this line
}

// Change these values to test your function
lookUp("Sherlock", "likes");

```

**Comment by TheMorkDaddy** [comment]
[http://mikemorkes.com/codepen/sherlock.jpg](url)

**Comment by AkiraLaine** [comment]
You changed this line:
```"likes": ["Intruiging Cases", "Violin"]``` 

Copy your function code, reset the editor and paste in your code.

**Comment by meatballcoder** [comment]
I received no errors with this below and explicitly used Sherlock, likes:

```
 for (var outer = 0; outer < contacts.length; outer++){
    if (contacts[outer].firstName === firstName){
       if (contacts[outer].hasOwnProperty(prop)){
          return contacts[outer][prop]; 
       }
      else {
        return "No such property";
      }
    }
  }
  return "No such contact";
// Only change code above this line
}
```

**Comment by hemantknayak** [comment]
thanks this helped...
