### ISSUE TITLE
I'm at 100% browser zoom with the correct code and still unable to submit

### ISSUE THREAD

**Issue by srasmussen86** [FreeCodeCamp/FreeCodeCamp#7386]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
*I am at 100% web browser zoom using google chrome and it says my code is correct but will not allow me to submit 
![screen shot 2016-03-03 at 8 29 00 pm](https://cloud.githubusercontent.com/assets/16784658/13518063/afc5898c-e17e-11e5-8420-1989a5c1ac03.png)

* Steps To Reproduce

#### Browser Information
* Google Chrome
* Mac OsX

#### Your Code
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
   
    .smaller-image {
    width: 100px;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
    
  }
</style>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```js
If relevant, paste all of your challenge code in here
```

**Comment by nateinaction** [comment]
Take a look at the the code editor. Do you see the red boxes in the <style> section around ".smaller-image" That's the editor telling you that there is an error in your code. In this case you are missing a closing bracket after your h2 style.

`h2 { font-family: Lobster, Monospace;} .smaller-image { width: 100px; }`

In the future, please post questions about your code in the [https://gitter.im/FreeCodeCamp/CodeReview](codereview chat).
