### ISSUE TITLE
class not working

### ISSUE THREAD

**Issue by Axande** [FreeCodeCamp/freecodecamp#739]
I don't know why my class doesn't work. Thank you!
![bug](https://cloud.githubusercontent.com/assets/11229423/7882264/97dba126-0614-11e5-8c9d-274692188aac.png)

**Comment by matejhegedus** [comment]
It should be
```
.smaller-image {
    width: 100px;
}
```
Notice ':' instead of '='.

**Comment by terakilobyte** [comment]
Please remember these issue tickets aren't for help with challenges but are meant to report an actual issue. You can join our Slack chat for syntax help.
