### ISSUE TITLE
Infinite Loop in Screen Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by luarca84** [FreeCodeCamp/FreeCodeCamp#7390]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
When i access to my page I cant change the code because the screen is Frozen

#### Browser Information
Chrome
Windows 10

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by luarca84** [comment]
Finally I could change my code pressing Supr when the page was loading.

**Comment by ltegman** [comment]
If you run into this problem again you can [Disable Code Auto-Run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run). Thanks and happy coding!
