### ISSUE TITLE
Reference Array.find() instead of Array.filter() for the Challenge [Finders Keepers]

### ISSUE THREAD

**Issue by vicneanschi** [FreeCodeCamp/FreeCodeCamp#7391]
Challenge [Finders Keepers](http://www.freecodecamp.com/challenges/finders-keepers) references misleading Array.filter(). It should be replaced with Array.find()

Similar issues #1350 wasn't resolved.

**Comment by ltegman** [comment]
Good call, that would definitely be a better fit.

**Comment by BerkeleyTrue** [comment]
Array.prototype.find may not be available in all browsers

**Comment by ltegman** [comment]
I was wondering why I hadn't heard of this array method before. Don't know why I didn't think of it being ES6. We're holding off on including ES6 in the curriculum at the moment, so I'm going to close this. Thanks and happy coding!
