### ISSUE TITLE
Record Collection: passing challenge, even when failing to push track to undefined array

### ISSUE THREAD

**Issue by tstelzer** [FreeCodeCamp/FreeCodeCamp#7394]
The challenge fails to check for pushing a track to an undefined `tracks` array.
Relevant code:
```js
  else if (prop === "tracks") {
    collection[id].tracks.push(value);
  }
```
It throws the following error:
```
TypeError: Cannot read property 'push' of undefined
```
Yet, I passed the challenge.
Note: I just want to point out this behaviour, I know what the problem is and fixed it in my code to properly push to the array.
In case any newbie like myself is wondering, I fixed it by checking if `tracks` exists before pushing. 
```
  else if (prop === "tracks") {
    if (collection[id].hasOwnProperty("tracks")) {
      collection[id].tracks.push(value);
    }
    else {
      collection[id].tracks = [];
      collection[id].tracks.push(value);
    }
  }
```

**Comment by demipixel** [comment]
Would you mind adding a pastebin to your full code so it's easy to test? :)

**Comment by Zeit-Werk** [comment]
http://pastebin.com/KWyCvgCS

Pastebin with faulty code.

**Comment by demipixel** [comment]
[Using that code](http://i.imgur.com/oxM6S8v.png)

**Comment by Zeit-Werk** [comment]
Try this one: http://pastebin.com/kbbX7PFy

I think I deleted the wrong line ...

**Comment by alistermada** [comment]
I think this challenge should either have:
* a `tracks` array added to last object in the collection for the sake of consistency

or

* an additional test and instructions to deal with a missing `tracks` array.

**Comment by erictleung** [comment]
It doesn't seem too outlandish to add a test to check for adding to an empty array and it does make the challenge more complete.

> After `updateRecords(5439, "tracks", "Take a Chance on Me")`, `tracks` should have `"Take a Chance on Me"`
