### ISSUE TITLE
This challenge accepts only with the shortened bit.ly link, but not with the original long one

### ISSUE THREAD

**Issue by artiomjar** [FreeCodeCamp/FreeCodeCamp#7397]
Challenge [Add Images to your Website](http://www.freecodecamp.com/challenges/add-images-to-your-website) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
To reproduce this issue, replace the https://bit.ly/fcc-relaxing-cat with the https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg
My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>
<h2 class="red-text">CatPhotoApp</h2>
<img src="https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg">
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment]
This is expected since the challenge asks you to use the shortened link. Thanks and happy coding!
