### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue 

### ISSUE THREAD

**Issue by strawstack** [FreeCodeCamp/freecodecamp#740]
assert.strictEqual(convert('Dolce & Gabbana'), 'Dolce & Gabbana', 'should escape characters');should escape characters: expected 'Dolce & Gabbana' to equal 'Dolce & Gabbana'

I got the above failed test. My answer is identical to the correct answer. This question needs some examples; it's really hard to figure out what is required.

**Comment by strawstack** [comment]
I have written "&amp" instead of "&amp;"

**Comment by arecvlohe** [comment]
How was this resolved?

**Comment by strawstack** [comment]
When I converted "&" to the HTML entity, I was using "&amp" instead of "&amp;" (I forgot the semicolon) my output text string looked correct, however the test was failing as the answer was not deeply equal.

**Comment by strawstack** [comment]
&amp/;

**Comment by strawstack** [comment]
&amp\;

**Comment by arecvlohe** [comment]
Here is what I wrote. I am using the number entity instead of the short name. From my point of view it should work.

     return str.replace(/[&<>'"]/gim, function(entity) {
         return '&#'+ entity.charCodeAt(0)+';';
       });

The test returns: `should escape characters: expected 'Dolce & Gabbana' to equal 'Dolce & Gabbana'`

Console returns:  `"Dolce &#38; Gabbana"`

**Comment by strawstack** [comment]
I think you're right. It seems the test is just checking for <b>&amp;amp;</b>. You may know of the file in the repo called [basic-bonfires.json](https://github.com/FreeCodeCamp/freecodecamp/blob/master/seed_data/challenges/basic-bonfires.json). 

The offending test in that file is written as follows:

```javascript
"tests": [
    "assert.strictEqual(convert('Dolce & Gabbana'), 'Dolce &amp; Gabbana', 'should escape characters');",
    "assert.strictEqual(convert('abc'), 'abc', 'should handle strings with nothing to escape');"
],
```

**Comment by arecvlohe** [comment]
I see. They should modify this. But I will try and change it in the mean time. Thanks strawstack.
