### ISSUE TITLE
Get Set for our Back End Development Projects - create simpler version for API Projects

### ISSUE THREAD

**Issue by jondcoleman** [FreeCodeCamp/FreeCodeCamp#7401]
I think Clementine is a wonderful starting place for the Full Stack Apps but many users are finding it to be unnecessary and unhelpful for the API projects.  They are getting tripped up on things like authentication and MVC patterns, which aren't necessary for the API Projects.

Therefore, I'd like to suggest that the Clementine generator instructions are moved to a new step preceding the Full Stack projects.  For the API Projects, either create a different boilerplate or provide none at all.

**Comment by jondcoleman** [comment]
Maybe something like this

- Create a directory named for whatever your project is (e.g. time-server-api)
- Run `npm init` in the console and follow the prompts to set up your package.json file (most things you can leave as default)
- Run `npm install express --save` to insall express.js and save it as a dependency for your project.
- Add a .gitignore file to your directory which ignores the node_modules folder
- Run `git init` to initialize this as a git repository
- Create a file in your directory called `server.js`
- For the API projects you can write all your code in this file.  For a starting place I recommend this as a simple example of node/express set up: http://expressjs.com/en/starter/hello-world.html

**Comment by supergoat** [comment]
I was very confused on how to start after the Clementine tutorial, so jondcoleman's suggestion helped out a lot, so I think it would be useful if you included something like this before Clementine. Thumbs up :+1:

**Comment by dshgna** [comment]
+1

Additionally, I didn't find Clementine.js a good starting point for the dynamic web projects. Its directory structure is heavily based on Angular. As we are supposed to develop the frontend component with React, a React specific version would be much more useful.

**Comment by patricksevat** [comment]
I agree with this as well. I got very confused when first encountering Clementine for API projects due to unknown components (Passport and Mongoose). I ended up stripping pretty much everything and working from server.js

**Comment by delbertlegg** [comment]
+1 I was trying to figure out where I was going wrong before I was pointed in the direction of "modularization" which hadn't yet been really covered. Once I realized I could run the program in the server file, I was squared away. Not necessary to use Clementine.

**Comment by erictleung** [comment]
cc/ @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
I am in favor. But lets hear it from others.

**Comment by theflametrooper** [comment]
I agree with @raisedadead, I am also in favor :+1:

**Comment by ltegman** [comment]
I completely agree. By that point in the curriculum students should be familiar with Express and that is the only thing needed to start cracking on those projects.

**Comment by jondcoleman** [comment]
I'm going to give this a go.

**Comment by raisedadead** [comment]
Bumping up for comments.
/to @BerkeleyTrue @QuincyLarson and /cc @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
@raisedadead, I think it's a good idea to move... However, HyperDev is still limited in options, where as c9 is a full linux box.

**Comment by jondcoleman** [comment]
IMO c9 makes more sense to teach with but I see the advantage of HyperDev.

**Comment by QuincyLarson** [comment]
For the API challenges, we could definitely consider HyperDev. It is much, much easier to get started with, and replaces both c9.io (to a large extent) and Heroku (which requires a credit card and excludes a LOT of campers).

If we are going to move away from using Clementine.js anyway (which I agree is too heavy for the API challenges), I vote we move to HyperDev. 

We can link to wiki articles that show campers how to use c9.io/Heroku, or dev locally. But HyperDev seems to be a sane default for all of the back end challenges.

@jondcoleman thank you for taking the initiative to submit the PR. What do you think about hyperdev?

**Comment by jondcoleman** [comment]
Thanks @QuincyLarson 

I feel torn about HyperDev - the abstraction certainly makes it easier.  There are a few disadvantages to HyperDev in my mind:

- Loss of true git workflow.  You can export your project to github but there's no individual commits or standard workflow.
- Non-standard ways of adding libraries.  For example, users might get tripped up by the fact that there is no `npm install x --save` when most guides out there will describe that as the way to install a package.
- Lack of ability to use task runners (gulp, webpack, etc).  This wouldn't be a big deal for the API projects but for the dynamic web apps this would be a pain.
- Lack of ability to use generators or boilerplates not specifically designed for HyperDev.  Because of the forced project structure this seems be an issue.
- HyperDev is still in Beta so who knows what issues campers might run into.

My opinion would be to stay with c9 for the dynamic apps.  For API projects I would lean towards sticking with c9 but think it's less of an obstacle there.

**Comment by raisedadead** [comment]
@jondcoleman thanks a lot for this research, and you are absolutely right, we should not be moving to something, that needs no standard ways of doing stuff. This would confuse beginners, which ironically is the opening post in this thread.

Let's just stick to removing the ClementineJS part and simplify the instructions as suited best with C9.

Thanks a lot, once again.

**Comment by steelman80** [comment]
Pleas i need someones help, i dont know how to link my git hub with my FCC

**Comment by raisedadead** [comment]
@steelman80 please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).
