### ISSUE TITLE
tooltip on example code doesnt match to data.. fix: need to add time to Date creation

### ISSUE THREAD

**Issue by moigithub** [FreeCodeCamp/FreeCodeCamp#7403]
Challenge [Visualize Data with a Bar Chart](http://www.freecodecamp.com/challenges/visualize-data-with-a-bar-chart) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

hello... found a small bug on code.. tooltip

```
"from_date":` "1947-01-01",
...
  "data": [
    [
      "1947-01-01",
      243.1
    ],
```
when u mouseover on the first bar (left side) it says "December 1946"
and according to the data... doesnt match
had same bug on my code.. 
..u probably doing `new Date(  "1947-01-01" )` which give "Dec 1946" (didnt saw ur code, but that was what i did)
solution is adding the time on the Date creation
`new Date(  "1947-01-01T20:00:00.000Z" )`

**Comment by mutantspore** [comment]
Yes, I noticed and fixed this quite awhile ago on my version of the Pen. The FCC version of it needs to be updated.

http://codepen.io/MutantSpore/full/pgyrwB/

**Comment by Junicus** [comment]
another solution could be achieved by using the d3 library

'var parseDate = d3.time.format('%Y-%m-%d').parse;`

With that you get a function that will parse the date provided
http://codepen.io/Junicus/pen/yOgxjr

**Comment by erictleung** [comment]
@raisedadead are you able to change the code pen to fix this?

**Comment by mutantspore** [comment]
Again, I have fixed the original some months ago ... BUT I have no way of updating the Free code camp  forked version.

This simply needs someone with the "power" to fork this as update the example link.

http://codepen.io/MutantSpore/full/pgyrwB/

**Comment by raisedadead** [comment]
Thanks again @mutantspore !
But I believe I this is fixed already. 

Thanks @erictleung for pointing out that this issue is open here. 
Can you check and confirm if it works? Because its working on my end.

Refer comments on #7700

**Comment by erictleung** [comment]
@raisedadead there's nothing inherently broken with the visualization but the tooltip is still a bit off. 

![image](https://cloud.githubusercontent.com/assets/2754821/14664542/dac9731a-0680-11e6-8810-d0f62045acb4.png)

The earliest data point should be January 1946, not December 1946.

![image](https://cloud.githubusercontent.com/assets/2754821/14664508/84d330d6-0680-11e6-8c95-2d81c6dd77df.png)

**Comment by raisedadead** [comment]
@mutantspore I'll copy your pen's code to FCC version. I am feel you would not mind? It would be faster and easier than forking and updating the challenge link.

Thanks and let me know if that's okay.

**Comment by mutantspore** [comment]
Yes, go ahead though I have no idea if I changed anything other than the JS. :)

**Comment by raisedadead** [comment]
Closing as resolved!
