### ISSUE TITLE
Increment not functioning

### ISSUE THREAD

**Issue by rwils83** [FreeCodeCamp/FreeCodeCamp#7406]
Challenge [Increment a Number with Javascript](http://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%20%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar ++;


```

**Comment by ltegman** [comment]
This is not a bug with the site, but a bug with your code. Please read the instructions carefully and visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) next time to confirm what you're seeing is actually a bug. Thanks and happy coding!
