### ISSUE TITLE
Your h2 element should have the text "CatPhotoApp". 

### ISSUE THREAD

**Issue by Cipto1001** [FreeCodeCamp/FreeCodeCamp#7407]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by ltegman** [comment]
Issue does not describe a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) to have someone confirm that this is a bug with the site and not your code and then file a bug that is filled in with the relevant information if they confirm that it is. Thanks and happy coding!
