### ISSUE TITLE
"translate/" branch prefix

### ISSUE THREAD

**Issue by regonn** [FreeCodeCamp/FreeCodeCamp#7409]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7408

I received a note from bot.

Do we need a "translate/" branch prefix?

**Comment by ltegman** [comment]
Yes, we need to add some more accepted options. I know @bugron was working on fixing this. Any update on this, @bugron?

**Comment by MajideB** [comment]
ایرانی بنویسید 


ارسال شده از دستگاه سامسونگ من

-------- پیام اصلی --------
از: Kenta Tanoue <notifications@github.com> 
تاریخ: ۲۰۱۶/۳/۵  ۱۰:۵۰  (GMT+03:30) 
گیرنده: FreeCodeCamp/FreeCodeCamp <FreeCodeCamp@noreply.github.com> 
موضوع: [FreeCodeCamp] "translate/" branch prefix (#7409) 

#7408

I received a note from bot.

Do we need a "translate/" branch prefix?

**Comment by bugron** [comment]
I have even more prefixes in my local bot. Whitelisted prefixes are `new/`, `add/`, `audit/`, `translate/`. @ltegman once all those prefixes are in guidelines I'll add them to the bot. We need the bot to behave according to our contribution guidelines. But even if I do that it won't be live until we setup the new bot with @BerkeleyTrue.

**Comment by BerkeleyTrue** [comment]
@bugron Latest version crashes.
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/13581795/7aa08338-e45d-11e5-9e34-f2c63af83f83.png)

**Comment by BerkeleyTrue** [comment]
Fixed.

Happy Coding!
