### ISSUE TITLE
Block level scope

### ISSUE THREAD

**Issue by jklinck** [FreeCodeCamp/FreeCodeCamp#7411]
Challenge [Iterate with JavaScript For Loops](http://www.freecodecamp.com/challenges/iterate-with-javascript-for-loops) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = [];

for (var i = 0; i < 5; i++) {
  ourArray.push(i);
}

// Setup
var myArray = [];

// Only change code below this line.

for(var j=1;j<6;j++){
  myArray.push(j);
}

```
I think it should be mentioned on this section that for loops have block level scope and are not functions and all declared variables are global. Some students may use "var i" in their loop which will be an issue because "var i" is used in the demonstration loop. Thus causing conflicts. I suggest putting this as a comment in the editor.

**Comment by ltegman** [comment]
It doesn't seem like this should be necessary since as long as the variable is initialized to whatever starting value the user wants inside the loop it should behave as expected. Is that not what you experienced?

**Comment by jklinck** [comment]
This is what I'm referring to

for(var i=0;i<x.length;i++){
     for(var i=0;i<y.length;i++){
        //do stuff
    }
}

**Comment by jklinck** [comment]
This is what I'm referring to:

`for(var i=0;i<x.length;i++){
    for(var i=0;i<y.length;i++){
        // do stuff
    }
}`

**Comment by bugron** [comment]
@ltegman I think @jklinck means we should mention about hoisting.

**Comment by ltegman** [comment]
We could mention in the scope lessons that ES5 JavaScript only has function scoping and not block scoping, but since this is not true in ES6 we'd have to get into that and start teaching `let` and `const`. Given that there has been no follow up from any other users running into issues with this I'm going to take this as a sign that the lesson is fine as-is.

Thanks and happy coding!
