### ISSUE TITLE
Callback definition

### ISSUE THREAD

**Issue by jklinck** [FreeCodeCamp/FreeCodeCamp#7413]
Challenge [Iterate over Arrays with map](http://www.freecodecamp.com/challenges/iterate-over-arrays-with-map) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray;

```

In this example is starts referring to callbacks when there hasn't been any explanation of what they are. Maybe the file before this should have something explaining what a callback is and some simple examples of them.

**Comment by LupDre** [comment]
Hello,

The example code in the description shows a callback function:

`var timesFour = oldArray.map(function(val){
  return val * 4;
});`

The '(function(val)' part is the callback function. Here's an article I found where you can learn more: [(http://javascriptissexy.com/understand-javascript-callback-functions-and-use-them/)]

I think the keyword to remember with this problem is 'function' and once you focus on that then the instructions make a whole lot more sense. Hope this helps!

**Comment by antlersanchors** [comment]
I think @jklinck’s issue stands—the subject of this exercise is introducing the `map()` method. 

The simultaneous introduction of callbacks, particularly without any further explanation, seems pedagogically off-point. ;)

**Comment by kehugter** [comment]
Agree with @jklinck and @antlersanchors. `callback` comes out of the blue, and there's no way for an unexperienced user to identify it directly from the code. Furthermore, along with `callback`s, optional parameters are mentioned, which adds more complexity and unexplained concepts to the challenge.

**Comment by LupDre** [comment]
You guys are right. I tried searching for callback in the map and found nothing and if there's a whole page talking about callbacks (the link I posted) then FCC should definitely include it in their curriculum. Great catch, @jklinck

**Comment by PandaWhisperer** [comment]
That leaves the question of coming up with a challenge to introduce callbacks.

In [Eloquent JavaScript](http://eloquentjavascript.net/05_higher_order.html), they are introduced by building a custom `forEach()` function to iterate over arrays. This would segue well into using `.map()`.

**Comment by RyanWillDev** [comment]
I really like @PandaWhisperer's idea of using `Array.forEach()` to teach callbacks. I am not sure how to make a challenge, but I would definitely be interested in helping. I can start on the challenge explanation. I'll just need some direction on the rest.

**Comment by QuincyLarson** [comment]
Thanks for pointing these things out. We are covering these concepts much better in our expanded curriculum, which we will release soon.
