### ISSUE TITLE
My code passes in jsbin but not in freecodecamp

### ISSUE THREAD

**Issue by martensclass** [FreeCodeCamp/FreeCodeCamp#7414]
Challenge [No repeats please](http://www.freecodecamp.com/challenges/no-repeats-please#?solution=var%20permArr%20%3D%20%5B%5D%2C%20usedChars%20%3D%20%5B%5D%3B%0Avar%20count%3D0%3B%0Afunction%20permAlone(str)%20%7B%0A%20%20var%20i%2C%20ch%2C%20chars%20%3D%20str.split(%22%22)%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20chars.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20ch%20%3D%20chars.splice(i%2C%201)%3B%0A%20%20%20%20usedChars.push(ch)%3B%0A%20%20%20%20if%20(chars.length%20%3D%3D%3D%200)%7B%0A%20%20%20%20%20%20permArr%5BpermArr.length%5D%20%3D%20usedChars.join(%22%22)%3B%0A%20%20%20%20%20%20checktwo(usedChars.join(%22%22))%3B%0A%20%20%20%20%7D%20%0A%20%20%20%20permAlone(chars.join(%22%22))%3B%0A%20%20%20%20chars.splice(i%2C%200%2C%20ch)%3B%0A%20%20%20%20usedChars.pop()%3B%0A%20%20%7D%0Areturn%20count%3B%0A%7D%0A%0Afunction%20checktwo(arr)%7B%0A%20%20var%20result%3Dfalse%3B%0A%20%20for(var%20i%3D0%3B%20i%3Carr.length-1%3B%20i%2B%2B)%7B%0A%20%20%20%20if(arr%5Bi%5D%3D%3D%3Darr%5Bi%2B1%5D)%20result%3Dtrue%3B%0A%20%20%7D%0A%20%20if(result%3D%3D%3Dfalse)count%2B%2B%3B%0A%7D%0A%0ApermAlone('aab')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var permArr = [], usedChars = [];
var count=0;
function permAlone(str) {
  var i, ch, chars = str.split("");
  for (i = 0; i < chars.length; i++) {
    ch = chars.splice(i, 1);
    usedChars.push(ch);
    if (chars.length === 0){
      permArr[permArr.length] = usedChars.join("");
      checktwo(usedChars.join(""));
    } 
    permAlone(chars.join(""));
    chars.splice(i, 0, ch);
    usedChars.pop();
  }
return count;
}

function checktwo(arr){
  var result=false;
  for(var i=0; i<arr.length-1; i++){
    if(arr[i]===arr[i+1]) result=true;
  }
  if(result===false)count++;
}

permAlone('aab');

```

**Comment by martensclass** [comment]
The code above will pass all tests when I run in in another editor like jsbin.

**Comment by alistermada** [comment]
It passes all tests individually in JS Bin because the value of your global variables are reset each time you run the script.

When you run the tests on an FCC challenge, the values of your global variables (`permArr`, `usedChars`, `count`) will not be reset for each test. In this case, all it does is run the preset function `permAlone()` once for each test (not including the recursive calls to `permAlone()` in your code).

It's recommended that you not use any global variables in order to get consistent results when calling `permAlone()`.

**Comment by ltegman** [comment]
@alistermada Is correct. Global variables should not be used for function specific storage. Think about what your code will do if it is run twice. Thanks and happy coding!
