### ISSUE TITLE
muhammed amr

### ISSUE THREAD

**Issue by 0muhammed** [FreeCodeCamp/FreeCodeCamp#7416]
Challenge [Import a Google Font](http://www.freecodecamp.com/challenges/import-a-google-font#_=_) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ltegman** [comment]
Issue does not describe a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for help and if someone there says you're experiencing a bug file another issue with the relevant details. Thanks and happy coding!
