### ISSUE TITLE
Size your images issue

### ISSUE THREAD

**Issue by jlesly** [FreeCodeCamp/FreeCodeCamp#7420]
Challenge [Size your Images](http://www.freecodecamp.com/challenges/size-your-images#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
  .smaller-image {
    width: 100px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

I am not allowed to move on to the next challenge.The first task is to add a class (smaller-image) to the img element. I have revised my code and I can't figure out what I am doing wrong. My browser zoom is at 100%.

**Comment by cannelflow** [comment]
instructions are Create a class called smaller-image and use it to resize the image so that it's only 100 pixels wide.and i can see smaller image class in css but not here at <img src="https://bit.ly/fcc-relaxing-cat"> before asking here you can try here https://gitter.im/FreeCodeCamp/FreeCodeCamp first

**Comment by jlesly** [comment]
Thank you

**Comment by vijayalaxmidara** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  .smaller-image{
    width:260;
  }
  h2 {
    font-family: Lobster, Monospace;
    }
  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>
 <h2 class="red-text">CatPhotoApp</h2>
<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat"
    alt="cat photo with orage baground">
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
 <style>

**Comment by vijayalaxmidara** [comment]
I am not allowed to move on to the next challenge.The first task is to add a class (smaller-image) to the img element. I have revised my code and I can't figure out what I am doing wrong. My browser zoom is at 100%.

**Comment by texas2010** [comment]
@vijayalaxmidara, this place is not for ask help on here.  sorry!
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help. 

Happy Coding.

**Comment by dana2402** [comment]
}
 .smaller-image { width: 100px;}
 </style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. " >

**Comment by dana2402** [comment]
}
 .smaller-image { width: 100px;}
 </style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image"

**Comment by texas2010** [comment]
@dana2402 
Please do not post your solution on here. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by horizon141** [comment]
it should look like this 

img 
  .smaller-image {
    width: 100px;
  }

and not like this 

  .smaller-image {
    width: 100px;
  }

**Comment by Thirucoder** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
 
  h2 {
    font-family: Lobster, Monospace;
  }
 
  p { 
    font-size: 16px;
    font-family: Monospace;
  }

</style>

<style>
  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class= smaller-image {width: 100px;} src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Thirucoder** [comment]
<img class= smaller-image {width: 100px;} src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

**Comment by Thirucoder** [comment]
you just add
 <img class= smaller-image {width: 100px;} src [ the # ULR ]
