### ISSUE TITLE
trying to understand how you came up with your code

### ISSUE THREAD

**Issue by DivaWeb** [FreeCodeCamp/FreeCodeCamp#7425]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

#### Screenshot
Let's make it so that when a user clicks the "Get Message" button, we change the text of the element with the class message to say "Here is the message".

I do not understand where you get "the class message" from because I do not see any such class in the html. It would be more helpful to me if you could explain where you get this class from so I know how to use this in the future.

**Comment by raisedadead** [comment]
Hi @DivaWeb Can you please point us to the challenge where you are getting this?

**Comment by bugron** [comment]
@DivaWeb thanks for posting. Actually, there is an element with the `message` class in that challenge (Change Text with Click Events).
![](http://i.imgur.com/8sQumBs.png)
Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first,thanks.
