### ISSUE TITLE
Make Object Properties Private , returns correct in console but doesn't pass challenge? 

### ISSUE THREAD

**Issue by Ballal00** [FreeCodeCamp/FreeCodeCamp#7428]
Challenge [Make Object Properties Private](http://www.freecodecamp.com/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20var%20gear%20%3D%200%3B%0A%20%20%0A%20%20%2F%2Fpublic%20methods%0A%20%20this.setGear%3D%20function(change)%20%7B%0A%20%20%20%20gear%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%20%20%0A%20%20this.getGear%20%3D%20function()%20%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0A%0AmyBike.setGear(4)%3B%0AmyBike.getGear()%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
  var gear = 0;
  
  //public methods
  this.setGear= function(change) {
    gear += change;
  };
  
  this.getGear = function() {
    return gear;
  };

};

var myCar = new Car();

var myBike = new Bike();

myBike.setGear(4);
myBike.getGear();
```

**Comment by Ballal00** [comment]
As you can see i've tried testing to set the value 4 using setGear(4) and getGear returns 4. However the activity isn't passed. 

![fcc](https://cloud.githubusercontent.com/assets/9910380/13552082/3133c53c-e3a6-11e5-8e8c-4b9946a12d79.png)

**Comment by ltegman** [comment]
Check out what happens if you call the `setGear` method twice. Next time please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to confirm what you're seeing is a site issue and not an issue with your solution before filing a Github Issue. Thanks and happy coding!

**Comment by Ballal00** [comment]
ohh right! Thank you it works now, changed:
gear += change;  to 
gear = change;

**Comment by hemantknayak** [comment]
this helped me as well :+1:

**Comment by fuko4** [comment]
This helped me too! Thank you!

**Comment by sinharajatit** [comment]
this also helped me but I have a point to make. In my case why "+=" issue was working for setGear(4) and not for setGear(3)/setGear(1);

**Comment by real-gobs** [comment]
wow...I am finally through..Thank you!

**Comment by bingcanshizhe** [comment]
thanks, but why "+=" cant complete it?

**Comment by Pulsar-Mind** [comment]
I really don't understand why its not working out with +=. Maybe they did not want us to just copy the example. or is the code running more than one time so the second time gear will be added to the old value? with +=? thats maybe it but im getting the right answers with += in my console so I does not make any sense...

**Comment by phroday** [comment]
I think the += is performing an addition to the gear instead of just displaying it.

**Comment by Gichunge** [comment]
I found this example on GitHub and it works;
var Cake = function() {

  var loot = 2;
  // Getter to know how much loot you have
  this.getLoot = function() {
    return loot;
  };

  // Setter to change the ammount of loot
  this.setLoot = function(num){
    loot = num;
  };

**Comment by texas2010** [comment]
@Gichunge 
Please do not post the solution on here. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
