### ISSUE TITLE
 Fill in the Blank with Placeholder Text

### ISSUE THREAD

**Issue by Cipto1001** [FreeCodeCamp/FreeCodeCamp#7429]
Challenge [Fill in the Blank with Placeholder Text](http://www.freecodecamp.com/challenges/fill-in-the-blank-with-placeholder-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

```

**Comment by ltegman** [comment]
Issue does not describe a problem. Check with the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need help and file a bug with problem description and repro steps if they confirm you're experiencing a bug. Thanks and happy coding!
