### ISSUE TITLE
bug Change the Font Size 

### ISSUE THREAD

**Issue by jkb10** [FreeCodeCamp/FreeCodeCamp#7437]
i have an issue in change the font size of an element. i am using firefox web broser 44.0.2(Ubuntu 15.10) , and i also try to hit "ctrl ++" but it not give an effect. here my code
![screenshot from 2016-03-06 23-32-54](https://cloud.githubusercontent.com/assets/14923762/13555473/e8222d86-e3f3-11e5-8b4d-80ae900f25ba.png)

**Comment by ltegman** [comment]
You have not correctly done what the challenge is asking you to do. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you need assistance. Thanks and happy coding!

**Comment by jkyereh** [comment]
am having the same issue
