### ISSUE TITLE
Video challenges question animations

### ISSUE THREAD

**Issue by alphashuro** [FreeCodeCamp/FreeCodeCamp#7438]
The text enter and exit animations for each question are really straining on the eyes, makes me dizzy every time, please remove them or use more eye-friendly animations.

**Comment by QuincyLarson** [comment]
Hi @alphashuro you're the first person who's reported this. I'm going to leave this issue open and see whether anyone else is experiencing this.

**Comment by ltegman** [comment]
It doesn't make me dizzy or hurt my eyes, but @SaintPeter and myself both expressed concerns over the animation being too much in the release PR (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5871#issuecomment-169236885), so you can count me as another who has an issue with it.

**Comment by QuincyLarson** [comment]
@alphashuro @ltegman we will simplify the video challenge interface and it will not use animations.
