### ISSUE TITLE
The lesson allows you to continue without placing the buttons side by side 

### ISSUE THREAD

**Issue by maper81** [FreeCodeCamp/freecodecamp#744]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by maper81** [comment]
While using the <div class="col-xs-4"> the lesson is marked as complete without closing the div </div> which results in stacked buttons rather than a row of buttons

**Comment by BerkeleyTrue** [comment]
Hey @maper81,

A fix has been completed and should be up soon. Thanks!

Good Luck with the rest of the challenges!
