### ISSUE TITLE
This does not seem to work for "May the force be with you". But my testing shows it to be correct in the result window of 5.

### ISSUE THREAD

**Issue by nexatris** [FreeCodeCamp/FreeCodeCamp#7441]
Challenge [Find the Longest Word in a String](http://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20longestLength%20%3D%200%3B%0Afunction%20findLongestWord(str)%20%7B%0A%20%20%20%20var%20res%20%3D%20str.split(%22%20%22)%3B%0A%20%20var%20arrayLength%20%3D%20res.length%3B%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20arrayLength%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(res%5Bi%5D.length%20%3E%20longestLength)%7B%0A%20%20%20%20%20%20%20%20%20%20longestLength%20%3D%20res%5Bi%5D.length%3B%0A%20%20%20%20%7D%0A%7D%0Areturn%20longestLength%3B%0A%0A%0A%20%20%0A%20%20%20%20%2F%2FDo%20something%0A%7D%20%0A%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var longestLength = 0;
function findLongestWord(str) {
    var res = str.split(" ");
  var arrayLength = res.length;
for (var i = 0; i < arrayLength; i++) {
    if (res[i].length > longestLength){
          longestLength = res[i].length;
    }
}
return longestLength;


  
    //Do something
} 


findLongestWord("May the force be with you");

```

**Comment by ltegman** [comment]
Global variables are bad. Think through what your code does if it is run twice. Thanks and happy coding!

**Comment by nexatris** [comment]
Thank you.  I just moved the variable to inside of the function.  Lesson 
learned.  Thanks again.

Sent with AquaMail for Android
http://www.aqua-mail.com
