### ISSUE TITLE
Wrong test result of challenge

### ISSUE THREAD

**Issue by Laconty** [FreeCodeCamp/FreeCodeCamp#7449]
Challenge [Drop it](http://www.freecodecamp.com/challenges/drop-it#?solution=function%20drop(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20var%20filtArr%20%3D%20arr.filter(func)%3B%0A%20%20return%20%20filtArr%3B%0A%7D%0A%0Adrop(%5B1%2C%202%2C%203%2C%209%2C%202%5D%2C%20function(n)%20%7Breturn%20n%20%3E%202%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.116 Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function drop(arr, func) {
  // Drop them elements.
  var filtArr = arr.filter(func);
  return  filtArr;
}

drop([1, 2, 3, 9, 2], function(n) {return n > 2;});

```

**Comment by ltegman** [comment]
@Laconty There is nothing wrong with the tests. The challenge is not asking you to do something that can be accomplished with `filter`. Reread the instructions and visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help. Thanks and happy coding!
