### ISSUE TITLE
a little confuse about passing the chhllenge's logic 

### ISSUE THREAD

**Issue by gofighting123** [FreeCodeCamp/FreeCodeCamp#7451]
Challenge [Comparison with the Equality Operator](http://www.freecodecamp.com/challenges/comparison-with-the-equality-operator#?solution=%2F%2F%20Setup%0Afunction%20myTest(val)%20%7B%0A%20%20if%20(val%3D%3D12)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function myTest(val) {
  if (val==12) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
myTest(10);

```

the left iframe shows as below:
and the test console response : Not Equal

myTest(10) should return "Not Equal"
myTest(12) should return "Equal"
myTest("12") should return "Equal"
You should use the == operator

so, that means I just follow the instructions and i will get pass ?

**Comment by raisedadead** [comment]
Yes, The console output just shows the test that's in the editor window (and only last one if there are multiple test cases in the editor) , however the test runner runs all the test cases, that are listed.

If you are stuck please ask for help in the [Chat room](https://gitter.im/FreeCodeCamp/Help).

**Comment by gofighting123** [comment]
thanks @raisedadead anyway. 
i am newbie here:> and git system...still trying to catch up with this whole changes @@

**Comment by darbane** [comment]
Change fuction myTest to testEqual
it works this way
function testEqual(val) {
  if (val == "12") { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testEqual("12");
