### ISSUE TITLE
Arguments Optional

### ISSUE THREAD

**Issue by fickojuventino** [FreeCodeCamp/FreeCodeCamp#7452]
Challenge [Arguments Optional](http://www.freecodecamp.com/challenges/arguments-optional#?solution=function%20add(x)%20%7B%0A%0A%20%20if(arguments.length%3D%3D%3D1)%7B%0A%20%20return%20function(y)%7B%0A%0A%20%20%20%20%0A%20%20%20%20if(typeof(y)%3D%3D%3D%22number%22)%7B%0A%20%20%20%20return%20x%2By%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if(typeof%20(y)%20%3D%3D%3D%20%22string%22)%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%7D%0A%20%20%7D%3B%0A%20%7D%0A%20%20%0A%20%20else%7B%0A%20%20%20%20var%20suma%3D0%3B%0A%20%20var%20provera%3B%0A%20%20for(var%20i%3D0%3B%20i%3Carguments.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(isNaN(arguments%5Bi%5D)!%3D%3Dtrue)%7B%0A%20%20%20%20%20%20%0A%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if(typeof(arguments%5Bi%5D)%3D%3D%3D%22number%22)%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20suma%2B%3Darguments%5Bi%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20suma%3B%0A%20%20%7D%0A%7D%0A%0Avar%20sumTwoAnd%3Dadd(2)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function add(x) {

  if(arguments.length===1){
  return function(y){

    
    if(typeof(y)==="number"){
    return x+y;
    }
    else if(typeof (y) === "string"){
      return undefined;
    }
  };
 }
  
  else{
    var suma=0;
  var provera;
  for(var i=0; i<arguments.length; i++){
    if(isNaN(arguments[i])!==true){
      

      
      if(typeof(arguments[i])==="number"){
        
        suma+=arguments[i];
      }
      else{
        return undefined;
      }
      
    }
    else{
        return undefined;
      }
  }
  return suma;
  }
}

var sumTwoAnd=add(2);
```

I think my code is correct and it gives me wanted output, but still "add("http://bit.ly/IqT6zt") should return undefined." is not checked.

**Comment by ltegman** [comment]
Your code doesn't return `undefined` for the test case that is failing. If you need help visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript). Thanks and happy coding!
