### ISSUE TITLE
I can't see any different between the standard results and mine.

### ISSUE THREAD

**Issue by danielinwind** [FreeCodeCamp/FreeCodeCamp#7453]
Challenge [Steamroller](http://www.freecodecamp.com/challenges/steamroller#?solution=var%20newarr%3D%5B%5D%3B%0Afunction%20steamroller(arr)%20%7B%0A%20%20%2F%2F%20I'm%20a%20steamroller%2C%20baby%0A%20%20if(Array.isArray(arr))%7B%0A%20%20%20%20for(var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%0A%20%20%20%20%20%20steamroller(arr%5Bi%5D)%3B%0A%20%20%7Delse%7B%0A%20%20%20%20newarr.push(arr)%3B%0A%20%20%7D%0A%20%20return%20newarr%3B%0A%7D%0A%0Asteamroller(%5B1%2C%20%5B2%5D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var newarr=[];
function steamroller(arr) {
  // I'm a steamroller, baby
  if(Array.isArray(arr)){
    for(var i=0;i<arr.length;i++)
      steamroller(arr[i]);
  }else{
    newarr.push(arr);
  }
  return newarr;
}

steamroller([1, [2], [3, [[4]]]]);

```

**Comment by ltegman** [comment]
You're using a global variable for what should be a function specific storage. Check what happens if you call that function twice. Thanks and happy coding!
