### ISSUE TITLE
Map the Debris

### ISSUE THREAD

**Issue by fangmobile** [FreeCodeCamp/FreeCodeCamp#7455]
Challenge [Map the Debris](http://www.freecodecamp.com/challenges/map-the-debris) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function orbitalPeriod(arr) {
  var GM = 398600.4418;
  var earthRadius = 6367.4447;
  return arr;
}

orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]);

```

Just give the formula to calculate. This is a code camp, not math camp...

**Comment by ltegman** [comment]
Sometimes coding involves branching outside your current knowledge base to learn something related to the business logic of the code you're working on. In this case we've done more work than an employer would likely do and have pointed you towards a wikipedia article to help. If you need more assistance there's people in the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) who I'm sure would be happy to help you. Thanks and happy coding!
