### ISSUE TITLE
Profile lookup bug

### ISSUE THREAD

**Issue by samosale** [FreeCodeCamp/FreeCodeCamp#7458]
Challenge [Profile Lookup](http://www.freecodecamp.com/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUp(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20var%20obj%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20var%20bool%20%3D%20contacts.some(function(val)%7B%0A%20%20%20%20%0A%20%20%20%20return%20val.firstName%20%3D%3D%3D%20firstName%3B%0A%20%20%20%20%0A%20%20%7D)%3B%0A%20%20%0A%20%20if(!bool)%7Breturn%20%22No%20such%20contact%22%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%0A%20%20contacts.forEach(function(val)%7B%0A%20%20%20%20%0A%20%20%20%20if(val.firstName%20%3D%3D%3D%20firstName)%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20obj.push(val)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D)%3B%0A%20%20%0A%20%20%0A%20%20if(obj.length%20%3D%3D%3D%200)%7B%0A%20%20%20%20%0A%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20obj%5B0%5D%5Bprop%5D%3B%0A%20%20%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUp(%22Akira%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];
/*   lookUp("Akira", "address");  */
// firstName does not exist(Akira) so it should return no such contact, however it asks for ''no such property"
function lookUp(firstName, prop){
// Only change code below this line

  var obj = [];
  
  var bool = contacts.some(function(val){
    
    return val.firstName === firstName;
    
  });
  
  if(!bool){return "No such contact";
            
           }
  
  contacts.forEach(function(val){
    
    if(val.firstName === firstName){
      
      obj.push(val);
    }
    
  });
  
  
  if(obj.length === 0){
    
    return "No such property";
  }
  
  return obj[0][prop];
  
// Only change code above this line
}

// Change these values to test your function
lookUp("Akira", "address");

```

**Comment by alistermada** [comment]
There's something wrong with your setup. The `firstName` property is missing from the first contact. If you reset your code, you'll see that the `firstName` of the first contact is Akira.

**Comment by samosale** [comment]
I hit f5 but didn't see it.

**Comment by ltegman** [comment]
@samosale You should copy the function you wrote into a text editor so you don't lose it and then press the reset button on the side. You can then copy your function back in and try again. Thanks and happy coding!

**Comment by MajideB** [comment]
Thanks
