### ISSUE TITLE
h1>Hello World</h1>

### ISSUE THREAD

**Issue by maneeshlove** [FreeCodeCamp/FreeCodeCamp#7459]
Challenge [Uncomment HTML](http://www.freecodecamp.com/challenges/uncomment-html#?solution=%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A%3C!%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoAPP%3C%2Fh2%3E%20%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A%20%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; GWX:RESERVED; MAARJS; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->
<!
<h1>Hello World</h1>

<h2>CatPhotoAPP</h2> 

<p>Hello Paragraph</p>
-->
  
```

**Comment by maneeshlove** [comment]
how to complete the text

**Comment by maneeshlove** [comment]
please correct the above query submitted by me

**Comment by AkiraLaine** [comment]
Hey @maneeshlove! If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or any of our help rooms. GitHub is for issues only.
