### ISSUE TITLE
for loop is not working 

### ISSUE THREAD

**Issue by HaiderJaan** [FreeCodeCamp/FreeCodeCamp#7461]
Challenge [Iterate with JavaScript For Loops](http://www.freecodecamp.com/challenges/iterate-with-javascript-for-loops#?solution=%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%5D%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%205%3B%20i%2B%2B)%20%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afor%20(var%20a%20%3D%200%3B%20a%20%3C%2010%3B%20a%2B%2B)%20%7B%0A%20%20myArray.push(a)%3B%0A%7D%0A%0Avar%20myArray%20%3D%20%5B%5D%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = [];

for (var i = 0; i < 5; i++) {
  ourArray.push(i);
}

// Setup
var myArray = [];

// Only change code below this line.

for (var a = 0; a < 10; a++) {
  myArray.push(a);
}

var myArray = [];
```

**Comment by AkiraLaine** [comment]
Hey @HaiderJaan! If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or any of our help rooms. GitHub is for issues only.
