### ISSUE TITLE
Everything Be True instructions unclear

### ISSUE THREAD

**Issue by webdev8183** [FreeCodeCamp/FreeCodeCamp#7462]
Challenge [Everything Be True](http://www.freecodecamp.com/challenges/everything-be-true#?solution=function%20every(collection%2C%20pre)%20%7B%0A%20%20%20%20%2F%2F%20Create%20a%20counter%20to%20check%20how%20many%20are%20true.%0A%20%20%20var%20counter%20%3D%200%3B%0A%0A%20%20%0A%20%20%20%20%20%20%20%20for%20(var%20c%20in%20collection)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20If%20it%20has%20the%20same%20property%20or%20the%20same%20property%20value%20then%20add%201%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(collection%5Bc%5D.hasOwnProperty(pre))%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20counter%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20console.log(counter)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20if(collection%5Bc%5D%5Bpre%5D%20%3D%3D%20pre%20%26%26%20pre%20%3E%20'0')%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20counter%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(counter)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%0A%0A%20%20%2F%2F%20Outside%20the%20loop%2C%20check%20to%20see%20if%20we%20got%20true%20for%20all%20of%20them%20and%20return%20true%2Ffalse%20%0A%20if%20(counter%20%3D%3D%20collection.length)%20%7B%0A%20%20%20%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%0A%7D%0A%0A%0Aevery(%5B%7B%22user%22%3A%20%22Tinky-Winky%22%2C%20%22sex%22%3A%20%22male%22%7D%2C%20%7B%22user%22%3A%20%22Dipsy%22%2C%20%22sex%22%3A%20%22male%22%7D%2C%20%7B%22user%22%3A%20%22Laa-Laa%22%2C%20%22sex%22%3A%20%22female%22%7D%2C%20%7B%22user%22%3A%20%22Po%22%2C%20%22sex%22%3A%20%22female%22%7D%5D%2C%20%22sex%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function every(collection, pre) {
    // Create a counter to check how many are true.
   var counter = 0;

  
        for (var c in collection) {
           // If it has the same property or the same property value then add 1
            if (collection[c].hasOwnProperty(pre)){
             counter++;
            // console.log(counter);
            }
            if(collection[c][pre] == pre && pre > '0'){
            counter++;
            console.log(counter);
          }
     }
    
  

  // Outside the loop, check to see if we got true for all of them and return true/false 
 if (counter == collection.length) {
       return true;
  } else {
    return false;
    }

}


every([{"user": "Tinky-Winky", "sex": "male"}, {"user": "Dipsy", "sex": "male"}, {"user": "Laa-Laa", "sex": "female"}, {"user": "Po", "sex": "female"}], "sex");

```
example 
every([{"user": "Tinky-Winky", "sex": "male", "age": 0}, {"user": "Dipsy", "sex": "male", "age": 3}, {"user": "Laa-Laa", "sex": "female", "age": 5}, {"user": "Po", "sex": "female", "age": 4}], "age") should return false.
//seems like this should return true since property does exist for each object, and this one also seems wrong 
every([{"name": "Pete", "onBoat": true}, {"name": "Repeat", "onBoat": true}, {"name": "FastFoward", "onBoat": null}], "onBoat") should return false

**Comment by Certhic** [comment]
It wants you to check if the values are truthy or falsy. Your code does not seem to do so. 

I think this challenge should have links to truthy/falsy on MDN to prevent misunderstandings on what it wants.

**Comment by tamerMarzouk** [comment]
The instructions are very vague "Check if the predicate (second argument) is truthy on all elements of a collection (first argument)."
so, do I need to check the value of the property specified in the 2nd argument ?

**Comment by erictleung** [comment]
@webdev8183 thanks for the issue and sorry for the late response. @Certhic has pointed out why your code does not pass. Please check your understanding of truthy and falsy values. Also note, the function name has been changed recently from `every()` to `truthCheck()`.

But to resolve possible misunderstandings, the instructions can be rewritten to be a little bit clearer.

> Check if the predicate (second argument) is `truthy` on all elements of a collection (first argument).
>
> In other words, you are given an array collection of objects. The predicate `pre` will be an object property and you need to return `true` if its value is truthy. Otherwise, return `false`.
>
> Remember, you can access object properties through either dot notation or bracket (`[]`) notation.
