### ISSUE TITLE
Using labeled statements in the 'Pig Latin' exercise throws an "Undefined label" Error

### ISSUE THREAD

**Issue by tstusr441** [FreeCodeCamp/FreeCodeCamp#7465]
#### Issue Description
* The issue happens when you use a [labeled statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label) in the Pig Latin exercise. I have been unable to confirm whether this issue happens in other exercises as well.
* To reproduce:

1. Visit the [Pig Latin algorithm exercise](http://www.freecodecamp.com/challenges/pig-latin)
2. Use a labeled statement followed by a for loop. 
3. Observe the difference between the FreeCodeCamp output and Chrome's console. FreeCodeCamp throws an "**SyntaxError: Unlabeled statement**" error but works flawlessly if you use Chrome's console.

#### Browser Information
* Google Chrome, 48.0.2564.116 (Official Build) m (64-bit)
* Windows 7

#### Your Code

```js
function translate(str) {
  var isVowel = "aeiou";
  var newStr = "test";
  
label1:
  for (var i = 0; i < 2; i++) {
    for (var j = 0; j < 3; j++) {
      break label1;
    }
  }
  return newStr;
}

translate("california");
```

#### Screenshot
**FreeCodeCamp output**: http://i.imgur.com/f3ETnch.png
**Chrome Console output**: http://i.imgur.com/QEntg6O.png

**Comment by raisedadead** [comment]
Thanks for raising the issue @tstusr441, the details are nice.

_Adding more info:_

The code in the CodeMirror is some how getting messed up by LoopProtect.
Here's the output:
```javascript
function translate(str) {
  var isVowel = "aeiou";
  var newStr = "test";

la;loopProtect.protect({ line: 7, reset: true }); bel1:
  for (var i = 0; i < 2; i++) {;
if (loopProtect.protect({ line: 7 })) break;

    ;loopProtect.protect({ line: 8, reset: true }); for (var j = 0; j < 3; j++) {;
if (loopProtect.protect({ line: 8 })) break;

      break label1;
    }
  }
  return newStr;
}

translate("california");
```

@ltegman tagging you for some insight on this.

**Comment by ltegman** [comment]
Hmm, I believe label support is built into loopProtect, but clearly something about it is not working as it should. I won't have time to look at it this week, but it no one else picks it up I can look into this and the other pending loopProtect issue next week.

**Comment by jmakGH** [comment]
_Adding more info:_

It appears that the white space before the for keyword beneath the label is what's triggering the bug.
Photos below:

No bug without space: http://imgur.com/FtaMcXi
Label error with space: http://imgur.com/fYQEJlN
