### ISSUE TITLE
the lesson does not show all the tests in this Challenge(Stand In Line) as passed, whereas all  other tests have passed.

### ISSUE THREAD

**Issue by KaushikDev** [FreeCodeCamp/FreeCodeCamp#7466]
Challenge [Stand in Line](http://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0AtestArr.push(item)%3B%0A%20%20var%20shifted%20%3D%20testArr.shift()%3B%0A%20%20%2F%2Fconsole.log(testArr)%3B%0A%20%20return%20shifted%3B%0A%20%20%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(testArr%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item) {
  // Your code here
testArr.push(item);
  var shifted = testArr.shift();
  //console.log(testArr);
  return shifted;
  
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by KaushikDev** [comment]
this has been a mistake !! the Test was not passing as the value array that was used was actual array name instead of the argument !! Sorry for any inconvenience.

**Comment by jiaowoshabi** [comment]
I have the same problem in that problem.

`function queue(arr, item) {
  // Your code here
  testArr.push(item);
  item=testArr.shift();
  return item;  // Change this line
}
// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));`

**Comment by jiaowoshabi** [comment]
Failed Test case:
queue([5,6,7,8,9], 1) should return 5

**Comment by kauepacheco** [comment]
I finished doing this:

var testArr = arr;
testArr.push(item);
var shifted = testArr.shift(item);
return shifted;
