### ISSUE TITLE
Improvement suggestion: can we be more explicit about bracket vs. dot notation

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#7469]
Challenge [Accessing Objects Properties with Variables](http://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.

I know that the point of this exercise is to show that bracket notation required when using variables, but it seems like a great many campers are not getting that message.  It seems that at least once an hour on Gitter, I am explaining that you **cannot** use dot notation with a variable.  I'd like to suggest addressing this explicitly in the exercise in a manner similar to the existing:
>Note that we do not use quotes around the variable name when using it to access the property because we are using the value of the variable, not the name

**Comment by d3ddd** [comment]
Original: "Another use of bracket notation on objects is to use a variable to access a property. This can be very useful for iterating through lists of the object properties or for doing the lookup."

Possible edits:

1. Another way bracket notation can be used on objects, which dot notation can't, is to use a variable to access property.

2. Another use of bracket notation on objects, which doesn't work with dot notation, is to use a variable to access a property.

3. Another use of bracket notation on objects is to use a variable to access a property which cannot be done with dot notation.

4. Another use of bracket notation on objects is to use a variable to access a property which does not work with dot notation.

**Comment by erictleung** [comment]
Looks like your suggestion was [added](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/41ce2d83f85b042e3e8ba1a87aa6eefacd840cc2/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3965) recently. Closing as this is now resolved. Happy coding!
