### ISSUE TITLE
Global Variables break test cases - No Repeats Please

### ISSUE THREAD

**Issue by bmoe872** [FreeCodeCamp/FreeCodeCamp#7470]
The below code does the correct output, but does not pass the test cases. Putting the global variable permutations inside the function passes the test cases. 

Challenge [No repeats please](http://www.freecodecamp.com/challenges/no-repeats-please#?solution=%20%20var%20permutations%20%3D%20%5B%5D%3B%0A%0Afunction%20permAlone(str)%20%7B%0A%20%20%0A%20%20var%20regex%20%3D%20%2F(.)%5C1%2B%2Fg%3B%0A%20%20%0A%0A%0A%20%20%20var%20strArr%20%3D%20str.split('')%3B%0A%20%20%20var%20tmp%3B%0A%20%20%0A%20%20function%20swap(index1%2C%20index2)%7B%0A%20%20%20%20tmp%20%3D%20strArr%5Bindex1%5D%3B%0A%20%20%20%20strArr%5Bindex1%5D%20%3D%20strArr%5Bindex2%5D%3B%0A%20%20%20%20strArr%5Bindex2%5D%20%3D%20tmp%3B%0A%20%20%7D%0A%20%20%0A%20%20function%20generate(n)%7B%0A%20%20%20%20if(%20n%20%3D%3D%201)%7B%0A%20%20%20%20%20%20%20permutations.push(strArr.join(''))%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20for(var%20i%3D0%3B%20i%3C%20n%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20%20%20generate(n-1)%3B%0A%20%20%20%20%20%20%20%20if(n%252%20%3D%3D%3D%200)%7B%20%2F%2F%20if%20its%20even%0A%20%20%20%20%20%20%20%20%20%20swap(i%2Cn-1)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20%20%20swap(0%2Cn-1)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20generate(str.length)%3B%0A%20%20%0A%20%20var%20filtered%20%3D%20permutations.filter(function(string)%7B%0A%20%20%20%20return%20!string.match(regex)%3B%0A%20%20%7D)%3B%0A%0A%20%20return%20filtered.length%3B%0A%0A%7D%0A%0ApermAlone(%22aab%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
  var permutations = [];

function permAlone(str) {
  
  var regex = /(.)\1+/g;
  


   var strArr = str.split('');
   var tmp;
  
  function swap(index1, index2){
    tmp = strArr[index1];
    strArr[index1] = strArr[index2];
    strArr[index2] = tmp;
  }
  
  function generate(n){
    if( n == 1){
       permutations.push(strArr.join(''));
    }
    else{
      for(var i=0; i< n; i++){
        generate(n-1);
        if(n%2 === 0){ // if its even
          swap(i,n-1);
        }
        else{
          swap(0,n-1);
        }
      }
    }
  }
  
  generate(str.length);
  
  var filtered = permutations.filter(function(string){
    return !string.match(regex);
  });

  return filtered.length;

}

permAlone("aab");

```

**Comment by ltegman** [comment]
That's because when you use a global variable the function only returns the correct result the first time it is called. This is not a site issue. Thanks and happy coding!

**Comment by bmoe872** [comment]
O shoot, there was an issue right below mine that was already solved. It has to do with how its called in FCC.
