### ISSUE TITLE
Updated sort challenge to explain how the callback works

### ISSUE THREAD

**Issue by ZackWard** [FreeCodeCamp/FreeCodeCamp#7471]
#### Screenshot
![Screenshot](https://dl.dropboxusercontent.com/u/13022985/sort.png)

#### Suggested Edit
`sort` can be passed a compare function as a callback. The compare function should return a negative number if `a` should be before `b`, a positive number if `a` should be after `b`, or `0` if they are equal.

PR coming soon

**Comment by SaintPeter** [comment]
Looks good.  Get a PR going and I'll QA it.

**Comment by ZackWard** [comment]
PR ready to go.
