### ISSUE TITLE
Challenge will not run tests in Firefox

### ISSUE THREAD

**Issue by eac62** [FreeCodeCamp/FreeCodeCamp#7473]
Challenge [Use RGB to Color Elements Blue](http://www.freecodecamp.com/challenges/use-rgb-to-color-elements-blue) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

No idea if it's my browser or an issue, but this particular challenge will not allow me to submit my answer. I'm using Firefox 

My code:
```html
<style>
  body {
    background-color: rgb(0, 0, 225);
  }
</style>

```

**Comment by ZackWard** [comment]
@eac62 Make sure that the blue value is correct. 0 = No blue, 255 = full blue.

**Comment by d3ddd** [comment]
I'm using Firefox 45.0 on a Macbook Pro running 10.11.3
I also tried using Chrome Version 48.0.2564.116 (64-bit)
and Safari Version 9.0.3 (11601.4.4)

I copy and pasted that exact code into the FCC challenge and I also could not run a test even though the preview showed the background turning blue. 

However, when I started with the default code (by resetting the challenge) and then changed the middle 255 to 0 and then the last 0 to 255 (the correct answer) everything worked. 

Below is my code which as far as I can tell is EXACTLY the same as the code above except that it works for some reason and the code in the issue doesn't. 

```
<style>
  body {
    background-color: rgb(0, 0, 255);
  }
</style>
```

Maybe I missed something, but I seriously spent 20+ min trying to find ANY differences in the code and couldn't find any. I checked for additional spaces at the end of lines, the wrong number of spaces for tabs and every other little thing I could try.

I also tried pasting the code into TextEdit on my mac which is set to be plain text only, and then copy the text from TextEdit in case their was a formatting problem of some kind and it still would not work in any of the browsers tested. 

Below is a screen shot of both versions of the code in TextEdit. The code that was submitted in the issue which doesn't work is up top, and my version of the code that works is on the bottom. There are no differences that I can see. But if I copy and paste the first one, it works in NO browser that I've tested, and if I copy and paste the second one it works in EVERY browser that I've tested.

![image](https://cloud.githubusercontent.com/assets/9157052/13624071/fe0bfb82-e55f-11e5-9b1a-66c9794f71ae.png)

I'm now very interested and curious as to what the problem might be.

**Comment by ZackWard** [comment]
It's because the code included in the issue is setting a blue value of 225, not 255. The challenge will only complete if you use rgb(0, 0, 255). rgb(0, 0, 225) is not considered "blue" for the purpose of the challenge.

**Comment by d3ddd** [comment]
Hahaha I'm officially embarrassed for not seeing that. Thank you for figuring it out.

**Comment by raisedadead** [comment]
Thanks @d3ddd and @ZackWard for the inputs, @eac62 this is not an issue with the site, please refer the comments above, if you are still stuck please visit the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).
