### ISSUE TITLE
Suggestion: Close done tasks in map

### ISSUE THREAD

**Issue by ernarkazakh** [FreeCodeCamp/FreeCodeCamp#7474]
#### FreeCodeCamp Issue template

What if I would be able to close done task map in settings if I wanted, because it`s really distructing to close them manually every time i open them.

#### Your Code

(not written yet)

**Comment by drk7891** [comment]
Could you elaborate on this a little bit?

Do you mean opening the sidebar map and wanting to click outside of that to close it?

**Comment by ernarkazakh** [comment]
I mean like make some new settings to close tasks that are already done. It is really annoying to see done tasks opening each time I click on map

**Comment by alistermada** [comment]
There's talk about implementing this feature on issue #6680.

**Comment by BerkeleyTrue** [comment]
closing as duplicate

Happy Coding!
