### ISSUE TITLE
Please help reset code editor: page - Advanced Algorithm - No Repeat Please ... Screen stuck!

### ISSUE THREAD

**Issue by An9k** [FreeCodeCamp/FreeCodeCamp#7475]
Advanced Algorithm [ No Repeat Please](http://www.freecodecamp.com/challenges/no-repeats-please) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36</code>.

Code editor stuck and screen cannot be accessed after put first code revision in. This code here is a slight modified version to be changed. Please help check the page. 

Much thanks!!
-----------------------------------------
function permAlone(str) {

  //split string to array
  var chars = str.split("");
  var noRepeat = [], permArr = [], usedChars = [];
  
  //check if all characters same return 0
  var matched = 0;
  for (var j = 0; j < chars.length - 1; j++) {
    if (chars[j] === chars[j+1]) matched++;
  }
  
  if (matched === chars.length - 1) {
    return 0;
  } else {                             //if not all matching characters
    //create permutaion of strings (factorial) recursive n! into new array
    (function permutate() {
      for (var i = 0; i < chars.length; i++) {
        var ch = chars.splice(i, 1);
        usedChars.push(ch);
        if (chars.length === 0) permArr[permArr.length] = usedChars.join("");
        permutate(chars.join(""));
        chars.splice(i, 0, ch);
        usedChars.pop();
      }
      return permArr;
    })(chars);
    
    //check for consecutive same characters regexp exclude
    noRepeat = permArr.filter(function(value){     
      var regex = /([a-zA-Z])\1+/;
      return (!regex.test(value));   //return value when there is no duplicate
    });
  }
  
  return noRepeat.length;
}

**Comment by d3ddd** [comment]
I don't have a solution for a permanent fix but if you look at the wiki page linked below that should help you get your page unstuck so you can change your code to prevent the freezing from happening when the code is run.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run

Let me know if that works for you!

**Comment by An9k** [comment]
Thank you for your help

**Comment by hallaathrad** [comment]
We're definitely working on that feature for the wiki :+1: @d3ddd.
I'm making sure to keep your suggestion alive in the list of things we need to add.
@An9k I hope you've managed to get unstuck.

Closing this issue

**Comment by An9k** [comment]
Thank you Justin, you guys are awesome!

Wiki info is great, for loop is less expensive. I'm going that route.

Once again thanks!

On Wed, Mar 9, 2016 at 6:50 AM, Justin Richardsson <notifications@github.com
