### ISSUE TITLE
Programm dont check end symbols

### ISSUE THREAD

**Issue by gonardfreeman** [FreeCodeCamp/FreeCodeCamp#7477]
Challenge [Convert Celsius to Fahrenheit](http://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=function%20convert(celsius)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20fahrenheit%3B%0A%20%20fahrenheit%20%3D%20celsius%20*%209%2F5%2B32%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20if%20(%20typeof%20fahrenheit%20!%3D%3D%20'undefined'%20)%20%7B%0A%20%20%20%20return%20fahrenheit%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20'fahrenheit%20not%20defined'%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0Aconvert(30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(celsius) {
  // Only change code below this line
  var fahrenheit;
  fahrenheit = celsius * 9/5+32
  // Only change code above this line
  if ( typeof fahrenheit !== 'undefined' ) {
    return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(30);

```
  fahrenheit = celsius * 9/5+32 as u can see in this code i forgot to end with ";" symbol but code works.

**Comment by hallaathrad** [comment]
That's not a bug but a feature :wink: 
It's called "automatic semicolon insertion" and though it is best practice to not rely on that feature, it is allowed in our editor, as it is part of the specification.

Give [this article](http://www.bradoncode.com/blog/2015/08/26/javascript-semi-colon-insertion/) a read to better understand how it works :)

Thanks for your contribution.

**Comment by psunday** [comment]
please someone should help me out with dis

**Comment by psunday** [comment]
convertToF(0) should return a number
convertToF(-30) should return a value of -22
convertToF(-10) should return a value of 14
convertToF(0) should return a value of 32
convertToF(20) should return a value of 68
convertToF(30) should return a value of 86

**Comment by texas2010** [comment]
@psunday Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.
GitHub Issues are for reporting bugs on the website only.

Happy Coding.
