### ISSUE TITLE
Suggestion: Add new languages.

### ISSUE THREAD

**Issue by ernarkazakh** [FreeCodeCamp/FreeCodeCamp#7479]
What if we would be able to add some new languages. So that this project would be available for larger audience. E.g. I speak Russian so I think that I can definitely help with this featuture.

**Comment by erictleung** [comment]
I believe there's [a movement](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3Atranslation) already! :D Here's a start for [Russian translations](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6232).

**Comment by BerkeleyTrue** [comment]
Closing as this is already in progress.

Happy Coding!
