### ISSUE TITLE
Marked Library Link

### ISSUE THREAD

**Issue by briancbarrow** [FreeCodeCamp/FreeCodeCamp#7482]
Challenge [Build a Markdown Previewer](http://www.freecodecamp.com/challenges/build-a-markdown-previewer) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The https://cdnjs.com/libraries/marked link takes me away from FCC rather than opening a new tab. Not urgent, but I think it is necessary.

**Comment by drk7891** [comment]
Does the same for me as well. HTML is missing target.

I'm on it
