### ISSUE TITLE
Encouraging people to do something wrong

### ISSUE THREAD

**Issue by andre-vandam** [FreeCodeCamp/FreeCodeCamp#7483]
Challenge [Testing Objects for Properties](http://www.freecodecamp.com/challenges/testing-objects-for-properties) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if (myObj.hasOwnProperty(checkProp))
{
    return myObj[checkProp];  
 // when using bracket notation here, try mistakenly adding " " (i.e. ["checkProp"]) around the variable , 
// a yellow  warning triangle will appear and tell you to use dot notation, instead, which short of using //an eval will  be syntactically wrong
}
  return "Not Found";
}

// Test your code by modifying these values
checkObj("gift");

```

**Comment by ltegman** [comment]
The linter is right. If you do `myObj['checkProp']` you would be better off doing `myObj.checkProp`. Using `myObj.checkProp` may not be correct for this problem, but neither is `myObj['checkProp']`, so the linter really isn't leading someone more astray than they already are. Thanks and happy coding!

**Comment by Joll59** [comment]
curious, why doesnt dot notation work here?

**Comment by Shraddha99** [comment]
@Joll59 It won't work in this case coz the dot operator won't work for Variable
on Gitter I found it 
1 . the dot operator doesn't work when the property is a variable

2. dot operator works differently. there is no property named "checkProp", checkProp is a variable, not a property name.

3. you can only use dot operator if you know what the literal name of the property is, or else it will check for a property literally named checkProp
