### ISSUE TITLE
No response when requesting /wiki/Algorithm-Wiki-Template

### ISSUE THREAD

**Issue by jstoebel** [FreeCodeCamp/FreeCodeCamp#7486]
#### Issue Description
* When Issue Happens

When I pull up the wiki sidebar, and click [Template] (https://freecodecamp.com/wiki/Algorithm-Wiki-Template), nothing happens. The request gets no response
* Steps To Reproduce

See above

#### Browser Information
* Browser Name, Version
Firefox, 44.0.2
* Operating System
Ubuntu 14.04

#### Screenshot
![fcc_screencap](https://cloud.githubusercontent.com/assets/12101566/13670004/37dc31fc-e695-11e5-88a6-d1cd56b06f47.png)

**Comment by raisedadead** [comment]
@jstoebel Thanks for the issue. The new wiki is currently being worked upon. Most of the team is involved in fixing the same.

There is a dependency on [Gatsby](https://github.com/gatsbyjs/gatsby/issues/175) which is under discussion.

Rest assured, we are making every effort to get this and other things as noted in #6946 resolved ASAP.

I am closing thing and taking your points to the above issue for tracking everything together. PLease feel free to follow the discussion on that.
