### ISSUE TITLE
Name doesn't appear on certificates after updating GitHub profile

### ISSUE THREAD

**Issue by DuckyDisciple** [FreeCodeCamp/FreeCodeCamp#7487]
I previously received my front end certification and my name didn't appear on it. Since then, I have updated my GitHub profile so that my name is on there. I tried updating my FCC profile from GitHub and didn't see a change. I just received my back end certification and my name doesn't appear on there either. It looks like it isn't actually updating from GitHub.

![screenshot 2016-03-10 at 11 16 34 am](https://cloud.githubusercontent.com/assets/14015584/13675884/9475f274-e6b1-11e5-9918-6869c8d30af2.png)

![screenshot 2016-03-10 at 11 16 18 am](https://cloud.githubusercontent.com/assets/14015584/13675891/9a133c5a-e6b1-11e5-8228-dc9e37eb87b6.png)

**Comment by raisedadead** [comment]
@BerkeleyTrue Please have a look.

**Comment by BerkeleyTrue** [comment]
Fixed https://www.freecodecamp.com/duckydisciple/front-end-certification

Happy Coding!

**Comment by DuckyDisciple** [comment]
Thanks!

**Comment by raisedadead** [comment]
@BerkeleyTrue Thanks!
