### ISSUE TITLE
Computer Basics: Decoding a Binary Number

### ISSUE THREAD

**Issue by username1001** [FreeCodeCamp/FreeCodeCamp#7490]
The first question in this Hike was, to my knowledge, rhetorical.

The question was: 
1 === on. 0 === off.
False        True

I clicked false, since the operator is "strict equals", and thus should be false, no?

**Comment by erictleung** [comment]
I'm not sure why it uses the strict equality sign `===` instead of just `==`. But I'd agree that there should be `==` instead of `===`.
