### ISSUE TITLE
Does not pass the: myStr should have a value of This is the first sentence. This is the second sentence. 

### ISSUE THREAD

**Issue by iramc** [FreeCodeCamp/FreeCodeCamp#7492]
Challenge [Concatenating Strings with the Plus Equals Operator](http://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myStr%20%3D%20%27This%20is%20the%20first%20sentence.%20%27%3B%0AmyStr%20%2B%3D%20%27This%20is%20the%20second%20sentence%27%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line
var myStr = 'This is the first sentence. ';
myStr += 'This is the second sentence';



```

**Comment by drk7891** [comment]
Seems like you're missing a period at the end of the second sentence. :)

**Comment by iramc** [comment]
thanks

**Comment by AkiraLaine** [comment]
Closing this as it seems to be solved.

**Comment by ctscodes** [comment]
I just tried this solution, and it didn't work. I don't think this thread shouldn't have been closed. 
This code: 
var myStr = 'This is the first sentence. ';
myStr += 'This is the second sentence';
fails the test for:myStr should have a value of This is the first sentence. This is the second sentence.

**Comment by ar94952** [comment]
Same problem:  

var myStr = "This is the first sentence. ";
outStr += "This is the second sentence.";

Still giving me referenceError.

**Comment by musasesay** [comment]
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line


var myStr ;
myStr = "This is the first sentence.";
myStr += "This is the second sentence.";

**Comment by bettergrammer** [comment]
Doesn't work

**Comment by leangsuorKIM** [comment]
const myStr = "This is the start. " + "This is the end."
console.log(myStr);

**Comment by sarah681** [comment]
// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start sentence, " + "This is the end sentence. ";

(myStr should have a value of This is the start sentence. This is the end sentence.
Use the + operator to build myStr( I'm getting this error what can I do))
