### ISSUE TITLE
Control-clicking links should open them in a new tab

### ISSUE THREAD

**Issue by george-stepanek** [FreeCodeCamp/FreeCodeCamp#7493]
This applies to the Map, Chat and Wiki links in the menu bar.

**Comment by AkiraLaine** [comment]
I'm not should if it's *that* useful, but it can't hurt to add the control (if possible w/out conflicting with SideCar).

@FreeCodeCamp/issue-moderators What do you guys think?

**Comment by hallaathrad** [comment]
If there is a standard function associated with an action, we should not reinvent it. The thing with right click is that it's already associated with the context menu in most contexts... Maybe a combination of keys and click or something similar would work better.

**Comment by QuincyLarson** [comment]
+1

**Comment by BerkeleyTrue** [comment]
@QuincyLarson issue's can now be liked directly through Github.

![control-clicking_links_should_open_them_in_a_new_tab_ _issue__7493_ _freecodecamp_freecodecamp](https://cloud.githubusercontent.com/assets/6775919/13714583/61ca3e4c-e784-11e5-961f-4307cf37131b.png)
