### ISSUE TITLE
cant pass the test

### ISSUE THREAD

**Issue by sidpratap** [FreeCodeCamp/FreeCodeCamp#7497]
<style>
  .red-text {
    color: red;
  }
  p{
    font-size=16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

it seems my code is right but still i cant pass the test

**Comment by cannelflow** [comment]
pls give us at least exercise name its better to ask it on chat room https://gitter.im/FreeCodeCamp/Help  first

**Comment by raisedadead** [comment]
Thanks @cannelflow

@sidpratap Please visit [Help Chat](https://gitter.im/FreeCodeCamp/Help) first and confirm others are facing the same. 

Please follow [guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue) while opening issues.

Happy Coding!
