### ISSUE TITLE
Introducing JSON exercise is missing a comma to make tests pass

### ISSUE THREAD

**Issue by Daeke** [FreeCodeCamp/FreeCodeCamp#7498]
Challenge [Introducing JavaScript Object Notation JSON](http://www.freecodecamp.com/challenges/introducing-javascript-object-notation-json) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
  {
    "artist": "Green Day",
    "title": "Dookie",
    "release_year": 1993,
    "formats": [
      "CS",
      "8T",
      "LP",
      "CD"
    ],
    "gold": true
  }
];


```

Note that above the comment line ('add record here'), there should be a comma next to the closing brace, otherwise the tests will fail. The comment misleads the user into thinking they should not have to edit anything above that line (like most of the FCC exercises).

**Comment by raisedadead** [comment]
@Daeke Thanks for the issue.

But its clearly mentioned in the instructions:
> Note
> You will need a comma in between objects in JSON objects with more than one object in the array.

The comment doesn't say that anything can't be added above the statement. But Yes, as you say, campers as a habit from previous lessons can mis-judge this line to be similar.

But this is a good opportunity to break such a notion, and read the instructions and the content of the challenges carefully. Don't you agree?

What do you propose would be a better alternative?

**Comment by Daeke** [comment]
Wow, I completely missed that in the instructions.

I do think that because the rest of the exercises train you to put code after a comment, the formatting in this one is a bit strange. I would've expected the comma to be there for me in the first place, but if it hasn't come up previously, or isn't common feedback, I've got no issue just closing this out.

**Comment by raisedadead** [comment]
Well it actually has come up earlier with #7333, and even others I guess but that does leave us with the choice whether to add the comma or not.

IMHO, I favor the later. This will at least make campers register the importance of the comma, whilst they are learning.

Adding it there for campers if not always but for almost all times, have a oversight on its requirement.

Closing this. But feel free to continue the discussion. We can reopen this again if we have a notion to do it the other way round.

Thanks for your inputs and Happy coding! :smile:

**Comment by mkincaid11** [comment]
It also appears to be the placement of that comma as well. 

var myMusic = [
{
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true // I tried to place the comma after this boolean
},  // I got the correct answer by placing the comma here
  // Add record here
// I tried placing the comma here
{   // I tried placing a comma in front of this bracket
  "artist": "Nine Ince Nails",
    "title": "Head like a Hole",
    "release_year": 1989,
    "formats": 
    [ 
      "CS", 
      "8T", 
      "LP" 
    ],
    "gold": true
}

];

**Comment by dashdummy** [comment]
Hello sorry to re-open this, but ive just been stuck on this for ages. 

Granted I do now see after reading this that it does say in the instructions to add the comma, however historically I would agree with previous comments, when doing other exercises on FCC you are normally not "allowed" to modify above the comments.   

I think it may pay dividends on the starting code to be as such:
`
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true  **// Add record below this line**
  } 
];`

at least there is a clear demarcation of where the example ends and your input may start.

What are your thoughts?

**Comment by raisedadead** [comment]
@dashdummy 

This would lead to to confusion because, campers would start trying to insert the record clock before the `}` leading to errors.
