### ISSUE TITLE
Next Challenge Logic

### ISSUE THREAD

**Issue by cshutchinson** [FreeCodeCamp/freecodecamp#75]
While this is nothing major, I thought you guys might like to correct this logic in the code. When you load freecodecamp.com it by default takes you to your current challenge. It appears that the challenge returned is the next challenge after the last one you completed. However, the logic should be the next uncompleted challenge greater than the last one you completed. 

For example, coderbytes was my last completed challenge. So when I load FCC it takes me to the next challenge after that, Manage Source Code with Git, even thought it should be showing me my next uncompleted challenge, Using Redis to Persist Data. 

I can demonstrate if needed, no big deal; thought you might like to fix.

**Comment by terakilobyte** [comment]
This will be corrected after the overhaul of the way challenges are stored and served. I'll leave this open for now as a reminder and close it when that update happens.

**Comment by QuincyLarson** [comment]
Thanks for reporting this, @cshutchinson. @terakilobyte is right - all of this is already fixed on our coursewares, which will become our new challenges soon. So I am going to go ahead and close this issue.
