### ISSUE TITLE
Can't advance past step 33

### ISSUE THREAD

**Issue by guntario** [FreeCodeCamp/freecodecamp#750]
![step 33 error](https://cloud.githubusercontent.com/assets/1737183/7895005/ed30d750-062c-11e5-95eb-2efe0f3f0971.jpg)
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue. I can't get past it. Check the screenshot. The code is correct, but no matter what I try, I can't get "Your form should have a button inside it" to validate.

**Comment by QuincyLarson** [comment]
Thank you for pointing this out. I've fixed it.
