### ISSUE TITLE
Challenge DNA Pairing possible bug

### ISSUE THREAD

**Issue by bhargav4** [FreeCodeCamp/FreeCodeCamp#7500]
Challenge [DNA Pairing](http://www.freecodecamp.com/challenges/dna-pairing#?solution=var%20arr%3D%5B%5D%3B%0Afunction%20pair(str)%20%7B%0A%20%20for(var%20i%3D0%3Bi%3Cstr.length%3Bi%2B%2B)%7B%0A%20%20%20%20if(str%5Bi%5D%3D%3D'A')%7B%0A%20%20%20%20%20%20Dpair('T')%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if(str%5Bi%5D%3D%3D'T')%7B%0A%20%20%20%20%20%20Dpair('A')%3B%0A%20%20%20%20%7D%0A%20%20%20else%20if(str%5Bi%5D%3D%3D'G')%7B%0A%20%20%20%20%20%20Dpair('C')%3B%0A%20%20%20%20%7D%0A%20%20%20else%20if(str%5Bi%5D%3D%3D'C')%7B%0A%20%20%20%20%20%20Dpair('G')%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20function%20Dpair(x)%7B%0A%20%20%20%20arr.push(%5Bstr%5Bi%5D%2Cx%5D)%3B%0A%20%20%7D%0A%20%20%20return%20(arr)%3B%0A%7D%0A%0Apair(%22ATCGA%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
_Screenshot below_

My code:
```javascript
var arr=[];
function pair(str) {
  for(var i=0;i<str.length;i++){
    if(str[i]=='A'){
      Dpair('T');
    }
    else if(str[i]=='T'){
      Dpair('A');
    }
   else if(str[i]=='G'){
      Dpair('C');
    }
   else if(str[i]=='C'){
      Dpair('G');
    }
  }
  function Dpair(x){
    arr.push([str[i],x]);
  }
   return (arr);
}

pair("ATCGA");

```

**Comment by bhargav4** [comment]
![capture](https://cloud.githubusercontent.com/assets/12525622/13710371/2237c1e0-e7df-11e5-8ebc-3f91a485ed6c.JPG)

**Comment by sludge256** [comment]
Think about what happens to your array `arr` if the function is called more than once. Your issue is the scope of the variable.Not a site bug, but feel free to ask in [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need a more thorough explanation.
