### ISSUE TITLE
Counting Cards(Not Working)

### ISSUE THREAD

**Issue by HTMLNoob** [FreeCodeCamp/FreeCodeCamp#7502]
Challenge [Counting Cards](http://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0Afunction%20cc(card)%20%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Aswitch%20(card)%20%7B%0Acase%20%27J%27%3A%0Acase%20%27Q%27%3A%0Acase%20%27K%27%3A%0Acase%20%27A%27%3A%0Acase%2010%3A%0Acount--%3B%0A%7D%0Aif%20(count%20%3C%207)%20%7B%0Acount%2B%2B%3B%0A%7D%0Aif%20(count%20%3C%3D%200)%20%7B%0Areturn%20count%20%2B%20%22%20Hold%22%3B%0A%7Delse%20if%20(count%20%3E%200)%20%7B%0Areturn%20count%20%2B%20%22%20Bet%22%3B%0A%7D%0Areturn%20%22Change%20Me%22%3B%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(3)%3B%20cc(9)%3B%20cc(%27Q%27)%3B%20cc(8)%3B%20cc(%27A%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;
function cc(card) {
// Only change code below this line
switch (card) {
case 'J':
case 'Q':
case 'K':
case 'A':
case 10:
count--;
}
if (count < 7) {
count++;
}
if (count <= 0) {
return count + " Hold";
}else if (count > 0) {
return count + " Bet";
}
return "Change Me";
// Only change code above this line
}
// Add/remove calls to test your function.
// Note: Only the last will display
cc(3); cc(9); cc('Q'); cc(8); cc('A');

```
It looks to me like this code works. Several users in the chat said this should work. But, I keep on getting it wrong. I believe this is a bug,

**Comment by alistermada** [comment]
Nope, not a bug. Hint, here's your problem:
```JS
if (count < 7) {
count++;
}
```
Just one thing here needs to change and your code will pass. If you compare this `if` statement with your `switch` statement you'll see what's wrong.

**Comment by HTMLNoob** [comment]
Ah... Thank you @alistermada  Didn't realize that I put in the wrong variable. Thank you!

**Comment by raisedadead** [comment]
Thanks @alistermada !

**Comment by JBuji** [comment]
`var count = 0;

function cc(card) {
  // Only change code below this line
  if (card<=6) count++;
  else if (card<=9) ;       // do nothing =======
       else count--;
  if (count>0)
  return count+" Bet";  
  return count+" Hold";
  // Only change code above this line
}
// Add/remove calls to test your function.
// Note: Only the last will display
cc(3); cc(2); cc('A'); cc(10); cc('K');

**Comment by ouzatl** [comment]
if (1<card && card< 7) {
count++;
}

**Comment by ouzatl** [comment]
var count = 0;
function cc(card) {
  var answer="";
  switch (card){
    case 10 :
    case "J":
    case "K":
    case "Q":
    case "A":
   count--;
  }
   
  if(1<card && card<7){
    count++;
  }
  
  if (count<=0){
    answer = count + " Hold";
  }
  else if(count>0){
    answer = count + " Bet";
    
  }
  
  return answer;
 
}

cc(10); cc(3); cc(2); cc('K'); cc('A');

**Comment by raisedadead** [comment]
@ouzatl please do not post solutions or code on this thread, you can visit chat rooms and forum for assistance on code.
