### ISSUE TITLE
Change "nameEs" to "titleEs" for all translations

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#7503]
There are three properties associated with a challenge that have to do with naming, each has it's own place.

`Title` is user-defined. It is the name of the challenge given by the community. This is used in the challenge itself and displayed to the user in the html.

`name` is programmatically generated from the `title` property while removing any non-alphanumerics. This is used during regex searching for dynamic routes. 

'dashedName` is programmatically generated from the `name` property. It further changes the title by removing and replacing spaces with dashes. This is used in the url of the challenge.

This was not always the case and was changed to the current set up some months ago.

Unfortunately, the translations of these challenges did not have those properties updated.

In order to move forward with translations and enable dynamic routes, we need to change those title properties that are currently in the format `nameEs` to `titleEs`.

**Comment by SaintPeter** [comment]
I've got this.  I already have a framework written for processing the JSON.

I take it that we're talking about `nameLN` to `titleLN` where LN is any 2 letter language identifier?

**Comment by BerkeleyTrue** [comment]
Yes, but we are using camelCase even for the indentifier. `nameLn` to `titleLn`.

**Comment by SaintPeter** [comment]
I meant LN as a placeholder.  Got it.  I'll get a PR going by the end of the day.

**Comment by raisedadead** [comment]
@SaintPeter and @BerkeleyTrue Does this change affect the current translations procedures in anyway?
If yes would any of you mind commenting on the issue FreeCodeCamp/wiki#565 with the details?
I making changes to the guide and will update if anything is required.

**Comment by christophermoura** [comment]
@SaintPeter and @BerkeleyTrue I don't know if this "_issue_" causes any kind of impact , but the translators for Brazilian Portuguese are using **PtBR** as a identifier, once the language spoken in Brazil is different from the one spoken in Portugal (**PT**).

So far, we've been doing like in the excerpt bellow:

```json
      "namePtBR": "Recorra à nossa Wiki",
      "descriptionPtBR": [
        [
          "http://i.imgur.com/4GO4zcI.gif",
          "Um gif mostrando como você pode clicar no botão \"Wiki\" no canto superior esquerdo para acessar a wiki.",
          "Clique no botão \"Wiki\" no canto superior esquerdo. <br>Nossa comunidade tem contribuído com muitas informações úteis que podem ser pesquisadas nessa wiki.",
          ""
        ]
      ]
```

> Extracted from the following Pull Request: [7097](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7097).
