### ISSUE TITLE
This library (validator.js) validates strings only

### ISSUE THREAD

**Issue by ChristianLapinig** [FreeCodeCamp/FreeCodeCamp#7507]
I recently did a `git pull`. I usually run an npm install along with installing gulp and bower. I ran `bower install` and nothing installed which caught my attention. Then I ran `npm run only-once` and everything seemed to seed correctly. I ran gulp, and after I logged in I got this:

![screen shot 2016-03-11 at 5 35 58 pm](https://cloud.githubusercontent.com/assets/11323135/13719774/c5102036-e7af-11e5-9e73-66a8a837778b.png)

Does anyone know what's causing this? Usually when I run `bower install` the dependencies usually install, but that didn't happen this time

**Comment by techtolentino** [comment]
@christianlapinig what's the URL?

**Comment by raisedadead** [comment]
@ChristianLapinig I recommend you try some common trouble shooting steps that seem to work for me, I had seen this a while ago:

For broken modules/dependencies:
1. Clear npm cache : `npm cache clear`
2. Delete `node_modules`
3. `npm install` in the FCC directory.

For Seed:
Note : `npm run only-once` is not to be run once during setup, then it should be skipped for every other  `git pull` you do for updating the code.

If you do need to seed the database, you can do `node seed` instead.

Also for corrupted setup, if you are doing the `npm run only-once` anyway, then remember to delete the `server/rev-manifest.json` before you do so.

Hope this helps! Join us in the [Chat room](https://gitter.im/FreeCodeCamp/HelpContributors) if you need any help

**Comment by raisedadead** [comment]
@ChristianLapinig Closing as stale with no updates.

Please reach us on the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/HelpContributors) if you are still stuck.
