### ISSUE TITLE
Video challenges are broken in IE 11

### ISSUE THREAD

**Issue by Querky** [FreeCodeCamp/FreeCodeCamp#7510]
#### Issue Description
1. View any video challenge in IE 11, such as  [The DOM: What's the Document Object Model?](http://www.freecodecamp.com/videos/the-dom-whats-the-document-object-model).
**Observed**: The video is stuck on the loading circle.

2. Click on "Take me to the Questions."
**Observed**: Nothing happens.

Notes:
- I can complete code exercises (including moving to the next one) and view project videos with IE 11.
- Video challenges work for me in Firefox 44.0.2 and Firefox 45.

#### Browser Information
User Agent: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko</code>.

**Comment by raisedadead** [comment]
I tested this on `Windows 10 - IE11` its broken indeed as per the issue description.
But works completely fine on other browsers including `Microsoft Edge`.

**Comment by alistermada** [comment]
Might have something to do with this: [Playback issues on Windows](https://vimeo.com/forums/help/topic:112861).

Does disabling hardware acceleration fix the problem? I can't test this myself as Vimeo is blocked by my ISP and using a proxy doesn't work.

**Comment by Querky** [comment]
Disabling hardware acceleration had no effect.

I can view project videos with IE 11, and those are also hosted on Vimeo.

**Comment by raisedadead** [comment]
Addtional Info:

![image](https://cloud.githubusercontent.com/assets/1884376/13721933/42f1f06e-e85b-11e5-824f-773780fe799c.png)

**Comment by QuincyLarson** [comment]
@raisedadead Is this issue specific to Vimeo? If so, we can close it because I'm moving all videos over to youtube.

**Comment by raisedadead** [comment]
@QuincyLarson Yes we can close this when we close #8039
