### ISSUE TITLE
Outdated Italicize method

### ISSUE THREAD

**Issue by trashtalka3000** [FreeCodeCamp/FreeCodeCamp#7512]
Challenge [Change Text Inside an Element Using jQuery](http://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
In the descriptionof the challenge, it uses `<i>` to replace the italicized text with jquery instead of the `<em>` tag. In a previous challenge it mentions how `<i>`is outdated and usually used for icons in bootstrap now

ie.
`$("h3").html("<i>jQuery Playground</i>");`
should be:
`$("h3").html("<em>jQuery Playground</em>");`

My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
The [earlier challenge](https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons) you cited does say the `i` tags is used for icons now.

>The i element was originally used to make other elements italic, but is now commonly used for icons. You add the Font Awesome classes to the i element to turn it into an icon, for example: ...

I would either make it clear which tag to use or accept both tags. @FreeCodeCamp/issue-moderators thoughts?

**Comment by SaintPeter** [comment]
We might as well change it to `<em>` just so we'll stop getting these dang issues.

**Comment by raisedadead** [comment]
:+1: for changing to `<em>`
