### ISSUE TITLE
On FCC Course Map, Some of the course times are behind the course title.

### ISSUE THREAD

**Issue by HTMLNoob** [FreeCodeCamp/FreeCodeCamp#7513]
Some of the course times are behind the course title. 
Here is a screenshot of the problem.

![code](https://cloud.githubusercontent.com/assets/16970112/13720909/c201dfa2-e7db-11e5-96b7-f800fabc71b4.jpg)

I'm wondering if I could fix this problem.
Also, I'm using Firefox 44.0.2

**Comment by HTMLNoob** [comment]
You might have to zoom in to see the problem on certain screen sizes.

**Comment by raisedadead** [comment]
I haven't been able to reproduce this, but @hallaathrad can you have a look?

**Comment by HTMLNoob** [comment]
Also, I have tested this on Chrome(48.0.25) and Opera(35.0.20). The problem still persists. Could this be a problem with my screen size? ( I also made sure the fonts and other settings were returned to default)

**Comment by hallaathrad** [comment]
Thst does seem to be an issue with zooming. Just to confirm, @htmlnoob could you plesse rezoom to normal level (ctrl+0) and tell me if the problem is still there?

**Comment by HTMLNoob** [comment]
@hallaathrad Just did so, problem still exists, moreover, I also tested the problem on a different computer and the problem still exists. After using the developer console, it is a simple margin problem, but I'm not sure if other users can fix it, I will ask around the general chat to see if others see the problem.

**Comment by hallaathrad** [comment]
Let's see if these two changes fix it for you, @HTMLNoob.
@raisedadead I think it's due to an older version of the fonts/browser in what seems to be Windows XP (info missing from OP). Regardless of whether that's why or not, can you guys please check and make sure my PR does the trick?

**Comment by kekkerslawl** [comment]
Looks good on my browser. Zoomed to 200% and it doesn't overlap.

**Comment by hallaathrad** [comment]
:+1: @kekkerslawl @raisedadead !! :dancers:

**Comment by raisedadead** [comment]
@kekkerslawl Thanks a lot for confirming

**Comment by raisedadead** [comment]
@HTMLNoob please let us know when the changes reach main website in a couple of days!

**Comment by HTMLNoob** [comment]
Ok, thanks! Btw, @hallaathrad I do use Win XP so I believe you are correct with fonts
