### ISSUE TITLE
palindrome("0_0 (: /-\ :) 0-0") should return true. It's a bug.

### ISSUE THREAD

**Issue by ShenZQ** [FreeCodeCamp/FreeCodeCamp#7519]
Challenge [Check for Palindromes](http://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20tmpStr%20%3D%20str.replace(%2F%5B%5Cs%2C.!%3B%5D%2Fg%2C%22%22).toLowerCase().replace(%22-%22%2C%22_%22)%3B%0A%20%20var%20reStr%20%3D%20tmpStr.split(%22%22).reverse().join(%22%22)%3B%0A%20%20if%20(tmpStr%20%3D%3D%3D%20reStr)%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7Delse%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0A%0A%0Apalindrome(%22never-odd%20o_r%20even%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.116 Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var tmpStr = str.replace(/[\s,.!;]/g,"").toLowerCase().replace("-","_");
  var reStr = tmpStr.split("").reverse().join("");
  if (tmpStr === reStr){
    return true;
  }else{
    return false;
  }
}



palindrome("never-odd o_r even");

"0_0 (: /-\ :) 0-0" contains a escape symbol, so it  actually is "0_0 (: /- :) 0-0", it isn't a palindrome string.

**Comment by raisedadead** [comment]
> `"0_0 (: /-\ :) 0-0"` contains a escape symbol, so it  actually is `"0_0 (: /- :) 0-0"`, it isn't a palindrome string.

Agreed. It isn't until you remove all the symbols. 

Refer instructions:
> **Note**
> You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn  everything lower case in order to check for palindromes.

Bonus hint: This one is a trick question :wink: 

If you are still stuck please ask for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help)

**Comment by ShenZQ** [comment]
For passing this challenge, I must modify my code like this:
```
str.replace(/\W+|_/g,"")
```
But this is not the real intention. And when I am more in-depth, I find that I must process that pairs of symbol: "(" and ")", "<" and ">" , "{" and "}", "[" and "]". Oh, I would go nuts!

**Comment by raisedadead** [comment]
Lol yup! @ShenZQ I admit, I had to take two coffee's to solve this last test case! :sweat_smile:

**Comment by ShenZQ** [comment]
@raisedadead I wait for your code. Lol!

**Comment by kotrotko** [comment]
ahhahaha got it) cool
