### ISSUE TITLE
Is "green box" supposed to be typed twice?

### ISSUE THREAD

**Issue by mvoltron** [FreeCodeCamp/freecodecamp#752]
Challenge http://www.freecodecamp.com/challenges/waypoint-adjust-the-margin-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

See highlighted part of screen shot
![greenboxtwice](https://cloud.githubusercontent.com/assets/5934614/7895264/6fc20f2a-0648-11e5-8c90-71b20a77f8ba.png)

**Comment by QuincyLarson** [comment]
Nice catch. Thanks for submitting. I'll push a fix.
