### ISSUE TITLE
Links don't work in "Computer Basics: How the Internet Works"

### ISSUE THREAD

**Issue by aluzardo** [FreeCodeCamp/FreeCodeCamp#7522]
#### Issue Description
* The links are not working in "Computer Basics: How the Internet Works". Is impossible to click in the link, it is necessary copy and paste the url.

#### Steps To Reproduce
 
1. Go to http://www.freecodecamp.com/videos/computer-basics-how-the-internet-works
2. Try to click in the links of the description. `web.stanford.edu/class/msande91si/www-spr04/readings/week1/InternetWhitepaper.htm`

Actual: The link is working but you need copy and paste the url.
Expected: Access to the link only with one mouse click 
``` 
<a href="http://web.stanford.edu/class/msande91si/www-spr04/readings/week1/InternetWhitepaper.htm">web.stanford.edu/class/msande91si/www-spr04/readings/week1/InternetWhitepaper.htm</a> 
```

#### Browser Information
* Google Chrome, Version 48.0.2564.116 (64-bit)
* OSX El Capitan 10.11.3

#### Screenshot 
<img width="1438" alt="screen shot 2016-03-12 at 15 10 03" src="https://cloud.githubusercontent.com/assets/11529571/13723725/4322c55e-e865-11e5-9e79-e9420c7f618d.png">

**Comment by raisedadead** [comment]
@aluzardo Thanks for catching these!

**Comment by aluzardo** [comment]
Same issue in http://www.freecodecamp.com/videos/javascript-lingo-mdn-and-documentation

Maybe is in all Hikes with links in the description.

**Comment by alistermada** [comment]
I'll work on a fix for this.

**Comment by raisedadead** [comment]
@alistermada thanks! Please go ahead!
