### ISSUE TITLE
Stand in line challenge please help me.. i am not able to pass 3rd test case

### ISSUE THREAD

**Issue by akanksha31** [FreeCodeCamp/FreeCodeCamp#7524]
Challenge [Stand in Line](http://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20testArr.push(item)%3B%0A%20%20var%20shifted%3DtestArr.shift()%3B%0A%20%20return%20shifted%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(testArr%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item) {
  // Your code here
  testArr.push(item);
  var shifted=testArr.shift();
  return shifted;  // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by raisedadead** [comment]
@akanksha31 We are sorry Github issues are for bugs in site only.
Please ask for assistance in [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and Happy Coding!

**Comment by LeoRussus** [comment]
This is an issue, the code should work, in fact it does work, however the 3rd challenge is not completing

**Comment by akanksha31** [comment]
done sir i am supossed to use arr inside the function queue but instead i was using other variable

**Comment by raisedadead** [comment]
@LeoRussus 

If you check:
`function queue(`**arr**`, item)`
and
**testArr**`.push(item);`

**Comment by Sahadov** [comment]
function queue(arr, item) {
  // Your code here
 arr.push(item);
  var shifted=arr.shift();
  return shifted;  // Change this line
}
