### ISSUE TITLE
Weird cursor jumps

### ISSUE THREAD

**Issue by TheCodeJones** [FreeCodeCamp/FreeCodeCamp#7528]
Challenge [Use Spans for Inline Elements](http://www.freecodecamp.com/challenges/use-spans-for-inline-elements#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch2%20class%3D%22text-primary%20text-center%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%20%20%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22img-responsive%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%20%20%3Cimg%20src%3D%22http%3A%2F%2Fbit.ly%2Ffcc-running-cats%22%20class%3D%22img-responsive%22%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-primary%22%3ELike%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-info%22%3EInfo%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-4%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-danger%22%3EDelete%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%20%20%3Cul%3E%0A%20%20%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%20%20%3C%2Ful%3E%0A%20%20%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%20%20%3Col%3E%0A%20%20%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%20%20%3C%2Fol%3E%0A%20%20%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%20%20%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%20%20%3C%2Fform%3E%0A%3C%2Fdiv%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This issue has been going on for the last couple of challenges. The cursor jumps around when trying to start the challenge. I will click where I want to type. The cursor will be a few spaces back from where I clicked, so I try to type something. my input appears a line below where I clicked. Its not until I click, type something, and delete it that everything works as it should. Not a huge issue or anything, but distracting.

**Comment by Brayn7** [comment]
+1

**Comment by techtolentino** [comment]
Happens to me too.

**Comment by raisedadead** [comment]
@TheCodeJones @Brayn7 @techtolentino @Will-Campbell

Thanks for confirming this. Unfortunately I have not been able to reproduce this. Could you help us with below information to get started in resolving this:

1. **Location** : Where are you located (region) ?
2. Can you have any GIF recordings/Screenshots anything that can help us understand this better.
3. Can you check your console for any errors?
  - On your browser open the Dev Tools (Press <kbd>F12</kbd>) and go to the Console tab.
  - Refresh the page, and try to reproduce the error.
  - Post the screenshot of the console and network tabs.

Any other information that you could provide.

Sincere apologies for the inconvenience, and thanks for your patience and help in resolving this.

**Comment by SaintPeter** [comment]
This is a known issue with Code Mirror, the software we use to edit code for our challenges.  This occurs when there are long lines of code and they wrap.  There are supposed to be fixes in newer versions of Code Mirror.

Ref: https://github.com/codemirror/CodeMirror/issues/1862

**Comment by raisedadead** [comment]
@SaintPeter Thanks! So I guess we are blocked by this.

**Comment by hobohiggs** [comment]
+1

**Comment by allisonletts** [comment]
+1

**Comment by allisonletts** [comment]
This manifested for me as seemingly not being able to click or move the cursor (even using arrow keys) to the last line of my code.

**Comment by Kahldris** [comment]
So will this be fixed here soon if it's related to that Code Mirror bug?

I switched from my Surface to PC (where font size/scaling is all default) and tried all my browsers trying to fix it until I saw this thread.

I narrowed it down to occurring when the pre-filled code in the code box is long enough that a scroll bar is added (to the code box). Because it starts happening to me from "Add Placeholder Text to a Text Field" where the scroll bar appears. Just having lines of code that wrap don't seem to cause it because lines wrapped in the lessons prior to this one.

When the scroll bar is there I can't click certain parts of the code (on this stage it's very evident because I can't click where I need to to add the required code). The cursor jumps to some weird place instead. Arrow keys can't even get me where I need to go as mentioned above.

The easiest way I've found to get around this bug is just to click somewhere it lets me and hit the spacebar so I've typed something... then I can correctly click anywhere in the code.

It's not a show stopper, easy to get around, but between this and #3204 I've lost a couple hours on bugs in this code editor and I'm not very far in. I'm a bit worried of what's to come.

**Comment by BerkeleyTrue** [comment]
Please follow the codemirror issue here https://github.com/codemirror/CodeMirror/issues/1862

**Comment by KittSmith** [comment]
@Kahldris thank you for mentioning how you get around it. I didn't think to try anything like that.

**Comment by abbenilsson** [comment]
+1

**Comment by smartestprimate** [comment]
Tried @Kahldris suggestion of zooming in and out (ctrl + "+", ctrl + "0") as a temporary fix which allowed me to get past this.

**Comment by Gotchuonlock** [comment]
Started on "Use Spans for Inline Elements". It skips over the text that I need to edit to move on . . . can't do anything about it.

**Comment by Gotchuonlock** [comment]
@smartestprimate  worked for me too, thanks!

**Comment by JpTiger** [comment]
+1

**Comment by caene** [comment]
This issue is still a thing, apparently.
