### ISSUE TITLE
Challenge: No Repeats Please

### ISSUE THREAD

**Issue by someonefromcanada38** [FreeCodeCamp/FreeCodeCamp#7530]
After looking into the documentation provided on this problem thoroughly, I've realized it does not handle anything similar to what this problem is asking for. Although it gives a basic understanding of permutations it does not give a full enough understanding to create an algorithm that requires a strong understanding of the concept, and building on that concept to create a new algorithm. I believe this problem requires too much math and not enough programming to be effective for the purpose of teaching programming. A brute force approach to this problem is also simply incorrect, which again diminishes any potential gains a student could get from the problem. Various other sources use no repeating combinations for instance abb + aba + baa would be counted once each. There is an algorithm for that, it does not require learning an entire math concept in order to create an efficient function to do its purpose.

**Comment by tamer4cross** [comment]
I am stuck on this 
tried to watch several videos on permutations/ combinations, yet I am unable to pass this 
what should I do ?
