### ISSUE TITLE
Instruction improvement for Declare JavaScript Variables challenge

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#7531]
#### Instruction Improvement needed for **Declare JavaScript Variables** challenge
**Challenge URL:** [**`Declare JavaScript Variables`**](http://www.freecodecamp.com/challenges/declare-javascript-variables)

The following instruction is ambiguous and confusing.

> Variables allow computers to store data in a dynamic fashion, rather than **updating a formula every time the data changes**. Any of the seven different data types may be stored in a variable.

#### Wanna contribute to FreeCodeCamp?
**Repo file:** [**`basic-javascript.json#L51`**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L51)

> ----
<p align="center">Read <a href="https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines <br>Chat with us about <br><kbd><a href="https://gitter.im/FreeCodeCamp/CurriculumDevelopment"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>Curriculum Development</b></a></kbd> and <kbd><a href="https://gitter.im/FreeCodeCamp/HelpContributors"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>Getting Started Contributing</b></a></p>

> ----

**Comment by erictleung** [comment]
One change that could be made is:

> Variables allow computers to store **and manipulate** data in a dynamic fashion. **They do this by using a "label" to point to the data rather than using the data itself**. Any of the seven different data types may be stored in a variable.
