### ISSUE TITLE
French translation of Responsive Design with Bootstrap

### ISSUE THREAD

**Issue by N0bl3** [FreeCodeCamp/FreeCodeCamp#7532]
Just starting translating the Bootstrap part of the curriculum.

**Comment by N0bl3** [comment]
If you want to work on it too or watch as it improves, here's the link:
[Repo](https://github.com/N0bl3/FreeCodeCamp)

**Comment by raisedadead** [comment]
CC : @vtamara

**Comment by N0bl3** [comment]
Translated : 
From first challenge to "Create a Custom Heading". It's 12 challeges for now.

**Comment by N0bl3** [comment]
I translated all the Bootstrap challenges.
It might need reviewing.
