### ISSUE TITLE
This question has an answer that can be easily copy and pasted.

### ISSUE THREAD

**Issue by HTMLNoob** [FreeCodeCamp/FreeCodeCamp#7537]
Challenge [Reverse a String](http://www.freecodecamp.com/challenges/reverse-a-string#?solution=function%20reverseString(str)%20%7B%0A%20%20str%20%3D%20str.split(%27%27).reverse().join(%22%22)%3B%0A%20%20return%20str%3B%0A%7D%0A%0AreverseString(%22hello%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function reverseString(str) {
  str = str.split('').reverse().join("");
  return str;
}

reverseString("hello");

```
The link [String.split()] goes to MDN, now if you go to that link and scroll to the last string.split example, it shows you how to reverse a string, and that example can easily be copy and pasted. 

Though I'm not sure whether this was intended, I thought I might as well tell you guys.

**Comment by HTMLNoob** [comment]
Though this is admittedly not as informative and as useful as MDN, here is a W3schools tutorial on string.split.

http://www.w3schools.com/jsref/jsref_split.asp

**Comment by HTMLNoob** [comment]
Moreover, the MDN example also provides a palindrome solution that can also be implemented for the 'Test for palindrome' example.

**Comment by raisedadead** [comment]
@HTMLNoob People could always GOOGLE these solutions anyways. 
IMHO, keeping checks for specific solutions is NOT a good way to tackle this. 

At the end of the day, its up to the camper to learn a concept by following the instructions honestly. And I am 100% sure that any one interested in copy-pasting solutions will NOT learn it.
So there is no knowledge to gain in that case. A camper might skip the challenge as well in that case.

Won't you agree?

To best of my understanding these challenges are typically intended for teaching some of the basic concepts.
Closing this. 

Please feel free to comment, if you would like to have an alternate proposal, we can always re-open this!

Thanks and happy coding!
