### ISSUE TITLE
//noprotect in Chrome - FIX

### ISSUE THREAD

**Issue by stomperstomp** [FreeCodeCamp/FreeCodeCamp#7539]
Challenge [Iterate Odd Numbers With a For Loop](http://www.freecodecamp.com/challenges/iterate-odd-numbers-with-a-for-loop) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = [];

for (var i = 0; i < 10; i += 2) {
  ourArray.push(i);
}

// Setup
var myArray = [];

// Only change code below this line.

for (var t = 1; t < 10; t += 2){
  myArray.push(t);
}
```

If you do put //noprotect in the code and it crashes your browser (Chrome in my case) it will constantly crash if you refresh the page. The solution is to clear your browser history and cache to start over.

**Comment by ltegman** [comment]
@stomperstomp That would typically mean there's an infinite loop in your code. However, I'm not able to reproduce this error with the code you provided. This is the exact code that was causing your browser to crash?

**Comment by stomperstomp** [comment]
I added "//noprotect" beside myArray.push(t);

Once added it allows the infinite loops and crashes the server, and it's almost impossible to remove it and correct the code. The only way to clear cookies/cache.

There should be an intercept that allows a user to remove that snippet - //noprotect

**Comment by ltegman** [comment]
The reason we have loopProtect is to prevent just that problem. If you go out of your way to disable it you are accepting the risk that an infinite loop may crash your browser. Clearing your cache or [Disabling Code Auto-run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) are the way to fix this problem if you run into it. Thanks and happy coding!
