### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by NorCalMike** [FreeCodeCamp/freecodecamp#754]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
In the instructions it says  You should add a _class=fa fa-thumbs-up_ within your like button element
Because of the way it prints on my screen it was very difficult to see the space. 
![image](https://cloud.githubusercontent.com/assets/5025997/7895312/a8290e1c-063a-11e5-81fd-ba687cff8c49.png)

**Comment by QuincyLarson** [comment]
Thank you for pointing this out. I've reworded the text and the challenge to make this more clear.
