### ISSUE TITLE
Suggestion: External links in non-English challenges direct to translated version if available

### ISSUE THREAD

**Issue by alistermada** [FreeCodeCamp/FreeCodeCamp#7540]
There are Wikipedia and MDN links in the challenges that have translations available. The Spanish version of the challenges, for example, could link to the Spanish version of the pages instead of the default English ones.

**Comment by kaunglay** [comment]
#7540

**Comment by kaunglay** [comment]
#7540

**Comment by kaunglay** [comment]
#7540

**Comment by kaunglay** [comment]
#7540
