### ISSUE TITLE
Video challenge title tag says Hikes

### ISSUE THREAD

**Issue by alistermada** [FreeCodeCamp/FreeCodeCamp#7541]
![image](https://cloud.githubusercontent.com/assets/12993334/13732691/cf7bd97c-e9ba-11e5-8fee-86e515913f6b.png)

Should be the name of the challenge like in other types of challenges.

**Comment by raisedadead** [comment]
@alistermada Thanks.

The other challenges show up the challenge name as the title:

![1](https://cloud.githubusercontent.com/assets/1884376/13748512/218817b8-ea23-11e5-9c7e-a1a3a84750d0.png)

I believe we could change these to similar.

**Comment by Jago-Kosolosky** [comment]
Correct me if I'm wrong but this would mean that in FreeCodeCamp\server\views\partials meta.jade {title} is not filled up with the right value? I can't find out how it's picking up 'Hikes' though... Help welcome!

**Comment by alistermada** [comment]
@Jago-Kosolosky It may be getting 'Hikes' from `FreeCodeCamp/common/app/routes/Hikes/components/Hikes.jsx` in line 50: `updateTitle('Hikes');`.

All I know is that unlike the other challenges, the video challenges are loaded with React.

**Comment by theflametrooper** [comment]
Let me try and figure this one out..
