### ISSUE TITLE
In the 92th step of the map,there is a bug.$("button").prop("disabled", true);double quote missed of the “ture”.

### ISSUE THREAD

**Issue by xiajjing** [FreeCodeCamp/FreeCodeCamp#7544]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by alistermada** [comment]
Are you talking about [Disable an Element Using jQuery](http://www.freecodecamp.com/challenges/disable-an-element-using-jquery) ? 

`true` is a Boolean, not a string, so it does not need quotes. `$("button").prop("disabled", true)` is valid code.

**Comment by AkiraLaine** [comment]
Closing this as it's not and issue
