### ISSUE TITLE
Steamroller Challenge Page Unresponsive

### ISSUE THREAD

**Issue by emauser2** [FreeCodeCamp/FreeCodeCamp#7545]
The steamroller challenge page is unresponsive as soon as I open it. I am wondering if it has anything to do with the code that I have typed in there. I have attached a screenshot of the code. Please let me know how I can fix this, as it is preventing me from working on the challenge.
![fcc](https://cloud.githubusercontent.com/assets/16654992/13747065/d99c10c2-e9cc-11e5-87e3-11d2d70a6076.PNG)

**Comment by ltegman** [comment]
Looks like you have an infinite loop you can either [Disable Code Auto-run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) or [remove your code from localStorage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage). Thanks and happy coding!
