### ISSUE TITLE
Unclear error message.

### ISSUE THREAD

**Issue by eliatlas** [FreeCodeCamp/FreeCodeCamp#7546]
Challenge [Change the Font Size of an Element](http://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
When removing class atribute from both p elements, one of the tests is not passing, and the error is:
> Do not add a class attribute to the second p element, without removing it from the first 
> one.

The description is misleading.
I think better say something like:
> Do not add a class attribute to the second p element.
> First p element should have a class attribute and it's content should remain red.

**Comment by Skittles314** [comment]
I also couldn't figure this error out, just due to poor wording. It was unclear that the first p was supposed to be red text as well. My code was correct except I did not understand that it needed to be red in addition to h2.

**Comment by pawan92** [comment]
is this available? can i help out?

**Comment by erictleung** [comment]
PR #8101 fixes this issue. If it is still unclear, please comment. Otherwise, happy coding!
