### ISSUE TITLE
Generally buggy

### ISSUE THREAD

**Issue by mvoltron** [FreeCodeCamp/freecodecamp#755]
Challenge http://www.freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

There are several bugs on this page; the first is that the text at the top is a little confusing; also the green check marks come before several things that need to be completed are completed.  I suggest just going through it and checking it out.

**Comment by QuincyLarson** [comment]
Thank you for the feedback. I've cleaned it up a bit.
