### ISSUE TITLE
"Stand In Line"

### ISSUE THREAD

**Issue by jacob1324756** [FreeCodeCamp/FreeCodeCamp#7550]
I JUST CANT DO IT

**Comment by MesyMacos** [comment]
@jacob1324756  Don't give up yet; Use the Read Search Method; I couldn't do this too for awhile. Finally did it now.

**Comment by jacob1324756** [comment]
what is the Read Search Method

**Comment by jacob1324756** [comment]
?

**Comment by mdelgadonyc** [comment]
@jacob1324756 The method that @MesyMacos is referring to is outlined in the brief FreeCodeCamp (FCC) Wiki document ["How to get help when you get stuck"](https://freecodecamp.github.io/wiki/en/How-to-get-help-when-you-get-stuck/).

It basically recommends that the person:


> When you get stuck, remember: Read-Search-Ask.
>
> 1. Read the documentation or error
> 2. Search Google
> 3. Ask your friends for help

There are a few extra tips and examples if you check out the [document](https://freecodecamp.github.io/wiki/en/How-to-get-help-when-you-get-stuck/).

-Moisés

**Comment by sludge256** [comment]
Ask in the relevant help chat if you need to. In this case, https://gitter.im/FreeCodeCamp/HelpJavaScript

**Comment by islq** [comment]
there is a typo error:

After queue(testArr, 10), myArr[4] should be 10

myArr => testArr

**Comment by raisedadead** [comment]
@islq Its known and fixed in #7615

**Comment by juniorveasy** [comment]
I don't understand how i'm supposed to go about fulfilling the requirements. With queue being new, how am I to know how to resolve the matter without a prior lesson?
