### ISSUE TITLE
Issue with Sort Arrays with sort challenge (Object Oriented and Functional Programming)

### ISSUE THREAD

**Issue by Hellano** [FreeCodeCamp/FreeCodeCamp#7552]
#### Browser Information
* Google Chrome, Versão 48.0.2564.116 m
* Windows 10

#### Issue Description
* This issue happens in [Sort Arrays with sort (Object Oriented and Functional Programming)](http://www.freecodecamp.com/challenges/sort-arrays-with-sort#?solution=var%20array%20%3D%20%5B1%2C%2012%2C%2021%2C%202%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Aarray.sort(function(a%2C%20b)%20%7B%0A%20%20return%20a%20-%20b%3B%0A%7D)%3B%0A%0Aarray.sort()%3B%0A)
* When you click on Run tests button, the result provided for the example is not correct.

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/4286567/13757051/7965e356-ea01-11e5-90b3-18fc5c912f70.png)

**The result should be: [1, 2, 12, 21]**, This can be checked in [this example](http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_sort2).

#### Your Code
* The solution to the challenge should be the code below, but it seems that the sort method is not considering any callback function as parameter and sorting alphabetically.
```js
var array = [1, 12, 21, 2];

array.sort(function(a, b) {
  return b - a;
});

array.sort();
```

**Comment by ltegman** [comment]
This is not an issue with the challenge. Your code is incorrect. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help. Thanks and happy coding!

**Comment by Hellano** [comment]
The challenge description say: 

> Here is an example of using sort with a compare function that will sort the elements from smallest to largest number:
```js
var array = [1, 12, 21, 2];
array.sort(function(a, b) {
  return a - b;
});
```
But when I click on Run tests button the result is: [1,12,2,21].
This isn't sorting the elements from smallest to largest number.

am i missing something?

**Comment by ltegman** [comment]
@Hellano You called sort again after that without the right sorting callback.

**Comment by Hellano** [comment]
My bad, you're right, thank you!

**Comment by djsirena** [comment]
array.sort(function(a, b) {
  return b - a;           
});

caffeine helped with this. =)
