### ISSUE TITLE
convert-json-data-to-html rejects working answer

### ISSUE THREAD

**Issue by bguiz** [FreeCodeCamp/FreeCodeCamp#7557]
#### Issue Description
- Code does what it is supposed to do
- But the test that verifies it doesn't seems to work
- To reproduce, simply enter the code snippet below
- The error you get is: "The message box should have something in it."
- The message box certainly does have something in it
#### Browser Information
- Firefox
- Linux
#### Your Code

``` js
html = json.map(function(val) {
          return "<div class = 'cat'>"+
            Object.keys(val).map(function(key) {
              return "<b>"+key+"</b>: "+ val[key]+"<br>";
            })+
            '</div><br>';
        }).join('');
```

**Comment by alistermada** [comment]
Found the problem in the source code: All the test does is look for `json.forEach` in your code.

I also want to point out that this challenge can be easily solved by copy+pasting the code in the instructions. A lot of folks might just breeze through this without thinking about what's going on.

**Comment by PolakAllen** [comment]
I experienced this as well. Here's my solution (I ended up just copy pasting when my solution didn't work)

```
        html = json.map(function(item) {
          return '<div class="cat">' + 
             Object.keys(item).reduce(function(acc, key) {
               acc.push("<b>"+key+"</b>: " + item[key] + "<br/>");
               return acc;
             }, []).join('') +
          '</div><br/>';
        }).join('');
```

**Comment by raisedadead** [comment]
Closing as decayed.
