### ISSUE TITLE
Accessing Nested Arrays in JSON - Example should match challenge

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#7559]
Challenge ~~[Accessing Nested Objects in JSON](http://www.freecodecamp.com/challenges/accessing-nested-objects-in-json)~~ [Accessing Nested Arrays in JSON](http://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json)-
The example code does match the actual challenge very closely, which causes questions.

The example should be updated to be Array->Object->Array.

**Updated: ** corrected challenge name.

**Comment by paycoguy** [comment]
I would like to work on this as my first contribution

**Comment by erictleung** [comment]
@paycoguy Take a look at the [contributing guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to get started. There's also the [Help Contributors Gitter page](https://gitter.im/FreeCodeCamp/CurriculumDevelopment) if you need help. Good luck!

**Comment by paycoguy** [comment]
Is this issue supposed to reference [Accessing Nested Arrays in JSON](http://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json) instead?  The Array->Object->Array"= reference makes more sense to me on the Accessing Nested Arrays in JSON challenge.

**Comment by SaintPeter** [comment]
You are correct:
http://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json

The one with "myPlants" - the example does not match the challenge.
