### ISSUE TITLE
More Gen Bugs

### ISSUE THREAD

**Issue by mvoltron** [FreeCodeCamp/freecodecamp#756]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-custom-heading has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hi Guys, you probably know there are some common bugs in the code, so I won't keep mentioning the same one, but what I'm noticing is that if certain changes are made, i.e. if code is added but not in the right place and it doesn't create the right effect in the phone app, you still get a green check mark.

**Comment by QuincyLarson** [comment]
Thanks for pointing this out. It would be tricky to locate elements relative to other elements, and this would introduce an unforgiving rigidity.
