### ISSUE TITLE
Unable to github login from a specific computer

### ISSUE THREAD

**Issue by samk64** [FreeCodeCamp/FreeCodeCamp#7560]
Hi guys,

I've been looking for a way to learn web development and have really been enjoying the material you guys have put together, so thank you. 

I have a login issue I can't figure out and didn't see a duplicate looking through the issues.
#### Issue Description
- When I login with github from my mac mini on any browser, it does not work. I get a red error saying `Oops! Something went wrong. Please try again later`. I get redirected back to http://www.freecodecamp.com/map, and I'm not logged in.

Things I have tried on the mac mini:
- Github login after hard refresh / clearing all of the browser cache
- Github login on Firefox, Safari, Chrome
- Github login in private browsing mode (all browsers)

But the weird thing is, I can successfully use github to login with 3 other computers:
- Acer Chromebook (ChromeOS 48.0.2564.116 (64-bit))
- Macbook Pro (OSX El Capitan)
- Thinkpad (Ubuntu 14.04)
#### Browser Information (mac mini)
- Firefox 43.0.4
- Chrome 49.0.2623.87 (64-bit)
- Safari 9.0.3 (11601.4.4)
- OS: OSX El Capitan 10.11.3 (15D21)
#### Screenshot
- **Login Error (mac mini)**
  ![login_error](https://cloud.githubusercontent.com/assets/9358742/13768004/1e66eb06-ea3f-11e5-8788-04e22b6ae95e.png)
- **Login Success (thinkpad ubuntu)**
  ![login_success](https://cloud.githubusercontent.com/assets/9358742/13768200/2fce0512-ea41-11e5-80ce-c123351b5528.png)
#### Other Information

I have HAR files of logging in using the mac mini (error) and chromebook (success) for the GET requests of:
- GET github
- GET authorize?response_type=code&redirect_uri...
- GET callback?code=...
- (mac mini, error) GET map
- (others, success) GET trigger-click-events-with-jquery

I can share a link to these files to you privately, but I would rather not post them here in case the files have my cookie information, and they're a bit big (12 MB total).

**Comment by raisedadead** [comment]
Hi @samk64 Apologies for the inconvenience you have been facing. We have lately had some reports to similar login issues, but yours seems a bit different with a specific device as you mention.

We will keep you posted on this via this thread, however please note that it might be a while, before we can find someone with the same specific device to reproduce and analyse the error. 

Thanking you for your patience in the meantime.

**Comment by BerkeleyTrue** [comment]
Has anyone else replicated?

**Comment by 3316** [comment]
This is not me. I do not or have ever owned a mini Mac. Please take off.

**Comment by sludge256** [comment]
@3316 Please visit this link and change your settings accordingly https://github.com/settings/notifications

**Comment by sic-f** [comment]
same problem i'm experiencing posted above by sludge256

**Comment by sludge256** [comment]
@samk64 is this still occurring?

**Comment by samk64** [comment]
Hi @sludge256, yes I just tried and still have the same issue.

**Comment by raisedadead** [comment]
Closing as decayed, let us know if this persists.

**Comment by samk64** [comment]
Just for the record, I tried logging in today and the issue is gone. Thanks for all of your help.
