### ISSUE TITLE
Comparisons with the Logical Or Operator

### ISSUE THREAD

**Issue by hadyanzon** [FreeCodeCamp/FreeCodeCamp#7563]
Challenge [Comparisons with the Logical Or Operator](http://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=function%20myTest(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3E%2010%20%7C%7C%20val%20%3C%2020)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  // Only change code below this line

  if (val > 10 || val < 20) {
    return "Outside";
  
  }
  // Only change code above this line
  return "Inside";
}


// Change this value to test
myTest(10);

```
I think this right answer please help me if wrongyou can give me clue solve this challege

**Comment by drk7891** [comment]
Your if statement should be checking if `val` is **not** between 10 and 20

Please check out the help channel on gitter at https://gitter.im/FreeCodeCamp/FreeCodeCamp before posting here as this is for bugs

**Comment by cannelflow** [comment]
instruction says  if val is not between 10 and 20,  means number leas then 10 or number greater then 20 and you are checking number between 10 to 20 Please use FCC chat room https://gitter.im/FreeCodeCamp/Help Before posting Here

**Comment by raisedadead** [comment]
@drk7891 @cannelflow Thanks!
