### ISSUE TITLE
Poorly explained, confusing on what to answer

### ISSUE THREAD

**Issue by gpressman** [FreeCodeCamp/FreeCodeCamp#7570]
Challenge [Selecting from many options with Switch Statements](http://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch%20(val)%7B%0A%20%20%20%20case%201%3A%0A%20%20%20%20%20%20answer%20%3D%20%22alpha%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%202%3A%0A%20%20%20%20%20%20answer%20%3D%20%22beta%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%203%3A%0A%20%20%20%20%20%20answer%20%3D%20%22gamma%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%204%3A%0A%20%20%20%20%20%20answer%20%3D%20%22delta%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

There's no real "bug" here, just switch statements aren't well explained and what it's looking for in terms of an answer is kind of confusing.

**Comment by N0bl3** [comment]
You could use regExp to filter the answer and also ask specifically for the client/ip/whatever using a lib like express-useragent.
Add "express-useragent": "^0.2.4" to your dependencies in your package.json and npm install.
In your code require the module and use it.

This is just two ways of doing the job.

**Comment by 3316** [comment]
This is not me. do not own a Mac

**Comment by N0bl3** [comment]
My excuses! I was thinking of a back end challenge !

**Comment by rfprod** [comment]
Adding a [helpful link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch) may help with switch statements explanation. Also, this may eliminate confusion, because task is stated quite clearly if one understands what is a switch statement. If still confused what answers are correct, press Ctrl+Enter to invoke current solution testing.

**Comment by raisedadead** [comment]
@rfprod Agreed. Would you like to put up a PR?

**Comment by rfprod** [comment]
@raisedadead sorry, not now, busy building book trading club.

**Comment by michaelkro** [comment]
I am a first-timer and would like to help out with this issue.  If I am understanding @rforod correctly, we want to add a link to the MDN switch article and add a line to the instructions saying to press Ctrl + Enter to see what is being tested for?

**Comment by raisedadead** [comment]
@michaelkro Yup that is correct, you need to add a hint link, in this challenge. Should you need any help please ping us in the [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room.

Here are the [contribution guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), for this repo.

Happy fixing!
