### ISSUE TITLE
Issue on page- 151: Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by ChethanAshwathaReddy** [FreeCodeCamp/FreeCodeCamp#7574]
#### Issue Description
* As per the description of test case, below combination cannot be achieved. Please assist have added the code.

Only add one class with each of your three selectors.
Your #target1 element should have the classes animated‚ shake and btn-primary.
Only use jQuery to add these classes to the element.

#### Browser Information
* Chrome,48.0.2564.116 m (64-bit)
* Windows 8.1

#### Your Code

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("animated");
    $("#target1").addclass("animated shake btn-primary");
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by raisedadead** [comment]
@ChethanAshwathaReddy The instructions and the tests are valid.

It is possible to add all the classes to same element, with different selectors. 
Please visit our [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you are stuck.

Closing as not a site issue.
