### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by DrineTN** [FreeCodeCamp/FreeCodeCamp#7575]
Challenge [Prioritize One Style Over Another](http://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20pink-text%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  pink-text{
    color: pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by CullenIO** [comment]
Please check the FreeCodeCamp chat before posting here. ☺
The problem is that in the style tags, "pink-text" has no dot (.) before it. This is the class selector.

**Comment by raisedadead** [comment]
@CullenIO Thanks.

@DrineTN Github Issues are not for Code Help, please follow our guidelines and seek assistance in the [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Thanks and Happy Coding!

**Comment by DrineTN** [comment]
Okey Thanks :+1:
