### ISSUE TITLE
The attribute is giving much trouble pls repair it

### ISSUE THREAD

**Issue by dexter123233** [FreeCodeCamp/FreeCodeCamp#7577]
Challenge [Prioritize One Style Over Another](http://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%7Bcolor%3Apink%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text{color:pink}
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by samuelbeard** [comment]
It seems that in order for the second objective (Your <style> should have a pink-text CSS class with its color set to pink.) to complete, the code needs to be written on multiple lines.


```
.pink-text{
    color:pink;
  }
```

**Comment by samuelbeard** [comment]
It seems that in order for the second objective (Your should have a pink-text CSS class with its color set to pink.) to complete, the code needs to be written on multiple lines.

```
.pink-text {
  color:pink;
}
```

**Comment by raisedadead** [comment]
@samuelbeard thanks. 

the single line CSS is still valid `.pink-text{color:pink}`

@dexter123233 Your code is not correct completely. 
While I agree a skipping semi colon `;` is okay in most browsers, its essential and recommended  that you keep adding a `;` as a good coding practice.

That's why the test fails.

**Comment by dexter123233** [comment]
Yeah tq both!
