### ISSUE TITLE
how-to-npm issues are mostly human error compounded by an annoying bug

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/freecodecamp#758]
Challenge http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm.

The dist-tag bug in how-to-npm 2.0.0 is trivial if you know the cause and how to deal with it. The bug is actually triggered entirely by human error: e.g., if you try to add or remove an invalid dist-tag, 403 or 404 errors will begin to accumulate. The tutorial should have delivered a descriptive error message in these cases.

If at any point you see a 403 or 404 error your only recourse is to run `how-to-npm` again, and in some cases you may need to repeat a prior step.

Here are some common causes for these errors;

1. Try not to use commands out of sequence. For example, avoid using `npm publish` on steps that do not ask you to publish. Even if you enter a valid npm command, the tutorial will often break if you do things it isn't expecting for a given test. If you need to repeat a command, you may be better off returning to the relevant test before picking up at your current step.
2. `npm version` should be followed by a version number (e.g., 1.0.2) or by a keyword indicating a semver type (e.g., 'patch'). See `npm help version` for examples. (You may also set the version number manually in package.json, but `npm version` works if you understand the syntax.)
3. You can not change the `dist-tag` of the version tagged `latest` until you've assigned `latest` to a different version.
4. `dist-tags` can not be added to a version number beyond the highest existing version. For example, if you've set  and published version 2.0.0, you can not add a dist-tag to 2.0.1.
5. Finally, if you set `latest` to a low number (e.g., 0.0.1) you're eliminating or vastly reducing the available version numbers to which you can assign dist-tags.

Any of these (and more like them) will cause 403 or 404 errors and will require users to step back, rerun `how-to-npm`, and be careful not to repeat mistakes.

**Comment by QuincyLarson** [comment]
@denmch and I had an extensive discussion about this in Slack, and we've updated the challenge. I'm closing this issue. Huge thanks to @denmch for isolating these issues and synthesizing clear simple work arounds for our campers!

**Comment by Philosophist** [comment]
The problem with this entire set is that it's designed to teach by guessing. Please make simple and clear instructions in a tutorial. Don't TRY to fool students by leaving the solution out of the lesson. The I still don't know how to tell the name of my package or what the function of a package or dependency actually is.

**Comment by noates** [comment]
The how-to-npm should not list steps as "Completed"...   if things have been broken inside that will make further steps impossible. 

 I wish someone could post actual working commands. I wish I knew where the clear, simple workarounds are posted.  I should have looked elsewhere for more informative npm information before wasting so much time on this challenge.

**Comment by kaym0** [comment]
This is actually ridiculous and I cannot pass it no matter what I have done. I skipped the entire challenge after it would NOT work the 1000 different things I tried, I have spent 3 hours on this.

**Comment by kaym0** [comment]
I can usually build a lightweight site and code it in less than 3 hours. This is probably the longest I've EVER spent on something and especially without reward. I have completed almost the entire front-end certification and have never run into something so impossibly stupid.

**Comment by kaym0** [comment]
Also, how-to-npm verify skip  DOES NOT WORK.

**Comment by kaym0** [comment]
I don't think I have been angry like this since I had a mentally ill girlfriend who would blame things that she made up in her head on me. That's how fucking irrational this is.

**Comment by QuincyLarson** [comment]
@kaym0 yes - this Node School module is seriously broken. We are working on a replacement for it - something that would run on top of HyperDev (instead of the command line) and would not involve a lot of package creation-specific tasks (that you can learn if and when you choose to create npm packages yourself). 

Would you be interested in helping us design a replacement?

**Comment by Philosophist** [comment]
Thank you Quincy for being on this. I am willing to help with the questions
that a novice would ask given that I am one. I've put off FreeCodeCamp for
months because of this blockade. Had some help try to clarify for me, but
it's still something over my head as a concept. Regardless, you've been
awesome with leading this resource. If you could use my help, please let me
know.

-Steve

**Comment by QuincyLarson** [comment]
@Philosophist Thanks for your kind words. Sad to hear that this has blocked you. Yes - we will work to replace these challenges. I will talk with the core team and create some issues. We are coordinating our curriculum expansion here, so feel free to dive in and contribute:  https://github.com/FreeCodeCamp/CurriculumExpansion/

**Comment by kaym0** [comment]
@QuincyLarson I would love to help, but I'm not sure if I have the technical capacity to do so.

**Comment by kaym0** [comment]
@QuincyLarson Although, let me know what you need done and I will see if I can help!

**Comment by kaym0** [comment]
@QuincyLarson Didn't notice the Git link above. Have saved it and I will look at it shortly! In the mean time, what will we miss out by not actually completing the 'how-to-npm dist-tag' and the few challenges beyond it? Would it be safe to move forward and come back to finish that after the fix has been made?

**Comment by QuincyLarson** [comment]
@kaym0 honestly, you won't miss much. Most of the generally applicable npm knowledge is at the beginning of that challenge. I recommend you keep on moving forward.

**Comment by yeongren** [comment]
@QuincyLarson 
Thanks. Looking forward to the replacement curriculum.

**Comment by oppositive** [comment]
@QuincyLarson I'm confused. "Manage Packages with npm" looks like a normal challenge (if such a challenge even exists :-) ). I can't get through it without a bunch of errors however. If there's still something seriously wrong with how-to-npm then shouldn't people be warned about it inside the FCC challenge. I would like to contribute...

**Comment by QuincyLarson** [comment]
@oppositive if things go well, we will replace these Node School challenges completely within the next week or so. But if you want to dig in and figure out which how to npm challenges have issues and produce a list we could update it.

**Comment by olddognewtrix123** [comment]
Hi, everyone. I have spent my morning trying to very carefully get around step 11 but I keep getting a 404 error.  I go back and repeat steps 09 and 10, but still get the 404. I have deleted the directory and started a new one, carefully repeated the steps, and still get the 404, even after once again repeating steps 9 and 10 and always using the next to most recent version # (if current version is 3.00.00, I attach a dist tag to 2.00.00, for example)

       {
         "name": "@newuser/fcc01",
         "version": "3.0.0",
         "description": "this is a test",
         "main": "0",
        "sc....

     olddognewtrix123:~/workspace/fcc01 $ npm dist-tag add fcc01@2.0.0 [beta]
     npm ERR! Linux 4.2.0-c9
     npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/node"         "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/npm" "dist-tag" "add" "fcc01@2.0.0" "[beta]"
     npm ERR! node v4.6.1
     npm ERR! npm  v4.0.2
     npm ERR! code E404

    npm ERR! 404 missing : -/package/fcc01/dist-tags

**Comment by davidpickup** [comment]
I get the same errors as @olddognewtrix123. All my previous challenges are "COMPLETED", but trying to add a dist-tag just doesn't work.

**Comment by sonichanxiao** [comment]
Finally got work. 

It seems when you create a project, in the name give something like "@username/packagename". And before you add a tag, try to use npm dist-tag ls to see what tags are there first.

But still want the author to update the instructions, get some newbie to test the steps and update. It will save a lot of time for many people.

**Comment by jjarocewicz** [comment]
I continue to get a 404 when trying to point latest to a different version.  Please supply better instructions on this step.  I've tried googling and referring to npm documentation, with no luck.  Please advise or revise.

**Comment by olddognewtrix123** [comment]
I took a few (geeze, a lot actually) months of from FCC just to build some
games and sharpen my coding skills in other areas. Now I'm circling back to
FCC and need to complete the rest of the Node projects so I can get the
back end cert.

That said, I'm completely ignoring those how-to-npm tutorials. Instead, I'm
plowing through the Net Ninja video tutorials on youtube. That should get
me to a point where I can build the required stuff for FCC without hassling
with a poorly written tutorial.

Take away: there's lots of other really great sources to learn node js.
Don't kill yourself with a crappy tutorial.  Find something that works for
you.

On Jul 14, 2017 2:49 PM, "Julie" <notifications@github.com> wrote:

I continue to get a 404 when trying to point latest to a different version.
Please supply better instructions on this step. I've tried googling and
referring to npm documentation, with no luck. Please advise or revise.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/758#issuecomment-315437119>,
or mute the thread

**Comment by thenerdywiz** [comment]
I guess I'm having the same problems with npm dist-tag add <pkg> <tag> and have tried several workarounds. Can you give us credit for this tutorial if we make it through 10? When are you guys gonna update or fix this?

**Comment by QuincyLarson** [comment]
@thenerdywiz We are removing the Node School challenges completely in favor of our own challenges. These are in the beta curriculum: beta.freecodecamp.com/map

**Comment by thenerdywiz** [comment]
Hi Quincy...I'm sorry to pester you but I'm now having some problems with the beta curriculum. I have setup my account with Glitch and somewhat understand its workings. However, the "show live your app" opens a page with just '**Manage Node.js projects and npm packages using package.json
Part 1 of Free Code Camp Backend Challenges**' and a grey screen. What's worse is that the beta fcc is not letting me get going even though I have a valid key inside my package.json file? I checked the logs and I'm not getting any errors? Can you help me out please?

**Comment by QuincyLarson** [comment]
@thenerdywiz It sounds like you may have identified a bug. Can you take some screenshots and create a separate issue for this?

**Comment by che2901** [comment]
As I get it ,to start Back End I have to go straight to beta challenges and skip Node School challenges.
Am I right?

**Comment by Knowledge-Wisdom-Understanding** [comment]
i got it to work after about an hour of frustration and it was an AHA moment. here is my solution,
npm dist-tag add @yourname/yourfilename@1.0.1 beta

p.s. your name and file name have to be all lowercase. for instance, mine looked exactly like this:
npm dist-tag add @phil/managepackageswithnpm@1.0.1 beta

**Comment by scshepard** [comment]
Hi all,
Rarely am I stumped, but here I am; I'm quite familiar with the term beta; what is the meaning of FCC in the context of this thread?
Thanks muchly!
Steve
________________________________

**Comment by sahinerbay** [comment]
List available dist-tags
**npm dist-tag ls**

Adding a dist-tag
**npm dist-tag add @"yourname"/"yourfilename"@1.1.0 beta**

Removing a dist-tag
**npm dist-tag rm @"yourname"/"yourfilename" beta**

Pointing "latest" tag somewhere else
**npm dist-tag add @sahinerbay/demo@1.0.0 latest**

If you face any problems with the last one, first change the version in package.json and then run the command.
