### ISSUE TITLE
Change protocol on Imgur links from http to https

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#7580]
Most images in the codebase are served from Imgur. We've recently switched to SSL and will need to change the protocols in these links to https.

for example https://github.com/FreeCodeCamp/FreeCodeCamp/blob/bf4ccab5868e3541c4be19dfcae668856be06747/server/views/certificate/front-end.jade#L3

http://i.imgur.com/ToFZKBd.jpg => https://i.imgur.com/ToFZKBd.jpg

**Comment by abhisekp** [comment]
It should be protocol independent links [//i.imgur.com/ToFZKBd.jpg](//i.imgur.com/ToFZKBd.jpg)

**Comment by BerkeleyTrue** [comment]
Sure that works too
