### ISSUE TITLE
My objectives aren't popping up

### ISSUE THREAD

**Issue by RhemaMcGee** [FreeCodeCamp/FreeCodeCamp#7581]
#### Issue Description
* My objectives aren't popping up
* I have refreshed this site so many times!!!!
http://www.freecodecamp.com/challenges/access-multidimensional-arrays-with-indexes#?solution=%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B1%2C2%2C3%5D%2C%20%5B4%2C5%2C6%5D%2C%20%5B7%2C8%2C9%5D%2C%20%5B%5B10%2C11%2C12%5D%2C%2013%2C%2014%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myData%20%3D%20myArray%5B8%5D%5B0%5D%3B%0Avar%20a%20%3D%20new%20Array(4)%3B%0Afor%20(i%20%3D%200%3B%20i%20%3C%204%3B%20i%2B%2B)%20%7B%0A%20%20a%5Bi%5D%20%3D%20new%20Array(4)%3B%0A%20%20for%20(j%20%3D%200%3B%20j%20%3C%204%3B%20j%2B%2B)%20%7B%0A%20%20%20%20a%5Bi%5D%5Bj%5D%20%3D%20%22%5B%22%20%2B%20i%20%2B%20%22%2C%22%20%2B%20j%20%2B%20%22%5D%22%3B%0A%20%20%7D%0A%7D%0A 
#### Browser Information
* Safari,Mac
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

#### Screenshot

**Comment by ltegman** [comment]
Your code is crashing the test runner and yielding an error to the console that reads:
![access_multi-dimensional_arrays_with_indexes___free_code_camp](https://cloud.githubusercontent.com/assets/1381313/13834182/1878aaa6-ebaa-11e5-8f49-0cf50c200714.png)
Once you solve the issue that is causing your code to crash the tests will show back up.
Thanks and happy coding!
