### ISSUE TITLE
Video challenges out of sequence

### ISSUE THREAD

**Issue by pamelawoodbrowne** [FreeCodeCamp/FreeCodeCamp#7583]
#### Computer Basics video challenges are out of sequence
* The Variables in Code video uses information explained in Console and Logging video
* Console and Logging should be moved to position before Variables in Code

http://www.freecodecamp.com/videos/variables-in-code
http://www.freecodecamp.com/videos/console-and-logging

#### Screenshot
![screenshot 2016-03-16 22 55 02](https://cloud.githubusercontent.com/assets/4888730/13835001/424b5d72-ebca-11e5-8b13-8a040eca1db5.png)

**Comment by 3316** [comment]
This is not me

**Comment by erictleung** [comment]
I've also found that in the Computer Basics section, Binary Bytes feels like it would be better suited going after Decoding a Binary Number.

[Binary Bytes](https://www.freecodecamp.com/videos/computer-basics-binary-bytes)
[Decoding a Binary Number](https://www.freecodecamp.com/videos/computer-basics-decoding-a-binary-number)

![screen shot 2016-03-30 at 09 37 39](https://cloud.githubusercontent.com/assets/2754821/14149876/1cb4a1f4-f65b-11e5-8f96-ebe9ad2f6f0c.png)

**Comment by sahilkhurana19** [comment]
Hi, I was thinking about trying to fix this issue and put the challenges in the correct order, but being a relatively new contributor here I was unable to find the place where the challenges names are stored. Any help would be appreciated.

**Comment by pranayberry** [comment]
@sahilkhurana19 https://github.com/FreeCodeCamp/FreeCodeCamp/tree/staging/seed/challenges
