### ISSUE TITLE
Cannot submit - Nest an Anchor Element within a Paragraph challenge

### ISSUE THREAD

**Issue by cmchenry1** [FreeCodeCamp/FreeCodeCamp#7584]
Challenge [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Ca%20href%3D%22'%22http%3A%2F%2Fwww.freecatphotoapp.com'%3Ecat%20photos%3C%2Fa%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>
  
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

I believe the code above is correct, but I'm unable to submit it. I've tried verifying the code in the Help Chat Room. I had no luck there.

Update:
I got the code above to submit. I clicked Map, reloaded this challenge, and copied & pasted the exact code from this issue into the editor.

One more thing... When I couldn't submit before, the iPhone screen rendering the HTML appeared to be unresponsive to any changes made in the editor.

**Comment by cannelflow** [comment]
instruction says Now nest your existing a element within a new p element (just after the existing h2 element) so that the surrounding paragraph says "View more cat photos", but where only "cat photos" is a link, and the rest of the text is plain text. which is like
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>
since it says at the end where only "cat photos" is a link it should be within a and  rest of the text is plain text so it should be in p 
Please use FCC Chat Room For Your Doubt https://gitter.im/FreeCodeCamp/Help

**Comment by cmchenry1** [comment]
Update:
I got the code above to submit. I clicked Map, reloaded this challenge, and copied & pasted the exact code from this issue into the editor.

One more thing... When I couldn't submit before, the iPhone screen rendering the HTML appeared to be unresponsive to any changes made in the editor.

**Comment by cannelflow** [comment]
@cmchenry1 yes your code is good what issue are you getting while submitting perhaps this [Article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Using-browsec-for-securing-your-connection-to-fcc) can help you

**Comment by raisedadead** [comment]
@cmchenry1 Your code passes for me.

Can you check if you are getting any errors in your browser's dev console. Press <kbd>F12</kbd> to launch Dev tools and go to the `Console` tab.

Then refresh the challenge page and proceed with the submitting the solution and check the console for errors.

If any then please post the screenshot here.

Thanks.

**Comment by cmchenry1** [comment]
@cannelflow I read the article and installed Browsec.

@raisedadead Here are the errors from my browser with (1st screen) and without (2nd screen) Browsec.

I was able to successfully submit my answer in both cases. Let me know if you guys need any other info from me.

**Comment by raisedadead** [comment]
@cannelflow Thanks for helping out with your comments.
@cmchenry1 Thanks a lot. The screen shots confirm the problem. You needn't use Browsec.

I just confirmed and this is a regression with the recent SSL upgrade.
We have to change the :
`<link href="`**http**`://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">`
to 
`<link href="`**https**`://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">`

----

#### For anyone willing to help fixing this :

Please change the URL to **https** protocol in all the challenges that have this. Or similar. I'll try to compile a list of the affected challenges if I get some time.

**Comment by cannelflow** [comment]
@raisedadead :+1:

**Comment by alacrity26** [comment]
Hi I have similar issues running this test, even after changing http to https as suggested by @raisedadead

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17925120/13897707/3f4d1a38-edf6-11e5-9e60-a61816760545.png)

Pls help me solve this

**Comment by elchinsolo** [comment]
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>
<p>
<p>View more 
  <a href="http://www.freecatphotoapp.com">
    cat photos</a>
</p>
</p>

so it is right but console in firefox show last </p> tag red as it is false but code is right, maybe there is some bug in console

**Comment by 3316** [comment]
This is not me. I do not own a Mac.

**Comment by raisedadead** [comment]
@3316 Seems you have set the watching to all notifications and that's why you are receiving this mails/notfications which are not related to you.

Please check https://help.github.com/articles/unwatching-repositories/.

**Comment by Obazee** [comment]
- <style>
    font-family: Sans-serif;
  }

  Monospace {
    font-size: 16px;
  }
</style>

<h2> class="red-text">CatPhotoApp</h2>

<Monospace class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</Monospace>
<Monospace>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</Monospace>

**Comment by Obazee** [comment]
I can´t summit it. I need help
