### ISSUE TITLE
Issue with Replacing If Else Chains with Switch

### ISSUE THREAD

**Issue by shaanaa22** [FreeCodeCamp/FreeCodeCamp#7588]
Challenge [Replacing If Else Chains with Switch](https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%7B%0A%20%20%20%20%20case%20%22bob%22%3A%0A%20%20%20%20%20%20answer%3D%22Marley%22%3B%0A%20%20%20%20%20%20return%3B%0A%20%20%20%20case%2042%3A%0A%20%20%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%201%3A%20%0A%20%20%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2099%3A%20%0A%20%20%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%20%20%0A%20%20%20%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%0A%20%20%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
     case "bob":
      answer="Marley";
      return;
    case 42:
      answer = "The Answer";
      break;
    case 1: 
      answer = "There is no #1";
      break;
    case 99: 
      answer = "Missed me by this much!";
      break;
    case 7:  
      answer = "Ate Nine";
      break;
   
    }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(7);


```
**myTest("bob") should be "Marley" -- isn't getting passed. Please someone check the code.**

**Comment by raisedadead** [comment]
@shaanaa22 

Your code is not correct. Double check what you are returning in the first switch case.
Secondly, Github Issues are NOT for code help. Please ask for assistance in the Help Chat[https://gitter.im/FreeCodeCamp/HelpJavaScript]

Closing as not site issue

**Comment by shaanaa22** [comment]
Thanks @raisedadead I just saw where I made the mistake. Sorry for the trouble.

**Comment by Trupal24** [comment]
function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  switch (val) {
    case "bob":
    answer = "Marley";
    break;
    case 42:
    answer = "The Answer";
    break;  
    case 1 :
    answer = "There is no #1";
    break;
    case 99:
    answer = "Missed me by this much!";
    break;
    case "John":
    answer ="";
    break;
    case 156:
    answer ="";
    break;
    default:
    answer = "Ate Nine";
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);

Here is the right code.
