### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by orvi2014** [FreeCodeCamp/FreeCodeCamp#7598]
#### Issue Description
* Steps To Reproduce
 1. Go to Video Challenges.
 2. Go to Dom Section.
 3. Check the second challenge-"The DOM: Style in the Header, Script in the Footer".
 4. In that challenge a link is provided in the last line "ablogaboutcode.com/2011/06/14/how-  javascript-loading-works-domcontentloaded-and-onload/" which is not working. 
 5. It gives a 404 error.

**Comment by raisedadead** [comment]
Tested fixed with #7571

**Comment by raisedadead** [comment]
@orvi2014 This will soon reach the main website

**Comment by orvi2014** [comment]
Yes I saw it later when I try to send the PR. Thanks Anyway
