### ISSUE TITLE
Social Media Login/Link

### ISSUE THREAD

**Issue by crosscris** [FreeCodeCamp/freecodecamp#76]
This is not a bug, but it would be a nice login feature. Currently, there seems to be no way to delete or reset the social media logins. When I go to the profile page, I do not see any options to change the social media links. I have attached an image of what I encounter when I try to change the facebook login.
![fcc social media logins](https://cloud.githubusercontent.com/assets/9522511/6046088/e7a19e9c-ac53-11e4-9631-3abd4dfda534.JPG)

**Comment by aldraco** [comment]
What do you mean by change? as in change your facebook login credentials to login under a new account? and delete your old credentials?

**Comment by BerkeleyTrue** [comment]
Do you mean unlinking an account?

**Comment by QuincyLarson** [comment]
Hi @crosscris, Is this an issue that many people would encounter? The only reason I can think of for unlinking an account is 1) you have more than one Facebook account and you want to move the account from your original Facebook account to a new Facebook account or 2) you have more than one FCC account. Neither of those sound like typical scenarios. I'd rather not clutter up the UI with buttons few if anyone will use.

**Comment by BerkeleyTrue** [comment]
This issue has grown stale. I don't see a demand for unlinking. Please feel free to reopen to keep the discussion open.

**Comment by pacalabre** [comment]
I am interested in unlinking my facebook account as I do not wish to advertise that to potential employers but would like to have my FFC profile on my portfolio.

**Comment by Michael-Morris-1** [comment]
I've changed my twitter username from mkemo8870 to Mike_Morris_1. How can I update this to my twitter icon on my free code camp profile.

**Comment by acoombs12** [comment]
I linked the wrong Twitter account to my profile. How can I undo this?
