### ISSUE TITLE
This code should not pass the test :D

### ISSUE THREAD

**Issue by mohammedzamakhan** [FreeCodeCamp/FreeCodeCamp#7600]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20if(str%20%3D%3D%3D%20'not%20a%20palindrome'%20%7C%7C%20str%20%3D%3D%3D%20'nope'%20%7C%7C%20str%20%3D%3D%3D%20'almostomla'%20%7C%7C%20str%20%3D%3D%3D%20'1%20eye%20for%20of%201%20eye.')%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  if(str === 'not a palindrome' || str === 'nope' || str === 'almostomla' || str === '1 eye for of 1 eye.') {
    return false;
  }
  return true;
}



palindrome("eye");

```

**Comment by khaduch** [comment]
I agree!  Although it is a very _resourceful _ way to pass the test... wouldn't be too good if the test inputs changed, though.

**Comment by sludge256** [comment]
I don't know if we'd want to update the tests just to account for an intentional bypass.
@FreeCodeCamp/issue-moderators thoughts?

**Comment by raisedadead** [comment]
@sludge256 Interesting.

Thing is IMHO, if we do handle a couple of cases like this there will be a ton others similar when it comes to people intentionally wanting to pass the challenges.
And after a point it will become really tedious to manage these cases.

Why would anyone genuinely interested in solving the challenge would do as such?

Well, I do have a dirty/unfair way to avoid such scenarios:

1. Add just one input test case that's not in the list (by [Obfuscating it](https://en.wikipedia.org/wiki/Obfuscation_(software))).
2. When anyone does come up with scenarios like one stated in the issue (the test fails in background), we show a modal window:

 > Are you sure you are doing this challenge honestly?

 IDK, make the message a bit funnier.

Of course our code is Open Source and anyone can go thru the code and bypass this anyway, but definitely it would prompt most to act more honestly?

IDK, that's just my personal opinion, although I really really wouldnt want such a thing ever. I believe most of the campers and the community is dedicated to the curriculum. And this is simply not just a good way to do it for their sake.

**Comment by 3316** [comment]
This is not me. Do not own a Mac mac. I only have my cell phone to connectconnect to internet.

**Comment by SaintPeter** [comment]
There is obviously a limit to what we can do to stop attempts like this.

I would consider someone "solving" problems like this to potentially have violated out academic honesty policy.  This is clearly not solving the problem as per the instructions.  If I saw a "solution" like this when reviewing for a non-profit project, the camper would not be allowed to participate until they fixed it.

**Comment by benmcmahon100** [comment]
The most complete solution would to have a function that generates input and an expected output for each challenge. This would totally stop people from doing this but it would require a lot of work. It would also require that the perfect solution is contained within the code so you'd be exchanging one cheat for another. As @SaintPeter said though, the deterrent lies in the fast that the only person who loses it are the people who fudge the tests.

**Comment by raisedadead** [comment]
That's a lot of complexity IMHO !

**Comment by benmcmahon100** [comment]
Yeah that's my point. It's totally fixable but it's probably not worth the effort just to end up with a different form of cheating :p

**Comment by raisedadead** [comment]
Closing. 

As discussed : Increasing the complexity of the code would introduce more bugs. Its really up to the camper to cheat, pass and lose on the learning.

**Comment by philipjc** [comment]
So, '1 eye for of 1 eye' is bugged?
