### ISSUE TITLE
can not pass challenge even though i zoomed to 100

### ISSUE THREAD

**Issue by petralatchman** [FreeCodeCamp/FreeCodeCamp#7602]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by orvi2014** [comment]
what was the issue ?

**Comment by sludge256** [comment]
Can you post your code or ask here https://gitter.im/FreeCodeCamp/Help ?
In all likelihood there's an issue with your code unrelated to your browser zoom level.

**Comment by bugron** [comment]
@petralatchman thanks for posting. I'm going to close this issue but feel free to reopen with the description of your issue.
