### ISSUE TITLE
Challenge: Word Blanks should have tests to make sure campers use function parameters

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#7603]
A low priority/bike shedding issue, but I figured it's worth mentioning anyways.

Supplied code passes, but defeats the purpose of the challenge. It's unlikely that someone would ever do this, but I do recall seeing similar code being posted in one of the Gitter rooms.

Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20result%20%3D%20%22dog%20big%20ran%20quickly%20cat%20little%20hit%20slowly%22%3B%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) 

```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result = "dog big ran quickly cat little hit slowly";

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

The code I saw in chat looked something like this (from what I remember at least):
```js
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "dog big ran quickly ";
  // Your code below this line
  result += "cat little hit slowly";

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
```

**Comment by ltegman** [comment]
Hahaha, I love this. It's not something we could ever fully prevent, but we could make it more annoying by adding 2 or 3 more tests. However, I tend to be of the mind that it doesn't matter. If someone does this there's no way they can't realize they're circumventing the purpose of the challenge and since this challenge isn't required for a cert the only thing they're harming is their own learning potential.

Anyone else have thoughts on if this is worth fixing?

**Comment by raisedadead** [comment]
@sludge256 @ltegman Isn't this similar to #7600 of intentionally trying to pass the tests?

**Comment by sludge256** [comment]
@raisedadead Yes, that's why I brought it up.

I also agree that's not a big issue. I can go ahead and close this, and maybe 7600 if we don't plan on preventing such code any time soon.

**Comment by 3316** [comment]
This is not me. Do not own a Mac. Connect with cell phone only

**Comment by jowright** [comment]
I would like to know what I am supposed to learn from this. Could you help me understand why the above code was controversial.  I also noticed there was no closing } at top of page it is a must in java script right.  I get an error when I try to place the code.  Can anyone help me understand.

**Comment by alistermada** [comment]
@jowright This challenge is meant to be an exercise in string concatenation using variables. This concept was introduced in [Constructing Strings with Variables](https://www.freecodecamp.com/challenges/constructing-strings-with-variables).

The above code is controversial because it passes without following the instructions:
> You will need to use string operators to build a new string, `result`, using the provided variables: `myNoun`, `myAdjective`, `myVerb`, and `myAdverb`.

None of the provided variables were used.

The closing `}` for the function is just below the return statement.

**Comment by juniorveasy** [comment]
I don't quite understand what's being asked of me.

**Comment by raisedadead** [comment]
Closing. Please [refer comment here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7600#issuecomment-212386978)

**Comment by Toriki07** [comment]
result+= "My "+myAdjective+" "+myNoun+" "+myVerb+" very "+myAdverb+".";
it's so funny :santa:

**Comment by Bhargavbonu** [comment]
First of all the challenge itself is not clear with poorly framed and confusing question. Despite reading multiple times I don't understand what the question expects. Can the FreeCodeCamp look after this question and change it?
You will need to use string operators to build a new string, result, using the provided variables: myNoun, myAdjective, myVerb, and myAdverb.

You will also need to use additional strings, which will not change, and must be in between all of the provided words. The output should be a complete sentence.

We have provided a framework for testing your results with different words. The tests will run your function with several different inputs to make sure all of the provided words appear in the output, as well as your extra strings.

result+= "My "+myAdjective+" "+myNoun+" "+myVerb+" very "+myAdverb+".";

**Comment by raisedadead** [comment]
@Bhargavbonu please open a fresh issue.

**Comment by siguniang** [comment]
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result=myNoun+" "+myAdjective+" "+myVerb+" "+myAdverb;
  //result="dog, big, ran ,quickly";
  //result="cat, little, hit ,slowly";
  
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
wordBlanks("cat", "little", "hit", "slowly");
