### ISSUE TITLE
"Where do I belong",  issue while sorting the array

### ISSUE THREAD

**Issue by kikreddy** [FreeCodeCamp/FreeCodeCamp#7606]
function where(arr, num) {
  // Find my place in this sorted array.
  var newArr = [];
  newArr=arr.sort();
  
  return newArr;
}

where([1, 3, 20, 3], 5);

o/p : [1,20,3,3]

instead it should give output as [1,3,3,20]

in place of 20, numbers from 10 to 29 can be placed which gives the same issue... Could anyone pls help me out. Your response would be appreciated

**Comment by ltegman** [comment]
Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance. Thanks and happy coding!
