### ISSUE TITLE
Again issue with "Iterate Through an Array with a For Loop"

### ISSUE THREAD

**Issue by chandra90** [FreeCodeCamp/FreeCodeCamp#7609]
Challenge [Iterate Through an Array with a For Loop](https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myTotal%20%3D%200%3B%0Afor%20(i%20%3D%200%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%0A%7B%0A%20%20%20%20myTotal%20%2B%3D%20myArr%5Bi%5D%3B%0A%7D%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0.3 Waterfox/44.0.3</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
My code:
```javascript
// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line
var myTotal = 0;
for (i = 0; i < myArr.length; i++)
{
    myTotal += myArr[i];
}



```

**Comment by raisedadead** [comment]
Hi @chandra90 ,

I am afraid your code is not correct. Please reach out to the [JavaScript Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assitance.

Closing as not a site issue.

Thanks and happy coding!
