### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jungowrites** [FreeCodeCamp/freecodecamp#761]
Throughout the challenges I've noticed simple typos. For Example, "you" instead of "your"
![typos](https://cloud.githubusercontent.com/assets/9904547/7899038/4d6519fa-06e2-11e5-879e-6ee171f22928.png)

**Comment by QuincyLarson** [comment]
Nice catch!

**Comment by jungowrites** [comment]
Thanks! I know they are minor, but I know every little help counts.

**Comment by QuincyLarson** [comment]
I really appreciate it. I'm doing a full audit of our challenges and their wording to catch these typos.
