### ISSUE TITLE
Title Case A Sentence arrives at the correct result but fails 

### ISSUE THREAD

**Issue by Plaskin87** [FreeCodeCamp/FreeCodeCamp#7610]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20str%20%3D%20str.toLowerCase().split(%22%20%22)%3B%0A%20%20%20%20var%20b%20%3D%22%22%20%3B%0A%20%20for(i%3D0%3Bi%3Cstr.length%3Bi%2B%2B)%7B%0A%20%20%20for(j%3D0%3Bj%3Cstr%5Bi%5D.length%3Bj%2B%2B)%7B%0A%20%20%20%20%20%0A%20%20%20%20if(str%5Bi%5D%5Bj%5D%20%3D%3D%3D%20str%5Bi%5D%5B0%5D)%20%7B%0A%20%20%20%20%20%20b%20%2B%3D%20str%5Bi%5D%5B0%5D.toUpperCase()%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20b%20%2B%3Dstr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20b%2B%3D%20%22%20%22%3B%0A%20%20%7D%0A%20%20%20%20%20%0A%20%20return%20%20b%3B%0A%7D%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My approach is not accepted. I know it's not the nicest solution but it works. 
Or is there an error I do not see?

My code:
```javascript
function titleCase(str) {
 str = str.toLowerCase().split(" ");
    var b ="" ;
  for(i=0;i<str.length;i++){
   for(j=0;j<str[i].length;j++){
     
    if(str[i][j] === str[i][0]) {
      b += str[i][0].toUpperCase();
      }
     
    else{
      b +=str[i][j];
      }
   }
    
    
    b+= " ";
  }
     
  return  b;
}
titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");
```
<a href="http://www.bilder-upload.eu/upload/772b1d-1458296663.png" target="_blank"><img src="http://www.bilder-upload.eu/thumb/772b1d-1458296663.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by raisedadead** [comment]
@Plaskin87 You are almost there, the function is returning a string an extra space at the end, that's not visible in console output.

If you are stuck please reach out the [JavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript), for assistance.

Closing as not a site issue.

Thanks and happy coding!

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
