### ISSUE TITLE
Output is showing incorrect. myVar++; still giving output 87.

### ISSUE THREAD

**Issue by kaustubh6** [FreeCodeCamp/FreeCodeCamp#7611]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar++;


```

**Comment by raisedadead** [comment]
@kaustubh6 : Check the instructions

![image](https://cloud.githubusercontent.com/assets/1884376/13875452/f6aeb430-ed23-11e5-9459-18a4a7b67114.png)

I know it looks a bit weird, but that's how assignment and expression evaluation work.

Please feel to reach out to the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) room should you need assistance.

@SaintPeter : I am not sure if we want to introduce concept of `pre & post increment/decrement` here or until later or point to a wiki article, given the scope and target audience and the complexity of the challenge. But I would love your feedback on this. Keeping this open for opinion.

**Comment by 3316** [comment]
This is not me. Do not own  Mac. Use. Cell phone only. is this a hacker?

**Comment by SaintPeter** [comment]
@raisedadead We've discussed this a bit before, but it's not clear that we can cleanly introduce the idea of pre/post increment without causing more confusion.   The Hint line was our compromise.

**Comment by raisedadead** [comment]
@SaintPeter I thought so too. How about a wiki article explaining the concepts instead of actuall challenges?

Also see related issue #7705

**Comment by SaintPeter** [comment]
@raisedadead 
Another possibility would be to add additional challenges that explicitly explore the differences.  Neither solution ultimately fixes the problems with THIS challenge though.  Maybe this is one we could add some additional clarification?

I'm not sure I know what that'd look like.

**Comment by raisedadead** [comment]
@SaintPeter  We Should add test to this as discussed in #7705. 

Refering:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Increment_()

May be we add this as a link for reference in this challenge. Of course with your valuable feed back for the text.

Also we could add a couple challenges on this as well

**Comment by raisedadead** [comment]
Anyone interested in fixing this please add a link in the challenge as hint as mentioned above.

**Comment by DusanSacha** [comment]
@raisedadead 
Hi, I can take care of it. However I am not sure how exactly was it meant to be done.

Is this enough? (added the last "hint" paragraph with the link)
![free_camp_fix](https://cloud.githubusercontent.com/assets/16412025/14692337/b8173f10-0756-11e6-8b6d-b79b385cd5d7.png)

**Comment by raisedadead** [comment]
@DusanSacha Yup that looks perfect, how about adding like this:

**Hint**
Learn more about [Arithmetic operators - Increment (++)](#)

Please feel free to make a PR!
Thanks for contributing.
