### ISSUE TITLE
The font link doesn't change the font to Lobster in Chrome (Windows 7)

### ISSUE THREAD

**Issue by yuleto** [FreeCodeCamp/FreeCodeCamp#7612]
Challenge [Import a Google Font](https://www.freecodecamp.com/challenges/import-a-google-font#) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello,

When I copy&paste the link for the Lobster font, the font doesn't change.

![lobster1](https://cloud.githubusercontent.com/assets/14294309/13875259/7a0dd26c-ed05-11e5-9c5f-9bfc31fb4f6b.png)

I did a Google search and found this site: http://www.cssfontstack.com/Lobster
After comparing the href links, I tried to delete the "http:" part from the one used in the challenge.
After the change, the Lobster font displayed correctly.

![lobster2](https://cloud.githubusercontent.com/assets/14294309/13875405/59126798-ed06-11e5-8d71-50185f09065b.png)

I was able to run the test with the modified link and to proceed to the next challenge. The link in the next challenge still contains the "http:" part though.

**Comment by raisedadead** [comment]
@yuleto Thanks for reporting. 

Please check this [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7584#issuecomment-198277716)

Closing as similar to #7584 . Please continue the discussion there and follow along.

**Comment by yuleto** [comment]
@raisedadead Great, thank you for the fast reply!

**Comment by RandyCG** [comment]
Thanks so much.!
