### ISSUE TITLE
"Stand in line" exercise under Basic JS has unclear directions or doesn't evaluate properly

### ISSUE THREAD

**Issue by W8sconsin** [FreeCodeCamp/FreeCodeCamp#7614]
1. queue([], 1) should return 1
2. queue([2], 1) should return 2
3. queue([5,6,7,8,9], 1) should return 5
4. After queue(testArr, 10), myArr[4] should be 10

4 doesn't seem to relate to the task.  Unclear directions in task.  What is myArr?  It comes out of the blue.

**Comment by raisedadead** [comment]
@W8sconsin thanks.

Yup There is a typo :
`After queue(testArr, 10), `**myArr**`[4] should be 10` 
should be
`After queue(testArr, 10), `**testArr**`[4] should be 10`

Needs to be fixed [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2535)

Apart from that do you feel there is anything that is not clear in the challenge, please comment.

Thanks again.

**Comment by W8sconsin** [comment]
That's more clear.  Thanks for the help!

**Comment by drk7891** [comment]
I have a fix coming

**Comment by raisedadead** [comment]
@drk7891 Thanks!

**Comment by bakerameen** [comment]
I am stuck with this:

queue([], 1) should return 1
queue([2], 1) should return 2
queue([5,6,7,8,9], 1) should return 5
After queue(testArr, 10), testArr[4] should be 10

**Comment by gnefkow** [comment]
Yeah, I'm also stuck on that one... Specifically, it is the:
The directions say: "remove the first element of array. The nextInLine function should then return the element that was removed."
But one of the validations says:
"queue ([], 1) should return 1"

But the value removed from the array was null, so shouldn't var nextInLine return nothing?

**Comment by juniorveasy** [comment]
Yeah, I'm totally confused. The directions are not clear. @gnefkow

**Comment by trouterusa** [comment]
I have to agree... I don't know what to do here. I am searching all the interwebs, and coming up with all sorts of solutions, but the freeCodeCamp editor doesn't seem to accept them. This is very unclear as to what we are supposed to do here.

**Comment by styop88** [comment]
arr.push(item);
  return arr.shift();

**Comment by texas2010** [comment]
@styop88 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
