### ISSUE TITLE
Font degradation occurs even when font is being inserted correctly

### ISSUE THREAD

**Issue by TheIllusionistMirage** [FreeCodeCamp/FreeCodeCamp#7616]
#### Issue Description
* When Issue Happens
Starting from the challenge [Add Images to your Website Complete](https://www.freecodecamp.com/challenges/add-images-to-your-website) till the challenge [Use an ID Attribute to Style an Element](https://www.freecodecamp.com/challenges/use-an-id-attribute-to-style-an-element), the font for `h2` degrades to Monospace even when Lobster is being fetched from Google fonts and the 'style' element of 'h2' is being defined as:
`h2 {
    font-family: Lobster, Monospace;
  }`

* Steps To Reproduce
Visit the challenge pages for the challenges lying between the aforementioned tutorials. You will see the result in the HTML simulator of FCC as shown in the screenshots below.

#### Browser Information
* Browser Name, Version
Firefox 44.0.2
* Operating System
Fedora 22 Workstation, 32-bit

#### Screenshot
1. First instance
![screenshot-1](http://i.imgur.com/sZsjZ12.png)

2. Second instance
![screenshot-1](http://i.imgur.com/GxOuqsc.png)

#### NOTE:
This happens in all the challenges lying between the above mentioned challenges.

**Comment by mdelgadonyc** [comment]
@TheIllusionistMirage This does not appear to be a FCC site error. I saw the same problem when I tested the code you posted on the jsfiddle.net site. What mitigated the problem for me was replacing http with https in the <link> tag that pulls in the Lobster font from Google. As in:

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

-Moisés

**Comment by TheIllusionistMirage** [comment]
Thanks @mdelgadonyc Yeah fixes for me too. Since Google Fonts is using HTTPS, I think it'd be better to use that in the challenges as well. But I don't seem to understand what's the technical reason behind this.

**Comment by N0bl3** [comment]
It is probably because Cross Domain non secured requests I.E HTTP here are forbidden.

**Comment by 3316** [comment]
This is not me. I do not own a Mac or use browsers listed. Use cell phone to. Connect to Google
