### ISSUE TITLE
Label Bootstrap Buttons

### ISSUE THREAD

**Issue by burnleyt** [FreeCodeCamp/FreeCodeCamp#7618]
Challenge [Label Bootstrap Buttons](https://www.freecodecamp.com/challenges/label-bootstrap-buttons#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23target1%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23target2%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23target3%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23target4%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23target5%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Ch4%3E%23target6%3C%2Fh4%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <h4>#target1</h4>
        <button class="btn btn-default target" id="target1"></button>
        <h4>#target2</h4>
        <button class="btn btn-default target" id="target2"></button>
        <h4>#target3</h4>
        <button class="btn btn-default target" id="target3"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <h4>#target4</h4>
        <button class="btn btn-default target" id="target4"></button>
        <h4>#target5</h4>
        <button class="btn btn-default target" id="target5"></button>
        <h4>#target6</h4>
        <button class="btn btn-default target" id="target6"></button>
      </div>
    </div>
  </div>
</div>

```
Very simple instructions.  Similar to challenge before.  I checked for closing tags, I put the hash, no spaces, no typos...

I can not see the problem.

**Comment by drk7891** [comment]
Your issue isn't a bug as you aren't giving the buttons a label. You're having `h4` set to the label when you would want to give it to the button. For example:

`<button class="btn btn-default target" id="target4">#target4</button>`

Have you checked out the [FreeCodeCamp Gitter channel](https://gitter.im/FreeCodeCamp/FreeCodeCamp)?

**Comment by burnleyt** [comment]
Oh ok, thanks for your help.  I did look for a solution before posting but couldn't find answer.  Again, thank you, I understand now.  I relied too much on the similarity to the one before this and got tunnel vision.  Thx
