### ISSUE TITLE
name attribute test does not work...

### ISSUE THREAD

**Issue by purpleHey** [FreeCodeCamp/freecodecamp#762]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Put the following code in after the submit button:

  <label for="Indoor">Indoor</label>
  <input type="radio" name="indoor-outdoor" id="indoor">
  <label for="Outdoor">Outdoor</label>
  <input type="radio" name="indoor-outdoor" id="outdoor">

The test for name = indoor-outdoor still fails.

**Comment by LumenTeun** [comment]
@purpleHey Please describe the problem you're having. I was able to complete this challenge without a hitch, so you might just have misunderstood the objective? If you could post the code that's not working, that would be great.

**Comment by purpleHey** [comment]
Sorry, I thought I had pasted this code in:
 
 <label for="Indoor">Indoor</label>
  <input type="radio" name="indoorOrOutdoor" id="indoor">
  <label for="Outdoor">Outdoor</label>
  <input type="radio" name="indoorOrOutdoor" id="outdoor">
 
This does work, and its done the way w3school shows it:

http://www.w3schools.com/tags/tag_label.asp

**Comment by purpleHey** [comment]
ug...the code get's stripped out!

      <label for="Indoor">Indoor</label>
      <input type="radio" name="indoorOrOutdoor" id="indoor"><br>
      <label for="Outdoor">Outdoor</label>
      <input type="radio" name="indoorOrOutdoor" id="outdoor">

**Comment by LumenTeun** [comment]
Ah, I see what happened. If you read the instructions carefully you'll see that you're missinterpreting the information. If you click "More information", there's an example of how they want the radio buttons to look, at the bottom. Oh, and remember to close this issue.

Also, don't use w3schools.com, from what I've heard and seen, it's a bad resource. I recommend [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web), they're absolutely great!
