### ISSUE TITLE
Wrong Test Case?

### ISSUE THREAD

**Issue by reyhansofian** [FreeCodeCamp/FreeCodeCamp#7626]
Challenge [Chunky Monkey](https://www.freecodecamp.com/challenges/chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20var%20n%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20size%3B%20i%2B%2B)%20%7B%0A%20%20%20%20n.push(arr.slice(i*size%2C%20i*size%2Bsize))%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20return%20n%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function chunk(arr, size) {
  var n = [];
  for (var i = 0; i < size; i++) {
    n.push(arr.slice(i*size, i*size+size));
  }
  
  // Break it up.
  return n;
}

chunk(["a", "b", "c", "d"], 2);

```

Whenever I run the test, it will always failed. See my screenshot below 
![screen shot 2016-03-19 at 11 55 18](https://cloud.githubusercontent.com/assets/5353857/13896766/4bb0cba6-edcb-11e5-81e1-649bb4c917c3.png)

As  you can see, the second until fourth test case is failed, same as the last test case. So, I tried to debug the array, and it show just like the console view on the right side

**Comment by alistermada** [comment]
That's the expected output of logging `arr` to the console in the beginning of the function. If you log `n` to the console just before your return statement, you'll see that your code does not match what is expected.

Note: `size` is not meant to define the length of the returned array (`n` in this case), but the maximum length of the arrays nested inside it.

If you need further help on the algorithm challenges, check out the [Help JavaScript chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by bugron** [comment]
@reyhansofian thanks for posting. Closing this issue. As @alistermada is correct, if you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

**Comment by zhixinyiye** [comment]
function chunkArrayInGroups(arr, size) {
  // Break it up.
  var newArr = [];

  for(var j= 0;j<(((arr.length)/size));j++){
    newArr.push(arr.slice(j*size,(j+1)*size));
  }
  return newArr;
}
