### ISSUE TITLE
Inconsistency in challenge instructions

### ISSUE THREAD

**Issue by gboyega** [FreeCodeCamp/FreeCodeCamp#7628]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
I think this is a general issue. Sometimes what you are instructed to do is different from what is listed in the checklist. Usually I just do what is on the checklist but this challenge (Understanding Uninitialized Variables) appears to behave differently. I did what was on the checklist but it didn't let me go forward. So I followed the instructions instead this time and it worked.

#### Browser Information
* Chrome, 49
* Android

#### Screenshot
(No upload button here)

**Comment by bugron** [comment]
@gboyega thanks for posting. Not sure what is the issue with Understanding Uninitialized Variables challenge, I've just completed it by following it's instructions.
Can you comment here what's wrong in your opinion with other challenges?

**Comment by gboyega** [comment]
Yes, following the instructions worked for me in this particular challenge but there is a checklist (after the instructions) that has some items marked red when they fail and green when they pass the tests. The items on this checklist are not consistent with the instructions. In previous challenges I've had to ignore the instructions just to satisfy the checklist (every item has to have a green checkmark for you to go forward). This time around the opposite happened. It can be a little confusing.

**Comment by alistermada** [comment]
The tests (checklists) are the expected output of your code, while the instructions are what you should do in your code. They are not the same thing.

In [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables), you need to consider the bottom half of the code:
```
// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";
```

The instructions tell you to initialize `a` to 5. After that, it will run `a = a + 1` which makes `a` equal to 6 by the end of your code. This is why the first test says that `a` should have a value of 6.

**Comment by gboyega** [comment]
@alistermada Ok, I get it now. Thanks. Sorry for the false alarm.

**Comment by bugron** [comment]
Closing this issue then. @gboyega thanks again for posting.
