### ISSUE TITLE
"Tile Case a Sentence" Challenge does not accept correct solution.

### ISSUE THREAD

**Issue by ManBearPigg** [FreeCodeCamp/FreeCodeCamp#7629]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=var%20test%20%3D%20%5B%5D%3B%0Avar%20myArray%20%3D%20%5B%5D%3B%0Afunction%20titleCase(str)%20%7B%0A%20%20myArray%20%3D%20str.toLowerCase().split('%20')%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20myArray.length%3B%20i%2B%2B)%20%7B%0A%20%20%20test.push(myArray%5Bi%5D%5B0%5D.toUpperCase()%20%2B%20myArray%5Bi%5D.substr(1))%3B%20%0A%0A%20%20%7D%0A%20%20return%20test.join(%22%20%22)%3B%0A%20%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var test = [];
var myArray = [];
function titleCase(str) {
  myArray = str.toLowerCase().split(' ');
  for (i = 0; i < myArray.length; i++) {
   test.push(myArray[i][0].toUpperCase() + myArray[i].substr(1)); 

  }
  return test.join(" ");
 
}

titleCase("sHoRt AnD sToUt");

```

**Comment by ltegman** [comment]
Global variables are bad news. Think about what happens if you run that function more than once. Thanks and happy coding!

**Comment by JBuji** [comment]
My code:
`function titleCase(str) {
  str = str.toLowerCase().split(" ");
  
  for (var i in str)
    str[i] = str[i][0].toUpperCase()+str[i].substr(1);
  
   return str.join(" ");
}
titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");
`

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
