### ISSUE TITLE
French translation of Responsive Design with Bootstrap

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/FreeCodeCamp#7631]
- [x] Use Responsive Design with Bootstrap Fluid Containers 
- [x] Make Images Mobile Responsive 
- [x] Center Text with Bootstrap 
- [x] Create a Bootstrap Button 
- [x] Create a Block Element Bootstrap Button 
- [x] Taste the Bootstrap Button Color Rainbow 
- [x] Call out Optional Actions with Button Info 
- [x] Warn your Users of a Dangerous Action 
- [x] Use the Bootstrap Grid to Put Elements Side By Side 
- [x] Ditch Custom CSS for Bootstrap 
- [x] Use Spans for Inline Elements 
- [x] Create a Custom Heading 
- [x] Add Font Awesome Icons to our Buttons 
- [x] Add Font Awesome Icons to all of our Buttons 
- [x] Responsively Style Radio Buttons 
- [x] Responsively Style Checkboxes 
- [x] Style Text Inputs as Form Controls 
- [x] Line up Form Elements Responsively with Bootstrap 
- [x] Create a Bootstrap Headline 
- [x] House our page within a Bootstrap Container Fluid Div 
- [x] Create a Bootstrap Row 
- [x] Split your Bootstrap Row 
- [x] Create Bootstrap Wells 
- [x] Add Elements within your Bootstrap Wells 
- [x] Apply the Default Bootstrap Button Style 
- [x] Create a Class to Target with jQuery Selectors 
- [x] Add ID Attributes to Bootstrap Elements 
- [x] Label Bootstrap Wells 
- [x] Give Each Element a Unique ID 
- [x] Label Bootstrap Buttons 
- [x] Use Comments to Clarify Code

**Comment by theflametrooper** [comment]
#7625

**Comment by theflametrooper** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7625

**Comment by ck7up** [comment]
Utiliser un design réactif avec les conteneurs de fluide Bootstrap
 Réaliser des images mobiles
 Centre de texte avec Bootstrap
 Créer un bouton Bootstrap
 Créer un bouton d'amorçage d'élément de bloc
 Goût du bouton Bootstrap Couleur Rainbow
 Appeler Actions facultatives avec Info sur les boutons
 Avertissez vos utilisateurs d'une action dangereuse
 Utiliser la grille d'amorçage pour mettre les éléments côte à côte
 Ditch CSS personnalisé pour Bootstrap
 Utiliser Spans pour les éléments Inline
 Créer un titre personnalisé
 Ajoutez des icônes impressionnantes à nos boutons
 Ajoutez des icônes impressionnantes de polices à tous nos boutons
 Boutons Réponse Style Style
 Boîtes à cocher
 Entrées de texte de style en tant que contrôles de formulaire
 Élaborez les éléments du formulaire de manière responsable avec Bootstrap
 Créer un titre Bootstrap
 Maison notre page dans un Bootstrap Container Fluid Div
 Créer une ligne Bootstrap
 Diviser votre ligne de démarrage
 Créer Bootstrap Wells
 Ajouter des éléments dans vos poches Bootstrap
 Appliquer le style de bouton Bootstrap par défaut
 Créer une classe à cibler avec jQuery Selectors
 Ajouter des attributs ID aux éléments Bootstrap
 Étiquette Bootstrap Wells
 Donnez à chaque élément un ID unique
 Bootstrap Badges publicitaires
 Utiliser les commentaires pour clarifier le code
