### ISSUE TITLE
French translation of Gear up for Success

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/FreeCodeCamp#7632]
- [x] Join our LinkedIn Alumni Network 
- [x] Join our Subreddit 
- [x] Read Coding News on our Medium Publication 
- [x] Watch us Code Live on Twitch.tv
- [x] Commit to a Goal and a Nonprofit

**Comment by elazzabi** [comment]
Working on it

**Comment by elazzabi** [comment]
Translation ready
