### ISSUE TITLE
French translation of Basic Front End Development Projects

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7634]
- [ ] Get Set for our Front End Development Projects
- [ ] Build a Tribute Page 
- [ ] Build a Personal Portfolio Webpage

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #64](https://github.com/FreeCodeCamp/TranslationExpansion/issues/64) via [**ZenHub**](https://www.zenhub.com/)
