### ISSUE TITLE
French translation of Basic Algorithm Scripting

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7637]
- [ ] Get Set for our Algorithm Challenges 
- [ ] Reverse a String 
- [ ] Factorialize a Number 
- [ ] Check for Palindromes 
- [ ] Find the Longest Word in a String 
- [ ] Title Case a Sentence 
- [ ] Return Largest Numbers in Arrays 
- [ ] Confirm the Ending 
- [ ] Repeat a string repeat a string 
- [ ] Truncate a string 
- [ ] Chunky Monkey 
- [ ] Slasher Flick 
- [ ] Mutations 
- [ ] Falsy Bouncer 
- [ ] Seek and Destroy 
- [ ] Where do I belong 
- [ ] Caesars Cipher

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #67](https://github.com/FreeCodeCamp/TranslationExpansion/issues/67) via [**ZenHub**](https://www.zenhub.com/)
