### ISSUE TITLE
French translation of JSON APIs and Ajax

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7638]
- [ ] Trigger Click Events with jQuery 
- [ ] Change Text with Click Events 
- [ ] Get JSON with the jQuery getJSON Method 
- [ ] Convert JSON Data to HTML 
- [ ] Render Images from Data Sources 
- [ ] Prefilter JSON 
- [ ] Get Geo-location Data

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #68](https://github.com/FreeCodeCamp/TranslationExpansion/issues/68) via [**ZenHub**](https://www.zenhub.com/)
