### ISSUE TITLE
French translation of Intermediate Front End Development Projects

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7639]
- [ ] Build a Random Quote Machine 
- [ ] Show the Local Weather 
- [ ] Build a Wikipedia Viewer 
- [ ] Use the Twitch.tv JSON API

**Comment by elazzabi** [comment]
Working on it

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #69](https://github.com/FreeCodeCamp/TranslationExpansion/issues/69) via [**ZenHub**](https://www.zenhub.com/)
