### ISSUE TITLE
French translation of Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/FreeCodeCamp#7640]
- [x] Sum All Numbers in a Range 
- [x] Diff Two Arrays 
- [x] Roman Numeral Converter 
- [x] Where art thou 
- [x] Search and Replace 
- [x] Pig Latin 
- [x] DNA Pairing 
- [x] Missing letters 
- [x] Boo who 
- [x] Sorted Union 
- [x] Convert HTML Entities 
- [x] Spinal Tap Case 
- [x] Sum All Odd Fibonacci Numbers 
- [x] Sum All Primes 
- [x] Smallest Common Multiple 
- [x] Finders Keepers 
- [x] Drop it 
- [x] Steamroller 
- [x] Binary Agents 
- [x] Everything Be True 
- [x] Arguments Optional

**Comment by NaitoKenzo** [comment]
- Additionner tous les nombres d'une série
- Comparer 2 arrays
- Convertir en nombres romains
- Où êtes vous ? (Litterally but would probably be better to translate as "Oh Roméo !")
- Chercher et remplacer
- Verlan britanique (pig latin is a British concept which doesn't exactly translate, the closest widely known thing would be verlan)
- Couples d'ADN
- Lettres manquantes
- Boo qui
- Couple arrangé
- Convertir les entités HTML
- Cas de ponction lombaire
- Additionner tous les nombre de Fibonacci impairs
- Additionner tous les nombres primaires
- Plus petit commun multiple
- Qui trouve garde
- Laisse tomber
- Rouleau compresseur
- Agent binaire
- Tout doit être vrai
- Arguments en option

**Comment by NaitoKenzo** [comment]
I'll do a PR with those translations if that's ok.

**Comment by theflametrooper** [comment]
Awesome!

**Comment by NaitoKenzo** [comment]
I'm adding those to the json file along with the descriptions but I can't find the French version of the website. Is it WIP?

**Comment by theflametrooper** [comment]
There won't be a french version until we've finished translating the whole curriculum.

**Comment by NaitoKenzo** [comment]
Oh, right, let's get it done then.

**Comment by theflametrooper** [comment]
Thanks. Use this for chatting in future: https://gitter.im/FreeCodeCamp/TranslationFrench
