### ISSUE TITLE
French translation of Advanced Algorithm Scripting

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7641]
- [ ] Validate US Telephone Numbers 
- [ ] Symmetric Difference 
- [ ] Exact Change 
- [ ] Inventory Update 
- [ ] No repeats please 
- [ ] Friendly Date Ranges 
- [ ] Make a Person 
- [ ] Map the Debris 
- [ ] Pairwise

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #70](https://github.com/FreeCodeCamp/TranslationExpansion/issues/70) via [**ZenHub**](https://www.zenhub.com/)
