### ISSUE TITLE
French translation of Advanced Front End Development Projects

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7642]
- [ ] Build a JavaScript Calculator 
- [ ] Build a Pomodoro Clock 
- [ ] Build a Tic Tac Toe Game 
- [ ] Build a Simon Game

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #72](https://github.com/FreeCodeCamp/TranslationExpansion/issues/72) via [**ZenHub**](https://www.zenhub.com/)
