### ISSUE TITLE
French translation of React Projects

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7646]
- [ ] Build a Markdown Previewer 
- [ ] Build a Camper Leaderboard 
- [ ] Build a Recipe Box 
- [ ] Build the Game of Life 
- [ ] Build a Roguelike Dungeon Crawler Game

**Comment by apswak** [comment]
.

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #76](https://github.com/FreeCodeCamp/TranslationExpansion/issues/76) via [**ZenHub**](https://www.zenhub.com/)
