### ISSUE TITLE
French translation of Data Visualization Projects

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7648]
- [ ] Visualize Data with a Bar Chart 
- [ ] Visualize Data with a Scatterplot Graph 
- [ ] Visualize Data with a Heat Map 
- [ ] Show Relationships with a Force Directed Graph 
- [ ] Map Data Across the Globe

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #78](https://github.com/FreeCodeCamp/TranslationExpansion/issues/78) via [**ZenHub**](https://www.zenhub.com/)
