### ISSUE TITLE
French translation of Automated Testing and Debugging

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7650]
- [ ] Use the JavaScript Console
- [ ] Using typeof

**Comment by ScrumUser1** [comment]
working on it

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #79](https://github.com/FreeCodeCamp/TranslationExpansion/issues/79) via [**ZenHub**](https://www.zenhub.com/)
