### ISSUE TITLE
French translation of API Projects

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7651]
- [ ] Get Set for our Back End Development Projects Incomplete
- [ ] Timestamp Microservice 
- [ ] Request Header Parser Microservice 
- [ ] URL Shortener Microservice 
- [ ] Image Search Abstraction Layer 
- [ ] File Metadata Microservice

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #80](https://github.com/FreeCodeCamp/TranslationExpansion/issues/80) via [**ZenHub**](https://www.zenhub.com/)
