### ISSUE TITLE
French translation of Dynamic Web Application Projects

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#7652]
- [ ] Build a Voting App 
- [ ] Build a Nightlife Coordination App 
- [ ] Chart the Stock Market 
- [ ] Manage a Book Trading Club 
- [ ] Build a Pinterest Clone

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #81](https://github.com/FreeCodeCamp/TranslationExpansion/issues/81) via [**ZenHub**](https://www.zenhub.com/)
