### ISSUE TITLE
Steamroller solution working fine, but not passing the level

### ISSUE THREAD

**Issue by shrihari-balasubramani** [FreeCodeCamp/FreeCodeCamp#7655]
Challenge [Steamroller](https://www.freecodecamp.com/challenges/steamroller#?solution=var%20gloabArr%20%3D%5B%5D%3B%0Afunction%20getMyBabies(arr)%7B%0A%20%20%20var%20count%20%3D0%3B%0A%20%20for(count%3D0%3Bcount%3Carr.length%3Bcount%2B%2B)%7B%0A%20%20%20%20%20%20if(Array.isArray(arr%5Bcount%5D))%7B%0A%20%20%20%20%20%20%20%20getMyBabies(arr%5Bcount%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20gloabArr.push(arr%5Bcount%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0Afunction%20steamroller(arr)%20%7B%0A%20%20getMyBabies(arr)%3B%0A%20%20return%20gloabArr%3B%0A%20%20%0A%7D%0Asteamroller(%5B1%2C%20%7B%7D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var gloabArr =[];
function getMyBabies(arr){
   var count =0;
  for(count=0;count<arr.length;count++){
      if(Array.isArray(arr[count])){
        getMyBabies(arr[count]);
      }
    else{
      gloabArr.push(arr[count]);
    }
  }
}
function steamroller(arr) {
  getMyBabies(arr);
  return gloabArr;
  
}
steamroller([1, {}, [3, [[4]]]]);

```

**Comment by ltegman** [comment]
Global variables are bad. Think about what your code does if you call this function more than once. Thanks and happy coding!
