### ISSUE TITLE
Change the Font Size of an Element. 100% zoom in the browser, still won't work.

### ISSUE THREAD

**Issue by dude920228** [FreeCodeCamp/FreeCodeCamp#7658]
I have this code, which should pass the tests:
```
<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16 px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Purr jump eat the grass</p>
<p>Purr jump eat the grass</p>
```
It still won't pass. I'm using firefox.

**Comment by drk7891** [comment]
Have you checked out [FreeCodeCamp's help channel on Gitter?](https://gitter.im/FreeCodeCamp/FreeCodeCamp)

This is not a bug but wrong syntax. The issue is where you're setting the `font-size`. You're setting it to `16 px` where it should be `16px`.

**Comment by ltegman** [comment]
@drk7891 Is correct. Thanks and happy coding!

**Comment by kikenz** [comment]
Using Chrome ver 49 (up-to-date) and I cannot pass.

<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by GuominWu** [comment]
I run into the same problem, but got it working, but I don't know why.   

works with:
.red-text {color: red;}
p{font-size: 16px;}

not working with:
.red-text {color: red;}
.p{font-size:16px;}

If the red-text class needs a . in front of class name, why not the p?

**Comment by jeremy0804** [comment]
@kikenz the .red-text class and the element p attribute should be on separate lines with separate curly braces. 

@GouminWu Because the p is an element, not a class. Elements do not get the dot.

**Comment by georgebakerus** [comment]
@GuominWu the . means "for elements with a class of this name, apply this style".   Writing .p  {style...] means "apply this style to elements with class named p" .  So for example the style will be applied to 
<h2 class=p> some_header2_content </h2>

Without the period, writing p {style...} means "apply this style to all p elements".  So for example the style will be applied to 
<p>some_paragraph_text</p>
<p class=red-text>more_text</p>
and all other <p elements

**Comment by moniquelow** [comment]
This worked for me:
`<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
`

**Comment by moniquelow** [comment]
This worked for me:

```
<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>


```

**Comment by azumah94** [comment]
Thanks @moniquelow.
