### ISSUE TITLE
FrontEnd tutorial must call https instead of http

### ISSUE THREAD

**Issue by johnsalcedonetwork** [FreeCodeCamp/FreeCodeCamp#7659]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* During the FrontEnd tutorial, the instruction indicates to call the Google Lobster font by using the link (http://www.google.com/fonts#UsePlace:use/Collection:Lobster), but, it would not reflect on the preview unless https is used instead of http.

#### Browser Information
Google Chrome
Windows 8.1

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/17956698/13902475/dce43dd8-ee84-11e5-9616-135c1a5dd1d4.png)

**Comment by alistermada** [comment]
There is already a fix for this on the way: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7613.

**Comment by raisedadead** [comment]
Thanks @alistermada

**Comment by Ahmedrezk** [comment]
stop emailing me plz

**Comment by sludge256** [comment]
@Ahmedrezk change your settings here http://bugs.openweathermap.org/projects/api/wiki/Weather_Data
