### ISSUE TITLE
Create a Bootstrap Row

### ISSUE THREAD

**Issue by Nadura** [FreeCodeCamp/FreeCodeCamp#7663]
Challenge [Create a Bootstrap Row](https://www.freecodecamp.com/challenges/create-a-bootstrap-row) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 4.4.2; SM-P605V Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.99 Safari/537.36 OPR/35.0.2070.100283</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <div class="row">
  <h3 class="text-primary text-center">jQuery Playground</h3>
<div></div>
</div>
</div>

```

**Comment by ltegman** [comment]
Issue does not describe a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for help and if they confirm what you're seeing is a bug file an issue with a detailed description of the problem and any steps to reproduce it. Thanks and happy coding!

**Comment by Nadura** [comment]
Sorry I was not finished editing the the question, but I got the answer this link is the answer:https://www.freecodecamp.com/challenges/create-a-bootstrap-row#?solution=<div class%3D"container-fluid">   <h3 class%3D"text-primary text-center">jQuery Playground<%2Fh3>      <div class%3D"row"><%2Fdiv>   <%2Fdiv>
