### ISSUE TITLE
This lesson needs to be looked over, had to look up troubleshooting.

### ISSUE THREAD

**Issue by Og-Morrow** [FreeCodeCamp/FreeCodeCamp#7664]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStr%3B%0AmyStr%20%3D%20%22%5C%5C%20%5Ct%20%5Ct%20%5Cr%20%5Cn%22%3B%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr;
myStr = "\\ \t \t \r \n";// Change this line



```

**Comment by kalunlee136** [comment]
@Og-Morrow what exactly are you having trouble with?

**Comment by cannelflow** [comment]
what is the issue i went to your link working for me

**Comment by Og-Morrow** [comment]
I fixed the issue. I'm not experienced enough to speak with clarity but the
myStr = " escape sequences "; had to go below and the lesson made it clear
that just the line had to be changed but when you do that then the code
doesn't work

**Comment by cannelflow** [comment]
exercise says Encode the following sequence, separated by spaces:
backslash tab tab carriage-return new-line and assign it to myStr and that is what you did there 
var  myStr;
myStr = "\\ \t \t \r \n";// Change this line
or you can just write like
var myStr = "\\ \t \t \r \n";// Change this line

**Comment by Og-Morrow** [comment]
Right, I tried is this way "var myStr = "\ \t \t \r \n";// Change this line" and just could not figure out why it wasnt working, heres the page i found the answer. I just wanted to help others before they have to go throught the same thing.
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5673

**Comment by cannelflow** [comment]
do like 
`
var myStr = "\\ \t \t \r \n";// Change this line 
`
not like
`
var myStr = "\ \t \t \r \n
`
can you please come at https://gitter.im/FreeCodeCamp/Help

**Comment by ltegman** [comment]
Closing as resolved. Thanks and happy coding!
