### ISSUE TITLE
Fix the tedious spacing issue for the second string by making it clear there should be one there.

### ISSUE THREAD

**Issue by Og-Morrow** [FreeCodeCamp/FreeCodeCamp#7665]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3B%0A%0AmyStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22%20This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr;

myStr = "This is the start." + " This is the end.";



```

**Comment by ltegman** [comment]
I don't think we could make it much clearer without doing it for you:

>__Note__
Watch out for spaces. Concatenation does not add spaces between concatenated strings, so you'll need to add them yourself.

Thanks and happy coding!
