### ISSUE TITLE
Challenge Completed - No Congratulatory Sound

### ISSUE THREAD

**Issue by TuckerDev** [FreeCodeCamp/FreeCodeCamp#7666]
When completing challenges there are no sounds or sound effects.

I was thinking perhaps there could be some sort of congratulatory ding, similar to how MMORPGs are.

**Comment by will2b** [comment]
I know nothing about computers or the lingo and feel incompetent when it
comes to this

**Comment by erictleung** [comment]
Bike shedding or worth pursuing? @QuincyLarson @BerkeleyTrue

**Comment by raisedadead** [comment]
Closing as stale. 

Please discuss this in the chat rooms first, we can always take this up if there is a popular demand.
