### ISSUE TITLE
Truncate a string with ternary operator

### ISSUE THREAD

**Issue by drk7891** [FreeCodeCamp/FreeCodeCamp#7669]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20var%20newString%20%3D%20str%3B%0A%20%20var%20trim%3B%0A%20%20%0A%20%20num%20%3C%203%20%3F%20trim%20%3D%20num%20%3A%20trim%20%3D%20num%20-%203%3B%0A%20%20%0A%20%20if(str.length%20%3E%20num)%20%7B%0A%20%20%20%20newString%20%3D%20newString.slice(0%2C%20trim)%20%2B%20%22...%22%3B%0A%20%20%7D%0A%20%20return%20newString%3B%0A%7D%0A%0Atruncate(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.

My code:
```javascript
function truncate(str, num) {
  var newString = str;
  var trim;
  
  num < 3 ? trim = num : trim = num - 3;
  
  if(str.length > num) {
    newString = newString.slice(0, trim) + "...";
  }
  return newString;
}

truncate("A-tisket a-tasket A green and yellow basket", 11);
```

Using a ternary operator to check if the `num` is less than 3 results in all tests passing but throws an error in the editor. The error is on `num - 3` and states `Expected an assignment or function call and instead saw an expression`.

**Comment by ltegman** [comment]
This is normal. It's the linter telling you this is a bad practice use of a ternary that results in hard to read code. It should pass because the code isn't technically wrong, it's just something you probably want to not do. Thanks and happy coding!
