### ISSUE TITLE
Bonfire: Mutations 'more info' is misleading.

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/freecodecamp#767]
Afer spending around 6 hours on this bonfire and getting help from several other campers, we all agreed that the Array.sort() information is not necessary (or even incorrect) for this bonfire. The easiest and quickest solution can be done with Array.indexOf()

**Comment by QuincyLarson** [comment]
@akiralaine Thank you for your feedback on this. I will update the MDN link based on your suggestion.
