### ISSUE TITLE
Size Your Images = eBrick Wall

### ISSUE THREAD

**Issue by kreddibletrout** [FreeCodeCamp/FreeCodeCamp#7670]
Hey there.
So... i can't get past the Size Your Images test. I've checked around and it looks like my code is the cat's meow. I've seen others have had a problem with it as well but can't seem to find any resolution. I've refreshed, used another computer, normally work in Firefox but dusted off IE but to no avail...

Any help here? The challenge won't let me pass. I'm stuck there.

Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
  .smaller-image {
    width: 100px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by kreddibletrout** [comment]
i suck.

**Comment by kreddibletrout** [comment]
can I not erase that issue? delete it? I'm embarrassed.

**Comment by phoenixrising77** [comment]
Hi there, I'm a newcomer to Free Code Camp and I'm stuck with the same issue.  I've checked and rechecked the code and it's fine and I've zoomed in and out and tried different browsers to no avail.  I'm wondering if you solved this since you last commented here and if you could help point me in the right direction. cheers.

**Comment by kreddibletrout** [comment]
Hey 77,
for me, it was my code. I was missing something. when you see it, it's obvious. double check it a few more times. focus on the HTML part of your img element for the clue. if yours is the same as mine above, the problem lies there. I forgot to add something to it.
lemme know if you want more clues.
