### ISSUE TITLE
kkk

### ISSUE THREAD

**Issue by maotao1** [FreeCodeCamp/FreeCodeCamp#7673]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=var%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch%20(card)%20%7B%0Acase%20%27J%27%3A%0Acase%20%27Q%27%3A%0Acase%20%27K%27%3A%0Acase%20%27A%27%3A%0Acase%2010%3A%0Acount--%3B%0A%7D%0Aif%20(count%20%3C%207)%20%7B%0Acount%2B%2B%3B%0A%7D%0Aif%20(count%20%3C%3D%200)%20%7B%0Areturn%20count%20%2B%20%22%20Hold%22%3B%0A%7Delse%20if%20(count%20%3E%200)%20%7B%0Areturn%20count%20%2B%20%22%20Bet%22%3B%0A%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc(%27K%27)%3B%20cc(%27A%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var count = 0;

function cc(card) {
  // Only change code below this line
  switch (card) {
case 'J':
case 'Q':
case 'K':
case 'A':
case 10:
count--;
}
if (count < 7) {
count++;
}
if (count <= 0) {
return count + " Hold";
}else if (count > 0) {
return count + " Bet";
}

  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by niyasc** [comment]
What is the error message you're getting?
