### ISSUE TITLE
Use of Angular JS in demo application

### ISSUE THREAD

**Issue by niyasc** [FreeCodeCamp/FreeCodeCamp#7674]
Challenge [Build a Wikipedia Viewer](https://www.freecodecamp.com/challenges/build-a-wikipedia-viewer) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Model App given with challenge make use of Angular JS which is not a part of curriculum. I don't think that it is a fair example. It would be better if same example is recreated using topics covered in this website.

**Comment by alistermada** [comment]
I don't think most people even know that the sample project uses Angular since the first rule says:
> Don't look at the example project's code. Figure it out for yourself.

All our app needs to do is fulfill the user stories. None of them require Angular. Besides, we're encouraged to "use whichever libraries or APIs [we] need" and "give it [our] own personal style".

**Comment by ltegman** [comment]
Yeah, this is not a problem. People are still free to use Angular if they choose to and the example can be recreated without Angular. Thanks and happy coding!
