### ISSUE TITLE
result is correct but doesn't recognize it

### ISSUE THREAD

**Issue by marshall20** [FreeCodeCamp/FreeCodeCamp#7678]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20var%20array%20%3D%20str.split('%20')%3B%0A%20%20str%3D%22%22%3B%0A%20%20for(var%20i%20%3D0%3B%20i%20%3C%20array.length%3Bi%2B%2B)%7B%0A%20%20%20%20var%20string%3D%20array%5Bi%5D.substring(1%2C%20array%5Bi%5D.length)%3B%0A%20%20%20%20str%2B%3D%20array%5Bi%5D%5B0%5D.toUpperCase()%20%2Bstring.toLowerCase()%20%2B%22%20%22%3B%0A%20%20%7D%0A%20%20return%20str%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  var array = str.split(' ');
  str="";
  for(var i =0; i < array.length;i++){
    var string= array[i].substring(1, array[i].length);
    str+= array[i][0].toUpperCase() +string.toLowerCase() +" ";
  }
  return str;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```

**Comment by raisedadead** [comment]
You are almost there @marshall20 !
Check your code, and use some logs there is an extra space in your output!

If you are stuck please visit our dedicated [Chat Room for JavaScript/Algorithms](https://gitter.im/FreeCodeCamp/HelpJavaScript) 

Thanks and Happy Coding!

**Comment by frempongandrews** [comment]
Hi. Same issue here

     `         function titleCase(str) {

	//string to lowercase
	var low = str.toLowerCase();

	//split words string

	var words = low.split(" ");


	//get length of string(words)

	var len = words.length;

	//iterate each word by using length in for loop
	var sentence = "";


	for (i = 0; i <= len-1; i++){
		//getting first letter to uppercase
		var firstLet = words[i].substring(0,1).toUpperCase();
		//getting rest of letters
		var rest = words[i].substring(1);
		sentence += firstLet + rest + " ";
		
		
	}

	    console.log(sentence);

	    return;
        
 
       }


         titleCase("I'm a little tea pot and I like dancing");`

**Comment by adrielzarate** [comment]
yes, me too. My code:

		function titleCase(str) {

			str = str.split(' ');
			var aux = [];

			for ( var i = 0; i < str.length; i++ ) {

				aux.push(str[i][0].toUpperCase());
					
				for ( var j = 1; j < str[i].length; j++ ) {
					aux.push(str[i][j].toLowerCase());
				}

				aux.push(' ');

			}

			aux = aux.join();
			str = aux.replace(/,/g,'');

			return str;
		}

		titleCase("sHoRt AnD sToUt");
