### ISSUE TITLE
Bug in Waypoint: Escaping Literal Quotes in String

### ISSUE THREAD

**Issue by ajaybti** [FreeCodeCamp/FreeCodeCamp#7679]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3D%22I%20am%20a%20%5C%22double%20quoted%5C%22string%20inside%20%5C%22double%20quotes%5C%22%22%3B%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr="I am a \"double quoted\"string inside \"double quotes\"";// Change this line



```

**Comment by sludge256** [comment]
Pay careful attention to all spaces, or lack thereof, in your output to see your error. Ask in the relevant [help chat](https://gitter.im/FreeCodeCamp/Help) next time, before posting an issue on Github. Thank you.
