### ISSUE TITLE
Font Typo in CatPhotoApp

### ISSUE THREAD

**Issue by MarkBLittle** [FreeCodeCamp/FreeCodeCamp#7683]
The link to the font should start with "https://" rather than "http://" - When I change it before submitting, the font goes to Lobster from Monospace. However, when the next lesson starts, the https switches back to http and I am stuck with Monospace again. It's a minor issue, but a small annoyance.

**Comment by raisedadead** [comment]
@MarkBLittle We are really sorry about that!

This is a know issue with a latest SSL upgrade across the website, we have a fix ready, it will reach the main website real soon! Thanks for your patience meanwhile.

Refer #7613
