### ISSUE TITLE
Spelling error on waypoint-add-different-a-margin-to-each-side-of-an-element

### ISSUE THREAD

**Issue by ghost** [FreeCodeCamp/freecodecamp#769]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-a-margin-to-each-side-of-an-element has an issue. 

There is a spelling error in the title of the issue, "Add Different a Margin" should be "Add **a** Different Margin"
![screen shot 2015-05-31 at 10 16 26 am](https://cloud.githubusercontent.com/assets/775781/7902184/387a9172-077e-11e5-9bbd-243b76bf84c0.png)

**Comment by LumenTeun** [comment]
I'll be making a PR with this fixed in just a minute.

**Comment by QuincyLarson** [comment]
@ghost thanks for catching this! @lumenteun I saw you'd fixed this so I'm closing this.

**Comment by QuincyLarson** [comment]
@ghost thanks for catching this. @lumenteun thanks for fixing it! I'm closing this issue.
