### ISSUE TITLE
The www.freecodecamp.com page isn’t working

### ISSUE THREAD

**Issue by Dipeshwagle** [FreeCodeCamp/FreeCodeCamp#7691]
Whent i try to open the website it says,

> www.freecodecamp.com redirected you too many times.

**Comment by raisedadead** [comment]
@Dipeshwagle Thanks for the issue.

We need more information for this:
1. Whats your region/location?
2. OS and Browsers?
3. Are you behind any firewalls, proxies, for example like at work place or college/school etc? 
4. Can you check on any other device if you are facing the same?
5. Have you tried clearing your cache/cookies etc?

Please let us know if anyone else around you is facing the same.

**Comment by Dipeshwagle** [comment]
It's working now,if it happens again I'll make sure all details are included. :smile:

**Comment by Max-Villafranca** [comment]
I have the same problem, its letting me in sometimes,

**Comment by raisedadead** [comment]
@Max-Villafranca We were facing some issues, it should be resolved now.
