### ISSUE TITLE
Issue with Wikipedia Search

### ISSUE THREAD

**Issue by EmilianFlorea** [FreeCodeCamp/FreeCodeCamp#7696]
Challenge [Build a Wikipedia Viewer](https://www.freecodecamp.com/challenges/build-a-wikipedia-viewer) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Mixed content error, see the screenshot attached. Change the calls to the wikipedia api to use the https protocol.
![screenshot_2016-03-22_17-28-32](https://cloud.githubusercontent.com/assets/16718608/13957066/5dff8a36-f04b-11e5-8ece-842f019e3b1b.png)

**Comment by raisedadead** [comment]
Thanks @EmilianFlorea this is a known issue with the recent `https` update. We are still in the process of auditing and fixing all the pages/pens in the challenges.

Please follow #7700 for updates.
