### ISSUE TITLE
Build web apps with expressjs solutions provided

### ISSUE THREAD

**Issue by biganth** [FreeCodeCamp/FreeCodeCamp#7698]
#### Issue Description
The setup script below clones https://github.com/reddock/expressworks which provides the solutions to all of the problems. Was this the intended behavior? Should this be a different repo without the solutions?

As detailed here: https://www.freecodecamp.com/challenges/build-web-apps-with-expressjs 

```git clone https://github.com/FreeCodeCamp/fcc-expressworks.git && chmod 744 fcc-expressworks/setup.sh && fcc-expressworks/setup.sh && source ~/.profile ``` 

![3-22-2016 12-28-38 pm](https://cloud.githubusercontent.com/assets/16448/13959212/afe3d662-f029-11e5-9319-3ba706a39010.png)

#### Screenshot

**Comment by ltegman** [comment]
This is expected. These tutorials are purely for student benefit, so we're operating on the assumption that if someone wants to spend the time on them they won't just look at the answers. Thanks and happy coding!
