### ISSUE TITLE
RegExp: Literal notation vs constructor

### ISSUE THREAD

**Issue by LumenTeun** [FreeCodeCamp/freecodecamp#770]
So, this is probably scraping the very bottom of the list of priorities, but I'm wondering about how RegExp is used in test cases.
Right now, all examples I've found use the constructor, like this:
```javascript
new RegExp('like this photo','gi').test($('.btn').text())
```

The [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) says to "[u]se literal notation when the regular expression will remain constant", which it will most, if not all, of the time.

The same RegExp you see above as a constructor would be written like this in literal notation:
```javascript
/like this photo/gi.test($('.btn').text())
```
This looks, in my opinion, cleaner, and I guess since it uses less characters it would also take up a minimal amount of less space.
On the other hand, the constructor makes it more obvious that it is a regular expression.

Like I said, not a very important issue, but it's also not too hard to make the switch. What do you guys think?

**Comment by terakilobyte** [comment]
This has stemmed from the fact that all of these tests live as strings
inside json files. Using literal syntax was proving to be an absolute PITA
for some of the tests. If you'd like to take a crack at refactoring them to
use literal vs constructor I'd be open to looking at the PR.

**Comment by BerkeleyTrue** [comment]
For better grokability, you usually wrap Regex literals in parentheses.

```js
(/like this photo/gi).test($('.btn').text())
```
IMHO the cleanest way to do Regex.

**Comment by LumenTeun** [comment]
Oh yeah, that looks better @BerkeleyTrue. I'll give it a try eventually, working on some simple test case improvements right now.

**Comment by QuincyLarson** [comment]
It looks like this issue was fixed with @lumenteun's PR earlier so I'm closing it. I agree with @terakilobyte that it's not only a PITA, but bad user experience to be so rigid about accepting input from the user.
