### ISSUE TITLE
HTTPS : Audit all codepen example links in the challenges for CSP issues.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#7700]
After the `HTTPS` upgrade mixed content and CSP issues have been reported, with some of the codepen.io example links.

These need to be updated to `https` in the challenge links as well as within the code of the individual Pens for avoiding the CSP issues.

### List of Pens :

Portfolio page of the Free Code Camp account on CodePen.io : http://codepen.io/FreeCodeCamp

#### Basic Front End Development Projects:
| Challenge | Link | Update link to `https` | Update links in Pen 
| ------------- | ----- | --------------------------- |------------------------- | ------- |
| Build a Tribute Page | [Link](http://codepen.io/FreeCodeCamp/full/wMQrXV) | Yes | Yes  
| Build a Personal Portfolio Webpage | [Link](http://codepen.io/FreeCodeCamp/full/VemmoX) | Yes | Yes 

#### Intermediate Front End Development Projects:
| Challenge | Link | Update link to `https` | Update links in Pen 
| ------------- | ----- | --------------------------- |------------------------- | ------- |
| Build a Random Quote Machine | [Link](http://codepen.io/FreeCodeCamp/full/bELoPJ) | Yes | Yes  
| Show the Local Weather | [Link](http://codepen.io/FreeCodeCamp/full/bELRjV) | Yes | Yes 
| Build a Wikipedia Viewer | [Link](http://codepen.io/FreeCodeCamp/full/pgNRvJ) | Yes | Yes 
| Use the Twitchtv JSON API | [Link](http://codepen.io/FreeCodeCamp/full/adBpOw) | Yes | Yes 

#### Advanced Front End Development Projects:
| Challenge | Link | Update link to `https` | Update links in Pen 
| ------------- | ----- | --------------------------- |------------------------- | ------- |
| Build a JavaScript Calculator | [Link](http://codepen.io/FreeCodeCamp/full/zrRzMR) | Yes | Not Required  
| Build a Pomodoro Clock | [Link](http://codepen.io/FreeCodeCamp/full/VemPZX) | Yes | Yes 
| Build a Tic Tac Toe Game | [Link](http://codepen.io/FreeCodeCamp/full/adBpvw) | Yes | Not Required 
| Build a Simon Game | [Link](http://codepen.io/Em-Ant/full/QbRyqq) | Yes | Yes 

#### React Projects:
| Challenge | Link | Update link to `https` | Update links in Pen 
| ------------- | ----- | --------------------------- |------------------------- | ------- |
| Build a Markdown Previewer | [Link](http://codepen.io/FreeCodeCamp/pen/obYYqW) | Yes | Yes  
| Build a Camper Leaderboard | [Link](http://codepen.io/FreeCodeCamp/full/qbqqJm) | Yes | Yes 
| Build a Recipe Box | [Link](http://codepen.io/FreeCodeCamp/full/LGbbqj) | Yes | Not Required 
| Build the Game of Life | [Link](http://codepen.io/FreeCodeCamp/full/dGOOrZ) | Yes | Yes 
| Build a Roguelike Dungeon Crawler Game | [Link](http://codepen.io/FreeCodeCamp/full/dGOOEJ) | Yes | Not Required 

#### Data Visualization Projects:
| Challenge | Link | Update link to `https` | Update links in Pen 
| ------------- | ----- | --------------------------- |------------------------- | ------- |
| Visualize Data with a Bar Chart | [Link](http://codepen.io/FreeCodeCamp/full/adBBWd) | Yes | Yes  
| Visualize Data with a Scatterplot Graph | [Link](http://codepen.io/FreeCodeCamp/full/GoNNEy) | Yes | Yes  
| Visualize Data with a Heat Map | [Link](http://codepen.io/FreeCodeCamp/full/rxWWGa) | Yes | Not Required 
| Show Relationships with a Force Directed Graph | [Link](http://codepen.io/FreeCodeCamp/full/KVNNXY) | Yes | Yes  
| Map Data Across the Globe | [Link](http://codepen.io/FreeCodeCamp/full/mVEJag) | Yes | Not Required  

`Updating Lists...`

#### Dynamic Web Application Projects:
----

**NOTE to Contributors** :

 1. Please check through the Pens and if any of them are using the `http` resources (for example Wikipedia viewer uses `http://en.wikipedia.org/wiki/Special:Random`) within the Pen's code.
 2. If they do, please fork them, update the code to use `https` resources wherever possible.
 3. CAUTION  : Don't modify any logic without confirmation! Just move to `https`
 4. Add a comment on this thread once done.
 5. @QuincyLarson can fork back the corrected challenges to the Free Code Camp Page
 6. Finally the affected, challenges can be updated to reflect the `https` links

Please ping me : [@raisedadead](https://gitter.im/raisedadead) on Gitter if you need any assistance.

Thanks!

**Comment by raisedadead** [comment]
## First Time contributors are highly encouraged to take this as their first contribution to Open Source.

**Comment by theflametrooper** [comment]
@raisedadead Can I help with this?

**Comment by theflametrooper** [comment]
Working on it

**Comment by theflametrooper** [comment]
Everything has been updated to `https`

| Challenge  | Fork |
| ------------- | ------------- |
| Build a Tribute Page  | http://codepen.io/theflametrooper/pen/wGdeYM  |
| Build a Personal Portfolio Webpage  | http://codepen.io/theflametrooper/pen/xVdryJ  |
| Build a Random Quote Machine  | http://codepen.io/theflametrooper/pen/ZWKyVa  |
| Show the Local Weather  | http://codepen.io/theflametrooper/pen/WwjOWo  |
| Build a Wikipedia Viewer  | http://codepen.io/theflametrooper/pen/xVdrMa  |
| Use the Twitchtv JSON API  | http://codepen.io/theflametrooper/pen/JXNJxm  |
| Build a JavaScript Calculator  | http://codepen.io/theflametrooper/pen/pyPwBw  |
| Build a Pomodoro Clock  | http://codepen.io/theflametrooper/pen/yObXro  |
| Build a Tic Tac Toe Game  | http://codepen.io/theflametrooper/pen/MymoRO  |
| Build a Simon Game  | http://codepen.io/theflametrooper/pen/ZWKyZv  |
| Build a Markdown Previewer  | http://codepen.io/theflametrooper/pen/RaVZrN  |
| Build a Camper Leaderboard  | http://codepen.io/theflametrooper/pen/WwjErj  |
| Build a Recipe Box  | http://codepen.io/theflametrooper/pen/EKmvPO  |
| Build the Game of Life  | http://codepen.io/theflametrooper/pen/dMWzGx  |
| Build a Roguelike Dungeon Crawler Game  | http://codepen.io/theflametrooper/pen/YqVxqz  |
| Visualize Data with a Bar Chart  | http://codepen.io/theflametrooper/pen/zqwdqm  |
| Visualize Data with a Scatterplot Graph	  | http://codepen.io/theflametrooper/pen/EKmvKO  |
| Visualize Data with a Heat Map  | http://codepen.io/theflametrooper/pen/aNWyNP  |
| Show Relationships with a Force Directed Graph	  | http://codepen.io/theflametrooper/pen/xVdLVM |
| Map Data Across the Globe  | http://codepen.io/theflametrooper/pen/qZmXZw  |

**Comment by raisedadead** [comment]
@theflametrooper Thanks a lot for this list and your efforts. 
I'll do the QA and get back once we have forked these into the Free Code Camp Account.

**Comment by kehugter** [comment]
Seems like the HTTP Pens were deleted before the live site got the update? I just got a 404 following http://codepen.io/FreeCodeCamp/full/wMQrXV in the first challenge.

**Comment by sludge256** [comment]
@kehugter That pen is still up for me.

**Comment by kehugter** [comment]
@sludge256 tried again after your comment and in fact it was my blanked referrers that were causing it to 404. That bug is entirely on codepen's side.

**Comment by raisedadead** [comment]
@theflametrooper I am QA-ing and forking to FCC Account. I'll mark the status of the fork on your list above.

@ Contributors : Please refer the list for QA-ed Pens.
All the forked and QA-ed Pens are available on the collection :
> http://codepen.io/collection/AWQMxq/

PR's on the forked links are welcome! Do tag this issue as refer #7700 in the PR (Do not add Closes tag).

**Comment by theflametrooper** [comment]
@raisedadead I'll take care of this PR. So all I have to do is change the links on the challenges to the new links in the collection?

**Comment by raisedadead** [comment]
@theflametrooper That's correct. Make sure everything to be `https`
Ping me in the Chat if you have queries

**Comment by theflametrooper** [comment]
Cool

**Comment by raisedadead** [comment]
@theflametrooper pens updated, I might have fixed missed settings in the pens as well as I was forking, well I could see those in the console tab of dev tools.

Please update the PR.

I have left some pens purposefully because they are broken even with https update. 
But for now you can just update the PR and address the Pens that have been QA-ed.

Thanks.

**Comment by theflametrooper** [comment]
I'll get on that @raisedadead

**Comment by theflametrooper** [comment]
@raisedadead The pr has been updated...

**Comment by erictleung** [comment]
Help wanted: the [API link](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/729f9669527d58f5ba810efbdcc60a79376b843d/seed/challenges/02-data-visualization-certification/data-visualization-projects.json#L133) for the Force Directed Graph project should have `https`. Otherwise, your graph won't work.

**Comment by raisedadead** [comment]
Pens that are directly fixed in the Free Code Camp's  CodePen account :

Show the Local Weather - http://codepen.io/FreeCodeCamp/full/bELRjV **<--** This one has to be loaded over `http` to work.
Build a Personal Portfolio Webpage - https://codepen.io/FreeCodeCamp/full/YqLyXB/
Map Data Across the Globe - https://codepen.io/FreeCodeCamp/full/mVEJag
Show Relationships with a Force Directed Graph - https//codepen.io/FreeCodeCamp/full/KVNNXY

**Comment by SnoopJeDi** [comment]
[Here's a forked pen](http://codepen.io/snoopjedi/pen/revxJE) that fixes **Visualize Data with a Bar Chart**, changed to pull the data from the GitHub link provided in the challenge, using `$.getJSON()` instead of `$.get()`

**Comment by raisedadead** [comment]
@SnoopJeDi You are the man! I'll fork it back to the FCC account. Would you like to make a PR to change it in the challenge?

**Comment by raisedadead** [comment]
@SnoopJeDi Here is a the forked copy under FCC 
https://codepen.io/FreeCodeCamp/full/vGjLVZ/

**Comment by benschac** [comment]
Hey, is there anyway to flag frontend projects as in construction or something. That weather App project with the geolocation API is really messing people up still.  Even just a notification or grey out explaining the situation.

Maybe a short term fix is adding another requirement to use a third party service like https://geocoda.com/location/ to get coordinates?
or, add a field that the user needs to input.

**Comment by benschac** [comment]
It's super frustrating, especially to new users if something like this isn't working.

**Comment by raisedadead** [comment]
@benschac Hi, Are you by any chance talking about a scenario same as #7853 ?

**Comment by benschac** [comment]
Heck yes.  There needs to be some kind of notification to end users to let them know this project is under construction or something.  A new comer isn't going to have a clue that this is actively being worked on.

**Comment by raisedadead** [comment]
Apologies for the issues and we sure share frustration as well. 
As you would have noticed, we have been looking for alternatives, unfortunately there are a variety of considerations. 

Please continue and check the discussion on that thread.

**Comment by benschac** [comment]
That totally cool.  Is there anyway to flag the content on the site as under construction? I fear this will detract new users when they get stuck on something that literally doesn't have a solution.

**Comment by raisedadead** [comment]
@benschac 

Nope. 
We can at best add a Hint/Warning as I have mentioned my comment on the other thread.

We wont be blocking the entire page for the challenge with notifications.
The issue is not no Free Code Camp website, but a challenge that requires use of CodePen.

Again I urge you to continue further on the other thread which is specific to this challenge.

**Comment by benschac** [comment]
It not about me.  I know what's going on.  It's about the thousands of users who are currently trying to solve this issue.  There should be a better way of notifying users a project is down or not working :(
