### ISSUE TITLE
Where Do I Belong Challenge Test

### ISSUE THREAD

**Issue by CWHargett** [FreeCodeCamp/FreeCodeCamp#7702]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20where(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20arr.sort(function%20(a%2C%20b)%20%7Breturn%20a-b%3B%7D)%3B%0A%20%20for%20(var%20x%20in%20arr)%20%7B%0A%20%20%20%20if%20(num%20%3C%3D%20arr%5Bx%5D)%20%7B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20x%3B%0A%7D%0A%0Awhere(%5B2%2C%205%2C%2010%5D%2C%2015)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code returns correct answers, but they are reported as failures.I tracked down the problem to be with the "for (var x in arr)" statement. The statement iterates through an array similar to 
"for (var x=0;x<arr.length;x++)" which when used causes the tests to succeed. I suspect it's because the the first version of the "for" creates the variable "x" as a character type for some reason. The tests are likely comparing the results using the "===" operator.

If you change the return to "return x-0;" it will work. 

My code:
```javascript
function where(arr, num) {
  // Find my place in this sorted array.
  arr.sort(function (a, b) {return a-b;});
  for (var x in arr) {
    if (num <= arr[x]) {
      return x;
    }
  }
  return arr.length;
}

where([20,3,5], 19);
```

**Comment by ltegman** [comment]
This is not an error with our site. As you've identified your code is returning a string instead of a number. This is one of many reasons why `for ... in` is a bad and uncommon choice for iterating through an array. Thanks and happy coding.

**Comment by sd23152243** [comment]
@ltegman Thank you ,your answer is useful!
