### ISSUE TITLE
Code Editior issue on Mobile Devices

### ISSUE THREAD

**Issue by ribsmcgee** [FreeCodeCamp/FreeCodeCamp#7703]
#### Issue Description

I work two jobs so I mostly use my phone's internet, chrome, to work on this website. I amb trying to do the class creation challenge for the CatPhotoApp. When I go to delete the h2 style section I get to about the b in blue. When that happens a bunch of b's appear and eventually I get something that looks like this: 
<style>
      h2 {
color : blbbbbbbbbbbbbbbbbbbbbbbbbue;
</style>

I was able at one point to get this all gone, only to create the class for red text and have it copy and paste itself repeatedly.

#### Browser Information
Chrome v 49.0.2623.91
Android marshmallow v 6.0

#### Your Code
Listed above.

#### Screenshot
Unable on mobile.

**Comment by raisedadead** [comment]
@ribsmcgee Thanks for the issue. Reporting this itself would have been tough from a mobile device.

I can confirm, the issue on my device as well:
Here is a screenshot:
![screenshot_2016-03-23-12-53-59](https://cloud.githubusercontent.com/assets/1884376/13978406/c685cac4-f0f6-11e5-854c-760138af3310.png)

**Comment by Demon000** [comment]
Can confirm, happens to me too. And it also happens on Codepen.

**Comment by karenfreemansmith** [comment]
Also had problems with letters appearing/disappearing. Android Marshmallow. Got past it but had to try many times for each exercise.

**Comment by BerkeleyTrue** [comment]
@raisedadead Can you confirm that this is an issue with our code as opposed to CodeMirror's?

**Comment by raisedadead** [comment]
@BerkeleyTrue I have been trying to findout, will keep you posted, as soon as I find something.

**Comment by ribsmcgee** [comment]
I have come to the conclusion that it happens whenever I go back to delete something. It replaces it and if I keep deleting it it overcompensates. I've managed to pass that challenge and I'm almost ready to start on jQuery, but there have been a few times where I accidentally put a set of quotes and when I delete them and put them somewhere else, the original ones reappear.

**Comment by Demon000** [comment]
@BerkeleyTrue The issue is present in CodeMirror too.

**Comment by BerkeleyTrue** [comment]
Does someone mind filing an issue with CodeMirror?

**Comment by BerkeleyTrue** [comment]
Follow https://github.com/codemirror/CodeMirror/issues/3508 for this issue

Happy Coding!
