### ISSUE TITLE
Change dataset for "Show Relationships with a Force Directed Graph"

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7704]
Since we are retiring Camper News, we need a new dataset or API to replace our Camper News dataset in [Show Relationships with a Force Directed Graph](https://www.freecodecamp.com/challenges/show-relationships-with-a-force-directed-graph).

We need to identify the dataset (preferably one that doesn't require an API key) and update the challenge.

**Comment by QuincyLarson** [comment]
Duplicate of #7082 - thanks for catching this @sludge256

**Comment by pompan129** [comment]
For now we could avoid the "No 'Access-Control-Allow-Origin'" error by just changing the url in the directions from...
http://www.freecodecamp.com/news/hot
to
https://www.freecodecamp.com/news/hot
