### ISSUE TITLE
Operator chains

### ISSUE THREAD

**Issue by adrenalin** [FreeCodeCamp/FreeCodeCamp#7707]
Challenge [Storing Values with the Equal Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-equal-operator#?solution=%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Ab%20%3D%20a%20%3D%207%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var a;
var b = 2;

// Only change code below this line

b = a = 7;

```

The parser doesn't accept chaining operators... ;)

**Comment by cannelflow** [comment]
instructions are Assign the value 7 to variable a.
Assign the contents of a to variable b.
which is like var a = 7;
var b = a;
please use chat room https://gitter.im/FreeCodeCamp/FreeCodeCamp

**Comment by adrenalin** [comment]
@cannelflow: JavaScript evaluates assignment operators right to left, so `b = a = 7` is equal to `a = 7; b = a;`

My answer stands correct.

**Comment by erictleung** [comment]
It does seem to be a legitimate way to store a variable. What's your opinion @SaintPeter on changing the regex for this? I don't see any reason to not to add this case.

**Comment by SaintPeter** [comment]
I think the instructions are pretty clear and unambiguous. They tell you exactly what to do and in what order to do it.  The tests then test for that.

Yes, the chained answer is "correct" in the general sense, but it is not technically possible to test for all possible correct solutions - just the ones we're looking for.

These challenges are intended to serve people who are brand new to code.  If you are experienced to know what chaining operators are, then why are you even doing these challenges to begin with?  These challenges are optional.

**Comment by raisedadead** [comment]
I agree with @SaintPeter . This exercise is purely concentrating on the basics, and adding complex checks would be tedious to manage as well.

While I agree @adrenalin you may have got a valid assignment operation here, it just defeats the purpose of the challenge and its target audience.

Thanks, and happy Coding.
