### ISSUE TITLE
Steamroller cannot load on chrome

### ISSUE THREAD

**Issue by richao03** [FreeCodeCamp/FreeCodeCamp#7709]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* I cannot access the steamroller page on Chrome, I was able to complete the challenge on firefox, but I can't even return to the challenge page on chrome. 
* When I click map - steamroller, it will bring to me the challenge page, show me the code, then freeze. 

#### Browser Information
*Google Chrome, Version 49.0.2623.87 m
* Windows 8.1 64bit

#### Screenshot
<img width="960" alt="steamroller" src="https://cloud.githubusercontent.com/assets/16840614/14000006/853b04d4-f115-11e5-960a-ba944472ef9f.png">

**Comment by drk7891** [comment]
You're missing semicolons `;` on those lines with the errors.

Have you checked out [FreeCodeCamp's Gitter help room?](https://gitter.im/FreeCodeCamp/FreeCodeCamp)

**Comment by richao03** [comment]
its not that my code doesn't run, the webpage is completely unresponsive. However when I put the same code into my firefox browser it runs fine. 
Ive completed the challenge but when I try to go back to the challenge page on google Chrome, it still freezes up.

**Comment by raisedadead** [comment]
@richao03 Please check [this article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) on how to disable the code auto run.

Hope this helps.
