### ISSUE TITLE
Help with ReadMe.md in Hike repo

### ISSUE THREAD

**Issue by brianamarie** [FreeCodeCamp/FreeCodeCamp#7711]
View [this issue](https://github.com/FreeCodeCamp/hikes/issues/174) in Hike repository to contribute. 

> If anyone is looking for an opportunity to contribute with minimal coding involved, the readme for this repo isn't in great shape.

> It would be idea for the readme to reflect the current status of videos in five tiers.

> 1. Help wanted
> 2. Pre-production (script has not yet complete, but video has user assigned to start the process)
> 3. Production (script is complete and has been looked at by other team members, video is not yet complete)
> 4. Post-production (video has been recorded)
> 5. Deployed & live

**Comment by raisedadead** [comment]
I understand that this is for the hikes (Videos) Repository and not this repo, however we can keep this here for finding people to get around to [the original issue](https://github.com/FreeCodeCamp/hikes/issues/174) on the hikes repo.

Note to potential contributors:
* We need help in improving the README.md Guide on the Hikes repo.
* Link to the [README](https://github.com/FreeCodeCamp/hikes/blob/master/README.md)
* We want to categorize the list of the Videos in the way as suggested on the issue.

This should not probably not involve any coding, and you could edit from the comfort of the GitHub Web Interface. 

Refer [this article](https://medium.freecodecamp.com/how-to-land-your-first-open-source-contribution-from-your-browser-in-15-minutes-756d9bbf81ad#.5vdxxoc56) to get you started.

Remember that you need to follow the article to contribute to the Hike Repo that can be [found here](https://github.com/FreeCodeCamp/hikes).

Thanks.

**Comment by CharlesManga** [comment]
I am happy to help and I'd like to take this challenge.

**Comment by theflametrooper** [comment]
@CharlesManga Someone has already submitted a pr for this issue. (Found [here](https://github.com/FreeCodeCamp/hikes/pull/177)).
