### ISSUE TITLE
Understanding Uninitialized Variables won't move to next challenge

### ISSUE THREAD

**Issue by kddixon** [FreeCodeCamp/FreeCodeCamp#7712]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%204%3B%0Avar%20b%20%3D%205%3B%0Avar%20c%20%3D%20%22I%20am%20a%22%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I see the correct output, but when I click "Run Test", it won't move to the next challenge.

My code:
```javascript
// Initialize these three variables
var a = 4;
var b = 5;
var c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by alistermada** [comment]
Please read the instructions carefully:
> Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.

The output shows the value of the variables after the entire code  is run. It is not the value of the variables when they are initialized.

If you're stuck on a challenge, please ask for help on the [Help Chat](https://gitter.im/FreeCodeCamp/Help) first before posting a bug report.

**Comment by raisedadead** [comment]
@kddixon @alistermada is correct.

Closing as not a site issue. Thanks and Happy Coding!

**Comment by bmweiner** [comment]
@raisedadead 
I noticed the instructions do not correspond to the text in the *testSuite*, this might be causing the confusion.

    Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be
    undefined.

vs

    a should be defined and have a value of 6
    b should be defined and have a value of 15
    c should not contain undefined and should have a value of "I am a String!"
    Do not change code below the line

**Comment by krishgarg** [comment]
// Initialize these three variables
var a= 5;
var b=10;
var c ="I am a "; 

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";

**Comment by texas2010** [comment]
@krishgarg 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by F3D0s** [comment]
@bhabajitkashyap you forgot the spaces:

```
// Initialize these three variables
var a = 5;
var b = 10;
var c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";
```
