### ISSUE TITLE
Change Text Inside an Element Using jQuery NOT WORKING

### ISSUE THREAD

**Issue by ebrees** [FreeCodeCamp/FreeCodeCamp#7713]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens: Every time
* Steps To Reproduce: Go to the challenge and try it

#### Browser Information
* current version of Firefox
* Operating System
Windows 7

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").text("<i>target4</i>");
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by Mikaiyl** [comment]
Where is your code?

**Comment by ebrees** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").text("<i>target4</i>");
  });
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by ebrees** [comment]
Sorry. Pasting it wasn't working properly. Here is a pertinent screenshot.

![challenge](https://cloud.githubusercontent.com/assets/17937371/14006296/3d860ca6-f129-11e5-95a0-535155d1b313.PNG)

**Comment by alistermada** [comment]
You should use `.html()` instead of `.text()` for this challenge.

This part of the instructions may be the cause of confusion:
> jQuery also has a similar function called `.text()` that only alters text without adding tags.

It could be rewritten so it's clear to students that `.text()` will not evaluate the tags in the string input as HTML and instead treat them as part of the text.

**Comment by ebrees** [comment]
Thank you for the reply, sir. However, I tried it with .html as well as with .text and it still did not work. Please go to this challenge amd see for yourself. If I am makimg a mistake I do not knlw what it is. I have tried it any number of ways and it does not work.

**Comment by alistermada** [comment]
In your original code, you were missing the `#` in front of `target4`.

**Comment by raisedadead** [comment]
@alistermada Thanks for the for the clarification, we could add a test to check campers are not reading through the lines, and getting confused?

> Make sure you are using `.html()` and not `.text()`

or something on similar lines.

**Comment by alistermada** [comment]
@raisedadead Sounds like a good idea to me.

**Comment by ebrees** [comment]
Thank you. I can't believe I missed that.

**Comment by texxs** [comment]
I and others are using .html (and trying <em> instead of <i>) to no avail.  Clicking "Run Test" does not return an error or a success message, nothing happens.   Others reports her of same issue with what I assume is exactly correct code:

`$(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>$target4</em>");
  });`

I'm guessing it's correct because it does change the text of target 4 to italics within the codecamp editor or in a separate environment like cloud9 or codeanywhere.com etc.

**Comment by alistermada** [comment]
@texxs It should be `#target4` instead of `$target4` between the tags.

**Comment by texxs** [comment]
Ya got me on that one!  Thanks.  :)

**Comment by jnmorse** [comment]
Is this still and issue? and if so what is the exact issue?  It seems like the test in staging was updated to look for em tags and the text about .text seems clear enough to me. Though seems like an aside that may not be needed since the .text method isn't relevant to what is being looked for.

If I were to draw issues with this one it would be the following.

1. The title is "Change Text Inside an Element Using jQuery", yet that is not what you are asked to do.  You are asked to add tags, *without* changing the text.
2. There is another jQuery method to add tags without changing text that may be better suited, `.wrapInner`, since it will do what is looked for adding tags without changing the text, inside of `#target4`
    ```javascript
    $('#target4').wrapInner('<em></em>')
    ```
where as using `.html` you have to add the text again.

Using `.wrapInner` will pass the test by the way, so should a test be added to check that `.html` is being used?

Just looking for some clarification?

**Comment by cinquemason** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>#target4</em>")
  });
</script>
this worked for me

**Comment by cinquemason** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>#target4</em>")
  });
</script>

**Comment by texas2010** [comment]
@cinquemason 
Please don't put your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by amin8666** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>#target4</em>");
     $("#targt4").text("#target4");
  });
</script>

**Comment by raisedadead** [comment]
@amin8666 please reach out to the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by cainesim** [comment]
![image](https://cloud.githubusercontent.com/assets/25155867/22771072/8ff63f48-eecf-11e6-9cac-e84f1dd29997.png)

**Comment by gracexu222** [comment]
You could try code as below:
    $("#target4").html("<em>#target4</em>");

**Comment by gracexu222** [comment]
change <i>,</i> to <em></em>
then run tests

**Comment by piyushkathayat** [comment]
@cainesim I am also getting the same error. Can't see any issue.  Did you find any solution ?

**Comment by Preeetrockz** [comment]
![1](https://cloud.githubusercontent.com/assets/27354386/25277489/75037456-26bc-11e7-80d7-ae8dc779b718.png)

**Comment by Preeetrockz** [comment]
**here is a solution !!!**
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    
    $("#target4").html("<em>#target4</em>");
  });
</script>

**Comment by Arash1982** [comment]
In the exercise it says 

> Make sure to select button id="target4" with jQuery.

What is it exactly implying upon?

**Comment by Getachew-Mulat** [comment]
Not working... here is the screenshot...
![not working](https://user-images.githubusercontent.com/19872729/35769717-51fd3cf2-0920-11e8-99d0-22245d4840aa.PNG)
