### ISSUE TITLE
Example page has a link to a malware infected page.

### ISSUE THREAD

**Issue by Sephem** [FreeCodeCamp/FreeCodeCamp#7717]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When I open the example page and click the link to Thiago Ferreira on  the top left it takes me to a page that is infected with malware.

**Comment by AkiraLaine** [comment]
I can confirm. We should remove it ASAP

**Comment by sludge256** [comment]
@Sephem Are you using Avast?

**Comment by Sephem** [comment]
Yes I am.

**Comment by jbull328** [comment]
I scanned the URL with https://www.virustotal.com, a malicious URL scanner and it came back clean.

**Comment by sludge256** [comment]
I used a few scanners when this was reported and got no results either. As far as I know, this issue is only present for Avast users.

**Comment by alistermada** [comment]
I don't get any warnings when visiting that site. However, I can't  access www.freecodecamp.com at all on Firefox with Avast enabled. Disabling Avast allows me to connect with Firefox and Chrome works fine regardless.

![image](https://cloud.githubusercontent.com/assets/12993334/14057207/83e12f1a-f32b-11e5-9dd8-8f556949cffb.png)

**Comment by hallaathrad** [comment]
We can use mine meanwhile we find a better one. At least we'll know it's not booby trapped.

http://codepen.io/hallaathrad/pen/vNEPpL
