### ISSUE TITLE
Exercise completed correctly but not marked correct.

### ISSUE THREAD

**Issue by tonyx42** [FreeCodeCamp/freecodecamp#772]
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

<a href='#'><img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'></a>

appears correct and has the described behaviour. waypoint complains about missing </a> closing tag.

**Comment by LumenTeun** [comment]
Could you post your code, please?

**Comment by tonyx42** [comment]
Hi, nevermind, I tried to replicate the issue but it passed OK this time... I'll save everything next time I see something weird. thanks for the prompt support :)

**Comment by LumenTeun** [comment]
Yeah, sometimes the browser seems to mess up for no good reason. Could you close this issue if it's no longer a problem? :)

**Comment by QuincyLarson** [comment]
This is probably because you accidentally deleted another element. This happens, but I'm refactoring our tests to prevent these sort of problems from cropping up.
