### ISSUE TITLE
Where are thou Challenge: Small typo 

### ISSUE THREAD

**Issue by megnotarte** [FreeCodeCamp/FreeCodeCamp#7723]
#### Issue Description
There is a small typo on http://freecodecamp.com/challenges/bonfire-where-art-thou, in the second paragraph.

> For example, if the first argument is [{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], and the second argument is { last: "Capulet" }, then you must return the third object from the array (the first argument), because it contains the property and **it's value**, that was passed on as the second argument.

It should read "its" not "it's".

**Comment by pawan92** [comment]
hey if i wanted to fix this how would i go about?

**Comment by sludge256** [comment]
@pawan92 It looks like someone has already submitted a PR
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7724

You can go ahead and read this for now though,
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

We look forward to contributions from you in the future!
