### ISSUE TITLE
Wrong solution being accepted

### ISSUE THREAD

**Issue by ameymhatre** [FreeCodeCamp/FreeCodeCamp#7728]
https://www.freecodecamp.com/challenges/counting-cards

For a below test case my code returns "1 Hold" which is wrong.. still my solution is accepted

### My code
var count = 0;

function cc(card) {
  // Only change code below this line
  
  var result = 0;
 if(card >1 && card< 7){
   result = ++count;
   return (result +" "+"Bet");
 }
  
  else if (card >6 && card <10){
     //result = 0;
    if(count>0){
      return count+" Bet";
    }
     return (count +" " +"Hold");
  }else{
     result = --count;
   return (result +" "+"Hold");
  }
   
  // Only change code above this line
}

cc(2); cc(2); cc(10);

**Comment by erictleung** [comment]
Yeah, it looks like the tests so far don't cover the case where the effect of the last card drawn is opposite the count. An example is like in your case where the last card decreases the count (10 -> -1 Count), but the overall count is still positive.

So we just need an extra test for the card sequence `cc(2); cc(2); cc(10)`.

> Cards Sequence 2, 2, 10 should return "1 Bet"
