### ISSUE TITLE
Challenge doesn't accept CSS shorthand

### ISSUE THREAD

**Issue by vishalarora** [FreeCodeCamp/freecodecamp#773]
Re: Waypoint: Add Borders Around your Elements
http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. 

Adding `border: 10px solid green` satisfies the `border-width` requirement but not the `border-style`.  I think the shorthand should either not work at all or work for both.

**Comment by QuincyLarson** [comment]
Good point. I've fixed this. Thanks!
