### ISSUE TITLE
Arguments Object

### ISSUE THREAD

**Issue by AmLearning** [FreeCodeCamp/FreeCodeCamp#7732]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20%0A%20%20var%20l%20%3D%20arguments.length%3B%0A%20%20var%20arrayLength%20%3D%20arr.length%3B%0A%0A%2F%2F%20%20return%20arguments%5B2%5D%3B%0A%2F%2F%20%20return%20l%3B%0A%20%20%0A%20%20function%20isNum%20(num)%7B%0A%20%20%20%20var%20x%20%3D%202%3B%2F%2Farguments%5B1%5D%3B%0A%20%20%20%20return%20num%20%3D%3D%20x%3B%0A%20%20%7D%2F%2Fend%20function%20isNum%0A%20%20%0A%20%20%0A%20%20%0A%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%20%20newArr%20%3D%20arr.filter(isNum)%3B%0A%20%20%0A%20%20%0A%20%20return%20newArr%3B%0A%2F%2F%20%20return%20arr%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  // Remove all the values
  
  var l = arguments.length;
  var arrayLength = arr.length;

//  return arguments[2];
//  return l;
  
  function isNum (num){
    var x = 2;//arguments[1];
    return num == x;
  }//end function isNum
  
  
  
  var newArr = [];
  newArr = arr.filter(isNum);
  
  
  return newArr;
//  return arr;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```

I am told that the Arguments () is no longer supported in JS, but rather REST.  The question I was asking was why in the function isNum, if I put the actual number 2 (same as parameter arguments[1]), it worked, but that referring to the argument did not.  I was advised in Chat that arguments. no longer supported.  Should this refer us to REST rather than Arguments?

**Comment by alistermada** [comment]
From [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/arguments):
> The arguments object is a local variable available within all functions.

This means that `argument[1]` within the `isNum()` function is not the same as `argument[1]` for the `destroyer()` function. It's similar to how a local variable overrides a global variable within the scope of its function.

The arguments object is a part of every function in JavaScript and it's not likely to be dropped. I don't understand how this relates to REST.

**Comment by BKinahan** [comment]
@alistermada is correct; the arguments object is still supported and isn't likely to lose support.

It seems to me like REST here doesn't refer to the [API concept](https://en.wikipedia.org/wiki/Representational_state_transfer) usually associated with that capitalized spelling, but rather to ES6's [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) as an alternative to the arguments object. (@AmLearning, check the latter link for more details on the differences between rest parameters and the arguments object).

The challenge in question could be solved quite neatly with rest parameters as shown below, which could be why it was recommended in the chat, but it is not yet widely supported across the full range of web browsers.

```js
function destroyer(arr,...b) {
  return arr.filter(function(value){
    return b.indexOf(value)<0;
  });
}
```
(or, more succinctly:)
```js
destroyer = (arr,...b) => arr.filter(value=>b.indexOf(value)<0);
```

**Comment by AmLearning** [comment]
Thanks!  I think @alistermada's clarification of scope is what I was not seeing..will reproach the problem.
