### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by rdx1subhankar** [FreeCodeCamp/FreeCodeCamp#7734]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0A%0AmyStr%3D%22I%20am%20a%20%5C%22double%20quoted%5C%22string%20inside%20%5C%22double%20quotes%5C%22%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 OPR/36.0.2130.32</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr; // Change this line

myStr="I am a \"double quoted\"string inside \"double quotes\"";

```
kindly check the screenshot
![untitled](https://cloud.githubusercontent.com/assets/13295399/14058796/5672c3be-f352-11e5-93d3-24eeaac9042c.png)

**Comment by alistermada** [comment]
You're missing a space somewhere in your string. Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) first if you are stuck on a challenge.

**Comment by sludge256** [comment]
Thanks @alistermada

**Comment by rdx1subhankar** [comment]
can you tell me exactly where @alistermada  
i have posted in the JS chat rooms 
and if you kindly write the correct line .

**Comment by rdx1subhankar** [comment]
Got it 
thank you

**Comment by rdx1subhankar** [comment]
problem was with the comment part

**Comment by rdx1subhankar** [comment]
not giving a space
