### ISSUE TITLE
Incorrect count of closed <p> tags

### ISSUE THREAD

**Issue by vishalarora** [FreeCodeCamp/freecodecamp#774]
Re: Waypoint: Wrap an Anchor Element within a Paragraph 
http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph

It seems the expectation is that one would create a new paragraph tag with an element within.  However, if I were to insert the anchor tag within an existing `<p>` tag, it doesn't satisfy the "Be sure that each of your p elements has a closing tag" requirement.

In other words, the following code evaluates to incorrect:
```
<p class='red-text'>
    Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.
    Click here for <a href="#">cat photos</a>.
</p>
```

It seems that you're just counting the number of `</p>` tags as I'm able to make that condition pass by simply adding closing `<p>` tags (without ever opening them) and pass the challenge.  Code example:

```
<p class='red-text'>
    Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.  
    Click here for <a href="#">cat photos</a>
</p></p></p>
```
This evaluates as correct even though it obviously isn't.  It might be better to check that the number of closing tags match the number of opening tags instead of checking the absolute count of closing `<p>` tags.

**Comment by QuincyLarson** [comment]
Good point. I figured out a way to do this with our one-line Chai.js tests, and I'm going through and retrofitting our curriculum right now. Thanks!
