### ISSUE TITLE
Inaccurate statement regarding links in codepen.io in build-a-tribute-page video

### ISSUE THREAD

**Issue by tmowad** [FreeCodeCamp/FreeCodeCamp#7741]
Right around 3:00, Quincy says that codepen.io won't follow links without the target attribute equaling _blank, but in my current codepen (http://codepen.io/tmowad/full/WwOZwJ/) this doesn't seem to be required.  

No biggie, but something to change, if its universal in all browsers, if you re-record the video.  

I have Chrome Version 49.0.2623.87 (64-bit) -- on Mac OS X Version 10.11.4 (15E65), in case this matters.

**Comment by jbull328** [comment]
In your code pen your link to the biography does indeed work. But for me in the chrome browser, your link to your FCC profile does not load. What Quincy is advising is using the target="_blank" method to a get around this issue. 

![same](https://cloud.githubusercontent.com/assets/9585707/14118654/5e52f834-f59f-11e5-82c8-37ad6ca97131.jpg)

Maybe we can have a video or lesson on this, to make it more clear.

**Comment by sludge256** [comment]
I think you only need the `target="_blank"` to work around sites that don't allow iframing.

**Comment by raisedadead** [comment]
@tmowad @jbull328 
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Known-Issues-With-Codepen

**Comment by bugron** [comment]
Closing this issue. Feel free to reopen if this is still an issue for you, thanks.
