### ISSUE TITLE
Not validating closing tags

### ISSUE THREAD

**Issue by vishalarora** [FreeCodeCamp/freecodecamp#775]
Re: Waypoint: Create an Ordered List 
http://www.freecodecamp.com/challenges/waypoint-create-an-ordered-list has an issue.

The "You should have an `ol` element on your webpage." condition is satisfied by the following code:

```
<ol>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
```

Note the incorrect closing tag.

**Comment by QuincyLarson** [comment]
Thank you for bringing this to my attention. I've fixed this and will push it soon.
