### ISSUE TITLE
Default HTML code on Lobster font

### ISSUE THREAD

**Issue by trubicus** [FreeCodeCamp/FreeCodeCamp#7755]
#### Wrong link to Lobster font
Happens on responsive design section.
Default is *http://...* but correct is *https://...* so the font rolls back on Monospace.
It is correct in previous sections.

**Comment by raisedadead** [comment]
@trubicus Thanks  for reporting this.
This is a known effect of the recent SSL upgrade.

You can bypass this by changing to HTTPS as you have already identified

Anyone looking into this:
* You have to update the Code Editor Sample code in to `https` link for the font.

**Comment by raisedadead** [comment]
Closing in favor of #7758
