### ISSUE TITLE
Challenge isn't checking where code is added

### ISSUE THREAD

**Issue by vishalarora** [FreeCodeCamp/freecodecamp#776]
Re: Waypoint: Add Font Awesome Icons all of our Buttons
http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-all-of-our-buttons

I'm able to satisfy either of the conditions by adding `fa-trash` or `fa-info-circle` to any existing or new element on the page.

**Comment by LumenTeun** [comment]
@vishalarora I've just made [a PR](https://github.com/FreeCodeCamp/freecodecamp/pull/777) that will fix a lot of the issues with the Bootstrap challenges. If you're able, please look at my code and see or ask me in the Slack chatroom before posting any other issues that might've been solved already. :)

**Comment by vishalarora** [comment]
@LumenTeun Thanks!  I'll be sure take a look at your PR before submitting new issues.  Thanks for making those fixes.

**Comment by vishalarora** [comment]
For the record, PR #777 fixes this issue.
