### ISSUE TITLE
 Missing One Sort of Test in Algorithm Spinal Tap Case

### ISSUE THREAD

**Issue by HectorHu** [FreeCodeCamp/FreeCodeCamp#7763]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* call spinalCase('thisIsSpinalSap');When this function call, the result should be 'this-is-spinal-sap',but when my function return this-is--spinalsap,this also pass the test.

#### Browser Information
* Browser Google-Chrome, Latest Version
* Linux(OpenSUSE Leap 42.1)

#### Your Code

```js
function spinalCase(str) {
  // "It's such a fine line between stupid, and clever."
  // --David St. Hubbins
  var regex = /[^a-zA-Z]/g,
      res = str.match(regex),
      upper_regex = /[A-Z]/g,
      upper_res = str.match(upper_regex);
  if(res !== null) {
    str = str.replace(/[^a-zA-Z]/g, '-');
  } else {
    for(var i = 0; i < upper_res.length; i++) {
      str = str.replace(upper_res[i], '-' + upper_res[i]);
    }
  }
  str = str.toLowerCase();
  return str;
}

spinalCase('thisIsSpinalSap');
```
#### Screenshot
![](https://cloud.githubusercontent.com/assets/4621881/14070202/1bb833aa-f4d6-11e5-99d2-a75010f6c16c.png)

**Comment by raisedadead** [comment]
@HectorHu Thanks for reporting this.
I haven't checked the test case logic. But clearly this has to be handled.

**Comment by geoff616** [comment]
Looks like that code was passing because there wasn't a test case with two+ capitals that were the same letter. Added a test case that fails for that function.
