### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lavraalex** [FreeCodeCamp/FreeCodeCamp#7765]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by nmcae** [comment]
Variables map[string]string

	// Flags to be used with Template
	Flags map[string]bool

**Comment by raisedadead** [comment]
Closing as no description provided. 
Please reach out to our [Help Chat](https://gitter.im/FreeCodeCamp/Help) room, to confirm any issues that you are facing, before reporting.

Also we need you to follow the Issue template and provide as much details about the issue as possible.
