### ISSUE TITLE
Misleading Label name

### ISSUE THREAD

**Issue by bumbeishvili** [FreeCodeCamp/FreeCodeCamp#7766]
When viewiing other peoples profiles , projects link label title is `View my project` which references other users project, I suggest to delete word` my` from this title,so that only  `View project` remains

#### Screenshot
![untitled](https://cloud.githubusercontent.com/assets/6873202/14073919/f6ab180e-f4dd-11e5-9ece-8a96c88d8b0d.png)

**Comment by raisedadead** [comment]
Ahh! @bumbeishvili I remember you reported a similar issue earlier in #6598 :sweat_smile: 
Well I guess we can fix all of these occurrences! 

Thanks! Am on it.
