### ISSUE TITLE
Improper use of the JSON term

### ISSUE THREAD

**Issue by zerkms** [FreeCodeCamp/FreeCodeCamp#7767]
(at least) The following articles use the JSON term incorrectly:

* https://www.freecodecamp.com/challenges/introducing-javascript-object-notation-json
* https://www.freecodecamp.com/challenges/accessing-nested-arrays-in-json
* https://www.freecodecamp.com/challenges/accessing-nested-objects-in-json

All those articles refer to JS objects (object literals) and arrays (array literals) as JSON, which is incorrect.

It is a really harmful mistake that misleads newbies to use the JSON and JS object literal terms interchangeably. And that is a problem in the industry: people do not realise JSON is simply a serialisation format, not the way you define objects and arrays in your code.

I believe the FCC should not introduce/use the term JSON with something that is not JSON.

Relevant parts of the standard:

* http://www.ecma-international.org/ecma-262/6.0/#sec-array-initializer
* http://www.ecma-international.org/ecma-262/6.0/#sec-object-initializer

PS: I wanted to make a PR to fix that, but then found that the first article should be entirely reworked to address the issue.

**Comment by raisedadead** [comment]
@zerkms Thanks for the issue. Would you mind discussing this further in the [Curriculum Development](https://gitter.im/FreeCodeCamp/CurriculumDevelopment) Chat Room.

/cc @SaintPeter You are probably the best person to address this.

**Comment by zerkms** [comment]
@raisedadead I'm there, left few notes

**Comment by SaintPeter** [comment]
I agree that this is incorrect.

I am open to a PR to rework the challenges. 

The key value of these challenges is in analyzing and accessing arbitrary complex JS Object/Array structures.   They don't need to be called JSON to do that.

**Comment by zerkms** [comment]
> The key value of these challenges is in analyzing and accessing arbitrary complex JS Object/Array structures

Indeed.

Okay, I will try to rewrite all 3 and send a PR, but keep in mind it will require intensive proof reading (a non-native here).
