### ISSUE TITLE
h2 not turning blue. 2 cases currently on chat 

### ISSUE THREAD

**Issue by yssah** [FreeCodeCamp/FreeCodeCamp#7769]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3Eh2%20%7Bcolor%3Ablue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>h2 {color:blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by raisedadead** [comment]
@yssah Thanks for the reporting the issue!
I am afraid your code is not correct, you do not have a <h2> element.

Please re-confirm in the [Help Chat](https://gitter.im/FreeCodeCamp/Help), that this is the intended code.
