### ISSUE TITLE
Nonprofit projects still locked

### ISSUE THREAD

**Issue by DuckyDisciple** [FreeCodeCamp/FreeCodeCamp#7774]
I have completed the 3 certifications: Front-End, Data-Visualtization, and Back-End, but the non-profit projects are still locked. I have tried closing out of the page and going back in, and it still shows that those projects are locked until I finish the other certifications.

If I go into my profile, I can see that I have all 3 of those certifications.

**Comment by roelver** [comment]
I don't think this is a bug. Getting assigned to a non-profit project is a manual procedure, Search for a partner on the [HalfWayClub](https://gitter.im/FreeCodeCamp/HalfWayClub) or send your name and contact to team@freecodecamp.com.

**Comment by DuckyDisciple** [comment]
Gotcha. After some deeper digging, I found the documentation on the non-profits. Might be helpful to have that linked from that section in the map for future reference.
