### ISSUE TITLE
French Translation Progress

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/FreeCodeCamp#7777]
This list will be updated regularly. If you want to help out, please leave a comment on the issue of the relevant section and then submit a pr. In the pr description add `closes #ID`,  where ID is the issue number e.g. #7244. Join this [chatroom ](https://gitter.im/FreeCodeCamp/TranslationFrench) if you need help or need to ask any questions. Thanks!

**Getting Started**

| Section | Status | Link |
| ------------- | ------------- | ------------- |
| Join the Free Code Camp Community  | Completed  | #7244  |

**Front End Development Certification**

| Section | Status | Link |
| ------------- | ------------- | ------------- |
| HTML5 and CSS  | Help Wanted  | #7288  |
| Responsive Design with Bootstrap  | Completed  | #7631  |
| Gear up for Success | Completed | #7632  |
| jQuery  | Help Wanted  | #7633  |
| Basic Front End Development Projects  | Help Wanted  | #7634  |
| Basic Javascript  | Help Wanted  | #7635  |
| Object Oriented and Functional Programming  | Help Wanted  | #7636  |
| Basic Algorithm Scripting  | Help Wanted  | #7637  |
| JSON APIs and Ajax  | Help Wanted  | #7638  |
| Intermediate Front End Development Projects  | Help Wanted  | #7639  |
| Intermediate Algorithm Scripting  | Completed | #7640  |
| Advanced Algorithm Scripting  | Help Wanted  | #7641 |
| Advanced Front End Development Projects  | Help Wanted  | #7642  |
| Claim Your Front End Development Certificate  | Help Wanted  | #7643  |

**Data Visualization Certification**

| Section | Status | Link |
| ------------- | ------------- | ------------- |
| SASS  | Waiting for English Version  | #7644  |
| React  | Waiting for English Version  | #7645  |
| React Projects  | Help Wanted  | #7646  |
| D3  | Waiting for English Version  | #7647  |
| Data Visualization Projects  | Help Wanted  | #7648  |
| Claim Your Data Visualization Certificate  | Completed  | #7649  |

**Back End Development Certification**

| Section | Status | Link |
| ------------- | ------------- | ------------- |
| Automated Testing and Debugging  | Help Wanted  | #7650  |
| API Projects  | Help Wanted | #7651  |
| Dynamic Web Application Projects  | Help Wanted  | #7652  |
| Claim Your Back End Development Certificate  | Completed  | #7653  |

**Comment by CharlesManga** [comment]
do you need any help with this problem. If you do what can I help you with?

**Comment by CharlesManga** [comment]
I am confused. Do you need a French translation? If you do, then I'm happy to help.

**Comment by theflametrooper** [comment]
@CharlesManga This is a list of what does and doesn't need translating. If the status is 'help wanted' then click on the link to the right, comment that you're gonna help out with it and then submit a pr!

**Comment by theflametrooper** [comment]
This isn't up-to-date and makes things complicated...
