### ISSUE TITLE
closing p tag error while it is correctly closed

### ISSUE THREAD

**Issue by Zwennes** [FreeCodeCamp/freecodecamp#778]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
![image](https://cloud.githubusercontent.com/assets/9589158/7903262/3490d226-07d6-11e5-854d-6ed56705b6e1.png)

**Comment by LumenTeun** [comment]
Actually, you seem to have misunderstood the instructions a bit. If you're not already there, go to [our Slack chatroom's help channel](https://freecode.slack.com/messages/help/) and ask if you're having trouble with any of the challenges.

**Comment by QuincyLarson** [comment]
This isn't working because you deleted the other p elements. We check for closing tags by counting them (this is the most flexible way to do so).

**Comment by Zwennes** [comment]
You are absolutely right! Thanks for the response, you have a very educative website.
