### ISSUE TITLE
My code has disappeared

### ISSUE THREAD

**Issue by ar2g** [FreeCodeCamp/FreeCodeCamp#7782]
#### Issue Description
Although my progress shows on my profile page the code I wrote has disappeared.

* When Issue Happens
When I log in to FCC

* Steps To Reproduce
View my profile page

#### Screenshot

![fcc](https://cloud.githubusercontent.com/assets/2738610/14094541/91c3d956-f557-11e5-813e-ce615dd6e2dd.jpg)

**Comment by BKinahan** [comment]
I viewed your profile page, and your code appears to be intact. Click on the 'View solution' link in the Solution column on the right to view your completed challenge solutions. (Your solution code is encoded within the link URL, so you can confirm that your code is saved by checking that.)

Happy coding!
