### ISSUE TITLE
Bonfire: Binary Agents - correct output but not passing tests

### ISSUE THREAD

**Issue by ptrchoi** [FreeCodeCamp/FreeCodeCamp#7787]
#### Issue Description
* Code produces the correct output strings according to test reqs, but the tests do not show as passed. Have tried output strings with double quotes and without, but neither passes.

#### Browser Information
* Browser Name, Version > Chrome Version 49.0.2623.87 (64-bit)
* Operating System > OS X - El Capitan Version 10.11.3

#### Your Code
function binaryAgent(str) {
  var bytes = str.split(" "),
      chars = []; 
  for (var i = 0; i < bytes.length; i++) {
    chars.push(String.fromCharCode(parseInt(bytes[i], 2)));
  }
  chars = chars.join(" ");
  console.log(chars);
  return chars;
}

#### Screenshot
![screenshot](https://cloud.githubusercontent.com/assets/17165193/14099852/8ad6bf5e-f54e-11e5-8ed3-1349a12c34af.png)

**Comment by BKinahan** [comment]
`binaryAgent("01000001 01110010 01100101 01101110 00100111 01110100 00100000 01100010 01101111 01101110 01100110 01101001 01110010 01100101 01110011 00100000 01100110 01110101 01101110 00100001 00111111")` should return `"Aren't bonfires fun!?"`

Your function returns `"A r e n ' t   b o n f i r e s   f u n ! ?"`

The difference is the spaces between each character. Your code can be corrected by changing line 8 to `chars = chars.join("");` which does not introduce extra spaces when forming the string.

The test cases are written correctly.

Happy coding!

**Comment by ptrchoi** [comment]
doh! Thanks for the quick response and correction!
