### ISSUE TITLE
Suggestion: add a chat panel/text area to Bonfires for pairing chat

### ISSUE THREAD

**Issue by kurzninja** [FreeCodeCamp/freecodecamp#779]
For people that want to pair but maybe don't have access to a microphone for use in Screenhero, it would be really useful to have an on-screen area to type into for chat purposes besides the code pane. Using the Screenhero chat during Bonfires can be frustrating due to it losing focus while the other user is clicking on things in the browser.

**Comment by LumenTeun** [comment]
I don't want to be a buzzkill, but I think that the text area would lose focus, even in an in-browser chat.

**Comment by kurzninja** [comment]
Good point. There's gotta be a better, less frustrating way for folks who don't have a mic.

**Comment by LumenTeun** [comment]
If you haven't already, you could check [FCC's list of local groups](http://www.freecodecamp.com/field-guide/how-can-i-find-other-free-code-camp-campers-in-my-city) and maybe find someone to pair program with in physical space. If you're stuck at the computer and want to pair, getting a mic might be a good idea; you can usually get stand alone microphones quite cheap from either Amazon or some local tech shop.

**Comment by QuincyLarson** [comment]
@kurzninja We are planning to make it possible to pair right inside FreeCodeCamp.com once we've moved to React (no need for Screen Hero). Once we've made this available, there will be both VOIP and instant messaging. But this is a long way off.
