### ISSUE TITLE
Dead link challenge 

### ISSUE THREAD

**Issue by cienci** [FreeCodeCamp/FreeCodeCamp#7790]
#### Issue Description
* Issue happens when replacing href with # then validating, does not validate
* Challenge Make Dead Links using the Hash Symbol , replace href with # 

#### Browser Information
* Chrome Version 49.0.2623.87 m
Windows

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a #="http://www.freecatphotoapp.com">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```js
If relevant, paste all of your challenge code in here
```

![image](https://cloud.githubusercontent.com/assets/18105263/14103708/aaa8e570-f5a1-11e5-9fce-9483b5c744e4.png)

**Comment by munga4** [comment]
Still not working.

**Comment by KobiMaru** [comment]
The problem your having is instead of deleting the href attribute you need to add the deadlink in onto it. example: <a href="#".
the ("") are needed also.

**Comment by munga4** [comment]
How are you, yeah i did that and its working thank you very much.



Kelvin
