### ISSUE TITLE
border Challenges

### ISSUE THREAD

**Issue by cienci** [FreeCodeCamp/FreeCodeCamp#7791]
#### Issue Description
* When on my phone coding with free code camp
* Trying to code challenges concerning border, all of them, with the right code (same challenges with same code done on laptop worked, but not on the phone.

#### Browser Information
*Google App version 5.10.32.19.arm64
* Android version 5.1.1
Sony Xperia Z6

The right code for challenges concerning border

```js
If relevant, paste all of your challenge code in here
```

**Comment by erictleung** [comment]
@cienci can you provide any specific challenges and your code for us to test?
