### ISSUE TITLE
Wrong test case for Pairwise

### ISSUE THREAD

**Issue by shrihari-balasubramani** [FreeCodeCamp/FreeCodeCamp#7793]
Challenge [Pairwise](https://www.freecodecamp.com/challenges/pairwise#?solution=function%20pairwise(arr%2C%20arg)%20%7B%0A%0A%20%20%2F%2Ffor%20every%20number%20in%20arr%20while%20the%20array%20is%20not%20over%20while%20the%20sum%20is%20not%20equal%20to%20or%20greater%20than%20arg%20keep%20adding.If%20its%20equal%20give%20all%20the%20index%20.%20If%20more%20or%20equal%20to%202%20add%20it%20to%20list.%0A%20%20%20%20var%20count%20%3D%200%3B%0A%20%20for(count%3D0%3Bcount%3C%20arr.length-1%3Bcount%2B%2B)%7B%0A%20%20%20%20var%20loopcount%3D0%2Cintcounter%3Darr%5Bcount%5D%3B%0A%20%20%20%20var%20usedarr%3D%5B%5D%2Ctemparr%3D%5B%5D%3B%0A%20%20%20%20%0A%20%20%20%20while(loopcount%3Carr.length%2B1)%7B%0A%20%20%20%20%20%0A%20%20%20%20%20%20if(intcounter%20%3C%20arg)%7B%0A%20%20%20%20%20%20%20if(%20intcounter%2Barr%5Bloopcount%5D%3C%3Darg)%0A%20%20%20%20%20%20%20%20intcounter%20%2B%3Darr%5Bloopcount%5D%3B%0A%20%20%20%20%20%20%20%20%20%20if(intcounter%20%3D%3D%20arg)%7B%0A%20%20%20%20%20%20%20%20%20%20%2F%2Freturn%20the%20value%20of%20indices.%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20loopcount%2B%2B%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20intcounter%3D0%3B%0A%20%20%20%20%20%20%20%20%20%20loopcount%2B%2B%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%0A%20%20%20%20return%20arg%3B%0A%7D%0A%0Apairwise(%5B1%2C4%2C2%2C3%2C0%2C5%5D%2C%207)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

>  For example, pairwise([1, 4, 2, 3, 0, 5], 7) should return 11 because 4, 2, 3 and 5 can be paired with each other to equal 7 and their indices (1, 2, 3, and 5) sum to 11.

The above test case is wrong.
for the condition

>  If multiple sums are possible, return the smallest sum

Consider the array
[1, 4, 2, 3, 0, 5] the first 3 elements would be equal to 7 and their indices equate to 3(0+1+2).

**Comment by BKinahan** [comment]
The use of the word 'pair' used throughout the instructions implies matching 2 and only 2 elements. I feel that the example reinforces this too, but I'm open to the idea that clarifying how many elements are in a pair could make the meaning of the instructions more accessible to a wider range of users.

**Comment by alistermada** [comment]
@BKinahan  Doesn't the first sentence already suggest how many elements are in a pair?

> Return the sum of all element indices of array `arr` that can be **paired with one other element** to form a sum that equals the value in the second argument `arg`.

I gotta admit though, I had to read that sentence slowly to understand what it's asking for.

**Comment by shrihari-balasubramani** [comment]
Hey my bad, somehow I skipped the "pair" and just thought it to be sum. All though I feel as an end user I feel it would be great if the description reads as "use only 2 elements to equal second argument " instead of just the word "pair".
