### ISSUE TITLE
Some Computer Basics lessons not marked as completed

### ISSUE THREAD

**Issue by vzhikness** [FreeCodeCamp/FreeCodeCamp#7795]
It's not possible to mark some Computer Basics as completed. I tried to complete them many times. No success.

Browser: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36`
OS: `OS X 10.11.3`

Screenshot:
![Alt text](https://monosnap.com/file/aGkvSwFLkSmKXhbw0xD3f4ZQydMU9k.png)

**Comment by yashdeeph709** [comment]
I have also faced same problem.

**Comment by vzhikness** [comment]
@yashdeeph709 the same lessons or different?

**Comment by yashdeeph709** [comment]
No this happend with me on js lessons

**Comment by NicholasAsimov** [comment]
Same here, tried Chrome 49 and Firefox 45.
Adblock disabled.
After submitting the quiz POST request gets aborted after 300ms.

![image](https://cloud.githubusercontent.com/assets/8828810/14413365/165a911e-ff80-11e5-975c-a0d411a78fd4.png)

**Comment by QuincyLarson** [comment]
@vzhikness @NicholasAsimov @yashdeeph709 can you confirm whether this is still an issue?

**Comment by vzhikness** [comment]
No issue for me now
![computer_basics](https://cloud.githubusercontent.com/assets/3816520/19379529/0ae486e2-91fb-11e6-8df5-927dea1f5222.PNG)

**Comment by ramir141974** [comment]
confirm sir thank you
