### ISSUE TITLE
Challenge 87: Create a Custom Heading

### ISSUE THREAD

**Issue by DeanMauro** [FreeCodeCamp/FreeCodeCamp#7797]
This is the challenge where you move the cat in a green circle up to the same line as the "CatPhotoApp" heading. 

The first time I did the challenge, I wrote this:

```
 <div class="container-fluid">
   <div class="row">
     <div class="col-xs-8">
       <h2 class="text-primary text-center">CatPhotoApp</h2>
     </div>
     <div class="col-xs-4">
       <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
     </div>
   </div>
 
 …
```

The heading and cat pic are still in the topmost div, which squishes them together like this:

<a href="http://tinypic.com?ref=350pb35" target="_blank"><img src="http://i67.tinypic.com/350pb35.png" border="0" alt="Image and video hosting by TinyPic"></a>

This was accepted and said the challenge was completed correctly. The objects were only oriented correctly when the heading and picture were placed outside of the main div like this:

```
   <div class="row">
     <div class="col-xs-8">
       <h2 class="text-primary text-center">CatPhotoApp</h2>
     </div>
     <div class="col-xs-4">
       <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
     </div>
   </div>
 
 <div class="container-fluid">
 …
```

<a href="http://tinypic.com?ref=ibbb61" target="_blank"><img src="http://i68.tinypic.com/ibbb61.png" border="0" alt="Image and video hosting by TinyPic"></a>

(I am using Safari v8.0.7)

**Comment by DeanMauro** [comment]
Update: 
This squishing is happening on all subsequent challenges too. For example: 

<a href="http://tinypic.com?ref=ap7kab" target="_blank"><img src="http://i65.tinypic.com/ap7kab.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by erictleung** [comment]
There appears to be several issues going on:

- The link at the top of the editor does not use `https` so the console yells at you if you do take a peak.

![image](https://cloud.githubusercontent.com/assets/2754821/14196335/3d7b4302-f778-11e5-88b7-a94672ca39fe.png)

- Changing the above will change the font and the top will look normal/expected.

![image](https://cloud.githubusercontent.com/assets/2754821/14196361/77c201d6-f778-11e5-9898-7d732859fa0c.png)

- The second image link does not use `https` as well so the console will yell at you for that too.

![image](https://cloud.githubusercontent.com/assets/2754821/14196377/acbb4834-f778-11e5-8412-71084676231a.png)

**Comment by erictleung** [comment]
Looks like the title stuff has [already been fixed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/789fba9750558e79dc9a2c03e212084fe8ff6b2c/seed/challenges/01-front-end-development-certification/bootstrap.json#L1047) but the fixes haven't been pushed to the live site yet. But the smushing thing might be part of a larger problem. Closing this issue for the heading issue. Happy coding!

**Comment by Milan-Varghese** [comment]
just a matter of a closing tag </div>
