### ISSUE TITLE
Infinite Challenges/Points

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#78]
After a user completes all challenges, click on take me to my next challenge forwards to a challenge number that doesn't really exist, and awards a point for completion.

**Comment by teddy-error** [comment]
I will become the highest pointed camper of all time

**Comment by terakilobyte** [comment]
Until we set your points to 53 manually.

**Comment by terakilobyte** [comment]
I'm closing this issue as it doesn't increment infinitely. Additionally, this is fully addressed on the courseware branch.
