### ISSUE TITLE
Test wrongly passed for the challenge "Override All Other Styles by using Important" 

### ISSUE THREAD

**Issue by payal-prksh** [FreeCodeCamp/FreeCodeCamp#7800]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens: My code gets approved and passes all the test cases (which it should not be doing). Technically, the test "Your pink-text class should have the !important keyword to override all other declarations." should be approved only when ".pink-text {color: pink !important;}" class is entered in the Css. This is a false positive test case. 
* Steps To Reproduce: The issue can be reproduced when we type "color: pink !important" in any of the classes/ id other than pink-text. 
Eg: 
 #orange-text {
    color: pink !important;
  }
OR
.blue-text{
color: pink !important;
}

#### Browser Information
* Browser Name, Version: Google Chrome, 49.0.2623.108 (64-bit)
* Operating System: Ubuntu 14.04

#### Your Code

```js
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: pink !important;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>
```

#### Screenshot
![oie_uesectwuisp6](https://cloud.githubusercontent.com/assets/1385489/14124559/6906784a-f5c3-11e5-96c1-a77d3fa576bf.png)

**Comment by erictleung** [comment]
That does pass the tests! I think the easiest way to test this is to make sure the two color style declarations `#orange-text` and `.blue-text` both have their respective styles unchanged.

**Comment by BKinahan** [comment]
@erictleung I think it could be that the larger issue here is that the test with message "Your `pink-text` class should have the `!important` keyword to override all other declarations.' only checks for "!important" following "pink" (with `code.match(/pink.*\\!important;/gi)` rather than asserting that this occurs within the `.pink-text` declaration. 

It may be less important that the other style declarations are unchanged, and expanding the regexp directly related to this test might be a better solution.

**Comment by erictleung** [comment]
@BKinahan I agree, my solution was only supposed to be the "easiest" to implement :smile: My knowledge of the unit testing system on FCC isn't wide enough to know off the top of my head a way to check the `.pink-text` with the `!important` keyword. If you have ideas, you're welcome to make a PR!
