### ISSUE TITLE
Add CSS style to element challenge missing final step

### ISSUE THREAD

**Issue by lauradb** [FreeCodeCamp/FreeCodeCamp#7801]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%7Bcolor%3A%20blue%3B%7D%0A%20%20%3C%2Fstyle%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2{color: blue;}
  </style>
<h2>CatPhotoApp</h2>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```
exercise did not include final step adding <h> text </h>

**Comment by sludge256** [comment]
The text is already there. You just have to be mindful of what you delete.

Starting code:
```html
<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```
Please elaborate if you're talking about some other text or, if I have missed the point of your post.

**Comment by lauradb** [comment]
Thanks so much! Sorry about that. I'm new. :)

On Tue, Mar 29, 2016 at 3:25 PM, Brian <notifications@github.com> wrote:

> The text is already there. You just have to be mindful of what you delete.
>
> Starting code:
>
> <h2 style="color: red">CatPhotoApp</h2>
>
> <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
>
> Please elaborate if you're talking about some other text or, if I have
> missed the point of your post.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7801#issuecomment-203137539>
>



-- 
​
Laura Brown M.B.A., P.M.P., C.S.M., S.M.A.C.
Scrum Master - Senior Executive Project Manager
http://www.linkedin.com/pub/laura-brown/0/7b3/32a
​
http://lauradbrown.smugmug.com/​
FundRaising Campaign for Ecuador: http://bit.ly/1N1A7ZQ

**Comment by sludge256** [comment]
@lauradb Don't worry about it. 

Closing as resolved.

**Comment by simmisweets** [comment]
Saved my day! Thank you so much👊🏾

**Comment by carlsagonator** [comment]
omg thanks so much for posting this it helped me out so much as well :)
