### ISSUE TITLE
Bug in Solution

### ISSUE THREAD

**Issue by kvscse** [FreeCodeCamp/FreeCodeCamp#7806]
I think according to the problem statement, the problem should accept the solution a=7 and then b=a statements. But, its even accepting b=a then a=7 .

Refer below for the problem statement:

Challenge [Declare JavaScript Variables](https://www.freecodecamp.com/challenges/declare-javascript-variables#?solution=%2F%2F%20Example%0Avar%20ourName%3B%0Avar%20myName%3B%0A%2F%2F%20Define%20myName%20below%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourName;
var myName;
// Define myName below this line


```

**Comment by TravisHi** [comment]
Did you put the correct challenge and explaination? What you've put in "My code:" doesn't match what you wrote at the top.

**Comment by erictleung** [comment]
Yeah, I think @kvscse is referring to the [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator) challenge.

If the following is what you intended, it should not pass the challenge, thus there is no problem with the challenge. It would not pass the third test of `b should have a value of 7` because `b` would still be equal to 2.

```
// Setup
var a;
var b = 2;

// Only change code below this line
b = a;
a = 7;
```

Closing as this isn't a bug. @kvscse let me know if my understanding of your problem is wrong and I can reopen the issue.

**Comment by alistermada** [comment]
@erictleung The code fails the first time. However, when the tests are run again, it will pass. 

![image](https://cloud.githubusercontent.com/assets/12993334/14132891/a819bf4a-f674-11e5-9c9b-0a580202233f.png)

I added `console.log("a = " + a + ", b = " + b);` above the rest of the code. Here's what my browser's console outputs the first time the tests are run:

![image](https://cloud.githubusercontent.com/assets/12993334/14133010/c5977390-f675-11e5-9be5-835da1d8587e.png)

As expected, both `a` and `b` are `undefined` before the rest of the code is run. However, when the tests are run the second time, here's what I get:

![image](https://cloud.githubusercontent.com/assets/12993334/14133066/438fc496-f676-11e5-9dc5-ed12ad337d24.png)

**Comment by kvscse** [comment]
Yes..sorry..I mistakenly typed the code..
Thanks @erictleung its the problem what I wanted to note.Thank You. :)

**Comment by kvscse** [comment]
@alistermada @erictleung 
yes look at the console, according to the motive of the problem statement, it must be success only if b is also 7..but not "undefined" right??

**Comment by erictleung** [comment]
@FreeCodeCamp/issue-moderators Any thoughts on why this is happening? If you copy paste this into a newly opened window for [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator), and run the tests twice, it'll pass.

```js
console.log("a = " + a + ", b = " + b);

// Setup
var a;
var b = 2;

// Only change code below this line
b = a;
a = 7;
```

**Comment by hallaathrad** [comment]
Running it once goes to the point in which a=7. The second time takes that value when b=a. The store is remaining in the console's memory.

How to avoid that is beyond me. But that is why, @erictleung

**Comment by SaintPeter** [comment]
Humm . . one way to fix this would be to add a regex to check that the assignment has been done properly. 
IE:
/b\s*=\s*a/

**Comment by erictleung** [comment]
@SaintPeter right now, the [last test](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/41ce2d83f85b042e3e8ba1a87aa6eefacd840cc2/seed/challenges/01-front-end-development-certification/basic-javascript.json#L121) actually tests for that with `/b\\s*=\\s*a\\s*;/g.test(code)`. This challenge has all sorts of weird things going on with it like in #7890.

**Comment by SaintPeter** [comment]
LOL, well, I guess we ought to fix it then?  ;)

**Comment by codelaw90** [comment]
I did the same thing, but it's not working. I really want to figure this out.

**Comment by hossain128** [comment]
var a=7;
var b=a;
var b=;

Please help me, What will be the value of B;

**Comment by hossain128** [comment]
Alhamdulillah, I found the solution:

http://prntscr.com/gx9x1a
