### ISSUE TITLE
Mark people who violate academic honesty's profiles more prominently

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7809]
Currently when I try to visit the certificate of a user who's marked as { "isCheater": true }, instead of showing their certificate, I see "Upon review, this account has been flagged for academic dishonesty."

It would be nice if this message could be featured prominently on that user's profile as well. This would reduce confusion (multiple campers reporting the same user as having cheated, even though they are already flagged as "isCheater" in the database).

**Comment by phillip-hogan** [comment]
I'd like to help with this one.

**Comment by CharlesManga** [comment]
I would possibly like to work on this. Where would I go to work on this???
