### ISSUE TITLE
Div around everything

### ISSUE THREAD

**Issue by matejkonrad** [FreeCodeCamp/freecodecamp#781]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-many-elements-within-a-div-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

It's possible to wrap around one div element around the ul,p and the ol tag. So if you put your starting tag div before the p tag and close it before the form tag, you can complete the challange.

**Comment by QuincyLarson** [comment]
This is possible, but this isn't something we care to test for, since by definition if you understand the concept of wrapping elements in a div you're ready to move on to the next challenge.
