### ISSUE TITLE
Lost all of  my work

### ISSUE THREAD

**Issue by hashemn** [FreeCodeCamp/FreeCodeCamp#7810]
i completed 50 lessons and after a week i sign in and see all of my work is gone . not looking froward to start from beginning.

**Comment by raisedadead** [comment]
@hashemn Sorry about the inconvenience, but Can you confirm that you were signed in while you were solving the lessons? 

Your profile page shows that you were active on March 29th 2016 and March 30th 2016

![image](https://cloud.githubusercontent.com/assets/1884376/14142029/b85e23ec-f6a0-11e5-9b0c-016aa18ec1a5.png)
