### ISSUE TITLE
Error - Your p element should contain the first few words of the provided additional kitty ipsum text.

### ISSUE THREAD

**Issue by amitpn89** [FreeCodeCamp/FreeCodeCamp#7811]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%20style%3D%22font-size%3A16px%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p style="font-size:16px">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

![capture](https://cloud.githubusercontent.com/assets/12931255/14140643/effbf378-f697-11e5-8557-fc21860cfffc.PNG)

**Comment by amitpn89** [comment]
Even after writing correct code, I am finding this error. Anyone help me out here.

Thanks in Advance!

**Comment by raisedadead** [comment]
Thanks for reporting this. However we are afraid this is not an Error/Bug on the website.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Please review the instructions carefully. 
Hint : What did you copy into the `<p>` ?

Happy Coding!

**Comment by fmfarinacci** [comment]
I am having the same issue with the <p></p> tag. This is what I have as my code below:
<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by amitpn89** [comment]
@fmfarinacci 

I have added the same 
"Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff." 
text in the second <p> also. Then why I am not passing this test ?

**Comment by kirbyedy** [comment]
@amitpn89 
please read the instructions carefully...

> Create a second p element with the following kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

**Comment by jkyereh** [comment]
same issue here

**Comment by campossrg** [comment]
Not possible to move on this exercise.

Apparently I made the class and I implement it on the <p> but still waiting to get the green tick to move forward.

:S

**Comment by campossrg** [comment]
https://cloud.githubusercontent.com/assets/12931255/14140643/effbf378-f697-11e5-8557-fc21860cfffc.PNG

This is the correct code to move on :D

**Comment by fmfarinacci** [comment]
Hi Everyone,
If your stuck on # 14, below is what you need to do, the instructions were not clear.
I figured it out. You need to remove the first class="" from the first paragraph. Add the same class to the second paragraph.

**Comment by dixon1305** [comment]
I'm still having the same problem. I have changed it many times and still get the same results

**Comment by hb002300** [comment]
Create a second p element with the following kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. it really works thanks to@amitpn89

**Comment by pannainnovation** [comment]
Hi everyone,
same problem i am faceing from last 2 days. any one solve this issuse. 
Pannainnovaiton@gmail.com

**Comment by texas2010** [comment]
@pannainnovation 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by vickxy** [comment]
![image](https://user-images.githubusercontent.com/19183849/27371161-39b2bb00-567d-11e7-882f-b5341a9a8fa7.png)
