### ISSUE TITLE
Challenge : "Nest Many Elements within a Single Div Element" has an issue

### ISSUE THREAD

**Issue by metedagsuyu** [FreeCodeCamp/FreeCodeCamp#7812]
#### Issue Description
* The first challenge on this page reads "Nest your p element inside your div element."
* Should ask user to put div around both p elements as it wont let you proceed

#### Browser Information
* Chrome, 49
* Win 7

**Comment by raisedadead** [comment]
@metedagsuyu Please follow our guidelines that were mentioned in the issue template while reporting issues. The more clear info you provide the better it is to solve the issue

Do you mean that this is confusing?
![image](https://cloud.githubusercontent.com/assets/1884376/14143909/3be51aea-f6ab-11e5-992a-e1bc78673513.png)

**Comment by metedagsuyu** [comment]
@raisedadead Hello, I found it to be slightly confusing. It should read 
"Nest your p elemets
inside you div element".

**Comment by raisedadead** [comment]
@metedagsuyu Agreed and thanks.

For anyone looking towards fixing this the first test case reads:
> Nest your `p` element inside your `div` element.

this should be changed to
> Nest your `p` element**s** inside your `div` element.

Making it plural.

**Comment by metedagsuyu** [comment]
@raisedadead Thank you for helping me out on this issue. I have learned a few more helpful solutions. I understand its nothing major, but I wanted to contribute by giving a try. :+1:
