### ISSUE TITLE
where() instead of getIndexToIns()

### ISSUE THREAD

**Issue by garwil** [FreeCodeCamp/FreeCodeCamp#7817]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20%0A%20%20var%20theIndex%3D0%3B%0A%20%20arr.push(num)%3B%0A%20%20arr%3Darr.sort(function(a%2C%20b)%20%7B%0A%20%20return%20a%20-%20b%3B%0A%7D)%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3Carr.length%3Bi%2B%2B)%20%7B%0A%20%20%20%20if%20(num%20%3D%3D%3D%20arr%5Bi%5D)%20%7B%0A%20%20%20%20%20%20theIndex%20%3D%20arr.indexOf(num)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20theIndex%3B%0A%7D%0A%0AgetIndexToIns(%5B10%2C%2020%2C%2030%2C%2040%2C%2050%5D%2C%2030)%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The default code on the page names the function "where()" instead of "getIndexToIns()." It took me a little while to work out why I was returning the right answers but not passing the test.

**Comment by BKinahan** [comment]
The default code uses the function name `getIndexToIns`, but this was changed recently along with other changes that gave unique function names to many of the challenge functions. It's likely that you had loaded the challenge before the change and the old code was saved. Resetting the code will load the editor with the new function name, not the old one.

**Comment by raisedadead** [comment]
@garwil the changes have been done as mentioned by @BKinahan !
You need to resubmit the code, to pass however please note that if you were logged in and submitted the challenge earlier, your progress was captured and is safe on your profile.

Re-submitting will update the submission. 

I am afraid nothing much can be done, apart from this 

Thanks and Happy Coding!
