### ISSUE TITLE
Connectivity Issue : Cannot advance between challenges.

### ISSUE THREAD

**Issue by interglobalmedia** [FreeCodeCamp/FreeCodeCamp#7818]
Challenge [Adjusting the Padding of an Element](https://www.freecodecamp.com/challenges/adjusting-the-padding-of-an-element#?solution=%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3A%20red%3B%0A%20%20%20%20padding%3A%2020px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2020px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 10px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px;
  }

  .green-box {
    background-color: green;
    padding: 20px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

Edit by @raisedadead:

#### Camper is unable to advance between challenges due to slow/poor connectivity.

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!

**Comment by interglobalmedia** [comment]
This has NOTHING to do with coding. It has to do with website PERFORMANCE. This is happening when I have achieved SUCCESS on the page. It is happening consistently.

**Comment by raisedadead** [comment]
@interglobalmedia Sorry about the inconvenience you have been facing.
But I am afraid it wasn't very clear when the issue was reported.
Well, unless you mention that in the issue description its hard to analyse the trouble.

Re-opening this and renaming the issue to reflect the same.

Would you mind sharing details like the region you are in?

/cc @sludge256 Any reports in the Chat?

**Comment by sludge256** [comment]
Not that I'm aware of but, I haven't been active today.

Here's yesterday's Tweet about the issue for reference:
https://twitter.com/FreeCodeCamp/status/714856314791309312

**Comment by interglobalmedia** [comment]
It was somewhere in HTML challenges. However, haven't been able to get back into the website since! And that has been HOURS now. So I am just giving up for the moment. Have better things to do than waste my time trying to get into a site that isn't letting me. I don't think it's robust enough to handle the traffic it's getting is my guess. What happens is when I hit control + enter to move on to the next challenge page after having successfully coded the challenge (trust me, it was correct), and I wasn't advanced to the next challenge. The page never quite reloaded completely. There must be something in the code that is off, and it was pretty much happening continuously until finally I couldn't advance at all.

**Comment by raisedadead** [comment]
@interglobalmedia 

We are sincerely apologize for this inconvenience, and we assure you that our team is working hard on resolving the server performance issues.
We hope to resolve the same as soon as possible.

Meanwhile we request you to kindly bear with us.

Closing as I just confirmed with the team that this is a server load issue and not related to the code base.

Thanks!

**Comment by palacios27** [comment]
Having that issue with all the challenges. I know im doing it right. Well at least the best of my knowledge

**Comment by raisedadead** [comment]
Thanks for reporting looking into it.

**Comment by ThomasBlake** [comment]
I too am having the same problem with 'Give a Background Colour to a Div Element'. It doesn't allow me to get through to the next challenge
I'm using Google Chrome in Australia, I'll switch to Firefox to see if that works.
