### ISSUE TITLE
Outdated video in Pair Program waypoint.

### ISSUE THREAD

**Issue by eabedrapo** [FreeCodeCamp/freecodecamp#782]
The video in Challenge http://www.freecodecamp.com/challenges/waypoint-pair-program-on-bonfires still refers to Gitter.

Although we can follow the directions written at the left, it would be more clear for new users if the page contains a temporary warning that the video is outdated until a new version is uploaded.

**Comment by ahmednaguib** [comment]
I will start working in this one if not assigned to anyone

**Comment by johnmellis** [comment]
This video seems to be working properly.  Not sure if the card was just missed or not.

**Comment by qubodup** [comment]
since gitter is being used now again, it seems like the outdated video now is current again and the issue is no more.

**Comment by eabedrapo** [comment]
Well, it's right that now we've moved back to Gitter the video isn't quite outdated as before, but now the directions at the left-hand side are outdated as they refer to our former slack channel (see item 6) and they should be reverted to use https://gitter.im/FreeCodeCamp/LetsPair

Regarding Screen Hero, the links in item 5 at the left-hand side are still valid and once you install the application in your desktop you can create an account from there.

However, it's true that Linux users are still unable to pair using SH, so maybe the community could investigate some alternatives like maybe Mikogo, Team Viewer or similar.

But for now to solve this issue, I think it's enough to revert the left-hand side instructions :wink: 

Thanks for looking at this guys.

**Comment by LumenTeun** [comment]
The link to Slack was reported in #1053 and fixed in 7004e81b4a29b196a659bcb5cdcef30253b71d6f, it should be in production shortly.

If the video is no longer outdated, this issue can be closed.

**Comment by eabedrapo** [comment]
Cool.
