### ISSUE TITLE
Suggestion to add an additional "Helpful Link" to the "Convert HTML Entities" challenge

### ISSUE THREAD

**Issue by jamigibbs** [FreeCodeCamp/FreeCodeCamp#7826]
Challenge [Convert HTML Entities](https://www.freecodecamp.com/challenges/convert-html-entities).

Before I submit a PR, I'd like to get feedback on adding an additional link to reference on this challenge. 

I might be wrong but I think this is the first exposure users have to regular expressions in the track so I think it would be helpful to also include a reference to [.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) which makes solving this challenge much more manageable for new coders.

Example solution:
```javascript
function convert(str) {
  
  // The list of chars to convert
  var charHTMLlist = {
    "&" : "&amp;",
    "<" : "&lt;",
    ">" : "&gt;",
    '"' : "&quot;",
    "'" : "&apos;"
  };

  // Char replacement function triggered when a match is found
  function charHTMLmapper(ch){
    return charHTMLlist[ch];
  }

  // Returns a new string with the encode matches
  return str.replace(/[&"'<>]/g, charHTMLmapper);

}

// returns "Dolce &​amp; Gabbana"
convert("Dolce & Gabbana");

```

**Comment by raisedadead** [comment]
@jamigibbs I feel that wouldn't hurt.

**Comment by sludge256** [comment]
Regular Expressions are introduced in the "Basic JavaScript" section and `.replace()` is mentioned in the instructions of [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes) in the "Basic Algorithm Scripting" section.

**Comment by erictleung** [comment]
For people wanting to work on this, you'll need to change[ this part of the file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/9aa45a3d56fae3cb4dac5e08eca10373aa045946/seed/challenges/01-front-end-development-certification/intermediate-bonfires.json#L551) and add `String.replace()` in the MDN links to look something like this:

```
"MDNlinks": [
  "RegExp",
  "HTML Entities",
  "String.replace()"
], ...
```

**Comment by williamsolivera** [comment]
I'd love to do this change as my first contribution!

**Comment by erictleung** [comment]
@williamsolivera go for it! :+1: Please read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) if you haven't already before taking care of the issue. And don't hesitate to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions about helping. They are pretty responsive and friendly!
