### ISSUE TITLE
Increment a Number with JavaScript - post increment not working

### ISSUE THREAD

**Issue by jaredjacob667** [FreeCodeCamp/FreeCodeCamp#7830]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When adding "++" to the end of myVar the run tests button will say that myVar still is only 87. I found that even putting this before makes it at least 88 but then fails on the using the ++ operator test.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = myVar++;


```

**Comment by piotrjaw** [comment]
Could you try:

```
var myVar = 87;

// Only change code below this line
myVar++;
```

Best regards
Piotr

**Comment by erictleung** [comment]
Please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript). Happy coding!
