### ISSUE TITLE
Error on loading a challenge under the /videos path

### ISSUE THREAD

**Issue by benmcmahon100** [FreeCodeCamp/FreeCodeCamp#7831]
![image](https://cloud.githubusercontent.com/assets/10749142/14191432/c0bab68c-f78f-11e5-8c98-fbd4a8517b37.png)
/videos/hike-computer-basics-1-the-4-basic-parts-of-a-computer

Found when running the application on localhost

@BerkeleyTrue

**Comment by crashuniverse** [comment]
Does it matter that this video no longer is listed on Map (at least for me), can be found in codebase and redirects to Map from its assumed location at https://www.freecodecamp.com/videos/hike-computer-basics-1-the-4-basic-parts-of-a-computer
