### ISSUE TITLE
Can someone help me with my code. why it can't return the right result?

### ISSUE THREAD

**Issue by Marc-Wang** [FreeCodeCamp/FreeCodeCamp#7832]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20myStr%20%3D%20str.toLowerCase().replace(%22%20%22%2C%20%22%22).replace(%22%2C%22%2C%20%22%22).replace(%22.%22%2C%20%22%22)%3B%0A%20%20var%20myArray%20%3D%20myStr.split(%22%22)%3B%0A%20%20if(myArray%20%3D%3D%3D%20myArray.reverse())%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0Apalindrome(%22eyes%2Csdf%20lksdjf.%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var myStr = str.toLowerCase().replace(" ", "").replace(",", "").replace(".", "");
  var myArray = myStr.split("");
  if(myArray === myArray.reverse()) {
    return true;
  }
  else {
    return false;
  }
}

palindrome("eyes,sdf lksdjf.");

```

**Comment by piotrjaw** [comment]
You almost had it right, I'd go with:

```
function palindrome(str) {
  // Good luck!
  var myStr = str.toLowerCase().replace(/[^a-zA-Z0-9]/g, '');
  var myArray = myStr.split('');
  return (myArray.join('') === myArray.reverse().join(''));
}

palindrome("eyes,sdf lksdjf.");
```

What I've changed:
- first of all, you only need to do one replace with a regex, the one above catches all non-alphanumeric chars (check out http://regexr.com/ for regex testing and debugging);
- secondly, it's probably not the best of ideas to compare arrays like that. For that specific use case, you can simply ```.join()``` them to Strings and compare them, but it's generally better to recursevily iterate through the contents (joining can fool you on non-flat arrays). More here: http://stackoverflow.com/questions/7837456/how-to-compare-arrays-in-javascript
- thirdly, when you only need to perform a simple boolean check, there is no need for that kind of big if ... else statement - IMHO the one above make's it a bit more readable.

Best regards
Piotr

**Comment by sludge256** [comment]
Thanks @piotrjaw 

@Marc-Wang please use the chat rooms for code help in the future. The help button on the challenge page will point you to the right room.

GitHub issues are reserved for site related issues and discussions (curriculum, features, etc.).

**Comment by Marc-Wang** [comment]
Thanks so much for your help  @piotrjaw !!

**Comment by Marc-Wang** [comment]
@sludge256  Ok. I got it.
