### ISSUE TITLE
FEATURE: Allow user to choose custom IDE theme

### ISSUE THREAD

**Issue by onebree** [FreeCodeCamp/freecodecamp#784]
I see that the theme used in FCC is monokai, a Mac-inspired theme.

Where I work, half of us use light themes, the other half dark. I personally like [Solarized](http://ethanschoonover.com/solarized) Dark, for its readability -- all colors have the same Value levels, yet provide enough contrast to differentiate. Other popular themes include Github's, crayon, vivid chalk...

I guess this would be done in the account/profile settings of the site.

**Comment by QuincyLarson** [comment]
Hi @onebree, We are considering changing to Ace Editor, which will allow us to easily do this. We may make the switch in the near future. We're closing this issue for now.

**Comment by onebree** [comment]
:+1:
