### ISSUE TITLE
Challenge is solved with incorrect solution

### ISSUE THREAD

**Issue by gabelilly** [FreeCodeCamp/freecodecamp#785]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I added the col-xs-4 class to the button elements themselves, instead of a separate new div. Here's the code that I had which caused the problem to be solved.

```
<div class='row'>
  <button class='btn btn-block btn-primary col-xs-4'>Like</button>
  <button class='btn btn-block btn-info col-xs-4'>Info</button>
  <button class='btn btn-block btn-danger col-xs-4'>Delete</button>
</div>
```

I was confused because this did not actually cause the buttons to aline properly within the same row, so I re-read the problem description.

**Comment by QuincyLarson** [comment]
Thank you for pointing this out, @gabelilly. I have now fixed this.
