### ISSUE TITLE
Stuck with this assigment

### ISSUE THREAD

**Issue by bakerameen** [FreeCodeCamp/FreeCodeCamp#7850]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20queue(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(queue(testArr%2C%202))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function queue(arr, item) {
  // Your code here
  
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(queue(testArr, 2)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by erictleung** [comment]
Code issues are not handled on GitHub unless there is a bug with the site. Please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript). Happy coding!

**Comment by bakerameen** [comment]
Thanks for information
