### ISSUE TITLE
nesting for loops bug - continues to return null

### ISSUE THREAD

**Issue by Arcrunner819** [FreeCodeCamp/FreeCodeCamp#7851]
Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops#?solution=function%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20for%20(i%3D0%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20for%20(j%3D0%3B%20j%20%3C%20arr.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20product%20*%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  for (i=0; i < arr.length; i++) {
    for (j=0; j < arr.length; j++) {
      product *= arr[i][j];
    }
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);


```

**Comment by erictleung** [comment]
Please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: I would check your `for` loops again and see if they are doing what you think they are doing. Happy coding!

**Comment by jjivezic** [comment]
@Arcrunner819  you should add like this  and it will work.
`function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
   for ( var i=0; i < arr.length; i++) {
    for (var j=0; j < arr[i].length; j++) {
      product *= arr[i][j];
    }
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);
`

**Comment by jjivezic** [comment]
@Arcrunner819 you should add code like this and it will work.
```
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
   for ( var i=0; i < arr.length; i++) {
    for (var j=0; j < arr[i].length; j++) {
      product *= arr[i][j];
    }
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);

```

**Comment by akber7ali** [comment]
great you are the genius ! @jjivezic
