### ISSUE TITLE
Math.random() not working in Chrome

### ISSUE THREAD

**Issue by vlory73** [FreeCodeCamp/FreeCodeCamp#7859]
Challenge [Generate Random Fractions with JavaScript](https://www.freecodecamp.com/challenges/generate-random-fractions-with-javascript#?solution=function%20myFunction()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20Math.random()%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {

  // Only change code below this line.

  return Math.random();

  // Only change code above this line.
}

```
not working in Google Chrome but worked fine in Safari

**Comment by hallaathrad** [comment]
It works well on mine. Try reseting your code and typing it manually again.

**Comment by vlory73** [comment]
tried to reset several times. only did not restart the browser

On 02 Apr 2016, at 15:58, Justin Richardsson <notifications@github.com> wrote:

It works well on mine. Try reseting your code and typing it manually again.

**Comment by erictleung** [comment]
@vlory73 can you give more details on what kind of errors are you getting? Or like how did you find out it was not working on Chrome?

**Comment by vlory73** [comment]
it just seemed that Math.random() wasn’t doing anything.

i was writing “return Math.random();” and nothing happened. Went to Safari and I was able to finish the exercise.

On 02 Apr 2016, at 19:42, Eric Leung <notifications@github.com> wrote:

@vlory73 <https://github.com/vlory73> can you give more details on what kind of errors are you getting? Or like how did you find out it was not working on Chrome?

**Comment by hallaathrad** [comment]
This issue is extremely odd. Alas, I'm unable to replicate on any version of chrome I've tried (including the one @vlory73 is using. I can only assume it is a machine specific problem, thus I'd advice to clean cache and such, but since he's already moved on from the challenge, and the solution would delete his locally saved progress, I don't see the point in doing so.

Thus, I believe this issue can be closed until/unless someone reopens it for having the same problem.

**Comment by mzaneri** [comment]
@hallaathrad 

I've had this same exact issue, same OS, same browser- just drove me nuts for 10 minutes thinking I had some syntax issue.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

Once the proper code is input and "Run tests" is clicked, the console outputs "0"

The first check shows completed, but not the following two. 

Copied and pasted my code into Safari and it worked fine.

**Comment by pseudovar** [comment]
Same problem as mzaneri detailed above.  Windows 10, Chrome.  Challenge console outputs 0 regardless of what is coded to be returned.  I cleared several times, but results were the same.  I tried sending stuff to console.log while viewing in the browser's console and got strange errors related to ".split".

Finally a hard page refresh in the browser fixed everything.  No need to go to a different browser, for me at least..

**Comment by vekatobias** [comment]
@vlory73 Your is wrong because you don't have to change function's name...

**Comment by vlory73** [comment]
@vekatobias maybe the code is wrong. I probably would do it differently today. But today I have substantial more experience than back then. Also, the intended solution of the exercise was this. In the end, it boils down to Safari working, whereas Chrome did not. 
I don't mind that this is not addressed. In fact, I'm happy that raising it already helped a couple of people .
