### ISSUE TITLE
[HTML/CSS/Bootstrap waypoints] Cursor gets hidden when moving to certain texts in the editor.

### ISSUE THREAD

**Issue by eabedrapo** [FreeCodeCamp/freecodecamp#786]
Using arrow keys to edit the code in the editor the cursor is suddenly hidden so it's hard to know where I am currently editing until I write down anything in there and sometimes it becomes very annoying.

This had occurred to me in several HTML, CSS & Bootstrap challenges so I guess the problem is with the editor itself, but I couldn't get a pattern to reproduce it 100% of times as it wasn't always reproduced in the same challenge or with the same text in the editor.

What I've observed is that when going forward from one challenge into another is more likely to happen than when just loading the page from scratch.

Using Developer Tools to analyse the code didn't help me to get any clues for this issue although there is a JS error in the console right after the page is loaded.

Given the randomness of the problem, I discarded that JS error as a root cause for the issue I'm reporting here, because the JS error is displayed in all waypoint pages, but I'm mentioning here just in case it might be somehow related to the failure.

**Comment by QuincyLarson** [comment]
@eabedrapo You're right - I've experienced this, too, and I believe it's a flaw in the editor library we're using (CodeMirror). We hope to switch to Ace (an alternative tool) soon, which should solve this problem.

**Comment by eabedrapo** [comment]
Gotcha, thanks for answering! ;)
