### ISSUE TITLE
_JailedSite.js error

### ISSUE THREAD

**Issue by tupelo87** [FreeCodeCamp/FreeCodeCamp#7868]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
it happens randomly when i visit the site it also appears randomly above the coding challenges heading
* Steps To Reproduce
unsure on this as it happens randomly when i visit the site 

#### Browser Information
* Browser Name, Version
Chrome, Version 49.0.2623.110 m
* Operating System
Windows 10

#### Screenshot
no screen shot but i can press f12 and see this
refused to execute script from 'https://www.freecodecamp.com/_JailedSite.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

the _JailedSite.js is the part of the error i remember seeing above the code challenege heading but can not remember it all and can not replicate that part at the time of submitting this. if i see it again i will grab screenshot if i remember and attach it to this.

**Comment by erictleung** [comment]
Thanks for creating the issue. I can't access the `/_JailedSite.js` page on the site. I'll keep this open in case any one else runs in the problem. Please update if this happens again.

**Comment by tupelo87** [comment]
this is what i randomly see when i am doing the challenges
![error](https://cloud.githubusercontent.com/assets/17498889/14235887/b8e94b42-fa02-11e5-864c-9fe6497353d4.jpg)

**Comment by BerkeleyTrue** [comment]
@tupelo87 Are you trying to navigate to that page or does that error message pop up consistently for you?

**Comment by tupelo87** [comment]
i am not trying to navigate to that page as i thought the screen shot showed i am on the coding page as  in the screen shot when it appears and i see it quite often which is why i mentioned it to quincy who said to raise this

**Comment by BerkeleyTrue** [comment]
This is quite mysterious, since we no longer use jailedSite and there are no references to it in the code base. Can you try doing a hard fresh?

**Comment by tupelo87** [comment]
the _jailedsite.js is loaded from jailed.js which shows up when i inspect the page (i got curious after your post as to why i was seeing it) its a library or in that folder.  but at the moment only f12 is showing the error message i posted in first post.  if this post needs deleted because sensative info please say i will delete it and try find another way to write it.

**Comment by BerkeleyTrue** [comment]
I see. Not sure why that error message is showing up, but I've opened up https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7877 and hopefully that should solve this issue as well.

**Comment by tupelo87** [comment]
ok thank you berkeley.

**Comment by BerkeleyTrue** [comment]
Fix merged
