### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NiallSzalkai** [FreeCodeCamp/freecodecamp#787]
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

- will not let recognise my closed </a> tag

![image](https://cloud.githubusercontent.com/assets/9200508/7909809/12bf7672-0847-11e5-90f6-5bb90a16f7be.png)

**Comment by BerkeleyTrue** [comment]
Hey @NiallSzalkai 

Remember that you should not be removing any html already on the page.

Good Luck!
