### ISSUE TITLE
Accessing Objects Properties with Bracket Notation- Error message" ReferenceError: Can't find variable: entreeValue"

### ISSUE THREAD

**Issue by Kosaladesilva** [FreeCodeCamp/FreeCodeCamp#7870]
Challenge [Accessing Objects Properties with Bracket Notation](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-bracket-notation#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20%22an%20entree%22%3A%20%22hamburger%22%2C%0A%20%20%22my%20side%22%3A%20%22veggies%22%2C%0A%20%20%22the%20drink%22%3A%20%22water%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AtestObj%5B%22an%20entree%22%5D%3B%0AtestObj%5B%22the%20drink%22%5D%3B) has an issue.

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testObj = {
  "an entree": "hamburger",
  "my side": "veggies",
  "the drink": "water"
};

// Only change code below this line

testObj["an entree"];
testObj["the drink"];
```

getting an error message.. any idea please?

Error message**"  ReferenceError: Can't find variable: entreeValue"****

**Comment by jnmorse** [comment]
Just tried this as well, seems the challenge was updated at some point, and the ReferenceError is because it is not finding the vars `entreeValue` and `drinkValue`

So to pass you need to keep the
```
var entreeValue
var drinkValue
```
in the code and assign the values using the bracket notation to those vars.  Perhaps the instructions need to be updated?

**Comment by Kosaladesilva** [comment]
Im not sure...I kept 
var entreeValue
var drinkValue 

and then entered  
testObj["an entree"];
testObj["the drink"];

still getting an error :-(

**Comment by erictleung** [comment]
Looks like this challenge could be more explicit. The original code was:

```
var entreeValue = testObj;   // Change this line
var drinkValue = testObj;    // Change this line
```

@Kosaladesilva The challenge needs `entreeValue` and `drinkValue` to exist. Add those back in so it looks like the code above and you'll be fine. 

This challenge needs an update in the instructions saying:

> Using bracket notation on `testObj`, read in the values of the properties of `"an entree"` and save it to `entreeValue`. Do the same with the property `"the drink"` and save it to `drinkValue`.

**Comment by Kosaladesilva** [comment]
Yes could do with instruction update as to pass this challenge those property values of "an entree"  and " the drink " should pass to
 var entreeValue  and  var drinkValue

**Comment by LibanTheDev** [comment]
Is it alright if I take care of this issue?

**Comment by erictleung** [comment]
@LibanTheDev go for it! :+1: Please read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of the issue and visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions about helping.

**Comment by henrihyacinthe** [comment]
var entreeValue = testObj["an entree"];   // Change this line
var drinkValue = testObj["the drink"];    // Change this line

**Comment by luke818h** [comment]
The solution does not look like what is in the example at all.

**Comment by duoduoma66** [comment]
exactly! @luke818h
