### ISSUE TITLE
Won't complete - browser zoom set to 100% on Windows - Chrome

### ISSUE THREAD

**Issue by Admthoughts** [FreeCodeCamp/FreeCodeCamp#7871]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  .p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Admthoughts** [comment]
Error in code caused the tests to fail!

**Comment by SMannix** [comment]
What was the error? I dont seem to be able to progress?
:-)

**Comment by dilipagheda** [comment]
don't put . in front of p. when you put . then it is intrepreted as a class and not the element.
