### ISSUE TITLE
Typo in Computer Basics: Measuring Data Speed

### ISSUE THREAD

**Issue by RayBB** [FreeCodeCamp/FreeCodeCamp#7872]
#### Issue Description
The caption for [Computer Basics: Measuring Data Speed ](https://www.freecodecamp.com/videos/computer-basics-measuring-data-speed) has a typo.
The caption under the video says:

> size is usually measured in bits.

It should be corrected to:

> size is usually measured in **bytes**.

**Comment by Markchri34** [comment]
Let's get it figured out and get some money 
Amigos. Way to go team
