### ISSUE TITLE
Remove jailed and all references to it.

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#7877]
Remove this line https://github.com/FreeCodeCamp/FreeCodeCamp/blob/7b3e78119da00a1ebd34d94df6686a634256a6b8/server/views/partials/challenge-footer.jade#L1
And all the associated files https://github.com/FreeCodeCamp/FreeCodeCamp/search?l=javascript&q=jailed&utf8=%E2%9C%93

**Comment by baguzzzaji** [comment]
@BerkeleyTrue Hi, I want to try on this issue. After removing L1 on challenge-footer.jade, should I remove the folder for all the associated files?

**Comment by BerkeleyTrue** [comment]
@baguzzzaji Yes, thanks.
