### ISSUE TITLE
Cannot pass the tests although the output seems correct

### ISSUE THREAD

**Issue by sudeepnarkar** [FreeCodeCamp/FreeCodeCamp#7879]
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

function lookUp(firstName, prop){
// Only change code below this line
  for(i = 0; i < contacts.length; i++)
  {
if(contacts[i].firstName === firstName && contacts[i].hasOwnProperty(prop)){
  return contacts[i][prop];
  } 
  else if (contacts[i].firstName !== firstName) 
  {
  return "No such contact";
  } 
   else 
   {
return "No such property";
}
}
  
  
// Only change code above this line
}

// Change these values to test your function
lookUp("Akira", "likes");

```

**Comment by erictleung** [comment]
Code issues are not handled on GitHub unless there is a bug with the site. Please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript). Hint: carefully go through your `for` loop and think about its logic. Happy coding!
