### ISSUE TITLE
Waypoint bug

### ISSUE THREAD

**Issue by Lee182** [FreeCodeCamp/freecodecamp#788]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Here's my html input
```
<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by BerkeleyTrue** [comment]
Hey @Lee182 

Please describe the issue you are having with this challenge.

Thanks!

**Comment by Lee182** [comment]
Hi its just the test for the checking the challenge isn't working for me. even though it renders the font-size 16px in my browser, i checked with firefox dev tools, its no biggie!

**Comment by BerkeleyTrue** [comment]
@Lee182 

This is not an issue with the test. Looks like you are almost there to solving it, though! Try asking the help section on the freecodecamp slack. http://freecodecamp.slack.com/messages/help

Good Luck!
