### ISSUE TITLE
Instructions for "Quoting Strings with Single Quotes" challenge are confusing and do not teach concept

### ISSUE THREAD

**Issue by tmad40blue** [FreeCodeCamp/FreeCodeCamp#7881]
Hi, the challenge "Quoting Strings with Single Quotes" (available at https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes ) has confusing, vague, and conflicting information/instructions that did not allow me to complete the challenge without arbitrarily searching outside of FCC for a long while.

The instructions tell you that single- and double-quotes in JavaScript are interchangeable, so long as you are consistent:

> String values in JavaScript may be written with single or double quotes, so long as you start and end with the same type of quote. Unlike some languages, single and double quotes are functionally identical in JavaScript.

This implies that you could complete the challenge by using ALL single or ALL double quotes, so long as you remain consistent. Unfortunately, this is not the case, as the challenge CANNOT be passed without having single AND double quotes in "correct" locations, which are not taught.

The instructions say:

> Change the provided string from double to single quotes and remove the escaping.

This implies that ALL double quotes need to be changed to single quotes, but this does not produce a satisfactory solution to the challenge.

This is my working solution to the challenge:

```
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
```

Only by Googling various opinions on single- vs. double-quoting in JavaScript was I able to use trial-and-error to find a working solution for the challenge. I was left confused and without an understanding of when to use which type of quote, and I have not learned this concept in any usable manner.

It is my suggestion that the teaching and instructions of this challenge be seriously revised so that they actually teach the concept that you are wanting to teach, and so that anyone attempting the challenge is not left confused about where to start.

EDIT: After having this concept explained to me in your Gitter chat room, I now understand that there is a rule about quotes in JavaScript that is NOT taught through this challenge:

> Unless they are escaped, you cannot have more than one pair of whichever quote type begins a string.

This is not covered in the instructions, at least not thoroughly enough to understand the concept.

**Comment by erictleung** [comment]
> The value in using one or the other has to do with the need to escape quotes of the same type.

The above is what I believe to be the challenge's way of phrasing your lesson of:

> Unless they are escaped, you cannot have more than one pair of whichever quote type begins a string.

@SaintPeter maybe add this line to the challenge? Or to make it more explicit, give an example of not escaping with two quotes of the same type (e.g. `"Sam says, "I love to program!"`) and say you'll get an error because JavaScript will think your string ended early (e.g. `"Sam says, "`).

**Comment by SaintPeter** [comment]
> Unless they are escaped, you cannot have more than one pair of whichever quote type begins a string.

I like this.  It seems like a reasonable addition.  I can see how the original phrasing would be confusing.

**Comment by phorekka** [comment]
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';

It works.And it also fulfills the demand.You can either try in another fasion.

var myStr = "<a href='http://www.example.com' target='_blank'>Link</a>"

Both the ways are correct but above code do not meet the requirement of the exercise..

**Comment by MaximusO** [comment]
Thanks for explanation tmad40blue. 
Adding to the confusion is also the fact that the pure html part of the string would be wrong with quotes, anyway. I suggest using a phrase as not to make it "**double**" confusing:)

**Comment by GitH7** [comment]
* Remove all the backslashes (\)
* You should have two single quotes ' and four double quotes "
* Only remove the backslashes \ used to escape quotes.


1st and 3rd aren't conflicting ?

**Comment by da-anguiano** [comment]
The first an third condition bizarrely contradict each other. Also minimizing double quotations is an aesthetic choice and not necessarily best practice -- which is how it's made to sound.

**Comment by 4mit** [comment]
How do we can use two double quotes without using /
is it possible ?
