### ISSUE TITLE
multiple jquery selector - program not getting executed.

### ISSUE THREAD

**Issue by coderashish** [FreeCodeCamp/FreeCodeCamp#7882]
hi
please point out the error as i am stuck on this for long.

![screen shot 2016-04-04 at 16 20 22](https://cloud.githubusercontent.com/assets/16953968/14245838/9b68bcc2-fa81-11e5-8d81-c99c81a21f5d.png)

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
