### ISSUE TITLE
Translation of documents to Nigeria Language(Yoruba)

### ISSUE THREAD

**Issue by Adsurplux** [FreeCodeCamp/FreeCodeCamp#7885]
i will be happy to translate documents to Nigeria language (Yoruba) for better understanding of clients who understands things more in their native language

**Comment by vtamara** [comment]
Good! 
Please check https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Translations-Guide

**Comment by raisedadead** [comment]
Closing as this looks like an abandoned issue.

We have moved our translation collaboration to the https://github.com/FreeCodeCamp/TranslationExpansion repo. If still pursuing, please open a issue on the new repo.

Thanks, and Happy Translating!
