### ISSUE TITLE
Correction in directions

### ISSUE THREAD

**Issue by DivaWeb** [FreeCodeCamp/FreeCodeCamp#7886]
Challenge [Make Object Properties Private](https://www.freecodecamp.com/challenges/make-object-properties-private) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
   var gear;
  
  this.setGear = function(change){
    gear = change;
  };
  

  this.getGear = function(){
    return gear;
  };
};

var myCar = new Car();
var myBike = new Bike();



 

```
I have noticed that a lot of us are having problems because we are following the instructions like we are all told to do. I could not get my code to work until I changed how my properties were placed. It should say setGear and getGear to help solve a lot of our confusions.

**Comment by erictleung** [comment]
> Modify the `Bike constructor` to have a `private property` called `gear` and **two public methods called `getGear` and `setGear`** to get and set that value.

I'm sorry but I'm confused on your issue. The challenge states you need two methods with `getGear` and `setGear`. Can you elaborate on your issue a bit?

**Comment by raisedadead** [comment]
Closing as stale. Please feel free to comment below with explanatory details of the issue. We can re-open this again based upon that.

**Comment by DamianMitchell** [comment]
I appreciate for the advice I need it

**Comment by sunnylovesyew** [comment]
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
var gear=0;
  
  this.setGear  = function(change) {
    gear = change;
  };

  this.getGear = function() {
    return gear ;
  };

};

var myCar = new Car();

var myBike = new Bike();
