### ISSUE TITLE
Quizzes will not accept mobile answers

### ISSUE THREAD

**Issue by BrendanJackson** [FreeCodeCamp/FreeCodeCamp#7887]
#### Issue Description
* When Issue Happens
* Steps To Reproduce
This issue has Been happening for about a month now,  whenever I try to enter an answer on my phone at least one qualification will be incorrect and it won't give me credit. I've just been doing simple things like html and css. For whatever reason it won't work but it's fine on my desk top.

My phone is an optimus 90 lg, with the standard browser

<style>

  body {

    background-color: rgb(255, 165, 0);

  }

</style>

​

**Comment by erictleung** [comment]
I don't think I've ran into any problems on a mobile browser. I'll keep this open in case others run into any issues.
