### ISSUE TITLE
Issue with test cases Friendly Date Ranges

### ISSUE THREAD

**Issue by ShaklinSyed** [FreeCodeCamp/FreeCodeCamp#7888]
Here is my Solution for the Friendly Date Range 

```javascript
function makeFriendlyDates(arr){
	function getDayStr(num){

		if( num == 1 || num ==21){
			return num + "st";
		}
		else if(num ==2 || num == 22){
			return num + "nd";
		}
		else if(num == 3 || num == 23){
			return num + "rd";
		}
		else{
			return num + "th";
		}
	}

	var months = ["","January","February","March","April","May","June","July","August","September","October","November","December"];
	var parsedArr = new Array();

	arr.forEach(function(ele,ind){
		var tempArray = new Array();
		ele.split("-").forEach(function(elem,inde){
			tempArray.push(parseInt(elem,10));
		});
		parsedArr.push(tempArray);
	});

	var oneYearMilliSeconds = 31536000000;
	var oneMonthMilliSeconds = 2678400000;


	var diff = (new Date(parsedArr[1]) - new Date(parsedArr[0]));
		var str1 = "",str2 = ""; 
		var resultArray = new Array();
		var year = 365 * 24 * 60 * 60 ;

	if(diff == 0){
		str1 = months[parsedArr[0][1]] + " " + getDayStr(parsedArr[0][2]) +", " + parsedArr[0][0];
		console.log("Equal to diff");
		resultArray.push(str1);

	}
	else if(diff < oneMonthMilliSeconds){
		console.log("Less than one month");
		str1 = months[parsedArr[0][1]] + " " + getDayStr(parsedArr[0][2]);
		str2 = getDayStr(parsedArr[1][2]);
		resultArray.push(str1 , str2);

	}
	else if(diff == oneYearMilliSeconds)
	{
		console.log("Equal to one year");

		str1 = months[parsedArr[0][1]] + " " + getDayStr(parsedArr[0][2]) + ", " + parsedArr[0][0];
		str2 = months[parsedArr[1][1]] + " " + getDayStr(parsedArr[1][2]) + ", " + parsedArr[1][0];
		resultArray.push(str1,str2);

	}

	else if(diff > oneMonthMilliSeconds && diff < oneYearMilliSeconds){
		console.log("greater than month and less than year");

		if(parsedArr[0][0] != parsedArr[1][0]){
			str1 = months[parsedArr[0][1]] + " " + getDayStr(parsedArr[0][2]);
			str2 = months[parsedArr[1][1]] + " " + getDayStr(parsedArr[1][2]);
		}
		else{
			str1 = months[parsedArr[0][1]] + " " + getDayStr(parsedArr[0][2]) + ", " + parsedArr[0][0];
			str2 = months[parsedArr[1][1]] + " " + getDayStr(parsedArr[1][2]);
		}

 		resultArray.push(str1 , str2);
	}
	
	else if(diff > oneYearMilliSeconds){
		console.log("more than one year");
		str1 = months[parsedArr[0][1]] + " " + getDayStr(parsedArr[0][2]) + ", " + parsedArr[0][0];
		str2 = months[parsedArr[1][1]] + " " + getDayStr(parsedArr[1][2]) + ", " + parsedArr[1][0];
		resultArray.push(str1,str2);
	}

	return resultArray;
}
```

The Solution passes all test cases except for the 6th 
`makeFriendlyDates(["2022-09-05", "2023-09-04"])`

where the range is less than one year. Test case expects the result as 
`["September 5th, 2022","September 4th"]`

the issue is if year(2022) is to be added to the above case then the output of second test case 
'makeFriendlyDates(["2016-12-01", "2017-02-03"])'

should be 
`["December 1st,2016","February 3rd"]`

whereas the output
`["December 1st","February 3rd"]` passes the case.

Since the range of both test cases are less than a year and different years.

Chrome, 
OS X,

**Comment by ShaklinSyed** [comment]
The issue was not with test cases, rather i had difficult time understanding the problem

**Comment by Mohamedsalmaan** [comment]
Try this 



var start = new Date(arr[0]),
      end = new Date(arr[1]),
      currYear = new Date().getUTCFullYear();
  
  var startYear = start.getUTCFullYear(),
      startMonth = start.getUTCMonth(),
      startDay = start.getUTCDate(),
      endYear = end.getUTCFullYear(),
      endMonth = end.getUTCMonth(),
      endDay = end.getUTCDate();
  
  var months = ["January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"];
  
  // check for same date
  if (start.getTime() === end.getTime()) {
    if (currYear === startYear) {
      // Same Date, this year
      return [ months[startMonth] + " " + ordinalize(startDay) ];
    } else {
      // Same Date, not this year
      return [ months[startMonth] + " " + ordinalize(startDay) + ", " + startYear ]; 
    }
  }
  // check for same month
  else if (startYear === endYear && startMonth === endMonth) {
    if (currYear === startYear) {
      // Same Month, this year
      return [ months[startMonth] + " " + ordinalize(startDay), ordinalize(endDay) ];
    } else {
      // Same Month, not this year
      return [ months[startMonth] + " " + ordinalize(startDay) + ", " + startYear, ordinalize(endDay) ];
    }
  }
  // check for same year
  else if (sameYear(start, end)) {
    if (currYear === startYear) {
      // Start Date in this year, end date less than 1 year away
      return [ months[startMonth] + " " + ordinalize(startDay), months[endMonth] + " " + ordinalize(endDay)];
    } else {
      // Dates fall within same year. Start Date is NOT in this year
      return [ months[startMonth] + " " + ordinalize(startDay) + ", " + startYear, months[endMonth] + " " + ordinalize(endDay) ];
    }
  }
  // does not meet any of the above conditions
  else {
    // display both full dates
    return [ months[startMonth] + " " + ordinalize(startDay) + ", " + startYear, months[endMonth] + " " + ordinalize(endDay) + ", " + endYear];
  }
  
  
  // sameYear returns true if the date objects are less than one year apart, otherwise returns false
  function sameYear(d1, d2) {
    var years = d2.getUTCFullYear() - d1.getUTCFullYear();
    var origYear = d1.getUTCFullYear();
    d1.setUTCFullYear(d2.getUTCFullYear());
    if (d2 < d1) years--;
    d1.setUTCFullYear(origYear);
    if (years < 1) return true;
    return false;
  }
  
  // ordinalize returns a formatted day string
  function ordinalize(n) {
    switch (n) {
      case 1:
      case 21:
      case 31:
        return n + 'st';
      case 2:
      case 22:
        return n + 'nd';
      case 3:
      case 23:
        return n + 'rd';
      default:
        return n + 'th';
    }
  }
}
