### ISSUE TITLE
Editor Scrolls with Instructions

### ISSUE THREAD

**Issue by johnotu** [FreeCodeCamp/freecodecamp#789]
Challenge http://www.freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I noticed that when I scroll the instructions on the left pane, the code editor scrolls too, making me scroll back to the top when I want to type code.

It wouldn't have been an issue if I had only a few Waypoints but with over 1000 hours of coding, it should be fixed please.

Here is a screenshot of the  editor when the instruction is scrolled down: https://www.dropbox.com/s/lvcxjdpnmbtuu42/editor-scrolls.png?dl=0

**Comment by LumenTeun** [comment]
This is sort of a duplicate of #716

**Comment by johnotu** [comment]
True. My bad.
