### ISSUE TITLE
Tests are wrongly passed for the "Storing Values with the Assignment Operator" challenge

### ISSUE THREAD

**Issue by payal-prksh** [FreeCodeCamp/FreeCodeCamp#7890]
#### Issue Description
* When Issue Happens : Every time
* Steps To Reproduce : Assign the value of 7 to b. The next line has the code b = a;
On running the tests, it finds the value of 'a' to be 'undefined' and the value of 'b' as 7.
-> If the line b = a; is present and is not commented out, it passes all the test cases. 
-> If the line b = a; is commented out, it still passes all the test cases. 
-> If the line b = a; is removed the test "a should be assigned to b with =" does not pass. 

#### Browser Information
* Browser Name, Version : Google Chrome, 49.0.2623.110 (64-bit)
* Operating System : Ubuntu 14.04

#### Your Code

```javascript
// Setup
var a;
var b = 2;

// Only change code below this line
b = 7;
//b = a;
```
#### Screenshot
![freecodecamperror1](https://cloud.githubusercontent.com/assets/1385489/14259697/5044daee-fa65-11e5-99d8-cbe08bb50bbd.png)

**Comment by jnmorse** [comment]
I tried to start working on this locally, but am unable to even open this challenge from my clone of the Free Code Camp Repo.

![unable-to-open](https://cloud.githubusercontent.com/assets/1467889/14329196/403fecf2-fc08-11e5-9227-047d059ec074.png)

Also it seems the name shows up differently

![different-name](https://cloud.githubusercontent.com/assets/1467889/14329207/4eb342a2-fc08-11e5-9824-d5301443a870.png)

I am able to open up most other challenges in the Basic Javascript section, haven't tried them all in Chrome but this one I can't for some reason.

**Comment by erictleung** [comment]
@jnmorse head over to https://gitter.im/FreeCodeCamp/HelpContributors for help on local instances.

**Comment by erictleung** [comment]
@payal-prksh I added new code with #7953 that might have fixed this. Can you try and see if you are still getting this problem? I wasn't able to reproduce this now, but I was able to before.

**Comment by payal-prksh** [comment]
@erictleung I tried to run the earlier code and the test cases failed (as it should do). The problem no longer persists and the fix helped. Thank you very much.

**Comment by erictleung** [comment]
@payal-prksh thanks for the feedback! Happy coding!

**Comment by RobAK84** [comment]
your should put b = 7; after a = 7;

a = 7; b = 7;
// b = a;                   there u go

**Comment by tgavin2017** [comment]
var myNum = 7;
var a = myVar;
var myVar = myNum;
var b = myNum;

//b = a;

**Comment by barkinet** [comment]
a = 7;
var myNum = 7;
var a = myVar;
var myVar = myNum;
var b = myNum;

//b = a;
