### ISSUE TITLE
this solution pass all the text but it is wrong. Add the case [1,2,3,1] [4,5,6]. Since there are 2 item with value 1, this solution will not add 1 in the final array. It should to be correct!

### ISSUE THREAD

**Issue by ninjasun** [FreeCodeCamp/FreeCodeCamp#7891]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays#?solution=function%20diff(arr1%2C%20arr2)%20%7B%0A%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%0A%20%20newArr%20%3D%20arr1.concat(arr2)%3B%0A%20%20console.log(%22arr%20total%20is%3A%20%22%2CnewArr)%3B%0A%20%20%0A%20%0A%20%20%2F%2Fcount%20occurence%20of%20item%20in%20array%0A%20%20%2F%2Freturn%20number%20of%20occurrence%20%3E%200%0A%20%20var%20count%20%3D%20function(item%2C%20array)%7B%0A%20%20%20%20var%20count%20%3D%200%3B%0A%20%20%20%20var%20i%3D0%3B%0A%20%20%20%20for%20(i%20%3B%20i%3Carray.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if%20(array%5Bi%5D%20%3D%3D%20item)%7B%0A%20%20%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20console.log(%22This%20item%3A%20%22%2Bitem%2B%22%20appears%3A%20%22%2B%20count%2B%22%20times!%22)%3B%0A%20%20%20%20return%20count%3B%0A%20%20%7D%3B%0A%20%20%0A%20arr%20%3D%20%5B%5D%3B%0A%20%0A%20var%20%20y%3D0%3B%0A%20%20var%20restOfArr%20%3D%20newArr.slice(0)%3B%0A%20%20%0A%20%20for%20(y%3B%20y%3CnewArr.length%3B%20%20y%2B%2B)%7B%0A%20%20%20%20%20if%20(restOfArr.length%20%3D%3D%200)%7B%0A%20%20%20%20%20console.log(%22EMPTY.%20RES%20IS%3A%20%22%2C%20arr)%3B%0A%20%20%20%20%20return%20arr%3B%0A%20%20%20%7D%0A%20%20%20%20%2F%2Fconsole.log(%22index%20is%3A%20%22%2C%20y)%3B%0A%20%20%20%20var%20item%20%3D%20restOfArr%5B0%5D%3B%0A%20%20%20%20console.log(%22item%20is%3A%20%22%2C%20item)%3B%0A%20%20%20%20restOfArr%20%3D%20restOfArr.slice(1)%3B%0A%20%20%20%0A%20%20%20%20var%20counter%20%3D%20count(item%2C%20restOfArr)%3B%0A%20%20%20%20%0A%20%20%20%0A%20%20%20%20if%20(counter%20%3D%3D%200)%7B%0A%20%20%20%20%20%20arr.push(item)%3B%0A%20%20%20%20%20%20restOfArr%20%3D%20restOfArr.filter(function(el)%7B%0A%20%20%20%20%20%20%20%20return%20el%20!%3D%3D%20item%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%2F%2F%20console.log(%22after%20delete%20item%20restOfArr%20is%3A%20%22%2C%20restOfArr)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20if%20(counter%20%3E%200)%7B%0A%20%20%20%20%20%20%2F%2Fce%20ne%20sono%202%20non%20addo%0A%20%20%20%20%20%20restOfArr%20%3D%20restOfArr.filter(function(el)%7B%0A%20%20%20%20%20%20%20%20return%20el%20!%3D%3D%20item%3B%0A%20%0A%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20console.log(%22rest%20of%20arr%3A%20%22%2C%20restOfArr)%3B%0A%0A%20%20%20%2F%2F%20console.log(%22FOR%3A%20arr%20is%3A%20%22%2Barr%2B%22%20newArr%20is%3A%20%22%2BnewArr)%3B%0A%20%20%20%0A%20%20%7D%0A%20%20%0A%0A%20%20return%20arr%3B%0A%7D%0A%0Adiff(%5B1%2C%202%2C%203%2C%205%5D%2C%20%5B1%2C%202%2C%203%2C%204%2C%205%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function diff(arr1, arr2) {
  var newArr = [];

  newArr = arr1.concat(arr2);
  console.log("arr total is: ",newArr);
  
 
  //count occurence of item in array
  //return number of occurrence > 0
  var count = function(item, array){
    var count = 0;
    var i=0;
    for (i ; i<array.length; i++){
      
      if (array[i] == item){
        count++;
      }
    }
    
    console.log("This item: "+item+" appears: "+ count+" times!");
    return count;
  };
  
 arr = [];
 
 var  y=0;
  var restOfArr = newArr.slice(0);
  
  for (y; y<newArr.length;  y++){
     if (restOfArr.length == 0){
     console.log("EMPTY. RES IS: ", arr);
     return arr;
   }
    //console.log("index is: ", y);
    var item = restOfArr[0];
    console.log("item is: ", item);
    restOfArr = restOfArr.slice(1);
   
    var counter = count(item, restOfArr);
    
   
    if (counter == 0){
      arr.push(item);
      restOfArr = restOfArr.filter(function(el){
        return el !== item;
      
     // console.log("after delete item restOfArr is: ", restOfArr);
    });
    }
    if (counter > 0){
      //ce ne sono 2 non addo
      restOfArr = restOfArr.filter(function(el){
        return el !== item;
 
    });
    }
    console.log("rest of arr: ", restOfArr);

   // console.log("FOR: arr is: "+arr+" newArr is: "+newArr);
   
  }
  

  return arr;
}

diff([1, 2, 3, 5], [1, 2, 3, 4, 5]);

```

**Comment by vaspv** [comment]
I am also having an issue with this - my code is passing the challenges but they are not becoming green. 

Code below:

`function diff(arr1, arr2) {
  var newArr = [];
  // Same, same; but different.
  
  newArr = arr1.concat(arr2);
  newArr.sort();
  var ans = [];
  var i = 1;
  
  for (i=1; i<newArr.length; i++) {
    if (newArr[i] !== newArr[i+1] && newArr[i] !== newArr[i-1] ) {
   ans.push(newArr[i]);
    }
   }
  
  return ans.sort();
}

diff(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);`

**Comment by erictleung** [comment]
@ninjasun thanks for the issue but I don't think it is necessary to add a test with duplicate elements in one array. This challenge IMO is on testing you to implement symmetric differences, which is actually a method on (mathematical) sets, which don't have duplicates. @SaintPeter thoughts?

@vaspv your code isn't working because we have been updating function names recently. Change your function `diff` to `diffArray` and then you should start seeing some checkmarks.

**Comment by vaspv** [comment]
Thanks Eric, working now.

**Comment by tushar3112** [comment]
I tried to pass different values in the array and it is working, but I am not able to clear this challenge.

If I am doing something wrong, any help would be appreciated.
I know there may be better ways of solving this particular challenge but right now I'm interested in what am I missing? or is it some kind of a bug?


```javascript
function diff(arr1, arr2) {
  var newArr = [];
  // Same, same; but different.
 for (var i = 0;i<arr1.length;i++) {
   if(arr2.indexOf(arr1[i]) === -1) {
     newArr.push(arr1[i]);
   }
 }
  for(var j=0;j<arr2.length;j++) {
    if(arr1.indexOf(arr2[j]) === -1) {
      newArr.push(arr2[j]);
    }
  }
  return newArr;
}

diff(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);
```

**Comment by vaspv** [comment]
Hi as per Eric above  - Change your function diff to diffArray and then you should start seeing some checkmarks.

**Comment by tushar3112** [comment]
Ok it worked, although it din't make any sense.

**Comment by SaintPeter** [comment]
@erictleung For this earlier bonfire I don't know that we need to have corner cases like duplicate elements in one array.

**Comment by JoshCheek** [comment]
@erictleung I think duplicates would be good, it would allow a user to discover that these are to be treated like sets. Also, it doesn't really make sense to think of them as sets, since arrays impose ordering, and I thought the ordering was significant, which is where the difficulty came in. If a user thinks ordering matters, it seems like it will follow a levenshtein style of solution, which makes it unnecessarily complicated. Another option would be to describe it in more accessible language like "Return the elements in only the first array followed by the elements in only the second"

**Comment by JoshCheek** [comment]
I'd advocate these tests:

```js
// the element in array 2 fulfills every element in array 1
diffArray([1, 1], [1]); // => []

// order doesn't matter, like a set
diffArray([1, 2], [2, 1]); // => []

// comparison does not get confused by types (eg I put them in as object keys to cache lookup, but that casts them to strings, so my solution was wrong)
diffArray([1], ['1']); // => [1, '1']
```
