### ISSUE TITLE
"Getting Started"-challenges need little content-updates

### ISSUE THREAD

**Issue by abisz** [FreeCodeCamp/FreeCodeCamp#7892]
While translating the "getting started" challenges, I noticed two little things that need an update:
* Learn What to Do If You Get Stuck (last text): the learn button doesn't exist anymore. I guess users won't be too confused, but on the other hand it's not that big deal to remove it from the description.
* Join a Campsite in Your City (second text): the button for instruction on how to create a campsite is at the beginning of the site (not the bottom, as the description suggests)

I hope this isn't to trivial, just thought I let you know.

**Comment by CharlesManga** [comment]
I'd like to help with this. Where should I go?

**Comment by erictleung** [comment]
@CharlesManga [This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/ab2df1a15a6607ec2cb2c2cf2fc49758987ef7cb/seed/challenges/00-getting-started/getting-started.json#L751) needs to be changed for the first problem in "Learn What to Do If you Get Stuck." [This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/ab2df1a15a6607ec2cb2c2cf2fc49758987ef7cb/seed/challenges/00-getting-started/getting-started.json#L663) needs to be changed for the second problem that is in "Join a Campsite in Your City." Please read over the [contributing guidelines document](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) for how to help. And if you run into any problems along the way, you can ask for help in the [contributors help Gitter room](https://gitter.im/FreeCodeCamp/HelpContributors). Good luck!

**Comment by josectello** [comment]
@CharlesManga If you don't get around to it, I'd like to give a shot as well.

**Comment by erictleung** [comment]
PR #7934 closes this.
