### ISSUE TITLE
Profile update buttons

### ISSUE THREAD

**Issue by teddy-error** [FreeCodeCamp/freecodecamp#79]
The update profile info buttons are all disabled for no apparent reason, and so users cannot add profiles/info

**Comment by terakilobyte** [comment]
Can you provide a sceenshot please?

**Comment by teddy-error** [comment]
![2015-02-05-031735_1600x900_scrot](https://cloud.githubusercontent.com/assets/1146921/6057640/a00005e6-ace5-11e4-8cb6-00b4bdbdb6a0.png)

**Comment by teddy-error** [comment]
I think it auto populated the email field with an invalid email and I didn't notice, because it didn't show an error message. This causes all of the other buttons to disable as well.
![2015-02-05-031735_1600x900_scrot](https://cloud.githubusercontent.com/assets/1146921/6057668/db9c0528-ace5-11e4-8a13-cfe2355bdbc2.png)

**Comment by terakilobyte** [comment]
Yep, that is the reason. I'm going to close this issue as it's not something the server does anymore. We'll look at writing a script to scrub the database.

You can also alleviate this by providing an email address.
