### ISSUE TITLE
Bootstrap call not actually included in code.

### ISSUE THREAD

**Issue by EngineeredEdge** [FreeCodeCamp/freecodecamp#790]
Beginning at 'Waypoint: Mobile Responsive Images' we begin to use the responsive CSS framework called bootstrap. Further, the text of the problem states:

"You can add Bootstrap to any app just by including it with link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'/ at the top of your HTML. But we've gone ahead and automatically added it to your Cat Photo App for you."

However, that call is not actually included in the code for that waypoint or any subsequent waypoints in the section. Instead we only get-
"link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'"

**Comment by BerkeleyTrue** [comment]
Hey @EngineeredEdge,

Its not included explicitly in the waypoints editor as this is included in the challenges page html itself. You can verify this by looking in Dev-Tools file source tab under the bootstrapcdn domain.

Thanks and good luck with the rest of the challenges!

![waypoint__fill_in_the_blank_with_placeholder_text___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/7951926/94a86754-0962-11e5-95a8-ae3997044014.png)
