### ISSUE TITLE
The tests aren't passing. I've checked all variations and they should pass. I noticed between yesterday and today that the provided function name changed from where() to whereAreYou()

### ISSUE THREAD

**Issue by oscarbaruffa** [FreeCodeCamp/FreeCodeCamp#7902]
Challenge [Where art thou](https://www.freecodecamp.com/challenges/where-art-thou#?solution=console.clear()%3B%0A%0Aconsole.log(%22******START************%22)%3B%0A%0Avar%20resultArr%20%3D%5B%5D%3B%0A%0Afunction%20whereAreYou(collection%2C%20source)%20%7B%0A%0A%20%20for%20(var%20i%20%3D%200%3B%20i%3C%20collection.length%3B%20i%2B%2B)%7B%0A%20%20%20%20var%20objectStr%20%3D%20JSON.stringify(collection%5Bi%5D)%3B%0A%20%20%20%20console.log(%22Object%20%22%2Bi%2B%22%3A%22%2BobjectStr)%3B%0A%0A%20%20%20var%20sourceStr%20%3D%20JSON.stringify(source)%3B%0A%20%20%20console.log(%22Source%3A%22%2BsourceStr)%3B%0A%0A%20%20%20var%20objectMatch%20%3D%20true%3B%20%0A%20%20%20%20var%20sourcePropArray%20%3D%20Object.keys(source)%3B%0A%0A%20%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3CsourcePropArray.length%3B%20j%2B%2B)%20%7B%20%20%0A%20%20%20%20%20%20var%20sourceProp%20%3D%20%20sourcePropArray%5Bj%5D%3B%0A%20%20%20%20%20%20var%20sourceValue%20%3D%20%20source%5BsourceProp%5D%3B%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%20if%20(collection%5Bi%5D.hasOwnProperty(sourceProp)%20%3D%3D%3D%20true)%20%7B%0A%20%20%20%20%20%20%20console.log(%22Yes%20property%22)%3B%0A%20%20%20%20%20%20%20%20if%20(collection%5Bi%5D%5BsourceProp%5D%20%3D%3D%3D%20sourceValue)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%2F%2Fconsole.log(%22Value%20match%22)%3B%0A%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20else%20%7B%20%0A%20%20%20%20%20%20%2F%2Fconsole.log(%22No%20value%20match%22)%3B%0A%20%20%20%20%20%20%20%20%20%20%20objectMatch%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%7D%20%0A%0A%20%20%20%20else%20%7B%20%0A%20%20%20%20%20%20console.log(%22No%20property%22)%3B%0A%20%20%20%20%20%20objectMatch%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%7D%0A%20%20%20%20if%20(objectMatch%20%3D%3D%3D%20true)%7B%0A%20%20%20%20%20%2F%2F%20console.log(%22Object%20Match%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F%2F%3F%20%22%2BobjectMatch)%3B%0A%20%20%20%20%20%20resultArr.push(collection%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%7D%0A%0Aconsole.log(%22-----------END---------------%22)%3B%0Areturn%20resultArr%3B%0A%0A%7D%0A%0A%0AwhereAreYou(%5B%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D%5D%2C%20%7B%20%22a%22%3A%201%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
console.clear();

console.log("******START************");

var resultArr =[];

function whereAreYou(collection, source) {

  for (var i = 0; i< collection.length; i++){
    var objectStr = JSON.stringify(collection[i]);
    console.log("Object "+i+":"+objectStr);

   var sourceStr = JSON.stringify(source);
   console.log("Source:"+sourceStr);

   var objectMatch = true; 
    var sourcePropArray = Object.keys(source);

     for (var j = 0; j <sourcePropArray.length; j++) {  
      var sourceProp =  sourcePropArray[j];
      var sourceValue =  source[sourceProp];
       
       
      if (collection[i].hasOwnProperty(sourceProp) === true) {
       console.log("Yes property");
        if (collection[i][sourceProp] === sourceValue) {
           //console.log("Value match");

        }
         else { 
      //console.log("No value match");
           objectMatch = false;
         }
       } 

    else { 
      console.log("No property");
      objectMatch = false;
         }
     }
    if (objectMatch === true){
     // console.log("Object Match???????????????????????/? "+objectMatch);
      resultArr.push(collection[i]);
    }
    
    
   }

console.log("-----------END---------------");
return resultArr;

}


whereAreYou([{ "a": 1 }, { "a": 1 }, { "a": 1, "b": 2 }], { "a": 1 });

```

**Comment by oscarbaruffa** [comment]
I've checked all variations and they should pass. I noticed between yesterday and today that the provided function name changed from where() to whereAreYou()

**Comment by AkiraLaine** [comment]
@oscarbaruffa Hey! I can confirm your code works. This is weird, but you can pass the challenge by copying all of your code in your ```whereAreYou``` function. Reset your code in the editor. And then paste your code within the function.

@FreeCodeCamp/issue-moderators Do you guys see why this code doesn't pass? I might be missing something.

**Comment by oscarbaruffa** [comment]
Hi, thanks - I reset and repasted it and it passed. I think I know what was wrong, in part anyway, I was declaring var resultArr =[]; above the function. Moving it inside the function passes all the tests.
