### ISSUE TITLE
create note to ignore the editors warnings regarding unreachable break after return

### ISSUE THREAD

**Issue by akdacquel** [FreeCodeCamp/FreeCodeCamp#7907]
the requirements to pass the exercise conflicts with the editor warnings.  Either the pseudo code encourages bad practice, the warning is irrelevant and should be ignored( a note would help) or the requirement promotes a practice that will get your editor to throw warnings.

Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20switch%20(val)%20%7B%0A%20%20case%201%3A%0A%20%20return%20%22alpha%22%3B%0A%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20case%202%3A%0A%20%20return%20%22beta%22%3B%0A%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20case%203%3A%0A%20%20return%20%22gamma%22%3B%0A%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%0A%20%20case%204%3A%20%0A%20%20return%20%22delta%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%7D%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  
  switch (val) {
  case 1:
  return "alpha";
     break;
      
  case 2:
  return "beta";
  break;
      
  case 3:
  return "gamma";
  break;
      
      
  case 4: 
  return "delta";

  // Only change code above this line  
  return answer;  
}
}
// Change this value to test
myTest(1);


```

**Comment by erictleung** [comment]
@akdacquel this challenge actually wants you to write one return statement and multiple assignment statements. This hinted to be the way the challenge wants you to solve it because of the `var answer = ""` at the beginning and the `return answer` near the end. Plus, there are comments indicating where you should put your code. So change your case to the look like the following and you'll be fine. Happy coding!

```
case 1:
  answer = "one answer";
  break;
...
```
