### ISSUE TITLE
Possible Bug With Loading Challenges Outputs

### ISSUE THREAD

**Issue by tupelo87** [FreeCodeCamp/FreeCodeCamp#7908]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
When i load a Challenege i can not see the outputs needed which is a problem as i need to enter some random code to see it so i can understand better what the question is asking me to do.
* Steps To Reproduce
Loading any Challenge

#### Browser Information
* Browser Name, Version
Firefox 45.0.1 & Chrome 49.0.2623.110 
* Operating System
Windows 10

#### Screenshot
![nooutputs](https://cloud.githubusercontent.com/assets/17498889/14272681/0e8c295c-fafd-11e5-85a0-7a366872edfe.jpg)
this is what i am trying to see but have to either hit run tests or enter code depending on if there is code there to run. (different challenges the one i show outputs on i had to click run tests)
![theoutputs](https://cloud.githubusercontent.com/assets/17498889/14272802/da02f3ea-fafd-11e5-8561-2390e87ccbd8.jpg)

**Comment by erictleung** [comment]
Sometimes this happens because there are intentional issues with the original code, but the [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup) challenge isn't one of them. So for me, this rarely happens. @FreeCodeCamp/issue-moderators thoughts?

**Comment by tupelo87** [comment]
this happens on all the code scenarios i load i can not see the outputs unless code is run

**Comment by sludge256** [comment]
This has happened to me on occasion, but I have not been able to reproduce the issue, or determine the cause. Pure speculation, but this issue seems to come and go regardless of what the user does. If it happens to me again I can attempt to investigate in a more detailed manner.

**Comment by raisedadead** [comment]
Closing as stale, please comment is still facing this to re-open.
