### ISSUE TITLE
GitHub email not necessarily becoming user email

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7909]
I discovered a camper's record that had a "githubEmail" property (pulled from GitHub), but had no "email" property. They weren't getting our email updates and wanted them. 

"githubEmail": "user@example.com"

User story: When I link my GitHub account with my FCC account, it should check whether I have an email address, and if not set it to my githubEmail.

@BerkeleyTrue what do you think of this?

**Comment by NicholasAsimov** [comment]
Yeah, ai had this problem too. I would like to subscribe to news aggregation email you announced on Medium but didn't get any.
I registered through Github auth,

**Comment by raisedadead** [comment]
@NicholasAsimov If you go to your settings page on FreeCodeCamp, you can update your email with us. This has been introduced recently.

**Comment by raisedadead** [comment]
@BerkeleyTrue this issue is also resolved with the below I believe? 
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/utils/auth.js#L37

**Comment by NicholasAsimov** [comment]
@raisedadead Yeah, I updated the email recently and it worked flawlessly, I recieved Quincy's news email too.

**Comment by BerkeleyTrue** [comment]
Yes.

Happy Coding!
