### ISSUE TITLE
Waypoint: Fill in the Blank with Placeholder Text (Typo)

### ISSUE THREAD

**Issue by mike591** [FreeCodeCamp/freecodecamp#791]
Challenge http://www.freecodecamp.com/challenges/waypoint-fill-in-the-blank-with-placeholder-text has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

In the instructions, it says to use the "Ktty Ipsum" text when it should be "Kitty Ipsum".

http://www.evernote.com/shard/s585/sh/fa0d5334-514c-4c0b-935f-d38bdf1ce0b2/d3b194b1a5877176205cd71ba2a5f02c

**Comment by BerkeleyTrue** [comment]
@mike591 This has been fixed. Thanks again @mike591
