### ISSUE TITLE
Oops error triggered when changing email settings without email address

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7911]
Steps to reproduce (only occurs in FireFox):
- create an account without an email address (Twitter doesn't provide one, for example)
- go to /settings and attempt to change the email settings
- You will get an oops error

**Comment by Ab1d** [comment]
i would like to help on this, can you give me more info on where to start on this?

**Comment by raisedadead** [comment]
This is resolved as of the new migration. Users without an email will not be shown the email settings except for an option to add one.
Refer #8232
