### ISSUE TITLE
Challenge has dead link

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7912]
Challenge [Assignment with a Returned Value](https://www.freecodecamp.com/challenges/assignment-with-a-returned-value) has an issue.

It attempts to link to https://www.freecodecamp.com/challenges/waypoint-storing-values-with-the-equal-operator but should instead link to https://www.freecodecamp.com/challenges/assignment-with-a-returned-value

**Comment by plavakutlaca** [comment]
Thank you .... I just wanted to add that it is not the Challenge that is the issue but the text in the Challenge......   One reference in Challenge text description should open and it's linked to   https://www.freecodecamp.com/challenges/waypoint-storing-values-with-the-equal-operator
but this link is not valid anymore, maybe exercise name was changed ...  so it starts to load this url and that redirects to https://www.freecodecamp.com/map.....

**Comment by alistermada** [comment]
Yes, the challenge was renamed to [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator).

**Comment by nsgonultas** [comment]
Opened a pull request, can you check it please? #7913
