### ISSUE TITLE
I think it's a bug, Diff Two Arrays or may be not, please I would like some help.

### ISSUE THREAD

**Issue by tushar3112** [FreeCodeCamp/FreeCodeCamp#7914]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays#?solution=function%20diff(arr1%2C%20arr2)%20%7B%0A%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20Same%2C%20same%3B%20but%20different.%0A%20for%20(var%20i%20%3D%200%3Bi%3Carr1.length%3Bi%2B%2B)%20%7B%0A%20%20%20if(arr2.indexOf(arr1%5Bi%5D)%20%3D%3D%3D%20-1)%20%7B%0A%20%20%20%20%20newArr.push(arr1%5Bi%5D)%3B%0A%20%20%20%7D%0A%20%7D%0A%20%20for(var%20j%3D0%3Bj%3Carr2.length%3Bj%2B%2B)%20%7B%0A%20%20%20%20if(arr1.indexOf(arr2%5Bj%5D)%20%3D%3D%3D%20-1)%20%7B%0A%20%20%20%20%20%20newArr.push(arr2%5Bj%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20newArr%3B%0A%7D%0A%0Adiff(%5B1%2C%20%22calf%22%2C%203%2C%20%22piglet%22%5D%2C%20%5B1%2C%20%22calf%22%2C%203%2C%204%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function diff(arr1, arr2) {
  var newArr = [];
  // Same, same; but different.
 for (var i = 0;i<arr1.length;i++) {
   if(arr2.indexOf(arr1[i]) === -1) {
     newArr.push(arr1[i]);
   }
 }
  for(var j=0;j<arr2.length;j++) {
    if(arr1.indexOf(arr2[j]) === -1) {
      newArr.push(arr2[j]);
    }
  }
  return newArr;
}

diff([1, "calf", 3, "piglet"], [1, "calf", 3, 4]);

```

I tried to pass different values in the array and it is working, but I am not able to clear this challenge.

If I am doing something wrong, any help would be appreciated.
I know there may be better ways of solving this particular challenge but right now I'm interested in what am I missing? or is it some kind of a bug?

**Comment by alistermada** [comment]
Change your function name from `diff` to `diffArray`. 

The name of the function for this challenge was changed about two weeks ago. You may have loaded the old function name if you visited this challenge before the change.

**Comment by erictleung** [comment]
@tushar3112 @alistermada is correct. Change your function name from `diff` to `diffArray` and you should be fine. Happy coding!
