### ISSUE TITLE
Waypoint: Import a Google Font (Incorrect placement still marked as correct)

### ISSUE THREAD

**Issue by mike591** [FreeCodeCamp/freecodecamp#792]
Challenge http://www.freecodecamp.com/challenges/waypoint-import-a-google-font has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Placing the import under <style> rather than above will still mark the task as correct even though it is not.

http://www.evernote.com/shard/s585/sh/e8204d62-aff1-4d4a-b060-db96c55bf1d9/bb3429035b5ce46a2e8db87b4ec479a4

**Comment by BerkeleyTrue** [comment]
Hey @mike591,

Thanks for bringing this to our attention. It doesn't matter where the link tag is, as long as the link tag is included somewhere on the page, but we are going to be changing the wording here to instruct the camper to just copy the link in but not specifying where.

Good Luck with the rest of the challenges!
