### ISSUE TITLE
Retire blog and use nginx redirects to Medium

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#7920]
We still get some search traffic to blog.freecodecamp.com, but we can instead send this to medium.freecodecamp.com
- [ ] Audit blog to make sure all articles have been cross-posted on Medium
- [ ] Create nginx redirect for each article

**Comment by BerkeleyTrue** [comment]
@QuincyLarson I'm closing this as it isn't actionable on the repo or by our users.
