### ISSUE TITLE
Arguments Optional

### ISSUE THREAD

**Issue by k-drive** [FreeCodeCamp/FreeCodeCamp#7922]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

01 Issue Description
When I paste my code into the window, I get an error where the comment on a right bracket says: 
"/ / end of inner function"

The error is: "Missing semicolon".
The error red line indicactor is between the two forward slashes and the word "end" in the comments.

* Steps To Reproduce
I paste my code into the window.

Note: There are no issues/errors when I test/paste the code into JSLint.com

02 Issue Description
I am not sure if this is related. But, my code solves all the test cases in the project in both CodePen and when I run it in my browser. But, the first two test cases fail when I run it in FreeCodeCamp:

addTogether(2, 3) should return 5.
addTogether(2)(3) should return 5.

#### Browser Information
* Chrome 49.0.2623.87
* Windows

My code:

function addTogether() {

  var c; // This will handle undefined values.
var nbr = "number";

if(arguments.length ===1 && typeof arguments[0] === "string"){

// alert("c "+ c);
return c;

}

  if(arguments.length === 1) {
  return function (b2) { // You could call this b or b2.
	if((typeof a === nbr) && (typeof b2 ===  nbr)) {
		c = (a+b2);
		// alert("Inner function "+ c);
		return c;  // It would shadow (hide, supercede) the one above.
		}
	else {
		// alert("c "+c);
		return c;
		}
	} // end of inner function.
		
  }
    
  if((typeof a === nbr) && (typeof b === nbr)){
  c = (a+b);
 // alert("Outer function "+ c);
  return c;
  }
  else {
	// alert("c "+c);
	return c;
  }
  
  
}

addTogether(2,3);

**Comment by kehugter** [comment]
> "/ / end of inner function"

You have a space there. Are you sure that your code in the editor doesn't have it?

**Comment by erictleung** [comment]
You're returning a function after your second `if` statement and that function needs a semicolon to finish off. Code issues are not handled on GitHub unless there is a bug with the site. Please take all future coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by k-drive** [comment]
kehugter: Thanks for the reply.
I checked my code in CodePen. The space is not there.
(If you look at my code listed, you will see the space is not there.)

**Comment by k-drive** [comment]
erictleung:

I see. The return statement needs the semicolon (not the function).
Thanks for pointing that out.

Are you in a particular Help Room? I tried them a couple of times. I never received a reply to my posts. It seems like they are for groups of coders who know each other. That is my impression from watching the conversations. It is difficult to tell, of course, just from my computer.

Have a good day.
Happy coding!

Ken

**Comment by erictleung** [comment]
@k-drive I'm not too active in the help rooms but I'm in all the main ones and I check frequently. Yeah, sometimes the conversations can go pretty fast and people who actually need help get taken over. I would stay persistent. If need be, you can always tag me in a help room if you need help and I'll get a notification. Good luck!

**Comment by k-drive** [comment]
erictleung: Thank you. I will give the help rooms another try.
