### ISSUE TITLE
stored messages

### ISSUE THREAD

**Issue by luvfknhrts** [FreeCodeCamp/FreeCodeCamp#7926]
#### FreeCodeCamp Issue template
To Use this Template:
* Fill out what you can
* Delete what you do not fill out

NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for Help at https://gitter.im/FreeCodeCamp/Help

#### Issue Description
* When Issue Happens
* Steps To Reproduce

#### Browser Information
* Browser Name, Version
* Operating System

#### Your Code

```js
If relevant, paste all of your challenge code in here
```

**Comment by AkiraLaine** [comment]
Hey! If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is for issues only. Happy Coding :smile:

**Comment by luvfknhrts** [comment]
I want notifications
