### ISSUE TITLE
Test cases not validating, even though my code returns the correct values in Friendly Date Ranges

### ISSUE THREAD

**Issue by llamatarianism** [FreeCodeCamp/FreeCodeCamp#7928]
```js
//jshint esversion:6

const monthsList = ["January ", "February ", "March ", "April ", "May ", "June ", "July ", "August ", "September ", "October ", "November ", "December "];
let results = [];

function convertDate(str) {
  let dateArr = str.split('-');
  return (new Date(Date.UTC(dateArr[0], dateArr[1] - 1, dateArr[2])));
}

function dateEnding(day) {
  switch(day) {
    case "1,":
    case "21,":
    case "31,":
      return day.slice(0, -1) + "st" + day.slice(-1);
    case "2,":
    case "22,":
      return day.slice(0, -1) + "nd" + day.slice(-1);
    case "3,":
    case "23,":
      return day.slice(0, -1) + "rd" + day.slice(-1);
    default:
      return day.slice(0, -1) + "th" + day.slice(-1);
  }
}

function monthsDiff(date1, date2) {
  let month1 = date1.getUTCMonth();
  let month2 = date2.getUTCMonth();
  return Math.abs(month1 - month2);
}

function makeFriendlyDates(arr) {
  let date1 = convertDate(arr[0]);
  let date2 = convertDate(arr[1]);
  let options = { year: 'numeric', month: 'long', day: 'numeric' };
  
  results.push(date1.toLocaleDateString('en-US', options).split(" "));
  results.push(date2.toLocaleDateString('en-US', options).split(" "));
  results[0][1] = dateEnding(results[0][1]);
  results[1][1] = dateEnding(results[1][1]);
  
  if (date2 - date1 === 0) {
    results.pop();
  } else if (monthsDiff(date1, date2) === 0 && date2 - date1 < 2764800000) {
    results[0].pop();
    results[1].shift();
    results[1].pop();
    results[1][0] = results[1][0].slice(0, -1);
  } else if (monthsDiff(date1, date2) && date2 - date1 < 31536000000) {
    results[1].pop();
    results[1][1] = results[1][1].slice(0, -1);
  } else if (date2 - date1 < 31536000000) {
    results[1].pop();
    results[1][1] = results[1][1].slice(0, -1);
  }
  results[0] = results[0].join(" ");
  results[1] = results[1].join(" ");
  
  let merged = [].concat.apply([], results);
  return merged;
}

makeFriendlyDates(["2022-09-05", "2023-09-05"]); // ["September 5th, 2022","September 5th, 2023"]
```
This code will return the correct values for all the test cases, but none of the test cases will validate. I have tried this on both Chrome and Firefox. I have hard refreshed and opened FCC in a new tab/window. I even re-typed the entire code from scratch instead of copy-pasting it, and it still won't work.

[Here is a link to the challenge.](https://www.freecodecamp.com/challenges/friendly-date-ranges)

[Here are some example screenshots,](http://imgur.com/a/PGqhG) demonstrating that my code returns the correct values, but the test cases do not pass.

**Comment by erictleung** [comment]
@llamatarianism Mmm my guess is that the way the editor and the JS compiler works on FCC is that it takes your function name exclusively to test. All other functions you use won't be used. Can anyone confirm or correct me? @FreeCodeCamp/issue-moderators

**Comment by SaintPeter** [comment]
@llamatarianism The problem is with your `results` array being global.
When the tests are run, your function is called multiple times.  As written, only for the first run will `results` start as an empty array.  For each subsequent test run `results` will contain the prior runs results.

The best solution is to simply move your `let results = []` inside your main function.  Then you're starting with a "fresh slate" every time the function is run.

@erictleung There is no problem with having additional functions.  So long as the "main" function matches, everything will be called properly.

**Comment by raisedadead** [comment]
@llamatarianism Please check the comments above to get the tests passing.

Closing this as stale. 

Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any further assistance to Coding.

Happy Coding!
