### ISSUE TITLE
Waypoint: Add borders around your elements (doesn't accept shorthand for border as a solution)

### ISSUE THREAD

**Issue by ciosifweb** [FreeCodeCamp/freecodecamp#793]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has the following issue:

Using the shorthand for border (border: 10px solid green) is not accepted as a valid solution, border style needs to be specified individually.

Repro steps:

1. Create the "thick-green-border" class
2. Add the following in the class body: border: 10px solid green;

Actual behavior: The following assert fails: Give your image a border style of "solid".

Expected behavior: Shorthand notation should be accepted as a proper solution.

Screenshot bellow:

![image](https://cloud.githubusercontent.com/assets/10694248/7921190/698b9336-08ac-11e5-87b9-770eb4eb12d3.png)

**Comment by BerkeleyTrue** [comment]
Hey @ciosifweb,

This should be fixed in the latest version. If you are still having issues please feel free to re-open this issue.

![waypoint__add_borders_around_your_elements___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/7951659/3fccb210-095f-11e5-9cda-98fd10b7e631.png)
