### ISSUE TITLE
fullstack certification (bug or what ?)

### ISSUE THREAD

**Issue by linuxenko** [FreeCodeCamp/FreeCodeCamp#7930]
So .. why ?

[![](https://pbs.twimg.com/media/CfXYjmiWsAAaPw1.jpg)](https://pbs.twimg.com/media/CfXYjmiWsAAaPw1.jpg)

**Comment by BerkeleyTrue** [comment]
What exactly is the issue?

**Comment by sludge256** [comment]
@linuxenko Thanks for posting. We'll be updating the functionality of this section with https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7931.

In the mean time, you can join this room https://gitter.im/FreeCodeCamp/HalfWayClub on Gitter and state that you're ready to get started on the nonprofit projects. There is also more information about the process here https://www.freecodecamp.com/how-nonprofit-projects-work.
