### ISSUE TITLE
Update "Nonprofit Projects" section

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#7931]
![image](https://cloud.githubusercontent.com/assets/10524623/14326225/edbf3508-fbe1-11e5-829e-a9e1de90530d.png)

The challenges should be unlocked if a camper has obtained all three required certifications.

They should also link to https://gitter.im/FreeCodeCamp/HalfWayClub in order to facilitate the process of getting started with the nonprofit projects.

**Comment by CharlesManga** [comment]
I would like to help. where should I go?

**Comment by sludge256** [comment]
@CharlesManga This is a good starting point: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

There's also a [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have additional questions.

**Comment by NicolaFerracin** [comment]
Hey @sludge256 , I found this issue and saw there hasn't been any update in the last couple of months, would it be ok for me to pick it up?

If yes, I was wondering where should we link the list items to? You suggested the HalfWay Club, but if I'm not wrong we shouldn't be using that chat anymore.

Second question: the Coding Interview Preparation section presents the same problem: the challenges inside should be unlocked if a camper has obtained all 4 certs. Should we fix that too since it's almost the same thing? If so, again, where should the challenges link to?

**Comment by sludge256** [comment]
@NicolaFerracin You can definitely pick this up. I'll let you know what we want to link to instead of the now defunct Halfway Club room.

cc: @CodeNonprofit 
What do you think?
Some alternatives would be your email or https://www.freecodecamp.com/how-nonprofit-projects-work

**Comment by CodeNonprofit** [comment]
@sludge256 I'd prefer the info document over my email. Otherwise I'd just get hundreds of emails with questions answered in our comprehensive document. Thanks!

**Comment by NicolaFerracin** [comment]
@sludge256 So, I started looking into it and I'm not sure how to proceed: if I understood it correctly all the other challenges pull data from DB and based on that the challenges are shown differently (as never seen, new, completed, coming soon, etc...). And the challenges are split in different superBlocks representing the sections.
![768f639ebd6b18e6214ef95922df90f6](https://cloud.githubusercontent.com/assets/7750769/15977551/b8f903c0-2f59-11e6-889e-7b6b9c9a1e6f.png)

But for the Nonprofit or Coding Interview sections there isn't any dedicated superBlock, so I'm not sure what's the best solution here. Even if we do create a dedicated one, how does a camper set one of these challenges as completed? Any ideas?

That's what I have so far:
![c8fdfd9547dd588626ed12c06703f95b](https://cloud.githubusercontent.com/assets/7750769/15977622/1b1e19fa-2f5a-11e6-9544-c0296e2a9711.png)

**Comment by QuincyLarson** [comment]
We plan to completely overhaul the nonprofit projects section (and the map) in the near future, and this will become a non-issue. So I am closing this issue.
