### ISSUE TITLE
example project does not have twitter authentication

### ISSUE THREAD

**Issue by kalunlee136** [FreeCodeCamp/FreeCodeCamp#7933]
Challenge [Build a Pinterest Clone](https://www.freecodecamp.com/challenges/build-a-pinterest-clone) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

One of the requirements for this project is to have twitter user authentication, but the example project only has local authentication.

**Comment by raisedadead** [comment]
It does have twitter auth for me, can you post some screenshots?

**Comment by kalunlee136** [comment]
wait nevermind, i found the twitter login. i didn't see it initially because i thought it was just text and not a button.
