### ISSUE TITLE
Shirt campaigns in "Shop"

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#7935]
#### Screenshot
![image](https://cloud.githubusercontent.com/assets/6234475/14327838/514fe2c0-fbf1-11e5-9cce-498fbec0cec4.png)

Hey friends.  It would be super rad if shirt campaigns were featured on the "Shop" page of FCC.  I know that I, for one, check the Shop fairly regularly but I guess I've missed the last couple shirt campaigns.

![shut up and take my money](https://tse4.mm.bing.net/th?id=OIP.M203bdc39b3830070cb441f406ea6de11H0&pid=15.1)

**Comment by QuincyLarson** [comment]
@sludge256 @ArielLeslie I'm on this! :) Should have a PR in ~15 mins.

**Comment by QuincyLarson** [comment]
Closed with this PR: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7941
