### ISSUE TITLE
Emphasis, Not italicize

### ISSUE THREAD

**Issue by dlaskey** [FreeCodeCamp/FreeCodeCamp#7939]
Challenge [Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0</code>.

The challenge asks for italicizing of the test; however, the test can't be passed unless the emphasis element is used. 

My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<i>#target4</i>");
    
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by diilmac** [comment]
i got same issue

**Comment by erictleung** [comment]
@SaintPeter I remember changing this recently. Should we also change the wording to `emphasize` to make it less semantically conflicting with users? I don't see an issue in doing so as we already changed the tag to the emphasis tags, `em`.

**Comment by SaintPeter** [comment]
Yes, we can change the wording to `emphasize`.   

We say: 
> Here's how you would rewrite and italicize the text of our heading:

and 

> Change the button with id target4 by italicizing its text.

Just replace `italicizing` with `emphasizing`.

**Comment by josectello** [comment]
May I submit a PR for this? Unless someone else is already on it.

**Comment by erictleung** [comment]
@josectello go for it! :+1:

**Comment by josectello** [comment]
Great! #7948

**Comment by dlaskey** [comment]
Thanks guys, this had me stumped all last night until I dropped by the FCC Reddit.

**Comment by mayankpatel15** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>#target4</em>");
  });
</script>
