### ISSUE TITLE
A wrong test case in "Confirm the Ending"  exercise

### ISSUE THREAD

**Issue by Bharat-Kalluri** [FreeCodeCamp/FreeCodeCamp#7940]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=function%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20ans%20%3D%20%22%22%3B%0A%20%20arr%20%3D%20str.split(%22%20%22)%3B%0A%20%20if(arr.length%20%3D%3D%201)%20%7B%0A%20%20%20%20if(target%20%3D%3D%20arr%5B0%5D.substring(arr%5B0%5D.length-1))%20%7B%0A%20%20%20%20%20%20ans%20%3D%20true%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20else%20if(arr.length%20%3E%201)%20%7B%0A%20%20%20%20if(arr%5Barr.length-1%5D%20%3D%3D%20target)%20%7B%0A%20%20%20%20%20%20ans%20%3D%20true%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20%7B%20%0A%20%20%20%20%20%20ans%20%3D%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20ans%3B%0A%7D%0A%0AconfirmEnding(%22He%20has%20to%20give%20me%20a%20new%20name%22%2C%20%22me%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  ans = "";
  arr = str.split(" ");
  if(arr.length == 1) {
    if(target == arr[0].substring(arr[0].length-1)) {
      ans = true;
    }
    else {
      return false;
    }
  }
  else if(arr.length > 1) {
    if(arr[arr.length-1] == target) {
      ans = true;
    }
    else { 
      ans = false;
    }
  }
  return ans;
}

confirmEnding("He has to give me a new name", "me");

```

This code if perfectly fine, but there is a wrong test case stating that

> confirmEnding("He has to give me a new name", "me") should return true.

it should be false.

**Comment by sludge256** [comment]
The string does end with "me", "He has to give me a new na**me**".

**Comment by JBuji** [comment]
my code:
function confirmEnding(str, target) {
    return str.substr(-target.length)==target;
}
confirmEnding("He has to give me a new name", "me");

**Comment by BrunoFDeveloper** [comment]
@JBuji your solution is very smart, congratulations =D

**Comment by JBuji** [comment]
@BrunoFDeveloper Thank you. "helpful link" was very useful.
