### ISSUE TITLE
Correct answer shown in terminal can't clear challenge.

### ISSUE THREAD

**Issue by iamraymond69** [FreeCodeCamp/FreeCodeCamp#7950]
Challenge [Adding a default option in Switch statements](https://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements#?solution=function%20myTest(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%20%7B%0A%20%20case%20%22a%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22apple%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20case%20%22b%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22bird%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22c%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22cat%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20answer%20%3D%20%22stuff%22%3B%0A%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(%22a%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myTest(val) {
  var answer = "";
  // Only change code below this line
  switch(val) {
  case "a":
      answer = "apple";
      break;
  case "b":
      answer = "bird";
      break;
    case "c":
      answer = "cat";
      break;
    default:
      answer = "stuff";
      
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest("a");


```

I get the correct answer in my terminal box under the "Run Test" but none of the challenges change from the red "x" to a green check. I have posted in several FCC help areas and no code changes have been suggested.

**Comment by erictleung** [comment]
@iamraymond69 we've been updating function names recently and some of them haven't changed in the editor. Change the function name from `myTest` to `switchOfStuff` and that should solve your problems. Happy coding!

**Comment by iamraymond69** [comment]
@erictleung Thanks solved the problem perfectly.

Take good care.
