### ISSUE TITLE
results is coming up but i'm unable to move to next page

### ISSUE THREAD

**Issue by devmurali6** [FreeCodeCamp/FreeCodeCamp#7951]
Challenge [Where art thou](https://www.freecodecamp.com/challenges/where-art-thou#?solution=function%20where(collection%2C%20source)%20%7B%0A%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20var%20keys%20%3D%20Object.keys(source)%3B%0A%20%20%0A%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20return%20collection.filter(function(item)%20%7B%0A%20%20%20%20return%20item%5Bkeys%5D%20%3D%3D%3D%20source%5Bkeys%5D%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%20%0A%20%0A%20%20%0A%0A%20%0A%0A%20%20%0A%20%0A%20%20%0A%0A%20%0A%7D%0A%0Awhere(%5B%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D%5D%2C%20%7B%20%22a%22%3A%201%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(collection, source) {

  var arr = [];
  var keys = Object.keys(source);
  
 
  
  
  
  
  return collection.filter(function(item) {
    return item[keys] === source[keys];
  });
  
  
  
  
   
 
  

 

  
 
  

 
}

where([{ "a": 1 }, { "a": 1 }, { "a": 1, "b": 2 }], { "a": 1 });

```

**Comment by erictleung** [comment]
@devmurali6 we've been changing function names lately so change `where` to `whereAreYou` and you should see some results. Happy coding!
