### ISSUE TITLE
can't login using github

### ISSUE THREAD

**Issue by sic-f** [FreeCodeCamp/FreeCodeCamp#7954]
#### Issue Description
* Last week Apr 1st, 2016
* Can't login using Github *see screenshot below*

#### Browser Information
* Firefox v. 45
* Windows, Ubuntu 14.10

#### Screenshot
![capture](https://cloud.githubusercontent.com/assets/17798988/14342491/87d8be3a-fccc-11e5-86c8-1e8787638205.PNG)

**Comment by sludge256** [comment]
Likely to be related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7560

**Comment by sludge256** [comment]
@sic-f Would you mind sending an email to team @freecodecamp.com and reference this issue? We can investigate any potential problems there may be with your account.

**Comment by sludge256** [comment]
Closing as stale. If you are still having issues please send an email as stated in the comment above.
