### ISSUE TITLE
Exercise 206 dont test right

### ISSUE THREAD

**Issue by AlVSidorov** [FreeCodeCamp/FreeCodeCamp#7956]
#### Issue Description
Issue Happens when a test 'Return Early Pattern for Functions' challenge in FCC.
To Reproduce add the condition logic ' if (a<0 || b<0){return "undefined";} ' into the code.
 
#### Browser Information
Firefox 44.0.2
Windows 8.1 Professional

#### Your Code
// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if ( (a < 0) || (b < 0) ) {
    return "undefined";
    }
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,-2);

#### Screenshot
![206](https://cloud.githubusercontent.com/assets/17743562/14348383/c7cf8382-fcc4-11e5-99b8-9b1acff2fd19.jpg)

**Comment by erictleung** [comment]
@AlVSidorov Code issues are not handled on GitHub unless there is a bug with the site. Please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: look at the hint given on the page of this challenge (you can see a glimpse of it even on your screen shot). Happy coding!
