### ISSUE TITLE
Typo: Global vs Local Scope in Functions challenge has inconsistent function name

### ISSUE THREAD

**Issue by gyousuf** [FreeCodeCamp/FreeCodeCamp#7957]
Challenge [Global vs Local Scope in Functions](https://www.freecodecamp.com/challenges/global-vs-local-scope-in-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.

The instructions refer to the function in the challenge to be submitted as "myOutfit" whereas the pre-populated code refers to it as "myFunction". Challenge will fail unless user updates "myFunction" with "myOutfit" prior to submitting.

![image](https://cloud.githubusercontent.com/assets/4924941/14354900/ead344c6-fc93-11e5-867b-84b888f52781.png)

My code:
```javascript
// Setup
var outerWear = "T-Shirt";

function myFunction() {
  // Only change code below this line
  
  
  
  // Only change code above this line
  return outerWear;
}

myFunction();

```

**Comment by erictleung** [comment]
@gyousuf thanks for the issue. We have recently been updating certain function names and the change is slowly propagating. Clicking the reset button should pre-populate the editor with the correct code. Happy coding!
