### ISSUE TITLE
Array.sort() broken in Challenge: "Where do I belong"

### ISSUE THREAD

**Issue by dedalux** [FreeCodeCamp/FreeCodeCamp#7960]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20quicksort(arr)%0A%7B%0A%20%20%20%20if%20(arr.length%20%3D%3D%200)%0A%20%20%20%20%20%20%20%20return%20%5B%5D%3B%0A%20%0A%20%20%20%20var%20left%20%3D%20new%20Array()%3B%0A%20%20%20%20var%20right%20%3D%20new%20Array()%3B%0A%20%20%20%20var%20pivot%20%3D%20arr%5B0%5D%3B%0A%20%0A%20%20%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if%20(arr%5Bi%5D%20%3C%20pivot)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20left.push(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20right.push(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%0A%20%20%20%20return%20quicksort(left).concat(pivot%2C%20quicksort(right))%3B%0A%7D%3B%0A%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20%0A%20%20arr%20%3D%20arr.sort()%3B%0A%20%20console.log(arr)%3B%0A%20%20var%20i%20%3D%20arr.length%20-%201%0A%20%20while%20(i%20%3E%3D%200)%20%7B%0A%20%20%20%20if%20(num%20%3E%20arr%5Bi%5D)%20%7B%0A%20%20%20%20%20%20return%20i%20%2B%201%0A%20%20%20%20%7D%20else%20if%20(num%20%3D%3D%20arr%5Bi%5D)%20%7B%0A%20%20%20%20%20%20return%20i%0A%20%20%20%20%7D%3B%0A%20%20%20%20i--%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20false%3B%0A%7D%0A%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

For some reason regular Array.sort() returns this... I had to implement a custom sort method to get the right sorted results...

![image](https://cloud.githubusercontent.com/assets/6294548/14360454/c9503382-fcf6-11e5-8916-997706139763.png)

My code:
```javascript
function quicksort(arr)
{
    if (arr.length == 0)
        return [];
 
    var left = new Array();
    var right = new Array();
    var pivot = arr[0];
 
    for (var i = 1; i < arr.length; i++) {
        if (arr[i] < pivot) {
           left.push(arr[i]);
        } else {
           right.push(arr[i]);
        }
    }
 
    return quicksort(left).concat(pivot, quicksort(right));
};

function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  
  arr = quicksort(arr)
  var i = arr.length - 1
  while (i >= 0) {
    if (num > arr[i]) {
      return i + 1
    } else if (num == arr[i]) {
      return i
    };
    i--;
  }
  
  return false;
}

getIndexToIns([40, 60], 50);

```

**Comment by alistermada** [comment]
That's exactly how `Array.sort()` is supposed to work.  If you are unsure about how to get `Array.sort()` to sort numbers, check out the [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) that was linked in the challenge.

**Comment by erictleung** [comment]
@alistermada is right. That is what is expected from the JavaScript version of `Array.sort()`. I would read the MDN page he linked to. It'll probably give you insight into what you'd like `Array.sort()` to do. Happy coding!

**Comment by dedalux** [comment]
Didn't know! Guess I was used to sorting single digit number and it always worked out as expected

**Comment by Dnnsmoyo** [comment]
Hello my code returns the  position after sorting but it doesnt seem correct i dont know why
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  var j = [];
  var s = arr.concat(num);
   j = s.sort();
  if(j == s) {
    return j.indexOf(num);
  }
  return j;
}


getIndexToIns([40, 60], 50);

**Comment by texas2010** [comment]
@Dnnsmoyo, Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
