### ISSUE TITLE
Cannot claim Front end dev cert

### ISSUE THREAD

**Issue by carefulAxe** [FreeCodeCamp/FreeCodeCamp#7963]
Hi, this looks to be the same as issue #5174, which is closed.

When I try to claim my front end development certificate at:
https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate

When I get to step 3, and I click "Open link in new tab (this unlocks this step)", I get an "Oops" error.

Console log says:
Failed to parse SourceMap: https://www.freecodecamp.com/challenges/rx.all.map

Screenshot below:

![image](https://cloud.githubusercontent.com/assets/9951362/14366150/2f14af12-fcc6-11e5-82ce-dfef605976f6.png)

**Comment by carefulAxe** [comment]
I don't know if it helps but I started the front end curriculum in Sep 2015, then put it on hold for a few months (Nov, Dec, Jan). When I came back, I noticed the curriculum had changed, some challenges were added and a couple projects I had completed had been removed, although those I had completed still showed. Maybe the parser is expecting the most up to date curriculum but choking on some of the old ones I did..?

**Comment by codemzy** [comment]
I am having the same problem getting the back end certificate :cry: 

It seems to mess up at the same step. I managed to trick it to let me through that step... which may have been a mistake because now the back-end certificate challenge is ticked, but my certificate has not been added to my portfolio :disappointed:

**Comment by konato** [comment]
I have the same problem, I cannot get my Front End Certificate.

**Comment by carefulAxe** [comment]
I would recommend each person experiencing this to create an issue, so that
it will get attention.

**Comment by konato** [comment]
I did updated an issue on git.

Thank you,

Stephane



Confidentiality Warning: This message, including any attachment, is sent
only for the use of the intended recipient; it is confidential and may
constitute privileged information. If you are not the intended recipient,
you are hereby notified that any printing, copying, distribution or other
use of this message is strictly prohibited. If you have received this email
in error, please notify the sender immediately by return email, and delete
it. Thank you!


2016-04-08 12:57 GMT-04:00 Yulgene Suh <notifications@github.com>:

> I would recommend each person experiencing this to create an issue, so that
> it will get attention.
> On Apr 8, 2016 9:49 AM, "Stephane Rousseau" <notifications@github.com>
> wrote:
>
> > I have the same problem, I cannot get my Front End Certificate.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7963#issuecomment-207508926
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7963#issuecomment-207514237>
>

ᐧ

**Comment by BerkeleyTrue** [comment]
I'm working on a solution. Thank you all for your patience.

**Comment by BerkeleyTrue** [comment]
Fix is in production. Thanks for you patience.

Happy Coding!
