### ISSUE TITLE
Getting the correct results, tests not passing, not sure why

### ISSUE THREAD

**Issue by kristenmthayer** [FreeCodeCamp/FreeCodeCamp#7965]
Challenge [Pig Latin](https://www.freecodecamp.com/challenges/pig-latin#?solution=function%20translate(str)%20%7B%0A%20%20var%20firstLetter%20%3D%20str.charAt(0)%3B%0A%20%20var%20secondLetter%20%3D%20str.charAt(1)%3B%0A%20%20if%20(str.charAt(0)%3D%3D%3D%22a%22%7C%7Cstr.charAt(0)%3D%3D%3D%22e%22%7C%7Cstr.charAt(0)%3D%3D%3D%22i%22%20%7C%7C%20str.charAt(0)%3D%3D%3D%22o%22%7C%7Cstr.charAt(0)%3D%3D%3D%22u%22)%7B%0A%20%20%20%20str%20%2B%3D%20%22way%22%3B%0A%20%20%7D%0A%20%20else%20if%20(str.charAt(1)%3D%3D%3D%22a%22%7C%7Cstr.charAt(1)%3D%3D%3D%22e%22%7C%7Cstr.charAt(1)%3D%3D%3D%22i%22%20%7C%7C%20str.charAt(1)%3D%3D%3D%22o%22%7C%7Cstr.charAt(1)%3D%3D%3D%22u%22)%7B%0A%20%20%20%20str%20%3D%20str.slice(1)%3B%0A%20%20%20%20str%20%2B%3D%20firstLetter%20%2B%20%22ay%22%3B%0A%20%20%7D%0A%20%20%0A%20%20else%20%7B%0A%20%20%20%20str%20%3D%20str.slice(2)%3B%0A%20%20%20%20str%20%2B%3D%20firstLetter%20%2B%20secondLetter%20%2B%20%22ay%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0Atranslate(%22paragraphs%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

You can see in the screenshot that the word logged in the console is correct, but the tests aren't passing.
<img width="923" alt="piglatin" src="https://cloud.githubusercontent.com/assets/15021800/14367795/eb054760-fcce-11e5-8b43-f12744a15342.PNG">

My code:
```javascript
function translate(str) {
  var firstLetter = str.charAt(0);
  var secondLetter = str.charAt(1);
  if (str.charAt(0)==="a"||str.charAt(0)==="e"||str.charAt(0)==="i" || str.charAt(0)==="o"||str.charAt(0)==="u"){
    str += "way";
  }
  else if (str.charAt(1)==="a"||str.charAt(1)==="e"||str.charAt(1)==="i" || str.charAt(1)==="o"||str.charAt(1)==="u"){
    str = str.slice(1);
    str += firstLetter + "ay";
  }
  
  else {
    str = str.slice(2);
    str += firstLetter + secondLetter + "ay";
  }
  
  return str;
}

translate("paragraphs");

```

**Comment by rouje** [comment]
The name of your function is `translate` while the guide needs the function `translatePigLatin`. Change your function name and I think it will pass.

**Comment by sludge256** [comment]
If you change your function name and function call from `translate` to `translatePigLatin` your code will pass. There was a batch of function name updates that occurred yesterday and you loaded the challenge seed before it happened causing this issue. We have some things in the works to prevent this from happening in the future. Thanks for posting.

**Comment by kristenmthayer** [comment]
Thanks!

**Comment by kristenmthayer** [comment]
Thanks!
