### ISSUE TITLE
Confusing problem statement in Friendly Date Ranges

### ISSUE THREAD

**Issue by danielcodes** [FreeCodeCamp/FreeCodeCamp#7967]
#### Friendly Date Ranges
https://www.freecodecamp.com/challenges/friendly-date-ranges

#### Issue Description

There is an inconsistency with how the problem is described and what is seen on the test cases.

```
1. if the date range ends in less than a year from when it begins, do not display the ending year. 
2. If the range ends in the same month that it begins, do not display the ending year or month.
3. Additionally, if the date range begins in the current year and ends within one year, the year should not be displayed at the beginning of the friendly range.
```

Aren't rules 1 and 3 the same? They're both asking to do something with the range when it is less than a year. So far it seems that it is looking to get rid of the year if that is the case. 

Then the test cases throw further confusion,

```javascript
//test cases #2, 4 and 6
makeFriendlyDates(["2016-12-01", "2017-02-03"]) should return ["December 1st","February 3rd"].
makeFriendlyDates(["2017-03-01", "2017-05-05"]) should return ["March 1st, 2017","May 5th"]
makeFriendlyDates(["2022-09-05", "2023-09-04"]) should return ["September 5th, 2022","September 4th"].
```

In all of these test cases, the range is ending in less than a year. Yet they're being handled differently.
Two display the years while one doesn't. As I was coding through the challenge, I seemed to be hardchecking lots of things and this was because I was being required to handle one case in two different ways.

Some clarification on this would be appreaciated,
Thanks

**Comment by alistermada** [comment]
Rule 1 determines whether or not the second date should display the year. Rule 3 is the same, but for the first date.

However, Rule 3 also includes "if the date range begins in the current year". The second test case has no year displayed because it starts at 2016 (current year) and ends in less than a year.

**Comment by erictleung** [comment]
@danielcodes what @alistermada has described is correct. The tests and descriptions are consistent with each other. I guess we could add emphasis tags on the dates that are required to make it more clear as to the differences between each requirement.

> ...if the date range ends in less than a year from when it begins, do not display the *ending year*. 
> ...If the range ends in the same month that it begins, do not display the *ending year or month*.
> ...Additionally, if the date range begins in the current year and ends within one year, the year should not be displayed at the *beginning* of the friendly range.

**Comment by danielcodes** [comment]
Ohh, ok. I missed the 'current year part' and that threw me into a world of confusion. The third rule should be placed right after the first or even under it since it adds on top of it. Technically everything follows the 'do something' for date ranges under a year, but if it starts on the current year, 'do this as well'.  

Thanks! @alistermada @erictleung

**Comment by josectello** [comment]
Anyone currently tackling this? If not, I'd love to jump in.

**Comment by erictleung** [comment]
@josectello go for it! You'll need to change [these two lines of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/e85da70d465d8d54bd1f6e27dc6e092632d3a14c/seed/challenges/01-front-end-development-certification/advanced-bonfires.json#L268-L269) to something like this:

> Do not display information that is redundant or that can be inferred by the user. If the date range ends in less than a year from when it begins, do not display the `<em>`ending year`</em>`.
> 
> Additionally, if the date range begins in the `<em>`current year`<em>` and ends within one year, the year should not be displayed at the `<em>`beginning`</em>` of the friendly range.
> 
> If the range ends in the same month that it begins, do not display the `<em>`ending year or month`<em>`.

**Comment by rvlewerissa** [comment]
I got to admit this question is so confusing, in terms of how the problem is described :(
