### ISSUE TITLE
Does Not Past Test but my code returns matches the returns in the test

### ISSUE THREAD

**Issue by asaki444** [FreeCodeCamp/FreeCodeCamp#7970]
Challenge [Where art thou](https://www.freecodecamp.com/challenges/where-art-thou#?solution=function%20where(collection%2C%20source)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20var%20result%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20What's%20in%20a%20name%3F%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20collection.length%3B%20i%2B%2B)%7B%0A%20%20%20%20var%20keys%20%3D%20Object.keys(source)%3B%0A%20%20%20%20var%20include%20%3D%20true%3B%0A%20%20%20%20for(var%20j%20%3D%200%3B%20j%20%3C%20keys.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20if(collection%5Bi%5D%5Bkeys%5Bj%5D%5D%20!%3D%3D%20source%5Bkeys%5Bj%5D%5D)%7B%0A%20%20%20%20%20include%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20if(include)%7B%0A%20%20%20%20%20%20%20%20result.push(collection%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%0A%20return%20result%3B%0A%7D%0A%0Awhere(%5B%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D%5D%2C%20%7B%20%22a%22%3A%201%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(collection, source) {
  var arr = [];
  var result = [];
  // What's in a name?
  for(var i = 0; i < collection.length; i++){
    var keys = Object.keys(source);
    var include = true;
    for(var j = 0; j < keys.length; j++){
      if(collection[i][keys[j]] !== source[keys[j]]){
     include = false;
        break;
      }
    }
    if(include){
        result.push(collection[i]);
      }
    } 
 return result;
}

where([{ "a": 1 }, { "a": 1 }, { "a": 1, "b": 2 }], { "a": 1 });

```

**Comment by erictleung** [comment]
@asaki444 We have recently been updating certain function names and the change is slowly propagating. Change your function `where` to `whereAreYou` and your code should work. If you notice this inconsistency in the future, you can click on the "Reset" button and it should pre-populate the editor with the correct code. Happy coding!
