### ISSUE TITLE
All the tests are failing on my solution which has previously succeeded. The sample result is returning correctly.

### ISSUE THREAD

**Issue by MadOgre** [FreeCodeCamp/FreeCodeCamp#7971]
Challenge [Where art thou](https://www.freecodecamp.com/challenges/where-art-thou#?solution=function%20where(collection%2C%20source)%20%7B%0A%0A%20%20return%20collection.filter(function(thing)%7B%0A%20%20%20%20%20%20for%20(var%20key%20in%20source)%7B%0A%20%20%20%20%20%20%20%20if%20(thing%5Bkey%5D%20!%3D%3D%20source%5Bkey%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20return%20true%3B%0A%20%20%7D)%3B%0A%7D%0A%0Awhere(%5B%7B%20first%3A%20%27Romeo%27%2C%20last%3A%20%27Montague%27%20%7D%2C%20%7B%20first%3A%20%27Mercutio%27%2C%20last%3A%20null%20%7D%2C%20%7B%20first%3A%20%27Tybalt%27%2C%20last%3A%20%27Capulet%27%20%7D%5D%2C%20%7B%20last%3A%20%27Capulet%27%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(collection, source) {

  return collection.filter(function(thing){
      for (var key in source){
        if (thing[key] !== source[key]){
          return false;
        }
      }
    return true;
  });
}

where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet' });

```

**Comment by erictleung** [comment]
@MadOgre We have recently been updating certain function names and the change is slowly propagating. Change your function `where` to `whereAreYou` and your code should work. If you notice this inconsistency in the future, you can click on the "Reset" button and it should pre-populate the editor with the correct code. Happy coding!
