### ISSUE TITLE
I had to change code above the line - the function name was wrong

### ISSUE THREAD

**Issue by wbrennan899** [FreeCodeCamp/FreeCodeCamp#7974]
Challenge [Multiple Identical Options in Switch Statements](https://www.freecodecamp.com/challenges/multiple-identical-options-in-switch-statements#?solution=function%20sequentialSizes(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%20%7B%0A%20%20%20%20case%201%3A%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Low%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Mid%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20answer%20%3D%20%22High%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20default%3A%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AmyTest(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sequentialSizes(val) {
  var answer = "";
  // Only change code below this line
  switch(val) {
    case 1:
    case 2:
    case 3:
      answer = "Low";
      break;
    case 4:
    case 5:
    case 6:
      answer = "Mid";
      break;
    case 7:
    case 8:
    case 9:
      answer = "High";
      break;
    default:
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
myTest(1);


```

**Comment by erictleung** [comment]
@wbrennan899 thanks for the issue. We have recently been updating certain function names and the change is slowly propagating. If you notice this inconsistency in the future, you can click on the "Reset" button and it should pre-populate the editor with the correct code. Happy coding!
