### ISSUE TITLE
comparisons-with-the-logical-or-operator challenge has the wrong function name.

### ISSUE THREAD

**Issue by AidenKerr** [FreeCodeCamp/FreeCodeCamp#7975]
#### Challenge Name

comparisons-with-the-logical-or-operator

#### Issue Description

The function that is already written has the wrong name. You must rename the function to testLogicalOr or else it will fail.

Edit: re-looking at it, it seems to be fixed.

**Comment by erictleung** [comment]
@AidenKerr We have recently been updating certain function names and the change is slowly propagating. If you notice this inconsistency in the future, you can click on the "Reset" button and it should pre-populate the editor with the correct code. Happy coding!
