### ISSUE TITLE
 Browser and Text zoom should be at 100%.

### ISSUE THREAD

**Issue by cgrewal** [FreeCodeCamp/FreeCodeCamp#7976]
Here is my code:

<style>
  .red-text {
    color: red;
    p{font-size:16px;}
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

tried on two different browser's with 100% zoom,still getting this error

**Comment by erictleung** [comment]
@cgrewal Code issues are not handled on GitHub unless there is a bug with the site. Hint: there is an issue with your code in the style section. Please take your coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by phamvien** [comment]
Unable to pass the 100% browser zoom at 100%.  I am running chrome: Version 49.0.2623.110 m

Screen shot below:

![image](https://cloud.githubusercontent.com/assets/11760199/14510951/d66f2aee-0199-11e6-9b45-f92280652a7b.png)

**Comment by erictleung** [comment]
@phamvien check your CSS rules (the code in between the `<style>` tags). You have a mistake there. If you continue having difficulty, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by kaungkhant620** [comment]
@phamvien DO U FORGET FULLSTOP(.)......CHECK OUT...

**Comment by fausty1** [comment]
This is how it is suppose to be :)
.red-text {
    color: red;} 
  p{font-size:16px;}

**Comment by texas2010** [comment]
@fausty1 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by axiomteck** [comment]
is showing me a red circle with an x and it show Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%.

**Comment by axiomteck** [comment]
never mind i was adding a dot to the P tag sorry guys i figure out

**Comment by DVPRASADRAYUDU** [comment]
Instead of adding in between  style tags:
Add style attribute at the <p>tag itself like below:
<p style="font-size:16px">

**Comment by fahadi123** [comment]
<style>
  .red-text {
    color: red;
  }
  
  p {    
    font-size: 16px;
    zoom: 100%;
  }  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum text</p>
<p> Kitty ipsum text. Purr jump eat the grass</p>

**Comment by joshdrochon** [comment]
Make sure the p element isn't highlight pink, (or any element for that matter). That was my problem. For some reason the element kept wanting to highlight pink.

**Comment by Mr-Sonnet** [comment]
# The Actual **Problem** is:

> **when we do the right still we get the error massage showing in the bottom** 

And we don't press` ctrl` + `enter` 🥇 


> The error is on the site,



**Just Submit your answer you will see a `success` massage.** 

Thanks me later.
.

**Comment by rajeshtanwar89** [comment]
ghost bad answer

**Comment by AjuanM** [comment]
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

> Aquí está mi código:
> 
> <style> .red-text {color: rojo; p {tamaño de fuente: 16px;}} </style>
> ## CatPhotoApp
> Kitty ipsum dolor sit amet, derramado por todas partes derramado por todas partes estiramiento ataca tus tobillos persigue el punto rojo, bola de pelo corre catnip come la hierba olfatea.
> 
> Ronroneo saltar comer la hierba rasgar el sofá rayado tomar el sol, cobertizo por todas partes rasgar el sofá dormir en el fregadero piel esponjosa catnip rayado.
> 
> probé en dos navegadores diferentes con un zoom del 100%, pero todavía aparece este error

<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
  }
</style>
