### ISSUE TITLE
string.replace() did't remove all space on the string.

### ISSUE THREAD

**Issue by The14thNoah** [FreeCodeCamp/FreeCodeCamp#7979]
#### Challenge Name

https://www.freecodecamp.com/challenges/check-for-palindromes

#### Issue Description

string.replace on remove the first character to be remove on the string and the rest still on the text. Example is string.replace(" ","") only remove the first white space on the string.
I comment my codes on this challenge and check every functions I used and I found this issue. Is this a bug or I'm missing something?

#### Browser Information

* Browser Name, Version: Google Chrome Version 49.0.2623.110 m
* Operating System:  Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/16794644/14377693/bab0da54-fda3-11e5-9110-991dcbd6f1ea.png)

**Comment by elazzabi** [comment]
Hello,
From the [documentation ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)

> To perform a global search and replace, either include the g switch in the regular expression or if the first parameter is a string, include g in the flags parameter.

So you have _two solutions_: Use a RegEx, or include a flag.
**Note (From the same page):** The flags argument does not work in v8 Core (Chrome and Node.js) and will be removed from Firefox.

**Comment by The14thNoah** [comment]
Thanks for the response.
I include a flag from my codes and work fine except for replacing dot character ("."). when I use string.replace(/./g,"") it returns a blank string.

**Comment by The14thNoah** [comment]
All right, I get it. I just need to search deeply on Google for this problem. Thanks for the response @elazzabi 

![image](https://cloud.githubusercontent.com/assets/16794644/14379649/aff018dc-fdad-11e5-8d5c-20c828e0fa26.png)

**Comment by erictleung** [comment]
Looks like your problem is solved. In the future, please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
