### ISSUE TITLE
Passed with a red border

### ISSUE THREAD

**Issue by Philosophist** [FreeCodeCamp/freecodecamp#798]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Just do the task, but instead of typing "border-color: green;" type "border-color: red;" It will pass despite not following the instructions.

 I found this out by typing from the example rather than the initial instructions. Thought it would be preferable to make sure it's green.

**Comment by BerkeleyTrue** [comment]
This is fixed in latest version. Thanks for letting us know!
