### ISSUE TITLE
Broken Link to "Storing Values with the Equal Operator"

### ISSUE THREAD

**Issue by Hitoshura** [FreeCodeCamp/FreeCodeCamp#7981]
Challenge [Generate Random Fractions with JavaScript](https://www.freecodecamp.com/challenges/generate-random-fractions-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The link to "Storing Values with the Equal Operator" is broken, as that page doesn't seem to exist.  Most likely, it's supposed to link to this page:

https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator

Clicking the current link redirects back to the Map page with: "We couldn't find a challenge with the name -storing-values-with-the-equal-operator. Please double check the name."

**Comment by erictleung** [comment]
Yeah, we change the naming of that challenge recently. I believe the `href` link in [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/98efa93c68376d8e85f3e3f7ceaf9adb2b5c0b94/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4956) needs to be changed to

```
storing-values-with-the-assignment-operator
```

**Comment by DusanSacha** [comment]
Hello, I am new here and would like to contribute.
This issue looks like easy to learning. I will take care of it.
