### ISSUE TITLE
Jade renamed to Pug

### ISSUE THREAD

**Issue by owenfromcanada** [FreeCodeCamp/FreeCodeCamp#7983]
As of Dec. 2015, the Jade package has been renamed to Pug (see https://github.com/pugjs/pug/issues/2184).  Expressworks tutorial is still referring to Jade.

Issue submitted for ExpressWorks package as well (https://github.com/azat-co/expressworks/issues/111), but the FreeCodeCamp page may want to suggest skipping the JADE portion of the tutorial for now.

Challenge [Build Web Apps with Expressjs](https://www.freecodecamp.com/challenges/build-web-apps-with-expressjs) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.

**Comment by awesomeaniruddh** [comment]
The API is still the same, and plugins for gulp etc. still refer to Jade. The transition to PugJS is far from complete at this moment. Instead of skipping over the Jade tutorial, we can perhaps add a little note that the package has been renamed to Pug, although they are still working on updating Jade plugins.

**Comment by BerkeleyTrue** [comment]
@awesomeaniruddh Sounds good

**Comment by matthewfortier** [comment]
@awesomeaniruddh Hey there, I am a beginner when it comes to FOSS projects, and this seems like a change that I would be able to do, could you give me some more details to the change you would like and I can submit at PR? Thanks!

**Comment by Jago-Kosolosky** [comment]
@BerkeleyTrue @awesomeaniruddh @owenfromcanada First pull request here but I think I did OK, added a small comment. https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8336/files
