### ISSUE TITLE
not understanding

### ISSUE THREAD

**Issue by tarun47900** [FreeCodeCamp/FreeCodeCamp#7986]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%3C!--how%20ARE%20YOU%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--how ARE YOU
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->

```

**Comment by erictleung** [comment]
@tarun47900 thanks for the issue, but code issues are not handled on GitHub unless there is a bug with the site. Please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
