### ISSUE TITLE
response fas not able to finish this

### ISSUE THREAD

**Issue by tarun47900** [FreeCodeCamp/FreeCodeCamp#7989]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--hi%20ji%20--%3E%3Ch1%3EHello%20World%20%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--now%20ji%20--%3E%3Cp%3EHello%20Paragraph%20%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--hi ji --><h1>Hello World </h1>

<h2>CatPhotoApp</h2>

<!--now ji --><p>Hello Paragraph </p>

```

**Comment by BerkeleyTrue** [comment]
Can you describe the issue you are having and steps to reproduce it?

**Comment by tarun47900** [comment]
not able to comment out my first heading as in challenge  given

**Comment by BerkeleyTrue** [comment]
@tarun47900 Issue tracker is for reporting bugs.

Use the [help chat](https://gitter.im/freecodecamp/help) when you get stuck.

Happy Coding!
