### ISSUE TITLE
Credit card for heroku?

### ISSUE THREAD

**Issue by Lajt** [FreeCodeCamp/freecodecamp#799]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hi, when i try complete above waypoint
checkpoint 46:
Set the config flag for your Heroku environment and add MongoLab for your MongoDB instance by running the following command: cd ~/workspace/dist && heroku config:set NODE_ENV=production && heroku addons:add mongolab.

I get this:
http://i.imgur.com/Odkvvxv.jpg

Does that mean i need to verify my account with credit card?
I dont have any so is it impossible to complete basejumps for me?

**Comment by BerkeleyTrue** [comment]
Hey @Lajt,

Unfortunately this is Heroku's policy when using addons and we cannot change this. 

Here is more information: https://devcenter.heroku.com/articles/account-verification

Heroku's billing is very transparent and they do not charge unless you step outside their defined limits.

Good Luck with the rest of the Challenges.

**Comment by Lajt** [comment]
@BerkeleyTrue so is there any other way for me to complete basejumps? like post only github link? i dont have credit card so i cant verify heroku account.
