### ISSUE TITLE
Feature Request: Alternative test cases to be hidden from users

### ISSUE THREAD

**Issue by DanJFletcher** [FreeCodeCamp/FreeCodeCamp#7990]
#### Issue Description

All bonfires it seems can be passed with hard coded solutions, and some of them are exceptionally easy to do so.

I've noticed a few challenges where a hard coded solution is much easier than a programmatic one, and it's possible to pass all test cases w/o writing an algorithm.

One example is in Smallest Common Multiples.

The following will pass:
```js
function smallestCommons(arr) {
  if (arr[0] === 1)
    if (arr[1] === 13) {return 360360;}
    else return 60;
  return 60;
}
```

Of course it's unethical to do this and request a front-end certificate after completing bonfires this way. It's also a valid argument that since FCC is open source, users can look up the solutions in the source code if they really wanted to anyway.

I still feel it would be a benefit to have test cases that are not shown to the user to prevent hard coded solutions such as this.

Are there any thoughts on whether or not this is desirable?

**Comment by erictleung** [comment]
@DanJFletcher I agree that some challenges could be solved with hard coded but in my opinion, the tests are purposely shown to encourage [test-driven development](https://en.wikipedia.org/wiki/Test-driven_development). In the real world, you should get feedback on what cases your function will fail at and then you can iterate again to make your function better.

With that challenge (The Smallest Common Multiples) in particular, someone else has [brought up insufficiencies in the current tests](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7292).

So if you feel a challenge has tests that don't cover broad enough of a range of cases, you can always create an issue to create more.

**Comment by BerkeleyTrue** [comment]
I agree with @erictleung. While we discourage this kind of behavior, ultimately it only harms those who try to pass challenges in this manner.

The last couple of months have seen a lot of improvements focused on production and cost. In the next couple of weeks we will see improvements in UX and in the challenge framework. These improvements, among many other things, should include the ability to create tests with random inputs, mocking/stubbing, and async tests. 

While those improvement can help prevent this kind of cheating, we always have worked on the assumption that we won't be able to stop all cheaters and instead we should focus on curriculum and the experience.

Happy Coding!

**Comment by DanJFletcher** [comment]
@erictleung @BerkeleyTrue I see what both of you are saying.I think you make good points. For one I strongly agree that for those who deside to cheat, they are only hurting themselves in the end. It also makes sense to focus more on features that add to the UX and the curriculum. 

However, I still think an interface similar to what these guys use is still a good idea: https://www.codingame.com/games/puzzles

I like that you are given a set of test cases to pass, and then test your algorithm for it's robustness against tests that you can not see. @erictleung You mention that we are trying to encourage TDD as such would be used in the real world. I argue that it's not always the case that our tests represent all cases, as many use cases in any system can be missed by a requirements analysis, which is why most dev cycles use some form of iteration like Agile. An algorithm is rarely as robust as we believe it is before having used and tested by real users. Here in FCC, the hidden tests would add an element of realism to the challenges; pass the provided tests, and then send the algorithm out against use cases that might not have been considered during the first attempt.

Check out the format codingame uses. It's definitely an interesting concept that I think deserves careful consideration.  

Thanks for the reply.

Cheers!

**Comment by erictleung** [comment]
@DanJFletcher I just checked it out and worked out one of their challenges. CodinGame reminds me of CodeWars (http://www.codewars.com/). I agree that in the real world, you aren't handed everything on a platter and some use cases might not be obvious at first. 

However, in my opinion, FCC's focus is on being a learning community for new programmers, while CodinGame (where their tagline is "**Improve your skills** by solving algorithmic puzzles") and CodeWars (where their tagline is "Codewars is where **developers achieve code mastery** through challenge.") are where developers go to master and improve their skills. Their demographic of programmers are totally different and their purpose are different. Thus, I still stand by FCC's philosophy in designing their challenges based on their target audience. Plus, obfuscating extra tests sounds like it would go against FCC's open source philosophy :smile:

Thanks again for your consideration in improving FCC to guard against cheaters and improve teaching learning programmers.  Happy coding!

**Comment by DanJFletcher** [comment]
@erictleung Thanks for looking into it further. You do make really good points, that I can't argue with. Sounds fair enough to me. I think the improvements @BerkeleyTrue suggested are going to help a lot with this issue anyways.

Thanks again,

Cheers!
