### ISSUE TITLE
REVIEW INSTRUCTIONS: parameters are not properly referenced(as such), causing confusion

### ISSUE THREAD

**Issue by tommygebru** [FreeCodeCamp/FreeCodeCamp#7992]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0Aif(value!%3D%3D%22%22)%0A%20%20%7B%0A%20%20%20%20if(prop!%3D%3D%22tracks%22)%7B%0A%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D%3Dvalue%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if%20(prop%3D%3D%3D%22tracks%22)%7Bcollection%5Bid%5D.tracks.push(value)%3B%7D%0A%0A%20%20%7D%2F%2Fend%20of%20first%20if%20statement%0A%20%20%20%20else%7Bdelete%20collection%5Bid%5D%5Bprop%5D%3B%7D%20%20%20%20%20%20%20%20%20%20%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
if(value!=="")
  {
    if(prop!=="tracks"){
      collection[id][prop]=value;
    }
    else if (prop==="tracks"){collection[id].tracks.push(value);}

  }//end of first if statement
    else{delete collection[id][prop];}          
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by erictleung** [comment]
@tommygebru can you be more specific on how the parameters are currently referenced confusing?

**Comment by tommygebru** [comment]
Of course... take a look at the explanation of the instructions as
explained here.....
https://github.com/Rafase282/My-FreeCodeCamp-Code/wiki/Lesson-Review-Record-Collection
notice how the parameters of the function named update, is being referenced
as a parameter......

**Comment by erictleung** [comment]
@tommygebru ah so you're referring specifically to the Wiki articles? The Wiki articles are undergoing an update along with the changes in the function names. If you'd like to help out change the `update` function to the correct function name, you can go [here](https://github.com/FreeCodeCamp/wiki/issues/615). Happy coding!
