### ISSUE TITLE
Buttons for the Map drawer are not visible in Night Mode

### ISSUE THREAD

**Issue by sludge256** [FreeCodeCamp/FreeCodeCamp#7999]
![screenshot of site in night mode](https://cloud.githubusercontent.com/assets/10524623/14399340/836ea9ac-fda0-11e5-8183-026e24a69a9e.png)

The exit and expand buttons are not visible in the top right.

**Comment by raisedadead** [comment]
@sludge256 and @hallaathrad lol thanks I should keep track of stuff more precisely.
