### ISSUE TITLE
It keeps showing this error message

### ISSUE THREAD

**Issue by Elifaz** [FreeCodeCamp/freecodecamp#800]
Challenge http://www.freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
<h1>Hello World</h1>

output: $ is not defined
What does this means? I have never seen this before.

**Comment by terakilobyte** [comment]
$ is not defined means jquery isn't defined. Can you take a screenshot with your developer console open? cmd option i on mac, cntl-alt-i on windows if I remember correctly.

**Comment by Elifaz** [comment]
Alright, I understood, I was using Tor as the browser and when I flipped to Chrome it worked just fine. So I'll be using chrome for this course. Thanks for the help!!
