### ISSUE TITLE
Suggestions regarding contrast for Night Mode in user portfolio

### ISSUE THREAD

**Issue by alistermada** [FreeCodeCamp/FreeCodeCamp#8001]
![image](https://cloud.githubusercontent.com/assets/12993334/14400255/a252ab5a-fe1f-11e5-8b21-9ae79a8970eb.png)

I think there's too much contrast between the table rows for the list of completed projects/challenges. Scrolling down hurts my eyes. I'd make white rows darker.

The text in the white rows is hard to read. A little more contrast here would be good.

I also suggest changing the white background for the heat map to match the page background color. It seems a bit out of place.

Other than that, I think the Night Mode looks pretty good.

**Comment by BKinahan** [comment]
Adding to this, here's how the close button on the map slide-out looks on night mode. Super low contrast.

<img width="35" alt="Map Slide-out Close Button" src="https://cloud.githubusercontent.com/assets/15965601/14403138/a6db26e0-fe3b-11e5-8802-afb18802579b.png">

**Comment by hallaathrad** [comment]
Ooh I'd missed these rows. Lemme fix that!
