### ISSUE TITLE
console.log does not work in "Check for Palindromes" challenge

### ISSUE THREAD

**Issue by edronen** [FreeCodeCamp/FreeCodeCamp#8003]
To simplify, I've removed everything and just left in the test. Please let me know if I'm doing anything wrong. I've also tested with using single quotes or just a plain number, which didn't work either. 

Any help is appreciated. 

Thank you :-) 

Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=console.log(%22this%20does%20not%20work%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
console.log("this does not work");

```

**Comment by sludge256** [comment]
Is it because you're looking at the FCC output area? It's not the same thing as your browser's console.
![console](https://cloud.githubusercontent.com/assets/10524623/14401000/db893c6c-fdb7-11e5-9563-c2a2eef35e7c.PNG)

**Comment by edronen** [comment]
@sludge256 - yes, newbie mistake. Thank you. (open hand, bring palm to forehead, smack)
