### ISSUE TITLE
Unable to change social account references.

### ISSUE THREAD

**Issue by ParaBolt** [FreeCodeCamp/FreeCodeCamp#8004]
https://www.freecodecamp.com/parabolt

I just changed my Twitter ID and would like my FCC profile to reflect this change as well. But there seems to be no way at the moment to do that.

**Comment by AkiraLaine** [comment]
FCC reflects changes from your GitHub profile only. if you want to change your name, for example, then you will need to change it on GitHub and then update your FCC profile from the settings page.

**Comment by AkiraLaine** [comment]
@ParaBolt would like to change the URL of his Twitter icon, but there seems to be no way do doing that.

**Comment by atjonathan** [comment]
@AkiraLaine @ParaBolt, this can be closed. We have removed twitter authentication.

**Comment by ParaBolt** [comment]
@atjonathan @BerkeleyTrue @erictleung @BerkeleyTrue @AkiraLaine 

![image](https://cloud.githubusercontent.com/assets/12890542/16018858/f68b61b2-31c3-11e6-9cd2-f9abf2c1ad1f.png)

This is what I mean. That's the URL I want to change. It reflects an old URL. Anyone clicking on that will get a 404, unless that username gets taken by someone else, in which case it will reflect the wrong person's profile.

**Comment by BerkeleyTrue** [comment]
@ParaBolt Please contact me at berkeley@freecodecamp.com or send me a PM on gitter and I'll fix your profile.
