### ISSUE TITLE
pink-text css class created but tests is unsuccessful

### ISSUE THREAD

**Issue by redrexdas** [FreeCodeCamp/FreeCodeCamp#8005]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20.pink-text%0A%20%20%7B%0A%20%20%20%20color%3Apink%0A%20%20%7D%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .pink-text
  {
    color:pink
  }
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by BerkeleyTrue** [comment]
Seems like the test is acting weird if the semicolon after the `pink` is missing. Not sure why this is happening though.

**Comment by erictleung** [comment]
@redrexdas @BerkeleyTrue it appears the regex requires the semi-colon.

```
/\\.pink-text\\s*\\{\\s*color\\s*:\\s*pink\\s*;\\s*\\}/g
```

**Comment by sludge256** [comment]
While it's not necessary in this case, is it something we want to enforce, or should we modify the regex?

**Comment by BerkeleyTrue** [comment]
@sludge256 Is correct, we should enforce the semicolons.

Happy Coding
