### ISSUE TITLE
JavaScript needs S capitalized

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8007]
Challenge [Iterate Through an Array with a For Loop](https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

First sentence needs "Javascript" changed to "JavaScript". [This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/09191454377f9f3baa8f6d25c9930e86619c3d9b/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4737) needs to be changed.

> A common task in **Javascript** is to iterate through the contents of an array. ...

**Comment by josectello** [comment]
@erictleung Submitted a PR.
