### ISSUE TITLE
Editor says there is no closing </p> tag, yet there is one!

### ISSUE THREAD

**Issue by shanemarvinmay** [FreeCodeCamp/freecodecamp#801]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Here is my code:
```html
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<a href='http://www.catphotoapp.com'>cat photos</a>

<img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>

<p class='red-text'> <a href='http://www.catphotoapp.com'>click here for</a>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p> <------------- (and here is my closing </p> tag)
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
Edit(@berkeleyTrue): Added back ticks

**Comment by terakilobyte** [comment]
Can you surround the code you put in with three backticks on a newline above and below? the ` character, right below escape

**Comment by BerkeleyTrue** [comment]
@shanemarvinmay Please add back ticks to your code or else we cannot see your code. Please read https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks for more details.

**Comment by BerkeleyTrue** [comment]
@shanemarvinmay Looks like this is not an issue with the test. You are close to a solution but no quite there yet. Try asking [slack channel](http://freecodecamp.slack.com/messages/help) for help.
