### ISSUE TITLE
Record Collection Exercise

### ISSUE THREAD

**Issue by pesokot** [FreeCodeCamp/FreeCodeCamp#8011]
#### Record Collection

https://www.freecodecamp.com/challenges/record-collection
#### Issue Description

It seems that I have a bug with parsing second and third tests. After testing in IDE, track so not added, but system still throughs error.

#### Browser Information

* Google Chrome, 49.0.2623.110 m 
* Windows 8.1
* Desktop

#### Your Code

```js
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  
  if(value !== "" && prop !== 'tracks'){
    
    collection[id][prop] = value;
  } else if(value !== "" && prop === 'tracks'){
    
    collection[id][prop].push(value);
  }
  console.log(collection[id][prop]);
  return collection;
  
}

// Alter values below to test your code
updateRecords(2548, "tracks", "");

```

The result of the current test is:
![image](https://cloud.githubusercontent.com/assets/8618068/14402910/e3fa79d4-fe42-11e5-80eb-174003d39ab5.png)

however, I still have these errors:
![image](https://cloud.githubusercontent.com/assets/8618068/14402903/ac2942ba-fe42-11e5-939f-0118ebca3b3d.png)

**Comment by BKinahan** [comment]
From the instructions: 
> If `value` is blank, delete that `prop`.

Your code does not delete the `"tracks"` property of record with ID `2548` for the test case you reference; in fact it does nothing to the data in the case where `value == ""`

The correct output for this test case for this record is
```js
"2548": {
"album": "Slippery When Wet",
"artist": "Bon Jovi"
}
```
without any `"tracks"` property.

If you get stuck with a challenge, please ask for assistance in the [help chat](https://gitter.im/FreeCodeCamp/Help) before reporting a bug. In this case there is no bug.

Happy coding!

**Comment by pesokot** [comment]
Thanks a lot!

**Comment by erictleung** [comment]
Closing as it looks like the issue was resolved. Happy coding!
