### ISSUE TITLE
Test case breaks own rules.

### ISSUE THREAD

**Issue by JamieSK** [FreeCodeCamp/FreeCodeCamp#8012]
Challenge [Sum All Primes](https://www.freecodecamp.com/challenges/sum-all-primes#?solution=function%20sumPrimes(num)%20%7B%0A%20%20%0A%20%20var%20total%20%3D%200%3B%0A%20%20%0A%20%20if%20(num%20%3C%202)%20%7B%0A%20%20%20%20return%200%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20for%20(var%20i%20%3D%202%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20var%20prime%20%3D%20true%3B%0A%20%20%20%20%20%20loop%3A%0A%20%20%20%20%20%20for%20(var%20j%20%3D%202%3B%20j%20%3C%3D%20i%2F2%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if%20(i%20%25%20j%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%20%20prime%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%20break%20loop%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if%20(prime)%20%7B%0A%20%20%20%20%20%20%20%20console.log(%22i%20%3D%20%22%20%2B%20i)%3B%0A%20%20%20%20%20%20%20%20total%20%2B%3D%20i%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20total%3B%0A%7D%0A%0AsumPrimes(977)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sumPrimes(num) {
  
  var total = 0;
  
  if (num < 2) {
    return 0;
  } else {
    for (var i = 2; i <= num; i++){
      var prime = true;
      loop:
      for (var j = 2; j <= i/2; j++) {
        if (i % j === 0) {
          prime = false;
          break loop;
        }
      }
      if (prime) {
        console.log("i = " + i);
        total += i;
      }
    }
  }
  
  return total;
}

sumPrimes(977);

```

The challenge says itself, "The provided number may not be a prime." and yet one of the test cases provides a prime.

Also my code is horribly inefficient but that's not really freeCodeCamp's fault.

**Comment by erictleung** [comment]
@JamieSK I don't think the tests break anything. It says "The provided number **may not** be a prime." This suggests that you may or may not assume the number you get is a prime number. Happy coding!

**Comment by JamieSK** [comment]
Oh I see how it was meant now, I read it to mean "it may not be" as in is not allowed to be, that's fine anyways. Thanks!
