### ISSUE TITLE
Correct Answer not Recognized

### ISSUE THREAD

**Issue by amolinasf** [FreeCodeCamp/FreeCodeCamp#8013]
![screen shot 2016-04-09 at 4 46 02 pm](https://cloud.githubusercontent.com/assets/16341561/14404303/a27cd968-fe72-11e5-8809-9baeeaac19b7.png)
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20testArr.push(item)%3B%0A%20%20var%20removed%20%3D%20testArr.shift(arr)%3B%0A%20%20return%20removed%3B%0A%20%20%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.

It appears that the array is modified correctly and the correct value is returned, yet the third success requirement is not satisfied.

My code:
```javascript
function nextInLine(arr, item) {
  // Your code here
  testArr.push(item);
  var removed = testArr.shift(arr);
  return removed;
    // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by erictleung** [comment]
@amolinasf Hint: I would double check what arrays you are modifying in your function. In general, code issues are not handled on GitHub unless there is a bug with the site. Please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by nextasy2010** [comment]
Hi, did you resolve this? Im getting the same error.

function nextInLine(arr, item) {
  var addNum= testArr.push(item);
  var removeNum= testArr.shift();// Your code here
  
  return removeNum;  // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

**Comment by amolinasf** [comment]
I did manage to resolve it, I cant remember off the top of my head how i
did it exactly.

-AM

**Comment by nextasy2010** [comment]
Solved it. Dont use testArr use arr

**Comment by nextasy2010** [comment]
Apparently you need to use arr instead of testArr

**Comment by alexstelmakh** [comment]
Help! I have a similar problem. This is my code : `function nextInLine(arr, item) {
  // Your code here
  arr.push(6);
  return item = arr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
`

**Comment by nextasy2010** [comment]
Apparently you need to use arr instead of testArr

**Comment by mony224461** [comment]
function nextInLine(arr, item) {
  // Your code here
arr.push(item);
return item = arr.shift();
 // return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 4)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

**Comment by mony224461** [comment]
Hi, 
The below code work for all

**Comment by mony224461** [comment]
function nextInLine(arr, item) {
  // Your code here
arr.push(item);
return item = arr.shift();
 // return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 4)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

**Comment by nehaniphadkar** [comment]
[
function nextInLine(arr, item) {
  // Your code here
  arr.push(item);
  return arr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];
// Display Code
//testArr=[5,6,7,8,9];
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));](url)
