### ISSUE TITLE
When you click on the code ide it changes lines

### ISSUE THREAD

**Issue by Nojil** [FreeCodeCamp/FreeCodeCamp#8014]
#### Issue Description

When ever i click on the ide within all challenges for the first time it will show the blinking " | " however when i start to type for click tab ora nything it will move the the next line.

#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Mac El Capitan v10.11.3
* Mobile, Desktop, or Tablet: Mac Book Pro

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by smlabt** [comment]
Already reported in #7847

**Comment by Nojil** [comment]
@smlabt awesome I didn't see that thank you

**Comment by erictleung** [comment]
Closing because duplicate issue. Happy coding!
