### ISSUE TITLE
Night Mode: HR elements should be lighter so as to be visible

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8016]
The HR color should probably match the color of night mode text.

![](https://www.evernote.com/l/Ar_z_bg3LChMXZ-YDuiXPNUIIKQAES91E6AB/image.png)

**Comment by josectello** [comment]
@QuincyLarson Would you have any advice on how one could get started tackling something like this?

**Comment by tehkaiyu** [comment]
You can add a `hr` class nested within the `.night` class of `main.less` file

**Comment by QuincyLarson** [comment]
@benmcmahon100 @hallaathrad

**Comment by hallaathrad** [comment]
done :) merge at will

**Comment by erictleung** [comment]
@hallaathrad I think your PR #8056 was trying going to close this but missed the keywords in the commit message. Good to close?

**Comment by raisedadead** [comment]
Yeah this is good to close.
