### ISSUE TITLE
Curser placement is weird

### ISSUE THREAD

**Issue by bymusicayelive** [FreeCodeCamp/FreeCodeCamp#8019]
#### Challenge Name

All of them.

#### Issue Description

Whenever I start a new challenge and try to place my curser in the code to start editing it, my curser won't go to or move to where I need it to go. I can place my curser somewhere near where I need it and try to arrow over to where I need it to go, but it gets stuck. Also if I put my cursor on a blank line between lines of code where I want to add a line of code, it'll start typing somewhere in the middle of a whole other line. Once I've started editing the code (in the wrong place originally since I can't get to the right place), THEN it will allow me to put my cursor anywhere I need it. It's just annoying.

#### Browser Information

* Browser Name, Version: Chrome 49.0.2623.110 (64-bit)
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by smlabt** [comment]
Already reported in #7847

**Comment by erictleung** [comment]
Closing because it is a duplicate issue. Happy coding!
