### ISSUE TITLE
Says there is no </p> tag, yet there is one!

### ISSUE THREAD

**Issue by shanemarvinmay** [FreeCodeCamp/freecodecamp#802]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

here is my code:

**Comment by terakilobyte** [comment]
Closing this as a duplicate of #801, please comment in that issue thread. Thanks!
