### ISSUE TITLE
The wording of the 4th goal in the change the font size of an element is misleading.

### ISSUE THREAD

**Issue by sjames1958gm** [FreeCodeCamp/FreeCodeCamp#8020]
Challenge [Change the Font Size of an Element]

**Do not add a class attribute to the second p element, without removing it from the first one**

Countless members in chat read this as moving the class attribute from one <p> to the other. Just drop the second phrase starting with ", without".

**Comment by sludge256** [comment]
Closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7546. We had a PR for this issue but it has gone stale.
