### ISSUE TITLE
don't know what is wrong?

### ISSUE THREAD

**Issue by neelshah22** [FreeCodeCamp/FreeCodeCamp#8023]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=var%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20%2B%2BmyVar%20%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = 87;

// Only change code below this line
myVar = ++myVar ;


```

**Comment by mitziw** [comment]
me too
![image](https://cloud.githubusercontent.com/assets/10342643/14588975/1011da40-04a5-11e6-960d-c2e9df8ef84b.png)

**Comment by theflametrooper** [comment]
@mitziw You're code is incorrect. The correct solution is `myVar++;`. In future, please ask for challenge related help in the chat rooms.

**Comment by mitziw** [comment]
@theflametrooper No, that is not the issue and that is also incorrect. In the future, if you can't help, don't respond. thanks.
