### ISSUE TITLE
Objective met but unable to proceed

### ISSUE THREAD

**Issue by seancyw** [FreeCodeCamp/FreeCodeCamp#8028]
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=function%20unite(arr1%2C%20arr2%2C%20arr3)%20%7B%0A%20%20%0A%20%20var%20array%20%3D%20arr1%3B%0A%20%20%0A%20%20for(%20var%20i%20%3D%201%3B%20i%20%3C%20arguments.length%3B%20i%2B%2B%20)%20%7B%0A%20%20%20%20%0A%20%20%20%20for(var%20j%20%3D%200%3B%20j%20%3C%20arguments%5Bi%5D.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if(array.indexOf(arguments%5Bi%5D%5Bj%5D)%20%3C%200)%20%7B%0A%20%20%20%20%20%20%20%20array.push(arguments%5Bi%5D%5Bj%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20array%3B%0A%7D%0A%0Aunite(%5B1%2C%203%2C%202%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2703.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function unite(arr1, arr2, arr3) {
  
  var array = arr1;
  
  for( var i = 1; i < arguments.length; i++ ) {
    
    for(var j = 0; j < arguments[i].length; j++) {
      if(array.indexOf(arguments[i][j]) < 0) {
        array.push(arguments[i][j]);
      }
    }
  }
  
  return array;
}

unite([1, 3, 2], [5, 2, 1, 4], [2, 1]);

```

**Comment by erictleung** [comment]
@seancyw we have recently been updating certain function names and the change is slowly propagating. Change your function `unite` to `uniteUnique ` and your code should work. If you notice this inconsistency in the future, you can click on the "Reset" button and it should pre-populate the editor with the correct code. Happy coding!
