### ISSUE TITLE
My placeholder is correct but the editor still says its wrong!

### ISSUE THREAD

**Issue by shanemarvinmay** [FreeCodeCamp/freecodecamp#803]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p>Click here for <a href='#'>cat photos</a>.</p>

<a href='#'><img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type='text'>
<input type='text' placeholder='cat photo URL'>

**Comment by shanemarvinmay** [comment]
<input type='text'>
<input type='text' placeholder='cat photo URL'>

**Comment by shanemarvinmay** [comment]
The input code won't show up here!

**Comment by BerkeleyTrue** [comment]
Hey @shanemarvinmay,

Try modifying the input tag instead of adding an additional input tag. That should fix you issue.
