### ISSUE TITLE
Footer on sample page

### ISSUE THREAD

**Issue by ibbad** [FreeCodeCamp/FreeCodeCamp#8030]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In footer at the give sample page [http://codepen.io/hallaathrad/full/vNEPpL], "All Rights **Reversed**" should be "All Rights **Reserved**."

**Comment by erictleung** [comment]
@ibbad I believe this is intentional because @hallaathrad wants people to use his portfolio as a goal for your portfolio page. Thus, he is encouraging you to copy his site. Here you can read more about [All Rights **Reversed**](https://en.wikipedia.org/wiki/All_rights_reversed).

**Comment by hallaathrad** [comment]
True true @erictleung :) copyleft! Knowledge should be freely available to all and any interested. Thanks for trying to help, @ibbad.

No issues here.
