### ISSUE TITLE
Build a Tribute Page Project - Reduce ambiguity of goals

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#8036]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.

Some campers are confused if they are allowed to use their own CSS or alternate frameworks.  Additionally, we want to make sure that students don't directly replicate the existing tribute page - even if they did it using their own code, it makes it very difficult to distinguish from cheating.

Add the following rules:
> **Rule #3:** You may use your own CSS and frameworks other than Bootstrap
> **Rule #4:**  Choose your own tribute subject

**Comment by josectello** [comment]
I'll gladly give this a shot. :)
