### ISSUE TITLE
Transition all vimeo videos over to youtube

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8039]
We are moving from Vimeo to Youtube and focusing our efforts on promoting our YouTube channel (which provides better auto-subtitles than Vimeo). I am in the process of doing this now.

**Comment by sanspace** [comment]
Is there anything we can help with?

**Comment by raisedadead** [comment]
@sanspace We would mostly move the videos from the FCC's Vimeo account to the [youtube channel](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ). Please pitch on any of the help wanted issues. Contributions are welcome on those 😉 !

**Comment by Pankwood** [comment]
I am looking for my **first ** challenge in FCC. Can I help you in anything?

**Comment by theflametrooper** [comment]
@Pankwood Maybe you should check the `easy` and `help wanted` labels. This issue doesn't really need help as it'll be done on quincys end. Have fun!
