### ISSUE TITLE
Used the class .grey-background, and the background is grey, yet the editor isn't picking up on that!

### ISSUE THREAD

**Issue by shanemarvinmay** [FreeCodeCamp/freecodecamp#804]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

```html
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
  
  .grey-background {
    background-color:grey;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p>Click here for <a href='#'>cat photos</a>.</p>

<a href='#'><img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/></a>

<div class="grey-background">
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="/submit-cat-photo">
  <label><input type='radio' name='indoor-outdoor' checked> Indoor</label>
  <label><input type='radio' name='indoor-outdoor'> Outdoor</label>
  <br>
  <label><input type='checkbox' name='personality' checked> Loving</label>
  <label><input type='checkbox' name='personality'> Lazy</label>
  <label><input type='checkbox' name='personality'> Energetic</label>
  <br>
  <input type='text' placeholder='cat photo URL' required>
  <button type='submit'>Submit</button>
</form>
```
edit(@berkeleytrue): added back ticks

**Comment by shanemarvinmay** [comment]
The styles added to the page can't be show here.

**Comment by Harshdand** [comment]
Its a small mistake you did the class name is gray-background not grey-background

**Comment by shanemarvinmay** [comment]
Oh okay. Thank you for letting me know.

To God be the glory,
Shane May

**Comment by BerkeleyTrue** [comment]
@shanemarvinmay Does that fix your issue?

**Comment by BerkeleyTrue** [comment]
@shanemarvinmay Looks like @Harshdand Is correct. Please use [the Slack Channel](http://freecodecamp.slack.com/messages/help) when you get stuck before reporting an issue.

Good luck with the rest of the challenges!

**Comment by andyeff** [comment]
I know this is a closed issue, but is it much effort to make the waypoint also accept grey as well as gray? Grey is the traditional spelling for a Brit and as far as I know, the HTML spec supports it being spelt as grey too.

**Comment by JimC86** [comment]
THANK YOU SO MUCH, I looked everywhere, and could NOT figure out the deal... In my case, I figured out to put the .gray-background part under the style tag, but I didn't know to ONLY put class="gray-background" in my opening div tag, and viola

**Comment by AsrielBekere** [comment]
I'd tried a lot, not working

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
   .gray-background {
    background-color:gray;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<div class"gray-background">
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
