### ISSUE TITLE
Double/Single Quotation Introduces fun text in simulated window

### ISSUE THREAD

**Issue by meiotta** [FreeCodeCamp/FreeCodeCamp#8042]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text'%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
</style>
<h1 class="pink-text'>Hello World!</h1>
![objectproperties](https://cloud.githubusercontent.com/assets/18387106/14416705/c8d3f5fa-ff72-11e5-9cf9-7706b0e4d7b2.PNG)

```

**Comment by erictleung** [comment]
@meiotta thanks for the issue but I don't think this is a "bug" per se. I believe it is just the editor indicating there is something wrong with your code. In this case, you can't have mismatching quote types in your `<h1>` element. Happy coding!

**Comment by meiotta** [comment]
Oh, I just figured it wasn't meant to display the .. underlying app source like that.
