### ISSUE TITLE
Add Test to Comment out HTML

### ISSUE THREAD

**Issue by webgoto** [FreeCodeCamp/FreeCodeCamp#8046]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--
<h1>Hello World</h1>
<p>Hello Paragraph</p>
-->

<h2>CatPhotoApp</h2>
```

**Comment by raisedadead** [comment]
This is interesting. :smile: while you have valid code here, I am afraid, you did move the `<p>` to get the job done in a single comment.

The tests are expecting two comments and hence fail.

So, I feel we should add a test that checks the order of the elements are correct, and people are not intentionally moving the elements around to pass this.

The aim of the challenge is to showcase comments and HTML can be anywhere.

#### To Contributors:

Add a test that checks:
> Do not change the order of the `<h1>`, `<h2>` or `<p>` in the code.

**Comment by dwd2010** [comment]
few mins ago, I did test it. I passed this challenge.  So this issue dont have a problem... @raisedadead

**Comment by raisedadead** [comment]
@dwd2010 Do you mean with the exact same code as mentioned in the issue description?
It doesn't pass.

**Comment by dwd2010** [comment]
@raisedadead Right, he not suppose to move code around. that is how it got wrong answer.

well, my correct answer is:
```
<!--
<h1>Hello World</h1>
-->
<h2>CatPhotoApp</h2>
<!--
<p>Hello Paragraph</p>
-->
```

**Comment by webgoto** [comment]
>Be sure to close each of your comments with -->.

I was not able to understand the meaning of this part.
Thank you.

**Comment by raisedadead** [comment]
@dwd2010 This challenge still needs the fix. I am updating the title. Any reason you closed this?

**Comment by dwd2010** [comment]
@raisedadead, i closed this because this one dont have a issue. since there have a answer.

**Comment by raisedadead** [comment]
@dwd2010 :
refer comment:

Add a test that checks:
> Do not change the order of the `<h1>`, `<h2>` or `<p>` in the code.

**Comment by dwd2010** [comment]
but I already give you answer.  I didnt change that order.  that answer is correct for pass the challenge
@raisedadead

**Comment by raisedadead** [comment]
Okay, so there is some confusion that needs to be cleared:

1. The campers code is incorrect but still VALID code.
2. The tests are looking for two comments and not one.
3. This leads to a confusion, why the test fails with the below code:
```
<!--
<h1>Hello World</h1>
<p>Hello Paragraph</p>
-->

<h2>CatPhotoApp</h2>
```
4. The below code would pass (again its not correct but Valid):
```
<!--
<h1>Hello World</h1>
-->
<--
<p>Hello Paragraph</p>
-->

<h2>CatPhotoApp</h2>
```

So we need to add a test that checks the order of the tags, this will avoid the confusion:
Add a test that checks:

> Do not change the order of the `<h1>`, `<h2>`or `<p>` in the code.

**Comment by dwd2010** [comment]
@webgoto

**Comment by webgoto** [comment]
If the test can check the order of the elements.

>Be sure to close each of your comments with -->.

This test is not necessary?

**Comment by raisedadead** [comment]
@webgoto that test is still required

**Comment by webgoto** [comment]
@raisedadead I see.

**Comment by ryanjohnston** [comment]
I am working on this.

**Comment by ryanjohnston** [comment]
I have submitted a possible solution for this.

**Comment by velvetstar** [comment]
I am trying to submit my answer:

<h2>CatPhotoApp</h2>


and it will not accept it. It won't pass the "Do not change the order of the h1 h2 or p in the code" test. Isn't that in order?!!
