### ISSUE TITLE
Record Collection

### ISSUE THREAD

**Issue by realMin** [FreeCodeCamp/FreeCodeCamp#8047]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%204%3B%20i%2B%2B)%7B%0A%20%20%20%20if(id%20%3D%3D%20collection%5Bi%5D)%7B%0A%20%20%20%20%20%20if(value%20!%3D%3D%20%22%22%20%26%26%20(prop%20!%3D%3D%20collection%5Bi%5D.tracks%5B0%5D%20%7C%7C%20prop%20!%3D%3D%20collection%5Bi%5D.tracks%5B1%5D))%7B%0A%20%20%20%20%20%20%20%20prop%20%3D%20value%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if(value%20!%3D%3D%20%22%22%20%26%26%20(prop%20%3D%3D%20collection%5Bi%5D.tracks%5B0%5D%20%7C%7C%20prop%20%3D%3D%20collection%5Bi%5D.tracks%5B1%5D))%7B%0A%20%20%20%20%20%20%20%20collection%5Bi%5D.tracks.push(%5Bvalue%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if(value%20%3D%3D%3D%20%22%22)%7B%0A%20%20%20%20%20%20%20%20prop.delete()%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  for(var i = 0; i < 4; i++){
    if(id == collection[i]){
      if(value !== "" && (prop !== collection[i].tracks[0] || prop !== collection[i].tracks[1])){
        prop = value;
      }
      if(value !== "" && (prop == collection[i].tracks[0] || prop == collection[i].tracks[1])){
        collection[i].tracks.push([value]);
      }
      if(value === ""){
        prop.delete();
      }
    }
  }
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by raisedadead** [comment]
> Please describe how to reproduce this issue, and include links to screenshots if possible.

Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by revisualize** [comment]
@realMin I regret to inform you that this is not an issue with the website. Your code isn't correct to complete the solution.
I recommend that you seek assistance in the https://gitter.im/FreeCodeCamp/HelpJavaScript chatroom.

**Comment by raisedadead** [comment]
Closing with no updates.
