### ISSUE TITLE
Cheating to pass challenges

### ISSUE THREAD

**Issue by shortgiraffe4** [FreeCodeCamp/FreeCodeCamp#8048]
#### Challenge Name
https://www.freecodecamp.com/challenges/no-repeats-please

#### Issue Description

I think it is just a particular example of this kind of bugs. I don't know whether there's a way to prevent it but this is how I can cheat to pass this challenge:
```
function permAlone(str) {
  switch(str){
    case "aab": 
      return 2;
    case "aaa":
      return 0;
    case "aabb":
      return 8;
    case "abcdefa":
      return 3600;
    case "abfdefa":
      return 2640;
    case "zzzzzzzz":
      return 0;
  }
}

permAlone('aab');
```
Apparently, if I have all the test cases, in many circumstances(challenges), I can possibly return valid result for every test case.

#### Browser Information

* Mozilla Firefox, Version: 45.0.1
* Operating System: Windows 10
* Desktop

**Comment by erictleung** [comment]
@shortgiraffe4 I think @SaintPeter has commented on this before in that I don't think we can prevent people from doing this. In addition, someone brought up hiding some of the tests so people can't do this (#7990). @BerkeleyTrue gives a response of:

> While those improvements can help prevent this kind of cheating, we always have worked on the assumption that we won't be able to stop all cheaters and instead we should focus on curriculum and the experience.

Even so, your coding solutions will be saved in your profile so employers or others can see your work.

**Comment by shortgiraffe4** [comment]
@erictleung: Yeah, it's probably true. Thank you for letting me know.
