### ISSUE TITLE
Tests for Waypoint: Add Borders Around Your Elements don't check for green border color

### ISSUE THREAD

**Issue by veerhoff** [FreeCodeCamp/freecodecamp#805]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

There doesn't appear to be any tests for the green border color requirement. I passed the waypoint before adding 'border-color: green;' to my '.thick-green-border' class

**Comment by BerkeleyTrue** [comment]
Hey @veerhoff,

Thanks for letting us know!

**Comment by BerkeleyTrue** [comment]
fix should be up soon

**Comment by veerhoff** [comment]
Glad to help! FreeCodeCamp has been the best online resource I've found for
all-inclusive browser-based web development education. Keep it up!

**Comment by BerkeleyTrue** [comment]
Woot!
