### ISSUE TITLE
Everything Be True bonfire function name incorrect

### ISSUE THREAD

**Issue by megnotarte** [FreeCodeCamp/FreeCodeCamp#8051]
Challenge [Everything Be True](https://www.freecodecamp.com/challenges/everything-be-true#?solution=function%20truthCheck(collection%2C%20pre)%20%7B%0A%20%20%2F%2F%20Is%20everyone%20being%20true%3F%0A%20%20var%20blnTrue%3Dtrue%3B%0A%20%20%0A%20%20collection.forEach(function(item)%0A%20%20%20%20%20%20%7B%0A%20%20%20%20console.log(item)%3B%0A%20%20%20%20if%20(item.hasOwnProperty(pre)%20%26%26%20Boolean(item%5Bpre%5D))%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%2F%2F%20console.log(true)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%2F%2F%20console.log(false)%3B%0A%20%20%20%20%20%20blnTrue%20%3D%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D)%3B%0A%20%20%0A%20%20console.log(blnTrue)%3B%0A%20%20return%20blnTrue%3B%0A%7D%0A%0AtruthCheck(%5B%7B%22name%22%3A%20%22Pete%22%2C%20%22onBoat%22%3A%20true%7D%2C%20%7B%22name%22%3A%20%22Repeat%22%2C%20%22onBoat%22%3A%20true%7D%2C%20%7B%22name%22%3A%20%22FastFoward%22%2C%20%22onBoat%22%3A%20null%7D%5D%2C%20%22onBoat%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.

The tests are calling a function called `truthCheck`, but the code populates a function called `every`. Until you change the function name to match the test, the tests will always fail. This might be an intentional speed bump, but I can't tell, and it's super confusing when the tests have matched the provided function name up until this point.

**Comment by BerkeleyTrue** [comment]
Hello @megnotarte, thanks for reporting.

I can't replicate the issue. If you hit the reset button, it populates with the correctly named function. Can you elaborate?

**Comment by megnotarte** [comment]
@BerkeleyTrue Checking again, since I had loaded the bonfire and worked on it over the course of a few days. I don't see the issue anymore. Closing this!

**Comment by davelane** [comment]
Actually I had this problem too. The function in the console was called "every" which was not being called. I had to change it to truthCheck by hand.
