### ISSUE TITLE
Challenge asks for "color" instead of "background-color" (which is what the challenge validates for)

### ISSUE THREAD

**Issue by feiyun0112** [FreeCodeCamp/FreeCodeCamp#8069]
#### Challenge Name
Use Hex Code to Color Elements Red

https://www.freecodecamp.com/challenges/use-hex-code-to-color-elements-red

#### Issue Description

**Use the hex code for the color red instead of the word red. For example body { color: #FF0000; }
**
but right code is
`<style>
  body {
    background-color: #FF0000;
  }
</style>
`

**Comment by akkatracker** [comment]
I think it's just demonstrating what sort of form to put the colour in. 

If it gave you the right code there wouldn't be much point in the challenge - it doesn't get you to think.

**Comment by erictleung** [comment]
I agree with @akkatracker. The tests doesn't ask for "color" because it says "**For example** `body`...". It was only used an example to help people out on what we mean. Sorry for any confusion but this isn't a bug with the site. Happy coding!
