### ISSUE TITLE
Bug image responsive

### ISSUE THREAD

**Issue by MrAndrewPeterson** [FreeCodeCamp/freecodecamp#807]
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to r
![image](https://cloud.githubusercontent.com/assets/10198376/7944999/e091e040-0922-11e5-9654-2803571827bf.png)
eproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
@MrAndrewPeterson Can you give us more information on what the bug is and how to reproduce it?

**Comment by BerkeleyTrue** [comment]
@MrAndrewPeterson Looks like this is not an issue with the test. You are super close to a solution. Try asking [The Slack channel](http://freecodecamp.slack.com/messages/help) for help when you get stuck.

Good luck!
