### ISSUE TITLE
ARMAN

### ISSUE THREAD

**Issue by SOHAIL14** [FreeCodeCamp/FreeCodeCamp#8070]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3EHello%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello</h1>

```

**Comment by SOHAIL14** [comment]
HOW I START LEARNING ABOUT HTML

**Comment by AkiraLaine** [comment]
Hey! If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is for issues only. Happy Coding :smile:
