### ISSUE TITLE
 Change Text Inside an Element Using jQuery-"Italicize the text in your target4 button by adding HTML tags."

### ISSUE THREAD

**Issue by chandramaniadil** [FreeCodeCamp/FreeCodeCamp#8071]
Challenge [Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery)
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.

My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<i>#target4</i>")
    
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
Even though the code is correct ,the solution has not been accepted as correct.

**Comment by koyels** [comment]
+1

**Comment by PhilipWoulfe** [comment]
Should you use <em> instead of <i>?

**Comment by chandramaniadil** [comment]
yes it works with <em> in place of <i> @PhilipWoulfe

**Comment by erictleung** [comment]
@chandramaniadil thanks for the issue. We recently changed this from accepting `<i>` to accepting `<em>` (#5425 and #7939). [One reason](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5425#issuecomment-178426739) is that we eventually agreed the `i` tags are outdated to truly emphasize a text. HTML should be about content, while CSS should be used to style the text. Thus, the `i` tag, which just styles the text is against what HTML and CSS are about. I hope you can understand. Closing as this change was on purpose. Happy coding!

**Comment by chandramaniadil** [comment]
I agree with you ! @erictleung 
role of '<i>' has now changed ,so use of '<em>' is preferable..

**Comment by shakirul15-311** [comment]
# **Correct answer:**

 $("#target4").html("<em>#target4</em>")

**Comment by texas2010** [comment]
@shakirul15-311 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by aj141** [comment]
use <em> instead of <i>

**Comment by harunugur4** [comment]
`change  $("#target4").html("<i>#target4</i>") to  $("#target4").html("<em>#target4</em>")`

**Comment by ratansingh98** [comment]
try
``  $("#target4").html("<i><em>#target4</em></i>");``
