### ISSUE TITLE
Use Conditional Logic with If Statements - complete without if-else

### ISSUE THREAD

**Issue by PhilipWoulfe** [FreeCodeCamp/FreeCodeCamp#8074]
#### Challenge Name

Use Conditional Logic with If Statements

#### Issue Description

Not really a bug, however you can complete the challenge without using if-else. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// Setup
function trueOrFalse(wasThatTrue) {
  
  // Only change code below this line.
  var result = "That was ";
  return result += wasThatTrue;

  // Only change code above this line.

}

```

**Comment by erictleung** [comment]
@PhilipWoulfe mmm good point. This challenge needs a simple test to check for the use of an `if` statement.

**Comment by josectello** [comment]
@erictleung I'll start working on this if no one else is. :)

**Comment by josectello** [comment]
I've been looking into how to go about testing to see if an `if` statement is present within the function, and this is what I've come up with:

*Convert the function to a string and check if the word "if" is present in its contents:*

`var myFunction = function() {
    return 1 + 3;
};

console.log(myFunction.toString()); // convert to string & print output
// this outputs function() { return 1 + 3; }
`

From here it's simple enough to do a `.indexOf()` to check if "if" is present in the stringified function. However, doing this inside an `assert` statement seems very monotonous and messy.

There is also a hole. If the user (for some odd reason) includes a string with the word "if" inside the function, the test will pass regardless of whether or not they *actually* used an if statement.

@erictleung Am I on the right track here or is there more efficient way to test for this? Thanks!

**Comment by erictleung** [comment]
@josectello I was thinking of having a regex look for the canonical forms of the `if` statement:

```
# one kind of if statement
if (...) {
  ...
}

# another kind of if statement
if (...) return ...;
```

You can use the regex: `/if\s*\(.*{?\s*.*\s*}?/g`. You'll need to escape things as necessary if you make the test. I used http://www.regexpal.com/ as an easy way to test the regex.

**Comment by josectello** [comment]
@erictleung Thanks for the regex. That's much easier than parsing it with `indexOf()`. I am curious about escaping some the escape characters within the regex. I've been reading up on it and so far this looks right, it's only Atom that complains about the regex. 

```assert(myFunction(true).toString().search(/if\s*\(.*{?\s*.*\s*}?/g) > -1, 'message: <code>myFunction</code> should use an if statement');```

When I escape the escape characters it breaks the test. Is it fine to have Atom highlight the regex like so?

<img src="http://s21.postimg.org/kposp121j/Screen_Shot_2016_04_12_at_9_44_06_PM.png" />

**Comment by erictleung** [comment]
@josectello that's the escaping I mentioned. Backslashes need to be escaped because of how they are parsed in FCC. So I think the correct regex to be added should be `/if\\s*\\(.*{?\\s*.*\\s*}?/g`. If you were to use the regex in a script in JavaScript, you wouldn't need to double escape backslashes. I hope that helps.

**Comment by BKinahan** [comment]
It seems simpler to have the function output require some other strings not simply differing by ending with "true" or "false". The meaningful difference from the example function is using the past tense, so perhaps something like "Yes, it was true." and "No, it was false."
