### ISSUE TITLE
Palindrome Typo?

### ISSUE THREAD

**Issue by inspiredtolive** [FreeCodeCamp/FreeCodeCamp#8077]
#### Challenge Name
Check for Palindromes

https://www.freecodecamp.com/challenges/check-for-palindromes

#### Issue Description

It says "palindrome("0_0 (: /-\ :) 0-0") should return true." But hyphen and underscore are not the same character so it should return false.

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function palindrome(str) {
  // Good luck!
  var alphaLower = str.toLowerCase().replace(/\W/g, "");
  var reverse = alphaLower.split("");
  reverse.reverse();
  reverse = reverse.join("");
  return reverse === alphaLower;
}

palindrome("eye");
```

#### Screenshot
http://puu.sh/og5BM/7f274f57d7.png

**Comment by alistermada** [comment]
From the instructions:
> You'll need to remove **all non-alphanumeric characters** (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

In other words, the hyphen and underscore are irrelevant to checking for palindromes, just like commas and spaces.

**Comment by sludge256** [comment]
Thanks @alistermada.
@inspiredtolive Please use the chat rooms for code related help.

**Comment by JBuji** [comment]
My solution:
`function palindrome(str) {
  
  str = str.replace(/[^A-Za-z0-9]/g, '');
  
  return str.split('').reverse().join('').toLowerCase() === str.toLowerCase();
 
}

palindrome("0_0 $# ^^ & * ()\"'\"\ __--++  = = + =!``~~  ~`\":'';/?...>>,,<<(: /-\ :) 0-0");
`
