### ISSUE TITLE
Bootstrap css link is not on the tutorial description

### ISSUE THREAD

**Issue by felixcriv** [FreeCodeCamp/freecodecamp#808]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
@felixcriv Thanks for bringing this to our attention. @QuincyLarson is currently auditing the entire curriculum. While there is a link to the bootstrap on the image, we are considering a adding a text link as well. If this works for you please feel free to close this issue.

**Comment by QuincyLarson** [comment]
@felixcriv our goal is to keep campers focused and moving forward. I think unnecessarily sending them to Bootstrap's documentation would be an unnecessary distraction at this step.
