### ISSUE TITLE
Back End Certification - Links and Redirect Issues

### ISSUE THREAD

**Issue by vtange** [FreeCodeCamp/FreeCodeCamp#8080]
#### Challenge Name

https://www.freecodecamp.com/challenges/claim-your-back-end-development-certificate

#### Issue Description

Went through the 5 min-long certification process as normal.

The links to the Plagiarism stuff, etc. do not work (click -> no effect). User gets the certification with no problems, but the site seems to get an issue redirecting the user to the "Computer Basics" video section.

#### Browser Information

Firefox Beta (46.0b1)
Windows 7 x64 Desktop

#### Screenshot
![untitled](https://cloud.githubusercontent.com/assets/4667949/14479531/8c219d8e-00d4-11e6-8d52-53a5e3dee7d1.png)

**Comment by dwd2010** [comment]
@vtange, Have you try to refresh/reload then click that link?

**Comment by vtange** [comment]
Clicking on Computer Basics: The 4.... works normally from when the site failed to redirect. It's overall a really minor issue

**Comment by dwd2010** [comment]
@vtamara, Do you still have this issue?

**Comment by vtange** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4667949/14550518/26ad7076-027e-11e6-8e0b-596210ed2408.png)

The link here and on 3/4 still doesn't do anything.

**Comment by BerkeleyTrue** [comment]
@vtange You'll need to click on the `Go to my next step button`. 

Happy Coding!
