### ISSUE TITLE
Update CONTRIBUTING.md Getting Started guidelines

### ISSUE THREAD

**Issue by KerryKDiehl** [FreeCodeCamp/FreeCodeCamp#8081]
#### Issue Description

The current Getting Started guidelines are great!  The only thing I had to search for was the version of Node being used for the application.  From what I saw in Gitter, any version of Node v5 should work.  Might be helpful to put this into the guidelines as well as a link to a version manager (nvm, n, etc) for any newbies jumping in.

**Comment by pawan92** [comment]
I agree with this. I recently went through the contribution guide pretty easily except for the fact that it turned out i was using an older version of node. Wasn't a big deal but a good idea nonetheless :)

**Comment by raisedadead** [comment]
@KerryKDiehl @pawan92 Thanks for reporting this.

IMHO, we could add the versions for `node` (^4) and `npm` (^2) however, adding anything about the version manager is going to be gnarly with multiple OS types.

For instance I have done installations on OSX, Windows 10, Windows 7, Ubuntu 14 and C9.io and trust me it takes a different workaround for each type for the version manager.

So, I recommend that adding something on the lines of below in the [Prerequisites](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#prerequisites) should be okay:

> - [MongoDB](http://www.mongodb.org/downloads) ~ ^3
> - [Node.js](http://nodejs.org) ^4
> - npm ~ ^2

> _Updating to the latest releases is recomended_.

**Comment by raisedadead** [comment]
FYI, personally for me:
`nvm` is awesome on *UNIX  and `nodist` is awesome on Windows

There are others but these two work best, but IMHO we needn't endorse any in the contribution guidelines. Its really up to the users to choose.
