### ISSUE TITLE
Write Reusable JavaScript with Functions bug

### ISSUE THREAD

**Issue by shanemarvinmay** [FreeCodeCamp/FreeCodeCamp#8083]
The comments tell us to only change code below the function, but to accomplish the challenge I had to change above the second comment.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@shanemarvinmay you shouldn't need to change anything below the second comment to complete the challenge. You are able to complete the challenge by only changing things under the second comment. 
Please ask for help in the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you are still stuck. Happy coding!
