### ISSUE TITLE
Need project for practice

### ISSUE THREAD

**Issue by sunnycal** [FreeCodeCamp/FreeCodeCamp#8085]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by dwd2010** [comment]
@sunnycal, that is not issue. so i have to close this issue.

**Comment by sunnycal** [comment]
How can I begin working on projects

**Comment by dwd2010** [comment]
@sunnycal, You could ask anyone on the [FCC Room](https://gitter.im/FreeCodeCamp/FreeCodeCamp) at the gitter. they would answer your question.
