### ISSUE TITLE
Typo: Leaving out 'the'

### ISSUE THREAD

**Issue by acr187** [FreeCodeCamp/FreeCodeCamp#8086]
#### Challenge Name

https://www.freecodecamp.com/challenges/comparison-with-the-strict-equality-operator

#### Issue Description
The instructions are written without the word 'the' in 2 places it should be used. This format is readable but does not match the way surrounding challenges are written. The current instructions read: 
> "Use strict equality operator in if statement so the function will return "Equal" when val is strictly equal to 7"

I would change this to:
>"Use the strict equality operator in the if statement so the function will return "Equal" when val is strictly equal to 7"

#### Screenshot
![typo](https://cloud.githubusercontent.com/assets/17096026/14484477/2a6869fe-0194-11e6-8988-a2b4b4f4efec.png)

**Comment by Pankwood** [comment]
Is this available? Can I help in anything?

**Comment by raisedadead** [comment]
@Pankwood Thanks there is a PR open for this if you see, its referenced. I encourage you to go the issues section and look for the help wanted  tags.

Reach out to [Help Contributors Room](https://gitter.im/FreeCodeCamp/HelpContributors) for any assistance.
