### ISSUE TITLE
List Users Who Have Earned Certificates

### ISSUE THREAD

**Issue by CEREBR4L** [freeCodeCamp/freeCodeCamp#8087]
#### Addition Suggestion

Add a the option to click into the number of users that have earned certificates on the about page and have listed all users (linked to their profiles). 

So the idea is make the "87 earned" link into a page that lists all 87 people that have earned the certificate. 

Users can then go there, look see who has earned certs easily as well as being able to click into their profile and see what they have done for inspiration or whatever, just seems like that is what it should be doing (I even clicked on the text a few times expecting it to go somewhere)... 

If you want or need anymore info let me know.

#### Screenshot

![screen shot 2016-04-13 at 09 52 19](https://cloud.githubusercontent.com/assets/7153918/14488036/0fa0fe50-015e-11e6-85b8-67a8415e2e6f.png)

**Comment by ChaituVR** [comment]
## That would be awesome ...
