### ISSUE TITLE
Cannon read property length of null

### ISSUE THREAD

**Issue by aileryen** [FreeCodeCamp/freecodecamp#809]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

![image](https://cloud.githubusercontent.com/assets/12404085/7952308/92d026c6-0979-11e5-807b-fdd062458c34.png)

Get that error of cant read length null in prereq. Was the prereq for ensuring you have a closing tag. SOmeone else posted in help on exercise 33 of html/css they had an error with it not reading closing tag as well. But currently stuck.

**Comment by aileryen** [comment]
Seems to be an issue with all of the bootstrap waypoint starting at 11. After that all of the lessons start with this error.

**Comment by BerkeleyTrue** [comment]
@aileryen Thanks for the heads up. We will be using this issue to track all similar issues.

**Comment by AkiraLaine** [comment]
Most of the Bootstrap Waypoints have this error.

**Comment by BerkeleyTrue** [comment]
I can't reproduce on my side.

@aileryen or @AkiraLaine Can you try hitting ctrl(or cmd on osx) + shift + r and let me know if that makes a difference?

cc @QuincyLarson @terakilobyte

**Comment by BerkeleyTrue** [comment]
I am able to replicate

**Comment by AkiraLaine** [comment]
@BerkeleyTrue Doesn't change.

**Comment by nvamsikrishna05** [comment]
@BerkeleyTrue Yes still the same error. even trying the ctrl+shift+r

**Comment by BerkeleyTrue** [comment]
Thanks Yall. Will take a look at the code see if I can spot the error.

**Comment by AkiraLaine** [comment]
This issue seems to be fixed.

**Comment by BerkeleyTrue** [comment]
Fix should be up soon in production. Thanks everyone!
