### ISSUE TITLE
Error section in night mode a bit harder to read

### ISSUE THREAD

**Issue by krua** [FreeCodeCamp/FreeCodeCamp#8090]
#### Issue Description

When I activated night mode and test my solution in one of FCC challenge, error section has a dark green color so its a bit harder to read.

#### Browser Information

* Browser Name, Version: Firefox 45.0 (64bit) and Google Chrome 49.0.2623.112 (64-bit)
* Operating System: Linux mint 17.3
* Mobile, Desktop, or Tablet: Dekstop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![fcc](https://cloud.githubusercontent.com/assets/11352023/14490299/3b3f39a8-019c-11e6-9969-d18a4225719a.png)

**Comment by raisedadead** [comment]
@krua this has been fixed in #8056 and should reflect on the main website very soon,
We request you to bear with us while that happens.

Thanks a lot!

/cc @BerkeleyTrue to release staging to production.
