### ISSUE TITLE
Issues with Night Mode feature for FCC

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#8091]
Some of the issues with the Night Mode

- [x]  **Map Sidebar Pop-up and Close Button**

![image](https://cloud.githubusercontent.com/assets/1884376/14492465/008125d2-019d-11e6-8866-f817b12f951e.png)
![image](https://cloud.githubusercontent.com/assets/1884376/14492477/139981c8-019d-11e6-8f57-8e522c7bd95b.png)

- [ ] **Map Sidebar Toggle Issue**

![image](https://cloud.githubusercontent.com/assets/1884376/14492639/5b2f9f12-019e-11e6-9188-93e2318ff6a8.png)

Note there are two observations : 

1. There is a visible delay in if the map sidebar is already open and we have the main page [challenge area] in focus and toggle the night mode ( <kbd>g</kbd> + <kbd>t</kbd> + <kbd>n</kbd>).
This may or may not be ignored.

2. The second ***buggy*** issue is the one reflected in the screenshot. if the sidebar is in focus then the night mode toggle only changes the sidebar, not the main page [challenge area]

----
Please add more in here or in the comments.

**Comment by benmcmahon100** [comment]
@raisedadead the second issue cannot be fixed as it is an iframe. We would have to change how the map works.

**Comment by hallaathrad** [comment]
The first issue (with the invisible buttons) has already been dealt with at https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8000

@benmcmahon100 what about the toggling inside of the sidebar only? can the global be somehow modified so it's always caught by the main container, and thus alone?

**Comment by raisedadead** [comment]
Tested on `Chrome Version 49.0.2623.112 m on Windows 7`
The buttons are invisible still:

![image](https://files.gitter.im/FreeCodeCamp/CoreTeam/tqRc/blob)

Updated the issue description.

**Comment by MAshrafM** [comment]
on Chrome V. 49.0.2623.112 m on Windows 7
The Buttons has been fixed.
![capture](https://cloud.githubusercontent.com/assets/10391294/14581057/206e01e8-03e2-11e6-908b-fea6fd913050.PNG)

**Comment by raisedadead** [comment]
Wow @hallaathrad did you do some magic?

**Comment by hallaathrad** [comment]
Time is a man's most powerful tool ;)
I'd told you I had fixed this... You of little faith!

**Comment by raisedadead** [comment]
Closing as resolved for first part, second part is a **wont fix**
