### ISSUE TITLE
Chanllenge Drop it I can't submit!

### ISSUE THREAD

**Issue by coloroso** [FreeCodeCamp/FreeCodeCamp#8092]
#### Drop It

####I can't submit the challenge

I got all the correct answers and I didn't get the submit message. Below is my code.

#### Your Code

```js

function drop(arr, func) {
  var i=0;
  while(!func(arr[i])){
    arr.shift();
    if(arr.length===0){
      break;
    }
  }
  return arr;
}
// If relevant, paste all of your challenge code in here

```

**Comment by BKinahan** [comment]
Your code is correct, however your function name is not. The challenge was updated and the correct function name is now `dropElements`. This can be seen by resetting the code; however you can keep your current code and simply update the function name.

**Comment by coloroso** [comment]
Hi thanks I realized after I posted. Now I am getting the same error on chanllenge Steamroller

var ara=[];
function steamrollArray(arr) {
  // I'm a steamroller, baby  
  for(var i=0;i<arr.length;i++){
    if(Array.isArray(arr[i])){      
      steamrollArray(arr[i]);
    }else{
      ara.push(arr[i]);
    }
  }
  return ara;
}

steamrollArray([1, {}, [3, [[4]]]]);



I got all the correct answer but I don get the submit message

**Comment by erictleung** [comment]
@coloroso you have `var ara = []` as a global variable, which will be changed every time your function is invoked. If you are still stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
