### ISSUE TITLE
test message should say "checkboxes" instead of "radio buttons"

### ISSUE THREAD

**Issue by Nbutter** [FreeCodeCamp/freecodecamp#810]
failed test message says 'Give your radio buttons the name attribute of "personality".'

this should say 'Give your checkboxes the name attribute of "personality".'

the instructions for the waypoint:

Add to your form a set of three checkbox elements. Each checkbox should be wrapped within its own label element. All three should share the name attribute of "personality”.

at least one camper was confused by the error message.

Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.
