### ISSUE TITLE
Example codepen link is not functioning. Update the codepen with provided solution.

### ISSUE THREAD

**Issue by arsho** [FreeCodeCamp/FreeCodeCamp#8100]
Challenge [Map Data Across the Globe](https://www.freecodecamp.com/challenges/map-data-across-the-globe) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36</code>.

The example codepen app for this challenge is: https://codepen.io/FreeCodeCamp/full/mVEJag.
This code is returning blank page like this:
![maperror](https://cloud.githubusercontent.com/assets/5465070/14516904/a45e900e-0229-11e6-8587-e30dcd8ac964.png)

The error on console is showing:

> Mixed Content: The page at 'https://s.codepen.io/FreeCodeCamp/fullpage/mVEJag?' was loaded over HTTPS, but requested an insecure script 'http://d3js.org/d3.v3.js'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://s.codepen.io/FreeCodeCamp/fullpage/mVEJag?' was loaded over HTTPS, but requested an insecure script 'http://d3js.org/topojson.v1.min.js'. This request has been blocked; the content must be served over HTTPS.
Uncaught ReferenceError: d3 is not defined

To get off this error I changed the following  
1. d3.js link(http://d3js.org/d3.v3.js) to //cdnjs.cloudflare.com/ajax/libs/d3/3.5.16/d3.min.js
2. Topojson link(http://d3js.org/topojson.v1.min.js) to https://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.20/topojson.min.js

Now it's showing the map data as:
![mapok](https://cloud.githubusercontent.com/assets/5465070/14516986/799e10c8-022a-11e6-9f42-8ca6e197a8aa.png)

I suggest to update d3.js and topjson.js url correctly in codepen example as early as possible.

**Comment by raisedadead** [comment]
Thanks for reporting. Pen Updated. @arsho @erictleung Confirm and close.

**Comment by erictleung** [comment]
@raisedadead works for me. Closing as issue has been fixed.

**Comment by arsho** [comment]
Thank you @erictleung  and @raisedadead. The issue is fixed.
