### ISSUE TITLE
Fix "flashing" effect on page load

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8102]

**Comment by BerkeleyTrue** [comment]
The best approach for this is to move from storing this in localStorage to adding a boolean on the user object so that this setting can be added on server render instead of after page load

**Comment by benmcmahon100** [comment]
@BerkeleyTrue indeed! That can certainly be done!

**Comment by QuincyLarson** [comment]
@benmcmahon100 please fix this as soon as possible. It is affecting every page load and is distracting. It's difficult for us to estimate how this could be negatively impacting session length.

**Comment by bugron** [comment]
This issue seems to be solved. Closing.
