### ISSUE TITLE
Create hotkey legend for /settings page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8104]

**Comment by raisedadead** [comment]
@QuincyLarson We already have this [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/main.js#L620)
```
window.Mousetrap.bind('g n o', () => {
    // Settings
    window.location = '/settings';
  });
```

Is it something different you were looking into?

**Comment by bugron** [comment]
We already have `g n o`. Closing.
