### ISSUE TITLE
Re-style full screen wiki search

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8105]
Here's what it looks like currently:
![image](https://www.evernote.com/l/Ar-vyVOtFThGaKuwzFdZl11vIrHi9DccVnIB/image.png)

**Comment by raisedadead** [comment]
Edited @QuincyLarson 's issue description to render the image else @hallaathrad would be running around in circles :wink:

**Comment by Rafase282** [comment]
Do we want the list of articles to be visible all the time or just to display when the user is actively searching?
