### ISSUE TITLE
Make Wiki Articles crawlable for sitemap

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8106]

**Comment by robeerob** [comment]
A quick google search reveals that this is controlled by the sitewide robots.txt for github.com.

See the answers in [this StackExchange question](http://webapps.stackexchange.com/questions/70595/how-can-i-make-my-github-wiki-crawlable-by-search-engines-robots-txt-seems-to-f).

The only option seem to be to either contact the different search engines and let them know you would like to be indexed, and there is gitbhub API that supports it (see answer #2 in the link above), or contact github and ask them how to proceed.

**Comment by QuincyLarson** [comment]
@robeerob Thanks for looking into this. Our goal is to have the wiki located on FCC itself crawlable (not the wiki located here on GitHub).

**Comment by Rafase282** [comment]
@robeerob please come over to https://github.com/FreeCodeCamp/wiki-generator/issues/14

No one is working on this yet and I'm note sure how to tackle it yet.

**Comment by atjonathan** [comment]
This can be closed because we are moving to using the forum.
