### ISSUE TITLE
Design alternative to wiki dropdown menu

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8107]
With the increasing number of articles in our wiki, this dropdown menu is impractical. It would be much better if it were somehow searchable.

**Comment by DanAdrenaline** [comment]
I would love to get involved in helping to design a more user friendly unified experience for the 3 wiki access locations. Do you already have some ideas or still looking?

**Comment by Rafase282** [comment]
@DanAdrenaline we are open to suggestions. The facelift would be for the [this](https://www.freecodecamp.com/wiki/en/) version of the wiki only.
