### ISSUE TITLE
Individual wiki articles fail to load without trailing slash

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8109]
https://www.freecodecamp.com/wiki/en/python doesn't work but
https://www.freecodecamp.com/wiki/en/python/ does

**Comment by chandramaniadil** [comment]
One possible reason can be that URLs that pointed to files did not include the trailing slash, while URLs that pointed to directories do include the trailing slash. This means that:

http://web.about.com/example/ is a directory, while
http://web.about.com/example is a file
