### ISSUE TITLE
completing the "Add images" waypoint generates a 404 flash box

### ISSUE THREAD

**Issue by siruguri** [FreeCodeCamp/freecodecamp#811]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. 
see screenshot

seems consistent - tried it twice
![screen shot 2015-06-02 at 9 41 06 pm](https://cloud.githubusercontent.com/assets/40653/7952835/b8380176-0970-11e5-9d68-1ebdbd448cb5.png)

**Comment by siruguri** [comment]
could it be because i added a closed `img` tag? (`</img>`)

**Comment by BerkeleyTrue** [comment]
Hey @siruguri 

When you complete a challenge our servers look up the next challenge and redirect you. Seems like we are trying to redirect you to a challenge that doesn't exist.

Try going to the challenge map and finding your next challenge that is uncompleted. Let me know if you can continue from there.

**Comment by Harshdand** [comment]
@BerkeleyTrue I faced a similar kind of issue when I tried to open multiple challenges in different tabs.

**Comment by QuincyLarson** [comment]
Yes - this message appears if you get redirected. This is working as designed. Thank you anyway for submitting this issue.
