### ISSUE TITLE
CSS Style

### ISSUE THREAD

**Issue by Agirl6833** [FreeCodeCamp/FreeCodeCamp#8114]
Code isnt correct to change color for h2

**Comment by dwd2010** [comment]
@Agirl6833, if you need a help with that.  please ask a help at [FCC help room](https://gitter.im/FreeCodeCamp/Help).
if you think it is issue. please explain. thank you.

**Comment by dwd2010** [comment]
@Agirl6833, Do you have a issue on that challenges?

**Comment by theflametrooper** [comment]
@dwd2010 @Agirl6833 I'm closing this  issue, please use the chat rooms for help regarding the challenges!

**Comment by Agirl6833** [comment]
Ok thanks
