### ISSUE TITLE
compiler error on 309

### ISSUE THREAD

**Issue by shirga** [FreeCodeCamp/FreeCodeCamp#8116]
#### Exact Change 309

https://www.freecodecamp.com/challenges/exact-change#?solution=function%20check_closed%28cid%29{%0A%20%20for%28var%20i%3D0%3B%20i%3Ccid.length%3B%20i%2B%2B%29{%0A%20%20%20%20if%20%28cid[i][1]%20!%3D%3D%200%29{%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20}%0A%20%20}%0A%20%20return%20true%3B%0A}%0A%0Afunction%20get_change%28change%2C%20coin%20%2C%20cid%20%29{%0A%20%20if%20%28change%20%3D%3D%20cid%20%29{%0A%20%20%20%20return%20change%3B%0A%20%20}%0A%20%20var%20i%20%3D%20coin%3B%0A%20%20while%28i%20%3C%20cid%29{%0A%20%20%20%20if%20%28i%20%3E%20change%29{%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20}%0A%20%20%20%20i%20%2B%3D%20coin%3B%0A%20%20%20%20return%200.20%20%2B%200.10%3B%0A%20%20}%20%0A%20%20%20%20%0A%20%20return%20i-coin%3B%0A}%0A%0A%0A%0Afunction%20checkCashRegister%28price%2C%20cash%2C%20cid%29%20{%0A%20%20var%20change%20%3D%20%28cash%20-%20price%29%3B%0A%20%20var%20coins%20%3D%20[0.01%2C%200.05%2C%200.1%2C%200.25%2C%201%2C%205%2C%2010%2C%2020%2C%20100]%3B%0A%20%20var%20change_arr%20%3D%20[]%3B%0A%20%20%0A%20%20for%20%28var%20i%3Dcid.length-1%3B%20i%3E%3D0%3B%20i--%29{%0A%20%20%20%20if%20%28%28coins[i]%3Cchange%29%20%26%20%28cid[i][1]%20!%3D%3D%200%29%20%29{%0A%20%20%20%20%20%20%20var%20temp%20%3D%20get_change%28change%2C%20coins[i]%2C%20cid[i][1]%20%29%3B%0A%20%20%20%20%20%20%20%20change_arr.push%28[cid[i][0]%2C%20temp]%29%3B%0A%20%20%20%20%20%20%20%20change%20-%3D%20temp%3B%0A%20%20%20%20%20%20%20%20cid[i][1]%20-%3D%20temp%3B%0A%20%20%20%20%20%20}%0A%20%20%20%20}%0A%20%20%0A%20%20if%20%28change%20%3D%3D%3D%200%29{%0A%20%20%20%20if%20%28check_closed%28cid%29%29{%0A%20%20%20%20%20%20return%20%22Closed%22%3B%0A%20%20%20%20}%0A%20%20%20%20return%20change_arr%3B%0A%20%20}%0A%20%20%2F%2F%20Here%20is%20your%20change%2C%20ma%27am.%0A%20%20return%20get_change%280.26%2C%200.1%2C%203.10%29%3B%0A}%0A%0A%2F%2F%20Example%20cash-in-drawer%20array%3A%0A%2F%2F%20[[%22PENNY%22%2C%201.01]%2C%0A%2F%2F%20[%22NICKEL%22%2C%202.05]%2C%0A%2F%2F%20[%22DIME%22%2C%203.10]%2C%0A%2F%2F%20[%22QUARTER%22%2C%204.25]%2C%0A%2F%2F%20[%22ONE%22%2C%2090.00]%2C%0A%2F%2F%20[%22FIVE%22%2C%2055.00]%2C%0A%2F%2F%20[%22TEN%22%2C%2020.00]%2C%0A%2F%2F%20[%22TWENTY%22%2C%2060.00]%2C%0A%2F%2F%20[%22ONE%20HUNDRED%22%2C%20100.00]]%0A%0AcheckCashRegister%283.26%2C%20100.00%2C%20[[%22PENNY%22%2C%201.01]%2C%20[%22NICKEL%22%2C%202.05]%2C%20[%22DIME%22%2C%203.10]%2C%20[%22QUARTER%22%2C%204.25]%2C%20[%22ONE%22%2C%2090.00]%2C%20[%22FIVE%22%2C%2055.00]%2C%20[%22TEN%22%2C%2020.00]%2C%20[%22TWENTY%22%2C%2060.00]%2C%20[%22ONE%20HUNDRED%22%2C%20100.00]]%29%3B%0A

#### Issue Description

return 0.1+0.2 ===> 0.3000000004 !!!!!!!

#### Browser Information

* Browser Name, Version: firefox
* Operating System: mac
* Mobile, Desktop, or Tablet: desktop

#### Your Code

function check_closed(cid){
  for(var i=0; i<cid.length; i++){
    if (cid[i][1] !== 0){
      return false;
    }
  }
  return true;
}

function get_change(change, coin , cid ){
  if (change == cid ){
    return change;
  }
  var i = coin;
  while(i < cid){
    if (i > change){
      
      break;
    }
    i += coin;
    return 0.20 + 0.10;
  } 
    
  return i-coin;
}

function checkCashRegister(price, cash, cid) {
  var change = (cash - price);
  var coins = [0.01, 0.05, 0.1, 0.25, 1, 5, 10, 20, 100];
  var change_arr = [];
  
  for (var i=cid.length-1; i>=0; i--){
    if ((coins[i]<change) & (cid[i][1] !== 0) ){
       var temp = get_change(change, coins[i], cid[i][1] );
        change_arr.push([cid[i][0], temp]);
        change -= temp;
        cid[i][1] -= temp;
      }
    }
  
  if (change === 0){
    if (check_closed(cid)){
      return "Closed";
    }
    return change_arr;
  }
  // Here is your change, ma'am.
  return get_change(0.26, 0.1, 3.10);
}

// Example cash-in-drawer array:
// [["PENNY", 1.01],
// ["NICKEL", 2.05],
// ["DIME", 3.10],
// ["QUARTER", 4.25],
// ["ONE", 90.00],
// ["FIVE", 55.00],
// ["TEN", 20.00],
// ["TWENTY", 60.00],
// ["ONE HUNDRED", 100.00]]

checkCashRegister(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);

```

#### Screenshot

**Comment by BerkeleyTrue** [comment]
Can you describe the issue you are having?

**Comment by shirga** [comment]
I created a function, and when I add 0.1+0.2 instead of getting 0.3 I get
0.30000004.

**Comment by shirga** [comment]
found the problem online
http://stackoverflow.com/questions/3650081/why-does-the-sum-of-2-parsefloat-variables-give-me-an-incorrect-decimal-number

Thanks anyway
Shir
