### ISSUE TITLE
Add units to GM in "Map the Debris"

### ISSUE THREAD

**Issue by kehugter** [FreeCodeCamp/FreeCodeCamp#8117]
Challenge [Map the Debris](https://www.freecodecamp.com/challenges/map-the-debris#?solution=function%20orbitalPeriod(arr)%20%7B%0A%20%20var%20GM%20%3D%20398600.4418%3B%0A%20%20var%20earthRadius%20%3D%206367.4447%3B%0A%20%20var%20ops%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20obj%20of%20arr)%20%7B%0A%20%20%20%20var%20op%20%3D%20Math.round(%0A%20%20%20%20%20%202%20*%20Math.PI%20*%20Math.pow(%0A%20%20%20%20%20%20%20%20Math.pow(%0A%20%20%20%20%20%20%20%20%20%20earthRadius%20%2B%20obj.avgAlt%2C%203%0A%20%20%20%20%20%20%20%20)%20%2F%20GM%2C%200.5%0A%20%20%20%20%20%20)%0A%20%20%20%20)%3B%0A%20%20%20%20ops.push(%7Bname%3A%20obj.name%2C%20orbitalPeriod%3A%20op%7D)%3B%0A%20%20%7D%0A%20%20return%20ops%3B%0A%7D%0A%0AorbitalPeriod(%5B%7Bname%3A%20%22iss%22%2C%20avgAlt%3A%20413.6%7D%2C%20%7Bname%3A%20%22hubble%22%2C%20avgAlt%3A%20556.7%7D%2C%20%7Bname%3A%20%22moon%22%2C%20avgAlt%3A%20378632.553%7D%5D)%0A) has an issue.

The provided GM value (398600.4418) is not the standard one in [m<sup>3</sup>s<sup>-2</sup>], it is converted to kilometres instead. It would be of good physics style to include the units.

I'd PR it myself but I don't find any occurrence of powers in other instructions to copy the tags/style used.

**Comment by erictleung** [comment]
@kehugter the tags you want should be:

```
m<sup>3</sup>s<sup>-2</sup>
```

It'll print out  "m<sup>3</sup>s<sup>-2</sup>"

**Comment by kehugter** [comment]
Yes, I couldn't grep those tags elsewhere and was unsure if you had something against them.
