### ISSUE TITLE
The result I got has object property like name in quotes.  I tried literal string constructor, dot notation.  Nothing works to get rid of quotes.  I did some research.  There is no difference with or without quotes.  Please advise.  Thanks.

### ISSUE THREAD

**Issue by llwang8** [FreeCodeCamp/FreeCodeCamp#8123]
Challenge [Map the Debris](https://www.freecodecamp.com/challenges/map-the-debris) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function getOrbitalPeriod(orbitObjAlt, GM, planetRadius){
  var avgDistance = planetRadius + orbitObjAlt;
  var orbitalPeriod = 2 * Math.PI * Math.sqrt(Math.pow(avgDistance, 3) / GM);
  return Math.round(orbitalPeriod);
}

function orbitalPeriods(arr) {
  var GM = 398600.4418;
  var earthRadius = 6367.4447;
  return arr.map(function(curObj){
    var newObj = {};
    newObj.name = curObj.name;
    newObj.orbitalPeriod = getOrbitalPeriod(curObj.avgAlt, GM, earthRadius);
    return newObj;
  });
}

orbitalPeriods([{name : "sputnik", avgAlt : 35873.5553}]);


```

**Comment by dwd2010** [comment]
@llwang8, By the way, you could ask a help at [FCC Help room](https://gitter.im/FreeCodeCamp/Help).

**Comment by erictleung** [comment]
@llwang8 your function name should be `orbitalPeriod` with no "s" at the end. It should work when you fix it. Happy coding!

**Comment by llwang8** [comment]
I got it work.  Thank you so much.

Li
