### ISSUE TITLE
Probably wrong rule in "Build a Personal Portfolio Webpage"

### ISSUE THREAD

**Issue by AidenKerr** [FreeCodeCamp/FreeCodeCamp#8125]
#### Challenge Name

Build a Personal Portfolio Webpage

#### Issue Description

One of the rules is "Choose your own tribute subject". This is probably accidentally copied from the tribute project's requirements.

**Comment by dwd2010** [comment]
Thank you for report.  this issue need to fix

**Comment by dwd2010** [comment]
![46541238448](https://cloud.githubusercontent.com/assets/9701609/14550607/b5b6308a-028f-11e6-9933-25424f6ecf08.png)
number 5 is wrong.

**Comment by theflametrooper** [comment]
@erictleung I'll take care of this...
