### ISSUE TITLE
Quoting Strings with Single Quotes

### ISSUE THREAD

**Issue by jthurlow** [FreeCodeCamp/FreeCodeCamp#8128]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=var%20myStr%20%3D'%3Ca%20href%3D%20%22http%3A%2F%2Fwww.example.com%22%20target%3D%20%22_blank%22%3ELink%3C%2Fa%3E'%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr ='<a href= "http://www.example.com" target= "_blank">Link</a>';



```

**Comment by erictleung** [comment]
@jthurlow please explain the issue you are having. If you are stuck on this challenge, please close this issue and ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

This quote from an upcoming update might help:

> Unless they are escaped, you cannot have more than one pair of whichever quote type begins a string.

**Comment by robeerob** [comment]
While I agree that this is more of a "ask for help issue" rather than a bug issue, the "quote from an upcoming update" is not relevant to the mistake @jthurlow made. The quote type that begins the string is only used in one pair in his code (start and end).

**Comment by jthurlow** [comment]
I believe what I have written is correct. The reason given for unsuccessful challenge was is that I need to remove all escaping backslashes.

**Comment by robeerob** [comment]
The code you shared had all escaping backslashes removed already. You just needed to also remove the two whitespaces that had snuck in.

**Comment by jthurlow** [comment]
Ok thanks!

**Comment by erictleung** [comment]
@jthurlow yes, @robeerob is correct. I didn't look at your code long enough. The string shouldn't be modified at all except changing the quotes and removing backspaces. Closing as it appears it is resolved and not an issue with FCC. Happy coding!
