### ISSUE TITLE
Nesting For Loops Error

### ISSUE THREAD

**Issue by ALMY91** [FreeCodeCamp/FreeCodeCamp#8129]
Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  
 for (var i =0 ; i< arr.length;i++) {
   for(var j=0 ; j<arr[i].length; j++)
**console.log (arr[i][j]);    **
   product*=arr[i][j];
 }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);


```

**Comment by ALMY91** [comment]
What is the reasoning behind this that my code only work when i take away the console.log liner?

**Comment by sludge256** [comment]
Confirming that I am getting `null` in the output box if any `console.log()` statement occurs before the nested `product*=arr[i][j];`.
