### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/freecodecamp#813]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-button has an issue. 

After completing the task, there is still a "length" error that cannot be fixed:
"Cannot read property 'length' of null"

UPDATE: Most of the Waypoints have this error.

**Comment by nvamsikrishna05** [comment]
I am also getting the same error.
This appeared in two waypoints : 
<em>Waypoint: Create a Bootstrap Button
Waypoint: Create a Block Element Bootstrap Button
</em>

**Comment by daewu** [comment]
http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons

I passed the bootstrap button earlier today, but im on this one and i get the length of null error, maybe it's similar issue?

**Comment by BerkeleyTrue** [comment]
We will be tracking this issue in #809
