### ISSUE TITLE
Getting correct answer in console, but test case is not passing...

### ISSUE THREAD

**Issue by raj-maurya** [FreeCodeCamp/FreeCodeCamp#8132]
Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%3D16%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%5B16%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber=16;       // Change this Line
var player = testObj[16];   // Change this Line

```
![screenshot from 2016-04-15 13 54 20](https://cloud.githubusercontent.com/assets/9070249/14555790/12a1a57c-0312-11e6-981c-677c8e6fd53e.png)

**Comment by awesomeaniruddh** [comment]
@raj-maurya The last test expects you to use the `playerNumber` variable to access the value from the objects, like so: `var player = testObj[playerNumber];`

The copy of the last test should probably be changed to 
> You should use bracket notation to access `testObj` using the variable `playerNumber`

**Comment by raj-maurya** [comment]
Thanks @awesomeaniruddh !

**Comment by AkiraLaine** [comment]
Closing this is as it's not an issue.

**Comment by barasof** [comment]
Although the console warned "expected an assignment or function call and instead saw an expression," my answer got accepted when I did not declare a "player" variable. Would that be okay nonetheless? Just in case this should not be accepted I paste it below,

// Only change code below this line;

var playerNumber=16;       // Change this Line
testObj[playerNumber];   // Change this Line
