### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by LvntE** [FreeCodeCamp/FreeCodeCamp#8134]
![2016-04-15](https://cloud.githubusercontent.com/assets/18472489/14561560/14d427d4-02e5-11e6-8fb3-c42a44713c84.png)
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-test%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-test%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-test {
    color: pink;
  }
</style>
<h1 class="pink-test">Hello World!</h1>

```

I think this should pass the challenge

**Comment by raisedadead** [comment]
Thanks for reporting this. Your code is incorrect:

`.pink-test` ?? should be something else, refer instructions.

Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
