### ISSUE TITLE
Codepen - Issue with Show Local Weather App

### ISSUE THREAD

**Issue by dhyey35** [FreeCodeCamp/FreeCodeCamp#8139]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.

The local weather app at https://codepen.io/FreeCodeCamp/full/bELRjV. is not working properly
![image](https://cloud.githubusercontent.com/assets/11143604/14569485/b333fd24-035c-11e6-90d9-7507fc8706f3.png)

It does not show any weather information. Please update the link with an app that works.

**Comment by raisedadead** [comment]
@dhyey35 

It works for me:

![screen shot 2016-04-15 at 11 14 43 pm](https://cloud.githubusercontent.com/assets/1884376/14570063/ef69fad4-035f-11e6-8af4-e7b0f56bcb26.png)

Have you tries the common debugging steps?

**Comment by sludge256** [comment]
The issue appears on my end with Chrome 49 also. I've tested other weather Pens and they appear to be working.

**Comment by raisedadead** [comment]
@sludge256 can you fork a copy and get it to working? If you do I can update this right away with your changes?

**Comment by dwd2010** [comment]
Odd i have that problem. I cant figure it out myself.  somehow it didnt ask me allow or deny my location.

**Comment by raisedadead** [comment]
@sludge256 never mind I found the trouble:
`http://ipinfo.io/json?callback=JSON_CALLBACK`

**Comment by theflametrooper** [comment]
I also had the same problem as @dwd2010

**Comment by raisedadead** [comment]
Okay I found the trouble, the JSON resource is hosted over `http` and not `https`,
opening the pen also over `http` works as in :

http://codepen.io/FreeCodeCamp/full/bELRjV/    <-- NOT broken
vs
https://codepen.io/FreeCodeCamp/full/bELRjV/   <-- Broken

**Comment by dwd2010** [comment]
oh odd, http://codepen.io/FreeCodeCamp/full/bELRjV/ is work on me.

**Comment by raisedadead** [comment]
Making a quick fix.

**Comment by j7an** [comment]
Found the solution here on Reddit so I didn't have to rewrite my code for another API: https://www.reddit.com/r/FreeCodeCamp/comments/4ioycb/how_to_solve_mixed_content_issue/
