### ISSUE TITLE
"editor.match(...) is null" added as a condition on waypoints in bootstrap section

### ISSUE THREAD

**Issue by hunterst44** [FreeCodeCamp/freecodecamp#814]
http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-button

"editor.match(...) is null" is added as a third condition, which can't be passed even if the correct code is entered.

This condition also appears in waypoints 4-8 and 10 (possibly others too)
![waypoint](https://cloud.githubusercontent.com/assets/3461521/7953207/c645a15a-0976-11e5-92bc-7c9f00a017eb.jpg)

**Comment by daewu** [comment]
Waypoint: Add Font Awesome Icons to our Buttons

I passed the create a bootstrap button earlier today...but now maybe all the waypoint ones have the null bug right now? I can't get passed the Font Awesome one

**Comment by BerkeleyTrue** [comment]
Looks like this is related to #809 We will be tracking this issue there. Thanks for reporting.
