### ISSUE TITLE
Comparisons with the Logical And Operator. The console returns the right value but the test says points 5,6 and 7 are wrong. 

### ISSUE THREAD

**Issue by massield** [FreeCodeCamp/FreeCodeCamp#8140]
Challenge [Comparisons with the Logical And Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator#?solution=function%20testLogicalAnd(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20if%20(%20val%20%3C%3D%2050%20%26%26%20val%20%3E%3D%2025)%7B%0A%20%20%20return%20%22yes%22%3B%0A%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22No%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalAnd(50)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function testLogicalAnd(val) {
  // Only change code below this line

 if ( val <= 50 && val >= 25){
   return "yes";
 }
  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(50);

```

**Comment by sludge256** [comment]
Make sure what you are returning matches the expected results _**exactly**_. 

Please use the `help` button to access the chat and ask for confirmation in the future.
We don't handle code related issues via GitHub, but we do appreciate the attempt at reporting a bug. Thanks!

**Comment by massield** [comment]
ok. thanks
