### ISSUE TITLE
Wiki article request:

### ISSUE THREAD

**Issue by WAKEUPMGPI** [FreeCodeCamp/FreeCodeCamp#8142]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by dwd2010** [comment]
Could you explain what you request?  I need to get more information.

**Comment by sludge256** [comment]
Please post over at the Wiki repo: https://github.com/FreeCodeCamp/wiki/issues

Be sure to fill in relevant details otherwise your issue will be closed.

**Comment by WAKEUPMGPI** [comment]
I was setting up a text editor & I had no idea this happened! Please except
my apologies! I feel terrible!

**Comment by WAKEUPMGPI** [comment]
I was setting up a text editor & I had no idea this happened!

**Comment by sludge256** [comment]
@WAKEUPMGPI Don't worry about it. Stuff happens.

**Comment by WAKEUPMGPI** [comment]
Thank you.
