### ISSUE TITLE
Error: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by billiams** [FreeCodeCamp/freecodecamp#815]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Added "<i class="fa fa-thumbs-up"></i>" nested within like button like so:
<button class='btn btn-block btn-primary'><i class="fa fa-thumbs-up"></i> Like</button>

and am triggering an error "Cannot read property 'length' of null" in the debug panel. See screenshot. Won't let me go forward.
![screenshot 2015-06-02 22 26 18](https://cloud.githubusercontent.com/assets/2591682/7953240/476ec0fe-0977-11e5-86c7-ad44aae554d3.png)

**Comment by AkiraLaine** [comment]
@billiams Most of the Waypoints have this error, I also opened an issue: https://github.com/FreeCodeCamp/freecodecamp/issues/813

**Comment by billiams** [comment]
@AkiraLaine I see - looks like it may be a regex / "match" issue according to StackOverflow... thanks for the heads up. 

http://stackoverflow.com/questions/10183614/cannot-read-property-length-of-null-in-javascript-for-loop

**Comment by BerkeleyTrue** [comment]
We will be tracking this bug in #809
