### ISSUE TITLE
Code is correct but unable to complete the challenge

### ISSUE THREAD

**Issue by sdg123** [FreeCodeCamp/FreeCodeCamp#8152]
#### Challenge Name
Finders Keepers

https://www.freecodecamp.com/challenges/finders-keepers

#### Issue Description

My code works fine. I've ran each test case provided and the required sample output appears. However, I am unable to proceed and the challenge is still incomplete.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function find(arr, func)
{
  var num = 0;
  var flag=0;
  
  for(var i=0;i<arr.length;i++)
    {
      if(func(arr[i])===true)
        {
          flag=1;
          break;
        }
    }
  if(flag===1)
    return arr[i];
  else
    return undefined;

}

find([1, 3, 5, 9,8], function(num) { return num % 2 === 0; });

```

#### Screenshot

![fcc](https://cloud.githubusercontent.com/assets/3778313/14581956/68a718f6-0418-11e6-8aca-ff6d4965116a.png)

**Comment by theflametrooper** [comment]
@sdg123 `findElement([1, 3, 5, 9], function(num) { return num % 2 === 0; })` should return undefined.

**Comment by sdg123** [comment]
return undefined; 
Doesn't this statement return undefined?

**Comment by theflametrooper** [comment]
@sdg123 Oh yeh I see! This looks like a bug...

Tagging @SaintPeter

**Comment by SaintPeter** [comment]
We recently changed the names of many of the functions so they would be unique.

The correct function name for this challenge is `findElement`.

Change your first line from:
`function fund(arr, func)`
to
`function findElement(arr, func)`

**Comment by sdg123** [comment]
Thank you!
