### ISSUE TITLE
8th test case of  Make a Person Challange  failing

### ISSUE THREAD

**Issue by rupeshpadhye** [FreeCodeCamp/FreeCodeCamp#8153]
Challenge [Make a Person](https://www.freecodecamp.com/challenges/make-a-person#?solution=%20%20%20%20%20function%20Person(fullName)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20fistName%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20lastName%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.getFirstName%3Dfunction%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20fistName%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.getLastName%3D%20function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20lastName%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.setFistName%3D%20function%20(fname)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fistName%20%3D%20fname%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.setLastName%3D%20function%20(lname)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20lastName%20%3D%20lname%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.getFullName%3D%20function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20fistName%20%2B%20%22%20%22%20%2B%20lastName%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.setFullName%3D%20function%20(fullname)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20data%20%3D%20fullname.split(%22%20%22)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fistName%20%3D%20data%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20lastName%20%3D%20data%5B1%5D%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20this.setFullName(fullName)%3B%0A%0A%20%20%20%20%20%20%0A%0A%20%20%20%20%20%20%20%20%7D%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0Abob.getFullName()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
     function Person(fullName) {
            var fistName;
            var lastName;

           

                this.getFirstName=function () {
                    return fistName;
                };
                this.getLastName= function () {
                    return lastName;
                };
                this.setFistName= function (fname) {
                    fistName = fname;
                };
                this.setLastName= function (lname) {
                    lastName = lname;
                };
                this.getFullName= function () {
                    return fistName + " " + lastName;
                };
                this.setFullName= function (fullname) {
                    var data = fullname.split(" ");
                    fistName = data[0];
                    lastName = data[1];

                };
                
            this.setFullName(fullName);

      

        }
        var bob = new Person('Bob Ross');
        console.log(bob.getFullName()); //console Bob Ross
        bob.setFistName("Haskell");
        console.log(bob.getFullName()); //console Haskell Ross

```
I am getting desired answer in console but test case is failing

**Comment by theflametrooper** [comment]
Hey @rupeshpadhye this is just an issue with your code! Please contact the [Javascript Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting help with challenges!

**Comment by qq345386817** [comment]
This will work:
`this.setFullName = function(fullName) {
    var arr = fullName.split(" ");
    this.setFirstName(arr[0]);
    this.setLastName(arr[1]);
  };`

**Comment by pigtails21** [comment]
What the fuck!!

**Comment by theflametrooper** [comment]
@qq345386817 Please don't post answers to challenges here.

**Comment by qq345386817** [comment]
@theflametrooper Sorry!
