### ISSUE TITLE
Two test cases for the Drop it challenge are incorrect

### ISSUE THREAD

**Issue by sdg123** [FreeCodeCamp/FreeCodeCamp#8154]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=function%20dropElements(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20var%20new_arr%3D%5B%5D%3B%0A%20%20for(var%20i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if(func(arr%5Bi%5D))%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20new_arr.push(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20return%20new_arr%3B%0A%7D%0A%0AdropElements(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(n)%20%7Breturn%20n%20%3E%3D%203%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
There are two test cases that are wrong.
![fcc](https://cloud.githubusercontent.com/assets/3778313/14582609/d34e7672-0427-11e6-9fa5-c7c4400eb531.png)

My code:
```javascript
function dropElements(arr, func) {
  // Drop them elements.
  var new_arr=[];
  for(var i=0;i<arr.length;i++)
    {
      if(func(arr[i]))
        {
          new_arr.push(arr[i]);
        }
    }
  return new_arr;
}

dropElements([1, 2, 3, 4], function(n) {return n >= 3;});

```

**Comment by erictleung** [comment]
@sdg123 thanks for the issue but there isn't anything wrong with the tests. The first line of the instructions read:

> Drop the elements of an array (first argument), starting from the front, **until** the predicate (second argument) returns `true`.

If you are still stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by sdg123** [comment]
Oh, thanks for clearing that up!
