### ISSUE TITLE
Issue In Sorted Union

### ISSUE THREAD

**Issue by ryetika** [FreeCodeCamp/FreeCodeCamp#8156]
#### Challenge Name

https://www.freecodecamp.com/challenges/sorted-union

#### Issue Description

My unit test outputs are correct, but they dont get marked as so.

#### Browser Information
Internet explorer 11 and chrome (ver 49)

* Browser Name, Version: Internet explorer 11 and chrome (ver 49)
* Operating System: windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
var unitedArr = [];

function insertNumber(searchNum) {
  var unitedArrLength = unitedArr.length;
 
  var currIndex = unitedArrLength - 1;
  while(currIndex >= 0)
    {
      if(unitedArr[currIndex] === searchNum)
        {
          return false;
        }
      currIndex--;
    }
  return true;
}

function uniteUnique() {
    var argumentsLength = arguments.length;
  for(var i = 0; i < argumentsLength; i++)
    {
      var inputArr = arguments[i];
      var inputArrLength = inputArr.length;
      for(var j = 0; j < inputArrLength; j++)
        {
          if(insertNumber(inputArr[j]) === true)
          {
            unitedArr.push(inputArr[j]);
          }
        }
    }
  return unitedArr;
}

uniteUnique([1, 2, 3], [5, 2, 1, 4], [2, 1], [6, 7, 8]);
```

#### Screenshot

![snapshot](https://cloud.githubusercontent.com/assets/13025064/14582974/06eca60c-0432-11e6-9cde-3495cd66aabd.png)

**Comment by BKinahan** [comment]
This happens because your variable `unitedArr` is in the global scope, and while the code works for a single call of the `uniteUnique` function, calling the function multiple times continues to operate on the now non-empty `unitedArr` array so that by the end of the tests being run, `unitedArr` looks like this:
`[ 1, 3, 2, 5, 4, [ 5 ], [ 4 ], 6, 7, 8 ]`. This is an important point about using global variables with functions.

Rearranging your code as such prevents this problem:
```js
// If relevant, paste all of your challenge code in here

function uniteUnique() {
  var unitedArr = [];
  
  function insertNumber(searchNum) {
  var unitedArrLength = unitedArr.length;

  var currIndex = unitedArrLength - 1;
  while(currIndex >= 0)
    {
      if(unitedArr[currIndex] === searchNum)
        {
          return false;
        }
      currIndex--;
    }
  return true;
}
  
    var argumentsLength = arguments.length;
  for(var i = 0; i < argumentsLength; i++)
    {
      var inputArr = arguments[i];
      var inputArrLength = inputArr.length;
      for(var j = 0; j < inputArrLength; j++)
        {
          if(insertNumber(inputArr[j]) === true)
          {
            unitedArr.push(inputArr[j]);
          }
        }
    }
  return unitedArr;
}
```

**Comment by erictleung** [comment]
@ryetika what @BKinahan has said is correct. You'll want to avoid any global variables. Closing as not an issue with the site. Happy coding!

**Comment by ryetika** [comment]
Thanks a lot for explaining. I never realized the test case are being run sequentially in the same execution. My bad.
