### ISSUE TITLE
Challenge is not suitable for Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by xRahul** [FreeCodeCamp/FreeCodeCamp#8161]
#### Challenge Name

https://www.freecodecamp.com/challenges/finders-keepers

#### Issue Description

The solution is one-liner and requires only basic js knowledge. 
It is not intermediate level in difficulty.

**Comment by xRahul** [comment]
This Also should be in Basic Algorithm Scripting-

#### Challenge Name

https://www.freecodecamp.com/challenges/drop-it

**Comment by raisedadead** [comment]
@xRahul Thanks for reporting this.

However, personally I would disagree on moving the challenges to basic sections.
The "target audience" would be overwhelmed.
Beginners, for instance would not do a one liner solution to these challenges (if you are counting that as a metrics).

Having said that I would love to see what the others have to say. Please feel free to discuss this more in the [CurriculumDevelopment](https://gitter.im/FreeCodeCamp/CurriculumDevelopment) room.

/cc Looping in @SaintPeter for his expert insight on this.

**Comment by SaintPeter** [comment]
I believe it is in the right place.  If you're able to one-liner it, bully for you, but many novice programmers will not be able to do it quite so easily.

Sometimes the hardest part is coming up with a simple solution.

**Comment by xRahul** [comment]
If you all think so, then it's alright I guess.
For me the rest were a lot more difficult than this one, but to each his own.

**Comment by johnnc2** [comment]
Yeah looking at this one I'm definitely not able to complete it in one line so it's perfect where it is.
