### ISSUE TITLE
Separate "sign in" and "sign up" workflows

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8167]
Sign in should remain as it currently is. 

Sign up should ~~only~~ offer ~~(passwordless)~~ email authentication. Note that many people will attempt to use a fake email, only to later realize that they actually need to verify the email, so we will need to show them a page that says "confirmation email sent" and gives them a chance to change their email and send the email again.

Once they click through the verification link, we should create their user object using the email they used.

Edit(@berkeleyTrue):
- [x] User can signup with either Email or GitHub
- [x] Remove other O-auth signup processes (exluding Github)
- [x] Leave other O-auth login processes in tacked
- [ ] Show users without verified email flash message to add email
- [x] Add form so users can add email and verify them
- [x] Move deprecated O-auth to separate page with notice of their pending removal

I've also removed the passwordless feature from this issue as their is another issue for that already. This issue does not require passwordless email

**Comment by CharlesManga** [comment]
I would like to help. Where can i get started?

**Comment by raisedadead** [comment]
@CharlesManga You have been pointed to the [Contribution](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) guidelines already many times. Follow the instructions there. Also seek any further assistance in the [HelpContributors Chat Room](https://gitter.im/FreeCodeCamp/HelpContributors). 

Thanks.

**Comment by BerkeleyTrue** [comment]
@raisedadead are you working on the email verification?
