### ISSUE TITLE
Started Html coding

### ISSUE THREAD

**Issue by Drake9546** [FreeCodeCamp/FreeCodeCamp#8169]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch2%3Ehi%3C%2Fh2%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello</h1>
<h2>hi</h2>

```

**Comment by dwd2010** [comment]
Sorry. this challenge dont have a issue. you could ask a help at [FCC help room](https://gitter.im/FreeCodeCamp/Help)

**Comment by theflametrooper** [comment]
@Drake9546 You're h1 tag should have the text `Hello World`. Please read the challenge instructions more thoroughly next time.
