### ISSUE TITLE
Make sure your i element has a closing tag

### ISSUE THREAD

**Issue by pringlesjoa** [FreeCodeCamp/freecodecamp#817]
http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons has an issue. 
It says I am missing a closing tag for my i element, but I cannot find any issues in my code..
![screenshot_20150603162123](https://cloud.githubusercontent.com/assets/12726968/7954670/a091a558-0a0c-11e5-8886-16ce8bb5f0ce.png)

**Comment by QuincyLarson** [comment]
Thank you for your detailed issue! I've pushed a fix for this.
