### ISSUE TITLE
delate my account

### ISSUE THREAD

**Issue by Mohammedamin7** [FreeCodeCamp/FreeCodeCamp#8171]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@Mohammedamin7 if you'd like to delete your account, you have to visit the settings page on the Free Code Camp website https://www.freecodecamp.com/settings. Near the bottom will have a button to delete your account. Closing as not an issue with the site.

**Comment by Robert381** [comment]
stop sending me emails 

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 18, 2016 at 2:44 AM, Eric Leung<notifications@github.com> wrote:   
Closed #8171.

**Comment by theflametrooper** [comment]
@Robert381 To stop receiving emails go here: https://www.freecodecamp.com/settings and scroll down to "Email Settings". In future please ask in chat rooms for help regarding this matter.
