### ISSUE TITLE
Change the font size of an element - BUG

### ISSUE THREAD

**Issue by deadmann** [FreeCodeCamp/FreeCodeCamp#8175]
#### Challenge Name

https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%0A%20%20p%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

#### Issue Description

on running tests. and on refresh

#### Browser Information

* Browser Name, Version:  Chrome, 49
* Operating System: windows 10
* Mobile, Desktop, or Tablet: All In One (Kind of Desktop)

#### Your Code

```js
// If relevant, paste all of your challenge code in here
<style>
  .red-text {
    color: red;
  }
  
  p{
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

#### Screenshot

![1234567890-](https://cloud.githubusercontent.com/assets/1919241/14601949/54285972-057a-11e6-9a42-8fd68cf1daa8.jpg)

**Comment by cannelflow** [comment]
instructions are
#Create a second p element with the following kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.
i guess you just pasted first p tag
you can also use FCC chat room https://gitter.im/FreeCodeCamp/Help

**Comment by deadmann** [comment]
but as you see there are two p

**Comment by raisedadead** [comment]
Hi @deadmann Thanks for reporting but your code is incorrect.

Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
