### ISSUE TITLE
Code Tags partially moving onto the next line

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/FreeCodeCamp#8179]
#### Challenge Name
[Adding a default option in Switch statements](https://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements)

#### Issue Description
Weird bug where code tags on this specific challenge move partially onto the next line.
Bug also appears on night mode.

#### Browser Information
* User Agent: _Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36_
* Operating System: _Windows_
* Mobile, Desktop, or Tablet: _Desktop_

_Tested on **Chrome, Chrome (Incognito) and Firefox**_

#### Screenshot
![](https://i.gyazo.com/93c2b218e67d33e4ec2d2d52ab339087.png)

**Comment by dwd2010** [comment]
![56131384355645](https://cloud.githubusercontent.com/assets/9701609/14625348/ee6cd6e8-05a7-11e6-99d1-ce1d01a028f5.png)

**Comment by awesomeaniruddh** [comment]
This happens because the `code` tag on the first five tests is not closed:
(`seed/challenges/01-front-end-development-certification/basic-javascript.json`)
```js
"assert(switchOfStuff(\"a\") === \"apple\", 'message: <code>switchOfStuff(\"a\") should have a value of \"apple\"');",
"assert(switchOfStuff(\"b\") === \"bird\", 'message: <code>switchOfStuff(\"b\") should have a value of \"bird\"');",
"assert(switchOfStuff(\"c\") === \"cat\", 'message: <code>switchOfStuff(\"c\") should have a value of \"cat\"');",
"assert(switchOfStuff(\"d\") === \"stuff\", 'message: <code>switchOfStuff(\"d\") should have a value of \"stuff\"');",
"assert(switchOfStuff(4) === \"stuff\", 'message: <code>switchOfStuff(4) should have a value of \"stuff\"');",
"assert(!/else/g.test(code) || !/if/g.test(code), 'message: You should not use any <code>if</code> or <code>else</code> statements');",
"assert(code.match(/break/g).length > 2, 'message: You should have at least 3 <code>break</code> statements');"
```

**Comment by theflametrooper** [comment]
@awesomeaniruddh Thanks! Let me submit a pr!
