### ISSUE TITLE
Waypoint wants name of radio button set, can't recognize correct change

### ISSUE THREAD

**Issue by DanSt** [FreeCodeCamp/freecodecamp#818]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I followed all the necessary requests to change the code the way it is supposed to be. It seems that the request "Give your radio buttons the name attribute of "personality"." is either broken or misplaced. After changing the name of the radio-buttons, the checkpoint does not turn green.

**Comment by DanSt** [comment]
Well played freecodecamp. The reason (according to your source-code) does not look like a mistake. You have to read the site's source-code to understand what the test actually wants from you (Surprise: it is not what it says that it wants)

**Comment by greglgomez** [comment]
Thanks for the tip, but I don't think GitHub issues are the place to be cryptic.

`attr('name') === 'trait'` should instead be `attr('name') === 'personality'` to match what the test says it's looking for.

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.

**Comment by DanSt** [comment]
Thanks for the fast fix! I was being cryptic, because it could have been on purpose and I would have ruined the 'easter egg' otherwise ;)
