### ISSUE TITLE
Remove Classes from an element with jQuery   bug

### ISSUE THREAD

**Issue by ankur1163** [FreeCodeCamp/FreeCodeCamp#8180]
#### Challenge Name

https://www.freecodecamp.com/challenges/remove-classes-from-an-element-with-jquery#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%0A%20%20%20%20%24(%22button%22).removeClass(%22btn-default%22)%3B%0A%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A

#### Issue Description

I think my code is perfect. still, it says my task " Only use jQuery to remove this class from the element" isnt done. 
#### Browser Information

* Browser Name, Version: laest chrome version
* Operating System: 
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
<script>
  $(document).ready(function() {
   
    $("button").removeClass("btn-default");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn  btn-default target" id="target1">#target1</button>
        <button class="btn  btn-default target" id="target2">#target2</button>
        <button class="btn  btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn  btn-default target" id="target4">#target4</button>
        <button class="btn  btn-default target" id="target5">#target5</button>
        <button class="btn  btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

#### Screenshot

it still doesnt get past the "Only use jQuery to remove this class from the element."

**Comment by theflametrooper** [comment]
@ankur1163 You have more than one space between your classes:
~~`class="btn  btn-default`~~ `class="btn btn-default`.

Please ask in the help room for future help with challenges...
