### ISSUE TITLE
My Working Code Does Not Allow Me To Progress

### ISSUE THREAD

**Issue by Seniority** [FreeCodeCamp/FreeCodeCamp#8182]
Challenge [Introducing Else Statements](https://www.freecodecamp.com/challenges/introducing-else-statements#?solution=function%20testElse(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(val%20%3E%205)%20%0A%20%20%7B%0A%20%20%20%20result%20%3D%20%22Bigger%20than%205%22%3B%0A%20%20%7D%0A%20%20else%20%0A%20%20%7B%0A%20%20%20%20result%20%3D%20%225%20or%20smaller%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestElse(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function testElse(val) {
  var result = "";
  // Only change code below this line
  
  if (val > 5) 
  {
    result = "Bigger than 5";
  }
  else 
  {
    result = "5 or smaller";
  }
  
  // Only change code above this line
  return result;
}

// Change this value to test
testElse(5);


```

**Comment by acostariel** [comment]
Hi.
You have a typo in the result you're assigning in the else block. It should be '5 or Smaller'.

**Comment by milpool** [comment]
there is a bug in the system. It works when you write it as
 
else result = "5 or smaller";
  }

when it should be 

else {
result = "5 or smaller";
}
}
