### ISSUE TITLE
Can we use Bootstrap for Personal Portfolio?

### ISSUE THREAD

**Issue by meganjean** [FreeCodeCamp/FreeCodeCamp#8184]
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage

#### Issue Description

It is unclear based on the instructions whether we are allowed to use Bootstrap for this challenge.

1. Number 4. Rule #3: You may use your own CSS and frameworks other than Bootstrap.
2. Number 10. There are many great portfolio templates out there, but for this challenge, you'll need to build a portfolio page yourself. Using Bootstrap will make this much easier for you.

#### Browser Information

* Browser Name, Version: n/a
* Operating System: n/a
* Mobile, Desktop, or Tablet: n/a

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/16136601/14624795/cbe26f30-05ab-11e6-8fe1-168b8a399deb.png)

**Comment by theflametrooper** [comment]
@meganjean Thanks for pointing that out! Going to pull in @QuincyLarson to see if we want to use Bootstrap for this project or not.

**Comment by xRahul** [comment]
Rule 3 means you don't have to use only bootstrap to build that. You're allowed to use other css frameworks too if you want. 
It doesn't say you must use a framework other than bootstrap though.

**Comment by alayek** [comment]
@meganjean sorry for the instruction being not clear.

Yes, whether to use Bootstrap or not, is absolutely up to you. 

If you can deliver a finished end-to-end responsive portfolio without using Bootstrap, that's even better! But you shouldn't feel bad that you would have to use Bootstrap :)

We would recommend using Bootstrap for now.

**Comment by meganjean** [comment]
@alayek Thank you.
