### ISSUE TITLE
Generate Random Whole Numbers within a Range

### ISSUE THREAD

**Issue by eratio08** [FreeCodeCamp/FreeCodeCamp#8188]
Challenge [Generate Random Whole Numbers within a Range](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-within-a-range#?solution=%2F%2F%20Example%0Afunction%20ourFunction(ourMin%2C%20ourMax)%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%7D%0A%0AourFunction(1%2C%209)%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20randomRange(myMin%2C%20myMax)%20%7B%0A%0A%20%20return%20%20Math.floor(Math.random()%20*%20(myMax%20-%20myMin))%20%2B%20myMin%3B%20%2F%2F%20Change%20this%20line%0A%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0Avar%20myRandom%20%3D%20randomRange(5%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
function ourFunction(ourMin, ourMax) {

  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourFunction(1, 9);

// Only change code below this line.

function randomRange(myMin, myMax) {

  return  Math.floor(Math.random() * (myMax - myMin)) + myMin; // Change this line

}

// Change these values to test your function
var myRandom = randomRange(5, 15);

```
Checked the maxima (Math.random()=1) and minima(Math.random()=0) and and the solution is right but the target "The random number generated by randomRange should be less than or equal to your maximum number, myMax. " won't evaluate to true.

**Comment by alistermada** [comment]
`randomRange()` in the code above has a maximum value of 14 instead of 15 (`myMax`).

I think the first two test messages should be reworded so that it's clear that the maximum value in the range should equal `myMax` and the minimum value should equal `myMin`.

**Comment by BKinahan** [comment]
@eratio08 To expand on what @alistermada wrote, the maximum of `Math.random()` is not actually 1. The range is `[0,1)`, which is inclusive of 0 but exclusive of 1. So the real maximum is something like 0.99999..., but when combined with `Math.floor()` the maximum is 0 unless the result is multiplied (or increased in some way) first.

Although it probably didn't cause the confusion here, I agree the text should be clarified.

**Comment by erictleung** [comment]
@eratio08 your code doesn't match the code example in the instructions, as you removed the `+1`. If you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

@BKinahan I like the change in wording 😄

**Comment by jbundrea** [comment]
What @BEBEDYDY said. Adding the 1 to the myMax did the trick
