### ISSUE TITLE
Challenge Getting Passed even with incorrect code

### ISSUE THREAD

**Issue by Harshdand** [FreeCodeCamp/freecodecamp#819]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue.

This challenge is getting passed even without the buttons
Code
```
<div class="row">
  <div class="col-xs-4"></div>
   <div class="col-xs-4"></div>
   <div class="col-xs-4"></div>
</div>

**Comment by BerkeleyTrue** [comment]
Indeed!
