### ISSUE TITLE
Something wrong with this exercise?

### ISSUE THREAD

**Issue by dac2205** [FreeCodeCamp/FreeCodeCamp#8191]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=function%20dropElements(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20var%20x%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(func(arr%5Bi%5D))%20%7B%0A%20%20%20%20%20%20x.push(arr%5Bi%5D)%3B%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20x%3B%0A%7D%0A%0Avar%20x%20%3D%20dropElements(%5B1%2C%202%2C%203%2C%209%2C%202%5D%2C%20function(n)%20%7Breturn%20n%20%3E%202%3B%7D)%3B%0A%0Aconsole.log(x)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function dropElements(arr, func) {
  // Drop them elements.
  var x = [];
  
  for (var i = 0; i < arr.length; i++) {
    if (func(arr[i])) {
      x.push(arr[i]);    
    }
  }
  return x;
}

var x = dropElements([1, 2, 3, 9, 2], function(n) {return n > 2;});

console.log(x);
```

**Comment by erictleung** [comment]
@dac2205 this snippet from the instructions may help you:

> Drop the elements of an array (first argument), starting from the front, **until** the predicate (second argument) returns `true`.

If you are still stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Closing as not an issue with the site. Happy coding!
