### ISSUE TITLE
Hotkey to focus on code window

### ISSUE THREAD

**Issue by PrasoonVaish** [FreeCodeCamp/FreeCodeCamp#8193]
Hello everyone,

When a new challenge is launched, the focus is not on the code window.

User has to manually click into the code window to be able to write.

Is it possible to have a keyboard shortcut to focus on the code window, just like we have a keyboard shotcut (Ctrl + Enter) to submit our solution and to launch the next challenge?

It feels annoying sometimes to use mouse just to get focus when all the actions are happening via keyboard.

Thanks in advance.
Prasoon

**Comment by raisedadead** [comment]
@benmcmahon100 What do you say?

**Comment by dwd2010** [comment]
I think that idea is good to me!

**Comment by raisedadead** [comment]
How about <kbd>Ctrl/Cmd</kbd> + <kbd>Shift</kbd>+<kbd>E</kbd> ?

**Comment by raisedadead** [comment]
Anyone interested in working on this, check these files:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework/bindings.js
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework/create-editor.js

**Comment by benmcmahon100** [comment]
While I'm theory this can be done, there's an on-going issue with the code mirror cursor bugging out. The editor does auto focus on page loads but there's a bug that prevents round. There are a few issues open around this that would still be open.

**Comment by ttymed** [comment]
Hi, I would like to work on this if you guys are alright with that.

**Comment by raisedadead** [comment]
@ttymed Go ahead, help wanted issues are open to all.
Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).
