### ISSUE TITLE
challenge task cannot be accomplished with tests provided

### ISSUE THREAD

**Issue by marekpetak** [FreeCodeCamp/FreeCodeCamp#8195]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%0A%20%20var%20reversed%20%3D%20str.toLowerCase().replace(%2F%5CW%2Fg%2C%22%22).split(%22%22).reverse().join(%22%22)%3B%0A%20%20var%20original%20%3D%20str.toLowerCase().replace(%2F%5CW%2Fg%2C%22%22)%3B%0A%20%20%0A%20%20%2F%2Fconsole.log(%22%20reversed%20%3D%3E%20%22%20%2B%20reversed)%3B%0A%20%20%0A%20%20return%20reversed%20%3D%3D%3D%20original%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

this challenge clearly states: **You'll need to remove all non-alphanumeric characters**   but the last value passed in a test is **palindrome("0_0 (: /-\ :) 0-0")** which has non-alfanumeric characters in ...

Is this intentional or just a bug ???

**Comment by erictleung** [comment]
@marekpetak this is intentional and there shouldn't be anything wrong with the tests. 

> You'll need to remove all non-alphanumeric characters (**punctuation, spaces and symbols**)...

If you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) first before reporting a bug. Happy coding!
