### ISSUE TITLE
What's wrong with this exercise?

### ISSUE THREAD

**Issue by dac2205** [FreeCodeCamp/FreeCodeCamp#8197]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function dropElements(arr, func) {
  // Drop them elements.
  var x = [];
  
  for (var i = 0; i < arr.length; i++) {
    if (func(arr[i])) {
      x.push(arr[i]);    
    }
  }
  return x;
}

var x = dropElements([1, 2, 3, 9, 2], function(n) {return n > 2;});

console.log(x);
```

**Comment by theflametrooper** [comment]
@dac2205 If you are stuck with a challenge, please ask questions in the [Help Room](https://gitter.im/FreeCodeCamp/Help). Closing as not an issue with the site. Happy coding!
