### ISSUE TITLE
Locked out of account

### ISSUE THREAD

**Issue by jmargolisvt** [FreeCodeCamp/FreeCodeCamp#8198]
#### Challenge Name
https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description

I submitted a working solution to the Fibonacci challenge.  I got the success message, clicked ctrl-enter to continue, then the server just hung.  If I go to the challenge in an incognito window, I can complete it with the same solution and it moves on successfully.  If I try to login again in that same window, using Github Oauth, again it hangs.  It eventually tells me **Error 504 Ray ID: 29622a72950b472e • 2016-04-19 17:45:40 UTC**.  I can't login nor can I view any of my logged in pages even though I am logged in in my original browser window.  I'm effectively locked out of my account.

#### Browser Information

* Browser Name, Version: Chrome Version 50.0.2661.75 (64-bit), Firefox 45.0.2
* Operating System: OSX 10.9.5
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot
<img width="1280" alt="screen shot 2016-04-19 at 1 50 42 pm" src="https://cloud.githubusercontent.com/assets/1338941/14649615/ddb26834-0635-11e6-93a1-4f1a26efab7a.png">

**Comment by jmargolisvt** [comment]
And after 20 minutes of lockout, by the time I finish writing up the issue... i'm back in.  <shrug>

**Comment by sludge256** [comment]
This was an issue caused by the DB server receiving a large spike in activity. Things seem to be back in working order. Thanks for the patience!

**Comment by micos7** [comment]
Same thing here I cant reach the site since a few days.
