### ISSUE TITLE
Change language on local installation

### ISSUE THREAD

**Issue by 5k9m** [FreeCodeCamp/FreeCodeCamp#8199]
Hi guys,

I'm currently translating parts of your awesome work into german. To have some visual feedback on my translations I installed FreeCodeCamp on my local machine and it runs perfectly. But when I'm following 8.3 of the Translations Guide ( https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Translations-Guide ) I hit a dead end. 

Point 8.3 says:
> Follow the changes shown in this commit but instead of descriptionEs and nameEs use the keys of your language (e.g descriptonFr and nameFr)

The thing is that I can't find the files mentioned in the commit ( https://github.com/FreeCodeCamp/FreeCodeCamp/commit/d36e33f3938ddd079931a5fb2bc5dc6db37667e5 ). Even when I search for the changes, I'm not able to locate the files I have to change in order to switch the language to german.

Am I simply too blind, or did something change? How can I change the language?

Thanks a lot :-)

**Comment by raisedadead** [comment]
The files seem to have moved over the time the code has changed:
Currently you can find them at:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/challenge.js
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/map/show.jade

/cc @vtamara Can you confirm, these are the files that @5k9m needs?

**Comment by BKinahan** [comment]
Going by the issue title my impression is that the question may actually be about changing the display language on FCC for viewing/testing on the local copy (though I don't know how to answer that).

**Comment by vtamara** [comment]
I updated, @5k9m please check https://github.com/pasosdeJesus/FreeCodeCamp/commit/ad584ebec449734267e6f7dc5234eeae1b240ec3
