### ISSUE TITLE
Bug in  36. Waypoint: Create a Set of Checkboxes

### ISSUE THREAD

**Issue by ShabbirK** [FreeCodeCamp/freecodecamp#820]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Even after changing the name attribute of the radio button to "personality", the checkbox requiring to do so doesn't change to green. Thanks.

![problem](https://cloud.githubusercontent.com/assets/12728955/7957372/b2c936a4-0a08-11e5-936c-3337cc265743.jpg)

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.
