### ISSUE TITLE
Odd text editor behavior in the code sheet.

### ISSUE THREAD

**Issue by beem812** [FreeCodeCamp/FreeCodeCamp#8204]
#### Challenge Name

Give a Background Color to a Div Element

#### Issue Description

On a new load of the page I click in the code area and start typing and the text appears one
row below where I clicked in at. I also have some issues where there are certain parts of the code 
text that I can't click in to or put my cursor in to.

#### Browser Information

* Browser Name, Version: chrome Version 50.0.2661.75 m.
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

https://beem132-gmail.tinytake.com/sf/NjAzNTg1XzMwMDkzNjY
That's a link to a video showing the behavior in question I know this is the screen shot section but
the video is small and short and better at showing the issue, didn't have the ability to clip it but there's no new info after 30 seconds, hope it's useful.

**Comment by erictleung** [comment]
This is a confirmed problem (#7605 and #7528) but it has to do with the code editor we use, Code Mirror. We will have to wait until they fix the problem. Sorry for the inconvenience. Closing as not an issue we can fix on our end. Happy coding otherwise!
