### ISSUE TITLE
HTML difficulty

### ISSUE THREAD

**Issue by CBlay** [FreeCodeCamp/FreeCodeCamp#8205]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%3Cdelete%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3E%3C%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3E%3Cdelay%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<delete
<h1>Hello World</h1>
><
<h2>CatPhotoApp</h2>
><delay
<p>Hello Paragraph</p>
>
```

**Comment by erictleung** [comment]
@CBlay thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
