### ISSUE TITLE
Content Security Policy issue with Non-Standard font resource

### ISSUE THREAD

**Issue by ricky0512** [FreeCodeCamp/FreeCodeCamp#8206]
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=var%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%20%3E%205%3B%0A%7D%0A)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val > 5;
}
);

```

I've done hard refresh, with resource cleaning of certain challenge in the console
I get the error msg: 
Refused to load the font 'https://www.moedict.tw/MOEDICT.ttf' because it violates the following Content Security Policy directive: "font-src *.cloudflare.com https://*.cloudflare.com *.bootstrapcdn.com *.googleapis.com *.gstatic.com https://*.bootstrapcdn.com 'self'".

**Comment by raisedadead** [comment]
I am unable to reproduce this, except that the code is incorrect as well.

But, the website/font you mention is not used at FreeCodeCamp's end, is it because of some browser extension that you may have installed? Are you using some translation plugin? or similar? These could be injecting the font to the webpage.

Try reproducing the issue in an incognito window with all extensions disabled.

**Comment by raisedadead** [comment]
Closing please feel free to comment below and let us know.

**Comment by ktajpuri** [comment]
I am still getting this issue.

![image](https://cloud.githubusercontent.com/assets/10725893/20724066/e0c12732-b692-11e6-9e24-20b1606a407a.png)

**Comment by raisedadead** [comment]
@ktajpuri your issue is different from one that's noted here, and is also normal because from the screenshot, its coming from your localhost (running fcc locally) in a development environment.

You can ignore them.
