### ISSUE TITLE
Waypoint: Create a Set of Checkboxes Error

### ISSUE THREAD

**Issue by Waterbirds** [FreeCodeCamp/freecodecamp#821]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. 
The instructions says to make the name "personality" for all inputs but for it to be correct you have to change the name of the check boxes to "trait".

![2015-06-03 19_56_34-waypoint_ create a set of checkboxes _ free code camp](https://cloud.githubusercontent.com/assets/11172727/7957506/3ecbaa98-0a2b-11e5-9014-f784123a776a.png)
The code in the picture above will not work.

![2015-06-03 20_01_39-waypoint_ create a set of checkboxes _ free code camp](https://cloud.githubusercontent.com/assets/11172727/7957527/5e5b2a96-0a2b-11e5-952e-56693b154b00.png)
The code has to be like this in order to continue.

**Comment by xubik** [comment]
Exactly the same for me

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.

**Comment by thebaconnater** [comment]
Has this issue been resolved?
I came across the same error. I changed the name to "trait", but that did not work either.

**Comment by texas2010** [comment]
@thebaconnater, this issue is old.    if you need a help with this challenge. 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
