### ISSUE TITLE
cannot figure out the Record Collection problem 

### ISSUE THREAD

**Issue by wangdejun** [FreeCodeCamp/FreeCodeCamp#8211]
Record Collection
why cannot my code pass the  test? help me please.

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup

var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: []
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));
// Only change code below this line
function updateRecords(id, prop, value){
  
  if(!value){
    return;
  }else if(prop==="album"||prop==="artist"){
     collection[id][prop] = value;
  }else if(prop==="tracks"){
     collection[id][prop].push(value);
  }else
    return;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBAA");
updateRecords(2548, "tracks", "Addicted to Love");
updateRecords(5439, "artist", "");


```

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding. and Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Happy Coding!

**Comment by wangdejun** [comment]
Wow! there is a reply really , thank you!

**Comment by raisedadead** [comment]
Did you get an answer on the help chat :wink: ?

**Comment by wangdejun** [comment]
@raisedadead  I got help from nice guys in the Help Chat Room, and I Make it! thanks!

`// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: []
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));
// Only change code below this line
function updateRecords(id, prop, value){
    if(prop!=="tracks"&&value!==""){
     collection[id][prop] = value;
    }
    if(prop=="tracks"&&value!==""){
     collection[id][prop].push(value);
    }
    if(value===""){
    delete collection[id][prop];
    }
  return collection;
}
// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");

**Comment by wangdejun** [comment]
@raisedadead I got help from some nice guys in the CHAT ROOM， and i make it ,thank you !
`// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: []
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));
// Only change code below this line
function updateRecords(id, prop, value){
    if(prop!=="tracks"&&value!==""){
     collection[id][prop] = value;
    }
    if(prop=="tracks"&&value!==""){
     collection[id][prop].push(value);
    }
    if(value===""){
    delete collection[id][prop];
    }
  return collection;
}
// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");

`

**Comment by wangdejun** [comment]
@raisedadead

 I got help from some nice guys in the CHAT ROOM， and i make it ,thank you !
```
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: []
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));
// Only change code below this line
function updateRecords(id, prop, value){
    if(prop!=="tracks"&&value!==""){
     collection[id][prop] = value;
    }
    if(prop=="tracks"&&value!==""){
     collection[id][prop].push(value);
    }
    if(value===""){
    delete collection[id][prop];
    }
  return collection;
}
// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");

```

**Comment by raisedadead** [comment]
@wangdejun Do not post any solutions in here.
