### ISSUE TITLE
auto compile/interpret causes freeze

### ISSUE THREAD

**Issue by OoLZoO** [FreeCodeCamp/FreeCodeCamp#8212]
#### Challenge Name

https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description
I missunderstood the task at first, so my function does some heavy calculation which freezes the browser due to the auto compile/interpret interface thats is provided  (chrome, ff, ie). (The code in a local file opened with any browser actually works, which shows a array containing many elements)

Since everything is frozen, I can't click on the reset button nor delete the code quickly enough to make to auto compile stop.
Everytime I open the challenge it just freeze instantly.

Is there a way to reset the code in this challenge so I can rewrite the code? 

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/15012280/14672732/07c59320-06fa-11e6-98b1-f0797ace0e06.png)

**Comment by raisedadead** [comment]
Here are two options:

- [Disable Code Auto-run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) 
- [Clear localStorage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage). 

Thanks and happy Coding!
