### ISSUE TITLE
Menu doesn't drop down correctly on video pages

### ISSUE THREAD

**Issue by RayBB** [FreeCodeCamp/FreeCodeCamp#8216]
#### Challenge Name
This happens on all of the videos pages https://www.freecodecamp.com/videos/*

#### Issue Description
When you click the menu button instead of dropping down like normal it is squished and unreadable.
See screenshot.

#### Browser Information

* Browser Name, Version:  Chrome 49
* Operating System: Android M
* Mobile, Desktop, or Tablet:  Mobile

#### Screenshot
![2016-04-18 13 53 25](https://cloud.githubusercontent.com/assets/921217/14684928/2f6b891a-0700-11e6-9d7b-3e0450ea8179.png)

**Comment by dwd2010** [comment]
@hallaathrad

**Comment by hallaathrad** [comment]
oh wow. that's sexy :) @BerkeleyTrue what do you think? bootstrap fail?

**Comment by dwd2010** [comment]
@hallaathrad @BerkeleyTrue  https://gyazo.com/b5e1083ea58c48aa40aff812f5b889a2

**Comment by hallaathrad** [comment]
That's very helpful, @dwd2010! let's see how we get this one sorted out

**Comment by augmt** [comment]
One solution could be to [wrap the NavbarBrand and Navbar.Toggle](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/9a8bc9b80e122707b72900a55ccf53cb5c7c12f0/common/app/components/Nav/Nav.jsx#L112-L113) in a Navbar.Header, though that would throw off the navbar's margins and would require some messing around with the styling.

Or a Clearfix could be added right after the Navbar.Toggle for small and extra-small devices, but some media queries in [client/less/main.less](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/9a8bc9b80e122707b72900a55ccf53cb5c7c12f0/client/less/main.less) would have to be amended.

I / anyone can submit a PR for whichever option seems best.

**Comment by hallaathrad** [comment]
Personally, I'd rather we sort issues for specific (i.e. small) devices rather than modifying the whole thing for everyone,  unforeseeably risking breaking it for all.

**Comment by dwd2010** [comment]
@hallaathrad, Odd, I test that page on Chrome and Safari on my iPhone 6. it is fine to me. 
probably you are right about specific devices.

**Comment by charlottetan** [comment]
I can repro this on the live site, but am unable to repro when building on localhost, looks like it has been fixed?

**Comment by atjonathan** [comment]
This has been solved in `staging`. Thanks for the heads up @charlottetan 😜
