### ISSUE TITLE
Sum All Numbers in a Range: Array.reduce() seems unnecessary

### ISSUE THREAD

**Issue by leakvoid** [FreeCodeCamp/FreeCodeCamp#8217]
Challenge [Sum All Numbers in a Range](https://www.freecodecamp.com/challenges/sum-all-numbers-in-a-range#?solution=function%20sumAll(arr)%20%7B%0A%20%20var%20max%20%3D%20Math.max(arr%5B0%5D%2C%20arr%5B1%5D)%3B%0A%20%20var%20min%20%3D%20Math.min(arr%5B0%5D%2C%20arr%5B1%5D)%3B%0A%20%20%0A%20%20return%20(max%20%2B%20min)%20*%20(max%20-%20min%20%2B%201)%20%2F%202%3B%0A%7D%0A%0AsumAll(%5B1%2C%204%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36</code>.
Solution below without suggested Array.reduce() is simpler, and so I don't think this problem shows usefulness of Array.reduce() method well:

My code:
```javascript
function sumAll(arr) {
  var max = Math.max(arr[0], arr[1]);
  var min = Math.min(arr[0], arr[1]);
  
  return (max + min) * (max - min + 1) / 2;
}

sumAll([1, 4]);

```

**Comment by erictleung** [comment]
@leakvoid thanks for the issue. But the MDN links are just suggested links/commands to look into to help solve the problem. The use of a mathematical formula to sum numbers in a range isn't against the rules :wink: Closing as not an issue with the site. Happy coding!
