### ISSUE TITLE
Waypoint: Create a Set of Checkboxes

### ISSUE THREAD

**Issue by willieschen** [FreeCodeCamp/freecodecamp#822]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

One of requests is "Give your radio buttons the name attribute of "personality"."
but it should be "Give your Checkboxes the name attribute of "personality"." to match waypoint

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.
