### ISSUE TITLE
H1 element isn't pink

### ISSUE THREAD

**Issue by Nikitaw99** [FreeCodeCamp/FreeCodeCamp#8221]
#### Challenge Name
[Prioritize one style over another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another).

#### Issue Description
The `h1` isn't pink for some reason.
1. Create CSS class `pink-text`.
2. Set the class to have `color: pink`.
3. Give the `h1` element the class `pink-text`.

#### Browser Information

* Browser Name, Version: Chrome 49.0.2623.105
* Operating System: Android 4.4.2; SM-T531 Build/KOT49H
* Mobile, Desktop, or Tablet: Samsung (Tablet)

#### Your Code

```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>
```

#### Screenshot
![Imgur](http://i.imgur.com/WMwT9XL.jpg)

**Comment by sludge256** [comment]
Try deleting some of the spaces that you have in front of
```html
.pink-text {
  color: pink;
}
```

**Comment by Nikitaw99** [comment]
@sludge256 I tried, but nothing actually happened...

**Comment by sludge256** [comment]
Does it work if you have the `pink-text` CSS all in one line?
Do you mind posting the link to the code you have in the screenshot?

**Comment by Nikitaw99** [comment]
@sludge256 
> link to the code

What link?

**Comment by sludge256** [comment]
@Nikitaw99 The URL changes as you type code into the editor. I'd like that URL for code analysis.

**Comment by Nikitaw99** [comment]
[Here](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%C2%A0%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A).

**Comment by sludge256** [comment]
@Nikitaw99 Go the beginning of line 8, go right two spaces, then press backspace.

**Comment by Nikitaw99** [comment]
@sludge256 Thanks for solving the problem.

**Comment by sludge256** [comment]
For reference:
![diff](http://i.imgur.com/4jUryxQ.png)
https://www.diffnow.com/?report=ah4dc

Related: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753

**Comment by abood4556** [comment]
Your <style> should have a pink-text CSS class that changes the color.
<style>
  body {
    background-color: black;
    font-family: monospace;
    color: pink;
  }
  pink-text{
    color:pink;
  }

</style>
<h1 class="pink-text">Hello World!</h1>
<style>

**Comment by abood4556** [comment]
please solve this problem Your <style> should have a pink-text CSS class that changes the color.

**Comment by casandracarrizales** [comment]
<style>
  body {
    background-color: black;
    font-family: monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }

  .blue-text {
    color: blue;
  }
</style>
<h1 class="pink-text blue-text">Hello World!</h1>

**Comment by casandracarrizales** [comment]
<img width="433" alt="Screen Shot 2020-08-19 at 10 38 03 PM" src="https://user-images.githubusercontent.com/60071014/90714162-aa50f880-e26c-11ea-9b15-582ab9685fad.png">

**Comment by scoaband** [comment]
Try using anther browser. Sometime browser tend to cache pages.
