### ISSUE TITLE
Roman Numeral Converter: solution is lost

### ISSUE THREAD

**Issue by leakvoid** [FreeCodeCamp/FreeCodeCamp#8224]
Challenge [Roman Numeral Converter](https://www.freecodecamp.com/challenges/roman-numeral-converter) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36</code>.
1. I wrote solution for 'Roman Numeral Converter', then I submitted it by pressing 'ctrl + enter' two times (all passed)
2. I was curious how others solved it; so I viewed different user solution for this problem without executing it ( freecodecamp.com/user_name    ---> view solution )
3. Now I have that user solution instead of mine
4. this screenshot shows another abnormality http://i.imgur.com/r41LR8Z.png

NOT My code:
```javascript
function convert(num) {
  
  var result = "";
  
  while (num > 0) {
    if (num >= 1000) {
      result += "M";
      num -= 1000;
    } else if (num > 900) {
      result += "CM";
      num -= 900;
    } else if (num >= 500) {
      result += "D";
      num -= 500;
    } else if (num > 400) {
      result += "CD";
      num -= 400;
    } else if (num >= 100) {
      result += "C";
      num -= 100;
    } else if (num > 90) {
      result += "XC";
      num -= 90;
    } else if (num >= 50) {
      result += "L";
      num -= 50;
    } else if (num > 40) {
      result += "XL";
      num -= 40;
    } else if (num > 10) {
      result += "X";
      num -= 10;
    } else if (num == 9) {
      result += "IX";
      num -= 9;
    } else if (num >= 5) {
      result += "V";
      num -= 5;
    } else if (num == 4) {
      result += "IV";
      num -= 4;
    } else {
      result += "I";
      num -= 1;
    }
  }
  
 return result;
}

convert(36);

```

**Comment by theflametrooper** [comment]
@leakvoid That abnormality is because you have already passed the challenge beforehand.

**Comment by raisedadead** [comment]
@leakvoid 

I have this code on your profile:
function convertToRoman(num) {
  if( num > 3999 )
    return "Number is too big";
  
  var arr = [[1000, 'M'],
             [500, 'D'],
             [100, 'C'],
             [50, 'L'],
             [10, 'X'],
             [5, 'V'],
             [1, 'I']];
  
  var result = [];
  
  for( var i = 0; i < arr.length; i += 2 ) {
    
    var base = Math.floor( num / arr[i][0] );      
    num -= arr[i][0] * base;
    
    switch(base) {
      case 9:
        result.push( arr[i][1] );
        result.push( arr[i - 2][1] );
        break;
      case 8:
        result.push( arr[i - 1][1] );
        result.push( arr[i][1] );
        result.push( arr[i][1] );
        result.push( arr[i][1] );
        break;
      case 7:
        result.push( arr[i - 1][1] );
        result.push( arr[i][1] );
        result.push( arr[i][1] );
        break;
      case 6:
        result.push( arr[i - 1][1] );
        result.push( arr[i][1] );
        break;
      case 5:
        result.push( arr[i - 1][1] );
        break;
      case 4:
        result.push( arr[i][1] );
        result.push( arr[i - 1][1] );
        break;
      case 3:
        result.push( arr[i][1] );
        result.push( arr[i][1] );
        result.push( arr[i][1] );
        break;
      case 2:
        result.push( arr[i][1] );
        result.push( arr[i][1] );
        break;
      case 1:
        result.push( arr[i][1] );
        break;
    }
  }
  
  return result.join("");
}

convertToRoman(36);

If you visit your profile and check:
https://www.freecodecamp.com/leakvoid
![image](https://cloud.githubusercontent.com/assets/1884376/14706711/fb9c9208-07dd-11e6-81bb-3b93811e09d8.png)

This is different from the one submitted in the issue.
So believe that your code is not lost at all, can you confirm.

**Comment by raisedadead** [comment]
Secondly when you are logged in and visit anyone else's challenge solution, it wont be updated to your profile until you submit that as well (<kbd>Ctrl</kbd> + <kbd>Enter</kbd>) Twice not once.

I don't see it as updated as well, concluding that you prior submission is there intact.

**Comment by leakvoid** [comment]
> So believe that your code is not lost at all, can you confirm.

Yes, after i visited 'View solution' through my own profile, it went back to normal.

> Secondly when you are logged in and visit anyone else's challenge solution, it wont be updated to your profile until you submit that as well (Ctrl + Enter) Twice not once.

Makes sense.
1) As I understand, whenever I visit another person challenge, my own buffer for current challenge gets modified (https://www.freecodecamp.com/challenges/challenge-name)
2) And to get my own solution back, I should revisit https://www.freecodecamp.com/my-profile and go to  'View solution' (https://www.freecodecamp.com/challenges/challenge-name?solution=...)

Just to be sure, between step (1) and (2), this sort of behavior is normal: http://i.imgur.com/FLaLUq0.png

**Comment by raisedadead** [comment]
Yes this behavior is normal. The solutions are stored in the DB with your profile and are additionally stored in your browser (localStorage).

When you visit any solution page others or your the local storage gets updated.
The database will be updated only by doing run test and move to next, i.e (`Ctrl + Enter` twice).

I recommend that you use incognito mode to visit others solutions. (`right click > open link in incognito mode`)

**Comment by raisedadead** [comment]
Closing as resolved
