### ISSUE TITLE
Solution is  not accepted even if the code returns the correct answer

### ISSUE THREAD

**Issue by mkanzit** [FreeCodeCamp/FreeCodeCamp#8227]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=function%20largestOfFour(arr)%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20var%20maxi%20%3D%200%3B%0A%20%20var%20maxe%20%3D%200%3B%0A%20%20var%20lrg%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20for(var%20i%3D0%3B%20i%20%3C%20arr.length%20%3B%20i%2B%2B)%20%7B%0A%20%20%20%20for(var%20j%3D0%20%3B%20j%20%3C%20arr%5Bi%5D.length%20%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if(arr%5Bi%5D%5Bj%5D%20%3E%20maxi)%0A%20%20%20%20%20%20%20%20maxi%20%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20if(maxi%20%3E%20maxe)%20%7B%0A%20%20%20%20%20%20maxe%20%3D%20maxi%3B%0A%20%20%20%20%20%20lrg%20%3D%20arr%5Bi%5D.slice()%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%20%20%0A%20%20return%20lrg%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function largestOfFour(arr) {
  // You can do this!
  var maxi = 0;
  var maxe = 0;
  var lrg = [];
  
  for(var i=0; i < arr.length ; i++) {
    for(var j=0 ; j < arr[i].length ; j++) {
      if(arr[i][j] > maxi)
        maxi = arr[i][j];
    }
    if(maxi > maxe) {
      maxe = maxi;
      lrg = arr[i].slice();
    }
  }
    
  return lrg;
}

largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]]);
// return [1000000, 1001, 857, 1]

/*
i've noticed that the indications (tests to pass) was also wrong:
ex:

largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]) 
it said it should return [27,5,39,1001].
but the real result is [1000, 1001, 857, 1]

Thanks 
*/
```

**Comment by raisedadead** [comment]
I am afraid that the logic you have is not correct, I checked on the console (Chrome DevTools), the output is not as expected.

![image](https://cloud.githubusercontent.com/assets/1884376/14707352/f862444e-07e1-11e6-93d7-10bf94fc47a1.png)

Here it should have returned:
[9, 35, 97, 1000000]

Closing this as not a issue on the website. 
Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!

**Comment by mkanzit** [comment]
Hi, @raisedadead 

Thanks for the fast response
i think i've misunderstood something in the sentence
that's why i've the incorrect the answer

anyway, thanks a lot man
