### ISSUE TITLE
Task don't closed what i doing wrong? Result right.

### ISSUE THREAD

**Issue by Hygo94** [FreeCodeCamp/FreeCodeCamp#8228]
Challenge [Symmetric Difference](https://www.freecodecamp.com/challenges/symmetric-difference#?solution=function%20sym(args)%20%7B%0A%20%20args%20%3D%20%5B%5D%3B%0A%20%20for(i%3D0%3B%20i%3Carguments.length%3B%20i%2B%2B)%7B%0A%20%20%20%20args%20%3D%20args.concat(%5Barguments%5Bi%5D%5D)%3B%0A%20%20%7D%0A%20%20%0A%20%20var%20result%20%3D%20args%5B0%5D%3B%0A%20%20%0A%20%20for(i%3D1%3B%20i%3Cargs.length%3B%20i%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20var%20temp%20%3D%20%5B%5D%3B%0A%20%20%20%20%20%20temp.push(check(result%2Cargs%5Bi%5D))%3B%0A%20%20%20%20%20%20temp.push(check(args%5Bi%5D%2Cresult))%3B%0A%20%20%20%20%20%20result%20%3D%20temp.reduce(function(a%2Cb)%7B%0A%20%20%20%20%20%20%20%20return%20a.concat(b)%3B%0A%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20for(i%3D0%3B%20i%3Cresult.length%3B%20i%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20if(result%5Bi%5D%3D%3Dresult%5Bi%2B1%5D)%0A%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20delete%20result%5Bi%5D%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20result%20%3D%20result.filter(filt).sort()%3B%0A%20%20%0A%20%20return%20result%3B%0A%7D%0A%0A%0Afunction%20check(firstArr%2C%20secondArr)%0A%7B%0A%20%20var%20temp%20%3D%20%5B%5D%3B%0A%20%20%20%20%20%20for(j%20%3D%200%3B%20j%3CfirstArr.length%3B%20j%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20if(secondArr.indexOf(firstArr%5Bj%5D)%3C0)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20temp.push(firstArr%5Bj%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20return%20temp%3B%0A%7D%0A%0Afunction%20filt(value)%7B%0A%20%20return%20value!%3D%3Dnull%3B%0A%7D%0A%0Asym(%5B1%2C%202%2C%203%2C3%2C%203%2C%203%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D)%3B%20%2F%2F3%2C%204%2C%205%0A%2F%2Fsym(%5B1%2C%202%2C%205%5D%2C%20%5B2%2C%203%2C%205%5D%2C%20%5B3%2C%204%2C%205%5D)%3B%20%2F%2F%201%2C%204%2C%205%0A%2F%2Fsym(%5B1%2C%201%2C%202%2C%205%5D%2C%20%5B2%2C%202%2C%203%2C%205%5D%2C%20%5B3%2C%204%2C%205%2C%205%5D)%3B%20%2F%2F%201%2C%204%2C%205%0A%2F%2Fsym(%5B3%2C%203%2C%203%2C%202%2C%205%5D%2C%20%5B2%2C%201%2C%205%2C%207%5D%2C%20%5B3%2C%204%2C%206%2C%206%5D%2C%20%5B1%2C%202%2C%203%5D)%3B%20%2F%2F2%2C%203%2C%204%2C%206%2C%207%0A%2F%2Fsym(%5B3%2C%203%2C%203%2C%202%2C%205%5D%2C%20%5B2%2C%201%2C%205%2C%207%5D%2C%20%5B3%2C%204%2C%206%2C%206%5D%2C%20%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%203%2C%209%2C%208%5D%2C%20%5B1%5D)%3B%20%0A%2F%2F%201%2C%202%2C%204%2C%205%2C%206%2C%207%2C%208%2C%209%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sym(args) {
  args = [];
  for(i=0; i<arguments.length; i++){
    args = args.concat([arguments[i]]);
  }
  
  var result = args[0];
  
  for(i=1; i<args.length; i++)
    {
      var temp = [];
      temp.push(check(result,args[i]));
      temp.push(check(args[i],result));
      result = temp.reduce(function(a,b){
        return a.concat(b);
      });
    }
  
  for(i=0; i<result.length; i++)
    {
     if(result[i]==result[i+1])
       {
         delete result[i];
       }
    }
  result = result.filter(filt).sort();
  
  return result;
}


function check(firstArr, secondArr)
{
  var temp = [];
      for(j = 0; j<firstArr.length; j++)
        {
          if(secondArr.indexOf(firstArr[j])<0)
            {
              temp.push(firstArr[j]);
            }
        }
  return temp;
}

function filt(value){
  return value!==null;
}

sym([1, 2, 3,3, 3, 3], [5, 2, 1, 4]); //3, 4, 5
//sym([1, 2, 5], [2, 3, 5], [3, 4, 5]); // 1, 4, 5
//sym([1, 1, 2, 5], [2, 2, 3, 5], [3, 4, 5, 5]); // 1, 4, 5
//sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3]); //2, 3, 4, 6, 7
//sym([3, 3, 3, 2, 5], [2, 1, 5, 7], [3, 4, 6, 6], [1, 2, 3], [5, 3, 9, 8], [1]); 
// 1, 2, 4, 5, 6, 7, 8, 9

```

![image](https://cloud.githubusercontent.com/assets/14911321/14715511/5eaeadb2-07e9-11e6-9f0b-ece65cf0e03e.png)

**Comment by erictleung** [comment]
@Hygo94 thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
