### ISSUE TITLE
Does not give credit for correct answer.

### ISSUE THREAD

**Issue by orkist** [FreeCodeCamp/freecodecamp#823]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This will work   <label><input type='radio' name="personality> Indoor</label>
However the correct answer   <label><input type='radio' name='personality'> Indoor</label>
does not work

![image](https://cloud.githubusercontent.com/assets/5121859/7962045/35cf866e-09d9-11e5-89d7-6f0b944e015c.png)

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.
