### ISSUE TITLE
Help needed please?

### ISSUE THREAD

**Issue by Gaozzie8** [FreeCodeCamp/FreeCodeCamp#8230]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%20%22red-text%22%3E%20Kitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%0A%3Cp%3E%20Puur%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20subbather%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class= "red-text"> Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


<p> Puur jump eat the grass rip the couch scratched subbather, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by sludge256** [comment]
You have a typo in your "kitty ipsum" text.

Please use the `Help` button in the future and ask in the chat.
GitHub issues are not for code issues. If you can get confirmation that there is a bug then feel free to post here.

**Comment by siadevelopment** [comment]
What's the problem with the exercise?
