### ISSUE TITLE
I've found an open source project. Now what?

### ISSUE THREAD

**Issue by sunnycal** [FreeCodeCamp/FreeCodeCamp#8231]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by dwd2010** [comment]
This is not issue. Sorry I have to close this issue.  You could ask people at gitter, if you want to ask a question. https://gitter.im/FreeCodeCamp/FreeCodeCamp
