### ISSUE TITLE
New favicons for freecodecamp.com

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8233]
![](https://www.evernote.com/l/Ar8qgTOzluBBfrNeL96-7gaocJZhPGWd28wB/image.png)

We briefly used a more "olive" color when we were doing our January redesign, and it looks like we never updated our favicons. We need to create favicons that use #006400 (dark green) in the appropriate sizes.
I can add them to s3 once they're done. They should have the same file names as the current ones, which are listed here:

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/public/favicons.html

**Comment by BKinahan** [comment]
Is there an original vector graphic file for the icon available to use for these?

**Comment by BerkeleyTrue** [comment]
@BKinahan Check here => https://github.com/FreeCodeCamp/FCCAssets/tree/master/Logos%20and%20Covers

**Comment by BKinahan** [comment]
Thanks @BerkeleyTrue, I'll get going on this with the assumption that the dark green color mentioned should be `#006400` rather than an issue about returning the largest numbers in arrays :)

**Comment by BKinahan** [comment]
Images complete and available here: https://github.com/BKinahan/fccfavicons
... with filenames matching https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/public/favicons.html as requested.

**Comment by QuincyLarson** [comment]
@BKinahan Awesome - I've uploaded these and CloudFlare should start using them soon. One thing I noticed is the files seem quite large. Could you compress these using something like http://compresspng.com/ or a local file compression tool and update the repo? I think for example 16x16 favicons should be closer to 400 bytes (not several kilobytes like they are now)

**Comment by BKinahan** [comment]
@QuincyLarson Ah ha, a small oversight. Done, and replaced on the repo linked above.

**Comment by QuincyLarson** [comment]
@BKinahan Awesome! Thank you again for your fast help with this. Thanks to you, I'm marking this issue closed! :)
