### ISSUE TITLE
WIKI : Bad solution code for the "Profile lookup" challenge

### ISSUE THREAD

**Issue by n00bax** [FreeCodeCamp/FreeCodeCamp#8235]
#### Challenge Name

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Checkpoint-Profile-Lookup#code-solution

#### Issue Description

The code solution in the profile lookup challenge wiki page is wrong(I think), I added the correct code below with an explanation inside comments in front of the modified line.

#### Your Code

```js
for (var x = 0; x < contacts.length; x++){
    if (contacts[x].firstName === firstName) {
        if (contacts[x].hasOwnProperty(prop)) {  //instead of contacts[x][prop] because in that case it would return the value of that prop and if that prop was e.g 0  the if statement wouldn't work has expected.
            return contacts[x][prop];
        } else {
            return "No such property";
        }
    }
}
return "No such contact";

```

**Comment by BerkeleyTrue** [comment]
Please open this issue in the wiki repository. Thanks.
https://github.com/freecodecamp/wiki
Happy Coding
