### ISSUE TITLE
No name displayed on front-end certificate

### ISSUE THREAD

**Issue by ashi2014** [FreeCodeCamp/FreeCodeCamp#8238]
#### Challenge Name
Claim your front-end development certificate

#### Issue Description
After going through the steps to claim my front-end certificate, my name does not show up on the certificate: https://www.freecodecamp.com/ashi2014/front-end-certification

#### Browser Information

* Browser Name, Version: Chrome v49
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/7401767/14731891/126401fc-080a-11e6-8d54-e1e5a43dcd10.png)

**Comment by raisedadead** [comment]
@ashi2014 You ** do not** have a name associated with your GitHub profile.

We need that property of a user to generate the name.

Please update a name on your GitHub profile here:
https://github.com/settings/profile

Then login to FreeCodeCamp.com and go to to your profile page:
https://www.freecodecamp.com/ashi2014 > Update your Settings > Update Portfolio from Github.

Ensure that your profile page at /ashi2014 displays a name.
Then check again by claiming your certificate.

If this does not work, send an email to team@freecodecamp.com leave a comment below.
We will try to sort this.

**Comment by ashi2014** [comment]
This worked, thank you!

**Comment by puneet222** [comment]
Thanks Alot

**Comment by ankitgaurav** [comment]
I am having the same problem with my certificate https://www.freecodecamp.com/ankitgaurav/front-end-certification
I have followed all the steps mentioned by @raisedadead 
Still the problem persists. Help please.

**Comment by ankitgaurav** [comment]
As I can see from inspecting the view, the certificate image is just the template of the certificate with no name, certificate date or link in it.
And these are being shown using a small script that calculates the window width and positions the mentioned texts over the image.

As such, when downloading the certificate or sharing the page on twitter etc, the certificate snippet is just a blank template, and also an embarassment. :grin: 

Please take notice.

**Comment by raisedadead** [comment]
@ankitgaurav thanks for reporting, apologizes for your inconvenience.
Since your issue is bit different, do you mind creating a new issue with the same comments as above?

Also it would be awesome if you could help us with some screenshots of the certs, and the error that you are seeing in the console.

thanks.

**Comment by ankitgaurav** [comment]
Yeah sure. I was only going to create the issue before I was warned not to do so without checking if there exists a similar one.
From the README, I also saw don't create an issue without any third-party confirmation.

So, I am filing the issue now. Thanks
