### ISSUE TITLE
This is not going threw next one and shows error 

### ISSUE THREAD

**Issue by prabsW** [FreeCodeCamp/FreeCodeCamp#8239]
Challenge [Create Bootstrap Wells](https://www.freecodecamp.com/challenges/create-bootstrap-wells#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%3C%2Fdiv%3E%0A%20%20%20%20%20%20%3Cdiv%20calss%3D%22well%22%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20calss%3D%22well%22%3E%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6"></div>
      <div calss="well">
    </div>
    <div class="col-xs-6">
      <div calss="well"></div>
    </div>
  </div>
</div>

```

**Comment by prabsW** [comment]
![error](https://cloud.githubusercontent.com/assets/4496364/14731952/1fea09e0-0899-11e6-82a0-415cb9ae548f.jpg)

**Comment by prabsW** [comment]
Turns out im dyslexic. :(

**Comment by zerofour** [comment]
The code should read:

`<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">



      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">



      </div>
    </div>
  </div>
</div>
`
