### ISSUE TITLE
"name" field looking for incorrect label 

### ISSUE THREAD

**Issue by brianamarie** [FreeCodeCamp/freecodecamp#824]
Challenge http://www.freecodecamp.com/challenges/waypoint-clean-up-your-form-using-linebreaks has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

When following the directions and putting the "name" trait set to "personality", it doesn't pass. The first checkbox needs the name to be "trait" to pass.

**Comment by QuincyLarson** [comment]
Thank you for noticing this! I'm pushing a fix for this momentarily.
