### ISSUE TITLE
Check for Palindromes & Title Case a Sentence > Two other steep learning curves

### ISSUE THREAD

**Issue by allenhsieh** [FreeCodeCamp/FreeCodeCamp#8243]
Hello All,

I posted a similar message for another exercise and it seemed like a useful discussion popped out of it. Though, again apologies if this isn't the appropriate area for this.  

I am having an incredibly difficult time with the algorithm exercises:
https://www.freecodecamp.com/challenges/check-for-palindromes
https://www.freecodecamp.com/challenges/title-case-a-sentence

I know there are four RegEx exercises at the end of Basic Javascript:
https://www.freecodecamp.com/challenges/invert-regular-expression-matches-with-javascript
https://www.freecodecamp.com/challenges/find-whitespace-with-regular-expressions
https://www.freecodecamp.com/challenges/find-numbers-with-regular-expressions
https://www.freecodecamp.com/challenges/sift-through-text-with-regular-expressions

And I also understand at a certain point the gloves will be off and we will be expected to use Read-Search-Ask methodology. Given all that, I feel like other students and myself are pretty lost when it comes to these exercises. I've skipped them for now since I want to be able to write my code myself and understand how to do it.

I've looked at the answers in the wiki:
https://github.com/freecodecamp/freecodecamp/wiki/algorithm-check-for-palindromes
and aside from knowing that the capital W selects anything that is not a letter (thanks to the inversion exercise) I have no idea what any of the answers do.

Would a more thorough progression of exercises dealing with RegEx be possible? 

Thank you,
Allen

Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript
function palindrome(str) {
  var newstr = str.toLowerCase();
  var reverse = newstr.reverse();

  return true;
}



palindrome("eye");

```

**Comment by JilaMK64** [comment]
Your idea is ok for one word, but for sentence with few words is not. Problem are spaces beetwen words

**Comment by theflametrooper** [comment]
I think it's a good idea to maybe add some more regex based challenges. Or at least make campers more confident with it.

**Comment by allenhsieh** [comment]
Hi @JilaMK64 . Sorry for the confusion, I was not asking for help on my code (that was just gibberish as a placeholder), it is a follow up to my earlier discussion question:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8207

I have unfortunately lost a lot of steam and hit a wall in my learning. There was a pretty steep curve once I got to the algorithms. As I wrote in Gitter: everything up until the algorithms has been smooth sailing. I am able to do about 1/3 them completely on my but for the others I have had to peek at how to do them on the FCC wiki or through Googling. For the ones I'm stuck on and needed to check wiki/google to solve, when I peeked at possible solutions, 1/3 I understand the logic behind but would never have thought up the answer (or vice versa). The other 1/3 I don't understand the logic nor answer at all. Since I don't find it useful in learning to copy someone else's code, I have not used those answers and I'm essentially stuck.

 I'll be taking a break from Free Code Camp and trying to learn a bit about RegEx on Lynda and just general JavaScript on CodeAcademy. Hopefully something will finally click where I am able to jump back in once again, full force though I won't lie, it is pretty disheartening right now.

**Comment by JilaMK64** [comment]
Hi @allenhsieh 
Visit www.w3schools.com . They have a lot of JS practical examples, so it is worth to visit them. On tutorials point you have good beginner' s tutorials.

Good luck, and go back on free CodeCamp :-)

**Comment by calicode** [comment]
Regular expressions are very tricky especially when you are starting out. 

https://regex101.com/ is a great way to experiment with regexps before trying them in code. Make sure to set language to 'Javascript' on the left. 

Also familiarizing yourself with the differences between the String methods 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search

**Comment by mytreasures** [comment]
![image](https://cloud.githubusercontent.com/assets/20458399/17105764/2880160a-52bb-11e6-9881-438ed713e7e6.png)

**Comment by jfkirkpatrick** [comment]
I'm lost!!  I get the "ReferenceError: andCount is not defined".  Where did andCount come from and how is it used.  I created the var andCount and that did not make a difference.

var test = (function() {
  var testString = "Ada Lovelace and Charles Babbage designed the first computer and the software that would have run on it.";
  var expressionToGetSoftware = /software/gi;

  // Only change code below this line.
  var andCount = 0;
  var expression = /and/gi;
 
  // Only change code above this line.

  return testString.match(expression).length;
})
();(function()
    {  return test;}
   )();

I went of the JavaScript Help Forum without and result.
Any suggestion?
John

**Comment by jfkirkpatrick** [comment]
I started this course initially in November 2015 but had to stop while undergoing chem treatment.  I am now repeating exercises with code from November 2015.  When I did a reset and ctrl +F5, it cleared the code to current which included the variablr andCount.  Problem solved.  On to the next exercise.  John
