### ISSUE TITLE
Invalid Selector Passes - Change Text Inside an Element Using jQuery

### ISSUE THREAD

**Issue by Brian13206** [FreeCodeCamp/FreeCodeCamp#8248]
Challenge [Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(target4).html(%22%3Cem%3E%23target4%3C%2Fem%3E%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $(target4).html("<em>#target4</em>");  <!--This should not have passed-->
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by Brian13206** [comment]
If challenge was looking for .text   the code would be fine.  With .html the code above should NOT have passed.

**Comment by sludge256** [comment]
The tags would be rendered as text if using `.text()` was the correct answer.

**Comment by erictleung** [comment]
@Brian13206 I'm not understanding the concern. The challenge asks to use the `.html` code to complete the challenge and your code correctly uses the `.html` method. Are you pointing at `$(target4)` and how this shouldn't be able to target the button at all?

**Comment by raisedadead** [comment]
@Brian13206 Closing as stale. 

Please clarify in the comments below if you are not clear on this challenges instruction.

**Comment by Brian13206** [comment]
To claify,inaddition to the correct procedure ...an INCORRECT procedure will pass as well,which should have errored. I did and do understand the instructions. I was pointing out that passing what should have not passed might not be the best teaching method.

**Comment by raisedadead** [comment]
Okay, this is still not clear. :confused: 

@erictleung says:
> The challenge asks to use the .html code to complete the challenge and **your code** correctly **uses **the **.html** method

The tests state:
> Make sure you are using .html() and **not **.text()

You state:
> If challenge was looking for .text the code would be fine. **With .html the code** above should **NOT **have passed.

So are you stating that **.html** is NOT supposed to be used here? Meaning instructions are incorrect?

**Comment by Brian13206** [comment]
I ...don't enough to argue this..if you look at the code I said should not have passed(but did)..and say that that is also correct..I simply d



I stand by my original post.. I don't care enough to argue about a free program

**Comment by Brian13206** [comment]
Marking 2+2=5 as correct is a hole in the codes logic...you answer to that is well it asked you to add 2+2.....

**Comment by raisedadead** [comment]
@erictleung
I am afraid I now get what the issue creator actually meant, after checking your comment.

> `$(target4).html("<em>#target4</em>");`

The tests should check this.

**Comment by Saurabh-Bishnoi** [comment]
$("#target4").html("<em>#target4</em>");

do like this

**Comment by Saurabh-Bishnoi** [comment]
$("#target4").html("<em>#target4</em>");

do like this

**Comment by bkayaarda** [comment]
$(#target4).html("<em>#target4</em>"); 

add #

**Comment by Brian13206** [comment]
Ok...guys. I know how the correct code went. Thanks anyways..if you re-read the op you'll see that it was because incorrect code would also pass.

**Comment by theflametrooper** [comment]
@Brian13206 @Saurabh-Bishnoi @bkayaarda Thanks, you are correct!
