### ISSUE TITLE
Wikipedia link does not open in new tab.

### ISSUE THREAD

**Issue by rasheinstein** [FreeCodeCamp/freecodecamp#825]
Challenge http://www.freecodecamp.com/challenges/bonfire-map-the-debris has an issue. When you click on the wikipedia link, it does not direct to a new tab. Minor issue but should be fixed

**Comment by BerkeleyTrue** [comment]
@rasheinstein This works for me. Can you give more information on your browser?

**Comment by rasheinstein** [comment]
In the more information dropdown menu, all links opened from all pages
should open in a new tab. For Map the Debris, the link opens in the same
tab and could cause your work to get cleared if you have started

**Comment by treece** [comment]
@BerkeleyTrue I can confirm this is an issue for me also on Google Chrome. The target attribute `target="_blank"` isn't being generated for the anchor.

**Comment by BerkeleyTrue** [comment]
confirmed

**Comment by QuincyLarson** [comment]
Fixed. Thank you for pointing this out, @rasheinstein!
