### ISSUE TITLE
Minor issue with "brownie points" and user names

### ISSUE THREAD

**Issue by khaduch** [FreeCodeCamp/FreeCodeCamp#8258]
#### Issue Description

I could not find an open issue that covered this ---

While helping a user with the username `E-Tank`, any comment made that referenced that user's name with `@` preceding it caused camperbot to issue brownie points. 

This is not a huge issue, except that it clutters the chat room with additional "noise" and it isn't correct.  I don't know if there is a regular expression that is looking for variants of the word "thanks", but that is what I suspect?  If so, maybe it could be tweaked a little bit to change this?

The biggest problem with it is the clutter in the chatroom, which is already difficult to navigate and use when there is a lot of activity...

#### Reference links:

:point_up: [April 23, 2016 9:27 AM](https://gitter.im/FreeCodeCamp/HelpJavaScript?at=571b78417469496137b8848e)

And camperbot issuing brownie points:
:point_up: [April 23, 2016 9:27 AM](https://gitter.im/FreeCodeCamp/HelpJavaScript?at=571b78416e3ae55e37e95f81)

And the few entries following that show repeated activity.
Thanks

**Comment by raisedadead** [comment]
@abhisekp you are the expert. Please chime in and guide about this.

**Comment by BKinahan** [comment]
This probably belongs as an issue on the [Camperbot repo](https://github.com/FreeCodeCamp/Camperbot/issues). I've seen it occur with `@thanks` before, too.

**Comment by BerkeleyTrue** [comment]
@BKinahan Is correct, please open this issue there.

Happy Coding

**Comment by abhisekp** [comment]
@khaduch this has been addressed here https://github.com/FreeCodeCamp/camperbot/pull/78
