### ISSUE TITLE
Waypoint Lesson requires the removal of Monospace even though it stated the removal of a dead link in the lesson information.

### ISSUE THREAD

**Issue by maugus33** [FreeCodeCamp/freecodecamp#826]
Challenge http://www.freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

1. go to challenge question.
2. Look at the requirements needed to go to the next lesson. You will notice that one of the requirements require the removal of Monospace from all paragraphs.
![image](https://cloud.githubusercontent.com/assets/7149823/7973922/7bf07c7a-0a29-11e5-9cc2-555408b13c48.png)
3. Read the lesson information. You will notice that it makes no mention of removing the Monospace font from all paragraphs but instead requires the removal of a dead link.

![image](https://cloud.githubusercontent.com/assets/7149823/7973941/da1f8c46-0a29-11e5-9328-5050fdc6d11c.png)

I think for consistency purposes, this should be fixed. I am using Google Chrome.

**Comment by QuincyLarson** [comment]
Hi @maugus33 thank you for submitting this issue. The directions say to delete the "p" declaration from your style element, and that is where the monospace font family is assigned. This said, if you misunderstood this, there's a good chance other people will misunderstand this, too, so I will update the wording. Thanks and happy coding! :)

**Comment by cloudclear** [comment]
Hi @QuincyLarson In the instruction, it still is not clear that it is the "p" declaration from the style element. New coders are still learning how to "talk" code (and digest instructions), including how to differentiate between where (style vs body vs...) something is located. If "delete the p element" means anything related to "p", this wording may be clear to advanced coders, less clear to others:
![screen shot 2016-01-05 at 0 49 03](https://cloud.githubusercontent.com/assets/16531295/12108547/480100c0-b347-11e5-8f67-dc033f044f44.png)
The waypoint can be completed by [also] deleting the "p" declaration from the body element, though the instructions do not require this explicitly. In the following waypoint, both declarations are absent. 

Updating the instructions to "Delete the p body element that contains a dead link, then delete the p style element."  might clear up any confusion. Cheers!
