### ISSUE TITLE
Update Certifications Pages

### ISSUE THREAD

**Issue by filipemeneses** [FreeCodeCamp/FreeCodeCamp#8261]
#### Challenge Name
[Claim Your Front End Development Certificate](https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate)

#### Issue Description
At the URL: 
`https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate` in step 2 

there is supposed to have a link about Plagiarism, probably this one: 
`https://en.wikipedia.org/wiki/Plagiarism`

instead there is an empty anchor and doesn't open anything:
`https://www.freecodecamp.com/challenges/claim-your-front-end-development-certificate#`

#### Browser Information
Google Chrome 

* Browser Name, Version: 49.0.2623.112 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by BKinahan** [comment]
Where should there be a link to an article about plagiarism? I'm pretty sure those buttons serve more of a 'click here to confirm' purpose, although somewhat inelegantly. They probably shouldn't say 'Open link in new tab' when there isn't anything to open.

Also the images have the old brown background color and are hosted on Imgur, so these pages could probably do with a few updates.

**Comment by filipemeneses** [comment]
In this button _Open link in new tab (this unlocks the next step)_: ![Open link in new tab (this unlocks the next step)](https://cloud.githubusercontent.com/assets/10226292/14763674/9d3b3da4-0972-11e6-99a6-6c80eaf60c48.png)

I agree with you, add the link or change the button's label.

**Comment by theflametrooper** [comment]
Changes to be made:

- [ ] Change "Open link in new tab" to "Confirm" or something similar
- [ ] Change brown background to green on images

**Comment by theflametrooper** [comment]
@filipemeneses Please change your description to the comment I made above...

**Comment by BerkeleyTrue** [comment]
This isn't a trivial change. It requires some knowledge of the challengeFramework to introduce conditional logic that renders different button text dependent on the type of url. The image change should be a separate issue.

**Comment by NJFoster** [comment]
I would like to work on this issue. For the second part of the changes that need to be made are you referring to the image's background that needs to be changed?

**Comment by theflametrooper** [comment]
@NJFoster Yeh!

**Comment by NJFoster** [comment]
What is the font on the images? I don't want to change the font and I can't identify it.

**Comment by theflametrooper** [comment]
@NJFoster Try this font: https://github.com/chrissimpkins/hack.

It doesn't have to be an exact replica, don't worry. Just make sure the image is 1280 by 720 and the background is the `#006400` hex color.

**Comment by filipemeneses** [comment]
@NJFoster Probably it's Monaco, font from Apple. [https://www.myfonts.com/fonts/apple/monaco/](https://www.myfonts.com/fonts/apple/monaco/)

**Comment by NJFoster** [comment]
I have the images done, is it fine to host them on imgur and replace the links that exist in the JSON files?

**Comment by theflametrooper** [comment]
Sure, just submit a pr!

**Comment by NJFoster** [comment]
I am having trouble squashing all of my commits into one commit request. I tried rebasing but it just adds more commits. Any help would be appreciated.

**Comment by theflametrooper** [comment]
@NJFoster Checkout [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) tutorial!

**Comment by hangaebal** [comment]
PR #8606 
- Certifications Page's Button "Open link in new tab" to "Confirm"

- Other Page's Link Button is not change
(ex: https://www.freecodecamp.com/challenges/create-a-github-account-and-join-our-chat-rooms)

**Comment by NJFoster** [comment]
Not at my computer right now will fix when I get home

**Comment by raisedadead** [comment]
![image](https://cloud.githubusercontent.com/assets/1884376/15269587/1a3a3de6-1a21-11e6-81dc-f52e77d3b37e.png)

This needs to be changes to the FCC's Green theme

**Comment by sahilkhurana19** [comment]
I can submit a PR with the green background on plagiarism image if anyone isn't working on it.

**Comment by NJFoster** [comment]
@sahilkhurana19 I do not have access to my machine anymore so if you could do that it would be great thank you.

**Comment by theflametrooper** [comment]
@NJFoster Do you want me to close your PR?

**Comment by NJFoster** [comment]
Yes please that would be helpful.
