### ISSUE TITLE
There is a bug in the test case testing.

### ISSUE THREAD

**Issue by dhanabh** [FreeCodeCamp/FreeCodeCamp#8266]
#### Challenge Name

https://www.freecodecamp.com/challenges/no-repeats-please

#### Issue Description

Earlier I wrote the code for permutation using Heaps https://en.wikipedia.org/wiki/Heap%27s_algorithm. My code worked great for test cases aab, aabb,aaa but when I tested the code for abcdefa my code showed 3300 results against FCC's 3600.
After trying in vain for getting help on the forum. I changed the algorithm from Heap to one of the other mentioned at https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-No-Repeats-Please. The code worked perfectly locally on my laptop using sublime text editor and chrome browser. My answers matched perfectly with the test cases. So I transferred my program from laptop to FCC bonfire. But on FCC bonfire it shows only first test case correct. I have rechecked my code many times for a bug. But couldn't find one. So I think there is a bug in the testing the test cases. Kindly do the needful. 

#### Browser Information

* Browser Name, Version: Google Chrome,Version 49.0.2623.112. Microsoft Edge
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  DeskTop

#### Your Code
`var temp = [];
var result = [] ;

function permAlone(str) {

arr = getPermutation(str);

console.log("Result: " + arr);
//console.log("Total: " + arr.length);

return arr.length;
}

function getPermutation(str){
var testStr;
var re = /(.)\1+/;
var cur;
var arr =  str.split("");

for(var x = 0; x < arr.length ; x++){
	
cur = arr.splice(x,1);
temp.push(cur);
		if(arr.length === 0 ){
			
			testStr = temp.join('');
			if (!(re.test(testStr)))result.push(testStr);
		}
		else
		{
				getPermutation(arr.join(''));
		}

arr.splice(x,0,cur);
temp.pop();
}

return result;

}

var word= "aabb";
var sat = permAlone(word);

console.log("sat: " + sat);`

![bonfire_issue01](https://cloud.githubusercontent.com/assets/879310/14766270/8cb1aeba-0a20-11e6-9369-2e2bde907a3d.png)

`

**Comment by erictleung** [comment]
@dhanabh you've declared `temp` and `result` in the global scope. Tests are run after each other so these global variables will change accordingly. Please make them locally scoped and try again.

**Comment by dhanabh** [comment]
@erictleung : many thanks. I just added initialization for the global variables in the function permAlone(). The code is working ok now. thanks once again.

**Comment by dhanabh** [comment]
Many thanks. I'll make changes and test again. best regards.
