### ISSUE TITLE
h2 problem

### ISSUE THREAD

**Issue by desafiador3991** [FreeCodeCamp/FreeCodeCamp#8268]
Challenge [Headline with the h2 Element](https://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
```

**Comment by chandramaniadil** [comment]
What is your issue ? the above solution is correct @desafiador3991

**Comment by dwd2010** [comment]
@desafiador3991, you got correct answer. I dont see any problem.

**Comment by Supreja** [comment]
Ya ! I am also facing problems . Nothing appears on the mobile screen

**Comment by Manish-Giri** [comment]
I can confirm this too.

**Comment by P1xt** [comment]
@Supreja  @Manish-Giri it looks like the same thing that's happening on this ticket here: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10678 which is a new ticket just opened this morning.
