### ISSUE TITLE
Cat app tutorial image does not load.

### ISSUE THREAD

**Issue by popertop32** [FreeCodeCamp/FreeCodeCamp#8269]
#### Add Images to your Website 
[Link](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20{%0A%20%20%20%20color%3A%20red%3B%0A%20%20}%0A%0A%20%20h2%20{%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20}%0A%0A%20%20p%20{%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20}%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A)

#### Issue Description
Cat photo won't load.

I've tried the following link for this challenge, but unfortunately the cat photo will not load. I also tried attaching extensions `.jpg` and `.png` to the url, neither have seemed to work.
```html
<img src="https://bit.ly/fcc-relaxing-cat">
```

#### Browser Information

* Firefox for ubuntu, Version: 45.0.2
* Operating System: Ubuntu 16 LTS
* Mobile, Desktop, or Tablet: Desktop

**Comment by theflametrooper** [comment]
@popertop32 So it appears neither of these images are being displayed:

- https://bit.ly/fcc-running-cats
- https://bit.ly/fcc-relaxing-cat

Your code is technically correct as you're linking to the correct source. This is an issue with the image hosting.

**Comment by Tripoli** [comment]
This Issue has once again resurfaced and the image will not load

**Comment by Tripoli** [comment]
nevermind, just add into the instructions that no .jpg ext is needed after the image

**Comment by timetoss** [comment]
I am having the same issue with this image. I went to the website and pulled the source code for this image from the url, that allowed the image to work but now its telling me that I haven't used the src attribute and I cant move forward

**Comment by erictleung** [comment]
@timetoss please read the feedback from the failing test:

> Your new image should have a `src` of **`https://bit.ly/fcc-running-cats`**.

Your code is incorrect. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
