### ISSUE TITLE
Dead 'X' button for the bug and help dialog boxes for Waypoint lessons

### ISSUE THREAD

**Issue by maugus33** [FreeCodeCamp/freecodecamp#827]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-custom-heading has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

1. Go to a waypoint interactive lesson
2. click on either the 'help' or 'bug' button
3. A dialog should pop up with a broken X button on the top right

For some reason, the 'X' button on the top right of the dialog box of both the 'help' and 'bug' option on the interactive waypoint lessons are dead. 

![image](https://cloud.githubusercontent.com/assets/7149823/7974072/3d2a3510-0a2b-11e5-8b5f-b70efe729115.png)

I went to a bonfire lesson and the 'X' button for the help and bug were working just fine so I think there is something in the code for the waypoint lessons that is breaking the link.  I am using Google Chrome.

**Comment by treece** [comment]
@QuincyLarson @BerkeleyTrue This bug is related to issue [#830] (https://github.com/FreeCodeCamp/freecodecamp/issues/830). The iPhone image is covering up the 'X' button which makes the button unclickable.

**Comment by BerkeleyTrue** [comment]
Thanks for the investigation @treece Closing this in favor of pull #831
