### ISSUE TITLE
Medium account is now defunct -- remove from Gear Up For Success

### ISSUE THREAD

**Issue by saramartinez** [FreeCodeCamp/FreeCodeCamp#8272]
#### Challenge Name
Gear Up For Success/Read Coding News on our Medium Publication

#### Issue Description
As of 3 days ago, FreeCodeCamp's Medium blog has been shut down ([We just abandoned our blog for Medium. You probably should, too.](https://medium.freecodecamp.com/we-just-abandoned-our-blog-for-medium-you-probably-should-too-33e742a1d49#.auy7bmh1v "Posted by Quincy Larson, April 21, 2016")). I think the challenge in "Gear Up For Success" that instructs students to sign up for Medium and follow FreeCodeCamp's blog should be removed. I can submit a PR as soon as you OK this change.

**Comment by theflametrooper** [comment]
@saramartinez This article is documenting the move from blogger to medium, not moving away from medium. Make sure you the whole article before submitting an issue. We have no intention of moving away from medium :smile:. Happy Coding!

**Comment by saramartinez** [comment]
OOPS! That was confusing. Sorry about that. I skipped over key words in my reading. Doh!
