### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by hateradeee** [FreeCodeCamp/FreeCodeCamp#8273]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by theflametrooper** [comment]
Only submit an issue if you have a title, description and relevant issue. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
