### ISSUE TITLE
CSS attribute semicolon bug

### ISSUE THREAD

**Issue by Yemeni** [FreeCodeCamp/FreeCodeCamp#8274]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%7Bcolor%3Apink%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text{color:pink}
</style>
<h1 class="pink-text">Hello World!</h1>

```
Because the attribute "color:pink" was not followed by a semicolon, the challenge was not successful.
It works in other challenges.

**Comment by dwd2010** [comment]
@Yemeni, Sorry this is not issue. you forget to add semicolon.

**Comment by erictleung** [comment]
@Yemeni Hmm the semi-colon in a single CSS rule isn't necessary. I guess we could relax the regex to allow the option of putting the semi-colon. It appears to already be relaxed in [Style the HTML Body Element](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4aaae7b48828ad58c5646a731b73e5465f2d7037/seed/challenges/01-front-end-development-certification/html5-and-css.json#L3833).

@FreeCodeCamp/issue-moderators second opinion?

**Comment by sludge256** [comment]
We discussed this in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8005. Should we reconsider?

**Comment by erictleung** [comment]
@sludge256 well @BerkeleyTrue has spoken on these rules. I personally would add semi-colons to my CSS for consistency. Considering our target audience are beginner programmers, I agree we should enforce this best practice. Maybe we should also change the test in Style the HTML body Element to require the semi-colon too.

**Comment by BerkeleyTrue** [comment]
@erictleung @sludge256 Yes, semicolons should always be included for consistency.

**Comment by erictleung** [comment]
@Yemeni closing this issue as the semicolon should be required to complete the challenge. Happy coding!
