### ISSUE TITLE
Free Code Camp: Challenge [Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by jimawofadeju** [FreeCodeCamp/FreeCodeCamp#8276]
I think there is a bug here because I followed the format of the example in my answer. The example code was:

<p>Here's a <a href="https://freecodecamp.com"> link to Free Code Camp</a> for you to follow.</p>

The code I entered, one line below the <h2></h2> tags was:
<p>View more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

There were 8 tests run for this challenge, but only one test failed. The test that failed was “your p element should have the text “View more “ (with a space after it). However, I included the exact words "View more " with a space after it. I would like to pass this challenge and move on to the next one. I would like this problem resolved. Thank you.

**Comment by erictleung** [comment]
@jimawofadeju I cannot see the rest of your code but I think I know what the "issue" is. A hint that's in the instructions is:

> Now nest your **existing** `a` element within a new `p` element (just after the existing h2 element)...

If that doesn't help, please copy-paste all of your code for us to determine if it is a bug in the site or there's an issue with your code. Thanks!

**Comment by jimawofadeju** [comment]
I just copied and pasted all of my code for this challenge. I submitted a new issue with the same title as the old issue.

**Comment by erictleung** [comment]
@jimawofadeju looking at your code you've posted in #8277, my guess was right. There isn't anything wrong with the site. Please read the instructions carefully. The answer to fix your issue is in the instructions. But if you are still stuck with this challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by jimawofadeju** [comment]
I did ask twice if anyone was able to pass the nesting an anchor element within a paragraph. No one responded and it has been 7 or 8 hours since I asked.

**Comment by jimawofadeju** [comment]
I figured it out. I had two of the same anchor elements. I only need one. I must have copied and pasted the anchor element without removing the one I initially copied.
