### ISSUE TITLE
FCC website redesign

### ISSUE THREAD

**Issue by GreatDanton** [FreeCodeCamp/FreeCodeCamp#8279]
I was using elementary os a while ago, so I decided to take a look at their site. I noticed their Github page and took a look at their issues. I found this post:

https://github.com/elementary/mvp/issues/1098

> 
> 
> We should probably collect a comprehensive list, rank by the amount of applicable lessons and price, then shortlist from there.
> 
>     Codecademy [Recommended]
>     Code School
>     Teaching Tree
>     Linux Academy
>    ** Free Code Camp [Disqualified]**
>     The Odin Project [Non-Interactive]
>     Code.org [?]
> 
> 

and explanation in the next post:

>  I think I would disqualify freecodecamp.com just on the way their website looks. I'm not sure I trust someone to teach web skills when their website looks like it does.

The FCC site doesn't really bother me, it's not the prettiest out there but it does it's job. However in the eyes of someone who does not know anything about FCC, it might seem exactly what's written in the last quote.

**Comment by theflametrooper** [comment]
@GreatDanton We currently have no intention of changing the design of our site. If you want to improve certain areas via PR, feel free! We won't be redesigning our site just to be featured on a list. Happy Coding!
