### ISSUE TITLE
Challenge: Title Case a Sentence

### ISSUE THREAD

**Issue by apugoneappu** [FreeCodeCamp/FreeCodeCamp#8280]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20var%20lowerCase%20%3D%20str.toLowerCase()%3B%0A%20%20var%20sliced%20%3D%20lowerCase.slice().split(%22%20%22)%3B%0A%20%20var%20cap%20%3D%20%22%22%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20sliced.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20cap%20%2B%3D%20sliced%5Bi%5D%5B0%5D.toUpperCase()%20%2B%20sliced%5Bi%5D.substring(1%2Csliced%5Bi%5D.length)%20%2B%20%22%20%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20cap%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
**The code is returning the correct result but FreeCodeCamp isn't accepting it!**
My code:
```javascript
function titleCase(str) {
  var lowerCase = str.toLowerCase();
  var sliced = lowerCase.slice().split(" ");
  var cap = "";
  for (var i = 0; i < sliced.length; i++) {
    cap += sliced[i][0].toUpperCase() + sliced[i].substring(1,sliced[i].length) + " ";
  }
  
  return cap;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```

**Comment by theflametrooper** [comment]
@apugoneappu Was your issue resolved?

**Comment by JilaMK64** [comment]
Same problem. My code is:
        function titleCase(str) {
            var lista = str.split(" ");
            var wordLc;
            var wordUc;
            var newSentance = "";
            for (var i = 0; i < lista.length; i++){
                wordLc = lista[i].toLowerCase();
                wordUc = wordLc.charAt(0).toUpperCase() + wordLc.slice(1);
                newSentance = newSentance + " " + wordUc;
            }
            return newSentance;
        }
        titleCase("sHoRt AnD sToU");
I tested for all examples and got correct result. But freecode  did not accept.

**Comment by apugoneappu** [comment]
@theflametrooper Yes.
@JilaMK64 The problem is that our code is adding a space at the end of the last word, making the result "I'm A Little Tea Pot " whereas it should be "I'm A Little Tea Pot".
Notice the space at the end of the result, that's not wanted.

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`

**Comment by yaseenagag** [comment]
use this when you return your result cap.slice(0 , -1)
