### ISSUE TITLE
titleCase

### ISSUE THREAD

**Issue by JilaMK64** [FreeCodeCamp/FreeCodeCamp#8281]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%20%20%20%20%20%20%20%20function%20titleCase(str)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20lista%20%3D%20str.split(%22%20%22)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20wordLc%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20wordUc%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20newSentance%20%3D%20%22%22%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20lista.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wordLc%20%3D%20lista%5Bi%5D.toLowerCase()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wordUc%20%3D%20wordLc.charAt(0).toUpperCase()%20%2B%20wordLc.slice(1)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20newSentance%20%3D%20newSentance%20%2B%20%22%20%22%20%2B%20wordUc%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20newSentance%3B%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20titleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
        function titleCase(str) {
            var lista = str.split(" ");
            var wordLc;
            var wordUc;
            var newSentance = "";
            for (var i = 0; i < lista.length; i++){
                wordLc = lista[i].toLowerCase();
                wordUc = wordLc.charAt(0).toUpperCase() + wordLc.slice(1);
                newSentance = newSentance + " " + wordUc;
            }
            return newSentance;
        }

        titleCase("sHoRt AnD sToUt");

```
I tested for all examples and got correct result. But freecode did not accept.. Any ideaa

**Comment by JilaMK64** [comment]
I solve it. To many " " in my code when adding words to var newSentance

**Comment by NerdyPixels** [comment]
Opps sorry should be written this way:

*var lista = str.split;*

Remove the "" inside the ( ), so it should be

*var lista = str.split( );*

**Comment by NerdyPixels** [comment]
function titleCase(str) {
            var lista = str.split( );
            var wordLc;
            var wordUc;
            var newSentance =( );
            for (var i = 0; i < lista.length; i++){
                wordLc = lista[i].toLowerCase();
                wordUc = wordLc.charAt(0).toUpperCase() + wordLc.slice(1);
                newSentance = newSentance + " " + wordUc;
            }
            return newSentance;
        }

        titleCase("sHoRt AnD sToUt");
}

**Comment by JilaMK64** [comment]
I started newSentnace with the wordUc. When I add last word it must be without "  "

**Comment by JilaMK64** [comment]
NerdyPixels your code return "syntaxErroe": Unexpected token ). This is my code for this problem:
        function titleCase(str) {
            var lista = str.split(" ");
            var wordLc;
            var wordUc;
            var newSentance = "";
            for (var i = 0; i < lista.length; i++){
                wordLc = lista[i].toLowerCase();
                wordUc = wordLc.charAt(0).toUpperCase() + wordLc.slice(1);
                if ( i != lista.length - 1) {
                  newSentance += wordUc + " ";
                }
                else if (i == lista.length - 1) {
                  newSentance += wordUc;
                }
            }
            
            return newSentance;
        }

**Comment by Bharat-Kalluri** [comment]
You can solve it this way

```
        function titleCase(str) {
            var lista = str.split(" ");
            var wordLc;
            var wordUc;
            var newSentance = "";
            for (var i = 0; i < lista.length; i++){
                wordLc = lista[i].toLowerCase();
                wordUc = wordLc.charAt(0).toUpperCase() + wordLc.slice(1);
                newSentance = newSentance + " " + wordUc;
            }
            return newSentance;
        }

        titleCase("sHoRt AnD sToUt");
```

**Comment by erictleung** [comment]
@JilaMK64 sounds like the issue is resolve. If you get stuck with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by woldyj** [comment]
still wont work i have the same issue

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
