### ISSUE TITLE
unable to go futher even when everything thing is right

### ISSUE THREAD

**Issue by akzt8** [FreeCodeCamp/FreeCodeCamp#8283]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%0A%20%20%20%20background-color%3Ablack%3B%0A%20%20%20%20font-family%3AMonospace%3B%0A%20%20%20%20color%3Agreen%3B%0A%20%20%7D%0A%20%20%0A%20%20.pink-test%7Bcolor%3Apink%20%3B%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22pink-test%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
  
    background-color:black;
    font-family:Monospace;
    color:green;
  }
  
  .pink-test{color:pink ;}

</style>

<h1 class="pink-test">Hello World!</h1>

```

can you please tell me what is wrong in this code?
<img width="947" alt="code" src="https://cloud.githubusercontent.com/assets/18656242/14786967/111a7d2c-0b1f-11e6-872c-04f1db64d63f.PNG">

**Comment by erictleung** [comment]
@akzt8 thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: check your spelling. Happy coding!
