### ISSUE TITLE
typo in bootstrap block-level btn example

### ISSUE THREAD

**Issue by Afrenz** [FreeCodeCamp/FreeCodeCamp#8284]
I believe the examples for bootstraps block-level button class is incorrect and may cause confusion. Examples are showing " .btn.btn-block" when they should be "btn btn-block" in order to work 

#### Challenge Name
Create a Block Element Bootstrap Button

https://www.freecodecamp.com/challenges/create-a-block-element-bootstrap-button
#### Browser Information

* Browser Name, Version: Chrome Canary
* Operating System: OS X El Capitan vs 10.11.3
* Mobile, Desktop, or Tablet: Mackbook Pro Laptop

**Comment by erictleung** [comment]
@Afrenz thanks for the issue. I can foresee confusion from this but that notation is used in CSS rules (e.g. `.btn`). I'm not sure how much effort would be needed to edit that image. Maybe adding an actual code example might help alleviate any confusion.

/cc: @FreeCodeCamp/issue-moderators

**Comment by Afrenz** [comment]
Totally understandable that it may not be worth changing out the image. I
think you're solution of a detailed example would suffice. Wasn't trying to
be picky just an observation. Thanks for your hard work with FCC!

**Comment by malisayang** [comment]
@Afrenz Thanks so much, I was really confused why my code wasn't working. Your comment helped a lot :)

**Comment by raisedadead** [comment]
@erictleung I agree we should add a snippet instead, of the image.

**Comment by Bouncey** [comment]
I have this, just trying to set up a testing environment before PR
