### ISSUE TITLE
I passed with bad code

### ISSUE THREAD

**Issue by JilaMK64** [FreeCodeCamp/FreeCodeCamp#8286]
I passed this task but my code is not good for all possible situation.  For example mutation(["helo", "Hello"] will give back true, but it is false. Any ideac how to solve this problem?
My code:
```javascript
            function mutation(arr) {
                var result;
                var countLet = 0;
                
                for (var i = 0; i < arr[1].length; i++) {
                    var char = arr[1][i].toLowerCase();
                    for (var j = 0; j < arr[0].length; j++) {
                        if ( char == arr[0][j].toLowerCase()) {
                            countLet += 1;
                            break;
                        } else {
                            continue;
                        }
                    }
                }
                if (countLet == arr[1].length){
                    return true;
                } else {
                    return false;
                }
            }
mutation(["hello", "hey"]);

```

**Comment by erictleung** [comment]
@JilaMK64 this is part of the challenge. Only the same letters need to exist, ignoring the actual number.

> Return true if the string in the first element of the array contains all of the letters of the string in the second element of the array.

Look at the 5th test for an example:

> `mutation(["Mary", "Aarmy"])` should return true

Closing as not an issue with the site. Happy coding!
