### ISSUE TITLE
copy and paste in edge

### ISSUE THREAD

**Issue by hellmaca** [FreeCodeCamp/FreeCodeCamp#8289]
I am trying to copy and paste in the Microsoft Edge browser to save time. It is a terrible implementation. Just trying to save time. This is so inconvenient!

Challenge [Apply the Default Bootstrap Button Style](https://www.freecodecamp.com/challenges/apply-the-default-bootstrap-button-style#?solution=%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%22%3E%3C%2Fbutton%3E%0A%0A%20%20%20%20%20%20%20%20%3Cbutton%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button class="btn btn-default"></button>
        <button class="btn btn-default"></button>

        <button></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
        <button></button>
        <button></button>
      </div>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@hellmaca can you elaborate on your issue? What is a terrible implementation? Or is it already convenient?

**Comment by hellmaca** [comment]
Sorry I was frustrated when I wrote that. Also did not expect anyone to
read it. The exercise is asking me to type the same text 6 times inside 6
different elements. When I select the text I want to copy it ends up
copying the whole element to the clipboard rather than the selection that
the exercise is asking me to type repeatedly. Not sure if it is an Edge
problem or a free code camp problem.

**Comment by pavanharsha** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button class="btn btn-default"></button>
        <button class="btn btn-default"></button>

        <button></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
        <button></button>
        <button></button>
      </div>
    </div>
  </div>
</div>

**Comment by pavanharsha** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button class="btn btn-default"></button>
        <button class="btn btn-default"></button>

        <button></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
        <button></button>
        <button></button>
      </div>
    </div>
  </div>
</div>

**Comment by erictleung** [comment]
@hellmaca I don't have access to Microsoft Edge to verify that I would assume it to be more of a Microsoft Edge issue.

**Comment by raisedadead** [comment]
@erictleung I'll check when I get back home. But yeah mostly I agree this maybe a browser side issue. Will update.

**Comment by raisedadead** [comment]
@erictleung and @hellmaca I am afraid Copy/Paste works just fine on Edge.

Tested Agent : `Windows NT 10.0  Edge/13.10586`

My personal recommendation, if you can please make sure that you have all the updates installed, on your system. Alternatively if you can please switch to Chrome.

Closing, unless we can find anyone else getting the same issue or confirm that this is an issue with the FCC code base and not the browser.

**Comment by hellmaca** [comment]
No matter which browser I use there is a bug. Edge seemed to have the least
problematic bug.

**Comment by raisedadead** [comment]
@hellmaca Do you mean that you are getting this on other browsers as well, can you provide the details of the System you are on?

Also can you take a screenshot of the Dev Console of the browser?
Press `F12 > Console`
Then refresh the browser `Ctrl + F5`

Take some screenshots and post them here.

Note :
You have to visit the this issue page on a browser and upload the screenshots by dragging and dropping them in the comments box.
Email reply/attachements will not work.

Thanks.
