### ISSUE TITLE
Add hints to new react challenge framework

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#8290]

**Comment by BerkeleyTrue** [comment]
![test-hints](https://cloud.githubusercontent.com/assets/6775919/16065623/4ae5e6cc-3261-11e6-9f75-37448ceefd8d.gif)

**Comment by chuckadams** [comment]
The pop-up hint I think would be better-placed in a textbox appearing under the hint button, where it's not only closer to the action that initiated it, it gives the hint a place to stay rather than having to be dismissed.
