### ISSUE TITLE
Challenge "Check for Palindromes" has a bug

### ISSUE THREAD

**Issue by Yasic** [FreeCodeCamp/FreeCodeCamp#8292]
#### Check for Palindromes

https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20%2F%2Fstr%20%3D%20str.match(%2F%2Fgi)%3B%0A%20%20%2F%2Fstr%20%3D%20str.join(%22%22)%3B%0A%20%20%2F%2Fstr%20%3D%20str.replace(%2F%5C.%2Fgi%2C%22%22)%3B%0A%20%20if%20(str%20%3D%3D%20%220_0%20(%3A%20%2F-%5C%5C%20%3A)%200-0%22)%7B%0A%20%20%20%20%2F%2Freturn%20true%3B%0A%20%20%7D%0A%20%20return%20str%3B%0A%20%20str%20%3D%20str.replace(%2F%5Cs%2Fgi%2C%22%22)%3B%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20str%20%3D%20str.replace(%22%2C%22%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%22%2C%22%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%22.%22%2C%22%22)%3B%0A%20%20var%20i%20%3D%20str.length%20-%201%3B%0A%20%20var%20flag%20%3D%200%3B%0A%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20i%3B%20j%2B%2B)%7B%0A%20%20%20%20if%20(str%5Bj%5D%20%3D%3D%20str%5Bi%20-%20j%5D)%7B%0A%20%20%20%20%20%20flag%20%3D%200%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20flag%20%3D%201%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20if(flag%20%3D%3D%3D%200)%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20return%20false%3B%0A%7D%0A%0Apalindrome(%220_0%20(%3A%20%2F-%5C%20%3A)%200-0%22)%3B%0A

#### Issue Description

The last situation of the test which shows “palindrome("0_0 (: /-\ :) 0-0") should return true.” can not be checked well. Because the string "0_0 (: /-\ :) 0-0" will become "0_0 (: /- :) 0-0" when it is given to the function palindrome().
I think it is because backslash “\” is a special character and it will bring ambiguity in the function.
Finally I reproduce it by some code as following.
```
if (str == "0_0 (: /-\ :) 0-0"){
    return true;
  }
```
#### Browser Information

* Browser Name, Version:  Chrome,49.0.2623.112 m
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function palindrome(str) {
  // Good luck!
  //str = str.match(//gi);
  //str = str.join("");
  //str = str.replace(/\./gi,"");
  if (str == "0_0 (: /-\ :) 0-0"){
    return true;
  }
  str = str.replace(/\s/gi,"");
  str = str.toLowerCase();
  str = str.replace(",","");
  str = str.replace(",","");
  str = str.replace(".","");
  var i = str.length - 1;
  var flag = 0;
  for (var j = 0; j < i; j++){
    if (str[j] == str[i - j]){
      flag = 0;
    }
    else{
      flag = 1;
      break;
    }
  }
  if(flag === 0){
    return true;
  }
  return false;
}

palindrome("0_0 (: /-\ :) 0-0");

```

**Comment by erictleung** [comment]
@Yasic you need to remove more characters from that string.

> You'll need to remove all non-alphanumeric characters (punctuation, spaces and **symbols**) and...

If you are still stuck with this challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
