### ISSUE TITLE
Title Case a Sentence

### ISSUE THREAD

**Issue by woldyj** [FreeCodeCamp/FreeCodeCamp#8298]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0Avar%20part1%3B%0Avar%20part2%3B%0A%20%20%0A%20var%20array%20%3D%20str.split(%22%20%22)%3B%0A%20%20%0A%20var%20final%20%3D%20%22%20%22%3B%0A%20%20%0A%20%20for(i%20%3D%200%3B%20i%20%3C%20array.length%3B%20i%2B%2B)%7B%0A%20%20%20%20part1%20%3D%20array%5Bi%5D.toLowerCase()%3B%0A%20%20%20%20part2%20%3D%20part1.charAt(0).toUpperCase()%20%2B%20part1.slice(1)%3B%0A%20%20%20%20%0A%20final%20%2B%3D%20%22%20%22%2B%20part2%20%3B%20%0A%20%20%7D%0A%20%20%0A%20%20return%20final%3B%0A%20%20%0A%7D%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
var part1;
var part2;
  
 var array = str.split(" ");
  
 var final = " ";
  
  for(i = 0; i < array.length; i++){
    part1 = array[i].toLowerCase();
    part2 = part1.charAt(0).toUpperCase() + part1.slice(1);
    
 final += " "+ part2 ; 
  }
  
  return final;
  
}
titleCase("sHoRt AnD sToUt");

```

the test works but codeCamp wont accept it

**Comment by sludge256** [comment]
It's because there are two spaces at the beginning of your output(s).

In the future, please attempt to seek secondary confirmation before posting issues, as we want to reserve GitHub Issues for actual bugs or discussions. The `Help` button on the challenge page will bring you to the appropriate chat room where you can ask questions about your code. Thanks.

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`

**Comment by thuyetbk** [comment]
You need add function trim().It will look like return final.trim();
