### ISSUE TITLE
Having to enter email multiple times

### ISSUE THREAD

**Issue by PKMNinja** [FreeCodeCamp/freecodecamp#83]
When you finally complete all the challenges it sends you to the page where you put your email. Then after you do that is sends you to the next page. If you close the tab and want to revisit the second page you have to reenter your email. It would be faster for the user to only have to enter their email once. First page http://www.freecodecamp.com/done-with-first-100-hours and second page http://www.freecodecamp.com/nonprofit-project-instructions

**Comment by QuincyLarson** [comment]
Thanks for pointing this out. As a result, I've linked to the http://www.freecodecamp.com/nonprofit-project-instructions page from the nonprofit project trello board. 

We are in the process of completely overhauling the curriculum, and this will no longer be an issue then. Considering that this is a minor inconvenience to only a handful of people, I'm going to go ahead and close this issue.
