### ISSUE TITLE
iPhone image covers up a portion of the code editor

### ISSUE THREAD

**Issue by treece** [FreeCodeCamp/freecodecamp#830]
![screen shot 2015-06-03 at 10 38 41 pm](https://cloud.githubusercontent.com/assets/3117424/7975879/89f7b014-0a41-11e5-9269-26bab063966b.png)

This effects longer lines of codes by making it impossible to select code when trying to insert the cursor with the mouse.

I saw where @QuincyLarson added a commit to make the iphone stand out over footer by adding a z-index of 9999 but 9999 is too high.

I'm doing a pull request right now that fixes the cover up issue on the code editor and still keeps the iphone above the footer as Quincy wanted.

Thanks,
Charles

**Comment by QuincyLarson** [comment]
Thanks, I didn't even think about the modal when I set the z-index that high. I'm taking a look at your pull request now.
