### ISSUE TITLE
A Bug on Link to External Pages with Anchor Elements Help Please!!!

### ISSUE THREAD

**Issue by Gaozzie8** [FreeCodeCamp/FreeCodeCamp#8300]
Challenge [Link to External Pages with Anchor Elements](https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%20%0A%3Ca%20href%3D%22http%3A%2F%2Ffreecodecamp.com%22%3E%20cat%20photos%3C%2Fa%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
 
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
 
<a href="http://freecodecamp.com"> cat photos</a>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>


```
So i was in the chat room and i was told to refresh my page and it still wouldnt work after  times of refreshing the page. Maybe i did do something wrong but i do need help. This is what my text looks like:

Create an a element that links to http://freecatphotoapp.com and has "cat photos" as its anchor text.

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
 
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
 
<a href="http://freecodecamp.com"> cat photos</a>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
 
After i press run the test it's also still telling me: You need an a element that links to http://freecatphotoapp.com.

**Comment by sludge256** [comment]
Resolved via Gitter.

**Comment by Tomi105** [comment]
I have same problem  and I don't know what must do

**Comment by dwd2010** [comment]
@Tomi105, you can ask help at gitter.

**Comment by Tomi105** [comment]
@dwd2010  I will try to do that thank you

**Comment by sasory21** [comment]
look like the photo                                   

![2](https://cloud.githubusercontent.com/assets/18900090/16608100/9bbc26fc-4359-11e6-98f7-70f90cf43331.JPG)

**Comment by xiaji2** [comment]
Is there anybody able to help me with Link to External Pages with Anchor Elements on Free Code Camp?

**Comment by xiaji2** [comment]
``

**Comment by xiaji2** [comment]
Is there anybody able to help me with Link to External Pages with Anchor Elements on Free Code Camp?

              Thanks!

**Comment by erictleung** [comment]
@xiaji2 please take all coding questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by xiaji2** [comment]
### Yy

**Comment by Himanshuias** [comment]
use www.freecodecamp.com

like this 
<a href="http://www.freecodecamp.com"> cat photos</a>

**Comment by Himanshuias** [comment]
please ,use http://www.freecodecamp.com

**Comment by ZHEN7954** [comment]
this is bug

**Comment by GodHimself1** [comment]
I'm having the same problem right now. I will refresh the page.

**Comment by conoh** [comment]
Just got past this issue/bug - refreshing the page will get you through this challenge.

**Comment by Milan-Varghese** [comment]
Simple
They've asked an a element that links to http://freecatphotoapp.com
but your element links to http://freecodecamp.com
So just correct the link
