### ISSUE TITLE
Calling paramater num in a loop causes the browser to crash

### ISSUE THREAD

**Issue by Mason-Rojik** [FreeCodeCamp/FreeCodeCamp#8306]
When I call the num paramater from the function sumFibs() it crashes my browser /

Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sumFibs(num) {
  
  var a,b,result;
  var arr=[];
  var i, sum;
 
  a=0;
  b=1;
  result=b;
  for(i =1;i<num;i++)
  {
    result = a+b;
    if(result % 2 !== 0)
      {
        arr.push(result);
      }
    
    a=b;
    b=result;
  }
  sum=0;
  for(i = 0;i<arr.length;i++){
    sum += arr[i];
    
  }
  return arr;
}

sumFibs(4);

```

**Comment by BKinahan** [comment]
This is an issue with your code, not an issue with the challenge. Please consult the [help chat](https://gitter.im/FreeCodeCamp/HelpJavascript).

Hint: The fibonacci numbers lower than 100 is not the same set as the first 100 fibonacci numbers.

**Comment by raisedadead** [comment]
@Mason-Rojik you are almost there, but this is not an issue with challenge, 
If you would like, please visit the chat room and seek further assistance to coding.

Thanks @BKinahan 

Happy Coding!
