### ISSUE TITLE
Points don't update (on next challenge page) after challenge completed

### ISSUE THREAD

**Issue by RayBB** [freeCodeCamp/freeCodeCamp#8307]
#### Issue Description

When I complete a challenge FCC automatically directs me to the next challenge. However, when I'm on the next challenge page it doesn't have my updated number of points in the top right hand corner of the screen. If I refresh or navigate to another page the points update.

I have only tested this on video challenge pages.
#### Browser Information

Shouldn't be relevant but:
- Browser Name, Version: Chrome 50
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
Ahh. If I am not wrong its a known issue with the ongoing react migration ain't it @BerkeleyTrue ?

**Comment by raisedadead** [comment]
This is similar related to #8455 but has to do with the brownies.
