### ISSUE TITLE
Link to External Pages with Anchor Elements with CatPhotoApp

### ISSUE THREAD

**Issue by cesilva108** [FreeCodeCamp/FreeCodeCamp#8308]
Challenge [Link to External Pages with Anchor Elements](https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements)

The instructions are:
_Create an a element that links to http://freecatphotoapp.com and has "cat photos" as its anchor text._

The statement I constructed is:
<p>Here are <a href="http://freecatphotoapp.com">cat photos</a> for you to follow.</p>

Upon submitting, the page does not accept the response and does not move forward.

**Comment by venkateshilango7** [comment]
Hi Christian,

![image](https://cloud.githubusercontent.com/assets/9502407/14859469/409393d2-0c72-11e6-9feb-bfb86db8d6f3.png)

I was able to update may be could you try again?

Thanks and Regards, Venkatesh

**Comment by theflametrooper** [comment]
Those tests appear to complete fine. What device are you using?

**Comment by cesilva108** [comment]
I tried it again, and now it's working. I was accessing the site through a
Chromebook and then through a Dell Windows 7. It's fixed.

Thank you,

-cs

**Comment by niharika517** [comment]
hii Mr.Venkatesh,i tried the way u had done it,but i am not getting it y???

**Comment by venkateshilango7** [comment]
Hi Niharika,

Can you paste the snap shot of your code?

Thanks and Regards, Venkatesh

**Comment by niharika517** [comment]
hey I got it
thanks

**Comment by biobytes** [comment]
I'm having the same problem exactly and i've pretty much followed all recommended solutions here,

**Comment by niharika517** [comment]
once check this

**Comment by freecodecampcoder671326** [comment]
hey  i am also having the same problem
i am writing the same command but it is not accepting

**Comment by ifydechu** [comment]
I have tried everything you explained to make progress but am still stucked. Where am I getting it wrong?
