### ISSUE TITLE
"7===val"  should also right, not only "val===7" 

### ISSUE THREAD

**Issue by alfrescoo** [FreeCodeCamp/FreeCodeCamp#8309]
Challenge [Comparison with the Strict Equality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-strict-equality-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function testStrict(val) {
  if (val) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testStrict(10);

```

**Comment by raisedadead** [comment]
Agreed. Nice Catch @alfrescoo ! :sweat_smile:

**Comment by josectello** [comment]
I'm going to give this a shot if no one else is already working on it!

**Comment by eprempeh** [comment]
Passing string value eg. "7" allows you to submit and go to next challenge as well as calling the function without the argument.

**Comment by raisedadead** [comment]
Yup that's because the test case's (behind the scenes) are called correctly.
