### ISSUE TITLE
Audit Favicons

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8312]
We need to audit all the Favicons here and make sure they are all the FCC icon with the color #006400. Some of them are currently brown or an olive shade of green.

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/partials/meta.jade

If you someone has a tool like photoshop to update the images as #006400, you can attach them to this issue and I can get them into s3.

**Comment by sahat** [comment]
@QuincyLarson you can assign it to me.

**Comment by HelioGuilherme66** [comment]
@sahat I am already doing them.

**Comment by sahat** [comment]
Ok, disregard my earlier comment.

**Comment by HelioGuilherme66** [comment]
[Images_for_#8312.zip](https://github.com/FreeCodeCamp/FreeCodeCamp/files/241498/Images_for_.8312.zip)
Here are the images, file contains the changed and not_changed images in zip archives.

**Comment by PandaWhisperer** [comment]
I've noticed that freecodecamp.com and medium.freecodecamp.com use slightly different favicons (see screenshot below – medium.freecodecamp.com is the first one). 

<img width="168" alt="screen shot 2016-05-05 at 5 27 39 pm" src="https://cloud.githubusercontent.com/assets/749244/15061150/bb974270-12e6-11e6-86d5-eca564eff2cf.png">

As you can see the color is slightly different, and the left icon is crisper (on a retina screen) than the right one.

**Comment by HelioGuilherme66** [comment]
@PandaWhisperer could you open the attached zip file and validate the quality of the favicon.ico image?
Thanks.

**Comment by theflametrooper** [comment]
@PandaWhisperer This because cloudfare is still using the cached favicon.

**Comment by PandaWhisperer** [comment]
@HelioGuilherme66 downloaded the .zip file, icons looked good to me.

**Comment by BerkeleyTrue** [comment]
Cloudflare does not cache favicon's. In fact, the favicon requests don't ever touch cloudflare since they are directly served from aws

**Comment by BerkeleyTrue** [comment]
@HelioGuilherme66 can you submit a PR to https://github.com/FreeCodeCamp/assets

**Comment by HelioGuilherme66** [comment]
@BerkeleyTrue Please clarify what you need for the PR. What from the below list? 

- Audit the existing icons/images in "Logos and Covers"
- Create a new directory with all the icons/images from the zip file (what directory structure to create?)

Thanks.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @HelioGuilherme66 FYI the favicon on Free Code Camp is still the wrong shade of green. I've uploaded what seems to be the correct file to S3.

**Comment by QuincyLarson** [comment]
I've long-since resolved this and am closing this issue. Thanks for your help, everyone!
