### ISSUE TITLE
Audit wiki articles and remove redundant headlines

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8313]
It seems Gatsby automatically adds the article title as a headline, but some articles have headlines as well.

![](https://www.evernote.com/l/Ar-OANhYsJVGRav8Bbg9j1ZHKJAnt_j6BbEB/image.png)

**Comment by Rafase282** [comment]
I would prefer is the title was not added automatically. As far as I understand it as generated from the filename. While we try to make filenames short and to the point, we have more room for better titles by providing one in the markdown itself. @QuincyLarson
