### ISSUE TITLE
Wiki typeface isn't Lato

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8314]
The wiki should use the Lato typeface for both articles and the sidebar, like every other part of FCC. It currently seems to be using the browser default.

![](https://www.evernote.com/l/Ar9vxhAteaVCoKvU4MON46DZPiBWtz37tkkB/image.png)

**Comment by theflametrooper** [comment]
@QuincyLarson I submitted a [PR](https://github.com/FreeCodeCamp/wiki-generator/pull/8) to add the Raleway Font. If you want I can change this to the `Lato` font.

**Comment by Rafase282** [comment]
https://github.com/FreeCodeCamp/wiki-generator/pull/9 should fix that. However, the real problem is that no one seems to be able to get the wiki generator running to update the current generated wiki.
