### ISSUE TITLE
Some wiki articles route to subdirectories that don't exist

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8315]
![](https://www.evernote.com/l/Ar9IzQgIWYlA6IbkYekKAXOsIH-8PR7TfFYB/image.png)

**Comment by QuincyLarson** [comment]
We need to decide whether we want to organize articles this way or just have articles in one big file and have a language-specific naming convention like "Python-[name of article]"

**Comment by Rafase282** [comment]
The current code is the following:

```
- [Introduction](Python-Introduction)
- [Basics](Python-Basics)
- [Operators](Python-Operators)
- [More Built-in Types](Python-More-Builtin-Types)
- [Functions](Python-Functions)
- [Web-development in Python](Web-Development-in-Python)
- [Installing Django and Flask](Install-Django-Flask)
- [More Python Resources](Python-Resources)
```

So it shouldn't have that link. I checked the wiki and that problem is not there. Also we currently use the `Python-[name of article]` for python and the other languages we now support.
