### ISSUE TITLE
i should have not passed

### ISSUE THREAD

**Issue by tuliodnw** [FreeCodeCamp/FreeCodeCamp#8316]
#### Mutations
https://www.freecodecamp.com/challenges/mutation

#### Issue Description
i should have not passed, my code is flawed

#### Browser Information
i 
* Browser Name, Version:  chrome
* Operating System: windows 8.1

#### Your Code

```js
function mutation(arr) {
  
var a="",b,veces; var count=0;
   
arr[0]=arr[0].toLowerCase(); 
 arr[1]=arr[1].toLowerCase();    
    
a=arr[0]  ;
b=arr[1];
  
  
b=b.split("");
for(var i=0;i<arr[1].length;i++){

 var pos = a.indexOf(b[i]);
  
while (pos !== -1) {
  count++;
  pos = a.indexOf(b[i], pos + 1);
 
}      
}
 if (count>=arr[1].length) {
   return true;   
 } 
  return false;
}
mutation(["pooooooooooooooooor", "no"]);
```

**Comment by erictleung** [comment]
@tuliodnw it looks like there needs to be an additional test for exactly the case you've shown. We should have a test like this:

> `mutation(["voodoo", "no"])` should return false

**Comment by benmxavier** [comment]
#dibs

**Comment by vcooley** [comment]
I'm going to take my first swing at fixing this.

**Comment by rshafto** [comment]
I submitted a pull request to resolve this issue, pull request #8324
