### ISSUE TITLE
Update Wiki Readme so it's easier to get wiki up and running

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8317]
The wiki's README.md's directions are out of date.

**Comment by Rafase282** [comment]
Do you mean [this](https://github.com/freecodecamp/freecodecamp/wiki) or [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/README.md) one?

**Comment by Rafase282** [comment]
I think you are referring to the wiki generator. I'm currently looking into it.

**Comment by QuincyLarson** [comment]
@Rafase282 Actually, we need to create a README.md file for the Wiki repo itself, which you can do here: https://github.com/FreeCodeCamp/wiki/new/master?readme=1

This should be aimed at developers who want to contribute and/or improve the wiki's code. It should walk them through getting the wiki running locally.

**Comment by xRahul** [comment]
I've also tried to use the wiki-generator locally, but there are too many errors to take care of.
someone who has installed it locally needs to update the install scripts and update the readme.

**Comment by Rafase282** [comment]
@xRahul yes, I tried that too and it didn't work for me no matter what.

@QuincyLarson For the readme, perhaps just add instructions on how to fork the repo and clone it and edit locally and then link to the article I pointed out?

**Comment by theflametrooper** [comment]
Closing, we're switching to using the `Lato` font instead.

**Comment by Rafase282** [comment]
When you create the PR make it to auto close this one

**Comment by Rafase282** [comment]
Reopened, it got closed by the wrong PR

**Comment by Rafase282** [comment]
@QuincyLarson I created the README page by taking bits from the Wiki's home page and Wiki's central article for contributing and learning about the wiki itself.

It can probably be expanded but there is no much science in forking and cloning. Maybe add code snippes with actual urls, the thing is depending how you clone, you get a remote with the original one or not. Adding the remote one and learning how to keep it synced will be good.
