### ISSUE TITLE
Waypoint: Create a Bulleted Unordered List

### ISSUE THREAD

**Issue by pikinkz** [FreeCodeCamp/freecodecamp#832]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

After you finish the challenge it won't let you pass saying that "Make sure your li element has a closing tag." even though I have them in place.
![screenshot1](https://cloud.githubusercontent.com/assets/3469292/7976809/c754452e-0aa2-11e5-9dc4-c08dcd99e1c7.png)
It will only let me through when I remove all Classes within <li> tags.
![screenshot2](https://cloud.githubusercontent.com/assets/3469292/7976827/2ad34820-0aa3-11e5-8923-84ee863a1204.png)

**Comment by QuincyLarson** [comment]
Hm... We were actually expecting your input to look more like this: https://www.evernote.com/l/AHRHhVr1X4RMrJtngupnxfNGC19P3HDPipcB/image.png

Do you have screen shots of the full page including tests?

**Comment by QuincyLarson** [comment]
I haven't heard back and am closing this issue. Please resubmit if you encounter this issue again. Thanks!

**Comment by Goyapa** [comment]
i have the exact same issiu as @pikinkz
and as well works if i remove classes  within <li>tags</li>
