### ISSUE TITLE
Spanish translation of Get Started with Free Code Camp Site 

### ISSUE THREAD

**Issue by pcimagenca** [FreeCodeCamp/FreeCodeCamp#8327]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by alistermada** [comment]
There's already a Spanish translation for Get Started with Free Code Camp. Duplicate of #4539.

**Comment by theflametrooper** [comment]
Thanks @alistermada !!
