### ISSUE TITLE
Enabled Site Multilanguage with Json or another format for I18n

### ISSUE THREAD

**Issue by pcimagenca** [FreeCodeCamp/FreeCodeCamp#8328]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@pcimagenca the `.json` files do have areas that allow internationalization. Are you having issues changing the language settings? I'm not understanding your issue.

**Comment by ltegman** [comment]
Closing as stale. Please feel free to reopen with a detailed description of the issue. Thanks and happy coding!
