### ISSUE TITLE
"Iterate Through an Array with a For Loop" not able to complete due to infinite loop & automatic execution

### ISSUE THREAD

**Issue by piyushon2411** [FreeCodeCamp/FreeCodeCamp#8329]
#### Challenge Name

https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop

#### Issue Description

While writing the loop for this challenge, I used a new variable j but instead of doing j++, I mistyped i++. When I ran the code it gave me a warning saying it will go in infinite loop and browser will crash
so I double checked but couldn't find this mistyped letter. So I wrote the comment //noprotect and the browser crashed which is fine. I restarted to correct it but it crashes everytime whenever I go to this challenge due to automatic execution maybe. Not able to complete this one.
for(int j=0; j<myArr.length; **_i++_**)

#### Browser Information

* Browser Name, Version: Chrome 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/7472294/14884577/4704d518-0d63-11e6-95a0-be8057e96a06.PNG)

**Comment by adityaparab** [comment]
This doesn't seem to be an issue with the platform itself. This is a semantic error on part of the programmer.

Your loop control condition `j<myArr.length` is always `true` for value of `j` is left unchanged. Therefore the infinite loop.

`j` is 0. and `j` is always less than `myArr.length` (5) for this condition is independent of `i`, loop ends up being infinite. :)

**Comment by xRahul** [comment]
@piyushon2411 What you can do is-
* run the correct code in a new private window without logging in
* the url will change to reflect the entered solution
* copy the url of the correct solution and now run it in the normal window where you're already logged in.

Let me know if you encounter any problems!

**Comment by erictleung** [comment]
@piyushon2411 thanks for the issue. This isn't a bug, per se. When you mistyped `i++` in your `for` loop, there is no constraint or condition for it to check (yours currently checks the value of `j`, `j < myArr.length`, but not `i`) and `i` will increment to infinity. Thus, you will get an infinite loop. 
If you need more help with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by xRahul** [comment]
@erictleung actually, I think his issue is that the code he wrote is autorun on page load every time he revisits the challenge, due to which the browser crashes and he is unable to write the correct code.

We can do something like preventing that via a url append like-
`http://freecodecamp.com/...``&codeautorun=false`

**Comment by piyushon2411** [comment]
Thanks @xRahul @erictleung for responding promptly. Rahul, your instructions resolved the issue.
