### ISSUE TITLE
where do I belong

### ISSUE THREAD

**Issue by AparnaSE** [FreeCodeCamp/FreeCodeCamp#8330]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20arguments%5B0%5D.sort()%3B%0A%20%20var%20big%3Darguments%5B0%5D%5B0%5D%3B%0A%20%20var%20i%3D0%3B%0A%20%20while(i%3Carguments%5B0%5D.length)%0A%20%20%7B%0A%20%20%20if(big%3E%3Dnum)%0A%20%20%20%7B%20%20%20%20%20%0A%20%20%20%20%20return%20i%3B%0A%20%20%20%7D%0A%20%20%20else%0A%20%20%20%7B%0A%20%20%20%20i%2B%2B%3B%20%20%20%20%20%0A%20%20%20%20big%3Darguments%5B0%5D%5Bi%5D%3B%20%20%20%20%0A%20%20%20%7D%20%20%20%0A%20%20%20%20%20%0A%20%20%7D%0A%20%20return%20i%3B%20%20%20%20%20%0A%7D%0A%0AgetIndexToIns(%5B5%2C%203%2C%2020%2C%203%5D%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.22 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arguments[0].sort();
  var big=arguments[0][0];
  var i=0;
  while(i<arguments[0].length)
  {
   if(big>=num)
   {     
     return i;
   }
   else
   {
    i++;     
    big=arguments[0][i];    
   }   
     
  }
  return i;     
}

getIndexToIns([5, 3, 20, 3], 5);

```
The array is not getting sorted correct

![image](https://cloud.githubusercontent.com/assets/4658310/14893217/1c53bb8a-0d8c-11e6-8ab3-304eab3214a2.png)

**Comment by erictleung** [comment]
@AparnaSE thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: I would make sure you know exactly what `.sort()` is doing by checking [the MDN page on it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). Happy coding!
