### ISSUE TITLE
Adjusting the Padding of an Element 

### ISSUE THREAD

**Issue by surekha88** [FreeCodeCamp/FreeCodeCamp#8333]
#### Challenge Name

Adjusting the Padding of an Element 
[https://www.freecodecamp.com/challenges/adjusting-the-padding-of-an-element#?solution=%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-15px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3A%20red%3B%0A%20%20%20%20padding%3A%2030px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2030px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A]

#### Issue Description

The challenge says "Change the padding of your green box to match that of your red box."
Initially the padding of the red box is 30 px and the padding of the green box is 20 px.
So, we need to change the padding of the green box to 30 px to pass the challenge.

1. But when we do so,the Run Tests is not successful.
2.Below the challenge it says "Your green-box class should give elements 20px of padding." .But it should be "30 px of padding" instead of 20 px.

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/18264442/14895381/4e268b60-0d46-11e6-82e6-81434adf1861.png)

![image](https://cloud.githubusercontent.com/assets/18264442/14895385/535e4a64-0d46-11e6-9812-ef0c1a4c8c3c.png)

**Comment by erictleung** [comment]
@surekha88 mmm not sure how it changed to `30px`, but if you reset your code, the original code shows the `.red-box` having a padding of `20px`. Thus the instructions and tests are consistent. Happy coding!
