### ISSUE TITLE
Better project rule wording

### ISSUE THREAD

**Issue by Atomk** [FreeCodeCamp/FreeCodeCamp#8340]
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage
(this applies to tribute page and portfolio page projects)

#### Issue Description

Some users in the help chat got confused by the project rule:
_You may use your own CSS and frameworks other than Bootstrap._
They thought you must not use Bootstrap, due to ambigue wording. I'd suggest to use something like "You can use Bootstrap, or any other framework of your choice".

**Comment by erictleung** [comment]
@Atomk this issue has been brought up before in #8184 but we didn't change it then. I guess it has been an on-going issue that needs to be changed.

**Comment by dlwebdev** [comment]
Can I take care of this? I'm trying to get involved in the open source community. I have one PR about to be accepted and already have a local dev env set up.

It looks like I would just edit that json file in the seed directory?

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-ziplines.json

    {
      "id": "bd7158d8c242eddfaeb5bd13",
      "title": "Build a Personal Portfolio Webpage",
      "description": [
        "<strong>Objective:</strong> Build a <a href='https://codepen.io' target='_blank'>CodePen.io</a> app that is functionally similar to this: <a href='https://codepen.io/FreeCodeCamp/full/YqLyXB/' target='_blank'>https://codepen.io/FreeCodeCamp/full/YqLyXB/</a>.",
        "<strong>Rule #1:</strong> Don't look at the example project's code. Figure it out for yourself.",
        "<strong>Rule #2:</strong> Fulfill the below <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>user stories</a>. Use whichever libraries you need. Give it your own personal style.",
        "<strong>Rule #3:</strong> You may use your own CSS and frameworks other than Bootstrap.",
        "<strong>User Story:</strong> I can access all of the portfolio webpage's content just by scrolling.",
        "<strong>User Story:</strong> I can click different buttons that will take me to the portfolio creator's different social media pages.",
        "<strong>User Story:</strong> I can see thumbnail images of different projects the portfolio creator has built (if you haven't built any websites before, use placeholders.)",
        "<strong>User Story:</strong> I navigate to different sections of the webpage by clicking buttons in the navigation.",
        "Don't worry if you don't have anything to showcase on your portfolio yet - you will build several apps on the next few CodePen challenges, and can come back and update your portfolio later.",
        "There are many great portfolio templates out there, but for this challenge, you'll need to build a portfolio page yourself. Using Bootstrap will make this much easier for you.",
        "Note that CodePen.io overrides the Window.open() function, so if you want to open windows using jQuery, you will need to target invisible anchor elements like this one: <code>&lt;a target='_blank'&gt;</a></code>.",
        "Remember to use <a href='//github.com/FreeCodeCamp/freecodecamp/wiki/How-to-get-help-when-you-get-stuck' target='_blank'>Read-Search-Ask</a> if you get stuck.",
        "When you are finished, click the \"I've completed this challenge\" button and include a link to your CodePen. ",
        "You can get feedback on your project from fellow campers by sharing it in our <a href='//gitter.im/freecodecamp/codereview' target='_blank'>Code Review Chatroom</a>. You can also share it on Twitter and your city's Campsite (on Facebook)."
      ],

**Comment by erictleung** [comment]
@dlwebdev go for it! Yes, that looks like the correct one.

**Comment by dlwebdev** [comment]
Sweet! 

Will update to "You can use Bootstrap, or any other framework of your choice".

**Comment by dlwebdev** [comment]
Cool, glad to see git commits can be tied to tickets. Setting up PR now.

**Comment by dlwebdev** [comment]
Argh! I've balls upped by fork and I have a PR currently open so I can't destroy my fork and refork yet. 

I will take care of this once that existing PR has cleared.

If someone else wants to go ahead and take care of this, then that's cool.  Everything needed has already been spelled out above, so it's a good first timer change.

**Comment by BrianZ1** [comment]
Hey, do you mind if I take this issue then? This is my first time contributing and I would love to go through the process using an easier issue.

**Comment by dlwebdev** [comment]
Go for it dude!

**Comment by Atomk** [comment]
@BrianZ1 @BrianZ1 Keep in mind the message is shown both in the Tribut challenge and the Portfolio challenge, I don't know if it is shown in other front-end challenges as well.

**Comment by wendu77** [comment]
Go to www.withwendu.com if you need any custom orders for affordable design prices!!

**Comment by raisedadead** [comment]
@wendu77 please do not spam issue trackers on Github.
