### ISSUE TITLE
mispelling - extra quote in instructions. for "Escaping Literal Quotes in Strings"

### ISSUE THREAD

**Issue by spencer1573** [FreeCodeCamp/FreeCodeCamp#8341]
#### Challenge Name
https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=var%20myStr%3B%20%2F%2F%20Change%20this%20line%0A%0AmyStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%0A

#### Issue Description

Mispelling
there is just an extra quote in the at the very bottom of the instructions
it says:
Variable myStr should equal to ("I am a "double quoted" string inside "double quotes"").
it should read:
Variable myStr should equal to ("I am a "double quoted" string inside "double quotes").

#### Browser Information

any browser
* Browser Name, Version: any
* Operating System: any
* Mobile, Desktop, or Tablet: any

#### Your Code
not relevent

#### Screenshot

![screen shot 2016-04-28 at 5 49 21 pm](https://cloud.githubusercontent.com/assets/4762850/14904955/95570424-0d69-11e6-9218-3becd66b095e.png)

**Comment by erictleung** [comment]
@spencer1573 the second quotation matches the beginning quote before the `I` so there is no typo. Happy coding!

**Comment by spencer1573** [comment]
totally didn't see that! oops!

**Comment by tchinburg** [comment]
grammatically there is a typo.   no punctuation to end the sentence.
