### ISSUE TITLE
Can't see my solutions to problems beyond "Get Set for our Algorithm Challenges"

### ISSUE THREAD

**Issue by stomperstomp** [FreeCodeCamp/FreeCodeCamp#8343]
I want to review my solutions to previous problems, specifically those in the Basic Scripting Challenges, but I can't. Clicking on the [number] only shows solutions up to "Get Set for our Algorithm Challenges"

Is this intentional?

**Comment by erictleung** [comment]
@stomperstomp the [number] I think that you're referring to is just the number of challenges you've completed. If you click on that number, it'll bring you to your profile page where you can view your challenge solutions. Does that guide you to the correct place?

**Comment by stomperstomp** [comment]
@erictleung 

Yes, that functionality works fine. I know what it's supposed to do. The issue is, that I have completed tasks in the Basic Scripting Challenges, but can't view the solutions. The solutions that are accessible and linked, end at the task "Get Set for our Algorithm Challenges," nothing beyond it.

**Comment by alistermada** [comment]
@stomperstomp The algorithms are in their own table above the rest of the challenges. I'm looking at your profile and I see that your latest completed algorithm is Slasher Flick. Is that correct?

**Comment by stomperstomp** [comment]
Oh, you are correct! I missed it. I just automatically scroll to the bottom since I assumed all exercises were listed together chronologically.

I'm not sure if you guys take UI/UX suggestions, but I'm happy to elaborate further as I do UX design, if  that would help.

**Comment by alistermada** [comment]
@stomperstomp FCC's open to [UI/UX suggestions](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3AUX). Feel free to comment or create a new issue if your suggestion isn't relevant to existing issues.

**Comment by raisedadead** [comment]
Looks like this is resolved. 

@stomperstomp You may reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors) for any suggestions, and as always open an issue with your feedback.

@alistermada Thanks for looking into this.
