### ISSUE TITLE
Console log hangs when i run the test

### ISSUE THREAD

**Issue by rudolfpablico** [FreeCodeCamp/FreeCodeCamp#8344]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20var%20strarray%20%3D%20%5B%5D%3B%0A%20%20var%20strupper%20%3D%20%5B%5D%3B%0A%20%20var%20strlower%20%3D%20str.toLowerCase()%3B%20%2F%2F%20make%20str%20all%20lowercase%0A%20%20strarray%20%3D%20strlower.split(%22%20%22)%3B%20%2F%2F%20split%20str%20into%20an%20array%20element%0A%20%20%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20strarray.length%3B%20i%2B%2B)%20%7B%20%2F%2Faccess%20all%20the%20elements%20in%20strarray%0A%0A%20%20%20%20%20%20strupper%20%3D%20strarray%5Bi%5D%5B0%5D.toUpperCase%3B%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20return%20strupper%3B%0A%2F%2F%20return%20strarray%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  var strarray = [];
  var strupper = [];
  var strlower = str.toLowerCase(); // make str all lowercase
  strarray = strlower.split(" "); // split str into an array element
  
  for (var i = 0; i < strarray.length; i++) { //access all the elements in strarray

      strupper = strarray[i][0].toUpperCase; 
  }
  
  
  return strupper;
// return strarray;
}

titleCase("I'm a little tea pot");
```

**Comment by erictleung** [comment]
@rudolfpablico there is an error in your code that is throwing an undefined error. Check to make sure you're using calling every method correctly. If you're still stuck with the challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
