### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by aniketchitodkar** [FreeCodeCamp/FreeCodeCamp#8346]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20color%3Agreen%3B%0A%20%20%7D%0A%20%20pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
   color:green;
  }
  pink-text {
    color: pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by erictleung** [comment]
@aniketchitodkar there is actually an error within your `<style>` element. If you are still stuck with the challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
