### ISSUE TITLE
Map and Chat Sidebars don't appear on Hikes

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/FreeCodeCamp#8349]
**Normal Challenges:**

![](https://i.gyazo.com/ede57b62ba2b2c03ab39073417e8a3e6.gif)

**Hikes:**

![](https://i.gyazo.com/988ae95e7e447264f230cbb0fe862fcb.gif)

**Comment by alistermada** [comment]
This was mentioned in #6910.

**Comment by theflametrooper** [comment]
Thanks @alistermada, closing as duplicate.
