### ISSUE TITLE
"Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by kevonturner** [FreeCodeCamp/freecodecamp#835]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue.  Every time I try and submit my code i encounter this issue, it is clearly not to with my programming as there was no javascript involved in the waypoint and my code works exactly as intended by the directions outside the website.

**Comment by QuincyLarson** [comment]
@kevonturner I can't reproduce this issue. It works fine for me. Could you send me a screen shot? Which browser are you using? Thanks!

**Comment by QuincyLarson** [comment]
I haven't heard back so I am closing this issue. Please reopen it if you can help us reproduce it. Thanks for your help!
