### ISSUE TITLE
Goals completed, showing syntax error

### ISSUE THREAD

**Issue by Pellicove** [FreeCodeCamp/FreeCodeCamp#8352]
Shopping List Challenge
https://www.freecodecamp.com/challenges/shopping-list#?solution=var%20myList%20%3D%20[[%22cigarette%20cartons%22%2C%201]%2C%20[%22ramen%20noodles%22%2C%20328]%2C%20[%22mystic%20literature%22%2C%20090]%2C%20[%22coffee%22%2C%203]%2C%20[%22cans%20of%20tuna%22%2C%208]]%3B%0A%0A%0A

I've completed the goals. Challenge registers:
SyntaxError: octal literals and octal escape sequences are deprecated

Desktop, Firefox

var myList = [["cigarette cartons", 1], ["ramen noodles", 328], ["mystic literature", 090], ["coffee", 3], ["cans of tuna", 8]];

**Comment by theflametrooper** [comment]
@Pellicove This appears to be an issue for me on firefox also! Not appearing on chrome or internet explorer though.

**Comment by Pellicove** [comment]
What do you suggest I do?

**Comment by theflametrooper** [comment]
@Pellicove We're currently trying to resolve this problem.
For now you can just change the number in `["mystic literature", 090]`.

**Comment by Pellicove** [comment]
Thank you.

**Comment by hallaathrad** [comment]
@theflametrooper I've spoken to a contact in my local Mozilla office, and he's suggested we submit a bug report on their site (for this and other confirmed FF specific issues).

**Comment by QuincyLarson** [comment]
@hallaathrad @atjonathan did we ever end up submitting a bug to Firefox? I'm going to close this issue for now, as it sounds like it's not specific to our platform.
