### ISSUE TITLE
This is not bug just something I noticed

### ISSUE THREAD

**Issue by Saymon85** [FreeCodeCamp/FreeCodeCamp#8355]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=function%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20%0A%20%20%2F%2Freturn%20str.endsWith(target)%3B%20-%20more%20elegant%20way%0A%20%20%2F*%0A%20%20if(str.endsWith(target))%7B%0A%20%20%20%20return%20true%3B%20%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%20*%2F%0A%20%20%0A%20%20var%20str2%20%3D%20str.substr(str.length%20-%20target.length)%3B%0A%20%20%0A%20%20if(str2%20%3D%3D%3D%20target)%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%20%0A%20%20%0A%20%20%0A%0AconfirmEnding(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  
  //return str.endsWith(target); - more elegant way
  /*
  if(str.endsWith(target)){
    return true; 
  }
  else{
    return false;
  } */
  
  var str2 = str.substr(str.length - target.length);
  
  if(str2 === target){
    return true;
  }
  else{
    return false;
  }
} 
  
  

confirmEnding("Bastian", "n");

```

Hello FCC,

I noticed that this challenge have some very simple solution which uses endsWith(http://www.w3schools.com/jsref/jsref_endswith.asp) JavaScript method to resolve this problem, so I would like to point that this challenge dosen't make sense when you can do it in one line of code. I'm sorry if I posted this on wrong place or bothering someone too much.

Kind regards,
Nemanja

**Comment by erictleung** [comment]
@Saymon85 thanks for your consideration. There's already been a discussion here #4764. Closing as duplicate. Happy coding!
