### ISSUE TITLE
Error accepting my code and continuing in spite of it being correct

### ISSUE THREAD

**Issue by isaacionescu** [FreeCodeCamp/FreeCodeCamp#8358]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another) has an issue.
**The h1 is changed to pink, all code is fine, but the first two requirements are interpreted as not being completede and the proceed button just doesn't work. Don't know if local issue or the site is down. Restarted chrome, tried incognito, tried it in Firefox - same result: neither pressing the 'Run tests' nor hitting ctrl+enter works anymore**
![proof](https://cloud.githubusercontent.com/assets/17751456/14931773/be4189e6-0e76-11e6-9d92-2d1cdd6de64f.png)
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.

**My code:**
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  
  .pink-test {
    color: pink;
  }
</style>
<body>
<h1 class="pink-test">Hello World!</h1>
</body>

```

**Comment by theflametrooper** [comment]
You have a typo in your class name. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help in future. Happy Coding!

**Comment by isaacionescu** [comment]
oh god im fucking autistic. sorry, its late @ night. gonna delete this.
