### ISSUE TITLE
Customize Google Calendar

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#836]
It's possible to make our event calendar (freecodecamp.com/twitch) look a lot better with an interface like this: http://www.necessaryarts.ca/#!workshops/ctzx

Here's how to do this: http://www.webdesignerdepot.com/2012/04/integrating-google-calendar-with-your-website/

Anyone interested in taking a crack at this?

**Comment by mikemimik** [comment]
@storbeck I nominate you, sir.

**Comment by LumenTeun** [comment]
I could take a crack at this, as long as I can leave the design choices up to someone else. Do you want the calendar to look exactly like the one in the Necessary Arts link, and if so, is that legal? I'm seeing a `© All Rights Reserved` notice in the footer.

**Comment by QuincyLarson** [comment]
We are shelving Google Calendar integration for now and removing this page our Twitch.tv page from Free Code Camp (and simply redirecting to Twitch)

**Comment by ahstro** [comment]
Maybe ditch the "help wanted"-tag as well? :)
