### ISSUE TITLE
I thik all the parameter that areinputs in the fuctions arent arrays

### ISSUE THREAD

**Issue by licontre** [FreeCodeCamp/FreeCodeCamp#8365]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0Avar%20n%3D%5B%5D%3B%0A%20%20var%20pos%3D0%3B%0A%20%20var%20j%3D1%3B%0A%20%20var%20put%3Dtrue%3B%0A%20%20%0A%20%20for(var%20i%3D0%3Bi%3Carr%5B0%5D.length%3Bi%2B%2B)%7B%0A%20%20%20%20while(j%3Carr.length%20%26%26%20put%3D%3D%3Dtrue)%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if(arr%5B0%5D%5Bi%5D%3D%3D%3Darr%5Bj%5D)%7B%0A%20%20%20%20%20%20%20%20%20put%3Dfalse%3B%20%20%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20j%2B%2B%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20if(put%3D%3D%3Dtrue)%7B%0A%20%20%20%20%20%20n%5Bpos%5D%3Darr%5B0%5D%5Bi%5D%3B%0A%20%20%20%20%20%20pos%2B%2B%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20put%3Dtrue%3B%0A%20%20%20%20j%3D1%3B%0A%20%20%20%20%20%7D%0A%20%20return%20n%3B%7D%0A%0Adestroyer(%5B%5B%22tree%22%2C%20%22hamburger%22%2C%2053%5D%2C%20%22tree%22%2C%2053%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  // Remove all the values
var n=[];
  var pos=0;
  var j=1;
  var put=true;
  
  for(var i=0;i<arr[0].length;i++){
    while(j<arr.length && put===true){
      
      if(arr[0][i]===arr[j]){
         put=false;   
      }
       j++;
      }
    
    
    if(put===true){
      n[pos]=arr[0][i];
      pos++;
      
    }
    
    put=true;
    j=1;
     }
  return n;}

destroyer([["tree", "hamburger", 53], "tree", 53]);
```

**Comment by theflametrooper** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
