### ISSUE TITLE
when the  value is null, the boolean dont work

### ISSUE THREAD

**Issue by licontre** [FreeCodeCamp/FreeCodeCamp#8366]
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don't%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20var%20o%20%3D%20%20Boolean%5B5%5D%20%3D%5Bfalse%2C%20null%2C0%2C%22%22%2Cundefined%2CNaN%5D%3B%0A%20%20%0A%20%20var%20pos%3D0%3B%0A%20%20var%20narr%3D%5B%5D%3B%20%20%0A%20%20var%20i%3D0%3B%0A%20%20var%20ok%3Dtrue%3B%0A%20%20%0A%20%20for(var%20j%3D0%3Bj%3Carr.length%3Bj%2B%2B)%7B%0A%20%20%20%20%0A%20%20%20%20%20while(i%3C6%26%26ok%3D%3D%3Dtrue)%7B%0A%20%20%20%20%20%20%20%20%20%20if(arr%5Bj%5D%3D%3D%3Do%5Bi%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20ok%3Dfalse%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20if(arr%5Bj%5D%3D%3D%3Dnull)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20ok%3Dfalse%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20i%2B%2B%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20if(ok%3D%3D%3Dtrue)%7B%0A%20%20%20%20%20%20%20narr%5Bpos%5D%3Darr%5Bj%5D%3B%0A%20%20%20%20%20%20%20pos%2B%2B%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%20%20i%3D0%3B%0A%20%20%20%20%20%20ok%3Dtrue%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%0A%20%20%0A%20%20%20%20%0A%20%20return%20narr%3B%0A%7D%0A%0Abouncer(%5B1%2C%20null%2C%20NaN%2C%202%2C%20undefined%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function bouncer(arr) {
  // Don't show a false ID to this bouncer.
 var o =  Boolean[5] =[false, null,0,"",undefined,NaN];
  
  var pos=0;
  var narr=[];  
  var i=0;
  var ok=true;
  
  for(var j=0;j<arr.length;j++){
    
     while(i<6&&ok===true){
          if(arr[j]===o[i]){
             ok=false;
          }
           if(arr[j]===null){
              ok=false;
             
          }
       i++;
       }
           
    
    if(ok===true){
       narr[pos]=arr[j];
       pos++;
    }
    
      i=0;
      ok=true;
  }
  
  

  
    
  return narr;
}

bouncer([1, null, NaN, 2, undefined]);

```

**Comment by theflametrooper** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
