### ISSUE TITLE
testNotEqual Not Working

### ISSUE THREAD

**Issue by uotou** [FreeCodeCamp/FreeCodeCamp#8367]
#### Challenge Name
https://www.freecodecamp.com/challenges/comparison-with-the-inequality-operator#?solution=%2F%2F%20Setup%0Afunction%20testNotEqual(val)%20%7B%0A%20%20if%20(val%20!%3D%20'99')%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Not%20Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestNotEqual(10)%3B%0A

#### Issue Description
Use (val != "99")
Ctrl-Enter

#### Browser Information
* Browser Name, Version: Chrome
* Operating System: Windows 10
* Laptop 

#### Your Code
// Setup
function testNotEqual(val) {
  if (val != '99') { // Change this line
    return "Not Equal";
  }
  return "Equal";
}

// Change this value to test
testNotEqual(10);

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/1214448/14936495/d993111a-0f20-11e6-9f20-c087f0441daf.png)

**Comment by theflametrooper** [comment]
Your if statement should include a `number` not a `string`. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
