### ISSUE TITLE
Cursor lies on the correct line, but typing is on the line below

### ISSUE THREAD

**Issue by bradarv90** [FreeCodeCamp/FreeCodeCamp#8371]
Challenge [Warn your Users of a Dangerous Action](https://www.freecodecamp.com/challenges/warn-your-users-of-a-dangerous-action) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive">
  <button class="btn btn-block btn-primary">Like</button>
  <button class="btn btn-block btn-info">Info</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

If I clicked in on the line that reads ```<img src="https://bit.ly/fcc-running-cats" class="img-responsive">``` at the end, my cursor would appear as far as the line below it goes. Then when I type, the cursor will move down a line and begin typing there. See the below gif that demonstrates exactly what's happening. This issue isn't just with this page; it appears to be happening on every page where the text doesn't wrap around. 

[gif](http://i.imgur.com/Q62grIs.gifv)

**Comment by erictleung** [comment]
@bradarv90 thanks for the issue. This is an issue with CodeMirror, which is what we use to emulate an editor in the browser, rather a problem FCC can fix ourselves. Closing as this is a duplicate issue #7847. Happy coding otherwise!

**Comment by Shwrndasink** [comment]
I have the same or similar issue. Each step I go to, the editor will not allow me to edit the line I want. When I hit the reset, it works as expected but is kind of frustrating doing this on each new challenge.
