### ISSUE TITLE
"Where do I Belong" not accepting answer that passes all test cases

### ISSUE THREAD

**Issue by winkelman** [FreeCodeCamp/FreeCodeCamp#8375]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=function%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20arr.sort(function(a%2C%20b)%20%7Breturn%20a%20-%20b%3B%7D)%3B%0A%20%20var%20tooBig%20%3D%20true%3B%0A%20%20%0A%20%20for(var%20index%20in%20arr)%20%7B%0A%20%20%20%20if(num%20%3C%3D%20arr%5Bindex%5D)%20%7B%0A%20%20%20%20%20%20tooBig%20%3D%20false%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20if(tooBig)%20%7B%0A%20%20%20%20index%2B%2B%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2Farr.splice(index%2C%200%2C%20num)%3B%0A%20%20return%20index%3B%0A%7D%0A%0A%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arr.sort(function(a, b) {return a - b;});
  var tooBig = true;
  
  for(var index in arr) {
    if(num <= arr[index]) {
      tooBig = false;
      break;
    }
  }
  
  if(tooBig) {
    index++;
  }
  
  //arr.splice(index, 0, num);
  return index;
}


getIndexToIns([40, 60], 50);

```

**Comment by winkelman** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12734117/14941235/31f55390-0f49-11e6-9d54-be63fdbeeca0.png)

Running the first test results in '3' but the grader doesn't recognize this

**Comment by BKinahan** [comment]
There are several issues with your code, but the crucial error is that you are returning a string, not a number. Changing the return line to `return +index;` (or any method of converting the string to an integer) allows the code to pass.

Please consult the [JavaScript help chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for further assistance. Happy coding!

**Comment by winkelman** [comment]
My apologies, had some confusion about the data type of the index and the usage of `for... in` vs `for` loops.  I see now that `for... in` is for properties of an object.  Consequently a simple `for` loop solves the out of bounds hack from before:

```
for(var i = 0; i < arr.length; i++) {
    if(num <= arr[i]) {
      break;
    }
  }
```
