### ISSUE TITLE
in creating this notation the var value and obj seem not to converse

### ISSUE THREAD

**Issue by DamianMitchell** [FreeCodeCamp/FreeCodeCamp#8378]
Challenge [Accessing Objects Properties with Bracket Notation](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-bracket-notation#?solution=%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20%22an%20entree%22%3A%20%22hamburger%22%2C%0A%20%20%22my%20side%22%3A%20%22veggies%22%2C%0A%20%20%22the%20drink%22%3A%20%22water%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20entreeValue%20%3D%20testObj%5B%22entree%22%5D%3B%20%20%20%2F%2F%20Change%20this%20line%20%0Avar%20drinkValue%20%3D%20testObj%5B%22drink%22%5D%3B%20%20%20%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
var testObj = {
  "an entree": "hamburger",
  "my side": "veggies",
  "the drink": "water"
};

// Only change code below this line

var entreeValue = testObj["entree"];   // Change this line 
var drinkValue = testObj["drink"];    // Change this line

```

**Comment by raisedadead** [comment]
@DamianMitchell Thanks for reporting this.

However I am not sure whats the issue, can you please describe more clearly? On a side note the code is incorrect.

P.S : Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) as well.

**Comment by ltegman** [comment]
It looks like you're not accessing the properties of the object with the correct keys. Closing as not a site bug. Thanks and happy coding!
