### ISSUE TITLE
Order of padding in css

### ISSUE THREAD

**Issue by AtomicTea** [FreeCodeCamp/freecodecamp#838]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

If the order of padding is anything other than top, right, bottom left, you get an error. This isn't explained in the documentation, and I don't think it has to be in this order right?
![screen shot 2015-06-04 at 12 51 05 pm](https://cloud.githubusercontent.com/assets/7680754/7990815/1699a2d0-0ab9-11e5-99cf-e58f85c903e4.png)

**Comment by QuincyLarson** [comment]
Hi @atomictea you made a typo. You're missing a semicolon in your screen shot. I just verified this works fine in any sequence in Firefox and Chrome. Thanks anyway for submitting the issue.
