### ISSUE TITLE
`Pull request guideline` Link is broken

### ISSUE THREAD

**Issue by meetmangukiya** [FreeCodeCamp/FreeCodeCamp#8385]
#### Issue Description

In the wiki link on FCC homepage in the navbar , the link to [Pull request quideline](https://freecodecamp.github.io/wiki/en/PULL_REQUEST_TEMPLATE) is broken.
The link is https://freecodecamp.github.io/wiki/en/PULL_REQUEST_TEMPLATE

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: 
I don't think it has got to do with any of this specifications
#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![capture2](https://cloud.githubusercontent.com/assets/7620533/14947204/1641ab44-104d-11e6-9bbe-4b49c1ca538b.JPG)

**Comment by erictleung** [comment]
@meetmangukiya thanks for the issue but I can't figure out which FCC homepage wiki link you are referring to. Are you talking about from the www.freecodecamp.com website or the GitHub website?

**Comment by sludge256** [comment]
This issue is present on the website wiki, and on the GitHub wiki at https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki.

It's already been reported on the Wiki repo: https://github.com/FreeCodeCamp/wiki/issues/818

Thanks for reporting this @meetmangukiya.
