### ISSUE TITLE
Upon loading a new challenge, codemirror editor's cursor blinking, but it isn't selected upon 

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8388]
Each time a challenge loads, I want to immediately be able to start typing. It looks like the codemirror textarea (code editor) is already selected because my cursor is blinking. But it isn't. I have to use my mouse to click in the code editor.

@benmcmahon100 This is a new regression, and it may be caused by night mode or hotkeys.

**Comment by benmcmahon100** [comment]
@QuincyLarson unfortunately, this issue pre-dates night mode and the hot keys. I believe an issue was opened on code mirror about it.

**Comment by benmcmahon100** [comment]
I can take a look at it later today

**Comment by bugron** [comment]
I can't reproduce this issue neither in Firefox 46 nor in Chrome 50. Closing.
