### ISSUE TITLE
Waypoint: Style Multiple Elements with a CSS Class text needs updating

### ISSUE THREAD

**Issue by jrniemijr** [FreeCodeCamp/freecodecamp#839]
On the "Waypoint: Style Multiple Elements with a CSS Class", the description in More Information has a paragraph that shows css class named .red-text but the property is value is set to blue and then the class is later called blue-text. The lesson was to set red text.

![image](https://cloud.githubusercontent.com/assets/1591379/7991395/d98d78aa-0ac5-11e5-9b40-beb66e70cae9.png)

**Comment by QuincyLarson** [comment]
This is indeed a typo. I'm fixing it now! Thanks!
