### ISSUE TITLE
Pig Latin - 2nd example not completely visible

### ISSUE THREAD

**Issue by keks411** [FreeCodeCamp/FreeCodeCamp#8390]
#### Challenge Name
https://www.freecodecamp.com/challenges/pig-latin

#### Issue Description

Second Example is not completely visible and therefore makes no sense.

_translatePigLatin("paragraph") should return "aragraphspay". _

As you can see the "s" in **paragraphs** is missing. The example should look like:

_translatePigLatin("paragraphs") should return "aragraphspay". _

Screenshot:
http://www.pic-upload.de/view-30530569/Screenshot_20160502_114947.png.html

#### Browser Information

* Browser Name, Version:  Firefox 46.0
* Operating System: Kubuntu 16.04 KDE
* Mobile, Desktop, or Tablet: HP Elitebook (1366x768)

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by raisedadead** [comment]
Yeah I agree, this is indeed a problem. This is not just about the single line code that's lengthy and is bleeding out of the view.

I understand that the HTML & CSS challenges needed more space on the right for the iPhone preview widget, on the Algorithms we can perhaps make the width of the editor a bit smaller and expand the instructions view a bit more, to accommodate in a 30:70 ratio. 

The instructions area is a bit crunched while we have so much real estate on the right for the editor.

/cc @FreeCodeCamp/issue-moderators

**Comment by erictleung** [comment]
@raisedadead a quick and dirty fix for this particular challenge would be to shorten the function name. I'm sure there are more challenges like this so we could implement this as a quick fix until we want to make a more systemic fix. But I'm all for a more permanent fix of adding giving more room to the instructions if it isn't too hard to implement.

Although we are already having growing pains in changing function names, this challenge is unique enough to just be `pigLatin` or something. Here are some suggestions and how they look.

**Before**

![image](https://cloud.githubusercontent.com/assets/2754821/14953858/614a4e14-1022-11e6-84c1-0a8f3382faeb.png)

**After**

![image](https://cloud.githubusercontent.com/assets/2754821/14953930/168bb358-1023-11e6-9b7d-5c54c4e06cea.png)

**Comment by raisedadead** [comment]
I like the `pigLatin` one! :fire: 

@hallaathrad can you guide if would be too costly to have a permanent fix, rather than depending on the function names to be shorter?

If its way too costly in terms of efforts I guess changing names would be faster.

**Comment by BKinahan** [comment]
As mentioned by @erictleung in #9577, it's possible this may be closed by #9247
