### ISSUE TITLE
Inconsistency of challenge's description

### ISSUE THREAD

**Issue by PizzaVillain** [FreeCodeCamp/FreeCodeCamp#8392]
#### Challenge Name

https://www.freecodecamp.com/challenges/declare-javascript-variables#?solution=%0A%2F%2F%20Example%0Avar%20ourName%3B%0A%20%0A%2F%2F%20Define%20myName%20below%20this%20line%0A%0A

#### Issue Description

> In computer science, data is anything that is meaningful to the computer. 
JavaScript provides seven different data types which are 
undefined, null, **Boolean**, string, symbol, number, and object.

Quote above is challenge's description.
Only boolean use UpperCase 'Boolean' but other data types are not.
It's better to use lowercase for consistency.

**Comment by theflametrooper** [comment]
cc/ @FreeCodeCamp/issue-moderators Should we have all data types as `Title Case` or `Lowercase`?

**Comment by raisedadead** [comment]
I am almost tempted to close this as bikeshedding, but that's just me.

**Comment by erictleung** [comment]
I was thinking all title case. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) talks about objects with title case. @raisedadead I can see this as bikeshedding as well but I like consistency 😄  Plus, this isn't too difficult of a change. But that's just me 😄

**Comment by theflametrooper** [comment]
@erictleung @raisedadead `Title Case` it is! PR incoming...

**Comment by SaintPeter** [comment]
Note that "undefined" and "null" should not be capitalized.  If you capitalize them in code it will break.

**Comment by theflametrooper** [comment]
@SaintPeter thanks for that! I'll submit a PR asap ;)
