### ISSUE TITLE
Two modules are misplaced.

### ISSUE THREAD

**Issue by albert2309** [FreeCodeCamp/FreeCodeCamp#8395]
http://imgur.com/SeJ2P0L

As you can see on the right side, the "Intermediate Algorithm Scripting" should be before the "Advanced Algorithm Scripting", but when I refreshed the page, the right window shown in proper order.

**Comment by theflametrooper** [comment]
@albert2309 Thanks for reporting this issue! I have confirmed this issue on Chrome and Firefox.

**Comment by albert2309** [comment]
No problem!
Do you want me to confirm the bug on Opera and IE too?

**Comment by theflametrooper** [comment]
@albert2309 Sure, go ahead :laugh:

**Comment by albert2309** [comment]
https://imgur.com/a/qoulb 
the bug also occured in IE and Opera

**Comment by thorstenschaefer** [comment]
Can confirm it for Safari. Also, I just finished Advanced but cannot submit the last task - I guess it might be because I haven't touched the intermediate algorithm scripting part yet (the test succeeds but the submit button is disabled)?
