### ISSUE TITLE
Unnecessary GitHub challenge when logged in by GitHub account

### ISSUE THREAD

**Issue by michal-szepielak** [FreeCodeCamp/FreeCodeCamp#8396]
The challenge of creating GitHub account is important only for those who doesn't have GitHub account. Please consider skipping this step for users who are already logged in to FCC by GitHub account. I think it will improve UX a little bit.

#### Challenge Name

https://www.freecodecamp.com/challenges/create-a-github-account-and-join-our-chat-rooms

**Comment by gasperno** [comment]
Among the 9 steps for that challenge, 
1 - Introduction to why github is needed
2 & 3 - create github account and how to add some details
4 - Star repository 
5, 6, 7, 8, 9 - chatter rooms, configure notification settings and details related to chatrooms
Only steps 2 & 3 deal wih Github account creation.
@michal-szepielak I think this is a good introduction to chatrooms.

**Comment by michal-szepielak** [comment]
@gasperno it's ok to keep this challenge as a chat room introduction. However the github part could be hidden for github users. They have already did it in the past. I think the good feature would be, if backend could check if user has starred the project and hide/show the 4th step.

The first step doesn't explain why github is needed. Anyway I couldn't find this information.

**Comment by BerkeleyTrue** [comment]
These are optional challenges, you are not required to completed them. If you already have a github account you can skip it.
