### ISSUE TITLE
The array.splice() method by itself passes the challenge.

### ISSUE THREAD

**Issue by skinnercodecamp** [FreeCodeCamp/FreeCodeCamp#8398]
Challenge [Slasher Flick](https://www.freecodecamp.com/challenges/slasher-flick#?solution=%0Afunction%20slasher(arr%2C%20howMany)%20%7B%0A%20%20arr.splice(0%2C%20howMany)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0Aslasher(%5B1%2C%202%2C%20%22chicken%22%2C%203%2C%20%22potatoes%22%2C%20%22cheese%22%2C%204%5D%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function slasher(arr, howMany) {
  arr.splice(0, howMany);
  return arr;
}

slasher([1, 2, "chicken", 3, "potatoes", "cheese", 4], 5);

```
This code by itself appears to solve all of the test cases, and I don't know if this is simply something that I don't understand about arr.splice(), or if there's something subtle going on here.

I'm guessing that the splice method takes out 'howMany' number of the elements starting at the desired element, and continues until completed?

If this is just a comprehension thing, please disregard and close.

**Comment by theflametrooper** [comment]
@skinnercodecamp Checkout the documentation for the `splice` method here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice.

Closing because this is not an issue with the site.

**Comment by moltrex** [comment]
managed to rezolve this only using splice ... no slice needed ...

> function slasher(arr, howMany) {
  // it doesn't always pay to be first
  
  if(arr.length - howMany >= 0 ){ 
    arr = arr.splice(howMany, arr.length);
  }else{
    arr = [];
  }
 
  return arr;
}

slasher([1, 2, 3], 2);
