### ISSUE TITLE
bash: expressworks: command not found

### ISSUE THREAD

**Issue by malaymj** [FreeCodeCamp/FreeCodeCamp#8399]
![expressworks not found](https://cloud.githubusercontent.com/assets/12676312/14961553/c7ef57aa-10b7-11e6-9956-346606fa88b0.jpg)
Challenge [Build Web Apps with Expressjs](https://www.freecodecamp.com/challenges/build-web-apps-with-expressjs) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Started working on build-web-apps-with-expressjs.After 1st step of  running this command:-
git clone https://github.com/FreeCodeCamp/fcc-expressworks.git && chmod 744 fcc-expressworks/setup.sh && fcc-expressworks/setup.sh && source ~/.profile

"expressworks" command does not work and throws error as:bash: expressworks: command not found

Screenshot attached for clarity.

**Comment by raisedadead** [comment]
@malaymj Thanks for reporting this, A fix is on its way.
As a work around for the time being first do a :
`nvm install v4.1`

then

you can run the setup script again :

`chmod 744 fcc-expressworks/setup.sh && fcc-expressworks/setup.sh && source ~/.profile`

**Comment by Gkleinereva** [comment]
Heads up: this appears to still be an issue as of 4/25/2018.  This fix worked though.
