### ISSUE TITLE
Coursewares Confirming Prematurely

### ISSUE THREAD

**Issue by brndnb** [FreeCodeCamp/freecodecamp#84]
When typing the correct solution into the second courseware challenge (http://www.freecodecamp.com/coursewares/use-the-h2-element), I am congratulated before I have closed the h2 tag. The congratulations modal pops up once I have typed this much:

![screen shot 2015-02-09 at 9 24 39 am](https://cloud.githubusercontent.com/assets/7098232/6109078/e8652108-b03d-11e4-9951-9e8edba6fb4b.png)

If I click away from the modal, I am able to complete the tag, and then the modal pops up again. I'm assuming whatever regex or otherwise that is checking this needs some tweaking?

**Comment by brndnb** [comment]
To confirm, I just rechecked this after the latest push to Heroku and it still exists. I will take a look at the regex later today if you don't get to it first. The same issue happens on the subsequent <p> challenge.

**Comment by terakilobyte** [comment]
This is a side effect of the browser being helpful and rendering the element even though it's technically incomplete, as far as I can tell. Unless over-ruled, it's something I'm willing to live with as the alternative is to pattern match the entire document body vs. just checking an individual element.

**Comment by QuincyLarson** [comment]
As @terakilobyte said, it's the browser's fault that it's so robust and user-friendly! We're planning to remove the success modal from the completion page and replace it with a more subtle button that appears when all tests are passing. That way, even though all tests are passing, you can still easily finish closing the tag before proceeding.
