### ISSUE TITLE
contradictory conditions ?

### ISSUE THREAD

**Issue by ufairiya** [FreeCodeCamp/FreeCodeCamp#8400]
Remove all the backslashes
Only remove the backslashes \ used to escape quotes.

both of the above seems contradictory and the challenge could not be completed. please clarify

Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20'%3Ca%20href%3D%22http%3Awww.example.com%22'%2B%22%20target%3D_blank%3ELink%3Ca%3E%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = '<a href="http:www.example.com"'+" target=_blank>Link<a>";



```

**Comment by theflametrooper** [comment]
@ufairiya 
Read this test: `Only remove the backslashes \ used to escape quotes`. There is something wrong with your closing `anchor` tag.
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
