### ISSUE TITLE
Invalid link on Binary Agents challenge page that should direct to Mozilla documentation instead

### ISSUE THREAD

**Issue by Scripore** [FreeCodeCamp/FreeCodeCamp#8403]
#### Binary Agents
https://www.freecodecamp.com/challenges/binary-agents

#### Issue Description
One of the help links that's suppose to direct to Mozilla documentation on String.charCodeAt() instead points to https://www.freecodecamp.com/challenges/undefined

#### Browser Information
* Browser Name, Version: Chrome
* Operating System: OS X
* Mobile, Desktop, or Tablet: Desktop

**Comment by theflametrooper** [comment]
This issue is similar to #8402. We'll keep both of them open as their referencing different challenges.
