### ISSUE TITLE
CatPhotoApp

### ISSUE THREAD

**Issue by raysichic** [FreeCodeCamp/FreeCodeCamp#8404]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EI%27m%20a%20p%20tag!%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>I'm a p tag!</p>
```

**Comment by dwd2010** [comment]
@raysichic 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
