### ISSUE TITLE
Two Scroll Bars Overlapping

### ISSUE THREAD

**Issue by albert2309** [freeCodeCamp/freeCodeCamp#8408]
#### Challenge Name

[Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather)
#### Issue Description

Unless I use my touchscreen display, I cannot scroll down the map because the scroll bar is overlapping with the page's scroll bar.
#### Browser Information

- Browser Name, Version:  Internet Explorer 11
- Operating System: Windows 8.1
- Mobile, Desktop, or Tablet: Desktop

https://imgur.com/DYZeSJA

**Comment by raisedadead** [comment]
@albert Thanks for reporting this.
Can you also guide if this is specific to IE or on other browsers as well?

**Comment by Albert** [comment]
I think you mean @albert2309, not @albert

**Comment by albert2309** [comment]
@raisedadead Only IE. Other browsers works well.

**Comment by raisedadead** [comment]
@Albert Ooops! Apologies! :sweat_smile: 

@albert2309 Thanks for letting us know!

**Comment by QuincyLarson** [comment]
@albert2309 can you confirm whether you're still experiencing this problem on IE?

**Comment by albert2309** [comment]
@QuincyLarson Yes. I am still experiencing this in Windows 10. My suggestion for this problem is: 
1. Wait for a few seconds then the page's scroll will vanish, so users can scroll the map. 
2. Use *page up* and *page down* button to scroll the map.
3. Use another browser.

**Comment by raisedadead** [comment]
Can anyone check, and do an RCA on this?

**Comment by albert2309** [comment]
@raisedadead I tried to fix the problem by modifying CSS properties in the .map-accordion, but I still couldn't find any best solution that is compatible with all browsers.

**Comment by dhcodes** [comment]
This should be fixed by #14707
