### ISSUE TITLE
Completed Challenge without creating "CSS blue" class

### ISSUE THREAD

**Issue by MightyBoosh92** [FreeCodeCamp/freecodecamp#841]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue. 

I was able to complete this challenge without doing the "Create the CSS class "blue-text"" step.

![nobluetext](https://cloud.githubusercontent.com/assets/9490709/7997127/59a9f614-0af6-11e5-9b85-3b8bf8de2e3a.png)

![check](https://cloud.githubusercontent.com/assets/9490709/7997100/0ecf2358-0af6-11e5-8e98-48b7ac7f16b3.png)

**Comment by QuincyLarson** [comment]
Thank you for your detailed explanation and screen shots. One of our campers has submitted a fix for this.
