### ISSUE TITLE
'Change the font size of an element' does not give all needed information to complete challenge

### ISSUE THREAD

**Issue by Stephaceae** [FreeCodeCamp/FreeCodeCamp#8415]
#### Challenge Name

https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A

#### Issue Description

We are not told how to 'create an entry for p elements' in or before this challenge

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

I had to guess at how to assign font-size, and guessed wrong about 6 different ways before finding the info in the Bug listings.
```

<style>
  .red-text {
    color: red;
  }
  .p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by Stephaceae** [comment]
(to have correct code just remove the period from before the 'p' in style tag.

**Comment by theflametrooper** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by Stephaceae** [comment]
There is a flaw in the challenge and I am reporting it.  Please address my
concern.

**Comment by Stephaceae** [comment]
Have you addressed the problem with this challenge?

**Comment by theflametrooper** [comment]
@Stephaceae Please checkout this link about selectors: https://developer.mozilla.org/en/docs/Web/Guide/CSS/Getting_started/Selectors.

HTML Elements don't have `periods` before them, only classes do.

**Comment by Stephaceae** [comment]
Yeah, I got it thanks. I'm saying the challenge requires the info, but it's
not included in the challenge, or the challenges leading up to it.

This either means that the challenge should be corrected, by simply
including a section on how to use elements in a style tag.  The other
option is FCC is deliberately omitting the data to screen people out.  I
don't think that is the case, as it appears FCC designed this first set of
challenges of to be easy and engaging for noobs.

I was doing this section as review, as it has been some time since I've
used FCC, and the first time I completed the section, I did not have this
trouble.  The challenge has been modified since, and isn't fully complete.

Please stop sending me info I've already worked out for myself and instead
include that info in the challenge for others to use.

Cheers!
