### ISSUE TITLE
I have a blank page. cannot see the bonfire anymore. :<

### ISSUE THREAD

**Issue by articnet** [FreeCodeCamp/freecodecamp#842]
Challenge http://www.freecodecamp.com/challenges/bonfire-steamroller has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
Please describe how to reproduce your issue.

**Comment by mikemimik** [comment]
This issue was a server error that has been rectified. Please close this issue.

**Comment by BerkeleyTrue** [comment]
@mikemimik Thanks!
