### ISSUE TITLE
function takes only 3 arrays as arguments, last test gives 4 though

### ISSUE THREAD

**Issue by Erody** [FreeCodeCamp/FreeCodeCamp#8426]
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=%0Afunction%20uniteUnique(arr1%2C%20arr2%2C%20arr3%2C%20arr4)%20%7B%0A%20%20%2F%2Ftake%20arr%201%20and%20put%20it%20into%20new%20arr%0A%20%20%2F%2Fcompare%20arr2.%20if%20item%20in%20arr%202%20doesn't%20exist%20in%20new%20arr%20push%20it%20in%20else%20ignore%20it%0A%20%20%2F%2Fdo%20the%20same%20for%20arr3%0A%20%20%0A%20%20var%20newArr%20%3D%20arr1%3B%0A%20%20%0A%20%20for(var%20item%20in%20arr2)%7B%0A%20%20%20%20if(newArr.indexOf(arr2%5Bitem%5D)%20%3D%3D%3D%20-1)%7B%0A%20%20%20%20%20%20newArr.push(arr2%5Bitem%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20for(var%20thing%20in%20arr3)%7B%0A%20%20%20%20if(newArr.indexOf(arr3%5Bthing%5D)%20%3D%3D%3D%20-1)%7B%0A%20%20%20%20%20%20newArr.push(arr3%5Bthing%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20for(var%20s%20in%20arr4)%7B%0A%20%20%20%20if(newArr.indexOf(arr4%5Bs%5D)%20%3D%3D%3D%20-1)%7B%0A%20%20%20%20%20%20newArr.push(arr4%5Bs%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20newArr%3B%0A%7D%0A%0AuniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function uniteUnique(arr1, arr2, arr3, arr4) {
  //take arr 1 and put it into new arr
  //compare arr2. if item in arr 2 doesn't exist in new arr push it in else ignore it
  //do the same for arr3
  
  var newArr = arr1;
  
  for(var item in arr2){
    if(newArr.indexOf(arr2[item]) === -1){
      newArr.push(arr2[item]);
    }
  }
  for(var thing in arr3){
    if(newArr.indexOf(arr3[thing]) === -1){
      newArr.push(arr3[thing]);
    }
  }
  for(var s in arr4){
    if(newArr.indexOf(arr4[s]) === -1){
      newArr.push(arr4[s]);
    }
  }
  
  return newArr;
}

uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);

```

The original function only takes the arguments arr1, arr2, arr3. The last test however looks like this: 

```javascript
uniteUnique([1, 2, 3], [5, 2, 1, 4], [2, 1], [6, 7, 8])  
```

As you can see, those are 4 arrays. I had to add another argument to the function and add another for loop for the last array to get my code to pass.

**Comment by raisedadead** [comment]
@Erody 

Thanks for reporting this, however this is not a bug and is intentional.
You are expected to derive a a logic using the [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments).

While your code is technically passing the challenge but it is not Generic (you have fixed no of input args).

Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any further assistance to Coding.

Happy Coding!

**Comment by DanRom624** [comment]
I had a similar objection to that of Erody.
I realized that the object of the exercise is to force the student to derive a logic using the arguments object, as it is confirmed by raisedadead.
However, it would probably beneficial to have a more generic initial function statement such as :
"function uniteUnique(arr) {" --- (note only one argument, vs three!) 

followed by a comment such as
"// Change the code only below this line"

This should force the use of the arguments object.

**Comment by raisedadead** [comment]
Yup I do agree with your analogy @DanRom624 
/cc @FreeCodeCamp/issue-moderators thoughts? I am in favor of having one input argument. 
Any second opinions on this?

**Comment by erictleung** [comment]
@raisedadead it does seem counterintuitive to suggest using the `arguments` objects but then simultaneously imply to use "just" three input arguments. I'm all for the only one input argument in the function 👍

**Comment by erictleung** [comment]
For those wanting to help, you need to change [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/intermediate-bonfires.json#L484) and [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/intermediate-bonfires.json#L491) to have just one argument:

```js
function uniteUnique(arr) ...
```

**Comment by arun1595** [comment]
@erictleung I would like to work on this issue.

**Comment by raisedadead** [comment]
@arun1595 go ahead and make a PR, Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by arun1595** [comment]
@raisedadead I submitted a PR. Can you have a look at it?
