### ISSUE TITLE
Helpful link URL directs to FCC instead of MDN

### ISSUE THREAD

**Issue by Murkrage** [FreeCodeCamp/FreeCodeCamp#8430]
#### Challenge Name
https://www.freecodecamp.com/challenges/missing-letters

#### Issue Description
The link that should direct to 'String.charCodeAt()', directs to the FCC map instead of the MDN page.

#### Browser Information
* Chrome, Version: 50
* Operating System: OSX

**Comment by raisedadead** [comment]
Duplicate of #8423 
Fixed in #8425

**Comment by raisedadead** [comment]
HOLD your horses!

**Comment by sludge256** [comment]
:hand: :horse_racing:

**Comment by sludge256** [comment]
@Murkrage Thanks for the report, we have a fix for it already. Don't mind my incompetence with the labels :stuck_out_tongue_winking_eye:

**Comment by Murkrage** [comment]
@sludge256 Haha no problem. For some reason I didn't see the duplicate. My bad :)
