### ISSUE TITLE
Nonprofit project demo videos link is incorrect

### ISSUE THREAD

**Issue by george-stepanek** [FreeCodeCamp/FreeCodeCamp#8431]
In the About page the "Nonprofit project demo videos" link is incorrect. (The referenced playlist no longer exists.) It should instead be https://www.youtube.com/watch?v=O993J5KCR_w&list=PLWKjhJtqVAbnQ048Pa8sAqJoVRhx8TJtM

**Comment by taml** [comment]
Hey @george-stepanek I'd like to take on this issue, if that's ok!

**Comment by theflametrooper** [comment]
@taml Sure, ping me on gitter if you need any help!
