### ISSUE TITLE
Stop sending notifications.

### ISSUE THREAD

**Issue by Vanco521** [FreeCodeCamp/FreeCodeCamp#8434]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by Vanco521** [comment]
Request you stop sending notifications from every posts from participants.

Remove my mail from notification list.

Thank you

**Comment by sludge256** [comment]
You can change your settings with these links:
https://github.com/settings/notifications
https://github.com/settings/emails

**Comment by raisedadead** [comment]
Hello @Vanco521 !

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Comment by BerkeleyTrue** [comment]
Closing as not an issue
