### ISSUE TITLE
Make Object Properties Private 

### ISSUE THREAD

**Issue by antsarandriamihaja** [FreeCodeCamp/FreeCodeCamp#8435]
My code:
```javascript

var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {
  
  // Only change code below this line.
var gear = 0;
  this.getGear = function(){
    return gear;
  };
  this.setGear = function(set){
    gear += set;
  };

};

var myCar = new Car();

var myBike = new Bike();

```
This only works for when set = 4, but not when set =3, or set =1. 
The code that works is: 

var Bike = function() {
  
  // Only change code below this line.
var gear = 0;
  this.getGear = function(){
    return gear;
  };
  this.setGear = function(set){
    gear = set;
  };

};

var myCar = new Car();

var myBike = new Bike();

------
My problem is that I don't understand why in the setGear function, I cannot do gear += set if I initially set gear to 0. Is it a bug?

**Comment by erictleung** [comment]
@antsarandriamihaja thanks for the issue but there is an error in your code. Hint: based on why you cannot do `gear += set` may give you clue to why its not working. If you are still stuck with this challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by alamitina** [comment]
If you're trying to do gear += set;
I think the issue, even if you're starting with 0, is that every time you use the public method, you're trying to add gears rather than creating a new value for them altogether, which is why gear = set works.
I had a similar issue with this one.

**Comment by im-zablon** [comment]
Hi @alamitina I'm with @antsarandriamihaja on this one. I came across the same problem and wondered why it wasn't working. So I pasted the code on [repl.it](https://repl.it/DyvM/0) and it seems to work just fine with the ```+=```  method.

**Comment by chandrakumarreddy** [comment]
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
var gear=0;
  this.getGear=function(){
    return gear ;
};
  this.setGear=function(val){
    gear= val;
    this.getGear();
  };
};

var myCar = new Car();

var myBike = new Bike();
myBike.setGear(4);

**Comment by BartekKwapisz** [comment]
I also tried this and it worked"
  // Only change code below this line.
var gear = 0;
var x="";
this.setGear = function(set){
   x = gear+set; };
this.getGear=function(){
   return x; };
};
Looks like when you write "gear += set;" it add first myBike.setGear(4) to myBike.setGear(3) what returns 7 when it checks for myBike.setGear(3) (because 4+3=7).

**Comment by kneesham** [comment]
"gear += set;" should be: (  gear = set;  )

**Comment by kuldeep-izap** [comment]
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.

  var gear = 0;
  this.getGear = function() {
    return gear;
  };
  this.setGear = function(set) {
    gear = set;
  };
};

var myCar = new Car();

var myBike = new Bike();



Here is My Code. Try These and solve our problem.

**Comment by gracexu222** [comment]
FYI: 
 var x;
  this.getGear = function(){
   return x;
  };
  this.setGear = function(change){
    return x = change;
  };
it works.

**Comment by texas2010** [comment]
@gracexu222 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Gichunge** [comment]
I found this example on FreecodeCamp on GitHub and it works:

var Cake = function() {

  var loot = 2;
  // Getter to know how much loot you have
  this.getLoot = function() {
    return loot;
  };

  // Setter to change the ammount of loot
  this.setLoot = function(num){
    loot = num;
  };

**Comment by aaliev** [comment]
This helped me [https://www.youtube.com/watch?v=Wl98eZpkp-c](url)

**Open your eyes** :)

**Comment by mukulkh** [comment]
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
  var gear = 0;

  //public methods
  this.setGear= function(change) {
    gear = change;
  };

  this.getGear = function() {
    return gear;
  };

};

var myCar = new Car();

var myBike = new Bike();

myBike.setGear(4);
myBike.getGear();

**Comment by IamManchanda** [comment]
Hey Guys this is right code for the bike :wink: 

```js
var Bike = function() {
  var gear = 0;
  
  this.setGear = function(set) {
    gear = set;
  };
  
  this.getGear = function() {
    return gear;
  };
 
};

var myBike = new Bike();
myBike.setGear(2);
var result = myBike.getGear();
console.log(result);
```
