### ISSUE TITLE
Sum All Odd Fibonnacci Numbers: Tests fail even though function returns correct answer

### ISSUE THREAD

**Issue by giancarlo88** [FreeCodeCamp/FreeCodeCamp#8436]
Hello, 

I can't pass this algorithm because FCC says I don't pass the test cases. However when I call the same  numbers in the test functions myself the correct answer is returned to the console. 

Is there something I should fix?

Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=var%20prev%20%3D%200%3B%0Avar%20current%20%3D%201%3B%0Avar%20next%20%3D%200%3B%0Avar%20sum%20%3D%200%3B%0Afunction%20sumFibs(num)%20%7B%0A%20while%20(current%20%3C%3D%20num)%7B%0Aif%20(current%252%20!%3D%3D%200)%7B%0A%20%20sum%20%2B%3D%20current%0A%7D%0Anext%20%3D%20current%20%2B%20prev%3B%0Aprev%20%3D%20current%0Acurrent%20%3D%20next%0A%7D%0A%20%0A%20%20%0Areturn%20sum%3B%0A%0A%7D%0A%0AsumFibs(75025)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var prev = 0;
var current = 1;
var next = 0;
var sum = 0;
function sumFibs(num) {
 while (current <= num){
if (current%2 !== 0){
  sum += current
}
next = current + prev;
prev = current
current = next
}
 
  
return sum;

}

sumFibs(75025);

```

**Comment by erictleung** [comment]
@giancarlo88 the challenge runs only your function for each test. The variables you've declared are in the global scope and will continually change. I hope that helps but if you are still stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by giancarlo88** [comment]
Of course!! One quick change was all it took. Thanks for that :)
