### ISSUE TITLE
Instructions not too clear

### ISSUE THREAD

**Issue by benjaminjacobharley** [FreeCodeCamp/FreeCodeCamp#8438]
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22button%22).addClass(%22animated%22)%3B%0A%20%20%20%20%24(%22.btn%22).addClass(%22shake%22)%3B%0A%20%20%20%20%24(%22%23target1%22).addClass(%22btn-primary%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
Please clear up instructions and explain better for student sto understand as it took some time figuring this challenge out.

**Comment by erictleung** [comment]
@benjaminjacobharley thanks for the feedback. How do you suggest we change the instructions to make it more clear? Or what parts of the instructions were confusing?

**Comment by benjaminjacobharley** [comment]
The instructions below the run test section is not to clear in my opinion on what it expect the student to do or know. A potential fix for this could be to perhaps have a more thorough explanation for students especially considering it is a beginning experience for users. https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3583    
The article linked above also shows other user's at the same level and  more experienced suggesting perhaps better wordplay with either the instructions or the lesson(or both). Thanks for listening always is appreciated to get a helping hand and trying to make learning more engaging.

**Comment by erictleung** [comment]
@benjaminjacobharley I can see how there can be confusion from reading the instructions and looking at the test requirements. Here's my proposed changes (the bold text represents what I've changed/added). Let me know what could be change to make it the most clear on what to do.

**Instructions**

> ...
>
> Although it is possible to add multiple classes in a single `.addClass()` call, let's add them to the same element in ***three different ways***.
> 
> Using each of the above jQuery selectors and the `addClass()` function in **three separate lines of code**:
> 
> Add the `animated` class to all elements with type `button`.
>
> Add the `shake` class to all the buttons with class `.btn`.
> 
> Add the `btn-primary` class to the button with id `#target1`.
>
> **Note: You should only be targeting one element and adding only one class at a time. All together, your three individual selectors will end up adding the three classes `shake`, `animated`, and `btn-primary` to `#target1`.**

**Comment by bigkatspence** [comment]
Eric as a camper I understood fully what was being said a change commit is
necessary for that challenge nice job

**Comment by buckeyekt** [comment]
Eric,

Since you've clearly laid out the changes to instructions above, would it be alright if I forked it and attempted to make those changes and submit a pull request? It would be my 2nd PR so I'm still new but can no longer do "first-timers-only" :)

**Comment by erictleung** [comment]
@buckeyekt go for it! If you haven't already done so, please read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of the issue. Also, don't hesitate to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions about helping.

**Comment by erictleung** [comment]
For those interested in fixing this, what is displayed should look similar to [what I typed up above](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8438#issuecomment-216992238).

The [code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/jquery.json#L346-L350) itself should be something like this:

```json
"Now you know three ways of targeting elements: by type: <code>$(\"button\")</code>, by class: <code>$(\".btn\")</code>, and by id <code>$(\"#target1\")</code>.",
"Although it is possible to add multiple classes in a single <code>.addClass()</code> call, let's add them to the same element in <em>three separate ways</em>.",
"Using each of the above jQuery selectors and the <code>.addClass()</code> function in three separate lines of code:",
"Add the <code>animated</code> class to all elements with type <code>button</code>.",
"Add the <code>shake</code> class to all the buttons with class <code>.btn</code>.",
"Add the <code>btn-primary</code> class to the button with id <code>#target1</code>.",
"<strong>Note</strong><br>You should only be targeting one element and adding only one class at a time. Altogether, your three individual selectors will end up adding the three classes <code>shake</code>, <code>animated</code>, and <code>btn-primary</code> to <code>#target1</code>."
```

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions about helping. We're there to help.

**Comment by robjloranger** [comment]
Another one for @yourfirstpr ?

**Comment by atjonathan** [comment]
@robjloranger, yeh :smile:

**Comment by qaoo8** [comment]
My idea:
Change this line "Your #target1 element should have the classes animated‚ shake and btn-primary." into "Your #target1 element should have the **three class effects of**  animated‚ shake and btn-primary." **and change three words color from red to black with in this line.**

**Comment by andmckvr13** [comment]
@erictleung is this issue still open/ no pull requests? I'm interested in contributing to this

**Comment by atjonathan** [comment]
@andmckvr13, yeh no one has made a PR to this yet. Feel free to jump on it :wink: :shipit:

**Comment by andmckvr13** [comment]
should I label this branch fix/instructionsNotTooClear#8438?

**Comment by atjonathan** [comment]
@andmckvr13, you could remove `#8438` at the end!

**Comment by shahid1212** [comment]
replace shake with animate__shakeX like this
$(document).ready(function() {
  $("button").addClass("animated");
    $(".btn").addClass("animate__shakeX");
    $("#target1").addClass("btn-primary");
  });
