### ISSUE TITLE
Uncomment Task

### ISSUE THREAD

**Issue by codesnsuch** [FreeCodeCamp/FreeCodeCamp#8440]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A%3C!----%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3C!----%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3C!----%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I am being asked to delete a trailing comment tag that is not ther
My code:
```html

<!---->
<h1>Hello World</h1>
<!---->
<h2>CatPhotoApp</h2>
<!---->
<p>Hello Paragraph</p>

```

**Comment by dwd2010** [comment]
@codesnsuch 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!

**Comment by moviebuff20** [comment]
I'm experiencing the same issue and the default code has, <h2> which has been brought to my understanding as incorrect syntax
