### ISSUE TITLE
No details how to deploy mongodb to heroku

### ISSUE THREAD

**Issue by ChaituVR** [FreeCodeCamp/FreeCodeCamp#8444]
Challenge [URL Shortener Microservice](https://www.freecodecamp.com/challenges/url-shortener-microservice) has an issue.

There are no Details for deploying mongodb in heroku.. Its my first time i am trying to deploy a db into heroku and i am finding it hard.

At last i found out a way to do this is adding mLab MongoDB add-on but it is asking for a credit card for billing , Not all people will have a credit card, Is there any better alternative for this? or anyother better way to do this Challenge other than using a DB.

or if in case i am assuming this in wrong way please tell me and close this issue.
my code is at `https://github.com/ChaituVR/URL-Shortner.git`

![image](https://cloud.githubusercontent.com/assets/15967809/15006531/834ac07e-11ef-11e6-91f0-87c656ef491d.png)

Thank you

**Comment by ltegman** [comment]
There are no alternative options with Heroku. All "addons" apart from one or two of them require a credit card for verification (they will not charge you if the addon is free). I'll leave this open in case anyone else knows of an alternative free hosting solution for people without a credit card.

**Comment by sludge256** [comment]
To avoid providing credit card information, I believe you can sign up for mLab (MongoLab) directly via their [site](https://mlab.com/), then use the provided URL in Heroku.

**Comment by ChaituVR** [comment]
Yes i tried signing up for mLab and i tried it..  And it works.. My app is up and running..   But not all guys are familiar with this..  May be mentioning this some where in the challenge or wiki will help some people like me to solve this much faster than searching for alternatives.. Today I wasted a few hours searching for alternatives..

**Comment by ChaituVR** [comment]
And also there is no information about deploying it with add-on's..

**Comment by raisedadead** [comment]
@ChaituVR Yup I agree, and we apologize that you had to waste precious time, but if you wouldn't mind how about creating a wiki article on out [wiki repo](https://github.com/FreeCodeCamp/wiki)? 

Since you have freshly setup this, you are probably the best suited in doing this. Its real quick and easy and you get to contribute to Open Source as well! How about that?

Of course if you aren't comfortable, we can tag this as help wanted. Let us know!

Thanks!

**Comment by ChaituVR** [comment]
Don't apologize ;)  it's like i am apologizing myself..  Ok yes...  Sure..  i will make a wiki  by tomorrow..  :)  thanks for the help everyone..  And if anyone think we need to add about this in the challenge..  Then keep this issue open or else you may close this..  Thanks again..

**Comment by raisedadead** [comment]
Great! Once the wiki is ready we can link it as a reference in the challenge.

**Comment by ChaituVR** [comment]
@raisedadead please check that PR

**Comment by raisedadead** [comment]
@ChaituVR Thanks.

After the wiki is merged we need a PR to refer that in the challenge.

A line needs to be added here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/api-projects.json#L261 and any translations (if unsure, just add the english version, there as well, its fine and can be updated later) that are there on the page.

Something similar on the below should do:
> <strong>ProTip:</strong>Checkout [this article on the wiki](#) for tips on integrating MongoDB on heroku

where the link leads to our wiki page at 
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/ `<pagename>`

**Comment by ChaituVR** [comment]
@raisedadead Thanks for suggesting me to do this .. learned how things work in an open source ... ok let   me commit those changes and after merging i will open a pull request here..

**Comment by raisedadead** [comment]
@ChaituVR Awesome do not forget to have a look at our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by ChaituVR** [comment]
@raisedadead Hey i haven't seen any ProTip in any of the challenges .. so no problem keeping it?

**Comment by raisedadead** [comment]
Well we could keep it as a Hint, as in other challenges, but its really not a hint.
So I think `ProTip` should be okay

**Comment by ChaituVR** [comment]
Ok :+1:  i am going with  `ProTip` so we should be keeping `ProTip` as a Checkbox?? or we should be adding it at end of this ??
![image](https://cloud.githubusercontent.com/assets/15967809/15048073/71149aee-1305-11e6-856c-d7dc7a62352b.png)

**Comment by raisedadead** [comment]
Add it as a checkbox, like other steps.

**Comment by ChaituVR** [comment]
@raisedadead pull requested but did't tested it locally..
I am trying to install FCC locally ...

**Comment by ChaituVR** [comment]
@raisedadead Hey I am having trouble squshing the commits ...i squshed my commits but in doing so i've recommitted `CONTRIBUTING.md` can you help there ?/

**Comment by raisedadead** [comment]
@ChaituVR Hit me at [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).
