### ISSUE TITLE
Int Algorithm Scripting "Missing Letter" - helpful links "String.charCodeAt()" link is incorrect

### ISSUE THREAD

**Issue by mathewjcohen** [FreeCodeCamp/FreeCodeCamp#8445]
Intermediate Algorithm Scripting challenge "Missing Letter" - helpful links "String.charCodeAt()" url link is incorrect.

**Comment by theflametrooper** [comment]
@mathewjcohen Duplicate of #8425. This will be fixed the next time we push `staging` to `master`! Sorry!
