### ISSUE TITLE
Works but the challenge does not complete?

### ISSUE THREAD

**Issue by OriginalMike** [FreeCodeCamp/FreeCodeCamp#8446]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20var%20iTemp%20%3D%200%3B%0A%20%20var%20pos%20%3D%200%3B%0A%20%20%0A%20%20%0A%20%20for%20(var%20k%20%3D%200%3B%20k%20%3C%20arr.length%3B%20k%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20var%20check%20%3D%20arr%5Bk%5D%3B%0A%20%20%20%20%20%20for%20(var%20l%20%3D%200%3B%20l%20%3C%20check.length%3B%20l%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20if%20(iTemp%20%3C%20check%5Bl%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20iTemp%20%3D%20check%5Bl%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20console.log(check%5Bl%5D)%3B%20%2F%2Ffor%20tests%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pos%20%3D%20k%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20return%20arr%5Bpos%5D%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%2010%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function largestOfFour(arr) {
  var iTemp = 0;
  var pos = 0;
  
  
  for (var k = 0; k < arr.length; k++)
    {
      var check = arr[k];
      for (var l = 0; l < check.length; l++)
        {
          
          if (iTemp < check[l])
            {
              iTemp = check[l];
             // console.log(check[l]); //for tests
              pos = k;
              
            }
        }
    }
  // You can do this!
  return arr[pos];
}

largestOfFour([[4, 5, 10, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by shl-kfy** [comment]
hi @OriginalMike,
in this problem we should put each array's biggest number into a new array.

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!

**Comment by akarika** [comment]
Check this code!!!

    function largestOfFour(arr) {
      // You can do this!
    function compareNombres(a, b) {
      return a - b;
    }
      var arrNb=[];
      for(i=0;i<arr.length;i++){
        var ar=arr[i].sort(compareNombres);
        arrNb.push(ar[3]);
      }

      return arrNb ;
    }

    largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

**Comment by akarika** [comment]
check this!!!

```javascript
    function largestOfFour(arr) {
      // You can do this!
    function compareNombres(a, b) {
      return a - b;
    }
      var arrNb=[];
      for(i=0;i<arr.length;i++){
        var ar=arr[i].sort(compareNombres);
        arrNb.push(ar[3]);
      }

      return arrNb ;
    }

    largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
```

**Comment by theflametrooper** [comment]
@akarika Please don't post solutions here. If you wouldn't mind, could you delete your comment?
