### ISSUE TITLE
German translation of Basic JavaScript

### ISSUE THREAD

**Issue by 5k9m** [FreeCodeCamp/FreeCodeCamp#8447]
- [x] Comment your JavaScript Code Complete
- [x] Declare JavaScript Variables Complete
- [x] Storing Values with the Assignment Operator Complete
- [x] Initializing Variables with the Assignment Operator Complete
- [ ] Understanding Uninitialized Variables Complete
- [ ] Understanding Case Sensitivity in Variables Complete
- [ ] Add Two Numbers with JavaScript Complete
- [ ] Subtract One Number from Another with JavaScript Complete
- [ ] Multiply Two Numbers with JavaScript Complete
- [ ] Divide One Number by Another with JavaScript Complete
- [ ] Increment a Number with JavaScript Complete
- [ ] Decrement a Number with JavaScript Complete
- [ ] Create Decimal Numbers with JavaScript Complete
- [ ] Multiply Two Decimals with JavaScript Complete
- [ ] Divide one Decimal by Another with JavaScript Complete
- [ ] Finding a Remainder in JavaScript Complete
- [ ] Compound Assignment With Augmented Addition Complete
- [ ] Compound Assignment With Augmented Subtraction Complete
- [ ] Compound Assignment With Augmented Multiplication Complete
- [ ] Compound Assignment With Augmented Division Complete
- [ ] Convert Celsius to Fahrenheit Complete
- [ ] Declare String Variables Complete
- [ ] Escaping Literal Quotes in Strings Complete
- [ ] Quoting Strings with Single Quotes Complete
- [ ] Escape Sequences in Strings Complete
- [ ] Concatenating Strings with Plus Operator Complete
- [ ] Concatenating Strings with the Plus Equals Operator Complete
- [ ] Constructing Strings with Variables Complete
- [ ] Appending Variables to Strings Complete
- [ ] Find the Length of a String Complete
- [ ] Use Bracket Notation to Find the First Character in a String Complete
- [ ] Understand String Immutability Complete
- [ ] Use Bracket Notation to Find the Nth Character in a String Complete
- [ ] Use Bracket Notation to Find the Last Character in a String Complete
- [ ] Use Bracket Notation to Find the Nth-to-Last Character in a String Complete
- [ ] Word Blanks Complete
- [ ] Store Multiple Values in one Variable using JavaScript Arrays Complete
- [ ] Nest one Array within Another Array Complete
- [ ] Access Array Data with Indexes Complete
- [ ] Modify Array Data With Indexes Complete
- [ ] Access Multi-Dimensional Arrays With Indexes Complete
- [ ] Manipulate Arrays With push() Complete
- [ ] Manipulate Arrays With pop() Complete
- [ ] Manipulate Arrays With shift() Complete
- [ ] Manipulate Arrays With unshift() Complete
- [ ] Shopping List Complete
- [ ] Write Reusable JavaScript with Functions Complete
- [ ] Passing Values to Functions with Arguments Complete
- [ ] Global Scope and Functions Complete
- [ ] Local Scope and Functions Complete
- [ ] Global vs. Local Scope in Functions Complete
- [ ] Return a Value from a Function with Return Complete
- [ ] Assignment with a Returned Value Complete
- [ ] Stand in Line Incomplete
- [ ] Understanding Boolean Values Complete
- [ ] Use Conditional Logic with If Statements Complete
- [ ] Comparison with the Equality Operator Incomplete
- [ ] Comparison with the Strict Equality Operator Incomplete
- [ ] Comparison with the Inequality Operator Incomplete
- [ ] Comparison with the Strict Inequality Operator Incomplete
- [ ] Comparison with the Greater Than Operator Incomplete
- [ ] Comparison with the Greater Than Or Equal To Operator Incomplete
- [ ] Comparison with the Less Than Operator Incomplete
- [ ] Comparison with the Less Than Or Equal To Operator Incomplete
- [ ] Comparisons with the Logical And Operator Incomplete
- [ ] Comparisons with the Logical Or Operator Incomplete
- [ ] Introducing Else Statements Incomplete
- [ ] Introducing Else If Statements Incomplete
- [ ] Logical Order in If Else Statements Incomplete
- [ ] Chaining If Else Statements Incomplete
- [ ] Golf Code Incomplete
- [ ] Selecting from many options with Switch Statements Incomplete
- [ ] Adding a default option in Switch statements Incomplete
- [ ] Multiple Identical Options in Switch Statements Incomplete
- [ ] Replacing If Else Chains with Switch Incomplete
- [ ] Returning Boolean Values from Functions Incomplete
- [ ] Return Early Pattern for Functions Incomplete
- [ ] Counting Cards Incomplete
- [ ] Build JavaScript Objects Complete
- [ ] Accessing Objects Properties with the Dot Operator Incomplete
- [ ] Accessing Objects Properties with Bracket Notation Incomplete
- [ ] Accessing Objects Properties with Variables Incomplete
- [ ] Updating Object Properties Complete
- [ ] Add New Properties to a JavaScript Object Complete
- [ ] Delete Properties from a JavaScript Object Complete
- [ ] Using Objects for Lookups Incomplete
- [ ] Testing Objects for Properties Incomplete
- [ ] Introducing JavaScript Object Notation (JSON) Incomplete
- [ ] Accessing Nested Objects in JSON Incomplete
- [ ] Accessing Nested Arrays in JSON Incomplete
- [ ] Record Collection Incomplete
- [ ] Iterate with JavaScript For Loops Complete
- [ ] Iterate Odd Numbers With a For Loop Complete
- [ ] Count Backwards With a For Loop Complete
- [ ] Iterate Through an Array with a For Loop Incomplete
- [ ] Nesting For Loops Incomplete
- [ ] Iterate with JavaScript While Loops Complete
- [ ] Profile Lookup Complete
- [ ] Generate Random Fractions with JavaScript Complete
- [ ] Generate Random Whole Numbers with JavaScript Complete
- [ ] Generate Random Whole Numbers within a Range Complete
- [ ] Sift through Text with Regular Expressions Complete
- [ ] Find Numbers with Regular Expressions Complete
- [ ] Find Whitespace with Regular Expressions Complete
- [ ] Invert Regular Expression Matches with JavaScript

**Comment by 5k9m** [comment]
I'm working on it.

**Comment by bugron** [comment]
@5k9m any progress on this?

**Comment by 5k9m** [comment]
@bugron Unfortunately not as much as I would like - have been swamped with work for the past 3 weeks... Hope to finish the translation until the middle of June!

**Comment by codingHahn** [comment]
How is it going? @5k9m

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #82](https://github.com/FreeCodeCamp/TranslationExpansion/issues/82) via [**ZenHub**](https://www.zenhub.com/)

**Comment by raisedadead** [comment]
@codingHahn @5k9m please continue collaboration on the new issue thread.

**Comment by krishenexson** [comment]
var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

a += 12;
b += 9;
c += 7;
