### ISSUE TITLE
i press submit and it works without an error as it should be.

### ISSUE THREAD

**Issue by danydin** [FreeCodeCamp/FreeCodeCamp#8448]
Challenge [Create a Set of Radio Buttons](https://www.freecodecamp.com/challenges/create-a-set-of-radio-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 7834.70.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

```

**Comment by shadfien** [comment]
(ᓄಠ_ಠ)ᓄ

**Comment by raisedadead** [comment]
This doesn't pass with the above code.

Have you tried the common trouble shooting steps?
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Confirm that this is the case with others as well on the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help), and let us know. Will re-open if reproducible.

Happy Coding!
