### ISSUE TITLE
String.charCodeAt() link broken

### ISSUE THREAD

**Issue by scucow** [FreeCodeCamp/FreeCodeCamp#8449]
Challenge [Missing letters](https://www.freecodecamp.com/challenges/missing-letters#?solution=%0Afunction%20fearNotLetter(str)%20%7B%0A%20%20%0A%20%20%2F%2FDeclare%20a%20string%20with%20the%20full%20alphabet.%0A%20%20%0A%20%20var%20alphabet%20%3D%20%22abcdefghijklmnopqrstuvwxyz%22%3B%0A%20%20%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0AfearNotLetter(%22abce%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function fearNotLetter(str) {
  
  //Declare a string with the full alphabet.
  
  var alphabet = "abcdefghijklmnopqrstuvwxyz";
  
  
  return str;
}

fearNotLetter("abce");

```

**Comment by erictleung** [comment]
@scucow thanks for the issue. We've made a fix with #8425 and you will see the change once we've been pushed those change to the live site. Happy coding!
