### ISSUE TITLE
Bonfire: Mutations: ['Mary', 'Maary']

### ISSUE THREAD

**Issue by vzhikness** [FreeCodeCamp/freecodecamp#845]
Challenge http://www.freecodecamp.com/challenges/bonfire-mutations has an issue.

The example from the task says:
['Mary', 'Aarmy'] should return false because 'Mary' is only 4 letters while 'Aarmy' is 5, so 'Mary' can't possibly contain 'Aarmy'.

Consider this example: ['Mary', 'Maary']. 'Maary' has 5 letters, but 'Mary' contains all the letters from it.

I think, we should:
- or remove ['Mary', 'Aarmy'] example from the description
- or just set a condition: length of the first string >= length of the second string

**Comment by LumenTeun** [comment]
I think what this bonfire looks for is an [anagram](https://en.wikipedia.org/wiki/Anagram) and, if so, should be renamed as such?

**Comment by BerkeleyTrue** [comment]
Not anagram as we are not looking for exact letter length match. 

My vote is for removal of the mary/aarmy example as it doesn't fit the pattern established in the rest of the info.

Anyone want to sumbit a PR against master branch?

**Comment by treece** [comment]
@BerkeleyTrue Sure, I can. So just remove the mary/aarmy example from the description and leave the test for it right? or remove both the description and test for it?

**Comment by LumenTeun** [comment]
@BerkeleyTrue So the number of occurences in either word should not matter?

**Comment by BerkeleyTrue** [comment]
>Return true if the string in the first element of the array contains all of the letters of the string in the second element of the array.

It doesn't state anything about duplicates. Just containment. If `arr[1]` has two `a`'s and `arr[0]` contains one `a` `arr[0]` contains all the letters in `arr[1]`. At least that is my take away. I was not the original author so I am only guessing at the intent.

@treece Removing the example and changing the test to to passing should work. You want it?

**Comment by treece** [comment]
@BerkeleyTrue Sure, if no one else wants to do it :D

**Comment by QuincyLarson** [comment]
Great work guys! I'm closing this thanks to @treece's PR.
