### ISSUE TITLE
Claim Certificates - Challenges - Text Rendering Issues

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#8451]
![image](https://cloud.githubusercontent.com/assets/1884376/15014874/1068513e-1226-11e6-9002-e08996800373.png)

This is generic to all of the "Claim your XYZ Certificate" Pages.
/cc @hallaathrad

**Comment by theflametrooper** [comment]
@raisedadead Could we maybe use something like [Bootstrap Alerts](http://getbootstrap.com/components/#alerts-examples) for this, or just move the `paragraph` tag onto a new line?

**Comment by raisedadead** [comment]
I am not sure actually, I think the line should be contained within area on the right.

**Comment by theflametrooper** [comment]
@raisedadead Oh, I see...
