### ISSUE TITLE
Video Challenges - Computer Basics not recording completion

### ISSUE THREAD

**Issue by SandraFlato** [FreeCodeCamp/FreeCodeCamp#8455]
#### Challenge Name
Video Challenges - Computer Basics

https://www.freecodecamp.com/videos/computer-basics-how-to-measure-data-size

#### Issue Description

I have watched How to Measure Data Size and answered the questions 3 times now and it is not marking it as complete.  Same thing with Measuring Data Speed.

#### Browser Information

* Browser Name, Version: Google Chrome 50.0.2661.94 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: laptop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
Possible duplicate of #6929

**Comment by alistermada** [comment]
@erictleung Assuming that "marking it as complete" refers to the check mark on the map, this issue  seems to be more likely a duplicate of #8463, #8462, and #8307. Those issues describe that completing the video challenges don't award brownie points and isn't marked on the map. This wasn't a problem at the time I posted #6929.

**Comment by QuincyLarson** [comment]
+1 a lot of campers are reporting this.

**Comment by ltegman** [comment]
Started digging into this and it appears to be related to our recent addition of a CSRF token. The react app doesn't have access to this token and so can't send it back on completion of a challenge. This prevents the submission from being successful.

**Comment by ltegman** [comment]
@BerkeleyTrue csrf doesn't seem to play well with react. I can't come up with a good solution to this problem right away. Unless you can solve it quickly we may want to disable csrf on video challenges, because they'll be broken until we get this sorted out.
