### ISSUE TITLE
German translation of "JSON APIs and AJAX"

### ISSUE THREAD

**Issue by john-dederer** [FreeCodeCamp/FreeCodeCamp#8458]
- [ ] Trigger Click Events with jQuery
- [ ]  Change Text with Click Events
- [ ]  Get JSON with the jQuery getJSON Method
- [ ]  Convert JSON Data to HTML
- [ ]  Render Images from Data Sources
- [ ]  Prefilter JSON
- [ ]  Get Geo-location Data

**Comment by john-dederer** [comment]
I'm working on it.

**Comment by bugron** [comment]
@john-dederer any progress on this?

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #83](https://github.com/FreeCodeCamp/TranslationExpansion/issues/83) via [**ZenHub**](https://www.zenhub.com/)

**Comment by raisedadead** [comment]
@john-dederer please continue on the new thread, I have updated the Opening post to reflect current status for others, please make a pr when ready.
