### ISSUE TITLE
Challenge Test Broken = All test case correct using strict equality, still fails

### ISSUE THREAD

**Issue by shanethughes** [FreeCodeCamp/FreeCodeCamp#8459]
Challenge [Comparison with the Strict Equality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-strict-equality-operator#?solution=var%20myVal%20%3D%207%3B%0A%2F%2F%20Setup%0Afunction%20testStrict(val)%20%7B%0A%20%20if%20(val%20%3D%3D%3D%20myVal)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestStrict(10)%3B%0AtestStrict(7)%3B%0AtestStrict(%227%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVal = 7;
// Setup
function testStrict(val) {
  if (val === myVal) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testStrict(10);
testStrict(7);
testStrict("7");

```

**Comment by shanethughes** [comment]
Issue appears to be in the fourth test case:  "assert(code.match(/(val\\s*===\\s*\\d+)|(\\d+\\s*===\\s*val)/g).length > 0, 'message: You should use the <code>===</code> operator');"

![image](https://cloud.githubusercontent.com/assets/12244245/15025965/dc42c4c8-1209-11e6-8773-66eb3951e411.png)

**Comment by erictleung** [comment]
@shanethughes thanks for the issue. The challenge is trying to prompt you to do the (direct) comparison within the `if` statement, rather than compare to a variable. The comment is even pointing `// Change this line`. Closing as not an issue with the site. Happy coding!

**Comment by shanethughes** [comment]
Thank you erictleung, you are correct. The confusion was caused from how similar it is to the previous challenge Comparison with the Equality Operator , where it is almost identical except in this case it appears to not require the extra step of placing it in a variable.

**Comment by zcassini** [comment]
The function names should be changed to testStrict7, testNotStrict17, testEqual12 etc.  if we students are expected to use a magic number in the function's body.

**Comment by frogshelp** [comment]
change ur 7's to a 12  and it will work i just had same issue and thats all i did was make the bottom two 12's and my var =12 and  also u notice u got === only suppose to be == and it should pass

**Comment by frogshelp** [comment]
change the (val ===myval) to (val === 7) it will pass
