### ISSUE TITLE
Possible Bug in Video Challenges

### ISSUE THREAD

**Issue by LeWood16** [FreeCodeCamp/FreeCodeCamp#8462]
#### Issue Description

I'm having an issue with several of the Video Challenges in the Computer Basics section.  Lessons 1 through 8 have all logged properly (i.e. the links have faded out, they are check-marked, the brownie point was logged, etc.) However I've completed the remainder of the video lessons in the Computer Basics section a few times now (from "Computer Basics: Types of Computers" to "Computer Security"), and for some reason none of them have logged.

Sections "The DOM" and "Javascript Lingo" have both logged successfully, however, they were completed before I had finished the "Computer Basics" section.

I have tried both completing the challenges with playing the video and without playing the video, but get the same result.  Any challenge in the "Video Challenges" section now refuse to be logged as completed.

#### Browser Information

* Browser Name, Version: Google Chrome 49.0.2623.112 (Official Build) (64-bit)
* Operating System: Chrome OS
* Mobile, Desktop, or Tablet: Lenovo Ideapad N20P 11.6 inch touchscreen Chromebook 

```

**Comment by RayBB** [comment]
Possible the same issue as this one: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8463

**Comment by raisedadead** [comment]
Closing in favor of #8455 (Oldest logged issue for this)
