### ISSUE TITLE
not saving progress after completing video challenge

### ISSUE THREAD

**Issue by RayBB** [FreeCodeCamp/FreeCodeCamp#8463]
#### Challenge Name
Any video challenge

#### Issue Description
I did a video challenge yesterday and then when I came back today it wasn't done.
I did it again on my phone but it didn't save. I tried again in incognito mode (see screenshot/gif) and it didn't work.
I tried again on a desktop and it didn't work still, even with a different video.

#### Browser Information
Issue is happening on mobile and desktop platforms (even in incognito mode).

#### Screenshot

![2016_05_04_17_35_28](https://cloud.githubusercontent.com/assets/921217/15031484/e291d554-1226-11e6-8a93-97bbb45cf0d1.gif)

**Comment by raisedadead** [comment]
Closing in favor of #8455 (Oldest logged issue for this)
