### ISSUE TITLE
Sum All Odd Fibonacci Numbers: gives an error when I use console.log()

### ISSUE THREAD

**Issue by Y-Taras** [FreeCodeCamp/FreeCodeCamp#8468]
Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=function%20sumFibs(num)%20%7B%0A%20%20%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%20%20var%20i%20%3D%200%3B%0A%20%20%20%20var%20sum%20%3D%200%3B%0A%20%20%20%20do%20%7B%0A%20%20%20%20%20%20%20%20if%20(i%20%3C%3D%201)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20arr.push(i)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(%27arr%5B%27%2C%20i%2C%20%27%5D%27%2C%20arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20arr.push(arr%5Bi%20-%201%5D%20%2B%20arr%5Bi%20-%202%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(%27arr%5B%27%2C%20i%2C%20%27%5D%27%2C%20arr%5Bi%5D)%3B%0A%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20if%20(arr%5Bi%5D%20%3E%20num)%20%7B%20break%3B%7D%0A%0A%0A%20%20%20%20%20%20%20%20if%20((arr%5Bi%5D%20%25%202)%20!%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20sum%20%2B%3D%20arr%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20i%20%2B%3D%201%3B%0A%0A%20%20%20%20%7D%20while%20(i)%3B%0A%0A%20%20%20%20return%20sum%3B%0A%7D%0AsumFibs(4)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
**
#1  Mozilla v.42 : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      SyntaxError: missing while after do-loop body;
#2  Google Chrome v.47 : SyntaxError: Unexpected token; 
Without strings with console.log it works fine.**

My code:
```javascript
function sumFibs(num) {
    var arr = [];
    var i = 0;
    var sum = 0;
    do {
        if (i <= 1) {
            arr.push(i);
            console.log('arr[', i, ']', arr[i]);
        } else {
            arr.push(arr[i - 1] + arr[i - 2]);
            console.log('arr[', i, ']', arr[i]);

        }

        if (arr[i] > num) { break;}


        if ((arr[i] % 2) !== 0) {
            sum += arr[i];
        }

        i += 1;

    } while (i);

    return sum;
}
sumFibs(4);
```

**Comment by raisedadead** [comment]
@Y-Taras Thanks for reporting this. 
A library `looprotect` that we use is conflicting with this solution.
You can pass this challenge by adding `//noprotect` on the top of your code.

This is the looprotect output, at line no 5, there is a conflict.
```js
function sumFibs(num) {
    var arr = [];
    var i = 0;
    var sum = 0;
    ;loopProtect.protect({ line: 7, reset: true }); do {;
if (loopProtect.protect({ line: 7 })) break;

        if (i <= 1) {
            arr.push(i);
            console.log('arr[', i, ']', arr[i]);
        } else {
            arr.push(arr[i - 1] + arr[i - 2]);
            console.log('arr[', i, ']', arr[i]);

        }

        if (arr[i] > num) { break;}


        if ((arr[i] % 2) !== 0) {
            sum += arr[i];
        }

        i += 1;

    } ;loopProtect.protect({ line: 26, reset: true }); while (i){
if (loopProtect.protect({ line: 26 })) break;
;
}


    return sum;
}
sumFibs(4);
```

**Comment by raisedadead** [comment]
Just checked this is an known issue with loopProtect sadly, reported back in #5162 
Closing this in favor of the older issue.
