### ISSUE TITLE
Field guides have infinite redirect loop

### ISSUE THREAD

**Issue by vaultx** [FreeCodeCamp/freecodecamp#847]
http://www.freecodecamp.com/field-guide/ is unusable for me, I get redirect loop errors. Others in the Slack are experiencing this as well.

**Comment by mauriciovieira** [comment]
Specifically http://www.freecodecamp.com/field-guide/will-i-really-be-able-to-get-software-engineering-job-after-free-code-camp?,  in my case, is returning a ```ERR_TOO_MANY_REDIRECTS```error

**Comment by terakilobyte** [comment]
Thanks for the reports. This should be fixed now.
