### ISSUE TITLE
Symmetric Difference Hung

### ISSUE THREAD

**Issue by SandraFlato** [FreeCodeCamp/FreeCodeCamp#8472]
#### Challenge Name

https://www.freecodecamp.com/challenges/symmetric-difference

#### Issue Description

The last code I added caused the screen to lock. Think it was the last return at the bottom.  I have restarted it multiple times, but it immediately locks.  I can access other challenges, but can not complete Symmetric Difference.  None of the buttons on the page work.

#### Browser Information

* Browser Name, Version: Google Chrome 50.0.2661.94
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: 

#### Your Code
can' copy it.
```js
// If relevant, paste all of your challenge code in here

```

**Comment by raisedadead** [comment]
Hi @SandraFlato 
Can you try and add `run=disabled` in the URL.

Refer wiki :
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run

Then maybe share the code here as well for us to have a look.
Thanks.

**Comment by SandraFlato** [comment]
Thanks.  run=disabled fixed it.  

Sorry, but I am a newbie and sometimes need help getting out of trouble.  Thanks for helping
