### ISSUE TITLE
Remove "important notice" from deprecated signin page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8474]
![](https://www.evernote.com/l/Ar-gNOmen9lHQ536abePpfUAVLmRpouZoeMB/image.png) 

We are adding a flash notification, which will replace the need for this (somewhat scary) message. (https://www.freecodecamp.com/deprecated-signin)

**Comment by raisedadead** [comment]
@QuincyLarson Agreed. This was just a place holder anyways. Will do asap.
