### ISSUE TITLE
Update weather app frontend challenge

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#8475]
#### Challenge Name

https://www.freecodecamp.com/challenges/show-the-local-weather

#### Issue Description

you need a secure connection (https) to use the Geolocation API.  Someone should update the challenge with resources on how to configure their system to be able to use it or use a static lat long.
#### Browser Information

* Browser Name, Version: Chrome 50
* Operating System: MC
* Mobile, Desktop, or Tablet: All

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

most browsers/the internet is moving in this direction.  The issue will only continue.  Some updated challenge directions would go a long way.

**Comment by raisedadead** [comment]
This is being discussed in #7853, please continue the discussion no that thread.

Relates #7700
