### ISSUE TITLE
When completing video challenge questions no check mark or points are given.

### ISSUE THREAD

**Issue by benschac** [FreeCodeCamp/FreeCodeCamp#8476]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by raisedadead** [comment]
Duplicate of #8455 
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)
