### ISSUE TITLE
Why challenges didn't include /  on self closing html element like link and img 

### ISSUE THREAD

**Issue by ReactorboY** [FreeCodeCamp/FreeCodeCamp#8477]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat.jpg%22%20%2F%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<img src="https://bit.ly/fcc-relaxing-cat.jpg" />
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by khaduch** [comment]
Hello - are you saying that it should flag the fact that the trailing slash was used?  Or that it should have been used?  It seems that it is no longer supported in HTML5?  Or at least no longer required - XHTML 1.0 required it, at least for an empty element. (I'm not an expert - jut looking at various sources.)  

I guess that I'm trying to clarify what you are asking?  Thanks!

**Comment by erictleung** [comment]
@ReactorboY thanks for the issue. They do seem odd now that I look at it. However, with a little Googling, it appears that the `/` is not necessary for elements like `img` and `link` because they are considered ["void elements"](http://w3c.github.io/html/syntax.html#void-elements), which apparently [don't require the `/` character](http://w3c.github.io/html/syntax.html#start-tags).

> Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single U+002F SOLIDUS character (/). **This character has no effect on void elements**, but on foreign elements it marks the start tag as self-closing.

cc/ @FreeCodeCamp/issue-moderators

**Comment by ltegman** [comment]
Closing slashes on void elements is a holdover from XHTML (and is unfortunately required in JSX) but generally discouraged when writing HTML5. It's not something we should bar people from doing but it's definitely not a pattern we'll be switching our examples to. Thanks and happy coding!

**Comment by ReactorboY** [comment]
thanx for the reply's.
