### ISSUE TITLE
API endpoint for FreeCodeCamp Camper information

### ISSUE THREAD

**Issue by rngadam** [FreeCodeCamp/FreeCodeCamp#8479]
I would like to query the score and name for a particular user without having to scrape the profile page.

This information is rendered on (for example): https://www.freecodecamp.com/rngadam (last part is the username).

Something such as:

GET https://www.freecodecamp.com/rngadam.json

```
{
  "username": "rngadam",
  "score": 285,
  "name": "Ricky Ng-Adam"
}
```

**Comment by raisedadead** [comment]
We have some work in progress on these API endpoints. 
Not sure when they are going to be available publicly. @roelver is working on this bit if I am not wrong.

/cc @QuincyLarson @BerkeleyTrue @evaristoc

**Comment by evaristoc** [comment]
@rngadam thanks for sharing this.

As @raisedadead mentioned there is still some work to be done for the API endpoints: in fact, the project is ready but we would like to be sure that the data we provide won't affect FCC users' privacy.

Momentarily the only way to go is scrapping. Can you please send us more information about your scrap and the reason of your project? We are not preventing people to scrap FCC pages if it is with a good purpose, but we would need from you information about the rate and size of the scrap so it doesn't affect performance.

Please introduce your scrap here or at https://gitter.im/FreeCodeCamp/DataScience?

Thanks in advance!

**Comment by rngadam** [comment]
@evaristoc we have a local group of people working together on the FreeCodeCamp curriculum. We'd like to have a leaderboard updated based on their current score. Eventually, we'd also like to show the progression in the physically co-located sessions versus at home, so we'd like to snapshot the scores at a particular point in time (the day of the session).

Rate & size; I don't think we'd need to capture the data more than twice a day (morning and evening). We'd snapshot into a MeteorJS/mongodb.

**Comment by rngadam** [comment]
The leaderboard we can base directly on the example code provided with MeteorJS which looks like this:

![screen shot 2016-05-07 at 1 31 18 pm](https://cloud.githubusercontent.com/assets/538542/15090353/49a33034-1458-11e6-8921-33cf203559cc.png)

**Comment by raisedadead** [comment]
@rngadam You might want to have a Leaderboard app that @roelver made sometime back
https://github.com/roelver/fcctop100

Hoping it helps.

**Comment by evaristoc** [comment]
@rngadam sounds nice! As commented above by @raisedadead there is already an implementation that does something similar.

I am personally not opposed to your idea, actually I would like to encourage you and your group to continue. However twice a day is too much and for the current implementation the running time reached 7 hours at one point.

If you are still interested, check the current project and please follow the settings suggested by @roelver's fcctop100? He is also the owner of the FCC API development, by the way.

If this discourages you to pursue a Leaderboard, perhaps you could try something similar for a different FCC platform? For example: GitHub contributors (wiki and core code)? There is no information available and it would be interesting to have a nice weekly/monthly information about FCC's GitHub contributions by campers. Much nicer if you can work historical data. Much much nicer if you can detect on which topic they were contributing the most.

An application of that kind could be a good topic for a publication at Medium.

Let me know what you think. Hope you don't mind if I close this issue. Thanks, @rngadam!

**Comment by rngadam** [comment]
There might be a misunderstanding; we'd only fetch information for the 20 or so participants in our local group twice a day at most, NOT all fcc participants.

**Comment by evaristoc** [comment]
@rngadam that's another thing. Nice!

Still, while no other option available please keep similar specs for data extraction as those proposed by @roelver's project. It would be much better if you follow those prescriptions even if yours is a smaller project. 

Also let us know about the app and the repo of the project? Make it public here.

**Comment by DanStockham** [comment]
Do you know how soon the api will be publicly available? I'm attempting to do my React Leaderboard project on my local machine instead of using codepen to practice some backend skills.
