### ISSUE TITLE
Console.log not working

### ISSUE THREAD

**Issue by ionakathryn** [FreeCodeCamp/FreeCodeCamp#8480]
**Title Case a Sentence**
https://www.freecodecamp.com/challenges/title-case-a-sentence

**Issue Description**
There is no output on the terminal for console.log. When I run even basic console.log nothing happens e.g:
console.log("hi");

**#### Browser Information**
I have tried on 3 different browsers: Chrome, Firefox & Internet Explorer. On a laptop & separate desktop. 

**#### Your Code**
The code is not relevant. The issue is that console.log doesn't output anything, just a blank screen.

console.log("hi");

doesn't work.....

**Comment by BKinahan** [comment]
In each of those three different browsers, did you try looking at the browser JavaScript console? That is where messages are printed when using `console.log()`, not in the FCC editor's output section.

**Comment by ionakathryn** [comment]
Hi I am not sure what I'm looking at there because there is a lot of information but this is the main thing I thought was relevant:

"NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITaskbarTabPreview.invalidate]"

What does this mean? This is from using:
console.log("hi");
Thanks

**Comment by theflametrooper** [comment]
@ionakathryn Make sure your press `Run tests`. This works fine for me.

**Comment by ionakathryn** [comment]
Here is what i have..I don't understand at all why it's not turning up in the FCC terminal...thanks
![title a case](https://cloud.githubusercontent.com/assets/16601596/15087262/36ce555c-13df-11e6-9032-be4ca8cef71a.png)

Please can someone explain this to me....

**Comment by sludge256** [comment]
This may have been resolved based on the conversation that happened on Gitter :point_up: [May 6, 2016 3:09 PM](https://gitter.im/FreeCodeCamp/HelpJavaScript?at=572d1620f9a53a60793c7a8b)

>Also you split the string on " " so all the " " are gone

:point_up: [May 6, 2016 3:10 PM](https://gitter.im/FreeCodeCamp/HelpJavaScript?at=572d166e3170252648f4b36d)

@ionakathryn please confirm that the original issue has been resolved. The subsequent comments are best addressed via Gitter as we do not provide code support in GitHub issues.

**Comment by ionakathryn** [comment]
This issue has not been resolved. The terminal window in FCC is not working...

**Comment by ltegman** [comment]
The in page output does not capture console logs. This is expected. Thanks and happy coding!
