### ISSUE TITLE
Get Set for our Back End Development Projects - mongod

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [FreeCodeCamp/FreeCodeCamp#8482]
#### Challenge Name

https://www.freecodecamp.com/challenges/get-set-for-our-back-end-development-projects

#### Issue Description

On step 9 there is an issue with mongod --smallfiles. I am assuming this is a c9 issue with the way the project is setup.

In the .bash_aliases there is a line: alias mongod="mongod --bind_ip=$IP --small --rest '$@'" --small does not appear to be a mongod flag and the flag --rest has other requirements, namely --httpinterface

The easiest way to fix this is by modifying the line to: alias mongod="mongod --bind_ip=$IP --smallfiles --rest --httpinterface " and then: source ~/.bash_aliases

#### Browser Information

C9, Chrome browser on Centos 7.2

* Browser Name, Version: Chrome 47.0.2526.106 (64-bit)
* Operating System: Centos 7.2
* Mobile, Desktop, or Tablet: Gnome

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by jondcoleman** [comment]
Opened a PR here to fix it on c9: https://github.com/c9/templates/pull/50

**Comment by jondcoleman** [comment]
Also @moigithub recommend this as a one line command to fix this:

`sed -i".bak" '/mongod/d' ~/.bash_aliases && source ~/.bash_aliases`

**Comment by raisedadead** [comment]
@MichaelLeeHobbs Thanks for reporting.
@jondcoleman Thanks for the PR. I hope that gets merged soon.

**Comment by raisedadead** [comment]
Closing as resolved.

**Comment by jondcoleman** [comment]
FYI the patch has made it into production now. https://github.com/c9/templates/issues/51#event-676590813

**Comment by raisedadead** [comment]
@jondcoleman awesome! thanks for the update once again.
