### ISSUE TITLE
Counting cards - can't find the bug

### ISSUE THREAD

**Issue by stark1024** [FreeCodeCamp/FreeCodeCamp#8487]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%20count%2B%3D1%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%20count%2B%3D0%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20'J'%3A%0A%20%20%20%20case%20'Q'%3A%0A%20%20%20%20case%20'k'%3A%0A%20%20%20%20case%20'A'%3A%20count-%3D1%3B%0A%20%20%7D%0A%20%20if(count%3E0)%7B%0A%20%20%20%20return%20count%2B%22%20Bet%22%3B%0A%20%20%7D%20else%0A%20%20return%20count%2B%22%20Hold%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(10)%3B%20cc('J')%3B%20cc('Q')%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6: count+=1;
      break;
    case 7:
    case 8:
    case 9: count+=0;
      break;
    case 10:
    case 'J':
    case 'Q':
    case 'k':
    case 'A': count-=1;
  }
  if(count>0){
    return count+" Bet";
  } else
  return count+" Hold";
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(10); cc('J'); cc('Q'); cc('K'); cc('A');

```

**Comment by erictleung** [comment]
@stark1024 thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by stark1024** [comment]
Apologies sir! I will keep this in mind. Thank you for the help.

**Comment by jamella1** [comment]
you just needed to capitalize the 'K' in King, pumpkin!
