### ISSUE TITLE
Fix spacing in cell of Counting Cards table

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8488]
#### Challenge Name

https://www.freecodecamp.com/challenges/counting-cards

#### Issue Description

In the table in the instructions, there needs to be a space between the `K` and `A`. Right now, it looks like:

> 'K','A'

but it should be:

> 'K', 'A'

The code that needs to be changed is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/e14cb69d5b4e8c135d74aed1467c85bd31783127/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3760).

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/15082529/0a89f83c-137d-11e6-96b3-c82e184a073d.png)

**Comment by raisedadead** [comment]
Lets keep this for a first time contributor only!

**Comment by mriyaz** [comment]
Hi guys. Starting my contribution to Free Code Camp here. I will work on this, but I will need to understand FCC code base asap. Any pointers towards this will be appreciated.

**Comment by erictleung** [comment]
@mriyaz thanks for your interest in helping out! This issue doesn't require knowing the FCC codebase too extensively. But we do ask you read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of the issue and don't hesitate to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions about helping. The line of code you need to change is in [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/e14cb69d5b4e8c135d74aed1467c85bd31783127/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3760). Good luck!

**Comment by pranayberry** [comment]
Will create a PR. Fixed the issue as per the contribution guidelines. Just one question How to preview the fixed file because I don't know much about JS as of now.
