### ISSUE TITLE
Counting Cards teaches an antipattern

### ISSUE THREAD

**Issue by dmitryleskov** [FreeCodeCamp/FreeCodeCamp#8497]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards) has an issue: it teaches an antipattern.

The function should take the current count as a parameter and return the new count.

**Comment by ltegman** [comment]
Pure functions are an ideal to strive for, but impure functions are not an antipattern. There are many cases where side-effects are necessary. I'll leave this open for other @FreeCodeCamp/issue-moderators to weigh in, but I don't see this as a problem.

**Comment by SaintPeter** [comment]
There is certainly no requirement in Javascript for functions to be "Pure".  It's definitely something to strive for, but it's not disallowed, nor is it an anti-pattern.  

You could see it as being a part of a larger class where `count` is a private variable.  It would be very reasonable to have the card counting function be a member function. 

I could, potentially, see a way to make it work with passing in the count value - it would make testing somewhat easier in some regards, but somewhat harder in other regards.  It's harder to test multiple iterations if we have to keep track of a running count "ourselves".  We'd have to write more individual tests, one per card.

**Comment by BerkeleyTrue** [comment]
@ltegman and @SaintPeter are right, there is no requirement that javascript functions be pure.

On top of that, challenges are meant to teach specific concepts and not necessarily teach best practices.

Happy Coding!

**Comment by sjames1958gm** [comment]
Teaching and demonstrating the use of global variables in this fashion, while not an antipattern, shouild be discouraged.
