### ISSUE TITLE
Check for Palindromes - is underscore a symbol?

### ISSUE THREAD

**Issue by dmitryleskov** [FreeCodeCamp/FreeCodeCamp#8499]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20a%20%3D%20str.toLowerCase().replace(%2F%5B%5E0-9a-z%5D%2B%2Fg%2C%22%22)%3B%0A%20%20var%20b%20%3D%20a.split(%22%22).reverse().join(%22%22)%3B%0A%20%20%2F%2Freturn%20a%0A%20%20return%20a%20%3D%3D%20b%3B%0A%7D%0A%0A%0A%0Apalindrome(%22A%20man%2C%20a%20plan%2C%20a%20canal.%20Panama%22)%3B%0A) has an issue.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  var a = str.toLowerCase().replace(/[^0-9a-z]+/g,"");
  var b = a.split("").reverse().join("");
  return a == b;
}
palindrome("0_0 (: /-\ :) 0-0");

```
I thought `/\W+/g` would work here, but it fails the last test. Apparently "_" is the source of ambiguity.

**Comment by alistermada** [comment]
The underscore is a symbol; it just so happens to be the only one included in `\w` and thus excluded in `\W`.

Relevant background on `\w`:
http://programmers.stackexchange.com/questions/237754/why-does-the-regular-expression-metacharacter-w-include-underscores

**Comment by raisedadead** [comment]
Thanks @alistermada 

@dmitryleskov Yes ` _` is an symbol, and this last case is kind of an tricky one intentionally, Lol when I was solving this challenge I was stuck at it for hours before I figured out the regex.

But yes its still valid!

Closing as not an issue with the Code Base.

**Comment by sludge256** [comment]
To clarify, alphanumeric and word characters are not the same thing. Word characters are a superset of alphanumeric characters. That's why the MDN entry for RegExp is worded the way it is for `\w`
>Matches any alphanumeric character from the basic Latin alphabet, including the underscore. Equivalent to [A-Za-z0-9_].

and `\W`
>Matches any character that is not a word character from the basic Latin alphabet. Equivalent to [^A-Za-z0-9_].

Notice that the second explanation says "word character" and no simply "alphanumeric character."
