### ISSUE TITLE
I have met the codes requirements but it won't let me progress

### ISSUE THREAD

**Issue by askadroid** [FreeCodeCamp/FreeCodeCamp#8500]
#### Change The Colour Of Text
[link to challenge](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3C!Doctype%3E%0A%3Chtml%3E%0A%20%20%3CHead%3E%0A%20%20%20%20%3Ctitle%3E%20%3C%2Ftitle%3E%0A%20%20%20%20%3C%2Fhead%3E%0A%20%20%3Cbody%3E%0A%20%20%20%20%3Cdiv%20class%3D%20%22heading%22%3E%20%0A%3Ch2%3EHello%20World%3C%2Fh2%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%20headingBody%3E%20%0A%20%20%20%20%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22subHeading%22%3E%0A%20%3C!--%20%3Ch2%20style%3D%22color%3A%20%23FF0000%20red%22%3ECatPhotoApp%3C%2Fh2%3E%20--%3E%0A%20%20%3Ch2%20style%3D%22color%3A%20red%22%3ECatPhotoApp%3C%2Fh2%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%20%22subHeading%20body%22%3E%20%0A%20%20%20%20%20%20%3Cp%3E%20Kitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fbody%3E%0A%3C%2Fhtml%3E%0A%0A)

#### Issue Description
the issue is what's not happening with my current code it isn't progressing.

#### Browser Information
Chrome Version 50.0.2661.94 m
Windows 10
Laptop

#### 
<!Doctype>
<html>
  <Head>
    <title> </title>
    </head>
  <body>
    <div class= "heading"> 
<h2>Hello World</h2>
      </div>
    <div class= headingBody> 
    </div>
<div class="subHeading">
 
  <h2 style="color: red">CatPhotoApp</h2>
   </div>
    <div class= "subHeading body"> 
      <p> Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
    </div>
  </body>
</html>

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot
![capture](https://cloud.githubusercontent.com/assets/19241566/15093656/dc51b716-1485-11e6-8a12-c350a6d7584d.PNG)

**Comment by raisedadead** [comment]
@askadroid I am afraid your code is incorrect. There is a typo in there somewhere! :wink: 

GitHub Issues are for reporting bugs on the website only.

Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
