### ISSUE TITLE
Challenge Create an Ordered list Has an Issue

### ISSUE THREAD

**Issue by SinglaSunil** [FreeCodeCamp/FreeCodeCamp#8501]
Challenge [Create an Ordered List](https://www.freecodecamp.com/challenges/create-an-ordered-list#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3EMilk%3C%2Fli%3E%0A%20%20%3Cli%3ECurd%3C%2Fli%3E%0A%20%20%3Cli%3EButter%3C%2Fli%3E%0A%3C%2Ful%3E%0A%0A%3Cp%3ETop%203%20things%20cats%20hate%3C%2Fp%3E%0A%3Col%3E%20%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Fol%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>Milk</li>
  <li>Curd</li>
  <li>Butter</li>
</ul>

<p>Top 3 things cats hate</p>
<ol> 
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ol>

```

**Comment by sludge256** [comment]
It looks like the instructions are incorrect.

>Your should have an ordered list for "Top 3 things cats hate"  
is missing a semicolon.

```
 "assert.equal($(\"ol\").prev().text(), 'Top 3 things cats hate:', 'message: Your should have an ordered list for \"Top 3 things cats hate\"');",
```
[Link to code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/258c6b5fcf89086884e6c1cd994843690f606f73/seed/challenges/01-front-end-development-certification/html5-and-css.json#L1956)

**Comment by BKinahan** [comment]
For whomever picks this up,
> Your should have an ordered list for "Top 3 things cats hate"

should also begin with "You" for proper grammar and to match the subsequent test message, rather than "Your".

**Comment by qualitymanifest** [comment]
Similar issue on this challenge: If you capitalize `Things Cats Love` like it says on one of the tests on the left, it will fail.

**Comment by mriyaz** [comment]
Hello guys, I am working on this issue

**Comment by mriyaz** [comment]
I have tested this issue @raisedadead  and it works for me [Create an Ordered List](https://www.freecodecamp.com/challenges/create-an-ordered-list#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Fol%3E%0A%20)

**Comment by mriyaz** [comment]
@raisedadead, BTW which browser have you been using. I have tested this on chrome Version 50.0.2661.94 m

**Comment by raisedadead** [comment]
@mriyaz This is reproducible on all browsers"

> Your should have an ordered list for "Top 3 things cats hate"

should be

> Your should have an ordered list for "Top 3 things cats hate**:**"

There is a semi colon missing. Reset the code or open the challenge with a clean link in an incognito window and use the code from the description above this should be easy enough to reproduce.

https://www.freecodecamp.com/challenges/create-an-ordered-list

**Comment by raisedadead** [comment]
@mriyaz I have update the comment above for the things to be updated while checking this challenge.

**Comment by mriyaz** [comment]
Sorry @raisedadead, I don't get any error while working on this challenge 
[https://www.freecodecamp.com/challenges/create-an-ordered-list](https://www.freecodecamp.com/challenges/create-an-ordered-list)

**Comment by raisedadead** [comment]
@mriyaz Thats because you are using

`<p>Top 3 things cats hate:</p>`
instead of
`<p>Top 3 things cats hate</p>`

You are using the correct code. But the instructions accidentally state to use a statement without a **:**

**Comment by jhadams82** [comment]
So..  should we add more versions of the test to allow people to not include the semicolon?  Or to use all caps?

Or are we sticking with a strict expectation and we just need to fix a couple typos?  Cuz I feel like I can do that for my first FCC pull request ever  =)

**Comment by mriyaz** [comment]
@jhadams82  Please go ahead with the PR. I am stuck in creating a local instance of FCC. I am coordinating with @raisedadead over this problem.
