### ISSUE TITLE
Typo on submit

### ISSUE THREAD

**Issue by mmccullar** [FreeCodeCamp/FreeCodeCamp#8503]
Hi guys, simple issue here you might want to know about: on the /config directory commit message, there is a typo. "remvoe old passport file" When it should be "Remove old passport file."

Not too huge of an issue but thought you'd like to know!

- Matt

**Comment by raisedadead** [comment]
@mmccullar : Thanks Matt.

I am afraid to fix that commit we are gonna have to probably rebase the commits, and since there are a ton of commits its going to be tedious.

So, I guess we are going to have to live with this one! :sob: Sorry about that.

Thanks again!
Happy coding!
