### ISSUE TITLE
Wiki at Free Code Camp's website has readability issues with night mode

### ISSUE THREAD

**Issue by hamzashezad** [FreeCodeCamp/FreeCodeCamp#8504]
[The wiki](https://www.freecodecamp.com/wiki/en/) has a colour contrast problem with night mode enabled: dark text colour with a dark background. It's not quite readable.

Here is a screenshot:

![](http://i.imgur.com/fb3VdjR.png)

**Comment by raisedadead** [comment]
The new wiki is very much work in progress @hamzashezad .
Thanks for reporting this, however supporting night mode may take a while before we first fix the wiki's default UX first.

Nevertheless we acknowledge this, and should be taking it up in the wiki updates.
