### ISSUE TITLE
On certain views, flash notices are awkwardly placed

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8505]
![](https://www.evernote.com/l/Ar_mgMVRy0pLEZXMzrc1TM1W8bv1oJwnoggB/image.png)

Steps to reproduce: Go to a nonexistent challenge like this one: https://www.freecodecamp.com/challenges/dfdsfds

**Comment by cashhh** [comment]
I'm going to work on this

**Comment by theflametrooper** [comment]
@cashhh You need to create a PR to our repo, not your fork. https://github.com/FreeCodeCamp/FreeCodeCamp/compare

**Comment by cashhh** [comment]
Can you elaborate please? I thought that was what I did.

**Comment by theflametrooper** [comment]
@cashhh You created a PR to your fork. You need to create a PR to https://github.com/FreeCodeCamp/FreeCodeCamp instead.

**Comment by cashhh** [comment]
Haha.. Okay got it, thanks.
