### ISSUE TITLE
[Fix] Update Code of Conduct

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#8506]
Update official code of conduct in the website [**FreeCodeCamp.com/code-of-conduct**](https://www.freecodecamp.com/code-of-conduct) with the one in the wiki [**Code of Conduct** (wiki)](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Code-of-Conduct) which was updated recently.

#### Related Files:
- **File to Update:** [**code-of-conduct.jade** (FCC repository file)](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/resources/code-of-conduct.jade)
- **Reference File:** [**Code-of-Conduct.md** (FCC wiki file)](https://github.com/FreeCodeCamp/wiki/blob/master/Code-of-Conduct.md)
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/HelpContributors"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>FreeCodeCamp/HelpContributors</b></a></kbd></p>

> ----

**Currently Assigned to:** @josevill 

> *If you want to work on this, please comment below and we can chat over* <kbd><a href="https://gitter.im/FreeCodeCamp/HelpContributors"><img src="http://i.imgur.com/ThSWa6Y.png?2"> <b>gitter</b></a></kbd>
Note: you may be assigned **only if** the current assignee doesn't respond within a given time-frame.

**Comment by josevill** [comment]
I will make a PR later today on this matter.

**Comment by nishant-tomer** [comment]
I would like to do this, if not done already.

**Comment by theflametrooper** [comment]
@josevill Are you working on this fix? If not I will assign @nishant-tomer.

**Comment by nishant-tomer** [comment]
Link broken for reference file : Code-of-Conduct.md

**Comment by raisedadead** [comment]
@nishant-tomer since you have already made a PR, we may accept it this time. But please make a note that you can resolve only one "first-timers-only" only issue.

@theflametrooper already accepted the other PR. (which should have been rejected because the issue had a PR already)

Nevertheless in good spirit and the hard work you have put in is much appreciated. 

Thanks again for contributing.

**Comment by nishant-tomer** [comment]
oh oh oh! I see. my bad. Thank you for explaining this or i'd have gone on with this streak. I'll take care from now on.

**Comment by raisedadead** [comment]
@nishant-tomer 

Keep those PR's coming, please go wild on taking down as many "help wanted" ones :wink: , we encourage you to! But as you have already noticed just not on the first-timers-only ones!

Thanks a lot again for contributing!
