### ISSUE TITLE
Fix Test in Override Styles Using Important

### ISSUE THREAD

**Issue by arthurver** [FreeCodeCamp/FreeCodeCamp#8511]
Challenge [Override All Other Styles by using Important](https://www.freecodecamp.com/challenges/override-all-other-styles-by-using-important#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%7B%0A%20%20%20%20color%3A%20pink%20!important%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%20style%3D%22color%3A%20white%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text{
    color: pink !important;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>

I can't go to the next challenge, because I haven't completed this point:

> Your pink-text class declaration should have the !important keyword to override all other declarations.

**Comment by erictleung** [comment]
@arthurver thanks for the issue. It appears that the regex for the test needs to allow spaces between `.pink-text` and the bracket. The beginning of the assert test in [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4268) is currently

```json
"assert(code.match(/\\.pink-text\\s+\\{\\s+color: ...
```

But it should be changed to:

```json
"assert(code.match(/\\.pink-text\\s*?\\{\\s+color: ...
```

Next time if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) first to confirm this is a bug with the site or if there is a problem with your code.

**Comment by Charlotteis** [comment]
I'm going to tweet about this tomorrow from the twitter.com/yourfirstpr account! Thanks for this issue! :)

**Comment by Mausamagr** [comment]
I am getting the same issue again. Not able to pass this challenge due to this bug. What to do?

**Comment by raisedadead** [comment]
@Mausamagr please create a separate issue and share the code that you have which fails.

**Comment by Mausamagr** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9455
