### ISSUE TITLE
Access MultiDimensional Arrays With Indexes

### ISSUE THREAD

**Issue by bricedjilo** [FreeCodeCamp/FreeCodeCamp#8515]
Challenge [Access MultiDimensional Arrays With Indexes](https://www.freecodecamp.com/challenges/access-multidimensional-arrays-with-indexes#?solution=%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B1%2C2%2C3%5D%2C%20%5B4%2C5%2C6%5D%2C%20%5B7%2C8%2C9%5D%2C%20%5B%5B10%2C11%2C12%5D%2C%2013%2C%2014%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myData%20%3D%20myArray%5B0%5D%5B0%5D%20%2B%20myArray%5B2%5D%5B0%5D%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myArray = [[1,2,3], [4,5,6], [7,8,9], [[10,11,12], 13, 14]];

// Only change code below this line.
var myData = myArray[0][0] + myArray[2][0];
```

I think the code used to validate the answer in this challenge has a bug. 
Could you please investigate.

**Comment by BKinahan** [comment]
Huh. Guess we need to specify that correct code is expected to access only one value from the array rather than using arithmetic operators to combine multiple values.

That, or perhaps populate the array with strings instead of numbers.

`var myArray = [['1','2','3'], ['4','5','6'], ['7','8','9'], [['10','11','12'], '13', '14']];`

Any reasons why that's a bad solution?

**Comment by JAWL** [comment]
Stop.

**Comment by BKinahan** [comment]
@JAWL Stop what? You may need to adjust your notification settings.

**Comment by erictleung** [comment]
@BKinahan I agree that when read in a certain way, you can interpret the instructions as to get the value 8 in any way you want.

My suggestion on what the instructions should read is:

>  Using bracket notation, read from `myArray` to select the element `8` so that `myData` will equal `8`.

And an extra test can also be added to check for the use of only one accessed value. Any suggestions on a better rewrite are welcome.

**Comment by pranayberry** [comment]
My suggestion for the instructions is:
> Using bracket notation select an element from `myArray` such that myData is equal to 8.
If this instruction is worthwhile I'll change it and post a PR soon.

**Comment by bricedjilo** [comment]
After reading the above suggestions, I was able to pass the challenge by submitting:
`var myData = myArray[2][1];`
<br />
So as @pranayberry  suggested, the instructions should be change to
> Using bracket notation select an element from myArray such that myData is equal to 8.
In the editor, the code should be 
`// Setup
var myArray = [[1,2,3], [4,5,6], [7,8,9], [[10,11,12], 13, 14]];

// Only change code below this line.
var myData = "Eneter your number here" `

**Comment by Faikabbaszadeh** [comment]
// Setup
var myArray = [
  [1,2,3],
  [4,5,6],
  [7,8,9],
  [[10,11,12], 13, 14]];
// Only change code below this line.
var myData = myArray[2][1];

**Comment by markayd** [comment]
I am new to coding and this challenge like a lot of them is still so vague as to what it is we are doing ? i am not the only person that feels this way either.

**Comment by meizaifeng** [comment]
```
var myData = myArray[2][1];
```

**Comment by Simbaxo** [comment]
I see the answer but how did u guys get that?

**Comment by ebbalundgren** [comment]
i have never been more confused, why is the solution 2, 1??

**Comment by astoroid** [comment]
How [2][1] equals 8. Can anyone break it down?

**Comment by aleksayaroshrenko** [comment]
For me, this video explanation helped to figure out why [2][1]: https://youtu.be/9glEVOTrSYo

**Comment by Davidgsilva** [comment]
var myArray = [[1,2,3], [4,5,6], [7,8,9], [[10,11,12], 13, 14]];

// Only change code below this line.

var myData = myArray[2][1];

Quick Explanation: 

The code above is setting the variable myData to target the third array within the nested array:
[2] = [7,8,9]
[1] = [8]

You target the third array and you only want the second # within that array; which is the number 8.

**Comment by Koder90** [comment]
Thank you davidgsilva for solution. Instructions were to target all three arrays which is why it was confusing.
