### ISSUE TITLE
cannot solve this stuff. Some sort of inconsistency in my chrome browser

### ISSUE THREAD

**Issue by sidharthsuresh** [FreeCodeCamp/FreeCodeCamp#8516]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=var%20myVar%20%3D%20%22outer%22%3B%0Afunction%20myLocalScope()%20%7B%0A%20%20%0A%20var%20myVar%20%3D%20%22fun%22%3B%0A%20%20%0A%7D%0A%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myVar = "outer";
function myLocalScope() {
  
 var myVar = "fun";
  
}


// Run and check the console
// myVar is not defined outside of myLocalScope


// Now remove the console log line to pass the test


```

**Comment by ltegman** [comment]
Issue does not describe a problem. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance and if they confirm what you're seeing is a site bug file an issue with a detailed description and steps to reproduce the error.

Thanks and happy coding!
