### ISSUE TITLE
HTML Waypoint 13 returns false negative.

### ISSUE THREAD

**Issue by omarwilson3** [FreeCodeCamp/freecodecamp#852]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

When inputing a correct answer, the site claims the font size is not yet set. The new size is properly displayed to the right but "Give your p elements the font-size of 16px." still shows a red X. Even copy and pasting your own markup form waypoint 14 does not work.

Example:
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

edit(@berkeleytrue): added backticks.

**Comment by BerkeleyTrue** [comment]
Cannot replicate. Can you give us a screenshot of your issue?

**Comment by BerkeleyTrue** [comment]
Please feel free to re-open if this is still an issue.
