### ISSUE TITLE
Won't let me pass "Check for Palindromes"

### ISSUE THREAD

**Issue by dchen97** [FreeCodeCamp/FreeCodeCamp#8521]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20str.length%20-%201%3B%20j%20%2B%2B)%20%7B%0A%20%20%20%20if%20(str.charAt(j))%7B%0A%20%20%20%20%20%20str%20%3D%20str.replace(%2F%5B%5CW_%5D%2B%2Fg%2C%20%22%22)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20str.length%20%2F%202%20%2B%201%3B%20i%20%2B%2B)%20%7B%0A%20%20%20%20if%20(!(str.charAt(i)%20%3D%3D%20str.charAt(str.length-1-i)))%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  str = str.toLowerCase();
  for (var j = 0; j < str.length - 1; j ++) {
    if (str.charAt(j)){
      str = str.replace(/[\W_]+/g, "");
    }
  }
  
  for (var i = 0; i < str.length / 2 + 1; i ++) {
    if (!(str.charAt(i) == str.charAt(str.length-1-i))) {
      return false;
    }
  }
  return true;
}



palindrome("eye");

```
All of my code has passed the tests and everything seems correct, but when the "Submit challenge" modal loads, it doesn't let me actually submit the challenge. The "Submit and go to the next challenge" button is unclickable and it has the loading image sequence constantly present even though nothing is loading.

![image](https://cloud.githubusercontent.com/assets/12034267/15102002/e83d1b3a-155f-11e6-9047-039b92c56973.png)

Won't give me credit for challenge until I click the button, but it won't let me.

**Comment by khaduch** [comment]
Hello -
It seems that the free code camp servers were having an issue, or many people in the chat rooms were commenting on that.  Someone on the admin team can confirm that - I just saw a note that there is a DDOS attack on the site.

**Comment by erictleung** [comment]
@dchen97 sorry you're having issues with submitting your challenge. @khaduch is correct, as we had some issues earlier today. Try again when you get the chance and see if this issue still persists.

**Comment by erictleung** [comment]
@dchen97 closing as stale. If you are still experiencing the problem, please update us. Happy coding!
