### ISSUE TITLE
The title is red like it should be but i can't move forward

### ISSUE THREAD

**Issue by NicH4real** [FreeCodeCamp/FreeCodeCamp#8523]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%3E%3Ch2%20style%3D%22color%3Ared%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2><h2 style="color:red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by NicH4real** [comment]
![screen shot 2016-05-08 at 11 52 40 pm](https://cloud.githubusercontent.com/assets/15953024/15104666/08a7a72e-1578-11e6-97d2-60eada0e2ab1.png)

This

**Comment by erictleung** [comment]
@NicH4real thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: check the number of `h2` tags and if they have closing tags. Happy coding!
