### ISSUE TITLE
Padding need on "required asterix" notification

### ISSUE THREAD

**Issue by theflametrooper** [FreeCodeCamp/FreeCodeCamp#8524]
#### Issue Description
Padding is needed on `Challenges required for certifications are marked with a *`.

#### Browser Information
* Browser Name, Version: Chrome
* Operating System: Android
* Mobile, Desktop, or Tablet: Mobile 

#### Screenshot
![](http://i.imgur.com/9h9OnIx.png)

**Comment by theflametrooper** [comment]
To contributor: Add the `padding` on line 76 on [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/less/map.less#L76) file using `less`.

**Comment by imjamesdotme** [comment]
![fcc-map-issue](https://cloud.githubusercontent.com/assets/9949268/15119800/8c8a6db4-160a-11e6-930b-cc3ee025b41a.png)

It appears that `position: absolute` needs removing from the class `.mapWrapper` as well. This will allow the accordions to sit full width across small screens. This is also what's causing the issue with the challenges copy.

**Comment by theflametrooper** [comment]
There are a couple of things that need fixed. I'm gonna remove the `first-timers-only` label.

**Comment by imjamesdotme** [comment]
@theflametrooper I just submitted a pull request (my first ever) to fix this issue. As you'll see from my notes, half of the issue was already fixed on the staging branch. 😄

**Comment by theflametrooper** [comment]
@imjamesdotme That works now, great! Congrats on your first pr...

**Comment by imjamesdotme** [comment]
@theflametrooper Thank you very much 😄  Hopefully first of many!
