### ISSUE TITLE
Setting href to # still does not work.

### ISSUE THREAD

**Issue by swapy** [FreeCodeCamp/FreeCodeCamp#8529]
Challenge [Make Dead Links using the Hash Symbol](https://www.freecodecamp.com/challenges/make-dead-links-using-the-hash-symbol#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

Ideally this should work . I dont know why it isnt working.
Chrome version : Version 50.0.2661.94 (64-bit)

**Comment by erictleung** [comment]
@swapy I can't seem to reproduce this. Your code works for me and looks correct to me. Have you tried resetting your code and trying again?

**Comment by swapy** [comment]
I have tried a reset and cleared code editor but it did not work.
FYI: Only this step did not work I moved ahead and others worked.

On Mon, 9 May 2016 10:18 pm Eric Leung, <notifications@github.com> wrote:

> @swapy <https://github.com/swapy> I can't seem to reproduce this. Your
> code works for me and looks correct to me. Have you tried resetting your
> code and trying again?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8529#issuecomment-217920121>
>
-- 
Regards,
Swapnil P.Marathe

**Comment by ltegman** [comment]
Are you getting any console errors?

**Comment by swapy** [comment]
No I am not getting any errors in console

**Comment by swapy** [comment]
I am sorry, I tried it again and it worked.

**Comment by Seonaid** [comment]
I had the same problem with this challenge. It did work after two refreshes, but I think there's still an issue here. (Using Chrome 50.0.2661.102 on a MacBook with El Capitan. Started by working through from the previous challenge, and got no feedback at the point that I clicked Run Tests. Ctrl-Enter didn't work either. Did a "Reset" with the button in the layout, and tried a second time, but still had the same problem. Did a hard reload by using the keyboard shortcut of Command-R, which launched in a new tab. This carried my code forward, and in the new tab, "Run Tests" was successful.)

**Comment by worldhroda** [comment]
I kept replacing href with # but realized it said the value of href then it worked

**Comment by akapetzoglou** [comment]
@Seonaid Hard refresh worked for me as well.

**Comment by carlitos23** [comment]
I was stuck on this problem for 20mins until I found out that the code was bugged for some reason and the way it fixed was refreshing my browser. I'm using google chrome btw.
