### ISSUE TITLE
Comment slashes are rendered.

### ISSUE THREAD

**Issue by omarwilson3** [FreeCodeCamp/freecodecamp#853]
Challenge http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

HTML Waypoint 16 says: "Now try commenting out your call to Google Fonts, so that the "Lobster" font isn't available." The issue is that the renderer to the right does not seem to handle comments correctly. 

When I try to comment out the code thus:
/*
href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
*/ 

instead of commenting out the code, the code is still run and "/* */" is also shown in the renderer.

**Comment by terakilobyte** [comment]
@omarwilson3,

/* */ isn't a valid comment in html which is the language you're using in that challenge. Please use  html comments.
