### ISSUE TITLE
Having trouble with the Mad Lib 

### ISSUE THREAD

**Issue by sharonwischkaemper** [FreeCodeCamp/FreeCodeCamp#8534]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@sharonwischkaemper if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). There are many people there willing to give hints and help on these challenges. Good luck and happy coding!
