### ISSUE TITLE
Challenge text is wrong

### ISSUE THREAD

**Issue by lucrp** [FreeCodeCamp/FreeCodeCamp#8535]
Challenge [Use Clockwise Notation to Specify the Padding of an Element](https://www.freecodecamp.com/challenges/use-clockwise-notation-to-specify-the-padding-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2020px%2040px%2020px%2040px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3A%20red%3B%0A%20%20%20%20padding%3A%2020px%2040px%2020px%2040px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2020px%2040px%2020px%2040px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.

The challenge asks to "Use Clockwise Notation to give the ".green-box" class a padding of 40px on its top and left side, but only 20px on its bottom and right side." If the clockwise notation is "top, right, bottom, left" the correct would be asking to give the " '.green-box' class a padding of 20px on its top and left side, but only 40px on its bottom and right side.". Because the correct answer to this challenge is:

```html
  .green-box {
    background-color: green;
    padding: 20px 40px 20px 40px;
  }
```
My code:
```html

<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 20px 40px 20px 40px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px 40px 20px 40px;
  }

  .green-box {
    background-color: green;
    padding: 20px 40px 20px 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by dwd2010** [comment]
@lucrp, read this again. "Use Clockwise Notation to give the ".green-box" class a padding of 40px on its top and left side, but only 20px on its bottom and right side."
your code is wrong.  try again.

**Comment by lucrp** [comment]
@dwd2010 , when I type the correct answer to the question `  .green-box {
    background-color: green;
    padding: 40px 20px 40px 20px;
  }` I get this errors:
![freecodecamp](https://cloud.githubusercontent.com/assets/6523221/15126486/a2753070-1608-11e6-8ed5-eca8b52ee6b3.png)

So I think that the question would be "Use Clockwise Notation to give the the opposite: ".green-box" class a padding of 20px on its top and left side, but only 40px on its bottom and right side."

**Comment by dwd2010** [comment]
@lucrp, it is not error. I trying to say you got wrong answer.

**Comment by lucrp** [comment]
@dwd2010 You're right. I didn't read it right. Now I get it. Thank you and excuses for opening an Issue that was my mistake. Next time I'll ask for help at Gitter first.
