### ISSUE TITLE
Edit text issue

### ISSUE THREAD

**Issue by ICesarI** [FreeCodeCamp/freecodecamp#854]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. At the end the edit text cursor moves erratically, it tends to move the cursor at the beginning of the last line.

**Comment by QuincyLarson** [comment]
We cannot reproduce this. Which browser are you using?

**Comment by BerkeleyTrue** [comment]
Please feel free to re-open if issue still persists.
