### ISSUE TITLE
Span element does not work, 'love' doesn't turn into Red in my Opera browser

### ISSUE THREAD

**Issue by rohan222** [FreeCodeCamp/FreeCodeCamp#8541]
Challenge [Create a Custom Heading](https://www.freecodecamp.com/challenges/create-a-custom-heading) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36 OPR/37.0.2178.32</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <h2 class="text-primary text-center">CatPhotoApp</h2>

  <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary">Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by ltegman** [comment]
I'm unable to repro this in Opera and there's nothing wrong with the markup used. My guess is that some resource (likely the bootstrap css) is not loading correctly for you and causing this error. Closing as not a site bug. Thanks and happy coding!

**Comment by rohan222** [comment]
Hello Itegman,                        You are absolutely right regarding the issue, the code works fine today after having updated my browser, there must have been some problem with few resources, as it did not work even after restarting my browser.
Thank you,
With best regards,Rohan Mohammad. 

    On Wednesday, 11 May 2016 2:51 AM, Logan Tegman <notifications@github.com> wrote:
 

 I'm unable to repro this in Opera and there's nothing wrong with the markup used. My guess is that some resource (likely the bootstrap css) is not loading correctly for you and causing this error. Closing as not a site bug. Thanks and happy coding!—
