### ISSUE TITLE
************var = c **********i am having problem

### ISSUE THREAD

**Issue by Boduke217** [FreeCodeCamp/FreeCodeCamp#8546]
Challenge [Compound Assignment With Augmented Multiplication](https://www.freecodecamp.com/challenges/compound-assignment-with-augmented-multiplication) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var a = 5;
var b = 12;
var c = 4.6;

// Only modify code below this line

a *= a * 1;
b *= 0.25 * b;
c *= c * 2.18;



```

**Comment by Boduke217** [comment]
and the is not working for me and i have github accout

**Comment by raisedadead** [comment]
@Boduke217 nevertheless, please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

The issue has no description, no relevant details and a non-informative title:
> ************var = c **********i am having problem

We need information (as precise as possible) to help you out.
 
Please specify what is the issue you are facing while signing in to the [Gitter Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript)

Closing for now.
