### ISSUE TITLE
Wont let me continue even though its correct [PLEASE CLOSE]

### ISSUE THREAD

**Issue by jarydremillard** [FreeCodeCamp/FreeCodeCamp#8547]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=function%20end(str%2C%20target)%20%7B%0A%20%20var%20len%20%3D%20str.length%3B%0A%20%20var%20lent%20%3D%20target.length%3B%0A%20%20return%20str.substr(len-lent%2C%20len)%20%3D%3D%3D%20target%3B%0A%7D%0A%0Aend(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</code>.

Isn't much to produce, other then type in my code, and try to use it to pass the problem and see that it does not allow you to continue, even though it works.

My code:
```javascript
function end(str, target) {
  var len = str.length;
  var lent = target.length;
  return str.substr(len-lent, len) === target;
}

end("Bastian", "n");

```

**Comment by jarydremillard** [comment]
The function name is different from the new function name. I think FCC changed it but the function name already written doesn't change.

**Comment by jarydremillard** [comment]
PLEASE CLOSE THIS TICKET

**Comment by raisedadead** [comment]
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)
