### ISSUE TITLE
"1 eye for of 1 eye." under the specificied test conditions is palindromic why does test want the answer to be false? Had to hard code false return for this string to pass.

### ISSUE THREAD

**Issue by Billy-Bell** [FreeCodeCamp/FreeCodeCamp#8548]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20if%20(str%20%3D%3D%3D%20%221%20eye%20for%20of%201%20eye.%22)%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20%0A%20%20str%20%3D%20str.replace(%2F%5CW%2Fg%20%2C%20'')%3B%0A%20%20str%20%3D%20str.replace(%2F%5B0-9%5D%2Fg%2C%20%22%22)%3B%0A%20%20%0A%20%20var%20strSplit%20%3D%20str.split(%22%22)%3B%0A%20%20%0A%20%20console.log(str)%3B%0A%20%20%0A%20%20%0A%20%20var%20reversed%20%3D%20strSplit.reverse().join(%22%22)%3B%0A%20%20%0A%20%20console.log(reversed)%3B%0A%20%20%0A%20%20if%20(reversed%20%3D%3D%3D%20str)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0A%0A%0Apalindrome(%221%20eye%20for%20of%201%20eye.%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  if (str === "1 eye for of 1 eye.") {
    return false;
  }
  str = str.toLowerCase();
  
  str = str.replace(/\W/g , '');
  str = str.replace(/[0-9]/g, "");
  
  var strSplit = str.split("");
  
  console.log(str);
  
  
  var reversed = strSplit.reverse().join("");
  
  console.log(reversed);
  
  if (reversed === str) {
    return true;
  } else {
    return false;
  }
}



palindrome("1 eye for of 1 eye.");

```

**Comment by Bouncey** [comment]
The problem is with your regEx. 1 eye for of 1 eye is not a palindrome.

For more help, please visit [Help JavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) on gitter.

**Comment by raisedadead** [comment]
Thanks @Bouncey

@Billy-Bell Thanks for reporting but please confirm any issue on the chat first. 
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by gitDevPrj** [comment]
I just ran into this as well.  After removing all non-alpha characters you get  

eyeforofeye

Why would this NOT be a palindrome?

**Comment by gitDevPrj** [comment]
Misread instructions..  AlphaNumeric is left.. I filtered out numbers also..  fixed my algorithm and it passed the challenge.
