### ISSUE TITLE
'Spaces' should be 'white space' when concatenating strings

### ISSUE THREAD

**Issue by da-anguiano** [FreeCodeCamp/FreeCodeCamp#8555]
In order to get students familiar with computer-science vocabulary at this point in the course I think it would be beneficial to begin to refer to 'spaces' as 'white space' or 'white-space'. Most documentation for various tools and languages will talk about spaces this way. It could help clear up some confusion down the road.

**Comment by BKinahan** [comment]
At what point in the course? If you are referring to a specific challenge or group of challenges, that information is not included automatically when writing an issue.

**Comment by da-anguiano** [comment]
Sorry about that -- totally my fault.

At the point in the course where we're concatenating strings and assigning them to variables.

**Comment by raisedadead** [comment]
@da-anguiano Kindly do not ignore the [Issue Checklist](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/.github/ISSUE_TEMPLATE.md) that was presented to you while opening this issue.

**We need the challenge details that you are referring to "at this point in course".**

Additionally have you confirmed your issue with others on the [Help Chat rooms](https://gitter.im/FreeCodeCamp/Help)? Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug), to help us in helping you.

**Comment by erictleung** [comment]
@da-anguiano I don't think the different between "space" and "whitespace" is too wildly different that it'll confuse someone who hasn't seen the term "whitespace" before. 

So closing this issue because it has gone stale and I don't think we should change it. If more people find that this is confusing, we can revisit this issue. Happy coding!
