### ISSUE TITLE
Instructions ask for an array that already exists

### ISSUE THREAD

**Issue by hyperfilament** [FreeCodeCamp/FreeCodeCamp#8556]
This is semantic, but clearly communicating what's required of the user is key.

In the challenge Store Multiple Values in one Variable using JavaScript Arrays the instructions ask the student to create and array but the array is already instantiated. The students only task is to assign the already existing array a string and a number. 

The instructions should be amended or the starter code improved.

**Comment by sludge256** [comment]
Could you specify the challenge name?

**Comment by da-anguiano** [comment]
Cleared it up in the OP. Thanks.

**Comment by raisedadead** [comment]
@da-anguiano Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) before reporting issues.

Thanks and happy coding!

**Comment by sludge256** [comment]
Sorry for all the issue activity.

Do you have any proposal on how this should be re-worded?
>Create a new array called myArray that contains both a string and a number (in that order).

**Comment by erictleung** [comment]
Here's a suggestion:

> Modify the new array `myArray` so that it contains both a `string` and a `number` (in that order).

On a side note, I think the `var sandwich = ["peanut butter", "jelly", "bread"]` could be given its own line whoever takes care of this issue.
