### ISSUE TITLE
Correct answer has a syntax error. 

### ISSUE THREAD

**Issue by alkapwn3d** [FreeCodeCamp/FreeCodeCamp#8557]
Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0AtestObj%5BplayerNumber%5D%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%5B16%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

testObj[playerNumber];       // Change this Line
var player = testObj[16];   // Change this Line

```
Editor give syntax error on line 11 (testObj[playerNumber];  ) but FCC says the answer is correct. This isn't fair to people who are just learning.

**Comment by AkiraLaine** [comment]
Your code doesn't pass the challenge. In this case, your `playerNumber` variable isn't even defined. If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room. GitHub is for issues only. Happy Coding :smile:

**Comment by alkapwn3d** [comment]
Akira

The code I gave you is the code I passed with. If I passed with wrong code
then there is your issue. I don't need your damn help. I need the issue
fixed.

**Comment by AkiraLaine** [comment]
@alkapwn3d Could you attach a screenshot of passing the challenge? Also, what browser and OS are you using?

**Comment by raisedadead** [comment]
@alkapwn3d Thanks . With "All Due Respect" this is not reproducible.

![1](https://cloud.githubusercontent.com/assets/1884376/15179187/e2eb7994-1797-11e6-84d7-45f55133f963.png)

P.S : 
Here is a [code of conduct](https://www.freecodecamp.com/code-of-conduct), I am sure you could use it.

Good luck!
