### ISSUE TITLE
Test case in Profile Lookup. Sherlock, likes prints to console but does not pass

### ISSUE THREAD

**Issue by siriusblueus** [FreeCodeCamp/FreeCodeCamp#8559]
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup#?solution=%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intruiging%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%2C%0A%5D%3B%0A%0A%0Afunction%20lookUpProfile(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20a%20%3D%20-1%3B%0Afor(var%20i%20%3D%200%20%3B%20i%20%3C%3D%203%20%3B%20i%2B%2B)%0A%20%20%7B%0A%20%20%20%20if(contacts%5Bi%5D.firstName%20%3D%3D%3D%20firstName)%0A%20%20%20%20%20a%20%3D%20i%3B%0A%20%20%7D%0A%0A%20%20if(a%20!%3D%20-1)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20if(contacts%5Ba%5D.hasOwnProperty(prop))%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20contacts%5Ba%5D%5Bprop%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%7D%0A%20%20else%0A%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUpProfile(%22Kristian%22%2C%20%22lastName%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intruiging Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    },
];


function lookUpProfile(firstName, prop){
// Only change code below this line
  var a = -1;
for(var i = 0 ; i <= 3 ; i++)
  {
    if(contacts[i].firstName === firstName)
     a = i;
  }

  if(a != -1)
    {
        if(contacts[a].hasOwnProperty(prop))
          {
          return contacts[a][prop];
          }
        else
          return "No such property";
    }
  else
    return "No such contact";


// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Sherlock", "likes");
```

**Comment by AkiraLaine** [comment]
Hey @siriusblueus. You changed `Intriguing Cases` to `Intruiging Case`. That's why the test doesn't pass. Happy Coding :smile:

**Comment by Shraddha99** [comment]
@siriusblueus that code worked for me , urs was simple n nice algo .     but I wrote it this way :                                                  
function lookUpProfile(firstName, prop){

  for(i=0; i<= contacts[i].length; i++)
    {
      if(contacts[i].firstName === firstName)
        {
          if(contacts.firstName[i].prop == prop)
            {
              return contacts[i].prop;
            }
        }
      else if (contacts[i].firstName !== firstName)
      {
          return "No such contact";
      }
      else if(contacts[i].prop != prop)
        {
          return "No such Property";
        }
    }

n it didn't worked . could u please point out whr m I making mistake?
