### ISSUE TITLE
bad ending 'comment out' syntax resulted in completion of waypoint

### ISSUE THREAD

**Issue by Kesb4Aspire** [FreeCodeCamp/freecodecamp#856]
![screenshot 4](https://cloud.githubusercontent.com/assets/12790960/8027742/d1fc5be4-0d6b-11e5-8655-b821e513de34.png)

Challenge http://www.freecodecamp.com/challenges/waypoint-comment-out-html has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by QuincyLarson** [comment]
Thank you for submitting this issue. We've fixed it.
