### ISSUE TITLE
"++" operator not recognized in pre-increment position, (++myVar)

### ISSUE THREAD

**Issue by dmm10** [FreeCodeCamp/FreeCodeCamp#8561]
#### Challenge Name

https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%2B%2B%3B%0A%0A

#### Issue Description

The test:
  Use the ++ operator
fails when the pre-increment version of the "++" operator is used (i.e. "++myVar;") rather than the post-increment version.  Nothing in the description of the task precludes the pre-increment version being correct.

#### Browser Information

* Browser Name, Version: various
* Operating System: various
* Mobile, Desktop, or Tablet: multiple

#### Your Code

```js
// If relevant, paste all of your challenge code in here
var myVar = 87;

// Only change code below this line
++myVar;


```

#### Screenshot

![screen shot 2016-05-11 at 12 16 47 am](https://cloud.githubusercontent.com/assets/1255054/15169830/91fb4102-170d-11e6-8a45-f9ca6faf1457.png)

**Comment by erictleung** [comment]
@dmm10 thanks for the issue. Because we're targeting beginner coders, we wanted the challenges to be simple enough to teach a concept but not overwhelm learners with other details. Same goes for #8562.

cc/ @FreeCodeCamp/issue-moderators worth accepting this prefix operation?

**Comment by raisedadead** [comment]
I remember this was [discussed earlier](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7611#issuecomment-200573519) and more times in the chat, we could add separate challenges for pre/post increments/decrements.

But this is going to be confusing for beginners. Maybe we could relax the tests to allow `pre` but not change the test case message.

So advanced campers who are attempting these as in this case can pass the challenge and beginners are not overwhelmed as well.

**Comment by erictleung** [comment]
@raisedadead I agree on just accepting the answer for flexibility but not change the test messages.

I think editing [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L456) to the following will work. I'm not sure about escaping the parentheses but whoever takes this will have to check this.

```
assert(/([+]{2})?\\s*myVar\\s*([+]{2})?/.test(code) 
```

The code will break for `++myVar++` anyways so I think the above should be okay.

**Comment by SaintPeter** [comment]
@erictleung Won't the above code pass with just `myVar`?   Since both `++` sections are optional, that will match just `myVar`.

Better to do:
`/([+]{2}\s*myVar|myVar\s*[+]{2}/`

**Comment by erictleung** [comment]
@SaintPeter good point. I was being careless 😄  Thanks!

**Comment by dmm10** [comment]
Thanks ya’ll!  I couldn’t have asked for a better outcome.

Having poked your backend with alternate ‘correct' solutions to prior challenges and been impressed with your robust handling of them this situation stuck out a bit.  And I was hoping to contribute to the polish of your beautiful project.

I appreciate the peak behind the curtain.  It confirmed that the modification only required a simple regex edit and that ya’ll really are a copacetic group.

Kudos all around!

**Comment by BariqFitri** [comment]
var myVar = 11;

// Only change code below this line
myVar--;
