### ISSUE TITLE
"--" operator not recognized in pre-decrement position, (--myVar;.)

### ISSUE THREAD

**Issue by dmm10** [FreeCodeCamp/FreeCodeCamp#8562]
#### Challenge Name

https://www.freecodecamp.com/challenges/decrement-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2011%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A--myVar%3B%0A%0A

#### Issue Description

Use "--myVar" rather than "myVar--;" in the solution to reproduce the error.

#### Browser Information

* Browser Name, Version: *
* Operating System: *
* Mobile, Desktop, or Tablet: *

#### Your Code

```js
// If relevant, paste all of your challenge code in here
var myVar = 11;

// Only change code below this line
--myVar;
```

#### Screenshot

![screen shot 2016-05-11 at 12 24 36 am](https://cloud.githubusercontent.com/assets/1255054/15169972/23c6798e-170f-11e6-9806-9d43f98df13d.png)

**Comment by erictleung** [comment]
People wanting to fix this see [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8561#issuecomment-218467713).
