### ISSUE TITLE
grammatical error in description 

### ISSUE THREAD

**Issue by dmm10** [FreeCodeCamp/FreeCodeCamp#8563]
#### Challenge Name

https://www.freecodecamp.com/challenges/manipulate-arrays-with-push#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.push(%5B%22happy%22%2C%20%22joy%22%5D)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%2C%20%5B%22happy%22%2C%20%22joy%22%5D%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray.push(%5B%22dog%22%2C%203%5D)%3B%0A%0A

#### Issue Description

"takes one or more parameter "  should read
"takes one or more parameters " 

#### Browser Information

* Browser Name, Version: *
* Operating System: *
* Mobile, Desktop, or Tablet: *

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by raisedadead** [comment]
@dmm10 Thanks for reporting this.

To contributors (First timers only :wink: ) : 
Change this [line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1799) to reflect:

> .push() takes one or more parameter**s** and "pushes" it onto the end of the array.

**Comment by akshatbahety** [comment]
I am completely new to this i saw the label first-timers
 hence how can I help?

**Comment by raisedadead** [comment]
@akshatbahety:

1. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

2. As I mentioned in my comment above, you have to [change this line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1799).
> .push() takes one or more parameter**s** and "pushes" them onto the end of the array.

3. If you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).
