### ISSUE TITLE
pal

### ISSUE THREAD

**Issue by KrisGeyer** [FreeCodeCamp/FreeCodeCamp#8566]
#### Challenge Name

Check for Palindrom

#### Issue Description

All other aspects have been passed. The final milestone of this challenge is proving to be difficult "0_0 (: /-\ :) 0-0". I believe my code satisfies the requirements but there is difficulty for my browser to understand this section: "/-\". If I try it with code that is "/-\\" it returns true for detection of a palindrome, so I think that this is the source of the problem.

Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function palindrome(str) {
str = str.replace(/\s/g,'');
str = str.replace(/\,/g, '');
str = str.replace(/\./g, '');
str = str.replace(/\-/g, '_');
str = str.replace(/\(/g,")");
str = str.replace(/\\/g, "/");
str = str.toLowerCase();
var reverseStr = str.split('').reverse().join('');   
  if (reverseStr === str){
    return true;
  }
  else {
    
    return false;
  }
 }

palindrome("0_0 (: /-\ :) 0-0");
```

**Comment by raisedadead** [comment]
@KrisGeyer Thanks for the issue, but this last test case is a intentionally tricky but is valid.

Also, your code is not completely correct. You are close though.

GitHub Issues are for reporting bugs on the website only.
Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!
