### ISSUE TITLE
Instruction or objective is wrong in the question

### ISSUE THREAD

**Issue by swapy** [FreeCodeCamp/FreeCodeCamp#8567]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Afunction%20testLogicalOr(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%3E%3D10%20%7C%7C%20val%3C%3D20)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(15)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line

  if (val>=10 || val<=20) {
    return "Outside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(15);

```

Combine the two if statements into one statement which returns "Outside" if val is not between 10 and 20, inclusive. Otherwise, return "Inside".

Either instruction is wrong here or objective is wrong
How can you you check **between** condition with || operator? I think there is some bug.

**Comment by raisedadead** [comment]
@swapy Thanks for the issue, but this is not a bug with the challenge. The `||` can be used to check the between condition.

I am tempted to give you a hint 
`if (val>=10 || val<=20)` translate this into pure English and maybe you will get what's wrong

> If `val` is greater than/equal to `10` **OR** if `val`is lesser than/equal to 20

Something similar like union of sets? 

Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy coding!

**Comment by milpool** [comment]
my code is right but. I have checked each number individually and got the correct answer but it will not show as being correct for the challenge

**Comment by milpool** [comment]
here is where some of the bug problems are coming from. It is like this for a number of the questions in this section. 

This is what I get to start with. If you notice the function name is myTest and it instructs to only change code below this line. However for validating it is looking for the function "testLogicalAnd"

 function myTest(val) {
  // Only change code below this line

  if (val <= 50 && val >=25) {
    
      return "Yes";
    
  }

  // Only change code above this line
  return "No";
}

// Change this value to test
myTest(10);

There for even though I put in the code correct it will not actually call it correct until I change function name from myTest to testLogicAnd. However it said not to change the name myTest. There is similar problems with each one of the comparison questions.

**Comment by raisedadead** [comment]
@milpool Can you raise a separate issue with details and screenshots.

**Comment by milpool** [comment]
since I have changed all of them I cant give you a screenshot with the error.
