### ISSUE TITLE
Escape Sequences in Strings - Exercise Bug?

### ISSUE THREAD

**Issue by Narduril** [FreeCodeCamp/FreeCodeCamp#8569]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22%5C%5C%20backslash%20%5C%5C%20%5Ct%20tab%20%5Ct%20%5Ct%20tab%20%5Ct%20%5Cr%20carriage-return%20%5Cr%20%5Cn%20new-line%5Cn%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "\\ backslash \\ \t tab \t \t tab \t \r carriage-return \r \n new-line\n";



```

Hi,

I have a problem with this exercise. I've wrote this code in code editor:

"\\ backslash \\ \t tab \t \t tab \t \r carriage-return \r \n new-line\n";

This code should solve the exercise but, when i use virtual machine it appears like this: 

"\\ backslash \\ \t tab \t \t tab \t \r carriage-return \r \n new-line\n";

I don't understand what i'm doing wrong, i think it's a bug. Can you help me?

**Comment by erictleung** [comment]
@Narduril thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: you solution should only have backslashes and characters, no words. Happy coding!
