### ISSUE TITLE
Bonfire Falsey Bouncer

### ISSUE THREAD

**Issue by ekojsalim** [FreeCodeCamp/freecodecamp#857]
```
var arr = [7, 'ate', '', false, 9];
function bouncer(arr) {
  return arr;
}

bouncer(arr);
```

This (obviously wrong) code give the bonfire all green checkmarks but the prompts does not show up. 
(Visual bug?)

**Comment by BerkeleyTrue** [comment]
@ekojsalim Thanks!

Looks like you have found a flaw in the framework we built to run the test. 

@terakilobyte Should now how to diagnose this.

**Comment by BerkeleyTrue** [comment]
cc @terakilobyte 
![bonfire__falsey_bouncer___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/8068599/ba247e40-0ea9-11e5-9a43-ae09bfd7b0cd.png)

**Comment by terakilobyte** [comment]
Commit 870c80d72da31bbd1f234f6629c55e23eefdaea4 resolves this issue.
