### ISSUE TITLE
Remainder challenge needs numbers directly used in modulo

### ISSUE THREAD

**Issue by ashekgo** [FreeCodeCamp/FreeCodeCamp#8570]
Challenge [Finding a Remainder in JavaScript](https://www.freecodecamp.com/challenges/finding-a-remainder-in-javascript#?solution=%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20a%3D11%3B%0Avar%20b%3D3%3B%0Avar%20remainder%3B%0Avar%20remainder%3Da%20%25%20b%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Only change code below this line
var a=11;
var b=3;
var remainder;
var remainder=a % b;
```

**Comment by erictleung** [comment]
@ashekgo thanks for the issue. Your answer will give the correct answer, but because our site is directed to beginner coders, this challenge is more simple than you think. The challenge simply wants you to take the remainder directly `remainder = 11 % 3`.

cc/ @FreeCodeCamp/issue-moderators worth changing? I was thinking we modify the `You should use the % operator` test to just look for the modulo character. Then we add another test that uses the current test looking for the modolo character to look for the use of two numbers directly with the modulo symbol.

```
/\d+\s*%\s*\d+/.test(code)
```

**Comment by pranayberry** [comment]
@erictleung Or we can only check for the use of modulo and the value of the remainder variable so that users can complete the challenge either by using variables or using numbers.

**Comment by erictleung** [comment]
@pranayberry that sounds good to me. Just looking for the modulo character so something like this might help.

```json
...
"assert(/%/.test(code), 'message: You should use the <code>%</code> operator');"
...
```

**Comment by pranayberry** [comment]
@erictleung I used the following test locally.
`assert(/.*%.*/.test(code), 'message: You should use the <code>%</code> operator');`

**Comment by erictleung** [comment]
@pranayberry not really. Mine *just* looks for the remainder operator. Yours looks for the remainder operator and stuff being around it.

But to make it more explicit, it might be good to look for the correct use of the remainder operator with something like this:

```
assert(/var\\s*?remainder\\s*?=\\s*?.*%.*;/.test(code), 'message: You should use the <code>%</code> operator');
```

**Comment by pranayberry** [comment]
@erictleung Tested and working absolutely fine. Will submit the PR. :+1:

**Comment by yuens1002** [comment]
for this challenge, i entered 
```
remainder = 11 % 3;
```
as my solution and got "You should use the % operator" error.  can you confirm?

**Comment by erictleung** [comment]
@yuens1002 you need a `var` in front.

**Comment by yuens1002** [comment]
It is already declared from the line above

**Comment by erictleung** [comment]
@yuens1002 mmm I see. We changed the test recently to look for `var remainder = ...`. However, as long as the `remainder = ...%...` is there, it should be correct.

For anyone wanting to fix this, [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L646) should be changed to:

```
"assert(/remainder\\s*?=\\s*?.*%.*;/.test(code), 'message: You should use the <code>%</code> operator');"
```

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by yuens1002** [comment]
Best to check if the variable remainder has been declared elsewhere or not
have the variable remainder be declared by default.
