### ISSUE TITLE
Inherit Styles from the Body Element

### ISSUE THREAD

**Issue by abinayams1010** [FreeCodeCamp/FreeCodeCamp#8572]
Challenge [Inherit Styles from the Body Element](https://www.freecodecamp.com/challenges/inherit-styles-from-the-body-element#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3D%22green%22%3B%0A%20%20%7D%0A%0A%3C%2Fstyle%3E%0A%3Ch1%3Ehello%20world%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color="green";
  }

</style>
<h1>hello world</h1>
```

**Comment by theflametrooper** [comment]
@abinayams1010 Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by tsinootrac** [comment]
`body {
background-color: green;
color: green;
}`
read carefully & slow
i had the same problem but i read it again 
to figure out it's my mistake
