### ISSUE TITLE
Prioritize One Style Over Another

### ISSUE THREAD

**Issue by abinayams1010** [FreeCodeCamp/FreeCodeCamp#8573]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: pink;
  }
</style>
<h1>Hello World!</h1>

```

**Comment by BerkeleyTrue** [comment]
Please describe the steps to reproduce the issue.

Happy Coding!

**Comment by theflametrooper** [comment]
Please check the following tests:
`Your h1 element should have the class pink-text.`
`Your <style> should have a pink-text CSS class with its color set to pink.`

Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help in future. Happy Coding!
