### ISSUE TITLE
Instructions Incorrect - Write Reusable JavaScript with Functions

### ISSUE THREAD

**Issue by fearofshorts** [FreeCodeCamp/FreeCodeCamp#8577]
Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20reusableFunction()%20%7B%0A%20%20console.log(%22Hi%20World%22)%3B%0A%7D%0A%0AreusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The instructions tell you to

1. Create a function called reusableFunction which prints "Hi World" to the dev console.
2. Call the function.

But the code provided has already created this function and called it above the "Only change code below this line" comment line. AFAIK, you can't redefine a function in JavaScript, so the only solution I can see was to modify the function (against instruction).

My code:
```javascript

// Example
function reusableFunction() {
  console.log("Heyya, World");
}

reusableFunction();

// Only change code below this line



```

**Comment by AkiraLaine** [comment]
Hey @fearofshorts! Yes, the starter code or the instructions need to be changed.

Thanks for pointing this out.

**Comment by erictleung** [comment]
Closing in favor of #8551.
