### ISSUE TITLE
Font size issue in Safari

### ISSUE THREAD

**Issue by leytzher** [FreeCodeCamp/freecodecamp#858]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The problem ask to change the font size of 2 p sections to 16px:
My code is:
![waypoint__change_the_font_size_of_an_element___free_code_camp](https://cloud.githubusercontent.com/assets/830054/8036708/2509dd5a-0e2c-11e5-9e52-929eb6874f24.jpg)

This code changes the font size of both p elements to 16px but the code is flag as invalid by the evaluator.
![errormsg](https://cloud.githubusercontent.com/assets/830054/8036710/2596af6e-0e2c-11e5-8dac-64af3fea7a59.jpg)

My browser is Safari.

**Comment by leytzher** [comment]
Update:
I tried in Chrome and the code works.
Apparently the issue happens with Safari.

**Comment by treece** [comment]
I'm unable to reproduce your issue on in my Safari. What version of Safari do you have? Just curious. Also, do you have any extensions running? If so, try turning them off or open a private window and retry your code and see if that works. Thanks.

**Comment by BerkeleyTrue** [comment]
Also works for me in safari.

**Comment by leytzher** [comment]
My Safari is Version 8.0.6 (10600.6.2).
I tried again today and now is working.
I think we can close this issue.
