### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by KarmaComaa** [FreeCodeCamp/FreeCodeCamp#8580]
Challenge [Condense arrays with reduce](https://www.freecodecamp.com/challenges/condense-arrays-with-reduce#?solution=%0Avar%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0Avar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AsingleVal%20%3D%20array.reduce(function(sum%2C%20current)%7B%0A%20%20return%20sum%20%2B%20current%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var array = [4,5,6,7,8];
var singleVal = 0;

// Only change code below this line.

singleVal = array.reduce(function(sum, current){
  return sum + current;
});

```

**Comment by theflametrooper** [comment]
@KarmaComaa This code seems to pass fine? What error are you having exactly?

**Comment by KarmaComaa** [comment]
It does not count as a covered job.

2016-05-12 17:35 GMT+06:00 Jonathan <notifications@github.com>:

**Comment by erictleung** [comment]
@KarmaComaa can you elaborate on what makes it not a covered job? Your code does exactly what the challenge asks for.

**Comment by erictleung** [comment]
@KarmaComaa closing as stale. If you can elaborate on why your code isn't a covered job, we can revisit this issue. Happy coding!
