### ISSUE TITLE
css style selector

### ISSUE THREAD

**Issue by gideonknight** [FreeCodeCamp/FreeCodeCamp#8581]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0Ah2%20(color%3A%20blue%3B)CatPhotoApp%0A%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:29.0) Gecko/20100101 Firefox/29.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
h2 (color: blue;)CatPhotoApp
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
