### ISSUE TITLE
Incorrect link to the Falsy Bouncer challenge on camper profile page

### ISSUE THREAD

**Issue by oharrison** [FreeCodeCamp/FreeCodeCamp#8582]
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=%0Afunction%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don%27t%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20return%20arr%3B%0A%7D%0A%0Abouncer(%5B1%2C%20null%2C%20NaN%2C%202%2C%20undefined%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

1 - Here is a screenshot of the page that shows all the camper's challenges, completion dates, and the link to there most recent submission.
![1_show_all_challeges_page](https://cloud.githubusercontent.com/assets/10459779/15215721/e9d33c6c-1821-11e6-86da-fb42e57d6ed1.png)

2 - Here is what happens when I click the View Solution link for the _Falsey_ Bouncer challenge. I get redirect to the map page with a message saying "We couldn't find a challenge with the name _Falsey_ Bouncer. Please double check the name."
![2_redirect_to_map_with_flash_on_click_challenge](https://cloud.githubusercontent.com/assets/10459779/15215743/1284e480-1822-11e6-9424-da555e6f8750.png)

3 - The challenge does exist, but under a different name as shown by the screenshot below. 
![3_challenge_exists_under_a_different_name](https://cloud.githubusercontent.com/assets/10459779/15215968/0bdac342-1823-11e6-8e86-7a0e561cb484.png)

You can see from the above image that the url being used for the challenge is [freecodecamp.com/challenges/falsy-bouncer](freecodecamp.com/challenges/falsy-bouncer). But, the href value being used as the link in the show all challenges page is using "/challenges/Falsey Bouncer". See image below.
![4_wrong_url](https://cloud.githubusercontent.com/assets/10459779/15216763/7b6a5cc4-1826-11e6-9596-90f07543bbd1.png)

If I adjust the href attribute of the View Solution link in the show all challenges page to use "/challenges/falsy-bouncer" then I get the expected result of sending me to the challenge when I click the link. 

Also, the name of the challenge as displayed on the show all challenges page (from image 1) is not the consistent name of the challenge. _Flasey_ vs _Falsy_ (consistent with no 'e').

This issue could be revealing that the challenge names and the View Solution links are not being completely dynamically generated.

**Comment by DanStockham** [comment]
I'm wondering if whatever is holding the href value on the controller end has a typo?

**Comment by erictleung** [comment]
@oharrison I can't seem to reproduce your problem. I'm on your page and it is spelled correctly for me. Is it still a problem for you?

![image](https://cloud.githubusercontent.com/assets/2754821/15219264/f4714560-1817-11e6-92d1-b21595d5b565.png)

I think a stranger thing is the number of missing challenge names, but they might be from past challenges that are now removed.

![image](https://cloud.githubusercontent.com/assets/2754821/15219336/38cd3f70-1818-11e6-8c9f-1c1327e5872b.png)

**Comment by raisedadead** [comment]
@oharrison 
This is a known issue, if a challenge was updates, renamed or removed, then the link would exist on the profile, in case the challenge was completed on prior date.

But when you visit the renamed challenge and submit it, the challenge would get updated on the profile with correct details.

Now, if you are visiting any other camper's profile, visiting the challenge would result as expected and reported by you. This can be updated only when the camper themselves visit the challenge and re-submit them.

**Comment by oharrison** [comment]
@erictleung @raisedadead Since creating this issue, I have re-summited the challenge, and the issue no longer exists. 

@erictleung I was thinking creating a separate issue for the missing challenge names, which is why I didn't mention them here.

**Comment by raisedadead** [comment]
@oharrison yes as I mentioned this is the expected behavior. 

Unless the camper themselves re-submitted the challenges their profile would always keep showing the older challenges, I am guessing in this case from last year.

We would never change the profile of a camper from our side, as a protocol, the camper only have the options to re-submit and update their profile or leave them as they are.

**Comment by raisedadead** [comment]
If you are okay with analogy, would you please confirm so that this issue may be closed.

**Comment by oharrison** [comment]
Yes, I am okay with the analogy.
