### ISSUE TITLE
Video Challenges - immediately goes to questions

### ISSUE THREAD

**Issue by SandraFlato** [FreeCodeCamp/FreeCodeCamp#8583]
#### Challenge Name

Video Challenges

#### Issue Description

They now record completion, however, I liked it better when I chose when I wanted to go to the questions.  Now it automatically brings up the questions when the video finishes.  That means I can't read over the notes below the video after the video.  I have to read and understand them before I watch the video or have to exit out and start the challenge again.  I liked the old way better.

**Comment by theflametrooper** [comment]
cc/ @FreeCodeCamp/issue-moderators Should this be changed, or was this feature implemented on purpose?

**Comment by BerkeleyTrue** [comment]
This was recently implemented recently. It can be removed.

**Comment by RayBB** [comment]
A good middle ground may be to have a toggle or account setting to allow the user to decide if it automatically goes to the question.

**Comment by atjonathan** [comment]
@RayBB I don't think it's worth adding this feature, as you can very simply start the questions.

**Comment by SandraFlato** [comment]
Still finding the automatic feature frustrating.  I have to answer the questions, exit out and then go back in to read the comments if I have questions or there is a link that I need to follow.

**Comment by atjonathan** [comment]
@SandraFlato #8840 will fix this when it's merged and pushed to `master` :tada:

**Comment by SandraFlato** [comment]
Thank you!  Sorry to be high maintenance!
