### ISSUE TITLE
Challenge: Mutations - tests return correct boolean but no tests will pass

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#8584]
Challenge [Mutations](https://www.freecodecamp.com/challenges/mutations#?solution=%2F*%20jshint%20asi%3Atrue%2C%20esversion%3A6%2C%20strict%3Aimplied%20*%2F%0A%0Alet%20mutation%20%3D%20(arr)%20%3D%3E%0A%20%20arr.map((word)%20%3D%3E%20word.toLowerCase())%0A%20%20%20%20%20.reduce((control%2C%20test)%20%3D%3E%0A%20%20%20%20%20%20%20Array.from(test).every((letter)%20%3D%3E%20control.includes(letter)))%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

All tests will return the correct boolean, but none of the tests will pass.

My code:
```javascript
/* jshint asi:true, esversion:6, strict:implied */

let mutation = (arr) =>
  arr.map((word) => word.toLowerCase())
     .reduce((control, test) =>
       Array.from(test).every((letter) => control.includes(letter)))

mutation(["hello", "hey"])
```

**Comment by erictleung** [comment]
@0x0936 I can't seem to reproduce your errors. Your code works fine for me and passes all the tests.

**Comment by 0x0936** [comment]
Thanks for looking at it @erictleung - all tests are passing now and not sure why they weren't before. Closing issue.
