### ISSUE TITLE
Use Bracket Notation to Find the First Character in a String

### ISSUE THREAD

**Issue by cowanjt** [FreeCodeCamp/FreeCodeCamp#8586]
Use Bracket Notation to Find the First Character in a String

https://www.freecodecamp.com/challenges/use-bracket-notation-to-find-the-first-character-in-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstLetterOfFirstName%20%3D%20%22%22%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstLetterOfFirstName%20%3D%20firstName%5B0%5D%3B%0A%0A%2F%2F%20Setup%0Avar%20firstLetterOfLastName%20%3D%20%22%22%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AfirstLetterOfLastName%20%3D%20lastName%5BlastName.length%20-%20lastName.length%5D%3B%0A%0A

Based on the criterion of the challenge and while not the most concise, this should be an acceptable answer...

```
firstLetterOfLastName = lastName[lastName.length - lastName.length];
```

* Browser Name, Version: Chrome, Version 50.0.2661.94 m
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop, but replicated on mobile device

![image](https://cloud.githubusercontent.com/assets/19294607/15228650/6ffff640-184a-11e6-91e3-22f7382d50ec.png)

**Comment by dhcodes** [comment]
I'm too newb to know exactly how the test cases are written, but wouldn't one then need to write test cases for anything that equals zero? ex. firstLetterOfLastName = lastName[Math.PI - Math.PI]

**Comment by jenish2014** [comment]
I looked through the code and found this, 
"assert(code.match(/firstLetterOfLastName\\s*=\\s*lastName\\s*\\[\\s*\\d+\\s*\\]/), 'message: You should use bracket notation.');"  

This piece of code uses Regular-expression "\d+" to determine the value passed with-in the bracket, but instead gets an expression which results in above error.

**Comment by erictleung** [comment]
@FreeCodeCamp/issue-moderators should relax the regex on the "You should use bracket notation" test so it'll accept anything within the brackets? Something like below.

```
/firstLetterOfLastName\s*?=\s*?lastName\[.*?\]/
```

**Comment by ltegman** [comment]
I like changing it. We're already making sure the variable contains the right value, so enforcing a specific thing in the brackets doesn't seem helpful.

**Comment by BariqFitri** [comment]
I have done it
![tuto6](https://cloud.githubusercontent.com/assets/21375993/18341530/f2c3c332-75dc-11e6-92aa-8d4ccc36be33.PNG)
