### ISSUE TITLE
Quoting Strings with Single Quotes

### ISSUE THREAD

**Issue by 9wilson6** [FreeCodeCamp/FreeCodeCamp#8587]
"Only remove the backslashes " \" used to escape quotes"
even after having them all corrected it still wunt mark it right

**Comment by raisedadead** [comment]
Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Have you confirmed this behavior in the [JavaScript Chat Room(https://gitter.im/FreeCodeCamp/HelpJavaScript)?

**Comment by erictleung** [comment]
@9wilson6 closing as stale. Feel free to comment if you have any updates. Happy coding!

**Comment by yuens1002** [comment]
i can confirm that this answer

```
var myStr ='<a href="http://www.example.com" target="_blank">Link</a>'
```

will result in in a console.log of

```
"<a href=\"http://www.example.com\" target=\"_blank\">Link</a>"
```

interestingly, if i did

```
var myStr ="<a href='http://www.example.com' target='_blank'>Link</a>"
```

console.log results in

```
var myStr ="<a href='http://www.example.com' target='_blank'>Link</a>"
```

therefore, i single and double quotes are on longer functionally the same in js?
