### ISSUE TITLE
Reverse a String issue

### ISSUE THREAD

**Issue by martinhesko** [FreeCodeCamp/FreeCodeCamp#8588]
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#?solution=%0Afunction%20reverseString(str)%20%7B%0Astr%20%3D%20str.split(%22%22).reverse().join(%22%22)%3B%0A%20%20return%20str%3B%0A%7D%0A%0AreverseString(%22hello%22)%3B%0A) has an issue.

There is literally a tutorial a the bottom of a page on [string.split()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split) on how to do it

You should probably find other resource that doesn't hand out the sollution to the students, even though it's really easy

**Comment by raisedadead** [comment]
@martinhesko Thanks a lot for reporting this.

This has been debated before, we sure can remove this link, but then someone will come up and log a issue to add it back.

Point is MDN is just a Google Search away. If someone wants to go ahead and copy paste a solution, that is not going to strengthen their skill. But, If they copy paste while understanding it, there is no harm as well.

So its not about handing out solutions, this challenge does need people to be aware of the available API's

Having said that to earn a certification, they have to solve actual projects and much tougher challenges and algorithms where the skills learnt here would be required.

So, IMHO the campers are well aware that they cannot fluke through everything.

I would prefer as debated in past to let these links stay.

Keeping this open for discussion.

**Comment by erictleung** [comment]
@martinhesko I agree with @raisedadead. In more real programming challenges you'll face, you would rely on Google for some help. So I'm okay with letting the link stay. Plus, it is the first of the Basic Algorithm Scripting challenges.

**Comment by raisedadead** [comment]
@martinhesko Thanks again, closing this but feel free to continue on the discussion. We would love any alternates that you may have in mind.
