### ISSUE TITLE
Hard coded language when linking to wiki

### ISSUE THREAD

**Issue by vcooley** [FreeCodeCamp/FreeCodeCamp#8591]
In pull #8373 a new feature is introduced to link the user to the wiki page for the current challenge that they are on. Currently the language for the wiki challenge page is hard coded to prevent 404s. As there is no way to check on the contents of the iframe after loading it, a fix to this problem likely needs to be implemented on the wiki's side. 

The preferable behavior would be to try to open the page in the user's language, if it's not available fallback and redirect to the english page for the challenge, and finally, if that's not available, link to the wiki's homepage in the user's own language.

**Comment by BerkeleyTrue** [comment]
Unfortunately, static pages don't work like that. You can't have automatic pages. If it's not there you get a 404 page.

**Comment by raisedadead** [comment]
So to tackle this we would need some form of API that fetches the article from GitHub hosted pages, and render it within the iframe of the wiki sidebar?

That's going to hit the performance quite a bit.

**Comment by BerkeleyTrue** [comment]
@raisedadead We should take the same approach we will take with languages on the main site, support for those will come when they are close to completed.

For the wiki we can define this as having every wiki article for the challenges translated into a language.  We can reduce the burden for this by not requiring the entire article to be translated, but at least some minimum amount must be supplied. This increases usability without require tons of logic that for now will mostly return false.

**Comment by vcooley** [comment]
Could/should those articles be automatically generated with scripts to
redirect (or even just links) to the complete English version of the
article?

**Comment by BerkeleyTrue** [comment]
We want them to be translated (or at least created) by humans who speak the language. It will create a better translation and drive engagement and ownership.

This might also be a great place for someone new to github to create their first PR!

**Comment by vcooley** [comment]
Absolutely. That makes a lot of sense.

**Comment by raisedadead** [comment]
No longer relevant. Closing.
