### ISSUE TITLE
Filter Arrays with .filter - Incorrect test

### ISSUE THREAD

**Issue by vamsikumarg** [FreeCodeCamp/FreeCodeCamp#8594]
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%20%7B%0A%20%20return%20val%3C%3D5%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
  return val<=5;
});

```
The following test should be reworded 
from 
You should have filtered out all values from the array that are greater than 5.
to
You should have filtered out all values from the array that are less than or equal to 5.

**Comment by erictleung** [comment]
@vamsikumarg if we changed the wording on the test, it would then conflict with the instructions.

> Use filter to create a new array with **all the values** from `oldArray` which are **less than 6**.

Closing as there is no bug. Happy coding!

**Comment by vamsikumarg** [comment]
The test is failing if the filter is set to
`return val>5;`
and succeeds if the filter is set to 
`return val<=5;`
which is incorrect and should be fixed.

**Comment by vamsikumarg** [comment]
Thanks @erictleung ... late night coding, misread the test.
