### ISSUE TITLE
Line break needs to be removed in Filter Challenge

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8595]
#### Challenge Name

https://www.freecodecamp.com/challenges/filter-arrays-with-filter

#### Issue Description

The `<br>` needs to be removed from [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L400).

The change should give you:

```
... which are less than 6. The <code>oldArray</code> should not change."
```

So it should end up looking like this:

![image](https://cloud.githubusercontent.com/assets/2754821/15235012/a31ba1ba-186c-11e6-87aa-c77d968d4856.png)

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/15234933/e57349a6-186b-11e6-95cb-6fccee645ec0.png)

**Comment by DrLeeroyPhD** [comment]
Fix made, but am unable to push, pull request required.

**Comment by erictleung** [comment]
@DrLeeroyPhD if you need help contributing, please read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) first. Also, don't hesitate to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions about helping. Good luck!

**Comment by DrLeeroyPhD** [comment]
Ah, great! Thank you very much for your reply. I'd like to make this fix.

**Comment by Maritimesailor** [comment]
Is this bug still open to fix?

**Comment by theflametrooper** [comment]
@Maritimesailor #8595 addresses this issue!

Checkout our other `first-timers-only` issues here: https://github.com/FreeCodeCamp/FreeCodeCamp/labels/first-timers-only.

**Comment by c0906969479** [comment]
2016/5/15 23:58於 "Jonathan" <notifications@github.com>寫道：

**Comment by raisedadead** [comment]
@c0906969479 

Hello!

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Comment by radoslaw-gajos** [comment]
Is this issue still relevant? I'm new here so I wonder should I wait for another 'first-timers-only' issue, contribute to this one or find another issue without that tag? I'm new to github in general, if someone could answer me this questions I'd be very grateful.

**Comment by theflametrooper** [comment]
@radoslaw-gajos Please see my [above](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8595#issuecomment-219293849) comment. Happy Coding!

**Comment by radoslaw-gajos** [comment]
@theflametrooper Thanks, there's no other first-timers-only issues, or at least I don't see any, so I'll wait untill a new one appears.

**Comment by theflametrooper** [comment]
@radoslaw-gajos Awesome!

**Comment by raisedadead** [comment]
@radoslaw-gajos this one is open again!

**Comment by jaydenwindle** [comment]
Since this is open again, I'd like to take a crack at it.

**Comment by atjonathan** [comment]
@jaydenwindle Cool!

Assigning @jaydenwindle to this issue.
