### ISSUE TITLE
Improve email unsubscription usability

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8597]
- [ ] We should send a notification confirming that a user has been unsubscribed. This email should contains a link back to their email settings in case they decide to resubscribe.
- [ ] Instead of passing the campers' email as plaintext parameter to the unsubscribe path, we should somehow encode it. This will prevent people from maliciously unsubscribing one another.

**Comment by BerkeleyTrue** [comment]
1. I don't see this as being an improvement, The reason they are hitting the unsubscribe endpoint is to stop receiving emails. 

We should do 2.

**Comment by raisedadead** [comment]
Agreed with @BerkeleyTrue for point one.

**Comment by Maritimesailor** [comment]
How will it prevent people from maliciously unsubscribing one another?

**Comment by avirajkhare00** [comment]
I agree with @quincylarson

**Comment by RayBB** [comment]
I also agree with @quincylarson about the changes. The unsubscribe notification is something that I would prefer as I have accidentally unsubscribed from things before.

**Comment by avirajkhare00** [comment]
@raybb @quincylarson let's implement this feature.

**Comment by raisedadead** [comment]
Its ongoing @avirajkhare00

**Comment by sajidali** [comment]
Agreed. 
Specially with point 2.

So my suggested priority do 2 then do 1.

Both are important improvements.

**Comment by allonhadaya** [comment]
For implementing point 2: If you want to encode the user's email address, you may need to keep an application secret that can be used to encrypt the email. A simple encoding may offer some obfuscation, but no more security.

Another approach which I see more often is generating a GUID and keeping track of which user owns a particular generated GUID in the database. Then when a request is received to unsubscribe `https://www.freecodecamp.com/unsubscribe/:GUID`, it's a simple lookup + calling the same unsubscribe functionality for the associated user.

As for point 1: I agree with sending an email for account setting changes, in case the account has been compromised. But this is kind of a special case. I wouldn't want to receive an email after telling someone to stop emailing me. The user already gets feedback when they click the link. I think that's enough.

**Comment by QuincyLarson** [comment]
@allonhadaya A belated thanks for your feedback on this.

We may implement some sort of GUID in our new https://github.com/FreeCodeCamp/nonprofit-email-service which we've already started using for these emails.
