### ISSUE TITLE
for in loop

### ISSUE THREAD

**Issue by huluoyang** [FreeCodeCamp/FreeCodeCamp#8604]
something missd in the [chapter:](https://www.freecodecamp.com/challenges/profile-lookup)
the solution is use for in loop to iterate  object's property.
but for in loop did not introduced in the previous chapter.
so we should add the introduce  in this chapter.

**Comment by erictleung** [comment]
@huluoyang `for` loops are covered in [Iterate with JavaScript For Loops](https://www.freecodecamp.com/challenges/iterate-with-javascript-for-loops), which is six challenges before Profile Look up. Please visit there if you need a review. Happy coding!

**Comment by huluoyang** [comment]
@erictleung  you are right. for in loop can solve this question, the same to for loop.
