### ISSUE TITLE
no semi colon after border radius = completion (percent)

### ISSUE THREAD

**Issue by Kesb4Aspire** [FreeCodeCamp/freecodecamp#861]
![screenshot 6](https://cloud.githubusercontent.com/assets/12790960/8038797/9d611e34-0dd3-11e5-8093-105822e90c38.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-make-circular-images-with-a-border-radius has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
duplicate of #865
