### ISSUE TITLE
bad palindrome

### ISSUE THREAD

**Issue by ferzerkerx** [FreeCodeCamp/FreeCodeCamp#8610]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%20%20console.log(str)%3B%0A%20%20str%20%3D%20str.replace(%2F%5B%20%2C.%5D%2Fig%2C%20%22%22).toLowerCase()%3B%0A%20%20console.log(str)%3B%0A%20%20for%20(var%20i%20%3D%200%2C%20j%20%3D%20str.length%20-1%20%3B%20i%20%3C%20j%3B%20i%2B%2B%2C%20j--)%20%7B%0A%20%20%20%20if%20(str%5Bi%5D%20!%3D%3D%20str%5Bj%5D)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
    console.log(str);
  str = str.replace(/[ ,.]/ig, "").toLowerCase();
  console.log(str);
  for (var i = 0, j = str.length -1 ; i < j; i++, j--) {
    if (str[i] !== str[j]) {
      return false;
    }
  }
  return true;
}



palindrome("eye");

```
palindrome("0_0 (: /-\ :) 0-0") --> this is not a palindrome '_'  v.s. '-'  even If I replaced that the str that gets passed in as a param is not "0_0 (: /-\ :) 0-0" console.log says it's "0_0 (: /- :) 0-0"  it's missing the "\"

**Comment by BerkeleyTrue** [comment]
@ferzerkerx Please read the instructions carefully.

Also a cursory search of github issues would have shown this as a duplicate issue.

If you are still stuck, please use the help chatrooms or the forums to get guidance. Github issue's are for reporting bugs only.

Happy Coding!

**Comment by ferzerkerx** [comment]
My Bad thanks
Note
You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.
