### ISSUE TITLE
Linking github problem

### ISSUE THREAD

**Issue by charlsagente** [FreeCodeCamp/FreeCodeCamp#8611]
#### Issue Description
I signed up to free code camp using my linkedin account, now i want to link my github account pushing the button "Link my Github to unlock my portfolio" but i get the error:

The `user` instance is not valid. Details: `username` User already exists (value: "charlsagente"); `username` is not unique (value: "charlsagente").

#### Browser Information
Chrome 50.0.2661.102 m
Windows 7

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/948024/15256918/6df738bc-1909-11e6-9e47-9b0bca9b0c5e.png)

**Comment by BerkeleyTrue** [comment]
Looks like there was an orphaned github account. I've gone ahead and deleted it. You should now be able to link your github account.

Happy Coding!
