### ISSUE TITLE
Challenge #115, not cleared. help! Not sure of the fix.

### ISSUE THREAD

**Issue by unleashiot** [FreeCodeCamp/FreeCodeCamp#8616]
<script>
 $(document).ready(function() {
    $("button").addClass(function() {
    "animated"});
    $(".btn").addClass(function() {
      "shake"});
    $("#target1").addClass(function() {
      "btn-primary"});
  });
  
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by unleashiot** [comment]
$(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });

**Comment by dwd2010** [comment]
@unleashiot 
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!
