### ISSUE TITLE
Link from challenge "Use the Twitchtv JSON API" to example use of API is broken

### ISSUE THREAD

**Issue by geligelu** [FreeCodeCamp/FreeCodeCamp#8618]
#### Use the Twitchtv JSON API
https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

#### Issue Description

> 8. Hint: See an example call to Twitch.tv's JSONP API at https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-the-Twitchtv-JSON-API.

The link is broken. It results in being dropped at the main wiki page. If you look into the index, the page for this project doesn't exist.

Re-instate the example

#### Browser Information

* Browser Name, Version: All
* Operating System: All
* Mobile, Desktop, or Tablet: All 

#### Screenshot
<img width="201" alt="use_the_twitch_tv_json_api___free_code_camp" src="https://cloud.githubusercontent.com/assets/6688676/15267190/67499354-19ed-11e6-9d04-1cec4e288a72.png">

**Comment by theflametrooper** [comment]
*To contributor:*

Old link: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-the-Twitchtv-JSON-API
New link: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Front-End-Project-Use-Twitchtv-JSON-API

Change this line of code: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/intermediate-ziplines.json#L156.
