### ISSUE TITLE
When I try to re-run code, it seems to not run.

### ISSUE THREAD

**Issue by abbynormative** [FreeCodeCamp/freecodecamp#862]
Challenge http://www.freecodecamp.com/challenges/bonfire-dna-pairing has an issue. 
I'm trying to debug and re-run my code and it's not working. I have a console.log statement in the code that will run and output *once* and when I try to re-run the code nothing at all prints to the console. Here's a screenshot of the initial output. It seems like I'm getting some errors with the backend code at FCC.
![screen shot 2015-06-08 at 10 13 06 am](https://cloud.githubusercontent.com/assets/6013096/8040853/ac8c01ea-0dc8-11e5-84b4-8fe5bb87d79d.png)

**Comment by treece** [comment]
Can you supply your full code including your console.log code? Thanks
