### ISSUE TITLE
glove piglatin should be lovegay instead of oveglay

### ISSUE THREAD

**Issue by ankit31894** [FreeCodeCamp/FreeCodeCamp#8623]
Challenge [Pig Latin](https://www.freecodecamp.com/challenges/pig-latin#?solution=%0Afunction%20translatePigLatin(str)%20%7B%0A%20%20str%3Dstr.toLowerCase()%3B%0A%20%20if(str%5B0%5D%3D%3D%3D'a'%7C%7Cstr%5B0%5D%3D%3D%3D'e'%7C%7Cstr%5B0%5D%3D%3D%3D'i'%7C%7Cstr%5B0%5D%3D%3D%3D'o'%7C%7Cstr%5B0%5D%3D%3D%3D'u')%0A%20%20return%20str.split(%22%22).push(%22way%22).join(%22%22)%3B%0A%20%20else%20%7B%0A%20%20%20%20var%20f%3Dstr.split(%22%22)%3B%0A%20%20%20%20f.push(f.splice(0%2C1)%2B%22ay%22)%3B%0A%20%20%20%20console.log(f.join(%22%22))%3B%0A%20%20%20%20return%20f.join(%22%22)%3B%20%0A%20%20%7D%0A%7D%0A%0AtranslatePigLatin(%22consonant%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function translatePigLatin(str) {
  str=str.toLowerCase();
  if(str[0]==='a'||str[0]==='e'||str[0]==='i'||str[0]==='o'||str[0]==='u')
  return str.split("").push("way").join("");
  else {
    var f=str.split("");
    f.push(f.splice(0,1)+"ay");
    console.log(f.join(""));
    return f.join(""); 
  }
}

translatePigLatin("consonant");

```

**Comment by erictleung** [comment]
@ankit31894 thanks for the issue but "oveglay" is the correct translation. 

> Pig Latin takes the first consonant (or **consonant cluster**) of an English word, moves it to the end of the word and suffixes an "ay".

Happy coding!
