### ISSUE TITLE
Improve UX for sent emails

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#8628]
Not a pressing concern at the moment.

We currently use loopback + nodemailer to send out emails.
 - Welcome emails.
 - Verification emails.
 - User reaching all three certificates
 - @QuincyLarson 's email blasts
 - And maybe other's in future when we go passwordless.

The emails are currently not very appealing to look.
It would be a good move to migrate to make them more appealing in future.

[nodemailer](https://nodemailer.com/) already supports EJS templating.
The idea is to come up with beautiful templates themed with Free Code Camp's style guidelines.

Screenshot for reference:
![welcome](https://cloud.githubusercontent.com/assets/1884376/15270288/e09124a8-1a37-11e6-8946-fbf13b6d5951.png)

**Comment by raisedadead** [comment]
/cc @QuincyLarson @BerkeleyTrue 

I have had a word with @hallaathrad and both of us will look into this sometime after the priority tasks are sorted.

But would love the feed backs from everyone before we proceed.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson has done a lot of research on this. He found plain text emails have a better engagement and feel less startup-y. This is why all are emails are plain text.

**Comment by QuincyLarson** [comment]
@raisedadead yes - research seems to indicate that text emails "seem more authentic" and have higher engagement than HTML emails. Which makes sense, if you think about it. After all, when was the last time you got an HTML email from an individual person?
