### ISSUE TITLE
Not able to complete challenge after adding the correct code

### ISSUE THREAD

**Issue by gabrielsixel** [FreeCodeCamp/freecodecamp#863]
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Opening the challange and adding the correct code, is not enabling the "Go to my next challenge" button, in Chrome, OS Ubuntu 14.04 LTS.

![screenshot from 2015-06-08 15 23 50](https://cloud.githubusercontent.com/assets/3343261/8042017/95adc10a-0df2-11e5-8c42-284c1f580a38.png)

**Comment by treece** [comment]
Hey @gabrielsixel, I see your issue. Unfortunately, your code isn't correct according to the instructions :P Your second image is missing the `img-responsive` class. I can't see the code for your first image but I bet you put the 'img-responsive` class on the first img. The second image is your new image, not the first. Fix those things and it should pass for you ;-) Thanks for submitting your issue! Don't hesitate to keep submitting more issues if you find them. Every issue helps! This challenge's test descriptions may need to be reworded. Maybe change `Your new image should have the class "img-responsive"` to `Your second image should have the class "img-responsive"`. I'll leave that up to the project owners to decide :D Thanks again!

**Comment by BerkeleyTrue** [comment]
@treece Thanks!. This test is working fine. @treece comment is correct. 

@gabrielsixel Good luck with the rest of the challenges!
