### ISSUE TITLE
'Understanding Uninitialized Variables' accepts code that breaks the rules

### ISSUE THREAD

**Issue by llamatarianism** [FreeCodeCamp/FreeCodeCamp#8631]
#### Understanding Uninitialized Variables
[Link here](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables)

#### Accepts invalid code
One of the test cases is: `"Do not change code below the line."` However, you can still pass the challenge if you change code below that line.

#### Browser Information
* Browser Name, Version: Firefox 46
* Operating System: Ubuntu 14.04 LTS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```js
// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";

a = 6;
b = 15;
c = "I am a String!";

// This passes.
```

#### Screenshot
![screenshot of the code passing](http://i.imgur.com/72VDM2E.png)

**Comment by ltegman** [comment]
@FreeCodeCamp/issue-moderators What do you think? I don't think these kinds of errors are worth fixing because as an optional challenge the only point is for the students learning benefit. If a student chooses to blatantly disregard the instructions they are only harming their own learning potential.

**Comment by SaintPeter** [comment]
Bah.  This is for truly new coders.  If you're smart enough to do this, you're smart enough to not need what it teachers. 

I say leave it as it is.

**Comment by ltegman** [comment]
Cool. With a 3 person consensus I feel fine closing this, hopefully you can understand our reasoning 👍

**Comment by vamenssa** [comment]
I am having similar problem. But i tried changing the 's' in string to uppercase 'S', like so: c = "I am a String !". It worked.

**Comment by ganksquad** [comment]
a = 5 + 1;
b = 10 + 5;
c = "I am a" + " String!";  this is how i did !  but could not pass "Do not change code below the line"
so tried your solutions and it worked!
