### ISSUE TITLE
Code Portfolio  - UI/UX issues

### ISSUE THREAD

**Issue by stomperstomp** [FreeCodeCamp/FreeCodeCamp#8632]
The sections of the code portolio should be collapsed by default (accordians) - projects, algorithms, challenges etc. Based on it's current designs, users automatically scroll to the bottom to find their latest (current) work which is not the case. It would be easier if the sections were accordians and collapsed/closed by default, so that the user can toggle visibility to quickly identify and find the project they need.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by bugron** [comment]
@stomperstomp thanks for posting!
Closing this issue in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5667.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
