### ISSUE TITLE
Trigger Click Events with jQuery: Missing $ sign will still pass the test.

### ISSUE THREAD

**Issue by raynor84** [FreeCodeCamp/FreeCodeCamp#8634]
I Don't know if it is a general issue or only related to this task.
if i write folling code in the exercise:
```
    $("#getMessage").on("click", function() {
      //alert((".message"));
      (".message").html("You clicked get Message");
    });
```
This test will pass, even though i should have put a dollar sign before ("message"). I found this error when I passed the test, but the message didn't change on the mobile screen.
[link](https://www.freecodecamp.com/challenges/trigger-click-events-with-jquery#?solution=%0Afccss%0A%20%20%24%28document%29.ready%28function%28%29%20{%0A%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%24%28%22%23getMessage%22%29.on%28%22click%22%2C%20function%28%29%20{%0A%20%20%20%20%20%20%2F%2Falert%28%28%22.message%22%29%29%3B%0A%20%20%20%20%20%20%24%28%22.message%22%29.html%28%22You%20clicked%20get%20Message%22%29%3B%0A%20%20%20%20}%29%3B%0A%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%20%20}%29%3B%0Afcces%0A%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by internetbird** [comment]
It seems that the tests for this challenge only  test that you attached a handler to the button's click event. It doesn't check what the handler is actually doing something or that it is valid.

**Comment by raisedadead** [comment]
This challenge needs an additional test case to check the below is doing what it should be

`$(".message").html("You clicked get Message");`

**Comment by nishant-tomer** [comment]
Yes. Tests for this challenge only check for attachment of event handler.
What i found more interesting was that instructions for [this challenge](https://www.freecodecamp.com/challenges/trigger-click-events-with-jquery) encompasses instructions for [next challenge](https://www.freecodecamp.com/challenges/change-text-with-click-events) also as both of these ask the camper to update the html of the div with the class ".message" in addition to to first challenge asking for attaching an event handler.

Taking a guess, I don't _think_ the first challenge is supposed to have instructions for updating html.

**Comment by c0906969479** [comment]
2016/5/16 02:11於 "Nishant Tomer" <notifications@github.com>寫道：

**Comment by raisedadead** [comment]
@c0906969479 

If you have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)

**Comment by raynor84** [comment]
so maybe, the two tasks should be merged together or update the instruction.

**Comment by nishant-tomer** [comment]
Conceptually both tasks are different and independent. That's why i believe they have broken into two steps. Lets see what core team has to say about it

**Comment by raisedadead** [comment]
Oh Yes, this is an utter confusion. Sorry my bad.
@raynor84 @nishant-tomer thanks.

The tests are actually correct. the instructions confused me as well. 

The code from the issue description is not required at all. The below block is unnecessary.
```
//alert((".message"));
      (".message").html("You clicked get Message");
```

That's the reason the tests do not look for it.

The below should rather be updated
>Let's make our "Get Message" button change the text of the element with the class message.
>Before we can do this, we need to implement a click event inside of our $(document).ready() function by adding this code:

to perhaps:
> Let's  implement a click event inside of our $(document).ready() function by adding this code:
```
code block
```
> Proceed to the next challenge where we will make our "Get Message" button change the text of the element with the class message.

**Comment by raisedadead** [comment]
@nishant-tomer you are correct we still need two challenges, for the sake of not overwhelming target audience.

**Comment by nishant-tomer** [comment]
do i go ahead and update the instructions and have someone review them or we need to decide the exact final instructions before editing?

**Comment by raisedadead** [comment]
You can make the PR and we can update you in the comments if we need a change, this should be pretty straight.

I would rather wait for @erictleung though for second thoughts.

**Comment by erictleung** [comment]
@nishant-tomer Yeah, the JSON and Ajax challenges need some love. But I like @raisedadead's suggestion on the instruction changes. 

> Let's implement a `click event` inside of our `$(document).ready()` function by adding this code:
> ```
> code block
> ```
> Then proceed to the next challenge where we will make our "Get Message" button change the text of the element with the class message.
