### ISSUE TITLE
Facebook campsite group link is very hard to find

### ISSUE THREAD

**Issue by bumbeishvili** [FreeCodeCamp/FreeCodeCamp#8637]
#### Challenge Name
Challenge - [Join Campsite in your city](https://www.freecodecamp.com/challenges/join-a-campsite-in-your-city)

#### Issue Description
This challenge says that we must find campsite city on the list, but when I open link, there is not any list of campsites. It redirects to camperbot page, which redirects to gitter

**Comment by theflametrooper** [comment]
The wiki URL was changed for the list of campsites.

**To contributor:**

Change this line: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/00-getting-started/getting-started.json#L664

New link: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/LocalGroups-List

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by b2m9** [comment]
Hi, first timer here. I'll fix in the next hours. Cheers!

**Comment by raisedadead** [comment]
@b2m9 Hey Bob, mind having a look at any of the open issues? Looking forward to your contributions.
