### ISSUE TITLE
Bug in challenge: Create a Text Field  

### ISSUE THREAD

**Issue by UsamaHameed** [FreeCodeCamp/FreeCodeCamp#8638]
#### Challenge Name

Create a Text Field

#### Issue Description

The challenge says to add a Text Field at the end of the ordered list. But the area at the end is not clickable. When I use Ctrl+A, the last line is left out of the selection as shown in the screenshot I uploaded.
 When I re-size my browser the area becomes clickable. I think this has something to do with the <html> height specified in the code.

#### Browser Information

* Browser Name, Version: Google Chrome v50.0.2661.102
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/11444352/15273310/bf53476e-1aad-11e6-9793-8d26d1f1e654.PNG)

**Comment by UsamaHameed** [comment]
My resolution is 1920x1080

**Comment by Ali-AM** [comment]
در تاریخ ۱۵ مهٔ ۲۰۱۶ ۱۴:۳۵، "Usama Hameed" <notifications@github.com> نوشت:
>
> Challenge Name
>
> Create a Text Field
>
> Issue Description
>
> The challenge says to add a Text Field at the end of the ordered list.
But the area at the end is not clickable. When I use Ctrl+A, the last line
is left out of the selection as shown in the screenshot I uploaded.
> When I re-size my browser the area becomes clickable. I think this has
something to do with the height specified in the code.

**Comment by ltegman** [comment]
I'm not able to repro this and I suspect it's a codemirror issue. I'll leave this open for now in case someone else can repro, but it not there's really no way to proceed with fixing this.

**Comment by niwsa** [comment]
I can confirm the issue as @UsamaHameed mentioned tried resizing the window it works.

User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.

**Comment by bugron** [comment]
@UsamaHameed we've updated CodeMirror (see https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8737) a couple of days ago, hopefully, this issue is fixed with that. I'm going to close this issue but feel free to reopen if you still experience this, thanks.
