### ISSUE TITLE
If a class is in a UL reports no ending UL bracket

### ISSUE THREAD

**Issue by Kesb4Aspire** [FreeCodeCamp/freecodecamp#864]
![screenshot 7](https://cloud.githubusercontent.com/assets/12790960/8042030/42cdec1a-0dea-11e5-8436-4c4e9f47b110.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/12790960/8042038/4d5d0bfc-0dea-11e5-904e-1bae7b5d4dc5.png)

took a few to figure this one out

Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by treece** [comment]
Hey, @Kesb4Aspire , thanks for submitting this issue! Your right, there is an issue in the test for this waypoint. I'll do a PR for this tonight if nobody else wants to do it. Good find though! Keep'em coming :+1:  Thanks!
