### ISSUE TITLE
Outdated username

### ISSUE THREAD

**Issue by SavageryVisual** [FreeCodeCamp/FreeCodeCamp#8648]
I changed my GitHub username and linked it with my FCC account and it changed. 
But in chat it is still outdated and when people send me points, it says I'm not found.
Old username-> TeamAgarioPlayer
New username-> SavageryVisual
Pls help :/

**Comment by BerkeleyTrue** [comment]
You'll need to contact Gitter support. We don't have control over the Gitter.

Happy Coding!

**Comment by sludge256** [comment]
@SavageryVisual Try updating again via the button at https://www.freecodecamp.com/settings([direct](https://www.freecodecamp.com/link/github)). It may also help to relog on your various Gitter apps.

**Comment by SavageryVisual** [comment]
@sludge256 I tried updating but still didn't work :/

**Comment by BerkeleyTrue** [comment]
@SavageryVisual Again, we don't control the Gitter service. You need to contact their support. Changing your settings won't do anything on their end.

**Comment by sludge256** [comment]
Resolved
