### ISSUE TITLE
Night mode is not persisting on any other page except the challenges.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#8650]
We are storing the Night mode as theme, its not persisting on any page other than the challenges.

Steps to reproduce:

1. Clear browser cache.
2. Visit FreeCodeCamp.com, login
3. toggle night mode (g + t +n)
4. Visit profile, about, settings, email-update, etc.

You can however press (g+t+n) to activate night mode on these pages.

**Comment by raisedadead** [comment]
Can be seen on the sidebars, but individual stand alone pages for map and wiki are persisting the change.

**Comment by flipsyde606** [comment]
Does this need fixing? Can I look into this?

**Comment by raisedadead** [comment]
@flipsyde606 yes if you would want to, thanks. 
/cc @benmcmahon100

**Comment by qbeer** [comment]
it is still not working properly. :(
