### ISSUE TITLE
escaping literal quotes challenge does not validate syntax accurately

### ISSUE THREAD

**Issue by bobbytanwer** [FreeCodeCamp/FreeCodeCamp#8653]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0A%2F%2Fvar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%0Avar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%20%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
while attempting to complete challenge escaping literal quotes. Validation fails on accurate syntax. i am sure that my declaration is correct. 
My code:
```javascript

//var myStr = "I am a \"double quoted\" string inside \"double quotes\"";
var myStr = "I am a \"double quoted\" string inside \"double quotes\""; 




```

**Comment by erictleung** [comment]
@bobbytanwer thanks for the issue. Your uncommented code is correct. The first test your code "fails" actually looks for the number of double quotes and escaped quotes, independent of being commented or not. I'm not sure how we would be able to check for this.

cc/ @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
Well at best we can add a warning, 
> Do not add comments with `''` in them, to avoid conflicts with tests.

or alternatively we can write a test case that checks for this.

**Comment by nishant-tomer** [comment]
We can alter the test to discard any double quotes between double forward slashes and a newline.
I don't know if that's comprehensive enough.If you agree, i will make a PR for this.

**Comment by raisedadead** [comment]
Sure, if that can work, why not. Make a PR,  we will do a through QA testing.

**Comment by freinet12** [comment]
I'm having a similar problem. My code is correct but it wont let me pass the second test.

var myStrd = "I am a \"double quoted\" string inside \"double quotes\" ";

**Comment by SaintPeter** [comment]
@freinet12 You have a trailing space before your second to last and last quote.

**Comment by freinet12** [comment]
@SaintPeter Thank you

**Comment by yoavgray** [comment]
Seems like there is still a problem. My code is:
var myStr = "I am a \"double quoted\" string inside \"double quotes\"";

and still it does not let me pass.
Anyone?

**Comment by erictleung** [comment]
@yoavgray GitHub issues aren't the place for coding help. Please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by Razz67** [comment]
I got mine to work by putting the period before the last quotation mark.  Hope this helps.

**Comment by Gione** [comment]
@Razz67 ^^^ That worked perfectly

**Comment by bobbytanwer** [comment]
Thank you for the share

**Comment by fmd123** [comment]
I am having a problem with this also... 
This is my code and I'm pretty sure that I 'm not doing it incorrectly. I am using Chrome.
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; 
// Change this line

**Comment by dhcodes** [comment]
Closing this as it appears to be fixed in beta and locally.
