### ISSUE TITLE
Everyone around me can be happy.

### ISSUE THREAD

**Issue by zhangzheng08331** [FreeCodeCamp/FreeCodeCamp#8654]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<html>
  <head>
    <title> Everyone around me can be happy.</title>
    
  </head>
  <body>
     <h1>
       Hello,Word!!!my name is ZZ,I hope everyone around me can be   
       happy!!!
    </h1>
  

- [ ] </body>

  
</html>

```

**Comment by raisedadead** [comment]
Yes. They are, but that's not issue to be logged under this repo :wink: !

Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
