### ISSUE TITLE
Basic Algorithm Scripting - "Where do I belong" - Incorrect test pass

### ISSUE THREAD

**Issue by pradxj07** [FreeCodeCamp/FreeCodeCamp#8656]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20var%20id%20%3D%200%3B%0A%20%20%2F%2Fvar%20arrSort%20%3D%20%0A%20%20arr.sort(function(prev%2C%20curr)%20%7B%0A%20%20%20%20return%20prev-curr%3B%0A%20%20%7D)%3B%0A%20%20var%20length1%20%3D%20arr.length%3B%20%0A%20%20%0A%2F%2F%20if%20array%20is%20empty%20or%20num%20is%20less%20than%20lowest%20item%2C%20item%20should%20be%20placed%20at%20beginning%20of%20array%20%20%0A%20%20if(length1%20%3C%3D0)%20%20%7B%0A%20%20%20%20return%200%3B%0A%20%20%7D%20else%20if%20(num%20%3E%20arr%5Blength1-1%5D)%20%7B%20%20%20%20%20%2F%2F%20if%20num%20%3E%20last%20item%2C%20item%20should%20be%20placed%20at%20end%20of%20array%20%0A%20%20%20%20return%20length1%20%3B%0A%20%20%7D%20else%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2Ffind%20position%0A%20%20%20%20%20%20%2F%2Fconsole.log(arr)%3B%0A%20%20%20%20%2F%2F%20Divide%20array%20into%20two%20parts%0A%0A%2F%2F%20%20%20%20var%20loopCheck%20%3D%20function(this%2C%20lower%2C%20upper)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%20%20%20%20%0A%7D%0A%20%20%20%20%0A%20%20%0AgetIndexToIns(%5B%5D%2C%203)%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

+++
While I was testing my partially written code and I noticed that test case **"getIndexToIns([2, 5, 10], 15) should return 3."** even when I pass an empty array as input. Kindly see the code below that I was testing - 
+++ 

My code:
```javascript

function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  var id = 0;
  //var arrSort = 
  arr.sort(function(prev, curr) {
    return prev-curr;
  });
  var length1 = arr.length; 
  
// if array is empty or num is less than lowest item, item should be placed at beginning of array  
  if(length1 <=0)  {
    return 0;
  } else if (num > arr[length1-1]) {     // if num > last item, item should be placed at end of array 
    return length1 ;
  } else {                          //find position
      //console.log(arr);
    // Divide array into two parts

//    var loopCheck = function(this, lower, upper) {
             
  }
      
}
    
  
getIndexToIns([], 3);



```

Also, attached is a screenshot for your reference. 

![2016-05-16_9-51-46_incorrect test case passed](https://cloud.githubusercontent.com/assets/15888038/15285412/dac2c334-1b4e-11e6-9cf2-e8734173aa5c.png)
Thank you.

**Comment by erictleung** [comment]
@pradxj07 this is happening because of your code:

```
if(length1 <=0)  {
    return 0;
} else if (num > arr[length1-1]) {
    return length1
}
```

Your code and function says to essentially return the length of the array given. So for the test case, the length of the array `[2, 5, 10]` is 3, and thus will pass that test.

Happy coding!
