### ISSUE TITLE
There is some problem with test conditions.

### ISSUE THREAD

**Issue by shubhdo** [FreeCodeCamp/FreeCodeCamp#8659]
Challenge [Validate US Telephone Numbers]
i have tested regex on tester its returning true but in freecodecamp console it returning false.i have taken screenshots of each window
(https://www.freecodecamp.com/challenges/validate-us-telephone-numbers#?solution=%0Afunction%20telephoneCheck(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20regex%3D%2F%5E1%3F%5E%5C(%3F%5Cs%3F%5E%5Cd%7B3%7D%5B%5Cs-%5C)%5D%3F%5Cd%7B3%7D%5B-%5Cs%5D%3F%5Cd%7B4%7D%24%2F%3B%0A%20%20%20if(regex.test(str))%20%7B%0A%20%20%20%20%20return%20true%3B%0A%20%20%20%7D%0A%20%20else%0A%20%20%20%20return%20false%3B%0A%7D%0A%0A%0AtelephoneCheck(%221%20456%20789%204444%22)%3B%0A) has an issue.
![screenshot 1](https://cloud.githubusercontent.com/assets/9122440/15288017/01367f02-1b1c-11e6-82b3-9c4843775d2c.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/9122440/15288018/01f2cfa4-1b1c-11e6-8678-0bc444025913.png)

User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function telephoneCheck(str) {
  // Good luck!
  var regex=/^1?^\(?\s?^\d{3}[\s-\)]?\d{3}[-\s]?\d{4}$/;
   if(regex.test(str)) {
     return true;
   }
  else
    return false;
}


telephoneCheck("1 555-555-5555");

```

**Comment by raisedadead** [comment]
Tested on the same site with your regex `/^1?^\(?\s?^\d{3}[\s-\)]?\d{3}[-\s]?\d{4}$/`

![image](https://cloud.githubusercontent.com/assets/1884376/15291416/5690b0a6-1b9b-11e6-8c27-b1b44a87f06c.png)

Your code is not correct. Look closely, you may have submitted a different on than one you tested.
