### ISSUE TITLE
green box padding will complete without semicolon

### ISSUE THREAD

**Issue by Kesb4Aspire** [FreeCodeCamp/freecodecamp#866]
![screenshot 10](https://cloud.githubusercontent.com/assets/12790960/8042743/4474d8da-0def-11e5-9972-16e9a4553c8e.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-padding-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
closing as duplicate of #865
