### ISSUE TITLE
Georgian translation "Getting Started"

### ISSUE THREAD

**Issue by kiknag** [FreeCodeCamp/FreeCodeCamp#8660]
#### Getting Started - Translation in Georgian

In this issue I will discuss translation "Getting Started" section in Georgian.
Getting Started - დაწყება
Join the FreeCodeCamp community - შეუერთდი FreeCodeCamp-ის საზოგადოებას.

- [ ] Learn how Free Code Camp Works
- [ ] Create a GitHub Account and Join our Chat Rooms 
- [ ] Configure your Code Portfolio 
- [ ] Join a Campsite in Your City
- [ ] Learn What to Do If You Get Stuck  

---------------------
**Constants**
Minutes - წუთი
Hours - საათი

**Comment by bugron** [comment]
@kiknag any updates on this?

**Comment by raisedadead** [comment]
Issue moved to [FreeCodeCamp/TranslationExpansion #84](https://github.com/FreeCodeCamp/TranslationExpansion/issues/84) via [**ZenHub**](https://www.zenhub.com/)
