### ISSUE TITLE
milestones are shown in red even though the coed is right

### ISSUE THREAD

**Issue by Shashank143s** [FreeCodeCamp/FreeCodeCamp#8661]
#### Challenge Name

Comparisons with the Logical Or Operator
https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator

#### Issue Description

```js
function testLogicalOr(val) {
  // Only change code below this line

  if (val<10 || val>20) {
    return "Ouside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(0);
```

the  code produces output as "outside" which is required but still it shows a red cross in the milestone section.

#### Browser Information

* Browser Name, Version: Firefox Nightly 49.0a1 (2016-05-09)
* Operating System: Windows 7 professional
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function testLogicalOr(val) {
  // Only change code below this line

  if (val<10 || val>20) {
    return "Ouside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(0);
```

#### Screenshot

![error](https://cloud.githubusercontent.com/assets/16089477/15292001/725de058-1b9e-11e6-9f24-eb8d70057cd5.jpg)

**Comment by raisedadead** [comment]
![image](https://cloud.githubusercontent.com/assets/1884376/15292307/2429bed2-1ba0-11e6-9a37-25f6fe1da023.png)

Typo?

Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)
