### ISSUE TITLE
Change the Font Size of an Element

### ISSUE THREAD

**Issue by MattewDeveloper** [FreeCodeCamp/FreeCodeCamp#8662]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Cp%20class%3D%22red-text%22%3ELorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipiscing%20elit.%20Nunc%20sagittis%20lorem%20ligula%2C%20ut%20fermentum%20ligula%20congue%20id.%20In%20vel%20facilisis%20nisi%2C%20at%20interdum%20nibh.%20Suspendisse%20hendrerit%20viverra%20neque%20rutrum%20mollis.%20Praesent%20gravida%20arcu%20nisl%2C%20sit%20amet%20suscipit%20lectus%20consequat%20ac.%20In%20tristique%20et%20purus%20in%20luctus.%20Phasellus%20euismod%20facilisis%20felis%20at%20blandit.%20Cum%20sociis%20natoque%20penatibus%20et%20magnis%20dis%20parturient%20montes%2C%20nascetur%20ridiculus%20mus.%20Morbi%20at%20tempor%20sapien.%20Aenean%20condimentum%20ligula%20eget%20porttitor%20porttitor.%20Donec%20dolor%20leo%2C%20venenatis%20et%20lacus%20sed%2C%20maximus%20dictum%20nulla.%20Pellentesque%20consectetur%2C%20erat%20sed%20convallis%20ultricies%2C%20enim%20ex%20commodo%20purus%2C%20vel%20hendrerit%20libero%20dui%20ultrices%20tortor.%20Vestibulum%20ullamcorper%20augue%20libero%2C%20quis%20dignissim%20turpis%20fermentum%20eu.%20Fusce%20tempor%20ex%20a%20ullamcorper%20consectetur.%20Vestibulum%20eget%20sagittis%20odio%2C%20sodales%20posuere%20tellus.%20Morbi%20mollis%20vulputate%20neque%2C%20aliquam%20tempus%20turpis.%3C%2Fp%3E%0A%3Cp%3ELorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipiscing%20elit.%20Nunc%20sagittis%20lorem%20ligula%2C%20ut%20fermentum%20ligula%20congue%20id.%20In%20vel%20facilisis%20nisi%2C%20at%20interdum%20nibh.%20Suspendisse%20hendrerit%20viverra%20neque%20rutrum%20mollis.%20Praesent%20gravida%20arcu%20nisl%2C%20sit%20amet%20suscipit%20lectus%20consequat%20ac.%20In%20tristique%20et%20purus%20in%20luctus.%20Phasellus%20euismod%20facilisis%20felis%20at%20blandit.%20Cum%20sociis%20natoque%20penatibus%20et%20magnis%20dis%20parturient%20montes%2C%20nascetur%20ridiculus%20mus.%20Morbi%20at%20tempor%20sapien.%20Aenean%20condimentum%20ligula%20eget%20porttitor%20porttitor.%20Donec%20dolor%20leo%2C%20venenatis%20et%20lacus%20sed%2C%20maximus%20dictum%20nulla.%20Pellentesque%20consectetur%2C%20erat%20sed%20convallis%20ultricies%2C%20enim%20ex%20commodo%20purus%2C%20vel%20hendrerit%20libero%20dui%20ultrices%20tortor.%20Vestibulum%20ullamcorper%20augue%20libero%2C%20quis%20dignissim%20turpis%20fermentum%20eu.%20Fusce%20tempor%20ex%20a%20ullamcorper%20consectetur.%20Vestibulum%20eget%20sagittis%20odio%2C%20sodales%20posuere%20tellus.%20Morbi%20mollis%20vulputate%20neque%2C%20aliquam%20tempus%20turpis.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  p {
    font-size: 16px;
  }
</style>
<p class="red-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis lorem ligula, ut fermentum ligula congue id. In vel facilisis nisi, at interdum nibh. Suspendisse hendrerit viverra neque rutrum mollis. Praesent gravida arcu nisl, sit amet suscipit lectus consequat ac. In tristique et purus in luctus. Phasellus euismod facilisis felis at blandit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi at tempor sapien. Aenean condimentum ligula eget porttitor porttitor. Donec dolor leo, venenatis et lacus sed, maximus dictum nulla. Pellentesque consectetur, erat sed convallis ultricies, enim ex commodo purus, vel hendrerit libero dui ultrices tortor. Vestibulum ullamcorper augue libero, quis dignissim turpis fermentum eu. Fusce tempor ex a ullamcorper consectetur. Vestibulum eget sagittis odio, sodales posuere tellus. Morbi mollis vulputate neque, aliquam tempus turpis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis lorem ligula, ut fermentum ligula congue id. In vel facilisis nisi, at interdum nibh. Suspendisse hendrerit viverra neque rutrum mollis. Praesent gravida arcu nisl, sit amet suscipit lectus consequat ac. In tristique et purus in luctus. Phasellus euismod facilisis felis at blandit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi at tempor sapien. Aenean condimentum ligula eget porttitor porttitor. Donec dolor leo, venenatis et lacus sed, maximus dictum nulla. Pellentesque consectetur, erat sed convallis ultricies, enim ex commodo purus, vel hendrerit libero dui ultrices tortor. Vestibulum ullamcorper augue libero, quis dignissim turpis fermentum eu. Fusce tempor ex a ullamcorper consectetur. Vestibulum eget sagittis odio, sodales posuere tellus. Morbi mollis vulputate neque, aliquam tempus turpis.</p>
```
Why my code doesn't work?

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

and 

Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) before reporting.


Happy Coding!
