### ISSUE TITLE
Cannot read property length of null bug

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#867]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

cc @QuincyLarson 
![waypoint__create_a_bulleted_unordered_list___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/8042896/353631f6-0dd7-11e5-8d07-ec7ec2581bdb.png)

**Comment by treece** [comment]
Wow, I just saw this or I would've fixed it with my last commit. Yea, match returns `Cannot read property length of null` if there is no match found. How about using `.test` instead of `.match`? What do you think?

**Comment by BerkeleyTrue** [comment]
It actually needs to check existence before trying to read the property `length`.

match will sometime return undefined. So when the test tries to read undefined.length it will crash the app and be unusable.

**Comment by QuincyLarson** [comment]
Fixing it. I caught most of these but this one slipped through. @berkeley is correct.
