### ISSUE TITLE
String parameter incorrect

### ISSUE THREAD

**Issue by GavEnlighten** [FreeCodeCamp/FreeCodeCamp#8672]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20console.log(str)%3B%0A%20%20var%20palin%20%3D%20str%3B%2F%2F.replace(%2F%2C%2Fg%2C%20'').replace(%2F%5C.%2Fg%2C%20'').replace(%2F%5Cs%2Fg%2C%22%22)%3B%0A%20%2F%2F%20console.log(palin)%3B%0A%20%20%2F%2Fpalin%20%3D%20palin.trim().toLowerCase()%3B%0A%20%20%2F%2Fconsole.log(palin.split('').reverse().join(''))%3B%0A%20%20%0A%20%20return%20palin%20%3D%3D%20palin.split('').reverse().join('')%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  console.log(str);

}



palindrome("eye");

```

When trying to complete the palindrome challenge, it appears that 1 of the strings is incorrect.
palindrome("0_0 (: /-\ :) 0-0"), when I log the string variable to the console i get 0_0 (: /- :) 0-0 instead. This causes the challenge to always fail.

![image](https://cloud.githubusercontent.com/assets/12943718/15306874/4b9f8a78-1c22-11e6-80be-e3991e64c9f3.png)

**Comment by erictleung** [comment]
@GavEnlighten the string is correct.

> You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

GitHub issues are not for coding help. If you get stuck with a challenge, please ask questions first to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by GavEnlighten** [comment]
I am not asking for help.

The highlighted string in the image is a console.log of the str variable before any processing.

It is supposed to be 0_0 (: /-\ :) 0-0 not 0_0 (: /- :) 0-0. which is missing the "\" character. I thought that the missing character was causing issues.

But I suppose what you are saying is with all the special characters removed it would then default to 0000 which is a palindrome

**Comment by erictleung** [comment]
@GavEnlighten oh gotcha. The backslash `\` is an escape character so that is why it appears to "disappear." But nonetheless, yes, the backslash would be removed because of the instructions.
