### ISSUE TITLE
bonfire : Confirm the ending

### ISSUE THREAD

**Issue by gobbledegeek** [FreeCodeCamp/FreeCodeCamp#8674]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20%0A%20var%20hits%20%3D%20%5B%5D%3B%0A%0Afor%20(var%20i%20%3D%20str.length-target.length%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(str%5Bi%5D%20%3D%3D%3D%20target%5B0%5D)%20%7B%0A%20%20%20%20%20%20%20%20for%20(j%3Di%3B%20j%20%3C%20(target.length%20%2B%20i)%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20hits.push(str%5Bj%5D)%3B%0A%20%20%20%20%20%20%20%20hjoin%20%3D%20hits.join(%22%22)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%0A%20return%20hjoin%20%3D%3D%3D%20target%3B%0A%20%0A%20%20%2F*%20this%20is%20the%20actual%20answer.%20Do%20not%20alter.%20delete%20this%20line%0A%20%20strCut%20%3D%20str.substring(str.length-target.length)%3B%0A%20%20%20%20return%20strCut%20%3D%3D%3D%20target%3B%0A%20%20%20%20%0A%20%20answer%20ends.%20delete%20this%20line%20*%2F%20%0A%20%20%0A%7D%20%0A%0AconfirmEnding(%22Connor%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  
 var hits = [];

for (var i = str.length-target.length; i < str.length; i++) {
    if (str[i] === target[0]) {
        for (j=i; j < (target.length + i); j++) {
        hits.push(str[j]);
        hjoin = hits.join("");
        }
        }
        }
        
 return hjoin === target;
 
 } 

confirmEnding("Connor", "n");

```

This returns false when I run it (it says so right on the black box). But at the left-side checklist, the item saying 'confirmEnding("Connor", "n") should return false.' has a big red X beside it instead of a green check.

And yes, I know there's a shorter solution code using String.substr(), and I know how to solve this bonfire that way, but I wanted to try out other methods to see if they work too. And they seem to, but the checklist is saying otherwise...

**Comment by raisedadead** [comment]
After doing a clean reset and testing the above code I am getting:
![image](https://cloud.githubusercontent.com/assets/1884376/15311368/a58e07ae-1c17-11e6-8f0c-a3cb75ad3c9d.png)

**Comment by raisedadead** [comment]
Please provide screenshots. You may have submitted incorrect code.
Try the common troubleshooting steps.

**Comment by gobbledegeek** [comment]
Thanks, raisedadead. I've found the issue, and I've corrected it. :)

I now have 3 solutions. one using str.substr(), one using str.endsWith(), and the longest one using loops (this one, one for loop is sufficient, it turned out).
