### ISSUE TITLE
Text color of warning and errors while hovering over the marker

### ISSUE THREAD

**Issue by karuppiah7890** [FreeCodeCamp/FreeCodeCamp#8675]
The issue is present in the text editor used by FCC site. It's CodeMirror. And I noticed this for a long time that the text color of the warning and errors when hover over were "infotext" on a "infobackground" background color, which was very tough to view, and I had to strain my eye to see the text. I opened an issue in CodeMirror's github repo and they fixed it and closed it. Here's the link to the issue : 

https://github.com/codemirror/CodeMirror/issues/4025

And looks like they also updated their bower component too. But FCC has to update it's bower component too! So I opened this issue so that you update your bower components.

#### Browser Information
Firefox Developer Edition. Ubuntu 64 bit. Desktop.
I think the problem exists in a lot of system.

#### Screenshot
![error hover](https://cloud.githubusercontent.com/assets/12808424/15311490/0b565c2a-1c19-11e6-9fc6-843dec480ada.png)

**Comment by raisedadead** [comment]
@karuppiah7890 Thanks for letting us know!
/cc @ltegman @BerkeleyTrue

**Comment by ltegman** [comment]
I can look into updating codemirror tomorrow if no one else beats me to it. I look forward to the day we're doing everything through npm + webpack and (hopefully) no longer have a second group of dependencies to manage!

**Comment by ltegman** [comment]
The latest CodeMirror release is from 28 days ago and your patch is from 3 days ago, so we can not update this and see the benefit yet.

**Comment by karuppiah7890** [comment]
Uh, You are using bower right ? I remember seeing "bower_components" folder in FCC github repo.

The bower site has this in the webpage. 
![update](https://cloud.githubusercontent.com/assets/12808424/15352704/1328b3cc-1d03-11e6-9b31-3692ba3eca2e.png)

It does mean it's updated right ? Or no ? How do you say the release was 28 days ago ?

**Comment by karuppiah7890** [comment]
Oh. The github release. Okay. Sorry. I just checked the bower site alone. But why does Bower say this ?

**Comment by ltegman** [comment]
It's a side effect of the fact that bower uses Github as project storage and has no "publish" step to update packages, so their update time reflects the repo state but the software it will install will be from the latest release tag.

**Comment by karuppiah7890** [comment]
Oh, okay! :+1:
