### ISSUE TITLE
font awesome trash icon closing brackets complete waypoint un-closed

### ISSUE THREAD

**Issue by Kesb4Aspire** [FreeCodeCamp/freecodecamp#868]
![screenshot 11](https://cloud.githubusercontent.com/assets/12790960/8043258/cf9ed73c-0df2-11e5-86ec-852705d08154.png)

<button class='btn btn-block btn-danger'><i class='fa fa-trash'>Delete</i </button>
  </div>

Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-all-of-our-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
@Kesb4Aspire Thanks for this. Unfortunately I cannot reproduce. Can you give us steps to reproduce?
![waypoint__add_font_awesome_icons_all_of_our_buttons___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/8044258/5a00bdea-0de0-11e5-937e-5162bd0c6b21.png)

**Comment by Kesb4Aspire** [comment]
I finished the line then somehow hit arrow keys putting me back at the </i>
closing bracket coming from the button bracket deleting the bracket noticed
it was still completed

On Jun 8, 2015 4:15 PM, "Berkeley Martinez" <notifications@github.com>
wrote:
>
> @Kesb4Aspire Thanks for this. Unfortunately I cannot reproduce. Can you
give us steps to reproduce?

**Comment by BerkeleyTrue** [comment]
@Kesb4Aspire Thanks. Once the challenge is passed the test are no longer run so your code is no longer being validated.

**Comment by kd13794** [comment]
i was going through this i element dilemma...your query saved my day...was pisst getting the error off..
thanx @Kesb4Aspire
