### ISSUE TITLE
"//Only change code above this line" should be 1 line lower

### ISSUE THREAD

**Issue by anvarov** [FreeCodeCamp/FreeCodeCamp#8681]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20result%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%20%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%20%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%20%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%20%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%20%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%20%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  result = {
    "alpha": "Adams",
    "bravo": "Boston",
    "charlie": "Chicago",
    "delta": "Denver",
    "echo": "Easy",
    "foxtrot": "Frank"
  };

  // Only change code above this line
  return result[val];  (I changed this, original was: return result)
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by raisedadead** [comment]
> Convert the switch statement into a lookup table called lookup. Use it to lookup val and **assign the associated string to the `result` variable**.

Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!

**Comment by daianepiva** [comment]
Hi guys, 
This issue was closed but the problem was not solved. The code still reads "Only change code above this line" when we are actually supposed to change what is bellow said line. That should be fixed.

**Comment by raisedadead** [comment]
@daianepiva the code indeed needs to be changed just above the comment mentioning 
> // Only change code above this line

Campers aren't expected to return a string, as per instruction:
> Use it to lookup `val` and assign the associated string to the `result` variable.

If you are still stuck please reachout to the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).
