### ISSUE TITLE
num >= 20 - return "Huge"  instruction are not correct, to pass it should be num < 20 - return "Huge"

### ISSUE THREAD

**Issue by bobbytanwer** [FreeCodeCamp/FreeCodeCamp#8682]
Challenge [Chaining If Else Statements](https://www.freecodecamp.com/challenges/chaining-if-else-statements#?solution=%0Afunction%20testSize(num)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20if(num%20%3C%205)%7B%0A%20%20%20return%20%22Tiny%22%3B%0A%20%7D%20else%20if%20(num%20%3C%2010)%7B%0A%20%20%20return%20%22Small%22%3B%0A%20%7D%20else%20if%20(num%20%3C%2015)%7B%0A%20%20%20return%20%22Medium%22%3B%0A%20%7D%20else%20if%20(num%20%3E%3D%2020)%7B%0A%20%20%20return%20%22Large%22%3B%0A%20%7Delse%7B%0A%20%20%20return%20%22Huge%22%3B%0A%20%7D%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestSize(7)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testSize(num) {
  // Only change code below this line
 if(num < 5){
   return "Tiny";
 } else if (num < 10){
   return "Small";
 } else if (num < 15){
   return "Medium";
 } else if (num >= 20){
   return "Large";
 }else{
   return "Huge";
 }
  
  return "Change Me";
  // Only change code above this line
}

// Change this value to test
testSize(7);

```

**Comment by erictleung** [comment]
@bobbytanwer the instructions are correct. You'll need to return "Huge" whenever `num >= 20`. If you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by cpereversoff** [comment]
my test size 20 and test size 25 =huge but they are not passing
