### ISSUE TITLE
Wrapping my a element in my new p element

### ISSUE THREAD

**Issue by kadheim** [FreeCodeCamp/freecodecamp#869]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by QuincyLarson** [comment]
@kadheim I've updated this challenge. Thank you for submitting this. Next time please add a more detailed description to make it easier to fix these things.
