### ISSUE TITLE
requirements of problem not clear.

### ISSUE THREAD

**Issue by Spartano** [FreeCodeCamp/FreeCodeCamp#8692]
Challenge [Friendly Date Ranges](https://www.freecodecamp.com/challenges/friendly-date-ranges#?solution=%0Afunction%20makeFriendlyDates(arr)%20%7B%0A%20%20%0A%20%20function%20dateEndings(val)%7B%0A%20%20%20%20%0A%20%20%20%20switch(val)%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20case%201%3A%0A%20%20%20%20%20%20case%2021%3A%0A%20%20%20%20%20%20case%2031%3A%0A%20%20%20%20%20%20%20%20return%20val%20%2B%20%22st%22%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20case%202%3A%0A%20%20%20%20%20%20case%2022%3A%0A%20%20%20%20%20%20%20%20return%20val%20%2B%20%22nd%22%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20case%203%3A%0A%20%20%20%20%20%20case%2023%3A%0A%20%20%20%20%20%20%20%20return%20val%20%2B%20%22rd%22%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20default%20%3A%20%0A%20%20%20%20%20%20%20%20return%20val%20%2B%20%22th%22%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20var%20temp%20%3D%20%5B%5D%3B%0A%20%20var%20dates%20%3D%20%5B%5D%3B%0A%20%20var%20converted%20%3D%20%5B%5D%3B%0A%20%20var%20months%20%3D%20%5B'January'%2C%20'February'%2C%20'March'%2C%20'April'%2C%20'May'%2C%20'June'%2C%20'July'%2C%20'August'%2C%20'September'%2C%20'October'%2C%20'November'%2C%20'December'%5D%3B%20%20%0A%20%20%0A%20%20%0A%20for(var%20i%20in%20arr)%7B%0A%20%20%20%0A%20%20%20temp%5Bi%5D%20%20%3D%20arr%5Bi%5D.%20split(%22-%22)%3B%0A%20%20%20%0A%20%20%20dates%5Bi%5D%20%3D%20new%20Date(Date.UTC(temp%5Bi%5D%5B0%5D%2C%20(temp%5Bi%5D%5B1%5D-1)%2C%20temp%5Bi%5D%5B2%5D))%3B%0A%20%20%20%0A%20%20%20converted%5Bi%5D%20%3D%20months%5Bdates%5Bi%5D.getUTCMonth()%5D%20%2B%20%22%20%22%20%2B%20dateEndings(dates%5Bi%5D.getUTCDate())%20%20%20%2B%20%22%2C%20%22%20%2B%20dates%5Bi%5D.getUTCFullYear()%3B%0A%20%20%20%0A%20%7D%0A%20%20%0A%20%0A%20%20%0Avar%20yearInMilliseconds%20%3D%201000%20*%2060%20*%2060%20*%2024%20*%20365%3B%0Avar%20today%20%3D%20new%20Date()%3B%0Avar%20year%20%3D%20today.getFullYear()%3B%0A%0A%0A%20%20%2F%2Ffirst%20condition%20if%20it's%20in%20the%20current%20year%0A%20%20%0A%20%20if(dates%5B0%5D.getUTCFullYear()%20%3D%3D%3D%20year%20%26%26%20dates%5B1%5D%20-%20dates%5B0%5D%20%3C%20yearInMilliseconds)%7B%0A%20%20%20%20%0A%20%20%20%20converted%5B0%5D%20%3D%20converted%5B0%5D.substring(0%2C%20converted%5B0%5D.indexOf(%22%2C%22))%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%20%2F%2Fsecond%20condition%0A%20if(%20dates%5B1%5D%20-%20dates%5B0%5D%20%3C%20yearInMilliseconds)%7B%0A%20%20%20%0A%20%20converted%5B1%5D%20%3D%20converted%5B1%5D.substring(0%2C%20converted%5B1%5D.indexOf(%22%2C%22))%3B%0A%20%20%20%0A%20%7D%0A%20%20%0A%20%20%2F%2Fthird%20if%20ends%20the%20same%20month%20of%20the%20same%20year%0A%20%20%0A%20%20if(dates%5B0%5D.getUTCMonth()%20%3D%3D%3D%20dates%5B1%5D.getUTCMonth()%20%26%26%20dates%5B0%5D.getUTCFullYear()%20%3D%3D%3D%20dates%5B1%5D.getUTCFullYear())%7B%0A%20%20%20%20%0A%20%20%20converted%5B1%5D%20%3D%20converted%5B1%5D.substring(converted%5B1%5D.indexOf(%22%20%22)%20%2B%201)%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%20return%20converted%3B%0A%7D%0A%0AmakeFriendlyDates(%5B%222018-01-13%22%2C%20%222018-01-13%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function makeFriendlyDates(arr) {
  
  function dateEndings(val){
    
    switch(val){
        
      case 1:
      case 21:
      case 31:
        return val + "st";
      
      case 2:
      case 22:
        return val + "nd";
        
      case 3:
      case 23:
        return val + "rd";
        
     default : 
        return val + "th";
        
    }
    
  }
  
  
  var temp = [];
  var dates = [];
  var converted = [];
  var months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];  
  
  
 for(var i in arr){
   
   temp[i]  = arr[i]. split("-");
   
   dates[i] = new Date(Date.UTC(temp[i][0], (temp[i][1]-1), temp[i][2]));
   
   converted[i] = months[dates[i].getUTCMonth()] + " " + dateEndings(dates[i].getUTCDate())   + ", " + dates[i].getUTCFullYear();
   
 }
  
 
  
var yearInMilliseconds = 1000 * 60 * 60 * 24 * 365;
var today = new Date();
var year = today.getFullYear();


  //first condition if it's in the current year
  
  if(dates[0].getUTCFullYear() === year && dates[1] - dates[0] < yearInMilliseconds){
    
    converted[0] = converted[0].substring(0, converted[0].indexOf(","));
    
  }
  
   //second condition , if the range is within an year
 if( dates[1] - dates[0] < yearInMilliseconds){
   
  converted[1] = converted[1].substring(0, converted[1].indexOf(","));
   
 }
  
  //third condition , is the same month of the same year
  
  if(dates[0].getUTCMonth() === dates[1].getUTCMonth() && dates[0].getUTCFullYear() === dates[1].getUTCFullYear()){
    
   converted[1] = converted[1].substring(converted[1].indexOf(" ") + 1);
    
  }
  
  
  
  
   return converted;
}

makeFriendlyDates(["2018-01-13", "2018-01-13"]);

```

my problem is with the same date solution... i dont get it what i have to display.

**Comment by erictleung** [comment]
@Spartano what needs to be displayed for the same date is suggested to you in the tests:

> `makeFriendlyDates(["2018-01-13", "2018-01-13"])` should return `["January 13th, 2018"]`

Happy coding!

**Comment by Spartano** [comment]
i understand that, but it isn't explained in the problem requirements. Maybe should be added an extra requirement, for clarity sake.  For me personaly, when i saw the suggestion it make me think that my understanding of the problem was wrong. Thanks. Bye.
