### ISSUE TITLE
Allowed to pass Get Geolocation Data waypoint, but no prompt appears

### ISSUE THREAD

**Issue by lahowitt** [FreeCodeCamp/FreeCodeCamp#8693]
Challenge [Get Geolocation Data](https://www.freecodecamp.com/challenges/get-geolocation-data) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I pass the Waypoint, but no prompt actually appears. From what I can tell, this is because safari and chrome both deny this user request. 

My code:

``` html

<script>
  // Only change code below this line.

  if(navigator.geoLocation){
    navigator.geolocation.getCurrentPosition(function(position){
      $("#data").html("latitude:"+position.coords.latitude+"<br> longitude:"+position.coords.longitude);
    });
  }

  // Only change code above this line.
</script>
<div id = "data">
  <h4>You are here:</h4>

</div>

```

**Comment by raisedadead** [comment]
Thanks for reporting this. Yup looks like these XHR are getting blocked.

![image](https://cloud.githubusercontent.com/assets/1884376/15348113/7785c86e-1ce5-11e6-9fd6-db476a0512ac.png)

**Comment by QuincyLarson** [comment]
@raisedadead @lahowitt is this still an issue?

**Comment by raisedadead** [comment]
Closing as stale, we haven't seen this issue pop up recently.
