### ISSUE TITLE
can not be escaped

### ISSUE THREAD

**Issue by RihuaChen** [FreeCodeCamp/FreeCodeCamp#8698]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22%5C%5Cn%5Ct%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "\\n\t"; // Change this line



```
Others can't be escaped to the right output, like "\n" or "\t",can't be escaped.

**Comment by edwinfrancisd** [comment]
This should be the changed code for that challenge
`var myStr = "\\ \t \t \r \n";`
May I know what's wrong with it???
;-)

**Comment by erictleung** [comment]
@RihuaChen thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
