### ISSUE TITLE
Update incorrect (older) reference to "Field Guide"

### ISSUE THREAD

**Issue by sunnyspecs** [FreeCodeCamp/freecodecamp#870]
I don't know if this qualifies for a bug or not, but this page wrongly refers to "Field Guide" in navigation menu which seemingly has been changed to "Guide" only. Just felt like reporting it for update.
http://www.freecodecamp.com/challenges/waypoint-browse-our-field-guide

**Comment by BerkeleyTrue** [comment]
@sunnyspecs Thanks for the letting us know! This typo will be fixed.

**Comment by QuincyLarson** [comment]
Thanks - I've fixed this.

**Comment by sunnyspecs** [comment]
Thanks.
