### ISSUE TITLE
word Blanks

### ISSUE THREAD

**Issue by Pujachaubey** [FreeCodeCamp/FreeCodeCamp#8700]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%0A%20%20string.result%20%3D%20myAdjective%20%2B%20%22%20%22%20%2B%20myNoun%20%2B%20%22%20%22%20%2B%20myVerb%20%2B%20%22%20%22%20%2B%20myAdverb%3B%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
 
  string.result = myAdjective + " " + myNoun + " " + myVerb + " " + myAdverb;
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by theflametrooper** [comment]
`ReferenceError: string is not defined`

Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by Shraddha99** [comment]
@Pujachaubey  your code worked for me .

**Comment by ysroels** [comment]
**This Should Work:**
`function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line

  string.result = myAdjective + " " + myNoun + " " + myVerb + " " + myAdverb;
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");`
happy coding

**Comment by ysroels** [comment]
sorry: 
leave out string.
like this: 
result = myAdjective + " " + myNoun + " " + myVerb + " " + myAdverb;
