### ISSUE TITLE
Join our Forum Challenge and Forum links not working properly for HTTPS connections

### ISSUE THREAD

**Issue by Carnubak** [FreeCodeCamp/FreeCodeCamp#8703]
#### Join our Forum Challenge
https://www.freecodecamp.com/challenges/join-our-forum

#### Issue Description
In the new Join our Forum Challenge, the provided link to open the Forums doesn't work, and the challenge does not complete after clicking "Go to my next step".
The issue seems to originate in a misconfiguration in the Forum server. Since the target links are relative to the URL root (they start with //, as seen in 704f757cbb3749889778584a8e1d91a6f630fbd0), they try to connect using the HTTPS protocol when signed-in, but the Forum only supports HTTP connections. I get an Error 521 from CloudFlare when trying to connect via HTTPS.
Even after signing into the Forum, I can only navigate them using HTTP, whereas, I would expect to be using HTTPS for an authenticated session.

#### Browser Information

* Browser Name, Version: Firefox 46.0.1
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![forum error](https://cloud.githubusercontent.com/assets/9649010/15374346/3f561346-1d20-11e6-84ed-73400ddf6a19.png)

**Comment by theflametrooper** [comment]
We need to change the link from `https` to `http` or else @BerkeleyTrue can we setup `https` for the forum?
