### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tarektarho** [FreeCodeCamp/FreeCodeCamp#8704]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%5C%22double%20quotes%5C%22%20%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr= "I am a \"double quoted\" string inside\"double quotes\" ";



```

**Comment by shadowfool** [comment]
You are missing a space after inside.

Please close this as it is not a bug.

**Comment by raisedadead** [comment]
@tarektarho: @shadowfool is correct.

Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!

@shadowfool thanks a lot for helping, you can just direct people to the appropriate chat rooms.

**Comment by tarektarho** [comment]
yes thank you  guys
