### ISSUE TITLE
First box unchecked at html waypoint 38

### ISSUE THREAD

**Issue by rhicooper** [FreeCodeCamp/freecodecamp#871]
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue. I'm not sure how to reproduce it as I've only played with it a few times, but the code is written identically from line to line but it's not working correctly on the page for the first item.  The rest are all fine.  
![screenshot 1](https://cloud.githubusercontent.com/assets/12600135/8049314/adab2796-0e2b-11e5-8512-8006a79fc9b1.png)

**Comment by BerkeleyTrue** [comment]
@rhicooper Thanks for the PR!

This is not an issue with the text. Only one Radio button can be checked at a time. If you check all of them, the last radio button checked will be on by default. There should only be one radio button and one checkbox checked for this test.

Good luck with the rest of your challenges!

**Comment by rhicooper** [comment]
Thanks for clearing that up.
