### ISSUE TITLE
Basic Algorith Scripting: Seek and Destroy - Tests not passing

### ISSUE THREAD

**Issue by jaisonv** [FreeCodeCamp/FreeCodeCamp#8712]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%0A%20%20var%20cleaned%20%3D%20arguments%5B0%5D%3B%0A%0A%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%20arguments.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20cleaned%20%3D%20cleaned.filter(different%2C%20arguments%5Bi%5D)%3B%0A%20%20%7D%0A%0A%20%20return%20cleaned%3B%0A%7D%0A%0Afunction%20different(value)%20%7B%0A%20%20return%20value%20!%3D%3D%20this%3B%0A%7D%0A%0Adestroyer(%5B%22tree%22%2C%20%22hamburger%22%2C%2053%5D%2C%20%22tree%22%2C%2053)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  // Remove all the values

  var cleaned = arguments[0];

  for (var i = 1; i < arguments.length; i++) {
    cleaned = cleaned.filter(different, arguments[i]);
  }

  return cleaned;
}

function different(value) {
  return value !== this;
}

destroyer(["tree", "hamburger", 53], "tree", 53);
```
My code above works and produces the results as expected, but it doesn't pass any tests.

Screenshots:

![screen shot 2016-05-18 at 10 59 13 pm](https://cloud.githubusercontent.com/assets/2567823/15380448/f7f9f2f6-1d4c-11e6-837f-572368be4737.png)
![screen shot 2016-05-18 at 11 00 04 pm](https://cloud.githubusercontent.com/assets/2567823/15380449/f7fc0ba4-1d4c-11e6-82bd-66f336884c14.png)
![screen shot 2016-05-18 at 11 00 41 pm](https://cloud.githubusercontent.com/assets/2567823/15380446/f7f72cba-1d4c-11e6-929d-d285e700b7fc.png)
![screen shot 2016-05-18 at 11 01 13 pm](https://cloud.githubusercontent.com/assets/2567823/15380445/f7f71022-1d4c-11e6-81cc-34448598652f.png)
![screen shot 2016-05-18 at 11 01 39 pm](https://cloud.githubusercontent.com/assets/2567823/15380447/f7f74d62-1d4c-11e6-9ed0-5797c423b34c.png)

**Comment by erictleung** [comment]
Closing as duplicate #8697.

**Comment by erictleung** [comment]
@jaisonv I don't know if you saw, but [here's an explanation](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8697#issuecomment-220247997) for the problem you were facing. Happy coding!

**Comment by jaisonv** [comment]
@erictleung thank you. I just saw it. they say to use **'use strict';**
It gave a warning but passed. hehe
