### ISSUE TITLE
Selecting with Switch Statements missing code tags in tests

### ISSUE THREAD

**Issue by venkyafhs** [FreeCodeCamp/FreeCodeCamp#8713]
Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements#?solution=%0Afunction%20caseInSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%20%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20switch(answer)%20%7B%0A%20%20%0A%20%20%20%20%20%20case%201%3A%0A%20%20%20%20%20%20console.log(%22alpha%22)%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20case%202%3A%0A%20%20%20%20%20%20console.log(%22beta%22)%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20case%203%3A%0A%20%20%20%20%20%20console.log(%22gamma%22)%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20case%204%3A%0A%20%20%20%20%20%20console.log(%22delta%22)%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20default%3A%0A%20%20%20%7D%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AcaseInSwitch(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function caseInSwitch(val) {
  var answer = " ";
  // Only change code below this line
   switch(answer) {
  
      case 1:
      console.log("alpha");
      break;
      
      case 2:
      console.log("beta");
      break;
      
      case 3:
      console.log("gamma");
      break;
      
      case 4:
      console.log("delta");
      break;
      
    default:
   } 
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);


```What to value to assign to var answer=" ";

**Comment by erictleung** [comment]
@venkyafhs thanks for the issue. I'm not sure what your particular issue is but I assume it is the issue with the tests not rendering correctly.

![image](https://cloud.githubusercontent.com/assets/2754821/15383320/00461378-1d47-11e6-83b0-28c6d2e992f8.png)

Currently, the `<code>` tags are not closed. So these:

```json
...'message: <code>caseInSwitch(1) should have a value of \"alpha\"
```

need to be

```json
...'message: <code>caseInSwitch(1)</code> should have a value of \"alpha\"
```

for the first four tests.

These [four lines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3459-L3462) need to be changed.

**Comment by raisedadead** [comment]
@erictleung you rock. Just when we needed more first timers issues! :sparkles:

**Comment by ankitkachru** [comment]
@raisedadead I think you should try switching the 'val' (switch(val)), and then assigning 'answer' the values of alpha, beta...

**Comment by InsomniacSabbir** [comment]
I will work on this from now. Is that ok ? Please let me know if there is any conflict.
Thank you.

**Comment by theflametrooper** [comment]
@InsomniacSabbir Awesome!

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by InsomniacSabbir** [comment]
Hello,
I have added the </code> as mentioned in the previous comment. But the problem still remains. Can you please help me to find the code where the view is generated.
Thank you.

![screen](https://cloud.githubusercontent.com/assets/5733224/15430865/0598aa56-1ec9-11e6-9889-6adcd0b8684a.png)

**Comment by theflametrooper** [comment]
@InsomniacSabbir You need to run `gulp` to view changes.

**Comment by zelalem19** [comment]
you do not have to console.log, think about using answer as your return value. i will give you the first one as an example, your switch should be val not answer but your returning answer 
switch(val) {

      case 1:
     answer= ("alpha");
      break;
//do the the same thing for what you have left  
    }
 // Only change code above this line  
  return answer;  
}
this should help

**Comment by StenNick** [comment]
function caseInSwitch(val) {
  var answer = val; //here need set answer = val  and your code work!) 
  // Only change code below this line
   switch (answer) {
    case 1:
    answer = "alpha";
      break;
    case 2:
  answer = "beta";
      break;
    case 3:
      answer = "gamma";
      break;
    case 4: 
      answer = "delta";
      break;

  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(2);

**Comment by git123hub** [comment]
return "beta"
----- 原始邮件 -----
发件人：StenNick <notifications@github.com>
收件人：FreeCodeCamp/FreeCodeCamp <FreeCodeCamp@noreply.github.com>
主题：Re: [FreeCodeCamp/FreeCodeCamp] Selecting with Switch Statements missing code tags in tests (#8713)
日期：2016年08月08日 17点41分

function caseInSwitch(val) {

  var answer = val; //here need set answer = val  and your code work!) 

  // Only change code below this line

   switch (answer) {

    case 1:

    answer = "alpha";

      break;

    case 2:

  answer = "beta";

      break;

    case 3:

      answer = "gamma";

      break;

    case 4: 

      answer = "delta";

      break;

}

// Only change code above this line


  return answer;


}

// Change this value to test

caseInSwitch(2);

&mdash;

**Comment by majedmahmood27** [comment]
also your switch should be switch(val) not answer

**Comment by iameuanmackay** [comment]
Gah! I'm stuck, and not too sure what I'm missing on this... Any pointers, would be much appreciated...

`function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line

  switch (val){
    case "1": answer = ("alpha");
     break;
    case "2": answer = "beta";
     break;
    case "3": answer = "gamma";
     break;
    case "4": answer = "delta";
     break;
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);`

**Comment by texas2010** [comment]
@iameuanmackay 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by cara06** [comment]
All you need do is get the code:


function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
  case 1:
   answer= "alpha";
    break;
  case 2:
    answer= "beta";
    break;
  case 3:
    answer= "gamma";
    break;
  case 4:
    answer="delta";
    break;
  
  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);

**Comment by raisedadead** [comment]
@cara06 please provide all asssitance in the chat rooms.

**Comment by janapanaramsai** [comment]
`
function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case 1:
      answer = "alpha";
      break;
    case 2:
      answer = "beta";
      break;
    case 3:
      answer = "gamma";
      break;
    case 4:
      answer = "delta";
      break;
  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);
`

**Comment by MihaelaMarinca** [comment]
just one thing: the **default** should always be there in a switch statement.

**Comment by r1card0amr** [comment]
you should not use console.log. At the bottom the return statement is equal to answer (return answer;). There's a hint. Good luck.

**Comment by NdegwaJulius** [comment]
function caseInSwitch(val) {
var answer = val;
// Only change code below this line
switch (answer){
case 1:
answer = "alpha";

  break;
  
 case 2:
  answer = "beta";
  break;
  
  case 3:
  answer = "gamma";
  
  break;
  
 case 4:
  answer = "delta";
  break;
  
  default:

}
// Only change code above this line
return answer;
}

// Change this value to test
caseInSwitch(3);
