### ISSUE TITLE
City listed in wrong state

### ISSUE THREAD

**Issue by crowchirp** [FreeCodeCamp/FreeCodeCamp#8714]
#### Challenge Name
City listed in wrong state
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/LocalGroups-List

#### Issue Description
Indian city 'Noida' is listed in 'Haryana' State, whereas 'Noida' is in 'Uttar Pradesh'

 
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/14236753/15383257/5d599e78-1daf-11e6-929c-a753ab63ed48.png)

**Comment by raisedadead** [comment]
Hi @crowchirp,

Thanks for reporting this.

Closing in favor of FreeCodeCamp/wiki#984
