### ISSUE TITLE
Problem with the Exact Change challenge

### ISSUE THREAD

**Issue by unc0mm0n** [FreeCodeCamp/FreeCodeCamp#8719]
Challenge [Exact Change](https://www.freecodecamp.com/challenges/exact-change#?solution=%0Afunction%20checkCashRegister(price%2C%20cash%2C%20cid)%20%7B%0A%20%20var%20change%3B%0A%20%20%2F%2F%20Here%20is%20your%20change%2C%20ma'am.%0A%20%20return%20change%3B%0A%7D%0A%0A%2F%2F%20Example%20cash-in-drawer%20array%3A%0A%2F%2F%20%5B%5B%22PENNY%22%2C%201.01%5D%2C%0A%2F%2F%20%5B%22NICKEL%22%2C%202.05%5D%2C%0A%2F%2F%20%5B%22DIME%22%2C%203.10%5D%2C%0A%2F%2F%20%5B%22QUARTER%22%2C%204.25%5D%2C%0A%2F%2F%20%5B%22ONE%22%2C%2090.00%5D%2C%0A%2F%2F%20%5B%22FIVE%22%2C%2055.00%5D%2C%0A%2F%2F%20%5B%22TEN%22%2C%2020.00%5D%2C%0A%2F%2F%20%5B%22TWENTY%22%2C%2060.00%5D%2C%0A%2F%2F%20%5B%22ONE%20HUNDRED%22%2C%20100.00%5D%5D%0A%0AcheckCashRegister(19.50%2C%2020.00%2C%20%5B%5B%22PENNY%22%2C%201.01%5D%2C%20%5B%22NICKEL%22%2C%202.05%5D%2C%20%5B%22DIME%22%2C%203.10%5D%2C%20%5B%22QUARTER%22%2C%204.25%5D%2C%20%5B%22ONE%22%2C%2090.00%5D%2C%20%5B%22FIVE%22%2C%2055.00%5D%2C%20%5B%22TEN%22%2C%2020.00%5D%2C%20%5B%22TWENTY%22%2C%2060.00%5D%2C%20%5B%22ONE%20HUNDRED%22%2C%20100.00%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Not a bug, just I think the challenge have a logical problem in it.
At no point do you tell the cash register what the values of each coin are, making something like giving a change of 150 from two bills of 100 and one bill of 50 impossible. i.e.
```
checkCashRegister(5, 20, [["FIVE", 5],["TEN", 20]]) //rest being 0
```
is impossible with the information given in the question, and the behavior in that case is not defined in the question.
It's easy enough to hard-code the values in the question, but it does beat the point of passing the cid as part of the function.

**Comment by erictleung** [comment]
@unc0mm0n the passed in values values in `cid` are the value of how much of that currency are left where each array (e.g. `["PENNY", 0.50]`) has the currency type (e.g. `"PENNY"`) and the currency value of those currency type (e.g. `0.50`, which means I have 50 cents worth of pennies). For your example, you should return `[["FIVE", 5.00], ["TEN", 10.00]]`. If you have more questions with this challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by unc0mm0n** [comment]
But who said TEN is worth 10$? Certainly the exercise didn't, it just said "build a generic register which accepts currency type and amount of money in that currency". Which means it will completely fail if used anywhere else, or if someone who doesn't know how much a penny is worth tries to solve it.

This is not a question and really has nothing to do with the help room, it's just a problem with the definition of the question...

**Comment by erictleung** [comment]
@unc0mm0n ah I see. I didn't fully understand your issue the first time I read it. We could make it more explicit saying that the function being made is for US currency. This should erase any confusion on it being a "generic register".

**Comment by BerkeleyTrue** [comment]
closing in favor of #10097
