### ISSUE TITLE
"Reference error: Fahrenheit not defined" shows up before starting challenge

### ISSUE THREAD

**Issue by TrentHand** [FreeCodeCamp/FreeCodeCamp#8721]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20a%3D32%3B%0A%20%20var%20b%3D9%2F5%3B%0A%20%20var%20c%3D30%3B%0A%20%20%0A%20%20var%20d%3D%20a%20%2B%20b%20*%20c%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 7978.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertToF(celsius) {
  // Only change code below this line
  var a=32;
  var b=9/5;
  var c=30;
  
  var d= a + b * c;
  
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);

```

**Comment by erictleung** [comment]
@TrentHand thanks for the issue. The instructions do say:

> Create a variable `fahrenheit` and apply the algorithm to assign it the corresponding temperature in Fahrenheit.

So although the instructions do say to create the variable, the fact that you can't see any of the tests before you write the code may seem alarming and different from all the other challenges.

cc/ @FreeCodeCamp/issue-moderators should we at least define the variable `fahrenheit` for them before they start coding? Considering we haven't introduced functions at this point, I think this would be helpful. But I'm open to suggestions.

**Comment by raisedadead** [comment]
@erictleung agreed. looks like this is an oversight no one saw earlier. But they have been introduced to variables at least, nevertheless, I guess we should be defining it.

**Comment by erictleung** [comment]
Anyone wanting to fix this needs to change the lines around [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L873) to:

```
"function convertToF(celsius) {",
"  var fahrenheit;",
"  // Only change code below this line",
"  ",
"  ",
"  // Only change code above this line",
"  return fahrenheit;",
"}",
```

And you'll also to change the instructions to be consistent to something like:

> You are given a variable `celsius` representing a temperature in Celsius. Use the variable `fahrenheit` already defined and apply the algorithm to assign it the corresponding temperature in Fahrenheit.

**Comment by BoDonkey** [comment]
@erictleung Just curious, since the fix is clear and you essentially just outlined what had to be done, are you leaving this open to help new people get their first PR approved? Please note - I'm a complete newbie who hasn't submitted any PR and want to make sure I understand what is going on. Thanks!

**Comment by theflametrooper** [comment]
@BoDonkey That is correct. This PR is for `first-timers-only`. Seeing as you haven't created a PR yet, why not make this your first one :tada: 

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by BoDonkey** [comment]
I'll start working on it after work or first thing tomorrow morning! I actually remember this from when I was going through this section.

**Comment by TrentHand** [comment]
Hi everyone!  The error is still showing up this morning.  Is this request still open?

**Comment by BoDonkey** [comment]
Huh, that is odd - it shows up correctly in the seed [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L873).
Not sure why it isn't coming through online. I'm too much of a newbie to troubleshoot further, but I'll be listening for people to chime in.

**Comment by raisedadead** [comment]
Hi @TrentHand and @BoDonkey the code is yet to reach the main website, it happens every couple of days when we push a bunch of fixes and updates together to the main site.

We request you to bear with us meanwhile.

Thanks and Happy Coding!

**Comment by ArmantHitchcock** [comment]
I believe the code is incomplete:
function convertToF(celsius) {
  var fahrenheit;                              

**NB: var fahrenheit isn't assigned to the parameter "celsius" of the above function, and as the instruction below states the the student shouldn't edit it thus the function won't work**
  
// Only change code below this line
  

  // Only change code above this line
  return fahrenheit;
}

`<hr>`

This is my example:

function convertToF(celsius) {
  var fahrenheit = celsius;
  // Only change code below this line
  fahrenheit *=1.8;
  fahrenheit +=32;
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);

**Comment by nellee24** [comment]
function convertToF(celsius) {
  var fahrenheit;
  // Only change code below this line
  
  fahrenheit = (celsius * 1.8) + 32;
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);

**Comment by dwd2010** [comment]
@nellee24 
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by TinaLittlemoon** [comment]
I think that sometimes it really helps to see the correct code. Of course some explanations and the way how to get there would be useful too. If everyone would post their code snippets here with asking for help, this forum would be probably a mess. 
I prefer asking for further explanations if there should be some remaining, however often after seeing the code, everything becomes clearer :) usually the question is unclear or too difficult to get although the code in the end appears to be very simple :)

**Comment by nellee24** [comment]
@texas2010 
Im trying help and simplified the code of @ArmantHitchcock. :)

**Comment by nellee24** [comment]
@texas2010 
Im trying to help and simplified the code of @ArmantHitchcock. :)

**Comment by Mohamedsalmaan** [comment]
Challenge Convert Celsius to Fahrenheit has an issue.
 i don't know how to solve this challenge

**Comment by Diesirae91** [comment]
you have to modify the text above the line, against the instructions.  celsius is not defined and will spit out an error. 

var fahrenheit = celsius;
