### ISSUE TITLE
Show Relationships with a Force Directed Graph broken after deprecated Camper news API.

### ISSUE THREAD

**Issue by kristenmthayer** [FreeCodeCamp/FreeCodeCamp#8722]
Challenge [Show Relationships with a Force Directed Graph](https://www.freecodecamp.com/challenges/show-relationships-with-a-force-directed-graph) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by theflametrooper** [comment]
This was broken in #8690. cc/ @FreeCodeCamp/wiki-mods

**Comment by kristenmthayer** [comment]
Thanks for letting me know :-) Sorry to send a duplicate.

**Comment by theflametrooper** [comment]
@kristenmthayer Np :smiley:, It's not a duplicate -- this issue hasn't been brought up yet.

**Comment by kristenmthayer** [comment]
Oh, I see :-)

**Comment by raisedadead** [comment]
> Should we add the API again or should we immediately start work on the new dataset? 

The later. We need a new static data set that can be fetched, could be JSON (data hard coded).

**Comment by DealPete** [comment]
I did this challenge recently (http://codepen.io/DealPete/pen/GZPgpG), and I used country contiguity data I got from Correlates of War. We could use that as an example.

**Comment by kristenmthayer** [comment]
@DealPete your example is really cool! But I did mine with the FCC data, so mine is broken :-(

**Comment by DealPete** [comment]
Thanks @kristenmthayer, I started mine after they had discontinued Camper News, so I knew I'd have to use new data.

**Comment by raisedadead** [comment]
@DealPete Thanks a lot for the pen, and the alternate data set. Do you think you can make a PR to update the challenge.

I have forked your pen under FCC and tested it with `https` and it works, if you do update the challenge, then use the below as the link in the challenge:

https://codepen.io/FreeCodeCamp/pen/xVopBo

**Comment by raisedadead** [comment]
I will take care of updating the Pen's title once PR is ready and merged.

**Comment by kristenmthayer** [comment]
@raisedadead @theflametrooper @DealPete any chance one of you has a copy of the old data set somewhere? If the challenge gets changed, I would still want my graph to work, and it would be easier to copy an existing set rather than reverse engineering it. Thanks :-)

**Comment by kaunglay** [comment]
#7082

**Comment by kaunglay** [comment]
Ok ok good luck.com

**Comment by kaunglay** [comment]
Ok ok good luck.com

**Comment by kaunglay** [comment]
#8772

**Comment by kristenmthayer** [comment]
Okay, hard-coded some fake data in my graph so it works again, if you want to borrow/use it, feel free: http://codepen.io/KMT/pen/dMqgrO. Have a good day!

**Comment by sludge256** [comment]
@kristenmthayer I think I have a copy of the data somewhere if you would prefer. I'll try to remember to look for it when I get home.

**Comment by kristenmthayer** [comment]
@sludge256 thanks! That would be great, if you have it, mine is pretty obviously invented.

**Comment by sludge256** [comment]
@kristenmthayer Sorry for the delay. I don't know how much data this file contains but it's what I have.
[campernews_archive_04052016.txt](https://github.com/FreeCodeCamp/FreeCodeCamp/files/288816/campernews_archive_04052016.txt)

**Comment by kristenmthayer** [comment]
@sludge256  thanks! I really appreciate that!!
