### ISSUE TITLE
Chunky Monkey, 3 dimensional arrays?

### ISSUE THREAD

**Issue by noates** [FreeCodeCamp/FreeCodeCamp#8724]
#### Issue Description

The Chunky Monkey challenge asks for you to write a function that... "returns them as a  2 dimensional array."

But some of the test cases appear to require a 3 dimensional array to be returned.

 Are these following 2 return values actually 2-D  or 3-D  arrays?:

chunkArrayInGroups([0, 1, 2, 3, 4, 5, 6, 7, 8], 4) should return [[0, 1, 2, 3], [4, 5, 6, 7], [8]].

chunkArrayInGroups([0, 1, 2, 3, 4, 5, 6], 3) should return [[0, 1, 2], [3, 4, 5], [6]].

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet:  desktop/laptop

**Comment by BerkeleyTrue** [comment]
Hey @noates 

The example you gave are all examples of 2D arrays. Imagine that every item in the top level array defines the values of a single row. So the length of the top level array defines the number of rows, and the length of the nested arrays defines the number of columns. 

```
0 1 2 3
4 5 6 7
8

0 1 2
3 4 5
6
```

It's also perfectly valid to define them the reverse way, but the important part is that all the tests expect 2D arrays, not 3D.

Happy Coding!
