### ISSUE TITLE
Forgetting a semicolon gives a type error that neither console nor node gives

### ISSUE THREAD

**Issue by bradarv90** [FreeCodeCamp/FreeCodeCamp#8729]
Challenge [Make Instances of Objects with a Constructor Function](https://www.freecodecamp.com/challenges/make-instances-of-objects-with-a-constructor-function#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0AmyCar.nickname%20%3D%20%22POTATO%22%0A%2F%2FmyCar.nickname%20%3D%20%22twin%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.

My code:
```javascript

var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var myCar = new Car();
myCar.nickname = "nickname"
```
Running this code outputs

```
TypeError: "nickname" is not a function
```

I ran this code both through the console in Chrome and with the node REPL and neither throw errors.

**Comment by BerkeleyTrue** [comment]
Always include semicolons.

Internally we append some code to yours. Because new lines are meaningless in JavaScript the next line of code is seen as a continuation of yours. Since we append an IIFE, your last statement is interpreted as a function call. 

Happy Coding
