### ISSUE TITLE
Grammatical error in "Waypoint: Specify How Fonts Should Degrade"

### ISSUE THREAD

**Issue by silentflea** [FreeCodeCamp/freecodecamp#873]
Challenge http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade has an issue.

In the third paragraph from the top, it says "For example, if you wanted an element to use the "Helvetica" font, but also degrade to the "Sans-Serif" font when "Helvetica" wasn't available, you could do use this CSS style: p { font-family: Helvetica, Sans-Serif; }."

"you could DO use this..." - is the error.

You can omit "DO" from this sentence.

**Comment by QuincyLarson** [comment]
Thanks for catching this. I've fixed it!

**Comment by silentflea** [comment]
So I visited the page again, and the "do" is still there. Just a heads up.

**Comment by BerkeleyTrue** [comment]
It may have not been pushed up to production yet but it will get there eventually.

**Comment by silentflea** [comment]
I see, thanks.
