### ISSUE TITLE
Can't Run the test ??!

### ISSUE THREAD

**Issue by SherifAbdelfattah** [FreeCodeCamp/FreeCodeCamp#8730]
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function(){
  $("button").addClass("animated");
  $(".btn").addclass("shake");
  $("#target1").addClass("animated shake btn-primary");


  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by raisedadead** [comment]
Thanks for reporting this. Unfortunately your code is not correct.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!

**Comment by FreedomOpenProjects** [comment]
@raisedadead  You did knew where his code is not correct. Can you correct it for us?

Happy coding!

**Comment by sludge256** [comment]
@FreedomOpenProjects We don't provide coding help via GitHub issues. They are reserved for site issues and discussions. It's better to ask in the appropriate help room (that's why there's a help button on each challenge page) to keep the repository clear of posts unrelated the functionality of the site.

**Comment by FreedomOpenProjects** [comment]
I did it myself. So proud of it. But why don't you leave him some correction? It doesn't matter for helping someone despite proper place
