### ISSUE TITLE
Challenge [Use Clockwise Notation to Specify the Padding of an Element]

### ISSUE THREAD

**Issue by daz1uk** [FreeCodeCamp/FreeCodeCamp#8731]
Hi,

I believe that I have specified the padding correctly but can not proceed.

Challenge [Use Clockwise Notation to Specify the Padding of an Element](https://www.freecodecamp.com/challenges/use-clockwise-notation-to-specify-the-padding-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 20px 40px 20px 40px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px 40px 20px 40px;
  }

  .green-box {
    background-color: green;
    padding: 40px, 20px, 20px, 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by coolsday** [comment]
i got the same problem here

**Comment by AhmedTunuLashku** [comment]
+1

**Comment by StevenKing-Profile** [comment]
Your answer has commas - remove them.
