### ISSUE TITLE
how come when i hit run test it only bounce the buttons but does not go on to the next one? O and by the way i did reload the hole pageso i dont know what to do.

### ISSUE THREAD

**Issue by the18wats** [FreeCodeCamp/FreeCodeCamp#8734]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@the18wats thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by the18wats** [comment]
o good idea thxs

**Comment by the18wats** [comment]
there's a problem there it says this Secure Connection Failed
