### ISSUE TITLE
Pressing 'Enter' works wrong with multi select

### ISSUE THREAD

**Issue by MikeYermolayev** [FreeCodeCamp/FreeCodeCamp#8736]
#### Challenge Name
All challenges in which there is a lot of code

#### Issue Description
When I use multi select Enter key press works only for the first cursor.
But that's actual only for the first key press. Pressing more times works OK.
Please look at video for more details.

#### Video
http://screencast.com/t/UKxxPMyRoH

#### Browser Information
* Browser Name, Version:  Google Chrome Canary 52.0.2743.0 (64-bit)
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

**Comment by ltegman** [comment]
I actually just opened up a PR to update CodeMirror and it will solve this problem once it is merged and deployed :smile:

**Comment by MikeYermolayev** [comment]
@ltegman cool! Thanks.
