### ISSUE TITLE
Kitten image error

### ISSUE THREAD

**Issue by axelcandia** [FreeCodeCamp/FreeCodeCamp#8739]
I wrote this
<img scr="http://bit.ly/fcc-relaxing-cat"> but it still gives me an error saying 
"Your image should have a src attribute that points to the kitten image."

**Comment by erictleung** [comment]
@axelcandia thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by rx290** [comment]
well things are worst here can't skip the challenge ._.

**Comment by esaky** [comment]
Getting the same error @erictleung

**Comment by erictleung** [comment]
@esaky thanks for the comment, but if you get stuck or have questions with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) to help you debug your error. Happy coding!

**Comment by esaky** [comment]
Ok, got it. But for bugs i should ask ! From yesterday i getting this error, one of the user send me the right code( I used the same) - not working.
https://www.freecodecamp.com/challenges/warn-your-users-of-a-dangerous-action
All of your Bootstrap buttons should have the btn and btn-block classes.
Your new button should have the class btn-danger.
Make sure all your button elements have a closing tag.
This is my Code:
# <button class="btn btn-block btn-primary">Like</button>
<button class="btn btn-block btn-danger">Delete</button>

I need to learn and go to next challenge.

**Comment by simikhurana** [comment]
it is giving me error
"Your image should have a src attribute that points to the kitten image."

**Comment by mushaid01** [comment]
<h2>CatPhotoApp</h2>
<main>

  <img src="https://www.bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">

  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>

**Comment by mushaid01** [comment]
<h2>CatPhotoApp</h2>
<main>

  <img src="https://www.bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">

  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>

**Comment by mushaid01** [comment]
<h2>CatPhotoApp</p>
<main>
<img src="https://www.bit.ly/fcc-relaxing-cat alt=" relaxing cat">
<p>Kitty .........</p>
<p>lorem.....</p>
</main>
