### ISSUE TITLE
Input field missing to input your CodePen Link into.

### ISSUE THREAD

**Issue by danraley** [FreeCodeCamp/freecodecamp#874]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
There is no input field to enter the link to your codepen when you click the "I've completed this challenge (ctrl + enter)" button.

**Comment by QuincyLarson** [comment]
I've updated the copy on this. Thanks for pointing out the discrepancy.
