### ISSUE TITLE
The Golf Course. The code for comparing par go home is broken. Images are attached

### ISSUE THREAD

**Issue by zayy862** [FreeCodeCamp/FreeCodeCamp#8741]
![screenshot from 2016-05-20 20 32 21](https://cloud.githubusercontent.com/assets/11012246/15445730/d1c5439a-1eca-11e6-8d8c-7bb019603eb1.png)
![screenshot from 2016-05-20 20 32 35](https://cloud.githubusercontent.com/assets/11012246/15445729/d1c3bf7a-1eca-11e6-9e7e-dd96dacc504c.png)

Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(strokes%20%3D%3D%201)%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3C%3D%20par-2)%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par%20-%201)%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par)%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par%20%2B%201)%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par%20%2B%202)%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3E%3D%20par%20%2B%203)%7B%0A%20%20%20%20return%20%22Go%20Home%22%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20%22Change%20Me%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(4%2C%207)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes == 1){
    return "Hole-in-one!";
  }
  else if(strokes <= par-2){
    return "Eagle";
  }
  else if(strokes == par - 1){
    return "Birdie";
  }
  else if(strokes == par){
    return "Par";
  }
  else if(strokes == par + 1){
    return "Bogey";
  }
  else if(strokes == par + 2){
    return "Double Bogey";
  }
  else if(strokes >= par + 3){
    return "Go Home";
  }
  else{
    return "Change Me";
  }
  // Only change code above this line
}

// Change these values to test
golfScore(4, 7);

```

**Comment by erictleung** [comment]
@zayy862 thanks for the issue the test works perfectly. Please refer back to the table. You'll find the answer to your problem there. Happy coding!

![image](https://cloud.githubusercontent.com/assets/2754821/15445740/84759758-1eba-11e6-85f7-91a512d3dcfd.png)
