### ISSUE TITLE
s/jade/pug/g

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#8743]
replace jade package with newly renamed pug.
rename jade helper functions to pug helper functions
replace .jade extensions with .pug   🐶 

There may be other things that should be replaced that I'm missing

**Comment by zaclem01** [comment]
So just the package.json, templates for the views, and functions?

How would you test to ensure all views have the correct extension?

If it isn't more technical than that, I could probably take it on.

**Comment by atjonathan** [comment]
@zaclem01 This has already been addressed by #8827

**Comment by QuincyLarson** [comment]
We will merge the PR that remedies this as soon as we ship staging.

**Comment by BerkeleyTrue** [comment]
The PR is waiting on pug to come out of beta.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue OK - thanks for the clarification.

**Comment by BerkeleyTrue** [comment]
This issue is blocked until pug comes out of beta.

**Comment by BerkeleyTrue** [comment]
pug has moved to release candidate. Hopeful we will see a release soon
