### ISSUE TITLE
Prevent wiki iframe from redirect to other domains

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#8745]
It's possible to navigate with the wiki iframe to other domains (for example, the python docs). This leads to confusion and a broken experience. Code should be added to prevent this from happening on the main site. 

related to https://github.com/FreeCodeCamp/wiki-generator/issues/37

**Comment by raisedadead** [comment]
No longer relevant. Closing.
