### ISSUE TITLE
Condense arrays with reduce: Better variable naming 

### ISSUE THREAD

**Issue by dev-seahouse** [FreeCodeCamp/FreeCodeCamp#8748]
Challenge [Condense arrays with reduce](https://www.freecodecamp.com/challenges/condense-arrays-with-reduce#?solution=%0Avar%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0Avar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AsingleVal%20%3D%20array.reduce(function(total%2C%20currentVal)%7B%0A%20%20return%20total%20%2B%20currentVal%3B%20%2F%2F%20previousVal%20is%20the%20accumulator%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This is not quite a issue, but i think that if the variable "previousVal" is changed to "total" or "sum" would help others better understand and avoid confusion. As in this case previousVal represents an accumulator.

My code:
```javascript

var array = [4,5,6,7,8];
var singleVal = 0;

// Only change code below this line.

singleVal = array.reduce(function(total, currentVal){
  return total + currentVal; // previousVal is the accumulator
});

```

**Comment by erictleung** [comment]
@dev-seahouse thanks for the issue. I do agree that it does seem confusing at first. However, these are the same parameter names used in the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce).

> `previousValue`
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The value previously returned in the last invocation of the callback, or `initialValue`, if supplied. (See below.)

cc/ @FreeCodeCamp/issue-moderators I could lean either way on changing it or not.

**Comment by ltegman** [comment]
This is just my personal practice (based on nothing standard), but I usually use `prev` and `curr` when I don't supply an `initialValue` (to make it clear to myself that `prev` starts as the first item in the array) and something like `acc`, `sum`, or `collection` when I supply an `initalValue`. I don't have strong opinions either way, but I can definitely see how `prevTotal` or `accumulator` or `total` might make the exercise clearer.

**Comment by sahilkhurana19** [comment]
@erictleung @ltegman I too think that we can use something that <code>prevTotal</code> in the example code as I also got confused while attempting this challenge. Shall I make a PR regarding this??

**Comment by erictleung** [comment]
@sahilkhurana19 thanks for your interesting in contributing! Thinking about this challenge a little more, what do you guys think about keeping `previousVal` and `currentVal` in there but then have additional commentary/hint on how you can intuitively think of `currentVal` as a sort of total or the accumulated value thus far in your callback?

**Comment by sahilkhurana19** [comment]
@erictleung 
So I guess it would be better if I reverted back the changes in my PR and add something like `In the following example reduce is being used to subtract all the values of an array, note that while previousVal is the accumulator, currentVal on the other hand iterates over the array and modifies the previousVal as per the return statement. `

**Comment by raisedadead** [comment]
@sahilkhurana19 The instructions suggestion look good except I feel its bit daunting, can we make iit simpler?

/cc @erictleung

**Comment by erictleung** [comment]
@sahilkhurana19 @raisedadead how about this?

> ...
> To use `reduce` you pass in a callback whose arguments are an accumulator (in this case, `previousVal`) and the current value (`currentVal`).
>
> The accumulator is like a total that `reduce` keeps track of after each operation. The current value is just the next element in the array you're iterating through.
> ...

**Comment by raisedadead** [comment]
Perfect
