### ISSUE TITLE
The Image link is broken

### ISSUE THREAD

**Issue by amorantep** [FreeCodeCamp/freecodecamp#875]
Challenge http://www.freecodecamp.com/challenges/waypoint-responsively-style-radio-buttons has an issue. 

This link is broken I think
https://bit.ly/fcc-kittens

![bug](https://cloud.githubusercontent.com/assets/5499116/8065368/ab8b6d60-0ea6-11e5-897b-86a4f22ccb12.png)

**Comment by QuincyLarson** [comment]
I can't reproduce this issue. Which browser are you using. Please try this URL again and confirm whether the image still appears to be broken.
