### ISSUE TITLE
Seek and Destroy- basic Algorithm Scripting, the input should be an entire array

### ISSUE THREAD

**Issue by mfalcop** [FreeCodeCamp/FreeCodeCamp#8753]
Seek and Destroy-Basic Algorithm Scripting

https://www.freecodecamp.com/challenges/seek-and-destroy

#### Issue Description

I've tried to set the first index form arr input, but I get aware of the input are no a completely array, they are arguments. So  the solution is just put brackets at the start and the end of arguments.

#### Browser Information

* Browser Name, Version: Google chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
destroyer([[1, 2, 3, 1, 2, 3] , 2, 3]);
```

**Comment by erictleung** [comment]
@mfalcop thanks for the issue but there is nothing wrong with the challenge. Hint: I would checkout the helpful links on the side. They'll give you a clue on how to complete the challenge. If you are still stuck with the challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
