### ISSUE TITLE
Comparisons with the logical or operator

### ISSUE THREAD

**Issue by fybwid** [FreeCodeCamp/FreeCodeCamp#8754]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

[Screenshot](http://www.awesomescreenshot.com/showImage?img_id=1267553)

Hi, i found typo mistake. In the explanation `only if` **num is between** `5 and 10 (5 and 10 included)` but the sample is `num > 10 || num < 5` (`num` = 11, 12, 13, ... `OR` `num` = 4, 3, 2 ...).

I think it should be `num >= 5 || num <= 10`

**Comment by erictleung** [comment]
@fybwid thanks for the issue. There does seem to be a typo. I think when it is said the function

> ...will return "Yes" only if `num` is between `5` and `10` (5 and 10 **included**).

the "included" is supposed to be "excluded" so it should read:

> ...will return "Yes" only if `num` is between `5` and `10` (5 and 10 **excluded**).

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3120) needs to be changed.

**Comment by radoslaw-gajos** [comment]
Hi! What do I have to do to solve this issue (I know the solution to the problem, I mean more formal steps like synchronization, making a branch etc)? I've never participated in an open source project before.

**Comment by fybwid** [comment]
@erictleung Thanks for the explanation.

**Comment by alistermada** [comment]
@erictleung I don't think there's a typo. The examples return "No" if `num` is greater than 10 or less than 5 (not 5, 10, or any number in between). If those conditions aren't met, then "Yes" is returned as the explanation suggests:

>...will return "Yes" only if num is between 5 and 10 (5 and 10 included)

**Comment by fybwid** [comment]
@alistermada That's correct, thanks. @erictleung Thank you, it's my fault. I should read more carefully.
