### ISSUE TITLE
Read-Search-Ask links are broken

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8756]
#### Challenge Name

All challenges that have the "Read-Search-Ask" suggestion.

For example: https://www.freecodecamp.com/challenges/where-art-thou

#### Issue Description

The "Read-Search-Ask" links are broken. The recent changes in the Wiki articles broke this. The new article for seeking help is here:

https://github.com/FreeCodeCamp/wiki/blob/master/FreeCodeCamp-Get-Help.md

#### To Fix

Change the links from:

```
<a href='//github.com/FreeCodeCamp/freecodecamp/wiki/How-to-get-help-when-you-get-stuck' target='_blank'>Read-Search-Ask</a>
```

to:

```
<a href='//github.com/FreeCodeCamp/freecodecamp/wiki/FreeCodeCamp-Get-Help' target='_blank'>Read-Search-Ask</a>
```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/15452339/50b6209a-1fa0-11e6-9e61-f73ef601f975.png)

**Comment by andrewcbass** [comment]
I would like to help with this issue.

**Comment by Alexr6667** [comment]
The links on the page to the 3 step article don't work either

**Comment by Ramon-Carroll** [comment]
It should also be noted that on the new page, the 3 links to Camper Bianca Mihai's 3 article series appears to be broken as well. Should I post this as a separate issue?
