### ISSUE TITLE
Constant Code Reset

### ISSUE THREAD

**Issue by Jrusso8199** [FreeCodeCamp/FreeCodeCamp#8758]
#### Challenge Name

Taste the Bootstrap Button

#### Issue Description

When selecting the area to add text it is unclickable.  I can not get to the area of the code with arrow keys.  I found that each challenge that loads I must first click reset code.  This seems to move some of the text from a picture link to the next line.  After doing the reset code it works fine.  I must do this for every challenge based on the CatPhotoApp.

#### Browser Information

* Browser Name, Version: Firefox v46.0.1, Safari, and Chrome on my windoze pc
* Operating System: OS X 10.11.4 and Windows 10
* Mobile, Desktop, or Tablet: IMac, and Microsoft Surface Pro 3

#### Your Code

```js
// If relevant, paste all of your challenge code in here

'''<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive">
  <button class="btn btn-block btn-primary">Like</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
'''
```

**Comment by bugron** [comment]
@Jrusso8199 thanks for posting this issue!
We have updated CodeMirror a couple of days ago (see https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8737) and, hopefully, this issue is solved with that update. I'm going to close it but, please, feel free to reopen if you still can reproduce this issue, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Jrusso8199** [comment]
Thank You,
It is fixed now
