### ISSUE TITLE
Chunky Monkey Challenge

### ISSUE THREAD

**Issue by amandacaseyamos** [FreeCodeCamp/freecodecamp#876]
Challenge http://www.freecodecamp.com/challenges/bonfire-chunky-monkey has an issue.

This is the code I wrote to solve the challenge.

var i = 0;
var newArray = [ ];
var finalArray = [ ];

function chunk(arr, size) {
  while (i < arr.length) {
    newArray = arr.slice(i, i+size);
    finalArray.push(newArray);
    i += size;
  } return finalArray;
}

chunk(['a', 'b', 'c', 'd'], 2);

It says this doesn't solve for all the situations but it does. I don't understand why this code isn't passing. Seems to be a bug.

**Comment by QuincyLarson** [comment]
@amandacaseyamos Thank you for submitting this issue.

Actually, this is correctly failing in this case. You are declaring global variables outside of the function. If you move those variable declarations inside your function, your code works fine and all tests will pass.

We are considering adding some copy to warn campers about this unexpected behavior of JavaScript.

**Comment by amandacaseyamos** [comment]
Thank you so much for your help, QuincyLarson. I really appreciate it.
