### ISSUE TITLE
Forum posting issue if you type <style>

### ISSUE THREAD

**Issue by twmilli** [FreeCodeCamp/FreeCodeCamp#8765]
#### Issue Description
If you type <style> in the forum, all of the text following and including the tag will not appear.  This was an issue because I was trying to describe to a fellow user why they don't need to put <style></style> in their code.

#### Browser Information

Chrome, Mac OSX, on the forum

#### Screenshot

![screen shot 2016-05-22 at 4 32 00 pm](https://cloud.githubusercontent.com/assets/15217013/15456339/ede74a2a-203a-11e6-818e-7f2cb34a7047.png)

**Comment by erictleung** [comment]
@twmilli the editor parses Markdown but also does HTML. So writing `<style>` will be considered HTML. To make sure it doesn't do this, use backticks around the style tag. The backtick is usually near the ESC key on the top left hand corner of your keyboard. So it should look like this:

```
`<style>`
```

Happy coding!
