### ISSUE TITLE
Sum all prime numbers fails test

### ISSUE THREAD

**Issue by kendsr** [FreeCodeCamp/FreeCodeCamp#8766]
fails this test: sumPrimes(977) ( but works outside of FCC.
my code:
function sumPrimes(num) {
	var allprimes=[];
  	for(i=2;i<=num;i++){
    	var notPrime = true;
    	for(j=2 ;j<=i;j++){
        	if(i%j===0 && i!==j){
            	notPrime = false;
        	}
    	}
    	if(notPrime){
        	allprimes.push(i);
    	}
  	}
  	var addPrimes = allprimes.reduce(function(a,b){
     	return a+b;
  	});
	return addPrimes;
}
sumPrimes(977);

**Comment by kendsr** [comment]
This finally worked when i put // noprotect as first line of code.

**Comment by ltegman** [comment]
This just means on your particular setup this code took long enough to execute that it triggered loop protect. Closing as resolved.
