### ISSUE TITLE
Potentially confusing wording/example on Portfolio Zipline instructions.

### ISSUE THREAD

**Issue by Ramon-Carroll** [FreeCodeCamp/FreeCodeCamp#8767]
#### Build a Personal Portfolio Webpage
[https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage](url)

#### Issue Description
From my discussion with some members on the new forum here: [http://forum.freecodecamp.com/t/portfolio-page-project-framework-usage/3128/](url), it appears that there is some confusion because the current portfolio example: [https://codepen.io/FreeCodeCamp/full/YqLyXB/](url), appears that it may have been built on top of a template: [http://blackrockdigital.github.io/startbootstrap-freelancer/](url), while the instructions, particularly number 10 (Not listed as one of the rules, by the way.) seems to discourage the use of a template: 

> There are many great portfolio templates out there, but for this challenge, you'll need to build a portfolio page yourself. Using Bootstrap will make this much easier for you.

The portfolio example does add in a decent amount of customization, so it doesn't look like a complete copy/paste. Perhaps the wording in the instructions should be modified, then?

**Comment by erictleung** [comment]
@Ramon-Carroll I think there is vagueness within the instructions so that the portfolio (and the other more challenging projects) can be your own. You have the freedom to make it however you want. But I guess there could be more clarification.

How might you change the wording to make it more clear?

**Comment by Ramon-Carroll** [comment]
@erictleung 

Hi there, Eric. Well, perhaps we could go with something more like this maybe:

_There are many great portfolio templates out there already. However, as an added challenge and learning opportunity, you could consider building the portfolio page yourself. Using Bootstrap can help make this process much easier for you._

Does this work, or is it too explicit?

**Comment by erictleung** [comment]
@Ramon-Carroll I wouldn't want to suggest that "as an added challenge" to do it from the ground up, but rather it is a learning opportunity. Maybe change it to:

> There are many great portfolio templates out there already. However, you should consider building your portfolio page as much as you can from the ground up. Using Bootstrap can help make this process much easier for you.

**Comment by Ramon-Carroll** [comment]
@erictleung That sounds cool too! Most importantly, it's clear. I'm interested in trying my hand at a pull request for this project, but I'm not exactly sure where it is in the source. Do you know where this is located?

**Comment by erictleung** [comment]
@Ramon-Carroll [here's the line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-ziplines.json#L195) you need to change.

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by Ramon-Carroll** [comment]
@erictleung I understand. Thank you very much.

**Comment by Ramon-Carroll** [comment]
Oh, and in case I haven't made myself clear, I'm working on this.
