### ISSUE TITLE
I can´t find were the mistake is.

### ISSUE THREAD

**Issue by Lerocha6** [FreeCodeCamp/FreeCodeCamp#8768]
Challenge [Add Elements within your Bootstrap Wells](https://www.freecodecamp.com/challenges/add-elements-within-your-bootstrap-wells#?solution=%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%0A%20%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%20%20%0A%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%3Cbutton%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%0A%20%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%3Cbutton%3E%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%0A%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%20%20%3Cbutton%3E%3C%2Fbutton%3E%20%20%20%20%20%20%0A%20%20%20%20%3C%2Fdiv%3E%20%20%20%20%0A%20%20%3C%2Fdiv%3E%0A%20%20%0A%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  
  <div class="row">
   
     <div class="col-xs-6">  
    <div class="well">
       <button></button>
      </div>
    </div>
    
     <div class="col-xs-6">
      <div class="well">
     <button></button>
    </div>
    </div>
  
   <div class="col-xs-6">
       <div class="well">
         <button></button>      
    </div>    
  </div>
  
 </div>
</div>
```

**Comment by erictleung** [comment]
@Lerocha6 thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: read the instructions carefully.

> Nest three button elements **within each** of your well div elements.

You should have a total of 6 buttons.

 Happy coding!
