### ISSUE TITLE
"Extra-curricular apps built by campers" link is broken

### ISSUE THREAD

**Issue by george-stepanek** [FreeCodeCamp/FreeCodeCamp#8771]
#### Issue Description

Clicking on the "Extra-curricular apps built by campers" link in the About page brings up a "We couldn't find a page for /labs" message.

**Comment by AkiraLaine** [comment]
@gasperno `/labs` has been deprecated. The link should be removed.

**Comment by tjgerot** [comment]
An SEO related note: if you were to search (I used Google) "free code camp labs" the top result brings about the same error.

**Comment by SpyR1014** [comment]
If help is still wanted I would be happy to remove the link.

**Comment by theflametrooper** [comment]
@saahilk Sorry :disappointed:, I'm already working on this. Checkout our other `help wanted` issues here: https://github.com/FreeCodeCamp/FreeCodeCamp/labels/help%20wanted.

**Comment by theflametrooper** [comment]
@SpyR1014 Sorry :disappointed:, I am already working on this. Checkout our other `help wanted` issues here: https://github.com/FreeCodeCamp/FreeCodeCamp/labels/help%20wanted. Happy Coding!
