### ISSUE TITLE
all conditions satisfied.  

### ISSUE THREAD

**Issue by urkrishna1** [FreeCodeCamp/FreeCodeCamp#8772]
Challenge [Everything Be True](https://www.freecodecamp.com/challenges/everything-be-true#?solution=function%20every(collection%2C%20pre)%20%7B%0A%20%20var%20ndw%3D%5B%5D%3B%0A%20%20var%20fal%3D%5B0%2C%20null%2C%20NaN%2C%20%22%22%2C%20undefined%5D%3B%0A%20%20var%20each%3B%0A%20%20for(each%20in%20collection)%7B%0A%20%20%20%20ndw%3DObject.keys(collection%5Beach%5D)%3B%0A%20%20%20%20%20%20if(ndw.indexOf(pre)%3D%3D%3D-1)%7B%0A%20%20%20%20%20%20%20%20%20ndw%3Dfalse%3B%0A%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20else%20if(fal.indexOf(collection%5Beach%5D%5Bpre%5D)!%3D%3D1%7C%7C%20Number.isNaN(collection%5Beach%5D%5Bpre%5D))%7B%0A%20%20%20%20%20%20ndw%3Dfalse%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20ndw%3D%20true%3B%0A%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20return%20ndw%3B%0A%20%20%7D%0A%0A%0Aevery(%5B%7B%22name%22%3A%20%22Pete%22%2C%20%22onBoat%22%3A%20true%7D%2C%20%7B%22name%22%3A%20%22Repeat%22%2C%20%22onBoat%22%3A%20true%7D%2C%20%7B%22name%22%3A%20%22FastFoward%22%2C%20%22onBoat%22%3A%20null%7D%5D%2C%20%22onBoat%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function every(collection, pre) {
  var ndw=[];
  var fal=[0, null, NaN, "", undefined];
  var each;
  for(each in collection){
    ndw=Object.keys(collection[each]);
      if(ndw.indexOf(pre)===-1){
         ndw=false;
         break;
         }
    else if(fal.indexOf(collection[each][pre])!==1|| Number.isNaN(collection[each][pre])){
      ndw=false;
      break;
    }
    else{
      ndw= true;
    }
    }
  return ndw;
  }


every([{"name": "Pete", "onBoat": true}, {"name": "Repeat", "onBoat": true}, {"name": "FastFoward", "onBoat": null}], "onBoat");

```

**Comment by erictleung** [comment]
@urkrishna1 thanks for the issue but there is an issue with your code. Please change your function name to `truthCheck`. If you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by urkrishna1** [comment]
I got it, thank you.
