### ISSUE TITLE
Heroku allows only five apps without credit card Info

### ISSUE THREAD

**Issue by ChaituVR** [FreeCodeCamp/FreeCodeCamp#8773]
We have ten back-end projects and Heroku only allows upto five apps without credit card info... Not all people will have cards and not all people want to share their card details . . May be there is some better alternative to this other than providing the card info or Creating  account ?  because all the 10 back end projects says this `enter the URLs for both your GitHub repository and your live app running on Heroku `

Thanks

**Comment by theflametrooper** [comment]
@ChaituVR Heroku is changing their plans soon: 

> Starting June 1st, when you sign up for a Heroku account you will immediately get 550 free dyno hours. In addition, we add another 450 dyno hours for a total of 1,000 free dyno hours if you verify your identity by providing us with a valid credit card. We do not charge this card unless you use paid services, and ask for this information as an identity confirmation step. **(Alternative identity confirmation methods will be introduced in the future.)**

[Source](https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours)

**Comment by ChaituVR** [comment]
@theflametrooper That's a great one i can give my card details and sign up but what i am talking about is Most of the people joining FCC would be Students some from city or some from small towns or even from remote areas ... Not every one will have a card.. take a person for example.. he don't have a card ... what if he want to complete all the back end projects but stopped because he don't have a card.. (apart from creating another account) then the whole idea of FCC is for nothing right... no submission because of no card .. no certificate because of no submission..  I am talking about those kind of people .. there could be another alternative for this ?? may be we should keep submitting the heroku link
 as an (optional) ??  at least for the API projects ??

**Comment by theflametrooper** [comment]
@ChaituVR It says on their post that Alternative **identity confirmation methods will be introduced in the future.** instead of just using valid credit cards. However, I see your point.

**Comment by ChaituVR** [comment]
i missed that line ;)  ok lets hope for them to change the verification but till then we should have some alternative right? may be i am assuming this in the wrong way ... :P

**Comment by theflametrooper** [comment]
cc/ @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
Closing this issue, feel free to reopen after June 1st if you still are having this issue and think it needs addressed. This is technically not an issue with site however. Thanks for bringing this up!

**Comment by BerkeleyTrue** [comment]
Alternatively, you could run each project on a separate subpath. for instance /app1 /app2 /app3, and then have express serve different apps. This way only one is needed.

**Comment by ChaituVR** [comment]
Thanks @BerkeleyTrue and yes this could be the best alternative...
