### ISSUE TITLE
Cannot scroll through wiki article titles

### ISSUE THREAD

**Issue by efaryna** [FreeCodeCamp/FreeCodeCamp#8778]
#### Issue Description

The new Wiki search does not allow scrolling through the article titles. Only the first title in the list is clickable.

#### Browser Information

* Browser Name, Version: Chrome, Firefox, Edge
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by theflametrooper** [comment]
@efaryna Are you talking about `https://www.freecodecamp.com/wiki/`? If so this is a duplicate of FreeCodeCamp/wiki-generator#44 and FreeCodeCamp/wiki-generator#45

**Comment by ltegman** [comment]
Closing as a duplicate of the bugs on the wiki repo.
