### ISSUE TITLE
Steam Roller is Unolvable

### ISSUE THREAD

**Issue by Terron23** [FreeCodeCamp/FreeCodeCamp#8780]
Steam Roller

<a href="https://www.freecodecamp.com/challenges/steamroller#?solution=function%20steamroller(arr)%20%7B%0A%20%20var%20flatArr%3D%5B%5D%2C%20i%3B%0A%20%20%0A%20%20function%20nestedCheck(arr1)%20%7B%0A%20%20%20%20for%20(var%20j%3D0%3Bj%3Carr1.length%3Bj%2B%2B)%20%7B%0A%20%20%20%20if%20(!Array.isArray(arr1%5Bj%5D))%0A%20%20%20%20%20%20flatArr.push(arr1%5Bj%5D)%3B%0A%20%20%20%20else%20nestedCheck(arr1%5Bj%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0Afor%20(i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%20%7B%0A%20%20if%20(!Array.isArray(arr%5Bi%5D))%0A%20%20%20%20flatArr.push(arr%5Bi%5D)%3B%0A%20%20else%20nestedCheck(arr%5Bi%5D)%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20flatArr%3B%0A%7D%0A%0Asteamroller(%5B1%2C%20%5B2%5D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A">FreeCodeCaamp</a>

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by sludge256** [comment]
It looks like you have an old version of the challenge loaded.

Update your function (and call) to `steamrollArray` and your code will pass.

**Comment by erictleung** [comment]
@Terron23 @sludge256 is correct. Just change your function name to `streamrollArray` and your code should work. Happy coding!

**Comment by Terron23** [comment]
It worked. Thanks! I really appreciate it.
