### ISSUE TITLE
Running tests crashes browser

### ISSUE THREAD

**Issue by TJBANEY** [FreeCodeCamp/FreeCodeCamp#8783]
Anytime I try to run a test to see if my code works, even when i don't edit the initial code at all, the page becomes unresponsive and I have to exit out of the browser. I also have to clear my cache because going back to free code camp will take me back to the challenge, and immediately crash the browser.

Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function sumFibs(num) {
  return num;
}

sumFibs(4);

```

**Comment by ltegman** [comment]
It sounds like you have an infinite loop in your solution. Could you show us the code you're trying to submit?

**Comment by TJBANEY** [comment]
Absolutely.
function sumFibs(num) {  arr = [];  for (i = 1; i <= num; i++){      arr.push(i);  }
  return arr;}
sumFibs(4);
Date: Mon, 23 May 2016 17:19:34 -0700

**Comment by ltegman** [comment]
Ahh, yes -- this isn't an infinite loop, but this particular algorithm (or start of one) is too slow to be practical. One of our test cases is `4000000` and calling `Array.push()` 4 million times takes a LONG time. Your browser isn't actually locked, it just seems like it. If you want to try out algorithms you fear may do this I'd recommend giving [https://repl.it/](https://repl.it/) a go. They'll ask you if you want to kill the code if it runs too long.

Thanks and happy coding!
