### ISSUE TITLE
C9 and learnyoumongo workarounds in challenge description

### ISSUE THREAD

**Issue by zaclem01** [FreeCodeCamp/FreeCodeCamp#8784]
#### Challenge Name
[Store Data in MongoDB](https://www.freecodecamp.com/challenges/store-data-in-mongodb)

#### Issue Description
As referenced in #8629 and #8482, the DB challenges are not able to be completed unless a [workaround is implemented](http://forum.freecodecamp.com/t/psa-for-anyone-attempting-to-use-mongodb-on-c9-and-having-issues/2541) in C9 to get the `mongod` command alias to work correctly. This includes either creating an alias in a file or editing the `~/.bashrc_aliases` file. 

While it is possible for someone to find this information by searching online or looking at fcc issues, I feel that the level of knowledge that it takes for a beginner in a Linux environment to solve this is too steep (note, I'm by no means an expert and it took me quite some time to fix it).

I believe it should be referenced in the challenge description. The creators of C9 are working on a fix, but it could be a long time coming and keep campers from completing the challenge in a timely fashion.

#### Browser Information
C9.io environment

**Comment by Andrparsons** [comment]
Just to add to this, [here](https://community.c9.io/t/setting-up-mongodb/1717) is a link to the workaround posted by a c9 staff member.

**Comment by zaclem01** [comment]
@FreeCodeCamp/issue-moderators thoughts on this?  I'd be happy to add links to the descriptions if desired.

**Comment by Balundo** [comment]
I am new I am just going to my first challenge

**Comment by raisedadead** [comment]
@zaclem01 I don't see why it would hurt. Please go ahead.

**Comment by zaclem01** [comment]
@raisedadead On it. Thanks!
