### ISSUE TITLE
Use JavaScript Console needs semicolon in example + code tag formatting

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8785]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-the-javascript-console

#### Issue Description

The example code in "Use the JavaScript Console" needs a semicolon at the end to be consistent with best practices of JavaScript.

Additionally for visual appeal, the test text needs some `<code>` tags to be modified so it can look similar to this:

> You should use the `console.log` method to log `"Hello world!"` to your JavaScript console.

#### How to Fix

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/automated-testing-and-debugging.json#L14) needs a semicolon.

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/automated-testing-and-debugging.json#L25) needs `<code>` tags so it'll look like this:

```js
"assert(editor.getValue().match(/console\\.log\\(/gi), 'message: You should use the <code>console.log</code> method to log <code>\"Hello world!\"</code> to your JavaScript console.');"
```

#### Screenshot

**Example Code Format Issue**
![image](https://cloud.githubusercontent.com/assets/2754821/15489518/4e23a3b8-2115-11e6-8b45-73f2beb2f371.png)

---

**Test Text Format Issue**
![image](https://cloud.githubusercontent.com/assets/2754821/15489579/b11e231c-2115-11e6-8f41-d2ae8b2b6141.png)

**Comment by zaclem01** [comment]
@erictleung working on the issue

**Comment by zaclem01** [comment]
@erictleung Submitted pull request finally. vi is an awful editor to get used to (had to squash because I closed with </cod> :frowning: )

Looks like it passed, do I just wait for review now?
