### ISSUE TITLE
Alt tag glitch

### ISSUE THREAD

**Issue by Lemony-Andrew** [FreeCodeCamp/freecodecamp#879]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-alt-text-to-an-image-for-accessibility has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Due to a 'known' error with webkit, which is implemented in Chrome, the ALT tag does not render on the screen. A work around is using the TITLE tag and may want to be mentioned in the tutorial because a majority of people will notice this problem. 

A link to the stackexchange discussion can be found here: http://stackoverflow.com/questions/5386570/how-to-display-alt-text-for-an-image-in-chrome

**Comment by QuincyLarson** [comment]
@lemony-andrew thank you for pointing this out. Our intention is not to show anything, but rather just to raise awareness of the alt tag and its role. The title tag is much less important, and I don't think it warrants introduction at this point (we're not trying to be exhaustive in our coverage of HTML, but rather to just introduce common aspects).
