### ISSUE TITLE
i don't know what's wrong !!!!!

### ISSUE THREAD

**Issue by maurice-jabbour** [FreeCodeCamp/FreeCodeCamp#8791]
I can't solve this ..... please help me :) 

![capture](https://cloud.githubusercontent.com/assets/18706464/15514016/bbd514c0-21ef-11e6-99b5-279cb901fda6.JPG)

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!
