### ISSUE TITLE
Ambiguous question statement in 4 Basic Parts of Computer Basics Hike

### ISSUE THREAD

**Issue by tjgerot** [FreeCodeCamp/FreeCodeCamp#8792]
#### Challenge Name
[Computer Basics: The 4 Basic Parts of a Computer](https://www.freecodecamp.com/videos/computer-basics-the-4-basic-parts-of-a-computer) (Quiz Question 1)

#### Issue Description
Question 1 of the "Computer Basics: The 4 Basic Parts of a Computer" quiz (following the reading) asks for a true or false on the following statement: "The computer has 3 basic parts." Now simply referencing the quiz title, one can see the unit review 4 basic parts of a computer, but it can be very confusing based on the wording of the question. The answer could be true, as a computer does have 3 basic parts (and one more). The answer could also be false, as many quiz takers expect 4 basic parts by the name of the unit. To make the question clearer, I propose we rephrase the question to be "The computer has 5 basic parts."

My aim in raising this issue is to make this question more specific, and follow clear logic.

**Comment by erictleung** [comment]
@tjgerot thanks for the feedback. I can see how, if read too deeply, can be misinterpreted.

Keeping inline with the same statement, we could change it to:

> The computer only has 3 basic parts.

**Comment by tjgerot** [comment]
Quite the simple fix, I apologize for overlooking that simple change. I do indeed believe that would be a wonderful fix! Thank you.

**Comment by erictleung** [comment]
@tjgerot no worries! Thanks for the feedback nonetheless :+1: 

If anyone wants to fix this, you'll need to change [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/04-video-challenges/computer-basics.json#L29) to

> The computer only has 3 basic parts.

**Comment by radoslaw-gajos** [comment]
I'd like to fix this. I'm new to GitHub.

**Comment by atjonathan** [comment]
@radoslaw-gajos Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by radoslaw-gajos** [comment]
@atjonathan Thanks! I'll follow the instructions and in case of doubt I know what to do.
