### ISSUE TITLE
Fix CSS for Pledge cancelling button

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8793]
On hover the "maybe later" button on https://www.freecodecamp.com/commit is barely visible.
![](https://www.evernote.com/l/Ar_T1dS0cD9HwKvMOCfxxRUQ-1UxtcU2bBYB/image.png)

**Comment by theoneinskane** [comment]
I would love to try and fix this but although it is a bit of CSS(?) I think it is more difficult in the application for me to find where to fix it. 
For information, it has the same "too light" grey when you already have a pledge as well.

**Comment by prabhavgupta** [comment]
i tried searching , but could not find any less file or css file with class .btn .

**Comment by prabhavgupta** [comment]
where is main-3a3af892a1.css uploaded?

**Comment by atjonathan** [comment]
@prabhavgupta You will have to update the `less`, found here: https://github.com/FreeCodeCamp/FreeCodeCamp/tree/staging/client/less.

**Comment by estherfang09** [comment]
If we update the property of main.less of .btn-primary hover's color. The issue would be fixed right?

**Comment by erictleung** [comment]
[This](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/commit/index.jade#L81) is where the classes are applied to the "Maybe later" button. Right now, the button is rendered as:

```html
<a href="/map" class="btn btn-block btn-lg btn-default">Maybe later</a>
```

@QuincyLarson do we just wanna remove the `btn-default` and replace it with `btn-primary` like the other buttons? That'll make it look like this when highlighted:

![image](https://cloud.githubusercontent.com/assets/2754821/15562495/81a5590c-22b4-11e6-8f3d-847800465a21.png)
 
Or is there another reason why that button was just `btn-default`?

**Comment by prideloki** [comment]
Hi @QuincyLarson , i will work on it
it would look like this gif below
![05ydnveexw](https://cloud.githubusercontent.com/assets/1741356/15602140/a6f0eef0-241d-11e6-8299-fdd0010a472d.gif)
