### ISSUE TITLE
Passes objectives, throws an error on the console.

### ISSUE THREAD

**Issue by Quartzito** [FreeCodeCamp/FreeCodeCamp#8796]
Challenge [Arguments Optional](https://www.freecodecamp.com/challenges/arguments-optional#?solution=function%20addTogether(num1%2C%20num2)%20%7B%20%0A%20if%20(arguments.length%3C2)%7B%20%20%20%20%0A%20%20if((typeof(num1)!%3D%3D%22number%22))%7B%0A%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%7D%0A%20%20return%20function%20addmore(num2)%7B%0A%20%20%20%20%20%20if((typeof(num1)!%3D%3D%22number%22)%7C%7C(typeof(num2)!%3D%3D%22number%22))%7B%0A%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%7D%0A%20%20%20%20return%20num1%2Bnum2%3B%0A%20%20%7D%3B%0A%20%7D%0A%20%0A%20if((typeof(num1)!%3D%3D%22number%22)%7C%7C(typeof(num2)!%3D%3D%22number%22))%7B%0A%20%20%20%20%20%20%20return%20undefined%3B%0A%20%7D%0A%20%20%0A%20%20return%20num1%2Bnum2%3B%0A%0A%7D%0A%0AaddTogether(2)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function addTogether(num1, num2) { 
 if (arguments.length<2){    
  if((typeof(num1)!=="number")){
       return undefined;
  }
  return function addmore(num2){
      if((typeof(num1)!=="number")||(typeof(num2)!=="number")){
       return undefined;
     }
    return num1+num2;
  };
 }
 
 if((typeof(num1)!=="number")||(typeof(num2)!=="number")){
       return undefined;
 }
  
  return num1+num2;

}

addTogether(2);
```

Well, the title pretty much explains it. When I execute the code it passes the objectives on green but the "you win" pop-up wont appear and the black box stays on "testing challenge..." Checking the console I got an error that reads "Uncaught TypeError: Cannot read property 'split' of undefined".. 

Any advise?

**Comment by atjonathan** [comment]
@Quartzito The problem is with your custom test case: `addTogether(2);`. All the actual test cases work fine.

**Comment by ltegman** [comment]
I can confirm this error despite the fact that the code is a valid solution. Seems that calling a function that returns a function on the final line of a solution breaks our code execution? Whatever the case you shouldn't be able to completely crash the JS environment for FCC with valid code (which this code does).
