### ISSUE TITLE
'_'  is counted as an Latin alphanumeric character

### ISSUE THREAD

**Issue by vadmiral786** [FreeCodeCamp/FreeCodeCamp#8798]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20newString%3Dstr.replace((%2F%5CW%2B%2Fg)%2C%20%22%22)%3B%0A%20%20var%20newNewString%3DnewString.replace((%2F%5Cs%2B%2Fg)%2C%20%22%22)%3B%0A%20%20var%20newerString%3DnewNewString.toLowerCase()%3B%0A%20%20var%20array%20%3D%20newerString.split(%27%27)%3B%0A%20%20var%20yarra%20%3D%20array.reverse()%3B%0A%20%20var%20reverseString%20%3D%20yarra.join(%27%27)%3B%0A%20%20if(reverseString%20%3D%3D%3D%20newerString)%7B%0A%20%20return%20true%3B%7D%0A%20%20else%20if(reverseString%20!%3D%3D%20newerString)%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0A%0A%0Apalindrome(%220_0%20(%3A%20%2F-%5C%20%3A)%200-0%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  var newString=str.replace((/\W+/g), "");
  var newNewString=newString.replace((/\s+/g), "");
  var newerString=newNewString.toLowerCase();
  var array = newerString.split('');
  var yarra = array.reverse();
  var reverseString = yarra.join('');
  if(reverseString === newerString){
  return true;}
  else if(reverseString !== newerString){
    return false;
  }
}



palindrome("0_0 (: /-\ :) 0-0");

```

**Comment by ltegman** [comment]
`_` is not an alphanumeric character, but it is included in the regex word shorthand. It's up to you to account for this in your code. Thanks and happy coding!
