### ISSUE TITLE
The result of randomWholeNum should be a whole number.

### ISSUE THREAD

**Issue by Ashul** [FreeCodeCamp/FreeCodeCamp#8801]
Challenge [Generate Random Whole Numbers with JavaScript](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript#?solution=%0Avar%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20randomWholeNum()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0AMath.floor(Math.random()*10)%3B%0A%20%20return%20Math.random()%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  // Only change code below this line.
Math.floor(Math.random()*10);
  return Math.random();
}

```

**Comment by erictleung** [comment]
@Ashul your code doesn't return a whole number, it only returns `Math.random` which is a random real number. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
