### ISSUE TITLE
freedom all my site for malware spam and bug

### ISSUE THREAD

**Issue by boyamh8** [FreeCodeCamp/FreeCodeCamp#8802]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by boyamh8** [comment]
I want to loading from my site is don't track and virus

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Happy Coding!
