### ISSUE TITLE
Convert JSON Data to HTML doesn't call for "message button to be pressed" to pass

### ISSUE THREAD

**Issue by theoneinskane** [freeCodeCamp/freeCodeCamp#8805]
Challenge [Convert JSON Data to HTML](https://www.freecodecamp.com/challenges/convert-json-data-to-html) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html

<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json", function(json) {

        var html = "";
        // Only change code below this line.
        json.forEach(function(val) {
          var keys = Object.keys(val);
          html += "<div class = 'cat'>";
          keys.forEach(function(key) {
          html += "<b>" + key + "</b>: " + val[key] + "<br>";
          });
          html += "</div><br>";
          });


        // Only change code above this line.

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
   </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

The student doesn't have to press the button and see the updated output before the test is passed and therefore doesn't see what the output would be. Suggest to update instructions to tell the student to click the message button at least and if possible don't pass them unless they have.

**Comment by atjonathan** [comment]
@theoneinskane I personally like this idea, let's see what the other @FreeCodeCamp/issue-moderators think!

**Comment by hallaathrad** [comment]
🔨 git er done!

**Comment by raisedadead** [comment]
Adding a instruction is the easy part. The real challenge is to check the assertion on the Message button which lies in the the phone preview which is a iframe.

Possible but yes real tricky

**Comment by theoneinskane** [comment]
@raisedadead maybe just start with the instruction to click message?

**Comment by SaintPeter** [comment]
Our current infrastructure does not support asynchronous tests or spies, both of which are needed to test this properly.  As I understand it, our "coming soon" infrastructure will support this, which should enable a much larger variety of tests/challenges.

**Comment by lawfets** [comment]
I don't know if I can put this here but if you make a mistake in the html code that can be copy-pasted into the right position, it still validates the test, although there's a major mistake in the coding and if you press the button nothing happens.
for instance : if you remove  html += "<div class = 'cat'>"; the test passes but there's no output due to the problems created in the html code that is being produced.
