### ISSUE TITLE
Add a fixed header on Wiki Modal

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#8806]
#### Issue Description
Add a fixed header on the Wiki Modal with the close and open link in new tab buttons, similar to the Chat Room Modal. This will keep consistency.

#### Screenshots

**Current Wiki Modal:**

![GIF showing current Wiki Modal](https://i.gyazo.com/d8b182f7e1e5fb0cc887266b5e3f77e0.gif)

**Chat Room Modal:**

![GIF showing Chat Room Modal](https://i.gyazo.com/410dea50c17724c8b7e685815425c23c.gif)

**Comment by estherfang09** [comment]
shouldn't it belong to the wiki repo's issue?

**Comment by atjonathan** [comment]
@estherfang09 Not really, this `aside` is generated on FreeCodeCamp's codebase along with the less.

**Comment by estherfang09** [comment]
Oh I see. there is an append function in main.js to append the header. but for the wiki ,what should the title be

**Comment by atjonathan** [comment]
@estherfang09 I'm not sure what you mean?
