### ISSUE TITLE
Users getting 522 timeout error

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#8808]
We're getting scattered reports of users getting 522(timeout) errors when trying to reach the site.

If you've encountered it, please list your locations (city/state/country), whether it is still happening, if it's consistent, and whether you can access the site now.

I have a pretty good idea of the cause and I'm trying to verify it.

**Comment by Lx-e** [comment]
Did you find a fix? I tried so many things to fix this issue, but nothing works. On my mac and PC I still get the 522 Host Error, and when I disable the wifi on my phone I'm able to go on it. I'm from Montreal Quebec but I know at least 25 people from the same area using the site and they have no problem using the site.

**Comment by gz4053** [comment]
#### Issue Description

For the past couple of weeks I haven’t been able to access the site. While I can access the offline cloud flare  version of the homepage I receive the message error “522 connection timed out” and “Host Error”; I haven’t been having a problem on other sites. The site works on my phone when it’s disconnected to the home wifi but for some reason the home wifi produces a “host error”. Does anyone know how I could fix this?

This is my 2nd time submitting this problem. 


#### Browser Information


Mac (Safari, Chrome)
Android(Chrome)





#### Screenshot

![image](https://cloud.githubusercontent.com/assets/14838949/16060432/aa36b55e-3255-11e6-87c2-3d9b44b03112.png)

![image](https://cloud.githubusercontent.com/assets/14838949/16060463/d6a7e5ae-3255-11e6-9f69-575b2c91baee.png)

**Comment by gz4053** [comment]
Anyone figure this out?

**Comment by gz4053** [comment]
Newark / New Jersey / USA

**Comment by rustyvera** [comment]
Brooklyn / New York / USA

Though when I tried in Manhattan it worked fine.

**Comment by LRodriguez92** [comment]
Bronx / New York / USA

It's been like this for me for weeks.

**Comment by LRodriguez92** [comment]
Hey guys I downloaded an extension on chrome called Hola. Its a free vpn (I'm sure you can use any other one). even though I'm already in the US I made it browse from the US and it works perfectly now. Hope it works for you guys as well

**Comment by QuincyLarson** [comment]
Here's a stack trace a camper sent us: ![](https://ton.twitter.com/1.1/ton/data/dm/745668157797470211/745668157826818050/ErfyVXYC.jpg:large)

**Comment by benivegna** [comment]
That's my traceroute, I'm in Brooklyn getting the same 522 error.  Rodriguez I'm also using a vpn to connect successfully, but a word a warning about Hola: http://www.pcworld.com/article/2928340/ultra-popular-hola-vpn-extension-sold-your-bandwidth-for-use-in-a-botnet-attack.html  Apparently Hola will use your computer as an exit node for other Hola users.

**Comment by LRodriguez92** [comment]
Interesting. I had no idea. Thanks for the info. I'll definitely stop using Hola.

**Comment by benivegna** [comment]
Here is cloudflares 522 error [documentation](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out)

I've tried flushing my dns cache with no results.

The website ["Is it down right now?"](http://www.isitdownrightnow.com/freecodecamp.com.html) also seems to have the same issue.
![screenshot from 2016-06-22 13-08-02](https://cloud.githubusercontent.com/assets/11660811/16469115/40fefa64-3e1d-11e6-953d-e43d387c46e9.png)

**Comment by usertwelve** [comment]
Also from Montreal Canada and getting the 522 error when trying to accessing freecodecamp from home wifi. Bu it works fine using phone connection. Anyone have figured this out yet?

**Comment by benivegna** [comment]
I believe the problem is a network routing issue between CloudFlare and the origin web server.  FreeCodeCamp needs to raise a support ticket with the cloudflare support team.

![screenshot from 2016-07-06 14-14-42](https://cloud.githubusercontent.com/assets/11660811/16629596/57415a6c-4384-11e6-8377-7a0c252d41cf.png)

**Comment by ekwong** [comment]
I'm having this problem as well.  I've flushed my DNS cache and no go. 

New York, USA

**Comment by BerkeleyTrue** [comment]
Please check if you are now able to reach Free Code Camp from effected networks.

This issue may have been resolved.

**Comment by benivegna** [comment]
Now I'm receiving a 403 forbidden.  I can still reach the site fine with a vpn, however.

**Comment by benivegna** [comment]
Scratch that 403, everything is working fine now.  Thanks Berkeley!

**Comment by usertwelve** [comment]
Same here. Receiving 403 forbidden error.

**Comment by ekwong** [comment]
I'm getting a 403 forbidden error as well now.

**Comment by BerkeleyTrue** [comment]
Can someone screen cap this 403?

**Comment by usertwelve** [comment]
![403](https://cloud.githubusercontent.com/assets/20324911/16787250/ead121de-4868-11e6-9b55-01171a426062.jpg)

**Comment by BerkeleyTrue** [comment]
Ok, how about now?

**Comment by usertwelve** [comment]
Looks like it is finally working. Thank you very much.

**Comment by BerkeleyTrue** [comment]
Thanks for all your patience. Looks like we finally tracked down the firewall issues with CloudFlare.

Happy Coding!

**Comment by ekwong** [comment]
Thank you!

**Comment by tabrza** [comment]
Hello!
Appears that this problem has recurred. I'm getting the 522 error for the past couple of days when trying to access it freecodecamp. It was down for a few hours yesterday and now again today

**Comment by nvnitin27** [comment]
Error 504 gateway timeout error 
kottayam/kerala/India
