### ISSUE TITLE
PHP Subforum Needed

### ISSUE THREAD

**Issue by m-henderson** [FreeCodeCamp/FreeCodeCamp#8809]
Had a user ask a question about PHP in the forum. The question was asked in the camper lounge,  I was going to refer him to a part of the forum where he could get PHP specific help and noticed that there was not a PHP Help subforum under the Free Code Camp category. 

What are your thoughts on adding this to the forum ? Free Code Camp > PHP Help

**Comment by atjonathan** [comment]
@m-henderson I've moved this to the `discourse` repo.
Feel free to follow the issue here: FreeCodeCamp/discourse#18
