### ISSUE TITLE
Make a person Issues

### ISSUE THREAD

**Issue by dwilbank68** [FreeCodeCamp/FreeCodeCamp#881]
![](https://dl.dropboxusercontent.com/spa/lkj2dewi3ofvkgc/l_ggz85t.jpg)

I was all hyped up after the Hack Reactor lessons, and I thought we were supposed to use the prototype object - which this exercise does not want us to do.

Maybe a sentence saying not to use prototype object?

Pretty sure I saw others having a similar confusion.

Thanks!

**Comment by BerkeleyTrue** [comment]
@dwilbank68  Thanks for pointing this out!

Both ways are valid but if you put instance methods on the prototype (which is the correct place to put this things) they will not show up in Object.keys because they are not direct properties of bob but properties of bobs prototype. But if you but them in the constructor on the `this` object, then they are direct properties of bob.

The test should change to check that the keys of bob are six is true or 
`Object.keys(Object.getPrototypeOf(bob)) === 6`

so that bot cases work.

Any takers?

**Comment by dwilbank68** [comment]
Got it. Thanks. I got it to pass them moved on.

**Comment by BerkeleyTrue** [comment]
>You made a valid point, though. Not sure if its something that should be changed as getting it to work with prototype methods would involve creating a Person object in an IIFE… that may be advanced of this point of the Map.

Here is what it would look like to use the prototype to set instance methods and use closures to create private variables.

![bonfire__make_a_person___free_code_camp_and_slack](https://cloud.githubusercontent.com/assets/6775919/8075406/0b1b6e94-0ef5-11e5-87a7-0675edb3fc0a.png)

This passes all but the first test.

**Comment by BerkeleyTrue** [comment]
@terakilobyte Do you think this use case is worth supporting?

**Comment by dwilbank68** [comment]
var Person = function(firstAndLast) {
  this.fullname = firstAndLast;
  this.firstname = firstAndLast.split(' ')[0];
  this.lastname = firstAndLast.split(' ')[1];
  // this.property = 'test passer';
  // this.propertytoo = 'is a test passer';
  // this.property_as_well = 'just a mess';
};

Person.prototype.setFullName = function(firstAndLast) {
    this.fullname = firstAndLast;
};

Person.prototype.getFullName = function() {
    return this.fullname;
};

Person.prototype.setFirstName = function(first) {
    this.firstname = first;
};

Person.prototype.getFirstName = function() {
    return this.firstname;
};

Person.prototype.setLastName = function(last) {
    this.lastname = last;
};

Person.prototype.getLastName = function() {
    return this.lastname;
};

var bob = new Person('Bob Ross');
bob.getFullName();

If the test would pass with either 6 or 3 keys, then this code would
work. I was just asking about the wording of the instructions. In my
haste I misread them!


On Tue, Jun 9, 2015 at 10:24 PM, Berkeley Martinez <notifications@github.com

**Comment by terakilobyte** [comment]
Actually, I've given some thought about this. I think we need to split this into two separate bonfires.

In initially wrote this bonfire to prod people into data encapsulation through closure and "private" variables. I can however see how this is absolutely confusing with the structure of the bonfires.

As I said I'd love to see this moved into two separate bonfires. One that checks the prototype, and one that checks the object. Thoughts @dwilbank68? I'm past the point where the recency of learning causes conflict on this, and further at a disadvantage to look at it objectively as I was the one who authored the bonfire so have exact knowledge of what it wants.

**Comment by dwilbank68** [comment]
On Wed, Jun 10, 2015 at 8:06 AM, Nathan <notifications@github.com> wrote:

> Thoughts @dwilbank68 <https://github.com/dwilbank68>?
>
dwilbank68 is always for splitting an exercise to build pattern
recognition. The Udacity course didn't use the terms 'closure' or 'private
variables' though, when demonstrating how to add methods to a Class. While
I know what those entities do under other situations like IIFEs, I might be
confused once again as to how they would be used to solve this particular
exercise.

**Comment by dwilbank68** [comment]
okay, looking back at the code I see what you mean.

**Comment by BerkeleyTrue** [comment]
@terakilobyte Maybe the challenge should be rewritten to remove the OOP concepts and just focus on understanding closures and scope?

**Comment by QuincyLarson** [comment]
Our new OOP challenges are addressing these concerns and are being expanded daily. I'm going to close this issue.
