### ISSUE TITLE
Suggested re-design of /map

### ISSUE THREAD

**Issue by dewhiz** [FreeCodeCamp/FreeCodeCamp#8814]
Thanks to the people who responded.  So I need to work on changing design for a 'linear map' - looked up linear parlance, landed in math-land, basically - things have to run like a trail, & can't be parallel.
Seems like I'm in over my head, so I'll just tread water, look around, think it over before I take the next whack at it.

---

I would like to redesign the 'Map' page in order to enhance:
1. The educational value of the map.
2. The attractiveness of the page.

It just has a single long list of challenge topics, with dozens of items included in a single topic.  If there were sub-topics, it's easier for the learner to develop a concept of the material, to remember, and to use a list as a reference when using the material later.

The page could be set up with a few "divs, " or as a table:

| HTML Topics | CSS Topics |
| --- | --- |
| Block Elements | Fonts Colors |

(This is the first time I'm using Markdown.)

We could use the current headlines, with  2 or 3 columns across the page for subtopic headlines.  Individual challenges could be nested under the subtopic headlines, with a toggle for viewing or hiding the challenges. 

In a formal proposal, should I make up a sample page, or choice of pages?  
I could either decide how to group  and name sup-topics, or would it be a decision by wiki?

The current page is just one long laundry list. (Could anything be better than a laundry list?)

Here's the current page:
![fireshot screen capture 001 - a map to learn to code and become a software engineer i free code camp - www_freecodecamp_com_map](https://cloud.githubusercontent.com/assets/18739327/15588665/f16916fe-235c-11e6-98e7-2d031b08b8d6.png)

Looking forward to getting some response.  

FCC  @dewhiz

**Comment by hallaathrad** [comment]
Agreed. The curriculum's display could be greatly improved.
Seems like you've already got ideas on how to improve it, so perhaps it'd be best if you made some sort of mock or even better submit a PR we could iterate over :)

**Comment by sludge256** [comment]
I agree that the map could use some work. I've had some ideas float through my mind in regards to this issue and would be interested in seeing what others have in mind.

**Comment by BerkeleyTrue** [comment]
> It just has a single long list of challenge topics, with dozens of items included in a single topic. 
> Individual challenges could be nested under the subtopic headlines,

Just to clarify, this isn't a list but a linear map (hence why it's at /map). We want it to convey the idea that there is only one single track, instead of multiple tracks that are tangentially related to the others like on other coding sites. Any mock ups should preserve this idea.

> Individual challenges could be nested under the subtopic headlines

They are separated by super-block(getting started, front end, data vis, ...etc), then broken into blocks (in front end: html/css, jquery, projects, ...etc), then each block lists it's challenges. This order should be preserved and unchanged. Putting them into categories doesn't make sense. That would make more sense as a wiki article instead of a change in how the map is organized (there is a lot going on internally and on the back end that relies on this structure).

With the above said, it could use a better layout, although a table wouldn't make sense and does not convey the idea of linear progression.

**Comment by atjonathan** [comment]
@hallaathrad I assigned you so you can do `QA` :stuck_out_tongue_winking_eye:

**Comment by raisedadead** [comment]
Yup, while I agree this needs more love with perhaps the most visited resource, potential mock-ups should not break the underlying concept of the linearity (rightly pointed by Berkeley).  

Also to consider that this page needs to be rendered on mobile devices (smaller view ports) and the aside.

Looking forward to a more accessible change though.

**Comment by DanStockham** [comment]
I agree with Berkeley. The idea of putting the sections in certain categories and having them stand on their own would confuse the beginner. Most newbies are used to a linear progression when learning a new trade. A general IT approach of learning is picking a category and just learning it. Everything else just falls in line as long the learner is meeting an objective. It would be a shock for those with non-technical IT backgrounds and the bulk of our new members consist of them.

**Comment by hallaathrad** [comment]
Perhaps I've misunderstood the opening post, but the way it sounds to make, @dewhiz wanted to show the "list" in a more understandable way, by visually segmenting the chapters while respecting the linear structure, yet it was never implied breaking it into parallel learning paths.

Having thought of some myself, I do believe there are ways to keep it as @BerkeleyTrue correctly puts it, but with a much better and more understandable visual metaphor. And I've explained I'm curious about other people's input on how we can improve it, as long as we keep the forementioned requirements. Maybe I should've expressed it in my previous comment but I took it for granted.

Let's see options! :) at worst, we can just not take the changes, but it's an interesting intellectual and technical exercise. Even something that can be added to your portfolio as information architecture and design.

**Comment by hrokr** [comment]
@dewhiz - Perhaps a good start for a mockup would be color code the main sections (front end, back end and data visualizations, plus non-profit projects, etc). You could then break down the subsections while still keeping the order but increasing the lightness or darkness. So Objects might be #ff0000 with the next section, JSON, being #b30000.

[http://www.w3schools.com/colors/colors_picker.asp](W3 color picker)

**Comment by dogwaddle** [comment]
@dewhiz ya the map seems fine in the sense that it's serving its purpose, a straight, linear, focused progression. I'd imagine a separate resource would be better for what you had in mind. Say an interactive mind map, linking concepts and topics? Linked to later in course to help aid in developing a larger context a and mental picture.

**Comment by QuincyLarson** [comment]
Discussion on this has stalled out, so I'm closing this issue. We are keeping the map linear for the reasons that @BerkeleyTrue mentioned, but making it easier to drill into specific topics. Here's my mockup if you're interested: http://codepen.io/FreeCodeCamp/full/VKXyZJ
