### ISSUE TITLE
Creating random quote machine

### ISSUE THREAD

**Issue by redixhumayun** [FreeCodeCamp/FreeCodeCamp#8815]
Challenge [Build a Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My codepen link is provided below 
http://codepen.io/redixhumayun/pen/zqeXyB?editors=0001

In the code, I have provided the link for the API I am using for my random quote generator, but I have no idea how to access the data contained in the JSON object provided by the API. Is the name of the object Object? Do I need to parse the data to access the data in JavaScript notation? I have tried using JSON.parse(Object) and JSON.parse(json) but nothing seems to be working. Any help would be greatly appreciated.

**Comment by erictleung** [comment]
@redixhumayun GitHub issues are only for issues with the site. Code review questions should be asked in the Gitter rooms. The one most appropriate with your question may be in the [Front End Help Room](https://gitter.im/FreeCodeCamp/HelpFrontEnd). Happy coding!

**Comment by vaibsharma** [comment]
Hi 
I am Vaibhav Sharma . Recently while doing Random Quote Machine API based project , in the reference code of the project (which I opened just for the reference)I found the qoutes are missing the right qoute icon. 
You can see them in the attached file.
![screenshot from 2016-07-09 17 39 05](https://cloud.githubusercontent.com/assets/15328723/16707887/dc460422-45fc-11e6-93e9-dc3cc498d0f7.png).
I want you to review this bug .
Thank you
