### ISSUE TITLE
Changing color of h2 with classes 

### ISSUE THREAD

**Issue by labrat10001** [FreeCodeCamp/FreeCodeCamp#8816]
It will do all the steps it just won't change the h2 color 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@labrat10001 thanks for the issue but if you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
