### ISSUE TITLE
Zipline marked as "done" but I haven't done it.

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/freecodecamp#882]
Challenge http://www.freecodecamp.com/challenges/zipline-build-a-random-quote-machine has an issue.

The Zipline - Build a Random Quote Generator has been marked as "done" but I haven't done it nor have I clicked the "done" button. I have clicked links to other peoples codepen through Slack for this challenge - might there be a bug?

**Comment by QuincyLarson** [comment]
That's really strange. This is the first I've heard of this. There is no way that visiting a codepen would trigger this. Perhaps someone added you as their pair on one of their ziplines? This is would result in the challenge already being completed for you.
