### ISSUE TITLE
h2 element should be red 

### ISSUE THREAD

**Issue by Shreyas1994** [FreeCodeCamp/FreeCodeCamp#8821]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3Ared%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

#### Issue Description

Even though the code is correct it says h2 element should be red 

#### Browser Information

* Browser Name, Version: Google chrome
* Operating System: Android marshmallow
* Mobile, Desktop, or Tablet: mobile

#### Your Code

```js
<style>
  .red-text {
    color:red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Shreyas1994** [comment]
<style>
  .red-text {
    color:red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by raisedadead** [comment]
@Shreyas1994 you can use backticks to format code:
https://guides.github.com/features/mastering-markdown/
<code>\`\`\`</code>

I have done this for you.

**Comment by BerkeleyTrue** [comment]
```
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by raisedadead** [comment]
On a side note I am able to pass this challenge with your code after, resetting the code (using RESET Button).

Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

Let us know if you are still facing issues

**Comment by ltegman** [comment]
There's an illegal whitespace character in your input, which is why resetting the code and typing it manually fixes the error. CSS is very picky about whitespace characters. To avoid this problem please always type your answer by hand rather than copying and pasting any of it from somewhere else (even from our own page). Thanks and happy coding!
