### ISSUE TITLE
404 File Not Found 

### ISSUE THREAD

**Issue by m-henderson** [FreeCodeCamp/FreeCodeCamp#8823]
When clicking the WikiCentral link I am directed to a page with 404 error. 
I have pointed out the WikiCentral link with a red arrow in the image below.

![1](https://cloud.githubusercontent.com/assets/16070192/15613420/fc57fa8e-23f8-11e6-85dc-2292b8115c6f.png)

I have provided an image below this sentence to show you what the page looks like that I am directed to after clicking the WikiCentral link. 

![2](https://cloud.githubusercontent.com/assets/16070192/15613497/59addad2-23f9-11e6-8cb7-c78ee8b0b9b8.png)

You can regenerate the issue by doing the following: Go to freecodecamp.com > click About > click Wiki > then scroll down to Guides On How to Contribute and click the WikiCentral link in that first sentence directly under How to Contribute. 

OR: go directly to WikiCentral via link https://freecodecamp.github.io/wiki/en/Wiki-Central

* Browser Name, Version:  **Firefox 46.0.1**
* Operating System: **Windows 7**
* Mobile, Desktop, or Tablet: **Desktop**

**Comment by atjonathan** [comment]
@m-henderson We recently moved all our links to lowercase: The file can be found with the same filename, just lowercase here: http://freecodecamp.github.io/wiki/en/wiki-central/

**Comment by atjonathan** [comment]
@m-henderson I've moved this issue over to the wiki repo: FreeCodeCamp/wiki#1050. Thanks for the report!

**Comment by m-henderson** [comment]
@atjonathan  the Wiki Central link pointed out in the image with the red arrow needs to be updated to contain the link without capitalization. Until that link is updated users will be sent to the 404 page if they click Wiki Central under Guides on How to Contribute

**Comment by m-henderson** [comment]
@atjonathan sorry, we replied at the same time. no problem and happy coding (:
