### ISSUE TITLE
please, help me 

### ISSUE THREAD

**Issue by Tsadoila** [FreeCodeCamp/FreeCodeCamp#8826]
Challenge [Inherit Styles from the Body Element](https://www.freecodecamp.com/challenges/inherit-styles-from-the-body-element#?solution=%0A%3Cstyle%3E%0A%20%20body%7B%0A%20%20%20%20background-color%3Agreen%3B%0A%20%20%20%20font-family%3AMonospace%3B%0A%20%20%7D%0A%0A%3C%2Fstyle%3E%3Ch1%3E%20Hello%20World%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body{
    background-color:green;
    font-family:Monospace;
  }

</style><h1> Hello World</h1>

```

**Comment by zagu** [comment]
I had the same issue with Firefox. Switched to Chromium(Chrome) and it worked.

**Comment by EximiusPrime** [comment]
Your code is wrong

<style>
    body {
                 background-color:black;
                 font-family:Monospace;
                 color:green;
}

</style><h1> Hello World</h1>

**Comment by texas2010** [comment]
@EximiusPrime, Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by zagu** [comment]
That's just sad @texas2010, the fact that you actually had to remove his code, he was only trying to help in an old thread.

**Comment by texas2010** [comment]
@zagu, this thread is only issue tracker.  this place is not for help people in here.  they have to use chat room or forum.  sorry

**Comment by EximiusPrime** [comment]
My bad @texas2010 didn't mean to break the rules. :/ Now I know for next time.

**Comment by texas2010** [comment]
@EximiusPrime, nah you didnt break the rules.  all good now

**Comment by muhmaadd** [comment]
<style>
  body {
    color: green;
    font-family: Monospace;
  }
 
  .h1 {
    color: green;
  }
</style>

<h1 class="h1">"Hello World"</h1>
