### ISSUE TITLE
Multiple li closing brackets fail last check

### ISSUE THREAD

**Issue by radujica** [FreeCodeCamp/freecodecamp#883]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Adding 2 or more li ending brackets fails the last check of "Make sure your li element has a closing tag."

![li](https://cloud.githubusercontent.com/assets/8166962/8079076/8d75e2f8-0f62-11e5-9098-2e3d0296987f.jpg)

**Comment by QuincyLarson** [comment]
Thank you for catching this new bug that we accidentally seem to have introduced last night. I've fixed this.
