### ISSUE TITLE
Access Array Data with Indexes... var myData = [0] is the correct answer... not var myData = [1]

### ISSUE THREAD

**Issue by marcelpirata** [FreeCodeCamp/FreeCodeCamp#8831]
Challenge [Access Array Data with Indexes](https://www.freecodecamp.com/challenges/access-array-data-with-indexes#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20ourData%20%3D%20ourArray%5B0%5D%3B%20%2F%2F%20equals%201%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20myData%20%3D%20%5B0%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
var ourData = ourArray[0]; // equals 1

// Setup
var myArray = [1,2,3];
var myData = [0];

// Only change code below this line.


```

**Comment by sludge256** [comment]
Correct me if I'm wrong.

I believe there's an issue with the test:
```js
assert((function(){if(typeof myArray != 'undefined' && typeof myData != 'undefined' && myArray[0] == myData){return true;}else{return false;}})()
```

[link](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a2dbb61062e4857b49890b119406ca2ad0fa4a02/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1695)

`myArray[0]` has the value of 1.
`myData = [1]` would give you the value of [1].

`myArray[0] == myData` :point_right: `1 == [1]` :+1: which should not be an accepted answer.

**Comment by bugron** [comment]
@marcelpirata thanks for posting this issue!
Neither `var myData = [0]` nor `var myData = [1]` is a correct answer. And I don't see any issue with the test. This challenge asks you to create a variable called `myData` and set it to equal the first value of `myArray`. First value of `myArray` is 1, not `[1]`, thus `myArray[0] == myData` equals to `1 == 1` which is true.
Closing this issue.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by sludge256** [comment]
@bugron You can pass with `var myData = [1];`

**Comment by bugron** [comment]
@sludge256 I'm sorry, seems I misunderstood the issue.

**Comment by junzy** [comment]
Can i take this up?

**Comment by bugron** [comment]
@junzy sure, go ahead.
