### ISSUE TITLE
Update GIFs and screenshots on Getting Started Challenges

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#8839]
Some GIFs and screenshots on the following challenges need updated, as they show older versions of the site and branding:
- [x] [Create a GitHub account and join our chat rooms](https://www.freecodecamp.com/challenges/create-a-github-account-and-join-our-chat-rooms)
- [x] [Configure your code portfolio](https://www.freecodecamp.com/challenges/configure-your-code-portfolio)
- [x] [Join a campsite in your city](https://www.freecodecamp.com/challenges/join-a-campsite-in-your-city)
- [x] [Learn what to do if you get stuck](https://www.freecodecamp.com/challenges/learn-what-to-do-if-you-get-stuck)

## Examples:

**_Older version of the site_**

![image](https://cloud.githubusercontent.com/assets/11198912/15627547/8f27d712-24df-11e6-8b2d-b4d33a58e3e4.png)

_**Needs changed to the new green background: `#006400`**_

![image](https://cloud.githubusercontent.com/assets/11198912/15627552/b723b0a6-24df-11e6-94d5-67713ee47198.png)

**Comment by myou11** [comment]
Hello, I am new to contributing, and I would like to tackle this issue, but I want to make sure I have the right idea first.

So, the issue is that the background color on these pages are outdated and they just need changing? Also, I have cloned the repo, but I don't see any HTML or CSS files in it; is that intentional?

**Comment by atjonathan** [comment]
Hey @myou11 :smile:, these are just images or gifs that need edited in an application like photoshop with the changes, uploaded to imgur and then you need to update the relevant JSON with the new links.

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by saqibnaveed** [comment]
Hey, I am also new here. If this is not resolved can I contribute to this?

**Comment by atjonathan** [comment]
@saqibnaveed, certainly! It doesn't seem to have been picked up by anyone yet...

**Comment by saqibnaveed** [comment]
I want to work on this.. please guide me

**Comment by Lehmax** [comment]
It would be a good idea not to use GIF this time and webm instead. It doesn't look like a slideshow with reduced colors AND takes up less space.

**Comment by atjonathan** [comment]
I will take this on 👍

**Comment by dhcodes** [comment]
@atjonathan lol, I just thought to myself, 'I could do this', and then I scroll down and see your comment.
