### ISSUE TITLE
Mistake in the action description.

### ISSUE THREAD

**Issue by arturjonczyk** [FreeCodeCamp/freecodecamp#884]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-out-html has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
Screen shot:
https://dl.dropboxusercontent.com/u/2931218/Waypoint-%20Comment%20out%20HTML%20-%20bug%20-2015-06-10.png

**Comment by QuincyLarson** [comment]
Thanks for catching this. I've fixed this.
