### ISSUE TITLE
level of difficulty / scope of challenge / further explanations

### ISSUE THREAD

**Issue by MaxSchumacher** [FreeCodeCamp/FreeCodeCamp#8841]
Challenge [Build a Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) has an issue.

I've spent quite a lot of time on this task and undoubtedly learned a lot. Still, I feel like there should be additional explanations regarding two issues to help people get started.

**Sharing on Twitter**
For example, pointing users to the Twitter Web Intents documentation (https://dev.twitter.com/web/intents) would be helpful. Figuring out that the Tweet button that results from the button generator turns into an iframe for which it is not straight-forward to include custom parameters is needlessly frustrating (e.g. standard web APIs like element.innerHTML fail for no obvious reason).

**Frontend-API-calls & CORS**
Also, the various problems related to CORS (e.g. making API requests from the frontend) should at least be mentioned; the fact that jQuery conveniently abstracts this problem away does not help here.
I've used plain DOM-APIs and the new fetch()-feature and ran into quite some trouble. jQuery is on its way out and this should be reflected in a course for beginners. Just hard-coding a couple of quotes is not truly "random" - an external quote API should be used; some additional information on that topic would have been helpful.

**Comment by abhisekp** [comment]
> jQuery is on its way out 

I don't agree with that as in a production environment, one cannot conclude about a user's browser type. Also jQuery gives an API much easier to use than the DOM API.

> Just hard-coding a couple of quotes is not truly "random" - an external quote API should be used

I agree about adding more helpful information about quote APIs. But as a beginner, one may hard code and build the system and it should also be accepted.

**Comment by MeonAigeanta** [comment]
As a beginner, I think this challenge's instructions could be improved by explicitly stating if creating JSON objects is the goal (hard-coding is OK) or if using an API to generate the objects is the preferred method.  Separating the challenge into two one for testing object manipulation and the other for using external APIs would also solve the problem.

**Comment by systimotic** [comment]
Hi all! Some good points are made here. The projects are being redone in the curriculum expansion. Discussion of this can be continued in https://github.com/FreeCodeCamp/CurriculumExpansion/issues/59
