### ISSUE TITLE
This is a buggy challange

### ISSUE THREAD

**Issue by orenyny** [FreeCodeCamp/FreeCodeCamp#8843]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%20shed%20everywhere%3C%2Fp%3E%20%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet shed everywhere</p> 
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

The instructions on this challenge are very confusing, unlike all previous challenges and it takes a long time to understand what you require to be done, which is a shame. Thanks!

**Comment by erictleung** [comment]
@orenyny thanks for the feedback. What do you suggest on changing to make it more clear on what the challenge requires?

**Comment by paprzytula** [comment]
I think the challenges with "add something" should also include information about the line and in some cases even the column where the code should be implemented.

**Comment by erictleung** [comment]
@paprzytula the only things about this challenge that could be more clear is where the new `p` element should go and maybe on how to add additional CSS properties.

In the case, I think the instructions could be rewritten to be:

> Create a second `p` element **after the existing `p` element** with the following kitty ipsum text: ...

The second set of instructions I think are clear enough on what it wants. However, from a new coder's perspective, I could see how it might be unclear what needs to be done because up until this challenge, you haven't been asked to put two CSS rules together.

A change for the adding a new CSS property would be to give an example for it like:

> Example
> ```css
> h1 {
>   font-size: 30px;
> }
> h2 {
>   font-size: 20px;
> }
> ```
> 

cc/ @FreeCodeCamp/issue-moderators comments on how much guidance we should give?

**Comment by raisedadead** [comment]
> Create a second `p` element **after the existing `p` element** with the following kitty ipsum text: ...

:+1: for this. 

Any further guidance is not wise IMHO, part of the challenge is to figure out what is to be done. And the above modification should do it.

This is one of the simplest challenges yet, and that should the set the tempo for the next ones.
I like adding the example as well.

**Comment by Pasayadaan** [comment]
If it's not taken up, I can try.

**Comment by erictleung** [comment]
@Pasayadaan go for it. Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.
