### ISSUE TITLE
Challenge [Accessing Objects Properties with Variables]: confusing error message

### ISSUE THREAD

**Issue by lenzai** [FreeCodeCamp/FreeCodeCamp#8844]
Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%3D%2016%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%5B16%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber= 16;       // Change this Line
var player = testObj[16];   // Change this Line

```

The test fails is "You should use bracket notation to access testObj", that's quite confusing.

**Comment by erictleung** [comment]
@lenzai thanks for the feedback. It does seem confusing that you are using bracket notation correctly but the test is failing. The test actually is checking for the specific use of `playerNumber` within the brackets. Maybe the test should be more specific and have an additional test:

> You should use bracket notation to access `testObj`
>
> You should be using the variable `playerNumber` in your bracket notation 

The first test should be changed to:

```
"assert(/testObj\\s*?\\[*?]/.test(code),'message: You should use bracket notation to access <code>testObj</code>');",
```

And the second test should be:

```
"assert(/testObj\\s*?\\[\\s*playerNumber\\s*\\]/.test(code),'message: You should be using the variable <code>playerNumber</code> in your bracket notation');"
```

**Comment by frankkiogora** [comment]
if you follow the example given, you will notice that var player should be set equal to  the value (var) and not the value of var. Makes sense? var player=[playerNumber];

**Comment by Kaence** [comment]
// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16;       // Change this Line
var player = testObj[playerNumber];   // Change this Line
