### ISSUE TITLE
Check for Palindromes failing to remove non aplhanumerics.

### ISSUE THREAD

**Issue by ecchioni** [FreeCodeCamp/FreeCodeCamp#8846]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20start%20%3D%200%3B%0A%20%20var%20end%20%3D%20str.length%20-%201%3B%0A%20%20str%20%3D%20str.replace(%2F%5CW%2B%2F%2C%22%22)%3B%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20while(start%20%3C%20end)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if(str%5Bstart%5D%20!%3D%3D%20str%5Bend%5D)%0A%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%20%20start%2B%2B%3B%0A%20%20%20%20%20%20end--%3B%0A%20%20%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
The code fails to remove the non alphanumeric chars from the string.
My code:
```javascript

function palindrome(str) {
  // Good luck!
  var start = 0;
  var end = str.length - 1;
  str = str.replace(/\[W_]+/,"");
  str = str.toLowerCase();
  while(start < end)
    {
      if(str[start] !== str[end])
        return false;
      start++;
      end--;
    }
  return true;
}



palindrome("eye");

```

**Comment by erictleung** [comment]
@ecchioni please reread the instructions on dealing with non-alphanumeric characters.

> You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

Happy coding!

**Comment by ecchioni** [comment]
Are you sure you read the code?

**Comment by erictleung** [comment]
@ecchioni I did and there is an issue with your code. If you get stuck with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). If your issues is not with the code but on how the challenge tests your code, can you describe the issue you're having in more detail?

**Comment by Achillesthewarrior** [comment]
palindrome("five|\_/|four");

function palindrome(str) {

       return str; 
}

output it is giving is : five|_/|four"

For the same reason could not solve palindrome problem.

**Comment by Achillesthewarrior** [comment]
palindrome("five|\_/|four");

function palindrome(str) {
return str; 
}

output is : five|_/|four

How \ is automatically removed?

**Comment by Achillesthewarrior** [comment]
just like it happened in above example??

**Comment by erictleung** [comment]
@Achillesthewarrior the backslash `\` is an escape character and is tries to escape special characters if necessary. If you have more questions, please ask them to the [Help Room](https://gitter.im/FreeCodeCamp/Help).
