### ISSUE TITLE
tests using consistent logic?

### ISSUE THREAD

**Issue by dwilbank68** [FreeCodeCamp/freecodecamp#885]
I could probably come up with some fancy logic to pass these tests, but is that justified?

friendly(['2015-07-01', '2015-07-04']), ['July 1st','4th']                             // drops the year completely
friendly(['2015-12-01', '2016-02-03']), ['December 1st','February 3rd']   // drops the years
friendly(['2015-12-01', '2017-02-03']), ['December 1st, 2015','February 3rd, 2017'] // keeps the years
friendly(['2016-03-01', '2016-05-05']), ['March 1st','May 5th, 2016']       // keeps the year!

Why should input 4 retain a year, while input 1 and 2 drop the year?

Thanks

**Comment by terakilobyte** [comment]
While I agree it's a bit odd, it does force you to exercise control flow. I'll ask the original author of this bonfire what this was inspired by but don't see a good reason at the moment to remove this test other than to make it easier.

**Comment by dwilbank68** [comment]
Yes, a side effect would be that the problem would need to surrender one of
its difficulty flames. As long as you agree it's a bit inconsistent though.

**Comment by BerkeleyTrue** [comment]
fixed
