### ISSUE TITLE
Escaping Literal Quotes challenge test is unclear

### ISSUE THREAD

**Issue by Blazer433** [FreeCodeCamp/FreeCodeCamp#8850]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22(I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22).%22%3B%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "(I am a \"double quoted\" string inside \"double quotes\").";




```

**Comment by HenrySanches** [comment]
RIght, I would want to dig into this code

**Comment by Carlosmcoelho** [comment]
Solution should be:
Variable myStr should equal to (**I am a "double quoted" string inside "double quotes"**).

and your solution is:
 **(I am a "double quoted" string inside "double quotes").**

**Comment by BKinahan** [comment]
```
Variable myStr should equal to (I am a "double quoted" string inside "double quotes").
```
The parentheses in the test message are confusing and ambiguous, though I think they were added recently to clear up confusing ambiguity. Probably no perfect solution here 😄

**Comment by erictleung** [comment]
@Blazer433 thanks for the issue. Your code doesn't require the parentheses. Looking at that last test, I can see how there can be confusion on what the string should be.

We've had lots of issues on this challenge. Looking back at a [previous issue](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8183), I think a little edit to [a suggestion](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8183#issuecomment-211731358) on changing the test to this will help:

> Variable `myStr` should be **contain** the string: `I am a "double quoted" string inside "double quotes".`

I changed the wording to "contain" because I think the word "equals" could be interpreted as a coding-kind-of equals (i.e. `var myStr EQUALS string;`), which may have people copy-pasting that string. I think that should help clear up some confusion.

cc/ @FreeCodeCamp/issue-moderators

**Comment by erictleung** [comment]
Anyone wanting to fix this, [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L976) needs to be changed to what is below.

```js
"assert(myStr === \"I am a \\\"double quoted\\\" string inside \\\"double quotes\\\".\", 'message: Variable <code>myStr</code> should contain the string: <code>I am a \"double quoted\" string inside \"double quotes\".</code>');"
```

This is what it should look like:

![image](https://cloud.githubusercontent.com/assets/2754821/15659997/b8e1913c-2689-11e6-9b64-950a3dc229d4.png)


Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any questions about helping. We're there to help.

**Comment by daniel-chung** [comment]
Since I haven't see any activity on this thread for almost a week, I decided to take a crack at this. Will be submitting a PR shortly.

**Comment by AlenaHall** [comment]
What all do you know how to do with coding, if I may ask.

On Sunday, June 5, 2016, Daniel Chung <notifications@github.com> wrote:

> Since I haven't see any activity on this thread for almost a week, I
> decided to take a crack at this. Will be submitting a PR shortly.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8850#issuecomment-223851704>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASbzOl0xAzGbwKhnx8UG_eiSTc-7nJK0ks5qI3mOgaJpZM4IpR-_>
> .
>


-- 
Cadet Hall

**Comment by daniel-chung** [comment]
@Blazer433 I think it makes sense to keep this issue open for the time being because the pull request hasn't been merged yet (and the issue has not been fully addressed).

@AlenaHall do you mind clarifying what you mean? Thanks!

**Comment by OakerMin** [comment]
I managed to solve it after a few tries. turns out there's a full stop at the end of the sentence. And guys  make sure you have no spaces in between the backslashes and quotes and your next letter in line
