### ISSUE TITLE
Will this set of front end courses include mobile device's front end design and the usage of photoshop?

### ISSUE THREAD

**Issue by cmal** [FreeCodeCamp/FreeCodeCamp#8851]
Will the front end courses include the specific front end design for mobile devices? not the responsive front-end framework.
Will the front end courses include the usage of photoshop? or is the skills of photoshop indispensable in front end design?
Thanks very much!

**Comment by erictleung** [comment]
@cmal thanks for the suggestions. Although they would be great content to teach, I don't think the curriculum will change anytime soon to include any mobile-specific design challenges or challenges requiring Photoshop. These may be too specific for our curriculum, as ours is directed to just new coders.

cc/ @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
This looks really wide to me. UI Design targets specific audiences and while important is generally not an mandatory requirement to learn to code. These can be take up as video courses IMHO as supplements.

Let's keep this off GitHub issues list unless confirmed as a request, I would urge you to discuss this in the forums or the chat rooms first, and then re-open.

To be closed if other moderators agree.

**Comment by atjonathan** [comment]
Closing. Feel free to open an issue on our wiki or hikes repos. However, we won't be integrating this content into the main curriculum, thanks!
