### ISSUE TITLE
Spinal Tap Case Missing Parenthesis

### ISSUE THREAD

**Issue by twmilli** [FreeCodeCamp/FreeCodeCamp#8852]
#### Spinal Tap Case intermediate algorithm
https://www.freecodecamp.com/challenges/spinal-tap-case

#### Issue Description
3rd test case is missing a closing parenthesis.  This does not really affect my experience with the challenge too much I just felt like it is something that should be fixed and would be an easy fix.  I would be interested in doing it just for fun if possible

#### Browser Information
Google Chrome, Mac OSX Yosemite

#### Screenshot
![screen shot 2016-05-29 at 6 13 53 pm](https://cloud.githubusercontent.com/assets/15217013/15636336/27288626-25c9-11e6-94f9-e39214342cee.png)

**Comment by erictleung** [comment]
@twmilli thanks for the issue. So I do see the same thing but if you zoom out, you can actually see the closing parentheses.

![image](https://cloud.githubusercontent.com/assets/2754821/15636404/165a1a56-25b2-11e6-93ea-3a0890e4ca23.png)

Related #8390.

cc/ @hallaathrad

**Comment by Bouncey** [comment]
Could we add a '<wbr>'  somewhere in 'The_Andy_Griffith_Show'?

**Comment by Bouncey** [comment]
Oh hahaha forgot the escapes

A '&lt;wbr&gt;'
