### ISSUE TITLE
Incorrect text editor behavior. Enter, new line, arrow keys, mouse position (windows 10, google chrome)

### ISSUE THREAD

**Issue by designofhumanity** [FreeCodeCamp/FreeCodeCamp#8853]
I think this is general text editor behavior. For exmaple use arrow keys to correct mouse cursor position
https://www.freecodecamp.com/challenges/taste-the-bootstrap-button-color-rainbow

![arrowkeyerror](https://cloud.githubusercontent.com/assets/2714036/15647281/4b4d0f48-266b-11e6-9731-cb7570e75d78.png)
26 times press right arrow and 27 unexpected new line
![backarrowerror](https://cloud.githubusercontent.com/assets/2714036/15647442/40e0ccc4-266c-11e6-9ddf-7dde089efe23.png)
when press left arror key at the begining of line. Cursor appears not an the end of previous line.
Sometimes backspace solve thin problem (сome down to the line below and press backspace)

**Comment by erictleung** [comment]
@designofhumanity can you be more specific on what behavior issues you are having?

**Comment by designofhumanity** [comment]
![image](https://cloud.githubusercontent.com/assets/2714036/15646960/7579ebee-2669-11e6-99cf-b2149745a1fb.png)

**Comment by designofhumanity** [comment]
pls look at this, and analog situation with other cursor position like press enter, backspace and so on

**Comment by designofhumanity** [comment]
look at screen shots and pls ublock i think it is very uncomfotable web
text editor abblock off, firerox have the same issue

2016-05-30 12:41 GMT+03:00 Eric Leung <notifications@github.com>:

**Comment by erictleung** [comment]
@designofhumanity this issue has been persistent for a while (#7847 recently closed). The editor is by [CodeMirror](https://github.com/codemirror/CodeMirror) so any bugs are mostly out of our control. 

cc/ @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
@erictleung we should close this, re-open the original and continue the discussion there.
