### ISSUE TITLE
Italian Translation of Getting Started translation

### ISSUE THREAD

**Issue by ArmendBerisha** [FreeCodeCamp/FreeCodeCamp#8856]
- [ ] Getting started

**Comment by tjgerot** [comment]
Thank you for opening this issue, as errors in translation are difficult to find without help from multilingual individuals. I took a look at Google Translate's translation of the label "Getting Started" at it displayed it as _Iniziare_, which translates back to English as _To start_. What translation would you suggest instead? Also, just to keep all the bases covered, what browser (Chrome, Firefox, Safari) are you using when you access FreeCodeCamp.com ? Thank you!

**Comment by ArmendBerisha** [comment]
I've already posted the question to the Italian translation room, but looking at some user guides in English and comparing them with the Italian version they often use "Introduzione" for "get started". So at the moment I will say " Introduzione a FreeCodeCamp ". I will wait for some suggestion by the translation room. Currently I'm using Chromium. I hope this is helpful! :+1:

**Comment by cla63** [comment]
Per iniziare

**Comment by Em-Ant** [comment]
I put a stub translation on the [chat channel](https://gitter.im/FreeCodeCamp/TranslationItaliana). I don't see any active PR about this issue. @ArmendBerisha do you want to open one ? You can even use use my translation as starting point if you think it is ok. Or I can open a PR on my own. Just let me know. Thanks.

**Comment by Em-Ant** [comment]
Ok. I'm workin on this.
