### ISSUE TITLE
Create new sample certificates with fixed date format

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8858]
We need to capture new certificates with the updated format, and reapply our sample watermark.

![](https://www.evernote.com/l/Ar_9MJTxO6JMbZIorGG91CTGWi_OWvTOFWgB/image.png)

**Comment by atjonathan** [comment]
To contributor: Wait until #8859 has been fixed, before tackling this one!

**Comment by raisedadead** [comment]
Not a first timers one! :sweat_smile:

**Comment by pietromenna** [comment]
Can I try this issue?

**Comment by atjonathan** [comment]
@pietromenna, we need to wait until #8859 has been addressed. Feel free to try and tackle that one first!

**Comment by atjonathan** [comment]
@pietromenna, you can give this issue a shot now :smiley:

**Comment by Trion129** [comment]
Can I try this one? :smile:

**Comment by raisedadead** [comment]
@Trion129 yup.

**Comment by Trion129** [comment]
I made the new samples and uploaded them to imgur at http://imgur.com/a/EMeqm 
I don't know where in the code should I change the old links. If they are in some database then I don't think this would need a pull request :yum:

**Comment by raisedadead** [comment]
@Trion129 

Thanks a lot for the hard work. Some are a bit noisy though (I know I am being picky), Did you just photoshop the old ones? Maybe I can help ya a bit on getting some clean ones. Hit me up on [gitter](https://gitter.im/raisedadead).

You will have to make a pull request to change the images starting at [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/00-getting-started/getting-started.json#L48).

Be careful that you have to replace the image URL's at their each occurrence, a good way to do that would be to search in the entire file.

And one more point, I think we would be making the logo on the certificate green (currently brown), will confirm on this.

You can visit the [assets repo](https://github.com/FreeCodeCamp/assets) for anything that you may need. My advice make a separate PR and add these there as well?

/cc @QuincyLarson
