### ISSUE TITLE
Fix date format on certificates

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8859]
We need to change the date format on our certificates. Currently it's 
January, 15th 2016
It should be:
January 15, 2016

Note that the comma needs to be moved, and the date should just be a natural number, not an ordinal number.

![](https://www.evernote.com/l/Ar9fN3rYcAdNbZPD9bcrWGqbNUmjh2SjcgkB/image.png)

**Comment by sanskar-modi** [comment]
Can i try this issue ??

**Comment by atjonathan** [comment]
@sanskar-modi, this issue has already got 2 Pull Requests! Checkout our other `help wanted` issues here: https://github.com/FreeCodeCamp/FreeCodeCamp/labels/help wanted.
