### ISSUE TITLE
Change ordered list to unordered list in project challenges

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8867]
#### Challenge Name

Any of the project challenge pages (e.g https://www.freecodecamp.com/challenges/show-the-local-weather)

#### Issue Description

Currently, the project challenges have an ordered list, listing the requirements and instructions for the challenge. However, I think there are too many "lists" as there is a bulleted list and the numerical list.

Firstly, I remember reading someone making an issue or comment on how the rule numbers usually make a weird contrast with its list number, like so where `Rule #1` is listed as `#2` in the list:

![image](https://cloud.githubusercontent.com/assets/2754821/15667074/1fd2662a-26c9-11e6-8c02-fc12a2a1aa02.png)

Secondly, there appears to be a redundancy in "lists," where you have the check boxes but also the numbered list items. Each item is already separated by spaces so I don't think you _really_ need the numbers. 

Numbers in a list, in my opinion, should have some meaning to it like needing to know there are 3 or 4 requirements for something. But in this case, the numbers don't really tell you much except there are 10 or so lines to read, which knowing the number is inconsequential to solving the challenge.

#### Proposed Fix

Change the ordered list to an unordered one. To make these changes, I think all we'd need to do is change [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/challenges/showZiplineOrBasejump.jade#L11) from `ol` to `ul` (correct me if I'm wrong). Overall, I think these changes will give a cleaner look to the challenges.

#### Screenshot

**Currently**:
![image](https://cloud.githubusercontent.com/assets/2754821/15666586/5db1625a-26c6-11e6-94ba-7550212e6d53.png)

**Proposed Change**:
![image](https://cloud.githubusercontent.com/assets/2754821/15667034/e2a4f0ce-26c8-11e6-8878-6073668d31f0.png)

cc/ @hallaathrad

**Comment by atjonathan** [comment]
In agreement, :+1:

**Comment by sanskar-modi** [comment]
can i try this or there is more discussion on this ??

**Comment by atjonathan** [comment]
@sanskar-modi let's wait for @hallaathrad opinion!

**Comment by hallaathrad** [comment]
Hmm haven't checked on all cases, but at least right now it makes a lot of sense to me. I'd say we take it, and then if any specific challenge requires an ordered list, we go an fix it on a case by case. 
LGTM

**Comment by erictleung** [comment]
We could probably go without the checkboxes as well.

![image](https://cloud.githubusercontent.com/assets/2754821/15690015/52b8b9dc-2736-11e6-947b-95dbf1158c99.png)

We could probably center the list a little as well. I just did a quick HTML change to show what it'll look like.

**Comment by hallaathrad** [comment]
Perfect, now a matter of removing the space on the left of the list, and we should be golden. 
what do you think @FreeCodeCamp/issue-moderators ?

**Comment by raisedadead** [comment]
Yup, lets save some more real estate!

**Comment by atjonathan** [comment]
@hallaathrad @raisedadead, yeah let's do it!

**Comment by atjonathan** [comment]
@sanskar-modi, feel free to tackle this now! We have decided to remove the checkboxes and numbers.

**Comment by dhcodes** [comment]
Looks like this has been fixed. Reopen if I'm mistaken.
