### ISSUE TITLE
Challenge 109 - Replace Text "replace with." with "replace."

### ISSUE THREAD

**Issue by VincentDiCarlo** [FreeCodeCamp/FreeCodeCamp#8868]
#### Challenge Name

https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery

#### Issue Description

Possible error in diction in text.  Suggest replacing "replace with." with "replace."

#### Browser Information

Not relevant.

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@VincentDiCarlo thanks for looking into this but I don't think there needs to be a change. 

> In other words, this function will not evaluate any HTML tags passed to it, but will instead treat it as text you want to replace with.

The text you pass into the function is the "text you want to replace with" rather than just the "text you want to replace." You want to replace the existing text. Maybe it could be changed to:

>  In other words, this function will not evaluate any HTML tags passed to it, but will instead treat it as **the** text you want to replace **the existing text** with.

**Comment by atjonathan** [comment]
@erictleung In your suggestions, the word **text** is too repetitive. What about:

> In other words, this function will not evaluate any HTML tags passed to it, but will instead treat it as text you want to replace **the existing content** with.

**Comment by erictleung** [comment]
@atjonathan sounds good to me!

Those wanting to fix this, [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/jquery.json#L628) needs to be changed to the following:

> In other words, this function will not evaluate any HTML tags passed to it, but will instead treat it as the text you want to replace the existing content with.

**Comment by WillySchu** [comment]
I have submitted a PR to address this issue.

**Comment by l-tong** [comment]
I will take this as a first timers :).

**Comment by atjonathan** [comment]
@l-tong #8884 has already addressed this issue!

**Comment by l-tong** [comment]
Got it.  thanks!
