### ISSUE TITLE
Zipline: Stylize Stories on Camper News - example issue in Firefox

### ISSUE THREAD

**Issue by kmiasko** [FreeCodeCamp/freecodecamp#887]
Example for Zipline: Stylize Stories on Camper News doesn't work properly in Firefox. It shows only one column of images.

changing -moz-column-fill from auto to balanced (or removing it fixes problem).

**Comment by QuincyLarson** [comment]
@kmiasko Thank you for reporting this issue. Hey @storbeck Could you update your CodePen real quick with this added attribute? Thanks for your fast help with this.

**Comment by storbeck** [comment]
Thanks for reporting this, I've updated the codepen and it appears to be working fine in Firefox.
