### ISSUE TITLE
I tried to submit my challenge but it doesnt got submitted

### ISSUE THREAD

**Issue by achalofficial** [FreeCodeCamp/FreeCodeCamp#8872]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@achalofficial If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by erictleung** [comment]
@achalofficial can you give us more information on the challenge and your code? It'll make helping you resolve this issue easier.

**Comment by raisedadead** [comment]
@achalofficial  Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by erictleung** [comment]
@achalofficial closing as stale. If you still have an issue, please make another issue and fill out the issue template with more details on your issue. Happy coding!
