### ISSUE TITLE
Streak On FCC having issues? 

### ISSUE THREAD

**Issue by m-henderson** [FreeCodeCamp/FreeCodeCamp#8878]
Hey guys , I do not mean to bore you or come here with lack of information but we are getting complaints about the streak on FCC not being correct. Could you guys check it out ? Also, here is the source of the complaints http://forum.freecodecamp.com/t/camper-streak-dates-off/6781

**Comment by twmilli** [comment]
Cool that you took the initiative to post this but this is already a known issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7925

**Comment by atjonathan** [comment]
Closing as duplicate. thanks for reporting!!
