### ISSUE TITLE
Test case error: Confirm the ending

### ISSUE THREAD

**Issue by basmaseyam** [FreeCodeCamp/FreeCodeCamp#8879]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20var%20substring%3B%0A%20%20var%20arr%3Dstr.split(%22%20%22)%3B%0A%20%20if(arr.length%3E1)%7B%20%0A%20%20substring%3Darr%5Barr.length-1%5D%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20substring%3Dstr.substr(str.length-1)%3B%0A%20%20%7D%0A%20%20if(substring%3D%3D%3Dtarget)%7B%0A%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0AconfirmEnding(%22He%20has%20to%20give%20me%20a%20new%20name%22%2C%20%22me%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the fifth test case it is written as follows : confirmEnding("He has to give me a new name", "me") should return true. while the ending is different (name) than the target (me).

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var substring;
  var arr=str.split(" ");
  if(arr.length>1){ 
  substring=arr[arr.length-1];
  }
  else{
  substring=str.substr(str.length-1);
  }
  if(substring===target){
  return true;
  }
  else{
    return false;
  }
}

confirmEnding("He has to give me a new name", "me");

```

**Comment by sludge256** [comment]
"He has to give me a new na**_me_**"

**Comment by basmaseyam** [comment]
Thank you for the fast reply
