### ISSUE TITLE
Typo in the 2nd instruction

### ISSUE THREAD

**Issue by meeshu** [FreeCodeCamp/freecodecamp#888]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-out-html has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The 2nd instruction currently reads "Leave your h2 element uncommented so that is **not** visible on your page"

It could instead be-"Leave your h2 element uncommented so that is visible on your page."

Thanks!

**Comment by QuincyLarson** [comment]
Nice catch! I've fixed this. Thanks!
