### ISSUE TITLE
Your h2 element should be red.

### ISSUE THREAD

**Issue by kanjicat** [FreeCodeCamp/FreeCodeCamp#8880]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.1.1; SM-T670 Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

I have made all required changes, but it still says the h2 element isn't red. I have tried entering the changes in a different order, and have tried clearing browser history and cache. Nothing seems to fix the issue.

**Comment by alistermada** [comment]
This seems to be the same problem reported in #8821.

> There's an illegal whitespace character in your input, which is why resetting the code and typing it manually fixes the error. CSS is very picky about whitespace characters. To avoid this problem please always type your answer by hand rather than copying and pasting any of it from somewhere else (even from our own page). Thanks and happy coding!
 \- **ltegman**

**Comment by raisedadead** [comment]
Closing as duplicate, @kanjicat please check the issue comment above and let us know if that works for you, as you can see this is pretty common when you copy paste.

Hope this helps, and @alistermada thanks for assisting.

P.S : Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by dreadfulman** [comment]
+1

**Comment by miguel361** [comment]
this is not working for me either and im not even copying and pasting it

**Comment by papapocho84** [comment]
hi
i only delete "h2" in the stylesheet and works!
