### ISSUE TITLE
No Requirements/ Can't Submit Code

### ISSUE THREAD

**Issue by KTDid95** [FreeCodeCamp/FreeCodeCamp#8882]
Challenge [Target the same element with multiple jQuery Selectors](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Everything was working just fine on this challenge until I tried to submit my code. I couldn't submit, and suddenly the list of requirements on the bottom left hand side of the screen was gone. Now the site doesn't react at all to me attempting to submit my code. Here's a screenshot that shows the missing requirements list: http://imgur.com/sUv51aH 

My code:
```html

<script>
  $(document).ready(function() {
  $("button").addClass(animated);
  $(".btn").addClass(shake);
  $("#target1").addClass(btn-primary);
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@KTDid95 your code is incorrect within the `.addClass()` passed in values, as they are invalid. It being invalid is what is causing the  issues. I would checkout ["Target Elements by Class Using jQuery"](https://www.freecodecamp.com/challenges/target-elements-by-class-using-jquery) for a review. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by sludge256** [comment]
The tests now showing up seems to be a FireFox issue from what I remember. Pressing the "Run tests" button or `ctrl+enter` sometimes fixes it.

**Comment by marco2323** [comment]
I'm stucked the same way, but on chrome for android.
My code is right, but  I can't submit too, and also the list of requirements is gone too.
:(

**Comment by atjonathan** [comment]
@marco2323, try the [Help](https://gitter.im/FreeCodeCamp/Help) chat room :smile:

**Comment by marco2323** [comment]
@atjonathan thank you! :)
