### ISSUE TITLE
Symmetric difference args passing issue

### ISSUE THREAD

**Issue by dreamife** [FreeCodeCamp/FreeCodeCamp#8883]
Challenge [Symmetric Difference](https://freecodecamp.cn/challenges/symmetric-difference#?solution=function%20sym(args)%20%7B%0A%20%20var%20res%3D%5B%5D%3B%0A%20%20console.log(args)%3B%0A%20%20%2F*%0A%20%20args.reduce(function(p%2Cc%2Ci%2Ca)%20%7B%0A%20%20%20%20console.log(p)%3B%0A%20%20%20%20p.forEach(function(c%2Ci%2Ca)%20%7B%0A%20%20%20%20%20%20if(this.indexOf(c)%3D%3D-1)%20%7B%0A%20%20%20%20%20%20%20%20res.push(c)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2Cc)%3B%0A%20%20%20%20c.forEach(function(c%2Ci%2Ca)%20%7B%0A%20%20%20%20%20%20if(this.indexOf(c)%3D%3D-1)%20%7B%0A%20%20%20%20%20%20%20%20res.push(c)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2Cp)%3B%0A%20%20%20%20return%20res%3B%20%20%20%20%0A%20%20%7D)%3B*%2F%0A%20%20return%20res%3B%0A%7D%0A%0Asym(%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I use console.log to output the passed args, but the result is just the first element of the input array, which is also a array but in one dimession.
![capture](https://cloud.githubusercontent.com/assets/11721688/15697429/a0bf92a2-27ec-11e6-9b68-7cff856c81ca.PNG)

My code:
```javascript
function sym(args) {
  var res=[];
  console.log(args);  
  return res;
}

sym([1, 2, 3], [5, 2, 1, 4]);

```

**Comment by erictleung** [comment]
@dreamife the site is working correctly. The `args` is truly the "first" argument to the function, as your `console.log` is showing. I would look into the [Arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) for help. Happy coding!

**Comment by dreamife** [comment]
I missed a lesson on argaments obeject , and didn't look at the the code careful enough. My bad
