### ISSUE TITLE
sort13

### ISSUE THREAD

**Issue by AMD-Roy** [FreeCodeCamp/FreeCodeCamp#8889]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20var%20xx%3D''%3B%0A%20%20for(i%3D0%3Bi%3Cstr.length%3Bi%2B%2B)%7B%0A%20%20%20%20var%20vv%3Dstr.charCodeAt(i)%3B%0A%20%20%20%20if(vv%3E%3D65%20%26%26%20vv%3C78)%7B%0A%20%20%20%20%20%20xx%3Dxx%2BString.fromCharCode(vv%2B13)%3B%0A%20%20%20%20%7Delse%20if(vv%3E%3D78%20%26%26%20vv%3C91)%7B%0A%20%20%20%20%20%20xx%3Dxx%2BString.fromCharCode(vv-13)%3B%0A%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20xx%3Dxx%2Bstr%5Bi%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20return%20xx%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  var xx='';
  for(i=0;i<str.length;i++){
    var vv=str.charCodeAt(i);
    if(vv>=65 && vv<78){
      xx=xx+String.fromCharCode(vv+13);
    }else if(vv>=78 && vv<91){
      xx=xx+String.fromCharCode(vv-13);
    }else{
      xx=xx+str[i];
    }
    
  }
  return xx;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

**Comment by erictleung** [comment]
@AMD-Roy is there any issue with this challenge? Your code works and passes the tests.

**Comment by AMD-Roy** [comment]
I am sorry, it's ok. thanks.

**Comment by AMD-Roy** [comment]
do you have written more simple?

**Comment by erictleung** [comment]
@AMD-Roy you can checkout the Wiki for it here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Caesars-Cipher

Happy coding!
