### ISSUE TITLE
Same error regardless of input

### ISSUE THREAD

**Issue by davisec52** [FreeCodeCamp/freecodecamp#889]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

No matter what the input I give for the function, the bonfire says, "Expected [3, 4, 5] to deeply equal [3, 4, 5]."  Thus, if my input is "sym([7, 8, 9], [4, 6, 7], [1, 2, 3])", the bonfire fails and says, "Expected [3, 4, 5] to deeply equal [3, 4, 5]."  My code appears to work in repl.it. I've provided my solution below:

```
function sym(args){
    var arr = [];
    for(var i in arguments){
        var units = arguments[i];
        for(var j = 0; j < units.length; j++){
            arr.push(units[j]);
        }
    }
    return counting(arr);
}

function counting(arr){
    var count = {};
    var result = [];
    var i;
    var j;
    for(i = 0; i < arr.length; ++i){
        if(!count[arr[i]])
        count[arr[i]] = 0;
        ++count[arr[i]];
    }
    for(j in count){
        if(count[j] === 1){
            result.push(+j);
        }
    }
     return result;
}
sym([5, 2, 1, 4], [4, 6, 3, 9], [1, 3, 4, 8]);

```

**Comment by BerkeleyTrue** [comment]
fix is up on staging.
