### ISSUE TITLE
"10 == val" should be evaluated regardless of the order of values

### ISSUE THREAD

**Issue by eprempeh** [FreeCodeCamp/FreeCodeCamp#8895]
Challenge [Comparison with the Equality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-equality-operator#?solution=%0A%2F%2F%20Setup%0Afunction%20testEqual(val)%20%7B%0A%20%20if%20(10%20%3D%3D%20val)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestEqual(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function testEqual(val) {
  if (12 == val) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testEqual(12);

```

**Comment by raisedadead** [comment]
Agreed this is same as #8309.
