### ISSUE TITLE
Firefox Web Console and Bonfire Freeze

### ISSUE THREAD

**Issue by crosscris** [FreeCodeCamp/freecodecamp#89]
Action Performed:
1: Logged onto Bonfire through FCC on Firefox.
2. Worked through problem for 5-10mins, then refreshed page.
3. Worked for 5-10 mins and then added code before shutdown. Code before shutdown include a change in the first variable, 7.
4. After removing 7 from the first array to revert to default arrays, web console and bonfire cease to work.
Expected Result:
[] and both Bonfire and Console refresh.
Actual Result:
No Bonfire and Console refresh. Output area with return array does not change.

Further detail:
Firefox 35.0.1, Windows 7 32 bit

https://drive.google.com/file/d/0B-94cRSEUQu_YXpPMjY0Rl9vMTg/view?usp=sharing

**Comment by QuincyLarson** [comment]
@terakilobyte does this have anything to do with Firefox not killing Bonfire's web workers?

**Comment by terakilobyte** [comment]
Yeah I'm pretty sure it does. As discussed the way to resolve this would be
putting bonfire evaluation on the server, which we may do under react

**Comment by terakilobyte** [comment]
We've discussed this and have decided that we'll just make it a fact that bonfire only works in Chrome.
