### ISSUE TITLE
Doesn't register this challenge as completed

### ISSUE THREAD

**Issue by Kushal-C** [FreeCodeCamp/freecodecamp#890]
![untitled](https://cloud.githubusercontent.com/assets/7200254/8099592/08b5f556-0fb4-11e5-9eed-373e51fd333a.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. The Challenge doesn't register as completed despite having followed all of the steps correctly.

**Comment by sourabhkumar0308** [comment]
hey how did you fixed this issue???

**Comment by Kushal-C** [comment]
It has to be placed exactly where it tells you within the program I missed it the first time I read the problem, hence why you see cat photos next to the picture of the cat on the top as well as the black text on the bottom.

**Comment by sourabhkumar0308** [comment]
I figured it out yesterday. Anyways thanks :)
