### ISSUE TITLE
Instructions & run tests results do not match - Challenge [Use Hex Code for Specific Colors]

### ISSUE THREAD

**Issue by jaytsecan** [FreeCodeCamp/FreeCodeCamp#8904]
Challenge [Use Hex Code for Specific Colors](https://www.freecodecamp.com/challenges/use-hex-code-for-specific-colors#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%23000000%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows; Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

- The instructions say to change the "background-color", while the test only passes if the "color" is changed

**Comment by erictleung** [comment]
@jaytsecan are you talking about this?

> Use the `hex code` for the color black instead of the word `black`. For example body `{ color: #000000; }`

If so, then it was just an example of a hex code being used in a CSS property, which wasn't intended to solve the challenge.

**Comment by erictleung** [comment]
@jaytsecan closing as stale. I think I answered your issue with my comment above. If you get stuck with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
