### ISSUE TITLE
Incorrect Tests

### ISSUE THREAD

**Issue by eliaslfox** [FreeCodeCamp/FreeCodeCamp#8908]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string)

My code:
```javascript
function truncateString(str, num) {
  if (num <= 3) num+=3;
  return str.split('').map((v, i) => {
    if (i >= num-3) return '';
    return v;
  }).join('') + '...';
}
```

Two of the tests, numbers 3 and 4 don't expect to have the "..." added to the end of the string, although they are required by the instructions.

**Comment by raisedadead** [comment]
Your code is giving the below output.

![image](https://cloud.githubusercontent.com/assets/1884376/15741330/c39dfd8c-28d6-11e6-967a-2af78a096fd6.png)

Instructions:

> Truncate a string (first argument) **if it is longer than the given maximum string length** (second argument). 

I don't see a conflict. IMHO your code is not correct, unless you meant something else.

**Comment by eliaslfox** [comment]
Look at the failing tests, note now they are missing the three dots at the end which are included in the passing tests. Those dots are also required in the instructions.

**Comment by eliaslfox** [comment]
Thank you for helping me, I feel really stupid now

**Comment by raisedadead** [comment]
@eliaslfox no issues, glad to be able to sort out the confusion.

**Comment by avotg** [comment]
function truncateString(str, num) {

  if (str.length > num && num > 3){
    return str.slice (0, num-3) + "...";
  } else if (num < 3){
    return str.slice (0, num) + "...";
  }
  
  
  return str;
}

truncateString("A-", 1);
