### ISSUE TITLE
Browser and Text zoom should be at 100%, but i can't pass

### ISSUE THREAD

**Issue by FabricioLeiteQueiroz** [FreeCodeCamp/FreeCodeCamp#8909]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red; font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by allanarmstrong** [comment]
You're not supposed to add `font-size: 16px` to the `.red-text` class. You need to make a new CSS selector that just selects p elements.You can learn more about them [here](http://www.w3schools.com/cssref/sel_element.asp).

**Comment by raisedadead** [comment]
@allanarmstrong thanks.

@FabricioLeiteQueiroz Thanks for reporting this. Unfortunately your code is not correct.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!

**Comment by FabricioLeiteQueiroz** [comment]
I see my error, I read today and see.


Thanks, for answer!



Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Mrugesh Mohapatra <notifications@github.com>
Enviado: quinta-feira, 2 de junho de 2016 08:17:24
Para: FreeCodeCamp/FreeCodeCamp
Cc: Fabricio Leite Queiroz; Mention
Assunto: Re: [FreeCodeCamp/FreeCodeCamp] Browser and Text zoom should be at 100%, but i can't pass (#8909)


Closed #8909<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8909>.

-

**Comment by Shraddha99** [comment]
getting same error .

here is the code. and the browser and text zoom are at 100 %.


<style>
  .red-text {
    color: red;
  p
    {
      font-size:16px;
    }
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Shraddha99** [comment]
the only error is this : 
Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%.

**Comment by allanarmstrong** [comment]
@Shraddha99 You have an error in the position of your closing curly braces. the `p` selector should not be inside the `.red-text` selector.

**Comment by CostGranda** [comment]
@Shraddha99 you have this:
````css
.red-text { color: red; p { font-size:16px; } }
````
and should be this:
```css
.red-text { color: red; } p { font-size:16px; } 
```

**Comment by shamstabrez16** [comment]
**# SAME ERROR**
PLEASE HELP
<style>
  .red-text {
    color: red;
  }
  .p {
    font-size:16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p >Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="p"> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Hexovale20** [comment]
@shamstabrez 

It should look like this:.red-text { color: red; } p { font-size:16px; }

You need to remove the (.) before p

**Comment by kbeni** [comment]
same error
<style>
  .red-text {color: red;}
  p {font-size=16px;}
</style> please help

**Comment by jaineshsingh** [comment]
<style>
  .red-text {
    color: red;
  }
  p
  {
    font-size=16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>       still error coming.

**Comment by shorlly4u** [comment]
I am having the same problem

**Comment by williamskm4** [comment]
How do you give the Browser and text zoom 100%

**Comment by raisedadead** [comment]
> Please consult the Help Chat Room for any assistance to Coding.

**Comment by phatsnikky** [comment]
I am having the same problem on this but what I did was I just created  a new CSS selector that just selects p elements, so it goes like this:

<style>
 .red-text {
    color: red;
}
p{
 font-size: 16px;
}
</style>

hope this will help.

**Comment by StevenRB** [comment]
This is neat.

**Comment by heart2hack** [comment]
whats the solution for the given question....??

**Comment by kdsagar22** [comment]
phatsnikky u helped me alot

**Comment by delsonscoelho** [comment]
It's important check if the code is attending what exactly is demanded. See each one of the three last requirements on this task:
----
* The _**first p**_ element should have the class red-text.
* Do _**not add a class attribute to the second p element**_.
* _**Between the style tags**_, give the p elements font-size of 16px. Browser and Text zoom should be at 100%.
----
If you will do this in a job, remember to respond demands of your customer,  inside or outside of you company. So pay attention to each individual issue asked. 
My code:
![my first solution](https://user-images.githubusercontent.com/28747546/27739839-5fc0c8c2-5d86-11e7-9e42-e0f131707e11.jpg)

**Comment by kartik-1799** [comment]
can @delsonscoelho why there is requirement of new css directory
while my code is
p,red-text{
 color:red; font-size: 16px; zoom:100%;
 }
and thanks for your code
