### ISSUE TITLE
# 32 Bonfire: Smallest Common Multiple

### ISSUE THREAD

**Issue by tourn171** [FreeCodeCamp/freecodecamp#891]
Challenge http://www.freecodecamp.com/challenges/bonfire-smallest-common-multiple has an issue. Please describe how to reproduce it, and include links to screen shots if possible.  
  
Your assert on the # 32 Bonfire: Smallest Common Multiple is in error. It is expecting the least common multiple of 1 and 5 to be 60. The least common multiple of one and any number is that number. Also if that wasn't the case the next common multiple 1 and 5 have is 10. So I am really not sure how you got 60 or for that matter how 360360 is the least common multiple of 1 and 13. 
  

![fcc-bonfire-lcm](https://cloud.githubusercontent.com/assets/7043044/8099987/33190c86-0fcb-11e5-8047-1b50e86b7d93.png)

**Comment by anknits** [comment]
Hello tourn171. I think you misunderstood the problem definition. It asks the least common multiples(lcm) of all numbers int the range of the two numbers provided in the array, including the provided numbers in the range. Also the numbers in the array may not be in numerical order.
Thus [1,5] is the same as [5,1]. The range now is 1,2,3,4,5 and not only 1,5. This means you need to find the lcm of the first 5 natural numbers.
Similarly, [13,1] indicates the range 1 through 13.
Hope this helps. Please see https://github.com/FreeCodeCamp/freecodecamp/issues/1282 for more information.
