### ISSUE TITLE
Actual Order of returned newArr different from expected for one of the results. Does that matter?

### ISSUE THREAD

**Issue by interglobalmedia** [FreeCodeCamp/FreeCodeCamp#8913]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function diffArray(arr1, arr2) {
  var newArr = [];
  // Same, same; but different.
  for(var i = 0; i < arr1.length; i++) {
    if(arr2.indexOf(arr1[i]) === -1) {
      newArr.push(arr1[i]);
    }
  }
  for(i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) === -1) {
          newArr.push(arr2[i]);
    }

  }
  return newArr;
}

diffArray([1, 2, 3, 5], [1, 2, 3, 4, 5]);

```

All of my results are expected === actual, except for  no 3:

["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"] should return ["diorite", "pink wool"].

My actual was ["pink wool", "diorite"]. Does that matter? OR, was expected meant to be === to my actual, and what was typed there an oversight/mistake? Please advise. Thanks!

**Comment by wangk1** [comment]
I tried out your code on both chrome and firefox. It works and passes all the tests in both cases. Honestly, from inspection, it looks like it does exactly what is asked, so order here should not matter. In fact, the order of the answer may be different depending on the data structure you used.

**Comment by interglobalmedia** [comment]
Thanks so much Kevin! That totally answers my question and what I thought MIGHT be the case.

**Comment by erictleung** [comment]
@interglobalmedia no, the order doesn't matter and your code passes for me. Happy coding!

**Comment by interglobalmedia** [comment]
Thanks Eric!
