### ISSUE TITLE
Nothing will pass. Not even the solutions provided by FreeCodeCamp

### ISSUE THREAD

**Issue by jjoyce24** [FreeCodeCamp/FreeCodeCamp#8915]
Challenge [Convert HTML Entities](https://www.freecodecamp.com/challenges/convert-html-entities#?solution=%0Afunction%20convertHTML(str)%20%7B%0A%20%20%2F%2F%20Split%20by%20character%20to%20avoid%20problems.%0A%0A%20%20var%20temp%20%3D%20str.split('')%3B%0A%0A%20%20%2F%2F%20Since%20we%20are%20only%20checking%20for%20a%20few%20HTML%20elements%20I%20used%20a%20switch%0A%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20temp.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20switch%20(temp%5Bi%5D)%20%7B%0A%20%20%20%20%20%20case%20'%3C'%3A%0A%20%20%20%20%20%20%20%20temp%5Bi%5D%20%3D%20'%3C'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%20'%26'%3A%0A%20%20%20%20%20%20%20%20temp%5Bi%5D%20%3D%20'%26'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%20'%3E'%3A%0A%20%20%20%20%20%20%20%20temp%5Bi%5D%20%3D%20'%3E'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%20'%22'%3A%0A%20%20%20%20%20%20%20%20temp%5Bi%5D%20%3D%20'%22'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%20%22'%22%3A%0A%20%20%20%20%20%20%20%20temp%5Bi%5D%20%3D%20%22'%22%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20temp%20%3D%20temp.join('')%3B%0A%20%20return%20temp%3B%0A%7D%0A%0AconvertHTML(%22Dolce%20%26%20Gabbana%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) brave/0.10.0 Chrome/50.0.2661.102 Brave/0.37.8 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertHTML(str) {
  // Split by character to avoid problems.

  var temp = str.split('');

  // Since we are only checking for a few HTML elements I used a switch

  for (var i = 0; i < temp.length; i++) {
    switch (temp[i]) {
      case '<':
        temp[i] = '<';
        break;
      case '&':
        temp[i] = '&';
        break;
      case '>':
        temp[i] = '>';
        break;
      case '"':
        temp[i] = '"';
        break;
      case "'":
        temp[i] = "'";
        break;
    }
  }

  temp = temp.join('');
  return temp;
}

convertHTML("Dolce & Gabbana");

```

**Comment by raisedadead** [comment]
Hi, unfortunately your code is not correct.

for example ` temp[i] = '&'; <-- this is not what the tests expect`

Please go through the instructions and test cases once again.
Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any further assistance to Coding.

Happy Coding!

**Comment by sludge256** [comment]
@jjoyce24 You should file an issue on the [wiki repo](https://github.com/FreeCodeCamp/wiki/issues).
