### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by ARufai** [FreeCodeCamp/FreeCodeCamp#8916]
I am unable to work with your editor quite well, am using android tablet when ever I tried to make some edit then its misbehaving

**Comment by Bouncey** [comment]
Can you please explain further? How is it misbehaving?

**Comment by sludge256** [comment]
Does this issue cover what you're describing?
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847

**Comment by ARufai** [comment]
Yes

**Comment by ARufai** [comment]
Am using tablet with android v4.2.1 and Firefox browser v40.0

**Comment by sludge256** [comment]
Are you also exeriencing https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7259 ?

**Comment by ARufai** [comment]
Yes
