### ISSUE TITLE
Add Vimeo markers that allow you to skip to certain point in challenge video

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#892]

**Comment by QuincyLarson** [comment]
How to dynamically change iFrame: http://stackoverflow.com/questions/1554396/how-do-i-dynamically-change-the-content-in-an-iframe-using-jquery
You can add 
```
#t=0m0s
```
to a Vimeo URL to skip to a specific point

**Comment by johnmellis** [comment]
Quincy, I wouldn't mind taking this one on today - what videos?

**Comment by QuincyLarson** [comment]
I'm closing this because we're removing all videos from FCC's challenges (except for Hikes)
