### ISSUE TITLE
CAN I ALSO USE SCSS INSTEAD OF SASS?

### ISSUE THREAD

**Issue by jacobbogers** [FreeCodeCamp/FreeCodeCamp#8920]
Challenge [Build a Camper Leaderboard](https://www.freecodecamp.com/challenges/build-a-camper-leaderboard) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi The user stories specify I have to use SaSS, but is SCSS also allowed. I Want to explicitly ask!

**Comment by BerkeleyTrue** [comment]
Yes

Happy Coding!
