### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jgarcia965** [FreeCodeCamp/FreeCodeCamp#8921]
#### Challenge Name

https://www.freecodecamp.com/challenges/nesting-for-loops#?solution=%0Afunction%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20for(var%20i%3D0%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%0A%20%20%20%20%20%20%7B%0A%20%20%20%20for(var%20j%3D0%3B%20j%20%3C%20arr%5Bi%5D.length%3Bi%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20product%20*%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0A%0A

#### Issue Description

Won't recognize length. The length method is not being recognized

#### Browser Information

Chrome
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@jgarcia965 your code has a bug and is causing the error for the length method to "not being recognized." I would double check your `for` loops. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
