### ISSUE TITLE
Authorization Required error on email update.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#8923]
![image](https://cloud.githubusercontent.com/assets/1884376/15769566/e93d75ba-2979-11e6-9744-4f4a61e09527.png)

The above is a know issue that has crept in with our recent upgrade for email verification process.
Please ignore this error and we are coming up with a fix ASAP.
While that happens you will not be able to update your email.
Rest assured we are doing our best to address this.
Sincere apologies for the inconvenience.

**Comment by BerkeleyTrue** [comment]
For those effected, it may be possible to switch browsers to get around it.

**Comment by raisedadead** [comment]
Update: This will be resolved once we have the Free Code Camp website on react, very soon.

**Comment by MrSimy0** [comment]
any update?

**Comment by BerkeleyTrue** [comment]
This is fixed in current staging

**Comment by Rule1001** [comment]
Issue still exists. Changing browser to IE9 worked

**Comment by usamaiv** [comment]
Issue still exists on Chrome 56.

**Comment by raisedadead** [comment]
@Rule1001 @mUsamaDev We have fixed this, but haven't pushed the fix to the main website yet. Please bear with us while we do that.

Alternatively, you could try any browser other than Chrome.
