### ISSUE TITLE
Need to handle flash messages more elegantly

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#8926]
![image](https://cloud.githubusercontent.com/assets/1884376/15770315/779ffa2a-2980-11e6-957d-ab6ad809656a.png)

**Comment by BerkeleyTrue** [comment]
This may be a mute point since the new react site uses toast messages

**Comment by raisedadead** [comment]
Great, to be closed when react infrastructure in place.
