### ISSUE TITLE
Tell certificate earners how to add their names

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8933]
Campers will often claim a certificate, then not understand why their certificate doesn't have their name on it. This is because we pull their name from GitHub, and if they haven't added a name to their GitHub account, we don't have their name, either.

Agile user story:
- As a user, if I attempt to claim a certificate and my account doesn't have a name, I should see instructions for how to add it.
- I should not be able to claim a certificate while my name is blank

Copy for the flash message: 

"We need your name so we can put it on your certificate. [Add your name to your GitHub account](https://github.com/settings/profile), then go to your [settings page](https://www.freecodecamp.com/settings) and click the "update my portfolio from GitHub" button. Then we can issue your certificate."

**Comment by dakshshah96** [comment]
Can I take care of this?

**Comment by QuincyLarson** [comment]
@dakshshah96 I didn't respond earlier, but yes - you can take care of this.

**Comment by dakshshah96** [comment]
I tried hard figuring out how to do this, but couldn't. Would be great if someone else can take up this issue. Sorry about that! 😅

**Comment by Trion129** [comment]
I will try this :+1:

**Comment by QuincyLarson** [comment]
@Trion129 any updates?

**Comment by Trion129** [comment]
I started to work on backend projects so forgot to give updates here :sweat_smile: I had added this code to check if, on certificate view, the name is empty it is replaced by a link to github settings
```
var nameDiv = document.getElementById('name');
if(nameDiv.innerHTML == ""){
  gitLink = document.createElement("a");
  gitLink.innerHTML = "No Name provided on Github";
  gitLink.href = "https://github.com/settings/profile";
  nameDiv.appendChild(gitLink);
}
```
I also wanted to add a name checking page during the certificate claiming procedure but problem is I couldn't find where the api code is present so I can make a new api for checking names. I need help on that
