### ISSUE TITLE
Rewrite of "Where do I belong" instructions

### ISSUE THREAD

**Issue by wanmi59** [FreeCodeCamp/FreeCodeCamp#8934]
#### Where do I belong

https://www.freecodecamp.com/challenges/where-do-i-belong

#### Issue Description
I tried passing all the test cases and the output are supposed to be accepted but...

#### Browser Information

* Browser Name, Version: Google Chrome, 51.0.2704.79 m (64-bit)
* Operating System: Windows 7
* Mobile, Desktop, or Tablet:  Desktop

#### My Code
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arr.push(num);
  arr.sort(function(a, b){
    return a - b;
  });
  for(var i in arr){
    if(arr[i] == num){
      return i;
    }
  }
}

getIndexToIns([2, 20, 10], 19);

![untitled](https://cloud.githubusercontent.com/assets/6716035/15776012/da99b900-29a2-11e6-9c74-ff896a794d31.png)

**Comment by erictleung** [comment]
@wanmi59 the type of the return statement should be an integer, not a string, so that is why the tests are failing. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

However, I do propose rewriting the instructions to be more clear:

> Return the lowest index at which a value (second argument) should be inserted into an array (first argument) once it has been sorted. **The returned value should be a number.**

cc/ @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
@erictleung, sounds good to me!

**Comment by erictleung** [comment]
Those wanting to fix this, [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L648) needs to be changed to:

> Return the lowest index at which a value (second argument) should be inserted into an array (first argument) once it has been sorted. The returned value should be a number.

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by JonW27** [comment]
Can I take this?

**Comment by erictleung** [comment]
@JonW27 go for it!

**Comment by JonW27** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8944
