### ISSUE TITLE
All conditions are full filled except the first one??

### ISSUE THREAD

**Issue by sinharajatit** [FreeCodeCamp/FreeCodeCamp#8936]
Challenge [Mutations](https://www.freecodecamp.com/challenges/mutations#?solution=%0A%20function%20mutation(arr)%20%7B%0A%20%20arr%5B0%5D%20%3D%20arr%5B0%5D.toLowerCase()%3B%0A%20%20arr%5B1%5D%20%3D%20arr%5B1%5D.toLowerCase()%3B%0A%20%20%0A%20%20var%20ar%20%3D%20arr%5B1%5D.split(%22%22)%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3Carr%5B1%5D.length%3Bi%2B%2B)%7B%0A%20%20if(arr%5B0%5D.indexOf(ar%5Bi%5D)%20%3E%3D%200%20)%7B%0A%20%20%20%20%0A%20%20%20%20return%20true%3B%0A%20%20%20%7D%0A%20%20%0A%20%20%20%20return%20false%3B%0A%20%20%0A%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B%20%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

 function mutation(arr) {
  arr[0] = arr[0].toLowerCase();
  arr[1] = arr[1].toLowerCase();
  
  var ar = arr[1].split("");
  for(var i = 0; i <arr[1].length;i++){
  if(arr[0].indexOf(ar[i]) >= 0 ){
    
    return true;
   }
  
    return false;
  
  
  }
  
  
}

mutation(["hello", "hey"]); 


```

**Comment by erictleung** [comment]
@sinharajatit your code is not sufficient to complete the challenge. I would walk through your `for` loop logic carefully and make sure it actually checks all the letters in your string. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by sinharajatit** [comment]
@erictleung Help room was not helpful for the code i have written. They have given me some other logic to solve this challenge which was quite helpful. But i don't know what is the problem with my code. Its is working perfectly for similar kinds of conditions.

**Comment by benjamn77** [comment]
sinharajatit: I wrote the same code and have the same issue. Did you ever figure out why this code is insufficient? An explanation of logic and the for loop issue would help me clear this up! Thanks!
