### ISSUE TITLE
Roman Numeral Converter: Doesn't correctly test

### ISSUE THREAD

**Issue by chelseypaulsen** [FreeCodeCamp/FreeCodeCamp#8940]
#### Challenge Name

Roman Numeral Converter

#### Issue Description

The test does not accurately reflect correct answers.I used while loops (maybe a far to primitive idea) to complete the challenge, I get the write answer as a string in the console, but no green check-marks appear. 

Here is [the link to my issue](https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=var%20arr%20%3D%20%5B%5D%3B%0Afunction%20convertToRoman(num)%20%7B%0A%20%20%0A%20%20while%20(num%3E%3D1000)%7B%0A%20%20%20%20num%20%3D%20num-1000%3B%0A%20%20%20%20arr.push('M')%3B%0A%20%20%7D%0A%20%20%0A%20%20while%20(num%3E%3D900)%7B%0A%20%20%20%20num%20%3D%20num-900%3B%0A%20%20%20%20arr.push('CM')%3B%0A%20%20%7D%0A%20%20%0A%20%20while%20(num%3E%3D500)%7B%0A%20%20%20%20num%20%3D%20num-500%3B%0A%20%20%20%20arr.push('D')%3B%0A%20%20%7D%0A%20%20%0A%20%20%20%20while%20(num%3E%3D400)%7B%0A%20%20%20%20num%20%3D%20num-400%3B%0A%20%20%20%20arr.push('CD')%3B%0A%20%20%7D%0A%20%20%0A%20%20while%20(num%3E%3D100)%7B%0A%20%20%20%20num%20%3D%20num-100%3B%0A%20%20%20%20arr.push('C')%3B%0A%20%20%7D%0A%20%20%0A%20%20%20%20while%20(num%3E%3D90)%7B%0A%20%20%20%20num%20%3D%20num-90%3B%0A%20%20%20%20arr.push('XC')%3B%0A%20%20%7D%0A%20%20%0A%20%20while%20(num%3E%3D50)%7B%0A%20%20%20%20num%20%3D%20num-50%3B%0A%20%20%20%20arr.push('L')%3B%0A%20%20%7D%0A%20%20%0A%20%20%20%20while%20(num%3E%3D40)%7B%0A%20%20%20%20num%20%3D%20num-40%3B%0A%20%20%20%20arr.push('XL')%3B%0A%20%20%7D%0A%20%20%0A%20%20%20%20while%20(num%3E%3D10)%7B%0A%20%20%20%20num%20%3D%20num-10%3B%0A%20%20%20%20arr.push('X')%3B%0A%20%20%7D%0A%20%20%0A%20%20%20%20while%20(num%3E%3D9)%7B%0A%20%20%20%20num%20%3D%20num-9%3B%0A%20%20%20%20arr.push('IX')%3B%0A%20%20%7D%0A%20%20%0A%20%20while%20(num%3E%3D5)%7B%0A%20%20%20%20num%20%3D%20num-5%3B%0A%20%20%20%20arr.push('V')%3B%0A%20%20%7D%0A%20%20%0A%20%20while%20(num%3E%3D4)%7B%0A%20%20%20%20num%20%3D%20num-4%3B%0A%20%20%20%20arr.push('IV')%3B%0A%20%20%7D%0A%20%20%0A%20%20while%20(num%3E%3D1)%7B%0A%20%20%20%20num%20%3D%20num-1%3B%0A%20%20%20%20arr.push('I')%3B%0A%20%20%7D%0A%20%20%0A%20%20num%20%3D%20arr.join('')%3B%0A%20return%20num%3B%0A%7D%0A%0AconvertToRoman(36)%3B%0A)

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
Here is the code I used:
var arr = [];
function convertToRoman(num) {
  
  while (num>=1000){
    num = num-1000;
    arr.push('M');
  }
  
  while (num>=900){
    num = num-900;
    arr.push('CM');
  }
  
  while (num>=500){
    num = num-500;
    arr.push('D');
  }
  
    while (num>=400){
    num = num-400;
    arr.push('CD');
  }
  
  while (num>=100){
    num = num-100;
    arr.push('C');
  }
  
    while (num>=90){
    num = num-90;
    arr.push('XC');
  }
  
  while (num>=50){
    num = num-50;
    arr.push('L');
  }
  
    while (num>=40){
    num = num-40;
    arr.push('XL');
  }
  
    while (num>=10){
    num = num-10;
    arr.push('X');
  }
  
    while (num>=9){
    num = num-9;
    arr.push('IX');
  }
  
  while (num>=5){
    num = num-5;
    arr.push('V');
  }
  
  while (num>=4){
    num = num-4;
    arr.push('IV');
  }
  
  while (num>=1){
    num = num-1;
    arr.push('I');
  }
  
  num = arr.join('');
 return num;
}

convertToRoman(36);

```

#### Screenshot

notice that I correctly convert 44 to roman numerals.
![image](https://cloud.githubusercontent.com/assets/15622450/15789947/cac3051e-299c-11e6-92f2-582b744c8739.png)

**Comment by erictleung** [comment]
@chelseypaulsen your `var arr = [];` is a global variable. You need to put it within your function. Our tests run just your function. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
