### ISSUE TITLE
There seems to be a lesson missing

### ISSUE THREAD

**Issue by alaaaaaaaaan** [FreeCodeCamp/FreeCodeCamp#8942]
#### Challenge Name

https://www.freecodecamp.com/challenges/add-a-submit-button-to-a-form

#### Issue Description

These are the instructions provided by the challenge:
" Let's add a submit button to your form. Clicking this button will send the data from your form to the URL you specified with your form's action attribute."

However, there is never a lesson that teaches you how to create a form or give it the action attribute. I understood what it meant because i have some minor knowledge of this stuff but it may be beneficial to add a lesson right before this one on creating forms or the form element. 

Keep up the good work y'all

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

The piece of code below is already in the editor window when you start the lesson and it is not one that you create in the previous lesson. 
```js
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL">
</form>
```

**Comment by tianz** [comment]
I think you create a form and give it a action in the previous challenge https://www.freecodecamp.com/challenges/create-a-form-element

**Comment by erictleung** [comment]
@alaaaaaaaaan the code

```
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL">
</form>
```

is the same code that you should have input from the previous challenge "Create a Form Element." This lesson, as @tianz has pointed out, is where you learn to add actions:

> Nest your text field in a `form` element. Add the `action="/submit-cat-photo"` attribute to this form element.

Happy coding!
