### ISSUE TITLE
Add bio to Free Code Camp portfolios

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#8943]
GitHub recently introduced a bio field. We should also pull this from GitHub and store it on each user's object the same way we pull their name and location from GitHub. 

- [x] Update user schema to store bio
- [x] Update GitHub auth logic to request and store bio
- [x] Update code portfolio view to display bio if present

For reference, here's my public info: (https://api.github.com/users/quincylarson). You can see the new attribute is simply "bio":

```
{
  "login": "QuincyLarson",
  "id": 985197,
  "avatar_url": "https://avatars.githubusercontent.com/u/985197?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/QuincyLarson",
  "html_url": "https://github.com/QuincyLarson",
  "followers_url": "https://api.github.com/users/QuincyLarson/followers",
  "following_url": "https://api.github.com/users/QuincyLarson/following{/other_user}",
  "gists_url": "https://api.github.com/users/QuincyLarson/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/QuincyLarson/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/QuincyLarson/subscriptions",
  "organizations_url": "https://api.github.com/users/QuincyLarson/orgs",
  "repos_url": "https://api.github.com/users/QuincyLarson/repos",
  "events_url": "https://api.github.com/users/QuincyLarson/events{/privacy}",
  "received_events_url": "https://api.github.com/users/QuincyLarson/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Quincy Larson",
  "company": "Free Code Camp",
  "blog": "http://www.FreeCodeCamp.com",
  "location": "San Francisco, California, US",
  "email": null,
  "hireable": null,
  "bio": "I'm a teacher at Free Code Camp. I write articles about technology at medium.com/@quincylarson and quora.com/profile/Quincy-Larson",
  "public_repos": 22,
  "public_gists": 38,
  "followers": 932,
  "following": 13,
  "created_at": "2011-08-17T04:08:08Z",
  "updated_at": "2016-06-03T21:48:07Z"
}
```

**Comment by jacobbearden** [comment]
Mind if I take care of this one?

**Comment by atjonathan** [comment]
@jacobbearden, definitely!

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by VishalRam** [comment]
Can I work on this one?

**Comment by atjonathan** [comment]
@VishalRam, still looking to help? If you are, go right ahead and let us know :smile:

**Comment by VishalRam** [comment]
@atjonathan - Yes. I will work on this and send you a Pull request by weekend. Is that good?

**Comment by atjonathan** [comment]
@VishalRam, please hold back on this one. It might be better to choose a different issue to work on. I'm currently working on a revamp of the profile page, and I have already started integrating this and other new features. Happy Coding and Sorry about that :smiley:
