### ISSUE TITLE
"ANS" button in freeCodeCamp's JavaScript Calculator example not functional

### ISSUE THREAD

**Issue by LeWood16** [FreeCodeCamp/FreeCodeCamp#8945]
#### Build A JavaScript Calculator
https://www.freecodecamp.com/challenges/build-a-javascript-calculator

#### Issue Description

I'm not sure whether someone had already pointed this issue out (I couldn't find someone else posting about it anywhere), but the button in the example code that stores the last answer to be used later (the "ANS" button) doesn't do anything; For example when you type "2+2=", 4 appears, then when you type "Ans+2=" you simply get 2, meaning it starts from 0 again, and nothing seems to be stored for later use.

I'm not sure if this would be considered a bug or not.  It's not an objective for the challenge either, I just thought it was odd to have a button in the example that doesn't do anything.

Here is my link if it's any help: https://codepen.io/LeFonze/pen/pbzYGo

**Comment by raisedadead** [comment]
@LeWood16 thanks a lot reporting this. Can you help us in fixing this?
If you could, please point what's not correct in the code for the original pen we can quickly fix that.

**Comment by CDEguia** [comment]
Got a fix!!! but haven't contributed before...
here is the code snippet:
` else if(text === "And") {
      calc = $(".textbox").val();
      $(".textbox").val(calc);
      clear=false;`
this can be placed at the end of the 'else if's
my forked pen can be found [here](https://codepen.io/CDEguia/pen/pbJpgY)

**Comment by raisedadead** [comment]
Thanks @CDEguia appreciate the help, this may not be related but its still a rough on the ages.
Clicking the `ANS` followed by `-`, doesn't seem to work.

**Comment by CDEguia** [comment]
My mistake, I didn't save the final version of the code [this](http://codepen.io/CDEguia/full/pbJpgY/) should work.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

@CDEguia Thanks a lot! WOOT.

@LeWood16 please check the original pen, I have updated it with changes suggested by @CDEguia 
Closing as resolved.
