### ISSUE TITLE
Inadequate Unit Tests

### ISSUE THREAD

**Issue by postpoststructuralism** [FreeCodeCamp/FreeCodeCamp#8948]
Challenge [Prefilter JSON](https://www.freecodecamp.com/challenges/prefilter-json#?solution=%0Afccss%0A%20%20%24%28document%29.ready%28function%28%29%20%7B%0A%0A%20%20%20%20%24%28%22%23getMessage%22%29.on%28%22click%22%2C%20function%28%29%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON%28%22%2Fjson%2Fcats.json%22%2C%20function%28json%29%20%7B%0A%0A%20%20%20%20%20%20%20%20var%20html%20%3D%20%22%22%3B%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20json%20%3D%20json.filter%28function%28val%29%7B%0A%20%20%20%20%20%20%20%20%20%20return%20%28val.id%20%3D%3D%3D%201%29%3B%0A%20%20%20%20%20%20%20%20%7D%29%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%20%20%20%20%20%20%20%20json.forEach%28function%28val%29%20%7B%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3Cdiv%20class%20%3D%20'cat'%3E%22%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3Cimg%20src%20%3D%20'%22%20%2B%20val.imageLink%20%2B%20%22'%3E%22%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3C%2Fdiv%3E%22%0A%0A%20%20%20%20%20%20%20%20%7D%29%3B%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24%28%22.message%22%29.html%28html%29%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D%29%3B%0A%20%20%20%20%7D%29%3B%0A%20%20%7D%29%3B%0Afcces%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Issue can be reproduced by simply submitting buggy code that happens to contain the filter function (e.g., note how I am filtering the wrong values, i.e., should be "return (val.id !== 1);").

Although the assumption is probably that people are going to simply copy paste the solution from the question, the tests should be robust enough to catch bugs in code that people have written themselves, e.g., note that I am here filtering the wrong elements, but the code still passes.

My code:

``` html

<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json", function(json) {

        var html = "";

        // Only change code below this line.

        json = json.filter(function(val){
          return (val.id === 1);
        });

        // Only change code above this line.

        json.forEach(function(val) {

          html += "<div class = 'cat'>"

          html += "<img src = '" + val.imageLink + "'>"

          html += "</div>"

        });

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
    </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@postpoststructuralism thanks for the feedback. I want to say this issue is related to #5004. These tests were "left" inadequate because we don't have the infrastructure to test these properly. The least we can do is have regexes look for the code we suggest but doing so, coders will find other ways to pass the challenge, as with #7557.

cc/ @FreeCodeCamp/issue-moderators am I correct in saying we don't have the infrastructure to test these properly yet?
