### ISSUE TITLE
Even if second p element is given a wrong css class name, no error is flagged

### ISSUE THREAD

**Issue by indcoder** [FreeCodeCamp/freecodecamp#895]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
:
The below code was deemed to be correct:
```
<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='text-red'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by LumenTeun** [comment]
Correct me if I'm wrong, but I don't think the p tags require classes.

**Comment by indcoder** [comment]
Yes ....see what the next challenge code starts as. Both the p element have the style class applied to them.

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by LumenTeun** [comment]
That's true, but the test cases doesn't mention any classes, and since the challenge is about styling elements directly, adding tests for a class seems uncalled for in my opinion.

**Comment by BerkeleyTrue** [comment]
@ahstro is correct.

Happy Coding.
