### ISSUE TITLE
All of my previous work missing before "Intermediate Algorithms" if viewed via "MAP" navigation

### ISSUE THREAD

**Issue by geligelu** [FreeCodeCamp/FreeCodeCamp#8950]
#### Challenge Name

All of them

#### Issue Description

I don't know how to reproduce it. I just went back today to check some of my solutions, and all my work is missing!

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: OS X latest
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by geligelu** [comment]
Sorry, panic over. It's not missing. However, if I go back to my solutions via "map" - my work isn't there. I can only view them via my profile and then "view solution". Is this a bug?

**Comment by atjonathan** [comment]
@geligelu, I can view my solutions find from the map. Are you saying the code editor just shows the default challenge code?

cc/ @FreeCodeCamp/issue-moderators

**Comment by geligelu** [comment]
@atjonathan - that's exactly what I'm saying. yes.

Example - went to the "Find the longest word" algorithm page, via Map, from within a later challenge:

<img width="706" alt="find_the_longest_word_in_a_string___free_code_camp" src="https://cloud.githubusercontent.com/assets/6688676/15799001/5ac96d36-2a80-11e6-8d89-f4569173a67a.png">

and then I visited from my profile page:

<img width="708" alt="find_the_longest_word_in_a_string___free_code_camp 2" src="https://cloud.githubusercontent.com/assets/6688676/15799004/6886c27a-2a80-11e6-8a7a-fc2e64cdf1a8.png">

**Comment by atjonathan** [comment]
@geligelu, this problem doesn't appear for me on Google Chrome `Version 50.0.2661.102 m`...
cc/ @FreeCodeCamp/issue-moderators, can anyone reproduce?

**Comment by geligelu** [comment]
Also on Version 50.0.2661.102 (64-bit)

**Comment by sludge256** [comment]
Accessing challenges via the map will load data stored in Local Storage.

**Comment by atjonathan** [comment]
@geligelu, confused cause it works fine for me. As @sludge256 stated, it's possible your local storage was cleared. Try resubmitting a challenge...

**Comment by geligelu** [comment]
OK @sludge256  - with more testing I can see that this is exactly the case. as soon as I visit a challenge from my profile page, leave and come back via map, the data has been restored.

I'm happy to close this now, but here's food for thought:  I won't be the only person to clear their cache/local storage/cookies every so often. What happens if someone else gets into a bit of a panic that half of their stuff has disappeared after all the hard work?

I don't know - a note in the wiki somewhere that says 'When you submit your work, it's stored in our database, but we also cache  a local copy. If you delete your local storage, it might look like it's gone, but don't worry, we've still got all your work!' - or something to that effect.

**Comment by raisedadead** [comment]
Closing. Separate issue raised to track wiki request.

**Comment by BerkeleyTrue** [comment]
The default behavior is changing to only store the current challenge you are working on in localStorage. Once you submit a challenge it will be removed from your local cache and saved on the server.
