### ISSUE TITLE
Update tests for Manipulate Arrays With pop challenge.

### ISSUE THREAD

**Issue by fkingn00bGG** [FreeCodeCamp/FreeCodeCamp#8953]
Challenge [Manipulate Arrays With pop](https://www.freecodecamp.com/challenges/manipulate-arrays-with-pop#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20removedFromOurArray%20%3D%20ourArray.pop()%3B%20%0A%2F%2F%20removedFromOurArray%20now%20equals%203%2C%20and%20ourArray%20now%20equals%20%5B1%2C2%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20removedFromMyArray%3B%0A%0AremovedFromMyArray%20%3D%20%5B%22cat%22%2C%202%5D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray;

removedFromMyArray = ["cat", 2];

```

**Comment by raisedadead** [comment]
Your code passes for me baby! :wink:

Please clarify what is the issue you are facing, exactly.
P.S : Please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)

**Comment by fkingn00bGG** [comment]
That is the problem if you look at the checks `myArray` should only have one array but this still passed all the checks even though I have not removed the array from it.

**Comment by erictleung** [comment]
Right, this challenge needs a test to test the use of `.pop()`

**Comment by raisedadead** [comment]
@fkingn00bGG thanks a lot.

**Comment by Bouncey** [comment]
Another issue with this test is that test one gives a false positive under the conditions of the OP.

**Comment by dilawarx** [comment]
sorry it didn't help 👎

**Comment by OgunniyiOwamamwen** [comment]
THE CODE ANSWER
Manipulate Arrays With pop


// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray = myArray.pop();
