### ISSUE TITLE
Record Collection challenge has incorrect JSON syntax

### ISSUE THREAD

**Issue by aleksgorbenko** [FreeCodeCamp/FreeCodeCamp#8955]
The task says: "You are given a JSON object representing..."

Start of the example code given at the start:

```
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
```

Quote on JSON objects from MDN:

> JSON permits **only property definition using _"property": value syntax_**.  The property name must be double-quoted, and the definition cannot be a shorthand.

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Object_literal_notation_vs_JSON

Hence, the statement that it is a JSON object is wrong - it is JS object as properties are not written as strings. Personally, it made me confused because there is another task:
https://www.freecodecamp.com/challenges/profile-lookup
Where properties are written correctly with quotes. As a result, it made me think that both options are the correct declaration of JSOn objects.

I hope that can be fixed.

Thanks,
Aleks

**Comment by erictleung** [comment]
@aleksgorbenko thanks for the feedback. This is related to #7767.

**Comment by karel1980** [comment]
I would like to work on this

**Comment by karel1980** [comment]
I'm a bit conflicted about the best approach here. We could simply state that it is a "Javascript object" instead of a JSON object (i.e. leave out the term JSON), or change the javascript so that object keys are quoted.
I actually prefer the former, because there is no JSON here. JSON is just a representation format which looks a lot like javascript. Sure, with proper quotes a particular part of the source code could be interpreted as JSON, but in the given context it's still javascript.
WDYT?

**Comment by aleksgorbenko** [comment]
@erictleung - you are right about the other post, missed that one.
@karel1980 - I think the best would be just to put quotes around the properties and then the description matches the code + code will be consistent with the other challenge - https://www.freecodecamp.com/challenges/profile-lookup , therefore causing less confusion.

**Comment by andmckvr13** [comment]
hello, I would like to help with this issue, however I have never submitted to an issue before. Do I need to retrieve the specific file for Record Collection challenge or do I simply fork the repo, add the changes to a new branch and then submit a pull request? I'm a little lost so I apologize if the answer is straight forward and it's just going over my head

**Comment by atjonathan** [comment]
@andmckvr13 

> do I simply fork the repo, add the changes to a new branch and then submit a pull request?

Correct :white_check_mark: 

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by karel1980** [comment]
You should fork the repo, make changes in a branch an submit a pull request.
I have already made the changes locally, I just never got around to testing
them. I'm committing them now so you can work from there if you like.
Here you go:
https://github.com/karel1980/FreeCodeCamp/tree/feature/correct-json-syntax

Here is some more information about the process:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

**Comment by LindsayBrown81** [comment]
+1 @aleksgorbenko, @erictleung, @karel1980, @andmckvr13 @andmckvr13, @aleksgorbenko @atjonathan 
I am relieved that you all have addressed that the Record Collection problem [https://www.freecodecamp.com/challenges/record-collection](url) does not contain valid JSON syntax. I would also like to address that the instructions contain vague wording; i.e., the word "property" is being used to refer to the more specific and more accurate word "key." For example, "Write a function which takes an id, a property (prop), and a value."

The ECMAScript 2015 standard defines a property as the part of an object that associates a key (either a String value or a Symbol value) and a value (source: [http://www.ecma-international.org/ecma-262/6.0/#sec-property](url)). So, a property consists of a key - value pair. (source: [http://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties](url)). The vague word choice in the Record Collection problem's instructions causes confusion for campers who are already familiar with the definition of property; further, instructions should provide a definition for important terminology for that lesson; in this case, the word "property," which is an important aspect of the JSON schema.

I plan on rewriting the instructions and making a pull request this weekend  (June 11-12, 2016).
