### ISSUE TITLE
Freecodecamp site not recognizing remainder operator (%) on Windows 8.1 or iPad Air 2, both chrome browsers

### ISSUE THREAD

**Issue by wjhurley** [FreeCodeCamp/FreeCodeCamp#8956]
Challenge [Finding a Remainder in JavaScript](https://www.freecodecamp.com/challenges/finding-a-remainder-in-javascript#?solution=%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20remainder%3B%0A%0Aremainder%3D11%20%25%203%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_1 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/51.0.2704.64 Mobile/13E238 Safari/601.1.46</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Only change code below this line

var remainder;

remainder=11 % 3;
```

**Comment by BerkeleyTrue** [comment]
Looks like the test is looking for the var declaration and operation on the same line.

**Comment by arun1595** [comment]
@BerkeleyTrue I would like to work on this.

**Comment by atjonathan** [comment]
@arun1595, cool!

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).
