### ISSUE TITLE
Algorithm - Convert HTML Entities wiki page: all solutions will not work as written

### ISSUE THREAD

**Issue by geligelu** [FreeCodeCamp/FreeCodeCamp#8957]
#### Challenge Name

https://www.freecodecamp.com/wiki/en/algorithm-convert-html-entities/

#### Issue Description

In all of the solutions, whether it's a case statement, object, or regex string replace, they do not map to the correct html entities, but they simple repeat the symbol that should be replaced:

e.g.

`str.replace(/&/g,'&')`

 instead of 

`str.replace(/&/g,'&amp;')`

or 

```
htmlEntities={
'&':'&',
...
```

instead of 

```
htmlEntities={
'&':'&amp;',
...
```

#### Browser Information

* Browser Name, Version:  Chrome, Version 50.0.2661.102 (64-bit)
* Operating System: OS X El Capitan
* Mobile, Desktop, or Tablet:  Deskptop

**Comment by erictleung** [comment]
For those wanting to work on this, you'll need to head over to the Wiki repository to make these changes. [This is the file](https://github.com/FreeCodeCamp/wiki/blob/0d16c5badf43d19b08ea1f01d0187fe7bde7bad4/Algorithm-Convert-HTML-Entities.md) you'll need to edit.

When you make your PR over on the Wiki repo, use `Closes FreeCodeCamp/FreeCodeCamp#8957` in your PR message to automatically close this issue from there.

**Comment by gvp-raviteja** [comment]
can i take this up?

**Comment by erictleung** [comment]
@gvp-raviteja go for it!
