### ISSUE TITLE
Recaptcha in codepen prevents me from signup.

### ISSUE THREAD

**Issue by harveythedinosaur** [FreeCodeCamp/FreeCodeCamp#8963]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:2.0) Gecko/20100101 Goanna/20160507 PaleMoon/26.2.2</code>.
Be a not stupid user and have efficient tracking protection in your browser, don't usually use google accounts. Then try to login on a site with recaptcha. Also I cant even solve the puzzles because I always get a new set and it never finishes. Windows 7 x64 with Palemoon 26.2.2
Have fun. This cancer is driving me insane.

**Comment by erictleung** [comment]
@harveythedinosaur sorry, but I'm not understanding your issue. Are you having difficulty signing up for Codepen because of the reCAPTCHA?

**Comment by harveythedinosaur** [comment]
Yeah recaptcha never finishes even if I solve 30 sets for them.

**Comment by erictleung** [comment]
@harveythedinosaur I'm sorry to hear you're having issues with the reCAPTCHA. There's nothing on our end that can help the situation. If you're still having issues with it, I would advise you to have another person help you solve the puzzles. Be sure to fill out the rest of the sign-up form as well. Happy coding!
