### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by aledavila** [FreeCodeCamp/FreeCodeCamp#8964]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20var%20newStr%20%3D%20str.replace(%2F%5B%5Ea-zA-Z%5D%2Fg%2C%20%22%22).toLowerCase()%3B%0A%20%20var%20palindrome%20%3D%20newStr.split('').reverse().join('')%3B%0A%20%0A%20%20return%20newStr%20%3D%3D%3D%20palindrome%20%3F%20true%20%3A%20false%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  var newStr = str.replace(/[^a-zA-Z]/g, "").toLowerCase();
  var palindrome = newStr.split('').reverse().join('');
  return newStr === palindrome ? true : false;
}



palindrome("eye");

```

The test `palindrome("1 eye for of 1 eye.") should return false` is palindrome

**Comment by erictleung** [comment]
@aledavila "1 eye for of 1 eye" is not a palindrome. Reversing the string after removing spaces gives you "eye1forofeye1", which is not the same as the original "1eyeforof1eye". Happy coding!
