### ISSUE TITLE
"Kool-Aid Man" should be hyphenated

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#8967]
#### Issue Description

In the compliment involving the Kool-Aid Man, his name should be hyphenated (https://en.wikipedia.org/wiki/Kool-Aid_Man).

#### To Fix

You'll need to change [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/utils/resources.json#L87) and add a hyphen to make it:

> Kool-Aid Man says oh yeah!

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/15803628/f53d7bca-2a9c-11e6-93a0-53f0e8468d37.png)

#### Wanting to Contribute

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by tjgerot** [comment]
This issue has been fixed in [pull request #8969](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8969).

**Comment by wildaces215** [comment]
Is this issue still open even though 7 out of 10 tasks are complete?

**Comment by crashuniverse** [comment]
LGTM
