### ISSUE TITLE
Sign Up then Sign In Returns False

### ISSUE THREAD

**Issue by johnmellis** [FreeCodeCamp/freecodecamp#897]
Steps to Replicate:
1. Open an incognito window to FreeCodeCamp Website
2. Click Sign Up with Email link
3. Enter email address
4. Click Yellow Sign In button in Top Right Nav
5. Login

You're taken to a failed authentication page, but if you click back and refresh you're authenticated.

**Comment by BerkeleyTrue** [comment]
fixed in beta
