### ISSUE TITLE
I am doing what is required but it is mot letting me pass.

### ISSUE THREAD

**Issue by pragya68** [FreeCodeCamp/FreeCodeCamp#8970]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20if(%20value%20!%3D%3D%20%22%22)%7B%0A%20%20%20%20if(prop!%3D%3D%22tracks%22)%7B%0A%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D%3Dvalue%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if(%20prop%20%3D%3D%3D%22tracks%22)%7B%0A%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D.push(value)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20else%0A%20%20%20%20delete%20collection%5Bid%5D%5Bprop%5D%3B%0A%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  if( value !== ""){
    if(prop!=="tracks"){
      collection[id][prop]=value;
    }
    else if( prop ==="tracks"){
      collection[id][prop].push(value);
    }
  }
  else
    delete collection[id][prop];

  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by rameshsyn** [comment]
@pragya68  It works perfectly for me !!!. You can   clear your  browser caches and cookies  and resubmit .

**Comment by crashuniverse** [comment]
It's okay, sometimes we do get stuck and `console.log` helps a lot to determine what the problem could be. The assignment looks okay, I'll talk about what is going wrong with your code. It is possible that the underlying concept is not explained to you already but with this conversation, you would be able to proceed.

1. Identify what is going wrong with tests. Your solution suggests 2nd test is failing. So instead I changed your code to include the failing test at bottom: 
`updateRecords(5439, "tracks", "Take a Chance on Me");`
2. Now when I run your code it throws a more explanatory error:
`TypeError: Cannot read property 'push' of undefined`
3. And now you should think more about what could be problem with `collection[id][prop].push(value);`

I can add more hints if you need more help on this.

p.s. I am not fixing your code by intention, as learning is what is needed here.

**Comment by erictleung** [comment]
@pragya68 what @crashuniverse suggests is a good way to debug your issues in the future. The issue is because you're pushing to a non-existent `tracks` property for record 5439. It was intended for the user to check for this, but this requirement was a bit implied and should probably be more explicitly stated.

[In between these two lines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4504-L4505), this line of code needs to be put:

```
"If <code>\"tracks\"</code> is empty before you update it, create an empty array before pushing to it.",
```

This change should look like this:

![image](https://cloud.githubusercontent.com/assets/2754821/15806225/1706ea64-2af4-11e6-85df-313bbc4c09e7.png)

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by fkingn00bGG** [comment]
@erictleung Finally you have acknowledged this issue maybe now you can understand my fix? fking GG XD

**Comment by mav1283** [comment]
still can't resolve the issue, i tried creating an empty array before updating, same error. even tried clearing my cach on chrome and firefox, still the same error:  

"updateRecords(5439, "tracks", "Take a Chance on Me"), tracks should have "Take a Chance on Me" as the last element."

**Comment by profoundhub** [comment]
I noticed that a lot of people were having problems with this challenge, which is why I wrote a short blog post on CodePen about possible solutions, I hope you and others would find it helpful. Here's the URL: https://codepen.io/profoundcoder/post/record-collection

**Comment by mav1283** [comment]
Yes i tried solutions 1 2 and 3 but i keep getting this error:  **updateRecords(5439, "tracks", "Take a Chance on Me"), tracks should have "Take a Chance on Me" as the last element.**

seems like a cache thing, but i cleared all my browser's cache. still the same error.

please check the attached screenshot and look on the left side error number 2
![record collection - bug](https://cloud.githubusercontent.com/assets/11674969/15809993/3b9acd36-2bcc-11e6-8b32-4adcef98e82d.png)

**Comment by mav1283** [comment]
It worked now, someone from gitter suggest this: collection[id][[prop] = [value];

**Comment by crashuniverse** [comment]
What @erictleung suggests is a good indicator for user to know what needs to be done. If we all agree, I can pick it up.

**Comment by crashuniverse** [comment]
@mav1283 What you say will work only if collection[id] is an object and exists already so that you can access its propery `prop`.

**Comment by crashuniverse** [comment]
I am taking this up. I'll enhance something on lines of what @erictleung suggested.

**Comment by 1Copenut** [comment]
@crashuniverse Your comment about collection[id] being an object and already existing was a crucial hint for me to unlock this problem.

**Comment by profoundhub** [comment]
I have updated my post on CodePen: https://codepen.io/profoundcoder/post/record-collection

**Comment by profoundhub** [comment]
@mav1283 , could you recheck your solution, I tried it and it did not work for me, here is a screenshot: 
![mav1283 -record collection](https://cloud.githubusercontent.com/assets/8409825/16882281/3da047ee-4a8c-11e6-8865-4f74425189d3.png)

**Comment by profoundhub** [comment]
Sorry, I mixed up the Solution Code, here is @mav1283 's 
![mav1283-solution -record collection-2](https://cloud.githubusercontent.com/assets/8409825/16885751/183f9d26-4a9e-11e6-9d57-7be0c8d0d0ee.png)

**Comment by mav1283** [comment]
hey i must have forgotten this already, try this one

```
function updateRecords(id, prop, value) {
  
 if(value !== ""){
    if(prop !== "tracks"){
      collection[id][prop] = value;
    } else if(prop === "tracks"){
      if(collection[id].tracks){
        collection[id].tracks.push(value);
      } else {
        collection[id].tracks = [];
        collection[id].tracks.push(value);
      }
    }
  } else {
    delete collection[id][prop];
  }
  return collection;
}
```
