### ISSUE TITLE
Back End Development Curriculum

### ISSUE THREAD

**Issue by vaspv** [FreeCodeCamp/FreeCodeCamp#8971]
#### Challenge Name

https://www.freecodecamp.com/challenges/continue-working-with-nodejs-servers

#### Issue Description

This is a general issue about Back End Development curriculum. I recently completed Front End certificate and have moved to Back End but am struggling to orient myself within the curriculum. What I find is that I don't have any overall picture of back end development and how different things link together. It starts with console, git and then to node.js. Setting up Node.js is ok and command line takes some getting used to but is fine. Cloud9 is also good. But my issue is that the curriculum does not make it clear what is Cloud9 what is node.js, how they link, why they link etc. Second issue is around the exercises. The first 2-3 node.js were do-able but the step up from this to the "continue working" and "finish working" challenges is too steep. I find myself confused and have reached a point where I cannot understand. My aim is not to complain as such but to make people aware of learning roadblock in case others also are experiencing the same. The third confusion comes when setting up for backend projects. We are introduced to Clementine js so now we have that and cloud9, nodejs, expressjs, mongo, javascript, command line, and it is suddenly very overwhelming. Also in terms of tutorials, the node.js is ok but not really helpful in understanding what is being accomplished and how. For example, timeserver, hello world and summing array arguments are understandable but http client - what does that do? When can it ever be used? These things are not clear.  

The Front End curriculum is great. I wanted to suggest that Back End curriculum be modified so that it starts with overview and then progresses to concepts, examples and basic and advanced projects, just like Front End does. 

I would like to suggest the following and happy to contribute further as required:

1) The API projects be converted into exercises that have full worked solutions in the Wiki - much like intermediate/advanced algorithm scripting. Ideally these should also be made optional (not starred). Perhaps they can part of progression towards a larger fully worked back-end project so that we can know what the technologies are and how to use them? 
2) Have a new category of basic Back End projects where we perhaps use the Front End projects and then add back end elements to it  e.g. server supported Tic Tac Toe?

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
cc/ @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
Let's wait for the ongoing restructuring and address this, we surely welcome more feedback on this thread with ideas, possibly expanding the challenges into smaller bits, but yeah this should be further discussed.

@vaspv Thanks for letting us know, feed backs like these help shape the challenges. Having said that please expect that this may take a while, cause lots of re-structuring may take place in the certifications, post that we could possibly look into this.

**Comment by atjonathan** [comment]
Closing in favour of https://github.com/FreeCodeCamp/CurriculumExpansion/issues/26
