### ISSUE TITLE
Code style & answer verification

### ISSUE THREAD

**Issue by dkfiresky** [FreeCodeCamp/FreeCodeCamp#8972]
#### Challenge Name
Target Elements by ID Using jQuery
https://www.freecodecamp.com/challenges/target-elements-by-id-using-jquery

#### Issue Description
If you insert spaces between function arguments the answer will not be valid. If you omit the spaces, it will be all fine.

#### Browser Information
* Browser Name, Version: Safari 9.1 (11601.5.17.1)
* Operating System: OS X 10.11.4
* Mobile, Desktop, or Tablet: Desktop

This code will be invalid, since there are spaces:
```js
$( "#target3" ).addClass( "animated fadeOut" );
```

But this will be valid:
```js
$("#target3").addClass("animated fadeOut");
```

**Comment by erictleung** [comment]
@dkfiresky hmm this is odd. The [tests](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/jquery.json#L256-L257) are using jQuery selectors on the elements so spaces shouldn't be an issue, but I'm stumped.

cc/ @FreeCodeCamp/issue-moderators
