### ISSUE TITLE
Computer Basics - Quizzes are ending too early

### ISSUE THREAD

**Issue by dedalux** [FreeCodeCamp/FreeCodeCamp#8973]
#### Challenge Name

Any Computer Basics tutorial -- the quizzes for passing cut away from the last question and goes to the next lesson
#### Browser Information

- Browser Name, Version: Chrome
- Operating System: Win 10
- Mobile, Desktop, or Tablet: Desktop 
#### Your Code

``` js
// If relevant, paste all of your challenge code in here

```

**Comment by systimotic** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9861, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. 
Happy coding!
