### ISSUE TITLE
Record Collection Bug

### ISSUE THREAD

**Issue by mav1283** [FreeCodeCamp/FreeCodeCamp#8974]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%202548%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%202468%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%221999%22%2C%0A%20%20%20%20%20%20artist%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%201245%3A%20%7B%0A%20%20%20%20%20%20artist%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%205439%3A%20%7B%0A%20%20%20%20%20%20album%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20var%20identry%20%3D%20id%3B%0A%20%20var%20recordID%20%3D%20collection%5Bidentry%5D%3B%0A%20%20if(value%20!%3D%3D%22%22)%7B%0A%20%20%20%20if(prop%20%3D%3D%3D%20%22tracks%22)%7B%0A%20%20%20%20%20%20recordID%5Bprop%5D.push(value)%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20recordID%5Bprop%5D%20%3D%20value%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%20else%7B%0A%20%20%20%20%20delete%20recordID%5Bprop%5D%3B%0A%20%20%20%7D%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  var identry = id;
  var recordID = collection[identry];
  if(value !==""){
    if(prop === "tracks"){
      recordID[prop].push(value);
    }
    else{
      recordID[prop] = value;
    }
  }
   else{
     delete recordID[prop];
   }
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


I keep getting this error:

After updateRecords(5439, "tracks", "Take a Chance on Me"), tracks should have "Take a Chance on Me" as the last element.

and when i change the values to test the code i get this error on the console that says: recordID[prop] is undefined

**Comment by fkingn00bGG** [comment]
Perhaps you should try chat first. My answer is over here #8962 people are getting stumped on this question for the wrong reasons.

**Comment by fkingn00bGG** [comment]
@mav1283 after looking at your code as you can see
 ``` 
5439: {
      album: "ABBA Gold"
    }
```
has no `tracks` but you are trying to access it like so
```
if(prop === "tracks"){
      recordID[prop].push(value);
    }
```

My issue that was closed which should not of been talks about this

**Comment by mav1283** [comment]
yes because the requirement is push the valu
![record collection - free code camp 2016-06-05 22-46-00](https://cloud.githubusercontent.com/assets/11674969/15806126/5a783804-2b6f-11e6-861b-ac9035bd959c.png)
![record collection - free code camp 2016-06-05 22-46-00](https://cloud.githubusercontent.com/assets/11674969/15806131/65140298-2b6f-11e6-9666-37a6768405f7.png)

e if prop is equal to tracks, but since "tracks" is nonexistent on the array, i get this error:  "updateRecords(5439, "tracks", "Take a Chance on Me"), tracks should have "Take a Chance on Me" as the last element."  which is not part of the first intructions the first time i get into this challenge.

so i tried to make one by updating the properties, adding tracks and also update the prop value... i see the console now showing the album, artist and tracks on 5439 but i still get the same message.. 

please take a look at this screenshot

**Comment by erictleung** [comment]
Duplicate of #8970. Closing in favor of that issue.

**Comment by mutasimgsm** [comment]
try this, it w'll work 

function updateRecords(id, prop, value) {
  if (prop === "tracks" && value !== "") {
   if(collection[id][prop]) {
    collection[id][prop].push(value);
   }
   else {
    collection[id][prop]=[value];
   }
  } else if (value !== "") {
    collection[id][prop] = value;
  } else {
    delete collection[id][prop];
  }

  return collection;
}

**Comment by odulzaides** [comment]
In my code I kept getting the right results but not achieving a pass. Turns out I was not putting a return statement for the collection inside the function. That made it pass. Last detail was getting me!!!!

**Comment by ajitkumarsahu** [comment]
just create a tracks array in your 5439 property .
it works
