### ISSUE TITLE
Golf Code Challenge wiki article mispelling

### ISSUE THREAD

**Issue by Coding-in-progress** [FreeCodeCamp/FreeCodeCamp#8975]
#### Challenge Name
Challenge Golf Code

#### Issue Description
When referencing the Wiki article for this challenge it reads "Challenge **Gold** Code"

Simple typo is all.

**Comment by crashuniverse** [comment]
Good point. I see the problem at https://freecodecamp.github.io/wiki/en/challenge-golf-code/
The index for Article search also has this typo and so we have 2 instances of this problem.

**Comment by adisesharao** [comment]
I Didn't get any error msgs while completed this challenge i successfully completed this challenge and previous comments and codes are also exactly same but i don't know why they people are getting errors in some situations u can refer my following code








function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes==1)
    {
      return "Hole-in-one!";
    }
  else if(strokes <= par-2)
    {
      return "Eagle";
    }
  else if(strokes == par-1)
    {
      return "Birdie";
    }
  else if(strokes == par)
    {
      return "Par";
    }
  else if(strokes == par+1)
    {
      return "Bogey";
    }
  else if(strokes <= par+2)
    {
      return "Double Bogey";
    }
  else if(strokes >= par+3)
    {
      return "Go Home!";
    }
  else{
  return "Change Me";
  }
  // Only change code above this line

}

// Change these values to test
golfScore(5, 5);

**Comment by texas2010** [comment]
@adisesharao 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
