### ISSUE TITLE
Issue in <a> element wrapped in <p> element in lesson: http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph

### ISSUE THREAD

**Issue by KBLST** [FreeCodeCamp/freecodecamp#898]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue.

I marked the code correctly in the text editor and received: "Your a element should be wrapped within your new p element." this.

![a element wrapped in p](https://cloud.githubusercontent.com/assets/4502224/8118511/2a54acee-1044-11e5-90e0-55114823b254.PNG)

**Comment by KBLST** [comment]
Went back, and did it again, following instructions a little closer.

**Comment by Ekbaazigar** [comment]
KBLST..mind sharing what the issue was ? I am facing the same issue but cant seem to pin point

**Comment by Ekbaazigar** [comment]
never mind, i found it.

**Comment by sandaruwankodi** [comment]
<p>click here for <a href="http://www.catphotoapp.com">cat photos</a></p>
