### ISSUE TITLE
123

### ISSUE THREAD

**Issue by qinouz** [FreeCodeCamp/FreeCodeCamp#8983]
Challenge [Word Blanks](https://www.freecodecamp.cn/challenges/word-blanks#?solution=function%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20result%3DmyNoun%2B%20myAdjective%2B%20myVerb%2B%20myAdverb%3B%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0AwordBlanks(%22cat%22%2C%20%22little%22%2C%20%22hit%22%2C%20%22slowly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result=myNoun+ myAdjective+ myVerb+ myAdverb;

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");
wordBlanks("cat", "little", "hit", "slowly");

```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
