### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by HilalCelikmakas** [FreeCodeCamp/FreeCodeCamp#8985]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello World</h1>
```

**Comment by kabadayi28** [comment]
`<h1>hello</h1>
<h3>im cevher</h3>
`
Güzel bir uygulama ile başlamışsın :)) @HilalCelikmakas takip ediyorum, umarım güzel işler başarabilirsin.
