### ISSUE TITLE
Error in challenge 192 (Stand in Line)

### ISSUE THREAD

**Issue by kishimi8** [FreeCodeCamp/FreeCodeCamp#8986]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20var%20array%3B%0A%20%20arrayy%20%3D%20arr%20%3B%0A%20%20%0A%20%20arrayy%20%3D%20arrayy.push(item)%3B%0A%20%0A%20%0A%0AremovedFromOurArray%20%3D%20arrayy.shift()%3B%0A%20%20item%20%3D%20removedFromOurArray%3B%0A%20%20%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B2%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  var array;
  arrayy = arr ;
  
  arrayy = arrayy.push(item);
 
 

removedFromOurArray = arrayy.shift();
  item = removedFromOurArray;
  
  return item;  // Change this line
}

// Test Setup
var testArr = [2];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

keeps generating type error that arrayy.shift(); is not a function

**Comment by BKinahan** [comment]
Issues are for reporting bugs or problems with the website. For help with coding in the JavaScript algorithm sections please consult the [HelpJavaScript chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

It isn't a function. You assign the result of `arrayy.push(item)` to `arrayy` before attempting to use `shift()`, and the result of `arrayy.push(item)` is the new length of `arrayy`. See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push).

Numbers don't have a `shift()` method.

Happy coding.

**Comment by erictleung** [comment]
@kishimi8 I agree with what @BKinahan suggests. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
