### ISSUE TITLE
Escaping Character Issue

### ISSUE THREAD

**Issue by ritam378** [FreeCodeCamp/FreeCodeCamp#8987]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3B%20%2F%2F%20Change%20this%20line%0AmyStr%20%3D%20%22%20%5Cb%20%5Ct%20%5Ct%20%5Cr%20%5Cn%20%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr; // Change this line
myStr = " \b \t \t \r \n ";


```
![image](https://cloud.githubusercontent.com/assets/19747927/15819265/cb2b8cfa-2bff-11e6-860b-a58b07ecd977.png)

**Comment by aliblack89** [comment]
Try putting it on the same line as var myStr;

i.e. it would be: var myStr = "\b \t \t \r \n";

**Comment by ritam378** [comment]
Its working.
Thanks :)

**Comment by Shraddha99** [comment]
@ritam378 @aliblack89  I wrote same still its incorrect.

**Comment by erictleung** [comment]
@Shraddha99 if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by ritam378** [comment]
Hi , its backslah not backspace.
Pls correct that
