### ISSUE TITLE
Multiple Identical Options in Switch Statements

### ISSUE THREAD

**Issue by hitikrajpalhr** [FreeCodeCamp/FreeCodeCamp#8989]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@hitikrajpalhr thanks for the issue, but can you give more detail on what your issue is?

**Comment by erictleung** [comment]
@hitikrajpalhr closing as stale. If you're still having issues, please fill out the issue template as much as possible so that we may address your issue. Happy coding!
