### ISSUE TITLE
$(...).attr(...) is undefined in Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by iamrphy** [FreeCodeCamp/FreeCodeCamp#899]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue.

In the process of testing to fix another issue (https://github.com/FreeCodeCamp/freecodecamp/issues/898) I deleted 
"<a href='http://www.catphotoapp.com'>cat photos</a>" in the text editor and received this:

Cannot read property 'length' of null.

![cannot read property length of null](https://cloud.githubusercontent.com/assets/4502224/8118670/419840a4-1045-11e5-9098-e4d0f6f1d44c.PNG)

**Comment by LumenTeun** [comment]
This is an error message generated by the test code. Some of the challenges currently check if a certain case is true by checking if the length of it is over, say, 0. If the element it tries to check does't exist it tries to check the length of 'null', which doesn't work. I'm not sure how this would be resolved, but a workaround would probably be to copy your code and refresh the page so you can see the instructions again.

**Comment by BerkeleyTrue** [comment]
This challenge has been removed

Happy Coding!

**Comment by gzpaitch** [comment]
Hey, guys!

This challenge still there and I having the same problem right now!

How can I fix it? 

Thanks!

**Comment by Freya939** [comment]
+1 
Having same issue as gzpaitch on same challenge.

Thanks1

**Comment by ahstro** [comment]
Confirmed. Removing the anchor element which contains `cat photos` gives this error: `$(...).attr(...) is undefined`.
A similar error was reported in #965, and @BerkeleyTrue reported it fixed, but I couldn't find an associated commit. Any idea what the fix was Berk?

**Comment by BerkeleyTrue** [comment]
#965 was not reported fix. The OP did not include any context so it was blocked and eventually closed as abandoned. 

@ahstro The original reported issue is completely different from what you are reporting now and should be reported in a new issue not opening an old issues. That is why this issue was closed originally.

Also I cannot replicate either issue.

**Comment by BerkeleyTrue** [comment]
![waypoint__nest_an_anchor_element_within_a_paragraph___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/10463113/6a0ccf56-7197-11e5-8106-49b931f65a07.png)

**Comment by ahstro** [comment]
@BerkeleyTrue You need to remove the entire `<a>` node to see the error.
I understand not opening reopening this since it is a new waypoint, but since there was already discussion here, I took a chance. Won't happen again.

**Comment by ptsurbeleu** [comment]
@BerkeleyTrue Tried to address the issue by refactoring matching expression to rely on jQuery selectors instead.
