### ISSUE TITLE
If there is a commented line between if's closing `}` and `else` next to `if`, it doesn't accept my code.

### ISSUE THREAD

**Issue by smhnaji** [FreeCodeCamp/FreeCodeCamp#8993]
Challenge [Introducing Else Statements](https://www.freecodecamp.com/challenges/introducing-else-statements#?solution=%0Afunction%20testElse(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(val%20%3E%205)%20%7B%0A%20%20%20%20result%20%3D%20%22Bigger%20than%205%22%3B%0A%20%20%7D%20%20%0A%20%20else%20%7Bresult%20%3D%20%225%20or%20Smaller%22%3B%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestElse(4)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testElse(val) {
  var result = "";
  // Only change code below this line
  
  if (val > 5) {
    result = "Bigger than 5";
  }  
  // if (val <= 5) {  //////////// THIS LINE CAUSES THE PARSER, NOT ACCEPT MY CODE.
  else {result = "5 or Smaller";}
  // }
  
  // Only change code above this line
  return result;
}

// Change this value to test
testElse(4);


```

If there is a commented line between if's `}` and `else`, it doesn't accept my code.

<img width="787" alt="screen shot 2016-06-06 at 23 58 10" src="https://cloud.githubusercontent.com/assets/13175046/15834863/b3e95ade-2c42-11e6-968d-d1da4a56819e.png">

<img width="1100" alt="screen shot 2016-06-06 at 23 58 44" src="https://cloud.githubusercontent.com/assets/13175046/15834886/cb1669d6-2c42-11e6-9420-95c0693effff.png">

**Comment by erictleung** [comment]
@smhnaji the issue is actually the inclusion of `if` in your comment. The test is a regular expression looking for only one `if` statement. I'm not sure if we can parse just the uncommented code.

@raisedadead In #8653, we have a similar problem as this one. For a quick fix, we could do the same thing here and rewrite the problem test with a warning so the test goes from:

> You should only have one `if` statement

to 

> You should only have one `if` statement **in the editor**

**Comment by smhnaji** [comment]
Thanks @erictleung, that's right.

It's a good idea to add "**in the editor**", so it cannot be called a bug from then! :D

**Comment by raisedadead** [comment]
@erictleung Yeah I agree for the quick fix.

**Comment by NicolaFerracin** [comment]
Can I take this?

**Comment by raisedadead** [comment]
Sure @NicolaFerracin go ahead, make a pull request, and make sure you go through our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by NicolaFerracin** [comment]
Thanks @raisedadead !

I went through the guidelines and it should be all fine (fingers-crossed!)
