### ISSUE TITLE
Check for Palindromes

### ISSUE THREAD

**Issue by sergroja** [FreeCodeCamp/FreeCodeCamp#8994]
Check for Palindromes
https://www.freecodecamp.com/challenges/check-for-palindromes

One of the tests for the string is not equal but it should return true.

palindrome("0_0 (: /-\ :) 0-0") should return true

Chrome 50.0.2661.102
Linux

**Comment by tianz** [comment]
It says "You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.". Then the string becomes "0000" which is indeed a palindrome.

**Comment by erictleung** [comment]
@sergroja what @tianz suggests is correct. There is nothing wrong with the current. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by hudsontaylor** [comment]
But, technically, "0_0 (: /-\ :) 0-0" is not a palindrome. So, shouldn't it return false?
