### ISSUE TITLE
Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by hrokr** [FreeCodeCamp/FreeCodeCamp#8995]
@erictleung, @pranayberry, @raisedadead, @ceejayoz

#### Issue Description
As with the previous exercise (Write Reusable JavaScript with Functions -- issue #8551) the example code and what the students are to write are essentially identical. The identical function name becomes confusing. 

Either slightly renaming either function would be helpful or saying "rewrite the function, changing the contents of ..... " would be helpful in this case.

#### Screenshot

![screen shot 2016-06-06 at 5 08 41 pm](https://cloud.githubusercontent.com/assets/9368785/15837989/d4487c76-2c09-11e6-8b67-ce2c4351dda3.png)

**Comment by erictleung** [comment]
@hrokr thanks for the issue. Looks like this was fixed with a recently PR #9485. Closing as resolved. Happy coding!
