### ISSUE TITLE
Import a Google Font

### ISSUE THREAD

**Issue by marisbotero** [FreeCodeCamp/FreeCodeCamp#9000]
Challenge [Import a Google Font](https://www.freecodecamp.com/challenges/import-a-google-font) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by erictleung** [comment]
@marisbotero please describe the issue or bug you are experiencing, if any. Your code doesn't pass the challenge tests. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue is legitimate!
