### ISSUE TITLE
Stuck on persistent problem....

### ISSUE THREAD

**Issue by Fleestrom** [FreeCodeCamp/FreeCodeCamp#9007]
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>View more <a href="http://www.freecatphotoapp.com"> cat photos </a></p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

Tried submitting this every which way, no help from Forums....Still telling me that I need a space after "View more"...

**Comment by Fleestrom** [comment]
I did try it with no spaces before and after "cat photos"...same result

**Comment by arun1595** [comment]
Thats because the link you're targetting is http://www.freecatphotoapp.com but the link given in the instructions is http://freecatphotoapp.com
Remove the **www** and you should be good to go.

**Comment by erictleung** [comment]
@Fleestrom which challenge are you having issues with? Is it https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph. If so, you code passes for me but please confirm that this is the challenge you're having issues with, otherwise, it makes it difficult to assist.

**Comment by Fleestrom** [comment]
Thank you so much for taking the time: your input allowed me to clear this
exercise!

**Comment by erictleung** [comment]
Closing as the issue seems to be resolved.

**Comment by dorenecom** [comment]
I tried the fix above (taking the www out of the url) and it didn't seem to help UNTIL I refreshed the page. Thanks!

**Comment by sunshineaustin** [comment]
It looks like a bug. When your code is correct, and the Run test does not work, refresh the page and try again.
