### ISSUE TITLE
Instruction text overflows in one of the challenges

### ISSUE THREAD

**Issue by arun1595** [FreeCodeCamp/FreeCodeCamp#9009]
#### Challenge Name

https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements
#### Issue Description

In the instructions, learners are asked to create an anchor tag that points to `http://freecatphotoapp.com`. In the tests output, if you have a look at the link, 'm' in 'com' is hidden as the text is overflowing and it shows `http://freecatphotoapp.co`. This might confuse the learners.
The problem is because `code` tag doesn't wrap by default.
Check out my fix for this issue at [this codepen](http://codepen.io/arun1595/pen/RRWjgN)
#### Browser Information

* Browser Name, Version: Google Chrome 51.0.2704.79
* Operating System: Ubuntu 16.04 LTS

#### Screenshot

![link](https://cloud.githubusercontent.com/assets/7039523/15863635/77cdf5f0-2cf1-11e6-99d9-21db579706f9.png)

**Comment by erictleung** [comment]
@arun1595 we can probably solve this using the same method as in #8911, where we use `<wbr>` to break at a particular point.

cc/ @hallaathrad
