### ISSUE TITLE
Waypoint: Add Images to your Website

### ISSUE THREAD

**Issue by nishgop** [FreeCodeCamp/freecodecamp#901]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Problem:
<img src="http://bit.ly/fcc-kittens"/> does not seem to work. It works well in http://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic.

**Comment by nishgop** [comment]
1) Using CSS:

"<style>
.MyClass123{
	content:url("http://bit.ly/fcc-kittens");
}
</style>
<img class="MyClass123"/>"

2) Using HTML:


<img src="http://bit.ly/fcc-kittens"/>

**Comment by LumenTeun** [comment]
Please write your code wrapped in ``` so we can see it.

**Comment by nishgop** [comment]
It got resolved after I restarted chrome. Not quite sure why it did not recognize it.

**Comment by LumenTeun** [comment]
Glad to hear it worked out. Remember to close this if it's no longer an issue.
