### ISSUE TITLE
Spelling error in Code of Conduct

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9010]
#### Challenge Name

https://www.freecodecamp.com/code-of-conduct

#### Issue Description

Underneath "Trolling"

> ...posting inflamitory comments...

should be 

> ...posting inflammatory comments... 

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/e5c18bed602b257aeaea72565413eb0eb09dba27/server/views/resources/code-of-conduct.jade#L11) needs to be changed.

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/15864008/2037ce36-2c8a-11e6-9e5f-052274bbda18.png)

**Comment by gr2m** [comment]
Just want to say thanks for making a `first-timers-only` issue out of it, instead of doing it yourself ❤️ We know this is much more work for you :)
