### ISSUE TITLE
check for palindromes

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#9012]
https://www.freecodecamp.com/challenges/check-for-palindromes

Seems like we have a huge issue with campers forgetting to remove non-alphanumeric chars for this challenge. I suggest we add a simple test at the top to make sure the user is stripping non-alphanumeric characters first.

I suggest adding a test after the second one like so
```
palindrome("eye") should return a boolean.
palindrome("eye") should return a true.
palindrome("_eye") should return a true.
```

What do y'all think?

**Comment by simplywondrous** [comment]
Definitely a first-timer - can I work on this issue?

**Comment by atjonathan** [comment]
@simplywondrous, certainly :smile: 

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by erictleung** [comment]
Anyone wanting to fix this, you'll need to the following a line of code [below this line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/83868f9f591a9752f0b74fa261a24793df507755/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L175):

```
"assert(palindrome(\"_eye\") === true, 'message: <code>palindrome(\"_eye\")</code> should return true.');",
```

**Comment by simplywondrous** [comment]
I appreciate the help, however while I am a first-timer I'd have liked to have the opportunity to figure out this small task myself without "copy this and paste it here." I know it's been almost a week since I picked up the issue, however my internet's been spotty. It should be fixed in a day or two and I shall make my first contribution then!

**Comment by erictleung** [comment]
@simplywondrous I apologize if I came off condescending in any way. My help was directed to anyone who wanted to contribute and wanted to lower the barriers on contributing as figuring out how to git this and that can sometimes be challenging. I probably should have asked if you were still planning on working on it. Thanks for your enthusiasm in contributing! FreeCodeCamp is ever changing so there are bound to be more issues to be solved! 😃

**Comment by luongthomas** [comment]
Hello, I was wondering if I could contribute to this issue.  This will be my first contribution to an open source project.  I have corrected basic-bonfires to add a new test to include "_eye" to result in false.  Could I open a pull request?  Unless simplywonderous has dibs on it.
