### ISSUE TITLE
Check for Palindromes - Error

### ISSUE THREAD

**Issue by hudsontaylor** [FreeCodeCamp/FreeCodeCamp#9014]
On the "Check for Palindromes" test one of the requirements states, "palindrome("0_0 (: /-\ :) 0-0") should return true."
However, this set of characters does not appear to be a palindrome at all. By definition, a palindrome is identical forwards or backwards. In this case, the "_" is not the same as the "-". 
So, I am wondering why this is one of the requirements on this test?

Note: I did manage to solve this problem anyways.

Thanks much!

**Comment by sludge256** [comment]
Removing all non-alphanumeric characters would leave you with "0000". This is addressed in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9012.

**Comment by hudsontaylor** [comment]
Yes, but "0_0 (: /-\ :) 0-0" is not a palindrome, so it would be erroneous for it to be evaluated as true.

**Comment by sludge256** [comment]
I guess compared to all the other test cases this one is "forced" into being a palindrome. "0_0 (: /-\ :) 0-0" seems to be an abstract test case to check for what's being discussed in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9012. If said issue is resolved by a PR it might be worth removing this test case.

**Comment by hudsontaylor** [comment]
Good point! Maybe a requirement should be added in its place, such as, "If the string is made up of only nonalphanumeric characters, return 'Not a valid entry." (or something along those lines)

**Comment by crashuniverse** [comment]
@hudsontaylor: `0_0 (: /-\ :) 0-0` IS a palindrome. 

Wikipedia definition says, _A palindrome is a word, phrase, number, or other sequence of characters which reads the same backward or forward. Allowances may be made for adjustments to capital letters, punctuation, and word dividers._ 

`-, _` are word dividers and I believe it extends to more non alphabetical characters, just like @sludge256  earlier mentioned.

IMO there is no scope of improvement, unless we add additional learning, but the challenge looks stable to me. A suggestion mentioned in the other issue referenced earlier looks better, and I'd refrain from talking more about that here.

**Comment by BerkeleyTrue** [comment]
Please move discussion to #9012
