### ISSUE TITLE
Compound Assignment With Augmented Addition

### ISSUE THREAD

**Issue by Mzahoor** [FreeCodeCamp/FreeCodeCamp#9016]
Challenge [Compound Assignment With Augmented Addition](https://www.freecodecamp.com/challenges/compound-assignment-with-augmented-addition#?solution=%0Avar%20a%20%3D%203%3B%0Avar%20b%20%3D%2017%3B%0Avar%20c%20%3D%2012%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0A%2B%3D%20a%20%2B%2012%3B%0A%2B%3D%209%20%2B%20b%3B%0A%2B%3D%20c%20%2B%207%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

+= a + 12;
+= 9 + b;
+= c + 7;


```

**Comment by erictleung** [comment]
@Mzahoor thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: review the example in the instructions. Happy coding!

**Comment by RomingArt** [comment]
This is what I wrote up, and I was able to pass the section, but I wanted to know if my syntax is correct. `var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

a = a += 12;
b = b += 9;
c = c += 7;


`

**Comment by texas2010** [comment]
@RomingArt 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by DomingoSanzPerez** [comment]
Hy, my code was.

var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

+= a + 12;
+= b + 9; // in this line I change b for 9.
+= c + 7;

**Comment by riturajpandey93** [comment]
var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

a += 12;
b += 9;
c += 7;

**Comment by lyndel2** [comment]
var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

a += 12;
b += 9;
c += 7;
I hope this will help with your question
