### ISSUE TITLE
Waypoint: Link to External Pages with Anchor Elements

### ISSUE THREAD

**Issue by justaposed** [FreeCodeCamp/freecodecamp#902]
Challenge http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

As soon as you add "<a" you are allowed to move onto the next challenge.

**Comment by LumenTeun** [comment]
I can not reproduce this. Can anyone else confirm?
