### ISSUE TITLE
confirm-the-ending test  not match : Check if a string (first argument, str) ends with the given target string (second argument, target).

### ISSUE THREAD

**Issue by yanbin92** [FreeCodeCamp/FreeCodeCamp#9021]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```
the test 'confirmEnding("He has to give me a new name", "me") should return true.'
is not match the disclusion Check if a string (first argument, str) ends with the given target string (second argument, target).

**Comment by yanbin92** [comment]
sorry  i  see  this is not bug , I misunderstood it.

**Comment by Ollysho** [comment]
I would like to reopen this, maybe I'm understanding it wrong, but that should return false no? me is not the last letter or word of that string
