### ISSUE TITLE
Record Collection challenge does not pass all tests

### ISSUE THREAD

**Issue by kelyjames** [FreeCodeCamp/FreeCodeCamp#9023]
#### Challenge Name
.freecodecamp.com/challenges/record-collection

#### Issue Description
Even with the solution from the challenge guide the 2nd test does not pass  
After updateRecords(5439, "tracks", "Take a Chance on Me"), tracks should have "Take a Chance on Me" as the last element.

#### Browser Information

tested on Windows 10 with firefox and edge and chrome

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function updateRecords(id, prop, value) {
  if (prop === "tracks" && value !== "") {
    collection[id][prop].push(value);
  } else if (value !== ""){
    collection[id][prop] = value;
  } else {
    delete collection[id][prop];
  }

  return collection;
}
```

#### Screenshot

![screenshot-www freecodecamp com 2016-06-07 `21-32-40](https://cloud.githubusercontent.com/assets/1762608/15881945/89af329c-2cf7-11e6-8c0b-1d4a31a27c49.png)`

**Comment by kelyjames** [comment]
I found out the correct solution to this does not use push for that 2nd test but the solution in the guide has not been updated to not use push

**Comment by xboudsady** [comment]
Yeah, seriously. This one been driving me up the walls! So Frustrating.

**Comment by crashuniverse** [comment]
This is a duplicate of  #8970 
@xboudsady If you follow the thread in above mentioned issue, it talks about a solution and proposes an update in instructions. I also know that in future this will no longer be a problem as our tests are being updated in a way to do a fail safe check for existence of this array.

Sending this message primarily so that @xboudsady doesn't stay blocked with this challenge by looking at hints in other issue.

**Comment by trmeyer1** [comment]
What do I use if i take out PUSH? This challenge is rough. Lol.

**Comment by HasanatJahan** [comment]
Did you solve it yet?

**Comment by axelashi** [comment]
`else if (prop === "tracks" && collection[id].hasOwnProperty("tracks") === false) {
  collection[id][prop] = [];
    collection[id][prop].push(value);
      } `
you should create an empty array. after hasOwnProperty test it sees that there is no array tracks for id 5439.
