### ISSUE TITLE
Incorrect description of first test for the Inventory Update algorithm challenge.

### ISSUE THREAD

**Issue by joechan3** [FreeCodeCamp/FreeCodeCamp#9025]
#### Challenge Name

Inventory Update
https://www.freecodecamp.com/challenges/inventory-update

#### Issue Description

The first test for the Inventory Update algorithm challenge is described as `updateInventory() should return an array.`

The description should really be `updateInventory(curInv, newInv) should return an array.` because if you don't provide arguments to the `updateInventory` function call, you will get at the least an `undefined` value back and at the worst an `Uncaught TypeError`.

You can tell this is what the actual test is doing because if you leave only
```
function updateInventory(arr1, arr2) {
    // All inventory must be accounted for or you're fired!
    return arr1;
}
```
it still passes the test in question. In other words, the test is passing the `updateInventory` function at least one array argument and the `updateInventory` function returns an array as a result.

If you agree with this issue, may I get permission to fix it with a pull request? :D

#### Browser Information

N/A
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
N/A
```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

N/A

**Comment by erictleung** [comment]
@joechan3 thanks for the feedback. And I agree. It could be misinterpreted.

I'd be hesitant to hard code those variable parameters in. What about this:

> The function `updateInventory` should return an array.

**Comment by joechan3** [comment]
@erictleung your fix is more appropriate so I agree!

**Comment by erictleung** [comment]
@joechan3 great! 👍  You're welcome to make a PR now if you still want to 😃 

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by joechan3** [comment]
@erictleung Awesome! I will work on the PR today.
