### ISSUE TITLE
unable to get the the text: CatPhotoApp to show in red

### ISSUE THREAD

**Issue by miguel361** [FreeCodeCamp/FreeCodeCamp#9026]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3Ablue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2 style="color:blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
@miguel361 your code is incorrect. The `h2` element has a blue color but it should be red.

> Change your `h2` element's style so that its text color is red.

I see you have made use of [Help Room](https://gitter.im/FreeCodeCamp/Help). Please continue to use that resource for coding help. GitHub issues are only for bugs. Unless you feel this is truly a bug, please give us more details on reproducing the error. Happy coding!
