### ISSUE TITLE
ddd

### ISSUE THREAD

**Issue by sanjeev17** [FreeCodeCamp/FreeCodeCamp#9033]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Chtml%3E%0A%20%20%3Ctitle%3Efirst%20login%3C%2Ftitle%3E%0A%20%20%3Cbody%3E%0A%20%20%20%20%3Cp%20style%3D%22align%3Acenter%22%3Ekumar%20sanjeev%3C%2Fp%3E%20%20%20%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%20%20%20%20%3Ctable%20border%3D%222%22%20color%3D%22red%22%3E%0A%20%20%20%20%20%20%3Cthead%3E%0A%20%20%20%20%20%20%20%20%3Cth%3ESerial%20No.%3C%2Fth%3E%0A%20%20%20%20%20%20%20%20%3Cth%3EFirst%20Name%3C%2Fth%3E%0A%20%20%20%20%20%20%20%20%3Cth%3ELast%20Name%3C%2Fth%3E%0A%20%20%20%20%20%20%3C%2Fthead%3E%0A%20%20%20%20%20%20%3Ctbody%3E%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%20%3Ctd%3E1.%3C%2Ftd%3E%0A%20%20%20%20%20%20%3Ctd%3Esanjeev%3C%2Ftd%3E%0A%20%20%20%20%20%20%3Ctd%3Ekumar%3C%2Ftd%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%3C%2Ftr%3E%0A%20%20%20%20%20%20%3C%2Ftbody%3E%0A%20%20%20%20%3C%2Ftable%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<html>
  <title>first login</title>
  <body>
    <p style="align:center">kumar sanjeev</p>   
<h1>Hello</h1>
    <table border="2" color="red">
      <thead>
        <th>Serial No.</th>
        <th>First Name</th>
        <th>Last Name</th>
      </thead>
      <tbody>
        
    <tr>
      <td>1.</td>
      <td>sanjeev</td>
      <td>kumar</td>
      
    </tr>
      </tbody>
    </table>

```

**Comment by dwd2010** [comment]
@sanjeev17 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help.

Happy Coding!
