### ISSUE TITLE
error telling me i didn't use -=

### ISSUE THREAD

**Issue by bigos** [FreeCodeCamp/FreeCodeCamp#9038]
Challenge [Compound Assignment With Augmented Subtraction](https://www.freecodecamp.com/challenges/compound-assignment-with-augmented-subtraction#?solution=%0Avar%20a%20%3D%2011%3B%0Avar%20b%20%3D%209%3B%0Avar%20c%20%3D%203%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0Aa%20-%3D%206%3B%0Ab%20-%3D%2015%3B%0Ac%20-%3D%201%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var a = 11;
var b = 9;
var c = 3;

// Only modify code below this line

a -= 6;
b -= 15;
c -= 1;



Pressing ctrl+enter lets me submit the task but I still get the red error message about missing -= operator

**Comment by erictleung** [comment]
@bigos sorry, but I can't reproduce this. Your code looks fine to me and the third test didn't give me any problems. Can you provide a screenshot of your issue?

**Comment by zackharley** [comment]
@bigos have you tried refreshing your browser? I've gotten weird errors before due to browser caching. You might also want to try clearing your cookies and cached data.

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue still occurs!

**Comment by bigos** [comment]
I've just tiried it on another machine and it worked flawlessly. Strange!
