### ISSUE TITLE
Inserting random code appears to pass the challenge.

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/freecodecamp#904]
Challenge http://www.freecodecamp.com/challenges/bonfire-chunky-monkey has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I was using the Bonfire challenge to test some random code and the challenge appears to 'Pass'; without any correlation to the challenge itself:

var arr = [
  { id: 15 },
  { id: -1 },
  { id: 0 },
  { id: 3 },
  { id: 12.2 },
  { },
  { id: null },
  { id: NaN },
  { id: 'undefined' }
];

var invalidEntries = 0;

function filterByID(obj) {
  if ('id' in obj && typeof(obj.id) === 'number' && !isNaN(obj.id)) {
    return true;
  } else {
    invalidEntries++;
    return false;
  }
}

var arrByID = arr.filter(filterByID);

console.log('Filtered Array\n', arrByID); 
// [{ id: 15 }, { id: -1 }, { id: 0 }, { id: 3 }, { id: 12.2 }]

console.log('Number of Invalid Entries = ', invalidEntries); 
// 4

![challenge pass](https://cloud.githubusercontent.com/assets/12093799/8131810/df0429ca-10ea-11e5-8436-2d2de4c7e450.png)

**Comment by JesseNoBata** [comment]
This seems to work for a few challenges: Bonfire: Seek and Destroy
Difficulty, though it doesn't mark the challenge as 'Passed'

**Comment by BerkeleyTrue** [comment]
Please stick to modifying the contents of the function only. 

Happy Coding!
