### ISSUE TITLE
Unable to submit corrected code (change the text colour of <h2>)

### ISSUE THREAD

**Issue by bryanoid** [FreeCodeCamp/FreeCodeCamp#9043]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%3Cstyle%3E%0A%20%20.red-text%7B%0A%20%20%20%20colour%3Ared%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text{
    colour:red;
  }
</style>
<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
@bryanoid HTML uses the American English spelling of `color`. Happy coding!

**Comment by atjonathan** [comment]
@bryanoid, you have a spelling mistake:
~~`colour`~~ `color`
You use american spellings in CSS. 

Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by bryanoid** [comment]
Thanks.i might be sleeping....

**Comment by CGalloza** [comment]
Hi, I've made something wrong here?

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by erictleung** [comment]
@CGalloza if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
