### ISSUE TITLE
myVar = myVar should be changed

### ISSUE THREAD

**Issue by Eclogesh** [FreeCodeCamp/FreeCodeCamp#9044]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyVar%20%3D%20myVar%2B1%3B%0A%0AmyVar%20%3D%20myVar%2B%2B%3B%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line

myVar = myVar+1;

myVar = myVar++;





```

**Comment by erictleung** [comment]
@Eclogesh thanks for the issue but GitHub issues are not for code help. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by sonalsp** [comment]
myVar = myVar should be changed still gives a no check when code is changed in any way.

code:
var myVar = 87;

// Only change code below this line
myVar = ++myVar;

**Comment by JakeHenshall** [comment]
This should be the code:

var myVar = 87;

// Only change code below this line
var total = ++myVar;

**Comment by felipemarques8** [comment]
This should be the code:

var myVar = 87;

// Only change code below this line
++myVar;

**Comment by sun1994** [comment]
var myVar = 87

you can change the var name 
like, var myvar = myVar++ +1;

then you will get result.
