### ISSUE TITLE
Minor UI Breaking: Simon Game

### ISSUE THREAD

**Issue by udbhavaashu1** [FreeCodeCamp/FreeCodeCamp#9046]
#### Build a Simon Game
https://www.freecodecamp.com/challenges/build-a-simon-game

#### Issue Description
The UI of featured Simon Game is breaking slightly.
https://codepen.io/Em-Ant/full/QbRyqq/

#### Browser Information
* Browser Name, Version: Chrome 53.0.2756.0
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/9340783/15918489/cb065aee-2e24-11e6-8ecb-76b161984bfe.png)

**Comment by erictleung** [comment]
@udbhavaashu1 thanks for the feedback but can you be more specific on how the UI is breaking? It works fine for me.

**Comment by udbhavaashu1** [comment]
No functional bug.
Just that the four layers of buttons should not be visible outside the circular area
(You may refer the attached screenshot.)

Please correct me if I'm wrong.

![image](https://cloud.githubusercontent.com/assets/9340783/15918706/606c4d3a-2e27-11e6-8f89-cbd58d025947.png)

**Comment by erictleung** [comment]
@udbhavaashu1 oh I see. I can't reproduce this. This is what I see:

![image](https://cloud.githubusercontent.com/assets/2754821/15918790/83de1ee6-2dbf-11e6-8e54-933b783a9dc7.png)

**Comment by udbhavaashu1** [comment]
Okay, then it might be system specific.
Kindly ignore this.

**Comment by atjonathan** [comment]
@udbhavaashu1 @erictleung, works fine for me :confused:

**Comment by raisedadead** [comment]
Closing as stale, kindly re-open if able to reproduce.
