### ISSUE TITLE
Challenge "Reusable Javascript with Functions"

### ISSUE THREAD

**Issue by stephenKise** [FreeCodeCamp/FreeCodeCamp#9047]
Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20reusableFunction()%20%7B%0A%20%20console.log(%22Heyya%2C%20World%22)%3B%0A%7D%0A%0AreusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20reusableFunction()%20%7B%0A%20%20console.log(%27Hi%20World%27)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0</code>.

My code:
```javascript

// Example
function reusableFunction() {
  console.log("Heyya, World");
}

reusableFunction();

// Only change code below this line
function reusableFunction() {
  console.log('Hi World');
}

```

This challenge states to "Call reusableFunction after you define it" again. However, the second step of this challenge is not checked in the user's input.

**Comment by erictleung** [comment]
@stephenKise this issue should be resolved with a recently merged PR #9485. The changes have yet to be pushed to the live site but will be soon. Closing as resolved. Happy coding!

**Comment by Vipersad** [comment]
// Example
function ourReusableFunction() {
```  
console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction() {
  console.log("Hi World");
}
reusableFunction();
```

**Comment by meizaifeng** [comment]
```
function reusableFunction(x, y) {
  var sum = x + y;
  console.log("Hi World");
}

reusableFunction();
```

**Comment by vaheed-sediqi** [comment]
just remove the Example code from above and run the code

// Example


// Only change code below this line

function reusableFunction(x, y) {
  var sum = x + y;
  console.log("Hi World");
}

reusableFunction();

**Comment by spookysaint** [comment]
> ```
> function reusableFunction(x, y) {
>   var sum = x + y;
>   console.log("Hi World");
> }
> 
> reusableFunction();
> ```

I cannot understand why does this works. Does this mean that we can't directly make a function with empty parenthesis in javascript?

**Comment by Sky020** [comment]
@spookysaint,

In general, I recommend you open a topic on the [forum](https://forum.freecodecamp.org) for a question like this.

Have a go  at running this code to see what is happening:
```
function reusableFunction(x, y) {
  var sum = x + y;
  console.log("Hi World", x, y, sum);
}

reusableFunction(); // x and y are not defined... therefore, they get a value of ____?
```
