### ISSUE TITLE
paragraph color change without class

### ISSUE THREAD

**Issue by digambarthete** [FreeCodeCamp/FreeCodeCamp#9049]
Challenge [Style Multiple Elements with a CSS Class](https://www.freecodecamp.com/challenges/style-multiple-elements-with-a-css-class) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p> <h class="red-text"> Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. </h> </p>

```

**Comment by Yannickhj** [comment]
class="" should be between the paragraph <p>arrows. the h stands for heading but you need to change the color of the normal paragraph text. 

Code should be:
`<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>`

Same way as the head text but between the <p> tag.

**Comment by erictleung** [comment]
@digambarthete what @Yannickhj suggests is correct. Your code is incorrect. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
