### ISSUE TITLE
Grammar error in the "Join our chat room" page

### ISSUE THREAD

**Issue by thegluestickman** [FreeCodeCamp/freecodecamp#905]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has a grammar error.

 **Item 3:** Click this link, which will email you can invite to Free Code Camp's Slack chat rooms: http://freecodecamp.com/api/slack.

**Suggested Edit:** Click on this link, it will send you an email inviting you to join Free Code Camp's Slack chat rooms: http://freecodecamp.com/api/slack.

**Comment by LumenTeun** [comment]
+1

If you've never created a pull request, this is a good opportunity.

**Comment by thegluestickman** [comment]
I agree @LumenTeun, I just have no idea where to start looking for that page in the repository haha.

**Comment by NatashaHaggard** [comment]
Suggested new edit - change the chat room to Gitter since we are moving back over there - http://blog.freecodecamp.com/2015/06/so-yeah-we-tried-slack-and-we-deeply-regretted-it.html

**Comment by thegluestickman** [comment]
It seems to be fixed since the page was updated. It can be closed now I guess :)

**Comment by LumenTeun** [comment]
@thegluestickman Most of the stuff related to challenges, at least the stuff relevant to the users, is located in the `seed` folder, but feel free to @ me on Gitter if you need a walkthrough :)
