### ISSUE TITLE
https page not loading buttons properly for "Inherit Styles from the Body Element" Map

### ISSUE THREAD

**Issue by chelleis** [FreeCodeCamp/FreeCodeCamp#9050]
Challenge [Inherit Styles from the Body Element](https://www.freecodecamp.com/challenges/inherit-styles-from-the-body-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The Test, Reset, Help, and Bug buttons are missing from my Map [53] "Complete Inherit Styles from the Body Element" page (please see attached screenshot) when default https page loads in Chrome browser.

Tried a hard refresh, did not find freecodecamp in my local storage (followed the instructions https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Clear-Specific-Data-Local-Storage), closed my browser and signed out/signed in my freecodecamp account, but it was still unable to load the buttons.  

Resolved this issue by manually changing the default 'https' in the URL to 'http'.  The page reloaded with https in the URL, then the buttons appeared.  But it requires me to do this in order to load the page correctly. 

Aloha,
Michelle
![screen shot 2016-06-09 at 12 00 49 am](https://cloud.githubusercontent.com/assets/6703856/15926567/69e5158a-2dd8-11e6-958e-b715064488c2.png)

My code:
```html

<style>
  body {
    background-color: green;
    font-family: Monospace;
  }
<h1>Hello World</h>
  </body>
</style>

```

**Comment by erictleung** [comment]
@chelleis the code you have is incorrect. Does making it correct fix or help your issue? Thanks for the details on how you were able to reproduce it for yourself. Unfortunately, I was unable to reproduce your issue.

cc/ @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
Cannot reproduce. Maybe an issue with screen resolution? What happens when you zoom out @chelleis?

**Comment by chelleis** [comment]
Jonathan, the buttons appeared after zooming out to 90%!

[image: Inline image 1]

**Comment by ramir141974** [comment]
Hello everyone just to let them know regarding my Github account I thing we have issue and I really don't now how to proceed because I'm first timer only of this site thank you.

**Comment by raisedadead** [comment]
Closing as stale, please comment to re-open.

**Comment by franzryan** [comment]
i have the same problem with this challenge. i tried removing and adding body tags but its still not working
![image](https://cloud.githubusercontent.com/assets/20453878/16839665/dd4779f0-4a02-11e6-9909-9bfb63b627e7.png)

**Comment by franzryan** [comment]
i have the same problem with this challenge. i tried removing and adding body tags but its still not working for me.
![image](https://cloud.githubusercontent.com/assets/20453878/16839704/17595316-4a03-11e6-8390-38fc64b5e4b7.png)

**Comment by raisedadead** [comment]
@franzryan Can you specify the viewport size (your screen's resolution), OS and browser details and the code?

**Comment by franzryan** [comment]
@raisedadead sorry i got it already. it says color not bgcolor. my bad.

**Comment by Enkhtr** [comment]
that's work
<style>
  body {
    color: green;
    font-family: monospace;
    
  }

</style>
<h1>Hello World</h1>

**Comment by Enkhtr** [comment]
background-color: green; no
color: green;  yes yes
