### ISSUE TITLE
test cases not displaying value of num

### ISSUE THREAD

**Issue by yuens1002** [FreeCodeCamp/FreeCodeCamp#9057]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncateString(str%2C%20num)%20%7B%0A%20%20%0A%20%20%2F%2F%20if%20num%20%3E%20str.lenght%2C%20return%20str%0A%20%20%2F%2F%20else%20if%20num%20%3C%3D%203%0A%20%20%2F%2F%20%20%20truncate(str-num).concat('...')%2C%20return%20str%0A%20%20%2F%2F%20else%2C%20truncate%20str%20starting%20at%200%20index%20to%20num-3%20index%0A%20%20%2F%2F%20str.concat(%22...%22)%2C%20return%20str%0A%20%20%0A%20%20%2F%2Fassuming%20equal%20to%20as%20well%20since%0A%20%20%2F%2F%20%20there%20would%20be%20no%20reason%20to%20truncate%20str%20if%0A%20%20%2F%2F%20%20the%20correct%20num%20of%20char%20can%20be%20shouwn%0A%20%20%2F%2F%20%20w%2Fo%20the%20elipses%0A%20%20%0A%20%20if%20(num%20%3E%3D%20str.length)%20%7B%0A%20%20%20%20return%20(str)%3B%0A%20%20%7D%20else%20if%20(num%20%3C%3D%203)%20%7B%20%20%0A%20%20%20%20%20%20%20str%20%3D%20str.substr(0%2C%20num)%3B%0A%20%20%20%20%20%20%20str%20%3D%20%20str.concat(%22...%22)%3B%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20str%20%3D%20str.substr(0%2C%20num-3)%3B%0A%20%20%20%20%20%20%20str%20%3D%20str.concat('...')%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20(str)%3B%0A%7D%0A%0AtruncateString(%22A-tisket%22%2C%203)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

my code passes just find, it's just these included tests aren't displaying the value of _num_ correctly.

```
truncateString("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length) should return "A-tisket a-tasket A green and yellow basket".
```
```
truncateString("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length + 2) should return "A-tisket a-tasket A green and yellow basket".
```

My code:
```javascript
function truncateString(str, num) {
  
  // if num > str.lenght, return str
  // else if num <= 3
  //   truncate(str-num).concat('...'), return str
  // else, truncate str starting at 0 index to num-3 index
  // str.concat("..."), return str
  
  //assuming equal to as well since
  //  there would be no reason to truncate str if
  //  the correct num of char can be shouwn
  //  w/o the elipses
  
  if (num >= str.length) {
    return (str);
  } else if (num <= 3) {  
       str = str.substr(0, num);
       str =  str.concat("...");  
  } else {
       str = str.substr(0, num-3);
       str = str.concat('...');
  }
  
  return (str);
}

truncateString("A-tisket", 3);
```

**Comment by erictleung** [comment]
@yuens1002 thanks for the feedback. Can you elaborate on what you mean by the value of num doesn't display correctly? A screenshot of what you are seeing would be great.

**Comment by yuens1002** [comment]
test cases 3 &4 are showing his for the value of num

```
 "A-tisket a-tasket A green and yellow basket".length)
```

instead of a whole number like the rest of the test cases

**Comment by erictleung** [comment]
@yuens1002 those were on purpose and valid JavaScript. So there isn't any problem with this challenge. Closing this issue as there is nothing wrong with the challenge. Happy coding!

**Comment by sidrai97** [comment]
function truncateString(str, num) 
{  
  if(str.length > num)
    {     
      if(num>=3)
        {
          str=str.slice(0,num-3);      
        }
      else
        {
          str=str.slice(0,num);      
        }    
      str=str.concat("...");
    }
  return str;
}
