### ISSUE TITLE
Chunky Monkey: I'm returning the given solution but not solving the problem

### ISSUE THREAD

**Issue by gonzalezi2** [FreeCodeCamp/FreeCodeCamp#9058]
#### Chunky Monkey

https://www.freecodecamp.com/challenges/chunky-monkey

#### Issue Description

The code I've written correctly follows the steps as described in the problem and I'm returning the correct solution to each instance. However, none of the instances are being checked off as correct.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
var segments = [];
var newArray = [];
function chunkArrayInGroups(arr, size) {
  // Break it up.
  for (var i = 0; i < arr.length; i += size) {
    segments = arr.slice(i, i+size);
    newArray.push(segments);
    console.log(newArray);
  }
  return newArray;
}


chunkArrayInGroups(["a", "b", "c", "d"], 2);
```

**Comment by erictleung** [comment]
@gonzalezi2 your `segments` and `newArray` variables are in the global scope, which will keep state after each function call used in the tests. Locally scope them (i.e. put them within your function) and it should work. Happy coding!

**Comment by gonzalezi2** [comment]
Wow. That's all it took. Thank you so much!!

One question: Why would it return the correct answer though? If I had gotten an error I would know to change it but without an error, and a correct answer, it's hard to figure out what the problem is.

**Comment by erictleung** [comment]
@gonzalezi2 when you run it just once with the `Run Tests` button, it runs the entire code in your editor. However, the tests just run the function you've created and so the variables you've initialized in the global scope change with each test. Yeah, I've seen many people confused about it. Maybe we could add in a note somewhere early on in the curriculum about not using global scoped variables or something.

**Comment by gonzalezi2** [comment]
yeah that would make it more clear. I still have trouble with it at times because sometimes it is necessary to create it globally because if I create a local variable and try to call it outside I get the "out of scope" error. So yeah some clarification on that would go a long way. Thanks for your help!

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
