### ISSUE TITLE
Exact Change Issue with Numbers and Strings for the amount returned

### ISSUE THREAD

**Issue by k-drive** [FreeCodeCamp/FreeCodeCamp#9059]
#### Challenge Name

Exact Change

Hello. Having worked in the software development biz for eight years I thought I would turn this issue. When I was producing software or testing software I would often take such an issue to the designer I was coding for, or to the programmer I was testing for to get an answer. This post is the equivalent of that. I am presenting you with the issue so that you can decide on what to do with it.
#### Issue Description

The project description/requirements show that the returned dollar amount should have two decimal places even if they are trailing zeros. That is only possible using toFixed(2) method which converts the value to a string for display purposes.

The solutions in the test data show numbers being returned, that is, values without quotes. 

From searching various sources, this isn't possible with JavaScript. 
(Please let me know if you have a way of doing so. I should add that I did enjoy searching for a solution for this on various web pages and forums. I think I learned a lot about toFixed() and Math.round(), etc.)

Examples of what can be returned:
Either a string with quotes can be returned 
["QUARTER", "0.50"]
...or a number without trailing zeros can be returned.
["QUARTER", 0.5]

My solution which returned a string with two decimal places using toFixed(2) was rejected. I am assuming that it is because it had quotes.
My solution with a number with no trailing zeros was accepted. But, this didn't match the test data solution ("should return"). So, I was a bit confused even though I had supposedly completed the project successfully.

See my screenshot. I outlined the solution in the test data and what was accepted as the correct answer in the small black screen with white characters. They don't match. As a programming trying to use the supplied information/requirements to produce results, this is just not good.

I think the test data with solutions should be changed to show no trailing decimal zeros, 
or the solution should be changed to return a string with quotes with trailing decimal zeros.

Thanks.
Have a good day.
K-Drive`
#### Screenshot

![screenshot_for_report](https://cloud.githubusercontent.com/assets/16052055/15944153/4294f158-2e5a-11e6-8102-763c39a35433.png)

**Comment by valterlima** [comment]
It's a subtle issue, but I agree with you. The other test cases have the same problem.

The test cases are [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/master/seed/challenges/01-front-end-development-certification/advanced-bonfires.json#L151) between the lines 147 and 154, but they are written in the proper way, with 2 leading zeros like: ["QUARTER", 0.50].

`"assert.deepEqual(checkCashRegister(19.50, 20.00, [[\"PENNY\", 1.01], [\"NICKEL\", 2.05], [\"DIME\", 3.10], [\"QUARTER\", 4.25], [\"ONE\", 90.00], [\"FIVE\", 55.00], [\"TEN\", 20.00], [\"TWENTY\", 60.00], [\"ONE HUNDRED\", 100.00]]), [[\"QUARTER\", 0.50]], 'message: <code>checkCashRegister(19.50, 20.00, [[\"PENNY\", 1.01], [\"NICKEL\", 2.05], [\"DIME\", 3.10], [\"QUARTER\", 4.25], [\"ONE\", 90.00], [\"FIVE\", 55.00], [\"TEN\", 20.00], [\"TWENTY\", 60.00], [\"ONE HUNDRED\", 100.00]])</code> should return <code>[[\"QUARTER\", 0.50]]</code>.');",`

It looks like something in the middle is trimming the zeros.

**Comment by raisedadead** [comment]
@k-drive @valterlima apologies for responding to the issue with so much delay, and thank's for reporting. Bumping up for assistance from @FreeCodeCamp/issue-moderators

**Comment by AdventureBear** [comment]
Interesting issue, I found the test cases confusing as well but when my answer of  .5 passed instead of .50, I didn't think much more about it.

**Comment by kiraPez** [comment]
Hi, I'm experienceing the same problem as well. I usually do the work on codepen, and on codepen the numbers are also being trimmed (60.00 -> 60).

Is there any update on the question?

**Comment by k-drive** [comment]
kiraPez:  Submit your code returning the trimmed value. It will be accepted and the project will be completed. (See my text starting with "My solution...").

**Comment by kiraPez** [comment]
Hey k-drive. Thanks for the response. It didn't directly help me, because I had done that before, but your comment made me realize that it has to be [["QUARTER", 0.5]], not ["QUARTER", 0.5]. Thanks for replying.

**Comment by raisedadead** [comment]
Hi all, once again apologies into coming back to this topic, I am not an expert but to achieve the desired result you could try something like [Number.prototype.toPrecision()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Number/toPrecision)

We do accept the challenge with the zeros stripped (this is done natively by the browser when JavaScript executes), however you could achieve the necessary with something like this:
```js
> x = 50
> 50
> x.toPrecision(4)
> "50.00"
```

**Comment by raisedadead** [comment]
We are really limited by the infrastructure, while this is not a huge issue IMHO, I understand that coming from a strictly typed and interpreted language can be bit tough to understand how liberal JavaScript can be. (Trust me I have been doing C++ since a decade only to switch to JS now)

Nevertheless we are open to suggestion how this can be clarified more, but on that note I feel that this challenge is by far the one of the most algorithmic-ally challenging ones in the curriculum, hence adding a more complexity by enforcing a certain output type may not be good at this point.

Please let us know how to improve this further, should you feel the need.

Thanks.
