### ISSUE TITLE
Disappearing to-do list

### ISSUE THREAD

**Issue by klee0589** [FreeCodeCamp/freecodecamp#906]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

As i continue down the codes the new to-do list for the radio buttons disappear.
I think it might be a glitch.

**Comment by LumenTeun** [comment]
What do you mean by "as i continue down the codes"? Could you post the code that makes the buttons disappear?

**Comment by BerkeleyTrue** [comment]
Closing do to inactivity
