### ISSUE TITLE
Extra gap in button group on iPhone

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9060]
#### Issue Description

When viewing HTML, Bootstrap and jQuery challenges on an iPhone, there is a gap in the button group containing the 'reset' 'help' and 'bug' buttons. 

The gap is the same width as the other three buttons. 

The gap is between the help and bug buttons.

**Comment by erictleung** [comment]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/2754821/15949399/03b8c6f6-2e5c-11e6-8c23-2eabe2956321.png)

When the width of the screen gets larger than 770 pixels, it'll switch from an entire closed gap block of buttons to one with a block.

cc/ @hallaathrad
