### ISSUE TITLE
I don't play Golf, why don't you REALLY explain the task?

### ISSUE THREAD

**Issue by orenyny** [FreeCodeCamp/FreeCodeCamp#9062]
#### Challenge Name
Golf

https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%204)%3B%0A

#### Issue Description

Your description for such a task is too minimal and you assume that students will know what you mean.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@orenyny how do you suggest changing the instructions? I feel that in conjunction with reading the instructions and table (which I admit by themselves, *may* be unclear on what you need to do), along with the tests themselves gives enough information to the user on what to do.

I also feel that the instructions give just enough detail on what `par` and `strokes` mean in a golf context to complete the challenge. The Wiki page linked is quite overwhelming but just that paragraph is enough.

**Comment by Pasayadaan** [comment]
Though I did not find very difficult to understand but it may be easier if we reword as follows
"In the game of golf each hole has a par **(score), meaning** the average number of strokes needed to sink the ball **in a hole to complete the play**. Depending on how far above or below **the** par your strokes are, there is a different nickname." (Inspiration - Wiki)
Compared to the original 
"In the game of golf each hole has a par for the average number of strokes needed to sink the ball. Depending on how far above or below par your strokes are, there is a different nickname."

**Comment by orenyny** [comment]
This looks better to me. Thank you!

Please note that much simpler or smaller tasks had more details on what
needs to be done than this task...
I just suggest that you don't count in someone being familiar with Golf or
its jargon.

Thanks,
Oren

**Comment by Pasayadaan** [comment]
So if the change is acceptable it needs to be done in
seed/challenges/01-front-end-development-certification/basic-javascript.json 
Replace the following text
"In the game of golf each hole has a par for the average number of strokes needed to sink the ball. Depending on how far above or below par your strokes are, there is a different nickname."

By new text
"In the game of golf each hole has a par (score), meaning the average number of strokes needed to sink the ball in a hole to complete the play. Depending on how far above or below the par your strokes are, there is a different nickname."

**Comment by erictleung** [comment]
@orenyny @Pasayadaan thanks for the feedback. Here's my small edit of @Pasayadaan suggestion.

> In the game of golf, each hole has a `par`, meaning the average number of `strokes` **a golfer is expected to make in order** to sink the ball in a hole to complete the play. Depending on how far above or below `par` your strokes are, there is a different nickname.

I removed the `the` in

> ...above or below **the** part...

because you don't need it. Reading the Wiki article uses this way of talking about par.
