### ISSUE TITLE
Can't pass adding padding to Each of a Element

### ISSUE THREAD

**Issue by SaloneKay** [FreeCodeCamp/FreeCodeCamp#9066]
#### Add Different Padding to Each Side of an Element

<img width="605" alt="screen shot 2016-06-10 at 1 52 13 am" src="https://cloud.githubusercontent.com/assets/19763142/15955249/fc01061a-2ead-11e6-9717-c8aba40eb4c3.png">

#### Issue Description

I input the code correctly (seemingly) but its not responding. I assume a bug or something
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

I can't seem to pass this challenge. Help is appreciated!

**Comment by chunsli** [comment]
Seems like you are missing some semi-colons for the green box?

**Comment by SaloneKay** [comment]
Oh wow, thanks! Can't believe I missed that

**Comment by dwd2010** [comment]
@SaloneKay 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help.

Happy Coding!
