### ISSUE TITLE
it does not accept the font size .. zoom is at 100%

### ISSUE THREAD

**Issue by freecodecamp2** [FreeCodeCamp/FreeCodeCamp#9067]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%7B%0A%20%20%20%20font-size%3D%2016%20px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }
  p{
    font-size= 16 px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

#

**Comment by chunsli** [comment]
hey you were pretty close

```
<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>
```

**Comment by atjonathan** [comment]
@chunsli is correct and thanks!

Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help in future. Happy Coding!

**Comment by Numbers13** [comment]
i have a similar issue .. here is my code

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16x;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Numbers13** [comment]
```<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16x;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>```

**Comment by chunsli** [comment]
you are missing the p in px.

  p {
    font-size: 16px;
  }

**Comment by yasminchino** [comment]
Hi! For some reason when I click on "Run tests" nothing happens... I've tried changing a few elements of my code and I've checked the zoom on my browser etc and the same thing keeps happening :/ 
Could anyone possibly offer some advice please? 
![screen shot 2016-06-14 at 5 47 28 pm](https://cloud.githubusercontent.com/assets/19929709/16045253/af7109a4-3258-11e6-9e27-bc403c4c4228.png)

**Comment by jsgaonac** [comment]
@yasminchino Between the style tags, change the .h for p, without leading dot.

**Comment by aorborc** [comment]
Whats the problem? Also, how to skip html and css?
<img width="724" alt="screen shot 2016-06-17 at 2 33 51 am" src="https://cloud.githubusercontent.com/assets/4959806/16146634/ff1948f4-3433-11e6-840b-55dd975725a4.png">
