### ISSUE TITLE
Access Array Data with Indexes problem needs a little tweak

### ISSUE THREAD

**Issue by dimahali** [FreeCodeCamp/FreeCodeCamp#9068]
#### Challenge Name

Access Array Data with Indexes

https://www.freecodecamp.com/challenges/access-array-data-with-indexes#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20ourData%20%3D%20ourArray%5B0%5D%3B%20%2F%2F%20equals%201%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A

Instructions
Create a variable called myData and set it to equal the first value of myArray.

#### Issue Description

It is not an issue rather we can get solution by not following steps

**here is the wrong solution which is accepted**

```
var ourArray = [1,2,3];
var ourData = ourArray[0]; // equals 1

// Setup
var myArray = [1,2,3];

// Only change code below this line.
var myData = 1;
```

**solution to be accepted**
```

var ourArray = [1,2,3];
var ourData = ourArray[0]; // equals 1

// Setup
var myArray = [1,2,3];

// Only change code below this line.
var myData = myArray[0];
```

**Comment by atjonathan** [comment]
@dimahali thanks for catching this! We should update the tests so this incorrect solution isn't allowed.

**Comment by jarrydfillmore** [comment]
+1!
