### ISSUE TITLE
type in the example

### ISSUE THREAD

**Issue by bigos** [FreeCodeCamp/FreeCodeCamp#9069]
Challenge [Sort Arrays with sort](https://www.freecodecamp.com/challenges/sort-arrays-with-sort#?solution=%0Avar%20array%20%3D%20%5B1%2C%2012%2C%2021%2C%202%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Aarray.sort(function(x%2Cy)%7Breturn%20x%20%3C%20y%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var array = [1, 12, 21, 2];

// Only change code below this line.

array.sort(function(x,y){return x < y;});

```

example says return a MINUS b

**Comment by erictleung** [comment]
@bigos although your code does sort correctly, the `a - b` is still a valid way to sort an array. I would suggest looking at the [MDN page on the `sort` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). Happy coding!
