### ISSUE TITLE
Hi everyone this does not produce 1 backslash but 2.

### ISSUE THREAD

**Issue by ThembinkosiZwane** [FreeCodeCamp/FreeCodeCamp#9070]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22%5C%5C%22%3B%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "\\";





```

**Comment by ThembinkosiZwane** [comment]
When I use 1 backslash instead it escapes the double quotes.

**Comment by erictleung** [comment]
@ThembinkosiZwane the little box of the left, supposedly showing some output, in this case tries to keep the escape characters in there as well. This challenge is about escape characters so we wanted to show that they exist. We have a proposed changed in #8554 to make it more clear on what is going on. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
