### ISSUE TITLE
Bug in Challenge "Seek And Destroy"

### ISSUE THREAD

**Issue by jaytsecan** [FreeCodeCamp/FreeCodeCamp#9072]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=%0Afunction%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20var%20returnArr%20%3D%20arguments%5B0%5D%3B%0A%20%20var%20args%20%3D%20Array.from(arguments).slice(1)%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20args.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20returnArr%20%3D%20returnArr.filter(function%20(value)%20%7B%20return%20value%20!%3D%3D%20this%3B%7D%2C%20args%5Bi%5D)%3B%0A%20%20%7D%0A%20%20return%20returnArr%3B%0A%7D%0A%0Adestroyer(%5B%22tree%22%2C%20%22hamburger%22%2C%2053%5D%2C%20%22tree%22%2C%2053)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows; Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function destroyer(arr) {
  // Remove all the values
  var returnArr = arguments[0];
  var args = Array.from(arguments).slice(1);
  for (var i = 0; i < args.length; i++) {
    returnArr = returnArr.filter(function (value) { return value !== this;}, args[i]);
  }
  return returnArr;
}

destroyer(["tree", "hamburger", 53], "tree", 53);

```
Note: My code works for all the tests (when I test it manually), but when I click on the "Run Tests (ctrl+enter)" button, all the tests fail.

I know this code works because I tested it manually with exactly all the tests specified in the left column.

Hence, it won't let me submit my solution.

**Comment by jaytsecan** [comment]
There is a bug in the challenge, but it is in the display of the output.
When I checked my code in "https://repl.it/", it did not work.
So there is something wrong with my code.
BUT then the output shown in the challenge is wrong.

**Comment by erictleung** [comment]
@jaytsecan since you are using `this` keyword, the scope ([Lexical Scoping](https://developer.mozilla.org/en/docs/Web/JavaScript/Closures)) changes while evaluating the tests, and the behavior is unpredictable depending on the browser.

Using the `'use strict';` within your function, as shown below, should allow you to pass the challenge.

```js
function destroyer(arr) {
'use strict'; // <-- tells the browser to bind 'this' object to the functions scope
...
...
}
```

If you have any questions about this kind of lexical scoping, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
