### ISSUE TITLE
Instructions do not match expected results

### ISSUE THREAD

**Issue by overbaymd** [FreeCodeCamp/FreeCodeCamp#9073]
instructions ask for different code then what is checked for submission.  Just FYI.

Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0Aa%20%3D%206%2C%20b%20%3D%2015%2C%20c%20%3D%20%22I%20am%20a%20String!%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";
a = 6, b = 15, c = "I am a String!";

```

**Comment by erictleung** [comment]
@overbaymd if you look in the editor, you can see a line `Do not change code below this line`, indicating where you make your changes. Although your code does pass, your changes should have been made at the beginning of the editor.

But can you be more specific on what instructions you were referring to?

**Comment by robjloranger** [comment]
Actually the code below the line is the default example. The last line is displaying what the variable should be after you initialize them to the values explained in the description.

@overbaymd The code is checking for what the variables will become once you have initialized them. After which they are operated on to give the values in the last line.

**Comment by overbaymd** [comment]
Ah, I see.  Am just rushing thru as I use to do a lot of javascript.  User error on my part ;)
