### ISSUE TITLE
Test result for Prefilter JSON challenge

### ISSUE THREAD

**Issue by heltucosta** [FreeCodeCamp/FreeCodeCamp#9080]
#### Challenge Name

Prefilter JSON

#### Issue Description

You are supposed to exclude the objects which have an id of 1 from the json you acquired and show the images of the remaining ones. If you put any value to your filter, the test will give a success message, even if you use id's that don't exist on the JSON Object.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 50.0.2661.102 (64-bit)
* Operating System: OSX El Capitan
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

``` 
json = json.filter(function(val){
          return (val.id === -1);
        });
```

#### Screenshot

![screen shot 2016-06-10 at 5 18 57 pm 2](https://cloud.githubusercontent.com/assets/18036894/15977504/8449d868-2f2f-11e6-85a1-8e7d60e56c9b.png)

**Comment by choiceman** [comment]
On Jun 10, 2016 1:22 PM, "Helton Costa" <notifications@github.com> wrote:
>
> Challenge Name
>
> Prefilter JSON
>
> Issue Description
>
> You are supposed to exclude the objects which have an id of 1 from the
json you acquired and show the images of the remaining ones. If you put any
value to your filter, the test will give a success message, even if you use
id's that don't exist on the JSON Object.

**Comment by Bouncey** [comment]
The tests for this challenge only assert that `filter` is in the code. You can pass the test with just
```
       // Only change code below this line.
        
        filter
        
        // Only change code above this line.
```
The tests require a more robust regex

**Comment by heltucosta** [comment]
Yes, but even if you use an id that don't exist on the JSON object where you will get no image back, you will still be able to pass the challenge without seeing it work properly

**Comment by Bouncey** [comment]
@heltucosta

I was just expanding on your issue and pointing out a floor in the challenge tests. The tests were only checking that the word 'filter' was in the campers code, without any context as to the rest of the code. 

I have submitted a PR to rectify the issue. 

Thank you for reporting the bug.

**Comment by alexalexson143** [comment]
14Dec16 - Bug still exists.
