### ISSUE TITLE
Setting up FreeCodeCamp for Windows

### ISSUE THREAD

**Issue by Pasayadaan** [FreeCodeCamp/FreeCodeCamp#9085]
The instruction to create .env file based on the sample.env file is missing from the following page:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Fork-Windows
Though it has been mentioned in CONTRIBUTING.md it may be nice to have on the above page also.

**Comment by marlyna93** [comment]
Guys, can I have this one?
I would like to do this. 
Is there any further information, what I should follow?

**Comment by atjonathan** [comment]
@marlyna93, sure :smile: 

Checkout our current [FreeCodeCamp Contributors Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) for more information.
If you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by marlyna93** [comment]
@atjonathan 

Oh, thank you!
Well, I followed the instructions in the Contributors Guide, and started to host the application on my local computer. It works, but I don't really find where can I put the .env file based on the [link above](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Fork-Windows).


I could edit the CONTRIBUTING.md, but I couldn't see or edit the wiki pages on my fork repo.

I already  asked it in the chatroom, but I haven't got any answers.

Can you please help me, what am I doing wrong?

**Comment by pdurbin** [comment]
@marlyna93 it looks like you'll need to fork the wiki, make a commit to your fork, and then make a pull request: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Central#contribution-guides

**Comment by marlyna93** [comment]
Yeah, you're right! I missed that point, thank you for your help!
I do appreciate it!

**Comment by pdurbin** [comment]
@marlyna93 I see you've make a number of commits in your fork of the wiki at https://github.com/marlyna93/FreeCodeCamp/wiki/FreeCodeCamp-Fork-Windows/_history but I'm not sure how you are supposed to make a pull request upstream.

**Comment by pdurbin** [comment]
Oh, I see, there's a separate repo for the wiki at https://github.com/FreeCodeCamp/wiki and @marlyna93 has forked it at https://github.com/marlyna93/wiki and will make a normal pull request. Makes sense now. I hadn't looked at https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Contribute-Fork closely enough.

**Comment by pdurbin** [comment]
@marlyna93 now you just need to make a pull request from https://github.com/marlyna93/wiki/tree/patch-1
