### ISSUE TITLE
Use Conditional Logic with If Statements

### ISSUE THREAD

**Issue by Mzahoor** [FreeCodeCamp/FreeCodeCamp#9087]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunction(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20that%20was%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20that%20was%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0A%0Afunction%20trueOrFalse(wasThatTrue)%20%7B%0A%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0Aif%20(wasThatTrue)%20%7B%20%0A%20%20return%20%22%20Yes%2C%20that%20was%20true%22%3B%0A%7D%0A%0A%20%20return%20%22No%2C%20that%20was%20false%22%3B%0A%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtrueOrFalse(true)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourFunction(isItTrue) {
  if (isItTrue) { 
    return "Yes, that was true";
  }
  return "No, that was false";
}

// Setup

function trueOrFalse(wasThatTrue) {


  // Only change code below this line.
if (wasThatTrue) { 
  return " Yes, that was true";
}

  return "No, that was false";
}
  // Only change code above this line.


// Change this value to test
trueOrFalse(true);

```

**Comment by BKinahan** [comment]
`trueOrFalse(true)` should return `"Yes, that was true"`. You return `" Yes, that was true"` with an extra space at the start of the string.

Please use the [Help chat](https://gitter.im/FreeCodeCamp/Help) for help with coding; issues are for reporting bugs or problems with the website. Happy coding!

**Comment by atjonathan** [comment]
Thanks @BKinahan :tada:

**Comment by qjawe** [comment]
// Example
function ourFunction(isItTrue) {
  if (isItTrue) { 
    return "Yes, that was true";
  }
  return "No, that was false";
}

// Setup

function trueOrFalse(wasThatTrue) {


  // Only change code below this line.
if (wasThatTrue) { 
  return "Yes, that was true";
}

  return "No, that was false";
}
  // Only change code above this line.


// Change this value to test
trueOrFalse(true);


Very useful on this one any human error or the typo errors..

**Comment by texas2010** [comment]
@qjawe 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
