### ISSUE TITLE
Change of Title for Mutations Challenge

### ISSUE THREAD

**Issue by byteknacker** [FreeCodeCamp/FreeCodeCamp#9088]
I have a suggestion for a new and more semantic title for Challenge [Mutations](https://www.freecodecamp.com/challenges/mutations#?solution=%0Afunction%20mutation(arr)%20%7B%0A%20%20var%20counter%20%3D%200%3B%0A%20%20arr%5B0%5D%20%3D%20arr%5B0%5D.toLowerCase()%3B%0A%20%20arr%5B1%5D%20%3D%20arr%5B1%5D.toLowerCase()%3B%0A%20%20var%20splitArray%20%3D%20arr%5B1%5D.split(%22%22)%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20splitArray.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(arr%5B0%5D.indexOf(splitArray%5Bi%5D)%20!%3D%3D%20-1)%20%7B%0A%20%20%20%20%20%20counter%2B%2B%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20if%20(counter%20%3D%3D%20splitArray.length)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B%0A).

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My Suggestion:

This task is a rather mathematical one borrowed from set theory. You are supposed to find out whether or not the second element in the ```arr``` array is a subset of the first element of ```arr```. A more appropriate title should not be mutation, since this has its own mathematical meaning within the area of combinatorics and is rather unrelated to basic set theory. My suggested title is:

"Confirm Subset of an Array's Element"

My code:
```javascript

function mutation(arr) {
  var counter = 0;
  arr[0] = arr[0].toLowerCase();
  arr[1] = arr[1].toLowerCase();
  var splitArray = arr[1].split("");
  for (var i = 0; i < splitArray.length; i++) {
    if (arr[0].indexOf(splitArray[i]) !== -1) {
      counter++;
    }
  }
  
  if (counter == splitArray.length) {
    return true;
  } else {
    return false;
  }
}

mutation(["hello", "hey"]);

```

**Comment by erictleung** [comment]
@byteknacker although I agree that semantically your suggestion does describe the challenge, I don't think there needs to be a change in the title. The title name, IMO, comes from being able to "mutate" the first string into the second one by using only the letters in the first string. Plus, these challenge names give a friendlier feel to them, rather than a colder feel of computer science terms.

Side note, I haven't heard of mutations being used in combinatorics or set theory. Don't they use terms such as "permutations" and "combinations"? But I guess the word "mutation" is a substring of "permutations" 😆 

cc/ @FreeCodeCamp/issue-moderators

**Comment by byteknacker** [comment]
@erictleung, yeah you are right, I was thinking of permutations.

**Comment by erictleung** [comment]
@byteknacker no worries. Thanks again for your sincere feedback and suggestion for FreeCodeCamp. If you have any other constructive criticisms of the site, let us know. In the meantime, happy coding!

**Comment by Myst** [comment]
Sorry, but I think you should edit your code, since you are giving the answer to this test and the idea is that campers found a way to the answer.
