### ISSUE TITLE
点击运行测试无响应

### ISSUE THREAD

**Issue by sblig** [FreeCodeCamp/FreeCodeCamp#9089]
Challenge [Use a CSS Class to Style an Element](https://freecodecamp.cn/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%7B%0A%20%20%20%20color%3Ared%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%0A%3Cp%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E5%8F%AF%E7%8C%AB%E5%8F%AF%E7%8B%97%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text{
    color:red
  }
</style>

<h2 class="red-text">我家的猫咪</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，可猫可狗。</p>

```

**Comment by Bouncey** [comment]
有一个在你的CSS错误
句法。请参阅有关定义CSS属性的说明。

有提示，以需要什么，根据运行测试按钮

这是使用谷歌翻译，我希望这是有道理的。

~~~~~~~~~~~~~~~~~~
Issue Title: Run Tests button is unresponsive.

There is an error in you CSS syntax. Please review the instructions on defining CSS properties.

There are test pass/fail icons under the Run Tests button. They provide hints as to what is required.

This was translated using Google, I hope it makes sense.

**Comment by crashuniverse** [comment]
** Click Run Test unresponsive **

I see no problem with challenge, and underlying logic to test progress.

I'm going to answer it in english and then translate to Chinese simplified using Translate.

`.red-text{
    color:red
  }`
This code is technically correct, should pass the test. However it is very important to write correct syntax all the time. The only problem with this line is it doesn't have a `;` semicolon in end. This may look trivial, but when the code becomes long, things like this can be very hard to find out and may cause bigger problems. I hope you fix this in your solution and make progress with challenge.

Chinese (can't do better - sorry):

**点击运行测试反应迟钝**

我看到的挑战没有问题的，背后的逻辑测试进度。

我要回答的英文，然后翻译成中国使用翻译简化。

`.red-text{
    color:red
  }`
这个代码在技术上是正确，应该通过测试。然而，它写出正确的语法所有的时间是非常重要的。与此行唯一的问题是它没有一个' ;在终端`分号。这可能看起来微不足道，但是当码变长了，这样的事情可能很难找出并可能导致更大的问题。我希望你在你的解决方案解决这一问题，并与挑战的进展。

**Comment by alistermada** [comment]
The link posted above leads to [freecodecamp.cn](https://freecodecamp.cn/) instead of [freecodecamp.com](https://www.freecodecamp.com/). I don't think that site affiliated with Free Code Camp. As far as I know, there isn't a way to change language in FCC yet. FCC's code is open source so it wouldn't be too difficult to make a clone.

**Comment by erictleung** [comment]
@sblig 你好和谢谢你的问题。我的中文不太好。但是，我可以帮你一点。

首先，这是英文的FreeCodeCamp网站。我们不能给同中国网站获得帮助。你的问题是，你没有`;`在你的CSS。

今后，请到[中国的网站](https://github.com/huluoyang/freecodecamp.cn)，使问题。我们不能帮你。 我希望你明白。 在未来，[中国聊天室](https://gitter.im/FreeCodeCamp/chinese)可以帮助你。谢谢和编程快乐！

**Comment by huluoyang** [comment]
@sblig  抱歉，issue链接没有指向中文社区，已更正。
多谢楼上各位的解答，此问题系缺少分号导致。
正确如下：
`  .red-text{
    color:red;
  }
`
