### ISSUE TITLE
Apparently one of the challenges has an undefined condition.

### ISSUE THREAD

**Issue by lewisje** [FreeCodeCamp/freecodecamp#909]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

![freecodecamp_error0](https://cloud.githubusercontent.com/assets/4865237/8142511/c8638776-114c-11e5-96c7-de4939608dfb.png)

1. Go through all of the waypoints up to this one.

2. The second condition says `Cannot read property 'match' of undefined.`

3. However, when you finish the waypoint, the second success condition will say, accurately, `Set the value of your placeholder attribute to "cat photo URL".`

**Comment by LumenTeun** [comment]
This is sort of the same as #899, read my comment there.

**Comment by RahulHP** [comment]
Signing in to say that this bug still exists.

**Comment by BerkeleyTrue** [comment]
fixed
