### ISSUE TITLE
Errors with "Getting Started" - setting up local environment

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#9091]
#### Private Environment Variables (API Keys)
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#getting-started

#### Issue Description
I am trying to setup my environment to be able to work on and contribute to FCC issues. I am following the steps listed out at the [Contributing page](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#getting-started). 

However, I'm stuck at the step where it says - 
```
# Create a copy of the "sample.env" and name it as ".env".
# Populate it with the necessary API keys and secrets:
cp sample.env .env
```
For me, this returns - 
```
Manish-MacBook-Pro:FreeCodeCamp manishgiri$ cp sample.env .env
cp: sample.env: No such file or directory
```
I asked in the Wiki help room to see if the sample.env file was located somewhere else, but I was told it's in the main directory itself, and clearly it's not there. 

When I try to run the command `npm run only-once`, I get errors there as well - 
```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "only-once"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 only-once: `npm run create-rev && echo '
npm ERR! 
npm ERR! seeding database
npm ERR! 
npm ERR! ' && node seed && echo '
npm ERR! 
npm ERR! Seeding Completed
npm ERR! 
npm ERR! '`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 only-once script 'npm run create-rev && echo '
npm ERR! 
npm ERR! seeding database
npm ERR! 
npm ERR! ' && node seed && echo '
npm ERR! 
npm ERR! Seeding Completed
npm ERR! 
npm ERR! ''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run create-rev && echo '
npm ERR! 
npm ERR! seeding database
npm ERR! 
npm ERR! ' && node seed && echo '
npm ERR! 
npm ERR! Seeding Completed
npm ERR! 
npm ERR! '
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/manishgiri/GitHub/mean/FreeCodeCamp/npm-debug.log
```
This is a snippet of the terminal window when I was cloning the FCC repo - 
```
Checking connectivity... done.
Manish-MacBook-Pro:mean manishgiri$ ls
FreeCodeCamp
Manish-MacBook-Pro:mean manishgiri$ cd FreeCodeCamp/
Manish-MacBook-Pro:FreeCodeCamp manishgiri$ ls
CONTRIBUTING.md		client			package.json		server
LICENSE.md		common			pm2Start.js		test
README.md		config			public			webpack.config.js
bower.json		gulpfile.js		seed			webpack.config.node.js
Manish-MacBook-Pro:FreeCodeCamp manishgiri$ git remote add upstream https://github.com/FreeCodeCamp/FreeCodeCamp.git
Manish-MacBook-Pro:FreeCodeCamp manishgiri$ git status
On branch staging
Your branch is up-to-date with 'origin/staging'.
nothing to commit, working directory clean
Manish-MacBook-Pro:FreeCodeCamp manishgiri$ 
```

I was also told in the wiki help room that it might be an issue with my cloning of the FCC forked repo. I had cloned this several weeks back using the github desktop app, so I was advised to delete everything and reclone it. Did that yesterday evening with the command line, but doesn't seem to help much. 

I'm really eager to be able to contribute to the community, and would appreciate any help with this problem. Thanks!

**Comment by Rafase282** [comment]
The problem was that he was cloning his fork which was outdated. I have help him setup his fork to keep it in sync following our wiki guides and explained the process and now everything is working as it should.
