### ISSUE TITLE
Missing apostrophe in fourth paragraph of 'Logical Order in If Else Statements'

### ISSUE THREAD

**Issue by kishba** [FreeCodeCamp/FreeCodeCamp#9097]
Challenge [Logical Order in If Else Statements](https://www.freecodecamp.com/challenges/logical-order-in-if-else-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/602.1.35 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.4</code>.

The fourth paragraph is missing an apostrophe for "here is":

> Heres the first:

It should read:

> Here's the first:

**Comment by atjonathan** [comment]
> **To contributor:**
Change this line of code: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3283

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by Trupal24** [comment]
function orderMyLogic(val) {
  if (val < 10) {
    return "Less than 10";
  } else if (val < 5) {
    return "Less than 5";
  } else {
    return "Greater than or equal to 10";
  }
}

// Change this value to test
orderMyLogic(7);
orderMyLogic(4) should return "Less than 5".
Help me to solve this?

**Comment by vekatobias** [comment]
I resolved that challengue:

function orderMyLogic(val) {
  if (val < 5) {
    return "Less than 5";
  } else if (val < 10) {
    return "Less than 10";
  } else {
    return "Greater than or equal to 10";
  }
}

// Change this value to test
orderMyLogic(10);

**Comment by texas2010** [comment]
@vekatobias 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
