### ISSUE TITLE
Basic HTML/CSS Bug

### ISSUE THREAD

**Issue by theberbie** [FreeCodeCamp/freecodecamp#910]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**
There's a chance I might have skipped something, but basically, it says to wrap `<a>` within the `<p>`

I skipped to the next level and pasted the "correct" code but it still said I wasn't wrapping `<a>` within the `<p>`
Please forgive me if I'm wrong and pretend I brought cookies for everyone 
![screen shot 2015-06-12 at 7 31 16 pm](https://cloud.githubusercontent.com/assets/9112209/8142680/9dc03ec8-1139-11e5-8429-c84aedeb76ef.png)

**Comment by LumenTeun** [comment]
Please wrap your code in ``` so we can see it.

**Comment by BerkeleyTrue** [comment]
I've gone ahead and wrapped the code so that it is visible.

**Comment by ahstro** [comment]
I don't think this is an issue anymore? Close?

**Comment by benmcmahon100** [comment]
I'm happy this works! Closing for now.
