### ISSUE TITLE
Text-editor overflow hidden on iPad

### ISSUE THREAD

**Issue by ButsAndCats** [FreeCodeCamp/FreeCodeCamp#9104]
#### Challenge name: Turn an Image into a link

https://www.freecodecamp.com/challenges/turn-an-image-into-a-link

#### Issue Description

I am using an iPad.
The bottom of the text editor and content is cut-off.
The text editor does not scale with the amount of text it contains. Nor does it scroll. This makes it impossible to edit the below-the-fold content. Although this is an issue on other challenges the above challenge link and name is a good example. This is the first challenge that this bug stops you from completing the challenge.

Please see below device information to reproduce issue.
#### Browser Information

* Browser Name, Version: Safari
* Operating System: iOS 9.3.2
* Mobile, Desktop, or Tablet: iPad 2

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/930712/15989999/8e794d94-30cb-11e6-95e6-a64674a1560b.jpg)

**Comment by raisedadead** [comment]
@ButsAndCats thanks for reporting, and sorry about the delay in responding. Tagging as help wanted for anyone who can reproduce and find a fix, if this is an issue.

**Comment by craigstroman** [comment]
Hi,

Is this still an issue?

If so I would be interested in taking it.

**Comment by raisedadead** [comment]
Yes. Could you reproduce the issue?

**Comment by craigstroman** [comment]
I was able to reproduce it in the iOS simulator.  

I do have one question though.  I was wondering where in the repo is this CSS/HTML produced?  I couldn't find it when I was looking for it.

**Comment by craigstroman** [comment]
Hi,

I created a pull request for this fix.  Please let me know if anything needs to be changed.

Thank you,
Craig
