### ISSUE TITLE
Core Team Badge on FreeCodeCamp Profiles

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9108]
As discussed by members of the CoreTeam, it would be cool to have a simple badge saying "staff" on their freecodecamp profiles, indicating they're on the CoreTeam.

**Comment by dwd2010** [comment]
I think that is great idea!

**Comment by QuincyLarson** [comment]
@atjonathan if we do this, instead of using the word "staff" it should use the word "core team".

**Comment by QuincyLarson** [comment]
We are hoping to implement a lot of badges in the near future. This can be one of them.

**Comment by QuincyLarson** [comment]
We may add a core team badge in the future. I will close this issue for now and we can add it to the new badge issue.

**Comment by clothesclothes439** [comment]
Your h2 element should be red.
Your h2 element should have the class red-text.
Your stylesheet should declare a red-text class and have its color set to red.
Do not use inline style declarations like style="color: red" in your h2 element.
I am on lesson 15 and i am having issue with the color text?  I cannot get into the chat room for some strange reason

**Comment by clothesclothes439** [comment]
i will work on but i have tried everything, and it is red,the text is red but no cigar.

**Comment by clothesclothes439** [comment]
bing i got it, but that was hard

**Comment by dwd2010** [comment]
@clothesclothes439, it seem like you leave comment in wrong issue.
