### ISSUE TITLE
Null value issue, cannot remove null

### ISSUE THREAD

**Issue by akashsinha261995** [FreeCodeCamp/FreeCodeCamp#9109]
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don't%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20function%20value(val)%20%7B%0A%20%20%20%20return%20val%20!%3D%3Dfalse%20%26%26%20typeof%20val%20!%3D%3D%20undefined%20%26%26%20val%20!%3D%200%20%3B%0A%20%20%7D%0A%0A%20%20arr%20%3D%20arr.filter(value)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0Abouncer(%5Bfalse%2C%20null%2C%200%2C%20NaN%2C%20undefined%2C%20%22%22%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  function value(val) {
    return val !==false && typeof val !== undefined && val != 0 ;
  }

  arr = arr.filter(value);
  return arr;
}

bouncer([false, null, 0, NaN, undefined, ""]);
```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
