### ISSUE TITLE
check for palindrome

### ISSUE THREAD

**Issue by hnamitha1** [FreeCodeCamp/freecodecamp#911]
There is  a bug in the test, I wrote the code to check the string palindrome or not like this.
function palindrome(str) {
  // Good luck!
  var i, j;
  for (i = 0,j = (str.length -1) ; i < j; i++,j--){
      if(str[i].toLowerCase() !== str[j].toLowerCase()) return false;
     else    
      return true;
  }
}
If you see this program it looks correct. yes this is correct to check the string palindrome or not. but this is wrong in returning. it wont loop entire string, With this code all the tests are passing, but it should not pass any test, at least 2 test should fail.

**Comment by LumenTeun** [comment]
Pleese close this and take an extra look at your if-statement. The #help channel on Slack is a great resource if you can't figure it out, or you can @ me on there and I'll help you out.

**Comment by hnamitha1** [comment]
Hi
I know my program is wrong. That's what I am mentioning with this program
all test cases are passing, and it allowed me to go to next exercise.
Regards
Namitha

**Comment by LumenTeun** [comment]
Oh, sorry, my bad! Should be fixed with #939
