### ISSUE TITLE
Getting the desired result but no passing the test

### ISSUE THREAD

**Issue by akashsinha261995** [FreeCodeCamp/FreeCodeCamp#9113]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20var%20res%20%3D%20arguments%5B0%5D%3B%0A%20%20var%20args%20%3D%20Array.from(arguments).slice(1)%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20args.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20res%20%3D%20res.filter(function%20(value)%20%7B%20return%20value%20!%3D%3D%20this%3B%7D%2C%20args%5Bi%5D)%3B%0A%20%20%7D%0A%20%20return%20res%3B%0A%7D%0A%0A%0Adestroyer(%5B2%2C%203%2C%202%2C%203%5D%2C%202%2C%203)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2470.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function destroyer(arr) {
  // Remove all the values
  var res = arguments[0];
  var args = Array.from(arguments).slice(1);
  for (var i = 0; i < args.length; i++) {
    res = res.filter(function (value) { return value !== this;}, args[i]);
  }
  return res;
}


destroyer([2, 3, 2, 3], 2, 3);
```

**Comment by erictleung** [comment]
@akashsinha261995 the way our site parses your code will change the relative use of `this` in your code and have unintended consequences. Put `"use strict";` within the top of your function, and it'll work correctly. Happy coding!
