### ISSUE TITLE
Prevent infinite loops from recurring by removing //noprotect from saved code

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9114]
One of the most common questions I get through email is "I used //noprotect and now my browser is stuck. What do I do?"

I get this email at least once every day. 

We should automatically remove //noprotect from their code before we load it into the browser, so that when they return to the challenge after crashing their browser, it won't crash their browser again

![](https://www.evernote.com/l/Ar-__b9UdnVIqKG2UJsX6z8tjk70oc2bIpMB/image.png)

**Comment by keks411** [comment]
Either that or maybe delay the script for a couple seconds if //noprotect is present. I did just that with greasemonkey+noscript while working trough all the challenges and I gave myself 5 seconds to interact.

**Comment by profoundhub** [comment]
Another way would be to reset the challenge to default, but the user might lose all his/her work.

**Comment by QuincyLarson** [comment]
@keks411 @profoundhub I think deleting the noprotect is probably the most elegant solution of the three (even though it's my suggested solution). The reason is we wouldn't need to explain anything to the camper. If they wanted to disable loop protection again, they would realize they just needed to use noprotect once again. I definitely wouldn't want to delete any of their other code, as that could anger them, and I get enough angry emails as is :)

**Comment by benmcmahon100** [comment]
#9129

**Comment by benmcmahon100** [comment]
Open pr for this is #9129
Github seems to have missed that :p

**Comment by wrejcodes** [comment]
In the past when I've accidentally done this, I would kill he task and add run=disabled to the url. Would it be possible to append run=disabled to the url from the backend? I know you can front the browser (window.location.href) but if their browser is crashing that doesn't help. Sorry if this is totally off base this is actually the first time looking at FCC github page.
