### ISSUE TITLE
After submitting a challenge, remove its code from browser's local storage

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9115]
Our storage of incomplete code has caused a ton of confusion. Many campers switch browsers or devices, then visit a previously completed challenge only to think that "Free Code Camp has lost my code!"

The reason we store campers' code in a browser is to prevent them from losing this code if their browser crashes. 

- [ ] As a camper, once I submit a solution to a challenge, my stored solution should be removed from my browser's local storage so I next time I view this challenge.

- [ ] As a camper, if I return to a challenge and a partial solution for that challenge is available in my local storage, it should load my partial solution (as it currently does). I should see a flash message that says "We have loaded your partial solution below. Good luck finishing and submitting it."

**Comment by jkascend** [comment]
Okay if I tackle this one?

**Comment by benmcmahon100** [comment]
Hey @jkascend Unfortunately, it looks as if someone already has a PR in place!
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9130

We'd still love to have a contribution from you so please keep browsing issues!

**Comment by jkascend** [comment]
Oh ok, no problem! I will keep a lookout for new issues :-)

**Comment by chuckadams** [comment]
Commenting from the peanut gallery: wouldn't it make more sense to just implement proper caching of challenge code?  Request the text as a resource with a proper URL, give it appropriate etags and cache-control, and all this takes care of itself, with no need to reinvent caching using local storage.
