### ISSUE TITLE
Ctrl+enter shortcut doesnt work

### ISSUE THREAD

**Issue by Desentso** [FreeCodeCamp/freecodecamp#912]
Challenge http://www.freecodecamp.com/challenges/waypoint-try-camper-news has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

It's not just that challenge but in every one the shortcut to get to the next challenge/mark the challenge completed. When I press Ctrl+Enter nothing happens. Clicking with mouse works as intended.

**Comment by LumenTeun** [comment]
Which browser do you use, and do you have any add-ons that might interfere with keyboard shortcuts or something similar?

**Comment by Desentso** [comment]
I use the newest chrome. As far as I know I have only AdBlock installed in my browser. Actually now it just started working when I got to the challenges where I can write things and do exercises. The shortcut didn't work in the introduction part where was videos and basic information about the Freecodecamp.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if it still an issue.
