### ISSUE TITLE
I can't move to the next challenge. What i'm I doing wrong?

### ISSUE THREAD

**Issue by vamenssa** [FreeCodeCamp/FreeCodeCamp#9120]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20Assignments%0ASTUDLYCAPVAR%20%3D%2010%3B%0APRoperCAmelCAse%20%3D%20%22A%20String%22%3B%0AtITLEcASEoVER%20%3D%209000%3B%0A%0AstudylCapVar%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;

studylCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;
```

**Comment by BerkeleyTrue** [comment]
Please use help room when you get stuck. Issue's are for bug reporting only.

Happy Coding

**Comment by vamenssa** [comment]
thanks @BerkeleyTrue

**Comment by CptnRnz** [comment]
did u solve it? im stuck here too i need help

**Comment by ncarrasco** [comment]
@CptnRnz here the solutions.
![camelcase](https://cloud.githubusercontent.com/assets/12000912/20402220/2f977eda-acd2-11e6-8f67-5f4536f3c3ca.PNG)

**Comment by texas2010** [comment]
@ncarrasco 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by ncarrasco** [comment]
@texas2010 
Sorry, actually you're right
