### ISSUE TITLE
"Tribute Page" Challenge/"Personal Portfolio" Challenge Mix-Up

### ISSUE THREAD

**Issue by ghost** [FreeCodeCamp/FreeCodeCamp#9121]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When I completed the "Tribute Page" challenge project and submitted it, I went to my profile and it said that I had also completed the "Personal Portfolio" challenge project; I clicked "View Project" and it displayed my Tribute Page.

It seems like when I submitted my Tribute Page, it submitted the same CodePen pen for the Personal Portfolio challenge project. The date under when it was completed is also the same.

Here is a picture:
![untitled](https://cloud.githubusercontent.com/assets/19766293/16014928/773f842c-3161-11e6-8993-86827f764040.png)

**Comment by LKloosterman** [comment]
Hey Jonathan,

I didn't submit anything to the personal portfolio project, I didn't even
start that project; it just sort of appeared as finished after I submitted
my tribute page. I only have one CodePen pen which I submitted to the
Tribute Page submission but it seems to have also submitted to the Personal
Portfolio project (which looks a little silly).

Thanks,

-Lars Kloosterman

On Mon, Jun 13, 2016 at 12:34 PM, Jonathan <notifications@github.com> wrote:

> @LKloosterman <https://github.com/LKloosterman>, are you sure you didn't
> actually provide the wrong link? Try resubmitting with defiantly the
> correct links, to see if the problem is resolved.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9121#issuecomment-225635175>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS2cFf5iltd7Y37zBl7Amr4BWA268Mnuks5qLYZ7gaJpZM4I0gGs>
> .
>



-- 

( ͡° ͜ʖ ͡°)

**Comment by sthodup1** [comment]
@LKloosterman  Now that I think about it. I think I ran into the same problem but assumed I inputted the link wrong.

**Comment by atjonathan** [comment]
Can anyone else confirm this?
cc/ @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
Closing as stale?
