### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by ddurkee1** [FreeCodeCamp/FreeCodeCamp#9122]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by ddurkee1** [comment]
I cant load all this information easily while working from my phone.

**Comment by erictleung** [comment]
@ddurkee1 can you take a screenshot of what you're seeing? What challenges are you having issues with? And can you give more information about what kind of device (Android, iPhone, etc), and browser? The more information you can provide about your situation will help us diagnose the issue for you. Currently, we don't have much information to help you. I hope you understand.

**Comment by ddurkee1** [comment]
I did submit that info, I thought at least.  When it loaded the page to
after I typed in everything, the info didn't transfer.  But it was the find
length of a string demo in the Javascript section.  I used the
lastName.length to find the length of 8 as I am supposed to do, but when I
run the testing says that I didn't use that method call.

Drew

**Comment by ddurkee1** [comment]
It was on an android note5 and the browser was chrome.

**Comment by erictleung** [comment]
@ddurkee1 I can't reproduce your issue. When you have the chance, please post the code you used. It might aid in addressing the issue.

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue is legitimate!
