### ISSUE TITLE
Accessing Objects Properties with the Dot Operator

### ISSUE THREAD

**Issue by Mzahoor** [FreeCodeCamp/FreeCodeCamp#9124]
Challenge [Accessing Objects Properties with the Dot Operator](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-the-dot-operator#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20%22hat%22%3A%20%22ballcap%22%2C%0A%20%20%22shirt%22%3A%20%22jersey%22%2C%0A%20%20%22shoes%22%3A%20%22cleats%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20hatValue%20%3D%20%7B%0A%20%20%22hat%22%3A%20%22ballcap%22%2C%0A%20%20%22shirt%22%3A%20%22jersey%22%2C%0A%0A%7D%3B%0Avar%20hatValue%20%3D%20hatValue.hat%3B%20%20%20%20%20%20%2F%2F%20Change%20this%20line%0Avar%20shirtValue%20%3D%20shirtValue.shirt%3B%20%20%20%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  "hat": "ballcap",
  "shirt": "jersey",
  "shoes": "cleats"
};

// Only change code below this line
var hatValue = {
  "hat": "ballcap",
  "shirt": "jersey",

};
var hatValue = hatValue.hat;      // Change this line
var shirtValue = shirtValue.shirt;    // Change this line

```

**Comment by erictleung** [comment]
@Mzahoor your code is incorrect. Please reread the instructions. You should only be adding to the code:

```js
var hatValue = testObj;      // Change this line
var shirtValue = testObj;    // Change this line
```

You shouldn't be deleting anything. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
