### ISSUE TITLE
<h1>Hello</h1>

### ISSUE THREAD

**Issue by artich111** [FreeCodeCamp/FreeCodeCamp#9125]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36 OPR/38.0.2220.29</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>
<h1>Hello</h1>

```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
