### ISSUE TITLE
不能通关，问题出在哪里

### ISSUE THREAD

**Issue by yorkyue** [FreeCodeCamp/FreeCodeCamp#9127]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.cn/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-test%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-test%22%3E%E6%88%91%E5%AE%B6%E7%9A%84%E7%8C%AB%E5%92%AA%3C%2Fh2%3E%0A%0A%3Cp%3E%E5%9C%A8%E5%A4%A7%E5%AE%B6%E5%BF%83%E7%9B%AE%E4%B8%AD%EF%BC%8C%E7%8C%AB%E6%98%AF%E6%85%B5%E6%87%92%E7%9A%84%E5%8F%AF%E7%88%B1%E7%9A%84%E5%8C%96%E8%BA%AB%EF%BC%8C%E5%AE%83%E5%8F%AF%E4%BB%A5%E7%9D%A1%E9%A5%B1%E4%BA%86%E5%86%8D%E8%B5%B7%E6%9D%A5%E5%90%83%E9%A5%AD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%97%E8%B6%A3%E5%B0%8F%E8%80%97%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8D%96%E5%BE%97%E4%BA%86%E8%90%8C%EF%BC%8C%E4%BD%BF%E5%BE%97%E4%BA%86%E5%9D%8F%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%99%BE%E5%8F%98%E7%9A%84%E5%B0%8F%E6%80%AA%E5%85%BD%E5%B0%B1%E9%9B%86%E7%BB%93%E5%9C%A8%E4%B8%80%E5%8F%AA%E5%AE%A0%E7%89%A9%E4%B8%8A%EF%BC%8C%E5%8F%AF%E7%8C%AB%E5%8F%AF%E7%8B%97%E3%80%82%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-test {
    color: red;
  }
</style>

<h2 class="red-test">我家的猫咪</h2>

<p>在大家心目中，猫是慵懒的可爱的化身，它可以睡饱了再起来吃饭，可以逗趣小耗子，可以卖得了萌，使得了坏，这样百变的小怪兽就集结在一只宠物上，可猫可狗。</p>

```

**Comment by erictleung** [comment]
@yorkyue 你好和谢谢你的问题。我的中文不太好。但是，我可以帮你一点。

首先，这是英文的FreeCodeCamp网站。我们不能给同中国网站获得帮助。你的问题是，你用“test”，但是你应该用“text”。

今后，请到[中国的网站](https://github.com/huluoyang/freecodecamp.cn)，使问题。我们不能帮你。 我希望你明白。 在未来，[中国聊天室](https://gitter.im/FreeCodeCamp/chinese)可以帮助你。谢谢和编程快乐！

**Comment by yorkyue** [comment]
thanks
