### ISSUE TITLE
Profile Lookup Challenge, Done everything but only passing 2/5 

### ISSUE THREAD

**Issue by AhmedElkashef02** [FreeCodeCamp/FreeCodeCamp#9128]
The problem is that the first if condition has a problem that I think is trivial but I can't figure it out ath the same time ..
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup#?solution=%0A%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUpProfile(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20for%20(%20var%20i%20%3D%200%3B%20i%20%3C%20contacts.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(%20contacts%5Bi%5D.firstName%20%3D%3D%3D%20firstName%20%26%26%20contacts%5Bi%5D.hasOwnProperty(prop))%20%7B%0A%20%20%20%20%20%20return%20contacts%5Bi%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if%20(firstName%20!%3D%3D%20contacts%5Bi%5D.firstName)%20%7B%0A%20%20%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20if%20(contacts%5Bi%5D.hasOwnProperty(prop)%20%3D%3D%3D%20false)%20%7B%0A%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUpProfile(%22Harry%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
  for ( var i = 0; i < contacts.length; i++) {
    if ( contacts[i].firstName === firstName && contacts[i].hasOwnProperty(prop)) {
      return contacts[i][prop];
    }
    else if (firstName !== contacts[i].firstName) {
      return "No such contact";
    }
    else if (contacts[i].hasOwnProperty(prop) === false) {
      return "No such property";
    }
  }
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Harry", "likes");

```

**Comment by pitlv2109** [comment]
I think this challenge is designedly bad. The three incorrect answers from your code were the ones that had property with value(s), weren't they? For example, lookUpProfile("Sherlock", "likes");. Well, when the for-loop runs, it will not iterate from 0 to contacts.length - 1. The value of i will only be 0. Do you see why? After the first run, there will be a return statement no matter what. Therefore, the for-loop (and the function) will end. 

P.s: If you have coded in complied programming languages, such as C, C++, Java, etc. (I'm not sure if this is JavaScript or the compile that FreeCodeCamp is using), when you use if-else statement, there will/must always be an "else" at the end of this if-else statement (you has else if).

**Comment by AhmedElkashef02** [comment]
Ok, you have made a good point here, and I tried your code but I found 2 consecutive returns, can you post a picture so I can see how your code indentation? I really appreciate your help :+1:

**Comment by pitlv2109** [comment]
Mine works just fine. 

<img width="525" alt="screen shot 2016-06-13 at 8 39 08 pm" src="https://cloud.githubusercontent.com/assets/10616421/16028655/f3db4e54-31a6-11e6-98f2-7d68c10d8cc7.png">

**Comment by erictleung** [comment]
@AhmedElkashef02 @pitlv2109 looks like the issue is resolved. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by romort** [comment]
Thank you for posting.  I got stuck on this challenge and this helped me.  

I still have one question though: Shouldn't the for loop be using contacts.length instead of firstName.length?

**Comment by sucomimus** [comment]
I have the same question as @romort 
I tried both and both work perfectly.  Why is firstName.length correct? Is it just because both lengths are equal to 4?

**Comment by brainExplorer** [comment]
solution:
function lookUpProfile(name, prop)
{
// Only change code below this line
for (var p in contacts) 
 {
    if (contacts[p].firstName === name) 
    {
        if (!contacts[p].hasOwnProperty(prop))
        {
          return 'No such property';
        }
      return contacts[p][prop];
    } 
  }
  return "No such contact";
// Only change code above this line
}
