### ISSUE TITLE
Stumped

### ISSUE THREAD

**Issue by kimpossible9** [FreeCodeCamp/FreeCodeCamp#9131]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%3C!--Hello%20World--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3C!--CatPhotoApp--%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3C!--Hello%20Paragraph--%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--Hello World-->
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<!--CatPhotoApp-->
<p>Hello Paragraph</p>
<!--Hello Paragraph-->
```

**Comment by BerkeleyTrue** [comment]
Please use the help rooms/forums when you get stuck. The issue tracker is for reporting bugs only.

Happy Coding.
