### ISSUE TITLE
It says  You should not use any if or else statements but I didnt

### ISSUE THREAD

**Issue by FaiqAgayev** [FreeCodeCamp/FreeCodeCamp#9135]
Challenge [Adding a default option in Switch statements](https://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements#?solution=%0Afunction%20switchOfStuff(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%7B%0A%20%20%20%20case%20%22a%22%3A%0A%20%20%20%20return%20%22apple%22%3B%0A%20%20%20%20break%3B%0A%20%20%20%20case%20%22b%22%3A%0A%20%20%20%20return%20%22bird%22%3B%0A%20%20%20%20break%3B%0A%20%20%20%20case%20%22c%22%3A%0A%20%20%20%20return%20%22cat%22%3B%0A%20%20%20%20break%3B%0A%20%20%20%20default%3A%0A%20%20%20%20return%20%22stuff%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AswitchOfStuff(%22a%22)%3B%2F%2F%20should%20have%20a%20value%20of%20%22apple%22%0AswitchOfStuff(%22b%22)%3B%2F%2F%20should%20have%20a%20value%20of%20%22bird%22%0AswitchOfStuff(%22c%22)%3B%2F%2F%20should%20have%20a%20value%20of%20%22cat%22%0AswitchOfStuff(%22d%22)%3B%2F%2F%3B%20should%20have%20a%20value%20of%20%22stuff%22%0AswitchOfStuff(4)%3B%20%2F%2Fshould%20have%20a%20value%20of%20%22stuff%22%0A%2F%2FYou%20should%20not%20use%20any%20if%20or%20else%20statements%0A%2F%2FYou%20should%20have%20at%20least%203%20break%20statements%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch(val){
    case "a":
    return "apple";
    break;
    case "b":
    return "bird";
    break;
    case "c":
    return "cat";
    break;
    default:
    return "stuff";
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff("a");// should have a value of "apple"
switchOfStuff("b");// should have a value of "bird"
switchOfStuff("c");// should have a value of "cat"
switchOfStuff("d");//; should have a value of "stuff"
switchOfStuff(4); //should have a value of "stuff"
//You should not use any if or else statements
//You should have at least 3 break statements

```

**Comment by FaiqAgayev** [comment]
Oh I reseted this code and this worked

**Comment by robjloranger** [comment]
this can be closed
