### ISSUE TITLE
Sum All Numbers In A Range Bonfire Issue - Not Passing Correct Code

### ISSUE THREAD

**Issue by redixhumayun** [FreeCodeCamp/FreeCodeCamp#9137]
#### Challenge Name

https://www.freecodecamp.com/challenges/sum-all-numbers-in-a-range#?solution=var%20max%3D0%3B%0Avar%20min%3D0%3B%0Avar%20sum%3D0%3B%0Afunction%20sumAll(arr)%20%7B%0A%20%20if(arr%5B0%5D%3Earr%5B1%5D)%7B%0A%20%20%20%20max%3Darr%5B0%5D%3B%0A%20%20%20%20min%3Darr%5B1%5D%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20max%3Darr%5B1%5D%3B%0A%20%20%20%20min%3Darr%5B0%5D%3B%0A%20%20%7D%0A%20%20sum%2B%3D((max-min%2B1)*(min%2Bmax))%2F2%3B%0A%20%20return%20sum%3B%0A%7D%0A%0AsumAll(%5B10%2C5%5D)%3B%0A

#### Issue Description

Have the correct code and the correct output is being displayed, but the code will not pass the test. Tried with all the cases and got the correct output. Attempts attached in screenshots. 

#### Browser Information

* Browser Name, Version: Chrome Ver 49.0
* Operating System: Mac OSX Yosemite
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here
var max=0;
var min=0;
var sum=0;
function sumAll(arr) {
  if(arr[0]>arr[1]){
    max=arr[0];
    min=arr[1];
  }
  else{
    max=arr[1];
    min=arr[0];
  }
  sum+=((max-min+1)*(min+max))/2;
  return sum;
}

sumAll([10,5]);
```

#### Screenshot

<img width="1295" alt="screen shot 2016-06-14 at 11 48 08 am" src="https://cloud.githubusercontent.com/assets/18127629/16049508/f58b6264-3225-11e6-9cc2-09ecc7086d28.png">
<img width="1339" alt="screen shot 2016-06-14 at 11 48 18 am" src="https://cloud.githubusercontent.com/assets/18127629/16049507/f5875c6e-3225-11e6-8224-ee23f924b3f5.png">
<img width="1332" alt="screen shot 2016-06-14 at 11 48 28 am" src="https://cloud.githubusercontent.com/assets/18127629/16049509/f58cf46c-3225-11e6-8f4d-76ad646f8f1f.png">
<img width="1340" alt="screen shot 2016-06-14 at 11 48 36 am" src="https://cloud.githubusercontent.com/assets/18127629/16049506/f583c9dc-3225-11e6-9082-3cb0fdf07a5c.png">

**Comment by erictleung** [comment]
@redixhumayun global variables are bad. Our tests run your function multiple times and they change your globally scoped variables each time, resulting in unintended consequences. Move your global variables into your function and everything should be good. Happy coding!
