### ISSUE TITLE
Missing test for basic javascript challenge

### ISSUE THREAD

**Issue by paccao** [FreeCodeCamp/FreeCodeCamp#9138]
#### Challenge Name

[Appending Variables to Strings](https://www.freecodecamp.com/challenges/appending-variables-to-strings#?solution=%0A%2F%2F%20Example%0Avar%20anAdjective%20%3D%20%22awesome!%22%3B%0Avar%20ourStr%20%3D%20%22Free%20Code%20Camp%20is%20%22%3B%0AourStr%20%2B%3D%20anAdjective%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20someAdjective%20%3D%20%22fun!%22%3B%0Avar%20myStr%20%3D%20%22Learning%20to%20code%20is%20%22%3B%0AsomeAdjective%20%2B%3D%20someAdjective%3B%0A)
#### Issue Description

It doesn't verify that the result is added to the variable `myStr` so my solution passes although it's not.

#### Browser Information

* Browser Name, Version: Google Chrome Version 51.0.2704.84 m
* Operating System: Windows 10 Desktop

#### Your Code

```js
// Example
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// Only change code below this line

var someAdjective = "fun!";
var myStr = "Learning to code is ";
someAdjective += someAdjective;
```

#### Screenshot

![freecodecamp bug 1](https://cloud.githubusercontent.com/assets/16489683/16056110/54340c32-3274-11e6-9528-b868468ae075.PNG)

**Comment by robjloranger** [comment]
I can write a new test for this when i get home, ~4hrs from now :)

**Comment by atjonathan** [comment]
@paccao thanks for catching this!
@robjloranger, sounds great :smile: 

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by Dinar717** [comment]
`
// Example
var anAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

var someAdjective = "fun!";
var myStr = "Learning to code is ";
myStr += someAdjective;`
