### ISSUE TITLE
Find the Longest Word in a String

### ISSUE THREAD

**Issue by Mzahoor** [FreeCodeCamp/FreeCodeCamp#9140]
Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=const%20findLongestWord%20%3D%20str%20%3D%3E%20Math.max(...str.split(%22%20%22).map(g%20%3D%3E%20g.lenghth))%3B%0A%0A%0AfindLongestWord(%22%22)%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
const findLongestWord = str => Math.max(...str.split(" ").map(g => g.lenghth));


findLongestWord("");



```

**Comment by BKinahan** [comment]
Fix the typo `lenghth` and it works. You may need to refresh the page.

Note that issues are for reporting bugs with challenges. For help with your code please consult the [Help chat room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by atjonathan** [comment]
Thanks @BKinahan :+1:

**Comment by Mzahoor** [comment]
thank you BKinahan i got it
