### ISSUE TITLE
last html lesson "use rgb to mix colors"

### ISSUE THREAD

**Issue by BlindBlake** [FreeCodeCamp/FreeCodeCamp#9142]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(255%2C0%2C0)%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C112%2C214)%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C82%2C45)%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C0%2C255)%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(255,0,0)
  }
  .orchid-text {
    color: rgb(218,112,214)
  }
  .sienna-text {
    color: rgb(160,82,45)
  }
  .blue-text {
    color: rgb(0,0,255)
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```
When I submit my code the program will not let me pass because all the "Use rgb for the color y" answers are ex-out. I asked about this in the forum and everyone seemed to think my coding is correct. Plus, all the text that are supposed to change colors do change to the appropriate color. Help! What is wrong?

**Comment by robjloranger** [comment]
@BlindBlake Your just missing the semi-colons after each rgb():
i.e.    ``` color: rgb(255,0,0); ```

**Comment by erictleung** [comment]
@BlindBlake what @robjloranger suggests is correct. You need semicolons at the end of your color values. Although they work without semicolons (as you can see color changes), we want to promote the best practice of having them there. I hope that helps. Happy coding!

**Comment by ronit31** [comment]
Hi,

Thanks for that :D

**Comment by lismil15** [comment]
Hi I had the same issue but in my case I do have the semicolons. What is it that's wrong? 
<style>
  .red-text {
    color: rbg(255,0,0);
  }
  .orchid-text {
    color: rbg(218,112,214);
  }
  .sienna-text {
    color: rbg(160,82,45);
  }
  .blue-text {
    color: rbg(0,0,255);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

**Comment by kayode16** [comment]
good job guys. it works for me.

**Comment by TomorrowIsToday** [comment]
Strange same issue. Copied the above Code and worked just fine.

**Comment by wonmaungthein** [comment]
@robjloranger Wow... Thanks.. I had same issues..

**Comment by twyststar** [comment]
Thanks!

**Comment by wolff2016** [comment]
Thanks

**Comment by bibbitybobbityboo** [comment]
This worked thanks but I don't recall in the lessons it ever saying to add the ";". 
Thanks

**Comment by robjloranger** [comment]
No problem, just fyi every declaration in css should end with a semi-colon.
```
.my-class{
  color: blue;
  opacity: .8;
}
```
etc, this is useful if you ever have to inline some css in a style attribute
```<div style="color: blue; opacity: .8;"></div>```
it tells the css processor where the last declaration ends.

**Comment by bibbitybobbityboo** [comment]
Thanks

**Comment by rjkmurray** [comment]
At at first you succeed

**Comment by rjkmurray** [comment]
Try try again
