### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by nghiann262** [FreeCodeCamp/FreeCodeCamp#9147]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22%5Cb%2C%5Ct%2C%5Ct%2C%5Cr%2C%5Cn%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/55.2.126 Chrome/49.2.2623.126 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="\b,\t,\t,\r,\n"; // Change this line



```

**Comment by Dinar717** [comment]
var myStr="\\ \t \t \r \n"; //

**Comment by Dinar717** [comment]
`var myStr="\\ \t \t \n";`

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
