### ISSUE TITLE
Animate #testSuite to focus user on errors

### ISSUE THREAD

**Issue by heldersepu** [FreeCodeCamp/FreeCodeCamp#9148]
#### Challenge Name
This applies to any challenge that has the button [Run tests]

#### Issue Description
For a new user clicking multiple times in the [Run tests] button looks like nothing is happening.
We should animate the div that contains the errors ( #testSuite ) to let the user know that something is wrong

#### Browser Information

* Browser Name, Version: Google Chrome V51
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by katrina562** [comment]
Hello

**Comment by atjonathan** [comment]
@katrina562, hey :wave: :joy:

**Comment by katrina562** [comment]
Hi
