### ISSUE TITLE
Unable to succeed at "Storing Values with the Assignment Operator"

### ISSUE THREAD

**Issue by leemurdock** [FreeCodeCamp/FreeCodeCamp#9149]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20a%20%3D%207%3B%0Avar%20b%20%3D%20var%20a%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Write the code I've written below and attempt to run the test.

My code:
```javascript

// Setup
var a;
var b = 2;

// Only change code below this line
var a = 7;
var b = var a;

```

**Comment by sujeet100** [comment]
The code you have mentioned has got a syntax error and hence no tests would be run.
I think the code stub has intentionally kept the syntax error, so that students can resolve it, before running any tests.
If you change your code to following, then the tests would pass.
```javascript
// Setup
var a;
var b = 2;

// Only change code below this line
var a = 7;
var b = a;
```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by solo800** [comment]
I have also run into the issue described above even without the syntax error.
`// Setup
var a;
var b = 2;

// Only change code below this line

b += 5;
a = b;`

**Comment by aj-willi** [comment]
here is the answer 


// Setup
var a;
var b = 2;

// Only change code below this line

var b = 7;
var a = 7;
b = a;

**Comment by texas2010** [comment]
@aj-willi 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Sh0t1337** [comment]
First pass: 
a = 7; b = 7;
// ^^^^^ Read.

**Comment by Marcelloe** [comment]
// Setup
var a;
var b = 2;
// Only change code below this line
var a = 7;
var b = a;

**Comment by Parajux** [comment]
i had problem with this and I put

// Setup
var a;
var b = 2;

// Only change code below this line
var a = 7;
var b = a;
