### ISSUE TITLE
Comment p and h1 with one comment block

### ISSUE THREAD

**Issue by spiritinlife** [FreeCodeCamp/freecodecamp#915]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-out-html has an issue.

Shouldn't this work also  ?
 ```
<!--
<h1>Hello World</h1>
<p>Hello Paragraph</p>
--> 
```
It complains about Be sure to close each of your comments with -->.

**Comment by LumenTeun** [comment]
You need to wrap your code in ``` if you don't want GitHub to remove it.

**Comment by spiritinlife** [comment]
@LumenTeun :+1: 
Updated the post ,Thx for pointing out :)

**Comment by LumenTeun** [comment]
The tests check for more than one closud comment, like this:
```javascript
editor.match(/-->/g).length > 1
```
I think this is because you're not supposed to restructure your code, i.e., the h2 element should still be between the h1 and p elements.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please reopen if this is still an issue
