### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by WanderBread** [FreeCodeCamp/FreeCodeCamp#9154]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunction(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20it's%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20it's%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Afunction%20trueOrFalse(wasThatTrue)%7B%0A%20%20if%20(wasThatTrue)%20%7B%0A%20%20%20%20return%20%22Yes%2C%20that%20was%20true%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%7B%0A%20%20%20%20return%20%22No%2C%20that%20was%20false%22%3B%0A%20%20%7D%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourFunction(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
function trueOrFalse(wasThatTrue){
  if (wasThatTrue) {
    return "Yes, that was true";
  }
  
  {
    return "No, that was false";
  }
}

```
I encounter a problem with this challenge, for some odd reason the code was returning "Yes, that was true" but it wasn't checking it off on the challenge goals, the way I fixed it was by rewriting the function from scratch and making sure I had open and closing curly brackets for my - return "No, that was false" - segment.

my guess is that there's a indentation problem somewhere.

**Comment by BKinahan** [comment]
"For some odd reason my code didn't work" isn't exactly a reproducible issue we can do something to fix.. Maybe you could provide some more information?

If there isn't an issue, you can close this report :)

**Comment by benmcmahon100** [comment]
@WanderBread as a side note JS doesn't about indentation.
You're else part of the statement should also actually contain and else or not include the second set of curly braces.
Finally I've just ran your code and it works. Try refreshing your browser and re-running your code.

**Comment by benmcmahon100** [comment]
I'm going to close for now as it is more of a help request. If the issue persists than feel free to re-open the issue. Otherwise, happy coding!

**Comment by WanderBread** [comment]
@benmcmahon100  I was looking for a way to explain myself better, so I apologize for the inconvenience... my code worked it was the original code that gave me a problem... I would make sure to be more specific if I ever run into any other problems... again my apologies for the lack of explanation.

**Comment by benmcmahon100** [comment]
@WanderBread No worries! No incomvenience experienced! :stuck_out_tongue:  
Thank you for being a pro-active user and reporting issues!
Happy coding!
