### ISSUE TITLE
Challenges should not auto-run

### ISSUE THREAD

**Issue by chuckadams** [FreeCodeCamp/FreeCodeCamp#9157]
A simple way to replicate the problem, taking a random challenge:

https://www.freecodecamp.com/challenges/understanding-boolean-values#?solution=alert("BOO!")

This not only pops up an alert, it does it twice.  It shouldn't even be running it at all, unless and until the submit button (or ctrl-enter) requests it.  All the problems people have with infinite loops, and the magic URL parameters people have to enter to prevent them, can be prevented if FCC simply refrains from auto-running user code in the first place.  Infinite loops could then be broken out of by simply hitting refresh.

**Comment by erictleung** [comment]
Related to #5072.

**Comment by raisedadead** [comment]
I like this idea. If implemented will help a ton of common issues. But mostly will not count once we have reactified challenge editor in place.

/cc @BerkeleyTrue
