### ISSUE TITLE
Updating Codepen instructions for adding Bootstrap to a pen

### ISSUE THREAD

**Issue by nickbarry** [FreeCodeCamp/freecodecamp#916]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I'm recommending a change in one of the instructions on this Waypoint.

One step in this waypoint describes how to add Bootstrap to your pen:
'Click the gear next to CSS. Then in the "External CSS File or Another Pen" text field, type "bootstrap" and scroll down until you see the latest version of Bootstrap. Click it.'

When I do this, the latest version appears to be 3.3.2, and there are several of those from different sources. I'm not sure if they're all the same. The Bootstrap website says the latest version is actually 3.3.4. 

Then I noticed that there's a "Quick-add" dropdown, which allows you to easily add Bootstrap. And it's the latest version, too!

![bootstrap codepen](https://cloud.githubusercontent.com/assets/8515899/8146181/5dc37374-11e0-11e5-83c1-3c9092fbd47a.png)

So I'd recommend you change the wording of that particular step to:
'Click the gear next to CSS. Then under the "Add External CSS" section, use the "Quick-add" select box to select Bootstrap. Then click "Save & Close".'

For the next step, #11, in the Javascript settings, I also don't see a "Latest version of..." select box. Maybe Codepen has made some changes since this Waypoint was written? I propose new wording for step 11:
'Click the gear next to JavaScript. Click the "Quick-add" select box and choose jQuery (not jQuery UI). Then click "Save & Close".'

![javascript codepen settings](https://cloud.githubusercontent.com/assets/8515899/8146205/7d26b176-11e1-11e5-9845-c72c1310325f.png)

**Comment by QuincyLarson** [comment]
Thank you for your excellent GitHub issue, and for the screen shots to clarify. I've updated the copy, and credited you on the commit.
