### ISSUE TITLE
missing dependency for #23 of 'Manage packages with npm'

### ISSUE THREAD

**Issue by NatalieLow** [FreeCodeCamp/FreeCodeCamp#9160]
#### Challenge Name

https://www.freecodecamp.com/challenges/manage-packages-with-npm

#### Issue Description

When running #23 Complete "Package Niceties", I encountered the following error:

npm ERR! code E404

npm ERR! 404 missing : async
npm ERR! 404 
npm ERR! 404  'async' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@gnatann/chat-example'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/learn_npm/npm-debug.log

Uh oh!
It looks like something went wrong
#########################################
#########################################
https://preview.c9users.io/natalie_low/npm/learn_npm/npm-debug.log

#### Browser Information

* Browser Name, Version: Chrome Version 51.0.2704.84
* Operating System: OSX El Capitan 10.11.5 
* Mobile, Desktop, or Tablet: Macbook air

#### Screenshot

![screen shot 2016-06-15 at 2 36 07 pm](https://cloud.githubusercontent.com/assets/5697015/16098426/b888cb58-3307-11e6-94af-3a6f7daed084.png)

**Comment by dhcodes** [comment]
This is not a FreeCodeCamp issue. If anything, it would be a LearnYouNode issue, but I do believe the package is there. Try running `sudo npm install -g async`. If that doesn't work, consider asking in the FreeCodeCamp HelpBackEnd room on Gitter: https://gitter.im/FreeCodeCamp/HelpBackEnd

Hopefully the install command fixes it though.

**Comment by BerkeleyTrue** [comment]
@dhcodes is correct. Please open this issue with LearnYouNode.

Happy Coding
