### ISSUE TITLE
Size Your Image Issue

### ISSUE THREAD

**Issue by JacquiM505** [FreeCodeCamp/FreeCodeCamp#9161]
#### Challenge Name

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

#### Issue Description

I am not able to continue to the next Challange, please help

#### Browser Information

* Browser Name, Version: Chrome Version 51.0.2704.84 (64-bit)
* Operating System: Mac OSX Yosemite Mac Book Air 
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by arun1595** [comment]
This is not the space for asking help to solve challenges. Please head over to [FreeCodeCamp Help](https://gitter.im/FreeCodeCamp/Help)

**Comment by JacquiM505** [comment]
I did the challenge correctly - I cannot get it to advance me to next
challenge.

I will look again though FreeCodeCamp Help

Thank you.

On Wednesday, June 15, 2016, Arun Kumar <notifications@github.com> wrote:

> This is not the space for asking help to solve challenges. Please head
> over to FreeCodeCamp Help <https://gitter.im/FreeCodeCamp/Help>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9161#issuecomment-226375236>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS_bf4ZAbeVsZtfTUodc6HwAw6Kn0G1eks5qMLpzgaJpZM4I23FY>
> .
>


-- 
Sent from Gmail Mobile

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by PiTvApp** [comment]
I'm having the same issue & have used the help chat. I am using safari and it is saying that I need to zoom in. Each time I zoom in, I check to see if it will allow me to pass, but it is still stuck on this problem. Were you able to pass this section? If so what did you do?

**Comment by MsMarChe** [comment]
i am having the same problem it must be a bug in the program. can the programer check this issue instead of just sending us to help on a broke part of the program. thankyou

**Comment by MsMarChe** [comment]
i will just go to my map and go to the next part until this part is debug. also i have imported the code from the next challenge and it still say i am wrong
