### ISSUE TITLE
Random Quote Machine - Facebook Javascript SDK not working on codepen

### ISSUE THREAD

**Issue by mav1283** [FreeCodeCamp/FreeCodeCamp#9164]
My share to facebook button works locally on my computer, im using xampp.. here's my javascript for the facebook button:

A.)  i tried this initialization as instructed on the facebook developers page and it worked locally

```
 $.ajaxSetup({ cache: true });
	   $.getScript('//connect.facebook.net/en_US/sdk.js', function(){
	     FB.init({
	       appId: '1613185902325802',
	       version: 'v2.6' // or v2.0, v2.1, v2.2, v2.3
	     });     
	  });
```

B.) i also tried this one and worked locally

```
window.fbAsyncInit = function() {
	    FB.init({
	      appId      : '1613185902325802',
	      xfbml      : true,
	      version    : 'v2.6'
	    });
	  };

	  (function(d, s, id){
	     var js, fjs = d.getElementsByTagName(s)[0];
	     if (d.getElementById(id)) {return;}
	     js = d.createElement(s); js.id = id;
	     js.src = "//connect.facebook.net/en_US/sdk.js";
	     fjs.parentNode.insertBefore(js, fjs);
	   }(document, 'script', 'facebook-jssdk'));
```

But both didn't worked on codepen, i don't use them together because they're just the same.. and here's my button code:

```
$("#sharefacebook").on("click",function(){
		FB.ui({
		  method: 'share',
		  quote: sharequote,
		  href: 'http://codepen.io/mav1283/pen/wWWMdg',
		}, function(response){});
	});
```

it also worked locally with either inializations (A. and B.) mentioned above.

am i doing something wrong or it's just codepen does not support the facebook javascript sdk?

**Comment by dhcodes** [comment]
I recommend checking your console to see if there are any errors listed there. Codepen often has cross-origin errors to prevent spamming. 

Ultimately, though, this is not an issue with FreeCodeCamp. The user stories say to make a button to tweet the quote, not use Facebook. And if Codepen is indeed the problem, then the FCC team can't really fix it so you may be better off submitting the issue to the Codepen bug repository or to their site.

**Comment by atjonathan** [comment]
@dhcodes, good point!
@mav1283, this is not an issue with FreeCodeCamp, use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge help. Happy Coding!
