### ISSUE TITLE
MangoDB issue when start the project

### ISSUE THREAD

**Issue by keepcurrent** [FreeCodeCamp/FreeCodeCamp#9169]
This is my first time to set up this project. I installed mangodb, node, and follow the instructions. Everything looks good until I run 'mongod' in Git Bash,  got error message:
bash: mongod: command not found

I tried to reinstall MangoDB, still doesn't work. Anything I missed?

![image](https://cloud.githubusercontent.com/assets/6341472/16103611/e9155558-3347-11e6-97e7-359251b98772.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by erictleung** [comment]
@keepcurrent you'll probably need to run the `mongod` command straight from where you downloaded it or you can find where the `mongod.exe` file is and add that folder to your path. I think that should solve your issue.

So you could run `mongod` by specifying the path:

```
C:\mongodb\bin\mongod.exe
```

This is given your file is at that file path.

**Comment by keepcurrent** [comment]
Thank you! This works! MangoDB is running
