### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by arecvlohe** [FreeCodeCamp/freecodecamp#917]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

    function convert(str) {
       return str.replace(/[&'<>]/gim, function(entity) {
         return '&#'+ entity.charCodeAt(0) + ';';
       });
    }

    convert('Dolce & Gabbana'); 

I am able to pass one test but not the other. What am I missing? It is not explained well in the tests.

**Comment by kurzninja** [comment]
Which test is it showing you're passing and which is it showing that you are not passing?

**Comment by LumenTeun** [comment]
GitHub issues are not for support, if you have trouble with your code, please use [RSAP](http://www.freecodecamp.com/field-guide/how-do-i-get-help-when-i-get-stuck) and ask in the #help channel on Slack.

From a cursory glance, you're converting to Unicode, not [HTML entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Character_entity_references_in_HTML) like the challenge says.

**Comment by arecvlohe** [comment]
@LumenTeun I don't think I was using Unicode. Referencing the w3schools site it says: "&	- ampersand - &amp;  &#38;." Is this not so? 

Either way I passed the test using something else. Thanks for the passive aggressive tone!

**Comment by arecvlohe** [comment]
`&amp; or &#38;`
