### ISSUE TITLE
Unable to create GitHub Issue from Bug button

### ISSUE THREAD

**Issue by thinsoldier** [FreeCodeCamp/FreeCodeCamp#9172]
Challenge [Style Text Inputs as Form Controls](https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls)

Unable to create github issue because of error: 414 Request-URI Too Large. Attempting to include the entire source code from the challenge in the url results in a GET request that is too damn big. Use POST instead I guess.

**Comment by bugron** [comment]
@thinsoldier thanks for posting this issue!
I'm going to close this issue in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9123, thanks for reporting.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
