### ISSUE TITLE
without creating an arbitrary variable defined as arr[i].length, inside the for loop  j<arr[i].length condition does not work for some reason

### ISSUE THREAD

**Issue by kechy** [FreeCodeCamp/FreeCodeCamp#9175]
Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops#?solution=%0Afunction%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20proj%3D%5B%5D%3B%0A%20%20for%20(var%20i%3D0%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%0A%20%20%7B%0A%20%20%20%20%20var%20x%3Darr%5Bi%5D.length%3B%0A%20%20%20%20%20for%20(var%20j%3D0%3B%20j%20%3C%20x%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%20y%3Darr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%20product%3Dproduct*y%3B%0A%20%20%20%20%20%7D%20%20%20%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%5D%2C%5B2%5D%2C%5B3%5D%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
var proj=[];
  for (var i=0; i < arr.length; i++)
  {
     var x=arr[i].length;
     for (var j=0; j < x; j++) {
       y=arr[i][j];
       product=product*y;
     }   
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1],[2],[3]]);


```

**Comment by raisedadead** [comment]
Your code passes for me.

> `var x=arr[i].length;`
Even without using the above.

GitHub Issues are for reporting bugs on the website only.
Please consult the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance to Coding.

Happy Coding!
