### ISSUE TITLE
test does not pass despite correct results in the console

### ISSUE THREAD

**Issue by bigos** [FreeCodeCamp/FreeCodeCamp#9176]
Challenge [Sum All Numbers in a Range](https://www.freecodecamp.com/challenges/sum-all-numbers-in-a-range#?solution=%0Afunction%20sumAll(arr)%20%7B%0A%20%20var%20list%20%3D%20%5B%5D%3B%0A%20%20var%20a%20%3D%20arr%5B0%5D%3B%0A%20%20var%20b%20%3D%20arr%5B1%5D%3B%0A%20%20for%20(var%20i%20%3D%20Math.min(a%2Cb)%3B%20i%20%3C%3D%20Math.max(a%2Cb)%3B%20i%2B%2B)%20%7B%0A%20%20%20%20list.push(i)%3B%0A%20%20%7D%0A%20%20return%20list.reduce(function(x%2Cy)%7Breturn%20x%2By%3B%7D)%3B%0A%7D%0A%0AsumAll(%5B1%2C%204%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function sumAll(arr) {
  var list = [];
  var a = arr[0];
  var b = arr[1];
  for (var i = Math.min(a,b); i <= Math.max(a,b); i++) {
    list.push(i);
  }
  return list.reduce(function(x,y){return x+y;});
}

sumAll([1, 4]);

```

**Comment by erictleung** [comment]
@bigos I can't reproduce the error you're getting. Your code works for me. Have you tried resetting your code and typing in your answer again?

**Comment by dhcodes** [comment]
I concur. Worked for me in Firefox and Chrome.

**Comment by bigos** [comment]
You say ''typing your answer". Is it possible that if I type the answer in
my favourite editor or browser console it might not pass the tests even if
the pasted code appears to be OK?

**Comment by khaduch** [comment]
Hello - it is possible because of browser caching or other issues that it is necessary at times to reset the code, clear the browser cache (temporary files), etc.  It is unfortunate that sometimes that gets to be an issue, but it does.  I always copy and paste the code to an external file, reset the code on the page, then paste the code back into the editor (or sometimes just re-enter it) and try again.  Hope it works for you?

**Comment by raisedadead** [comment]
@bigos Closing as stale, please comment to re-open if you are still stuck with this.
