### ISSUE TITLE
 lesson "use rgb to mix colors"

### ISSUE THREAD

**Issue by oshamo1** [FreeCodeCamp/FreeCodeCamp#9177]
i can't progress to the next challenge even after solving correctly and color blue is faulty

#### Challenge Name

Use RGB to Mix Colors

#### Browser Information

* Browser Name, Version: firefox
* Operating System: windows 10
* Mobile, Desktop, or Tablet: asus laptop

#### Your Code

```js

<style>
  .red-text {
    color: rgb(255, 0, 0);
  }
  .orchid-text {
    color: rgb(218, 112, 214);
  }
  .sienna-text {
    color: rgb(160, 82, 45);
  }
  .blue-text {
    color: rgb(0, 0, 225);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>
// If relevant, paste all of your challenge code in here

```

**Comment by atjonathan** [comment]
@oshamo1, please provide us with more details about your issue :+1:

**Comment by oshamo1** [comment]
@atjonathan hope these details are enough and how long will it take to be resolved

**Comment by erictleung** [comment]
@oshamo1 your code is incorrect. Please refer back to the color table in the challenge and make sure you're using the correct RGB codes. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!Happy coding!
