### ISSUE TITLE
Change default 'test value'

### ISSUE THREAD

**Issue by FlorisWarmenhoven** [FreeCodeCamp/FreeCodeCamp#9180]
Challenge [Adding a default option in Switch statements](https://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements#?solution=%0Afunction%20switchOfStuff(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%20%7B%0A%20%20%20%20case%20%22a%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22apple%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22b%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22bird%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22c%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22cat%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20answer%20%3D%20%22stuff%22%3B%0A%20%20%7D%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AswitchOfStuff(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch(val) {
    case "a":
      answer = "apple";
      break;
    case "b":
      answer = "bird";
      break;
    case "c":
      answer = "cat";
      break;
    default:
      answer = "stuff";
  }  
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(1);


```

On the test value (last line), it would be a tiny bit easier if this was changed to `switchOfStuff("a");`
This isn't an issue, just a small 'quality of life' change.

**Comment by BKinahan** [comment]
I agree with you that this isn't an issue :) Why change the initial input arbitrarily? I don't see what it makes easier.. The input `1` will only output `"stuff"` correctly if the code is written correctly, the same way the input `"a"` will only output `apple` if the code is right.

Anyway, users can change the input value to test their code if they like, but it's not necessary to pass the challenge.

**Comment by FlorisWarmenhoven** [comment]
Fair point. I just figured, because the previous assignment used the case values 1 through 4, and this assignment uses case values 'a' through 'c', it would make sense to change that '1' in to 'a'.

**Comment by BKinahan** [comment]
@FlorisWarmenhoven Ah ha, I see what you mean now. I didn't have the context of the previous challenge at first. 

However I believe the point of this challenge is to illustrate what happens when the input does *not* match any of the switch cases (that is, the `default` statements are executed), so it makes sense to not use `"a"`.
