### ISSUE TITLE
File metadata microservice sample app does not satisfy specs

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#9181]
Challenge [File Metadata Microservice](https://www.freecodecamp.com/challenges/file-metadata-microservice) has an issue.

The [sample app](https://cryptic-ridge-9197.herokuapp.com/) does not render a JSON response as requested in instruction 5:

> User Story: When I submit something, I will receive the file size in bytes within the JSON response

**Comment by atjonathan** [comment]
@FreeCodeCamp/issue-moderators, should we change the user story or update the sample app. I think it would be better if we updated the sample app, to show a json response (It would be quite simple :smiley:).

**Comment by AryanJ-NYC** [comment]
If you guys are looking to link to a working app, you can, of course, use this one: https://aryanj-file-size.herokuapp.com/ :wink:

**Comment by raisedadead** [comment]
@AryanJ-NYC please make a Pull request to replace the current app, and BTW welcome back to contributing, you have been away a while.

**Comment by thanhlan1912** [comment]
https://m.facebook.com/profile.php?id=100005562164845
