### ISSUE TITLE
Tests do not update after code resets

### ISSUE THREAD

**Issue by hrokr** [FreeCodeCamp/FreeCodeCamp#9184]
#### Issue Description
For some exercises, it's helpful to restart the problem and use FCC handy "reset" button. After the confirmation, the code is reset but the test results are from the previous attempt.

#### Browser Information

* Safari (not tested on other browsers): 
* OS X (10.11): 
* laptop: 

#### Screenshot

Origional code - or code that has been reset and then tested
![origional code - or code that has been reset and then tested](https://cloud.githubusercontent.com/assets/9368785/16128078/31bbab92-33cd-11e6-94ce-5e6aab20f94d.png)

Partially functioning code

![code with mods](https://cloud.githubusercontent.com/assets/9368785/16128130/635619bc-33cd-11e6-81f4-5b5164cbddeb.png)

... then we reset and find the tests haven't updated.

![reset code -- now erroniously saying certain parts work](https://cloud.githubusercontent.com/assets/9368785/16128165/86396eca-33cd-11e6-981a-4843fa8d787a.png)

**Comment by arun1595** [comment]
@Bouncey I would like to take this.
