### ISSUE TITLE
Widen narrow instructions column at standard 1280px laptop width?

### ISSUE THREAD

**Issue by rawreef** [FreeCodeCamp/FreeCodeCamp#9185]
#### Issue Description

I like using FCC in full screen mode on Chrome, but at 1280px the instructions column is very narrow, too narrow to read the code snippet without horizontally scrolling. Can this be widened at this standard laptop width? (See attached screenshot.)

#### Browser Information

* Browser Name, Version: Chrome 51
* Operating System: El Capitan on Macbook Pro 2011
* Mobile, Desktop, or Tablet: Macbook Pro 2011 laptop

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![fcc-layout-narrow](https://cloud.githubusercontent.com/assets/8128944/16129135/4ab08c00-340c-11e6-8504-d715db4ef8b0.png)

**Comment by atjonathan** [comment]
@rawreef I think this could be widened also, especially as a lot of the codemirror width isn't used. We 'd have to narrow it for lower resolutions however.

cc/ @FreeCodeCamp/issue-moderators

**Comment by rawreef** [comment]
@atjonathan The width actually increases anyway when I narrow my browser window to about 1200px and less, as it seems to hit a break point then. So I could just use a narrower browser window, but I would prefer to use full screen mode to fit as much as possible on my screen.

**Comment by dlwebdev** [comment]
On a 3 column page: .col-log-6 kicks in at 1200px. Less than other and col-md-5 applies.
On 2 column page: 
left column is col-md-4 col-lg-3 and right is col-md-8 col-lg-9.

**Comment by dlwebdev** [comment]
The current layouts are:

On a 3 column page: 
   - left column:   col-md-3 col-lg-3
   - middle col:    col-md-5 col-lg-6
   - right col:        col-md-4 col-lg-3
On 2 column page: 
   - left column:   col-md-4 col-lg-3 
   - right column: col-md-8 col-lg-9

**Comment by rawreef** [comment]
@dlwebdev Funny that Bootstrap's largest breakpoint kicks in already on 1280px laptop screens. There's a big difference between a 1280px screen and a 1960+px screen. 

**3-column layout**
So this is really crowded already. I doubt any of those column widths could be changed easily.

**2-column page now:**
left column: col-md-4 col-lg-3 // 1280px laptop gets just 320px and horizontal scrolling is needed to view code examples.
right column: col-md-8 col-lg-9

**Better 2-column page?**
left column: col-md-4 // Wider instructions column at standard 1280px laptop width
right column: col-md-8
max-width: 1600px??? // This would be so the instructions column doesn't get too wide at very large screen widths. No-one needs more than about 1600px width to do Free Code Camp, right?

**Comment by rawreef** [comment]
Should I be making a pull request about this? As it would be my first one, can anyone point me in the right direction?

**Comment by raisedadead** [comment]
@rawreef yes please we would love a pull request. 
Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

/cc @hallaathrad we may guide us with additional inputs.

**Comment by rawreef** [comment]
@raisedadead Thanks for the link and encouragement. Very excited to have just made my [first ever pull request](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9247)
