### ISSUE TITLE
red and blue is bugged

### ISSUE THREAD

**Issue by kelseywest520** [FreeCodeCamp/FreeCodeCamp#9190]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(225%2C0%2C0)%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C%20112%2C%20214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C%2082%2C%2045)%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(225%2C%200%2C%200)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(225,0,0);
  }
  .orchid-text {
    color: rgb(218, 112, 214);
  }
  .sienna-text {
    color: rgb(160, 82, 45);
  }
  .blue-text {
    color: rgb(225, 0, 0);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by benmcmahon100** [comment]
Hey @kelseywest520 i think you may have opened several of the same issue inadvertently. There is also not enough description on this one to help out with the potential bug you may have encountered. Can you expand on the issue you have encountered?

#9189
#9188

**Comment by dwd2010** [comment]
@benmcmahon100, I checked that challenge with her answer.  it is incorrect. I could pass this challenge.  more like it dont have any bug..

So we could wait for her comment...

**Comment by erictleung** [comment]
@kelseywest520 the code you have written is incorrect. Please double check your RGB values and make sure they are exactly the same as what is shown in the table in the challenge. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by kelseywest520** [comment]
I passed it no problem. The code was not incorrect. It was not working
there for a second but then it worked again.

**Comment by kelseywest520** [comment]
The red and blue become bugged sometimes. I passed it with the same code
that is was failing me for.

**Comment by kelseywest520** [comment]
I was not the only person who complained about the red and blue in this
challenge

**Comment by kelseywest520** [comment]
The only reason that the code may have been incorrect is because I tried
changing it to let me pass. However, this NEEDS to be kept up on because I
red several complaints about this. I'm not dumb and it was not incorrect
and not my fault. I would have figured it out before reporting it if it was
my fault.

**Comment by erictleung** [comment]
@kelseywest520 thanks for your feedback. The code you have in #9188 does not pass because you are not using RGB values as the challenge requires. Your issue in #9189 is partially correct where your blue `rgb` values are incorrect but red is correct. You needed to use a value of **255** instead of **225** so that is why your answers are incorrect. I have seen that same mistake in the other issues made on this challenge.

The code you have posted in this issue #9190 is:

```css
<style>
  .red-text {
    color: rgb(225,0,0);
  }
  .orchid-text {
    color: rgb(218, 112, 214);
  }
  .sienna-text {
    color: rgb(160, 82, 45);
  }
  .blue-text {
    color: rgb(225, 0, 0);
  }
</style>
```

and it is incorrect. If you have code that is correct and does not pass the challenge, can you please post it so that we may thoroughly diagnose the issue? Thanks for your patience.

**Comment by Skyesdalimit** [comment]
![image](https://cloud.githubusercontent.com/assets/21270436/18029604/60472a22-6c94-11e6-88d1-94aee409881f.png)


i think i have found a bug

**Comment by Skyesdalimit** [comment]
both red and blue that is, the others are fine

**Comment by JHernandez1** [comment]
I am having the same issue with this one, the red and the blue wont process.
