### ISSUE TITLE
app crash, missing .env file

### ISSUE THREAD

**Issue by keepcurrent** [FreeCodeCamp/FreeCodeCamp#9191]
It's my first time to start the application. I got an error message when run 'gulp', the last step in the setup.

I made a copy of 'sample.env' in the FreeCodeCamp folder, and tried to change the file name to '.env' as the instruction said, but the system doesn't let me leave the file name blank. What other names can I use for this .env file? What should I change in this file? I am totally new to the server and back end. 

![image](https://cloud.githubusercontent.com/assets/6341472/16138706/613e9d5c-340e-11e6-82d6-5336db9cb4d6.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by robjloranger** [comment]
try naming the file ```.env.```

**Comment by raisedadead** [comment]
@keepcurrent you are using windows explorer to rename, instead use command line, (using the git bash is also fine)

`cp sample.env .env`

This is mentioned in the instructions and is recomended way.

alternatively on a windows command prompt : `copy sample.env .env`
