### ISSUE TITLE
Understanding Uninitialized Variables 

### ISSUE THREAD

**Issue by etacalpha** [FreeCodeCamp/FreeCodeCamp#9193]
Understanding Uninitialized Variables 

"Instructions
Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined." 

If you set var c = "I am a" it will not pass as it is looking for var c = " I am a String!"

Chrome
windows 10 
Surface Pro 3 

![screenshot 2](https://cloud.githubusercontent.com/assets/18453591/16139283/5e26dcf4-340b-11e6-9134-e1b16de2b083.png)

**Comment by etacalpha** [comment]
Disregard I did not read fully

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
