### ISSUE TITLE
Email verification link doesn't work in at least some cases

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9195]
#### Issue Description
We are getting an alarming number of emails from campers who can't verify their emails. They get this error:

{"error":{"name":"Error","status":400,"message":"Invalid token: ["<token>","statusCode":400,"code":"INVALID_TOKEN"}}

**Comment by raisedadead** [comment]
I could not reproduce this on the local setup. 
Can we have access to the emails that did not work for the campers?

Anyone facing this please PM me the mail on Gitter: https://gitter.im/raisedadead
