### ISSUE TITLE
You need an a element that links to http://freecatphotoapp.com does not show complete

### ISSUE THREAD

**Issue by mm3ss678** [FreeCodeCamp/FreeCodeCamp#9198]
everything shows to be done and the hyper-link looks to be in place but for some reason this does not finish. Is there something out of place?

CatPhotoApp

Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.

Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. when I click on " cat photos" the link takes me to: http://webhelper.centurylink.com/index.php?origURL=http%3A//www.freecatphotoapp.com/&r=&bc=
thanks for your assistance.

"View more" "cat photos"
Challenge [Link to External Pages with Anchor Elements](https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements#?solution=%0A%3Clink%20%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp.com%3E%20link%20to%20Free%20Code%20Camp%3C%2Fa%3E%0A%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link <a href="http://freecatphotoapp.com> link to Free Code Camp</a>

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<p>"View more" <a href="http://www.freecatphotoapp.com">   "cat photos" </a> </p>


```

**Comment by raisedadead** [comment]
> `<link <a href="http://freecatphotoapp.com> link to Free Code Camp</a>`

The above line of code is not correct.

> `http://webhelper.centurylink.com/index.php?origURL=http%3A//www.freecatphotoapp.com/&r=&bc=`

This is not our's either. 
Please check if you are using any extensions or have a infected PC, which are injecting them into the webpage.

This can also be the case if you copy pasted the code from someplace, that already had the above.

**Comment by mm3ss678** [comment]
changed to: <link <a href="http://freecatphotoapp.com"> link to Free cat photos apps</a>.
When I type in HTTP://www.freecatphotoapp.com I get sent to:http://webhelper.centurylink.com/index.php?origURL=http%3A//www.freecatphotoapp.com/&r=&bc= by goole chrome when using a mac computer.

**Comment by raisedadead** [comment]
> When I type in HTTP://www.freecatphotoapp.com I get sent to:http://webhelper.centurylink.com/index.php?origURL=http%3A//www.freecatphotoapp.com/&r=&bc= by goole chrome when using a mac computer.

Again this is not us, please run an antivirus / anti malware program on your PC and disable the browser extensions.

Can you try the below :
> http://freecatphotoapp.com

I get this (as expected)
![image](https://cloud.githubusercontent.com/assets/1884376/16150677/2d8bd09e-34b6-11e6-8cda-41edf1304e09.png)

**Comment by mm3ss678** [comment]
Thank you, century link is my internet access provider and is not a virus so to speak, lol and was attempting to take a dead link and provide something for me to choose from.

I finally got the answer to where I was off in my thinking of this a being a (Link) and not a (P) element entry from Romeo. It will take some time for this 60 year old brain to work around these various differences.
