### ISSUE TITLE
Create CatPhotoApp to host on freecatphotoapp.com

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9202]
View the progress here: https://github.com/atjonathan/catphotoapp

**Comment by AryanJ-NYC** [comment]
Need any help with this? I'd love to contribute.

**Comment by atjonathan** [comment]
@AryanJ-NYC, do you have any experience with using firebase? If so ping me on gitter :smiley: I have already started working on this, but it's unfinished :stuck_out_tongue_winking_eye:

**Comment by atjonathan** [comment]
This has been finished. Tagging @BerkeleyTrue to host it on the appropriate domain when we have finished testing the rectification :+1:
