### ISSUE TITLE
Incrementing code Issue

### ISSUE THREAD

**Issue by emontag** [FreeCodeCamp/FreeCodeCamp#9206]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = ++myVar;


```
Output: myVar = 88

What is wrong: myVar = myVar should be changed

Thank you.

**Comment by erictleung** [comment]
@emontag please review the instructions again for the answer to your issue.

> The entire line becomes `i++;`, eliminating the need for the equal sign.

If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
