### ISSUE TITLE
What's wrong with my code?

### ISSUE THREAD

**Issue by codecampergg** [FreeCodeCamp/FreeCodeCamp#9209]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunction(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20it's%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20it's%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Afunction%20trueOrFalse(wasThatTrue)%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%0A%20%20if(trueOrFalse)%20%7B%0A%20%20%20%20return%20%22Yes%2C%20that%20was%20true%22%3B%0A%20%20%7D%0A%20%20%20%20return%20%22No%2C%20that%20was%20false%22%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtrueOrFalse(true)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourFunction(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
function trueOrFalse(wasThatTrue) {

  // Only change code below this line.
  
  if(trueOrFalse) {
    return "Yes, that was true";
  }
    return "No, that was false";
  
  // Only change code above this line.

}

// Change this value to test
trueOrFalse(true);

```

**Comment by luongthomas** [comment]
Hello.  I don't believe there is an issue with this challenge but I will tell you why the provided code isn't working.  The condition "trueOrFalse" that is written in the if block is supposed to be the variable "wasThatTrue".  

"wasThatTrue" is the argument being passed in as either true or false).  "trueOrFalse" is the name of the function, which is not what we want to use in a conditional statement like ours here.

**Comment by erictleung** [comment]
@codecampergg I would heed @luongthomas suggestion to solve the challenge. Additionally, the help room linked will be of greater help than here as this is not a place for coding help. So if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by frogshelp** [comment]
ok i just did this one and i had exact same issue as it states change trueorfalse to test  but however it still onc changed does not make it pass matter fact it says test is not defined  so i took luongthamas comment and used it  i  did a lil changing  so where u messed up like i had did  where our if(trueOrFalse) is has to be changed so example take the setup of function trueOrFalse(wasThatTrue) and place it above your first return  and remove the function trueOrFalse off the end of it  and replace it with -->if<-- then it will pass

**Comment by frogshelp** [comment]
@ erictleung that help room ignores ur request more often then not thiers been many times i asked for help an sat literally 3 hrs waiting and reposted my code and request for help 4 times and still got no help so thier needs to be a place such like this as an alternitive for help  so ur constant comments of go thier instead of here is just about useless as getting help in the help room
