### ISSUE TITLE
control + enter

### ISSUE THREAD

**Issue by matthewsvm** [FreeCodeCamp/freecodecamp#921]
Challenge http://www.freecodecamp.com/challenges/bonfire-falsey-bouncer has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I don't know if I am doing it wrong or if it is because I am on a mac, but in all the bonfires, neither "control + enter" nor "command + enter" runs the code.  

Cheers!
Matthew

**Comment by LumenTeun** [comment]
Is your cursor in the editor window? If not, put it there. If it's still not working, from what I've seen, the code sometimes doesn't run if there's a fatal error in your code or if you've crashed some script by programming an infinite loop. Does a complete refresh restore functionality?

Also, which browser are you using?

**Comment by matthewsvm** [comment]
Thanks.  It works...just didn't realize the cursor had to be in the editor window.

**Comment by LumenTeun** [comment]
Yeah, I think I saw that the <C-Enter> functionality is added as a custom keybinding in CodeMirror right now. This might be changed when FCC is reactified and issue #240 is completed. Remember to close this issue if it's no longer, ou know, an issue.
