### ISSUE TITLE
rgb code for orchid not working. unable to proceed further

### ISSUE THREAD

**Issue by rizTech** [FreeCodeCamp/FreeCodeCamp#9214]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(255%2C0%2C0)%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C112%2C214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C82%2C45)%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C0%2C255)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(255,0,0);
  }
  .orchid-text {
    color: rgb(218,112,214);
  }
  .sienna-text {
    color: rgb(160,82,45);
  }
  .blue-text {
    color: rgb(0,0,255);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by atjonathan** [comment]
@rizTech, your code passes for me fine!

**Comment by rizTech** [comment]
![rgb code issue](https://cloud.githubusercontent.com/assets/19963381/16170205/918e7d3c-3568-11e6-8409-6baf3ec8b4a6.png)

**Comment by rizTech** [comment]
What cld b the issue with my code?????

**Comment by atjonathan** [comment]
The code you provided us in the issue description completes fine.
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by rizTech** [comment]
thanks! atjonathan
