### ISSUE TITLE
在编辑器中鼠标无法方向键没有作用

### ISSUE THREAD

**Issue by haira1987** [FreeCodeCamp/FreeCodeCamp#9215]
在编辑器中鼠标无法方向键没有作用

**Comment by Bouncey** [comment]
@haira1987 请提供您有问题的挑战URL。

**Comment by atjonathan** [comment]
@haira1987, if you are referring to https://freecodecamp.cn/, please open an issue on their repository.

**Comment by haira1987** [comment]
我已知道原因了，应该是网络延迟问题。多谢大家
