### ISSUE TITLE
Record collection. verify existant array and create

### ISSUE THREAD

**Issue by Imaurea** [FreeCodeCamp/FreeCodeCamp#9218]
// Setup
var collection = {
    2548: {
      album: "Slippery When Wet",
      artist: "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    2468: {
      album: "1999",
      artist: "Prince",
      tracks: [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    1245: {
      artist: "Robert Palmer",
      tracks: [ ]
    },
    5439: {
      album: "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line

function updateRecords(id, prop, value) {
    if (value !== "") {
      if (prop !== "tracks") {
        collection[id][prop] = value ;
      }
      else {
        if (typeof "tracks" === 'undefined') {
         var tracks = new Array() ;
        }
        collection[id][prop].push(value) ;
      }
    if (prop === "tracks")  {
      delete collection[id][prop] ;
    }
 
  return collection;
}
}
updateRecords(5439, "tracks", "Take a Chance on Me") ;

I get the error : collection[id][prop] is undifined
Could you please help me ?

**Comment by arun1595** [comment]
This is not the space for asking help related to challenges. Head over to [Help Chatroom](https://gitter.im/FreeCodeCamp/Help) if you need help with challenges.

**Comment by Imaurea** [comment]
sorry. I didn't know it.
thank you very much
