### ISSUE TITLE
Challenge: Use CSS selectors has a bug...

### ISSUE THREAD

**Issue by krissrocksu** [FreeCodeCamp/FreeCodeCamp#9219]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20red%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: red;}
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```
I can't advance, it says my code has to be blue? The code is exactly as needed...

Here is a dropbox screenshot:
https://www.dropbox.com/s/ndv7o8pig0kln98/Screen%20Shot%202016-06-18%20at%2010.04.57%20AM.png?dl=0

**Comment by BerkeleyTrue** [comment]
Please use the help chat rooms/forums when you get stuck.

The issue tracker is for reporting issue's only.

Happy Coding.

**Comment by mynameisjeff010** [comment]
i think you shoud delete </style> becuase it is just closing it down

**Comment by mynameisjeff010** [comment]
sorry for my english

**Comment by mynameisjeff010** [comment]
h2 {color: red;} has to be changet to   h2 {color: blue;}
