### ISSUE TITLE
anchor

### ISSUE THREAD

**Issue by MugiLarson** [FreeCodeCamp/FreeCodeCamp#9222]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
