### ISSUE TITLE
Whats next Please Help

### ISSUE THREAD

**Issue by cao2828** [FreeCodeCamp/FreeCodeCamp#9223]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Ch1%3EHello%20World%3Ch1%3E%0A%3Ch2%3ECatPhotoApp%3Ch2%3E%0A%3Cp%3EI'm%20a%20Pussy%20Cat%20tag!%3Cp%2F%3E%0A%3Cp%3EI'm%20a%20p%20tag!%3C%2Fp%3E%0A%20%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.1 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<h1>Hello World<h1>
<h2>CatPhotoApp<h2>
<p>I'm a Pussy Cat tag!<p/>
<p>I'm a p tag!</p>
  
```

**Comment by atjonathan** [comment]
> Your p element should have the text "Hello Paragraph".

Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
