### ISSUE TITLE
TypeError: 0 is read-only

### ISSUE THREAD

**Issue by kvanderkamp** [FreeCodeCamp/FreeCodeCamp#9227]
#### Caesars Cipher

[https://www.freecodecamp.com/challenges/caesars-cipher#?solution=...](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20str.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20var%20charCode%20%3D%20str.charCodeAt(i)%3B%0A%20%20%20%20if(charCode%20%3E%3D%2065%20%26%26%20charCode%20%3C%2078)%20%7B%0A%20%20%20%20%20%20charCode%20%2B%3D%2013%3B%0A%20%20%20%20%7D%20else%20if%20(charCode%20%3E%3D78%20%26%26%20charCode%20%3C%2091)%20%7B%0A%20%20%20%20%20%20charCode%20-%3D%2013%3B%0A%20%20%20%20%7D%20%0A%20%20%20%20str%5Bi%5D%20%3D%20String.fromCharCode(charCode)%3B%0A%20%20%7D%0A%20%20return%20str%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A)

#### Running test gives TypeError: 0 is read-only
When testing script in the browser console it works fine. This error appears ONLY when testing on FCC with the solution from the link above. After some debugging it appears that the error is caused by `` str[i] = ...``

#### Browser Information
* Browser Name, Version: Firefox 47.0 
* Operating System: Linux Mint 17.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

function rot13(str) { // LBH QVQ VG!
  for (var i = 0; i < str.length; i++) {
    var charCode = str.charCodeAt(i);
    if(charCode >= 65 && charCode < 78) {
      charCode += 13;
    } else if (charCode >=78 && charCode < 91) {
      charCode -= 13;
    } 
    str[i] = String.fromCharCode(charCode);
  }
  return str;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

#### Screenshot
![screenshot from 2016-06-19 00 02 52](https://cloud.githubusercontent.com/assets/13351722/16173965/33aae34c-35b1-11e6-919e-41e2a4ad16cf.png)

**Comment by dhcodes** [comment]
@kvanderkamp you say you only get this error on FCC. Does the code work elsewhere? The reason I ask is because it seems like this error is due to a string being immutable (unable to be changed) in Javascript. By doing str[0] = ... you are trying to assign a new value to the first letter of the string which is not possible in Javascript.

**Comment by kvanderkamp** [comment]
I'm curious why it doesn't give a TypeError in the browser console or this [CodePen](http://codepen.io/kvanderkamp/pen/KMVwzB), which got me confused. You're right about trying to replace a letter, I'll find another way to do this.

**Comment by kvanderkamp** [comment]
I suppose this issue can be discarded.
