### ISSUE TITLE
Examples often don't line up with or match expectations. Daunting and disappointing. 

### ISSUE THREAD

**Issue by mrburks** [FreeCodeCamp/FreeCodeCamp#9228]
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20%0A%20%20return%20%22Change%20Me!%22%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22gift%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.2000 Chrome/30.0.1599.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  
  return "Change Me!";
}

// Test your code by modifying these values
checkObj("gift");

```
Example

var myObj = {
  top: "hat",
  bottom: "pants"
};
myObj.hasOwnProperty("top");    // true
myObj.hasOwnProperty("middle"); // false

If you look at the code in the example, which BTW is intended to show the Learner how an operation or a particular task is done; If you provide this example, in this manner, then expect the learner to write his/her code in a completely different way is not only misleading to the user, it is unfair.

**Comment by sanskar-modi** [comment]
i don't think example is misleading to user. example clearly shows how to check for a key in object i.e using `hasOwnProperty` method, you just have to put that line in function and change the return statement. They already taught functions before this, so i don't understand what exactly the problem is?

**Comment by Bouncey** [comment]
@mrburks If the solution was explicitly provided in the instructions, the learner would simply copy/paste and move on to the next challenge. This would hamper the learning process. 

If you think the instructions could be improved to explain the use of `hasOwnProperty` better, please discuss it here.
