### ISSUE TITLE
typo in "Pair Program on Bonfires" waypoint

### ISSUE THREAD

**Issue by tdugger** [FreeCodeCamp/freecodecamp#923]
look for 
"Your pair will have their own cursor, and will be able to type text on his or her and keyboard."

Remove the "and" after "his or her".

**Comment by kurzninja** [comment]
You should fork and fix this, then submit a pull request for the correction.

**Comment by NatashaHaggard** [comment]
Fixed, opened a pull request - https://github.com/FreeCodeCamp/freecodecamp/pull/1115
