### ISSUE TITLE
Word Blanks Instructions Are Unclear

### ISSUE THREAD

**Issue by eclecticeasel** [FreeCodeCamp/FreeCodeCamp#9233]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myProNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20result%20%3D%20myNoun%20%2B%20myProNoun%20%2B%20myAdjective%20%2B%20%22%20little%22%20%2B%20myVerb%20%2B%20%22%20hit%22%20%2B%20myAdverb%20%2B%20%22%20slowly%22%3B%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22little%22%2C%20%22%20tool%22%2C%20%22%20very%22%2C%20%22%20licked%22%2C%20%22%20longingly%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8172.47.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myProNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result = myNoun + myProNoun + myAdjective + " little" + myVerb + " hit" + myAdverb + " slowly";

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("little", " tool", " very", " licked", " longingly");
```

**Comment by erictleung** [comment]
@eclecticeasel thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: reset your code; it appears you changed the code at the top and added an additional parameter `myProNoun`. Happy coding!

**Comment by eclecticeasel** [comment]
This challenge is written so as to be easily confusing. You can add the non-word characters in the wordBlanks definition at the bottom and the challenge still works fine in the output and that makes the error message seem wrong. 

I suggest a change to the instructions and error report  so it is not so confusing. My recommendations are in brackets.

INSTRUCTIONS
"You will also need to provide additional strings [in the function], which will not change, [and must be] in between [all of] the provided words."

ERROR
"should contain all of the passed words [that are] separated by non-word characters [in the function] (and any additional words in your madlib)."

**Comment by erictleung** [comment]
@eclecticeasel thanks for your suggestions. Looking at the challenge again, it does appear a bit confusing when first looking at it.

Here's my modification to your suggestion,

> ### Instructions
> ...
> You will also need to **use** additional strings, which will not change, **and must be** in between **all of** the provided words. **The output should be a complete sentence.**
> 
> We have provided a framework for testing your results with different words. The tests will run your function with several different inputs to make sure all of the provided words appear in the output, as well as your extra strings.
> ### Error Messages
> ...should contain all of the passed **in** words separated by non-word characters (and any additional words in your madlib).

**Comment by atjonathan** [comment]
**To the contributor that takes this up:**

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by GreyhoundIt** [comment]
Id like a go at this please :)

**Comment by siguniang** [comment]
![25](https://cloud.githubusercontent.com/assets/24384921/21541463/8603e4a8-cdf1-11e6-8e6c-a7cd0a8f52ef.png)
