### ISSUE TITLE
Show the Local Weather 

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [FreeCodeCamp/FreeCodeCamp#9235]
Not an issue so much as a notification. I was going back and checking up on some of my older projects and making fixes where things had broken. I found the weather app had broken and the cause was Chrome no longer supports geo locations outside of HTTPS connection. It works fine in other browsers. Might need to adjust this challenge.

#### Challenge Name
Show the Local Weather 

#### Issue Description
Chrome no longer supports geo locations outside of HTTPS connection, does not affect other browsers.

#### Browser Information
Chrome

**Comment by dhcodes** [comment]
@MichaelLeeHobbs It's a known issue and there are multiple issues referencing it. See #9079 and #9145. I do agree that FCC should probably update the instructions to suggest location over ip for chrome, but that discussion is still ongoing.

**Comment by atjonathan** [comment]
Closing in favour of #9145 and #9079
