### ISSUE TITLE
Free Code Camp logo in nav bar should redirect to next challenge

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9238]
#### Issue Description
Currently the Free Code Camp logo button in the navbar redirects to '/' which redirects to the home page if campers are unauthenticated and the /challenges/next-challenge route if they are authenticated. Rather than send campers to '/' we can just send them directly to /challenges/next-challenge which will go ahead and get them started, even if they haven't authenticated. 

We recently discovered that 25% of people who visit or landing page click on this logo for some reason. We don't know why, but it doesn't make any sense to send them right back to the landing page.

**Comment by erictleung** [comment]
@QuincyLarson correct me if I'm wrong but to resolve this issue, we need to change [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/partials/navbar.jade#L6) to:

```jade
a.navbar-brand(href='/challenges/next-challenge')
```

**Comment by VDecalS** [comment]
@QuincyLarson  FWIW - As a newbie, I tried clicking on the logo button when looking for the gitter PM button.  The "help" chat room only opens a side bar that doesn't include gitter navigation.  For someone new like me, navigating a service never before used includes a lot of trial and error.

**Comment by Manish-Giri** [comment]
I can give this is a shot, if it's still open for fixing! I have just 1 PR in so far, so I guess I'm still almost a first timer.
