### ISSUE TITLE
Where art thou - Intermediate Algorithm 

### ISSUE THREAD

**Issue by MD91** [FreeCodeCamp/FreeCodeCamp#9239]
I'm being very pedantic: 

1) The quote is not 'where art thou?', it's 'wherefore art thou?' 
2) The meaning is not 'where are you?', but 'why are you?' i.e. 'why were you born a Montague?'

Challenge [Where art thou](https://www.freecodecamp.com/challenges/where-art-thou) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/537.86.5</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function whereAreYou(collection, source) {
  // What's in a name?
  var arr = [];
  // Only change code below this line
  
  
  // Only change code above this line
  return arr;
}

whereAreYou([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" });

```

**Comment by raisedadead** [comment]
@MD91 thanks a lot for the issue, would you mind pointing us to reference to support the above, for instance I searched and found this

http://www.urbandictionary.com/define.php?term=Where%20Art%20Thou%3F

according to which the naming is correct. But we could be wrong too, so it will be great if you could drive us in the right direction.

Thanks.

**Comment by raisedadead** [comment]
Okay, never mind I found it
http://www.dictionary.com/browse/romeo-romeo-wherefore-art-thou-romeo

/cc @FreeCodeCamp/issue-moderators worth pursuing or bikeshedding?

**Comment by Bouncey** [comment]
Good for first timers?

Change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/83868f9f591a9752f0b74fa261a24793df507755/seed/challenges/01-front-end-development-certification/intermediate-bonfires.json#L172) challenge.

Challenge title changed to:
>Wherefore art thou?

Challenge function changed to:
>whatIsInAName

**Comment by Manish-Giri** [comment]
I'd be happy to take this up, if it is still up for fixing.

**Comment by amfische** [comment]
I noticed this change erased the code I created for this challenge :(

**Comment by BKinahan** [comment]
@amfische your code is still available encoded within this link (which I found under 'View Solution' for the original 'Where art thou' challenge on your profile page):
```
https://www.freecodecamp.com/challenges/Where%20art%20thou?solution=%0Afunction%20whereAreYou(collection%2C%20source)%20%7B%0A%20%20%2F%2F%20What%27s%20in%20a%20name%3F%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20prop%20%3D%20Object.keys(source)%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20collection.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20for%20(j%20%3D%200%3B%20j%20%3C%20prop.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(collection%5Bi%5D.hasOwnProperty(prop%5Bj%5D))%20%7B%0A%20%20%20%20%20%20%20%20if%20(collection%5Bi%5D%5Bprop%5Bj%5D%5D%20%3D%3D%3D%20source%5Bprop%5Bj%5D%5D)%20%7B%0A%20%20%20%20%20%20%20%20%20%20if%20(arr.indexOf(collection%5Bi%5D)%20%3D%3D%3D%20-1)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20arr.push(collection%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20arr.splice(arr.indexOf(collection%5Bi%5D)%2C%201)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20arr.splice(arr.indexOf(collection%5Bi%5D)%2C%201)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20arr%3B%0A%7D%0AwhereAreYou(%5B%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%20%7D%2C%20%7B%20%22a%22%3A%201%20%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%2C%20%22c%22%3A%202%20%7D%5D%2C%20%7B%20%22a%22%3A%201%2C%20%22c%22%3A%202%20%7D)%3B%0A%2F%2FwhereAreYou(%5B%7B%20first%3A%20%22Romeo%22%2C%20last%3A%20%22Montague%22%20%7D%2C%20%7B%20first%3A%20%22Mercutio%22%2C%20last%3A%20null%20%7D%2C%20%7B%20first%3A%20%22Tybalt%22%2C%20last%3A%20%22Capulet%22%20%7D%5D%2C%20%7B%20last%3A%20%22Capulet%22%20%7D)%3B%0A
```

Maybe it can be an interesting programming challenge for you to convert that back to readable code :)
(Or you can simply change the first occurrence of `Where` in the URL to `Wherefore` to match the new title, and follow the URL to enter the old code into the new challenge.)

**Comment by amfische** [comment]
Ah nice catch @BKinahan. I think I'll just follow the URL instead of trying to convert it back to code hah thanks a bunch!
