### ISSUE TITLE
Missing tests in "Convert HTML Entities" bonfire

### ISSUE THREAD

**Issue by kurzninja** [FreeCodeCamp/freecodecamp#924]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This bonfire seems to be missing assertion tests for all the different test cases outlined in the instructions. It currently is only testing the case of the ampersand (&) and is leaving out the <, >, ', and " cases. Suggest adding another assertion or assertions to test the rest of these cases.

**Comment by LumenTeun** [comment]
Just for logging purposes, this was discussed in #903.

I'm currently not at a computer, but if someone wants to assign me, I could fix this as soon as I can, which /should/ be tonight.
