### ISSUE TITLE
Show campers how to add name to certificate

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9240]
#### Issue Description

We frequently get emails from campers complaining that their name doesn't show up on their certificates. I respond to them with the following instructions:

"We pull all your biographical information directly from GitHub. So you just need to add your name to your GitHub account. Then go back to your Free Code Camp code portfolio and click the "update my profile from GitHub" button. Then your name will appear on your certificate.

Instead of having to answer these emails, if a camper doesn't have a name, we could just put a short message like this right on their certificate where there name would normally go. I propose the following copy for this, which is short enough to avoid an ugly line wrap:

"Add name on GitHub then update FCC"

You'll do this in boot/user.js in the showCert function.

#### Screenshot
![](https://www.evernote.com/l/Ar_-08-MMpdFhqdWJ7LG48XTeabW-m3BePQB/image.png)

**Comment by atjonathan** [comment]
**To contributor:**

Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by QuincyLarson** [comment]
@atjonathan yes - you're right. I opened this same issue a month ago and forgot about it.
