### ISSUE TITLE
Change the font size of an element

### ISSUE THREAD

**Issue by AbdusSamiPatel** [FreeCodeCamp/FreeCodeCamp#9241]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A16px%3B%0A%20%20%7D%0A%20%20p2%7B%0A%20%20%20%20font-size%3A16px%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%20%20%0A%3Cp2%3EKitty%20Ipsum%20text%20Purr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp2%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  p {
    font-size:16px;
  }
  p2{
    font-size:16px;
  }
  
</style>


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  
<p2>Kitty Ipsum text Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p2>

```

**Comment by MarioComputer** [comment]
P2 is and unnecessary class. All paragraphs will respond to p class
it would look like
`<style>
  p {
    font-size:16px;
  }

</style>


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p2>Kitty Ipsum text Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p2>`

**Comment by MarioComputer** [comment]
let me know if that did the trick!

**Comment by AbdusSamiPatel** [comment]
Thanks

**Comment by MarioComputer** [comment]
Anytime Mate

**Comment by erictleung** [comment]
@AbdusSamiPatel sounds like @MarioComputer was able to help you out with the issue. Please note that if you get stuck with a challenge, the [Gitter Help Room](https://gitter.im/FreeCodeCamp/Help) is where you should be asking for help first. Happy coding!

**Comment by AbdusSamiPatel** [comment]
@MarioComputer it's not working. what i do?

**Comment by MarioComputer** [comment]
it's the last line this time, i forgot to replace p2 with p. check it now
```
<style>
  p {
    font-size:16px;
  }

</style>


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Kitty Ipsum text Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by AbdusSamiPatel** [comment]
5 out of 4 items are cleared but only one item can not be resolve
*) Do not add a class attribute to the second p element.

**Comment by MarioComputer** [comment]
you forgot the class red-text
```
<style>
 .red-text {
    color:red;
  }
  
  p{
    font-size: 16px;
  }

  
</style>


<p class = "red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  
<p>Kitty Ipsum text Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by MarioComputer** [comment]
Sorry i didn't open the challange at first.

**Comment by AbdusSamiPatel** [comment]
Thank you so much

**Comment by MarioComputer** [comment]
No problem my friend. We are all learning here ;)

**Comment by FourPines** [comment]
This was really helpful.  I was stuck for a while on that one too.  Thanks MarioComputer.

**Comment by MarioComputer** [comment]
Glad I could help!
