### ISSUE TITLE
Guys am new to this platform so help me become a developer by showing me how to uncomment HTML

### ISSUE THREAD

**Issue by piuswangwelo** [FreeCodeCamp/FreeCodeCamp#9242]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%3C!--hello%20world--%3E%0A%3C!--catPhotoApp--%3E%0A%3C--hello%20paragraph--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--hello world-->
<!--catPhotoApp-->
<--hello paragraph-->
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
```

**Comment by acsrujan** [comment]
Uncomment HTML is tutorial to teach you how to use comments in HTML.
As mentioned on the left panel, anything written between **** 
(notice that start has an exclamation and end doesn't) is considered as comment.

In the exercise mentioned, you're supposed to uncomment `h1`, `h2` and `p`. 

`<--hello paragraph-->` is not a HTML comment.
`<!--hello world-->` is a comment but not necessary in this exercise. 

Uncomment h1 means, replace 
`<!-- <h1> Hello World <h2> -->`

**Comment by raisedadead** [comment]
Thanks for reporting this. GitHub Issues are for reporting bugs on the website only.
Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to Coding.

Happy Coding!
