### ISSUE TITLE
run tests not working

### ISSUE THREAD

**Issue by mayur7099** [FreeCodeCamp/FreeCodeCamp#9244]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3Ablue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2 style="color:blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by arun1595** [comment]
The instruction says 'Change your h2 element's style so that its text color is **red**'.
If you need help with the challenges, head over to [Help room](https://gitter.im/FreeCodeCamp/Help)

**Comment by Bouncey** [comment]
Please follow the instructions for the challenge. You might find a hint in the test suite below the `run tests` button.

Please use the `help` button under the `run tests` button for help with the challenge, Github issues are for issues/bugs with FreeCodeCamp itself, not for challenge help.
