### ISSUE TITLE
Challenge Video Instructions Inconsistant with Written Instructions

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9245]
Challenge [Start a Nodejs Server](https://www.freecodecamp.com/challenges/start-a-nodejs-server) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The video instructions say to use your previous node workspace for this challenge, but written instructions asks you to create a new blank workspace and install npm.

**Comment by erictleung** [comment]
Seems related to #5294.

**Comment by Bouncey** [comment]
Agreed. Closing this duplicate
