### ISSUE TITLE
Reduce font size in Field Guide on mobile

### ISSUE THREAD

**Issue by ahstro** [FreeCodeCamp/freecodecamp#925]
The font size used in the article index of the field guide appears quite large (fig. 1), we should consider reducing to the same size used on the Map page (fig. 2).

Fig. 1
<img src='http://i.imgur.com/cwpIn5v.jpg' alt='' title='Fig. 1' width="50%" />

Fig. 2
<img src='http://i.imgur.com/XwHuHqD.jpg' alt='' title='Fig. 2' width="50%" />

**Comment by BerkeleyTrue** [comment]
Field guides have been removed.

Happy Coding!
