### ISSUE TITLE
Solution getting overwritten for earlier solved challenge

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#9250]
I solved the palindrome problem just 1 day ago with a one liner RegEx.

But now, I have this solution available when I open the palindrome challenge in FCC main site:
```js
function reverseString(str) {
  str = str.split("").reverse().join("");
  return str;
}

function palindrome(str) {
  palistr = str.toLowerCase();
  testStr = palistr.replace(/[^a-z0-9]/g, "");
  if ( testStr == reverseString(testStr)) {
    return true;
  } else {
    return false; 
  }
}


palindrome("A man, a plan, a canal. Panama");
```

---

I don't know how did this come to be in the code editor, but this is not a solution I ever wrote, nor would I ever condone a solution this ghastly.

**Comment by BerkeleyTrue** [comment]
Can't replicate. 

Going to your profile and loading your solution gives me

```js

function palindrome(str) {
  // Good luck!
  return str.toLowerCase().replace(/[\W_]/g, '') === str.toLowerCase().replace(/[\W_]/g, '').split('').reverse().join('');
}

palindrome("eye");
```
Going to your profile also shows that you have only submitted your solution once so it is impossible for your solution to be coming from an earlier solution if you only have one.
![camper_alayek_s_code_portfolio___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/16207877/4b761030-36e4-11e6-80c5-1ec344a0a531.png)

**Comment by alayek** [comment]
I opened this from [map](https://freecodecamp.com/map). 

![palindrome](https://cloud.githubusercontent.com/assets/5607371/16208053/fb03f972-374d-11e6-97f8-26ea18960cb5.png)

Here's a screenshot of this.

**Comment by BerkeleyTrue** [comment]
Have you tried loading it from your profile page?

**Comment by alayek** [comment]
Yes, when I open from my profile, it shows me my solution. But otherwise, when I open from map, it gives this solution.

If I recall correctly, the Wiki probably has this solution as one of the basic solutions.

**Comment by BerkeleyTrue** [comment]
So just to clarify.

Open challenge from profile.
see proper solution
Close page
open solution from map
see unknown code

Is that correct?

**Comment by alayek** [comment]
Yes, that is correct.

**Comment by BerkeleyTrue** [comment]
I can't replicate. I see the same solution regardless. Can you try clearing your localStorage and then repeating the steps above.

**Comment by alayek** [comment]
Weird, now that I opened from map page, I am getting my solution. I checked from incognito mode, the basic problem template loads up.

**Comment by BerkeleyTrue** [comment]
Cool. sounds like everything is working as expected.

Happy Coding
