### ISSUE TITLE
For git challenge, use repository name other than hello-world

### ISSUE THREAD

**Issue by restartedwill** [FreeCodeCamp/FreeCodeCamp#9251]
#### Challenge Name

https://www.freecodecamp.com/challenges/save-your-code-revisions-forever-with-git

#### Issue Description

If someone is brand new to coding with git, the getting started suggested task on github is to make a "hello-world" repository. But the referenced challenge uses the same name for its repository. We should use some other name in the challenge. I spent a great deal of time trying to deal with an existing repository with a file already created when using the challenge, ultimately blowing away the getting started repository and then starting over with the challenge.

**Comment by atjonathan** [comment]
@restartedwill, you should raise an issue with https://github.com/jlord/git-it. Thanks for bringing this up!
