### ISSUE TITLE
I think is a bug. 

### ISSUE THREAD

**Issue by CarlosDizz** [FreeCodeCamp/FreeCodeCamp#9252]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%22%5C%5C%20%5Ct%20%5Ct%20%5Cr%20%5Cn%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr ="\\ \t \t \r \n"; // Change this line



```

**Comment by CarlosDizz** [comment]
Solved! I didn't read properly. Sorry.

**Comment by arun1595** [comment]
@CarlosDizz Please close the issue.
