### ISSUE TITLE
Improve instructions for Understanding case sensitivity in variables challenge

### ISSUE THREAD

**Issue by arun1595** [FreeCodeCamp/FreeCodeCamp#9254]
#### Understanding Case Sensitivity in Variables

It looks like a learner had problem in understanding the instructions for [this](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables) challenge.

The instructions currently read 
> Fix the variable declarations and assignments so their names use camelCase.

Maybe we can change it along the lines of  
> Modify the existing declarations and assignments so their names use camelCase. 
> In other words, do not create any new variables; just change and fix existing incorrect variable names in the declaration and assignment statements.

**Comment by erictleung** [comment]
[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b4cf1037d53fc614ddfde615ada46d02ddf5eabb/seed/challenges/01-front-end-development-certification/basic-javascript.json#L238) needs to be changed to something similar to above.

To whoever picks this up, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by Manish-Giri** [comment]
I can take this up! I do have another PR in progress, but it's not yet merged, so I'm *technically* still a first timer, I guess!

**Comment by okputus** [comment]
I would like to help. Haven't commited anything before.
