### ISSUE TITLE
Cannot go from Task 22 to Task 23. Because, there is no status bar in the left bottom side of the page.

### ISSUE THREAD

**Issue by ceyhunhajiyev** [FreeCodeCamp/FreeCodeCamp#9255]
#### Challenge Name 
"Size Your Images"
https://bit.ly/fcc-relaxing-cat

#### Issue Description
Cannot go from Challenge 22 to Challenge 23. Normally, once I done the task, it should tell me if it is right or wrong. But, it did not happen. Refreshing page, still same result.

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: Mac OS
* Mobile, Desktop, or Tablet: Notebook

#### Your Code
<style>
  .larger-image {
    width: 500px;
  }
</style>
```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

<img width="1266" alt="screen shot 2016-06-20 at 8 02 58 pm" src="https://cloud.githubusercontent.com/assets/20033403/16214085/da643ea0-3722-11e6-8ce3-a1c114f988f2.png">

**Comment by arun1595** [comment]
Did your run the tests? Click on the button which says **Run tests** or use ctrl + enter key combination.

**Comment by ceyhunhajiyev** [comment]
Yes, I tried both clicking the button and Ctrl+Enter, not proceeding to the result or next challenge

**Comment by heldersepu** [comment]
https://www.freecodecamp.com/challenges/size-your-images
I was able to proceed just fine...
@ceyhunhajiyev  looking at you screenshot you have not added the required class, and for some strange reason you can not see the result of the tests, see how it looks on mine
![image](https://cloud.githubusercontent.com/assets/545474/16215144/5c0c5fe6-372d-11e6-96e9-52c65a85a1ab.png)
I'm also using Google Chrome but on Windows

**Comment by erictleung** [comment]
@ceyhunhajiyev your code is incorrect. Double check your code again to make sure you have matching tags and the correct number of them. An indication of your code being incorrect is that your text in your `<p>` elements are red. They should be white as in @heldersepu screenshot.

If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
