### ISSUE TITLE
Scroll to bottom of #scroll-locker

### ISSUE THREAD

**Issue by heldersepu** [FreeCodeCamp/FreeCodeCamp#9256]
#### Challenge Name
https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator

#### Issue Description
This applies to any challenge with large contents.
The scroll to the bottom of #scroll-locker has some side effect, is scrolling the user on inital load.
We should not scroll when the JS does initial challenge run to populate tests

**Comment by Bouncey** [comment]
When going to a new challenge, I don't have time to read the instructions before the animation kicks in.

If you can disable the animation on page load, that would be much better.

**Comment by atjonathan** [comment]
@bouncey I agree
