### ISSUE TITLE
Cannot Solve - Escape Sequences in Strings

### ISSUE THREAD

**Issue by asingh714** [FreeCodeCamp/FreeCodeCamp#9257]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStr%20%3D%20%22Here%20is%20a%20backslash%3A%20%5C%5C%20%5Cn%5Cr%5Ct%5CtHere%20is%20a%20new%20line%20with%20two%20tabs.%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "Here is a backslash: \\ \n\r\t\tHere is a new line with two tabs.";
```

**Comment by heldersepu** [comment]
Try this:
`var myStr = "Here is a backslash: \\.\n\t\tHere is a new line with two tabs.";`

**Comment by arun1595** [comment]
You're a missing a 'dot'(.) after the backslash .

**Comment by erictleung** [comment]
@asingh714 thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). A hint would be to look at @heldersepu comment above. Happy coding!
