### ISSUE TITLE
no user tests were run" - program execution failure whatever  I do or not do

### ISSUE THREAD

**Issue by mientje** [FreeCodeCamp/freecodecamp#926]
Challenge http://www.freecodecamp.com/challenges/bonfire-make-a-person has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

 Whatever I do, I get "no user tests were run" - program execution failure. Is this normal?

**Comment by kurzninja** [comment]
This usually indicates that there's a problem with your code, like a syntax issue or a function that doesn't exist or something similar. Without seeing your code it's impossible to say, but it's highly unlikely that this is an issue with the Bonfire itself.

**Comment by mientje** [comment]
I always hit run before entering code, because the criteria that are set provide useful insight in the nature of the assignment and this time there was this program execution failure.




But, 




I got a little further this weekend. There are still the last three criteria I have to meet and I'll investigate a little further first. Maybe I can find it on my own.


Thanks for the reply and greets,

Karin








Verzonden met Windows Mail





Van: Brett Guillory
Verzonden: ‎maandag‎ ‎15‎ ‎juni‎ ‎2015 ‎03‎:‎43
Aan: FreeCodeCamp/freecodecamp
CC: meersmankarin@hotmail.com





This usually indicates that there's a problem with your code, like a syntax issue or a function that doesn't exist or something similar. Without seeing your code it's impossible to say, but it's highly unlikely that this is an issue with the Bonfire itself.

**Comment by BerkeleyTrue** [comment]
closing as stale.

Also, at the moment the only browser fully supported is chrome. It might be an issue with your browser as most browsers do not have full web worker capabilities.

Happy Coding!
