### ISSUE TITLE
It seems the last section missed the <p> tag. But such code passed the run test.It should not pass the test I think.

### ISSUE THREAD

**Issue by breakpoint1025** [freeCodeCamp/freeCodeCamp#9261]
Challenge [Link to External Pages with Anchor Elements](https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%0A%20%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A%20%20%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp.com%22%3E%20cat%20photos%3C%2Fa%3E%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.
 </p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

  <a href="http://freecatphotoapp.com"> cat photos</a></p>
```

**Comment by Bouncey** [comment]
Related to #5533 and #8137 

Perhaps we need to explain that pink highlighted syntax in the editor means there is a syntax error. 

In JS it is pretty obvious because errors are thrown due to syntax errors, but HTML is very forgiving, and will generate the missing tags for you (with no attributes). 


Cc @FreeCodeCamp/issue-moderators

**Comment by Bouncey** [comment]
@breakpoint1025 Thanks for contributing

**Comment by erictleung** [comment]
@Bouncey yes, the code is incorrect with some non-matching tags. However, these are rendered to eventually match and creates an empty paragraph.

![image](https://cloud.githubusercontent.com/assets/2754821/16219975/a1af52a4-373e-11e6-92c5-9c96deef89e6.png)

I'm not sure how important it is to prevent this. As you mention, HTML is forgiving and for learning purposes, so I don't know how much it'll matter to prevent all these matching of tags unless it is integral for completing the challenge.

**Comment by Bouncey** [comment]
@erictleung I completely agree see [this](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8137#issuecomment-223148442) comment in issue 8137. 

I think we should make campers aware of what pink highlighted syntax means in the editor to help resolve these issues. As I mentioned in the linked comment, it would be unreasonable to test the correctness of every single html tag (something which codemirror is already doing) in all the challenges. the rendered challenge environment acts like the 'real world'.

**Comment by erictleung** [comment]
@Bouncey maybe in future challenges on QA and testing, we can talk about linting and syntax highlighting.

**Comment by breakpoint1025** [comment]
@Bouncey @erictleung thank you guys for your explanation to a beginner like me^_^

**Comment by Bouncey** [comment]
@erictleung I meant, maybe we should make campers aware of what the syntax highlighting means, possibly  as early as `Say Hello to HTML Elements`. Or even a new challenge by itself to point it out the linting going on in the text editor.

It would help cut down on issues of this nature being raised.

cc @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
I agree with @erictleung, it should be included in the new section "QA and Testing".

**Comment by kitapsiz** [comment]
This page has error and did not occur by novicer/me. And no one knows how to pass to next challange.
