### ISSUE TITLE
Iniciante

### ISSUE THREAD

**Issue by THIAGOWESLLEY2** [FreeCodeCamp/FreeCodeCamp#9262]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3EOl%C3%A1%20Mundo%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3E%20Mundo%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Olá Mundo
<h1>Hello</h1>
<h1> Mundo</h1>
```

**Comment by dwd2010** [comment]
@THIAGOWESLLEY2 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!
