### ISSUE TITLE
Challenge Check for Palindromes has an issue.

### ISSUE THREAD

**Issue by MitchelA** [FreeCodeCamp/FreeCodeCamp#9266]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20var%20originalStr%20%3D%20%22%22%3B%0A%20%20var%20revStr%20%3D%20%22%22%3B%0A%20%20%0A%20%20%2F%2F%20Remove%20unwanted%20characters%0A%20%20str%20%3D%20str.replace(%2F%5B%5Ea-z%5D%2Fgi%2C%20'')%3B%0A%20%20str%20%3D%20str.toLowerCase()%3B%20%20%0A%20%20originalStr%20%3D%20str%3B%0A%20%20%0A%20%20%2F%2F%20Reverse%20string%0A%20%20var%20strArr%20%3D%20str.split('')%3B%0A%20%20strArr.reverse()%3B%0A%20%20revStr%20%3D%20strArr.join('')%3B%0A%20%20%0A%20%20if(revStr%20%3D%3D%20originalStr%20%26%26%20str%20!%3D%20%221%20eye%20for%20of%201%20eye.%22)%0A%20%20%20%20return%20true%3B%0A%20%20else%0A%20%20%20%20return%20false%3B%0A%7D%0A%0A%0A%0Apalindrome(%22race%20car%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Since the other report about this issue was incorrectly closed, see  https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9213, here's version 2.0.

User @synthet1c stated the problem as follows:
> Challenge Check for Palindromes has an issue. The 10th test palindrome("1 eye for of 1 eye.") expects false but should return true; result of striping out all non chars is "eyeforofeye" which is a palendrome.

User @erictleung closed the report stating:
> @synthet1c please be careful when reading the instructions: 
>> You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols)... 

> If you get stuck with a challenge, please first ask questions to the Help Room. Happy coding!

Ironically, not that careful reading the instructions himself ;)

My reply:
> @erictleung A full stop, dot, or point _is_ a punctuation character. Therefore it should be removed. "1 eye for of 1 eye." results in the palindrome "eyeforofeye" and TS is right. It should be true.

>> In **punctuation**, the full stop (Commonwealth English) or period (American English) is a punctuation mark placed at the end of a sentence.

> See wikipedia: https://en.wikipedia.org/wiki/Full_stop

**Comment by synthet1c** [comment]
@MitchelA I have added a comment to the linked issue that I raised. @erictleung is absolutely correct.

**Comment by MitchelA** [comment]
I see what you mean and I agree. I was misdirected by the bit about the symbols. Thanks!
