### ISSUE TITLE
not reading string on the "Make Instances of Objects with a Constructor Function"

### ISSUE THREAD

**Issue by MigZyy** [FreeCodeCamp/FreeCodeCamp#9268]
Challenge [Make Instances of Objects with a Constructor Function](https://www.freecodecamp.com/challenges/make-instances-of-objects-with-a-constructor-function#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0Athis.wefv%20%3D%204%3B%0Athis.nickname%20%3D%22lewfknw3%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var myCar = new Car();
this.wefv = 4;
this.nickname ="THIS IS THE PROBLEM    NOT READING THIS STRING";

```

**Comment by raisedadead** [comment]
Thanks for reporting this but, your code is not correct.
Please consult [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for any assistance.

Happy coding.
