### ISSUE TITLE
" !important " not detected in Waypoint: Override Styles with Important

### ISSUE THREAD

**Issue by ManojitBallav** [FreeCodeCamp/freecodecamp#927]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue. 
Even after i have entered the !important by creating a urgent-red class in the CSS, its not getting recognised.
The code is as follows:
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .urgently-red{
    color: red
    !important;
  }
  
  .blue-text{
    color: blue;
    
  }
</style>

<h2 class='blue-text urgently-red'>CatPhotoApp</h2>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

![screenshot 28](https://cloud.githubusercontent.com/assets/10193961/8149064/28a0bfbc-12d5-11e5-8f2c-c8e9feb76024.png)

Since I an new to this I an not sure if it is a confirmed bug.
I apologise the community in advance if it does not happen to be a bug and just a code error.
Suggestions are welcomed !

**Comment by vaibhavmule** [comment]
@ManojitBallav 
Your code should not be like this.

```.urgently-red {
    color: red 
    !important;
  }```

This is right one:

```.urgently-red {
    color: red !important;
  }```
Please do not write `!important` in next line. just write `color: red !important;`
