### ISSUE TITLE
Title Case Sentence - Not Working

### ISSUE THREAD

**Issue by Anciso** [FreeCodeCamp/FreeCodeCamp#9271]
#### The compiler works well but I can not go ahead

I don't know why it's not being accepted, it solve all necessary steps.

#### Here's the code

```js

function titleCase(str) {
  
  var stringSplited = [];
  stringSplited = str.split(" ");
  var ans = "";
  var soft = " ";
  
  for(var i=0;i<stringSplited.length;i++)
    {
      if(i === stringSplited.length-1)
        soft = ".";
      
     ans += stringSplited[i][0].toUpperCase()+stringSplited[i].replace(/[^]/,"").toLowerCase()+soft;
    }
  
  return ans;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");
```

**Comment by dhcodes** [comment]
@Anciso Your code works provided two things. 
1. Remove the if statement that adds a period at the end as the results do not have periods.
2. Your current code returns the correct string but has a space character at the end which is what is rendering it wrong. You can correct this by changing your return to `return ans.trim();` to remove the trailing space.

It can be helpful to ask in the FCC [Help Javascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) or [Help](https://gitter.im/FreeCodeCamp/Help) chat rooms on Gitter to see if anyone can confirm that there is indeed an issue with the tests before submitting it on Github.

Happy coding!

**Comment by Anciso** [comment]
Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks Thanks.
Very apreciated, I did that... look for some help there (Gitter) but no one was helpfull enough.

Very apreciated !!!
Obrigado !!!

**Comment by renewu0707** [comment]
@Anciso Hi Anciso, I solved the same challenge with the similar regular expression,
 ans += stringSplited[i][0].toUpperCase()+stringSplited[i].replace(/[\S]/,"").toLowerCase();
It worked well but i don't really understand why this regular expression can retrieve the string starting from the second character? thx

**Comment by Anciso** [comment]
Hi @renewu0707 Sorry does not answer you earlier...... Well its all because the regular expression and the replace function... the replace function will replace the string but instead replace all the string it will only replace first char on the string and the rest of that string will remain intact....

We must remember the regular Espression's used /[^]/.

Here's an example:

```
var strReplaced = "Bush".replace(/[^]/,"C");
return strReplaced;
 // it will return "Cush".
```

Sorry my English I'm learning now.., my native language is Portuguese.

I hope I've helped.

Happy Coding !!
