### ISSUE TITLE
Description is not clear

### ISSUE THREAD

**Issue by bunnyvishal6** [FreeCodeCamp/FreeCodeCamp#9273]
Challenge [Image Search Abstraction Layer](https://www.freecodecamp.com/challenges/image-search-abstraction-layer) has an issue.
Description is not clear. Please give any hint from where can we get the search results.

**Comment by erictleung** [comment]
@bunnyvishal6 the challenges are designed for you to go out and search how to complete these challenges for yourself. For challenge help and guidance, please visit our [Gitter chat room focused on Back-End challenges](https://gitter.im/FreeCodeCamp/HelpBackEnd) where there will be people willing to give you hints or resources that may help. Happy coding!
