### ISSUE TITLE
ReferenceError: Can't find variable: stringify ?

### ISSUE THREAD

**Issue by zachbpd** [FreeCodeCamp/FreeCodeCamp#9275]
#### Challenge Name

https://www.freecodecamp.com/challenges/record-collection

#### Issue Description

Although I had the correct code, I kept getting that error. I changed the collectionCopy var declaration to
var collectionCopy = JSON.parse(JSON.stringify(collection));
and that fixed the problem.

#### Browser Information

* Browser Name, Version: Safari 9.1.1
* Operating System: OS X El Capitan
* Mobile, Desktop, or Tablet: -

#### Your Code

```js
// If relevant, paste all of your challenge code in here

```

**Comment by dhcodes** [comment]
Lol, didn't hear from you so we submitted it here @zachbpd https://github.com/FreeCodeCamp/FreeCodeCamp/commit/3fa86377f87c98cb5a3ea3bae84daee3424cf58c

**Comment by dhcodes** [comment]
You can probably close this one since there is more documentation in the other. But feel free to comment if you have more to add to the other.

**Comment by zachbpd** [comment]
oh okay, cheers mate 👍
