### ISSUE TITLE
Challenge 197

### ISSUE THREAD

**Issue by RomitDhamija** [FreeCodeCamp/FreeCodeCamp#9278]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(strokes%3D%3D1)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20%22Hole-in-one%22%3B%0A%20%20%20%20%7D%0A%20%20else%20if(strokes%3C%3D(par-2))%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%20%20%7D%0A%20%20else%20if(strokes%3D%3D(par-1))%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%20%20%7D%0A%20%20else%20if(strokes%3D%3D(par))%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20%22Par%22%3B%0A%20%20%20%20%7D%0A%20%20else%20if(strokes%3D%3D(par%2B1))%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%20%20%7D%0A%20%20else%20if(strokes%3D%3D(par%2B2))%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%20%20%7D%0A%20%20else%20if(strokes%3E%3D(par%2B3))%0A%20%20%7B%0A%20%20%20%20return%20%22Go%20Home%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(4%2C7)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes==1)
    {
      return "Hole-in-one";
    }
  else if(strokes<=(par-2))
    {
      return "Eagle";
    }
  else if(strokes==(par-1))
    {
      return "Birdie";
    }
  else if(strokes==(par))
    {
      return "Par";
    }
  else if(strokes==(par+1))
    {
      return "Bogey";
    }
  else if(strokes==(par+2))
    {
      return "Double Bogey";
    }
  else if(strokes>=(par+3))
  {
    return "Go Home";
  }
  
  // Only change code above this line
}

// Change these values to test
golfScore(4,7);

```
the following code returns the desired output but unfortunately fcc says the challenge is incomplete. Look into the matter please

**Comment by RomitDhamija** [comment]
The following code returns the desired output but unfortunately fcc says the challenge is incomplete. Look into the matter please

**Comment by atjonathan** [comment]
The strings you are returning aren't the sames as the tests require.

Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by elfseven** [comment]
I think you missed two "!" in the strings
