### ISSUE TITLE
Issue with example link for Buidling a Tribute Page. 

### ISSUE THREAD

**Issue by jads1073** [FreeCodeCamp/FreeCodeCamp#9279]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
When click on the link for the Tribute Page (https://codepen.io/FreeCodeCamp/full/NNvBQW/) Page takes you to the codepen.io site, but the web paged referenced is 404, page not found. Please update link to active example tribute page.

**Comment by atjonathan** [comment]
@jads1073, this works perfectly fine for me. Can you provide a screenshot?

**Comment by mdrose** [comment]
This seems to be an issue with codepen. I get the same result for any pen on the site, not just freecodecamp's, unless it's in the editor view ie. /pen/ in url instead of /full/.

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue still occurs!

**Comment by mdrose** [comment]
@jads1073 For me, it turned out that this was caused by having referer turned off in my browser. Codepen doesn't work properly without it. Maybe that's your problem as well.
