### ISSUE TITLE
Faulty instructions on Truncate a String

### ISSUE THREAD

**Issue by jvhensley** [FreeCodeCamp/freecodecamp#928]
Challenge http://www.freecodecamp.com/challenges/bonfire-truncate-a-string has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This is not really a bug -- it's just that the directions don't specify that you need to return the full string, if the string is not longer than the second argument. 

That's all!

**Comment by LumenTeun** [comment]
The first sentence of the instructions is this:
```"Truncate a string (first argument) if it is longer than the given maximum string length (second argument)."```
This would indicate that if the first argument is not longer than the second argument specifies, it should not be truncated.
