### ISSUE TITLE
Exercise Factorialize a Number not entering the for loop

### ISSUE THREAD

**Issue by N3tl0d3r** [FreeCodeCamp/FreeCodeCamp#9282]
Factorialize a Number

https://www.freecodecamp.com/challenges/factorialize-a-number

#### Issue Description

I write my solution but nothing happened, then I decided to put a console.log in to my for loop and I noticed using the console that the program never enters the loop.

#### Browser Information

* Browser Name, Version: Google Chrome Version 51.0.2704.103 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

function factorialize(num) {
  for(var i = 0; i >5; i++) {
    console.log("Test");
  }
  return num;
}

factorialize(5);

```js
// If relevant, paste all of your challenge code in here

```

#### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/7348594/16249446/de4c5180-37e3-11e6-8073-6d304e6cfe43.png)

**Comment by Bouncey** [comment]
@N3tl0d3r There is an issue with your code. Please use the `Help` button to get advice on your code. GitHub issues are not for challenge help.

**Comment by erictleung** [comment]
@N3tl0d3r thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: to at least solve your `console.log()` issue, please double check your condition in your `for` loop. Happy coding!
