### ISSUE TITLE
Issue with Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by smitdoshi** [FreeCodeCamp/FreeCodeCamp#9283]
#### Challenge Name

https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions

#### Issue Description

I purposely pass one argument and it still passes all the test but ya it does not show the output.
I know, it's obvious that it won't show any output but on the other hand
It should not pass all the Test described in the Question, Right?

#### Browser Information

* Browser Name, Version: Chrome, (64 bit)
* Operating System:  Mac OS
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
**CODE**
function functionWithArgs(a, b) {
  console.log(a+b);
}
functionWithArgs(10); // Outputs 5


```

#### Screenshot

I am attaching the screenshot.

Thank you.
You all are doing great Job.

Your Sincerely,
SMIT DOSHI.
<img width="1016" alt="bug" src="https://cloud.githubusercontent.com/assets/17622034/16251306/e1dd1212-37f2-11e6-8185-2f70b8a767cf.png">

**Comment by erictleung** [comment]
@smitdoshi the tests are based on the function you've written, which is correct. Your function call doesn't really affect the test results. Any function call you make (generally speaking) is for your debugging convenience. Closing as not an issue with the site. Happy coding!
