### ISSUE TITLE
Commenting if else doesn't compile the code.

### ISSUE THREAD

**Issue by praneethkumarpidugu** [FreeCodeCamp/FreeCodeCamp#9284]
Challenge [Replacing If Else Chains with Switch](https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch#?solution=%0Afunction%20chainToSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20switch(val)%20%7B%0A%20%20%20%20case%20%22bob%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Marley%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2042%3A%0A%20%20%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%201%3A%0A%20%20%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2099%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AchainToSwitch(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  /**
  if (val === "bob") {
    answer = "Marley";
  } else if (val === 42) {
    answer = "The Answer";
  } else if (val === 1) {
    answer = "There is no #1";
  } else if (val === 99) {
    answer = "Missed me by this much!";
  } else if (val === 7) {
    answer = "Ate Nine";
  }**/
  switch(val) {
    case "bob":
      answer = "Marley";
      break;
    case 42:
      answer = "The Answer";
      break;
    case 1:
      answer = "There is no #1";
      break;
    case 99:
      answer = "Missed me by this much!";
      break;
    case 7:
      answer = "Ate Nine";
      break;
  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);


```

**Comment by erictleung** [comment]
@praneethkumarpidugu the presence of any `if` or `else` statements will cause the test to fail because it is searching your entire code.

@FreeCodeCamp/issue-moderators a quick fix for this would be update the test saying you shouldn't have an `if` or `else` statement anywhere in the editor. Is there are more long term fix for this?

**Comment by raisedadead** [comment]
This seems to return every now and then. I honestly believe that we figure out a way to address these problems in a more generic way.

Its time we have a infrastructure for parsing real JavaScript. Will have a look unless someone is interested to prototype.

Meanwhile lets have a quick fix in the interim, can be tagged as help-wanted + first timers if others agree.

**Comment by erictleung** [comment]
@raisedadead agreed on needing a better way to address these. I'll go ahead and mark it for a quick change.

[These lines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4713669d46ce19fa65ed988ad404e12798145f9b/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3642-L3643) need to be changed to something along the lines of 

> You should not use any <code>else</code> statements anywhere in the editor

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.
