### ISSUE TITLE
Bonfire: Title Case a Sentence

### ISSUE THREAD

**Issue by AlfonB6** [FreeCodeCamp/freecodecamp#929]
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

function titleCase(str) {
  //split(/\W/g) to convert it into an array
  //for...in to go through each word
    //inside for/in arr[word].toUpperCase();
    //return arr
  arr = str.split(/\W/g);
  for (var word in arr) {
    console.log (arr[word].toUpperCase());
  }
  return arr;
}

titleCase("I'm a little tea pot");

![image](https://cloud.githubusercontent.com/assets/11698182/8151125/8c453640-12d2-11e5-982b-1f17a60fb8bf.png)

Thank you

**Comment by kurzninja** [comment]
You didn't specify what the issue is here.

**Comment by felixcriv** [comment]
The code he wrote is wrong as you see at the console window and it is passing all test cases. The test cases should look for capitalized first letters on a sentence and the code is capitalizing all letters and still pases the tests.

**Comment by LumenTeun** [comment]
The test cases do look for correctly capitalized sentences, specifically:
```json
"expect(titleCase(\"I'm a little tea pot\")).to.be.a('String');",
"expect(titleCase(\"I'm a little tea pot\")).to.equal(\"I'm A Little Tea Pot\");",
"expect(titleCase(\"sHoRt AnD sToUt\")).to.equal(\"Short And Stout\");",
"expect(titleCase(\"HERE IS MY HANDLE HERE IS MY SPOUT\")).to.equal(\"Here Is My Handle Here Is My Spout\");"
```

Not sure what went wrong, could @AlfonB6 post their code, wrapped in ```, and tell us whether the issue is still there after a refresh?
