### ISSUE TITLE
ReferenceError: stringify is not defined

### ISSUE THREAD

**Issue by MistaTwist** [FreeCodeCamp/FreeCodeCamp#9290]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%20%222548%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20tracks%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%222468%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%221999%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%221245%22%3A%20%7B%0A%20%20%20%20%20%20%22artist%22%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%225439%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20%0A%20%20%20%20if%20(value%20%3D%3D%3D%20%22%22)%20%7B%0A%20%20%20%20%20%20delete%20collection%5Bid%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20if%20(prop%20%3D%3D%3D%20%22tracks%22)%20%7B%0A%20%20%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D.push(value)%3B%20%20%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%20%20%20%20%20%7D%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {


  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by raisedadead** [comment]
Thanks for reporting. Your code is not correct.
Please consult [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and Happy Coding!

**Comment by MistaTwist** [comment]
hi @raisedadead - the above is the default code.

FYI, the default code should prepend stringify with JSON, like this:

var collectionCopy = JSON.parse(JSON.stringify(collection));

I mention it as anyone newer to coding will have problems not necessarily to do with their own code.

Thanks,

Regards,

Paul.

**Comment by raisedadead** [comment]
Hi Paul (@MistaTwist),

Apologies for the closure, I just noticed after you comment the true issue, unfortunately the Opening Post of the thread did not mention that this was the default code, to which I assumed that this is the code you wrote and hence my conclusion.

Looks like this has crept in as a part of a recent merge of PR #9096 
Specifically on line :
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9096/files#diff-5fbffcdf48f7976dd3b0216c387eebc2R4554

Reopening for a fix.

Thanks for reporting.

**Comment by raisedadead** [comment]
Additional issues with the challenge:

https://www.freecodecamp.com/challenges/introducing-javascript-object-notation-json results in
![image](https://cloud.githubusercontent.com/assets/1884376/16267501/bb248b54-38a7-11e6-93c0-8eb8dbe9b810.png)

/cc @atjonathan

**Comment by erictleung** [comment]
@raisedadead the `JSON.stringify` issue was resolved with #9277. It just needs to be pushed to the live site. Feel free to close this issue unless you want to address the issue you've just mentioned right above.

**Comment by atjonathan** [comment]
@raisedadead, this is due to a recent merge by @Bouncey (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9144). I'm gonna close this issue, as @erictleung is correct, and make another for this problem.
