### ISSUE TITLE
Editor - cursor repositioning issue

### ISSUE THREAD

**Issue by Dhrumilcse** [FreeCodeCamp/FreeCodeCamp#9296]
Having issue with cursor repositioning, while loading a new challenge.

**Comment by ramir141974** [comment]
I don't know how to fixed it this issue if somebody help me to organized this issue it must be great thank you.

I am biggener that's all...

**Comment by BKinahan** [comment]
This is a duplicate of #7847, feel free to take a look at that issue and add any additional information or insight you may have :)

**Comment by atjonathan** [comment]
@Dhrumilcse, thanks for reporting this issue, feel free to follow along with #7847 and leave a comment :smile: 
@BKinahan, thanks for that :tada:
