### ISSUE TITLE
I believe the symmetric difference test is broken.

### ISSUE THREAD

**Issue by cornjacket** [FreeCodeCamp/freecodecamp#930]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I believe the symmetric difference autotest test is broken. Just to be sure I ran terakilobyte's solution to this problem which he did on April 18th, 2015 and his results did not pass the test with the following error;

expected [3, 4, 5] to deeply equal [3, 5, 4]

Screenshot link:
https://www.dropbox.com/s/0r056t5coxowts4/Screenshot%202015-06-14%2022.54.14.png?dl=0

 I would suggest running terakilobyte's solution

http://www.freecodecamp.com/terakilobyte

Thanks for your help.

-dave

**Comment by QuincyLarson** [comment]
Thank you for your help! We've now fixed this in production!
