### ISSUE TITLE
Get Geolocation Data: jQuery selector with single quote won't pass

### ISSUE THREAD

**Issue by sabrinaluo** [FreeCodeCamp/FreeCodeCamp#9303]
Challenge [Get Geolocation Data](https://www.freecodecamp.com/challenges/get-geolocation-data#?solution=%0Afccss%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0Aif%20(navigator.geolocation)%20%7B%0A%20%20navigator.geolocation.getCurrentPosition(function(position)%20%7B%0A%20%20%20%20%24(%22%23data%22).html(%22latitude%3A%20%22%20%2B%20position.coords.latitude%20%2B%20%22%3Cbr%3Elongitude%3A%20%22%20%2B%20position.coords.longitude)%3B%0A%20%20%7D)%3B%0A%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0Afcces%0A%3Cdiv%20id%20%3D%20%22data%22%3E%0A%20%20%3Ch4%3EYou%20are%20here%3A%3C%2Fh4%3E%0A%20%20%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  // Only change code below this line.
if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(function(position) {
    $('#data').html("latitude: " + position.coords.latitude + "<br>longitude: " + position.coords.longitude);
  });
}

  // Only change code above this line.
</script>
<div id = "data">
  <h4>You are here:</h4>
  
</div>

```

The code is 99% similar with the given example code, except the single quote of jQuery selector.

If I change `$('#data')` to `$("#data")`, the last test case **You should display the users' position within the data div element** can be passed.

Single quote for `string` can be passed, this seems only happen for jQuery selectors.

**Comment by sthodup1** [comment]
I'll try to reproduce the issue. Something to note is that the jQuery style guides say to use double quotes instead of single quotes [.](http://contribute.jquery.org/style-guide/js/#quotes).

**Comment by raisedadead** [comment]
@sthodup1 thanks for pointing that out, we need a hint to be added to the instruction pointing to the resource suggested above.

Just to explore : http://stackoverflow.com/questions/7027986/single-or-double-quotes-in-jquery

**Comment by raisedadead** [comment]
Yeah @sthodup1 you are correct, I forgot to mention that we should mention the hint in the beginning of the jQuery section.

Well as far as the tests for the challenge go I think they are not flexible to allow for single quotes, but that's up to us, we should rather be teaching best practices, which I think can be referred from the guide.

**Comment by sthodup1** [comment]
@raisedadead I tried to submit a pr to fix this, but it failed the check. Could you help me figure out what the problem is?

**Comment by raisedadead** [comment]
@sthodup1 check comments on the PR thread.

**Comment by sthodup1** [comment]
Sorry for all the reference spams. I couldn't figure out how to squash the commits so I reforked FCC and made the commit again. However, the test fails now because apt-get is failing, which should have nothing to do with my changed code.

**Comment by raisedadead** [comment]
@sthodup1 I have re-started the build, it got interrupted somehow.

**Comment by sthodup1** [comment]
@raisedadead Thanks for all the help!
