### ISSUE TITLE
Escape Sequences in Strings challenge not accepting escape sequences

### ISSUE THREAD

**Issue by aicccia** [FreeCodeCamp/FreeCodeCamp#9314]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStr%20%3D%20%22Here%20is%20a%20backslash%3A%5C%5C.%5Cn%20%5Ct%5Ct%20Here%20is%20a%20new%20line%20with%20two%20tabs.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2756.0 Safari/537.36 OPR/40.0.2267.0 (Edition developer)</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
var myStr = "Here is a backslash:\\.\n \t\t Here is a new line with two tabs.";
 
Screenshot: https://i.sli.mg/hEmocD.png

I asked for help in the chatroom and my solution was the same as others who had successfully completed the challenge. 

```

**Comment by erictleung** [comment]
@aicccia To complete this challenge, you'll need to be very precise. There should be a space before the first escape backslashes, no space between the new line character and tab, and no space between the tab and "Here".

@FreeCodeCamp/issue-moderators I recently updated the challenge and it checks for a very precise string and I think it'll be difficult and possibly confusing to ask for those specific spaces. I think a better solution would be to write a regex looking for the string and accommodate for spaces around the escape characters. Thoughts?

**Comment by BKinahan** [comment]
This challenge has definitely had a spike in confusion in the HelpJavaScript chat since the change to a pair of sentences from the previous string of only escaped characters separated by spaces. This is compounded by the fact that the instructions don't display spaces clearly, and exacerbated by many new users' lack of familiarity with Gitter's code formatting syntax (which makes it difficult to detect where the error lies as `\\` without formatting displays as \ and spaces can't be located/counted accurately).

Perhaps a string without any spaces or punctuation is a better alternative, such as this or some variation:

`var myStr = "First\tLine\n\"Second\tLine\"\rThird\tLine";`

**Comment by einblock** [comment]
I spent quiet some time getting this one right. I kept getting the error messages:

`myStr` should have encoded text with the proper escape sequences and spacing.

and

`myStr` should not have any spaces in between consecutive escape sequences.

So, I typed and retyped the escape character sequence several times, making sure there were no spaces.
In the end, it turned out I was missing the final period, after "tabs". 

I'm thinking it might be an idea to change the error messages somehow, maybe making the first one encourage that you check the entire text, not just escape sequences and spacing, and for the last one making sure it doesn't show unless the spacing is actually wrong.

**Comment by Doomflake** [comment]
I've tried entering nothing but \\ into my variable quotes and it still prints out as a double backslash.  If I try formatting the entire string, it looks like none of it is being ran correctly.  It still prints out the actual code instead of the escaped characters.

**Comment by charlesBak** [comment]
the string should look like this. there is no space between the second tab and the second line.
myStr = "Here is a backslash: \\.\n\t\tHere is a new line with two tabs.";

**Comment by charlesBak** [comment]
the string should look like this. there is no space between the second tab and the second line.

myStr = 'Here is a backslash: \\.\n\t\tHere is a new line with two tabs';

**Comment by charlesBak** [comment]
the string should look like this. there is no space between the second tab and the second line.

`myStr = 'Here is a backslash: \\.\n\t\tHere is a new line with two tabs';`

**Comment by Marshallgray** [comment]
Just tried charlesBak solution still having no success!

**Comment by charlesBak** [comment]
dont forget the mark at the end of the string.

`myStr = 'Here is a backslash: \\.\n\t\tHere is a new line with two tabs.';`

**Comment by Marshallgray** [comment]
Thanks charlesBak!

**Comment by charlesBak** [comment]
my pleasure Marshallgray.

**Comment by wiseleo** [comment]
This part is confusing. Although the string https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9314#issuecomment-228518151 passes the challenge, the rendered preview has a bug.
![screenshot 35](https://cloud.githubusercontent.com/assets/451505/16359790/cac8bee4-3b32-11e6-8580-97429a4ec787.png)

**Comment by erictleung** [comment]
@BKinahan thanks for fielding through all the new confusion about this challenge. I like your suggestion on the string what should be used

```js
var myStr = "First\tLine\n\"Second\tLine\"\rThird\tLine";
```

**Comment by Chrono79** [comment]
You will also need to follow the spacing as it looks above with no additional spaces between each escape sequence.

I think it should be "...with no additional spaces after each escape sequence" instead, a lot of people leave a space between the last \t and Here

**Comment by ShivaShinde** [comment]
This challenge is a  bit confusing, definitely need more help on this, @FreeCodeCamp please add some more content to understand it better. Thanks 😄

**Comment by atjonathan** [comment]
@ShivaShinde, if you feel this challenge needs more changes, please open a new github issue.

**Comment by ajaykandari222** [comment]
var myStr= "FirstLine\n\\SecondLine\\\rThirdLine";   // Change this line

this will work fine

**Comment by gari3d** [comment]
i have this one,  var myStr = "FirstLine\n\SecondLine\rThirdLine";  
but i still have issues with myStr should have encoded text with the proper escape sequences and no spacing. and myStr should have two correctly escaped backslash characters \\.  
i think this is issue?

**Comment by Chrono79** [comment]
gari3d: You need to enclose SecondLine with two correctly escaped backslash characters \ as you posted, I don't know if github is hiding it or not, but an escaped backslash is this: \\

**Comment by malixi** [comment]
Why it's not working on me. 

var myStr = "\\FirstLine\n\Secondline\rThirdline\\"; 

All are check except to the myStr should have encoded text with the proper escape sequences and no spacing.

**Comment by Chrono79** [comment]
malixi: you don't need the backslashes before FirstLine and after ThirdLine (this one is escaping the closing " btw).

**Comment by ajaykandari222** [comment]
Malixi : this is the solution

var myStr= "FirstLine\n\SecondLine\\rThirdLine";

**Comment by Chrono79** [comment]
alayek: sorry, but you have a backslash more than needed: the one before ThirdLine

**Comment by BEBEDYDY** [comment]
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line
here you go

**Comment by BEBEDYDY** [comment]
for some reason, browsers hide the \\\
so:
var myStr ="FirstLine\n\\\SecondLine\\\rThirdLine"; // Change this line

**Comment by lokenpuri** [comment]
It took so much time

**Comment by krishenexson** [comment]
var myStr= "FirstLine\n\\SecondLine\\\rThirdLine";

works!!!!!

**Comment by krishenexson** [comment]
#!var myStr= "FirstLine\n\\SecondLine\\\rThirdLine";!#

**Comment by dwd2010** [comment]
@krishenexson 
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by krishenexson** [comment]
I apologize

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Aug 17, 2016 at 3:54 AM -0500, "Lance" <notifications@github.com<mailto:notifications@github.com>> wrote:


@krishenexson<https://github.com/krishenexson>
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

-

**Comment by llacy730** [comment]
My code:
var myStr ='FirstLine\n\SecondLine\\\rThirdLine\\';

Error:
myStr should have encoded text with the proper escape sequences and no spacing.

**Comment by AmirErnest** [comment]
that one worked fine 
var myStr= "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by bjungbogati** [comment]
Solution that worked so far is : var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line

**Comment by texas2010** [comment]
@bjungbogati 
This place is not for put solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by egglestn** [comment]
When I had this error, the slashes were all correct: the problem was that I had "Firstline" instead of "FirstLine" (camel-case issue). It was really tricky to spot given that the error message made me think it was a problem with the slashes. 

FreeCodeCamp, please could you upgrade the error message to suggest there might be an issue with the text itself?
"myStr should have encoded text with the proper escape sequences and no spacing."
Maybe something like this...?
"myStr must match the provided case-sensitive text, with no spacing, and match the required escape characters".

**Comment by evan-blake** [comment]
"FirstLine\n\\SecondLine\\\rThirdLine";

;)

**Comment by texas2010** [comment]
@evan-blake 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by jonathan-kagi** [comment]
if better instructions existed folks would not be posting here with questions. please improve

**Comment by Roachk** [comment]
This challenge can be pretty confusing with out being able to see the output. Try running this code in a interpreter online like www.codecademy.com or codepen.io. Using the interpreters you can see your output and how it looks.

![image](https://cloud.githubusercontent.com/assets/20018670/19276339/136d1224-8fa4-11e6-8e84-637e03be0b01.png)

**Comment by AlaeddineMessadi** [comment]
This will work fine

`myStr= "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line`

**Comment by rbrentwells** [comment]
The Correct String is the following:

var myStr= "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by sumit-prgmr** [comment]
i also tried but iam only getting errors

**Comment by oforchinedu** [comment]
Here is my answer  "FirstLine\n\\SecondLine\\\rThirdLine"

**Comment by machao112** [comment]
Here is my answer: var myStr= "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by texas2010** [comment]
@oforchinedu 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by oforchinedu** [comment]
Ok sorry I did

**Comment by krishnaa208** [comment]
Escape Sequences in Strings
Solution:
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by texas2010** [comment]
@krishnaa208 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by angelogianopulos** [comment]
Hello guys I have spent hours trying to solve this challenge without any luck can anyone help?
This is what I have

**Comment by angelogianopulos** [comment]
var myStr = "First\tLine\n\"Second\tLine\"\rThird\tLine";

**Comment by angelogianopulos** [comment]
var myStr = '\"FirstLine\n \\n SecondLine \\\r nThirdLine/"'; // Change this line

**Comment by pksr04** [comment]
var myStr ="FirstLine\n\\SecondLine\\\n\rThirdLine"; // Change this line
The above code works in google chrome
![js_escapecode](https://cloud.githubusercontent.com/assets/23273418/20135551/3e4eea18-a696-11e6-82b2-b6817b04ac6b.png)

**Comment by wiki7** [comment]
it's vary simple write below code.
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by kellykevin** [comment]
but guys you are forgetting about the first instruction "myStr should have encoded text with the proper escape sequences and no spacing."

**Comment by symbioticon16** [comment]
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

this is it ;-)

**Comment by kellykevin** [comment]
still not working

**Comment by choiceman** [comment]
Mar 19 '13 at 21:56

**Comment by kellykevin** [comment]
this is still not working

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by raisedadead** [comment]
Temporarily locking conversation.
