### ISSUE TITLE
The text describing/introducing JSON is repetitive and ambiguous

### ISSUE THREAD

**Issue by manicmarvin** [FreeCodeCamp/FreeCodeCamp#9315]
#### Manipulating Complex Objects -- introducing-javascript-object-notation-json)

https://www.freecodecamp.com/challenges/manipulating-complex-objects

#### Issue Description

*The text describing/introducing JSON is repetitive and ambiguous.*

Both the description of complex data structures and JSON use the same example and much the same text, but it becomes unclear if they are one and the same or not. A short line explaining the link between JSON and complex objects would be helpful.

**Comment by heldersepu** [comment]
I agree with @manicmarvin 
Maybe we should merge the example and note below into one for both

**Comment by atjonathan** [comment]
:+1: (+1)
