### ISSUE TITLE
Misleading Instructions in "Understanding Uninitialized Variables" JS Section

### ISSUE THREAD

**Issue by Alexkal** [FreeCodeCamp/FreeCodeCamp#9317]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0Aa%20%3D%205%2C%20b%20%3D%2010%2C%20c%20%3D%20'I%20am%20a'%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a;
var b;
var c;
a = 5, b = 10, c = 'I am a';

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

So, one set of instructions is telling me to set a equal to 6, b equal to 15, and c equal to 'I am a String!', which doesn't complete the challenge. the instructions in "Instructions" though are the correct instructions, which my code satisfies. 

<img width="1920" alt="ntvj1m9" src="https://cloud.githubusercontent.com/assets/7352713/16295446/976db920-38ec-11e6-9fc6-270ada0dd65c.png">

**Comment by Mare9** [comment]
Sorry but maybe, you didn't see it. It asking you to do "I am a String ! String !" not " "I am a String !"
I hope this helps

**Comment by RyanGarant** [comment]
Same problem.

**Comment by genedex** [comment]
This is still the issue.

**Comment by EnerioJJ** [comment]
Someone mentioned this in May, and it hasn't been addressed for one reason or another.

**Comment by chiajw1** [comment]
Also same here, the above and below instruction contradicts with each other
