### ISSUE TITLE
Link broken to Introducing JavaScript Object Notation (JSON)

### ISSUE THREAD

**Issue by qdr** [FreeCodeCamp/FreeCodeCamp#9325]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      tracks: [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {

  if (prop == "tracks")

  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by BKinahan** [comment]
If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Issues are for reporting problems with the challenges or web site.
Happy coding!

**Comment by BKinahan** [comment]
Yeah, looks like the challenge referred to no longer exists, so the link should be removed or directed to a different (relevant) challenge.

<img width="685" alt="screen shot 2016-06-23 at 18 37 20" src="https://cloud.githubusercontent.com/assets/15965601/16315426/c21bea54-3971-11e6-8ad9-a9989d9b2dae.png">

**Comment by atjonathan** [comment]
To contributor:

This [line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4530) needs changed to use the new challenge link (https://www.freecodecamp.com/challenges/manipulating-complex-objects).

You can change the link tag from:
`<a href=\"https://www.freecodecamp.com/challenges/**challenge-name**\">**Challenge Name**</a>`
to
`<a href=\"**challenge-name**\">**Challenge Name**</a>`

**Comment by sunydyz** [comment]
Hi may I try this one?

**Comment by qdr** [comment]
just issued a pull request.  my first :)),

perhaps you can back me up,

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9331#issuecomment-228169444

greetings,
Dominik

2016-06-23 22:07 GMT+02:00 sunydyz <notifications@github.com>:
