### ISSUE TITLE
Timestamp Microservice User Story 6 is bad practice

### ISSUE THREAD

**Issue by chuckadams** [FreeCodeCamp/FreeCodeCamp#9327]
Challenge [Timestamp Microservice](https://www.freecodecamp.com/challenges/timestamp-microservice) has an issue.

> User Story: If it does not contain a date or Unix timestamp, it returns null for those properties.

For the very first backend project, do we want to be teaching people to return nulls or nonsensical data for errors?  They should be returning error codes.  I recommend changing it to read instead to:

**User Story:** If the request not contain a date or unix timestamp, an HTTP error 400 is returned.

**Comment by DG000gl** [comment]
Вы уже предали тот кого вы даже не знаете и обвинили не обосновано в краже целый день гнобили я может учусь только что правда а Вы за айфон меня обвинили у кого там опера хром  стоит хвастался вот увидимся скоро в суде спасибо

**Comment by chuckadams** [comment]
That was ... random.  DG000gl, please don't comment on issues unless you have something helpful to add.

**Comment by raisedadead** [comment]
Thanks @chuckadams I am in favor of returning HTTP error codes, just need to debate that should we be providing a link or hint of some sort on why to use HTTP error codes and what they are.

/cc @FreeCodeCamp/issue-moderators

**Comment by Em-Ant** [comment]
@chuckadams Thanks for your help. We are improving the microservice projects in the new curriculum. I'm closing this and moving the discussion to the related issue in the curriculum expansion repository https://github.com/FreeCodeCamp/CurriculumExpansion/issues/82.
