### ISSUE TITLE
inspite of puting the right syntax for css i am not able to enter the next file 

### ISSUE THREAD

**Issue by manojrammurthy** [FreeCodeCamp/freecodecamp#933]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by LumenTeun** [comment]
Please describe more indepth what the issue is and provide your code, wrapped in ```, so that others can try it out as well.

**Comment by manojrammurthy** [comment]
it got resolved , it was not really an issue , my bad

**Comment by LumenTeun** [comment]
Great :) Remember to close this issue.
