### ISSUE TITLE
Sum All Primes challenge giving me infinite loop error

### ISSUE THREAD

**Issue by amfische** [FreeCodeCamp/FreeCodeCamp#9333]
#### Challenge Name

https://www.freecodecamp.com/challenges/sum-all-primes

#### Issue Description

My code works when I transfer the code to a text editor and run a console.log in Firefox. On FCC website the code works fine when I run the function with a value of 10, ie sumPrimes(10); it even works fine with a value of 200, but when I run the function with a value of 977, sumPrimes(977); I get an error which says potential infinite loop at line 5, which is where I declare the counter variable.  

#### Browser Information

* Browser Name, Version: Firefox version 42.0
* Operating System: Mac OS X version 10.6.8
* Mobile, Desktop, or Tablet: laptop

#### Your Code

```js
// If relevant, paste all of your challenge code in here
function sumPrimes(num) {
  var sum = 0;
  for (var i = 1; i <= num; i++) {
    var counter = 0;
    for (var j = 1; j <= i; j++) {
      if (i % j === 0) {
        counter ++;
      }
    }
    if (counter === 2) {
      sum += i;
    }
  } 
  return sum;
}

sumPrimes(10);

```

**Comment by arun1595** [comment]
Your code works fine for me. See [here](https://www.freecodecamp.com/challenges/sum-all-primes#?solution=function%20sumPrimes(num)%20%7B%0A%20%20var%20sum%20%3D%200%3B%0A%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%20%7B%0A%20%20%20%20var%20counter%20%3D%200%3B%0A%20%20%20%20for%20(var%20j%20%3D%201%3B%20j%20%3C%3D%20i%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(i%20%25%20j%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20counter%20%2B%2B%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20if%20(counter%20%3D%3D%3D%202)%20%7B%0A%20%20%20%20%20%20sum%20%2B%3D%20i%3B%0A%20%20%20%20%7D%0A%20%20%7D%20%0A%20%20return%20sum%3B%0A%7D%0AsumPrimes(977)%3B)

**Comment by amfische** [comment]
I tried your link, but I'm still getting the same error. Maybe it's something with my computer

**Comment by rayGreycloud** [comment]
Your code works fine for me on the FCC too. I tried it using Chrome and then Edge, and all tests passed.

**Comment by amfische** [comment]
I got the code to work on my windows computer, running chrome. I guess it must have been something with Firefox on my macbook.
