### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by lillil25** [FreeCodeCamp/FreeCodeCamp#9334]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "Here is a backslash: \\.\n\t\tHere is a new line with two tabs."; // Change this line




```
Part of the error for this says "myStr should not have any spaces in between consecutive escape sequences."

What it fails to mention is to not have a space between the escape sequence and a word which is (Here). This code works fine....... var myStr = "Here is a backslash: \\.\n\t\tHere is a new line with two tabs."; // Change this line

**Comment by erictleung** [comment]
@lillil25 thanks for the feedback. We've got another issue on this same challenge talking about it in #9314. So closing this issue as it is a duplicate. Happy coding!
