### ISSUE TITLE
Problem with point 151 Understand String Immutability

### ISSUE THREAD

**Issue by bekir0v** [FreeCodeCamp/FreeCodeCamp#9335]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyStr%20%3D%20%22Hello%20World%22%3B%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line
myStr = "Hello World";
myStr[0] = "H"; // Fix Me



```

**Comment by erictleung** [comment]
@bekir0v if you run your code sequentially, it still tries to change an immutable string so that is why your code is failing. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by stefant93** [comment]
This challenge isn't really explaining or describing what to do... ?

**Comment by melyndaandrews** [comment]
This challenge is very poorly written.  The only instructions are to "Correct the assignment to myStr to achieve the desired effect."  What 'desired result?'  We have no idea what the desired result is, so how can we change the code to achieve it?

**Comment by aolyf** [comment]
I feel like it's implied what the "desired effect" should be.

**Comment by meizaifeng** [comment]
```
// Setup
var myStr = "Jello World";

// Only change code below this line

myStr = "Hello World"; // Fix Me
```

**Comment by bzouzou** [comment]
I think the desires effect is to correct the string. delete the [0] and replace it with ="Hello Wolrd";
