### ISSUE TITLE
Find the Longest Word in a String

### ISSUE THREAD

**Issue by EntopricInformation** [FreeCodeCamp/FreeCodeCamp#9337]
####Find the Longest Word in a String

https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20array%20%3D%20%5B%22a%22%5D%3B%0A%0Afunction%20findLongestWord(str)%20%7B%0A%20%20var%20string%20%3D%20str.split('%20')%3B%0A%20%20for%20(i%20%3D%200%3Bi%20%3C%20string.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if%20(string%5Bi%5D.length%20%3E%20array%5B0%5D.length)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20array.splice(0%2C1)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20array.push(string%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20array%5B0%5D.length%3B%0A%7D%0A%0AfindLongestWord(%22The%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22)%3B%0A

#### Issue Description
Everything returns Correctly, but I have a red "X" next to "findLongestWord("May the force be with you") should return 5."

#### Browser Information

* Google Chrome, 51.0.2704.103
* Windows 8.1
*Laptop

#### Your Code

```js
var array = ["a"];

function findLongestWord(str) {
  var string = str.split(' ');
  for (i = 0;i < string.length; i++) {
        if (string[i].length > array[0].length) {
            array.splice(0,1);
            array.push(string[i]);
        }
    }
    return array[0].length;
}

findLongestWord("The quick brown fox jumped over the lazy dog");


```

#### Screenshot
http://i.imgur.com/EAUAcuL.png

I know the code in this image doesn't match the code I posted, but I was just taking a screenshot of the error with the code "findLongestWord("The quick brown fox jumped over the lazy dog");" to show that it is returning the correct length in the form of a number

**Comment by erictleung** [comment]
@EntopricInformation the tests run your function so after global variable you've declared outside your function are changed with each function call. Place your global variable inside your function and all should be good. Happy coding!
