### ISSUE TITLE
Linkedin link broken on Jobs board

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/freecodecamp#934]

**Comment by LumenTeun** [comment]
Which link is broken and where should it lead to? I don't have a LinkedIn account, but clicking on the one LinkedIn link I can find takes me to a login page.

**Comment by BerkeleyTrue** [comment]
Jobs board has been removed. New board to come!

@CodeNonprofit Thanks for keeping us on our toes!

Happy Coding!
