### ISSUE TITLE
"Escaping Literal Quotes in Strings" not working in IE11

### ISSUE THREAD

**Issue by 9littlebees** [FreeCodeCamp/FreeCodeCamp#9340]
#### Challenge Name

Escaping Literal Quotes in Strings
#### Issue Description

I've read through the bug reports to ensure I was writing the code correctly, and for some reason I can't get past this challenge.
#### Browser Information

- Browser Name, Version: Internet Explorer 11
- Operating System: Windows 7 Pro (64bit)
- Mobile, Desktop, or Tablet: Desktop
#### Your Code

``` js
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line
```

**Comment by 9littlebees** [comment]
Just tried the same code in Google Chrome v51.0.2704.103 and it worked fine.  Issue is with Internet Explorer.

**Comment by erictleung** [comment]
@9littlebees I can confirm your code works on Chrome. However, I don't have a Windows computer at the moment to reproduce your error.

**Comment by heldersepu** [comment]
It works for me on IE 11...
@9littlebees what version of IE are you using?

**Comment by atjonathan** [comment]
@heldersepu, he is using **Internet Explorer 11**, it says in the issue description :wink:

**Comment by 9littlebees** [comment]
@erictleung Yep, first comment is my own, saying it works in Chrome.

@heldersepu No matter what I tried, I couldn't get it to work in IE 11, and I'm fully up-to-date with it.  Does your code match mine exactly?

**Comment by heldersepu** [comment]
I should have been more specific...
I'm on IE 11.0.9600.18349

![image](https://cloud.githubusercontent.com/assets/545474/16342604/09916e88-3a01-11e6-9e2d-06141bed096f.png)

**Comment by heldersepu** [comment]
@9littlebees yes my code is just a copy/paste of yours, take a look at my screenshot.

**Comment by 9littlebees** [comment]
@heldersepu I'm on 11.0.9600.18314.  I'll update and try again.  I know the code is fine, because it worked flawlessly in Chrome.  I also don't see why a slightly older version of IE 11 (looks like it released 16-May-2016) should have problems with basic JavaScript, though...

**Comment by heldersepu** [comment]
You might want to change the Title to reflect that the problem is only on IE.

Are you familiar with the Developer Tools? 
On IE you can press F12 and it will open, See if you are getting any errors there.
Also on the Developer Tools Console paste your string: 
`"I am a \"double quoted\" string inside \"double quotes\".";`
it should respond with:
`"I am a "double quoted" string inside "double quotes"."`

**Comment by AmeySingh** [comment]
Facing same problem with this challange but I am using crome.

**Comment by erictleung** [comment]
@AmeySingh you need a space after `inside`.

**Comment by AmeySingh** [comment]
I did that. Still not working.

**Comment by AmeySingh** [comment]
@erictleung 
![screenshot 2](https://cloud.githubusercontent.com/assets/19966908/16559295/94a7a5ea-4209-11e6-882f-98cfe9558bc2.png)

**Comment by fmd123** [comment]
I am having the exact same problem with Chrome on a mac.

I have the correct declaration that they want: 
var myStr = "I am a \"double quoted\" string inside \"double quotes\".";

but I can't pass.  Could someone please help? I'm not sure how to get past this one. 
And yes, I know that this is not the place for code help! I think this is a bug.

It does not pass the first requirement of two double quotes and four escaped quotes even though it does have all the required elements.
