### ISSUE TITLE
[beta] Clicking on Map doesn't do anything.

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#9341]

**Comment by erictleung** [comment]
Specifically for me, `Map` doesn't work was while I was on the main page http://beta.freecodecamp.com/en/. I am able to access http://beta.freecodecamp.com/en/map with no problems though.

**Comment by Bouncey** [comment]
Its not positioned correctly, so far I have only found this in the portfolio page.

![anim](https://cloud.githubusercontent.com/assets/18572518/16334683/4fe490c4-39fa-11e6-9c46-46a48a001ff3.gif)

**Comment by BerkeleyTrue** [comment]
@AkiraLaine Please add browser/OS.
@Bouncey Yeah will need @hallaathrad or someone with some css skills to help me here. I had to undo a lot of @hallaathrad css to get it to work properly in the drawer that's not an iframe.
![free_code_camp_and_freecodecamp_coreteam_-_gitter](https://cloud.githubusercontent.com/assets/6775919/16342455/1d594004-39e7-11e6-8717-52d4e4299218.png)

**Comment by hallaathrad** [comment]
The fact that you took it out is brilliant... those iframes were in fact the reason for a lot of the hacky css (iframes are bad news for scrolling cross browser, specially on tablets).

I'll wait for som further scoping of the issue before I chime in on how to sort it out 🐹

**Comment by BerkeleyTrue** [comment]
@hallaathrad I'm glad you approve 💖 

Unfortunately I don't have a Linux machine to test out what's going on. @Bouncey If you have some time to play around with the css that would be great

**Comment by Bouncey** [comment]
@berkeleytrue I'll see what I can do this evening? Push to the beta branch?

**Comment by Bouncey** [comment]
The map aside is still an iframe?
![anim](https://cloud.githubusercontent.com/assets/18572518/16354910/b6385b40-3a9e-11e6-83f4-6327fa014156.gif)

I have it in the right place, but I need it to not have a navbar in it. Currently looking at the logic of the current site and the beta to see if anything has changed

**Comment by BerkeleyTrue** [comment]
Fixed. All none react pages will now link directly to the map instead of opening the old iframe map version

**Comment by atjonathan** [comment]
@BerkeleyTrue The map aside doesn't work for me anymore. The link just brings me to /map.

[![https://gyazo.com/67a8b42218e6782ed76f0a6c8a98e2f3](https://i.gyazo.com/67a8b42218e6782ed76f0a6c8a98e2f3.gif)](https://gyazo.com/67a8b42218e6782ed76f0a6c8a98e2f3)

**Comment by BerkeleyTrue** [comment]
@atjonathan When you are on the map page the map drawer does not open.

**Comment by atjonathan** [comment]
@BerkeleyTrue, I was on the shop page when I clicked it.

**Comment by BerkeleyTrue** [comment]
> All none react pages will now link directly to the map instead of opening the old iframe map version

**Comment by atjonathan** [comment]
@BerkeleyTrue, sorry didn't catch that! This can be closed then.
