### ISSUE TITLE
[beta] CSS - Need more spacing at the bottom of tests

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9342]
![image](https://cloud.githubusercontent.com/assets/1884376/16329087/bfdb573e-39fd-11e6-9030-0072a0f0f0e2.png)

**Comment by Bouncey** [comment]
+ iframe iPhone wrapper could do with some margin-bottom

**Comment by BerkeleyTrue** [comment]
fixed
