### ISSUE TITLE
[beta] Can't login with GITHUB

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9343]
I can sign in but can't visit my portfolio page after sign in.

**Comment by Bouncey** [comment]
It worked for me? 
Ubuntu 16.04 LTS/Chrome 51

![anim](https://cloud.githubusercontent.com/assets/18572518/16342777/bbeaf066-3a2b-11e6-965e-706482968e96.gif)

**Comment by BerkeleyTrue** [comment]
These seems to be working fine @raisedadead. Can you elaborate some more?

**Comment by raisedadead** [comment]
@BerkeleyTrue I am on Windows 10 - Chrome 51.0.2704.103 m
 
![sign-in](https://cloud.githubusercontent.com/assets/1884376/16404082/40539836-3d19-11e6-9592-2a668187a574.gif)

**Comment by atjonathan** [comment]
@raisedadead, @Bouncey, @BerkeleyTrue I am having the same issue.

[![https://gyazo.com/c9ae162ec04434964abb9a8a9b2309a6](https://i.gyazo.com/c9ae162ec04434964abb9a8a9b2309a6.gif)](https://gyazo.com/c9ae162ec04434964abb9a8a9b2309a6)

**Comment by Bouncey** [comment]
I can sign in on Ubuntu in chrome and iPhone safari, will try other combinations with same OS's and Windows later on

**Comment by BerkeleyTrue** [comment]
@raisedadead @atjonathan Could either of you two pull down the PR and debug. I can't fix what I can't see.

**Comment by raisedadead** [comment]
@BerkeleyTrue I am on it, setting up the things. Will update asap.

**Comment by BerkeleyTrue** [comment]
@raisedadead ❤️

**Comment by BerkeleyTrue** [comment]
I've updated the issue title. The problem seems to be that the Github login is broken for beta. This does not appear to be an issue with React itself

**Comment by BerkeleyTrue** [comment]
@raisedadead I figured out what it was. I had removed all the users in the db but not the user identities. So when you try to log in using github, the user identity would point to a user object that no longer existed.

This should be fixed now. 


Happy Coding

**Comment by raisedadead** [comment]
@BerkeleyTrue Thanks.

**Comment by shuvongkor-barman** [comment]
I can't sign in to freeCodeCamp using my GitHub account. I used it two days ago but now it is not working.

Please Help. I don't want to loose my progress.


![01](https://user-images.githubusercontent.com/37457267/40265616-59971c6e-5b5d-11e8-984b-d35be11a06cf.jpg)
![02](https://user-images.githubusercontent.com/37457267/40265618-5ef09384-5b5d-11e8-8b29-183f3796564d.jpg)

**Comment by Bouncey** [comment]
@shuvongkor-barman can you please open a new issue, you are having problems with the main platform, this issue was for a development version of freeCodeCamp.
