### ISSUE TITLE
[beta] Code vanishes in JavaScript Challenges

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9344]
1. I have write a solution.
2. I use <kbd>Ctrl</kbd> + <kbd>Enter</kbd> once.
3. The challenge is submitted.

At this point my code from the editor vanishes.

Refer:
![code-vanished](https://cloud.githubusercontent.com/assets/1884376/16329150/3664836c-39fe-11e6-8189-bcc4334658d6.PNG)

**Comment by BerkeleyTrue** [comment]
Can't replicate. Anyone getting this?
![free_code_camp](https://cloud.githubusercontent.com/assets/6775919/16401914/404d1690-3c9d-11e6-8ef4-4fca054457e4.png)

**Comment by raisedadead** [comment]
Strange its not reproducible for me either now. Will observe once again, and re-open.
