### ISSUE TITLE
[beta] /about redirects to map

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9345]
![](https://i.gyazo.com/03e2736792ece185459bc64a40734350.gif)

**Comment by Bouncey** [comment]
This issue PLUS on front page, /wiki is `target="_blank"` to map.

If not related, I will split to a separate issue.

![anim](https://cloud.githubusercontent.com/assets/18572518/16334879/8c07d2c2-39fb-11e6-8103-3ce77b52682f.gif)

**Comment by Bouncey** [comment]
Related?

/commit links to map

![anim](https://cloud.githubusercontent.com/assets/18572518/16335203/4a214120-39fd-11e6-94d2-57ca7220a8a6.gif)

**Comment by BerkeleyTrue** [comment]
These are all related to the language routing system.

**Comment by BerkeleyTrue** [comment]
Fixed the about problem but didn't see the commit issue. Will address.

**Comment by BerkeleyTrue** [comment]
Fixed! Thanks @atjonathan and @Bouncey for finding these two!

**Comment by ric026** [comment]
Memperbaiki server
