### ISSUE TITLE
[beta] Map doesn't get filtered when I type into the search box

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9346]
![](https://www.evernote.com/l/Ar_c1zFoUhVPXJA5-IuKvmvNZ7le2-tKVP0B/image.png)

**Comment by BerkeleyTrue** [comment]
This is on my list.

**Comment by BerkeleyTrue** [comment]
Moving my list to issue tracker so I'll reopen this.

**Comment by BerkeleyTrue** [comment]
This one is quite tuff. Finding the solution that would take the least time to implement while still being performant and meeting the requirements is not that easy.

I think the way forward is to use a tree structure that represents the map list (which is actually a tree).

When the user updates the filter regex the list of challenges, which in this case are the leaves of the tree.

Then recur up a node (block) and check whether all those challenges are filtered out. remove if true
Then recur up a node (superblock) and check whether all those blocks are empty (challenges all filtered out). Remove if true.

This logic ends up duplicating the DOM structure, which is then used to update the virtual Dom through react, which is then used to update the actual DOM.

Not ideal, but I can't think of a way that is performant and does not involve holding state in react components.

This can be changed at some later date.

**Comment by BerkeleyTrue** [comment]
Live on beta
