### ISSUE TITLE
[beta] Un-populated Challenges Not Disabled in Map

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9349]
Learn Sass Challenges,
Learn React Challenges,
Learn D3 Challenges,
Learn Accessibility Challenges,
Learn Agile Challenges,
Learn Computer Science Challenges,
Learn Data Visualization Challenges,
Learn Embedded Internet of Things Challenges,
Learn Game Development Challenges,
Learn Gamification Challenges,
Learn Machine Learning Challenges,
Learn Math for Progrmmers Challenges,
Learn Mobile JavaScript Development Challenges,
Learn DevOps Challenges,
Learn Software Engineering Principles Challenges,
Learn Statistics Challenges,
Learn Tools Challenges,
Learn User Experience Design Challenges,
Learn Visual Design Challenges

![anim](https://cloud.githubusercontent.com/assets/18572518/16334108/02be3d0c-39f7-11e6-838e-f3cc1d41d040.gif)

**Comment by BerkeleyTrue** [comment]
@Bouncey Those challenges are not disabled during development, but yes they need to be disabled on the beta site.

**Comment by BerkeleyTrue** [comment]
Fixed in beta
