### ISSUE TITLE
[beta] Reset, Help and Bug Buttons Do Not Show Modals

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9350]
Ubuntu 16.04 LTS/Chrome 51

Tried in random challenges from HTML5, Bootstrap, jQuery, Basic JS, JSON etc...

![anim](https://cloud.githubusercontent.com/assets/18572518/16333940/0ad301b8-39f6-11e6-989a-678ebc4a782c.gif)

**Comment by Bouncey** [comment]
![anim](https://cloud.githubusercontent.com/assets/18572518/16333940/0ad301b8-39f6-11e6-989a-678ebc4a782c.gif)

**Comment by BerkeleyTrue** [comment]
Live on Beta
