### ISSUE TITLE
Correct solution not detected

### ISSUE THREAD

**Issue by PPeMg** [FreeCodeCamp/FreeCodeCamp#9352]
#### Challenge Name

Inventory Update

#### Issue Description

I think i've found a solution for the challenge and when i test it, it always returns the correct answer, but there is any problem which doesn't let me continue. I've checked all the test guidelines and it works for all of them.

#### Browser Information

* Browser Name, Vivaldi 1.2: 
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Laptop SONY Vaio VGN-Z5

#### Your Code

```js
// If relevant, paste all of your challenge code in here
var myInventory = {};

function updateInventory(arr1, arr2) {
    // All inventory must be accounted for or you're fired!
  arr1.reduce(function(anterior, actual){
    //inventory += actual[1] + '////';
    if(myInventory.hasOwnProperty(actual[1])){
      myInventory[actual[1]] += actual[0];
    } else {
      myInventory[actual[1]] = actual[0];
    }
    
  }, []);
  
  arr2.reduce(function(anterior, actual){
    //inventory += actual[1] + '////';
    if(myInventory.hasOwnProperty(actual[1])){
      myInventory[actual[1]] += actual[0];
    } else {
      myInventory[actual[1]] = actual[0];
    }
    
  }, []);
  
  var newInventory = [];
  
  for(var propiedad in myInventory){
    newInventory.push([myInventory[propiedad], propiedad]);
  }
  
  newInventory.sort(function (a, b) {
        if (a[1] > b[1]) {
            return 1;
        }
        if (a[1] < b[1]) {
            return -1;
        }
        return 0;
    });
  
  arr1 = newInventory;
  
 return arr1;
}

updateInventory([[21, "Bowling Ball"], [2, "Dirty Sock"], [1, "Hair Pin"], [5, "Microphone"]], [[2, "Hair Pin"], [3, "Half-Eaten Apple"], [67, "Bowling Ball"], [7, "Toothpaste"]]);

/*
// Example inventory lists
var curInv = [
    [21, "Bowling Ball"],
    [2, "Dirty Sock"],
    [1, "Hair Pin"],
    [5, "Microphone"]
];

var newInv = [
    [2, "Hair Pin"],
    [3, "Half-Eaten Apple"],
    [67, "Bowling Ball"],
    [7, "Toothpaste"]
];

//updateInventory(curInv, newInv);
*/
```

#### Screenshot

![pruebaerror](https://cloud.githubusercontent.com/assets/6950370/16335034/bd20f2cc-3a04-11e6-962c-320355545794.png)

**Comment by BKinahan** [comment]
Your use of the global variable `myInventory` is not compatible with the way the tests are run (eg `myInventory` is not reset to an empty object between tests, so any tests after the first will start with incorrect values for that variable). Moving `var myInventory = {};` within the function fixes your problem.

If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Issues are for reporting problems with the challenges or web site.
Happy coding!

**Comment by Bouncey** [comment]
Related to #9199 .

As suggested by @BKinahan , move your global variable inside the function. We run multiple tests to avoid campers 'hard coding' the results in order to pass.

**Comment by PPeMg** [comment]
Sorry, i dind't know that fact. 

I posted it here because i thought it was a system error and it should be fixed. Again, sorry for the inconveniences. And thanks for your quick response. :100:

**Comment by raisedadead** [comment]
@PPeMg thanks for reporting, and no inconvenience caused, please keep reporting. 
But do make sure you go though [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).

Closing as duplicate.
