### ISSUE TITLE
/Facebook Target

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9353]
All social media links on About page are `target="_blank"` except Facebook.

Edit [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/resources/about.jade#L80) in `server/views/resources/about.jade` to make the link open in a new window, like the other social media links.

Be sure to follow the [Contributor's Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). If you need any help, head over to the [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room.

Good luck and thanks for contributing :tada:

**Comment by adamisntdead** [comment]
I will give it a go

**Comment by adamisntdead** [comment]
One minute, the commits went weird
