### ISSUE TITLE
[beta] Invert Success 'Toast' button

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9354]
It's difficult to see the button and hard to read.

![anim](https://cloud.githubusercontent.com/assets/18572518/16335808/a7899e40-3a00-11e6-823a-6b2b228d0000.gif)

**Comment by BerkeleyTrue** [comment]
Move to a different toast notification components that follow closer to googles guidelines.

Fixed in beta
