### ISSUE TITLE
Stand in line challenge - wrong validation

### ISSUE THREAD

**Issue by Tzahile** [FreeCodeCamp/FreeCodeCamp#9355]
#### Challenge Name: Stand in Line

https://www.freecodecamp.com/challenges/stand-in-line

#### Issue Description

When using push and shift function, the validation "nextInLine([5,6,7,8,9], 1) should return 5" shows I'm wrong.
However, when inserting manually the array '[5,6,7,8,9]' to testArr, and the argument '1' when calling the function, it returns '5'.

#### Browser Information

* Browser Name, Version: Chrome, 51.0.2704.84 (64-bit)
* Operating System: Ubuntu 14.04
* Mobile, Desktop, or Tablet: desktop

####  Code

```js
function nextInLine(arr, item) {
  testArr.push(item);
  item = testArr.shift();
  return item;  // Change this line
}
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
```

#### Screenshot

![screenshot114](https://cloud.githubusercontent.com/assets/13683050/16337722/3c03d6e8-3a20-11e6-8c77-79e7df6d850a.png)

**Comment by heldersepu** [comment]
You should be using the parameter in your function not testArr

**Comment by heldersepu** [comment]
Your code:
```js
function nextInLine(arr, item) {
  testArr.push(item);
  item = testArr.shift();
  return item;  // Change this line
}
```

Correct code:
```js
function nextInLine(arr, item) {
  arr.push(item);
  return arr.shift();  // Change this line
}
```

**Comment by Tzahile** [comment]
Got it, thanks.
