### ISSUE TITLE
[beta] Navigation Links aren't responsive

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9356]

**Comment by BerkeleyTrue** [comment]
@atjonathan Please include description/images and browser/os information.

**Comment by atjonathan** [comment]
This issue works fine for me on a different computer, so can't reproduce now :disappointed:

**Comment by BerkeleyTrue** [comment]
Cool. It helps to capture screen caps or gifs if you can for next time
