### ISSUE TITLE
Github Gist Export - Feature Suggestion

### ISSUE THREAD

**Issue by adamisntdead** [FreeCodeCamp/FreeCodeCamp#9360]
#### Feature Suggestion

Possibility of having a button to export a solution to a github gist? Might be handy for some... Sould I make it?

**Comment by raisedadead** [comment]
@adamisntdead there is already an open issue #5138.
Closing in favor of that, please feel free to follow along.

**Comment by adamisntdead** [comment]
Didn't Know That Was There!
