### ISSUE TITLE
[beta] Instruction Panel Doesn't Return to Top

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9361]
Ubuntu 16.04 LTS/Chrome 51

Instructions panel remains scrolled when new challenge is rendered.

![anim](https://cloud.githubusercontent.com/assets/18572518/16341178/c46de1c4-3a23-11e6-89eb-20a21deec3af.gif)

**Comment by BerkeleyTrue** [comment]
fixed in beta
