### ISSUE TITLE
Challenges that need an output to the user need to be wrapped in console log.

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#9363]
The new challenge framework will no longer automatically infer the output of a challenge. These challenge will need to have their final statement wrapped in a `console.log`.

This can be done in parallel with the beta release.

For example:

This outputs the the return of factorialize(5) to the output box in the old framework. Not in the new.

``` js
function factorialize(num) {
  return num;
}

factorialize(5);
```

It should explicitly output to console like so:

``` js
function factorialize(num) {
  return num;
}

console.log(factorialize(5));
```

Most Javascript/Algorithm challenges will need to be updated. This can be done now without any adverse effect on the current site.

**Comment by kalila855** [comment]
I can take it!

**Comment by Bouncey** [comment]
@kalila855 How are you getting on with this?

**Comment by BerkeleyTrue** [comment]
This is still up for grabs.

**Comment by andela-bebowe** [comment]
@BerkeleyTrue Can I take this ?

**Comment by raisedadead** [comment]
@andela-bebowe yup go ahead!

**Comment by andela-bebowe** [comment]
@BerkeleyTrue @raisedadead Just to be clear, am I to log the output for every challenge that has an output. Or are there specific challenges that need this I am currently working on the Basic Javascript Challenges.

**Comment by chiptus** [comment]
@Bouncey @BerkeleyTrue Probably will be good idea to separate this into sub tasks so more people can do it, and so we know which challenges should get this done
