### ISSUE TITLE
About Page - Shop Link Should Open a New Page

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9364]
Please edit [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/33d565e5651cf6f95f420a57bc2a74790a5b2113/server/views/resources/about.jade#L170) in `/server/views/resources/about.jade`. The 'shop' link should open a new page when clicked. Similar to the link to Quincey's Quora page.

Be sure to follow the [Contributor's Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). If you need any help, head over to the [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room.

Good luck and thanks for contributing :tada:

**Comment by Manish-Giri** [comment]
May I try this?

**Comment by Bouncey** [comment]
@manish-giri I would like someone who hasn't contributed to FreeCodeCamp before to give it a go. If it is still here tomorrow, then sure. 

There are plenty of issues to choose from. If you need help and guidance with an issue, try the HelpContributors chat room on gitter.im

**Comment by zk433** [comment]
Can I have a go?

**Comment by Bouncey** [comment]
Yes @zk433 certainly, I look forward to it

**Comment by jarenescueta731** [comment]
I haven't seen a pull request for this yet, can i try? I haven't been able to contribute yet, and I could use the practice.

**Comment by zk433** [comment]
@jarenescueta731 I'm already working on it but it's a weekend so I haven't had enough time to finish setting things up. 
@Bouncey are you in a hurry with this? I should have it finished by tomorrow.

**Comment by jarenescueta731** [comment]
@zk433 alrighty, the first-time setup for contributing to FreeCodeCamp is still confusing me anyways

**Comment by zk433** [comment]
@jarenescueta731 Hi Jaren, if you still want to, go for it. I'm taking too long setting things up, I may have taken on way too much at this point of my learning journey.

**Comment by MaxySpark** [comment]
may I try this?
I haven't contributed yet

**Comment by ladybugtju** [comment]
Hello
Could you please specify which part of the text you want to link to which page. I don t see any error and checked Quincey s page for any new shop but couldn t find it. Thanks

**Comment by Oxyrus** [comment]
Should be fixed in #9416

**Comment by ladybugtju** [comment]
+1

**Comment by ladybugtju** [comment]
:+1:
