### ISSUE TITLE
<h1>Hello</h1>

### ISSUE THREAD

**Issue by xaxiclouddev** [FreeCodeCamp/FreeCodeCamp#9370]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/51.0.2704.104 Mobile/13F69 Safari/601.1.46</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello</h1>

```

**Comment by woofiewilly** [comment]
What is the issue? You have given no description of what is wrong

**Comment by vbXhaiden** [comment]
if your looking to complete the assignment, you need to change the text to "Hello World".

At the bottom of the page, after clicking the "Run Tests" button, there is a description listing things you may want to look over if it doesn't pass and advance to the next lesson.

**Comment by raisedadead** [comment]
![image](https://cloud.githubusercontent.com/assets/1884376/16355415/7a426f42-3ad3-11e6-9421-1e3e2e4e9c21.png)

@vbXhaiden this what I see at the bottom, are you getting something else?
Mind sharing a screenshot.

**Comment by vbXhaiden** [comment]
@raisedadead What exactly are you having a problem with? Are you not able to advance to the next lesson?

**Comment by dwd2010** [comment]
umm everyone, nothing with with that challenge.   that code is incorrect.

**Comment by raisedadead** [comment]
Closing as not a issue with the website.
Happy coding.
