### ISSUE TITLE
Trigger Google Analytics event when navbar "chat" button clicked

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9373]
We are trying to figure out how frequently the navbar chat button is clicked.

**Comment by sthodup1** [comment]
I think I can do this. The file located [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/main.js) has the chat opening functionality. If I need the analytics.js library to trigger an event, is it okay for me to put an import statement at the top of this file, or is the library already available for use?

**Comment by jondcoleman** [comment]
@sthodup1 made this change before realizing you were planning to do this.  Sorry about that.  If you've got a change already in place I'll withdraw the PR.

**Comment by sthodup1** [comment]
@jondcoleman no worries. I haven't made the change already
