### ISSUE TITLE
Issue with revisiting old challenges

### ISSUE THREAD

**Issue by jessmear** [FreeCodeCamp/FreeCodeCamp#9378]
When I go back to previous challenges and repeat them, everything works great until I get the success box, but then it's not entirely filled out and the button is not clickable to go on. The exercise is already marked complete and I can use the map to go forward, but this has happened several times so it seems like it should be addressed.

I am on a Mac running 10.7.3, using Firefox 47.0 

![fcc_problem](https://cloud.githubusercontent.com/assets/1884376/16539381/0245f0f4-405f-11e6-8497-431f753e2be9.jpg)

Challenge [Target HTML Elements with Selectors Using jQuery](https://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22button%22).addClass(%22animated%20bounce%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by jessmear** [comment]
To clarify, it does not happen every time. Just sometimes.

**Comment by Bouncey** [comment]
cc  @FreeCodeCamp/issue-moderators 

We will monitor this issue, we need more data to be able to diagnose the problem. Please, if it happens again, comment on this issue.

For future reference, you can drag and drop images into the comment box and GitHub will upload it for you :+1:

**Comment by jessmear** [comment]
Still going through jQuery again and the same thing happened. This time I can be more specific because I was watching for it:

1. Finished "Disable an Element Using jQuery".
2. Proceeded to the next thing as normal, submitting the challenge and moving on worked correctly.
3. Left the window to test the code in my own environment.
4. It didn't work, realized I must have a typo, couldn't pinpoint it. 
5. Hit the back button to go back to "Disable an Element Using jQuery".
6. Checked my code and fixed it locally. 
7. Tried to proceed again and got the empty green non-working button in the success box. 

So maybe this only happens after I hit "back" to go to a previous challenge? I'll keep an eye on it. :)

**Comment by raisedadead** [comment]
@jessmear this is strange. 

1. Have you seen any one else get the same error, also can you specify the region you are located?
2. Do the [common trouble shooting steps](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) still leave you with this issue.
3. Can you also help us by [opening the browser's Dev Tools](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) and dump any weird logs that you may see there.

Thanks a lot.

**Comment by raisedadead** [comment]
Closing as stale. Please comment if you are still facing this.
