### ISSUE TITLE
Correct code, no color change.

### ISSUE THREAD

**Issue by bmur961** [FreeCodeCamp/FreeCodeCamp#9386]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E.%0A

#### Issue Description

I have the correct code which I have verified with the gitter community but still the header will not change to red. I have no other means of doing this training than on my phone which is an Android. I cannot proceed with these lessons until this is rectified.

#### Browser Information

I only have access to this via my Android using Google chrome

* Browser Name, Version: Google chrome
* Operating System: Android 
* Mobile, Desktop, or Tablet: Mobile

#### Your Code

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere 
```js
```

**Comment by bmur961** [comment]
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere

**Comment by bmur961** [comment]
I can't put code up here because it won't post without executing the code

**Comment by Bouncey** [comment]
@bmur961 The way we test your code is, we encode it into the URL, then extract it behind the scenes for testing. By comparing your code to my code (which passes) like this (your code, my code):

`%20.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red`
`%20.red-text%20%7B%0A%20%20%20%20color%3A%20red`

We can see that there are some additional characters in your code. Try clicking the reset button and start again. If you still have problems passing the challenge with the correct code, comment on this issue.

Hope this helps

Many thanks.

**Comment by dwd2010** [comment]
I found a problem because this.
```
<span style="padding-right: 0.1px;"> &nbsp;  <span class="cm-property">color</span>: <span class="cm-keyword">red</span>;</span>
```
`&nbsp;` make this challenges wont passed.
so, it is not their fault.  they need to reset then try challenge again.

**Comment by divya455** [comment]
I'm also having same problem regarding color, i tried to reset it but also its if no use. How can i complete this challenge now

**Comment by arun1595** [comment]
This is not the space for getting help with the challenges. Please get help from [FCC Help chatroom](https://gitter.im/FreeCodeCamp/Help)

**Comment by erictleung** [comment]
@bmur961 apologies that you are having this issue. This is actually a known issue with Android phones rendering the CSS (issue was filed here #7753). I would advise you, if you have access, to try this on a desktop or laptop. This *should* solve the issue. Nonetheless, I'll be closing this issue because it is a duplicate issue and precedence goes to the older issue. Happy coding!
