### ISSUE TITLE
validation error with multiple returns

### ISSUE THREAD

**Issue by yuens1002** [FreeCodeCamp/FreeCodeCamp#9387]
Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=%2F*jshint%20esversion%3A%206%20*%2F%0A%2F%2F%20use%20a%20loop%20to%20find%20all%20odd%20fib%20numbers%0A%2F%2F%20%20%20using%20num%20to%20exit%20the%20loop%0A%2F%2F%20store%20all%20odd%20numbers%20in%20an%20array%20%0A%2F%2F%20use%20reduce%20to%20sum%20%0A%0Avar%20%0A%20%20arrSum%20%3D%20%5B1%2C1%5D%2C%0A%20%20arrOdd%20%3D%20%5B%5D%3B%0A%20%20%20%20%0Afunction%20oddNum%20(value)%20%7B%0A%20%20if%20(value%252%20%3E%200)%20%7B%0A%20%20%20%20return%20value%3B%0A%20%20%7D%20%0A%7D%0A%0Afunction%20sumFibs(num)%20%7B%0A%20%20var%20i%20%3D%200%3B%0A%20%20do%20%7B%20%0A%20%20%20%20arrSum%5Bi%2B2%5D%20%3D%20arrSum%5Bi%5D%2BarrSum%5Bi%2B1%5D%3B%0A%20%20%20%20i%2B%2B%3B%0A%20%20%7D%20while%20((arrSum%5Bi%5D%2BarrSum%5Bi%2B1%5D)%20%3C%3D%20num)%3B%0A%20%20%0A%20%20arrOdd%20%3D%20arrSum.filter(oddNum)%3B%0A%20%20return%20arrOdd.reduce((prev%2C%20curr)%20%3D%3E%20prev%20%2B%20curr%20)%3B%0A%7D%0A%0AsumFibs(75025)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code does produce the correct answer with any number.  I believe the validation is being confused by multiple return statements in the code. 

My code:
```javascript
/*jshint esversion: 6 */
// use a loop to find all odd fib numbers
//   using num to exit the loop
// store all odd numbers in an array 
// use reduce to sum 

var 
  arrSum = [1,1],
  arrOdd = [];
    
function oddNum (value) {
  if (value%2 > 0) {
    return value;
  } 
}

function sumFibs(num) {
  var i = 0;
  do { 
    arrSum[i+2] = arrSum[i]+arrSum[i+1];
    i++;
  } while ((arrSum[i]+arrSum[i+1]) <= num);
  
  arrOdd = arrSum.filter(oddNum);
  return arrOdd.reduce((prev, curr) => prev + curr );
}

sumFibs(75025);
```

**Comment by BKinahan** [comment]
Your use of the global variables `arrSum` and `arrOdd` is not compatible with the way the tests are run (eg `arrOdd` is not reset to an empty array between tests, so any tests after the first will start with incorrect values for that variable). Moving both of these variable declarations within the `sumFibs` function as shown below fixes your problem.

If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Issues are for reporting problems with the challenges or web site.
Happy coding!

```js
function sumFibs(num) {
  var 
  arrSum = [1,1],
  arrOdd = [];
  var i = 0;
  do { 
    arrSum[i+2] = arrSum[i]+arrSum[i+1];
    i++;
  } while ((arrSum[i]+arrSum[i+1]) <= num);
  
  arrOdd = arrSum.filter(oddNum);
  return arrOdd.reduce((prev, curr) => prev + curr );
}
```

**Comment by raisedadead** [comment]
Thanks for the explaination @BKinahan 

@yuens1002 this is a known topic, not issue per say, but we tracking the same in #9199, please feel to follow along there.

Thanks, and happy coding.
