### ISSUE TITLE
help me fix this bug

### ISSUE THREAD

**Issue by mukulsahi52** [FreeCodeCamp/FreeCodeCamp#9388]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%0A%20%20%7B%0A%20%20%20%20color%3Ablue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%20class%3D%22blue-text%22%3EHello%20world%3C%2Fh1%3E%0A%3Ch1%20class%3D%22blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text 
  {
    color:blue;
  }
</style>
<h1 class="pink-text" class="blue-text">Hello world</h1>
<h1 class="blue-text">Hello World!</h1>

```

**Comment by dwd2010** [comment]
@mukulsahi52 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by Bhargavbonu** [comment]
I am facing the same problem!
Override Styles in Subsequent CSS

My Code:
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text{
    color: blue;
  }
</style>
<h1 class="blue-text" class="pink-text"> Hello World!</h1>

I am unable to run it! Please someone help me!

**Comment by dwd2010** [comment]
@Bhargavbonu, You could go to [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.
this place for not ask help.
Happy Coding!
