### ISSUE TITLE
whats wrong with this code?

### ISSUE THREAD

**Issue by steelman80** [FreeCodeCamp/FreeCodeCamp#9390]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20h1%7B%0A%20%20%20%20.pink-text%3B%0A%20%20%20%20color%3Apink%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  h1{
    .pink-text;
    color:pink
  }
</style>
<h1>Hello World!</h1>

```

**Comment by Petar-np** [comment]
This is the right answer, there is no issue
```
<style>
 body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text{
    
    color:pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>
```

**Comment by raisedadead** [comment]
@steelman80 thanks for reporting, but Github issues are not for coding help, please consult chat rooms for any assistance

[Help Chat Room](https://gitter.im/FreeCodeCamp/Help).
[JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).
