### ISSUE TITLE
Typo - Basic Javascript - Replacing If Else Chains with Switch

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/FreeCodeCamp#9393]
Challenge [Replacing If Else Chains with Switch](https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch#?solution=%0Afunction%20chainToSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(val%20%3D%3D%3D%20%22bob%22)%20%7B%0A%20%20%20%20answer%20%3D%20%22Marley%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%2042)%20%7B%0A%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%2099)%20%7B%0A%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%207)%20%7B%0A%20%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AchainToSwitch(7)%3B%0A%0A) has a minor typo. Could probably be suitable as a first-timer-contribution.

![Typo showed in screenshot](http://i.imgur.com/ZNxsdIa.png?1)

I think it would make sense to rephrase 
**`if` / `if else` statements**

into

**`if` / `else if`statements**.

This would make the instructions more aligned with the actual syntax.

**Comment by raisedadead** [comment]
@Greenheart thanks for reporting.

Potential contributors (first timers only) please have a look at [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3605) and [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L3610) and change the same to be in tune as proposed above.

Thanks and happy fixing.

**Comment by jessmear** [comment]
I can do it. Do I need to do anything other than make the changes

**Comment by blakemanzo** [comment]
Happy to have a go also

**Comment by raisedadead** [comment]
@jessmear just change those lines and make a pull request and make sure you go through the  [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by rajkthakur** [comment]
@raisedadead I am also the first timer is this already assigned to @jessmear.

**Comment by raisedadead** [comment]
Hey @rajkthakur sorry about the delay in responding, seems there is already a pull request, please checkout any of the `help wanted + first-timers+only` issue on the issues page.

All such issues are open to all, until someone opens a pull request (first one to open one gets the issue to be closed), no permissions required.

Looking forward for a contribution from you! Happy fixing!

**Comment by rajkthakur** [comment]
@raisedadead thankyou :)

**Comment by ladybugtju** [comment]
Hi there 
The same problem seems to persist in the title. Would that be something to fix? Would give it a shot in case. Let me know

**Comment by atjonathan** [comment]
@ladybugtju, as discussed in the pull request, we decided not to change the name of the challenge. This brings up lots of issues with campers portfolios etc.

**Comment by ladybugtju** [comment]
👍 🎱
