### ISSUE TITLE
Steamroller: First Test Fails Even If I Literally Code To Return The Answer

### ISSUE THREAD

**Issue by lair001** [FreeCodeCamp/FreeCodeCamp#9396]
Challenge [Steamroller](https://www.freecodecamp.com/challenges/steamroller#?solution=function%20steamrollArray(arr%2CflatArr)%20%7B%0A%20%20%2F%2F%20I%27m%20a%20steamroller%2C%20baby%0A%20%20var%20answer%20%3D%20%5B%22a%22%2C%20%22b%22%5D%3B%0A%20%20if%20(arr%20%3D%3D%20%5B%5B%5B%22a%22%5D%5D%2C%20%5B%5B%22b%22%5D%5D%5D)%20%7B%0A%20%20%20%20return%20answer%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20if%20(!flatArr)%20%7B%0A%20%20%20%20flatArr%20%3D%5B%5D%3B%0A%20%20%7D%0A%20%20%0A%0A%20%20%0A%0A%20%20%20%20%0A%20%20%20%20for%20(i%3D0%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(arr%5Bi%5D.length%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%20else%20if%20(Array.isArray(arr%5Bi%5D))%20%7B%0A%20%20%20%20%20%20%20%20steamrollArray(arr%5Bi%5D%2CflatArr)%3B%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20flatArr.push(arr%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%20%20%0A%0A%0A%20%20return%20flatArr%3B%0A%7D%0A%0AsteamrollArray(%5B%5B%5B%22a%22%5D%5D%2C%20%5B%5B%22b%22%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function steamrollArray(arr,flatArr) {
  // I'm a steamroller, baby
  var answer = ["a", "b"];
  if (arr == [[["a"]], [["b"]]]) {
    return answer;
  }
  
  if (!flatArr) {
    flatArr =[];
  }
  
  for (i=0; i < arr.length; i++) {
      if (arr[i].length === 0) {
        
      } else if (Array.isArray(arr[i])) {
        steamrollArray(arr[i],flatArr);
      } else {
        flatArr.push(arr[i]);
      }
 }
    


  return flatArr;
}

steamrollArray([[["a"]], [["b"]]]);

```
Yes, I literally coded a return with the correct answer and the first test still fails.  The tester somehow thinks that ["a", "b"] is ["a"].  My code passes the other tests.

**Comment by erictleung** [comment]
@lair001 check what happens when you do the following in your JS interpreter.

```js
[[["a"]], [["b"]]] == [[["a"]], [["b"]]]
```

And from the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Equality_operators) on using the equality operator `==`: 

> If **both operands are objects**, then JavaScript compares internal references which are equal when operands refer to the same object in memory.

When comparing objects, like you are here, the equality operator doesn't work like you think it does. Hope that helps. Closing as not an issue with the tester. Happy coding!
