### ISSUE TITLE
GitHub user not detected

### ISSUE THREAD

**Issue by jrogatis** [FreeCodeCamp/FreeCodeCamp#9400]
Challenge [Save your Code Revisions Forever with Git](https://www.freecodecamp.com/challenges/save-your-code-revisions-forever-with-git) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
ACTUAL                             EXPECTED
------                             --------
"{ [Error: Command failed: /bin/sh -c git config user.username" != "Username added to Git config!"
"]"                             != "You're on GitHub!"            
"  killed: false,"              != "Username same on GitHub and"  
"  code: 1,"                    != "Git config!"                  
"  signal: null,"               != ""                             
"  cmd: '/bin/sh -c git config user.username' }" != null                           
""                              != null                           
# FAIL

Your solution to GITHUBBIN didn't match the expected output.
Try again!
-----------------------------------------------------------------

jrogatis:~/workspace (master) $ git config --list
user.name=jrogatis
user.email=jrogatis@conecta.net.br
core.editor=nano
core.whitespace=off
core.excludesfile=~/.gitignore
advice.statusuoption=false
color.ui=true
push.default=current
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
user.name=jrogatis
user.email=jrogatis@conecta.net.br
jrogatis:~/workspace (master) $ 

I have a valid acc at github

**Comment by raisedadead** [comment]
@jrogatis

While we try to reproduce and confirm this, can you check the below:

1. Your GitHub account has the SSH key that is created/saved in the C9 workspace.
2. Your GitHub Username and Email are the same as that in the C9 Workspace.

Thanks for reporting.

**Comment by raisedadead** [comment]
@jrogatis I could pass the challenge just fine.

```sh
raisedadead:~/workspace/fcc-issue-test (master) $ git-it verify
Verifying "GITHUBBIN"...

ACTUAL                             EXPECTED
------                             --------
"Username added to Git config!"    "Username added to Git config!"
"You're on GitHub!"                "You're on GitHub!"            
"Username same on GitHub and"      "Username same on GitHub and"  
"Git config!"                      "Git config!"                  
""                                 ""                             
# PASS

Your solution to GITHUBBIN passed!
-----------------------------------------------------------------

You have 7 challenges left.
Type `git-it` to show the menu.

-----------------------------------------------------------------

raisedadead:~/workspace/fcc-issue-test (master) $ 
```


From the output in your comment above this looks like you haven't configured your `username`

have you done `git config --global user.username <USerNamE>`?

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue still occurs!
