### ISSUE TITLE
How am i supposed to solve this when I have to delete the trailing tags?

### ISSUE THREAD

**Issue by Hayden8ike** [FreeCodeCamp/FreeCodeCamp#9401]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->

```

**Comment by Bouncey** [comment]
@Hayden8ike Please describe the issue in more detail.

**Comment by raisedadead** [comment]
@Hayden8ike if you need any assistance to coding, please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

GitHub issues are for bugs in the Codebase only.

Thanks and Happy Coding!

**Comment by Hayden8ike** [comment]
@raisedadead I need help coding. I cannot pass the ending trail algorithm.

**Comment by raisedadead** [comment]
@Hayden8ike Please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).
