### ISSUE TITLE
Add One Click Actions to Email - Sign In / Confirm / Verify

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#9402]
https://developers.google.com/gmail/markup/reference/one-click-action

**Comment by QuincyLarson** [comment]
@raisedadead is this how this works on your passwordless branch?

**Comment by raisedadead** [comment]
Currently, the user will have to open the email and click on a link like any other email. This feature is a Gmail only (maybe yahoo allows it too), where you see something like below.

![image](https://cloud.githubusercontent.com/assets/1884376/21633268/95eaacfe-d273-11e6-8ae3-b7d30eb99d18.png)

Instead of the View Issue, it will display login and will directly hit an endpoint with the the auth token, logging in the user instantly.

I am going to integrate this some time after we have a stable passwordless working on the production.

**Comment by QuincyLarson** [comment]
@raisedadead thanks for the additional explanation. I agree that this would be a useful feature, and that it should be implemented later on after we finish more pressing authentication issues.

**Comment by kerbylane** [comment]
And how do I turn it off?  When I've got my window shrunk down these take up too much room and hide more useful fields.
<img width="741" alt="screen shot 2017-04-10 at 9 34 32 am" src="https://cloud.githubusercontent.com/assets/4228228/24872098/04fd067a-1dd1-11e7-8f14-776ea9d379f2.png">

**Comment by texas2010** [comment]
@kerbylane 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by raisedadead** [comment]
@kerbylane your issue is unrelated to this feature request. Please proceed with unsubscribe as mentioned by @texas2010 above.

**Comment by QuincyLarson** [comment]
@raisedadead this is an awesome feature idea, and will really enhance the passwordless user experience. How difficult is this to implement? Would you be interested in implementing it?

**Comment by raisedadead** [comment]
@QuincyLarson yes, I intend to. But let's wait for a stable beta with passwordless well tested in the field.

**Comment by QuincyLarson** [comment]
@raisedadead OK. Sounds good.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
