### ISSUE TITLE
Object Oriented and Functional Programming DESPERATELY needs rewrite!

### ISSUE THREAD

**Issue by manicmarvin** [FreeCodeCamp/FreeCodeCamp#9403]
Challenge [Iterate over Arrays with map](https://www.freecodecamp.com/challenges/iterate-over-arrays-with-map#?solution=var%20timesFour%20%3D%20oldArray.map(function(val)%7B%0A%20%20return%20val%20*%204%3B%0A%7D)%3B%0A%0A%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray%3B%0A) has an issue.

The description of this waypoint is completely inadequate. It reads:

>The map method is a convenient way to iterate through arrays. Here's an example usage:
>```
>var timesFour = oldArray.map(function(val){
>  return val * 4;
>});
>```
>The map method will iterate through every element of the array, creating a new array with values that have been modified by the callback function, and return it. Note that it does not modify the original array.

>In our example the callback only uses the value of the array element (the val argument) but your callback can also include arguments for the index and array being acted on.

It does not really explain the syntax, what results the map method produces and requires readers to speak CSspeak and decipher many implicit unstated things. 

I am struggling to understand anything in the section *Object Oriented and Functional Programming*, not because the concepts are difficult but because the lessons are poorly constructed. I'm referring to Crockford, Eloquent JS and Codeacademy to provide information written in a manner that I *can* understand. 

Forgive my shortness, I just hope that my suggestion that this need a rewrite is taken up.

**Comment by raisedadead** [comment]
/cc @FreeCodeCamp/issue-moderators 

Again as mentioned in #9404 we could have supplementary MDN links however let's see how this can be re-written?

**Comment by heldersepu** [comment]
I think that the challenge is clear enough 
...and at this point we should be familiar with the Read-Search-Ask

**Comment by erictleung** [comment]
@manicmarvin thanks for the feedback. Maybe we can expand the example code a bit to show what the `oldArray` is and what the `.map` function returns.

```js
var oldArray = [1, 2, 3];
var timesFour = oldArray.map(function(val){
  return val * 4;
});
console.log(timesFour); // returns [4, 8, 12]
console.log(oldArray);  // returns [1, 2, 3]
```

This line needs to be changed to

```
"<blockquote>var oldArray = [1, 2, 3];<br>var timesFour = oldArray.map(function(val){<br>&nbsp;&nbsp;return val * 4;<br>});<br>console.log(timesFour); // returns [4, 8, 12]<br>console.log(oldArray);  // returns [1, 2, 3]</blockquote>",
```

What these changes should look like

![image](https://cloud.githubusercontent.com/assets/2754821/16553683/d7ac9e26-417e-11e6-8529-4180f7aaf61f.png)

To contributors, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by manicmarvin** [comment]
@erictleung That's super clear! Thank you.

**Comment by dhcodes** [comment]
I'll take this one as my first potential commit if that's okay.

**Comment by priyanshAgarwal** [comment]
`
var oldArray = [1,2,3,4,5];

// Only change code below this line.

var addThree = oldArray.map(function(val){
  return val +3;
});

var newArray = addThree;
`
