### ISSUE TITLE
Description missing Algorithm/Details.

### ISSUE THREAD

**Issue by manicmarvin** [FreeCodeCamp/FreeCodeCamp#9404]
Challenge [Sort Arrays with sort](https://www.freecodecamp.com/challenges/sort-arrays-with-sort) has an issue.

The description uses

```
var array = [1, 12, 21, 2];
array.sort(function(a, b) {
  return a - b;
});
```

to "sort the elements from smallest to largest number".

But nowhere is this algorithmic concept described.

**Comment by manicmarvin** [comment]
In fact, the [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) explains better that how arguments are passed to `compare`,  but **not** how the sort algorithm works. 

>

**Comment by BKinahan** [comment]
Do you mean that 
> `sort` can be passed a compare function as a callback. The compare function should return a negative number if `a` should be before `b`, a positive number if `a` should be after `b`, or `0` if they are equal.

... isn't an accurate description of how the sort method determine sort order? Or do you want a lower-level understanding of the mechanics of the exact algorithm `sort` performs using these returned values?

If the former, perhaps a link to `sort` on MDN as a helpful link in the instructions would be a useful addition. If the latter, this can vary from browser to browser depending on which sorting algorithm (quicksort, etc) the developers choose to implement and explaining the details of each is not feasible in the challenge format or appropriate for this level of study.

**Comment by raisedadead** [comment]
We do have wiki's explaining the concept "sort" and campers are expected to search through them for such broader concepts, challenges are targeted towards learning the algorithm.

However a link to MDN won't hurt either, also we could have a separate issue to create video challenges to teach concepts, frankly speaking adding text in the challenge won't help, because it has been a observation that campers would tend to skip long text of explanations.

Anyone up for adding a MDN link and/or videos (on YouTube) ??

**Comment by rajkthakur** [comment]
I am first-timers. can I give it a try??

**Comment by andmckvr13** [comment]
I love the idea of adding a youtube video link! Some learners (like me) fair better with learning by being shown rather than always having to wrap their brains around the text.

**Comment by raisedadead** [comment]
@andmckvr13 we could create separate challenges teaching that. And add them to our videos section. 

Anyone up for creating a curriculum request issue on the [videos (hikes) repo](https://github.com/FreeCodeCamp/hikes).

**Comment by andmckvr13** [comment]
@raisedadead do you mean creating an issue in the hikes repo for something like this? or creating an actual sample curriculum?

**Comment by raisedadead** [comment]
I meant the former. The hikes team will then look into it. You can also later help in creating the curriculum if interested.
