### ISSUE TITLE
Can't got to the next level. Browser and text zoom level error.

### ISSUE THREAD

**Issue by babaraliny** [FreeCodeCamp/FreeCodeCamp#9407]
![freecodecamp zoom error bug can t get to next level](https://cloud.githubusercontent.com/assets/20164675/16378017/5977d5d0-3c37-11e6-851e-96e4ae3ced41.png)
![freecodecamp zoom error bug can t get to next level](https://cloud.githubusercontent.com/assets/20164675/16378050/848cc406-3c37-11e6-8573-fee72fcfd451.jpg)

Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red; p {font-size:16px;}
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by babaraliny** [comment]
My browser Zoom level and the text zoom level in chrome is set to 100% for both. I've checked it. hat is wrong ?

**Comment by raisedadead** [comment]
@babaraliny Thanks for reporting, but unfortunately your code is incorrect and github issues are reporting bugs on the website only, please consult the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) for any assistance to coding.

Thanks and Happy Coding!
