### ISSUE TITLE
Accessing Nested Objects

### ISSUE THREAD

**Issue by JamalPolaya** [FreeCodeCamp/FreeCodeCamp#9411]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects#?solution=%0A%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove%20box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyStorage.car%5B%22inside%22%5D.golvebox%3B%0Avar%20gloveBoxContents%20%3D%20%22%22%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line
myStorage.car["inside"].golvebox;
var gloveBoxContents = ""; // Change this line


```

**Comment by atjonathan** [comment]
Your code is incorrect. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by Yogesh15031993** [comment]
myStorage.car.inside['glove box'];

**Comment by stepco** [comment]
// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line
var ansver = myStorage.car.inside["glove box"];
var gloveBoxContents = ansver; // Change this line

**Comment by dwd2010** [comment]
@Yogesh15031993, @stepco 
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
