### ISSUE TITLE
Challenge Request: CSS Flexbox

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#9412]
#### Challenge Name
Request for new challenge(s)

#### Issue Description
The current challenges in the CSS section do not cover CSS Flexboxes. I think Flexboxes are an important CSS tool, and should have a couple of challenges in the current [CSS curriculum](https://www.freecodecamp.com/map-aside#nested-collapseHTML5andCSS). 

There is a detailed [FCC wiki](https://github.com/freecodecamp/freecodecamp/wiki/css-flexbox) on Flexboxes, but it would be good to have challenges in the CSS curriculum. Newcomers to the site/beginners might not necessarily reach out to the Github wiki during the early stages.

**Comment by Manish-Giri** [comment]
@atjonathan Thank You for considering my request!!

**Comment by arirawr** [comment]
@atjonathan I'd be happy to work on this!

**Comment by atjonathan** [comment]
@arirawr, awesome :smile:

**Comment by arirawr** [comment]
@atjonathan Any specific breakdown of challenges you'd like to see here? I'll think on what sections may make sense.

**Comment by atjonathan** [comment]
@arirawr, take a look [here](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) for some topics you could cover. We shouldn't really want to have any more than 6 - 8 challenges on this topic.

**Comment by arirawr** [comment]
@atjonathan Ah, my favourite web page of all time ❤️ 

I got all my dev env set up - I'll start some challenges this week!

**Comment by atjonathan** [comment]
Closing in favour of https://github.com/FreeCodeCamp/CurriculumExpansion/issues/21
