### ISSUE TITLE
Let challenge names change, without affecting portfolio

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9417]
We should be able to change the name of a challenge, without having to deal with fallout from code portfolio etc.

**Comment by arun1595** [comment]
@atjonathan Can we add some tests to make sure that for a single challenge id, the name is same both in the challenges json file and in the other json file which houses the ids and titles of challenges.

This way we don't have to worry about renaming of challenges breaking the portfolio. So, if the contributor fails to rename the challenges in both the places, our tests would report.
What do you think?

**Comment by BerkeleyTrue** [comment]
@arun1595 There is no file that has only ids and titles.

**Comment by arun1595** [comment]
@BerkeleyTrue 

I meant the json files which holds information about all the challenges in a certification.
For example, we have `seed/challenges/01-front-end-development-certification/front-end-development-certification.json`which contains the ids and titles of the bonfires and ziplines.

**Comment by BerkeleyTrue** [comment]
Those titles are never rendered. They are just used for use humans working on those files. It's kind of hard to tell one Object id from another.

**Comment by raisedadead** [comment]
Nevertheless if implemented this should take care of migrating the search from name based to id based and encoding the URL of the challenge that is stored in the user profile with id, which means while visiting the challenge the reverse look-up is also applicable.

Using challenge id's is a good idea, but is going to affect a ton of things (impact not broken):
1. The wiki which automatically loads the relevant challenge in the sidebar.
2. Current User portfolios
3. Search and Look up
4. npm run test?

Anyone looking into this should look into all these areas and if I have missed some.

**Comment by BerkeleyTrue** [comment]
This is fixed in current staging. Display Names are pulled directly from challenge

Happy Coding
