### ISSUE TITLE
Start a Node.js Server - learnyounode documentation URLs do not work

### ISSUE THREAD

**Issue by noates** [FreeCodeCamp/FreeCodeCamp#9419]
Challenge [Start a Nodejs Server](https://www.freecodecamp.com/challenges/start-a-nodejs-server) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The Cloud9 "learnyounode" challenges often contain links that look like this:
-------------------------------------------------------
 ## HINTS  
   
  For this exercise you will need to use the http core module.  
   
  Documentation on the http module can be found by pointing your browser  
  here:  
  file:///home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounod  
  e/node_apidoc/http.html  

------------------------------------------------------
My browser cannot find that page. Are we supposed to know what to substitute in the URL to make the link work?
I found this page   :https://github.com/workshopper/learnyounode/blob/master/node_apidoc/http.html

Is this the correct one?

So far I have viewed zero of the documentation URLs provided to pass the challenges.

edit:  I found this one too:
https://nodejs.org/docs/v4.4.5/api/http.html

**Comment by BerkeleyTrue** [comment]
This is an issue with [LearnYouNode](https://github.com/workshopper/learnyounode). Please report issues with the module there so the authors can address them. 

Happy Coding
