### ISSUE TITLE
faulty passing?

### ISSUE THREAD

**Issue by matthewsvm** [FreeCodeCamp/freecodecamp#942]
Challenge http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This passes when there are more than 2 arguments after the array, even if it doesn't actually delete those arguments from the array.

**Comment by LumenTeun** [comment]
Which code makes the test cases pass incorrectly?

**Comment by matthewsvm** [comment]
Here's an example of one that passed, but the returned array is [1, 1] instead of an empty array:

function destroyer(arr) {
  // Remove all the values
  
  // for each element in arr, remove each element in args that 
  // is > args[0]
  var args = Array.prototype.slice.call(arguments);
  var holder = [];
  
  var filtered = arr.filter(destroy);
  // function for above 
  function destroy(value) {
    for (i = 1; i < args.length; i++) {
      return value !== args[i] && value !== args [i + 1];
    }
  }
  return filtered;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3, 1);

// returned arr is [1, 1] instead of [ ].
