### ISSUE TITLE
Wiki `Algorithm Where Art Thou` advanced code solution is not correct

### ISSUE THREAD

**Issue by ranranking** [FreeCodeCamp/FreeCodeCamp#9421]
The code in `Advanced code solution` is not working when the last element of the source object is correct while other elements are wrong. For example, `whatIsInAName([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { first: 1, last: "Capulet" });` will return `[{"first":"Tybalt","last":"Capulet"}]` which is not right. I think using `.reduce()` function is not the best way to do this. Please change it. Thank you.

**Comment by raisedadead** [comment]
Closing this in favor of https://github.com/FreeCodeCamp/wiki/issues/1191
