### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by thuyetbk** [FreeCodeCamp/FreeCodeCamp#9423]
Challenge [Returning Boolean Values from Functions](https://www.freecodecamp.com/challenges/returning-boolean-values-from-functions#?solution=%0Afunction%20isLess(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Fix%20this%20code%0A%20%20if%20(a%20%3C%20b)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AisLess(10%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/55.2.126 Chrome/49.2.2623.126 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function isLess(a, b) {
  // Fix this code
  if (a < b) {
    return true;
  } else {
    return false;
  }
}

// Change these values to test
isLess(10, 15);

```

**Comment by raisedadead** [comment]
GitHub issues are for bugs on the website only, please reach out to [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance to coding.

**Comment by Shahadot-shr** [comment]
function isLess(a, b) {
  // Fix this code
 return a <= b;
}

// Change these values to test
isLess(10, 15);
