### ISSUE TITLE
Change the Font Size of an Element

### ISSUE THREAD

**Issue by Tsvetan-Georgiev** [FreeCodeCamp/FreeCodeCamp#9424]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%7B%0A%20%20%20%20%20%20font-size%3A16px%3B%0A%20%20%20%20%20%20width%3A100%25%3B%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EKitty%20ipsum%20text%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I stuck because the code below i right but this point : "Your p element should contain the first few words of the provided additional kitty ipsum text." still red. Why?
My code:
```html

<style>
  .red-text {
    color: red;
  }
  p{
      font-size:16px;
      width:100%;      
    }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Kitty ipsum text</p>

```

**Comment by checkmateman** [comment]
Hi there,

If you read the instructions carefully they provide you with kitty ipsum text that is the following: 

"Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched."

So just add that to the second paragraph instead of "Kitty ipsum text"

**Comment by Tsvetan-Georgiev** [comment]
Hi,
Now it`s o.k. Thankyou!

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
