### ISSUE TITLE
learn nodejs

### ISSUE THREAD

**Issue by thuyetbk** [FreeCodeCamp/FreeCodeCamp#9425]
Challenge [Start a Nodejs Server](https://www.freecodecamp.com/challenges/start-a-nodejs-server) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/55.2.126 Chrome/49.2.2623.126 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by atjonathan** [comment]
If you need any help with the challenges, you should use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting help. Happy Coding!
