### ISSUE TITLE
Continue working with Nodejs Servers

### ISSUE THREAD

**Issue by thuyetbk** [FreeCodeCamp/FreeCodeCamp#9426]
Challenge [Continue working with Nodejs Servers](https://www.freecodecamp.com/challenges/continue-working-with-nodejs-servers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/55.2.126 Chrome/49.2.2623.126 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by atjonathan** [comment]
@thuyetbk, if this is a legitimate issue, please provide more details.
