### ISSUE TITLE
Boilerplate for new challenges

### ISSUE THREAD

**Issue by arirawr** [FreeCodeCamp/FreeCodeCamp#9428]
#### Issue Description

I'm contributing to #9412 , and it took quite a while to get set up to create new challenges. Would be great to have a template, boilerplate, or generator to facilitate growth of educational materials!
##### Pain Points (WIP)
- Generating unique IDs so Mongo can seed properly
- No comments for what each key in the JSON file pertains to
- Have to re-seed on every change

**Comment by arirawr** [comment]
Sidenote, I'll likely hop on this myself once I get a couple challenges under my belt.

**Comment by raisedadead** [comment]
Hey @arirawr thanks a lot for the issue, and yeah these are good points that need to be addressed.
On a side note, I do not know what's the current status on [COM1000](https://github.com/FreeCodeCamp/COM1000), but will get back if its working again, that would solve tons of issues creating challenges.

**Comment by arirawr** [comment]
@raisedadead Keep me posted if dev on that picks up again on that project!

**Comment by raisedadead** [comment]
@arirawr It seems to be working on Ubuntu but fails on my Windows 10 System. Feel free to try out if you are on Unix* setup.

**Comment by QuincyLarson** [comment]
Since I've been manually importing new challenges myself, this hasn't been an issue. We'll address this when we overhaul the challenge creation process.
