### ISSUE TITLE
Waypoint Responsive style correct but not accepting

### ISSUE THREAD

**Issue by Mktspeed** [FreeCodeCamp/freecodecamp#943]
Challenge http://www.freecodecamp.com/challenges/waypoint-responsively-style-radio-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The code is correct but the app is not passing so the user (me) cannot move forward

![image](https://cloud.githubusercontent.com/assets/8096081/8173804/ef0b4ef8-13a0-11e5-957e-71c4430a3f3a.png)

**Comment by LumenTeun** [comment]
Sorry, but this code is, in fact, not correct. Please close this issue and head over to the #help Slack room. :)

**Comment by sat96** [comment]
I'm having the exact same problem. @Mktspeed Did you figure out what's wrong?
