### ISSUE TITLE
I can't use mouse for move on the code

### ISSUE THREAD

**Issue by Simone2** [FreeCodeCamp/FreeCodeCamp#9436]
#### Challenge Name

[Add Borders Around your Elements](
https://www.freecodecamp.com/challenges/add-borders-around-your-elements)

#### Issue Description

I was trying to change the class on "img src" tag, but when I click on the old class (for the changing) I can't write something else.

#### Browser Information

* Browser Name, Version: 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![a1e34206-3d7b-11e6-8688-c77d934d8929](https://cloud.githubusercontent.com/assets/1884376/16430754/e1e965dc-3d9a-11e6-9003-4c1cf43265fb.png)

Edited by : @raisedadead

**Comment by raisedadead** [comment]
I think you are speaking about the same issue as #7847?

**Comment by raisedadead** [comment]
Closing as duplicate
