### ISSUE TITLE
Backspace Outside of Text Editor Returns to Previous Tut - Skips Over Lesson After Resubmitting Old Tut

### ISSUE THREAD

**Issue by megahoser** [FreeCodeCamp/freecodecamp#944]
Challenge http://www.freecodecamp.com/challenges/waypoint-import-a-google-font has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I started the next tutorial. 
Clicked outside of the text editor (anywhere outside will do).
Hit backspace.
Returned to the previous lesson.
Only way to advance is to complete the lesson.
Complete the lesson.
Skipped over incomplete lesson to next lesson, automagically.

I duplicated this a few times.
Each time it skipped yet another lesson forward.

Replication:
Went back to Basic HTML and CSS #14 
Completed lesson
Skipped much further forward to #18 (add images to your website)

Work around:

Go back to the map and select lessons without a check mark (bullet). No credit is given for incomplete tasks.

**Comment by BerkeleyTrue** [comment]
This is default browser we will not change.

Also, challenges are now saved to localStorage so previous code should still exist on refresh.
