### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Indhusethu** [FreeCodeCamp/FreeCodeCamp#9443]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20a%20href%3D%22http%3A%2F%2Fwww.example.com%22%3C%20target%3D%22_blank%22%3ELink%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = a href="http://www.example.com"< target="_blank">Link;


somebody help me in correcting this code please!!
```

var myStr = a href="http://www.example.com"< target="_blank">Link;

![capture](https://cloud.githubusercontent.com/assets/20180170/16446174/f2e2394a-3e03-11e6-8955-d789341c9d56.PNG)

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
