### ISSUE TITLE
Certifications Overhaul

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9449]
The current certifications are built using an image and overlaid text. We should have this completely made with css and html, along with mobile responsiveness. We are going to try and make the overall design similar also.

**References:**
:point_up: [June 29, 2016 7:34 PM](https://gitter.im/FreeCodeCamp/CoreTeam?at=577414d0cd7efd7714980861)
:point_up: [June 29, 2016 7:48 PM](https://gitter.im/FreeCodeCamp/CoreTeam?at=577417f78a12aa4d563e2c24)
:point_up: [June 29, 2016 8:24 PM](https://gitter.im/FreeCodeCamp/CoreTeam?at=5774205e50501d830ba38718)

cc/ @QuincyLarson @BerkeleyTrue

**Comment by QuincyLarson** [comment]
I think we agree that EdX's certificates look clean and are a good model for ours:
![](https://billyljm.files.wordpress.com/2013/05/cs50x-certificate.jpg)

I think we can keep the elements and text on the certificate the same. I will dig up my signature and @CodeNonprofit's.

**Comment by atjonathan** [comment]
@QuincyLarson, will you be about on gitter in a few hours so I can grab assets off you?
