### ISSUE TITLE
Typos in Source Code Video questions

### ISSUE THREAD

**Issue by Oxyrus** [FreeCodeCamp/FreeCodeCamp#9454]
#### Challenge Name

Video: Source Code

#### Issue Description

In [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/8fb8820a393e26dd4aefbfb20a76b7e6b78eebc6/seed/challenges/04-video-challenges/computer-basics.json#L908:#L910) lines it should be "compiled" and "interpreted" respectively.

#### Browser Information

* Browser Name, Version: Firefox
* Operating System: Ubuntu 16
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```

#### Screenshot

![http://i.imgur.com/CtHMKdU.png?1](http://i.imgur.com/CtHMKdU.png?1)

Probably a good one for first-timers-only :grinning:

**Comment by BKinahan** [comment]
It seems from the description (eg "Javascript, however, and other interpreter languages...") and some quick searches that these terms are used as intended.

**Comment by Oxyrus** [comment]
I even asked in Gitter because I'm not native in English and the campers told me it should be "compiled" and "interpreted" that's why I created it, but if that's how it was planned it's ok.

**Comment by atjonathan** [comment]
I think we should change this:
```diff
- Javascript is a compiler language
+ JavaScript is a compiled language
- Javascript is an interpreter language
+ Javascript is an interpreted language
```

**Comment by Oxyrus** [comment]
Exactly @atjonathan

**Comment by erictleung** [comment]
@atjonathan I agree and tweaking it a little further to make sure the "JavaScript" is stylized correctly:

```diff
- Javascript is a compiler language
+ JavaScript is a compiled language
- Javascript is an interpreter language
+ JavaScript is an interpreted language
```

To contributors, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.
