### ISSUE TITLE
Challenge is not passing even having the right code.

### ISSUE THREAD

**Issue by Mausamagr** [FreeCodeCamp/FreeCodeCamp#9455]
Challenge [Override All Other Styles by using Important](https://www.freecodecamp.com/challenges/override-all-other-styles-by-using-important#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%20!important%3B%0A%20%20%20%20margin-left%3A%2010px%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%20style%3D%22color%3A%20white%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink !important;
    margin-left: 10px;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>

```

**Comment by Mausamagr** [comment]
We are supposed to override all styles by pink-text class style using important key word.
I have given the important keyword, still getting this error:
Your pink-text class declaration should have the !important keyword to override all other declarations.

what to do?

**Comment by finch145** [comment]
Has any solution been found here? I'm currently having the same issue.

**Comment by Mausamagr** [comment]
Hi finch145,

Remove the margin line : "margin-left: 10px;"
And it will work. There is some conditional mismatch in the regular expression used for evaluation of this challenge.

Thanks,
Mausam

**Comment by finch145** [comment]
Hi,
Thanks a mill 😃
