### ISSUE TITLE
Confusing comment

### ISSUE THREAD

**Issue by bibekg** [FreeCodeCamp/FreeCodeCamp#9456]
The pre-included comments say only write below THIS line but the actual modifications to be made seem to be above the line. Not exactly a bug but may confuse coders.

Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20reusableFunction()%20%7B%0A%20%20console.log(%22Hi%20World%22)%3B%0A%7D%0A%0AreusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function reusableFunction() {
  console.log("Hi World");
}

reusableFunction();

// Only change code below this line



```

**Comment by khaduch** [comment]
My version of this challenge (which I completed on January 8, 2016) had a
totally different example function and it looks like there might have been
an edit that does confuse the issue?  My editor window for this challenge
has this example function:

// Example
function ourFunction() {
  console.log("Heyya, World");
}

ourFunction();

and then the comment to indicate editing code below the line.

Ken

**Comment by bibekg** [comment]
Oh, I see. It seems like they since changed the example function to be the actual function they want the user to create.

--
Bibek Ghimire

**Comment by raisedadead** [comment]
Hey guys, I do agree that this is a bit confusing. 
/cc @erictleung are you aware if this change was made during the function renaming phase we went?

I was checking the [blame history](https://github.com/FreeCodeCamp/FreeCodeCamp/blame/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json) couldn't find out though.

**Comment by erictleung** [comment]
@raisedadead mmm I guess it did get changed inappropriately in the function renaming phase. The seed function should have been left as `ourFunction`. That'll at least clear up the confusion in this issue.

**Comment by BKinahan** [comment]
Yeah, it seems that `ourFunction` for the example and a unique function name for the user is also used in [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements).

Maybe in all such cases it would be clearer to use the unique function name prefixed with `our` for the example, and without it for the user's function, i.e. `ourReusableFunction` / `reusableFunction` for this challenge and `ourTrueOrFalse` / `trueOrFalse` for the Conditional Logic challenge linked above.

Or maybe that camel case variation is confusing :)

**Comment by erictleung** [comment]
@BKinahan looks like the Passing Values to Functions with Arguments also had an inappropriate change to its function name.

I like the prefix `our` for the example functions.
