### ISSUE TITLE
reverse a string.Done!

### ISSUE THREAD

**Issue by thuyetbk** [FreeCodeCamp/FreeCodeCamp#9459]
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#?solution=%0Afunction%20reverseString(str)%20%7B%0A%20%20var%20split1%20%3D%20str.split(%22%22)%3B%0A%20%20var%20reverse%20%3D%20split1.reverse()%3B%0A%20%20return%20reverse.join(%22%22)%3B%0A%7D%0A%0AreverseString(%22hello%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/55.2.126 Chrome/49.2.2623.126 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function reverseString(str) {
  var split1 = str.split("");
  var reverse = split1.reverse();
  return reverse.join("");
}

reverseString("hello");

```

**Comment by Happy-Ferret** [comment]
What exactly seems to be the issue? I just checked it in several versions of Gecko. Works fine in every one of them.

**Comment by raisedadead** [comment]
@thuyetbk Your code passes for me, please go through [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug), and reach out to the 
[JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance.

Thanks and happy coding!
