### ISSUE TITLE
String.length should return a number? 

### ISSUE THREAD

**Issue by JackC27** [FreeCodeCamp/freecodecamp#946]
Challenge http://www.freecodecamp.com/challenges/bonfire-truncate-a-string has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

truncate('A-tisket a-tasket A green and yellow basket', 'A-tisket a-tasket A green and yellow basket'.length);

function truncate(str, num) {
  return str.length + " " + num*1;
}

returns 43 and 43 in the console but in the image below you can see that the test is still evaluating String.length as a function or something.
![screen shot 2015-06-15 at 11 41 59 pm](https://cloud.githubusercontent.com/assets/3687036/8177302/3a2b3940-13b8-11e5-9536-db784f40f82a.png)

**Comment by LumenTeun** [comment]
I'm not sure what the issue is here?

**Comment by BerkeleyTrue** [comment]
Closing as stale. Please reopen if the issue persist.

Happy Coding!
