### ISSUE TITLE
[beta] Additional Button(?) Element

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9460]
At the bottom of front page on mobile. No access to devtools right now so I can't inspect it

![image](https://cloud.githubusercontent.com/assets/18572518/16478018/c7d790de-3e8e-11e6-95ab-cef2f512871a.png)

**Comment by Bouncey** [comment]
Related?

Bottom of /nonprofits

![image](https://cloud.githubusercontent.com/assets/18572518/16478129/ab4766fa-3e8f-11e6-80fb-e4690a7cd13f.png)

**Comment by Bouncey** [comment]
And signin
![image](https://cloud.githubusercontent.com/assets/18572518/16478148/d8b9a2ec-3e8f-11e6-845f-823ba048f322.png)

**Comment by Bouncey** [comment]
Shop

![image](https://cloud.githubusercontent.com/assets/18572518/16478728/8b13edc8-3e93-11e6-9f96-0369f02a665f.png)

About
![image](https://cloud.githubusercontent.com/assets/18572518/16478729/8b3904f0-3e93-11e6-99d8-b71877ccac01.png)

Profile
![image](https://cloud.githubusercontent.com/assets/18572518/16478730/8b3fdea6-3e93-11e6-80c9-de13bf22339b.png)

**Comment by BerkeleyTrue** [comment]
None of these pages are touched by this PR. Also I cannot replicate

**Comment by Bouncey** [comment]
I only see them on the beta site. 

### These are from the live site
![image](https://cloud.githubusercontent.com/assets/18572518/16478974/203fdd02-3e95-11e6-8d57-6271f4481421.png)
![image](https://cloud.githubusercontent.com/assets/18572518/16478975/2066ae46-3e95-11e6-92a9-6ec31d629aea.png)
![image](https://cloud.githubusercontent.com/assets/18572518/16478976/20691ff0-3e95-11e6-8665-1d31530783bb.png)

**Comment by atjonathan** [comment]
I can reproduce this.

**Comment by Bouncey** [comment]
@BerkeleyTrue 
Seems like it is the `map-aside` close button.

![screenshot from 2016-06-30 10-38-26](https://cloud.githubusercontent.com/assets/18572518/16484002/dfd3633c-3eae-11e6-9d76-4e02a00ea7ed.png)

**Comment by BerkeleyTrue** [comment]
@Bouncey Thanks for much for finding that. This was really bugging me that I couldn't reproduce. Regardless, I can remove that html since we will no longer support the iframe map drawer

**Comment by BerkeleyTrue** [comment]
@Bouncey Can you confirmed if this is fixed now?

**Comment by Bouncey** [comment]
All fixed, can't see it anywhere :+1:
