### ISSUE TITLE
[Title Case a Sentence].I have completed but I don't think it is good design

### ISSUE THREAD

**Issue by thuyetbk** [FreeCodeCamp/FreeCodeCamp#9462]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20lower%3D%20str.toLowerCase()%3B%0A%20%20var%20string%20%3D%20lower.split(%22%20%22)%3B%0A%20%20var%20part2%3D%22%22%3B%0A%20%20for(i%3D0%3Bi%3Cstring.length%3Bi%2B%2B)%7B%0A%20%20%20%20var%20substring%20%3D%20string%5Bi%5D.split(%22%22)%3B%0A%20%20%20%20var%20part1%3B%0A%20%20%20%20for(j%3D0%3Bj%3Csubstring.length%3Bj%2B%2B)%7B%0A%20%20%20%20%20%20if(j%3D%3D%3D0)%7B%0A%20%20%20%20%20%20%20%20part1%3Dsubstring%5B0%5D.toUpperCase()%3B%0A%20%20%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20%20%20part1%2B%3Dsubstring%5Bj%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20part2%2B%3Dpart1%2B%22%20%22%3B%0A%20%20%7D%0A%20%20return%20part2.trim()%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/55.2.126 Chrome/49.2.2623.126 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  var lower= str.toLowerCase();
  var string = lower.split(" ");
  var part2="";
  for(i=0;i<string.length;i++){
    var substring = string[i].split("");
    var part1;
    for(j=0;j<substring.length;j++){
      if(j===0){
        part1=substring[0].toUpperCase();
      }else{
        part1+=substring[j];
      }
    }
  part2+=part1+" ";
  }
  return part2.trim();
}

titleCase("I'm a little tea pot");

```

**Comment by raisedadead** [comment]
Please describe the issue you are facing?

**Comment by raisedadead** [comment]
Refer : https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9465#issuecomment-229593106
