### ISSUE TITLE
[beta] No 404 or Not Found Flash

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9463]
When given an incorrect address, browser redirects to /map

There is no 404 or flash messages as per the live site
![anim](https://cloud.githubusercontent.com/assets/18572518/16485518/2d758950-3eb7-11e6-8305-eae0b15bcc40.gif)

 ### From live site

![image](https://cloud.githubusercontent.com/assets/18572518/16479536/ed272b9c-3e98-11e6-8571-23336aca6396.png)

**Comment by raisedadead** [comment]
@Bouncey This is the existing behavior for the production site, and there is a notification. Were you expecting any thing else?

**Comment by Bouncey** [comment]
@raisedadead Clarified in OP

**Comment by BerkeleyTrue** [comment]
Live on beta!

I chose a simple 404 page instead of rendering errors on the map. We have experience infinite loops when the map page itself is the cause of the error.

Someone with more talent will need to make that page purdy.

**Comment by raisedadead** [comment]
Sweeeeet!
