### ISSUE TITLE
Using <i> vs <span> for icons.

### ISSUE THREAD

**Issue by darrenbkl** [FreeCodeCamp/FreeCodeCamp#9464]
Using `<i>` for icon is a not good, fcc shouldn't teach/encourage bad practice, use `<span>`.

**Comment by raisedadead** [comment]
Can you cite some sources in support of this?

**Comment by darrenbkl** [comment]
<i> is used for _italic_, <span> is generic, since html does not have tag for icon, span is generally used for such purpose. The use of <i> for icon is semantically incorrect, and might confuse and mislead beginners.

From W3 HTML Language Reference:
The i element represents a span of text offset from its surrounding content without conveying any extra emphasis or importance, and for which the conventional typographic presentation is italic text; for example, a taxonomic designation, a technical term, an idiomatic phrase from another language, a thought, or a ship name.
https://www.w3.org/TR/html-markup/i.html

The span element is a generic wrapper for phrasing content that by itself does not represent anything.
https://www.w3.org/TR/html-markup/span.html

**Comment by raisedadead** [comment]
@darrenbkl Thanks for the links, but IMHO those are definitions of `<i>` and `<span>` tags.

Can you point us to any resources that state that this not a good practice?

On a side note, this was discussed earlier that the use of `<i>` is outdated in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7512

/cc @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
@darrenbkl okay here is what I found that may help:

http://stackoverflow.com/questions/11135261/should-i-use-i-tag-for-icons-instead-of-span?answertab=votes#tab-top

> Why are they using `<i>` tag to display icons ?
> Because it is:
> - [x] Short
> - [x] `i` stands for icon (although not in HTML)
>
> Is it not a bad practice ?
> Awful practice. It is a triumph of **performance over semantics**.

Also, I may be wrong but this something which campers will find used everywhere, and I think keeping them aware of the fact that this not standard spec, is used as a common practice is the best we should do and are doing in one of the challenges already.

Refer the issue mentioned in the earlier comment where this is explained.

Do let us know your thoughts.

**Comment by atjonathan** [comment]
@raisedadead, I agree. We should let campers know that this is not good practice, but used all the time. I suggest we just add a sentence in the challenge instructions about this.

**Comment by raisedadead** [comment]
@atjonathan as I said its there already https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7512#issuecomment-203678412

And the OP did not mention any other specific challenge that gets affected.

**Comment by atjonathan** [comment]
@raisedadead, sorry didn't see that comment. I think we can close this issue then.

**Comment by Bouncey** [comment]
From [Fontawesome.io](fontawesome.io):

You can place Font Awesome icons just about anywhere using the CSS Prefix fa and the icon's name. Font Awesome is designed to be used with inline elements (we like the <i> tag for brevity, but using a <span> is more semantically correct).

**Comment by darrenbkl** [comment]
@raisedadead I don't think it is used in many places.

If it's decided to let member aware of the spec, the challenge should also allows interchangeable use of those tags, i.e. not forcing the use of `<i>`. Just a thought.

**Comment by raisedadead** [comment]
@atjonathan lets wait for OP's comment. 
@Bouncey thanks, but the thing is this an argument of semantics vs general practice. Where IMO the later wins.

**Comment by raisedadead** [comment]
@darrenbkl Yeah, you are correct indeed. We should allow alternative use. Thanks for reverting.

**Comment by raisedadead** [comment]
To contributors:

[Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery) needs to be updated with instructions and tests to allow alternative use of `<i>`

Please comment and share your proposal before making a PR.

**Comment by AkiraLaine** [comment]
@raisedadead @darrenbkl I don't think anyone uses the `span` tag to display icons. In fact, every major icon provider (Font Awesome, Google Icons...etc) use the `i` tag for it. 

To empathize(italicize) text, you should use the `em` tag.

**Comment by atjonathan** [comment]
I agree with @AkiraLaine.

**Comment by sludge256** [comment]
Here's Font Awesome's comment on the issue in question,
>You can place Font Awesome icons just about anywhere using the CSS Prefix fa and the icon's name. Font Awesome is designed to be used with inline elements (we like the <i> tag for brevity, but using a <span> is more semantically correct).

http://fontawesome.io/examples/

We should definitely allow the use of the span tag though.

**Comment by AryanJ-NYC** [comment]
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-all-of-our-buttons

Two more links where `<i>` is used and `<span>` is not.

**Comment by dhcodes** [comment]
I'm working on this one. Will have a PR in later today.

**Comment by sagayev** [comment]
This was accepted:
 **<button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up">Like</i></button>**

But this was not:
 <button class="btn btn-block btn-primary fa fa-thumbs-up">Like</button>

Although they yield the same result. I am newbie here. I don't know if the latter has any side effect..

**Comment by raisedadead** [comment]
@sagayev please open a new issue.

**Comment by Mielai1l** [comment]
the challenges mentioned by  AryanJ-NYC on 5 Aug 2016 are not yet updated 
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-all-of-our-buttons

**Comment by erictleung** [comment]
@Mielai1l they've been changed [in the codebase](https://github.com/freeCodeCamp/freeCodeCamp/blob/d5db2803ad0214e43f2d4ddc12f8a1b1976ac853/seed/challenges/03-front-end-libraries/bootstrap.json#L1328-L1331). You can see for yourself in the [beta site](http://beta.freecodecamp.com/en/challenges/bootstrap/add-font-awesome-icons-to-our-buttons). Changes will be pushed to the production site soon.
