### ISSUE TITLE
 [Confirm the Ending] I'm done!

### ISSUE THREAD

**Issue by thuyetbk** [FreeCodeCamp/FreeCodeCamp#9465]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20var%20part1%3Dtarget.length%3B%0A%20%20var%20part2%3Dstr.substr(-part1)%3B%0A%20%20if(part2%3D%3Dtarget)%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7Delse%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0AconfirmEnding(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/55.2.126 Chrome/49.2.2623.126 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var part1=target.length;
  var part2=str.substr(-part1);
  if(part2==target){
    return true;
  }else{
    return false;
  }
}

confirmEnding("Bastian", "n");

```

**Comment by arun1595** [comment]
What issue are you facing with this challenge?

**Comment by raisedadead** [comment]
@thuyetbk Unless you can specify the issue you are facing we can't address the same. Also We have noticed that you have been posting such issues frequently without any clear description.

Github issues are for bugs only, please go though [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).

Closing as invalid, please clarify to re-open.
