### ISSUE TITLE
"Make Images Mobile Responsive" challenge passes without </img> tag

### ISSUE THREAD

**Issue by k3ntucky** [FreeCodeCamp/FreeCodeCamp#9467]
#### Challenge Name

https://www.freecodecamp.com/challenges/make-images-mobile-responsive

#### Issue Description

The first image is from the "Add Images to your Website" challenge and mentions that "Note that in most cases, img elements are self-closing."
  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
But in the challenge "Make Images Mobile Responsive" it specifically mentions to have a closing tag and the challenge will still pass if the </img> isn't present, despite it being on the check list.
  <img class="img-responsive" src="https://bit.ly/fcc-running-cats">

#### Browser Information

* Browser Name, Version: Firefox 47.0
* Operating System: Ubuntu 16.04 LTS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
<img class="img-responsive" src="https://bit.ly/fcc-running-cats">
```

**Comment by atjonathan** [comment]
Related to #9383.
@k3ntucky, this is valid html as far as I know and should be fine to pass.
cc/ @FreeCodeCamp/issue-moderators

**Comment by dhcodes** [comment]
<img> does not require a closing tag and according to MDN, should not have one. In XHTML or XML you can add a `/` after the source but in HTML, this is not required.

Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by Bouncey** [comment]
@k3ntucky The exception to the case in "Add Images to your Website" is in XML

In XML, element tags are not allowed to be self-closing:

`<br>` becomes `<br />`
`<hr>` becomes `<hr />`
and `<img>` becomes `<img />`

The XML tags do work in HTML5, but is not strictly correct.

I hope this clears up the issue.

**Comment by MuhammadLaraib** [comment]
Thanks @k3ntucky
