### ISSUE TITLE
Lessons are missing Script include for Bootstrap

### ISSUE THREAD

**Issue by interactivebpj** [FreeCodeCamp/freecodecamp#947]
For a novice learner, like me, most of the bootstrap lessons are missing the script link or include to the bootstrap.min.js.  

Doesn't the following line need to be in your code view in order to use the classes such as (button class "button-block"  or responsive img ??)

"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js

This file is missing in the black code view screens.

**Comment by LumenTeun** [comment]
That's sort of addressed in the first Bootstrap instuctions:
```Fortunately, we have access to a Responsive CSS Framework called Bootstrap. You can add Bootstrap to any app just by including it with <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'/> at the top of your HTML. But we've gone ahead and automatically added it to your Cat Photo App for you.```
I believe it's missing from the editor HTML because Boostrap is included in FCC's HTML, but I might be wrong? It would probably be good to include the ```<link>``` in the editor HTML for clarity.

**Comment by BerkeleyTrue** [comment]
@ahstro Is correct.

Happy Coding!
