### ISSUE TITLE
Run Test Bug in jQuery courses

### ISSUE THREAD

**Issue by ZiedChekir** [FreeCodeCamp/FreeCodeCamp#9470]
so i was following the courses about jQuery with title "Target the same element with multiple jQuery Selectors" [link](https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors) but there is a bug preventing me from running the test and passing to the next course 
when you click on run test or ctrl + enter the task bar fade out and i got stuck there 
so i decided to let you now about this bug i tried in google chrome and firefox

**Comment by erictleung** [comment]
@ZiedChekir thanks for the issue. Can you post your code you have tried for this challenge? It'll help diagnose your problem as a bug with the site or an issue with your code.

**Note**: in the future, if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by ZiedChekir** [comment]
sure :)

<script>
  $(document).ready(function() {
    $("button").addclass("animated ");
    $(".btn").addclass("shale");
    $("#target1").addclass("btn-primary");
    
  });
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by ZiedChekir** [comment]
yea sure but how can i post my code because github reads the code and prints the result of the code

**Comment by HassHz** [comment]
$("button").addclass("animated "); -> extra space after animated
$(".btn").addclass("shale");            -> shake spelled incorrectly

addclass()                                      -> should be addClass()

**Comment by erictleung** [comment]
@ZiedChekir as @HassHz has pointed out, it looks like you have a typo. If that fixes your issue, please close this issue. If not, please report back your correct code and any screenshots and errors you got.

**Comment by ZiedChekir** [comment]
ah sorry, it was a test i wanted to see how the run test behaves when i have a problem. besides when it   s correct (with shake*) the run test button doesnt do anything ...

**Comment by almesh** [comment]
‏في الجمعة، ١ يوليو، ٢٠١٦, ZiedChekir <notifications@github.com> كتب:

> ah sorry, it was a test i wanted to see how the run test behaves when i
> have a problem. besides when it s correct (with shake*) the run test button
> doesnt do anything ...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9470#issuecomment-229826556>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AP1TBUpPdWCUNAYrwt_Fz6Ss-9GMzb8nks5qRGJggaJpZM4JCYvI>
> .
>


-- 
null

**Comment by erictleung** [comment]
@ZiedChekir the Run Test button should create an animation to show that the tests were run and if you don't get a modal pop up, that means your code is incorrect.

So does this mean there's no bug? I'm confused on your issue now.

**Comment by HassHz** [comment]
@ZiedChekir Did you change addclass to addClass? That's what was causing the expected test results at the bottom of the Run Tests button to disappear for me.

**Comment by JetroLopez** [comment]
I'm having the same bug with the code, I've checked multiple times if i had a typo but it seems alright, i can't keep going with the lessons
This is the code if there's anything wrong please point it out

$(document).ready(function(){
    $("button").addClass(animated)
    $(".btn").addClass(shake)
    $("#target1").addClass(btn-primary)

  });

**Comment by erictleung** [comment]
@JetroLopez if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: check for semi-colons and correct use of the `.addClass()` method; are you passing in a correctly formatted class name? Happy coding!
