### ISSUE TITLE
Unclear instructions - Basic JS - Accessing Nested Objects

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/FreeCodeCamp#9473]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects) has an unclear instruction. This fix will be good for first-timers!

## The Instruction at the Moment 
Access the `myStorage` object to retrieve the contents of the `glove box`. Use bracket notation for properties with a space in their name.

## Suggested Update
Access the `myStorage` object and assign the contents of the `glove box` property to the `gloveBoxContents` variable. Use bracket notation for properties with a space in their name.

**Comment by atjonathan** [comment]
@Greenheart, thanks this makes the challenge easier to understand :+1: 

**To contributor (first-timer):**
You will need to change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4405) line of code.
Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by HassHz** [comment]
I can work on this issue

**Comment by smolaei** [comment]
var gloveBoxContents = myStorage.car.inside["glove box"];

Remember: 

properties with spaces must go inside brackets & quotes.

**Comment by texas2010** [comment]
@smolaei 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
