### ISSUE TITLE
[beta] settings for language css issue.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9474]
![image](https://cloud.githubusercontent.com/assets/1884376/16502699/4b85f5f8-3f2d-11e6-96a8-e92ef571c9de.png)

----
![image](https://cloud.githubusercontent.com/assets/1884376/16502718/5ab03e6c-3f2d-11e6-9868-7d1861b23c0c.png)

**Comment by BerkeleyTrue** [comment]
@raisedadead OS? Browser?

**Comment by raisedadead** [comment]
Windows 10 - Chrome 51 and Firefox 46

**Comment by BerkeleyTrue** [comment]
@raisedadead Can you verify that this is still an issue?

**Comment by raisedadead** [comment]
Sweeeeeet... its fixed now. Thanks @BerkeleyTrue. Please close as you seem fit,

**Comment by BerkeleyTrue** [comment]
✨
