### ISSUE TITLE
Problem on BRANCHES AREN'T JUST FOR BIRDS 

### ISSUE THREAD

**Issue by danweinstock** [FreeCodeCamp/FreeCodeCamp#9475]
#### Challenge Name
BRANCHES AREN'T JUST FOR BIRDS 

#### Issue Description
I have followed the instruction to the letter and am getting error that I don't have permission to push up to jlord/patchwork repo.

#### Browser Information

* Browser Name, Version: Chrome Version 51.0.2704.103 (64-bit)
* Operating System:  Yosemite
* Mobile, Desktop, or Tablet: Desktop Mac Book Air

#### Your Code

```js
 
```

**Comment by erictleung** [comment]
@danweinstock mmm it sounds like you are probably trying to write to the remote origin repo. I would make sure you are making a branch on your fork and then pushing it up.

Can you give your output for `git remote -v`?

Note: if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by raisedadead** [comment]
Closing as stale. Please comment if you are still facing this.
