### ISSUE TITLE
Challenges need a Linter like JSLint

### ISSUE THREAD

**Issue by N0bl3** [FreeCodeCamp/FreeCodeCamp#9476]
It would be great to have a linter built in FCC challenges. Even a basic one like JSLint so that beginners start with good practices and remember the syntax as soon as they put it in a wrong way like using =, == & === etc...

We should probably first decide to implement a linter or not, then if yes, which linter to implement, then how we could do it.

**Comment by raisedadead** [comment]
We do have syntax highlighting and linting:

![image](https://cloud.githubusercontent.com/assets/1884376/16512699/d84b36a8-3f7b-11e6-979a-16a052b3c59a.png)

and

![image](https://cloud.githubusercontent.com/assets/1884376/16512704/eb8f4916-3f7b-11e6-81f9-e055b1783b3f.png)

are we discussing something else?

**Comment by raisedadead** [comment]
Closing as stale. Please comment, if you still need more clarification?

**Comment by N0bl3** [comment]
That's not what i wanted to say i was a bit confused this day ! ;) I wanted to speak about styling practices like avoid == etc.. and that it would be great to have the possibility to autoformat on a keyboard shortcut.

**Comment by raisedadead** [comment]
Now I get what you mean, (the opening post and the original title was not clear).

However, IMHO building Linting challenges is not really a very effective idea to teach best coding practices, I feel these should be taken up in the wiki.

Would you mind adding a issue on the wiki repo, in that case?

**Comment by Enkkee** [comment]
Hi,

Thanks for your respond. I found solution. Some of title guided wrong way.
But it is not problem. It depends on learner. I really excited it.

Thanks,
Enkkee

**Comment by N0bl3** [comment]
Yes i'll emit an issue with more sense than this one :)
