### ISSUE TITLE
the unit tests appear to be faulty.

### ISSUE THREAD

**Issue by boruchwoolstone** [FreeCodeCamp/FreeCodeCamp#9478]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=%0Afunction%20truncateString(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20if%20(num%20%3C%3D%203)%7B%0A%20%20%20%20%20if%20(str.length%20%3E%20num)%20%7B%0A%20%20%20%20%20shortStr%20%3D%20str.substring(0%2C%20num)%3B%0A%20%20%20%20%20shortStr%20%2B%3D%20%22...%22%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20if%20(str.length%20%2B%203%20%3E%20num)%20%7B%0A%20%20%20%20%20shortStr%20%3D%20str.substring(0%2C%20num%20-%203)%3B%0A%20%20%20%20%20shortStr%20%2B%3D%20%22...%22%3B%0A%20%20%20%20%7D%20%20%0A%20%20%7D%0A%20%20var%20a%20%3D%20%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%3B%0A%20%20var%20b%20%3D%20a.length%3B%0A%20%20return%20shortStr%3B%0A%7D%0A%0AtruncateString(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2043)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (num <= 3){
     if (str.length > num

**Comment by boruchwoolstone** [comment]
![codecampbug](https://cloud.githubusercontent.com/assets/10391211/16512489/44e54948-3f9f-11e6-8de9-e18824b68d5c.png)
here is a screen shot

**Comment by boruchwoolstone** [comment]
![codecampbug2](https://cloud.githubusercontent.com/assets/10391211/16512520/c045287e-3f9f-11e6-839f-2e55f009d4e5.png)
I spoofed it to work by adding an extra condition at the end.

**Comment by erictleung** [comment]
@boruchwoolstone there isn't anything wrong with the tests. Please reread the instructions.

> Truncate a string (first argument) **if it is longer than the given maximum string length** (second argument)

`"A-tisket a-tasket A green and yellow basket".length` is not longer than `"A-tisket a-tasket A green and yellow basket"`. Thus this string should not be truncated.

In the future, if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by boruchwoolstone** [comment]
If you look at the screen shot. In the second and third test the second parameter is not correct.

**Comment by erictleung** [comment]
@boruchwoolstone can you elaborate on what you mean by the second parameter being incorrect? How is the parameter incorrect and what do you think it should be? And in which screenshot? Thanks!

**Comment by myanreeks** [comment]
While, I can understand your assertion that the instructions are correct, as are the tests, I think the issue is one of clarity.  Separating out the information into shorter, less complex sentences might help comprehension and avoid bugs being reported incorrectly.

"The function should accept a string(first argument) and a number(second argument) representing the length of the string that should be returned.  If number is less than the length of str, the function should truncate the string.  If number is greater than or equal to the length of string, return the original string unmodified."
