### ISSUE TITLE
Repeat a string - clicking Wiki results in 404

### ISSUE THREAD

**Issue by wiseleo** [FreeCodeCamp/FreeCodeCamp#9479]
Verified in incognito mode to eliminate variable conditions. Other challenges are OK, but clicking "Wiki" on https://www.freecodecamp.com/challenges/repeat-a-string results in a 404.

The associated wiki URL is incorrectly https://www.freecodecamp.com/wiki/en/algorithm-repeat-a-string-repeat-a-string/

It appears to be related to #9321

**Comment by raisedadead** [comment]
Hey @wiseleo ,

Thanks for the report, the challenges have been recently renamed back to Repeat a string repeat a string and the changes havent reached the production website yet.

Once the 404 would get resolved automatically, until then the workaround would be to visit the challenge wiki directly with a search.

**Comment by atjonathan** [comment]
Closing, This fix should be live within the next few days.
