### ISSUE TITLE
Use Firepad as the code editor for FreeCodeCamp, for collaborative editing.

### ISSUE THREAD

**Issue by azuriolinist** [FreeCodeCamp/freecodecamp#948]
Replace the code editor with <a href="http://www.firepad.io/">Firepad</a>. Firepad is a collaborative code/text editor. This would be useful for pair programming, for those who can't use ScreenHero.

**Comment by LumenTeun** [comment]
There has been some talk (See @QuincyLarson's comments in #784 and #786) about moving to [Ace](http://ace.c9.io/), and although I can not find the source right now, I remember hearing something about integrating a pair programming environment into FCC itself, although I'm not sure if Ace would be an integral part of that. Whether Firepad or Ace would be a better fit for what the lead devs have in mind, only they can tell you.

**Comment by BerkeleyTrue** [comment]
Firepad was one of the editors we looked at in the beginnings of FCC. Unfortunately it is not a fleshed out editor as are Ace and CodeMirror and its realtime isn't the best.

There are plans to create a realtime pairing system using react/flux and web sockets its further down the list of features to add so don't expect to come for at least a month while other things are implemented.


@azuriolinist Thanks for the input!
