### ISSUE TITLE
Flyer returns after being dismissed in FireFox

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9480]
#### Issue Description

1. open up FreeCodeCamp.com in firefox, sign in, and make sure you have at least 5 brownie points.
2. you should see the "flyer" at the top of the page with a promotional message like "check out our forum"
3. dismiss it
4. refresh the page. It comes back.

This is a problem with our use of local storage.

**Comment by flipsyde606** [comment]
Can I take this?

**Comment by atjonathan** [comment]
@flipsyde606, sure :wink: 
Check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).
