### ISSUE TITLE
Inconsistent Output

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9481]
#### Challenge Name

[Add Two Numbers with JavaScript](https://www.freecodecamp.com/challenges/add-two-numbers-with-javascript)
and
[Subtract One Number from Another with JavaScript](https://www.freecodecamp.com/challenges/subtract-one-number-from-another-with-javascript)

#### Issue Description

The `console.log()` output for these two challenges is inconsistent with [Multiply Two Numbers with JavaScript](https://www.freecodecamp.com/challenges/multiply-two-numbers-with-javascript). See screenshots below.

#### To Fix

This [line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/6722e2278ef324ad20914e1c1afa52136fb750fe/seed/challenges/01-front-end-development-certification/basic-javascript.json#L296) needs to be changed to:

```js
"(function(z){return 'sum = '+z;})(sum);"
```

And [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/6722e2278ef324ad20914e1c1afa52136fb750fe/seed/challenges/01-front-end-development-certification/basic-javascript.json#L333) needs to be changed to:

```js
"(function(z){return 'difference = '+z;})(difference);"
```

#### Screenshot

Add Two Numbers with JavaScript

![image](https://cloud.githubusercontent.com/assets/2754821/16515393/9752910a-3f26-11e6-98cc-961497f9092d.png)

Subtract One Number from Another with JavaScript

![image](https://cloud.githubusercontent.com/assets/2754821/16515358/71b0db14-3f26-11e6-99c7-005b93324b9c.png)

Multiply Two Numbers with JavaScript

![image](https://cloud.githubusercontent.com/assets/2754821/16515421/c23df940-3f26-11e6-9d17-9ce889b0829d.png)

#### To Contributors

Only first time contributors to FreeCodeCamp can attempt this issue. Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by aksinghdce** [comment]
I am working on this

**Comment by aksinghdce** [comment]
Done
