### ISSUE TITLE
Waypoint: Write Functions with jQuery Possible Error With Assignment Link at CodeAcademy

### ISSUE THREAD

**Issue by softwaregeek** [FreeCodeCamp/freecodecamp#949]
An FYI for those working assignment Waypoint: Write Functions with JQuery. Number 4 in the list has a URL linking us to a location: http://www.codecademy.com/courses/web-beginner-en-GfjC6/0/1 

That location takes us to the Codeacademy JQuery Functions and Selectors 3 of 13's (3/13) assignment. At the bottom of the assignment there is a Hint. That Hint mentions :nth-child() or :last-child(http://www.codecademy.com/courses/web-beginner-en-WF0CF/3#!/exercises/3)!

But, the URL for ":nth-child() or :last-child" takes you to the assignment about CSS Selectors 15 of 23 (15/23), and that assignment is about Links and does not mention nth-child nor last-child. 

The CSS Selectors Nth child assignment is actually 17 of 23 (17/23) http://www.codecademy.com/courses/web-beginner-en-WF0CF/3/4

Perhaps they were working you up from Links, to First child, then to Nth child?

**Comment by LumenTeun** [comment]
The first link takes me to the first section (1/13), not sure why it doesn't for you.

I'm not really sure what could be done about this since it's not an issue with FCC, but with Codecademy. I suppose a note could be made in the waypoint instructions, but that seems a bit excessive in my opinion.

**Comment by BerkeleyTrue** [comment]
Closing as codecademy is removed in beta.
