### ISSUE TITLE
Problem with resuming lessons, skips forward a lesson after leaving and revisiting.

### ISSUE THREAD

**Issue by pbcub1** [FreeCodeCamp/FreeCodeCamp#9498]
#### Issue Description
When I return to FCC after leaving, I get skipped to the next lesson, and not the one I left off at. This seems to be a problem in the logged in homepage? I keep having to go to the map to go back to the lesson I left off on, and if I forget to do that, I will get through multiple lessons and notice a skipped lesson when I finally go back. This is more annoying than critical.

#### Browser Information
* Mozilla Firefox, Version: 47.0
* Operating System: Desktop Windows 10 64bit

**Comment by raisedadead** [comment]
@pbcub1 thanks for reporting. I can't seem to reproduce this though. 

Can you please try the common trouble shooting steps on the below page:
[Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Report-Bugs).

If that doesn't work, then could you help us with any weird logs that you see on the console of Dev Tools on your Browser (<kbd>F12</kbd> >> Console Tab). Hit refresh on the page to see the logs.

**Comment by raisedadead** [comment]
Closing as stale, please comment on the thread if you are still facing this issue.
