### ISSUE TITLE
Waypoint: Wrap an Anchor Element within a Paragraph(code doesn't work)

### ISSUE THREAD

**Issue by sourabhkumar0308** [FreeCodeCamp/freecodecamp#950]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

<.p>click here for <.a href="http://catphotoapp.com">cat photos<./a><./p>
(period(.) added just to highlight the code)

'a' element is wrapped within 'p' element still it gives me an error.

**Comment by LumenTeun** [comment]
I can not reproduce this, but I feel like I've seen others mention the same issue. Is it persistent between refreshes/restarts?

**Comment by sourabhkumar0308** [comment]
yes it is persistent between refreshes/restarts. It's still note rectified.
