### ISSUE TITLE
Chunky Monkey needs better solutions

### ISSUE THREAD

**Issue by wiseleo** [FreeCodeCamp/FreeCodeCamp#9500]
The basic solution is very convoluted and intermediate isn't much better. Advanced is OK.

Challenge also might benefit from mentioning the <code>splice</code> method since that is a much simpler approach than <code>slice</code>.

Propose eliminating that ugly basic solution, demoting intermediate to basic, and advanced to intermediate. Also recommend adding <code>splice</code> to list of suggested methods.

**Comment by santakmishra** [comment]
I think this issue belongs to https://github.com/FreeCodeCamp/wiki

**Comment by raisedadead** [comment]
@santakmishra thanks.

@wiseleo Thanks for reporting, closing this in favor of https://github.com/FreeCodeCamp/wiki/issues/1205
