### ISSUE TITLE
Slasher Intermediate explanation has incorrect statement regarding slice()

### ISSUE THREAD

**Issue by wiseleo** [FreeCodeCamp/FreeCodeCamp#9501]
Someone apparently copied the explanation from splice.
> Modify the array with slice() and return it.

Slice does not modify arrays. 
> The slice() method returns a shallow _copy_ of a portion of an array into a new array object. - **_Source: MDN_**

The entire explanation is problematic:
- This solution uses the slice() function. **OK**
- The argument `howMany` is the number of elements to be ~~removed~~ **_skipped since beginning of array_** ~~starting with arr[0]~~.
- ~~Modify the array with `slice()` and return it.~~ **_Return the remaining array without modifying original array_**

**Comment by BKinahan** [comment]
Ah, you're talking about the solution explanations found on the [wiki page for the Slasher Flick challenge](https://www.freecodecamp.com/wiki/en/algorithm-slasher-flick/).

This issue belongs on the FCC Wiki repo issue list instead: https://github.com/FreeCodeCamp/wiki/issues

**Comment by raisedadead** [comment]
@BKinahan thanks.

Closing in favor of https://github.com/FreeCodeCamp/wiki/issues/1208
