### ISSUE TITLE
how to change the image size??

### ISSUE THREAD

**Issue by itay14717** [FreeCodeCamp/FreeCodeCamp#9503]
HTML Code
I need to change the image size to a smaller size and make it 100px i did the code but it doesn't work please help me...
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by raisedadead** [comment]
Hi @itay14717 ,

Thanks for reporting, but GitHub issues are for bugs in website only. Please check below for help.
- [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).
- [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

Happy Coding!
