### ISSUE TITLE
problem with instructons

### ISSUE THREAD

**Issue by abdullah-holm** [FreeCodeCamp/FreeCodeCamp#9505]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22Here%20is%20a%20backslash%3A%20%5C%5C.%5Cn%5Ct%5CtHere%20is%20a%20new%20line%20with%20two%20tabs.%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr='"Here is a backslash: \\. \n \t \t Here is a new line with two tabs."'; // Change this line



```

**This code SHOULD work according to the instructions, it is impossible to guess what form it should take, I got it to work, but the instructions never said to remove the space between an escape sequence and a word following it.**

**Comment by raisedadead** [comment]
Thanks for reporting.

This was recently discussed in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9314 and fixed via https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9446 (changes will reach main website soon)

Hope this helps, please confirm.

**Comment by raisedadead** [comment]
Closing as stale, as mentioned this should have been fixed.
