### ISSUE TITLE
it refuses to remove the error.

### ISSUE THREAD

**Issue by mbotiy2k** [FreeCodeCamp/FreeCodeCamp#9506]
Challenge [Override Class Declarations by Styling ID Attributes](https://www.freecodecamp.com/challenges/override-class-declarations-by-styling-id-attributes#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%0A%20%20%0A%20%20%20%20%23orange-text%7Bcolor%3Aorange%3B%7D%0A%20%20%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%20blue-text%22%20id%3D%22orange-text%22%3EHello%20World!%3C%2Fh1%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  
  
    #orange-text{color:orange;}
  
  }
</style>
<h1 class="pink-text blue-text" id="orange-text">Hello World!</h1>


```

**Comment by raisedadead** [comment]
Thanks for reporting, but GitHub issues are for bugs in website only. Please check below for help.
- [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).
- [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

Unfortunately your code is not correct, almost there though. Please check the above.
Happy Coding!

**Comment by TinaLittlemoon** [comment]
The order of the class declarations in the <style> section matters GIVEN that there is **no** ID provided. 
If there is an id attribute, it always takes precedence. That's why it turns the letters orange and not blue.
`
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text{
    color:orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }

</style>
<h1 id="orange-text" class="pink-text blue-text">Hello World!</h1>
`
