### ISSUE TITLE
Grey should be acceptable for Gray

### ISSUE THREAD

**Issue by patraicemery** [FreeCodeCamp/FreeCodeCamp#9510]
For Give a Background Color to a Div Element the color gray could also be done as grey as it is spelled in certain places. Both give the right color to the background.

**Comment by BKinahan** [comment]
I see your point that `grey` equates to the same color for the background, but one of the spellings had to be chosen for the class name, and I think it makes sense that the color name used should match the class name `gray-background`. It reinforces consistency and attention to detail at this early part of the course.

Unless we should change the class name to `gray-or-grey-background`? :)

**Comment by patraicemery** [comment]
I think it could be beneficial to point out that even though the spelling is different  using grey as a pose to gray would still work because for some people they would naturally use that spelling. I can not think of any other examples of occurrences like this as I am just begging to learn how to code, but I'm sure there are other examples out there.

**Comment by erictleung** [comment]
So `gray` is the among [basic color keywords](https://www.w3.org/TR/css3-color/#html4) according to the W3. Eventually, it appears that [an expanded set of color keywords were added](https://www.w3.org/TR/css3-color/#svg-color) which allowed for spelling variants gray/grey to indicate the same color.

So there are a couple things we could do:

1. modify the tests in the background to accept `grey` and `gray` spellings
2. change the color used in this challenge to avoid this issue altogether
3. keep it how it is and mention the acceptable use of both `grey` and `gray`

cc/ @FreeCodeCamp/issue-moderators

**Comment by atjonathan** [comment]
@erictleung, I think we should choose option 2 and just change the color. That seems the easiest and simplest solution. Just pick a color e.g. pink that doesn't have english **(UK)** / english **(US)** issues.

**Comment by jarrydfillmore** [comment]
+1!

**Comment by BKinahan** [comment]
@atjonathan Funny that you mention UK/US english differences, since UK english users have to accept the (far more common) use of "color" in styling when their spelling is "colour" :)

And `hotpink` is in the expanded color list too, but I'd like to suggest either `silver` or `skyblue` as an alternative colo(u)r.
