### ISSUE TITLE
Using Night Mode should render the page content in a readable color

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#9512]
#### Algorithm Where Art Thou (Wiki)

https://www.freecodecamp.com/wiki/en/algorithm-where-art-thou/

#### Issue Description
First, visit the wiki page linked above, while you are not on night mode. See how the website content text is in black color, and the background is white, so it's readable - 

![screenshot 2016-07-02 16 17 09](https://cloud.githubusercontent.com/assets/11348778/16542300/01b25f8a-4071-11e6-8915-f69d17acfb35.png)

Now, switch to "Night Mode" in the settings page, and visit the same page again. The background color turns dark/black, and the text color also remains black, which makes the text barely readable.

![screenshot 2016-07-02 16 08 49](https://cloud.githubusercontent.com/assets/11348778/16542303/29c6eba8-4071-11e6-98f8-ab1aa9a7e5ee.png)

Perhaps the font color should change to a more readable color in night mode?

#### Browser Information

* Browser Name, Version: Google Chrome, Version 51.0.2704.103 (64-bit)
* Operating System: Mac OSX 
* Mobile, Desktop, or Tablet: Desktop

I came across this issue while working on a PR in a wiki page for the "Wherefore Art Thou" challenge, but I suspect this issue would occur across all wikis on night mode.

**Comment by atjonathan** [comment]
Thanks for reporting. This is a know issue (#8504). Closing as duplicate.
