### ISSUE TITLE
Links break in FCC Wiki 

### ISSUE THREAD

**Issue by arun1595** [FreeCodeCamp/FreeCodeCamp#9513]
I noticed that a couple of links are breaking in FreeCodeCamp wiki.
 - Camperbot https://freecodecamp.github.io/wiki/en/CamperBot
 - Template https://freecodecamp.github.io/wiki/en/Algorithm-Wiki-Template

**Comment by arun1595** [comment]
https://www.freecodecamp.com/wiki/

**Comment by erictleung** [comment]
To contributors, [this file](https://github.com/FreeCodeCamp/wiki/blob/f77228f65a50cc190abbdeb665efa11ca7f04753/Home.md) needs to be edited with the correct links.

```
[template](wiki-template-challenge-solution)
```

I'm not sure how to fix the Camperbot link though cc/ @FreeCodeCamp/issue-moderators

**Comment by Rafase282** [comment]
These issues should be fixed through https://github.com/FreeCodeCamp/wiki-generator/issues/58 not by directly renaming the link. The links are dynamically edited via the script there.

Furthermore, we are moving the wiki tot he forum and this will not be an issue there.
