### ISSUE TITLE
Error in testing

### ISSUE THREAD

**Issue by sethkoch** [FreeCodeCamp/FreeCodeCamp#9520]
The problem is with the testing that takes place.  This is one of the test that are run : 

confirmEnding("He has to give me a new name", "me") should return true.

This should return false, not true.  

Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20if(str.split(%22%20%22).length%20%3D%3D%3D%201)%7B%0A%20%20return%20str%5Bstr.length%20-1%5D%20%3D%3D%3D%20target%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20str%20%3D%20str.split(%22%20%22)%3B%0A%20%20%20%20return%20str%5Bstr.length%20-1%5D%20%3D%3D%3D%20target%3B%0A%20%20%7D%0A%7D%0A%0AconfirmEnding(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  if(str.split(" ").length === 1){
  return str[str.length -1] === target;
  }
  else{
    str = str.split(" ");
    return str[str.length -1] === target;
  }
}

confirmEnding("Bastian", "n");

```

**Comment by BKinahan** [comment]
Please explain your reasoning why `confirmEnding("He has to give me a new name", "me")` should return `false` while it's acceptable to you that `confirmEnding("Bastian", "n")` should return `true`.

The challenge is to confirm that the ending of the first string matches the second string, and the ending of `"He has to give me a new name"` (the substring of the final two characters) is `"me"`, so it is correct that it should return `true`.

**Comment by Bouncey** [comment]
@sethkoch please provide your reasoning for it to resolve as `false`

**Comment by erictleung** [comment]
@sethkoch closing as stale. If you still are having issues with the tests, please provide your reasoning for your statements. Happy coding!
