### ISSUE TITLE
Roman Numerals code passes every test but won't accept code.

### ISSUE THREAD

**Issue by gsc229** [FreeCodeCamp/FreeCodeCamp#9521]
Challenge [Roman Numeral Converter](https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=function%20convert(num)%20%7B%0A%20%20var%20toRoman%20%3D%20%22%22%3B%0A%20%20%20%20%20%20%20%20%2F%2Findex%3A%20%200%20%20%20%201%20%20%20%20%202%20%20%20%203%20%20%20%20%204%20%20%20%205%20%20%20%206%20%20%20%20%207%20%20%20%20%208%20%20%20%209%20%20%20%20%2010%20%20%2011%20%20%20%2012%0A%20%20var%20romNums%20%3D%20%5B%22M%22%2C%20%22CM%22%2C%20%22D%22%2C%20%22CD%22%2C%20%22C%22%2C%20%22XC%22%2C%20%22L%22%2C%20%22XL%22%2C%20%22X%22%2C%20%22IX%22%2C%20%22V%22%2C%20%22IV%22%2C%20%22I%22%5D%3B%0A%20%20%20%20%20%20%20%2F%2Findex%3A%20%20%200%20%20%20%20%201%20%20%20%202%20%20%20%203%20%20%20%204%20%20%205%20%20%206%20%20%20%207%20%208%20%20%209%20%2010%2011%2012%0A%20%20var%20numbers%20%3D%20%5B1000%2C%20900%2C%20500%2C%20400%2C%20100%2C%2090%2C%2050%2C%2040%2C%2010%2C%209%2C%205%2C%204%2C%201%5D%3B%0A%20%20%20%20%20%20%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20numbers.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20while(num%3E%3Dnumbers%5Bi%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20toRoman%20%3D%20toRoman%20%2B%20romNums%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20num%20%3D%20num%20-%20numbers%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%0A%20%20%20%20return%20toRoman%3B%0A%7D%0A%0A%0Aconvert(44)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(num) {
  var toRoman = "";
        //index:  0    1     2    3     4    5    6     7     8    9     10   11    12
  var romNums = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"];
       //index:   0     1    2    3    4   5   6    7  8   9  10 11 12
  var numbers = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];
        for(var i = 0; i < numbers.length; i++){
          while(num>=numbers[i]){
            toRoman = toRoman + romNums[i];
            num = num - numbers[i];
          }
        }
  
    return toRoman;
}


convert(44);

```

**Comment by Bouncey** [comment]
@gsc229 You have changed the function name. Our tests call that specific function during the tests.

**Comment by gsc229** [comment]
oh, right.  I see.  Thanks!
