### ISSUE TITLE
Code editor not able to add code to last line 

### ISSUE THREAD

**Issue by twhite96** [FreeCodeCamp/FreeCodeCamp#9522]
#### Challenge Name

All challenges

#### Issue Description

I go to a challenge. Try to add code to the last couple of lines. The cursor will not go any farther until I hit return and go back up a few lines. The cursor skips over a whole line when pressing return.

#### Browser Information

Chrome Version 51.0.2704.103 (64-bit)
Mac OS X 10.11.5
Desktop

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

#### Screenshot

No screenshot available. Would need a gif

**Comment by BKinahan** [comment]
This is a duplicate of #7847. There is plenty of information and discussion there, so you can keep track of the issue there :)
