### ISSUE TITLE
Broken trailing comment tags,

### ISSUE THREAD

**Issue by Chiemychanga** [FreeCodeCamp/FreeCodeCamp#9525]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A%3C!--%20--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3C!--%20--%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3C!--%20--%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!-- -->
<h1>Hello World</h1>
<!-- -->
<h2>CatPhotoApp</h2>
<!-- -->
<p>Hello Paragraph</p>

```

**Comment by Bouncey** [comment]
@Chiemychanga There is still one test left to pass, unless I am missing something?

Please see the test suite under the `Run test` button

**Comment by arun1595** [comment]
@Bouncey The test checks for the absence of -->. But since the OP had comments all over, the tests fail.  
I think we should take care of that. What do you think?

**Comment by Bouncey** [comment]
Now I understand. 

cc @FreeCodeCamp/issue-moderators Is the test for trailing comments redundant/unnecessary?

**Comment by arun1595** [comment]
I think the test is necessary because without that test, a camper can get through with code like this.
```
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragraph</p>
-->
```
The first three tests would still pass. So, the test which checks for trailing comments is not redundant and actually needed.
