### ISSUE TITLE
Inform with the Paragraph Element

### ISSUE THREAD

**Issue by supertrek** [FreeCodeCamp/FreeCodeCamp#9528]

**Comment by Bouncey** [comment]
@supertrek please go to the challenge you have an issue with, click the `bug` button and follow the instructions for creating my github issue.

Doing this will help us help you as it will provide us with more data,

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue is legitimate!
Use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
