### ISSUE TITLE
Completed achieve before achieving it

### ISSUE THREAD

**Issue by lucianomdangelo** [FreeCodeCamp/freecodecamp#953]
I haven't finished the import of the font and the "Go to my next challenge" button has already been unlocked.
![screen shot 2015-06-16 at 22 06 08](https://cloud.githubusercontent.com/assets/10271923/8197817/0ce75eb6-1474-11e5-85b2-c32b3b220e49.png)

Challenge http://www.freecodecamp.com/challenges/waypoint-import-a-google-font has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by BerkeleyTrue** [comment]
This should be fixed now.

Happy Coding!
