### ISSUE TITLE
Bind ESC key to collapse map

### ISSUE THREAD

**Issue by jboxman** [FreeCodeCamp/FreeCodeCamp#9530]
When clicking Map from the menu, the map slides out. The only way to collapse it again is using the X.

client/main.js:298
`
$('.map-aside-action-collapse').on('click', collapseMap);
`

Would an event handler that fires on keyup for ESC key work?

This is a wish list item. Mostly I wanted to see if I could locate where in the code this happens. Thanks!

**Comment by erictleung** [comment]
@jboxman this has been an intuitive thing for me to want to do too. I've put this code underneath the one you've cited and tested it and it works.

```js
$(document).keyup(function(e){
  if (e.keyCode === 27) collapseMap();
});
```

@FreeCodeCamp/issue-moderators good to add?

**Comment by chuckadams** [comment]
I tried implementing it myself:
```javascript
window.Mousetrap.bind('esc', () => {
  collapseMap();
});
```

But I ran into a maddening bug: the binding doesn't work unless one clicks outside of the map, then presses ESC.  Just to make it interesting, the binding works just fine any subsequent time you open the map, it just fails to take the first time the map slides out.

There's some further subtleties too, possibly related: the `esc` key currently clears the map filter, so the map ought only be collapsed if the input is already blank (i.e. one hits esc twice).  This is straightforward to check for, but I got nowhere, as I found that ESC would be ignored at all times whenever the search box had focus.

Might be easier to fix this in the react branch.

**Comment by systimotic** [comment]
@BerkeleyTrue Why was this closed?

I'm working on fixing this (rather, I've fixed this) but I'm unsure about some of the implementation details. 
Currently, pressing escape with the input in focus empties out the input. If we want this feature, it would make sense to get rid of this functionality. Our options are either removing focus from the input on pressing escape, or to close it immediately. What would be the best option?

/cc @FreeCodeCamp/moderators

**Comment by raisedadead** [comment]
> Why was this closed?

Issues which do not see any activity for prolonged periods of time and aren't mission critical can be closed with 'decayed' flag.

They may be re-opened if the activity picks up.

If you have a fix, please make a pull request.

Thanks.

**Comment by systimotic** [comment]
Ok, thanks @raisedadead! I'll fine-tune what I have and submit a PR

**Comment by BerkeleyTrue** [comment]
@systimotic You might want to hold off. We are in the process of removing all the sidecar related drawers.
