### ISSUE TITLE
Test is incorrectly resulting in false.

### ISSUE THREAD

**Issue by josephbrockw** [FreeCodeCamp/FreeCodeCamp#9532]
#### Challenge Name

https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20longest%20%3D%201%3B%0Avar%20myArray%3B%0Afunction%20findLongestWord(str)%20%7B%0A%20%20myArray%20%3D%20str.split(%22%20%22)%3B%0A%20%2F%2F%20console.log(myArray%5B1%5D.length)%3B%0A%0A%20%20for(i%20%3D%200%3B%20i%20%3C%20myArray.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if(myArray%5Bi%5D.length%20%3E%20longest)%20%7B%0A%20%20%20%20%20%20longest%20%3D%20myArray%5Bi%5D.length%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20console.log(longest)%3B%0A%20%20return%20longest%3B%0A%7D%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B%0A

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: iOS
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

var longest = 1;
var myArray;
function findLongestWord(str) {
  myArray = str.split(" ");
 // console.log(myArray[1].length);

  for(i = 0; i < myArray.length; i++) {
    if(myArray[i].length > longest) {
      longest = myArray[i].length;
    }
  }

  console.log(longest);
  return longest;
}

findLongestWord("May the force be with you");

#### Screenshot

<img width="843" alt="screen shot 2016-07-03 at 11 21 09 pm" src="https://cloud.githubusercontent.com/assets/11033221/16550782/f09e0834-4174-11e6-924d-b16d7623ffd1.png">

**Comment by erictleung** [comment]
@josephbrockw thanks for your issue but there's nothing wrong with the tests. The tests run your function one time after each other so those global variables you've made are changed accordingly. Move those within your function and you shouldn't have any problems. Happy coding!
