### ISSUE TITLE
bug in button bootstrap

### ISSUE THREAD

**Issue by roncemine** [FreeCodeCamp/FreeCodeCamp#9536]
Challenge [Apply the Default Bootstrap Button Style](https://www.freecodecamp.com/challenges/apply-the-default-bootstrap-button-style#?solution=%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn-default%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn-default%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22bbtn-default%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button class="btn btn-default></button>
        <button class="btn btn-default></button>
        <button class="btn btn-default></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button class="btn-default></button>
        <button class="btn-default></button>
        <button class="bbtn-default></button>
      </div>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@roncemine thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: check that all quotes have matching end quotes and also check for spelling errors. Happy coding!
