### ISSUE TITLE
Error during unit-test, Record Collection.

### ISSUE THREAD

**Issue by willfree108** [FreeCodeCamp/FreeCodeCamp#9539]
#### Challenge Name

Record Collection

#### Issue Description

If I test by hand updateRecords(5439, "tracks", "Take a Chance on Me");  it wont work, otherwise any other test will work and valid challenge.

try : 

#### Invalid Code

```js
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {

  if(prop !== "tracks")
  {
    collection[id].tracks = [];
    collection[id][prop] = value;
  } 
  else if (value)
     collection[id].tracks.push(value);
  if (value === "")
    delete collection[id][prop];
  return collection;
}

// Alter values below to test your code

updateRecords(5439, "tracks", "Take a Chance on Me");
```
Change the calling function, by one of these and it will work and valid :
``` 
updateRecords(5439, "artist", "ABBA");
updateRecords(2548, "artist", "");
updateRecords(1245, "tracks", "Addicted to Love");
updateRecords(2468, "tracks", "Free");
updateRecords(2548, "tracks", "");
```

The solution to the first test : 

#### Valid Code

```js
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {

  if(prop !== "tracks")
  {
    collection[id].tracks = [];
    collection[id][prop] = value;
  } 
  else if (value)
  {
     if (collection[id].hasOwnProperty("tracks") === false)
        collection[id].tracks = [];
     collection[id].tracks.push(value);
  }
  if (value === "")
    delete collection[id][prop];
  return collection;
}

// Alter values below to test your code

updateRecords(5439, "tracks", "Take a Chance on Me");
```
I simply check if tracks exist, otherwise I init.

### Possible Cause

- It's maybe during unit-test, tracks is initialized before the test updateRecords(5439, "tracks", "Take a Chance on Me"); I dunno how unit-test work on js.

- Or maybe the case described is insufficient : 
```
Origine : 
If prop does not contain the key "tracks" before you update it, create an empty array before pushing a track to it.
```
If prop contain tracks but tracks isn't init, create an empty array ?

- Maybe a strict mode.

#### Browser Information

In fact is not only me, someone on glitter called my help for this challenge which I already  solved and I noticed this test was weird.

* Browser Name, Version: Mozilla 47.0
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: 

Hope my information are relevant.
Sorry for my bad english, have a nice day.

**Comment by BKinahan** [comment]
The instructions for this challenge have been changed in [this recent pull request](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9472), and the site will soon be updated with the change.

Perhaps it will be helpful to include the new instruction text here to reduce confusion until the update goes live:

> You are given a JSON object representing a part of your musical album collection. Each album has several properties and a unique id number as its key. Not all albums have complete information.
Write a function which takes an album's <code>id</code> (like <code>2548</code>), a property <code>prop</code> (like <code>"artist"</code> or <code>"tracks"</code>), and a <code>value</code> (like <code>"Addicted to Love"</code>) to modify the data in this collection.
If <code>prop</code> isn't <code>"tracks"</code> and <code>value</code> isn't blank, update or set the <code>value</code> for that record album's property.
Your function must always return the entire collection object.
There are several rules for handling incomplete data:
If <code>prop</code> is <code>"tracks"</code> but the album doesn't have a <code>"tracks"</code> property, create an empty array before adding the new value to the album's corresponding property.
If <code>prop</code> is <code>"tracks"</code> and <code>value</code> isn't blank, push the <code>value</code> onto the end of the album's existing <code>tracks</code> array.
If <code>value</code> is blank, delete that property from the album.
<strong>Hints</strong><br>Use <code>bracket notation</code> when <a href="accessing-objects-properties-with-variables" target="_blank">accessing object properties with variables</a>.
Push is an array method you can read about on <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push">Mozilla Developer Network</a>.
You may refer back to <a href="manipulating-complex-objects">Manipulating Complex Objects</a>Introducing JavaScript Object Notation (JSON)</a> for a refresher.

**Comment by willfree108** [comment]
Oh my bad, thank you.

If I see someone stuck about that on gitter I'll give the new instruction text.
It sure helpful, some are stuck while trying test 2.

Have a nice day.
