### ISSUE TITLE
Waypoint: Change the Font Size of an Element

### ISSUE THREAD

**Issue by Legalyze** [FreeCodeCamp/freecodecamp#954]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue.
***The challenge says to make the p elements set the font-size to 16 px.
![screen shot 2015-06-16 at 9 33 14 pm](https://cloud.githubusercontent.com/assets/8771202/8198070/5f4f6018-146f-11e5-9ae3-1c36f3f9a3a1.png)

**Comment by BerkeleyTrue** [comment]
This should be fixed now. Feel free to reopen if issue still persist.
