### ISSUE TITLE
A car has more than 1 seat usually

### ISSUE THREAD

**Issue by JonathanScher** [FreeCodeCamp/FreeCodeCamp#9544]
Challenge [Construct JavaScript Objects with Functions](https://www.freecodecamp.com/challenges/construct-javascript-objects-with-functions#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20MotorBike%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%202%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%201%3B%0A%7D%3B%0A) has an issue.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I would change the numbers of seats for the object "car" to 5, as per the previous challenge.

Original text:
```javascript

var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 1;
};

// Only change code below this line.

var MotorBike = function() {

};


Prefered text:
```javascript

var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 5;
};

// Only change code below this line.

var MotorBike = function() {
  
};

```

**Comment by erictleung** [comment]
@JonathanScher agreed. A typical car usually has five seats, unless we're talking about the [Tango T600](http://www.hybridcars.com/tango-t-600/) 😆 

[This line in the seed code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/dbc347a8b6b0cd17234ee361a79abef9905a7e63/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L73), [this line in the instructions](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/dbc347a8b6b0cd17234ee361a79abef9905a7e63/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L62)and [this line in the solution](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/dbc347a8b6b0cd17234ee361a79abef9905a7e63/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L86) all need to be changed to be `this.seats = 5;`

To contributors, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by alanbares** [comment]
K just submitted a PR and fixed this.

**Comment by astuter** [comment]
I am working on this issue.

**Comment by erictleung** [comment]
@astuter unfortunately, someone else had already made a PR after yours. If you're still interested in contributing, you can check out [issues with "Help Wanted"](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22). Feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.
