### ISSUE TITLE
The freecodecamp editor went down when opened the challenge "Sum All Odd Fibonacci Numbers"

### ISSUE THREAD

**Issue by renewu0707** [FreeCodeCamp/FreeCodeCamp#9546]
The freecodecamp editor went down each time I opened the challenge "Sum All Odd Fibonacci Numbers Incomplete" under the category of Intermediate Algorithm Scripting. So I cannot compete that challenge. Other challenges are all fine except this one.

I've put some codes inside the challenge the first time I opened it, but I cannot because it always went down after that time.

Is there something with my browser settings or the online editor?

Thank you very much for the help.

**Comment by erictleung** [comment]
@renewu0707 sorry to hear you're having issues with the editor. Do you have a screenshot of your issue? You might have an infinite loop in your code. Try [disabling your code to auto run](https://github.com/freecodecamp/freecodecamp/wiki/FreeCodeCamp-Disable-Code-Autorun) and see if that helps.

**Comment by renewu0707** [comment]
Hi Eric,

Thanks for your reply. The screenshot is in the attachment. I can still see
my codes (which were incorrect, but I don't think it had an infinite
loop.), but I cannot edit it. The page just die, i couldn't do anything but
close it. However, I tried the disabling auto run solution but it didn't
work, there is no response of the page if I added the run=disable into the
url.

Do you have any other suggestions? Thank you so much.

Rene


Thank you.

Best regards
Rene

**Comment by erictleung** [comment]
@renewu0707 sorry, but it turns out you can send attachments through email to GitHub. If you can head over to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9546 and drag and drop your image in the comment box, we'll be able to see it.

Also, if you could copy-paste your code into the comment box as well, that'll be great. Thanks!

**Comment by renewu0707** [comment]
@erictleung sorry i am quite familiar with Github. I attached the screenshot here. The codes are inside the screenshot. The page died so I couldn't copy the code as text.

![issue](https://cloud.githubusercontent.com/assets/17485102/16596845/91770e64-42aa-11e6-8b8a-51df1458a532.png)

**Comment by renewu0707** [comment]
@erictleung Another thing is I happened to open the page on another computer, it works. However, after I put some codes inside, it died again. I guess I have some infinite loop or bad codes here. But the run=disabled stuff cannot help me open the page.

Thank you for your help.

**Comment by erictleung** [comment]
@renewu0707 sorry for the late response. Mmm I'm not sure what the issue could be. Your code doesn't appear to give an infinite loop and its odd that if only affects this challenge.

cc/ @FreeCodeCamp/issue-moderators any ideas on where or if this is a known issue?

**Comment by raisedadead** [comment]
@erictleung Could be a loopProtect bug.

@renewu0707 Coud you add `//noprotect` the top (first line) an then add your code. If that lets you pass then its definitely the case.

**Comment by raisedadead** [comment]
Closing as stale, please comment to re-open after you have a chance to trouble shoot.

**Comment by Margaret2** [comment]
Hi, I also had this issue, put in a simple for loop and the entire page froze up. 
The //noprotect didn't help, but disabling the auto-run did and I was able to reset the code. It is weird that it only affects this challenge. 
![codebugsnip](https://cloud.githubusercontent.com/assets/18198357/18030313/f46d0546-6c76-11e6-8cdd-8c23a4a1b93f.JPG)
