### ISSUE TITLE
Wikipedia CORS Does Not Accept External Website Requests (such as Codepen)

### ISSUE THREAD

**Issue by sentedelviento** [FreeCodeCamp/FreeCodeCamp#9547]
Despite the MediaWiki API claiming to support CORS requests, this open ticket says otherwise: 
https://phabricator.wikimedia.org/T62835
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-wikipedia-viewer
#### Issue Description

Students who follow the instructions on the 'Build a Wikipedia Viewer' page, will try to use CORS to make calls using JSON to the Wikimedia API. This is impossible, the only way to access their API is with JSONP, which does work, although I have read a few tickets here that indicate some people are having trouble with JSONP as well. However, I have had no problems getting JSONP to work, and I suspect that issues with JSONP are likely a result of a misunderstanding of invoking XMLHttpRequest, which will not work with JSONP. 

I got it working using jQuery's .ajax, and including 'callback=?' in the url.
#### Browser Information

Issue is almost certainly present in all browsers, though I haven't ran any code in IE.
- Browser Name, Version: Chrome, V51
- Operating System: Mac OS X
- Mobile, Desktop, or Tablet: Desktop

**Comment by dhcodes** [comment]
I do agree that there should probably be a step in the directions to add `&callback=?` to the API URL as I'm not sure there is another way to get the results to codepen without it, and this question does come up on the chat quite a bit. At the same time, it encourages people to use Read-Search-Ask and visit the chatroom, but I'm not sure that visiting the chatroom out of frustration should be a goal.

What do others think?

**Comment by sentedelviento** [comment]
I think that people are able to figure out a workaround by using &callback=?, but I don't think most people understand why this is necessary. The link to the Media Wiki API FreeCodeCamp provided has inaccurate information. If you think that causing needless confusion to promote 'question-asking' ability, we should just include more intentionally misleading information, to give students more practice sorting out their confusion.

**Comment by dhcodes** [comment]
Yeah, I don't think we should promote misinformation. So what's the best way to solve this? Add a step to the instructions regarding `&callback=?` with "Read more..." link to something explaining why it's necessary?

**Comment by sentedelviento** [comment]
Although &callback=? is the solution, I don't think it explains the problem very well. I think the solution would be to add a step that says that the Media Wiki API doesn't support CORS requests, and that the getaround to this problem is to use jsonp, then maybe link to a page explaining how to use jsonp, which may include callbacks.

**Comment by BFunk86** [comment]
If you read the Wikipedia documentation (which is very daunting) there are a few pages that explain this step. I remember trying adding the whole callback=? and it still dodnt work for me. I had to add dataType="json" to get it to work. The links can be found here:
https://m.mediawiki.org/wiki/Manual:CORS
https://m.mediawiki.org/wiki/API:Cross-site_requests
Or you can check put my code here: http://codepen.io/Youngbd/full/yJzLBJ/

**Comment by QuincyLarson** [comment]
We are removing this challenge from our core curriculum (it will be an optional extra project) so I'm closing this issue.
