### ISSUE TITLE
Invalid Test Results with No Repeats Please

### ISSUE THREAD

**Issue by reggie3** [FreeCodeCamp/FreeCodeCamp#9548]
The test case of aaabb should have 120 total permutations (5! = 120).  I followed Heap's algorithm as posted on wikipedia and calculated 120 permutations.

     110 of the permutations are the following 9 strings which have same consecutive letters:
1. aaabb
2. aabab
3. aabba
4. abaab
5. abbaa
6. baaab
7. baaba
8. babaa
9. bbaaa

    Removing all examples of these 9 permutations leaves 10 permutations that appear to pass the consecutive letters case as I read and interpret it it.   Btw, I found these matches using the regular expression `/(.)\1+/g;`
However, the answer on the challenge page says that there are 12 permutations from this given test case.  Which of the nine listed permutations count as valid answers?

This same issue affects the "abcdefa" and "abfdefa" strings.

```
// array that will hold the permutations
// it is emptied each time the permAlone function is called
var perms = [];

function permAlone(str) {
     var strArr = str.split("");
     //console.log(strArr);

     // empty the answer array each time this function is called
     perms = [];
     permutator(strArr.length, strArr);
     console.log(str + " - num perms: " + perms.length);
     // console.log(perms.join(", "));
     perms = removeDuplicates();
     console.log(perms.length);
     return perms.length;
}

/**
 * removeDuplicates
 *   does a filter to remove array elments with consecutive duplicate characters "aa", "bbb", etc.
 * @returns - array with duplicate elements removed
 */
function removeDuplicates() {
     var removeCounter = 0;
     var regEx = /(.)\1+/g;

     var finalPerms = perms.filter(function (element, index, array) {
          if (element.match(regEx)) {
               console.log("removed: " + element);
               removeCounter++;
               return false;
          }
          else {
               return true;
          }
     });
     console.log("Removed: " + removeCounter);
     return finalPerms;
}

/**
 * permutator
 *
 * @param {any} arr - an array of characters to be permutated
 * @return perms - an array of permutated strings
 */
function permutator(n, array) {

     function swap(a, b) {
          var temp = array[a];
          array[a] = array[b];
          array[b] = temp;
     }

     if (n === 1) {
          perms.push(array.join(""));
          //return array;
     }
     else {
          for (var i = 0; i < n - 1; i++) {
               permutator(n - 1, array);


               if (i % 2 === 0) {
                    swap(i, n - 1);
               }
               else {
                    swap(0, n - 1);
               }
          }
          // console.log(array.toString());
          permutator(n - 1, array);
     }
}
```

**Comment by BKinahan** [comment]
I haven't looked through all of your code, but maybe I can point you in the right direction.

Your implementation of Heap's algorithm seems to generate permutations in uneven proportions, and to miss some permutations altogether.

Consider the input `"abcde"` which should also generate 120 permutations, each of which is unique. A correct solution to this challenge will generate each permutation once. With your code, some permutations are generated more than once (some up to four times) and some not at all. For example, the string `"decab"` is not generated. You can see this for yourself by running [this code](https://repl.it/C8f3/0) (your code above, with the return value of `permAlone` altered to show each permutation and the number of times it occurs in the `perms` array). When applied to strings with repeated characters such as `"aaabb"` this effect causes problems when counting the number of permutations without consecutive letter repeats.

Please also note that code writing assistance can be found in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) and the other help rooms (which is much faster than waiting for a response here 😄), and issues are for reporting bugs with challenges or the website.

Happy coding!

**Comment by reggie3** [comment]
BKinanhan, thank you.  I was able to find my mistake; it was just a matter of changing one i to an n.
