### ISSUE TITLE
Challenge [Link to External Pages with Anchor Elements]

### ISSUE THREAD

**Issue by supertrek** [FreeCodeCamp/FreeCodeCamp#9549]
Hello World 

I am using Google Chrome Version 51.0.2704.106 m (64-bit)

I have deleted my cookies changed browsers the error message does not change. I have googled and tried the freecode camp help line and have not found a solution. I have now been asked to report this as a BUG

Errror message:
You need an a element that links to http://freecatphotoapp.com

This is my entire code given below :

```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>
 View more <a href="http://www.freecatphotoapp.com">cat photos</a>
</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by erictleung** [comment]
@supertrek thanks for the issue. If you look at the test

> You need an a element that links to http://freecatphotoapp.com

It asks specifically for `http://freecatphotoapp.com` but your code has `http://www.freecatphotoapp.com` with the `www` in it. That's why you're not passing the test. Happy coding!

**Comment by supertrek** [comment]
Thanks.


Lesson Learnt :  (As stated in the initiation ) READ

[😊]
________________________________

**Comment by joykama** [comment]
Transfer my account prabayar maxis
