### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by amitdante** [FreeCodeCamp/FreeCodeCamp#9550]
Challenge [/challenges/target-the-parent-of-an-element-using-jquery](https://www.freecodecamp.com/challenges/target-the-parent-of-an-element-using-jquery#?solution=%24(%22%23left-well%22).parent().css(%22background-color%22%2C%20%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
$("#left-well").parent().css("background-color", 

```

**Comment by amitdante** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19373438/16570525/6536a6ca-4264-11e6-8415-fb522df79da1.png)

**Comment by atjonathan** [comment]
Your code is incorrect. You will need to reset the challenge, as you don't have the correct `challengeSeed`.
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by amitdante** [comment]
Actually when the screen loads it should show the code i wrote in the previous slide, but it shows only this one line, if i write whole of that code again here (or copy it) then it shows error in script tag as if JQuery is not running.
