### ISSUE TITLE
Screen not showing any code

### ISSUE THREAD

**Issue by amitdante** [FreeCodeCamp/FreeCodeCamp#9551]
Challenge [/challenges/target-the-parent-of-an-element-using-jquery](https://www.freecodecamp.com/challenges/target-the-parent-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Actually when the screen loads it should show the code i wrote in the previous slide, but it shows only this one line, if i write whole of that code again here (or copy it) then it shows error in script tag as if JQuery is not running.
![untitled](https://cloud.githubusercontent.com/assets/19373438/16570676/187c6618-4268-11e6-9a5b-37df8823295b.png)

My code:
```

undefined

```

**Comment by amitdante** [comment]
See what happens if i write the code myself.
![untitled](https://cloud.githubusercontent.com/assets/19373438/16570692/50224862-4268-11e6-911b-ca68e3abae95.png)

**Comment by atjonathan** [comment]
Cannot reproduce. cc/ @FreeCodeCamp/issue-moderators

**Comment by BKinahan** [comment]
@amitdante What happens if you click the Reset button? Does the editor contain only `undefined`?

**Comment by amitdante** [comment]
Yes, exactly. Still undefined.

**Comment by Bouncey** [comment]
@amitdante do you have a different browser you could try it in?

**Comment by amitdante** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19373438/16575878/2ebe4da6-42a9-11e6-97d3-89e2a8202dee.png)

Here is Internet Explorer Screenshot.

The link is :
https://www.freecodecamp.com/challenges/target-the-parent-of-an-element-using-jquery

**Comment by BKinahan** [comment]
That text at the bottom of the screenshot looks like a clue about what's going wrong here, looks like code from https://github.com/FreeCodeCamp/FreeCodeCamp/blob/94f9d0b11491cd6be11e9f1e19596d2b83313be5/server/views/challenges/showJS.jade or another Jade file. 

@amitdante are there any errors in the browser console?

Can anyone reproduce this?

**Comment by amitdante** [comment]
No there are no errors, Since this challenge is not mandatory for certification and its basic stuff I will just move ahead of it, but the moderators should check the site if it is an issue which can trouble other people.
Thanks to everyone for helping.
Regards.

**Comment by Bouncey** [comment]
@amitdante is it just this challenge? Or are there others?

**Comment by amitdante** [comment]
Only on this particular challenge exercise, the ones before it and after it work perfectly.

**Comment by Bouncey** [comment]
@amitdante are you able to try a different machine or device?

**Comment by raisedadead** [comment]
By the first looks of this looks like someone/somehow is injecting "malicious code" on the pages.
Please try the below and let us know how it works:

1. On Chrome, Go to Extensions and disable all extensions (no need to remove).
2. Open an incognito Window.
3. Visit the challenges and test the Scenario.

If the above works, you can try disabling the extentions one by one to know which one is messing with the page.

If the above doesn't work:
1. You could be behind a ISP that is causing the trouble : [Follow this guide in that case](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Browsec-Security)
2. Your PC could be infected, run a scan with a anti-malware/anti-virus.

Thanks and happy coding!

**Comment by h4yfans** [comment]
@amitdante Try Shift+F5.

**Comment by raisedadead** [comment]
Closing as stale. Please comment if you are still facing this.
