### ISSUE TITLE
Remove unnecessary spaces

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9554]
#### Challenge Name

https://www.freecodecamp.com/challenges/iterate-over-arrays-with-map

#### Issue Description

There are unnecessary line breaks in "Iterate over Arrays with .map".

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/78a1240f4f9a4c4ecf02ec30a871f4fdc64b83ee/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L309) and [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/78a1240f4f9a4c4ecf02ec30a871f4fdc64b83ee/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L341) need to be removed.

#### To Contributors

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled as `first-timers-only` so only those who have never contributed to FreeCodeCamp's main repo can take up this issue.

#### Screenshot

**Now:**
![image](https://cloud.githubusercontent.com/assets/2754821/16571542/2c619f0e-4213-11e6-9a49-beaf6746f8b7.png)

**After:**
![image](https://cloud.githubusercontent.com/assets/2754821/16571544/468805da-4213-11e6-9cd0-3c727593836a.png)

**Comment by TheOneAmir** [comment]
Can I have this one?

**Comment by erictleung** [comment]
@TheOneAmir unfortunately, it looks like someone else make a PR already #9556. There are [two other `first-timers-only`](https://github.com/FreeCodeCamp/FreeCodeCamp/labels/first-timers-only) issues that are fairly written on what needs to be fixed if you're looking to resolve another issue.
