### ISSUE TITLE
Update Mobile Responsive Images waypoint copy

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#956]
The following is verbatim copy edit proposed by a camper:

50] Waypoint:  Mobile Responsive Images   "Your new image should have the class "img-responsive".  Could be misinterpreted to lead one to create this as  `<style> .img-responisve {} </style>` and then add the coding` <img src="http://bit.;y/fcc-kittens2" class="img-responsive" />`.    But actually the way "class" is worded might lead anyone to code both lines  when only the 'wording'    `class=img-responsive" />` need be tacked onto the end of the `<img src="http://....` code line in order to complete the assignment.    Thinking that just because "class" goes into the element it should ALSO be placed as a class i.e.,   `.img-responsive{}`  can be the misleading idea here when it comes to CSS.

**Comment by BerkeleyTrue** [comment]
edit: added back ticks around code segments for clarity.

**Comment by BerkeleyTrue** [comment]
We would like feedback from other campers who completed this waypoint. Specifically, did you find the instructions misleading or confusing?

**Comment by LumenTeun** [comment]
Personally, I don't find the instructions that confusing. One minor improvement could possibly be changing ```First, add a new image with the src attribute of "http://bit.ly/fcc-kittens2", and add the "img-responsive" Bootstrap class to that image.``` to something along the lines of ```First, add a new image with the src attribute of "http://bit.ly/fcc-kittens2", and the Bootstrap class "img-responsive".```, but I'm not sure.

From what I can gather, the instructions only mention adding a class along with the image, so there shouldn't be too much room for confusion.

[Link to the relevant waypoint](http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images)

**Comment by aldraco** [comment]
The confusion might be because this is the first waypoint that deals with Bootstrap classes, and everyone has just been taught to make their own. Perhaps adding a short note about what Bootstrap is might clear up confusion, i.e. it's a library of pre-made CSS classes to use (just like the ones campers have just been building themselves).

Perhaps...
"Now we're going to learn about some of Bootstrap's handy pre-formatted CSS classes. For example, the Bootstrap class .img-responsive makes your images adjust appropriately to any screen width. Try it out!"

.. or something appropriately less cheesy than what I wrote :)

**Comment by jkmanning** [comment]
I'm having trouble with this Waypoint.  I've followed the instructions numerous times; however, it's still telling me that I need to add the second image which is displaying on my app.  Anyone else having this problem?

**Comment by sarahj4077** [comment]
me too.  I have tried it a bunch of different ways and stil can't get past it.

**Comment by jkmanning** [comment]
Sarahj4077, I ended up leaving it for a day or two, and when I went back and re-did the problem, it worked!

**Comment by GwenWinegar** [comment]
Thank you Quincy. Removing the second line was very helpful.

**Comment by keuz37** [comment]
Stuck and then solved it.     My problem is that i copied and pasted from the first "src" line of code.   As a result of that, "https" was carried across and deemed incorrect by the parser for the second "src" required to pass through.    Took a while to discover that.   Perhaps, to help us to avoid this mistake, could the first "src"'s "https" be changed to "http"?    Or is this the way to get coders to learn from this example, the perils of cut-and-paste in coding.  lols.     Hey, how about a button link to a solution page after X number of failed attempts?

**Comment by Madsailor65** [comment]
I'm having similar issue trying to add the second image.   code looks fine, app looks fine, but am not able to complete the challenge.....

**Comment by jetstone** [comment]
So going back to the initial posted comment, Are two issues here?
1. the instructions to the users may not be as clear as it could be.(how can I help resolve this?)
2. the syntax of code on this page is not linking up with check that being done on the users input (is anyone working on this if not can I help?)

Offtopic:
Keuz37 brings up an interesting concept of creating a learning experience from copy and pasting of code. Maybe there can be debugging way-points sprinkled through out a collection.

**Comment by jayGorio** [comment]
This worked for me. First i need to copy the first img together with all of its class. Then paste it for the second image. Then remove the first img-responsive class in the first img
  
![bootcamp](https://cloud.githubusercontent.com/assets/11474751/9102297/1ae13600-3c23-11e5-82bf-204cf9d90b06.PNG)

**Comment by ZinaRae** [comment]
Thanks keuz37 I made the same mistake as you, I read your comment, deleted 2 S's and now my code works... : )

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
