### ISSUE TITLE
"Ditch Custom CSS for Bootstrap" Run Test Don't Work help me !!!

### ISSUE THREAD

**Issue by nassimols** [FreeCodeCamp/FreeCodeCamp#9560]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by Bouncey** [comment]
@nassimols 

Please got to the challenge you are having issue with and click on the 'Bug' button and follow the steps there. If you have a genuine issue, we need more information than you have supplied, this is gathered during these steps.

I hope we can resolve your issue for you.

**Comment by pleabargain** [comment]
here's the working code
https://gist.github.com/pleabargain/4c5689ba51ec795dd6e7ccd75d76a0b2

the img-responsive must be on BOTH images to pass
url for FCC of working code 
https://goo.gl/Al0R3U
