### ISSUE TITLE
another bug in change font size

### ISSUE THREAD

**Issue by tristochief** [FreeCodeCamp/FreeCodeCamp#9562]
#### Issue Description
Even after following all of the instructions for this challenge, and trying both firefox and chrome, I still cannot pass the level

#### Browser Information
firefox version 47.0
and tried chrome version 51.0.2704.103
* Operating System: 
windows 10

#### problem trying to solve:
![capture](https://cloud.githubusercontent.com/assets/9490719/16574474/a31dd4aa-42c2-11e6-8f54-63bf45cf1de5.PNG)

#### Your Code
![capture](https://cloud.githubusercontent.com/assets/9490719/16574495/e5ea8f1c-42c2-11e6-8924-4d8dbaf32ca9.PNG)

**Comment by erictleung** [comment]
@tristochief thanks for the issue but you've actually used the wrong text in your `<p>` element.

> Your `p` element should contain the first few words of **the provided additional** `kitty ipsum text`.

Look back in the instructions to find the correct text. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
