### ISSUE TITLE
Change number of car seats to 5

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9565]
#### Challenge Name

https://www.freecodecamp.com/challenges/make-instances-of-objects-with-a-constructor-function

#### Issue Description

Same issue as #9544 but in another challenge.

#### To Fix
[This line in an example block](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9c172454fcc1b637830a5fd6ff3cdf20d0543b6/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L120), [this line in the challenge seed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9c172454fcc1b637830a5fd6ff3cdf20d0543b6/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L132), and [this line in the solution](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a9c172454fcc1b637830a5fd6ff3cdf20d0543b6/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L143) needs to be changed to have 5 seats (e.g. `this.seats = 5;`).

#### To Contributors

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help. 

This issue is labeled `first-timers-only` so only those who have not contributed to Free Code Camp's main repository may resolve this issue. 

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/16577406/ef70ff54-4249-11e6-9878-93713c8cdcbe.png)

**Comment by BhaveshSGupta** [comment]
Can I take up this and any one can actually help me too!

**Comment by BKinahan** [comment]
@BhaveshSGupta Visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room as @erictleung mentioned.

**Comment by ladybugtju** [comment]
Hi there 
Excellent explanations Eric! I just made a pull request with the number #9578. Not sure how to link bug reports and pull requests. Title: Change number of car seats to 5 #9565 #9578.
