### ISSUE TITLE
New Challenge Layout for Responsive Web Design Challenges

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9567]
For at least the responsive design challenges (FreeCodeCamp/CurriculumExpansion#10) we will need the user to be able to change the width and height of the iphone. I propose we don't use an iphone and instead have a box that has controls like:

[![https://gyazo.com/93851318e82fcf083ac00cdd93856257](https://i.gyazo.com/93851318e82fcf083ac00cdd93856257.gif)](https://gyazo.com/93851318e82fcf083ac00cdd93856257)

We would also show what width and height the viewport is when they change the size
In the responsive challenges, we have media query challenges etc. that will need the user to easily see what their css does. this seems the best option ^^

**Comment by BerkeleyTrue** [comment]
Please follow the instructions laid out in the curriculum expansion issues
