### ISSUE TITLE
No file path in process arguments

### ISSUE THREAD

**Issue by TJBANEY** [FreeCodeCamp/FreeCodeCamp#9570]
Challenge [Start a Nodejs Server](https://www.freecodecamp.com/challenges/start-a-nodejs-server) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When I try and run my program "node program.js" for the challenge "My first I/O" it is saying that process.argv[2] is undefined, when there should be a file path in that index. It gives me this error. 

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/ubuntu/workspace/program.js:5:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

My code

var fs = require("fs")

var filePath = process.argv[2];
var filePathArray = fs.readFileSync(filePath).toString().split("\n")

console.log(filePathArray.length);

**Comment by arun1595** [comment]
`process.argv[2]` is undefined because you didn't pass the path as a command line argument. You should run the program using
```
node program.js your-path
```
Moderators, please close this since it has nothing to do with a bug in the site.

**Comment by atjonathan** [comment]
Thanks @arun1595 :tada:
