### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by achalofficial** [FreeCodeCamp/FreeCodeCamp#9571]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20'Here%20is%20a%20backslash%3A%20%5C%5C%5C.%5Cn%5Ct%5Ct%20Here%20is%20a%20new%20line%20with%20two%20tabs.'%3B%20%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = 'Here is a backslash: \\\.\n\t\t Here is a new line with two tabs.';  // Change this line



```

**Comment by johnaoss** [comment]
@achalofficial Don't include a space before it, not a bug.

**Comment by BerkeleyTrue** [comment]
@achalofficial Issue tracker is for reporting bugs only.

Please use the appropriate channels when looking for help.

Happy Coding
