### ISSUE TITLE
Update Code of Conduct Spamming definition

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9579]
We want to update Free Code Camp's [code of conduct](http://freecodecamp.com/code-of-conduct) of spamming to include soliciting donations.

Here's the current copy:

![](https://www.evernote.com/l/Ar9xdtg_Dg5MW5AeFi2wvA3jXzeYZPII5uEB/image.png)

The new definition should read: 

Spamming includes posting off-topic messages to disrupt discussions, promote a product, or solicit donations.

**Comment by joshghent** [comment]
Going to work on this. It might not be code but it's still gonna be my first OSS contribution!

**Comment by erictleung** [comment]
@joshghent please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.
