### ISSUE TITLE
Wording of the Exact Change challenge is confusing

### ISSUE THREAD

**Issue by shamieya** [FreeCodeCamp/FreeCodeCamp#9580]
Challenge [Exact Change](https://www.freecodecamp.com/challenges/exact-change) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The issue doesn't really have anything to do with my code; I'm not even close to an answer yet. The instructions say " Return the string "Insufficient Funds" if cash-in-drawer is less than the change due. "  In the second-to-last (7th) example there is 1.01 in the drawer and the change is 0.50 but the answer is "Insufficient Funds." The cash-in-drawer is not less than change due. I assume this answer is because there are no coins to return. I think the instructions should be reworded to reflect that if there are not enough coins to return change, return "Insufficient Funds."

I also do not care for the test case that returning 0.50 requires quarters. In real life, I could return dimes, nickels or pennies.  That's just a little nit pick though.

My code:
```javascript

function checkCashRegister(price, cash, cid) {
  
  //Find total amount in drawer
  var totalArray=[];
  var answerArray=[];
  var change = 0;
  
  for (var i = 0; i < arguments[2].length; i++) {
    totalArray.push(arguments[2][i][1]);
  }
  var longTotal = totalArray.reduce(  (prev,curr) => (prev+curr));
  var total = longTotal.toFixed(2);
  
  //Determine the amount of change
  change = (cash - price).toFixed(2);
  
  if (total == change) {
    return "Closed";
  } else if (total < change) {
    return "Insufficient Funds"; 
  } else if (total > change) {


var twenties = 0;
var tens = 0;  
  //Break down change
  
  }
}

// Example cash-in-drawer array:
// [["PENNY", 1.01],
// ["NICKEL", 2.05],
// ["DIME", 3.10],
// ["QUARTER", 4.25],
// ["ONE", 90.00],
// ["FIVE", 55.00],
// ["TEN", 20.00],
// ["TWENTY", 60.00],
// ["ONE HUNDRED", 100.00]]

checkCashRegister(19.50, 20.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]); 

```

**Comment by shamieya** [comment]
I see someone reported this recently and was advised it is not a bug.

A bug is a deviation from the expected behavior of the application. I think it definitely qualifies as a bug; instructions should be corrected.

**Comment by AdventureBear** [comment]
I agree...the error code returned could be worded better.

 "Insufficient Funds" for a bank overdraft doesn't take into account what type of bills the bank has sitting in their vault. 

"Cannot make change right now" would be a better message to return, and is more reflective of a real life situation.   There's no need to be cryptic with a challenge like this meant to replicate a real world function.
