### ISSUE TITLE
Seems to be a bug in the commenting challenge, with the ending comment trail. I am sure I don't have a trail. 

### ISSUE THREAD

**Issue by saritapdx** [FreeCodeCamp/FreeCodeCamp#9581]
#### Challenge Name
https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A%3C!--here%20is%20the%20header--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3C!--here%20is%20the%20subheader--%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--here%20is%20the%20paragraph--%3E%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A

#### Issue Description
I am sure I don't have a trailing comment and can't pass without deleting it. If it's not there... I am confused. i tried the forum - but the comments didn't show, so noone knew what I was talking about. 

#### Browser Information

* Chrome Version 51.0.2704.106 (64-bit)
* Operating System: Mac - El Capitano
* Mobile, Desktop, or Tablet: MabBook Pro

#### Your Code

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

```js
 
```

#### Screenshot

<img width="317" alt="screen shot 2016-07-05 at 8 26 12 pm" src="https://cloud.githubusercontent.com/assets/20094898/16606686/c7cc787a-42ee-11e6-9489-aae1298749da.png">

**Comment by saritapdx** [comment]
never mind. I figured out uncomment meant delete the comment. Slow on the uptake.

**Comment by Bouncey** [comment]
Thanks for reporting this issue. We are aware of it and a patch has been applied. Unfortunately, it is waiting for the next release into production. The PR that addresses this issue is here #9572 

For now, to complete the challenge, please remove all comments from your code. 

Thanks for contributing :tada:

**Comment by Bouncey** [comment]
@saritapdx Your solution in the original issue was correct. It was more a failing of our tests.
