### ISSUE TITLE
Test case always fail for removing artist property

### ISSUE THREAD

**Issue by popofly** [FreeCodeCamp/FreeCodeCamp#9582]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; 
InfoPath.3; MS-RTC LM 8; rv:11.0) like Gecko</code>.

Test case: After updateRecords(2548, "artist", ""), artist should not be set 

This test case is always fail. The collection is printed in alert window and it is proven the 'artist' property is removed but the test case is still failed. There is no report for this bug yet. Is it a new bug?

My code:
```javascript
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value){ 
  if(value === undefined || value.length === 0){
    alert(id); 
    delete collection[id][prop];
    alert(JSON.stringify(collection));
  }

  
  if(prop !== "tracks"){
    
    collection[id][prop] = value;
  } else {
    if(value !== undefined && value.length >0){
   
      if(!collection[id].hasOwnProperty(prop)){
        var trackArray = [];
        trackArray.push(value);
        collection[id][prop] = trackArray;
        
      } else {


        collection[id][prop].push(value);
      }      
      
    } 
    
  }


  return collection;
}

// Alter values below to test your code
updateRecords(2548, "artist", "");


![result](https://cloud.githubusercontent.com/assets/17896111/16609628/226da26a-4388-11e6-96d3-0bc4f62ef148.png)

**Comment by BKinahan** [comment]
Aside from being an annoying way to test code, your alerts have misled you. You do delete the `"artist"` property for that test case with your first if statement, but then with your second if statement you set it to `""` (`collection[id][prop] = value;`)

Please seek assistance in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) when stuck with code. Issues are for reporting bugs with the challenges or website.

Happy coding!

**Comment by atjonathan** [comment]
Thanks @BKinahan :smile:

**Comment by popofly** [comment]
Thanks! @BKinahan

**Comment by IrshadAhmad** [comment]
I have the following code for https://www.freecodecamp.com/challenges/record-collection:
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  if(prop=="tracks") {
    if(!collection[id].hasOwnProperty(prop))
        collection[id][prop]=[];
    if(value === undefined || value.length === 0)
      delete collection[id][prop]; 
    else
      collection[id][prop].push(value); 
  }
  else
  {
    if(value.length!==0)
      collection[id][prop]=value; 
  }
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");
updateRecords(5439, "tracks", "Take a Chance on Me");
updateRecords(2548, "artist", "");
updateRecords(2468, "tracks", "Free");

The out put looks to be correct but test case:
After updateRecords(2548, "artist", ""), artist should not be set

failing awlays.
Please help me.

**Comment by yayakyogi** [comment]
// Setup
const recordCollection = {
  2548: {
    albumTitle: 'Slippery When Wet',
    artist: 'Bon Jovi',
    tracks: ['Let It Rock', 'You Give Love a Bad Name']
  },
  2468: {
    albumTitle: '1999',
    artist: 'Prince',
    tracks: ['1999', 'Little Red Corvette']
  },
  1245: {
    artist: 'Robert Palmer',
    tracks: []
  },
  5439: {
    albumTitle: 'ABBA Gold'
  }
};

// Only change code below this line
function updateRecords(records, id, prop, value) {
  let obj = records;
  if(value == ''){
    delete obj[id][prop]
  }
  else if(prop !== 'tracks' && value !== ''){
    obj = {
      ...records,
      [id]:{
        [prop]:value
      }
    }
  }
  else if(prop === 'tracks'){
    if(obj[id].hasOwnProperty('tracks')){
      obj[id].tracks.push(value)
    }else{
      obj[id].tracks = [];
      obj[id].tracks.push(value)
    }
  }
  return obj;
}

console.log(updateRecords(recordCollection, 2548, 'artist', ''));

// its work for me

**Comment by ankitptl96** [comment]
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
    if(value==="") {
      delete collection[id][prop];
    } else if(prop === "tracks"){
      collection[id][prop] = collection[id][prop] || [];
        collection[id][prop].push(value);
      }else{
        collection[id][prop] = value;
      }
    
  return collection;
}

// Alter values below to test your code
updateRecords(2468, "tracks", "test");
console.log(updateRecords(5439, "artist", "ABBA"));
