### ISSUE TITLE
Convert JSON Data to HTML should use 'strong' and self-closing br

### ISSUE THREAD

**Issue by nicoleneo** [FreeCodeCamp/FreeCodeCamp#9586]
Challenge [Convert JSON Data to HTML](https://www.freecodecamp.com/challenges/convert-json-data-to-html#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON(%22%2Fjson%2Fcats.json%22%2C%20function(json)%20%7B%0A%0A%20%20%20%20%20%20%20%20var%20html%20%3D%20%22%22%3B%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%20%20%20%20json.forEach(function(val)%20%7B%0A%20%20%20%20%20%20%20%20%20%20var%20keys%20%3D%20Object.keys(val)%3B%0A%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3Cdiv%20class%3D'cat'%3E%22%3B%0A%20%20%20%20%20%20%20%20%20%20keys.forEach(function(key)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3Cstrong%3E%22%20%2B%20key%20%2B%20%22%3C%2Fstrong%3E%3A%20%22%20%2B%20val(key)%20%2B%20%22%3Cbr%20%2F%3E%22%3B%0A%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3C%2Fdiv%3E%3Cbr%20%2F%3E%22%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24(%22.message%22).html(html)%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json", function(json) {

        var html = "";
        // Only change code below this line.
        json.forEach(function(val) {
          var keys = Object.keys(val);
          html += "<div class='cat'>";
          keys.forEach(function(key) {
            html += "<strong>" + key + "</strong>: " + val(key) + "<br />";
          });
          html += "</div><br />"
        });
        
        
        // Only change code above this line.

        $(".message").html(html);

      });
    });
  });
</script>

<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
   </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

**Comment by revisualize** [comment]
I clicked the link and it worked just fine. I also pasted your code into the editor and it worked just fine.

I also reset the challenge and used the code in the instruction text.

No issue.

```js
json.forEach(function(val) {
  var keys = Object.keys(val);
  html += "<div class = 'cat'>";
  keys.forEach(function(key) {
    html += "<b>" + key + "</b>: " + val[key] + "<br>";
  });
  html += "</div><br>";
});
```

**Comment by erictleung** [comment]
@nicoleneo thanks for the feedback. I can agree with the `<strong>` tag but can you cite your sources on why we need to have self-closing `<br>` tags? The [W3 HTML5 entry on `<br>`](https://www.w3.org/TR/html5/text-level-semantics.html#the-br-element) doesn't use self-closing tags. However, for XHTML and XML, I guess you [do need self-closing tags for `<br>`](http://stackoverflow.com/a/15149657).

**Comment by BKinahan** [comment]
I think what @nicoleneo is suggesting is that the example code should use `<strong>` in place of `<b>` and `<br />` in place of `<br>`

There is an argument that `<strong>` should be used instead of `<b>` where the text it encloses has some semantic importance, whereas `<b>` is for non-semantic text decoration, but I'm not sure that applies here.

In HTML5, `<br>` is fine. The closing `/` can be used but has no effect. (See [here](https://www.w3.org/TR/html5/syntax.html#start-tags), `br` is one of the `void elements` mentioned), so that change is not needed.

Anyway, bike-shedding, yay 😄

**Comment by dhcodes** [comment]
Went ahead and changed `<b>` to `<strong>` since that seemed to be the consensus. I left `<br>` as-is.
