### ISSUE TITLE
"Bonfire: Truncate a String" needs additional tests.

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/FreeCodeCamp#959]
Challenge http://www.freecodecamp.com/challenges/bonfire-truncate-a-string has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The instructions indicate the dots ('...") need to be factored into the string length when truncating the string. However you can get away with `str.split(0, 8)` instead of `str.split(0, num - 3)` since there is only one test where the string is truncated. If there is another test with a different max length, `str.split(0, 8)` will fail because it should have been truncated at another spot and the correct solution will need to be used instead.

**Comment by benschenker** [comment]
Looks like this is fixed and can be closed
