### ISSUE TITLE
golf code

### ISSUE THREAD

**Issue by NadaH** [FreeCodeCamp/FreeCodeCamp#9595]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(strokes%3D%3D1)%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7Delse%20if(strokes%20%3C%3Dpar-2)%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7Delse%20if(strokes%3D%3Dpar-1)%7B%0A%20%20%20%20return%22Birdie%22%3B%0A%20%20%7Delse%20if%20(strokes%3D%3Dpar)%20%7B%0A%20%20%20%20return%20%22par%22%3B%0A%20%20%7Delse%20if%20(strokes%3D%3Dpar%2B1)%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7Delse%20if%20(strokes%3D%3Dpar%2B2)%7B%0A%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7Delse%20if%20(strokes%3E%3Dpar%2B3)%7B%0A%20%20%20%20return%20%22Go%20Home!%22%3B%0A%20%20%7Delse%7B%0A%20%20%20%20%0A%20%20%0A%20%0A%20%20return%20%22Change%20Me%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20%7D%0A%7D%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%205)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
# the test is okay
**I don't know what is the matter**
![my code](https://cloud.githubusercontent.com/assets/19336016/16643215/d034752e-4412-11e6-9181-f31cf00a6d58.PNG)
![req](https://cloud.githubusercontent.com/assets/19336016/16643218/dabd711c-4412-11e6-8484-5872905c66da.PNG)

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes==1){
    return "Hole-in-one!";
  }else if(strokes <=par-2){
    return "Eagle";
  }else if(strokes==par-1){
    return"Birdie";
  }else if (strokes==par) {
    return "par";
  }else if (strokes==par+1){
    return "Bogey";
  }else if (strokes==par+2){
  return "Double Bogey";
  }else if (strokes>=par+3){
    return "Go Home!";
  }else{
    
  
 
  return "Change Me";
  // Only change code above this line
  }
}
// Change these values to test
golfScore(5, 5);


```

**Comment by erictleung** [comment]
@NadaH please check the case of each golf phrase. You'll need to code the phrases precisely as they are in the instructions. If you get stuck with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
