### ISSUE TITLE
Invalid Error when trying to submit "Using Objects for Lookups"

### ISSUE THREAD

**Issue by Cassandra12091** [FreeCodeCamp/FreeCodeCamp#9601]
#### Challenge Name
https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20var%20lookup%20%3D%20%7B%0A%20%20%20%20alpha%3A%20%22Adams%22%2C%0A%20%20%20%20bravo%3A%20%22Boston%22%2C%0A%20%20%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20%20%20delta%3A%20%22Denver%22%2C%0A%20%20%20%20echo%3A%20%22Easy%22%2C%0A%20%20%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20lookup%5Bval%5D%3B%20%20%2F%2F%20%3C-----%20%20%20They%20modified%20this%20line%0A%7D

#### Issue Description
I added in my code which doesn't include a case, switch or if statement and yet that's the error that I'm getting at the bottom.

#### Browser Information

* Browser Name, Version: Mozilla Firefox, 47.0
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
 var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };

  // Only change code above this line
  return lookup[val];  // <-----   They modified this line
}

```js
 
```

#### Screenshot

![ffcerror](https://cloud.githubusercontent.com/assets/8696426/16656271/09d4be42-442c-11e6-9c32-705da8efe0c9.PNG)
![ffcerror](https://cloud.githubusercontent.com/assets/8696426/16656534/0fb28ae6-442d-11e6-821a-6a2040a0b5eb.PNG)

**Comment by raisedadead** [comment]
Hi @Cassandra12091 

Thanks for reporting but:

> `// <----- They modified this line`

Who modified this line?

Your code is not correct, check the instructions:
> Use it to lookup val and assign the associated string to the result variable.

GitHub issues are for bugs in website only. Please check below for help.
- [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Report-Bugs).
- [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Thanks and happy coding!
