### ISSUE TITLE
it wont turn blue for some reason did i do typo?

### ISSUE THREAD

**Issue by likwit69** [FreeCodeCamp/FreeCodeCamp#9603]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Manish-Giri** [comment]
@likwit69 You're missing the `h2` element in your HTML. Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) for questions about your code.

**Comment by bugron** [comment]
@likwit69 thanks for posting, @Manish-Giri thanks for answering. Closing this issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by freddiehdxd** [comment]
bro need to add the <h2>


<style>
  h2{color:blue;}
</style>

<h2>CatPhotoApp</h2>
