### ISSUE TITLE
FCC Challenges Already Solved

### ISSUE THREAD

**Issue by rigobertomolina** [FreeCodeCamp/FreeCodeCamp#9604]
#### Challenge Name

***EVERY CHALLENGE***

#### Issue Description
Every time I go to a new challenge the code is already solved so there is nothing to do but just run the test. I don't know if it's just a browser problem...

#### Browser Information
* Browser Name, Version:  Safari 10.0
* Operating System: macOS Sierra Developers Beta 1
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![screen shot 2016-07-07 at 12 26 16 pm](https://cloud.githubusercontent.com/assets/17030877/16666793/074a6070-443e-11e6-8b8e-7bb18df38803.png)

**Comment by rigobertomolina** [comment]
I just noticed there's an issue from using 2 accounts. I already passed these challenges in my account, but when my sister logs in, the challenges haven't been passed but the code needed is there. (The code I used) I think it's some type of storage problem.

**Comment by BKinahan** [comment]
Yup, code is saved in your local storage. You can delete them en masse if you like by following these steps: https://www.freecodecamp.com/wiki/en/freecodecamp-clear-specific-data-local-storage/ (you can delete more than one at a time)

But don't worry about your completed solutions being lost; those are saved with your account when you click "Submit and Continue", and you can access them by clicking "View Solution" on your FCC profile.

**Comment by raisedadead** [comment]
Alternatively you can also use separate user profiles on the PC or on the browser as well.
We have a feature comming up in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9130 that will remove the locally stored solutions, until then please try the workarounds as @BKinahan mentioned or the above.

Thanks and happy coding!
