### ISSUE TITLE
word blanks

### ISSUE THREAD

**Issue by shivani2108** [FreeCodeCamp/FreeCodeCamp#9609]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by kado88** [comment]
Stop sending me E-mails!!! I deleted FCC!!!!

**Comment by raisedadead** [comment]
Hello @kado88!

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Comment by raisedadead** [comment]
@shivani2108 

Please refer : [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Report-Bugs).

Closing.
