### ISSUE TITLE
Bug on Opera, Firefox and Chrome "Change the Font Size of an Element"

### ISSUE THREAD

**Issue by mapgyik** [FreeCodeCamp/FreeCodeCamp#9610]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20.p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3Ekitty%20ipsum%20text%20Kitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3Ekitty%20ipsum%20text%20Purr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  .p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">kitty ipsum text Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>kitty ipsum text Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

I'm having the following problem using Opera, Firefox, Chrome: 
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41```

"Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%."

![no_pass_bug](https://cloud.githubusercontent.com/assets/18014742/16679473/243178e0-44e8-11e6-9c51-b2e8a6b72242.png)

I have tried the suggested methods (zoom 100%, restart) from other issues (#6242, #6335, #6664) did not solve the problem...

Kindly ask you to look into the situation.

**Comment by Bouncey** [comment]
@mapgyik there is an error in your code. Please you the 'help' button to ask in the chat rooms.

Quick hint: The issue is in how you have selected the p element in your css

**Comment by mapgyik** [comment]
Thanks for the quick reply. For others who are stuck with this, here is the correct code:
```
<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
</style>
```
hint: "." is only used for a class . and p is an element. just use p

**Comment by mapgyik** [comment]
Thanks for the quick reply.

For others who also stuck with this issue: 
>. is only used for a class . and p is an element.just use p

**Comment by Riverino** [comment]
that is right, it works for me. thanks
