### ISSUE TITLE
Something is wrong with the validator

### ISSUE THREAD

**Issue by IulianChirvasa** [FreeCodeCamp/FreeCodeCamp#9617]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20a%20%5C%22double%20quotes%5C%22.%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "I am a \"double quoted\" string inside a \"double quotes\"."; // Change this line



```

**Comment by Jaskaranbir** [comment]
It should be:

`var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line`

(remove that `a`)

**Comment by BerkeleyTrue** [comment]
@Jaskaranbir Thanks!

@IulianChirvasa Please use the help chat rooms when you are stuck.

Happy Coding.
