### ISSUE TITLE
Wrong information being shown on claim certificate

### ISSUE THREAD

**Issue by dlwebdev** [FreeCodeCamp/FreeCodeCamp#9619]
#### Challenge Name
https://www.freecodecamp.com/challenges/claim-your-data-visualization-certificate

#### Issue Description
When confirming completion of React and D3 it says "Front End Development Certificate requirements" in the brown box. I believe it should say "Data Visualization Certificate requirements" instead.

#### Browser Information
All

#### Screenshot

![screenshot from 2016-07-08 14 41 17](https://cloud.githubusercontent.com/assets/668910/16698038/654ab4fe-451a-11e6-9c57-0edd52f3dd7e.png)

**Comment by BKinahan** [comment]
It probably should be green, too, instead of brown 😄 

Definitely needs an image update.

**Comment by dlwebdev** [comment]
I can take care of this image replacement. Do you know what font family that is?

**Comment by atjonathan** [comment]
@dlwebdev Great! I believe it is `SaxMono` or `Monaco` :smile:

**Comment by dlwebdev** [comment]
How's this image look? It looks like the font was indeed Monaco, so thanks for that.
![new-data-visualization-requirements](https://cloud.githubusercontent.com/assets/668910/16710623/0540af2a-4603-11e6-8d4c-283ff56414c6.png)

**Comment by dlwebdev** [comment]
Here's a link to the existing image:
https://i.imgur.com/14F2Van.jpg 

And the new one for comparison:
http://i.imgur.com/nTuA3rZ.png

**Comment by dlwebdev** [comment]
Do you guys have an imgur account that you want to post this image to or can we just use the link to the one I create?

**Comment by dlwebdev** [comment]
And should we also replace the image before this one regarding plagiarism with the FCC green background as well?
https://www.freecodecamp.com/challenges/claim-your-data-visualization-certificate

**Comment by atjonathan** [comment]
@dlwebdev, this looks great! No, we will just use the link you provided.

**Comment by dlwebdev** [comment]
Some of the images for Spanish and French were using english. I've created new images for those as well and also changed the Congratulations! image to have the green background as well, so in total there is 9 new images. ( 3 for each language).

I'm going to go back and check these slides for the front end certificate as well and will open a new issue if those need to be updated in either wording in other languages or the color of the slides.

**Comment by atjonathan** [comment]
@dlwebdev thank you!!

**Comment by atjonathan** [comment]
Fixed in #9666
