### ISSUE TITLE
Misspelling of Brackets

### ISSUE THREAD

**Issue by LeeWarnock** [FreeCodeCamp/FreeCodeCamp#9623]
Misspelling in the challenge question: 
Access MultiDimensional Arrays With Indexes
One way to think of a multi-dimensional array, is as an array of arrays. When you use brackets to access your array, the first set of **bracket** refers to the entries in the outer-most (the first level) array, and each additional pair of brackets refers to the next level of entries inside.

should be plural "brackets"

**Comment by atjonathan** [comment]
Thanks for catching this @LeeWarnock :wink:  
**To First Timer:**
You will need to change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1769) line. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:

**Comment by sergroja** [comment]
Can I work on the issue.

**Comment by arun1595** [comment]
@sergroja If you're a first-timer, please go-ahead.

**Comment by sergroja** [comment]
Okay I will work on this issue.

**Comment by Grantlyk** [comment]
This can be closed as it was fixed by https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9640

**Comment by erictleung** [comment]
@Grantlyk thanks! Closing as resolved. Happy coding!
