### ISSUE TITLE
Random - Qoute-Machine code in codepen 

### ISSUE THREAD

**Issue by vaibsharma** [FreeCodeCamp/FreeCodeCamp#9637]
Challenge [Build a Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Hi 
I am Vaibhav Sharma . Recently while doing Random Quote Machine API based project , in the reference code of the project (which I opened just for the reference)I found the qoutes are missing the right qoute icon. 
You can see them in the attached file.
![screenshot from 2016-07-09 17 39 05](https://cloud.githubusercontent.com/assets/15328723/16707887/dc460422-45fc-11e6-93e9-dc3cc498d0f7.png).
I want you to review this bug ( Once you get free) .
Thank you

**Comment by abhisekp** [comment]
Please post your frontend related questions in https://gitter.im/FreeCodeCamp/HelpFrontend room

Include the following
- A link to your project url (codepen, etc)
- Description of the problem

**Comment by abhisekp** [comment]
I would say, it's an unique design to present the quote :smirk: 

> Just a UI design decision to think out of the box.

**Comment by qmikew1** [comment]
Visually, it creates a nice effect. It's also true people naturally look for closing quotes as it's sort of basic grammar thing.

**Comment by raisedadead** [comment]
It's just a visual style. Lot of quote sites use them and lots do not
For instance:

![image](https://cloud.githubusercontent.com/assets/1884376/16725187/c3bcc008-4773-11e6-8d59-a41fb61b9bbc.png)


Closing as bikeshedding.
