### ISSUE TITLE
can't complete a challenge. 2nd task says "$(...).attr(...) is undefined" 

### ISSUE THREAD

**Issue by leverington** [FreeCodeCamp/freecodecamp#964]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The first task is "Add a placeholder attribute text input element." Which I can complete.
The second task says "$(...).attr(...) is undefined". Which mean's what? Seems like a bug to me.

**Comment by leverington** [comment]
Update: I had to guess, and deleted the line that said "<input type='text'>
rather than only adding a new line with "placeholder" and the 'cat phot URL' text. 


having 

<input type='text''>
<input type='text' placeholder='cat photo URL'>

does not work'and results in the 2nd task looking like $(...).attr(...) is undefined. Having only

<input type='text' placeholder='cat photo URL'>

does work and the task shows up correctly.

**Comment by Groxx** [comment]
The assertion is at https://github.com/FreeCodeCamp/freecodecamp/blob/staging/seed/challenges/basic-html5-and-css.json#L1641 but I unfortunately don't know enough of the system to fix it :(
So I'm leaving this comment to maybe speed things along, and so I don't totally forget forever in case I get time to make a pull request.

**Comment by BerkeleyTrue** [comment]
fixed 

Happy coding!
