### ISSUE TITLE
The code is completed for the user already and by passing the users instructional inputs. The code is allowing the user to submit without even completing the instructional task. 

### ISSUE THREAD

**Issue by Grenexa** [FreeCodeCamp/FreeCodeCamp#9643]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by abhisekp** [comment]
@Grenexa please use the template provided for adding the relevant information for filing the issue.

You must include at least the following things for clarifying about your issue
- Challenge name
- Issue Description
- Code (*if applicable*)

**Comment by Grenexa** [comment]
I cleared my cache and it fixed the problem. Thanks. The problem is solved.

Sent from my HTC on T-Mobile 4G LTE

----- Reply message -----

**Comment by abhisekp** [comment]
nice mobile :smirk: 

you may close the issue
