### ISSUE TITLE
record collection "tracks" not verifying correctly? 

### ISSUE THREAD

**Issue by df6000** [FreeCodeCamp/FreeCodeCamp#9644]
I run the test cases, get the appropriate output for the variable 'collection', but the checker says something is wrong.  Is this a bug?  Perhaps related to the recent fix?  Thanks.

![takeachance](https://cloud.githubusercontent.com/assets/20364274/16708876/c73fc76c-45b5-11e6-8663-97717f91ce98.png)

**Comment by abhisekp** [comment]
@df6000 It would be really nice if you could share your code with the community in [![FreeCodeCamp/HelpJavaScript](https://img.shields.io/badge/Gitter_Chat_Room:-FreeCodeCamp/HelpJavaScript_⮭-006400.svg?style=flat-square&maxAge=2592000 "FreeCodeCamp/HelpJavaScript")](https://gitter.im/FreeCodeCamp/HelpJavaScript)  

Most probably, your code might have some bugs. 
Better to first verify with the community before filing an issue.

Thanks for caring :heartpulse:

**Comment by atjonathan** [comment]
@abhisekp :+1:
