### ISSUE TITLE
videos/computer-basics-measuring-data-speed Q1: bits -> bits/sec

### ISSUE THREAD

**Issue by bagrounds** [FreeCodeCamp/FreeCodeCamp#9646]
#### Challenge Name

https://www.freecodecamp.com/videos/computer-basics-measuring-data-speed

#### Issue Description

The first question: Data speed is measured in bits. True or False?

The correct answer should be false (but is currently true). Data speed is measured in bits per second.

**Comment by erictleung** [comment]
@bagrounds thanks for catching this. I believe the initial intent was to differentiate between bits and bytes. But I guess in doing so, it made it technically incorrect.

So I agree, [the question](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b4f108c1afa8bbb30fdeb4e3c81e409eef91f0df/seed/challenges/04-video-challenges/computer-basics.json#L373), [the text](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b4f108c1afa8bbb30fdeb4e3c81e409eef91f0df/seed/challenges/04-video-challenges/computer-basics.json#L365), and the [next question](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b4f108c1afa8bbb30fdeb4e3c81e409eef91f0df/seed/challenges/04-video-challenges/computer-basics.json#L379) should be changed to say that data speed is measured in bits per second.

To contributors, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue has been labeled as `first-timers-only` meaning that only individuals who have not contributed to the main FreeCodeCamp repository may fix this issue.

**Comment by andela-bebowe** [comment]
Can I work on this I am a first-timer ?

**Comment by andela-bebowe** [comment]
@erictleung Can I work on this I am a first-timer ?

**Comment by atjonathan** [comment]
@andela-bebowe, certainly :+1:
