### ISSUE TITLE
Pig Latin instructions translation - Es

### ISSUE THREAD

**Issue by BKinahan** [FreeCodeCamp/FreeCodeCamp#9648]
Spanish language translation for PR #9602

Added text: "Input strings are guaranteed to be English words in all lowercase."

**Comment by BeaCodes** [comment]
Here it is! "Cadenas de entrada están garantizadas de ser palabras en Inglés en minúscula."

**Comment by atjonathan** [comment]
@BeaCodes could you submit a pull request with the change? Thanks :smiley:
