### ISSUE TITLE
Pig Latin instructions translation - Fr

### ISSUE THREAD

**Issue by BKinahan** [FreeCodeCamp/FreeCodeCamp#9649]
French language translation for PR #9602

Added text: "Input strings are guaranteed to be English words in all lowercase."

**Comment by mizujin** [comment]
Here you go !

"Les chaînes de caractères entrées sont garanties d'être des mots anglais en lettres minuscules."

**Comment by atjonathan** [comment]
@mizujin, could you create a pull request with the change?
