### ISSUE TITLE
Not able to code it

### ISSUE THREAD

**Issue by priksp08** [FreeCodeCamp/freecodecamp#965]
Challenge http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by sourabhkumar0308** [comment]
You might have added an 'a' tag for cat photos in one of the previous exercise. Now in this exercise it asks you to add a 'p' tag to enclose 'a' tag.
So you don't have to create a seperate 'a' tag to enclose in a 'p' tag. Use your previous 'cat photos' tag and add a 'p' tag around it. Hope this helps.
