### ISSUE TITLE
Run test button not working- jQuery

### ISSUE THREAD

**Issue by hmorri32** [FreeCodeCamp/FreeCodeCamp#9653]
"Target Elements by Class using jQuery"

https://www.freecodecamp.com/challenges/target-elements-by-class-using-jquery

"Run Text" button works but won't proceed to next challenge. After completing section, can not proceed to the next. 

Using Safari.

My code, which works, is as follows... 

![screen shot 2016-07-09 at 8 57 20 pm](https://cloud.githubusercontent.com/assets/20346065/16711082/c3c079da-4617-11e6-9dc2-45937a3ab3bb.png)

**Comment by arun1595** [comment]
Please refresh and try submitting again.

**Comment by dhcodes** [comment]
@hmorri32 are you sure it passes? I think in line 5, it should be `addClass` instead of `addclass`. Maybe that's holding the challenge from passing.

**Comment by erictleung** [comment]
@hmorri32 what @dhcodes points out is probably the cause of your issue. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by grappler2** [comment]
I had to reset and add the correct code several times to pass the validation. There might be some funky whitespace/hidden character issues with this one.
