### ISSUE TITLE
Generate random whole number with javascript fail

### ISSUE THREAD

**Issue by zealsham** [FreeCodeCamp/FreeCodeCamp#9654]
#### Challenge Name

https://gitter.im/freecodecamp/freecodecamp
#### Your Code

```js
 var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  // Only change code below this line.
for(i=0; i<9; i++){
 DAM= (Math.random(i));
  J=10*DAM;
  w=Math.floor(J);
  
}
  return w;
}

```

**Comment by dhcodes** [comment]
@zealsham I think you're trying to get multiple random numbers via a loop when really you only need to get one random number between 0 and 9. Also, there are a few errors in your code such as:

1. Math.random() does not take a parameter.
2. You haven't defined DAM, J, or w.

The instructions give a pretty good outline for the code you'll need to write. Be sure to ask for help in the chat room if you need more assistance.

**Comment by erictleung** [comment]
@zealsham what @dhcodes advises is good.

> Use this technique to generate and _return a random whole number_ between 0 and 9.

If you get stuck with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
