### ISSUE TITLE
videos/big-o-notation-a-few-examples "exponential time" -> "polynomial time"

### ISSUE THREAD

**Issue by bagrounds** [FreeCodeCamp/FreeCodeCamp#9655]
#### Challenge Name

https://www.freecodecamp.com/videos/big-o-notation-a-few-examples

#### Issue Description

In the discussion and questions concerning big-o notation, O(N^2) is referred to as "exponential time", which is wrong. 

O(N^C), where C is any constant greater than 1 (e.g. 2) is called "polynomial time". 

Exponential time looks like O(C^N), where the input variable (N) is in the exponent.

Roughly speaking, the complexity class P (polynomial time solvable) is what we (or complexity theorists) consider "easy" - or at least solvable.

Exponential time algorithms typically have no hope of being solved on large inputs (and therefore are good candidates for heuristics, or approximations).

For a bit more intuition, an algorithm with O(N^2) complexity may not be a good candidate for real-time processing in your web app - but it may be perfectly suitable for less time critical tasks. With an algorithm like this, you might decide to pre-compute some solutions as a workaround.

With an exponential time algorithm O(C^N), on the other hand, the sun may burn out before your computation ends.

Concerning O(infinity) - notice the lack of an input variable (N), and that infinity isn't a number. It's probably best to replace that idea with a statement about non-terminating routines. This might lead into a discussion about the halting problem, for example.

**Comment by erictleung** [comment]
To contributors, [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/666f9c83b66a53e16bf411ba3a367996afcc1d54/seed/challenges/04-video-challenges/bigonotation.json#L79) needs to be changed to

> Algorithms expressed exponentially like O(C^N), where C is a constant, can work well in certain....

**Comment by RP99** [comment]
Hi, I would like to work on this issue.

**Comment by ltegman** [comment]
I wonder if this lesson might need more done to it than just a simple one sentence fix. The lesson text and quiz questions map directly to the video lesson, so correcting them while the video is saying something different would probably be confusing. This text fix might need to wait until there's a video fix. Or maybe we could add an errata at the top or bottom of the lesson text until the video is corrected?

**Comment by dapperAuteur** [comment]
I can work on creating a new video tomorrow afternoon.
