### ISSUE TITLE
it doesn't recognise the change in colour for some reason

### ISSUE THREAD

**Issue by NadaNM** [FreeCodeCamp/FreeCodeCamp#9659]
<img width="1426" alt="screen shot 2016-07-10 at 2 12 19 pm" src="https://cloud.githubusercontent.com/assets/20374347/16713228/5dfda54a-46a9-11e6-88ea-b8ae96be21ca.png">
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(255,0,0);
  }
  .orchid-text {
    color: rgb(218,112,214);
  }
  .sienna-text {
    color: rgb(160,82,45);
  }
  .blue-text {
    color: rgb(0, 0, 225);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by BKinahan** [comment]
Check your rgb values again.

Please seek code-writing assistance in the [Help Chat](https://gitter.im/FreeCodeCamp/Help). Issues are for reporting bugs with the challenges or website.

Happy coding!

**Comment by erictleung** [comment]
@NadaNM what @BKinahan advises is correct. If you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by Amarie1634** [comment]
@NadaNM  Did you get this figured out? I'm running into the same problem and am stuck.

**Comment by texas2010** [comment]
@Amarie1634 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
