### ISSUE TITLE
Exercise accepts Pixel and Percentage answer due to image dimensions

### ISSUE THREAD

**Issue by clearsmoke** [FreeCodeCamp/freecodecamp#966]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-circular-images-with-a-border-radius has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

For this exercise someone may accidentally use 50px instead of 50% and think it's Ok though the exercise calls for percentage. It just so happens to work for this exercise because the image is 100px and of course 50px is 50% of 100px. Really minor issue as I think everyone would figure this out during the exercise or when it comes up again. 

Sorry if this has been mentioned already; learning Git Hub

**Comment by digitaldak** [comment]
I think this was fixed in 1002 tonight by Quincy.  Wish  there was some way to link this to that one.

**Comment by clearsmoke** [comment]
..sorry, seeing this late, thanks guys!
