### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by farmanp** [FreeCodeCamp/FreeCodeCamp#9664]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStr%20%3D%20%22%5C%5C.%5Cn%5Ct%5CtHere%20is%20a%20new%20line%20with%20two%20tab.%5Cr%5C%5C%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "\\.\n\t\tHere is a new line with two tab.\r\\";
```

**Comment by BKinahan** [comment]
Take another look at the instructions; they have changed recently.

Please use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) if you get stuck writing code. Issues are for reporting bugs with the challenges or web site.

Happy coding!

**Comment by erictleung** [comment]
Closing as not a bug and issue has gone stale. Happy coding!
