### ISSUE TITLE
Streak Issues

### ISSUE THREAD

**Issue by evan153** [FreeCodeCamp/FreeCodeCamp#9665]
#### Issue Description

My streak ended last night randomly even though I completed some work. At least that's what I thought. The next day someone told me they can see my streak, but I can not. (See the screenshots)

#### Browser Information

* Browser Name, Version: Google Chrome not even sure what version
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

The user sent me this it shows the streak going fine. His timezone is GMT+5:30
http://i.imgur.com/NwaRiK6.png

But when I look at it.. My timezone UTC-08:00
http://imgur.com/uPyoOz1

**Comment by raisedadead** [comment]
This is a known issue, closing as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9665

**Comment by evan153** [comment]
That was from April is there still no fix?
