### ISSUE TITLE
Advanced solution for Whereforarthou

### ISSUE THREAD

**Issue by sethkoch** [FreeCodeCamp/FreeCodeCamp#9668]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 function whatIsInAName(collection, source) {
  // "What's in a name? that which we call a rose
  // By any other name would smell as sweet.”
  // -- by William Shakespeare, Romeo and Juliet
  var srcKeys = Object.keys(source);

  // filter the collection
  return collection.filter(function (obj) {
    return srcKeys.reduce(function (res, key) {
      return obj.hasOwnProperty(key) && obj[key] === source[key];
    }, false);
  });
}

// test here
whatIsInAName([{ first: "Romeo", last: "Montague" }, { first: "Mercutio", last: null }, { first: "Tybalt", last: "Capulet" }], { last: "Capulet" });
```

#### Screenshot

if you use {first : "ron", last: "Capulet"} as the source, you get a false positive.  The last object in the collection is returned but it shouldn't be because it is not a 100% match.

**Comment by raisedadead** [comment]
@sethkoch Thanks for reporting. Please open this issue on the [wiki repo](https://github.com/FreeCodeCamp/wiki).
