### ISSUE TITLE
Jts622

### ISSUE THREAD

**Issue by jts622** [FreeCodeCamp/FreeCodeCamp#9670]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A--%3E%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A--%3E%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

--><h1>Hello World</h1>

--><h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->


```

**Comment by dwd2010** [comment]
@jts622 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!
