### ISSUE TITLE
Challenge tests for jQuery fail to run

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9673]
Challenge tests for jQuery fail to run if syntax errors are present in a campers code. 

Examples:
#9289
#9082
#9470
#9672
#9698

What is stopping the tests running? Can we fix it?

Is there a way to lint jQuery in codemirror so campers get visual clues to syntax errors, like in the JS challenges? 

-Or-

When there is a syntax error, can we present a modal to the camper saying there is a syntax error present in their code when they click 'Run tests'?

**Comment by BerkeleyTrue** [comment]
@Bouncey Do these issue's persist on beta?

**Comment by raisedadead** [comment]
@FreeCodeCamp/issue-moderators can some one pitch in to check this? 
We have been getting a lot of similar issues lately.

**Comment by Bouncey** [comment]
@BerkeleyTrue from what I can see the bug is not present in beta. But there is no Bootstrap, so a lot of the html & CSS challenges don't make sense any more.

I will raise a separate issue for no Bootstrap.

**Comment by raisedadead** [comment]
@Bouncey @BerkeleyTrue from the reports this seems to be appearing for some HTML5, CSS and JavaScript challenges as well.

Should we update this issue to reflect the same?

**Comment by BerkeleyTrue** [comment]
Does the error not show up in the iframe window?

**Comment by raisedadead** [comment]
Will take a look next time I encounter it. Most of the times its not reproducible.
