### ISSUE TITLE
Computer Basics challenges : Take me to questions not working

### ISSUE THREAD

**Issue by sharkmanch** [FreeCodeCamp/FreeCodeCamp#9674]
i am having bug or error whatever at stage "Computer Basics" where when i click "take me to the questions it gives no reaction at all"
I tried both google chrome and internet explorer but its the same. But when i asked other users they claims that its working for them so i wonder if its about my firewall or what.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by raisedadead** [comment]
Hi @sharkmanch 

Thanks for reporting.

> But when i asked other users they claims that its working for them so i wonder if its about my firewall or what.

Please open issues after you confirm that others are facing the same in the chat room.

Nonetheless,
Alternatively check your browser's console (Open Dev tools), and visit the console tab. Then reload.
Also you haven't mentioned which OS you are on? 
Any screenshots that you can share?

Thanks.

**Comment by sharkmanch** [comment]
Dear guys,
I apologize for late reply. Ifound a way to make it work, using Safari to open it is working for me. 
However the problem is still happening on chrome or IE platform.
I noticed one problem i didnt mention. There 're suppose to be videos shown at the top of the page to introduce the computer basics. I can see it on safari its perfectly working but its not shown on chrome or IE. I think its connected too. Please check the attached file it shows how it looks like in chrome or ie.
![image](https://cloud.githubusercontent.com/assets/19811451/16758482/1e0c529e-4855-11e6-98c8-4d0d8aa0ef97.png)

**Comment by raisedadead** [comment]
Okay, this clears up the issue a bit more, clearly youtube (where the videos are hosted and embedded on the challenges page) is getting blocked somehow by the browser settings or the firewall.

If you open up the Developer tools on chrome (<kbd>F12</kbd> or Settings > More Tools > Developer Tools), you should see the error logs on the Console Tab.

Something like below or similar:
![image](https://cloud.githubusercontent.com/assets/1884376/16760584/101b713a-483a-11e6-8d89-5dd1683534f4.png)

Can you please check and confirm. Thanks.

**Comment by sharkmanch** [comment]
Uncaught TypeError: Array.from is not a functionbundle-cad26b4d13.js:16 

this is the error i saw.

**Comment by raisedadead** [comment]
@BerkeleyTrue any ideas for the above error?

> Uncaught TypeError: Array.from is not a functionbundle-cad26b4d13.js:16

**Comment by BerkeleyTrue** [comment]
@sharkmanch What version of chrome are you using?

**Comment by sharkmanch** [comment]
ver. 31.0.1650.63 m

**Comment by sharkmanch** [comment]
@BerkeleyTrue @raisedadead  Problem solved. I simply updated google chrome and its working now, thanks guys.

**Comment by raisedadead** [comment]
Great! Closing as resolved.

Happy Coding!
