### ISSUE TITLE
No repeat please not valid

### ISSUE THREAD

**Issue by willfree108** [FreeCodeCamp/FreeCodeCamp#9677]
#### No repeat please

https://www.freecodecamp.com/challenges/no-repeats-please

#### Issue Description

I got the right answer which also display in the black box but exept the first test none are valid.
So I can't valid this challenge despite having the good answer.

#### Browser Information

* Browser Name, Version: Firefox 47.0.1 and Google chrome 
* Operating System: win 7
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js
 var unique = 0;

function swap(arr, i, j) {
    var tmp;
  
    tmp = arr[i];
    arr[i] = arr[j];
    arr[j] = tmp;
}

function perm(arr, posAc, posEnd) {
    var i;
    if (posAc !== posEnd) {
        for (i = posAc; i < posEnd; i++) {
            swap(arr, posAc, i);
            perm(arr, posAc + 1, posEnd);
            swap(arr, posAc, i);
        }
    }
    else
    {
      if (arr.join('').match(/(.)\1/g) === null)
        unique++;
	}
}


function permAlone(str) {
  perm(str.split(''), 0, str.length);  
  return unique;
}

permAlone("abcdefa");
```

It display 3600 in the black box which is the right answer but dont valid.

#### Screenshot

![sans titre](https://cloud.githubusercontent.com/assets/10143821/16738887/e62c365e-4797-11e6-9138-e86eac0a8df5.png)

Have a nice day.

**Comment by Bouncey** [comment]
Please see #9199 

Although your code is correct. Manipulating global variables invalidates your code when we come to test it. We are discussing this in the linked-to-issue above

**Comment by willfree108** [comment]
Alright, thank you a lot !
