### ISSUE TITLE
Broken link and confusing language (Heroku or Cloud 9 for API Projects)?

### ISSUE THREAD

**Issue by dlwebdev** [FreeCodeCamp/FreeCodeCamp#9678]
#### Challenge Name
https://www.freecodecamp.com/challenges/request-header-parser-microservice 

#### Issue Description

I'm working through the API Projects challenges and came across a few things.

First off, there is a broken link to the following in #2 for those challenges:
https://freecodecamp.com/challenges/get-set-for-our-back-end-development-projects 

I believe that link should go to: https://www.freecodecamp.com/challenges/get-set-for-our-api-development-projects 

```
Note that for each project, you should create a new GitHub repository and a new Heroku project. If you can't remember how to do this, revisit https://freecodecamp.com/challenges/get-set-for-our-back-end-development-projects.
```

Also, using "Request Header Parser Microservice" as an example (https://www.freecodecamp.com/challenges/request-header-parser-microservice), it states that the objective is:

`Objective: Build a full stack JavaScript app that is functionally similar to this: https://cryptic-ridge-9197.herokuapp.com/api/whoami/ and deploy it to Heroku.`

However, in the "Get Set for our API Development Projects" challenge it uses Cloud 9.
(https://www.freecodecamp.com/challenges/get-set-for-our-api-development-projects)

Should we be using Heroku here or C9? Should this language be updated in these challenges to direct them to C9 instead of Heroku now? If so I can make that change and submit a PR.

#### Browser Information
All

#### Screenshot

![screenshot from 2016-07-11 15 35 20](https://cloud.githubusercontent.com/assets/668910/16744032/1d1811bc-477d-11e6-9b29-2347a80661d7.png)

**Comment by atjonathan** [comment]
The broken links were already addressed in #9679. You should use c9 for coding and Heroku for deploying the app. https://github.com/FreeCodeCamp/FreeCodeCamp/issues/4436 is the issue for creating a waypoint on deploying to Heroku.
