### ISSUE TITLE
Reference to lesson "get-set-for-our-back-end-development-projects" does not exist

### ISSUE THREAD

**Issue by danyim** [FreeCodeCamp/FreeCodeCamp#9679]
Challenge [URL Shortener Microservice](https://www.freecodecamp.com/challenges/url-shortener-microservice) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

There is a link to [get-set-for-our-back-end-development-projects](https://freecodecamp.com/challenges/get-set-for-our-back-end-development-projects) on this challenge and also on several others, but it does not exist

**Comment by atjonathan** [comment]
@danyim, thanks for catching this :+1: 
**To First Timer:**
You will need to change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/api-projects.json#L163), [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/api-projects.json#L197), [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/api-projects.json#L230), [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/api-projects.json#L101) and [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/api-projects.json#L134) lines with the new link (https://www.freecodecamp.com/challenges/get-set-for-our-api-development-projects).
You will also need to change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/dynamic-web-applications.json#L194), [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/dynamic-web-applications.json#L236), [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/dynamic-web-applications.json#L272), [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/dynamic-web-applications.json#L306) and [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/dynamic-web-applications.json#L340) lines with the new link (https://www.freecodecamp.com/challenges/get-set-for-our-dynamic-web-application-projects).
Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:
