### ISSUE TITLE
grammar typo?

### ISSUE THREAD

**Issue by matthewsvm** [FreeCodeCamp/freecodecamp#968]
Challenge http://www.freecodecamp.com/challenges/bonfire-search-and-replace has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The second sentence needs a fix, I believe:  
"First argument is the sentence the perform the search and replace on."

**Comment by BerkeleyTrue** [comment]
@matthewsvm Thanks for reporting. Anyone want to tackle this one?

**Comment by 1hella** [comment]
Wasn't that already fixed? https://github.com/FreeCodeCamp/freecodecamp/pull/920

**Comment by matthewsvm** [comment]
If so, it wasn't pushed.

**Comment by LumenTeun** [comment]
This was indeed fixed in #920 and is currently in `staging` but not `production`. It should end up on the website eventually, so this issue can be closed.
