### ISSUE TITLE
Size your Images challange

### ISSUE THREAD

**Issue by alsadawy** [FreeCodeCamp/FreeCodeCamp#9682]
i write the code as following
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .smaller-image {
    width: 500px;
  }
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
 
<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
 and my browser set 
![image](https://cloud.githubusercontent.com/assets/12017930/16749426/61f65792-47ca-11e6-87d3-d0cdd2b5c938.png)

**Comment by mack318** [comment]
the image should be   { width: 100px }    not 500px as you have here

**Comment by alsadawy** [comment]
You are right , but i closed it just i saw the error

**Comment by cmhardin** [comment]
I have this exact thing typed in, but it is not taking?

**Comment by alsadawy** [comment]
when i fixed the error it worked , so please copy your code so we can take a closer look

**Comment by tgoconker** [comment]
I am with the same problem, my code is as follow

 .smaller-image { width: 100px; } 
.red-text { color: red; } 
h2 { font-family: Lobster, Monospace; } 
p {font-size: 16px; font-family: Monospace; }

Is there anything wrong in my code?

**Comment by chaddgallagher** [comment]
I'm having the same problem 
![screen shot 2016-07-26 at 7 32 59 pm](https://cloud.githubusercontent.com/assets/20567693/17159002/175b0166-5368-11e6-8af1-e47f06b1bd48.png)

**Comment by tgoconker** [comment]
You need to put your "smaller-image" inside a class element, as follow...

[image: Imagem inline 1]

Hope it helps.


Thiago Mendes

2016-07-26 20:38 GMT-03:00 chaddgallagher <notifications@github.com>:
