### ISSUE TITLE
My prior code work appears to have disappeared for mutiple exercises .... ?!?

### ISSUE THREAD

**Issue by egnosis** [FreeCodeCamp/FreeCodeCamp#9685]
In reviewing my prior work (see screen scrape below), I note that the code I had used to complete the assignments has been deleted?!?  So, if I want to review my earlier efforts, I am finding that I have to actually redo the assignments.  Is this by design?  Is there  a way to restore the coding I have completed for the first part of the FCC HTML section?!?

-Eric Garcia

(screen scrape of work I'd finished:)

Challenges Completed Last Updated Solution
Learn how Free Code Camp Works Jun 18, 2016 View this challenge
Create a GitHub Account and Join our Chat Rooms Jun 18, 2016 View this challenge
Configure your Code Portfolio Jun 18, 2016 Jul 12, 2016 View this challenge
Join a Free Code Camp Group in Your City Jun 18, 2016 Jul 12, 2016 View this challenge
Learn What to Do If You Get Stuck Jun 18, 2016 Jul 12, 2016 View this challenge
Say Hello to HTML Elements Jun 18, 2016 Jul 12, 2016 View solution
Headline with the h2 Element Jun 18, 2016 Jul 12, 2016 View solution
Inform with the Paragraph Element Jun 18, 2016 View solution
Uncomment HTML Jun 18, 2016 View solution

**Comment by raisedadead** [comment]
Hey Eric,

Can you help us with the date prior to which the challenges are not appearing on your portfolio?
I can see that the challenges that you mention above are visible on your portfolio.

https://www.freecodecamp.com/egnosis

If you recently cleared your cache and cookies then its possible that you may not see the code you submitted only in case you visit from the map page.

However if you visit the challenge via the View Solution link then you should be able to see the code.
Your solutions are never deleted from your profile.
