### ISSUE TITLE
Getting error on task list: Cannot read property 'length' of null 

### ISSUE THREAD

**Issue by neofatalist** [FreeCodeCamp/FreeCodeCamp#969]
http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements

Code used: 

  
&lt;h2>CatPhotoApp&lt;/h2>

&lt;p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.&lt;/p>

&lt;style type="text/css"&gt;
  h2{
    color: blue;
  }
&lt;/style&gt;

**Comment by BerkeleyTrue** [comment]
This is likely an issue with the tests not checking for existence. Anyone available to investigate?

**Comment by neofatalist** [comment]
It only happens if there is a space in the element after style. 

- Noel Lastrella

**Comment by 1hella** [comment]
This works fine.

```
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<style>
h2 {
  color: blue;
}
</style> 
```

You don't need `type='text/css'`, although it does work fine with it in a regular HTML file. I guess the test should be more specific?

**Comment by Ikucuk** [comment]
I might be spouting nonsense, but the issue seems to lay here:
"assert(($('style').length > 1), 'Create a <code>style</code> element.')",
if <style> != <style> but instead has a space in it (in this case followed by type='text/css')
$('style').length returns null?

**Comment by BerkeleyTrue** [comment]
This still needs to be fixed in beta. Any takers?

**Comment by QuincyLarson** [comment]
I'll take this. Thanks for reporting, @neofatalist and @lkucuk

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2677 is merged.
