### ISSUE TITLE
Confirm the Ending Instruction issue

### ISSUE THREAD

**Issue by Ollysho** [FreeCodeCamp/FreeCodeCamp#9694]
#### Challenge Name
Confirm the Ending

#### Issue Description
<img src="http://image.prntscr.com/image/c7e8c8f8a6e24808b91ae2e5cf67bea1.png">
That is what you need to do in order to pass this specific excercise, but one of the parameters is completely the opposite of what you should do. 
<img src="http://image.prntscr.com/image/7409c7bdf5614d1ba9586527c53846c0.png">

**confirmEnding("He has to give me a new name", "me") should actually return false**

#### Browser Information

I'm using the latest version of Chrome on a Windows 10 laptop

**Comment by dhcodes** [comment]
@Ollysho I believe it is correct. The target does not need to match the last whole word in the string. Therefore, "name" in the `str` does match "me" in the `target` because the last two letters of name are "me".

**Comment by Ollysho** [comment]
@dhcodes Ahh. That makes sense. My misunderstanding then.

Cheers!
