### ISSUE TITLE
Add note about translations degrading to english

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#9696]
cc/ @QuincyLarson

**Comment by QuincyLarson** [comment]
Our community has translated many of our challenges. If we don't have a translation for a challenge, it will be in English.

**Comment by Bouncey** [comment]
@QuincyLarson As per the discussion in #11469 please can you expand on the issue and what the required outcome would be

**Comment by BerkeleyTrue** [comment]
Instead of a long message i'd like to see a simple toast with a short message and a link as the call to action.

`No translation found <link>info</link>` 

We've moved away from alerts and we don't want this message to be as intrusive as an alert as it will get tiring soon.

**Comment by Bouncey** [comment]
@QuincyLarson @BerkeleyTrue, is there a consensus? Personally I like the idea of a toast, the `Alert` IMO is very intrusive on the UI.

If we got the toast route, what about `We have not yet translated this challenge into {user lang}. <link>More info</link>`

**Comment by BerkeleyTrue** [comment]
Yes, we should stick to toasts where possible.

We don't need to mention the language. 

`We have not translated this challenge yet.`

**Comment by Bouncey** [comment]
Just had a quick look over `Toasts.jsx` and it seems that the `onClick` event handler is tied into `dispatch`. 

What is the best way of doing a `target='_blank'` link to the forum through actions? Would it have to be an epic?

**Comment by BerkeleyTrue** [comment]
We'll need to change the set up to accept links

**Comment by erictleung** [comment]
Small change in the comment to make it more conversational?

> We **haven't** translated this challenge yet.

**Comment by QuincyLarson** [comment]
@erictleung yes - I agree. That reads much better and is unambiguous. I agree with @BerkeleyTrue about wanting to keep these as short as possible, and I think your copy is a good happy medium.

**Comment by Bouncey** [comment]
PR refactored to use toasts :+1:
