### ISSUE TITLE
Chalenges marked as complete but do NOT show solutions 

### ISSUE THREAD

**Issue by jlorenzo123** [FreeCodeCamp/FreeCodeCamp#9699]
#### Challenge Name
 https://www.freecodecamp.com/challenges/comparison-with-the-less-than-or-equal-to-operator  

#### Issue Description
Chalenges show green check mark, but do not show my solutions this has been a problem since the very 1st challenge to the challenge above 

#### Browser Information
FireFox ,  Chrome  (PC, Dell, Windows 10 , Latest browser version )

**Comment by Jaskaranbir** [comment]
Directly browsing from map will not show your solutions. To check your solutions, you have to open and view your profile where all your completed challenges are listed and you will have an option to view your solution too. To view your profile, just click on your profile picture thumbnail at top right corner.

**Comment by erictleung** [comment]
@jlorenzo123 what @Jaskaranbir says is correct. Go to your Free Code Camp page at `https://www.freecodecamp.com/username`, where `username` is your username for Free Code Camp. There, you'll be able to see your solutions.Let us know if that helps.

**Comment by maxmatthews** [comment]
Curious as to the reasoning behind this. Sometimes when I click on challenge in the map I've completed recently I see the solution code but other times I don't. It always works when I go to my profile, but I was wondering why it's only there sometimes in the map. Something to do with a cache?

**Comment by atjonathan** [comment]
Closing as stale.

**Comment by samsdj** [comment]
https://www.freecodecamp.com/username does not opens , can anyone help me get it my freecodecamp username
