### ISSUE TITLE
clear code function

### ISSUE THREAD

**Issue by lasergunpew** [FreeCodeCamp/FreeCodeCamp#9701]
Challenge [Headline with the h2 Element](https://www.freecodecamp.com/challenges/headline-with-the-h2-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have recently advanced to the bootstrap section but activated the clear my code button. On login again , all the previous sections code was missing. Is there any way to retrieve them. Does this mean I have to start all over again from the first exercise since my written code is lost.

My code:
```html

<h1>Hello World</h1>

```

**Comment by erictleung** [comment]
@lasergunpew don't worry, if you visit your Free Code Camp page here https://www.freecodecamp.com/lasergunpew, you can see the solutions you have submitted for each challenge you have passed. I hope that helps.

Please note that GitHub issues are for bug issues. Next time, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) or [FreeCodeCamp main room](https://gitter.im/FreeCodeCamp/FreeCodeCamp). Happy coding!
