### ISSUE TITLE
Broken link in challenge manipulating complex objects

### ISSUE THREAD

**Issue by samuelpath** [FreeCodeCamp/FreeCodeCamp#9704]
#### Challenge Name

https://www.freecodecamp.com/challenges/manipulating-complex-objects

#### Issue Description

When you click on the link labeled "JavaScript Object Notation", you get a ERR_SSL_PROTOCOL_ERROR.
In the source code, we have: "href='//json.org/'"
By default, the browser replaces "//" by "https://", but the Json.org page doesn't support SSL.
I advise to use "http://www.json.org/" instead.

#### Browser Information

* Browser Name, Version: Chrome (latest), but also reproduced with my Safari
* Operating System: Mac OS X
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```

**Comment by BKinahan** [comment]
Thanks for reporting this!

(By the way, challenges aren't numbered, so use the challenge title when referring to one instead. The 208 you see is actually your number of [brownie points](https://www.freecodecamp.com/wiki/en/brownie-points/))

**Comment by atjonathan** [comment]
**To First Timer:**
Checkout the comment from @samuelpath https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9704#issue-165242468 with details on what to change. You will need to change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4338) line. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:

**Comment by raisedadead** [comment]
@BKinahan thanks for pointing out that the nos are points and not challenge nos. The issue which we had for this has been closed by its creator, I am gonna throw it open once again.
