### ISSUE TITLE
ajuda na resolução deste desafio.

### ISSUE THREAD

**Issue by matondodomingos** [FreeCodeCamp/FreeCodeCamp#9705]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!-%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3C!-%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!-
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>
<!->
<p>Hello Paragraph</p>


```

**Comment by raisedadead** [comment]
Hi @matondodomingos 

Please visit the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help), for coding help.


Thanks.
