### ISSUE TITLE
Golf Code returns correct answer but says that I haven't passed two of the criteria (i.e. for Go Home!

### ISSUE THREAD

**Issue by lukede** [FreeCodeCamp/FreeCodeCamp#9711]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(strokes%20%3C%202)%20%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%3D%20par%20-2)%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%20par)%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%20par%2B1)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%20par%20%2B2)%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3C%20par%20%2B3)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes%20%3E%3D%20par%20%2B3)%20%7B%0A%20%20return%20%22Go%20home!%22%3B%20%20%0A%20%20%7D%0A%20%20%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%208)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes < 2) {
    return "Hole-in-one!";
  } else if (strokes <= par -2){
    return "Eagle";
  } else if (strokes < par){
    return "Birdie";
  } else if (strokes < par+1) {
    return "Par";
  } else if (strokes < par +2){
    return "Bogey";
  } else if (strokes < par +3) {
    return "Double Bogey";
  } else if (strokes >= par +3) {
  return "Go home!";  
  }
    
  
  
  // Only change code above this line
}

// Change these values to test
golfScore(5, 8);

```

**Comment by lukede** [comment]
I believe I completed the challenge, but after I click "run test" it says that I haven't completed test for par 4 7 strokes and par 5 9 strokes, even though my return displays right answer ("Go Home!).

**Comment by Bouncey** [comment]
@lukede your code is almost there. 

Make sure your output matches exactly what is required from the instructions.

**Comment by lukede** [comment]
Oh, OK. Thanks for the tip

**Comment by lukede** [comment]
Jeez, I found it! My "H" in "Go Home!" wasn't capitalized :)

**Comment by erictleung** [comment]
Closing as issue appears resolved. Happy coding!
