### ISSUE TITLE
Incorrect test "Use the + operator to build myStr" is actually testing against "ourStr" not "myStr"

### ISSUE THREAD

**Issue by metasean** [FreeCodeCamp/FreeCodeCamp#9717]
#### Challenge Name
Concatenating Strings with Plus Operator

#### Issue Description

My complete answer (after refactoring out unused code and comments), is:
``` javascript
var myStr = "This is the start. " + "This is the end.";
```
Which triggers a fail for the test:
```
Use the + operator to build myStr
```
Interestingly, adding back in the example code *and* commenting it out:
``` javascript
// var ourStr = "I come first. " + "I come second.";
```
Will result in the same test passing, while removing the "+" from that commented out example, i.e.:
``` javascript
// var ourStr = "I come first. "  "I come second.";
```
will fail.

So the test:
```
Use the + operator to build myStr
```
Looks like it's actually testing against the example **`ourStr`** and  *not* against the camper's **`myStr`**.

**Comment by erictleung** [comment]
@metasean thanks for the issue. However, that particular test checks for the number of `+` signs. Within the editor, it mentions to `Only change code below this line`. Changing the lines above it will create unintended consequences. So the test isn't actually testing against the example `outStr`. Although inconvenient, this isn't a bug per se so I'll be closing this issue. 

If you get stuck with a challenge or have any initial questions, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
