### ISSUE TITLE
Unable to go to my next challenge

### ISSUE THREAD

**Issue by palango7** [FreeCodeCamp/freecodecamp#972]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I try CTRL + enter or click on that green button and nothing happens.

**Comment by terakilobyte** [comment]
I'm unable to reproduce this issue after adding the required styling to the h2 element. Please confirm if this is still an issue.
