### ISSUE TITLE
Turn an Image into a Link. I ma sure is correct, but I couldnt move forward. 

### ISSUE THREAD

**Issue by lubodrinka** [FreeCodeCamp/FreeCodeCamp#9721]
Challenge [Turn an Image into a Link](https://www.freecodecamp.com/challenges/turn-an-image-into-a-link#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%20%3Cimg%20class%3Dthick-green-border%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"> <img class=thick-green-border src="https://bit.ly/fcc-relaxing-cat"></a>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
The output alarm> Nest the existing img element within an a element.

**Comment by raisedadead** [comment]
@lubodrinka thanks for reporting, but your code is not correct, you are not supposed to modify the class attribute of the `<img>` element.

/cc @FreeCodeCamp/issue-moderators  
Should we add a test for checking that campers do not modify the existing element? I may have seen this a couple of times in the chat as well.

**Comment by raisedadead** [comment]
@FreeCodeCamp/issue-moderators: Please close if deemed unecessary.

**Comment by lubodrinka** [comment]
I follow the instructions, I put a element to existing img! There was <img> modified from previous lesson.
But what now? I cannot move forward.

**Comment by raisedadead** [comment]
I am afraid the code in the previous challenge and in this challenge was:

`<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">`

Did you happen to modify it by any chance? Did you happen to code this on some other application (notepad, etc) and copied it later to the page, leading to an accidental change?

**Comment by lubodrinka** [comment]
after it did not work at first because I misspelled a/ instead /a  I cut and paste from another line. after one And there was no attention I cant do that.
wait how you coded that? You put in session  number of line and text?

**Comment by lubodrinka** [comment]
finally I paste smaller-image into, but I try previous lesson. is there possibility to cross session?

**Comment by erictleung** [comment]
@raisedadead I'm fine with adding an additional test to check for modifications to the existing element.

**Comment by lubodrinka** [comment]
I notice on other practices the sites code change what I wrote before. The comparison could be wrong.
previous lesson end <img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
and next lesson start <img class=thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

**Comment by raisedadead** [comment]
@lubodrinka the code on the current lesson is **not** `<img class=thick-green-border" src="https://bit.ly/fcc-relaxing-cat">`

Please use the reset button to check.

**Comment by lubodrinka** [comment]
You must something changed, because now there is smaller-image without reset.

**Comment by infotech7777** [comment]
I also have a problem with this part .I am also sure i have do it right.
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back . "></a>
this is part of my code including the link of the photo given to a previous part and the solution of the part needed in the "turn an image into a link" part

**Comment by dwd2010** [comment]
@infotech7777, you could go to the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by SasukeUchiha619** [comment]
How to resize the image?

**Comment by SasukeUchiha619** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  smaller-image {
    width: 100px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by texas2010** [comment]
@SasukeUchiha619, Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
