### ISSUE TITLE
set the font-family

### ISSUE THREAD

**Issue by Radeztky** [FreeCodeCamp/FreeCodeCamp#9722]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by Sprinting** [comment]
Uhh, where's the code?

**Comment by raisedadead** [comment]
Please refer [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Report-Bugs).
