### ISSUE TITLE
Better syntax example...

### ISSUE THREAD

**Issue by Absailnit** [FreeCodeCamp/FreeCodeCamp#9723]
The syntax issue in this code example doesnt work within the way it is presented to the pupil. I had to manipulate the syntax in order for the code to be accepted fortunately I have prior knowledge in Java and python to manipulate the parentheses but to someone starting to code this would take a very long time to come to an understanding of how and where to put the parentheses. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by raisedadead** [comment]
> The syntax issue in this code example doesnt work within the way it is presented to the pupil.

@Absailnit which code sample? Which challenge are we talking about?
P.S: Follow [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Report-Bugs) while reporting issues.

**Comment by Absailnit** [comment]
The tutorial "Introducing Else If Statements.. example doesnt include the closing brackets to the function statements.. Those unfamiliar with syntax and how to close these statements are going to be experiencing some hinderance on this tutorial. The next few examples dealing with else if tutorials include these to close.  I have included my screenshot so that you can see from the example to the code the missing closing bracket in the example.`
![image](https://cloud.githubusercontent.com/assets/19542340/16846856/10e0763c-49bc-11e6-973f-e81fff72c770.png)
`

**Comment by erictleung** [comment]
@Absailnit the example code given is correct JavaScript. It doesn't need any closing brackets, unless you write a complete function, which it is not intended to be in this case.

Functions were introduced in [Write Reusable JavaScript Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions), which was about 20 challenges before the "Introducing Else If Statements." So writing functions at this point in the curriculum (unless the learner jumped around) should not be too difficult.

The editor is set up to check for these missing brackets so even if a learner doesn't catch them, the editor will show errors.

![image](https://cloud.githubusercontent.com/assets/2754821/16848947/0d68c964-49ad-11e6-9cc5-bd31992fd25b.png)

**Comment by Absailnit** [comment]
Eric Thank you for your candid response! Must have neglected to pay
attention to those brackets... 20 lessons ago with the gobs of codes. I
will Google from here out.

**Comment by raisedadead** [comment]
Closing, as resolved.

Thanks @Absailnit and happy coding!
