### ISSUE TITLE
Challenges/no-repeats-please needs more tests

### ISSUE THREAD

**Issue by pnahratow** [FreeCodeCamp/FreeCodeCamp#9727]
#### Challenge Name

No Repeats Please
https://www.freecodecamp.com/challenges/no-repeats-please
#### Issue Description

I've just passed https://www.freecodecamp.com/challenges/no-repeats-please but I was in the middle of doing some trial and error. I was happy at first but I wanted more tests. So I went to other people's solutions and calculated some more values. Some of which chrashed my browser and some didn't deliver the same result as my code.

I assume my code is wrong and just works for the limited amount of test cases.
I'd wish for more tests where the number of repeating characters is > 2 and the result is > 0 since there is only one of this.
#### Browser Information

- Browser Name, Version: Google Chrome Version 50.0.2661.102 (64-bit)
- Operating System: Debian GNU/Linux 8.5
- Mobile, Desktop, or Tablet: Desktop
#### Your Code

``` js
 /**
* n!
*/
var f = [];
function factorial (n) {
  if (n === 0 || n === 1) {
    return 1;
  }

  if (f[n] > 0) {
    return f[n];
  }

  f[n] = factorial(n-1) * n;
  return f[n];
}

/**
* Creates an array of numbers about the multiple occurences of identical chars in string
* "aaabbcdef" => [3,2]
*/
function getKs(str) {
  var ks = [];
  var sortedStr = str.split('').sort();
  var current;

  while (sortedStr.length > 0) {
    var value = sortedStr.pop();
    if(value == current) {
      ks[ks.length-1]++;
    } else {
      current = value;
      ks.push(1);
    }
  }
  return ks.filter(function(item) {
    return item>1;
  });
}

/**
* Based on http://stackoverflow.com/a/36178855
*
* Solution for char repetitions of max 2 is perfectly working. The idea is to assume
* a doubled char as a single character in a string with length n-1 thus generating the number
* of permutations we consider invalid.
*
* When char repitiions are > 2 we recurse and add with lower k values [3,2,2] => [2]
* The calculation problem probably happens when calculating the overlaps in this case.
*/
function invalidPerms(n,ks) {
  var result = 0;

  // if repititons are more than 2 recurse with lower ks
  if(Math.max.apply(null,ks) > 2){
    result += invalidPerms(n,ks.filter(function(item){
      return item>2;
    }).map(function(item){
      return item-1;
    }));  
  }  

  // calc perms of compound occurence in n-k+1 length
  ks.forEach(function(k){
    result += factorial(n-k+1)*factorial(k);
  });

  // remove overlaps
  if (ks.length > 1) {
    result -= ks.reduce(function(p,c) {
        return p* factorial(c);
    },factorial(n-ks.reduce(function(p,c){
      return p + c - 1;
    },0)));
  }

  return result;  
}

function permAlone(str) {  
  var n = str.length;
  var ks = getKs(str);

  var result = factorial(n) - invalidPerms(n,ks);  
  return result > 0 ? result : 0;
}

permAlone('aabbccdefg');
```

**Comment by raisedadead** [comment]
We can certainly add more tests, but the question is we must maintain a balance between the target audience as well.

/cc @FreeCodeCamp/issue-moderators

**Comment by erictleung** [comment]
@raisedadead considering "No Repeats Please" is in the advanced algorithm challenges, I think having good tests for these challenges is good. However, this challenge isn't a required one for getting a certification so not sure how much effort we should put into coming up with new tests. 

All in all, I'm all for better tests that cover the scope of the challenge.

**Comment by pnahratow** [comment]
@raisedadead
I'm not sure what "balance between the target audience" means but I can only assume it is about crashing browsers with large strings. In that case strings with lengths <= 8 should already do the trick.

Like these ones

```
aaabcdef  // triple occurence with more room
aaaabcde  // quadruple occurence
aaabbbcd  // triple occurence twice
aaabbcd   // triple mixed with a double occurence. like "aaabb" but with more room
```

**Comment by raisedadead** [comment]
@pahlsson apologies, should have clarified. The intent here is that we could add more tests, but we must keep in mind that this challenge being one of the non-mandatory challenges should not be very tough for campers who are learning and may find this a bit too difficult.

Nevertheless, like Eric in the previous comment I am up for expanding the tests a little bit more.

**Comment by QuincyLarson** [comment]
Since no one has explicitly proposed any new tests that I know of and it's been 6 months, I'm closing this issue.

**Comment by dionisos2** [comment]
Like @pnahratow i also needed more tests to test my [permAlone function](https://gist.github.com/dionisos2/8dd9f18c0a299265f25f99ad961e8ccf).
I think these tests would be good (don’t saturate the browser when we are using brute force, but still permit to deal with more complex solutions) :
```
permAlone("aaabcdef") = 14400  // triple occurence with more room
permAlone("aaaabcde") = 2880  // quadruple occurence
permAlone("aaabbbcd") = 6624// triple occurence twice
permAlone("aaabbcd") = 1152   // triple mixed with a double occurence. like "aaabb" but with more room
permAlone("aaabbcce") = 9216 // triple + double + double
```
