### ISSUE TITLE
"Import a Google Font" bug, and, apparently, this issue tracker's issue template markdown

### ISSUE THREAD

**Issue by rahlzel** [FreeCodeCamp/FreeCodeCamp#9729]
#### Challenge Name

https://www.freecodecamp.com/challenges/import-a-google-font

#### Issue Description

The left sidebar text says "Now you can set Lobster as a font-family value on your h2 element", yet there is no h2 section in the `<style>` above, and there are no checkboxes in the bottom that explain that it needs to be added, or that it can be done by adding an inline `style="font-family: Lobster;"` to the h2 element. This is fairly elementary for experienced HTML users, but anyone actually new to coding would likely stop at this challenge for longer than intended. It's easy to tell that this isn't intended because in the very next challenge the steps are laid out for the user.

#### Browser Information

* Browser Name, Version: Chrome v51
* Operating System: Windows 7 64bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
 <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>
<h2 class="red-text" style="font-family: Lobster;">CatPhotoApp</h2>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

#### Screenshot

http://i.imgur.com/YyhcAjN.png

Wow. What the hell is wrong with the issue template markdown? Here's my source: http://i.imgur.com/5QuNoGI.png

**Comment by dwd2010** [comment]
@rahlzel 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by rahlzel** [comment]
This issue IS about the website...

**Comment by dwd2010** [comment]
@rahlzel, oh ok. do you mean this challenge need to explain more?

**Comment by rahlzel** [comment]
Yes. Every other challenge before and the one immediately after it literally tells the person what to type and what the code should look like. This is the only challenge (so far) that forces the user to remember what they did several challenges ago and to try to repeat it without any advice on how to do so, which makes this particular section very challenging compared to the ones around it. It's good that the questions become increasingly challenging because that's how you learn, but this one takes a sudden node-dive in difficulty and it's very obviously not intentional.

If you read my issue or look at my screenshot, or just click on the challenge link, you'll see that the challenge does not have an `<h2>` element in the `<style>` header, so the person needs to create one, but the tips in the sidebar don't mention this. Nor do they mention that they might need to create an inline style in order to achieve the same result.

**Comment by erictleung** [comment]
@rahlzel thanks for the feedback.

Maybe the challenge could be rewritten like so:

> ...
> 
> First, you'll need to make a `call` to Google to grab the `Lobster` font and load it into your HTML.
> 
> Copy the following code snippet and paste it into the top of your code editor:
> 
> `<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">`
> 
> Remember, to add a font family to an element, you'll need to create a CSS rule.
> 
> ```html
> h2 {
>   font-family: Sans-serif;
> }
> ```
> 
> Create a CSS rule for the the `font-family` of `Lobster` and apply this new font to your `h2` element.

Also, can you elaborate on your comment on something wrong with the issue template? I don't know what you're pointing at in that image.

**Comment by dwd2010** [comment]
@erictleung, I forget to mention about I did fix that person issue template.  rahlzel write style in code.  so i have to add backtick on that.   that is how it got mess up first place

**Comment by didong27** [comment]
thank you soooo......much!

**Comment by GepettoB** [comment]
Yes. Thank you for this!
