### ISSUE TITLE
This is in order, right?

### ISSUE THREAD

**Issue by najaelfil** [FreeCodeCamp/FreeCodeCamp#9732]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%0A%3C!--h1%3EHello%20World%3C%2Fh1--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp--%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html


<!--h1>Hello World</h1-->

<h2>CatPhotoApp</h2>

<!--p>Hello Paragraph</p-->


```

**Comment by dagadego** [comment]
<h2>CatPhotoApp</h2>

**Comment by raisedadead** [comment]
Please refer [Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Report-Bugs) and head on to the chat please.
