### ISSUE TITLE
I CANT SKIP TESTS , IN CONSOLE I GET RIGHT ANSWER

### ISSUE THREAD

**Issue by andybmx20** [FreeCodeCamp/FreeCodeCamp#9733]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncate(str, num) {
  
  if (str.length <= num) {
    return str;
  } else if (num <= 3){
    return str.slice(0, num) + '...';
  } else {
    
    return str.slice(0, num - 3) + '...';
  }    
}

truncate("Absolutely Longer", 2);
```

**Comment by raisedadead** [comment]
You have modified the function name, or you have a solution that was before this challenge editor code was renamed in changes to the challenges.

`truncate > truncateString`

Hitting the reset button should give you the correct starter code.
Please consult [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).
