### ISSUE TITLE
Progress Visualization for clean UX experience

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9735]
For a user, who visits the website (initial loads on a fresh device), certain UI elements take a while to populate.

Example:
1. Login, the profile image takes a couple of seconds to appear on the navbar
2. The map aside takes a couple of seconds to populate and displays "No Superblocks" 
3. Challenges views at times take a second to render.

Although these happen seamlessly from the next interaction with the elements. Hence we might as well think of having some form of progress to present the blocking nature of the UI.

**Comment by BerkeleyTrue** [comment]
Excellent idea!

**Comment by atjonathan** [comment]
@raisedadead 👌

**Comment by BerkeleyTrue** [comment]
> Challenges views at times take a second to render.

@raisedadead Can you clarify this? Initial page load is done server side so there shouldn't be any delay in the page rendering.

**Comment by raisedadead** [comment]
> Challenges views at times take a second to render.

Sure, when we were testing this in the beta, the challenge transitions were not smooth. Any challenge, if they were loading the first time used to take 1 second or so to load.

Steps were:

1. Visit a challenge from the map.
2. Solve, click submit.
3. Next challenge loads (<--- with some delay).

I am not sure if this is the case anymore. I haven't seen any delays even for the map on my local setup, however, if the beta is still up with the latest deploy, I could check if this is still reproducible.

**Comment by BerkeleyTrue** [comment]
@raisedadead I see. That seems to be different issue then this one here. That might be an actual bug as there isn't any reason why the next challenge should see a delay.

**Comment by raisedadead** [comment]
@BerkeleyTrue yup. I agree. We could just keep this aside unless something comes up. 
Yes, the only loading delay is currently:
> Login, the profile image takes a couple of seconds to appear on the navbar

**Comment by Bouncey** [comment]
Following on from #11611 

I have just used `console.time` to confirm what you said by putting `.delay(15000)` after `.retry(3)`.

I'll see if I can track down the block.

**Comment by BerkeleyTrue** [comment]
I'd still like to see some interface preview for codemirror, something similar to what FaceBook use to do. 

http://www.callumhart.com/blog/non-blocking-uis-with-interface-previews

**Comment by raisedadead** [comment]
Wow! That's such an excellent read. Thanks for the share Berkeley.
