### ISSUE TITLE
[beta] feature: challenge can declare libraries it requires

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9736]
The absence of Bootstrap means a lot of the HTML/CSS/jQuery challenges  do not make sense.

**Comment by BerkeleyTrue** [comment]
Nice catch! Definitely needs to be fixed before merging

**Comment by BerkeleyTrue** [comment]
Done! Now a challenge or a challenge block can declare an array of files it requires to be pulled down using ajax!

**Comment by BerkeleyTrue** [comment]
Live on beta!
