### ISSUE TITLE
this is not working.  i believed its correct. function myLocalScope() {   var myVar = 'use strict';         console.log(myVar); }  myLocalScope();

### ISSUE THREAD

**Issue by gari3d** [FreeCodeCamp/FreeCodeCamp#9739]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0A%0Afunction%20myLocalScope()%20%7B%0A%20%20var%20myVar%20%3D%20'use%20strict'%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0A%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


function myLocalScope() {
  var myVar = 'use strict';
  
  
  console.log(myVar);
}

myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope


// Now remove the console log line to pass the test


```

**Comment by erictleung** [comment]
@gari3d thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
