### ISSUE TITLE
Beta test: Unable to register new account

### ISSUE THREAD

**Issue by katiequin335** [FreeCodeCamp/freecodecamp#974]
When registering a new account using my email address, I get this error after hitting submit:
![loginissue](https://cloud.githubusercontent.com/assets/8561539/8239591/cd983610-15ca-11e5-83da-d3ac39291572.png)
{"error":{"name":"Error","status":500,"message":"Timeout in connecting after 5000 ms"}}

Ubuntu 14.04, Chrome browser

**Comment by BerkeleyTrue** [comment]
Not sure if this is the same as #971 so I am going to keep this open for now.

**Comment by BerkeleyTrue** [comment]
Looks like this issue might of be resolved with https://github.com/FreeCodeCamp/freecodecamp/commit/28f346e830bccdab7e0332f438f9724b8adf7c00
I will keep an I on this to see if it rears its head again! Thanks for your help!
