### ISSUE TITLE
plz help me

### ISSUE THREAD

**Issue by tanayu** [FreeCodeCamp/FreeCodeCamp#9741]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by qmikew1** [comment]
It doesn't appear you've attempted to solve the challenge. Issues are for reporting bugs related to site and not for code assistance. You may want to use the [help room](https://gitter.im/FreeCodeCamp/HelpJavaScript)

**Comment by erictleung** [comment]
@tanayu thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
