### ISSUE TITLE
it is still issue??? :\  

### ISSUE THREAD

**Issue by gari3d** [FreeCodeCamp/FreeCodeCamp#9743]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5CnSecondLine%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\nSecondLine\rThirdLine"; // Change this line



```

**Comment by erictleung** [comment]
@gari3d thanks for the issue but if you get stuck with a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: please look at the instructions again. Your string doesn't match the required string. It should look like this when you print it out:

```
FirstLine
\SecondLine\
ThirdLine
```

Happy coding!
