### ISSUE TITLE
nextInLine text needs code tags

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9744]
#### Challenge Name

https://www.freecodecamp.com/challenges/stand-in-line

#### Issue Description

The last sentence in this challenge needs `nextInLine` in code tags to be consistent.

#### To Contributors

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/3434918d00f241d601abf8e6d865a2ced9dce563/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2506) needs to be changed so the last sentence is:

```
The <code>nextInLine</code> function should then return the element that was removed.
```

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/16883824/ede9161a-4a7a-11e6-8a76-8dc91728ef99.png)

**Comment by mnttnm** [comment]
I am working on this. Changing the code as mentioned above.
