### ISSUE TITLE
Broken IMG link (BootStrap Grid)

### ISSUE THREAD

**Issue by haunja** [FreeCodeCamp/FreeCodeCamp#9745]
#### Challenge Name
https://www.freecodecamp.com/challenges/use-the-bootstrap-grid-to-put-elements-side-by-side

#### Issue Description
Broken image link on page for image of BootStrap Grid example.  No image on page and link is dead. 

#### Browser Information
Chrome Version 51.0.2704.106 m
Firefox 47.0.1
Windows 7 64
Laptop with 8gig ram. 

#### Screenshot

![brokenlink](https://cloud.githubusercontent.com/assets/5329973/16884128/8f354f9c-4a95-11e6-9571-ba533ed63303.PNG)

**Comment by dwd2010** [comment]
Odd, I could see that picture of grid system at that challenge.

**Comment by erictleung** [comment]
@haunja thanks for the issue. The image shows up for me.

![image](https://cloud.githubusercontent.com/assets/2754821/16884288/6c7d9346-4a7d-11e6-9365-c88ede83e18d.png)

**Comment by qmikew1** [comment]
Image also shows for me

**Comment by haunja** [comment]
Thanks for the feedback. It looks like it only an issue from me work machine. Probably a corporate firewall setting. Works fine on my home PC.
