### ISSUE TITLE
Text Editor Issue

### ISSUE THREAD

**Issue by davedd233** [FreeCodeCamp/FreeCodeCamp#9746]
#### Challenge Name

Call out Optional Actions with Button Info

#### Issue Description

Whenever I complete a challenge and go on to the next one, I am unable to click the cursor where I want within the text editor. Once I hit enter, I can click and have the cursor go where I want it to go. 

#### Browser Information

* Browser Name, Version: Google Chrome Version 51.0.2704.103 m (64-bit)

* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```

**Comment by erictleung** [comment]
@davedd233 thanks for the issue. This is a known issue #7847. Please read the comments there for work-arounds to the issue. Happy coding!
