### ISSUE TITLE
Beta Test: diff two arrays shows dashed title

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#975]
Challenge http://www.freecodecamp.org/challenges/Bonfire: Diff Two Arrays has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Shows dashed title
![bonfire-diff-two-arrays___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/8240682/5cb078a6-15b9-11e5-9641-48937bcd1c1c.png)

**Comment by turtleman95** [comment]
This also shows up in the Map.
![image](https://cloud.githubusercontent.com/assets/12956806/8242045/e0870b92-15da-11e5-8380-e44a0f131ce0.png)
