### ISSUE TITLE
Use Responsive Design with Bootstrap Fluid Containers needs slight rewrite

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9757]
Challenge [Use Responsive Design with Bootstrap Fluid Containers](https://www.freecodecamp.com/challenges/use-responsive-design-with-bootstrap-fluid-containers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.

The instruction

> You can add Bootstrap to any app just **by including it by adding** the following code to the top of your HTML:

is kind of redundant. We can simplify it by editing it as

> You can add Bootstrap to any app by adding the following code to the top of your HTML:

[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/ece31687fa610bc51ffad016082845b87a04408d/seed/challenges/01-front-end-development-certification/bootstrap.json#L14) needs to be changed.

To contributors, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled as `first-timers-only` so only individuals who have not contributed to the main Free Code Camp repository can fix this issue. Thank you.

**Comment by Kallaway** [comment]
I will take this one if you don't mind!

**Comment by erictleung** [comment]
@Kallaway go for it!
