### ISSUE TITLE
Beta Test: Phone element on HTML and CSS Waypoints crossing over the footer.

### ISSUE THREAD

**Issue by silentfox91** [FreeCodeCamp/freecodecamp#976]
When scrolling down the phone is in a fixed position and crosses over the footer.
![waypoint make dead links using the hash symbol free code camp - mozilla firefox_002](https://cloud.githubusercontent.com/assets/10661000/8240838/688408de-15fd-11e5-9079-ad97a45ef029.png)

**Comment by BerkeleyTrue** [comment]
@silentfox91 Thanks!

**Comment by BerkeleyTrue** [comment]
Can't reproduce. Are you still seeing this @silentfox91 ?

**Comment by silentfox91** [comment]
I'm still see it, I'm using Firefox for Ubuntu canonical 1.0 and I'm seeing it on Chrome as well.

I have checked another computer and the issue isn't there. The two major differences is age and screen size (mine is a few months old & 13" while the other is a good five years old and 15")

**Comment by benmcmahon100** [comment]
potential fix for this issue https://github.com/FreeCodeCamp/freecodecamp/pull/1152
