### ISSUE TITLE
Add Font Awesome Icons to our Buttons run tests doesn't work in IE

### ISSUE THREAD

**Issue by rsponholtz** [FreeCodeCamp/FreeCodeCamp#9762]
#### Challenge Name

Add Font Awesome Icons to our Buttons 

#### Issue Description

"Run Tests" does not work properly in IE 11.  the exact same code worked and passed the test in Chrome.

#### Browser Information

* Browser Name, Version: 
IE 11
![capture](https://cloud.githubusercontent.com/assets/1828699/16901430/18148d04-4c09-11e6-96f8-54a0227d251a.PNG)

* Operating System: 
windows 10
* Mobile, Desktop, or Tablet: 
Tablet (surface pro 4)
#### Your Code

       <button class="btn btn-block btn-info"><i class="fa fa-thumbs-up"></i>Like</button>

#### Screenshot

![error](https://cloud.githubusercontent.com/assets/1828699/16901419/d68d501e-4c08-11e6-8765-cbde3d756be4.png)

**Comment by erictleung** [comment]
@rsponholtz thanks for the issue. I don't have a Windows 10 machine to try and replicate this

cc/ @FreeCodeCamp/issue-moderators do any of you have a Windows 10 machine to replicate this issue?

**Comment by dwd2010** [comment]
I thought window 10 dont have IE.  that is odd to me now.

**Comment by alayek** [comment]
@erictleung I have Windows 10. I am trying to reproduce this issue in IE11.

**Comment by alayek** [comment]
@erictleung I ran a test on this issue in my IE11 on Windows 11. Here are my observations:

- Clicking the _Rub Test_ button triggers the tests. 
- Hitting <kbd>Ctrl</kbd> + <kbd>Enter</kbd> also triggers the test, but only if the code-mirror text editor is in focus. The key combination **doesn't** run the tests if the editor is not in focus, i.e., you have to click somewhere within the editor before hitting the keys.

Here's my screenshot:

![ie](https://cloud.githubusercontent.com/assets/5607371/16902581/ebfda610-4c80-11e6-894f-c773945bbcc5.png)

**Comment by erictleung** [comment]
@alayek thanks for checking this! 👍 

@rsponholtz please checkout @alayek's post above and see if that solves your issue. Update us if that doesn't resolve the issue. Thanks!

**Comment by erictleung** [comment]
@rsponholtz closing this issue as it has become stale. Please take a look at the suggestions above to see if that resolves your issue. Otherwise, please update us on this issue and we can work from there. Happy coding!

**Comment by MuhammadLaraib** [comment]
@erictleung i have a same problem, i want to see your code:
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons#?solution=%3Clink%20rel%3D%22stylesheet%22%20href%3D%22%2F%2Fmaxcdn.bootstrapcdn.com%2Ffont-awesome%2F4.5.0%2Fcss%2Ffont-awesome.min.css%22%2F%3E%0A%3Cstyle%3E%0A%0A%3C%2Fstyle%3E%0A%0A%3Cbutton%3E%3Ci%20class%3D%22fa%20fa-thumbs-up%22%3Elike%3C%2Fi%3E%3C%2Fbutton%3E

**Comment by erictleung** [comment]
@MuhammadLaraib your code is incorrect. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: you're missing classes for your `button` element and the text "Like" should be in your button and not your `i` element. Happy coding!

**Comment by MuhammadLaraib** [comment]
@erictleung My Code don't work...
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons#?solution=%3Clink%20rel%3D%22stylesheet%22%20href%3D%22%2F%2Fmaxcdn.bootstrapcdn.com%2Ffont-awesome%2F4.5.0%2Fcss%2Ffont-awesome.min.css%22%2F%3E%0A%3Cstyle%3E%0A%0A%3C%2Fstyle%3E%0A%3Cbutton%20class%3D%22btn%20btn-block%20btn-info%22%3E%3Ci%20class%3D%22fa%20fa-thumbs-up%22%3E%3C%2Fi%3E%20Like%20%3C%2Fbutton%3E
![capture](https://cloud.githubusercontent.com/assets/20684314/17277191/1bed7b7c-5756-11e6-8ff8-59e4a7ffe89c.JPG)

**Comment by MuhammadLaraib** [comment]
add a "btn-primary" class to button element, then its works
![capture](https://cloud.githubusercontent.com/assets/20684314/17277374/ba89fa68-575a-11e6-812a-ecfcea9ac98e.JPG)
