### ISSUE TITLE
Escape Sequences in Strings - Free Code Camp (FCC)

### ISSUE THREAD

**Issue by naveenlb** [FreeCodeCamp/FreeCodeCamp#9764]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FirstLine%5Cn%20%5C%5CSecondLine%5C%5C%20%5CrThirdline%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Question : [
![error](https://cloud.githubusercontent.com/assets/20254866/16902130/44ef0baa-4c73-11e6-9317-02cf7573829b.jpg)
]

My code:
var myStr="FirstLine\n \\SecondLine\\ \rThirdline";

```

**Comment by naveenlb** [comment]
![error2](https://cloud.githubusercontent.com/assets/20254866/16902145/ae5d5af6-4c73-11e6-94bc-d12ce889b1e9.jpg)

**Comment by BKinahan** [comment]
Note that the instructions indicate there should not be any spaces in your string, and pay attention to capitalization.

Please seek coding assistance in the [Help chat](https://gitter.im/FreeCodeCamp/Help). Issues are for problems with the challenges or website.

Happy coding!

**Comment by erictleung** [comment]
@naveenlb thanks for the issue but as @BKinahan has pointed out, you need to pay attention to capitalization and spacing. Closing as not an issue with the site. Happy coding!

**Comment by malixi** [comment]
This is my version but it's not working on me 

var myStr = "FirstLine\\\nSecondLine\rThirdLine\\";

**Comment by BEBEDYDY** [comment]
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line
here you go.

**Comment by BEBEDYDY** [comment]
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line
here you go.

**Comment by BEBEDYDY** [comment]
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line
 for some reason,  browsers hide the \\
so:
var myStr ="FirstLine\n\\\SecondLine\\\\rThirdLine"; // Change this line

**Comment by makleriux** [comment]
logical is have to be like this, becouse if dont leave spaces at words JS escaping the word or only first letter? i cant get it done.
var myStr = "FirstLine \n \\ SecondLine \\ \r ThirdLine"; // Change this line

**Comment by kim3z** [comment]
I got it! The key is to not use any spaces.

Solution: var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line

**Comment by Muhsin2016** [comment]
Hi after I tried differnt ways this is how this code works

var myStr = "FristLine\n\\SecondLine\\\rThirdLine";

**Comment by Muhsin2016** [comment]
sorry, it has two backslashs before second and \r after the two backlashs of second;
var myStr = "FristLine\n\\SecondLine\\\rThirdLine";

**Comment by Muhsin2016** [comment]
var myStr = "FirstLine\n\\secondLine\\\rThirdLine";

**Comment by Muhsin2016** [comment]
some how when I post my code is not showing the right way again there are \\ before the secondand \\ 
\r before the third

**Comment by texas2010** [comment]
@Muhsin2016 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by Shashi-Bhardwaj** [comment]
"FirstLine\n\\SecondLine\\\rThirdLine";    (try this)

**Comment by Shashi-Bhardwaj** [comment]
"FirstLine\n\\SecondLine\\\rThirdLine";    (try this)

**Comment by nadeemkhan** [comment]
try this it worked for me var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line

**Comment by BrewBaby** [comment]
'FirstLine\n\\SecondLine\\\rThirdLine';

no spaces and pay attention to caps

**Comment by atuljha23** [comment]
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

this will work ! :)
