### ISSUE TITLE
The forums are down

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#9765]
#### Challenge Name
NA

#### Issue Description
For the past several days, the forums have been experiencing two issues.

Either the forum is down entirely "Failed to load resource: the server responded with a status of 500 (Internal Server Error)".

Or, the forum will display posts, however attempting to post a reply will error out with a 500 internal server error.

#### Browser Information

* Browser Name, Version: Chrome and Firefox (all latest version). PaleMoon (Arch only) 
* Operating System: MacOS, Ubuntu Linux 16.04, Arch Linux (current)
* Mobile, Desktop, or Tablet: Desktop and Laptop

#### Screenshot
![screen shot 2016-07-17 at 2 30 51 pm](https://cloud.githubusercontent.com/assets/322175/16902654/43fe3876-4c2b-11e6-8860-aa07a078e60f.png)

**Comment by dwd2010** [comment]
@P1xt, is it happened right now?  I checked on forum. I could enter it. it is fine to me right now.  I know forum was down few times.

**Comment by P1xt** [comment]
Right now, for me - 
![screen shot 2016-07-17 at 2 44 54 pm](https://cloud.githubusercontent.com/assets/322175/16902734/29d6904a-4c2d-11e6-91f9-61776cc44e96.png)

**Comment by P1xt** [comment]
The forums is back up to the state where you can "see" the forums - but that's what I get when I try to post.

Both issues have been happening A LOT the past three days.

**Comment by P1xt** [comment]
The forums is back up now, and I can post replies. However, unless something specific was done to "fix" it - there's some systemic issue here because they've been up and down repeatedly and frequently over the past three days.

**Comment by BerkeleyTrue** [comment]
@P1xt Thanks for opening up the issue. However, this is not specifically actionable here. 

In the future open forum issue's there. https://github.com/FreeCodeCamp/discourse/

I've gone ahead and done that now. see https://github.com/FreeCodeCamp/discourse/issues/35

Happy Coding

**Comment by P1xt** [comment]
Sorry 'bout that, I wasn't even aware there was a repo for the discourse
stuff and didn't expect there'd be one as there's no real code you'd be
needing to track changes for on a standard discourse install. I'll take
more care to check FCC's repo list before bug reporting next time.

On Sun, Jul 17, 2016 at 5:13 PM, Berkeley Martinez <notifications@github.com

**Comment by alayek** [comment]
@P1xt the discourse repo is to have a place to consolidate the issues campers are facing on the forum. To be clear, we don't modify anything in the discourse source code. If such a situation arises, our Forum mods reach out to Discourse support team.

**Comment by davidk350** [comment]
Thanks for sharing this nice information.

**Comment by davidk350** [comment]
The exercises are almost all copy-pasta. I like the projects and the challenges, but the learning exercises are almost a waste of time in my opinion. They tell you how to do something and then make you do it yourself, but the answer is almost always basically given. This makes it easy to breeze through exercises without learning anything.  [Asus live chat](https://www.asussupportnumber.com/asus-customer-support/)
