### ISSUE TITLE
Missing semi-colon for valid JS

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#9768]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

## Description

The sample code is missing a semi-colon.

## How to Fix

[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/75bba05718dc0bb288beafb154ecc4b0181e8d64/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4397) needs to be edited so that there is a semi-colon in the correct place. The edits you make in your code should be from the red to the green:

```diff
- "<blockquote>var ourStorage = {<br>  \"desk\": {<br>    \"drawer\": \"stapler\"<br>  },<br>  \"cabinet\": {<br>    \"top drawer\": { <br>      \"folder1\": \"a file\",<br>      \"folder2\": \"secrets\"<br>    },<br>    \"bottom drawer\": \"soda\"<br>  }<br>}<br>ourStorage.cabinet[\"top drawer\"].folder2;  // \"secrets\"<br>ourStorage.desk.drawer; // \"stapler\"</blockquote>",
+ "<blockquote>var ourStorage = {<br>  \"desk\": {<br>    \"drawer\": \"stapler\"<br>  },<br>  \"cabinet\": {<br>    \"top drawer\": { <br>      \"folder1\": \"a file\",<br>      \"folder2\": \"secrets\"<br>    },<br>    \"bottom drawer\": \"soda\"<br>  }<br>};<br>ourStorage.cabinet[\"top drawer\"].folder2;  // \"secrets\"<br>ourStorage.desk.drawer; // \"stapler\"</blockquote>",
```

## To Contributors

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled as `first-timers-only` so only individuals who have not contributed to the main repository for Free Code Camp can resolve this issue. Thank you for understanding.

## Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/16902956/8a710b14-4c24-11e6-83dd-050de1efb0f7.png)

**Comment by aashil** [comment]
Can I take this one?
