### ISSUE TITLE
Beta Test: Run Code on Bonfires Unresponsive

### ISSUE THREAD

**Issue by turtleman95** [FreeCodeCamp/freecodecamp#977]
The "Run Code" button on all Bonfires do nothing upon being clicked (this does not produce any actual error, so I don't have one to show).  Additionally, Ctrl+Enter does not work on these pages, either.
![image](https://cloud.githubusercontent.com/assets/12956806/8242002/7f0c52d2-15da-11e5-891f-7f74903152c7.png)

**Comment by BerkeleyTrue** [comment]
Thanks @turtleman95 I am experiencing the same thing.

**Comment by BerkeleyTrue** [comment]
Our content security is blocking a script that is need for this to work.

**Comment by BerkeleyTrue** [comment]
@turtleman95 What browser and browser version are you running?

**Comment by BerkeleyTrue** [comment]
Anyone else experiencing this?

**Comment by CWelshE** [comment]
It's functioning as it should on my end! I'm running Firefox 40.0a2 (Developer Edition). Both clicking and the keyboard command run as expected.

**Comment by turtleman95** [comment]
@BerkeleyTrue Sorry for the delay.  I am using Chrome, version 43.0.2357.124.

**Comment by BerkeleyTrue** [comment]
Its seems this is not directly related to the browser. Seems like signs are pointing to some caching issue.

**Comment by BerkeleyTrue** [comment]
Alright, looks like clearing javascript cache fixes it! @turtleman95 Let me know if you need help with this!
