### ISSUE TITLE
Profile Lookup Challenge—Periods (Full Stops) in Return Statements Fail Last Two Checks

### ISSUE THREAD

**Issue by powell956** [FreeCodeCamp/FreeCodeCamp#9771]
#### Profile Lookup (Basic JavaScript)

https://www.freecodecamp.com/challenges/profile-lookup

#### Periods (Full Stops) in Return Statements Fail Last Two Checks

All things equal, a solution with the return statements "No such property." and "No such contact." will be counted wrong because they include periods, whereas statements without periods are correct.

#### Browser Information

* Chrome, Version: 51.0.2704.103 (64-bit)
* Mac OS X Version 10.11.5 
* Desktop

#### My Code

```
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
  for (i = 0; i < contacts.length; i++){ 
    if (firstName === contacts[i].firstName){
      if(contacts[i].hasOwnProperty(prop)){
        return contacts[i][prop];
      }
      else{
        return "No such property.";
      }
    }
  }
  return "No such contact.";
}
// Only change code above this line


// Change these values to test your function
lookUpProfile("Akira", "likes");
 
```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/17016867/16905813/fd18c454-4c79-11e6-9deb-edd58825c3bc.png)

**Comment by qmikew1** [comment]
I would say that the last two tests didn't fail but were actually successful. If you look at the instructions it doesn't ask for a period. So, it's evaluating for the string specified (not up until a boundary or partial string). In my opinion, massaging a string into different levels of 'correctness' would be wrong because one dot, bracket, semicolon, or parenths can cause you lots of grief (often does) when you're programming. So, keeping an eye out for little things is important and is something that should be learned early on.

**Comment by erictleung** [comment]
@powell956 thanks for the issue but as @qmikew1 has pointed out, the instructions ask specifically for no periods. The instructions do not have a typo. In the future, if you get stuck with or have a question about a challenge, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by GODWJZ** [comment]
I thought I wrote the same code with @powell956 ,but I passed it . Anybody knows ? Here is my code:
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
for ( i = 0; i < contacts.length; i++) {
  if (firstName === contacts[i].firstName){
    if (contacts[i].hasOwnProperty(prop)){
       return contacts[i][prop];
    }else {
      return "No such property";
    }
  }
}
  return "No such contact";
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "likes");
![_2016-08-12t12-30-10 108z](https://cloud.githubusercontent.com/assets/20476998/17622245/a2f458f6-60cb-11e6-815a-a60532538d1b.png)
