### ISSUE TITLE
[HELP] I think my answer works, but couldn't pass the test..

### ISSUE THREAD

**Issue by RyC37** [FreeCodeCamp/FreeCodeCamp#9772]
Challenge [Generate Random Whole Numbers within a Range](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-within-a-range#?solution=%0A%2F%2F%20Example%0Afunction%20ourRandomRange(ourMin%2C%20ourMax)%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%7D%0A%0AourRandomRange(1%2C%209)%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20randomRange(myMin%2C%20myMax)%20%7B%0A%20%20var%20result%20%3D%20Math.floor((1%20-%20Math.random())%20*%20(myMax%20-%20myMin))%20%2B%20myMin%3B%0A%0A%20%20return%20result%3B%20%2F%2F%20Change%20this%20line%0A%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0Avar%20myRandom%20%3D%20randomRange(5%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourRandomRange(ourMin, ourMax) {

  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourRandomRange(1, 9);

// Only change code below this line.

function randomRange(myMin, myMax) {
  var result = Math.floor((1 - Math.random()) * (myMax - myMin)) + myMin;
  //when Math.random()=0,  the result = myMax; In this case, this function can generates myMax
  return result; // Change this line

}

// Change these values to test your function
var myRandom = randomRange(5, 15);

```

**Comment by erictleung** [comment]
@RyC37 thanks for the issue. Your clever answer does theoretically give the appropriate ranges asked for in the challenge. Our tests run a permutation test where it calls your function 100 times. Your code, however, requires that `Math.random()` return `0` precisely (as you have pointed out in your comments). If you run `Math.random()` yourself, you'll find it very difficult to get a precise number, say 0.4. 

Practically speaking, your answer doesn't give the correct answer. I hope this makes sense. Kudos on the clever solution though! 

Closing this issue as not an issue with the site. Happy coding!
