### ISSUE TITLE
Wiki broken link

### ISSUE THREAD

**Issue by Devinsuit** [FreeCodeCamp/FreeCodeCamp#9773]
#### Issue Description

https://www.freecodecamp.com/wiki/  
Link Wiki-Central is 404. (Guides on how to Contribute)

#### Browser Information

* Browser Name, Version:  Chrome 51
* Operating System:  Ubuntu 14.04
* Mobile, Desktop, or Tablet:  Desktop

**Comment by BKinahan** [comment]
More completely: 

None of the links on the main Wiki landing page to other pages within the Wiki are functional, and this includes:

- https://freecodecamp.github.io/wiki/CamperBot
- https://freecodecamp.github.io/wiki/Algorithm-Wiki-Template
- https://freecodecamp.github.io/wiki/Wiki-Central

Also, it seems that clicking a link to the Wiki from a source outside of the FCC website (eg the URL in @Devinsuit's issue description above) results in a lack of search functionality on the landing page, and refreshing results in no change. Can anyone reproduce that, or is it already reported?

**Comment by qmikew1** [comment]
Confirmed (accessing link directly https://www.freecodecamp.com/wiki/ results in page load but no search functionality) - But yeah, it's probably a side effect of the migration (and no idea if there's a bug outstanding)

**Comment by dhcodes** [comment]
I believe #9513 may be relevant.

**Comment by raisedadead** [comment]
Hey everyone, we are moving away the wiki completely to the forum. And while that happens there will be some of the links that are broken. We request all contributors to pitch in the effort to help audit the same and make pull requests (if needed) in the codebase addressing the same.

Please feel free to follow and your comments on
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9731
