### ISSUE TITLE
Add a hat symbol to babel-eslint version

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/FreeCodeCamp#9776]
A carat (aka hat) symbol, `^` needs to be added [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/package.json#L35). So the result should look like this:
`"babel-eslint": "^6.1.2",`.

**Comment by benschac** [comment]
This would be my second issue, could I grab it?

**Comment by brunnocgoncalves** [comment]
Hi, I'd like to work on it. Is it ok?

**Comment by bugron** [comment]
@benschac @brunnocgoncalves whenever you want to take an issue don't ask, just check if there is no a PR opened for the issue and freely open your PR. Make sure that you've read [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before submitting a PR.

**Comment by LeeWarnock** [comment]
I'm working on this one, it'll be my first :D

**Comment by LeeWarnock** [comment]
amended my PR for this per instruction! If there's anything else I can change please let me know! :D
