### ISSUE TITLE
Confusing Comment

### ISSUE THREAD

**Issue by KingLouisXVII** [FreeCodeCamp/FreeCodeCamp#9777]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%0A%20%20%2F%2F%20Add%20record%20here%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add new record here
]; // Add your own code down below


```

**Comment by erictleung** [comment]
@KingLouisXVII thanks for the issue but can you clarify what or which comment was confusing? It wasn't entirely clear from your issue description.

**Comment by KingLouisXVII** [comment]
In the exercise the existing comment "//Add new record here" confused me and led me to write my code at the place of the comment instead of after the semicolon. Maybe that could be prevented by an additional comment that points out to write the own code below the comment.  I am not sure if this is an issue that should be pointed out here though. If not, I'm sorry.

**Comment by erictleung** [comment]
@KingLouisXVII the challenge does ask you to add your code at the place of the comment. You shouldn't be adding code after that last semi-colon. I think the comment there is aptly placed.

**Comment by alayek** [comment]
@KingLouisXVII yes, you have to add your code after the comment (not in the same line, from next line; but you already know how single-line comment works, so you know not to add in the same line), so that the array `myMusic` would have two elements. The instruction is clear, and you just have to take care of the comma.

I am closing this for now. Happy coding!
