### ISSUE TITLE
[Fix Request] Add alternative to C9

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#9778]
Recently, C9 was [acquired](https://c9.io/blog/great-news/) by Amazon and with this new change, (or  maybe before), C9 is no longer usable by new campers as it [**requires Credit Card**](https://community.c9.io/t/credit-card-required-for-free-account/7434/3) info for verification.

I suggest adding another resource or an alternative to C9 for those who cannot verify using Credit Card or don't have one.

See,
- [Required Credit Card](https://community.c9.io/t/credit-card-required-for-free-account/7434/3)

**Comment by qmikew1** [comment]
I can also verify (though I have an existing c9 but went through steps as new user) that a credit card is now required. It's sort of a difficult thing because on the one hand it would break some projects that are required if a switch to another service occurred - But at the same time new users are going to run into it fairly soon. One thing though, before initiating any action (imo) somebody from fcc core staff should contact c9 because if you look through the posts in @abhisekp 's link there is some mention by c9 moderator relating to educational entitiest: 

Hi all,

Thank you again for the feedback and all the updates (including your workaround @Nezteb :thumbsup:). I just wanted to keep you posted and let you know that we have a proposed solution for this for educational users. It's probably a couple weeks out so it should be good by the time most schools start back up for the school year. I will post all updates I hear about right here but feel free to continue to post feedback and experiences here.

Thanks,
Brady

**Comment by ramir141974** [comment]
Thank you so much for helping me a important message and I figure out my
account in Amazon thanks...

**Comment by erictleung** [comment]
I think we've talked about using [HyperDev](https://hyperdev.com/) as a potential replacement for c9. But it is still unstable and untested fully.

The challenges it affects are at least:

- Save your Code Revisions Forever with Git
- Manage Packages with npm
- Start a Node.js Server
- Continue working with Node.js servers
- Finish working with Node.js servers
- Build Web Apps with Express.js
- Store Data in MongoDB

**Comment by atjonathan** [comment]
Most of the nodeschool challenges for node and express will be removed with our own challenges with the curriculum update.

**Comment by alayek** [comment]
I think there is some discussion in the pipeline that we would like to mimic some functionality of hyperdev in FreeCodeCamp main site. It would be great if campers can work in an environment in the site itself.

---

It doesn't solve the underlying issue though. [Nitrous](https://www.nitrous.io/) is another such platform. It had a free tier, and back in July 2015 they removed that. They resumed their free-tier two months ago, but with a limited monthly time limit.

Today we are looking at Hyperdev, and who knows, soon enough some other competitor to AWS (Google or Microsoft, or even Facebook) might acquire it. And then we would have to look for another service like this.

I initially started the [DevBlend](https://github.com/DevBlend/) process with @byteknacker, @koustuvsinha, Zac, Manuel, and @atjonathan  to help setup an offline environment, on personal machines of regular campers. 

I know it sounds like I am using this opportunity to promote my open source project; but politics aside - with some love from FCC core team, we could surely look at that as an alternative.

**Comment by atjonathan** [comment]
Yeah this is great solution which has a team from Freecodecamp behind it. Me, @alayek and @byteknacker can lead the team if we decide on this option.  The one issue I can see is users having to install things locally, however I think we should expect users to have that knowledge and we can walk them through it in a challenge.

**Comment by clothesclothes439** [comment]
You can add images to your website by using the img element, and point to a specific image's URL using the src attribute.

An example of this would be:

my image isnt working can someone help

<img src="https://www.your-image-source.com/your-image.jpg">

Note that in most cases, img elements are self-closing.

Try it with this image:

https://bit.ly/fcc-relaxing-cat

**Comment by alayek** [comment]
@clothesclothes439 what do you mean? How is this image related to the c9 discussion?

**Comment by qmikew1** [comment]
How outside the realm of possibility is it that fcc could develop and host its own c9 or hyperdev like environment? I've seen some of @alayek (et al)'s stuff (probably should look at more) and it's no doubt cool - One thing though, even with turnkey type VMs (which for the sake of argument I'll call it that (though there are different approaches, tools, scripts etc.) - Local always has an element of unknown(s) in terms of setup and from what I've seen in terms of questions relating to anything remotely local, a lot of new users just don't have a clue. This is really a team discussion but, can't help but chime in (sorry). Any of the options are doable/viable but maybe buying more time with c9 would allow  you to get there and also cause the least transition clash? *(i.e, probably doing a query on progress to see how many people (and when) are going to start hitting the projects that require c9 and thus generating "I have to have a credit card, what gives?" questions and stoppage in progress flow -in terms of scope  and would be a good idea either way)*

**Comment by atjonathan** [comment]
I agree about the issue with local setup. I would love to work in something like cloud 9. However, I think going with hyperdev would be a better option as hosting a c9 alternative would take a lot of time and money. And np we always love hearing what campers think :smiley:

**Comment by raisedadead** [comment]
Closing in favor of #9826 (although this was created earlier, @QuincyLarson has summarized in depth the need).

Please follow along there.
