### ISSUE TITLE
The star disappear from required, when done.

### ISSUE THREAD

**Issue by mikael1000** [FreeCodeCamp/FreeCodeCamp#9779]
#### Issue Description

Maybe it's a small thing. But in the Map link you can see an overview of everything. And there is the text on top of the page: "**Challenges required for certifications are marked with a *.**". It's nice but as soon as you have done a challenge marked with a * it's marked as done but the star disappear. The star that tells you it's required for certifications.

Just nice if the star was still there. :) 

#### Browser Information

I use Chrome on Windows and did not try any other. Don't think that matters?

**Comment by erictleung** [comment]
@mikael1000 thanks for the feedback. I have noticed this and sometimes do wish those stars were still there too 😄 

cc/ @FreeCodeCamp/issue-moderators what do you guys think about keeping those stars there?

**Comment by atjonathan** [comment]
I think they should stay :+1:

**Comment by raisedadead** [comment]
> The star that tells you it's required for certifications.

Agreed.

**Comment by alayek** [comment]
Yes, they should stay. Whether I have completed the challenge or not, I would like to know at any stage of my progress whether I needed to complete certain challenges. This might be beneficial to some campers in the long run, or say, even in an interview 
> Only 54% of it was required, as you can see from the stars next to them, but I finished 96% of it anyway.

**Comment by dhcodes** [comment]
I believe I've identified the fix for this so I'm happy to take it. I added the lines `span.text-primary &thinsp; &thinsp; strong *` after line 38 in the file: /server/views/map/show.jade and tested it locally. The challenge text still fades upon completion but the star remains.

Screenshot: http://i.imgur.com/wDPzH8k.png

Sound good?

**Comment by raisedadead** [comment]
@dhcodes line nos could be different with the code changing every time.

Is this the line you are talking about?
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/map/show.jade#L38

Can you share a snippet of your change?

**Comment by dhcodes** [comment]
I'm not sure the best way to snip. Does this work?
https://gist.github.com/dhcodes/c39fbc9a552d7fc530bbb041de8a4c63

**Comment by dhcodes** [comment]
I made a mistake on this PR. Now if you complete a non-required challenge, a star is added and that's not the desired outcome. Can you reopen this?
