### ISSUE TITLE
$.getJSON link redirects to jquery.each()

### ISSUE THREAD

**Issue by duttakapil** [FreeCodeCamp/freecodecamp#978]
The "JQurey's $.getJSON" link in the Zipline's, instead of opening the getJSON document, link to the $.each document.

**Comment by LumenTeun** [comment]
There is already two issues - #918 and #919 - mentioning this and one pull request - #937 - fixing it.

**Comment by terakilobyte** [comment]
Closing this is a duplicate issue, thanks for catching this @LumenTeun and thanks for the report @duttakapil
