### ISSUE TITLE
Believe BooWho(1) should be true, not false

### ISSUE THREAD

**Issue by jenniferpham** [FreeCodeCamp/FreeCodeCamp#9784]
Challenge [Boo who](https://www.freecodecamp.com/challenges/boo-who#?solution=%0Afunction%20booWho(bool)%20%7B%0A%0A%20%20%2F%2F%20What%20is%20the%20new%20fad%20diet%20for%20ghost%20developers%3F%20The%20Boolean.%0A%20%20if%20(bool%20%3C%3D%200%20%7C%20bool%20%3D%3D%3D%20-0%20%7C%20bool%20%3D%3D%3D%20null%20%7C%20bool%20%3D%3D%3D%20false%2C%20isNaN(bool)%20%7C%20bool%3D%3D%3D%20undefined%20%7C%20bool%20%3D%3D%3D%20%22%22%20%7C%20typeof%20bool%20%3D%3D%3D%20%22number%22)%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%7D%0A%0AbooWho(1)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function booWho(bool) {

  // What is the new fad diet for ghost developers? The Boolean.
  if (bool <= 0 | bool === -0 | bool === null | bool === false, isNaN(bool) | bool=== undefined | bool === "" | typeof bool === "number"){
    return false;
  }
  else{
    return true;
  }
}

booWho(1);

```
I believe that this is wrong. 
Testing says: "booWho(1) should return false", but according to: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean, it specifies which items are considered false, and the rest is true.  0 or neg numbers are false, but all other positive numbers should be true.
<img width="239" alt="screen shot 2016-07-18 at 5 48 43 pm" src="https://cloud.githubusercontent.com/assets/10639090/16934965/34560332-4d10-11e6-856d-cc5634794aeb.png">

**Comment by Jaskaranbir** [comment]
@jenniferpham I believe that you are interpreting the challenge incorrectly. The challenge is not about translating input values into boolean, but to check if the argument passed to function is a `true` or `false`. In simple words, this is valid:

```
function booWoo(true)...
function booWoo(false)...
```

But this is invalid:

```
function booWoo(1)...
function booWoo(0)...
// Or anything else, whether number or alphabet or whatever
```

Only valid arguments are `true` and `false`.

**Comment by erictleung** [comment]
@jenniferpham thanks for the issue but as @Jaskaranbir has pointed out, you may have misinterpreted the instructions.

> Check if a value is classified as a **boolean primitive**. Return true or false.
>
> **Boolean primitives** are true and false.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by stgisi** [comment]
Eu Hi
On Jul 18, 2016 2:53 PM, "Jennifer Pham" <notifications@github.com> wrote:
>
> Challenge Boo who has an issue.
> User Agent is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0)
Gecko/20100101 Firefox/47.0.
> Please describe how to reproduce this issue, and include links to
screenshots if possible.
>
> My code:
>
> function booWho(bool) {
>
>   // What is the new fad diet for ghost developers? The Boolean.
>   if (bool <= 0 | bool === -0 | bool === null | bool === false,
isNaN(bool) | bool=== undefined | bool === "" | typeof bool === "number"){
>     return false;
>   }
>   else{
>     return true;
>   }
> }
>
> booWho(1);
>
> I believe that this is wrong.
> Testing says: "booWho(1) should return false", but according to:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean,
it specifies which items are considered false, and the rest is true. 0 or
neg numbers are false, but all other positive numbers should be true.
