### ISSUE TITLE
function call returns right answer but when I click on Run Tests, nothing happens

### ISSUE THREAD

**Issue by MahadMajeed** [FreeCodeCamp/FreeCodeCamp#9786]
Challenge [Chunky Monkey](https://www.freecodecamp.com/challenges/chunky-monkey#?solution=%0Afunction%20chunkArrayInGroups(arr%2C%20size)%20%7B%0A%20%20var%20out%20%3D%20%5B%5D%3B%0A%20%20var%20upper%2C%20lower%2C%20i%3B%0A%20%20lower%20%3D%200%3B%0A%20%20upper%20%3D%20size%3B%0A%20%20while(1)%7B%0A%20%20%20%20%0A%20%20%20%20out%5Bi%5D%20%3D%20arr.slice(lower%2Cupper)%3B%0A%20%20%20%20if(upper%20%3E%3D%20arr.length)%7B%0A%20%20%20%20%20%20upper%20%3D%20arr.length%20%2B%201%3B%0A%20%20%20%20%20%20out.push(arr.slice(lower%2Cupper))%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20out.push(arr.slice(lower%2Cupper))%3B%0A%20%20%20%20%0A%20%20%20%20%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0A%20%20%20%20i%2B%2B%3B%0A%20%20%20%20lower%20%3D%20lower%20%2B%20size%3B%0A%20%20%20%20upper%20%3D%20upper%20%2B%20size%3B%0A%20%20%7D%0A%20%20return%20out%3B%0A%7D%0A%0AchunkArrayInGroups(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function chunkArrayInGroups(arr, size) {
  var out = [];
  var upper, lower, i;
  lower = 0;
  upper = size;
  while(1){
    
    out[i] = arr.slice(lower,upper);
    if(upper >= arr.length){
      upper = arr.length + 1;
      out.push(arr.slice(lower,upper));
      break;
    }
    /////////////////////////////
    out.push(arr.slice(lower,upper));
    
    /////////////////////////////
    i++;
    lower = lower + size;
    upper = upper + size;
  }
  return out;
}

chunkArrayInGroups([0, 1, 2, 3, 4, 5, 6, 7, 8], 2);

```

**Comment by MahadMajeed** [comment]
the function call at the end of the code returns the desired output but FreeCodeCamp doesn't recognize it.

**Comment by serj-babiy** [comment]
The while loop loops through a block of code as long as a specified condition is true.
So it because you use infinite loop.
And you did no receive two-dimensional array.

**Comment by alayek** [comment]
@MahadMajeed which tests are not passing?

**Comment by BKinahan** [comment]
@MahadMajeed Your returned value actually contains two hidden properties: `undefined` and `NaN`. For example for `chunkArrayInGroups([0, 1, 2, 3, 4, 5, 6, 7, 8], 2);` your output is `[ [ 0, 1 ], [ 2, 3 ], [ 4, 5 ], [ 6, 7 ], [ 8 ], undefined: [ 0, 1 ], NaN: [ 8 ] ]`

I'll leave it as an exercise for you to work out why and how to fix it. The [Help Javascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) chat might be useful if you get stuck 😄
