### ISSUE TITLE
Cant advance to next level

### ISSUE THREAD

**Issue by ucshadow** [FreeCodeCamp/FreeCodeCamp#9787]
#### Issue Description

https://www.freecodecamp.com/ucshadow

Hi, today I got all three foundational certifications: Front End, Data Visualization, and Back End and I should be able to access the next step -- Nonprofit Projects, but they are still locked.

Is there a period of time that my projects must be confirmed to advance, or what can the problem be?

Any help would be appreciated.

**Comment by erictleung** [comment]
@ucshadow congrats on finishing the certifications! I'll tag @QuincyLarson and @BerkeleyTrue to help guide you.

**Comment by BerkeleyTrue** [comment]
@ucshadow Please contact @CodeNonprofit to start the nonprofit projects. micheal@freecodecamp.com.

Happy Coding.

**Comment by ucshadow** [comment]
Thanx for the help guys, I'll do as pointed out.

**Comment by CodeNonprofit** [comment]
Hi @ucshadow,

Thank you for filing an issue. In the email @BerkeleyTrue gave you,  Michael is spelled wrong and I have not received your email. Please resend to michael@freecodecamp.com and I will get back to you today.
