### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by victorcarvalho1** [FreeCodeCamp/FreeCodeCamp#9790]
Challenge [Headline with the h2 Element](https://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3CH2%3ECatPhotoApp%3C%2Fh2%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<H2>CatPhotoApp</h2>

```

**Comment by dwd2010** [comment]
@victorcarvalho1, you wrote H2. it suppose to be h2. 
so It dont have a problem. 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!
