### ISSUE TITLE
Trouble in Use a CSS Class to Style an Element

### ISSUE THREAD

**Issue by abderafay0110** [FreeCodeCamp/FreeCodeCamp#9791]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20h2%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/20524114/16962311/76fa2e5c-4e0a-11e6-95ae-362b1121017d.png)

My code:
```html

<style>
  h2 {
    color: blue;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by abderafay0110** [comment]
donw whith it sorry

**Comment by BKinahan** [comment]
@abderafay0110 Please close the issue if there is no issue :)

Also please note that you can use the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance with writing code. Issues are for bugs with the challenges or website.

Happy coding!

**Comment by laluzinheaven** [comment]
Same Challenge giving problems.
css class  works with comma( , ) not  period ( . )                                        .
h2 ,red-text as opposed to h2 .red-text

Coding:
<style>
  h2 ,red-text {
    color: red;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
