### ISSUE TITLE
Roman Numeral converter

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#9794]
#### Challenge Name
Roman Numeral Converter

#### Issue Description

I'm reporting this based on my tests of an issue another camper reported on the forums.

The thread may be found here [on the FCC forum](http://forum.freecodecamp.com/t/roman-numeral-solution-not-working/21474)

The code pasted below fails all tests for this challenge, even though it is returning the correct answer.

Moving `var converted = []` inside the function returns the exact same result, yet passes all tests.

#### Browser Information

* Browser Name, Version: Chrome / Firefox - latest
* Operating System: Mac OSX El Capitan / Ubuntu 16.04
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
var converted = [];
 
function convertToRoman(num) {
  //use roman numerial char codes
  
  var romans = [{
    1: "I",
    2: "II",
    3: "III",
    4: "IV",
    5: "V",
    6: "VI",
    7: "VII",
    8: "VIII",
    9: "IX"
  }, {
    1: "X",
    2: "XX",
    3: "XXX",
    4: "XL",
    5: "L",
    6: "LX",
    7: "LXX",
    8: "LXXX",
    9: "XC"
  }, {
    1: "C",
    2: "CC",
    3: "CCC",
    4: "CD",
    5: "D",
    6: "DC",
    7: "DCC",
    8: "DCCC",
    9: "CM"
  }, {
  	1:"M"
  }];

  var stringedNum = num.toString().split("").reverse().join("");//63
  

  for (i = 0; i < stringedNum.length; i++) {

    switch (i) {
      case 0:
        converted.push(romans[0][stringedNum[i]]);
        break;
      case 1:
        converted.push(romans[1][stringedNum[i]]);
        break;
      case 2:
        converted.push(romans[2][stringedNum[i]]);
        break;
      case 3:
        converted.push(romans[3][1].repeat([stringedNum[i]]));
        break;
      case -1:
        console.log("-1");
        alert("No number!");
        break;
    }
  }
  //63. 
  return converted.reverse().join("");
}

convertToRoman(2); 
```

#### Screenshot

![roman numeral converter free code camp](https://cloud.githubusercontent.com/assets/322175/16969512/f2b5d346-4dda-11e6-97dd-8abc9366d4f3.png)

**Comment by BKinahan** [comment]
It's already known that use of global variables in such a way prevents the tests from running successfully for otherwise correct code as these variables are not reset between function calls. 
There is an open issue and discussion at #9199, so this is a duplicate issue.

Note that with a global variable for `converted` this function would not work with multiple invocations, even outside of the FCC editor and test environment. For example, for two calls to the function with the argument `2`, the returned values are:
```js
convertToRoman(2); // 'II'
convertToRoman(2); // 'IIII'
```

**Comment by P1xt** [comment]
Oh yes, I'm aware of the issues that occur on multiple calls to the function. Like I said, just reporting for another camper.

I'll close this out now as it appears to be covered by the other open ticket.
