### ISSUE TITLE
FreeCodeCamp doesn't work right on my Android tablet

### ISSUE THREAD

**Issue by TheSciencePundit** [FreeCodeCamp/FreeCodeCamp#9796]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```
I tried several times to submit this code on my Android tablet, and every time the color change didn't take. I finally decided to just input the exact same code on my girlfriend's laptop and it went through without a hitch. So does FreeCodeCamp not work on Android?

**Comment by erictleung** [comment]
@TheSciencePundit thanks for the issue. Yes, it appears that Android injects some odd characters that make it weird. This is a known issue #7753. So all I can advise is to do the challenges giving problems on a laptop or computer. Closing as this is a duplicate issue. Happy coding!
