### ISSUE TITLE
Hello Out there, I'm new and stuck here for like 30 minutes, any help?? thx

### ISSUE THREAD

**Issue by bobdaley** [FreeCodeCamp/FreeCodeCamp#9797]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3Ablue%3B%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

<style>
  h2  {color:blue;}
</style>

**Comment by dwd2010** [comment]
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!
