### ISSUE TITLE
Bug on 'Make Object Properties Private'

### ISSUE THREAD

**Issue by johnkirch123** [FreeCodeCamp/FreeCodeCamp#9798]
Challenge [Make Object Properties Private](https://www.freecodecamp.com/challenges/make-object-properties-private#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20var%20gear%20%3D%200%3B%0A%20%20%0A%20%20this.setGear%20%3D%20function(num)%20%7B%0A%20%20%20%20gear%20%2B%3D%20num%3B%0A%20%20%7D%3B%0A%20%20this.getGear%20%3D%20function()%20%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
  var gear = 0;
  
  this.setGear = function(num) {
    gear += num;
  };
  this.getGear = function() {
    return gear;
  };
};

var myCar = new Car();

var myBike = new Bike();

```

The code works as expected, when I put whatever I like into 'set' I can call the getGear method and it shows it to me. It even gives me a green check mark on the "The getGear() should return a 4 when you do setGear(4)", but not for 3 or 1, when I test it does give me a 3 and a 1, or whatever number I put in there.

**Comment by johnkirch123** [comment]
Found this issue elsewhere.

**Comment by U-ways** [comment]
This issue is still there, why did you close it?

**Comment by mytreasures** [comment]
![image](https://cloud.githubusercontent.com/assets/20458399/17098306/46c60088-5294-11e6-8a7a-be4da77967b5.png)

**Comment by Prateekmedy** [comment]
Thanks Mam!!!!!!
