### ISSUE TITLE
Frozen Tab

### ISSUE THREAD

**Issue by caseywoolley** [FreeCodeCamp/freecodecamp#980]
Challenge http://www.freecodecamp.com/challenges/bonfire-steamroller has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I'm not sure if this is a bug or a recursion error on my part but this code works on repl.it and it freezes the tab when I run it on FCC:

```js
var steamroller = function(arr) {
  return getValues(arr).split("");
};

var getValues = function(arr) {  
    var values = "";
    for (i = 0; i < arr.length; i++){
        console.log(arr[i]);
        
        if (arr[i]) {
            if (arr[i].constructor === Array){
                values += getValues(arr[i]);
            } else {
                values += arr[i];  
            }
        }
    }
    return values;    
};
```

**Comment by terakilobyte** [comment]
It's most likely a bug in your code, but could you do me a favor to rule it out or confirm it? When you invoke the code (`streamroller(...)`) at the bottom of the editor window, switch out the different test cases.

The only protection offered against infinite loops and other catastrophic things at the moment is based on the initial arguments passed in. The tests are executed in your main browser thread and one of them is likely inducing the freeze.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue persists.
