### ISSUE TITLE
FreeCodeCamp challenges fully reset.

### ISSUE THREAD

**Issue by poke1337** [FreeCodeCamp/FreeCodeCamp#9800]
#### Challenge Name

I got to the Build a Tribute Page challenge. But the problem does not lie in the challenge itself(read Issue Description).

#### Issue Description

So I found your website yesterday(Tuesday July 20 2016) and I started doing a lot of challenges up to "Build a Tribute Page" and I did some of that before I closed my computer and went to bed. Then the next day(Wednesday July 20 2016) I decided to go back and continue working on the challenges. And to my surprise it was all wiped! It had not logged me out, it had just cleared all my challenges as I have had done nothing.

I asked on the help chat and they said I might have logged in with the wrong account, but again it had not logged me out. But anyways I tried to login with both email and Github but still it said that I had completed no challenges at all.

This has really demotivated me to continue since I have to do all the challenges again. And I know that if this happens to other people they most likely will just quit.

Anyway can I get the progress back or do I have to do them all again?

Thanks for any answer.
Regards MartinT

#### Browser Information

* Browser Name, Version: Google Chrome Version 51.0.2704.103 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by alayek** [comment]
@poke1337 really sorry to hear that. Yes, if it were to happen to me, I would lose motivation to continue as well.

This is indeed a big issue. I am tagging @QuincyLarson and @BerkeleyTrue as they are more equipped to look into this matter better than I am.

Thanks for reporting this.

**Comment by poke1337** [comment]
@alayek Hello sir, I got some motivation back. Do you think I can just continue from where I got to, and then later it will be sorted out. Or do you think that there is no way it will be fixed and I have to start all over again no matter what?

Thanks in advance.

**Comment by BerkeleyTrue** [comment]
@poke1337 We do not save partial solutions. If you did not submit a solution it is saved locally in your localStorage. If you clear your browser localStorage those solutions are cleared as well.

If you feel you did submit your solutions and they are now gone please email our support team@freecodecamp.com

Happy Coding
