### ISSUE TITLE
page not working

### ISSUE THREAD

**Issue by anookeen** [FreeCodeCamp/FreeCodeCamp#9801]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by alayek** [comment]
hi @anookeen kindly provide details of the issue you have been facing. I am closing this issue for now, Feel free to re-open it with more details (or just comment below with details of your issue; yes, you have to type down what exactly is not working for you).
