### ISSUE TITLE
Remove wiki sidebar

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9807]
Since we are moving to the forum, we can remove the wiki sidebar javascript, HTML and less.

**Comment by dhcodes** [comment]
I'm up for taking a crack at this. To confirm, I would:
1) Remove the wiki button on the navbar.
2) Remove all code regarding the Wiki sidebar flyout (HTML, LESS, JS).

Anything else?

**Comment by raisedadead** [comment]
@dhcodes yes that is what we expect, please go ahead.

**Comment by alayek** [comment]
@raisedadead I think Quincy already has a PR removing the Wiki link from navbar. Is this different?

**Comment by raisedadead** [comment]
He has for removing it from the nav bar, this is removing it from the sidebar.

**Comment by raisedadead** [comment]
@dhcodes we have a PR for this
> 1) Remove the wiki button on the navbar.

you need to work on 
> 2) Remove all code regarding the Wiki sidebar flyout (HTML, LESS, JS).

**Comment by dhcodes** [comment]
Okay, thanks. Will do.

**Comment by atjonathan** [comment]
@raisedadead :+1:
