### ISSUE TITLE
Forum has 500 Internal Server Error

### ISSUE THREAD

**Issue by dhcodes** [FreeCodeCamp/FreeCodeCamp#9809]
#### Challenge Name

N/A

#### Issue Description

I'm getting a 500 Internal Service Error when making a reply on the forum. I didn't see a place to submit bugs on the forum so I'm posting it here. I had another camper in the chat room confirm that they are getting the same error.

#### Browser Information

* Browser Name, Version: Chrome, 51
* Operating System: OS X, El Capitan
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```

**Comment by Amallard** [comment]
I can confirm this. Blank page when going to http://forum.freecodecamp.com/ 

Checked the console. 

`right.js:22 Uncaught TypeError: Cannot read property 'version' of null
http://forum.freecodecamp.com/ 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

Browser Information

- Broswer Name, Version: Chrome, 51
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

**Comment by Amallard** [comment]
I had the same issue. Seems to be back online now.

**Comment by raisedadead** [comment]
Please open on https://github.com/FreeCodeCamp/discourse
/cc @m-henderson
