### ISSUE TITLE
Steamroller : console output does not match value used in the test cases

### ISSUE THREAD

**Issue by alidaca** [FreeCodeCamp/FreeCodeCamp#981]
Challenge http://www.freecodecamp.com/challenges/bonfire-steamroller has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

My code is returning the correct value in the console as well as in an external editor, but when I look at the test cases they compare the expected result to a different value than my code output in the console. I have ran it with several of the test cases and it seems to either duplicate the values in the final array or attach the values from the previously ran test to the current array. Please fix.

My code:
```
var newArr = [];

function steamroller(arr) {
  for (var i = 0; i < arr.length; i++){
   console.log(Array.isArray(arr[i]));
   if (Array.isArray(arr[i])){
     steamroller(arr[i]);
   }else{
     newArr.push(arr[i]);
   }
 }
console.log(newArr);
return newArr;
}

steamroller([[['a']], [['b']]]);
```
console output: ['a','b']
frecodecamp test result: expected [ 'a', 'b', 'a', 'b' ] to deeply equal [ 'a', 'b' ]

![steamroller](https://cloud.githubusercontent.com/assets/12631698/8243846/be785ad4-15cf-11e5-96fb-156d57a33dec.JPG)

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
