### ISSUE TITLE
[beta] Remove "update email" button underline 

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#9817]
When hovering over the button an underline appears.

**Comment by raisedadead** [comment]
Just to help:

Currently the DOM renders like below for the underlined button like this:
```html
<a href="/settings/update-email" data-reactid="66">
    <button class="btn-link-social btn-block btn btn-lg btn-primary" type="button" data-reactid="67"> 
    <span name="envelope" class="fa fa-envelope" data-reactid="68"></span>
    <!-- react-text: 69 -->Update my Email<!-- /react-text -->
    </button>
</a>
```

Where are a render like below fixes it.

```html
<a href="/settings/update-email" class="btn-link-social btn-block btn btn-lg btn-primary">
    <span name="envelope" class="fa fa-envelope"></span>
    <!-- react-text: 139 -->Update my Email<!-- /react-text -->
</a>
```

**Comment by BerkeleyTrue** [comment]
@raisedadead Thanks for the info. That gives me an idea of where to look. It could be the anchor tag without a class has an underline decoration on hover

**Comment by raisedadead** [comment]
Yeah seems like it. I directly edited the DOM on the Devtools to check for a fix.

**Comment by BerkeleyTrue** [comment]
Fixed and live on beta!

Thanks for finding that!
