### ISSUE TITLE
Item 13's link is wrong. It does not go to getJSON. It goes to each. 

### ISSUE THREAD

**Issue by cornjacket** [FreeCodeCamp/freecodecamp#982]
Challenge http://www.freecodecamp.com/challenges/zipline-use-the-twitch.tv-json-api has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Item 13's link is wrong. It does not go to getJSON. It goes to each. It should go to the following link.

http://api.jquery.com/jQuery.getJSON/

**Comment by LumenTeun** [comment]
This was mentioned it #918, #919 and #978, and fixed in #937.
