### ISSUE TITLE
Bug in the JavaScript Switch-challenges (return answer = ...)

### ISSUE THREAD

**Issue by Curting** [FreeCodeCamp/FreeCodeCamp#9821]
Challenge [Replacing If Else Chains with Switch](https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch#?solution=%0Afunction%20chainToSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(val%20%3D%3D%3D%20%22bob%22)%20%7B%0A%20%20%20%20answer%20%3D%20%22Marley%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%2042)%20%7B%0A%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%2099)%20%7B%0A%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%207)%20%7B%0A%20%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AchainToSwitch(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  if (val === "bob") {
    answer = "Marley";
  } else if (val === 42) {
    answer = "The Answer";
  } else if (val === 1) {
    answer = "There is no #1";
  } else if (val === 99) {
    answer = "Missed me by this much!";
  } else if (val === 7) {
    answer = "Ate Nine";
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);


```
Hey. I think I've encountered a chain of bugs. In the JavaScript "Switch" challenges it teaches one to simply write 'answer = ...' in each case. That produces an error. To succeed and continue one has to write 'return answer = ...'. Can anyone of you verify this? :-)

Regards,
Oliver Curting

**Comment by qmikew1** [comment]
The point of the exercise is to convert ```if /else if``` into a switch (case statement) -That hasn't been attempted in the pasted code. I went through and did the exercise, and don't see any errors. ```answer =``` is changing the variable (and would be whatever is instructed); however, the return statement is pretty clear ```return answer;```  [help](https://gitter.im/FreeCodeCamp/HelpJavaScript) is a great resource for questions like this

**Comment by erictleung** [comment]
@Curting thanks for the issue. I've completed the challenge and it works perfectly when you write `answer = ...` for each case. You don't need `return answer = ...`. Can you post the code that does give you bugs? Thanks.

**Comment by Curting** [comment]
Hello. Thanks for your quick replies.
I'm embarrassed to admit that you both are completely right. The error in my code was elsewhere.

I'm sorry for taking your time. I did try asking in the chat without any replies prior to writing this. With that being said I learned something from the issue.

Please keep up your great work – I really do appreciate it 👍
