### ISSUE TITLE
Second test is failing not sure why.

### ISSUE THREAD

**Issue by kpbeng** [FreeCodeCamp/FreeCodeCamp#9827]
Challenge [Map the Debris](https://www.freecodecamp.com/challenges/map-the-debris#?solution=%0Afunction%20orbitalPeriod(arr)%20%7B%0A%20%20var%20newArr%3Darr%3B%0A%20%20var%20GM%20%3D%20398600.4418%3B%0A%20%20var%20earthRadius%20%3D%206367.4447%3B%0A%20%20var%20T%3D0%3B%0A%20%20%0A%20%20for%20(var%20i%20in%20newArr)%0A%20%20%7B%0A%20%20%20%20var%20a%3DnewArr%5Bi%5D.avgAlt%2BearthRadius%3B%0A%20%20%20%20T%3D%202%20*%203.14159%20*%20Math.sqrt(Math.pow(a%2C%203)%20%2F%20398600.4418%20)%3B%0A%20%20%20%20newArr%5Bi%5D.orbitalPeriod%3D%20Math.round(T)%3B%0A%20%20%20%20delete%20newArr%5Bi%5D.avgAlt%3B%0A%20%20%20%7D%0A%20%20return%20newArr%3B%0A%7D%0A%0AorbitalPeriod(%5B%7Bname%3A%20%22iss%22%2C%20avgAlt%3A%20413.6%7D%2C%20%7Bname%3A%20%22hubble%22%2C%20avgAlt%3A%20556.7%7D%2C%20%7Bname%3A%20%22moon%22%2C%20avgAlt%3A%20378632.553%7D%5D)%0A) has an issue.
User Agent is: <code>Chrome/51.0.2704.103</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

```js
function orbitalPeriod(arr) {
  var newArr=arr;
  var GM = 398600.4418;
  var earthRadius = 6367.4447;
  var T=0;
  
  for (var i in newArr)
  {
    var a=newArr[i].avgAlt+earthRadius;
    T= 2 * 3.14159 * Math.sqrt(Math.pow(a, 3) / 398600.4418 );
    newArr[i].orbitalPeriod= Math.round(T);
    delete newArr[i].avgAlt;
   }
  return newArr;
}
```

**Comment by raisedadead** [comment]
Have you reached out to [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript)?

**Comment by BKinahan** [comment]
Yup, [here](https://gitter.im/FreeCodeCamp/HelpJavaScript?at=5790d56b16487c5e517293b2). And then it was [resolved](https://gitter.im/FreeCodeCamp/HelpJavaScript?at=5790d7ad841e619d162c4bb6). The power of the chat in action! 😄

**Comment by dwd2010** [comment]
@BKinahan, great.  thanks for let us know.
