### ISSUE TITLE
Normalize GA event data

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#9837]
Our GA event data is all wonky. We need to normalize!
Your task would be to track down all the `ga` function calls and normalize their values. These function calls currently happen in both JavaScript and Jade files.

Here is how they should be normalized.

## Category

Category should be space separated capital words i.e. `Map`, `Challenge` `Mind Blown` (hopefully there shouldn't be a need for more than one word in a category.

Here is what we have so far
![events_overview_-_analytics](https://cloud.githubusercontent.com/assets/6775919/17040741/724b4da8-4f56-11e6-9434-36472c4cca48.png)

As you can see NAV and SHOP needs to be fixed.

## Actions
Actions should be past tense verbs in `kebab-case` for instance: 'clicked', 'opened', 'toggled', 'downloaded', 'scrolled', 'ran-code', 'solved'.

These need to be fixed to just clicked and the label value should be used to differentiate which links:
![top_events_-_analytics](https://cloud.githubusercontent.com/assets/6775919/17040709/4116f82c-4f56-11e6-8d47-71b23c42cf80.png)

## Label

Label should be specific to the event. For instance, when someone clicks on a link in the shop, the label should be the item they are buying.

These need to have the 'button clicked' removed and the action changed to 'clicked' making it's inclusion in the label redundant.

![top_events_-_analytics](https://cloud.githubusercontent.com/assets/6775919/17041025/0232c47c-4f58-11e6-8075-247e8f8bfb67.png)

Here is the docs for event tracking https://developers.google.com/analytics/devguides/collection/analyticsjs/events

The ga function has the following signature

## value
this shoudln't need to be touched
```js
ga('send', 'event', category, action, label, value);
```

cc @evaristoc for feedback
cc @QuincyLarson

**Comment by alanbares** [comment]
I'd like to tackle this issue.

**Comment by BerkeleyTrue** [comment]
Yours ✨
