### ISSUE TITLE
Add 2016 New Coder Survey path to freecodecamp.com

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9841]
The 2016 New Coder Survey is live here: https://freecodecamp.github.io/2016-new-coder-survey/

We want https://www.FreeCodeCamp.com/2016-new-coder-survey to render this (as though it were actually hosted on FreeCodeCamp.com)

**Comment by raisedadead** [comment]
@QuincyLarson Can we change the green to Free Code Camp's green, at least on the header section, to maintain consistency?

**Comment by QuincyLarson** [comment]
@raisedadead Yes - I think we should change the green of the entire page to Free Code Camp green.

**Comment by SamAI-Software** [comment]
Keep it on pause until I push the entire page with new colors then.

**Comment by SamAI-Software** [comment]
After [**merging this**](https://github.com/FreeCodeCamp/2016-new-coder-survey/pull/65) we are good to go.

**Comment by raisedadead** [comment]
@SamAI-Software thanks a lot for making the changes so fast. 
@QuincyLarson Can you please do a QA and merge.

**Comment by QuincyLarson** [comment]
@raisedadead Yes, @SamAI-Software's changes look pretty sharp. We are I've pushed them to https://freecodecamp.github.io/2016-new-coder-survey/

All we need is for @BerkeleyTrue to help us set up the route.

**Comment by BerkeleyTrue** [comment]
https://freecodecamp.github.io/2016-new-coder-survey/ Done!

A little touch and go there. NGINX is not a forgiving beast.
