### ISSUE TITLE
Caesars Cipher: My code pass all the tests but doesn't validate on FCC

### ISSUE THREAD

**Issue by eakl** [FreeCodeCamp/FreeCodeCamp#9842]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=let%20engine%20%3D%20(v)%20%3D%3E%20%7B%0A%20%20%0A%20%20let%20low%20%3D%20'A'.charCodeAt()%3B%0A%20%20let%20high%20%3D%20'Z'.charCodeAt()%3B%0A%20%20%0A%20%20if%20(!!v.match(%2F%5Ba-z%5D%2Fi))%20%7B%0A%20%20%20%20if%20(v.charCodeAt()%20-%2013%20%3C%20low)%20%7B%0A%20%20%20%20%20%20let%20code%20%3D%20(high%20-%20(low%20-%20(v.charCodeAt()%20-%2013%20%2B%201)))%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20String.fromCharCode(code)%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%20return%20String.fromCharCode(v.charCodeAt()%20-%2013)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20return%20v%3B%0A%20%20%7D%0A%7D%3B%0A%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20%0A%20%20return%20'%22'%20%2B%20str%0A%20%20%20%20.split('')%0A%20%20%20%20.map(engine)%0A%20%20%20%20.join('')%20%2B%20'%22'%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0A%2F%2Frot13(%22SERR%20PBQR%20PNZC%22)%3B%0Arot13(%22SERR%20CVMMN!%22)%3B%0A%2F%2Frot13(%22SERR%20YBIR%3F%22)%3B%0A%2F%2Frot13(%22GUR%20DHVPX%20OEBJA%20QBT%20WHZCRQ%20BIRE%20GUR%20YNML%20SBK.%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.

The code pass all the tests but doesn't validate on FCC editor. Why that? 

My code:
```javascript
let engine = (v) => {
  
  let low = 'A'.charCodeAt();
  let high = 'Z'.charCodeAt();
  
  if (!!v.match(/[a-z]/i)) {
    if (v.charCodeAt() - 13 < low) {
      let code = (high - (low - (v.charCodeAt() - 13 + 1)));
      
      return String.fromCharCode(code);
    }
    else {
      return String.fromCharCode(v.charCodeAt() - 13);
    }
  }
  else {
    return v;
  }
};

function rot13(str) { // LBH QVQ VG!
  
  return '"' + str
    .split('')
    .map(engine)
    .join('') + '"';
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");
rot13("SERR CVMMN!");
rot13("SERR YBIR?");
rot13("GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.");

```

**Comment by raisedadead** [comment]
I am not an ES6 expert, requesting assistance from @FreeCodeCamp/issue-moderators 
By far the output is matching the expected criteria.

The only thing that I can play a hunch is with the error that shows on the Dev Console:

![image](https://cloud.githubusercontent.com/assets/1884376/17055669/e9667ff4-502b-11e6-999c-fcb580e9e47a.png)

[Here is the complete log](https://gist.githubusercontent.com/anonymous/a065fe2bcaf606cadb537bb56a60462c/raw/beb78788ffa388f20f422162df6ac7748cbb8bc1/log.txt)

Can anyone guide?

**Comment by Bouncey** [comment]
Could it be the global scope of 'engine'? Everytime a test runs it tries to define 'engine' again? 

I had a quick search in the repo for 'engine' being defined anywhere, but could only find it in some express files as a string.

**Comment by raisedadead** [comment]
Nope already checked that, changing the name is not helping. Also I tried refactoring the code to test global declaration to be a problem.

If you check the complete log there is a weird error thrown by the RX.js library which I believe only @BerkeleyTrue has a good understanding of.

**Comment by Bouncey** [comment]
I can't run ES6 on my phone, I'll try it out when I get a chance

**Comment by BKinahan** [comment]
Sorry guys, but the code is incorrect. Running the code above with two minor changes allows it to pass all tests. 

The original code returns a string containing an extra pair of double quotes, eg `'"FREE PIZZA!"'` instead of `'FREE PIZZA!'`, and deleting the pair of double quote concatenations in the return statement fixes that problem.

There does seem to be some conflict with the inner workings of the editor when using the variable name `engine`, but this doesn't stop the tests from passing successfully.

**Comment by raisedadead** [comment]
@BKinahan mind submitting your code in here?

**Comment by BKinahan** [comment]
@raisedadead It really is the same code as above without the concatenations I mentioned. You may be having the issue where a page refresh is needed to allow test results to be updated, which affects many challenges in certain conditions.

Here's the code anyway for the sake of completeness:
```js
let engine = (v) => {
  
  let low = 'A'.charCodeAt();
  let high = 'Z'.charCodeAt();
  
  if (!!v.match(/[a-z]/i)) {
    if (v.charCodeAt() - 13 < low) {
      let code = (high - (low - (v.charCodeAt() - 13 + 1)));
      
      return String.fromCharCode(code);
    }
    else {
      return String.fromCharCode(v.charCodeAt() - 13);
    }
  }
  else {
    return v;
  }
};

function rot13(str) { // LBH QVQ VG!
  
  return str
    .split('')
    .map(engine)
    .join('');
}

// Change the inputs below to test
//rot13("SERR PBQR PNZC");
rot13("SERR CVMMN!");
//rot13("SERR YBIR?");
//rot13("GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.");
```

**Comment by raisedadead** [comment]
Nope this doesn't let me pass the challenge.
I am on Windows 7 - Version 52.0.2743.82 m

**Comment by raisedadead** [comment]
Okay I did a full reset and cleared my cache then used the code you mentioned. 
Passed with flying colors!

Thanks for the help @BKinahan 

Yet I think the test messages are confusing, where a camper will definitely add the quotes as stated.
IMHO we should fix this.

**Comment by eakl** [comment]
@raisedadead My first attempt was without the quotes. It didn't work so I added the quotes without more success then posted an issue. Now I just removed the quotes and **refreshed** the page as mentioned by @BKinahan and it works. Weird...

**Comment by Bouncey** [comment]
Nice catch @BKinahan , but that has raised two issues:

1. Unclear instructions for the result expected
2. codeUri not extracting and running the updated code without a refresh

**Comment by raisedadead** [comment]
Yeah @eakl I got that too... I share your frustration.
Anyhow to contributors please update the messages to not have the quotes.

as in:

![image](https://cloud.githubusercontent.com/assets/1884376/17058291/44377dfa-503d-11e6-99ef-610332cdb1aa.png)

for all the tests.

**Comment by Bouncey** [comment]
Personally, I can't recall ever having to refresh the browser to get some code to run apart from testing this issue.

Does it warrant a separate issue? Does it happen often enough?

**Comment by BKinahan** [comment]
@Bouncey It happens to me a lot, but it may be due to my use of ES6 features like arrow functions (which notably are used in this case). More testing needed 😄

**Comment by eakl** [comment]
@Bouncey It happened 3 times for me so far. Including this challenge.

**Comment by raisedadead** [comment]
@eakl to be honest we don't have 100% ES6 support for challenges yet. So it could be anything, to best of my knowledge Chrome has started supporting only in the latest of v52 I think. Many things will be broken.

**Comment by Bouncey** [comment]
I've only just started using es6, and never in FCC, so I think it is an ES6 problem

**Comment by eakl** [comment]
@raisedadead @Bouncey I mostly use ES6 when I can (arrow function, const/let, argument operators, ...). It may be that indeed.

**Comment by BKinahan** [comment]
@raisedadead Does your note [above](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9842#issuecomment-234541953) imply that all other challenges whose functions return strings should also display them without quotation marks? E.g. Spinal Tap Case, Repeat a string repeat a string, and others..

I haven't seen this type of mistake in relation to this challenge or those others with similar outputs, so it may be quite uncommon. If so it might not justify a broad change, especially for test cases which should return empty strings and can't be represented without the quotes 😄

**Comment by raisedadead** [comment]
Yeah, that is correct. 
But this is the behavior that you would see in the Dev Console. 

So I think its not ambiguous.

![image](https://cloud.githubusercontent.com/assets/1884376/17076772/70175990-50d8-11e6-9bd9-d1f41dad7d2f.png)

But yeah representing empty string would be tough in the test messages. 
Any interesting ideas are most welcome

**Comment by iykyvic** [comment]
solved this question using the charCode  methods decided to solve it without those methods, solution seems okay but not working.
`function rot13(str) { // LBH QVQ VG!
  str = str.toUpperCase().split("");
  var abc = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"];
  var indices = [];
  var newString = [];
  var rot13arr = [];
  var newStringrot13arr = [];
  function getindices(){
    abc.forEach(function(val,index){
      if(index + 13 > 25){
        indices.push(index -13);
      }
      else{ 
        indices.push(index + 13);
      }
    });
  }
  function newStringFunc(){
    str.forEach(function(val){
      if(abc.indexOf(val) == -1){
        newString.push(val);
      }
       else{newString.push(abc.indexOf(val));}
    });
  }
  function rot13array(){
    newString.forEach(function(val){
      if(indices.indexOf(val) == -1){
        rot13arr.push(val);
      }
      else{ rot13arr.push(indices.indexOf(val));}
    });
  }
  function newRot13str(){
    rot13arr.forEach(function(val){
      if(abc[val] === null ||abc[val] === undefined || abc[val] === ""){
        newStringrot13arr.push(val);
      }
      else{newStringrot13arr.push(abc[val]);}
    });
  }
  getindices();
  newStringFunc();
  rot13array();
  newRot13str();
  //var finalString  = newStringrot13arr.join(" ");
  //return '"' + finalString + '"';
  return newStringrot13arr.join(" ");
}


// Change the inputs below to test
rot13("SERR PBQR PNZC");
`

help needed.

**Comment by texas2010** [comment]
@iykyvic, this place is not for get a help. 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by iykyvic** [comment]
@texas2010, thank you for responding, I already solved the problem using the charCode methods, so I don't need help solving this one, I am just asking why this code(previous comment) which works does not pass the test.
