### ISSUE TITLE
[beta] map aside pop out (new tab) button does not work

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9846]
![image](https://cloud.githubusercontent.com/assets/1884376/17057674/2b316b08-5039-11e6-89a5-ac754b6617a3.png)

Windows 7 - Chrome Version 52.0.2743.82 m

**Comment by raisedadead** [comment]
On a side note I was hoping to fix this myself, but setting up the react dev environment is driving me nuts.

**Comment by Bouncey** [comment]
@raisedadead I tried setting it up on ubuntu, but I couldn't get it working either

**Comment by BerkeleyTrue** [comment]
@bouncey @raisedadead we will need to figure out the issue you two are having during setup before we merge into staging. Can one of you open a separate issue describing the problem?

**Comment by BerkeleyTrue** [comment]
Fixed and live! Thanks for catching this y'all!
