### ISSUE TITLE
[beta] Profile icon doesn't navigate back to portfolio from settings

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9847]
On the settings page clicking the profile pic of the camper doesn't take them to their portfolio page, the browser shows the link as `/settings`. 

On clicking the icon nothing happens.

Refer Screenshot:

![1](https://cloud.githubusercontent.com/assets/1884376/17057863/ad7fcd10-503a-11e6-90b8-96cf150ea77b.png)

Windows 7 - Chrome Version 52.0.2743.82 m

**Comment by BerkeleyTrue** [comment]
The image and points now takes you to settings, not profile. We've changed that so we stay in the react app when navigating to settings. 

When you are on settings the link does nothing because there is no need to redirect the page.

**Comment by raisedadead** [comment]
Ah cool then this can be closed.
