### ISSUE TITLE
[beta] Social buttons don't work

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9849]
![image](https://cloud.githubusercontent.com/assets/1884376/17058070/d83c4ec4-503b-11e6-973d-9ea64ab0e6bb.png)

**Comment by BerkeleyTrue** [comment]
Which buttons? Sign-in with github works fine for me

**Comment by BerkeleyTrue** [comment]
I see which ones now!

**Comment by raisedadead** [comment]
Apologies, yeah the ones to link profile to Twitter, GitHub and LinkedIn

**Comment by BerkeleyTrue** [comment]
Fix and live on beta!

**Comment by BerkeleyTrue** [comment]
Nice catch!
