### ISSUE TITLE
Solution is not tested for correctness

### ISSUE THREAD

**Issue by hohguy** [FreeCodeCamp/freecodecamp#985]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue.

The lesson goal is to add a button labelled "submit". Simply pasting the string "<button type='submit'>this button submits the form</button>" (from the tutorial) into the form solves the lesson. The completion checking script should test for string length to ensure that only "submit" is used for the button label as well as testing for the presence of the string "submit".

**Comment by QuincyLarson** [comment]
@hohguy thank you for your input. We purposefully use loose regular expressions for validating text input in situations where it might be distracting or frustrating to have extra whitespace or other imperfections.
