### ISSUE TITLE
Pressing CTRL + Enter should take me to next challenge as per current behaviour

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9850]
After completing a challenge I press <kbd>CTRL</kbd> + <kbd>Enter</kbd> or <kbd>Cmd</kbd> + <kbd>Enter</kbd>, this submits my challenge.

Doing the same once again should take me to the next challenge as per the behaviour of the current site.

**Comment by BerkeleyTrue** [comment]
I'm not sure this should be added. I dislike that the behavior changes depending on the context and could not find a clean way to implement in Redux now that we do not have a modal after successful attempt.

One option is to make a successful attempt automatically submit and move you to the next challenge, but this might run into a `Principal of least surprise` issue. This is why I decided not to code it in and wait for the community to comment.

**Comment by raisedadead** [comment]
Ahh, I get what you mean, but problem is this behavior is known to almost all campers as a handy shortcut. 

I am up for the later proposal which is submit automatically + move to next.
we could just announce this behavioral change, when we push to production.

**Comment by raisedadead** [comment]
@BerkeleyTrue I think something on lines of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5759 should help? What say?

**Comment by BerkeleyTrue** [comment]
There is already too much clutter going on in the UI. That solution just doesn't look great and takes up a lot of real-estate.

**Comment by QuincyLarson** [comment]
I agree with @raisedadead that we need for ctrl+enter to advance to the subsequent challenge, like it used to. Switching to mouse mode and manually navigating is a hassle.

I agree with @BerkeleyTrue that we should not add a new UI element.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson 

> I dislike that the behavior changes depending on the context

**Comment by QuincyLarson** [comment]
Explanation by @p1xt of the issue (closed as duplicate): https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10623

**Comment by BerkeleyTrue** [comment]
How about a different key stroke to submit vs test?

**Comment by P1xt** [comment]
Why not just have control-enter automatically take you to the next challenge if the tests all passed?

**Comment by BerkeleyTrue** [comment]
@p1xt This was behavior in an older version of the site and it caused major issues. We don't want automatic behavior that involves hitting the database. 

We also got complaints from users.

**Comment by P1xt** [comment]
@BerkeleyTrue I fail to see how control enter to test and then click a submit toast (that disappears if you wait too long) is an improvement over control enter control enter.

**Comment by BerkeleyTrue** [comment]
> I dislike that the behavior changes depending on the context

**Comment by P1xt** [comment]
While it's true that you may dislike that - it worked. Plus, it was intuitive and quick to type, bam, bam, tested, submitted - it just worked.

Clicking a button that disappears doesn't.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @P1xt I think ctrl+enter should run the tests everywhere - regardless of which element you have in focus. And then, if the tests are passing, you should be able to able to press ctrl+enter a second time to submit and move to the next challenge. 

As @BerkeleyTrue said, we should not auto-advance, as it's astonishing and campers seem to like reviewing their passing code before moving on.

**Comment by P1xt** [comment]
@QuincyLarson @BerkeleyTrue I agree on the no autoadvance ... but intentionally removing the second cntl-enter to submit and proceed removed familiar, intuitive and popular behavior.

**Comment by Bouncey** [comment]
If #11202 is merged, I can have this done with

```js
'Ctrl-Enter': function() {
// this.props.isPassed is true only when the challenge has been passed
    if (this.props.isPassed) {
       submintChallenge();
     }
     executeChallenge();
     return false;
     }
```

**Comment by Bouncey** [comment]
@QuincyLarson @BerkeleyTrue I have this working locally
