### ISSUE TITLE
Not able to view Tribute Challenge Page

### ISSUE THREAD

**Issue by bboysathish** [FreeCodeCamp/FreeCodeCamp#9852]
#### Challenge Name
https://www.freecodecamp.com/challenges/build-a-tribute-page

#### Issue Description
Not able to view the already built tribute page. https://codepen.io/FreeCodeCamp/full/NNvBQW/

#### Browser Information

* Browser Name, Version: Brave 
* Operating System: Windows
* Mobile, Desktop, or Tablet:  0.11.1

#### Screenshot
![tribute](https://cloud.githubusercontent.com/assets/8023447/17061331/9eb359a8-504b-11e6-9066-0ec020def9dc.PNG)

**Comment by dhcodes** [comment]
This appears to be a browser-specific issue as I tested your browser (Brave) with another codepen URL and it gave a 404 as well. It's specifically to do with the "full" view of pages on codepen as if you [modify the URL to take you to the editor view](https://codepen.io/FreeCodeCamp/pen/NNvBQW/) it will display. For any future codepen URLs in full, you will need to replace the word "full" in the URL with the word "pen". 

While this is an issue, I'm not sure it's one that FCC can fix as it seems to be a specific issue with this browser and codepen, but others may chime in.

**Comment by BKinahan** [comment]
I'm not familiar with the Brave browser but their website claims that it "automatically blocks ads and trackers", so it looks like it's blocking something more than it should and preventing Codepen from working correctly.

I have downloaded Brave and can confirm that none of the FCC pens load correctly, nor do any pen previews on the main https://codepen.io/pens/ page.

I'd recommend whitelisting codepen.io within the browser if you can.

**Comment by bboysathish** [comment]
Well, then let me file this issue @brave-laptop repository. :)
