### ISSUE TITLE
Local development environment setup (React branch)

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9855]
While trying to setup the local development environment for `feature/react-challenges` branch.

`npm install` throws the following warnings:

```sh
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:                                         
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14                        
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:                            
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14                        
npm WARN thundercats-react@0.5.1 requires a peer of react@~0.14.0 but none was installed.                         
npm WARN thundercats-react@0.5.1 requires a peer of react-dom@~0.14.0 but none was installed.                     
npm WARN react-addons-css-transition-group@15.2.1 requires a peer of react@^15.2.1 but none was installed.        
npm WARN react-addons-transition-group@15.2.1 requires a peer of react@^15.2.1 but none was installed.            
npm WARN react-addons-shallow-compare@15.2.1 requires a peer of react@^15.2.1 but none was installed. 
```

Stack:
**OS** Windows 10 - 64 Bit
**node**  v4.2.2
**mongod** 
db version v3.0.7
git version: 6ce7cbe8c6b899552dadd907604559806aa2e9bd
**npm** 3.8.7

**Comment by raisedadead** [comment]
I have been able to run the instance without problems though. 
/cc @BerkeleyTrue

**Comment by raisedadead** [comment]
Okay first issue with Github Auth (hitting the Sign in with GitHub callback):

```sh
Loopback
500 TypeError: Cannot read property 'constructor' of undefined
   at User-Identity.js:59:22
   at run (D:\DEV\OpenSource\FreeCodeCamp\node_modules\core-js\modules\es6.promise.js:89:22)
   at D:\DEV\OpenSource\FreeCodeCamp\node_modules\core-js\modules\es6.promise.js:102:28
   at flush (D:\DEV\OpenSource\FreeCodeCamp\node_modules\core-js\modules\_microtask.js:18:9)
   at D:\DEV\OpenSource\FreeCodeCamp\node_modules\async-listener\glue.js:188:31
   at doNTCallback0 (node.js:419:9)
   at process._tickDomainCallback [as _tickCallback] (node.js:389:13)
```

**Comment by Bouncey** [comment]
I have now got a local instance running on my machine.

The only difference I have between now and the last time is my node version.

Before I was using node v6.3.0 and got 
```sh
npm WARN react-addons-css-transition-group@15.2.1 requires a peer of react@^15.2.1 but none was installed.        
npm WARN react-addons-transition-group@15.2.1 requires a peer of react@^15.2.1 but none was installed.  
```
I even went into `package.json` to pull that version of react, but it made no difference.

This time I used node v4.1.2 and `npm install` went without a problem, just
```sh
npm WARN prefer global marked@0.3.5 should be installed with -g
```

**OS**: Ubuntu 16.04
**node**: v4.1.2
**npm**: 2.14.4
**mongod**
db: v3.2.8
git: ed70e33130c977bda0024c125b56d159573dbaf0

**Comment by BerkeleyTrue** [comment]
> 500 TypeError: Cannot read property 'constructor' of undefined

@raisedadead This happens when you have a orphaned UserIdent. Clear out the userIdent and that should be fixed. Not related to beta.

**Comment by BerkeleyTrue** [comment]
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:                                         
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14                        
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:                            
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14                        
npm WARN thundercats-react@0.5.1 requires a peer of react@~0.14.0 but none was installed.                         
npm WARN thundercats-react@0.5.1 requires a peer of react-dom@~0.14.0 but none was installed.                     
npm WARN react-addons-css-transition-group@15.2.1 requires a peer of react@^15.2.1 but none was installed.        
npm WARN react-addons-transition-group@15.2.1 requires a peer of react@^15.2.1 but none was installed.            
npm WARN react-addons-shallow-compare@15.2.1 requires a peer of react@^15.2.1 but none was installed. 

@raisedadead Please clear your node_modules directly. That should clear most of these up.

**Comment by raisedadead** [comment]
@BerkeleyTrue thanks for the tip, all is good now! Can be closed if @Bouncey has no more issues to mention.
