### ISSUE TITLE
Confusing position of "Only change code above this line" at challenge "Using objects for lookup"

### ISSUE THREAD

**Issue by greedyvgeek** [FreeCodeCamp/FreeCodeCamp#9859]
![screen shot 2016-07-22 at 8 46 47 pm](https://cloud.githubusercontent.com/assets/20259415/17075623/e53ba702-504d-11e6-9bce-b1f92d46a3c2.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by erictleung** [comment]
@greedyvgeek thanks for the feedback. Can you clarify why the comments on "Only change code above this line" are confusing? What about it is confusing? And, if you want, how might you suggest a better way to make the challenges?

**Comment by greedyvgeek** [comment]
At first it was "Return result" and it did not work.
I had to change it to "return lookup[val].
I suggest putting "return result" line above the "\\only change code below
this line"

**Comment by raisedadead** [comment]
You are expected to return a string, and hence the `var result` has already been created as such, it can be assigned from a value from the array.

That's the intent of the challenge. IMHO the placement of the comment is correct.
/cc @erictleung this can be closed. Leaving it for your opinion.

**Comment by BKinahan** [comment]
Yup, the instructions say to assign the correct string to the `result` variable, and moving the return statement upward would cause some to try `return result = lookup[val];`

**Comment by erictleung** [comment]
Okay, closing then. Thanks all and happy coding!

**Comment by PrepressNinja** [comment]
The original critique is correct...the comment is wrong.  Reading the code from top to bottom (like we learn to do) and encountering a comment that says "// Only change code above this line" causes the student to STOP.  The correct solution requires editing BELOW the line (changing "return result" to "return result[val];").  This is a teaching tool for beginners. When you define a rule, don't expect a novice to break that rule.  Fix the comment position.

**Comment by OFFLlNE** [comment]
@PrepressNinja You are not meant to change the return line.
As Raisedadead said:
You are expected to return a string, and hence the var result has already been created as such, it can be assigned from a value from the array.

That's the intent of the challenge. IMHO the placement of the comment is correct.
