### ISSUE TITLE
Stuck at "Testing Objects for properties"

### ISSUE THREAD

**Issue by greedyvgeek** [FreeCodeCamp/FreeCodeCamp#9860]
![screen shot 2016-07-22 at 9 43 53 pm](https://cloud.githubusercontent.com/assets/20259415/17075839/7bc44038-5055-11e6-8fe4-163c7bddaaa7.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by erictleung** [comment]
@greedyvgeek thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). GitHub issues are for noting problems with the site, not challenges help. Happy coding!
