### ISSUE TITLE
CamperBot can't add brownie points after user has changed his Github username

### ISSUE THREAD

**Issue by macbem** [FreeCodeCamp/FreeCodeCamp#9862]
I've changed my Github username from noczesc to macbem a while ago. I was a user of FCC before the name change and every time someone tries to give me brownie points, CamperBot returns 'could not find receiver for macbem'. 'thanks @noczesc' still works though.

**Comment by BKinahan** [comment]
Hi @macbem, have you already tried the "Update my portfolio from GitHub" option on the [Settings page](https://www.freecodecamp.com/settings)?

**Comment by macbem** [comment]
@BKinahan I just tried it and it resolved my issue.

**Comment by BKinahan** [comment]
Great! Feel free to close the issue 😄

**Comment by sanjaykt** [comment]
Thanks for this.. This resolve my issue as well
