### ISSUE TITLE
CTRL + Enter not working in Chrome 43 for WIndows.

### ISSUE THREAD

**Issue by apkostka** [FreeCodeCamp/freecodecamp#987]
CTRL + Enter key combo to advance does not work in Chrome v. 43.0.2357.124 on Windows 7.

**Comment by oab00** [comment]
works for me in Chrome v. 43.0.2357.124 m (laptop) on Windows 7.

**Comment by LumenTeun** [comment]
There are already quite a few issues regarding <C-Enter>, namely #921 and #912.

**Comment by QuincyLarson** [comment]
Thanks for reporting this. I'm closing this as a duplicate.
