### ISSUE TITLE
Small screen laptop fails to render phone frame HTML/CSS Waypoints

### ISSUE THREAD

**Issue by josevill** [freeCodeCamp/freeCodeCamp#9873]
#### Challenge Name

[Every HTML/CSS waypoint](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css)
#### Issue Description

Look at the screenshots provided below. It has something to do with the screen resolution, it's 1024x600. This is a 11" laptop, i got it almost only to do the FCC curriculum on the go, but i found i cant use it using its native resolution. If i go into developer mode and simulate a bigger screen resolution, i can do my coding with ease, but it's a lot of work to browse the site in such mode using the touchpad.
#### Browser Information

- Browser Name, Version: Firefox 47.0
- Operating System: Windows 7 X86
- Mobile, Desktop, or Tablet: It's a netbook.
#### Your Code

``` js

```
#### Screenshot

[1st part of the site, Challenge description and stuff](http://i.imgur.com/FboSOhK.png)
[2nd part of the site, code itself](http://i.imgur.com/JgtdiOA.png)
[3rd part of the site, where the phone frame should be rendered](http://i.imgur.com/9xIFcWJ.png)
[Developer mode / Mobile mode](http://i.imgur.com/XziGzBF.png)

**Comment by dhcodes** [comment]
@josevill It's not just your laptop; the phone frame is not included on any tablet or mobile device. 

I supposed if the image were an svg or its width/height were in scalable units, it could be possible to have it show on smaller screens.

**Comment by evaristoc** [comment]
Confirming this one.

**Comment by hallaathrad** [comment]
Maybe we can add a breakpoint for screens between 960 and 1024 px wide... 
It'd show the instructions on top, and then the code taking 2/3 and the phone taking 1/3.

Any takers? I think this could work, and it'd help some iPad users too.

**Comment by codetweetie** [comment]
I would like to work on this if nobody has taken it already.

**Comment by hallaathrad** [comment]
Gopher! :) I'll QA for you :)
