### ISSUE TITLE
Nonprofit Projects

### ISSUE THREAD

**Issue by ucshadow** [FreeCodeCamp/FreeCodeCamp#9875]
Hello, it's been 6 days since I contacted @CodeNonprofit by writing an email to codenonprofit@gmail.com (as seen in his github profile) and still no answer. 

This was the original issue post https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9787

Is there any other way to contact him?

**Comment by raisedadead** [comment]
Hi @ucshadow apologies for the delay in getting back. Michael normally responds to his emails very fast, not sure if he is away/busy with something.

We will get back to you asap.

**Comment by CodeNonprofit** [comment]
Hi @ucshadow,

Thank you for filing an issue. In the email @BerkeleyTrue gave you, Michael is spelled wrong. I have not received your email. Please forward to michael@freecodecamp.com and I will get back to you today.

**Comment by CodeNonprofit** [comment]
@ucshadow Additionally, you should have received an email from us after receiving all 3 certifications. If you did not receive this email, you do not have an email address on file with Free Code Camp. This outlines the next steps for the nonprofit projects.

**Comment by raisedadead** [comment]
@ucshadow please follow as directed. Closing as resolved.
