### ISSUE TITLE
Wiki Issue

### ISSUE THREAD

**Issue by IsaacAbrahamson** [FreeCodeCamp/FreeCodeCamp#9877]
Algorithm Missing letters Wiki Page
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Missing-Letters

Wiki page states that 
> You will create a program that will find the missing letter from a string and add it.

and later

> Hint: 3 You will need to figure out where to insert the letter and how to do it...

However, the actual challenge states:
> Find the missing letter in the passed letter range and return it.

and

> fearNotLetter("abcdefghjklmno") should return "i".

The problem is that the challenge requires you to return the missing letter, but according to the wiki page, you are to add the missing letter to the word and then return the word from what I understood. Somewhat confusing.

**Comment by raisedadead** [comment]
Our wiki has been moved to http://forum.freecodecamp.com, we will shortly remove the GitHub Wiki as well, but for the time being please open this on the [wiki repo here](https://github.com/FreeCodeCamp/Wiki/issues)
