### ISSUE TITLE
It appears my code delivers what the lesson requires, yet it indicates an error.

### ISSUE THREAD

**Issue by heymartinadams** [FreeCodeCamp/FreeCodeCamp#9878]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20nextInLine(arr%2C%20item)%20%7B%0A%20%20arr.push(item)%3B%0A%20%20return%20arr.splice(0%2C%201)%3B%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%201))%3B%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function nextInLine(arr, item) {
  arr.push(item);
  return arr.splice(0, 1);
}

// Test Setup
var testArr = [];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1));
console.log("After: " + JSON.stringify(testArr));
```

It appears my code delivers what the lesson requires, yet it indicates an error.

**Comment by raisedadead** [comment]
`.splice` will return an array, while the tests are looking for a number. 
Hence with although your code prints the correct output it fails the test.

I feel we should add a testcase stating:
> `nextInLine` should return a number.

**Comment by BKinahan** [comment]
The same code will still appear to return a number while failing that test, so I'm not sure that addresses the issue.

Can we have the output show an array containing a single number element as an array rather than a number?

**Comment by raisedadead** [comment]
Yeah it's possible, but we gotta hack the tail code to detect if it's an array and then append the `[` and `]`, yet this might get buggy with different solutions.

**Comment by DenDunn** [comment]
Hello, I'm new here, but I want to share my code that also doesn't work:
function nextInLine(arr, item) {
  testArr.push(item);
  return testArr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

In this case .shift actually returns a number, but still I can't pass "nextInLine([5,6,7,8,9], 1) should return 5" check.

**Comment by dhcodes** [comment]
@dendunn I believe in your case, the reason the tests aren't passing are because you need to use arr instead of testArr. I know this can seem confusing because the array in the Test Setup is called testArr.

**Comment by Dayfiri** [comment]
Code works fine. Listen what @dhcodes said above me.

![screenshot at 2016-10-06 11 41 02](https://cloud.githubusercontent.com/assets/16082563/19149358/c0497aa0-8bc1-11e6-9c37-a6b41e72e3a4.png)

**Comment by chiptus** [comment]
Hi, I would like to help fix this. I understand that the solution is to add a test which checks that the result is actually a number.
How do I add a test? I need to work on the "Stand In line" page?

**Comment by tanyildiz** [comment]
you mean challenge page?

https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=function%20convertToRoman(num)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20result%20%3D%20num.toString().split(%22%22)%3B%0A%20%20%0A%20%20%2F%2Fresult%20%3D%20result.join()%3B%0A%20%20var%20x%20%3D%20result.length%3B%0A%20%20var%20roman%20%3D%20%22%22%3B%0A%20%20var%20binler%20%3D%20%5B%22%22%2C%20%22M%22%2C%20%22MM%22%2C%20%22MMM%22%5D%3B%0A%20%20var%20yuzler%20%3D%20%5B%22%22%2C%20%22C%22%2C%20%22CC%22%2C%20%22CCC%22%2C%20%22CD%22%2C%20%22D%22%2C%20%22DC%22%2C%20%22DCC%22%2C%20%22DCCC%22%2C%20%22CM%22%5D%3B%0A%20%20var%20onlar%20%3D%20%5B%22%22%2C%20%22X%22%2C%20%22XX%22%2C%20%22XXX%22%2C%20%22XL%22%2C%20%22L%22%2C%20%22LX%22%2C%20%22LXX%22%2C%20%22LXXX%22%2C%20%22XC%22%5D%3B%0A%20%20var%20birler%20%3D%20%5B%22%22%2C%20%22I%22%2C%20%22II%22%2C%20%22III%22%2C%20%22IV%22%2C%20%22V%22%2C%20%22VI%22%2C%20%22VII%22%2C%20%22VIII%22%2C%20%22IX%22%5D%3B%0A%0A%20%20function%20sum(arr)%20%7B%0A%20%20if%20(x%20%3D%3D%3D%204)%20%7B%0A%20%20%20%20%20var%20y%20%3D%20arr.splice(0%2C%201%2Cbinler%5Barr%5B0%5D%5D)%3B%0A%20%20%20%20console.log(binler%5By%5D%20%2B%20yuzler%5Barr%5B1%5D%5D%20%2B%20onlar%5Barr%5B2%5D%5D%20%2B%20birler%5Barr%5B3%5D%5D)%3B%0A%20%20%20%7D%20else%20if%20(x%20%3D%3D%3D%203)%20%7B%0A%20%20%20%20%20var%20z%20%3D%20arr.splice(0%2C%201%2Cyuzler%5Barr%5B0%5D%5D)%3B%0A%20%20%20%20%20console.log(yuzler%5Bz%5D%20%2B%20onlar%5Barr%5B1%5D%5D%20%2B%20birler%5Barr%5B2%5D%5D)%3B%0A%20%20%20%20%7D%20%20else%20if%20(x%20%3D%3D%3D%202)%20%7B%0A%20%20%20%20%20var%20k%20%3D%20arr.splice(0%2C%201%2Conlar%5Barr%5B0%5D%5D)%3B%0A%20%20%20%20%20console.log(onlar%5Bk%5D%20%2B%20birler%5Barr%5B1%5D%5D)%3B%0A%20%20%20%20%7D%20else%20if%20(x%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20%20var%20i%20%3D%20arr.splice(0%2C%201%2C%20birler%5Barr%5B1%5D%5D)%3B%0A%20%20%20%20%20console.log(birler%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20result%20%3D%20result.join()%3B%0A%20%20%20%20%0A%20%20%7D%20return%20sum(result)%3B%0A%7D%0A%0AconvertToRoman(36)%3B%0A%0A

or codepen.io page?

http://codepen.io/tanyildiz/pen/GjBvJw?editors=0011

Niyazi Tanyıldız
0532 263 36 64

**Comment by knappsacks** [comment]
I can't seem to get this one to work either. I keep getting an error message, `TypeError: arr.shift is not a function`.

`
function nextInLine(arr, item) {
  arr = arr.push(item);
  var nextUp = arr.shift();
  
  return nextUp;  // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
`

**Comment by ja5087** [comment]
@knappsacks You've set `arr` to `arr.push(item)`, which returns an integer representing the new length of the array. `arr` now has the value of `6`.  The key idea is that `arr.push(item)` modifies the array itself, and doesn't need the assignment.

**Comment by chayano** [comment]
thank yous
