### ISSUE TITLE
????

### ISSUE THREAD

**Issue by amelianstars** [FreeCodeCamp/FreeCodeCamp#9879]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%20%0A%20%20.redtext%20%7B%20%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20h2%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style> 
  .redtext { 
    color: red;
  }
  h2{
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by dhcodes** [comment]
@amelianstars There is an issue with your code. Please re-read the directions and ask for help in the [FCC Help chat room](https://gitter.im/FreeCodeCamp/Help).

**Comment by raisedadead** [comment]
@amelianstars thanks for the issue please follow the below before reporting issues.
[Help I have found a bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Report-Bugs).

@dhcodes thanks.
