### ISSUE TITLE
Help bug

### ISSUE THREAD

**Issue by duonganh169** [FreeCodeCamp/FreeCodeCamp#9885]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyStr%20%3D%20%22Hello%20World%22%3B%0A%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line
myStr = "Hello World";

myStr[0] = "H"; // Fix Me



```

**Comment by raisedadead** [comment]
@duonganh169 its mentioned that

`myStr[0] = "J";` **cannot** change the value of myStr to "Job".

Are you stuck on understanding the challenge? Have you visited the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by BEBEDYDY** [comment]
// Setup
var myStr = "Jello World";


// Only change code below this line
myStr = "Hello World";
 // Fix Me


here you go.
