### ISSUE TITLE
Notification modal for campers who have claimed all six certifications

### ISSUE THREAD

**Issue by CodeNonprofit** [freeCodeCamp/freeCodeCamp#9886]
Campers who have claimed all 6 certifications should receive a popup modal telling them to check their email for next steps or to email team@freecodecamp.com if they haven't received one.

Modal copy: 

> You should receive an email with the next steps toward volunteering on a nonprofit project. If you do not receive this email, or haven't associated an email address with your account, please email team@freecodecamp.com.

**Comment by flipsyde606** [comment]
I will work on this.

**Comment by cynicaldevil** [comment]
Since this issue hasn't been active long enough, I assume @flipsyde606 isn't working on this. I'd like to take up this issue to make a PR for my Hacktoberfest contribution!

**Comment by flipsyde606** [comment]
@cynicaldevil, please do so. I have been quite preoccupied.

**Comment by themaxsandelin** [comment]
Hi there, is this issues still in progress?

**Comment by cynicaldevil** [comment]
Ah, I think I will be unable to tackle this issue, I have some work to attend to. Maybe someone else can take it.

**Comment by CodeNonprofit** [comment]
@themaxsandelin We'd love the help if you want to take it on.

**Comment by thanhacun** [comment]
Can I take on that if there is no active one currenly?

**Comment by lijulat** [comment]
Is this taken?

**Comment by atjonathan** [comment]
This hasn't been taken. Feel free to take it on @thanhacun or @lijulat

**Comment by AuroreM** [comment]
Hi everyone ! 
Is this issue still on going ?

**Comment by nsuchy** [comment]
@AuroreM The issue is still open so yes.
