### ISSUE TITLE
Closing form tag before input

### ISSUE THREAD

**Issue by LGMeersseman** [FreeCodeCamp/freecodecamp#989]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-form-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

It is marked as correct if you have the closing tag of the form before your input tags.
![image](https://cloud.githubusercontent.com/assets/9090714/8250404/b0c0a640-1673-11e5-8362-03b3774f067f.png)

**Comment by QuincyLarson** [comment]
Thanks for spotting this! I've fixed this and will push the fix soon.
