### ISSUE TITLE
Update output box copy

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9891]
We need to add "as well" to the end of:
```js
/**
  * Your output will go here
  * Any console.log() -type
  * Statements will appear in
  * Your browser's DevTools
  * JavaScript console
  */
```
since the results do indeed show up there, too.

Thanks to @ChadKreutzer for pointing this out.

**Comment by raisedadead** [comment]
For contributors looking to fix this update the below line of code
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework/output-display.js#L36

to reflect like this:
```js
/**
  * Your output will go here
  * Any console.log() -type
  * Statements will appear in
  * Your browser's DevTools
  * JavaScript console as well
  */
```

#### Please go through the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).
#### You do not need to ask any persmission to work on this, just ensure that you have not contributed to free code camp's codebase earlier.
#### If you need any assistance hit us up in the the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors), we will be happy to help.

Thanks and happy fixing.

**Comment by oalhait** [comment]
I'm on it!

**Comment by azaleas** [comment]
Can I participate now, given that @oalhait is on it? Can I create a pull request?

**Comment by raisedadead** [comment]
Ahh.. I am not sure, we will accept the first pull request that is meets the criteria laid out by the contribution guidelines.

Nevertheless we will log some more first timers issues if possible, also you should check this post on how to contribute to tons of first timer issues.
http://forum.freecodecamp.com/t/where-and-how-do-i-get-started-to-contributing-to-open-source/709

**Comment by azaleas** [comment]
@raisedadead I see. Well, ok then. I will wait out even though the pull is ready;)
