### ISSUE TITLE
Mutations  - FreeCodeCamp - beginner

### ISSUE THREAD

**Issue by for3v3r4u** [FreeCodeCamp/FreeCodeCamp#9892]
Can someone explain me why this code is not working?

function mutation(arr) {
  for(var i=0; i<arr.length; i++) {
    arr[i] = arr[i].toLowerCase();
  }
  for(var j=0; j<arr[1].length; j++) {
    if(arr[0].indexOf(arr[1].charAt(j), 0) !== -1) {
      return true;
    } else {
      return false;
    }
  }  
}

mutation(["hello", "hey"]);

For some reason the letter "y" is not seen by the engine and the return is "true", although is working for all other arguments. I'm trying to understand the behavior of the method.

**Comment by BKinahan** [comment]
Please visit the [HelpJavaScript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance with writing code for the JavaScript challenges.
Issues are for reporting bugs with the challenges or website.

Happy coding!

**Comment by raisedadead** [comment]
@for3v3r4u please visit the chat room as directed by @BKinahan

**Comment by benjamn77** [comment]
I wrote the same code and am trying to understand what's going on in my loops that causes the "y" to get missed. Any new incite for3v3r4u?
