### ISSUE TITLE
Challenge Increment a Number with JavaScript has an issue.

### ISSUE THREAD

**Issue by Fendysutji** [FreeCodeCamp/FreeCodeCamp#9899]
![bug on increment test](https://cloud.githubusercontent.com/assets/19755409/17147361/b3691326-538c-11e6-8e66-1fa40b64f317.png)
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20myVar%2B%2B%20%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
The Result Should 88 but it appear to be 87 ,Can see on the screenshots

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = myVar++ ;


```

**Comment by BKinahan** [comment]
Thanks for reporting, but your code is incorrect. Take another look at the instructions and if you're still stuck, please seek assistance in the [Help Chat](https://gitter.im/FreeCodeCamp/Help).

Happy coding!

**Comment by Fendysutji** [comment]
oh sorry for the false report issue but already find my false and correct it
![increment](https://cloud.githubusercontent.com/assets/19755409/17147819/97e4326e-538e-11e6-9238-632d764d4d20.png)

**Comment by ArmantHitchcock** [comment]
Hi can someone please explain how: myVar = myVar should be changed
means: that i should create a new variable "myVar1" 
myVar1 = ++myVar;

Would it not be better to give the instruction of:
Now create a new variable myVar1 and assign the incremented myVar to it
