### ISSUE TITLE
Single Quote Strings in Arrays Return False - Requires Double String Quotes

### ISSUE THREAD

**Issue by iarobinson** [FreeCodeCamp/FreeCodeCamp#9902]
#### Challenge Name - Single Quotes Return False for Pushing to Arrays
https://www.freecodecamp.com/challenges/manipulate-arrays-with-push

#### Browser Information

* Chrome, Version: 51.0.2704.106 (64-bit)
* Operating System: OSX 10.11.5
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot
<img width="1022" alt="screen shot 2016-07-26 at 12 23 07 pm" src="https://cloud.githubusercontent.com/assets/7991933/17152303/0d1338ae-532c-11e6-81ae-22800f65955c.png">

This screenshot will return incorrect, but when I declare the string inside the array with double quotes, it will work properly.

Both should work I believe.  :D  I LOVE FREE CODE CAMP. Thank you Quincy

**Comment by dhcodes** [comment]
@iarobinson I just tested it and it seems to be working for me (i.e. it accepts single quotes). Could you reset your code and type it again and see if it takes?

**Comment by erictleung** [comment]
@iarobinson using single quotes also work for me.

![screenshot 2016-07-27 at 05 30 57](https://cloud.githubusercontent.com/assets/2754821/17170712/5e24066c-53bb-11e6-8ecb-3c618114366d.png)

Try resetting your code and trying again. If the error still persists, please copy and paste your code verbatim for us to check it. Thanks.

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue still occurs!
