### ISSUE TITLE
Stand in Line || Right code but cannot pass challenge

### ISSUE THREAD

**Issue by McBiggos** [FreeCodeCamp/FreeCodeCamp#9903]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20testArr.push(item)%3B%0A%20%20item%20%3D%20testArr%5B0%5D%3B%0A%20%20testArr.shift()%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%201))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  testArr.push(item);
  item = testArr[0];
  testArr.shift();
  return item;  // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

Hello, I wrote code that should work just fine, but it doesn't.
All tasks are ticked except for "nextInLine([5,6,7,8,9], 1) should return 5"
I changed code to check this particular case and even though it returns right answer, task isn't marked as completed.

EDIT: I'm attaching a screenshot of what my browser displays.
![przechwytywanie](https://cloud.githubusercontent.com/assets/20635180/17155542/d46e3544-5385-11e6-9e3b-98ecee795bbe.JPG)

**Comment by dhcodes** [comment]
@McBiggos I think a key here is to remember that you are writing a function based on the parameters provided (ex. arr, not testArr). I see how based on the tests at the bottom of the code editor it could seem counterintuitive.

FWIW, check out the [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Stand-In-Line) for this challenge for a different take. 

In the future, you might ask for help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) to have another user confirm the issue before submitting it here.

Have a good one.

**Comment by McBiggos** [comment]
@dhcodes Now as I look into it, it seems so obvious I should have used arr instead of testArr.
Thanks for fast reply.
