### ISSUE TITLE
It works but will not let me past

### ISSUE THREAD

**Issue by cjoshmartin** [FreeCodeCamp/FreeCodeCamp#9904]
#### Title Case a Sentence (challenge)

https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0A%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20arryStr%3Dstr.split('%20')%3B%0A%20%20str%3D%22%22%3B%0A%20%20for%20(i%3D0%3B%20i%3CarryStr.length%3Bi%2B%2B)%7B%0A%20%20%20%20var%20temp%20%3DarryStr%5Bi%5D.charAt().toUpperCase()%3B%0A%20%20%20%20var%20lower%3D%22%22%3B%0A%20%20%20%20%20for(j%3D1%3Bj%3CarryStr%5Bi%5D.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20%20lower%2B%3DarryStr%5Bi%5D.charAt(j).toLowerCase()%3B%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%7D%0A%20%20%20%20str%2B%3Dtemp%2Blower%2B%22%20%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A

#### Issue Description

the program I wrote works fine but it will not let me pass

#### Browser Information

* Browser Name, Version:  chrome Version 51.0.2704.103 (64-bit)
* Operating System: OSX 10.11.15
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

function titleCase(str) {
  var arryStr=str.split(' ');
  str="";
  for (i=0; i<arryStr.length;i++){
    var temp =arryStr[i].charAt().toUpperCase();
    var lower="";
     for(j=1;j<arryStr[i].length; j++){
       lower+=arryStr[i].charAt(j).toLowerCase();
       
     }
    str+=temp+lower+" ";
  }
  
  return str;
}
 
```

#### Screenshot

<img width="1436" alt="screen shot 2016-07-26 at 8 44 14 pm" src="https://cloud.githubusercontent.com/assets/8135112/17160345/4f91d8b6-5372-11e6-8561-9bbf1ab391e6.png">

**Comment by pnahratow** [comment]
I think the line `str+=temp+lower+" ";` add a whitespace to the end of the text when in the last iteration which makes the strings not match.  Hint: Have a look at [Array.prototype.join()](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/join) to avoid the problem.

**Comment by erictleung** [comment]
@cjoshmartin as @pnahratow suggests, double check the spaces you add when you join strings. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
