### ISSUE TITLE
Show Cheater flag on everypage

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#9905]
When a user is flagged as `isCheater` A flash message is shown on their profile when ever someone visits that page. 

We would like to add a the same flash message to every page if the user is marked as a cheater while they are logged in.

**Comment by Manish-Giri** [comment]
How is a user flagged as a cheater?

**Comment by raisedadead** [comment]
When a user is reported to the team, we mark them such in the database. 
To work on this issue you gotta check for the `isCheater` property in the User model.

**Comment by IshtmeetSingh** [comment]
How do you actually cheat on freecodecamp?

**Comment by raisedadead** [comment]
Great question, but unfortunately GitHub issues are not for conversations, please ask on the [Forum](http://forum.freecodecamp.com) or in the [Chat rooms](https://gitter.im/FreeCodeCamp/FreeCodeCamp)

Thanks.
