### ISSUE TITLE
you gurz should help me out of thos problem

### ISSUE THREAD

**Issue by anuoluwapo** [FreeCodeCamp/FreeCodeCamp#9906]
Challenge [Comparison with the Equality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-equality-operator#?solution=%0A%2F%2F%20Setup%0Afunction%20testEqual(val)%20%7B%0A%20%20if%20(val)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Not%20Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestEqual(val)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function testEqual(val) {
  if (val) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testEqual(val);


```

**Comment by anuoluwapo** [comment]
you gurz should help out of this problem

**Comment by erictleung** [comment]
@anuoluwapo thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
