### ISSUE TITLE
change the front size of an element

### ISSUE THREAD

**Issue by Yohana13** [FreeCodeCamp/FreeCodeCamp#9908]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%7B%0A%20%20%20%20front-size%3A%2016px%3B%0A%20%20%7D%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I believe I'm doing everything right but I'm stuck, the 5th item is still not cleared
My code:
```html

<style>
  .red-text {
    color: red;
  }
  p{
    front-size: 16px;
  } 
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by SparklesPancake** [comment]
Hi Yohana13,
You have a typo in the line where it should read "font-size".  Currently it says "front-size".

**Comment by erictleung** [comment]
@Yohana13 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). As @SparklesPancake has pointed out, please double check your spelling. Happy coding!

**Comment by kaliyv** [comment]
`<style>
  .red-text {
    color: red;
  }
    
   p{
      font-size: 16x;
    }
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum text dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> kitty ipsum text purr jumpeat the grass rip the couch</p>`   where i did mistake if any one knows kindly let me know

**Comment by SparklesPancake** [comment]
Hi Kaliyv
On the part where you have font-size: 16x,  it should read font-size: 16px.
