### ISSUE TITLE
FCC Heroku app returning json for challenge seems to be down

### ISSUE THREAD

**Issue by jle3** [FreeCodeCamp/FreeCodeCamp#9909]
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-camper-leaderboard

#### Issue Description

The api returning top 100 campers for past 30 days and all time is not returning any data.

#### Browser Information

* Browser Name, Version: chrome 52
* Operating System: mac osx el capitan
* Mobile, Desktop, or Tablet:  desktop

#### Screenshot

![alt text](http://i.imgur.com/N78niU5.png)

**Comment by pnahratow** [comment]
Same problem here.

**Comment by raisedadead** [comment]
@jle3 @pnahratow thanks for reporting. looking into this asap.
@roelver I believe we could use your assistance here.

**Comment by pnahratow** [comment]
The issue seems fixed now. At least the site and API are working again.

**Comment by raisedadead** [comment]
Confirmed.
