### ISSUE TITLE
On installing npm on cloud 9

### ISSUE THREAD

**Issue by achock** [FreeCodeCamp/freecodecamp#991]
Challenge http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Your instructions says it should be on cli like this:
npm install how-to-npm@2.0.0 
npm WARN package.json chat-example@0.0.0 No repository field.
npm WARN prefer global how-to-npm@2.0.0 should be installed with -g

but in reality it should be 
npm install how-to-npm@2.0.0 -g

**Comment by BerkeleyTrue** [comment]
fixed by #1172
