### ISSUE TITLE
Audit and Bring all Heroku Deployments (and code) under FCC

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#9913]
We need to identify the owners of the code for all heroku deployments, and fork and maintain the same under FCC.

List as below:

| Challenge Name | URL | User |
| --- | --- | --- |
| Build a Camper Leaderboard | https://fcctop100.herokuapp.com |  |
| Build a Voting App | https://fcc-voting-arthow4n.herokuapp.com |  |
| Build a Nightlife Coordination App | http://whatsgoinontonight.herokuapp.com |  |
| Chart the Stock Market | http://watchstocks.herokuapp.com |  |
| Manage a Book trading club | http://bookjump.herokuapp.com |  |
| Build a pintrest clone | http://pintech.herokuapp.com |  |
| Time Stamp Microservice | https://timestamp-ms.herokuapp.com |  |
| Request Header Parser Microservice | https://cryptic-ridge-9197.herokuapp.com |  |
| URL Shortener Microservice | https://little-url.herokuapp.com |  |
| File Metadata Microservice | https://aryanj-file-size.herokuapp.com | @AryanJ-NYC ([repo](https://github.com/AryanJ-NYC/file-metadata)) |

/cc @FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
Contributors if you are the owner of the apps please leave links to the repositories below.

**Comment by QuincyLarson** [comment]
@raisedadead Actually, @Em-Ant is working on porting all of these to HyperDev, where we will recommend campers build the back end projects going forward (or they can build them locally - we are creating guides for doing this, too). 

@BerkeleyTrue, @CodeNonprofit and I literally made this decision yesterday, after seeing that @Em-Ant had already ported several dynamic web app projects to hyperdev. He hopes to finish this process soon.

@FreeCodeCamp/issue-moderators

**Comment by raisedadead** [comment]
@QuincyLarson awesome, that sounds great then. 
@Em-Ant looking forward to it. 

Will close this issue once they are in place.

**Comment by QuincyLarson** [comment]
@raisedadead we can put out the immediate fire by changing the Pinterest project link. I am in the process of forking @Em-Ant's Pinterest project and hope to have it live tomorrow, along with a PR updating the example URL.

**Comment by AryanJ-NYC** [comment]
@raisedadead You may also want to add my [file metadata microservice](https://www.freecodecamp.com/challenges/file-metadata-microservice) to the table above for easy reference.  Also, perhaps create a third column (User) in OP table?

Heroku link: https://aryanj-file-size.herokuapp.com/
GitHub link: https://github.com/AryanJ-NYC/file-metadata

**Comment by raisedadead** [comment]
@AryanJ-NYC thanks for these links. I have updated the OP. We have ported most of the challenges. And will update the challenges very soon.

**Comment by QuincyLarson** [comment]
We are moving all our back end projects to GoMix, so this will no longer be necessary.
