### ISSUE TITLE
Ambiguous Note

### ISSUE THREAD

**Issue by angusjlowe** [FreeCodeCamp/FreeCodeCamp#9914]
#### Challenge Name

https://www.freecodecamp.com/challenges/manipulating-complex-objects

#### Issue Description

Note reads "...place a comma in between every object in the array, unless it is the last object in the array" which is slightly misleading: it should read "...place a comma in between every object in the array" or "place a comma _after_ every object in the array, unless it is the last object in the array". 

#### Browser Information

* Browser Name, Version: n/a
* Operating System: n/a
* Mobile, Desktop, or Tablet: n/a 

#### Your Code

```js
 
```

**Comment by raisedadead** [comment]
@angusjlowe thanks for reporting

To contributors:

The below text:
> **Note**
> You will need to place a comma in between every object in the array, unless it is the last object in the array

should be changed to this:
> **Note**
> You will need to place a comma after every object in the array, unless it is the last object in the array.

The code can be found here:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4367

#### Please go through the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).
#### You do not need to ask any permission to work on this, just ensure that you have not contributed to free code camp's codebase earlier.
#### If you need any assistance hit us up in the the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors), we will be happy to help.

Thanks and happy fixing.

**Comment by agrullon95** [comment]
Hey, I would like to help with this issue if it's still up for grabs. This would be my first contribution.
