### ISSUE TITLE
Images should be made clickable on Shop page

### ISSUE THREAD

**Issue by Kallaway** [FreeCodeCamp/FreeCodeCamp#9918]
Here is the link to the page: https://www.freecodecamp.com/shop

#### Issue Description

For better UI, I think this page would benefit from having links not only on Buttons, but also on images themselves. I've found myself repeatedly opening links in new tabs - to look at later, and to my surprise the images were opened, not the links, which was something I expected (learnt behaviour from other sites).

I wonder if I can make the change, if you decided it's needed :) Would love to help out!

**Comment by raisedadead** [comment]
I feel it wont hurt, and this is something many would be used to. As long as we keep the links same as those on the buttons.

However this definitely needs @QuincyLarson's vote.

**Comment by dhcodes** [comment]
While we're thinking aloud, could I recommend a basic grid--5x2 or 4x4--of the items in the shop, at least as a media query for larger displays (greater than 1280px)?

**Comment by raisedadead** [comment]
@dhcodes thanks a lot for the advice but if you notice the single column layout is something that we have embraced since long for all static pages as a simple design ideology, this is something I am guessing makes us different from others.

It centralizing the user's focus on one thing at a time (with lots of non-distracting white space around the focus objects).

**Comment by BerkeleyTrue** [comment]
Let's add this 👍

**Comment by dhcodes** [comment]
@raisedadead I see, probably for the better.

**Comment by Kallaway** [comment]
I will take a crack at this tonight, if you don't mind! :)

**Comment by BerkeleyTrue** [comment]
@Kallaway Thanks! Make sure to include the appropriate google analytics functions as well.

**Comment by QuincyLarson** [comment]
@dhcodes @Kalcode so you mean clicking the image will be the same as clicking the button? That should be OK. 

@dhcodes we could consider using a fancier layout, but pretty much every decision should be driven through A/B tests here. I've already made some minor changes to the shop based on tests.

**Comment by Kalcode** [comment]
@QuincyLarson think you...randomly included me is this. Weird. 

Though reading the topic I would say the buttons are strange there. I believe the general standard is making them a big link. Like a border box on the whole element that you can click. 

Like so:
http://imgur.com/a/rKw04  

It would also make the offers flow it bit better. 

Thats my 2 cents about a topic I was randomly invited to. Good luck!

**Comment by dhcodes** [comment]
@kalcode, Quincy meant to reference @kallaway.

Thanks for the explanation. Makes sense @QuincyLarson

**Comment by DC4life** [comment]
Thank you thank you very much

On July 27, 2016, at 11:12 PM, Dylan H <notifications@github.com> wrote:

@kalcode, Quincy meant to reference @kallaway.

Thanks for the explanation. Makes sense @QuincyLarson

**Comment by QuincyLarson** [comment]
@Kallaway @dhcodes we definitely need to keep the button. Please don't change the UI (since I've already A/B tested it) - just make the images clickable. If you want to change the UI, please create the new HTML+CSS we can put use this for future A/B tests.

**Comment by dhcodes** [comment]
@Kallaway are you working on this or do you mind if I take a swing?

**Comment by dhcodes** [comment]
@QuincyLarson @BerkeleyTrue So I went ahead and made these changes locally with the GA intact and have the PR ready to go, but I have a question. The Amazon book links open in a new tab whereas the other links (audible, digital ocean, namecheap) do not. Should I make them each open in a new tab or leave them as-is?

**Comment by BerkeleyTrue** [comment]
They should behave the same as the other links

**Comment by dhcodes** [comment]
Do you mean?
a. the images should be linked the same as the current links (some opening in a new tab and some not)
b. make all links open in a new tab?

**Comment by BerkeleyTrue** [comment]
a

**Comment by dhcodes** [comment]
Okay. PR forthcoming.
