### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls has an issue

### ISSUE THREAD

**Issue by Wartz** [FreeCodeCamp/freecodecamp#992]
The line

    Give the text input in your form the class "form-control".

on the left has a styling issue. The words "in your form the class" shouldn't be red. Looks like a missing closing </code> tag?

Link to screenshot. http://i.imgur.com/pJmNN5B.png

**Comment by QuincyLarson** [comment]
Great find. I'll push a fix shortly.
