### ISSUE TITLE
Replace instances of the old wiki with appropriate links to the forum.

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#9923]
These need to be replaced by the appropriate forum post.

https://github.com/FreeCodeCamp/FreeCodeCamp/search?l=json&q=wiki&utf8=%E2%9C%93
https://github.com/FreeCodeCamp/FreeCodeCamp/search?l=markdown&q=wiki&utf8=%E2%9C%93
https://github.com/FreeCodeCamp/FreeCodeCamp/search?l=jade&q=wiki&utf8=%E2%9C%93

Help button should link to the appropriate forum article
![skitch](https://cloud.githubusercontent.com/assets/6775919/17188986/60fade72-53f4-11e6-9db0-4ac93a53b101.png)

**Comment by alanbares** [comment]
I'll work on this.

**Comment by DC4life** [comment]
Thank you so much lcm831cjr4ever4life@gmail.com and larrynscDC4life@gmail.com if I can merge them it will be great....

On July 27, 2016, at 7:11 PM, Alan Bares <notifications@github.com> wrote:

I'll work on this.

**Comment by karanjthakkar** [comment]
@alanbares Are you still working on it? Or can I fix this up?

**Comment by alanbares** [comment]
@karanjthakkar I believe someone made a PR and fixed it already.

**Comment by hallaathrad** [comment]
That one from the screen capture was fixed by @atjonathan with https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10010

Was going to fix this but I could not find any occurrences.
Closing as it seems to be resolved.
