### ISSUE TITLE
Add a caret symbol to connect-mongo version

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/FreeCodeCamp#9925]
A caret symbol, `^` needs to be added [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/package.json#L46). So the result should look like this:
`"connect-mongo": "^1.3.2",`.
Please review [**Contribution Guidelines**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before opening a PR, thank you!

**Comment by HKuz** [comment]
Hi there - can I take this one? I'm new to contributing to FCC and this issue seems like a great way to get everything set up and working properly to help out more in the future.
