### ISSUE TITLE
Question mark in value of alt-attribute leads to failed test

### ISSUE THREAD

**Issue by jonsensberger** [FreeCodeCamp/FreeCodeCamp#9927]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22Can%20i%20haz%20webpagez%3F%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.

The third testing-spec, **Your image element must have an alt attribute.** of this Challenge breaks, as soon as the user puts a question-mark into the value of the alt-attribute.
Removing the question mark leads to a instant pass.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="Can i haz webpagez?">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by erictleung** [comment]
@jonsensberger thanks for the issue. Yes, it appears that the test needs to account for question marks as well.

[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/9ee1d1beecaedf22819e2ab9fe6d8d33ba1e1c02/seed/challenges/01-front-end-development-certification/html5-and-css.json#L1164) needs ot be changed.

The regex should be changed from

```diff
- /alt\\s*?=\\s*?(\\\"|\\')[\\s\\w\\.\\,\\!]+?(\\\"|\\')/
+ /alt\\s*?=\\s*?(\\\"|\\')[\\s\\w\\.\\,\\!\\?]+?(\\\"|\\')/
```

**Comment by dhcodes** [comment]
I'll fix this one.

**Comment by traisen** [comment]
Hi - Didn't work with  - in alt text either

**Comment by dhcodes** [comment]
@traisen yeah, there are all sorts of special characters it doesn't work with like (, ), *, etc. Maybe we should change the Regex to accept any characters. I'm not sure

**Comment by erictleung** [comment]
@dhcodes in that case, maybe we should just use the wildcard character to make it flexible.

**Comment by traisen** [comment]
Changing to accept any character might save you answering post ;)

What is the regex that HTML uses to parse alt-text? That would be the best
to use.
What I found was there is a length limit, but seems all characters are
allowed. And testing, if too long it just chops off the extra characters.

**Comment by dhcodes** [comment]
But then I need to do an amend... NOOOOO j/k I need the practice.

**Comment by traisen** [comment]
(off topic) I'm curious: how you ended up working on the editor?

**Comment by dhcodes** [comment]
@traisen I'm not sure what you mean, but this isn't really the place for conversations. Look me up on the (Gitter chat)[https://gitter.im/FreeCodeCamp/FreeCodeCamp] and send me an @ mention or a PM and we can talk

**Comment by LodeScreen42** [comment]
I have a confirmation of similar symptoms while my alt attributes should be perfectly legal.  This thread describes what I am experiencing.
(Mozilla Firefox 47.0.1; Win10(x64)

My code:
`<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>

  .red-text {

    color: red;

  }

​

  h2 {

    font-family: Lobster, Monospace;

  }

​

  p {

    font-size: 16px;

    font-family: Monospace;

  }

</style>

​

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="Curious kitten is looking upside-down.">

​

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

​`

**Comment by Locheed** [comment]
Hyphen ( - ) also breaks it. Regex fix to accept any character would be good.
@LodeScreen42 That's your problem. Remove hyphen.

**Comment by dhcodes** [comment]
@Locheed @LodeScreen42 I changed the Regex to accept any character so it should be good to go once my PR gets merged and posted.

**Comment by duendwang** [comment]
Hyphen broke it for me too just now.
