### ISSUE TITLE
link on http://www.freecodecamp.com/jobs to those who have jobs (Many Already Have) is broken

### ISSUE THREAD

**Issue by MetaCoderHirschl** [FreeCodeCamp/freecodecamp#993]
this message 
![jobslinkinerr](https://cloud.githubusercontent.com/assets/5752096/8258274/dd230bf4-1670-11e5-9dc6-f0cc460723d7.png)

if from inCognito window -- log into LinkedIn get this:

![errincognito](https://cloud.githubusercontent.com/assets/5752096/8258331/4aaedd74-1671-11e5-8a31-59fe5634f060.png)

**Comment by QuincyLarson** [comment]
Thanks for spotting this. We'll push a fix shortly.
