### ISSUE TITLE
Some one can help me to identify what is wrong. (changing font size of an element)

### ISSUE THREAD

**Issue by Abayo** [FreeCodeCamp/FreeCodeCamp#9933]
![changing stlye issue](https://cloud.githubusercontent.com/assets/20681465/17206809/d41f7558-54b1-11e6-963f-0508af2d8c23.PNG)
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20text%20kitty%20ipsm%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3CP%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p{
    font-size: 16px;
  }
</style>
<h2 class="red-text">CatPhotoApp</h2>
<p class="red-text">Kitty ipsum text kitty ipsm dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<P>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by jacobsteenhuysen** [comment]
i have the same problem.

**Comment by musekwa** [comment]
I've just encountered the same problem. Can someone help?

**Comment by robbiegod** [comment]
@musekwa @jacobsteenhuysen  post your code somewhere.  In the original example above it might be something as simple as that last "<P>" is capitalized but in the stylesheet is references a lowercase 'p'.  If you change that lowercase so everything matches, then that should fix it.  i passed the test.

**Comment by musekwa** [comment]
Hello dear robbiegod, here is the code:
![image](https://cloud.githubusercontent.com/assets/19254270/17312021/e95bf62a-584f-11e6-9713-7422c6e06174.png)

I've tried to change the <p> from lowercase to upper one, but it couldn't pass

**Comment by musekwa** [comment]
Finally, it worked. I was mispelling the "font-size" to "fonte-size"...

**Comment by abayo-luc** [comment]
@musekwa @jacobsteenhuysen @robbiegod I hope you all kept coding, and now look back and laugh at this 😀 and also be proud that you did not quit!
