### ISSUE TITLE
palindrome

### ISSUE THREAD

**Issue by Annemariede** [FreeCodeCamp/FreeCodeCamp#9934]
On the Palindrome challenge, one of the test results:

palindrome("1 eye for of 1 eye.") should return false.

But I get it as true . If I remove the spaces, ones and the full stop it is a palindrome.
I tested it in excel to change the letters around and it is the same.

Is this correct or am I missing something?

**Comment by qmikew1** [comment]
That's not a palindrome.
Compare:
```
//1eyeforof1eye
//eye1forofeye1
```
*You'll need to remove all non-alphanumeric characters (**punctuation, spaces and symbols**) and turn everything lower case in order to check for palindromes.*

[help](https://gitter.im/FreeCodeCamp/Help) is a great place for discussion on stuff like this.

**Comment by raisedadead** [comment]
@Annemariede thanks for reporting but the test case is correct. Please refer the explanation above.
@qmikew1 thanks.

happy coding.
