### ISSUE TITLE
BETA TEST - Logon Using Linkedin Fails on FreeCodeCamp.org

### ISSUE THREAD

**Issue by ESOComputing** [FreeCodeCamp/freecodecamp#994]
![screenshot - 06192015 - 10 12 41 am](https://cloud.githubusercontent.com/assets/10407472/8258713/fe17203e-166b-11e5-87f7-698ba2f989a8.png)

When attempting logon authentication via LinkedIn, invalid redirect_uri. URL doesn't match API key.

**Comment by BerkeleyTrue** [comment]
Looks like @QuincyLarson Has fixed this. Thanks!
