### ISSUE TITLE
Use Conditional Logic with If Statements isssues

### ISSUE THREAD

**Issue by coolsuper101** [FreeCodeCamp/FreeCodeCamp#9942]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourTrueOrFalse(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20it's%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20it's%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Afunction%20trueOrFalse(wasThatTrue)%20%7B%0A%0A%20%20if%20(false)%20%7B%0A%20%20%20%20return%20%22No%2C%20that%20was%20false%22%3B%0A%0A%20%20%7D%0A%20%20if%20(true)%0A%20%20%20%7B%0A%20%20%20%20return%20%22Yes%2C%20that%20was%20true%22%3B%0A%20%20%0A%20%20%7D%0A%20%20%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtrueOrFalse(false)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This is the only way I  can get the most 4/5 ticks 
My code:
```javascript

// Example
function ourTrueOrFalse(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
function trueOrFalse(wasThatTrue) {

  if (false) {
    return "No, that was false";

  }
  if (true)
   {
    return "Yes, that was true";
  
  }
  
// Only change code below this line.
  
  
  
  // Only change code above this line.

}

// Change this value to test
trueOrFalse(false);

```

**Comment by erictleung** [comment]
@coolsuper101 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: use the parameter `wasThatTrue` in your conditional statements. Happy coding!
