### ISSUE TITLE
The solution is not being stored in an overnight.

### ISSUE THREAD

**Issue by araujojeff** [FreeCodeCamp/FreeCodeCamp#9943]
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  return arr;
}

bouncer([7, "ate", "", false, 9]);

```

**Comment by erictleung** [comment]
They may appear not to be stored overnight possibly because you are using different computers. However, your solution is stored in a database because if you go to your FreeCodeCamp profile, you can see your solution for "Falsy Bouncer" there https://www.freecodecamp.com/araujojeff

**Comment by araujojeff** [comment]
Yes! Is this! Tks @erictleung  =)
