### ISSUE TITLE
Challenge way to easy

### ISSUE THREAD

**Issue by FatKoala** [FreeCodeCamp/FreeCodeCamp#9944]
Challenge [Slasher Flick](https://www.freecodecamp.com/challenges/slasher-flick) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.
This challenge can be solved in one line of code. Is it intended that way? If yes than ok. If not, note that suggested method is actually a solution.

My code:
```javascript

function slasher(arr, howMany) {
  // it doesn't always pay to be first
  var arr2 = arr.slice(howMany);
  return arr2;
}

slasher([1, 2, 3], 2);

```

**Comment by raisedadead** [comment]
I somewhat tend to agree, not sure if we should change the verbiage and add more tests though.
@erictleung thoughts?

**Comment by erictleung** [comment]
@raisedadead I also somewhat agree that this is pretty easy. We could add in some constraints like filter out non-numbers and then start chopping off elements. It would up the challenge a little bit.

**Comment by raisedadead** [comment]
This is a required challenge, we can have a fair amount of toughness, at least in increment of the previous

**Comment by BKinahan** [comment]
Here's a rough draft of a frankenSplice challenge, feedback appreciated!

```js

// Use slice() and splice() to insert the elements of the first array into the second, starting at index n of the second array.
// Optional objective: Do not mutate the input arrays.

// Solution (with optional objective)
const frankenSplice = (arr1,arr2,n) => {
	let r = arr2.slice();
	for (let i = 0; i<arr1.length;i++){
		r.splice(n+i,0,arr1[i]);
	}
	return r;
};

a = [1,2,3];
b = ["c","d","e","f"];

frankenSplice(a,b,1); // [ 'c', 'd', 1, 2, 3, 'e', 'f' ]
console.log(a); // [ 1, 2, 3 ]
console.log(b); // [ 'c', 'd', 'e', 'f' ] // Input arrays remain intact
```

**Comment by raisedadead** [comment]
`mutate` maybe little tough on non-native speakers?

How about?
> The input arrays should still remain the same

**Comment by BKinahan** [comment]
Oh yeah, this is not final language at all, just brainstorming about the requirements and difficulty of this potential challenge. 

Is it feasible to have multiple tests check that various input arrays have not been changed by the function? Or does that make the test code overly complex?

I do think this is a good opportunity to reinforce that some array methods mutate arrays even outside the function scope, even if it's described in simpler language, and that requirement means users will have to use *both* slice and splice to solve it fully.

**Comment by raisedadead** [comment]
Tests are basically asserts. So wecan have one assert check all the input arrays. not complex, but lengthy one. To be clear this one will need a `assert.deepEqual` to check the arrays and chain them with logical `AND`

Yup I agree to the second point as well
> I do think this is a good opportunity to reinforce that some array methods mutate arrays even outside the function scope, even if it's described in simpler language, and that requirement means users will have to use both slice and splice to solve it fully.

**Comment by BKinahan** [comment]
Finally got my replacement working now that `tail`s are (mostly) working in `staging` again! Writing the PR now..

**Comment by JBPereira** [comment]
BKinahan my code is equal to yours and it outputs everything as supposed and yet it tells me that the variables are changed... did you pass this with that code?

**Comment by JBPereira** [comment]
``` javascript 
function frankenSplice(arr1, arr2, n) {
  // It's alive. It's alive!
  var ans=arr2.slice();
  for(i=0;i<arr1.length;i++){
  ans.splice(n+i,0,arr1[i]);
  }
  console.log(ans);
  console.log(arr1);
  console.log(arr2);
  return ans;
}
