### ISSUE TITLE
Arr only passes in first array

### ISSUE THREAD

**Issue by astro8891** [FreeCodeCamp/FreeCodeCamp#9945]
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=%0Afunction%20uniteUnique(arr)%20%7B%0A%20%20console.log(arr)%3B%0A%7D%0A%0AuniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function uniteUnique(arr) {
  console.log(arr);
}

uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);

```

**Comment by erictleung** [comment]
@astro8891 thanks for the issue but the challenge setup is correct. Please read the link to the [arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) to understand why. Happy coding!
