### ISSUE TITLE
[beta]Map aside not closing on challenge selection (mobile)

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#9947]
In the map aside, clicking on a challenge does not close the map or drop down menu. The user cannot see that the challenge has arrived. 

The challenge is still rendered

Mobile: (iOS)

**Comment by BerkeleyTrue** [comment]
How does closing the map aside when ever a challenge is updated sound?

**Comment by atjonathan** [comment]
Yeah I think that sounds good

**Comment by SamAI-Software** [comment]
> How does closing the map aside when ever a new challenge is loaded sound?

Totally make sense for small screens.
But for most of campers with big screens it might lead to poor UX, when they are trying to find the certain challenge to recap the solution, that they used there, so they can use that method/function/logic again in a current challenge or project.

**Comment by BerkeleyTrue** [comment]
@SamAI-Software mobile/tablet users account for a very small percent of our users. Most people are on desktop.

I personally like that the map drawer stays open while switching between challenges, but I'm not a good representation of a typical user.

Then there is the argument of what was the behavior before reactification. It was to refresh to page, essentially closing the map drawer.

**Comment by raisedadead** [comment]
+1 for closing the aside after a challenge is loaded (to remedy the immediate problem we have).

And yeah, while I can see what Sam means, and is important too. So maybe a bit off this thread how about something not like the sidecar, but a react component that is rendered within the challenges editor and is collapsible? Being in react now, I think we do not need the iframe for this?

I good point of inspiration would be https://github.com/buunguyen/octotree, I use this all the time.

Well  might be completely wrong too.

**Comment by SamAI-Software** [comment]
Also the easy solution would be to close aside map only if window width is less than 800px or so.

**Comment by BerkeleyTrue** [comment]
For now let's go with the expected behavior of closing the map on challenge load. We can discuss new UX in another issue

**Comment by raisedadead** [comment]
Agreed.
