### ISSUE TITLE
[beta] Map links don't show pointer on hover

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9948]
On the map, if I hover my cursor over a link, it shows the text selection cursor, not the clicker cursor.

**Comment by bishoo** [comment]
Ok

**Comment by SamAI-Software** [comment]
I get both pointers and text selectors in Chrome. Same with a big map (full page).

![cursor](https://cloud.githubusercontent.com/assets/16253583/17245747/2055205c-55b2-11e6-96fd-4b6382b26ad7.jpg)
