### ISSUE TITLE
[beta] CSS issues with HTML challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9955]
#### Challenge Name
Any HTML challenge (http://beta.freecodecamp.com/en/challenges/html5-and-css/say-hello-to-html-elements)

#### Issue Description
![](https://www.evernote.com/l/Ar-DPWPx4TVO2ZEI6nrGDvw052xu7wswyk0B/image.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by SamAI-Software** [comment]
1366x768
![betacss](https://cloud.githubusercontent.com/assets/16253583/17242809/7109d498-55a3-11e6-8001-3f05b187626b.jpg)
