### ISSUE TITLE
[beta] Reset button does not work on HTML challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9956]
#### Challenge Name
http://beta.freecodecamp.com/en/challenges/html5-and-css/say-hello-to-html-elements

#### Issue Description
When I click the "reset" button, then confirm in the toast that pops up, it still doesn't clear my code.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by SamAI-Software** [comment]
> When I click the "reset" button, then confirm in the toast that pops up, it still doesn't clear my code.

Works for me in Chrome. It cleans the code, but doesn't set the preview (right screen) to the original one.
