### ISSUE TITLE
[beta] iPhone preview doesn't update on challenge change until tests run

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9959]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9981
