### ISSUE TITLE
BETA TEST - Landing Page - Button/Link Issues

### ISSUE THREAD

**Issue by ESOComputing** [FreeCodeCamp/freecodecamp#996]
The button labeled "Go to my next challenge" generates the following browser error message "Redirect Loop" 

![screenshot - 06192015 - 10 24 15 am](https://cloud.githubusercontent.com/assets/10407472/8258994/088eeec8-166e-11e5-84e0-bac1d8cfaecc.png)

Also, the button immediately below labeled "My nonprofit needs coding help" generates errors within the page when clicked if you use the browser back button immediately following the above error. If it is the initial visit to the landing page and you click the nonprofit button no error is generated. See below.

![screenshot - 06192015 - 10 32 36 am](https://cloud.githubusercontent.com/assets/10407472/8259062/a1821b6e-166e-11e5-9592-c76b45f59140.png)

**Comment by BerkeleyTrue** [comment]
This has been fixed.

Happy Coding!
