### ISSUE TITLE
End-to-End tests of beta on Chrome

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9962]
Here is a full End-to-End Testing checklist. You should go through all of these tasks to verify everything works. If something doesn't, create an issue (preferably with a screenshot) and tag it "beta" and specify which browser you were using. 

Go through the following test plan and click the boxes below as you complete each task. Once all the boxes below are checked off, you can close this issue.

  - [ ] As a returning user
    - [ ] signout
    - [ ] sign in using email
    - [ ] sign in using GitHub
    - [ ] sign in using legacy oauth options
    - [ ] view code portfolio and settings page
      - [ ] streak is visible
      - [ ] points are showing up in upper right hand corner
      - [ ] completed challenges are in the right places, and accessible
      - [ ] I can add LinkedIn/Twitter to my profile
      - [ ] I can activate night mode
      - [ ] I can make my solutions private
      - [ ] I can delete my account
      - [ ] I can update my email settings
      - [ ] I can change and confirm my email address
    - [ ] video challenges
      - [ ] completing a video challenge increment points and takes me to the next challenge
      - [ ] the video shows up and can be played
      - [ ] I can answer the true false questions
    - [ ] map
      - [ ] I can expand and collapse it
      - [ ] I can expand and collapse individual sections
      - [ ] the fullscreen button works
      - [ ] the map collapse when I click the x close button
      - [ ] I can use the search box to filter challenges
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
      - [ ] completing a challenge increases my brownie points
      - [ ] completing the same challenge a second time does not increase my brownie points
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time
  - [ ] As an unauthenticated user
    - [ ] video challenges
      - [ ] completing a video challenge takes me to the next one
      - [ ] the video shows up and can be played
      - [ ] I can answer the true false questions
    - [ ] map
      - [ ] I can expand and collapse it
      - [ ] I can expand and collapse individual sections
      - [ ] the fullscreen button works
      - [ ] the map collapse when I click the x close button
      - [ ] I can use the search box to filter challenges
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent challenge.
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time

**Comment by SamAI-Software** [comment]
I'll go for it

**Comment by alayek** [comment]
Testing done by me on Chromium Version 52.0.2743.82 (64-bit) on Linux Mint. I will keep on updating status of each test as I progress.

---

  - [ ] As a returning user
    - [ ] signout
    - [ ] sign in using email
    - [ ] sign in using GitHub
    - [ ] sign in using legacy oauth options
    - [ ] view code portfolio and settings page
      - [ ] streak is visible
      - [ ] points are showing up in upper right hand corner
      - [ ] completed challenges are in the right places, and accessible
      - [ ] I can add LinkedIn/Twitter to my profile
      - [ ] I can activate night mode
      - [ ] I can make my solutions private
      - [ ] I can delete my account
      - [ ] I can update my email settings
      - [ ] I can change and confirm my email address
    - [ ] video challenges
      - [ ] completing a video challenge increment points and takes me to the next challenge
      - [ ] the video shows up and can be played
      - [ ] I can answer the true false questions
    - [ ] map
      - [ ] I can expand and collapse it
      - [ ] I can expand and collapse individual sections
      - [ ] the fullscreen button works
      - [ ] the map collapse when I click the x close button
      - [ ] I can use the search box to filter challenges
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
      - [ ] completing a challenge increases my brownie points
      - [ ] completing the same challenge a second time does not increase my brownie points
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time
  - [ ] As an unauthenticated user
    - [X] video challenges
      - [X] completing a video challenge takes me to the next one
      - [X] the video shows up and can be played
      - [X] I can answer the true false questions
    - [ ] map
      - [X] I can expand and collapse it
      - [X] I can expand and collapse individual sections
      - [X] the fullscreen button works
      - [X] the map collapse when I click the x close button
      - [X] I can use the search box to filter challenges (Comment: if the challenge is collapsed under a topic, the topic name appears in filtered result and you have to expand the topic to view the thing you had searched for)
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent challenge.
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time

**Comment by Bouncey** [comment]
Are the on-boarding challenges new? I'm not being taken to the challenge I was last attempting (Recipe Box/Data-Viz), instead I am being on-boarded. 

Other challenges in my profile have a solution

**Comment by alayek** [comment]
@Bouncey are you accessing the Beta site or main site?

**Comment by Bouncey** [comment]
@alayek main site

**Comment by Bouncey** [comment]
As I complete them, my brownie points do  not increment, which would be correct I guess

**Comment by alayek** [comment]
@Bouncey these testings are to be done on the beta [site](beta.freecodecamp.com), which Berkeley has just refactored with React components.

**Comment by Bouncey** [comment]
And I am not having to open up links to github and gitter to progress

**Comment by Bouncey** [comment]
I thought the react branch had been merged?

**Comment by Bouncey** [comment]
just re-read core team chat, my bad

**Comment by bugron** [comment]
Browser: SRWare Iron 51.0.2700.0 (64-bit)
OS: Windows 10
Anything that is **NOT** listed below works as expected.
- [x] As a returning user
  - [ ] sign in using legacy oauth options (**haven't tried**)
  - [ ] view code portfolio and settings page
    - [ ] I can add LinkedIn/Twitter to my profile (**haven't tried**)
    - [ ] I can activate night mode (**button does not do anything when I click**)
    - [ ] I can delete my account (**button does not do anything when I click**)
  - [x] map (see https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9999 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9998 for issues)
  - [ ] slide challenges
    - [ ] I can navigate forward and backward (**this needs a separate GitHub issue**)
  - [ ] html challenges
    - [ ] when I return to a challenge, my previous solution is already in the code editor (**my solution is not in the editor, it is saved in localStorage though**)
  - [ ] bootstrap challenges
    - [ ] font awesome is available
  - [ ] jQuery, AJAX challenges
    - [ ] animate.css is available
  - [x] JavaScript and algorithm challenges
    - [x] infinite loop protection works (see https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10000)
  - [ ] Project challenges (the ones that currently have video explanations)
    - [ ] I can check checkboxes (**there are no checkboxes, just an unordered list**)
    - [ ] when I return to the challenges, I can check the checkboxes a second time (**there are no checkboxes, just an unordered list**)
- [x] As an unauthenticated user
  - Same issues above
