### ISSUE TITLE
[beta] End-to-End Testing Android Chrome

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#9965]
Here is a full End-to-End Testing checklist. You should go through all of these tasks to verify everything works. If something doesn't, create an issue (preferably with a screenshot) and tag it "beta" and specify which browser you were using. 

Go through the following test plan and click the boxes below as you complete each task. Once all the boxes below are checked off, you can close this issue.

- Android Chrome
  - [ ] As a returning user
    - [ ] signout
    - [ ] sign in using email
    - [ ] sign in using GitHub
    - [ ] sign in using legacy oauth options
    - [ ] view code portfolio and settings page
      - [ ] streak is visible
      - [ ] points are showing up in upper right hand corner
      - [ ] completed challenges are in the right places, and accessible
      - [ ] I can add LinkedIn/Twitter to my profile
      - [ ] I can activate night mode
      - [ ] I can make my solutions private
      - [ ] I can delete my account
      - [ ] I can update my email settings
      - [ ] I can change and confirm my email address
    - [ ] video challenges
      - [ ] completing a video challenge increment points and takes me to the next challenge
      - [ ] the video shows up and can be played
      - [ ] I can answer the true false questions
    - [ ] map
      - [ ] I can expand and collapse it
      - [ ] I can expand and collapse individual sections
      - [ ] the fullscreen button works
      - [ ] the map collapse when I click the x close button
      - [ ] I can use the search box to filter challenges
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
      - [ ] completing a challenge increases my brownie points
      - [ ] completing the same challenge a second time does not increase my brownie points
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time
  - [ ] As an unauthenticated user
    - [ ] video challenges
      - [ ] completing a video challenge takes me to the next one
      - [ ] the video shows up and can be played
      - [ ] I can answer the true false questions
    - [ ] map
      - [ ] I can expand and collapse it
      - [ ] I can expand and collapse individual sections
      - [ ] the fullscreen button works
      - [ ] the map collapse when I click the x close button
      - [ ] I can use the search box to filter challenges
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent challenge.
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time

**Comment by atjonathan** [comment]
I will take this on!

**Comment by atjonathan** [comment]
**Jonathan's Tests**

- Android Chrome
  - [ ] As a returning user
    - [ ] signout
    - [ ] sign in using email
    - [ ] sign in using GitHub
    - [ ] sign in using legacy oauth options
    - [ ] view code portfolio and settings page
      - [ ] streak is visible
      - [ ] points are showing up in upper right hand corner
      - [ ] completed challenges are in the right places, and accessible
      - [ ] I can add LinkedIn/Twitter to my profile
      - [ ] I can activate night mode
      - [ ] I can make my solutions private
      - [ ] I can delete my account
      - [ ] I can update my email settings
      - [ ] I can change and confirm my email address
    - [ ] video challenges
      - [ ] completing a video challenge increment points and takes me to the next challenge
      - [ ] the video shows up and can be played
      - [ ] I can answer the true false questions
    - [ ] map
      - [ ] I can expand and collapse it
      - [ ] I can expand and collapse individual sections
      - [ ] the fullscreen button works
      - [ ] the map collapse when I click the x close button
      - [ ] I can use the search box to filter challenges
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
      - [ ] completing a challenge increases my brownie points
      - [ ] completing the same challenge a second time does not increase my brownie points
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time
  - [ ] As an unauthenticated user
    - [ ] video challenges
      - [ ] completing a video challenge takes me to the next one
      - [ ] the video shows up and can be played
      - [ ] I can answer the true false questions
    - [ ] map
      - [ ] I can expand and collapse it
      - [ ] I can expand and collapse individual sections
      - [ ] the fullscreen button works
      - [ ] the map collapse when I click the x close button
      - [ ] I can use the search box to filter challenges
    - [ ] static pages
      - [ ] I can navigate to the about view from the navbar
      - [ ] I can navigate to the shop view from the navbar
      - [ ] I can navigate to my profile from the navbar
      - [ ] I can navigate to the map from about page
      - [ ] Clicking the Free Code Camp logo in the nav bar takes me to my most recent challenge.
    - [ ] slide challenges
      - [ ] I can navigate forward and backward
      - [ ] clicking open link in new tab button unlocks "go to next tab" button and opens link in new tab
      - [ ] When I reach the last slide, and click the finish challenge button it takes me to the next challenge
    - [ ] html challenges
      - [ ] code in style tag to make sure CSS works
      - [ ] challenges can still be completed
      - [ ] challenges cannot be completed until all tests have passed
      - [ ] when I return to a challenge, my previous solution is already in the code editor
      - [ ] the form related challenges work, and the cat photo app's submit action works
    - [ ] bootstrap challenges
      - [ ] bootstrap is availble
      - [ ] font awesome is available
    - [ ] jQuery, AJAX challenges
      - [ ] jquery is available
      - [ ] animate.css is available
    - [ ] JavaScript and algorithm challenges
      - [ ] infinite loop protection works
      - [ ] I can disable infinite loop protection
      - [ ] The code output box works and also shows console.log activity
    - [ ] Project challenges (the ones that currently have video explanations)
      - [ ] the video plays properly
      - [ ] I can check checkboxes
      - [ ] when I return to the challenges, I can check the checkboxes a second time
