### ISSUE TITLE
[beta] Map doesn't show challenge progress properly when clicking on a freeCodeCamp homepage link

### ISSUE THREAD

**Issue by SamAI-Software** [FreeCodeCamp/FreeCodeCamp#9968]
* Browser Name, Version: Chrome
* Operating System: Win7-x64
* Mobile, Desktop, or Tablet: Laptop

It might be an issue with a link to [homepage](beta.freecodecamp.com), when I press there, it always sends me to the [first challenge](http://beta.freecodecamp.com/en/challenges/join-the-free-code-camp-community/learn-how-free-code-camp-works) and my progress map is reset or even empty, but all my brownies are still with me.

![progressmap1](https://cloud.githubusercontent.com/assets/16253583/17244468/33ccb8e4-55ac-11e6-8031-a674087f1f43.jpg)

![progressmapempty](https://cloud.githubusercontent.com/assets/16253583/17244662/29d0feee-55ad-11e6-922d-897e21186e4b.jpg)

However, if I open the map in a full page (new tab), then my progress is shown (after a few seconds).

![progressmap](https://cloud.githubusercontent.com/assets/16253583/17244320/695400ea-55ab-11e6-93de-0b3ffeac9493.jpg)

And after that I can open the latest (or any other challenge) and I will see my real progress again.

![progressmap2](https://cloud.githubusercontent.com/assets/16253583/17244695/53399f2a-55ad-11e6-9a33-56122d2559c2.jpg)

And if I click to [homepage](beta.freecodecamp.com), it will again send me to the first challenge with empty progress.

**Comment by raisedadead** [comment]
This is a known issue #9735 , we need to add the progress, react rendering takes sometime with all sorts of reasons.

**Comment by SamAI-Software** [comment]
@raisedadead, I think it's the different problem. It doesn't load the progress at all (even after a long time) and it always sends me to the first challenge, when I click to the top-left **freeCodeCamp** link.

**Comment by raisedadead** [comment]
Oh that's strange, the HomePage should be redirecting to the current challenge.
