### ISSUE TITLE
[beta] Cannot login with email

### ISSUE THREAD

**Issue by SamAI-Software** [FreeCodeCamp/FreeCodeCamp#9969]
* Browser Name, Version: Chrome
* Operating System: Win7-x64
* Mobile, Desktop, or Tablet: Laptop

When trying to login with email, I'm getting
```diff
- Invalid username or password
```
![email1](https://cloud.githubusercontent.com/assets/16253583/17245352/542b6ffa-55b0-11e6-8822-46c86e2866af.jpg)

When trying to restore the password, I'm getting
```diff
- access token invalid
```

![email2](https://cloud.githubusercontent.com/assets/16253583/17245355/59bc2fae-55b0-11e6-95c9-1946e87f8c28.jpg)

The [main website](https://www.freecodecamp.com) works fine both login with email and reset password.
Note: I've tried main and beta with the same email address.

**Comment by raisedadead** [comment]
On the beta site you have to do a fresh sign up. Didn't see that on the OP. Is it the case?
I can sign-in and reset password after I created an account.

**Comment by atjonathan** [comment]
@raisedadead, same with me :+1:
