### ISSUE TITLE
Markup error

### ISSUE THREAD

**Issue by isomoar** [FreeCodeCamp/freecodecamp#997]
Challenge http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls has an issue. 
Seems there is some markup mistake:
![Alt text](https://www.evernote.com/l/AmFR2RpFKQJKEYA6UsRA9tLTP9hPmmXobisB/image.png)

**Comment by QuincyLarson** [comment]
Great find. I'll push a fix shortly.
