### ISSUE TITLE
[beta] Completed challenges don't display proper data on profile page

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9970]
[![https://gyazo.com/34f611dc15cbf4f756b835338504e63f](https://i.gyazo.com/34f611dc15cbf4f756b835338504e63f.png)](https://gyazo.com/34f611dc15cbf4f756b835338504e63f)

**Comment by SamAI-Software** [comment]
ref #9954

**Comment by raisedadead** [comment]
Closing as duplicate of the former.
