### ISSUE TITLE
[beta] CatPhotoApp iPhone is shown on top of the code editor

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9972]
[![https://gyazo.com/83ef1e61e7ed3afea42e76e7a2c93237](https://i.gyazo.com/83ef1e61e7ed3afea42e76e7a2c93237.png)](https://gyazo.com/83ef1e61e7ed3afea42e76e7a2c93237)

Reproduced on **Nexus 5X (Chrome Dev Tools)**

**Comment by BerkeleyTrue** [comment]
Is this still an issue?

**Comment by atjonathan** [comment]
@BerkeleyTrue, no this was fixed :+1:
