### ISSUE TITLE
[beta] Font awesome isn't displaying

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#9973]
[![https://gyazo.com/3c5fb2e561c36e6e6eda24a3036c2cab](https://i.gyazo.com/3c5fb2e561c36e6e6eda24a3036c2cab.png)](https://gyazo.com/3c5fb2e561c36e6e6eda24a3036c2cab)

[![https://gyazo.com/78f31285b957e2b64741a943774cc9c0](https://i.gyazo.com/78f31285b957e2b64741a943774cc9c0.png)](https://gyazo.com/78f31285b957e2b64741a943774cc9c0)

**Comment by alayek** [comment]
I faced the same issue on Google Chrome

---

![screenshot from 2016-07-29 20 55 21](https://cloud.githubusercontent.com/assets/5607371/17253552/dd77182c-55ce-11e6-8b6e-96fb7030ffdd.png)

**Comment by BerkeleyTrue** [comment]
@atjonathan Can you find all the challenges that require font-awesome?

**Comment by atjonathan** [comment]
@BerkeleyTrue:

[![https://gyazo.com/1721730876d47fced129825217219e84](https://i.gyazo.com/1721730876d47fced129825217219e84.png)](https://gyazo.com/1721730876d47fced129825217219e84)

**Comment by atjonathan** [comment]
@BerkeleyTrue, I'll make a PR to fix this.
