### ISSUE TITLE
[beta] Re-direct to /settings from non-react pages.

### ISSUE THREAD

**Issue by SamAI-Software** [FreeCodeCamp/FreeCodeCamp#9975]
The top-right buttons sometime link to **profile** page, but sometime to **settings** page.

* Browser: Chrome
* OS: Win7-x64
* Device: Laptop

In **beta** these buttons usually link to **settings** (but not always!).

![navbar2](https://cloud.githubusercontent.com/assets/16253583/17247198/d680b16c-55bb-11e6-817f-b5850b278c14.jpg)

***

Sometimes these buttons actually link to **profile** page. For example, if I open my profile page, then these buttons will link to my **profile**, not to the **settings**. Also sometimes when I open a new tab these buttons link to **profile**, sometimes to **settings**.
Didn't find the repeatable consequence yet.

![navbar3](https://cloud.githubusercontent.com/assets/16253583/17248121/6c498c68-55c2-11e6-920a-40044e9f2050.jpg)

**Comment by raisedadead** [comment]
I pointed out this in #9847 but as per @BerkeleyTrue we have changed the logic. Possibly to be closed.

**Comment by SamAI-Software** [comment]
@raisedadead the problem is that sometimes it links to **settings**, but sometimes it still links to **profile** page.

Btw, I do search for issues before posting a new one, but didn't find that issue :)

**Comment by raisedadead** [comment]
Lol that's because its closed, and yeah that's why mentioned that probably this will be closed, depends on how we want to define the behaviour, I think Berkeley will take a call on that.

**Comment by SamAI-Software** [comment]
Yeah, I see, so I edited the issue.

**Comment by SamAI-Software** [comment]
Also **about** link at the nav bar has very inconsistent behavior.
For example, when I'm on the **map page** or inside of the challenge:
- click to **about** page will open it in a **new** tab
- click to **shop** page will open it in the same tab
- click to **settings** page will open it in the same tab

When I'm on other pages, all links in nav bar will open in the same tab (including **about**).

**Comment by raisedadead** [comment]
Nice Catch!
The current site behaviour is and should be all navigation pages should open in same tab, except the forum (which of course should open in a new tab).

**Comment by raisedadead** [comment]
And regarding the profile icon and points, I think we should just make it uniform that they navigate to settings always as mention by Berkeley.
