### ISSUE TITLE
Change the name of "collapse all challenges" in a map menu (UX)

### ISSUE THREAD

**Issue by SamAI-Software** [FreeCodeCamp/FreeCodeCamp#9976]
For not native English speakers "collapse all" sounds like "delete all challenges", so they probably never click this button.

I was always wondering why do we need such a big button to destroy all challenge's progress until I found this step in a TODO testing list and only then I've discovered this great feature :)

I'm not a native speaker, so need help with a more appropriate word.
Possible variants:

- Hide all challenges
- Hide all sub-challenges
- Minify all challenges

**Comment by raisedadead** [comment]
> Hide all challenges

This is probably the best alternate.

**Comment by SamAI-Software** [comment]
But keep in mind that the meaning should stay the same as "collapse", because native English speakers are still the majority.

![lang](https://cloud.githubusercontent.com/assets/16253583/17248951/d4008e7e-55c7-11e6-9ad2-89cac70338ad.jpg)

**Comment by JuFisch** [comment]
I'd like to work on this for my first contribution

**Comment by dhcodes** [comment]
Go forth @JuFisch

**Comment by iamrudra** [comment]
@JuFisch - Are you still on it?

**Comment by raisedadead** [comment]
Marked as first-timer, @iamrudra you are assigned on one of the issues, lets keep this for some one else?

**Comment by iamrudra** [comment]
@raisedadead - Looking for `help wanted` led me here. It did not have `first-timers-only` when I put that comment. Will resolve the #10017 first and then look for another.

**Comment by raisedadead** [comment]
Great! @iamrudra thanks, looking forward to your contribution!

**Comment by Rlin415** [comment]
@raisedadead Could I take this one if @JuFisch is not on it anymore?

**Comment by raisedadead** [comment]
Unless, anyone has made a pull request, it's considered not claimed, @Rlin415 please go ahead.

**Comment by JuFisch** [comment]
Sorry for the delay, thanks for removing me. I'll try and find a new one! :)
