### ISSUE TITLE
[beta] Phone viewport improperly spaced with respect to code editor

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#9978]
The phone viewport is overlapping with editor in beta site.

![screenshot from 2016-07-29 19 05 17](https://cloud.githubusercontent.com/assets/5607371/17250000/0b1e51dc-55c0-11e6-9259-727e18c2b656.png)

I have tested this on other challenges too.

Browser: Google Chrome (latest) on Linux and Windows

**Comment by SamAI-Software** [comment]
ref #9955

**Comment by raisedadead** [comment]
Closing this in favor of the original report.
