### ISSUE TITLE
Two scroll bars on a map page

### ISSUE THREAD

**Issue by SamAI-Software** [FreeCodeCamp/FreeCodeCamp#9979]
I'm not sure if it's a bug or a new feature, but do we actually need two scroll bars?

![map](https://cloud.githubusercontent.com/assets/16253583/17249874/2088d2d4-55cc-11e6-8824-a58ef5d63c62.jpg)

***
Pros
- people without browser scroll bar will see that there is something more on the page (fixes well-known UX issue called "scroll stoppers")

Cons
- weird UI
- doesn't allow to use mouse scrolling on 70% of the page space (poor UX)

![map2](https://cloud.githubusercontent.com/assets/16253583/17250035/c28da23a-55cc-11e6-82ef-048faa68fd78.jpg)

***

If the new small scroll bar is a feature, then we can at least get rid of the big browser scroll bar on the right side for better UI.

**Comment by raisedadead** [comment]
Map is probably the most used feature, and IMHO we should leave the behaviour that is on the main site one scroll bar (on the extreme right).


![image](https://cloud.githubusercontent.com/assets/1884376/17250429/f33db95c-55c1-11e6-8c54-efa6b235e452.png)

**Comment by raisedadead** [comment]
Just to mention on smaller viewports (or any size window for that matter) this will give ample area for a user to scroll, vs the one with two scrolls.

**Comment by alayek** [comment]
I was about to report this :smile: 

Yeah, nested scrollbar is a strict no-no in web design

**Comment by sachinmour** [comment]
What is the state of this issue.. should we remove the scrollbar on the middle and enable scrollbar on the right...

**Comment by codetweetie** [comment]
Is this issue solved ? Atleast I don't see the double scrollbar on Firefox 48.0 (Ubuntu)

**Comment by SamAI-Software** [comment]
Seems like solved.
