### ISSUE TITLE
[beta] Preview pane out of sync with challenge code

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#9981]
The preview pane reflects changes if and only if the "Run Test" is triggered.

And as a result falls out of sync with the code in the code editor. I submitted a challenge and this is what the next challenge looks like

![screenshot from 2016-07-29 19 44 54](https://cloud.githubusercontent.com/assets/5607371/17251296/b9fa1010-55c5-11e6-89b3-a8e7861419c2.png)

This also happens mid-challenge. If you change CSS of some HTML element, it should immediately reflect that in the preview pane. Instead, it takes a <kbd>Ctrl</kbd> + <kbd>Enter</kbd> to trigger the rendering in the pane.

Browser: Google Chrome latest on Linux Mint

**Comment by BerkeleyTrue** [comment]
This is expected behavior. This prevents malformed code from freezing the preview/test iframes.
