### ISSUE TITLE
[beta] Code editor cannot display full seed code if it is large

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#9983]
No scrollbar here, and I cannot access the end of the code in the editor.

![screenshot from 2016-07-29 20 27 26](https://cloud.githubusercontent.com/assets/5607371/17252586/e7ca7002-55ca-11e6-91e1-e2d2862d6772.png)

Browser: Google Chrome latest on Linux Mint.

**Comment by dwd2010** [comment]
probably need to remove `overflow: hidden;` in body element style. that will be solve.

**Comment by dwd2010** [comment]
or in class="challenges-editor" could use `overflow-x: hidden; overflow-y: scroll;`.
