### ISSUE TITLE
[beta] Submitted solution not present on revisit

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#9984]
When code is submitted, and user goes to solve other problems; and decides to revisit the earlier challenge (from map page or hitting back button), the code in the editor should contain the solution.

However, I didn't find that to be the case.

This is what I am seeing before refresh 
![screenshot from 2016-07-29 20 34 47](https://cloud.githubusercontent.com/assets/5607371/17252870/ef46c3f2-55cb-11e6-904a-03e380b91e6b.png)

---

After refreshing the page, it comes back and preview pane also reflects that

![screenshot from 2016-07-29 20 34 56](https://cloud.githubusercontent.com/assets/5607371/17252899/112933f6-55cc-11e6-99c8-dffa81552ab2.png)

Browser: Google Chrome latest on Linux Mint

**Comment by raisedadead** [comment]
Confirmed.
