### ISSUE TITLE
Comment Issue

### ISSUE THREAD

**Issue by 321aislinn** [FreeCodeCamp/FreeCodeCamp#9985]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%20h1%20--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3C!--%20p%20--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!-- h1 -->
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
<!-- p -->

```

**Comment by 321aislinn** [comment]
The challenge is to create comments for the h1 and p elements, however, when I submit the above code it fails.

**Comment by dwd2010** [comment]
@321aislinn 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!
