### ISSUE TITLE
When I remove the google link for Lobster, the font don't change to Monospace

### ISSUE THREAD

**Issue by robertcorreas** [FreeCodeCamp/freecodecamp#999]
Challenge http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by QuincyLarson** [comment]
This works fine for me. Please show me your code. Are you doing this? 

    font-family: Lobster, Monospace;

**Comment by TheDoctorsLife** [comment]
+1 
Am seeing the same issue, doesn't seem to matter where I comment the code.
Related screenshots:
http://i.imgur.com/BoxJ9Fs.png
http://i.imgur.com/rn4msf4.png
