### ISSUE TITLE
The message keeps telling me that my style color should be blue, I changed it to blue and still nothing happen.

### ISSUE THREAD

**Issue by DoneishaF** [FreeCodeCamp/FreeCodeCamp#9992]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%0A%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%20%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2 {color: blue;} 
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by dwd2010** [comment]
@DoneishaF, there suppose to have h2 element. but you deleted h2 element.
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by DoneishaF** [comment]
it said to : Delete your h2 element's style attribute and instead create a CSS style element. Add the necessary CSS to turn all h2 elements blue.

So I don't know what I am doing wrong.

**Comment by dwd2010** [comment]
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

**Comment by DoneishaF** [comment]
ugh

**Comment by dwd2010** [comment]
btw this place is not help. but you could ask help at fcc chat room. sorry.

**Comment by guambomb23** [comment]
I have the exact same issue, and I went to the chat room and the told me my code was correct, if it is not correct I do not know where to go for help next

**Comment by mrlazos** [comment]
this is what I entered and it still says the h2 element is supposed to be blue

<style>
  h2 {color: blue;}CatPhotoApp</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
