### ISSUE TITLE
i'm stuck! pls help

### ISSUE THREAD

**Issue by Fiyin-Anne** [FreeCodeCamp/FreeCodeCamp#9993]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr.push(item)%3B%0A%20%20console.log(arr.shift())%3B%20%20%0A%20%20console.log(arr.shift())%3B%0A%20%20return%20arr.shift()%3B%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  arr.push(item);
  console.log(arr.shift());  
  console.log(arr.shift());
  return arr.shift();// Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by dwd2010** [comment]
@Fiyin-Anne 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by Fiyin-Anne** [comment]
the chat room isnt allowing me report my challenge. it keeps saying only for Github users and i am logged in via github!

**Comment by dwd2010** [comment]
@Fiyin-Anne, try log out on gitter then log in.

**Comment by Fiyin-Anne** [comment]
@dwd2010 oh okay. Thank you so much
