### ISSUE TITLE
[beta] Map button redirects to /map instead of opening sidecar for non React routes

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/FreeCodeCamp#9998]
Also Map button doesn't do anything when I'm on `/map`.

**Comment by BerkeleyTrue** [comment]
Yes, those are both expected behaviors. We can't support both the iframe and the react map component. Also, while on map there is no reason to also open the map drawer.

**Comment by raisedadead** [comment]
@bugron can this be closed as resolved?

**Comment by bugron** [comment]
Closed. But in my opinion behavior of the Map button should be the same on every page (except `/map` where there is no need to open the sidecar).

**Comment by raisedadead** [comment]
Umm yeah, I understand, but its technically very costly to do that on the non-react pages. On those pages if we did have a sidecar, clicking the links would mean a redirect request to the server and not the react routes.

While on react pages we can simply render the corresponding challenge after hitting the react routes within the page.

Hence the behavior.

Maybe if in future we have all the pages reactified, we could do this easily. Hope this helps?

**Comment by bugron** [comment]
Sure, I understand. Hopefully, in future this behavior will be changed.
