### ISSUE TITLE
Some issues with map drawer

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/FreeCodeCamp#9999]
**1. Search button is croped in Firefox (47.0.1)**
![](http://i.prntscr.com/a02435dca07b4b44889d7a22676a9af4.png)
![](http://i.prntscr.com/ee4dd87b6a104927b5172e9a29a1cb13.png)
**2. `Esc` key doesn't clear search text input**
**3. There are three scrollbars when Firefox'es search box is opened (see next screenshot)** (I've not reproduced this in Chrome). In prod site everything is OK (only two scrollbars).
![](http://i.prntscr.com/15b62c996a294db282d69da965cb5610.png)
**4. Not sure why but filtering doesn't work as expected.** As you can see in the screenshot above there is only challenge which has the word `hello` in its title. This issue is present in prod site too so either this is an issue both on beta an prod sites or I don't understand how does filtering work.

**Comment by BerkeleyTrue** [comment]
4) filtering is done using a fuzzy search, not a direct regex matching. This was added a couple of months ago.

**Comment by bugron** [comment]
@BerkeleyTrue ah OK, but search results doesn't look relevant to want I wanted to search because it finds lots of challenges and then I have to visually filter challenges that include the word I've searched.

**Comment by BerkeleyTrue** [comment]
@bugron Yes, but that has been live on the site for months and is not relevant to Beta. I suggest opening up a new issue to discuss and see if you can get the author of the fuzzy search to comment.

**Comment by bugron** [comment]
@raisedadead 
![video_2016-07-31_082210](https://cloud.githubusercontent.com/assets/13225220/17274572/80eb12e0-56f8-11e6-9da6-ff3307d69586.gif)

**Comment by raisedadead** [comment]
@bugron you on Windows?

**Comment by bugron** [comment]
@raisedadead Windows 10, Firefox 47.0.1
